### {100}{}{Here is Hilberto.}
{100}{}{这是希尔伯托。}
### {101}{}{You see a man with a bushy mustache. He is wearing a captain's cap.}
{101}{}{你看到一个留着浓密胡子的男人。他戴着上尉帽。}
### {102}{}{Please help me! Rippers attacked the village!}
{102}{}{请帮帮我！开膛手袭击了村庄！}
### {103}{}{The rippers! Hide!}
{103}{}{撕裂者！隐藏}
### {104}{}{It's the rippers! Run!}
{104}{}{是撕裂者！跑}
### {105}{}{Rippers attacked the village!}
{105}{}{开膛手袭击了村庄！}
### {106}{}{Save yourself who can! Rippers are everywhere!}
{106}{}{谁能救你自己！到处都是开膛手！}
### {107}{}{Hey, get off the table! It's not funny.}
{107}{}{嘿，离开桌子！这一点也不好笑。}

### {200}{}{Hi. My name is Hilberto. I run a fishing club. What brings you to our harbor?}
{200}{}{你好我叫希尔伯托。我经营一家钓鱼俱乐部。是什么把你带到我们的港口？}
### {201}{}{Hi, Gilberto. I'm passing through here and I need a bed for the night.}
{201}{}{你好，吉尔伯托。我要经过这里，需要一张床过夜。}
### {202}{}{Passing through? It's a strange thing. Tell me about it later. In the meantime, you can stay in the village, but be careful - we have been restless lately.}
{202}{}{通过？这是一件奇怪的事情。稍后再告诉我。在此期间，你可以留在村里，但要小心——我们最近一直很不安。}
### {203}{}{Then I'll take a look around, if you don't mind. See you later.}
{203}{}{如果你不介意的话，我会四处看看。回头见。}
### {204}{}{What happened?}
{204}{}{发生了什么？}
### {205}{}{What's going on here?}
{205}{}{这是怎么回事？}
### {206}{}{I'm on a mission for the Brotherhood of Steel. This does not apply to you.}
{206}{}{我为钢铁兄弟会执行任务。这不适用于您。}
### {207}{}{Then welcome! But be careful - we have been restless lately.}
{207}{}{那么欢迎！但要小心，我们最近一直坐立不安。}
### {208}{}{I'll take a look around, if you don't mind. See you later.}
{208}{}{如果你不介意的话，我会四处看看。回头见。}
### {209}{}{What did you warn me against?}
{209}{}{你警告我不要做什么？}

### {210}{}{What can I do for you?}
{210}{}{我能为你做什么？}
### {211}{}{It's good to see you.}
{211}{}{很高兴见到你。}
### {212}{}{How long are you going to be here for?}
{212}{}{你要在这里呆多久？}
### {213}{}{See you later, Gilberto.}
{213}{}{回头见，吉尔伯托。}

### {220}{}{Can you tell me about this place?}
{220}{}{你能告诉我这个地方的情况吗？}
### {221}{}{This is a fishing settlement. We occupied an old pier and repaired several boats to go fishing. That's all.}
{221}{}{这是一个捕鱼定居点。我们占据了一个旧码头，修理了几艘船去钓鱼。仅此而已。}
### {222}{}{Yourself? Just came and fixed it? I can't believe that a group of fishermen understood the old technology.}
{222}{}{你自己刚来修的？我真不敢相信一群渔民竟然懂得这项古老的技术。}
### {223}{}{I see.}
{223}{}{我明白了。}
### {224}{}{Well, not really. We are patronized by the order, which is located in Puerto Penasco. In exchange for seafood, he provides us with everything we need.}
{224}{}{嗯，不是真的。我们受到订单的光顾，该订单位于佩纳斯科港。作为海鲜的交换，他为我们提供了所需的一切。}
### {225}{}{Can you tell us more about the platform?}
{225}{}{你能告诉我们更多关于这个平台的信息吗？}
### {226}{}{A man-made structure in the middle of the sea. It has been there since time immemorial.}
{226}{}{海中央的人造建筑。它自古以来就在那里。}
### {227}{}{Why was it built?}
{227}{}{为什么要建造它？}
### {228}{}{It seems that oil was extracted from the seabed there. But I do not know why it is needed. Although it burns pretty well.}
{228}{}{石油似乎是从那里的海底提取的。但我不知道为什么需要它。虽然它烧得很好。}
### {229}{}{I see. That's all I was interested in.}
{229}{}{我明白了。这就是我感兴趣的全部。}
### {230}{}{How can I get there?}
{230}{}{我怎样才能到那里？}
### {231}{}{By boat, of course. Ask the pescadores on the pier.}
{231}{}{当然是坐船。问问码头上的小贩。}
### {232}{}{Where is Puerto Penasco?}
{232}{}{佩纳斯科港在哪里？}
### {233}{}{About 50 miles to the south. Walk along the shore, you won't miss.}
{233}{}{往南大约50英里。沿着海岸走，你不会错过的。}

### {250}{}{We are suffering an environmental disaster. As if the sea itself punishes fishermen and peasants for the mistakes of our ancestors!}
{250}{}{我们正在遭受一场环境灾难。就好像大海本身惩罚了渔民和农民，因为他们犯了我们祖先的错误！}
### {251}{}{What are you talking about?}
{251}{}{你在说什么？}
### {252}{}{Take a closer look at the sea. Do you see a platform on the horizon there? It looks like black oily stuff is draining from it directly onto the water. It doesn't smell great at all, and marine life is dying from it at a terrible speed. This has happened before, but lately it has become quite unbearable.}
{252}{}{仔细看看大海。你看到地平线上有站台吗？看起来黑色的油性物质正从里面直接排到水上。它闻起来一点也不香，海洋生物正以可怕的速度死于它。这种情况以前也发生过，但最近变得非常难以忍受。}
### {253}{}{Is it that bad?}
{253}{}{有那么糟糕吗？}
### {254}{}{At first we were delighted to see the coast littered with corpses - just come and take as many as you want. But all these animals are poisoned. Some of our people are still suffering from the poison. And I'm not sure that they will recover at all.}
{254}{}{起初，我们很高兴看到海岸上到处都是尸体——来吧，想带走多少就带走多少。但是所有这些动物都中毒了。我们的一些人仍在遭受这种毒药的折磨。我也不确定他们是否会康复。}
### {255}{}{What kind of poison is this?}
{255}{}{这是什么毒药？}
### {256}{}{I think this is what used to be called "oil" and was extracted from the bottom of the sea. But I do not know what it is. In any case, you need to stop the leak. We will pay 1000 caps to the daredevil who decides to go to the platform and do it.}
{256}{}{我认为这就是过去所说的“石油”，是从海底提取的。但我不知道它是什么。无论如何，你需要停止泄漏。我们将支付1000个瓶盖给决定去平台做这件事的冒险家。}
### {257}{}{So what's the problem?}
{257}{}{那么问题出在哪里呢？}
### {258}{}{We have been bypassing the platform for a long time. Some flying animals have built their nest there and are not allowed to approach it. Several fishermen have already tried to break through there with a fight. Some came back, others died. But if we don't stop the pollution of the sea, then we will have nothing to eat.}
{258}{}{我们已经绕过这个平台很长时间了。一些会飞的动物在那里筑巢，不允许靠近。一些渔民已经试图通过打斗来突破那里。有些人回来了，有些人死了。但是，如果我们不停止对海洋的污染，那么我们就没有吃的了。}
### {259}{}{I'll think about your offer. But I'll need a boat.}
{259}{}{我会考虑你的报价。但我需要一艘船。}
### {260}{}{What are you! I can't even swim. I hope you find someone for this assignment.}
{260}{}{你是什么！我甚至不会游泳。我希望你能为这项任务找到合适的人选。}
### {261}{}{Thank you. You give me hope. And about the boat, talk to the pescadores on the pier.}
{261}{}{非常感谢。你给了我希望。关于船的事，和码头上的小贩谈谈。}
### {262}{}{Okay.}
{262}{}{可以}
### {263}{}{What about the Brotherhood of Steel? Why not ask them for help?}
{263}{}{钢铁兄弟会呢？为什么不向他们寻求帮助呢？}
### {264}{}{The brotherhood? Ha! They would rather give a hand to cut off than allow the destruction of ancient technologies. I think the order hopes to restore this platform. But until he deals with the problems in the east, he will not have enough strength for the platform. That is, we will have to wait for their help for a long time.}
{264}{}{兄弟情谊？哈他们宁愿放手切断，也不愿允许破坏古老的技术。我认为该命令希望恢复这个平台。但在他处理好东部的问题之前，他将没有足够的力量来支持这个平台。也就是说，我们将不得不等待他们的帮助很长一段时间。}
### {265}{}{Clearly.}
{265}{}{清晰地}

### {270}{}{All patients returned to normal. The poison no longer torments them.}
{270}{}{所有患者均恢复正常。毒药不再折磨他们。}
### {271}{}{Thank you on behalf of the whole village!}
{271}{}{代表全村感谢您！}
### {272}{}{You're welcome.}
{272}{}{不客气。}
### {273}{}{You don't think it was free, do you?}
{273}{}{你不认为它是免费的，是吗？}
### {274}{}{Did we negotiate the payment? However, you probably spent some medicines. Here, take 40 caps for each patient. Thanks again.}
{274}{}{我们协商付款了吗？然而，你可能花了一些药。在这里，为每位患者取40个瓶盖。再次感谢。}
### {1274}{}{Did we negotiate the payment? However, you probably spent some medications. Here, take 40 caps for each patient. Thanks again.}
{1274}{}{我们协商付款了吗？然而，你可能花了一些药物。在这里，为每位患者取40个瓶盖。再次感谢。}
### {275}{}{Well, that's another thing.}
{275}{}{好吧，那是另一回事。}

### {280}{}{Viva! You succeeded! The whole village was watching you from the shore. Now the sea will be more merciful to us. Thank you, amigo. We are eternally indebted to you. Here are 1000 caps. We collected this award to the one who could cope with our problem. She's yours now.}
{280}{}{Viva！你成功了！全村人都在岸边看着你。现在大海会对我们更加仁慈。谢谢你，朋友。我们永远感激你。这里有1000个瓶盖。我们把这个奖颁给了能解决我们问题的人。她现在是你的了。}
### {281}{}{Keep the caps for yourself. I didn't do it for the caps, but for the sake of ordinary people in trouble. How my Villa once got into it.}
{281}{}{瓶盖自己留着。我这样做不是为了瓶盖，而是为了陷入困境的普通人。我的别墅是怎么进去的。}
### {282}{}{You really are an amazing person.}
{282}{}{你真是个了不起的人。}
### {283}{}{Goodbye, Gilberto. It's time for me to go.}
{283}{}{再见，吉尔伯托。我该走了。}
### {284}{}{Well, if you insist, you'll have to take these bottlecaps.}
{284}{}{好吧，如果你坚持的话，你就得把这些瓶子拿走。}
### {285}{}{Drop by if you're around. You're always welcome here.}
{285}{}{如果你在附近，顺便来看看。这里永远欢迎你。}
### {286}{}{Goodbye, Cap. It's time for me to go.}
{286}{}{再见，上尉。我该走了。}

### {290}{}{Listen, you're on your way from Puerto, aren't you? We know that there was an explosion there, and after that communication with the order stopped.}
{290}{}{听着，你正在从波多黎各来的路上，是吗？我们知道那里发生了爆炸，之后与订单的沟通停止了。}
### {291}{}{The Order went to the bottom to feed the six-eyed fish.}
{291}{}{骑士团到海底去喂六眼鱼。}
### {292}{}{That's how... And you don't really appreciate them, do you? To be honest, we weren't ready to kiss them passionately either. But they helped us in exchange for fish. Without them, you know, it will be hard. Well, we've lived well for a while, now let's do survival again.}
{292}{}{这就是为什么...你并不是真的很欣赏他们，是吗？老实说，我们也没有准备好热情地亲吻他们。但他们帮助我们换取了鱼。没有他们，你知道，这将是困难的。好吧，我们已经过了一段时间了，现在让我们重新开始生存吧。}
### {293}{}{Freedom is more precious to me than life under someone's oppression. I hope you will understand this now too. Happen.}
{293}{}{对我来说，自由比在别人压迫下的生命更珍贵。我希望你现在也能理解这一点。发生}
### {294}{}{I didn't think of that. I am very sorry that it happened.}
{294}{}{我没想到。我对事情的发生感到非常抱歉。}
### {1294}{}{I didn't think about it. I'm really sorry about what happened.}
{1294}{}{我没想过。发生的事我真的很抱歉。}
### {295}{}{I? No, I haven't been there and I don't know anything about the explosion.}
{295}{}{我不，我没有去过那里，我对爆炸一无所知。}
### {1295}{}{I? No, I wasn't there and I don't know anything about the explosion.}
{1295}{}{我不，我当时不在，我对爆炸一无所知。}
### {296}{}{Really? Okay, I'm not going to ask how you managed to get here, bypassing the only settlement on the way. I just want to say that if the Brotherhood is no more, then we will have a hard time here. After all, they helped us in exchange for fish.}
{296}{}{真正地好吧，我不想问你是如何绕过路上唯一的定居点来到这里的。我只想说，如果兄弟会不复存在，那么我们在这里的日子会很难过。毕竟，他们用鱼来交换我们。}
### {297}{}{I think now you will feel the beauty of freedom. You'll like it.}
{297}{}{我想现在你会感受到自由之美。你会喜欢的。}
### {298}{}{I'm really sorry about what happened.}
{298}{}{我对所发生的事情感到非常抱歉。}
{299}{}{}

### {300}{}{I'm going to Inferno on a mission from the Brotherhood. What do you know about this place?}
{300}{}{我要去地狱执行兄弟会的任务。你对这个地方了解多少？}
### {301}{}{A lost place. That's why it's called Inferno.}
{301}{}{一个失落的地方。这就是为什么它被称为地狱。}
### {302}{}{Have you been there?}
{302}{}{你去过那里吗？}
### {303}{}{I haven't been there myself. But some brave souls went in search of useful things. The Brotherhood of Steel pays handsomely for pre-war relics. But life is more expensive, you know. The only one who has been there and returned is the bartender, he should be at the club now. Talk to him.}
{303}{}{我自己还没去过那里。但是一些勇敢的人去寻找有用的东西。钢铁兄弟会为战前文物支付了丰厚的费用。但是生活更昂贵，你知道的。唯一一个去过那里并回来的是酒保，他现在应该在俱乐部了。和他谈谈。}
### {304}{}{I'll talk to him when I'm done with you.}
{304}{}{等我和你分手了，我再和他谈谈。}
### {305}{}{OK, thanks.}
{305}{}{好的，谢谢。}

### {310}{}{The Brotherhood of Steel is talking about a settlement on the other side. What do you know about him?}
{310}{}{钢铁兄弟会正在讨论另一方面的解决方案。你对他了解多少？}
### {311}{}{We don't swim that far. But it may be true. Some saw lights on the other side with binoculars. If people live there, they probably suffer from loneliness.}
{311}{}{我们不会游那么远。但这可能是真的。有些人用双筒望远镜看到了另一边的灯光。如果人们住在那里，他们可能会感到孤独。}
### {312}{}{Looks like I'll have to go there myself to find out.}
{312}{}{看来我得亲自去看看。}
### {1312}{}{Looks like I'll have to go there myself to find out.}
{1312}{}{看来我得亲自去看看。}

### {320}{}{Besides the platform, what else can you do here?}
{320}{}{除了站台，你还能在这里做什么？}
### {321}{}{Well, someone is stealing fish caches and nets along the shore. I think it's some kind of beast from the wasteland. But it has not been possible to catch him yet. If you find out who is doing this, I will pay 50 caps.}
{321}{}{嗯，有人在岸边偷鱼窝和渔网。我认为这是某种来自荒原的野兽。但现在还没能抓到他。如果你发现是谁干的，我会支付50个瓶盖。}
### {322}{}{Agreed. I'll find this thief.}
{322}{}{同意。我会找到这个小偷的。}
### {323}{}{This is not enough. Look for a fish lover yourself.}
{323}{}{这还不够。自己找一个爱鱼的人。}
### {324}{}{I know what kind of creature was ruining your networks.}
{324}{}{我知道是什么生物在破坏你的网络。}
### {325}{}{Really? And who is it?}
{325}{}{真正地是谁？}
### {326}{}{It was a dead man. During the day he hid in the shadow of the lighthouse, and at night he went to the beach in search of fish. Now he's deader than dead.}
{326}{}{那是一个死人。白天他躲在灯塔的阴影里，晚上他去海滩找鱼。现在他死得比死还惨。}
### {327}{}{Was it the Ripper from Inferno? Oh, Holy Mary, that's not enough yet!}
{327}{}{是来自地狱的开膛手吗？哦，圣母玛利亚，这还不够！}
### {328}{}{Inferno? What is it?}
{328}{}{无法控制的大火它是什么？}
### {329}{}{Burnt ruins in the northwest. Who has been there, tells about the locals, disfigured by radiation beyond recognition. This place turns people into monsters and takes away their sanity. We avoid Inferno. But the Rippers never came here either. They probably don't like the fresh sea air.}
{329}{}{西北部被烧毁的废墟。谁去过那里，告诉当地人，他们被辐射毁容得面目全非。这个地方把人变成怪物，夺走了他们的理智。我们避开地狱。但是开膛手也从来没有来过这里。他们可能不喜欢新鲜的海洋空气。}
### {330}{}{However, this one got here somehow.}
{330}{}{然而，这一个不知怎么来到了这里。}
### {331}{}{Perhaps something forced him to leave his native ruins. I hope the others won't follow him. Oh yes, here are your 50 caps. Thank you.}
{331}{}{也许是什么原因迫使他离开了家乡的废墟。我希望其他人不要跟着他。哦，是的，这是你的50个瓶盖。非常感谢。}
### {332}{}{Good luck, Gilberto.}
{332}{}{祝你好运，吉尔伯托。}
### {333}{}{Inferno? Yes, most likely he was from there.}
{333}{}{无法控制的大火是的，他很可能是从那里来的。}
### {334}{}{Is there any small job?}
{334}{}{有什么小工作吗？}
### {335}{}{It was a dead man. During the day he hid in the shadow of the lighthouse, and at night he went to the beach in search of fish. I managed to drive him out of the Black Lagoon.}
{335}{}{那是一个死人。白天他躲在灯塔的阴影里，晚上他去海滩找鱼。我设法把他赶出了黑湖。}
### {336}{}{Perhaps something forced him to leave his native ruins. I hope the others won't follow him. That's just not an invention, is it? I'm not ready to pay 50 caps for bare words, I'm sorry. Here are 10 caps so that no one will be offended.}
{336}{}{也许是什么原因迫使他离开了家乡的废墟。我希望其他人不要跟着他。这不是一项发明，是吗？对不起，我还没有准备好为裸言支付50个瓶盖。这里有10个瓶盖，这样就不会冒犯任何人。}
### {337}{}{You can be understood. Thanks for the 10 caps.}
{337}{}{你可以被理解。谢谢你的10个瓶盖。}
### {338}{}{You bastard, you're going to pay for your deception!}
{338}{}{你这个混蛋，你要为你的欺骗付出代价！}

### {340}{}{What's new in this village?}
{340}{}{这个村子有什么新鲜事？}
### {341}{}{The news is not joyful. The Brotherhood of Steel is no longer with us. Something exploded on their ship, and now we are on our own. I don't know how we will get out of this old technology without them.}
{341}{}{这个消息并不令人高兴。钢铁兄弟会已经不在我们身边了。他们的船上发生了爆炸，现在我们只能靠自己了。我不知道如果没有他们，我们将如何摆脱这种旧技术。}
### {342}{}{I see. Anything else?}
{342}{}{我明白了。还有别的吗？}
### {343}{}{We have problems with the oil rig and the flyers here. Big problem. And no one can solve it yet.}
{343}{}{我们这里的石油钻井平台和传单有问题。大问题。现在还没有人能解决这个问题。}
### {344}{}{Things are getting better! The oil rig no longer pollutes the water. I think in a few weeks the sea waters will start to delight us with fresh fish again.}
{344}{}{情况正在好转！石油钻井平台不再污染水。我想几周后，海水会再次让我们喜欢上新鲜的鱼。}
### {345}{}{But things got a lot better at sea. }
{345}{}{但海上的情况好多了。}
### {346}{}{Ruiz is obsessed with finding the treasure. Which is not. Hehe. Don't fall for his bait, amigo.}
{346}{}{鲁伊斯痴迷于寻找宝藏。事实并非如此。呵呵。别上当了，朋友。}
### {347}{}{Ruiz has disappeared somewhere. And I don't want to look for him.}
{347}{}{鲁伊斯在某处失踪了。我不想找他。}
### {348}{}{It looks like Ruiz has finally found the treasure he was looking for. Who would have thought that the treasure really exists?}
{348}{}{看起来鲁伊斯终于找到了他一直在寻找的宝藏。谁会想到宝藏真的存在？}
### {349}{}{Sometimes the sea shows us unusual phenomena. Then some monster will appear out of the water, then the other shore is illuminated by light. But we don't usually swim that far. There's nothing to do there.}
{349}{}{有时大海会向我们展示不同寻常的现象。然后一些怪物会出现在水面上，然后另一边的海岸被灯光照亮。但我们通常不会游那么远。那里没有什么可做的。}
### {350}{}{It turns out that there was a whole settlement on the other side, and we didn't even know about it! Although the guys there don't look particularly cheerful.}
{350}{}{事实证明，在另一边有一个完整的定居点，我们甚至不知道！尽管那里的人看起来不是特别高兴。}
### {351}{}{Some saw a strange greenish glow from the side of the destroyed lighthouse. But it's ruined. Where does the light come from there?}
{351}{}{有些人从被毁的灯塔边上看到一道奇怪的绿光。但它毁了。光从哪里来？}
### {352}{}{After we found the dead man near the lighthouse, people began to be afraid to go in that direction. What if other zombies come here from Inferno?}
{352}{}{当我们在灯塔附近发现死者后，人们开始害怕往那个方向走。如果其他僵尸从地狱来到这里呢？}
### {353}{}{And there are no more stories. Our town is small and boring.}
{353}{}{没有更多的故事了。我们的小镇又小又无聊。}
### {354}{}{Clearly. Then let's change the subject.}
{354}{}{清晰地那我们换个话题吧。}
### {355}{}{I see. well, then have a good stay.}
{355}{}{我明白了。好吧，那就祝你住得愉快。}
### {356}{}{Ruiz has been pretty angry lately. I don't know what happened.}
{356}{}{鲁伊斯最近很生气。我不知道发生了什么。}

### {360}{}{Bad news. Someone strangled a teenager at the lighthouse.}
{360}{}{坏消息。有人在灯塔勒死了一名少年。}
### {361}{}{This is VERY bad news! We're going there now...}
{361}{}{这是个非常坏的消息！我们现在要去那里...}
### {362}{}{Okay.}
{362}{}{可以}
### {363}{}{Hey, let's agree right away that I have nothing to do with it. Is it clear?}
{363}{}{嘿，让我们马上同意我与此事无关。清楚了吗？}
### {364}{}{God, poor Johnny! Who could have done it?}
{364}{}{天啊，可怜的强尼！谁能做到呢？}
### {365}{}{Tell me about Johnny.}
{365}{}{告诉我关于强尼的事。}
### {366}{}{He moved here with his parents three years ago. The parents died at sea when the boat capsized. But Johnny was not discouraged. He was such a good boy! He worked tirelessly to provide for himself.}
{366}{}{三年前，他和父母搬到了这里。船倾覆时，父母在海上遇难。但强尼并没有气馁。他真是个好孩子！他不知疲倦地工作以养活自己。}
### {367}{}{Does he have any relatives?}
{367}{}{他有亲戚吗？}
### {368}{}{Only Uncle Tin. He moved recently by an invitation letter that Johnny sent to Phoenix after the death of his parents. Tin is a little weird. He often spends time on the shore trying to catch a fish, although there is only garbage floating here. I don't know how to tell him what happened. As soon as the relatives were united, fate separated them again. It's so sad.}
{368}{}{只有丁叔。最近，约翰尼在父母去世后给凤凰城发了一封邀请函，这让他感动不已。锡有点奇怪。他经常在岸边钓鱼，尽管这里只有漂浮的垃圾。我不知道该怎么告诉他发生了什么事。亲人们一团聚，命运又把他们分开了。太令人难过了。}
### {369}{}{Any idea why he might have been killed?}
{369}{}{知道他为什么会被杀吗？}
### {370}{}{Well, Johnny didn't have any enemies. And there was no point in robbing him.}
{370}{}{嗯，强尼没有任何敌人。抢劫他是没有意义的。}
### {371}{}{What do you say about the piece of rope with which he was strangled?}
{371}{}{你觉得他被勒死的那根绳子怎么样？}
### {372}{}{Hmm, exactly the same rope Ruiz uses in his craft. But this piece looks pretty fresh, as if it was only recently taken out of the warehouse.}
{372}{}{嗯，和鲁伊斯在他的工艺中使用的绳子一模一样。但这件作品看起来很新鲜，好像是最近才从仓库里拿出来的。}
### {373}{}{Well, a thorough investigation is required here. It's not worth spreading yet, so as not to scare off the criminal.}
{373}{}{嗯，这里需要进行彻底的调查。它还不值得传播，以免吓跑罪犯。}
### {374}{}{I want to talk to you about Johnny's murder.}
{374}{}{我想和你谈谈强尼被谋杀的事。}
### {375}{}{Poor Johnny! So did you manage to find the killer?}
{375}{}{可怜的强尼！你找到凶手了吗？}
### {376}{}{No new leads yet. See you later.}
{376}{}{还没有新的线索。回头见。}
### {377}{}{Where were you at the time of the murder?}
{377}{}{谋杀发生时你在哪里？}
### {378}{}{I was sleeping in my club!}
{378}{}{我睡在我的俱乐部里！}
### {379}{}{Tell me about him.}
{379}{}{告诉我关于他的事。}
### {380}{}{I talked to Uncle Johnny. He says that only Ruiz has such a rope.}
{380}{}{我和强尼叔叔谈过了。他说只有鲁伊斯有这样一根绳子。}
### {381}{}{That doesn't prove anything. Although Ruiz is always angry, he still has no motive for murder. Try talking to him too.}
{381}{}{这并不能证明什么。尽管鲁伊斯总是很生气，但他仍然没有杀人的动机。试着也和他谈谈。}
### {382}{}{Okay.}
{382}{}{可以}
### {383}{}{The records of Jose Rene Ruiz say that Tin-Tan was the last one to buy his rope.}
{383}{}{Jose Rene Ruiz的记录显示，Tin Tan是最后一个买他的绳子的人。}
### {384}{}{That doesn't prove anything. Tin-Tan is weird, but he's still Johnny's uncle. He has no motive for murder. Try talking to him too.}
{384}{}{这并不能证明什么。谭很奇怪，但他仍然是强尼的叔叔。他没有谋杀的动机。试着也和他谈谈。}
### {385}{}{Okay.}
{385}{}{可以}
### {386}{}{It could be Jose Rene Ruiz. He has that rope. And Tin-Tan. He bought it in the recent past.}
{386}{}{可能是何塞·雷内·鲁伊斯。他有那根绳子。还有谭。他最近才买的。}
### {387}{}{Well, that doesn't prove anything yet. After all, they both have no motive. But that's something. I think we should ask around at the club. Maybe someone knows something about their relationship with Johnny?}
{387}{}{这还不能证明什么。毕竟，他们都没有动机。但这很重要。我想我们应该去俱乐部问问。也许有人知道他们和强尼的关系？}
### {388}{}{Okay.}
{388}{}{可以}
### {389}{}{The real killer is Tin-Tan.}
{389}{}{真正的杀手是田。}
### {390}{}{I remember our conversation. But doesn't he have a motive?}
{390}{}{我记得我们的谈话。但他没有动机吗？}
### {391}{}{To be honest, I don't know what his motive is. I should probably think about it again.}
{391}{}{老实说，我不知道他的动机是什么。我可能应该再想想。}
### {392}{}{He's not who he says he is. Johnny's real uncle died during the trip, and he appropriated his documents. He is a robber.}
{392}{}{他不是他说的那个人。约翰尼的亲生叔叔在旅途中去世了，他盗用了他的文件。他是个强盗。}
### {393}{}{So that's why he was acting like an idiot comedian! He pretended to be a fool so that no one would recognize him as a dangerous person. Sly son of a bitch!}
{393}{}{所以这就是为什么他表现得像个白痴喜剧演员！他假装成一个傻瓜，这样就不会有人认出他是个危险的人。狡猾的婊子养的！}
### {394}{}{He already got what he deserved after he decided to attack me.}
{394}{}{在他决定攻击我之后，他已经得到了他应得的。}
### {395}{}{Wow! You've got nerves of steel. Thanks for the help. We don't need any garbage here. And life is not very good without them.}
{395}{}{哇！你有钢铁般的神经。谢谢你的帮助。我们这里不需要垃圾。没有他们生活就不太好。}
### {396}{}{I hope you feel better now. Good luck.}
{396}{}{我希望你现在感觉好多了。祝你好运}
### {397}{}{That's not the cruelest thing you've ever seen in your life, Cap. Be.}
{397}{}{这不是你一生中见过的最残忍的事，上尉。是}
### {398}{}{It's true. You need to capture him as soon as possible and bring him to justice.}
{398}{}{这是真的。你需要尽快抓住他并将他绳之以法。}
### {399}{}{Thanks for the help. We don't need any garbage here. And life is not very good without them.}
{399}{}{谢谢你的帮助。我们这里不需要垃圾。没有他们生活就不太好。}

