### {100}{}{Thelma is in front of you.}
{100}{}{塞尔玛就在你面前。}
### {101}{}{You see a girl with a sad expression on her face.}
{101}{}{你看到一个女孩脸上带着悲伤的表情。}
### {102}{}{Nice to see you.}
{102}{}{很高兴见到你。}
### {103}{}{Zombies all around! Is this some kind of apocalypse?}
{103}{}{僵尸到处都是！这是某种启示录吗？}

#The first dialog
### {200}{}{Hey, hello, wanderer. It's nice to see a new face in the city. My name is Thelma Ferrino. How are you?}
{200}{}{嗨，你好，流浪者。很高兴在这个城市看到一张新面孔。我的名字叫塞尔玛·费里诺。你好吗}
### {1200}{}{Hey, hello, wanderer. It's nice to see a new face in the city. My name is Thelma Ferrino. How are you?}
{1200}{}{嗨，你好，流浪者。很高兴在这个城市看到一张新面孔。我的名字叫塞尔玛·费里诺。你好吗}
### {201}{}{Just great. And how are you doing?}
{201}{}{太棒了。你过得怎么样？}
### {202}{}{There have been better days. But thanks for asking.}
{202}{}{有更好的日子。但谢谢你的询问。}
### {1202}{}{There have been better days. But thanks for asking.}
{1202}{}{有更好的日子。但谢谢你的询问。}
### {203}{}{Why are you asking?}
{203}{}{你为什么要问？}
### {204}{}{Well, I just want to get to know you. We rarely have guests. Especially now. It used to be busier here.}
{204}{}{我只是想了解你。我们很少有客人。尤其是现在。这里以前更忙。}
### {205}{}{What happened?}
{205}{}{发生了什么？}
### {206}{}{Well, I can tell you if you pour me something refreshing from the bar.}
{206}{}{好吧，我可以告诉你，如果你从酒吧里给我倒点提神的东西。}
### {207}{}{Okay, I'll get something now.}
{207}{}{好吧，我现在就去拿点东西。}
### {208}{}{No booze, se?orita. Adios.}
{208}{}{没有酒，塞诺丽塔。再见。}
### {209}{}{Here are 5 caps for you, take it yourself.}
{209}{}{这里有5个瓶盖给你，你自己拿吧。}
### {210}{}{Muchas gracias!}
{210}{}{Muchas gracias！}
### {211}{}{Now tell me what's going on here.}
{211}{}{现在告诉我这里发生了什么。}
### {212}{}{Well, you've already shared a drink. I think I owe you.}
{212}{}{好吧，你已经喝了一杯了。我想我欠你的。}
### {1212}{}{Well, you've already shared the booze. I think I owe you one.}
{1212}{}{好吧，你已经分享了酒。我想我欠你一个。}
### {213}{}{You're not leaving. Which means you liked it here. Will you keep me company?}
{213}{}{你不会离开的。这意味着你喜欢这里。你愿意陪我吗？}
### {214}{}{And will you tell me about this settlement?}
{214}{}{你能告诉我这个和解方案吗？}
### {215}{}{What is going on here in general and why are you so sad?}
{215}{}{这里总体上发生了什么？你为什么这么难过？}

### {220}{}{It's all because of that damn tower in the Sea of Cortez. It has been there since time immemorial. She didn't have any problems before. The Pescadores even used it for recreation until some flying monsters got there. And recently, some kind of poisonous filth began to drain from this platform. Half the sea is probably already dead because of her.}
{220}{}{这都是因为科尔特斯海那座该死的塔。它自古以来就在那里。她以前没有遇到任何问题。佩斯卡多雷斯人甚至用它来娱乐，直到一些会飞的怪物到达那里。最近，一些有毒的污物开始从这个平台上排出。因为她，半个大海可能已经死了。}
### {221}{}{Did someone die in the settlement too? Is that why you're so sad?}
{221}{}{定居点里也有人死了吗？这就是你如此悲伤的原因吗？}
### {222}{}{When all this became unbearable, my uncle and the other pescadores went to the platform. They knew it was dangerous, but they had to do something.}
{222}{}{当这一切变得难以忍受时，我叔叔和其他的pescadore走到站台上。他们知道这很危险，但他们必须做点什么。}
### {223}{}{What happened there?}
{223}{}{那里发生了什么？}
### {224}{}{I just saw through the binoculars how they went inside. Nothing has been heard of them since. Obviously, they all died. (takes a deep sip straight from the bottle)}
{224}{}{我只是通过双筒望远镜看到他们是怎么进去的。从那以后就再也没有听说过他们。很明显，他们都死了。（直接从瓶子里深深地吸了一口）}
### {225}{}{Sorry. You must have loved your uncle?}
{225}{}{很抱歉你一定爱你的叔叔吧？}
### {226}{}{When you live together in the same boat for so long, everyone becomes family, even if they come from different parts of the wasteland. You know, I would be happy if someone would return his things to me as a keepsake.}
{226}{}{当你在同一条船上生活这么久时，每个人都会成为一家人，即使他们来自荒原的不同地方。你知道，如果有人把他的东西作为纪念品还给我，我会很高兴的。}
### {227}{}{I don't think I'll ever be on this platform. Sorry, but you're in the wrong place.}
{227}{}{我想我永远不会在这个平台上。对不起，你来错地方了。}
### {228}{}{I'll keep that in mind. Cheer up, Thelma.}
{228}{}{我会记住的。振作起来，塞尔玛。}
{229}{}{}

### {230}{}{Hey, hello, wanderer. So it was you who lit the torch right in the middle of the sea? Cool!}
{230}{}{嗨，你好，流浪者。所以是你在海中央点燃了火炬？凉的}
### {1230}{}{Hey, hello, wanderer. So it was you who lit the torch right in the middle of the sea? Cool!}
{1230}{}{嗨，你好，流浪者。所以是你在海中央点燃了火炬？凉的}
### {231}{}{There was a case. Oil won't hurt you anymore. And the flyers, too.}
{231}{}{有一个案例。石油不会再伤害你了。还有传单。}
### {232}{}{Thank you from the bottom of my heart. Have you come across the remains of our pescadores on the platform? My uncle was among them.}
{232}{}{从心底感谢你。你有没有在站台上发现我们的佩萨多雷残骸？我叔叔也在其中。}
### {233}{}{No, I'm sorry. The flyers must have eaten them.}
{233}{}{不，对不起。传单一定吃了它们。}
### {234}{}{I thought so. Well, all right. It's time to come to your senses and get down to business. Now we will have a lot of work again!}
{234}{}{我想是的。好吧。是时候清醒过来，开始做正事了。现在我们将再次有大量的工作！}
### {235}{}{Be.}
{235}{}{是}
### {236}{}{I only came across this token among a pile of bones.}
{236}{}{我只是在一堆骨头中偶然发现了这枚代币。}
### {237}{}{Yes, this is his token! Thank you very much, I will take care of it.}
{237}{}{是的，这是他的代币！非常感谢，我会处理好的。}
### {238}{}{You're welcome.}
{238}{}{不客气。}
### {239}{}{Not so fast. A reward is usually given for such cases.}
{239}{}{没那么快。这种情况通常会得到奖励。}
### {240}{}{I didn't think you'd say that. Maybe that's why you helped us with the platform - to show yourself? Okay, here's my last hundred caps. Is that enough?}
{240}{}{我没想到你会这么说。也许这就是你帮助我们搭建平台的原因——展示自己？好吧，这是我最后一百个瓶盖。够了吗？}
### {1240}{}{I didn't think you'd say that. Maybe that's why you helped us with the platform - to show yourself? Okay, here's my last hundred caps. Is that enough?}
{1240}{}{我没想到你会这么说。也许这就是你帮助我们搭建平台的原因——展示自己？好吧，这是我最后一百个瓶盖。够了吗？}
### {241}{}{Enough. Bye.}
{241}{}{足够地再见}
### {242}{}{On the platform, I came across a token among a pile of bones. Apparently it belonged to your uncle.}
{242}{}{在平台上，我在一堆骨头中发现了一个代币。显然它是你叔叔的。}
### {243}{}{Coincidentally, I just visited the platform and found this token there. Your last name is on it.}
{243}{}{无独有偶，我刚刚访问了平台，在那里发现了这个代币。上面有你的姓氏。}

### {250}{}{Hi.}
{250}{}{你好}
### {251}{}{Bye.}
{251}{}{再见}
### {252}{}{Hi. It's good to see you.}
{252}{}{你好很高兴见到你。}
