### {100}{}{Here is a villager.}
{100}{}{这是一位村民。}
### {101}{}{You see a fisherman with dark skin.}
{101}{}{你看到一个皮肤黝黑的渔夫。}
### {102}{}{You have a sick person in front of you.}
{102}{}{你面前有一个病人。}
### {103}{}{You see a fisherman. He looks exhausted from a long illness.}
{103}{}{你看到一个渔夫。他久病看起来疲惫不堪。}
### {104}{}{Your skills are not enough to cure a patient without special medications.}
{104}{}{你的技能不足以在没有特殊药物的情况下治愈病人。}
### {105}{}{(}
{105}{}{(}
### {106}{}{/3) The patient is on the mend.}
{106}{}{/3） 病人正在好转。}
### {107}{}{I felt better. Thanks, Doc.}
{107}{}{我感觉好多了。谢谢，医生。}

### {110}{}{*Cough-cough*}
{110}{}{*咳嗽*}
### {111}{}{Oh...}
{111}{}{哦}

### {120}{}{*Cough-cough*}
{120}{}{*咳嗽*}
### {121}{}{I'm not feeling well. Are you kidding me?}
{121}{}{我感觉不舒服。你在开玩笑吗？}
### {122}{}{The disease went away as if it had never happened. You're doing wonders, Doc.}
{122}{}{疾病消失了，好像从未发生过一样。你在创造奇迹，医生。}
### {123}{}{Why treat me if you hate this place so much?}
{123}{}{如果你这么讨厌这个地方，为什么要待我？}
