### {100}{}{Lozen is in front of you.}
{100}{}{Lozen就在你面前。}
### {101}{}{You see an old woman in an unusual outfit for her tribe. She mutters something under her breath, probably a spell.}
{101}{}{你可以看到一位老妇人穿着一身不寻常的部落服装。她低声咕哝着什么，可能是咒语。}

### {200}{}{I knew you'd come here someday, villager. A sad story happened to you.}
{200}{}{我就知道你总有一天会来这里的，村民。一个悲伤的故事发生在你身上。}
### {201}{}{How do you know?}
{201}{}{你怎么知道的？}
### {202}{}{I see a lot, the blood of a sacred animal tells me about it. My name is Lozen.}
{202}{}{我经常看到，一种神圣动物的血液告诉我这件事。我叫洛赞。}
### {203}{}{So you're guessing on the blood of a brahmin, or something?}
{203}{}{你猜的是婆罗门的血还是什么？}
### {204}{}{I see the future and the past. Call it whatever you want. Show me your hands, I'll look at your future.}
{204}{}{我看到了未来和过去。你想怎么称呼它就怎么称呼它。让我看看你的手，我会看看你的未来。}
### {205}{}{Well, no.}
{205}{}{嗯，没有。}
### {206}{}{Okay, look.}
{206}{}{好吧，看。}
### {207}{}{Hmm... Big changes are coming. And I see you will be in the very center of them. But I need to perform a full rite to find out the details.}
{207}{}{嗯…大的变化即将到来。我看到你会站在他们中间。但我需要做一个完整的仪式来了解细节。}
### {208}{}{Maybe another time.}
{208}{}{也许改天吧。}
### {209}{}{Okay, I'm taking the bait. What is needed for this?}
{209}{}{好吧，我上当了。这需要什么？}
### {210}{}{You need to part with something that is valuable to you. You can even give away the bottlecaps. Only in the sense of loss are revealed the most intimate lines of life.}
{210}{}{你需要放弃一些对你有价值的东西。你甚至可以把水瓶送人。只有在失落的感觉中，才显露出生命中最亲密的线条。}
### {211}{}{Here are 100 caps. Tell me, I want to know everything!}
{211}{}{这里有100顶帽子。告诉我，我想知道一切！}
### {212}{}{Maybe another time.}
{212}{}{也许改天吧。}
### {213}{}{(performs a complex ritual on the blood of a sacred animal) Um-m-m... Om-m-m... I'm starting to see... yes...}
{213}{}{（对神圣动物的血液进行复杂的仪式）嗯。。。Om-m。。。我开始看到。。。对}
### {214}{}{What do you see?}
{214}{}{你看到了什么？}
### {215}{}{I see people with a star in their forehead... And people who generate fire with the power of thought, opposite them... They want to destroy each other, and you are between them. Right in the line of fire...}
{215}{}{我看到人们额头上有一颗星星。。。而那些用思想的力量产生火焰的人，与他们相对。。。他们想摧毁彼此，而你却夹在他们中间。就在火线上。。。}
### {216}{}{Not very happy about it.}
{216}{}{对此不太高兴。}
### {217}{}{But the Divine Brahmin will not let you die in this battle. You have your own way! Don't let yourself be fooled! A great mission awaits you! Great!!!}
{217}{}{但是神圣的婆罗门不会让你在这场战斗中死去。你有自己的路！不要让自己上当受骗！伟大的使命在等着你！太棒了}
### {218}{}{Ugh, it was quite stressful. But how to understand all this?}
{218}{}{啊，压力很大。但如何理解这一切呢？}
### {219}{}{You're lying to me! This is no vision of the future.}
{219}{}{你在骗我！这不是对未来的展望。}
### {220}{}{Think about what I'm saying! The Divine Brahmin does not give direct instructions, he only indicates images, they need to be able to read. Maybe it's not time yet. When your heart and mind open up, you will understand it.}
{220}{}{想想我在说什么！神圣的婆罗门没有给出直接的指示，他只指示图像，他们需要能够阅读。也许现在还不是时候。当你敞开心扉，你就会明白。}
### {221}{}{Everything is clear with you. I just wasted the bottlecaps. Later.}
{221}{}{你一切都很清楚。我只是浪费了瓶子。后来}
### {1221}{}{Everything is clear with you. I just wasted the bottlecaps. Bye.}
{1221}{}{你一切都很清楚。我只是浪费了瓶子。再见}
### {222}{}{Thank you, Lozen. Your words inspire me to continue my journey.}
{222}{}{谢谢你，洛岑。你的话激励我继续我的旅程。}
### {223}{}{You're back. I see fate is bothering you. I can find out what's waiting for you if you want.}
{223}{}{你回来了。我知道命运在困扰着你。如果你愿意的话，我可以找到等你的是什么。}
### {1223}{}{You're back. I see fate is bothering you. I can find out what awaits you if you want.}
{1223}{}{你回来了。我知道命运在困扰着你。如果你愿意的话，我可以找到等待你的是什么。}
### {224}{}{No, thanks, no need.}
{224}{}{不，谢谢，没必要。}

### {240}{}{I have nothing more to say to you.}
{240}{}{我没有什么要对你说的了。}
### {241}{}{Okay. Goodbye.}
{241}{}{可以再见}
### {242}{}{And yet - how to understand your vision?}
{242}{}{然而，如何理解你的愿景？}
### {243}{}{What happened to the brahmin whose blood you use?}
{243}{}{你用血的婆罗门怎么了？}
### {244}{}{A sacred animal. Genaro is preparing him for the celebration of the Day of the Sun. On this day, the animal is sacrificed, and its sacred blood is washed away from failure and shame. I use blood for divination to see our possible future and convey it to the rest of the residents.}
{244}{}{神圣的动物。Genaro正在为庆祝太阳日做准备。在这一天，动物被献祭，它神圣的血液被从失败和耻辱中冲走。我用血占卜，看看我们可能的未来，并将其传达给其他居民。}
### {245}{}{What kind of holiday is this?}
{245}{}{这是什么样的假期？}
### {246}{}{When the Sonoran desert is closed by sandstorms, pastoralists cannot go out to graze Brahmins. They're waiting out the storm season here in Pueblo. These days, when we have enough food supplies, we thank the Divine Brahmin for our salvation.}
{246}{}{当索诺兰沙漠被沙尘暴封闭时，牧民不能外出放牧婆罗门。他们在普韦布洛等着暴风雨季节结束。这些天，当我们有足够的食物供应时，我们感谢神圣的婆罗门拯救了我们。}
### {247}{}{What is a sacred animal? Is it any different from the others?}
{247}{}{什么是神圣的动物？它和其他的有什么不同吗？}
### {248}{}{A brahmin with the highest fortitude. Genaro keeps him in a separate pen to avoid any risks and allow the brahmin to live until the Day of the Sun. The death or infirmity of such an animal would be a tragedy for us.}
{248}{}{具有最高毅力的婆罗门。Genaro把他关在一个单独的围栏里，以避免任何风险，并允许婆罗门活到太阳日。这种动物的死亡或虚弱对我们来说将是一场悲剧。}
### {249}{}{Don't you feel sorry for this sacred animal?}
{249}{}{你不为这个神圣的动物感到难过吗？}
### {250}{}{Don't talk nonsense! Brahmins sacrifice themselves for us humans. Genaro chooses one of the Brahmins and feeds him especially hard for a whole year. A whole year of clean, well-fed, happy life to die in one day and give the whole tribe redemption. A worthy fate for an animal.}
{250}{}{别胡说八道！婆罗门为我们人类牺牲自己。Genaro选择了一个婆罗门，并特别努力地喂养了他一整年。整整一年干净、营养充足、幸福的生活，在一天内死去，给整个部落救赎。对动物来说，这是一个有价值的命运。}
### {251}{}{What future do you see for your tribe?}
{251}{}{你认为你们部落的未来会怎样？}
### {252}{}{We are standing between a rock and a precipice in the fog. It's hard to see anything.}
{252}{}{我们站在雾中的岩石和峭壁之间。很难看到任何东西。}
### {253}{}{Interesting.}
{253}{}{有趣的}
