### {100}{}{Here is the priest Mangas.}
{100}{}{这是曼加斯牧师。}
### {101}{}{You see a shaman in a national outfit.}
{101}{}{你可以看到一个穿着民族服装的萨满。}
### {102}{}{Look! That evil iron spirit! Do you believe me now?}
{102}{}{看那个邪恶的铁精灵！你现在相信我了吗？}
### {103}{}{Old man Mangas is completely out of his mind!}
{103}{}{曼加斯老人完全疯了！}

#Floating phrases on the square
### {110}{}{Drive the outsiders away!}
{110}{}{把外人赶走！}
### {111}{}{Outsiders are dividing our tribe!}
{111}{}{外来者正在分裂我们的部落！}
### {112}{}{Look what these outsiders are doing to our community!}
{112}{}{看看这些外来者对我们的社区做了什么！}
### {113}{}{We have kept traditions for so many generations not for outsiders to destroy them!}
{113}{}{我们保留了这么多代人的传统，而不是让外人来破坏它们！}
### {114}{}{Now there are dissenters among us. What will it lead to?}
{114}{}{现在我们中间有持不同意见的人。这会导致什么？}
### {115}{}{The tribe is once again on the path of enmity. And it's all because of the Phoenix.}
{115}{}{这个部落再次走上了敌对的道路。这都是因为凤凰。}
### {116}{}{We were one, but Phoenix taught us to argue over nothing!}
{116}{}{我们是一体的，但菲尼克斯教会了我们什么都不要争论！}
### {117}{}{Look at Chatto and his comrades. There is no way to fix them!}
{117}{}{看看查特和他的战友们。没有办法修复它们！}
### {118}{}{Chatto learned to read from the caravaneers. And what will happen next?}
{118}{}{查特是从马车夫那里学会读书的。接下来会发生什么？}
### {119}{}{It will get worse! Phoenix won't give us the wasteland. Aaron needs everything!}
{119}{}{情况会变得更糟！凤凰不会给我们荒地。亚伦需要一切！}
### {120}{}{Because of the missionaries, we can't even gather in the wasteland to graze Brahmins.}
{120}{}{因为传教士的缘故，我们甚至不能聚集在荒地上放牧婆罗门。}
### {121}{}{Bring all the things of the pagans here! Burn them! Burn!}
{121}{}{把异教徒的东西都带过来！烧了他们！燃烧}
### {122}{}{Look at these books and technologies - do we really need this?}
{122}{}{看看这些书和技术，我们真的需要这些吗？}
### {123}{}{Phoenix promises only deception!}
{123}{}{凤凰只承诺欺骗！}
### {124}{}{Don't fall for the tricks of the missionaries!}
{124}{}{不要上当传教士的把戏！}
### {125}{}{Cover your ears when the missionaries explain something to you.}
{125}{}{当传教士向你解释某事时，请捂住耳朵。}
### {126}{}{We've lived here for generations! We will not give our land to strangers!}
{126}{}{我们在这里住了好几代人！我们不会把我们的土地让给陌生人！}

#Stop-dialogue about the bike
### {200}{}{Here! That's what I was talking about! Outsiders have conquered iron! Playing God, they resurrected old technologies and subordinated them to their will. And what's next? Will they subdue our bodies and souls?}
{200}{}{在这里我就是这么说的！局外人征服了铁！他们扮演上帝，复活了旧技术，并将其服从于他们的意志。接下来是什么？他们会征服我们的身体和灵魂吗？}
### {201}{}{Don't worry so much. This is my personal transport. He's not threatening you.}
{201}{}{别那么担心。这是我的私人交通工具。他没有威胁你。}
### {202}{}{Do not believe the words of a stranger! Who knows what's on the mind of someone who goes against nature.}
{202}{}{不要相信陌生人的话！谁知道一个违背自然的人在想什么。}
### {203}{}{Be simple, you're driving too hard.}
{203}{}{简单点，你开得太猛了。}
### {204}{}{In my opinion, you smoked the wrong herb, shaman.}
{204}{}{在我看来，你抽错了草药，萨满。}
### {205}{}{Calm down, old man. I haven't done anything wrong to you. NOT done YET.}
{205}{}{冷静点，老人。我没有对你做任何错事。还没有完成。}
### {1205}{}{Calm down, old man. I haven't done anything wrong to you. I haven't done it YET.}
{1205}{}{冷静点，老人。我没有对你做任何错事。我还没做。}

#First meeting
### {210}{}{...Here, look what these advanced people have brought us with all their progress!}
{210}{}{……在这里，看看这些先进人物的进步给我们带来了什么！}
### {211}{}{[Listen to speech]}
{211}{}{[听演讲]}
### {212}{}{[Interrupt speech]}
{212}{}{[中断语音]}
### {213}{}{We were a close-knit community, but the fire worshippers brought us selfishness! We believed in one god, but they taught us to argue about religion! We wanted to do good to our fellow tribesmen, but the clans have once again entered the path of enmity...}
{213}{}{我们是一个紧密团结的社区，但拜火者给我们带来了自私！我们相信一个神，但他们教会我们争论宗教！我们想对我们的部落同胞做好事，但部落再次走上了敌对的道路...}
### {214}{}{The Phoenix taught us to trade brahmins as objects, although these animals are sacred. How many more outsiders will destroy our foundations? How many more feuds within the tribe will they cause just by their appearance in our lands?}
{214}{}{凤凰教我们将婆罗门作为物品进行交易，尽管这些动物是神圣的。还有多少外来者会摧毁我们的基础？仅仅因为他们出现在我们的土地上，就会在部落内部引发多少世仇？}
### {215}{}{Now look at Chatto. He learned to read pagan texts from the caravaneers. Reading! He calls for the Brahmins to be exchanged for the soulless technology of outsiders. He and his friends want to trade our freedom for an alliance with Phoenix. They want to put the pueblo in the hands of missionaries!}
{215}{}{现在看看查特。他从商队那里学会了阅读异教徒的经文。阅读他呼吁用外来者的无灵魂技术来交换婆罗门。他和他的朋友们想用我们的自由换取与凤凰城的联盟。他们想把普韦布洛交给传教士！}
### {216}{}{Look at these pagan things - books, technology, dubious and dangerous substances... We have always rejected them because they are dangerous, but there is nothing more valuable than the life of the tribe and the Brahmins. And now Chatto, along with his companions, collects pagan talismans and tries to read them. The Dark Brahmin has taken over the minds of our youth!}
{216}{}{看看这些异教徒的东西——书籍、技术、可疑和危险的物质...我们一直拒绝他们，因为他们很危险，但没有什么比部落和婆罗门的生命更宝贵的了。现在查特和他的同伴们收集异教徒的护身符，并试图阅读它们。黑暗婆罗门已经占领了我们年轻人的思想！}
### {217}{}{And this is our future? When did we fall so low that even the youth goes against the tribe? The missionaries are to blame for this! Drive them away! The pueblo must remain ours...}
{217}{}{这就是我们的未来？我们什么时候堕落到连年轻人都反对部落的地步？这要怪传教士！把他们赶走！普韦布洛必须属于我们...}
### {218}{}{Oh, I see a stranger in the pueblo. Who are you? What are you doing in a strange tribe?}
{218}{}{哦，我在普韦布洛看到一个陌生人。你是谁？你在一个陌生的部落里干什么？}
### {219}{}{Oh, I see a fire worshipper in the pueblo. What do you want? Take away our children and our brahmins? We have already answered your predecessors that the San Brahmin tribe cannot be bought, as you have done with the rest. Get back to your stinking Phoenix, pagan!}
{219}{}{哦，我在普韦布洛看到一个火崇拜者。你想要什么？带走我们的孩子和婆罗门？我们已经回答了你的前任，圣婆罗门部落是买不来的，就像你对其他部落所做的那样。回到你的臭凤凰，异教徒！}
### {220}{}{I am going to the chief on behalf of the Villa. Nana missed me.}
{220}{}{我代表维拉去见酋长。娜娜想我了。}
### {221}{}{Ah, the Divine Brahmin of Peace! If Nana lets in an outsider, there must be a reason. Okay, come on in. But keep in mind that nothing will hide from my eagle eye. I'll be watching your every move in the pueblo.}
{221}{}{啊，和平的神圣婆罗门！如果娜娜让外人进来，那肯定是有原因的。好吧，进来吧。但要记住，没有什么能瞒着我的鹰眼。我会看着你在普韦布洛的一举一动。}
### {222}{}{Thank you, Mangas. Please don't be angry with me for my intrusion.}
{222}{}{谢谢你，曼加斯。请不要因为我的打扰而生我的气。}
### {223}{}{You're just crazy in your old age. Leave me alone and let me pass.}
{223}{}{你老了简直疯了。别管我，让我过去。}
### {224}{}{See you, Mangas.}
{224}{}{再见，曼加斯。}
### {225}{}{[Next]}
{225}{}{[下一个]}

#Repeat dialog
### {230}{}{Greetings, stranger from the Villa.}
{230}{}{你好，来自别墅的陌生人。}
### {1230}{}{Greetings, women from the Villa.}
{1230}{}{你好，别墅的女人们。}
### {231}{}{I am troubled by your dark spirit on the land of my tribe.}
{231}{}{在我部落的土地上，我被你的黑暗灵魂所困扰。}
### {232}{}{See you later, shaman.}
{232}{}{回头见，萨满。}

### {240}{}{Who are you?}
{240}{}{你是谁？}
### {241}{}{My name is Mangas. I am the chief of the Eastern clan.}
{241}{}{我的名字叫曼加斯。我是东方氏族的首领。}
### {242}{}{Glad to meet you, Mangas, chief of the Eastern tribe.}
{242}{}{很高兴见到你，曼加斯，东方部落的首领。}
### {1242}{}{Glad to meet you, Mangas, chief of the Eastern tribe.}
{1242}{}{很高兴见到你，曼加斯，东方部落的首领。}
### {243}{}{I guess you're in charge here, Chief?}
{243}{}{我想你是这里的负责人，警长？}
### {244}{}{You're talking about the supreme leader Geronimo. He is in the Sanctuary. The leaders of each clan gathered in San Brahmin and chose him as our representative.}
{244}{}{你说的是最高领袖杰罗尼莫。他在保护区。每一个氏族的首领都聚集在圣婆罗门，并选择他作为我们的代表。}
### {245}{}{Then why are you here and not in the east?}
{245}{}{那你为什么在这里而不在东方？}
### {246}{}{The fight against the troops from Phoenix forced the whole tribe to gather in San Brahmin to defend our freedom and our values. Besides, this pueblo has always been our seasonal haven during dust storms and droughts.}
{246}{}{与凤凰城军队的战斗迫使整个部落聚集在圣婆罗门，捍卫我们的自由和价值观。此外，在沙尘暴和干旱期间，这个普韦布洛一直是我们的季节性天堂。}
### {247}{}{Did you build this pueblo? It looks very ancient.}
{247}{}{你建了这个普韦布洛吗？它看起来很古老。}
### {248}{}{There have always been ruins here for as long as I can remember. Sand has covered them for many generations, and no one knows what this place was like before. Now this is our main camp.}
{248}{}{从我记事起，这里就一直是废墟。沙子已经覆盖了他们好几代人，没有人知道这个地方以前是什么样子。现在这里是我们的主要营地。}
### {249}{}{OK, but we'll do it later.}
{249}{}{好的，但我们稍后再做。}

### {250}{}{What's going on here?}
{250}{}{这是怎么回事？}
### {251}{}{Chatto and the other boys were collecting forbidden things. I've found them and I'm going to burn them so that the others won't be offended. And don't you dare bring us new ones. It's none of your business, stranger from the Villa.}
{251}{}{查特和其他男孩正在收集违禁物品。我找到了它们，我要把它们烧掉，这样其他人就不会被冒犯了。你不敢给我们带来新的。这不关你的事，别墅里的陌生人。}
### {1251}{}{Chatto and other boys collected forbidden things. I've found them and I'm going to burn them so that the others won't be offended. And don't you dare bring us new ones. It's none of your business, the woman from the Villa.}
{1251}{}{查特和其他男孩收集违禁物品。我找到了它们，我要把它们烧掉，这样其他人就不会被冒犯了。你不敢给我们带来新的。这不关你的事，别墅里的女人。}
### {252}{}{I see.}
{252}{}{我明白了。}
### {253}{}{But what's wrong with these old things?}
{253}{}{但是这些旧东西怎么了？}
### {254}{}{We wander through the desert and live by what the desert gives us. Our people and our herds are the only thing that is valuable. There is no need for young people to join the things of the Ancient World. It's useless and unsafe.}
{254}{}{我们漫步在沙漠中，依靠沙漠给我们的生活。我们的人民和我们的牛群是唯一有价值的东西。年轻人没有必要加入古代世界。它既无用又不安全。}
### {255}{}{Whatever you say. Can I take these things?}
{255}{}{不管你说什么。我可以拿这些东西吗？}
### {256}{}{You're doing some nonsense. These are just old things, there are a lot of them on the ruins.}
{256}{}{你在胡说八道。这些都是旧东西，废墟上有很多。}
### {257}{}{But we don't live on those ruins! We are wandering through the Sonoran desert. Our people and our herds are the only thing that is valuable to us. There is no need for young people to join the things of the Ancient World. It's not safe.}
{257}{}{但我们不是生活在那些废墟上！我们在索诺兰沙漠中漫步。我们的人民和我们的畜群是唯一对我们有价值的东西。年轻人没有必要加入古代世界的事物。这不安全。}
### {258}{}{Whatever you say. How about an exchange? I can take them from here back to the ruins.}
{258}{}{不管你说什么。交换一下怎么样？我可以把他们从这里带回废墟。}
### {259}{}{You're doing the right thing. We don't have enough people like you in the Villa, Shaman Mangas. Accept the words of respect.}
{259}{}{你做的是对的。我们的别墅里没有足够的人像你一样，萨满曼加斯。接受尊重的话语。}
### {260}{}{Hmm. If you really are from the Villa I've heard about, then I should treat you more favorably. Perhaps our tribes are somewhat similar.}
{260}{}{嗯。如果你真的是我听说的别墅的人，那么我应该对你更有利。也许我们的部落有些相似。}
### {261}{}{It's not worth burning these things. Let me exchange them and take them away from here?}
{261}{}{这些东西不值得烧掉。让我交换一下，然后从这里拿走？}
### {262}{}{I don't care what happens to pagan talismans. It is much more important to teach the apostates a lesson and show the rest the truth. But I don't mind getting a benefit from the exchange, if you really have something to offer.}
{262}{}{我不在乎异教徒的护身符会发生什么。更重要的是给叛教者一个教训，并向其他人展示真相。但如果你真的有什么可以提供的，我不介意从交换中获得好处。}
### {263}{}{I think we can negotiate.}
{263}{}{我认为我们可以谈判。}
### {264}{}{All these things are really unsafe for you.}
{264}{}{所有这些东西对你来说真的很不安全。}
### {265}{}{That's what I'm talking about! The things of strangers bring disease, discord or death.}
{265}{}{这就是我在说的！陌生人的东西会带来疾病、不和或死亡。}
### {266}{}{Burn everything! Immediately! Especially this one. [Point to the grenade]}
{266}{}{烧掉所有东西！立即尤其是这个。[指向手榴弹]}
### {267}{}{You're doing a great job for your tribe.}
{267}{}{你为你的部落做得很好。}
### {268}{}{Do you want to exchange for something useful?}
{268}{}{你想换些有用的东西吗？}
### {269}{}{Look, this thing is endowed with demonic power! Destroy it immediately! [Throw a grenade into the fire]}
{269}{}{看，这东西被赋予了恶魔的力量！立即摧毁它！[往火里扔手榴弹]}

### {270}{}{What is the conflict with outsiders?}
{270}{}{与外界的冲突是什么？}
### {271}{}{They bring turmoil and discord to the tribe. Their soulless technologies contradict our precepts, and with their weapons outsiders are trying to conquer us and force us to work. Even the firewater has become a subject of contention.}
{271}{}{他们给部落带来混乱和不和。他们没有灵魂的技术与我们的戒律相矛盾，外来者正试图用他们的武器征服我们，迫使我们工作。就连消防水也成了争论的焦点。}
### {272}{}{I see. Let me ask you something else?}
{272}{}{我明白了。让我问你别的事吗？}
### {273}{}{Turmoil and discord? Who is against whom?}
{273}{}{混乱和不和？谁反对谁？}
### {274}{}{The Phoenix missionaries want a union and a place near the pueblo. The youth echoes them, the others drive them away.}
{274}{}{凤凰城的传教士想要一个联盟和一个靠近普韦布洛的地方。年轻人呼应他们，其他人赶走他们。}
### {275}{}{What kind of weapons do strangers have?}
{275}{}{陌生人有什么武器？}
### {276}{}{The aliens have fire sticks and durable metal armor. We cannot resist with our spears against such an army. Only cunning and knowledge of the wasteland help us fight against such a strong enemy.}
{276}{}{外星人有火棍和耐用的金属盔甲。我们不能用长矛抵抗这样的军队。只有狡猾和对荒原的了解才能帮助我们对抗如此强大的敌人。}
### {277}{}{What soulless technologies are you talking about?}
{277}{}{你在说什么没有灵魂的技术？}
### {278}{}{Old things whose power comes from other old things. You call it "bat-tare" and "radiation". For a long time, no one from the tribe dared to even touch these things. And now in Phoenix and Two-Sun they make them as easily and deftly as we make bags made of brahmin leather.}
{278}{}{力量来自其他古老事物的古老事物。你称之为“蝙蝠皮重”和“辐射”。很长一段时间以来，部落里没有人敢碰这些东西。现在，在凤凰城和两个太阳城，他们制作它们就像我们制作婆罗门皮革袋一样简单灵巧。}
### {279}{}{What kind of firewater is this?}
{279}{}{这是什么样的消防水？}
### {280}{}{This bitter smelly liquid came to us from Phoenix. She stupefies the head, like a Dark Brahmin. Those who drink this water do strange things. I try to burn all the supplies I find, but it's in vain. Until Phoenix stops producing and selling the tribe's drink, the general hangover will not stop.}
{280}{}{这种气味苦涩的液体是从凤凰城来的。她像一个黑暗的婆罗门一样把脑袋打晕。那些喝这种水的人会做一些奇怪的事情。我试图烧掉我找到的所有补给品，但都是徒劳的。直到凤凰停止生产和销售部落的饮料，一般的宿醉不会停止。}
### {281}{}{There's probably a whole moonshine distillery doing it in Phoenix.}
{281}{}{凤凰城可能有一整家私酒酒厂在做这件事。}
### {282}{}{I have been looking for a long time for a person who will find and destroy this plant. Without tequila, it will be easier for our tribe to resist outsiders. Do this and I will reward you handsomely.}
{282}{}{我一直在寻找一个能找到并摧毁这种植物的人。如果没有龙舌兰酒，我们部落将更容易抵抗外来者。这样做，我会给你丰厚的报酬。}
### {283}{}{Good. I'll do it.}
{283}{}{好的我会做的。}
### {284}{}{I will bring offerings to the Divine Brahmin to guide and protect you on the road. Good luck, my friend.}
{284}{}{我将为神圣的婆罗门带来祭品，在路上引导和保护你。祝你好运，我的朋友。}
### {285}{}{See you, Mangas.}
{285}{}{再见，曼加斯。}
### {286}{}{Wait, I want to know something else.}
{286}{}{等等，我想知道其他事情。}
### {287}{}{There must be a lot of security there. And I don't even know where this factory is. No, I will not interfere with the alcohol business.}
{287}{}{那里一定很安全。我甚至不知道这家工厂在哪里。不，我不会干涉酒类生意。}
### {288}{}{Then go. You're wasting our time.}
{288}{}{那就去吧。你在浪费我们的时间。}

### {290}{}{Rejoice, Mangas! The moonshine distillery in Phoenix has been completely destroyed.}
{290}{}{高兴吧，曼加斯！凤凰城的私酒酒厂已经完全被毁。}
### {291}{}{The Divine Brahmin himself must have helped you in this difficult task. Now I see that I was wrong in my attitude towards you. Not all outsiders are trying to subdue us or steal from us. Thank you, my friend from the Villa.}
{291}{}{神圣的婆罗门一定在这项艰巨的任务中帮助了你。现在我发现我对你的态度是错误的。并不是所有的外人都想制服我们或从我们这里偷东西。谢谢你，我的别墅朋友。}
### {292}{}{You're welcome.}
{292}{}{不客气。}
### {293}{}{Did you say something about a reward?}
{293}{}{你说了关于奖励的事吗？}
### {294}{}{You deserve respect and reward. Take these old things that I recently took away from the tribesmen. Surely you will find a use for all this.}
{294}{}{你应该得到尊重和奖励。拿我最近从部落里拿走的这些旧东西来说。你肯定会找到这一切的用处。}
### {295}{}{So, so, nuclear batteries, stimpacks, Radawaye and a bunch of caps... Pretty good.}
{295}{}{核电池，刺激包，Radawaye和一堆瓶盖...还不错。}

### {300}{}{...And this is our future? When did we fall so low that even the youth goes against the tribe? The Phoenix missionaries are to blame for this...}
{300}{}{…这就是我们的未来？我们什么时候堕落到连年轻人都反对部落的地步？凤凰城的传教士应该对此负责...}
### {301}{}{It's too late to shout about freedom, Mangas. The chief has made an alliance with the Phoenix. Accept it.}
{301}{}{现在喊自由已经太晚了，曼加斯。首领已与凤凰城结盟。接受它。}
### {302}{}{I look with grief at the future of the tribe. It's covered in fog. We are like a lost brahmin strayed from the herd. Sadly. Very sad.}
{302}{}{我悲痛地看着部落的未来。它被雾笼罩着。我们就像一个迷路的婆罗门。悲哀地非常难过。}
### {303}{}{Yeah. Be there.}
{303}{}{是 啊在那里。}

### {310}{}{I'm asking you to advocate for an alliance with the Phoenix missionaries.}
{310}{}{我请求你倡导与凤凰城传教士结盟。}
### {311}{}{You're delusional, my friend. I am trying to expel outsiders from our land with spells and enlightenment of the minds of my fellow tribesmen. And you ask me to stop and surrender to the will of the Brahmin of Fate.}
{311}{}{你在妄想，我的朋友。我正试图用咒语和我部落同胞的思想启蒙，将外来者驱逐出我们的土地。你让我停下来，向命运的婆罗门的意志投降。}
### {312}{}{That's right.}
{312}{}{没错。}
### {313}{}{If you think about it, it sounds really crazy.}
{313}{}{如果你仔细想想，这听起来真的很疯狂。}
### {314}{}{What's wrong with you, stranger from the Villa? It seems that your village and our tribe are on the same side on the warpath. Isn't that right?}
{314}{}{你怎么了，别墅里的陌生人？看来你们的村庄和我们的部落在战争中是站在同一边的。对不对？}
### {1314}{}{What's wrong with you, Villa woman? It seems that your village and our tribe are on the same side on the warpath. Isn't that right?}
{1314}{}{你怎么了，维拉女人？看来你们的村庄和我们的部落在战争中是站在同一边的。对不对？}
### {315}{}{Unfortunately, Mangas, you are out of touch with reality. The world is changing, and it's still impossible to live anymore.}
{315}{}{不幸的是，曼加斯，你脱离了现实。世界在变化，仍然不可能再活下去。}
### {316}{}{Now you're showing your true face. If your tribe is so weak, let it. But WE will not bend under strangers from Phoenix!}
{316}{}{现在你展现了你的真实面貌。如果你的部落如此软弱，那就顺其自然吧。但我们不会屈服于来自凤凰城的陌生人！}
### {317}{}{In vain. You'll remember my words later.}
{317}{}{徒劳。你以后会记住我的话的。}
### {318}{}{You know best. And I'm leaving.}
{318}{}{你最清楚。我要走了。}
### {319}{}{Unfortunately, Mangas, you are out of touch with reality. The world demands change. Otherwise, the tribe will be wiped off the face of the earth.}
{319}{}{不幸的是，曼加斯，你脱离了现实。世界需要改变。否则，这个部落将从地球上消失。}
### {320}{}{Strong words. They make your hamstrings shake with fear. But if we bend under the New World, we will disappear anyway. Isn't that right?}
{320}{}{措辞强硬。它们会让你的腿筋因恐惧而颤抖。但如果我们屈服于新世界，我们无论如何都会消失。对不对？}
### {321}{}{Make an alliance with the Phoenix and you will keep your traditions. If you stay with the Rangers, you will only condemn yourself to a war with complete defeat.}
{321}{}{与凤凰城结盟，你将保持你的传统。如果你留在流浪者队，你只会让自己陷入一场彻底失败的战争。}
### {322}{}{I don't know. Decide for yourself. Bye.}
{322}{}{我不知道。自己决定。再见}
### {323}{}{The tribe has so far managed to resist missionaries and bandits. But their increasing power presses us more and more. Even united, the tribe barely holds on to the San Brahmin.}
{323}{}{到目前为止，这个部落已经设法抵抗了传教士和土匪。但他们日益强大的力量越来越迫使我们。即使联合起来，这个部落也几乎无法留住圣婆罗门。}
### {324}{}{So be it. For the sake of saving my clan, I will stand for the union. But I will also maintain an alliance with the Rangers. And at the first sign of a threat, we will break all agreements.}
{324}{}{就这样吧。为了拯救我的家族，我将代表联盟。但我也会和流浪者队保持联盟关系。一旦出现威胁迹象，我们就会破坏所有协议。}
### {325}{}{A reasonable solution.}
{325}{}{一个合理的解决方案。}
### {326}{}{You have no choice. Phoenix will win anyway.}
{326}{}{你别无选择。菲尼克斯无论如何都会赢。}
### {327}{}{Trust me. Rangers are not your friends, and Phoenix will win anyway. You have no choice, otherwise you will perish in the sand.}
{327}{}{相信我，流浪者队不是你的朋友，凤凰队无论如何都会赢。你别无选择，否则你会死在沙子里。}
### {328}{}{I listen to your words and I am more and more grieved... Is it really so bad that even the Villa is ready to bend under the Phoenix? Then we really have no choice.}
{328}{}{听着你的话，我越来越难过...就连维拉都准备在凤凰城下屈服，真的这么糟糕吗？那我们真的别无选择。}
### {329}{}{I don't know anymore, Mangas... I need to collect my thoughts.}
{329}{}{我不知道了，曼加斯...我需要收集我的想法。}
### {330}{}{Of course. And until you convince me otherwise, I will speak at the council for an alliance with the Rangers. They are the ones who wish us well.}
{330}{}{当然在你说服我之前，我会在理事会上发言，争取与流浪者队结盟。他们是祝福我们的人。}
### {331}{}{Okay. Bye.}
{331}{}{可以再见}
### {332}{}{And if I bring you proof of their treachery?}
{332}{}{如果我给你他们背信弃义的证据？}
### {333}{}{Well, I will listen. But don't you dare lie to me.}
{333}{}{好吧，我会听的。但是你不敢对我撒谎。}
### {334}{}{Okay. Bye.}
{334}{}{可以再见}
### {335}{}{The Rangers are defeated. Their dam is destroyed.}
{335}{}{游骑兵队被击败了。他们的水坝被毁了。}
### {336}{}{Oh, why is the Divine Brahmin of Fate so cruel!}
{336}{}{哦，为什么命运的神圣婆罗门如此残忍！}
### {337}{}{Now they are busy with their own survival. It is hardly worth waiting for help from them.}
{337}{}{现在他们正忙于自己的生存。等待他们的帮助是不值得的。}
### {338}{}{The Rangers have already destroyed the Jackal tribe. You can be next.}
{338}{}{游骑兵已经摧毁了豺狼部落。你可能是下一个。}
### {339}{}{The whole tribe was destroyed? Oh, why is the Divine Brahmin of Fate so cruel!}
{339}{}{整个部落都被摧毁了？哦，为什么命运的神圣婆罗门如此残忍！}
### {340}{}{To these tough guys, all of you are just savages.}
{340}{}{对这些硬汉来说，你们都只是野蛮人。}
### {341}{}{A convoy of civilians was passing through your lands to Garage City. The Rangers treacherously robbed them.}
{341}{}{一支平民车队正穿过你们的土地前往车库城。游骑兵背信弃义地抢劫了他们。}
### {342}{}{What kind of oddities did the Divine Brahmin of Fate have in store for them?}
{342}{}{命运的神圣婆罗门为他们准备了什么样的怪事？}
### {343}{}{The migrants simply refused to follow their demands. They do this to everyone who does not obey them.}
{343}{}{移民们根本拒绝听从他们的要求。他们这样对待每一个不服从他们的人。}
