### {100}{}{This is George Crook.}
{100}{}{这是乔治·克鲁克。}
### {101}{}{You see a man with a gorgeous mustache and a determined look.}
{101}{}{你看到一个留着漂亮胡子、神情坚定的男人。}
### {102}{}{Right. Now go and kill all the savages. You understand orders, don't you, robot?}
{102}{}{正确的现在去杀掉所有的野蛮人。你懂命令，不是吗，机器人？}
### {103}{}{Take care of yourself. Maybe we'll meet again.}
{103}{}{照顾好自己。也许我们还会再见面。}
### {104}{}{I'll have to go back to Phoenix. God knows I did what I could.}
{104}{}{我得回凤凰城了。天知道我做了力所能及的事。}

#First meeting
### {200}{}{Wait. What are you doing here?}
{200}{}{等待你在这里干什么？}
### {201}{}{I don't know. Just wandering around here.}
{201}{}{我不知道。只是在这里闲逛。}
### {202}{}{Don't joke with me. I can see right through you rednecks. You're obviously not from Phoenix, which means you're from somewhere in the wasteland. From where? Answer me.}
{202}{}{别跟我开玩笑。我能看穿你们这些乡下人。你显然不是来自凤凰城，这意味着你来自荒原上的某个地方。从哪里？回答我。}
### {203}{}{I don't have to answer to you.}
{203}{}{我不必回答你。}
### {1203}{}{I don't have to answer to you.}
{1203}{}{我不必回答你。}
### {204}{}{First of all, what is it. In front of me is a proud and unbending redneck. Do you think you're the right one here? Soon the whole wasteland will be under the heel of Aaron and his army! And then we'll see how much your pride is enough.}
{204}{}{首先，它是什么。在我面前是一个骄傲而不屈的红脖子。你觉得你是对的吗？不久，整个荒原将被亚伦和他的军队所控制！然后我们再看看你的骄傲有多足。}
### {1204}{}{First of all, what is it. In front of me is a proud and unbending hillbilly. Do you think you're the right one here? Soon the whole wasteland will be under the heel of Aaron and his army! And then we'll see how much your pride is enough.}
{1204}{}{首先，它是什么。在我面前是一个骄傲而坚定的乡下人。你觉得你是对的吗？不久，整个荒原将被亚伦和他的军队所控制！然后我们再看看你的骄傲有多足。}
### {205}{}{Really?}
{205}{}{真正地}
### {206}{}{You, a peasant, will have nothing left but to bow your knees. You'll find out soon enough. In the meantime, I'll give you a chance to improve. Go back to the wastelands and tell everyone about the greatness of the Phoenix regular army.}
{206}{}{你，一个农民，什么都没有了，只能跪下。你很快就会发现的。在此期间，我会给你一个提高的机会。回到荒原，告诉大家凤凰正规军的伟大。}
### {1206}{}{You, a peasant woman, will have nothing left but to bow your knees. You'll find out soon enough. In the meantime, I'll give you a chance to improve. Go back to the wastelands and tell everyone about the greatness of the Phoenix regular army.}
{1206}{}{你，一个农民妇女，将什么都没有了，只能跪下。你很快就会发现的。在此期间，我会给你一个提高的机会。回到荒原，告诉大家凤凰正规军的伟大。}
### {207}{}{I'm leaving.}
{207}{}{我要走了。}
### {208}{}{I will not leave without answers to questions.}
{208}{}{我不会在没有答案的情况下离开。}
### {209}{}{Aaron sent me to help. Here is the order and the seal.}
{209}{}{亚伦派我来帮忙。这是订单和印章。}
### {210}{}{My village is deserted. So I'm going wherever my eyes look.}
{210}{}{我的村庄空无一人。所以我要去我眼睛看到的任何地方。}
### {211}{}{And that's right, baby. Go to Phoenix. There is nothing to do in the desert, and in a big city there will be many opportunities for you. Just don't mix up the road. If you know what I mean.}
{211}{}{没错，宝贝。去凤凰城。在沙漠里没有什么可做的，在大城市里你会有很多机会。只是不要把路弄乱。如果你知道我的意思。}
### {212}{}{Yes, I understand.}
{212}{}{是的，我理解。}
### {213}{}{Great. For now, I will assume that we are on the same side.}
{213}{}{太棒了现在，我认为我们站在同一边。}
### {214}{}{Okay. What's going on here?}
{214}{}{可以这是怎么回事？}
### {215}{}{Not really.}
{215}{}{不是。}
### {216}{}{I represent Aaron's authority in these lands. Aaron appreciates those who honor him. And he is very harsh with those who get in his way. Choose better which list to fit into.}
{216}{}{我代表亚伦在这片土地上的权威。亚伦感谢那些尊敬他的人。他对那些妨碍他的人非常苛刻。选择更适合的列表。}
### {217}{}{I see.}
{217}{}{我明白了。}
### {218}{}{What's going on here?}
{218}{}{这是怎么回事？}

### {220}{}{Wait... hmm? Familiar mantle. Did Aaron send you?}
{220}{}{等待嗯？熟悉的衣钵。是亚伦派你来的吗？}
### {221}{}{I don't know who you're talking about. It's just an old hoodie.}
{221}{}{我不知道你在说谁。这只是一件旧连帽衫。}
### {222}{}{Then forget it. What are you doing here?}
{222}{}{那就算了。你在这里干什么？}
### {223}{}{Yes, Aaron sent me. He wants to know the situation.}
{223}{}{是的，亚伦派我来的。他想知道情况。}
### {224}{}{I don't understand his train of thought. I will soon have nothing to feed my squad, and he is sending another fighter. Tell me, what use are you?}
{224}{}{我不明白他的思路。我很快就没有什么可以养活我的球队了，他又派了一名战士。告诉我，你有什么用？}
### {225}{}{I have a special assignment. Aaron is tired of waiting for results.}
{225}{}{我有一项特殊任务。亚伦厌倦了等待结果。}
### {226}{}{I think he just wants to solve the problem as soon as possible.}
{226}{}{我认为他只是想尽快解决这个问题。}
### {227}{}{Hmm. I'm already curious how you earned so much trust from Aaron himself. Perhaps I should listen to your advice. But keep in mind that I am still the commander of the squad.}
{227}{}{嗯。我已经很好奇你是怎么从亚伦那里赢得这么多信任的。也许我应该听听你的建议。但请记住，我仍然是小队的指挥官。}
### {228}{}{No problem.}
{228}{}{没问题。}
### {229}{}{I don't care about your squad.}
{229}{}{我不在乎你的球队。}

### {230}{}{I represent the Rangers. We have heard rumors that someone is trying to break the tribe of cattle breeders.}
{230}{}{我代表游骑兵队。我们听说有人试图破坏养牛部落。}
### {231}{}{We are just peaceful colonizers. They came to an empty land to establish a settlement here. Are we doing something bad?}
{231}{}{我们只是和平的殖民者。他们来到一片空地上，在这里建立了一个定居点。我们在做坏事吗？}
### {232}{}{You're trying to drive the tribe away.}
{232}{}{你想把部落赶走。}
### {233}{}{I'll tell you what. Listen carefully, Ranger henchman. These lands don't belong to you. And they don't belong to savages either. Aaron of Phoenix owns this whole valley. Get back to your people. And don't you dare get in our way.}
{233}{}{我会告诉你的。仔细听，流浪者的党羽。这些土地不属于你。他们也不属于野蛮人。凤凰城的亚伦拥有整个山谷。回到你的人身边。你也不敢挡我们的路。}
### {234}{}{You've said enough. I don't need more.}
{234}{}{你说得够多了。我不需要更多了。}
### {235}{}{I'm not leaving until I get the answers to the questions. What's going on here?}
{235}{}{在得到问题的答案之前我不会离开。这是怎么回事？}

#Repeat dialog
### {250}{}{Well? Speak, I'm listening.}
{250}{}{好说吧，我在听。}
### {251}{}{Let me go.}
{251}{}{让我走。}
### {252}{}{And what are you all doing here?}
{252}{}{你们在这里干什么？}

### {260}{}{This land belongs to His Majesty Aaron, Lord of the Sacred Fire and Lord of the Phoenix. He decided to establish a colony here. But our mission is being harmed by local savages.}
{260}{}{这块土地属于神圣之火和凤凰之主亚伦陛下。他决定在这里建立殖民地。但我们的使命正受到当地野蛮人的伤害。}
### {261}{}{What's wrong with these savages?}
{261}{}{这些野蛮人怎么了？}
### {262}{}{They didn't show hostility before. Now they are trying to drive us away with threats and brute force. But we don't want extra blood and offer them a mutually beneficial alliance.}
{262}{}{他们以前没有表现出敌意。现在他们正试图用威胁和暴力把我们赶走。但我们不希望有多余的血液，并为他们提供一个互利的联盟。}
### {263}{}{So why not leave the tribe alone?}
{263}{}{那么，为什么不让部落独处呢？}
### {264}{}{Their brahmins are too valued in Phoenix. Without them, there will be a crisis. Besides, it is unforgivable to leave an enemy under your nose.}
{264}{}{他们的婆罗门在凤凰城太受重视了。没有他们，就会出现危机。此外，把敌人留在你眼皮底下是不可原谅的。}
### {265}{}{[Next]}
{265}{}{[下一个]}
### {266}{}{In any case, I am a subordinate person. I am following the order of the high command. The settlement order is clear to me. And the demands of nomadic illiterate savages are not a decree to me.}
{266}{}{无论如何，我是一个下属。我听从最高指挥部的命令。定居令对我来说很清楚。游牧文盲野蛮人的要求对我来说不是法令。}
### {267}{}{Clear.}
{267}{}{清楚的}
### {268}{}{Listen. The tribe doesn't want to talk to me anymore. But you'll make a good spy. Talk to the leader, try to convince him to conclude an alliance.}
{268}{}{听部落不想再和我说话了。但你会成为一名出色的间谍。与领导人交谈，试图说服他缔结联盟。}
### {269}{}{I'm not going to interfere in someone else's war. Your problems are more important.}
{269}{}{我不会干涉别人的战争。你的问题更重要。}
### {270}{}{What are your problems compared to the war between the two peoples? Then pray that it does not touch you and your family.}
{270}{}{与两国人民之间的战争相比，你的问题是什么？然后祈祷它不要影响你和你的家人。}
### {271}{}{I have to go.}
{271}{}{我得走了。}
### {272}{}{I'll try. I will report on the result.}
{272}{}{我会试试的。我将报告结果。}

### {280}{}{I managed to talk to the chief. But he flatly refuses the union.}
{280}{}{我设法和局长谈过了。但他断然拒绝加入工会。}
### {281}{}{Geronimo is too stubborn. It looks like I'm wasting time with him. We need to act more decisively.}
{281}{}{Geronimo太固执了。看起来我在浪费时间和他在一起。我们需要采取更果断的行动。}
### {282}{}{What's your plan?}
{282}{}{你的计划是什么？}
### {283}{}{I know that not all savages despise us. The young are even trying to help. Among them is the chief's son, Chatto. Talk to him, find out what he wants. If he takes his father's place, then we can come to an agreement.}
{283}{}{我知道并不是所有的野蛮人都鄙视我们。年轻人甚至试图帮助我们。其中包括酋长的儿子查托。和他谈谈，了解他想要什么。如果他接替他父亲的位置，那么我们可以达成协议。}
### {284}{}{It's worth a try.}
{284}{}{值得一试。}
### {285}{}{I killed Geronimo and his successor Chatto.}
{285}{}{我杀了杰罗尼莫和他的继任者查特。}
### {1285}{}{I killed Geronimo and his successor Chatto.}
{1285}{}{我杀了杰罗尼莫和他的继任者查特。}
### {286}{}{It was very reckless! Geronimo resisted the union. But Chatto could have mediated in his place. Now we have no one to negotiate with. The tribe will scatter across the desert, breaking up into small flocks again.}
{286}{}{这太鲁莽了！杰罗尼莫抵制工会。但查特本可以替他调停的。现在我们没有人可以谈判了。部落将分散在沙漠中，再次分成小群。}
### {287}{}{It was hard to foresee...}
{287}{}{很难预见。。。}
### {288}{}{But you wanted to get rid of the leader yourself.}
{288}{}{但你想自己摆脱领导。}
### {289}{}{In any case, the situation has become easier. We will settle in the pueblo and force the savages to accept our rules by force. They won't be able to resist an entire colony.}
{289}{}{无论如何，情况已经变得更容易了。我们将在普韦布洛定居，并通过武力迫使野蛮人接受我们的规则。他们将无法抵抗整个殖民地。}
### {290}{}{Well, can I congratulate you on your victory?}
{290}{}{我可以祝贺你的胜利吗？}
### {291}{}{Not yet. The scouts found out who was raising dust in this pueblo. It turned out to be a man named Oscar. Ranger! Now I understand how the locals know the basics of tactics and guerrilla tricks.}
{291}{}{还没有。侦察兵发现是谁在这个普韦布洛掀起了一片尘土。原来是一个叫奥斯卡的人。护林员现在，我明白了当地人是如何掌握战术和游击队技巧的。}
### {292}{}{[Next]}
{292}{}{[下一个]}
### {293}{}{The Ranger must be driven out of the pueblo! So that they don't even remember his name here. And if he does not want to leave, we will whip him like a stubborn brahmin.}
{293}{}{游骑兵必须被赶出普韦布洛！以至于他们在这里都不记得他的名字了。如果他不想离开，我们会像一个固执的婆罗门一样鞭打他。}
### {294}{}{Good. I'll see what I can do.}
{294}{}{好的我看看我能做些什么。}
### {295}{}{Chatto is now the chief of the tribe. And he agrees to the conclusion of the union.}
{295}{}{查特现在是部落首领。他同意工会的结束。}
### {296}{}{The beauty of the news! Chatto has power in the eyes of the rest of the tribe, his authority will not allow the tribe to scatter in the desert. Very good job. You made a great diplomat. }
{296}{}{新闻之美！查特在部落其他人眼中拥有权力，他的权威不会允许部落分散在沙漠中。做得很好。你做了一个伟大的外交官。}
### {297}{}{The leader agrees to the alliance. I managed to convince him, although it was not easy.}
{297}{}{首领同意结盟。我设法说服了他，尽管这并不容易。}
### {298}{}{The beauty of the news. I don't think he's changed his views that much. Most likely, he was pressured by the other elders who are afraid of war. But it's a good job. You've made a great diplomat.}
{298}{}{新闻之美。我不认为他改变了那么多看法。最有可能的是，他受到了其他害怕战争的长辈的压力。但这是一份不错的工作。你已成为一位伟大的外交家。}

### {300}{}{Oscar is dead. His minions also kneel before you, Commander.}
{300}{}{奥斯卡死了。他的小黄人也跪在你面前，指挥官。}
### {301}{}{This is a victory! We have dealt a decisive blow to the reputation of the Rangers before the eyes of the tribe. Now they will understand who is worth dealing with.}
{301}{}{这是一场胜利！我们对游骑兵队在部落眼中的声誉造成了决定性的打击。现在他们会明白谁值得打交道了。}
### {302}{}{Oscar has escaped from the pueblo and will no longer interfere with your plans.}
{302}{}{奥斯卡已经逃离普韦布洛，不再干涉你的计划。}
### {303}{}{This is a victory! The Rangers fled and thus fell in the eyes of the savages to the level of a cowardly iguana. Now these savages will understand who is worth dealing with.}
{303}{}{这是一场胜利！游骑兵逃走了，因此在野蛮人的眼中，他们堕落到了懦弱的鬣蜥的地步。现在这些野蛮人会明白谁值得对付了。}
### {304}{}{Glad to help, Commander!}
{304}{}{很高兴帮忙，指挥官！}
### {1304}{}{I was glad to help, Commander!}
{1304}{}{我很乐意帮忙，指挥官！}
### {305}{}{Ahem. Actually, you know WHO solved this problem.}
{305}{}{嗯。事实上，你知道世界卫生组织解决了这个问题。}
### {306}{}{You have served the empire well. The rest would have the same amount of willpower and fighting fortitude. I'm glad we ended up on the same side.}
{306}{}{你为帝国服务得很好。其余的人都有同样的意志力和战斗毅力。我很高兴我们最终站在了同一边。}
### {1306}{}{You have served the empire well. The rest would have the same amount of willpower and fighting fortitude. I'm glad we ended up on the same side.}
{1306}{}{你为帝国服务得很好。其余的人都有同样的意志力和战斗毅力。我很高兴我们最终站在了同一边。}
### {307}{}{Do you think Aaron's empire still needs heroes?}
{307}{}{你认为亚伦的帝国还需要英雄吗？}
### {308}{}{Of course. I will send a letter of recommendation addressed to you in Phoenix. Go straight to Aaron, he values my word.}
{308}{}{当然我会在菲尼克斯给你寄一封推荐信。直接去找亚伦，他很重视我的话。}
### {309}{}{Thank you.}
{309}{}{非常感谢。}
### {310}{}{No, don't thank me. We are doing a common cause. Good luck on the way, comrade.}
{310}{}{不，不用谢我。我们在做一项共同的事业。路上祝你好运，同志。}
### {311}{}{Good luck.}
{311}{}{祝你好运}

### {320}{}{Who are you? And who are all these people?}
{320}{}{你是谁？这些人都是谁？}
### {321}{}{Tell us about yourself and your squad.}
{321}{}{告诉我们你自己和你的团队。}
### {322}{}{George Crook, field commander of His Majesty Aaron of Phoenix. And this is my loyal squad. When we clear the territory of the enemies, a group of ordinary settlers will come after us.}
{322}{}{乔治·克鲁克，凤凰城亚伦陛下的战地指挥官。这是我忠诚的团队。当我们清除敌人的领土时，一群普通的定居者会来追我们。}
### {323}{}{It was nice to chat. But I have to go.}
{323}{}{聊天很愉快。但我得走了。}
### {324}{}{Isn't the title too long for the lord of one city?}
{324}{}{对于一座城市的领主来说，这个头衔不是太长了吗？}
### {325}{}{Hold your tongue. Aaron's empire is quite large and is constantly expanding. Soon all of Arizona will be at his mercy.}
{325}{}{别说话。亚伦的帝国相当庞大，而且还在不断扩张。很快整个亚利桑那州都将任由他摆布。}
### {326}{}{Once again - who are you?}
{326}{}{再说一遍，你是谁？}
### {327}{}{Where did you all come from?}
{327}{}{你们都是从哪里来的？}
### {328}{}{We came from Phoenix to establish a colony here. But this place has already been occupied by savages.}
{328}{}{我们从凤凰城来到这里建立殖民地。但是这个地方已经被野蛮人占领了。}
### {329}{}{And where is this Phoenix?}
{329}{}{这只凤凰在哪里？}
### {330}{}{The city is southeast of here. But it's strange that you don't know that. It seems to be the largest city for miles around.}
{330}{}{这个城市在这里的东南部。但奇怪的是，你不知道这一点。它似乎是方圆数英里内最大的城市。}
### {331}{}{I don't know. I'm actually from a village in the opposite direction.}
{331}{}{我不知道。事实上，我来自相反方向的一个村庄。}
### {332}{}{Then it's clear. These are Ranger lands. It is not surprising that there are only villages in your area and no civilization. Take a look at Phoenix, see what a normal city is.}
{332}{}{那就清楚了。这些是游骑兵的领地。你所在的地区只有村庄，没有文明，这并不奇怪。看看凤凰城，看看什么是一个正常的城市。}
### {333}{}{I'll do that. Thanks for the advice.}
{333}{}{我会那样做的。谢谢你的建议。}
### {334}{}{I don't care about this "civilization" of yours.}
{334}{}{我不在乎你们的这种“文明”。}
### {335}{}{Tell me about the tribe.}
{335}{}{告诉我部落的情况。}
### {336}{}{This is a tribe of pastoralists and nomads. Phoenix residents have long had a difficult relationship with them.}
{336}{}{这是一个由牧民和游牧民族组成的部落。长期以来，凤凰城的居民与他们的关系一直很艰难。}
### {337}{}{By the way, what do you know about the locals?}
{337}{}{顺便问一下，你对当地人了解多少？}
### {338}{}{It seems you don't like them?}
{338}{}{你好像不喜欢它们？}
### {339}{}{Savages! They crawl like fleas in the desert. And once you settle in the old ruins, they immediately claim this land.}
{339}{}{野蛮人！它们像跳蚤一样在沙漠中爬行。一旦你在古老的废墟中定居下来，他们就会立即声称拥有这片土地。}
### {340}{}{Go on.}
{340}{}{继续}
### {341}{}{Some radical clans even attack civilians. Phoenix has been trying to negotiate peace for several years. And some clans even went over to our side. But not all of them. Now my squad also felt the stubbornness of the savages on their own skin. }
{341}{}{一些激进的部族甚至攻击平民。菲尼克斯几年来一直在努力进行和平谈判。甚至有几个家族来到我们这边。但并不是所有的。现在，我的小队也感受到了野蛮人的固执。}
### {342}{}{Now I understand why you are so bristling with weapons. Peace to you. And I have to go.}
{342}{}{现在我明白了你为什么武器这么多。愿你平安。我得走了。}
### {343}{}{Are you from Phoenix too?}
{343}{}{你也是凤凰城人吗？}

### {350}{}{You must leave San Brahmin. You and your whole squad.}
{350}{}{你必须离开圣婆罗门。你和你的整个团队。}
### {351}{}{What are you talking about?}
{351}{}{你在说什么？}
### {352}{}{Well, you don't want to anger the tribe, right?}
{352}{}{好吧，你不想激怒部落，对吧？}
### {353}{}{First of all, I want to put these savages in their place. You would also do well to reconsider your views on life.}
{353}{}{首先，我想把这些野蛮人放在他们的位置上。你最好重新考虑一下你对生活的看法。}
### {354}{}{Okay. I won't argue.}
{354}{}{可以我不会争辩的。}
### {355}{}{If you don't leave, blood will be shed.}
{355}{}{如果你不离开，就会流血。}
### {356}{}{Whoever sent you, tell them that George Crook knows no fear. Words can't intimidate me.}
{356}{}{不管是谁派你来的，告诉他们乔治·克鲁克无所畏惧。言语无法恐吓我。}
### {357}{}{Well, I warned you. Now the blood will flow like a river!}
{357}{}{我警告过你。现在血液会像河流一样流动！}
### {1357}{}{Well, I warned you. Now the blood will flow like a river!}
{1357}{}{我警告过你。现在血液会像河流一样流动！}
### {358}{}{Okay. I heard you.}
{358}{}{可以我听到了。}
### {1358}{}{Okay. I heard you.}
{1358}{}{可以我听到了。}
### {359}{}{The tribe is ready for decisive action. Your appearance only gives them a reason.}
{359}{}{部落已准备好采取果断行动。你的出现只会给他们一个理由。}
### {360}{}{I know that savages will not give up so easily. They are too far from the ideal of the New World that my lord is building. But that is why my mission is so important - to show the savages that they live in an outdated and incorrect way. Show that there is a better world.}
{360}{}{我知道野蛮人不会轻易放弃的。他们离我的领主正在建设的新世界的理想太远了。但这就是为什么我的使命如此重要——向野蛮人展示他们以过时和不正确的方式生活。表明世界更美好。}
### {361}{}{Okay. I won't argue.}
{361}{}{可以我不会争辩的。}
### {362}{}{However, angering them will only scare the tribe away from their ideals. Give them time to think. In the end, your mission will end in nothing if they attack.}
{362}{}{然而，激怒他们只会让部落远离他们的理想。给他们思考的时间。最终，如果他们发动攻击，你的任务将一无所获。}
### {363}{}{Thousands of savages! I'm already thinking about returning to Phoenix myself. My people are tired, there are not enough supplies for everyone, and then there are savages watching from behind a dune.}
{363}{}{成千上万的野蛮人！我已经在考虑自己回凤凰城了。我的人民很累，没有足够的物资给每个人，然后有野蛮人在沙丘后面看着。}
### {364}{}{So what have you decided?}
{364}{}{那么你决定了什么？}
### {365}{}{Okay. We'll leave. But only to return with renewed vigor.}
{365}{}{可以我们会离开的。但只是带着新的活力回来了。}
### {366}{}{A reasonable decision, Commander. Good luck on the way.}
{366}{}{一个合理的决定，指挥官。祝你好运。}
