### {100}{}{This is Luc?a.}
{100}{}{我是Luc?一}
### {101}{}{You see a girl in ceremonial attire.}
{101}{}{你看到一个穿着仪式服装的女孩。}
### {102}{}{Thanks for everything.}
{102}{}{谢谢你所做的一切。}
### {103}{}{Muchas gracias.}
{103}{}{Muchas gracias。}
### {104}{}{The wreath has been returned to its rightful owner.}
{104}{}{花圈已归还其合法主人。}
### {105}{}{It seems to be yours. Take it and do what you want with it.}
{105}{}{它似乎是你的。拿着它，用它做你想做的事。}
### {106}{}{It's too early to give it to you yet.}
{106}{}{现在给你还为时过早。}

{110}{}{}

#Dialogue before the ceremony
### {200}{}{Buenas noches.}
{200}{}{布埃纳斯·诺切斯。}
### {201}{}{Buenos dias.}
{201}{}{布宜诺斯艾利斯。}
### {202}{}{Nevermind to me.}
{202}{}{对我来说没关系。}
### {203}{}{Hi. Who are you? What's your name?}
{203}{}{你好你是谁？你叫什么名字？}
### {204}{}{Mi nombre es Luc?a.}
{204}{}{Mi nombre es Luc?一}
### {205}{}{Lucia, then. What kind of special outfit are you wearing? Is this holiday really in your honor? }
{205}{}{露西娅。你穿什么特别的衣服？这个节日真的是为了你吗？}
### {206}{}{Hoy soy reina. Este es un gran honor para mi... (excitedly hides his gaze) Dime, honestamente, te gusta nuestra ciudad?}
{206}{}{Hoy大豆reina。Este es un gran honor para mi…（兴奋地隐藏着目光）Dime，honestarmte，te gusta nuestra ciudad？}
### {207}{}{I don't understand, are you happy or crying?}
{207}{}{我不明白，你是高兴还是哭泣？}
### {208}{}{(bottlecaps his face) Estoy bien.}
{208}{}{（用瓶子塞住他的脸）Estoy bien。}
### {209}{}{Okay, I'm going to keep having fun.}
{209}{}{好吧，我会继续玩得开心的。}
### {210}{}{Hi. I speak Spanish too. Can I meet you?}
{210}{}{你好我也会说西班牙语。我能见见你吗？}
### {211}{}{My name is Luc?a.}
{211}{}{我的名字叫吕克?一}
### {212}{}{You seem so modest, and your outfit is so provocative. Is this holiday in your honor?}
{212}{}{你看起来很谦虚，你的打扮也很有挑逗性。这个节日是为了你吗？}
### {213}{}{I'm going to be queen today. It's such a tradition. And it's a great honor for me... (excitedly hides his gaze) Tell me, do you like our city and this holiday?}
{213}{}{我今天要当女王。这是一种传统。这对我来说是一种莫大的荣誉……（兴奋地隐藏着他的目光）告诉我，你喜欢我们的城市和这个节日吗？}
### {214}{}{Yes, this is the most beautiful and friendly place I've ever been!}
{214}{}{是的，这是我去过的最美丽、最友好的地方！}
### {1214}{}{Yes, this is the most beautiful and friendly place I've ever been!}
{1214}{}{是的，这是我去过的最美丽、最友好的地方！}
### {215}{}{Really? Oh, I'm so glad. I will do everything to keep it that way.}
{215}{}{真正地哦，我太高兴了。我会尽一切努力保持这种状态。}
### {216}{}{Of course, you're the queen... I don't understand, are you happy or crying?}
{216}{}{当然，你是女王...我不明白，你是高兴还是哭泣？}
### {217}{}{(bottlecaps his face) I am well... Talk to someone else.}
{217}{}{（用瓶子塞住他的脸）我很好...与其他人交谈。}
### {218}{}{Okay, I'm going to keep having fun.}
{218}{}{好吧，我会继续玩得开心的。}
### {219}{}{There is nothing better than my beautiful Villa. You have no idea how much better it is.}
{219}{}{没有什么比我美丽的别墅更好的了。你根本不知道它有多好。}
### {220}{}{Really? Ah, I'd like to see. But I will never leave my family.}
{220}{}{真正地啊，我想看看。但我永远不会离开我的家人。}
### {221}{}{I don't understand, are you laughing at me or crying?}
{221}{}{我不明白，你是在嘲笑我还是在哭？}
### {222}{}{Do you know where your crown could have gone?}
{222}{}{你知道你的王冠会去哪里吗？}
### {223}{}{Is it missing? Oh, that's bad... find her, please! I have to go through the ceremony, otherwise the saints will be angry!}
{223}{}{它不见了吗？哦，太糟糕了...请找到她！我必须通过仪式，否则圣人会生气的！}
### {224}{}{Okay, okay. I'll try to talk to someone else. Maybe someone saw something.}
{224}{}{好吧，好吧。我会试着和其他人谈谈。也许有人看到了什么。}

#Dialogue after the ceremony
### {230}{}{(He sits on the floor and looks down in frustration)}
{230}{}{（他坐在地板上沮丧地往下看）}
### {231}{}{[Leave]}
{231}{}{[离开]}
### {232}{}{Hey, how are you?}
{232}{}{嘿，你好吗？}
### {233}{}{(Puts his head on his knees)}
{233}{}{（把头放在膝盖上）}
### {234}{}{Are you okay?}
{234}{}{你还好吗？}
### {235}{}{(pulls back his hand and pushes you away) Go home, gringo! El Diablo ya est? aqu?!}
{235}{}{（拉回手推开你）回家吧，外国佬！暗黑破坏神? aqu？！}
### {236}{}{El Diablo? Who is it? What are you talking about anyway? I don't understand...}
{236}{}{暗黑破坏神？是谁？你到底在说什么？我不明白...}
### {237}{}{El Diablo is dead. Do you understand? (show with gestures) Dead!}
{237}{}{暗黑破坏神死了。你明白吗？（手势表演）死了！}
### {238}{}{(looks up in amazement) El Diablo est? muerto?.. No... No! (runs away from the church)}
{238}{}{（惊讶地抬头）El Diablo est? 穆尔托？。。不…不！（逃离教堂）}
### {239}{}{Come on, get some fresh air. Now you can afford it.}
{239}{}{来吧，呼吸新鲜空气。现在你可以负担得起了。}
