### {100}{}{Here is a visitor.}
{100}{}{这是一位访客。}
### {101}{}{You see a man in dusty clothes. It looks like he walked many miles in it.}
{101}{}{你看到一个男人穿着满是灰尘的衣服。看起来他开着它走了好几英里。}
### {102}{}{Wow. I knew that tinsmiths are masters, but I didn't even think about it...}
{102}{}{哇！我知道锡匠是大师，但我甚至没有想过。。。}
### {103}{}{What's wrong with this damn city?}
{103}{}{这个该死的城市怎么了？}
### {104}{}{...}
{104}{}{。。。}

#First meeting
### {200}{}{Hey, is that you? What a surprise. I didn't think I'd meet you here.}
{200}{}{嘿，是你吗？真是个惊喜。我没想到会在这里见到你。}
### {201}{}{And you...}
{201}{}{而你。。。}
### {202}{}{Do you remember you brought me a letter in Phoenix? I was very surprised at the time and thought it was some kind of deception. As it turned out, in vain.}
{202}{}{你还记得你在凤凰城给我带来一封信吗？当时我非常惊讶，认为这是某种欺骗。事实证明，这是徒劳的。}
### {1202}{}{Do you remember when you brought me the letter in Phoenix? I was very surprised at the time and thought it was some kind of deception. As it turned out, in vain.}
{1202}{}{你还记得你在凤凰城给我带来这封信的时候吗？当时我非常惊讶，认为这是某种欺骗。事实证明，这是徒劳的。}
### {203}{}{Well, but what brought you to this God-forsaken town?}
{203}{}{是什么把你带到这个被上帝遗弃的小镇？}
{204}{}{}
{205}{}{}
### {206}{}{There is an abandoned swimming pool building in the city center. I'm looking for the owner of this establishment.}
{206}{}{市中心有一座废弃的游泳池建筑。我在找这家公司的老板。}
### {207}{}{A swimming pool? Here in the middle of the desert?}
{207}{}{游泳池？在沙漠中央？}
### {208}{}{Well yes. There is a lot of water in the city, so caravans from all around come here. However, water is not sold to everyone.}
{208}{}{是的。城里有很多水，所以周围的大篷车都来了。然而，水并不是卖给所有人的。}
### {209}{}{Why are you looking for the owner?}
{209}{}{你为什么要找失主？}
### {210}{}{He's my relative. I received a letter from him with an offer to come and work in the bathhouse. And here I am. And he's nowhere to be found.}
{210}{}{他是我的亲戚。我收到了他的一封信，信中说我愿意来澡堂工作。我就在这里，他却不见了。}
### {211}{}{Just like that, he just came to a strange city?}
{211}{}{就这样，他刚刚来到一个陌生的城市？}
### {212}{}{Why not? After all, things got really bad in Phoenix after that monstrous explosion.}
{212}{}{为什么不呢？毕竟，在那次可怕的爆炸之后，凤凰城的情况变得非常糟糕。}
### {213}{}{An explosion? What's the story with the explosion?}
{213}{}{爆炸？爆炸是怎么回事？}
### {214}{}{Don't you know? Yes, the whole tenth track is already cracking about this. The Church of the Sacred Fire was blown up. Poof-f! Literally.}
{214}{}{你不知道吗？是的，整个第十条赛道都已经开始了。圣火教堂被炸毁了。呜呜！字面上}
### {215}{}{Wow. Do the locals know anything about your uncle?}
{215}{}{哇！当地人了解你叔叔吗？}
### {216}{}{The locals don't know anything. The bathhouse is closed, and the owner has not been seen for a long time. I talked to the mayor, but he called me another conman and kicked me out on the street.}
{216}{}{当地人什么都不知道。澡堂已经关门了，主人已经很久没有露面了。我和市长谈过了，但他叫我另一个骗子，把我踢到街上。}
### {217}{}{What are you going to do?}
{217}{}{你打算怎么办？}
### {218}{}{I don't know yet. I'll stay here a little longer, maybe my uncle will finally show up. If you find out anything, let me know, okay? I will not remain in debt.}
{218}{}{我还不知道。我会在这里多呆一段时间，也许我叔叔最终会出现。如果你发现什么，告诉我，好吗？我不会继续负债。}
### {219}{}{Well, good luck with the search.}
{219}{}{祝你搜索顺利。}
### {220}{}{Yeah. Be.}
{220}{}{是 啊是}
### {221}{}{Bye.}
{221}{}{再见}
### {222}{}{Surely this is some kind of mistake.}
{222}{}{这肯定是某种错误。}
### {223}{}{I don't think so.}
{223}{}{我不这么认为。}
### {224}{}{Well, well. Stay deluded.}
{224}{}{嗯，嗯。不要上当受骗。}
### {225}{}{Hmm. Or maybe you're just pretending to be his relative to take his place?}
{225}{}{嗯。或者你只是假装是他的亲戚来代替他的位置？}
### {226}{}{Nonsense. We really haven't seen each other for a long time. But the uncle himself sent the letter through couriers, it can be checked. Besides, it was you who gave me his letter.}
{226}{}{胡说我们真的好久没见面了。但是叔叔自己通过快递员寄来的信，是可以查到的。此外，是你把他的信给了我。}
### {1226}{}{Nonsense. We really haven't seen each other for a long time. But the uncle himself sent the letter through couriers, it can be checked. Besides, it was you who gave me his letter.}
{1226}{}{胡说我们真的好久没见面了。但是叔叔自己通过快递员寄来的信，是可以查到的。此外，是你把他的信给了我。}

#Repeated dialogue at the parking lot
### {250}{}{Ah, it's you. I was just thinking about you. Two strangers in the same city. We should stick together, huh?}
{250}{}{啊，是你。我只是在想你。两个陌生人在同一个城市。我们应该团结在一起，是吗？}
### {251}{}{Sounds very far-fetched. Bye.}
{251}{}{听起来很牵强。再见}
### {252}{}{Sure. See you again.}
{252}{}{当然再见。}
### {253}{}{By the way, what's your name?}
{253}{}{顺便问一下，你叫什么名字？}
### {254}{}{Just call me Steve.}
{254}{}{就叫我史蒂夫吧。}
### {255}{}{Okay, Steve. How about you tell me again what you're doing here?}
{255}{}{好吧，史蒂夫。不如你再告诉我你在这里干什么？}
### {256}{}{See you later, Steve.}
{256}{}{回头见，史蒂夫。}
### {257}{}{Tell me again, who are you looking for?}
{257}{}{再说一遍，你在找谁？}

#stage 1
### {260}{}{Have you been to the local cemetery? Looks like your uncle is there.}
{260}{}{你去过当地的墓地吗？看起来你叔叔在那里。}
### {261}{}{What? So he's dead? Now I understand why the mayor is trying to kick me out. But how did it happen?}
{261}{}{什么所以他死了？现在我明白了市长为什么要把我赶出去。但这是怎么发生的呢？}
### {262}{}{Judging by the mass graves, many people died here. Do you know something about this?}
{262}{}{从乱葬岗来看，这里死了很多人。你知道这件事吗？}
### {263}{}{Hmm. As far as I know, clan wars have been waged here recently. That's why the locals get nervous when you try to ask them about the past. If my uncle fell victim to this war, then it remains only to accept.}
{263}{}{嗯。据我所知，最近这里发生了部族战争。这就是为什么当你试图询问当地人的过去时，他们会感到紧张。如果我的叔叔成为这场战争的受害者，那就只能接受了。}
### {264}{}{Will you leave with nothing?}
{264}{}{你会一无所有地离开吗？}
### {265}{}{Well, no. The bathhouse belonged to my uncle. And I am his relative. Shouldn't I inherit it?}
{265}{}{不，澡堂是我叔叔的。我是他的亲戚。难道我不应该继承它吗？}
### {266}{}{Are you kidding? After all these threats, are you going to stay?}
{266}{}{你在开玩笑吗？在所有这些威胁之后，你会留下来吗？}
### {267}{}{You see... To be honest, things weren't going well in Phoenix either. I was completely desperate, trying to earn caps on the fights. But here you can revive my uncle's business and get rich. Why the hell should I miss my chance?}
{267}{}{你看。。。老实说，菲尼克斯的情况也不太好。我完全绝望了，试图赢得比赛的上限。但在这里你可以重振我叔叔的生意并致富。我为什么要错过机会？}
### {268}{}{Ah, that's it. The death of your relative was very convenient, wasn't it?}
{268}{}{啊，就是这样。你亲戚的死很方便，不是吗？}
### {269}{}{What are you talking about? I can revive my uncle's business and get rich. It would be stupid to miss such a chance.}
{269}{}{你在说什么？我可以重振我叔叔的生意并致富。错过这样的机会是愚蠢的。}
### {270}{}{Great idea. It's worth a try. Do you need partners?}
{270}{}{好主意。值得一试。你需要合作伙伴吗？}
### {271}{}{You have to be absolutely desperate to take such a risk.}
{271}{}{你必须不顾一切地冒这样的风险。}
### {272}{}{Well, the main thing now is to win the mayor's favor. He doesn't want to make contact with me, the guards won't let him in. Can you talk to him?}
{272}{}{现在最重要的是赢得市长的好感。他不想和我联系，警卫不让他进来。你能和他谈谈吗？}
### {273}{}{And what will I get for this mediation?}
{273}{}{这次调解我能得到什么？}
### {274}{}{And, of course, everyone wants to make money. Don't worry, I'll pay when I get rich. We're partners. We just have to wait a bit.}
{274}{}{当然，每个人都想赚钱。别担心，我有钱的时候会付钱的。我们是合作伙伴。我们只需要等一等。}
### {275}{}{I'll try to convince him.}
{275}{}{我会试着说服他。}
### {276}{}{Thank you, partner. What would I do without you?}
{276}{}{谢谢你，合伙人。没有你我该怎么办？}
### {277}{}{See you later.}
{277}{}{回头见。}
### {278}{}{The very thought of talking to this tyrant scares me. Find someone else.}
{278}{}{一想到要和这个暴君说话，我就害怕。找其他人吧。}
### {279}{}{I understand. It's okay, I'll figure it out somehow. Anyway, thanks for the help.}
{279}{}{我理解。没关系，我会想办法的。不管怎样，谢谢你的帮助。}
### {280}{}{Bye, loser.}
{280}{}{再见，失败者。}
### {281}{}{I'm just passing through here, I don't have time to wait for the first customers.}
{281}{}{我只是路过这里，没有时间等第一批顾客。}

#stage 2
### {300}{}{So what did the mayor say? Did you manage to talk to him?}
{300}{}{市长说了什么？你设法和他谈过了吗？}
### {301}{}{No, I wasn't up to him. Wait a little longer.}
{301}{}{不，我不能胜任他。再等一会儿。}
### {302}{}{The mayor of the city is dead. Now there's nothing stopping you from starting your own business.}
{302}{}{市长去世了。现在没有什么能阻止你自己创业。}
### {303}{}{Dead? What the hell is wrong with this city? Okay, I don't want the details. But your truth is - I need to occupy the bathhouse before someone else does it.}
{303}{}{死去的这个城市到底怎么了？好吧，我不想要细节。但你的真相是——我需要在别人之前占据澡堂。}
### {304}{}{OK, we'll meet there...}
{304}{}{好的，我们在那里见面。。。}
### {305}{}{The mayor has recognized your right to a bathing place. You can start your own business.}
{305}{}{市长已经承认你有权去洗澡。你可以自己创业。}
### {306}{}{Wow, you know how to negotiate with people. Now we need to occupy the bathhouse before the mayor changes his mind.}
{306}{}{哇，你知道如何与人谈判。现在，在市长改变主意之前，我们需要占用澡堂。}
### {307}{}{OK, we'll meet on the spot...}
{307}{}{好的，我们会在现场见面。。。}
### {308}{}{The mayor demands that you leave the city. Immediately.}
{308}{}{市长要求你离开这个城市。立即}
### {309}{}{What happened to you? Can't you see that it's not fair? I rightfully own this bathhouse. It's empty now anyway.}
{309}{}{你怎么了？你看不出这不公平吗？我理所当然地拥有这个澡堂。反正现在是空的。}
### {310}{}{Sorry, I'll try to convey this idea to the mayor.}
{310}{}{对不起，我会试着把这个想法传达给市长。}
### {311}{}{If you value your life, you will leave right now.}
{311}{}{如果你珍惜你的生命，你现在就离开。}
### {312}{}{Ah, that's it. I thought we were partners. It turned out that you are an ordinary corrupt dog.}
{312}{}{啊，就这样。我还以为我们是合作伙伴呢。原来你是一只普通的腐败狗。}
### {1312}{}{Ah, that's it. I thought we were partners. It turned out that you are an ordinary selling bitch.}
{1312}{}{啊，就这样。我还以为我们是合作伙伴呢。原来你是个普通的贱货。}
### {313}{}{We will discuss this further. But later.}
{313}{}{我们将对此进行进一步讨论。但后来。}
### {314}{}{I'm not kidding. Get out of town.}
{314}{}{我不是在开玩笑。离开城镇。}
### {315}{}{I'm not leaving. This is my family business. And I won't leave him.}
{315}{}{我不会走的。这是我的家族企业。我不会离开他。}
### {316}{}{You leave me no choice. If you don't want to leave, I'll make you.}
{316}{}{你让我别无选择。如果你不想离开，我就强迫你。}
### {317}{}{However, do what you want.}
{317}{}{但是，做你想做的事。}
### {318}{}{Listen to me. I'll count to five, and then I'll get the gun. One... two...}
{318}{}{听我说，我数数到五，然后拿枪。一二}
### {319}{}{Hey, hey, wait...}
{319}{}{嘿，嘿，等等。。。}
### {320}{}{...three.}
{320}{}{三}
### {321}{}{Come on, it's a joke. Of course, stay, it's your problem.}
{321}{}{拜托，这是个笑话。当然，留下来，这是你的问题。}
### {322}{}{Okay, that's it, I'm leaving, look.}
{322}{}{好吧，就这样，我要走了，看。}
### {323}{}{And don't come back.}
{323}{}{不要回来。}

### {330}{}{Look what the locals have done with this once wonderful institution. Dirty barbarians.}
{330}{}{看看当地人对这个曾经很棒的机构做了什么。肮脏的野蛮人。}
### {331}{}{I'll take a look around if you don't mind.}
{331}{}{如果你不介意的话，我会四处看看。}
### {332}{}{What's wrong?}
{332}{}{怎么了？}
### {333}{}{Apart from the fact that all the most valuable things were stolen from here, the real problem is in the water heating system.}
{333}{}{除了这里所有最值钱的东西都被偷了之外，真正的问题还在热水系统。}
### {334}{}{Is it not working?}
{334}{}{它不起作用吗？}
### {335}{}{Someone tried to steal the tank, but knocked it over and damaged it. I don't know how to fix it yet.}
{335}{}{有人想偷坦克，但把它撞倒了，把它弄坏了。我还不知道怎么修。}
### {336}{}{Well, good luck. I'm definitely not going to do this.}
{336}{}{祝你好运。我绝对不会这么做。}
### {337}{}{Let me see. I'm sure I'll fix this monster with a piece of scrap metal.}
{337}{}{让我看看。我相信我会用一块废金属把这个怪物修好的。}
### {338}{}{The tank is in perfect order. You can warm the water and wash.}
{338}{}{油箱状况良好。你可以温水洗。}
### {339}{}{Did you manage to fix it? Cool. Now the business will definitely be trampled. Thank you, you've done a lot for me. Drop by if you need to freshen up.}
{339}{}{你设法修好了吗？凉的现在这项业务肯定会被践踏。谢谢你，你为我做了很多。如果你需要梳洗一下的话，顺便来。}
### {1339}{}{Did you manage to fix it? Cool. Now the business will definitely be trampled. Thank you, you've done a lot for me. Drop by if you need to freshen up.}
{1339}{}{你设法修好了吗？凉的现在这项业务肯定会被践踏。谢谢你，你为我做了很多。如果你需要梳洗一下的话，顺便来。}
### {340}{}{I'll keep that in mind. Be there.}
{340}{}{我会记住的。在那里。}

### {350}{}{How are you?}
{350}{}{你好吗}
### {351}{}{How are you? Do you want to wash up?}
{351}{}{你好吗你想洗洗吗？}
### {352}{}{Do you want to wash up? Come on, I just found some old sea salt.}
{352}{}{你想洗洗吗？拜托，我刚找到一些旧海盐。}
### {353}{}{Do you want to wash up? It's about time while it's so hot outside.}
{353}{}{你想洗洗吗？外面这么热是时候了。}
### {354}{}{Now you definitely need to wash up. Don't be shy, I won't charge you too much.}
{354}{}{现在你肯定需要洗洗了。别害羞，我不会向你收取太多费用的。}
### {355}{}{The bathroom is free. Get in, it's time to wash off this road dirt.}
{355}{}{浴室是免费的。上车，是时候把路上的泥土洗掉了。}
### {356}{}{Bye, Stephen.}
{356}{}{再见，斯蒂芬。}

#The rest
### {400}{}{I need to wash up. How much does it cost?}
{400}{}{我需要洗洗。它要多少钱？}
### {401}{}{I'll only charge you for firewood and water. It will cost in }
{401}{}{我只收你的柴火和水。它将花费}
### {402}{}{ caps.}
{402}{}{帽子。}
### {403}{}{I can't afford that luxury. Another time.}
{403}{}{我负担不起那种奢侈。下次}
### {404}{}{Sounds acceptable. Here...}
{404}{}{听起来可以接受。在这里}

### {410}{}{For such a period of time, your business should have already brought good results.}
{410}{}{在这样的一段时间里，你的生意应该已经取得了良好的效果。}
### {411}{}{You know, not really. Caravanners travel seasonally, so there are times when there are no visitors in the city at all. Not everyone is willing to pay caps for such a service. But enough to live on.}
{411}{}{你知道，不是真的。房车旅行是季节性的，所以有时城市里根本没有游客。并不是每个人都愿意为这样的服务支付上限。但足够生活了。}
### {412}{}{Have you not forgotten our agreement?}
{412}{}{你没有忘记我们的协议吗？}
### {413}{}{My patience is running out. Where is my share of the business?}
{413}{}{我的耐心不多了。我的业务份额在哪里？}
### {414}{}{What are you talking about? I don't owe you anything. Come on, get out of here, you're stopping me from cleaning the tub.}
{414}{}{你在说什么？我什么都不欠你。来吧，离开这里，你阻止我打扫浴缸。}
### {415}{}{What?}
{415}{}{什么}
### {416}{}{You're a scum.}
{416}{}{你是个渣滓。}
### {417}{}{Of course, partner. I've been saving up caps just for you. Here, 200 pieces. And now I'm sorry, this tub needs to be cleaned properly.}
{417}{}{当然，伙伴。我一直在为你攒帽子。给，200块。现在我很抱歉，这个浴缸需要好好清洗。}
### {418}{}{Thank you, it's a pleasure doing business with you. Have a nice day, Steve.}
{418}{}{谢谢你，很高兴和你做生意。祝你今天愉快，史蒂夫。}
### {419}{}{And that's it? Shit is your business, Steve. And change the sign. It looks lousy.}
{419}{}{就这样？妈的是你的事，史蒂夫。然后换个标志。它看起来很糟糕。}
### {420}{}{If you don't want to give up the bottlecaps, I'll take them by force. Stand still, you bastard...}
{420}{}{如果你不想放弃瓶子，我就强行拿走。站住，你这个混蛋。。。}

### {430}{}{The tinsmiths sent an ambassador here. Do you know anything about it?}
{430}{}{锡匠们派了一位大使来这里。你知道这件事吗？}
### {431}{}{I saw this tinker, but he didn't talk to anyone and immediately went to the mayor. I never saw him again.}
{431}{}{我看到了这个修补匠，但他没有和任何人说话，立即去找市长。我再也没见过他。}
### {432}{}{At least some information. Bye.}
{432}{}{至少有一些信息。再见}
### {433}{}{You're of no use. Bye.}
{433}{}{你没有用。再见}
