### {100}{}{Here is the leader of the gang.}
{100}{}{这是这个团伙的头目。}
### {101}{}{You see one of the highway robbers. Looks like he's running everything here.}
{101}{}{你看到一个高速公路劫匪。看起来他在管理这里的一切。}
### {102}{}{We're already leaving. Give the mayor our "deepest apologies."}
{102}{}{我们已经离开了。向市长致以“最深切的歉意”}

### {200}{}{Climbing right under a bullet and not afraid? You're either brave or just a fool. Who are you?}
{200}{}{在子弹下爬而不害怕？你要么勇敢，要么就是个傻瓜。你是谁？}
### {1200}{}{The count is so pathetic that he sends a woman to negotiate. Okay. But who are you?}
{1200}{}{伯爵太可怜了，他派了一个女人来谈判。可以但你是谁？}
### {201}{}{I'm the last thing you'll see.}
{201}{}{我是你最后看到的人。}
### {202}{}{It doesn't matter who I am. The mayor sent me to negotiate.}
{202}{}{我是谁并不重要，市长派我来谈判。}
### {203}{}{Well of course. Bustos does not change. He is ready to sacrifice any life except his own. Let's see if he values his daughter's life.}
{203}{}{当然。Bustos不会改变。除了自己的生命，他愿意牺牲任何生命。让我们看看他是否重视女儿的生命。}
### {204}{}{The mayor demands to release the hostage. Otherwise you won't get out of here alive.}
{204}{}{市长要求释放人质。否则你就不会活着离开这里。}
### {205}{}{The mayor can't be trusted. He's meaner than a wasteland snake. Tell him that if he does not fulfill our demands, we will kill his daughter.}
{205}{}{市长不可信任。他比荒原上的蛇还卑鄙。告诉他，如果他不满足我们的要求，我们就会杀死他的女儿。}
### {206}{}{What do you want?}
{206}{}{你想要什么？}
### {207}{}{To hell with talking. You deserve only death.}
{207}{}{见鬼去吧。你该死。}
### {208}{}{Ten thousand caps.}
{208}{}{一万个瓶盖。}
### {209}{}{Ten thousand? You can't get that much in the whole city.}
{209}{}{一万？你不可能在整个城市得到那么多。}
### {210}{}{It's not our problem. So, there is only one thing left - the life of the mayor. Let him take his daughter's place.}
{210}{}{这不是我们的问题。所以，只剩下一件事了——市长的生活。让他接替他女儿的位置。}
### {211}{}{I'll let him know your requirements.}
{211}{}{我会让他知道你的要求。}
### {212}{}{What's wrong with you?}
{212}{}{你怎么了？}
### {213}{}{Hmm. You're not from around here, are you? Otherwise I would have known you.}
{213}{}{嗯，你不是这一带的人，是吗？否则我早就认识你了。}
### {214}{}{What does it matter?}
{214}{}{这有什么关系？}
### {215}{}{caps are not the main thing for me. There is an old cemetery in the east of the city. A mass grave. In this place, where only dry grass grows, the inhabitants of Casa Grande rest. My parents are among them.}
{215}{}{瓶盖对我来说不是主要的东西。在城市的东部有一个古老的墓地。乱葬岗。在这个只有干草生长的地方，卡萨格兰德的居民休息着。我的父母也在其中。}
### {216}{}{[Listen]}
{216}{}{[听]}
### {217}{}{They were trying to establish a peaceful life in this city. They worked tirelessly to launch a water pump and equip the city. But then Bustos came, killed them and took the city for himself. He left no one alive who stood in his way.}
{217}{}{他们试图在这座城市过上平静的生活。他们不知疲倦地为启动水泵和为城市配备设备。但后来巴斯托斯来了，杀死了他们，并占领了这座城市。他没有留下任何挡住他的人。}
### {218}{}{And now you're taking revenge?}
{218}{}{现在你在报复？}
### {219}{}{Why would I lie? I'm telling the truth. Tell the mayor my words. Although it is unlikely that he will want to listen to you.}
{219}{}{我为什么要撒谎？我说的是实话。把我的话告诉市长。尽管他不太可能愿意听你的。}
### {220}{}{I will convey your demands to the mayor.}
{220}{}{我会把你的要求转达给市长。}
### {221}{}{You're lying. And I will kill you so that others will not be offended...}
{221}{}{你在撒谎。我会杀了你，这样别人就不会被冒犯...}
### {222}{}{Are you sure you want even more blood on the land of your ancestors?}
{222}{}{你确定你想在你祖先的土地上留下更多的血吗？}
### {223}{}{I'm not going to argue with you. Bring me the mayor. I will only talk to him.}
{223}{}{我不会和你争论的。把市长带来。我只会和他谈谈。}
### {224}{}{This city is already knee-deep in blood. Only now have we managed to achieve at least some peace.}
{224}{}{这座城市已经血流成河。直到现在，我们才设法至少实现了一些和平。}
### {225}{}{There will be no more negotiations. You're going to die right now...}
{225}{}{不会再有谈判了。你现在就要死了...}
### {226}{}{Are you saying I'm just being selfish? How do you think I should live after the mayor banished me from my land? I eat carrion and rob caravans on the highway just to survive. And all because of one greedy scoundrel.}
{226}{}{你是说我只是自私吗？市长把我驱逐出我的土地后，你认为我该怎么生活？为了生存，我在高速公路上吃腐肉和抢劫大篷车。这一切都是因为一个贪婪的恶棍。}
### {227}{}{So get off this road. You can live in Phoenix or another city.}
{227}{}{所以离开这条路。你可以住在凤凰城或其他城市。}
### {228}{}{I don't think I'm ready to start over. It's too late to change anything. And yet your words have sunk into my soul. The girl can leave. It's not her fault. But if the mayor has any dignity left, then let him come to me. Let's have a duel with him, just like in the good old days.}
{228}{}{我想我还没有准备好重新开始。改变任何事情都为时已晚。然而你的话却深深地印在了我的灵魂里。女孩可以离开了。这不是她的错。但如果市长还有什么尊严，那就让他来找我吧。让我们和他决斗吧，就像过去一样。}
### {229}{}{Glad you listened to reason.}
{229}{}{很高兴你听了道理。}
### {1229}{}{Glad you listened to reason.}
{1229}{}{很高兴你听了道理。}
### {230}{}{What did the mayor say?}
{230}{}{市长说了什么？}
### {231}{}{That he promised a reward for your head. And I will get it.}
{231}{}{他答应悬赏你的脑袋。我会得到的。}
### {232}{}{The situation has not changed. He will let you go if you release the hostage.}
{232}{}{情况没有改变。如果你释放人质，他会放你走的。}
### {233}{}{What are these spy tricks? Do you really hope that I don't recognize you as a stranger under these signs?}
{233}{}{这些间谍伎俩是什么？你真的希望我不要在这些标志下认出你是个陌生人吗？}
### {234}{}{Well...}
{234}{}{好}
### {235}{}{You will only get a thousand caps and leave the city. Otherwise you won't get out of here alive.}
{235}{}{你只会得到一千个瓶盖，然后离开这个城市。否则你就不会活着离开这里。}
### {236}{}{Surprisingly. I thought Bustos wouldn't give ten caps...}
{236}{}{惊人地我以为巴斯托斯不会给10场比赛...}
### {237}{}{[Next]}
{237}{}{[下一个]}
### {238}{}{(One of the accomplices interrupts the leader, takes him into a corner and begins to actively discuss something with him) And ... yes... You're right, buddy, calm down... (comes back to you) We accept your terms. Give me the caps and you can take the girl.}
{238}{}{（其中一名同伙打断了领导的话，把他带到角落里，开始积极地和他讨论一些事情）然后...对你是对的，伙计，冷静点...（回复您）我们接受您的条件。把瓶盖给我，你就可以带走那个女孩。}
### {239}{}{Why would the count be so nice to robbers? I'll just kill you and take the bottlecaps for myself...}
{239}{}{伯爵为什么对强盗这么好？我会杀了你，把瓶子给我自己...}
### {240}{}{We'll have to wait a bit. I'll go get the caps.}
{240}{}{我们得等一等。我去拿瓶盖。}
### {241}{}{The whole amount is here.}
{241}{}{全部金额都在这里。}
### {242}{}{Tell the count that we're leaving, and don't let him try to send a tail after us.}
{242}{}{告诉伯爵我们要走了，不要让他试图尾随我们。}
### {243}{}{It would be foolish to lose such a sum of caps. I will kill you and take them back.}
{243}{}{失去这么多上限是愚蠢的。我会杀了你，然后把他们带回去。}
### {244}{}{The Count keeps his word.}
{244}{}{伯爵信守诺言。}
