### {100}{}{Here is Count Bustos.}
{100}{}{这是巴斯托斯伯爵。}
### {101}{}{You see a man in a solid but dilapidated suit. His gray temples seem to hint at a difficult past.}
{101}{}{你看到一个男人穿着结实但破旧的西装。他灰色的鬓角似乎暗示着一段艰难的过去。}
### {102}{}{I've heard of such armor, but I thought it was fiction.}
{102}{}{我听说过这样的盔甲，但我认为这是虚构的。}
### {103}{}{I will not tolerate this major infection in my city.}
{103}{}{在我的城市里，我不会容忍这种严重的感染。}
### {104}{}{I advise you two to leave the city immediately.}
{104}{}{我建议你们两个立即离开这个城市。}

#First meeting
### {200}{}{(When you enter the office of the local mayor, you immediately feel the unpleasant smell of alcohol. Looking around, you finally notice a man in a chair, wearily looking at you through his fingers. "M?" he says after a short pause.)}
{200}{}{（当你走进当地市长的办公室时，你会立刻感觉到难闻的酒精味。环顾四周，你终于注意到一个坐在椅子上的男人，疲惫地用手指看着你。“M？”他停顿了一会儿后说道。）}
### {201}{}{And where is the mayor? I have a conversation with him.}
{201}{}{市长在哪里？我和他进行了交谈。}
### {202}{}{(With a heavy sigh, the man in the chair frees himself from the bent posture and leans back wearily). He's in front of you. But who are you?}
{202}{}{（坐在椅子上的男人重重地叹了一口气，从弯腰的姿势中解脱出来，疲惫地向后倾去）。他在你面前。但你是谁？}
### {203}{}{Are you the mayor? And he looks like an ordinary clerk who spends the entire fee in a bar.}
{203}{}{你是市长吗？他看起来就像一个在酒吧里花掉所有费用的普通店员。}
### {204}{}{Let's get something straight. I am the legitimate mayor of this city. If you're not going to recognize the local government and accept the local rules, then get out of Casa Grande immediately. My city doesn't need troublesome outsiders. Is that clear?}
{204}{}{让我们把事情弄清楚。我是这个城市的合法市长。如果你不承认当地政府，也不接受当地的规定，那就立即离开格兰德之家。我的城市不需要麻烦的外来者。清楚吗？}
### {205}{}{Yeah, I see.}
{205}{}{是的，我明白了。}
### {206}{}{Excuse me, Mr. Mayor. I'm not going to cause any problems.}
{206}{}{对不起，市长先生。我不会造成任何问题。}
### {207}{}{That's good. So where did you come from?}
{207}{}{这很好。那么你是从哪里来的？}
### {1207}{}{That's good. So where did you come from?}
{1207}{}{这很好。那么你是从哪里来的？}
### {208}{}{My name is }
{208}{}{我的名字是}
### {209}{}{, I'm traveling.}
{209}{}{，我在旅行。}
### {210}{}{Okay, }
{210}{}{可以}
### {211}{}{. And where are you from?}
{211}{}{。你是哪里人？}
### {212}{}{Why is this so important?}
{212}{}{为什么这这么重要？}
### {213}{}{Because in such a small town, everyone wants to know who you're dealing with and how much you can trust him. And no one here knows you at all.}
{213}{}{因为在这样一个小镇上，每个人都想知道你在和谁打交道，你有多信任他。这里根本没有人认识你。}
### {214}{}{No one should care about my background.}
{214}{}{没有人应该关心我的背景。}
### {215}{}{That's how, you don't want to accept the rules? You're walking a dangerous path, stranger. Then explain to me what the hell are you doing here?}
{215}{}{这就是为什么，你不想接受规则？你走的路很危险，陌生人。然后向我解释你到底在这里干什么？}
### {1215}{}{That's how, you don't want to accept the rules? You're walking a dangerous path, stranger. Then explain to me what the hell are you doing here?}
{1215}{}{这就是为什么，你不想接受规则？你走的路很危险，陌生人。然后向我解释你到底在这里干什么？}
### {216}{}{I'm from a small village far from here. We just call it the Villa.}
{216}{}{我来自一个远离这里的小村庄。我们就叫它别墅。}
### {217}{}{I've never heard of such a thing. Let's assume it's true. What are you doing in my city so far from home?}
{217}{}{我从没听说过这样的事。让我们假设这是真的。你在离家这么远的城市干什么？}
### {218}{}{I'm just traveling. Can I spend the night at your place?}
{218}{}{我只是在旅行。我可以在你家过夜吗？}
### {219}{}{I don't mind. Usually visitors spend the night near the water pump, in the barracks of the caravans.}
{219}{}{我不介意。通常游客会在水泵附近的大篷车营房里过夜。}
### {220}{}{Thank you, Mr. Mayor.}
{220}{}{谢谢你，市长先生。}
### {221}{}{What kind of city do you have if you don't even have a motel? Okay, the barracks will do. Goodbye, Mayor.}
{221}{}{如果你连汽车旅馆都没有，你会是一个什么样的城市？好的，营房就行了。再见，市长。}
### {222}{}{Bustos. My name is Alfred Bustos. Now go. I've spent too much time on you.}
{222}{}{巴斯托斯。我的名字叫阿尔弗雷德·布斯托斯。现在走。我在你身上花了太多时间。}
### {223}{}{[Leave]}
{223}{}{[离开]}

### {224}{}{I'm looking for my people. They were captured by slavers.}
{224}{}{我在找我的人。他们被奴隶贩子抓走了。}
### {225}{}{(raises one eyebrow) Slaves? And are you counting on something else?}
{225}{}{（扬起眉毛）奴隶？你还在指望别的东西吗？}
### {226}{}{Have you heard anything about them?}
{226}{}{你听说过他们吗？}
### {227}{}{Slaveholders sometimes lead their slaves through my town. But I don't ask where they get them from.}
{227}{}{奴隶主有时会带领他们的奴隶穿过我的城镇。但我不会问他们从哪里来的。}
### {228}{}{Where are they being taken?}
{228}{}{他们被带到哪里去了？}
### {229}{}{Some are being taken to work in the south. Others are just pulling the load... listen, stranger... what's your name there?}
{229}{}{一些人被带到南方工作。其他人只是在拉负载...听着，陌生人...你叫什么名字？}
### {1229}{}{Some are being taken to work in the south. Others are just pulling the load... listen, woman... what's your name there?}
{1229}{}{一些人被带到南方工作。其他人只是在拉负载...听着，女人...你叫什么名字？}
### {230}{}{It doesn't matter.}
{230}{}{没关系。}
### {231}{}{.}
{231}{}{。}
### {232}{}{Slaveholders are a serious force. If they took your family, then you have no chance to return their freedom. In addition, my city lives at the expense of caravanners. Don't you dare break this pattern.}
{232}{}{奴隶主是一股强大的力量。如果他们带走了你的家人，那么你就没有机会归还他们的自由。此外，我所在的城市以房车为代价。你不敢打破这种模式。}
### {233}{}{I'm not afraid of the slavers or you. Goodbye, Mayor.}
{233}{}{我不怕奴隶主也不怕你。再见，市长。}
### {234}{}{I just want my family back. You have to understand that, Mr. Mayor.}
{234}{}{我只想让我的家人回来。市长先生，你必须明白这一点。}

### {235}{}{There are no empty seats in the city. You can spend the night in the barracks with the caravans near the water station.}
{235}{}{这个城市没有空座位。你可以在水站附近的营房里和大篷车一起过夜。}
### {236}{}{Bustos. My name is Alfred Bustos. Welcome to my city.}
{236}{}{巴斯托斯。我的名字叫阿尔弗雷德·布斯托斯。欢迎来到我的城市。}
### {237}{}{I need the mayor of this city. I'm from the Sacred Fire Church.}
{237}{}{我需要这个城市的市长。我来自拜火教堂。}
### {238}{}{What a surprise. Usually I am warned about the appearance of the ambassador of your church.}
{238}{}{真是个惊喜。通常我会被警告你们教会大使的出现。}
### {239}{}{Come in. Make yourself at home.}
{239}{}{进来吧，别拘束。}
### {240}{}{What is it this time?}
{240}{}{这次是什么？}
### {241}{}{You again? What is it this time?}
{241}{}{你又来了？这次是什么？}
### {242}{}{You again? I told you to get out of my city.}
{242}{}{你又来了？我告诉过你离开我的城市。}
### {243}{}{Goodbye, Count Bustos.}
{243}{}{再见，巴斯托斯伯爵。}
### {244}{}{(When you enter the office, you find the local mayor leaning wearily on the table. In the second hand he holds a bottle of alcohol. "Oh ..." - he says, seeing your colorful robe.) What a surprise. Usually I am warned about the appearance of the ambassador of your church.}
{244}{}{（当你走进办公室时，你会发现当地市长疲惫地靠在桌子上。他用另一只手拿着一瓶酒。“哦……”——他说，看到你五颜六色的长袍。）真是令人惊讶。通常我会被警告你们教会大使的出现。}
### {245}{}{I'm passing through here.}
{245}{}{我要经过这里。}
### {246}{}{Sure. Make yourself comfortable. Are you on your way to Two-Sun? Is there anything I can do to help?}
{246}{}{当然让自己舒服一点。你在去二日的路上吗？有什么我能帮忙的吗？}
### {247}{}{I'm interested in a slave convoy. Perhaps such a one took place here recently.}
{247}{}{我对奴隶车队感兴趣。也许最近在这里发生了这样一件事。}
### {248}{}{Recently, the tinkerers have been collecting slaves for some important business. Several such caravans passed through my city. But I don't ask where they got the slaves from.}
{248}{}{最近，修补匠们一直在为一些重要的生意收集奴隶。有几辆这样的大篷车经过我的城市。但我不会问他们从哪里得到这些奴隶。}
### {249}{}{So Two-Sun... Thank you, Mr. Mayor. I'll see you again.}
{249}{}{所以两个太阳...谢谢你，市长先生。我会再见到你的。}

#Bathhouse
### {250}{}{I need to talk to you about the bathhouse.}
{250}{}{我需要和你谈谈澡堂的事。}
### {251}{}{The old abandoned building across the street? What do you care about him?}
{251}{}{街对面那栋废弃的旧建筑？你关心他什么？}
### {252}{}{Just idle curiosity. I don't dare to distract you any more, Mr. Mayor.}
{252}{}{只是无聊的好奇心。市长先生，我再也不敢分散你的注意力了。}
### {253}{}{Well, there is a person applying for this place.}
{253}{}{嗯，有个人在申请这个地方。}
### {254}{}{We have already discussed this with him. In our small town, everyone knows each other. People have been building relationships here for years, and many do not like the appearance of a stranger with a dubious past in the neighborhood. I will not tolerate scammers in my city.}
{254}{}{我们已经和他讨论过了。在我们的小镇上，每个人都互相认识。多年来，人们一直在这里建立关系，许多人不喜欢附近出现一个有着可疑过去的陌生人。我不会容忍我所在城市的骗子。}
### {255}{}{Hmm. And where then is the real owner of the bathhouse?}
{255}{}{嗯。那么澡堂的真正主人在哪里呢？}
### {256}{}{Must have been eaten by radscorpions. These creatures are frequent in our area.}
{256}{}{一定是被蝎子吃了。这些生物在我们地区很常见。}
### {257}{}{It's so awful. I'll have to tell him your refusal.}
{257}{}{太可怕了。我得告诉他你的拒绝。}
### {258}{}{And then remember that I don't like people poking their noses into other people's affairs.}
{258}{}{然后请记住，我不喜欢人们对别人的事情嗤之以鼻。}
### {259}{}{Uh, okay, I'll remember.}
{259}{}{好吧，我会记住的。}
### {260}{}{I see. I can rid you of this type once and for all.}
{260}{}{我明白了。我可以一劳永逸地让你摆脱这种类型。}
### {261}{}{Sounds good. I'll pay 100 caps, but don't mention my name anywhere. I don't want my reputation to suffer.}
{261}{}{听起来不错。我会付100个瓶盖，但不要在任何地方提到我的名字。我不想让我的名誉受损。}
### {262}{}{You can rely on me, Mr. Mayor.}
{262}{}{市长先生，你可以相信我。}
### {263}{}{In that case, I want to buy the rights to the bathhouse for 250 caps.}
{263}{}{在这种情况下，我想以250顶的价格买下澡堂的使用权。}
### {264}{}{Well, that's fair. Bring the bottlecaps in, I'll draw up a bill of sale for the bathhouse.}
{264}{}{这很公平。把水瓶拿进来，我会为澡堂起草一份销售清单。}
### {265}{}{OK, see you later.}
{265}{}{好的，回头见。}
### {266}{}{Here are the bottlecaps, Mr. Mayor.}
{266}{}{市长先生，这是水瓶。}
### {267}{}{I hope you understand what you're signing up for.}
{267}{}{我希望你明白你要报名参加什么。}
### {268}{}{Thank you, Mr. Mayor.}
{268}{}{谢谢你，市长先生。}
### {269}{}{He has a letter confirming the right to own the bathhouse.}
{269}{}{他有一封信，确认他有权拥有这个澡堂。}
### {270}{}{And no one knows where he got it. Stop trying my patience.}
{270}{}{没有人知道他是从哪里得到的。别再考验我的耐心了。}
### {271}{}{Excuse me, Mr. Mayor.}
{271}{}{对不起，市长先生。}
### {272}{}{That's pretty rude of you.}
{272}{}{你太粗鲁了。}
### {273}{}{He has a letter confirming the rights to the bathhouse. And I confirm his identity.}
{273}{}{他有一封确认拥有澡堂使用权的信。我确认了他的身份。}
### {274}{}{Well, you managed to convince me. But let this scoundrel know that no one was waiting for him here.}
{274}{}{好吧，你设法说服了我。但让这个恶棍知道，没有人在这里等他。}
### {275}{}{As you say, Mr. Mayor.}
{275}{}{正如你所说，市长先生。}
### {276}{}{That's not very kind of you.}
{276}{}{你真不太好。}
### {277}{}{It has something to do with the recent war in Casa Grande, doesn't it? Are you afraid of revenge?}
{277}{}{这与最近发生在格兰德之家的战争有关，不是吗？你害怕报复吗？}
### {278}{}{(sigh) Although I didn't kill the owner of the bathhouse, others did... against the background of the war that I started.}
{278}{}{（叹气）虽然我没有杀死澡堂的主人，但其他人...在我发动战争的背景下。}
### {279}{}{I think the guy already knows. But it seems that he is only interested in business.}
{279}{}{我想那家伙已经知道了。但他似乎只对商业感兴趣。}
### {280}{}{Then it's a big risk for you. I'll tell the guy your refusal.}
{280}{}{那么这对你来说是一个很大的风险。我会告诉那个家伙你的拒绝。}
### {281}{}{It's true? Then it's worth talking to him. Although it is unlikely to atone for my sins.}
{281}{}{这是真的吗？那就值得和他谈谈了。虽然这不太可能为我赎罪。}
### {282}{}{Great. I'll go to cheer him up.}
{282}{}{太棒了我去给他打气。}
### {283}{}{We know each other well. I guarantee that he can be trusted.}
{283}{}{我们彼此很了解。我保证他是可以信任的。}
### {284}{}{Then it's worth talking to him. Although it is unlikely to atone for my sins.}
{284}{}{那就值得和他谈谈了。虽然这不太可能为我赎罪。}
### {285}{}{Great. I'll go to cheer him up.}
{285}{}{太棒了我去给他打气。}
### {286}{}{? It is not surprising that a person with such a name cannot sit still. }
{286}{}{？一个有这样名字的人坐不住也就不足为奇了。}
### {287}{}{If it's a joke, it's a bad one. If something happens to you, they will think about me, because no one will realize that there are two people with the same name in the city. It will be very unpleasant... }
{287}{}{如果这是个笑话，那就是个坏笑话。如果你出了什么事，他们会想到我，因为没有人会意识到这个城市里有两个同名的人。这将是非常不愉快的...}

### {290}{}{The stranger won't bother you anymore.}
{290}{}{陌生人不会再打扰你了。}
### {291}{}{Very good. I don't like to dirty my hands.}
{291}{}{很好。我不喜欢弄脏我的手。}
### {292}{}{[Next]}
{292}{}{[下一个]}
### {293}{}{All work should be paid adequately. Here are your 100 caps. But don't forget - I have nothing to do with this incident.}
{293}{}{所有的工作都应该得到足够的报酬。这是你的100个瓶盖。但别忘了，我与这件事无关。}
### {294}{}{No one will know anything, Mr. Mayor.}
{294}{}{没有人会知道任何事情，市长先生。}
### {295}{}{It is not in my interest to destroy relationships with potential clients.}
{295}{}{破坏与潜在客户的关系不符合我的利益。}

#Stop dialog
### {300}{}{I don't know what you want to achieve, but there are more enemies on your list. Get out of my town. I don't need idiots like you.}
{300}{}{我不知道你想实现什么，但你的名单上还有更多的敌人。滚出我的城市。我不需要你这样的白痴。}
### {301}{}{[Exit the building]}
{301}{}{[离开大楼]}
### {302}{}{The guards take you outside.}
{302}{}{警卫把你带到外面。}

### {308}{}{Hi. Imagine some idiot digging graves in our cemetery. Maybe you know who does it?}
{308}{}{你好想象一下，一些白痴在我们的墓地里挖坟墓。也许你知道是谁干的？}
### {309}{}{Is someone digging graves? I don't know anything about it.}
{309}{}{有人在挖坟墓吗？我对此一无所知。}
### {310}{}{I remember you. After your appearance, graves were found dug in the cemetery.}
{310}{}{我记得你。你出现后，在墓地里发现了坟墓。}
### {311}{}{Strange coincidence, isn't it?}
{311}{}{奇怪的巧合，不是吗？}
### {312}{}{So what? Are you accusing me of something?}
{312}{}{那又怎样？你是在指责我吗？}
### {313}{}{I don't believe in coincidences. If at least one piece of evidence appears against you in this case, then you will be severely punished. Understand this and don't do anything stupid.}
{313}{}{我不相信巧合。在这种情况下，如果至少有一条证据对你不利，那么你将受到严厉惩罚。明白这一点，不要做任何愚蠢的事。}
### {314}{}{Wow, how scary.}
{314}{}{哇，真可怕。}
### {315}{}{It seems that you are out of your mind if you behave like this with a representative of the authorities. Usually there is a lot of leniency for fools, but not in this city. We are tired of endless problems. So don't try my patience. Is that clear?}
{315}{}{如果你对当局的代表这样做，你似乎疯了。通常对傻瓜有很多宽容，但在这个城市却没有。我们厌倦了没完没了的问题。所以不要考验我的耐心。清楚吗？}
### {316}{}{I see.}
{316}{}{我明白了。}
### {317}{}{I have nothing to do with it, Mr. Mayor.}
{317}{}{市长先生，我与此事无关。}
### {318}{}{Good. For now, we will consider it that way. Don't disappoint me.}
{318}{}{好的目前，我们将这样考虑。别让我失望。}
### {319}{}{Of course, Count Bustos. No problem.}
{319}{}{当然，巴斯托斯伯爵。没问题。}

### {320}{}{Security says you fixed the street lamp?}
{320}{}{保安说你修好了路灯？}
### {1320}{}{Security says you fixed the street lamp?}
{1320}{}{保安说你修好了路灯？}
### {321}{}{Exactly.}
{321}{}{确切地}
### {322}{}{I don't understand why you want to do this. But if you wanted to make an impression, then you succeeded. Thank you.}
{322}{}{我不明白你为什么要这么做。但如果你想给人留下深刻印象，那么你就成功了。非常感谢。}
### {1322}{}{I don't understand why you want to do this. But if you wanted to make an impression, then you succeeded. Thank you.}
{1322}{}{我不明白你为什么要这么做。但如果你想给人留下深刻印象，那么你就成功了。非常感谢。}
### {323}{}{Won't they give me something for this?}
{323}{}{他们不会为此给我点什么吗？}
### {324}{}{I didn't ask you to fix the lantern. But you can take clean water as a reward.}
{324}{}{我没叫你修灯笼。但是你可以用干净的水作为奖励。}
### {325}{}{Thank you, Mr. Mayor.}
{325}{}{谢谢你，市长先生。}
### {326}{}{And this is all your gratitude? Yeah.}
{326}{}{这就是你所有的感激之情？是 啊}
### {327}{}{I just like to dig into old technology. You're welcome.}
{327}{}{我只是喜欢钻研旧技术。不客气。}
### {328}{}{You have raised your status in the eyes of the mayor, and therefore the rest of the city.}
{328}{}{你提高了你在市长眼中的地位，也因此提高了整个城市的地位。}
### {329}{}{Aha.}
{329}{}{啊哈。}

### {330}{}{Your appearance is one continuous trouble.}
{330}{}{你的外表是一个持续的麻烦。}
### {331}{}{Really?}
{331}{}{真正地}
### {332}{}{What are you talking about?}
{332}{}{你在说什么？}
### {333}{}{A corpse of one of the residents was found near the railway station. Do you know anything about this?}
{333}{}{其中一名居民的尸体在火车站附近被发现。你知道这件事吗？}
### {334}{}{No, I don't know anything.}
{334}{}{不，我什么都不知道。}
### {335}{}{Okay. We have yet to find out what happened there. Don't try to keep silent if you know something. Now go, I have a lot of work to do.}
{335}{}{可以我们还没有弄清楚那里发生了什么。如果你知道什么，不要试图保持沉默。现在走吧，我有很多工作要做。}
### {336}{}{[Leave the mayor alone]}
{336}{}{[别管市长]}
### {337}{}{One of the residents has disappeared. She was last seen near the train station, where she was catching iguanas. Do you know anything about it?}
{337}{}{其中一名居民失踪了。她最后一次露面是在火车站附近，当时她正在那里抓鬣蜥。你知道这件事吗？}
### {338}{}{The Radscorpions must have eaten her. There are plenty of them there.}
{338}{}{一定是雷蝎子吃了她。那里有很多。}
### {339}{}{Most likely. And yet you know that Radscorpions have turned up there. If you find out, be sure to let me know. Now go, I have a lot of work to do.}
{339}{}{很有可能。但你知道，Radscorpion已经出现在那里了。如果你发现了，一定要告诉我。现在走吧，我有很多工作要做。}
### {340}{}{She was not destined to reach the city. Radscorpions are to blame for this.}
{340}{}{她注定不能到达这个城市。这要归咎于辐射蝎子。}
### {341}{}{That's it. Well, that sounds plausible. While you can go.}
{341}{}{就是这样。听起来很有道理。当你可以去的时候。}
### {342}{}{[Leave]}
{342}{}{[离开]}

#Questions
### {350}{}{I'm looking for a tinsmith who was sent to you as an ambassador.}
{350}{}{我在找一位被派来担任大使的锡匠。}
### {351}{}{Didn't he go back to Two-Sun? In that case, I do not know where he can be.}
{351}{}{他不是回到二日吗？那样的话，我不知道他会在哪里。}
### {352}{}{He was here?}
{352}{}{他在这里？}
### {353}{}{Yes, but he disappeared without saying a word. I thought he just left.}
{353}{}{是的，但他一声不吭就消失了。我以为他刚离开。}
### {354}{}{And you didn't see anything strange about it?}
{354}{}{你没发现什么奇怪的地方吗？}
### {355}{}{The tinkerers consider us mere mortals to be something like savages. They are a strange people, you can expect anything from them. Therefore, I did not worry about the quiet departure of our guest. Surely he is already among his own.}
{355}{}{修补匠们认为我们这些凡人有点像野蛮人。他们是一个奇怪的人，你可以从他们那里得到任何东西。因此，我并不担心我们的客人安静地离开。他肯定已经是自己人了。}
### {356}{}{No, he didn't go back to Two-Sun. Master Hard asked me to find him.}
{356}{}{不，他没有回到《太阳二号》。哈德大师让我去找他。}
### {357}{}{Ah, I understand. Well, I've told you everything I know. You can ask around somewhere else.}
{357}{}{啊，我明白了。我已经把我所知道的都告诉你了。你可以四处打听。}
### {358}{}{I will do so. Goodbye.}
{358}{}{我会的，再见。}
### {359}{}{In my opinion, something is not clean here. You're lucky, Mayor, if his disappearance has nothing to do with you.}
{359}{}{在我看来，这里有些地方不干净。你很幸运，市长，如果他的失踪与你无关。}
### {360}{}{It seems that the locals don't like tinsmiths. Who could wish him harm?}
{360}{}{看来当地人不喜欢铁匠。谁会希望他受到伤害？}
### {361}{}{Hold your tongue, mercenary. We are indebted to the tinsmiths for repairing the water pump and regular caravans. None of the locals would dream of harming them.}
{361}{}{住口，唯利是图。我们感谢修理水泵和普通大篷车的铁匠。当地人做梦也不会伤害他们。}
### {1361}{}{Hold your tongue, mercenary. We are indebted to the tinsmiths for repairing the water pump and regular caravans. None of the locals would dream of harming them.}
{1361}{}{住口，唯利是图。我们感谢修理水泵和普通大篷车的铁匠。当地人做梦也不会伤害他们。}
### {362}{}{And yet I will check this version. Goodbye.}
{362}{}{但我会检查这个版本。再见}
### {363}{}{Such confidence breeds even more doubts, Mayor. Hope she doesn't let you down.}
{363}{}{市长，这种信心会滋生更多的疑虑。希望她不要让你失望。}
### {364}{}{Don't you think his disappearance is strange?}
{364}{}{你不觉得他的失踪很奇怪吗？}
### {365}{}{Is he sure he got to Casa Grande?}
{365}{}{他确定他到了格兰德之家吗？}
### {366}{}{He never returned to Two-Sun. I was asked to find him.}
{366}{}{他再也没有回到《太阳二号》。我被要求去找他。}
### {367}{}{Looks like I'm wasting my time with you. I'm going to look for a tinsmith elsewhere.}
{367}{}{看来我在浪费时间和你在一起。我要去别处找一个锡匠。}
### {368}{}{Surely this is so. Sorry for distracting you from business.}
{368}{}{当然是这样。很抱歉让你分心了。}
### {1368}{}{Surely this is so. Sorry to distract you from your business.}
{1368}{}{当然是这样。很抱歉分散了你的注意力。}
### {369}{}{And where did he stay during the visit?}
{369}{}{访问期间他住在哪里？}

### {370}{}{I want to ask about the city, I don't know it well yet.}
{370}{}{我想问一下这个城市的情况，我还不太了解它。}
### {371}{}{Casa Grande is my treasure. What do you want to know?}
{371}{}{格兰德之家是我的宝贝。你想知道什么？}
### {372}{}{All you need to know is the direction to the exit of the city.}
{372}{}{你所需要知道的就是去城市出口的方向。}
### {373}{}{No one knows Casa Grande better than me. What do you want to know?}
{373}{}{没有人比我更了解卡萨格兰德。你想知道什么？}
### {374}{}{Now I know enough. Goodbye.}
{374}{}{现在我知道的够多了。再见}
### {375}{}{Let me take a little more of your time.}
{375}{}{让我多花点时间给你。}
### {376}{}{In a former moonshiner's shack in the east. Tinsmiths don't like to be around... "ordinary" people.}
{376}{}{在东部一个曾经的登月者的棚屋里。铁匠们不喜欢在身边...“普通”人。}

### {380}{}{What can I do in this city?}
{380}{}{在这个城市我能做什么？}
### {381}{}{Casa Grande is a small town. We used to have a saloon that was famous all over the neighborhood for its own booze and old music. But the bar is closed, and the jukebox is broken, and now people are entertaining themselves.}
{381}{}{卡萨格兰德是一个小镇。我们曾经有一家酒吧，它以自己的酒和古老的音乐而闻名于整个社区。但酒吧关门了，自动点唱机坏了，现在人们在自娱自乐。}
### {382}{}{What happened?}
{382}{}{发生了什么？}
### {383}{}{A robbery shootout in a bar. But this is a thing of the past. Just keep in mind that the bar is closed.}
{383}{}{酒吧里的抢劫枪战。但这已经成为过去。请记住酒吧已经关门了。}
### {384}{}{We both know that it wasn't exactly a "rogue" shootout.}
{384}{}{我们都知道这并不完全是一场“流氓”枪战。}
### {385}{}{You talk too much. Then in the bar my people ambushed the enemy clan. The bartender got a stray bullet. I'm sorry, he was a sincere person.}
{385}{}{你说得太多了。然后在酒吧里，我的人伏击了敌人的部落。酒保被流弹击中。对不起，他是个真诚的人。}
### {386}{}{Thank you for the honest answer. I think it's better to change the subject.}
{386}{}{谢谢你的诚实回答。我认为最好换个话题。}
### {387}{}{Wow, your own booze?}
{387}{}{哇，你自己的酒？}
### {388}{}{Yes, local production. Have you ever tasted this wonderful drink? The moonshiner supplied us with beer and traded it with Phoenix. Eh, if it weren't for those damn radscorpions, he would still continue to bring a good income to the treasury.}
{388}{}{是的，本地生产。你尝过这种美妙的饮料吗？月光客给我们提供了啤酒，并与凤凰城进行了交易。呃，如果不是那些该死的蝎子，他还会继续给财政部带来不错的收入。}
### {389}{}{I've seen tequila production in Phoenix before.}
{389}{}{我以前在凤凰城看过龙舌兰酒的生产。}
### {390}{}{Really? Sometimes caravans bring fire agave juice from the south for the Phoenix. This competition was like a lump in our brewer's throat. And now we are buying this Phoenix swill ourselves.}
{390}{}{真正地有时大篷车从南方为凤凰带来火龙舌兰汁。这场比赛让我们的酿酒商如虎添翼。现在我们要自己买这只凤凰雨燕。}
### {391}{}{Enough of the sad stuff. We need to change the subject.}
{391}{}{受够了悲伤的东西。我们需要改变话题。}
### {392}{}{Is there a store here?}
{392}{}{这里有商店吗？}
### {393}{}{If you need water, contact the water station. We take the rest of the goods from the caravaneers in the parking lot nearby.}
{393}{}{如果你需要水，请联系供水站。我们从附近停车场的房车司机那里拿走了剩下的货物。}
### {394}{}{Why are there so many caravans here?}
{394}{}{为什么这里有这么多大篷车？}
### {395}{}{Because we have a lot of water and we are halfway between Phoenix and Two-Sun settlement. A good position, except for the damn highway robbers.}
{395}{}{因为我们有很多水，而且我们在菲尼克斯和两个太阳定居点之间。一个不错的位置，除了那些该死的高速公路劫匪。}
### {396}{}{Rumor has it that the tinsmiths are no longer in business. How will this affect Casa Grande?}
{396}{}{有传言说，锡匠已经不在营业了。这将如何影响Casa Grande？}
### {397}{}{In addition to the tinsmiths, there are other settlements in the south. And we can still trade water. Besides, after hearing this story, a lot of looters rushed to the south. Therefore, we will stay afloat for now, but what will happen next?}
{397}{}{除了锡匠，南部还有其他定居点。我们仍然可以进行水交易。此外，听到这个故事后，许多抢劫者涌向南方。因此，我们暂时会维持生计，但接下来会发生什么呢？}
### {398}{}{They say the Phoenix Fire Church has been destroyed.}
{398}{}{他们说凤凰火教堂已经被摧毁。}
### {399}{}{Yes, and that's a problem. In a sense, the Church actively supported this caravan route. There will be fewer caravans without it. But over time, someone will surely take their place.}
{399}{}{是的，这是个问题。从某种意义上说，教会积极支持这条商队路线。没有它，大篷车会越来越少。但随着时间的推移，肯定会有人取代他们的位置。}
### {400}{}{What are these highway robbers?}
{400}{}{这些高速公路劫匪是什么？}
### {401}{}{Different rabble comes across along the tenth highway. These bandits rob caravans and other travelers, which is why we suffer losses.}
{401}{}{不同的乌合之众沿着第十条高速公路穿过。这些土匪抢劫大篷车和其他旅行者，这就是我们遭受损失的原因。}
### {402}{}{Did you try to catch them?}
{402}{}{你试图抓住他们了吗？}
### {403}{}{Who? Two dozen disparate and constantly changing gangs? This fight will never end. You kill some, others will come in their place. It is more important to deal with security inside the city.}
{403}{}{谁二十多个不同的、不断变化的帮派？这场斗争永远不会结束。你杀了一些人，其他人就会取而代之。处理城市内部的安全问题更为重要。}
### {404}{}{Let's forget about the mainline workers for now, there are other questions.}
{404}{}{让我们暂时忘记主线工人，还有其他问题。}
### {405}{}{I'm interested in that water station.}
{405}{}{我对那个供水站很感兴趣。}
### {406}{}{Talk to Joe Sullivan at the station about it. He knows her like the back of his hand.}
{406}{}{和车站的乔·沙利文谈谈。他对她了如指掌。}
### {407}{}{Talk to someone at the station about it.}
{407}{}{和车站的人谈谈这件事。}
### {408}{}{OK, I'll look in there later.}
{408}{}{好的，我稍后再进去看看。}
### {409}{}{Great idea, I'll go there right now.}
{409}{}{好主意，我现在就去。}
### {410}{}{Tell Sullivan about it. Who is he?}
{410}{}{告诉沙利文，他是谁？}
### {411}{}{I don't discuss my people with strangers. If you want to get to know Sullivan, get to know him personally.}
{411}{}{我不与陌生人讨论我的人。如果你想了解沙利文，就要亲自了解他。}
### {412}{}{One more question before leaving.}
{412}{}{离开前还有一个问题。}
### {413}{}{Then I'll go straight to him. Goodbye.}
{413}{}{那我就直接去找他。再见}
### {414}{}{Tell Sullivan about it. Is he a good person?}
{414}{}{把这件事告诉沙利文。他是个好人吗？}
### {415}{}{He's like a brother to me. We started out together. I knew how to negotiate with people, and he knew how to solve problems. It would be hard without John.}
{415}{}{他就像我的兄弟。我们是一起开始的。我知道如何与人谈判，他也知道如何解决问题。没有约翰就很难了。}
### {416}{}{Looks like you're really like brothers. But I'm more interested in the city.}
{416}{}{看起来你们真的很像兄弟。但我对这座城市更感兴趣。}
### {417}{}{Usually the word "brother" loses all meaning when it comes to business.}
{417}{}{当谈到生意时，“兄弟”这个词通常失去了所有的意义。}
### {418}{}{I'll let it pass. Perhaps, in a big city, the caps are separated, but this is not the case here. I appreciate John as a reliable person. The most reliable in Casa Grande.}
{418}{}{我会让它过去的。也许，在大城市里，瓶盖是分开的，但这里不是这样。我很欣赏约翰是个可靠的人。卡萨格兰德最可靠的。}
### {419}{}{Was Sullivan a friend to you?}
{419}{}{沙利文是你的朋友吗？}
### {420}{}{Don't mention his name. We started out together, and I could not have expected such a betrayal. Now I don't even want to hear about him.}
{420}{}{别提他的名字。我们一起出发，我没想到会有这样的背叛。现在我甚至不想听到他的消息。}
### {421}{}{Didn't you previously call him "the most reliable person in Casa Grande"?}
{421}{}{你以前不是说他是“格兰德之家最可靠的人”吗？}
### {422}{}{It looks like you're really hurt by this. Let's not talk about it anymore.}
{422}{}{看起来你真的受到了伤害。我们别再谈论它了。}
### {423}{}{(fist bump on the table) Sullivan... He got what he deserved for his meanness. I can only erase this traitor from my life. And you'd better keep quiet until our relationship has completely deteriorated.}
{423}{}{（拳头撞在桌子上）沙利文...他的卑鄙得到了应有的惩罚。我只能把这个叛徒从我的生活中抹去。你最好保持沉默，直到我们的关系完全恶化。}
### {424}{}{Sorry, we won't talk about it anymore.}
{424}{}{对不起，我们不再谈这个了。}
### {425}{}{If you want to close your eyes to past mistakes, it's up to you. Change the subject?}
{425}{}{如果你想对过去的错误视而不见，那就取决于你自己。换个话题？}
### {426}{}{You really are bringing one death to your city. I've had enough of these creepy stories.}
{426}{}{你真的给你的城市带来了一个死亡。我受够了这些令人毛骨悚然的故事。}
{427}{}{}
### {428}{}{I shouldn't have gotten involved in this shit at all. Goodbye, Mayor.}
{428}{}{我根本不应该卷入这件事。再见，市长。}
### {429}{}{Weak argument, Mayor. Very weak.}
{429}{}{论据不足，市长。非常虚弱。}

### {430}{}{You have an unusually large cemetery for such a small population.}
{430}{}{对于这么少的人口来说，你有一个不同寻常的大墓地。}
### {431}{}{You shouldn't go in there. And ask about things that don't concern you in any way.}
{431}{}{你不应该进去。问一些与你无关的事情。}
### {432}{}{Sorry, I won't do it anymore.}
{432}{}{对不起，我不会再做了。}
### {433}{}{And yet. What happened here?}
{433}{}{然而。这里发生了什么？}
### {434}{}{A little bit of everything - robbers, scorpions... And enough about it. People don't like it when their past is stirred up.}
{434}{}{什么都有一点点——强盗，蝎子...这已经够了。人们不喜欢他们的过去被搅乱。}
### {435}{}{I know what happened here in the past. You seized power in Casa Grande by force.}
{435}{}{我知道过去这里发生了什么。你武力夺取了卡萨格兰德的政权。}
### {436}{}{That robber claimed that you killed half the population to come to power.}
{436}{}{那个强盗声称你为了掌权杀死了一半的人。}
### {437}{}{Difficult times require difficult decisions. If I hadn't started the fight then, someone else would have started it. This is the natural state of things.}
{437}{}{困难时期需要艰难的决定。如果当时不是我挑起的，其他人也会挑起的。这是事情的自然状态。}
### {438}{}{Was it inevitable?}
{438}{}{这是不可避免的吗？}
### {439}{}{Too many people and too few resources. This city survives by a water pump and as a camp for caravans. There is nothing else in this desert that could give life. As a result, many did not find a place for themselves, looting and clan wars began.}
{439}{}{人太多，资源太少。这座城市靠水泵和商队营地生存。在这片沙漠中，没有任何其他东西可以赋予生命。结果，许多人找不到自己的住处，抢劫和部族战争开始了。}
### {440}{}{Now I understand why you are constantly drunk.}
{440}{}{现在我明白你为什么总是喝醉了。}
### {441}{}{So that's why you have so many bodyguards.}
{441}{}{所以这就是为什么你有这么多保镖。}
### {442}{}{You can't say goodbye to the past. This is our cross.}
{442}{}{你不能和过去说再见。这是我们的十字架。}
### {443}{}{I happened to visit a place where an ancient factory was restored. There, too, many people died fighting for him.}
{443}{}{我碰巧参观了一个修复了古老工厂的地方。在那里，也有许多人为他而战而牺牲。}
### {444}{}{Really? Heh, poor consolation. But I am glad that the wastelands are finally being transformed. I hope that during my lifetime I will still see Korvega on the move, as in old books.}
{444}{}{真正地呵呵，可怜的安慰。但我很高兴荒地终于被改造了。我希望在我的有生之年，我仍然能看到科尔维加像旧书中那样四处奔波。}
### {445}{}{You're a monster. How could you kill dozens of people for your own benefit?}
{445}{}{你是个怪物。你怎么能为了自己的利益杀死几十个人？}
### {446}{}{If this conversation is too hard for you, then let's talk about something else.}
{446}{}{如果这次谈话对你来说太难了，那就让我们谈谈别的吧。}
### {447}{}{Now I know what to do with my head for the near future. Goodbye.}
{447}{}{现在我知道在不久的将来我的脑袋该怎么办了。再见}
### {448}{}{Close your mouth and listen. I AM THE MAYOR OF THIS CITY. I'm responsible for him. And I will not allow ANYONE to desecrate its good name. Who are you to judge me? Just a stranger who was passing by. So go your own way.}
{448}{}{闭上你的嘴听。我是这个城市的市长。我对他负责。我不会允许任何人亵渎它的好名声。你是谁来评判我？只是一个路过的陌生人，走你自己的路吧。}
### {449}{}{Your truth. I'm just a traveler who stopped by to drink. Goodbye, Mayor.}
{449}{}{你的真相。我只是一个路过喝酒的旅行者。再见，市长。}
### {1449}{}{Your truth. I'm just a traveler who stopped by to drink. Goodbye, Mayor.}
{1449}{}{你的真相。我只是一个路过喝酒的旅行者。再见，市长。}

#The first quest
### {450}{}{Is there a job in the city? I could use some money while I'm here.}
{450}{}{这个城市有工作吗？我在这里的时候可以用点钱。}
### {451}{}{I don't have a job for you.}
{451}{}{我没有工作给你。}
### {452}{}{Clear. But maybe you can answer a couple of questions?}
{452}{}{清楚的但也许你可以回答几个问题？}
### {453}{}{OK, I'll go ask the rest of the residents.}
{453}{}{好的，我去问问其他的居民。}
### {454}{}{I don't have a job for you... However, you can solve one problem.}
{454}{}{我没有工作给你...然而，你可以解决一个问题。}
### {455}{}{What are we talking about?}
{455}{}{我们在说什么？}
### {456}{}{Highway robbers robbed one of the caravans near the railway station and locked themselves in with the goods inside. It seems that they are not going to leave, as if they are provoking or testing us. Go there and find out what they want.}
{456}{}{高速公路劫匪在火车站附近抢劫了一辆大篷车，并将自己和车内的货物锁在了车内。他们似乎不会离开，好像在挑衅或考验我们。去那里看看他们想要什么。}
### {457}{}{Are your guys standing here for show?}
{457}{}{你们是来表演的吗？}
### {458}{}{Is there really no sheriff here for these purposes?}
{458}{}{这里真的没有治安官吗？}
### {459}{}{No one wants to risk their lives for a box of old rags. We hope that the bandits will get tired of being locked up and they will leave on their own.}
{459}{}{没有人愿意为了一盒旧抹布而冒着生命危险。我们希望土匪们厌倦被关起来，他们会自己离开。}
### {460}{}{I need caps, but I'm not going to take that risk. Look for someone else.}
{460}{}{我需要瓶盖，但我不会冒这个险。找其他人。}
### {461}{}{OK, I'll get rid of these robbers.}
{461}{}{好的，我会把这些强盗赶走的。}
### {462}{}{Great. The station is south of here.}
{462}{}{太棒了车站在这里的南边。}
### {463}{}{Prepare the reward. Soon the scum will regret their audacity.}
{463}{}{准备奖励。渣滓很快就会后悔他们的厚颜无耻。}

### {470}{}{And here you are. Come in, have a seat. After that mess at the bar, I wanted to relax a little and have a drink. Pour yourself something. After all, it is thanks to you that my daughter and I still enjoy our freedom.}
{470}{}{你来了。进来，坐下。在酒吧的那次混乱之后，我想放松一下，喝一杯。给自己倒点什么。毕竟，多亏了你，我和女儿仍然享受着我们的自由。}
### {471}{}{A strange story. Count, why did the robbers get so close to the city?}
{471}{}{一个奇怪的故事。伯爵，为什么强盗们离城市这么近？}
### {472}{}{Highway workers usually rob travelers on the highway and are afraid to come close to the city. But they knew what to do, because their leader once lived in Casa Grande... However, it's a long story, and I still haven't paid you for your help.}
{472}{}{高速公路工人通常在高速公路上抢劫旅行者，他们害怕靠近城市。但他们知道该怎么办，因为他们的领袖曾经住在格兰德之家...不过，说来话长，我还没有付钱请你帮忙。}
### {473}{}{[Next]}
{473}{}{[下一个]}
### {474}{}{Here are 250 caps. And you can earn more.}
{474}{}{这里有250个瓶盖。你可以赚更多。}
### {475}{}{More? How much more?}
{475}{}{更多还有多少？}
### {476}{}{I'm listening. Who's the problem this time?}
{476}{}{我在听。这次谁有问题？}
### {477}{}{Your freedom cost someone their life, didn't it?}
{477}{}{你的自由让人付出了生命的代价，不是吗？}
### {478}{}{Your tongue is too loose for a mercenary. As you know, highway workers rob travelers on the highway. But the robbers in the bar had personal scores. However, it's a long story, and I still haven't paid you.}
{478}{}{你的舌头太松了，不适合雇佣兵。正如你所知，高速公路工人在高速公路上抢劫旅行者。但是酒吧里的劫匪有个人的分数。不过，说来话长，我还没有付钱给你。}
### {479}{}{[Next]}
{479}{}{[下一个]}
### {480}{}{And here you are... Come in. After that bar fight, I need a drink.}
{480}{}{你来了...进来吧。酒吧斗殴之后，我需要喝一杯。}
### {481}{}{I am very sorry that your daughter died.}
{481}{}{我对你女儿的去世感到非常抱歉。}
### {482}{}{To hell with regrets! I once made the mistake of driving some residents out of the city instead of executing them. And they came back. Now I have to take cruel revenge on the mainline...}
{482}{}{带着遗憾见鬼去吧！我曾经犯过一个错误，把一些居民赶出了城市，而不是处决他们。他们回来了。现在我不得不在主线上进行残酷的报复...}
### {483}{}{[Next]}
{483}{}{[下一个]}
### {484}{}{Are you trying to wash down the problem with alcohol? It won't work.}
{484}{}{你想用酒精来解决这个问题吗？这行不通。}
### {485}{}{What do you understand... (calms himself) Your truth. I once made the mistake of driving some residents out of the city instead of executing them. And they came back. Now I have to take cruel revenge on the mainline...}
{485}{}{你理解什么...（冷静下来）你的真相。我曾经犯过一个错误，把一些居民赶出了城市，而不是处决他们。他们回来了。现在我不得不在主线上进行残酷的报复...}
### {486}{}{[Next]}
{486}{}{[下一个]}
### {487}{}{I think you needed the caps? I will not pay for the disassembly in the bar. But I will pay for a new case.}
{487}{}{我想你需要瓶盖吗？我不会为酒吧里的拆卸买单。但我会为一个新案子买单。}
### {488}{}{What should I do?}
{488}{}{我该怎么办？}
### {489}{}{Those bandits in the bar belonged to the largest clan of highway workers-the Blue Shield Clan. He is known throughout the neighborhood for his ruthless crimes. After robbing the last caravans, these scum got good equipment. So now the whole city is at risk of being held hostage.}
{489}{}{酒吧里的那些土匪属于最大的公路工人家族——蓝盾家族。他因其残忍的罪行而闻名于整个社区。在抢劫了最后一辆大篷车后，这些渣滓得到了很好的装备。所以现在整个城市都有被扣为人质的危险。}
### {490}{}{Are you suggesting we stop them? But how?}
{490}{}{你是在建议我们阻止他们吗？但是怎么做呢？}
### {491}{}{Kill their leader, Ben. I'll pay 500 caps for his head.}
{491}{}{杀死他们的首领本。我愿意为他的头付500个瓶盖。}
### {492}{}{I've been looking for smart people like you for a long time to find their lair and finish off their leader Ben. Without him, the clan will fall apart and, at least for a while, leave us alone.}
{492}{}{很长一段时间以来，我一直在寻找像你这样的聪明人，找到他们的巢穴，干掉他们的领袖本。如果没有他，这个家族将分崩离析，至少在一段时间内，让我们独处。}
### {493}{}{There is no need to explain the whole story. What is the price?}
{493}{}{没有必要解释整个故事。价格是多少？}

#The second quest
### {500}{}{Highway robbers are like scavengers - they stick together in packs and hunt down easy prey on the highways. Small clans do not pose a threat to the city. But there is one big one.}
{500}{}{高速公路劫匪就像拾荒者——他们成群结队地聚在一起，在高速公路上追捕猎物。小部族不会对这座城市构成威胁。但有一个大问题。}
### {501}{}{Let me guess - is that where the robbers who captured your daughter came from?}
{501}{}{让我猜一猜，抓你女儿的强盗是从那里来的吗？}
### {502}{}{Yes. And this is not their first major attack. The Blue Shield Clan is known throughout the district for its ruthless crimes. It includes the most desperate and reckless bastards who have no place in a civilized society.}
{502}{}{对这并不是他们的第一次重大攻击。蓝盾家族以其残忍的罪行闻名于整个地区。其中包括那些在文明社会中没有立足之地的最绝望、最鲁莽的混蛋。}
### {503}{}{Sounds terrible. But is it possible to stop an entire gang by force of mercenaries?}
{503}{}{听起来很糟糕。但是，有可能通过雇佣兵的力量来阻止整个帮派吗？}
### {504}{}{To hell with the background. Just tell me how to find them.}
{504}{}{让背景见鬼去吧。告诉我怎么找到它们。}
### {505}{}{There's no need to kill a whole crowd. I will pay 500 caps for the head of their leader, Ben. You'll get the same amount if you destroy their fuel depot.}
{505}{}{没有必要杀了一大群人。我将为他们的领袖本的领袖支付500个瓶盖。如果你摧毁他们的燃料库，你会得到同样的数量。}
### {506}{}{All these deaths will be in my nightmares for more than one night. I'm washing my hands of it this time.}
{506}{}{所有这些死亡都将在我的噩梦中持续一个多晚上。这次我要洗手不干了。}
### {507}{}{Well, it's a pity. I was already hoping that this was really a real fighter in front of me. But don't rush to a decision. The problem won't solve itself, and I'm always willing to pay for a good job.}
{507}{}{很遗憾。我已经希望这真的是一个真正的战士在我面前。但不要急于做出决定。这个问题不会自行解决，我总是愿意为一份好工作付出代价。}
### {508}{}{Goodbye.}
{508}{}{再见}
### {509}{}{Great, consider this Ben's skull already in your hands.}
{509}{}{太好了，想想这个本的头骨已经在你手里了。}
### {510}{}{Everything is simple. Bring the head and you'll get a reward. Good luck.}
{510}{}{一切都很简单。带上人头，你会得到奖励的。祝你好运}
### {511}{}{Goodbye.}
{511}{}{再见}
### {512}{}{I need to know more about these mainline drivers.}
{512}{}{我需要更多地了解这些主线司机。}

### {520}{}{About the mainline workers.}
{520}{}{关于主线工人。}
### {521}{}{What news?}
{521}{}{什么消息？}
### {522}{}{None yet. I just want to say that I am working on this problem. Goodbye.}
{522}{}{还没有。我只想说我正在解决这个问题。再见}
### {523}{}{Why is this clan so strong?}
{523}{}{为什么这个家族如此强大？}
### {524}{}{After the attacks on the last caravans, these robbers received good equipment, which the tinsmiths produced on their machines. In addition, they have huge reserves of combustible mixture. If this goes on, the whole city will soon be held hostage.}
{524}{}{在最后一批商队遭到袭击后，这些劫匪得到了很好的装备，这些装备是锡匠用他们的机器生产的。此外，他们还有大量的可燃混合物储备。如果这种情况继续下去，整个城市很快就会被扣为人质。}
### {525}{}{Where did they get so much fuel from?}
{525}{}{他们从哪里得到这么多燃料？}
### {526}{}{They say they have occupied an old gasoline warehouse and are using it as a fortress. And fuel serves as their weapon.}
{526}{}{他们说，他们占领了一个旧的汽油仓库，并将其用作堡垒。燃料是他们的武器。}
### {527}{}{Tell me about their leader.}
{527}{}{告诉我他们的领导人。}
### {528}{}{His name is Ben. He used to live among us, but I drove him and his gang out of town. That's why he's so familiar to me.}
{528}{}{他的名字叫本。他曾经和我们住在一起，但我把他和他的帮派赶出了城里。这就是为什么他对我如此熟悉。}
### {529}{}{Why is it so important to kill the leader?}
{529}{}{为什么杀死首领这么重要？}
### {530}{}{Without a leader, the clan will fall apart and leave us alone at least for a while.}
{530}{}{如果没有首领，氏族就会分崩离析，至少在一段时间内让我们独处。}
### {531}{}{What's the point of destroying a fuel depot?}
{531}{}{摧毁一个燃料库有什么意义？}
### {532}{}{Fuel serves as a weapon for the gang and helps in survival. And in the future it could be used for trading. In addition, with the burned capacity, it will become more difficult to use the citadel. In any case, such a diversion will greatly shake the gang.}
{532}{}{燃料是帮派的武器，有助于生存。在未来，它可以用于交易。此外，随着容量的消耗，使用城堡将变得更加困难。无论如何，这样的转移会极大地动摇这个团伙。}
### {533}{}{And how will you know if I blow up these warehouses?}
{533}{}{如果我炸毁这些仓库你怎么知道？}
### {534}{}{I'll see the smoke through binoculars. There are eyes and ears everywhere, such an event will not hide from anyone.}
{534}{}{我将用双筒望远镜看到烟雾。到处都是耳目，这样的事件不会瞒着任何人。}
### {535}{}{Where is the main base of the Blue Shields?}
{535}{}{蓝盾的主要基地在哪里？}
### {536}{}{Judging by the words of the caravaneers, it is somewhere in the northeast of us.}
{536}{}{根据房车司机的话判断，它在我们东北部的某个地方。}
### {537}{}{How did it happen that the residents of Casa Grande got mixed up among the mainline workers?}
{537}{}{Casa Grande的居民是如何与主线工人混在一起的？}
### {538}{}{It's an old and long story. When I got to the post of mayor, the first thing I did was evict all the scum from the city. As it turned out, some of them survived and began to terrorize highways.}
{538}{}{这是一个古老而漫长的故事。当我担任市长时，我做的第一件事就是把所有的渣滓赶出这个城市。事实证明，他们中的一些人幸存下来，并开始恐吓高速公路。}
### {539}{}{I've learned enough. See you later, Count.}
{539}{}{我已经学够了。回头见，伯爵。}
### {1539}{}{I've learned enough. See you later, Count.}
{1539}{}{我已经学够了。回头见，伯爵。}
### {540}{}{Here is the head of your enemy. You recognize him, don't you?}
{540}{}{这是你敌人的头颅。你认出他了，不是吗？}
### {541}{}{(silently looks at the head with contempt and hatred for a while, then waves his hand away) Throw this stuff out on the wastelands. Let the radscorpions eat the last reminder of the mainline workers.}
{541}{}{（带着轻蔑和仇恨默默地看了看他的头，然后挥手离开）把这些东西扔到荒地上。让雷达蝎子吃掉最后一个提醒主线工人的东西。}
### {542}{}{Whatever you say, Count.}
{542}{}{不管你说什么，伯爵。}
### {543}{}{No, don't touch it. I'll hang this head on the railroad at the entrance to the city. Let people know what awaits them in case of disobedience to the authorities.}
{543}{}{不，别碰它。我会把这个头挂在城市入口处的铁路上。让人们知道，如果他们不服从当局，等待他们的是什么。}
### {544}{}{Good idea. }
{544}{}{好主意}
### {545}{}{Then don't forget to sign who killed him.}
{545}{}{那就别忘了签上谁杀了他。}
### {546}{}{I appreciate people who do their job flawlessly. You deserve a reward... (takes the lid out of the safe) Here are 500 caps, as we agreed. Now leave me alone. I want to rest.}
{546}{}{我欣赏那些完美地完成工作的人。你应该得到奖励...（把保险箱的盖子拿出来）这是我们约定的500个瓶盖。现在别管我。我想休息。}
### {547}{}{Goodbye, Count.}
{547}{}{再见，伯爵。}
### {548}{}{Hey, where's my reward? I didn't just trudge along hot highways with rotting flesh in a bag.}
{548}{}{嘿，我的奖励在哪里？我不只是背着腐烂的肉在炎热的高速公路上跋涉。}
### {549}{}{Sure. This is your honestly earned right... (takes the caps out of the safe) There are 500 caps here, as we agreed. Now leave me alone.}
{549}{}{当然这是你应得的权利...（把瓶盖从保险箱里拿出来）按照我们的约定，这里有500个瓶盖。现在别管我。}

### {550}{}{I've destroyed the Blue Shield fuel depots. This will surely weaken the gang.}
{550}{}{我已经摧毁了蓝盾号的燃料库。这肯定会削弱这个团伙。}
### {1550}{}{I've destroyed the Blue Shield fuel depots. This will surely weaken the gang.}
{1550}{}{我已经摧毁了蓝盾号的燃料库。这肯定会削弱这个团伙。}
### {551}{}{So the rumors are true. The caravaneers saw smoke away from the trade route. If the fuel is destroyed, then a hard time will come for the raiders.}
{551}{}{所以传言是真的。商队队员看到贸易路线上浓烟滚滚。如果燃料被销毁，那么袭击者的日子就会很难过。}
### {552}{}{Ahem. The services are not free, wasn't that the deal?}
{552}{}{嗯。服务不是免费的，不是这样吗？}
### {553}{}{Of course, here's the reward - 500 caps. And thank you. Your service is invaluable for the city.}
{553}{}{当然，这是500个瓶盖的奖励。谢谢你。你的服务对这座城市来说是无价之宝。}
### {554}{}{You're welcome, Count. As long as the city brings caps, it has a future.}
{554}{}{不客气，伯爵。只要这座城市有上限，它就有未来。}
### {555}{}{I know well from my community how to tolerate violence against you. Therefore, I consider it my duty to stop the mainline workers.}
{555}{}{我在社区里很清楚如何容忍针对你的暴力行为。因此，我认为阻止主线工人是我的职责。}
### {556}{}{That's how? Now it's clear where you got so much strength to fight. I really hope you will save your people from captivity. Take the reward, there are 500 caps here. And thank you. Your service is invaluable for the city.}
{556}{}{就是这样？现在很清楚你在哪里有这么大的力量去战斗了。我真的希望你能把你的人民从囚禁中拯救出来。拿着奖励，这里有500个瓶盖。谢谢你。你的服务对这座城市来说是无价之宝。}
### {557}{}{Goodbye, Count Bustos.}
{557}{}{再见，巴斯托斯伯爵。}
### {558}{}{That was the calculation. For a while, the raiders will weaken and start fighting with each other.}
{558}{}{这就是计算。在一段时间内，袭击者将削弱并开始相互战斗。}
### {559}{}{Great job. It's not a pity to pay all 500 caps for this. And thank you. Your service is invaluable for the city.}
{559}{}{干得好。为此支付全部500个瓶盖并不可惜。谢谢你。你的服务对这座城市来说是无价之宝。}
### {560}{}{You're welcome, Count Bustos.}
{560}{}{不客气，巴斯托斯伯爵。}

### {569}{}{Your city is already suffering from robbers. So there will be fewer of them.}
{569}{}{你的城市已经遭受了抢劫。所以他们中的人会更少。}
### {570}{}{They say you caught one of the highway robbers?}
{570}{}{他们说你抓到了一个高速公路劫匪？}
### {571}{}{It's true. We keep him locked up. First we need to get all the information about the gang out of him, and then we will publicly execute him.}
{571}{}{这是真的。我们把他关起来。首先，我们需要从他那里获得有关该团伙的所有信息，然后我们将公开处决他。}
### {572}{}{Are you sure he's a criminal?}
{572}{}{你确定他是罪犯吗？}
### {573}{}{Some residents identified him as a highway worker. I believe them. In addition, he was wearing road shields, highway workers often use them as armor during attacks.}
{573}{}{一些居民认出他是一名高速公路工人。我相信他们。此外，他还戴着路盾，公路工人在袭击时经常将其用作盔甲。}
### {574}{}{Well, congratulations, Mayor. And I have to go.}
{574}{}{祝贺你，市长。我得走了。}
### {575}{}{I need to see him. Maybe I can find out something from him.}
{575}{}{我需要见他。也许我能从他身上找到一些东西。}
### {576}{}{He's locked up downstairs. Tell the guards to let you through.}
{576}{}{他被锁在楼下。告诉警卫让你通过。}
### {577}{}{You've got the wrong guy. He needs to be released.}
{577}{}{你找错人了。他需要被释放。}
### {578}{}{Am I supposed to let him go just by taking your word for it? Too naive a move. It's interesting to hear your arguments.}
{578}{}{我应该相信你的话就让他走吗？太天真了。听听你的论点很有趣。}
### {579}{}{My job is to inform, the rest is on your conscience.}
{579}{}{我的工作是通知，剩下的就凭你的良心了。}
### {580}{}{Isn't my testimony enough?}
{580}{}{我的证词还不够吗？}
### {581}{}{No. I trust my people, but not you.}
{581}{}{不，我信任我的人，但不信任你。}
### {582}{}{Then this decision will remain on your conscience. Goodbye.}
{582}{}{那么这个决定将取决于你的良心。再见}
### {583}{}{We, well, worked with him in the same caravan. I can guarantee that he does not pose a threat to you.}
{583}{}{我们在同一个大篷车里和他一起工作。我可以保证他不会对你构成威胁。}
### {584}{}{Hmm. To be honest, I myself do not know who he is or where he comes from, and residents always see an enemy in an outsider. Okay, I'll let this guy go for now, but on the condition that he has to get out of my city within an hour.}
{584}{}{嗯。老实说，我自己不知道他是谁，也不知道他来自哪里，居民们总是在局外人身上看到敌人。好吧，我暂时放了这家伙，但条件是他必须在一小时内离开我的城市。}
### {585}{}{Thank you, Mr. Mayor.}
{585}{}{谢谢你，市长先生。}
### {586}{}{How about a deposit? I'll pay 100 caps for his freedom.}
{586}{}{押金怎么样？我愿意为他的自由支付100个瓶盖。}
### {587}{}{Sounds acceptable. But tell him to get out of town within an hour.}
{587}{}{听起来可以接受。但告诉他一小时内离开小镇。}
### {588}{}{Thank you, Mr. Mayor.}
{588}{}{谢谢你，市长先生。}
### {589}{}{Sounds acceptable.}
{589}{}{听起来可以接受。}
### {590}{}{I'll bring the bottlecaps in soon.}
{590}{}{我很快就会把瓶子带来。}
### {591}{}{The Blue Shields offer an alliance. They have already agreed with the tinsmiths.}
{591}{}{蓝盾提供了一个联盟。他们已经同意了铁匠的意见。}
### {592}{}{What? Are these bandits protected by tinkerers? What an injustice!}
{592}{}{什么这些土匪有修匠保护吗？多么不公正！}
### {593}{}{The tinsmiths recognized them as a peaceful independent settlement.}
{593}{}{锡匠们承认他们是一个和平独立的定居点。}
### {594}{}{I should have acted faster. It's good that the gang will leave us and the caravans behind for a while. But bandits can't be trusted. In addition, many of them seek revenge on me personally or the entire Casa Grande.}
{594}{}{我本应该行动得更快。这帮人会把我们和大篷车留下一段时间，这很好。但是土匪是不能信任的。此外，他们中的许多人都在为我个人或整个格兰德之家复仇。}
### {595}{}{You don't have a choice. The tinkerers won't approve of resistance.}
{595}{}{你别无选择。修补匠们不会赞成抵抗。}
### {596}{}{Obviously, it is. I will sign the contract, considering your past achievements. But I will do everything to make the Shields pay dearly for it.}
{596}{}{很明显，是的。考虑到你过去的成就，我会签合同的。但我会尽一切努力让希尔兹一家为此付出高昂的代价。}
### {597}{}{I'll tell Ben what you said. Goodbye.}
{597}{}{我会把你说的告诉本。再见}
### {598}{}{I'll be damned if I sign this union. Get out and tell Ben that the tinkers won't protect him and his gang from a righteous judgment.}
{598}{}{如果我签了这个工会，我会被诅咒的。出去告诉本，修补匠们不会保护他和他的帮派免受正义的审判。}
### {599}{}{I'll tell Ben what you said. Goodbye.}
{599}{}{我会把你说的告诉本。再见}
