### {100}{}{Before you is a warrior of the road.}
{100}{}{在你成为道路上的战士之前。}
### {101}{}{This is one of the highway robbers.}
{101}{}{这是一个高速公路劫匪。}
### {102}{}{Good luck on the way.}
{102}{}{祝你好运。}

### {200}{}{Hey, thanks for the help, bro. These cops chased me for several days off-road. But why did you save me?}
{200}{}{嘿，谢谢你的帮助，兄弟。这些警察越野追了我好几天。但你为什么救我？}
### {1200}{}{Hey, thanks for the help, girlfriend. These cops chased me for several days off-road. But why did you save me?}
{1200}{}{嘿，谢谢你的帮助，女朋友。这些警察越野追了我好几天。但你为什么救我？}
### {201}{}{I always help people in need.}
{201}{}{我总是帮助需要帮助的人。}
### {202}{}{Nonsense! I don't believe in any nobility. Everyone cares only about their own skin. But if you don't mind putting yourself under attack for the sake of an outsider, it's only better for me. By the way, do you want to meet my gang? The boss will probably be interested in you.}
{202}{}{胡说我不相信任何贵族。每个人都只关心自己的皮肤。但如果你不介意为了一个局外人而攻击自己，那对我来说只会更好。顺便问一下，你想见见我的帮派吗？老板可能会对你感兴趣。}
### {203}{}{What kind of gang?}
{203}{}{什么帮派？}
### {204}{}{Blue Shields. We are so called because of these road signs. Don't you know? Then look at our base, it's over there. I'll tell them to let you through to Ben.}
{204}{}{蓝色盾牌。我们之所以如此出名，是因为这些路标。你不知道吗？然后看看我们的基地，它在那边。我会告诉他们让你接通本。}
### {205}{}{OK. Good luck on the road.}
{205}{}{好的。祝你在路上好运。}
### {206}{}{I want to join your gang.}
{206}{}{我想加入你们的帮派。}
### {207}{}{Ha! Not the best idea. Only those who really have nothing to lose in the "civilized world" take root here. In any case, this is handled personally by Ben, our leader. You need to talk to him.}
{207}{}{哈不是最好的主意。只有那些在“文明世界”中真正没有什么可失去的人才能在这里扎根。无论如何，这都是由我们的领导人本亲自处理的。你需要和他谈谈。}
### {208}{}{Okay. I will do so.}
{208}{}{可以我会这么做的。}
### {209}{}{The base is over there. I'll tell them to let you through to Ben. Have a good trip.}
{209}{}{基地在那边。我会告诉他们让你接通本。祝你旅途愉快。}
### {210}{}{Good. Good luck on the road.}
{210}{}{好的祝你在路上好运。}
### {211}{}{Hey, thanks for the help, bro. These cops chased me for several days off-road.}
{211}{}{嘿，谢谢你的帮助，兄弟。这些警察越野追了我好几天。}
### {1211}{}{Hey, thanks for the help, girlfriend. These cops chased me off-road for several days.}
{1211}{}{嘿，谢谢你的帮助，女朋友。这些警察越野追了我好几天。}
### {212}{}{What did they want from you?}
{212}{}{他们想从你那里得到什么？}
### {213}{}{They were bounty hunters. They are sometimes hired in Casa Grande or Phoenix to drive our gang off the tracks. But these are our tracks! They won't succeed.}
{213}{}{他们是赏金猎人。他们有时被雇在格兰德之家或凤凰城，把我们的帮派赶走。但这些是我们的足迹！他们不会成功。}
### {214}{}{Clear.}
{214}{}{清楚的}
### {215}{}{I'll tell Ben and the others this story. See you at the base.}
{215}{}{我会把这个故事告诉本和其他人。基地见。}
### {216}{}{Have a good trip.}
{216}{}{祝你旅途愉快。}
