### {100}{}{Here is a bar visitor.}
{100}{}{这是一位酒吧客人。}
### {101}{}{You see a strung-out colonist. He's a little drunk.}
{101}{}{你看到一个精神错乱的殖民者。他有点醉了。}
### {102}{}{Don't come near me.}
{102}{}{不要靠近我。}
### {103}{}{Stop, that's enough! I'm guilty, I admit!}
{103}{}{住手，够了！我承认我有罪！}
### {104}{}{Ah, now I see potential in you.}
{104}{}{啊，现在我看到了你的潜力。}
### {105}{}{Okay, let's assume we're reconciled.}
{105}{}{好吧，假设我们和解了。}
### {106}{}{Okay, you've had enough. Now go get me a drink.}
{106}{}{好吧，你受够了。现在去给我拿杯饮料。}
### {107}{}{Ah, someone's showing off with their shining armor.}
{107}{}{啊，有人在炫耀他们闪亮的盔甲。}

### {200}{}{Hey, you! I don't know you. For the first time in the city? Then get me a drink. Right now.}
{200}{}{嘿，你！我不认识你。第一次在这个城市？那给我拿杯饮料。马上}
### {201}{}{Why should I buy you a drink?}
{201}{}{我为什么要请你喝一杯？}
### {1201}{}{Why should I buy you a drink?}
{1201}{}{我为什么要请你喝一杯？}
### {202}{}{Look, I don't want any trouble, just don't bother me, okay?}
{202}{}{听着，我不想惹任何麻烦，只是不要打扰我，好吗？}
### {1202}{}{Look, I don't want any trouble, just don't touch me, okay?}
{1202}{}{听着，我不想惹任何麻烦，只是不要碰我，好吗？}
### {203}{}{The hell with it.}
{203}{}{见鬼去吧。}

### {204}{}{Because in front of you is the living embodiment of power and law in this city! I work for Roy Faber himself. Got it? Then bring a drink, otherwise you'll run into a fight.}
{204}{}{因为在你面前是这个城市权力和法律的活生生的化身！我为罗伊·法伯工作。明白了吗？然后带一杯饮料，否则你会打架的。}
### {205}{}{I don't want any trouble, don't touch me.}
{205}{}{我不想惹麻烦，别碰我。}
### {206}{}{You can only scream. Haven't you been hit in the ribs for a long time?}
{206}{}{你只能尖叫。你的肋骨被打了很久了吗？}

### {207}{}{Ha! Pathetic village pussy. Get out of the bar if you don't have the guts. There's no place for weaklings like you in this town.}
{207}{}{哈可怜的村姑。如果你没有勇气就滚出酒吧。这个镇上没有你这样的弱者的容身之地。}
### {1207}{}{For me to touch a village brat like you? Better go outside, that's where you belong.}
{1207}{}{让我去碰你这样的乡巴佬？最好到外面去，那是你的归属。}
### {208}{}{Okay, okay, whatever you say. You're the boss here.}
{208}{}{好吧，好吧，不管你说什么。你是这里的老板。}
### {209}{}{And that was unpleasant. Did you want a fight? So get it!}
{209}{}{这很不愉快。你想打架吗？所以，抓住它！}

### {210}{}{What about? The way you talk to me, you empty shit! Now you will beg for mercy from me...}
{210}{}{那么...怎么样你跟我说话的方式，你这个废物！现在你要向我求饶...}
### {211}{}{Just don't hit me in the face...}
{211}{}{只是不要打我的脸...}
### {212}{}{Great, show me what you're capable of.}
{212}{}{太好了，让我看看你的能力。}

### {213}{}{I work for him too. So shut up.}
{213}{}{我也为他工作。所以闭嘴。}
### {214}{}{ (through his teeth) W-damn... (returns to his bottle and looks dejectedly at the table)}
{214}{}{（透过他的牙齿）该死的...（回到瓶子旁，沮丧地看着桌子）}
### {215}{}{That's it.}
{215}{}{就是这样。}

### {216}{}{Faber is dead! Do you hear? He's dead!}
{216}{}{费伯死了！你听到了吗？他死了！}
### {217}{}{Yes, yes, uh, I hear, calm down...}
{217}{}{是的，是的，嗯，我听说了，冷静点...}
### {218}{}{I found something to be proud of. You get off on drunks in a bar just because you're a six, right?}
{218}{}{我找到了值得骄傲的东西。你在酒吧里因为你是六岁的孩子就对醉汉大发雷霆，对吧？}
### {219}{}{Well, no. I'm just... me... Go to hell!}
{219}{}{不，我只是...我…去死吧！}

### {220}{}{What do I need?}
{220}{}{我需要什么？}
### {221}{}{Nothing anymore.}
{221}{}{什么都没有了。}
### {222}{}{Which is to be expected.}
{222}{}{这是意料之中的事。}
### {223}{}{Fuck off.}
{223}{}{滚蛋。}
### {224}{}{With pleasure.}
{224}{}{很高兴。}
### {225}{}{Don't come near me!}
{225}{}{不要靠近我！}
### {226}{}{And I'm not going to.}
{226}{}{我不会的。}
### {227}{}{The peasants from the Villa are kept in prison. They need to be released.}
{227}{}{别墅里的农民被关在监狱里。他们需要被释放。}
### {228}{}{What?! It's the craziest idea I've ever heard. Faber will not part with the prisoners just like that. And you shouldn't even think about escaping - you'll just sign a death sentence for yourself.}
{228}{}{什么这是我听过的最疯狂的想法。费伯不会就这样和犯人分手的。你甚至不应该考虑逃跑——你只会为自己签署死刑判决。}
### {229}{}{Then you tell me.}
{229}{}{然后你告诉我。}
### {230}{}{Well, if the prisoners break free, they will be killed by collars. Just a few miles of freedom, and then boom! - and there is no head.}
{230}{}{好吧，如果囚犯越狱，他们会被项圈杀死的。只有几英里的自由，然后轰隆隆！-而且没有头。}
### {231}{}{How cruel.}
{231}{}{真残忍。}
### {232}{}{Collars can be turned off at the radio station. But only two people know how to do it: Faber and Smart Guy. So you have almost no chance.}
{232}{}{项圈可以在电台关掉。但只有两个人知道怎么做：费伯和聪明人。所以你几乎没有机会。}
### {233}{}{We'll see about that.}
{233}{}{我们拭目以待。}
