### {100}{}{Ugo is in front of you.}
{100}{}{乌戈就在你面前。}
### {101}{}{You see a slave. If you look closely, you will recognize in his dirty, emaciated face your fellow tribesman.}
{101}{}{你看到一个奴隶。如果你仔细看，你会从他那张又脏又瘦的脸上认出你的部落同胞。}
### {102}{}{Oops, I hope no one at the Villa finds out about this...}
{102}{}{哎呀，我希望别墅里没有人知道这件事。。。}
### {103}{}{The traitor! You're possessed by Diablo!}
{103}{}{叛徒！你被暗黑破坏神附身了！}
### {104}{}{Now Hugo will not be able to return to the Villa.}
{104}{}{现在雨果将无法回到别墅。}
### {105}{}{Hugo returns to the Villa.}
{105}{}{雨果回到别墅。}
### {106}{}{Of course, friend, as you wish.}
{106}{}{当然，朋友，随你所愿。}
### {107}{}{See you at the Villa, amigo.}
{107}{}{别墅见，朋友。}

#The first dialog
### {200}{}{? Good heavens, it's you! And we are already completely desperate.}
{200}{}{？天哪，是你！我们已经完全绝望了。}
### {201}{}{I'm here to set you free.}
{201}{}{我是来放你自由的。}
### {202}{}{You're just in time! We would only get to the exit, and then somehow ourselves.}
{202}{}{你来得正是时候！我们只会走到出口，然后不知怎么地走到我们自己。}
### {203}{}{Tell me what happened first.}
{203}{}{告诉我先发生了什么。}
### {204}{}{It's all Sancho! He came up with this stupid idea with explosives. None of us knew how to handle it, but he decided to try anyway. You ask him! Sancho has become the main one here.}
{204}{}{都是桑乔！他用炸药想出了这个愚蠢的主意。我们谁也不知道该怎么处理，但他还是决定试一试。你问他！桑乔已经成为这里的主力。}
### {205}{}{Stay here. I'll talk to him first.}
{205}{}{待在这儿我先和他谈谈。}
### {206}{}{We're at the entrance. Freedom is very close.}
{206}{}{我们在入口处。自由是非常接近的。}

### {207}{}{Si?}
{207}{}{Si？}
### {208}{}{That was a rat! I've never seen such a huge and vicious one! Eh, I would like to roast her now...}
{208}{}{那是只老鼠！我从来没有见过这么大又恶毒的家伙！呃，我现在想烤她。。。}
### {209}{}{Okay, let's go.}
{209}{}{好吧，我们走吧。}

### {210}{}{Hey, Hugo, do you remember when you turned me in once?}
{210}{}{嘿，雨果，你还记得你把我交给我的时候吗？}
### {211}{}{What... wait...}
{211}{}{什么等待}
### {212}{}{I took the padre's things without asking, and then you told him. And I was punished. Remember?}
{212}{}{我没问就拿走了牧师的东西，然后你告诉了他。我受到了惩罚。回想起}
### {1212}{}{I took the padre's things without asking, and then you told him. And I was punished. Remember?}
{1212}{}{我没问就拿走了牧师的东西，然后你告诉了他。我受到了惩罚。回想起}
### {213}{}{(smiling) Yeah, hehe, it was... (confused) like this...}
{213}{}{（微笑）是啊，呵呵，是。。。（困惑）像这样。。。}
### {214}{}{I'm here now. Saving your skin. How do you feel, Hugo?}
{214}{}{我现在在这里。拯救你的皮肤。你感觉怎么样，雨果？}
### {215}{}{(mutters under his breath) P-sorry... I'm sorry for everything! (wipes away tears)}
{215}{}{（低声喃喃自语）对不起。。。我为一切感到抱歉！（擦去眼泪）}
### {216}{}{That's the same thing. Remember this day... "friend".}
{216}{}{这是一样的。记住这一天。。。“朋友”。}
### {217}{}{Come on, I'm not angry, calm down. Let's get out of here.}
{217}{}{拜托，我不生气，冷静点。让我们离开这里。}
### {218}{}{Come on, forget it.}
{218}{}{来吧，忘了它。}
### {219}{}{It's all right, Hugo, don't worry.}
{219}{}{没事的，雨果，别担心。}

### {222}{}{Ugh, thanks for the help! Then we'll find our own way. But you will have to save the rest of the residents of the Villa. We're of little use now after what we've been through. Good luck.}
{222}{}{啊，谢谢你的帮助！然后我们会找到自己的路。但你必须拯救别墅的其他居民。在经历了这些之后，我们现在没什么用了。祝你好运}
### {223}{}{Okay. I'll meet you at the Villa.}
{223}{}{可以我会在别墅见你。}
### {224}{}{Yes, listen, Sancho says we should blow up the mines. Otherwise, the tragedy will repeat itself. If blown up, the company will go bankrupt and stop looking for new slaves.}
{224}{}{是的，听着，桑乔说我们应该炸掉地雷。否则，悲剧将重演。如果被炸毁，公司将破产，并停止寻找新的奴隶。}
### {225}{}{Blow up the mines? The idea is for me.}
{225}{}{炸掉地雷？这个主意是给我的。}
### {226}{}{Sancho is talking nonsense. The explosion will only add work to the slaves.}
{226}{}{桑乔在胡说八道。爆炸只会增加奴隶的工作量。}
### {227}{}{Really, will you do it? Then find the explosives in the warehouse inside the mine, the administrator keeps the key to the warehouse with him. Good luck.}
{227}{}{真的，你会这么做吗？然后在矿井内的仓库里发现了爆炸物，管理员随身携带了仓库的钥匙。祝你好运}
### {228}{}{But the company will continue to search for and use slaves. Our escape won't change anything, don't you understand? Okay, you think about it, and it's time for us to hit the road. Good luck.}
{228}{}{但该公司将继续搜寻和使用奴隶。我们的逃亡不会改变任何事情，你不明白吗？好吧，你想一想，现在是我们上路的时候了。祝你好运}
### {229}{}{I'll think. Now get out of here.}
{229}{}{我会考虑的。现在离开这里。}
