### {110}{}{The inscription on the glass reads: "The slot machine temporarily does not work."}
{110}{}{玻璃上的铭文写道：“老虎机暂时无法工作。”}
### {111}{}{" Hey, starfighter! Throw a coin into that slot and find yourself in the incredible world of Space!"}
{111}{}{“嘿，星际战斗机！往那个插槽里扔一枚硬币，你就会发现自己置身于不可思议的太空世界！”}
### {112}{}{You managed to repair the burnt-out parts of the slot machine. We need to tell the bartender about this.}
{112}{}{你设法修理了老虎机烧坏的零件。我们需要把这件事告诉酒保。}

### {120}{}{For some reason, you no longer enjoy this game.}
{120}{}{出于某种原因，你不再喜欢这个游戏了。}
### {121}{}{I'm sick of just the sight of this machine.}
{121}{}{我看厌了这台机器。}
### {122}{}{To play, use special tokens on this slot machine.}
{122}{}{要玩，请在此老虎机上使用特殊代币。}
### {123}{}{M-m-m! It looks fantastic.}
{123}{}{M-M-M！它看起来棒极了。}
### {124}{}{"Hey, starship! Give up the helm to a more experienced pilot."}
{124}{}{“嘿，星际飞船！把舵交给更有经验的飞行员。”}
### {125}{}{I have *no* chance against this machine.}
{125}{}{我没有机会对付这台机器。}
### {126}{}{"Hey, starship! The onboard medic cannot allow you to take the helm in this condition!"}
{126}{}{“嘿，星舰！船上的医生不能允许你在这种情况下掌舵！”}
### {127}{}{I'm not able to play right now.}
{127}{}{我现在不能打球。}

#Phrases when playing
### {130}{}{Well done, pilot! You earned it }
{130}{}{干得好，飞行员！这是你应得的}
### {131}{}{ points!}
{131}{}{积分！}
### {132}{}{Total account: }
{132}{}{账户总额：}
### {133}{}{.}
{133}{}{。}
### {134}{}{}
{134}{}{error : string is empty}
### {135}{}{From the screw!}
{135}{}{从螺丝钉！}
### {136}{}{Show aerobatics!}
{136}{}{表演特技飞行！}
### {137}{}{Fly, ball!}
{137}{}{飞，球！}
### {138}{}{I want to win!}
{138}{}{我想赢！}
### {139}{}{Come on! Come on!}
{139}{}{来吧来吧}
### {140}{}{It was a bad flight! Lost }
{140}{}{那是一次糟糕的飞行！迷路的}
### {141}{}{ points!}
{141}{}{积分！}
### {142}{}{.}
{142}{}{。}
### {145}{}{Yes, not there!}
{145}{}{是的，不在那儿！}
### {146}{}{Damn the gamer!}
{146}{}{该死的玩家！}
### {147}{}{You disappoint me, piece of iron!}
{147}{}{你让我失望了，铁块！}
### {148}{}{I'll conquer you anyway!}
{148}{}{无论如何我都会征服你的！}
### {149}{}{No!}
{149}{}{不}
### {150}{}{"It was aerobatics, Captain! You've conquered Space and you can be proud of yourself!"}
{150}{}{“这是特技飞行，上尉！你征服了太空，你可以为自己感到骄傲！”}
### {151}{}{Phew, it's finally over... It's strange, I feel something... emptiness after victory.}
{151}{}{哇，终于结束了。。。这很奇怪，我感觉到了。。。胜利后的空虚。}
### {152}{}{During the game you had a seizure!}
{152}{}{在比赛中你癫痫发作了！}
