### {100}{}{This is Mr. Kogan.}
{100}{}{这是Kogan先生。}
### {101}{}{You see a sloppy fat man in a dirty business suit. Looks like he's in charge here.}
{101}{}{你看到一个穿着脏西装的邋遢胖子。看起来他是这里的负责人。}
### {102}{}{Choke on lead, you fat pig-rat!}
{102}{}{被铅噎住，你这肥猪老鼠！}
### {103}{}{What does a scavenger feel when his fate depends on garbage?}
{103}{}{当一个拾荒者的命运取决于垃圾时，他会有什么感受？}
### {104}{}{Hey! I had nothing to do with it. He's having a heart attack!}
{104}{}{嘿我与此事无关。他心脏病发作了！}
### {105}{}{I'm not against peace talks, but first get out of this tin can.}
{105}{}{我并不反对和平谈判，但首先要离开这个铁罐。}
### {106}{}{Get out of my city.}
{106}{}{滚出我的城市。}
### {107}{}{Get out of my garage.}
{107}{}{滚出我的车库。}

#Floating replicas (do not delete empty lines!)
### {110}{}{*Cough-cough*}
{110}{}{*咳嗽*}
### {111}{}{*Uv-f*}
{111}{}{*Uv-f*}
### {112}{}{*Urp*}
{112}{}{*Urp*}
### {113}{}{*Burp*}
{113}{}{*打嗝*}
### {114}{}{Damn heartburn...}
{114}{}{该死的烧心...}
### {115}{}{ }
{115}{}{error : string is empty}
### {116}{}{ }
{116}{}{error : string is empty}
### {117}{}{ }
{117}{}{error : string is empty}
### {118}{}{ }
{118}{}{error : string is empty}
### {119}{}{ }
{119}{}{error : string is empty}

#Cut scene
### {120}{}{   }
{120}{}{error : string is empty}
### {121}{}{Mr. Kogan! Mr. Kogan!}
{121}{}{Kogan先生！Kogan先生！}
### {122}{}{Larry, for fuck's sake! Why the hell are you breaking into my office?}
{122}{}{拉里，看在他妈的份上！你为什么闯进我的办公室？}
### {123}{}{What's the matter? No one dares to break into my office...}
{123}{}{怎么了？没有人敢闯入我的办公室...}
### {124}{}{Mr. Kogan! There, in the dormitory, a serious mess began!}
{124}{}{Kogan先生！在宿舍里，一片狼藉开始了！}
### {125}{}{Well, what else can happen in this hole? Probably another drunken brawl.}
{125}{}{这个洞里还能发生什么？可能又是一场酒后斗殴。}
### {126}{}{No, it doesn't look like it. I didn't understand the reason for the fight, I immediately ran here...}
{126}{}{不，看起来不像。我不明白打架的原因，我马上跑过来...}
### {127}{}{So go figure it out, idiot!}
{127}{}{去想办法吧，白痴！}

#Dialog
### {170}{}{I've seen such a garment before. What do you have to do with the Followers of Fire?}
{170}{}{我以前见过这样的衣服。你和火的追随者有什么关系？}
### {171}{}{The most direct. I'm part of this church.}
{171}{}{最直接的。我是这个教堂的一部分。}
### {172}{}{Hmm... What a curious coincidence. I usually try to bypass any religion. But Followers contribute to progress in Arizona and, as a result, the development of my cartel. You can feel protected here.}
{172}{}{嗯…真是个奇怪的巧合。我通常试图绕过任何宗教。但追随者们为亚利桑那州的进步做出了贡献，因此也为我的卡特尔的发展做出了贡献。在这里你会感到受到保护。}
### {173}{}{Well, that's great news.}
{173}{}{好吧，这是个好消息。}
### {174}{}{Can I expect full service in the garage?}
{174}{}{我可以期待车库的全面服务吗？}
### {175}{}{Sure. I'll give instructions to Pete.}
{175}{}{当然我会给皮特指示的。}
### {176}{}{Thank you.}
{176}{}{非常感谢。}
### {177}{}{This is the first time I hear about these "pursuers". And he took off his mantle from a corpse in the desert.}
{177}{}{这是我第一次听说这些“追求者”。他从沙漠中的一具尸体上脱下了斗篷。}
### {1177}{}{This is the first time I hear about these "pursuers". And she took the mantle off a corpse in the desert.}
{1177}{}{这是我第一次听说这些“追求者”。她把沙漠里一具尸体的披风摘了下来。}
### {178}{}{It's true? Then forget about our conversation.}
{178}{}{这是真的吗？那就忘掉我们的谈话吧。}
### {179}{}{I'll do that.}
{179}{}{我会那样做的。}

### {180}{}{They say you had some kind of grater with Larry?}
{180}{}{他们说你和拉里有过节？}
### {181}{}{Nothing special. He was just looking for trouble at the bar.}
{181}{}{没什么特别的。他只是在酒吧找麻烦。}
### {182}{}{You must have nerves of steel if you think you can kill my people. But on the other hand, I've been wanting to get rid of this devil for a long time. He makes too much noise.}
{182}{}{如果你认为你能杀死我的人民，你一定有钢铁般的勇气。但另一方面，我想摆脱这个魔鬼已经很久了。他太吵了。}
### {183}{}{So you're not going to chase me?}
{183}{}{所以你不打算追我？}
### {184}{}{You'll have to work hard to earn my respect. It all depends on you.}
{184}{}{你必须努力工作才能赢得我的尊重。这一切都取决于你。}
### {185}{}{That's how...}
{185}{}{这就是为什么...}
### {186}{}{He started it first! I was just defending myself.}
{186}{}{他先开始的！我只是在为自己辩护。}
### {1186}{}{He started it first! I was just defending myself.}
{1186}{}{他先开始的！我只是在为自己辩护。}
### {187}{}{This is our grater with him. They don't concern you.}
{187}{}{这是我们对他的不满。它们与你无关。}

### {190}{}{You again... (sigh) Do you know about the Rangers? I hate these guys. They're always poking their noses into other people's business, as if the whole wasteland belongs to them. You're not going to do the same in *my* city, are you?}
{190}{}{你又...（叹气）你知道游骑兵队吗？我讨厌这些家伙。他们总是对别人的事情嗤之以鼻，好像整个荒地都属于他们。你不会在我的城市做同样的事，是吗？}
### {191}{}{No, Mr. Kogan. I'm here solely on business.}
{191}{}{不，Kogan先生。我来这里只是出差。}
### {192}{}{OK. I think we understand each other. Don't forget who this place belongs to.}
{192}{}{好吧。我想我们互相理解。别忘了这个地方是谁的。}
### {193}{}{No problems.}
{193}{}{没有问题。}
### {194}{}{You'd better talk about the Rangers in a respectful tone. Someday we will control the whole of Arizona.}
{194}{}{你最好用尊重的语气谈论流浪者队。总有一天我们会控制整个亚利桑那州。}
### {195}{}{I doubt it very much. The rangers have a lot of enemies, and their numbers are too small to independently manage the population. And they'll certainly never get control of this city while I'm alive.}
{195}{}{我非常怀疑。护林员有很多敌人，他们的数量太少，无法独立管理人口。在我活着的时候，他们肯定永远无法控制这座城市。}
### {196}{}{What's your problem with the Rangers?}
{196}{}{你对流浪者队有什么问题？}
### {197}{}{I have *no* problems with them. But I'm not going to share power with anyone. I put too much work into this mine and created this whole city practically from scratch.}
{197}{}{我对他们没有意见。但我不会和任何人分享权力。我在这个矿上投入了太多的工作，几乎从零开始创建了整个城市。}
### {198}{}{Yes, you can think about it.}
{198}{}{是的，你可以考虑一下。}
### {199}{}{Rangers are busy with narrow interests. They are not able to create a new production. And this is exactly what people need right now.}
{199}{}{游骑兵忙于狭隘的利益。他们无法创造新的产品。这正是人们现在所需要的。}

### {200}{}{(In front of you is a very well-fed man in a worn business suit, looking out of place against the background of the surrounding landfill. When he sees you, he gets distracted from some device and removes the headphones connected to it.)}
{200}{}{（你面前是一个穿着破旧西装、吃得很饱的男人，他在周围垃圾填埋场的背景下显得格格不入。当他看到你时，他会被一些设备分散注意力，并摘下连接的耳机。）}
### {201}{}{Ahem. Are you in charge here?}
{201}{}{嗯。你是这里的负责人吗？}
### {202}{}{(puts down the headphones and presses some buttons on the device, then points to the device) It's an old record player. These were produced by the famous Watts Electronics company before the Great War. The model is not the most expensive, but very reliable, since it has survived to this day.}
{202}{}{（放下耳机，按下设备上的一些按钮，然后指着设备）这是一台旧的录音机。这些是由著名的瓦茨电子公司在大战前生产的。这个模型不是最贵的，但非常可靠，因为它一直存活到今天。}
### {203}{}{[Listen]}
{203}{}{[听]}
### {204}{}{That's why I love old things. Our ancestors made a lot of mistakes, but they knew how to make players. At that time, many factories of various specializations were operating throughout Arizona. Now none of them work.}
{204}{}{这就是为什么我喜欢旧东西。我们的祖先犯了很多错误，但他们知道如何培养球员。当时，许多不同专业的工厂在亚利桑那州各地运营。现在它们都不起作用了。}
### {205}{}{Who needs all this junk?}
{205}{}{谁需要这些垃圾？}
### {206}{}{I knew you wouldn't appreciate it. So what's on your mind, man?}
{206}{}{我知道你不会感激的。那么你在想什么，伙计？}
### {1206}{}{I knew you wouldn't appreciate it. So what's on your mind, lady?}
{1206}{}{我知道你不会感激的。那么你在想什么，女士？}
### {207}{}{Yeah... The world has definitely lost a lot.}
{207}{}{是 啊世界肯定损失惨重。}
### {208}{}{M? I thought you'd have a different opinion. In any case, we have very few opportunities to fix it. So what's on your mind, man?}
{208}{}{M我以为你会有不同的看法。无论如何，我们几乎没有机会解决这个问题。那么你在想什么呢，伙计？}
### {1208}{}{M? I thought you'd have a different opinion. In any case, we have very few opportunities to fix it. So what's on your mind, lady?}
{1208}{}{M我以为你会有不同的看法。无论如何，我们几乎没有机会修复它。那么，女士，你在想什么呢？}
### {209}{}{End this nonsense. I didn't come here to cross the desert.}
{209}{}{别再胡说八道了。我来这里不是为了穿越沙漠。}
### {1209}{}{Finish this nonsense. I didn't come here to cross the desert.}
{1209}{}{别再胡说八道了。我来这里不是为了穿越沙漠。}
### {210}{}{You're not the talkative type, are you? So what's on your mind, man?}
{210}{}{你不是那种爱说话的人，是吗？你在想什么，伙计？}
### {1210}{}{You're not the talkative type, are you? So what's on your mind, lady?}
{1210}{}{你不是那种爱说话的人，是吗？女士，你在想什么？}

### {211}{}{I am here because someone enslaved the peasants of the Villa and took them in this direction.}
{211}{}{我来这里是因为有人奴役了别墅的农民，把他们带向这个方向。}
### {212}{}{No one likes it when their usual way of life is violated. I don't like it when the ruins run out of minerals, as a result of which you need to look for new places to mine. But I have dozens of scavengers and several contracts under my command.}
{212}{}{没有人喜欢他们通常的生活方式受到侵犯。我不喜欢废墟中的矿物耗尽，因此你需要寻找新的开采地点。但我手下有几十个拾荒者和几份合同。}
### {213}{}{[Next]}
{213}{}{[下一个]}
### {214}{}{Villa was lucky. But it's hard for people of your type to understand. While you are busy with your internal worries, we, the scavengers, provide equipment for the whole of Southern Arizona. I don't think anyone else cares about the fate of the Villa, except the local peasants.}
{214}{}{维拉很幸运。但你这种类型的人很难理解。当你忙于内心的担忧时，我们拾荒者为整个亚利桑那州南部提供设备。我想除了当地的农民，其他人都不关心别墅的命运。}
### {215}{}{Bastard, so it was you who ordered the peasants to be captured?}
{215}{}{混蛋，是你下令抓农民的？}
### {216}{}{So you don't deny your involvement?}
{216}{}{所以你不否认你的参与？}
### {217}{}{Me? Of course not. It was a project of another, more influential organization. We just happened to be on the way. And if I were you, I would forget this story and go back to my empty house to start all over again.}
{217}{}{我当然不是。这是另一个更有影响力的组织的项目。我们刚好在路上。如果我是你，我会忘记这个故事，回到我空荡荡的房子里重新开始。}
### {218}{}{Do you think it's that simple?}
{218}{}{你觉得就这么简单吗？}
### {219}{}{There are no other ways for you. However, you can stay here and work as a garbage collector if you like it. What do you say?}
{219}{}{你别无选择。但是，如果你喜欢的话，你可以留在这里做垃圾收集工。你觉得怎么样？}
### {220}{}{I...}
{220}{}{我}
### {221}{}{It's like you're rejoicing at our tragedy.}
{221}{}{你好像在为我们的悲剧而高兴。}
### {222}{}{Am I happy? No. But when WE needed help in times of famine, YOU meanwhile profited from it and demanded double rates from us. Well, is it nice to feel like a litter this time?}
{222}{}{我快乐吗？没有。但当我们在饥荒时期需要帮助时，你却从中获利，并要求我们加倍收费。好吧，这次感觉像垃圾一样好吗？}
### {223}{}{That's not what I'm asking.}
{223}{}{这不是我要问的。}

### {230}{}{These scavengers can be unbearable when they get drunk... Listen, if you're going to stay in town, you're going to need my protection. And now a great opportunity has turned up to show itself.}
{230}{}{这些拾荒者喝醉了会让人难以忍受...听着，如果你要留在城里，你需要我的保护。现在出现了一个展示自己的大好机会。}
### {231}{}{Are you suggesting I calm down the workers?}
{231}{}{你是在建议我让工人们冷静下来吗？}
### {232}{}{Go to the dorm and find out what happened there. I don't need any extra problems in the city.}
{232}{}{去宿舍看看那里发生了什么。我在城里不需要任何额外的麻烦。}
### {233}{}{I'll see what I can do.}
{233}{}{我看看我能做些什么。}
### {234}{}{I don't think I want to work for you.}
{234}{}{我想我不想为你工作。}
### {235}{}{Great. Oh, yes, I didn't introduce myself. Karl Kogan. Now get busy.}
{235}{}{太棒了哦，是的，我没有自我介绍。卡尔·科根。现在开始忙碌吧。}
### {236}{}{. . .}
{236}{}{。}
### {237}{}{Then you don't belong in Garage City. Get out of my garage.}
{237}{}{那你就不属于车库城了。滚出我的车库。}
### {238}{}{. . .}
{238}{}{。}
### {239}{}{Why would I get involved in a local showdown?}
{239}{}{我为什么要参与当地的决战？}
### {240}{}{Is my loyalty not enough? Don't forget that I know everything about your enemies - more than anyone in Garage City.}
{240}{}{我的忠诚还不够吗？别忘了，我知道你敌人的一切——比车库城的任何人都了解。}
### {241}{}{What did you find out about the fight in the dorm?}
{241}{}{你发现宿舍打架的事了吗？}
### {1241}{}{What did you find out about the fight in the dorm?}
{1241}{}{你发现宿舍打架的事了吗？}
### {242}{}{Nothing. I'll do it right now.}
{242}{}{没有什么我现在就做。}
### {243}{}{Can I ask a couple of questions?}
{243}{}{我能问几个问题吗？}
### {244}{}{First prove that you are worthy of my attention. Or do you already want to get out of town?}
{244}{}{首先证明你值得我关注。还是你已经想出城了？}
### {1244}{}{First prove that you are worthy of my attention. Or do you already want to get out of town?}
{1244}{}{首先证明你值得我关注。还是你已经想出城了？}
### {245}{}{Okay, I'll do your errand.}
{245}{}{好的，我来帮你跑腿。}
### {246}{}{That's exactly what I'm going to do.}
{246}{}{这正是我要做的。}
### {247}{}{Lucas's men robbed Trayvon's men and left town. They were talking about some kind of decoder.}
{247}{}{卢卡斯的人抢劫了特雷文的人并离开了小镇。他们在谈论某种解码器。}
### {248}{}{I know, you idiot! How long has it been since I gave you this assignment? Your chances of proving your usefulness are rapidly disappearing.}
{248}{}{我知道，你这个白痴！我给你这个任务已经有多久了？你证明自己有用的机会正在迅速消失。}
### {1248}{}{I know, damn it! How long has it been since I gave you the assignment? Your chances of proving your usefulness are rapidly disappearing.}
{1248}{}{我知道，该死！我给你分配任务有多久了？你证明自己有用的机会正在迅速消失。}
### {249}{}{What's going on anyway?}
{249}{}{怎么回事？}
### {250}{}{I didn't expect this from Lucas. His clan had a reputation for being a small but punchy team. If he decides to go against me, he will have to pay dearly for it.}
{250}{}{我没想到卢卡斯会这么说。他的家族以小而有力著称。如果他决定与我作对，他将为此付出高昂的代价。}
### {251}{}{I have questions about this story with Lucas.}
{251}{}{我对卢卡斯的故事有疑问。}
### {252}{}{Is there anything else I can do for you, Mr. Kogan?}
{252}{}{Kogan先生，我还能为你做什么吗？}
### {1252}{}{Is there anything else I can do for you, Mr. Kogan?}
{1252}{}{Kogan先生，我还能为你做什么吗？}

### {253}{}{I have the answers.}
{253}{}{我有答案。}
### {254}{}{Why are the clans so bitter against each other?}
{254}{}{为什么部族之间如此仇恨？}
### {255}{}{Recently, mine revenues have been falling, so it has become difficult for scavengers to survive. Previously, the clans got along well - there was enough work for everyone. Now they have become fierce competitors.}
{255}{}{最近，矿山收入一直在下降，因此拾荒者很难生存。以前，部落相处得很好——每个人都有足够的工作。现在他们已经成为了激烈的竞争对手。}
### {256}{}{What's the story with the decoder?}
{256}{}{解码器是怎么回事？}
### {257}{}{A rare device for hacking electronic systems. I ordered a decoder for a large amount of caps through the southern caravans and gave it to the Trayvon clan to open the old factory. It's the only place we couldn't get to because of the damn security system. It looks like Lucas decided to bypass all of us in this operation.}
{257}{}{一种罕见的用于入侵电子系统的设备。我通过南部大篷车订购了大量瓶盖的解码器，并将其交给特雷冯家族，让他们打开旧工厂。这是我们唯一不能去的地方，因为该死的安全系统。看起来卢卡斯决定在这次行动中绕过我们所有人。}
### {258}{}{Why was it necessary to divide the scavengers into clans?}
{258}{}{为什么有必要把拾荒者分成部落？}
### {259}{}{They wanted it themselves. People need authorities, that's how their thinking works. I don't care who I give instructions to. The main thing is that they obey and do not create problems.}
{259}{}{他们自己想要。人们需要权威，这就是他们的思维方式。我不在乎我给谁下达指令。最重要的是他们服从，不会制造问题。}
### {260}{}{Enough about the scavengers.}
{260}{}{关于拾荒者已经够多了。}
### {261}{}{Enough talk about the cartel.}
{261}{}{关于卡特尔的讨论已经够多了。}
### {262}{}{I've had enough of these muddy stories. Goodbye.}
{262}{}{我受够了这些乱七八糟的故事。再见}

### {270}{}{Are you the local headman?}
{270}{}{你是当地的校长吗？}
### {271}{}{Elder... Is that what the peasants call the mayor? No, the city doesn't need a mayor. At least for now. I'm the head of a cartel of scavengers. But since the whole city is tied up in this business, no important decision can do without me. In this sense, you can consider me a "prefect".}
{271}{}{长者这就是农民们对市长的称呼吗？不，这个城市不需要市长。至少目前是这样。我是一个拾荒者卡特尔的头目。但既然整个城市都在做这件事，任何重要的决定都离不开我。从这个意义上说，你可以把我视为“州长”。}
### {272}{}{So you're the mayor of this town?}
{272}{}{你是这个镇的镇长吗？}
### {273}{}{I'm telling you, the city doesn't need a mayor. At least for now. I'm the head of a cartel of scavengers. But since the whole city is tied up in this business, no important decision can do without me. In this sense, you can consider me the mayor.}
{273}{}{我告诉你，这个城市不需要市长。至少目前是这样。我是一个拾荒者卡特尔的头目。但由于整个城市都在做这件事，任何重要的决定都离不开我。从这个意义上说，你可以把我视为市长。}
### {274}{}{How did you become the head of the company? Surely went over the heads of competitors?}
{274}{}{你是如何成为公司负责人的？肯定超过了竞争对手的头？}
### {275}{}{Stupid stereotypes. I started out as an ordinary garbage man in a Big City. The cartel already existed, I just took a vacant place in the administration. And then we opened a branch on these ruins, and I decided to move here to control the work.}
{275}{}{愚蠢的刻板印象。我一开始是一个大城市里的普通垃圾工。卡特尔已经存在了，我只是在政府中占据了一个空缺。然后我们在这些废墟上开了一家分店，我决定搬到这里来控制工作。}
### {276}{}{It's not like you want to come back.}
{276}{}{你好像不想回来。}
### {277}{}{I'm afraid we have some with the main office... disagreements.}
{277}{}{恐怕我们总公司有一些...分歧。}
### {278}{}{What is your cartel doing?}
{278}{}{你们的卡特尔在干什么？}
### {279}{}{Mainly extracts minerals from old ruins. For a hundred years after the Great War, many things have deteriorated, but some have survived and can be useful to society. We also try to fix some things, but things are much more complicated with this.}
{279}{}{主要从古老的废墟中提取矿物。在大战后的一百年里，许多事情都恶化了，但有些事情幸存下来，对社会有用。我们也试图解决一些问题，但事情要复杂得多。}

### {280}{}{My village does not like that you are restoring an old factory.}
{280}{}{我的村子不喜欢你在修复一个旧工厂。}
### {281}{}{Why is that? Oh, yes, I've heard a lot about your superstitions and fear of old technology. Well, you have no choice. Accept it.}
{281}{}{为什么？哦，是的，我听过很多关于你的迷信和对旧技术的恐惧。你别无选择。接受它。}
### {282}{}{Really?}
{282}{}{真正地}
### {283}{}{From now on, no one will let your peaceful village prosper by manual labor alone and live according to the laws of conscience. Cities are being reborn. If not now, then later someone will come here to restore production. It's inevitable.}
{283}{}{从现在起，没有人会让你平静的村庄仅靠体力劳动繁荣起来，并按照良心法则生活。城市正在重生。如果不是现在，那么以后会有人来这里恢复生产。这是不可避免的。}
### {284}{}{It seems impossible to fight this. Goodbye.}
{284}{}{这似乎是不可能对抗的。再见}
### {285}{}{The elders want isolation. They don't like that strangers will come to the valley again.}
{285}{}{长辈们希望与世隔绝。他们不喜欢陌生人再次来到山谷。}
### {286}{}{As I said, it's inevitable. All you can do is prepare. You could buy weapons, build fences, restore lost property, and even create a more efficient irrigation system. And for this, oddly enough, you just need the services of my company.}
{286}{}{正如我所说，这是不可避免的。你所能做的就是做好准备。你可以购买武器，建造围栏，恢复损失的财产，甚至创建一个更高效的灌溉系统。奇怪的是，你只需要我公司的服务。}
### {287}{}{Are you offering a deal?}
{287}{}{你提供交易吗？}
### {288}{}{Considering that the whole city is to blame for your troubles and that the factory was opened by your own hands, I propose to provide services to your Villa at a very low price. This will give jobs to the city and allow your people to prepare for the inevitable. Everyone will benefit.}
{288}{}{考虑到整个城市都应该为你的麻烦负责，而且工厂是你自己开的，我建议以很低的价格为你的别墅提供服务。这将为城市提供就业机会，让你的人民为不可避免的事情做好准备。每个人都会受益。}
### {289}{}{Sounds interesting. But there is a problem in convincing the elders. I'll think about it.}
{289}{}{听起来很有趣。但是，说服长辈是有问题的。我会考虑的。}

### {300}{}{What's on your mind?}
{300}{}{你在想什么？}
### {301}{}{Nothing special. I'm going to do something.}
{301}{}{没什么特别的。我要做点什么。}

#Quest 2
### {310}{}{Old Lucas made an unforgivable mistake. He hit my reputation. And more importantly, he ruined my plans.}
{310}{}{老卢卡斯犯了一个不可原谅的错误。他损害了我的声誉。更重要的是，他毁了我的计划。}
### {311}{}{[Listen]}
{311}{}{[听]}
### {312}{}{But that's not the main thing right now, I'll deal with it later. It is much more important to get radio components out of the factory. I need them as soon as possible. Can you do it?}
{312}{}{但这不是目前的主要问题，我稍后再处理。更重要的是把收音机部件从工厂里拿出来。我需要他们尽快。你能做到吗？}
### {313}{}{What if I kill Lucas?}
{313}{}{如果我杀了Lucas怎么办？}
### {314}{}{I doubt you have the guts and the skills. And if they kill you, then our whole conversation will be meaningless. Just get me what I'm asking for.}
{314}{}{我怀疑你是否有勇气和技巧。如果他们杀了你，那么我们的整个谈话将毫无意义。把我要的东西给我。}
### {315}{}{I see. I'll do it.}
{315}{}{我明白了。我会做的。}
### {316}{}{Well, no. Look for fools.}
{316}{}{不，找傻瓜。}
### {317}{}{Sure. I will do it.}
{317}{}{当然我会做的。}
### {318}{}{What will I get for it?}
{318}{}{我能得到什么？}
### {319}{}{Of course, I'll pay you for this job. But my respect is worth much more.}
{319}{}{当然，这份工作我会付钱给你的。但我的尊重更值得。}
### {320}{}{Is there anything else I can do for you, Mr. Kogan?}
{320}{}{Kogan先生，我还能为你做什么吗？}
### {1320}{}{Is there anything else I can do for you, Mr. Kogan?}
{1320}{}{Kogan先生，我还能为你做什么吗？}

### {330}{}{These are the parts from the abandoned factory.}
{330}{}{这些是废弃工厂的零件。}
### {331}{}{Great. I'm starting to like you. Now it's a small matter - to give this thing to the client.}
{331}{}{太棒了我开始喜欢你了。现在这是一件小事——把这个东西交给客户。}
### {332}{}{What about my reward?}
{332}{}{我的奖励呢？}
### {333}{}{You will receive it after the successful completion of the transaction.}
{333}{}{您将在交易成功完成后收到它。}
### {334}{}{What is the deal?}
{334}{}{怎么回事？}
### {335}{}{I am waiting for one very important caravan, with which a new milestone in the history of this city will begin. The caravan is following this detail. And I need reliable people to protect me during the transaction. Are you with us?}
{335}{}{我正在等待一辆非常重要的大篷车，这座城市历史上的一个新里程碑将由此开始。大篷车正在遵循这一细节。我需要可靠的人在交易过程中保护我。你和我们在一起吗？}
### {336}{}{And if I refuse?}
{336}{}{如果我拒绝了呢？}
### {337}{}{Then you'll upset me a lot. And it's better not to upset me.}
{337}{}{那你会让我很难过的。最好不要惹我生气。}
### {338}{}{Then I have to upset you a lot, fat man.}
{338}{}{那我得让你很难过，胖子。}
### {1338}{}{Then I have to make you very sad, fat man.}
{1338}{}{那我得让你很伤心，胖子。}
### {339}{}{Well, that was very stupid of you. Get out of my town. And you won't get any reward.}
{339}{}{你真是太愚蠢了。滚出我的城市。而且你不会得到任何奖励。}
### {340}{}{...}
{340}{}{...}
### {341}{}{ Yes. I'm with you.}
{341}{}{对我支持你。}
### {342}{}{Very good. Get ready for the meeting, take everything you need. And then come back to me.}
{342}{}{很好。为会议做好准备，带上你需要的一切。然后回到我身边。}
### {343}{}{OK.}
{343}{}{好啊}
### {344}{}{Okay, what should I do?}
{344}{}{好吧，我该怎么办？}

#Quest 3
### {350}{}{}
{350}{}{error : string is empty}
### {351}{}{Are you ready?}
{351}{}{你准备好了吗？}
### {1351}{}{Are you ready?}
{1351}{}{你准备好了吗？}
### {352}{}{Yes, I'm ready.}
{352}{}{是的，我准备好了。}
### {1352}{}{Yes, I'm ready.}
{1352}{}{是的，我准备好了。}
### {353}{}{No, I need to get something else. It won't take long.}
{353}{}{不，我需要其他东西。这不会花很长时间。}
### {354}{}{Be careful. Nobody knows about this deal, but anything can happen. I will talk to the caravan, your task is to make sure that everything goes as it should. The client should leave satisfied.}
{354}{}{小心。没有人知道这笔交易，但任何事情都有可能发生。我会和车队谈谈，你的任务是确保一切正常进行。客户应该满意地离开。}
### {355}{}{The goal is clear.}
{355}{}{目标很明确。}
### {356}{}{I could use a pee before an important case. Come back soon.}
{356}{}{我可以在一个重要案件之前小便。快回来。}

### {360}{}{The transaction was successful, wasn't it?}
{360}{}{交易成功了，不是吗？}
### {361}{}{It was a great deal. You have no idea how much. We didn't just earn caps. We gave the city a chance to survive.}
{361}{}{这是一笔巨大的交易。你不知道有多少。我们不仅仅是赢得了瓶盖。我们给了这座城市生存的机会。}
### {362}{}{What do you mean?}
{362}{}{你是什么意思？}
### {363}{}{This city is degenerating. We used to survive by extracting minerals from the ruins, but their reserves have become scarce. To survive, the city needs not just new orders, but a whole new production.}
{363}{}{这座城市正在退化。我们过去靠从废墟中提取矿物来生存，但它们的储量已经变得稀缺。为了生存，这座城市不仅需要新的订单，还需要全新的生产。}
### {364}{}{So are you going to rebuild that factory?}
{364}{}{你打算重建那家工厂吗？}
### {365}{}{Right. However, this will be a meaningless activity without a powerful source of energy. This can only be obtained in Flagstaff, the city where that caravan came from.}
{365}{}{正确的然而，如果没有强大的能量来源，这将是一项毫无意义的活动。这只能在弗拉格斯塔夫（Flagstaff）获得，那是商队的发源地。}
### {366}{}{Great idea. This is exactly what the ruined world lacks.}
{366}{}{好主意。这正是被毁灭的世界所缺乏的。}
### {367}{}{I am glad that we have reached an agreement. Someday you'll see Garage City like in the good old days - in shining vacuum tubes with a perky be-bop and bikers on motorcycles.}
{367}{}{我很高兴我们达成了协议。总有一天，你会看到车库城，就像过去一样——在闪闪发光的真空管里，有一个活泼的家伙和骑摩托车的人。}
### {368}{}{So what about our deal?}
{368}{}{那么我们的交易呢？}
### {369}{}{The current plant is madness!}
{369}{}{现在的工厂太疯狂了！}
### {370}{}{So many people think. But I am confident in my abilities. And someday you'll see Garage City like in the good old days - in shining vacuum tubes with a perky be-bop and bikers on motorcycles.}
{370}{}{很多人都这么想。但我对自己的能力充满信心。总有一天，你会看到车库城，就像过去一样——在闪闪发光的真空管里，有一个活泼的花花公子和骑摩托车的摩托车手。}
### {371}{}{So what about our deal?}
{371}{}{那么我们的交易呢？}
### {372}{}{Yeah, cool. So what about the payment?}
{372}{}{是的，很酷。那么付款呢？}
### {373}{}{I don't care. I'm only interested in our agreement.}
{373}{}{我不在乎。我只对我们的协议感兴趣。}

### {380}{}{I appreciate my business partners. Here's your fee for your work - here are 200 caps. I'll also tell Pete to serve you to the fullest. Make yourself at home.}
{380}{}{我感谢我的商业伙伴。这是你的工作费——这里有200个瓶盖。我也会告诉皮特为你服务到极致。别拘束。}
### {381}{}{I'm going to spend the bottlecaps.}
{381}{}{我要花掉瓶子里的钱。}
### {382}{}{What about the Villa and the raiders?}
{382}{}{别墅和袭击者呢？}
### {383}{}{And you still won't calm down... The slave convoy has gone to the city of Flagstaff, it is located to the east, a week away from here. Go along the 40th federal highway, you won't miss.}
{383}{}{你还是不会冷静下来...奴隶车队已经前往弗拉格斯塔夫市，该市位于东部，距离这里一周路程。沿着40号联邦高速公路走，你不会错过的。}
### {384}{}{Great, now I'm going to deal with these damn raiders.}
{384}{}{太好了，现在我要对付这些该死的袭击者。}
### {385}{}{I hope there will be something to spend the earned caps on.}
{385}{}{我希望有一些东西可以花掉赚来的上限。}
### {386}{}{How could you accept slavers? Does your conscience torment you?}
{386}{}{你怎么能接受奴隶主？你的良心折磨你吗？}
### {387}{}{You know, fat guy. If I had a nuclear bomb, I would blow up this whole town after what I heard. But I don't have it. Unfortunately.}
{387}{}{你知道，胖子。如果我有一枚核弹，我会在听到这些消息后炸毁整个城镇。但我没有。不幸的是。}
### {1387}{}{You know, fat guy. If I had a nuclear bomb, I would blow up this whole city after hearing what I heard. But I don't have it. Unfortunately.}
{1387}{}{你知道，胖子。如果我有一枚核弹，我会在听到我所听到的之后炸毁整个城市。但我没有。不幸的是。}
### {388}{}{A. Well okay. Later.}
{388}{}{A.好吧。后来}

### {390}{}{You might be pleased to hear that Lucas is dead.}
{390}{}{听到卢卡斯死了，你可能会很高兴。}
### {391}{}{Good job. Here's your reward, 100 caps. You can spend it at a local bar, although I don't think that after this you will be met there amicably.}
{391}{}{干得好这是你的奖励，100个瓶盖。你可以在当地的酒吧消费，尽管我认为在这之后你不会在那里友好地见面。}
### {392}{}{Thank you for the bottlecaps, Mr. Kogan.}
{392}{}{谢谢你给我的瓶子，Kogan先生。}
### {393}{}{I was hoping for a different amount for such dirty work. But this one will do.}
{393}{}{我希望能得到不同的报酬。但这一次就行了。}
### {1393}{}{I was hoping for a different amount for such dirty work. But this one will do.}
{1393}{}{我希望能得到不同的报酬。但这一次就行了。}
### {394}{}{Can I ask you a question? What do you feel after getting rid of a competitor?}
{394}{}{我能问你一个问题吗？摆脱竞争对手后你有什么感觉？}
### {395}{}{And what does a person feel after getting rid of garbage? Relief, I suppose. Although, I confess, I am also haunted by a faint sense of loss.}
{395}{}{一个人在扔掉垃圾后会有什么感受？我想是松了一口气。尽管，我承认，我也有一种淡淡的失落感。}
### {396}{}{Go ahead.}
{396}{}{着手}
### {397}{}{Really?}
{397}{}{真正地}
### {398}{}{Lucas was one of the best scavengers. We were friends at one time. But even such an experienced and valuable person eventually turned out to be a traitor and set a bad example to others. And I'm absolutely not going to worry about it for a long time.}
{398}{}{卢卡斯是最好的拾荒者之一。我们曾经是朋友。但即使是这样一个经验丰富、有价值的人，最终也变成了叛徒，给别人树立了坏榜样。我绝对不会在很长一段时间内担心它。}
### {399}{}{An original point of view.}
{399}{}{独到的观点。}
