### {100}{}{This is the senior shepherd.}
{100}{}{这是高级牧羊人。}
### {101}{}{You see a cattleman in worn desert clothes.}
{101}{}{你看到一个穿着破旧的沙漠服装的牧场主。}

### {111}{}{All right, stranger, take the brahmin. And may our paths part.}
{111}{}{好吧，陌生人，带上婆罗门。愿我们的路分开。}
### {1111}{}{All right, stranger, take the brahmin. And may our paths part.}
{1111}{}{好吧，陌生人，带上婆罗门。愿我们的路分开。}
### {112}{}{I hope our paths will never meet again.}
{112}{}{我希望我们的道路再也不会相遇。}

### {200}{}{Hey, stranger, don't get too close to the brahmin. What do you want from our peaceful camp?}
{200}{}{嘿，陌生人，不要离婆罗门太近。你想从我们的和平营地得到什么？}
### {1200}{}{Hey, woman, don't get too close to a brahmin. What do you want from our peaceful camp?}
{1200}{}{嘿，女人，不要离婆罗门太近。你想从我们的和平营地得到什么？}
### {201}{}{I need your brahmin... No, the whole Garage City needs your brahmin.}
{201}{}{我需要你的婆罗门...不，整个车库城都需要你的婆罗门。}
### {202}{}{We don't share sacred animals with scum. Leave us.}
{202}{}{我们不与渣滓共享神圣的动物。离开我们。}
### {203}{}{Okay, I'll leave.}
{203}{}{好的，我走。}
### {204}{}{It's worse for you. Go away!}
{204}{}{这对你来说更糟。走开！}

### {220}{}{How did you manage to tame this animal?}
{220}{}{你是怎么驯服这只动物的？}
### {221}{}{It was born among people. From another brahmin who also lived among people.}
{221}{}{它是在人与人之间诞生的。来自另一个同样生活在人群中的婆罗门。}
### {222}{}{So are you from San Brahmin?}
{222}{}{你是圣婆罗门人吗？}
### {223}{}{The Northern Horn Clan. Our people do not like a noisy city, we try to visit San Brahmin only on business.}
{223}{}{北角部族。我们的人民不喜欢喧闹的城市，我们只在出差时去拜访圣婆罗门。}
### {224}{}{I see. Well, I won't bother you.}
{224}{}{我明白了。好吧，我不会打扰你的。}
### {225}{}{This is the first time I've heard of anyone succeeding.}
{225}{}{这是我第一次听说有人成功。}
### {226}{}{We've been keeping our secrets from outsiders for generations. If you find yourself in our city, which strangers call San Brahmin, you will see everything with your own eyes.}
{226}{}{几代人以来，我们一直对外界保密。如果你发现自己在我们的城市，陌生人称之为圣婆罗门，你会亲眼看到一切。}
### {227}{}{I see. Well, I won't bother you.}
{227}{}{我明白了。好吧，我不会打扰你的。}

### {230}{}{There are some scavengers over there. If you don't give them the brahmin, they will take him by force.}
{230}{}{那边有一些拾荒者。如果你不把婆罗门交给他们，他们就会强行带走他。}
### {231}{}{Threats are a common thing for palefaces. Tell them we'll defend ourselves. They cannot defeat those who are protected by the Spirit of the Wasteland.}
{231}{}{威胁对苍白的人来说很常见。告诉他们我们会自卫。他们无法击败那些受到荒原之灵保护的人。}
### {232}{}{Abandon the brahmin if life is precious.}
{232}{}{如果生命宝贵，就抛弃婆罗门。}
### {233}{}{We cannot be intimidated. I've said it all.}
{233}{}{我们不能被吓倒。我都说了。}
### {234}{}{Damn pale faces! We'll leave. But let the meat of this sacred animal become poison for you. Ar-r!}
{234}{}{该死的苍白的脸！我们会离开的。但是，让这种神圣动物的肉成为你的毒药吧。Ar-r！}
### {235}{}{A reasonable solution.}
{235}{}{一个合理的解决方案。}
### {236}{}{Trust me, I'm trying to save your skins. I am from Villa, we are friends for San Brahmin tribes.}
{236}{}{相信我，我在努力挽救你的性命。我来自维拉，我们是圣婆罗门部落的朋友。}
### {237}{}{I've heard about you. If you say that we will be killed, it remains to believe. Tell these savages not to touch us.}
{237}{}{我听说过你。如果你说我们会被杀，那还有待相信。告诉这些野蛮人不要碰我们。}
### {238}{}{You will not be able to resist their weapons. Hand over the brahmin or you will be killed.}
{238}{}{你将无法抵抗他们的武器。交出婆罗门，否则你会被杀的。}
### {239}{}{I'm trying to avoid bloodshed. }
{239}{}{我尽量避免流血。}

### {240}{}{Maybe I can buy out a brahmin?}
{240}{}{也许我可以买下一个婆罗门？}
### {241}{}{(exchange glances) What can you offer in return?}
{241}{}{（交换眼神）你能提供什么作为回报？}
### {242}{}{Let's see...}
{242}{}{让我们看看...}
### {243}{}{To be honest, I don't have anything. Sorry to bother you in vain.}
{243}{}{老实说，我什么都没有。很抱歉白打扰你。}
### {244}{}{I'm offering you a pitchfork. Eat, stupid rednecks!}
{244}{}{我给你一把干草叉。吃吧，愚蠢的乡下人！}
### {245}{}{Shepherds are no longer a hindrance to your plans.}
{245}{}{牧羊人不再是你计划的障碍。}
### {246}{}{This is where our paths diverge, stranger.}
{246}{}{这就是我们分道扬镳的地方，陌生人。}
### {1246}{}{This is where our paths diverge, stranger.}
{1246}{}{这就是我们分道扬镳的地方，陌生人。}
### {247}{}{[Leave]}
{247}{}{[离开]}
