### {100}{}{This is Eugene.}
{100}{}{这是尤金。}
### {101}{}{You see a teenager. His hands are dirty with dirt and rust, apparently he likes to tinker with technology.}
{101}{}{你看到一个青少年。他的手上沾满了污垢和铁锈，显然他喜欢摆弄技术。}
### {102}{}{Did you want a happy life, man? This is the best I can offer.}
{102}{}{你想要幸福的生活吗，伙计？这是我能提供的最好的。}
### {103}{}{Sorry, man, but in this life you were expected only pain and suffering.}
{103}{}{对不起，伙计，但在这一生中，你所期望的只是痛苦和折磨。}
### {104}{}{Eugene has reached his destination.}
{104}{}{尤金已经到达目的地。}
### {105}{}{Wow!}
{105}{}{哇！}
### {106}{}{While Eugene is on your team, you get a bonus of 20 points to repair broken equipment.}
{106}{}{当尤金在你的团队中时，你可以获得20分的奖金来修复损坏的设备。}

#Floating replicas when visiting locations:
### {120}{}{ }
{120}{}{error : string is empty}
### {121}{}{Wow! I've never seen anything like it!}
{121}{}{哇！我从来没有见过这样的东西！}
### {122}{}{Is this a real live radio station? Awesome!}
{122}{}{这是一个真正的现场广播电台吗？令人惊叹的}
### {123}{}{ }
{123}{}{error : string is empty}
### {124}{}{Let's get out of here, this place scares me.}
{124}{}{让我们离开这里，这个地方让我害怕。}
### {125}{}{You're lucky to have a house like this. But I have to live in a barrack made of garbage.}
{125}{}{你很幸运有这样的房子。但我不得不住在垃圾堆成的营房里。}
### {126}{}{I've heard about this city, but I didn't even hope to be here!}
{126}{}{我听说过这个城市，但我甚至不希望来到这里！}
### {127}{}{I don't know why, but I don't like this place.}
{127}{}{我不知道为什么，但我不喜欢这个地方。}
### {128}{}{It doesn't look like a ranger base. Don't you think we've lost our way?}
{128}{}{它看起来不像一个护林员基地。你不觉得我们迷路了吗？}
### {129}{}{What are all these people doing?}
{129}{}{这些人在干什么？}
### {130}{}{What... what happened here?!}
{130}{}{什么这里发生了什么？！}

#Final dialogue
### {190}{}{Thanks for everything. These rangers are tough guys, and their dam is a real fortress. I'm so happy!}
{190}{}{谢谢你所做的一切。这些护林员是硬汉，他们的堤坝是真正的堡垒。我太高兴了！}
### {191}{}{It's good that you like it here. Have a good stay.}
{191}{}{你喜欢这里真好。祝你住得愉快。}
### {192}{}{Pull up your pants, sucker. You still have a lot to learn.}
{192}{}{把你的裤子拉起来，笨蛋。你还有很多东西要学。}
### {193}{}{Hi.}
{193}{}{你好}
### {194}{}{For now.}
{194}{}{现在。}

### {195}{}{They say a lot of bad things about you in the wastelands. Don't you want to explain?}
{195}{}{他们在荒原上说了很多关于你的不好的话。你不想解释一下吗？}
### {196}{}{To be honest, you are just an object of earnings for me. No more than that.}
{196}{}{老实说，对我来说，你只是一个收入对象。仅此而已。}
### {197}{}{This is the gossip of my enemies. Nevermind.}
{197}{}{这是我敌人的流言蜚语。永远不会。}
### {198}{}{I thought so...}
{198}{}{我是这么想的...}
### {199}{}{M?}
{199}{}{M}

#The first dialog
### {200}{}{And who else are you? Hey, you're not from around here!}
{200}{}{你还有谁？嘿，你不是这一带的人！}
### {201}{}{Uh, yeah.}
{201}{}{嗯，是的。}
### {202}{}{Then where are you from? Are you also engaged in enslaving peasants?}
{202}{}{那你是哪里人？你也在奴役农民吗？}
### {203}{}{Actually... YES!}
{203}{}{事实上是的！}
### {204}{}{Get away from me!}
{204}{}{离我远点！}
### {205}{}{Hey, don't be so nervous...}
{205}{}{嘿，别那么紧张...}
### {206}{}{On the contrary, I release them. What do you know about the attack on the Villa?}
{206}{}{相反，我释放了他们。你对维拉遇袭事件了解多少？}
### {207}{}{Nothing. Better leave before the others give you a "warm" welcome.}
{207}{}{没有什么最好在别人热情欢迎你之前离开。}
### {208}{}{Why would they do that?}
{208}{}{他们为什么要那样做？}
### {209}{}{Okay, okay, I'm hardly going to stay here.}
{209}{}{好吧，好吧，我很难留在这里。}
### {210}{}{This place is dying. Soon there will be no resources left in the ruins. Then the cartel will close, and the residents will be left with only a bandit's share. How I wish I could get out of this damn place!}
{210}{}{这个地方正在消亡。废墟中很快就没有资源了。然后卡特尔将关闭，居民将只剩下土匪的一份。我多么希望我能离开这个该死的地方！}
### {211}{}{Where, for example?}
{211}{}{例如，在哪里？}
### {212}{}{To the Rangers. Or just to the south, where there is at least some kind of civilization.}
{212}{}{致游骑兵队。或者只是在南方，那里至少有某种文明。}
### {213}{}{You have ambitious plans. Adios, muchacho.}
{213}{}{你有雄心勃勃的计划。再见，伙计。}
### {214}{}{What do you know about the enslavement of the Villa?}
{214}{}{你对别墅的奴役了解多少？}
### {215}{}{Hi.}
{215}{}{你好}
### {216}{}{Bye.}
{216}{}{再见}
### {217}{}{Todd lives here. He doesn't like uninvited guests.}
{217}{}{托德住在这里。他不喜欢不速之客。}

#In the team
### {220}{}{Why are we still here?}
{220}{}{为什么我们还在这里？}

### {221}{}{Are we going to be with the Rangers soon?}
{221}{}{我们会很快和游骑兵队在一起吗？}
### {222}{}{Do we have a long way to go?}
{222}{}{我们还有很长的路要走吗？}
### {223}{}{I'm tired...}
{223}{}{我累了...}
### {224}{}{Let's make a halt, eh?}
{224}{}{让我们停下来，嗯？}
### {225}{}{I can't wait to see the Ranger Dam.}
{225}{}{我等不及要去看游骑兵大坝了。}
### {226}{}{Do you know exactly where to go?}
{226}{}{你知道该去哪里吗？}
### {227}{}{It must be great to travel in the company of rangers.}
{227}{}{和护林员一起旅行一定很棒。}
### {228}{}{Is it true that rangers drink their urine while traveling?}
{228}{}{护林员在旅行时喝尿是真的吗？}
### {229}{}{I wish I could see the Ranger General himself!}
{229}{}{我希望我能亲眼见到游骑兵将军！}

### {230}{}{Wait here, I'll be back soon.}
{230}{}{在这里等着，我很快就会回来。}
### {231}{}{Let's go.}
{231}{}{我们走吧。}
### {232}{}{Get it out of your hands.}
{232}{}{把它从你手里拿开。}
### {233}{}{But you will protect me, won't you?}
{233}{}{但你会保护我的，不是吗？}
### {234}{}{Take it off yourself.}
{234}{}{你自己把它摘下来。}
### {235}{}{Whatever you say.}
{235}{}{不管你说什么。}

### {236}{}{I want to get home as soon as possible... However, I don't know what I want anymore.}
{236}{}{我想尽快回家...然而，我不知道我想要什么了。}
### {237}{}{I don't like your team. Are they coming with us too? Then I'm staying.}
{237}{}{我不喜欢你们队。他们也和我们一起去吗？那我就留下来。}
### {238}{}{That's not a good idea, man.}
{238}{}{这不是个好主意，伙计。}
### {239}{}{Eugene doesn't trust your noisy team, he'll only go with you.}
{239}{}{尤金不信任你吵闹的团队，他只会和你一起去。}

#Joining the team
### {300}{}{Hey, man, the Rangers are interested in your skills. I'm here to take you to the base.}
{300}{}{嘿，伙计，游骑兵队对你的技术很感兴趣。我是来带你去基地的。}
### {301}{}{What?! Is it true?! Wow! Yes, I've been dreaming about this since the day I first saw Ranger. But...}
{301}{}{什么这是真的吗？！哇！是的，从我第一次看到流浪者的那天起，我就一直梦想着这个。但是}
### {302}{}{But?}
{302}{}{但是}
### {303}{}{My father won't let me go. He doesn't even want to hear about Rangers and thinks I should be like him, a scavenger. But I'm not interested in digging into scrap metal, I want to repair this scrap metal!}
{303}{}{我爸爸不让我走。他甚至不想听到流浪者队的消息，认为我应该像他一样，一个拾荒者。但我对挖掘废金属不感兴趣，我想修理这个废金属！}
### {304}{}{Exactly. Your talents won't be able to reveal themselves in this place. Go to the Rangers.}
{304}{}{确切地你的才能不会在这个地方显露出来。去游骑兵队。}
### {305}{}{I can't run away. And if I run away, the locals will become bitter against the rangers. They already treat them with contempt. Please talk to your father! Maybe he'll listen to you?}
{305}{}{我不能逃跑。如果我逃跑了，当地人会对护林员很反感。他们已经蔑视他们了。请和你爸爸谈谈！也许他会听你的？}
### {306}{}{Okay, I'll talk to him.}
{306}{}{好吧，我和他谈谈。}
### {307}{}{The offer about the Rangers is still valid.}
{307}{}{关于流浪者队的报价仍然有效。}
### {308}{}{It's great... But I can't leave until my father agrees.}
{308}{}{太棒了...但在我父亲同意之前，我不能离开。}
### {309}{}{Okay, I'll talk to him.}
{309}{}{好吧，我和他谈谈。}
### {310}{}{Your padre has agreed. You can be free.}
{310}{}{你的牧师已经同意了。你可以自由。}
### {311}{}{Really?! I didn't even hope. I thought he'd never let me... So when do we leave?}
{311}{}{真正地我甚至没有希望。我以为他永远不会让我…那么我们什么时候离开？}
### {312}{}{Right now. Let's go.}
{312}{}{马上我们走吧。}
### {313}{}{Your padre is dead. You're free now.}
{313}{}{你的牧师死了。你现在有空了。}
### {314}{}{How?! But... I didn't think it would turn out like this. (sobbing) Whatever he was, he wanted only the best for me... (calms down) Well, now I definitely have nothing to lose. When do we leave?}
{314}{}{怎样但是我没想到会变成这样。（抽泣着）不管他是谁，他只想给我最好的……（冷静下来）好吧，现在我肯定没有什么可失去的了。我们什么时候离开？}
### {315}{}{Right now. Come on.}
{315}{}{马上来吧}
### {316}{}{How about an inconspicuous portion of scorpion venom?}
{316}{}{一份不起眼的蝎子毒液怎么样？}
### {317}{}{It's not serious, is it? I will never forgive you then!}
{317}{}{这不严重，是吗？那我永远不会原谅你！}
### {318}{}{Don't you want to just run away?}
{318}{}{你不想逃跑吗？}
### {319}{}{Then the Rangers will be treated even worse here than they are now. And I won't run far.}
{319}{}{然后流浪者队在这里会受到比现在更糟糕的待遇。而且我不会跑很远。}

# If the dam is destroyed
### {320}{}{I have bad news for you: the Ranger base has been destroyed.}
{320}{}{我有个坏消息要告诉你：游骑兵基地被毁了。}
### {321}{}{It can't be! I was so hoping that everything would get better... that you don't have to pick through the trash anymore for a couple of caps... But I don't want to go home now either. What should I do?}
{321}{}{不可能！我非常希望一切都会好起来...你再也不用为了几个瓶盖而翻垃圾了...但我现在也不想回家。我该怎么办？}
### {322}{}{You won't survive alone in the desert, and the Rangers aren't up to you right now. Come home.}
{322}{}{你无法独自在沙漠中生存，而游骑兵队现在也无法胜任你。回家吧。}
### {323}{}{Now no one will pay me to guard your ass. Which means you're on your own. Disappear.}
{323}{}{现在没有人会付钱给我来保护你的屁股，这意味着你只能靠自己了。消失}
### {324}{}{My father warned me not to trust you. I'll find my own way!}
{324}{}{我父亲警告我不要相信你。我会找到自己的路！}
### {325}{}{That's great.}
{325}{}{太好了。}
### {326}{}{Yes, of course... I can't believe it was all in vain!}
{326}{}{是的，当然...我不敢相信这一切都是徒劳的！}
### {327}{}{Well, maybe life in a landfill isn't so bad. Let's go.}
{327}{}{也许垃圾填埋场的生活没那么糟糕。我们走吧。}
### {328}{}{Here you are at home. What's the matter?}
{328}{}{你在家。怎么了？}
### {329}{}{You know... This journey with you has not been in vain. I've seen so much, discovered a whole world I didn't know anything about. After all this, I will not be able to live in the old way. Someday I will definitely go south.}
{329}{}{你知道...和你的这次旅行没有白费。我看到了很多，发现了一个我一无所知的世界。在经历了这一切之后，我将不能再过旧的生活了。总有一天我一定会南下。}
### {330}{}{Sounds flattering, though sad. Goodbye.}
{330}{}{听起来很讨人喜欢，但很难过。再见}
### {331}{}{Well, you now have the right to decide for yourself. My job is done. Have a good stay.}
{331}{}{好吧，你现在有权自己决定。我的工作完成了。祝你住得愉快。}
