### {100}{}{Here is a scavenger.}
{100}{}{这是一个拾荒者。}
### {101}{}{You see a guy red with tension.}
{101}{}{你看到一个人紧张得通红。}

### {110}{}{Don't you dare blab}
{110}{}{你不敢大声说}
### {111}{}{Please don't hit me! I will improve, honestly!}
{111}{}{请不要打我！老实说，我会进步的！}

### {200}{}{Which... Who are you anyway? What do you need?}
{200}{}{哪一个你到底是谁？你需要什么？}
### {201}{}{I'm just watching you guys having all the fun.}
{201}{}{我只是看着你们玩得很开心。}
### {202}{}{Yeah. Any problems?}
{202}{}{是 啊有什么问题吗？}
### {203}{}{Hey, what are you doing?}
{203}{}{嘿，你在干什么？}
### {204}{}{We're dancing here. On the mattress. Got it?}
{204}{}{我们在这里跳舞。在床垫上。明白了吗？}
### {205}{}{I want to join.}
{205}{}{我想加入。}
### {206}{}{You're not right in the head. Get lost, you idiot!}
{206}{}{你脑子不对劲。迷路吧，你这个白痴！}
### {1206}{}{You're not right in the head. And we have nothing to do with women who are knocked out. Get lost!}
{1206}{}{你脑子不对劲。我们与那些被淘汰的女性没有任何关系。迷路}
### {207}{}{Chill out, man, I'm already leaving...}
{207}{}{冷静点，伙计，我已经走了。。。}
### {208}{}{I won't let you go on.}
{208}{}{我不会让你继续下去的。}
### {209}{}{Uh-oh, we have the very Nobility here.  And what will you do? Well, tell me, BITCH?}
{209}{}{哦，我们这里有贵族。你会怎么做？告诉我吧，婊子？}
### {210}{}{I'll just leave and not bother you. Have fun, guys.}
{210}{}{我就走了，不打扰你。玩得开心，伙计们。}
### {211}{}{I'll kill you. Die, you creatures!}
{211}{}{我会杀了你。死吧，你们这些生物！}
### {212}{}{I'll take out my gun and wait exactly three seconds. One... two...}
{212}{}{我会拿出枪等三秒钟。一二}
### {213}{}{}
{213}{}{error : string is empty}
### {214}{}{Okay, okay! Calm down, man! Keep the gun to yourself. We are not such animals, eh, we can calmly solve everything.}
{214}{}{好吧，好吧！冷静点，伙计！把枪留给自己。我们不是这样的动物，嗯，我们可以冷静地解决一切。}
### {1214}{}{Okay, okay! Calm down, dude! Keep the gun to yourself. We are not such animals, eh, we can calmly solve everything.}
{1214}{}{好吧，好吧！冷静点，伙计！把枪留给自己。我们不是这样的动物，嗯，我们可以冷静地解决一切。}
### {215}{}{Get out of here.}
{215}{}{离开这里。}
### {216}{}{The doors are open.}
{216}{}{门是开着的。}
### {217}{}{You're disturbing my sleep.}
{217}{}{你扰乱了我的睡眠。}
### {218}{}{Hey, we paid for the room and we can do whatever we want. Do you understand?}
{218}{}{嘿，我们付了房费，我们想做什么就做什么。你明白吗？}
### {219}{}{If you don't stop, you will have problems with the whole city.}
{219}{}{如果你不停下来，整个城市都会有问题。}
### {220}{}{We know who you are, you lousy digger. No one invited you to our city. So you can't intimidate us.}
{220}{}{我们知道你是谁，你这个讨厌的挖掘者。没有人邀请你来我们的城市。所以你不能恐吓我们。}
### {221}{}{Okay. But you'll remember me again.}
{221}{}{可以但你会记得我的。}
### {222}{}{Know your place, punk. If you don't calm down, you will have problems.}
{222}{}{知道你的位置，朋克。如果你不冷静下来，你就会遇到问题。}
### {223}{}{Uh, okay... We don't need any problems. We'll leave as if we weren't there...}
{223}{}{好吧。。。我们不需要任何问题。我们会离开，就好像我们不在那里一样。。。}
