### {102}{}{The intruder! Alarm!}
{102}{}{入侵者！惊恐}

### {200}{}{Dios mio, who are you?}
{200}{}{迪奥斯·米奥，你是谁？}
### {201}{}{I am death to tyrants like you.}
{201}{}{我对你这样的暴君来说是死。}
### {202}{}{I was thinking about joining your squad.}
{202}{}{我在考虑加入你们的队伍。}
### {203}{}{What are you talking about? Capture the spy!}
{203}{}{你在说什么？抓住间谍！}
### {204}{}{Well, okay...}
{204}{}{好吧...}
### {205}{}{You're making a mistake, General.}
{205}{}{你犯了一个错误，将军。}
### {206}{}{Civilian. I want to join your army, General!}
{206}{}{平民我想加入你的军队，将军！}
### {207}{}{Very commendable. But considering how you got into the fort, you won't get any service. The commissioner will escort you to the exit. If you come back, it's worse for you. Is that clear? Now get out.}
{207}{}{非常值得称赞。但考虑到你是如何进入堡垒的，你不会得到任何服务。专员会护送你到出口。如果你回来了，情况会更糟。清楚吗？现在滚出去。}
### {1207}{}{Very commendable. But considering how you got into the fort, you won't get any service. The commissioner will escort you to the exit. If you come back, it's worse for you. And I will not look at the fact that you are a woman. Understand?}
{1207}{}{非常值得称赞。但考虑到你是如何进入堡垒的，你不会得到任何服务。专员会护送你到出口。如果你回来了，情况会更糟。我不会去看你是个女人的事实。懂}
### {208}{}{As you say, General.}
{208}{}{正如你所说，将军。}
### {209}{}{I'm not going anywhere.}
{209}{}{我哪儿也不去。}

### {210}{}{I warned you. Put him in the brig! Let him suffer with the rest of the prisoners of war.}
{210}{}{我警告过你。把他关进禁闭室！让他和其他战俘一起受苦吧。}
### {1210}{}{I warned you. Put her in the brig! Let him suffer with the rest of the prisoners of war.}
{1210}{}{我警告过你。把她关进禁闭室！让他和其他战俘一起受苦吧。}
### {211}{}{No, no, you can't go to the punishment cell, I have claustrophobia...}
{211}{}{不，不，你不能去惩罚室，我有幽闭恐惧症...}
### {212}{}{No one will drag me there.}
{212}{}{没有人会把我拖到那里。}
