### {100}{}{You see Dominguez's baby.}
{100}{}{你看到多明格斯的孩子了。}
### {101}{}{Here is a typical country boy. And he smells like it.}
{101}{}{这是一个典型的乡村男孩。他闻起来很香。}
### {102}{}{Hr-r-r...}
{102}{}{小时-小时...}
### {103}{}{The old shoes haven't worn out yet.}
{103}{}{这双旧鞋还没穿破。}
### {104}{}{The child is very happy about the new shoes.}
{104}{}{孩子对这双新鞋很满意。}
### {105}{}{Thank you!}
{105}{}{非常感谢。}

### {110}{}{Hi. Did you really come from the north?}
{110}{}{你好你真的来自北方吗？}
### {111}{}{Strange. You don't look like a man-eating savage.}
{111}{}{奇怪的你看起来不像个吃人的野蛮人。}
### {112}{}{We have always been told that only savages live in the north.}
{112}{}{我们一直被告知只有野蛮人生活在北方。}
### {113}{}{Do you really eat people there in the north?}
{113}{}{你真的吃北方的人吗？}
### {114}{}{Someday General Sarabia will capture Arizona.}
{114}{}{萨拉比亚将军总有一天会占领亚利桑那州。}
### {115}{}{Do you want to push Vaka?}
{115}{}{你想推瓦卡吗？}
### {116}{}{It's better not to approach our waka. They don't tolerate strangers.}
{116}{}{最好不要接近我们的瓦卡。他们不容忍陌生人。}
### {117}{}{Do you want to ride the vaks? Then pay double the peso.}
{117}{}{你想坐电子烟吗？然后付双倍的比索。}
### {118}{}{Are you really paying with caps? Pf-ha-ha-ha!}
{118}{}{你真的有上限吗？哈哈哈！}
### {119}{}{Stupid Northerner! Stupid Northerner! Be-be-be!}
{119}{}{愚蠢的北方人！愚蠢的北方人！Be Be Be！}
### {120}{}{My shoes are torn. Do you have anything to replace it?}
{120}{}{我的鞋子破了。你有什么可以替换的吗？}

### {1110}{}{Hi. Did you really come from the north?}
{1110}{}{你好你真的来自北方吗？}
### {1111}{}{Strange. You don't look like a man-eating savage.}
{1111}{}{奇怪的你看起来不像个吃人的野蛮人。}
### {1112}{}{We have always been told that only savages live in the north.}
{1112}{}{我们一直被告知只有野蛮人生活在北方。}
### {1113}{}{Do you really eat people there, in the north?}
{1113}{}{你真的吃北方的人吗？}
### {1114}{}{Someday General Sarabia will take Arizona.}
{1114}{}{萨拉比亚将军总有一天会占领亚利桑那州。}
### {1115}{}{Do you want to push vaka?}
{1115}{}{你想推vaka吗？}
### {1116}{}{It's better not to approach our waka. They don't tolerate strangers.}
{1116}{}{最好不要接近我们的瓦卡。他们不容忍陌生人。}
### {1117}{}{Do you want to ride the vaks? Then pay double the peso.}
{1117}{}{你想坐电子烟吗？然后付双倍的比索。}
### {1118}{}{Do you really pay with caps? Pf-ha-ha-ha!}
{1118}{}{你真的有上限吗？哈哈哈！}
### {1119}{}{Stupid Northerner! Stupid Northerner! Be-be-be!}
{1119}{}{愚蠢的北方人！愚蠢的北方人！Be Be Be！}
