### {102}{}{ gets one bottle cap.}
{102}{}{得到一个瓶盖。}
### {103}{}{This item won't help here.}
{103}{}{这个项目在这里没有帮助。}
### {104}{}{This won't help here}
{104}{}{这对这里没有帮助}
### {105}{}{This skill won't help here.}
{105}{}{这种技能在这里没有帮助。}
### {106}{}{This man refuses to go any further.}
{106}{}{这个人拒绝再往前走了。}
### {107}{}{This creature refuses to go any further.}
{107}{}{这个生物拒绝走得更远。}
### {108}{}{This hostile person refuses to obey you.}
{108}{}{这个充满敌意的人拒绝服从你。}
### {109}{}{This hostile creature refuses to obey you.}
{109}{}{这个充满敌意的生物拒绝服从你。}

#---------------------------------------------
# Names of skills and basic parameters
#---------------------------------------------
### {110}{}{Small arms}
{110}{}{小型武器}
### {111}{}{A big weapon}
{111}{}{一件大武器}
### {112}{}{Energy weapons}
{112}{}{能源武器}
### {113}{}{Hand-to-hand combat}
{113}{}{肉搏战}
### {114}{}{Edged weapons}
{114}{}{边缘武器}
### {115}{}{Throwing}
{115}{}{投掷}
### {116}{}{First aid}
{116}{}{急救}
### {117}{}{Doctor}
{117}{}{医生}
### {118}{}{Stealth}
{118}{}{隐身}
### {119}{}{Hacking}
{119}{}{黑客攻击}
### {120}{}{Theft}
{120}{}{盗窃}
### {121}{}{Traps}
{121}{}{陷阱}
### {122}{}{Science}
{122}{}{科学}
### {123}{}{Repair}
{123}{}{修理}
### {124}{}{Eloquence}
{124}{}{口才}
### {125}{}{Trade}
{125}{}{贸易}
### {126}{}{Gambling}
{126}{}{赌博}
### {127}{}{Survival}
{127}{}{生存}

### {130}{}{You have improved the skill "}
{130}{}{你提高了技能”}
### {131}{}{" on }
{131}{}{“在}
### {132}{}{.}
{132}{}{。}

### {133}{}{[}
{133}{}{[}
### {134}{}{] }
{134}{}{]}

### {135}{}{Attitude}
{135}{}{态度}
### {136}{}{Reputation}
{136}{}{名誉}
### {137}{}{Glory}
{137}{}{荣誉}
### {138}{}{Level}
{138}{}{数量}

### {140}{}{}
{140}{}{error : string is empty}
### {141}{}{With your skills, this is not possible.}
{141}{}{以你的技术，这是不可能的。}
### {142}{}{This creature cannot be robbed.}
{142}{}{这个生物不能被抢劫。}
### {143}{}{The victim didn't recognize your deception. You got out of the situation without consequences.}
{143}{}{受害者没有意识到你的欺骗。你摆脱了这种局面，没有任何后果。}
### {144}{}{This time you managed to convince the victim that there was a misunderstanding.}
{144}{}{这一次你设法让受害者相信存在误解。}
### {145}{}{The robot cannot be robbed while it is in active mode.}
{145}{}{机器人处于活动模式时不能被抢劫。}
### {146}{}{ it is watching you too closely.}
{146}{}{它太靠近你了。}
### {147}{}{Your skills do not allow you to heal these wounds without medication.}
{147}{}{你的技能不允许你在没有药物的情况下治愈这些伤口。}
### {148}{}{In power armor, it is impossible to commit pickpocketing.}
{148}{}{穿上权力盔甲，就不可能实施扒窃。}
### {149}{}{It can't be done.}
{149}{}{这是不可能的。}

### {150}{}{Power}
{150}{}{权力}
### {151}{}{Perception}
{151}{}{知觉}
### {152}{}{Endurance}
{152}{}{耐力}
### {153}{}{Charisma}
{153}{}{魅力}
### {154}{}{Intelligence}
{154}{}{智力}
### {155}{}{Dexterity}
{155}{}{灵巧}
### {156}{}{Luck}
{156}{}{好运}

#---------------------------------------------
# Gaining experience
#---------------------------------------------

### {200}{}{You have received }
{200}{}{您已收到}
### {201}{}{ experience points.}
{201}{}{经验点。}
### {202}{}{experience points for successful dialogue.}
{202}{}{成功对话的经验要点。}
### {203}{}{ experience points and reputation enhancement.}
{203}{}{体验点和声誉提升。}

#---------------------------------------------
# Injuries
#---------------------------------------------

### {300}{}{Your left leg is crippled! You are suffering from severe pain.}
{300}{}{你的左腿残废了！你正遭受着剧烈的疼痛。}
### {301}{}{Your right leg is crippled! You are suffering from severe pain.}
{301}{}{你的右腿残废了！你正遭受着剧烈的疼痛。}
### {302}{}{Your left arm is crippled! You are suffering from acute pain.}
{302}{}{你的左臂残废了！你正遭受着剧烈的疼痛。}
### {303}{}{Your right arm is crippled! You are suffering from acute pain.}
{303}{}{你的右臂残废了！你正遭受着剧烈的疼痛。}
### {304}{}{Your eyes are crippled! You are suffering from unbearable pain.}
{304}{}{你的眼睛残废了！你正遭受着难以忍受的痛苦。}
### {305}{}{Ugh, it's going to take a very long time to heal...}
{305}{}{呃，这需要很长时间才能痊愈...}

#---------------------------------------------
# Messages in battle
#---------------------------------------------

### {320}{}{ hesitates to make an attack.}
{320}{}{犹豫是否发起进攻。}
### {321}{}{ regenerates and restores some health.}
{321}{}{再生并恢复一些健康。}
### {322}{}{!!!}
{322}{}{！！！}
### {323}{}{Scared of fire }
{323}{}{怕火}
### {324}{}{flees.}
{324}{}{逃跑。}
### {325}{}{Damn it!}
{325}{}{该死！}
### {326}{}{ loses power and perception when an e/m pulse disables part of its electronics.}
{326}{}{当e/m脉冲使其部分电子设备失效时，会失去电源和感知能力。}
### {327}{}{!}
{327}{}{！}
### {328}{}{This cannot be done during combat.}
{328}{}{在战斗中不能这样做。}
### {329}{}{Pi!}
{329}{}{Pi！}

#---------------------------------------------
# Replicas of futility (the wrong object, skill, etc. was used)
#---------------------------------------------

### {330}{}{Useless}
{330}{}{无用的}
### {331}{}{Not that}
{331}{}{不是这样}
### {332}{}{Something's wrong}
{332}{}{出了问题}
### {333}{}{To no avail}
{333}{}{无济于事}
### {334}{}{It doesn't work}
{334}{}{它不起作用}
### {335}{}{Hmm?}
{335}{}{嗯？}
### {336}{}{Too complicated}
{336}{}{太复杂了}
### {337}{}{Useless}
{337}{}{无用的}
### {338}{}{Useless}
{338}{}{无用的}
### {339}{}{Useless}
{339}{}{无用的}

#---------------------------------------------
# Replicas upon completion of cases (mine clearance, repair, refueling of the bike, etc.)
#---------------------------------------------

### {340}{}{Done}
{340}{}{完成}
### {341}{}{Okay}
{341}{}{可以}
### {342}{}{Great}
{342}{}{太棒了}
### {343}{}{Done}
{343}{}{完成}
### {344}{}{It turned out}
{344}{}{事实证明}
### {345}{}{Success}
{345}{}{成功}
### {346}{}{There is}
{346}{}{有}
### {347}{}{Done}
{347}{}{完成}
### {348}{}{Done}
{348}{}{完成}
### {349}{}{Done}
{349}{}{完成}

#---------------------------------------------
# The use of different items on the NPC
#---------------------------------------------

#Consumer goods
### {400}{}{ refuses to eat it.}
{400}{}{拒绝吃。}
### {401}{}{This experience brought you resourcefulness.}
{401}{}{这段经历给你带来了足智多谋。}
### {402}{}{ will not eat during the fight.}
{402}{}{在打斗中不会吃东西。}
### {403}{}{ refuses to take it out of your hands.}
{403}{}{拒绝把它从你手中夺走。}
### {404}{}{This does not apply to robots.}
{404}{}{这不适用于机器人。}
### {405}{}{The free distribution of food has brought you experience and fame.}
{405}{}{免费分发食物给你带来了经验和名声。}
### {406}{}{It doesn't apply to plants.}
{406}{}{它不适用于植物。}
### {407}{}{ refuses to accept it.}
{407}{}{拒绝接受。}
### {408}{}{This creature becomes more friendly to you.}
{408}{}{这个生物对你变得更加友好。}
### {409}{}{stimpacks only work on people.}
{409}{}{刺激包只对人有效。}
### {410}{}{Animals and mutants do not drink alcohol.}
{410}{}{动物和变种人不喝酒。}
### {411}{}{It won't work on flyers.}
{411}{}{它对传单不起作用。}
### {412}{}{ succumbs to the harmful effects of the chemical and becomes enraged.}
{412}{}{屈服于化学物质的有害影响而变得愤怒。}
### {413}{}{Alcohol? Not interested...}
{413}{}{含酒精饮料不感兴趣...}
### {414}{}{That's what I've been missing!}
{414}{}{这就是我一直错过的！}
### {415}{}{It is not necessary to tease the members of the Brotherhood with their own rations. You may be mistaken for a thief.}
{415}{}{没有必要用自己的口粮来戏弄兄弟会的成员。你可能被误认为是小偷。}
### {416}{}{Wow, that's generosity!}
{416}{}{哇，太慷慨了！}
### {417}{}{Will you really just give it to me?}
{417}{}{你真的会把它给我吗？}
### {418}{}{This item will not work through the protective helmet of power armor.}
{418}{}{此物品无法通过强力装甲的防护头盔工作。}
### {419}{}{The free distribution of valuable liquid has brought you experience and fame.}
{419}{}{免费分发有价值的液体为您带来了经验和声誉。}

#Clutter items
### {420}{}{I think it will be useful to me}
{420}{}{我认为这对我有用}
### {421}{}{Wow! Thank you!}
{421}{}{哇！非常感谢。}
### {422}{}{The child accepts your gift with joy. Surely he will tell his friends about your action.}
{422}{}{孩子高兴地接受了你的礼物。他肯定会把你的行为告诉他的朋友。}
### {423}{}{The child does not want to accept your gift. He seems to sense a hidden threat in you.}
{423}{}{孩子不想接受你的礼物。他似乎感觉到你身上隐藏着一种威胁。}
### {424}{}{A shovel will definitely not help here.}
{424}{}{铲子在这儿肯定没用。}
### {425}{}{Hacking a robot requires skills, a decoder will not help here.}
{425}{}{破解机器人需要技巧，解码器在这里没有帮助。}
### {426}{}{poisoned!}
{426}{}{中毒！}
### {427}{}{dies in terrible convulsions.}
{427}{}{死于剧烈抽搐。}
### {428}{}{falls dead.}
{428}{}{摔死了。}
### {429}{}{ loses consciousness and soon dies.}
{429}{}{失去意识并很快死亡。}
### {430}{}{ stops breathing.}
{430}{}{停止呼吸。}
### {431}{}{This cannot be done during combat.}
{431}{}{在战斗中不能这样做。}
### {432}{}{Your partner knows what this leads to.}
{432}{}{你的伴侣知道这会导致什么。}
### {433}{}{U-u-u!}
{433}{}{U-U-U！}
### {434}{}{You're needlessly scaring the child. There will surely be a more worthy use for this trafei.}
{434}{}{你在无谓地吓唬孩子。这辆车肯定会有更值得使用的地方。}
### {435}{}{You have made 20 signal cartridges from old festive pyrotechnics.}
{435}{}{你们用古老的节日烟火制作了20个信号弹。}

#Ammunition items
### {440}{}{}
{440}{}{error : string is empty}
### {441}{}{}
{441}{}{error : string is empty}
### {442}{}{}
{442}{}{error : string is empty}
### {443}{}{}
{443}{}{error : string is empty}
### {444}{}{}
{444}{}{error : string is empty}
### {445}{}{}
{445}{}{error : string is empty}
### {446}{}{}
{446}{}{error : string is empty}
### {447}{}{}
{447}{}{error : string is empty}
### {448}{}{}
{448}{}{error : string is empty}
### {449}{}{}
{449}{}{error : string is empty}
### {450}{}{}
{450}{}{error : string is empty}
### {451}{}{}
{451}{}{error : string is empty}
### {452}{}{}
{452}{}{error : string is empty}
### {453}{}{}
{453}{}{error : string is empty}
### {454}{}{}
{454}{}{error : string is empty}
### {455}{}{}
{455}{}{error : string is empty}
### {456}{}{}
{456}{}{error : string is empty}
### {457}{}{}
{457}{}{error : string is empty}
### {458}{}{}
{458}{}{error : string is empty}
### {459}{}{}
{459}{}{error : string is empty}

#Items ammunition
### {460}{}{}
{460}{}{error : string is empty}
### {461}{}{}
{461}{}{error : string is empty}
### {462}{}{}
{462}{}{error : string is empty}
### {463}{}{}
{463}{}{error : string is empty}
### {464}{}{}
{464}{}{error : string is empty}
### {465}{}{}
{465}{}{error : string is empty}
### {466}{}{}
{466}{}{error : string is empty}
### {467}{}{}
{467}{}{error : string is empty}
### {468}{}{}
{468}{}{error : string is empty}
### {469}{}{}
{469}{}{error : string is empty}
### {470}{}{}
{470}{}{error : string is empty}
### {471}{}{}
{471}{}{error : string is empty}
### {472}{}{}
{472}{}{error : string is empty}
### {473}{}{}
{473}{}{error : string is empty}
### {474}{}{}
{474}{}{error : string is empty}
### {475}{}{}
{475}{}{error : string is empty}
### {476}{}{}
{476}{}{error : string is empty}
### {477}{}{}
{477}{}{error : string is empty}
### {478}{}{}
{478}{}{error : string is empty}
### {479}{}{}
{479}{}{error : string is empty}

#Other items
### {480}{}{Usually keys are used on locks.}
{480}{}{通常钥匙用在锁上。}
### {481}{}{Amazingly. And as soon as it occurred to you...}
{481}{}{令人惊奇。你一想到...}
### {482}{}{The weapon should be used in combat mode, holding it in your hands.}
{482}{}{武器应该在战斗模式下使用，拿在手里。}
### {483}{}{With the help of a surgical kit, you have cured all your injuries.}
{483}{}{在手术包的帮助下，你治好了所有的伤。}
### {484}{}{With the help of a surgical kit, you cured the patient's injuries.}
{484}{}{在手术包的帮助下，你治好了病人的伤。}
### {485}{}{This item should be used out of hand.}
{485}{}{这个项目应该立即使用。}
### {486}{}{It is unlikely that this will help in fixing the robot.}
{486}{}{这不太可能有助于修复机器人。}
### {487}{}{ refuses your treatment.}
{487}{}{拒绝你的治疗。}
### {488}{}{You don't need surgical treatment.}
{488}{}{你不需要手术治疗。}
### {489}{}{This item should be used on a motorcycle.}
{489}{}{此物品应在摩托车上使用。}
### {490}{}{It won't help here.}
{490}{}{这对这里没有帮助。}
### {491}{}{You have found the use of an ancient relic.}
{491}{}{你发现了一件古代遗物的用途。}
### {492}{}{Your shovel has fallen into disrepair.}
{492}{}{你的铲子年久失修了。}
### {493}{}{A surgical kit won't help here.}
{493}{}{手术包在这里没用。}

#---------------------------------------------
# Dialog Options
#---------------------------------------------

#Critter
### {500}{}{This hostile person will not talk to you.}
{500}{}{这个充满敌意的人不会和你说话。}
### {501}{}{This robot has already been reprogrammed for your protection.}
{501}{}{为了保护你，这个机器人已经被重新编程了。}
### {502}{}{You have reprogrammed the robot for your protection.}
{502}{}{为了保护你，你已经重新编程了机器人。}
### {503}{}{}
{503}{}{error : string is empty}
### {504}{}{You can't reconfigure the robot to protect yourself.}
{504}{}{你不能重新配置机器人来保护自己。}
### {505}{}{What is it? Are you threatening me?}
{505}{}{它是什么？你在威胁我吗？}
### {506}{}{This person will not communicate with you while you are holding a weapon in your hands.}
{506}{}{当你手里拿着武器时，这个人不会与你交流。}
### {507}{}{This person is near death and cannot talk right now.}
{507}{}{这个人濒临死亡，现在不能说话。}
### {508}{}{. . .}
{508}{}{。}
### {509}{}{The negotiations failed.}
{509}{}{谈判失败了。}
### {510}{}{?}
{510}{}{？}
### {511}{}{You see a Madman.}
{511}{}{你看到一个疯子。}
### {512}{}{Without access to fresh air }
{512}{}{无法获得新鲜空气}
### {513}{}{suffocating in the freezer.}
{513}{}{在冰箱里令人窒息。}
### {514}{}{What is it? Are you threatening me?}
{514}{}{它是什么？你在威胁我吗？}
### {515}{}{Put away your weapon, otherwise I'll get mine}
{515}{}{把你的武器收起来，否则我就拿我的}
### {516}{}{Power armor alarms your interlocutor.}
{516}{}{力量盔甲会提醒对话者。}
### {517}{}{...}
{517}{}{...}
### {518}{}{It seems this robot can't talk.}
{518}{}{这个机器人好像不会说话。}
### {519}{}{This person refuses to obey you.}
{519}{}{这个人拒绝服从你。}

#Computers
### {550}{}{Access denied.}
{550}{}{访问被拒绝。}
### {551}{}{This cannot be done during combat.}
{551}{}{在战斗中不能这样做。}
### {552}{}{The defense system has already been hacked.}
{552}{}{防御系统已经被黑客入侵。}
### {553}{}{The defense system has been hacked!}
{553}{}{防御系统被黑客入侵了！}
### {554}{}{Access received.}
{554}{}{已接收访问。}
### {555}{}{The game turned out to be very exciting.}
{555}{}{比赛结果非常精彩。}
### {556}{}{You can't find the password.}
{556}{}{你找不到密码。}
### {557}{}{You have installed the decoder. Now hacking a computer will become much easier.}
{557}{}{您已安装解码器。现在破解电脑将变得容易得多。}
### {558}{}{The decoder won't help here anymore. It's time to use skills.}
{558}{}{解码器再也帮不上忙了。是时候运用技巧了。}
### {559}{}{}
{559}{}{error : string is empty}

#Repair of equipment
### {570}{}{ not in need of repair.}
{570}{}{不需要修理。}
### {571}{}{This cannot be done during combat.}
{571}{}{在战斗中不能这样做。}
### {572}{}{}
{572}{}{error : string is empty}
### {573}{}{You have no idea how it can be fixed. Perhaps the lack of skills will be solved by replacing parts.}
{573}{}{你不知道怎样才能修复它。也许通过更换零件可以解决技能不足的问题。}
### {574}{}{You have no idea how it can be fixed.}
{574}{}{你不知道怎样才能修复它。}
### {575}{}{Failure! You were unlucky and you were electrocuted.}
{575}{}{失败你运气不好，被电死了。}
### {576}{}{With these details, the repair will become a little easier.}
{576}{}{有了这些细节，维修会变得容易一些。}
### {577}{}{With these parts, the repair will become much easier.}
{577}{}{有了这些零件，修理就会容易得多。}
### {578}{}{Additional details won't help here. It's time to use skills.}
{578}{}{其他详细信息在这里没有帮助。是时候运用技巧了。}
### {579}{}{You see the ripper.}
{579}{}{你看到开膛手了。}

#---------------------------------------------
# Ring nicknames
#---------------------------------------------

#Important: male and female nicknames are antipodes and match by numbers with a difference of 50.
#- men's
### {600}{}{Crusader}
{600}{}{十字军}
### {601}{}{Scorpio}
{601}{}{天蝎座}
### {602}{}{Cannibal}
{602}{}{食人族}
### {603}{}{The King}
{603}{}{国王}
### {604}{}{Caesar}
{604}{}{凯撒}
### {605}{}{Hidalgo}
{605}{}{伊达尔戈}
### {606}{}{Sergeant}
{606}{}{中士}
### {607}{}{Fang}
{607}{}{尖牙}
### {608}{}{Sledgehammer}
{608}{}{大锤}
### {609}{}{Dynamite}
{609}{}{炸药}
### {610}{}{Smoker}
{610}{}{吸烟者}
### {611}{}{Hulk}
{611}{}{残骸}
### {612}{}{Sniper}
{612}{}{狙击手}
### {613}{}{Macho}
{613}{}{马乔}
### {614}{}{Mr. X}
{614}{}{X先生}
### {615}{}{Big Brother}
{615}{}{老大哥}
### {616}{}{Mad Dog}
{616}{}{疯狗}
### {617}{}{Rip}
{617}{}{裂开}
### {618}{}{The Ripper}
{618}{}{狙击风月杀手}
### {619}{}{Butcher}
{619}{}{屠夫}
### {620}{}{Leprechaun}
{620}{}{小妖精}
### {621}{}{Whisperer}
{621}{}{耳语者}

#- female
### {650}{}{Black Widow}
{650}{}{黑寡妇}
### {651}{}{Scolopendra}
{651}{}{Scolopendra}
### {652}{}{Brain Eater}
{652}{}{吃脑器}
### {653}{}{The Queen}
{653}{}{女王}
### {654}{}{Cleopatra}
{654}{}{克利奥帕特拉}
### {655}{}{Duchess}
{655}{}{公爵夫人}
### {656}{}{Sergeant}
{656}{}{中士}
### {657}{}{Claws}
{657}{}{爪}
### {658}{}{Machete}
{658}{}{Machete}
### {659}{}{Magnum}
{659}{}{Magnum}
### {660}{}{Napalm}
{660}{}{Napalm}
### {661}{}{Ross}
{661}{}{罗斯}
### {662}{}{Marine}
{662}{}{海的}
### {663}{}{Muchacho}
{663}{}{穆查乔}
### {664}{}{Mrs. X}
{664}{}{X女士}
### {665}{}{Big Mama}
{665}{}{大妈妈}
### {666}{}{Crazy Bitch}
{666}{}{疯狂的婊子}
### {667}{}{Bad Girl}
{667}{}{坏女孩}
### {668}{}{Angel}
{668}{}{天使}
### {669}{}{Wild Jane}
{669}{}{狂野的简}
### {670}{}{Snow White}
{670}{}{白雪公主}
### {671}{}{Ruby}
{671}{}{红宝石}

#---------------------------------------------
# Cartography
#---------------------------------------------

### {1400}{}{A new place has been opened on the world map}
{1400}{}{世界地图上开辟了一个新的地方}
### {1401}{}{: }
{1401}{}{：}
### {1402}{}{.}
{1402}{}{。}
### {1403}{}{ Suspicious sounds are coming from the cave.}
{1403}{}{可疑的声音从山洞里传来。}

#Attention! The list should be copied unchanged from the file .../game/MAP.MSG
### {1500}{}{Villa}
{1500}{}{别墅}
### {1501}{}{Flagstaff}
{1501}{}{Flagstaff}
### {1502}{}{Garage City}
{1502}{}{车库城}
### {1503}{}{San Brahmin}
{1503}{}{San Brahmin}
### {1504}{}{Two-Sun}
{1504}{}{两个太阳}
### {1505}{}{Puerto}
{1505}{}{Puerto}
### {1506}{}{Rangers}
{1506}{}{Rangers}
### {1507}{}{Phoenix}
{1507}{}{凤凰}
### {1508}{}{Platform}
{1508}{}{站台}
### {1509}{}{Casa Grande}
{1509}{}{格兰德之家}
### {1510}{}{Hermosillo}
{1510}{}{赫莫西洛}
### {1511}{}{San Felipe}
{1511}{}{圣菲利佩}
### {1512}{}{Inferno}
{1512}{}{无法控制的大火}
### {1513}{}{Casa Nueva}
{1513}{}{努瓦之家}
### {1514}{}{-}
{1514}{}{-}
### {1515}{}{The motel}
{1515}{}{汽车旅馆}
### {1516}{}{The Dayglow}
{1516}{}{The Dayglow}
### {1517}{}{-}
{1517}{}{-}
### {1518}{}{Santa Ana}
{1518}{}{圣安娜}
### {1519}{}{-}
{1519}{}{-}
### {1520}{}{Jackals}
{1520}{}{千斤顶}
### {1521}{}{Pit stop}
{1521}{}{进站}
### {1522}{}{Villa}
{1522}{}{别墅}
### {1523}{}{Vault 27}
{1523}{}{27号避难所}
### {1524}{}{Brotherhood Camp}
{1524}{}{兄弟会营地}
### {1525}{}{Raiders}
{1525}{}{突袭者}
### {1526}{}{Wasteland}
{1526}{}{荒地}
### {1527}{}{Mountainous terrain}
{1527}{}{山地地形}
### {1528}{}{Ruins}
{1528}{}{废墟}
### {1529}{}{The coast}
{1529}{}{海岸}
### {1530}{}{Puerto}
{1530}{}{Puerto}
### {1531}{}{Gold!}
{1531}{}{金}
### {1532}{}{Henry Beamis}
{1532}{}{亨利·比米斯}
### {1533}{}{Roadside cafe}
{1533}{}{路边咖啡馆}
### {1534}{}{Bomber}
{1534}{}{轰炸机}
### {1535}{}{Petro-Chico truck}
{1535}{}{Petro Chico卡车}
### {1536}{}{The cry of silence}
{1536}{}{沉默的呐喊}
### {1537}{}{Outdoor cinema}
{1537}{}{户外影院}
### {1538}{}{Padre}
{1538}{}{Padre}
### {1539}{}{Baron of Arizona}
{1539}{}{亚利桑那男爵}
### {1540}{}{Snowfall}
{1540}{}{降雪}
### {1541}{}{The Lost Refuge}
{1541}{}{失落的避难所}
### {1542}{}{Mobile Fortress}
{1542}{}{移动堡垒}
### {1543}{}{Legend City}
{1543}{}{传奇城市}
### {1544}{}{-}
{1544}{}{-}
### {1545}{}{-}
{1545}{}{-}
### {1546}{}{Quartzsite}
{1546}{}{石英岩}
### {1547}{}{A chance meeting}
{1547}{}{偶遇}
### {1548}{}{Winon Camp}
{1548}{}{Winon营地}
