### {100}{}{It's a computer.}
{100}{}{这是一台电脑。}
### {101}{}{Here is an ancient computer. It's amazing that it still works.}
{101}{}{这是一台古老的电脑。令人惊讶的是它仍然有效。}

#Dialog
### {200}{}{The system is loaded.}
{200}{}{系统已加载。}
### {201}{}{End session.}
{201}{}{结束会话。}
### {202}{}{Back.}
{202}{}{返回}
### {203}{}{Welcome to the electronic file of the Mexicali Police Department.}
{203}{}{欢迎访问墨西卡利警察局的电子档案。}
### {204}{}{The database is being loaded...}
{204}{}{正在加载数据库。。。}

### {210}{}{Supermarket attack.}
{210}{}{超市袭击。}
### {211}{}{"...You've known him for a long time. What do you think caused such an act?"}
{211}{}{“……你认识他很长时间了。你认为是什么导致了这样的行为？”}
### {212}{}{Next.}
{212}{}{下一个}
### {213}{}{"What's there to tell? He's a war veteran. You know, all this horror at Anchorage. And although he was awarded for excellent service, but the injury in his head remained."}
{213}{}{“有什么好说的？他是一名退伍军人。你知道，在安克雷奇发生的所有恐怖事件。尽管他因出色的服务而获奖，但他的头部仍然受伤。”}
### {214}{}{Next.}
{214}{}{下一个}
### {215}{}{"In the head? Was he injured?"}
{215}{}{“头部？他受伤了吗？”}
### {216}{}{Further.}
{216}{}{进一步的}
### {217}{}{"No, he's gone mad! It was for you that he took a machine gun and shot people in a supermarket. And for him it is a continuation of the war. He thought he was shooting at the Reds..."}
{217}{}{“不，他疯了！是为了你，他拿着机关枪在超市里开枪。对他来说，这是战争的延续。他以为自己在向红军开枪……”}
### {218}{}{Stop recording.}
{218}{}{停止录制。}

### {220}{}{Complaints about construction work.}
{220}{}{对建筑工程的投诉。}
### {221}{}{"...I'm telling you - my plan is fully coordinated! Everything is according to the law! And how will the neighbors prove that I got into their bowels when mining the soil?"}
{221}{}{“……我告诉你，我的计划是完全协调的！一切都是依法进行的！邻居们如何证明我在挖掘土壤时钻进了他们的肚子？”}
### {222}{}{Next.}
{222}{}{下一个}
### {223}{}{"Suppose. But what about the vibrations from the construction work that prevent them from resting? As well as dust, broken windows and endless trucks? They also say that you use the labor of hired workers without a license."}
{223}{}{“假设一下。但是，建筑工程产生的振动阻止了他们休息呢？还有灰尘、破碎的窗户和无尽的卡车？他们还说，你在没有执照的情况下使用雇佣工人的劳动力。”}
### {224}{}{Next.}
{224}{}{下一个}
### {225}{}{"This is an expensive project... Ar-rh, yes, you understand! When the world war begins, and it will definitely begin, no one will care about vibrations and trucks! I'm building a bomb Vault to save myself and my family. And what will the neighbors do? Oh, they'll run to me to ask for Vault. You'll see, Officer. You'll see..."}
{225}{}{“这是一个昂贵的项目…啊，是的，你明白！当世界大战开始，而且肯定会开始的时候，没有人会关心震动和卡车！我正在建造一个炸弹库来拯救我自己和我的家人。邻居们会怎么做？哦，他们会跑来找我要保险库的。你会看到的，警官。你会知道的…”}
### {226}{}{Stop recording.}
{226}{}{停止录制。}

### {230}{}{Accusation of racism.}
{230}{}{对种族主义的指责。}
### {231}{}{"...Ma'am, please calm down..."}
{231}{}{“…女士，请冷静……”}
### {232}{}{Next.}
{232}{}{下一个}
### {233}{}{"Calm down? These barbarians want me dead! The neighbors have been trying to drive me out of town for a long time. I've been putting up with their antics for years. But they have already crossed all the boundaries! I pay dearly for the house and will not allow anyone to accuse me of having ties with the Reds just because I have Chinese blood in me. Do something, you're the police!"}
{233}{}{“冷静点？这些野蛮人想让我死！邻居们想把我赶出城里已经很久了。我多年来一直忍受他们的滑稽行为。但他们已经越界了！我为房子付出了高昂的代价，不会允许任何人仅仅因为我身上有中国血统就指责我与红军有联系。做点什么，你就是警察！”}
### {234}{}{Next.}
{234}{}{下一个}
### {235}{}{"Of course, ma'am... uh, we don't tolerate racism either... But understand - your evidence is not enough to accuse the neighbors. A dead cat, notes on the walls and anonymous notes - all this does not indicate a real threat. We are not smo..."}
{235}{}{“当然，女士……嗯，我们也不容忍种族主义……但要明白，你的证据不足以指控邻居。一只死猫、墙上的纸条和匿名纸条——所有这些都不意味着真正的威胁。我们不是smo…”}
### {236}{}{Next.}
{236}{}{下一个}
### {237}{}{"Why am I wasting my time here with you! And so it is clear - you are all racists here! Racists! Give me my application, I'm leaving..."}
{237}{}{“我为什么在这里浪费时间和你们在一起！很明显，你们都是种族主义者！种族主义者。给我申请表，我要走了……”}
### {238}{}{Next.}
{238}{}{下一个}
### {239}{}{"Ugh... What a bitch. This is the third one in a month. Do you think, Rodrigo, is she really one of "these"?"}
{239}{}{“啊…真是个婊子。这是一个月内的第三次了。罗德里戈，你觉得她真的是“这些”中的一员吗？”}
### {240}{}{Next.}
{240}{}{下一个}
### {241}{}{"Let him go, Nick. It is better to let the neighbors push her to the limit than suddenly she will find herself in ties with the Reds... Oh, shit, I didn't turn off the recorder..."}
{241}{}{“放开他，尼克。与其突然发现自己与红军有联系，不如让邻居把她逼到极限……哦，该死，我没有关掉录音机……”}
### {242}{}{Stop recording.}
{242}{}{停止录制。}

### {250}{}{The case of the cactus.}
{250}{}{仙人掌的案例。}
### {251}{}{"So, guys. Tell us how it really happened."}
{251}{}{“所以，伙计们。告诉我们事情是怎么发生的。”}
### {252}{}{Next.}
{252}{}{下一个}
### {253}{}{"Well, we were just walking in the desert and sat down near a cactus. And then this thing fell on Paco! We didn't do anything wrong, honestly, se?or!"}
{253}{}{“嗯，我们只是在沙漠中行走，在一棵仙人掌附近坐了下来。然后这东西掉在了帕科身上！老实说，我们没有做错任何事，塞诺！”}
### {254}{}{Next.}
{254}{}{下一个}
### {255}{}{"Yeah. Then how do you explain the charred laser marks on the stump of the cactus? [silence] Guys, I don't want to put pressure on you. I want to help. Tell me the truth, and you'll only get off with a warning. [silence] All right. Let me help you remember."}
{255}{}{“是的。那你怎么解释仙人掌残端烧焦的激光痕迹呢？（沉默）伙计们，我不想给你们施加压力。我想帮忙。告诉我真相，你们只会得到警告。（沉默）好吧。让我帮你们记住。”}
### {256}{}{Next.}
{256}{}{下一个}
### {257}{}{"Paco took his father's laser pistol without permission, after which you decided to test it on a cactus. Is that how it was? [silence] But the cactus turned out to be stronger, and the charge ended too quickly, and you decided to finish off the cactus manually? [silence] Guys, you know that shooting at cacti is prohibited in the state. Not to mention the use of weapons..."}
{257}{}{“帕科在未经允许的情况下拿走了他父亲的激光手枪，之后你决定在仙人掌上测试。事情就是这样吗？[沉默]但仙人掌变得更强壮了，冲锋结束得太快了，你决定手动干掉仙人掌？[沉默]伙计们，你们知道在这个州禁止向仙人掌射击。更不用说使用武器了…”}
### {258}{}{Next.}
{258}{}{下一个}
### {259}{}{"se?or! se?or! Just don't tell your parents!"}
{259}{}{“塞诺！塞诺！就是不要告诉你父母！”}
### {260}{}{Stop recording.}
{260}{}{停止录制。}

### {270}{}{The case of the robot.}
{270}{}{机器人的情况。}
### {271}{}{"...So you're saying that the robot had no defects, and it acted independently?"}
{271}{}{“……所以你是说机器人没有缺陷，而且它是独立行动的？”}
### {272}{}{Next.}
{272}{}{下一个}
### {273}{}{"I'm afraid it doesn't sound quite right in this form, se?or Officer... The robot of the "Mr. Assistant" series only performs the assigned tasks. But look at the requests of the Wilson family! I think they had... some relationship problems."}
{273}{}{“恐怕这种形式听起来不太正确，塞诺警官……”。“助理”系列只执行指定的任务。但看看威尔逊一家的要求！我认为他们有……一些关系问题}
### {274}{}{Next.}
{274}{}{下一个}
### {275}{}{"Relationship problems? Yes, we know that there were regular quarrels in their family. But how could this affect a robot that "only performs the assigned tasks"?"}
{275}{}{“关系问题？是的，我们知道他们家经常吵架。但这怎么会影响一个“只执行指定任务”的机器人呢？”}
### {276}{}{Next.}
{276}{}{下一个}
### {277}{}{"Well... The robot interpreter is not perfect. And when the Wilsons' mother threatens to "cook a chop" out of her son, and the son asks the robot to "kill the parents," then something here could be misunderstood..."}
{277}{}{“嗯……机器人翻译并不完美。当威尔逊夫妇的母亲威胁要给儿子“做一份排骨”，而儿子要求机器人“杀死父母”时，这里的一些事情可能会被误解……”}
### {278}{}{Next.}
{278}{}{下一个}
### {279}{}{"So. Do you understand what you're saying? Your service center serves robots that are banned from harming people in the program. And now these robots, you see, have "misunderstood" something there. Stop misleading the investigation! Admit the defect and we will reduce the penalty!"}
{279}{}{“那么。你明白你在说什么吗？你的服务中心为那些被禁止在程序中伤害他人的机器人提供服务。现在，你看，这些机器人“误解”了其中的一些东西。不要误导调查！承认缺陷，我们会减少处罚！”}
### {280}{}{Stop recording.}
{280}{}{停止录制。}

### {290}{}{Anti-American protest.}
{290}{}{反美抗议。}
### {291}{}{"So do you admit your guilt in participating in an illegal rally aimed at overthrowing the current government?"}
{291}{}{“那么，你承认参加旨在推翻现政府的非法集会有罪吗？”}
### {292}{}{Next.}
{292}{}{下一个}
### {293}{}{"Guilt? Well, no! These Americans have enslaved all of Sonora! They are the criminals! They and our corrupt government! How can you call the rally illegal?..."}
{293}{}{“有罪吗？不！这些美国人奴役了整个索诺拉！他们是罪犯！他们和我们腐败的政府！你怎么能说集会是非法的？…”}
### {294}{}{Next.}
{294}{}{下一个}
### {295}{}{"So. I will repeat my question again..."}
{295}{}{“那么，我再重复一遍我的问题……”}
### {296}{}{Next.}
{296}{}{下一个}
### {297}{}{"Mexico to Mexicans! Mexico to Mexicans!"}
{297}{}{“墨西哥对墨西哥人！墨西哥对墨西哥人”}
### {298}{}{Next.}
{298}{}{下一个}
### {299}{}{"Stop it! Silence! Everyone be silent!"}
{299}{}{“住手！安静！大家安静！”}
### {300}{}{Next.}
{300}{}{下一个}
### {301}{}{"Or are you going to put us in jail?" - "We demand a lawyer!" - "Are you happy with your salary?" - "While Madera was in power, the Americans did not climb to us..." - "Have you already forgotten that massacre on the border?" - "Mexico to Mexicans!"}
{301}{}{“或者你要把我们关进监狱？”-“我们需要律师！”-“你对你的薪水满意吗？”-《马德拉掌权时，美国人没有爬到我们身边……》-“你已经忘记了边境上的大屠杀了吗？”——“墨西哥对墨西哥人！”}
### {302}{}{Stop recording.}
{302}{}{停止录制。}
