### {100}{}{Here is a migrant from Phoenix.}
{100}{}{这是一位来自凤凰城的移民。}
### {101}{}{You see a man in dusty clothes. His hands are soiled in mud.}
{101}{}{你看到一个男人穿着满是灰尘的衣服。他的手被泥弄脏了。}
### {102}{}{Hello}
{102}{}{你好}

### {200}{}{What a surprise. We knew that sometimes travelers pass here. But we didn't expect to meet a new face so soon.}
{200}{}{真是个惊喜。我们知道有时旅行者会经过这里。但我们没想到这么快就会遇到新面孔。}
### {201}{}{Have you been here recently?}
{201}{}{你最近来过这里吗？}
### {202}{}{Yes, just checked in. If you're looking for an overnight stay, then I'm sorry - we don't have enough space, all the rooms are occupied.}
{202}{}{是的，刚刚办理了入住手续。如果你想过夜，那么我很抱歉，我们没有足够的空间，所有的房间都被占用了。}
### {203}{}{No, I just want to talk.}
{203}{}{不，我只是想谈谈。}
### {204}{}{Overnight at this motel? Well, no. I'd rather spend the night in the desert under the open sky.}
{204}{}{在这家汽车旅馆过夜？不，我宁愿在开阔的天空下的沙漠里过夜。}
### {205}{}{Yes, just checked in. If you're looking for an overnight stay, then I'm sorry - there are no available rooms. But I don't mind exchanging a few words with a rare traveler.}
{205}{}{是的，刚刚办理了入住手续。如果你想过夜，很抱歉，没有空房间了。但我不介意和一个难得的旅行者说几句话。}

### {210}{}{There are no empty seats. But I don't mind exchanging a few words with a rare traveler.}
{210}{}{没有空座位。但我不介意和一个难得的旅行者说几句话。}
### {211}{}{Where did you come from?}
{211}{}{你从哪里来的？}
### {212}{}{We are immigrants from Phoenix. We are here to found a new community. Aaron himself gave us a deed of sale for this land.}
{212}{}{我们是来自凤凰城的移民。我们来这里是为了建立一个新的社区。亚伦亲自给了我们一份这片土地的买卖契约。}
### {213}{}{And for what such merits?}
{213}{}{这样的优点是什么？}
### {214}{}{For work in the glory of His ideas. Besides, it was easy, because Aaron is interested in colonizing the neighborhood under his banners.}
{214}{}{为了在他思想的光辉中工作。此外，这很容易，因为亚伦有兴趣在他的旗帜下殖民这个社区。}
### {215}{}{Well, well. What can you prove?}
{215}{}{嗯，嗯。你能证明什么？}
### {216}{}{We have a bill of sale. We got it for working for the glory of Aaron's ideas. But what do you have to put forward your doubts?}
{216}{}{我们有一张卖据。我们得到它是因为为亚伦的想法而努力。但是，你有什么可以提出你的疑虑呢？}
### {217}{}{And how did he have the right to this motel?}
{217}{}{他是怎么有权去这家汽车旅馆的？}
### {218}{}{Only Aaron can dispose of the lands around Phoenix. And try to say that it is not so.}
{218}{}{只有亚伦才能处置凤凰城周围的土地。试着说事实并非如此。}
### {219}{}{It's not like that.}
{219}{}{事实并非如此。}
### {220}{}{How dare you defile the name of a holy man? Keep your fucking mouth shut before I lose my temper. Away! Pro-och!}
{220}{}{你怎么敢玷污一个圣人的名字？在我发脾气之前，闭上你他妈的嘴。离开亲啊！}
### {221}{}{Okay, okay...}
{221}{}{好吧，好吧...}
### {222}{}{Hey, take it easy...}
{222}{}{嘿，别紧张...}
### {223}{}{He's doing a great job.}
{223}{}{他做得很好。}
### {224}{}{May the name of Aaron be glorified! A man who gives life to the desert.}
{224}{}{愿亚伦的名得荣耀！一个给沙漠赋予生命的人。}
### {225}{}{Aaron is killed. Do you know about it?}
{225}{}{亚伦被杀了。你知道吗？}
### {226}{}{Aaron and his cathedral are destroyed. Do you know about it?}
{226}{}{亚伦和他的大教堂被毁了。你知道吗？}
### {227}{}{How dare you talk about such a thing? Of course, Aaron is alive, and his cathedral stands where it stood. Cover your vile mouth before I lose my temper.}
{227}{}{你怎么敢谈论这样的事？当然，亚伦还活着，他的大教堂就矗立在那里。在我发脾气之前捂住你那卑鄙的嘴。}
### {228}{}{The truth is always offended.}
{228}{}{真相总是被冒犯。}
### {229}{}{Hey, take it easy...}
{229}{}{嘿，别紧张...}

### {230}{}{Do you know that mutants used to live here?}
{230}{}{你知道变种人以前住在这里吗？}
### {231}{}{What was, was. We need to start anew, and not mess around in the past.}
{231}{}{过去是什么。我们需要重新开始，不要在过去胡搅蛮缠。}
### {232}{}{And are you ready to settle here, knowing about the horrors that were happening in the walls of the motel?}
{232}{}{知道汽车旅馆墙上发生的恐怖事件，你准备好在这里定居了吗？}
### {233}{}{Although these mutants were cannibals and sadists, they were watching the motel at the same time. That's why we stopped here. Because this is the only place suitable for living in the district!}
{233}{}{尽管这些变种人是食人族和虐待狂，但他们同时在监视汽车旅馆。这就是我们停在这里的原因。因为这是该地区唯一适合居住的地方！}
### {234}{}{Did the mutants try?}
{234}{}{变种人试过了吗？}
### {235}{}{They repaired the roof and fence, fertilized the beds, put up desert water storage - this is a great place to start anew.}
{235}{}{他们修复了屋顶和围栏，给河床施肥，建立了沙漠蓄水库——这是一个重新开始的好地方。}
### {236}{}{That is, you have come to everything ready.}
{236}{}{也就是说，你已经做好了一切准备。}
### {237}{}{I think it's time for you to go.}
{237}{}{我想你该走了。}
### {238}{}{Yes, I have to go. Goodbye.}
{238}{}{是的，我得走了。再见}
### {239}{}{That was rude of you. Now I definitely don't want to linger here.}
{239}{}{你太粗鲁了。现在我绝对不想在这里逗留。}
### {240}{}{We can be happy for you. At least this cursed place will bring some benefit.}
{240}{}{我们可以为你高兴。至少这个被诅咒的地方会带来一些好处。}
### {241}{}{Now everything will be different. Aaron gave us and the motel a second chance. I promise - we will make the promised land out of this desert.}
{241}{}{现在一切都不一样了。亚伦给了我们和汽车旅馆第二次机会。我保证，我们将在这片沙漠中开辟出应许之地。}
### {242}{}{Amen.}
{242}{}{阿门。}
### {243}{}{Good luck.}
{243}{}{祝你好运}
