### {100}{}{Before you is a warrior of the road.}
{100}{}{在你成为道路上的战士之前。}
### {101}{}{This is one of the highway robbers.}
{101}{}{这是一个高速公路劫匪。}
### {102}{}{The Raider does not want to negotiate.}
{102}{}{突袭者不想谈判。}

### {110}{}{Hey, how's business?}
{110}{}{嘿，生意怎么样？}
### {111}{}{Good luck on the track.}
{111}{}{祝你在赛道上好运。}
### {112}{}{You're cooler than we thought.}
{112}{}{你比我们想象的要酷。}
### {113}{}{I can't believe we're the defenders of the trails now.}
{113}{}{我不敢相信我们现在是防守队员。}
### {114}{}{The tracks are now under our control.}
{114}{}{轨道现在在我们的控制之下。}
### {115}{}{You bring us luck.}
{115}{}{你给我们带来了好运。}
### {116}{}{Ben trusts you.}
{116}{}{本信任你。}

### {120}{}{If you stare at me, I'll arrange a sun-out.}
{120}{}{如果你盯着我看，我会安排太阳出来。}
### {121}{}{What do you need, trash?}
{121}{}{你需要什么，垃圾？}
### {122}{}{*Spits back*}
{122}{}{*向后吐*}
### {123}{}{Although Ben let you in, you're not a gang member yet.}
{123}{}{虽然本让你进来了，但你还不是帮派成员。}
### {124}{}{I am bored. Entertain me.}
{124}{}{我很无聊。娱乐我。}
### {125}{}{You're taking a big risk being here.}
{125}{}{你在这里冒着很大的风险。}
### {126}{}{Don't cross our path.}
{126}{}{不要越过我们的路。}

### {130}{}{Who the fuck are you? Are you from the tinsmiths?}
{130}{}{你他妈的是谁？你是铁匠铺的吗？}
### {131}{}{You're it, keep it down there.}
{131}{}{你就是它，把它放在下面。}
### {132}{}{I wish I had armor like yours.}
{132}{}{我希望我有像你一样的盔甲。}

### {199}{}{    }
{199}{}{error : string is empty}
### {200}{}{What are you staring at, cowboy?}
{200}{}{牛仔，你在看什么？}
### {201}{}{At you, bitch.}
{201}{}{对你，婊子。}
### {202}{}{I hate being called that.}
{202}{}{我讨厌别人这样叫我。}
### {203}{}{Well, get used to it, BITCH.}
{203}{}{好吧，习惯吧，婊子。}
### {204}{}{Watch your mouth, you piece of roadside shit, otherwise...}
{204}{}{小心你的嘴，你这路边的屎，否则...}
### {205}{}{Otherwise what? Ooh, will you resist?}
{205}{}{否则怎么办？哦，你会反抗吗？}
### {206}{}{Well, one more word, and...}
{206}{}{好吧，再来一个词，然后...}
### {207}{}{What are you gonna do, baby? I have a palm. The palm I'm going to slap you with...}
{207}{}{你打算怎么办，宝贝？我有一只手掌。我要扇你的手掌...}
### {208}{}{Do you want me, trash?}
{208}{}{你想要我吗，垃圾？}
### {209}{}{You want to, huh?}
{209}{}{你想吗？}
### {210}{}{*Ugh*}
{210}{}{*啊*}
### {211}{}{No, it's fine... Sorry, I got confused...}
{211}{}{不，很好...对不起，我弄糊涂了...}
### {212}{}{Talk to me here.}
{212}{}{在这里和我说话。}
### {213}{}{. . .}
{213}{}{。}
