### {100}{}{Here is Mayor Alvaro.}
{100}{}{这是市长阿尔瓦罗。}
### {101}{}{You see a puny-looking Mexican with a thin mustache and an apologetic look.}
{101}{}{你看到一个身材矮小的墨西哥人，留着稀疏的胡子，带着歉意的表情。}
### {102}{}{Hide it immediately. No weapons while you're in town.}
{102}{}{立即隐藏。你在城里的时候不要带武器。}
### {103}{}{We have a quiet settlement. It's not worth walking around here in this thing and scaring civilians.}
{103}{}{我们有一个安静的解决方案。不值得在这里到处走，吓唬平民。}
### {104}{}{Did something happen? Then get back to bed immediately! There is a curfew in the city at night.}
{104}{}{发生什么事了吗？那就马上回去睡觉！这个城市晚上实行宵禁。}
### {105}{}{They demand solutions from me. What can I do? I was just signing papers for the Brotherhood!}
{105}{}{他们要求我提供解决方案。我该怎么办？我只是在为兄弟会签署文件！}

#First meeting
### {200}{}{Oh, a new face in town! What a pleasant surprise... Greetings to you. I am, one might say, the mayor of this city. And my name is Alvaro.}
{200}{}{哦，城里的新面孔！多么令人愉快的惊喜...问候你。有人可能会说，我是这个城市的市长。我的名字叫阿尔瓦罗。}
### {201}{}{Hello, Mayor.}
{201}{}{你好，市长。}
### {202}{}{Hmm. Don't you want to tell me your name? I won't insist. Surely you have a reason for that.}
{202}{}{嗯，你不想告诉我你的名字吗？我不会坚持的。你肯定有这样的理由。}
### {203}{}{Yes, that's right.}
{203}{}{是的，没错。}
### {204}{}{I }
{204}{}{我}
### {205}{}{. Very nice, senor Alvaro.}
{205}{}{。很好，阿尔瓦罗先生。}
### {206}{}{Good manners? Then you and I will meet.}
{206}{}{礼貌？然后你和我会见面的。}
### {207}{}{Thank you for the warm welcome.}
{207}{}{谢谢你的热情欢迎。}
### {208}{}{What a pathetic sight, Mayor? And this, in your opinion, is a city?}
{208}{}{多么可悲的景象，市长？在你看来，这是一座城市吗？}
### {209}{}{Uh, yes, I realize that it's not as big as Phoenix or its outskirts. And besides the Sonoran desert, I've never seen anything in my life. But look - isn't it beautiful here?}
{209}{}{嗯，是的，我意识到它没有凤凰城或它的郊区那么大。除了索诺兰沙漠，我一生中从未见过任何东西。但是你看，这里不是很美吗？}
### {210}{}{Maybe.}
{210}{}{大概}
### {211}{}{It's just terrible here - there is no civilization.}
{211}{}{这里太可怕了——没有文明。}
### {212}{}{May I know where you're going?}
{212}{}{我可以知道你要去哪里吗？}
### {213}{}{I don't know. I'm going wherever my eyes look.}
{213}{}{我不知道。我要去我眼睛看到的任何地方。}
### {214}{}{Well, okay, I'll take your word for it. It's really none of my business.}
{214}{}{好吧，我相信你的话。这真的不关我的事。}
### {215}{}{Thank you for understanding.}
{215}{}{感谢您的理解。}
### {216}{}{Exactly.}
{216}{}{确切地}
### {217}{}{You can count on an overnight stay in our city. But subject to the rules. You're not going to make trouble for us, are you?}
{217}{}{你可以指望在我们城市过夜。但要遵守规则。你不会给我们制造麻烦的，是吗？}
### {218}{}{Of course. Thanks for the offer.}
{218}{}{当然谢谢你的提议。}
### {219}{}{I don't bite until I'm disturbed. Keep in mind.}
{219}{}{我不被打扰才咬。牢记}
### {220}{}{I serve the Brotherhood of Steel. Here's my badge.}
{220}{}{我为钢铁兄弟会服务。这是我的徽章。}
### {221}{}{Oh, welcome! Did not recognize... er... we are always glad to have our defenders. Make yourself as comfortable as you like.}
{221}{}{哦，欢迎！不认识...呃…我们总是很高兴有我们的后卫。让自己随心所欲地舒服。}
### {222}{}{Thank you.}
{222}{}{非常感谢。}
### {223}{}{That would be right away.}
{223}{}{那就马上。}
### {224}{}{I'm heading to Puerto. I have business there.}
{224}{}{我要去波多黎各。我在那里有生意。}
### {225}{}{What a surprise. Usually only caravans go in that direction without permission. But if you don't want to talk, I can't insist.}
{225}{}{真是个惊喜。通常只有大篷车在未经许可的情况下才朝那个方向行驶。但如果你不想说话，我不能坚持。}
### {226}{}{Thank you for understanding.}
{226}{}{感谢您的理解。}
### {227}{}{That's good. As they say, silence is more expensive than a bag of corn.}
{227}{}{这很好。正如他们所说，沉默比一袋玉米还贵。}
### {228}{}{It's none of your business.}
{228}{}{这不关你的事。}
### {229}{}{Well, let's assume that it's really none of my business. But don't be rude to us, because we are a peaceful settlement.}
{229}{}{好吧，让我们假设这真的不关我的事。但不要对我们无礼，因为我们是和平解决的。}
### {230}{}{Sorry, it was in a hurry - just fatigue from the road...}
{230}{}{对不起，很匆忙——只是路上的疲劳...}
### {231}{}{If you don't want a conflict, don't start it yourself. Got it?}
{231}{}{如果你不想发生冲突，就不要自己动手。明白了吗？}
### {232}{}{I was glad to chat. But I'm sorry, I have a lot of paperwork right now.}
{232}{}{我很高兴聊天。但我很抱歉，我现在有很多文书工作。}
### {233}{}{See you again.}
{233}{}{再见。}
### {234}{}{Do we have the same names? Funny coincidence. Then you and I will surely meet.}
{234}{}{我们有相同的名字吗？有趣的巧合。那你和我一定会见面的。}

### {239}{}{So your town will come to an end. Run away from here before the crowd overthrows you, the mayor is a loser.}
{239}{}{所以你的城市将结束。在人群推翻你之前逃离这里，市长是个失败者。}
### {240}{}{(clutching his head with his hands, the mayor sits at the table and does not pay attention to others) Eh...}
{240}{}{（市长双手抱着头，坐在桌子旁，不理会其他人）呃...}
### {241}{}{You look like shit. Did something happen?}
{241}{}{你看起来像大便。发生什么事了吗？}
### {242}{}{Everything is gone... We used to survive thanks to the Brotherhood of Steel. And recently a messenger came with bad news...}
{242}{}{一切都不见了...多亏了钢铁兄弟会，我们才得以生存。最近一个信使带来了坏消息...}
### {243}{}{Yes, I know - the Brotherhood has been destaroyed. Probably an explosion at the ammunition depot.}
{243}{}{是的，我知道——兄弟会已经被摧毁了。可能是弹药库发生爆炸。}
### {244}{}{What should we do now? Who will protect us? Who will give us instructions?}
{244}{}{我们现在该怎么办？谁来保护我们？谁来给我们指示？}
### {245}{}{What about the Followers?}
{245}{}{追随者们呢？}
### {246}{}{They are not warriors and there are very few of them to solve so many issues. It's hopeless... Everything is gone... it's all gone...}
{246}{}{他们不是战士，他们中很少有人能解决这么多问题。这是无望的...一切都不见了...一切都过去了...}
### {247}{}{Hey, Alvaro, get it together! You're the mayor. Everything is in your hands now. You are free from total control and oppression. Isn't that wonderful?}
{247}{}{嘿，阿尔瓦罗，振作起来！你是市长。现在一切都掌握在你手中。你完全摆脱了控制和压迫。这不是很棒吗？}
### {248}{}{Yes... of course... But what kind of mayor am I? I was just doing paperwork under the supervision of people from the order. Now we have to survive on our own. It won't be easy.}
{248}{}{对当然但我是什么样的市长？我只是在订单人员的监督下做文书工作。现在我们必须靠自己生存。这并不容易。}
### {249}{}{You will succeed. I believe in you.}
{249}{}{你会成功的。我相信你。}

#Repeat meeting
### {250}{}{Sorry, I have a lot of paperwork right now.}
{250}{}{对不起，我现在有很多文书工作。}
### {251}{}{Goodbye.}
{251}{}{再见}
### {252}{}{How can I help, dear friend?}
{252}{}{我能帮你什么，亲爱的朋友？}
### {253}{}{Hello, our new hero. How can I help you?}
{253}{}{你好，我们的新英雄。我能帮你什么？}
### {1253}{}{Hello, our new heroine. How can I help you?}
{1253}{}{你好，我们的新女主角。我能帮你什么？}

### {260}{}{They say people are disappearing from you. Is it true?}
{260}{}{他们说人们正在从你身边消失。这是真的吗？}
### {261}{}{Who's talking?}
{261}{}{谁在说话？}
### {262}{}{I won't say.}
{262}{}{我不会说。}
### {263}{}{Ah, of course, no one disappears from us! Except for some criminals who escaped themselves during the construction of the city.}
{263}{}{啊，当然，没有人会从我们身边消失！除了一些在城市建设过程中逃跑的罪犯。}
### {264}{}{I see.}
{264}{}{我明白了。}
### {265}{}{I really hope that you will not spread these dirty false rumors further.}
{265}{}{我真的希望你不要再散布这些肮脏的谣言了。}
### {266}{}{Sure. No problem.}
{266}{}{当然没问题。}
### {267}{}{Only until it turns out that you're lying. Adios, Mr. Mayor.}
{267}{}{直到事实证明你在撒谎。再见，市长先生。}
### {268}{}{This is Rosalia. She says you forbid looking for her husband.}
{268}{}{这是罗莎莉亚。她说你禁止找她丈夫。}
### {269}{}{What nonsense! I do not forbid the search, let him search. But she can't find it because her hubby just ran away from town. Surely her grumpy nature could not stand it.}
{269}{}{胡说八道！我不禁止搜查，让他搜查吧。但她找不到它，因为她的丈夫刚刚从城里跑了。她脾气暴躁，当然受不了。}
### {270}{}{I see.}
{270}{}{我明白了。}
### {271}{}{Nevermind- the old witch is going crazy.}
{271}{}{永远——老巫婆快疯了。}

### {280}{}{Tell me, please, about the city?}
{280}{}{请告诉我这个城市的情况？}
### {281}{}{We have a peaceful peasant community. Half of the people work on plantations, the resta - various peaceful affairs. There, the Followers even have their own school.}
{281}{}{我们有一个和平的农民社区。一半的人在种植园和餐馆工作——各种和平事务。在那里，信徒们甚至有自己的学校。}
### {282}{}{Thanks for the reply.}
{282}{}{谢谢你的回复。}
### {283}{}{What is grown here?}
{283}{}{这里种什么？}
### {284}{}{These are mainly maize and fire agave. The whole city lives on these plantations.}
{284}{}{这些主要是玉米和火龙舌兰。整个城市都生活在这些种植园里。}
### {285}{}{So do you trade with other cities?}
{285}{}{你和其他城市做贸易吗？}
### {286}{}{The harvesta is enough only for their own needs and for the nearesta settlements. We also have a stable caravan coming from Phoenix for agave juice.}
{286}{}{哈维斯塔人只够满足他们自己的需要和附近的定居点。我们也有一个稳定的商队从凤凰城来的龙舌兰汁。}
### {287}{}{By the way, what settlements are there around?}
{287}{}{顺便问一下，周围有什么定居点？}
### {288}{}{I see.}
{288}{}{我明白了。}
### {289}{}{Puerto in the westa and Tu San in the east. This is all, except for a few small villages and outposts, but they are mostly seasonal.}
{289}{}{西面是波多黎各，东面是屠山。这就是全部，除了一些小村庄和前哨基地，但它们大多是季节性的。}
### {290}{}{Thank you.}
{290}{}{非常感谢。}
### {291}{}{A real oasis in the middle of the desert. How did this become possible?}
{291}{}{沙漠中央的一片真正的绿洲。这是怎么可能的？}
### {292}{}{We thank the Followers of the Apocalypse for their intelligence and kindness. It was they who brought out in their laboratory varieties of plants that can take root in a dry desert.}
{292}{}{我们感谢启示录的追随者们的智慧和善良。正是他们在实验室里培育出了各种可以在干燥沙漠中生根的植物。}
### {293}{}{Do other cities also buy your crops?}
{293}{}{其他城市也买你的庄稼吗？}
### {294}{}{Who are the Followers?}
{294}{}{追随者是谁？}
### {295}{}{By the way, who are these Followers?}
{295}{}{顺便问一下，这些追随者是谁？}
### {296}{}{Followers of the Apocalypse... It's a strange name, but we're already used to it. They conduct scientific research, teach children, treat diseases. Needless to say, the plantation itself appeared in the middle of the desert thanks to their experiments. But it's easier for you to ask the Followers themselves.}
{296}{}{启示录的追随者...这是一个奇怪的名字，但我们已经习惯了。他们进行科学研究，教育孩子，治疗疾病。不用说，由于他们的实验，种植园本身出现在沙漠中央。但你更容易问追随者自己。}
### {297}{}{I know about some other followers - Followers of Fire in Phoenix.}
{297}{}{我知道其他一些追随者-凤凰城的拜火教徒。}
### {298}{}{I heard something about them, but we never crossed paths. Except for the caravans that come from Phoenix.}
{298}{}{我听说了一些关于他们的事情，但我们从未有过交集。除了来自凤凰城的大篷车。}
### {299}{}{By the way, why is alcohol banned here?}
{299}{}{顺便问一下，为什么这里禁止饮酒？}
### {300}{}{Why is alcohol banned here?}
{300}{}{为什么这里禁止饮酒？}
### {301}{}{Formally, only strong alcohol is prohibited. We have too much work to waste time on entertainment. However, after the harvesta, the peasants get a couple of days of complete freedom.}
{301}{}{从形式上讲，只有烈性酒是被禁止的。我们的工作太多了，不能把时间浪费在娱乐上。然而，在收获之后，农民们获得了几天的完全自由。}
### {302}{}{Curiously, there are no guards here. Are you not afraid of slavers or bandits?}
{302}{}{奇怪的是，这里没有警卫。你不怕奴隶贩子或土匪吗？}
### {303}{}{About the "peaceful community". Are you not afraid of slavers or bandits?}
{303}{}{关于“和平社区”。你不怕奴隶贩子或土匪吗？}
### {304}{}{Why should we be afraid of them? Our patrons keep order in these lands. We are peaceful people and do only peaceful things. We are not even allowed to have weapons. Therefore, there is nothing to be afraid of here.}
{304}{}{我们为什么要害怕他们？我们的赞助人在这些土地上维持秩序。我们是和平的人民，只做和平的事情。我们甚至不允许拥有武器。因此，这里没有什么可害怕的。}
### {305}{}{Yes, you have a real oasis here. How did this become possible?}
{305}{}{是的，你在这里有一片真正的绿洲。这是怎么可能的？}
### {306}{}{Patrons? Who is it?}
{306}{}{赞助人？是谁？}
### {307}{}{What, you don't know about the military base in Puerto? Then I shouldn't discuss it with you. Just know that there is someone to stand up for us.}
{307}{}{什么，你不知道在波多黎各的军事基地？那我就不该和你讨论了。只要知道有人为我们挺身而出。}
### {308}{}{You know who we're talking about-the Brotherhood of Steel. They are now the owners of these lands.}
{308}{}{你知道我们说的是谁钢铁兄弟会。他们现在是这些土地的所有者。}

### {310}{}{How do you feel about the Brotherhood of Steel?}
{310}{}{你觉得钢铁兄弟会怎么样？}
### {311}{}{They are our patrons. We wouldn't have survived without them.}
{311}{}{他们是我们的赞助人。如果没有他们，我们就活不下去了。}
### {312}{}{I see.}
{312}{}{我明白了。}
### {313}{}{And to be honesta?}
{313}{}{做一个诚实的人？}
### {314}{}{This is the honesta answer.}
{314}{}{这是honesta的答案。}
### {315}{}{That's good.}
{315}{}{这很好。}
### {316}{}{So be it - I'll believe it.}
{316}{}{那就这样吧——我会相信的。}
### {317}{}{I do not hear joy and admiration in your words.}
{317}{}{我听不到你言语中的喜悦和钦佩。}
### {318}{}{I can talk to you frankly, right? We try not to talk about it, but everyone here lives by and large on the rights of peons. That is, lifelong slaves. After all, in order to obtain protection and a place of residence, you need to pay unaffordable taxes.}
{318}{}{我可以坦率地和你谈谈，对吧？我们尽量不谈论它，但这里的每个人基本上都以人民的权利为生。也就是说，终身奴隶。毕竟，为了获得保护和住所，你需要支付负担不起的税款。}
### {319}{}{So, go on...}
{319}{}{所以，继续...}
### {320}{}{Due to the lack of so many funds, residents conclude a peonage contract, in fact, renting themselves out for the resta of their lives.}
{320}{}{由于缺乏这么多资金，居民们签订了一份雇佣合同，事实上，他们把自己租出去过自己的生活。}
### {321}{}{It's sad to hear that.}
{321}{}{听到这个消息很难过。}
### {322}{}{Which was required to be proved.}
{322}{}{这是需要证明的。}
### {323}{}{But it's not that bad. We are given free rein in everything that does not contradict the laws and interestas of the Brotherhood of Steel. And we really get reliable protection and help. After all, the Brotherhood needs products and a trade route. And without us, none of this will happen.}
{323}{}{但也没那么糟糕。我们可以自由支配一切不违背钢铁兄弟会法律和利益的事情。我们确实得到了可靠的保护和帮助。毕竟，兄弟会需要产品和贸易路线。没有我们，这一切都不会发生。}
### {324}{}{And are you ready to put up with this situation?}
{324}{}{你准备好忍受这种情况了吗？}
### {325}{}{We have no choice! It is thanks to the Brotherhood and the tinsmiths that we have built such a beautiful city and grown such a harvesta. Without them, we would have dragged out a miserable life of scavengers in the desert.}
{325}{}{我们别无选择！正是由于兄弟会和锡匠们，我们建造了这样一座美丽的城市，种植了这样一个哈维斯塔。如果没有它们，我们将在沙漠中度过拾荒者的悲惨生活。}
### {326}{}{And it's true - difficult conditions. I don't know what I would have to choose in such a situation.}
{326}{}{这是真的——困难的条件。我不知道在这种情况下我会选择什么。}
### {327}{}{It's hard for me to understand how freedom can be exchanged for a life in a stall. You clearly made a mistake. Goodbye.}
{327}{}{我很难理解自由是如何换取地摊上的生活的。你显然犯了一个错误。再见}
### {328}{}{I know your secret about the infection and its silencing. And also - pressure on residents and continuous bans. Isn't it your tyranny if the Brotherhood has nothing to do with it?}
{328}{}{我知道你关于感染和沉默的秘密。还有对居民的压力和持续的禁令。如果兄弟会与之无关，那不是你的暴政吗？}
### {329}{}{If you can't become a death claw, pretend to be a blind pig-rat. Is that what you mean, weakling?}
{329}{}{如果你不能成为一只死亡之爪，就假装成一只失明的猪老鼠。这就是你的意思吗，胆小鬼？}

### {330}{}{Do you know that your son's pet is dying?}
{330}{}{你知道你儿子的宠物快死了吗？}
### {331}{}{Yes... This pig-rat has already bored me with his whining and night fuss. I told Chip not to keep the beast in the house, but he won't listen to me. Now we have to put up with and fend off the attacks of neighbors.}
{331}{}{对这只猪老鼠已经让我厌烦了它的哀嚎和夜间的大惊小怪。我告诉奇普不要把野兽留在家里，但他不听我的。现在我们必须忍受并抵御邻居的攻击。}
### {332}{}{What did Pinkie do to all of you?}
{332}{}{平基对你们做了什么？}
### {333}{}{Well.. uh, to be honesta, nothing in particular, except for the night noises. He scares just by his appearance. And that's enough. If he had been useful, perhaps the attitude towards Pinkie would have changed.}
{333}{}{好呃，老实说，没有什么特别的，除了夜间的噪音。他光看外表就害怕。这就足够了。如果他有用的话，也许人们对平基的态度会改变。}
### {334}{}{An interestaing observation.}
{334}{}{令人感兴趣的观察。}

### {340}{}{In the settlement of Santa Ana, they want to start trading with you.}
{340}{}{在圣安娜的定居点，他们想开始与你交易。}
### {341}{}{Santa Ana? I haven't heard of this village for many years. Its inhabitants avoided all contact with us. What has changed there?}
{341}{}{圣安娜？我已经很多年没听说过这个村庄了。它的居民避免与我们接触。那里发生了什么变化？}
### {342}{}{Well, let's just say that the government has changed there.}
{342}{}{好吧，就说政府已经改变了。}
### {343}{}{Oh, that sounds intriguing. I'll prepare the caravan. Perhaps we will recruit new workers among the residents of Santa Ana, which are sometimes so lacking. Thank you for the message.}
{343}{}{哦，听起来很有趣。我会准备商队的。也许我们会在圣安娜的居民中招募新的工人，而圣安娜有时非常缺乏。谢谢你的留言。}
### {344}{}{Please.}
{344}{}{请}
