### {100}{}{This is Arthur Carrington.}
{100}{}{我是阿瑟·卡林顿。}
### {101}{}{You see the same archaeologist from Vault 27.}
{101}{}{你看到的是27号避难所的同一位考古学家。}

#The first dialog
### {200}{}{Glad to see you again, hero.}
{200}{}{很高兴再次见到你，英雄。}
### {1200}{}{Glad to see you again, heroine.}
{1200}{}{很高兴再次见到你，女英雄。}
### {201}{}{I see you've already settled into your new place. Can you give me a minute?}
{201}{}{我看你已经安顿好了。你能给我一分钟时间吗？}
### {202}{}{Yes?}
{202}{}{对}
### {203}{}{Bye.}
{203}{}{再见}
### {204}{}{Another question.}
{204}{}{另一个问题。}

### {220}{}{What are you doing here?}
{220}{}{你在这里干什么？}
### {221}{}{I am offered to teach children to read and write. It's an unusual experience. But it's better than messing around on a plantation. I am not allowed to do more serious research yet. And it's annoying, because I used to manage several serious projects.}
{221}{}{我被邀请教孩子们读写。这是一次不同寻常的经历。但这总比在种植园里乱搞要好。我还没有被允许做更严肃的研究。这很烦人，因为我曾经管理过几个严肃的项目。}
### {222}{}{I think you'll get along with time. In the meantime, relax.}
{222}{}{我想你会慢慢来的。在此期间，请放松。}
### {223}{}{What do you think about Followers?}
{223}{}{你觉得追随者怎么样？}
### {224}{}{At first I was fascinated by their thirst for knowledge. But their kindness is shocking. It is impossible to help everyone so indiscriminately and share knowledge. Many simply do not deserve it. And if they deserve it, then because of stupidity they are not able to properly dispose of the received good.}
{224}{}{起初，我被他们对知识的渴望所吸引。但他们的善良令人震惊。不可能如此不分青红皂白地帮助每个人并分享知识。许多人根本不配得到它。如果他们应得，那么由于愚蠢，他们无法妥善处理收到的货物。}
### {225}{}{You have different views on the same thing. This is normal.}
{225}{}{你对同一件事有不同的看法。这很正常。}
