### {100}{}{Here is Ralph.}
{100}{}{这是拉尔夫。}
### {101}{}{You see a man with burnt skin. He is wearing well-worn work clothes with a pre-war symbol.}
{101}{}{你看到一个皮肤烧焦的人。他穿着带有战前标志的破旧工作服。}
### {102}{}{I have nothing to do with traitors.}
{102}{}{我与叛徒没有任何关系。}
### {103}{}{Thanks for the help. She was very helpful.}
{103}{}{谢谢你的帮助。她很乐于助人。}

### {200}{}{Wait, strangers can't go any further. What do you need?}
{200}{}{等等，陌生人不能再往前走了。你需要什么？}
### {201}{}{I thought this place had been abandoned for a long time. What are you doing here?}
{201}{}{我以为这个地方已经废弃很长时间了。你在这里干什么？}
### {202}{}{We have been living here for many years. But the whole city knows about it. So I don't advise you to lie anymore.}
{202}{}{我们已经在这里住了很多年了。但整个城市都知道这件事。所以我不建议你再撒谎了。}
### {203}{}{But I'm not a local. I'm from a village northeast of here.}
{203}{}{但我不是本地人。我来自这里东北部的一个村庄。}
### {1203}{}{But I'm not local. I'm from a village northeast of here.}
{1203}{}{但我不是本地人。我来自这里东北部的一个村庄。}
### {204}{}{Oh, that's a surprise. You really don't look like an ordinary citizen - your skin is tanned, your accent is unusual. Curious...}
{204}{}{哦，真是个惊喜。你看起来真的不像一个普通公民——你的皮肤晒黑了，你的口音不同寻常。好奇的}
### {1204}{}{Oh, this is a surprise. You really don't look like an ordinary citizen - your skin is tanned, your accent is unusual. Curious...}
{1204}{}{哦，这真是个惊喜。你看起来真的不像一个普通公民——你的皮肤晒黑了，你的口音不同寻常。好奇的}
### {205}{}{Hmm. Let me just leave.}
{205}{}{嗯，让我走吧。}
### {206}{}{Why is that?}
{206}{}{为什么？}
### {207}{}{Okay, listen, we have an emergency here. Maybe you can help. Go to the manager, and then - as you agree.}
{207}{}{好吧，听着，我们这里有紧急情况。也许你可以帮忙。去找经理，然后——正如你所同意的那样。}
### {208}{}{OK.}
{208}{}{好啊}

### {210}{}{Wait, what... Is that makeup?}
{210}{}{等等，什么...那是化妆品吗？}
### {211}{}{This is real leather. A little green, but you can live.}
{211}{}{这是真皮的。有点绿，但你可以活着。}
### {212}{}{With such jokes, you are seriously risking.}
{212}{}{开这样的玩笑，你是在冒很大的风险。}
### {213}{}{But I'm telling the truth. It's all because of the experiments in Inferno. They are real madmen.}
{213}{}{但我说的是实话。这都是因为在地狱的实验。他们真是疯子。}
### {214}{}{Damn it, but it's true. I don't remember what I looked like before the Transformation. It must have been hard for you. Glad to meet you.}
{214}{}{该死，但这是真的。我不记得转型前的样子了。这对你来说一定很难。很高兴认识你。}
### {215}{}{Oh, so I'm welcome here now? Well, of course.}
{215}{}{哦，那么我现在不受欢迎了？当然。}
### {216}{}{Mutually. So you live here?}
{216}{}{相互地所以你住在这里？}
### {217}{}{I haven't introduced myself yet. My name is Ralph. I am, one might say, Theodore's right-hand man. Sorry for the cold reception, but we haven't been in the mood for pleasantries lately.}
{217}{}{我还没有自我介绍。我的名字叫拉尔夫。有人可能会说，我是西奥多的得力助手。很抱歉受到冷遇，但我们最近没有心情开玩笑。}
### {218}{}{Can I ask you a few questions, Ralph?}
{218}{}{拉尔夫，我能问你几个问题吗？}

### {220}{}{Hello again.}
{220}{}{你好。}
### {221}{}{See you again.}
{221}{}{再见。}

### {230}{}{Has this station been operating since before the war?}
{230}{}{这个车站从战前就开始运营了吗？}
### {231}{}{It has been preserved for a long time. And only recently it was possible to start the main reactor.}
{231}{}{它保存了很长时间。直到最近才有可能启动主反应堆。}
### {232}{}{How did it work out?}
{232}{}{结果如何？}
### {233}{}{Thank the fire worshippers and their colony in Flagstaff for this. Uranium is mined there on the church lid. And some of this uranium comes to us. It was a profitable contract for the whole city.}
{233}{}{为此感谢火焰崇拜者和他们在弗拉格斯塔夫的殖民地。铀是在教堂的盖子上开采的。这些铀中的一部分来到了我们这里。这对整个城市来说都是一份有利可图的合同。}
### {234}{}{Wow, it turns out that people in the church don't just pray.}
{234}{}{哇，原来教堂里的人不仅仅是祈祷。}
### {235}{}{It would be better to feed the people than to force slaves to work ore.}
{235}{}{与其强迫奴隶开采矿石，不如养活人民。}
### {236}{}{How did you all end up here?}
{236}{}{你们是怎么来到这里的？}
### {237}{}{We came from the west, from California. But this is a separate story. Coincidentally, we were offered to restore the station. After all, you, the modern generation, don't know a damn thing about the old technology.}
{237}{}{我们来自西部，来自加利福尼亚。但这是另一回事。巧合的是，我们得到了修复车站的提议。毕竟，你们现代一代对旧技术一无所知。}
### {238}{}{Wait a minute, do you really mean to say that you have lived for a hundred years?}
{238}{}{等等，你真的是说你已经活了一百年了吗？}
### {239}{}{Well preserved, aren't they? Our favorite joke. They say that the cause of our mutation was some kind of virus that accidentally got into the air during the bombing of the old laboratory. But these are just rumors.}
{239}{}{保存完好，不是吗？我们最喜欢的笑话。他们说，我们突变的原因是在轰炸旧实验室时意外进入空气中的某种病毒。但这些只是谣言。}
### {240}{}{Tell me, what was the world like before the war?}
{240}{}{告诉我，战前的世界是什么样子的？}
### {241}{}{Hmm... A hundred years have passed, much is in a fog. I remember cars, skyscrapers and military checkpoints. I remember the war when the bombs fell on the city. But is it possible to explain all this to a person like you? It's just a story for you.}
{241}{}{嗯…一百年过去了，很多事情都是迷雾重重。我记得汽车、摩天大楼和军事检查站。我记得炸弹落在城市上的那场战争。但是，有可能向你这样的人解释这一切吗？这只是给你的一个故事。}
### {242}{}{I see it's hard for you to remember this. Let's change the subject.}
{242}{}{我知道你很难记住这件事。让我们换个话题。}
### {243}{}{Are you trying to humiliate me now? Not another word, Mr. Pockmarked Skin.}
{243}{}{你现在是想羞辱我吗？别再说了，麻子皮先生。}
### {244}{}{Your boss says the pipeline was blown up. What do you think about it?}
{244}{}{你老板说管道被炸毁了。你觉得怎么样？}
### {245}{}{Wow, that's a strong word. Don't take that old man's words into your head. He's losing his mind a little.}
{245}{}{哇，这是一个强有力的词。不要把那个老人的话记在脑子里。他有点失去理智了。}
### {246}{}{But he has to pay me for the work.}
{246}{}{但他得付我工钱。}
### {247}{}{Then do what he says. He needs the culprits - find them. How to do it? That's bad luck... You know, most likely the bombers penetrated through the sewers. But I thought we sealed all the entrances well.}
{247}{}{那就照他说的去做。他需要罪犯——找到他们。怎么做？那是坏运气...你知道，轰炸机很可能穿过下水道。但我认为我们把所有的入口都封得很好。}
### {248}{}{Good idea. This needs to be checked.}
{248}{}{好主意这需要检查。}
### {249}{}{Most likely, the bombers penetrated through the sewers. But it seemed to me that we had sealed all the passages well.}
{249}{}{最有可能的是，轰炸机穿过下水道。但在我看来，我们把所有的通道都封得很好。}

### {250}{}{Fiend of the Electromagnetic Hell, disappear! Everything was going well while you were away.}
{250}{}{电磁地狱的恶魔，消失！你不在的时候一切都很顺利。}
### {251}{}{The game is over, Ralph. You've lost. }
{251}{}{比赛结束了，拉尔夫。你输了。}
### {252}{}{Oh no, we just started the fun. Now you will see the real power of the Old World!}
{252}{}{哦，不，我们刚开始玩。现在你将看到旧世界的真正力量！}
### {253}{}{Don't, don't do this...}
{253}{}{不要，不要这样...}
### {254}{}{It's worse for you, you idiot.}
{254}{}{这对你来说更糟，你这个白痴。}
### {255}{}{Listen to me, Ralph. Everything was bad from the very beginning. You were used.}
{255}{}{听我说，拉尔夫。一切从一开始就很糟糕。你被利用了。}
### {256}{}{This is a mutually beneficial contract. Only fire worshippers could give the station a new life and revive a piece of the Old World. No one else had the knowledge and resources to do this. And old Theodore is just losing his mind. It's scary to think how this story will end under his leadership.}
{256}{}{这是一份互惠互利的合同。只有消防崇拜者才能赋予车站新的生命，让旧世界的一部分复活。没有其他人有这样的知识和资源。老西奥多正在失去理智。想想这个故事在他的领导下会如何结束，真是令人恐惧。}
### {257}{}{Even so, you won't get out of here alive.}
{257}{}{即便如此，你也不会活着离开这里。}
### {258}{}{Yes, the church does not care about all of you and the world around you. Don't you see?}
{258}{}{是的，教会并不关心你们所有人和你们周围的世界。你没看见吗？}
### {259}{}{Enough of this chatter! Now you will see the real power of the Old World.}
{259}{}{别再喋喋不休了！现在你将看到旧世界的真正力量。}
### {260}{}{I understand you. You want to bring back the old world that you knew. But look around - fire worshippers create another world.}
{260}{}{我理解你。你想把你熟悉的旧世界带回来。但环顾四周，拜火教徒创造了另一个世界。}
### {261}{}{Another... Yes. Aaron is just using them to create an empire. I didn't think about it. But if you think about it... Damn it, what should I do? Go back to ruined California? Or go with the guys to the east? Who knows, maybe it will be possible to find oil in Texas or restore the old Chrysler Motors plants.}
{261}{}{另一个对亚伦只是利用他们来建立一个帝国。我没想过。但如果你想一想…该死，我该怎么办？回到被毁的加利福尼亚？还是和他们一起去东部？谁知道呢，也许有可能在得克萨斯州找到石油，或者恢复克莱斯勒汽车公司的旧工厂。}
### {262}{}{Believe me, they won't let you live here. You will become only a weapon in the hands of the emperor.}
{262}{}{相信我，他们不会让你住在这里的。你将成为皇帝手中的唯一武器。}
### {263}{}{To hell with it. You can't let a schizoid like you go. You will die here and now.}
{263}{}{见鬼去吧，你不能放过像你这样的精神分裂症患者。你会在此时此地死去。}
### {264}{}{That's a strong word. I'll leave. Peacefully. Tell Theodore to remove the guards from the doors.}
{264}{}{这是一个强有力的词。我要走了。和平地。告诉西奥多把警卫从门上移开。}
### {265}{}{A reasonable solution, Ralph.}
{265}{}{一个合理的解决方案，拉尔夫。}
### {266}{}{Your boss suggested I fix the cooling system. Can you tell me where to start?}
{266}{}{你老板建议我修理一下冷却系统。你能告诉我从哪里开始吗？}
### {267}{}{What is this old man thinking about, letting a stranger into the very heart of the station? Okay, let's see. First, inspect the damage on the lower level. We will need materials and equipment for repairs. The easiest way to get them is at the tinsmith factory. It's somewhere to the south of the city, the caravaneers should know for sure.}
{267}{}{这个老人在想什么，让一个陌生人进入车站的中心？好吧，让我们看看。首先，检查下层的损坏情况。我们将需要材料和设备进行维修。拿到它们最简单的方法是在锡匠厂。它在城市南部的某个地方，房车司机应该肯定知道。}
### {268}{}{Thank you.}
{268}{}{非常感谢。}

### {270}{}{I know that the cardinals acted through you. There was information about this in the Cathedral.}
{270}{}{我知道红衣主教是通过你行事的。大教堂里有关于这件事的信息。}
### {271}{}{Keep your voice down, there's no need for such rudeness. So, let's go to a secluded place...}
{271}{}{小声点，没必要这么粗鲁。所以，让我们去一个僻静的地方...}
### {272}{}{[Next]}
{272}{}{[下一个]}
### {273}{}{I understand that you have connections with the fire worshippers, otherwise how did you get information about our secret contract?}
{273}{}{我知道你和拜火教徒有关系，否则你是怎么得到我们秘密合同的信息的？}
### {274}{}{I have a lot of connections. But what are you trying to achieve? Do you want to take your boss's place?}
{274}{}{我有很多关系。但是你想达到什么目的呢？你想取代你老板的位置吗？}
### {275}{}{What narrow-minded motives. Don't forget that I'm a hundred years old. If we were in the Old World, I would crave a career promotion. But what do we have now? The devastation, the lack of transport and roads, even street lighting, people saw only thanks to us and the Church of Fire.}
{275}{}{多么狭隘的动机啊。别忘了我已经一百岁了。如果我们在旧世界，我会渴望职业晋升。但我们现在有什么？人们看到的破坏、缺乏交通和道路，甚至街道照明，都要归功于我们和火之教会。}
### {276}{}{Isn't the church sponsoring you with uranium?}
{276}{}{教会不是在用铀赞助你吗？}
### {277}{}{That's not enough. Theodore doesn't let them go to the station's affairs, and without them, business is moving too slowly. At first it seemed like a purely technical matter - they took uranium and got energy from it. Now comes the time of the economy, business and taxes. Theodore does not understand anything about this and believes that it is enough just to sell energy left and right.}
{277}{}{这还不够。西奥多不让他们去处理车站的事务，没有他们，生意进展太慢了。起初，这似乎是一个纯粹的技术问题——他们从中提取铀并获得能源。现在是经济、商业和税收的时候了。西奥多对此一无所知，他认为仅仅左右出售能源就足够了。}
### {278}{}{So you want to renegotiate the contract. What about Theodore?}
{278}{}{所以你想重新谈判合同。西奥多呢？}
### {279}{}{The problem is that the old man is out of his mind, but there are workers behind him. I need to be at the helm of the station for something to change. Help me. Get rid of Theodore, and you will receive a reward and respect. Moreover, you will do a useful thing for the whole city.}
{279}{}{问题是老人疯了，但他身后有工人。我需要掌管电台才能有所改变。帮帮我，除掉西奥多，你就会得到奖赏和尊重。此外，你将为整个城市做一件有用的事情。}
### {280}{}{I'll think about it.}
{280}{}{我会考虑的。}
### {281}{}{My plan has already partially failed because you fixed the cooler. Don't let me down this time.}
{281}{}{我的计划已经部分失败了，因为你修理了冷却器。这次别让我失望。}
### {1281}{}{My plan has already partially failed because you fixed the cooler. Don't let me down this time.}
{1281}{}{我的计划已经部分失败了，因为你修理了冷却器。这次别让我失望。}
### {282}{}{Bye.}
{282}{}{再见}
### {283}{}{We've already discussed everything. Don't disappoint me again.}
{283}{}{我们已经讨论过了。别再让我失望了。}
### {284}{}{Bye.}
{284}{}{再见}
### {285}{}{But how do I eliminate Theodore? This is a dangerous task.}
{285}{}{但我该如何消除西奥多？这是一项危险的任务。}
### {286}{}{I've been thinking about it. An open murder will cause too much controversy and suspicion. Try mixing poison from strong drugs. The old ghoul's heart probably won't stand it.}
{286}{}{我一直在想。公开的谋杀会引起太多的争议和怀疑。试着把毒药和烈性药混合在一起。老食尸鬼的心可能受不了。}
### {287}{}{Good idea. There was a pusher somewhere in the slums.}
{287}{}{好主意贫民窟里有个推手。}
### {288}{}{It's done. The stationmaster's post is yours now.}
{288}{}{它完成了。站长的职位现在是你的了。}
### {289}{}{The angel of the Electromagnetic Pulse must have sent you to us. Thank you. You did the right thing. Now go to the storekeeper and ask him for a reward. He'll find something to thank you with.}
{289}{}{电磁脉冲的天使一定把你送到我们这里了。谢谢。你做了正确的事。现在去找店主，向他索要报酬。他会找到一些东西来感谢你的。}
### {1289}{}{The angel of the Electromagnetic Pulse must have sent you to us. Thank you. You did the right thing. Now go to the storekeeper and ask him for a reward. He will find something to thank you with.}
{1289}{}{电磁脉冲的天使一定把你送到我们这里了。谢谢。你做了正确的事。现在去找店主，向他索要报酬。他会找到一些东西来感谢你的。}
### {290}{}{Goodbye, Ralph.}
{290}{}{再见，拉尔夫。}

### {291}{}{I heard that you are getting uranium from Flagstaff.}
{291}{}{我听说你们从弗拉格斯塔夫那里得到铀。}
### {1291}{}{I heard that you are getting uranium from Flagstaff.}
{1291}{}{我听说你们从弗拉格斯塔夫那里得到铀。}
### {292}{}{Not quite. We get fuel elements with uranium filling, and they are produced in the south. Uranium ore is also being transported there. And what?}
{292}{}{不完全是。我们用铀填充燃料元素，它们是在南方生产的。铀矿也正在运往那里。什么？}
### {293}{}{Does it bother you that this ore is mined by slave labor?}
{293}{}{你觉得这些矿石是奴隶开采的吗？}
### {294}{}{We don't care who gets it and how. We need uranium, and the rest is not our concern.}
{294}{}{我们不在乎谁和如何得到它。我们需要铀，其余的都不是我们关心的问题。}
### {295}{}{Hmm. It makes sense. But you are still indirectly guilty.}
{295}{}{嗯，这很有道理。但你仍然间接有罪。}
### {296}{}{I understand. It's just business.}
{296}{}{我理解。这只是生意。}
