### {100}{}{This is Bart Thur.}
{100}{}{我是Bart Thur。}
### {101}{}{You see the owner of the gun shop. He seems to be obsessed with weapons.}
{101}{}{你看到枪店的老板了。他似乎痴迷于武器。}
### {102}{}{Oh, it's power armor! I've heard so much about her, but I've never seen...}
{102}{}{哦，这是力量盔甲！我听说过很多关于她的事，但我从未见过...}
### {103}{}{Don't touch it. I don't serve addicts. Who knows what's on your mind?}
{103}{}{别碰它。我不为瘾君子服务。谁知道你在想什么？}

#Start of the dialog
### {200}{}{(looks closely and skeptically at you, assessing the prospects of trading) What kind of weapon do you need, sir? For hunting or to intimidate bandits? I have plenty of guns for any purpose.}
{200}{}{（仔细而怀疑地看着你，评估交易的前景）你需要什么样的武器，先生？狩猎还是恐吓土匪？我有很多枪可以用。}
### {1200}{}{(looks closely and skeptically at you, assessing the prospects of trading) What are you looking for, ma'am? There are plenty of weapons here for any purpose and for any level of prosperity.}
{1200}{}{（仔细而怀疑地看着你，评估交易的前景）女士，你在找什么？这里有很多武器，用于任何目的和任何程度的繁荣。}
### {201}{}{Let me see...}
{201}{}{让我看看...}
### {202}{}{Let me take a closer look at your guns.}
{202}{}{让我仔细看看你的枪。}

### {210}{}{(silently waiting for your remarks, lovingly wiping the weapon from the dust)}
{210}{}{（默默地等待你的发言，深情地擦拭着武器上的灰尘）}
### {211}{}{I think I'll go.}
{211}{}{我想我会去的。}
### {212}{}{I see.}
{212}{}{我明白了。}

### {213}{}{Someone broke into the mercenary guild and killed Bruce Turner.}
{213}{}{有人闯入雇佣兵公会杀死了布鲁斯·特纳。}
### {214}{}{Yes, I know.}
{214}{}{是的，我知道。}
### {215}{}{I hope that son of a bitch got what he deserved. Because because of him, I lost a good welding from the guild.}
{215}{}{我希望那个婊子养的得到他应得的。因为他，我失去了公会的一个好焊接。}
### {216}{}{Cheer up, a new guild will surely appear.}
{216}{}{振作起来，一个新的公会一定会出现。}
### {217}{}{So you sponsored them with guns? You shouldn't have done that.}
{217}{}{所以你用枪资助他们？你不应该那样做。}

#Questions
### {220}{}{Where did you get this weapon?}
{220}{}{你从哪里得到的武器？}
### {221}{}{Everyone here has their own story. This revolver, for example, was sold by an unlucky casino player. But this gun was taken from local bandits during the storming of their camp. Something was brought by caravans from the south. But don't you care? The main thing is not to fail in battle.}
{221}{}{这里的每个人都有自己的故事。例如，这把左轮手枪是由一个倒霉的赌场玩家卖掉的。但这把枪是在当地土匪袭击营地时从他们那里拿走的。一些东西是由南方的大篷车带来的。但你不在乎吗？最重要的是不要在战斗中失败。}
### {222}{}{What did you say about caravans from the south?}
{222}{}{你对来自南方的大篷车怎么说？}
### {223}{}{In the south there is a settlement of tinsmiths. These guys know a lot about old technologies and almost pray to them. They have restored the machines and are now engaged in repair and production. For example, here is their development... (takes it out and shows it)}
{223}{}{在南部有一个锡匠定居点。这些家伙知道很多关于旧技术的知识，几乎向他们祈祷。他们已经修复了这些机器，现在正在进行维修和生产。例如，以下是他们的发展...（拿出并展示）}
### {224}{}{[Next]}
{224}{}{[下一个]}
### {225}{}{A pneumatic spear. It operates on a spring-piston mechanism. No electronics and questionable gunpowder. (with pomp shows the work of the spear) You rest against the enemy's body, and boom! - the thorn flies out of the spear and pierces the body. Don't worry, it will return to its place by itself with the help of a return spring. Then it's just a question of your skills.}
{225}{}{气动矛。它在弹簧活塞机构上运行。没有电子产品和可疑的火药。（盛况显示长矛的作用）你靠着敌人的身体休息，然后轰隆隆！-刺从矛中飞出，刺穿了身体。别担心，它会在回位弹簧的帮助下自行返回原位。那么这只是你的技能问题。}
### {226}{}{Are they still carrying weapons from the south?}
{226}{}{他们还携带来自南方的武器吗？}
### {227}{}{Some adventurers went there in search of valuable finds. But sooner or later this flow will stop. It is much more important that the tinkerers no longer produce new weapons and do not repair old technologies. They were very useful to the whole Phoenix.}
{227}{}{一些冒险家去那里寻找有价值的发现物。但这种流动迟早会停止。更重要的是，修补者不再生产新武器，也不再修复旧技术。他们对整个凤凰城都很有用。}

#Product Disclosure
### {230}{}{And what do you have on those covered shelves?}
{230}{}{那些有盖的架子上有什么？}
### {231}{}{The best thing I have. But this product is waiting for special customers. You're not one of them yet.}
{231}{}{我拥有的最好的东西。但这款产品正在等待特殊客户。你还不是他们中的一员。}
### {232}{}{Why be so careful?}
{232}{}{为什么要这么小心？}
### {233}{}{The followers of Fire don't like it when I sell good weapons to untested types. They think that sooner or later he will be turned against the church. Therefore, all the best is bought by the followers themselves, as well as casino security, the bounty hunters guild and other respected people of the city who can be trusted.}
{233}{}{拜火教徒不喜欢我把好武器卖给未经测试的人。他们认为他迟早会反对教会。因此，所有最好的东西都是由追随者自己购买的，还有赌场保安、赏金猎人协会和其他值得信赖的城市里受人尊敬的人。}
### {234}{}{Why did you cover part of the product?}
{234}{}{为什么要覆盖部分产品？}
### {235}{}{I want to take a look at those special guns.}
{235}{}{我想看看那些特殊的枪支。}
### {236}{}{I'm sorry, but all the best I have is kept for special customers. You're not one of them yet.}
{236}{}{对不起，我所有最好的东西都留给了特殊客户。你还不是他们中的一员。}
### {237}{}{Why be so careful?}
{237}{}{为什么要这么小心？}
### {238}{}{Apparently, I have nothing else to do here.}
{238}{}{显然，我在这里没有别的事可做。}
### {239}{}{Okay, let me see what you have for a commoner like me.}
{239}{}{好吧，让我看看你对像我这样的平民有什么。}

### {240}{}{Hmm... sounds convincing. (opens the product and spreads his hands with a satisfied look) Here is all the best that there is in Phoenix...}
{240}{}{嗯…听起来很有说服力。（打开产品，满意地张开双手）这是凤凰城最好的东西...}
### {241}{}{Damn, it's enough to take over the whole city.}
{241}{}{该死，这足以占领整个城市。}
### {242}{}{And this is what you keep for the most important customers? What a pathetic sight.}
{242}{}{这就是你为最重要的客户保留的东西？多么可悲的景象。}

### {243}{}{The fire worshippers are on the run, their sect doesn't have long left. It's time to forget about your agreement.}
{243}{}{拜火教徒正在逃亡，他们的教派已经所剩无几了。是时候忘记你的协议了。}
### {244}{}{I have recently been initiated in the Cathedral.}
{244}{}{我最近在大教堂接受了启蒙。}
### {1244}{}{I have recently been initiated in the Cathedral.}
{1244}{}{我最近在大教堂接受了启蒙。}
### {245}{}{Am I really not trustworthy after so many victories in the ring?}
{245}{}{在拳击场上赢了这么多之后，我真的不值得信任吗？}
### {246}{}{I'm from the Arizona Rangers. And I really need a reliable trunk.}
{246}{}{我来自亚利桑那游骑兵队。我真的需要一个可靠的行李箱。}
### {247}{}{Don Diego advised me to buy a gun here. Don't let him down.}
{247}{}{唐建议我在这里买把枪。不要让他失望。}
### {248}{}{You have quite diverse clients, right? [Name the rebel password]}
{248}{}{你的客户非常多样化，对吧？[说出叛军的密码]}
### {249}{}{You will be happy with this contract.}
{249}{}{你会对这份合同感到满意的。}
### {250}{}{Sounds unconvincing.}
{250}{}{听起来难以令人信服。}
### {251}{}{Okay, what about the rest of the weapons?}
{251}{}{好吧，剩下的武器呢？}
### {252}{}{Then I'm out of here.}
{252}{}{那我就离开这里。}
### {253}{}{I have connections all over Arizona. Such a contract will be beneficial to both of us.}
{253}{}{我在亚利桑那州各地都有关系。这样的合同对我们双方都有利。}
### {254}{}{I'll vouch for my reputation.}
{254}{}{我保证我的名誉。}
### {255}{}{You won't have any problems because of me. I guarantee my reputation.}
{255}{}{你不会因为我而有任何问题。我保证我的声誉。}
### {256}{}{If you don't cooperate with me, I'll kill you.}
{256}{}{如果你不配合我，我就杀了你。}
### {257}{}{Do you want me to call my friends from an influential gang?}
{257}{}{你想让我给一个有影响力的帮派的朋友打电话吗？}
### {258}{}{I understand. Let's see what you have for ordinary citizens.}
{258}{}{我理解。让我们看看你为普通公民做了什么。}
### {259}{}{Trust me, too. "There are no people more loyal to the emperor than a handful of peasants."}
{259}{}{也相信我。“没有什么人比一小撮农民更忠于皇帝了。”}

### {260}{}{Anything else?}
{260}{}{还有别的吗？}
### {261}{}{Yes, I wanted to ask something else.}
{261}{}{是的，我想问别的问题。}
### {262}{}{That's all I need. Later.}
{262}{}{这就是我所需要的。后来}

#Discounts and penalties
### {280}{}{(recognizing your person, the seller suddenly perks up) Ah, it's you. Glad to see you in my store.}
{280}{}{（认出你的人，卖家突然兴奋起来）啊，是你。很高兴在我店里见到你。}
### {281}{}{Sounds like a hint of a bargain.}
{281}{}{听起来像是讨价还价的暗示。}
### {282}{}{We'll see... Dear people, I make a small discount. After all, it is necessary to support the development of the city, even doing business.}
{282}{}{我们拭目以待...亲爱的人们，我给你们打个小折扣。毕竟，支持城市发展，甚至做生意都是必要的。}
### {283}{}{Discount? Great, I'll need it.}
{283}{}{折扣太好了，我需要它。}
### {284}{}{(Having recognized your person, the seller warily changes his position, as if expecting a trick) Hey. Do you need something?}
{284}{}{（认出你的人后，卖家小心翼翼地改变了自己的位置，好像在期待一个把戏）嘿。你需要什么吗？}
### {285}{}{I'm thinking of buying a weapon...}
{285}{}{我在考虑买武器...}
### {286}{}{Then choose quickly and get lost. This isn't a gang hangout. And keep in mind, I won't sell anything to assholes like you at a normal price.}
{286}{}{然后快速选择，然后迷失方向。这不是帮派聚会。记住，我不会以正常价格把任何东西卖给像你这样的混蛋。}
### {287}{}{Whatever you say, man. Still, I need a weapon. Even at an increased price.}
{287}{}{不管你说什么，伙计。不过，我需要一把武器。即使价格上涨。}
### {288}{}{You should appreciate any buyer. You know, the world is changing too fast.}
{288}{}{你应该感谢任何买家。你知道，世界变化太快了。}

### {290}{}{Hey, do you think you can just show up here after the explosion in the Cathedral? The townspeople will be unhappy if I continue to trade weapons with you sectarians...}
{290}{}{嘿，你觉得大教堂爆炸后你能出现在这里吗？如果我继续和你们这些宗派主义者交换武器，镇上的人会不高兴的...}
### {291}{}{That's why I need a weapon for self-defense.}
{291}{}{这就是为什么我需要自卫武器。}
### {292}{}{Hmm, okay. I'll sell you something. But no discounts, okay?}
{292}{}{嗯，好吧。我要卖给你一些东西。但没有折扣，好吗？}
### {293}{}{caps are not a problem. Just show your product.}
{293}{}{上限不是问题。只需展示您的产品。}
### {294}{}{I don't need your condescension, you fool.}
{294}{}{我不需要你的屈尊俯就，你这个傻瓜。}
### {295}{}{Looks like I'm not welcome here. I'd better go.}
{295}{}{看来我在这里不受欢迎。我最好去。}

#Training
### {300}{}{Can you just shoot a gun without buying it?}
{300}{}{你能不买就开枪吗？}
### {301}{}{Pay for ammo and rental of weapons - and you can shoot skills in the dash as much as you want.}
{301}{}{支付弹药和武器租赁费用，你就可以随心所欲地在冲刺中射击。}
### {302}{}{Here are 500 caps for shooting light weapons.}
{302}{}{这里有500顶射击轻武器的瓶盖。}
### {303}{}{Here are 1000 caps for firing heavy weapons.}
{303}{}{这里有1000顶重型武器发射帽。}
### {304}{}{Here are 2000 caps if you let me shoot with an energy weapon.}
{304}{}{如果你让我用能量武器射击，这里有2000个瓶盖。}
### {305}{}{Here are 250 caps for learning the throwing skill.}
{305}{}{这里有250顶用来学习投掷技巧的瓶盖。}
### {306}{}{Then it's easier for me to buy a gun.}
{306}{}{那我就更容易买枪了。}
### {307}{}{This is robbery. I'm leaving here.}
{307}{}{这是抢劫。我要离开这里。}
### {308}{}{Save caps if you want to learn shooting.}
{308}{}{如果你想学习射击，可以节省瓶盖。}
### {309}{}{OK.}
{309}{}{好啊}

#Ammunition equipment
### {330}{}{I need to refit the cartridges.}
{330}{}{我需要重新装配弹药筒。}
### {331}{}{I can re-equip signal cartridges and cartridges with buckshot. And it doesn't make much sense to mess with pistol and rifle ones.}
{331}{}{我可以重新装备信号弹药筒和装有子弹的弹药筒。把手枪和步枪弄得一团糟也没有多大意义。}
### {332}{}{[Strengthen the signal cartridge]}
{332}{}{[加强信号盒]}
### {333}{}{[Strengthen the modified signal cartridge]}
{333}{}{[加强修改后的信号盒]}
### {334}{}{[Replace buckshot with a bullet in a 12-gauge cartridge]}
{334}{}{[用12号子弹替换子弹]}
### {335}{}{Each cartridge for 1 cap. How old are you?}
{335}{}{每个墨盒一个盖。你多大了？}
### {336}{}{Each cartridge for 2 caps. How old are you?}
{336}{}{每个墨盒可容纳2个盖帽。你多大了？}
### {337}{}{Not at all yet. I just wanted to know the prices.}
{337}{}{还没有。我只是想知道价格。}
### {338}{}{Too weak, right? They are not designed to hit a live target. But you can strengthen them and add something killer.}
{338}{}{太弱了，对吧？它们的设计并不是为了击中实弹目标。但你可以加强它们，并添加一些杀手级的东西。}
### {339}{}{I don't need it.}
{339}{}{我不需要它。}

### {340}{}{Done. Anything else?}
{340}{}{完成。还有别的吗？}
### {341}{}{I have more cartridges that need to be reloaded.}
{341}{}{我还有更多的子弹需要重新装填。}
### {342}{}{I might be interested in something other than cartridges.}
{342}{}{我可能对子弹以外的东西感兴趣。}
### {343}{}{No, goodbye.}
{343}{}{不，再见。}
### {344}{}{Something is missing, right? Look around, I have a lot of other products.}
{344}{}{有些东西不见了，对吧？环顾四周，我还有很多其他产品。}
### {345}{}{One cartridge.}
{345}{}{一个墨盒。}
### {346}{}{Two cartridges.}
{346}{}{两个墨盒。}
### {347}{}{Three rounds.}
{347}{}{三轮。}
### {348}{}{Four rounds.}
{348}{}{四轮。}
### {349}{}{Five rounds.}
{349}{}{五轮。}

#Improving weapons
### {350}{}{Do you repair weapons?}
{350}{}{你修理武器吗？}
### {351}{}{Show me your toys, I'll think about what I can do with them.}
{351}{}{给我看看你的玩具，我会考虑我能用它们做什么。}
### {352}{}{It seems that nothing can be done about it.}
{352}{}{似乎对此无能为力。}
### {353}{}{Perhaps not this time.}
{353}{}{也许这次不会。}
### {354}{}{}
{354}{}{error : string is empty}
### {355}{}{Is there a sight for a hunting rifle?}
{355}{}{有猎枪瞄准镜吗？}
### {356}{}{I can put a 10-fold sniper scope of the Yunertl brand. A great thing when you need to shoot at a *long* distance.}
{356}{}{我可以放一个Yunertl品牌的10倍狙击镜。当你需要远距离拍摄时，这是一件很棒的事情。}
### {357}{}{How much does it cost?}
{357}{}{它要多少钱？}
### {358}{}{ caps. bottlecaps forward.}
{358}{}{瓶盖。瓶子向前冲。}
### {359}{}{I need this scope. Here are the bottlecaps and the rifle.}
{359}{}{我需要这个范围。这是水瓶和步枪。}
### {360}{}{What is missing?}
{360}{}{缺少什么？}
### {361}{}{Yes, it will have to be postponed.}
{361}{}{是的，它将不得不推迟。}
### {362}{}{(with a satisfied look evaluates his work and gives you the finished product) Anything else?}
{362}{}{（满意地看了看他的作品，然后把成品给你）还有什么吗？}
### {363}{}{Yes, don't rush to close.}
{363}{}{是的，不要急于关门。}
### {364}{}{No, I don't need anything else.}
{364}{}{不，我什么都不需要。}
### {365}{}{I need a more spacious magazine for PP 0.22.}
{365}{}{我需要一本更宽敞的杂志，PP 0.22。}
### {366}{}{Yes, such a small caliber of such a store will not be enough. But you're lucky, I have a drum just for the caliber of 0.22.}
{366}{}{是的，这样一家小规模的商店是不够的。但你很幸运，我有一个0.22口径的鼓。}
### {367}{}{I want this drum. Here are the bottlecaps and weapons.}
{367}{}{我想要这个鼓。这是瓶子和武器。}
### {368}{}{Is it possible to somehow strengthen this cattle-chasing?}
{368}{}{有没有可能以某种方式加强这种对牛的追逐？}
### {369}{}{Yes, perhaps.}
{369}{}{是的，也许吧。}
### {370}{}{It's worth it. Do it.}
{370}{}{这是值得的。去做吧。}
### {371}{}{Is there a big store for my AK-112?}
{371}{}{我的AK-112有大商店吗？}
### {372}{}{Yes, there is a magazine for forty rounds instead of the usual twenty-four. Just the last one left.}
{372}{}{是的，有一本杂志是四十发的，而不是通常的二十四发。只剩下最后一个了。}
### {373}{}{Give it here.}
{373}{}{给我。}
### {374}{}{Ten rounds.}
{374}{}{十发。}
### {375}{}{All the ammo I have.}
{375}{}{我所有的弹药。}

#Quests
### {400}{}{Was it your gun that shot the monks at the casino?}
{400}{}{是你的枪在赌场射杀了僧侣吗？}
### {401}{}{And who are you to ask me questions?}
{401}{}{你是谁来问我问题？}
### {402}{}{Sorry. I'm investigating an attack ordered by Aaron. So can I ask you a few questions?}
{402}{}{很抱歉我正在调查亚伦下令的一次袭击。我可以问你几个问题吗？}
### {403}{}{I don't know any more about the attack than you do. And I doubt that they fired from weapons bought in my store.}
{403}{}{我对这次袭击的了解不比你多。我怀疑他们是用在我店里买的武器开枪的。}
### {404}{}{Why is that?}
{404}{}{为什么？}
### {405}{}{Here I ask questions and you answer. Or do you want problems with Followers?}
{405}{}{在这里我提问，你回答。还是你希望追随者有问题？}
### {406}{}{I've been interrogated by four people before you. I've already told them everything I know. And I don't know any more than you do. And I doubt that they fired from weapons bought in my store.}
{406}{}{在你之前我已经被四个人审问过了。我已经告诉了他们我所知道的一切。我不知道的比你多。我怀疑他们是用在我店里买的武器开枪的。}
### {407}{}{Something is doubtful. This is the only gun shop, right?}
{407}{}{有些事情值得怀疑。这是唯一的枪支商店，对吧？}
### {408}{}{Although my shop is the only one in the city, you can get weapons anywhere. The most armed people in the city are, perhaps, the Followers of Fire themselves. At one time, all the trunks were collected by them to make a revolution. Besides, I supply the best weapons to them, such an agreement.}
{408}{}{虽然我的商店是城里唯一的一家，但你可以在任何地方买到武器。这座城市里武装最多的人，也许就是拜火教徒。有一段时间，所有的树干都被他们收集起来进行革命。此外，我向他们提供最好的武器，这样的协议。}
### {409}{}{Then who could attack the monks?}
{409}{}{那么谁能攻击僧侣呢？}
### {410}{}{Are you *asking* me that? You're a shitty detective. My advice to you is to talk to people in the market, they saw everything with their own eyes.}
{410}{}{你在问我这个吗？你是个差劲的侦探。我给你的建议是与市场上的人交谈，他们亲眼目睹了一切。}
### {411}{}{Okay, I'll talk to them. But remember that no one will get away from Followers unpunished.}
{411}{}{好吧，我会和他们谈谈。但请记住，没有人会逃脱追随者的惩罚。}
### {412}{}{Thank you, you helped me a lot. Have a nice day.}
{412}{}{谢谢你，你帮了我很多。祝你今天愉快。}
