### {100}{}{Here is a player.}
{100}{}{这是一个球员。}

### {101}{}{It looks like this player is very lucky today.}
{101}{}{看起来这位球员今天很幸运。}
### {102}{}{You see a casino customer. He gets into a rage from a string of wins.}
{102}{}{您看到一位赌场客户。他因一连串的胜利而勃然大怒。}
### {103}{}{This player is bored. It looks like he's not winning, but he's not losing either.}
{103}{}{这个玩家很无聊。看起来他没有赢，但他也没有输。}
### {104}{}{You see a casino customer. He is angry from a string of losses.}
{104}{}{您看到一位赌场客户。他对一连串的损失感到愤怒。}
### {105}{}{This player panicked his head. Apparently, he lost his entire fortune.}
{105}{}{这个球员惊慌失措。显然，他失去了全部财产。}

### {109}{}{How did they let you through in such armor?}
{109}{}{他们是怎么让你穿上这样的盔甲的？}

#Retaliatory remarks
#- good
### {110}{}{Great place, right?}
{110}{}{好地方，对吧？}
### {111}{}{I'm doing great, and you?}
{111}{}{我做得很好，你呢？}
### {112}{}{I'm lucky today.}
{112}{}{我今天很幸运。}
### {113}{}{This casino is the best place in the world.}
{113}{}{这个赌场是世界上最好的地方。}
### {114}{}{I know how to win, honestly.}
{114}{}{老实说，我知道如何获胜。}
### {115}{}{Do you like this game? Sheer pleasure.}
{115}{}{你喜欢这个游戏吗？纯粹的快乐。}
### {116}{}{bottlecaps! bottlecaps! bottlecaps!}
{116}{}{装瓶！装瓶！装瓶！}
### {117}{}{Don't scare my luck.}
{117}{}{别吓到我的运气。}
### {118}{}{Why does this always happen to me?}
{118}{}{为什么这种事总是发生在我身上？}
### {119}{}{I just had a breakthrough.}
{119}{}{我刚刚有了突破。}
### {120}{}{Step back.}
{120}{}{退一步。}
### {121}{}{Don't stand here.}
{121}{}{不要站在这里。}
### {122}{}{Today all the chips will be mine!}
{122}{}{今天所有的筹码都是我的！}
### {123}{}{I already feel like a part of the machine.}
{123}{}{我已经觉得自己是机器的一部分了。}
#Quote from the TV series Star Track season 1 episode 2: I already feel like a part of the remote.
### {124}{}{We are old acquaintances with this machine.}
{124}{}{我们是这台机器的老熟人了。}
### {125}{}{Don't count on a drink.}
{125}{}{不要指望喝一杯。}
### {126}{}{Dare to play against me?}
{126}{}{敢和我比赛吗？}
### {127}{}{These damn beggar tourists...}
{127}{}{这些该死的乞丐游客。。。}
### {128}{}{Don't get caught when I'm playing.}
{128}{}{我玩的时候别被抓住。}
### {129}{}{Do you want to share my luck? No, go for a walk.}
{129}{}{你想分享我的运气吗？不，去散散步。}

#- bad
### {150}{}{Terrible place, I can't win anything.}
{150}{}{糟糕的地方，我什么都赢不了。}
### {151}{}{I'm doing the worst, aren't you?}
{151}{}{我做得最糟了，不是吗？}
### {152}{}{I'm really unlucky today.}
{152}{}{我今天真的很倒霉。}
### {153}{}{This is not a casino, but a den of one-armed robbers.}
{153}{}{这不是一个赌场，而是一个独臂强盗的巢穴。}
### {154}{}{I will never win here.}
{154}{}{我在这里永远不会赢。}
### {155}{}{I shouldn't be playing this game at all. It's hopeless.}
{155}{}{我根本不应该玩这个游戏。这是无望的。}
### {156}{}{Hey, borrow a couple of caps.}
{156}{}{嘿，借几顶帽子。}
### {157}{}{If I win, I'll give everyone a drink.}
{157}{}{如果我赢了，我会给每个人一杯。}
### {158}{}{I hope you have better luck than me.}
{158}{}{我希望你的运气比我好。}
### {159}{}{This streak of bad luck will never end.}
{159}{}{这一连串的厄运永远不会结束。}
### {160}{}{I really need to win.}
{160}{}{我真的需要赢。}
### {161}{}{Well, it's just a game.}
{161}{}{这只是一场游戏。}
### {162}{}{The dice don't go.}
{162}{}{骰子不会掉。}
### {163}{}{They are clearly cheating.}
{163}{}{他们显然在作弊。}
### {164}{}{Fortune has turned away from me.}
{164}{}{命运已经从我身边溜走了。}
### {165}{}{Wherever you go, there are scammers all around.}
{165}{}{无论你走到哪里，到处都是骗子。}
### {166}{}{I've already run out of chips.}
{166}{}{我的筹码已经用完了。}
### {167}{}{Luck is a flighty bitch.}
{167}{}{幸运是个轻浮的婊子。}
### {168}{}{I managed to win as many as 60 chips! But then...}
{168}{}{我赢得了多达60个筹码！但是。。。}
### {169}{}{My whole life is at stake!}
{169}{}{我的整个生命危在旦夕！}
### {170}{}{Be careful, there's deception all around.}
{170}{}{小心，到处都是骗局。}
### {171}{}{They must have screwed up the machines.}
{171}{}{他们一定把机器搞砸了。}

#Random replicas
#- bad
### {200}{}{Come on!}
{200}{}{来吧}
### {201}{}{Why is this game so cruel to me?}
{201}{}{为什么这个游戏对我如此残酷？}
### {202}{}{I'm out of luck today.}
{202}{}{我今天运气不好。}
### {203}{}{Crappy game!}
{203}{}{疯狂的游戏！}
### {204}{}{I hate this game}
{204}{}{我讨厌这个游戏}
### {205}{}{I have a fever!}
{205}{}{我发烧了！}
### {206}{}{But it started so well...}
{206}{}{但它开始得很好。。。}
### {207}{}{Either I win, or I'm dead.}
{207}{}{要么我赢了，要么我死了。}
### {208}{}{If I lose again, I will demolish this place.}
{208}{}{如果我再输，我会毁掉这个地方。}
### {209}{}{I'm not going anywhere without winning.}
{209}{}{我哪儿也不会不赢。}
### {210}{}{I can't win.}
{210}{}{我赢不了。}
### {211}{}{I'm almost at zero!}
{211}{}{我快归零了！}
### {212}{}{A little more and I'm bankrupt.}
{212}{}{再多一点，我就破产了。}
### {213}{}{I'm tired of losing.}
{213}{}{我厌倦了失败。}
### {214}{}{Were there really the last chips?}
{214}{}{真的有最后的筹码吗？}
### {215}{}{Damn it!}
{215}{}{该死！}
### {216}{}{If I'm not lucky now, then I'm leaving.}
{216}{}{如果我现在运气不好，那我就要走了。}
### {217}{}{My pockets are empty.}
{217}{}{我的口袋是空的。}
### {218}{}{Almost got it...}
{218}{}{差一点。。。}
### {219}{}{Not that!}
{219}{}{不是这样！}
### {220}{}{My affairs are bad.}
{220}{}{我的事情很糟糕。}
### {221}{}{Eh, one more time?}
{221}{}{呃，再来一次？}
### {222}{}{No, no. Stop!}
{222}{}{不，不，停下！}
### {223}{}{Oops}
{223}{}{Oops}
### {224}{}{Almost!}
{224}{}{几乎}
### {225}{}{Damn it!}
{225}{}{该死！}
### {226}{}{How did this happen?}
{226}{}{这是怎么发生的？}
### {227}{}{Why me?}
{227}{}{为什么是我？}
### {228}{}{What, again?!}
{228}{}{又是什么？！}
### {229}{}{That's really unlucky...}
{229}{}{这真的很不幸。。。}
### {230}{}{I need a drink.}
{230}{}{我需要喝一杯。}
### {231}{}{Everything was against me.}
{231}{}{一切都对我不利。}
### {232}{}{So close!}
{232}{}{太近了！}
### {233}{}{Watch me break the bank.}
{233}{}{看着我打破银行。}
### {234}{}{Great, one more beggar.}
{234}{}{太好了，又来了一个乞丐。}
### {235}{}{Ugh, it's time to take a leak.}
{235}{}{啊，是时候泄漏了。}
### {236}{}{By selling my spleen, I can recoup...}
{236}{}{通过卖我的脾脏，我可以收回。。。}
### {237}{}{Not in this life.}
{237}{}{这辈子都不会。}
### {238}{}{Stop mocking me!}
{238}{}{别再嘲笑我了！}
### {239}{}{Today is not my day.}
{239}{}{今天不是我的日子。}
### {240}{}{Your mother!}
{240}{}{你妈妈！}
### {241}{}{Oh, no!}
{241}{}{哦，不！}

#- good
### {300}{}{Yes!}
{300}{}{对}
### {301}{}{Don't let me down this time.}
{301}{}{这次别让我失望。}
### {302}{}{I'm lucky today.}
{302}{}{我今天很幸运。}
### {303}{}{Great game!}
{303}{}{伟大的游戏！}
### {304}{}{I love this game.}
{304}{}{我喜欢这个游戏。}
### {305}{}{Am I dreaming or is it true?}
{305}{}{我是在做梦还是真的？}
### {306}{}{Great, let's continue.}
{306}{}{太好了，让我们继续。}
### {307}{}{Today I can live beautifully.}
{307}{}{今天我可以活得很漂亮。}
### {308}{}{If I win, I'll give everyone a drink.}
{308}{}{如果我赢了，我会给每个人一杯。}
### {309}{}{You can't stop while you're lucky.}
{309}{}{运气好的时候不能停下来。}
### {310}{}{I can't lose, not now.}
{310}{}{我不能输，现在不行。}
### {311}{}{I smell a good jackpot.}
{311}{}{我闻到了好彩的味道。}
### {312}{}{At this rate, I will become the richest in the city.}
{312}{}{按照这个速度，我将成为这个城市最富有的人。}
### {313}{}{It's been better.}
{313}{}{好多了。}
### {314}{}{bottlecaps! bottlecaps! bottlecaps!}
{314}{}{装瓶！装瓶！装瓶！}
### {315}{}{Yes-s-s!}
{315}{}{是的，是的！}
### {316}{}{I'm definitely going to get lucky now.}
{316}{}{我现在肯定会很幸运的。}
### {317}{}{Chips are already out of my pockets.}
{317}{}{薯片已经从我口袋里出来了。}
### {318}{}{That's how it would always be.}
{318}{}{事情总是这样。}
### {319}{}{Hurray! Win!}
{319}{}{万岁！赢}
### {320}{}{Jump up again!}
{320}{}{再跳起来！}
### {321}{}{Of course!}
{321}{}{当然}
### {322}{}{Let's! Come on!}
{322}{}{让我们来吧}
### {323}{}{Great!}
{323}{}{太棒了}
### {324}{}{Good!}
{324}{}{好的}
### {325}{}{Waiter, another drink!}
{325}{}{服务员，再来一杯！}
### {326}{}{Lady Luck, don't let me down.}
{326}{}{幸运女士，别让我失望。}
### {327}{}{Who is the winner today? It's me!}
{327}{}{今天谁是获胜者？是我！}
### {328}{}{Ha-ha!}
{328}{}{哈哈！}
### {329}{}{I'll sleep in my coffin.}
{329}{}{我会睡在我的棺材里。}

#- In front of the stage
### {350}{}{Veronica sings well.}
{350}{}{维罗妮卡唱得很好。}
### {351}{}{Veronica is beautiful.}
{351}{}{维罗妮卡很漂亮。}
### {352}{}{She lacks mobility.}
{352}{}{她行动不便。}
### {353}{}{The singer seemed to be tortured before the performance.}
{353}{}{这位歌手在演出前似乎受到了折磨。}
### {354}{}{Her songs are sad.}
{354}{}{她的歌很悲伤。}
### {355}{}{What is she singing about?}
{355}{}{她在唱什么？}
### {356}{}{Change your repertoire.}
{356}{}{改变你的曲目。}
### {357}{}{I guess I'll just listen.}
{357}{}{我想我只是听着。}
### {358}{}{Only here there is a live concert.}
{358}{}{只有这里有现场音乐会。}
### {359}{}{This is the only place where there is a singer.}
{359}{}{这是唯一有歌手的地方。}
### {360}{}{I love the casino for this scene.}
{360}{}{我喜欢赌场里的这一幕。}
### {361}{}{There is no other active stage in the city.}
{361}{}{这个城市没有其他活跃的舞台。}
### {362}{}{Bartender, another cocktail.}
{362}{}{调酒师，再来一杯鸡尾酒。}
### {363}{}{How much is it, bartender?}
{363}{}{多少钱，酒保？}
### {364}{}{Bartender, the bill!}
{364}{}{酒保，买单！}
### {365}{}{I don't seem to have anything to pay with.}
{365}{}{我似乎没有什么可付的。}
### {366}{}{This is the best bar in town.}
{366}{}{这是城里最好的酒吧。}
### {367}{}{They serve great steaks here.}
{367}{}{这里供应美味的牛排。}
### {368}{}{It's a pity to leave after this.}
{368}{}{很遗憾在这之后离开。}
### {369}{}{}
{369}{}{error : string is empty}
