### {100}{}{Here is a croupier.}
{100}{}{这是一个赌台。}
### {101}{}{You see a man with a sharp look and businesslike habits.}
{101}{}{你看到的是一个目光犀利、习惯办事的男人。}
### {102}{}{Because, in-you can't sit at roulette in THIS...}
{102}{}{因为，在这里你不能坐在轮盘赌上...}
### {103}{}{If you don't leave, I'll call security.}
{103}{}{如果你不离开，我会叫保安。}

### {200}{}{(Here is a roulette in nuclear coloring. The betting table is divided into black and red cells, and two cells labeled "0" and "00" are highlighted with a nuclear explosion pattern. The dealer takes a bright yellow ball, which for some reason is called a "bomb" here. With a habitual movement of his hand, he launches it along the wheel under the intense gazes of the players.)}
{200}{}{（这是一个核色轮盘。赌台分为黑色和红色单元格，标有“0”和“00”的两个单元格用核爆图案突出显示。庄家拿了一个亮黄色的球，不知为什么，这个球在这里被称为“炸弹”。他习惯性地用手移动，在玩家的激烈注视下沿着轮盘发射。）}
### {201}{}{Ugh, I don't know how to play this.}
{201}{}{啊，我不知道怎么玩这个。}
### {202}{}{It's probably worth a try.}
{202}{}{这可能值得一试。}
### {203}{}{I'm just looking, nevermind.}
{203}{}{我只是在看，没关系。}
### {204}{}{Of course, sir. Join us.}
{204}{}{当然，先生。加入我们。}
### {1204}{}{Of course, ma'am. Join us.}
{1204}{}{当然，夫人。加入我们。}
### {205}{}{So, what do we have here...}
{205}{}{那么，我们这里有什么...}

### {210}{}{Place your bets.}
{210}{}{下注。}
### {211}{}{I'm not playing anymore.}
{211}{}{我不再玩了。}
### {212}{}{I put 5 chips on red.}
{212}{}{我把5个筹码放在红色上面。}
### {213}{}{I bet 5 chips on black.}
{213}{}{我在黑色赌5个筹码。}
### {214}{}{I bet 5 chips on zero.}
{214}{}{我把5个筹码押在零上。}
### {215}{}{I don't have any chips left. We'll have to look in another time.}
{215}{}{我没有剩下的筹码了。我们得改天再来看看。}

### {220}{}{Bets are made.}
{220}{}{下注。}
### {221}{}{Come on, ball, don't let me down.}
{221}{}{来吧，球，别让我失望。}
### {222}{}{Let's see who gets lucky.}
{222}{}{让我们看看谁会幸运。}
### {223}{}{Keep playing.}
{223}{}{继续玩。}
### {224}{}{We play on.}
{224}{}{我们继续玩。}
### {225}{}{Launch!}
{225}{}{发射}
### {226}{}{Stop. I'm doubling my bet.}
{226}{}{停止我加倍下注。}
### {227}{}{Let. I'm tripling the bid.}
{227}{}{允许我的出价是原来的三倍。}
### {228}{}{Uh, please, sir.}
{228}{}{呃，求你了，先生。}
### {1228}{}{Uh, please, ma'am.}
{1228}{}{呃，求你了，女士。}
### {229}{}{I think I've run out of chips. Okay, keep playing.}
{229}{}{我想我的筹码用完了。好吧，继续玩。}

### {230}{}{There are no more bets.}
{230}{}{没有更多的赌注了。}
### {231}{}{[Wait]}
{231}{}{[等待]}
### {232}{}{The bomb is on red. You lost.}
{232}{}{炸弹是红色的，你输了。}
### {233}{}{Bomb on black. You lost.}
{233}{}{黑色炸弹。你输了。}
### {234}{}{Bomb on zero! You lost.}
{234}{}{零度轰炸！你输了。}
### {235}{}{A bomb on double zero! All bets go to the casino.}
{235}{}{双零点炸弹！所有赌注都押在赌场。}
### {236}{}{I want to keep playing.}
{236}{}{我想继续打球。}
### {237}{}{I think I've had enough for today.}
{237}{}{我想我今天已经受够了。}
### {238}{}{The bomb is on red. You've won.}
{238}{}{炸弹是红色的。你赢了。}
### {239}{}{A bomb on black. You won.}
{239}{}{黑色炸弹。你赢了。}
### {240}{}{The bomb is on zero. You've won! The payout will be 1 to 8.}
{240}{}{炸弹归零。你赢了！支出将为1比8。}
### {241}{}{Great, let's play on.}
{241}{}{太好了，让我们继续玩吧。}
### {242}{}{I don't play anymore. I need a break.}
{242}{}{我不再玩了。我需要休息一下。}
