### {100}{}{You see a tramp.}
{100}{}{你看到一个流浪汉。}
### {101}{}{This tramp wanders aimlessly around the square.}
{101}{}{这个流浪汉在广场上漫无目的地闲逛。}
### {102}{}{This inadequate tramp is actively chanting something in honor of the church.}
{102}{}{这个不称职的流浪汉正在积极地为教堂唱圣歌。}
### {103}{}{This guy barely moves across the square.}
{103}{}{这家伙几乎没穿过广场。}
### {104}{}{This refugee wanders aimlessly around the square.}
{104}{}{这个难民在广场上漫无目的地闲逛。}

#Floating replicas
#- beggar
### {110}{}{Leave me alone.}
{110}{}{别管我。}
### {111}{}{I do not know what to do.}
{111}{}{我不知道该怎么办。}
### {112}{}{Such as me, nothing shines in the city.}
{112}{}{像我一样，这个城市没有什么闪光点。}
### {113}{}{I'm going to lie down here... you don't mind?}
{113}{}{我要躺在这里...你不介意吗？}
### {114}{}{I want to quit this street life, but I can't.}
{114}{}{我想放弃这种街头生活，但我做不到。}
### {115}{}{Phoenix is thriving, and I'm falling further and further.}
{115}{}{凤凰在茁壮成长，而我却越来越堕落。}
### {116}{}{This, do you have some food for the poor brother from the street?}
{116}{}{这个，你有给街上那个可怜的兄弟的食物吗？}
### {117}{}{Borrow some caps, I'll give it, honestly.}
{117}{}{借几个瓶盖，老实说，我会给你的。}
### {118}{}{I really need medicine for the baby. Help me out, huh?}
{118}{}{我真的需要给孩子吃药。帮我吧？}
### {119}{}{I'm starving, at least give me a rat's tail.}
{119}{}{我饿了，至少给我一条老鼠尾巴吧。}
### {120}{}{Do you want to join? Sorry, but the area won't fit so many.}
{120}{}{你想加入吗？对不起，这个区域容纳不了那么多人。}
### {121}{}{I'm waiting for the fanatics to bring us free food.}
{121}{}{我在等狂热分子给我们带来免费的食物。}
### {122}{}{The cathedral sometimes distributes leftovers after lunch.}
{122}{}{大教堂有时会在午饭后分发剩菜。}
### {123}{}{When the food is taken out, you need to kiss the priest's feet.}
{123}{}{当食物被取出时，你需要亲吻牧师的脚。}
### {124}{}{Praise the Fire! All people are brothers! See, I'm a believer too.}
{124}{}{赞美火焰！所有人都是兄弟！看，我也是一个信徒。}

#- adept
### {130}{}{I want to become a novice, but they won't take me.}
{130}{}{我想成为一个新手，但他们不会接受我。}
### {131}{}{I'm telling you - I'll become a novice!}
{131}{}{我告诉你，我会成为一个新手！}
### {132}{}{We'll have to pray a lot to be accepted into the order.}
{132}{}{我们必须祈祷很多才能被接受。}
### {133}{}{Peace! Love! Sacred Fire!}
{133}{}{和平爱神圣之火！}
### {134}{}{Do you also believe in something-there?}
{134}{}{你也相信那里的某些东西吗？}
### {135}{}{What do YOU believe in?}
{135}{}{你相信什么？}
### {136}{}{Hail the Sacred Fire!}
{136}{}{向圣火致敬！}
### {137}{}{Hail Phoenix! Hail, Aaron!}
{137}{}{凤凰万岁！万岁，亚伦！}
### {138}{}{I love Aaron! Hail, Aaron, Lord of the Phoenix!}
{138}{}{我爱亚伦！万岁，亚伦，凤凰之主！}
### {139}{}{My life belongs to Saint Aaron}
{139}{}{我的生命属于圣亚伦}

#- sick or disabled
### {150}{}{I am here to ask for healing from an illness.}
{150}{}{我来这里是为了请求治愈疾病。}
### {151}{}{There is no escape from my illness, but the monks promised to help.}
{151}{}{我的病无法逃脱，但僧侣们答应帮忙。}
### {152}{}{They say monks possess the ancient sacrament of healing.}
{152}{}{他们说僧侣拥有古老的治疗圣礼。}
### {153}{}{I pray to Aaron every day to heal my sores.}
{153}{}{我每天都向亚伦祈祷，让他治好我的疮。}
### {154}{}{I gave all my savings to the church, but I never cured my illness.}
{154}{}{我把所有积蓄都捐给了教堂，但我从未治好我的病。}
### {155}{}{The monks treat me with prayers. And I feel a surge of strength! Oh, no...}
{155}{}{僧侣们为我祈祷。我感觉到了力量的激增！哦，不...}
### {156}{}{The monks say I need to purify my soul. And for this you need to give everything to the church.}
{156}{}{僧侣们说我需要净化我的灵魂。为此，你需要把一切都奉献给教会。}
### {157}{}{I'm so worthless, right?}
{157}{}{我太没价值了，对吧？}
### {158}{}{I ask my followers to help me.}
{158}{}{我请求我的追随者帮助我。}
### {159}{}{Only Followers of Fire can heal as well as before the Great War.}
{159}{}{只有拜火教徒才能像大战前一样痊愈。}

#- refugee
### {170}{}{I am here to seek refuge from the Followers of Fire.}
{170}{}{我来这里是为了躲避拜火教徒。}
### {171}{}{I was told that the church accepts refugees, but this is not the case.}
{171}{}{有人告诉我教会接受难民，但事实并非如此。}
### {172}{}{We fled from bandits, but the church does not want to receive us.}
{172}{}{我们逃离了土匪，但教堂不愿意接待我们。}
### {173}{}{Followers of Fire help refugees.}
{173}{}{拜火教徒帮助难民。}
### {174}{}{The monks here are unusually round-cheeked. They are probably ill with something.}
{174}{}{这里的僧侣们的脸异常圆。他们可能病了。}
### {175}{}{Only near the temple do I feel safe.}
{175}{}{只有在寺庙附近我才感到安全。}
### {176}{}{They are strange - these fire worshippers.}
{176}{}{他们很奇怪——这些拜火教徒。}
### {177}{}{These fanatics promise paradise on earth.}
{177}{}{这些狂热分子许诺人间天堂。}
### {178}{}{They say we should be afraid, but I don't understand what or who.}
{178}{}{他们说我们应该害怕，但我不明白是什么或是谁。}
### {179}{}{It's better to give food, and everyone can preach.}
{179}{}{最好是提供食物，每个人都可以传教。}
