### {100}{}{You see a cripple.}
{100}{}{你看到一个瘸子。}
### {101}{}{Here is a beggar. He can barely move on homemade crutches.}
{101}{}{这是一个乞丐。他拄着自制的拐杖几乎不能动。}
### {102}{}{Here is a beggar. He looks much better from your last meeting.}
{102}{}{这是一个乞丐。和上次见面相比，他看起来好多了。}
### {103}{}{Thank you, Doctor. But the monks did not want to treat me.}
{103}{}{谢谢你，医生。但是僧侣们不想待我。}
### {104}{}{Help the cripple, good man! Don't pass by...}
{104}{}{帮帮瘸子，好人！不要路过。。。}
