### {100}{}{You see an old acquaintance.}
{100}{}{你看到一个老熟人。}
### {101}{}{This is one of the Followers of Fire... since recently.}
{101}{}{这是拜火教徒之一...自最近以来。}

### {200}{}{(In front of you is your old acquaintance who spied on the rangers; he seems depressed and weak-willed, his gaze has dimmed, and his former gangster manners seem to be in the past)}
{200}{}{（你面前是你的老熟人，他监视着护林员；他看起来很沮丧，意志薄弱，目光暗淡，他以前的黑帮风度似乎已经过去了）}
### {201}{}{Well, wow, what a meeting ...}
{201}{}{哇，真是个会议...}
### {202}{}{ (cloudy eyes rise heavily and barely distinguish you) You... I remember you. The Sacred Fire must have brought us together that day. Thanks to you, I am here among the Followers. Thank you.}
{202}{}{（浑浊的眼睛重重地抬起，几乎看不清你）你...我记得你。那天一定是圣火把我们带到了一起。感谢你，我在这里的追随者。非常感谢。}
### {203}{}{Uh, please. It's nice to participate in someone's personal growth.}
{203}{}{呃，求你了。参与某人的个人成长是件好事。}
### {204}{}{I thought you wouldn't survive this journey. Oh well.}
{204}{}{我还以为你撑不过这次旅行呢。哦，好吧。}

### {210}{}{I have to pray. Please leave me alone.}
{210}{}{我必须祈祷。请别理我。}
### {211}{}{Bye.}
{211}{}{再见}

### {220}{}{How did you manage to overcome the path from Parker Dam?}
{220}{}{你是如何克服帕克大坝的障碍的？}
### {221}{}{Don't ask me about such nonsense. Now I'm above that.}
{221}{}{别问我这些无稽之谈。现在我已经超越了这一点。}
### {222}{}{Then stay alone with your own... prayers.}
{222}{}{那就和你自己单独呆着...祈祷。}
### {223}{}{What is it like to be a novice in the Temple of Fire?}
{223}{}{在火神庙当新手是什么感觉？}
### {224}{}{Work and prayers. That's all we need. Until I'm ready for something more important. And only my mentor can determine that.}
{224}{}{工作和祈祷。这就是我们所需要的。直到我为更重要的事情做好准备。只有我的导师才能决定这一点。}
### {225}{}{Hmm, let me take a look at your pupils.}
{225}{}{嗯，让我看看你的瞳孔。}
### {226}{}{What is it? Stupid jokes of a villager?}
{226}{}{它是什么？一个村民的愚蠢笑话？}
### {227}{}{Yeah, uh, sort of.}
{227}{}{是的，有点。}
### {228}{}{Looks like they're drugging you here, huh?}
{228}{}{看起来他们在这里给你下药，是吗？}
### {229}{}{Well... We are given a couple of relaxing pills at lunch, this is part of the dedication. We have to clear our minds of arrogance, that's what the monks say... Ugh... I think I need to go to the toilet...}
{229}{}{好我们在午餐时吃了几片放松的药丸，这是奉献精神的一部分。我们必须清除心中的傲慢，这就是僧侣们所说的...啊...我想我需要上厕所...}
### {230}{}{Uh, it's better to leave you.}
{230}{}{呃，最好离开你。}
