### {100}{}{Here is a racketeer.}
{100}{}{这是一个敲诈勒索者。}
### {101}{}{You see an ordinary bandit. He is very determined.}
{101}{}{你看到一个普通的土匪。他意志坚定。}
### {102}{}{All right! We're leaving! It's okay, don't get excited!}
{102}{}{好吧我们要走了！没关系，别激动！}

### {110}{}{Where are you going? Get out, this is our territory now.}
{110}{}{你要去哪里？滚出去，这是我们的地盘。}
### {111}{}{You only know how to scare. Prove your right to own this place, you piece of shit.}
{111}{}{你只知道如何恐吓。证明你拥有这个地方的权利，你这个混蛋。}
### {112}{}{Oh, I'm sorry...}
{112}{}{哦，对不起...}
### {113}{}{Please leave, the locals don't want problems...}
{113}{}{请离开，当地人不希望出现问题...}
### {114}{}{Then you will GET them! Got it? Get lost, you moron piece, while your legs are intact!}
{114}{}{然后你就会得到它们！明白了吗？迷路吧，你这个白痴，趁你的腿完好无损！}
### {115}{}{You're in the Cardinals' territory. They don't tolerate competitors. Get lost.}
{115}{}{你在红雀队的地盘上。他们不容忍竞争对手。迷路}
### {116}{}{The Cardinals have been squabbling for a long time. Where do you see them?}
{116}{}{红雀队已经争吵了很长时间。你在哪里看到它们？}
### {117}{}{No matter. I'm going to clean up here now. Out!}
{117}{}{不管怎样我现在要打扫这里。出来}
### {118}{}{The cardinals still rule the area. Get out.}
{118}{}{红衣主教仍然统治着这个地区。滚出去。}
### {119}{}{Ar-r-r! (grinning, waving his fists and backing away to the exit)}
{119}{}{Ar-r-r！（咧嘴笑着，挥舞着拳头，退向出口）}
### {120}{}{Yes, right outside. And don't come back, morons...}
{120}{}{是的，就在外面。别回来了，白痴...}
### {121}{}{Guys, here are 100 caps for you. Just don't touch us, okay?}
{121}{}{伙计们，给你们100个瓶盖。别碰我们，好吗？}
### {122}{}{You see. I just needed MOTIVATION. See you next month, morons.}
{122}{}{你看。我只是需要激励。下个月见，白痴们。}
### {123}{}{Yes, uh, bye...}
{123}{}{是的，呃，再见...}
