### {100}{}{You have a contact in front of you.}
{100}{}{你面前有一个联系人。}
### {101}{}{You see a man with a knife in his side. He won't last long.}
{101}{}{你看到一个男人身边拿着一把刀。他活不了多久。}
### {102}{}{You see a wounded man. He barely hobbles, clutching his wounded side.}
{102}{}{你看到一个受伤的人。他几乎一瘸一拐地抓着受伤的一侧。}
### {103}{}{...Bruce's mercenaries... they attacked...}
{103}{}{…布鲁斯的雇佣兵...他们袭击了...}
### {104}{}{I was already desperate, I thought I was going to die. Thanks, Doc.}
{104}{}{我已经绝望了，我以为我快要死了。谢谢，医生。}

### {110}{}{...I'm hurt...}
{110}{}{…我受伤了...}
### {111}{}{...Ah-h... how painful...}
{111}{}{…啊…多么痛苦...}
### {112}{}{...C-save...}
{112}{}{…C-保存...}
### {113}{}{...I'll tell you everything, just help...}
{113}{}{…我会告诉你一切，只要帮忙...}
### {114}{}{...The Ooni attacked... they were waiting for us...}
{114}{}{Ooni攻击了...他们在等我们...}
### {115}{}{Help me!}
{115}{}{帮帮我！}
### {116}{}{Okay... okay... I'll say...}
{116}{}{可以可以我会说...}
### {117}{}{...They were Bruce's mercenaries...}
{117}{}{…他们是布鲁斯的雇佣兵...}
### {118}{}{...They grabbed it... cardinal... and...}
{118}{}{…他们抓住了…红衣主教...和}
### {119}{}{...Ar-rh...}
{119}{}{…Ar-rh...}
### {120}{}{Sorry, buddy, but there won't be time for help.}
{120}{}{抱歉，伙计，但没有时间寻求帮助了。}

### {200}{}{Thanks, Doc. I am eternally indebted to you.}
{200}{}{谢谢，医生。我永远感激你。}
### {201}{}{Who attacked you?}
{201}{}{谁袭击了你？}
### {202}{}{They were mercenaries from Bruce's guild. I think they were waiting for us. They grabbed the man I was supposed to meet, and they just stabbed me. They didn't finish me off, apparently they decided that I was already a dead man.}
{202}{}{他们是布鲁斯公会的雇佣兵。我想他们在等我们。他们抓住了我应该见面的那个人，然后刺伤了我。他们没有把我干掉，显然他们认为我已经死了。}
### {203}{}{How did you get into this mess in the first place?}
{203}{}{你一开始是怎么陷入这种混乱的？}
### {204}{}{Listen, I'm just an unemployed resident of the city. They asked me to take the note and give it to them. That's all. I don't know anything else.}
{204}{}{听着，我只是这个城市的一个失业居民。他们让我把纸条拿给他们。仅此而已。我什么都不知道。}
### {205}{}{There are no easy bottlecaps. Remember that. And now it's time for me to visit the mercenary guild.}
{205}{}{没有容易的瓶颈。记住这一点。现在是我参观雇佣兵公会的时候了。}
### {206}{}{I'm really sorry, buddy. You're just unlucky. Bye.}
{206}{}{我真的很抱歉，伙计。你只是运气不好。再见}
### {207}{}{Bye.}
{207}{}{再见}
