### {100}{}{Here is a fighter.}
{100}{}{这是一个战士。}
### {101}{}{You see an arena fighter. It looks like he overdid it in training.}
{101}{}{你看到一个竞技场斗士。看起来他在训练中做得太过火了。}
### {102}{}{You see an arena fighter. He looks cheerful.}
{102}{}{你看到一个竞技场斗士。他看起来很高兴。}
### {103}{}{Thanks, Doc, that's much better}
{103}{}{谢谢，医生，这样好多了}

### {110}{}{*Groan*}
{110}{}{*Groan*}
### {111}{}{It hurts}
{111}{}{很疼}
### {112}{}{Uv...}
{112}{}{Uv。。。}
### {113}{}{*Cough-cough*}
{113}{}{*咳嗽*}
### {114}{}{Um-m-m...}
{114}{}{嗯。。。}
### {115}{}{Filth...}
{115}{}{污物}
### {116}{}{Not another step into the ring.}
{116}{}{别再踏入拳击场了。}
### {117}{}{Where is this damn pusher?}
{117}{}{这个该死的推手在哪里？}
### {118}{}{I need anesthesia.}
{118}{}{我需要麻醉。}
### {119}{}{It's getting worse every hour.}
{119}{}{情况每小时都在恶化。}

### {150}{}{Broken in the ring.}
{150}{}{戒指坏了。}
### {151}{}{As you can see, I'm dying here.}
{151}{}{正如你所看到的，我在这里快要死了。}
### {152}{}{The last fight turned out to be difficult.}
{152}{}{最后一场比赛结果很艰难。}
### {153}{}{I think I got a concussion.}
{153}{}{我想我得了脑震荡。}
### {154}{}{I need a doctor...}
{154}{}{我需要一个医生。。。}
### {155}{}{Do you have painkillers?}
{155}{}{你有止痛药吗？}
### {156}{}{Pusher, bitch, can't get a stimpack.}
{156}{}{Pusher，婊子，拿不到刺激包。}
### {157}{}{These fights are exhausting.}
{157}{}{这些打斗让人筋疲力尽。}
### {158}{}{*Moans in response, clutching his head*}
{158}{}{*Moans抓着他的头回应道*}
### {159}{}{Um-m-m... My head hurts!}
{159}{}{嗯。。。我的头疼！}

### {170}{}{Thank you for saving me.}
{170}{}{谢谢你救了我。}
### {171}{}{If it wasn't for you, I could have died.}
{171}{}{如果不是你，我可能已经死了。}
### {172}{}{Who taught you first aid?}
{172}{}{谁教你急救的？}
### {173}{}{What luck that you're around.}
{173}{}{你真幸运。}
### {174}{}{Many of my friends could have survived if you were around.}
{174}{}{如果你在我身边，我的许多朋友都可以活下来。}
### {175}{}{I hope you're not going to go to the ring?}
{175}{}{我希望你不要去拳击场？}
### {176}{}{You're going to patch me up after the next fight, aren't you?}
{176}{}{下次打架后你要给我打补丁，是吗？}
### {177}{}{Another fight? Why not!}
{177}{}{又打架了？为什么不呢？}
### {178}{}{Your help came in very handy.}
{178}{}{你的帮助派上了用场。}
### {179}{}{Now I'm going to get back in the ring.}
{179}{}{现在我要重返赛场了。}
