### {100}{}{Here is a squatter.}
{100}{}{这是一个擅自占用者。}
### {101}{}{You see a dirty man in rags. He smells like it.}
{101}{}{你看到一个穿着破烂的脏男人。他闻起来很香。}

#Floating replicas
### {110}{}{Eh? What is it?}
{110}{}{呃？它是什么？}
### {111}{}{Do you hear?}
{111}{}{你听到了吗？}
### {112}{}{I smell pureskins. Do we have guests?}
{112}{}{我闻到了纯皮的味道。我们有客人吗？}
### {113}{}{Looks like we have new tourists.}
{113}{}{看来我们有新游客了。}
### {114}{}{It's not rat season yet.}
{114}{}{现在还不是老鼠季节。}
### {115}{}{We need to check the rat traps.}
{115}{}{我们需要检查捕鼠器。}
### {116}{}{The skin is shedding again.}
{116}{}{皮肤又开始脱落了。}
### {117}{}{Uv. I need to empty my stomach...}
{117}{}{Uv。我需要排空我的胃...}
### {118}{}{*Lazily itching*}
{118}{}{*懒痒*}
### {119}{}{*Cough-cough-cough*}
{119}{}{*咳嗽咳嗽*}

#Response remarks

#- GG with tinker glasses
### {130}{}{The right decision. Keep your eyes peeled in those glasses of yours.}
{130}{}{正确的决定。戴上你的眼镜，眼睛要擦亮。}
### {131}{}{I would have such glasses - I wouldn't have broken my leg twice last week.}
{131}{}{我会有这样的眼镜——我上星期不会摔断两次腿。}
### {132}{}{If you live in sewers like we do, then you won't need glasses.}
{132}{}{如果你像我们一样生活在下水道里，那么你就不需要眼镜了。}
### {133}{}{Live here for a while - you'll get used to the dark too.}
{133}{}{在这里住一段时间，你也会习惯黑暗的。}
### {134}{}{Can you look through your clothes with those glasses of yours?}
{134}{}{你能用你的眼镜透视一下你的衣服吗？}

#- GG sneaks
### {135}{}{Why are you sneaking around?}
{135}{}{你为什么偷偷摸摸？}
### {136}{}{Hiding from someone?}
{136}{}{躲着别人？}
### {137}{}{Yeah, merge with the wall. But I can still see you.}
{137}{}{是的，和墙融合。但我仍然可以看到你。}
### {138}{}{Do you always move like this?}
{138}{}{你总是这样动吗？}
### {139}{}{Damn drunk tourists.}
{139}{}{该死的醉酒游客。}

#- Common phrases
### {150}{}{Great.}
{150}{}{太棒了}
### {151}{}{What are you looking for in the dungeon, handsome?}
{151}{}{你在地牢里找什么，帅？}
### {152}{}{The new guy? Okay, I don't mind.}
{152}{}{那个新人？好吧，我不介意。}
### {153}{}{Lost? The city is above.}
{153}{}{迷路的城市在上面。}
### {154}{}{It's not often that tourists come down to us.}
{154}{}{很少有游客来找我们。}

### {155}{}{It's not bad here. The truth is true.}
{155}{}{这里还不错。事实是真的。}
### {156}{}{It is customary for us to share food for dating.}
{156}{}{我们约会时分享食物是一种习惯。}
### {157}{}{Shh! Speak softly.}
{157}{}{嘘！说话轻声细语。}
### {158}{}{Do you hear? It breathes the city above.}
{158}{}{你听到了吗？它呼吸着上面的城市。}
### {159}{}{It's usually quiet and peaceful here... until someone from above comes down here.}
{159}{}{这里通常很安静...直到有人从上面下来。}

### {160}{}{Hello.}
{160}{}{你好}
### {161}{}{What are you looking for in the dungeon, beauty?}
{161}{}{美女，你在地牢里找什么？}
### {162}{}{New girl? Okay, I don't mind.}
{162}{}{新来的女孩？好吧，我不介意。}
### {163}{}{Lost? The city is above.}
{163}{}{迷路的城市在上面。}
### {164}{}{It's not often that tourists come down to us.}
{164}{}{很少有游客来找我们。}
