### {102}{}{Admission received.}
{102}{}{已入院。}
### {103}{}{Only silence responds to your call signs.}
{103}{}{只有沉默才能回应你的呼号。}
### {104}{}{You press the buttons, but nothing happens. This intercom doesn't seem to be working.}
{104}{}{你按下按钮，但什么也没发生。这个对讲机好像坏了。}
### {105}{}{It won't help here.}
{105}{}{这对这里没有帮助。}
### {106}{}{No one answers your call signs.}
{106}{}{没有人接你的呼号。}

### {200}{}{You press the buttons, but nothing happens.}
{200}{}{你按下按钮，但什么也没发生。}
### {201}{}{Hey, is anyone home?}
{201}{}{嘿，有人在家吗？}
### {202}{}{Only silence answers your call.}
{202}{}{只有沉默才能回应你的呼唤。}
### {203}{}{Leave.}
{203}{}{离开}
### {204}{}{[CHEAT: open]}
{204}{}{[CHEAT：打开]}
### {205}{}{(You hear a click and the door opens)}
{205}{}{（你听到咔嗒一声，门就开了）}
### {206}{}{It looks like taciturn guys are sitting there...}
{206}{}{看起来沉默寡言的家伙坐在那里...}
### {207}{}{I'm from the Rangers. Here are my call signs.}
{207}{}{我是游骑兵队的。这是我的呼号。}
### {208}{}{Prior Mathias sent me to help the Liberation Party.}
{208}{}{马西亚斯派我去帮助解放党。}
