### {102}{}{It won't help here.}
{102}{}{这对这里没有帮助。}

### {110}{}{This generator provides electricity to the entire cathedral.}
{110}{}{这台发电机为整个大教堂供电。}
### {111}{}{This generator is supposed to provide electricity to the entire cathedral, but now it is disconnected from the mains.}
{111}{}{这台发电机本应为整个大教堂供电，但现在却断开了电源。}
### {112}{}{You have turned off the lighting within the cathedral.}
{112}{}{你已经关了大教堂的灯。}
### {113}{}{You have returned the lighting to the cathedral.}
{113}{}{你已经把灯还给了大教堂。}
