### {100}{}{This is the Adviser's computer.}
{100}{}{这是顾问的电脑。}
### {101}{}{Here is a powerful computer with a slot for an access card.}
{101}{}{这是一台功能强大的电脑，里面有一个门禁卡插槽。}

#Dialog
### {200}{}{Enter the command.}
{200}{}{输入命令。}
### {201}{}{End session.}
{201}{}{结束会话。}
### {202}{}{Back.}
{202}{}{返回}

### {210}{}{Alarm cancellation.}
{210}{}{警报取消。}
### {211}{}{The alarm is disabled.}
{211}{}{警报被禁用。}
### {212}{}{Disable traps in the corridor.}
{212}{}{禁用道路中的陷阱。}
### {213}{}{The traps are deactivated.}
{213}{}{陷阱已停用。}

### {220}{}{Sabotage in Flagstaff.}
{220}{}{弗拉格斯塔夫大屠杀。}
### {221}{}{(Flagstaff's agents report a sabotage in a uranium mine. Presumably, the sabotage was committed by prisoners. In any case, we should reconsider our policy regarding this colony and Mr. Faber's methods.)}
{221}{}{（弗拉格斯塔夫的特工报告称，一座铀矿遭到蓄意破坏。据推测，蓄意破坏是囚犯所为。无论如何，我们应该重新考虑我们对这个殖民地的政策和法伯先生的方法。）}

### {230}{}{Old report on the Phoenix coup.}
{230}{}{关于凤凰城政变的旧报道。}
### {231}{}{(The adviser describes the details of the coup that happened a few years ago in Phoenix. It follows from the records that a certain third force established the power of the cult of Fire in the city, putting the people he needed. The goals of this unnamed organization are to form a society to create a subsequent raw materials and reconstruction base and to provide the general staff with basic resources. In other words, the cult of Fire is a puppet in someone else's game..)}
{231}{}{（这位顾问描述了几年前发生在凤凰城的政变的细节。从记录中可以看出，某个第三方势力在该市建立了火崇拜的力量，安置了他需要的人。这个未命名的组织的目标是组建一个社会，创建一个后续的原材料和重建基地，并为总参谋部提供基本的资源。）资源。换句话说，对火的崇拜是别人游戏中的木偶。）}
### {232}{}{Financial report.}
{232}{}{财务报告。}
### {233}{}{Thanks to our systematic work, a new bottle cap currency borrowed from the Hub has firmly established itself in Phoenix. But since residents are not used to the currency as such, it took several years to instill this idea in the population and stabilize the exchange rate of caps. I attach to the report statistics and analysis of financial processes in the city and prospects for the development of the cap currency in the future.}
{233}{}{由于我们的系统工作，从Hub借来的一种新的瓶盖货币在凤凰城站稳了脚跟。但由于居民不习惯这种货币，他们花了几年时间才向民众灌输这一理念，并稳定了上限汇率。我在报告中附上了该市金融流程的统计和分析，以及未来上限货币的发展前景。}

### {240}{}{Report on the status of the cult.}
{240}{}{关于邪教状况的报告。}
### {241}{}{...Conclusion 1. As expected, the cult of Fire created on the model of the Chad Cathedral showed high results. He captured almost all spheres of life in the city and firmly established himself in his position. The population of Phoenix either remains loyal to the fire worshippers, or is afraid of them. Thus, we can flexibly change the local society at our discretion by the Followers of Fire. Although the rebels hiding in the sewers are still causing problems, they do not pose a significant threat to our plan.}
{241}{}{…结论1。不出所料，在乍得大教堂模型上创建的火崇拜取得了很高的效果。他几乎占领了这座城市的所有生活领域，并牢牢地确立了自己的地位。凤凰城的居民要么仍然忠于拜火者，要么害怕他们。因此，我们可以通过火的追随者来灵活地改变当地社会。尽管躲在下水道里的叛军仍在制造问题，但他们并没有对我们的计划构成重大威胁。}
### {242}{}{Read more.}
{242}{}{阅读更多。}
### {243}{}{Conclusion 2. We manage to remain incognito, limited only to a small circle of selected persons. The cult leader is ready to follow our instructions without question, regardless of his own ambitions. He is aware of his puppet nature and is ready to reckon with it, but he does not suspect our plans. Presumably, this relationship will continue for the next 3-4 years, after which it will be useful to eliminate Aaron and put a new person.}
{243}{}{结论2。我们设法保持隐姓埋名，只限于选定的一小群人。邪教领袖准备毫无疑问地听从我们的指示，不管他自己的野心如何。他意识到自己的木偶本性，并准备考虑一下，但他并不怀疑我们的计划。据推测，这种关系将持续3-4年，之后淘汰亚伦并换一个人会很有用。}
### {244}{}{Read more.}
{244}{}{阅读更多。}
### {245}{}{Conclusion 3. I think that the cult is ready to expand. We are starting the expansion of the ideas of the Sacred Fire in San Brahmin with the aim of organizing a new raw materials and transport colony there.}
{245}{}{结论3。我认为邪教已经准备好扩大了。我们正在圣婆罗门开始扩展圣火的理念，目的是在那里组织一个新的原材料和运输殖民地。}

### {250}{}{GECK search report.}
{250}{}{GECK搜索报告。}
### {251}{}{Information about the current Generator of the Eden Tabernacles is still missing, the search continues. I attach the expedition reports.}
{251}{}{搜寻工作仍在继续，目前有关伊甸园避难所发电机的信息仍然下落不明。我附上探险队的报告。}
### {252}{}{Expedition to the Vault 26.}
{252}{}{远征金库26。}
### {253}{}{The expedition to Vault 26 gave a negative result. The Vault was destroyed by a nuclear strike. Excavation is impossible.}
{253}{}{对26号金库的探险给出了否定的结果。保险库被核打击摧毁了。挖掘是不可能的。}
### {254}{}{Expedition to the Vault 27.}
{254}{}{远征金库27。}
### {255}{}{The expedition to Vault 27 could not confirm the presence of the GECK. Long-term excavations are currently underway. It is confirmed that the Vault has been looted and is in poor condition. Some equipment was taken out by convoy to Two-Sun, the list is attached. I also attach copies of the expedition reports.}
{255}{}{27号金库的探险队无法确认GECK的存在。目前正在进行长期挖掘。经证实，该金库已被洗劫一空，目前状况不佳。一些设备是由车队带到“二太阳”的，名单附后。我还附上探险报告的副本。}
### {256}{}{Remark.}
{256}{}{评论}
### {257}{}{There is information that the population of Phoenix largely consists of descendants of the inhabitants of refuge 27. And there is also a legend about the discord of their ancestors who went different ways. It can be assumed that one of the groups of immigrants took the GECK with them. This hypothesis should be worked out if we don't find the device.}
{257}{}{有资料表明，菲尼克斯的人口主要由27号避难所居民的后代组成。还有一个传说是关于他们的祖先的不和，他们走了不同的道路。可以假设，其中一组移民携带了GECK。如果我们找不到这个装置，这个假设就应该成立。}
### {258}{}{Search for the coordinates of the Vault 27.}
{258}{}{搜索Vault 27的坐标。}
### {259}{}{(You enter the coordinates in your Pip-Boy)}
{259}{}{（你在你的皮普男孩里输入坐标）}

### {260}{}{Report on the nuclear bomb project.}
{260}{}{关于核弹项目的报告。}
### {261}{}{At the moment, the project is 92% ready. We are expecting new mechanical components from Two-Sun workshops. Progress is hindered by the lack of scientific personnel and the slowness of uranium production in the Flagstaff mines. The fire worshippers still have no idea about the true customer and the purpose of the bomb.}
{261}{}{目前，该项目已准备就绪92%。我们期待来自两个太阳车间的新机械部件。由于缺乏科学人员和弗拉格斯塔夫矿的铀生产缓慢，进展受到阻碍。火灾崇拜者仍然不知道真正的顾客和炸弹的目的。}
