### {100}{}{This is Cadet Burke.}
{100}{}{我是伯克学员。}
### {101}{}{You see a skinny and very inexperienced cadet. It is not surprising that he was placed on this post.}
{101}{}{你看到的是一个骨瘦如柴、经验不足的学员。他被安排担任这一职务并不奇怪。}

### {200}{}{ (in front of you is a young man with a thin neck; looking at you, he cannot cross eyes in any way and every minute makes a short strained grin) I wish you good health! What can I do for you?}
{200}{}{（你面前是一个脖子很细的年轻人；看着你，他无论如何都不会斜视，每分钟都会咧嘴笑）祝你身体健康！我能为你做什么？}
### {201}{}{What is this place?}
{201}{}{这是什么地方？}
### {202}{}{This is an information center... more precisely, this is the reception room, more precisely... (straightens up) Here we discuss business with strangers, sir!}
{202}{}{这是一个信息中心...更确切地说，这是接待室，更准确地说...（挺直腰杆）先生，我们在这里和陌生人讨论生意！}
### {1202}{}{This is an information center... more precisely, this is the reception room, more precisely... (straightens up) Here we discuss business with strangers, ma'am!}
{1202}{}{这是一个信息中心...更确切地说，这是接待室，更准确地说...（挺直腰杆）在这里我们和陌生人讨论生意，女士！}

### {203}{}{Who is "we"?}
{203}{}{谁是“我们”？}
### {204}{}{( makes a confused face) Rangers... That is... (straightens up) Cadet Burke at your service! If you need a senior ranger, you'll have to make an appointment.}
{204}{}{（一脸困惑）游骑兵队...那是…（挺直腰杆）伯克学员为你服务！如果你需要一名资深护林员，你必须预约。}
### {205}{}{And who is behind this door?}
{205}{}{谁在这扇门后面？}
### {206}{}{Field Commander Helford... But you haven't made an appointment yet, so I can't...}
{206}{}{战地指挥官赫尔福德...但是你还没有预约，所以我不能...}
### {207}{}{Great, maybe he can help me.}
{207}{}{太好了，也许他能帮我。}
### {208}{}{Hey, wait!}
{208}{}{嘿，等等！}
### {209}{}{[Leave]}
{209}{}{[离开]}

### {210}{}{I need your main one.}
{210}{}{我需要你的主菜。}
### {211}{}{The General? Oh no, you can't go to the general in any way.}
{211}{}{将军？哦，不，你无论如何都不能去找将军。}
### {212}{}{And who can I go to?}
{212}{}{我可以去找谁？}
### {213}{}{Field Commander Helford is behind this door... But you have to make an appointment, I can't let in...}
{213}{}{战地指挥官赫尔福德在这扇门后面...但你必须预约，我不能让...}
### {214}{}{Great, maybe he can help me.}
{214}{}{太好了，也许他能帮我。}
### {215}{}{Hey, wait!}
{215}{}{嘿，等等！}
### {216}{}{[Leave]}
{216}{}{[离开]}

### {220}{}{Just don't cause me any problems.}
{220}{}{只是不要给我带来任何问题。}
### {221}{}{I won't.}
{221}{}{我不会的。}
### {222}{}{Hi, uh, congratulations on the promotion. And I still have to serve for years to the rank of ranger.}
{222}{}{嗨，祝贺你升职。我还得服役多年才能成为护林员。}
### {223}{}{Bye.}
{223}{}{再见}
