### {100}{}{Here is a handyman.}
{100}{}{这是一个杂工。}
### {101}{}{You see an ordinary inhabitant from the wasteland.}
{101}{}{你看到一个来自荒原的普通居民。}

#The first dialog
### {200}{}{ (in front of you is a young man in dirty clothes; he wearily raises a dissatisfied look at you) What do you want?}
{200}{}{（你面前是一个穿着脏衣服的年轻人，他疲惫地向你投来不满的目光）你想要什么？}
### {201}{}{Are you not a Ranger?}
{201}{}{你不是游骑兵吗？}
### {202}{}{No, of course not. I don't give a shit about these rangers. But they give protection to our community. They make me work as a payment.}
{202}{}{不，当然不是。我一点也不在乎这些护林员。但他们为我们的社区提供了保护。他们让我工作作为报酬。}
### {203}{}{I see. Well, I won't distract you.}
{203}{}{我明白了。好吧，我不会分散你的注意力。}

#Repeat dialog
### {210}{}{You again?}
{210}{}{你又来了？}
### {211}{}{Bye.}
{211}{}{再见}
### {212}{}{Can you refuse to perform your services?}
{212}{}{你能拒绝提供服务吗？}
### {213}{}{It's unlikely. If the rangers get angry, they will take all our supplies from us and stop protecting us from bandits and mutants. Therefore, we have to fulfill all their whims. And the list of works is quite long.}
{213}{}{这不太可能。如果护林员生气了，他们会拿走我们所有的补给，停止保护我们免受土匪和变种人的袭击。因此，我们必须满足他们所有的奇思妙想。作品的清单相当长。}
### {214}{}{Tell us about your community.}
{214}{}{告诉我们您所在的社区。}
### {215}{}{We live near an Aqueduct on the Colorado shore. We survive at the expense of fish and small game. I don't know what else to tell you.}
{215}{}{我们住在科罗拉多海岸的一个渡槽附近。我们以捕鱼和小猎物为代价生存。我不知道还能告诉你什么。}
### {216}{}{What do you think about the Rangers?}
{216}{}{你觉得游骑兵队怎么样？}
### {217}{}{When necessary, they will become the only hope for salvation. But the rest of the time they just parasitize our community, taking the catch and forcing them to work for their own benefit.}
{217}{}{在必要的时候，他们将成为拯救的唯一希望。但在剩下的时间里，它们只是寄生在我们的社区，抓住猎物，强迫它们为自己的利益工作。}
### {218}{}{Do you know a way to get into the base?}
{218}{}{你知道进入基地的方法吗？}
### {219}{}{I don't know. Excursions for tourists are not taken there. You need to do the Rangers a good service or have a really good reason.}
{219}{}{我不知道。那里不允许游客游览。你需要给流浪者队一个好的服务，或者有一个很好的理由。}
