### {100}{}{Here is Paladin Latham.}
{100}{}{这是圣骑士莱瑟姆。}
### {101}{}{You see a strong unshaven man.}
{101}{}{你看到一个没有刮胡子的强壮男人。}
### {102}{}{Well, no, not now.}
{102}{}{不，现在不行。}
### {103}{}{?}
{103}{}{？}

### {200}{}{Wait. This is a closed area, civilians are not allowed to enter the base.}
{200}{}{等待这是一个封闭区域，平民不得进入基地。}
### {201}{}{Civilian? Are you some kind of army?}
{201}{}{平民你是某种军队吗？}
### {202}{}{No. We are an ancient order called the Brotherhood of Steel. Although we do have military discipline at our base.}
{202}{}{不，我们是一个古老的骑士团，叫做钢铁兄弟会。尽管我们的基地确实有军事纪律。}
### {203}{}{I see. And who are you?}
{203}{}{我明白了。你是谁？}
### {204}{}{It's amazing. And with whom do I have the honor to speak?}
{204}{}{太神奇了。我有幸与谁交谈？}
### {205}{}{I am Paladin Latham, chief of Patrol. Any more questions?}
{205}{}{我是帕拉丁·莱瑟姆，巡逻队队长。还有问题吗？}
### {206}{}{Not at all, sir.}
{206}{}{一点也不，先生。}
### {207}{}{Oh, I have a lot of questions. But you still won't answer them.}
{207}{}{哦，我有很多问题。但你仍然不会回答他们。}
### {208}{}{Okay. Now tell me, amigo, what brought you to us?}
{208}{}{可以现在告诉我，朋友，是什么把你带到我们这里来的？}
### {209}{}{I'm from a village in the north. We were attacked by slavers, and now I'm trying to save the village...}
{209}{}{我来自北方的一个村庄。我们被奴隶贩子袭击了，现在我正试图拯救这个村庄...}
### {210}{}{That's exactly what I need. My village was enslaved by slavers, and I'm trying to save it...}
{210}{}{这正是我所需要的。我的村庄被奴隶贩子奴役，我正在努力拯救它...}
### {211}{}{I'm sorry, but I won't bother the general about one village. We just don't have time for this.}
{211}{}{对不起，我不会为一个村庄的事打扰将军。我们只是没有时间。}
### {212}{}{No, you don't understand. You are the slavers. I'll destroy your whole gang!}
{212}{}{不，你不明白。你们是奴隶主。我要摧毁你的整个帮派！}
### {213}{}{What's going on? What's the fuss?}
{213}{}{怎么回事？有什么大惊小怪的？}
### {214}{}{I see. I see they won't help me here. Permission to go, paladin?}
{214}{}{我明白了。我看他们在这里不会帮我的。允许去吗，圣骑士？}
### {215}{}{You again? I told you - we don't have time to deal with your village. Sorry, but we don't have time for this yet.}
{215}{}{你又来了？我告诉过你，我们没有时间和你的村子打交道。对不起，我们还没有时间。}
### {216}{}{There is an enemy army coming from the south, mutants in the west, and a complete mess in the east. We recently lost a squad in the north and can't even send a rescue team there.}
{216}{}{有一支来自南方的敌军，西部是变种人，东部是一片混乱。我们最近在北方失去了一支队伍，甚至不能派救援队去那里。}
### {217}{}{And if I help you, will you let me see the general?}
{217}{}{如果我帮助你，你会让我去见将军吗？}
### {218}{}{Can you help me? Are you for us? Haha, the peasant wants to help the Brotherhood! Did you guys hear that? Okay, let's see what happens.}
{218}{}{你能帮我吗？你支持我们吗？哈哈，农民想帮助兄弟会！你们听到了吗？好吧，让我们看看会发生什么。}
### {1218}{}{Can you help me? Are you for us? Haha, the peasant woman wants to help the Brotherhood! Did you guys hear that? Okay, let's see what happens.}
{1218}{}{你能帮我吗？你支持我们吗？哈哈，农妇想帮助兄弟会！你们听到了吗？好吧，让我们看看会发生什么。}
### {219}{}{So what's up with the squad?}
{219}{}{那么球队怎么了？}
### {220}{}{There are ruins of a big city in the north. We call them Infernos. A convoy was coming through the ruins to us. But the connection was interrupted, now we don't know anything about the fate of the squad.}
{220}{}{北方有一座大城市的废墟。我们称他们为地狱。一支车队穿过废墟向我们驶来。但连接被中断了，现在我们对这支队伍的命运一无所知。}
### {221}{}{I see. Anything else?}
{221}{}{我明白了。还有别的吗？}
### {222}{}{Go there and find out what happened to our brothers. But be careful, the scribes say there are places with high levels of radiation.}
{222}{}{去那里看看我们兄弟发生了什么事。但要小心，抄写员说有些地方的辐射水平很高。}
### {223}{}{Good. I'll do it.}
{223}{}{好的我会做的。}
### {224}{}{Agreed. But you can't get away from me, Paladin.}
{224}{}{同意。但是你不能离开我，圣骑士。}
### {225}{}{M-mutants... Ugh! When will you all rest?}
{225}{}{M-突变体...啊！你们什么时候休息？}
### {226}{}{Give me a minute, boss, I'm not doing anything wrong.}
{226}{}{给我一分钟，老板，我没有做错什么。}
### {227}{}{Oh, it won't be soon, my pale-skinned friend...}
{227}{}{哦，不会很快的，我苍白皮肤的朋友...}

### {230}{}{What do you need?}
{230}{}{你需要什么？}
### {231}{}{Nothing. Goodbye.}
{231}{}{没有什么再见}
### {232}{}{What do you need, warrior?}
{232}{}{你需要什么，战士？}

### {240}{}{I need to know more about Inferno.}
{240}{}{我需要了解更多关于地狱的信息。}
### {241}{}{I don't have much information. Scribes consider these ruins lifeless and warn of radiation near the site of a nuclear explosion.}
{241}{}{我没有太多信息。抄写员认为这些废墟没有生命，并警告核爆炸现场附近有辐射。}
### {242}{}{What can you say about the convoy?}
{242}{}{关于车队你能说些什么？}
### {243}{}{Several members of the Brotherhood were carrying important cargo from California. They should have been in touch a long time ago.}
{243}{}{兄弟会的几名成员正从加利福尼亚运送重要货物。他们早就该联系了。}
### {244}{}{Thank you, that's enough.}
{244}{}{谢谢，够了。}
### {245}{}{Indeed - a little information.}
{245}{}{确实——一点信息。}
### {246}{}{Let me take a little more of your time, paladin.}
{246}{}{让我多花点时间，圣骑士。}
### {247}{}{I know what happened in Inferno...}
{247}{}{我知道地狱里发生了什么...}
### {248}{}{...The scribes were telling the truth - this is a CURSED place. Thank you. You need to talk to our general.}
{248}{}{……抄写员说的是实话——这是一个封闭的地方。非常感谢。你需要和我们的将军谈谈。}
### {249}{}{By the general himself?}
{249}{}{将军本人？}
### {250}{}{He'll be interested in your story. I'll tell the guards to let you on the ship.}
{250}{}{他会对你的故事感兴趣的。我会告诉警卫让你上船。}
### {251}{}{Excellent.}
{251}{}{杰出的}
### {252}{}{That would be right away.}
{252}{}{那就马上。}
### {253}{}{Okay, slow down. WHERE did you get this power armor from?}
{253}{}{好的，慢一点。你从哪里得到的力量盔甲？}
### {254}{}{It was a terrible place. Well, you know, dead people on the streets, ruins all around...}
{254}{}{那是一个可怕的地方。嗯，你知道，街上的死人，周围的废墟...}
### {255}{}{It looks like a description of the Inferno through which our lost convoy passed. Have you come across people who carried this armor?}
{255}{}{这看起来像是对我们迷路的车队经过的地狱的描述。你有没有遇到过携带这件盔甲的人？}
### {256}{}{Now I'll tell you what I know...}
{256}{}{现在我告诉你我所知道的...}
### {257}{}{I won't tell you anything. This is my trophy, and I won't give it up.}
{257}{}{我什么都不告诉你。这是我的奖杯，我不会放弃。}

### {260}{}{Is there any other way I can help the Brotherhood?}
{260}{}{我还有其他办法可以帮助兄弟会吗？}
### {261}{}{Did you say something about an enemy army?}
{261}{}{你说了关于敌军的事吗？}
### {262}{}{Yes, army units are pulling together from the south to the Mexican border. We don't know much about the new enemy yet. Even the location of the enemy general staff is unknown.}
{262}{}{是的，军队正在从南部向墨西哥边境集结。我们对新敌人还不太了解。甚至连敌人总参谋部的位置都不知道。}
### {263}{}{But in the south there is an endless desert. Where would a military base come from there?}
{263}{}{但在南方有一片一望无际的沙漠。军事基地从哪里来？}
### {264}{}{It is this desert that keeps the enemy army from occupying Arizona. While holding back.}
{264}{}{正是这片沙漠阻止了敌军占领亚利桑那州。一边退缩。}
### {265}{}{I hope you can handle this threat. Adios.}
{265}{}{我希望你能处理这个威胁。再见。}
### {266}{}{I can find out. I've always wanted to visit those parts.}
{266}{}{我可以找到。我一直想参观那些地方。}
### {267}{}{I can scout the southern lands if it helps.}
{267}{}{如果有帮助的话，我可以侦察南方的土地。}
### {268}{}{We sent several scouts to the south, but none of them returned. Still want to take a chance? Then go ahead. The brotherhood will pay for information about the objectives of the Mexican army.}
{268}{}{我们派了几个侦察兵去南方，但他们都没有回来。还想冒险吗？那就继续吧。兄弟会将为有关墨西哥军队目标的信息付费。}
### {269}{}{I'll be back when I find out something.}
{269}{}{我发现什么事就会回来。}
### {270}{}{There is a Mexican army fort in Hermosillo...}
{270}{}{在赫莫西洛有一座墨西哥军队的堡垒...}
### {271}{}{...Great job! Your intelligence will give us an advantage over the enemy if it comes to an offensive.}
{271}{}{…干得好！如果进攻的话，你的智慧会使我们比敌人更有优势。}
### {272}{}{Hermosillo is quite far across the desert. I doubt that the Mexicans will reach these places in the near future.}
{272}{}{赫莫西洛穿过沙漠很远。我怀疑墨西哥人能否在不久的将来到达这些地方。}
### {273}{}{I don't care why you need it. Just a quid pro quo.}
{273}{}{我不在乎你为什么需要它。只是交换条件。}
### {274}{}{Here, take the payment for the work. We value good scouts.}
{274}{}{给，拿着工钱。我们重视优秀的球探。}
### {275}{}{Thank you.}
{275}{}{非常感谢。}
### {276}{}{This loser claims that he owes his salvation to you. He wasn't much use. But what can you tell me?}
{276}{}{这个失败者声称他的救赎归功于你。他没什么用。但你能告诉我什么？}
### {277}{}{Jack said you need information about the Mexican army.}
{277}{}{杰克说你需要关于墨西哥军队的信息。}
### {278}{}{So did you manage to go there? And what did you find out?}
{278}{}{那你去那里了吗？你发现了什么？}
### {1278}{}{So did you manage to go there? And what did you find out?}
{1278}{}{那你去那里了吗？你发现了什么？}
### {279}{}{Honestly, nothing that would be useful to you. If I find myself there again, I will collect more detailed information.}
{279}{}{老实说，没有什么对你有用的。如果我再次发现自己在那里，我会收集更详细的信息。}

### {280}{}{There is a request. Take Novice Corwin on your next patrol.}
{280}{}{有一个请求。带着新手科温进行下一次巡逻。}
### {281}{}{Corwin? Why doesn't he apply himself?}
{281}{}{科温？他为什么不努力呢？}
### {282}{}{He's been begging for a shore leave ticket for a long time.}
{282}{}{他一直在乞求一张靠岸假机票。}
### {283}{}{Ah, that's the thing. No, we don't need ballast on the way. And even more so, I will not be convinced by the words of a crook like you.}
{283}{}{啊，就是这样。不，我们在路上不需要压载物。更重要的是，我不会被你这样的骗子的话所说服。}
### {284}{}{A crook, then? Okay...}
{284}{}{那是骗子吗？可以}
### {285}{}{Ah, that's the thing. No, we don't need ballast on the way. And your authority in this matter does not change anything. I don't know you well enough to answer your requests.}
{285}{}{啊，就是这样。不，我们在路上不需要压载物。你在这件事上的权威不会改变任何事情。我对你不够了解，不能回答你的要求。}
### {286}{}{You can understand...}
{286}{}{你可以理解...}
### {287}{}{Ah, that's the thing. Well, I listen to the requests of those who have shown themselves to be a worthy warrior. Tell Corwin I'll take him on patrol to Casa Nueva and back. It's not exactly a furlough, but it's enough for him to get some fresh air.}
{287}{}{啊，就是这样。好吧，我听取了那些表现出自己是一名有价值的战士的请求。告诉科温，我会带他去努瓦之家巡逻，然后再回来。这并不完全是休假，但对他来说，呼吸新鲜空气就足够了。}
### {288}{}{Thank you, Paladin Latham. You've been very helpful.}
{288}{}{谢谢你，圣骑士莱瑟姆。你帮了我很大的忙。}
### {289}{}{Here is a holo recording with the data that was stored in the computer of the General Staff. They're in Spanish.}
{289}{}{这是一份全息图记录，其中包含了总参谋部计算机中存储的数据。它们是西班牙语的。}

### {300}{}{Let me know what your service does?}
{300}{}{让我知道你的服务是什么？}
### {301}{}{This is a patrol service. We keep order in the neighborhood. Any more questions?}
{301}{}{这是一项巡逻服务。我们维持附近的秩序。还有问题吗？}
### {302}{}{No way, sir.}
{302}{}{不可能，先生。}
### {303}{}{Yes, let me ask you something?}
{303}{}{是的，让我问你一件事？}
### {304}{}{I understand that. But there's a desert all around. What order can be maintained here?}
{304}{}{我理解。但是周围都是沙漠。这里可以维持什么秩序？}
### {305}{}{First of all, we protect the caravan routes. There are fishing settlements on the coast under our protection. Sometimes requests come from Casa Nueva. And yes, even in such a wilderness there are bandits. You should always be on your guard.}
{305}{}{首先，我们保护商队的路线。在我们的保护下，海岸上有一些捕鱼定居点。有时请求来自Casa Nueva。是的，即使在这样的荒野中也有土匪。你应该时刻保持警惕。}
### {306}{}{I see.}
{306}{}{我明白了。}
### {307}{}{Interesting. Will you take me on patrol?}
{307}{}{有趣的你会带我去巡逻吗？}
### {308}{}{Taking a stranger on patrol is too dubious an idea. Even if your thoughts are pure.}
{308}{}{带一个陌生人去巡逻的想法太可疑了。即使你的思想是纯洁的。}
### {309}{}{Okay. Maybe you'll change your mind when I do something important.}
{309}{}{可以当我做一些重要的事情时，也许你会改变主意。}
### {310}{}{You probably need experienced mercenaries. You said yourself that there are not enough people.}
{310}{}{你可能需要有经验的雇佣兵。你自己说人不够。}
### {311}{}{Yes, but you are clearly not the level of fruit to fight shoulder to shoulder with you. Start with something simpler.}
{311}{}{是的，但你显然不是那种与你并肩作战的水果级别。从简单的事情开始。}
### {312}{}{Yes, but you... However, we really don't have enough people for one big operation.}
{312}{}{是的，但是你...然而，我们真的没有足够的人手来进行一次大手术。}
### {313}{}{Great. Tell me what's what.}
{313}{}{太棒了告诉我什么是什么。}
### {314}{}{Take me on patrol.}
{314}{}{带我去巡逻。}
### {315}{}{The General was talking about you. I will be glad if you help us in one difficult operation.}
{315}{}{将军在说你。如果你能在一次困难的手术中帮助我们，我将很高兴。}
### {316}{}{Sure. Tell me what's what.}
{316}{}{当然告诉我什么是什么。}
### {317}{}{Is there any other way I can help the Brotherhood?}
{317}{}{我还有其他办法可以帮助兄弟会吗？}
### {318}{}{After Hermosillo, I want to help the Brotherhood even more. Will you take me on patrol?}
{318}{}{在赫莫西洛之后，我更想帮助兄弟会。你会带我去巡逻吗？}
### {319}{}{Yes, we don't have enough people like you for one big operation.}
{319}{}{是的，我们没有足够的像你这样的人来做一次大手术。}
### {320}{}{Great. I'm listening carefully.}
{320}{}{太棒了我在认真听。}
### {321}{}{Bandits have been bothering us lately. They stuck to the main trade routes and local settlements. Recently they robbed one of our caravans, and this is no good at all.}
{321}{}{土匪最近一直在骚扰我们。他们坚守主要贸易路线和当地定居点。最近他们抢劫了我们的一辆大篷车，这一点都不好。}
### {322}{}{They don't know who they've contacted yet, Paladin Latham.}
{322}{}{他们还不知道他们联系过谁，圣骑士莱瑟姆。}
### {323}{}{They must be serious guys, since they robbed the Brotherhood caravan.}
{323}{}{他们一定是认真的家伙，因为他们抢劫了兄弟会的商队。}
### {324}{}{We tracked the attackers to one of their camps in the desert and want to visit them. It's time to pin the tail of these sons of bitches!}
{324}{}{我们追踪到了袭击者在沙漠中的一个营地，并想拜访他们。是时候钉住这些狗娘养的了！}
### {325}{}{Great. When are the fees?}
{325}{}{太棒了什么时候收费？}
### {326}{}{Go to the collection point, which I will indicate on the map. Field Commander Dobbs will meet you there and instruct you on the spot. And take care of your protection in advance. Good luck.}
{326}{}{去收集点，我会在地图上标明。多布斯中校会在那里迎接你，并在现场指导你。提前做好防护。祝你好运}
### {327}{}{Roger that. I'm leaving immediately.}
{327}{}{收到。我马上就走。}
### {1327}{}{The task is clear. I'm leaving immediately.}
{1327}{}{任务很明确。我马上就走。}
### {328}{}{Is it okay if they wait a bit? That's fine.}
{328}{}{他们等一下可以吗？没关系。}
### {329}{}{Take me on patrol, Paladin Latham.}
{329}{}{带我去巡逻，圣骑士莱瑟姆。}

### {330}{}{Here is my report on the raid on the bandit camp...}
{330}{}{这是我关于突袭土匪营地的报告...}
### {331}{}{...Very good. Obviously, it was just a small field camp. After the attack on the caravan, the bandits split up. The second group took the goods to their main base. Rescuing a caravan is an important mission, but it is even more important to get the stolen cargo.}
{331}{}{…非常好。很明显，这只是一个小的野外营地。商队遭到袭击后，匪徒们散开了。第二组把货物运到他们的主要基地。营救大篷车是一项重要任务，但找回被盗货物更为重要。}
### {332}{}{So there is another sortie ahead?}
{332}{}{那么前方还有一架飞机？}
### {333}{}{We don't know where the bandits' main base is. But during the operation, information appeared about a large outpost on the ruins of Kaborka. This outpost must be destroyed anyway. And at the same time you can get information about the location of the main base there.}
{333}{}{我们不知道土匪的主要基地在哪里。但在行动期间，出现了关于卡博卡废墟上一个大型前哨基地的信息。无论如何，这个前哨基地必须被摧毁。同时，你可以在那里获得主基地的位置信息。}
### {334}{}{So what are the instructions, sir?}
{334}{}{那么指示是什么，先生？}
### {335}{}{Go to Commander Dobbs and give my next order.}
{335}{}{去找多布斯指挥官，下达我的下一个命令。}
### {336}{}{Yes, Paladin Latham.}
{336}{}{是的，圣骑士莱瑟姆。}
### {337}{}{If there are no other leads, then it's worth taking the risk.}
{337}{}{如果没有其他线索，那么值得冒险。}
### {338}{}{Did I ask for your opinion? Ahem... Well, never mind. You're doing really well. It would be a little harder for us without you.}
{338}{}{我征求你的意见了吗？啊...好吧，没关系。你做得很好。没有你对我们来说会有点困难。}
### {339}{}{So what are the instructions, sir?}
{339}{}{那么指示是什么，先生？}
### {340}{}{...It turns out that the camp in Kaborka was organized only to attack our caravan routes. The main base of the bandits is in the mountains to the east. No wonder it took us so long to figure them out.}
{340}{}{……事实证明，在卡博卡的营地只是为了攻击我们的商队路线。土匪的主要基地在东边的山区。难怪我们花了这么长时间才弄清楚。}
### {341}{}{So are you going to attack their general staff?}
{341}{}{那么你打算攻击他们的总参谋部吗？}
### {342}{}{The General Staff? It's just a group of rural bandits. Call it a den or just a hole.}
{342}{}{总参谋部？这只是一群农村土匪。可以称之为巢穴或洞穴。}
### {343}{}{Acknowledged, sir.}
{343}{}{谢谢，先生。}
### {344}{}{Give the commander the order to attack. This time the operation will be harder than the previous ones. Let him gather the best guys. You, too, take your best weapons and armor. Good luck, soldier.}
{344}{}{命令指挥官进攻。这次的操作将比以前的操作更加困难。让他召集最优秀的人。你也要带上最好的武器和盔甲。祝你好运，士兵。}
### {345}{}{Yes, Paladin Latham.}
{345}{}{是的，圣骑士莱瑟姆。}
### {346}{}{...So we set up their main camp. The bandits were destroyed, the leaders were caught and put to death, the loot was returned to the order. Congratulations, warrior.}
{346}{}{…所以我们建立了他们的主要营地。土匪被消灭，首领被抓住并处死，战利品被归还给了骑士团。恭喜你，勇士。}
### {347}{}{Yes, the wastelands will remember this for a long time.}
{347}{}{是的，荒原会记住这一点很长一段时间。}
### {348}{}{It was a glorious day of victories! We have eradicated evil in these lands and once again showed the world our strength. After the defeat of the bandits, the roads will become safer, and the fame of the Brotherhood will spread further to the mainland. Thank you for your assistance.}
{348}{}{这是胜利的光辉日子！我们铲除了这些土地上的邪恶，再次向世界展示了我们的力量。土匪战败后，道路将变得更加安全，兄弟会的名声将进一步传播到大陆。感谢您的帮助。}
### {349}{}{I serve the Brotherhood of Steel!}
{349}{}{我为钢铁兄弟会服务！}
### {350}{}{I want to complain. I was excluded from the task force!}
{350}{}{我想抱怨。我被排除在工作组之外！}
### {351}{}{And rightly so. If not for your previous achievements, you would have been executed to the fullest extent of the law. And now do the most reasonable thing you can - disappear from our base.}
{351}{}{如果不是因为你之前的成就，你会被依法处决。现在做你能做的最合理的事——从我们的基地消失。}
### {352}{}{Yes, sir.}
{352}{}{是的，先生。}
### {353}{}{Gr-r!}
{353}{}{Gr-r！}
### {354}{}{I have bad news - Commander Dobbs died during the operation.}
{354}{}{我有个坏消息，多布斯指挥官在行动中牺牲了。}
### {355}{}{It's a bad thing. He was our best field commander. Besides, only he had a complete picture of what was happening, without him it would become much harder to defeat the bandits.}
{355}{}{这是一件坏事。他是我们最好的战地指挥官。此外，只有他对正在发生的事情有一个完整的了解，如果没有他，打败土匪将变得更加困难。}
### {356}{}{But what about the operation?}
{356}{}{但是手术呢？}
### {357}{}{We will have to suspend the operation and reorganize the combat personnel. If we need you, we'll call. In the meantime, you can be free.}
{357}{}{我们将不得不暂停行动并重组作战人员。如果我们需要你，我们会打电话的。在此期间，你可以自由。}
### {1357}{}{We will have to suspend the operation and reorganize the combat personnel. If we need you, we'll call. In the meantime, you can be free.}
{1357}{}{我们将不得不暂停行动并重组作战人员。如果我们需要你，我们会打电话的。在此期间，你可以自由。}
### {358}{}{Yes, sir.}
{358}{}{是的，先生。}

### {360}{}{I need equipment to participate in the raid.}
{360}{}{我需要装备参加突袭。}
### {361}{}{Your equipment is your responsibility. All I can help is to give access to the goods of the quartermaster. Talk to him, maybe you can trade your gun for something stronger.}
{361}{}{您的设备是您的责任。我所能做的就是让他们拿到军需官的货物。和他谈谈，也许你可以用你的枪换更强的东西。}
### {362}{}{And thanks for that.}
{362}{}{谢谢你。}
