### {110}{}{These are torpedoes with a nuclear charge.}
{110}{}{这些是装有核弹头的鱼雷。}
### {111}{}{It must be a damn powerful thing.}
{111}{}{这一定是一个非常强大的东西。}
### {112}{}{These are torpedoes with a nuclear charge. And they are on alert. }
{112}{}{这些是装有核弹头的鱼雷。他们处于戒备状态。}
### {113}{}{It's time to get out of here...}
{113}{}{是时候离开这里了...}
### {114}{}{It made sense to do this before. But not now, when I'm on the Brotherhood's side.}
{114}{}{以前这样做是有道理的。但现在不行，当我站在兄弟会一边的时候。}

### {120}{}{It's a nuclear torpedo. Somewhere nearby there should be a control panel for the torpedo compartment.}
{120}{}{这是一枚核鱼雷。附近的某个地方应该有一个鱼雷舱的控制面板。}
### {121}{}{There is nothing to repair here.}
{121}{}{这里没有什么可修的。}
### {122}{}{This device is too complicated for you. Perhaps there are other ways to activate the torpedo.}
{122}{}{这个设备对你来说太复杂了。也许还有其他方法可以激活鱼雷。}
### {123}{}{You have successfully activated the torpedo timer.}
{123}{}{您已成功启动鱼雷计时器。}
### {124}{}{You have successfully deactivated the torpedo timer.}
{124}{}{您已成功停用鱼雷计时器。}
### {125}{}{It is impossible to deactivate the timer.}
{125}{}{不可能停用计时器。}

### {150}{}{Until the explosion left }
{150}{}{直到爆炸离开}
### {151}{}{ seconds.}
{151}{}{秒。}
