### {100}{}{You see a peasant.}
{100}{}{你看到一个农民。}
### {101}{}{Here is a villager of quite ordinary appearance. It's strange to see him among all this crowd.}
{101}{}{这是一位相貌平平的村民。在人群中看到他真奇怪。}
### {102}{}{Thanks for the help. We will not forget this and will tell everyone about your feat.}
{102}{}{谢谢你的帮助。我们不会忘记这一点，并将告诉每个人你的壮举。}

### {200}{}{Hey, you're not from around here, right? You can see them right away. Let me give you a free tip - don't mess with these dealers. They don't put outsiders in anything.}
{200}{}{嘿，你不是这一带的人，对吧？你可以马上看到他们。让我免费给你小费——不要惹这些经销商。他们不把外人放在任何事情上。}
### {201}{}{And you...}
{201}{}{而你...}
### {202}{}{Another victim of their bad faith, if you want to know. The tinkerers refuse to sell power cells for the generator to my settlement. And do you know why? Because they called us unworthy of old technologies!}
{202}{}{如果你想知道的话，另一个他们恶意的受害者。修修补补的人拒绝把发电机的电池卖给我的定居点。你知道为什么吗？因为他们说我们不配使用旧技术！}
### {203}{}{Tell us more about this problem.}
{203}{}{请告诉我们有关此问题的更多信息。}
### {204}{}{It's none of my business. Goodbye.}
{204}{}{这不关我的事。再见}

### {210}{}{What do you want to know?}
{210}{}{你想知道什么？}
### {211}{}{Nothing else. Bye.}
{211}{}{没有别的。再见}
### {212}{}{I have to go.}
{212}{}{我得走了。}
### {213}{}{Tell me more.}
{213}{}{告诉我更多。}

### {220}{}{Tell me about your settlement.}
{220}{}{告诉我你的解决方案。}
### {221}{}{Just a small rural community. Recently, our generator ran out - and this is the only source of electricity in the entire valley. I had to turn to the tinsmiths for help, but they consider us small and underdeveloped.}
{221}{}{只是一个小的农村社区。最近，我们的发电机用完了——这是整个山谷唯一的电力来源。我不得不向锡匠寻求帮助，但他们认为我们又小又不发达。}
### {222}{}{Is the generator so important to you?}
{222}{}{发电机对你来说这么重要吗？}
### {223}{}{Our whole community was supported by him! Water pump, lighting, radio communication - without all this, our valley will once again turn into a desert and become uninhabitable.}
{223}{}{我们整个社区都得到了他的支持！水泵、照明、无线电通信——如果没有这些，我们的山谷将再次变成沙漠，变得不适合居住。}

### {230}{}{Nowhere else to get power cells?}
{230}{}{没有其他地方可以获得动力电池？}
### {231}{}{Tinsmiths *are the only ones* who produce them nowadays. And pre-war cells became difficult to find. After all, the nearest neighborhoods have long been ruined by these technofanatics.}
{231}{}{如今只有锡匠们生产这些产品。战前的牢房变得很难找到。毕竟，最近的社区早已被这些技术狂热分子摧毁。}
### {232}{}{Have you tried searching in Phoenix?}
{232}{}{你试过在凤凰城搜索吗？}
### {233}{}{Are you kidding? We are settled people, it will be a great challenge to overcome such a distance. In addition, the Big City also buys batteries from tinsmiths. And the prices there are much more expensive.}
{233}{}{你在开玩笑吗？我们是安定下来的人，克服这样的距离将是一个巨大的挑战。此外，大城市还从锡匠那里购买电池。而且那里的价格要贵得多。}

### {240}{}{Why don't the tinsmiths want to trade with you?}
{240}{}{锡匠们为什么不想和你交易？}
### {241}{}{They consider us unworthy of their technology. They think that we will waste their valuable resource. But this is complete nonsense - we need cells for survival, what could be more important?!}
{241}{}{他们认为我们配不上他们的技术。他们认为我们会浪费他们宝贵的资源。但这完全是无稽之谈——我们需要细胞来生存，还有什么更重要的呢？！}

### {250}{}{What are you going to do now?}
{250}{}{你现在打算做什么？}
### {251}{}{We urgently need power cells... Look, you're a peasant like us, right? I can see that. How not to hide behind all these clothes and armor, and your eyes and hands give away what you are doing. We have to stick together, amigo. Help us, and we will help you.}
{251}{}{我们急需动力电池...你和我们一样是农民，对吧？我看得出来。如何不躲在所有这些衣服和盔甲后面，你的眼睛和手泄露了你正在做的事情。我们必须团结一致，朋友。帮助我们，我们就会帮助你。}
### {1251}{}{We urgently need power cells... Look, you're a peasant like us, right? I can see that. How not to hide behind all these clothes and armor, and your eyes and hands give away what you are doing. We have to stick together, amigo. Help us, and we will help you.}
{1251}{}{我们急需动力电池...你和我们一样是农民，对吧？我看得出来。如何不躲在所有这些衣服和盔甲后面，你的眼睛和手泄露了你正在做的事情。我们必须团结一致，朋友。帮助我们，我们就会帮助你。}
### {252}{}{Why should I help you?}
{252}{}{我为什么要帮你？}
### {253}{}{I have a lot of friends among the caravaneers, I can arrange with them about the escort, and I will raise your reputation. And yet, this is pre-war money. They don't seem to be used anymore, but maybe you'll find a use for them.}
{253}{}{我在车队中有很多朋友，我可以和他们安排护送事宜，我会提高你的声誉。然而，这是战前的钱。它们似乎不再被使用了，但也许你会找到它们的用途。}
### {254}{}{I'll think about your offer.}
{254}{}{我会考虑你的报价。}
### {255}{}{Who can I talk to about these energy cells?}
{255}{}{关于这些能量电池，我可以和谁谈谈？}
### {256}{}{They are in the warehouse in that big hangar, and the quartermaster is in charge of the warehouse. But I doubt that he will change his attitude.}
{256}{}{他们在那个大机库的仓库里，军需官负责仓库。但我怀疑他是否会改变态度。}
### {257}{}{We'll see about that.}
{257}{}{我们拭目以待。}
### {258}{}{In other words, do you propose to rob the tinsmiths?}
{258}{}{换言之，你打算抢劫锡匠吗？}
### {259}{}{Just like they robbed many. But you will save an entire settlement and earn friends among honest people. So what do you think, amigo?}
{259}{}{就像他们抢劫了很多一样。但你将节省整个定居点，并在诚实的人中赢得朋友。你觉得呢，朋友？}

### {260}{}{I didn't think there was anyone else here!}
{260}{}{我没想到这里还有其他人！}
### {261}{}{What are you doing here?}
{261}{}{你在这里干什么？}
### {262}{}{I need power cells for the generator. They are in the warehouse in the hangar, but I can't go there unnoticed. You seem to have just come from there, and the robots don't seem to touch you. Can you get it?}
{262}{}{我需要发电机的电池。它们在机库的仓库里，但我不能不注意地去那里。你似乎刚从那里来，机器人似乎没有碰你。你能拿到吗？}
### {263}{}{I'll see what I can do.}
{263}{}{我看看我能做些什么。}
### {264}{}{Deal with your problem yourself. I've already decided mine.}
{264}{}{自己处理你的问题。我已经决定了我的。}
### {265}{}{Consider me no longer here.}
{265}{}{想想我已经不在了。}

### {300}{}{Here is the power cell for the generator.}
{300}{}{这是发电机的电池。}
### {301}{}{Unbelievable! How did you manage it? However, I don't want to know. It's time for me to get out of here while the exit is free. Thank you, amigo, without you our community would have collapsed.}
{301}{}{难以置信的你是怎么做到的？然而，我不想知道。出口空闲时我该离开这里了。谢谢你，朋友，如果没有你，我们的社区就会崩溃。}
### {302}{}{Hey, did you forget anything?}
{302}{}{嘿，你忘了什么吗？}
### {303}{}{I'm sorry, but I deceived you - I don't have any friends among the caravaneers. But I'll tell everyone I know about your feat anyway. If you want, we'll go to Casa Grande together, it's safer that way. Decide now, I won't wait.}
{303}{}{对不起，我欺骗了你——我在房车司机中没有朋友。但无论如何，我会告诉我认识的每个人你的壮举。如果你愿意，我们会一起去格兰德之家，那样更安全。现在就决定，我不会等的。}
### {304}{}{Then let's go.}
{304}{}{那我们走吧。}
### {305}{}{No, our paths diverge here. Happily.}
{305}{}{不，我们在这里分道扬镳。高兴地}
### {306}{}{So, are you with us? The way to Casa Grande is difficult, it will be safer for you to travel with us.}
{306}{}{那么，你和我们在一起吗？去格兰德之家的路很难，和我们一起旅行会更安全。}
