### {100}{}{This is the owner of the hotel.}
{100}{}{这是旅馆的老板。}
### {101}{}{Here is the owner of the hotel. He lazily scratches his belly, sitting heavily in the old pilot's seat.}
{101}{}{这是旅馆的老板。他懒洋洋地抓着肚子，重重地坐在老飞行员的座位上。}
### {102}{}{Close the door quickly! These robots are everywhere!}
{102}{}{快把门关上！这些机器人无处不在！}

#The first dialog
### {200}{}{(reluctantly turns in your direction) All rooms are occupied.}
{200}{}{（不情愿地转向你的方向）所有的房间都有人住。}
### {201}{}{But half of the keys are hanging on the counter...}
{201}{}{但是有一半的钥匙挂在柜台上...}
### {202}{}{A big race is planned. These numbers are not for sale. If you need to spend the night, I advise you to knock on residential buildings.}
{202}{}{计划举行一场大型比赛。这些号码是非卖品。如果你需要过夜，我建议你去敲住宅楼。}
### {203}{}{I don't think I'll be welcome there.}
{203}{}{我想我在那里不受欢迎。}
### {204}{}{It's none of my business.}
{204}{}{这不关我的事。}
### {205}{}{Uh, okay...}
{205}{}{好吧...}

### {210}{}{I told you - the rooms are occupied.}
{210}{}{我告诉过你了——房间都有人了。}
### {211}{}{I think you're just avoiding strangers.}
{211}{}{我觉得你只是在回避陌生人。}
### {212}{}{I remember.}
{212}{}{我记得。}

### {213}{}{And I think that some people allow themselves too much.}
{213}{}{我认为有些人允许自己太多。}
### {214}{}{Grm...}
{214}{}{Grm...}

### {215}{}{(leaning towards you) Tinkerers are afraid of espionage and do not want their plans to be public, so I have to be careful with strangers.}
{215}{}{（向你倾斜）修补者害怕间谍活动，不希望他们的计划公开，所以我必须小心对待陌生人。}
### {216}{}{It's good that we found a common language.}
{216}{}{我们找到了一种共同的语言，这很好。}
### {217}{}{As a Follower of Fire, I am outraged by your service!}
{217}{}{作为火的追随者，我对你的服务感到愤怒！}
### {218}{}{I think the Brotherhood of Steel will not approve of such an attitude towards its subordinates.}
{218}{}{我认为钢铁兄弟会不会赞成这种对待下属的态度。}
### {219}{}{Come on, why so much distrust?}
{219}{}{拜托，为什么这么不信任？}
### {220}{}{You're out of town.}
{220}{}{你不在城里。}
### {221}{}{Well, yes, of course...}
{221}{}{嗯，是的，当然...}

#Repeat dialog
### {250}{}{What can I do for you?}
{250}{}{我能为你做什么？}
### {251}{}{Thanks, I'll figure it out somehow.}
{251}{}{谢谢，我会设法解决的。}
### {252}{}{Goodbye.}
{252}{}{再见}

### {260}{}{Tell me what's going on here?}
{260}{}{告诉我这里发生了什么？}
### {261}{}{Tinsmiths are trying to open the burial ground of military equipment. There are no results yet, but it's only a matter of time.}
{261}{}{铁匠们正试图打开军事装备的墓地。目前还没有结果，但这只是时间问题。}
### {262}{}{Tinsmiths have opened the burial ground of military equipment. It looks like we have a lot of work ahead of us.}
{262}{}{铁匠们已经开辟了军事装备的墓地。看来我们还有很多工作要做。}
### {263}{}{Do you know anything about slaves from the Villa?}
{263}{}{你知道别墅里的奴隶吗？}
### {264}{}{No. I don't know. Ask in the hangar, they keep slaves there.}
{264}{}{不，我不知道。在机库里问，他们在那里养奴隶。}
### {265}{}{How did you manage to get along in this place?}
{265}{}{你在这个地方是怎么相处的？}
### {266}{}{I came here a few years ago when the tinsmiths opened a trade route with Phoenix. They needed a hotel to work with caravanners, and I organized it for them. If it wasn't for the tinsmiths, I wouldn't have lasted to my age. Surely he would be lying somewhere in the wastelands right now, warming his bones in the sun.}
{266}{}{几年前，我来到这里，当时锡匠公司开通了与凤凰城的贸易路线。他们需要一家酒店来与房车司机合作，我为他们组织了这家酒店。如果不是因为铁匠，我就活不下去了。他现在肯定会躺在荒原上的某个地方，在阳光下温暖他的骨头。}
