### {100}{}{You see the instructor.}
{100}{}{你看到教练了。}
### {101}{}{Here is one of the tinsmiths responsible for training slaves.}
{101}{}{这是一位负责训练奴隶的铁匠。}

### {200}{}{ (addressing the whole group) Listen to me, rusty gears! You were brought to this city so that your insignificant existence would find at least some meaning!}
{200}{}{（对整个小组讲话）听我说，生锈的齿轮！你被带到这个城市是为了让你微不足道的存在至少找到一些意义！}
### {201}{}{[Next]}
{201}{}{[下一个]}
### {202}{}{You have the great honor to participate in the extraction of ancient technologies from the Forbidden Zone. This place has been storing equipment since pre-war times. But there is a problem - a reliable security system does not let us outside the perimeter. You have to get into the control center and disable the protection. To those who do, we grant complete freedom.}
{202}{}{您很荣幸能参与从紫禁城中提取古代技术。这个地方从战前就一直在存放设备。但有一个问题——一个可靠的安全系统不允许我们进入外围。你必须进入控制中心并禁用保护。对于那些这样做的人，我们给予他们完全的自由。}
### {203}{}{[Next]}
{203}{}{[下一个]}
### {204}{}{Any questions?}
{204}{}{有什么问题吗？}
### {205}{}{Yes.}
{205}{}{对}
### {206}{}{No way.}
{206}{}{不可能。}
### {207}{}{Then pick up your rags and run to the parade ground! Anyone who escapes from the Restricted Area before the end of the mission will be permanently dismantled.}
{207}{}{然后拿起你的破布，跑向阅兵场！任何在任务结束前逃离禁区的人都将被永久解散。}
### {208}{}{It looks like it's going to be a tough test...}
{208}{}{看起来这将是一个艰难的考验...}
### {209}{}{No more questions.}
{209}{}{没有更多的问题。}

### {210}{}{Do you think you can do anything? State it quickly, piece of rags!}
{210}{}{你认为你能做什么吗？快点说出来，破布！}
### {211}{}{Will I be able to pick up my things if I complete the task?}
{211}{}{如果我完成了任务，我能收拾东西吗？}
### {212}{}{Will you pick them up in the quartermaster's drawer. But do not hope that you will succeed.}
{212}{}{你能在军需官的抽屉里把它们捡起来吗。但不要指望你会成功。}
### {213}{}{Is my father named Andres also in the Restricted Area?}
{213}{}{我的父亲叫安德烈斯也在禁区内吗？}
### {214}{}{I have no idea who you're talking about. So much human garbage has already disappeared in the Zone that I don't see the point in remembering at least one of them.}
{214}{}{我不知道你在说谁。如此多的人类垃圾已经在这个区域消失了，我认为至少记住其中一个是没有意义的。}
### {215}{}{What should we expect in the Forbidden Zone?}
{215}{}{我们在禁区应该期待什么？}
### {216}{}{Hostile robots, electromagnetic traps and increased radiation background. The perimeter is fenced with a force barrier, so you can't get out without a fight.}
{216}{}{敌对的机器人，电磁陷阱和增加的辐射背景。外围用力量屏障围起来，所以你不能不战而退。}
### {217}{}{Will they give us at least some weapons?}
{217}{}{他们会至少给我们一些武器吗？}
### {218}{}{Use what you find in the Zone.}
{218}{}{使用您在区域中找到的内容。}
### {219}{}{At least give me the brass knuckles.}
{219}{}{至少给我黄铜指节。}
### {220}{}{At least give me a primitive gun.}
{220}{}{至少给我一把原始的枪。}
### {221}{}{At least give me a stimpack.}
{221}{}{至少给我一个刺激包。}
### {222}{}{At least give me grenades against robots.}
{222}{}{至少给我手榴弹对付机器人。}
### {223}{}{I'm tired of your whining, pieces of rags! You won't get any weapons.}
{223}{}{我受够了你的抱怨，碎布！你不会得到任何武器。}
### {224}{}{I'm tired of your whining, pieces of rags! Take this and shut up.}
{224}{}{我受够了你的抱怨，碎布！拿着这个闭嘴。}
### {225}{}{Another question.}
{225}{}{另一个问题。}

### {230}{}{Is there a result? Report to our leader personally.}
{230}{}{有结果吗？亲自向我们的领导报告。}
### {231}{}{OK.}
{231}{}{好啊}
### {232}{}{What? A volunteer mercenary in a Restricted Area?}
{232}{}{什么一个在禁区内的志愿雇佣兵？}
### {233}{}{Yes, I will also participate.}
{233}{}{是的，我也会参加。}
### {234}{}{No, I'm just passing by.}
{234}{}{不，我只是路过。}
### {235}{}{Ask your stupid questions, volunteer.}
{235}{}{问你愚蠢的问题，志愿者。}
### {236}{}{Talk to our boss, I only deal with slaves.}
{236}{}{和我们的老板谈谈，我只和奴隶打交道。}
### {237}{}{Okay.}
{237}{}{可以}
### {238}{}{The great ZAX is defeated! Now we will have hot working days. So, it's time to look for new slaves.}
{238}{}{伟大的ZAX被击败了！现在我们将有炎热的工作日。所以，是时候寻找新的奴隶了。}
### {239}{}{I hope you can do without me this time... Uh, bye.}
{239}{}{我希望你这次可以不用我...再见。}
