### {100}{}{This is your padre.}
{100}{}{这是你的牧师。}
### {101}{}{You see Andres, your father.}
{101}{}{你看到了安德烈斯，你的父亲。}
### {102}{}{Your padre is dead.}
{102}{}{你的牧师死了。}
### {103}{}{You get }
{103}{}{你得到}
### {104}{}{ experience for the liberation of their fellow tribesmen.}
{104}{}{解放部落同胞的经验。}
### {105}{}{This is for you for my difficult childhood, Padre.}
{105}{}{这是给你的，为了我艰难的童年，神父。}
### {106}{}{Goodbye. I don't need my father's guidance anymore.}
{106}{}{再见我不再需要我父亲的指导了。}

#The first dialog
### {200}{}{?!}
{200}{}{？！}
### {201}{}{Hello, Padre.}
{201}{}{你好，神父。}
### {202}{}{How did you manage to find us?}
{202}{}{你是怎么找到我们的？}
### {203}{}{Well, I had to run through the desert...}
{203}{}{嗯，我不得不跑过沙漠。。。}
### {204}{}{Don't you understand the situation we're in?! Your place should not be here, but at home!}
{204}{}{你不明白我们现在的处境吗？！你的位置不应该在这里，而应该在家里！}
### {205}{}{The villa is gradually being restored. I managed to rescue those who were in Flagstaff from slavery.}
{205}{}{别墅正在逐步修复。我设法把那些在弗拉格斯塔夫的人从奴隶制中解救出来。}
### {206}{}{That's it... Now I see that I thought you were a child in vain. It seems that this whole story has given you a great life experience. In that case, I'm glad you're here.}
{206}{}{就这样……现在我明白了，我以为你是个徒劳的孩子。整个故事似乎给了你一次美好的人生体验。既然如此，我很高兴你在这里。}
### {207}{}{It seemed to me that it would be wiser to save the leader of the Villa, and then the others.}
{207}{}{在我看来，拯救维拉的领袖，然后拯救其他人会更明智。}
### {208}{}{And this is reasonable in your opinion?! Willa can live without me. And who needs a leader in an abandoned settlement?! You should have gone to the town of Flagstaff, where our people are being held. Your madre is there too.}
{208}{}{你认为这是合理的吗？！威拉可以没有我生活。在一个废弃的定居点里，谁需要一个领袖？！你应该去弗拉格斯塔夫镇，那里关押着我们的人民。你妈妈也在那里。}
### {209}{}{Okay. I'll deal with it later. Any ideas how to get out of here?}
{209}{}{可以我稍后再处理。有什么办法离开这里吗？}
### {210}{}{We would have done it a long time ago if it weren't for the damn barrier. It is impossible to pass through it. The only way out is to get into the bunker of the control center and disable what is there.}
{210}{}{如果不是因为这个该死的障碍，我们早就这么做了。通过它是不可能的。唯一的出路是进入控制中心的掩体并禁用那里的东西。}
### {211}{}{So let's do it?}
{211}{}{那我们来做吧？}
### {212}{}{Easy to say. This area is teeming with robots and traps. And what is in the bunker, no one knows at all. First, conduct a reconnaissance, find equipment and companions. We also tried to create a weapon against robots. But our technician died while looking for the right parts, and I don't understand it.}
{212}{}{说起来很简单。这个地区到处都是机器人和陷阱。地堡里有什么，谁也不知道。首先，进行侦察，寻找装备和同伴。我们还试图制造一种对抗机器人的武器。但我们的技术人员在寻找合适的零件时去世了，我不明白。}
### {213}{}{No problem, Padre. I'll find a way out.}
{213}{}{没问题，神父。我会想办法的。}
### {214}{}{At least say thank you. I'm saving you.}
{214}{}{至少说声谢谢。我在救你。}
### {215}{}{I'll figure it out without your guidance. Sit and wait for my instructions.}
{215}{}{没有你的指导，我会解决的。坐着等我的指示。}
### {216}{}{Pa-adre-e, how long have I been looking for you!}
{216}{}{爸爸，我找你多久了！}
### {1216}{}{Pa-adre-e, how long have I been looking for you!}
{1216}{}{爸爸，我找你多久了！}

#Repeat dialog
### {220}{}{Tell me, }
{220}{}{告诉我，}
### {221}{}{.}
{221}{}{。}
### {222}{}{I'll be back soon.}
{222}{}{我很快就会回来。}

### {230}{}{Let's discuss the plan again.}
{230}{}{让我们再讨论一下这个计划。}
### {231}{}{Our plan is to get past the robots, get into the bunker and, whatever it is, take control of it. And then get out of this damned place back to the Villa.}
{231}{}{我们的计划是越过机器人，进入地堡，不管是什么，控制它。然后离开这个该死的地方，回到别墅。}
### {232}{}{Clear.}
{232}{}{清楚的}

### {233}{}{Where can I get weapons?}
{233}{}{我在哪里可以买到武器？}
### {234}{}{Many slaves and mercenaries died here. Look for bodies, maybe some of them still have weapons. I also saw something that looked like a weapon near a large plane. But I do not know how to use it.}
{234}{}{许多奴隶和雇佣兵死在这里。寻找尸体，也许他们中的一些人还有武器。我还在一架大飞机附近看到了一个看起来像武器的东西。但我不知道如何使用它。}
### {235}{}{Are there other slaves here?}
{235}{}{这里还有其他奴隶吗？}
### {236}{}{There is a survivor's camp not far from the bunker. But he didn't want to cooperate with us. He doesn't seem to be right in the head. And he looks pretty... painful.}
{236}{}{在离地堡不远的地方有一个幸存者营地。但他不想和我们合作。他似乎头脑不清醒。他看起来很漂亮。。。痛苦的}
### {237}{}{How can robots be bypassed?}
{237}{}{如何绕过机器人？}
### {238}{}{These creatures are smarter than mole rats. They hide in dark corners or in the sand, you won't see them right away. But you can hear them from ten yards away. And it also looks like they're reacting to movement. If you move slowly or stand behind, they may not notice you.}
{238}{}{这些生物比鼹鼠更聪明。它们藏在黑暗的角落或沙子里，你不会马上看到它们。但你可以在十码外听到他们的声音。看起来他们也在对运动做出反应。如果你行动缓慢或站在后面，他们可能不会注意到你。}
### {239}{}{}
{239}{}{error : string is empty}

### {240}{}{What is this place?}
{240}{}{这是什么地方？}
### {241}{}{As far as I understand, this is a graveyard of long-forgotten technologies. The tinkerers want to revive them. I wouldn't want that to happen. These fools do not understand the danger posed by the technology of the Ancients!}
{241}{}{据我所知，这是一个被遗忘已久的技术的墓地。修补匠们想让它们复活。我不希望发生这种事。这些傻瓜不明白古人的技术所带来的危险！}
### {242}{}{How do you know that these technologies are dangerous?}
{242}{}{你怎么知道这些技术是危险的？}
### {243}{}{Our ancestors taught us to be afraid of old technology. They said she was unreliable and dangerous. All right. Have you already come across things that can explode in your hands or harm your health with invisible radiation? I've heard stories of entire settlements dying out from excessive attachment to technology. And in the wrong hands, old things become a weapon.}
{243}{}{我们的祖先教导我们要害怕旧技术。他们说她不可靠而且危险。好吧你是否已经遇到过会在你手中爆炸或通过隐形辐射危害你健康的东西？我听说过整个定居点因过度依赖技术而消亡的故事。在坏人手中，旧东西变成了武器。}
### {244}{}{Familiar stories...}
{244}{}{熟悉的故事。。。}
### {245}{}{Remember Flagstaff. Remember how easily a group of stupid bandits enslaved an entire settlement only thanks to their weapons and electric collars. All this equipment must be destroyed! All without exception!}
{245}{}{记住Flagstaff。记住，一群愚蠢的土匪仅仅凭借他们的武器和电项圈就轻而易举地奴役了整个定居点。所有这些设备都必须销毁！无一例外！}
### {246}{}{It's worth thinking about...}
{246}{}{值得思考的是。。。}
### {247}{}{And what about your pneumoculac? I could use it.}
{247}{}{你的肺炎球菌呢？我可以用它。}
### {248}{}{Will you leave the old man unprotected? (bitter laugh) Okay, we have one hope left - for you.}
{248}{}{你会让老人不受保护吗？（苦笑）好吧，我们只剩下一个希望了——给你。}
### {249}{}{Thanks for the gun, Padre.}
{249}{}{谢谢你的枪，神父。}

### {250}{}{Tell me about the raid on the Villa.}
{250}{}{告诉我对别墅的突袭。}
### {251}{}{Let's leave these conversations until we get home. In short, the raiders attacked us at the end of the working day, when our people were returning from the plantations and were tired. I managed to hold the defense in the town hall, but in the end we were all caught, tied up and brought to the town of Flagstaff. Most were left to work in the local mine, and only the best were sent here.}
{251}{}{让我们把这些对话留到回家。简言之，袭击者在工作日结束时袭击了我们，当时我们的人民正从种植园返回，疲惫不堪。我设法在市政厅守住了防线，但最终我们都被抓住了，被绑起来，带到了弗拉格斯塔夫镇。大多数人被留在当地的矿场工作，只有最好的人才被送到这里。}
### {252}{}{Have you been to Phoenix?}
{252}{}{你去过凤凰城吗？}
### {253}{}{Yes, we were brought to a church run by some cult. Disgusting people, devoid of compassion and devalued human life. They studied us in detail, like some kind of rats - they took blood for analysis, tortured us and asked about the Villa. Unfortunately, the church is now well aware of our house.}
{253}{}{是的，我们被带到一个由邪教组织经营的教堂。令人厌恶的人，缺乏同情心，贬低了人类的生命。他们像老鼠一样详细地研究我们——他们抽血进行分析，折磨我们，询问别墅的情况。不幸的是，教会现在很了解我们的房子。}
### {254}{}{There are more questions.}
{254}{}{还有更多的问题。}
### {255}{}{Why exactly were you sent to Two-Sun?}
{255}{}{你到底为什么被送到二太阳？}
### {256}{}{As a leader, I have learned a lot. Therefore, of all our residents, I was considered the best candidate for this job.}
{256}{}{作为一名领导者，我学到了很多。因此，在我们所有的居民中，我被认为是这份工作的最佳人选。}

#Joining the party
### {260}{}{Let's go together. I need your experience.}
{260}{}{我们一起去吧。我需要你的经验。}
### {261}{}{I'll help you get to the bunker. But you'll have to go down alone.}
{261}{}{我帮你到地堡去。但你得一个人下去。}
### {262}{}{Agreed.}
{262}{}{同意。}
### {263}{}{Why?}
{263}{}{为什么？}
### {264}{}{That way you'll have a better chance of going unnoticed. Besides, among all these technologies, I won't be of any use anyway. Your journey through Sonora has given you a lot more knowledge and experience.}
{264}{}{这样你就更有可能被忽视。此外，在所有这些技术中，我无论如何都没有任何用处。你的索诺拉之旅给了你更多的知识和经验。}
### {1264}{}{That way you'll have a better chance of going unnoticed. Besides, among all these technologies, I won't be of any use anyway. Your journey through Sonora has given you a lot more knowledge and experience.}
{1264}{}{这样你就更有可能被忽视。此外，在所有这些技术中，我无论如何都没有任何用处。你的索诺拉之旅给了你更多的知识和经验。}
### {265}{}{Hmm. Let's see what I can do.}
{265}{}{嗯。让我们看看我能做些什么。}
### {266}{}{Next I'll go alone.}
{266}{}{接下来我一个人去。}
### {1266}{}{Next I'll go alone.}
{1266}{}{接下来我一个人去。}
### {267}{}{I'll be guarding the entrance to the bunker. Good luck.}
{267}{}{我将守卫地堡的入口。祝你好运}
### {268}{}{[Go]}
{268}{}{[去]}

#Completion of the rescue quest
### {300}{}{Hard has given you freedom. You can go.}
{300}{}{努力给了你自由。你可以走了。}
### {301}{}{It's good. But *how* are we going to get out of here?}
{301}{}{这很好。但是我们该怎么离开这里呢？}
### {302}{}{Hmm. Let me think.}
{302}{}{嗯，让我想想。}
### {303}{}{The barrier is disabled, we can escape from Two-Sun.}
{303}{}{屏障被禁用，我们可以逃离两个太阳。}
### {304}{}{Good job, }
{304}{}{干得好}
### {305}{}{. It's a pity, this is only a temporary measure. Now the tinkerers will have access to old technologies, and God only knows how much trouble they will cause. At least we have time to prepare.}
{305}{}{很遗憾，这只是一个临时措施。现在，修补者将可以使用旧技术，上帝只知道它们会造成多大的麻烦。至少我们有时间准备。}
### {306}{}{[Next]}
{306}{}{[下一个]}
### {307}{}{Great job, }
{307}{}{干得好，}
### {308}{}{. We not only gained access to freedom, but also deprived the tinkerers of these old technologies. God only knows how much trouble they would have caused the wastelands by subjugating the equipment in the bunker.}
{308}{}{。我们不仅获得了自由，而且剥夺了修补者对这些旧技术的利用。只有上帝知道，如果他们征服了地堡里的设备，会给荒地带来多大的麻烦。}
### {309}{}{I'll rest for a while and then go home. Meet me at the Villa.}
{309}{}{我休息一会儿然后回家。在别墅见我。}
### {310}{}{Bye, Padre.}
{310}{}{再见，神父。}
### {311}{}{Meanwhile, find Carlos and try to reason with him. The tinsmiths won this fool over to their side, filled his head with nonsense. In case of failure... It must be eliminated. Do you understand? Perhaps I'm asking too much, but imagine the danger he poses to the whole Villa now.}
{311}{}{同时，找到卡洛斯，试着和他讲道理。铁匠们把这个傻瓜吸引到他们身边，让他的脑子里充满了胡言乱语。如果出现故障。。。它必须被消除。你明白吗？也许我要求太多了，但想象一下他现在对整个维拉构成的危险。}
### {312}{}{I understand, Padre. Rely on me.}
{312}{}{我理解，神父。靠我。}
### {313}{}{Kill your kinsman? I'm definitely not going to do that. But it's worth talking to him.}
{313}{}{杀了你的亲人？我绝对不会那样做。但值得和他谈谈。}
