### {100}{}{You see Gerardo.}
{100}{}{你看到杰拉多了。}
### {101}{}{Here is one of the enslaved peasants of the Villa.}
{101}{}{这是别墅里的一个被奴役的农民。}

#The first dialog
### {200}{}{?! And you're here?! I thought the raiders didn't find you...}
{200}{}{？！你在这里？！我以为袭击者没有找到你...}
### {201}{}{No, Gerardo, we haven't found it. That's why I'm here to save you.}
{201}{}{不，杰拉尔多，我们还没找到。这就是我来救你的原因。}
### {202}{}{Eh, amigo, you know how to encourage. But believe me, there's no way out of here. The very earth here is saturated with death! We will perish, amigo, and no one will even bury us.}
{202}{}{嗯，朋友，你知道如何鼓励。但相信我，这里没有出路。这里的大地上充满了死亡！我们会灭亡的，朋友，甚至没有人会埋葬我们。}
### {203}{}{Where is my padre?}
{203}{}{我的牧师在哪里？}
### {204}{}{Now he should be in an old hangar in the middle of the Burial Ground. All the survivors gather there. Go north, you won't miss.}
{204}{}{现在他应该在墓地中间的一个老机库里。所有幸存者都聚集在那里。往北走，你不会错过的。}
### {205}{}{Good. See you later.}
{205}{}{好的回头见。}
### {206}{}{What about you?}
{206}{}{你呢？}
### {207}{}{The padre said to sit here and direct new people to the hangar. Don't worry, I'm relatively safe in these containers.}
{207}{}{牧师说，坐在这里，引导新人到机库。别担心，我在这些集装箱里相对安全。}
### {208}{}{I see. See you later, Gerardo.}
{208}{}{我明白了。再见，杰拉尔多。}

### {210}{}{Thank heaven you're back!}
{210}{}{谢天谢地，你回来了！}
### {1210}{}{Thank heaven you're back!}
{1210}{}{谢天谢地，你回来了！}
### {211}{}{Be.}
{211}{}{是}
### {212}{}{The barrier is disabled, and the robots will not touch us. Go back to the Villa.}
{212}{}{屏障被禁用，机器人不会碰我们。回别墅去吧。}
### {213}{}{And did you manage it all? Truly, here is the real leader of the Villa! Although something has changed in you, amigo... Okay, I'll meet you at home! If, of course, we get there.}
{213}{}{你把这一切都搞定了吗？真的，这里才是真正的维拉首领！虽然你身上有些变化，朋友...好吧，我在家见！当然，如果我们到达那里。}
### {214}{}{Be.}
{214}{}{是}
### {215}{}{What now?}
{215}{}{现在怎么办？}

### {220}{}{Come with me, I need support in battle.}
{220}{}{跟我来，我在战斗中需要支持。}
### {221}{}{What are you, amigo! You're calling me to my death! With our weapons against robots, we are powerless. It's better to sit back and wait until someone opens the gate.}
{221}{}{你是什么，朋友！你在叫我死！用我们的武器对付机器人，我们无能为力。最好坐下来等有人打开大门。}
### {222}{}{I don't recognize you, Gerardo. Remember, you were always a cool pepper in our village?}
{222}{}{我不认识你，杰拉尔多。还记得吗，你在我们村里一直是个很酷的人？}
### {223}{}{Ya... I'm alive only because of your padre. The villa and this world are completely different. I'm not ready for this. Sorry. Even if I return to the Villa, I will not be able to live as before.}
{223}{}{耶...我活着只是因为你的牧师。别墅和这个世界完全不同。我还没准备好。很抱歉即使我回到了别墅，我也不能再像以前那样生活了。}
### {224}{}{Gerardo, now is not the time for despondency. Get up, your family needs you!}
{224}{}{杰拉尔多，现在不是沮丧的时候。起来，你的家人需要你！}
### {225}{}{Okay, amigo... But I won't take a step into that damn bunker! Let's get to the entrance, and then without me.}
{225}{}{好吧，朋友...但我不会踏入那个该死的掩体！让我们到入口，然后不要带我。}
### {226}{}{Well, at least so.}
{226}{}{至少是这样。}
### {227}{}{No... I'm needed here now. Padre Andres is counting on me.}
{227}{}{不……这里现在需要我。安德烈斯神父指望着我。}
### {228}{}{I see.}
{228}{}{我明白了。}
### {229}{}{We should split up. Stay where you are until I get back.}
{229}{}{我们应该分手。呆在原地直到我回来。}
### {230}{}{Whatever you say, amigo...}
{230}{}{不管你说什么，朋友...}
### {231}{}{That's settled.}
{231}{}{这就解决了。}
