### {110}{}{This body should be examined more closely.}
{110}{}{应该更仔细地审查这个机构。}
### {111}{}{There's no point in disturbing the dead now.}
{111}{}{现在打扰死者是没有意义的。}
### {112}{}{This cannot be done during a fight.}
{112}{}{在打斗中不能这样做。}

### {200}{}{This man died from a gunshot wound during the raid. It looks like he was one of the attackers, although you can't tell from his appearance.}
{200}{}{这名男子在突袭中死于枪伤。看起来他是袭击者之一，尽管你从他的外表看不出来。}
### {201}{}{[Next]}
{201}{}{[下一个]}
### {202}{}{In his pocket you find a cursory sketch of the layout of the Old City with an indication of a safe route. It can be assumed that a bandit camp is located in this place.}
{202}{}{在他的口袋里，你可以找到一张老城布局的粗略草图，上面标明了一条安全的路线。可以推测，这个地方有一个土匪营。}
### {203}{}{[Go to the Old Town]}
{203}{}{[去古城]}
### {204}{}{[Leave the corpse alone]}
{204}{}{[别管尸体]}
