### {101}{}{Here is a homemade workbench.}
{101}{}{这是一个自制的工作台。}
### {102}{}{You have made 20 signal cartridges from old festive pyrotechnics.}
{102}{}{你们用古老的节日烟火制作了20个信号弹。}
### {110}{}{This workbench contains components for assembling nuclear batteries.}
{110}{}{这个工作台包含用于组装核电池的部件。}
### {111}{}{All components are used up. There's nothing else to do here.}
{111}{}{所有部件都用完了。这里没有别的事可做。}
### {112}{}{You have assembled a micro-core battery for 8 charges.}
{112}{}{您已经组装了一个可充电8次的微型核心电池。}
### {113}{}{You have assembled a micro-core battery for 16 charges.}
{113}{}{您已经组装了一个可充电16次的微型核心电池。}
### {114}{}{You have assembled a micro-core battery for 20 charges.}
{114}{}{您已经组装了一个可充电20次的微型核心电池。}
