### {100}{}{This is Granny Adonsia.}
{100}{}{这是阿东西娅奶奶。}
### {101}{}{Here is a woman you know well - your grandmother. She smokes a pipe and squints with a sharp look.}
{101}{}{这是一个你很熟悉的女人——你的祖母。她抽着烟斗，斜视着眼睛，目光犀利。}
### {102}{}{Goodbye, Grandma. I hope no one finds out the real cause of your death.}
{102}{}{再见，奶奶。我希望没有人知道你的真正死因。}
### {103}{}{What kind of demon sent you against us? Banish him! Come to your senses!}
{103}{}{什么恶魔派你来对付我们？开除他！恢复理智！}

#The first dialog
### {210}{}{(takes a drag and then lets out puffs of black smoke while looking at you reproachfully) Here you are. You were lucky to be away from home at a bad time. And maybe it's for the best.}
{210}{}{（拖了一下，然后吐出一股黑烟，同时责备地看着你）给你。你很幸运在不好的时候离开了家。也许这是最好的。}
### {211}{}{Granny Adonsia, we don't have time to chat right now. Tell me what's going on.}
{211}{}{阿东西娅奶奶，我们现在没有时间聊天。告诉我发生了什么事。}
### {212}{}{Stop grumbling, old woman. Tell me what happened.}
{212}{}{别再抱怨了，老妇人。告诉我发生了什么事。}
### {213}{}{What happened? What's going on?}
{213}{}{发生了什么？怎么回事？}
### {214}{}{Huhm? You start talking like an adult. This is encouraging.}
{214}{}{嗯？你开始像成年人一样说话。这是令人鼓舞的。}
### {215}{}{And you still won't calm down your bad temper. Although it may help you in the future.}
{215}{}{你仍然无法平息你的坏脾气。尽管它可能在未来对你有所帮助。}
### {216}{}{Worried, eh? Not the best quality when you have to make a decision. But when it comes down to it, you'll have to do it.}
{216}{}{担心吗？当你不得不做出决定时，这不是最好的质量。但归根结底，你必须这么做。}
### {217}{}{So what happened?}
{217}{}{那么发生了什么？}

### {218}{}{While you were gone, strangers came. Evil people. Ten people, and all with weapons. Our men couldn't handle them.}
{218}{}{你走的时候，陌生人来了。邪恶的人。十个人，都带着武器。我们的人对付不了他们。}
### {219}{}{Go on.}
{219}{}{继续}
### {220}{}{Outsiders took all able-bodied. Only the elderly and children were left. Now the Villa is in your hands, you are in charge here. And you'll have to do something about it.}
{220}{}{外人带走了所有身体健全的人。只剩下老人和孩子。现在别墅在你手里，你在这里负责。你必须为此做点什么。}
### {221}{}{What can I do alone?}
{221}{}{我一个人能做什么？}
### {222}{}{What do you think? Bring back our men and women. At least their parents. They, too, fell into the clutches of these extranos.}
{222}{}{你觉得怎么样？把我们的男人和女人带回来。至少是他们的父母。他们也落入了这些外部网络的魔掌。}
### {223}{}{It won't be easy...}
{223}{}{这并不容易。。。}
### {224}{}{(nods) Right. And I'll tell you what, although your padre won't like it terribly. Downstairs, in the cellars under the town hall, there is a secret room with family heirlooms. Only a few people know about it. Go down, find and take everything that will be useful to you on the road. And do it right now, time is precious.}
{224}{}{（点点头）对。我会告诉你的，尽管你的牧师不会很喜欢。楼下，在市政厅地下的地窖里，有一间密室，里面有传家宝。只有少数人知道。走下去，找到并带走路上对你有用的一切。现在就做，时间是宝贵的。}
### {225}{}{Thanks, Grandma. Now every little thing will help me.}
{225}{}{谢谢，奶奶。现在每一件小事都会帮助我。}
### {226}{}{And that's it? Damn, you're no help. Okay, I'll look in Dad's cellar.}
{226}{}{就这样？该死，你帮不了什么忙。好吧，我去爸爸的地窖看看。}
### {227}{}{OK, I'll try to find these old things.}
{227}{}{好的，我会去找这些旧东西。}
### {228}{}{Be careful. There are rats in the cellars, and it's as dark as a fat-horn's ass. Here, take a lighter, even though I'll miss it. And when you find the secret things, go straight to the square and find Jose there. He will tell me more.}
{228}{}{小心。地窖里有老鼠，黑得像肥角的屁股。给，拿个打火机，尽管我会想念它。当你发现秘密时，直接去广场，在那里找到何塞。他会告诉我更多的。}
### {229}{}{Before I go down, I have to ask.}
{229}{}{在我下去之前，我得问问。}
### {1229}{}{Before I go down, I have to ask.}
{1229}{}{在我下去之前，我得问问。}
### {230}{}{I'll leave immediately.}
{230}{}{我马上就走。}

### {231}{}{Why are you still here?}
{231}{}{你为什么还在这里？}
### {232}{}{Before I leave, I have to ask.}
{232}{}{在我离开之前，我得问问。}
### {1232}{}{Before I leave, I have to ask.}
{1232}{}{在我离开之前，我得问问。}
### {233}{}{Really, I have to go.}
{233}{}{真的，我得走了。}
### {234}{}{You did a good job getting our people back. Well done.}
{234}{}{你把我们的人救回来做得很好。干得好。}
### {1234}{}{You did a good job getting our people back. Well done.}
{1234}{}{你把我们的人救回来做得很好。干得好。}
### {235}{}{I have some questions.}
{235}{}{我有一些问题。}
### {236}{}{I have to go.}
{236}{}{我得走了。}
### {237}{}{Well, it's my duty. I will do my best.}
{237}{}{这是我的职责。我会尽力的。}
### {238}{}{Bring back our men and women. Your parents also fell into the clutches of the extranos.}
{238}{}{把我们的男人和女人带回来。你的父母也落入了外部网络的魔掌。}
### {239}{}{I think you're crazy. What can I do against an entire armed squad?}
{239}{}{我觉得你疯了。我能对整个武装队伍做些什么？}

#Questions
### {240}{}{Find Jose in the square, he will tell me more.}
{240}{}{在广场上找到何塞，他会告诉我更多。}
### {241}{}{How did the stranger?s assault happen?}
{241}{}{这个陌生人怎么样?袭击发生了吗？}
### {242}{}{Has someone died?}
{242}{}{有人死了吗？}
### {243}{}{What's wrong with my parents?}
{243}{}{我父母怎么了？}
### {244}{}{This secret room in the cellars raises questions.}
{244}{}{地窖里的这个秘密房间引起了人们的疑问。}
### {245}{}{What should I do when I get those ancient things?}
{245}{}{当我得到那些古老的东西时该怎么办？}
### {246}{}{Okay, I'm leaving.}
{246}{}{好吧，我要走了。}
### {247}{}{Another question.}
{247}{}{另一个问题。}
### {248}{}{Your parents are also among the forced laborers. Whether you want it or not, you'll have to save them. Blood for blood and shoulder to shoulder - so our ancestors taught us. If you stay here, you will condemn the community to extinction.}
{248}{}{你的父母也被强迫劳动。不管你愿不愿意，你都必须拯救他们。血换血，肩并肩——这是我们祖先教导我们的。如果你留在这里，你将使这个社区走向灭绝。}

### {250}{}{They all piled up at once at the most unexpected moment. All able-bodied people were tied up and taken away to the east in the morning. Jose knows more, ask him.}
{250}{}{在最意想不到的时刻，它们都立刻堆积起来了。早上，所有身体健全的人都被绑起来，被带到东部。何塞知道更多，问问他。}
### {251}{}{There was a whole massacre at the town hall. Several were killed, others were maimed. If your nerves are weak, it's better not to go there.}
{251}{}{市政厅发生了一场大屠杀。一些人被杀，其他人致残。如果你的神经衰弱，最好不要去那里。}
### {252}{}{Your padre and madre were also taken away. So hurry up before anything worse happens to them.}
{252}{}{你的牧师和夫人也被带走了。所以，在他们发生更糟糕的事情之前，赶紧行动起来。}
### {253}{}{Well of course. Only the old people knew about the Founder's secret room. There are ancient things and knowledge stored there, which everyone in the Villa is not supposed to know about. Padre would have taken you to this room anyway, when he thought it was necessary.}
{253}{}{当然。只有老人们知道创始人的秘密房间。那里储存着古老的东西和知识，而别墅里的每个人都不应该知道这些。帕德雷认为有必要的时候，无论如何都会带你去这个房间。}
### {254}{}{Obviously stupid. First find Jose and ask about the raid. And then go after the raiders. Then you will have to decide for yourself.}
{254}{}{显然很愚蠢。首先找到Jose，询问突袭情况。然后追上袭击者。那你就得自己决定了。}
### {1254}{}{Obviously stupid. First find Jose and ask about the raid. And then go after the raiders. Then you will have to decide for yourself.}
{1254}{}{显然很愚蠢。首先找到Jose，询问突袭情况。然后追上袭击者。那你就得自己决定了。}
### {255}{}{But the old people have always taught us that you can't use ancient things. Did even the Founder break this taboo?}
{255}{}{但是老人们一直教导我们不能使用古老的东西。连创始人都打破了这个禁忌吗？}
### {256}{}{Don't jump to conclusions. Taboos were invented to protect you from the dangers of old things. But not all of them are really dangerous, and some are even useful.}
{256}{}{不要妄下结论。禁忌的发明是为了保护你免受旧事物的危险。但并不是所有这些都是真正危险的，有些甚至是有用的。}
### {257}{}{Perhaps if we knew more about ancient things, we would be ready for the attack of the raiders.}
{257}{}{也许如果我们对古代事物有更多的了解，我们就会为袭击者的袭击做好准备。}
### {258}{}{(inhales thoughtfully and lets out clouds of black smoke) The founder didn't think so. He said that our business is to grow crops. This is the only way we were able to survive in difficult times. And we had a good life without old technologies. Would life be better with them? I don't know. Nobody knows.}
{258}{}{（若有所思地吸了一口气，冒出滚滚黑烟）创始人不这么认为。他说我们的生意是种植庄稼。这是我们在困难时期生存下来的唯一途径。在没有旧技术的情况下，我们过着美好的生活。有了他们生活会更好吗？我不知道。没人知道。}
### {259}{}{Granny Adonsia, so you knew the Founder?}
{259}{}{阿东西娅奶奶，你认识创始人吗？}
### {260}{}{Oh, it was so long ago that I don't even remember his face. I remember the mustache, but I don't have a face. But this is a thing of the past, don't worry your head. You have more important questions.}
{260}{}{哦，那是很久以前的事了，我甚至都不记得他的脸了。我记得胡子，但我没有脸。但这已经是过去的事了，别担心。你还有更重要的问题。}

### {261}{}{Grandma, did you know that the Founder was a traitor to his sanctuary?}
{261}{}{奶奶，你知道创始人是他的避难所的叛徒吗？}
### {262}{}{That's how. Did the padre show you his notes? Well, Felix's burden was heavy and his conscience came to him in nightmares at night. It's not for you to judge him. He gave life to this place, albeit at the cost of many deaths. So appreciate it.}
{262}{}{就是这样。牧师给你看他的笔记了吗？费利克斯的负担很重，他的良心在晚上的噩梦中降临到他身上。你不能评判他。他给了这个地方生命，尽管付出了许多死亡的代价。非常感谢。}
### {263}{}{Don't fill your head with idle thoughts. That's not what we need to do right now.}
{263}{}{不要让你的脑子里充满无聊的想法。这不是我们现在需要做的。}

#After the plot ends
### {300}{}{You shouldn't have come back to the Villa after everything you've done.}
{300}{}{你不应该在做了所有的事情之后回到维拉。}
### {1300}{}{You shouldn't have come back to the Villa after everything you've done.}
{1300}{}{你不应该在做了所有的事情之后回到维拉。}
### {301}{}{Oh, come on. It's like you're all so righteous here.}
{301}{}{哦，得了吧。你们在这里好像都很正直。}
### {302}{}{The wastelands opened my eyes to the world. You are living wrong.}
{302}{}{荒原让我大开眼界。你活得不对。}
### {303}{}{It's not up to you to decide how we live! The villa survived thanks to the traditions and foundations that we chose. And no Wastelands can dictate to us another way. But you...}
{303}{}{我们的生活方式不是由你决定的！由于我们选择的传统和基础，别墅得以幸存。没有一片荒原可以对我们另辟蹊径。但是你。。。}
### {304}{}{?}
{304}{}{？}
### {305}{}{You're just a hypocrite who bottlecaps up his stupidity with the outside world! Go away and don't come back. I curse you, }
{305}{}{你只是一个伪君子，把自己的愚蠢与外界联系在一起！走开，别回来。我诅咒你，}
### {306}{}{!}
{306}{}{！}
### {307}{}{Take it easy, Grandma.}
{307}{}{别紧张，奶奶。}
### {308}{}{You are the hypocrites here. I won't take another step into this shithole.}
{308}{}{你们是这里的伪君子。我再也不会踏入这个粪坑了。}
### {309}{}{The Founder of the Villa himself warned us to stick together. But it's too late now. This infection cannot be stopped as long as the memory of you is alive.}
{309}{}{别墅的创始人亲自警告我们要团结一致。但现在已经太晚了。只要你的记忆还活着，这种感染就无法阻止。}
### {310}{}{By the way, what happened to the Founder?}
{310}{}{顺便问一下，创始人怎么了？}

### {320}{}{I'm proud of you, }
{320}{}{我为你感到骄傲，}
### {321}{}{.}
{321}{}{。}
### {322}{}{Really?}
{322}{}{真正地}
### {323}{}{It's nice to hear that.}
{323}{}{很高兴听到这个消息。}
### {324}{}{You have come a long way, but you have remained faithful to your home and your family. Now I can retire knowing that the Villa is in safe hands.}
{324}{}{你已经走了很长的路，但你仍然忠于你的家和家人。现在我可以退休了，因为我知道维拉在安全的手中。}
### {1324}{}{You've come a long way, but you've stayed true to your home and your family. Now I can retire knowing that the Villa is in safe hands.}
{1324}{}{你已经走了很长的路，但你忠于你的家和家人。现在我可以退休了，因为我知道维拉在安全的手中。}
### {325}{}{How could you doubt me?}
{325}{}{你怎么会怀疑我？}
### {326}{}{Thanks for the kind words, Grandma.}
{326}{}{谢谢你的客气话，奶奶。}
### {327}{}{The old people know a little more than the rest. We knew about the outer cities, and about the technologies of the Old World. And about the fact that only a common misfortune can unite people. And when people are doing well, there is no reason to restrain their selfishness.}
{327}{}{老人们知道的比其他人多一点。我们知道外面的城市和旧世界的技术。只有共同的不幸才能使人们团结起来。当人们做得好的时候，没有理由抑制他们的自私。}
### {328}{}{Not without it.}
{328}{}{没有它。}
### {329}{}{Again these moralizing ...}
{329}{}{再次这些道德说教。。。}
### {330}{}{Then conflicts and family breakdown begin. Perhaps the story of the raid was very useful - it reminded us that we should stick together. The founder of the Villa understood this well and prescribed it in his address to the descendants.}
{330}{}{然后，冲突和家庭破裂开始了。也许这次突袭的故事非常有用——它提醒我们应该团结一致。别墅的创始人很清楚这一点，并在给后代的讲话中规定了这一点。}
### {331}{}{By the way, what happened to him?}
{331}{}{顺便问一下，他怎么了？}

### {340}{}{So, }
{340}{}{所以}
### {341}{}{, you're here. Just like at the beginning of the journey. But something has changed in you, hasn't it?}
{341}{}{，你来了。就像旅程开始时一样。但你身上发生了一些变化，不是吗？}
### {342}{}{Oh, come on. As if you're all so righteous here.}
{342}{}{哦，来吧。好像你们在这里都很正直。}
### {343}{}{The wastelands have changed us all. It's okay to change.}
{343}{}{荒原改变了我们所有人。可以改变。}
### {344}{}{Until now, the Villa has survived thanks to the traditions and foundations that we have chosen. And no Wastelands can dictate to us another way. You should listen more to the opinion of your family.}
{344}{}{到目前为止，由于我们所选择的传统和基础，别墅得以幸存。没有一片荒原可以对我们另辟蹊径。你应该多听听家人的意见。}
### {345}{}{I'm not going to argue with you. My decisions have already been made.}
{345}{}{我不会和你争论的。我的决定已经做出了。}
### {346}{}{Maybe you're right. So what?}
{346}{}{也许你是对的。那又怎样？}
### {347}{}{The Founder of the Villa himself warned us to stick together. But now it's too late - a raid on the Villa could rally the community. Your intervention can create discord.}
{347}{}{别墅的创始人亲自警告我们要团结一致。但现在已经太晚了——对别墅的突袭可能会让社区团结起来。你的干预可能会造成不和。}
### {348}{}{By the way, what happened to the Founder? For some reason, I do not know the whole story.}
{348}{}{顺便问一下，创始人怎么了？出于某种原因，我不知道整个故事。}

### {350}{}{He died prematurely from hard work in the fields and construction sites. We did not bury it in the ground according to tradition. Instead, they were taken to a cave and surrounded with a brick sarcophagus. This crypt is still well preserved.}
{350}{}{他因在田里和建筑工地辛勤工作而过早去世。我们没有按照传统把它埋在地下。相反，他们被带到一个洞穴，周围是一个砖砌石棺。这个墓穴至今保存完好。}
### {351}{}{I've never been there. Can you show me this crypt?}
{351}{}{我从来没有去过那里。你能给我看看这个墓穴吗？}
### {1351}{}{I've never been there. Can you show me this crypt?}
{1351}{}{我从来没有去过那里。你能给我看看这个墓穴吗？}
### {352}{}{Curious. I think it's time for me to go. Bye, Grandma.}
{352}{}{好奇的我想我该走了。再见，奶奶。}
### {353}{}{Good. Perhaps a visit to his crypt will stir up your callous soul.}
{353}{}{好的也许去他的墓穴会激起你冷酷无情的灵魂。}
### {354}{}{Good. I think you deserve to visit this shrine.}
{354}{}{好的我认为你应该参观这个圣地。}
### {355}{}{Good. Perhaps a visit to the crypt will spiritualize you.}
{355}{}{好的也许去地下室会让你精神化。}
### {356}{}{Let's go. I can leave right now.}
{356}{}{我们走吧。我现在可以走了。}
### {357}{}{It's not up to that now. I'll go there when I get more free time.}
{357}{}{现在还没到那个地步。我有更多空闲时间就去那里。}

### {360}{}{Close the door behind you if you're going to leave.}
{360}{}{如果你要离开，就把门关上。}
### {361}{}{I'm already leaving. Bye, Grandma.}
{361}{}{我已经走了。再见，奶奶。}
### {362}{}{I want to see the Founder's crypt. Can you take me there?}
{362}{}{我想看看创始人的地下室。你能带我去那里吗？}
