### {100}{}{You see Jose Solis.}
{100}{}{你看到了何塞·索利斯。}
### {101}{}{Here is a ghoul in a pre-war suit. He looks much neater and cleaner than other ghouls.}
{101}{}{这是一个穿着战前西装的食尸鬼。他看起来比其他食尸鬼整洁得多。}
### {102}{}{You seem to be new here. Do you want to buy me a drink and tell me a little about yourself?}
{102}{}{你似乎是新来的。你想请我喝一杯，然后告诉我一些你自己的情况吗？}
### {103}{}{My dreams of Jose Solis' Mariachi are over.}
{103}{}{我对何塞·索利斯的马里亚奇的梦想结束了。}
### {104}{}{"Jose Solis' Mariachi" back in business!}
{104}{}{“Jose Solis‘Mariachi”重返商界！}
### {105}{}{Don't distract me, I'm busy rehearsing. Shoo! Shoo!}
{105}{}{别分散我的注意力，我正忙于排练。嘘！嘘！}

### {200}{}{Hello, man. I heard that there was a normal in town, but I thought it was another stupid joke of the oldies. And now you're here, blinding me with white skin and making me remember the old days. By the way, my name is Jose Solis. And you?}
{200}{}{你好，伙计。我听说城里有一个正常的，但我觉得这又是一个愚蠢的老笑话。现在你在这里，让我白皮肤失明，让我想起过去的日子。顺便说一下，我的名字叫何塞·索利斯。你呢？}
### {201}{}{I }
{201}{}{我}
### {202}{}{.}
{202}{}{。}
### {203}{}{ Damn nice to meet you, }
{203}{}{很高兴见到你，}
### {204}{}{. How do you like our little hell's corner? Bored already?}
{204}{}{.你觉得我们的小角落怎么样？无聊了吗？}
### {205}{}{I }
{205}{}{我}
### {206}{}{. Remember that name, ghoul.}
{206}{}{。记住那个名字，食尸鬼。}
### {207}{}{Okay, okay, }
{207}{}{好吧，好吧，}
### {208}{}{. I see you don't really like it here. Or am I wrong?}
{208}{}{。我看你不是很喜欢这里。还是我错了？}
### {209}{}{Normal. You can live.}
{209}{}{典型的你可以活着。}
### {210}{}{It's strange to hear this from normie. It seems that you want to trick me around your finger. Okay. So what do you need here?}
{210}{}{听到诺米这么说真奇怪。你好像想欺骗我。可以那么你在这里需要什么？}
### {211}{}{It's kind of boring.}
{211}{}{这有点无聊。}
### {212}{}{That's for sure! I want to shake this place up a little myself. So what do you need here?}
{212}{}{这是肯定的！我想自己把这个地方改造一下。那么你在这里需要什么？}
### {213}{}{Oh, nothing definite. Just looking around. Bye.}
{213}{}{哦，没什么确切的。只是环顾四周。再见}
### {214}{}{Can I ask you a few questions?}
{214}{}{我能问你几个问题吗？}
### {215}{}{Greetings, friend of misfortune! I heard that a new one has appeared in the city, but not from the Necropolis. It's an amazing thing. By the way, my name is Jose Solis. And you?}
{215}{}{问候，不幸的朋友！我听说城里出现了一个新的，但不是从墓地来的。这是一件了不起的事情。顺便说一下，我的名字叫何塞·索利斯。你呢？}
### {1215}{}{Greetings, beautiful lady! I heard that a new girl appeared in the city, but not from the Necropolis. You know how to surprise an old man. By the way, my name is Jose Solis. And you?}
{1215}{}{问候，美丽的女士！我听说城里出现了一个新女孩，但不是从墓地来的。你知道如何给一个老人一个惊喜。顺便说一下，我的名字叫何塞·索利斯。你呢？}
### {216}{}{Yes, perhaps. It's even better than the Necropolis. But this is just the beginning! Someday we will restore the city to its original appearance ? then you will lose your head with happiness. And how can I help you now?}
{216}{}{是的，也许吧。它甚至比墓地还要好。但这仅仅是一个开始！总有一天我们会把这座城市恢复原状? 那么你就会因为幸福而失去理智。我现在能帮你什么？}
### {217}{}{That's for sure! I want to shake this place up a little myself. So how can I help you?}
{217}{}{这是肯定的！我想自己把这个地方改造一下。我能帮你什么？}

### {220}{}{Greetings, friend of misfortune!}
{220}{}{问候，不幸的朋友！}
### {1220}{}{Greetings, my love!}
{1220}{}{问候，我的爱人！}
### {221}{}{Welcome, }
{221}{}{欢迎}
### {222}{}{.}
{222}{}{。}
### {223}{}{How can I help you, }
{223}{}{我能帮你什么，}
### {224}{}{.}
{224}{}{。}
### {225}{}{I know you, }
{225}{}{我认识你，}
### {226}{}{. You're nothing but trouble. Be reasonable and don't bother me in vain.}
{226}{}{。你不过是个麻烦。讲道理，不要白打扰我。}
### {227}{}{Greetings, Senor normie.}
{227}{}{你好，诺米先生。}
### {1227}{}{Greetings, Senora Normalka.}
{1227}{}{问候，诺马尔卡夫人。}
### {228}{}{Greetings, }
{228}{}{问候，}
### {229}{}{. I hope you're smart enough not to cause problems here.}
{229}{}{。我希望你足够聪明，不要在这里制造麻烦。}
### {230}{}{I think I should go.}
{230}{}{我想我应该走了。}
### {231}{}{Well, thanks for the conversation. Recently, the normies tried not to talk to us, but immediately fired from all barrels. Very not sociable guys.}
{231}{}{谢谢你的谈话。最近，正常人试图不和我们说话，但立即开火。不善于交际的家伙。}
### {232}{}{Goodbye.}
{232}{}{再见}

### {240}{}{Sure. Spit it out.}
{240}{}{当然吐出来。}
### {241}{}{Only if you finally leave me alone after that.}
{241}{}{只有在那之后你最终离开我。}
### {242}{}{What's going on here?}
{242}{}{这是怎么回事？}
### {243}{}{Nothing special. The usual routine life in a big city.}
{243}{}{没什么特别的。大城市的日常生活。}
### {244}{}{Hmm. Okay.}
{244}{}{嗯。好的。}

### {250}{}{Do you like it here yourself?}
{250}{}{你自己喜欢这里吗？}
### {251}{}{Not a bad city. Good climate, good people. But you know, San Diego used to be famous for its cultural life. And now here you can only hear the singing of the Geiger counter.}
{251}{}{不错的城市。好的气候，好的人。但你知道，圣地亚哥曾经以其文化生活而闻名。现在你只能听到盖革计数器的歌声。}
### {252}{}{Yes, I would like to listen to someone live.}
{252}{}{是的，我想听别人直播。}
### {253}{}{Are you kidding? These ruins are a hundred years old. There is no one to speak here.}
{253}{}{你在开玩笑吗？这些废墟已有一百年的历史。这里没有人说话。}
### {254}{}{Then smile, baby. This is Jose Solis! My ensemble was known throughout Baja California. It was a good time. We were just giving a concert in Bakersfield when the bombs fell on the city. I miraculously survived then. And just now I'm thinking of going back to the old craft.}
{254}{}{那就微笑吧，宝贝。这是何塞·索利斯！我的乐团在整个下加利福尼亚州都很出名。那是一段美好的时光。炸弹落在城市上空时，我们正在贝克斯菲尔德举行音乐会。我奇迹般地活了下来。而现在我正在考虑回到旧的工艺。}
### {255}{}{And what's in the way?}
{255}{}{什么挡住了去路？}
### {256}{}{Well, first of all I need new guitar strings. She's in my room right now. And it's not so easy to find them among these ruins.}
{256}{}{首先，我需要新的吉他弦。她现在在我的房间里。在这些废墟中找到它们并不容易。}
### {257}{}{I'll find you some strings. For me there is nothing that cannot be found in the old cities.}
{257}{}{我给你找些绳子。对我来说，在古城里没有什么是找不到的。}
### {258}{}{Gracias, senor! Together we will remind the Glow of the old days.}
{258}{}{谢谢，先生！我们将一起让Glow想起过去的日子。}
### {1258}{}{Gracias, senorita! Together we will remind the Shining of old times.}
{1258}{}{谢谢，小姐！我们将一起提醒光辉的旧时光。}
### {259}{}{Goodbye.}
{259}{}{再见}
### {260}{}{Can you at least pay me for this job?}
{260}{}{你至少能付我这份工作的钱吗？}
### {261}{}{To be honest, I don't have any caps right now. How about a share of the first fees?}
{261}{}{老实说，我现在没有瓶盖。第一笔费用分成如何？}
### {262}{}{I'm in. I'll find you some strings.}
{262}{}{我在。我会给你找一些线索。}
### {263}{}{I don't need any caps or extra hassle. Be.}
{263}{}{我不需要任何瓶盖或额外的麻烦。是}
### {264}{}{Sorry, it's not for me. Goodbye.}
{264}{}{对不起，这不是给我的。再见。}
### {265}{}{Do you know where you can find guitar strings?}
{265}{}{你知道在哪里可以找到吉他弦吗？}
### {266}{}{I have already climbed all the local ruins, there are no strings here. It remains only to visit Tijuana. At one time there was a Mariachi museum and several beautiful performance stages. And now there are crowds of robots and mutants.}
{266}{}{我已经爬遍了当地所有的废墟，这里没有绳子。它仍然只是访问蒂华纳。曾经有一个马里亚奇博物馆和几个美丽的表演舞台。现在有一群机器人和变种人。}
### {267}{}{Tijuana, then. I see.}
{267}{}{蒂华纳。我明白了。}
### {268}{}{Have you tried out new guitar strings yet?}
{268}{}{你试过新的吉他弦了吗？}
### {269}{}{Oh, it sounds great! Besides, it's easier for my stiff skin to clamp the strings now. Thank you, smooth-skinned amigo.}
{269}{}{哦，听起来很棒！此外，我僵硬的皮肤现在更容易夹紧绳子了。谢谢你，皮肤光滑的朋友。}
### {270}{}{No problem. When is the next performance?}
{270}{}{没问题。下一场演出是什么时候？}
### {271}{}{Don't be in such a hurry! I haven't prepared properly yet. And the most important thing is that I can't perform alone, without my beautiful companions!}
{271}{}{别这么着急！我还没有做好准备。最重要的是，没有我美丽的同伴，我无法独自表演！}
### {272}{}{So are they here, too, in the Glow?}
{272}{}{那么他们也在这里，在辉光中吗？}
### {273}{}{Trumpeter Fernando works at the dam, and senorita Beatriz is at a diner in the southern camp. Surely you will pass by, will you bring them to me?}
{273}{}{小号手费尔南多在大坝上工作，比阿特丽斯小姐在南部营地的一家餐厅里。你一定会经过，你会把它们带到我身边吗？}
### {274}{}{Okay. Why not?}
{274}{}{可以为什么不呢？}
### {275}{}{If I bring your companions, what will I get for it?}
{275}{}{如果我带上你的同伴，我会得到什么？}
### {276}{}{I'm in. I'll bring your companions.}
{276}{}{我来了。我会带上你的同伴。}
### {277}{}{Looking forward to it!}
{277}{}{期待它！}
### {278}{}{Goodbye.}
{278}{}{再见}
### {279}{}{Where can I find Fernando?}
{279}{}{我在哪里能找到费尔南多？}
### {280}{}{Trumpeter Fernando works at the Bonita Dam.}
{280}{}{小号手费尔南多在博尼塔大坝工作。}
### {281}{}{Where can I find Beatrice?}
{281}{}{我在哪里可以找到碧翠丝？}
### {282}{}{Senorita Beatriz works at a diner in the San Isidro neighborhood.}
{282}{}{Senorita Beatriz在圣伊西德罗社区的一家餐馆工作。}
### {283}{}{Clear. Another question.}
{283}{}{清楚的另一个问题。}
### {284}{}{Goodbye.}
{284}{}{再见}
### {285}{}{Fernando and Beatrice are already here.}
{285}{}{费尔南多和碧翠丝已经到了。}
### {286}{}{Excellent! We have a lot to talk about with them. Come to our first concert in a day.}
{286}{}{杰出的我们有很多事情要和他们谈。来参加我们一天内的第一场音乐会。}
### {287}{}{Okay. Have a good rehearsal.}
{287}{}{可以好好排练。}
### {288}{}{Fernando is already here. But Beatrice died.}
{288}{}{费尔南多已经来了。但是比阿特丽斯死了。}
### {289}{}{Poor Beatrice! Finally, she has suffered in this life. Even a little enviable...}
{289}{}{可怜的碧翠丝！最后，她在这一生中遭受了痛苦。甚至有点令人羡慕...}
### {290}{}{Beatrice is already here. But Fernando died.}
{290}{}{碧翠丝已经来了。但是费尔南多死了。}
### {291}{}{Poor Fernando! Finally, he has suffered in this life. Even a little envious...}
{291}{}{可怜的费尔南多！最后，他在这一生中遭受了痛苦。甚至有点嫉妒...}
### {292}{}{Woe to me! A dream slips out of your hands like ashes between your fingers... listen, what about a hologram? I know, there is one preserved in the Chula Vista shopping center. Maybe she will replace the missing participants for me? Will you bring the holographic module? I will certainly be able to reconfigure it for my purposes.}
{292}{}{我真倒霉！一个梦从你的手中滑落，就像你手指间的灰烬...听着，全息图怎么样？我知道，Chula Vista购物中心保存着一个。也许她会替我替换那些失踪的参与者？你会带来全息模块吗？我肯定能够为我的目的重新配置它。}
### {293}{}{Seriously? Okay, we'll have to look for this thing, otherwise you'll kill yourself like that.}
{293}{}{认真地好吧，我们得去找这个东西，否则你会那样自杀的。}
### {294}{}{I have a holographic module. Here you go.}
{294}{}{我有一个全息模块。给你。}
### {295}{}{Fernando and Beatrice are dead.}
{295}{}{费尔南多和碧翠丝死了。}
### {296}{}{Fernando and Beatrice died. I'm sorry.}
{296}{}{费尔南多和碧翠丝死了。对不起。}
### {297}{}{Excellent! I need time to prepare. Come to our first concert in a day.}
{297}{}{杰出的我需要时间准备。来参加我们一天内的第一场音乐会。}
### {298}{}{Okay. Have a good rehearsal.}
{298}{}{可以好好排练。}
### {299}{}{It's the old man }
{299}{}{是老人}
### {1299}{}{This is my goddess of inspiration, }
{1299}{}{这是我的灵感女神，}
### {300}{}{! It's like you brought me back to 2077. It's been a long time since I've been so happy. By the way, we made a lot of money on this performance. Here's your share, 1000 habaks. Thank you for your help, partner.}
{300}{}{！就像你把我带回了2077年。我已经很久没有这么开心了。顺便说一句，我们这次演出赚了很多钱。这是你的一份，1000个哈巴克人。谢谢你的帮助，伙伴。}
### {1300}{}{! It's like you brought me back to 2077. It's been a long time since I've been so happy. By the way, we made a lot of money on this performance. Here's your share, 1000 habaks. Thank you for your help, senora.}
{1300}{}{！就像你把我带回了2077年。我已经很久没有这么开心了。顺便说一句，我们这次演出赚了很多钱。这是你的一份，1000个哈巴克人。谢谢你的帮助，小姐。}
### {301}{}{Good luck, Jose.}
{301}{}{祝你好运，何塞。}
### {302}{}{! It's like you brought me back to 2077. It's been a long time since I've been so happy. By the way, we made a lot of money on this performance. Here's your share, 1000 habaks. And also from me personally ? this wonderful century-old whiskey. Thank you for your help, partner.}
{302}{}{！就像你把我带回了2077年。我已经很久没有这么开心了。顺便说一句，我们这次演出赚了很多钱。这是你的一份，1000个哈巴克人。还有我个人? 这种美妙的百年威士忌。谢谢你的帮助，伙伴。}
### {1302}{}{! It's like you brought me back to 2077. It's been a long time since I've been so happy. By the way, we made a lot of money on this performance. Here's your share, 1000 habaks. And also from me personally ? this wonderful century-old whiskey. Thank you for your help, senora.}
{1302}{}{！就像你把我带回了2077年。我已经很久没有这么开心了。顺便说一句，我们这次演出赚了很多钱。这是你的一份，1000个哈巴克人。还有我个人? 这种美妙的百年威士忌。谢谢你的帮助，小姐。}
### {303}{}{What do you call the band?}
{303}{}{你怎么称呼这支乐队？}
### {304}{}{Hmm, we need something romantic. Maybe "Last Breath"? Or ? "Love in hell"? Maybe "A Kiss before death"? What about...}
{304}{}{嗯，我们需要一些浪漫的东西。也许是《最后的呼吸》？或? “地狱里的爱”？也许是“死前之吻”？那么...怎么样}
### {305}{}{I think it would be easier to name after you.}
{305}{}{我想以你的名字命名会更容易。}
### {306}{}{Mariachi de Jose Solis? Of course!}
{306}{}{Mariachi de Jose Solis？当然}
### {307}{}{That's nice...}
{307}{}{太好了...}
### {308}{}{By the way, what do you call the band?}
{308}{}{顺便问一下，你叫这支乐队什么？}
