### {100}{}{In front of you is Distraught.}
{100}{}{你面前是心烦意乱。}
### {101}{}{You see a glowing ghoul with a distraught look. He seems hostile.}
{101}{}{你看到一个容光焕发的食尸鬼，神情悲痛欲绝。他似乎怀有敌意。}
### {102}{}{The distraught Gonzo does not react to you in any way.}
{102}{}{悲痛欲绝的贡佐对你没有任何反应。}
### {103}{}{Ar-r-r!}
{103}{}{Ar-r-r！}
### {104}{}{The ghoul himself is to blame. The pile has nothing to do with it.}
{104}{}{食尸鬼自己应该受到谴责。这堆东西与它无关。}

### {200}{}{Hr-r-r... h-man... a ghoul... fear...}
{200}{}{小时-小时...h-man...一个食尸鬼...害怕}
### {201}{}{I'm a friend, I want to help you.}
{201}{}{我是朋友，我想帮助你。}
### {202}{}{... friend... love... life...}
{202}{}{朋友爱生活}
### {203}{}{Yes, yes, your ghoul friends are worried about you. Let's go to them, they'll take care of you.}
{203}{}{是的，是的，你的食尸鬼朋友很担心你。我们去找他们吧，他们会照顾你的。}
### {204}{}{Gonzo... wants... to friends...}
{204}{}{极不寻常的想要...给朋友...}
### {205}{}{Let's go right now before you change your mind.}
{205}{}{在你改变主意之前，我们现在就走吧。}
### {206}{}{No, no, it will work right now. Wait here a bit.}
{206}{}{不，不，现在就行。在这里等一下。}
### {207}{}{Ah, you're crazy! I'm afraid of you!}
{207}{}{啊，你疯了！我害怕你！}
### {208}{}{Life. And death. Your death!}
{208}{}{生活还有死亡。你的死！}
