### {100}{}{You see a Trucker.}
{100}{}{你看到一个卡车司机。}
### {101}{}{In front of you is one of the guards of the caravan.}
{101}{}{在你面前的是商队的一名警卫。}
### {102}{}{Hush! Now the main thing is not to get caught in the eyes of the damn mutyars.}
{102}{}{安静现在最重要的是不要被那些该死的穆蒂亚尔人盯上。}
### {103}{}{Ugh! Now you can relax.}
{103}{}{啊！现在你可以放松了。}
### {104}{}{OK, I'm coming for you. You know how to get out of here unnoticed, right?}
{104}{}{好的，我来接你。你知道如何在不被注意的情况下离开这里，对吧？}
### {105}{}{Yes, the right idea. We need to be below the grass so that we are not noticed.}
{105}{}{是的，正确的想法。我们需要在草地下面，这样我们就不会被注意到。}
### {106}{}{The trucker is safe.}
{106}{}{卡车司机很安全。}
### {107}{}{What do they allow themselves? A little more and I'll stuff their faces!}
{107}{}{他们允许自己做什么？再多一点，我就塞他们的脸！}

### {110}{}{Thank you for saving us.}
{110}{}{谢谢你救了我们。}
### {111}{}{These super mutants would have already pulverized us if it weren't for you.}
{111}{}{如果不是你，这些超级变种人早就把我们粉碎了。}
### {112}{}{It was a great fortune to meet you.}
{112}{}{见到你真是太幸运了。}
### {113}{}{The way back won't be any easier.}
{113}{}{回来的路不会更容易。}
### {114}{}{I wonder if there's a bar here?}
{114}{}{我想知道这里有没有酒吧？}

### {120}{}{Rutegra is no more. Who will negotiate with the ghouls?}
{120}{}{Rutegra已经不在了。谁来和食尸鬼谈判？}
### {121}{}{Without Rutger, the return journey will be especially difficult.}
{121}{}{没有罗格，回程将特别困难。}
### {122}{}{Because of Rutger's death, we may not be paid at all.}
{122}{}{因为罗格的死，我们可能根本得不到报酬。}

### {130}{}{After the explosion on the island, it became clear that NOTHING could be taken out of here.}
{130}{}{岛上发生爆炸后，很明显，这里什么都拿不出来。}
### {131}{}{Gustavo is trying to drive us out of town. He's crazy!}
{131}{}{古斯塔沃想把我们赶出小镇。他疯了！}
### {132}{}{Butler reached the military base. Soon we will be swimming in caps!}
{132}{}{巴特勒到达了军事基地。很快我们就要戴着帽子游泳了！}
### {133}{}{}
{133}{}{error : string is empty}
### {134}{}{Ghouls scurry like ants after napalm. This is the first time I've seen this. Well, that's good for our wallet.}
{134}{}{食尸鬼像蚂蚁一样追逐凝固汽油弹。这是我第一次看到这个。这对我们的钱包有好处。}
