### {100}{}{In front of you is a ghoul.}
{100}{}{在你面前是一个食尸鬼。}
### {101}{}{You see an ordinary ghoul.}
{101}{}{你看到一个普通的食尸鬼。}

### {102}{}{Oh, thank you, you're just in time.}
{102}{}{哦，谢谢你，你来得正是时候。}
### {103}{}{This food has cooled down! Okay, there's nothing you can do. Come here.}
{103}{}{这食物凉了！好吧，你无能为力，过来。}
### {104}{}{You enjoy serving food, don't you? Thank you.}
{104}{}{你喜欢上菜，不是吗？非常感谢。}
### {105}{}{This is exactly what I want!}
{105}{}{这正是我想要的！}
### {106}{}{Thank you. But I don't have a tip.}
{106}{}{非常感谢。但我没有小费。}
### {107}{}{(}
{107}{}{(}
### {108}{}{) The customer has received his order.}
{108}{}{)客户已收到订单。}
### {109}{}{This customer has already received his order.}
{109}{}{该客户已收到订单。}

### {110}{}{Oh, mommies, it's a man!}
{110}{}{哦，妈妈们，是个男人！}
### {111}{}{Smooth-skinned in the Glow? I don't believe my eyes!}
{111}{}{在辉光中皮肤光滑？我不相信我的眼睛！}
### {112}{}{What do these normies allow themselves?}
{112}{}{这些标准允许自己做什么？}
### {113}{}{We haven't had enough smooth-faces here yet.}
{113}{}{我们的脸还不够光滑。}
### {114}{}{The smooth-skinned even got us here.}
{114}{}{光滑的皮肤甚至把我们带到了这里。}

### {115}{}{This normie can be trusted.}
{115}{}{这个标准值得信赖。}
### {116}{}{The Man in the Glow? Madman!}
{116}{}{《发光的男人》？疯子！}
### {117}{}{The Normies made a mistake. They need time to figure it out.}
{117}{}{北欧人犯了一个错误。他们需要时间来弄清楚。}
### {118}{}{Perhaps not all smooth-faces are bad.}
{118}{}{也许并不是所有光滑的脸都是坏的。}
### {119}{}{We just want to live separately from the smooth-faced.}
{119}{}{我们只想与表面光滑的人分开生活。}

### {120}{}{The smooth-faced ones even got us here.}
{120}{}{脸光滑的人甚至把我们带到了这里。}
### {121}{}{Guess what my line is?}
{121}{}{猜猜我的台词是什么？}
### {122}{}{The Dayglow is a wonderful city.}
{122}{}{霞光是一座美丽的城市。}
### {123}{}{It's a pity Harold isn't with us. He went north.}
{123}{}{很遗憾哈罗德没有和我们在一起。他去了北方。}
### {124}{}{Don't move! I dropped my brains... Haha, my favorite joke.}
{124}{}{别动！我掉了脑袋...哈哈，我最喜欢的笑话。}
### {125}{}{And yet I will miss the Necropolis.}
{125}{}{然而我会想念墓地。}
### {126}{}{The necropolis is now deader than ever.}
{126}{}{墓地现在比以往任何时候都更加死气沉沉。}
### {127}{}{I still remember Seth's look with a shudder.}
{127}{}{我还记得赛斯战栗的表情。}
### {128}{}{Where is my hair? I left them in 2077. Ha-ha-ha!}
{128}{}{我的头发在哪里？我在2077年离开了他们。哈哈哈！}
### {129}{}{Sometimes I vaguely remember something from my past life.}
{129}{}{有时我模糊地记得我过去生活中的一些事情。}

### {130}{}{Everyone who could, rushed to Coronado Island.}
{130}{}{所有有能力的人都赶往科罗纳多岛。}
### {131}{}{It's been a long time since there was such a movement among the ghouls!}
{131}{}{食尸鬼们已经很久没有这样的运动了！}
### {132}{}{The one who opened the way for us to Coronado is our hero.}
{132}{}{为我们开辟通往科罗纳多之路的人是我们的英雄。}
### {133}{}{Coronado is ours now!}
{133}{}{科罗纳多现在是我们的了！}
### {134}{}{Here we will live now, with little things from Coronado!}
{134}{}{我们现在就住在这里，带着科罗纳多的小东西！}

### {135}{}{Eh, I had such plans for Coronado...}
{135}{}{呃，我对科罗纳多有这样的计划...}
### {136}{}{Coronado could be a Klondike. Sorry.}
{136}{}{科罗纳多可能是克朗代克。很抱歉}
### {137}{}{There is nothing left of Coronado Island at all.}
{137}{}{科罗纳多岛一无所有。}
### {138}{}{An old bomb exploded on the island. I wonder, by myself or with someone's help?}
{138}{}{一枚旧炸弹在岛上爆炸了。我想知道，是自己还是在别人的帮助下？}
### {139}{}{I was very lucky that I was not on the pier at the time of the explosion.}
{139}{}{我很幸运，爆炸发生时我不在码头上。}

### {150}{}{I'm standing, Chief! I'm standing rooted to the spot!}
{150}{}{我站着，长官！我站在原地不动！}
### {151}{}{My respects, Officer.}
{151}{}{尊敬的警官。}
### {152}{}{I am a law-abiding citizen.}
{152}{}{我是一个守法的公民。}
### {153}{}{It's nice to see the remnants of the law on the wastelands... Oh, it's not your badge!}
{153}{}{很高兴在荒原上看到法律的残余...哦，这不是你的徽章！}
### {154}{}{You must have almost a hundred years of service?}
{154}{}{你一定有将近一百年的服役经历？}
### {155}{}{Some played with the law like that. And in the end, they played the Third World War.}
{155}{}{有些人就这样玩弄法律。最后，他们打了第三次世界大战。}
### {156}{}{Am I arrested?}
{156}{}{我被捕了吗？}
