### {100}{}{This is Frank.}
{100}{}{这是弗兰克。}
### {101}{}{Here is a ghoul in a business suit and hat, just like in the good old days.}
{101}{}{这是一个穿着西装、戴着瓶盖的食尸鬼，就像过去一样。}
### {102}{}{Thank you, friend. Without you, this story could have ended very badly.}
{102}{}{谢谢你，朋友。如果没有你，这个故事的结局可能会很糟糕。}
### {103}{}{Don't touch me, smooth face! I'm on edge right now.}
{103}{}{别碰我，光滑的脸！我现在很紧张。}
### {104}{}{Sorry, I'm too excited to talk right now.}
{104}{}{对不起，我太激动了，现在不能说话。}

### {110}{}{Jane, if we don't find him, I'll stop drinking. I promise.}
{110}{}{简，如果我们找不到他，我就不喝酒了。我保证。}
### {111}{}{Prepare for the worst, Jane.}
{111}{}{做好最坏的打算，简。}
### {112}{}{It would have happened some day anyway.}
{112}{}{总有一天会发生的。}
### {113}{}{Don't cry. Otherwise I'll cry too.}
{113}{}{不要哭。否则我也会哭的。}
