### {100}{}{Here is the Pec.}
{100}{}{这是佩奇。}
### {101}{}{You see a ghoul with a twisted spine. His head was thickly overgrown with small glowing mushrooms.}
{101}{}{你看到一个脊椎扭曲的食尸鬼。他的头上长满了发光的小蘑菇。}
### {102}{}{No problem, sir. As soon as I'm done cleaning up, I'm out of here.}
{102}{}{没问题，先生。我一打扫完就离开这里。}

### {120}{}{I feel like a million.}
{120}{}{我感觉自己像个百万富翁。}
### {121}{}{I'm Peck. Paxter. Do you want to sleep with me?}
{121}{}{我叫派克。帕克斯特。你想和我睡觉吗？}
### {122}{}{Do you know how many caps I have? And I don't have caps. And I'm happy!}
{122}{}{你知道我有多少顶帽子吗？而且我没有帽子。我很高兴！}
### {123}{}{I didn't have any money before. Now no one has any money.}
{123}{}{我以前没有钱。现在没人有钱了。}
### {124}{}{I live like the star of a TV show.}
{124}{}{我的生活就像电视节目中的明星。}
### {125}{}{This is the best place in the world. Wee-ee-ee!}
{125}{}{这是世界上最好的地方。哇！}
### {126}{}{It's time for Pack to take his medicine. * Yum-yum * Bue-uh...}
{126}{}{帕克该吃药了。*百胜。。。}
### {127}{}{Cops! It's the cops! But no... Just a flashback...}
{127}{}{警察！是警察！但不是…只是一个闪回。。。}
### {128}{}{It's okay, I'm fine... it seems.}
{128}{}{没关系，我很好。。。看起来。}
### {129}{}{Without foreigners, Glow is not Glow.}
{129}{}{没有外国人，Glow就不是Glow。}
### {130}{}{I'm not homeless. I'm free from home!}
{130}{}{我不是无家可归的。我不在家了！}
### {131}{}{I don't do drugs. My brain produces it by itself.}
{131}{}{我不吸毒。它是我的大脑自己产生的。}
### {132}{}{Holy macaroni!}
{132}{}{神圣的通心粉！}

### {200}{}{Whoa, whoa, bro! Don't pick here, you're on my private property. Well... I don't mind you being here. But keep in mind.}
{200}{}{哇，哇，兄弟！别挑这里，你在我的私人领地上。好我不介意你在这里。但请记住。}
### {201}{}{Seriously? Do you live in a sewer?}
{201}{}{认真地你住在下水道里吗？}
### {202}{}{Yes, I'm homeless. And what? But I live richly! I live in the most picturesque place of Glow. Do you understand?}
{202}{}{是的，我无家可归。什么？但我生活富裕！我住在Glow最风景如画的地方。你明白吗？}
### {203}{}{Have you tried to move to the rest of the city?}
{203}{}{你试过搬到城市的其他地方去吗？}
### {204}{}{Why? I'm fine here. There is a lot of food, there is no need to observe the laws, peace and quiet.}
{204}{}{为什么？我在这里很好。这里有很多食物，没有必要遵守法律，宁静祥和。}
### {205}{}{I'm afraid to ask, what do you eat here?}
{205}{}{我不敢问，你在这里吃什么？}
### {206}{}{No wonder you're overgrown with mushrooms. Have you ever seen yourself in the mirror?}
{206}{}{怪不得你长满了蘑菇。你见过镜子里的自己吗？}
### {207}{}{Everything grows in the valley. I have enough. Here, do you want mushrooms?}
{207}{}{山谷里万物生长。我受够了。给，你想要蘑菇吗？}
### {208}{}{Come on. What will you ask in return?}
{208}{}{来吧。你会要求什么作为回报？}
### {209}{}{No need. I'm not into that.}
{209}{}{不需要。我不喜欢。}
### {210}{}{The local climate is too humid. There was no such thing in the Necropolis. But you don't have to go far to take the medicine. Do you want one too?}
{210}{}{当地气候太潮湿。墓地里根本没有这样的东西。但是你不需要走很远就可以吃药。你也想要一个吗？}
### {211}{}{You'll see ? you'll come back for a new dose.}
{211}{}{你会看到的? 你会回来服用新剂量的。}
### {212}{}{Yeah.}
{212}{}{是 啊}

### {220}{}{Hey, how are you?}
{220}{}{嘿，你好吗？}
### {221}{}{How are you, bro?}
{221}{}{你好吗，兄弟？}
### {1221}{}{How are you, sister?}
{1221}{}{你好吗，姐姐？}
### {222}{}{What is it, kid, got lost in the area?}
{222}{}{是什么，孩子，在这个地区迷路了？}
### {1222}{}{What is it, baby, got lost in the area?}
{1222}{}{是什么，宝贝，在这个地区迷路了？}
### {223}{}{Be.}
{223}{}{是}
### {224}{}{I need more of these glowing mushrooms.}
{224}{}{我需要更多这些发光的蘑菇。}

### {230}{}{How do I get out of here?}
{230}{}{我该怎么离开这里？}
### {231}{}{The nearest bridge is destroyed, bro. That's bad luck, right? Go up to the mall, from there turn onto federal highways. And now you're free!}
{231}{}{最近的桥被毁了，兄弟。那是运气不好，对吧？上到购物中心，从那里转入联邦高速公路。现在你自由了！}
### {232}{}{Okay, I'll go. Have a good stay.}
{232}{}{好的，我走。祝你住得愉快。}
### {233}{}{I'll pay 300 caps if you take me to San Ysidro.}
{233}{}{如果你带我去圣伊西德罗，我会付300顶。}
### {234}{}{I know what you mean. I understand. Peck knows all the local trails and dangerous places. You will not pass the valley without me.}
{234}{}{我知道你的意思。我理解。佩克知道当地所有的小路和危险的地方。没有我，你将无法通过山谷。}
### {235}{}{Then lead the way. Here }
{235}{}{然后带路。在这里}
### {236}{}{ caps.}
{236}{}{帽子。}
### {237}{}{Not now. Later.}
{237}{}{现在不行。后来}
### {238}{}{I need to get to the power plant. Will you take it for 500 caps?}
{238}{}{我需要去发电厂。你愿意花500顶帽子吗？}
### {239}{}{I will pay 1500 caps if you take me to the Old Town along safe paths.}
{239}{}{如果你带我沿着安全的小路去老城，我会付1500顶帽子。}
