### {100}{}{You see a looter ghoul.}
{100}{}{你看到一个抢劫食尸鬼。}
### {101}{}{There's a ghoul in front of you. He is carefully studying some objects.}
{101}{}{你面前有个食尸鬼。他正在仔细研究一些物体。}

### {200}{}{Hey, wait, don't come any closer! These are my things, I found them!}
{200}{}{嘿，等等，别再靠近了！这些是我的东西，我找到了！}
### {201}{}{If they were yours, they will become mine.}
{201}{}{如果它们是你的，它们就会变成我的。}
### {202}{}{Okay, whatever you say. These are your things.}
{202}{}{好吧，不管你说什么。这些是你的东西。}
### {203}{}{Hmm, it's rare to meet normal people here... Well, that is now rarely. And once whole crowds walked these streets. Here, bones are still sticking out of the sand all around.}
{203}{}{嗯，在这里很少见到正常人...现在很少这样了。曾经整群人走在这些街道上。在这里，骨头仍然从沙子里伸出来。}
### {204}{}{And what are you doing here?}
{204}{}{你在这里干什么？}
### {205}{}{I'm looking for valuables in these ruins. Previously, scavengers rarely looked here because of the robot border guard. But someone did us a big favor by disabling it.}
{205}{}{我在废墟中寻找贵重物品。以前，由于机器人边防，拾荒者很少来这里。但有人禁用了它，帮了我们一个很大的忙。}
### {206}{}{Then good luck. Bye.}
{206}{}{那么祝你好运。再见}
### {207}{}{Have you found anything valuable yet?}
{207}{}{你找到有价值的东西了吗？}
### {208}{}{Yes, here, look...}
{208}{}{是的，在这里，看...}
### {209}{}{[Trade]}
{209}{}{[贸易]}
### {210}{}{Hello, little man. Do you need any things from the ruins? I can search. I give it almost for nothing. And I'll also make a discount for you.}
{210}{}{你好，小个子。你需要废墟里的东西吗？我可以搜索。我几乎免费给它。我也会给你打个折扣。}
### {211}{}{Not today, senora.}
{211}{}{今天不行，小姐。}
### {212}{}{Show me what you have...}
{212}{}{让我看看你有什么...}
### {213}{}{Come back. Maybe I'll find something else useful in a couple of days.}
{213}{}{回来也许过几天我会发现其他有用的东西。}
### {214}{}{Goodbye.}
{214}{}{再见}
### {215}{}{Hey, do me a favor, don't touch my stuff. Ok? I found them!}
{215}{}{嘿，帮我个忙，别碰我的东西。好啊我找到他们了！}
### {216}{}{Hmm, so now I'm not the only one in these ruins... But once whole crowds walked these streets. Here, bones are still sticking out of the sand all around.}
{216}{}{嗯，所以现在我不是这些废墟中唯一的一个...但有一次，整群人走在这些街道上。在这里，骨头仍然从沙子里伸出来。}
