### {100}{}{You see the bodyguard De Santis.}
{100}{}{你看到了保镖德桑蒂斯。}
### {101}{}{Here is a ghoul in combat armor.}
{101}{}{这是一个身穿战甲的食尸鬼。}

### {110}{}{Welcome to the Gulsky paradise.}
{110}{}{欢迎来到古尔斯基天堂。}
### {111}{}{Keep quiet while you're at the hotel... if possible.}
{111}{}{在酒店时保持安静...如果可能的话。}
### {112}{}{Welcome to the hotel "La Pension".}
{112}{}{欢迎光临“La Pension”酒店。}
### {113}{}{Do you need an administrator? He's at the end of the corridor.}
{113}{}{你需要管理员吗？他在走廊的尽头。}
