### {102}{}{This emitter is de-energized.}
{102}{}{此发射器断电。}
### {103}{}{Now this emitter is useless.}
{103}{}{现在这个发射器没用了。}
### {104}{}{This emitter is badly damaged.}
{104}{}{这个发射器损坏严重。}
### {105}{}{You have managed to fix the problems. The emitter is ready for use again.}
{105}{}{你已经设法解决了问题。发射器已准备好再次使用。}
### {106}{}{The emitter is damaged!}
{106}{}{发射器损坏了！}
### {107}{}{A powerful pulse goes into the ground and spreads around, causing damage to any electronics on the way.}
{107}{}{一个强大的脉冲进入地面并四处传播，对途中的任何电子设备造成损坏。}
### {108}{}{The emitter is damaged.}
{108}{}{发射器损坏。}
### {109}{}{The emitter is already charged.}
{109}{}{发射器已充电。}
### {110}{}{You are charging the radiator battery.}
{110}{}{你正在给散热器电池充电。}
### {111}{}{This emitter burned out under its own voltage after the last use.}
{111}{}{最后一次使用后，这个发射器在自己的电压下烧坏了。}
