### {100}{}{This is Stanley.}
{100}{}{我是斯坦利。}
### {101}{}{You see a terribly bony ghoul in a dirty, worn-out robe. A piece of rebar sticks out of his head.}
{101}{}{你看到一个骨瘦如柴的食尸鬼，穿着又脏又破的长袍。一根钢筋从他的头上伸了出来。}
### {102}{}{Hello, belyashik. You don't look like a real ghost anymore.}
{102}{}{你好，贝利亚希克。你看起来不再像个真正的鬼了。}

### {200}{}{A-a-a, don't take me, I still want to live!}
{200}{}{阿，别带走我，我还想活着！}
### {201}{}{What are you talking about?}
{201}{}{你在说什么？}
### {202}{}{What the hell are you yelling at?!}
{202}{}{你在吼什么？！}
### {203}{}{Oh, Mommy, you're a human being?! Ugh, I thought you were a ghost. Why are you scaring me?}
{203}{}{哦，妈妈，你是人吗？！啊，我还以为你是个鬼呢。你为什么吓唬我？}
### {204}{}{I have the same question for you. You're walking around all black in the dark, only your eyes are glowing!}
{204}{}{我也有同样的问题要问你。你在黑暗中一身漆黑地走来走去，只有你的眼睛在发光！}
### {205}{}{Sorry, whitey, but I was so scared! You know, it's so lonely at these stations. But there were once rumors about a ghostly wagon that took people's souls to hell. It's silly to believe that now, of course. We're already in hell.}
{205}{}{对不起，whitey，但我太害怕了！你知道，在这些车站太孤独了。但曾经有传言说，一辆幽灵马车把人们的灵魂带到了地狱。当然，现在相信这一点是愚蠢的。我们已经下地狱了。}
### {206}{}{I'm sorry, it was an accident. I didn't expect to meet anyone here either.}
{206}{}{对不起，那是个意外。我也没想到会在这里遇到任何人。}
### {1206}{}{I'm sorry, it was an accident. I didn't expect to meet anyone here either.}
{1206}{}{对不起，那是个意外。我也没想到会在这里遇到任何人。}
### {207}{}{Once there were crowds of people at these stations. And now it's really deserted here. Probably, the ghost train has already taken everyone to hell. Don't you believe it? Well, look around ? we're already in hell.}
{207}{}{这些车站曾经挤满了人。现在这里真的很冷清。也许，幽灵列车已经把所有人都带到了地狱。你不相信吗？好吧，看看周围? 我们已经下地狱了。}
### {208}{}{So, what are you doing here anyway?}
{208}{}{那么，你在这里干什么？}
### {209}{}{My brothers asked me to prepare the Blue Line for launch. I used to work in the subway, so I can do something. But not everything.}
{209}{}{我的兄弟们让我为发射蓝线做准备。我以前在地铁工作，所以我可以做点什么。但并非所有。}
### {210}{}{What do I need to run?}
{210}{}{我需要跑什么？}
### {211}{}{First of all, we don't have any energy yet. And it seems that it can only be taken at the Bonita hydroelectric station, and it has been well guarded since the War. And it is necessary not only to start the station, but also to send it to the monorail substation.}
{211}{}{首先，我们还没有任何能量。它似乎只能在博尼塔水电站拍摄，自战争以来，这里一直受到严密的保护。不仅需要启动车站，还需要将其发送到单轨变电站。}
### {212}{}{And secondly?}
{212}{}{其次呢？}
### {213}{}{Secondly, the monorail line needs to be repaired. Mr. Assistants will do it for us when we start the power. To do this, they will disassemble some of the old lines. But the automation of the tram depot will have to be repaired by ourselves. And here I cannot do without an experienced electronics specialist. This thing is in the control room. Maybe a technician in San Ysidro will fix it, but it's damn heavy. Will you help me?}
{213}{}{其次，单轨线路需要维修。当我们启动电源时，助理先生将为我们做这件事。为了做到这一点，他们将拆除一些旧线路。但是电车站的自动化将不得不由我们自己修理。在这里，我离不开一位经验丰富的电子专家。这个东西在控制室里。也许圣伊西德罗的技术人员会修理它，但它太重了。你能帮我吗？}
### {214}{}{Sure. After all, then I will be able to use the monorail.}
{214}{}{当然毕竟，那样我就可以使用单轨了。}
### {215}{}{I'll do anything to make life easier for you guys.}
{215}{}{我会做任何事情让你们的生活更轻松。}
### {216}{}{Wonderful! Help me, and I will share part of the fee that the city administration promised me.}
{216}{}{精彩的帮我吧，我会分担市政府答应我的部分费用。}
### {217}{}{OK. See you again.}
{217}{}{好的，再见。}
### {218}{}{Before I start, I'm going to ask you a few questions.}
{218}{}{在我开始之前，我要问你几个问题。}

### {220}{}{What do you say, belyashik?}
{220}{}{你说呢，贝利亚希克？}
### {221}{}{What are you staring at, belyash?}
{221}{}{你在看什么，贝利亚？}
### {1221}{}{What are you staring at, paleface?}
{1221}{}{脸色苍白的你在看什么？}
### {222}{}{Hey, that's my pale-skinned brother! How are you?}
{222}{}{嘿，那是我皮肤苍白的弟弟！你好吗}
### {1222}{}{Hey, it's my pale-skinned sister! Are you all right?}
{1222}{}{嘿，是我皮肤苍白的妹妹！你还好吗？}
### {223}{}{For now. See you later.}
{223}{}{现在。回头见。}

### {230}{}{What is a monorail?}
{230}{}{什么是单轨电车？}
### {231}{}{You really don't know? That sucks! Once upon a time, elevated trains used to travel along these rails. And it was cool. Help me fix the line ? then you will see it with your own eyes.}
{231}{}{你真的不知道吗？太糟糕了！从前，高架列车常常沿着这些铁轨行驶。而且很酷。帮我修线路? 然后你会亲眼看到的。}
### {232}{}{I see.}
{232}{}{我明白了。}
### {233}{}{What should I do to start the tram?}
{233}{}{我该怎么启动电车？}
### {234}{}{First you need to supply power to the substation of the Blue Line. And then fix the electronics in the control room. If you don't have the skills, then take the equipment to the technician in San Ysidro.}
{234}{}{首先，你需要为蓝线的变电站供电。然后把电子设备固定在控制室里。如果你没有这些技能，那就把设备交给圣伊西德罗的技术人员。}
### {235}{}{Okay.}
{235}{}{可以}
### {236}{}{Does that thing in your head bother you?}
{236}{}{你脑子里的那个东西打扰你了吗？}
### {237}{}{Piece? Oh, you mean the fittings. She's been sticking out of this head for a hundred years. It's okay, I'm used to it. But it's better not to pull it out.}
{237}{}{块哦，你是说配件。她已经从这个脑袋里冒出来一百年了。没关系，我已经习惯了。但最好不要把它拔出来。}
### {238}{}{Okay. Whatever you say.}
{238}{}{可以不管你说什么。}
### {239}{}{It's a miracle! To be honest, I thought it wouldn't work. It's so amazing that I can't even believe it. You bring back my hope for people. Maybe all is not lost for you yet.}
{239}{}{这真是个奇迹！老实说，我以为这行不通。太神奇了，我简直不敢相信。你让我重新燃起了对人们的希望。也许你还没有失去一切。}
### {240}{}{Uh, good.}
{240}{}{嗯，很好。}
### {241}{}{I'm not trying for you.}
{241}{}{我不是在帮你。}
### {242}{}{Probably, I need to share the fee with you ? 1000 caps. And thank you... friend.}
{242}{}{也许，我需要和你分担费用? 1000顶。谢谢你。。。朋友}
### {1242}{}{I probably need to share the fee with you ? 1000 caps. And thank you... a friend.}
{1242}{}{我可能需要和你分担费用? 1000顶。谢谢你。。。朋友。}
### {243}{}{You're welcome... friend.}
{243}{}{不客气。。。朋友}
### {244}{}{Probably, I need to share the fee with you ? 1000 caps. And thank you... partner.}
{244}{}{也许，我需要和你分担费用? 1000顶。谢谢你。。。搭档}
### {245}{}{You're welcome... partner.}
{245}{}{不客气。。。搭档}
### {246}{}{I probably need to share the fee with you ? 500 caps. And thank you... partner.}
{246}{}{我可能需要和你分担费用? 500顶。谢谢你。。。搭档}
### {247}{}{And that's it? You're not my "partner" anymore.}
{247}{}{就这样？你不再是我的“伙伴”了。}
