### {100}{}{This is a single bed.}
{100}{}{这是一张单人床。}
### {101}{}{It's just a bed. Judging by the footprints on the floor, it was recently moved.}
{101}{}{这只是一张床。从地板上的脚印来看，它最近被搬走了。}
### {102}{}{The bed is like a bed. You don't notice anything special about her.}
{102}{}{这床就像一张床。你没有注意到她有什么特别之处。}
### {103}{}{You are trying to find a lock by the bed, or at least a slot for the key. But you only find a couple of dead parasites.}
{103}{}{你想在床边找一把锁，或者至少找一个钥匙槽。但你只发现几个死寄生虫。}
