### {110}{}{    }
{110}{}{error : string is empty}
### {111}{}{Report, brother.}
{111}{}{报告，兄弟。}
### {112}{}{They succeeded. The ghouls really started the power plant.}
{112}{}{他们成功了。食尸鬼们真的启动了发电厂。}
### {113}{}{What cretins! Now we have less time to prepare.}
{113}{}{什么白痴！现在我们准备的时间少了。}
### {114}{}{So, can we seize the dam? It's not the case to leave such power to the dregs...}
{114}{}{那么，我们能占领大坝吗？不是把这样的权力留给渣滓...}
### {115}{}{No, it will only distract us from the main goal.}
{115}{}{不，这只会分散我们对主要目标的注意力。}
### {116}{}{Besides, the ghouls need the station for the city. It is unlikely that they use it to harm.}
{116}{}{除此之外，食尸鬼们还需要城市的车站。他们不太可能用它来伤害别人。}
### {117}{}{We have to be proactive. We return to the base. We need to discuss everything.}
{117}{}{我们必须积极主动。我们回到基地。我们需要讨论一切。}
