### {100}{}{Here is a terminal.}
{100}{}{这是一个终端。}
### {101}{}{You see a terminal for controlling the water and air supply system.}
{101}{}{您可以看到一个用于控制供水和供气系统的终端。}
### {102}{}{The computer does not start. Probably, there is no electricity coming to it.}
{102}{}{计算机无法启动。可能是没有电了。}
### {103}{}{You start the pump to pump water from the lower level.}
{103}{}{你启动水泵从较低的水位抽水。}
### {104}{}{You've already done everything you wanted here.}
{104}{}{你已经在这里做了你想做的一切。}
