### {100}{}{Here is a farmer.}
{100}{}{这是一个农民。}
### {101}{}{You see a man with overworked hands. He is carrying a bag of things.}
{101}{}{你看到一个男人双手过度劳累。他拿着一袋东西。}
### {102}{}{First, let's put away the weapons. OK?}
{102}{}{首先，让我们收起武器。好啊}

### {200}{}{Hello, traveler. I see you're ready to talk, not wave your hands like some. How can I help you?}
{200}{}{你好，旅行家。我看你已经准备好说话了，而不是像某些人那样挥手。我能帮你什么？}
### {1200}{}{Hello, traveler. I see you're ready to talk, not wave your hands like some. How can I help you?}
{1200}{}{你好，旅行家。我看你已经准备好说话了，而不是像某些人那样挥手。我能帮你什么？}
### {201}{}{Probably nothing. Bye.}
{201}{}{可能什么都没有。再见}
### {202}{}{Where are you going?}
{202}{}{你要去哪里？}
### {203}{}{I'm going to the nearest settlement to trade. Goods from my farm are snapped up on the fly.}
{203}{}{我要去最近的结算点交易。我农场的货物被迅速抢购一空。}
### {204}{}{And what are you selling?}
{204}{}{你在卖什么？}
### {205}{}{I have a surplus crop. I want to exchange it for something useful that I can't get on my own.}
{205}{}{我有多余的作物。我想用它交换一些我自己无法得到的有用的东西。}
### {206}{}{Can we trade right here?}
{206}{}{我们可以在这里交易吗？}
### {207}{}{Why not? It will be easier for me.}
{207}{}{为什么不呢？这对我来说会更容易。}
### {208}{}{Perhaps another time.}
{208}{}{也许改天吧。}
### {209}{}{Let's see what you have.}
{209}{}{让我们看看你有什么。}

### {210}{}{Well, great. We have to go.}
{210}{}{好吧，太好了。我们得走了。}
### {211}{}{Bye.}
{211}{}{再见}
### {212}{}{Hmm, I've seen you somewhere... Hey! It's you the Rangers are looking for, isn't it? I don't know what your problems are with them, and I don't want to know. Just go your own way.}
{212}{}{嗯，我在什么地方见过你...嘿流浪者队在找你，不是吗？我不知道你有什么问题，我也不想知道。走你自己的路。}
### {213}{}{Bye.}
{213}{}{再见}
### {214}{}{Just tell me one more time...}
{214}{}{再告诉我一次...}
### {215}{}{Hmm, I've seen you somewhere... Hey! It's you the Rangers are looking for, isn't it? Don't worry, I won't turn you in. They're looking for me too, heh-heh.}
{215}{}{嗯，我在什么地方见过你...嘿流浪者队在找你，不是吗？别担心，我不会交你的。他们也在找我，呵呵。}
### {216}{}{That's good. And where are you going?}
{216}{}{这很好。你要去哪里？}
