#{100}{}{You see a refugee.}
{100}{}{你看到一个难民。 -- You see a refugee.}
#{101}{}{You see a very thin man.}
{101}{}{你看到一个很瘦的男人。 -- You see a very thin man.}
#{102}{}{We shouldn't have run away. We were safe, at least.}
{102}{}{我们不该逃跑。至少我们是安全的。 -- We shouldn't have run away. We were safe, at least.}
#{110}{}{[He looks at the ground] Yes, sir?}
{110}{}{[他看着地面]是的，先生？ -- [He looks at the ground] Yes, sir?}
#{111}{}{So you're the fugitive slaves, right?}
{111}{}{所以你是逃亡的奴隶，对吧？ -- So you're the fugitive slaves, right?}
#{112}{}{Just passing by.}
{112}{}{只是路过。 -- Just passing by.}
#{113}{}{[They look at each other, then back at the ground] Er... Yes, sir. There's no point hiding it now. We're runaway slaves.}
{113}{}{[他们看着对方，然后又回到地面]呃。。。是的，先生。现在藏起来没有意义了。我们是逃跑的奴隶。 -- [They look at each other, then back at the ground] Er... Yes, sir. There's no point hiding it now. We're runaway slaves.}
#{114}{}{I need to know what happened to you before I can decide if you can stay.}
{114}{}{我要知道你发生了什么事，然后才能决定你是否能留下来。 -- I need to know what happened to you before I can decide if you can stay.}
#{115}{}{That's all I need to know. You have to get out of here.}
{115}{}{我只想知道这些。你必须离开这里。 -- That's all I need to know. You have to get out of here.}
#{116}{}{Wait here for now.}
{116}{}{在这里等一下。 -- Wait here for now.}
#{117}{}{Why don't you get rid of those collars?}
{117}{}{你为什么不把那些项圈去掉？ -- Why don't you get rid of those collars?}
#{120}{}{Yes, sir. Anything you say, sir.}
{120}{}{是的，先生。你说什么都行，先生。 -- Yes, sir. Anything you say, sir.}
#{121}{}{Where are you from?}
{121}{}{你从哪里来的？ -- Where are you from?}
#{122}{}{From Reno, sir. We were captured when we were young, and have been slaves since then.}
{122}{}{从雷诺来的，先生。我们年轻时被俘虏，从此成为奴隶。 -- From Reno, sir. We were captured when we were young, and have been slaves since then.}
#{123}{}{How did you escape?}
{123}{}{你怎么逃出来的？ -- How did you escape?}
#{124}{}{We spent weeks digging a tunnel, then knocked out a guard one night and escaped. Our friend spent a year planning it, but he only figured out how to get out. We didn't know how to survive outside or how to remove these collars. Walking around with these on our necks is... [they glance at each other anxiously] ...very dangerous.}
{124}{}{我们花了几个星期挖了一条隧道，然后一天晚上撞倒了一个警卫逃走了。我们的朋友花了一年时间计划，但他只知道怎么出去。我们不知道如何在外面生存，也不知道如何移除这些项圈。脖子上戴着这个到处走是。。。[他们焦急地互相瞥了一眼]…非常危险。 -- We spent weeks digging a tunnel, then knocked out a guard one night and escaped. Our friend spent a year planning it, but he only figured out how to get out. We didn't know how to survive outside or how to remove these collars. Walking around with these on our necks is... [they glance at each other anxiously] ...very dangerous.}
#{125}{}{Why did you run away?}
{125}{}{你为什么逃跑？ -- Why did you run away?}
#{126}{}{Mister Luciano is having trouble in Reno, so he gave us less food and made us work every day. We understand why he needed to do that, but it was too much. It was better to take the risks than stay there.}
{126}{}{卢西亚诺先生在雷诺遇到了麻烦，所以他给了我们更少的食物，让我们每天工作。我们理解他为什么要这么做，但这太过分了。与其呆在那儿，不如冒险。 -- Mister Luciano is having trouble in Reno, so he gave us less food and made us work every day. We understand why he needed to do that, but it was too much. It was better to take the risks than stay there.}
#{127}{}{How many of you escaped?}
{127}{}{你们有多少人逃走了？ -- How many of you escaped?}
#{128}{}{There were five of us. One starved to death. The second drank from a puddle and died of sickness. The third was eaten by a gecko. It was... [they look at each other sadly] ...a hard journey.}
{128}{}{我们有五个人。一个饿死了。第二个喝了水坑里的水，病死了。第三只被壁虎吃掉了。那是。。。[他们悲伤地看着对方]…一段艰难的旅程。 -- There were five of us. One starved to death. The second drank from a puddle and died of sickness. The third was eaten by a gecko. It was... [they look at each other sadly] ...a hard journey.}
#{129}{}{Do you think they're looking for you?}
{129}{}{你觉得他们在找你吗？ -- Do you think they're looking for you?}
#{130}{}{Mister Luciano will be angry, but we are not special. He won't pay anyone to look for us outside the city.}
{130}{}{卢西亚诺先生会生气的，但我们并不特别。他不会付钱给任何人在城外找我们。 -- Mister Luciano will be angry, but we are not special. He won't pay anyone to look for us outside the city.}
#{131}{}{I've heard enough to make a decision.}
{131}{}{我已经听够了，可以做决定了。 -- I've heard enough to make a decision.}
#{132}{}{[The two men watch you nervously.]}
{132}{}{[两个人紧张地看着你。] -- [The two men watch you nervously.]}
#{133}{}{You seem harmless. You can stay. Let's get you a job at the stables...}
{133}{}{你看起来无害。你可以留下来。让我们给你在马厩找份工作。。。 -- You seem harmless. You can stay. Let's get you a job at the stables...}
#{134}{}{You can't stay here. You have to leave.}
{134}{}{你不能呆在这里。你必须离开。 -- You can't stay here. You have to leave.}
#{135}{}{I need to think about this. I'll be back with my answer.}
{135}{}{我需要考虑一下。我会带着我的答案回来的。 -- I need to think about this. I'll be back with my answer.}
#{136}{}{[Their shoulders sag] Y-yes, sir. We understand. But we have nowhere to go. We won't survive another journey in the desert, sir! We can't leave.}
{136}{}{[肩膀下垂]是的，先生。我们理解。但我们无处可去。我们在沙漠中再也活不下去了，长官！我们不能离开。 -- [Their shoulders sag] Y-yes, sir. We understand. But we have nowhere to go. We won't survive another journey in the desert, sir! We can't leave.}
#{137}{}{Your master needs slaves, right? He'll accept you back if you return to Reno. You'll have food and a roof over your head again.}
{137}{}{你的主人需要奴隶，对吗？如果你回雷诺他会接受你的。你会有食物和住处的。 -- Your master needs slaves, right? He'll accept you back if you return to Reno. You'll have food and a roof over your head again.}
#{138}{}{Why don't you return to your master?}
{138}{}{你为什么不回到你的主人身边？ -- Why don't you return to your master?}
#{139}{}{Mister Luciano?! [he looks you in the eyes for the first time, terrified] He'll skin us alive!}
{139}{}{卢西亚诺先生？！[他第一次看着你的眼睛，吓坏了]他会活剥我们的皮！ -- Mister Luciano?! [he looks you in the eyes for the first time, terrified] He'll skin us alive!}
#{140}{}{I will think about this. Stay here.}
{140}{}{我会考虑的。呆在这里。 -- I will think about this. Stay here.}
#{141}{}{I didn't think of that. [he thinks for a moment] We can't survive on our own. Mister Luciano may still forgive us... [he turns to his friend] What do you think? [his friend nods, and he looks back at the ground in front of you] If we can't stay here, other towns won't accept us either. Our only chance is to go back to Reno. We'll leave as soon as we can.}
{141}{}{我没想到。[他想了一会儿]我们不能靠自己生存。卢西亚诺先生也许还会原谅我们。。。[他转向他的朋友]你觉得怎么样？[他的朋友点头，他回头看着你面前的地面]如果我们不能留在这里，其他城镇也不会接受我们。我们唯一的机会就是回雷诺。我们会尽快离开。 -- I didn't think of that. [he thinks for a moment] We can't survive on our own. Mister Luciano may still forgive us... [he turns to his friend] What do you think? [his friend nods, and he looks back at the ground in front of you] If we can't stay here, other towns won't accept us either. Our only chance is to go back to Reno. We'll leave as soon as we can.}
#{142}{}{Stay safe!}
{142}{}{注意安全！ -- Stay safe!}
#{143}{}{The sooner the better. I don't want to see you around here again.}
{143}{}{越快越好。我不想再在这里见到你。 -- The sooner the better. I don't want to see you around here again.}
#{144}{}{I'm not asking, I'm telling. Get out. One more word, and I'll feed you to the geckos, feet-first. Alive.}
{144}{}{我不是问，我是说。走出。再多说一句，我就把你喂给壁虎，脚先。活着。 -- I'm not asking, I'm telling. Get out. One more word, and I'll feed you to the geckos, feet-first. Alive.}
#{145}{}{N-no sir, please don't sir! We'll leave, sir, just please don't hurt us!}
{145}{}{不，先生，请不要！我们会离开的，先生，请不要伤害我们！ -- N-no sir, please don't sir! We'll leave, sir, just please don't hurt us!}
#{146}{}{That was a hell of a lot more than one word. Start running.}
{146}{}{那可不仅仅是一个词。开始跑步。 -- That was a hell of a lot more than one word. Start running.}
#{147}{}{Just walk away. Leave these people, this food, this water, this whole settlement, and I'll spare your lives. Just walk away.}
{147}{}{走开吧。离开这些人，这些食物，这些水，整个定居点，我就饶了你的命。走开吧。 -- Just walk away. Leave these people, this food, this water, this whole settlement, and I'll spare your lives. Just walk away.}
#{148}{}{Okay, we're going. We don't want any violence. We're going.}
{148}{}{好的，我们走。我们不想要任何暴力。我们要走了。 -- Okay, we're going. We don't want any violence. We're going.}
#{149}{}{Hey, I'm not finished! [end]}
{149}{}{嘿，我还没说完！[结束] -- Hey, I'm not finished! [end]}
#{150}{}{That would be very helpful. People wouldn't be able to tell we're slaves, then. But it's not easy to take them off.}
{150}{}{那会很有帮助的。那么，人们就不知道我们是奴隶了。但要脱下来可不容易。 -- That would be very helpful. People wouldn't be able to tell we're slaves, then. But it's not easy to take them off.}
#{151}{}{I'll try. Let me see.}
{151}{}{我试试看。我想一下。 -- I'll try. Let me see.}
#{152}{}{Tell me about yourselves.}
{152}{}{跟我说说你们自己。 -- Tell me about yourselves.}
#{153}{}{[These collars are specifically designed to resist being removed without proper authorization. Unless you know what you're doing, tampering with them will cause them to electrocute the wearer, killing them instantly.]}
{153}{}{[这些项圈是专门设计的，以防止未经适当授权而被拆除。除非你知道自己在做什么，否则篡改它们会导致佩戴者触电身亡，当场死亡。] -- [These collars are specifically designed to resist being removed without proper authorization. Unless you know what you're doing, tampering with them will cause them to electrocute the wearer, killing them instantly.]}
#{154}{}{I think I see how to disable these. I'll get them off now.}
{154}{}{我想我知道如何禁用这些。我现在就把他们弄下来。 -- I think I see how to disable these. I'll get them off now.}
#{155}{}{Whoops! [deliberately activate both collars]}
{155}{}{哎呀！[故意激活两个项圈] -- Whoops! [deliberately activate both collars]}
#{156}{}{I can't help you.}
{156}{}{我帮不了你。 -- I can't help you.}
#{157}{}{We're free! [he laughs in joy] I can't believe it! You saved us! [he moves his head around, stretching his neck like it's the first time he's ever doing it] Oh, this is... Amazing!}
{157}{}{我们自由了！[他高兴地笑]真不敢相信！你救了我们！[他把头转来转去，伸着脖子，好像这是他第一次这么做]哦，这是。。。太神了！ -- We're free! [he laughs in joy] I can't believe it! You saved us! [he moves his head around, stretching his neck like it's the first time he's ever doing it] Oh, this is... Amazing!}
#{158}{}{Enjoy, guys.}
{158}{}{好好享受，伙计们。 -- Enjoy, guys.}
#{1110}{}{[He looks at the ground] Yes, ma'am?}
{1110}{}{[他看着地面]是的，女士？ -- [He looks at the ground] Yes, ma'am?}
#{1113}{}{[They look at each other, then back at the ground] Er... Yes, ma'am. There's no point hiding it now. We're fugitive slaves.}
{1113}{}{[他们看着对方，然后又回到地面]呃。。。是的，女士。现在藏起来没有意义了。我们是逃亡的奴隶。 -- [They look at each other, then back at the ground] Er... Yes, ma'am. There's no point hiding it now. We're fugitive slaves.}
#{1120}{}{Yes, ma'am. Anything you say, ma'am.}
{1120}{}{是的，女士。你说什么都行，夫人。 -- Yes, ma'am. Anything you say, ma'am.}
#{1122}{}{From Reno, ma'am. We were captured when we were young, and have been slaves since then.}
{1122}{}{从里诺来的，女士。我们年轻时被俘虏，从此成为奴隶。 -- From Reno, ma'am. We were captured when we were young, and have been slaves since then.}
#{1131}{}{I've heard enough to make a decision.}
{1131}{}{我已经听够了，可以做决定了。 -- I've heard enough to make a decision.}
#{1136}{}{[Their shoulders sag] Y-yes, ma'am. We understand. But we have nowhere to go. We won't survive another journey in the desert, ma'am! We can't leave.}
{1136}{}{[肩膀下垂]是的，女士。我们理解。但我们无处可去。我们在沙漠中再也活不下去了，夫人！我们不能离开。 -- [Their shoulders sag] Y-yes, ma'am. We understand. But we have nowhere to go. We won't survive another journey in the desert, ma'am! We can't leave.}
#{1145}{}{N-no ma'am, please don't ma'am! We'll leave, ma'am, just please don't hurt us!}
{1145}{}{不，女士，请不要！我们要走了，女士，请不要伤害我们！ -- N-no ma'am, please don't ma'am! We'll leave, ma'am, just please don't hurt us!}
