#{100}{}{You see a young boy.}
{100}{}{你看到一个小男孩。 -- You see a young boy.}
#{101}{}{You see a cute young boy. He stinks of manure.}
{101}{}{你看到一个可爱的小男孩。他身上有粪臭味。 -- You see a cute young boy. He stinks of manure.}
#{110}{}{Yes, sir?}
{110}{}{是的，先生？ -- Yes, sir?}
#{111}{}{I'm just passing by.}
{111}{}{我只是路过。 -- I'm just passing by.}
#{120}{}{Your father asked me to look for a missing brahmin. What can you say in your defense?}
{120}{}{你父亲让我去找一个失踪的婆罗门。你能为自己辩护吗？ -- Your father asked me to look for a missing brahmin. What can you say in your defense?}
#{121}{}{Let's talk about the missing brahmin.}
{121}{}{让我们谈谈失踪的婆罗门。 -- Let's talk about the missing brahmin.}
#{122}{}{I didn't do anything wrong! Really! It's like she never existed - she was here in the night and gone in the morning! She just disappeared! I'm telling the truth!}
{122}{}{我没做错什么！真正地！就像她从未存在过一样——她晚上在这里，早上就走了！她消失了！我说的是实话！ -- I didn't do anything wrong! Really! It's like she never existed - she was here in the night and gone in the morning! She just disappeared! I'm telling the truth!}
#{123}{}{What the brahmin looked like?}
{123}{}{婆罗门长什么样？ -- What the brahmin looked like?}
#{124}{}{Like any normal brahmin. Four hoofs, two heads, one tail... And smelly...}
{124}{}{像任何正常的婆罗门。四蹄，两头，一尾。。。又臭。。。 -- Like any normal brahmin. Four hoofs, two heads, one tail... And smelly...}
#{125}{}{Where did you last see it?}
{125}{}{你最后一次看到它是在哪里？ -- Where did you last see it?}
#{126}{}{She was right there, in that corner! And in the morning, she was gone! Just disappeared!}
{126}{}{她就在那里，在那个角落！早上，她走了！就这么消失了！ -- She was right there, in that corner! And in the morning, she was gone! Just disappeared!}
#{127}{}{Was anyone else around that night?}
{127}{}{那晚周围还有其他人吗？ -- Was anyone else around that night?}
#{128}{}{No! I'm sure! Because... Because I didn't sleep, and I tied the gate shut with a special knot! If someone unties the rope, I'll know, because they won't tie it in the same way! No one could have taken it! Even the toilet and that lady from Reno aren't close enough to steal brahmin without me seeing!}
{128}{}{不！我肯定！因为。。。因为我没有睡觉，我用一个特殊的结把大门关上了！如果有人解开绳子，我就知道了，因为他们不会用同样的方法绑它！没人能拿走它！连厕所和里诺的那位女士都离得不近，不让我看见就偷走了婆罗门！ -- No! I'm sure! Because... Because I didn't sleep, and I tied the gate shut with a special knot! If someone unties the rope, I'll know, because they won't tie it in the same way! No one could have taken it! Even the toilet and that lady from Reno aren't close enough to steal brahmin without me seeing!}
#{129}{}{Look, kid, I can tell you're lying to me. Tell me the truth, or else.}
{129}{}{听着，孩子，我知道你在骗我。告诉我真相，否则。 -- Look, kid, I can tell you're lying to me. Tell me the truth, or else.}
#{130}{}{You... You won't tell my father, will you? I fell asleep... I'm sorry! I don't usually sleep in the night! But as soon as I drank some water, I just... I don't know! I don't even remember feeling tired, but I didn't wake up until morning. And then the brahmin was gone! It must have been some kind of... Of radiation, or a brahmin-stealing mutant with special powers!}
{130}{}{你。。。你不会告诉我父亲吧？我睡着了。。。我很抱歉！我通常晚上不睡觉！但我一喝水，我就。。。我不知道！我甚至不记得感觉累了，但我直到早上才醒来。然后婆罗门就不见了！一定是某种。。。或者是一个拥有特殊能力的婆罗门变种人！ -- You... You won't tell my father, will you? I fell asleep... I'm sorry! I don't usually sleep in the night! But as soon as I drank some water, I just... I don't know! I don't even remember feeling tired, but I didn't wake up until morning. And then the brahmin was gone! It must have been some kind of... Of radiation, or a brahmin-stealing mutant with special powers!}
#{131}{}{It's a mystery, all right.}
{131}{}{这是个谜，好吧。 -- It's a mystery, all right.}
#{132}{}{You'll find it, right? My father will be mad if you don't!}
{132}{}{你会找到的，对吧？如果你不这样做，我父亲会生气的！ -- You'll find it, right? My father will be mad if you don't!}
#{133}{}{Maybe, maybe not. I might get lucky.}
{133}{}{也许，也许不是。我可能会走运。 -- Maybe, maybe not. I might get lucky.}
#{134}{}{I'll do everything I can.}
{134}{}{我会尽我所能。 -- I'll do everything I can.}
#{135}{}{I told you everything! Honest!}
{135}{}{我都告诉你了！老实说！ -- I told you everything! Honest!}
#{136}{}{Fine, wait here.}
{136}{}{好吧，在这儿等着。 -- Fine, wait here.}
#{140}{}{Did anyone come by with a shotgun that night?}
{140}{}{那天晚上有人带着猎枪过来吗？ -- Did anyone come by with a shotgun that night?}
#{141}{}{I didn't see anyone, but... People come by the toilet all the time. I don't remember, too many of them.}
{141}{}{我没看见任何人，但是。。。人们总是到厕所来。我不记得了，太多了。 -- I didn't see anyone, but... People come by the toilet all the time. I don't remember, too many of them.}
#{142}{}{Right. I'll continue to search for a man with a shotgun then...}
{142}{}{正确的。我会继续找一个拿着猎枪的人。。。 -- Right. I'll continue to search for a man with a shotgun then...}
#{152}{}{I just want to ask you something.}
{152}{}{我只是想问你一件事。 -- I just want to ask you something.}
#{153}{}{What?}
{153}{}{什么？ -- What?}
#{154}{}{Nothing.}
{154}{}{没有什么。 -- Nothing.}
#{155}{}{What are you doing here?}
{155}{}{你在这里干什么？ -- What are you doing here?}
#{156}{}{What are those animals?}
{156}{}{那些动物是什么？ -- What are those animals?}
#{157}{}{What can you tell me about Black Rock?}
{157}{}{关于黑岩你能告诉我什么？ -- What can you tell me about Black Rock?}
#{158}{}{That's enough.}
{158}{}{够了。 -- That's enough.}
#{159}{}{My father made this corral a couple of years ago, and my job is to watch the brahmin so nobody steals them!}
{159}{}{我父亲几年前建了这个畜栏，而我的工作就是观察婆罗门，这样就没人偷了它们！ -- My father made this corral a couple of years ago, and my job is to watch the brahmin so nobody steals them!}
#{160}{}{[He looks incredulous] You don't know what a brahmin is?! I didn't know that was possible! Well... They are animals. We grow them, then slaughter them, and my father makes the meat soup out of them. It's really good!}
{160}{}{你不知道什么是婆罗门？！我不知道这是可能的！好。。。他们是动物。我们种植它们，然后宰杀它们，我父亲用它们做肉汤。真的很好！ -- [He looks incredulous] You don't know what a brahmin is?! I didn't know that was possible! Well... They are animals. We grow them, then slaughter them, and my father makes the meat soup out of them. It's really good!}
#{161}{}{I live here! I've never been anywhere else, except for Gerlach one time, and it doesn't really count because I didn't talk to anyone.}
{161}{}{我住在这里！我从来没去过别的地方，除了杰拉克一次，这不算什么，因为我没和任何人说话。 -- I live here! I've never been anywhere else, except for Gerlach one time, and it doesn't really count because I didn't talk to anyone.}
#{162}{}{Gerlach?}
{162}{}{杰拉克？ -- Gerlach?}
#{163}{}{Yeah. It's that way. [he points to the west]}
{163}{}{是 啊。就在那边。[他指向西方] -- Yeah. It's that way. [he points to the west]}
#{164}{}{Don't you get bored here?}
{164}{}{你在这儿不觉得无聊吗？ -- Don't you get bored here?}
#{165}{}{Yeah, it's REALLY boring. Sometimes I just want to leave and go home, but my father won't let me. But when the brahmin are sleeping, at night, you can play with them. You sneak up quietly and hit them in the belly, then run away! And then they look around like "Wha??? What's going on???" Hahahaha!}
{165}{}{是啊，真的很无聊。有时我只想离开家，但我父亲不让我。但是当婆罗门在睡觉的时候，在晚上，你可以和他们一起玩。你悄悄溜上来打他们的肚子，然后逃跑！然后他们环顾四周像“什么？？？怎么回事哈哈哈！ -- Yeah, it's REALLY boring. Sometimes I just want to leave and go home, but my father won't let me. But when the brahmin are sleeping, at night, you can play with them. You sneak up quietly and hit them in the belly, then run away! And then they look around like "Wha??? What's going on???" Hahahaha!}
#{1110}{}{Yes, ma'am?}
{1110}{}{是的，女士？ -- Yes, ma'am?}
