#{100}{}{The leader of the Coyote tribe.}
{100}{}{土狼部落的首领。 -- The leader of the Coyote tribe.}
#{101}{}{You see a damn attractive and just as rude person.}
{101}{}{你看到的是一个非常有魅力而且同样粗鲁的人。 -- You see a damn attractive and just as rude person.}
#{110}{}{You will burn on the sacrificial fire}
{110}{}{你会在烈火上燃烧 -- You will burn on the sacrificial fire}
#{111}{}{I'll eat your heart to become stronger}
{111}{}{我要吃了你的心变得更强壮 -- I'll eat your heart to become stronger}
#{112}{}{Come on, my children!}
{112}{}{快点，我的孩子们！ -- Come on, my children!}
#{113}{}{Kill! Kill!}
{113}{}{杀了我！杀了我！ -- Kill! Kill!}
#{114}{}{My children, if you are hungry, take yourself the most delicious!}
{114}{}{孩子们，如果你饿了，就吃最美味的吧！ -- My children, if you are hungry, take yourself the most delicious!}
#{115}{}{The meat of strangers is so delicious}
{115}{}{陌生人的肉真好吃 -- The meat of strangers is so delicious}
#{116}{}{I like you. Especially your sirloin part.}
{116}{}{我喜欢你。尤其是你的牛腰肉。 -- I like you. Especially your sirloin part.}
#{117}{}{Come on, run! You will only provoke my children!}
{117}{}{快点，快跑！你只会激怒我的孩子！ -- Come on, run! You will only provoke my children!}
#{118}{}{Nobody will be forgiven, if this prey gets away!}
{118}{}{没有人会被原谅，如果这个猎物逃走了！ -- Nobody will be forgiven, if this prey gets away!}
#{119}{}{A glorious dinner today, my children! Rejoice!}
{119}{}{今天的晚餐很丰盛，我的孩子们！高兴吧！ -- A glorious dinner today, my children! Rejoice!}
