#{100}{}{This is my house.}
{100}{}{这是我的房子。 -- This is my house.}
#{101}{}{Damn bandits.}
{101}{}{该死的强盗。 -- Damn bandits.}
#{102}{}{Leave us alone!}
{102}{}{别管我们！ -- Leave us alone!}
#{103}{}{I hate bandits.}
{103}{}{我讨厌强盗。 -- I hate bandits.}
#{104}{}{We have nothing for you to steal.}
{104}{}{我们没有东西给你偷。 -- We have nothing for you to steal.}
#{105}{}{Don't kill me.}
{105}{}{别杀我。 -- Don't kill me.}
#{106}{}{I've had enough.}
{106}{}{我受够了。 -- I've had enough.}
#{107}{}{Take what you want.}
{107}{}{你想拿什么就拿什么。 -- Take what you want.}
#{108}{}{Please, don't kill me.}
{108}{}{拜托，别杀我。 -- Please, don't kill me.}
#{109}{}{I hated farming anyway.}
{109}{}{反正我讨厌种地。 -- I hated farming anyway.}
#{110}{}{Please don't burn the house down.}
{110}{}{请不要把房子烧了。 -- Please don't burn the house down.}
