#{100}{}{You see a king.}
{100}{}{你看到一个国王。 -- You see a king.}
#{101}{}{You see one of the members of the "Kings" gang.}
{101}{}{你看到一个“国王”团伙的成员。 -- You see one of the members of the "Kings" gang.}
#{110}{}{You shouldn't have come into this area}
{110}{}{你不该来这个地方 -- You shouldn't have come into this area}
#{111}{}{Here *we* are the kings!}
{111}{}{我们是国王！ -- Here *we* are the kings!}
#{112}{}{You will have to pay for passage on our turf}
{112}{}{你得付在我们地盘上的通行费 -- You will have to pay for passage on our turf}
#{113}{}{Uh, the racketeering becomes harder lately}
{113}{}{呃，最近敲诈勒索越来越难了 -- Uh, the racketeering becomes harder lately}
#{114}{}{I'm not a gangster, but the band decided otherwise}
{114}{}{我不是黑帮，但乐队不这么认为 -- I'm not a gangster, but the band decided otherwise}
#{115}{}{Give us the money and get the fuck out!}
{115}{}{把钱给我们滚出去！ -- Give us the money and get the fuck out!}
#{116}{}{What, do the lights of Vegas beckon you? Too bad...}
{116}{}{什么，维加斯的灯光在召唤你吗？太糟糕了。。。 -- What, do the lights of Vegas beckon you? Too bad...}
#{117}{}{The boss will be happy, if I take a couple of coins of you}
{117}{}{如果我给你几枚硬币，老板会高兴的 -- The boss will be happy, if I take a couple of coins of you}
#{118}{}{We are the kings here, so behave!}
{118}{}{我们是这里的国王，所以规矩点！ -- We are the kings here, so behave!}
