#{100}{}{}
{100}{}{ -- }
#{101}{}{The encyclopedia is of no more use - let your personal experience be your guide from now on.}
{101}{}{百科全书不再有用了——从现在起，让你的个人经历成为你的指南。 -- The encyclopedia is of no more use - let your personal experience be your guide from now on.}
#{102}{}{Thorough study of the archive data broadens your knowledge of the world.}
{102}{}{对档案资料的透彻研究可以拓宽你对世界的了解。 -- Thorough study of the archive data broadens your knowledge of the world.}
