#{100}{}{You see old man Vernon.}
{100}{}{你看弗农老人。 -- You see old man Vernon.}
#{101}{}{You see Vernon, an old city dweller and an opinionated bookworm.}
{101}{}{你看弗农，一个老城里人，一个固执己见的书呆子。 -- You see Vernon, an old city dweller and an opinionated bookworm.}
#{102}{}{I may be old, but I still have some life in me!}
{102}{}{我可能老了，但我还有生命！ -- I may be old, but I still have some life in me!}
#{119}{}{Still looking for answers? Well, I may have some for you.}
{119}{}{还在寻找答案吗？好吧，我可以给你一些。 -- Still looking for answers? Well, I may have some for you.}
#{120}{}{Welcome to my humble dwelling!}
{120}{}{欢迎来到我的寒舍！ -- Welcome to my humble dwelling!}
#{121}{}{Greetings! How can a lonely old man be of help to you?}
{121}{}{问候语！一个孤独的老人怎么能帮助你？ -- Greetings! How can a lonely old man be of help to you?}
#{122}{}{Diogenes would surely find the "humble dwelling" part funny.}
{122}{}{提奥奇尼斯肯定会觉得“简陋的住所”很有趣。 -- Diogenes would surely find the "humble dwelling" part funny.}
#{123}{}{Ha! If you knew more about him, young man, you'd understand that that "humble dwelling" of Diogenes was quite *sufficient* for him and the conditions he lived in: after all, the climate, the scenery, the company...}
{123}{}{哈！如果你对他了解得更多，年轻人，你就会明白提奥奇尼斯的“简陋住所”对他和他生活的条件来说是相当的“足够”：毕竟，这里的气候、风景、公司。。。 -- Ha! If you knew more about him, young man, you'd understand that that "humble dwelling" of Diogenes was quite *sufficient* for him and the conditions he lived in: after all, the climate, the scenery, the company...}
#{124}{}{But there are other reasons for his living in a barrel. For him it was about rebellion and self-expression.}
{124}{}{但他住在桶里还有其他原因。对他来说，这是叛逆和自我表达。 -- But there are other reasons for his living in a barrel. For him it was about rebellion and self-expression.}
#{125}{}{Sure, sure, but... What are you getting at?}
{125}{}{当然，当然，但是。。。你在说什么？ -- Sure, sure, but... What are you getting at?}
#{126}{}{The point is, you shouldn't belittle yourself when you have quite a decent place to live in and comprise the active part of the city's population.}
{126}{}{关键是，当你有一个相当体面的居所，并且是城市人口的活跃部分时，你不应该贬低自己。 -- The point is, you shouldn't belittle yourself when you have quite a decent place to live in and comprise the active part of the city's population.}
#{127}{}{But I am the poorest man in this city!}
{127}{}{但我是这个城市最穷的人！ -- But I am the poorest man in this city!}
#{128}{}{There you go again.}
{128}{}{又来了。 -- There you go again.}
#{129}{}{Well... Okay, let's change it to "I am the poorest among the 'active part of the city's population'" then.}
{129}{}{好。。。好吧，让我们把它改成“我是‘城市活跃人口’中最穷的一个”。 -- Well... Okay, let's change it to "I am the poorest among the 'active part of the city's population'" then.}
#{130}{}{Do you mean to say that the tramps on the streets are not a part of this city?}
{130}{}{你的意思是说街上的流浪汉不是这个城市的一部分吗？ -- Do you mean to say that the tramps on the streets are not a part of this city?}
#{131}{}{Indeed, they are not. The city is bigger and beggars only work to disgrace it.}
{131}{}{事实上，他们不是。城市更大了，乞丐工作只是为了羞辱它。 -- Indeed, they are not. The city is bigger and beggars only work to disgrace it.}
#{132}{}{But the beggars are a direct result of the city's activity, they were begot by the city and the will also be consumed by it, if the situation changes for the better.}
{132}{}{但乞丐是城市活动的直接结果，他们是由城市生的，如果情况好转，也会被城市吞噬。 -- But the beggars are a direct result of the city's activity, they were begot by the city and the will also be consumed by it, if the situation changes for the better.}
#{133}{}{They are on the same level as polluting emissions. Like smoke coming out of a plant's chimney - it's not a part of the city anymore.}
{133}{}{它们与污染排放量处于同一水平。就像从工厂烟囱冒出的烟——它不再是城市的一部分了。 -- They are on the same level as polluting emissions. Like smoke coming out of a plant's chimney - it's not a part of the city anymore.}
#{134}{}{So you say that beggars are also not a part of the city? That is absurd.}
{134}{}{所以你说乞丐也不是城市的一部分？那太荒谬了。 -- So you say that beggars are also not a part of the city? That is absurd.}
#{135}{}{How so?}
{135}{}{怎么会这样？ -- How so?}
#{136}{}{Don't you think that if a part of the whole becomes something big and independent, it stops being a part, and thus, becomes another whole, but the whole, which it's not a part of anymore, does not depend on it?}
{136}{}{你不认为如果一个整体的一部分变成一个大的独立的东西，它就不再是一个整体，因此，成为另一个整体，但是这个整体，它不再是一部分，不依赖于它吗？ -- Don't you think that if a part of the whole becomes something big and independent, it stops being a part, and thus, becomes another whole, but the whole, which it's not a part of anymore, does not depend on it?}
#{137}{}{Hmm... Yes. You are right.}
{137}{}{隐马尔可夫模型。。。对。你是对的。 -- Hmm... Yes. You are right.}
#{138}{}{So, we have just learned that...}
{138}{}{所以，我们刚刚了解到。。。 -- So, we have just learned that...}
#{139}{}{[For the last few hours, you have been having a visionary discussion with the bookworm about dividing a whole into parts and assembling parts into a whole.]}
{139}{}{[在过去的几个小时里，你一直在和书呆子进行一次富有远见的讨论，讨论如何将一个整体分成几个部分，并将各个部分组装成一个整体。] -- [For the last few hours, you have been having a visionary discussion with the bookworm about dividing a whole into parts and assembling parts into a whole.]}
#{140}{}{...and thus, the whole, still being a part of the lesser whole, continues to be a whole, while, at the same time, being a part of the other whole, as the other whole remains a part of that whole.}
{140}{}{……因此，整体，仍然是较小整体的一部分，继续是一个整体，同时，作为另一个整体的一部分，另一个整体仍然是该整体的一部分。 -- ...and thus, the whole, still being a part of the lesser whole, continues to be a whole, while, at the same time, being a part of the other whole, as the other whole remains a part of that whole.}
#{141}{}{An excellent conclusion! I see your deduction skills are unparalleled.}
{141}{}{一个极好的结论！我看你的演绎技巧无与伦比。 -- An excellent conclusion! I see your deduction skills are unparalleled.}
#{142}{}{Quite so! It was a pleasure arguing with you. Goodbye!}
{142}{}{完全是这样！很高兴和你争论。再见！ -- Quite so! It was a pleasure arguing with you. Goodbye!}
#{150}{}{You seem way more intelligent than other people in this city. Perhaps you know the history of the place?}
{150}{}{你看起来比这个城市的其他人聪明多了。也许你知道这个地方的历史？ -- You seem way more intelligent than other people in this city. Perhaps you know the history of the place?}
#{151}{}{I sure do. I'll be happy to tell you about the city and the history of its establishment. If you have time, of course, as it is quite a long story.}
{151}{}{我当然知道。我很高兴向你介绍这座城市及其建立的历史。如果你有时间，当然，因为这是一个相当长的故事。 -- I sure do. I'll be happy to tell you about the city and the history of its establishment. If you have time, of course, as it is quite a long story.}
#{152}{}{Please, tell me about it.}
{152}{}{请告诉我。 -- Please, tell me about it.}
#{153}{}{Unfortunately, I don't have time for long stories.}
{153}{}{不幸的是，我没有时间讲长篇大论。 -- Unfortunately, I don't have time for long stories.}
#{154}{}{Here it goes, then. [He acts as if reading a fairy tale to children near a fireplace.] This is a tale of great people and their hard every day work.}
{154}{}{就这样吧。[他就像在壁炉旁给孩子们读童话一样]这是一个关于伟人和他们每天辛勤劳动的故事。 -- Here it goes, then. [He acts as if reading a fairy tale to children near a fireplace.] This is a tale of great people and their hard every day work.}
#{155}{}{[More.]}
{155}{}{[更多信息。] -- [More.]}
#{156}{}{Salt Lake City was built before the war. It was a big city by American standards. Many people were scurrying about here, trains were moving up and down the railroad, and factories were steaming with smoke. The city was buzzing and was always in motion.}
{156}{}{盐湖城建于战前。按照美国的标准，这是一座大城市。许多人在这里匆匆忙忙，火车在铁路上来回行驶，工厂里烟雾缭绕。这座城市嗡嗡作响，一直在运动。 -- Salt Lake City was built before the war. It was a big city by American standards. Many people were scurrying about here, trains were moving up and down the railroad, and factories were steaming with smoke. The city was buzzing and was always in motion.}
#{157}{}{After a while, a small gambling zone was set up, with not very expensive casinos and restaurants, which had big signs and shining corbels...}
{157}{}{过了一会儿，一个小小的赌博区成立了，赌场和餐馆都不是很贵，那里有很大的招牌和闪亮的牛腿。。。 -- After a while, a small gambling zone was set up, with not very expensive casinos and restaurants, which had big signs and shining corbels...}
#{158}{}{The city was by no means clean, as it was still an industrial center. It produced electricity, plants were operating, salt and copper were mined... There was even a military base with its own airfield in the north of here...}
{158}{}{这座城市一点也不干净，因为它还是一个工业中心。它发电，工厂运转，盐矿和铜矿开采。。。在这里的北部甚至有一个军事基地有自己的机场。。。 -- The city was by no means clean, as it was still an industrial center. It produced electricity, plants were operating, salt and copper were mined... There was even a military base with its own airfield in the north of here...}
#{159}{}{And then...}
{159}{}{然后。。。 -- And then...}
#{160}{}{God save us! The radios began crying about an impending nuclear threat! In panic, the residents were signing up for queues to enter large underground vaults, safe shelters constructed by the Vault-Tec Corporation. Small companies that had been engaged in the pool construction business started to make private mini-vaults, designed to hold families. There are hundreds of them in Salt Lake, scattered around the basements of various buildings.}
{160}{}{上帝保佑我们！收音机开始哭喊即将到来的核威胁！慌乱中，居民们排队进入大型地下保险库，这是保险库技术公司建造的安全避难所。从事游泳池建设业务的小公司开始制造私人迷你金库，用于容纳家庭。盐湖里有几百个，散落在各种建筑的地下室里。 -- God save us! The radios began crying about an impending nuclear threat! In panic, the residents were signing up for queues to enter large underground vaults, safe shelters constructed by the Vault-Tec Corporation. Small companies that had been engaged in the pool construction business started to make private mini-vaults, designed to hold families. There are hundreds of them in Salt Lake, scattered around the basements of various buildings.}
#{161}{}{Then everything calmed down. Armed conflicts subsided and people started to forget about the bombs. Nobody knows who had fired first. It may have been the Russians, or the Chinese, or even us. It doesn't matter now. The past is dead and gone.}
{161}{}{然后一切平静下来。武装冲突平息了，人们开始忘记炸弹。没人知道是谁先开枪的。可能是俄国人，或者中国人，甚至是美国。现在不重要了。过去已经过去了。 -- Then everything calmed down. Armed conflicts subsided and people started to forget about the bombs. Nobody knows who had fired first. It may have been the Russians, or the Chinese, or even us. It doesn't matter now. The past is dead and gone.}
#{162}{}{The most astute ones hid inside the big vault in the Wasatch Range east of here, while the rest sheltered in their family vaults and in basements. Those who lived in this part of Salt Lake City were luckier, as the bombs mostly fell in the northern area, where the military base was situated. The local climate smoothed the consequences of the blasts, washing off the nuclear fallout with autumn rains then weighing it down with snow.}
{162}{}{最精明的人躲在这里以东瓦萨奇山脉的大金库里，其余的人则躲在家里的金库和地下室里。住在盐湖城这一地区的人更幸运，因为炸弹大多落在军事基地所在的北部地区。当地的气候缓和了爆炸的后果，用秋雨冲走了核沉降物，然后用雪把它压下来。 -- The most astute ones hid inside the big vault in the Wasatch Range east of here, while the rest sheltered in their family vaults and in basements. Those who lived in this part of Salt Lake City were luckier, as the bombs mostly fell in the northern area, where the military base was situated. The local climate smoothed the consequences of the blasts, washing off the nuclear fallout with autumn rains then weighing it down with snow.}
#{163}{}{People didn't begin to emerge from the vaults until 10 to 30 years after the war. At the end of the day, nobody liked to spend their life confined within metal walls.}
{163}{}{人们直到战后10到30年才开始从地下室出来。最后，没有人愿意在金属墙里度过他们的一生。 -- People didn't begin to emerge from the vaults until 10 to 30 years after the war. At the end of the day, nobody liked to spend their life confined within metal walls.}
#{164}{}{Those who were brave were the first to come out, while others took their time. The last of the remaining vault dwellers saw the sun only a few years ago.}
{164}{}{那些勇敢的人是第一个出来的，而其他人则不慌不忙。剩下的金库居民中的最后一个几年前才看到太阳。 -- Those who were brave were the first to come out, while others took their time. The last of the remaining vault dwellers saw the sun only a few years ago.}
#{165}{}{Those first to emerge saw at once that the outside world was not safe anymore. Radiation and mutated animals frightened the citizens. Some of the people also didn't have the cleanest of hands. So, a council was called and a sheriff elected, with the task of building a new society on the ruins of the old city.}
{165}{}{那些最先出现的人立刻看到外面的世界不再安全了。辐射和变异的动物吓坏了市民。有些人的手也不干净。于是，召集了一个委员会，选出了一个治安官，任务是在旧城的废墟上建立一个新的社会。 -- Those first to emerge saw at once that the outside world was not safe anymore. Radiation and mutated animals frightened the citizens. Some of the people also didn't have the cleanest of hands. So, a council was called and a sheriff elected, with the task of building a new society on the ruins of the old city.}
#{166}{}{The Sheriff set about fighting crime. He gathered a team of determined people around him and helped many enterprises and organizations gain ground... It was not an easy task, of course.}
{166}{}{治安官着手打击犯罪。他召集了一批坚定的人围着他，帮助许多企业和组织站稳了脚跟。。。当然，这不是一件容易的事。 -- The Sheriff set about fighting crime. He gathered a team of determined people around him and helped many enterprises and organizations gain ground... It was not an easy task, of course.}
#{167}{}{The city is... Fragile, so to speak. Every prominent figure here is a pillar on which it stands. Should one of the pillars collapse, the whole city will follow.}
{167}{}{这个城市。。。可以说是脆弱的。这里每一个显赫的人物都是一根柱子。如果其中一根柱子倒塌，整个城市都会跟着倒塌。 -- The city is... Fragile, so to speak. Every prominent figure here is a pillar on which it stands. Should one of the pillars collapse, the whole city will follow.}
#{168}{}{I hope you find my story interesting. Would you be so kind as to offer me a cup of tea for the effort?}
{168}{}{我希望你觉得我的故事有趣。请您为我的努力倒杯茶好吗？ -- I hope you find my story interesting. Would you be so kind as to offer me a cup of tea for the effort?}
#{169}{}{Gladly! Here are 10 bucks as a tip. Thanks!}
{169}{}{很高兴！给你10美元作为小费。谢谢！ -- Gladly! Here are 10 bucks as a tip. Thanks!}
#{170}{}{Oh, no, I don't have money with me.}
{170}{}{哦，不，我身上没带钱。 -- Oh, no, I don't have money with me.}
#{171}{}{Oh well. It is a pity, because I'm hungry.}
{171}{}{哦，好吧。很遗憾，因为我饿了。 -- Oh well. It is a pity, because I'm hungry.}
#{172}{}{Goodbye.}
{172}{}{再见。 -- Goodbye.}
#{180}{}{Do you know anything about Provo's population?}
{180}{}{你知道普罗沃的人口吗？ -- Do you know anything about Provo's population?}
#{181}{}{Oh yes. It's an old story. The inhabitants of Provo were like the Ku Klux Klan from before the war. At first, the Sheriff used their bigotry and extremism for his own cause. He employed them to deal with certain undesirables, and when things improved he got rid of them. Since then, those rednecks hate the city and its citizens. They consider us crooks. After a while, they turned to brigandage, with criminals of all sorts joining their ranks.}
{181}{}{哦，是的。这是一个古老的故事。普罗沃的居民就像战前的三K党。起初，警长利用他们的偏执和极端主义为自己的事业。他雇用他们来对付某些不受欢迎的人，当情况好转时，他就把他们赶走了。从那时起，那些乡巴佬就憎恨这个城市和市民。他们认为我们是骗子。过了一会儿，他们转为强盗，各种各样的罪犯也加入了他们的行列。 -- Oh yes. It's an old story. The inhabitants of Provo were like the Ku Klux Klan from before the war. At first, the Sheriff used their bigotry and extremism for his own cause. He employed them to deal with certain undesirables, and when things improved he got rid of them. Since then, those rednecks hate the city and its citizens. They consider us crooks. After a while, they turned to brigandage, with criminals of all sorts joining their ranks.}
#{182}{}{The Sheriff asked me to deal with those criminals...}
{182}{}{警长让我对付那些罪犯。。。 -- The Sheriff asked me to deal with those criminals...}
#{183}{}{Oh? Well, it's no surprise. The rednecks has already robbed several caravans and even tried to sabotage the city. But the Sheriff doesn't want to openly wage war against them. You see, nobody knows much about Provo. There are bound to be a lot of traps scattered around the place waiting for an unwary target to set them off. The tactical situation is against the Sheriff, that's for sure. Anyway, if you decide to venture into the area, be on your guard and pay full attention to your surroundings.}
{183}{}{哦？嗯，这并不奇怪。红领军已经抢劫了好几辆商队，甚至试图破坏这座城市。但警长不想公开向他们开战。你看，没人对普罗沃了解太多。一定会有很多陷阱散布在这个地方，等待一个不小心的目标来引爆它们。战术上的情况是对警长不利的，这是肯定的。不管怎样，如果你决定冒险进入这个地区，要保持警惕，并充分注意你周围的环境。 -- Oh? Well, it's no surprise. The rednecks has already robbed several caravans and even tried to sabotage the city. But the Sheriff doesn't want to openly wage war against them. You see, nobody knows much about Provo. There are bound to be a lot of traps scattered around the place waiting for an unwary target to set them off. The tactical situation is against the Sheriff, that's for sure. Anyway, if you decide to venture into the area, be on your guard and pay full attention to your surroundings.}
#{184}{}{Understood.}
{184}{}{理解。 -- Understood.}
#{190}{}{I haven't seen such a large collection of books anywhere else. Where do the books in your library come from?}
{190}{}{我在别的地方没见过这么多的书。你们图书馆的书从哪里来？ -- I haven't seen such a large collection of books anywhere else. Where do the books in your library come from?}
#{191}{}{Well, I gathered these books from around the ruins with my own hands, believe it or not.}
{191}{}{不管你信不信，这些书是我亲手从废墟周围收集来的。 -- Well, I gathered these books from around the ruins with my own hands, believe it or not.}
#{192}{}{What a great example of selfless devotion to culture and education! You're a remarkable person.}
{192}{}{多么无私奉献文化教育的伟大典范！你是个了不起的人。 -- What a great example of selfless devotion to culture and education! You're a remarkable person.}
#{193}{}{A weird fetish to have for a resident of a destroyed city. Collecting knives would be a more useful occupation.}
{193}{}{对一个被摧毁城市的居民来说是一种奇怪的崇拜。收集刀具将是一个更有用的职业。 -- A weird fetish to have for a resident of a destroyed city. Collecting knives would be a more useful occupation.}
#{194}{}{What benefit is that to you?}
{194}{}{这对你有什么好处？ -- What benefit is that to you?}
#{195}{}{[Vernon chuckles.] That's rather an overstatement. Besides, it wasn't until later in my life that I began craving for literature. It took me several years to be able to see thoughts and ideas in writings, instead of viewing books purely as entertainment.}
{195}{}{[弗农咯咯笑了起来]这太夸张了。而且，直到晚年我才开始渴望文学。我花了好几年的时间才从作品中看到思想和想法，而不是单纯把书当作娱乐。 -- [Vernon chuckles.] That's rather an overstatement. Besides, it wasn't until later in my life that I began craving for literature. It took me several years to be able to see thoughts and ideas in writings, instead of viewing books purely as entertainment.}
#{196}{}{So collecting books wasn't originally your own idea?}
{196}{}{所以收集书籍不是你自己的主意？ -- So collecting books wasn't originally your own idea?}
#{197}{}{[Vernon chuckles.] There might be some benefits to hoarding knives, but it just gives off that odor of vanity and showing off. In my case, it wasn't like that at all. It wasn't because of enthusiasm that I started collecting books, I assure you. It took me several years to be able to see thoughts and ideas in writings, instead of viewing books purely as entertainment.}
{197}{}{[弗农咯咯笑着]囤积刀具也许有一些好处，但它只会散发出虚荣和炫耀的味道。对我来说，根本不是那样的。我向你保证，我不是因为热情才开始收集书籍的。我花了好几年的时间才从作品中看到思想和想法，而不是单纯把书当作娱乐。 -- [Vernon chuckles.] There might be some benefits to hoarding knives, but it just gives off that odor of vanity and showing off. In my case, it wasn't like that at all. It wasn't because of enthusiasm that I started collecting books, I assure you. It took me several years to be able to see thoughts and ideas in writings, instead of viewing books purely as entertainment.}
#{198}{}{It was a task given by our Mormon community. The Salt Lake City Public Library was destroyed during the nuclear attack. The fires that followed burned down many of the private libraries as well. The Mormons decided it was important to preserve the surviving remains of the pre-war wisdom. Nowadays, the main bulk of the archives is kept within the Mormon Church, and the books you see here are a private collection, for internal use only, so to speak.}
{198}{}{这是我们摩门教团体的任务。盐湖城公共图书馆在核攻击中被毁。随之而来的大火也烧毁了许多私人图书馆。摩门教徒认为保存战前遗留下来的智慧是很重要的。现在，大部分的档案都保存在摩门教教堂里，你在这里看到的书都是私人收藏，可以说是仅供内部使用。 -- It was a task given by our Mormon community. The Salt Lake City Public Library was destroyed during the nuclear attack. The fires that followed burned down many of the private libraries as well. The Mormons decided it was important to preserve the surviving remains of the pre-war wisdom. Nowadays, the main bulk of the archives is kept within the Mormon Church, and the books you see here are a private collection, for internal use only, so to speak.}
#{199}{}{I see.}
{199}{}{我懂了。 -- I see.}
#{200}{}{Do you have any books or magazines for sale?}
{200}{}{你们有卖书或杂志吗？ -- Do you have any books or magazines for sale?}
#{201}{}{Yes, I may have some, if you're interested.}
{201}{}{是的，如果你感兴趣的话，我可以买一些。 -- Yes, I may have some, if you're interested.}
#{202}{}{Tell me more.}
{202}{}{告诉我更多。 -- Tell me more.}
#{203}{}{No, thanks.}
{203}{}{不用了，谢谢。 -- No, thanks.}
#{204}{}{I happen to have a rare book on medicine - namely, on neurosurgery. Even if you don't practice medicine yourself, it will most likely be of interest to any professional doctor. I've never seen a more informational practical guide.}
{204}{}{我碰巧有一本关于医学的书——也就是神经外科。即使你自己不行医，也很可能是任何专业医生都感兴趣的。我从未见过比这更具信息性的实用指南。 -- I happen to have a rare book on medicine - namely, on neurosurgery. Even if you don't practice medicine yourself, it will most likely be of interest to any professional doctor. I've never seen a more informational practical guide.}
#{205}{}{How much for the book?}
{205}{}{这本书多少钱？ -- How much for the book?}
#{206}{}{Not interested.}
{206}{}{不感兴趣。 -- Not interested.}
#{207}{}{You know, at this stage of my life I don't value money as much as my own health. I have a heart condition and need a specific medication for it, which is nowhere to be found in the city. And I wasn't able to found it anywhere else myself.}
{207}{}{你知道，在我生命的这一阶段，我并不看重金钱，而是我自己的健康。我有心脏病，需要一种特殊的药物治疗，在城里找不到。我自己在别的地方也找不到。 -- You know, at this stage of my life I don't value money as much as my own health. I have a heart condition and need a specific medication for it, which is nowhere to be found in the city. And I wasn't able to found it anywhere else myself.}
#{208}{}{You say you need a cardiac medication? Alright, if I find some, I'll bring it to you.}
{208}{}{你说你需要心脏治疗？好吧，如果我找到一些，我会带给你的。 -- You say you need a cardiac medication? Alright, if I find some, I'll bring it to you.}
#{209}{}{You're in luck. I happen to have a vial of just the thing. Let's barter.}
{209}{}{你很幸运。我正好有一瓶这种东西。我们交换吧。 -- You're in luck. I happen to have a vial of just the thing. Let's barter.}
#{210}{}{I have the heart medication you wanted. I'll give it to you in exchange for the book on neurosurgery.}
{210}{}{我有你想要的心脏药物。我会把它给你，以换取那本神经外科的书。 -- I have the heart medication you wanted. I'll give it to you in exchange for the book on neurosurgery.}
#{211}{}{Thank you for giving me a chance to live longer!}
{211}{}{谢谢你给我一个活得更长的机会！ -- Thank you for giving me a chance to live longer!}
#{212}{}{You're welcome.}
{212}{}{不客气。 -- You're welcome.}
#{213}{}{You're going to like it, I'm sure! A fun little comic book from before the war. Get it, you won't regret it!}
{213}{}{我相信你会喜欢的！战前的一本有趣的小漫画书。明白了，你不会后悔的！ -- You're going to like it, I'm sure! A fun little comic book from before the war. Get it, you won't regret it!}
#{214}{}{What do you want in exchange for it?}
{214}{}{你想要什么交换？ -- What do you want in exchange for it?}
#{215}{}{Not money. Money can't buy you health. I hope you've heard about the situation with clean water in the city? The chemist very rarely has water purification tablets for sale. Bring me the tablets and you can have the comic book. It's worth all the effort.}
{215}{}{不是钱。金钱买不到健康。我希望你听说过这个城市清洁用水的情况？这位化学家很少有净水片出售。把平板电脑给我，你就可以拿到漫画书了。一切努力都是值得的。 -- Not money. Money can't buy you health. I hope you've heard about the situation with clean water in the city? The chemist very rarely has water purification tablets for sale. Bring me the tablets and you can have the comic book. It's worth all the effort.}
#{216}{}{I just happen to have the tablets. Let's barter.}
{216}{}{我正好有药片。我们交换吧。 -- I just happen to have the tablets. Let's barter.}
#{217}{}{Give me some time to think about it.}
{217}{}{给我点时间考虑一下。 -- Give me some time to think about it.}
#{218}{}{I have water purification tablets. I'll give them to you in exchange for the book on neurosurgery.}
{218}{}{我有净水片。我会把它们给你，以换取那本关于神经外科的书。 -- I have water purification tablets. I'll give them to you in exchange for the book on neurosurgery.}
#{219}{}{Since recently, I've had an automobile in my possession. Can you offer me anything on the topic?}
{219}{}{从最近开始，我就有了一辆汽车。关于这个话题你能给我一些建议吗？ -- Since recently, I've had an automobile in my possession. Can you offer me anything on the topic?}
#{220}{}{Oh, really? That's very, very interesting. Working automobiles are a great rarity these days. Well, I have a Chryslus Motors catalog. It's a very thick magazine, with many different articles and useful tips. But I will only sell such a rarity for a special price.}
{220}{}{哦，真的吗？那非常非常有趣。现在工作的汽车非常罕见。嗯，我有一个克莱斯勒汽车公司的目录。这是一本很厚的杂志，有许多不同的文章和有用的技巧。但我只会以特价出售这种珍品。 -- Oh, really? That's very, very interesting. Working automobiles are a great rarity these days. Well, I have a Chryslus Motors catalog. It's a very thick magazine, with many different articles and useful tips. But I will only sell such a rarity for a special price.}
#{221}{}{What's the price?}
{221}{}{价钱是多少？ -- What's the price?}
#{222}{}{Forget it, then.}
{222}{}{那就算了吧。 -- Forget it, then.}
#{223}{}{The same is ever. Heart medications. You know.}
{223}{}{永远都是这样。心脏药物。你知道的。 -- The same is ever. Heart medications. You know.}
#{224}{}{More pills for your heart? Phew! A second pack will be even harder to find than the first.}
{224}{}{你的心脏还有药吗？呸！第二包比第一包更难找到。 -- More pills for your heart? Phew! A second pack will be even harder to find than the first.}
#{225}{}{Here are the heart pills. Now about that Chryslus Motors catalog you promised...}
{225}{}{这是心脏药片。关于你答应的克莱斯勒汽车目录。。。 -- Here are the heart pills. Now about that Chryslus Motors catalog you promised...}
#{230}{}{Do you accept rare books and magazines?}
{230}{}{你们接受稀有的书籍和杂志吗？ -- Do you accept rare books and magazines?}
#{231}{}{I think I've found what you were looking for - a bundle of pre-war newspapers.}
{231}{}{我想我找到了你要找的东西-一捆战前的报纸。 -- I think I've found what you were looking for - a bundle of pre-war newspapers.}
#{232}{}{I have more than enough books, but can't say the same about serials. You see, I'd like to know more details about the last few months before the Great War. If you find something on the topic, I'll happily exchange it for one of my books.}
{232}{}{我的书已经够多了，但连载的书就不多了。你看，我想知道更多关于大战前几个月的细节。如果你找到关于这个话题的东西，我很乐意把它换成我的一本书。 -- I have more than enough books, but can't say the same about serials. You see, I'd like to know more details about the last few months before the Great War. If you find something on the topic, I'll happily exchange it for one of my books.}
#{233}{}{Hmm... It'll take a bit of work to find something like that.}
{233}{}{隐马尔可夫模型。。。要找到那样的东西要花点功夫。 -- Hmm... It'll take a bit of work to find something like that.}
#{234}{}{Hmm... [Vernon takes a good look at the articles.] Ah! Denver Post, isn't it! Goodness, it's been more than 50 years and they are still readable! Alright, you can pick something from my library in exchange for this, something valuable.}
{234}{}{隐马尔可夫模型。。。[弗农仔细看了一下文章]啊！丹佛邮报，不是吗！天哪，已经50多年了，它们仍然可读！好吧，你可以从我的图书馆里选一些东西来交换这个，一些有价值的东西。 -- Hmm... [Vernon takes a good look at the articles.] Ah! Denver Post, isn't it! Goodness, it's been more than 50 years and they are still readable! Alright, you can pick something from my library in exchange for this, something valuable.}
#{235}{}{I need a guide on surviving in the wilderness.}
{235}{}{我需要一个野外生存指南。 -- I need a guide on surviving in the wilderness.}
#{236}{}{I'll give you the newspapers in exchange for the book on electronics.}
{236}{}{我把报纸给你换那本关于电子学的书。 -- I'll give you the newspapers in exchange for the book on electronics.}
#{237}{}{Give me the manual of first aid - and the newspapers are yours.}
{237}{}{把急救手册给我，报纸就是你的了。 -- Give me the manual of first aid - and the newspapers are yours.}
#{238}{}{How about some scientific books?}
{238}{}{一些科学书籍怎么样？ -- How about some scientific books?}
#{239}{}{Do you have anything dealing with traps?}
{239}{}{你有什么关于陷阱的东西吗？ -- Do you have anything dealing with traps?}
#{240}{}{I'm interested in works about firearms.}
{240}{}{我对有关枪械的作品感兴趣。 -- I'm interested in works about firearms.}
#{241}{}{I've been looking for something on energy weapons...}
{241}{}{我一直在寻找能量武器。。。 -- I've been looking for something on energy weapons...}
#{242}{}{I want to read these newspapers first. I'll bring them to you when I'm finished.}
{242}{}{我想先看这些报纸。我吃完了就给你拿来。 -- I want to read these newspapers first. I'll bring them to you when I'm finished.}
#{243}{}{Teach you something? Well, I taught writing and mathematics to many residents of the city, but people usually stopped there. These days people are more practical and prefer not to waste their time on something of dubious benefit.}
{243}{}{教你点什么？嗯，我给城里的许多居民教写作和数学，但人们通常都在那里停下来。现在人们更加实际，不愿意把时间浪费在一些可疑的好处上。 -- Teach you something? Well, I taught writing and mathematics to many residents of the city, but people usually stopped there. These days people are more practical and prefer not to waste their time on something of dubious benefit.}
#{244}{}{Public speaking.}
{244}{}{公开演讲。 -- Public speaking.}
#{245}{}{Secrets of gambling.}
{245}{}{赌博的秘密。 -- Secrets of gambling.}
#{246}{}{No, thanks.}
{246}{}{不用了，谢谢。 -- No, thanks.}
#{247}{}{Perhaps, you'll find the "Scout Handbook" useful? You should definitely give it a read: much helpful information on surviving in the wilderness can be found here.}
{247}{}{也许，你会发现“童子军手册”有用？你一定要读一读：这里有很多关于野外生存的有用信息。 -- Perhaps, you'll find the "Scout Handbook" useful? You should definitely give it a read: much helpful information on surviving in the wilderness can be found here.}
#{248}{}{"Dean's Electronics". I happen to have the last remaining copy shelved. These days, study books like this sell like hotcakes.}
{248}{}{“迪安电子”。我碰巧把剩下的最后一本搁置了。现在，像这样的学习书籍很畅销。 -- "Dean's Electronics". I happen to have the last remaining copy shelved. These days, study books like this sell like hotcakes.}
#{249}{}{Yes, I have one last book on theory and practice of first aid, itching to be traded for a decent pack of newspapers.}
{249}{}{是的，我还有最后一本关于急救理论和实践的书，渴望能换一包像样的报纸。 -- Yes, I have one last book on theory and practice of first aid, itching to be traded for a decent pack of newspapers.}
#{250}{}{Alright, I'll gather the most interesting scientific publications for you.}
{250}{}{好的，我会为你收集最有趣的科学出版物。 -- Alright, I'll gather the most interesting scientific publications for you.}
#{251}{}{"Maddock's Tricks & Traps" is what you need. A *very* rare exemplar, but you're in luck, because I have it.}
{251}{}{"Maddock's Tricks & Traps" is what you need. A *very* rare exemplar, but you're in luck, because I have it. -- "Maddock's Tricks & Traps" is what you need. A *very* rare exemplar, but you're in luck, because I have it.}
#{252}{}{Then "Guns and Bullets" would be the thing you're looking for. And I have it.}
{252}{}{那么“枪和子弹”就是你要找的东西了。我有它。 -- Then "Guns and Bullets" would be the thing you're looking for. And I have it.}
#{253}{}{No, I'm interested in something else.}
{253}{}{不，我对别的东西感兴趣。 -- No, I'm interested in something else.}
#{254}{}{Yes, this will work. Let's trade.}
{254}{}{是的，这会有用的。我们交易吧。 -- Yes, this will work. Let's trade.}
#{255}{}{Thank you, wonderer, it was a pleasure dealing with you.}
{255}{}{谢谢你，奇妙的人，很高兴和你打交道。 -- Thank you, wonderer, it was a pleasure dealing with you.}
#{256}{}{Likewise. Goodbye.}
{256}{}{同样地。再见。 -- Likewise. Goodbye.}
#{257}{}{}
{257}{}{ -- }
#{258}{}{}
{258}{}{ -- }
#{259}{}{[Nods sarcastically.] Shame on you!}
{259}{}{你真丢脸！ -- [Nods sarcastically.] Shame on you!}
#{260}{}{I see you're not easy to fool.}
{260}{}{我看你不容易被愚弄。 -- I see you're not easy to fool.}
#{261}{}{I wonder - was it really so hard to find newspapers in this city?}
{261}{}{我想知道-在这个城市真的很难找到报纸吗？ -- I wonder - was it really so hard to find newspapers in this city?}
#{262}{}{It sure was. Firstly, before the war Salt Lake was a huge city with socially-minded citizens, so newspapers were in high demand. Secondly, newspapers degrade quickly, especially in a humid climate like the one here. I've already gone through all the dispensers in the area, barring those in radioactive zones and uninhabited districts. I most likely wasn't the first to do so, because I couldn't find anything of value. Alack and alas.}
{262}{}{确实是。首先，在战争之前，盐湖城是一个有社会意识的大城市，所以报纸的需求量很大。其次，报纸的质量下降很快，特别是在像这里这样潮湿的气候下。我已经检查了该地区所有的分配器，除了那些在放射性区和无人居住区。我很可能不是第一个这样做的，因为我找不到任何有价值的东西。唉，唉。 -- It sure was. Firstly, before the war Salt Lake was a huge city with socially-minded citizens, so newspapers were in high demand. Secondly, newspapers degrade quickly, especially in a humid climate like the one here. I've already gone through all the dispensers in the area, barring those in radioactive zones and uninhabited districts. I most likely wasn't the first to do so, because I couldn't find anything of value. Alack and alas.}
#{263}{}{I see. Well, goodbye.}
{263}{}{我懂了。好吧，再见。 -- I see. Well, goodbye.}
#{264}{}{Oh, I see. There aren't many of them left nowadays, are there? And not much in terms of detailed information about it, either. And to think that once there was a whole magazine series about that exact topic called "Super Science". Indeed, I'm parting with the only issue I have here.}
{264}{}{哦，我明白了。现在已经不多了，是吗？关于它的详细信息也不多。想想看，曾经有一整本杂志都是关于“超级科学”这个主题的。事实上，我要放弃我这里唯一的问题。 -- Oh, I see. There aren't many of them left nowadays, are there? And not much in terms of detailed information about it, either. And to think that once there was a whole magazine series about that exact topic called "Super Science". Indeed, I'm parting with the only issue I have here.}
#{265}{}{Well, you obviously don't have anything more "valuable" than books here. Okay, let's see what you have.}
{265}{}{很明显，你这里没有比书更“有价值”的东西了。好吧，让我们看看你有什么。 -- Well, you obviously don't have anything more "valuable" than books here. Okay, let's see what you have.}
#{266}{}{Hmm, what about a lesson? Surely you can teach me something.}
{266}{}{嗯，上一课怎么样？你一定能教我点东西。 -- Hmm, what about a lesson? Surely you can teach me something.}
#{267}{}{My library is the biggest in the city. Tell me what you need and I'll try to find it.}
{267}{}{我的图书馆是城里最大的。告诉我你需要什么，我会设法找到的。 -- My library is the biggest in the city. Tell me what you need and I'll try to find it.}
#{268}{}{What are you talking about?}
{268}{}{你在说什么？ -- What are you talking about?}
#{269}{}{Anyway, I have other interests.}
{269}{}{不管怎样，我还有其他兴趣。 -- Anyway, I have other interests.}
#{270}{}{A good topic for a lecture. Or even a series of lectures. But, as with books, the more you already know, the less I can teach you. So, what do you say? Shall we start?}
{270}{}{演讲的好题目。甚至是一系列的讲座。但是，就像书一样，你知道的越多，我教你的就越少。那么，你怎么说？我们开始吧？ -- A good topic for a lecture. Or even a series of lectures. But, as with books, the more you already know, the less I can teach you. So, what do you say? Shall we start?}
#{271}{}{Please start, Professor.}
{271}{}{请开始吧，教授。 -- Please start, Professor.}
#{272}{}{...And that's about it for today. Do you have any questions?}
{272}{}{……今天就到此为止。你有什么问题吗？ -- ...And that's about it for today. Do you have any questions?}
#{273}{}{That was very insightful. I only have one question: was it really so hard to find newspapers in this city?}
{273}{}{很有见地。我只有一个问题：在这个城市真的很难找到报纸吗？ -- That was very insightful. I only have one question: was it really so hard to find newspapers in this city?}
#{274}{}{Thanks for the lesson. No questions. I have to go - find ways to use the newly acquired knowledge.}
{274}{}{谢谢你的教训。没有问题。我得去-想办法利用新学到的知识。 -- Thanks for the lesson. No questions. I have to go - find ways to use the newly acquired knowledge.}
#{275}{}{I'm not exactly sure that I can teach you anything you don't already know.}
{275}{}{我不确定我能不能教你一些你还不知道的东西。 -- I'm not exactly sure that I can teach you anything you don't already know.}
#{300}{}{Youth these days...}
{300}{}{年轻的这些天。。。 -- Youth these days...}
#{301}{}{No, that's not it, not it...}
{301}{}{不，不是这样，不是这样。。。 -- No, that's not it, not it...}
#{302}{}{No, really, this comedian should've been hanged at once.}
{302}{}{不，真的，这个喜剧演员应该马上被绞死。 -- No, really, this comedian should've been hanged at once.}
#{303}{}{Nothing interesting about this.}
{303}{}{没什么有趣的。 -- Nothing interesting about this.}
#{304}{}{Another dime novel.}
{304}{}{又是一本廉价小说。 -- Another dime novel.}
#{305}{}{This is nonsense! Oh... It's a book on psychiatry...}
{305}{}{这是胡说八道！哦。。。这是一本关于精神病学的书。。。 -- This is nonsense! Oh... It's a book on psychiatry...}
#{306}{}{My God, if only I was born in 19th century!}
{306}{}{天哪，要是我出生在19世纪就好了！ -- My God, if only I was born in 19th century!}
#{307}{}{Civilization has become... Free, yes.}
{307}{}{文明已经变成。。。免费的，是的。 -- Civilization has become... Free, yes.}
#{308}{}{You can't really be strong until you see a funny side to things.}
{308}{}{只有看到事物有趣的一面，你才能真正坚强。 -- You can't really be strong until you see a funny side to things.}
#{309}{}{You have to laugh at the things that hurt you to keep the world from running you plumb crazy.}
{309}{}{你必须嘲笑那些伤害你的事情，才能让世界不让你发疯。 -- You have to laugh at the things that hurt you to keep the world from running you plumb crazy.}
#{310}{}{He who marches out of line hears another drum.}
{310}{}{越行越远的人听到的是另一个鼓声。 -- He who marches out of line hears another drum.}
#{311}{}{Whoever comes in the door is usually somebody disappointing.}
{311}{}{不管谁进门，通常都是令人失望的人。 -- Whoever comes in the door is usually somebody disappointing.}
#{312}{}{Every minute spent brooding alone only increases your separation.}
{312}{}{独自沉思的每一分钟只会增加你的分离。 -- Every minute spent brooding alone only increases your separation.}
#{313}{}{It's the truth, even if it didn't happen.}
{313}{}{这是事实，即使没有发生。 -- It's the truth, even if it didn't happen.}
#{314}{}{It's really too bad that so much crumby stuff is a lot of fun sometimes.}
{314}{}{真的太可惜了，这么多易碎的东西有时很有趣。 -- It's really too bad that so much crumby stuff is a lot of fun sometimes.}
#{315}{}{Nobody who's really using his real ego has any time for any goddamn hobbies.}
{315}{}{没有一个真正利用自我的人有时间做他妈的爱好。 -- Nobody who's really using his real ego has any time for any goddamn hobbies.}
#{316}{}{It's better for certain things to stay the way they are.}
{316}{}{某些事情最好保持现状。 -- It's better for certain things to stay the way they are.}
#{317}{}{I wish I knew why people think it's so important to be emotional.}
{317}{}{我希望我知道为什么人们认为情感是如此重要。 -- I wish I knew why people think it's so important to be emotional.}
#{318}{}{Do cats eat bats? Do bats eat cats?}
{318}{}{猫吃蝙蝠吗？蝙蝠吃猫吗？ -- Do cats eat bats? Do bats eat cats?}
#{319}{}{Why is a raven like a writing desk?}
{319}{}{为什么乌鸦像写字台？ -- Why is a raven like a writing desk?}
#{320}{}{If you don't know where you are going, any road will get you there.}
{320}{}{如果你不知道你要去哪里，任何一条路都会把你带到那里。 -- If you don't know where you are going, any road will get you there.}
#{321}{}{Everything has sense in it, only you should find it.}
{321}{}{一切都是有意义的，只有你应该找到它。 -- Everything has sense in it, only you should find it.}
#{322}{}{I'm older than you and must know better.}
{322}{}{我比你大，一定知道得更清楚。 -- I'm older than you and must know better.}
#{323}{}{Begin at the beginning and go on till you come to the end, then stop.}
{323}{}{从头开始，一直走到最后，然后停下来。 -- Begin at the beginning and go on till you come to the end, then stop.}
#{1123}{}{Well now! If you knew more about him, young lady, you'd understand that that "humble dwelling" of Diogenes was quite *sufficient* for him and the conditions he lived in: after all, the climate, the scenery, the company...}
{1123}{}{好吧，现在！如果你对他了解得更多，小姐，你就会明白提奥奇尼斯的“简陋住所”对他和他所处的条件来说是相当“足够”的：毕竟，这里的气候、风景、公司。。。 -- Well now! If you knew more about him, young lady, you'd understand that that "humble dwelling" of Diogenes was quite *sufficient* for him and the conditions he lived in: after all, the climate, the scenery, the company...}
#{1255}{}{Thank you, wanderer, it was a pleasure dealing with you.}
{1255}{}{谢谢你，流浪汉，很高兴和你打交道。 -- Thank you, wanderer, it was a pleasure dealing with you.}
