#{100}{}{You see a worker.}
{100}{}{你看到一个工人。 -- You see a worker.}
#{101}{}{This is just another ordinary laborer in the factory.}
{101}{}{这只是工厂里的另一个普通工人。 -- This is just another ordinary laborer in the factory.}
#{102}{}{I'm busy, let's talk after work}
{102}{}{我很忙，下班后再谈吧 -- I'm busy, let's talk after work}
#{103}{}{I'm not used to talking with my mouth full}
{103}{}{我不习惯满嘴食物说话 -- I'm not used to talking with my mouth full}
#{112}{}{Hey, buddy! Outsiders are not allowed near the tanks, it's a closed area of the factory. So turn around!}
{112}{}{嘿，伙计！不允许外人靠近油罐，这是工厂的禁区。所以转过身来！ -- Hey, buddy! Outsiders are not allowed near the tanks, it's a closed area of the factory. So turn around!}
#{113}{}{Outsiders are not allowed near the tanks, it's a closed area of the factory. So turn around!}
{113}{}{不允许外人靠近油罐，这是工厂的禁区。所以转过身来！ -- Outsiders are not allowed near the tanks, it's a closed area of the factory. So turn around!}
#{114}{}{Ugh...}
{114}{}{呃。。。 -- Ugh...}
#{250}{}{At this rate, I will make enough money to open my own factory!}
{250}{}{照这个速度，我会赚足够的钱开自己的工厂！ -- At this rate, I will make enough money to open my own factory!}
#{251}{}{Now I'm gonna have a lot of booze!}
{251}{}{现在我要喝很多酒了！ -- Now I'm gonna have a lot of booze!}
#{252}{}{Today I'll get the best chick in the city!}
{252}{}{今天我要找城里最好的小妞！ -- Today I'll get the best chick in the city!}
#{253}{}{And they were telling me that honest work will get you nowhere! Bah!}
{253}{}{他们告诉我诚实的工作不会让你一事无成！呸！ -- And they were telling me that honest work will get you nowhere! Bah!}
#{254}{}{With these conditions, I will work for days!}
{254}{}{有了这些条件，我要工作几天！ -- With these conditions, I will work for days!}
#{255}{}{Let's praise our Lord, brothers!}
{255}{}{让我们赞美我们的主，兄弟们！ -- Let's praise our Lord, brothers!}
#{256}{}{Everybody to the "Tin angel" today! I'm buying!}
{256}{}{今天大家都到“锡天使”来！我要买！ -- Everybody to the "Tin angel" today! I'm buying!}
#{257}{}{Finally, my old woman will cease to nag me...}
{257}{}{最后，我的老太太将不再唠叨我。。。 -- Finally, my old woman will cease to nag me...}
#{258}{}{Yes! Yes! Who said we are losers? Ha-ha!}
{258}{}{对！对！谁说我们是失败者？哈哈！ -- Yes! Yes! Who said we are losers? Ha-ha!}
#{259}{}{::happily hums something about a priest and 10 whores::}
{259}{}{●愉快地哼着一个牧师和10个妓女的歌： -- ::happily hums something about a priest and 10 whores::}
#{260}{}{It was worth to pick through all the cogs and screws of that fucking machines!}
{260}{}{把那该死的机器的齿轮和螺丝都挑出来是值得的！ -- It was worth to pick through all the cogs and screws of that fucking machines!}
#{261}{}{I'm ready to buy the one that helped us the best booze in Salt Lake for a week!}
{261}{}{我已经准备好买一个帮助我们在盐湖喝上一周最好的酒了！ -- I'm ready to buy the one that helped us the best booze in Salt Lake for a week!}
#{262}{}{Can't believe someone actually helped us! Let's make a monument of empty bottles to honor him!}
{262}{}{真不敢相信有人真的帮了我们！让我们用空瓶子来纪念他吧！ -- Can't believe someone actually helped us! Let's make a monument of empty bottles to honor him!}
#{263}{}{My lucky cap of Nuka-Cola has finally helped me!}
{263}{}{我的幸运帽努卡可乐终于帮助了我！ -- My lucky cap of Nuka-Cola has finally helped me!}
#{264}{}{I am now a successful man! Call me "sir"!}
{264}{}{我现在是一个成功的人！叫我“先生”！ -- I am now a successful man! Call me "sir"!}
#{265}{}{Nuka-Cola! The taste of victory!}
{265}{}{努卡可乐！胜利的滋味！ -- Nuka-Cola! The taste of victory!}
#{266}{}{Nuka-Cola! Obey your thirst!}
{266}{}{努卡可乐！服从你的渴望！ -- Nuka-Cola! Obey your thirst!}
#{267}{}{Nuka-Cola! Now 5 rad/h less!}
{267}{}{努卡可乐！现在减少5 rad/h！ -- Nuka-Cola! Now 5 rad/h less!}
#{268}{}{Life is good!}
{268}{}{生活是美好的！ -- Life is good!}
#{269}{}{No more brahmin shit for dinner!}
{269}{}{晚餐不要再吃婆罗门屎了！ -- No more brahmin shit for dinner!}
#{300}{}{Here comes another day, but the shit remains the same...}
{300}{}{又是一天，但大便依旧。。。 -- Here comes another day, but the shit remains the same...}
#{301}{}{Another pitiful day...}
{301}{}{又是可怜的一天。。。 -- Another pitiful day...}
#{302}{}{Machine number 3 isn't working again...}
{302}{}{3号机器又坏了。。。 -- Machine number 3 isn't working again...}
#{303}{}{Ow, the hangover...}
{303}{}{哦，宿醉。。。 -- Ow, the hangover...}
#{304}{}{Who pissed into the concentrate again?!}
{304}{}{谁又尿到浓缩液里了？！ -- Who pissed into the concentrate again?!}
#{305}{}{How are the things? Same, same...}
{305}{}{情况怎么样？一样，一样。。。 -- How are the things? Same, same...}
#{306}{}{To work? Why?}
{306}{}{去上班？为什么？ -- To work? Why?}
#{307}{}{Working overtime again...}
{307}{}{又加班了。。。 -- Working overtime again...}
#{308}{}{I'd better be herding brahmin...}
{308}{}{我最好去放牧婆罗门。。。 -- I'd better be herding brahmin...}
#{309}{}{Just hold out until the evening...}
{309}{}{坚持到晚上。。。 -- Just hold out until the evening...}
#{310}{}{Who took my beer?!!}
{310}{}{谁拿了我的啤酒？！！ -- Who took my beer?!!}
#{311}{}{I'm sick of staring at this Nuka-Cola!}
{311}{}{我讨厌盯着这个努卡可乐看！ -- I'm sick of staring at this Nuka-Cola!}
#{312}{}{Who worked today on the third machine? It's messed up again!}
{312}{}{今天谁在第三台机器上工作？又搞砸了！ -- Who worked today on the third machine? It's messed up again!}
#{313}{}{Where can I lie down for an hour?}
{313}{}{我在哪能躺一个小时？ -- Where can I lie down for an hour?}
#{314}{}{::looks back grimly, kicking some part from the machine::}
{314}{}{●冷酷地向后看，从机器上踢出一部分： -- ::looks back grimly, kicking some part from the machine::}
#{315}{}{If only I would be put in charge! I would have brought order!}
{315}{}{要是我能负责就好了！我会带来秩序的！ -- If only I would be put in charge! I would have brought order!}
#{316}{}{Instead of this shit they would be better making beer!}
{316}{}{与其做这些，不如做啤酒！ -- Instead of this shit they would be better making beer!}
#{317}{}{They should make moonshine - we would be bathed in gold...}
{317}{}{他们应该制造私酒-我们将沐浴在黄金之中。。。 -- They should make moonshine - we would be bathed in gold...}
#{318}{}{If only someone could help us...}
{318}{}{如果有人能帮我们。。。 -- If only someone could help us...}
#{319}{}{Didn't work and will not work!}
{319}{}{没用也不会用！ -- Didn't work and will not work!}
#{350}{}{Oh, crap... No, not like the usual shit - much worse...}
{350}{}{哦，该死。。。不，不像平常那样-更糟。。。 -- Oh, crap... No, not like the usual shit - much worse...}
#{351}{}{Time to change my job...}
{351}{}{是时候换工作了。。。 -- Time to change my job...}
#{352}{}{I have a raider brother... Maybe I should go join him?}
{352}{}{我有一个袭击者兄弟。。。也许我该和他一起去？ -- I have a raider brother... Maybe I should go join him?}
#{353}{}{What shitty prank could I pull on the manager before quitting?}
{353}{}{辞职前我能跟经理开什么恶作剧？ -- What shitty prank could I pull on the manager before quitting?}
#{354}{}{I'd rather be in slavery, than working here!}
{354}{}{我宁愿做奴隶，也不愿在这里工作！ -- I'd rather be in slavery, than working here!}
#{355}{}{Work in two shifts, no weekends, and here is the result...}
{355}{}{两班倒，没有周末，结果是。。。 -- Work in two shifts, no weekends, and here is the result...}
#{356}{}{Don't even have any poison to kill myself... But wait, there is Nuka-Cola! Beats arsenic any day!}
{356}{}{连自杀的毒药都没有。。。但是等等，有努卡可乐！任何一天都比砒霜强！ -- Don't even have any poison to kill myself... But wait, there is Nuka-Cola! Beats arsenic any day!}
#{357}{}{Nuka-Cola! The taste of victory? Is it? Hmm...}
{357}{}{努卡可乐！胜利的滋味？它是？隐马尔可夫模型。。。 -- Nuka-Cola! The taste of victory? Is it? Hmm...}
#{358}{}{Will drown the foreman in the concentrate tank - and to Vegas!}
{358}{}{会把工头淹死在浓缩液罐里-然后去维加斯！ -- Will drown the foreman in the concentrate tank - and to Vegas!}
#{359}{}{The payment is bigger even for cleaning brahmin shit!}
{359}{}{即使是洗婆罗门的屎，报酬也更高！ -- The payment is bigger even for cleaning brahmin shit!}
#{360}{}{Gonna have to sell my kidney...}
{360}{}{我得卖掉我的肾。。。 -- Gonna have to sell my kidney...}
#{361}{}{Will wait for the Ghost Train and just throw myself under its wheels...}
{361}{}{会等着幽灵火车然后把自己扔到它的轮子下。。。 -- Will wait for the Ghost Train and just throw myself under its wheels...}
#{362}{}{I told them - they should put more money into advertisement!}
{362}{}{我告诉他们-他们应该在广告上投入更多的钱！ -- I told them - they should put more money into advertisement!}
#{363}{}{I quit... I heard Vegas needs sewage workers...}
{363}{}{我辞职了。。。我听说维加斯需要排污工人。。。 -- I quit... I heard Vegas needs sewage workers...}
#{364}{}{Shoot myself first, or kill my wife with the kids?}
{364}{}{先开枪自杀，还是带着孩子杀了我妻子？ -- Shoot myself first, or kill my wife with the kids?}
#{365}{}{What should I eat? Brahmin gum dish with the rat shit on the side?}
{365}{}{我应该吃什么？婆罗门口香糖盘旁边有老鼠屎？ -- What should I eat? Brahmin gum dish with the rat shit on the side?}
#{366}{}{Let's dismantle the machines! Maybe the scrap is worth something...}
{366}{}{让我们把机器拆了！也许这些废品有价值。。。 -- Let's dismantle the machines! Maybe the scrap is worth something...}
#{367}{}{Today, everyone to the "Tin angel"! We'll celebrate my funeral!}
{367}{}{今天，大家来“锡天使”！我们要庆祝我的葬礼！ -- Today, everyone to the "Tin angel"! We'll celebrate my funeral!}
#{368}{}{Honest hard worker in our time will achieve nothing...}
{368}{}{我们这个时代诚实努力的人一事无成。。。 -- Honest hard worker in our time will achieve nothing...}
#{369}{}{Maybe I would do better at the Hoover dam?}
{369}{}{也许我会在胡佛大坝做得更好？ -- Maybe I would do better at the Hoover dam?}
