#{10}{}{ }
{10}{}{  --  }
#{100}{}{You see a client.}
{100}{}{你看到一个客户。 -- You see a client.}
#{101}{}{You see Tin Angel's patron.}
{101}{}{你看到锡天使的赞助人了。 -- You see Tin Angel's patron.}
#{102}{}{God damn it, Joe was the best...}
{102}{}{他妈的，乔是最好的。。。 -- God damn it, Joe was the best...}
#{103}{}{Ha, Joe is killing it today!}
{103}{}{哈，乔今天要杀了它！ -- Ha, Joe is killing it today!}
#{104}{}{This guy at the bar should be hanged.}
{104}{}{酒吧里的这个家伙应该被吊死。 -- This guy at the bar should be hanged.}
#{105}{}{What? Let me listen that crazy bastard.}
{105}{}{什么？让我听听那个疯子。 -- What? Let me listen that crazy bastard.}
