#{100}{}{Not in combat!}
{100}{}{不是在战斗中！ -- Not in combat!}
#{101}{}{You are looking doubtfully upwards - to where the water drips, and the sky is barely visible through the small windows. The spiral staircase goes into darkness, and you can't see the end of it. It's a hell of an artesian tower! The ascent to its apex would take a lot of energy.}
{101}{}{你怀疑地向上看——水滴落的地方，透过小窗户几乎看不见天空。螺旋楼梯进入黑暗，你看不到它的尽头。这是一个地狱般的自流塔！攀登到顶峰需要大量的能量。 -- You are looking doubtfully upwards - to where the water drips, and the sky is barely visible through the small windows. The spiral staircase goes into darkness, and you can't see the end of it. It's a hell of an artesian tower! The ascent to its apex would take a lot of energy.}
#{102}{}{I'll fall powerless if I won't rest.}
{102}{}{如果我不休息，我会失去力量的。 -- I'll fall powerless if I won't rest.}
#{103}{}{Climb up, risking your health.}
{103}{}{冒着健康的危险爬上去。 -- Climb up, risking your health.}
#{104}{}{Exit.}
{104}{}{出口。 -- Exit.}
#{105}{}{Ugh! What a view! Is Salt Lake really this dirty?!}
{105}{}{啊！多美的景色啊！盐湖真的这么脏吗？！ -- Ugh! What a view! Is Salt Lake really this dirty?!}
#{106}{}{You are on top of the broken artesian tower. A stunning panorama view opens from here.}
{106}{}{你在破碎的自流塔上。从这里可以看到令人惊叹的全景。 -- You are on top of the broken artesian tower. A stunning panorama view opens from here.}
#{107}{}{Panoramic view from the top of the tower temporarily sharpens your perception.}
{107}{}{从塔顶俯瞰的全景能暂时提高你的感知力。 -- Panoramic view from the top of the tower temporarily sharpens your perception.}
