#{100}{}{Vending machine is out of order.}
{100}{}{自动售货机坏了。 -- Vending machine is out of order.}
#{101}{}{}
{101}{}{ -- }
#{102}{}{You won't get much with your bare hands from this vending machine.}
{102}{}{你徒手从这台自动售货机上拿不到多少钱。 -- You won't get much with your bare hands from this vending machine.}
#{103}{}{It's empty}
{103}{}{它是空的 -- It's empty}
#{104}{}{You've already robbed this vending machine and hoarded all change.}
{104}{}{你已经抢了这台自动售货机，把所有的零钱都藏起来了。 -- You've already robbed this vending machine and hoarded all change.}
#{105}{}{Can't do anything with this.}
{105}{}{我什么也做不了。 -- Can't do anything with this.}
#{106}{}{Good thinking, but you can't manually break the register of this solid machine.}
{106}{}{好主意，但是你不能手动打破这台固态机器的寄存器。 -- Good thinking, but you can't manually break the register of this solid machine.}
#{107}{}{You managed to pick the lock and open the back cover of the machine. Now you've got all the change!}
{107}{}{你设法撬开了锁，打开了机器的后盖。现在你有了所有的零钱！ -- You managed to pick the lock and open the back cover of the machine. Now you've got all the change!}
#{108}{}{Yes!}
{108}{}{对！ -- Yes!}
#{109}{}{You weren't able to pick the lock.}
{109}{}{你没能撬开锁。 -- You weren't able to pick the lock.}
#{110}{}{You were able to open the back cover using tools. Now you've got all the change!}
{110}{}{你可以用工具打开封底。现在你有了所有的零钱！ -- You were able to open the back cover using tools. Now you've got all the change!}
#{111}{}{You got }
{111}{}{你有吗 -- You got }
#{112}{}{ bucks.}
{112}{}{美元。 --  bucks.}
