#{100}{}{Barrel with combustible mixture.}
{100}{}{装有可燃混合物的桶。 -- Barrel with combustible mixture.}
#{101}{}{Blown up barrel.}
{101}{}{炸了的桶。 -- Blown up barrel.}
#{102}{}{A heavy barrel with a flammable chemical composition of unknown purpose. Clearly not fuel.}
{102}{}{不明用途的含有易燃化学成分的重桶。显然不是燃料。 -- A heavy barrel with a flammable chemical composition of unknown purpose. Clearly not fuel.}
#{103}{}{Remnants of the metal barrels.}
{103}{}{金属桶的残余物。 -- Remnants of the metal barrels.}
#{104}{}{Barrel is going to explode!}
{104}{}{枪管要爆炸了！ -- Barrel is going to explode!}
