#{100}{}{You see Wright's guard.}
{100}{}{你看到赖特的卫兵了。 -- You see Wright's guard.}
#{101}{}{You see one of Mr. Wright's guards.}
{101}{}{你看到赖特先生的一个警卫了。 -- You see one of Mr. Wright's guards.}
#{102}{}{You here to see Mr. Wright? He's in his office.}
{102}{}{你是来看赖特先生的吗？他在办公室。 -- You here to see Mr. Wright? He's in his office.}
#{103}{}{Mr. Wright's sleeping now. Come back in the morning.}
{103}{}{赖特先生正在睡觉。明早再来。 -- Mr. Wright's sleeping now. Come back in the morning.}
#{104}{}{The entrance is right up the street.}
{104}{}{入口就在这条街的正对面。 -- The entrance is right up the street.}
#{105}{}{I've got my eye on you.}
{105}{}{我盯上你了。 -- I've got my eye on you.}
#{106}{}{Mr. Wright's asleep. Keep moving.}
{106}{}{赖特先生睡着了。继续前进。 -- Mr. Wright's asleep. Keep moving.}
#{107}{}{You see one of Mr. Wright's guards. The resemblance to Wright himself is uncanny.}
{107}{}{你看到赖特先生的一个警卫了。与赖特本人的相似之处是不可思议的。 -- You see one of Mr. Wright's guards. The resemblance to Wright himself is uncanny.}
#{108}{}{The boss is... He's not here. Just get out!}
{108}{}{老板是。。。他不在这儿。出去！ -- The boss is... He's not here. Just get out!}
#{109}{}{ }
{109}{}{  --  }
#{110}{}{Hey, did you miss me?}
{110}{}{嘿，你想我了吗？ -- Hey, did you miss me?}
#{111}{}{Oh, Chuck, it's you again...}
{111}{}{哦，查克，又是你。。。 -- Oh, Chuck, it's you again...}
#{112}{}{I'm just here to say hi. What's the problem?}
{112}{}{我只是来打个招呼的。有什么问题吗？ -- I'm just here to say hi. What's the problem?}
#{113}{}{Stop it, Chuck. We've talked about this.}
{113}{}{住手，查克。我们已经谈过了。 -- Stop it, Chuck. We've talked about this.}
#{114}{}{Come on! What does he need so many wives for, anyway?}
{114}{}{加油！他为什么需要这么多老婆？ -- Come on! What does he need so many wives for, anyway?}
#{115}{}{Status, Chuck. Status, and a desire to continue his bloodline.}
{115}{}{状态，查克。地位和延续血统的愿望。 -- Status, Chuck. Status, and a desire to continue his bloodline.}
#{116}{}{A bloodline?! What's wrong with any of us?! I have brothers all over Reno, and -}
{116}{}{血统？！我们有什么问题吗？！我的兄弟遍布雷诺，还有- -- A bloodline?! What's wrong with any of us?! I have brothers all over Reno, and -}
#{117}{}{Don't you dare!}
{117}{}{你敢！ -- Don't you dare!}
#{118}{}{- and he's got more wives than any man could need!}
{118}{}{-他妻子比任何男人都多！ -- - and he's got more wives than any man could need!}
#{119}{}{You really won't understand. He cares for this family. You just care about yourself.}
{119}{}{你不会明白的。他关心这个家庭。你只关心你自己。 -- You really won't understand. He cares for this family. You just care about yourself.}
#{120}{}{Oh, yeah, so noble. That's dad, for sure! All heart!}
{120}{}{哦，是啊，太高尚了。那当然是爸爸！全心投入！ -- Oh, yeah, so noble. That's dad, for sure! All heart!}
#{121}{}{You have no right to judge him. He gave you life and a job.}
{121}{}{你无权评判他。他给了你生命和工作。 -- You have no right to judge him. He gave you life and a job.}
#{122}{}{I... All he gives me is money. I want more. I want you!}
{122}{}{一、 。。。他只给我钱。我想要更多。我想要你！ -- I... All he gives me is money. I want more. I want you!}
#{123}{}{No, Chuck. I've told you this before.}
{123}{}{不，查克。我以前跟你说过。 -- No, Chuck. I've told you this before.}
#{124}{}{You're breaking my heart!}
{124}{}{你伤了我的心！ -- You're breaking my heart!}
#{125}{}{I never asked for your heart. Don't blame its condition on me.}
{125}{}{我从来没有要过你的心。别怪我的状况。 -- I never asked for your heart. Don't blame its condition on me.}
#{126}{}{Why are you so loyal to him? You're all less than half his age!}
{126}{}{你为什么对他这么忠诚？你们都还不到他年龄的一半！ -- Why are you so loyal to him? You're all less than half his age!}
#{127}{}{If you have to ask this question, you have no idea what loyalty means. But you've shown that already.}
{127}{}{如果你要问这个问题，你不知道什么是忠诚。但你已经证明了这一点。 -- If you have to ask this question, you have no idea what loyalty means. But you've shown that already.}
#{128}{}{Why are you cruel to me?}
{128}{}{你为什么对我这么残忍？ -- Why are you cruel to me?}
#{129}{}{Why are you here at all? Aren't you on duty?}
{129}{}{你为什么在这里？你不是值班吗？ -- Why are you here at all? Aren't you on duty?}
#{130}{}{What's gonna happen? Dad's asleep, and the doors are guarded.}
{130}{}{会发生什么？爸爸睡着了，门有人看守。 -- What's gonna happen? Dad's asleep, and the doors are guarded.}
#{131}{}{Anything can happen in this city.}
{131}{}{这个城市什么事都可能发生。 -- Anything can happen in this city.}
#{132}{}{I'm only a few feet from the door! No one's getting in.}
{132}{}{我离门只有几英尺远！没人进去。 -- I'm only a few feet from the door! No one's getting in.}
#{133}{}{Maybe. But if Wright finds out you're in here...}
{133}{}{也许 吧。但如果赖特发现你在这里。。。 -- Maybe. But if Wright finds out you're in here...}
#{134}{}{Be reasonable. I can't just stand next to his bedroom door all night!}
{134}{}{讲道理。我不能整晚都站在他卧室门口！ -- Be reasonable. I can't just stand next to his bedroom door all night!}
#{135}{}{Try explaining it to your father... Maybe he'll give you a chair. Tee-hee!}
{135}{}{试着向你父亲解释一下。。。也许他会给你一把椅子。嘻嘻！ -- Try explaining it to your father... Maybe he'll give you a chair. Tee-hee!}
#{136}{}{Grr! Yeah, laugh it up. I'll try to forget your cruelty over a bottle of whiskey.}
{136}{}{格瑞！是啊，笑一笑。我会努力忘记你喝威士忌时的残忍。 -- Grr! Yeah, laugh it up. I'll try to forget your cruelty over a bottle of whiskey.}
#{137}{}{Heh-hee...}
{137}{}{嘿嘿。。。 -- Heh-hee...}
#{138}{}{::sniff:: What's that, apple pie for my father?}
{138}{}{嗅嗅：那是什么，给我父亲的苹果派？ -- ::sniff:: What's that, apple pie for my father?}
#{139}{}{Yes, made with love.}
{139}{}{是的，是爱做的。 -- Yes, made with love.}
#{140}{}{It sure would be nice to have some...}
{140}{}{如果能有一些。。。 -- It sure would be nice to have some...}
#{141}{}{There's the door. Go and find someone to make it for you.}
{141}{}{门在那儿。去找人给你做吧。 -- There's the door. Go and find someone to make it for you.}
#{142}{}{::sigh::}
{142}{}{●叹息： -- ::sigh::}
#{150}{}{Hey, what the fuck are you doing here?! You can't come here at night! Get the fuck out of here!}
{150}{}{嘿，你他妈的在这里干什么？！你晚上不能来这里！他妈的滚出去！ -- Hey, what the fuck are you doing here?! You can't come here at night! Get the fuck out of here!}
#{151}{}{[Leave.]}
{151}{}{[离开] -- [Leave.]}
#{152}{}{Die, thief!!}
{152}{}{死吧，小偷！！ -- Die, thief!!}
#{153}{}{Don't you dare come here! I'll paint the ceiling with your brains!}
{153}{}{你敢来这里！我要用你的脑子来粉刷天花板！ -- Don't you dare come here! I'll paint the ceiling with your brains!}
#{154}{}{Hey, who let you in here? People are trying to sleep! Get the fuck out!}
{154}{}{嘿，谁让你进来的？人们都想睡觉！滚出去！ -- Hey, who let you in here? People are trying to sleep! Get the fuck out!}
#{155}{}{No one get in today. Come back in a week.}
{155}{}{今天没人进来。一周后再来。 -- No one get in today. Come back in a week.}
#{156}{}{Want to meet Mr. Wright? Lose the guns first.}
{156}{}{想见赖特先生吗？先把枪丢了。 -- Want to meet Mr. Wright? Lose the guns first.}
