#{100}{}{You see Barton the trader.}
{100}{}{你看到商人巴顿了。 -- You see Barton the trader.}
#{101}{}{You see a tired trader, lazily picking through his stock on a table.}
{101}{}{你看到一个疲惫的交易者，懒洋洋地在桌子上挑选他的股票。 -- You see a tired trader, lazily picking through his stock on a table.}
#{110}{}{Looking for something, friend?}
{110}{}{在找什么吗，朋友？ -- Looking for something, friend?}
#{111}{}{Yeah, show me what you've got.}
{111}{}{是的，让我看看你有什么。 -- Yeah, show me what you've got.}
#{112}{}{Don't think I am. Goodbye.}
{112}{}{别以为我是。再见。 -- Don't think I am. Goodbye.}
#{113}{}{Pleasure doing business with you. Anything else?}
{113}{}{很高兴和你做生意。还有别的吗？ -- Pleasure doing business with you. Anything else?}
#{114}{}{Show me what you have again. I think I forgot something.}
{114}{}{再给我看看你有什么。我想我忘了什么。 -- Show me what you have again. I think I forgot something.}
#{115}{}{Yeah, I think that's it. Goodbye.}
{115}{}{是的，我想就是这样。再见。 -- Yeah, I think that's it. Goodbye.}
#{116}{}{Look who it is! Always happy to see you. Good must be answered with good, right? I think I can make you a little discount on you-know-who's recommendation. I don't give prices like that to everyone!}
{116}{}{看看是谁！见到你总是很高兴。善有善报，对吗？我想我可以在你知道谁的推荐信上给你一点折扣。我不会给每个人这样的价格！ -- Look who it is! Always happy to see you. Good must be answered with good, right? I think I can make you a little discount on you-know-who's recommendation. I don't give prices like that to everyone!}
#{117}{}{Let's get to it then.}
{117}{}{那我们开始吧。 -- Let's get to it then.}
#{118}{}{Appreciate it, but I'm not here to buy.}
{118}{}{谢谢，但我不是来买的。 -- Appreciate it, but I'm not here to buy.}
#{119}{}{I talked to some caravaneers recently. They say a lot of good things about you. I think you deserve a little discount.}
{119}{}{我最近和一些商队的人谈过。他们说了很多关于你的好话。我认为你应该得到一点折扣。 -- I talked to some caravaneers recently. They say a lot of good things about you. I think you deserve a little discount.}
#{120}{}{I talked to some caravaneers recently. They don't have many nice things to say about you. And I value their opinion. So, from now on, this place will be more expensive to you. And don't even try to argue, you know what you did.}
{120}{}{我最近和一些商队的人谈过。他们对你没什么好说的。我很重视他们的意见。所以，从现在起，这个地方对你来说会更贵。别想争辩，你知道你做了什么。 -- I talked to some caravaneers recently. They don't have many nice things to say about you. And I value their opinion. So, from now on, this place will be more expensive to you. And don't even try to argue, you know what you did.}
#{121}{}{Everyone in the local slums is talking about you. I appreciate what you do for these poor people. If you're going to buy from me, I'll make sure to give you a nice discount.}
{121}{}{当地贫民窟的每个人都在谈论你。我很感激你为这些穷人所做的一切。如果你要买我的东西，我一定给你一个很好的折扣。 -- Everyone in the local slums is talking about you. I appreciate what you do for these poor people. If you're going to buy from me, I'll make sure to give you a nice discount.}
#{122}{}{Everyone in the local slums is talking about you. And not in the best of ways. You know what happens to people who act like that in this city? Their prices get raised so they get the hell out of here. But, I don't want to fight, unlike some of the others. Just know that my prices for you are now higher.}
{122}{}{当地贫民窟的每个人都在谈论你。而且不是以最好的方式。你知道在这个城市这样做的人会怎么样吗？他们的价格提高了，所以他们离开这里。但是，我不想打架，不像其他人。你要知道我给你的价格现在更高了。 -- Everyone in the local slums is talking about you. And not in the best of ways. You know what happens to people who act like that in this city? Their prices get raised so they get the hell out of here. But, I don't want to fight, unlike some of the others. Just know that my prices for you are now higher.}
#{123}{}{You received a 10% discount at Barton's store.}
{123}{}{你在巴顿的店里得到了10%的折扣。 -- You received a 10% discount at Barton's store.}
#{124}{}{You received a 5% discount at Barton's store.}
{124}{}{你在巴顿的店里得到了5%的折扣。 -- You received a 5% discount at Barton's store.}
#{125}{}{Sheriff? You're the new Sheriff of Uranium City? Amazing! It's an honor to see you in my store. By the way, I saved up a little something for a special client. A .44 revolver and some ammo! I think it will fit your holster quite well. I'll sell it at a discount.}
{125}{}{警长？你是铀城的新警长？太神了！很荣幸在我店里见到你。顺便说一句，我存了点钱给一个特别的客户。一把44口径的左轮手枪和一些子弹！我想它很适合你的皮套。我要打折出售。 -- Sheriff? You're the new Sheriff of Uranium City? Amazing! It's an honor to see you in my store. By the way, I saved up a little something for a special client. A .44 revolver and some ammo! I think it will fit your holster quite well. I'll sell it at a discount.}
#{126}{}{[Noticing your shady appearance, he scowls before shaking his head] Don't even think about it. I see your types from a mile away. Keep your hands where I can see them!}
{126}{}{[注意到你阴暗的外表，他在摇头前愁眉不展]想都别想。我从一英里外就能看到你的类型。把手放在我能看见的地方！ -- [Noticing your shady appearance, he scowls before shaking his head] Don't even think about it. I see your types from a mile away. Keep your hands where I can see them!}
#{127}{}{Barton has recognized your thieving tendencies and raised his prices by 10%.}
{127}{}{巴顿已经认识到你的偷窃倾向，把价格提高了10%。 -- Barton has recognized your thieving tendencies and raised his prices by 10%.}
#{128}{}{Hey, would you look at that. A bunch of marauders recently cracked open the Hawthorne base. Dragged out anything that wasn't nailed down. Got some sweet new toys. Take a look, maybe you'll find something you like.}
{128}{}{嘿，你看看那个。一群劫匪最近攻破了霍桑基地。把没有钉牢的东西都拖出来。买了些可爱的新玩具。看看，也许你会找到你喜欢的东西。 -- Hey, would you look at that. A bunch of marauders recently cracked open the Hawthorne base. Dragged out anything that wasn't nailed down. Got some sweet new toys. Take a look, maybe you'll find something you like.}
#{130}{}{What's that on the counter? Stagecoach tickets?}
{130}{}{柜台上是什么？驿站马车票？ -- What's that on the counter? Stagecoach tickets?}
#{131}{}{Yeah. The stagecoach only takes cash, so I buy a few tickets from the "Nevada Express" for those who want to barter other things. Feel free to get one, it's easier than waiting until your wallet fills up.}
{131}{}{是 啊。驿站马车只收现金，所以我从“内华达快车”买了几张票给那些想用其他东西交换东西的人。随便买一个吧，这比等钱包满了再买容易多了。 -- Yeah. The stagecoach only takes cash, so I buy a few tickets from the "Nevada Express" for those who want to barter other things. Feel free to get one, it's easier than waiting until your wallet fills up.}
#{132}{}{What's the catch?}
{132}{}{有什么问题吗？ -- What's the catch?}
#{133}{}{Great, let's trade.}
{133}{}{太好了，我们交易吧。 -- Great, let's trade.}
#{134}{}{There is none. You see, the stagecoach only takes cash, so I... Wait, I already said that. Otherwise, it's all up to you. Feel free to buy from the "Nevada Express" administrator if you have the cash.}
{134}{}{没有。你看，驿站马车只收现金，所以我。。。等等，我已经说过了。否则，就全靠你了。如果您有现金，请随时从“内华达快车”管理员处购买。 -- There is none. You see, the stagecoach only takes cash, so I... Wait, I already said that. Otherwise, it's all up to you. Feel free to buy from the "Nevada Express" administrator if you have the cash.}
#{135}{}{And I still smell rat. You wouldn't have done this if you didn't see profits along with the deal.}
{135}{}{我还闻到老鼠的味道。如果你没有看到交易带来的利润，你就不会这么做。 -- And I still smell rat. You wouldn't have done this if you didn't see profits along with the deal.}
#{136}{}{[Twists his lips in a grim smirk] Well, you got me. Yeah, I do get a profit. Buying tickets from me is much more expensive. But I think that's fair, considering I need to process the bartered goods later.}
{136}{}{[冷笑着扭动嘴唇]好吧，你抓住我了。是的，我确实赚了钱。从我这里买票要贵得多。但考虑到我以后需要处理易货，我认为这是公平的。 -- [Twists his lips in a grim smirk] Well, you got me. Yeah, I do get a profit. Buying tickets from me is much more expensive. But I think that's fair, considering I need to process the bartered goods later.}
#{137}{}{Thanks, but I was here for something else.}
{137}{}{谢谢，但我是来找别的事的。 -- Thanks, but I was here for something else.}
#{140}{}{I'm looking for Jay Kukish, a biker. Seen him?}
{140}{}{我在找杰伊·库基什，一个摩托车手。看见他了吗？ -- I'm looking for Jay Kukish, a biker. Seen him?}
#{141}{}{Well, not like I know the bikers by name. Although, there have been a lot of them recently, seemed like they were planning something. Saw one go over to stay the night at the Silver Legacy. Ask the guy at the front desk for more info.}
{141}{}{嗯，我可不知道那些摩托车手的名字。虽然，最近有很多人，好像他们在计划什么。我看见一个人去银遗产酒店过夜。向前台的人要更多的信息。 -- Well, not like I know the bikers by name. Although, there have been a lot of them recently, seemed like they were planning something. Saw one go over to stay the night at the Silver Legacy. Ask the guy at the front desk for more info.}
#{142}{}{Thanks.}
{142}{}{谢谢。 -- Thanks.}
#{250}{}{I have a question.}
{250}{}{我有个问题。 -- I have a question.}
#{251}{}{Shoot.}
{251}{}{开枪。 -- Shoot.}
#{252}{}{Nothing else for now.}
{252}{}{现在没有别的了。 -- Nothing else for now.}
#{253}{}{Thanks, but I have another question.}
{253}{}{谢谢，但我还有一个问题。 -- Thanks, but I have another question.}
#{254}{}{That's enough for now.}
{254}{}{现在已经够了。 -- That's enough for now.}
#{255}{}{I'm new here. Mind helping out with some advice?}
{255}{}{我是新来的。介意帮忙提些建议吗？ -- I'm new here. Mind helping out with some advice?}
#{256}{}{Well, I wouldn't suggest going anywhere further than El Dorado. The city is dangerous for newcomers. Street thugs, dealers, just scum and, finally, revolutionaries from both sides - it's easier than ever to find trouble. Our little district around the hotel is the safest and most cultured place. You know what - just go talk to the receptionist at the hotel. He'll tell you a lot more about the city than me.}
{256}{}{好吧，我不建议去比埃尔多拉多更远的地方。这个城市对新来的人来说很危险。街头暴徒，商人，只是渣滓，最后，双方的革命者-这比以往任何时候都更容易找到麻烦。我们酒店周围的小区是最安全、最有文化的地方。你知道吗-去和酒店的接待员谈谈。他会告诉你比我更多关于这个城市的事。 -- Well, I wouldn't suggest going anywhere further than El Dorado. The city is dangerous for newcomers. Street thugs, dealers, just scum and, finally, revolutionaries from both sides - it's easier than ever to find trouble. Our little district around the hotel is the safest and most cultured place. You know what - just go talk to the receptionist at the hotel. He'll tell you a lot more about the city than me.}
#{257}{}{Why are there so many caravaneers here?}
{257}{}{为什么这里有这么多商队？ -- Why are there so many caravaneers here?}
#{258}{}{This place is the only caravan stop in town. Good place to rest before a new route. All the better for me - they tend to have some great wares. That's why most of the trade in the city is centered here.}
{258}{}{这个地方是镇上唯一的商队停靠点。在走新路线前休息的好地方。对我来说就更好了——他们往往有一些很棒的商品。这就是为什么这个城市的大部分贸易都集中在这里。 -- This place is the only caravan stop in town. Good place to rest before a new route. All the better for me - they tend to have some great wares. That's why most of the trade in the city is centered here.}
#{260}{}{I'm looking for a slave... Well, a particular slave.}
{260}{}{我在找一个奴隶。。。嗯，一个特别的奴隶。 -- I'm looking for a slave... Well, a particular slave.}
#{261}{}{Hey, listen, I don't deal in slaves. Not like they're popular around here. The residents aren't living any better - except they don't wear collars.}
{261}{}{嘿，听着，我不卖奴隶。不像他们在这里很受欢迎。居民们的生活没有任何改善，只是他们没有戴项圈。 -- Hey, listen, I don't deal in slaves. Not like they're popular around here. The residents aren't living any better - except they don't wear collars.}
#{262}{}{Well, let's suppose I need a slave. Where would I get one?}
{262}{}{好吧，假设我需要一个奴隶。我在哪买？ -- Well, let's suppose I need a slave. Where would I get one?}
#{263}{}{Hm, usually, those who need slaves either form a special squad or order from Vegas. But that rarely happens. The biggest slave owner around here is Mister Oliver Luciano. You could try and buy a slave from him. Wright also used to buy slaves, before he closed his mines.}
{263}{}{嗯，通常，那些需要奴隶的人要么组成一个特别小组，要么从维加斯来。但这种情况很少发生。这里最大的奴隶主是奥利弗·卢西亚诺先生。你可以试着从他那里买个奴隶。赖特在关闭矿场之前也曾购买奴隶。 -- Hm, usually, those who need slaves either form a special squad or order from Vegas. But that rarely happens. The biggest slave owner around here is Mister Oliver Luciano. You could try and buy a slave from him. Wright also used to buy slaves, before he closed his mines.}
#{264}{}{So, Luciano then. Thank you for the advice.}
{264}{}{那么，卢西亚诺。谢谢你的建议。 -- So, Luciano then. Thank you for the advice.}
#{265}{}{What do you know about the bikers?}
{265}{}{你对摩托车手了解多少？ -- What do you know about the bikers?}
#{266}{}{Not much. They don't like to talk about their lives and don't tend to stick around for long. Most consider them an ordinary gang - wanderers with good guns and an intolerable attitude. But the "Nevada Express" is talking about bikers hitting one of their stagecoaches. Sounds rather convincing. Ask Tuco, if you want to hear more about the attack.}
{266}{}{不多。他们不喜欢谈论自己的生活，也不想在这里呆太久。大多数人认为他们是一个普通的流氓，枪法好，态度恶劣。但是“内华达快车”说的是骑自行车的人撞上了他们的马车。听起来很有说服力。问图科，如果你想知道更多关于这次袭击的情况。 -- Not much. They don't like to talk about their lives and don't tend to stick around for long. Most consider them an ordinary gang - wanderers with good guns and an intolerable attitude. But the "Nevada Express" is talking about bikers hitting one of their stagecoaches. Sounds rather convincing. Ask Tuco, if you want to hear more about the attack.}
#{270}{}{Did you see a fat man with a scar on his neck?}
{270}{}{你看到一个脖子上有疤的胖男人了吗？ -- Did you see a fat man with a scar on his neck?}
#{271}{}{You know who the bald guy at the entrance is?}
{271}{}{你知道入口处那个秃头是谁吗？ -- You know who the bald guy at the entrance is?}
#{272}{}{Where's that bald guy at the entrance now?}
{272}{}{入口处那个秃子现在在哪里？ -- Where's that bald guy at the entrance now?}
#{273}{}{Yeah, saw someone like that. Hung around the caravaneers, wanted to go somewhere. Ask them, they might tell you more.}
{273}{}{是啊，我见过这样的人。在商队里闲逛，想去什么地方。问问他们，他们可能会告诉你更多。 -- Yeah, saw someone like that. Hung around the caravaneers, wanted to go somewhere. Ask them, they might tell you more.}
#{274}{}{Shady guy. Speaks like a bandit but his clothes are fine and tries to keep a high tone. Definitely just visiting, especially when he's trying to cut a deal with the caravaneers. They aren't stupid either, can smell something's off. Don't know anything else.}
{274}{}{阴暗的家伙。说话像强盗，但他的衣服很好，并试图保持一个高语气。当然只是拜访，尤其是当他想和商队达成协议的时候。他们也不笨，能闻到什么东西掉了。我什么都不知道。 -- Shady guy. Speaks like a bandit but his clothes are fine and tries to keep a high tone. Definitely just visiting, especially when he's trying to cut a deal with the caravaneers. They aren't stupid either, can smell something's off. Don't know anything else.}
#{275}{}{Think he left for Vegas with a caravan, if my memory serves me right.}
{275}{}{如果我没记错的话，我想他带着一辆大篷车去了维加斯。 -- Think he left for Vegas with a caravan, if my memory serves me right.}
#{276}{}{We could organize a deal about Nuka-Cola sales.}
{276}{}{我们可以组织一个关于努卡可乐销售的交易。 -- We could organize a deal about Nuka-Cola sales.}
#{277}{}{But I don't sell food. The caravaneers buy from the Silver restaurant. Or, in the worst case, that small cafe near El Dorado. Perhaps they'd be more interested.}
{277}{}{但我不卖食物。商队从银餐厅买东西。或者，在最坏的情况下，在埃尔多拉多附近的小咖啡馆。也许他们会更感兴趣。 -- But I don't sell food. The caravaneers buy from the Silver restaurant. Or, in the worst case, that small cafe near El Dorado. Perhaps they'd be more interested.}
#{278}{}{Restaurant or cafe? I'll go see if they're interested.}
{278}{}{餐厅还是咖啡馆？我去看看他们是否感兴趣。 -- Restaurant or cafe? I'll go see if they're interested.}
#{282}{}{What's with the scant weapon stock?}
{282}{}{武器库存不足怎么了？ -- What's with the scant weapon stock?}
#{283}{}{[Surprised] You're kidding?! In this city, you're lucky if you find a good rifle just being traded, and if for a reasonable price - double lucky!}
{283}{}{你在开玩笑？！在这个城市，如果你发现一支好的步枪刚刚被交易，如果价格合理，你就是幸运的——双倍幸运！ -- [Surprised] You're kidding?! In this city, you're lucky if you find a good rifle just being traded, and if for a reasonable price - double lucky!}
#{284}{}{Why?}
{284}{}{为什么？ -- Why?}
#{285}{}{Hm, good question. Let me try and explain why I think it's so.}
{285}{}{嗯，问得好。让我试着解释一下为什么我这么认为。 -- Hm, good question. Let me try and explain why I think it's so.}
#{286}{}{Go ahead, I'm curious to hear it.}
{286}{}{说吧，我很想听。 -- Go ahead, I'm curious to hear it.}
#{287}{}{Not now.}
{287}{}{不是现在。 -- Not now.}
#{288}{}{First of all, this city never had much military presence before the Great War, so there's only civilian weapons here. And, as soon as a good gun appears on the market, it's bought by some rich gangster. Even ancient pieces are getting used, like by the El Dorado guards, for example.}
{288}{}{首先，这座城市在大战前从来没有多少军事存在，所以这里只有民用武器。而且，一旦一把好枪出现在市场上，它就被一些有钱的歹徒买走了。即使是古老的作品也在被使用，比如埃尔多拉多卫兵。 -- First of all, this city never had much military presence before the Great War, so there's only civilian weapons here. And, as soon as a good gun appears on the market, it's bought by some rich gangster. Even ancient pieces are getting used, like by the El Dorado guards, for example.}
#{289}{}{[Continue]}
{289}{}{[继续] -- [Continue]}
#{290}{}{You're probably wondering where the military arms are, the most powerful and reliable. My best bet would be that there's some left on the army bases, since nobody managed to get in yet. I heard talk of three bases around Nevada. Those brave enough to try and return told about deadly defense turrets and even of terrible mutants. Those are all rumors, but they seem to carry some weight. How else would you explain such a lack of military-grade arms in a country with such a militaristic past? Although, if anyone around has great arms, then it's Wind of War. They store everything they could loot or trade at their base.}
{290}{}{你可能想知道军事武器在哪里，最强大最可靠的。我最好的办法是在陆军基地还有一些，因为还没人能进去。我听说内华达州有三个基地。那些勇敢的尝试和回报告诉致命的防御炮塔，甚至可怕的变种人。这些都是谣言，但似乎有些分量。否则你怎么解释一个有着如此军国主义历史的国家如此缺乏军事级武器？虽然，如果周围有人有伟大的武器，那就是战争之风。他们把所有可以抢劫或交易的东西都储存在基地里。 -- You're probably wondering where the military arms are, the most powerful and reliable. My best bet would be that there's some left on the army bases, since nobody managed to get in yet. I heard talk of three bases around Nevada. Those brave enough to try and return told about deadly defense turrets and even of terrible mutants. Those are all rumors, but they seem to carry some weight. How else would you explain such a lack of military-grade arms in a country with such a militaristic past? Although, if anyone around has great arms, then it's Wind of War. They store everything they could loot or trade at their base.}
#{291}{}{What is that weapon you mentioned the El Dorado guards carrying?}
{291}{}{你提到的埃尔多拉多卫兵携带的武器是什么？ -- What is that weapon you mentioned the El Dorado guards carrying?}
#{292}{}{Tommy guns? They're pretty damn ancient, belong in a damn museum. I'm pretty sure the owner bought them just for the sake of style. Showing off and nothing else. I think he managed to buy every Tommy gun in the state. At the very least, I didn't see any outside of El Dorado.}
{292}{}{汤米枪？它们很古老，应该放在博物馆里。我敢肯定店主买它们只是为了时尚。只是炫耀而已。我想他买了全州所有的汤米枪。至少，我在埃尔多拉多外面没有看到任何东西。 -- Tommy guns? They're pretty damn ancient, belong in a damn museum. I'm pretty sure the owner bought them just for the sake of style. Showing off and nothing else. I think he managed to buy every Tommy gun in the state. At the very least, I didn't see any outside of El Dorado.}
#{293}{}{Thanks for explaining.}
{293}{}{谢谢你的解释。 -- Thanks for explaining.}
#{294}{}{This girl from the photo, has she ever shown her face here?}
{294}{}{照片上的这个女孩，她在这里露脸过吗？ -- This girl from the photo, has she ever shown her face here?}
#{295}{}{Cute, but her type doesn't tend to come around here.}
{295}{}{可爱，但她的类型在这里不常见。 -- Cute, but her type doesn't tend to come around here.}
#{296}{}{What about the name Ted Bundy. Does it mean anything to you?}
{296}{}{那泰德·邦迪的名字呢。这对你有什么意义吗？ -- What about the name Ted Bundy. Does it mean anything to you?}
#{297}{}{Nothing. I sell goods here, if you want info - ask a bartender. Heh, they like that kind of thing - it's their job.}
{297}{}{没有什么。我在这里卖东西，如果你想要信息-去问酒保。嘿，他们喜欢这种东西-这是他们的工作。 -- Nothing. I sell goods here, if you want info - ask a bartender. Heh, they like that kind of thing - it's their job.}
#{298}{}{Got it.}
{298}{}{知道了。 -- Got it.}
#{300}{}{Is this the only normal shop in Reno?}
{300}{}{这是雷诺唯一的普通商店吗？ -- Is this the only normal shop in Reno?}
#{301}{}{Well, how should I put it... I have the biggest shop in Reno - that's true. All thanks to the caravan stop and their personal trust. But I have an affiliate down south. And he tends to have some fancier stock.}
{301}{}{好吧，我该怎么说。。。我在里诺有一家最大的商店-没错。这一切都要感谢商队的驻足和他们的个人信任。但我在南方有一个分支机构。而且他往往有一些花哨的股票。 -- Well, how should I put it... I have the biggest shop in Reno - that's true. All thanks to the caravan stop and their personal trust. But I have an affiliate down south. And he tends to have some fancier stock.}
#{302}{}{Tell me more about this associate.}
{302}{}{告诉我更多关于这个同事的事。 -- Tell me more about this associate.}
#{303}{}{Well, I've got a helper of sorts. The type of risky fella who trades down south. The only normal town down there is the Hub. Although the road there is long and hard. You'll need to comb through most of the southern roads. His name's Hardy, by the way. You won't confuse him with anyone else - ghouls are rare in these parts.}
{303}{}{嗯，我有个帮手。在南方交易的那种冒险的家伙。那里唯一正常的城镇是中心。尽管那里的路漫长而艰难。你需要把大部分南部的路都梳理一遍。顺便说一下，他的名字叫哈迪。你不会把他和其他人搞混的-这些地方很少有食尸鬼。 -- Well, I've got a helper of sorts. The type of risky fella who trades down south. The only normal town down there is the Hub. Although the road there is long and hard. You'll need to comb through most of the southern roads. His name's Hardy, by the way. You won't confuse him with anyone else - ghouls are rare in these parts.}
#{304}{}{Hm. The costs of such a dangerous trip should cover themselves twice. That means the south has something special. Why only one caravan then?}
{304}{}{嗯，这样危险的旅行的费用应该是他们自己付的两倍。这意味着南方有一些特别的东西。为什么只有一个商队？ -- Hm. The costs of such a dangerous trip should cover themselves twice. That means the south has something special. Why only one caravan then?}
#{305}{}{Hey, you seem to know a thing or two about trade! You know, our region got really lucky - most of the city was left undamaged by the Great War and the radiation was lower. But, in the south, any decently sized city was reduced to radioactive rubble. But it's much easier to find weapons and ammo. That's why the biggest branch of trade we've got is our meds and supplies for their guns. And the reason it's just one caravan is because there aren't really enough people willing to risk their lives.}
{305}{}{嘿，你好像对贸易很了解！你知道，我们的地区真的很幸运——城市的大部分都没有受到大战的破坏，辐射也更低。但是，在南方，任何一个规模适中的城市都被夷为平地。但是找到武器和弹药要容易得多。这就是为什么我们最大的贸易分支是我们的药物和他们的枪支用品。之所以只有一个车队是因为没有足够的人愿意冒生命危险。 -- Hey, you seem to know a thing or two about trade! You know, our region got really lucky - most of the city was left undamaged by the Great War and the radiation was lower. But, in the south, any decently sized city was reduced to radioactive rubble. But it's much easier to find weapons and ammo. That's why the biggest branch of trade we've got is our meds and supplies for their guns. And the reason it's just one caravan is because there aren't really enough people willing to risk their lives.}
#{306}{}{Is there a caravan going to the Hub anywhere?}
{306}{}{有大篷车去中心吗？ -- Is there a caravan going to the Hub anywhere?}
#{307}{}{About Hardy. I need to send a note to the Hub through him.}
{307}{}{关于哈代。我要通过他给中心发张条子。 -- About Hardy. I need to send a note to the Hub through him.}
#{308}{}{You received 100 exp for successfully using your barter skill to learn about a caravan route.}
{308}{}{成功使用易货技巧学习商队路线，获得100经验。 -- You received 100 exp for successfully using your barter skill to learn about a caravan route.}
#{310}{}{I need to send a note with him to the Hub.}
{310}{}{我要和他一起寄张纸条到中心去。 -- I need to send a note with him to the Hub.}
#{311}{}{No problem, I'll pass him the letter. But I'm expecting a tip, understand?}
{311}{}{没问题，我把信递给他。但我在等小费，明白吗？ -- No problem, I'll pass him the letter. But I'm expecting a tip, understand?}
#{312}{}{Considering your reputation, I'll do it. No problem.}
{312}{}{考虑到你的名声，我会做的。没问题。 -- Considering your reputation, I'll do it. No problem.}
#{313}{}{Great. Here it is and a hundred bucks for your troubles.}
{313}{}{伟大的。给你，一百块钱给你。 -- Great. Here it is and a hundred bucks for your troubles.}
#{314}{}{Great. Here it is.}
{314}{}{伟大的。给你。 -- Great. Here it is.}
#{315}{}{No thanks, I think I'll try and find Hardy to give the letter personally... }
{315}{}{不，谢谢，我想我会试着找哈代亲自把信交给你。。。 -- No thanks, I think I'll try and find Hardy to give the letter personally... }
#{316}{}{Then I wish you luck. Oh, how you'll need it. The route to the south is difficult for a caravan, and there almost no settlements. So the search could take quite a while.}
{316}{}{那我祝你好运。哦，你怎么会需要它。通往南方的路线对于商队来说很困难，而且几乎没有定居点。所以搜寻可能需要一段时间。 -- Then I wish you luck. Oh, how you'll need it. The route to the south is difficult for a caravan, and there almost no settlements. So the search could take quite a while.}
#{317}{}{Understood.}
{317}{}{理解。 -- Understood.}
#{318}{}{You completed Lewis Birch's task.}
{318}{}{你完成了刘易斯·伯奇的任务。 -- You completed Lewis Birch's task.}
#{319}{}{The package fell out of your bag while you were talking to the trader.}
{319}{}{当你和商人谈话时，包裹从你的包里掉了出来。 -- The package fell out of your bag while you were talking to the trader.}
#{1110}{}{Looking for something, beautiful?}
{1110}{}{在找什么东西吗，美女？ -- Looking for something, beautiful?}
#{1114}{}{Show me what you have again. I think I forgot something.}
{1114}{}{再给我看看你有什么。我想我忘了什么。 -- Show me what you have again. I think I forgot something.}
#{1136}{}{[Twists his lips in a grim smirk] Well, you got me. Yeah, I do get a profit. Buying tickets from me is much more expensive. But I think that's fair considering I need to process the bartered goods later.}
{1136}{}{[冷笑着扭动嘴唇]好吧，你抓住我了。是的，我确实赚了钱。从我这里买票要贵得多。但考虑到我以后需要处理易货，我认为这是公平的。 -- [Twists his lips in a grim smirk] Well, you got me. Yeah, I do get a profit. Buying tickets from me is much more expensive. But I think that's fair considering I need to process the bartered goods later.}
