#{100}{}{You see a guard.}
{100}{}{你看到一个警卫。 -- You see a guard.}
#{101}{}{You see a hefty bodyguard.}
{101}{}{你看到一个高大的保镖。 -- You see a hefty bodyguard.}
#{102}{}{I'll go see what happened.}
{102}{}{我去看看发生了什么事。 -- I'll go see what happened.}
#{103}{}{Hey, you! If you see someone sneak in here, tear off his hands, clear?}
{103}{}{嘿，你！如果你看到有人偷偷进来，把他的手撕下来，明白吗？ -- Hey, you! If you see someone sneak in here, tear off his hands, clear?}
#{104}{}{Something's not right. We should warn the others.}
{104}{}{有点不对劲。我们应该警告其他人。 -- Something's not right. We should warn the others.}
#{105}{}{Uh... Okay.}
{105}{}{休斯敦大学。。。可以。 -- Uh... Okay.}
#{106}{}{I'm gonna find who did that and show him a *real* blackout.}
{106}{}{我要找到是谁干的，给他看一个真正的昏迷。 -- I'm gonna find who did that and show him a *real* blackout.}
#{107}{}{Well, if it isn't our saboteur!}
{107}{}{如果不是我们的破坏者！ -- Well, if it isn't our saboteur!}
#{108}{}{Again?! I lost patience with this the first time...}
{108}{}{再一次？！我第一次对这个失去了耐心。。。 -- Again?! I lost patience with this the first time...}
#{110}{}{Put your weapon away.}
{110}{}{把你的武器收起来。 -- Put your weapon away.}
#{111}{}{I SAID, put your weapon away!}
{111}{}{我说了，把你的武器收起来！ -- I SAID, put your weapon away!}
#{112}{}{Assassin! Protect Bertolini!}
{112}{}{刺客！保护贝托里尼！ -- Assassin! Protect Bertolini!}
#{113}{}{A thief!}
{113}{}{小偷！ -- A thief!}
#{120}{}{Get out of here, you damn junkie!}
{120}{}{滚开，你这个该死的瘾君子！ -- Get out of here, you damn junkie!}
#{121}{}{Don't even touch the boss. I've got my eye on you.}
{121}{}{别碰老板。我盯上你了。 -- Don't even touch the boss. I've got my eye on you.}
#{122}{}{Be happy. The boss is all the right things about you to all the right people.}
{122}{}{要快乐。老板把你的一切都告诉了所有合适的人。 -- Be happy. The boss is all the right things about you to all the right people.}
#{123}{}{Office hours are over. Come back in the morning.}
{123}{}{办公时间结束了。明早再来。 -- Office hours are over. Come back in the morning.}
#{150}{}{Hey, anyone want to arm wrestle?}
{150}{}{嘿，有人想摔跤吗？ -- Hey, anyone want to arm wrestle?}
#{151}{}{No thanks, Duke. We like our arms attached to our bodies.}
{151}{}{不，谢谢，杜克。我们喜欢把胳膊绑在身上。 -- No thanks, Duke. We like our arms attached to our bodies.}
#{152}{}{Ha-ha-ha! You're damn right to fear me! Back in the ring, everyone did!}
{152}{}{哈哈哈！你害怕我是对的！回到拳击场，每个人都做到了！ -- Ha-ha-ha! You're damn right to fear me! Back in the ring, everyone did!}
#{153}{}{Yeah, yeah, we know, you were a champion.}
{153}{}{是的，是的，我们知道，你是冠军。 -- Yeah, yeah, we know, you were a champion.}
#{154}{}{Champion my ass, motherfucker! I was KING!}
{154}{}{打我屁股，混蛋！我是国王！ -- Champion my ass, motherfucker! I was KING!}
#{155}{}{A king, huh? You'd think a king could afford some new teeth.}
{155}{}{一个国王，嗯？你以为国王能买得起新牙。 -- A king, huh? You'd think a king could afford some new teeth.}
#{156}{}{Ha! As if I care about the feeble insults of jealous plebeians.}
{156}{}{哈！好像我在乎嫉妒的平民的软弱侮辱。 -- Ha! As if I care about the feeble insults of jealous plebeians.}
#{157}{}{What did he just call us?}
{157}{}{他刚才叫我们什么？ -- What did he just call us?}
#{158}{}{Read a book, boy. There's no need to be physically AND mentally inferior.}
{158}{}{读一本书，孩子。没有必要在身体和精神上都低人一等。 -- Read a book, boy. There's no need to be physically AND mentally inferior.}
#{159}{}{Hey, Duke. Why'd you leave the ring, again?}
{159}{}{嘿，杜克。你为什么又把戒指留下？ -- Hey, Duke. Why'd you leave the ring, again?}
#{160}{}{...never mind that. Politics, that's all. The downfall of all kings.}
{160}{}{……没关系。政治，仅此而已。所有国王的垮台。 -- ...never mind that. Politics, that's all. The downfall of all kings.}
#{161}{}{They used you, Duke. Like all the others.}
{161}{}{他们利用了你，杜克。像其他人一样。 -- They used you, Duke. Like all the others.}
#{162}{}{What did you just say?! You want me to crush your skull?}
{162}{}{你刚才说什么？！你想让我压碎你的脑袋？ -- What did you just say?! You want me to crush your skull?}
#{163}{}{Woah, what did I say?}
{163}{}{哇，我说什么了？ -- Woah, what did I say?}
#{164}{}{Watch your tongue, boy, or someone may someday make you eat it.}
{164}{}{小心你的舌头，孩子，否则总有一天会有人让你吃的。 -- Watch your tongue, boy, or someone may someday make you eat it.}
#{165}{}{Woah, I'm sorry, man. Respect. Look... Let's just calm down and start over, okay?}
{165}{}{喔，对不起，伙计。尊重。看。。。让我们冷静下来重新开始，好吗？ -- Woah, I'm sorry, man. Respect. Look... Let's just calm down and start over, okay?}
#{166}{}{ }
{166}{}{  --  }
#{167}{}{ }
{167}{}{  --  }
#{168}{}{ }
{168}{}{  --  }
#{169}{}{ }
{169}{}{  --  }
