#{100}{}{You see the stagecoach guard.}
{100}{}{你看到驿站马车守卫了。 -- You see the stagecoach guard.}
#{101}{}{Before you is the stagecoach guard.}
{101}{}{在你前面是驿站马车守卫。 -- Before you is the stagecoach guard.}
#{105}{}{Hey, get me a drink!}
{105}{}{嘿，给我拿杯喝的！ -- Hey, get me a drink!}
#{106}{}{Hey, what's taking so... Oh, I thought you were the waiter.}
{106}{}{嘿，怎么这么。。。哦，我以为你是服务员。 -- Hey, what's taking so... Oh, I thought you were the waiter.}
#{107}{}{If you're looking for friends, you came to the wrong place.}
{107}{}{如果你在找朋友，你来错地方了。 -- If you're looking for friends, you came to the wrong place.}
#{108}{}{If this is about a job, talk to Tuco.}
{108}{}{如果这是关于一份工作的话，跟图科谈谈。 -- If this is about a job, talk to Tuco.}
#{109}{}{I'm just the guard. Talk to Tuco.}
{109}{}{我只是个警卫。和图科谈谈。 -- I'm just the guard. Talk to Tuco.}
#{110}{}{Unless you're selling whores and booze, keep walking.}
{110}{}{除非你在卖妓女和酒，否则继续走。 -- Unless you're selling whores and booze, keep walking.}
#{111}{}{Who are you?}
{111}{}{你是谁？ -- Who are you?}
#{112}{}{What are you doing here?}
{112}{}{你在这里干什么？ -- What are you doing here?}
#{113}{}{Maybe I do have whores and booze. Who's buying?}
{113}{}{也许我真的有妓女和酒鬼。谁在买？ -- Maybe I do have whores and booze. Who's buying?}
#{114}{}{You're that unlucky guards of "Nevada Express", right?}
{114}{}{你是“内华达快车”那个倒霉的守卫，对吧？ -- You're that unlucky guards of "Nevada Express", right?}
#{115}{}{Then we have nothing to talk about.}
{115}{}{那我们就没什么好谈的了。 -- Then we have nothing to talk about.}
#{116}{}{Bye.}
{116}{}{再见。 -- Bye.}
#{120}{}{Customers, obviously! Why?}
{120}{}{显然是顾客！为什么？ -- Customers, obviously! Why?}
#{121}{}{Tuco put us on "leave" after the last clusterfuck of a job. Says he wants us at our best or not at all. But he says we'll get our jobs back once our nerves settle down.}
{121}{}{在最后一堆工作之后，图科让我们“休假”。他说他想让我们处于最佳状态，或者根本不想。但他说，一旦我们的神经安定下来，我们就会重新找到工作。 -- Tuco put us on "leave" after the last clusterfuck of a job. Says he wants us at our best or not at all. But he says we'll get our jobs back once our nerves settle down.}
#{122}{}{Uh, we made good money working for the Nevada Express. Why?}
{122}{}{呃，我们在内华达快递公司工作赚了不少钱。为什么？ -- Uh, we made good money working for the Nevada Express. Why?}
#{123}{}{Ah, damn... People are already talking about it, huh? Christ, you'd think it wouldn't be so hard to stay hidden in such a big city...}
{123}{}{啊，该死。。。人们已经在谈论它了，嗯？天哪，你会觉得躲在这么大的城市里没那么难。。。 -- Ah, damn... People are already talking about it, huh? Christ, you'd think it wouldn't be so hard to stay hidden in such a big city...}
#{124}{}{So it's you. I want to know about the raided bus.}
{124}{}{原来是你。我想知道被突袭的巴士。 -- So it's you. I want to know about the raided bus.}
#{125}{}{Oh, just bugger off, alright? I'm trying to forget about that shit, not dredge it up again.}
{125}{}{哦，走开，好吗？我只是想忘掉那些狗屎，不要再把它挖出来。 -- Oh, just bugger off, alright? I'm trying to forget about that shit, not dredge it up again.}
#{126}{}{Sorry, but you don't have a choice. I'm investigating on Tuco's orders.}
{126}{}{对不起，你别无选择。我在调查图科的命令。 -- Sorry, but you don't have a choice. I'm investigating on Tuco's orders.}
#{127}{}{What? [they look at each other] Uh... Sure, whatever. But, you know, I wouldn't dig into this if I were you. These bikers, they're dangerous. They're not good enemies to have.}
{127}{}{什么？[他们看着对方]呃。。。当然，随便了。但是，你知道，如果我是你，我就不会深究这个问题。这些摩托车手，他们很危险。他们不是好敌人。 -- What? [they look at each other] Uh... Sure, whatever. But, you know, I wouldn't dig into this if I were you. These bikers, they're dangerous. They're not good enemies to have.}
#{128}{}{Okay, give me the details.}
{128}{}{好的，告诉我细节。 -- Okay, give me the details.}
#{129}{}{We were north of Lovelock when it happened. We were driving on the highway, as usual, when those bikers ambushed us at the turn. We were going so fast, that by the time we could stop the bus, they were shooting at us from all sides. They destroyed the robot immediately, and didn't take much longer for the rest of us.}
{129}{}{事情发生时我们在洛夫洛克北部。我们像往常一样在高速公路上开车，这时那些骑自行车的人在转弯处伏击了我们。我们走得太快了，等我们停下公共汽车时，他们正从四面八方向我们射击。他们立刻摧毁了机器人，我们其他人也没花太多时间。 -- We were north of Lovelock when it happened. We were driving on the highway, as usual, when those bikers ambushed us at the turn. We were going so fast, that by the time we could stop the bus, they were shooting at us from all sides. They destroyed the robot immediately, and didn't take much longer for the rest of us.}
#{130}{}{How'd they manage to destroy the robot?}
{130}{}{他们是怎么摧毁机器人的？ -- How'd they manage to destroy the robot?}
#{131}{}{Can you show me where the raid took place?}
{131}{}{你能告诉我突袭发生在哪里吗？ -- Can you show me where the raid took place?}
#{132}{}{Why didn't you fight back?}
{132}{}{你为什么不反击？ -- Why didn't you fight back?}
#{133}{}{How did you survive?}
{133}{}{你怎么活下来的？ -- How did you survive?}
#{134}{}{That's enough for now.}
{134}{}{现在已经够了。 -- That's enough for now.}
#{135}{}{They had energy weapons. They probably got them from military bases.}
{135}{}{他们有能量武器。他们可能是从军事基地弄来的。 -- They had energy weapons. They probably got them from military bases.}
#{136}{}{Hey, I can't tell you that! That's classified! If Tuco trusts you, then maybe he'll give you the coordinates.}
{136}{}{嘿，我不能告诉你！那是机密！如果图科相信你，也许他会给你坐标。 -- Hey, I can't tell you that! That's classified! If Tuco trusts you, then maybe he'll give you the coordinates.}
#{137}{}{No one expected this from the bikers. We've never fought each other before. Something's probably got them desperate if they're resorting to this.}
{137}{}{没人料到摩托车手会这样。我们以前从没打过架。如果他们这样做的话，他们可能会绝望。 -- No one expected this from the bikers. We've never fought each other before. Something's probably got them desperate if they're resorting to this.}
#{138}{}{They took everything we had and let us go. They wanted us to tell everyone in Reno what happened, can you believe that? Bastards! We got picked up by a rescue patrol after about a day.}
{138}{}{他们拿走了我们所有的一切，让我们走了。他们要我们告诉雷诺的每个人发生了什么，你相信吗？混蛋！大约一天后我们被救援巡逻队接走了。 -- They took everything we had and let us go. They wanted us to tell everyone in Reno what happened, can you believe that? Bastards! We got picked up by a rescue patrol after about a day.}
#{139}{}{You're lying!}
{139}{}{你在撒谎！ -- You're lying!}
#{140}{}{What the fuck?! [he stands up] You want to talk shit, motherfucker?! I'll kick your ass right out onto the street!}
{140}{}{卧槽？！[他站起来]你想说废话吗，混蛋？！我要把你踢到街上！ -- What the fuck?! [he stands up] You want to talk shit, motherfucker?! I'll kick your ass right out onto the street!}
#{141}{}{You should be very careful what you say next. I have proof - the records from robot.}
{141}{}{你下一步说话要小心。我有证据-机器人的记录。 -- You should be very careful what you say next. I have proof - the records from robot.}
#{142}{}{Don't take it personally, I just wanted to make sure...}
{142}{}{别当真，我只是想确定。。。 -- Don't take it personally, I just wanted to make sure...}
#{143}{}{I know you attacked the bus yourselves.}
{143}{}{我知道你自己袭击了公共汽车。 -- I know you attacked the bus yourselves.}
#{144}{}{What do you know, then? Get away from me!}
{144}{}{那你知道什么？离我远点！ -- What do you know, then? Get away from me!}
#{145}{}{Okay, okay...}
{145}{}{好吧，好吧。。。 -- Okay, okay...}
#{146}{}{You what? Fuck! We were so careful... [he leans in close] So what's the plan now, huh? What makes you think we won't kill you? What's one more body, huh?}
{146}{}{你什么？性交！我们很小心。。。[他靠得很近]那现在有什么计划？你凭什么认为我们不会杀你？还有一具尸体是什么？ -- You what? Fuck! We were so careful... [he leans in close] So what's the plan now, huh? What makes you think we won't kill you? What's one more body, huh?}
#{147}{}{Right here, in front of everybody? I don't think so.}
{147}{}{就在这里，在大家面前？我不这么认为。 -- Right here, in front of everybody? I don't think so.}
#{148}{}{Damn it... Alright, how about we buy that records off you? 2000 dollars - that's all we've got. It's more than you'll make from Tuco, believe me.}
{148}{}{该死的。。。好吧，我们从你这里买唱片怎么样？2000美元-我们只有这些。相信我，这比你从图科赚的还多。 -- Damn it... Alright, how about we buy that records off you? 2000 dollars - that's all we've got. It's more than you'll make from Tuco, believe me.}
#{149}{}{First, tell me why you did it.}
{149}{}{首先，告诉我你为什么这么做。 -- First, tell me why you did it.}
#{150}{}{It's a deal. Pleasure doing business with you.}
{150}{}{就这么定了。很高兴和你做生意。 -- It's a deal. Pleasure doing business with you.}
#{151}{}{Hmm. I'll think about.}
{151}{}{嗯。我会考虑的。 -- Hmm. I'll think about.}
#{152}{}{Be smart about this. When you come to the right decision, I'll be here.}
{152}{}{聪明点。当你做出正确的决定时，我会在这里。 -- Be smart about this. When you come to the right decision, I'll be here.}
#{153}{}{Uh-huh.}
{153}{}{啊哈。 -- Uh-huh.}
#{154}{}{[He gives you the money, then puts the holodisk under the leg of his chair and jumps down on it, crushing it] That could have been you, you know. Be happy you took the smart option.}
{154}{}{[他把钱给了你，然后把全息光盘放在椅子腿下，跳下来，压碎了它]你知道，那可能是你。很高兴你做出了明智的选择。 -- [He gives you the money, then puts the holodisk under the leg of his chair and jumps down on it, crushing it] That could have been you, you know. Be happy you took the smart option.}
#{155}{}{Don't go looking for trouble. That could have been you, too.}
{155}{}{别找麻烦了。那也可能是你。 -- Don't go looking for trouble. That could have been you, too.}
#{156}{}{Yeah, yeah, whatever you say. I'm just here for the money.}
{156}{}{是的，是的，随你怎么说。我只是为了钱来的。 -- Yeah, yeah, whatever you say. I'm just here for the money.}
#{157}{}{What do you care? Ah, hell... We were old paying old debts. We used to be mercenaries, and one of our old bosses gave the order to kill one of the passengers. We couldn't refuse - they'd have killed us.}
{157}{}{你在乎什么？啊，见鬼。。。我们老去还旧债了。我们曾经是雇佣兵，我们的一个老老板下令杀死一名乘客。我们不能拒绝-他们会杀了我们的。 -- What do you care? Ah, hell... We were old paying old debts. We used to be mercenaries, and one of our old bosses gave the order to kill one of the passengers. We couldn't refuse - they'd have killed us.}
#{158}{}{Who did you have to kill?}
{158}{}{你要杀谁？ -- Who did you have to kill?}
#{159}{}{Local businessman. He was coming back from Salt Lake City to arrange regular shipments of Nuka-Cola. Some people here weren't happy about it... You've got to watch your ass when you do business in Reno.}
{159}{}{当地商人。他从盐湖城回来，安排定期运送努卡可乐。有些人对此不满意。。。你在里诺做生意时要小心。 -- Local businessman. He was coming back from Salt Lake City to arrange regular shipments of Nuka-Cola. Some people here weren't happy about it... You've got to watch your ass when you do business in Reno.}
#{160}{}{Who wanted him killed?}
{160}{}{谁想杀了他？ -- Who wanted him killed?}
#{161}{}{Are you crazy? I can't tell you that! It'd get me killed... You, too. Of course, I can't go back to the Nevada Express now. And I wanted to get out of the mercenary business...}
{161}{}{你疯了吗？我不能告诉你！会让我送命的。。。你也是。当然，我现在不能回内华达快车了。我想退出雇佣兵行业。。。 -- Are you crazy? I can't tell you that! It'd get me killed... You, too. Of course, I can't go back to the Nevada Express now. And I wanted to get out of the mercenary business...}
#{170}{}{Thanks for not giving us away. It was the right decision.}
{170}{}{谢谢你没有把我们送走。这是正确的决定。 -- Thanks for not giving us away. It was the right decision.}
#{171}{}{Not a smart choice. I wouldn't stick around if I were you. People like you tend to have accidents around here.}
{171}{}{不是明智的选择。如果我是你，我就不会留下来了。像你这样的人在这里容易出事故。 -- Not a smart choice. I wouldn't stick around if I were you. People like you tend to have accidents around here.}
#{172}{}{Well? Have you decided yet?}
{172}{}{好？你决定了吗？ -- Well? Have you decided yet?}
#{1142}{}{Don't take it personally, I just wanted to make sure...}
{1142}{}{别当真，我只是想确定。。。 -- Don't take it personally, I just wanted to make sure...}
#{1154}{}{[He gives you the money, then puts the holodisk under the leg of his chair and jumps down on it, crushing it] That could have been you, you know. Be happy you took the smart option.}
{1154}{}{[他把钱给了你，然后把全息光盘放在椅子腿下，跳下来，压碎了它]你知道，那可能是你。很高兴你做出了明智的选择。 -- [He gives you the money, then puts the holodisk under the leg of his chair and jumps down on it, crushing it] That could have been you, you know. Be happy you took the smart option.}
#{1170}{}{Thanks for not giving us away. It was the right decision.}
{1170}{}{谢谢你没有把我们送走。这是正确的决定。 -- Thanks for not giving us away. It was the right decision.}
