#{100}{}{You see the administrator.}
{100}{}{你去见管理员。 -- You see the administrator.}
#{101}{}{You see a stern-faced manager. She has a clear answer to everything.}
{101}{}{你看到一个表情严肃的经理。她对一切都有明确的答案。 -- You see a stern-faced manager. She has a clear answer to everything.}
#{102}{}{I'm here for business, not chitchat. If you don't have anything important to say, then leave.}
{102}{}{我是来办事的，不是来闲聊的。如果你没有什么重要的事情要说，那就离开。 -- I'm here for business, not chitchat. If you don't have anything important to say, then leave.}
#{103}{}{Are you deaf or just simple? For as long as you work for Mr. Luciano, you will answer when I speak to you.}
{103}{}{你是聋了还是很单纯？只要你为卢西亚诺先生工作，我跟你说话的时候你就会回答。 -- Are you deaf or just simple? For as long as you work for Mr. Luciano, you will answer when I speak to you.}
#{104}{}{Without Oliver, it'll be harsh times for the ranch. But we've prepared for this.}
{104}{}{没有奥利弗，牧场的日子会很艰难。但我们已经准备好了。 -- Without Oliver, it'll be harsh times for the ranch. But we've prepared for this.}
#{110}{}{I'm guessing this isn't the helpdesk. What do you do here?}
{110}{}{我猜这不是服务台。你在这里做什么？ -- I'm guessing this isn't the helpdesk. What do you do here?}
#{111}{}{Well then, I'll just leave.}
{111}{}{好吧，那我就走。 -- Well then, I'll just leave.}
#{112}{}{I handle the day-to-day administration, paperwork, and other business that Mr. Luciano does not have time for. In practice, that means I handle all negotiations with our usual traders and vendors. Contracts, payments, everything. As you can imagine, that's a lot of work, I would *really* like to get back to it.}
{112}{}{我负责卢西亚诺先生没有时间处理的日常行政、文书工作和其他事务。在实践中，这意味着我处理所有与我们通常的贸易商和供应商的谈判。合同，付款，一切。你可以想象，这是一个很大的工作，我会*真的*想回到它。 -- I handle the day-to-day administration, paperwork, and other business that Mr. Luciano does not have time for. In practice, that means I handle all negotiations with our usual traders and vendors. Contracts, payments, everything. As you can imagine, that's a lot of work, I would *really* like to get back to it.}
#{113}{}{What if I would help you? Maybe I'd make a great negotiator, myself.}
{113}{}{如果我能帮你怎么办？也许我自己会成为一个很好的谈判者。 -- What if I would help you? Maybe I'd make a great negotiator, myself.}
#{114}{}{Hmm. [she raises one eyebrow] Maybe you could... You understand there's more to the market than just supply and demand, right?}
{114}{}{嗯[她扬起眉毛]也许你可以。。。你知道市场不仅仅是供求关系，对吧？ -- Hmm. [she raises one eyebrow] Maybe you could... You understand there's more to the market than just supply and demand, right?}
#{115}{}{Yes, and right now, the Reno market is in a bad state.}
{115}{}{是的，现在雷诺的市场状况很糟糕。 -- Yes, and right now, the Reno market is in a bad state.}
#{116}{}{Reno was a great place to do business, once. But then the businesses went to war, followed by the criminals. What we have today doesn't even compare to the old times.}
{116}{}{雷诺曾经是做生意的好地方。但是后来企业开战了，接着是罪犯。我们今天所拥有的甚至比不上旧时代。 -- Reno was a great place to do business, once. But then the businesses went to war, followed by the criminals. What we have today doesn't even compare to the old times.}
#{117}{}{Before the bombs, you mean?}
{117}{}{你是说在炸弹之前？ -- Before the bombs, you mean?}
#{118}{}{No, no. [she waves her hand] I'm talking about the "Golden Age" of Reno. It wasn't so long ago... But that's not the point. I need information. Are you interested?}
{118}{}{不，不[她挥挥手]我说的是雷诺的“黄金时代”。不久前。。。但这不是重点。我需要信息。你有兴趣吗？ -- No, no. [she waves her hand] I'm talking about the "Golden Age" of Reno. It wasn't so long ago... But that's not the point. I need information. Are you interested?}
#{119}{}{What's the job?}
{119}{}{什么工作？ -- What's the job?}
#{120}{}{[She sighs in exasperation] Whatever sort of trader you are, we're not looking for new contracts. We're already selling off all of our product, except for that which we keep for ourselves.}
{120}{}{[她气愤地叹了口气]不管你是哪种交易员，我们都不会寻找新的合约。我们已经把所有的产品都卖光了，除了留给自己的。 -- [She sighs in exasperation] Whatever sort of trader you are, we're not looking for new contracts. We're already selling off all of our product, except for that which we keep for ourselves.}
#{121}{}{Find out where Thompson and Stryker are getting their food supply. It's almost certainly from vendors that work with us, but we'll pay 300 bucks for details.}
{121}{}{找出汤普森和史崔克的食物来源。这几乎可以肯定是来自与我们合作的供应商，但我们将支付300美元的细节。 -- Find out where Thompson and Stryker are getting their food supply. It's almost certainly from vendors that work with us, but we'll pay 300 bucks for details.}
#{122}{}{ And I'll recommend you to Mr. Luciano, too, if you want to work for him.}
{122}{}{如果你想为卢西亚诺先生工作，我也会把你推荐给他。 --  And I'll recommend you to Mr. Luciano, too, if you want to work for him.}
#{123}{}{Sounds reasonable. I'll do it.}
{123}{}{听起来很合理。我会的。 -- Sounds reasonable. I'll do it.}
#{124}{}{I don't think I can do it.}
{124}{}{我想我做不到。 -- I don't think I can do it.}
#{125}{}{Good. Hurry up and let me get back to work.}
{125}{}{很好。快点，让我回去工作。 -- Good. Hurry up and let me get back to work.}
#{126}{}{Fine.}
{126}{}{好的。 -- Fine.}
#{127}{}{You'll be paid when you bring us the information. Until then, let me concentrate on my work.}
{127}{}{当你给我们提供信息时，你会得到报酬的。在那之前，让我专心工作。 -- You'll be paid when you bring us the information. Until then, let me concentrate on my work.}
#{128}{}{Why can't you find this information yourself?}
{128}{}{为什么你自己找不到这些信息？ -- Why can't you find this information yourself?}
#{129}{}{It's none of your concern, but most businesses in Reno keep their deals secret. We can't just ask who's selling to whom.}
{129}{}{这不关你的事，但雷诺的大多数企业都对交易保密。我们不能只问谁卖给谁。 -- It's none of your concern, but most businesses in Reno keep their deals secret. We can't just ask who's selling to whom.}
#{140}{}{I, uh, overheard a conversation in a restaurant. They say something's wrong with your meat!}
{140}{}{一、 呃，无意中听到一个餐馆里的谈话。他们说你的肉有问题！ -- I, uh, overheard a conversation in a restaurant. They say something's wrong with your meat!}
#{141}{}{Tch! Do you honestly think I don't know about this already, or are you just trying to piss me off? I'm sure it's baseless rumors from either the restaurant owner or our political enemies. Too bad Oliver now thinks there's a problem on the ranch. Or maybe he doesn't think that, and he just wants an excuse to discipline us. Either way, we already got a good beating.}
{141}{}{天哪！你真的以为我还不知道这件事，还是你只是想惹我生气？我敢肯定这是餐馆老板或政敌的毫无根据的谣言。可惜奥利弗现在认为牧场出了问题。或者他不这么认为，他只是想找个借口来惩罚我们。不管怎样，我们已经被打败了。 -- Tch! Do you honestly think I don't know about this already, or are you just trying to piss me off? I'm sure it's baseless rumors from either the restaurant owner or our political enemies. Too bad Oliver now thinks there's a problem on the ranch. Or maybe he doesn't think that, and he just wants an excuse to discipline us. Either way, we already got a good beating.}
#{142}{}{Hmm, shady business. Well then, see you around.}
{142}{}{嗯，阴暗的生意。那么，回头见。 -- Hmm, shady business. Well then, see you around.}
#{150}{}{I have a list of Thompson and Stryker's transactions. It should contain the information you need.}
{150}{}{我有汤普森和史崔克的交易清单。它应该包含你需要的信息。 -- I have a list of Thompson and Stryker's transactions. It should contain the information you need.}
#{151}{}{Well don't waste my time, give it to me!}
{151}{}{别浪费我的时间，给我！ -- Well don't waste my time, give it to me!}
#{152}{}{[Hand it over.]}
{152}{}{[交出来] -- [Hand it over.]}
#{153}{}{Hmm... Dates, suppliers, locations, transactions... I'm impressed. I didn't think gangsters had the brainpower for such meticulous record-keeping. Good work. Here's 300 dollars, as we agreed. If you're looking for more work, I'll put in a good word with Mr. Luciano.}
{153}{}{隐马尔可夫模型。。。日期，供应商，地点，交易。。。我印象深刻。我没想到黑帮有那么大的脑力来做如此细致的记录。干得好。这是我们说好的300美元。如果你想找更多的工作，我会和卢西亚诺先生说句好话。 -- Hmm... Dates, suppliers, locations, transactions... I'm impressed. I didn't think gangsters had the brainpower for such meticulous record-keeping. Good work. Here's 300 dollars, as we agreed. If you're looking for more work, I'll put in a good word with Mr. Luciano.}
#{154}{}{[Next]}
{154}{}{[下一步] -- [Next]}
#{155}{}{I have another proposition for you. According to this data, both gangs get some of their food from local businessmen and caravans. I don't know anything about these suppliers - find out who they are and why they're so devoted to these... Revolutionaries.}
{155}{}{我有另一个建议给你。根据这些数据，这两个团伙都从当地商人和商队那里得到了一些食物。我对这些供应商一无所知-找出他们是谁，为什么他们如此热衷于这些。。。革命者。 -- I have another proposition for you. According to this data, both gangs get some of their food from local businessmen and caravans. I don't know anything about these suppliers - find out who they are and why they're so devoted to these... Revolutionaries.}
#{1140}{}{I, uh, overheard a conversation in a restaurant. They say something's wrong with your meat!}
{1140}{}{一、 呃，无意中听到一个餐馆里的谈话。他们说你的肉有问题！ -- I, uh, overheard a conversation in a restaurant. They say something's wrong with your meat!}
