#{100}{}{You see the chief.}
{100}{}{你去见局长。 -- You see the chief.}
#{101}{}{You see the head of the food convoy.}
{101}{}{你看到食品运输队的队长了。 -- You see the head of the food convoy.}
#{102}{}{Huh? What? Get lost, I don't have time for you.}
{102}{}{呵呵？什么？滚开，我没时间陪你。 -- Huh? What? Get lost, I don't have time for you.}
#{103}{}{It's okay. Guard the cargo, I need to work out some details with my partner.}
{103}{}{没事的。守卫货物，我需要和我的搭档解决一些细节。 -- It's okay. Guard the cargo, I need to work out some details with my partner.}
#{104}{}{Hey, what are you doing? Step away from the carriage!}
{104}{}{嘿，你在干什么？离马车远点！ -- Hey, what are you doing? Step away from the carriage!}
