#{100}{}{You see a guard dog.}
{100}{}{你看到一只看门狗。 -- You see a guard dog.}
#{101}{}{You see a rather aggressive guard dog.}
{101}{}{你看到一只相当好斗的看门狗。 -- You see a rather aggressive guard dog.}
#{102}{}{Woof!!!}
{102}{}{呜呜！！！ -- Woof!!!}
#{103}{}{Woof! Woof! Woof!}
{103}{}{呜呜！呜呜！呜呜！ -- Woof! Woof! Woof!}
#{104}{}{::growls::}
{104}{}{●咆哮声： -- ::growls::}
#{105}{}{Grrrr...}
{105}{}{Grrrr。。。 -- Grrrr...}
