#{100}{}{You can not take pictures during combat.}
{100}{}{你不能在战斗中拍照。 -- You can not take pictures during combat.}
#{101}{}{This device is usually operated with one's hands.}
{101}{}{这个装置通常是用手操作的。 -- This device is usually operated with one's hands.}
#{102}{}{You don't see anything worth photographing here.}
{102}{}{你在这里看不到任何值得拍照的东西。 -- You don't see anything worth photographing here.}
#{103}{}{You already have a photo of this.}
{103}{}{你已经有这张照片了。 -- You already have a photo of this.}
#{104}{}{You took a photo of one of the rooms. Stryker will be pleased.}
{104}{}{你给其中一个房间拍了张照片。史崔克会很高兴的。 -- You took a photo of one of the rooms. Stryker will be pleased.}
#{105}{}{This place won't be of interest to Stryker.}
{105}{}{史崔克对这个地方不感兴趣。 -- This place won't be of interest to Stryker.}
#{106}{}{You don't have enough film.}
{106}{}{你没有足够的胶卷。 -- You don't have enough film.}
