#{100}{}{}
{100}{}{ -- }
#{101}{}{This generator supplies electricity to the entire bunker.}
{101}{}{这台发电机为整个地堡供电。 -- This generator supplies electricity to the entire bunker.}
#{102}{}{The generator fails. The light in the bunker blacks out.}
{102}{}{发电机坏了。地堡里的灯熄灭了。 -- The generator fails. The light in the bunker blacks out.}
#{103}{}{You can't figure out how to turn off the generator without hurting yourself.}
{103}{}{你不知道怎样关掉发电机而不伤到自己。 -- You can't figure out how to turn off the generator without hurting yourself.}
#{104}{}{This is the bunker's power source. Turning it off will disable all electronics in the bunker.}
{104}{}{这是地堡的电源。关掉它会使地堡里的所有电子设备失效。 -- This is the bunker's power source. Turning it off will disable all electronics in the bunker.}
