#{100}{}{}
{100}{}{ -- }
#{110}{}{I wonder how they'd be in a salad...}
{110}{}{我想知道他们怎么会在沙拉里。。。 -- I wonder how they'd be in a salad...}
#{111}{}{Better exterminate them before they start talking!}
{111}{}{最好在他们开口说话之前消灭他们！ -- Better exterminate them before they start talking!}
#{112}{}{Note to self, only weed the ones with teeth...}
{112}{}{注意自己，只给有牙齿的除草。。。 -- Note to self, only weed the ones with teeth...}
#{113}{}{One less mouth.}
{113}{}{少了一张嘴。 -- One less mouth.}
#{114}{}{Who crossed a dandelion with a deathclaw?}
{114}{}{谁用死爪穿过蒲公英？ -- Who crossed a dandelion with a deathclaw?}
#{115}{}{Rooting out weeds? Well, at least it's better than killing rats with a shovel.}
{115}{}{铲除杂草？好吧，至少比用铲子打死老鼠好。 -- Rooting out weeds? Well, at least it's better than killing rats with a shovel.}
#{116}{}{Kill a plant, save a fly!}
{116}{}{杀一株植物，救一只苍蝇！ -- Kill a plant, save a fly!}
#{117}{}{Was that mutated hemp?}
{117}{}{那是变异大麻吗？ -- Was that mutated hemp?}
#{118}{}{How do you like that?}
{118}{}{你觉得怎么样？ -- How do you like that?}
#{119}{}{That should do it!}
{119}{}{That should do it! -- That should do it!}
#{120}{}{Boy, was that boring, but I did it!}
{120}{}{天哪，真无聊，但我做到了！ -- Boy, was that boring, but I did it!}
#{121}{}{Boy, was that boring, but I did it!}
{121}{}{天哪，真无聊，但我做到了！ -- Boy, was that boring, but I did it!}
#{122}{}{You've killed all the killer plants in this field.}
{122}{}{你杀死了这片地里所有的杀手植物。 -- You've killed all the killer plants in this field.}
#{150}{}{You've killed }
{150}{}{你杀了我 -- You've killed }
#{151}{}{ out of 5 plants.}
{151}{}{五种植物中的一种。 --  out of 5 plants.}
