#{100}{}{You see a spectator.}
{100}{}{你看到一个观众。 -- You see a spectator.}
#{101}{}{You see a drunk and high raider, who only needs this spectacle to feel complete.}
{101}{}{你看到的是一个酒鬼和狂妄的掠夺者，他只需要这个场面就可以感觉完整。 -- You see a drunk and high raider, who only needs this spectacle to feel complete.}
#{102}{}{Dammit!}
{102}{}{该死！ -- Dammit!}
#{103}{}{What, can't wait to die or something?!}
{103}{}{什么，等不及要死了吗？！ -- What, can't wait to die or something?!}
#{104}{}{Come on, you people!}
{104}{}{快点，你们这些人！ -- Come on, you people!}
#{105}{}{A-a-ah!}
{105}{}{啊啊啊！ -- A-a-ah!}
#{106}{}{Ah, pain is beautiful!}
{106}{}{啊，痛苦是美丽的！ -- Ah, pain is beautiful!}
#{107}{}{Pain sweet pain!}
{107}{}{痛苦甜蜜的痛苦！ -- Pain sweet pain!}
#{108}{}{Goddammit!}
{108}{}{他妈的！ -- Goddammit!}
#{109}{}{You little...}
{109}{}{你这个小。。。 -- You little...}
#{110}{}{Guess what I did with your mom!}
{110}{}{猜猜我对你妈妈做了什么！ -- Guess what I did with your mom!}
#{111}{}{God fucking...}
{111}{}{他妈的。。。 -- God fucking...}
#{112}{}{Wait till I get to you...}
{112}{}{等我找到你。。。 -- Wait till I get to you...}
#{113}{}{Just you wait!!!}
{113}{}{你等一下！！！ -- Just you wait!!!}
#{114}{}{Drop that clown!}
{114}{}{放下那个小丑！ -- Drop that clown!}
#{115}{}{Oh, come on!}
{115}{}{哦，来吧！ -- Oh, come on!}
#{116}{}{Waste this punk!}
{116}{}{浪费这个混蛋！ -- Waste this punk!}
#{117}{}{* yells *}
{117}{}{*大叫* -- * yells *}
#{118}{}{Move away from it!}
{118}{}{走开！ -- Move away from it!}
#{119}{}{Punch him in the ear! In the ear!}
{119}{}{打他的耳朵！在耳朵里！ -- Punch him in the ear! In the ear!}
#{120}{}{Punch him! Right in the jaw!}
{120}{}{打他！正中下巴！ -- Punch him! Right in the jaw!}
#{121}{}{Just look, what is happening!!!}
{121}{}{看看，发生了什么事！！！ -- Just look, what is happening!!!}
#{122}{}{Wow, have you seen that?}
{122}{}{哇，你看到了吗？ -- Wow, have you seen that?}
#{123}{}{This was rough!!!}
{123}{}{这很艰难！！！ -- This was rough!!!}
#{124}{}{* yells *}
{124}{}{*大叫* -- * yells *}
