#{100}{}{You see a redneck.}
{100}{}{你看到一个红脖子。 -- You see a redneck.}
#{101}{}{You see one of the few Provo residents.}
{101}{}{你会看到普罗沃为数不多的居民之一。 -- You see one of the few Provo residents.}
#{102}{}{An outsider!}
{102}{}{一个局外人！ -- An outsider!}
#{103}{}{I'm not in the mood to chat with you}
{103}{}{我没心情和你聊天 -- I'm not in the mood to chat with you}
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
#{}{}{}
{}{}{ -- }
