#{100}{}{You see a generator.}
{100}{}{你看到一个发电机。 -- You see a generator.}
#{101}{}{You see an ordinary generator. Judging from the markings, it's responsible for the station's automatics.}
{101}{}{你看到一个普通的发电机。从标记来看，它负责车站的自动装置。 -- You see an ordinary generator. Judging from the markings, it's responsible for the station's automatics.}
#{102}{}{The generator is in poor condition, but it can be repaired.}
{102}{}{发电机状况很差，但可以修理。 -- The generator is in poor condition, but it can be repaired.}
#{103}{}{Needs repairs}
{103}{}{需要修理 -- Needs repairs}
#{104}{}{ exp. points.}
{104}{}{经验点。 --  exp. points.}
#{105}{}{The generator is in working condition and supplies power to the station.}
{105}{}{发电机处于工作状态，向电站供电。 -- The generator is in working condition and supplies power to the station.}
#{106}{}{No use}
{106}{}{没用 -- No use}
#{107}{}{The generator's running and doesn't need any repairs.}
{107}{}{发电机在运转，不需要修理。 -- The generator's running and doesn't need any repairs.}
#{108}{}{You repair the generator and it begins to produce a humming sound. You gain }
{108}{}{你修理发电机，它开始发出嗡嗡声。你得到了什么 -- You repair the generator and it begins to produce a humming sound. You gain }
#{109}{}{Done}
{109}{}{多恩 -- Done}
#{110}{}{This won't be of any use here. The generator needs repairing.}
{110}{}{这在这里没有任何用处。发电机需要修理。 -- This won't be of any use here. The generator needs repairing.}
#{111}{}{You fail to repair the generator.}
{111}{}{你没修好发电机。 -- You fail to repair the generator.}
#{112}{}{Fail}
{112}{}{失败 -- Fail}
