#{100}{}{It's a switch.}
{100}{}{这是一个开关。 -- It's a switch.}
#{101}{}{You see a light switch. It's in the "on" position.}
{101}{}{你看到一个电灯开关。它在“开”的位置。 -- You see a light switch. It's in the "on" position.}
#{102}{}{You see a light switch. It's in the "off" position.}
{102}{}{你看到一个电灯开关。它在“关闭”位置。 -- You see a light switch. It's in the "off" position.}
#{103}{}{This switch turns the lights on the underground level of the station on or off.}
{103}{}{这个开关打开或关闭车站地下层的灯。 -- This switch turns the lights on the underground level of the station on or off.}
#{110}{}{You switch off the light and the underground level of the station sinks into darkness.}
{110}{}{你关掉灯，车站的地下一层陷入黑暗。 -- You switch off the light and the underground level of the station sinks into darkness.}
#{111}{}{You turn on the light on the underground level of the station.}
{111}{}{你打开车站地下层的灯。 -- You turn on the light on the underground level of the station.}
#{112}{}{Hmm, flipping the switch doesn't appear to have any effect. Maybe the power is out?}
{112}{}{嗯，扳动开关似乎没有任何效果。可能停电了？ -- Hmm, flipping the switch doesn't appear to have any effect. Maybe the power is out?}
#{113}{}{Done}
{113}{}{多恩 -- Done}
#{114}{}{Let there be darkness!}
{114}{}{让黑暗降临吧！ -- Let there be darkness!}
#{115}{}{Let there be light!}
{115}{}{让那里有光！ -- Let there be light!}
#{116}{}{Nothing happens}
{116}{}{什么都没发生 -- Nothing happens}
