#{100}{}{You see a door.}
{100}{}{你看到一扇门。 -- You see a door.}
#{101}{}{An electronic door. Sadly, it will never open without power.}
{101}{}{电子门。可悲的是，它永远不会打开没有权力。 -- An electronic door. Sadly, it will never open without power.}
#{102}{}{An electronic door. Due to unstable power supply, its behavior is unpredictable.}
{102}{}{电子门。由于电源不稳定，其行为是不可预测的。 -- An electronic door. Due to unstable power supply, its behavior is unpredictable.}
#{103}{}{Without power the door won't open}
{103}{}{没有电源，门打不开 -- Without power the door won't open}
#{104}{}{The power supply is unstable, so right now there's not enough power to open the door.}
{104}{}{电源不稳定，所以现在没有足够的电力开门。 -- The power supply is unstable, so right now there's not enough power to open the door.}
#{105}{}{An electronic door. There must be an emergency opening system somewhere.}
{105}{}{电子门。一定有紧急开门系统。 -- An electronic door. There must be an emergency opening system somewhere.}
#{106}{}{Your skills are useless here. Look for an emergency opening system.}
{106}{}{你的技能在这里毫无用处。寻找紧急开启系统。 -- Your skills are useless here. Look for an emergency opening system.}
#{107}{}{Access key is required.}
{107}{}{需要访问密钥。 -- Access key is required.}
#{108}{}{Access key is required, but you don't have one. There must be an emergency opening mechanism.}
{108}{}{需要访问密钥，但您没有。必须有紧急开启机制。 -- Access key is required, but you don't have one. There must be an emergency opening mechanism.}
