#{100}{}{You see the cook.}
{100}{}{你看到厨师了。 -- You see the cook.}
#{101}{}{You see the cook. He cuts, shreds, rubs and scrapes something. All the time.}
{101}{}{你看到厨师了。他切、撕、擦、刮东西。总是。 -- You see the cook. He cuts, shreds, rubs and scrapes something. All the time.}
#{102}{}{Get out!}
{102}{}{走出！ -- Get out!}
#{103}{}{Hey, young man! Staff only! Go on and get out! And close the door behind you! Shoo! Shoo!}
{103}{}{嘿，年轻人！仅限员工！快出去！把门关上！嘘！嘘！ -- Hey, young man! Staff only! Go on and get out! And close the door behind you! Shoo! Shoo!}
#{104}{}{Fine.}
{104}{}{好的。 -- Fine.}
#{1103}{}{Hey, young lady! Staff only! Go on and get out! And close the door behind you! Shoo! Shoo!}
{1103}{}{嘿，小姐！仅限员工！快出去！把门关上！嘘！嘘！ -- Hey, young lady! Staff only! Go on and get out! And close the door behind you! Shoo! Shoo!}
