#{100}{}{You see a City Hall employee.}
{100}{}{你看到一个市政厅的职员。 -- You see a City Hall employee.}
#{101}{}{It's one of the City Hall employees.}
{101}{}{是市政厅的一名员工。 -- It's one of the City Hall employees.}
#{102}{}{I don't deal with such issues.}
{102}{}{我不处理这些问题。 -- I don't deal with such issues.}
#{103}{}{If you have any complains, address it to the doorknob over there.}
{103}{}{如果你有任何抱怨，请到那边的门把手。 -- If you have any complains, address it to the doorknob over there.}
#{110}{}{Dull pencils again.}
{110}{}{又是钝铅笔。 -- Dull pencils again.}
#{111}{}{Is the salary coming soon?}
{111}{}{工资快到了吗？ -- Is the salary coming soon?}
#{112}{}{I will buy myself a bulletproof vest next time I get paid.}
{112}{}{下次领工资时我会给自己买一件防弹背心。 -- I will buy myself a bulletproof vest next time I get paid.}
#{113}{}{What to read? Oh, the tax declaration!}
{113}{}{读什么？哦，纳税申报单！ -- What to read? Oh, the tax declaration!}
#{114}{}{Boring.}
{114}{}{真无聊。 -- Boring.}
#{115}{}{With this data...}
{115}{}{有了这些数据。。。 -- With this data...}
#{116}{}{Well, this is not to me.}
{116}{}{好吧，这不关我的事。 -- Well, this is not to me.}
#{117}{}{I'll never make so much money.}
{117}{}{我再也赚不到这么多钱了。 -- I'll never make so much money.}
#{118}{}{Reports, reports, reports...}
{118}{}{报告，报告，报告。。。 -- Reports, reports, reports...}
#{119}{}{Who to yell at?}
{119}{}{对谁大喊大叫？ -- Who to yell at?}
#{120}{}{Not so perspective, as it seems.}
{120}{}{不像看上去的那样有远见。 -- Not so perspective, as it seems.}
#{121}{}{Another stupid idea.}
{121}{}{又是个愚蠢的主意。 -- Another stupid idea.}
#{122}{}{Junk!}
{122}{}{废旧物品！ -- Junk!}
#{123}{}{Another stupid answer.}
{123}{}{又一个愚蠢的回答。 -- Another stupid answer.}
#{124}{}{When is the planning session?}
{124}{}{计划会议什么时候举行？ -- When is the planning session?}
#{125}{}{When is the launch break?}
{125}{}{发射时间是什么时候？ -- When is the launch break?}
#{126}{}{Is it dinner soon?}
{126}{}{晚饭快到了吗？ -- Is it dinner soon?}
#{127}{}{I want to sleep.}
{127}{}{我想睡觉。 -- I want to sleep.}
#{128}{}{I need to rest.}
{128}{}{我需要休息。 -- I need to rest.}
#{129}{}{My eyes are tired.}
{129}{}{我的眼睛累了。 -- My eyes are tired.}
#{130}{}{Read all this? Fire me.}
{130}{}{读过这些吗？解雇我。 -- Read all this? Fire me.}
#{131}{}{Please, just don't fire me.}
{131}{}{拜托，别解雇我。 -- Please, just don't fire me.}
