#{100}{}{You see: Servant}
{100}{}{你看：仆人 -- You see: Servant}
#{101}{}{You see a servant of Vault City.}
{101}{}{你看到金库城的一个仆人。 -- You see a servant of Vault City.}
#{102}{}{Uh, greetings... Citizen.}
{102}{}{呃，你好。。。公民。 -- Uh, greetings... Citizen.}
#{110}{}{Hey, it's you! Er, I mean... My apologies, citizen, it's good to see you, citizen. Oh, and long live Vault City!}
{110}{}{嘿，是你！呃，我是说。。。很抱歉，公民，很高兴见到你，公民。哦，金库城万岁！ -- Hey, it's you! Er, I mean... My apologies, citizen, it's good to see you, citizen. Oh, and long live Vault City!}
#{111}{}{Who taught you that greeting?}
{111}{}{谁教你这个问候语的？ -- Who taught you that greeting?}
#{112}{}{Enjoyed the trip?}
{112}{}{旅途愉快吗？ -- Enjoyed the trip?}
#{113}{}{Do you like it in the city?}
{113}{}{你喜欢这个城市吗？ -- Do you like it in the city?}
#{114}{}{What do you do around here?}
{114}{}{你在这附近干什么？ -- What do you do around here?}
#{115}{}{Are you treated well?}
{115}{}{你待遇好吗？ -- Are you treated well?}
#{116}{}{What do you think about the citizens?}
{116}{}{你觉得市民怎么样？ -- What do you think about the citizens?}
#{119}{}{See you.}
{119}{}{再见。 -- See you.}
#{120}{}{The head of servants, citizen. We must... [begins count on fingers] ...greet all citizens on sight, praise Vault City, avoid eye contact with all citizens, avoid asking questions, never use anything that citizens use, and... Something else. The head of servants explains to us every morning, how we should behave.}
{120}{}{仆人的首领，公民。我们必须。。。[开始数手指]…向所有市民致意，赞扬金库城市，避免与所有市民目光接触，避免提问，从不使用市民使用的任何东西，以及。。。还有别的。仆人的首领每天早晨都向我们解释，我们该如何行事。 -- The head of servants, citizen. We must... [begins count on fingers] ...greet all citizens on sight, praise Vault City, avoid eye contact with all citizens, avoid asking questions, never use anything that citizens use, and... Something else. The head of servants explains to us every morning, how we should behave.}
#{121}{}{Uh... Not exactly, citizen. We were blindfolded and placed in that prison with the energy doors. It was... Scary. First we were checked by a doctor, then interrogated by the guards. We thought we would go mad. But that's all over, and to be honest, I'm glad I ended up here.}
{121}{}{休斯敦大学。。。不完全是，公民。我们被蒙上眼睛，关在有能量门的监狱里。那是。。。吓人的。首先我们接受了医生的检查，然后被警卫审问。我们以为我们会发疯。但这一切都结束了，说实话，我很高兴我最终来到这里。 -- Uh... Not exactly, citizen. We were blindfolded and placed in that prison with the energy doors. It was... Scary. First we were checked by a doctor, then interrogated by the guards. We thought we would go mad. But that's all over, and to be honest, I'm glad I ended up here.}
#{122}{}{Yes, citizen! We are fed, clothed and healthy. We have a roof over our heads and don't need to fight to survive, like when we were free. Though... The work is hard. Especially after the pills we get each morning. And it's hard to think about not being allowed to leave the city, but... I'm sure I'll get used to it.}
{122}{}{是的，公民！我们衣食无忧，身体健康。我们有自己的屋顶，不需要为了生存而战斗，就像我们自由的时候一样。不过。。。工作很辛苦。尤其是每天早上吃了药之后。很难想象不被允许离开这个城市，但是。。。我相信我会习惯的。 -- Yes, citizen! We are fed, clothed and healthy. We have a roof over our heads and don't need to fight to survive, like when we were free. Though... The work is hard. Especially after the pills we get each morning. And it's hard to think about not being allowed to leave the city, but... I'm sure I'll get used to it.}
#{123}{}{I'm sorting out inventory on these shelves, citizen. The others are taken to work on constructing some sort of a building.}
{123}{}{我在整理这些架子上的存货，市民。其他人被带去建造某种建筑。 -- I'm sorting out inventory on these shelves, citizen. The others are taken to work on constructing some sort of a building.}
#{124}{}{Yes, citizen, but... There are times when I get tired of this endless rules, regulations, forms, pills and injections. I don't know what's in those shots, but afterward I can't think of anything but sitting and quietly working.}
{124}{}{是的，公民，但是。。。有时我厌倦了这种没完没了的规章制度、表格、药片和针剂。我不知道那些照片里是什么，但后来我想不出什么，只能坐着静静地工作。 -- Yes, citizen, but... There are times when I get tired of this endless rules, regulations, forms, pills and injections. I don't know what's in those shots, but afterward I can't think of anything but sitting and quietly working.}
#{125}{}{I... Value... And thank the citizens. They are wonderful people... Citizen. [his eyes make it clear he's lying through his teeth]}
{125}{}{一、 。。。值。。。感谢市民。他们是很棒的人。。。公民。[他的眼睛清楚地表明他在说谎] -- I... Value... And thank the citizens. They are wonderful people... Citizen. [his eyes make it clear he's lying through his teeth]}
#{1102}{}{Er, greetings... Citizen.}
{1102}{}{呃，你好。。。公民。 -- Er, greetings... Citizen.}
#{1110}{}{Hey, it's you! Er, I mean... My apologies, citizen, it's good to see you, citizen. Oh, and long live Vault City!}
{1110}{}{嘿，是你！呃，我是说。。。很抱歉，公民，很高兴见到你，公民。哦，金库城万岁！ -- Hey, it's you! Er, I mean... My apologies, citizen, it's good to see you, citizen. Oh, and long live Vault City!}
#{1120}{}{The head of servants, citizen. We must... [begins count on fingers] ...greet all citizens on sight, praise Vault City, avoid eye contact with all citizens, avoid asking questions, never use anything that citizens use, and... Something else. The head of servants explains to us every morning, how we should behave.}
{1120}{}{仆人的首领，公民。我们必须。。。[开始数手指]…向所有市民致意，赞扬金库城市，避免与所有市民目光接触，避免提问，从不使用市民使用的任何东西，以及。。。还有别的。仆人的首领每天早晨都向我们解释，我们该如何行事。 -- The head of servants, citizen. We must... [begins count on fingers] ...greet all citizens on sight, praise Vault City, avoid eye contact with all citizens, avoid asking questions, never use anything that citizens use, and... Something else. The head of servants explains to us every morning, how we should behave.}
#{1121}{}{Er... Not exactly, citizen. We were blindfolded and placed in that prison with the energy doors. It was... Scary. First we were checked by a doctor, then interrogated by the guards. We thought we would go mad. But that's all over, and to be honest, I'm glad I ended up here.}
{1121}{}{呃。。。不完全是，公民。我们被蒙上眼睛，关在有能量门的监狱里。那是。。。吓人的。首先我们接受了医生的检查，然后被警卫审问。我们以为我们会发疯。但这一切都结束了，说实话，我很高兴我最终来到这里。 -- Er... Not exactly, citizen. We were blindfolded and placed in that prison with the energy doors. It was... Scary. First we were checked by a doctor, then interrogated by the guards. We thought we would go mad. But that's all over, and to be honest, I'm glad I ended up here.}
#{1122}{}{Yes, citizen! We are fed, clothed and healthy. We have a roof over our heads and don't need to fight to survive, like when we were free. Though... The work is hard. Especially after the pills we get each morning. And it's hard to think about not being allowed to leave the city, but... I'm sure I'll get used to it.}
{1122}{}{是的，公民！我们衣食无忧，身体健康。我们有自己的屋顶，不需要为了生存而战斗，就像我们自由的时候一样。不过。。。工作很辛苦。尤其是每天早上吃了药之后。很难想象不被允许离开这个城市，但是。。。我相信我会习惯的。 -- Yes, citizen! We are fed, clothed and healthy. We have a roof over our heads and don't need to fight to survive, like when we were free. Though... The work is hard. Especially after the pills we get each morning. And it's hard to think about not being allowed to leave the city, but... I'm sure I'll get used to it.}
#{1123}{}{I'm sorting out inventory on these shelves, citizen. The others are constructing some sort of building.}
{1123}{}{我在整理这些架子上的存货，市民。其他人正在建造某种建筑。 -- I'm sorting out inventory on these shelves, citizen. The others are constructing some sort of building.}
#{1124}{}{Yes, citizen, but... There are times when I get tired of this endless rules, regulations, forms, pills and injections. I don't know what's in those shots, but afterward I can't think of anything but sitting and quietly working.}
{1124}{}{是的，公民，但是。。。有时我厌倦了这种没完没了的规章制度、表格、药片和针剂。我不知道那些照片里是什么，但后来我想不出什么，只能坐着静静地工作。 -- Yes, citizen, but... There are times when I get tired of this endless rules, regulations, forms, pills and injections. I don't know what's in those shots, but afterward I can't think of anything but sitting and quietly working.}
#{1125}{}{I... Value... And thank the citizens. They are wonderful people... Citizen. [her eyes make it clear she's lying through her teeth]}
{1125}{}{一、 。。。值。。。感谢市民。他们是很棒的人。。。公民。[她的眼睛清楚地表明她在说谎] -- I... Value... And thank the citizens. They are wonderful people... Citizen. [her eyes make it clear she's lying through her teeth]}
