#{100}{}{You see a slave.}
{100}{}{你看到一个奴隶。 -- You see a slave.}
#{101}{}{You see a slave. He is pathetic.}
{101}{}{你看到一个奴隶。他真可怜。 -- You see a slave. He is pathetic.}
#{102}{}{This one has nothing to say to you.}
{102}{}{这个没什么好说的。 -- This one has nothing to say to you.}
#{103}{}{::looks at you with a blank stare::}
{103}{}{●茫然地看着你： -- ::looks at you with a blank stare::}
#{104}{}{You managed to persuade the slave to leave the corral.}
{104}{}{你说服了奴隶离开畜栏。 -- You managed to persuade the slave to leave the corral.}
#{110}{}{I want to lie down. Don't bother me.}
{110}{}{我想躺下。别打扰我。 -- I want to lie down. Don't bother me.}
#{111}{}{No time to lie around, you louts! The slavers are dead. You are free!}
{111}{}{没时间躺着了，你们这些笨蛋！奴隶主死了。你自由了！ -- No time to lie around, you louts! The slavers are dead. You are free!}
#{112}{}{Okay.}
{112}{}{可以。 -- Okay.}
#{113}{}{Uh... Yeah, uh, good news, yes.}
{113}{}{休斯敦大学。。。是的，嗯，好消息，是的。 -- Uh... Yeah, uh, good news, yes.}
#{114}{}{That's news! Hey, did everyone hear that?!! Come on, guys! We are free... }
{114}{}{这是新闻！嘿，大家都听到了吗？！！快点，伙计们！我们自由了。。。 -- That's news! Hey, did everyone hear that?!! Come on, guys! We are free... }
#{115}{}{Hurry up!}
{115}{}{快点！ -- Hurry up!}
#{116}{}{Get your asses moving, herd!}
{116}{}{快走，畜群！ -- Get your asses moving, herd!}
#{117}{}{And why are you so sad?}
{117}{}{你为什么这么伤心？ -- And why are you so sad?}
#{118}{}{Oh, you dimwit! Do you even realize, what have you done!? [grabs his head]}
{118}{}{哦，你这个笨蛋！你知道吗，你做了什么！？[抓住他的头] -- Oh, you dimwit! Do you even realize, what have you done!? [grabs his head]}
#{119}{}{Hey, what's the problem?! You need to get out quickly and go home!}
{119}{}{嘿，怎么了？！你得赶快出去回家！ -- Hey, what's the problem?! You need to get out quickly and go home!}
#{120}{}{To go where? I have no home! Thanks, of course, you did quite a service, but they could give me work with food and water, and now I have to find them myself... You're a moron if you think that you made it better!}
{120}{}{去哪里？我没有家！谢谢，当然，你帮了我不少忙，但是他们可以给我提供食物和水，现在我得自己去找他们。。。如果你认为自己做得更好，你就是个白痴！ -- To go where? I have no home! Thanks, of course, you did quite a service, but they could give me work with food and water, and now I have to find them myself... You're a moron if you think that you made it better!}
#{121}{}{Hmm. What an unexpected reaction. At least the majority is satisfied...}
{121}{}{嗯。真是出乎意料的反应。至少大多数人满意。。。 -- Hmm. What an unexpected reaction. At least the majority is satisfied...}
#{122}{}{[The slave looks around in bewilderment]}
{122}{}{[奴隶困惑地环顾四周] -- [The slave looks around in bewilderment]}
#{123}{}{Hey! Why are you not running? The exit from the corral is opened! You need to get out quickly and go home!}
{123}{}{嘿！你为什么不跑？畜栏的出口打开了！你得赶快出去回家！ -- Hey! Why are you not running? The exit from the corral is opened! You need to get out quickly and go home!}
#{124}{}{Hey! Hurry up! Come on!}
{124}{}{嘿！快点！加油！ -- Hey! Hurry up! Come on!}
#{125}{}{So this is... They all are...}
{125}{}{所以这是。。。他们都是。。。 -- So this is... They all are...}
#{126}{}{Get up, you fool! Now! No time to lose! Forward! Go!!!}
{126}{}{起来，笨蛋！现在！别浪费时间！向前地！去吧！！！ -- Get up, you fool! Now! No time to lose! Forward! Go!!!}
#{150}{}{In this corral you eventually understand, what brahmin feels in the slaughterhouse}
{150}{}{在这个畜栏里，你最终明白了，婆罗门在屠宰场的感受 -- In this corral you eventually understand, what brahmin feels in the slaughterhouse}
#{151}{}{Why did I bet on zero?}
{151}{}{我为什么赌零？ -- Why did I bet on zero?}
#{152}{}{Another day in this hell hole...}
{152}{}{又一天在这个地狱里。。。 -- Another day in this hell hole...}
#{153}{}{Mama used to tell me - don't play in games of chance}
{153}{}{妈妈曾经告诉我-不要玩冒险游戏 -- Mama used to tell me - don't play in games of chance}
#{154}{}{Let me go to casino! Only one bet, and back!}
{154}{}{让我去赌场！只赌一次，然后回来！ -- Let me go to casino! Only one bet, and back!}
#{155}{}{And they said that the real life is in Vegas...}
{155}{}{他们说真正的生活在维加斯。。。 -- And they said that the real life is in Vegas...}
#{156}{}{Let me out!}
{156}{}{放我出去！ -- Let me out!}
#{157}{}{That's the violation of human rights! I will complain!}
{157}{}{这是对人权的侵犯！我会抱怨的！ -- That's the violation of human rights! I will complain!}
#{158}{}{It was cleaner even in the raiders crib...}
{158}{}{即使在袭击者的婴儿床里也很干净。。。 -- It was cleaner even in the raiders crib...}
#{159}{}{And once I had a couple of slaves myself...}
{159}{}{有一次我自己也有几个奴隶。。。 -- And once I had a couple of slaves myself...}
#{160}{}{Freedom! Freedom!!!}
{160}{}{自由！自由！！！ -- Freedom! Freedom!!!}
#{161}{}{A bottle of beer and a cigar - and they can shoot me, for all I care...}
{161}{}{一瓶啤酒和一支雪茄-他们可以开枪打我，我只在乎。。。 -- A bottle of beer and a cigar - and they can shoot me, for all I care...}
#{162}{}{Free us!}
{162}{}{释放我们！ -- Free us!}
#{163}{}{We're not animals! At least I'm...}
{163}{}{我们不是动物！至少我。。。 -- We're not animals! At least I'm...}
#{164}{}{He had marked cards! I should have won!}
{164}{}{他在卡片上做了记号！我应该赢的！ -- He had marked cards! I should have won!}
#{165}{}{We live in a country of freedom! Let me out!}
{165}{}{我们生活在一个自由的国度！放我出去！ -- We live in a country of freedom! Let me out!}
#{166}{}{I can't be here any more!}
{166}{}{我不能再在这里了！ -- I can't be here any more!}
#{167}{}{Even my wife didn't feed me that bad!}
{167}{}{连我老婆也没喂我那么多！ -- Even my wife didn't feed me that bad!}
#{168}{}{I require a normal toilet!}
{168}{}{我需要一个普通的厕所！ -- I require a normal toilet!}
#{169}{}{Ahhh! ::bangs his head against the ground::}
{169}{}{啊哈！●头撞在地上： -- Ahhh! ::bangs his head against the ground::}
#{170}{}{How was it... "You will die anyway"?}
{170}{}{怎么样……”你会死吗？ -- How was it... "You will die anyway"?}
#{1118}{}{Oh, you dimwit! Do you even realize, what have you done!? [grabs his head]}
{1118}{}{哦，你这个笨蛋！你知道吗，你做了什么！？[抓住他的头] -- Oh, you dimwit! Do you even realize, what have you done!? [grabs his head]}
#{1120}{}{To go where? I have no home! Thanks, of course, you did quite a service, but they could give me work with food and water, and now I have to find them myself... You're a moron if you think that you made it better!}
{1120}{}{去哪里？我没有家！谢谢，当然，你帮了我不少忙，但是他们可以给我提供食物和水，现在我得自己去找他们。。。如果你认为自己做得更好，你就是个白痴！ -- To go where? I have no home! Thanks, of course, you did quite a service, but they could give me work with food and water, and now I have to find them myself... You're a moron if you think that you made it better!}
