#{100}{}{You see a terminal.}
{100}{}{你看到一个终端。 -- You see a terminal.}
#{101}{}{You see a terminal of emergency help for City Hall workers.}
{101}{}{你看到了市政厅工作人员的紧急救助终端。 -- You see a terminal of emergency help for City Hall workers.}
#{102}{}{Not during combat.}
{102}{}{不是在战斗中。 -- Not during combat.}
#{103}{}{Your knowledge in computer systems is not enough to crack this terminal.}
{103}{}{你对计算机系统的知识还不足以破解这个终端。 -- Your knowledge in computer systems is not enough to crack this terminal.}
#{104}{}{To use this terminal, scientific methods are needed.}
{104}{}{要使用这个终端，需要科学的方法。 -- To use this terminal, scientific methods are needed.}
#{105}{}{A scientific method is required}
{105}{}{需要科学的方法 -- A scientific method is required}
#{106}{}{This terminal no longer works.}
{106}{}{这个终端不再工作了。 -- This terminal no longer works.}
#{107}{}{Not functional}
{107}{}{不起作用 -- Not functional}
#{108}{}{You managed to bypass the system. The emergency terminal gave you a stimpak, then tried to reboot - and shut down.}
{108}{}{你设法绕过了系统。紧急终端给了你一个stimpak，然后试图重新启动-然后关闭。 -- You managed to bypass the system. The emergency terminal gave you a stimpak, then tried to reboot - and shut down.}
#{109}{}{Yes!}
{109}{}{对！ -- Yes!}
