#{100}{}{This elevator intentionally damaged and de-energized, so it's not going anywhere.}
{100}{}{这部电梯故意损坏断电，所以哪儿也去不了。 -- This elevator intentionally damaged and de-energized, so it's not going anywhere.}
#{101}{}{With a fear for your life you go down through elevator shaft.}
{101}{}{带着对生命的恐惧，你从电梯井下去。 -- With a fear for your life you go down through elevator shaft.}
#{102}{}{With a fear for your life you climb up through elevator shaft.}
{102}{}{带着对生命的恐惧，你爬上电梯井。 -- With a fear for your life you climb up through elevator shaft.}
#{103}{}{Doesn't work.}
{103}{}{不起作用。 -- Doesn't work.}
#{104}{}{Hey... Someone or something shut the door!}
{104}{}{嘿。。。有人或什么东西把门关上！ -- Hey... Someone or something shut the door!}
#{105}{}{Oh shit!!!}
{105}{}{哦，妈的！！！ -- Oh shit!!!}
