#{100}{}{You see a dealer.}
{100}{}{你看到一个商人。 -- You see a dealer.}
#{101}{}{You see a dice table.}
{101}{}{你看到一张骰子桌。 -- You see a dice table.}
#{102}{}{Before you play, unequip any dangerous items.}
{102}{}{在你玩之前，解开任何危险物品。 -- Before you play, unequip any dangerous items.}
#{110}{}{You see a girl.}
{110}{}{你看到一个女孩。 -- You see a girl.}
#{111}{}{You see a table.}
{111}{}{你看到一张桌子。 -- You see a table.}
#{112}{}{Results: }
{112}{}{结果： -- Results: }
#{113}{}{ to }
{113}{}{到 --  to }
#{114}{}{ your favor.}
{114}{}{你的好意。 --  your favor.}
#{115}{}{ casino's favor.}
{115}{}{赌场的恩惠。 --  casino's favor.}
#{140}{}{You see a table for playing dice games.}
{140}{}{你看到一张玩骰子的桌子。 -- You see a table for playing dice games.}
#{141}{}{You see a table with stuff on it.}
{141}{}{你看到一张桌子上有东西。 -- You see a table with stuff on it.}
#{150}{}{You see one of the casino dealers.}
{150}{}{你看到一个赌场商人。 -- You see one of the casino dealers.}
#{151}{}{You see one of the casino dealers. She motions for you to come over and play.}
{151}{}{你看到一个赌场商人。她示意你过来玩。 -- You see one of the casino dealers. She motions for you to come over and play.}
#{152}{}{You see one of the casino dealers. Her dress barely covers her body.}
{152}{}{你看到一个赌场商人。她的衣服几乎遮住了她的身体。 -- You see one of the casino dealers. Her dress barely covers her body.}
#{153}{}{You see one of the casino dealers. She's got some nice guns.}
{153}{}{你看到一个赌场商人。她有一些漂亮的枪。 -- You see one of the casino dealers. She's got some nice guns.}
#{154}{}{You see one of the casino dealers. She winks at you.}
{154}{}{你看到一个赌场商人。她向你眨眼。 -- You see one of the casino dealers. She winks at you.}
#{155}{}{You see one of the casino dealers. She smells reeeally nice.}
{155}{}{你看到一个赌场商人。她闻起来真香。 -- You see one of the casino dealers. She smells reeeally nice.}
#{175}{}{NO DICE!!!}
{175}{}{没有骰子！！！ -- NO DICE!!!}
#{176}{}{TOO MANY DICE!!!}
{176}{}{骰子太多了！！！ -- TOO MANY DICE!!!}
#{177}{}{The odds seem right ever since you switched the dice.}
{177}{}{自从你换了骰子，胜算似乎是对的。 -- The odds seem right ever since you switched the dice.}
#{178}{}{The odds don't seem quite right.}
{178}{}{可能性似乎不大。 -- The odds don't seem quite right.}
#{179}{}{You can't tell the odds for certain.}
{179}{}{你不能确定胜算。 -- You can't tell the odds for certain.}
#{185}{}{The odds seem about right.}
{185}{}{可能性似乎差不多。 -- The odds seem about right.}
#{186}{}{You can't tell the odds for certain.}
{186}{}{你不能确定胜算。 -- You can't tell the odds for certain.}
#{187}{}{The odds don't seem quite right.}
{187}{}{可能性似乎不大。 -- The odds don't seem quite right.}
#{215}{}{Hello, }
{215}{}{你好， -- Hello, }
#{216}{}{If you're looking for a little company later... }
{216}{}{如果你以后想找个小公司。。。 -- If you're looking for a little company later... }
#{217}{}{Hey, you... [winks]... Are you looking to gamble?}
{217}{}{嘿，你。。。[眨眼]。。。你想赌博吗？ -- Hey, you... [winks]... Are you looking to gamble?}
#{218}{}{He looks so... [shivers]... Dangerous.}
{218}{}{他看起来很。。。[颤抖]。。。危险。 -- He looks so... [shivers]... Dangerous.}
#{219}{}{Welcome to the casino, }
{219}{}{欢迎来到赌场， -- Welcome to the casino, }
#{220}{}{Put in a good word with the boss for me?}
{220}{}{替我跟老板说句好话？ -- Put in a good word with the boss for me?}
#{221}{}{Hello, ma'am. Let me know if I can help you with anything.}
{221}{}{你好，女士。如果我能帮你什么，请告诉我。 -- Hello, ma'am. Let me know if I can help you with anything.}
#{222}{}{Looking to gamble, ma'am?}
{222}{}{想赌博吗，女士？ -- Looking to gamble, ma'am?}
#{223}{}{She looks so... [shivers]... Dangerous.}
{223}{}{她看起来很。。。[颤抖]。。。危险。 -- She looks so... [shivers]... Dangerous.}
#{235}{}{Looks like this one's already gambling with his life.}
{235}{}{看来这个人已经在拿自己的生命冒险了。 -- Looks like this one's already gambling with his life.}
#{236}{}{Uh, I think he just walked into the wrong casino... }
{236}{}{呃，我想他进错赌场了。。。 -- Uh, I think he just walked into the wrong casino... }
#{237}{}{If he doesn't leave before the boys see him... }
{237}{}{如果他不在孩子们看到他之前离开。。。 -- If he doesn't leave before the boys see him... }
#{238}{}{Uh-oh. Trouble... }
{238}{}{哦哦。麻烦。。。 -- Uh-oh. Trouble... }
#{239}{}{Looks like this one's already gambling with her life.}
{239}{}{看来这个人已经在用生命赌博了。 -- Looks like this one's already gambling with her life.}
#{240}{}{Uh, I think she just walked into the wrong casino... }
{240}{}{呃，我想她进错赌场了。。。 -- Uh, I think she just walked into the wrong casino... }
#{241}{}{If she doesn't leave before the boys see her... }
{241}{}{如果她不在孩子们看到她之前离开。。。 -- If she doesn't leave before the boys see her... }
#{270}{}{Hey there, movie man. You looking to spend some chips?}
{270}{}{嘿，电影人。你想花点钱吗？ -- Hey there, movie man. You looking to spend some chips?}
#{271}{}{Hey, }
{271}{}{嘿， -- Hey, }
#{272}{}{Hey, }
{272}{}{嘿， -- Hey, }
#{273}{}{If you're looking to win some chips }
{273}{}{如果你想赢些筹码 -- If you're looking to win some chips }
#{274}{}{Lady Luck's in the house tonight... Nothing but winners!}
{274}{}{幸运女神今晚在家。。。只有赢家！ -- Lady Luck's in the house tonight... Nothing but winners!}
#{275}{}{Step right up, }
{275}{}{站起来， -- Step right up, }
#{276}{}{Need another drink?}
{276}{}{需要再来一杯吗？ -- Need another drink?}
#{277}{}{Welcome to the casino, }
{277}{}{欢迎来到赌场， -- Welcome to the casino, }
#{278}{}{Hey there, Ms. Movie Star. Looking to spend a paycheck?}
{278}{}{嘿，电影明星小姐。想花点钱吗？ -- Hey there, Ms. Movie Star. Looking to spend a paycheck?}
#{279}{}{You dancing tonight?}
{279}{}{你今晚跳舞吗？ -- You dancing tonight?}
#{290}{}{Hey there, sweetie. You looking to spend some chips?}
{290}{}{嘿，亲爱的。你想花点钱吗？ -- Hey there, sweetie. You looking to spend some chips?}
#{291}{}{Hey, sweetie... [winks]... You looking to gamble?}
{291}{}{嘿，亲爱的。。。[眨眼]。。。你想赌博吗？ -- Hey, sweetie... [winks]... You looking to gamble?}
#{292}{}{Hey, sweetie... [smiles]... Wanna take a chance?}
{292}{}{嘿，亲爱的。。。[微笑]。。。想试试吗？ -- Hey, sweetie... [smiles]... Wanna take a chance?}
#{293}{}{If you're looking to win some chips, you came to the right place.}
{293}{}{如果你想赢些筹码，你来对地方了。 -- If you're looking to win some chips, you came to the right place.}
#{294}{}{Lady Luck's in the house tonight... Nothing but winners!}
{294}{}{幸运女神今晚在家。。。只有赢家！ -- Lady Luck's in the house tonight... Nothing but winners!}
#{295}{}{Step right up, win some chips.}
{295}{}{站起来，赢些筹码。 -- Step right up, win some chips.}
#{296}{}{Need another drink, honey?}
{296}{}{需要再来一杯吗，亲爱的？ -- Need another drink, honey?}
#{297}{}{Welcome to the casino, honey.}
{297}{}{欢迎来到赌场，亲爱的。 -- Welcome to the casino, honey.}
#{298}{}{This table's free if you're looking to gamble... }
{298}{}{如果你想赌博的话，这张桌子是免费的。。。 -- This table's free if you're looking to gamble... }
#{299}{}{Hey there, honey. You looking to spend some chips?}
{299}{}{嘿，亲爱的。你想花点钱吗？ -- Hey there, honey. You looking to spend some chips?}
#{300}{}{Looking to gamble, honey?}
{300}{}{想赌博吗，亲爱的？ -- Looking to gamble, honey?}
#{301}{}{Welcome to the casino, honey.}
{301}{}{欢迎来到赌场，亲爱的。 -- Welcome to the casino, honey.}
#{320}{}{[The dealer looks at you nervously, then chews her lip.] Um, place your bets... Minimum bet $}
{320}{}{[庄家紧张地看着你，然后咬着嘴唇。]嗯，下注吧。。。最小赌注$ -- [The dealer looks at you nervously, then chews her lip.] Um, place your bets... Minimum bet $}
#{321}{}{Place your bet, sir. Minimum bet $}
{321}{}{下注吧，先生。最小赌注$ -- Place your bet, sir. Minimum bet $}
#{322}{}{Place your bet, ma'am. Minimum bet $}
{322}{}{下注吧，女士。最小赌注$ -- Place your bet, ma'am. Minimum bet $}
#{323}{}{Place your bets, minimum bet $}
{323}{}{下注，最低下注$ -- Place your bets, minimum bet $}
#{324}{}{Me bet-ter than you}
{324}{}{我打赌我比你厉害 -- Me bet-ter than you}
#{325}{}{Me play craps in pants}
{325}{}{我在裤子里拉屎 -- Me play craps in pants}
#{326}{}{What this game? Can you bet gecko skin?  Me got geck... Ooooh... Pretty lights! [wander off]}
{326}{}{这是什么游戏？你能打赌壁虎皮吗？我找到geck了。。。哦哦。。。漂亮的灯光！[漫游] -- What this game? Can you bet gecko skin?  Me got geck... Ooooh... Pretty lights! [wander off]}
#{327}{}{[You have $}
{327}{}{[你有$ -- [You have $}
#{328}{}{Bet $}
{328}{}{打赌$ -- Bet $}
#{329}{}{Whoa, too rich for my blood.}
{329}{}{哇，对我的血液来说太丰富了。 -- Whoa, too rich for my blood.}
#{330}{}{No bets today, thanks.}
{330}{}{今天不用赌了，谢谢。 -- No bets today, thanks.}
#{331}{}{Uhhh, sorry, I don't know how to play these crazy games.}
{331}{}{呃，对不起，我不知道怎么玩这些疯狂的游戏。 -- Uhhh, sorry, I don't know how to play these crazy games.}
#{340}{}{Um... I hear they're giving away brains out back. Maybe you should go check it out.}
{340}{}{嗯。。。我听说他们要把脑浆送出去。也许你应该去看看。 -- Um... I hear they're giving away brains out back. Maybe you should go check it out.}
#{341}{}{Uh, very well, sir. Come back soon.}
{341}{}{呃，很好，先生。快回来。 -- Uh, very well, sir. Come back soon.}
#{342}{}{Uh, very well, ma'am. Come back soon.}
{342}{}{呃，很好，女士。快回来。 -- Uh, very well, ma'am. Come back soon.}
#{343}{}{Byeee-byeeee}
{343}{}{再见再见 -- Byeee-byeeee}
#{344}{}{Gooodie. }
{344}{}{古迪。 -- Gooodie. }
#{345}{}{Uh... Brains... What them?! Me go see!}
{345}{}{休斯敦大学。。。大脑。。。他们怎么了？！我去看看！ -- Uh... Brains... What them?! Me go see!}
#{350}{}{Very well, sir. Come back soon.}
{350}{}{很好，先生。快回来。 -- Very well, sir. Come back soon.}
#{351}{}{Very well, ma'am. Come back soon.}
{351}{}{很好，夫人。快回来。 -- Very well, ma'am. Come back soon.}
#{352}{}{[Dealer raises an eyebrow.] $}
{352}{}{【经销商扬起眉毛】$ -- [Dealer raises an eyebrow.] $}
#{354}{}{I will, thanks.}
{354}{}{我会的，谢谢。 -- I will, thanks.}
#{355}{}{Maybe so.}
{355}{}{也许是吧。 -- Maybe so.}
#{400}{}{Sorry, better luck next time.}
{400}{}{对不起，祝你下次好运。 -- Sorry, better luck next time.}
#{401}{}{Sorry, sir. Better luck next time.}
{401}{}{对不起，先生。祝你下次好运。 -- Sorry, sir. Better luck next time.}
#{402}{}{Sorry, ma'am. Better luck next time.}
{402}{}{对不起，女士。祝你下次好运。 -- Sorry, ma'am. Better luck next time.}
#{410}{}{Winner!}
{410}{}{赢家！ -- Winner!}
#{411}{}{Winner! Well done, sir!}
{411}{}{赢家！干得好，先生！ -- Winner! Well done, sir!}
#{412}{}{Winner! Well done, ma'am!}
{412}{}{赢家！干得好，女士！ -- Winner! Well done, ma'am!}
#{420}{}{Winner! You've doubled your money!}
{420}{}{赢家！你的钱翻了一倍！ -- Winner! You've doubled your money!}
#{421}{}{Winner! You've doubled your money! Well done, sir!}
{421}{}{赢家！你的钱翻了一倍！干得好，先生！ -- Winner! You've doubled your money! Well done, sir!}
#{422}{}{Winner! You've doubled your money! Well done, ma'am!}
{422}{}{赢家！你的钱翻了一倍！干得好，女士！ -- Winner! You've doubled your money! Well done, ma'am!}
#{430}{}{Winner! You've tripled your money!}
{430}{}{赢家！你的钱增加了三倍！ -- Winner! You've tripled your money!}
#{431}{}{Winner! You've tripled your money! Luck is in the house tonight! Well done, sir!}
{431}{}{赢家！你的钱增加了三倍！今晚幸运就在家里！干得好，先生！ -- Winner! You've tripled your money! Luck is in the house tonight! Well done, sir!}
#{432}{}{Winner! You've tripled your money! Luck is in the house tonight! Well done, sir!}
{432}{}{赢家！你的钱增加了三倍！今晚幸运就在家里！干得好，先生！ -- Winner! You've tripled your money! Luck is in the house tonight! Well done, sir!}
#{440}{}{Call it a day.}
{440}{}{今天到此为止。 -- Call it a day.}
#{441}{}{Call it a night.}
{441}{}{到此为止。 -- Call it a night.}
#{445}{}{Sorry, this table is temporarily closed. Use another, if you wish to continue.}
{445}{}{对不起，这张桌子暂时不营业。如果要继续，请使用另一个。 -- Sorry, this table is temporarily closed. Use another, if you wish to continue.}
#{446}{}{Sorry, the table is closed. It will reopen in a couple of minutes.}
{446}{}{对不起，桌子关门了。几分钟后就要重新开放了。 -- Sorry, the table is closed. It will reopen in a couple of minutes.}
#{447}{}{Table is opened}
{447}{}{表格已打开 -- Table is opened}
#{450}{}{Sorry, this table has been closed. Someone has been tampering with the dice.}
{450}{}{对不起，这张桌子已经关门了。有人在捣乱骰子。 -- Sorry, this table has been closed. Someone has been tampering with the dice.}
#{451}{}{Sorry sir, this table has been closed. Someone has been tampering with the dice.}
{451}{}{对不起，先生，这张桌子已经关门了。有人在捣乱骰子。 -- Sorry sir, this table has been closed. Someone has been tampering with the dice.}
#{452}{}{Sorry ma'am, this table has been closed. Someone has been tampering with the dice.}
{452}{}{对不起，女士，这张桌子已经关门了。有人在捣乱骰子。 -- Sorry ma'am, this table has been closed. Someone has been tampering with the dice.}
#{453}{}{Uhh, okay.}
{453}{}{呃，好吧。 -- Uhh, okay.}
#{454}{}{Sorry to hear that. Thanks.}
{454}{}{很抱歉听到这个消息。谢谢。 -- Sorry to hear that. Thanks.}
#{2203}{}{! Welcome to the casino, hero!}
{2203}{}{! 欢迎来到赌场，英雄！ -- ! Welcome to the casino, hero!}
#{2215}{}{. Can I help you with... *anything?*}
{2215}{}{. 我能帮你。。。*有什么事吗？* -- . Can I help you with... *anything?*}
#{2219}{}{.}
{2219}{}{. -- .}
#{2255}{}{. Looking to spend some chips?}
{2255}{}{. 想花点钱吗？ -- . Looking to spend some chips?}
#{2258}{}{, win some chips.}
{2258}{}{，赢得一些筹码。 -- , win some chips.}
#{2260}{}{.}
{2260}{}{. -- .}
#{2261}{}{. Let me know if I can help you with anything.}
{2261}{}{. 如果我能帮你什么，请告诉我。 -- . Let me know if I can help you with anything.}
#{2262}{}{?}
{2262}{}{? -- ?}
#{2263}{}{.}
{2263}{}{. -- .}
#{2321}{}{. Place your bets... }
{2321}{}{. 下注。。。 -- . Place your bets... }
#{2327}{}{.] }
{2327}{}{.] -- .] }
#{2328}{}{.}
{2328}{}{. -- .}
#{2344}{}{ could always use new inventory item [Leave.]}
{2344}{}{始终可以使用新库存项[离开] --  could always use new inventory item [Leave.]}
#{2352}{}{? 'Too rich for your blood?' [Scoffs.] Pal, you're in the wrong town.}
{2352}{}{? '你的血太多了吗伙计，你来错地方了。 -- ? 'Too rich for your blood?' [Scoffs.] Pal, you're in the wrong town.}
#{2353}{}{? 'Too rich for your blood?' [Scoffs.] Girl, you're in the wrong town.}
{2353}{}{? '你的血太多了吗女孩，你来错地方了。 -- ? 'Too rich for your blood?' [Scoffs.] Girl, you're in the wrong town.}
