#{100}{}{You see a door.}
{100}{}{你看到一扇门。 -- You see a door.}
#{101}{}{You see an ordinary door.}
{101}{}{你看到一扇普通的门。 -- You see an ordinary door.}
#{102}{}{You see an ordinary door. It almost says: Open me!}
{102}{}{你看到一扇普通的门。它几乎说：打开我！ -- You see an ordinary door. It almost says: Open me!}
#{103}{}{The door is too tough to take down.}
{103}{}{这门太硬了，拆不下来。 -- The door is too tough to take down.}
#{104}{}{The blow was not strong enough to take the door down.}
{104}{}{这一击不足以把门推倒。 -- The blow was not strong enough to take the door down.}
#{105}{}{Door is obliterated.}
{105}{}{门被擦掉了。 -- Door is obliterated.}
#{106}{}{Did you really expect to pull this off with muscles like that?}
{106}{}{你真的期望用那样的肌肉来完成这个吗？ -- Did you really expect to pull this off with muscles like that?}
#{107}{}{You don't have anything to light the thermite.}
{107}{}{你没有任何东西来点燃铝热剂。 -- You don't have anything to light the thermite.}
#{108}{}{It's no use}
{108}{}{没用的 -- It's no use}
#{109}{}{The incredible heat melts through the locks like butter.}
{109}{}{难以置信的热量像黄油一样融化在锁孔里。 -- The incredible heat melts through the locks like butter.}
#{110}{}{The door is locked.}
{110}{}{门是锁着的。 -- The door is locked.}
#{111}{}{Locked.}
{111}{}{锁定。 -- Locked.}
#{112}{}{Careful, the door is trapped!}
{112}{}{小心，门被困住了！ -- Careful, the door is trapped!}
#{113}{}{Trap!}
{113}{}{陷阱！ -- Trap!}
#{114}{}{Clear.}
{114}{}{清除。 -- Clear.}
#{115}{}{You couldn't disarm the trap. Lucky for you, it didn't blow up.}
{115}{}{你不能解除陷阱。幸运的是，它没有爆炸。 -- You couldn't disarm the trap. Lucky for you, it didn't blow up.}
#{116}{}{You disarmed the trap and placed it in your bag.}
{116}{}{你解除了陷阱，把它放进了包里。 -- You disarmed the trap and placed it in your bag.}
#{117}{}{Done}
{117}{}{多恩 -- Done}
#{118}{}{Good job, you triggered the trap.}
{118}{}{干得好，你触发了陷阱。 -- Good job, you triggered the trap.}
#{119}{}{Bad luck - the pin snapped.}
{119}{}{倒霉-别针折断了。 -- Bad luck - the pin snapped.}
#{120}{}{You locked the door.}
{120}{}{你锁门了。 -- You locked the door.}
#{121}{}{You unlocked the door.}
{121}{}{你打开了门。 -- You unlocked the door.}
#{122}{}{ experience points for cracking a tough lock.}
{122}{}{破解锁的经验点。 --  experience points for cracking a tough lock.}
#{123}{}{You couldn't unlock this lock.}
{123}{}{你不能打开这把锁。 -- You couldn't unlock this lock.}
#{124}{}{You receive }
{124}{}{你收到了吗 -- You receive }
#{125}{}{ experience points.}
{125}{}{经验点。 --  experience points.}
#{126}{}{This is beyond your abilities.}
{126}{}{这超出了你的能力。 -- This is beyond your abilities.}
#{127}{}{You don't have anything to light the thermite.}
{127}{}{你没有任何东西来点燃铝热剂。 -- You don't have anything to light the thermite.}
#{128}{}{It's no use}
{128}{}{没用的 -- It's no use}
#{129}{}{The incredible heat melts through the locks like butter.}
{129}{}{难以置信的热量像黄油一样融化在锁孔里。 -- The incredible heat melts through the locks like butter.}
#{130}{}{An Electronic Lockpick won't help, this is a mechanical lock.}
{130}{}{电子开锁器没用，这是机械锁。 -- An Electronic Lockpick won't help, this is a mechanical lock.}
#{131}{}{Lockpicks won't help, this is an electronic lock.}
{131}{}{撬锁没用，这是电子锁。 -- Lockpicks won't help, this is an electronic lock.}
#{132}{}{Wrong lockpicks}
{132}{}{错误的开锁器 -- Wrong lockpicks}
#{133}{}{The door crumbles under your strength.}
{133}{}{门在你的力量下破碎了。 -- The door crumbles under your strength.}
#{134}{}{Did you really expect to pull this off with muscles like that?}
{134}{}{你真的期望用那样的肌肉来完成这个吗？ -- Did you really expect to pull this off with muscles like that?}
#{135}{}{Ugh!}
{135}{}{啊！ -- Ugh!}
#{136}{}{}
{136}{}{ -- }
#{137}{}{}
{137}{}{ -- }
#{138}{}{You can't just break this door down. You'll need a lot more force than that.}
{138}{}{你不能把这扇门撞坏。你需要更多的力量。 -- You can't just break this door down. You'll need a lot more force than that.}
#{139}{}{The laser beam can't pierce through the door.}
{139}{}{激光束不能穿透门。 -- The laser beam can't pierce through the door.}
#{140}{}{No use}
{140}{}{没用 -- No use}
#{141}{}{This is pointless.}
{141}{}{这是毫无意义的。 -- This is pointless.}
#{142}{}{This is pointless - the door is already trapped.}
{142}{}{这是毫无意义的-门已经被困住了。 -- This is pointless - the door is already trapped.}
#{143}{}{Done}
{143}{}{多恩 -- Done}
#{144}{}{You've trapped the door. Touching it again is probably a bad idea.}
{144}{}{你把门关上了。再碰一下可能是个坏主意。 -- You've trapped the door. Touching it again is probably a bad idea.}
#{145}{}{Trapped}
{145}{}{被困 -- Trapped}
#{146}{}{Bad luck}
{146}{}{运气不好 -- Bad luck}
#{147}{}{You couldn't install the trap.}
{147}{}{你不能安装陷阱。 -- You couldn't install the trap.}
#{148}{}{Thanks to your lack of expertise, the trap worked prematurely.}
{148}{}{由于你缺乏专业知识，这个陷阱过早地奏效了。 -- Thanks to your lack of expertise, the trap worked prematurely.}
#{150}{}{You activated the alarm!}
{150}{}{你启动了警报！ -- You activated the alarm!}
#{151}{}{Hey! What's going on!?}
{151}{}{嘿！发生什么事！？ -- Hey! What's going on!?}
#{152}{}{This key doesn't fit.}
{152}{}{这把钥匙不合适。 -- This key doesn't fit.}
#{153}{}{That's not it}
{153}{}{不是这样的 -- That's not it}
#{154}{}{You can't set a trap on an open door.}
{154}{}{你不能在开着的门上设陷阱。 -- You can't set a trap on an open door.}
#{155}{}{You completed Luciano's task.}
{155}{}{你完成了卢西亚诺的任务。 -- You completed Luciano's task.}
#{160}{}{Conclusion: this door has a low level of difficulty.}
{160}{}{结论：此门的难度较低。 -- Conclusion: this door has a low level of difficulty.}
#{161}{}{Conclusion: this door has a medium level of difficulty.}
{161}{}{结论：这扇门难度中等。 -- Conclusion: this door has a medium level of difficulty.}
#{162}{}{Conclusion: this door has a high level of difficulty.}
{162}{}{结论：这扇门难度很大。 -- Conclusion: this door has a high level of difficulty.}
#{163}{}{Conclusion: this door has a super-tough level of difficulty.}
{163}{}{结论：这扇门的难度非常大。 -- Conclusion: this door has a super-tough level of difficulty.}
#{164}{}{[Lockpicking required >}
{164}{}{[需要开锁> -- [Lockpicking required >}
#{165}{}{]}
{165}{}{] -- ]}
#{200}{}{You see a tough warehouse door.}
{200}{}{你看到一扇坚固的仓库门。 -- You see a tough warehouse door.}
#{201}{}{You see an emergency exit from a pharmacy.}
{201}{}{你看到药房的紧急出口。 -- You see an emergency exit from a pharmacy.}
#{202}{}{You see a flimsy warehouse door.}
{202}{}{你看到一个脆弱的仓库门。 -- You see a flimsy warehouse door.}
#{203}{}{You see a gate to the slave pens.}
{203}{}{你看到一扇通往奴隶围栏的大门。 -- You see a gate to the slave pens.}
#{204}{}{You see an armored door to the reactor.}
{204}{}{你看到一扇通往反应堆的装甲门。 -- You see an armored door to the reactor.}
#{205}{}{You see a strong warehouse door.}
{205}{}{你看到一个坚固的仓库门。 -- You see a strong warehouse door.}
#{206}{}{You see hotel room numbered 26.}
{206}{}{你看到26号旅馆房间了。 -- You see hotel room numbered 26.}
#{207}{}{You see hotel room numbered 14.}
{207}{}{你看到14号旅馆房间了。 -- You see hotel room numbered 14.}
#{208}{}{You see hotel room numbered 7.}
{208}{}{你看到7号旅馆房间了。 -- You see hotel room numbered 7.}
#{209}{}{You see a strong, heavy door, reinforced with metal. Breaking it down will be hard, to say the least.}
{209}{}{你看到一扇坚固、沉重的门，用金属加固。至少可以说，分解它是很困难的。 -- You see a strong, heavy door, reinforced with metal. Breaking it down will be hard, to say the least.}
#{210}{}{You see a very tough door reinforced with metal.}
{210}{}{你看到一扇用金属加固的很硬的门。 -- You see a very tough door reinforced with metal.}
#{211}{}{You see a heavy, armored door to a weapon warehouse.}
{211}{}{你看到武器仓库的一扇沉重的装甲门。 -- You see a heavy, armored door to a weapon warehouse.}
#{212}{}{You see a tough, electronic warehouse door.}
{212}{}{你看到一扇坚硬的电子仓库门。 -- You see a tough, electronic warehouse door.}
#{213}{}{You see a tough garage door.}
{213}{}{你看到一扇坚固的车库门。 -- You see a tough garage door.}
#{214}{}{You see a very tough gate to a bunker. The lock looks like it was changed recently.}
{214}{}{你看到一扇通往碉堡的大门非常坚固。锁好像是最近换的。 -- You see a very tough gate to a bunker. The lock looks like it was changed recently.}
#{215}{}{Hm. There must be some sort of bunker below. The lock is brand new.}
{215}{}{嗯。下面一定有什么掩体。这把锁是全新的。 -- Hm. There must be some sort of bunker below. The lock is brand new.}
#{216}{}{You see a standard Vault door.}
{216}{}{你会看到一个标准的金库门。 -- You see a standard Vault door.}
#{217}{}{You see a hotel room numbered 15.}
{217}{}{你看到一间15号的旅馆房间。 -- You see a hotel room numbered 15.}
#{218}{}{You see a heavy duty hatch with a tough lock. It probably needs a special key.}
{218}{}{你看到一个重型舱门，锁很硬。它可能需要一把特别的钥匙。 -- You see a heavy duty hatch with a tough lock. It probably needs a special key.}
#{219}{}{This is a *very* tough lock. There's probably a key for it somewhere nearby.}
{219}{}{这是一把非常结实的锁。附近可能有钥匙。 -- This is a *very* tough lock. There's probably a key for it somewhere nearby.}
#{220}{}{You see a tough backdoor.}
{220}{}{你看到一个艰难的后门。 -- You see a tough backdoor.}
#{221}{}{You see a tough hangar door.}
{221}{}{你会看到一扇坚硬的机库门。 -- You see a tough hangar door.}
#{222}{}{You see an ordinary door. You can barely make out the number 9 on the surface.}
{222}{}{你看到一扇普通的门。你几乎看不清表面上的数字9。 -- You see an ordinary door. You can barely make out the number 9 on the surface.}
#{223}{}{You see tough gates with electronic locks.}
{223}{}{你看到了带电子锁的坚固大门。 -- You see tough gates with electronic locks.}
