#{100}{}{You see a vending machine.}
{100}{}{你看到一台自动售货机。 -- You see a vending machine.}
#{101}{}{You see a vending machine with Nuka-Cola - a tool of your own business.}
{101}{}{你会看到一台自动售货机，里面有你自己的工具Nuka Cola。 -- You see a vending machine with Nuka-Cola - a tool of your own business.}
#{102}{}{This vending machine is broken and robbed.}
{102}{}{这台自动售货机坏了，被抢了。 -- This vending machine is broken and robbed.}
#{103}{}{Not during combat!}
{103}{}{不是在战斗中！ -- Not during combat!}
#{110}{}{This machine is still working and can generate you income.}
{110}{}{这台机器还在运转，可以给你带来收入。 -- This machine is still working and can generate you income.}
#{111}{}{Take your revenue.}
{111}{}{拿你的收入。 -- Take your revenue.}
#{112}{}{Load the cola bottles.}
{112}{}{装可乐瓶。 -- Load the cola bottles.}
#{113}{}{Unload the cola bottles.}
{113}{}{把可乐瓶卸下来。 -- Unload the cola bottles.}
#{114}{}{How much cola left in stock?}
{114}{}{可乐还有多少存货？ -- How much cola left in stock?}
#{115}{}{View estimated profit expectations.}
{115}{}{查看预计利润预期。 -- View estimated profit expectations.}
#{116}{}{Leave the machine.}
{116}{}{离开机器。 -- Leave the machine.}
#{117}{}{}
{117}{}{ -- }
#{118}{}{}
{118}{}{ -- }
#{119}{}{}
{119}{}{ -- }
#{120}{}{Your revenue for the past period amounted to $}
{120}{}{你过去一段时间的收入是$ -- Your revenue for the past period amounted to $}
#{121}{}{.}
{121}{}{. -- .}
#{122}{}{Back.}
{122}{}{回来。 -- Back.}
#{123}{}{Close cash register.}
{123}{}{关上收银机。 -- Close cash register.}
#{124}{}{Since the last revenue, no coins appeared in the machine.}
{124}{}{自从上次有收入以来，机器里就没有硬币了。 -- Since the last revenue, no coins appeared in the machine.}
#{125}{}{There's no product left in the machine.}
{125}{}{机器里没有产品了。 -- There's no product left in the machine.}
#{130}{}{There's no product left at the stock.}
{130}{}{库存中没有产品了。 -- There's no product left at the stock.}
#{131}{}{The stock has (}
{131}{}{股票已经上涨了( -- The stock has (}
#{132}{}{) Nuka-Cola cola.}
{132}{}{)努卡可乐。 -- ) Nuka-Cola cola.}
#{133}{}{Presumably, local consumers are willing to buy about }
{133}{}{据推测，当地消费者愿意购买 -- Presumably, local consumers are willing to buy about }
#{134}{}{ bottles of drink per day, if the city's social situation stays the same.}
{134}{}{如果城市的社会状况保持不变，每天要喝几瓶。 --  bottles of drink per day, if the city's social situation stays the same.}
#{140}{}{Please put the cola in the container.}
{140}{}{请把可乐放在容器里。 -- Please put the cola in the container.}
#{141}{}{5 bottles.}
{141}{}{5瓶。 -- 5 bottles.}
#{142}{}{10 bottles.}
{142}{}{10瓶。 -- 10 bottles.}
#{143}{}{20 bottles.}
{143}{}{20瓶。 -- 20 bottles.}
#{144}{}{30 bottles.}
{144}{}{30瓶。 -- 30 bottles.}
#{145}{}{50 bottles.}
{145}{}{50瓶。 -- 50 bottles.}
#{146}{}{100 bottles.}
{146}{}{100瓶。 -- 100 bottles.}
#{147}{}{Load all available cola bottles.}
{147}{}{装入所有可用的可乐瓶。 -- Load all available cola bottles.}
#{148}{}{Leave it.}
{148}{}{别管了。 -- Leave it.}
#{149}{}{Done.}
{149}{}{完成。 -- Done.}
#{150}{}{The stock has (}
{150}{}{股票已经上涨了( -- The stock has (}
#{151}{}{) Nuka-Cola cola.}
{151}{}{)努卡可乐。 -- ) Nuka-Cola cola.}
#{152}{}{}
{152}{}{ -- }
#{153}{}{Take 5 bottles.}
{153}{}{拿5瓶。 -- Take 5 bottles.}
#{154}{}{Take 10 bottles.}
{154}{}{拿10瓶。 -- Take 10 bottles.}
#{155}{}{Take 20 bottles.}
{155}{}{拿20瓶。 -- Take 20 bottles.}
#{156}{}{Take 30 bottles.}
{156}{}{拿30瓶。 -- Take 30 bottles.}
#{157}{}{Take 50 bottles.}
{157}{}{拿50瓶。 -- Take 50 bottles.}
#{158}{}{Take 100 bottles.}
{158}{}{拿100瓶。 -- Take 100 bottles.}
#{159}{}{Take all the remaining bottles.}
{159}{}{把剩下的瓶子都拿走。 -- Take all the remaining bottles.}
#{160}{}{Leave it.}
{160}{}{别管了。 -- Leave it.}
#{161}{}{Done.}
{161}{}{完成。 -- Done.}
#{162}{}{There's no product left at the stock.}
{162}{}{库存中没有产品了。 -- There's no product left at the stock.}
#{163}{}{Sorry, I can't carry that much.}
{163}{}{对不起，我拿不了那么多。 -- Sorry, I can't carry that much.}
#{164}{}{Take as much as I can carry.}
{164}{}{我能拿多少就拿多少。 -- Take as much as I can carry.}
