### {100}{}{Don't try to steal from the father.}
{100}{}{不要试图从父亲那里偷东西。}
### {101}{}{Behave yourself!}
{101}{}{规矩点！}
### {102}{}{Our father can give you a blessing.}
{102}{}{我们的父亲可以给你祝福。}
### {103}{}{Be smart!}
{103}{}{聪明点！}
### {104}{}{Play by the rules!}
{104}{}{遵守规则！}
### {105}{}{Don't bother me.}
{105}{}{别打扰我。}
### {106}{}{Stay away from me, bastard!}
{106}{}{离我远点，混蛋！}
### {107}{}{Don't make me shoot you.}
{107}{}{别逼我开枪打你。}
### {108}{}{Just keep your distance.}
{108}{}{保持距离。}
### {109}{}{I don't want you near me!}
{109}{}{我不想你靠近我！}
### {110}{}{You'll never be welcome here.}
{110}{}{你在这里永远不受欢迎。}
### {111}{}{Why are you here? Looking for trouble?}
{111}{}{你为什么在这里？找麻烦？}
