### {100}{}{Good day. Can I help you with something?}
{100}{}{你好。我能帮你做点什么吗？}
### {101}{}{Who are you?}
{101}{}{你是谁？}
### {102}{}{What is this place?}
{102}{}{这是什么地方？}
### {103}{}{I don't need anything right now.}
{103}{}{我现在什么都不需要。}
### {104}{}{I'm Andy. Some people call me the plumber because I know so much about water and stuff. You find me a broken pipe, and I'll fix it within a minute.}
{104}{}{我是安迪。有些人叫我水管工，因为我对水和其他东西了解很多。你给我找一根坏管子，我会在一分钟内修好。}
### {105}{}{Yeah, if I find one... Let me ask you something else.}
{105}{}{是的，如果我找到一个。。。让我再问你一件事。}
### {106}{}{Sure thing, just say it.}
{106}{}{当然，说出来就好。}
### {107}{}{This is my workshop, doesn't it look like that?}
{107}{}{这是我的工作室，不是那样吗？}
### {108}{}{It sure does. Do you have anything for sale here?}
{108}{}{确实如此。这里有卖的吗？}
### {109}{}{Not to me. I'm out of here.}
{109}{}{对我来说不是。我要离开这里。}
### {110}{}{I got a lot of stuff. What do you need?}
{110}{}{我有很多东西。你需要什么？}
### {111}{}{A water chip. Do you have one?}
{111}{}{水芯片。你有吗？}
### {112}{}{Actually nothing.}
{112}{}{实际上什么都没有。}
### {113}{}{Water chip, let me see... [trying to remember]. Yeah, I got one... [smiles]. You should consider yourself lucky since this is the last one in working condition. It will cost you though, $1000. You still want it?}
{113}{}{水芯片，让我看看。。。[努力回忆]。是的，我有一个。。。[微笑]。你应该认为自己很幸运，因为这是最后一个处于工作状态的。不过，这将花费你1000美元。你还想要吗？}
### {114}{}{I don't have the money right now.}
{114}{}{我现在没有钱。}
### {115}{}{A thousand bucks? For such an old piece!? That's a bit steep.}
{115}{}{一千块？这么古老的作品！？这有点陡。}
### {116}{}{I didn't come all the way to leave empty handed. Alright, here's the money.}
{116}{}{我大老远来并不是要两手空空地离开。好的，这是钱。}
### {117}{}{Well... I'll regret this but fine... $800, that's my final offer. Any cheaper and I would be giving it away.}
{117}{}{好我会后悔的，但很好$800，这是我的最后报价。再便宜一点，我就把它送人。}
### {118}{}{If you have any problems with it, just bring it back and we'll work something out.}
{118}{}{如果你对它有任何问题，只要把它拿回来，我们就会解决的。}
### {119}{}{I'll keep that in mind.}
{119}{}{我会记住的。}
### {120}{}{About that water chip you sold to me...}
{120}{}{关于你卖给我的水芯片。。。}
### {121}{}{What's wrong with it?}
{121}{}{它怎么了？}
### {122}{}{Piece of crap is broken, that's what's wrong with it.}
{122}{}{一块垃圾碎了，这就是它的问题所在。}
### {123}{}{Damn. I'm sorry, these parts are very sensitive and break easily if not handled properly. Now, I'm not suggesting you did something wrong, these components age over time too. [Looking at the part.] However, I can repair it if you want, for $500?}
{123}{}{该死对不起，这些零件很敏感，如果处理不当很容易断裂。现在，我并不是说你做错了什么，这些组件也会随着时间的推移而老化。[看零件。]但是，如果你愿意，我可以修理它，500美元？}
### {124}{}{(I should have asked for a receipt)... I must be crazy but OK... if you cheat me again...}
{124}{}{（我本该要收据的）。。。我一定疯了，但好吧…如果你再骗我。。。}
### {125}{}{Forget it, I already paid for this! Guess I'll have to help myself to a working one!}
{125}{}{算了，我已经为此付出了代价！我想我得自食其力了！}
### {126}{}{I don't have the money right now, I'll be back.}
{126}{}{我现在没有钱，我会回来的。}
### {127}{}{Please, there's no need for that. Just give me the part and I'll start working on it.}
{127}{}{求你了，没必要那样。只要给我这个角色，我就开始做。}
### {128}{}{[Give him the part.]}
{128}{}{[给他这个角色。]}
### {129}{}{Alright, this is it. [Gives you the part.] That's all I can do. If you excuse me now, I got some work to do. [He goes to the back.]}
{129}{}{好吧，就这样。[给你这个角色。]这就是我所能做的。如果你现在原谅我，我还有一些工作要做。[他走到后面。]}
### {130}{}{[Leave.]}
{130}{}{[离开]}
### {131}{}{Where's my wrench...}
{131}{}{我的扳手在哪里。。。}
### {132}{}{...something is broken...}
{132}{}{…有东西坏了。。。}
### {133}{}{Where's that leak?}
{133}{}{泄漏在哪里？}
### {134}{}{Still in business.}
{134}{}{仍在营业。}
### {135}{}{I have to buy new tools.}
{135}{}{我必须买新工具。}
### {136}{}{So much dirt on this pipe.}
{136}{}{这个管子上有那么多污垢。}
### {137}{}{...not again...}
{137}{}{…不再。。。}
### {138}{}{Where's the plumber when you need one.}
{138}{}{当你需要水管工的时候，水管工在哪里。}
### {139}{}{I could use some help here...}
{139}{}{我需要一些帮助。。。}
### {140}{}{Sorry, but pre-war hardware has its price. If you don't like it try contacting the manufacturer.}
{140}{}{抱歉，战前的硬件是有价格的。如果你不喜欢，试着联系制造商。}
