### {100}{}{Mind your own business!}
{100}{}{管好你自己的事！}
### {101}{}{Where's that drink I asked for?}
{101}{}{我要的饮料在哪里？}
### {102}{}{You should go bother somebody else!}
{102}{}{你应该去麻烦别人！}
### {103}{}{Fuck off, peasant!}
{103}{}{滚，农民！}
### {104}{}{This is no place for your kind.}
{104}{}{这不是适合你这种人的地方。}
### {105}{}{Don't look at me!}
{105}{}{别看我！}
### {106}{}{I don't have time for this.}
{106}{}{我没有时间做这个。}
### {107}{}{Something's not right here!}
{107}{}{这里有点不对劲！}
### {108}{}{Why are those people running?}
{108}{}{那些人为什么要跑？}
### {109}{}{What the hell is this?}
{109}{}{这到底是什么？}
### {110}{}{What the...}
{110}{}{什么。。。}
### {111}{}{Intruder!}
{111}{}{入侵者}
### {112}{}{Get the intruder.}
{112}{}{抓住入侵者。}
### {113}{}{Go, go, go!}
{113}{}{走，走，走！}
### {114}{}{Security breached!}
{114}{}{安全漏洞！}
### {115}{}{What was that?!}
{115}{}{那是什么？！}
### {116}{}{Don't you touch me, you filth.}
{116}{}{你别碰我，你这个废物。}
### {117}{}{Where's that drink I asked for?}
{117}{}{我要的饮料在哪里？}
### {118}{}{Don't bother me, prisoner.}
{118}{}{别打扰我，囚犯。}
### {119}{}{Fuck off, slave!}
{119}{}{滚吧，奴隶！}
### {120}{}{I'll take care of you - later. ::grins::}
{120}{}{我稍后会照顾你的咧嘴笑：}
### {121}{}{Don't look at me!}
{121}{}{别看我！}
### {122}{}{Don't make me punish you.}
{122}{}{不要让我惩罚你。}
