{100}{}{Good day. Can I help you with something?}
{101}{}{Who are you?}
{102}{}{What is this place?}
{103}{}{I don't need anything right now.}
#who are you...
{104}{}{I'm Andy. Some people call me "the plumber" because I know so much about water and stuff. You find me a
 broken pipe, and I'll fix it within a minute.}
{105}{}{Yeah, if I find one... Let me ask you something else.}
#
{106}{}{Sure thing, just say it.}
#what is this place?
{107}{}{This is my workshop, doesn't it look like that?}
{108}{}{It sure does. Do you have anything for sale here?}
{109}{}{Not to me. I'm out of here.}
#for sale...
{110}{}{I got a lot of stuff. What do you need?}
{111}{}{A water chip. Do you have one?}
{112}{}{Actually nothing.}
#
{113}{}{Water chip, let me see... [trying to remember]. Yeah, I got one... [smiles]. You should consider yourself lucky
 since this is the last one in working condition. It will cost you though, $1000. You still want it?}
{114}{}{I don't have the money right now.}
{115}{}{A thousand bucks? For such an old piece!? That's a bit steep.}
{116}{}{I didn't come all the way to leave empty handed. Alright, here's the money.}
#A thousand...
{117}{}{Well... I'll regret this but fine... $800, that's my final offer. Any cheaper and I would be giving it away.}
#
{118}{}{If you have any problems with it, just bring it back and we'll work something out.}
{119}{}{I'll keep that in mind.}
#dude izvalio broken part...
{120}{}{About that water chip you sold to me...}
#
{121}{}{What's wrong with it?}
{122}{}{Piece of crap is broken, that's what's wrong with it.}
#
{123}{}{Damn. I'm sorry, these parts are very sensitive and break easily if not handled properly. Now, I'm not
 suggesting you did something wrong, these components age over time too. [Looking at the part.] However, I can repair
 it if you want, for $500?}
{124}{}{(I should have asked for a receipt)... I must be crazy but OK... if you cheat me again...}
{125}{}{Forget it, I already paid for this! Guess I'll have to help myself to a working one!}
{126}{}{I don't have the money right now, I'll be back.}
#cheat me again...
{127}{}{Please, there's no need for that. Just give me the part and I'll start working on it.}
{128}{}{[Give him the part.]}
#
{129}{}{Alright, this is it. [Gives you the part.] That's all I can do. If you excuse me now, I got some work to do.
 [He goes to the back.]}
{130}{}{[Leave.]}
#
{131}{}{Where's my wrench...}
{132}{}{...something is broken...}
{133}{}{Where's that leak?}
{134}{}{Still in business.}
{135}{}{I have to buy new tools.}
{136}{}{So much dirt on this pipe.}
{137}{}{...not again...}
{138}{}{Where's the plumber when you need one.}
{139}{}{I could use some help here...}
#
{140}{}{Sorry, but pre-war hardware has its price. If you don't like it try contacting the manufacturer.}
