### {100}{}{The door is using some strange electronic lock mechanism.}
{100}{}{门使用了某种奇怪的电子锁机制。}
### {101}{}{The storage door is electronically secured. You can't seem to break it.}
{101}{}{储物箱门采用电子方式固定。你似乎无法打破它。}
### {102}{}{This lock is electronically secured. You can't seem to open it. May need some clearance code or gadget to break it.}
{102}{}{这把锁是电子锁。你似乎无法打开它。可能需要一些许可码或小工具来破解它。}
### {103}{}{[Chance to avoid detection: Sneak: }
{103}{}{[躲避侦查的机会：潜行：}
### {104}{}{You've unlocked the door swiftly and without complications.}
{104}{}{你很快就打开了门，没有任何复杂的情况。}
### {105}{}{You have failed to disable the lock.}
{105}{}{您未能禁用锁定。}
### {106}{}{[Sneak: }
{106}{}{[偷偷摸摸：}
### {107}{}{That does nothing.}
{107}{}{这毫无作用。}
### {108}{}{You see: the supply room door.}
{108}{}{你看：供应室的门。}
### {109}{}{You see: the door to the arsenal.}
{109}{}{你看：军火库的门。}
### {110}{}{A heavy blast door with a security lock.}
{110}{}{带安全锁的重型防爆门。}
### {111}{}{The door is electronically secured.}
{111}{}{门是用电子装置固定的。}
### {112}{}{The door is open.}
{112}{}{门是开着的。}
