### {100}{}{Good day.}
{100}{}{你好。}
### {101}{}{Want to rent a room?}
{101}{}{想租个房间吗？}
### {102}{}{Sorry, we're full at the moment.}
{102}{}{对不起，我们现在客满了。}
### {103}{}{No empty rooms right now.}
{103}{}{现在没有空房间。}
### {104}{}{Come back some other time if you are looking to rent a room.}
{104}{}{如果你想租个房间，改天再来吧。}
### {105}{}{Looking for an empty room?}
{105}{}{找空房间吗？}
### {106}{}{Don't kill me please.}
{106}{}{请不要杀了我。}
### {107}{}{I don't want to die.}
{107}{}{我不想死。}
### {108}{}{Just leave me alone.}
{108}{}{别管我。}
