### {100}{}{Hey there stranger, new in town?}
{100}{}{嘿，陌生人，新来的？}
### {101}{}{Yep, and you are...?}
{101}{}{是的，你是。。。？}
### {102}{}{Sure, this is my first time here.}
{102}{}{当然，这是我第一次来这里。}
### {103}{}{I'm Darren and I'm guarding this bridge, nothing more. [Breaks into a beaming smile.] That's the best damn answer I've given in months. People just walk by, never say a thing. When they see someone with a gun, they immediately assume trouble and stay quiet. They just don't get it that I'm here to prevent that. So, what brings you here stranger?}
{103}{}{我是达伦，我守护着这座桥，没有别的。[突然露出灿烂的笑容。]这是我几个月来给出的最好的答案。人们只是路过，什么也不说。当他们看到有人拿着枪时，他们立刻承担了麻烦并保持沉默。他们只是不明白我来这里是为了防止这种情况发生。那么，是什么把你带到这里来的陌生人？}
### {104}{}{I travel a lot, came from the... east [you point]. I'm kinda interested... [smile]... in that gold you have around here... What can you tell me about this town?}
{104}{}{我经常旅行，来自。。。东方[你指的是]。我有点感兴趣。。。[微笑]。。。在你身边的金子里。。。关于这个小镇，你能告诉我什么？}
### {105}{}{I stopped by to get some supplies, maybe a place for the night. What exactly is your job?}
{105}{}{我顺道去买些补给品，也许是个过夜的地方。你的工作到底是什么？}
### {106}{}{I'm the sheriff's deputy. I've been working here for a few years now. This may seem boring at first but let me tell you something, it turned out to be unexpectedly profitable. You see, a town of this size attracts traders and travelers from hundreds of miles around. And where there are goods there are bandits following them, who then choose to camp in the surrounding woodland. Some of these groups bring serious firepower, but... [He smiles.]}
{106}{}{我是警长的副手。我已经在这里工作了几年了。这一开始可能看起来很无聊，但让我告诉你，它出乎意料地有利可图。你看，这样大的城镇吸引了数百英里外的商人和游客。在有货物的地方，有土匪跟着他们，然后他们选择在周围的林地露营。其中一些团体拥有强大的火力，但是。。。[他笑了。]}
### {107}{}{But...?}
{107}{}{但是}
### {108}{}{We got the brains. We have several snipers, hidden somewhere, covering the area. After the dust settles, all we have to do is to get rid of the bodies and collect the good stuff... sell some of it to the military, the rest to traders, it pays well enough.}
{108}{}{我们有头脑。我们有几个狙击手，藏在某个地方，掩护着这个地区。尘埃落定后，我们所要做的就是清除尸体，收集好东西。。。把其中一部分卖给军方，剩下的卖给贸易商，这样就足够划算了。}
### {109}{}{What kind of weapons do you sell to the military?}
{109}{}{你向军队出售什么样的武器？}
### {110}{}{Almost everything we pick up from these dead assholes. Small arms, grenades, even flamethrowers... lots of stuff I tell ya.}
{110}{}{我们从这些死混蛋身上学到的几乎所有东西。小武器，手榴弹，甚至火焰喷射器。。。我告诉你很多事情。}
### {111}{}{Do you keep some of those weapons?}
{111}{}{你有那些武器吗？}
### {112}{}{Where's that military base located?}
{112}{}{那个军事基地在哪里？}
### {113}{}{Thanks for the info.}
{113}{}{谢谢你提供的信息。}
### {114}{}{Well, I'm limited to what I can carry which is mostly ammo but if I would come across an interesting piece, why not. It's not like someone is going to rise from the dead and ask for his weapon back. But if someone does, maybe we're already in luck as they can only use their teeth. [Laughs.] Either way, I stick with my rifle here.}
{114}{}{嗯，我只能携带弹药，但如果我能遇到一件有趣的东西，为什么不呢。这并不是说有人会从死里复活并要求归还他的武器。但如果有人这样做了，也许我们已经很幸运了，因为他们只能用牙齿。[笑]不管怎样，我都会把步枪留在这里。}
### {115}{}{Right, let me ask you something else then.}
{115}{}{好吧，那我再问你一件事。}
### {116}{}{Sure, whatever I can help you with.}
{116}{}{当然，不管我能帮你什么。}
### {117}{}{About those weapons you were speaking of...}
{117}{}{关于你所说的那些武器。。。}
### {118}{}{What can you tell me about this town?}
{118}{}{关于这个小镇，你能告诉我什么？}
### {119}{}{Actually, there's nothing I want to ask you.}
{119}{}{事实上，我没有什么想问你的。}
### {120}{}{Nice to see you again. How can I help you?}
{120}{}{很高兴再次见到你。我能帮你什么？}
### {121}{}{I can't tell you much since I'm mostly on duty, either guarding the bridge or walking the perimeter further out. I rarely take a stroll through town. [He smiles.] You can ask the sheriff, though, he's more resourceful in that regard than me. I'm sure he will be delighted to have a little chat with you... and dozen others, every single day. [Laughs.]}
{121}{}{我不能告诉你太多，因为我大部分时间都在值班，要么守着桥，要么走得更远。我很少在城里散步。[他笑了笑。]不过你可以问警长，他在这方面比我更足智多谋。我相信他会很高兴和你聊一聊。。。每天都有十几个人。[大笑。]}
### {122}{}{It's on the western outskirts of town... Why do you want to know?}
{122}{}{它在城市的西郊。。。你为什么想知道？}
### {123}{}{I'm interested in buying some high tech equipment from them.}
{123}{}{我有兴趣从他们那里买一些高科技设备。}
### {124}{}{I was thinking about sneaking into their base and have a good look at that armory.}
{124}{}{我想偷偷溜进他们的基地，好好看看那个军械库。}
### {125}{}{[Smiles.] Well, good luck with that. They don't allow civilians even near the place. You have to be either military or someone from the law enforcement. Anyway, [whispering] just between us, I don't like those guys too much but their money is as good as any other. You know, speaking of business, mine started to involve more risk as bandits became better armed and organized. So I wanted to ask for a favor, in return I can get you something you'll find useful... like an access card for that military base, interested?}
{125}{}{[微笑]好吧，祝你好运。他们甚至不允许平民靠近这个地方。你必须要么是军人，要么是执法部门的人。不管怎样，只是在我们之间窃窃私语，我不太喜欢那些家伙，但他们的钱和其他人一样好。你知道，说到商业，随着土匪武装和组织的加强，我的风险开始增加。所以我想请你帮个忙，作为回报，我可以给你一些你会觉得有用的东西。。。比如那个军事基地的出入卡，感兴趣吗？}
### {126}{}{Alright, what's on your mind?}
{126}{}{好吧，你在想什么？}
### {127}{}{You better hand over that access card or I'll have to tell the sheriff about your little business here.}
{127}{}{你最好把出入卡交出来，否则我得把你在这里的小事情告诉警长。}
### {128}{}{Like I said, the threat to our society has increased. We manage to compensate our lack of manpower with better gear, but those things cost, and are quite rare these days. I thought you have a better chance of finding some of the stuff we need. Friend of mine suggested I get metal armor, said it's way better and durable than this leather stuff so I would like to start with that. Normally I ask one of my colleagues to do this or go by myself, but now it's too risky to leave my post. I can count on you, right?}
{128}{}{正如我所说，对我们社会的威胁已经增加。我们设法用更好的装备来弥补人力不足，但这些东西很贵，而且现在很少见。我以为你有更好的机会找到我们需要的东西。我的一个朋友建议我买金属盔甲，说它比这种皮革更好耐用，所以我想从它开始。通常我会让我的一位同事这样做，或者自己去，但现在离开我的岗位风险太大了。我可以指望你，对吧？}
### {129}{}{No problem. I'll be back with that armor.}
{129}{}{没问题。我会带着那件盔甲回来的。}
### {130}{}{So, did you find the metal armor we talked about?}
{130}{}{那么，你找到我们谈论的金属盔甲了吗？}
### {131}{}{Not yet.}
{131}{}{还没有。}
### {132}{}{Sure thing, take a look. [Give him the metal armor.]}
{132}{}{当然，看看。[把金属盔甲给他。]}
### {133}{}{[Looks at the armor.] That's some fine piece of equipment. I hope I can fit in. [Smiles]... Alright, this is for you. [He carefully slips you the access card wrapped in a piece of paper, while shaking your hand.] Just put it in your pocket... don't look around, someone is always watching...}
{133}{}{[看看盔甲。]这是一件很好的装备。我希望我能适应。[微笑]。。。好的，这是给你的。[他一边和你握手，一边小心地把包在纸里的门禁卡递给你。]把它放进你的口袋里。。。不要到处看，总有人在看。。。}
### {134}{}{Right...}
{134}{}{正确的}
### {135}{}{Yes, I remember. What do you want to know?}
{135}{}{是的，我记得。你想知道什么？}
### {136}{}{Thanks, man. I feel great in this armor. Now I can polish it every day. ::He smiles:: Take care.}
{136}{}{谢谢，伙计。我穿上这件盔甲感觉好极了。现在我可以每天打磨了他笑着说：“保重。}
### {137}{}{How are you...}
{137}{}{你好吗}
### {138}{}{Hear any rumors lately?}
{138}{}{最近听到什么传言了吗？}
### {139}{}{Got anything to report?}
{139}{}{有什么要报告的吗？}
### {140}{}{You can talk to the sheriff.}
{140}{}{你可以和警长谈谈。}
### {141}{}{How do you like our town?}
{141}{}{你觉得我们的小镇怎么样？}
### {142}{}{If there is any trouble, just let me know.}
{142}{}{如果有什么麻烦，请告诉我。}
### {143}{}{Can you help me improve my shooting skills?}
{143}{}{你能帮我提高投篮技术吗？}
### {144}{}{Well, you seem proficient enough. I don't think there's much you could learn from me.}
{144}{}{嗯，你似乎足够熟练了。我不认为你能从我身上学到什么。}
### {145}{}{Alright then, thanks anyway.}
{145}{}{好吧，不管怎样，谢谢。}
### {146}{}{Actually, I have something better... I can give you this book. Saves both time and ammo. [Smiles.] If you don't mind some light reading, that's the stuff for you.}
{146}{}{事实上，我有更好的。。。我可以把这本书给你。节省时间和弹药。[微笑]如果你不介意轻松阅读，那就是适合你的东西。}
### {147}{}{Alright, thanks.}
{147}{}{好的，谢谢。}
### {148}{}{About that armor you need...}
{148}{}{关于你需要的盔甲。。。}
### {149}{}{Have you seen any patrols from that prison on the west coast?}
{149}{}{你见过西海岸那所监狱的巡逻队吗？}
### {150}{}{Hmm... Well, I've heard about them but never actually seen any. Personally I don't see the reason why anyone from the west coast would bother coming all the way over here... Why do you ask?}
{150}{}{嗯…嗯，我听说过它们，但从来没有见过。就我个人而言，我不明白为什么有人会从西海岸来这里。。。你为什么问？}
### {151}{}{I've heard they are looking for a group of escaped criminals. I thought I'd better warn you.}
{151}{}{我听说他们在找一群逃犯。我想我最好警告你。}
### {152}{}{Some dangerous criminals were seen heading this way and my job is to find them.}
{152}{}{有人看到一些危险的罪犯朝这边走去，我的工作就是找到他们。}
### {153}{}{Thanks for the tip. If you come across any trouble while you're here, better report it to the sheriff because I'm already fully stretched out here.}
{153}{}{谢谢你的小费。如果你在这里遇到任何麻烦，最好向警长报告，因为我在这里已经筋疲力尽了。}
### {154}{}{Alright.}
{154}{}{好吧}
### {155}{}{I don't want to question what you do for a living but don't expect to have a friendly welcome here if you're hellbent on causing trouble. However, if you come across any, you'd better report it to the sheriff.}
{155}{}{我不想质疑你以什么为生，但如果你一心想制造麻烦，也不要指望在这里受到友好的欢迎。然而，如果你遇到任何情况，你最好向警长报告。}
### {156}{}{Will do.}
{156}{}{会的。}
### {157}{}{I believe you already asked me that. Like I said, I haven't seen any since, hmm... ever.}
{157}{}{我相信你已经问过我了。就像我说的，从那以后我再也没见过，嗯……从来没有。}
### {158}{}{I see.}
{158}{}{我明白了。}
### {159}{}{You have some serious explaining to do! What the hell happened!?}
{159}{}{你有一些严肃的解释要做！到底发生了什么！？}
### {160}{}{Easy, I don't want any trouble...}
{160}{}{别紧张，我不想惹麻烦。。。}
### {161}{}{Calm down, let's go to the sheriff's office, I'll explain everything...}
{161}{}{冷静点，我们去警长办公室，我会解释一切。。。}
### {162}{}{Mind your own business, will you!?}
{162}{}{管好你自己的事，好吗！？}
### {163}{}{You already got yourself in trouble by talking to the wrong people. But this is far more serious. The sheriff is going to demand some answers and you better tell him! Let's go!}
{163}{}{你已经因为和错误的人说话而惹上麻烦了。但这要严重得多。警长要问一些答案，你最好告诉他！我们走吧！}
### {164}{}{[Go.]}
{164}{}{[去]}
### {165}{}{To hell with you!}
{165}{}{见鬼去吧！}
### {166}{}{Move along.}
{166}{}{继续前进。}
### {167}{}{Nothing to see here.}
{167}{}{这里没什么可看的。}
### {168}{}{Keep moving.}
{168}{}{继续前进。}
### {169}{}{...wait, I'm not done yet... [shakes your hand firmly while smiling]. Show it to the front gate guard and don't ask too many questions, they just might let you in. In case they don't, it's not my problem anymore, and you better come up with a believable backup story... Anyway, a friend of mine told me that, supposedly, most pre-war military security systems used these cards. So you may find it very useful at some point. [Takes a quick look around.] Okay, time for you to be about your business, I've got a lot of work here. Take care.}
{169}{}{…等等，我还没说完。。。[微笑时坚定地握手]。把它展示给前门警卫，不要问太多问题，他们可能会让你进去。如果他们不这样做，那就不再是我的问题了，你最好拿出一个可信的后备故事。。。无论如何，我的一个朋友告诉我，据说战前大多数军事安全系统都使用这些卡。所以你可能会发现它在某个时候非常有用。[快速环顾四周。]好吧，是时候让你谈谈你的事情了，我在这里有很多工作要做。小心。}
### {170}{}{Great, thanks.}
{170}{}{太好了，谢谢。}
### {171}{}{Sure thing, take a look. [Give him the metal armor MKII.]}
{171}{}{当然，看看。[给他金属盔甲MKII。]}
