### {100}{}{Enter command:}
{100}{}{输入命令：}
### {101}{}{[Log in]}
{101}{}{[登录]}
### {102}{}{Status: in order, Database load: success}
{102}{}{状态：按顺序，数据库加载：成功}
### {103}{}{[Search database]}
{103}{}{[搜索数据库]}
### {104}{}{[Log off]}
{104}{}{[注销]}
### {105}{}{Search criterion:}
{105}{}{搜索条件：}
### {106}{}{Medical information.}
{106}{}{医疗信息。}
### {107}{}{Scientific information.}
{107}{}{科学信息。}
### {108}{}{Weaponry information.}
{108}{}{武器信息。}
### {109}{}{Species.}
{109}{}{种}
### {111}{}{[More]}
{111}{}{[更多]}
### {112}{}{[Log off]}
{112}{}{[注销]}
### {113}{}{[Back to main menu]}
{113}{}{[返回主菜单]}
### {114}{}{[Back]}
{114}{}{[返回]}
### {115}{}{[You spend some time searching, but find nothing useful.]}
{115}{}{[你花了一些时间搜索，但没有发现任何有用的东西。]}
### {116}{}{[After a few hours of searching you find some valuable medical information and gain some skills.]}
{116}{}{[经过几个小时的搜索，你会发现一些有价值的医疗信息，并获得一些技能。]}
### {117}{}{[After a few hours of searching you find some valuable scientific information and gain some skills.]}
{117}{}{[经过几个小时的搜索，你会发现一些有价值的科学信息，并获得一些技能。]}
### {118}{}{[After a few hours of searching you find some valuable information about weapons and gain some skills.]}
{118}{}{[经过几个小时的搜索，你会发现一些关于武器的宝贵信息，并获得一些技能。]}
### {119}{}{Status: in order, Database load: error}
{119}{}{状态：按顺序，数据库加载：错误}
### {120}{}{...No information about selected criterion...}
{120}{}{…没有关于所选条件的信息。。。}
### {121}{}{(You have already learned everything you could.)}
{121}{}{（你已经学到了你能学到的一切。）}
