### {100}{}{Greetings sir. ID check, your security card please.}
{100}{}{你好，先生。身份证，请出示您的安全卡。}
### {101}{}{ID... What's that?}
{101}{}{ID…那是什么？}
### {102}{}{I guess I don't have it.}
{102}{}{我想我没有。}
### {103}{}{That's a personal security card, every member of our unit has one. You have to show me your ID card, if it passes the clearance check then you can go in.}
{103}{}{这是一张个人安全卡，我们单位的每个成员都有一张。你必须给我看你的身份证，如果它通过了检查，你就可以进去了。}
### {104}{}{Sorry, I don't have one. I will be on my way then.}
{104}{}{对不起，我没有。那我就上路了。}
### {105}{}{Why didn't you just say so... Let me show you my ID.}
{105}{}{你为什么不这么说…让我给你看看我的身份证。}
### {106}{}{Alright, here you go...}
{106}{}{好吧，给你。。。}
### {107}{}{OK, everything seems to be in order. You can enter.}
{107}{}{好的，一切似乎都井然有序。您可以输入。}
### {108}{}{Sorry sir, chemicals of a recreational or lethal nature are not allowed inside the base. You'll have to leave them if you want to go inside. You can use that locker, it's closely guarded.}
{108}{}{对不起，先生，基地内不允许使用娱乐性或致命性的化学品。如果你想进去，就得离开他们。你可以用那个储物柜，它有严密的防护。}
### {109}{}{Hey, where do you think you're going!?}
{109}{}{嘿，你以为你要去哪里！？}
### {110}{}{Just looking around.}
{110}{}{只是环顾四周。}
### {111}{}{Sorry, I'll be going now.}
{111}{}{对不起，我现在就走。}
### {112}{}{Please, sir, this is a military facility, do your sightseeing somewhere else!}
{112}{}{请，先生，这是一个军事设施，到别的地方去观光吧！}
### {113}{}{I don't think so.}
{113}{}{我不这么认为。}
### {114}{}{Sorry, I'll be going now.}
{114}{}{对不起，我现在就走。}
### {115}{}{Thanks.}
{115}{}{谢谢}
### {116}{}{Alright, guess I'll have to trust you.}
{116}{}{好吧，我想我得相信你。}
### {117}{}{Leave my stuff alone, I'll put them away somewhere else...}
{117}{}{别管我的东西，我会把它们放在别的地方。。。}
### {118}{}{You'll have to put away that weapon.}
{118}{}{你必须把武器收起来。}
### {119}{}{Put away your weapon. Now!}
{119}{}{收起你的武器。现在}
### {120}{}{Going out, sir?}
{120}{}{出去，先生？}
### {121}{}{Yep.}
{121}{}{是的。}
### {122}{}{Hey, wait... [Looking at the plasma pistol you have just stolen.] Where did you get this?}
{122}{}{嘿，等等。。。[看着你刚刚偷来的等离子手枪。]你从哪里得到的？}
### {123}{}{The captain gave it to me...?}
{123}{}{船长给我的。。。？}
### {124}{}{That's a... gift, for my birthday.}
{124}{}{这是我生日的礼物。}
### {125}{}{Hmm... Wait here. [Talking over the radio.] Yes sir, I got the subject with me... [You hear some static coming from the speaker... suddenly he turns off the radio.] Sir, you'll have to hand over that item you have.}
{125}{}{嗯…在这里等着。[通过无线电交谈。]是的，先生，我带上了主题…[你听到扬声器传来一些静电……突然他关掉了收音机。]先生，你必须交出你的那件东西。}
### {126}{}{What if I keep it!?}
{126}{}{如果我留着呢！？}
### {127}{}{Uh... sure, I wasn't planning to keep it.}
{127}{}{嗯当然，我没打算保留它。}
### {128}{}{Your access to this base has been revoked. My orders are to escort you to the front gate and give you a warning. Sir, stay away from this base, or you'll be shot!}
{128}{}{您对此基地的访问权限已被吊销。我的命令是护送你到前门并警告你。先生，离这个基地远点，否则你会中弹的！}
### {129}{}{[Leave.]}
{129}{}{[离开]}
### {130}{}{Sorry sir, it's night time. Nobody can enter or exit at this hour.}
{130}{}{对不起，先生，现在是晚上。这个时候没有人可以进出。}
### {131}{}{Alright.}
{131}{}{好吧}
### {132}{}{Not yet.}
{132}{}{还没有。}
### {133}{}{Thieves are not allowed inside!}
{133}{}{小偷是不允许进入的！}
### {134}{}{Don't even think of sneaking in!}
{134}{}{别想偷偷溜进去！}
### {135}{}{Back off, traitor!}
{135}{}{退后，叛徒！}
### {136}{}{Don't make me shoot you!}
{136}{}{别逼我开枪打你！}
### {137}{}{You sir, stop right now! I have orders to search your inventory.}
{137}{}{你，先生，现在停下来！我有订单要搜索你的库存。}
### {138}{}{Uh... what for?}
{138}{}{嗯为何}
### {139}{}{Sorry, time to go...}
{139}{}{对不起，该走了。。。}
