### {100}{}{Alright, we're gonna sneak up on them. Lead on.}
{100}{}{好吧，我们要偷袭他们。诱骗}
### {101}{}{OK, follow me.}
{101}{}{好的，跟我来。}
### {102}{}{Looks like we're done here. You helped me a lot. I think I can trust you, partner. Listen carefully now, this operation was necessary, but not entirely legal. I haven't told anybody about it, I suggest you do the same. This way we ensure everyone's safe. Take care now.}
{102}{}{看来我们完了。你帮了我很多。我想我可以信任你，伙伴。现在仔细听，这个操作是必要的，但并不完全合法。我还没有告诉任何人这件事，我建议你也这样做。这样我们就能确保每个人的安全。现在小心。}
### {103}{}{You too, so long.}
{103}{}{你也是，太久了。}
### {104}{}{Great job!}
{104}{}{干得好！}
### {105}{}{Nice work, partner.}
{105}{}{干得好，伙计。}
### {106}{}{Watch yourself.}
{106}{}{注意自己。}
### {107}{}{Let's go.}
{107}{}{我们走吧。}
### {108}{}{No time to waste.}
{108}{}{没有时间浪费。}
### {109}{}{Quickly!}
{109}{}{迅速地}
