{100}{}{Stranger.}
{101}{}{Is this a store?}
{102}{}{Yep, and I'd rather keep it that way, grandpa.}
#
{103}{}{Well, [he looks around,] very well could be. In fact, I'd be damned if it ain't. Got coins?}
{104}{}{Yes, let's trade.}
{105}{}{Yeah, but... I'd better hold onto 'em. Last copper and all. Might get lucky at the slots.}
#
{106}{}{Seen you before. Up for trade?}
{107}{}{Sure.}
{108}{}{Do you ever have something interesting to say?}
{109}{}{I'm still looking.}
#
{110}{}{Nope.}
{111}{}{Never mind then, let's trade.}
{112}{}{Guess not.}
#
{113}{}{You see: an grumpy old man.}
{114}{}{He's running the shop and is eyeing you with a mixture of suspicion and annoyance.}
#
{115}{}{Did you forget something?}
{116}{}{I see myself out.}
