{100}{}{I'm busy.}
{101}{}{Good luck, stranger.}
{102}{}{Enjoying your stay here?}
{103}{}{Check those slots, they are really good.}
{104}{}{Mary is always glad to have new customers.}
{105}{}{You're gonna love it!}
#dude touched door...
{106}{}{Please, stay away from that door.}
#again touched...
{107}{}{Last warning sir, don't make me use this.}
#final...
{108}{}{Sorry sir, now I have to shoot you.}
