### {100}{}{Good day. I'm Justin. With that out of the way, can I help you with something?}
{100}{}{你好。我是贾斯汀。别这样，我能帮你点什么吗？}
### {101}{}{What do you do here?}
{101}{}{你在这里做什么？}
### {102}{}{Nope.}
{102}{}{没有。}
### {103}{}{As a scientist I conduct experiments on various fields of research. Most of it about robotics and cybernetics. Lately, I've been constructing a robot, more like an office assistant... but I encountered some difficulties...}
{103}{}{作为一名科学家，我在各个研究领域进行实验。大部分是关于机器人和控制论。最近，我一直在建造一个机器人，更像是一个办公室助理。。。但我遇到了一些困难。。。}
### {104}{}{Sounds interesting, can I help in any way?}
{104}{}{听起来很有趣，我能帮忙吗？}
### {105}{}{You could but I'm not sure you're up for all this science stuff. Could be complicated. Still, if you are interested?}
{105}{}{你可以，但我不确定你是否能胜任所有这些科学方面的工作。可能很复杂。不过，如果你感兴趣的话？}
### {106}{}{Just say it.}
{106}{}{说吧。}
### {107}{}{In that case, I'll leave you to your work.}
{107}{}{那样的话，我就让你自己干吧。}
### {108}{}{Robot design is complex and requires the use of some unconventional parts. So I started experimenting with biological replacements and their performance is even better than their mechanical counterparts. They are more aligned to our natural habitat because they don't rust, break or jam... Well, they do age, but I think that can be sorted out.}
{108}{}{机器人的设计很复杂，需要使用一些非常规的零件。所以我开始试验生物替代品，它们的性能甚至比机械替代品更好。它们更接近我们的自然栖息地，因为它们不会生锈、断裂或堵塞。。。嗯，他们确实变老了，但我认为这是可以解决的。}
### {109}{}{Point being?}
{109}{}{要点是什么？}
### {110}{}{There's a biological gel made especially for the purpose of preserving biological parts. This brainchild which dates back to the 20th century could save the day. Considering that this contribution could be invaluable to my project I'll probably need some. Point being, can you somehow get it for me?}
{110}{}{有一种生物凝胶是专门为保存生物部分而制作的。这个可以追溯到20世纪的创意可以拯救这一天。考虑到这些贡献对我的项目来说是非常宝贵的，我可能需要一些。重点是，你能为我找到它吗？}
### {111}{}{I can try. Know where I could find some?}
{111}{}{我可以试试。知道我在哪里能找到吗？}
### {112}{}{Is there some reward?}
{112}{}{有什么奖励吗？}
### {113}{}{Sounds complicated, you better hire somebody else.}
{113}{}{听起来很复杂，你最好雇佣其他人。}
### {114}{}{Back then it was used by the military... That reminds me, hmm... [He presses a finger against his forehead, looks like he's thinking really hard.] I've read something about an old medical research center from before the war.  That huge building in the middle of nowhere. [He points to far south.] That may be a start. Otherwise, I heard some rumors  about an old military base near Farmers Town. [He marks a spot on your map.] According to a traveler, they had an incident with poisonous gas spreading all over the place. The base was abandoned and sealed shortly after. They sure  took most of the equipment with them... but perhaps they left some behind...}
{114}{}{当时它被军方使用。。。这让我想起了，嗯…[他用手指抵住额头，看起来很认真地思考。]我读到了一些关于战前一个古老的医学研究中心的文章。在一个荒无人烟的地方那座巨大的建筑。[他指向遥远的南方。]这可能是一个开始。除此之外，我听到了一些关于农民镇附近一个旧军事基地的传言。[他在你的地图上标出了一个地方。]据一位旅行者说，他们发生了一起有毒气体弥漫的事故。该基地不久后被废弃并封闭。他们确实带走了大部分设备。。。但也许他们留下了一些。。。}
### {115}{}{Right, what about that gas thing? Is it safe now?}
{115}{}{好吧，那汽油怎么办？现在安全吗？}
### {116}{}{Without a proper air sealed suit? I doubt it. Although, it has been quite a while, maybe the molecules have dissolved into simpler compounds, forming... [He stops and a quick smile appears on his face.] Still with me?}
{116}{}{没有合适的气密套装？我对此表示怀疑。尽管已经有很长一段时间了，也许分子已经溶解成更简单的化合物，形成。。。[他停了下来，脸上露出了快速的微笑。]还和我在一起吗？}
### {117}{}{Yeah, here's one subatomic question. Where can I get the appropriate suit?}
{117}{}{是的，这里有一个亚原子问题。我在哪里可以买到合适的西装？}
### {118}{}{If you are willing to get me what I need, I'm prepared to give you equipment, money... I ain't got much but you should be satisfied. What do you say?}
{118}{}{如果你愿意给我我需要的东西，我准备给你设备，钱。。。我没有多少，但你应该满意。你怎么说？}
### {119}{}{Hey, you're back. Did you find any of that biological gel I asked you for?}
{119}{}{嘿，你回来了。你找到我要的那种生物凝胶了吗？}
### {120}{}{Nothing yet.}
{120}{}{还没有。}
### {121}{}{Yep, I found a can of this bio-something. Take it...}
{121}{}{是的，我发现了一罐这种生物。拿着。。。}
### {122}{}{This is great. [Looking into the jar you gave him.] Color looks good... [He puts a small tube in the jar and starts mixing it for a second.] Viscosity is good. I will put this on the shelf... Goes here...}
{122}{}{这太棒了。[看着你给他的罐子。]颜色看起来不错。。。[他在罐子里放了一根小管，开始搅拌一秒钟。]粘度很好。我会把这个放在架子上。。。转到这里。。。}
### {123}{}{Yeah, about my reward...}
{123}{}{是的，关于我的奖励。。。}
### {124}{}{Ah yes... Here's $800 and some 10mm ammo for you... Also some special grenades... These are strong so be careful what you use them for. I'm going to test that gel you have brought. Now if you excuse me...}
{124}{}{啊，是的。。。这是800美元和一些10毫米的弹药给你。。。还有一些特殊的手榴弹。。。这些很结实，所以要小心你用它们做什么。我要测试一下你带来的凝胶。现在请原谅。。。}
### {125}{}{Sure, good luck.}
{125}{}{当然，祝你好运。}
### {126}{}{Just got to put this in there...}
{126}{}{只要把这个放在那里。。。}
### {127}{}{...and there should be some progress...}
{127}{}{…应该会有一些进展。。。}
### {128}{}{Haha, I did it... my personal robot!}
{128}{}{哈哈，我做到了…我的私人机器人！}
### {129}{}{Hello there... I'll call you Robo...}
{129}{}{你好。。。我叫你罗伯。。。}
### {130}{}{Well, I have to program his functions now. It's gonna take some time.}
{130}{}{好吧，我现在必须对他的函数进行编程。这需要一些时间。}
### {131}{}{As you can see, it's going pretty well. Soon, it will be able to talk, move... And who knows what else, this is new even for me... All thanks to you!}
{131}{}{正如你所看到的，一切都很顺利。很快，它将能够说话，移动。。。谁知道呢，这对我来说都是新的……感谢你！}
### {132}{}{I'm glad it works, bye.}
{132}{}{我很高兴它能起作用，再见。}
### {133}{}{You said you don't want to help, so get the hell out of my lab!}
{133}{}{你说你不想帮忙，滚出我的实验室！}
### {134}{}{Alright.}
{134}{}{好吧}
### {135}{}{Why don't you make me!?}
{135}{}{你为什么不让我！？}
### {136}{}{I'm sorry to hear that, I'll be back later.}
{136}{}{听到这个消息我很抱歉，我稍后会回来。}
### {137}{}{We meet again. Something I can help you with?}
{137}{}{我们又见面了。有什么我能帮你的吗？}
### {138}{}{What's that scrap of metal you got there?}
{138}{}{你那里的那块金属碎片是什么？}
### {139}{}{That's my personal robot, and it's not a scrap of metal. As you can see it's not functional at the moment but I have faith in my work.}
{139}{}{那是我的私人机器人，它不是一块金属碎片。正如你所看到的，它目前还没有发挥作用，但我对自己的工作有信心。}
### {140}{}{Amen to that.}
{140}{}{阿门。}
### {141}{}{I haven't seen one for a very long time, if you're looking for a place to search, it's definitely not around here.}
{141}{}{我已经很久没有看到它了，如果你想找个地方搜索，它肯定不在这里。}
### {142}{}{I'll try someplace else then.}
{142}{}{那我就去别的地方试试。}
### {143}{}{Is the robot not fully working, yet?}
{143}{}{机器人还没有完全工作吗？}
### {144}{}{No, I still have to run a few diagnostics, wire up some boards, program its functions... the usual.}
{144}{}{不，我仍然需要运行一些诊断程序，连接一些电路板，对其功能进行编程。。。通常。}
### {145}{}{Mind if I help?}
{145}{}{介意我帮忙吗？}
### {146}{}{As long as you don't break anything, be my guest.}
{146}{}{只要你不打碎任何东西，就当我的客人。}
### {147}{}{You have found bio gel for Justin. You earn 1000 exp. points.}
{147}{}{你为贾斯汀找到了生物凝胶。你可以获得1000经验点。}
### {148}{}{Hey, I've did it! A fully working AI, it can talk, think, operate. A great day for science and myself. Thanks for your help.}
{148}{}{嘿，我做到了！一个完全工作的人工智能，它可以说话、思考、操作。对科学和我自己来说都是美好的一天。谢谢你的帮助。}
### {149}{}{I'm a bit busy at the moment.}
{149}{}{我现在有点忙。}
