{100}{}{[You can hear a voice coming from somewhere near, but there's nobody around you.] Hey, over here... }
{101}{}{Who... are you?}
{102}{}{Wow, are you a ghost or something?}
{103}{}{This is too much for me. I'm out of here!}
#
{104}{}{I suppose you have something to ask?}
#
{105}{}{Hmm, you look familiar... Where did you come from?}
{106}{}{Well... Um... I live here.}
{107}{}{If you really want to know... from the prison up north.}
#live here...
{108}{}{Nevermind then. [As you look in the other direction, you feel something squeezing your arm for a second.]
 Well, your number says you don't! But if you ever lie to me again, you'll end up dead. Got it!?}
{109}{}{Oh, don't scare me like that! [You look at your hand and notice some symbols, like a tattoo, but you have
 never seen anything like it in your life.] What the... Where did that come from!?}
# from the prison...
{110}{}{Good enough, now listen. I've been following some leads after the incident. Searching for those fugitives
 proved very difficult. It seems that these people don't trust us so they wouldn't talk. I had to hide here for a while.
 However, I didn't find any information about where those prisoners went.}
{111}{}{Why do you think they were here?}
{112}{}{Did you find any traces at all?}
{113}{}{Interesting. Let me ask you something else.}
#why they were here?
{114}{}{Because this is the nearest populated place after miles of harsh terrain and wasteland. And most of the
 convicts were captured here.}
{115}{}{Any traces so far?}
{116}{}{Interesting. Let me ask you something else.}
#any traces..
{117}{}{Not a damn thing! [Showing his radio.] Surveillance didn't help and this piece of crap broke down. I think
 there's a better way to expand our search.}
{118}{}{Really, what is it?}
{119}{}{Why do you search here?}
{120}{}{Interesting. Let me ask you something else.}
#what is it...
{121}{}{I thought about sending somebody to other towns could be a solution, but there is a little problem. I have
 nobody to send. I would go myself but there's too much going on here, so I have to stay in case someone shows up...}
{122}{}{Well, maybe I can help?}
{123}{}{I don't know.}
#well...
{124}{}{Hmm... I guess you could. Here's what you are going to do. I want you to track down those fugitives and bring
 them back where they belong. If you can't make them walk back here then I don't want them walking ever again! Also
 consider bringing me some proof if you decide to actually do something. Just get this job done!}
{125}{}{Is there some reward?}
{126}{}{I'm on it.}
#reward...
{127}{}{Hey, not so fast. We can discuss that after I see some evidence.}
{128}{}{Sure thing.}
#
{129}{}{Want to help us and find those fugitives?}
{130}{}{Will do.}
{131}{}{Nope.}
#
{132}{}{Anything useful on those escaped criminals?}
{133}{}{I found one of them, Scott. Looks like somebody found him before me. He was already dead when I came.
 I found this prison tags on his corpse. [Hand him the tags.]}
{134}{}{Sorry, no clue.}
#
{135}{}{Who are you, if I may ask?}
# spirit or something...
{136}{}{What a stupid question. If i was a spirit, the wind would blow me away, right? Don't insult my intelligence!}
{137}{}{Sorry, can I ask you something.}
{138}{}{Maybe I could blow you away, asshole!}
#
{139}{}{About that job...}
#
{140}{}{Here's what you are going to do. I want you to track down those fugitives and bring them back where they
 belong. If you can't make them walk back here then I don't want them walking ever again! Also consider bringing me
 some proof if you decide to actually do something. Are we clear about that!?}
#
{141}{}{I'm sorry but you can't help me.}
{142}{}{This is beyond your rat-brain understanding.}
{143}{}{Beat it, scum!}
{144}{}{You said you live here... You want to die here too!}
{145}{}{There's nothing for you to worry about, just back off!}
#
{146}{}{About what?}
#after 133 answer...
{147}{}{[Closely examining the tags.] These are Scott's, alright. I know he has companions, but better something than
 nothing. His buddies are going to be pissed off when they find out. And you make sure they don't or there would be
 trouble for all of us. If you come across any of them... Better run, unless you have a rocket launcher! [Laughs.]}
{148}{}{Very funny, I'll keep that in mind.}
#
{149}{}{I already told you who I am and what my job is. More, you don't need to know.}
{150}{}{Sorry, can I ask you something else?}
#
{151}{}{And what about my reward?}
#
{152}{}{Your job was also to find all of his companions. Scott alone is worthless to me so no reward for you and don't
 piss me off, pal! Now beat it!}
{153}{}{Alright, I'm going.}
{154}{}{I'm going to change your personal description!}
# after109...
{155}{}{Oh god, they sent me a moron. It's a prison mark, every prisoner has one. And keep your damn voice down,
 you're going to blow my cover. Pay attention now... I want you to track down those fugitives and bring them back
 where they belong. If you can't make them walk back here then I don't want them walking ever again! Also consider
 bringing me some proof if you decide to actually do something. Are we clear about that!?}
{156}{}{Alright...}
#after 111
{157}{}{What happened to your radio? They couldn't locate your signal back at the base.}
#
{158}{}{Piece of crap was too noisy so I had to turn it off. As soon as I got here I managed to call for assistance just
 before it broke down. It's good you are here, right on time for your assignment. You have to gather any information
 you can from the locals about those prisoners.}
# answer to 122 (dude wearing cloak)
{159}{}{Hmm... I guess you could. Here's what you are going to do. Track down those fugitives and bring them back
 to me. On a second thought, it doesn't matter if you bring them dead, alive or whatever. Just bring me some proof and
 get this job done. One more thing... Wear something else. You need to look like you're from around here, otherwise
 they would think you're one of us and you could be in trouble.}
# after 109 with cloak on
{160}{}{Oh god, they sent me a moron. It's a prison mark, every prisoner has one. And keep your damn voice down,
 you're going to blow my cover. Pay attention now... I want you to track down those fugitives and bring them back
 where they belong. If you can't make them walk back here then I don't want them walking ever again! Also consider
 bringing me some proof if you decide to actually do something. Are we clear on that!? By the way, change that cloak
 while you're here if you don't want to get yourself killed.}
#floating messages...
{161}{}{...hey you, be quiet...}
{162}{}{...what the...}
{163}{}{Is this some kind of joke? Who's there?}
{164}{}{...they must not see me...}
#
{165}{}{Do it yourself, I'm not helping you!}
#
{166}{}{Then you have to die!}
#
{167}{}{Remember, if you have some useful information... I'm usually here during the night.}
#
{168}{}{I better report this back to headquarters...}
#
{169}{}{Well, the nearest, and most logical place would be Philton. That's where I would go. The major of the town
 and the prison have some shared history. So that may be useful. Still, I wouldn't trust them, they are independent, and
 there are many different powers at work. That's democracy for you. However, the major keeps the place under control,
 for the most part...}
#
{170}{}{You could tell me more about yourself.}
{171}{}{Nothing, sorry.}
{172}{}{Any idea where they could have gone?}
{173}{}{What cities did you have in mind?}
