{100}{}{Are you new here?}
{101}{}{Where did you come from?}
{102}{}{What's your number, pal?}
{103}{}{What are you looking at!}
{104}{}{Get away from me.}
{105}{}{I can't talk with you.}
{106}{}{Who are you?}
#
{107}{}{[He looks preoccupied.] What? Can't you see I'm thinking here...? [Looks at you.] Hey, who are you?}
{108}{}{, I'm new here. Sorry if I'm interrupting something, what are you here for?}
{109}{}{I don't have time for this.}
#
{110}{}{I bet you really want to know... Because of one stupid bastard... Jeff! He planted a knife in my cell just
 before inspection. I figured he was plotting against me after a dispute we had one night when I told him I was
 going to tell the administrator about his plans. Son of a bitch got me first, I can give him credit for that.
 None of that matters now, I'm stuck in here... [sighs.]}
{111}{}{What plans?}
#
{112}{}{You don't know, but... Oh, I forgot, you're the new guy. [Laughs.] Listen, this guy Jeff had a plan about
 jail breaking. We all agreed to be a part of this plan... Back then, it was a simple choice for me. I could have chosen to
 escape or to rot in this place...}
{113}{}{So, what happened?}
#
{114}{}{It started as we planned, but Jeff wasn't aware of that nutcase Scott who ran for it first. Scott jumped over
 the fence and triggered the alarm, almost like he planned to do it. With that alarm sounded, it was every man for
 himself. All hell broke loose... shouting, laser guns blazing all over the place...}
{115}{}{So, Scott escaped, what happened to Jeff?}
#
{116}{}{I could tell Jeff was so pissed off. It was supposed to be a quiet few-man operation but then there was no other
 way but to go all-in. He and a few other guys went over the fence... One of them got stuck half way up, guards shot him
 a few times, [sighs] there was nothing left of him... just a pile of goo hanging down from the fence. I wish that was Jeff,
 not that poor fella...}
{117}{}{Maybe I can help you. So, where's Jeff headed?}
#
{118}{}{Well... the plan was to lay low for a while in a nearby town. But with so much heat going on, I doubt that's
 an option now. You said you could help me... I just don't see how...}
{119}{}{I will tell the administrator about Jeff's involvement and your situation, that should clear things up...}
#
{120}{}{You really want to do that? I mean, that's a huge favor you're doing for me. Hey, I can at least give you some
 useful information... There's a town south-east from here. It's a small community. They used to have a working mine,
 now it's just another god forsaken place. My cousin Sharon used to run a small store there, didn't hear from her in
 years though. But if you need some firearms, you go there... [smiles] and tell her hello from Nill, will ya?}
{121}{}{Sure thing. I'm off to clear this mess.}
#
{122}{}{I'm counting on you man.}
{123}{}{You know what to do.}
{124}{}{You know the truth, tell the others.}
{125}{}{I will have my revenge.}
{126}{}{Just keep it low.}
#
{127}{}{That bastard is gone.}
{128}{}{Thanks again.}
{129}{}{Thanks man.}
#extra answer added after line 119...
{130}{}{I can't be sure about your part in this "scheme", but I sure know that Jeff is guilty.}
#
{131}{}{You just wait!}
{132}{}{I'll be out of here and you'll be the first to know.}
{133}{}{See you outside soon, asshole!}
{134}{}{You better hide in a deep hole when I get out!}
