{100}{}{[He's just standing there, you're not sure he's looking at you because you can't see his face. A strong voice
 suddenly breaks the silence.] So... tell me, how do you feel?}
{101}{}{Fine, I guess. What is this place?}
#
{102}{}{Can't you see all these fences and bars? What does it look like? It's a prison. Unfortunately, the only one that
 survived the war and doesn't even remotely posses enough capacity for all wasteland scum there is. Although, there are
 other prisons but nothing like this one, serving its very own purpose, undisturbed for a very long time. We worked very
 hard to build this place but keeping everything in order, now that's a different story... Since you walked out alive, don't
 fool yourself by thinking you are worth something, but I will offer you a deal...}
{103}{}{Like what?}
#
{104}{}{Recently we had a major security breach. What you need to do is gather any information regarding that
 incident, people involved, inside and outside connections... I want all of it! Needless to say, get yourself familiar with
 the other inmates, get as close as you can to any of the prison gangs and find out what they know and who they hold
 responsible for that incident.}
{105}{}{Alright, when do I start?}
#
{106}{}{As we speak! Here, try this on. [Gives you a leather jacket.] You'll fit right in. Some money will come in
 handy, someone's trust can easily be bought nowadays. We're counting on you. Don't mess it up, this is your one and
 only chance.}
{107}{}{I feel motivated already. I'll be back with the information.}
#
{108}{}{Any progress so far, suspects, anything?}
{109}{}{Prisoner Gary is involved but I can't figure out how. He even warned me that if I tell anyone, I could be
 killed.}
{110}{}{Still no clue about who was involved in the incident.}
#
{113}{}{Hello again.}
{114}{}{Just watch yourself.}
{115}{}{You can look around.}
{116}{}{There's nothing I can do for you.}
{117}{}{Enjoying your stay here?}
#
{118}{}{What if... I refuse to help?}
#refuse...
{119}{}{It's very simple. Either you help us and live another day... or you can refuse and try to walk away. I don’t
 really care whatever you decide.}
{120}{}{Walk away, huh? [Run for it.]}
#
{121}{}{Nill wanted to report that Jeff devised a plan but he got thrown into solitary confinement before he had the
 chance.}
#gary is involved
{124}{}{[Reading some papers.] But... that's impossible, this guy was sitting quietly in his cell during the incident...
 Wait a minute, are you trying to hide something? Or cover up for someone!? If that's the case, you're
 out of luck, prisoner. You are going back, just the way you came in. Guards! Throw this human trash into a cell!}
{125}{}{Shit!}
#
{126}{}{You're dead, you hear me!?}
{127}{}{How did you get in here!}
{128}{}{You damn convict!}
{129}{}{Guards, we've got an intruder!}
#jeff devised a plan
{130}{}{Hm... [Looking at his papers.] This could be the guy we're looking for. Good work, but we have just scratched
 the surface. My outside source gave me a few leads but nothing solid, so you have to meet him on the east side of a
 small place called Miners Town, southeast of here...}
{131}{}{So I'm going out then?}
#
{132}{}{You stupid bastard! You haven't learned anything during your last visit, that's about to change!}
{133}{}{Sure, after I'm done with you!}
#after 101...
{134}{}{Why the hell did you put me through that?}
#put...
{135}{}{I thought you'd understand. Learning some new skills will be very useful once you are all by yourself in the
 wasteland. Behind these walls it's all about survival, isn't that what you've learned here?}
{136}{}{Well, yes...}
{137}{}{Have YOU learned something from torturing people?}
#well...
{138}{}{Then I have nothing more to add... Let me tell you something about this place. It's a prison. Unfortunately,
 the only one that survived the war and doesn't even remotely possess enough capacity for all wasteland scum there is.
 There are other prisons but nothing like this one, serving its very own purpose, undisturbed for a very long time. We
 worked very hard to build this place but keeping everything in order, now that's a different story... Since you walked
 out alive, don't fool yourself by thinking you are worth something, but I will offer you a deal...}
#torturing...
{139}{}{I've been over this so many times before and it still doesn't bring tears to my eyes. If you think hard, you
 might realize we're trying to help. You won't be able to survive without this... call it "training". Once you're alone in
 the wasteland there's only one rule, if you hesitate, you die. If you ever get face to face with death... what would
 you do? Call for help? [Laughs.]}
{140}{}{Right... What can you tell me about this place?}
#after 131...
{141}{}{Yes, but don't get carried away just yet, you haven't heard the rest of the story. My agent informed me he's
 having some trouble with the locals and that was just before I lost contact... Maybe his radio broke down, maybe he got
 distracted or... something else, I don't know. What I need is you to get out there and find answers. All these questions
 are wasting our time.}
{142}{}{Sure, no problem.}
#
{143}{}{And here's something that will help you find him. [He hands you some kind of motion detector.] It detects the
 heat signature of lifeforms, and can even penetrate cloaking devices. Just don't use it too often, it has a limited power
 supply. That's all. I expect your report within every four months. If you fail the detail... I'll send out a warrant for
 your arrest. And there won't be any second chances.}
{144}{}{Fine, I'm gone.}
#come back...
{145}{}{So, you have returned. Does that mean you have something to tell me?}
{146}{}{I'm sorry, what was my job again?}
{147}{}{I think I know where Scott is hiding...}
{148}{}{No, I don't.}
#my job again...
{149}{}{You idiot! [Sighs.] Regarding the escaped convicts... who else do you think I was talking about!? Have you
 done something about it?}
{150}{}{Not much since we spoke last time.}
{151}{}{I'm onto something, just need some more time.}
#scott hiding...
{152}{}{Really, eh... Good for you. So why the hell are you still here!? Go out there and take care of it, and don't
 forget proof that you did it. Standing there mumbling, that won't do us any good!}
{153}{}{I thought you should know... I'm off to finish my job.}
{154}{}{Oh, you are so wrong about that... Let me show you what I mean!}
#148,150,153 & 151...
{155}{}{I want to see some progress here so you better do your job before we meet next time. Remember, you're still
 on probation. If you fail to report within the next four months... I'll send someone after you. Now go!}
{156}{}{Sure, I know.}
#dude late...
{157}{}{You're late! And too late to do anything about it. [Talking to one of the guards.] Escort our friend here to his
 room. [Turns back to you.] As for you, you'll have enough time to think about your crimes. While we'll take care of the
 punishment. Your quarters are ready. Welcome to hell!}
{158}{}{Wait, I can explain...}
#added Scott as a suspect(14.6.2014)
{159}{}{I heard that Scott could be the guy you're looking for. A few other names came up but I guess they are less
 important.}
#
{160}{}{[Pauses for a second, thinking.] You know what I am thinking!? Let me tell you what I'm thinking... we are so
 tired of hearsay statements! I couldn't find a single word in my reports about him doing anything wrong. So [pointing
 at you] you better bring me some evidence, don't make me regret this or... [sighs] there will be consequences. Now
 go!}
{161}{}{I'm having second thoughts about this... I'll take my own chances, you son of a bitch!}
{162}{}{[Leave.]}
#misc.
{163}{}{You have found the prisoners involved in the prison break. You earn 200 exp. points.}
{164}{}{You have failed to use your steal skill.}
{165}{}{[Chance: }
#Scott is dead, back with tags, on time 29.08.2023
{166}{}{I've completed my mission and here's the proof. [Hand him the tags.]}
#Scott is dead, back with tags, time's up
{167}{}{Wait! I didn't come empty-handed, I have these. [Hand him the tags.]}
#166
{168}{}{[Closely examining the tags.] He caused so much trouble but eventually there was no place left to hide. [Looks
 at you.] Since you are quite capable, I prefer to keep you here. [Pauses for a second, thinking.] There's one more thing
 we need to take care of, your reward of course. [Talking to one of the guards.] Show our friend to his quarters.}
{169}{}{Thanks, I guess.}
#
{170}{}{You're late! [Talking to everyone around.] Disobeyed my orders, had to spend extra resources tracking you. [Turns
 back to you.] How do we deal with this situation now?}