### {100}{}{Can you spare any bullets?}
{100}{}{你能腾出子弹吗？}
### {101}{}{Where did you come from?}
{101}{}{你从哪里来的？}
### {102}{}{Can you help us?}
{102}{}{你能帮我们吗？}
### {103}{}{Talk to our leader, not me.}
{103}{}{和我们的领导人谈谈，而不是我。}
### {104}{}{I can't talk to you.}
{104}{}{我不能和你说话。}
### {105}{}{Bother somebody else, okay?!}
{105}{}{打扰别人，好吗？！}
### {106}{}{You're the man!}
{106}{}{你就是那个男人！}
### {107}{}{My thanks to you, stranger.}
{107}{}{谢谢你，陌生人。}
### {108}{}{Now we can breathe easier.}
{108}{}{现在我们可以更轻松地呼吸了。}
### {109}{}{I'm just fine here, thanks.}
{109}{}{我在这里很好，谢谢。}
### {110}{}{You bitch!}
{110}{}{你这个婊子！}
### {111}{}{Go back to your mommy!}
{111}{}{回到你妈妈身边去！}
### {112}{}{No, I'm not the damn boss!}
{112}{}{不，我不是该死的老板！}
### {113}{}{What a stupid...}
{113}{}{多么愚蠢。。。}
### {114}{}{Get outta here!}
{114}{}{滚出去！}
### {115}{}{You heard me!}
{115}{}{你听到了！}
### {116}{}{Is there any beer for me?}
{116}{}{有啤酒给我吗？}
### {117}{}{This place sucks.}
{117}{}{这个地方糟透了。}
### {118}{}{We are hiding in this cave like rats.}
{118}{}{我们像老鼠一样躲在这个山洞里。}
### {119}{}{Just like the old days.}
{119}{}{就像过去一样。}
### {120}{}{If only I had some Nukas.}
{120}{}{如果我有一些努卡就好了。}
### {121}{}{When are we going to get out of this place?}
{121}{}{我们什么时候离开这个地方？}
### {122}{}{I wish I knew what's going on here.}
{122}{}{我真希望我知道这里发生了什么。}
### {123}{}{This sure isn't what I signed up for.}
{123}{}{这肯定不是我报名参加的。}
### {124}{}{Iguana on a stick, that's tasty.}
{124}{}{棒上的鬣蜥，很好吃。}
### {125}{}{Somebody close the fridge, please... Coincidentally, do we have a fridge?!}
{125}{}{有人关上冰箱，请。。。无独有偶，我们有冰箱吗？！}
### {126}{}{I just stand here, I don't get to do anything.}
{126}{}{我只是站在这里，什么也做不了。}
