{100}{}{Report to the administration.}
{101}{}{Move it!}
{102}{}{Don't stop, keep walking!}
{103}{}{Move along.}
{104}{}{Don't just stand there, move it!}
{105}{}{Report to the administration immediately!}
{106}{}{No more answers from me.}
{107}{}{Stop wasting my time, report to the administration!}
{108}{}{Just keep walking.}
#
{109}{}{No weapons here!}
{110}{}{Put away your weapon!}
{111}{}{You are not allowed to carry a weapon here!}
{112}{}{Put away your weapon or I'll have to confiscate it!}
{113}{}{I'm warning you, put your weapon away!}
{114}{}{Put your weapon away! This is your final warning!}
