### {100}{}{God day stranger. What can I do for you?}
{100}{}{天啊，陌生人。我能为你做什么？}
### {101}{}{What is this place?}
{101}{}{这是什么地方？}
### {102}{}{Can I see your stock?}
{102}{}{我能看看你的存货吗？}
### {103}{}{Nothing, later.}
{103}{}{什么都没有。}
### {104}{}{This is the machine parts factory and I'm its supervisor. Name's Owen. It's the biggest factory of its kind on the west coast. We manufacture and sell various machine parts and tools.}
{104}{}{这是机器零件厂，我是它的主管。我叫欧文。这是西海岸同类工厂中最大的一家。我们生产和销售各种机械零件和工具。}
### {105}{}{Who's the owner?}
{105}{}{谁是主人？}
### {106}{}{Show me your stock.}
{106}{}{给我看看你的股票。}
### {107}{}{Can I ask you something else?}
{107}{}{我能问你别的事吗？}
### {108}{}{Mayor Donson. In fact, he owns half of the city. His investments and good management helped this city a lot.}
{108}{}{唐森市长。事实上，他拥有这座城市的一半。他的投资和良好的管理对这座城市帮助很大。}
### {109}{}{Where can I find mayor Donson?}
{109}{}{我在哪里可以找到唐森市长？}
### {110}{}{Thanks. I wanted to ask you something else.}
{110}{}{谢谢我想问你别的事。}
### {111}{}{His house is just across the way. If you intend to see him, keep in mind that he's a very busy man and usually doesn't have the time to meet people, sometimes for weeks.}
{111}{}{他的房子就在马路对面。如果你打算去见他，请记住，他是一个非常忙碌的人，通常没有时间与人见面，有时长达数周。}
### {112}{}{A very busy man you say? Thanks, I'll be on my way.}
{112}{}{你说他很忙？谢谢，我马上就来。}
### {113}{}{Of course. What would it be?}
{113}{}{当然会是什么？}
### {114}{}{Pleasure doing business with you. Come back anytime.}
{114}{}{很高兴和你做生意。随时回来。}
### {115}{}{Sure thing.}
{115}{}{当然可以}
### {116}{}{Leonard from Duntown sent me to ask you what happened to his shipment.}
{116}{}{邓敦的伦纳德派我来问你他的货怎么了。}
### {117}{}{Well... it's bad, I had no idea things can go so wrong. The shipment was intercepted by a group of bandits, about two hundred miles from here...}
{117}{}{好很糟糕，我不知道事情会出这么大的问题。这批货物被一群土匪拦截，距离这里大约200英里。。。}
### {118}{}{What happened?}
{118}{}{发生了什么？}
### {119}{}{Before we even got there... we could see a wide column of smoke from a distance. Usually a bad indicator... but nothing could prepare us for the horror afterwards. We sensed the smell of burning flesh... and soon, the wind started to blow and cleared the smoke. What we saw... was terrible. Dead bodies and blood everywhere, like a real slaughterhouse.}
{119}{}{在我们到达那里之前。。。我们从远处可以看到一股浓烟。通常是一个糟糕的指标。。。但没有什么能让我们为之后的恐怖做好准备。我们闻到了肉烧焦的味道。。。很快，风开始刮起来，把烟吹散了。我们看到的。。。太可怕了。到处都是尸体和血迹，就像一个真正的屠宰场。}
### {120}{}{Damn, what happened to the shipment?}
{120}{}{该死，这批货怎么了？}
### {121}{}{Most of the ore containers were gone... some got left behind, probably in a hurry. They took everything else of value: money, weapons, personal belongings, even stripped some of the bodies... At least we know they all fought bravely, died from gunshot wounds...}
{121}{}{大多数矿石集装箱都不见了。。。有些人可能是在匆忙中被落下的。他们拿走了其他一切有价值的东西：金钱、武器、个人物品，甚至剥去了一些尸体。。。至少我们知道他们都勇敢地战斗，死于枪伤。。。}
### {122}{}{I should go tell this to Leonard, see you later.}
{122}{}{我应该把这件事告诉伦纳德，回头见。}
### {123}{}{I want to take another look at your goods.}
{123}{}{我想再看一眼你们的货物。}
### {124}{}{Welcome back. What would it be this time?}
{124}{}{欢迎回来。这次会是什么？}
### {125}{}{We don't work at night time.}
{125}{}{我们晚上不工作。}
### {126}{}{You should come back during day time.}
{126}{}{你应该在白天回来。}
### {127}{}{I don't support your evil cause! Get the hell out!}
{127}{}{我不支持你的邪恶事业！滚出去！}
### {128}{}{We are closed for you, for good!}
{128}{}{我们永远为你关闭！}
### {129}{}{I don't deal with criminals!}
{129}{}{我不对付罪犯！}
### {130}{}{Do you sell replacement parts for ore processing machines?}
{130}{}{你们卖矿石加工机器的替换零件吗？}
### {131}{}{Well, I have some old ones. Demand for those on the market is... rare these days. Are you looking for something specific or...?}
{131}{}{嗯，我有一些旧的。如今市场上对这些产品的需求……很少。你在找什么特别的东西还是。。。？}
### {132}{}{Uh... I don't know, the whole damn thing is just huge...}
{132}{}{嗯我不知道，整个该死的事情太大了。。。}
### {133}{}{Well, the processing unit works slower than usual...}
{133}{}{嗯，处理单元的工作速度比平时慢。。。}
### {134}{}{I think it has something to do with the control unit.}
{134}{}{我认为这与控制单元有关。}
### {135}{}{Power supply unit is my best guess.}
{135}{}{电源装置是我的最佳猜测。}
### {136}{}{I'm afraid I don't know what I'm talking about. I'll talk to you later.}
{136}{}{恐怕我不知道自己在说什么。我稍后再和你谈谈。}
### {137}{}{About those machine parts I need...}
{137}{}{关于我需要的那些机器零件。。。}
### {138}{}{Alright, what do you need?}
{138}{}{好吧，你需要什么？}
### {139}{}{I'm sorry but that doesn't help at all. If you excuse me, I have other matters to attend to.}
{139}{}{我很抱歉，但那根本没用。对不起，我还有其他事情要处理。}
### {140}{}{Sure. I'll come back later.}
{140}{}{当然我稍后再回来。}
### {141}{}{I checked the control unit, it turns out there's a faulty module...}
{141}{}{我检查了控制单元，结果发现有一个故障模块。。。}
### {142}{}{Will a gun to your forehead help!?}
{142}{}{用枪指着你的额头会有帮助吗！？}
### {143}{}{Module you say... I remember I kept one for rainy days. [Takes something, what seems to be a dusty old circuit board, from his locker. Looking closely at it.] This is it. Most of the control units have one of these installed, like the one in our water station, although it's a different type.}
{143}{}{模块你说。。。我记得我留了一个以备不时之需。[从他的储物柜里拿了一些东西，似乎是一块满是灰尘的旧电路板。仔细看。]就是这样。大多数控制单元都安装了其中一个，就像我们供水站的那个，尽管它是不同的类型。}
### {144}{}{Does it work?}
{144}{}{它有效吗？}
### {145}{}{Are you sure this is the right module? It does look like some useless junk.}
{145}{}{你确定这是正确的模块吗？它看起来确实像一些无用的垃圾。}
### {146}{}{Sure, how much?}
{146}{}{当然，多少钱？}
### {147}{}{Absolutely. It's old but more important, not damaged.}
{147}{}{绝对地它很旧，但更重要，没有损坏。}
### {148}{}{Fine, I'll take your word for it. How much?}
{148}{}{好吧，我相信你的话。多少钱？}
### {149}{}{I'll leave it for later.}
{149}{}{我以后再做。}
### {150}{}{Well, you know that old saying, one man's junk is another man's treasure. It's your call. Take it or leave it.}
{150}{}{你知道那句老话，一个人的垃圾就是另一个人的财富。这是你的决定。要么接受，要么离开。}
### {151}{}{$1000 for it. No bargain and no return policy.}
{151}{}{1000美元。没有优惠和退货政策。}
### {152}{}{(It seems like a rip off, but it's your only option.) I'll take it.}
{152}{}{（这看起来像是敲竹杠，但这是你唯一的选择。）我会接受的。}
### {153}{}{Do you know of any uranium ore supplier?}
{153}{}{你知道有铀矿石供应商吗？}
### {154}{}{Actually, I do. I supply a nuclear power plant with replacement parts. They do use uranium, naturally, but I know they are also in the market of selling. Well, at least they used to be. With the ongoing caravan raids and peoples' growing distrust, business has become rather exclusive. Still, if you want to try and convince them they are in the north-east. I can show you on the map.}
{154}{}{事实上，我有。我为一个核电站提供替换部件。他们当然使用铀，但我知道他们也在销售市场上。至少过去是这样。随着商队的突袭和人们越来越不信任，商业变得相当排外。不过，如果你想说服他们，他们在东北部。我可以在地图上给你看。}
### {155}{}{Thanks.}
{155}{}{谢谢}
