### {100}{}{Are you new in town?}
{100}{}{你是新来的吗？}
### {101}{}{Haven't seen you before.}
{101}{}{以前没见过你。}
### {102}{}{Usually tribals come here looking for food.}
{102}{}{通常部落会来这里寻找食物。}
### {103}{}{Are you a tribal of some sort?}
{103}{}{你是某种部落吗？}
### {104}{}{We all work in the power plant.}
{104}{}{我们都在发电厂工作。}
### {105}{}{Ever had a thought about how boring you are?}
{105}{}{有没有想过你有多无聊？}
### {106}{}{We don't like strangers at all.}
{106}{}{我们一点也不喜欢陌生人。}
### {107}{}{This happens to be my house and you are bothering me!}
{107}{}{这恰好是我的房子，你打扰我了！}
### {108}{}{I have nothing to say.}
{108}{}{我无话可说。}
### {109}{}{This is no place for you.}
{109}{}{这里不适合你。}
### {110}{}{I'm sure we could get along.}
{110}{}{我相信我们可以相处。}
### {111}{}{Well, I was wrong about you.}
{111}{}{嗯，我错了。}
### {112}{}{Glad to have you here.}
{112}{}{很高兴你在这里。}
### {113}{}{Your help is really appreciated.}
{113}{}{非常感谢你的帮助。}
### {114}{}{We owe you for this.}
{114}{}{我们欠你的。}
### {115}{}{You have my thanks, traveler.}
{115}{}{谢谢你，旅行家。}
### {116}{}{Damn savage!}
{116}{}{该死的野蛮人！}
### {117}{}{You murderer!}
{117}{}{你这个杀人犯！}
### {118}{}{Who do you think you are... killing people...}
{118}{}{你以为你是谁。。。杀人。。。}
### {119}{}{Please don't kill me!}
{119}{}{请不要杀我！}
### {120}{}{I don't want to die.}
{120}{}{我不想死。}
### {121}{}{Just get away from me.}
{121}{}{离我远点。}
### {122}{}{Don't come any closer.}
{122}{}{别再靠近了。}
### {123}{}{Don't touch that door!}
{123}{}{不要碰那扇门！}
### {124}{}{Stop that!}
{124}{}{住手！}
