### {100}{}{Hi, stranger. I'm Sebastian and this would be my... office. Is there any particular reason why you came here?}
{100}{}{嗨，陌生人。我是塞巴斯蒂安，这将是我的…办公室。你来这里有什么特别的原因吗？}
### {101}{}{Don't know. What do you do?}
{101}{}{不知道。你是做什么的？}
### {102}{}{What is this building?}
{102}{}{这是什么建筑？}
### {103}{}{Nope, have a nice day.}
{103}{}{不，祝你今天愉快。}
### {104}{}{I... do lots of things. Since my early days I played with lockpicks quite often, even learned a few tricks in the meantime. For a while I did small time burglaries, pick pocketing... but I always had a secret obsession with handguns. So I tried a more profitable profession instead. It's amazing how someone can earn a fortune these days just by having a gun and some luck.}
{104}{}{我…做了很多事情。从我早期起，我就经常玩撬锁，甚至在这期间学会了一些技巧。有一段时间，我做过小规模的入室盗窃，扒窃。。。但我一直对手枪有一种隐秘的痴迷。所以我尝试了一个更有利可图的职业。令人惊讶的是，如今一个人只需拥有一把枪和一些运气就能赚大钱。}
### {105}{}{Are you still in the lock-picking business?}
{105}{}{你还在做开锁生意吗？}
### {106}{}{I know a gun is a necessity these days but I don't think luck has anything to do with it.}
{106}{}{我知道现在枪支是必需品，但我认为运气与此无关。}
### {107}{}{Not as much as a few years ago, but from time to time people still ask me to do some dirty work for them. The truth is, I can hardly earn enough these days. Either this town is full of greedy bastards or it's time to move on, or both. [Chuckles.]}
{107}{}{虽然没有几年前那么多，但人们仍然时不时地要求我为他们做一些肮脏的工作。事实是，这些天我挣的钱都快不够了。要么这个小镇到处都是贪婪的混蛋，要么是时候继续前进了，要么两者兼而有之。[咯咯笑。]}
### {108}{}{Interesting. Thanks for your time.}
{108}{}{有趣的谢谢你抽出时间。}
### {109}{}{Hah! [Laughs.] That's what I call a mercenary job. We stopped doing that though. Situation was horrible. At first, the whole easy money idea sounded too good to be true. But in the end, when you add up all the numbers on a piece of paper, cheap death was all you got. Can't look forward to that.}
{109}{}{哈哈！[笑]这就是我所说的雇佣兵工作。不过我们停止了这样做。情况很糟糕。起初，整个轻松赚钱的想法听起来太好了，不可能是真的。但最终，当你把所有的数字加在一张纸上时，你得到的只是廉价的死亡。我不能期待。}
### {110}{}{What happened later?}
{110}{}{后来发生了什么？}
### {111}{}{Couldn't find a more respectable job and we struggled for a while... With no income, it was a matter of time before our group was going to fall apart. Just out of nowhere, came this mayor man and offered us a deal. My guys patrol around the city, take out any bandits or raiders and get paid wages. Well, at least we are doing something useful.}
{111}{}{找不到一份更体面的工作了，我们挣扎了一段时间。。。由于没有收入，我们的团队分崩离析只是时间问题。不知从哪里冒出来，这位市长向我们提供了一笔交易。我的人在城市里巡逻，消灭任何土匪或袭击者，并获得工资。好吧，至少我们正在做一些有用的事情。}
### {112}{}{Yep, let me ask you something else.}
{112}{}{是的，让我再问你一件事。}
### {113}{}{Yeah, you're right about that. I'll be going now.}
{113}{}{是的，你说得对。我现在就去。}
### {114}{}{It used to be the city's council building, but it has been abandoned for some time. The west side is mostly ruined but the whole place is so huge, there is more space than we need. Still, we tried to ask for donations to rebuild the damaged parts of the building...}
{114}{}{它曾经是该市的议会大楼，但已经废弃了一段时间。西侧大部分被毁，但整个地方太大了，空间比我们需要的还多。尽管如此，我们还是试图请求捐款来重建大楼受损的部分。。。}
### {115}{}{Did you get any help?}
{115}{}{你得到什么帮助了吗？}
### {116}{}{Nobody wanted to help. But as always, concerned mayor Donson promised some money... But as time moved on, his support faded slowly like that money he promised. We worked all day and night and didn't get a fucking dime. He will pay eventually for all the people he fooled. As soon as we get our financial situation under control, we are out of here.}
{116}{}{没有人愿意帮忙。但和往常一样，忧心忡忡的市长唐森承诺给一些钱。。。但随着时间的推移，他的支持就像他承诺的那样慢慢消退。我们没日没夜地工作，一分钱也没挣。他最终会为他愚弄的所有人付出代价。一旦我们的财务状况得到控制，我们就离开这里。}
### {117}{}{Thanks for your time.}
{117}{}{谢谢你抽出时间。}
### {118}{}{It was the city's council building, but it has been abandoned for some time. We moved in and tried to raise some money for repairs, but never managed to see it through. We won't be staying here for long though. Things will get better and then we are out of here.}
{118}{}{这是该市的市政大楼，但已经废弃了一段时间。我们搬了进来，试图筹集一些维修费用，但始终未能成功。不过我们不会在这里呆太久。情况会好转的，然后我们离开这里。}
### {119}{}{If you say so. Let me ask you something else.}
{119}{}{如果你这么说的话，让我再问你一件事。}
### {120}{}{Welcome back. Please take a seat and tell me what you want.}
{120}{}{欢迎回来。请坐下，告诉我你想要什么。}
### {121}{}{Ask about what?}
{121}{}{询问什么？}
### {122}{}{Two citizens were killed recently. Do you  know anything about that?}
{122}{}{最近有两名市民被杀。你知道吗？}
### {123}{}{Guess I do, although it depends on what information you are looking for. But it's most likely, we're talking about the same event. Either way, I'll start with what I know and we'll continue from there... Not long ago I saw this terrible thing happening. Two people were killed close to the west side of the building, about one hour after sunset, I'd say. I had my men ordered to remain on their positions for the night because there could be raiders hiding in the forest. So we sat there and watched the whole thing...}
{123}{}{我想是的，尽管这取决于你在寻找什么信息。但最有可能的是，我们谈论的是同一个事件。无论哪种方式，我都会从我所知道的开始，我们将从那里继续。。。不久前，我看到这可怕的事情发生了。日落后大约一小时，两人在大楼西侧附近被杀。我命令我的士兵在他们的阵地上过夜，因为可能有袭击者藏在森林里。所以我们坐在那里看着整件事。。。}
### {124}{}{I need more details, tell me what happened.}
{124}{}{我需要更多的细节，告诉我发生了什么。}
### {125}{}{There were two guys with large suitcases, anxiously waiting for someone. Couple of minutes later, a group of four approached. They exchanged a few small packages which, I suppose, were money or drugs. Then they split up, but after a few dozen feet or so, someone drew a gun and the next thing I know all hell broke loose. Guns flashing all over the forest... Looked like a damn war zone.}
{125}{}{有两个人提着大箱子，焦急地等着人。几分钟后，一组四人走近。他们交换了几个小包裹，我想是钱还是毒品。然后他们分开了，但在几十英尺左右的地方，有人拔出一把枪，接下来我所知道的一切都失控了。枪声响彻整个森林。。。看起来像一个该死的战区。}
### {126}{}{Drug dealers you say...? This is not good at all. Do you know where they came from?}
{126}{}{你说毒贩。。。？这一点都不好。你知道它们是从哪里来的吗？}
### {127}{}{I believe from the south, saw some flashlights from that direction just before they approached the campfire at the meeting point. I'm not sure which way they went later... Like I told you, it was getting dark and the forest is dense in these parts, so it was impossible to track them down.}
{127}{}{我相信从南方，在他们接近集合点的篝火之前，看到了一些来自那个方向的手电筒。我不确定他们后来走了哪条路。。。就像我告诉你的，天快黑了，这些地方的森林很茂密，所以不可能找到他们。}
### {128}{}{Thanks Sebastian, you've been very helpful.}
{128}{}{谢谢Sebastian，你帮了我很大的忙。}
