### {100}{}{Move along.}
{100}{}{继续前进。}
### {101}{}{Are you lost?}
{101}{}{你迷路了吗？}
### {102}{}{If you need directions, talk to Brian.}
{102}{}{如果你需要指引，可以和布莱恩谈谈。}
### {103}{}{I'm not a tourist guide.}
{103}{}{我不是导游。}
### {104}{}{I'm busy.}
{104}{}{我很忙。}
### {105}{}{Can't you see I'm working here?}
{105}{}{你看不出我在这里工作吗？}
### {106}{}{I can't help you.}
{106}{}{我帮不了你。}
### {107}{}{Wrong person pal.}
{107}{}{错人了，伙计。}
