### {100}{}{Well, hello there stranger. Welcome to Canville. I'm Jerry, the sheriff of these parts. Just in case you didn't notice, we have a strict policy against weapon carrying in town, so be careful. Now, anything you have to ask, I would be glad to help.}
{100}{}{你好，陌生人。欢迎来到坎维尔。我是杰瑞，这些地方的治安官。万一你没有注意到，我们有严格的政策禁止携带武器进城，所以要小心。现在，如果你有什么要求，我很乐意帮忙。}
### {101}{}{Is there any place to relax?}
{101}{}{有放松的地方吗？}
### {102}{}{Any shops around here?}
{102}{}{这附近有商店吗？}
### {103}{}{Got any job for me?}
{103}{}{有工作给我吗？}
### {104}{}{What's going on in town?}
{104}{}{城里发生了什么事？}
### {105}{}{Nice to meet you Jerry, see you later.}
{105}{}{很高兴认识你，杰瑞，回头见。}
### {106}{}{Hello again, something I can help you with?}
{106}{}{你好，有什么我能帮你的吗？}
### {107}{}{Not really. If you are looking for entertainment or a place to stay for the night, you're out of luck, this is an industrial town after all. There's a fancy restaurant up north. If you feel hungry or thirsty that's the place for you. Besides that, we don't have any conventional hotels in town. Unless you want to spend a night in one of my two by two rooms. [Laughs.] Just kidding stranger.}
{107}{}{不是。如果你正在寻找娱乐或过夜的地方，那你就运气不好了，毕竟这是一个工业小镇。北边有一家高档餐馆。如果你觉得饿或渴，那就是适合你的地方。除此之外，我们城里没有任何传统的旅馆。除非你想在我的一个两乘两的房间里过夜。[笑]跟陌生人开玩笑。}
### {108}{}{I'll pass, let me ask you something else.}
{108}{}{我会过去的，让我问你别的事。}
### {109}{}{That's a good one. See you later.}
{109}{}{这是一个很好的。回头见。}
### {110}{}{Sure, I will be glad to help.}
{110}{}{当然，我很乐意帮忙。}
### {111}{}{Of course. Ask around, most of these people are workers and traders so I'm sure you'll find anything you need.}
{111}{}{当然问问周围，这些人大多是工人和贸易商，所以我相信你会找到你需要的任何东西。}
### {112}{}{Alright. I'll do that.}
{112}{}{好吧我会那样做的。}
### {113}{}{[Looking at his files.] I think I have something for you. One of the locals is having problems with his brahmin. He claims that they refuse to eat and started behaving weird. He is suspecting that someone is trying to poison his brahmin but he couldn't find any proof in the water or their food.}
{113}{}{[看他的档案。]我想我有东西要给你。一个当地人对他的婆罗门有意见。他声称他们拒绝进食并开始表现怪异。他怀疑有人试图毒害他的婆罗门，但他在水中或他们的食物中找不到任何证据。}
### {114}{}{So, any other possible cause?}
{114}{}{那么，还有其他可能的原因吗？}
### {115}{}{It could be wild dogs, rats... who knows. After all, I can't blame the man for being overly worried. He invested all his money into this. I promised I would check it out but I'm pretty busy around here so I trust you will help if you can, right?}
{115}{}{可能是野狗、老鼠。。。谁知道呢。毕竟，我不能责怪这个男人过于担心。他把所有的钱都投入到这件事上。我答应过我会去看看，但我在这里很忙，所以如果可以的话，我相信你会帮忙的，对吧？}
### {116}{}{Sure, do I get something for this?}
{116}{}{当然，我要买点什么吗？}
### {117}{}{Sorry, I have something else to do right now.}
{117}{}{对不起，我现在还有别的事要做。}
### {118}{}{Well, you can always use some more money, I guess. Listen, I don't expect this to be some wild-goose chase so I can give you $500 for the job.}
{118}{}{嗯，我想你总是可以用更多的钱。听着，我不希望这是一场徒劳的追逐，所以我可以给你500美元来做这份工作。}
### {119}{}{Fair enough. Tell me what has to be done?}
{119}{}{很公平。告诉我该怎么办？}
### {120}{}{Have a nice day, Jerry.}
{120}{}{祝你今天愉快，杰瑞。}
### {121}{}{Alright, his small farm is just east of here. I suspect if anything is happening there, it has to be during the night. So if you head there after sunset you can get a better clue of what's going on.}
{121}{}{好吧，他的小农场就在这里的东边。我怀疑如果那里发生了什么事，那一定是在晚上。因此，如果你在日落后前往那里，你可以更好地了解发生了什么。}
### {122}{}{I'm on it.}
{122}{}{我在上面。}
### {123}{}{About that job?}
{123}{}{关于那份工作？}
### {124}{}{Do you have something to report?}
{124}{}{你有什么要报告的吗？}
### {125}{}{Nothing right now.}
{125}{}{现在什么都没有。}
### {126}{}{A small deathclaw was causing all this trouble. This creature attacked me so I had to defend myself. I assume there's nothing more to do.}
{126}{}{一只小小的死爪引起了这一切的麻烦。这个生物攻击了我，所以我不得不自卫。我想没有什么可做的了。}
### {127}{}{Good work, here's your payment. It's strange though, that deathclaw wandering around... I don't know how it got over the wall. I'll see you later, I have to discuss this matter with the locals.}
{127}{}{干得好，这是你的报酬。奇怪的是，那个死爪四处游荡。。。我不知道它是怎么翻墙的。我待会儿见，我得和当地人讨论一下这件事。}
### {128}{}{All right.}
{128}{}{好吧}
### {129}{}{Well, one of the locals saw a few deathclaws in the forest, not far from here. That's just another confirmation of my suspicions that deathclaws have a lair in one of the forest caverns. One other thing is that small deathclaw you saw within the city walls. This can't be a coincidence so we must face the idea that we're in immediate danger of being overrun...}
{129}{}{一个当地人在离这里不远的森林里看到了几只死爪。这再次证实了我的怀疑，即死亡之爪在森林洞穴中有一个巢穴。另一件事是你在城墙内看到的那个小小的死亡爪。这不可能是巧合，所以我们必须面对被占领的直接危险。。。}
### {130}{}{I agree.}
{130}{}{我同意。}
### {131}{}{I do not agree with you.}
{131}{}{我不同意你的看法。}
### {132}{}{We have decided to deal with the deathclaws before things get out of control, that is, while we still can make a difference. I am gathering all available men for this so I'm asking if you can join us. There's a reward of $500 for every deathclaw we hunt down, to lift people's spirit a bit. I think we'll be ready to go in about a day or so and I expect you to give me an answer until then.}
{132}{}{我们已经决定在事情失控之前处理死亡之爪，也就是说，在我们仍然可以有所作为的时候。我正在召集所有可用的人，所以我想问你是否可以加入我们。我们追捕的每一个死亡爪都有500美元的奖励，以提升人们的精神。我想我们大约一天左右就可以出发了，我希望你在那之前给我一个答案。}
### {133}{}{No need to wait, I'll join.}
{133}{}{不用等，我会加入的。}
### {134}{}{I'll talk to you later.}
{134}{}{我稍后再和你谈谈。}
### {135}{}{Alright, you better collect your gear. We will head out around this time tomorrow. Don't be late or you'll miss all the fun [smiles].}
{135}{}{好吧，你最好收拾好装备。我们将在明天这个时候出发。不要迟到，否则你会错过所有的乐趣[微笑]。}
### {136}{}{I'll try to be here on time.}
{136}{}{我会尽量准时到这里。}
### {137}{}{Well, little bit of everything. We got ourselves a big ore mine which demands a lot of work. Its tunnels are stretching for kilometers and the only way of transportation through them is by simplified railway system. But very few workers go there because people say it's not worth the risk. Some tunnel sections collapsed, no investments whatsoever and the fact that the mine is over two hundred years old, made some say it might be time to shut it down for good.}
{137}{}{嗯，每样东西都有一点点。我们找到了一个需要大量工作的大矿场。它的隧道绵延数公里，唯一的交通方式是通过简化的铁路系统。但很少有工人去那里，因为人们说这不值得冒险。一些隧道段坍塌，没有任何投资，加上该矿已有200多年的历史，一些人说可能是时候永远关闭它了。}
### {138}{}{Interesting, anything else?}
{138}{}{有趣，还有什么吗？}
### {139}{}{Let me ask you something else.}
{139}{}{让我再问你一件事。}
### {140}{}{Thanks, see you later.}
{140}{}{谢谢，回头见。}
### {141}{}{...we used to trade our ore for fuel, but we lost interest because fuel is too expensive and most of our people stopped driving cars. [Smiles.] Our power generators have been modified to use coal as fuel... I know it's not environment friendly but I don't trust these high tech generators. There's also a threat of a different kind, our town is constantly under attack by raiders and other groups so a lot of our resources are traded for weapons.}
{141}{}{……我们过去常常用矿石换燃料，但我们失去了兴趣，因为燃料太贵了，我们大多数人都不再开车了。[微笑]我们的发电机已经被改造成用煤作为燃料。。。我知道它对环境不友好，但我不信任这些高科技发电机。还有一种不同的威胁，我们的城镇不断受到袭击者和其他团体的袭击，所以我们的很多资源都被用来换取武器。}
### {142}{}{Anything else going on?}
{142}{}{还有什么事吗？}
### {143}{}{Let me ask you something else.}
{143}{}{让我再问你一件事。}
### {144}{}{Thanks, see you later.}
{144}{}{谢谢，回头见。}
### {145}{}{Nothing for you to worry about. Come back any time if you need something.}
{145}{}{没什么好担心的。如果你需要什么随时回来。}
### {146}{}{I'll keep that in mind.}
{146}{}{我会记住的。}
### {147}{}{Since we busted the deathclaws, people feel a little safer. The danger always lurks but I'm watching.}
{147}{}{自从我们打破了死亡魔爪，人们感到更安全了。危险总是潜伏着，但我在观望。}
### {148}{}{Good to know. I'll keep in touch.}
{148}{}{很高兴知道。我会保持联系。}
### {149}{}{It's time to head east and join the hunt. Are you going with us?}
{149}{}{是时候往东去参加狩猎了。你和我们一起去吗？}
### {150}{}{Let's go.}
{150}{}{我们走吧。}
### {151}{}{Sorry, I'm going to stay.}
{151}{}{对不起，我要留下来。}
### {152}{}{You're missing all the fun. But have it your way.}
{152}{}{你错过了所有的乐趣。但按你的方式去做。}
### {153}{}{Nothing for now. Come back some other time.}
{153}{}{暂时没有。改天再来吧。}
### {154}{}{Sure thing.}
{154}{}{当然可以}
### {155}{}{I told you about the situation on that farm. Find out what's the problem and you can earn $500, interested?}
{155}{}{我告诉过你农场的情况。找出问题所在，你就能赚500美元，感兴趣吗？}
### {156}{}{All right, let's go.}
{156}{}{好吧，我们走吧。}
### {157}{}{Sorry, I'm going to stay.}
{157}{}{对不起，我要留下来。}
### {158}{}{Look, most of the locals are against my plan to attack the deathclaws. But let me tell you, there's nothing worse than waiting for something bad to happen. If the deathclaws attack us we might not live another day to talk about it. So the best solution could be the simplest one...}
{158}{}{听着，大多数当地人都反对我攻击死亡之爪的计划。但让我告诉你，没有什么比等待不好的事情发生更糟糕的了。如果死亡之爪袭击了我们，我们可能再也活不下去谈论它了。所以最好的解决方案可能是最简单的。。。}
### {159}{}{So, what's your plan?}
{159}{}{那么，你的计划是什么？}
### {160}{}{We are not yet ready to go. If you excuse me I have some work to do.}
{160}{}{我们还没有准备好出发。对不起，我还有工作要做。}
### {161}{}{Sure thing, see you later then.}
{161}{}{当然可以，那晚些时候见。}
### {162}{}{All right then. Looks like we're ready to go. The others are waiting...}
{162}{}{好吧。看来我们已经准备好出发了。其他人正在等待。。。}
### {163}{}{[Follow him...]}
{163}{}{[跟着他。。。]}
### {164}{}{Stick around, I might need your services later...}
{164}{}{留下来，我稍后可能需要你的服务。。。}
