### {100}{}{Hello there, what can Dr. Travis do for you?}
{100}{}{你好，特拉维斯医生能为你做些什么？}
### {101}{}{What can you tell me about this place?}
{101}{}{关于这个地方你能告诉我什么？}
### {102}{}{Got any medical supplies I could trade for?}
{102}{}{有我可以换的医疗用品吗？}
### {103}{}{I'm hurt.}
{103}{}{我受伤了。}
### {104}{}{Nothing.}
{104}{}{没有什么}
### {105}{}{[Clears throat.] Well, big city, lots of people. As you have noticed, most of the locals are workers so every day can potentially be a very busy day. Starting from light wounds to broken bones, it's not easy but I have to thank sheriff Jerry for giving us all the funds we need. Of course, I've got my assistant, helps me a lot but sometimes... it's not enough. That's why I'm always looking for a pair of skilled hands.}
{105}{}{[清嗓子。]嗯，大城市，人很多。正如你所注意到的，大多数当地人都是工人，所以每天都可能是非常繁忙的一天。从轻伤到骨折，这并不容易，但我必须感谢杰瑞警长给了我们所有需要的资金。当然，我有我的助理，帮了我很多忙，但有时。。。这还不够。这就是为什么我总是在寻找一双熟练的手。}
### {106}{}{So, Jerry is paying for all the stuff you need?}
{106}{}{那么，杰瑞在为你需要的东西买单？}
### {107}{}{Got any medicine I could buy?}
{107}{}{我能买到药吗？}
### {108}{}{Yes, he promised he will take care of his people and if Jerry or someone like him wasn't around I doubt we could help all of our patients. Takes a lot of guts to take that much responsibility.}
{108}{}{是的，他承诺会照顾好他的病人，如果杰瑞或像他这样的人不在身边，我怀疑我们能否帮助所有的病人。承担这么多责任需要很大的勇气。}
### {109}{}{You're right. Let me ask you something else.}
{109}{}{你说得对。让我再问你一件事。}
### {110}{}{Medicine, of course. Here's what I have.}
{110}{}{当然是医学。这是我的东西。}
### {111}{}{All right.}
{111}{}{好吧}
### {112}{}{OK, let me see. That'll cost you $100.}
{112}{}{好的，让我看看。那要花你100美元。}
### {113}{}{OK, let me see. That'll cost you $200.}
{113}{}{好的，让我看看。那要花你200美元。}
### {114}{}{OK, let me see. That'll cost you $300.}
{114}{}{好的，让我看看。那要花你300美元。}
### {115}{}{You're pretty messed up, it'll cost you $600.}
{115}{}{你搞砸了，要花600美元。}
### {116}{}{Hmm, this is a serious wound. That'll cost you $500.}
{116}{}{嗯，这是一个严重的伤口。那要花你500美元。}
### {117}{}{Here's the money.}
{117}{}{这是钱。}
### {118}{}{No way doc, that's too much for me.}
{118}{}{不行，医生，这对我来说太过分了。}
### {119}{}{Sorry, don't have the money right now.}
{119}{}{对不起，现在没有钱。}
### {120}{}{Then I can't help you. All our citizens have to pay as well, being an outsider doesn't give you any special rights here.}
{120}{}{那我帮不了你。我们所有的公民都必须付出代价，作为一个局外人并不能给你任何特殊的权利。}
### {121}{}{Feeling better?}
{121}{}{感觉好多了？}
### {122}{}{Much better, thanks doc.}
{122}{}{好多了，谢谢医生。}
### {123}{}{I don't talk with criminals.}
{123}{}{我不和罪犯说话。}
### {124}{}{Go away, I don't want to have any business with you.}
{124}{}{走开，我不想和你有任何生意。}
### {125}{}{Thank you for your time, come back if you need any of my services.}
{125}{}{谢谢你抽出时间，如果你需要我的任何服务，请回来。}
### {126}{}{Thanks doc.}
{126}{}{谢谢医生。}
### {127}{}{Don't do that!}
{127}{}{不要那样做！}
### {128}{}{I'm warning you!}
{128}{}{我警告你！}
### {129}{}{I've received a dose of radiation.}
{129}{}{我受到了一定剂量的辐射。}
### {130}{}{OK, let me see... That'll cost you $100 and one hour in the suspension tank.}
{130}{}{好的，让我看看。。。这将花费你100美元和一个小时的悬架油箱。}
### {131}{}{Wow, you are in serious trouble, kid. It'll cost you $200 and you will have to spend about two hours in the suspension tank.}
{131}{}{哇，你遇到大麻烦了，孩子。这将花费你200美元，你将不得不在悬架油箱里呆上大约两个小时。}
### {132}{}{What were you thinking...? It'll cost you $300 and you will have to spend about two and a half hours in the suspension tank. Now hurry!}
{132}{}{你在想什么。。。？这将花费你300美元，你将不得不在悬架油箱里呆上大约两个半小时。现在快！}
### {133}{}{Of course, what's on your mind?}
{133}{}{当然，你在想什么？}
### {134}{}{Stay away from my locker!}
{134}{}{离我的储物柜远点！}
### {135}{}{There's nothing for you in that locker!}
{135}{}{储物柜里什么都没有！}
### {136}{}{I want to buy some more supplies.}
{136}{}{我想再买一些补给品。}
### {137}{}{What's going on in town?}
{137}{}{城里发生了什么事？}
### {138}{}{Well, I really don't have time to chat with my patients. But I've heard somebody saw a deathclaw just outside the town. However, I'm more worried about injuries occurring in the mine. Workers complain that the management doesn't care about their safety too much. And town patrols often encounter armed bandits near the old fuel station north of here so treating gun wounds became my second specialty... That's all I can tell you for now.}
{138}{}{嗯，我真的没有时间和我的病人聊天。但我听说有人在城外看到了一只死爪。然而，我更担心的是矿井里发生的伤害。工人们抱怨管理层不太关心他们的安全。镇上的巡逻队经常在这里北部的旧加油站附近遇到武装匪徒，所以治疗枪伤成了我的第二专长。。。这就是我现在能告诉你的全部。}
### {139}{}{Let me ask you something else.}
{139}{}{让我再问你一件事。}
### {140}{}{Thanks doc, it was helpful.}
{140}{}{谢谢医生，这很有帮助。}
### {141}{}{Not much since we spoke last time. If you don't require any medical attention, there's nothing more I can do for you right now.}
{141}{}{自从上次我们讲话以来，没有多少。如果你不需要任何医疗护理，我现在就无能为力了。}
### {142}{}{Can I ask you something.}
{142}{}{我能问你一件事吗。}
### {143}{}{Sure, see you later doc.}
{143}{}{当然，医生，回头见。}
### {144}{}{I heard the deathclaws are gone. Although I don't support violence, this was the only way to keep the people from harm. You have my thanks! Now, can I do something for you?}
{144}{}{我听说死爪不见了。虽然我不支持暴力，但这是让人们免受伤害的唯一途径。谢谢你！现在，我能为你做点什么吗？}
### {145}{}{Let me ask you something else.}
{145}{}{让我再问你一件事。}
### {146}{}{Nope. Nothing at this time.}
{146}{}{没有。现在什么都没有。}
### {147}{}{Can you tell me something about the mine?}
{147}{}{你能告诉我一些矿井的情况吗？}
### {148}{}{It's probably the last place on earth you want to be at. The mine is too old and, personally, I don't think it's a safe place to work. Workers complain all the time about poor working conditions, some of them even left the town to search for a better place to live. One thing is for sure, we need that mine to keep this town running. Without it, it wouldn't be long before this place turns to dust.}
{148}{}{这可能是你最不想去的地方。矿井太旧了，就我个人而言，我认为这不是一个安全的工作场所。工人们总是抱怨工作条件差，其中一些人甚至离开小镇去寻找更好的住处。有一点是肯定的，我们需要我的矿来维持这个小镇的运转。如果没有它，这个地方很快就会变成尘土。}
### {149}{}{So, who owns the mine?}
{149}{}{那么，谁拥有这个矿呢？}
### {150}{}{It's a difficult subject, can I ask you something else?}
{150}{}{这是一个很难的话题，我能问你其他问题吗？}
### {151}{}{Thanks for you time doc, see you later.}
{151}{}{谢谢你的时间医生，回头见。}
### {152}{}{Larry. His office is on the west side. [Talking to his assistant.] What, another patient!? Time to go, stay out of trouble.}
{152}{}{拉里。他的办公室在西侧。[和他的助手交谈。]什么，又是一个病人！？该走了，别惹麻烦。}
### {153}{}{Will do, see you later doc.}
{153}{}{好的，医生，回头见。}
### {154}{}{Oh sorry, this is not an appropriate time, I've got some work here. Come visit me some other time.}
{154}{}{哦，对不起，现在不是合适的时间，我有一些工作要做。改天来看我吧。}
### {155}{}{Sure thing doc.}
{155}{}{当然，医生。}
### {156}{}{Anything else going on in town?}
{156}{}{城里还有什么事吗？}
### {157}{}{...hey wait. [He's trying to hear something.] You repaired the water pump?! Yes you did, that noise... It was really getting on my nerves. Thank you for this stranger. [He searches his desk.] I guess some stimpaks will come in handy during your trips through the wasteland. So here you go, I'm sure you'll make good use of them. Take care.}
{157}{}{…嘿，等等。[他试图听到什么。]你修理了水泵？！是的，你做了，那个噪音。。。这真的让我很紧张。谢谢这个陌生人。[他搜查了一下桌子。]我想在你穿越荒原的旅途中，一些刺激会派上用场的。所以给你，我相信你会好好利用它们。小心。}
### {158}{}{I will, thanks doc.}
{158}{}{我会的，谢谢医生。}
### {159}{}{I think I did something to that old water pump, at least the sound is not so annoying anymore...}
{159}{}{我想我对那个旧水泵做了什么，至少声音不再那么烦人了。。。}
### {160}{}{Cracked bone, hmm... Looks bad.}
{160}{}{骨折了，嗯…看起来很糟糕。}
### {161}{}{I told him not to go back there...}
{161}{}{我告诉他不要回那里。。。}
### {162}{}{He should be careful with that kind of injury.}
{162}{}{他应该小心这种伤。}
### {163}{}{...and every time the same thing, will they ever learn?}
{163}{}{……每次都是一样的事情，他们会学到吗？}
### {164}{}{Yes, I can remember my first patient, he was screaming!}
{164}{}{是的，我还记得我的第一个病人，他在尖叫！}
### {165}{}{...and the other one begged me to give him some painkillers.}
{165}{}{…另一个求我给他一些止痛药。}
### {166}{}{...that was the last time I saw him.}
{166}{}{…那是我最后一次见到他。}
### {167}{}{Oh man, I need a rest.}
{167}{}{哦，天哪，我需要休息一下。}
### {168}{}{Where did I put that needle...}
{168}{}{我把针放在哪里了。。。}
### {169}{}{Where's my aspirin...}
{169}{}{我的阿司匹林在哪里。。。}
