#dude neutral...
{100}{}{You want something?}
{101}{}{I guard the mine entrance, what about you?!}
{102}{}{I have a job to do, don't waste my time.}
{103}{}{I don't have time to talk to outsiders.}
#dude accepted...
{104}{}{Good day.}
{105}{}{Can I help you with something?}
{106}{}{Sorry, I'm busy right now.}
{107}{}{I'm doing fine, how about you?}
#dude wants to go down...
{108}{}{Sorry, you can't go down.}
{109}{}{You don't work here, so get out.}
{110}{}{You are not allowed to go down.}
{111}{}{Workers only! You don't look like one.}
#
{112}{}{Everything is fine, there's nothing to be worried about.}
{113}{}{Yes, sir, everything is in order.}
{114}{}{Sure thing, I'm doing just fine.}
