### {100}{}{[You can see he's hurt pretty badly, bloody claw marks all over him. Looks like his body armor is all that's keeping his body parts together. You're having a hard time guessing what happened with the others.] ...oh, it's you... Help. *Cough*. Oh shit, I'm all messed up...}
{100}{}{[你可以看到他伤得很重，到处都是血迹斑斑的爪印。看起来他的防弹衣是他身体各部分的唯一支撑。你很难猜测其他人发生了什么。]…哦，是你。。。帮助*咳嗽。哦，该死，我都搞砸了。。。}
### {101}{}{What happened here?}
{101}{}{这里发生了什么？}
### {102}{}{Those fucking deathclaws... *cough*... they heard us while we were going into the cave... made an ambush. *cough*... the whole damn place is full of them... our guns were too weak. I tried... *cough*... couldn't run for it, the bastard was too fast... [He's still alive but his breathing becomes shallow. He struggles to speak.]}
{102}{}{那些该死的死爪*咳嗽*。。。当我们进入洞穴时，他们听到了我们的声音。。。进行了伏击*咳嗽*。。。整个该死的地方都是他们。。。我们的枪太弱了。我试过了*咳嗽*。。。跑不动了，那个混蛋跑得太快了。。。[他还活着，但呼吸变浅了。他很难说话。]}
### {103}{}{Wait, stay with me Jerry! What can I do?}
{103}{}{等等，跟我来，杰瑞！我能做什么？}
### {104}{}{You... *cough* must stop them... uh, take my backpack... one explosive charge should be enough... place it ghhh... [Coughs, then passes out...]}
{104}{}{你*咳嗽必须停止。。。拿上我的背包。。。一个炸药应该足够了。。。把它放在。。。[咳嗽，然后昏倒…]}
### {105}{}{Hang on Jerry, don't you fucking die... shit!}
{105}{}{抓住杰瑞，你他妈的不要死。。。妈的！}
### {106}{}{It's too late for me...}
{106}{}{对我来说太晚了。。。}
### {107}{}{Get help, blow this fuckin' place up... *cough*.}
{107}{}{寻求帮助，炸掉这个该死的地方*咳嗽。}
### {108}{}{Forget about me. *Cough*. Save the others.}
{108}{}{忘了我。咳嗽。拯救其他人。}
### {109}{}{...alright, we are here. My men are taking positions inside. They are waiting for us, let's go!}
{109}{}{…好吧，我们到了。我的人在里面就位。他们在等我们，走吧！}
### {110}{}{[Exit.]}
{110}{}{[出口]}
### {111}{}{What are you waiting for?}
{111}{}{你还在等什么？}
### {112}{}{We don't have much time.}
{112}{}{我们没有太多时间。}
### {113}{}{We must go now.}
{113}{}{我们现在必须走了。}
### {114}{}{We did it... Jerry. [Sigh.]}
{114}{}{我们做到了…杰瑞。[叹气。]}
