### {100}{}{What are you doing here? This is private property!}
{100}{}{你在这里干什么？这是私人财产！}
### {101}{}{I was told I could buy some... Uh... Slaves here.}
{101}{}{有人告诉我可以买一些。。。嗯这里是奴隶。}
### {102}{}{Who's in charge here?}
{102}{}{谁是这里的负责人？}
### {103}{}{Nothing, I'm just looking around.}
{103}{}{没什么，我只是四处看看。}
### {104}{}{Sorry, I was just going...}
{104}{}{对不起，我正要。。。}
### {105}{}{I think you're at the wrong address, pal! I'm wondering how you walked past the security, but you shouldn't have come here. Start counting some bullets!}
{105}{}{我想你来错地址了，伙计！我想知道你是怎么经过安检的，但你不应该来这里。开始数子弹！}
### {106}{}{You mean, one for you and one for me?}
{106}{}{你是说一个给你一个给我？}
### {107}{}{Are you a fucking retard!? That's the worst excuse I've heard in my life... Time to die, lost one!}
{107}{}{你他妈的是个白痴！？这是我一生中听到的最糟糕的借口。。。该死了，丢了一个！}
### {108}{}{Well, lucky me...}
{108}{}{好吧，我很幸运。。。}
### {109}{}{Yes, you are going... to be wasted!}
{109}{}{是的，你要去。。。浪费！}
### {110}{}{I've got a better idea. Why don't you drop dead, you bastard?!}
{110}{}{我有个更好的主意。你为什么不去死呢，你这个混蛋？！}
### {111}{}{Who wants to know?}
{111}{}{谁想知道？}
### {112}{}{I do. [Make an angry face.]}
{112}{}{我知道。[做一个愤怒的表情。]}
### {113}{}{Well, I was just asking nicely...}
{113}{}{我只是善意地问。。。}
### {114}{}{Actually this was a bad idea, I'm out of here.}
{114}{}{实际上这是个坏主意，我要离开这里。}
### {115}{}{And who the hell are you, the postman?! [Laughs.]}
{115}{}{你到底是谁，邮差？！[大笑。]}
### {116}{}{Hey, I'm well known where I come from. So you show some respect!}
{116}{}{嘿，我从哪里来都很有名。所以你要表现出一些尊重！}
### {117}{}{That's right, and I'm going to kick your ass!}
{117}{}{没错，我要踢你屁股！}
### {118}{}{Alright, you'll get a respectable funeral!}
{118}{}{好吧，你会得到一个体面的葬礼！}
### {119}{}{You're a real fucking asshole!}
{119}{}{你真是个混蛋！}
### {120}{}{Alright, you can go in.}
{120}{}{好的，你可以进去。}
### {121}{}{Thanks.}
{121}{}{谢谢}
### {122}{}{Watch your step, there's a mine field on the west.}
{122}{}{小心脚下，西边有一块雷区。}
### {123}{}{I'm busy here, talk to you later.}
{123}{}{我在这里很忙，待会儿和你谈谈。}
### {124}{}{Be quick about your business.}
{124}{}{做事要快。}
### {125}{}{My boss doesn't like people sniffing around, so do what you have to and leave.}
{125}{}{我的老板不喜欢别人到处窥探，所以你该做什么就离开。}
### {126}{}{You possess a certain item that doesn't belong to you and my boss ordered me to shoot down any thief, including you. Nothing personal, I have to earn my pay, you know. I'll just make sure you don't make any more trouble here!}
{126}{}{你拥有一件不属于你的东西，我的老板命令我击落任何小偷，包括你。没有什么私人的，我必须挣工资，你知道的。我会确保你不会在这里制造任何麻烦！}
### {127}{}{Wait... uh, I'll give it back...}
{127}{}{等待我会还给你的。。。}
### {128}{}{Sure, you people always make me laugh.}
{128}{}{当然，你们总是让我发笑。}
