{100}{}{Hi there, stranger.}
{101}{}{Your first time here?}
{102}{}{Nothing to see here.}
{103}{}{Talk to Leny.}
{104}{}{This is the caravan's office.}
{105}{}{You need anything, stranger, you talk to Leny.}
{106}{}{I can't help you. My boss Leny can answer your questions.}
{107}{}{Seen any deathclaws lately?}
#
{108}{}{Get the hell out of here!}
{109}{}{You're not welcome here.}
{110}{}{You are a dead man!}
{111}{}{Go back to hell!}
{112}{}{Get out of my sight!}
