### {100}{}{You are new here?}
{100}{}{你是新来的吗？}
### {101}{}{I don't know you.}
{101}{}{我不认识你。}
### {102}{}{Who are you.}
{102}{}{你是谁。}
### {103}{}{Where did you come from.}
{103}{}{你从哪里来的。}
### {104}{}{I hope you are not one of those bandits.}
{104}{}{我希望你不是那种土匪。}
### {105}{}{Nice to see you.}
{105}{}{很高兴见到你。}
### {106}{}{You are welcome to stay.}
{106}{}{欢迎你留下来。}
### {107}{}{I think I can trust you.}
{107}{}{我想我可以信任你。}
### {108}{}{Anything I can help you with?}
{108}{}{有什么我能帮你的吗？}
### {109}{}{Hey stranger, nice to see you.}
{109}{}{嘿，陌生人，很高兴见到你。}
### {110}{}{Get away from me.}
{110}{}{离我远点。}
### {111}{}{I don't want to be anywhere near you.}
{111}{}{我不想靠近你。}
### {112}{}{Yeah, we had some folks like you. They are dead now!}
{112}{}{是的，我们有一些像你一样的人。他们现在死了！}
### {113}{}{Your gonna pay for what you did.}
{113}{}{你会为你的所作所为付出代价的。}
### {114}{}{Watch your back!}
{114}{}{小心背后！}
### {115}{}{You better watch yourself.}
{115}{}{你最好小心点。}
