{100}{}{Welcome to my W&A shop, customer. What can I get you?}
{101}{}{What can you tell me about this place?}
{102}{}{Who are you?}
{103}{}{Let me see your stock.}
{104}{}{Nothing, see you later.}
#this place...
{105}{}{W&A, Weapons and Ammo, is the best shop you'll find in these parts. I sell almost everything so take your
 time and tell me what you need.}
{106}{}{Show me what you got.}
{107}{}{Can you upgrade or modify something I have?}
{108}{}{Actually, nothing right now.}
#who are you?
{109}{}{I run this place. I can also repair stuff or modify weapons for a good price. Need any of my services?}
{110}{}{Yes. Do I have something you can work with?}
{111}{}{I want to see your stock.}
{112}{}{I don't need anything right now.}
#upgrade...
#sniper rifle...
{113}{}{I can do something about that sniper rifle. I could replace its frame with lighter materials so you can get some
 more space in your inventory, weapon handling will improve also. It'll cost you $2000.}
{114}{}{Alright, here's $2000.}
{115}{}{I don't have that money right now.}
#sniper done...
{116}{}{Here you go. Looks really nice, you won't regret this.}
{117}{}{I sure hope so.}
#rocket launcher...
{118}{}{I see you got some really big stuff here. I can upgrade your rocket launcher's firing mechanism so it can fire
 faster and more reliably. Say, for $2500 you get this upgrade and a free cleaning.}
{119}{}{Sure, sounds good.}
{120}{}{No way, this is too much for me.}
#flamer...
{121}{}{Well, your flamer could use some attention. I can modify it to burn the fuel more efficiently. It'll cost you
 $2000.}
{122}{}{OK, here's $2000.}
{123}{}{I don't have that money right now, I'll be back.}
#no upgrades at the moment...
{124}{}{Sorry, I can't see anything of interest on you.}
{125}{}{OK, can I ask you something?}
{126}{}{I'll be back some other time then.}
#dude spent all upgrades...
{127}{}{Sorry, I already did everything within my abilities. There's nothing more I can do about your gear.}
{128}{}{Thanks for your time anyway.}
#
{129}{}{Anything else?}
{130}{}{Let me have another look.}
{131}{}{Nothing, see you later.}
#
{132}{}{Sure thing, kind customer.}
#floating message, dude near shop owner...
{133}{}{Hello there, customer. Want to see my stuff?}
{134}{}{I've got some good stuff to offer, want to take a look?}
{135}{}{Nice day for trading, don't you think?}
{136}{}{Check out my stock, it'll only take a minute.}
#bad dude reputation float messages...
{137}{}{I don't like you sneaking around, get out!}
{138}{}{I'm not going to repeat myself, get the fuck out!}
{139}{}{One word from you and I'll order my man to shoot you!}
#box touched...
{140}{}{What the hell do you think you're doing?!}
{141}{}{Don't touch that!}
{142}{}{I don't like what you're doing!}
{143}{}{Hey, that's my stuff!}
{144}{}{Why don't you leave that locker alone!}
