### {100}{}{Hey there, how can I help you?}
{100}{}{嘿，有什么能帮你的吗？}
### {101}{}{What is this place?}
{101}{}{这是什么地方？}
### {102}{}{Nice looking car you got there, is it working?}
{102}{}{你的车很好看，能用吗？}
### {103}{}{Nothing.}
{103}{}{没有什么}
### {104}{}{Well, I used to sell cars, but that was a long time ago. Now I'm looking for junk, old parts, put them together... Try to make something that works. [Laughs.] You see that car there? That's my masterpiece, it took me five years to build it. It's not in good shape though, still have to work on its exhaust system, but it's working.}
{104}{}{我以前卖汽车，但那是很久以前的事了。现在我在找垃圾，旧零件，把它们放在一起。。。试着做一些有用的东西。你看到那辆车了吗？这是我的杰作，我花了五年的时间建造它。虽然它的形状不太好，但它的排气系统仍在工作，但它正在工作。}
### {105}{}{Is it for sale?}
{105}{}{它是待售的吗？}
### {106}{}{Looks good, see you later.}
{106}{}{看起来不错，回头见。}
### {107}{}{Sorry, I want to keep this one. As long as I live, it will be my pride... To remind me how the world used to be a better place to live in. I shouldn't be telling you, but I might have a car for sale. It's in my safe stock, if you want to see, $1000 is my price.}
{107}{}{对不起，我想保留这个。只要我活着，这将是我的骄傲。。。提醒我这个世界曾经是一个更适合生活的地方。我不应该告诉你，但我可能有一辆车要卖。这是我的安全库存，如果你想看的话，1000美元是我的价格。}
### {108}{}{Alright, but it better be something.}
{108}{}{好吧，但最好是一些东西。}
### {109}{}{Let me ask you something first.}
{109}{}{让我先问你一件事。}
### {110}{}{That's too much for me right now. I'll be back.}
{110}{}{这对我来说太过分了。我会回来的。}
### {111}{}{Excellent. This is just an insurance policy, I have to pay my bills you know. Let me show you what you came for.}
{111}{}{杰出的这只是一份保险单，我必须支付我的账单，你知道的。让我给你看看你来干什么。}
### {112}{}{[Follow him...]}
{112}{}{[跟着他。。。]}
### {113}{}{You bet it's working. Although it needs some more work around the exhaust pipes, fuel of course, and a set of tires. I might leave it that way just to make it harder for someone to steal it. Haha, just kidding. However, if you are interested, I've got a working one in my safe stock. If you have $1000 you can see my stock right now.}
{113}{}{你敢打赌它是有效的。尽管它需要在排气管周围做更多的工作，当然还有燃料和一套轮胎。我可能会把它放在那里，只是为了让别人更难偷它。哈哈，开玩笑。不过，如果你感兴趣的话，我的保险箱里有一个可以用的。如果你有1000美元，你现在就可以看到我的股票。}
### {114}{}{Alright, but it better be something good.}
{114}{}{好吧，但最好是好事。}
### {115}{}{Let me ask you something first.}
{115}{}{让我先问你一件事。}
### {116}{}{That's too much for me right now. I'll be back.}
{116}{}{这对我来说太过分了。我会回来的。}
### {117}{}{Sure, what you want to know?}
{117}{}{当然，你想知道什么？}
### {118}{}{Hey, you're back. Need anything?}
{118}{}{嘿，你回来了。需要什么吗？}
### {119}{}{What did you say about that car, is it for sale?}
{119}{}{你对那辆车说了些什么？它是待售的吗？}
### {120}{}{You got a lot of guts to show up here!}
{120}{}{你有勇气来这里！}
### {121}{}{Go away, I don't deal with criminals.}
{121}{}{走开，我不对付罪犯。}
### {122}{}{Your kind is not welcome here!}
{122}{}{这里不欢迎你这种人！}
### {123}{}{You can go back to wherever that is you came from.}
{123}{}{你可以回到你来自的任何地方。}
### {124}{}{I remember you already bought a car. Anyway, you can upgrade your car to run more reliably, add some speed to it... It's a turbo charger and it will cost you $2000, interested?}
{124}{}{我记得你已经买车了。无论如何，你可以升级你的车，使其运行更可靠，增加一些速度……这是一个涡轮增压器，它将花费你2000美元，感兴趣吗？}
### {125}{}{Alright, I can afford that...}
{125}{}{好吧，我负担得起。。。}
### {126}{}{Not really, I have to go now.}
{126}{}{不是，我现在得走了。}
### {127}{}{Stay away from there.}
{127}{}{离那里远点。}
### {128}{}{Hey, I'm still here.}
{128}{}{嘿，我还在这里。}
### {129}{}{Any particular reason for touching that door?}
{129}{}{触摸那扇门有什么特别的原因吗？}
### {130}{}{I told you... Don't waste your words!}
{130}{}{我告诉过你。。。不要浪费你的话！}
### {131}{}{Here you go... just don't drop it, hehe... [Grins.]}
{131}{}{给你。。。只是不要放弃它，呵呵。。。[咧嘴笑。]}
### {132}{}{Right, see you.}
{132}{}{好的，再见。}
### {133}{}{I remember you already bought a car and I sold you that turbocharger. So there's nothing else I can do for you right now.}
{133}{}{我记得你已经买了一辆车，我把涡轮增压器卖给了你。所以我现在没有什么能为你做的了。}
### {134}{}{Some other time then.}
{134}{}{那就改天吧。}
### {135}{}{[Smiles.] Nah, my car kinda runs on its own so there's no need for that fancy thing, which is fine with me.}
{135}{}{[微笑]不，我的车有点独立运行，所以不需要那种花哨的东西，这对我来说很好。}
