### {100}{}{...I've been looking for you. Listen, my boss Aston has a job for you. He said it's something very important so you better head to Golden Valley as soon as possible.}
{100}{}{…我一直在找你。听着，我的老板阿斯顿有一份工作给你。他说这是非常重要的事情，所以你最好尽快前往金谷。}
### {101}{}{Hey wait, did he say what kind of job?}
{101}{}{嘿，等等，他说什么工作？}
### {102}{}{Alright, I'll be there shortly after I finish something here.}
{102}{}{好吧，我在这里做完事情后不久就会到那里。}
### {103}{}{No, he just told me to inform you.}
{103}{}{没有，他只是让我通知你。}
### {104}{}{I'll keep that in mind. Thanks.}
{104}{}{我会记住的。谢谢}
### {105}{}{What?}
{105}{}{什么}
### {106}{}{I've been looking for you too.}
{106}{}{我也一直在找你。}
### {107}{}{I have nothing more to say.}
{107}{}{我没有什么好说的了。}
