{100}{}{...I've been looking for you. Listen, my boss Aston has a job for you. He said it's something very important so
 you better head to Golden Valley as soon as possible.}
{101}{}{Hey wait, did he say what kind of job?}
{102}{}{Alright, I'll be there shortly after I finish something here.}
#kind of job...
{103}{}{No, he just told me to inform you.}
{104}{}{I'll keep that in mind. Thanks.}
#
{105}{}{What?}
{106}{}{I've been looking for you too.}
{107}{}{I have nothing more to say.}
