### {100}{}{You stupid fool! That was the only way out! Oh, my God! They are coming, I... I can hear them! [Shouting madly.] You are not gonna get me!! [He pulls out a stick of dynamite and activates it.]}
{100}{}{你这个愚蠢的傻瓜！那是唯一的出路！天啊！他们来了，我…我能听到他们的声音！你抓不到我！！[他拿出一根炸药并激活了它。]}
### {101}{}{[You try to snatch the dynamite from his grasp...]}
{101}{}{[你试图从他手中抢夺炸药。。。]}
### {102}{}{Oh, shit!}
{102}{}{哦，该死！}
### {103}{}{Ahhhh...!!!}
{103}{}{啊。。。！！！}
### {104}{}{You bastard! You're gonna pay for this!}
{104}{}{你这个混蛋！你要为此付出代价！}
