### {100}{}{You see: the local idiot.}
{100}{}{你看：当地的白痴。}
### {101}{}{You see: Bob? Or Harold?}
{101}{}{你看到了吗：鲍勃？还是哈罗德？}
### {102}{}{A disheveled creature quietly humming and singing to himself. He looks lost.}
{102}{}{一个衣冠不整的生物静静地哼着歌。他看起来迷路了。}
### {103}{}{Have you seen them... have you seen them... THEY ARE HERE! [Turns around.] Who are you?}
{103}{}{你见过他们吗。。。你见过他们吗。。。他们来了！[转过身来。]你是谁？}
### {104}{}{Never mind that. Have you seen any prisoners lately?}
{104}{}{别介意。你最近见过犯人吗？}
### {105}{}{Who is here?}
{105}{}{谁在这儿？}
### {106}{}{[He flinches.] Prisoners? Here? [He suddenly smiles.] We're all prisoners, right? Prisoners of this world, prisoners of the five, no, it's four riders of the apocopopo... lop, what's it called; The end of the world! It's coming, it's coming! The four riders are coming. Dingo, Moon and, eh, Bongo and Terry. They will purge this wasteland for its sins!} #first name is the actual name of an escaped convict{107}{}{Is that so.}
{106}{}{[He flinches.] Prisoners? Here? [He suddenly smiles.] We're all prisoners, right? Prisoners of this world, prisoners of the five, no, it's four riders of the apocopopo... lop, what's it called; The end of the world! It's coming, it's coming! The four riders are coming. Dingo, Moon and, eh, Bongo and Terry. They will purge this wasteland for its sins!} #first name is the actual name of an escaped convict{107}{}{是这样吗。}
### {108}{}{Does your guardian know you're out and about?}
{108}{}{你的监护人知道你在外面吗？}
### {109}{}{The Lord cannot be found unless he wants to. [Giggles.] Run, little puppet, run!}
{109}{}{上帝不想找就找不到。[咯咯笑。]快跑，小木偶，快跑！}
### {110}{}{[Let him be and move on.]}
{110}{}{[让他走吧。]}
### {111}{}{[Make the idiot run.]}
{111}{}{[让那个白痴跑。]}
### {112}{}{The four horseman, the prophecy of old, sent to do the lord's will. They came to punish the evil doers and end the world for its sins. It's the Apocolops! No, the aproco-pops, the apocolopopopo..., the apoco-hopsy-lopsy..., the lopsy-popsy..., [with much effort] the ardropo-hoppo-loppo, the a..., the... [he trails off...]}
{112}{}{那四个骑马的，就是古代的预言，被派去执行耶和华的旨意。他们来到这里是为了惩罚作恶者，结束世界的罪恶。是阿波科洛普斯！不，阿普罗科pop，阿普罗科波popo。。。，apoco hopsy不平衡。。。，不平衡的教皇。。。，[费了很大的劲]阿，阿，阿。。。[他走了…]}
### {113}{}{Do they have a name?}
{113}{}{他们有名字吗？}
### {114}{}{Go on.}
{114}{}{继续}
### {115}{}{Yes, eh, Scooby, Dobby, Maan and, eh, Jeff.} #last two are the actual names of escaped convicts{116}{}{I thought it was war, death, famine and pestilence? Or have they already been here? And your lot of Tom, Dick and Harry are the squad to mop up the cockroaches and radiation?}
{115}{}{Yes, eh, Scooby, Dobby, Maan and, eh, Jeff.} #last two are the actual names of escaped convicts{116}{}{我以为是战争、死亡、饥荒和瘟疫？或者他们已经来过这里了？你的汤姆、迪克和哈利是扫荡蟑螂和辐射的小队吗？}
### {117}{}{[He looks at you in confusion.]}
{117}{}{[他困惑地看着你。]}
### {118}{}{Never mind.}
{118}{}{没关系。}
### {119}{}{They know everything, they see everything. [Whispers.] Trust me, they are organized, their little spies are everywhere, miners, farmers, gold diggers, squirrels... everyone. And they are gathering, watching and waiting, for the time to mount their beasts and ride out to purge the wasteland.}
{119}{}{他们什么都知道，什么都看到。相信我，他们是有组织的，他们的小间谍无处不在，矿工、农民、淘金者、松鼠。。。每个人他们聚集在一起，观看和等待，等待时机骑上他们的野兽，出去清理荒地。}
### {120}{}{Whatever put that into your head?}
{120}{}{你脑子里想的是什么？}
### {121}{}{Gee, how do you even find the courage to stand out here without your tin-foil hat on.}
{121}{}{天啊，你怎么有勇气不戴锡箔帽就站在这里呢。}
### {122}{}{[He reaches up to his head, feeling around in confusion.]}
{122}{}{[他抬起头来，困惑地摸了摸四周。]}
### {123}{}{Got you.}
{123}{}{抓住你了。}
### {124}{}{I've seen them walking into town late at night. The four horseman. They stayed at a tent south of here, left a message and moved out again. Now their couriers are in all corners of the world, spreading the lord's will to purge the wasteland.}
{124}{}{我见过他们深夜走进城里。四个骑手。他们住在这里以南的一个帐篷里，留言后又搬了出去。现在，他们的信使遍布世界的各个角落，传播着上帝的意愿，清除荒原。}
### {125}{}{I'm afraid to ask, but do go on.}
{125}{}{我不敢问，但请继续说下去。}
### {126}{}{Seriously now, *when* and *where* did this happen?}
{126}{}{说真的，这是什么时候在哪里发生的？}
### {127}{}{They seem to have purged your brain already.}
{127}{}{它们似乎已经净化了你的大脑。}
### {128}{}{There is a dark place with vermin inside.} #Miners Town{129}{}{...}
{128}{}{There is a dark place with vermin inside.} #Miners Town{129}{}{...}
### {130}{}{Oh, shut it.}
{130}{}{哦，闭嘴。}
### {131}{}{There's a place where the corn quietly grows but it has no peace.} #Farmers Town#{132}{}{A haunted base, once proud and honorable now abandoned and filled with evil.} #UMB#{133}{}{A golden place that lost its shimmer.} #Golden Valley#{134}{}{A place of power that decays from within.} #Duntown#{135}{}{A large place with too many minds, too many eyes.} #Philton#{136}{}{An old attempt, long forgotten, long lost, now in the dark.} #MRC#{137}{}{A tomb, once to protect, now a prison of body and soul.} #Silting#{138}{}{It's here. When the time comes. Run, little puppet, run!} #Canville{139}{}{What are those places?}
{131}{}{There's a place where the corn quietly grows but it has no peace.} #Farmers Town#{132}{}{A haunted base, once proud and honorable now abandoned and filled with evil.} #UMB#{133}{}{A golden place that lost its shimmer.} #Golden Valley#{134}{}{A place of power that decays from within.} #Duntown#{135}{}{A large place with too many minds, too many eyes.} #Philton#{136}{}{An old attempt, long forgotten, long lost, now in the dark.} #MRC#{137}{}{A tomb, once to protect, now a prison of body and soul.} #Silting#{138}{}{It's here. When the time comes. Run, little puppet, run!} #Canville{139}{}{那些地方是什么？}
### {140}{}{That was very flowery. I guess I should have known I was talking to a fucking poet. What's next, are you going to cut off your ear in a romantic gesture? I have a knife if you need it.   } #spaces needed to force line-break#{141}{}{What places?}
{140}{}{That was very flowery. I guess I should have known I was talking to a fucking poet. What's next, are you going to cut off your ear in a romantic gesture? I have a knife if you need it.   } #spaces needed to force line-break#{141}{}{什么地方？}
### {142}{}{The places you've just listed.}
{142}{}{你刚刚列出的地方。}
### {143}{}{They are places? I don't know any places. [Screws up his eyes.]}
{143}{}{它们是地方？我不认识任何地方。[拧上他的眼睛。]}
### {144}{}{Then where did you hear them?}
{144}{}{那你在哪里听到的？}
### {145}{}{When did what happen? I don't know what happened. [Screws up his eyes.]}
{145}{}{什么时候发生的？我不知道发生了什么。[拧上他的眼睛。]}
### {146}{}{I give up...}
{146}{}{我放弃了。。。}
### {147}{}{Then where did you hear it?}
{147}{}{那你是从哪里听到的？}
### {148}{}{Heard what?}
{148}{}{听到了吗？}
### {149}{}{Noises. Do you hear noises?} #with IN 10{150}{}{Places. Do you know any places?}
{149}{}{Noises. Do you hear noises?} #with IN 10{150}{}{地点。你知道什么地方吗？}
### {151}{}{I heard them. All the miners & farmers, all the anguished souls, shrieking out in terror and then suddenly farting very, very quietly into the night. There will be a reckoning, when the time comes. The oppressed masses are waiting. Waiting for the call to rise. Eternally alert and watchful! Just in case they send a vengeful spirit. We are well prepared and it should give us plenty of time to react, sir. Ring the bell three times! What do you mean Flash Gordon's approaching?! Open fire. All weapons! We removed the symptom, but not the cause! Hail to the King! Hail! Hail! Three times, they double-crossed us, they're coming by land and sea... Hark, and Jesus on a rubber duck! Unwittingly, he trained a dolphin to kill the president.}
{151}{}{我听到了。所有的矿工和农民，所有痛苦的灵魂，在恐惧中尖叫，然后突然非常非常安静地放屁到深夜。到时候会有一个清算。被压迫的群众正在等待。等待电话响起。永远保持警惕！以防他们派出复仇的精灵。我们已经做好了充分的准备，这应该给我们足够的时间做出反应，先生。按三下钟！你说闪电侠戈登要来了是什么意思？！开火。所有武器！我们消除了症状，但没有消除原因！向国王致敬！冰雹冰雹他们三次越过我们，从陆地和海上过来。。。哈克，上帝在一只橡皮鸭上！无意中，他训练了一只海豚来杀死总统。}
### {152}{}{It's been fun, but I really need to go now. Bye.}
{152}{}{这很有趣，但我现在真的需要走了。再见}
### {153}{}{Got any more?}
{153}{}{还有吗？}
### {154}{}{[Breathes in.] There is NOTHING more wretched under the sun than you Gods! You feed yourself poorly with sacrifices and incense. And would STARVE, if beggars and children wouldn't be hopeful fools. Here am I. Creating beings after my image. A race that is equal to me. To laugh. To cry. And to rejoice. And NOT to honor you. AS I DO! [coughs...] My heart stood still his name was BILL! The tragedy of human existence is not to be the master of its own creation. Nice try, she said. But no more buttered scones for me, I'm off playing the grand piano. Hundred little notes of never to be finished work, scattered all over the place, like his failing mind. He couldn't sit on a chair, you know, but neither could his eldest son, now picture that at the dinner table, on the one end the father keeps falling off and on the other his eldest son.}
{154}{}{【深呼吸】在太阳底下，没有什么比你们这些神更悲惨的了！你用祭品和熏香来养活自己。如果乞丐和孩子们不是满怀希望的傻瓜，他们会饿死的。我在这里。按照我的形象创造生命。一个与我平等的种族。笑。哭。并为此感到高兴。而不是为了尊重你。和我一样！[咳嗽…]我的心静止了——他的名字叫比尔！人类生存的悲剧不是成为自己创造的主人。“尝试得不错，”她说。但我再也不用奶油烤饼了，我要去弹大钢琴了。一百张永远无法完成的小纸条，散落在各处，就像他那颗失败的心。你知道，他不能坐在椅子上，但他的大儿子也不能，现在想象一下，在餐桌上，父亲一头不停地摔倒，另一头是他的大儿子。}
### {155}{}{Fascinating. Do go on.}
{155}{}{极有吸引力的请继续。}
### {156}{}{Flash, Flash I love you, but we only have fourteen hours the save the universe! [checks watch.] It's the people who don't pay their TV-license against the Nazis! Harold was a clever sheep. We were talking about mutual assured destruction and emotional responsibility. I couldn't remember my name so I called myself Bob. It's weird being a Bob but I get used to it. Guess, I have, too. Oh, come on darling, be realistic demand the impossible. Phoebus! A Goat? Phoebus! Emotions: An agitation or disturbance of the mind. [Sings.] I've seen blue skies, through the tears, and I realize, I'm going home. [Stops.] Bang! Bang! You're dead... but... That is not dead what endless rests, 'till time itself finds endless death. Nork! She rules the atomic wasteland! O, Soeur Marie-Therese des Batignolles...}
{156}{}{闪电侠，闪电侠我爱你，但我们只有十四个小时的时间来拯救宇宙！[查看手表]是那些不支付电视执照的人反对纳粹！哈罗德是一只聪明的绵羊。我们谈论的是相互保证的毁灭和情感上的责任。我记不起自己的名字了，所以我叫自己鲍勃。做鲍勃很奇怪，但我已经习惯了。我想，我也习惯了。哦，来吧，亲爱的，现实要求不可能。Phoebus！山羊？Phoebus！情绪：精神上的激动或紊乱。我透过泪水看到了蓝天，我意识到，我要回家了。[停下来。]砰！猛敲你死了。。。但是那并不是死，而是无休止的休息，直到时间本身发现无休止的死亡。诺克！她统治着原子荒原！O、 Marie Therese des Batignolles女士。。。}
### {157}{}{This needs a stage.}
{157}{}{这需要一个舞台。}
### {158}{}{He knew the game of fisticuffs, it always treated him right, but no one knew the game would come and take his life that night. Torille! Torille! Tavataan. And whoopsy-daisy. It's quite an irregular place to be, but never fear you're save with me - well, maybe. But if reality is but a dream, and this world a figment of our imagination, we should be quite safe. So for Helen's Back sake stop THINKING about it. I've been fighting gravity since I was two. Show me the money! ARSE. That would be an ecumenical matter! We are all guilty of judgment and only seeing what we want to see. Society needs to be protected - a decision had to be made. They didn't like me! They never liked me! And crawling on the planet's face, some insects called the human race. Lost in time, space and meaning. Still, you've got to laugh, haven't you. Hello, Dolly it's 5.75 and the freeway looks fine.}
{158}{}{他知道拳击比赛，这对他总是很好的，但没有人知道比赛会在那天晚上夺走他的生命。托里尔！托里尔！塔瓦坦。还有叫雏菊。这是一个不规则的地方，但永远不要害怕你和我在一起——好吧，也许吧。但是，如果现实只是一场梦，而这个世界是我们想象的虚构，那么我们应该很安全。看在海伦的份上，别再想了。我从两岁起就一直在与地心引力作斗争。让我赚大钱屁股。那将是一件普世的事情！我们都有罪，只看到我们想看到的东西。社会需要得到保护——必须做出决定。他们不喜欢我！他们从不喜欢我！在地球的表面爬行，一些昆虫称之为人类。迷失在时间、空间和意义中。尽管如此，你还是要笑，不是吗。你好，多莉，现在是5.75，高速公路看起来不错。}
### {159}{}{Hmm, I really need to go now. It's getting late. But... Lord knows what they've done to you.}
{159}{}{嗯，我现在真的需要走了。天已经晚了。但是上帝知道他们对你做了什么。}
### {160}{}{::sings:: Puppy, puppy do your wander,}
{160}{}{：：唱：：小狗，小狗走吧，}
### {161}{}{from this place to a yonder.}
{161}{}{从这个地方到那边。}
### {162}{}{When the puppet has that done...} #not a typo, change to puppet is a Freudian slip{163}{}{Come back home and have some fun. ::sings::}
{162}{}{When the puppet has that done...} #not a typo, change to puppet is a Freudian slip{163}{}{回家玩吧演唱：}
### {164}{}{::sings:: Find the pauper's begging hand,}
{164}{}{：：唱：：找到穷人的乞讨之手，}
### {165}{}{spend some coins and meet new friends... ::sings::}
{165}{}{花一些硬币认识新朋友…：演唱：}
### {166}{}{::giggles:: Run, puppy, run!}
{166}{}{：咯咯笑：：快跑，小狗，快跑！}
### {167}{}{::whistles::}
{167}{}{::口哨::}
### {168}{}{[Chance: }
{168}{}{[机会：}
### {169}{}{You have failed to use your steal skill properly.}
{169}{}{你没有正确使用你的偷技。}
### {170}{}{[Intelligence required: }
{170}{}{[所需情报：}
### {171}{}{Run Away!}
{171}{}{逃跑}
### {172}{}{The beast is among us!}
{172}{}{野兽就在我们中间！}
### {173}{}{No hurting.}
{173}{}{没有伤害。}
### {174}{}{El Beelzebub! Angel of hate!}
{174}{}{El Beelzebub！仇恨天使！}
