### {100}{}{The door is locked.}
{100}{}{门是锁着的。}
### {101}{}{The explosion has damaged the door.}
{101}{}{爆炸损坏了门。}
### {102}{}{You are no good while being watched. Try something else.}
{102}{}{你被监视的时候不好。试试别的吧。}
### {103}{}{Looks like a door... Nothing unusual about it.}
{103}{}{看起来像一扇门。。。没有什么异常。}
### {104}{}{You definitively see some wiring. But you have no idea if it's a power line or what.}
{104}{}{你肯定看到了一些线路。但你不知道这是不是一条电线或什么。}
### {105}{}{Thanks to your tenacious efforts to disarm the trap... you did it, the hard way!}
{105}{}{感谢你为解除陷阱所做的不懈努力。。。你做到了，很难！}
