### {100}{}{You're not supposed to be here.}
{100}{}{你不应该在这里。}
### {101}{}{You should be on your post.}
{101}{}{你应该在岗位上。}
### {102}{}{What are you doing here?}
{102}{}{你在这里干什么？}
### {103}{}{We're not allowed to talk with each other.}
{103}{}{我们不允许互相交谈。}
### {104}{}{No talking here.}
{104}{}{不要在这里说话。}
### {105}{}{I better check with Scott what to do next...}
{105}{}{我最好和斯科特核实一下下一步该怎么办。。。}
### {106}{}{It's finally done, if only Scott were alive to see it...}
{106}{}{它终于完成了，如果斯科特还活着看到它就好了。。。}
