### {100}{}{You have started the vehicle's engine.}
{100}{}{您已经启动了车辆的发动机。}
### {101}{}{You stopped the vehicle's engine.}
{101}{}{您停止了车辆的发动机。}
### {102}{}{You successfully installed the turbocharger.}
{102}{}{您已成功安装涡轮增压器。}
### {103}{}{You charged the car with more power.}
{103}{}{你给汽车充了更多的电。}
### {104}{}{I should be careful where I leave my car.}
{104}{}{我应该小心把车停在哪里。}
### {105}{}{There's enough power left, no need to recharge.}
{105}{}{剩余电量充足，无需充电。}
### {106}{}{Car power level: }
{106}{}{汽车功率水平：}
### {107}{}{Car is out of power, nothing happens.}
{107}{}{车没电了，什么也没发生。}
