### {100}{}{What are you looking at!?}
{100}{}{你在看什么！？}
### {101}{}{Get out of my face!}
{101}{}{别当我的面！}
### {102}{}{Beat it, you smell bad.}
{102}{}{别这样，你闻起来很臭。}
### {103}{}{Are you a tribal of some sort?}
{103}{}{你是某种部落吗？}
### {104}{}{Get lost, I have nothing to say.}
{104}{}{迷路吧，我无话可说。}
### {105}{}{Lapdog ::spits::}
{105}{}{哈巴狗：吐唾沫：}
### {106}{}{Get the hell away from here!}
{106}{}{滚出去！}
### {107}{}{I knew you were a damn uptown rat!}
{107}{}{我就知道你是个该死的上城老鼠！}
### {108}{}{Fuckin' beat it!}
{108}{}{他妈的打败它！}
### {109}{}{What the...!?}
{109}{}{什么。。。！？}
### {110}{}{What the... Oh, shit!}
{110}{}{什么。。。哦，该死！}
### {111}{}{Ahhh! That bastard killed Matthew!}
{111}{}{啊！那个混蛋杀了马修！}
