### {100}{}{[You notice a similar module installed in this unit.] (You can't stop but wonder if this module will perform any better than the one you bought...)}
{100}{}{[你注意到这个单元里安装了一个类似的模块。]（你忍不住想知道这个模块是否会比你买的更好…）}
### {101}{}{[Try to pull out the module...] (Your hands never let you down before.)}
{101}{}{[试着拉出模块…]（你的手以前从未让你失望过。）}
### {102}{}{[Use your science skill to examine the unit...]}
{102}{}{[运用你的科学技能来检查单元。。。]}
### {103}{}{I'll turn off the control unit and take out the module... (Sounds logical, but...)}
{103}{}{我将关闭控制单元并取出模块。。。（听起来合乎逻辑，但…）}
### {104}{}{[Leave it alone.]}
{104}{}{[别管它。]}
### {105}{}{[You were so eager to pull this off, that you forgot to unplug the unit and touched it while running at full power... You feel the wrath of god running through your spine... Your death was inevitable.]}
{105}{}{[你太渴望实现这一目标了，以至于在满功率运行时忘记拔下电源插头并触摸了它。。。你感觉到上帝的愤怒在你的脊椎上蔓延。。。你的死是不可避免的。]}
### {106}{}{[Exit.]}
{106}{}{[出口]}
### {107}{}{[After an hour or so, you can't reach any conclusion.] (Maybe some things are better left alone.)}
{107}{}{[大约一个小时后，你无法得出任何结论。]（也许有些事情最好不要管它。）}
### {108}{}{[Try another approach...]}
{108}{}{[尝试其他方法。。。]}
### {109}{}{[Leave.]}
{109}{}{[离开]}
### {110}{}{[You've figured out several options...]}
{110}{}{[你已经想出了几个选择。。。]}
### {111}{}{[Turn off the whole station and extract the module.] (I think it's safer than just turning off the control unit and leaving the rest of the system unmonitored.)}
{111}{}{[关闭整个工作站并提取模块。]（我认为这比只关闭控制单元而不监控系统的其他部分更安全。）}
### {112}{}{[Replace the module with the one you have.] (Might work but I'm not sure how well it will perform with this old module.)}
{112}{}{[用你现有的模块替换模块。]（可能可以工作，但我不确定它与这个旧模块的性能如何。）}
### {113}{}{[Pretend you don't care for once.] (Maybe this station can operate without a control unit?)}
{113}{}{[假装你一次都不在乎。]（也许这个电台可以在没有控制单元的情况下运行？）}
### {114}{}{[Override the safety procedures and bypass the module's circuitry with some carefully placed wires.] Then I can take out the module...}
{114}{}{[绕过安全程序，用一些小心放置的电线绕过模块的电路。]然后我可以取出模块。。。}
### {115}{}{[You turn off the control unit and take out the module... Nothing happens.] (Your guess is it will run as long as the water flow through the pipes stays constant or... the whole town could run out of drinking water.)}
{115}{}{[你关闭控制单元，取出模块……什么都没发生。]（你的猜测是，只要管道中的水流保持恒定，它就会运行，或者……整个城镇的饮用水都可能耗尽。）}
### {116}{}{Let's hope it does, fingers crossed...}
{116}{}{但愿如此，祈祷吧。。。}
### {117}{}{[It turns out to be an effective way of cutting the water supply for the entire city.] (At least this will get the processing machine up and running... You stand by your conviction it was the right choice.)}
{117}{}{[事实证明，这是切断整个城市供水的有效方法。]（至少这将使加工机启动并运行……你坚信这是正确的选择。）}
### {118}{}{Something's got to give...}
{118}{}{必须有所付出。。。}
### {119}{}{(Your gut tells you this could be the long term solution you were looking for. Other than that, it's pure guesswork.)}
{119}{}{（你的直觉告诉你，这可能是你正在寻找的长期解决方案。除此之外，这纯粹是猜测。）}
### {120}{}{Let's give it a try...}
{120}{}{让我们试一试。。。}
### {121}{}{[You remove the module after skillfully reconnecting the wiring. It seems that the control unit retained some of the module's basic functions, stored in its memory, enough to keep it operational.]}
{121}{}{[在熟练地重新连接线路后，您可以卸下模块。控制单元似乎保留了模块的一些基本功能，这些功能存储在其存储器中，足以使其保持运行。]}
### {122}{}{That's what I'm talking about.}
{122}{}{这就是我在说的。}
### {123}{}{[That working module still sits in its socket...] (and may well be used as the replacement for the damaged processing machine.)}
{123}{}{[那个工作模块仍然放在插座里…]（很可能被用作损坏的加工机器的替代品。）}
### {124}{}{[More.]}
{124}{}{[更多]}
### {125}{}{[Back.]}
{125}{}{[返回]}
### {126}{}{(You don't think tampering with it would be such a good idea, not after your latest adjustments.)}
{126}{}{（你认为篡改它不是一个好主意，尤其是在你最近的调整之后。）}
### {127}{}{[Leave.]}
{127}{}{[离开]}
