### {100}{}{You see: a local citizen.}
{100}{}{你看：一个当地公民。}
### {101}{}{A scrawny, old man with squinting eyes.}
{101}{}{一个瘦骨嶙峋、眯着眼睛的老人。}
### {102}{}{Hello there, stranger. Sorry, but I really can't talk with you at the moment. [He looks very anxious.]}
{102}{}{你好，陌生人。对不起，我现在真的不能和你说话。[他看起来很焦虑。]}
### {103}{}{Hey, you look like something is troubling you.}
{103}{}{嘿，你看起来好像有什么事困扰着你。}
### {104}{}{OK, I'll let you be.}
{104}{}{好的，我让你去吧。}
### {105}{}{Do I really? Well, as you have noticed I'm not very patient... Since you are here... Could you help me out?}
{105}{}{我真的吗？好吧，正如你所注意到的，我不是很有耐心。。。既然你在这里。。。你能帮我吗？}
### {106}{}{What's on your mind?}
{106}{}{你在想什么？}
### {107}{}{Sorry, but I have to be going.}
{107}{}{对不起，我得走了。}
### {108}{}{This is really hard for me. I have lost some precious books my good friend gave to me. I usually take a long morning walk and read a book. Yesterday, when I was passing near that big water tank, I stopped to say hello to my neighbor. In the meantime, I left my books on the table, but when I returned they were gone! You have no idea how important they are to me. If you help me find them, I could pay you 100 bucks for them. What do you say?}
{108}{}{这对我来说真的很难。我丢了一些好朋友送给我的珍贵书籍。我通常早上散步，看书。昨天，当我经过那个大水箱附近时，我停下来和邻居打招呼。与此同时，我把书留在了桌子上，但当我回来的时候，书不见了！你根本不知道它们对我有多重要。如果你帮我找到它们，我可以付给你100美元。你怎么说？}
### {109}{}{Alright, I'll return if I find your books.}
{109}{}{好的，如果我找到你的书，我会回来的。}
### {110}{}{That was a nice story, but I don't believe in fairy tales anymore. Goodbye.}
{110}{}{这是一个很好的故事，但我不再相信童话了。再见}
### {111}{}{So... Did you find my books?}
{111}{}{那么…你找到我的书了吗？}
### {112}{}{Yep, here they are.}
{112}{}{是的，他们在这儿。}
### {113}{}{No luck yet.}
{113}{}{还没有运气。}
### {114}{}{Oh, my precious... Thank you very much! I owe you so much... Ah, here it is: $100 for you, you my friend. And do not tell about my books - to anyone...}
{114}{}{哦，我的宝贝。。。非常感谢！我欠你太多了。。。啊，给你：100美元给你，你，我的朋友。不要把我的书告诉任何人。。。}
### {115}{}{Hey thanks. Take good care of them, grandpa.}
{115}{}{嘿，谢谢。好好照顾他们，爷爷。}
### {116}{}{I don't see you carrying my books. Come back when you have them.}
{116}{}{我没看见你拿我的书。等你拿到了再来。}
### {117}{}{Alright then.}
{117}{}{好吧。}
### {118}{}{Thank you for those books. Keep up the good work.}
{118}{}{谢谢你的那些书。继续努力。}
### {119}{}{You stole my books!}
{119}{}{你偷了我的书！}
### {120}{}{Give me back my books!}
{120}{}{把我的书还给我！}
### {121}{}{Thief! Thief!}
{121}{}{贼贼}
### {122}{}{Where did I put them?}
{122}{}{我把它们放在哪里了？}
### {123}{}{Oh, my precious, they are gone.}
{123}{}{哦，我的宝贝，它们不见了。}
### {124}{}{Just got to remember where I put them.}
{124}{}{只要记住我把它们放在哪里。}
### {125}{}{They must be somewhere around here...}
{125}{}{他们一定在这附近的某个地方。。。}
### {126}{}{Here booky, booky...}
{126}{}{在这里，书呆子，书呆子。。。}
