{100}{}{You see: a local citizen.}
{101}{}{A scrawny, old man with squinting eyes.}
{102}{}{Hello there, stranger. Sorry, but I really can't talk with you at the moment. [He looks very anxious.]}
{103}{}{Hey, you look like something is troubling you.}
{104}{}{OK, I'll let you be.}
{105}{}{Do I really? Well, as you have noticed I'm not very patient... Since you are here... Could you help me out?}
{106}{}{What's on your mind?}
{107}{}{Sorry, but I have to be going.}
{108}{}{This is really hard for me. I have lost some precious books my good friend gave to me. I usually take a long
 morning walk and read a book. Yesterday, when I was passing near that big water tank, I stopped to say hello to my
 neighbor. In the meantime, I left my books on the table, but when I returned they were gone! You have no idea how
 important they are to me. If you help me find them, I could pay you 100 bucks for them. What do you say?}
{109}{}{Alright, I'll return if I find your books.}
{110}{}{That was a nice story, but I don't believe in fairy tales anymore. Goodbye.}
{111}{}{So... Did you find my books?}
{112}{}{Yep, here they are.}
{113}{}{No luck yet.}
{114}{}{Oh, my precious... Thank you very much! I owe you so much... Ah, here it is: $100 for you, you my friend.
 And do not tell about my books - to anyone...}
{115}{}{Hey thanks. Take good care of them, grandpa.}
{116}{}{I don't see you carrying my books. Come back when you have them.}
{117}{}{Alright then.}
{118}{}{Thank you for those books. Keep up the good work.}
#
{119}{}{You stole my books!}
{120}{}{Give me back my books!}
{121}{}{Thief! Thief!}
#
{122}{}{Where did I put them?}
{123}{}{Oh, my precious, they are gone.}
{124}{}{Just got to remember where I put them.}
{125}{}{They must be somewhere around here...}
{126}{}{Here booky, booky...}
