### {100}{}{You are going to die.}
{100}{}{你会死的。}
### {101}{}{So, you're the one marked for death.}
{101}{}{所以，你就是那个被标记为死亡的人。}
### {102}{}{You should learn better manners.}
{102}{}{你应该学习更好的礼貌。}
### {103}{}{I am going to bring you back in a body bag.}
{103}{}{我要把你装在尸袋里带回来。}
### {104}{}{Die, you scum!}
{104}{}{死吧，你这个渣滓！}
### {105}{}{Screw this - they can keep the bounty.}
{105}{}{去他妈的，他们可以保留赏金。}
### {106}{}{I'm outta here.}
{106}{}{我要离开这里。}
### {107}{}{The job isn't worth this.}
{107}{}{这份工作不值得。}
