### {100}{}{You see: Dr. Karl.}
{100}{}{你看：卡尔博士。}
### {101}{}{He's got a small collection of drugs and medical items. Some seems veterinarian.}
{101}{}{他收藏了少量药品和医疗用品。有些似乎是兽医。}
### {102}{}{Good day. What can Dr. Karl do for you?}
{102}{}{你好。卡尔医生能为你做些什么？}
### {103}{}{What do you do here?}
{103}{}{你在这里做什么？}
### {104}{}{Got any medicine I could buy?}
{104}{}{我能买到药吗？}
### {105}{}{I'm hurt.}
{105}{}{我受伤了。}
### {106}{}{Well, as a doctor I take care of the community's health. I also sell medical supplies.}
{106}{}{作为一名医生，我照顾社区的健康。我也卖医疗用品。}
### {107}{}{It must be a hard job.}
{107}{}{这一定是一项艰巨的工作。}
### {108}{}{On the contrary, I really love my work. Helping people gives me a sense of doing something worthwhile with my life. And I see the results every day.}
{108}{}{相反，我真的很喜欢我的工作。帮助别人给了我一种用生命做一些有价值的事情的感觉。我每天都能看到结果。}
### {109}{}{You're one in a million, Doc.}
{109}{}{你是万里挑一，医生。}
### {110}{}{If you ever need any of my services, come again.}
{110}{}{如果你需要我的任何服务，请再来。}
### {111}{}{Thanks, Doc, I will.}
{111}{}{谢谢，医生，我会的。}
### {112}{}{Hello again! What can Doc Karl do for you?}
{112}{}{你好！卡尔医生能为你做些什么？}
### {113}{}{I need some stimpaks.}
{113}{}{我需要一些刺激。}
### {114}{}{Nothing today, thanks.}
{114}{}{今天没什么，谢谢。}
### {115}{}{Nice to see you again. Are you interested to help me with something?}
{115}{}{很高兴再次见到你。你有兴趣帮我做点什么吗？}
### {116}{}{Sure, Doc. What do you need?}
{116}{}{当然，医生。你需要什么？}
### {117}{}{Can I buy some stims first?}
{117}{}{我可以先买一些刺激药吗？}
### {118}{}{I got to go.}
{118}{}{我得走了。}
### {119}{}{You see this is an isolated town... People around here can hardly get their hands on the most basic supplies, and our reserves are tight. We help each other to balance the shortage as best we can, but lately I've run out of some medicine that is really needed here. I'm talking about heart pills... For several of my patients. Once, a traveler stopped by and he told me I could find some of those in a town east of here. Could you check it for me? I need two packages. I would be ever so grateful.}
{119}{}{你看，这是一个孤立的小镇。。。这里的人们几乎无法获得最基本的物资，我们的储备也很紧张。我们互相帮助，尽我们所能平衡短缺，但最近我用完了一些这里真正需要的药。我说的是心脏药。。。我的几个病人。有一次，一个旅行者路过，他告诉我在这里以东的一个小镇上可以找到一些。你能帮我查一下吗？我需要两个包裹。我会非常感激的。}
### {120}{}{Yes, I could try and look for them.}
{120}{}{是的，我可以试着去找他们。}
### {121}{}{Sorry, Doc, this is not your lucky day.}
{121}{}{对不起，医生，今天不是你的幸运日。}
### {122}{}{Have you found some of those heart pills?}
{122}{}{你找到一些心脏药了吗？}
### {123}{}{Yep, I got two boxes, here you go.}
{123}{}{是的，我有两个盒子，给你。}
### {124}{}{Nope. Didn't find any.}
{124}{}{没有。没有找到。}
### {125}{}{Oh, thank God, you found them! These are really going to help. Thank you very much. If you need anything come and see me, I'll be glad to help you if I can.}
{125}{}{哦，感谢上帝，你找到它们了！这些确实会有所帮助。非常感谢。如果你需要什么来找我，如果可以的话，我很乐意帮助你。}
### {126}{}{Thank you. Take care, Doc.}
{126}{}{非常感谢。保重，医生。}
### {127}{}{Oh, God! please don't hurt me.}
{127}{}{天啊！请不要伤害我。}
### {128}{}{I want to live.}
{128}{}{我想活下去。}
### {129}{}{Don't hurt my patients, please.}
{129}{}{请不要伤害我的病人。}
### {130}{}{Take what you want, just don't hurt me.}
{130}{}{拿走你想要的，只是不要伤害我。}
### {131}{}{You have failed to use your steal skill.}
{131}{}{你没有使用你的偷技。}
### {132}{}{[Chance: }
{132}{}{[机会：}
### {133}{}{You delivered the pills Dr. Karl needed. You gain 400 exp. points.}
{133}{}{你送了卡尔医生需要的药。你获得400经验点。}
### {134}{}{Could you give me directions to that town?}
{134}{}{你能告诉我去那个城镇的路吗？}
### {135}{}{I'm afraid not, the traveler wasn't in the best of states. East is all I know. However, before you travel too far, you may visit Jack, near the gas station, he may have some pills left, but I doubt it.}
{135}{}{恐怕不是，这位旅行者当时不在最佳状态。我只知道东方。然而，在你走得太远之前，你可以去加油站附近拜访杰克，他可能还剩下一些药丸，但我对此表示怀疑。}
