### {100}{}{You see: sheriff McKarty.}
{100}{}{你看：麦克卡蒂警长。}
### {101}{}{Hey, you, psst... Come here.}
{101}{}{嘿，你，psst。。。过来。}
### {102}{}{You go talk to Mirx and be ready, they won't let you go... alive.}
{102}{}{你去和米尔克斯谈谈，做好准备，他们不会让你走的。。。活着的}
### {103}{}{Good job you have done here. One less gang in our way to win our freedom. We thank you again for doing us this great service. We'll take it from here.}
{103}{}{你在这里做得很好。在我们争取自由的道路上少了一帮人。我们再次感谢您为我们提供的卓越服务。我们从这里开始。}
### {104}{}{Take care.}
{104}{}{小心。}
