{100}{}{You see: a ghost.}
{101}{}{The spirit looks unhappy.}
#dude pricq sa duhom
{102}{}{...I'm a sinner, I regret... [Sees you.] Wha...? How did you get here?}
{103}{}{I was traveling the road not far from here and I thought I saw some lights. I was right. What is this place?}
{104}{}{Ah... This is the resting place for those wicked spirits searching for the peace that will never come. So tell me,
 what do you seek, traveler? Is there anything I could help you with?}
{105}{}{Actually I'm in need of supplies. Any idea where I can find some?}
{106}{}{I need some directions.}
{107}{}{What happened here? Who's that dead guy?}
#
{108}{}{Supplies... You can take anything you find here, I don't need anything from this awful place. It only brings
 back those bad memories. Take what you want and leave.}
{109}{}{I couldn't give you any directions. I haven't seen the world for many, many years.}
{110}{}{Some merc... Don't know for sure. A few years ago this was a place where gangs gathered. I used to
 listen to their plans, they were usually here by daylight, therefore they couldn't see me... and then... I never imagined
 that the human mind could be so evil...}
#
{111}{}{What happened then?}
#
{112}{}{Some explorers came this way. They were studying the consequences of global radiation and stuff...
 But while they were doing that, the gangs saw them and then... They tortured them, like savages, and finally just left
 them for dead.}
#
{113}{}{Those gangs, I want to exterminate them all.}
#
{114}{}{You are fighting against them?}
#
{115}{}{My whole life. I have watched too many innocents die. I will put an end to those coldblooded, sadistic
 murderers or die trying.}
{116}{}{People make mistakes. Some don't learn from their mistakes while others try not to commit them again. I'm
 sure I can't judge others by their mistakes, the Holy One will. [You point to the roof.]}
#
{117}{}{In that case you have proven yourself worthy of carrying the weapon of my ancestors. This will help you in
 your fight against evil. Take it and be on your way. And never come back to this accursed place, bereft of all life... so
 long ago...}
{118}{}{So you're leaving everything to the judgment and mercy of the Holy One. Then you shall live longer to
 witness the suffering of your people, because Hell has come to earth, but no one wants to fight it... Be on your
 way and never come back.}
#
{119}{}{May your soul find peace at last... [You leave.]}
{120}{}{Begone evil spirit, my path will be whatever I choose.}
#after 108 and 109
{121}{}{Fine, I'll find my own way.}
#
{122}{}{What is it that you want from this spirit?}
#
{123}{}{This spirit must rest.}
{124}{}{Go... Never come back.}
{125}{}{This is an evil place.}
{126}{}{Life has left this place a long time ago.}
#
{127}{}{You've dealt with the spirit. You earn 300 exp. points.}
