### {100}{}{Hey, I'm Mike. Who are you?}
{100}{}{嘿，我是迈克。你是谁？}
### {101}{}{My name is not important, I'm just looking for some information.}
{101}{}{我的名字并不重要，我只是想了解一些情况。}
### {102}{}{Right... Say, I saw you talking to that tree over there. Are you funny in the head or just a bit peculiar?}
{102}{}{正确的我看见你在和那边的树说话。你脑子里是好笑还是有点怪？}
### {103}{}{Say, do you have any jobs around here?}
{103}{}{你在这附近有工作吗？}
### {104}{}{Jobs, jobs... I'm not sure. You might try... hmm... [Rubbing his thumb against index and middle finger.]}
{104}{}{工作，工作。。。我不确定。你可以试试。。。嗯…[用拇指摩擦食指和中指。]}
### {105}{}{[Give him $50.]}
{105}{}{[给他50美元。]}
### {106}{}{[Give him $100.]}
{106}{}{[给他100美元。]}
### {107}{}{[Give him $150.]}
{107}{}{[给他150美元。]}
### {108}{}{OK, let me see... [Scratching his head.] I've heard that the sheriff wants someone for a job. The sheriff is... Just go north and after the last house, take a right.}
{108}{}{好的，让我看看。。。[挠了挠他的头。]我听说警长想找个人工作。警长…往北走，在最后一栋房子后面，向右走。}
### {112}{}{Bye.}
{112}{}{再见}
### {113}{}{Right. [Big smile.] Here's what's going on: There's a cave down below, actually it's an unused mine. Murphy is looking for someone to clean it out. He wants to reopen it. The only problem is that the mine is full of rats, so if you're interested, I suggest you talk to him. His house is next to the sheriff's.}
{113}{}{正确的[灿烂的笑容。]事情是这样的：下面有一个洞穴，实际上是一个未使用的矿井。墨菲正在找人来清理。他想重新打开。唯一的问题是矿井里到处都是老鼠，所以如果你感兴趣，我建议你和他谈谈。他的房子紧挨着警长的房子。}
### {116}{}{Thanks.}
{116}{}{谢谢}
### {117}{}{Thanks. That's very generous of you. We got this holy man, he's at the church. [Points north with his hand.] He makes potions, but needs some plants. That's all from me. [Turns away.]}
{117}{}{谢谢你真慷慨。我们抓到了一个圣人，他在教堂里。[用手指向北方。]他做药水，但需要一些植物。这都是我说的。[转身离开。]}
### {118}{}{No problemo.}
{118}{}{没问题。}
### {119}{}{Hey man. How's it going? What can I do for you?}
{119}{}{嘿，伙计，怎么样？我能为你做什么？}
### {120}{}{Any jobs around here, anything useful?}
{120}{}{这里有什么工作，有用的吗？}
### {121}{}{Sorry, I already told you everything I know.}
{121}{}{对不起，我已经把我所知道的都告诉你了。}
### {122}{}{Right, nevermind then.}
{122}{}{好吧，没关系。}
### {123}{}{You want favors, but don't have any money. That's not gonna fly. Come back when you have some.}
{123}{}{你想要帮助，但没有钱。那不会飞的。等你有了再来。}
### {124}{}{What about doing me a favor?}
{124}{}{帮我个忙怎么样？}
### {125}{}{Ehehe... Fine day to spend some bullets!}
{125}{}{呃。。。好天气，花些子弹！}
### {126}{}{You see: a local citizen.}
{126}{}{你看：一个当地公民。}
### {127}{}{He's whistling. Like it's a nice day after a downpour of acid rain.}
{127}{}{他在吹口哨。就像是下了倾盆大雨之后的好天气。}
### {128}{}{Hey, you're the guy who's running around killing people! Fuck off before I blow your brains out!}
{128}{}{嘿，你就是那个到处乱跑杀人的家伙！在我把你的脑袋炸飞之前滚蛋！}
### {129}{}{Alright.}
{129}{}{好吧}
### {130}{}{I don't think you fully grasp who I am. Let me show you.}
{130}{}{我想你还没有完全了解我是谁。让我给你看看。}
### {131}{}{What are you talking about?}
{131}{}{你在说什么？}
### {132}{}{What tree, where?}
{132}{}{什么树，在哪里？}
### {133}{}{I was just um... thinking out loud...}
{133}{}{我只是…大声思考。。。}
### {134}{}{Maybe you are the one who's crazy. Stay away from me, weirdo!}
{134}{}{也许是你疯了。离我远点，怪人！}
### {135}{}{Don't try your tricks on me, I know your kind. I can smell trouble, and your stench is unbearable. There's only one place you could have come from. And it's that prison up north. I don't like you guys strolling around, taking away people... Hell, you may even take me away... I want nothing to do with you. Go away, I'm not gonna talk to you.}
{135}{}{别对我耍花招，我认识你这种人。我能闻到麻烦的味道，你的臭味让人难以忍受。你只能从一个地方来。它就是北边的那个监狱。我不喜欢你们四处闲逛，把人带走。。。见鬼，你甚至可以把我带走。。。我不想和你有任何关系。走开，我不会和你说话的。}
### {136}{}{Damn it.}
{136}{}{该死。}
### {137}{}{You'll sing like an angel. After the beating I'm gonna give you!}
{137}{}{你会像天使一样唱歌。打了之后我要给你！}
### {138}{}{Nevermind. I can see the prison mark on your wrist. Just one more burden to carry... You are welcome here, as long as you don't cause any trouble. People have become watchful of strangers recently, and although the sheriff may be fair, he won't take any risks either, one bad word from anyone, and you'll be right back to where you came from, got it?}
{138}{}{永远不会。我能看到你手腕上的监狱痕迹。只需要再背负一个负担。。。欢迎你来这里，只要你不惹任何麻烦。最近人们开始警惕陌生人，尽管警长可能很公平，但他也不会冒任何风险，任何人只要说一句脏话，你就会回到你的家乡，明白吗？}
### {139}{}{Right... You said recently, were there others like me?}
{139}{}{正确的你最近说，还有像我这样的人吗？}
### {140}{}{What can you tell me about this place?}
{140}{}{关于这个地方你能告诉我什么？}
### {141}{}{Sure. Nice talking to you.}
{141}{}{当然很高兴和你交谈。}
### {142}{}{Yeah, there were some folks asking around about a safe place to hide. I said I can't help them and they were gone not long after. Can't remember seeing them again. Then there was some guy looking for them but he was one of the prison guards. He was pushy, even threatened me... But I know them type and called the sheriff immediately...}
{142}{}{是的，有一些人四处打听一个安全的藏身之地。我说我帮不了他们，不久之后他们就走了。我不记得再见到他们了。然后有人在找他们，但他是其中一名狱警。他咄咄逼人，甚至威胁我……但我知道他们的类型，并立即打电话给警长。。。}
### {143}{}{What happened then?}
{143}{}{当时发生了什么？}
### {144}{}{So, did you whack him or what?}
{144}{}{那么，你打了他还是怎么了？}
### {145}{}{The next thing I know... He was running away and suddenly vanished in front of my eyes. It happened so fast that I couldn't explain it to the sheriff and he certainly thought I was losing my mind. Damn, I'm not sure either anymore... A lot of weird stuff is going on here, you just stick around and you'll see what I'm talking about.}
{145}{}{接下来我知道的是。。。他正在逃跑，突然消失在我眼前。事情发生得太快了，我无法向警长解释，他肯定认为我疯了。妈的，我也不确定了。。。这里发生了很多奇怪的事情，你只要呆在这里，你就会明白我在说什么。}
### {146}{}{I might do that, see you later.}
{146}{}{我可能会那样做，回头见。}
### {147}{}{This is a small community, mostly mine workers. You'll see a lot of locals selling something to survive. That's the way it goes these days. Above all, we have bandits gathering around town, like there is anything left to steal... Maybe some dirt! [He laughs.] If that isn't enough, patrols from the nearby prison pass through town at night, taking away our people.}
{147}{}{这是一个小社区，主要是矿工。你会看到很多当地人为了生存而卖东西。现在就是这样。最重要的是，我们有土匪聚集在镇上，好像还有什么东西可以偷。。。也许有些脏东西！[他笑了。]如果这还不够的话，附近监狱的巡逻队会在晚上穿过小镇，带走我们的人。}
### {148}{}{What about those bandits?}
{148}{}{那些土匪呢？}
### {149}{}{What can you tell me about those night patrols?}
{149}{}{你能告诉我那些夜间巡逻的情况吗？}
### {150}{}{Is there anything worth staying for?}
{150}{}{有什么值得留下来的吗？}
### {151}{}{I'll see you later, thanks Mike.}
{151}{}{我待会儿见，谢谢迈克。}
### {152}{}{Always the same, they come here to plunder and take away everything they can. So we started fighting back with everything we have. And of course, we are holding so far, mostly thanks to our sheriff. He put a lot of effort into organizing the town's defenses. But without any additional weaponry, it's hopeless.}
{152}{}{他们总是一样，来这里掠夺，拿走他们能拿走的一切。所以我们开始用我们所拥有的一切进行反击。当然，我们能坚持到现在，主要要感谢我们的警长。他在组织城镇防御方面下了很大功夫。但如果没有任何额外的武器，那就没有希望了。}
### {153}{}{What are you going to do?}
{153}{}{你打算怎么办？}
### {154}{}{What about those patrols?}
{154}{}{那些巡逻队呢？}
### {155}{}{If it's hopeless, why do you stay here?}
{155}{}{如果没有希望，你为什么留在这里？}
### {156}{}{I see, thanks for your time.}
{156}{}{我明白了，谢谢你抽出时间。}
### {157}{}{Well, the sheriff decided that the best way to protect our town is to build a wall. Although, many complained that it's a waste of money and they would rather have more guns in town, the sheriff emphasized that more guns means more trouble for the community and convinced people to hold off.}
{157}{}{好吧，警长决定保护我们小镇的最好方法是建一堵墙。尽管许多人抱怨这是浪费钱，他们宁愿在城里有更多的枪支，但警长强调，更多的枪支意味着社区会遇到更多的麻烦，并说服人们推迟。}
### {158}{}{I guess you're doing the right thing, see you later.}
{158}{}{我想你做的是对的，回头见。}
### {159}{}{Well, since we built these walls, it's going better already, I think. But we put ourselves in greater isolation which means we have to find other ways than trading to produce food and goods. I just hope we won't run out of supplies or there will be some serious issues. At least we have less trouble with the bandits, that's got to be something.}
{159}{}{好吧，自从我们建造了这些墙，我想情况已经好转了。但我们将自己置于更大的孤立之中，这意味着我们必须找到除贸易之外的其他方式来生产食品和商品。我只是希望我们不会耗尽物资，否则会出现一些严重的问题。至少我们与土匪的麻烦少了，这一定是有意义的。}
### {160}{}{Better for sure...}
{160}{}{当然更好。。。}
### {161}{}{The worst kind I know of. From the very beginning they gave us promises and we got nothing but empty words and lies. But the town is still divided whether we should accept the technology they have to offer or stay defenseless against the raiders. Some of the locals think it's far better to join these peace keepers than watch our people suffer every day...}
{161}{}{这是我所知道的最糟糕的一种。从一开始，他们就给了我们承诺，我们只得到了空话和谎言。但镇上仍然存在分歧，我们是应该接受他们提供的技术，还是对袭击者保持防御。一些当地人认为，与其看着我们的人民每天受苦受难，不如加入这些和平卫士的行列。。。}
### {162}{}{Have you decided anything?}
{162}{}{你决定了什么吗？}
### {163}{}{And what's the price for joining them?}
{163}{}{加入他们的价格是多少？}
### {164}{}{I've had enough of this, see you later.}
{164}{}{我受够了，回头见。}
### {165}{}{Well, sort of... But I'm glad the majority is strongly against any patrol presence in town. We don't need them and the only mistake we made was letting them poison our minds with the words we wanted to hear back then. Now, I know it's wrong and I'm helping others to realize that.}
{165}{}{嗯，有点。。。但我很高兴大多数人都强烈反对在城里巡逻。我们不需要他们，我们犯的唯一错误就是让他们用我们当时想听的话毒害我们的思想。现在，我知道这是错误的，我正在帮助别人认识到这一点。}
### {166}{}{I hope you are doing the right thing.}
{166}{}{我希望你做的是对的。}
### {167}{}{It's... too much even to consider as an alternative. They needed new recruits, we might be simple folks but we are smart enough to see they were only interested in taking our people to work in their labor camps.}
{167}{}{这是。。。太多了，甚至无法作为替代方案考虑。他们需要新员工，我们可能是简单的人，但我们足够聪明，看到他们只对带我们的人去劳改营工作感兴趣。}
### {168}{}{Labor camps? Can you tell me more?}
{168}{}{劳改营？你能告诉我更多吗？}
### {169}{}{Well, thanks for your time.}
{169}{}{谢谢你抽出时间。}
### {170}{}{Look, I can't tell you more because I don't know more... You better talk to the sheriff about it.}
{170}{}{听着，我不能告诉你更多，因为我不知道更多。。。你最好和警长谈谈。}
### {171}{}{I will, thanks.}
{171}{}{我会的，谢谢。}
### {172}{}{Because there's nothing for me out there. Everything I ever needed is right here... And I have never asked for more. It makes me feel bitter when someone tries to take away our peace... Even our lives at some point. So I try to smile every time and think of the day when this will be over. That day will come, I can assure you that.}
{172}{}{因为外面什么都不适合我。我所需要的一切都在这里。。。我从来没有要求过更多。当有人试图夺走我们的安宁时，我感到很痛苦。。。甚至在某个时刻我们的生活。所以我每次都试着微笑，想着有一天这一切会结束。我可以向你保证，那一天会到来的。}
### {173}{}{I don't think it will be anytime soon, what are you going to do until then?}
{173}{}{我认为这不会很快，在那之前你打算做什么？}
### {174}{}{I sure hope so.}
{174}{}{我当然希望如此。}
### {175}{}{Everything you see here is worth something to me. But it's the people we are fighting for, not rocks or trees!}
{175}{}{你在这里看到的一切对我来说都有价值。但我们为之奋斗的是人民，而不是石头或树木！}
### {176}{}{I get the point. There's nothing more I need to know.}
{176}{}{我明白了。我没有什么需要知道的了。}
### {177}{}{I'm not gonna talk to you.}
{177}{}{我不会和你说话的。}
### {178}{}{Stay away from me.}
{178}{}{离我远点。}
### {179}{}{Man, you scare me!}
{179}{}{伙计，你吓到我了！}
### {180}{}{I don't know what you want, but I'm not telling you anything.}
{180}{}{我不知道你想要什么，但我什么都没告诉你。}
### {181}{}{Do you have a hearing problem? I told you to stay away from me.}
{181}{}{你的听力有问题吗？我告诉过你离我远点。}
### {182}{}{I'll come back when I have some money.}
{182}{}{等我有钱了再回来。}
### {183}{}{Hey there, stranger.}
{183}{}{嘿，陌生人。}
### {184}{}{I'm watching you.}
{184}{}{我在看着你。}
### {185}{}{There's nothing of interest here.}
{185}{}{这里没有什么有趣的。}
### {186}{}{Do you want something?}
{186}{}{你想要什么吗？}
### {187}{}{Go away.}
{187}{}{走开。}
### {188}{}{Yeah, whatever...}
{188}{}{是的，不管怎样。。。}
### {189}{}{I'm not listening.}
{189}{}{我不听。}
### {190}{}{Just leave me be.}
{190}{}{别管我。}
### {191}{}{What? I can't hear you.}
{191}{}{什么我听不见你说话。}
### {192}{}{::he follows you with his eyes::}
{192}{}{::他用眼睛跟着你::}
### {193}{}{[Speech chance: }
{193}{}{[演讲机会：}
### {194}{}{You have failed to use your steal skill.}
{194}{}{你没有使用你的偷技。}
### {195}{}{[Chance: }
{195}{}{[机会：}
