{100}{}{You see: a gang member.}
{101}{}{A rather tough looking guard.}
#random float
{102}{}{Where did you come from?}
{103}{}{You're not welcome here.}
{104}{}{I don't like strangers.}
{105}{}{Don't even think about it.}
{106}{}{Wanna catch a bullet!?}
{107}{}{I could use some target practice.}
{108}{}{Really boring, don't have anything to shoot at.}
{109}{}{I'm watching you.}
#combat lines
{110}{}{You can't outrun the Dogs!}
{111}{}{Miners gonna pay for this!}
{112}{}{You hurt? I can smell the blood-trail.}
{113}{}{Me and my dogs gonna feed on your corpse for weeks.}
{114}{}{The wasteland will burn!}
{115}{}{The wasteland will echo with our barks!}
