### {100}{}{Nice day for killing.}
{100}{}{杀戮的好日子。}
### {101}{}{I'm on my twelfth jag. What about you?}
{101}{}{我正在进行我的第十二次jag。你呢？}
### {102}{}{Got any bullets left?}
{102}{}{还有子弹吗？}
### {103}{}{Not much left to do here. ::grins::}
{103}{}{这里没什么可做的了咧嘴笑：}
### {104}{}{We are a most organized gang.}
{104}{}{我们是最有组织的帮派。}
### {105}{}{I can hit a kid from over sixty yards away.}
{105}{}{我可以在60码外打一个孩子。}
### {106}{}{I was shot twice, but it's nothing.}
{106}{}{我中了两枪，但没什么。}
### {107}{}{Killed anyone recently? What a relief. Am I right?}
{107}{}{最近杀了谁？真是松了一口气。我说得对吗？}
### {108}{}{When did you join?}
{108}{}{你什么时候加入的？}
### {109}{}{Check out that guy at the gun store, he can't breathe!}
{109}{}{看看枪店的那个家伙，他无法呼吸！}
