{100}{}{How's it going, pal?}
{101}{}{I never get tired of talking to you. Anything else?}
{102}{}{Some geckos were running this way, seen any?}
{103}{}{Where did I put my book?}
{104}{}{Nothing new 'round here. What about you?}
#
{105}{}{Hello, stranger. New in town?}
{106}{}{Yes I am. [Smile.] How do you do?}
{107}{}{Maybe. What can you tell me about this place?}
{108}{}{No, lived here all my life. [Roll eyes.]}
#
{109}{}{[Shrugs.] Got my peace and quiet. Plenty of geckos around, so I can't complain. Trade is slow as ever, but I'm
 doing alright. Guess, we all do, kinda. It's a community thing. We don't have much, but we help each other. And that
 includes those nut-jobs guarding us, well, and Stockman's, I guess.}
#
{110}{}{Anything going on around here?}
{111}{}{What's with Stockman's?}
{112}{}{What about those guards?}
{113}{}{Any visitors lately?}
#general
{114}{}{Nothing really. There is a bulletin board if you need to know. [Gestures at it.] Well, may be out of date. Not
 much point in it these days. Hardly any visitors to read it. Still, I guess, there's Stockman's and Joe's garage but they
 don't run so well no more. Then there's Jack's drug store who sells medicine, Quincy's to buy weapons from, probably
 the last of use who manages to get steady supplies, God knows how, Anna's bar if you need a pick-me-up, and Doc
 Karl who keeps us all up and running. [Grins.] The rest of us are farmers, hunters and small time traders. We get by.}
#
{115}{}{What's wrong with Stockman's?}
{116}{}{And those guards you've mentioned?}
#stockman
{117}{}{Well, if there's a business in town it's theirs. They did a pretty penny once. Trading, guarding shipments,
 investments, anything around goods, cash and trade, really. But ever since the contract with Miners fell apart, and the
 caravans stopped coming, the town's been kinda isolated, and their business suffered the worst. Well, besides Joe's.}
#
{118}{}{Any laws in town?}
#militia
{119}{}{Well, there are two groups, Derek's and the Bulls. Both run some sort of militia group. Arming themselves up
 and protecting the town against bandits, mutants and such. Well, they say they do, it's all a bit gung-ho. Still, you may
 call them the local law, but it all depends on who you're talking to. Matter of fact is, we have no sheriff, judge or jury.
 So if you break the law who knows what will happen. [Laughs.] May change one day, but we're in no rush.}
#
{120}{}{What makes you doubt them?}
#
{121}{}{To be honest, I doubt any bandits are bothering with this place. And I've never seen any mutants either. So
 what are they doing out there? Other than camping. [Laughs.] But to be fair, I never really paid any attention to them,
 they go about playing their military games, or whatever they do, it never bothered me much. I guess they keep the area
 safe, but as long as they don't scare away the geckos, I'm fine either way. I guess the worst would be if both groups
 would end up at each other's throat. That could get messy.}
#
{122}{}{I see, thanks.}
#visitors
{123}{}{I haven't seen anyone coming this way, but I've heard of a suspicious bunch moving east. Seemed like the
 secretive type, didn't talk, didn't care showing their faces. They stayed for a bit, asked some questions, stocked up on
 supplies, then moved on east. From what I gathered they were after a place called Golden Valley. Apparently there's an
 old gold mine. Attracts all kinds of dubious characters. But I doubt there is anything left in that place, but old,
 abandoned mine shafts. It's always the same. We're a more quiet and peaceful community of farmers and hunters, well,
 for the most part...}
#
{124}{}{To the east you say. Hm, interesting. Anything else going on around here?}
#lived here all my life
{125}{}{Funny, never seen you before.}
{126}{}{Well, I've never seen you before either. So, what's up?}
{127}{}{I prefer to keep to myself. Which reminds me. Bye.}
{128}{}{[Panic.] I knew I shouldn't have left the vault! Aaaarghh!}
{129}{}{Perhaps I should get out more. Anything interesting?}
#
{130}{}{The usual, nothing changes much around here, [eyes you suspiciously], as you know.}
{131}{}{Yeah, right. Seen anyone new lately?}
{132}{}{Well, then. Don't let me disturb you... standing here. Bye.}
#
{133}{}{Besides you?}
{134}{}{...}
#
{135}{}{That's right.}
#
{136}{}{Seen anyone coming into town lately?}
{137}{}{What's the deal with Stockman's?}
{138}{}{Tell me about the local law.}
{139}{}{Tell me about this place again.}
{140}{}{Nothing. Bye.}
#
{141}{}{Let me ask you something else.}
#generic
{142}{}{You have failed to use your steal skill.}
{143}{}{[Chance: }
{144}{}{[Intelligence required: }
{145}{}{The town of Golden Valley has been added to your map.}

