{100}{}{You see: Mark, the gecko hunter.}
{101}{}{A competent gecko hunter from Farmers Town.}
#
{102}{}{You're here. Excellent... Just be quiet, we're going to surprise them. I saw a few big ones so don't wander off
 on your own, I don't want to drag you back, or what's left of you [smiles]. Time for the hunt, let's go champ! You
 lead.}
{103}{}{[Go.]}
#
{104}{}{We are gonna get ourselves some nice pelts. [Takes out his knife and starts skinning the geckos.]}
{105}{}{I'll wait.}
#
{106}{}{Very good. [He smiles.] This is gonna sell for a *lot*. Here's your half. [Gives you ten pieces.] Take good
 care of those. Catch you at the bar tomorrow morning.}
{107}{}{See ya.}
#
{108}{}{It's hunting time!}
{109}{}{Don't let it come too close to you!}
{110}{}{I can hear something, it's close...}
#
{111}{}{Thanks for your help.}
{112}{}{See you later.}
{113}{}{Catch you later, I'll buy you a drink.}
#
{114}{}{Damn coward!}
{115}{}{Walk away, like you always do!}
{116}{}{Get lost, punk! You had your chance.}
