### {100}{}{Be about your business and leave.}
{100}{}{管好你的事，然后离开。}
### {101}{}{Move along.}
{101}{}{继续前进。}
### {102}{}{I'm watching you.}
{102}{}{我在看着你。}
### {103}{}{There's nothing to see here.}
{103}{}{这里没有什么可看的。}
### {104}{}{Leave the damn door alone!}
{104}{}{别管那该死的门！}
### {105}{}{I'm not gonna repeat myself!}
{105}{}{我不会重复我自己！}
### {106}{}{The door is open for you. But don't touch anything you are not supposed to.}
{106}{}{门为你敞开。但不要碰任何你不该碰的东西。}
### {107}{}{Alright.}
{107}{}{好吧}
### {108}{}{I already told you, the door is open.}
{108}{}{我已经告诉过你了，门是开着的。}
### {109}{}{Alright.}
{109}{}{好吧}
