### {100}{}{You see: one of the sheriff's guards.}
{100}{}{你看：一个治安官的警卫。}
### {101}{}{He is standing there like a wall.}
{101}{}{他像墙一样站在那里。}
### {102}{}{Good day, stranger.}
{102}{}{你好，陌生人。}
### {103}{}{Came to speak with the sheriff?}
{103}{}{是来和警长说话的吗？}
### {104}{}{He's inside.}
{104}{}{他在里面。}
### {105}{}{Don't cause any trouble.}
{105}{}{不要惹任何麻烦。}
### {106}{}{Talk to the sheriff.}
{106}{}{和警长谈谈。}
### {107}{}{Hey there, looking for another job? Talk to the sheriff.}
{107}{}{嘿，在找另一份工作吗？和警长谈谈。}
### {108}{}{That's right, we're always looking for new officers.}
{108}{}{没错，我们一直在寻找新的军官。}
### {109}{}{Respect! An old word from better times.}
{109}{}{尊敬一个来自美好时代的旧词。}
### {110}{}{Nice to see you again.}
{110}{}{很高兴再次见到你。}
### {111}{}{You should come more often.}
{111}{}{你应该经常来。}
### {112}{}{The sheriff will be glad to see you well.}
{112}{}{警长很高兴见到你。}
### {113}{}{Nothing to report.}
{113}{}{无需报告。}
### {114}{}{Damn man, where did you bought that thing!?}
{114}{}{该死的人，你在哪里买的！？}
### {115}{}{Nice armor. Has it got to be polished every day?}
{115}{}{漂亮的盔甲。它必须每天都抛光吗？}
### {116}{}{Put your weapon away.}
{116}{}{把你的武器收起来。}
### {117}{}{You have failed to use your steal skill.}
{117}{}{你没有使用你的偷技。}
### {118}{}{[Chance: }
{118}{}{[机会：}
