##############################
#???????: ??...???
#???: ????? '????? 
#??????? ????????: ??????? ?? ??????? ? ??????
#???? ????????: 25.08.2014
##############################
#??? ???? "????? 2207"
#????? "Rainman" ????????
##############################
#
#???????? ????????
#
# ?? ??????????
### {1}{}{You see a man with a big mustache. }
{1}{}{你看到一个留着大胡子的男人。 -- You see a man with a big mustache. }
### {2}{}{As a child, you've seen an old Ninto magazine with a chubby plumber Maro on its cover. This man looks just like that plumber.}
{2}{}{小时候，你看过一本旧的《Ninto》杂志，封面上有一个胖乎乎的水管工Maro。这个人看起来就像那个水管工。 -- As a child, you've seen an old Ninto magazine with a chubby plumber Maro on its cover. This man looks just like that plumber.}
#
# ????? ??????????
### {3}{}{You see Ashton.}
{3}{}{你看到阿什顿了。 -- You see Ashton.}
### {4}{}{Wrenches and screwdrivers are sticking out of his pockets.}
{4}{}{扳手和螺丝刀从他的口袋里伸出来。 -- Wrenches and screwdrivers are sticking out of his pockets.}
#
#????? ?????????? ??????
#
### {10}{}{[You see a dissatisfied man with a mustache. Seeing you he starts grumbling] Another someone poking his nose around. Who are you and why did you come here? What do you want? }
{10}{}{[你看到一个不满的留着胡子的男人。看到你，他开始抱怨]另一个人到处捅他的鼻子。你是谁？你为什么来这里？你想要什么？ -- [You see a dissatisfied man with a mustache. Seeing you he starts grumbling] Another someone poking his nose around. Who are you and why did you come here? What do you want? }
### {11}{002}{I'm new here. Looking around the vault.}
{11}{002}{我是新来的。环顾保险库。 -- I'm new here. Looking around the vault.}
### {12}{009}{Who are YOU?}
{12}{009}{你是谁？ -- Who are YOU?}
### {13}{011}{Hey. I'm new, meeting my neighbors.}
{13}{011}{嘿我是新来的，认识我的邻居。 -- Hey. I'm new, meeting my neighbors.}

### {20}{}{Look around, but carefully. Don't put your fingers into everything, pushing every button you see. I'm Ashton Horton, the head of Hortons family and the most important man in Livos. Do you know the first rule of Livos?}
{20}{}{环顾四周，但要小心。不要把你的手指放在任何事情上，按下你看到的每一个按钮。我是阿什顿·霍顿，霍顿家族的首领，也是利沃斯最重要的人。你知道利沃斯的第一条规则吗？ -- Look around, but carefully. Don't put your fingers into everything, pushing every button you see. I'm Ashton Horton, the head of Hortons family and the most important man in Livos. Do you know the first rule of Livos?}
### {21}{003}{No.}
{21}{003}{不 -- No.}
### {22}{004}{Yes.}
{22}{004}{对 -- Yes.}
### {23}{005}{I have no time to talk about rules right now. I'll go.}
{23}{005}{我现在没有时间谈论规则。我去。 -- I have no time to talk about rules right now. I'll go.}

### {30}{}{The first rule of Livos is to take good care of the property! Use the local equipment only in case you need to. It's forbidden to turn everything on and off just for fun, or push any buttons when you feel like it! Understood?}
{30}{}{利沃斯的第一条规则是要好好照顾房子！只有在需要的时候才使用本地设备。禁止为了好玩而打开和关闭所有设备，或者在你喜欢的时候按下任何按钮！明白了吗？ -- The first rule of Livos is to take good care of the property! Use the local equipment only in case you need to. It's forbidden to turn everything on and off just for fun, or push any buttons when you feel like it! Understood?}
### {31}{004}{Yes, understood.}
{31}{004}{是的，明白了。 -- Yes, understood.}
### {32}{007}{No, I still don't get it.}
{32}{007}{不，我还是不明白。 -- No, I still don't get it.}
### {33}{005}{I don't care. I'll go.}
{33}{005}{我不在乎。我去。 -- I don't care. I'll go.}

### {40}{}{Good. Then I need to test your knowledge of the rules. Are you ready?}
{40}{}{好的然后我需要测试你对规则的了解。你准备好了吗？ -- Good. Then I need to test your knowledge of the rules. Are you ready?}
### {41}{006}{I'm ready!}
{41}{006}{我准备好了！ -- I'm ready!}
### {42}{007}{No, I'm not ready yet.}
{42}{007}{不，我还没准备好。 -- No, I'm not ready yet.}
### {43}{003}{Uh, which rules? I forgot.}
{43}{003}{呃，什么规则？我忘了。 -- Uh, which rules? I forgot.}

### {50}{}{[He grabs your hand] Wait! You can't leave until you learn the rules! You should demonstrate your knowledge of them! Are you ready?}
{50}{}{[他抓住你的手]等等！在你学会规则之前你不能离开！你应该展示你对它们的了解！你准备好了吗？ -- [He grabs your hand] Wait! You can't leave until you learn the rules! You should demonstrate your knowledge of them! Are you ready?}
### {51}{006}{Yes, I'm ready.}
{51}{006}{是的，我准备好了。 -- Yes, I'm ready.}
### {52}{003}{Remind me, which rules are there?}
{52}{003}{提醒我，有哪些规则？ -- Remind me, which rules are there?}
### {53}{007}{No, I'm not ready.}
{53}{007}{不，我还没准备好。 -- No, I'm not ready.}

### {60}{}{Okay then, first question - How do you treat the property of Livos?}
{60}{}{好吧，那么，第一个问题-你如何对待利沃斯的财产？ -- Okay then, first question - How do you treat the property of Livos?}
### {61}{012}{With good care.}
{61}{012}{小心。 -- With good care.}
### {62}{012}{With care.}
{62}{012}{小心。 -- With care.}
### {63}{013}{With a little care.}
{63}{013}{稍微小心一点。 -- With a little care.}
### {64}{013}{Usually.}
{64}{013}{通常 -- Usually.}
### {65}{013}{You can push buttons if you feel like it.}
{65}{013}{如果你愿意，你可以按按钮。 -- You can push buttons if you feel like it.}
### {66}{014}{You can poke into everything you want and push everything you find.}
{66}{014}{你可以戳进你想要的一切，推送你找到的一切。 -- You can poke into everything you want and push everything you find.}
### {67}{014}{You can do anything, including kicking stuff around and picking into it.}
{67}{014}{你可以做任何事情，包括踢球和捡东西。 -- You can do anything, including kicking stuff around and picking into it.}

### {70}{}{I won't let you go until you learn the rules! You will definitely go and break something! You should pass the test!}
{70}{}{我不会让你走的，除非你学会了规则！你一定会去打碎一些东西！你应该通过考试！ -- I won't let you go until you learn the rules! You will definitely go and break something! You should pass the test!}
### {71}{003}{Well, okay. Remind me, which rules are there?}
{71}{003}{好吧。提醒我，有哪些规则？ -- Well, okay. Remind me, which rules are there?}
### {72}{006}{I'm ready for the test.}
{72}{006}{我已经准备好考试了。 -- I'm ready for the test.}
### {73}{008}{Screw you! I don't care about that tests of yours!}
{73}{008}{去你的！我不在乎你的测试！ -- Screw you! I don't care about that tests of yours!}

### {80}{}{You are a stupid moron! I'm gonna beat some sense into you!}
{80}{}{你是个愚蠢的白痴！我要给你灌输一些道理！ -- You are a stupid moron! I'm gonna beat some sense into you!}
### {81}{998}{Come on then!}
{81}{998}{那就来吧！ -- Come on then!}

### {90}{}{You have a bad temper. Probably, that's because you didn't know that you are talking to Ashton Horton himself, the head of Hortons family and the most important man in Livos. Do you know the first rule of Livos?}
{90}{}{你脾气不好。也许，那是因为你不知道你在和阿什顿·霍顿本人交谈，他是霍顿家族的首领，也是利沃斯最重要的人。你知道利沃斯的第一条规则吗？ -- You have a bad temper. Probably, that's because you didn't know that you are talking to Ashton Horton himself, the head of Hortons family and the most important man in Livos. Do you know the first rule of Livos?}
### {91}{003}{No.}
{91}{003}{不 -- No.}
### {92}{004}{Yes.}
{92}{004}{对 -- Yes.}
### {93}{005}{I have no time to talk about rules right now. I'll go.}
{93}{005}{我现在没有时间谈论规则。我去。 -- I have no time to talk about rules right now. I'll go.}

### {1001}{}{Come in, chief. Did something break again?}
{1001}{}{进来吧，首领。有什么东西又坏了吗？ -- Come in, chief. Did something break again?}
### {1002}{}{Yes, I can answer your questions.}
{1002}{}{是的，我可以回答你的问题。 -- Yes, I can answer your questions.}
### {1003}{}{Oh, you again. You didn't break anything, did you.}
{1003}{}{哦，又是你。你没有打碎任何东西，是吗。 -- Oh, you again. You didn't break anything, did you.}
### {101}{015}{Ludwig lost his book on wave science. Did you see it?}
{101}{015}{路德维希丢失了他关于波浪科学的书。你看到了吗？ -- Ludwig lost his book on wave science. Did you see it?}
### {102}{016}{I want to talk about Seth and Matt from NWO. Do you want to make an alliance with them?}
{102}{016}{我想谈谈来自NWO的赛斯和马特。你想和他们结盟吗？ -- I want to talk about Seth and Matt from NWO. Do you want to make an alliance with them?}
### {103}{017}{You said that you are the most important man in Livos. Tell me more about it.}
{103}{017}{你说你是利沃斯最重要的人。告诉我更多关于它的信息。 -- You said that you are the most important man in Livos. Tell me more about it.}
### {104}{019}{What is it that you do here?}
{104}{019}{你在这里干什么？ -- What is it that you do here?}
### {105}{026}{I want to talk about the water filter.}
{105}{026}{我想谈谈水过滤器。 -- I want to talk about the water filter.}
### {106}{999}{I have some things to do. Let's talk later.}
{106}{999}{我有一些事情要做。我们稍后再谈。 -- I have some things to do. Let's talk later.}

### {110}{}{[The man smiles] Well, you've met the right person to talk to. I'm Ashton Horton, the head of Hortons family and the most important man in Livos. Do you know the first rule of Livos?}
{110}{}{[男人笑了]好吧，你遇到了合适的人。我是阿什顿·霍顿，霍顿家族的首领，也是利沃斯最重要的人。你知道利沃斯的第一条规则吗？ -- [The man smiles] Well, you've met the right person to talk to. I'm Ashton Horton, the head of Hortons family and the most important man in Livos. Do you know the first rule of Livos?}
### {111}{003}{No.}
{111}{003}{不 -- No.}
### {112}{004}{Yes.}
{112}{004}{对 -- Yes.}
### {113}{005}{I have no time to talk about rules right now. I'll go.}
{113}{005}{我现在没有时间谈论规则。我去。 -- I have no time to talk about rules right now. I'll go.}

### {120}{}{[Ashton looks satisfied] Right! You are good! If only everyone else would understand the rules as well as you. I have no more questions, you have passed. Now you can walk freely around the vault.}
{120}{}{[阿什顿看起来很满意]对！你很好！如果其他人都能像你一样理解规则就好了。我没有问题了，你已经通过了。现在，您可以在保险库中自由行走。 -- [Ashton looks satisfied] Right! You are good! If only everyone else would understand the rules as well as you. I have no more questions, you have passed. Now you can walk freely around the vault.}
### {121}{010}{I would like to ask some questions first.}
{121}{010}{我想先问几个问题。 -- I would like to ask some questions first.}
### {122}{999}{Okay, I'm going with a clean conscience.}
{122}{999}{好吧，我问心无愧地去。 -- Okay, I'm going with a clean conscience.}

### {130}{}{[Ashton raises his voice] Not exactly right! You should treat the property of Livos with GOOD CARE! How am I supposed to make all of you remember this simple thing... Okay, you can walk around freely, but don't poke your nose where you shouldn't.}
{130}{}{[阿什顿提高声音]不完全正确！你应该好好照顾利沃斯的财产！我该如何让你们记住这件简单的事情。。。好吧，你可以自由走动，但不要把鼻子伸到不该伸的地方。 -- [Ashton raises his voice] Not exactly right! You should treat the property of Livos with GOOD CARE! How am I supposed to make all of you remember this simple thing... Okay, you can walk around freely, but don't poke your nose where you shouldn't.}
### {131}{010}{I would like to ask some questions first.}
{131}{010}{我想先问几个问题。 -- I would like to ask some questions first.}
### {132}{999}{Okay, I'll go walk around.}
{132}{999}{好的，我去走走。 -- Okay, I'll go walk around.}

### {140}{}{[Ashton frantically waves his hands] Wrong! You can't do it, it's forbidden! You should take GOOD CARE of local property! How am I supposed to make all of you remember this simple thing... Okay, you can walk around freely, but don't touch any equipment! At least, until you learn the rules.}
{140}{}{[阿什顿疯狂地挥手]错了！你不能这样做，这是被禁止的！你应该好好照顾当地的财产！我该如何让你们记住这件简单的事情。。。好吧，你可以自由走动，但不要碰任何设备！至少，在你学会规则之前。 -- [Ashton frantically waves his hands] Wrong! You can't do it, it's forbidden! You should take GOOD CARE of local property! How am I supposed to make all of you remember this simple thing... Okay, you can walk around freely, but don't touch any equipment! At least, until you learn the rules.}
### {141}{010}{I would like to ask some questions first.}
{141}{010}{我想先问几个问题。 -- I would like to ask some questions first.}
### {142}{999}{Okay, I'll go walk around.}
{142}{999}{好的，我去走走。 -- Okay, I'll go walk around.}

### {150}{}{[Ashton carelessly shrugs] No, I didn't see any book. I have more important things to do than reading about some stupid theories. Ask others.}
{150}{}{[阿什顿漫不经心地耸耸肩]不，我没有看到任何书。比起读一些愚蠢的理论，我还有更重要的事情要做。问问别人。 -- [Ashton carelessly shrugs] No, I didn't see any book. I have more important things to do than reading about some stupid theories. Ask others.}
### {151}{010}{Okay. I have other questions.}
{151}{010}{可以我还有其他问题。 -- Okay. I have other questions.}
### {152}{999}{I'll go ask someone else.}
{152}{999}{我去问别人。 -- I'll go ask someone else.}

### {160}{}{[Ashton makes displeased face] Who the hell are Seth and Matt? I'm too busy to make some stupid alliances with some tramps from NWO! I don't care about their problems in the slightest. No alliances for them. Maybe some other families would talk about it. It's in their habit - to deal in nonsense.}
{160}{}{[阿什顿一脸不悦]赛斯和马特到底是谁？我太忙了，没时间和NWO的流浪汉结盟！我一点也不在乎他们的问题。他们没有联盟。也许其他一些家庭会谈论这件事。这是他们的习惯——胡说八道。 -- [Ashton makes displeased face] Who the hell are Seth and Matt? I'm too busy to make some stupid alliances with some tramps from NWO! I don't care about their problems in the slightest. No alliances for them. Maybe some other families would talk about it. It's in their habit - to deal in nonsense.}
### {161}{010}{Okay. I have other questions.}
{161}{010}{可以我还有其他问题。 -- Okay. I have other questions.}
### {162}{999}{I'll go and do that then.}
{162}{999}{那我就去做。 -- I'll go and do that then.}

### {170}{}{[Ashton complacently raises his chin] Yes, I'm the most important person in this place. Firstly, I do the repairs of the vital equipment. No one else does. Without my skills, everything here would have fallen apart already. These lazy amoebas can't do anything, so I forbid them to even touch the mechanisms. They will only make things worse with their crooked hands. }
{170}{}{[阿什顿得意地抬起下巴]是的，我是这个地方最重要的人。首先，我负责重要设备的维修。没有其他人这样做。如果没有我的技术，这里的一切都会分崩离析。这些懒惰的变形虫什么都不会做，所以我甚至禁止它们触摸机制。他们弯曲的双手只会让事情变得更糟。 -- [Ashton complacently raises his chin] Yes, I'm the most important person in this place. Firstly, I do the repairs of the vital equipment. No one else does. Without my skills, everything here would have fallen apart already. These lazy amoebas can't do anything, so I forbid them to even touch the mechanisms. They will only make things worse with their crooked hands. }
### {171}{018}{And secondly?}
{171}{018}{其次呢？ -- And secondly?}

### {180}{}{[His smile gets wider] And secondly, I am the one and only legitimate owner of this beautiful hotel. My ancestors, who were the proprietors of a huge hotel network, built it for me and my family. And the rest are only living here because we allow it. If Livos gets crowded, I'll throw someone outside. My word is the law here, everyone knows that I'm the rightful leader. Still, despite my high status, I don't act star-struck. I'm even proud that it doesn't get in my way of doing the hard labor of repairings.}
{180}{}{[他的笑容越来越灿烂]其次，我是这家美丽酒店的唯一合法所有者。我的祖先是一个巨大酒店网络的所有者，他们为我和我的家人建造了这个网络。其他人住在这里只是因为我们允许。如果利沃斯拥挤，我会把人扔到外面。我的话就是这里的法律，每个人都知道我是合法的领袖。尽管我的地位很高，但我并没有表现得像个明星。我甚至感到自豪的是，它没有妨碍我进行艰苦的维修工作。 -- [His smile gets wider] And secondly, I am the one and only legitimate owner of this beautiful hotel. My ancestors, who were the proprietors of a huge hotel network, built it for me and my family. And the rest are only living here because we allow it. If Livos gets crowded, I'll throw someone outside. My word is the law here, everyone knows that I'm the rightful leader. Still, despite my high status, I don't act star-struck. I'm even proud that it doesn't get in my way of doing the hard labor of repairings.}
### {181}{020}{You are able of repairing anything in the vault, right?}
{181}{020}{你可以修理金库里的任何东西，对吧？ -- You are able of repairing anything in the vault, right?}
### {182}{010}{Okay, I want to ask something else.}
{182}{010}{好吧，我想问别的问题。 -- Okay, I want to ask something else.}

### {190}{}{I'm doing repair duties. And I don't let anyone else poke into this important business. Only the hands of gold, like mine, would touch this complicated tech.}
{190}{}{我在做修理工作。我不让任何人插手这件重要的事情。只有像我一样的金子之手才能接触到这项复杂的技术。 -- I'm doing repair duties. And I don't let anyone else poke into this important business. Only the hands of gold, like mine, would touch this complicated tech.}
### {191}{020}{Can you fix anything here?}
{191}{020}{你能在这里修点什么吗？ -- Can you fix anything here?}
### {192}{010}{I see. I have other questions.}
{192}{010}{我明白了。我还有其他问题。 -- I see. I have other questions.}

### {200}{}{[Ashton stumbles] Not exactly... For example, our nutritional mixtures machine is completely out of order. Something burned in it. Or jammed. Or something else. Despite my highest qualification, I couldn't do anything. It's all because of the carelessness of other dwellers! I keep telling them - take good care of the property! But they just don't. Of course, they are guests in my hotel, but as an owner, I'm not very glad.}
{200}{}{不完全是。。。例如，我们的营养混合物机器完全失灵了。里面有东西烧焦了，或者卡住了。或者其他什么。尽管我有最高的资格，但我什么都做不了。这都是因为其他居民的疏忽！我一直告诉他们——好好保管房子！但他们就是没有。当然，他们是我酒店的客人，但作为业主，我不是很高兴。 -- [Ashton stumbles] Not exactly... For example, our nutritional mixtures machine is completely out of order. Something burned in it. Or jammed. Or something else. Despite my highest qualification, I couldn't do anything. It's all because of the carelessness of other dwellers! I keep telling them - take good care of the property! But they just don't. Of course, they are guests in my hotel, but as an owner, I'm not very glad.}
### {201}{021}{Any other problems?}
{201}{021}{还有其他问题吗？ -- Any other problems?}
### {202}{010}{I see. I'll ask about something else.}
{202}{010}{我明白了。我会问一些其他的事情。 -- I see. I'll ask about something else.}

### {2101}{}{[Ashton slowly and reluctantly continues] Uhh... You see... I don't know if I should tell you this, but, er... The thing is, there's something wrong with the water filter. He can't handle big amounts of water anymore. And I'm afraid it'll only get worse - if it breaks down completely, Livos could die out. I tried to repair it, but the situation is pretty complex. You can't just go and fix it.}
{2101}{}{[阿什顿缓慢而不情愿地继续说]嗯。。。你看。。。我不知道我是否应该告诉你，但是，呃…问题是，水过滤器出了问题。他再也不能处理大量的水了。我担心情况只会变得更糟——如果它完全坏了，利沃斯可能会死。我试着修复它，但情况相当复杂。你不能只是去修理它。 -- [Ashton slowly and reluctantly continues] Uhh... You see... I don't know if I should tell you this, but, er... The thing is, there's something wrong with the water filter. He can't handle big amounts of water anymore. And I'm afraid it'll only get worse - if it breaks down completely, Livos could die out. I tried to repair it, but the situation is pretty complex. You can't just go and fix it.}
### {2102}{}{No other problems for now. There were issues with the broken water filter, but it works fine now.}
{2102}{}{目前没有其他问题。滤水器坏了也有问题，但现在工作正常。 -- No other problems for now. There were issues with the broken water filter, but it works fine now.}
### {2103}{}{The water filter is completely dead. I've read the manual, spent much time, but still fail to fix it. Soon our water supply will become thin. Don't know what to do with it.}
{2103}{}{滤水器完全失灵了。我看了手册，花了很多时间，但还是没能修好。很快我们的水供应就会变少。不知道该怎么办。 -- The water filter is completely dead. I've read the manual, spent much time, but still fail to fix it. Soon our water supply will become thin. Don't know what to do with it.}
### {211}{022}{I've heard that the taste of water became strange. Is it because of a problem with the filter?}
{211}{022}{我听说水的味道变得奇怪了。是因为过滤器有问题吗？ -- I've heard that the taste of water became strange. Is it because of a problem with the filter?}
### {212}{025}{I can look into the filter problem. I have broad experience of repairing different stuff.}
{212}{025}{我可以调查一下过滤器的问题。我在修理不同的东西方面有丰富的经验。 -- I can look into the filter problem. I have broad experience of repairing different stuff.}
### {213}{023}{You are the best repairman of Livos! How come you still didn't manage?}
{213}{023}{你是利沃斯最好的修理工！你怎么还是没成功？ -- You are the best repairman of Livos! How come you still didn't manage?}
### {214}{010}{I see. Let's talk about something else.}
{214}{010}{我明白了。让我们谈谈其他事情。 -- I see. Let's talk about something else.}

### {220}{}{[Ashton shakes his head] No, the quality of water is the same. The filter problem only influences the amount of water that can be filtered. Every drop of water in Livos went through this filter, the taste is the same as before. You can see for yourself.}
{220}{}{[阿什顿摇摇头]不，水的质量是一样的。过滤器问题只会影响可过滤的水量。Livos的每一滴水都经过了这个过滤器，味道和以前一样。你可以自己看。 -- [Ashton shakes his head] No, the quality of water is the same. The filter problem only influences the amount of water that can be filtered. Every drop of water in Livos went through this filter, the taste is the same as before. You can see for yourself.}
### {221}{025}{I am experienced in repairings. I can see what has happened to the filter.}
{221}{025}{我在修理方面很有经验。我可以看到过滤器发生了什么。 -- I am experienced in repairings. I can see what has happened to the filter.}
### {222}{023}{How come you still didn't manage it? You are the best repairman of Livos!}
{222}{023}{你怎么还是没搞定？你是利沃斯最好的修理工！ -- How come you still didn't manage it? You are the best repairman of Livos!}
### {223}{010}{Really? So it's not about the filter then. I have other questions.}
{223}{010}{真正地所以这与过滤器无关。我还有其他问题。 -- Really? So it's not about the filter then. I have other questions.}
### {224}{999}{I need to find out what's wrong with the water. I'll go talk to someone else. Bye.}
{224}{999}{我需要找出水出了什么问题。我去和别人谈谈。再见 -- I need to find out what's wrong with the water. I'll go talk to someone else. Bye.}

### {230}{}{[Ashton hesitates] I don't even know... I've read the manual, but, uh, it's so difficult... I couldn't make heads or tails- I mean, I didn't have time to look into it properly! Yes, because of this other urgent business I have!}
{230}{}{我甚至不知道。。。我看过手册，但是，呃，太难了。。。我做不出头或尾——我的意思是，我没有时间好好研究它！是的，因为我还有其他紧急的事情！ -- [Ashton hesitates] I don't even know... I've read the manual, but, uh, it's so difficult... I couldn't make heads or tails- I mean, I didn't have time to look into it properly! Yes, because of this other urgent business I have!}
### {231}{024}{Ashton, you are the most experienced person in this vault in the matters of repairing things! I'm sure it will be very easy for you to understand this manual, if you try!}
{231}{024}{阿什顿，你是这个金库里修理东西最有经验的人！我相信，如果你尝试的话，你会很容易理解这本手册！ -- Ashton, you are the most experienced person in this vault in the matters of repairing things! I'm sure it will be very easy for you to understand this manual, if you try!}
### {232}{025}{Let me see into it. I have some skills in fixing things.}
{232}{025}{让我看看。我有一些修理东西的技巧。 -- Let me see into it. I have some skills in fixing things.}
### {233}{010}{I'm sure you'll fix it later. I want to ask something else.}
{233}{010}{我相信你稍后会修好的。我想问别的问题。 -- I'm sure you'll fix it later. I want to ask something else.}

### {240}{}{[Ashton shines] Yes! I'm the best in the whole Radius! I could fix the filter, sure, but I still need to deal with, uh, selling a couple of guns. Because, obviously, I need batteries for the parts. You could help me out if you buy one of them for, let's say, 350 batteries. Until I deal with this, I won't get into repairing the filter.}
{240}{}{[阿什顿闪耀]是的！我是整个Radius中最好的！我当然可以修理过滤器，但我仍然需要处理，呃，卖几支枪的问题。因为，很明显，我需要电池作为零件。如果你用350块电池买一块，你可以帮我。在我解决这个问题之前，我不会着手修理过滤器。 -- [Ashton shines] Yes! I'm the best in the whole Radius! I could fix the filter, sure, but I still need to deal with, uh, selling a couple of guns. Because, obviously, I need batteries for the parts. You could help me out if you buy one of them for, let's say, 350 batteries. Until I deal with this, I won't get into repairing the filter.}
### {241}{010}{I'd better look into fixing the filter myself. I have other questions.}
{241}{010}{我最好自己去修理过滤器。我还有其他问题。 -- I'd better look into fixing the filter myself. I have other questions.}
### {242}{031}{Here are the batteries. Give me one of that guns. Now you'll have the time you need to do fixings.}
{242}{031}{这是电池。给我一把枪。现在您将有时间进行固定。 -- Here are the batteries. Give me one of that guns. Now you'll have the time you need to do fixings.}
### {245}{999}{I have no batteries on me right now. I'll get them to you later.}
{245}{999}{我现在身上没有电池。我稍后再给你拿。 -- I have no batteries on me right now. I'll get them to you later.}

### {250}{}{[Ashton has visible doubts] I don't know... I don't let anyone fix things around here. Hm. But this is a difficult case, so I could have a use for a fresh eye. Okay, you can go look at the filter. But be very careful!}
{250}{}{[阿什顿有明显的怀疑]我不知道。。。我不让任何人修理这里的东西。嗯。但这是一个困难的情况，所以我可以有一个新的眼睛使用。好的，你可以去看看过滤器。但是要非常小心！ -- [Ashton has visible doubts] I don't know... I don't let anyone fix things around here. Hm. But this is a difficult case, so I could have a use for a fresh eye. Okay, you can go look at the filter. But be very careful!}
### {251}{999}{Okay, I'll go check the filter out.}
{251}{999}{好的，我去检查一下过滤器。 -- Okay, I'll go check the filter out.}

### {260}{}{The filter is still bad at filtering. And the repair manual is so obscure!}
{260}{}{过滤器的过滤能力仍然很差。而且维修手册太晦涩了！ -- The filter is still bad at filtering. And the repair manual is so obscure!}
### {261}{024}{Ashton, you are the most experienced person in this vault in the matter of repairing things! I'm sure it will be very easy for you to understand this manual, if you try!}
{261}{024}{阿什顿，你是这个金库里修理东西最有经验的人！我相信，如果你尝试的话，你会很容易理解这本手册！ -- Ashton, you are the most experienced person in this vault in the matter of repairing things! I'm sure it will be very easy for you to understand this manual, if you try!}
### {262}{010}{I'm still looking into the problem too. I have some questions though.}
{262}{010}{我还在调查这个问题。不过我还有一些问题。 -- I'm still looking into the problem too. I have some questions though.}
### {263}{027}{I've repaired the filter. It works even better than before.}
{263}{027}{我已经修好了过滤器。它的效果甚至比以前更好。 -- I've repaired the filter. It works even better than before.}
### {265}{027}{I'm not quite sure, but it looks like you need a NEW filter...}
{265}{027}{我不太确定，但看起来你需要一个新的过滤器。。。 -- I'm not quite sure, but it looks like you need a NEW filter...}
### {264}{030}{Can I look at the manual?}
{264}{030}{我能看一下说明书吗？ -- Can I look at the manual?}

### {270}{}{That is great! I'll check... [Ashton presses some buttons on a nearby device] The filter is really working! You were so lucky to have such a wise me giving you advice! Still, you've helped a bit too. Here are some batteries for that. And I also have a couple of guns here, so pick one as a present. }
{270}{}{太棒了！我会检查。。。[Ashton按下了附近设备上的一些按钮]过滤器真的很管用！你真幸运，有这么聪明的我给你建议！尽管如此，你也帮了一点忙。这里有一些电池。我这里也有几把枪，所以选一把作为礼物。 -- That is great! I'll check... [Ashton presses some buttons on a nearby device] The filter is really working! You were so lucky to have such a wise me giving you advice! Still, you've helped a bit too. Here are some batteries for that. And I also have a couple of guns here, so pick one as a present. }
### {271}{028}{I want a plasma rifle prototype.}
{271}{028}{我想要一个等离子步枪原型。 -- I want a plasma rifle prototype.}
### {272}{029}{I'm more into that laser pistol.}
{272}{029}{我更喜欢那把激光手枪。 -- I'm more into that laser pistol.}

### {273}{}{Wh- WHAT? You broke it completely?! [Ashton presses some buttons on a nearby device]] Damn... No signal at all... Well... All that's left is to hope that the water is not as dirty as we used to think... And I had some reward prepared for you, but now you obviously won't get it!}
{273}{}{什么？你把它完全打碎了？！[Ashton按下了附近设备上的一些按钮]]该死。。。根本没有信号。。。好剩下的就是希望水不会像我们过去想的那样脏。。。我为你准备了一些奖励，但现在你显然得不到了！ -- Wh- WHAT? You broke it completely?! [Ashton presses some buttons on a nearby device]] Damn... No signal at all... Well... All that's left is to hope that the water is not as dirty as we used to think... And I had some reward prepared for you, but now you obviously won't get it!}
### {274}{999}{Oh... [shrug and leave]}
{274}{999}{哦[耸耸肩离开] -- Oh... [shrug and leave]}
### {275}{999}{Of course, you'd better hide it somewhere [wink and leave]}
{275}{999}{当然，你最好把它藏在某个地方[眨眼就走] -- Of course, you'd better hide it somewhere [wink and leave]}

### {280}{}{Good choice. Here. Don't forget to take good care of it! [he smiles and mumbles] Unbelievable, I finally got rid of this useless junk...}
{280}{}{不错的选择。在这里别忘了好好照顾它！[他微笑着喃喃自语]难以置信，我终于摆脱了这些无用的垃圾。。。 -- Good choice. Here. Don't forget to take good care of it! [he smiles and mumbles] Unbelievable, I finally got rid of this useless junk...}
### {281}{999}{Thanks. Bye, Ashton.}
{281}{999}{谢谢再见，阿什顿。 -- Thanks. Bye, Ashton.}

### {290}{}{Good choice. Here. Don't forget to take good care of it! [he smiles and mumbles] Unbelievable, I finally got rid of this useless junk...}
{290}{}{不错的选择。在这里别忘了好好照顾它！[他微笑着喃喃自语]难以置信，我终于摆脱了这些无用的垃圾。。。 -- Good choice. Here. Don't forget to take good care of it! [he smiles and mumbles] Unbelievable, I finally got rid of this useless junk...}
### {291}{999}{Thanks. Bye, Ashton.}
{291}{999}{谢谢再见，阿什顿。 -- Thanks. Bye, Ashton.}

### {300}{}{No! I won't let anyone look into my documents!}
{300}{}{不我不会让任何人查看我的文件！ -- No! I won't let anyone look into my documents!}
### {301}{026}{Okay then. So, what about the filter?}
{301}{026}{好吧。那么，过滤器呢？ -- Okay then. So, what about the filter?}

### {310}{}{I have a laser pistol and plasma rifle prototype. Pick something and I'll go handle the filter.}
{310}{}{我有一把激光手枪和等离子步枪的原型。挑点东西，我去处理过滤器。 -- I have a laser pistol and plasma rifle prototype. Pick something and I'll go handle the filter.}
### {311}{032}{I want a plasma rifle prototype.}
{311}{032}{我想要一个等离子步枪原型。 -- I want a plasma rifle prototype.}
### {312}{033}{I'm more into that laser pistol.}
{312}{033}{我更喜欢那把激光手枪。 -- I'm more into that laser pistol.}

### {320}{}{Good choice. Here. Don't forget to take good care of it! [he smiles and mumbles] Unbelievable, I finally got rid of this useless junk... [Looks at you] I'll go fix the thing! Not a problem at all, especially for the best repairman in Radius!}
{320}{}{不错的选择。在这里别忘了好好照顾它！[他微笑着喃喃自语]难以置信，我终于摆脱了这些无用的垃圾。。。[看着你]我去修！一点问题都没有，尤其是对于Radius最好的修理工来说！ -- Good choice. Here. Don't forget to take good care of it! [he smiles and mumbles] Unbelievable, I finally got rid of this useless junk... [Looks at you] I'll go fix the thing! Not a problem at all, especially for the best repairman in Radius!}
### {321}{999}{Thanks. Bye, Ashton.}
{321}{999}{谢谢再见，阿什顿。 -- Thanks. Bye, Ashton.}

### {330}{}{Good choice. Here. Don't forget to take good care of it! [he smiles and mumbles] Unbelievable, I finally got rid of this useless junk... [Looks at you] I'll go fix the thing! Not a problem at all, especially for the best repairman in Radius!}
{330}{}{不错的选择。在这里别忘了好好照顾它！[他微笑着喃喃自语]难以置信，我终于摆脱了这些无用的垃圾。。。[看着你]我去修！一点问题都没有，尤其是对于Radius最好的修理工来说！ -- Good choice. Here. Don't forget to take good care of it! [he smiles and mumbles] Unbelievable, I finally got rid of this useless junk... [Looks at you] I'll go fix the thing! Not a problem at all, especially for the best repairman in Radius!}
### {331}{999}{Thanks. Bye, Ashton.}
{331}{999}{谢谢再见，阿什顿。 -- Thanks. Bye, Ashton.}
