##############################
#???????: ???
#???: ??????
#??????? ????????: ?????????, ???? ????, ???? Arsene
#???? ????????: 20.06.2014
##############################
#??? ???? "????? 2207"
#????? "Rainman" ????????
##############################
#
#???????? ????????
#
# ?? ??????????
### {1}{}{You see a twitchy lady.}
{1}{}{你看到一个抽搐的女士。 -- You see a twitchy lady.}
### {2}{}{She is constantly looking around, like being afraid of something.}
{2}{}{她不停地环顾四周，好像在害怕什么。 -- She is constantly looking around, like being afraid of something.}
#
# ????? ??????????
### {3}{}{You see Maurissa.}
{3}{}{你看到了Maurissa。 -- You see Maurissa.}
### {4}{}{As usual, she is a little nervous and twitchy.}
{4}{}{和往常一样，她有点紧张和抽搐。 -- As usual, she is a little nervous and twitchy.}
#
#????? ?????????? ??????
#
#Node001
### {10}{}{[You see a strange-looking middle-aged woman. When she sees you, she nervously jumps and freezes, gazing at you with wide eyes. Looks like she is ready to run away at any moment] Who are you? What are you doing here?}
{10}{}{【你看到一个长相奇怪的中年女人，看到你，她紧张地跳了起来，僵住了，睁大眼睛盯着你，看起来随时都准备逃跑】你是谁？你在这里干什么？ -- [You see a strange-looking middle-aged woman. When she sees you, she nervously jumps and freezes, gazing at you with wide eyes. Looks like she is ready to run away at any moment] Who are you? What are you doing here?}
### {11}{002}{Relax, I'm }
{11}{002}{放松，我 -- Relax, I'm }
### {12}{002}{. Is everything alright?}
{12}{002}{。一切都好吗？ -- . Is everything alright?}
### {13}{022}{What's wrong with you? Not quite right in the head?}
{13}{022}{你怎么了？脑子不太对劲？ -- What's wrong with you? Not quite right in the head?}
### {14}{999}{I was only passing by.}
{14}{999}{我只是路过。 -- I was only passing by.}

#Node002
### {20}{}{Oh, uh... I was just... I thought you are following me. They follow me all the time! [she still looks suspiciously at you, trying to act like everything is okay.]}
{20}{}{哦，呃。。。我只是。。。我以为你在跟着我。他们一直跟着我！[她仍然怀疑地看着你，试图表现得好像一切都好。] -- Oh, uh... I was just... I thought you are following me. They follow me all the time! [she still looks suspiciously at you, trying to act like everything is okay.]}
### {21}{014}{What? Who?}
{21}{014}{什么谁 -- What? Who?}
### {22}{014}{Who is following you? Are you the big cheese around here, knowing too much?}
{22}{014}{谁在跟踪你？你是这里的大人物吗，知道的太多了？ -- Who is following you? Are you the big cheese around here, knowing too much?}
### {23}{003}{I'll continue following you then.}
{23}{003}{到时我会继续关注你。 -- I'll continue following you then.}

#Node003
### {30}{}{What? Do you think it's funny?! There is nothing funny, go away!}
{30}{}{什么你觉得这有趣吗？！没有什么好笑的，走开！ -- What? Do you think it's funny?! There is nothing funny, go away!}
### {31}{999}{[you walk away. She is definitely not okay.]}
{31}{999}{[你走开了。她肯定不太好。 -- you walk away. She is definitely not okay.]}
### {32}{013}{I see that it's a sensitive topic for you...}
{32}{013}{我知道这对你来说是一个敏感的话题。。。 -- I see that it's a sensitive topic for you...}
### {33}{014}{You don't really have a sense of humor. Who is following you then?}
{33}{014}{你真的没有幽默感。那谁在跟踪你？ -- You don't really have a sense of humor. Who is following you then?}

#Node010 
### {100}{}{You again... [she nervously looks around]}
{100}{}{你又。。。[她紧张地环顾四周] -- You again... [she nervously looks around]}
### {101}{011}{Want to chat?}
{101}{011}{想聊天吗？ -- Want to chat?}
### {102}{999}{I was just coming by.}
{102}{999}{我刚过来。 -- I was just coming by.}

### {103}{}{Hello, nice to see you!}
{103}{}{你好，很高兴见到你！ -- Hello, nice to see you!}
### {104}{041}{I was passing by, decided to come around. Wanna chat?}
{104}{041}{我路过，决定绕过去。想聊聊吗？ -- I was passing by, decided to come around. Wanna chat?}
### {105}{999}{Hey. I was wondering how are you doing [smile]. Well, I need to go, see you.}
{105}{999}{嘿我在想你过得怎么样[微笑]。我得走了，再见。 -- Hey. I was wondering how are you doing [smile]. Well, I need to go, see you.}

### {106}{}{You! Don't you dare to come any closer! Get out! Out! [she slowly steps away]}
{106}{}{你你不敢再靠近了！滚出去！出来[她慢慢地走开] -- You! Don't you dare to come any closer! Get out! Out! [she slowly steps away]}
### {107}{031}{I saw the man who is following you...}
{107}{031}{我看到那个跟踪你的人。。。 -- I saw the man who is following you...}
### {108}{032}{Just relax. I'm here to talk, ask some questions. No more cruel jokes, honestly.}
{108}{032}{放松一下。我是来谈谈，问一些问题的。老实说，别再开残酷的玩笑了。 -- Just relax. I'm here to talk, ask some questions. No more cruel jokes, honestly.}
### {109}{999}{Okay! I'm leaving.}
{109}{999}{可以我要走了。 -- Okay! I'm leaving.}

#Node011
### {110}{}{[She crosses arms on her chest and stares at you. Or at something behind you?] Go ahead.}
{110}{}{[她双臂交叉放在胸前，盯着你。或者盯着你身后的什么东西？]继续。 -- [She crosses arms on her chest and stares at you. Or at something behind you?] Go ahead.}
### {111}{012}{Are you sick?}
{111}{012}{你生病了吗？ -- Are you sick?}
### {112}{014}{Is someone following you?}
{112}{014}{有人在跟踪你吗？ -- Is someone following you?}
### {113}{019}{Let's talk about you. Can you tell me something about yourself?}
{113}{019}{让我们谈谈你。你能告诉我一些你自己的情况吗？ -- Let's talk about you. Can you tell me something about yourself?}
### {114}{999}{[look over your shoulder] You know, I don't feel comfortable when people stare at something behind me. Talk later.}
{114}{999}{[回头看]你知道，当人们盯着我身后的东西看时，我感觉不舒服。以后再谈。 -- [look over your shoulder] You know, I don't feel comfortable when people stare at something behind me. Talk later.}

#Node012
### {120}{}{What? [her hands stretch like strings, the face is all red] You... Who do you think you are? I am perfectly okay!}
{120}{}{什么[她的手像绳子一样伸展，脸都红了]你。。。你以为你是谁？我完全没事！ -- What? [her hands stretch like strings, the face is all red] You... Who do you think you are? I am perfectly okay!}
### {121}{999}{You have definitely lost your marbles. I think it's no use talking to you, although a little interesting. Bye-bye.}
{121}{999}{你肯定是疯了。我觉得和你说话没用，虽然有点意思。再见 -- You have definitely lost your marbles. I think it's no use talking to you, although a little interesting. Bye-bye.}
### {122}{013}{You are as okay as I'm a stripper.}
{122}{013}{你和我一样是个脱衣舞娘。 -- You are as okay as I'm a stripper.}

#Node013
### {130}{}{Enough, go away!}
{130}{}{够了，走开！ -- Enough, go away!}
### {131}{999}{Sure. See ya.}
{131}{999}{当然再见。 -- Sure. See ya.}

#Node014
### {140}{}{A man, wearing a sand coat. And somebody else. I can't quite get their faces.}
{140}{}{一个穿着沙大衣的男人。还有其他人。我看不清他们的脸。 -- A man, wearing a sand coat. And somebody else. I can't quite get their faces.}
### {141}{015}{I believe you - I see him [stare behind her]}
{141}{015}{我相信你-我看到他[盯着她身后] -- I believe you - I see him [stare behind her]}
### {142}{999}{Yeah. You know, I've just remembered about all the things I need to do. I'll go now.}
{142}{999}{是 啊你知道，我刚刚想起了我需要做的所有事情。我现在就走。 -- Yeah. You know, I've just remembered about all the things I need to do. I'll go now.}
### {143}{999}{I had doubts before, but now I'm sure - you are really troubled in the head. [leave]}
{143}{999}{我以前有疑虑，但现在我确信——你真的很头疼。[离开] -- I had doubts before, but now I'm sure - you are really troubled in the head. [leave]}
### {144}{024}{It is called "paranoia". A severe case of it, I'd say.}
{144}{024}{这被称为“妄想症”。我认为这是一个严重的病例。 -- It is called "paranoia". A severe case of it, I'd say.}
### {145}{060}{[try to smile, making a kind face] Yes, I think this is just how it is. Very convincing.}
{145}{060}{[试着微笑，做一个和蔼的脸]是的，我想事情就是这样。非常有说服力。 -- [try to smile, making a kind face] Yes, I think this is just how it is. Very convincing.}

#Node015
### {150}{}{[she freezes in fear, pupils become widened, hands shaking. But she didn't turn around, she just stands on the spot, seemingly not breathing.] }
{150}{}{[她吓得僵住了，瞳孔变大，双手颤抖。但她没有转身，只是站在原地，似乎没有呼吸。] -- [she freezes in fear, pupils become widened, hands shaking. But she didn't turn around, she just stands on the spot, seemingly not breathing.] }
### {151}{016}{[focus your sight on her]}
{151}{016}{[把视线集中在她身上 -- focus your sight on her]}
### {152}{017}{I was just joking. There's no one there.}
{152}{017}{我只是在开玩笑。那里没有人。 -- I was just joking. There's no one there.}

#Node016
### {160}{}{Did he leave? It always ends like this... [She hunches. Now she looks extremely exhausted.]}
{160}{}{他走了吗？结局总是这样。。。[她弓着腰。现在她看起来非常疲惫。] -- Did he leave? It always ends like this... [She hunches. Now she looks extremely exhausted.]}
### {161}{999}{[take a deep breath] Okay... Now... I'm going... [leave]}
{161}{999}{[深呼吸]好的。。。现在我要去。。。[离开 -- take a deep breath] Okay... Now... I'm going... [leave]}
### {162}{011}{Can I ask you something before he comes back?}
{162}{011}{在他回来之前我能问你些什么吗？ -- Can I ask you something before he comes back?}

#Node017
### {170}{}{Don't you dare to do it again! My heart almost exploded!}
{170}{}{你再也不敢做了！我的心都快爆炸了！ -- Don't you dare to do it again! My heart almost exploded!}
### {171}{999}{Okay. Now I need to run. I'll come by.}
{171}{999}{可以现在我需要跑步了。我会过来的。 -- Okay. Now I need to run. I'll come by.}
### {172}{011}{I'm sorry, that was really stupid. Can I ask something else?}
{172}{011}{对不起，那真的很愚蠢。我能问别的问题吗？ -- I'm sorry, that was really stupid. Can I ask something else?}

#Node018
### {180}{}{Wh-... Get away! Out! [Her face becomes red, eyes flashing furiously]}
{180}{}{为什么。。。逃掉出来[她的脸涨红了，眼睛疯狂地闪烁] -- Wh-... Get away! Out! [Her face becomes red, eyes flashing furiously]}
### {181}{999}{[leave silently]}
{181}{999}{[默默地离开 -- leave silently]}

#Node019
### {190}{}{I live here with my husband and son. You know, they are not very fond of local authorities, and I understand them... I have seen so many bad things here... You wouldn't believe it. But our Mayor doesn't listen to me! So I fully support them undermining this... Stupid authority.}
{190}{}{我和我的丈夫和儿子住在这里。你知道，他们不太喜欢地方当局，我理解他们。。。我在这里看到了很多不好的事情。。。你不会相信的。但是我们的市长不听我的！所以我完全支持他们破坏这一点。。。愚蠢的权威。 -- I live here with my husband and son. You know, they are not very fond of local authorities, and I understand them... I have seen so many bad things here... You wouldn't believe it. But our Mayor doesn't listen to me! So I fully support them undermining this... Stupid authority.}
### {191}{020}{Can you tell me more details about your family?}
{191}{020}{你能告诉我更多关于你家庭的细节吗？ -- Can you tell me more details about your family?}
### {192}{013}{Those who are sick are always disappointed with something... You are a schizophrenic with a persecution mania.}
{192}{013}{那些生病的人总是对某事感到失望。。。你是一个患有迫害狂的精神分裂症患者。 -- Those who are sick are always disappointed with something... You are a schizophrenic with a persecution mania.}
### {193}{023}{I agree, it's quite boring here. And the authorities suck. }
{193}{023}{我同意，这里很无聊。当局也很差劲。 -- I agree, it's quite boring here. And the authorities suck. }

#Node020
### {200}{}{Dan is lovely! He is a real man, always making difficult decisions without any hesitations! That's how he conquered my heart... But lately he acts cold. He says that something is wrong with me. Arsene is just like him - strong and brave. He makes me so proud! Although, they both used to be more caring... Still, I'm happy they are busy with a common goal and spend time together.}
{200}{}{丹很可爱！他是一个真正的男人，总是毫不犹豫地做出艰难的决定！他就是这样征服了我的心。。。但最近他表现得很冷淡。他说我有点不对劲。阿尔塞纳和他一样——坚强而勇敢。他让我很自豪！虽然，他们都曾经更关心。。。尽管如此，我还是很高兴他们正忙于一个共同的目标，并共度时光。 -- Dan is lovely! He is a real man, always making difficult decisions without any hesitations! That's how he conquered my heart... But lately he acts cold. He says that something is wrong with me. Arsene is just like him - strong and brave. He makes me so proud! Although, they both used to be more caring... Still, I'm happy they are busy with a common goal and spend time together.}
### {201}{999}{I think I need to talk to Dan. See you around, Maurissa.}
{201}{999}{我想我需要和丹谈谈。再见，Maurissa。 -- I think I need to talk to Dan. See you around, Maurissa.}
### {202}{050}{I think it's your fault that your family is falling apart. You should look for things in your home, not watch out for someone who's "following" you. Don't you think so?}
{202}{050}{我认为你的家庭破裂是你的错。你应该在家里找东西，而不是提防“跟踪”你的人。你不这么认为吗？ -- I think it's your fault that your family is falling apart. You should look for things in your home, not watch out for someone who's "following" you. Don't you think so?}
### {203}{021}{I feel sorry for you. I think you deserve better. }
{203}{021}{我为你感到难过。我认为你应该得到更好的待遇。 -- I feel sorry for you. I think you deserve better. }


#Node021
### {210}{}{Do you really think so?}
{210}{}{你真的这么认为吗？ -- Do you really think so?}
### {211}{011}{Of course. But I want to ask something else. }
{211}{011}{当然但我想问别的问题。 -- Of course. But I want to ask something else. }
### {212}{022}{[roll eyes] What a fool you are...}
{212}{022}{[翻白眼]你真傻。。。 -- [roll eyes] What a fool you are...}

#Node022
### {220}{}{You are such a rude person!!!}
{220}{}{你真是个粗鲁的人！！！ -- You are such a rude person!!!}
### {221}{013}{Who cares.}
{221}{013}{谁在乎呢。 -- Who cares.}
### {222}{999}{Uh... I think I've picked the wrong words. I'm sorry. Let's talk later. Bye!}
{222}{999}{嗯我想我选错词了。对不起。我们稍后再谈。再见 -- Uh... I think I've picked the wrong words. I'm sorry. Let's talk later. Bye!}

#Node023
### {230}{}{It's good that we are on the same page!}
{230}{}{我们站在同一立场真是太好了！ -- It's good that we are on the same page!}
### {231}{020}{Tell me more about your family.}
{231}{020}{告诉我更多关于你家人的情况。 -- Tell me more about your family.}
### {232}{012}{I was just messing with you, the locals are the best. It is you who is troubled!}
{232}{012}{我只是在跟你开玩笑，当地人是最棒的。麻烦的是你！ -- I was just messing with you, the locals are the best. It is you who is troubled!}

#Node024
### {240}{}{Paranoia?}
{240}{}{妄想症 -- Paranoia?}
### {241}{033}{Yes. It's treatable.}
{241}{033}{对它是可以治疗的。 -- Yes. It's treatable.}
### {242}{011}{Forget about it. I'll ask something else.}
{242}{011}{算了，我再问别的。 -- Forget about it. I'll ask something else.}
### {243}{018}{That means you are a fool.}
{243}{018}{那意味着你是个傻瓜。 -- That means you are a fool.}


#Node031
### {310}{}{[Maurissa's facial expression abruptly changes] Leave! Immediately leave! [she turns away from you and starts to look around]}
{310}{}{[Maurissa的表情突然变了]离开！立即离开！[她转身离开你，开始环顾四周 -- Maurissa's facial expression abruptly changes] Leave! Immediately leave! [she turns away from you and starts to look around]}
### {311}{999}{[end conversation]}
{311}{999}{[结束对话 -- end conversation]}

#Node032
### {320}{}{We've talked. And now - leave! I'd better not see you again!!}
{320}{}{我们已经谈过了。现在——离开！我最好别再见到你！！ -- We've talked. And now - leave! I'd better not see you again!!}
### {321}{999}{Okay, I'm leaving. }
{321}{999}{好的，我要走了。 -- Okay, I'm leaving. }
### {322}{011}{I wasn't being serious the last time. But we can make things right, can't we? Let's try again. }
{322}{011}{上次我不是认真的。但我们可以把事情做好，不是吗？让我们再试一次。 -- I wasn't being serious the last time. But we can make things right, can't we? Let's try again. }


#Node033
### {330}{}{What!? I am sick? You are the same as them!!}
{330}{}{什么我生病了？你和他们一样！！ -- What!? I am sick? You are the same as them!!}
### {331}{080}{Yes, you are definitely sick. You are periodically seeing things that don't exist. Did you notice that no one else sees these men following you?}
{331}{080}{是的，你肯定病了。你会周期性地看到不存在的东西。你注意到没有其他人看到这些人跟着你吗？ -- Yes, you are definitely sick. You are periodically seeing things that don't exist. Did you notice that no one else sees these men following you?}
### {332}{999}{Sorry, but you have to think about it alone. I'll come by later. Bye.}
{332}{999}{很抱歉，但你必须单独考虑。我稍后再来。再见 -- Sorry, but you have to think about it alone. I'll come by later. Bye.}
### {333}{070}{Not exactly. Mental disorders are often the result of a combination of influencing factors. }
{333}{070}{不完全是。精神障碍通常是多种影响因素共同作用的结果。 -- Not exactly. Mental disorders are often the result of a combination of influencing factors. }


#Node034
### {340}{}{[you definitely struck something in her] I... I think you're right... What do I do? }
{340}{}{[你肯定在她身上撞到了什么]我…我认为你是对的。。。我该怎么办？ -- [you definitely struck something in her] I... I think you're right... What do I do? }
### {341}{035}{[try to remember the stuff you've read about in medical science literature and tell it to her]}
{341}{035}{[试着记住你在医学文献中读到的东西，并告诉她 -- try to remember the stuff you've read about in medical science literature and tell it to her]}
### {342}{999}{I need to think. I'll dig through the books and will come back.}
{342}{999}{我需要思考。我会翻遍这些书然后再回来。 -- I need to think. I'll dig through the books and will come back.}
### {343}{035}{Maurissa, you live in the safest, calmest, peaceful, and wonderful place in the whole Radius. Everyone here would stand for you - even if they are pulling some pranks sometimes. You are one big family. Any dangerous outsider just won't make it here. So you can just put it off your mind, and feel the easiness of your life.}
{343}{035}{Maurissa，你住在整个Radius最安全、最平静、最宁静、最美妙的地方。这里的每个人都会支持你——即使他们有时会恶作剧。你们是一个大家庭。任何危险的局外人都不会来到这里。所以你可以把它从你的脑海中抹去，感受你生活的轻松。 -- Maurissa, you live in the safest, calmest, peaceful, and wonderful place in the whole Radius. Everyone here would stand for you - even if they are pulling some pranks sometimes. You are one big family. Any dangerous outsider just won't make it here. So you can just put it off your mind, and feel the easiness of your life.}
### {344}{035}{You need to be more self-confident! All your problems caused by your suspiciousness.}
{344}{035}{你需要更加自信！你所有的问题都是由你的怀疑引起的。 -- You need to be more self-confident! All your problems caused by your suspiciousness.}
### {345}{035}{Try this [give her Brainiac]. Ask your husband to supply you with it. }
{345}{035}{试试这个[给她布雷尼亚克]。请你丈夫提供给你。 -- Try this [give her Brainiac]. Ask your husband to supply you with it. }

#Node035
### {350}{}{You know what, it seems like a great idea. I will try it, thank you!}
{350}{}{你知道吗，这似乎是个好主意。我会试试的，谢谢！ -- You know what, it seems like a great idea. I will try it, thank you!}
### {351}{999}{That's much better! I need to go now. Hope you will be alright when I see you again.}
{351}{999}{这样好多了！我现在得走了。希望我再次见到你时你会没事的。 -- That's much better! I need to go now. Hope you will be alright when I see you again.}
### {352}{999}{(Why do I always helping some messed up people?) Sure, bye.}
{352}{999}{（为什么我总是帮助那些搞砸的人？）当然，再见。 -- (Why do I always helping some messed up people?) Sure, bye.}


#Node041
### {411}{}{Of course! Ask! }
{411}{}{当然问 -- Of course! Ask! }
### {412}{042}{How are you doing?}
{412}{042}{你好吗？ -- How are you doing?}
### {413}{999}{Oh... I've just remembered about some urgent thing I need to do. See you soon, bye.}
{413}{999}{哦我刚想起一件急需做的事。再见。 -- Oh... I've just remembered about some urgent thing I need to do. See you soon, bye.}

#Node042
### {420}{}{Actually, a lot better... Thanks to you!}
{420}{}{事实上，好多了。。。谢谢你！ -- Actually, a lot better... Thanks to you!}
### {421}{999}{That's what I wanted to hear. Okay, I need to go. Will come by later. }
{421}{999}{这就是我想听到的。好的，我得走了。稍后会来。 -- That's what I wanted to hear. Okay, I need to go. Will come by later. }

#Node050
### {500}{}{[She heavily sighs.] }
{500}{}{[她重重地叹了口气。] -- [She heavily sighs.] }
### {501}{052}{Yes, this is how it is... [avoid looking into her eyes]}
{501}{052}{是的，事情就是这样…[避免看着她的眼睛] -- Yes, this is how it is... [avoid looking into her eyes]}
### {502}{051}{There's a phrase I remember from one ancient book: "Treat the soul with experience". I think it would work for you. Find an occupation of your liking, something to do, something you can put your soul into. Try making clothes for children, working as a caravan merchant, collecting something rare. Take a trip somewhere. Do something!}
{502}{051}{我记得一本古书中有一句话：“用经验对待灵魂”。我认为这对你有用。找一个你喜欢的职业，做一些事情，做一些你可以投入灵魂的事情。试着为孩子们做衣服，做商队商人，收集一些稀有的东西。去某个地方旅行。做点什么！ -- There's a phrase I remember from one ancient book: "Treat the soul with experience". I think it would work for you. Find an occupation of your liking, something to do, something you can put your soul into. Try making clothes for children, working as a caravan merchant, collecting something rare. Take a trip somewhere. Do something!}

#Node051
### {510}{}{[she gives you a really long stare] What do I lose? I... I guess I just need to try. And keep trying until I find something I love. Right?}
{510}{}{[她瞪了你很长一眼]我失去了什么？我…我想我只需要试试。继续努力，直到我找到我喜欢的东西。正确的 -- [she gives you a really long stare] What do I lose? I... I guess I just need to try. And keep trying until I find something I love. Right?}
### {511}{999}{Right. I'm so glad to hear it. Good luck to you.}
{511}{999}{正确的我很高兴听到。祝你好运。 -- Right. I'm so glad to hear it. Good luck to you.}

#Node052
### {520}{}{[now she is crying loudly.]}
{520}{}{[现在她哭得很大声。 -- now she is crying loudly.]}
### {521}{053}{Uh... Pull it together, will you...}
{521}{053}{嗯齐心协力，你会。。。 -- Uh... Pull it together, will you...}
### {522}{999}{[leave her]}
{522}{999}{[离开她 -- leave her]}

#Node053
### {530}{}{[She doesn't hear you. She keeps crying.]}
{530}{}{[她没有听到你说话。她一直哭。 -- She doesn't hear you. She keeps crying.]}
### {531}{999}{[leave her]}
{531}{999}{[离开她 -- leave her]}

#Node060
### {600}{}{I am sure about that! I'm so happy you understand. }
{600}{}{我确信！我很高兴你能理解。 -- I am sure about that! I'm so happy you understand. }
### {601}{019}{Maybe you can tell me about yourself?}
{601}{019}{也许你可以告诉我你自己的情况？ -- Maybe you can tell me about yourself?}
### {602}{999}{I'll go look for him!}
{602}{999}{我去找他！ -- I'll go look for him!}

#Node070
### {700}{}{[she is really trying to understand any bit from what you've just said] And what does it all mean?}
{700}{}{[她真的试图从你刚才说的话中理解任何一点]这一切意味着什么？ -- [she is really trying to understand any bit from what you've just said] And what does it all mean?}
### {701}{034}{That your brain is working not quite right, distorting your reality. You see the things that don't exist. And look what it did to you... You became unhappy! But the good news is that everything can be fixed.}
{701}{034}{你的大脑工作不太正常，扭曲了你的现实。你看到了不存在的东西。看看它对你做了什么。。。你变得不开心了！但好消息是，一切都可以修复。 -- That your brain is working not quite right, distorting your reality. You see the things that don't exist. And look what it did to you... You became unhappy! But the good news is that everything can be fixed.}

#Node080
### {800}{}{No! I am right! I know this... I... [she starts crying]}
{800}{}{不我是对的！我知道。。。我…[她开始哭了] -- No! I am right! I know this... I... [she starts crying]}
### {801}{052}{[wait for a while]}
{801}{052}{[等一下 -- wait for a while]}
