##############################
#???????: ???
#???: ???
#??????? ????????: ???????? ???????????? ???
#???? ????????: 05.08.2014
##############################
#??? ???? "????? 2207"
#????? "Rainman" ????????
##############################
#
#???????? ????????
#
# ?? ??????????
### {1}{}{You see an intelligently-looking ghoul.}
{1}{}{你看到一个聪明的食尸鬼。 -- You see an intelligently-looking ghoul.}
### {2}{}{He looks quite peaceful - and surprisingly handsome.}
{2}{}{他看起来很平和，而且出奇地英俊。 -- He looks quite peaceful - and surprisingly handsome.}
#
# ????? ??????????
### {3}{}{You see Sam.}
{3}{}{你看到萨姆了。 -- You see Sam.}
### {4}{}{He is rummaging through some papers, as usual.}
{4}{}{他像往常一样在翻找一些文件。 -- He is rummaging through some papers, as usual.}
#
#????? ?????????? ??????
#
### {10}{}{[You see an ancient ghoul with peeling skin and some ulcers around his body. He turns to you and smiles - but you feel terrified because it looks like the death itself grins at you in your last seconds.] Hello. What can I do for you? }
{10}{}{[你看到一个皮肤剥落、身上有溃疡的古代食尸鬼。他转向你微笑——但你会感到害怕，因为看起来死亡本身在你生命的最后几秒向你微笑。]你好。我能为你做什么？ -- [You see an ancient ghoul with peeling skin and some ulcers around his body. He turns to you and smiles - but you feel terrified because it looks like the death itself grins at you in your last seconds.] Hello. What can I do for you? }
### {11}{002}{Hello. I'm looking around the town, I'm new here. Just came by to talk.}
{11}{002}{你好我在城里四处看看，我是新来的。只是过来聊聊。 -- Hello. I'm looking around the town, I'm new here. Just came by to talk.}
### {12}{003}{Do you realize that you smell bad, to say the least?}
{12}{003}{至少可以说，你意识到你身上有臭味吗？ -- Do you realize that you smell bad, to say the least?}

### {20}{}{Well, let's become formally introduced. I'm Sam. Are you here on business? Or just want to talk?}
{20}{}{好吧，让我们正式介绍一下。我叫萨姆。你是来出差的吗？还是只是想聊聊？ -- Well, let's become formally introduced. I'm Sam. Are you here on business? Or just want to talk?}
### {21}{010}{I'd like to ask a few questions.}
{21}{010}{我想问几个问题。 -- I'd like to ask a few questions.}

### {30}{}{You got a mouth, I see... However, let's become formally introduced. I'm Sam. Are you here on business? Or just want to discuss my charming pheromones?}
{30}{}{你有一张嘴巴，我明白了。。。不过，让我们正式介绍一下。我叫萨姆。你是来出差的吗？或者只是想讨论我迷人的信息素？ -- You got a mouth, I see... However, let's become formally introduced. I'm Sam. Are you here on business? Or just want to discuss my charming pheromones?}
### {31}{010}{Uh, okay, let's talk. I want to ask something.}
{31}{010}{好吧，我们谈谈。我想问个问题。 -- Uh, okay, let's talk. I want to ask something.}
### {32}{004}{Phero-what?}
{32}{004}{费罗什么？ -- Phero-what?}


### {40}{}{Oh... Forget it. Do you want something?}
{40}{}{哦算了，你想要什么吗？ -- Oh... Forget it. Do you want something?}
### {41}{010}{Yes, I suppose...}
{41}{010}{是的，我想。。。 -- Yes, I suppose...}
### {42}{010}{Yes.}
{42}{010}{对 -- Yes.}

### {1000}{}{Come on then, say it.}
{1000}{}{那就来吧，说出来。 -- Come on then, say it.}
### {1001}{}{Hello. Come, let's talk.}
{1001}{}{你好来，我们谈谈。 -- Hello. Come, let's talk.}
### {1002}{}{Here comes our new Leader. I hope you won't flush my life's work down the toilet [he smiles]. Ask me if you need anything. I know every nook and cranny here.}
{1002}{}{我们的新领导人来了。我希望你不要把我一生的工作都冲到马桶上[他笑着]。问我你是否需要什么。我知道这里的每一个角落。 -- Here comes our new Leader. I hope you won't flush my life's work down the toilet [he smiles]. Ask me if you need anything. I know every nook and cranny here.}
### {1003}{}{Oh, hello! How are you? Have questions? I'm quite busy lately, but I can spare five minutes...}
{1003}{}{哦，你好！你好吗有问题吗？我最近很忙，但我能抽出五分钟。。。 -- Oh, hello! How are you? Have questions? I'm quite busy lately, but I can spare five minutes...}
### {1004}{}{Hello. [he looks saddened]}
{1004}{}{你好[他看起来很悲伤] -- Hello. [he looks saddened]}
### {101}{054}{Sam, what do you do here?}
{101}{054}{山姆，你在这里做什么？ -- Sam, what do you do here?}
### {102}{051}{About the problem with the water...}
{102}{051}{关于水的问题。。。 -- About the problem with the water...}
### {103}{011}{There aren't many ghouls around. How did you end up here?}
{103}{011}{周围没有多少食尸鬼。你是怎么来到这里的？ -- There aren't many ghouls around. How did you end up here?}
### {104}{019}{Tell me about yourself.}
{104}{019}{告诉我你自己的情况。 -- Tell me about yourself.}
### {105}{020}{Can you tell me something about the town?}
{105}{020}{你能告诉我一些关于这个城镇的情况吗？ -- Can you tell me something about the town?}
### {106}{023}{Sam, I've heard you quarrel with Lucy. Mind to tell me about it?}
{106}{023}{山姆，我听说你和露西吵架了。介意告诉我这件事吗？ -- Sam, I've heard you quarrel with Lucy. Mind to tell me about it?}
### {107}{058}{Sam, who is going to be the next Mayor, what do you think? Who do you want to see in this position?}
{107}{058}{山姆，谁将成为下一任市长，你觉得怎么样？你想在这个职位上看到谁？ -- Sam, who is going to be the next Mayor, what do you think? Who do you want to see in this position?}
### {108}{059}{How's life, Sam?}
{108}{059}{生活怎么样，山姆？ -- How's life, Sam?}
### {109}{999}{I need to go, talk later.}
{109}{999}{我得走了，稍后再谈。 -- I need to go, talk later.}


### {110}{}{[Sam laughs] I was born here - and died here! And will stay here until I die completely. New World Order is my reason to live, so to say.}
{110}{}{[山姆笑着说]我出生在这里，死在这里！并且会一直呆在这里直到我彻底死去。可以说，新的世界秩序是我活着的理由。 -- [Sam laughs] I was born here - and died here! And will stay here until I die completely. New World Order is my reason to live, so to say.}
### {111}{012}{You probably did a lot to NWO?}
{111}{012}{你可能对NWO做了很多？ -- You probably did a lot to NWO?}
### {112}{016}{Is NWO everything you care about?}
{112}{016}{NWO是你所关心的一切吗？ -- Is NWO everything you care about?}
### {113}{015}{How come you are ghoul? How did you become like that?}
{113}{015}{你怎么是食尸鬼？你是怎么变成那样的？ -- How come you are ghoul? How did you become like that?}
### {114}{020}{What else can you tell me about this place?}
{114}{020}{关于这个地方，你还能告诉我什么？ -- What else can you tell me about this place?}
### {115}{010}{I see. Another question then.}
{115}{010}{我明白了。那又是一个问题。 -- I see. Another question then.}


### {120}{}{[Sam looks into the distance] Some time ago, I was the Mayor of this beautiful town. I and my team built this place practically from sand and dust, turning a small settlement into a place known far beyond its borders.}
{120}{}{[山姆望向远方]不久前，我还是这个美丽小镇的市长。我和我的团队几乎用沙子和灰尘建造了这个地方，把一个小定居点变成了一个远超国界的地方。 -- [Sam looks into the distance] Some time ago, I was the Mayor of this beautiful town. I and my team built this place practically from sand and dust, turning a small settlement into a place known far beyond its borders.}
### {121}{020}{And what is NWO now?}
{121}{020}{现在什么是NWO？ -- And what is NWO now?}
### {122}{015}{Why did you leave Leader's position?}
{122}{015}{你为什么离开领袖的职位？ -- Why did you leave Leader's position?}
### {123}{013}{What happened to your team?}
{123}{013}{你的团队发生了什么事？ -- What happened to your team?}
### {124}{010}{Another question.}
{124}{010}{另一个问题。 -- Another question.}

### {130}{}{They died, every last one of them. From old age, illnesses, hands of bandits. I outlived them all. If only they were alive, my old fellas... We could do so much more! And now you can't even find someone suitable for a Leader of this place, let alone the people with a common goal.}
{130}{}{他们每个人都死了。从年老，疾病，土匪之手。我活得比他们都长。要是他们还活着就好了，我的老伙计们。。。我们可以做得更多！现在你甚至找不到适合这个地方的领导人，更不用说有共同目标的人了。 -- They died, every last one of them. From old age, illnesses, hands of bandits. I outlived them all. If only they were alive, my old fellas... We could do so much more! And now you can't even find someone suitable for a Leader of this place, let alone the people with a common goal.}
### {131}{018}{The current Leader is no good? Is that what you're saying?}
{131}{018}{现任领导人不好？你是这么说的吗？ -- The current Leader is no good? Is that what you're saying?}
### {132}{014}{Why didn't you continue the work of your team?}
{132}{014}{你为什么不继续你团队的工作？ -- Why didn't you continue the work of your team?}
### {133}{010}{Let me ask something else.}
{133}{010}{让我再问一个问题。 -- Let me ask something else.}

### {140}{}{Now here you are wrong - all these years I keep helping the development of NWO. Of course, when I was Mayor, I had more... Capabilities. Now I mostly assist Mark, my grandson. He's the Mayor.}
{140}{}{现在你错了——这些年来，我一直在帮助NWO的发展。当然，当我担任市长时，我有更多。。。能力。现在我主要帮助我的孙子马克。他是市长。 -- Now here you are wrong - all these years I keep helping the development of NWO. Of course, when I was Mayor, I had more... Capabilities. Now I mostly assist Mark, my grandson. He's the Mayor.}
### {141}{018}{Tell me about Mark.}
{141}{018}{告诉我关于马克的事。 -- Tell me about Mark.}
### {142}{015}{Why did you leave Mayor's position?}
{142}{015}{你为什么离开市长的职位？ -- Why did you leave Mayor's position?}
### {143}{010}{I want to ask something else.}
{143}{010}{我想问别的问题。 -- I want to ask something else.}

### {150}{}{When I was Mayor, I got very sick. I thought I won't make it to the end of the week. So, there was a need to elect a new Mayor, and they put my son in my place. For a few months, I was lying delirious, while damned radiation was doing its job. In the end, I didn't die and recovered... If you can call it that [with a smile, Sam points to pieces of skin sagging off his shoulder]. After "recovery" I started assisting my son, and then his son, Mark. You know, it's hard to see your family die... But what can I do about it? Not everyone as "lucky" as I am.}
{150}{}{当我担任市长时，我病得很重。我以为我撑不到周末了。因此，有必要选举一位新市长，他们让我儿子接替我的位置。几个月来，我一直躺在那里，神志不清，而该死的辐射正在发挥作用。最后，我没有死，并且康复了。。。如果你可以这么说的话（山姆微笑着指着肩膀上下垂的几块皮肤）。“康复”后，我开始帮助我的儿子，然后是他的儿子马克。你知道，很难看到你的家人死去。。。但是我该怎么办呢？不是每个人都像我这样“幸运”。 -- When I was Mayor, I got very sick. I thought I won't make it to the end of the week. So, there was a need to elect a new Mayor, and they put my son in my place. For a few months, I was lying delirious, while damned radiation was doing its job. In the end, I didn't die and recovered... If you can call it that [with a smile, Sam points to pieces of skin sagging off his shoulder]. After "recovery" I started assisting my son, and then his son, Mark. You know, it's hard to see your family die... But what can I do about it? Not everyone as "lucky" as I am.}
### {151}{018}{What can you say about your grandson?}
{151}{018}{关于你的孙子，你能说些什么？ -- What can you say about your grandson?}
### {152}{010}{I see. I have another question.}
{152}{010}{我明白了。我还有一个问题。 -- I see. I have another question.}

### {160}{}{Of course not. My family is what I care about the most. My town and my family. These two things are interconnected with each other. All our lives are dedicated to NWO, so the development of the town wouldn't stop. Although, lately we have some serious problems... }
{160}{}{当然不是。我最关心的是我的家庭。我的城镇和我的家人。这两件事是相互联系的。我们的一生都致力于NWO，所以这个小镇的发展不会停止。尽管最近我们遇到了一些严重的问题。。。 -- Of course not. My family is what I care about the most. My town and my family. These two things are interconnected with each other. All our lives are dedicated to NWO, so the development of the town wouldn't stop. Although, lately we have some serious problems... }
### {161}{021}{Tell me about your family.}
{161}{021}{告诉我你的家庭情况。 -- Tell me about your family.}
### {162}{023}{What problems are you talking about?}
{162}{023}{你在说什么问题？ -- What problems are you talking about?}
### {163}{017}{Are you willing to develop NWO no matter what?}
{163}{017}{不管怎样，你愿意发展NWO吗？ -- Are you willing to develop NWO no matter what?}
### {164}{010}{Okay, I'll ask something else.}
{164}{010}{好吧，我再问别的问题。 -- Okay, I'll ask something else.}

### {170}{}{Of course! I'd do everything so the town would thrive. I could even apply for the Mayor and continue the legacy of our family. I even want this, damn it! No man here has such vast experience of running this settlement as me. I can handle being the Mayor, even in these sad circumstances.}
{170}{}{当然我会尽一切努力让小镇繁荣起来。我甚至可以申请市长，继承我们家族的遗产。我甚至想要这个，该死！这里没有人像我这样有丰富的管理这个定居点的经验。即使在这种悲伤的情况下，我也能胜任市长的工作。 -- Of course! I'd do everything so the town would thrive. I could even apply for the Mayor and continue the legacy of our family. I even want this, damn it! No man here has such vast experience of running this settlement as me. I can handle being the Mayor, even in these sad circumstances.}
### {171}{018}{Sad circumstances? What do you mean?}
{171}{018}{悲伤的环境？你是什么意思？ -- Sad circumstances? What do you mean?}

### {180}{}{For now, my grandson Mark is in charge. He is a good Mayor and has done a lot for the town. But he is very sick and won't last long. Mark should name his successor. And there's no one around here who is good enough for succeeding him. For example, his son Daniel is completely incapable of being the Leader. He will ruin everything! And he is a good kid, but still quite light-headed. So, until he's ready, I could lead the settlement. That's what I want.}
{180}{}{现在，我的孙子马克负责。他是个好市长，为这个城市做了很多事。但他病得很重，活不了多久了。马克应该提名他的继任者。这里没有一个人能胜任接替他的工作。例如，他的儿子丹尼尔完全没有能力成为领袖。他会毁了一切！他是个好孩子，但头脑还是很清醒。所以，在他准备好之前，我可以领导和解。这就是我想要的。 -- For now, my grandson Mark is in charge. He is a good Mayor and has done a lot for the town. But he is very sick and won't last long. Mark should name his successor. And there's no one around here who is good enough for succeeding him. For example, his son Daniel is completely incapable of being the Leader. He will ruin everything! And he is a good kid, but still quite light-headed. So, until he's ready, I could lead the settlement. That's what I want.}
### {181}{022}{Tell me more about Daniel.}
{181}{022}{告诉我更多关于丹尼尔的事。 -- Tell me more about Daniel.}
### {182}{021}{What else can you say about your family?}
{182}{021}{关于你的家庭，你还能说些什么？ -- What else can you say about your family?}
### {183}{010}{Okay, let me ask something else.}
{183}{010}{好吧，让我问其他问题。 -- Okay, let me ask something else.}

### {190}{}{Uh, what can I say about me... I devoted all of my life to my family and my town. I think nobody else has done so much for NWO as myself. And I love my family very much, although not everything great in it. Because of some of its members...}
{190}{}{呃，我能说些什么呢…我把我的一生都奉献给了我的家庭和我的小镇。我想没有人能像我一样为NWO做这么多。我非常爱我的家庭，虽然不是所有的事情都很好。因为它的一些成员。。。 -- Uh, what can I say about me... I devoted all of my life to my family and my town. I think nobody else has done so much for NWO as myself. And I love my family very much, although not everything great in it. Because of some of its members...}
### {191}{023}{Who do you mean?}
{191}{023}{你是说谁？ -- Who do you mean?}
### {192}{020}{What can you tell me about NWO?}
{192}{020}{关于NWO，你能告诉我什么？ -- What can you tell me about NWO?}
### {193}{010}{Let's get back to other questions.}
{193}{010}{让我们回到其他问题上来。 -- Let's get back to other questions.}

### {200}{}{New World Order is the best place in the whole Radius. Its name reflects all the main principles we follow. Firstly, Order. We maintain peace here, ensured by our guards. Secondly, New. We are creating a new society, where anyone could feel protected and confident in his future. Thirdly, World. Our ideas and principles go far beyond us, there are more and more people in other places who support our worldview. It is possible for us to become a center of a New World, and that's what we are aiming for.}
{200}{}{新世界秩序是整个半径中最好的地方。它的名字反映了我们遵循的所有主要原则。第一，秩序。我们在这里维持和平，由我们的警卫保证。第二，新。我们正在创造一个新的社会，在那里，任何人都可以对自己的未来感到保护和信心。第三，世界。我们的想法和原则远远超出了我们的范围，在其他地方有越来越多的人支持我们的世界观。我们有可能成为新世界的中心，这就是我们的目标。 -- New World Order is the best place in the whole Radius. Its name reflects all the main principles we follow. Firstly, Order. We maintain peace here, ensured by our guards. Secondly, New. We are creating a new society, where anyone could feel protected and confident in his future. Thirdly, World. Our ideas and principles go far beyond us, there are more and more people in other places who support our worldview. It is possible for us to become a center of a New World, and that's what we are aiming for.}
### {201}{010}{I see. I want to ask something else.}
{201}{010}{我明白了。我想问别的问题。 -- I see. I want to ask something else.}

### {210}{}{My family means everything to me. There's Mark, my grandson, Lucy, his wife, damn her... And there's also Daniel, my, great-grandson... If you can call him that. Who you want to know about?}
{210}{}{我的家庭对我来说意味着一切。有马克，我的孙子，露西，他的妻子，该死的她。。。还有丹尼尔，我的曾孙。。。如果你能这样称呼他。你想了解谁？ -- My family means everything to me. There's Mark, my grandson, Lucy, his wife, damn her... And there's also Daniel, my, great-grandson... If you can call him that. Who you want to know about?}
### {211}{018}{Tell me about Mark.}
{211}{018}{告诉我关于马克的事。 -- Tell me about Mark.}
### {212}{023}{What can you say about Lucy?}
{212}{023}{关于露西，你能说些什么？ -- What can you say about Lucy?}
### {213}{022}{I'd like to hear about Daniel.}
{213}{022}{我想听听丹尼尔的情况。 -- I'd like to hear about Daniel.}
### {214}{010}{I want to ask something else.}
{214}{010}{我想问别的问题。 -- I want to ask something else.}

### {220}{}{Daniel is a good kid, but he's still young. He needs to learn so much - but all he is busy with is doing petty pranks all day long. I don't mind him becoming Mayor after Mark, but as for now - he is just not ready. And if he won't get his mind right, I won't let him become the Mayor. Even if I have to resort to extreme measures.}
{220}{}{丹尼尔是个好孩子，但他还年轻。他需要学习很多东西，但他整天忙于做一些小恶作剧。我不介意他在马克之后成为市长，但就目前而言，他只是还没有准备好。如果他头脑不清醒，我就不会让他当市长。即使我不得不采取极端措施。 -- Daniel is a good kid, but he's still young. He needs to learn so much - but all he is busy with is doing petty pranks all day long. I don't mind him becoming Mayor after Mark, but as for now - he is just not ready. And if he won't get his mind right, I won't let him become the Mayor. Even if I have to resort to extreme measures.}
### {221}{023}{Why do you think Daniel is not ready?}
{221}{023}{为什么你认为丹尼尔还没有准备好？ -- Why do you think Daniel is not ready?}
### {222}{027}{Do you mean you are ready to kill Daniel?}
{222}{027}{你是说你已经准备好杀死丹尼尔了吗？ -- Do you mean you are ready to kill Daniel?}
### {223}{010}{I see. Another question then.}
{223}{010}{我明白了。那又是一个问题。 -- I see. Another question then.}

### {2301}{}{[Sam becomes moody] Lucy... Mark's wife. The problem is that she is a brainless stupid chick. I was actually against Mark marrying her... She didn't let him raise his son in the ways that Mark himself was raised. So, Daniel grew up not capable of being a Mayor at all. I wouldn't allow Lucy to tend the Lavash, let alone raising a son! She treats Danial as a little child, not letting him make the decisions by himself.}
{2301}{}{[山姆变得喜怒无常]露西。。。马克的妻子。问题是她是一个没有头脑的愚蠢女孩。实际上我反对马克娶她。。。她不让他像马克那样抚养儿子。因此，丹尼尔在成长过程中根本没有能力当市长。我不允许露西照看熔岩，更不用说抚养儿子了！她把达尼尔当作小孩子对待，不让他自己做决定。 -- [Sam becomes moody] Lucy... Mark's wife. The problem is that she is a brainless stupid chick. I was actually against Mark marrying her... She didn't let him raise his son in the ways that Mark himself was raised. So, Daniel grew up not capable of being a Mayor at all. I wouldn't allow Lucy to tend the Lavash, let alone raising a son! She treats Danial as a little child, not letting him make the decisions by himself.}
### {2302}{}{We have our problems, but the situation with Lucy gets better every day. I think soon we'll forget we were quarreling. For that, I thank you.}
{2302}{}{我们有自己的问题，但露西的情况一天比一天好。我想我们很快就会忘记我们在吵架。为此，我感谢你。 -- We have our problems, but the situation with Lucy gets better every day. I think soon we'll forget we were quarreling. For that, I thank you.}
### {2303}{}{We have our problems, but the situation with Lucy gets better every day. No open conflicts anymore. Although, Lucy tries to sit on my head, making me help her to do dirty little jobs...}
{2303}{}{我们有自己的问题，但露西的情况一天比一天好。不再有公开的冲突。虽然，露西试图坐在我的头上，让我帮她做一些肮脏的小工作。。。 -- We have our problems, but the situation with Lucy gets better every day. No open conflicts anymore. Although, Lucy tries to sit on my head, making me help her to do dirty little jobs...}
### {231}{024}{It seems like you hate her.}
{231}{024}{你好像讨厌她。 -- It seems like you hate her.}
### {232}{025}{Sam, did you try to make peace with her?}
{232}{025}{山姆，你想和她讲和吗？ -- Sam, did you try to make peace with her?}
### {233}{010}{I want to ask something else.}
{233}{010}{我想问别的问题。 -- I want to ask something else.}

### {240}{}{No, I don't hate her. But I don't love her either. If Mark married her, then it's his problem. If she wouldn't interfere with raising Daniel, everything would have been alright. And also - she sleeps with everyone. And that is noticed by everybody, except Mark. We have huge fights with her lately... As you see, I'm not fond of her at all, and I don't try to keep it a secret. But if she would come and try to make peace, I'd consider it. The family must live in peace, after all. }
{240}{}{不，我不恨她。但我也不爱她。如果马克娶了她，那就是他的问题了。如果她不干涉抚养丹尼尔，一切都会好起来的。而且——她和每个人都睡在一起。每个人都注意到了这一点，除了马克。最近我们和她大吵了一架。。。正如你所见，我一点也不喜欢她，我也不想保守秘密。但如果她愿意来和我讲和，我会考虑的。毕竟，这个家庭必须和平相处。 -- No, I don't hate her. But I don't love her either. If Mark married her, then it's his problem. If she wouldn't interfere with raising Daniel, everything would have been alright. And also - she sleeps with everyone. And that is noticed by everybody, except Mark. We have huge fights with her lately... As you see, I'm not fond of her at all, and I don't try to keep it a secret. But if she would come and try to make peace, I'd consider it. The family must live in peace, after all. }
### {241}{025}{Didn't you think about making the first step yourself?}
{241}{025}{你没有想过自己迈出第一步吗？ -- Didn't you think about making the first step yourself?}
### {242}{010}{Yeah. I better ask something else.}
{242}{010}{是 啊我最好问问别的。 -- Yeah. I better ask something else.}

### {250}{}{[Sam raises voice] You wish! I'm not going first to that windbag! The truth is on my side, and I won't let her do things she does in front of Mark and Daniel!}
{250}{}{[山姆提高声音]你愿意！我不会先去那个风箱！事实是站在我这边的，我不会让她在马克和丹尼尔面前做她做的事情！ -- [Sam raises voice] You wish! I'm not going first to that windbag! The truth is on my side, and I won't let her do things she does in front of Mark and Daniel!}
### {251}{010}{Maybe you're right. Let's change the subject.}
{251}{010}{也许你是对的。让我们换个话题。 -- Maybe you're right. Let's change the subject.}
### {252}{026}{Sam, maybe Lucy is not faithful to Mark, and she doesn't have a lot of brains, but she is a devoted mother. She would do anything for Daniel, and you know that. Nobody is perfect. For peace in a family, somebody should make compromises. Try to talk to her. The quarrel makes things only worse.}
{252}{026}{山姆，也许露西对马克不忠诚，她没有多少头脑，但她是一个忠诚的母亲。她愿意为丹尼尔做任何事，你知道的。没有人是完美的。为了家庭的和平，应该有人做出妥协。试着和她谈谈。争吵只会使事情变得更糟。 -- Sam, maybe Lucy is not faithful to Mark, and she doesn't have a lot of brains, but she is a devoted mother. She would do anything for Daniel, and you know that. Nobody is perfect. For peace in a family, somebody should make compromises. Try to talk to her. The quarrel makes things only worse.}
### {253}{047}{Sam, you will go and try to make peace with her. Or I'll tell everyone that you are stealing batteries from the treasury.}
{253}{047}{山姆，你会去和她讲和的。或者我会告诉所有人你在从国库偷电池。 -- Sam, you will go and try to make peace with her. Or I'll tell everyone that you are stealing batteries from the treasury.}

### {260}{}{You know, maybe you're right. The family always comes first - and I am willing to humiliate myself to maintain peace in it. Okay, I'll try talking to Lucy. Thank you for helping me to realize this, you deserve my respect.}
{260}{}{你知道，也许你是对的。家庭总是第一位的，我愿意羞辱自己以维护家庭的和平。好吧，我试着和露西谈谈。谢谢你帮助我认识到这一点，你值得我尊敬。 -- You know, maybe you're right. The family always comes first - and I am willing to humiliate myself to maintain peace in it. Okay, I'll try talking to Lucy. Thank you for helping me to realize this, you deserve my respect.}
### {261}{010}{The right thing to do! I want to ask something else.}
{261}{010}{正确的做法！我想问别的问题。 -- The right thing to do! I want to ask something else.}
### {262}{999}{That's really great. Okay, I need to go, bye.}
{262}{999}{真是太棒了。好的，我得走了，再见。 -- That's really great. Okay, I need to go, bye.}

### {270}{}{[Sam laughs] Of course not! I'm not going to kill Daniel! By extreme measures, I mean a completely different thing. I know something that won't allow Daniel to be put in charge, heh-heh. And I'm ready to use this knowledge, even if it will harm both Mark and Daniel. I'm willing to do that if NWO's future would be threatened - but I still want to consider other options of resolving the situation.}
{270}{}{[山姆笑]当然不是！我不会杀了丹尼尔！我所说的极端措施是指完全不同的事情。我知道一些事情不允许丹尼尔负责，呵呵。我准备利用这些知识，即使这会伤害马克和丹尼尔。如果NWO的未来受到威胁，我愿意这么做，但我仍然想考虑解决这种情况的其他选择。 -- [Sam laughs] Of course not! I'm not going to kill Daniel! By extreme measures, I mean a completely different thing. I know something that won't allow Daniel to be put in charge, heh-heh. And I'm ready to use this knowledge, even if it will harm both Mark and Daniel. I'm willing to do that if NWO's future would be threatened - but I still want to consider other options of resolving the situation.}
### {271}{028}{What knowledge are you talking about?}
{271}{028}{你在说什么知识？ -- What knowledge are you talking about?}
### {272}{029}{What knowledge are you talking about?}
{272}{029}{你在说什么知识？ -- What knowledge are you talking about?}
### {273}{030}{What knowledge are you talking about?}
{273}{030}{你在说什么知识？ -- What knowledge are you talking about?}

### {280}{}{Hah, aren't you a smart one. Do you really think I would tell this to anyone? I have enough problems on my plate, because of a certain someone. I don't want to make it worse. If you earn some of my respect, I would consider telling you.}
{280}{}{哈，你不是个聪明人吗。你真的认为我会告诉任何人吗？因为某个人，我的问题已经够多了。我不想让事情变得更糟。如果你赢得我的尊重，我会考虑告诉你。 -- Hah, aren't you a smart one. Do you really think I would tell this to anyone? I have enough problems on my plate, because of a certain someone. I don't want to make it worse. If you earn some of my respect, I would consider telling you.}
### {281}{023}{Who is the certain someone, the cause of your problems?}
{281}{023}{谁是你问题的根源？ -- Who is the certain someone, the cause of your problems?}
### {282}{010}{Okay, I'll try to earn some of your respect. And now I want to ask a question.}
{282}{010}{好吧，我会努力赢得你的尊重。现在我想问一个问题。 -- Okay, I'll try to earn some of your respect. And now I want to ask a question.}
### {283}{999}{I'll try to earn some of your respect. I'll go think about it.}
{283}{999}{我会尽力赢得你的尊重。我会去考虑的。 -- I'll try to earn some of your respect. I'll go think about it.}

### {290}{}{You helped me make peace with Lucy, so I'll tell you a secret. The thing is - Daniel is not Mark's son! Lucy had an affair with Dan before Mark, the son even named after his father. If Mark learns about it, he wouldn't put Daniel in Mayor's position. And I would become NWO's Leader again!}
{290}{}{你帮我和露西讲和了，所以我要告诉你一个秘密。问题是——但以理不是马克的儿子！在马克之前，露西和丹有过一段婚外情，这个儿子甚至以他父亲的名字命名。如果马克知道了，他不会让丹尼尔担任市长的职位。我将再次成为NWO的领导者！ -- You helped me make peace with Lucy, so I'll tell you a secret. The thing is - Daniel is not Mark's son! Lucy had an affair with Dan before Mark, the son even named after his father. If Mark learns about it, he wouldn't put Daniel in Mayor's position. And I would become NWO's Leader again!}
### {291}{010}{Oh wow, that changes things. Thanks for trusting me, Sam. I'd like to ask about something else.}
{291}{010}{哦，哇，这改变了一切。谢谢你信任我，萨姆。我想问一些其他的事情。 -- Oh wow, that changes things. Thanks for trusting me, Sam. I'd like to ask about something else.}

### {300}{}{You think you can threaten me with that story about stealing batteries and then ask me to trust you a secret? You get no respect from me for your actions, so I won't tell you anything. Despite making peace in our family, you should put a lot of effort to earn my respect.}
{300}{}{你以为你可以用偷电池的故事威胁我，然后要求我相信你的秘密吗？你的行为得不到我的尊重，所以我什么都不会告诉你。尽管我们家和睦，但你应该付出很多努力来赢得我的尊重。 -- You think you can threaten me with that story about stealing batteries and then ask me to trust you a secret? You get no respect from me for your actions, so I won't tell you anything. Despite making peace in our family, you should put a lot of effort to earn my respect.}
### {301}{031}{How can I do it?}
{301}{031}{我该怎么做？ -- How can I do it?}

### {310}{}{Respect is earned through actions. For now, you did nothing. Tell me, why should I respect you?}
{310}{}{尊重是通过行动赢得的。现在，你什么也没做。告诉我，我为什么要尊重你？ -- Respect is earned through actions. For now, you did nothing. Tell me, why should I respect you?}
### {311}{033}{I have trained a lot, so I'm in perfect physical shape.}
{311}{033}{我训练了很多，所以我的身体状况很好。 -- I have trained a lot, so I'm in perfect physical shape.}
### {312}{037}{I'm very smart and acute. I read a lot and learned many things.}
{312}{037}{我非常聪明和敏锐。我读了很多书，学到了很多东西。 -- I'm very smart and acute. I read a lot and learned many things.}
### {313}{032}{I'm highly skilled in weaponry, I had a lot of practice.}
{313}{032}{我在武器方面非常熟练，我有很多练习。 -- I'm highly skilled in weaponry, I had a lot of practice.}
### {314}{050}{I am pretty good at medical science, can give some advice.}
{314}{050}{我很擅长医学，可以给一些建议。 -- I am pretty good at medical science, can give some advice.}
### {315}{040}{I'm great with technical stuff, I know much about working with mechanisms.}
{315}{040}{我擅长技术方面的东西，我对机械方面的工作了解很多。 -- I'm great with technical stuff, I know much about working with mechanisms.}
### {316}{041}{How can I prove that I deserve some respect?}
{316}{041}{我怎样才能证明我值得尊重？ -- How can I prove that I deserve some respect?}

### {320}{}{[Sam cringes] As any bandit in Radius. I don't respect solving problems by force.}
{320}{}{[山姆畏缩]就像Radius里的强盗一样。我不尊重用武力解决问题。 -- [Sam cringes] As any bandit in Radius. I don't respect solving problems by force.}
### {321}{010}{Too bad. Another question then.}
{321}{010}{太糟糕了。那又是一个问题。 -- Too bad. Another question then.}

### {330}{}{Well, a healthy mind means a healthy body. Show me what you're capable of. Do something.}
{330}{}{健康的头脑意味着健康的身体。让我看看你的能力。做点什么。 -- Well, a healthy mind means a healthy body. Show me what you're capable of. Do something.}
### {331}{034}{I'm ready! [demonstrate your physical capabilities]}
{331}{034}{我准备好了！[展示你的体能] -- I'm ready! [demonstrate your physical capabilities]}
### {332}{035}{I'm ready! [demonstrate your physical capabilities]}
{332}{035}{我准备好了！[展示你的体能] -- I'm ready! [demonstrate your physical capabilities]}
### {333}{010}{I'm not quite ready now. I better ask some questions.}
{333}{010}{我现在还没准备好。我最好问一些问题。 -- I'm not quite ready now. I better ask some questions.}

### {340}{}{[You do a somersault and some other tricks, demonstrating your great shape. Sam observes you, looking surprised] Impressive. You definitely put some work into your body. This deserves respect. }
{340}{}{[你做了一个空翻和其他一些技巧，展示了你的好身材。山姆观察到你，看起来很惊讶]令人印象深刻。你肯定对自己的身体进行了一些锻炼。这值得尊重。 -- [You do a somersault and some other tricks, demonstrating your great shape. Sam observes you, looking surprised] Impressive. You definitely put some work into your body. This deserves respect. }
### {341}{036}{Told you! So, will you tell me a secret now?}
{341}{036}{告诉你了！那么，你现在能告诉我一个秘密吗？ -- Told you! So, will you tell me a secret now?}

### {350}{}{[You do some easy athletic tricks. Sam chuckles] Hah, not very impressive, actually. Even I can do something similar - if nothing falls off me. No, that's not enough.}
{350}{}{[你做了一些简单的运动技巧。山姆笑了笑]哈，实际上不是很令人印象深刻。即使我也可以做类似的事情——如果我什么都没掉下来。不，这还不够。 -- [You do some easy athletic tricks. Sam chuckles] Hah, not very impressive, actually. Even I can do something similar - if nothing falls off me. No, that's not enough.}
### {351}{010}{A pity. Another question then.}
{351}{010}{很遗憾。那又是一个问题。 -- A pity. Another question then.}

### {360}{}{Okay, this proves you put a lot of work into yourself. I think that you have something in you. Okay, listen carefully. The thing is - Daniel is not Mark's son! Lucy had an affair with Dan before Mark, the son even named after his father. If Mark learns about it, he wouldn't put Daniel in Mayor's position. And I would become NWO's Leader again!}
{360}{}{好吧，这证明你为自己付出了很多努力。我认为你身上有某种东西。好的，仔细听。问题是——但以理不是马克的儿子！在马克之前，露西和丹有过一段婚外情，这个儿子甚至以他父亲的名字命名。如果马克知道了，他不会让丹尼尔担任市长的职位。我将再次成为NWO的领导者！ -- Okay, this proves you put a lot of work into yourself. I think that you have something in you. Okay, listen carefully. The thing is - Daniel is not Mark's son! Lucy had an affair with Dan before Mark, the son even named after his father. If Mark learns about it, he wouldn't put Daniel in Mayor's position. And I would become NWO's Leader again!}
### {361}{010}{Oh wow, that changes things. Thanks for trusting me, Sam. I'd like to ask about something else.}
{361}{010}{哦，哇，这改变了一切。谢谢你信任我，萨姆。我想问一些其他的事情。 -- Oh wow, that changes things. Thanks for trusting me, Sam. I'd like to ask about something else.}

### {370}{}{Smart and acute - that's a rarity. I have one old intellectual test. Try to pass it.}
{370}{}{聪明而敏锐——这是罕见的。我有一个旧的智力测试。试着通过它。 -- Smart and acute - that's a rarity. I have one old intellectual test. Try to pass it.}
### {371}{038}{Give me that test!}
{371}{038}{给我那个测试！ -- Give me that test!}
### {372}{039}{Give me that test!}
{372}{039}{给我那个测试！ -- Give me that test!}
### {373}{010}{I'm not quite ready now. I better ask some questions.}
{373}{010}{我现在还没准备好。我最好问一些问题。 -- I'm not quite ready now. I better ask some questions.}

### {380}{}{[You easily solve every task in the test, even coming up with alternative solutions and recommendations to make the test harder. Sam observes you, looking surprised] Impressive. You definitely put some work into your mind. This deserves respect.}
{380}{}{[你可以轻松地解决测试中的每一项任务，甚至可以想出其他解决方案和建议来让测试变得更难。Sam观察到你，看起来很惊讶]令人印象深刻。你肯定在脑子里想了一些工作。这值得尊重。 -- [You easily solve every task in the test, even coming up with alternative solutions and recommendations to make the test harder. Sam observes you, looking surprised] Impressive. You definitely put some work into your mind. This deserves respect.}
### {381}{036}{Told you! So, will you tell me a secret now?}
{381}{036}{告诉你了！那么，你现在能告诉我一个秘密吗？ -- Told you! So, will you tell me a secret now?}

### {390}{}{[You spend a lot of time on the test and fail to solve some tasks in it. Sam chuckles] Hah, not very impressive. The most interesting questions are skipped. No, that's not enough.}
{390}{}{[你在测试上花了很多时间，但没有解决其中的一些任务。Sam笑了笑]哈，不太令人印象深刻。跳过了最有趣的问题。不，这还不够。 -- [You spend a lot of time on the test and fail to solve some tasks in it. Sam chuckles] Hah, not very impressive. The most interesting questions are skipped. No, that's not enough.}
### {391}{010}{A pity. Another question then.}
{391}{010}{很遗憾。那又是一个问题。 -- A pity. Another question then.}

### {400}{}{[You help Sam to figure out details in a blueprint of an old piece of machinery, giving recommendations about how to optimize it. Sam observes you, looking surprised] Impressive. You definitely put some work into your skills. This deserves respect.}
{400}{}{[你帮助Sam在一台旧机器的蓝图中找出细节，并就如何优化它提出建议。Sam观察到你，看起来很惊讶]令人印象深刻。你肯定在你的技能上下了功夫。这值得尊重。 -- [You help Sam to figure out details in a blueprint of an old piece of machinery, giving recommendations about how to optimize it. Sam observes you, looking surprised] Impressive. You definitely put some work into your skills. This deserves respect.}
### {401}{036}{Told you! So, will you tell me a secret now?}
{401}{036}{告诉你了！那么，你现在能告诉我一个秘密吗？ -- Told you! So, will you tell me a secret now?}

### {410}{}{I don't even know... Although, there is one thing you can do for me...}
{410}{}{我甚至不知道。。。不过，你可以为我做一件事。。。 -- I don't even know... Although, there is one thing you can do for me...}
### {411}{042}{Which one?}
{411}{042}{哪一个？ -- Which one?}

### {420}{}{[Sam stumbles, not answering for some time] You already know that the batteries keep disappearing from the treasury. If you'll spare me two hundred more of them, I'll tell you everything.}
{420}{}{[山姆结结巴巴，有一段时间没有回答]你已经知道电池一直在从国库中消失。如果你能再给我二百个，我会告诉你一切的。 -- [Sam stumbles, not answering for some time] You already know that the batteries keep disappearing from the treasury. If you'll spare me two hundred more of them, I'll tell you everything.}
### {421}{043}{Of course, I have a lot of this stuff. Here's two hundred, for your healthcare.}
{421}{043}{当然，我有很多这样的东西。这是200，给你的医疗保健。 -- Of course, I have a lot of this stuff. Here's two hundred, for your healthcare.}
### {422}{044}{I don't have so many.}
{422}{044}{我没有那么多。 -- I don't have so many.}

### {430}{}{[Sam takes batteries and stashes them] You are a rich person. This deserves respect. Considering local poverty, it is an achievement. Most people spend everything on alcohol and narcotics. They are not capable of saving even small sums.}
{430}{}{[山姆把电池藏起来]你是个有钱人。这值得尊重。考虑到当地的贫困，这是一项成就。大多数人把所有的钱都花在了酒精和毒品上。他们连一小笔钱都省不下。 -- [Sam takes batteries and stashes them] You are a rich person. This deserves respect. Considering local poverty, it is an achievement. Most people spend everything on alcohol and narcotics. They are not capable of saving even small sums.}
### {431}{046}{So, what's about that secret?}
{431}{046}{那么，这个秘密是什么呢？ -- So, what's about that secret?}

### {440}{}{[Sam gives you despising look] I knew it. You are just like everyone else. Living in the moment, not thinking about the future. }
{440}{}{[山姆轻蔑地看了你一眼]我就知道。你和其他人一样。活在当下，不去想未来。 -- [Sam gives you despising look] I knew it. You are just like everyone else. Living in the moment, not thinking about the future. }
### {441}{045}{I will bring you the amount! Just give me more time. }
{441}{045}{我会把金额带给你！给我更多的时间。 -- I will bring you the amount! Just give me more time. }

### {450}{}{Well, you know where to find me. If you are capable of saving the necessary amount for me, I'll tell you a secret. Although I really doubt you could do it.}
{450}{}{好吧，你知道在哪里找我。如果你能为我存下必要的钱，我会告诉你一个秘密。尽管我真的怀疑你能做到。 -- Well, you know where to find me. If you are capable of saving the necessary amount for me, I'll tell you a secret. Although I really doubt you could do it.}
### {451}{999}{Okay, I'll go look for batteries.}
{451}{999}{好的，我去找电池。 -- Okay, I'll go look for batteries.}

### {460}{}{Okay, I'll tell you. The thing is - Daniel is not Mark's son! Lucy had an affair with Dan before Mark, the son even named after his father. If Mark learns about it, he wouldn't put Daniel in Mayor's position. And I would become NWO's Leader again!!}
{460}{}{好吧，我来告诉你。问题是——但以理不是马克的儿子！在马克之前，露西和丹有过一段婚外情，这个儿子甚至以他父亲的名字命名。如果马克知道了，他不会让丹尼尔担任市长的职位。我将再次成为NWO的领导者！！ -- Okay, I'll tell you. The thing is - Daniel is not Mark's son! Lucy had an affair with Dan before Mark, the son even named after his father. If Mark learns about it, he wouldn't put Daniel in Mayor's position. And I would become NWO's Leader again!!}
### {461}{010}{Oh wow, that changes things. Thanks for trusting me, Sam. I'd like to ask about something else.}
{461}{010}{哦，哇，这改变了一切。谢谢你信任我，萨姆。我想问一些其他的事情。 -- Oh wow, that changes things. Thanks for trusting me, Sam. I'd like to ask about something else.}

### {470}{}{[Sam freezez] Damn... I knew sooner or later someone would find out... }
{470}{}{该死的。。。我知道迟早会有人发现。。。 -- [Sam freezez] Damn... I knew sooner or later someone would find out... }
### {471}{048}{For now it's only me. And I won't tell anyone - but only if you'll make peace with Lucy and do what she tells you. It will be better for your family.}
{471}{048}{目前只有我一个人。我不会告诉任何人——但前提是你要和露西和好，照她说的做。这对你的家人会更好。 -- For now it's only me. And I won't tell anyone - but only if you'll make peace with Lucy and do what she tells you. It will be better for your family.}

### {480}{}{[Sam gets angry] I won't go to her, I won't apologize! She sleeps with everyone! }
{480}{}{[山姆生气了]我不会去找她，我不会道歉！她和所有人都睡在一起！ -- [Sam gets angry] I won't go to her, I won't apologize! She sleeps with everyone! }
### {481}{049}{You will. You have no choice, if you want to keep stealing the batteries for your medications.}
{481}{049}{你会的。如果你想继续偷你的药物电池，你别无选择。 -- You will. You have no choice, if you want to keep stealing the batteries for your medications.}

### {490}{}{[Sam lowers his shoulders, saddened] Okay... I'll talk to her. But no one should know about stealing.}
{490}{}{[山姆悲伤地低着肩膀]好吧。。。我会和她谈谈的。但是没有人应该知道偷窃。 -- [Sam lowers his shoulders, saddened] Okay... I'll talk to her. But no one should know about stealing.}
### {491}{010}{That's better. It will be our little secret. Now, to other questions.}
{491}{010}{这样更好。这将是我们的小秘密。现在，谈谈其他问题。 -- That's better. It will be our little secret. Now, to other questions.}

### {500}{}{[Sam carefully listens for your recommendations about taking care of the skin to prevent decaying] Impressive. You really are a specialist. I respect that.}
{500}{}{[山姆认真听取你关于护理皮肤以防止腐烂的建议]令人印象深刻。你真是个专家。我尊重这一点。 -- [Sam carefully listens for your recommendations about taking care of the skin to prevent decaying] Impressive. You really are a specialist. I respect that.}
### {501}{036}{Told you! So, will you tell me a secret now?}
{501}{036}{告诉你了！那么，你现在能告诉我一个秘密吗？ -- Told you! So, will you tell me a secret now?}

### {510}{}{Did you find out the reason behind the quality of water from Livos?}
{510}{}{你找到利沃斯的水质背后的原因了吗？ -- Did you find out the reason behind the quality of water from Livos?}
### {511}{010}{No, I'm still working on it... I wanted to ask something else.}
{511}{010}{不，我还在做……我想问其他问题。 -- No, I'm still working on it... I wanted to ask something else.}
### {512}{052}{Yes, I know the reason.}
{512}{052}{是的，我知道原因。 -- Yes, I know the reason.}

### {520}{}{And? What is it?}
{520}{}{和它是什么？ -- And? What is it?}
### {521}{053}{Due to the large quantities of exported water and increased usage of their water filter, they resorted to another option of water processing - charcoal filters. That's where the taste comes from.}
{521}{053}{由于大量的出口水和水过滤器的使用量增加，他们采用了另一种水处理选择——木炭过滤器。这就是味道的来源。 -- Due to the large quantities of exported water and increased usage of their water filter, they resorted to another option of water processing - charcoal filters. That's where the taste comes from.}

### {530}{}{I see. So, the water is alright, no need to worry. We used the same kind of filtering before until our filters got depleted. Here. Thanks for solving this. [Sam gives you a bag of batteries]}
{530}{}{我明白了。所以，水是好的，不需要担心。我们以前使用过同样的过滤方法，直到我们的过滤器用完为止。在这里谢谢你解决了这个问题。[山姆给你一袋电池] -- I see. So, the water is alright, no need to worry. We used the same kind of filtering before until our filters got depleted. Here. Thanks for solving this. [Sam gives you a bag of batteries]}
### {531}{999}{Thanks, it will come in handy.}
{531}{999}{谢谢，它会派上用场的。 -- Thanks, it will come in handy.}
### {532}{999}{Thanks, but no need. I'm glad to help.}
{532}{999}{谢谢，但没必要。我很乐意帮忙。 -- Thanks, but no need. I'm glad to help.}
### {533}{999}{Thanks, but to take care of the town's prosperity is my duty as a Mayor. Put the money into other needs.}
{533}{999}{谢谢，但作为一名市长，我有责任照顾这个城镇的繁荣。把钱用于其他需求。 -- Thanks, but to take care of the town's prosperity is my duty as a Mayor. Put the money into other needs.}

### {540}{}{My main mission is to assist the current Mayor to run NWO. Also, I'm supervising the water shipments from Livos. }
{540}{}{我的主要任务是协助现任市长管理NWO。此外，我正在监督从利沃斯运来的水。 -- My main mission is to assist the current Mayor to run NWO. Also, I'm supervising the water shipments from Livos. }
### {541}{055}{Do you need something for me to do?}
{541}{055}{你需要我做点什么吗？ -- Do you need something for me to do?}
### {542}{010}{I see, Another question then.}
{542}{010}{我明白了，那又是一个问题。 -- I see, Another question then.}

### {550}{}{I guess I do have something for you. Livos regularly supplies us with water of great quality, there were never any problems with it. But the last batch worries me. }
{550}{}{我想我确实有东西给你。Livos定期为我们提供优质的水，从来没有任何问题。但最后一批让我担心。 -- I guess I do have something for you. Livos regularly supplies us with water of great quality, there were never any problems with it. But the last batch worries me. }
### {551}{056}{Is there something wrong?}
{551}{056}{有什么问题吗？ -- Is there something wrong?}

### {560}{}{Water has some taste, which wasn't there before. So, I need to find out the reason behind it.}
{560}{}{水有一些以前没有的味道。所以，我需要找出背后的原因。 -- Water has some taste, which wasn't there before. So, I need to find out the reason behind it.}
### {561}{010}{I'm not interested in such a job for now. I have other questions.}
{561}{010}{我现在对这样的工作不感兴趣。我还有其他问题。 -- I'm not interested in such a job for now. I have other questions.}
### {562}{057}{Okay, I'll look into it.}
{562}{057}{好的，我会调查的。 -- Okay, I'll look into it.}

### {570}{}{Good. Go to Livos, find out the reason. Tell me when you do. I can show you this place on your map. Also, I'll show you the Tin Industries factory's location. A little bonus.}
{570}{}{好的去找利沃斯，找出原因。什么时候告诉我。我可以在你的地图上给你看这个地方。此外，我将带您参观锡工业工厂的位置。一点奖金。 -- Good. Go to Livos, find out the reason. Tell me when you do. I can show you this place on your map. Also, I'll show you the Tin Industries factory's location. A little bonus.}
### {571}{999}{Thanks. Mark it on the map, please.}
{571}{999}{谢谢请把它标记在地图上。 -- Thanks. Mark it on the map, please.}
### {572}{999}{I know where to go. I'll come to Livos and find out everything I can.}
{572}{999}{我知道该去哪里。我会来利沃斯，尽我所能找出一切。 -- I know where to go. I'll come to Livos and find out everything I can.}

### {580}{}{I suppose Lucy will do everything she can to put her son in Leader's position. This will bring us nothing good. As for me, it's I who should run this place, until he comes to a right mind.}
{580}{}{我想露西会尽她所能让她的儿子担任首领的职位。这不会给我们带来什么好处。至于我，应该由我来管理这个地方，直到他恢复理智。 -- I suppose Lucy will do everything she can to put her son in Leader's position. This will bring us nothing good. As for me, it's I who should run this place, until he comes to a right mind.}
### {581}{010}{I see... Another question then.}
{581}{010}{我明白了。。。那又是一个问题。 -- I see... Another question then.}
### {582}{999}{Understood. Thanks for your honesty.}
{582}{999}{明白了。谢谢你的诚实。 -- Understood. Thanks for your honesty.}

### {590}{}{Quite good. I hope you are not going to make a lot of changes here. I'd like to remind you that I am your advisor.}
{590}{}{不错。我希望你不会在这里做出太多改变。我想提醒你，我是你的顾问。 -- Quite good. I hope you are not going to make a lot of changes here. I'd like to remind you that I am your advisor.}
### {591}{}{We have a lot of things to do. Big plans! }
{591}{}{我们有很多事情要做。大计划！ -- We have a lot of things to do. Big plans! }
### {592}{}{I am saddened. I hope this little jerk will become smart faster than I think. }
{592}{}{我很难过。我希望这个小混蛋能比我想象的更快地变得聪明。 -- I am saddened. I hope this little jerk will become smart faster than I think. }
### {593}{060}{About that job...}
{593}{060}{关于那份工作。。。 -- About that job...}
### {594}{073}{Do you need any help?}
{594}{073}{你需要帮助吗？ -- Do you need any help?}
### {595}{074}{Come on, don't be so sad!}
{595}{074}{来吧，别那么伤心！ -- Come on, don't be so sad!}
### {596}{999}{I need to run. Lots of work!}
{596}{999}{我需要跑步。工作量很大！ -- I need to run. Lots of work!}

### {600}{}{Yes?}
{600}{}{对 -- Yes?}
### {601}{061}{I don't need an advisor anymore. You are free to go. }
{601}{061}{我不再需要顾问了。你可以自由走了。 -- I don't need an advisor anymore. You are free to go. }
### {602}{072}{I'd like you to run the town full-time, while I'm busy with other matters.}
{602}{072}{我想让你全职管理这个小镇，而我正忙于其他事情。 -- I'd like you to run the town full-time, while I'm busy with other matters.}
### {603}{066}{You know, I don't like ghouls much...}
{603}{066}{你知道，我不太喜欢食尸鬼。。。 -- You know, I don't like ghouls much...}

### {610}{}{[Sam hangs his head. He stays silently, gazing at his holey shoes.]}
{610}{}{[山姆垂下头。他静静地呆着，凝视着那双破洞的鞋子。 -- Sam hangs his head. He stays silently, gazing at his holey shoes.]}
### {611}{062}{Come on, I was just joking.}
{611}{062}{拜托，我只是在开玩笑。 -- Come on, I was just joking.}
### {612}{063}{You can live here. But you should find another job. }
{612}{063}{你可以住在这里。但是你应该找另一份工作。 -- You can live here. But you should find another job. }
### {613}{063}{Get out of my sight.}
{613}{063}{离开我的视线。 -- Get out of my sight.}
### {614}{065}{Get out. Better if I won't see you around this town in twenty-four hours.}
{614}{065}{滚出去。如果我二十四小时内不在城里见你，那就更好了。 -- Get out. Better if I won't see you around this town in twenty-four hours.}

### {620}{}{[He eyes you with a very discouraged look.]}
{620}{}{[他用一种非常沮丧的眼神看着你。 -- He eyes you with a very discouraged look.]}
### {621}{999}{Relax. I'll try not to make jokes like this anymore. Come to your senses, I'll run by later.}
{621}{999}{放松我尽量不再开这样的玩笑。你要清醒过来，我一会儿就过去。 -- Relax. I'll try not to make jokes like this anymore. Come to your senses, I'll run by later.}
### {622}{999}{This kind of stress keeps you in shape. Come to your senses, I'll run by later.}
{622}{999}{这种压力使你保持身材。你要清醒过来，我一会儿就过去。 -- This kind of stress keeps you in shape. Come to your senses, I'll run by later.}

### {630}{}{But...}
{630}{}{但是 -- But...}
### {631}{999}{That's my order. Now get lost.}
{631}{999}{这是我的命令。现在迷路吧。 -- That's my order. Now get lost.}
### {632}{064}{Keep talking - and I send you to beg for batteries in other towns.}
{632}{064}{继续说——我派你去其他城镇乞求电池。 -- Keep talking - and I send you to beg for batteries in other towns.}

### {640}{}{[Sam steps back. He is smudged, scraped off, chewed, and spat away to the roadside of life. He hunches and walks out somewhere.]}
{640}{}{[萨姆退了一步。他被弄脏、刮去、咀嚼，然后被吐到生活的路边。他弓着腰走出去。 -- Sam steps back. He is smudged, scraped off, chewed, and spat away to the roadside of life. He hunches and walks out somewhere.]}
### {641}{999}{[end of dialogue]}
{641}{999}{[对话结束 -- end of dialogue]}

### {650}{}{[He becomes as white as it is possible for a corpse. It seems he still didn't realize what he just heard. But his face already expresses devastation and depression] Why?}
{650}{}{[他变得像尸体一样苍白。他似乎仍然没有意识到他刚刚听到的话。但他的脸上已经表达了毁灭和沮丧]为什么？ -- [He becomes as white as it is possible for a corpse. It seems he still didn't realize what he just heard. But his face already expresses devastation and depression] Why?}
### {651}{999}{Just get out of here. I want you out of town in twenty-four hours. Hear me?}
{651}{999}{离开这里。我要你二十四小时后出城。听到了吗？ -- Just get out of here. I want you out of town in twenty-four hours. Hear me?}
### {652}{999}{Just get out of here. Before you go, you can take your monthly payment from the treasury. Tomorrow you'd better not be here. }
{652}{999}{离开这里。在你离开之前，你可以从国库中提取你每月的付款。明天你最好不要在这里。 -- Just get out of here. Before you go, you can take your monthly payment from the treasury. Tomorrow you'd better not be here. }

### {660}{}{Is it a problem?}
{660}{}{这是个问题吗？ -- Is it a problem?}
### {661}{067}{Yes.}
{661}{067}{对 -- Yes.}
### {662}{069}{I don't know yet. We'll see.}
{662}{069}{我还不知道。我们拭目以待。 -- I don't know yet. We'll see.}

### {670}{}{So, what are we going to do with it?}
{670}{}{那么，我们该怎么办呢？ -- So, what are we going to do with it?}
### {671}{068}{Nothing for now. I just want you to know that I despise you.}
{671}{068}{暂时没有。我只是想让你知道我鄙视你。 -- Nothing for now. I just want you to know that I despise you.}
### {672}{063}{For starters, let's change your occupation. I think you will be just fine doing the job of a conveyor worker.}
{672}{063}{首先，让我们改变你的职业。我认为你做一个输送机工人会很好的。 -- For starters, let's change your occupation. I think you will be just fine doing the job of a conveyor worker.}

### {680}{}{Is that it? }
{680}{}{就是这样吗？ -- Is that it? }
### {681}{999}{Yes. You can go back to your petty rat duties. }
{681}{999}{对你可以回到你琐碎的老鼠职责上来。 -- Yes. You can go back to your petty rat duties. }

### {690}{}{If that's all, can you don't distract me anymore? I'm trying to take care of the town here, solving problems. Important stuff.}
{690}{}{如果仅此而已，你能不能别再分散我的注意力？我正在努力照顾这里的小镇，解决问题。重要的东西。 -- If that's all, can you don't distract me anymore? I'm trying to take care of the town here, solving problems. Important stuff.}
### {691}{071}{Good for you. Pat yourself on the back.}
{691}{071}{这对你很好。表扬自己 -- Good for you. Pat yourself on the back.}
### {692}{070}{I see you don't show enough respect to your management...}
{692}{070}{我看你对管理层不够尊重。。。 -- I see you don't show enough respect to your management...}
### {693}{999}{Yes, I think you can deal with all this shit while I take a rest.}
{693}{999}{是的，我想你可以在我休息的时候处理这些垃圾。 -- Yes, I think you can deal with all this shit while I take a rest.}

### {700}{}{It is mutual.}
{700}{}{这是相互的。 -- It is mutual.}
### {701}{063}{Okay, if you put it like this... I think it's time to change your occupation...}
{701}{063}{好吧，如果你这样说。。。我认为是时候改变你的职业了。。。 -- Okay, if you put it like this... I think it's time to change your occupation...}

### {710}{}{What?}
{710}{}{什么 -- What?}
### {711}{063}{I said I have a prize for you. A new job. }
{711}{063}{我说我有个奖品给你。一份新工作。 -- I said I have a prize for you. A new job. }
### {712}{999}{Nothing. Don't get too comfortable. And go, deal with all this shit already. The town has a fuckload of problems, they need you to deal with them. Do your job while I didn't find someone to replace you.}
{712}{999}{没有什么不要太舒服。去吧，处理好所有这些垃圾。镇上有很多问题，他们需要你来处理。趁我找不到人接替你的时候做好你的工作。 -- Nothing. Don't get too comfortable. And go, deal with all this shit already. The town has a fuckload of problems, they need you to deal with them. Do your job while I didn't find someone to replace you.}

### {720}{}{Of course, I'll do my best. For now, I'm trying to smooch things. People ask questions, they are worried. After I deal with that - and it will take some time - we could think about expanding the town, building additional bays for the factory, and organizing new caravan routes. I'll let you know.}
{720}{}{当然，我会尽力的。现在，我正试着亲吻一些东西。人们问问题，他们很担心。在我处理完这件事之后——这需要一段时间——我们可以考虑扩建城镇，为工厂建造更多的海湾，并组织新的商队路线。我会告诉你的。 -- Of course, I'll do my best. For now, I'm trying to smooch things. People ask questions, they are worried. After I deal with that - and it will take some time - we could think about expanding the town, building additional bays for the factory, and organizing new caravan routes. I'll let you know.}
### {721}{999}{Great. keep me posted.}
{721}{999}{太棒了随时通知我。 -- Great. keep me posted.}

### {730}{}{Oh, no, thank you. I think I'm the one who should do the work. But thank you for the proposition, I'll keep that in mind. And now you'll have to exuse me, I have a lot of things to take care of.}
{730}{}{哦，不，谢谢。我认为我应该做这项工作。但谢谢你的提议，我会记住的。现在你必须让我兴奋，我有很多事情要处理。 -- Oh, no, thank you. I think I'm the one who should do the work. But thank you for the proposition, I'll keep that in mind. And now you'll have to exuse me, I have a lot of things to take care of.}
### {731}{999}{Yeah, sure. See you around.}
{731}{999}{是的，当然。回头见。 -- Yeah, sure. See you around.}

### {740}{}{Is that humor? [he rolls his eyes] Okay, you have to excuse me, but I can't talk right now. I need to make preparations for repairings of "Master's palace". }
{740}{}{这是幽默吗？[他翻白眼]好吧，对不起，但我现在不能说话。我需要为修复“大师宫”做准备。 -- Is that humor? [he rolls his eyes] Okay, you have to excuse me, but I can't talk right now. I need to make preparations for repairings of "Master's palace". }
### {741}{999}{Sure, good luck.}
{741}{999}{当然，祝你好运。 -- Sure, good luck.}

### {750}{}{You have a thought stuck in your head that you should have taken the money. His gratitude has no physical value, after all...}
{750}{}{你脑子里有个想法，认为你应该把钱拿走。毕竟，他的感激之情没有任何物质价值。。。 -- You have a thought stuck in your head that you should have taken the money. His gratitude has no physical value, after all...}
### {751}{}{Huh?.. [looks through you]}
{751}{}{嗯？。。[看透你] -- Huh?.. [looks through you]}
### {752}{}{Huh?.. Yeah, I'm just working...}
{752}{}{嗯？。。是的，我只是在工作。。。 -- Huh?.. Yeah, I'm just working...}
### {753}{}{Yeah, yeah, sure... As you say...}
{753}{}{是的，是的，当然。。。正如你所说。。。 -- Yeah, yeah, sure... As you say...}
