##############################
#???????: ?????? ??????
#???: '????
#??????? ????????: ???? ??????? - ???????????? ????????? (??? ?????? ?????)
#???? ????????: 02.05.2014
##############################
#??? ???? "????? 2207"
#????? "Rainman" ????????
##############################
#
#???????? ????????
#
# ?? ??????????
### {1}{}{You see an angry ghoul.}
{1}{}{你看到一个愤怒的食尸鬼。 -- You see an angry ghoul.}
### {2}{}{He gives you a heavy look from under his big brows.}
{2}{}{他从大眉毛下面重重地看了你一眼。 -- He gives you a heavy look from under his big brows.}
#
# ????? ??????????
### {3}{}{You see Hugo.}
{3}{}{你看到雨果了。 -- You see Hugo.}
### {4}{}{Every movement he makes is filled with determination and resolve.}
{4}{}{他的每一个动作都充满了决心和决心。 -- Every movement he makes is filled with determination and resolve.}
#
#????? ?????????? ??????
#
#Node001
### {10}{}{A newbie! Another runaway from Tartarus, am I right? Hey, newbie, how do you like it outside?}
{10}{}{新手！又是一个逃离塔尔塔罗斯的人，对吗？嘿，新手，你觉得外面怎么样？ -- A newbie! Another runaway from Tartarus, am I right? Hey, newbie, how do you like it outside?}
### {11}{999}{Me here bad. Go there.}
{11}{999}{我在这里很糟糕。去那里。 -- Me here bad. Go there.}
### {12}{002}{I think it's more dangerous. The food is more scarce. Cold at nights.}
{12}{002}{我认为这更危险。食物更加稀少。晚上很冷。 -- I think it's more dangerous. The food is more scarce. Cold at nights.}
### {13}{999}{I, uh- wrong door. See you.}
{13}{999}{I、 呃，门不对。再见 -- I, uh- wrong door. See you.}

#Node002
### {20}{}{That's right, damn it! You, dummies, don't know what you are running from! Tartarus - good place, Radius - bad place, no options. That's why we need to get into Tartarus, right? Right!}
{20}{}{没错，该死！你们这些笨蛋，不知道自己在逃避什么！塔尔塔罗斯-好地方，半径-坏地方，没有选择。这就是为什么我们需要进入塔尔塔罗斯，对吧？正确的 -- That's right, damn it! You, dummies, don't know what you are running from! Tartarus - good place, Radius - bad place, no options. That's why we need to get into Tartarus, right? Right!}
### {21}{003}{Uh, I guess. But how?}
{21}{003}{嗯，我想。但是怎么做呢？ -- Uh, I guess. But how?}

#Node003
### {30}{}{That's where the interesting part starts. [he scoffs with a smile full of rotten teeth] I'm Hugo and I represent the side of power around here. What's your name, young man?}
{30}{}{这就是有趣的部分的开始。[他笑得满嘴烂牙]我是雨果，我代表着这里权力的一面。年轻人，你叫什么名字？ -- That's where the interesting part starts. [he scoffs with a smile full of rotten teeth] I'm Hugo and I represent the side of power around here. What's your name, young man?}
### {31}{004}{. Are there any other sides?}
{31}{004}{.还有其他方面吗？ -- . Are there any other sides?}
### {32}{005}{ is my name, and I'm really into the side of power.}
{32}{005}{是我的名字，我真的很喜欢权力。 --  is my name, and I'm really into the side of power.}

#Node004
### {40}{}{[he wrinkles] There are, sure... There's this ancient wreck, Bono. He is, like, trying to deal with our problem the peaceful way, but by now he was able to do jack about it.}
{40}{}{[他皱着眉头]当然。。。这是一艘古老的沉船，波诺。他试图以和平的方式处理我们的问题，但现在他已经能够解决了。 -- [he wrinkles] There are, sure... There's this ancient wreck, Bono. He is, like, trying to deal with our problem the peaceful way, but by now he was able to do jack about it.}
### {41}{010}{Can you tell me more?}
{41}{010}{你能告诉我更多吗？ -- Can you tell me more?}
### {42}{999}{I see. I will definitely come back later for details.}
{42}{999}{我明白了。我稍后一定会回来了解详情。 -- I see. I will definitely come back later for details.}

#Node005
### {50}{}{In this case - welcome, }
{50}{}{在这种情况下——欢迎， -- In this case - welcome, }
### {51}{}{! I would hug you, but I'm not really into hugging [laughs] We are destined to do great things together, aren't we?}
{51}{}{！我会拥抱你，但我真的不喜欢拥抱[笑]我们注定要一起做大事，不是吗？ -- ! I would hug you, but I'm not really into hugging [laughs] We are destined to do great things together, aren't we?}
### {52}{010}{Can you tell me more?}
{52}{010}{你能告诉我更多吗？ -- Can you tell me more?}
### {53}{999}{I see. I will definitely come back later for details.}
{53}{999}{我明白了。我稍后一定会回来了解详情。 -- I see. I will definitely come back later for details.}

#Node010
### {100}{}{Spill it out. I have things to take care of.}
{100}{}{把它吐出来。我有事情要处理。 -- Spill it out. I have things to take care of.}
### {101}{}{Come on, make it quick.}
{101}{}{来吧，快一点。 -- Come on, make it quick.}
### {102}{011}{What "great things" are you talking about all the time?}
{102}{011}{你一直在谈论什么“伟大的事情”？ -- What "great things" are you talking about all the time?}
### {103}{020}{How can I help you?}
{103}{020}{我能帮你什么？ -- How can I help you?}
### {104}{030}{You asked to help you...}
{104}{030}{你请求帮助你。。。 -- You asked to help you...}
### {105}{040}{Who can I trust around here?}
{105}{040}{在这里我可以信任谁？ -- Who can I trust around here?}
### {106}{999}{You know, I'll better go.}
{106}{999}{你知道，我最好走了。 -- You know, I'll better go.}

#Node011
### {110}{}{I'm talking about a better life, son. Life in warmth and safety, where you won't have to eat dead rats to survive and grind your teeth from cold at night. I'm talking about life in Tartarus, not as slaves, but as free people!}
{110}{}{我说的是更好的生活，儿子。在温暖和安全的生活中，你不必吃死老鼠来生存，也不必在寒冷的夜晚磨牙。我说的是塔尔塔罗斯的生活，不是作为奴隶，而是作为自由的人！ -- I'm talking about a better life, son. Life in warmth and safety, where you won't have to eat dead rats to survive and grind your teeth from cold at night. I'm talking about life in Tartarus, not as slaves, but as free people!}
### {111}{013}{You mean... You plan to TAKE OVER the Tartarus?}
{111}{013}{你的意思是。。。你打算接管鞑靼人？ -- You mean... You plan to TAKE OVER the Tartarus?}
### {112}{012}{I don't quite get where this is going.}
{112}{012}{我不太明白这是怎么回事。 -- I don't quite get where this is going.}
### {113}{999}{Sounds dubious... I'll better go.}
{113}{999}{听起来可疑。。。我还是走吧。 -- Sounds dubious... I'll better go.}

#Node012
### {120}{}{Think for yourself - Tartarus is guarded only by a couple of armed guards. While the others would realize what happened, we'd already brick up other entrances! No one dares to enter us, we'll take care of this for sure!}
{120}{}{你自己想想——塔尔塔罗斯只有几个武装警卫。当其他人意识到发生了什么时，我们已经用砖堵住了其他入口！没有人敢进入我们，我们一定会处理好的！ -- Think for yourself - Tartarus is guarded only by a couple of armed guards. While the others would realize what happened, we'd already brick up other entrances! No one dares to enter us, we'll take care of this for sure!}
### {121}{010}{I don't know, sounds pretty dangerous... I'll think about it. Can I ask another question?}
{121}{010}{我不知道，听起来很危险。。。我会考虑的。我能再问一个问题吗？ -- I don't know, sounds pretty dangerous... I'll think about it. Can I ask another question?}
### {122}{999}{Wow. I need to think about it. [leave]}
{122}{999}{哇！我需要考虑一下 -- Wow. I need to think about it. [leave]}

#Node013
### {130}{}{"Take over" sounds harsh. I prefer to use the phrase "take away". We will take away what is more needed for us. Let these militarists idiots in armored suits live in their tower, we claim only the Tartarus.}
{130}{}{“接管”听起来很刺耳。我更喜欢用“带走”这个短语。我们将夺走我们更需要的东西。让这些穿着盔甲的军国主义白痴住在他们的塔里，我们只要求塔尔塔鲁人。 -- "Take over" sounds harsh. I prefer to use the phrase "take away". We will take away what is more needed for us. Let these militarists idiots in armored suits live in their tower, we claim only the Tartarus.}
### {131}{010}{I don't know, sounds pretty dangerous... I'll think about it. Can I ask another question?}
{131}{010}{我不知道，听起来很危险。。。我会考虑的。我能再问一个问题吗？ -- I don't know, sounds pretty dangerous... I'll think about it. Can I ask another question?}
### {132}{999}{Wow. I need to think about it. [leave]}
{132}{999}{哇！我需要考虑一下 -- Wow. I need to think about it. [leave]}

#Node020
### {200}{}{Help? YOU!? You can get from our way or protect us from bullets with your body! Well, okay, okay, we actually could use your help. We need some medical supplies for our soldiers, so they would feel more comfortable while taking away our beloved place.}
{200}{}{帮助你！？你可以避开我们，也可以用你的身体保护我们免受子弹的伤害！好吧，好吧，我们真的需要你的帮助。我们需要一些医疗用品给我们的士兵，这样他们在夺走我们心爱的地方时会感觉更舒服。 -- Help? YOU!? You can get from our way or protect us from bullets with your body! Well, okay, okay, we actually could use your help. We need some medical supplies for our soldiers, so they would feel more comfortable while taking away our beloved place.}
### {201}{021}{Which medical supplies?}
{201}{021}{哪些医疗用品？ -- Which medical supplies?}
### {202}{999}{Nah, I thought I would be fighting. Will handle it myself then.}
{202}{999}{不，我以为我会打架。那我自己来处理。 -- Nah, I thought I would be fighting. Will handle it myself then.}

#Node021
### {210}{}{5 packs of Heal-Up and 1 Combatid, personally for me. I'm going to have real fun, so I don't want to take risks for nothing. Combatid will do everything for me. So, will you deliver?}
{210}{}{5包治愈和1个Combatid，对我个人来说。我会玩得很开心，所以我不想白白冒险。Combatid会为我做任何事。那么，你会交付吗？ -- 5 packs of Heal-Up and 1 Combatid, personally for me. I'm going to have real fun, so I don't want to take risks for nothing. Combatid will do everything for me. So, will you deliver?}
### {211}{QA}{I don't know what it is, but I'm going to get it. I'll return to you when I do.}
{211}{QA}{我不知道它是什么，但我会得到它的。我会回来找你的。 -- I don't know what it is, but I'm going to get it. I'll return to you when I do.}
### {212}{999}{Heal-Up, Combatid... I don't even know such words, not talking about where to get something like this. No, it's too difficult. Handle it yourselves.}
{212}{999}{治愈，Combatid。。。我甚至不知道这些词，也不知道从哪里得到这样的东西。不，太难了。自己处理。 -- Heal-Up, Combatid... I don't even know such words, not talking about where to get something like this. No, it's too difficult. Handle it yourselves.}

#Node030
### {300}{}{"Asked to help you", my ass [he spits on the ground]. It was you, who volunteered. Did you get what you needed to?}
{300}{}{“请求帮助你”，我的屁股[他吐在地上]。是你自愿的。你得到了你需要的吗？ -- "Asked to help you", my ass [he spits on the ground]. It was you, who volunteered. Did you get what you needed to?}
### {301}{999}{No, but soon I'll bring everything.}
{301}{999}{没有，但很快我会把所有东西都带来。 -- No, but soon I'll bring everything.}
### {302}{031}{Yes. Here [give Hugo injectors]}
{302}{031}{对这里[给Hugo注射器] -- Yes. Here [give Hugo injectors]}
### {303}{032}{I've been searching for so long that I forgot what exactly should I bring... And how many.}
{303}{032}{我找了太久了，忘了我到底应该带什么。。。还有多少。 -- I've been searching for so long that I forgot what exactly should I bring... And how many.}

#Node031
### {310}{}{Yeah, give it to me. Don't drop it! Oh, your crooked hands... Hey guys, a little help here!! One injection per person, take it away... Well? Are you ready to take back our happy future?! We are deploying immediately!! Somebody, tell Robin to catch up, I can't wait any longer. Let's go!!}
{310}{}{是的，给我。别扔了！哦，你弯曲的手。。。嘿，伙计们，给我一点帮助！！每人注射一次，拿走。。。好你准备好夺回我们幸福的未来了吗？！我们正在立即部署！！有人，叫罗宾跟上，我等不及了。我们走！！ -- Yeah, give it to me. Don't drop it! Oh, your crooked hands... Hey guys, a little help here!! One injection per person, take it away... Well? Are you ready to take back our happy future?! We are deploying immediately!! Somebody, tell Robin to catch up, I can't wait any longer. Let's go!!}
### {311}{999}{[observe how Hugo and his fighters go away]}
{311}{999}{[观察雨果和他的战士们是如何离去的 -- observe how Hugo and his fighters go away]}

#Node032
### {320}{}{Memory of a goldfish... I have five fighters, each needs one Heal-Up, so five total. I personally need Combatid, because I'm the most valuable here. Understood?}
{320}{}{金鱼的记忆。。。我有五个战士，每个战士需要一个治疗，所以总共五个。我个人需要Combatid，因为我在这里是最有价值的。明白了吗？ -- Memory of a goldfish... I have five fighters, each needs one Heal-Up, so five total. I personally need Combatid, because I'm the most valuable here. Understood?}
### {321}{999}{Understood. Will get back soon.}
{321}{999}{明白了。很快就会回来。 -- Understood. Will get back soon.}

#Node040
### {400}{}{Trust? I don't even know. A piece of advice, kid - trust no one. If you learn a secret - keep it to yourself, be healthy. Radius doesn't like blabbers, it chews them down and spits them out because when you gave out the information, it has no need for you anymore. Listen and be silent. You'll live long enough.}
{400}{}{相信我甚至不知道。一条建议，孩子，不要相信任何人。如果你学会了一个秘密——保密，保持健康。Radius不喜欢胡言乱语，它会把它们咬下来吐出来，因为当你发布信息时，它就不再需要你了。倾听并保持沉默。你会活得足够长的。 -- Trust? I don't even know. A piece of advice, kid - trust no one. If you learn a secret - keep it to yourself, be healthy. Radius doesn't like blabbers, it chews them down and spits them out because when you gave out the information, it has no need for you anymore. Listen and be silent. You'll live long enough.}
### {401}{}{Trust? You can trust me. I won't answer for the others. Everyone here is so... Smart-ass.}
{401}{}{相信你可以相信我。我不会替别人负责的。这里的每个人都是如此…聪明。 -- Trust? You can trust me. I won't answer for the others. Everyone here is so... Smart-ass.}
### {402}{041}{Even the kids?}
{402}{041}{甚至孩子们？ -- Even the kids?}
### {403}{010}{I see. Another question.}
{403}{010}{我明白了。另一个问题。 -- I see. Another question.}

#Node041
### {410}{}{Hah, there are no kids here! Except for that little snot, Martha's offspring. I think her name is Lily. She was recently bit by a scorpion, everyone went crazy about it. That damn girl is only slowing us down. Instead of dealing with her, everyone could get together and storm the Tartarus already.}
{410}{}{哈，这里没有孩子！除了那个小鼻涕，玛莎的后代。我想她的名字叫莉莉。她最近被一只蝎子咬了，大家都为之疯狂。那个该死的女孩只会让我们慢下来。与其对付她，每个人都可以聚在一起，袭击鞑靼人。 -- Hah, there are no kids here! Except for that little snot, Martha's offspring. I think her name is Lily. She was recently bit by a scorpion, everyone went crazy about it. That damn girl is only slowing us down. Instead of dealing with her, everyone could get together and storm the Tartarus already.}
### {411}{999}{Lily, you say? Thanks, I'll go find her.}
{411}{999}{莉莉，你说呢？谢谢，我去找她。 -- Lily, you say? Thanks, I'll go find her.}
### {412}{010}{We were the kids once. Can I ask another question?}
{412}{010}{我们曾经是孩子。我可以再问一个问题吗？ -- We were the kids once. Can I ask another question?}
