#############################################################
#????????? ???? ??? ???????? << ??????? ??????? ? ??????? ?????? >> 
#############################################################
#????????? ?????:
#?????? 1-9 - ???????? ?????????;
#?????? 10-29 - ?????????? ? ?????????;
#?????? 30-99 - ???? ?? ????, ?? ?????, ??? ??????????...
#?????, ?? ?????? ???????.
#?????? ????? ?????? 100, ?.?. 100 - ???? ???? ???????, 200 - ??????.
#??????? ????????? ???? ????? 10, ?.?. 100, 110, 120 ? ?.?. ??? ??? 
#??? ??????? 100 ???????????? Node010, ??? ??????? 240 - Node024.
#??? ??????? ?????? - ???????? ?????????, ?.?. ?? ??????? 650 ?????? ????? 651, 652, 653 ? ?.?. 
#??? ?????? ??????????? ???????????? ?????????????? ????? (????????, ??????? 360 ??????? ?? 3601 ? 3602,
#??? ?? ???????? ????????? Node, ?????? ?? ????? ? ??????? ????? - 361, 362 ? ?.?.)
#############################################################
#????? ??????????????? ??????? ?? ????????? ????????? ??????? ??????? ???????,
#??? ??? ???? ????? ????? ??????!!!
############################################################
#?????????? ??? "????? 2207", by Rainman, 06/11/2010
#############################################################
#
#???????? ????????
#
### {1}{}{You see a man.}
{1}{}{你看到一个男人。 -- You see a man.}
### {2}{}{You see a runaway Servant.}
{2}{}{你看到一个逃跑的仆人。 -- You see a runaway Servant.}
### {3}{}{You see a guy.}
{3}{}{你看到一个男人。 -- You see a guy.}
### {4}{}{You see an exile.}
{4}{}{你看到的是流亡。 -- You see an exile.}
### {5}{}{You see the Servant from Tartarus.}
{5}{}{你看到了来自塔尔塔罗斯的仆人。 -- You see the Servant from Tartarus.}
### {6}{}{He looks very tired.}
{6}{}{他看起来很累。 -- He looks very tired.}
### {7}{}{How he ended up here?}
{7}{}{他是怎么来到这里的？ -- How he ended up here?}
### {8}{}{He has a little bothered look.}
{8}{}{他看起来有点烦恼。 -- He has a little bothered look.}
### {9}{}{His look doesn't express anything except sadness and disappointment.}
{9}{}{他的表情除了悲伤和失望什么都没有。 -- His look doesn't express anything except sadness and disappointment.}
#
#????? ?????????? ??????
#
### {10}{}{No, not interested.}
{10}{}{不，不感兴趣。 -- No, not interested.}
### {11}{}{I don't really care.}
{11}{}{我真的不在乎。 -- I don't really care.}
### {12}{}{Hm... No time for that.}
{12}{}{嗯…没时间了。 -- Hm... No time for that.}
### {13}{}{I actually have to go.}
{13}{}{我真的得走了。 -- I actually have to go.}
### {14}{}{I see... What happened after?}
{14}{}{我明白了。。。之后发生了什么？ -- I see... What happened after?}
### {15}{}{Well, what happened after?}
{15}{}{那之后发生了什么？ -- Well, what happened after?}
### {16}{}{What happened after that?}
{16}{}{之后发生了什么？ -- What happened after that?}
### {17}{}{And what happened next?}
{17}{}{接下来发生了什么？ -- And what happened next?}
### {18}{}{[end]}
{18}{}{[终止 -- end]}
### {19}{}{[finish]}
{19}{}{[完成 -- finish]}
### {20}{}{Yes, I'd like to hear it.}
{20}{}{是的，我想听。 -- Yes, I'd like to hear it.}
### {21}{}{Go on, tell me.}
{21}{}{继续，告诉我。 -- Go on, tell me.}
### {22}{}{Yes, I want to compare it to my story.}
{22}{}{是的，我想把它和我的故事进行比较。 -- Yes, I want to compare it to my story.}
#
#??????
#
### {100}{}{Want to know how I got here?}
{100}{}{想知道我是怎么来的吗？ -- Want to know how I got here?}
### {101}{}{It was usual night, I was tired of running around on Herald's orders. And I already heard rumors about the outside world before, so I just started to run past guards into the Purgatory. They didn't even move! And in the Purgatory was so dark, couldn't see a thing. Only was hearing some slurping sounds around the corner. I barely made it out of there.}
{101}{}{这是一个平常的夜晚，我厌倦了按照《先驱报》的命令到处乱跑。我之前就已经听到外界的传言了，所以我就开始从守卫身边跑进炼狱。他们甚至都没动！炼狱里一片漆黑，什么也看不见。只是听到拐角处传来一些咕噜咕噜的声音。我勉强离开了那里。 -- It was usual night, I was tired of running around on Herald's orders. And I already heard rumors about the outside world before, so I just started to run past guards into the Purgatory. They didn't even move! And in the Purgatory was so dark, couldn't see a thing. Only was hearing some slurping sounds around the corner. I barely made it out of there.}
### {102}{}{What happened... I got outside, pulled myself together, and was already going to walk to the tower - but heard that ghoul calling me, telling me that it's too dangerous. So we wandered around a little and eventually came here. It was a very long time ago, if you think of it... }
{102}{}{发生了什么。。。我走到外面，振作起来，本来打算走到塔前——但听到那个食尸鬼在叫我，告诉我这太危险了。所以我们四处闲逛，最后来到了这里。那是很久以前的事了，如果你想想。。。 -- What happened... I got outside, pulled myself together, and was already going to walk to the tower - but heard that ghoul calling me, telling me that it's too dangerous. So we wandered around a little and eventually came here. It was a very long time ago, if you think of it... }
### {200}{}{Want to listen about how I ran away from Tartarus?}
{200}{}{想听听我是如何逃离塔尔塔罗斯的吗？ -- Want to listen about how I ran away from Tartarus?}
### {201}{}{I had a friend there. He once noticed that the Sons of Gods almost never talk or move at night. Then it hit me - you can't see under the masks if they sleep or not! So, me and my friend walked into the purgatory past them. Just out of curiosity. }
{201}{}{我在那里有个朋友。他曾经注意到，众神之子在晚上几乎从不说话或行动。然后我突然想到了——不管他们睡不睡，你都看不到口罩下面！于是，我和我的朋友从他们身边走进了炼狱。只是出于好奇。 -- I had a friend there. He once noticed that the Sons of Gods almost never talk or move at night. Then it hit me - you can't see under the masks if they sleep or not! So, me and my friend walked into the purgatory past them. Just out of curiosity. }
### {202}{}{Try to guess! There were these creatures, howling, so scary! So we tried to run back, but took all the wrong turns - and ended up outside. And that's where one of these local ghouls met us. We ended up coming here. Now we are deciding what to do next... [he starts to ponder]}
{202}{}{试着猜测！有这些生物，嚎叫，太可怕了！所以我们试着往回跑，但拐错了弯，最后跑到了外面。当地的一个食尸鬼就是在那里遇见我们的。我们最终来到了这里。现在我们正在决定下一步该做什么。。。[他开始思考] -- Try to guess! There were these creatures, howling, so scary! So we tried to run back, but took all the wrong turns - and ended up outside. And that's where one of these local ghouls met us. We ended up coming here. Now we are deciding what to do next... [he starts to ponder]}
### {300}{}{Want me to tell you how I ended up here?}
{300}{}{想让我告诉你我是怎么来到这里的吗？ -- Want me to tell you how I ended up here?}
### {301}{}{Did you see that big door in the Farms? Of course you did. I was pretty much fed up with living in Tartarus, so I stole four bottles of moonshine from Smitty... }
{301}{}{你看到农场的那扇大门了吗？你当然做到了。我受够了住在塔尔塔罗斯，所以我从史密蒂偷了四瓶私酒。。。 -- Did you see that big door in the Farms? Of course you did. I was pretty much fed up with living in Tartarus, so I stole four bottles of moonshine from Smitty... }
### {302}{}{Don't interrupt! So, I gave the moonshine to the guards, they made it look like they turned around, and the door opened by itself. Though there were two other Son of Gods on the other side, they just told me to get out of sight and that there's no going back for me... So there's no going back.}
{302}{}{不要打断！所以，我把月光给了警卫，他们让它看起来像是他们转过身来，门自己打开了。虽然另一边还有另外两个神之子，但他们只是告诉我离开视线，我再也回不去了……所以再也回不了了。 -- Don't interrupt! So, I gave the moonshine to the guards, they made it look like they turned around, and the door opened by itself. Though there were two other Son of Gods on the other side, they just told me to get out of sight and that there's no going back for me... So there's no going back.}
#
#????????? ?????????
# ????????????? ?????????
### {1000}{}{Hey, buddy!}
{1000}{}{嘿，伙计！ -- Hey, buddy!}
### {1001}{}{Hello! How are you?}
{1001}{}{你好你好吗 -- Hello! How are you?}
### {1002}{}{Well, hello there!}
{1002}{}{你好！ -- Well, hello there!}
### {1003}{}{Hey brother! How are you doing?}
{1003}{}{嘿，兄弟！你好吗？ -- Hey brother! How are you doing?}
### {1004}{}{I would gladly stop and chat... But let's do it some other time.}
{1004}{}{我很乐意停下来聊聊。。。但让我们改天再做吧。 -- I would gladly stop and chat... But let's do it some other time.}
### {1005}{}{So glad to see you!}
{1005}{}{很高兴见到你！ -- So glad to see you!}
### {1006}{}{So nice to see you here!}
{1006}{}{很高兴在这里见到你！ -- So nice to see you here!}
### {1007}{}{Of course, I'll help with what I can!}
{1007}{}{当然，我会尽我所能提供帮助！ -- Of course, I'll help with what I can!}
### {1008}{}{So good you're here!}
{1008}{}{你在这里真好！ -- So good you're here!}
### {1009}{}{I'm so glad that you are with us!}
{1009}{}{我很高兴你和我们在一起！ -- I'm so glad that you are with us!}
# ??????????? ?????????
### {1010}{}{Don't bother me, I'm busy.}
{1010}{}{别打扰我，我很忙。 -- Don't bother me, I'm busy.}
### {1011}{}{Can't you see I'm busy?}
{1011}{}{你看不出我很忙吗？ -- Can't you see I'm busy?}
### {1012}{}{Not now, okay?}
{1012}{}{现在不行，好吗？ -- Not now, okay?}
### {1013}{}{Maybe some other time? Good.}
{1013}{}{也许改天吧？好的 -- Maybe some other time? Good.}
### {1014}{}{I have no time to talk to you right now.}
{1014}{}{我现在没有时间和你说话。 -- I have no time to talk to you right now.}
### {1015}{}{Don't bother me, I want to rest.}
{1015}{}{别打扰我，我想休息。 -- Don't bother me, I want to rest.}
### {1016}{}{What do you want?}
{1016}{}{你想要什么？ -- What do you want?}
### {1017}{}{...This work never ends...}
{1017}{}{…这项工作永无止境。。。 -- ...This work never ends...}
### {1018}{}{You'd better helped, instead of bothering me.}
{1018}{}{你最好帮忙，而不要打扰我。 -- You'd better helped, instead of bothering me.}
### {1019}{}{No. No time!}
{1019}{}{没有时间！ -- No. No time!}
# ????????????? ?????????
### {1020}{}{Get lost, dumbass!}
{1020}{}{迷路吧，蠢蛋！ -- Get lost, dumbass!}
### {1021}{}{Get the hell out!}
{1021}{}{滚出去！ -- Get the hell out!}
### {1022}{}{Better don't take your chances, you freak!}
{1022}{}{最好不要冒险，你这个怪胎！ -- Better don't take your chances, you freak!}
### {1023}{}{Screw you!!!}
{1023}{}{去你的！！！ -- Screw you!!!}
### {1024}{}{Make like a tree and get out of here.}
{1024}{}{像棵树一样，离开这里。 -- Make like a tree and get out of here.}
### {1025}{}{You're gonna get punched in the face if you don't get lost!}
{1025}{}{如果你不迷路，你会被打在脸上的！ -- You're gonna get punched in the face if you don't get lost!}
### {1026}{}{Make yourself invisible!}
{1026}{}{让自己隐形！ -- Make yourself invisible!}
### {1027}{}{What the heck do you want from me?!}
{1027}{}{你到底想从我这里得到什么？！ -- What the heck do you want from me?!}
### {1028}{}{How dare you?!}
{1028}{}{你怎么敢？！ -- How dare you?!}
### {1029}{}{You piss me off! Go away!}
{1029}{}{你惹我生气！走开！ -- You piss me off! Go away!}
#?????? ?????????
### {1030}{}{::Zzzzz...::}
{1030}{}{::兹。。。 -- Zzzzz...::}
### {1031}{}{::Hrmhmmmhm...::}
{1031}{}{::嗯。。。 -- Hrmhmmmhm...::}
### {1032}{}{::Mmmmnmrm...::}
{1032}{}{::嗯。。。 -- Mmmmnmrm...::}
### {1033}{}{::Uuuhmrmrm...::}
{1033}{}{::嗯。。。 -- Uuuhmrmrm...::}
{1034}{}{}
{1035}{}{}
{1036}{}{}
{1037}{}{}
{1038}{}{}
{1039}{}{}
