##############################
#???????: ??????? ???????
#???: ??????
#??????? ????????: ??????????? ???????? ??????. ????? ???????.
#???? ????????: 11.09.2014
##############################
#??? ???? "????? 2207"
#????? "Rainman" ????????
##############################
#
#???????? ????????
#
# ?? ??????????
### {1}{}{You see a huge guard.}
{1}{}{你看到一个巨大的警卫。 -- You see a huge guard.}
### {2}{}{He looks nervous. Or horny. Or both.}
{2}{}{他看起来很紧张。或者是饥渴。或者两者兼而有之。 -- He looks nervous. Or horny. Or both.}
#
# ????? ??????????
### {3}{}{You see Brick.}
{3}{}{你看到布里克了。 -- You see Brick.}
### {4}{}{As big as Lavash. Smart as much.}
{4}{}{和熔岩一样大。同样聪明。 -- As big as Lavash. Smart as much.}
#
#????? ?????????? ??????
#
### {10}{}{[This guy looks like an Ursa wearing a leather jacket. When you approach, he gets more tense, trying to look even bigger] Hey! Where do you think you're going? Better fetch me some beer from the bar, will you? Tell Apothecary that it's for Brick. No one goes here. Except maybe some juicy chicks with big boobs... And no more than for five minutes! [he hoarsely laughs]}
{10}{}{[这家伙穿着皮夹克，看起来像一只熊。当你走近时，他变得更加紧张，试图看起来更大]嘿！你以为你要去哪里？你最好从酒吧给我拿些啤酒，好吗？告诉药剂师这是给布瑞克的。没有人去这里。除了一些胸部大的多汁小鸡。。。不超过五分钟！[他嘶哑地笑着 -- This guy looks like an Ursa wearing a leather jacket. When you approach, he gets more tense, trying to look even bigger] Hey! Where do you think you're going? Better fetch me some beer from the bar, will you? Tell Apothecary that it's for Brick. No one goes here. Except maybe some juicy chicks with big boobs... And no more than for five minutes! [he hoarsely laughs]}
### {11}{011}{Five minutes, that's it? Looks like they don't visit this place very often...}
{11}{011}{五分钟，就这样？看起来他们不常来这个地方。。。 -- Five minutes, that's it? Looks like they don't visit this place very often...}
### {12}{013}{Brick, right? We need to talk.}
{12}{013}{砖，对吧？我们需要谈谈。 -- Brick, right? We need to talk.}
### {13}{012}{What's it you are so furiously guarding here?}
{13}{012}{你在这里疯狂地守护着什么？ -- What's it you are so furiously guarding here?}
### {14}{999}{I see. Take care, bully.}
{14}{999}{我明白了。小心，欺负人。 -- I see. Take care, bully.}


### {1001}{}{[he straightens his shoulders and gets serious] You again? I told you - nothing to do here.}
{1001}{}{[他挺直肩膀严肃起来]你又来了？我告诉过你——这里没什么可做的。 -- [he straightens his shoulders and gets serious] You again? I told you - nothing to do here.}
### {101}{013}{I'm from Shepherd. I think you know why.}
{101}{013}{我来自谢泼德。我想你知道为什么。 -- I'm from Shepherd. I think you know why.}
### {102}{012}{And what is it so important you're guarding here?}
{102}{012}{你在这里守护什么这么重要？ -- And what is it so important you're guarding here?}
### {103}{999}{Relax. I'm just walking around.}
{103}{999}{放松我只是四处走走。 -- Relax. I'm just walking around.}
### {1002}{}{What else do you want?! No, I don't go to Shepherd's chicks. At all. Sitting here, polishing my gun's barrel.}
{1002}{}{你还想要什么？！不，我不去牧羊人的小鸡。完全坐在这里，打磨我的枪管。 -- What else do you want?! No, I don't go to Shepherd's chicks. At all. Sitting here, polishing my gun's barrel.}
### {104}{012}{Spare me the details. Better tell me, why are you hanging around here all the time? }
{104}{012}{别告诉我细节。最好告诉我，你为什么一直在这里闲逛？ -- Spare me the details. Better tell me, why are you hanging around here all the time? }
### {105}{999}{Don't worry, you'll get lucky someday. Good day to you.}
{105}{999}{别担心，总有一天你会幸运的。祝你今天愉快。 -- Don't worry, you'll get lucky someday. Good day to you.}
### {1003}{}{[he looks nervous] So, how are my chicks? I'm getting all shaky already - too long without a good fuck!}
{1003}{}{[他看起来很紧张]那么，我的小鸡们怎么样了？我已经浑身发抖了——太久没有好好操了！ -- [he looks nervous] So, how are my chicks? I'm getting all shaky already - too long without a good fuck!}
### {106}{019}{All set. What's left is for you to meet them and talk details.}
{106}{019}{一切就绪。剩下的就是与他们见面并讨论细节。 -- All set. What's left is for you to meet them and talk details.}
### {107}{999}{Wait for a little more, I'll let you know when it's ready.}
{107}{999}{再等一等，等它准备好了我会通知你的。 -- Wait for a little more, I'll let you know when it's ready.}
### {1004}{}{Chief! During my time on duty, no incidents have occurred! Let me be fucked by a Ghoul if someone gets past me! I swear on all my chicks that it won't happen!}
{1004}{}{首领在我值班期间，没有发生任何事件！如果有人超过我，就让我被食尸鬼操！我向我所有的小鸡发誓，这不会发生！ -- Chief! During my time on duty, no incidents have occurred! Let me be fucked by a Ghoul if someone gets past me! I swear on all my chicks that it won't happen!}
### {108}{013}{You're too lively, I see. I can trouble for you. Why are you bothering Shepherd?}
{108}{013}{我明白了，你太活泼了。我可以麻烦你。你为什么要打扰谢泼德？ -- You're too lively, I see. I can trouble for you. Why are you bothering Shepherd?}
### {109}{013}{I had a talk with Shepherd. Can you guess about what?}
{109}{013}{我和谢泼德谈过了。你能猜出是什么吗？ -- I had a talk with Shepherd. Can you guess about what?}
### {1010}{023}{How's it going, soldier?}
{1010}{023}{进展如何，士兵？ -- How's it going, soldier?}
### {1011}{999}{Good job. You know what to do. Okay, later.}
{1011}{999}{干得好你知道该怎么办。好的，稍后。 -- Good job. You know what to do. Okay, later.}
### {1005}{}{[he is taking a nap, leaning against the wall. Under his feet lies a whole pyramid of empty bottles. When you approach, he opens one eye] What? Get lost, don't loiter here... And tell me - does that black ass pimp still have some bitches to fuck?}
{1005}{}{[他靠在墙上打盹。脚下是一整金字塔的空瓶子。当你走近时，他睁开了一只眼睛]什么？迷路，不要在这里闲逛。。。告诉我，那个黑屁股皮条客还有婊子养的吗？ -- [he is taking a nap, leaning against the wall. Under his feet lies a whole pyramid of empty bottles. When you approach, he opens one eye] What? Get lost, don't loiter here... And tell me - does that black ass pimp still have some bitches to fuck?}
### {1012}{013}{Does or doesn't, you're not getting near them anyway. Got it?}
{1012}{013}{不管有没有，你都不会靠近他们。明白了吗？ -- Does or doesn't, you're not getting near them anyway. Got it?}
### {1013}{023}{I see you're doing pretty well.}
{1013}{023}{我看你做得很好。 -- I see you're doing pretty well.}
### {1014}{999}{I'd better go.}
{1014}{999}{我最好去。 -- I'd better go.}
### {1006}{}{Ha! The king of bitches has arrived! [he shows his missing teeth in a wide smile] I think it's great that you've dealt with this coal asshole! He didn't let me near his whorehouse.}
{1006}{}{哈婊子养的国王来了！[他露出缺失的牙齿，笑容满面]我觉得你能对付这个煤混蛋真是太好了！他不让我靠近他的妓院。 -- Ha! The king of bitches has arrived! [he shows his missing teeth in a wide smile] I think it's great that you've dealt with this coal asshole! He didn't let me near his whorehouse.}
### {1015}{013}{Then it's in your best interests to collaborate with me. You wouldn't mind telling me what you're guarding here, right? Or you'll have to pay for every Shepherd's girl you screwed with.}
{1015}{013}{那和我合作最符合你的利益。你不介意告诉我你在这里保护什么，对吧？否则你必须为你惹上的每一个牧羊女付出代价。 -- Then it's in your best interests to collaborate with me. You wouldn't mind telling me what you're guarding here, right? Or you'll have to pay for every Shepherd's girl you screwed with.}
### {1016}{999}{Of course, we are always happy to see our regular customers. I hope to see you soon.}
{1016}{999}{当然，我们总是很高兴见到我们的老客户。我希望很快见到你。 -- Of course, we are always happy to see our regular customers. I hope to see you soon.}
### {1017}{999}{Don't be so happy. I won't let anyone disturb the order in my establishment. Take care, guard.}
{1017}{999}{别那么高兴。我不会让任何人扰乱我机构的秩序。小心，警卫。 -- Don't be so happy. I won't let anyone disturb the order in my establishment. Take care, guard.}
### {1007}{}{[he is taking a nap, leaning against the wall. Under his feet lies a whole pyramid of empty bottles. When you approach, he opens one eye] What? Get lost, don't loiter here... And tell me - are there still bitches left to fuck in that brothel of yours?}
{1007}{}{[他靠在墙上打盹。脚下是一整金字塔的空瓶子。当你走近时，他睁开了一只眼睛]什么？迷路，不要在这里闲逛。。。告诉我，你的妓院里还有婊子吗？ -- [he is taking a nap, leaning against the wall. Under his feet lies a whole pyramid of empty bottles. When you approach, he opens one eye] What? Get lost, don't loiter here... And tell me - are there still bitches left to fuck in that brothel of yours?}
### {1018}{023}{I see you're doing pretty well.}
{1018}{023}{我看你做得很好。 -- I see you're doing pretty well.}
### {1019}{999}{I'd better go.}
{1019}{999}{我最好去。 -- I'd better go.}


### {110}{}{[he stares at you, not saying anything, then gets an intimidating look] What the fuck are you implying? It's five minutes just because I can't leave my post for longer! Otherwise, I would be spinning every local chick on my device for hours!}
{110}{}{[他盯着你，什么也没说，然后露出一副吓人的表情]你他妈的在暗示什么？这是五分钟，因为我不能再离开我的岗位了！否则，我会在我的设备上旋转每一个当地女孩好几个小时！ -- [he stares at you, not saying anything, then gets an intimidating look] What the fuck are you implying? It's five minutes just because I can't leave my post for longer! Otherwise, I would be spinning every local chick on my device for hours!}
### {111}{013}{Okay, your device is none of my concern. We need to talk.}
{111}{013}{好吧，我不关心你的设备。我们需要谈谈。 -- Okay, your device is none of my concern. We need to talk.}
### {112}{012}{I believe you, cut it. Tell me, what you're guarding?}
{112}{012}{我相信你，别这样。告诉我，你在保护什么？ -- I believe you, cut it. Tell me, what you're guarding?}
### {113}{999}{Sure. See you around, sex monster.}
{113}{999}{当然再见，性怪物。 -- Sure. See you around, sex monster.}


### {1201}{}{What am I guarding? I mean - the warehouse, of course! [he laughs] Actually, I can't talk about it. Get lost.}
{1201}{}{我在守护什么？我的意思是——当然是仓库！[他笑着说]事实上，我不能谈论它。迷路吧。 -- What am I guarding? I mean - the warehouse, of course! [he laughs] Actually, I can't talk about it. Get lost.}
### {121}{013}{Are you a local retarded clown? I'll make you more serious. We need to talk.}
{121}{013}{你是当地的弱智小丑吗？我会让你更认真一点。我们需要谈谈。 -- Are you a local retarded clown? I'll make you more serious. We need to talk.}
### {122}{013}{Listen here - Shepherd has something to tell you.}
{122}{013}{听着，谢泼德有话要告诉你。 -- Listen here - Shepherd has something to tell you.}
### {123}{999}{See you around, funny guy.}
{123}{999}{回头见，有趣的家伙。 -- See you around, funny guy.}
### {1202}{}{[he stumbles, then speaks] If I tell you, would you get lost? I have enough on my plate... There's one girl in the lab. She is the daughter of a smart-ass who invented the Drop. Name's Naomi. She looks important - I'm even not allowed to fuck her...}
{1202}{}{[他跌跌撞撞，然后说话]如果我告诉你，你会迷路吗？我的盘子里有足够的。。。实验室里有一个女孩，她是发明Drop的聪明人的女儿。我叫娜奥米。她看起来很重要——我甚至不允许操她。。。 -- [he stumbles, then speaks] If I tell you, would you get lost? I have enough on my plate... There's one girl in the lab. She is the daughter of a smart-ass who invented the Drop. Name's Naomi. She looks important - I'm even not allowed to fuck her...}
### {124}{999}{I see. I don't have time for it now, I need to go.}
{124}{999}{我明白了。我现在没有时间，我得走了。 -- I see. I don't have time for it now, I need to go.}


### {1301}{}{Shepherd, you say? I bet he told everyone shit about me and too afraid to show up himself. Did he send you as his slut? You're not my type, you know! [he hoarsely laughs]}
{1301}{}{牧羊人，你说？我敢打赌，他把我的事告诉了所有人，而且他自己也不敢露面。他派你当他的荡妇了吗？你不是我喜欢的类型，你知道！[他嘶哑地笑] -- Shepherd, you say? I bet he told everyone shit about me and too afraid to show up himself. Did he send you as his slut? You're not my type, you know! [he hoarsely laughs]}
### {131}{016}{What did you just say, sperm bank?! Come here! [grab him]}
{131}{016}{你刚才说什么，精子库？！过来！[抓住他] -- What did you just say, sperm bank?! Come here! [grab him]}
### {132}{014}{I said I will solve this matter - and I'm going to do it. }
{132}{014}{我说过我会解决这个问题——我会去做的。 -- I said I will solve this matter - and I'm going to do it. }
### {133}{999}{Oh you f... I'll be back later.}
{133}{999}{哦，你…我一会儿回来。 -- Oh you f... I'll be back later.}
### {1302}{}{[he scratches his head] So, our potato fella tattled on me... Well... Chief, try to understand - I'm hanging out here like a dick in the box! The job is dangerous, I'm nervous... How do I relax? }
{1302}{}{[他挠了挠头]所以，我们的土豆家伙在我身上纹身…嗯。。。酋长，试着理解——我在这里待得像盒子里的老二！这份工作很危险，我很紧张。。。我该如何放松？ -- [he scratches his head] So, our potato fella tattled on me... Well... Chief, try to understand - I'm hanging out here like a dick in the box! The job is dangerous, I'm nervous... How do I relax? }
### {134}{025}{Don't you dare to play the pity angle! You left the post, plus you didn't pay for service! Questions?}
{134}{025}{你不敢玩怜悯的把戏！你离职了，而且你没有支付服务费！问题？ -- Don't you dare to play the pity angle! You left the post, plus you didn't pay for service! Questions?}
### {135}{026}{There's an option. I can set you up with two girls. But if I'll see that you visit them on shift... I'm going to chop your dangle off!}
{135}{026}{有一个选择。我可以帮你安排两个女孩。但如果我看到你轮班去看望他们。。。我要把你的吊儿砍掉！ -- There's an option. I can set you up with two girls. But if I'll see that you visit them on shift... I'm going to chop your dangle off!}
### {1303}{}{[he spits at your feet] It's about Shepherd, huh? He can't hide behind Hog anymore. So, what're you gonna do? Suck my dick?}
{1303}{}{[他朝你的脚吐口水]是关于谢泼德的，是吗？他再也不能躲在猪后面了。那么，你打算怎么办？吸我的老二？ -- [he spits at your feet] It's about Shepherd, huh? He can't hide behind Hog anymore. So, what're you gonna do? Suck my dick?}
### {136}{021}{What did you say? You're the one who's going to suck dick!}
{136}{021}{你说什么？你就是那个要吸老二的人！ -- What did you say? You're the one who's going to suck dick!}
### {137}{014}{There's always an option, which benefits everyone. And I'm going to find it.}
{137}{014}{总有一个选择，让每个人都受益。我会找到它的。 -- There's always an option, which benefits everyone. And I'm going to find it.}
### {138}{999}{I don't have time for this. But I'll be back.}
{138}{999}{我没有时间做这个。但我会回来的。 -- I don't have time for this. But I'll be back.}


### {140}{}{And? What are you going to do, Mr. Cool Guy? Only don't hit me, haha!}
{140}{}{和你打算怎么办，酷家伙先生？只是别打我，哈哈！ -- And? What are you going to do, Mr. Cool Guy? Only don't hit me, haha!}
### {141}{015}{I'm suggesting a compromise. What if I find you a worthy replacement of Shepherd's girls?}
{141}{015}{我建议达成妥协。如果我发现你是牧羊人的女儿们的替代者呢？ -- I'm suggesting a compromise. What if I find you a worthy replacement of Shepherd's girls?}
### {142}{016}{That's exactly what I'm going to do, you sex-obsessed freak! I'm going to break your bones until you understand that you have nothing to do at Shepherd's! [grab him]}
{142}{016}{这正是我要做的，你这个性痴迷的怪胎！我要打断你的骨头，直到你明白你在牧羊人家无所事事！[抓住他] -- That's exactly what I'm going to do, you sex-obsessed freak! I'm going to break your bones until you understand that you have nothing to do at Shepherd's! [grab him]}
### {143}{017}{Let's take a look at the situation. You are just a guard, while Shepherd is Hog's favorite. Who do you think Hog would back up? I barely talked Shepherd into not telling Hog about you...}
{143}{017}{让我们来看看情况。你只是一个警卫，而牧羊人是猪的最爱。你认为霍格会支持谁？我几乎没有说服谢泼德不要告诉霍格你的事。。。 -- Let's take a look at the situation. You are just a guard, while Shepherd is Hog's favorite. Who do you think Hog would back up? I barely talked Shepherd into not telling Hog about you...}
### {144}{021}{Damn, why the hell not? Let's see if you have some muscles under this layer of fat!!}
{144}{021}{该死，为什么不呢？让我们看看你在这层脂肪下面是否有肌肉！！ -- Damn, why the hell not? Let's see if you have some muscles under this layer of fat!!}
### {145}{024}{Why have problems with Shepherd, when Hog's slave girls are left without a master? If you hurry, you can take them for yourself...}
{145}{024}{为什么牧羊人会有问题，而猪的奴隶女孩却没有主人？如果你赶时间，你可以自己拿。。。 -- Why have problems with Shepherd, when Hog's slave girls are left without a master? If you hurry, you can take them for yourself...}
### {146}{999}{You'll learn soon. I'll be back}
{146}{999}{你很快就会学会的。我会回来的 -- You'll learn soon. I'll be back}


### {150}{}{Who can you offer me? A Lavash? Every girl around here ended up in a brothel...}
{150}{}{你能给我谁？熔岩？这里的每个女孩最后都进了妓院。。。 -- Who can you offer me? A Lavash? Every girl around here ended up in a brothel...}
### {151}{018}{What about Snowflake and Squirrel?}
{151}{018}{雪花和松鼠呢？ -- What about Snowflake and Squirrel?}
### {152}{999}{I don't know yet. But I'll tell you when finding someone.}
{152}{999}{我还不知道。但我会在找到人的时候告诉你。 -- I don't know yet. But I'll tell you when finding someone.}


### {160}{}{[you grab his throat with your right hand, holding him with your left. He tries to break free, but you only tighten the grip. When he starts to wheeze and faint, you let him go, and he drops to the ground, coughing and shaking] Khack! Fucking... Damn... Why do you need to get steamy all of a sudden? I get it, I'm not stupid... Okay, you win. I won't go to the whores until I have enough money to pay for them. Still, you shouldn't have dealt with Shepherd. He's too greedy...}
{160}{}{[你用右手抓住他的喉咙，用左手抓住他。他试图挣脱，但你只是紧紧抓住他。当他开始喘息和晕倒时，你放开他，他倒在地上，咳嗽和颤抖]卡嗒！他妈的。。。该死为什么你需要突然变得暴躁？我明白了，我并不愚蠢。。。好吧，你赢了。我不会去嫖娼，除非我有足够的钱支付。尽管如此，你不应该和谢泼德打交道。他太贪婪了。。。 -- [you grab his throat with your right hand, holding him with your left. He tries to break free, but you only tighten the grip. When he starts to wheeze and faint, you let him go, and he drops to the ground, coughing and shaking] Khack! Fucking... Damn... Why do you need to get steamy all of a sudden? I get it, I'm not stupid... Okay, you win. I won't go to the whores until I have enough money to pay for them. Still, you shouldn't have dealt with Shepherd. He's too greedy...}
### {161}{999}{That's not your business, understood? I can handle him. That's it, I'm going.}
{161}{999}{那不关你的事，明白吗？我能对付他。就这样，我要走了。 -- That's not your business, understood? I can handle him. That's it, I'm going.}


### {170}{}{[he kicks an empty bottle] This chocolate piece of shit is sticking his nose everywhere... He always feels bad when someone else feels good! Well... Okay, I'll keep quiet for now. The Hog is no joke - if he won't go to me himself, he will still send Mate. And Mate can easily cut my balls off...}
{170}{}{[他踢了一个空瓶子]这块巧克力屎把他的鼻子伸得到处都是。。。当别人感觉好的时候，他总是感觉不好！好好吧，我暂时保持沉默。猪可不是闹着玩的——如果他自己不去找我，他还是会派Mate来的。Mate可以很容易地把我的蛋蛋切掉。。。 -- [he kicks an empty bottle] This chocolate piece of shit is sticking his nose everywhere... He always feels bad when someone else feels good! Well... Okay, I'll keep quiet for now. The Hog is no joke - if he won't go to me himself, he will still send Mate. And Mate can easily cut my balls off...}
### {171}{999}{You get it. I'm glad we've come to an agreement. Good day to you.}
{171}{999}{你明白了。我很高兴我们达成了协议。祝你今天愉快。 -- You get it. I'm glad we've come to an agreement. Good day to you.}


### {1801}{}{[he perplexedly blinks] Uh... You mean... To shag the Hog's bitches? Uhhh... He would fuck me up for this...}
{1801}{}{[他困惑地眨眼]呃。。。你的意思是。。。和猪的婊子们做爱？啊。。。他会因为这个把我搞砸的。。。 -- [he perplexedly blinks] Uh... You mean... To shag the Hog's bitches? Uhhh... He would fuck me up for this...}
### {181}{019}{Relax, everything is already taken care of! They both, you hear, BOTH agreed to play a pink pony with you. [wink]}
{181}{019}{放松点，一切都已经搞定了！他们俩，你知道，都同意和你一起玩一匹粉红色的小马。[眨眼] -- Relax, everything is already taken care of! They both, you hear, BOTH agreed to play a pink pony with you. [wink]}
### {182}{019}{Don't sweat, everything's going to be alright. They are dreaming about a man like you, I've heard it myself! Just don't be afraid and try your luck. You're the man!}
{182}{019}{别担心，一切都会好起来的。他们梦见了一个像你这样的男人，我自己也听说过！只是不要害怕，试试你的运气。你就是那个男人！ -- Don't sweat, everything's going to be alright. They are dreaming about a man like you, I've heard it myself! Just don't be afraid and try your luck. You're the man!}
### {183}{999}{Maybe you're right... Let's consider other options.}
{183}{999}{也许你是对的。。。让我们考虑其他选择。 -- Maybe you're right... Let's consider other options.}
### {1802}{}{[[he perplexedly blinks] Uh... You mean... To shag the Mate's bitches? Uhhh... He would fuck me up for this...}
{1802}{}{他困惑地眨了眨眼呃。。。你的意思是。。。去和伙伴的婊子们做爱？啊。。。他会因为这个把我搞砸的。。。 -- [[he perplexedly blinks] Uh... You mean... To shag the Mate's bitches? Uhhh... He would fuck me up for this...}
### {184}{019}{Relax, everything is already taken care of! They both, you hear, BOTH agreed to play a pink pony with you. [wink]}
{184}{019}{放松点，一切都已经搞定了！他们俩，你知道，都同意和你一起玩一匹粉红色的小马。[眨眼] -- Relax, everything is already taken care of! They both, you hear, BOTH agreed to play a pink pony with you. [wink]}
### {185}{019}{Don't sweat, everything's going to be alright. They are dreaming about a man like you, I've heard it myself! Just don't be afraid and try your luck. You're the man!}
{185}{019}{别担心，一切都会好起来的。他们梦见了一个像你这样的男人，我自己也听说过！只是不要害怕，试试你的运气。你就是那个男人！ -- Don't sweat, everything's going to be alright. They are dreaming about a man like you, I've heard it myself! Just don't be afraid and try your luck. You're the man!}
### {186}{999}{Maybe you're right... Let's consider other options.}
{186}{999}{也许你是对的。。。让我们考虑其他选择。 -- Maybe you're right... Let's consider other options.}


### {190}{}{I knew it! Hang on, bitches, here comes the daddy!... Uh, it's still scary... [he leaves, mumbling something]}
{190}{}{我就知道！等一下，婊子们，爸爸来了！。。。呃，还是挺吓人的。。。[他喃喃自语地离开了] -- I knew it! Hang on, bitches, here comes the daddy!... Uh, it's still scary... [he leaves, mumbling something]}
### {191}{999}{You'll show them! Uh, at least something.}
{191}{999}{你会给他们看的！呃，至少有点什么。 -- You'll show them! Uh, at least something.}

### {200}{}{[he is definitely having doubts] Well, if you would deal with it... Man! What if they'll know?... But I want to fuck! Poor me... Okay, you live only once! I agree!!}
{200}{}{[他肯定有疑问]好吧，如果你能处理好的话……伙计！如果他们知道怎么办？。。。但我想去他妈的！可怜的我…好吧，你只活一次！我同意！！ -- [he is definitely having doubts] Well, if you would deal with it... Man! What if they'll know?... But I want to fuck! Poor me... Okay, you live only once! I agree!!}
### {201}{999}{Good! Stay here and wait for the news.}
{201}{999}{好的呆在这里等消息。 -- Good! Stay here and wait for the news.}

### {210}{}{[he gets closer] If it's about bashing heads - I'm always in. I have such a great boner after, you could chop wood with it...}
{210}{}{[他越来越近了]如果是关于打击头部的话——我总是在。我有一个很好的骨架，你可以用它砍柴。。。 -- [he gets closer] If it's about bashing heads - I'm always in. I have such a great boner after, you could chop wood with it...}
### {211}{998}{You're going to be pissing with blood! Hang on...}
{211}{998}{你会被血弄尿的！坚持 -- You're going to be pissing with blood! Hang on...}
### {212}{998}{Damn... You're so slow to understand what's happening. Okay, let's warm up a little.}
{212}{998}{该死你对发生的事情了解得太慢了。好吧，让我们稍微暖和一下。 -- Damn... You're so slow to understand what's happening. Okay, let's warm up a little.}

### {220}{}{[Brick slowly stands up, spitting out his teeth] You broke my nose, asshole... Looks like the rib too... Okay, I won't go to the Shepherd's anymore. Happy now? And now, be kind, piss off, will you?...}
{220}{}{[布里克慢慢站起来，吐出牙齿]你打断了我的鼻子，混蛋。。。看起来肋骨也。。。好吧，我不会再去牧羊人了。现在快乐吗？现在，友善一点，走开，好吗？。。。 -- [Brick slowly stands up, spitting out his teeth] You broke my nose, asshole... Looks like the rib too... Okay, I won't go to the Shepherd's anymore. Happy now? And now, be kind, piss off, will you?...}
### {221}{999}{That's better. If you pick on me again, you won't get off so easily. See you around.}
{221}{999}{这样更好。如果你再挑我的毛病，你就不会那么容易脱身了。回头见。 -- That's better. If you pick on me again, you won't get off so easily. See you around.}

### {2301}{}{It's all quiet, chief! Our smart-asses are working non-stop, afraid to even twitch... And the Rainbow became calmer. Everyone knows that it's dangerous to mess with you. Don't forget me when you're going to the Jackals! }
{2301}{}{一切都很安静，首领！我们聪明的屁股不停地工作，甚至不敢抽搐。。。彩虹变得更平静了。每个人都知道惹你是危险的。去豺狼队的时候别忘了我！ -- It's all quiet, chief! Our smart-asses are working non-stop, afraid to even twitch... And the Rainbow became calmer. Everyone knows that it's dangerous to mess with you. Don't forget me when you're going to the Jackals! }
### {231}{999}{I sure won't. As for now, look after the warehouse - everything can happen...}
{231}{999}{我当然不会。至于现在，照顾好仓库——一切都有可能发生。。。 -- I sure won't. As for now, look after the warehouse - everything can happen...}
### {2302}{}{Yup. No one tries to fuck my brain now. I made a deal with Apothecary - we're trying to sell the remaining Drop all at once... So, I'm guarding it for now. And he supplies me with booze. [he gulps from the bottle] }
{2302}{}{是的。现在没人想操我的脑子了。我和药剂师做了一笔交易——我们试图一次卖掉剩下的Drop。。。所以，我现在在保护它。他还给我提供酒。[他从瓶子里大口喝] -- Yup. No one tries to fuck my brain now. I made a deal with Apothecary - we're trying to sell the remaining Drop all at once... So, I'm guarding it for now. And he supplies me with booze. [he gulps from the bottle] }
### {232}{999}{Yeah... Good luck to you both.}
{232}{999}{是 啊祝你们俩好运。 -- Yeah... Good luck to you both.}
### {2303}{}{Yup. No one tries to fuck my brain now. I made a deal with Apothecary - now we're partners, selling the Drop to junkies from all around Radius. So, I'm guarding it for now. And he supplies me with booze. [he gulps from the bottle]}
{2303}{}{是的。现在没人想操我的脑子了。我和药剂师做了一笔交易——现在我们是合作伙伴，把滴剂卖给Radius各地的瘾君子。所以，我现在在保护它。他还给我提供酒。[他从瓶子里大口喝] -- Yup. No one tries to fuck my brain now. I made a deal with Apothecary - now we're partners, selling the Drop to junkies from all around Radius. So, I'm guarding it for now. And he supplies me with booze. [he gulps from the bottle]}
### {233}{999}{Yeah... Good luck to you both.}
{233}{999}{是 啊祝你们俩好运。 -- Yeah... Good luck to you both.}

### {240}{}{[he jumps up, bottles fly all over] Really?! I didn't even know!! I thought they ran off... Squirrel is such a beauty... Thank you for this. I'll go check upon them. Tell black asshole that we're good. }
{240}{}{[他跳了起来，瓶子飞得到处都是]真的吗？！我甚至都不知道！！我以为他们跑了…松鼠真是个美人。。。谢谢你。我去看看他们。告诉黑人混蛋我们很好。 -- [he jumps up, bottles fly all over] Really?! I didn't even know!! I thought they ran off... Squirrel is such a beauty... Thank you for this. I'll go check upon them. Tell black asshole that we're good. }
### {241}{999}{Good. I definitely will.}
{241}{999}{好的我一定会的。 -- Good. I definitely will.}

### {250}{}{[he stares at you with fright] Chief, I... I... I'm sorry! It won't happen again! I get it, really!}
{250}{}{[他吓得瞪着你]警长，我…我…对不起！这种事不会再发生了！我明白了，真的！ -- [he stares at you with fright] Chief, I... I... I'm sorry! It won't happen again! I get it, really!}
### {251}{999}{I believe you. But to make sure that you really get it, you're going to clean the toilet in the barracks for the whole next week. You can start now. And I need to go. }
{251}{999}{我相信你。但为了确保你真的得到它，你将在下周打扫营房里的厕所。你现在可以开始了。我得走了。 -- I believe you. But to make sure that you really get it, you're going to clean the toilet in the barracks for the whole next week. You can start now. And I need to go. }
### {252}{999}{Hmm. I need to think about what to do with you. Talk later.}
{252}{999}{嗯。我需要考虑一下该怎么处置你。稍后再谈。 -- Hmm. I need to think about what to do with you. Talk later.}

### {260}{}{[his jaw drops, he stares at you, dazzled] That means... I can do Squirrel, right? I was always into her... Ooh... Thanks, chief! I will never leave the post anymore, you can count on it!}
{260}{}{[他瞠目结舌，目不转睛地盯着你]这意味着。。。我会做松鼠，对吧？我一直很喜欢她。。。哦。。。谢谢局长！我再也不会离开这个岗位了，你可以放心！ -- [his jaw drops, he stares at you, dazzled] That means... I can do Squirrel, right? I was always into her... Ooh... Thanks, chief! I will never leave the post anymore, you can count on it!}
### {261}{999}{Okay, okay, enough. But be warned - one more screw-up, and I'm going to chop off your sapling down to the root.}
{261}{999}{好了，好了，够了。但请注意，再搞砸一次，我就把你的树苗砍倒。 -- Okay, okay, enough. But be warned - one more screw-up, and I'm going to chop off your sapling down to the root.}
### {262}{999}{On the other hand, I need to think about it. Wait for my decision.}
{262}{999}{另一方面，我需要考虑一下。等待我的决定。 -- On the other hand, I need to think about it. Wait for my decision.}

### {270}{}{[mumbles] Stupid bitch! What have you done!? Stupid... Dead... BITCH!}
{270}{}{愚蠢的婊子！你做了什么！？愚蠢的死去的婊子！ -- [mumbles] Stupid bitch! What have you done!? Stupid... Dead... BITCH!}
### {271}{}{The bitch tried to run away, I'm telling you!!}
{271}{}{我告诉你，那婊子想逃跑！！ -- The bitch tried to run away, I'm telling you!!}
### {272}{}{Why couldn't this stupid chick just stay there?}
{272}{}{为什么这个愚蠢的女孩不能呆在那里？ -- Why couldn't this stupid chick just stay there?}
### {273}{}{I couldn't let her go! And she resisted!}
{273}{}{我不能让她走！她反抗了！ -- I couldn't let her go! And she resisted!}
### {274}{}{[mumbles] Stupid bitch... Fuck! Why... Why did she want to run off..}
{274}{}{愚蠢的婊子。。。操！为什么？她为什么要逃跑。。 -- [mumbles] Stupid bitch... Fuck! Why... Why did she want to run off..}
