##############################
#???????: ??????? ???????
#???: ?????
#??????? ????????: ???????????? ???????? ?????. ??????: ?????????? ? ?????, ????? ??????? ??????.
#???? ????????: 05.09.2014
##############################
#??? ???? "????? 2207"
#????? "Rainman" ????????
##############################
#
#???????? ????????
#
# ?? ??????????
### {1}{}{You see a muscular raider.}
{1}{}{你看到一个肌肉发达的袭击者。 -- You see a muscular raider.}
### {2}{}{He seems relaxed - but you still can't shake this uncomfortable feeling...}
{2}{}{他看起来很放松，但你仍然无法摆脱这种不舒服的感觉。。。 -- He seems relaxed - but you still can't shake this uncomfortable feeling...}
#
# ????? ??????????
### {3}{}{You see the Hog.}
{3}{}{你看到猪了。 -- You see the Hog.}
### {4}{}{Addicted to the Drop, one and only leader of the Rainbow raiders.}
{4}{}{沉迷于空投，彩虹突袭者的唯一领导者。 -- Addicted to the Drop, one and only leader of the Rainbow raiders.}
#
#????? ?????????? ??????
#
### {10}{}{[his absent gaze of drug addict contrasts remarkably with bulging muscles under his tattoed skin. Even calm, he radiates a clear threat] Fresh meat on devil's kitchen... Everyone wants to get on the Hog's table... [with a great effort, he focuses his eyes on you] What do you want?}
{10}{}{[他对吸毒者的缺席凝视与他纹身皮肤下隆起的肌肉形成了鲜明对比。即使平静，他也散发出明显的威胁]魔鬼厨房里的新鲜肉。。。每个人都想上猪桌。。。[他费了很大的劲，把目光集中在你身上]你想要什么？ -- [his absent gaze of drug addict contrasts remarkably with bulging muscles under his tattoed skin. Even calm, he radiates a clear threat] Fresh meat on devil's kitchen... Everyone wants to get on the Hog's table... [with a great effort, he focuses his eyes on you] What do you want?}
### {11}{024}{Just looking around. Nice place you have here.}
{11}{024}{只是环顾四周。你这地方不错。 -- Just looking around. Nice place you have here.}
### {12}{016}{I'm pretty good at solving problems for a price. Interested?}
{12}{016}{我很擅长以一定的价格解决问题。感兴趣的 -- I'm pretty good at solving problems for a price. Interested?}
### {13}{025}{Do you know about G? He and his crew are operating on your turf.}
{13}{025}{你知道G吗？他和他的船员在你的地盘上活动。 -- Do you know about G? He and his crew are operating on your turf.}
### {14}{999}{Looks like the time is not right. I'll come by later.}
{14}{999}{看来时机不对。我稍后再来。 -- Looks like the time is not right. I'll come by later.}


### {1001}{}{[In his eyes you see your own body, hanging by the fires of hell] If this bitch doesn't disappear, the Hog will rip both of her legs, and beat her with them to death.}
{1001}{}{[在他的眼中，你可以看到你自己的身体，被地狱之火吊着]如果这个婊子不消失，猪会撕裂她的双腿，用它们把她打死。 -- [In his eyes you see your own body, hanging by the fires of hell] If this bitch doesn't disappear, the Hog will rip both of her legs, and beat her with them to death.}
### {101}{023}{Did you squeal something, Drop-head? It is I who will rip you up!}
{101}{023}{你尖叫了什么吗，低头？是我要把你撕碎！ -- Did you squeal something, Drop-head? It is I who will rip you up!}
### {102}{999}{Alright, alright, I'm leaving...}
{102}{999}{好吧，好吧，我要走了。。。 -- Alright, alright, I'm leaving...}
### {1002}{}{[his sight is tense at first, but then he recognizes you] Again, you come... Tread lightly, don't fall off the Rainbow...}
{1002}{}{[他的视线一开始很紧张，但后来他认出了你]你又来了。。。轻踩，不要从彩虹上掉下来。。。 -- [his sight is tense at first, but then he recognizes you] Again, you come... Tread lightly, don't fall off the Rainbow...}
### {103}{024}{Just looking around. Nice place you have here.}
{103}{024}{只是环顾四周。你这地方不错。 -- Just looking around. Nice place you have here.}
### {104}{016}{I'm pretty good at solving problems for a price. Interested?}
{104}{016}{我很擅长以一定的价格解决问题。感兴趣的 -- I'm pretty good at solving problems for a price. Interested?}
### {105}{025}{I stumbled upon a gang of kids, operating on your territory...}
{105}{025}{我偶然发现一群孩子在你的地盘上活动。。。 -- I stumbled upon a gang of kids, operating on your territory...}
### {106}{020}{Negotiations with Jackals are completed.}
{106}{020}{与豺狼的谈判已经完成。 -- Negotiations with Jackals are completed.}
### {1003}{}{[He looks at you strangely. You prefer to interpret his gaze as friendly] Here comes our negotiator... What brings you to me, smooth-talker?}
{1003}{}{[他奇怪地看着你。你更喜欢把他的目光解释为友好的]我们的谈判代表来了。。。是什么把你带到我这里来的，能说会道的人？ -- [He looks at you strangely. You prefer to interpret his gaze as friendly] Here comes our negotiator... What brings you to me, smooth-talker?}
### {107}{025}{Another matter to talk about. Lately, there's a company of little hustlers around the Rainbow, not very tall, but with a temper...}
{107}{025}{还有一件事要谈。最近，彩虹周围有一群小骗子，个子不高，但脾气暴躁。。。 -- Another matter to talk about. Lately, there's a company of little hustlers around the Rainbow, not very tall, but with a temper...}
### {108}{024}{I'm looking around. Nice place you have here.}
{108}{024}{我环顾四周。你这地方不错。 -- I'm looking around. Nice place you have here.}
### {109}{999}{Just checking on you. And I see that everything's good. See you then.}
{109}{999}{只是看看你。我看到一切都很好。到时见。 -- Just checking on you. And I see that everything's good. See you then.}
### {1004}{}{[It's like he's waiting for an attack at any moment - his eyes are all over the place, the whole body is tense. Seeing you, he pops another dose of the Drop, throws an empty ampoule on the floor, and squishes it with his heel. Another ampoule waits for its turn] Either you brought me a handful of batteries, or your whores have problems. What option is the best one for you, what do you think?}
{1004}{}{[这就像他随时都在等待袭击——他的眼睛到处都是，整个身体都很紧张。看到你，他又喝了一剂滴剂，把一个空安瓿扔在地板上，然后用脚后跟把它压扁。另一个安瓿在等着轮到它]要么你给我带了一把电池，要么你的妓女有问题。什么选择对你来说是最好的，你认为呢？ -- [It's like he's waiting for an attack at any moment - his eyes are all over the place, the whole body is tense. Seeing you, he pops another dose of the Drop, throws an empty ampoule on the floor, and squishes it with his heel. Another ampoule waits for its turn] Either you brought me a handful of batteries, or your whores have problems. What option is the best one for you, what do you think?}
### {1010}{028}{It's about the payment...}
{1010}{028}{这是关于付款。。。 -- It's about the payment...}
### {1011}{016}{I have everything under control on my territory. What about you? Do you need help?}
{1011}{016}{我控制着我领土上的一切。你呢？你需要帮助吗？ -- I have everything under control on my territory. What about you? Do you need help?}
### {1012}{025}{I stumbled upon a gang of kids, operating on your territory...}
{1012}{025}{我偶然发现一群孩子在你的地盘上活动。。。 -- I stumbled upon a gang of kids, operating on your territory...}
### {1013}{999}{I'm good. Just walking by. }
{1013}{999}{我很好。只是路过。 -- I'm good. Just walking by. }
### {1005}{}{[you get chills from the Hog's unusually calm voice] Looks like you think that local rules are not for you. Where's my money, you whore herder? And you pay a half extra - for troubles. }
{1005}{}{[你会从猪异常平静的声音中感到不寒而栗]看起来你认为当地的规定不适合你。我的钱在哪里，你这个婊子养的？而且你还要为麻烦多付一半。 -- [you get chills from the Hog's unusually calm voice] Looks like you think that local rules are not for you. Where's my money, you whore herder? And you pay a half extra - for troubles. }
### {1014}{999}{Of course, here's the full amount! My apologies, it won't happen again.}
{1014}{999}{当然，这是全额！我很抱歉，这种事不会再发生了。 -- Of course, here's the full amount! My apologies, it won't happen again.}
### {1015}{023}{I'd better throw some punches in this pig snout of yours! You get dicks, not batteries!}
{1015}{023}{我最好在你的猪鼻子上打几拳！你拿的是白痴，不是电池！ -- I'd better throw some punches in this pig snout of yours! You get dicks, not batteries!}
### {1016}{999}{I'll get it! Everything, down to the last battery! But a little later.}
{1016}{999}{我会得到的！一切，直到最后一个电池！但稍晚一点。 -- I'll get it! Everything, down to the last battery! But a little later.}
### {1006}{}{[the Hog looks surprised to see you] I thought that you were smart enough to leave the Radius completely... [the ampoule in his hand crunches into mush when he clenches fists] You has been fucking me up for three fucking months! I've seen a lot of different crazy fuckers, but you - you have outdone them all! That's okay, I will take my cut now - together with your ripped intestines!}
{1006}{}{[猪看到你看起来很惊讶]我以为你足够聪明，可以完全离开Radius。。。[他握紧拳头时手里的安瓿嘎吱嘎吱地变成糊状]你他妈的已经把我搞三个月了！我见过很多不同的疯狂混蛋，但你——你已经超越了他们！没关系，我现在就把我的伤口和你撕裂的肠子一起拿走！ -- [the Hog looks surprised to see you] I thought that you were smart enough to leave the Radius completely... [the ampoule in his hand crunches into mush when he clenches fists] You has been fucking me up for three fucking months! I've seen a lot of different crazy fuckers, but you - you have outdone them all! That's okay, I will take my cut now - together with your ripped intestines!}
### {1017}{998}{I'm so good at picking the right moment to come...}
{1017}{998}{我非常善于选择合适的时机。。。 -- I'm so good at picking the right moment to come...}
### {1018}{998}{You get squat, bitch! Fucking you up? I haven't even started! Let's see how it's done!}
{1018}{998}{你蹲着，婊子！搞砸你了？我还没开始呢！让我们看看是怎么做到的！ -- You get squat, bitch! Fucking you up? I haven't even started! Let's see how it's done!}


### {110}{}{[With a swift motion, he pours the content of another ampoule down his throat] Looks like you and Shepherd had some problem. You have two minutes to explain yourself. [his breathing gets rapid, fists clenching] And choose words carefully, because the ice you are walking on is very fucking thin.}
{110}{}{[他迅速地将另一安瓿的内容物倒进喉咙]看起来你和谢泼德有什么问题。你有两分钟的时间来解释自己。[他的呼吸越来越急促，拳头紧紧地握着]仔细选词，因为你走在上面的冰很薄。 -- [With a swift motion, he pours the content of another ampoule down his throat] Looks like you and Shepherd had some problem. You have two minutes to explain yourself. [his breathing gets rapid, fists clenching] And choose words carefully, because the ice you are walking on is very fucking thin.}
### {111}{012}{Well, your brown fella turned out to be too fickle for a serious fight.}
{111}{012}{事实证明，你那个棕色的家伙太善变了，不适合一场严肃的打斗。 -- Well, your brown fella turned out to be too fickle for a serious fight.}
### {112}{012}{There was a minor misunderstanding, which, I'm sure, won't get in the way of our good relationship.}
{112}{012}{有一个小误会，我相信，这不会妨碍我们的良好关系。 -- There was a minor misunderstanding, which, I'm sure, won't get in the way of our good relationship.}
### {113}{015}{It was all an accident, I have nothing to do with it! Seriously!}
{113}{015}{这都是一场意外，我与之无关！认真地 -- It was all an accident, I have nothing to do with it! Seriously!}


### {1202}{}{[he menacingly approaches you] Do you realize that you murdered my brother because of some cheap whore?}
{1202}{}{[他威胁性地接近你]你知道你谋杀我哥哥是因为某个贱妓女吗？ -- [he menacingly approaches you] Do you realize that you murdered my brother because of some cheap whore?}
### {123}{023}{Are you going to organize a thorough review meet-up when every petty raider of yours is killed? It's entirely his fault - he tried to act cool while couldn't even take a punch...}
{123}{023}{当你的每一个小袭击者都被杀时，你会组织一次彻底的审查会议吗？这完全是他的错——他试图表现得很冷静，却连一拳都打不动。。。 -- Are you going to organize a thorough review meet-up when every petty raider of yours is killed? It's entirely his fault - he tried to act cool while couldn't even take a punch...}
### {124}{013}{There's a bright side to it - I have identified and eliminated the weak link on the Rainbow, which could lead to many of your problems.}
{124}{013}{它有光明的一面——我已经识别并消除了彩虹上的薄弱环节，这可能会导致你的许多问题。 -- There's a bright side to it - I have identified and eliminated the weak link on the Rainbow, which could lead to many of your problems.}


### {130}{}{[his facial expression changes, although it is barely noticeable] What are you now trying to say to me? }
{130}{}{[他的面部表情发生了变化，尽管几乎不明显]你现在想对我说什么？ -- [his facial expression changes, although it is barely noticeable] What are you now trying to say to me? }
### {131}{014}{Let's be objective - Shepherd couldn't handle his duties of brothel manager. Damn, he couldn't even deal with one whore! He ended up running and chasing her around the whole Rainbow. And he wasn't much of a challenge to me, by the way... How do you think it makes you look?}
{131}{014}{让我们客观一点——谢泼德无法胜任妓院经理的职责。该死，他连一个妓女都对付不了！最后，他跑了一圈，在整个彩虹周围追着她。顺便说一句，他对我来说并不是什么挑战。。。你觉得它让你看起来怎么样？ -- Let's be objective - Shepherd couldn't handle his duties of brothel manager. Damn, he couldn't even deal with one whore! He ended up running and chasing her around the whole Rainbow. And he wasn't much of a challenge to me, by the way... How do you think it makes you look?}
### {132}{023}{I mean, your Shepherd was a wussie. All he was suited for is cleaning the cesspools...}
{132}{023}{我的意思是，你的牧羊人是个胆小鬼。他只适合打扫污水池。。。 -- I mean, your Shepherd was a wussie. All he was suited for is cleaning the cesspools...}
### {133}{022}{Erm... I won, he lost, what else to say? He couldn't take the blow of fate...}
{133}{022}{呃。。。我赢了，他输了，还有什么好说的？他无法承受命运的打击。。。 -- Erm... I won, he lost, what else to say? He couldn't take the blow of fate...}


### {140}{}{[the Hog freezes, then stretches his thin lips in a smile] You may be right somehow... [he stops, then continues] That's how it is - I took a loss. Because of you. And you're gonna make it up to me. You take Shepherd's place. Your security payment comes once a month. Three hundred. The rest you'll figure out. And don't you dare to screw this up...}
{140}{}{[猪僵住了，然后伸出薄薄的嘴唇微笑]你可能是对的。。。[他停了下来，然后继续]事情就是这样——我输了。因为你。你会补偿我的。你取代谢泼德的位置。你的保证金每月一次。三百。剩下的你会想明白的。你不敢搞砸这件事。。。 -- [the Hog freezes, then stretches his thin lips in a smile] You may be right somehow... [he stops, then continues] That's how it is - I took a loss. Because of you. And you're gonna make it up to me. You take Shepherd's place. Your security payment comes once a month. Three hundred. The rest you'll figure out. And don't you dare to screw this up...}
### {141}{999}{Good position, career prospects... Why not? I agree.}
{141}{999}{良好的职位，职业前景。。。为什么不呢？我同意。 -- Good position, career prospects... Why not? I agree.}
### {142}{023}{Whaaat? Who do you think I am? A half-assed pimp? Deal with your sluts yourself, asshole.}
{142}{023}{什么？你以为我是谁？半信半疑的皮条客？你自己处理你的荡妇，混蛋。 -- Whaaat? Who do you think I am? A half-assed pimp? Deal with your sluts yourself, asshole.}


### {150}{}{[he stares at you, not even blinking... And suddenly starts to laugh] Hahahah!! I even fell for it for a moment! Okay, tough guy, if you are so convincing... And strong enough to make Shepherd take a dirt nap... You belong to the brothel. Don't twitch. What I mean is you take Shepherd's place. Your security payment comes once a month. Three hundred. That's it. Go. You'll figure out the rest. It's in your own interests. "I have nothing to do with it"... Fucking hell... [he sinks into his narcotic thoughts, smiling]}
{150}{}{[他目不转睛地盯着你。。。突然大笑起来：哈哈哈！！我甚至一度爱上了它！好吧，硬汉，如果你这么有说服力。。。而且足够强壮，可以让谢泼德睡个午觉。。。你是妓院的。不要抽搐。我的意思是你取代谢泼德的位置。你的保证金每月一次。三百。就这样，走吧。剩下的你会解决的。这符合你自己的利益。“我与此事无关”。。。他妈的。。。[他陷入沉思，微笑着 -- he stares at you, not even blinking... And suddenly starts to laugh] Hahahah!! I even fell for it for a moment! Okay, tough guy, if you are so convincing... And strong enough to make Shepherd take a dirt nap... You belong to the brothel. Don't twitch. What I mean is you take Shepherd's place. Your security payment comes once a month. Three hundred. That's it. Go. You'll figure out the rest. It's in your own interests. "I have nothing to do with it"... Fucking hell... [he sinks into his narcotic thoughts, smiling]}
### {151}{999}{Uh... Thanks... I guess...}
{151}{999}{嗯谢谢我想。。。 -- Uh... Thanks... I guess...}

### {1601}{}{[You patiently wait for the Hog to pop another dose of the Drop] Argh... Yes, slick one, you can be of some help...}
{1601}{}{[你耐心地等待猪再注射一剂滴剂]啊。。。是的，圆滑的，你可以帮上点忙。。。 -- [You patiently wait for the Hog to pop another dose of the Drop] Argh... Yes, slick one, you can be of some help...}
### {161}{017}{I'm listening.}
{161}{017}{我在听。 -- I'm listening.}
### {1602}{}{[You patiently wait for the Hog to pop another dose of the Drop] Argh... I don't need you... Go...}
{1602}{}{[你耐心地等待猪再注射一剂滴剂]啊。。。我不需要你。。。去 -- [You patiently wait for the Hog to pop another dose of the Drop] Argh... I don't need you... Go...}
### {162}{999}{Damn, why didn't you say so earlier...}
{162}{999}{妈的，你为什么不早点说。。。 -- Damn, why didn't you say so earlier...}


### {170}{}{There's one crazed freak... Loudmouth. He's leading the Jackals... I used to run with him and his pack. [he shows you his crippled hand] See? This bitch took off my finger... But I'm not mad at him. I want to make peace.}
{170}{}{有一个疯狂的怪胎。。。大声说话。他在领导豺狼队。。。我曾经和他和他的背包一起跑步。[他向你展示他残废的手]看到了吗？这个婊子摘下了我的手指。。。但我并没有生他的气。我想讲和。 -- There's one crazed freak... Loudmouth. He's leading the Jackals... I used to run with him and his pack. [he shows you his crippled hand] See? This bitch took off my finger... But I'm not mad at him. I want to make peace.}
### {171}{018}{And you need a middleman for that?}
{171}{018}{你需要一个中间人吗？ -- And you need a middleman for that?}


### {180}{}{Yes. Now it's quiet - they sell us weapons, we supply them with Drop... But everything can go to shits at any moment. [he shakes head] Fucking asshole... Never learns... You... Convince him. No one benefits from war...}
{180}{}{对现在很安静——他们向我们出售武器，我们向他们提供空投。。。但任何事情都可能随时陷入困境。[他摇头]他妈的混蛋。。。从不学习。。。你说服他。没有人从战争中受益。。。 -- Yes. Now it's quiet - they sell us weapons, we supply them with Drop... But everything can go to shits at any moment. [he shakes head] Fucking asshole... Never learns... You... Convince him. No one benefits from war...}
### {181}{019}{Ha! You got the right man for the job, the diplomacy is what I do! Will deliver the result, just wait.}
{181}{019}{哈你找到了合适的人选，外交就是我的工作！将交付结果，只需等待。 -- Ha! You got the right man for the job, the diplomacy is what I do! Will deliver the result, just wait.}
### {182}{999}{No, thank you. I don't want to go near such crazy people. All the best, bye!}
{182}{999}{不用了，谢谢。我不想接近这样疯狂的人。祝你一切顺利，再见！ -- No, thank you. I don't want to go near such crazy people. All the best, bye!}


### {190}{}{[he closes his eyes, waiting for a drug to kick in] Good. Go and do it... The reward... Will please you... That's it, go...}
{190}{}{[他闭上眼睛，等待药物进入]很好。去做吧…奖励。。。请你。。。就这样，走吧。。。 -- [he closes his eyes, waiting for a drug to kick in] Good. Go and do it... The reward... Will please you... That's it, go...}
### {191}{999}{Got it, chief. Wait for the news.}
{191}{999}{明白了，首领。等待消息。 -- Got it, chief. Wait for the news.}


### {200}{}{[Slowly shakes his head to the rhythm of your words] What did Loudmouth say?}
{200}{}{[随着你说话的节奏慢慢摇头]劳德茅斯说了什么？ -- [Slowly shakes his head to the rhythm of your words] What did Loudmouth say?}
### {201}{021}{Well, swearing and cheap bluster aside, the message is pretty short and clear - they won't attack the Rainbow, while your business relations are in the interest of both sides. As a gesture of goodwill, they even ready to give you a discount on their next batch of weapons.}
{201}{021}{好吧，抛开脏话和廉价的虚张声势不谈，传达的信息非常简短而明确——他们不会攻击彩虹号，而你们的商业关系符合双方的利益。为了表示善意，他们甚至准备在下一批武器上给你折扣。 -- Well, swearing and cheap bluster aside, the message is pretty short and clear - they won't attack the Rainbow, while your business relations are in the interest of both sides. As a gesture of goodwill, they even ready to give you a discount on their next batch of weapons.}


### {210}{}{[he grins] You're good... If you managed to shake even this guy's stuck-up brain... [he waves to one of his raiders, who leaves the room and gets back carrying a rocket launcher] Here. Take this. Don't use it on the Rainbow though... And one more thing - if you want to fly, you can... Expect a discount from... Apothecary... [his eyes become unfocused and murky, speech is less cohesive. Looks like the conversation is over]}
{210}{}{[他咧嘴笑着]你很好。。。如果你能动摇这家伙的大脑。。。[他向他的一名袭击者挥手，后者离开房间，带着火箭发射器回来]这里。拿着这个。不过不要在彩虹上使用它。。。还有一件事——如果你想飞，你可以。。。期待来自…的折扣。。。药剂师[他的眼睛变得不集中，模糊不清，讲话缺乏连贯性。看起来谈话已经结束了 -- he grins] You're good... If you managed to shake even this guy's stuck-up brain... [he waves to one of his raiders, who leaves the room and gets back carrying a rocket launcher] Here. Take this. Don't use it on the Rainbow though... And one more thing - if you want to fly, you can... Expect a discount from... Apothecary... [his eyes become unfocused and murky, speech is less cohesive. Looks like the conversation is over]}
### {211}{999}{Christmas came earlier this year...}
{211}{999}{今年早些时候圣诞节来了。。。 -- Christmas came earlier this year...}


### {220}{}{[with an unusual speed, Hog rushes to you - and a moment later his huge fist smashes into your ribs. It's a miracle your insides didn't fly out of your throat] And you can take a punch, shithead?! Get your ass out of here!}
{220}{}{【猪以不同寻常的速度冲向你——过了一会儿，他那巨大的拳头砸在了你的肋骨上。你的内脏没有从喉咙里飞出来真是个奇迹】你可以挨一拳吗，混蛋？！滚出去！ -- [with an unusual speed, Hog rushes to you - and a moment later his huge fist smashes into your ribs. It's a miracle your insides didn't fly out of your throat] And you can take a punch, shithead?! Get your ass out of here!}
### {221}{998}{Oh you asshole! I'll pull your innards out for this! Die, bitch! }
{221}{998}{哦，你这个混蛋！我要把你的内脏拔出来！死吧，婊子！ -- Oh you asshole! I'll pull your innards out for this! Die, bitch! }
### {222}{999}{It hurts... Okay, I'm leaving. But we haven't finished...}
{222}{999}{很疼。。。好的，我要走了。但我们还没有完成。。。 -- It hurts... Okay, I'm leaving. But we haven't finished...}


### {230}{}{[the Hog calmly nods. But in his cleared eyes you see death] I'm going to squeeze every last drop of blood out of you - and put it in my morning dose...}
{230}{}{[猪平静地点头。但在他清澈的眼睛里，你看到了死亡]我要把你身上的最后一滴血都挤出来——放在我早上的剂量里。。。 -- [the Hog calmly nods. But in his cleared eyes you see death] I'm going to squeeze every last drop of blood out of you - and put it in my morning dose...}
### {231}{998}{Let's get down to business, you piggy head! }
{231}{998}{咱们言归正传吧，你这个猪头！ -- Let's get down to business, you piggy head! }
### {232}{998}{That didn't sound very friendly...}
{232}{998}{听起来不太友好。。。 -- That didn't sound very friendly...}


### {240}{}{Yes... The best place in Radius... Girls, booze... And the Drop. [he takes out an ampoule and wistfully gazes at it] This is what started it all... And this is what will be the end... Ask, if you need something... But not... Me... [he closes eyes, delving deeply into his intoxicated dreams]}
{240}{}{对Radius最好的地方。。。女孩们，喝酒。。。还有滴滴答答。[他拿出一个安瓿，若有所思地盯着它]这就是一切的开始。。。这就是结局。。。问问，如果你需要什么。。。但不是。。。我…[他闭上眼睛，深深地沉浸在他陶醉的梦境中] -- Yes... The best place in Radius... Girls, booze... And the Drop. [he takes out an ampoule and wistfully gazes at it] This is what started it all... And this is what will be the end... Ask, if you need something... But not... Me... [he closes eyes, delving deeply into his intoxicated dreams]}
### {241}{010}{I didn't even think about bothering such a respectable man with stupid questions... Hey! Do you hear me?}
{241}{010}{我甚至没有想过用愚蠢的问题来打扰这样一个受人尊敬的人。。。嘿你听到了吗？ -- I didn't even think about bothering such a respectable man with stupid questions... Hey! Do you hear me?}
### {242}{999}{[leave quietly]}
{242}{999}{[安静地离开 -- leave quietly]}


### {250}{}{[he slowly turns his head. Tattoed spider on his neck moves his paws. Looks creepy.] Yes... I heard. For now, they are just making noise... But we were like this once too. All it takes is to get the taste of blood - and you will never be able to stop... [he smiles to his thoughts] Why did you mention them?}
{250}{}{[他慢慢地转过头。脖子上的纹身蜘蛛在动爪子。看起来很恐怖。]是的。。。我听说了。现在，他们只是在制造噪音。。。但我们也曾经是这样的。只需要尝到血腥的味道——你永远无法停止。。。[他对自己的思绪微笑]你为什么提到它们？ -- [he slowly turns his head. Tattoed spider on his neck moves his paws. Looks creepy.] Yes... I heard. For now, they are just making noise... But we were like this once too. All it takes is to get the taste of blood - and you will never be able to stop... [he smiles to his thoughts] Why did you mention them?}
### {251}{026}{I see an opportunity to put their skills to good use. To the Rainbow's benefit.}
{251}{026}{我看到了一个充分利用他们技能的机会。为了彩虹的利益。 -- I see an opportunity to put their skills to good use. To the Rainbow's benefit.}
### {252}{999}{Just... Saying. Well, I won't be bothering you anymore.}
{252}{999}{只是说好吧，我不会再打扰你了。 -- Just... Saying. Well, I won't be bothering you anymore.}


### {260}{}{How is that, may I ask? All I can think of is to boil them into a stew in a big pot and feed my guys with it... Haha... A good idea, actually...}
{260}{}{我可以问一下是怎么回事吗？我所能想到的就是在大锅里把它们煮成炖菜，然后用它喂我的伙计们…哈哈。。。一个好主意，实际上。。。 -- How is that, may I ask? All I can think of is to boil them into a stew in a big pot and feed my guys with it... Haha... A good idea, actually...}
### {261}{027}{Where's the rationality in that? You are low on people. And it's obvious that G and his fellas are not great at fights - yet - but you can use them as scouts! Put them around the Rainbow, so they could monitor the situation everywhere. There are threats in Radius except for the Jackals, you know... Did I mention that you can pay them less than grown-ups?}
{261}{027}{其中的合理性在哪里？你对人太低了。很明显，G和他的队员们还不擅长打架，但你可以把他们当作球探！把他们放在彩虹周围，这样他们就可以监视各地的情况。除了豺狼，Radius还有威胁，你知道。。。我有没有提到你可以比成年人付得更少？ -- Where's the rationality in that? You are low on people. And it's obvious that G and his fellas are not great at fights - yet - but you can use them as scouts! Put them around the Rainbow, so they could monitor the situation everywhere. There are threats in Radius except for the Jackals, you know... Did I mention that you can pay them less than grown-ups?}
### {262}{999}{Uhh... I didn't mean this... Ahem... I better go think about it. Return with something better...}
{262}{999}{嗯。。。我不是这个意思。。。啊。。。我最好去考虑一下。带着更好的东西回来。。。 -- Uhh... I didn't mean this... Ahem... I better go think about it. Return with something better...}


### {270}{}{[he nods, twirling the ampoule with his intact fingers] Yes... This will do. Tell them that I agree... We lose nothing. But if they screw up - the stew is still an option...}
{270}{}{[他点了点头，用他完好的手指转动安瓿]是的。。。这就行了。告诉他们我同意。。。我们一无所获。但如果他们搞砸了——炖菜仍然是一种选择。。。 -- [he nods, twirling the ampoule with his intact fingers] Yes... This will do. Tell them that I agree... We lose nothing. But if they screw up - the stew is still an option...}
### {271}{999}{I hope it never comes to that. See you around, Hog.}
{271}{999}{我希望它永远不会变成那样。回头见，猪。 -- I hope it never comes to that. See you around, Hog.}


### {280}{}{What exactly didn't you understand? A client pays and fucks whores, you maintain order. The rest is my business. [he pops another ampoule] So hand over the batteries and leave, don't ruin this for me...}
{280}{}{你到底不明白什么？客户付钱嫖娼，你维持秩序。剩下的是我的事。[他打开另一个安瓿]所以把电池交出来离开，不要毁了我。。。 -- What exactly didn't you understand? A client pays and fucks whores, you maintain order. The rest is my business. [he pops another ampoule] So hand over the batteries and leave, don't ruin this for me...}
### {281}{999}{Sure. Here's for this month. See you around.}
{281}{999}{当然这是本月的。回头见。 -- Sure. Here's for this month. See you around.}
### {282}{029}{What? Do you always collect twice, or it's just me?}
{282}{029}{什么你总是收集两次，还是只有我？ -- What? Do you always collect twice, or it's just me?}
### {283}{030}{You know, I have a difficult situation - it turned out to be not so easy...}
{283}{030}{你知道，我的处境很艰难——结果并不那么容易。。。 -- You know, I have a difficult situation - it turned out to be not so easy...}


### {290}{}{[his voice starts to growl] What are you fucking saying?}
{290}{}{[他的声音开始咆哮]你他妈的在说什么？ -- [his voice starts to growl] What are you fucking saying?}
### {291}{031}{I paid you recently! You were just popping another dose...}
{291}{031}{我最近付钱给你了！你刚刚又注射了一剂。。。 -- I paid you recently! You were just popping another dose...}
### {292}{999}{No, nothing. Here's the cut. Sorry.}
{292}{999}{不，什么都没有。这是切口。很抱歉 -- No, nothing. Here's the cut. Sorry.}
### {293}{030}{You know, I have trouble getting the necessary amount.}
{293}{030}{你知道，我很难得到必要的金额。 -- You know, I have trouble getting the necessary amount.}


### {300}{}{That's your problem. Do whatever you want. Use your ass to earn it, I don't fucking care.}
{300}{}{这是你的问题。你想做什么就做什么。用你的屁股来赚，我他妈的不在乎。 -- That's your problem. Do whatever you want. Use your ass to earn it, I don't fucking care.}
### {301}{999}{Damn... I have to think of something...}
{301}{999}{该死我得想点什么。。。 -- Damn... I have to think of something...}


### {310}{}{[He wrinkles his forehead, trying to remember something. His muscles start to twitch uncontrollably, which makes tattoos of the skeletons, chimeras, and dog heads move in a wild dance. Then his sight clears] Fuck, you are right!... Okay, don't mind me, everything can happen. That's it, go, I need to rest.}
{310}{}{[他皱着额头，试图记住什么。他的肌肉开始不受控制地抽搐，这使得骷髅、嵌合体和狗头的纹身像狂野的舞蹈一样移动。然后他的视线消失了]操，你是对的！。。。好吧，别介意，一切都有可能发生。就这样，走吧，我需要休息。 -- [He wrinkles his forehead, trying to remember something. His muscles start to twitch uncontrollably, which makes tattoos of the skeletons, chimeras, and dog heads move in a wild dance. Then his sight clears] Fuck, you are right!... Okay, don't mind me, everything can happen. That's it, go, I need to rest.}
### {311}{999}{Nice.}
{311}{999}{美好的 -- Nice.}
