
#???????? ????????
#
### {1}{}{You see a trader.}
{1}{}{你看到一个交易员。 -- You see a trader.}
### {2}{}{You see a weapons dealer.}
{2}{}{你看到一个军火商。 -- You see a weapons dealer.}
### {3}{}{You see a merchant.}
{3}{}{你看到一个商人。 -- You see a merchant.}
### {4}{}{You see an arms-dealing merchant.}
{4}{}{你看到一个军火商。 -- You see an arms-dealing merchant.}
### {5}{}{You see a vendor.}
{5}{}{你看到一个供应商。 -- You see a vendor.}
### {6}{}{A common-looking weapon-selling merchant.}
{6}{}{一个长相普通的卖武器的商人。 -- A common-looking weapon-selling merchant.}
### {7}{}{Just an arms dealer.}
{7}{}{只是一个军火商。 -- Just an arms dealer.}
### {8}{}{One of Jackals, a weapon trader.}
{8}{}{一个豺狼，一个武器商人。 -- One of Jackals, a weapon trader.}
### {9}{}{One of Jackals. He sells local weaponry.}
{9}{}{豺狼之一。他出售当地武器。 -- One of Jackals. He sells local weaponry.}
#
#????? ?????????? ??????
#
### {10}{}{So, whatcha need?}
{10}{}{那么，你需要什么？ -- So, whatcha need?}
### {11}{}{Come on, I have something for you here.}
{11}{}{来吧，我这里有东西给你。 -- Come on, I have something for you here.}
### {12}{}{Come on, don't be so cheap!}
{12}{}{来吧，别这么贱！ -- Come on, don't be so cheap!}
### {13}{}{Show me what you have.}
{13}{}{给我看看你有什么。 -- Show me what you have.}
### {14}{}{No, I'm already leaving.}
{14}{}{不，我已经走了。 -- No, I'm already leaving.}
### {15}{}{Why the hell are your ammo so expensive?}
{15}{}{为什么你的弹药这么贵？ -- Why the hell are your ammo so expensive?}
### {16}{}{What do you think? They are genuine ones, factory-made! The amount of these birds in Radius is becoming smaller every day, so you have to chase them around different parts of wasteland, old warehouses, and such - but it's still worth it! Don't like the price - go buy homemade ones from a junk dealer. Except they are no good anyway.}
{16}{}{你怎么看？它们是货真价实的，工厂制造的！Radius中这些鸟的数量每天都在减少，所以你必须在荒地、旧仓库等的不同地方追逐它们——但这仍然是值得的！不喜欢这个价格——去旧货贩子那里买自制的吧。但它们无论如何都不好。 -- What do you think? They are genuine ones, factory-made! The amount of these birds in Radius is becoming smaller every day, so you have to chase them around different parts of wasteland, old warehouses, and such - but it's still worth it! Don't like the price - go buy homemade ones from a junk dealer. Except they are no good anyway.}
### {17}{}{I see... Well, let's look at your goods one more time.}
{17}{}{我明白了。。。好吧，让我们再看一次你的货物。 -- I see... Well, let's look at your goods one more time.}
### {18}{}{Understood. I've got to go now.}
{18}{}{明白了。我现在得走了。 -- Understood. I've got to go now.}
### {19}{}{When will you sell me more serious guns?}
{19}{}{你什么时候卖给我更严重的枪支？ -- When will you sell me more serious guns?}
### {20}{}{When your little hands grow up enough to handle them. Serious guns are for serious men! And you are fine with the current ones.}
{20}{}{当你的小手长大到可以处理它们的时候。严肃的枪是给严肃的人的！你对目前的情况很满意。 -- When your little hands grow up enough to handle them. Serious guns are for serious men! And you are fine with the current ones.}
{21}{}{}
{22}{}{}
{23}{}{}
{24}{}{}
{25}{}{}
{26}{}{}
#
#????????? ?????????
# ????????????? ?????????
### {1000}{}{Don't interrupt me, I'm busy.}
{1000}{}{别打扰我，我很忙。 -- Don't interrupt me, I'm busy.}
### {1001}{}{Can't you see I'm busy?}
{1001}{}{你看不出我很忙吗？ -- Can't you see I'm busy?}
### {1002}{}{Not now.}
{1002}{}{现在不行。 -- Not now.}
### {1003}{}{Huh?}
{1003}{}{嗯？ -- Huh?}
### {1004}{}{Just go away.}
{1004}{}{走开。 -- Just go away.}
### {1005}{}{Don't bother me, I need to rest...}
{1005}{}{别打扰我，我需要休息。。。 -- Don't bother me, I need to rest...}
### {1006}{}{What do you need?}
{1006}{}{你需要什么？ -- What do you need?}
### {1007}{}{[grins]}
{1007}{}{[咧嘴笑 -- grins]}
### {1008}{}{Leave me be, I have work to do.}
{1008}{}{别管我，我还有工作要做。 -- Leave me be, I have work to do.}
### {1009}{}{Yeah-yeah, you're good and all.}
{1009}{}{是的，是的，你很好。 -- Yeah-yeah, you're good and all.}
# ??????????? ?????????
### {1010}{}{Don't interrupt me, I'm busy.}
{1010}{}{别打扰我，我很忙。 -- Don't interrupt me, I'm busy.}
### {1011}{}{Can't you see I'm busy?}
{1011}{}{你看不出我很忙吗？ -- Can't you see I'm busy?}
### {1012}{}{Not now!}
{1012}{}{现在不行！ -- Not now!}
### {1013}{}{Just go away.}
{1013}{}{走开。 -- Just go away.}
### {1014}{}{Just turn around and walk away!}
{1014}{}{转身走开！ -- Just turn around and walk away!}
### {1015}{}{Don't bother me, I need to rest...}
{1015}{}{别打扰我，我需要休息。。。 -- Don't bother me, I need to rest...}
### {1016}{}{What do you need?}
{1016}{}{你需要什么？ -- What do you need?}
### {1017}{}{...All sorts of scum walking around...}
{1017}{}{…到处都是渣滓。。。 -- ...All sorts of scum walking around...}
### {1018}{}{Leave me be, I have a work to do!}
{1018}{}{别管我，我还有工作要做！ -- Leave me be, I have a work to do!}
### {1019}{}{Get lost!}
{1019}{}{迷路 -- Get lost!}
# ????????????? ?????????
### {1020}{}{Get lost, you piece of shit!}
{1020}{}{迷路吧，你这个混蛋！ -- Get lost, you piece of shit!}
### {1021}{}{Get the fuck out!}
{1021}{}{滚出去！ -- Get the fuck out!}
### {1022}{}{Better keep away from me, you freak!}
{1022}{}{最好离我远点，你这个怪胎！ -- Better keep away from me, you freak!}
### {1023}{}{Get out!!!}
{1023}{}{滚出去！！！ -- Get out!!!}
### {1024}{}{I'm gonna fuck you up!}
{1024}{}{我要搞砸你！ -- I'm gonna fuck you up!}
### {1025}{}{Want me to punch you in the face?!}
{1025}{}{想让我打你的脸吗？！ -- Want me to punch you in the face?!}
### {1026}{}{Get out of my sight!}
{1026}{}{滚出我的视线！ -- Get out of my sight!}
### {1027}{}{What the fuck do you want?!}
{1027}{}{你他妈的想要什么？！ -- What the fuck do you want?!}
### {1028}{}{Piece of shit!}
{1028}{}{糟透了！ -- Piece of shit!}
### {1029}{}{You motherfucker, get lost!}
{1029}{}{你这个混蛋，滚吧！ -- You motherfucker, get lost!}
#???? ????? ???????
### {1030}{}{Not now, I'm busy.}
{1030}{}{现在不行，我很忙。 -- Not now, I'm busy.}
### {1031}{}{Just wait one minute!}
{1031}{}{等一下！ -- Just wait one minute!}
### {1032}{}{Fuck! I'll be right back!}
{1032}{}{操！我马上回来！ -- Fuck! I'll be right back!}
{1033}{}{}
{1034}{}{}
{1035}{}{}
{1036}{}{}
{1037}{}{}
{1038}{}{}
{1039}{}{}
# ????????????? ?????????
### {1040}{}{Keep your hands to yourself, schmuck!}
{1040}{}{把手放在自己身上，笨蛋！ -- Keep your hands to yourself, schmuck!}
### {1041}{}{Hey! Keep your hands away from my pockets!}
{1041}{}{嘿把手从我的口袋里拿开！ -- Hey! Keep your hands away from my pockets!}
### {1042}{}{You are pushing ME around!?}
{1042}{}{你在逼我！？ -- You are pushing ME around!?}
### {1043}{}{Do this one more time and I will bury you!}
{1043}{}{再这样做一次，我就把你埋了！ -- Do this one more time and I will bury you!}
### {1044}{}{Oh, get the fuck out!}
{1044}{}{哦，滚出去！ -- Oh, get the fuck out!}
### {1045}{}{Do I bother you? Because I don't give a shit!}
{1045}{}{我打扰你了吗？因为我一点也不在乎！ -- Do I bother you? Because I don't give a shit!}
### {1046}{}{Better don't piss me off.}
{1046}{}{最好别惹我生气。 -- Better don't piss me off.}
### {1047}{}{I'm going to shove these hands of yours so deep into your ass!}
{1047}{}{我要把你的双手深深地塞进你屁股里！ -- I'm going to shove these hands of yours so deep into your ass!}
### {1048}{}{Wanna push around? Come here!}
{1048}{}{想四处走走吗？过来！ -- Wanna push around? Come here!}
### {1049}{}{[angrily looks at you]}
{1049}{}{[愤怒地看着你 -- angrily looks at you]}
