#############################################################
#????????? ???? ??? ???????? << ??? >> 
#????? ?????? ? scripts.lst << ??? >>
#############################################################
#????????? ?????:
#?????? 1-9 - ???????? ?????????;
#?????? 10-29 - ?????????? ? ?????????;
#?????? 30-99 - ???? ?? ????, ?? ?????, ??? ??????????...
#?????, ?? ?????? ???????.
#?????? ????? ?????? 100, ?.?. 100 - ???? ???? ???????, 200 - ??????.
#??????? ????????? ???? ????? 10, ?.?. 100, 110, 120 ? ?.?. ??? ??? 
#??? ??????? 100 ???????????? Node010, ??? ??????? 240 - Node024.
#??? ??????? ?????? - ???????? ?????????, ?.?. ?? ??????? 650 ?????? ????? 651, 652, 653 ? ?.?. 
#??? ?????? ??????????? ???????????? ?????????????? ????? (????????, ??????? 360 ??????? ?? 3601 ? 3602,
#??? ?? ???????? ????????? Node, ?????? ?? ????? ? ??????? ????? - 361, 362 ? ?.?.)
#############################################################
#????? ??????????????? ??????? ?? ????????? ????????? ??????? ??????? ???????,
#??? ??? ???? ????? ????? ??????!!!
############################################################
#?????????? ??? "????? 2207", by Rainman, 06/11/2010
#############################################################
#
#???????? ????????
#
# ?? ??????????
#
### {1}{}{You see Brook.}
{1}{}{你看到布鲁克了。 -- You see Brook.}
### {2}{}{This glum man is Brook, Catty's dad. He is always dissatisfied with something.}
{2}{}{这个闷闷不乐的人是布鲁克，凯蒂的爸爸。他总是对某事不满意。 -- This glum man is Brook, Catty's dad. He is always dissatisfied with something.}
#
# ????? ??????????
#
### {3}{}{You see Brook.}
{3}{}{你看到布鲁克了。 -- You see Brook.}
### {4}{}{This glum man is Brook, Catty's dad. He is always dissatisfied with something.}
{4}{}{这个闷闷不乐的人是布鲁克，凯蒂的爸爸。他总是对某事不满意。 -- This glum man is Brook, Catty's dad. He is always dissatisfied with something.}
#
#????? ?????????? ?????? ?? ??????????
#
{10}{}{}
{11}{}{}
{12}{}{}
{13}{}{}
{14}{}{}
{15}{}{}
{16}{}{}
{17}{}{}
{18}{}{}
{19}{}{}
#
#????? ?????????? ?????? ????? ??????????
#
### {100}{}{What do you need?}
{100}{}{你需要什么？ -- What do you need?}
### {101}{}{I'm the detective-man! Investigating the case of a missing wrench!}
{101}{}{我是侦探！正在调查扳手丢失的案件！ -- I'm the detective-man! Investigating the case of a missing wrench!}
### {102}{}{I'm looking for a dad's wrench...}
{102}{}{我在找爸爸的扳手。。。 -- I'm looking for a dad's wrench...}
### {103}{}{Nothing, I'm just playing here.}
{103}{}{没什么，我只是在这里玩。 -- Nothing, I'm just playing here.}
### {110}{}{You are just a little boy. And your dad's wrench is in the drawer near my bed. Go, fetch it.}
{110}{}{你只是个小男孩。你爸爸的扳手在我床边的抽屉里。去拿。 -- You are just a little boy. And your dad's wrench is in the drawer near my bed. Go, fetch it.}
### {120}{}{Oh... It's in the drawer near my bed. Tell your dad I said thanks.}
{120}{}{哦它在我床边的抽屉里。告诉你爸爸我说了谢谢。 -- Oh... It's in the drawer near my bed. Tell your dad I said thanks.}
### {111}{}{Thanks for the tip!}
{111}{}{谢谢你的小费！ -- Thanks for the tip!}
### {112}{}{Okay, I will go get it, thank you.}
{112}{}{好的，我去拿，谢谢。 -- Okay, I will go get it, thank you.}
#
#????????? ????????? (????????????? ???????)
#
### {1000}{}{Hey, buddy!}
{1000}{}{嘿，伙计！ -- Hey, buddy!}
### {1001}{}{Hello! How are you doing?}
{1001}{}{你好你好吗？ -- Hello! How are you doing?}
### {1002}{}{Well, hello there!}
{1002}{}{你好！ -- Well, hello there!}
### {1003}{}{Hey, brother! How are you?}
{1003}{}{嘿，兄弟！你好吗 -- Hey, brother! How are you?}
### {1004}{}{I would gladly stop and chat... But let's do it some other time.}
{1004}{}{我很乐意停下来聊聊。。。但让我们改天再做吧。 -- I would gladly stop and chat... But let's do it some other time.}
### {1005}{}{So good to see you!}
{1005}{}{很高兴见到你！ -- So good to see you!}
### {1006}{}{Maybe wanna chat? Suit yourself.}
{1006}{}{也许想聊聊？随你便。 -- Maybe wanna chat? Suit yourself.}
### {1007}{}{Listen, I've stashed something for you. Okay, let's talk later.}
{1007}{}{听着，我给你藏了些东西。好的，我们稍后再谈。 -- Listen, I've stashed something for you. Okay, let's talk later.}
### {1008}{}{Come see me more often, okay?}
{1008}{}{多来看我，好吗？ -- Come see me more often, okay?}
### {1009}{}{Of course! Come back anytime!}
{1009}{}{当然随时回来！ -- Of course! Come back anytime!}
# ??????????? ?????????
### {1010}{}{Don't get in my way, I'm busy.}
{1010}{}{别挡我的路，我很忙。 -- Don't get in my way, I'm busy.}
### {1011}{}{Can't you see? I have no time to spare.}
{1011}{}{你看不见吗？我没有多余的时间。 -- Can't you see? I have no time to spare.}
### {1012}{}{Hey! I'm trying to make these damn mechanisms here to work again!}
{1012}{}{嘿我正试图让这些该死的机制再次发挥作用！ -- Hey! I'm trying to make these damn mechanisms here to work again!}
### {1013}{}{Listen, maybe not now? Good.}
{1013}{}{听着，也许现在不行？好的 -- Listen, maybe not now? Good.}
### {1014}{}{Instead of bugging me with questions, hand me over that wrench.}
{1014}{}{与其问我问题，不如把扳手递给我。 -- Instead of bugging me with questions, hand me over that wrench.}
### {1015}{}{Listen, don't touch me, let me rest a little.}
{1015}{}{听着，别碰我，让我休息一下。 -- Listen, don't touch me, let me rest a little.}
### {1016}{}{What do you want?}
{1016}{}{你想要什么？ -- What do you want?}
### {1017}{}{...And then I'm like - you are sparking here! Hilarious.}
{1017}{}{…然后我就想——你在这里闪闪发光！令人捧腹的 -- ...And then I'm like - you are sparking here! Hilarious.}
### {1018}{}{...And then he's like - that's E-LEC-TREE-SEE-TEE!}
{1018}{}{…然后他说——那是E-LEC-TREE-SEE-TEE！ -- ...And then he's like - that's E-LEC-TREE-SEE-TEE!}
### {1019}{}{Oh. Listen, let's talk a little later, okay?}
{1019}{}{哦听着，我们稍后再谈，好吗？ -- Oh. Listen, let's talk a little later, okay?}
# ????????????? ?????????
### {1020}{}{Get lost, dumbass!}
{1020}{}{迷路吧，蠢蛋！ -- Get lost, dumbass!}
### {1021}{}{Get the hell out!}
{1021}{}{滚出去！ -- Get the hell out!}
### {1022}{}{Better don't take your chances, you freak!}
{1022}{}{最好不要冒险，你这个怪胎！ -- Better don't take your chances, you freak!}
### {1023}{}{Screw you!!!}
{1023}{}{去你的！！！ -- Screw you!!!}
### {1024}{}{Make like a tree and get out of here.}
{1024}{}{像棵树一样，离开这里。 -- Make like a tree and get out of here.}
### {1025}{}{You're gonna get punched in the face if you don't get lost!}
{1025}{}{如果你不迷路，你会被打在脸上的！ -- You're gonna get punched in the face if you don't get lost!}
### {1026}{}{Make yourself invisible!}
{1026}{}{让自己隐形！ -- Make yourself invisible!}
### {1027}{}{What the heck do you want from me?!}
{1027}{}{你到底想从我这里得到什么？！ -- What the heck do you want from me?!}
### {1028}{}{How dare you?!}
{1028}{}{你怎么敢？！ -- How dare you?!}
### {1029}{}{You piss me off! Go away!}
{1029}{}{你惹我生气！走开！ -- You piss me off! Go away!}
#
#????????? ????????? (?????????????)
#
### {1030}{}{No, I won't fix anything!}
{1030}{}{不，我什么都不修！ -- No, I won't fix anything!}
### {1031}{}{Nah, let this water pump burn. I'll pass.}
{1031}{}{不，让这个水泵烧了。我会通过的。 -- Nah, let this water pump burn. I'll pass.}
### {1032}{}{Why are you bothering me? If you need it, you fix it!}
{1032}{}{你为什么打扰我？如果你需要它，你就把它修好！ -- Why are you bothering me? If you need it, you fix it!}
### {1033}{}{Get off me, I won't be fixing it.}
{1033}{}{放开我，我不会修的。 -- Get off me, I won't be fixing it.}
### {1034}{}{This junk breaks down all the time! I'm tired of it!}
{1034}{}{这些垃圾总是坏掉！我受够了！ -- This junk breaks down all the time! I'm tired of it!}
### {1035}{}{No, no and NO again!}
{1035}{}{不，不，再不！ -- No, no and NO again!}
### {1036}{}{I won't do it, stop trying.}
{1036}{}{我不会做的，别再尝试了。 -- I won't do it, stop trying.}
### {1037}{}{Oh, just leave me be.}
{1037}{}{哦，别管我了。 -- Oh, just leave me be.}
### {1038}{}{There are many mechanics here! Why should I fi it?!?}
{1038}{}{这里有很多机械师！我为什么要拍？！？ -- There are many mechanics here! Why should I fi it?!?}
### {1039}{}{[waves hand]}
{1039}{}{[挥手 -- waves hand]}
#
#???? ????????? - ?????? ????? ? ????? ????
#
### {1040}{}{Water Servant Brooke?}
{1040}{}{水仆布鲁克？ -- Water Servant Brooke?}
### {1041}{}{Huh? Um... Yes?}
{1041}{}{嗯？嗯…是吗？ -- Huh? Um... Yes?}
### {1042}{}{The time has come for you to serve the common good...}
{1042}{}{现在是你们为共同利益服务的时候了。。。 -- The time has come for you to serve the common good...}
### {1043}{}{...With your inaction and your laziness, you've put us all in great danger...}
{1043}{}{…你的不作为和懒惰使我们都处于极大的危险之中。。。 -- ...With your inaction and your laziness, you've put us all in great danger...}
### {1044}{}{...and Herald told us the will of the Gods...}
{1044}{}{…《先驱报》告诉我们上帝的意志。。。 -- ...and Herald told us the will of the Gods...}
### {1045}{}{You will be feed to the Mouth of Hades!}
{1045}{}{你会被喂到地狱之口！ -- You will be feed to the Mouth of Hades!}
### {1046}{}{Your flesh will be given to the soil...}
{1046}{}{你的肉体将被赋予土壤。。。 -- Your flesh will be given to the soil...}
### {1047}{}{...Which feeds us.}
{1047}{}{…这养活了我们。 -- ...Which feeds us.}
### {1048}{}{Hurry up, Servant!}
{1048}{}{快，仆人！ -- Hurry up, Servant!}
### {1049}{}{MOVE!}
{1049}{}{移动！ -- MOVE!}
