#############################################################
#????????? ???? ??? ???????? << ???? ??, 17 ??? >> 
#????? ?????? ? scripts.lst << ??? >>
#############################################################
#????????? ?????:
#?????? 1-9 - ???????? ?????????;
#?????? 10-29 - ?????????? ? ?????????;
#?????? 30-99 - ???? ?? ????, ?? ?????, ??? ??????????...
#?????, ?? ?????? ???????.
#?????? ????? ?????? 100, ?.?. 100 - ???? ???? ???????, 200 - ??????.
#??????? ????????? ???? ????? 10, ?.?. 100, 110, 120 ? ?.?. ??? ??? 
#??? ??????? 100 ???????????? Node010, ??? ??????? 240 - Node024.
#??? ??????? ?????? - ???????? ?????????, ?.?. ?? ??????? 650 ?????? ????? 651, 652, 653 ? ?.?. 
#??? ?????? ??????????? ???????????? ?????????????? ????? (????????, ??????? 360 ??????? ?? 3601 ? 3602,
#??? ?? ???????? ????????? Node, ?????? ?? ????? ? ??????? ????? - 361, 362 ? ?.?.)
#############################################################
#????? ??????????????? ??????? ?? ????????? ????????? ??????? ??????? ???????,
#??? ??? ???? ????? ????? ??????!!!
############################################################
#?????????? ??? "????? 2207", by Rainman, 06/11/2010
#############################################################
#
#???????? ????????
#
# ?? ??????????
#
### {1}{}{You see your dad.}
{1}{}{你看到你爸爸了。 -- You see your dad.}
### {2}{}{John, your father. Disheveled hair, pale face... You are used to seeing him like this.}
{2}{}{约翰，你爸爸。头发凌乱，脸色苍白。。。你已经习惯了看到他这样。 -- John, your father. Disheveled hair, pale face... You are used to seeing him like this.}
#
# ????? ??????????
#
### {3}{}{You see your dad.}
{3}{}{你看到你爸爸了。 -- You see your dad.}
### {4}{}{John, your father. Disheveled hair, pale face... You are used to seeing him like this.}
{4}{}{约翰，你爸爸。头发凌乱，脸色苍白。。。你已经习惯了看到他这样。 -- John, your father. Disheveled hair, pale face... You are used to seeing him like this.}
#
#????? ?????????? ?????? ?? ??????????
#
### {10}{}{Who're you?}
{10}{}{你是谁？ -- Who're you?}
### {11}{}{I'm a hero!}
{11}{}{我是英雄！ -- I'm a hero!}
{12}{}{}
{13}{}{}
{14}{}{}
{15}{}{}
{16}{}{}
{17}{}{}
{18}{}{}
{19}{}{}
#
#????? ?????????? ?????? ????? ??????????
#
### {100}{}{Son? What do you want? What are you doing here? Why aren't you doing your labor? [he frowns] You should immediately go to the Farms and ask Herald about daily duties.}
{100}{}{儿子你想要什么？你在这里干什么？你为什么不做你的劳动？[他皱着眉头]你应该立即去农场，询问《先驱报》的日常职责。 -- Son? What do you want? What are you doing here? Why aren't you doing your labor? [he frowns] You should immediately go to the Farms and ask Herald about daily duties.}
### {101}{}{Did you want to ask something? [he slightly raises his eyebrows]}
{101}{}{你想问什么吗？[他微微扬起眉毛] -- Did you want to ask something? [he slightly raises his eyebrows]}
### {102}{}{I was just going, dad. See, already did.}
{102}{}{我正要去，爸爸。看，已经做了。 -- I was just going, dad. See, already did.}
### {103}{}{Why aren't YOU doing the labor? You hang around here all the time!}
{103}{}{你为什么不去劳动？你一直在这里徘徊！ -- Why aren't YOU doing the labor? You hang around here all the time!}
### {104}{}{No, nothing to ask about.}
{104}{}{不，没什么好问的。 -- No, nothing to ask about.}
### {105}{}{Uhh... Nothing.}
{105}{}{嗯。。。没有什么 -- Uhh... Nothing.}
### {106}{}{I'm on a daily duty already. Herald tasked me with finding out why Lavash are getting sick... I don't even know where to start.}
{106}{}{我已经每天值班了。《先驱报》让我找出拉瓦什生病的原因。。。我甚至不知道从哪里开始。 -- I'm on a daily duty already. Herald tasked me with finding out why Lavash are getting sick... I don't even know where to start.}
### {110}{}{You know how it is - the head of each family looks after his corner. And our sink is leaking again. That damn sink!}
{110}{}{你知道这是怎么回事——每个家庭的负责人都会照顾自己的角落。我们的水槽又漏水了。那该死的水槽！ -- You know how it is - the head of each family looks after his corner. And our sink is leaking again. That damn sink!}
### {111}{}{Yes, I know this, but shouldn't you be on the Farm, working for mom?}
{111}{}{是的，我知道，但你不应该在农场为妈妈工作吗？ -- Yes, I know this, but shouldn't you be on the Farm, working for mom?}
### {112}{}{What would Herald say about it? He always complains about the lack of people on the Farms.}
{112}{}{《先驱报》对此会怎么说？他总是抱怨农场缺人。 -- What would Herald say about it? He always complains about the lack of people on the Farms.}
### {113}{}{I see. Well, off to do labor then.}
{113}{}{我明白了。好吧，那就去劳动吧。 -- I see. Well, off to do labor then.}
### {114}{}{Why didn't you save mom? You could have done something!}
{114}{}{你为什么不救妈妈？你本可以做点什么的！ -- Why didn't you save mom? You could have done something!}
### {115}{}{[dad closes eyes and covers his face with palm] Again? Why do you need to blame someone all the time? I can't protect anyone from sickness, even the loved ones. I just can't! Even Kirk understands. Maybe you need to accept it too.}
{115}{}{[爸爸闭上眼睛，用手掌捂住脸]又来了？为什么你需要一直责怪别人？我无法保护任何人不生病，即使是我所爱的人。我就是不能！就连柯克也明白。也许你也需要接受它。 -- [dad closes eyes and covers his face with palm] Again? Why do you need to blame someone all the time? I can't protect anyone from sickness, even the loved ones. I just can't! Even Kirk understands. Maybe you need to accept it too.}
### {116}{}{So, the Gods just took her? Her time has come, and that's it?}
{116}{}{那么，上帝刚刚带走了她？她的时代到了，就这样？ -- So, the Gods just took her? Her time has come, and that's it?}
### {117}{}{Yes, you'd better believe in that.}
{117}{}{是的，你最好相信这一点。 -- Yes, you'd better believe in that.}
### {118}{}{I'll try... And I need to go.}
{118}{}{我会试试。。。我得走了。 -- I'll try... And I need to go.}
### {119}{}{No way! It's somebody's fault! And one day this somebody's gonna pay! [leave]}
{119}{}{不可能！这是别人的错！总有一天会有人付钱的！[离开] -- No way! It's somebody's fault! And one day this somebody's gonna pay! [leave]}
### {1201}{}{Ohh... These farms led Elize to the Mouth of Hades, and they will do the same to me. I'm lucky Dr. Pat allows me to now overwork myself and to rest here often.}
{1201}{}{哦。。。这些农场把伊丽莎带到了地狱之口，他们也会对我这样做。我很幸运，帕特医生允许我现在过度劳累，经常在这里休息。 -- Ohh... These farms led Elize to the Mouth of Hades, and they will do the same to me. I'm lucky Dr. Pat allows me to now overwork myself and to rest here often.}
### {121}{}{I need to talk to Dr. Pat, maybe he could give me a day off too.}
{121}{}{我需要和帕特医生谈谈，也许他也可以给我放一天假。 -- I need to talk to Dr. Pat, maybe he could give me a day off too.}
### {122}{}{Mom... I miss her so much...}
{122}{}{妈妈我非常想念她。。。 -- Mom... I miss her so much...}
### {123}{}{You know, you're right. You need to rest.}
{123}{}{你知道，你是对的。你需要休息。 -- You know, you're right. You need to rest.}
### {1202}{}{Herald Gregorius knows and understands the problems of our people. Nothing bad comes out of me spending some time here.}
{1202}{}{先驱格雷戈里乌斯知道并理解我们人民的问题。我在这里呆了一段时间，没有什么不好的结果。 -- Herald Gregorius knows and understands the problems of our people. Nothing bad comes out of me spending some time here.}
### {124}{}{Damn! I have my problems too! It's not fair I have to work!}
{124}{}{该死我也有自己的问题！我必须工作，这不公平！ -- Damn! I have my problems too! It's not fair I have to work!}
### {125}{}{Well, if he is aware of that...}
{125}{}{如果他知道的话。。。 -- Well, if he is aware of that...}
### {126}{}{I see. Then I'll go do my labor.}
{126}{}{我明白了。那我就去做我的劳动。 -- I see. Then I'll go do my labor.}
### {130}{}{You know, you can actually try. Do you want my help? I could break your hand or something. [he gives you a weak smile]}
{130}{}{你知道，你可以尝试一下。你需要我的帮助吗？我可能会打断你的手什么的。[他对你报以微弱的微笑] -- You know, you can actually try. Do you want my help? I could break your hand or something. [he gives you a weak smile]}
### {131}{}{Uhh... You know, I'd better go do my work then.}
{131}{}{嗯。。。你知道，那我最好去做我的工作。 -- Uhh... You know, I'd better go do my work then.}
### {132}{}{Considering your condition, you are more likely to hurt yourself. Okay, I'll go do my labor. See you around.}
{132}{}{考虑到你的情况，你更有可能伤害自己。好的，我去做我的劳动。回头见。 -- Considering your condition, you are more likely to hurt yourself. Okay, I'll go do my labor. See you around.}
### {1401}{}{Son, uh, just look around. I don't know, I need to work.}
{1401}{}{儿子，呃，看看周围。我不知道，我需要工作。 -- Son, uh, just look around. I don't know, I need to work.}
### {1402}{}{Oh... Well, I would start by examining the Lavash, just to try to understand what's wrong with them. Then I'd talk to those who oversee them about what they eat and drink. And then I'd figured out the rest. Maybe the water is rotten? Then it's something with the water cleaning filters, I would look into that.}
{1402}{}{哦好吧，我会从检查熔岩开始，只是想了解它们到底出了什么问题。然后我会和那些监督他们的人谈谈他们的饮食。然后我就想明白了。也许水已经腐烂了？然后是水清洁过滤器的问题，我会研究一下。 -- Oh... Well, I would start by examining the Lavash, just to try to understand what's wrong with them. Then I'd talk to those who oversee them about what they eat and drink. And then I'd figured out the rest. Maybe the water is rotten? Then it's something with the water cleaning filters, I would look into that.}
### {141}{}{Well, thanks for nothing...}
{141}{}{好吧，谢谢你。。。 -- Well, thanks for nothing...}
### {142}{}{You know what, that's a great plan! Thanks!}
{142}{}{你知道吗，这是一个伟大的计划！谢谢 -- You know what, that's a great plan! Thanks!}
### {149}{}{Dad, do you know who is that big gloomy black man on the parking lot?}
{149}{}{爸爸，你知道停车场上那个灰蒙蒙的黑人是谁吗？ -- Dad, do you know who is that big gloomy black man on the parking lot?}
### {1501}{}{Huh. Big and gloomy, right?... You mean, Bardock? It must be him. I know him since childhood, he was always getting into all kinds of troubles. And then this alcohol habit... Don't take me wrong, he is alright, but still - you'd better stay away from him.}
{1501}{}{嗯。又大又悲观，对吧？。。。你是说，巴多克？一定是他。我从小就认识他，他总是惹上各种各样的麻烦。然后这个酗酒的习惯。。。别误会我，他很好，但你还是离他远点。 -- Huh. Big and gloomy, right?... You mean, Bardock? It must be him. I know him since childhood, he was always getting into all kinds of troubles. And then this alcohol habit... Don't take me wrong, he is alright, but still - you'd better stay away from him.}
### {1502}{}{Big and gloomy? No, I don't know. And, just to make sure - stop hanging around, you should be on the Farms, doing your labor.}
{1502}{}{又大又悲观？不，我不知道。而且，为了确保——不要再闲逛了，你应该在农场里，做你的劳动。 -- Big and gloomy? No, I don't know. And, just to make sure - stop hanging around, you should be on the Farms, doing your labor.}
### {151}{}{Oh! Okay... I'll keep that in mind.}
{151}{}{哦可以我会记住的。 -- Oh! Okay... I'll keep that in mind.}
### {152}{}{Yeah, sure. Thanks, dad.}
{152}{}{是的，当然。谢谢，爸爸。 -- Yeah, sure. Thanks, dad.}
#
#????????? ????????? (????????????? ???????)
#
{1000}{}{}
{1001}{}{}
{1002}{}{}
{1003}{}{}
{1004}{}{}
{1005}{}{}
{1006}{}{}
{1007}{}{}
{1008}{}{}
{1009}{}{}
#
#????????? ????????? (??????????? ???????)
#
{1010}{}{}
{1011}{}{}
{1012}{}{}
{1013}{}{}
{1014}{}{}
{1015}{}{}
{1016}{}{}
{1017}{}{}
{1018}{}{}
{1019}{}{}
#
#????????? ????????? (????????????? ???????)
#
{1020}{}{}
{1021}{}{}
{1022}{}{}
{1023}{}{}
{1024}{}{}
{1025}{}{}
{1026}{}{}
{1027}{}{}
{1028}{}{}
{1029}{}{}
#
#????????? ????????? (?????????????)
#
{1030}{}{}
{1031}{}{}
{1032}{}{}
{1033}{}{}
{1034}{}{}
{1035}{}{}
{1036}{}{}
{1037}{}{}
{1038}{}{}
{1039}{}{}
