#############################################################
#????????? ???? ??? ???????? << ??? >> 
#????? ?????? ? scripts.lst << ??? >>
#############################################################
#????????? ?????:
#?????? 1-9 - ???????? ?????????;
#?????? 10-29 - ?????????? ? ?????????;
#?????? 30-99 - ???? ?? ????, ?? ?????, ??? ??????????...
#?????, ?? ?????? ???????.
#?????? ????? ?????? 100, ?.?. 100 - ???? ???? ???????, 200 - ??????.
#??????? ????????? ???? ????? 10, ?.?. 100, 110, 120 ? ?.?. ??? ??? 
#??? ??????? 100 ???????????? Node010, ??? ??????? 240 - Node024.
#??? ??????? ?????? - ???????? ?????????, ?.?. ?? ??????? 650 ?????? ????? 651, 652, 653 ? ?.?. 
#??? ?????? ??????????? ???????????? ?????????????? ????? (????????, ??????? 360 ??????? ?? 3601 ? 3602,
#??? ?? ???????? ????????? Node, ?????? ?? ????? ? ??????? ????? - 361, 362 ? ?.?.)
#############################################################
#????? ??????????????? ??????? ?? ????????? ????????? ??????? ??????? ???????,
#??? ??? ???? ????? ????? ??????!!!
############################################################
#?????????? ??? "????? 2207", by Rainman, 06/11/2010
#############################################################
#
#???????? ????????
#
# ?? ??????????
#
### {1}{}{You see Smitty.}
{1}{}{你看到史密蒂了。 -- You see Smitty.}
### {2}{}{A good old Smitty, your technological mentor, and teacher.}
{2}{}{一个好的老史密蒂，你的技术导师和老师。 -- A good old Smitty, your technological mentor, and teacher.}
#
# ????? ??????????
#
### {3}{}{You see Smitty.}
{3}{}{你看到史密蒂了。 -- You see Smitty.}
### {4}{}{A good old Smitty, your technological mentor, and teacher.}
{4}{}{一个好的老史密蒂，你的技术导师和老师。 -- A good old Smitty, your technological mentor, and teacher.}
#
#????? ?????????? ?????? ?? ??????????
#
### {10}{}{Who're yew?}
{10}{}{紫杉是谁？ -- Who're yew?}
### {11}{}{Ima hero!}
{11}{}{伊玛英雄！ -- Ima hero!}
{12}{}{}
{13}{}{}
{14}{}{}
{15}{}{}
{16}{}{}
{17}{}{}
{18}{}{}
{19}{}{}
#
#????? ?????????? ?????? ????? ??????????
#
### {100}{}{H-hey! [he coughs] Isn't that John's boy! What brings you here?}
{100}{}{嘿！[他咳嗽]那不是约翰的孩子吗！什么风把你吹到这儿来？ -- H-hey! [he coughs] Isn't that John's boy! What brings you here?}
### {101}{}{So, young man, what do you need?}
{101}{}{那么，年轻人，你需要什么？ -- So, young man, what do you need?}
### {102}{}{Hey, Smitty- oh man, you reek with booze! I'll come to you later.}
{102}{}{嘿，Smitty——哦，伙计，你浑身是酒臭味！我稍后再来找你。 -- Hey, Smitty- oh man, you reek with booze! I'll come to you later.}
### {103}{}{I'm fine. And I'll be back later.}
{103}{}{我很好。我稍后会回来。 -- I'm fine. And I'll be back later.}
### {104}{}{Nothing for now. See you, Smitty!}
{104}{}{暂时没有。再见，史密蒂！ -- Nothing for now. See you, Smitty!}
### {105}{}{Uhh... Nothing. Bye, Smitty!}
{105}{}{嗯。。。没有什么再见，史密蒂！ -- Uhh... Nothing. Bye, Smitty!}
### {106}{}{I could really use your advice, Smitty.}
{106}{}{我真的可以听从你的建议，史密蒂。 -- I could really use your advice, Smitty.}
### {107}{}{Listen, Smitty, do you have an empty bottle to spare, by any chance? I know you - you always have one! And I really need it.}
{107}{}{听着，史密蒂，你有空瓶子吗？我了解你——你总是有一个！我真的很需要它。 -- Listen, Smitty, do you have an empty bottle to spare, by any chance? I know you - you always have one! And I really need it.}
### {108}{}{I did it. I put an assembled filter into the machine. The bottle, please.}
{108}{}{我做到了。我把一个组装好的过滤器放进机器里。请给我瓶子。 -- I did it. I put an assembled filter into the machine. The bottle, please.}
### {110}{}{Sure! What are you having troubles fixing again?}
{110}{}{当然你又在修什么毛病？ -- Sure! What are you having troubles fixing again?}
### {111}{}{Actually, I can fix anything. Even something that is not broken yet. See you!}
{111}{}{事实上，我可以解决任何问题。即使是还没有坏的东西。再见 -- Actually, I can fix anything. Even something that is not broken yet. See you!}
### {112}{}{A fuse box on the second level.}
{112}{}{第二层的保险丝盒。 -- A fuse box on the second level.}
### {113}{}{Don't make it look like you don't know! You have a faulty water filtering machine right beside you!}
{113}{}{不要让它看起来像你不知道！你身边有一台有故障的滤水机！ -- Don't make it look like you don't know! You have a faulty water filtering machine right beside you!}
### {114}{}{I've been trying to assemble this stupid thing for a water filtering machine, but I just can't. Maybe you could do it? And I'll go and put it in.}
{114}{}{我一直想把这个愚蠢的东西组装成一台滤水机，但我就是做不到。也许你能做到？我去把它放进去。 -- I've been trying to assemble this stupid thing for a water filtering machine, but I just can't. Maybe you could do it? And I'll go and put it in.}
### {120}{}{Just don't put your fingers under the current! Examine the fuse box, study it closely. Find out which wires are sparky, connect them better. Or just try to trust your repairing skills - close your eyes and let the hands do the work. Maybe it would do it. It's easy, you'll see.}
{120}{}{只是不要把你的手指放在水流下！检查保险丝盒，仔细研究。找出哪根电线闪闪发光，把它们连接得更好。或者试着相信你的修复技巧——闭上眼睛，让手来完成工作。也许它能做到。这很容易，你会看到的。 -- Just don't put your fingers under the current! Examine the fuse box, study it closely. Find out which wires are sparky, connect them better. Or just try to trust your repairing skills - close your eyes and let the hands do the work. Maybe it would do it. It's easy, you'll see.}
### {121}{}{If it's easy, you could go and fix it. To show me how it's done, so to say.}
{121}{}{如果很容易的话，你可以去修理它。可以这么说，是为了向我展示它是如何做到的。 -- If it's easy, you could go and fix it. To show me how it's done, so to say.}
### {122}{}{Yeah, I get it, but it spikes me with electricity all the time! Okay, I'll go try again.}
{122}{}{是的，我明白了，但它一直给我通电！好的，我再试试。 -- Yeah, I get it, but it spikes me with electricity all the time! Okay, I'll go try again.}
### {123}{}{Oh, you actually don't know anything helpful.}
{123}{}{哦，你其实不知道什么有用的。 -- Oh, you actually don't know anything helpful.}
### {1301}{}{You know, maybe that's exactly what I'm gonna do! You are too crooked-handed anyway.}
{1301}{}{你知道，也许这正是我要做的！不管怎样，你的手腕太弯曲了。 -- You know, maybe that's exactly what I'm gonna do! You are too crooked-handed anyway.}
### {131}{}{Okay, go on, I'll wait for you right here.}
{131}{}{好的，继续，我在这里等你。 -- Okay, go on, I'll wait for you right here.}
### {132}{}{Don't sweat it, I'll do the job myself.}
{132}{}{别担心，我会自己做的。 -- Don't sweat it, I'll do the job myself.}
### {133}{}{No need. Can I ask another question?}
{133}{}{没有必要。我可以再问一个问题吗？ -- No need. Can I ask another question?}
### {1302}{}{Hey, I'm not your errand boy! I'm not gonna run around the levels, handle it yourself!}
{1302}{}{嘿，我不是你的跑腿的！我不会到处乱跑的，你自己处理吧！ -- Hey, I'm not your errand boy! I'm not gonna run around the levels, handle it yourself!}
### {134}{}{Pfft, I will! Suit yourself.}
{134}{}{普夫特，我会的！随你便。 -- Pfft, I will! Suit yourself.}
### {135}{}{I never had any doubts about you. Okay, I'll figure it out, bye!}
{135}{}{我从来没有怀疑过你。好的，我会解决的，再见！ -- I never had any doubts about you. Okay, I'll figure it out, bye!}
### {136}{}{Okay, no problem. Another question then?}
{136}{}{好的，没问题。那又是一个问题吗？ -- Okay, no problem. Another question then?}
### {140}{}{There, all done! The lights are good. No sparks and no flickering.}
{140}{}{完成了！灯光很好。没有火花，没有闪烁。 -- There, all done! The lights are good. No sparks and no flickering.}
### {141}{}{Thanks, Smitty! I owe you one!}
{141}{}{谢谢，史密蒂！我欠你一个！ -- Thanks, Smitty! I owe you one!}
### {142}{}{I could handle it eventually - but thanks anyway.}
{142}{}{我最终可以应付，但无论如何还是要感谢。 -- I could handle it eventually - but thanks anyway.}
### {150}{}{Do you think I don't know?! It doesn't work for two weeks already, the whole node went out, the filter itself! And I know how to fix it, no problem, but I need a bracket and a valve, and I'm too tired to run around Tartarus for them. Here, take the filter. If you wanna help, you can search for a valve in old cars, just look around a parking lot. As for the bracket - I heard the boys from the Residential level played with it recently.}
{150}{}{你以为我不知道吗？！它已经两周不工作了，整个节点都坏了，过滤器本身也坏了！我知道如何修复它，没问题，但我需要一个支架和一个阀门，我太累了，不能在塔尔塔罗斯到处跑。给，拿着过滤器。如果你想帮忙，你可以在旧车里找一个阀门，只要看看停车场就可以了。至于支架，我听说最近寄宿级别的男孩们玩过它。 -- Do you think I don't know?! It doesn't work for two weeks already, the whole node went out, the filter itself! And I know how to fix it, no problem, but I need a bracket and a valve, and I'm too tired to run around Tartarus for them. Here, take the filter. If you wanna help, you can search for a valve in old cars, just look around a parking lot. As for the bracket - I heard the boys from the Residential level played with it recently.}
### {151}{}{Oh my, it's so confusing! And what would I do with all this stuff?}
{151}{}{天哪，太让人困惑了！我该怎么处理这些东西呢？ -- Oh my, it's so confusing! And what would I do with all this stuff?}
### {152}{}{Why should I do all the work?! Although, what choice do I have... Give me that.}
{152}{}{为什么我要做所有的工作？！尽管如此，我还有什么选择。。。给我这个。 -- Why should I do all the work?! Although, what choice do I have... Give me that.}
### {160}{}{When you find the details, just put everything together - and you'll get a working node! Then you need to install it into the machine, and that's it! Easy!}
{160}{}{当你找到细节时，只要把所有东西放在一起——你就会得到一个工作节点！然后你需要把它安装到机器里，就这样！容易的 -- When you find the details, just put everything together - and you'll get a working node! Then you need to install it into the machine, and that's it! Easy!}
### {161}{}{I figured as much... Okay, I'm off to look for the parts.}
{161}{}{我也这么想。。。好的，我去找零件。 -- I figured as much... Okay, I'm off to look for the parts.}
### {162}{}{I see... Thanks for the instruction, I'll go to search.}
{162}{}{我明白了。。。谢谢你的指示，我去搜索。 -- I see... Thanks for the instruction, I'll go to search.}
### {170}{}{Hah! Aren't you a sly dog? You do know that there are almost no bottles left, and yet you are still asking! You know what? I can give you a bottle. For a little favor.}
{170}{}{哈哈！你不是一只狡猾的狗吗？你知道几乎没有瓶子了，但你仍然在问！你知道吗？我可以给你一瓶。为了一个小小的帮助。 -- Hah! Aren't you a sly dog? You do know that there are almost no bottles left, and yet you are still asking! You know what? I can give you a bottle. For a little favor.}
### {171}{}{Who could doubt that. Tell me about this "favor".}
{171}{}{谁会怀疑呢。告诉我这个“人情”。 -- Who could doubt that. Tell me about this "favor".}
### {172}{}{I don't need it right now. I want to ask something.}
{172}{}{我现在不需要它。我想问个问题。 -- I don't need it right now. I want to ask something.}
### {180}{}{Do you know about my Moonshine Machina Magnifico? That one, in the utility room? If you only knew how much soul and love I've put into it... [he wistfully rolls his eyes] But here's the problem - it eats up a lot of candies, and we don't have many of these around. So, I decided to make a few improvements and came up with a double-partition candy filter. Here's the filter grid, and here's the special pallet with a gutter. All is needed to do is to put the filter into the gutter, but my hands are so shaky today, you wouldn't believe it! So, assemble the filter and install it into my machine, and I will give you the bottle. I mean, lend you the bottle. Give it back to me when you're done, okay?}
{180}{}{你知道我的月光町吗？在杂物间的那个？如果你知道我在其中投入了多少灵魂和爱……（他渴望地翻白眼）但问题是——它会吃掉很多糖果，而我们身边没有很多。所以，我决定做一些改进，并提出了一个双分区糖果过滤器。这是过滤网，这是带排水沟的特殊托盘。所需要做的就是把过滤器放进排水沟，但我今天的手太颤抖了，你不会相信的！所以，组装好过滤器，安装到我的机器上，我会把瓶子给你。我的意思是，把瓶子借给你。做完后还给我，好吗？ -- Do you know about my Moonshine Machina Magnifico? That one, in the utility room? If you only knew how much soul and love I've put into it... [he wistfully rolls his eyes] But here's the problem - it eats up a lot of candies, and we don't have many of these around. So, I decided to make a few improvements and came up with a double-partition candy filter. Here's the filter grid, and here's the special pallet with a gutter. All is needed to do is to put the filter into the gutter, but my hands are so shaky today, you wouldn't believe it! So, assemble the filter and install it into my machine, and I will give you the bottle. I mean, lend you the bottle. Give it back to me when you're done, okay?}
### {181}{}{Okay, okay, give me the parts. Get the bottle ready, I'll be right back.}
{181}{}{好吧，好吧，把零件给我。把瓶子准备好，我马上回来。 -- Okay, okay, give me the parts. Get the bottle ready, I'll be right back.}
### {182}{}{As if I have nothing better to do! You invented it - you handle it! Bye, cheapskate.}
{182}{}{好像我没有更好的事情可做似的！你发明了它——你掌握了它！再见，吝啬鬼。 -- As if I have nothing better to do! You invented it - you handle it! Bye, cheapskate.}
### {190}{}{What a skillful man you are! Just kidding, even a baby could assemble it. [he laughs] But I keep my word, here's the bottle. Don't drop it!}
{190}{}{你是一个多么熟练的人！只是开玩笑，即使是婴儿也能组装它。（他笑着说）但我信守诺言，这是瓶子。别扔了！ -- What a skillful man you are! Just kidding, even a baby could assemble it. [he laughs] But I keep my word, here's the bottle. Don't drop it!}
### {191}{}{Come on, you old kidder... [take a bottle] Okay, I'll go put it to use.}
{191}{}{来吧，你这个老顽童。。。[拿一瓶]好的，我去用它。 -- Come on, you old kidder... [take a bottle] Okay, I'll go put it to use.}
### {2001}{}{[scratches his head] Well, you can't do much without a bottle here... No, you definitely can't. If you know what I mean.}
{2001}{}{[挠了挠他的头]好吧，这里没有瓶子你做不了什么。。。不，你绝对不能。如果你知道我的意思。 -- [scratches his head] Well, you can't do much without a bottle here... No, you definitely can't. If you know what I mean.}
### {2002}{}{Find the parts first! Do you expect me to run around and search for them? I'm not so young, you see.}
{2002}{}{先找到零件！你希望我到处跑去找他们吗？你看，我不那么年轻了。 -- Find the parts first! Do you expect me to run around and search for them? I'm not so young, you see.}
### {201}{}{Smitty, I know you! You are the real professional! And professionals are doing a good job in any condition!}
{201}{}{史密蒂，我认识你！你才是真正的专业人士！专业人士在任何情况下都做得很好！ -- Smitty, I know you! You are the real professional! And professionals are doing a good job in any condition!}
### {202}{}{A bottle of booze? I suppose there's a bottle needed for it, and I gave it to a guard... Be back soon.}
{202}{}{一瓶酒？我想这需要一个瓶子，我把它交给了一个警卫。。。很快回来。 -- A bottle of booze? I suppose there's a bottle needed for it, and I gave it to a guard... Be back soon.}
### {203}{}{Okay, okay, I'll go look for parts.}
{203}{}{好吧，好吧，我去找零件。 -- Okay, okay, I'll go look for parts.}
### {204}{}{Here's your favorite drink. [hand him the bottle] I've spent all my candies on this.}
{204}{}{这是你最喜欢的饮料。[把瓶子递给他]我把所有的糖果都花在这上面了。 -- Here's your favorite drink. [hand him the bottle] I've spent all my candies on this.}
### {2101}{}{A sweet talker, I see! Alright then, give me the parts. [he takes three details from you - and in a second gives you back an assembled node] Yeah, kid, you have a lot to learn!}
{2101}{}{一个甜言蜜语的人，我明白了！好吧，给我零件。[他从你那里得到了三个细节——一秒钟后还给你一个组装好的节点]是的，孩子，你有很多东西要学！ -- A sweet talker, I see! Alright then, give me the parts. [he takes three details from you - and in a second gives you back an assembled node] Yeah, kid, you have a lot to learn!}
### {2102}{}{No, that's not how it works! Do you see how shaky my hands are? You can't do much without the medicine here. Or come later, maybe I'll feel better, or be in a better mood...}
{2102}{}{不，这不是怎么回事！你看到我的手有多颤抖吗？没有这里的药你不能做什么。或者晚一点来，也许我会感觉更好，或者心情更好。。。 -- No, that's not how it works! Do you see how shaky my hands are? You can't do much without the medicine here. Or come later, maybe I'll feel better, or be in a better mood...}
### {211}{}{It's okay, all comes with experience. I'll go insert the node into a machine.}
{211}{}{没关系，一切都有经验。我去把节点插入机器。 -- It's okay, all comes with experience. I'll go insert the node into a machine.}
### {212}{}{[grit your teeth and go look for booze to give Smitty]}
{212}{}{[咬紧牙关去找酒给Smitty -- grit your teeth and go look for booze to give Smitty]}
### {220}{}{Alright then, give me the parts. [he takes three details from you - and in a second gives you back an assembled node] Yeah, kid, you have a lot to learn!}
{220}{}{好吧，给我零件。[他从你那里得到了三个细节——一秒钟后还给你一个组装好的节点]是的，孩子，你有很多东西要学！ -- Alright then, give me the parts. [he takes three details from you - and in a second gives you back an assembled node] Yeah, kid, you have a lot to learn!}
### {221}{}{It's okay, all comes with experience. I'll go insert the node into a machine.}
{221}{}{没关系，一切都有经验。我去把节点插入机器。 -- It's okay, all comes with experience. I'll go insert the node into a machine.}
#
#????????? ????????? (????????????? ???????)
#
{1000}{}{}
{1001}{}{}
{1002}{}{}
{1003}{}{}
{1004}{}{}
{1005}{}{}
{1006}{}{}
{1007}{}{}
{1008}{}{}
{1009}{}{}
#
#????????? ????????? (??????????? ???????)
#
{1010}{}{}
{1011}{}{}
{1012}{}{}
{1013}{}{}
{1014}{}{}
{1015}{}{}
{1016}{}{}
{1017}{}{}
{1018}{}{}
{1019}{}{}
#
#????????? ????????? (????????????? ???????)
#
{1020}{}{}
{1021}{}{}
{1022}{}{}
{1023}{}{}
{1024}{}{}
{1025}{}{}
{1026}{}{}
{1027}{}{}
{1028}{}{}
{1029}{}{}
#
#????????? ????????? (?????????????)
#
### {1030}{}{Alright, let's put this thingie here...}
{1030}{}{好吧，让我们把这个东西放在这里。。。 -- Alright, let's put this thingie here...}
### {1031}{}{This thing into that thing, aaand... Damn it!}
{1031}{}{这个东西变成那个东西，啊。。。该死！ -- This thing into that thing, aaand... Damn it!}
### {1032}{}{Wires, cords... And nothing works.}
{1032}{}{电线、电线。。。什么都不管用。 -- Wires, cords... And nothing works.}
### {1033}{}{Oh! My favorite screws...}
{1033}{}{哦我最喜欢的螺丝。。。 -- Oh! My favorite screws...}
### {1034}{}{My hands are so shaky...}
{1034}{}{我的手太颤抖了。。。 -- My hands are so shaky...}
### {1035}{}{I definitely need a drink!}
{1035}{}{我绝对需要喝一杯！ -- I definitely need a drink!}
### {1036}{}{Yeah, that's a pretty bad case of hand-crookery...}
{1036}{}{是的，这是一个非常糟糕的骗术案例。。。 -- Yeah, that's a pretty bad case of hand-crookery...}
### {1037}{}{It's alright, we're gonna patch you up.}
{1037}{}{没关系，我们会给你包扎的。 -- It's alright, we're gonna patch you up.}
### {1038}{}{May it burn in hell!}
{1038}{}{愿它在地狱里燃烧！ -- May it burn in hell!}
### {1039}{}{[rummages through some mechanism]}
{1039}{}{[翻找某种机制 -- rummages through some mechanism]}
