#############################################################
#????????? ???? ??? ???????? << ????????? ???????? ??? >> 
#############################################################
#????????? ?????:
#?????? 1-9 - ???????? ?????????;
#?????? 10-29 - ?????????? ? ?????????;
#?????? 30-99 - ???? ?? ????, ?? ?????, ??? ??????????...
#?????, ?? ?????? ???????.
#?????? ????? ?????? 100, ?.?. 100 - ???? ???? ???????, 200 - ??????.
#??????? ????????? ???? ????? 10, ?.?. 100, 110, 120 ? ?.?. ??? ??? 
#??? ??????? 100 ???????????? Node010, ??? ??????? 240 - Node024.
#??? ??????? ?????? - ???????? ?????????, ?.?. ?? ??????? 650 ?????? ????? 651, 652, 653 ? ?.?. 
#??? ?????? ??????????? ???????????? ?????????????? ????? (????????, ??????? 360 ??????? ?? 3601 ? 3602,
#??? ?? ???????? ????????? Node, ?????? ?? ????? ? ??????? ????? - 361, 362 ? ?.?.)
#############################################################
#????? ??????????????? ??????? ?? ????????? ????????? ??????? ??????? ???????,
#??? ??? ???? ????? ????? ??????!!!
############################################################
#?????????? ??? "????? 2207", by Rainman, 06/11/2010
#############################################################
#
#???????? ????????
#
### {1}{}{You see a trader.}
{1}{}{你看到一个交易员。 -- You see a trader.}
### {2}{}{You see a junk dealer.}
{2}{}{你看到一个垃圾贩子。 -- You see a junk dealer.}
### {3}{}{You see a merchant.}
{3}{}{你看到一个商人。 -- You see a merchant.}
### {4}{}{You see a merchant from NWO.}
{4}{}{你看到一个来自NWO的商人。 -- You see a merchant from NWO.}
### {5}{}{You see a vendor.}
{5}{}{你看到一个供应商。 -- You see a vendor.}
### {6}{}{This merchant is pretty unremarkable. Unlike the guards who stand behind him.}
{6}{}{这个商人并不起眼。不像站在他身后的警卫。 -- This merchant is pretty unremarkable. Unlike the guards who stand behind him.}
### {7}{}{Just a trader who sells all kinds of stuff.}
{7}{}{只是一个卖各种东西的商人。 -- Just a trader who sells all kinds of stuff.}
### {8}{}{He is one of the caravan merchants from NWO.}
{8}{}{他是来自西北大西洋的商队商人之一。 -- He is one of the caravan merchants from NWO.}
### {9}{}{He looks at you with such stare that you feel obliged to buy something from him.}
{9}{}{他瞪大眼睛看着你，你觉得有必要从他那里买点东西。 -- He looks at you with such stare that you feel obliged to buy something from him.}
#
#????? ?????????? ??????
#
### {10}{}{Of course, I don't have many rarities, but I assure you - you won't be disappointed!}
{10}{}{当然，我没有太多稀有的东西，但我向你保证——你不会失望的！ -- Of course, I don't have many rarities, but I assure you - you won't be disappointed!}
### {11}{}{Don't forget to check out our custom-made ammo, forged by the finest craftsmen from all corners of the Radius!}
{11}{}{别忘了看看我们定制的弹药，由来自Radius各个角落的最优秀的工匠锻造而成！ -- Don't forget to check out our custom-made ammo, forged by the finest craftsmen from all corners of the Radius!}
### {12}{}{Oh! I recognize you as a person who could appreciate little useful things - which, I'm telling you, I have enough!}
{12}{}{哦我认为你是一个能够欣赏小有用东西的人——我告诉你，我已经受够了！ -- Oh! I recognize you as a person who could appreciate little useful things - which, I'm telling you, I have enough!}
### {13}{}{Okay, let's see what you have.}
{13}{}{好的，让我们看看你有什么。 -- Okay, let's see what you have.}
### {14}{}{Let's look at your stock.}
{14}{}{让我们看看你的股票。 -- Let's look at your stock.}
### {15}{}{Yes, I might need to buy something. Show me your goods.}
{15}{}{是的，我可能需要买点东西。让我看看你的商品。 -- Yes, I might need to buy something. Show me your goods.}
### {16}{}{No, thank you. I don't need anything.}
{16}{}{不用了，谢谢。我什么都不需要。 -- No, thank you. I don't need anything.}
### {17}{}{No, I really need to go.}
{17}{}{不，我真的得走了。 -- No, I really need to go.}
### {18}{}{Maybe some other time. See you around.}
{18}{}{也许改天吧。回头见。 -- Maybe some other time. See you around.}
{19}{}{}
### {20}{}{H-hey! Don't come any closer!}
{20}{}{嘿！别再靠近了！ -- H-hey! Don't come any closer!}
### {21}{}{You aren't thinking of rifling through my pockets, are you?}
{21}{}{你没有想过要洗劫我的口袋，是吗？ -- You aren't thinking of rifling through my pockets, are you?}
### {22}{}{Better keep your distance, don't provoke my guards.}
{22}{}{最好保持距离，不要惹我的警卫。 -- Better keep your distance, don't provoke my guards.}
### {23}{}{Step away, for your own safety.}
{23}{}{走开，为了你自己的安全。 -- Step away, for your own safety.}
### {24}{}{No need to come so close, my friends here have itchy trigger fingers.}
{24}{}{没必要这么近，我在这里的朋友们都有发痒的扳机指。 -- No need to come so close, my friends here have itchy trigger fingers.}
### {25}{}{Touching me you risk an awful lot, pal!}
{25}{}{碰了我，你冒了很大的风险，朋友！ -- Touching me you risk an awful lot, pal!}
### {26}{}{Keep your hands to yourself, boy!}
{26}{}{把手放在自己身上，孩子！ -- Keep your hands to yourself, boy!}
### {27}{}{Hands off, quick!}
{27}{}{把手放开，快！ -- Hands off, quick!}
### {28}{}{Next time you'll have your hands ripped off.}
{28}{}{下次你的手会被扯下来。 -- Next time you'll have your hands ripped off.}
### {29}{}{Last warning - keep your hands where I can see them.}
{29}{}{最后一个警告——把手放在我能看到的地方。 -- Last warning - keep your hands where I can see them.}
{30}{}{}
{31}{}{}
{32}{}{}
{33}{}{}
{34}{}{}
{35}{}{}
#
#????????? ?????????
# ????????????? ?????????
### {1000}{}{Don't interrupt me, I'm busy.}
{1000}{}{别打扰我，我很忙。 -- Don't interrupt me, I'm busy.}
### {1001}{}{Can't you see I'm busy?}
{1001}{}{你看不出我很忙吗？ -- Can't you see I'm busy?}
### {1002}{}{Not now.}
{1002}{}{现在不行。 -- Not now.}
### {1003}{}{Huh?}
{1003}{}{嗯？ -- Huh?}
### {1004}{}{Just go away.}
{1004}{}{走开。 -- Just go away.}
### {1005}{}{Don't bother me, I need to rest...}
{1005}{}{别打扰我，我需要休息。。。 -- Don't bother me, I need to rest...}
### {1006}{}{What do you need?}
{1006}{}{你需要什么？ -- What do you need?}
### {1007}{}{[grins]}
{1007}{}{[咧嘴笑 -- grins]}
### {1008}{}{Leave me be, I have work to do.}
{1008}{}{别管我，我还有工作要做。 -- Leave me be, I have work to do.}
### {1009}{}{Yeah-yeah, you're good and all.}
{1009}{}{是的，是的，你很好。 -- Yeah-yeah, you're good and all.}
# ??????????? ?????????
### {1010}{}{Don't interrupt me, I'm busy.}
{1010}{}{别打扰我，我很忙。 -- Don't interrupt me, I'm busy.}
### {1011}{}{Can't you see I'm busy?}
{1011}{}{你看不出我很忙吗？ -- Can't you see I'm busy?}
### {1012}{}{Not now!}
{1012}{}{现在不行！ -- Not now!}
### {1013}{}{Just go away.}
{1013}{}{走开。 -- Just go away.}
### {1014}{}{Just turn around and walk away!}
{1014}{}{转身走开！ -- Just turn around and walk away!}
### {1015}{}{Don't bother me, I need to rest...}
{1015}{}{别打扰我，我需要休息。。。 -- Don't bother me, I need to rest...}
### {1016}{}{What do you need?}
{1016}{}{你需要什么？ -- What do you need?}
### {1017}{}{...All sorts of scum walking around...}
{1017}{}{…到处都是渣滓。。。 -- ...All sorts of scum walking around...}
### {1018}{}{Leave me be, I have a work to do!}
{1018}{}{别管我，我还有工作要做！ -- Leave me be, I have a work to do!}
### {1019}{}{Get lost!}
{1019}{}{迷路 -- Get lost!}
# ????????????? ?????????
### {1020}{}{Get lost, you piece of shit!}
{1020}{}{迷路吧，你这个混蛋！ -- Get lost, you piece of shit!}
### {1021}{}{Get the fuck out!}
{1021}{}{滚出去！ -- Get the fuck out!}
### {1022}{}{Better keep away from me, you freak!}
{1022}{}{最好离我远点，你这个怪胎！ -- Better keep away from me, you freak!}
### {1023}{}{Get out!!!}
{1023}{}{滚出去！！！ -- Get out!!!}
### {1024}{}{I'm gonna fuck you up!}
{1024}{}{我要搞砸你！ -- I'm gonna fuck you up!}
### {1025}{}{Want me to punch you in the face?!}
{1025}{}{想让我打你的脸吗？！ -- Want me to punch you in the face?!}
### {1026}{}{Get out of my sight!}
{1026}{}{滚出我的视线！ -- Get out of my sight!}
### {1027}{}{What the fuck do you want?!}
{1027}{}{你他妈的想要什么？！ -- What the fuck do you want?!}
### {1028}{}{Piece of shit!}
{1028}{}{糟透了！ -- Piece of shit!}
### {1029}{}{You motherfucker, get lost!}
{1029}{}{你这个混蛋，滚吧！ -- You motherfucker, get lost!}
#???? ????? ???????
### {1030}{}{Not now, I'm busy.}
{1030}{}{现在不行，我很忙。 -- Not now, I'm busy.}
### {1031}{}{Just wait one minute!}
{1031}{}{等一下！ -- Just wait one minute!}
### {1032}{}{Fuck! I'll be right back!}
{1032}{}{操！我马上回来！ -- Fuck! I'll be right back!}
{1033}{}{}
{1034}{}{}
{1035}{}{}
{1036}{}{}
{1037}{}{}
{1038}{}{}
{1039}{}{}
# ????????????? ?????????
### {1040}{}{Keep your hands to yourself, shmuck!}
{1040}{}{把手放在自己身上，笨蛋！ -- Keep your hands to yourself, shmuck!}
### {1041}{}{Hey! Keep your hands away from my pockets!}
{1041}{}{嘿把手从我的口袋里拿开！ -- Hey! Keep your hands away from my pockets!}
### {1042}{}{You are pushing ME around!?}
{1042}{}{你在逼我！？ -- You are pushing ME around!?}
### {1043}{}{Do this one more time and I will bury you!}
{1043}{}{再这样做一次，我就把你埋了！ -- Do this one more time and I will bury you!}
### {1044}{}{Oh, get the fuck out!}
{1044}{}{哦，滚出去！ -- Oh, get the fuck out!}
### {1045}{}{Do I bother you? Because I don't give a shit!}
{1045}{}{我打扰你了吗？因为我一点也不在乎！ -- Do I bother you? Because I don't give a shit!}
### {1046}{}{Better don't piss me off.}
{1046}{}{最好别惹我生气。 -- Better don't piss me off.}
### {1047}{}{I'm going to shove these hands of yours so deep into your ass!}
{1047}{}{我要把你的双手深深地塞进你屁股里！ -- I'm going to shove these hands of yours so deep into your ass!}
### {1048}{}{Wanna push around? Come here!}
{1048}{}{想四处走走吗？过来！ -- Wanna push around? Come here!}
### {1049}{}{[angrily looks at you]}
{1049}{}{[愤怒地看着你 -- angrily looks at you]}
