#{100}{}{You see a man.}
{100}{}{你看到一个男人。}
#{150}{}{You see Alvarez.}
{150}{}{你看到阿尔瓦雷斯。}
#{200}{}{You see a merchant surrounded with various goods.}
{200}{}{你看到一个被各种各样商品包围着的商人。}
#{250}{}{You see Alvarez, a local trader. He might never even leave his spot, just so he wouldn't lose any customers.}
{250}{}{你看阿尔瓦雷斯，一个本地商人。他甚至可能永远不会离开他的位置，只是为了不失去任何客户。}
#{300}{}{I told you to leave.}
{300}{}{我叫你离开。}
#{301}{}{Go away.}
{301}{}{走开。}
#{302}{}{Get lost.}
{302}{}{滚开。}
#{400}{}{Someone will take care of you soon.}
{400}{}{很快就会有人关照你的。}
#{401}{}{Heeelp!}
{401}{}{帮帮我！}
#{402}{}{What do you want?}
{402}{}{你想要什么？}
#{403}{}{Let it go!}
{403}{}{放手！}
#{404}{}{Let me live.}
{404}{}{让我活下去。}
#{500}{}{Welcome to Alvarez's, wanderer. That's me, and I trade with everything and everyone - strangers, locals, caravans. Anything your eyes see here is for sale.}
{500}{}{欢迎来到阿尔瓦雷斯，流浪者。就是我，我和所有人、陌生人、当地人、商队做生意。你在这里看到的任何东西都是出售的。}
#{501}{}{Welcome to Alvarez's, wanderer. That's me, and I trade with everything and everyone - strangers, locals, caravans. Anything... [He pauses when he sees Lystra.] I hope your friend doesn't think I'll feel honored or something just because someone from the empire paid me a visit. Anyone can see she's from there. It's painfully obvious that she doesn't belong here.}
{501}{}{欢迎来到阿尔瓦雷斯，流浪者。就是我，我和所有人、陌生人、当地人、商队做生意。任何东西...[他看到莱斯特拉时停顿了一下。]我希望你的朋友不会因为帝国的人来拜访我而觉得我很荣幸。很明显，任何人都能看出她不属于这里，她是从那来的。}
#{502}{}{Let us trade then.}
{502}{}{那就让我们交易吧 。}
#{503}{}{I have some questions about the city.}
{503}{}{我有一些关于这个城市的问题。}
#{504}{}{Ubha?}
{504}{}{乌卜哈？}
#{505}{}{Not interested, bye.}
{505}{}{不感兴趣，再见。}
#{550}{}{It was a pleasure trading with you. Please come again.}
{550}{}{很高兴和你交易。欢迎再来。}
#{551}{}{I have some questions about the city.}
{551}{}{我有一些关于这个城市的问题。}
#{552}{}{See you.}
{552}{}{回见。}
#{600}{}{I'm not opposed to trading anything - even information. For 300 caps I will tell you everything I know about the city whenever you stop by. Many people come to me, and I overhear much. Trust me, it will be worth it.}
{600}{}{我不反对交易任何东西-甚至是信息。300个瓶盖，我就告诉你这座城市的一切。很多人来找我，我听到了很多。相信我，这是值得的。}
#{601}{}{Can't you just answer a few questions?}
{601}{}{你就不能回答几个问题吗？}
#{602}{}{Alright, here you go. [Give him 300 caps.]}
{602}{}{好的，给你。[给他300个瓶盖。]}
#{603}{}{I think 250 caps would be enough. What do you say? [Give him 250 caps.]}
{603}{}{我想250个瓶盖就够了。你的意思呢？[给他250个瓶盖。]}
#{604}{}{I don't know what I'm paying for, so you won't get more than 200 from me. [Give him 200 caps.]}
{604}{}{我不知道我要付多少钱，所以你不会从我这里得到超过200。[给他200个瓶盖]}
#{605}{}{I don't have that much.}
{605}{}{我没有那么多。}
#{606}{}{I'm not giving you a dime, goodbye.}
{606}{}{我不会给你一分钱的，再见。}
#{650}{}{I don't know what backwater you're from, but here, nothing is free. You want answers - you pay for them.}
{650}{}{我不知道你来自哪个落后的地区，但在这里没有什么是免费的。你想要答案-付钱。}
#{651}{}{Alright, here you go. [Give him 300 caps.]}
{651}{}{好的，给你。[给他300个瓶盖。]}
#{652}{}{I think 250 caps would be enough. What do you say? [Give him 250 caps.]}
{652}{}{我想250个瓶盖就够了。你的意思呢？[给他250个瓶盖。]}
#{653}{}{I don't know what I'm paying for, so you won't get more than 200 from me. [Give him 200 caps.]}
{653}{}{我不知道我要付多少钱，所以你不会从我这里得到超过200。[给他200个瓶盖。]}
#{654}{}{I don't have that much.}
{654}{}{我没有那么多。}
#{655}{}{I'm not giving you a dime, goodbye.}
{655}{}{我不会给你一分钱的，再见。}
#{700}{}{Gracias. [He takes the caps.] Well then, what do you want to know?}
{700}{}{谢谢。[他拿走瓶盖。]那么你想知道什么？}
#{701}{}{Who rules this town?}
{701}{}{谁统治这个地方？}
#{702}{}{Tell me about this quarter.}
{702}{}{告诉我这段时间的情况。}
#{703}{}{What places are worth visiting?}
{703}{}{哪些地方值得看看？}
#{704}{}{Any work to be had here?}
{704}{}{这里有什么工作可以做吗？}
#{705}{}{I need Rebirth talismans to get into the Hunters' base. Any idea where I could get some?}
{705}{}{我需要重生护身符才能进入猎人基地。你知道我在哪儿能买到吗？}
#{706}{}{I need Rebirth talismans to get into the Hunters' base. Any idea where I could get some?}
{706}{}{我需要重生护身符才能进入猎人基地。你知道我在哪儿能买到吗？}
#{707}{}{The job from William that you set me up with involves terminating Vex. Any idea how to get close to him?}
{707}{}{你安排的来自威廉的工作涉及到终结维克斯，知道怎么接近他吗？}
#{708}{}{What do you know about William's women?}
{708}{}{你对威廉的女人了解多少？}
#{709}{}{Nothing right now.}
{709}{}{现在什么都没有。}
#{710}{}{William wants me to kill Vex. Any idea how to get close to him?}
{710}{}{威廉要我杀了维克斯。知道怎么接近他吗？}
#{750}{}{You could say that Albuquerque belongs to the empire, but the Mutant Hunters are really in charge here.}
{750}{}{你可以说阿尔伯克基是帝国的，但这里的真正主人是变种猎人。}
#{751}{}{Tell me about the empire.}
{751}{}{告诉我关于帝国的事。}
#{752}{}{Tell me about the Hunters.}
{752}{}{告诉我关于猎人的事。}
#{753}{}{I have some other questions.}
{753}{}{我还有一些问题。}
#{754}{}{That's enough for now.}
{754}{}{这就够了。}
#{800}{}{In case you didn't already know, there is a vault numbered 16 below the city. Descendants of those who lived there founded the empire. They don't care about us, though, they're holed up in their proud City, as they pompously call it. And why should they care, when they have everything.}
{800}{}{你还不知道吧，城市下面有一个编号为16的避难所。居住在那里的人的后代建立了帝国。但他们并不在乎我们，他们躲在他们骄傲的城市里，就像他们傲慢地称呼它的那样。他们什么都有，为什么还要在乎。}
#{801}{}{Tell me about the Hunters.}
{801}{}{告诉我关于猎人的事。}
#{802}{}{I have some other questions.}
{802}{}{我还有一些问题。}
#{803}{}{That's enough for now.}
{803}{}{这就够了。}
#{850}{}{They hate mutants, want to exterminate them all. According to their dubious agreement with the empire, they're supposed to protect Albuquerque from mutants. [He leans in close to you and starts whispering.] You'd best keep your distance and avoid provoking them - when a Hunter doesn't like you, they'll kill you and nobody will care one bit if you really were a mutant or not.}
{850}{}{他们讨厌变种人，想把他们全部消灭。根据他们与帝国的可疑协议，他们应该保护阿尔伯克基免受变种人的攻击。[他靠在你身边，开始耳语。]你最好保持距离，避免激怒他们-当猎人不喜欢你时，他们会杀了你，没有人会在乎你是否真的是变种人。}
#{851}{}{Tell me about the empire.}
{851}{}{告诉我帝国的事。}
#{852}{}{I have some other questions.}
{852}{}{我还有一些问题。}
#{853}{}{That's enough for now.}
{853}{}{这就够了。}
#{854}{}{They hate mutants, want to exterminate them all. According to their dubious agreement with the empire, they're supposed to protect Albuquerque from mutants. [He leans in close to you and starts whispering.] You'd best keep your distance and avoid provoking them - when a Hunter doesn't like you, they'll kill you and nobody will care one bit if you really were a mutant or not.}
{854}{}{他们讨厌变种人，想把他们全部消灭。根据他们与帝国的可疑协议，他们应该保护阿尔伯克基免受变种人的攻击。[他靠在你身边，开始耳语。]你最好保持距离，避免激怒他们-当猎人不喜欢你时，他们会杀了你，没有人会在乎你是否真的是变种人。}
#{900}{}{The wasteland is full of rampaging ghouls destroying everything they find, so people here in the Suburbs are mostly survivors of their attacks. We're all from different cities, but we stick together because we have to share this place with an assorted collection of all the scum that the wastes have to offer. Anything from tribals to various thieves and murderers.}
{900}{}{荒地上到处都是肆虐的僵尸，摧毁他们找到的一切，所以郊区的人们大多是他们袭击的幸存者。我们都来自不同的城市，但我们团结在一起，因为我们必须与各种各样的垃圾一起分享这个地方，不管是部落还是各种小偷和杀人犯。}
#{901}{}{Tell me about the people from the cities.}
{901}{}{告诉我关于城里人的事。}
#{902}{}{Tell me about the tribals.}
{902}{}{告诉我关于部落的事。}
#{903}{}{Tell me about the thieves and such.}
{903}{}{告诉我关于小偷之类的事。}
#{904}{}{I have some other questions.}
{904}{}{我还有一些问题。}
#{905}{}{That's enough for now.}
{905}{}{这就够了。}
#{950}{}{It's terrible, the ghouls are destroying even the large cities now. Albuquerque is the last city in this area that's still standing and, to the Hunters' credit, it's mostly thanks to them. We're all from different cities, but we stick together, mostly thanks to William.}
{950}{}{太可怕了，僵尸现在连大城市都在摧毁。阿尔伯克基是这个地区最后一个仍然屹立不倒的城市，这是猎人们值得称赞的地方，这要感谢他们。因为威廉，我们虽然来自不同的城市，但我们团结在一起。}
#{951}{}{Tell me more about William.}
{951}{}{告诉我更多关于威廉的事。}
#{952}{}{Tell me about the tribals.}
{952}{}{告诉我关于部落的事。}
#{953}{}{Tell me about the thieves and such.}
{953}{}{告诉我关于小偷之类的事。}
#{954}{}{I have some other questions.}
{954}{}{我还有一些问题。}
#{955}{}{That's enough for now.}
{955}{}{这就够了。}
#{1000}{}{A bunch of idiots with spears. Sometimes I buy skins of the animals they hunt from them. That's about the only thing they're good for.}
{1000}{}{一群拿着长矛的白痴。有时我会买他们猎取的动物的皮，这大概是他们唯一的优势。}
#{1001}{}{A bunch of idiots with spears. Sometimes I buy skins of the animals they hunt from them. That's about the only thing they're good for. I'm afraid the skins will become pretty rare now, though. I'll have to increase the prices.}
{1001}{}{一群拿着长矛的白痴。有时我会买他们猎取的动物的皮。这大概是他们唯一的优势。恐怕这些动物皮现在会变得非常罕见，所以我不得不提高价格收购。}
#{1002}{}{Tell me about the people from the cities.}
{1002}{}{告诉我关于城里人的事。}
#{1003}{}{Tell me about the thieves and such.}
{1003}{}{告诉我关于小偷之类的事。}
#{1004}{}{I have some other questions.}
{1004}{}{我还有一些问题。}
#{1005}{}{That's enough for now.}
{1005}{}{这就够了。}
#{1050}{}{A guy named Vex founded a gang here from former raiders and the like. They rob the locals or collect 'protection' money from them. Even William hasn't been able to disperse them yet, so you can see how dangerous they are.}
{1050}{}{一个叫维克斯的家伙在这里成立了一个帮派，他们是来自前掠夺者之类的人。他们抢劫当地人或向他们收取“保护费”。就连威廉也没能驱散他们，所以你可以看到他们有多危险。}
#{1051}{}{Now that Vex is dead the bastards will hopefully leave us alone. I think that his head on a pike will serve as a warning for people like them.}
{1051}{}{现在维克斯死了，这些混蛋们希望能离开我们。我认为他的头在长矛上会对像他们这样的人起到警示作用。}
#{1052}{}{A guy named Vex founded a gang here from former raiders and the like. They rob the locals or collect 'protection' money from them. They've shown how dangerous they are by killing William's wife, and now he doesn't want to waste any of his people on protecting us. That doesn't bode well for... For us and him as well, because business will suffer.}
{1052}{}{一个叫维克斯的家伙在这里成立了一个帮派，他们是来自前掠夺者之类的人。他们抢劫当地人或向他们收取“保护费”。他们杀了威廉的妻子，来证明他们是多么的危险，现在他不想浪费任何人来保护我们。这对我们和他都不是好兆头，因为生意会受到影响。}
#{1053}{}{Where can I find this Vex?}
{1053}{}{我在哪里可以找到维克斯？}
#{1054}{}{Tell me about the people from the cities.}
{1054}{}{告诉我关于城里人的事。}
#{1055}{}{Tell me about the tribals.}
{1055}{}{告诉我关于部落的事。}
#{1056}{}{I have some other questions.}
{1056}{}{我还有一些问题。}
#{1057}{}{That's enough for now.}
{1057}{}{这就够了。}
#{1100}{}{As you know, nobody should miss visiting my shop - I really do trade with everything. If you want some entertainment, try the Wild Paradise in the Hunters' Territory. Or, if you need medical treatment, you should pay a visit to the hospital in the Dead Quarter. But don't bother going into either of those without a nice sum of caps.}
{1100}{}{你懂的，任何人都不应该错过参观我的商店-我真的做任何东西的交易。如果你想要一些娱乐，试试猎人领地的狂野天堂。或者你需要治疗，可以去死区的医院看看。但是如果没有钱，就不要费心地去那两个地方了。}
#{1101}{}{I have some other questions.}
{1101}{}{我还有一些问题。}
#{1102}{}{That's enough for now.}
{1102}{}{这就够了。}
#{1150}{}{Vex and his buddies took over the large ruin in the northern Suburbs. Decent folk steer clear of that place. Vex is quite capable of killing you just for looking at him funny. That's what they say, at least, and it's best not to pry further.}
{1150}{}{维克斯和他的伙伴们接管了北郊的大片废墟。体面的人避开那个地方。维克斯很可能会因为你看他滑稽就杀了你。至少他们是这么说的，最好不要再打听了。}
#{1151}{}{Tell me about the people from the cities.}
{1151}{}{告诉我关于城里人的事。}
#{1152}{}{Tell me about the tribals.}
{1152}{}{告诉我关于部落的事。}
#{1153}{}{Tell me about the thieves and such.}
{1153}{}{告诉我关于小偷之类的事。}
#{1154}{}{I have some other questions.}
{1154}{}{我还有一些问题。}
#{1155}{}{That's enough for now.}
{1155}{}{这就够了。}
#{1200}{}{William lives not far from here - the two story house is his. His people protect us - or try to - in order to protect his investments. See, he has an agreement with the caravan companies from Sedit. Thanks to that, they come here loaded with trade goods, and the people here can at least get a job loading and unloading the caravans. William is fairly rich, so he can afford much.}
{1200}{}{威廉住在离这里不远的地方，那栋两层楼的房子是他的。他的人保护我们-或者试图-以保护他的投资。他和塞迪特的商队公司有协议。多亏了这一点，他们带着贸易货物来到这里，这里的人至少可以找到一份装卸商队的工作。威廉相当富有，所以他能负担得起。}
#{1201}{}{William lives not far from here - the two story house is his. He has an agreement with the caravan companies from Sedit. Thanks to that, they come here loaded with trade goods, and the people here can at least get a job loading and unloading the caravans. But I'm afraid that won't last long. After what's happened to William's wife, he doesn't want to waste any of his people on protecting us.}
{1201}{}{威廉住在离这里不远的地方，那栋两层楼的房子是他的。他和塞迪特的商队公司有协议。多亏了这一点，他们带着贸易货物来到这里，这里的人至少可以找到一份装卸商队的工作。但恐怕不会持续太久。在威廉的妻子发生了什么事之后，他不想浪费他的任何人来保护我们。}
#{1202}{}{Tell me about the people from the cities.}
{1202}{}{告诉我关于城里人的事。}
#{1203}{}{Tell me about the tribals.}
{1203}{}{告诉我关于部落的事。}
#{1204}{}{Tell me about the thieves and such.}
{1204}{}{告诉我关于小偷之类的事。}
#{1205}{}{I have some other questions.}
{1205}{}{我还有一些问题。}
#{1206}{}{That's enough for now.}
{1206}{}{这就够了。}
#{1250}{}{Si, I can give you a bit of a discount. [He takes the caps.] Well then, what do you want to know?}
{1250}{}{是的，我可以给你一点折扣。[他拿走瓶盖。]你想知道什么？}
#{1251}{}{Who rules this town?}
{1251}{}{谁统治这个地方？}
#{1252}{}{Tell me about this quarter.}
{1252}{}{告诉我这段时间的情况。}
#{1253}{}{What places are worth visiting?}
{1253}{}{哪些地方值得看看？}
#{1254}{}{Nothing right now.}
{1254}{}{现在什么都没有。}
#{1300}{}{Then come back when you do. Or you could sell something to me.}
{1300}{}{你会再回来的。或者你可以把东西卖给我。}
#{1301}{}{I might have something to sell, take a look.}
{1301}{}{我可能有东西要卖，看一眼。}
#{1302}{}{I have some gecko skins for sale.}
{1302}{}{我有一些蜥蜴皮要卖。}
#{1303}{}{I'll be back.}
{1303}{}{我会回来的。}
#{1350}{}{What else do you want to know?}
{1350}{}{你还想知道什么？}
#{1351}{}{Who rules this town?}
{1351}{}{谁统治这个城市？}
#{1352}{}{Tell me about this quarter.}
{1352}{}{告诉我这段时间的情况。}
#{1353}{}{What places are worth visiting?}
{1353}{}{哪些地方值得看看？}
#{1354}{}{Any work to be had here?}
{1354}{}{这里有什么工作可以做吗？}
#{1355}{}{I need Rebirth talismans to get into the Hunters' base. Any idea where I could get some?}
{1355}{}{我需要重生护身符才能进入猎人基地。你知道我在哪儿能买到吗？}
#{1356}{}{I need Rebirth talismans to get into the Hunters' base. Any idea where I could get some?}
{1356}{}{我需要重生护身符才能进入猎人基地。你知道我在哪儿能买到吗？}
#{1357}{}{The job from William that you set me up with involves terminating Vex. Any idea how to get close to him?}
{1357}{}{你安排的来自威廉的工作涉及到终结维克斯，知道怎么接近他吗？}
#{1358}{}{What do you know about William's women?}
{1358}{}{你对威廉的女人了解多少？}
#{1359}{}{Nothing right now.}
{1359}{}{现在什么都没有。}
#{1360}{}{William wants me to kill Vex. Any idea how to get close to him?}
{1360}{}{威廉要我杀了维克斯。知道怎么接近他吗？}
#{1400}{}{You're in luck - William has mentioned that I should send anyone that asks for a job to him. No idea what the job involves, though.}
{1400}{}{你真走运-威廉说过我应该把任何找工作的人都派给他。不过，不知道这项工作涉及什么。}
#{1404}{}{Know about any other work?}
{1404}{}{还有其它工作吗？}
#{1401}{}{Tell me more about William.}
{1401}{}{告诉我更多关于威廉的事。}
#{1402}{}{OK, but I have other questions.}
{1402}{}{OK，但是我还有其他问题。}
#{1403}{}{Alright, thanks.}
{1403}{}{好的，谢谢。}
#{1450}{}{Perdona, I don't. Work is scarce here in the Suburbs.}
{1450}{}{佩尔多纳，我不知道。郊区的工作很少。}
#{1451}{}{OK, I have some other questions.}
{1451}{}{OK，我还有一些问题。}
#{1452}{}{Alright then. Bye}
{1452}{}{那好吧。再见}
#{1500}{}{Head out and shoot some ghouls. But I'm guessing you don't want to get yourself killed. I do have a few of those talismans - people who for various reasons don't want to associate with the Hunters sell them to me. Usually I go and sell them to the Hunters myself when I have a bunch of them. But if you're really keen on getting into their base, I could throw them in with my regular goods for a buyout price. Think of it as a bonus for the paid information. I'm not too fond of the Hunter's Territory anyway, so at least I'll save myself the trip.}
{1500}{}{出去射杀几个僵尸。但我猜你不想自杀。我确实有一些护身符——出于各种原因不想与猎人打交道的人把它们卖给我的。通常我有一堆护身符时，就自己去把它们卖给猎人。但如果你真的想进入他们的基地，我可以以优惠的价格把它们和我的普通商品一起卖掉，就把它看作是对付费信息的奖励吧，反正我也不太喜欢猎人的领地，所以至少我可以省下这次旅行。}
#{1501}{}{Alright, let's trade.}
{1501}{}{好吧，我们交易吧。}
#{1502}{}{I have other questions for now.}
{1502}{}{我还有其他问题。}
#{1503}{}{I might buy them from you later, but I need to go now.}
{1503}{}{我以后可能会从你那儿买，但我现在得走了。}
#{1550}{}{Getting to Vex isn't hard, but who would want to? [He lowers his voice.] They say that he's completely insane. There's only one person that's really close to him - a whore from the Wild Paradise that he often visits. They say that being Vex's favorite hasn't done her much good.}
{1550}{}{找维克斯并不难，但谁会想去呢？他们说他完全疯了。只有一个他经常光顾的狂野天堂妓女跟他关系很近。他们说成为维克斯的宠儿对她没什么好处。}
#{1551}{}{I have some other questions.}
{1551}{}{我还有一些问题。}
#{1552}{}{Thanks, that's enough.}
{1552}{}{谢谢，够了。}
#{1600}{}{Doreen came here with William from Los Alamos, the place they used to live in. Not much is known about her. Penny, on the other hand, used to be quite popular here in Albuquerque. She worked her way up from a waitress in the Wild Paradise to stripper and up to a whore. William met her there and bought her off. I'm not sure you could consider that an improvement. William doesn't let his women leave the house much, and they say he's very strict with them. I'd say it's pretty wise of him, a woman can blow away an entire fortune in a moment.}
{1600}{}{多琳和威廉一起从洛斯阿拉莫斯来到这里，那是他们曾经住过的地方。对她了解不多。另一方面，佩妮过去在阿尔伯克基很受欢迎。她一路从狂野天堂的女招待，到脱衣舞女，再到妓女。威廉在那里遇见并包养了她。我不确定你能认为这是一种进步。威廉不让他的女人经常出门，他们说他对她管的很严。我认为他很聪明，一个女人可以在一瞬间挥霍掉一大笔财产。}
#{1601}{}{I have some other questions.}
{1601}{}{我还有一些问题。}
#{1602}{}{Thanks, that's enough.}
{1602}{}{谢谢，够了。}
#{1650}{}{Welcome back, wanderer, my shop is always open, so I don't miss any good deals.}
{1650}{}{欢迎回来，流浪者，我的商店一直营业，所以我不会错过任何好的交易。}
#{1651}{}{Welcome back...[He pauses when he sees Lystra.] I hope your friend doesn't think I'll feel honored or something just because someone from the empire paid me a visit. Anyone can see she's from there. It's painfully obvious that she doesn't belong here. But enough of that, are you here to trade?}
{1651}{}{欢迎回来…[他看到莱斯特拉时停顿了一下。]我希望你的朋友不会因为帝国的人来拜访我而觉得我很荣幸。很明显，任何人都能看出她不属于这里，她是从那来的。没关系，你是来交易的吗？}
#{1652}{}{Welcome back...[He pauses when he sees Lystra.] I hope your friend doesn't think I'll feel honored or something just because someone from the empire paid me a visit. Anyone can see she's from there. It's painfully obvious that she doesn't belong here. But enough of that, are you here to trade?}
{1652}{}{欢迎回来……[他看到莱斯特拉时停顿了一下]我希望你的朋友不会因为帝国的人来拜访我就觉得我很荣幸。很明显，任何人都能看出她不属于这里，她是从那来的。你是来交易的吗？}
#{1653}{}{Let's trade then.}
{1653}{}{那就交易吧。}
#{1654}{}{I have some gecko skins for sale.}
{1654}{}{我有一些蜥蜴皮要卖。}
#{1655}{}{I have some questions about the city.}
{1655}{}{我有一些关于这个城市的问题。}
#{1656}{}{I don't want to trade, bye.}
{1656}{}{我不想交易，再见。}
#{1657}{}{Ugaha?}
{1657}{}{嗷啊？}
#{1658}{}{Uf.}
{1658}{}{呃。}
#{1700}{}{Speaking of trading... It is said that you've been visiting the local tribals. I'm not judging you - that's your business. What I'm interested in are gecko skins. The tribals hunt geckos, and nobody can get the skin off like they can. I'd give you a good price for skins of such quality, say, 100 for silver and 200 for golden skin. And I don't care where nor how you get them.}
{1700}{}{说到交易...据说你一直在拜访当地部落。我不是在评判你-那是你的事。我感兴趣的是蜥蜴皮。部落猎杀壁虎，没有人能像他们那样把蜥蜴的皮剥下来。我会给你一个很好的价格，比如说，银皮100，金皮200。我不在乎你从哪里得到它们，也不在乎你是如何得到它们。}
#{1701}{}{I have some gecko skins for sale.}
{1701}{}{我有一些蜥蜴皮要卖。}
#{1702}{}{I want to trade something else right now.}
{1702}{}{我现在想换点别的东西。}
#{1703}{}{OK, maybe later.}
{1703}{}{OK，也许以后吧。}
#{1704}{}{Speaking of trading... It is said that you've been visiting the local tribals. I'm not judging you - that's your business. What I'm interested in are gecko skins. The tribals hunt geckos, and nobody can get the skin off like they can. I'd give you a good price for skins of such quality, say, 100 for silver and 200 for golden skin. And I don't care where nor how you get them.}
{1704}{}{说到交易...据说你一直在拜访当地部落。我不是在评判你-那是你的事。我感兴趣的是蜥蜴皮。部落猎杀壁虎，没有人能像他们那样把蜥蜴的皮剥下来。我会给你一个很好的价格，比如说，银皮100，金皮200。我不在乎你从哪里得到它们，也不在乎你是如何得到它们。}
#{1750}{}{Golden or silver gecko skins?}
{1750}{}{金色还是银色的蜥蜴皮？}
#{1751}{}{Silver.}
{1751}{}{银色。}
#{1752}{}{Golden.}
{1752}{}{金色。}
#{1753}{}{I want to trade something else right now.}
{1753}{}{我现在想换点别的东西。}
#{1754}{}{You know what? Maybe later.}
{1754}{}{你知道吗？也许以后吧。}
#{1800}{}{Alright. [He takes all your silver gecko skins and gives you }
{1800}{}{好吧。[他拿走你所有的银蜥蜴皮}
#{1801}{}{Excellent. [He takes all your golden gecko skins and gives you }
{1801}{}{好极了。[他拿走了你所有的金蜥蜴皮}
#{1802}{}{ caps.] I'd be interested in buying more, if you manage to get them.}
{1802}{}{ 瓶盖。]如果你能多弄到一些，我想再买点。}
#{1803}{}{I want to sell some silver gecko skins too.}
{1803}{}{我想卖些银蜥蜴皮。}
#{1804}{}{I want to sell some golden gecko skins too.}
{1804}{}{我想卖些金蜥蜴皮。}
#{1805}{}{I want to trade something else right now.}
{1805}{}{我现在想换点别的东西。}
#{1806}{}{We'll see. Bye for now...}
{1806}{}{我们拭目以待。再见...}
#{1850}{}{Welcome to Alvarez's, Hunter. That's me, and I'm sure you know that I fully support your cause with a hefty discount for each of you.}
{1850}{}{欢迎来到阿尔瓦雷斯，猎人。那是我，我相信你们知道我完全支持你们的事业，给你们每人一个大折扣。}
#{1851}{}{Excellent, let's trade then.}
{1851}{}{太好了，那就交易吧。}
#{1852}{}{I have some questions about the city.}
{1852}{}{我有一些关于这个城市的问题。}
#{1853}{}{I don't want to trade, bye.}
{1853}{}{我不想交易，再见。}
#{1854}{}{He?}
{1854}{}{他？}
#{1855}{}{Uf.}
{1855}{}{呃。}
#{1900}{}{It was an honor trading with you, Hunter. Please come again.}
{1900}{}{很荣幸和你交易，猎人。欢迎再来。}
#{1901}{}{I have some questions about the city.}
{1901}{}{我有一些关于这个城市的问题。}
#{1902}{}{Goodbye.}
{1902}{}{再见。}
#{1950}{}{A simple trader like me cannot possible know more then you do. Had I heard about any mutants trying to hide in the Suburbs, I would've reported them of course.}
{1950}{}{像我这样简单交易者不可能比你知道得更多。如果我听说有变种人想躲在郊区，我当然会举报他们。}
#{1951}{}{[Menacingly.] Are you ABSOLUTELY certain?}
{1951}{}{[威胁地。]你“确定”吗？}
#{1952}{}{Do you know about any work here in the city? I want to make some extra caps on the side.}
{1952}{}{你知道城里有什么工作吗？我想在附近多挣点钱。}
#{1953}{}{OK.}
{1953}{}{OK。}
#{2000}{}{I really don't know about any mutants. But you know how it is with the tribals. I have no doubt you'd find some mutation among them if you looked carefully enough.}
{2000}{}{我真的不知道有什么变种人。但你知道部落是怎么回事。如果你仔细观察的话，我毫不怀疑你会在他们中间发现一些变异。}
#{2001}{}{OK.}
{2001}{}{OK。}
#{2050}{}{I really don't know about any mutants, though it might be a good idea to take a look at Ben. He's been meeting with the tribals, and you know how it is with them and mutation.}
{2050}{}{我真的不知道有什么变种人，不过看看本可能是个好主意。他一直在和部落会面，他可能知道他们的情况。}
#{2051}{}{OK.}
{2051}{}{OK。}
#{2100}{}{I really don't know about any mutants. But, since you asked, a woman named Catherine has a small daughter that she never lets out of the house. Very suspicious.}
{2100}{}{我真的不知道有什么变种人。但是，说起来，一个叫凯瑟琳的女人有一个小女儿，她从不让她走出家门，非常可疑。}
#{2101}{}{OK.}
{2101}{}{OK。}
#{2150}{}{Ehh... you're in luck - William has mentioned that I should send anyone that asks for a job to him. No idea what the jobs involves, though.}
{2150}{}{呃...你真走运-威廉说过我应该把任何找工作的人都派给他。不过，不知道这些工作涉及到什么。}
#{2152}{}{Know about any other work?}
{2152}{}{还有其它工作吗？}
#{2151}{}{Alright, thanks.}
{2151}{}{好的，谢谢。}
#{2200}{}{Siento, I don't. As you might suspect, work is pretty scarce in the Suburbs.}
{2200}{}{我不知道。就像你想的那样，郊区的工作非常少。}
#{2201}{}{Goodbye then.}
{2201}{}{那么再见了。}
#{2250}{}{Welcome, I'm glad to see you again - as I'm glad to see every Hunter. My shop is always open, so don't miss any good deals.}
{2250}{}{欢迎，我很高兴再次见到你-就像我很高兴见到每个猎人一样。我的商店一直营业，所以不要错过任何优惠。}
#{2251}{}{Let's trade.}
{2251}{}{我们交易吧。}
#{2252}{}{I have some questions about the city.}
{2252}{}{我有一些关于这个城市的问题。}
#{2253}{}{[Leave.]}
{2253}{}{[离开。]}
#{2254}{}{He?}
{2254}{}{他？}
#{2255}{}{Uf.}
{2255}{}{呃。}
#{2300}{}{Another tribal. [He quietly sighs to himself.] Alright, look, people like you gather over there, where the tents are. [He signs a roof with his hands.] If you want to buy something, I'm sure we can agree on a fair price, just take a look.}
{2300}{}{另一个部落。[他轻轻地叹了口气。]好吧，听着，像你这样的人聚集在那里，帐篷在那里。[他用手在地图上做了标记。]如果你想买东西，我相信我们可以商定一个公平的价格，你看一下就行了。}
#{2301}{}{Another tribal. [He quietly sighs to himself.] Alright, look, people like you gather over there, where the tents are. [He signs a roof with his hands.] If you want to buy something, I'm sure we can agree on a fair price, just take a look.}
{2301}{}{另一个部落。[他轻轻地叹了口气。]好吧，听着，像你这样的人聚集在那里，帐篷在那里。[他用手在地图上做了标记。]如果你想买东西，我相信我们可以商定一个公平的价格，你看一下就行了。}
#{2302}{}{Hee.}
{2302}{}{嘿。}
#{2303}{}{Bai.}
{2303}{}{白。}
#{2350}{}{See, I have many nice things. Come back when you have many caps.}
{2350}{}{看，我有很多好东西。当你有很多瓶盖的时候再来。}
#{2351}{}{Baaai.}
{2351}{}{额呃。}
#{2400}{}{Certainly, my simple-minded friend. We can trade if you want to. I give special prices to people like you.}
{2400}{}{当然，我头脑简单的朋友。如果你愿意，我们可以交易。我给像你这样的人特别的价格。}
#{2401}{}{Certainly, my simple-minded friend. We can trade if you want to. I give special prices to people like you.}
{2401}{}{当然，我头脑简单的朋友。如果你愿意，我们可以交易。我给像你这样的人特别的价格。}
#{2402}{}{Woo!}
{2402}{}{喔！}
#{2403}{}{[Wave your hand and leave.]}
{2403}{}{[挥手离开。]}
#{2450}{}{Dammit, don't you know Hunters hate mutants?! And you come here with a monster, one big walking mutation! Go away, leave, I don't want any trouble.}
{2450}{}{该死的，你不知道猎人讨厌变种人吗？！你居然带着一个变种怪物来到这！快走开，我不想惹麻烦。}
#{2451}{}{Grrr!}
{2451}{}{咯喇！}
#{2452}{}{Blech.}
{2452}{}{唔拉。}
#{2453}{}{OK.}
{2453}{}{OK。}
#{2500}{}{Visit the chief of the tribals - if you don't mind dealing with their kind. I trade with them occasionally, and I know that some of their gecko hunters have gone missing. I'd say the dangers of the wasteland got them, but they think something else is behind it. Bah... They probably blame evil spirits or something.}
{2500}{}{如果你不介意和他们打交道的话，去拜访部落首领吧。我偶尔和他们交易，我知道他们的一些蜥蜴猎人失踪了。我想说是荒地的危险让他们受到了伤害，但他们认为背后还有别的原因。呸... 他们可能会怪恶魔什么的。}
#{2501}{}{Know about any other work?}
{2501}{}{还有其它工作吗？}
#{2502}{}{Tell me about the tribals.}
{2502}{}{告诉我关于部落的事。}
#{2503}{}{OK, but I have some other questions.}
{2503}{}{好的，但我还有一些问题。}
#{2504}{}{Alright, thanks.}
{2504}{}{好的，谢谢。}
#{2550}{}{You might try your luck in the hospital - you'll find it in the Dead Quarter. I doubt they'd take you on as a doctor, but the mercenaries that work for the hospital might still be looking for a few people.}
{2550}{}{你可以在医院碰碰运气-你会在死区找到它的。我怀疑他们会接受你当医生，但为医院工作的雇佣兵可能还在招几个人。}
#{2551}{}{Know about any other work?}
{2551}{}{还有其它工作吗？}
#{2552}{}{OK, but I had some other questions first.}
{2552}{}{好的，但我首先有一些其它的问题。}
#{2553}{}{Alright, thanks.}
{2553}{}{好的，谢谢。}
#{2570}{}{Hard to say. You could try asking Catherine. Every time I see her, I can see on her that something is troubling her. Maybe it's something you could help with. She lives in the house next door. But even if she does talk to you, don't expect much of a profit - she can't afford it.}
{2570}{}{很难说。你可以试着问下凯瑟琳。每次我见到她，我都能从她身上看出有什么事困扰着她。也许你能帮上忙。她住在隔壁的房子里。但即使她真的和你说话，也不要指望有多大的利润 - 她负担不起。}
#{2571}{}{Know about any other work?}
{2571}{}{还有其它工作吗？}
#{2572}{}{OK, but I had some other questions first.}
{2572}{}{好的，但我首先有一些其它的问题。}
#{2573}{}{Alright, thanks.}
{2573}{}{好的，谢谢。}
#{2600}{}{You should try the hospital in the Dead Quarter. The mercenaries working for the hospital might be happy to have a Mutant Hunter join them.}
{2600}{}{你应该去死区的医院看看。为医院工作的雇佣兵可能会很高兴有一个变种猎人加入他们。}
#{2601}{}{Know about any other work?}
{2601}{}{还有其他工作吗？}
#{2602}{}{Alright, thanks.}
{2602}{}{好的，谢谢。}
#{2650}{}{Ehm... Are you feeling well, Hunter? My apologies, I meant nothing by it. We can trade, if you want to.}
{2650}{}{嗯...你感觉好吗，猎人？抱歉，我没有别的意思。如果你愿意，我们可以交易。}
#{2651}{}{Yup.}
{2651}{}{是的。}
#{2652}{}{Noes. Bai.}
{2652}{}{没有。白。}
#{2700}{}{Come back again anytime, Hunter.}
{2700}{}{欢迎再来，猎人。}
#{2701}{}{Baaai.}
{2701}{}{巴艾。}
