#{100}{}{You see a nervous looking man.}
{100}{}{你看到一个看起来很紧张的人。}
#{150}{}{You see an informant.}
{150}{}{你看到线人了。}
#{200}{}{You see a man nervously surveying his surroundings.}
{200}{}{你看到一个人紧张地审视着周围的环境。}
#{250}{}{You see an informant willing to snitch on Anonym.}
{250}{}{你看到一个愿意匿名告密的线人。}
#{300}{}{Yeah, you do that.}
{300}{}{是的，你可以这么做。}
#{301}{}{I've told you all I know.}
{301}{}{我知道的都告诉你了。}
#{302}{}{Go away, someone might get suspicious.}
{302}{}{走开，有人会怀疑的。}
#{303}{}{Don't worry, I'll send the message on time like I said.}
{303}{}{别担心，我会像我说的那样准时发信息。}
#{304}{}{I don't want anyone see us talking.}
{304}{}{我不想让任何人看到我们谈话。}
#{305}{}{Do what you're supposed to and quit bothering me.}
{305}{}{做你该做的，别再烦我了。}
#{306}{}{What the fuck?! You leave me no choice but to kill you. I didn't want this.}
{306}{}{卧槽？！你让我别无选择只能杀了你。我不想这样。}
#{500}{}{She sent you? [He keeps looking around cautiously.]}
{500}{}{她派你来的？[他一直小心地环顾四周。]}
#{501}{}{If you mean Adviser Elisa, then yes, she sent me.}
{501}{}{如果你是指伊莉莎顾问，那么是的，她派我来的。}
#{502}{}{Ghe?}
{502}{}{啊？}
#{550}{}{What? [He takes a hard look at you.] It can't possibly be you. Look, moron, I'm waiting for someone. so get lost.}
{550}{}{什么？[他狠狠地看了你一眼。]不可能是你。听着，白痴，我在等人。所以，滚开。}
#{551}{}{What? [He takes a hard look at you.] It can't possibly be you. Look, moron, I'm waiting for someone, so get lost.}
{551}{}{什么？[他狠狠地看了你一眼。]不可能是你。听着，白痴，我在等人，所以，滚开。}
#{552}{}{Uff.}
{552}{}{呃。}
#{600}{}{Yeah, the imperial big shot, that's the one. Finally someone showed up, I've been trying to give her information about Anonym for quite some time.}
{600}{}{是的，帝国大人物，就是那个。终于有人出现了，我一直给她提供匿名者信息已经很长一段时间了。}
#{601}{}{But what about the soldiers she sent to meet you?}
{601}{}{但是她派来接你的士兵呢？}
#{602}{}{Come on then, tell me what you know.}
{602}{}{来吧，告诉我你知道什么。}
#{650}{}{What soldiers, what are you talking about? Nobody came to meet me.}
{650}{}{什么士兵，你在说什么？没人来接我。}
#{651}{}{The empire has sent a squad of soldiers to meet you so that you could send them after Anonym. They were all killed in the Dead Quarter.}
{651}{}{帝国派了一队士兵来迎接你，这样你就可以在匿名者后面派出他们。他们都在死区被杀了。}
#{700}{}{What? How could anyone kill an entire squad of the imperial soldiers? They must've gotten to them before me. That's not good, they might be suspecting me. The empire must get Anonym as soon as possible!}
{700}{}{什么？谁能杀死一整队帝国士兵？他们一定是在我之前找到他们的。不好，他们可能在怀疑我。帝国必须尽快找到匿名者！}
#{701}{}{What do you know then?}
{701}{}{那你知道什么？}
#{702}{}{Where did you get your information?}
{702}{}{你从哪里得到的信息？}
#{703}{}{Tell me everything you know before I break your teeth.}
{703}{}{在我把你牙都打掉之前告诉我你知道的一切。}
#{704}{}{Would 400 caps be enough for your information?}
{704}{}{400个瓶盖够买你的消息吗？}
#{705}{}{As a mercenary, you're the empire's target, and because you're a snitch, Anonym wants you dead too. That's some deep shit you're in, pal, so I'd recommend you start talking right now.}
{705}{}{作为一名雇佣兵，你是帝国的目标，因为你是告密者，匿名者也想让你死。你的处境很糟糕，伙计，所以我建议你现在赶紧说。}
#{706}{}{I don't trust you, so I'm not going to bother talking to you.}
{706}{}{我不相信你，所以我不想和你说话。}
#{750}{}{Wait, wait, not so fast. Not just anyone has this information. What do I get out of this? I'm risking my life here, that's worth a few caps, right?}
{750}{}{等等，等等，别那么快。不是每个人都有这个信息。我能从中得到什么？我在这里冒着生命危险，这值不少钱，对吗？}
#{751}{}{First, tell me about the soldiers that were supposed to meet with you.}
{751}{}{首先，告诉我应该和你见面的士兵的情况。}
#{752}{}{Where did you get your information?}
{752}{}{你从哪里得到的信息？}
#{753}{}{No. Either you tell me everything, or I break your teeth.}
{753}{}{不。要么你把一切都告诉我，要么我打掉你的牙。}
#{754}{}{Would 400 caps be enough for your information?}
{754}{}{400个瓶盖够买你的消息吗？}
#{755}{}{I don't trust you, so I'm not going to bother talking to you.}
{755}{}{我不相信你，所以我不想和你说话。}
#{800}{}{Does it matter? I can guarantee it's true, I'm not trying to screw you over. I've just kinda gotten myself involved in this, that's all.}
{800}{}{这有关系吗？我可以保证这是真的，我不是想欺骗你。我只是把自己卷入了这件事，仅此而已。}
#{801}{}{You're working for Anonym, am I right?}
{801}{}{你在为匿名者工作，对吗？}
#{850}{}{Alright, you got me! I'm a mercenary, he hired me and my party. But we didn't know what for, I swear! I don't want anything to do with it. The empire? Talk about biting off more than I can chew! That's why I contacted the empire bigwig. When Anonym and his people are busy worrying about the entire empire, I'll be able to quietly disappear. Some extra caps would help with that, too.}
{850}{}{好吧，你抓住我了！我是个雇佣兵，他雇了我和我的同伴，但我们不知道为什么，我发誓！我不想和他有任何关系。帝国？这是我“咬”不动的东西！这就是我联系帝国大人物的原因。当匿名者和他的人忙于担心整个帝国的时候，我就可以安静地消失了，一些额外的钱会对此有所帮助的。}
#{851}{}{Alright, you got me! I'm a mercenary, he hired me and my party. But we didn't know what for, I swear! I don't want anything to do with it. The empire? Talk about biting off more than I can chew! That's why I contacted the empire bigwig. When Anonym and his people are busy worrying about the entire empire, I'll be able to quietly disappear. Some extra caps would help with that, too.}
{851}{}{好吧，你抓住我了！我是个雇佣兵，他雇了我和我的同伴，但我们不知道为什么，我发誓！我不想和他有任何关系。帝国？这是我“咬”不动的东西！这就是我联系帝国大人物的原因。当匿名者和他的人忙于担心整个帝国的时候，我就可以安静地消失了，一些额外的钱会对此有所帮助的。}
#{852}{}{I'm not giving you anything. As a mercenary, you're the empire's target, and because you're a snitch, Anonym wants you dead too. That's some deep shit you're in, pal, so I'd recommend you start talking right now.}
{852}{}{我不会给你任何东西。作为一名雇佣兵，你是帝国的目标，因为你是告密者，匿名者也想让你死。你的处境很糟糕，伙计，所以我建议你现在赶紧说。}
#{853}{}{What about the soldiers that were supposed to meet with you?}
{853}{}{那些本来要和你见面的士兵呢？}
#{854}{}{Fuck you. Either you tell me everything, or I break your teeth.}
{854}{}{去你妈的。要么你把一切都告诉我，要么我打掉你的牙。}
#{855}{}{How about 400 caps, would that be enough?}
{855}{}{400瓶盖怎么样，够了吗？}
#{856}{}{I don't trust you, so I'm not going to bother talking to you.}
{856}{}{我不相信你，所以我不想和你说话。}
#{900}{}{Dammit, fine, just calm down. Anonym and his people meet with the hired mercenaries right here, in the cellar below this house. Knowing that won't help you now, because it's empty, but when the next meeting with Anonym takes place, I will know. Then I'll send a message to the empire boss woman. She can take care of him then. I'll make sure I'm not anywhere near that place.}
{900}{}{该死的，好吧，冷静点。匿名者和他的人就在这里，在这所房子下面的地窖里与雇佣兵会面。现在知道这对你没有帮助，因为它是空的，但下次与匿名者会面时，我会知道的。然后我会给帝国女老板发个信息，那时她可以照顾他了，我会确保我不在那个地方附近的。}
#{901}{}{OK, I can work with that. I'll go report to Elisa. Goodbye.}
{901}{}{OK，我可以处理这个问题。我去向伊莉莎报告。再见。}
#{950}{}{Bullshit, only Anonym is after me, you're nothing compared to him. What's your angle, anyway? I want to help and this is what I get? I don't want that much in return, do I?}
{950}{}{胡说，只有匿名者在找我，你跟他比什么都不是。你认为呢？我想帮忙，这就是我得到的？我不想得到那么多回报，是吗？}
#{951}{}{And about the soldiers that were supposed to meet with you?}
{951}{}{还有那些本来要和你见面的士兵？}
#{952}{}{Where did you get your information anyway?}
{952}{}{你从哪里得到的信息？}
#{953}{}{How about 400 caps, would that be enough?}
{953}{}{400瓶盖怎么样，够了吗？}
#{954}{}{I'm not giving you anything. As a mercenary, you're the empire's target, and because you're a snitch, Anonym wants you dead too. That's some deep shit you're in, pal, so I'd recommend you start talking right now.}
{954}{}{我不会给你任何东西。作为一名雇佣兵，你是帝国的目标，因为你是告密者，匿名者也想让你死。你的处境很糟糕，伙计，所以我建议你现在赶紧说。}
#{955}{}{I don't trust you, so I'm not going to bother talking to you.}
{955}{}{我不相信你，所以我不想和你说话。}
#{956}{}{I warned you. Time to say goodbye to your face!}
{956}{}{我警告过你，是时候对你的脸说再见了！}
#{957}{}{I warned you. Time to say goodbye to your face!}
{957}{}{我警告过你，是时候对你的脸说再见了！}
#{1000}{}{I offer information, take it or leave it. But I bet that the imperial big shot won't be pleased when she finds out that you ruined her only chance of finding Anonym.}
{1000}{}{我提供信息，要么接受，要么离开。但我敢打赌，当帝国大人物发现你毁了她找到匿名者唯一机会时，她不会高兴的。}
#{1001}{}{I offer information, take it or leave it. But I bet that the imperial big shot won't be pleased when she finds out that you ruined her only chance of finding Anonym.}
{1001}{}{我提供信息，要么接受，要么离开。但我敢打赌，当帝国大人物发现你毁了她找到匿名者唯一机会时，她不会高兴的。}
#{1002}{}{I don't want to end up like the soldiers that were supposed to meet with you.}
{1002}{}{我不想最后像那些本该和你见面的士兵下场一样。}
#{1003}{}{Where did you get your information anyway?}
{1003}{}{你从哪里得到的信息？}
#{1004}{}{Spit it out before I break your teeth.}
{1004}{}{在我打掉你的牙之前赶紧说。}
#{1005}{}{Alright, how about 400 caps, would that be enough?}
{1005}{}{好吧，400瓶盖怎么样，够了吗？}
#{1006}{}{And what if she finds out you're Anonym's mercenary? The empire will be after you because you're a mercenary, and Anonym will want you dead because you're a snitch. That's some deep shit you're in, pal, so I'd recommend you start talking right now.}
{1006}{}{如果她发现你是匿名者的佣兵怎么办？帝国会追杀你，因为你是个雇佣兵，而匿名者会因为你是告密者而杀了你。你的处境很糟糕，伙计，所以我建议你现在赶紧说。}
#{1007}{}{Bullshit. Go fuck yourself.}
{1007}{}{瞎扯。去你妈的。}
#{1008}{}{Oh, I'll beat the truth out of you yet.}
{1008}{}{哦，我会把你的真相说出来的。}
#{1050}{}{Sure, I can do something with that. Didn't expect you to be this generous, hehe. Well, if you insist, I'll tell you what I know for 400.}
{1050}{}{当然，我可以做点什么。没想到你这么大方，呵呵。好吧，如果你坚持，我会告诉你我知道的400英镑。}
#{1051}{}{Sure, I can do something with that. Didn't expect you to be this generous, hehe. Well, if you insist, I'll tell you what I know for 400.}
{1051}{}{当然，我可以用它做点什么。没想到你会这么慷慨，呵呵。好吧，恭敬不如从命，400我就告诉你我知道的。}
#{1052}{}{Here you go, enjoy. [Give him 400 caps.] And now, start talking.}
{1052}{}{给你，好好享受。[给他400个瓶盖。]现在，开始说吧。}
#{1053}{}{I'll return when I get them.}
{1053}{}{我拿到后会回来的。}
#{1054}{}{First you try to screw me over and then you laugh at me? I'll beat the information out of you!}
{1054}{}{你先是想骗我然后又嘲笑我？我会把你的消息公开的！}
#{1100}{}{Thanks, and don't worry, I'll keep my end of the bargain. Anonym and his people meet with the hired mercenaries right here, in the cellar below this house. Knowing that won't help you now, because it's empty, but when the next meeting with Anonym takes place, I will know. Then I'll send a message to the empire boss woman. She can take care of him then. I'll make sure I'm not anywhere near that place.}
{1100}{}{谢谢，别担心，我会遵守诺言的。匿名者和他的人就在这里，在这所房子下面的地窖里与雇佣兵会面。现在知道这对你没有帮助，因为它是空的，但下次与匿名者会面时，我会知道的。然后我会给帝国女老板发个信息，那时她可以照顾他了，我会确保我不在那个地方附近的。}
#{1101}{}{Alright, I can work with that. I'll go report to Elisa. Goodbye.}
{1101}{}{好吧，我可以处理这个问题。我去向伊莉莎报告。再见。}
#{1102}{}{Woo! Tells Elly!}
{1102}{}{喔！告诉伊莉！}
#{1150}{}{Well? Did you change your mind? I don't want much for that information about Anonym, just a few caps, nothing more.}
{1150}{}{好？你改变主意了吗？我不想知道太多关于匿名者的信息，只要几个大写字母就行了。}
#{1151}{}{Well? Did you change your mind? I don't want much for that information about Anonym, just a few caps, nothing more.}
{1151}{}{好？你改变主意了吗？我不想知道太多关于匿名者的信息，只要几个大写字母就行了。}
#{1152}{}{I don't want to end up like the soldiers that were supposed to meet with you.}
{1152}{}{我不想最后像那些本该和你见面的士兵下场一样。}
#{1153}{}{Where did you get your information anyway?}
{1153}{}{你从哪里得到的信息？}
#{1154}{}{Spit it out before I break your teeth.}
{1154}{}{在我打掉你的牙之前赶紧说。}
#{1155}{}{How about 400 caps, would that be enough?}
{1155}{}{400瓶盖怎么样，够了吗？}
#{1156}{}{I'm not giving you anything. As a mercenary, you're the empire's target, and because you're a snitch, Anonym wants you dead too. That's some deep shit you're in, pal, so I'd recommend you start talking right now.}
{1156}{}{我不会给你任何东西。作为一名雇佣兵，你是帝国的目标，因为你是告密者，匿名者也想让你死。你的处境很糟糕，伙计，所以我建议你现在赶紧说。}
#{1157}{}{Nope, I still don't trust you.}
{1157}{}{不，我还是不相信你。}
#{1158}{}{Uff.}
{1158}{}{呃。}
#{1200}{}{Well, what about the caps? Getting 400 caps shouldn't be a problem for someone like you. Stop dragging this out before Anonym gets us both.}
{1200}{}{那瓶盖呢？对于像你这样的人来说，拿到400瓶盖应该不是问题。别再拖拖拉拉了，不然我们俩都会被匿名者抓到的。}
#{1201}{}{Here you go, enjoy. [Give him 400 caps.] Now start talking.}
{1201}{}{给你，好好享受。[给他400个瓶盖。]现在开始说吧。}
#{1202}{}{I'll come back when I get the caps, just wait a bit longer.}
{1202}{}{我拿到瓶盖就回来，再等一会儿。}
#{1203}{}{Uf.}
{1203}{}{呃。}
#{1250}{}{That's enough! Are you nuts?! I'll tell you about Anonym, just leave me alone. I'd have talked anyway, you didn't have to attack me.}
{1250}{}{够了！你疯了吗？！我会告诉你关于匿名者的事，别烦我。反正我会说的，你不必攻击我。}
#{1251}{}{That's more like it, now spit it out!}
{1251}{}{更像是这样，赶快说！}
#{1252}{}{Hehee, talks now!}
{1252}{}{嘿嘿，现在说！}
#{1253}{}{No deal, killing you will make me much happier.}
{1253}{}{没有交易，杀了你会让我更快乐。}
#{1254}{}{Noo, me smash dead!}
{1254}{}{不，我死定了！}
