#{100}{}{You see a man of short stature.}
{100}{}{你看到一个身材矮小的人。}
#{150}{}{You see Benicio.}
{150}{}{你看到了贝尼西奥。}
#{200}{}{You see a short man with a sly face.}
{200}{}{你看到一个矮小的男人，有着一张狡猾的脸。}
#{250}{}{You see Benicio. He has a cunning look on his face.}
{250}{}{你看到了贝尼西奥，他脸上露出狡猾的神情。}
#{300}{}{Leave me alone.}
{300}{}{别烦我。}
#{301}{}{I love this place.}
{301}{}{我喜欢这个地方。}
#{302}{}{You won't find better whores anywhere else.}
{302}{}{你在其它地方找不到比这更好的妓女。}
#{303}{}{Time for another round.}
{303}{}{是时候再来一轮了。}
#{304}{}{I hope you understand why they call it the Wild Paradise now.}
{304}{}{我希望你明白为什么他们现在称它为狂野天堂。}
#{305}{}{Madame Chow sure knows how to train her whores.}
{305}{}{乔夫人当然知道如何训练她的妓女。}
#{306}{}{I'll never get tired of this place.}
{306}{}{我永远不会厌倦这个地方。}
#{310}{}{Come back when it's taken care of.}
{310}{}{处理好后再回来。}
#{311}{}{Go to Anonym.}
{311}{}{去找匿名者。}
#{312}{}{Sucks, huh? You won't have to worry about that for much longer though.}
{312}{}{真糟糕，是吗？不过，你不用担心太久了。}
#{313}{}{We have nothing to say to each other.}
{313}{}{我们没什么好说的。}
#{400}{}{Asking for trouble, are you?}
{400}{}{自找麻烦，是吗？}
#{401}{}{You're dead meat.}
{401}{}{你死定了。}
#{500}{}{[Right after you finish talking, Terrak gets into a loud debate with the bartender. At that moment, a short man with a crooked smile taps you on the back.] Sorry, buddy, but I couldn't help but overhear what you were talking about with the lieutenant here. I think I may have an offer for you. [He extends his hand to you.] I'm Benicio.}
{500}{}{[你刚说完，泰瑞克就和酒保展开了一场激烈的辩论。这时，一个带着扭曲微笑的矮个子男人拍了拍你的后背。]对不起，伙计，我无意中听到了你和中尉的谈话。我想我可以为你提供一份工作。[他向你伸出手。]我是贝尼西奥。}
#{501}{}{[Right after you finish talking, Terrak gets into a loud debate with the bartender. At that moment, a short man with a crooked smile taps you on the back.] Sorry, honey, but I couldn't help but overhear what you were talking about with the lieutenant here. I think I may have an offer for you. [He extends his hand to you.] I'm Benicio.}
{501}{}{[你刚说完，泰瑞克就和酒保展开了一场激烈的辩论。这时，一个带着扭曲微笑的矮个子男人拍了拍你的后背。]对不起，伙计，我无意中听到了你和中尉的谈话。我想我可以为你提供一份工作。[他向你伸出手。]我是贝尼西奥。}
#{502}{}{[Shake his hand.] }
{502}{}{[和他握手]}
#{503}{}{. What's the offer?}
{503}{}{。出价是多少？}
#{504}{}{I have no time for pleasantries, shorty. Get to the point.}
{504}{}{我没时间开玩笑，矮子。直说吧。}
#{550}{}{Working for the empire isn't a bad idea. If can you manage, you could earn a pretty sum. But if you really want to hit it big, there's only one person worth considering. [He lowers his voice.] Anonym.}
{550}{}{为帝国工作不是个坏主意，如果你能做到，你可以赚一大笔钱。但如果你真的想大干一场，只有一个人值得考虑。[他降低了声音。]匿名者。}
#{551}{}{Who are you and who is this Anonym?}
{551}{}{你是谁？这个匿名者是谁？}
#{552}{}{I don't believe a word of that. I'm not wasting any more time on you.}
{552}{}{我一个字也不相信。我不会再在你身上浪费时间了。}
#{600}{}{No need to be rude, I only want to help. Working for the empire isn't a bad idea. If can you manage, you could earn a pretty sum. But if you really want to hit it big, there's only one person worth considering. [He lowers his voice.] Anonym.}
{600}{}{别这么粗鲁，我只想帮忙。为帝国工作不是个坏主意，如果你能做到，你可以赚一大笔钱。但如果你真的想大干一场，只有一个人值得考虑。[他降低了声音。]匿名者。}
#{601}{}{Who is this Anonym?}
{601}{}{这位匿名者是谁？}
#{602}{}{I don't believe a word of that. I'm not wasting any more time on you.}
{602}{}{我一个字也不相信。我不会再在你身上浪费时间了。}
#{650}{}{I don't ask nosy questions about Anonym. I'd advise you to do the same. All you need to know is that nobody will pay you more. Decide for yourself. If you're interested, pay me a visit - I have a room rented here in the Wild Paradise.}
{650}{}{我不会问关于匿名者的八卦问题，我建议你也这样做。你需要知道的是没有人会给你更多的钱。自己决定吧，如果你有兴趣，来找我-我在狂野天堂租了一个房间。}
#{651}{}{I don't ask nosy questions about Anonym. I'd advise you to do the same. All you need to know is that nobody will pay you more. Decide for yourself. If you're interested, pay me a visit - I have a room rented here in the Wild Paradise.}
{651}{}{我不会问关于匿名者的八卦问题，我建议你也这样做。你需要知道的是没有人会给你更多的钱。自己决定吧，如果你有兴趣，来找我-我在狂野天堂租了一个房间。}
#{652}{}{I'll think about it.}
{652}{}{我会考虑的。}
#{700}{}{You're making a big mistake, but it's your decision. I won't bother you anymore. If you change your mind, pay me a visit - I have a room rented here in the Wild Paradise.}
{700}{}{你犯了个大错，但这是你的决定。我不会再打扰你了。如果你改变主意的话，就来找我吧-我在狂野天堂租了一个房间。}
#{701}{}{You're making a big mistake, but it's your decision. I won't bother you anymore. If you change your mind, pay me a visit - I have a room rented here in the Wild Paradise.}
{701}{}{你犯了个大错，但这是你的决定。我不会再打扰你了。如果你改变主意的话，就来找我吧-我在狂野天堂租了一个房间。}
#{702}{}{Goodbye.}
{702}{}{再见。}
#{750}{}{I knew you'd come. You won't regret this. Working for Anonym isn't easy, but it pays damn well.}
{750}{}{我就知道你会来的。你不会后悔的。为匿名者工作不容易，但报酬很高。}
#{751}{}{I hope so. Now tell me what he wants from me.}
{751}{}{希望如此。现在告诉我他想从我这里得到什么。}
#{752}{}{You're mistaken. I'm not going to work for him.}
{752}{}{你弄错了，我不会为他工作的。}
#{753}{}{Uh.}
{753}{}{呃。}
#{800}{}{Not so fast. First, I need to explain something. When you start working for Anonym, there's no going back. Maybe you think you'll just snoop around for a bit and bring the info straight to the empire for a nice paycheck - but that's not how it works! You won't hear anything from me that could harm Anonym. I'm just hired workforce - same as you will be. And I'll see to it that Anonym's contacts in the empire know that you're one of us. They'll make sure you won't be given any work where you could harm us. When you join Anonym, it's permanent. Are we clear on this?}
{800}{}{没那么快。首先，我需要解释一些事情。当你开始为匿名者工作的时候，就没有回头路了。也许你会认为你只需要四处窥探一下，然后把这些信息直接带到帝国，然后拿到一份不错的薪水——但这不是它的工作方式！你不会听到我的任何可能伤害匿名者的消息。我只是被雇佣的员工-和你一样。我会确保匿名者在帝国的联系人知道你是我们中的一员，他们会确保你不会得到任何可能伤害我们的工作。当你加入匿名组织时，就是永久性的，我们清楚了吗？}
#{801}{}{Not so fast. First, I need to explain something. When you start working for Anonym, there's no going back. Maybe you think you'll just snoop around for a bit and bring the info straight to the empire for a nice paycheck - but that's not how it works! You won't hear anything from me that could harm Anonym. I'm just hired workforce - same as you will be. And I'll see to it that Anonym's contacts in the empire know that you're one of us. They'll make sure you won't be given any work where you could harm us. When you join Anonym, it's permanent. Are we clear on this?}
{801}{}{没那么快。首先，我需要解释一些事情。当你开始为匿名者工作的时候，就没有回头路了。也许你会认为你只需要四处窥探一下，然后把这些信息直接带到帝国，然后拿到一份不错的薪水——但这不是它的工作方式！你不会听到我的任何可能伤害匿名者的消息。我只是被雇佣的员工-和你一样。我会确保匿名者在帝国的联系人知道你是我们中的一员，他们会确保你不会得到任何可能伤害我们的工作。当你加入匿名组织时，就是永久性的，我们清楚了吗？？}
#{802}{}{[Nod.] Tell me why we're both here then.}
{802}{}{[点头。] 告诉我为什么我们都在这里。}
#{803}{}{I don't like ultimatums. I refuse.}
{803}{}{我不喜欢最后通牒。我拒绝。}
#{850}{}{I like your attitude. The job requires someone who doesn't draw too much attention. A stranger that nobody knows. That's why I picked you.}
{850}{}{我喜欢你的态度。这项工作需要一个不会引起太多注意的人，最好是一个没有人认识的陌生人。这就是我选择你的原因。}
#{851}{}{Go on.}
{851}{}{继续。}
#{900}{}{What you need to do is get into the Imperial City and tell one of the Advisers that you're on Anonym's track. They'll interrogate you for a bit, and then you'll lead them to an abandoned house in the western Dead Quarter. When they ask about your source, tell them that you've overheard a few mercenaries talking over a drink in the Wild Paradise. You won't even be lying when you say you got the info here. [He grins slyly.] The imperial soldiers are getting pretty desperate, so it should be enough for them to dispatch a search party there. And that's exactly what we need. If you succeed, a nice fat reward will be waiting for you.}
{900}{}{你需要做的是进入帝国之城，告诉其中一位顾问你在追踪匿名者。他们会审问你一段时间，然后你会带他们去死区西部的一座废弃房子。当他们问起你的消息来源时，告诉他们你无意中听到一些雇佣兵在狂野天堂喝酒时的谈话。当你说你在这里得到信息时，你甚至不需要撒谎。[他狡黠地笑了笑。]帝国士兵已经非常绝望了，所以应该足够他们派遣一支搜索队去那里了。这正是我们所需要的。如果你成功了，将会有丰厚的奖励等着你。}
#{901}{}{What you need to do is get into the Imperial City and tell one of the Advisers that you're on Anonym's track. They'll interrogate you for a bit, and then you'll lead them to an abandoned house in the western Dead Quarter. When they ask about your source, tell them that you've overheard a few mercenaries talking over a drink in the Wild Paradise. You won't even be lying when you say you got the info here. [He grins slyly.] The imperial soldiers are getting pretty desperate, so it should be enough for them to dispatch a search party there. And that's exactly what we need. If you succeed, a nice fat reward will be waiting for you.}
{901}{}{你需要做的是进入帝国之城，告诉其中一位顾问你在追踪匿名者。他们会审问你一段时间，然后你会带他们去死区西部的一座废弃房子。当他们问起你的消息来源时，告诉他们你无意中听到一些雇佣兵在狂野天堂喝酒时的谈话。当你说你在这里得到信息时，你甚至不需要撒谎。[他狡黠地笑了笑。]帝国士兵已经非常绝望了，所以应该足够他们派遣一支搜索队去那里了。这正是我们所需要的。如果你成功了，将会有丰厚的奖励等着你。}
#{902}{}{I'm counting on that. Bye for now.}
{902}{}{我就指望这个了，再见。}
#{950}{}{Alright, but I've no idea why you came here then. Bye, buddy.}
{950}{}{好吧，但我不知道你为什么来这里。再见，朋友。}
#{951}{}{Alright, but I've no idea why you came here then. Bye, honey.}
{951}{}{好吧，但我不知道你为什么来这里。再见，朋友。}
#{952}{}{[Leave.]}
{952}{}{[离开。]}
#{1000}{}{Changed your mind? I can't think of any other reason why you're here again.}
{1000}{}{你改变了主意？我想不出还有什么别的原因能让你再来这里。}
#{1001}{}{Changed your mind? I can't think of any other reason why you're here again.}
{1001}{}{你改变了主意？我想不出还有什么别的原因能让你再来这里。}
#{1002}{}{I guess. Tell me what Anonym wants from me.}
{1002}{}{我想是吧。告诉我匿名者想从我这里得到什么。}
#{1003}{}{I accept your conditions. Now tell me what I'm supposed to do.}
{1003}{}{我接受你的条件。现在告诉我该怎么做。}
#{1004}{}{No way. Goodbye.}
{1004}{}{不可能。再见。}
#{1005}{}{Uh.}
{1005}{}{呃。}
#{1050}{}{A squad of soldiers has already been dispatched from the Imperial City. Looks like you've done your job well, and Anonym is very pleased with you. [He gives you 1000 caps.] He also sends further instructions.}
{1050}{}{帝国之城已经派出了一队士兵。看来你干得不错，匿名者对你很满意。[他给了你1000个瓶盖。]他还发出了下一步的指示。}
#{1051}{}{A squad of soldiers has already been dispatched from the Imperial City. Looks like you've done your job well, and Anonym is very pleased with you. [He gives you 1000 caps.] He also sends further instructions.}
{1051}{}{帝国之城已经派出了一队士兵。看来你干得不错，匿名者对你很满意。[他给了你1000个瓶盖。]他还发出了下一步的指示。}
#{1052}{}{I'm listening.}
{1052}{}{我在听。}
#{1100}{}{It seems that two things need to be taken care of at the same time. Anonym wanted the soldiers sent out so that he could kill them in the Dead Quarter and hit the empire in a sensitive spot. But he also needs to get rid of lieutenant Terrak here in the Wild Paradise. You only have time for one of those tasks, and I need to know which one it'll be. Are you able to fight when things get rough, or do you prefer more delicate matters?}
{1100}{}{似乎有两件事需要同时处理。匿名者想派出士兵，这样他就可以在死区杀死他们，并在一个敏感的地方打击帝国。但他也需要在狂野天堂除掉泰瑞克中尉。你只有时间完成其中一项任务，我需要知道是哪项任务。当事情变得棘手的时候，你能战斗吗？还是你更喜欢微妙的事情？}
#{1101}{}{It seems that two things need to be taken care of at the same time. Anonym wanted the soldiers sent out so that he could kill them in the Dead Quarter and hit the empire in a sensitive spot. But he also needs to get rid of lieutenant Terrak here in the Wild Paradise. You only have time for one of those tasks, and I need to know which one it'll be. Are you able to fight when things get rough, or do you prefer more delicate matters?}
{1101}{}{似乎有两件事需要同时处理。匿名者想派出士兵，这样他就可以在死区杀死他们，并在一个敏感的地方打击帝国，但他也需要在狂野天堂除掉泰瑞克中尉。你只有时间完成其中一项任务，我需要知道是哪项任务。当事情变得棘手的时候，你能战斗吗？还是你更喜欢微妙的事情？}
#{1102}{}{There's not a fight I couldn't live through. I'll take do first one.}
{1102}{}{没有我活不下去的战斗。我来做第一个。}
#{1103}{}{There's not a fight I couldn't live through. I'll take do first one.}
{1103}{}{没有我活不下去的战斗。我来做第一个。}
#{1104}{}{I'd rather handle the delicate matter.}
{1104}{}{我宁愿处理这个微妙的问题。}
#{1150}{}{Alright, but you better be ready for this, or you might lose your balls. We've planted explosives into the abandoned house you told the Advisers about. When the imperials get down into the cellar, the fuse will go off and all hell will break loose. But there's no guarantee that we'll get all of them - that's where you come in. As soon as we're done talking, you'll make your way to the Dead Quarter and check if they're all dead. And if they aren't, make them. And I'm sure I don't need to tell you how important this is to Anonym.}
{1150}{}{好吧，但你最好做好心理准备，否则你会失去你的蛋蛋。我们在你告诉顾问们的废弃房子里装了炸药。当帝国军进入地窖时，导火线就会点燃爆炸，一切都会失控。但不能保证我们会干掉所有的-这就是你要做的。我们一谈完，你就去死区看看他们是不是都死了。如果不是，就做吧。我相信不用我说你也知道这对匿名者有多重要。}
#{1151}{}{Alright, but you better be ready for this, or you might lose your head. We've planted explosives into the abandoned house you told the Advisers about. When the imperials get down into the cellar, the fuse will go off and all hell will break loose. But there's no guarantee that we'll get all of them - that's where you come in. As soon as we're done talking, you'll make your way to the Dead Quarter and check if they're all dead. And if they aren't, make them. And I'm sure I don't need to tell you how important this is to Anonym.}
{1151}{}{好吧，但你最好做好心理准备，否则你会失去你的蛋蛋。我们在你告诉顾问们的废弃房子里装了炸药。当帝国军进入地窖时，导火线就会点燃爆炸，一切都会失控。但不能保证我们会干掉所有的-这就是你要做的。我们一谈完，你就去死区看看他们是不是都死了。如果不是，就做吧。我相信不用我说你也知道这对匿名者有多重要。}
#{1152}{}{Anonym has nothing to fear. I can handle it.}
{1152}{}{匿名者没什么好害怕的，我能应付。}
#{1200}{}{OK, in that case it's clear. Talk to the lieutenant and make him leave Albuquerque - without resorting to violence. This matters a lot to Anonym. Terrak tries to keep to himself, but he's starting to know too much. He could start making problems after we get rid of the soldiers. And nobody needs that. I'd have him killed, but, as I'm sure you know, it's not that simple in the Wild Paradise. That's why you need to talk him into leaving.}
{1200}{}{好的，这样就很清楚了。和中尉谈谈，让他离开阿尔伯克基——不要诉诸暴力。这对匿名者来说很重要。泰瑞克试图保守秘密，但他知道的太多了。等我们除掉那些士兵，他就会开始制造麻烦。没人需要它。我想杀了他，但我相信你也知道，在狂野天堂可没那么简单。所以你才要劝他离开。}
#{1201}{}{OK, in that case it's clear. Talk to the lieutenant and make him leave Albuquerque - without resorting to violence. This matters a lot to Anonym. Terrak tries to keep to himself, but he's starting to know too much. He could start making problems after we get rid of the soldiers. And nobody needs that. I'd have him killed, but, as I'm sure you know, it's not that simple in the Wild Paradise. That's why you need to talk him into leaving.}
{1201}{}{好的，这样就很清楚了。和中尉谈谈，让他离开阿尔伯克基——不要诉诸暴力。这对匿名者来说很重要。泰瑞克试图保守秘密，但他知道的太多了。等我们除掉那些士兵，他就会开始制造麻烦。没人需要它。我想杀了他，但我相信你也知道，在狂野天堂可没那么简单。所以你才要劝他离开。}
#{1202}{}{Got it. Terrak will be leaving here with the first caravan.}
{1202}{}{明白了。泰瑞克会跟着一支商队离开这里。}
#{1250}{}{Well, what about the soldiers? Did they all bite the dust? I hope you realize we need to find out as soon as possible.}
{1250}{}{那么，士兵们呢？他们都死了吗？我希望你能意识到我们需要尽快查明真相。}
#{1251}{}{Don't worry, I'll see to it.}
{1251}{}{别担心，我会处理的。}
#{1252}{}{One of the soldiers survived the explosion, but I took care of him.}
{1252}{}{有个士兵在爆炸中活了下来，但我干掉了他。}
#{1253}{}{One of the soldiers survived the explosion, but I took care of him.}
{1253}{}{有个士兵在爆炸中活了下来，但我干掉了他。}
#{1300}{}{Terrak is gone. I don't know what you told him, but you must've been real convincing. Here's your money. [He gives you 2200 caps.] And that's all from me - I'm going to have to send you elsewhere. Anonym himself wants to see you.}
{1300}{}{泰瑞克消失了，我不知道你跟他说了什么，但你一定很有说服力。这是你的钱。[他给你2200个瓶盖。]这就是我的全部-我要送你到其他地方。匿名者要见你。}
#{1301}{}{Terrak is gone. I don't know what you told him, but you must've been real convincing. Here's your money. [He gives you 2200 caps.] And that's all from me - I'm going to have to send you elsewhere. Anonym himself wants to see you.}
{1301}{}{泰瑞克消失了，我不知道你跟他说了什么，但你一定很有说服力。这是你的钱。[他给你2200个瓶盖。]这就是我的全部-我要送你到其他地方。匿名者要见你。}
#{1302}{}{What does he need of me?}
{1302}{}{他需要我做什么？}
#{1350}{}{No idea. All I know is that he wants to meet you. Shit, buddy, I never saw him in my life. All I can tell you is the place you're supposed to meet him. He should be in be the northeast Dead Quarter right now. I'd head there immediately if I were you - Anonym doesn't like waiting.}
{1350}{}{不知道。我只知道他想见你。该死，伙计，我这辈子都没见过他。我只能告诉你你和他见面的地方，他现在应该在死区东北部。如果我是你，我会马上去那里-匿名者不喜欢等人。}
#{1351}{}{No idea. All I know is that he wants to meet you. Shit, honey, I never saw him in my life. All I can tell you is the place you're supposed to meet him. He should be in be the northeast Dead Quarter right now. I'd head there immediately if I were you - Anonym doesn't like waiting.}
{1351}{}{不知道。我只知道他想见你。该死，伙计，我这辈子都没见过他。我只能告诉你你和他见面的地方，他现在应该在死区东北部。如果我是你，我会马上去那里-匿名者不喜欢等人。}
#{1352}{}{Don't worry. Farewell, Benicio.}
{1352}{}{别担心。再见，贝尼西奥。}
#{1400}{}{Dammit man, look at yourself. You're completely fucked. I can't talk to you in that state. Fix yourself first and then come back, alright?}
{1400}{}{该死的，看看你自己，你他妈的完蛋了。我不能在那种状态下跟你说话。首先解决好自己然后回来，好吧？}
#{1401}{}{Dammit honey, look at yourself. You're completely fucked. I can't talk to you in that state. Fix yourself first and then come back, alright?}
{1401}{}{该死的，看看你自己，你他妈的完蛋了。我不能在那种状态下跟你说话。首先解决好自己然后回来，好吧？}
#{1402}{}{Burlek.}
{1402}{}{卟咳。}
#{1450}{}{[As soon as you enter the Dead Quarter you are surrounded by a group of armed men. The runt Benicio steps right before you.] Looks like this is the end for you, buddy. You picked the wrong side. Had you listened to me back in the Wild Paradise, things might have turned out differently. But it's too late for that now. Elisa wants to cover her tracks - nobody must learn that Anonym was her. That's why you must die. Any last words?}
{1450}{}{[你一进入死区，就被一群武装人员包围。小矮子贝尼西奥就站在你前面。]看来你要完蛋了，伙计。你选错边了。如果你在狂野天堂时听我的话，事情可能会变得不一样，但现在说已经太晚了。伊莉莎想掩盖她的踪迹-不能让任何人知道匿名者就是她。所以你必须死。有什么遗言吗？}
#{1451}{}{[As soon as you enter the Dead Quarter you are surrounded by a group of armed men. The runt Benicio steps right before you.] Looks like this is the end for you, honey. You picked the wrong side. Had you listened to me back in the Wild Paradise, things might have turned out differently. But it's too late for that now. Elisa wants to cover her tracks - nobody must learn that Anonym was her. That's why you must die. Any last words?}
{1451}{}{[你一进入死区，就被一群武装人员包围。小矮子贝尼西奥就站在你前面。]看来你要完蛋了，伙计。你选错边了。如果你在狂野天堂时听我的话，事情可能会变得不一样，但现在说已经太晚了。伊莉莎想掩盖她的踪迹-不能让任何人知道匿名者就是她。所以你必须死。有什么遗言吗？}
#{1452}{}{You sure talk big for a little guy. Guess I'll have to shut you up.}
{1452}{}{作为一个小矮子，你还真会说大话。看来我得让你闭嘴了。}
#{1453}{}{Elisa is Anonym? But everything was pointing to Aran.}
{1453}{}{伊莉莎就是匿名者？但一切都指向阿郎的。}
#{1454}{}{Hue?!}
{1454}{}{啊？！}
#{1455}{}{[As soon as you enter the Dead Quarter you are surrounded by a group of armed men. A midget with a sly face steps right before you.] Looks like this is the end for you, buddy. You picked the wrong side. Elisa wants to cover her tracks - nobody must learn that Anonym was her. That's why you must die. Any last words?}
{1455}{}{[你一进入死区，就被一群武装人员包围。一个满脸狡猾的侏儒站在你面前。]看来你要完蛋了，伙计。你选错边了。伊莉莎想掩盖她的踪迹-不能让任何人知道匿名者就是她。所以你必须死。有什么遗言吗？}
#{1456}{}{[As soon as you enter the Dead Quarter you are surrounded by a group of armed men. A midget with a sly face steps right before you.] Looks like this is the end for you, honey. You picked the wrong side. Elisa wants to cover her tracks - nobody must learn that Anonym was her. That's why you must die. Any last words?}
{1456}{}{[你一进入死区，就被一群武装人员包围。一个满脸狡猾的侏儒站在你面前。]看来你要完蛋了，伙计。你选错边了。伊莉莎想掩盖她的踪迹-不能让任何人知道匿名者就是她。所以你必须死。有什么遗言吗？}
#{1500}{}{[As soon as you enter the Dead Quarter you are surrounded by a group of armed men. The runt Benicio steps right before you.] Looks like this is the end for you, buddy. You picked the wrong side. Had you listened to me back in the Wild Paradise, things might have turned out differently. But it's too late for that now. Nobody kills our provider and gets away with it. That's why you must die. Any last words?}
{1500}{}{[你一进入死区，就被一群武装人员包围。小矮子贝尼西奥就站在你前面。]看来你要完蛋了，伙计。你选错边了。如果你在狂野天堂时听我的话，事情可能会变得不一样，但现在说已经太晚了。没人能杀了我们的供应商还能逍遥法外，所以你必须死。有什么遗言吗？}
#{1501}{}{[As soon as you enter the Dead Quarter you are surrounded by a group of armed men. The runt Benicio steps right before you.] Looks like this is the end for you, honey. You picked the wrong side. Had you listened to me back in the Wild Paradise, things might have turned out differently. But it's too late for that now. Nobody kills our provider and gets away with it. That's why you must die. Any last words?}
{1501}{}{[你一进入死区，就被一群武装人员包围。小矮子贝尼西奥就站在你前面。]看来你要完蛋了，伙计。你选错边了。如果你在狂野天堂时听我的话，事情可能会变得不一样，但现在说已经太晚了。没人能杀了我们的供应商还能逍遥法外，所以你必须死。有什么遗言吗？}
#{1502}{}{Elisa already got what she deserved. Now it's your turn.}
{1502}{}{伊莉莎已经得到了她应得的，现在轮到你了。}
#{1503}{}{Hue?!}
{1503}{}{哈？！}
#{1504}{}{[As soon as you enter the Dead Quarter you are surrounded by a group of armed men. A midget with a sly face steps right before you.] Looks like this is the end for you, buddy. You picked the wrong side. Nobody kills our provider and gets away with it. That's why you must die. Any last words?}
{1504}{}{[你一进入死区，就被一群武装人员包围。一个满脸狡猾的侏儒站在你面前。]看来你要完蛋了，伙计。你选错边了。没人能杀了我们的供应商还能逍遥法外，所以你必须死。有什么遗言吗？}
#{1505}{}{[As soon as you enter the Dead Quarter you are surrounded by a group of armed men. A midget with a sly face steps right before you.] Looks like this is the end for you, honey. You picked the wrong side. Nobody kills our provider and gets away with it. That's why you must die. Any last words?}
{1505}{}{[你一进入死区，就被一群武装人员包围。一个满脸狡猾的侏儒站在你面前。]看来你要完蛋了，伙计。你选错边了。没人能杀了我们的供应商还能逍遥法外，所以你必须死。有什么遗言吗？}
#{1550}{}{Fucking amazing work, I see I wasn't wrong about you. Here's your money. [He gives you 2200 caps.] And that's all from me - I'm going to have to send you elsewhere. Anonym himself wants to see you.}
{1550}{}{干得好，看来我没看错你。这是你的钱。[他给你2200个瓶盖。]这就是我的全部-我要送你到其他地方。匿名者要见你。}
#{1551}{}{What does he need of me?}
{1551}{}{他需要我做什么？}
#{1600}{}{I've heard that one of the soldiers survived the explosion. He already managed to tell the empire about it, too. You fucked up, and Anonym has no time to waste on incompetent idiots. Your job is over, and we never saw each other.}
{1600}{}{我听说有个士兵在爆炸中活了下来。他也已经把这件事告诉了帝国。你搞砸了，匿名者没有时间浪费在无能的白痴身上。你的工作结束了，我们从没见过面。}
#{1601}{}{I've heard that one of the soldiers survived the explosion. He already managed to tell the empire about it, too. You fucked up, and Anonym has no time to waste on incompetent idiots. Your job is over, and we never saw each other.}
{1601}{}{我听说有个士兵在爆炸中活了下来。他也已经把这件事告诉了帝国。你搞砸了，匿名者没有时间浪费在无能的白痴身上。你的工作结束了，我们从没见过面。}
#{1602}{}{[Leave.]}
{1602}{}{[离开。]}
#{1603}{}{You fucked up. Nobody tells me I'm incompetent, motherfucker!}
{1603}{}{你搞砸了。没人说我无能，混蛋！}
#{1604}{}{You fucked up. Nobody tells me I'm incompetent, motherfucker!}
{1604}{}{你搞砸了。没人说我无能，混蛋！}
#{1605}{}{Geh.}
{1605}{}{咯。}
#{1650}{}{[As soon as you enter the Dead Quarter you are surrounded by a group of armed men. The runt Benicio steps right before you.] I see you've worked your way up. Being Anonym's personal courier must make loads of money. I admire you buddy. [He grins.] But to get to what we're all here for. Got our caps?}
{1650}{}{[你一进入死区，就被一群武装人员包围。小矮子贝尼西奥就站在你前面。]我看你已经步步高升了。做"匿名者"的私人信使肯定能赚很多钱。我很佩服你，伙计。[他笑着说。]但是我们都在这里。拿到我们的钱了吗？}
#{1651}{}{[As soon as you enter the Dead Quarter you are surrounded by a group of armed men. The runt Benicio steps right before you.] I see you've worked your way up. Being Anonym's personal courier must make loads of money. I admire you honey. [He grins.] But to get to what we're all here for. Got our caps?}
{1651}{}{[你一进入死区，就被一群武装人员包围。小矮子贝尼西奥就站在你前面。]我看你已经步步高升了。做"匿名者"的私人信使肯定能赚很多钱。我很佩服你，伙计。[他笑着说。]但是我们都在这里。拿到我们的钱了吗？}
#{1652}{}{Eh... yes, I do. But how many caps are we talking about here?}
{1652}{}{呃...是的，我知道。但我们这里说的是多少瓶盖呢？}
#{1653}{}{You misunderstand. Anonym didn't send me here to pay you - he sent me here to kill you. And I'm sure you understand that I can't disappoint him.}
{1653}{}{你误会了。匿名者派我来不是为了给你钱- 他派我来杀了你。我相信你明白我不会让他失望的。}
#{1654}{}{You misunderstand. Anonym didn't send me here to pay you - he sent me here to kill you. And I'm sure you understand that I can't disappoint him.}
{1654}{}{你误会了。匿名者派我来不是为了给你钱- 他派我来杀了你。我相信你明白我不会让他失望的。}
#{1655}{}{I don't need caps. I come with nothing but some friendly advice. You and the other mercenaries should leave Albuquerque as soon as possible and never come back.}
{1655}{}{我不需要瓶盖。我只是来给你一些友好的建议。你和其他雇佣兵应该尽快离开阿尔伯克基，再也不要回来。}
#{1656}{}{Egh?! [After straining your brain for a while, you finally remember what Elisa asked you to do.] Shorty smash!}
{1656}{}{呃？！[你绞尽脑汁想了一会儿，终于想起来伊莉莎让你做什么了。]小矮子去死！}
#{1657}{}{Egh?! [After straining your brain for a while, you finally remember what Elisa asked you to do.] Shorty smash!}
{1657}{}{呃？！[你绞尽脑汁想了一会儿，终于想起来伊莉莎让你做什么了。]小矮子去死！}
#{1700}{}{Anonym promised us 4000 caps. And that's exactly how much we want. So quit yapping and give us our money.}
{1700}{}{匿名者承诺给我们4000瓶盖。这正是我们想要的。别废话了，把钱给我们。}
#{1701}{}{I don't want any trouble. Here's the sum that was agreed on.}
{1701}{}{我不想惹麻烦。这是双方商定的金额。}
#{1702}{}{The situation has changed. Anonym can't spare more than 2500 caps. I understand, it's not an optimal solution for you. [Look Benicio in the eyes.] But if you have any problems with that, you'll have to take them up to Anonym.}
{1702}{}{情况变了。“匿名者”最多只能留2500个大写字母。我明白，这不是你的最佳解决方案。[看着贝尼西奥的眼睛]但如果你对此有任何问题，你就得匿名告诉他们。}
#{1703}{}{That's too much. I think it'll be easier to just kill you all.}
{1703}{}{太过分了。我想杀了你们会更容易。}
#{1750}{}{[Benicio takes the caps.] That's how I like it. Now we can get away from this dying city. It was starting to get too hot here; the ghouls outside are getting more and more relentless, and the Hunters inside are getting more and more frustrated. [He signals the other mercenaries to leave.] Goodbye forever, buddy.}
{1750}{}{[贝尼西奥接过瓶盖]这就是我喜欢的。现在我们可以离开这个垂死的城市了。这里开始变得太热了；外面的僵尸越来越无情，里面的猎人越来越沮丧。[他示意其他雇佣兵离开]再见，伙计。}
#{1751}{}{[Benicio takes the caps.] That's how I like it. Now we can get away from this dying city. It was starting to get too hot here; the ghouls outside are getting more and more relentless, and the Hunters inside are getting more and more frustrated. [He signals the other mercenaries to leave.] Goodbye forever, honey.}
{1751}{}{[贝尼西奥接过瓶盖]这就是我喜欢的。现在我们可以离开这个垂死的城市了。这里开始变得太热了；外面的僵尸越来越无情，里面的猎人越来越沮丧。[他示意其他雇佣兵离开]再见，亲爱的。}
#{1752}{}{Goodbye, Benicio. I hope you don't croak somewhere in the wastes.}
{1752}{}{再见，贝尼西奥。我希望你不要在荒地里的某个地方呱呱叫。}
#{1800}{}{[Benicio stares at you for a while, but finally nods and accepts the caps.] OK, may Anonym choke on the rest. What matters is that we get out of this dying city. It was starting to get too hot here; the ghouls outside are getting more and more relentless, and the Hunters inside are getting more and more frustrated. [He signals the other mercenaries to leave.] Goodbye forever, buddy.}
{1800}{}{[贝尼西奥盯着你看了一会儿，但最后还是点了点头，接受了封盖]好吧，让阿莫尼奥窒息吧。重要的是我们要离开这个垂死的城市。这里开始变得太热了；外面的僵尸越来越无情，里面的猎人越来越沮丧。[他示意其他雇佣兵离开]再见，伙计。}
#{1801}{}{[Benicio stares at you for a while, but finally nods and accepts the caps.] OK, may Anonym choke on the rest. What matters is that we get out of this dying city. It was starting to get too hot here; the ghouls outside are getting more and more relentless, and the Hunters inside are getting more and more frustrated. [He signals the other mercenaries to leave.] Goodbye forever, honey.}
{1801}{}{[贝尼西奥盯着你看了一会儿，但最后还是点了点头，接受了封盖]好吧，让阿莫尼奥窒息吧。重要的是我们要离开这个垂死的城市。这里开始变得太热了；外面的僵尸越来越无情，里面的猎人越来越沮丧。[他示意其他雇佣兵离开]再见，亲爱的。}
#{1802}{}{Goodbye, Benicio. I hope you don't croak somewhere in the wastes.}
{1802}{}{再见，贝尼西奥。我希望你不要在荒地里的某个地方呱呱叫。}
#{1850}{}{[His smile freezes.] But that's not fair! We've done a lot of dirty work for Anonym, he can't just screw us over like this!}
{1850}{}{[他的微笑冻结]但这不公平！我们为匿名者做了很多肮脏的工作，他不能就这样把我们搞砸！}
#{1851}{}{Life isn't fair, Benicio. But don't worry, you're almost at its end. I'll see to that personally.}
{1851}{}{生活是不公平的，贝尼西奥。但别担心，你快完了。我会亲自处理的。}
#{1900}{}{[His smile freezes.] I can't say I like your little recommendation. Why would we want to do something like that?}
{1900}{}{我不能说我喜欢你的小建议。我们为什么要这样做？}
#{1901}{}{I'll share a little secret with you. As you might already know, Anonym was actually Adviser Elisa from the empire. Since we removed Adviser Aran out of her way, the whole imperial army is under her command. And now she wants to cover her tracks, anything that could prove her betrayal. That includes you and your pals. So either you disappear from the town, or she'll make you disappear. Got it?}
{1901}{}{我要和你分享一个小秘密。正如你可能已经知道的，匿名实际上是帝国的顾问。既然我们把阿兰顾问赶走了，整个帝国军队都在她的指挥之下。现在她想掩盖自己的行踪，任何能证明她背叛的东西。包括你和你的朋友。所以要么你从镇上消失，要么她会让你消失。知道了？}
#{1902}{}{I meant you well. But, if you're not going to listen, I'll just have to kill you and your friends.}
{1902}{}{我是认真的。但是，如果你不听，我就杀了你和你的朋友。}
#{1903}{}{I meant you well. But, if you're not going to listen, I'll just have to kill you and your friends.}
{1903}{}{我是认真的。但是，如果你不听，我就杀了你和你的朋友。}
#{1950}{}{[Benicio stares at you for a while, but in the end nods.] Alright. We wanted to get away from this dying city anyway. It was starting to get too hot here; the ghouls outside are getting more and more relentless, and the Hunters inside are getting more and more frustrated. We don't need even the imperial army on our backs. [He signals the other mercenaries to leave.] Goodbye forever, buddy.}
{1950}{}{[贝尼西奥盯着你看了一会儿，但最后还是点了点头]好吧。无论如何，我们都想离开这个垂死的城市。这里开始变得太热了；外面的僵尸越来越无情，里面的猎人越来越沮丧。我们甚至不需要帝国军队的支持。[他示意其他雇佣兵离开]再见，伙计。}
#{1951}{}{[Benicio stares at you for a while, but in the end nods.] Alright. We wanted to get away from this dying city anyway. It was starting to get too hot here; the ghouls outside are getting more and more relentless, and the Hunters inside are getting more and more frustrated. We don't need even the imperial army on our backs. [He signals the other mercenaries to leave.] Goodbye forever, honey.}
{1951}{}{[贝尼西奥盯着你看了一会儿，但最后还是点了点头]好吧。无论如何，我们都想离开这个垂死的城市。这里开始变得太热了；外面的僵尸越来越无情，里面的猎人越来越沮丧。我们甚至不需要帝国军队的支持。[他示意其他雇佣兵离开]再见，亲爱的。}
#{1952}{}{Goodbye, Benicio. I hope you don't croak somewhere in the wastes.}
{1952}{}{再见，贝尼西奥。我希望你不要在荒地里的某个地方呱呱叫。}
#{2000}{}{I heard you've been making trouble in the Imperial City. Working for the Anonym requires secrecy, we can't afford to have someone hunted by the empire among us. Get lost before you get me in trouble.}
{2000}{}{听说你在皇城闹事。为匿名者工作需要保密，我们不能让帝国在我们中间猎杀任何人。在你给我惹麻烦之前滚开。}
#{2001}{}{If you say so. Bye.}
{2001}{}{如果你这样说。再见。}
#{2002}{}{No way, you won't brush me off that easily, you bastard.}
{2002}{}{不可能，你不会那么容易就甩掉我的，你这个混蛋。}
#{2003}{}{Uf.}
{2003}{}{呃。}
