#{100}{}{You brush against an inconspicuous wire and set off a booby-trap. The following explosion destroys Chuck's goods completely.}
{100}{}{你碰到了一根不显眼的电线，然后引爆了一个陷阱。接下来的爆炸彻底摧毁了查克的货物。}
#{101}{}{You brush against an inconspicuous wire and set off a booby-trap. The following explosion destroys Chuck's goods completely.}
{101}{}{你碰到了一根不显眼的电线，然后引爆了一个陷阱。接下来的爆炸彻底摧毁了查克的货物。}
#{200}{}{You discovered a booby-trap connected to some explosives. Manipulating Chuck's goods in any way would likely lead to an explosion that would destroy everything.}
{200}{}{你发现了一个和炸药有关的陷阱，以任何方式翻动查克的货物都可能导致一场摧毁一切的爆炸。}
#{201}{}{You discovered a booby-trap connected to some explosives. Manipulating Chuck's goods in any way would likely lead to an explosion that would destroy everything.}
{201}{}{你发现了一个和炸药有关的陷阱，以任何方式翻动查克的货物都可能导致一场摧毁一切的爆炸。}
#{300}{}{The booby-trap is too sophisticated for your skills. You're unable to deactivate it safely.}
{300}{}{这个陷阱对你来说太复杂了。你无法安全地解除它。}
#{400}{}{Though it wasn't easy, you managed to deactivate the booby-trap in the end. Chuck's goods should be safely accessible now.}
{400}{}{虽然不容易，但你最终还是解除了陷阱。查克的货现在应该可以安全拿到了。}
