#{100}{}{You see a girl.}
{100}{}{你看到一个女孩。}
#{150}{}{You see Cindy.}
{150}{}{你看到了辛迪。}
#{200}{}{You see a scared looking young woman.}
{200}{}{你看到一个看起来很害怕的年轻女人。}
#{250}{}{You see Cindy. Her eyes are fixed on the ground and she's shivering in fear.}
{250}{}{你看到了辛迪。她的眼睛盯着地面，害怕得发抖。}
#{300}{}{The girl doesn't respond to you, merely quivers with fear.}
{300}{}{那女孩没有回应你，只是害怕得发抖。}
#{301}{}{Cindy doesn't respond to you, merely quivers with fear.}
{301}{}{辛迪没有回应你，只是害怕得发抖。}
#{500}{}{[The girl seems extremely afraid of you. You can see on her face that she'd like nothing more than to get out of here, but knows that she can't, so she at least tries to stay out of the reach of your hands.]}
{500}{}{[那女孩似乎非常害怕你。你可以从她的脸上看出，她只想离开这里，但她知道自己做不到，所以她至少尽量躲在你手够不着的地方。]}
#{501}{}{[Have sex with her.]}
{501}{}{[和她做爱。]}
#{502}{}{Cindy, you have to visit Vex from time to time, don't you?}
{502}{}{辛迪，你得时不时去看维克斯，对吧？}
#{503}{}{[Leave.]}
{503}{}{[离开。]}
#{550}{}{[She tries to get away, but you catch her easily. She immediately stops resisting, becoming almost lifeless. Sex with her is like sex with a blowup doll.]}
{550}{}{[她试图逃跑，但你很容易就抓住了她。她立刻停止反抗，变得几乎毫无生气。和她做爱就像和充气娃娃做爱一样。]}
#{551}{}{Cindy, you have to visit Vex from time to time, don't you?}
{551}{}{辛迪，你得时不时去看维克斯，对吧？}
#{552}{}{[Leave.]}
{552}{}{[离开。]}
#{600}{}{[She tries to get away, but you catch her easily. She immediately stops resisting, becoming almost lifeless. Sex with her is like sex with a blowup doll.]}
{600}{}{[她试图逃跑，但你很容易就抓住了她。她立刻停止反抗，变得几乎毫无生气。和她做爱就像和充气娃娃做爱一样。]}
#{601}{}{Cindy, you have to go to Vex from time to time, don't you?}
{601}{}{辛迪，你得时不时去看维克斯，对吧？}
#{602}{}{[Leave.]}
{602}{}{[离开。]}
#{650}{}{[Cindy starts to shake violently after hearing Vex's name.]}
{650}{}{[辛迪听到维克斯的名字后开始剧烈地颤抖。]}
#{651}{}{I know Vex is hurting you. I know it's hard, but I need to talk to you about him.}
{651}{}{我知道维克斯在伤害你。我知道这很难，但我需要和你谈谈他的事。}
#{652}{}{Look at me when I'm talking to you!}
{652}{}{我跟你说话的时候看着我！}
#{653}{}{I see there's no point in talking to you.}
{653}{}{我知道没必要跟你谈了。}
#{700}{}{[She doesn't respond, still quivering and staring at the ground.]}
{700}{}{[她没有回应，仍然颤抖着盯着地面。]}
#{701}{}{Cindy, what Vex is doing to you is wrong. It must end, you must stand up against him and make him stop hurting you.}
{701}{}{辛迪，维克斯对你做的事是不对的。这一切必须结束，你必须站起来反抗他，让他停止伤害你。}
#{750}{}{[Cindy hugs herself and speaks so quietly you almost don't hear her.] He won't let me.}
{750}{}{[辛迪抱着自己，轻声细语，你几乎听不到她说的话。]他不让我说。}
#{751}{}{It can't go on like this, Cindy. You have to kill him, there is no other option. Only then will you be free from him.}
{751}{}{不能再这样下去了，辛迪。你必须杀了他，别无他法。只有这样你才能摆脱他。}
#{800}{}{[Cindy hugs herself and speaks so quietly you almost don't hear her.] He won't let me.}
{800}{}{[辛迪抱住自己，轻声说话，你几乎听不到她说的话。]他不让我说。}
#{801}{}{It can't go on like this, Cindy. You have to kill him, there is no other option. Only then will you be free from him.}
{801}{}{不能再这样下去了，辛迪。你必须杀了他，别无选择。只有到那时你才能摆脱他。}
#{850}{}{[Whispers.] I can't.}
{850}{}{[低声说。]我不能。}
#{851}{}{Of course you can. When you're alone with him, stab him right in the chest when he's distracted. One quick stab and it will all be over.}
{851}{}{当然可以。当你和他独处的时候，趁他分心的时候刺他的胸口。只要一刺，一切就都结束了。}
#{900}{}{But...}
{900}{}{但是...}
#{901}{}{No buts, I know you can do it. If you do this and bring me his head, I'll buy you off Madame Chow and you'll be free. When are you supposed to see him again?}
{901}{}{没有但是，我知道你能做到。如果你能帮我把他的头带来，我就把你从乔夫人手里买回来，你就自由了。你什么时候能再见到他？}
#{950}{}{[She raises her head and looks at you, eyes full of tears.] Tonight.}
{950}{}{[她抬起头看着你，眼里满是泪水。]今晚。}
#{951}{}{Then do it tonight and you can finally be free. Nobody will touch you again. We'll meet at midnight between Wild Paradise and the weapons shop, alright?}
{951}{}{那就今晚行动，你就能重获自由了。没人会再碰你。我们午夜在狂野天堂和武器商店之间见面，好吗？}
#{952}{}{[She raises her head and looks at you, eyes full of tears.] Tomorrow night.}
{952}{}{[她抬起头看着你，眼里充满了泪水。]明天晚上。}
#{953}{}{Then do it tomorrow night and you can finally be free. Nobody will touch you again. We'll meet at midnight between Wild Paradise and the weapons shop, alright?}
{953}{}{明晚动手你就能重获自由了。我们午夜在狂野天堂和武器商店之间见面，好吗？}
#{1000}{}{[Cindy nods. She still seems afraid, but you can see determination in her eyes.]}
{1000}{}{[辛迪点头。她看起来仍然很害怕，但你可以从她的眼神中看出她的决心。]}
#{1001}{}{[Leave.]}
{1001}{}{[离开。]}
#{1050}{}{[She slowly raises her head, but she's still staring at the ground and shaking with fear.]}
{1050}{}{[她慢慢抬起头，但她仍然盯着地面，害怕得发抖。]}
#{1051}{}{[Shout.] I want you to kill Vex and bring me his head!}
{1051}{}{[大喊。]我要你杀了维克斯，把他的头带给我！}
#{1100}{}{[She covers her ears and starts sobbing.] No... He'll kill me.}
{1100}{}{[她捂住耳朵开始抽泣。]不... 他会杀了我的。}
#{1101}{}{[Quickly grab her hands and tear them off her ears.] And if you don't try, *I* will kill you! Right here, right now. Painfully. When are you supposed to see him next?}
{1101}{}{[迅速抓住她的手，从她的耳朵上拉下来。]如果你不试试，*我*会杀了你！就在此时此地。会非常痛苦的。你下次什么时候见他？}
#{1150}{}{[Tears start streaming down her face, but she doesn't resist.] Tonight.}
{1150}{}{[眼泪开始顺着她的脸流下来，但她没有反抗。]今晚。}
#{1151}{}{Excellent. When you're alone with him tonight, stab him in the heart when he's distracted. Then you'll cut off his head and bring it to me. We'll meet at midnight between Wild Paradise and the weapons shop, GOT IT?!}
{1151}{}{太好了。当你今晚单独和他在一起的时候，趁他分心的时候刺他的心脏。然后你就把他的头砍下来带给我。我们午夜在狂野天堂和武器商店之间见面，明白吗？！}
#{1152}{}{[Tears start streaming down her face, but she doesn't resist.] Tomorrow night.}
{1152}{}{[眼泪开始顺着她的脸流下来，但她没有反抗。]明天晚上。}
#{1153}{}{Excellent. When you're alone with him tomorrow night, stab him in the heart when he's distracted. Then you'll cut off his head and bring it to me. We'll meet at midnight between Wild Paradise and the weapons shop, GOT IT?!}
{1153}{}{太好了。明晚你和他单独在一起的时候，趁他分心的时候刺他的心脏。然后你就把他的头砍下来带给我。我们午夜在狂野天堂和武器商店之间见面，明白吗？！}
#{1200}{}{[She nods resignedly.]}
{1200}{}{[她顺从地点头。]}
#{1201}{}{And don't your dare disappoint me, or I'll make you regret it.}
{1201}{}{别让我失望，不然我会让你后悔的。}
