#{100}{}{You see a soldier.}
{100}{}{你看到一个士兵。}
#{200}{}{You see an imperial soldier.}
{200}{}{你看到一个帝国士兵。}
#{300}{}{Report, I can't hear anything!}
{300}{}{报告，我什么都听不见！}
#{301}{}{What the fuck happened?!}
{301}{}{他妈的发生了什么？！}
#{302}{}{Fucking trap!}
{302}{}{他妈的陷阱！}
#{303}{}{Dead, they're all dead.}
{303}{}{死了，他们都死了。}
#{304}{}{Someone else must've survived.}
{304}{}{肯定还有其他人活了下来。}
#{400}{}{Hey, you! You must be the one responsible. You're Anonym's underling!}
{400}{}{嘿，你！你一定是该负责的人。你是匿名者的属下！}
#{401}{}{Hey, you! You must be the one responsible. You're Anonym's underling!}
{401}{}{嘿，你！你一定是该负责的人。你是匿名者的属下！}
