#{100}{}{You see a soldier.}
{100}{}{你看到一个士兵。}
#{200}{}{You see an imperial soldier.}
{200}{}{你看到一个帝国士兵。}
#{500}{}{Mission accomplished.}
{500}{}{任务完成。}
#{501}{}{It's over, the traitor is dead.}
{501}{}{结束了，叛徒死了。}
#{502}{}{Time to get out of here.}
{502}{}{该离开这里了。}
#{550}{}{Death to the traitor!}
{550}{}{处死叛徒！}
#{551}{}{We can handle this.}
{551}{}{我们能处理的。}
#{552}{}{I've got your back.}
{552}{}{我支持你。}
#{600}{}{We surrender! We'll accept any punishment.}
{600}{}{我们投降！我们愿意接受任何惩罚。}
#{4000}{}{The traitor is dead. The empire is saved.}
{4000}{}{叛徒已经死了。帝国得救了。}
#{4050}{}{The old emperor has fallen. Long live emperor Aran.}
{4050}{}{老皇帝下台了，阿郎皇帝万岁。}
#{4100}{}{All hail Aran.}
{4100}{}{阿郎万岁。}
