#{100}{}{You see a soldier.}
{100}{}{你看到一个士兵。}
#{200}{}{You see a soldier guarding a gate.}
{200}{}{你看到一个守卫大门的士兵。}
#{300}{}{Welcome to the empire.}
{300}{}{欢迎来到帝国。}
#{301}{}{Welcome to the empire.}
{301}{}{欢迎来到帝国。}
#{302}{}{Leave.}
{302}{}{离开。}
#{303}{}{Go away.}
{303}{}{走开。}
#{304}{}{Welcome back, Miss Lystra.}
{304}{}{欢迎回来，莱斯特拉小姐。}
#{305}{}{Miss Lystra may enter the City anytime. As may members of her entourage.}
{305}{}{莱斯特拉小姐随时可以进城，她的随从也一样。}
#{310}{}{The emperor has decreed that you are free to enter the City as you please. I will keep you no more.}
{310}{}{皇帝已经下令，你可以随意进入城里。我不会再耽搁你了。}
#{311}{}{The empress has decreed that you are free to enter the City as you please. I will keep you no more.}
{311}{}{女王下令，你们可以随意进入城里。我不会再耽搁你了。}
#{312}{}{Long live the new emperor.}
{312}{}{新皇帝万岁。}
#{313}{}{Long live the new empress.}
{313}{}{新女王万岁。}
#{314}{}{Nothing will stop us now that Anonym has fallen.}
{314}{}{匿名者已经垮台了，没有什么能阻止我们。}
#{315}{}{The imperial army will not bow before any threat.}
{315}{}{帝国军队不会屈服于任何威胁。}
#{316}{}{The empire is the last hope for the survival of humanity.}
{316}{}{帝国是人类生存的最后希望。}
#{317}{}{Long live the new emperor.}
{317}{}{新皇帝万岁。}
#{330}{}{Get lost. You're no longer welcome in the empire.}
{330}{}{滚开。帝国不再欢迎你了。}
#{331}{}{Get lost. You're no longer welcome in the empire.}
{331}{}{滚开。帝国不再欢迎你了。}
#{400}{}{You've brought this on yourself. Now you must die.}
{400}{}{这是你自找的。现在你必须死。}
#{401}{}{You've brought this on yourself. Now you must die.}
{401}{}{这是你自找的。现在你必须死。}
#{402}{}{For the emperor!}
{402}{}{为了皇帝！}
#{403}{}{For the empress!}
{403}{}{为了女王！}
#{500}{}{Greetings, stranger. What brings you before the gate to the Imperial City?}
{500}{}{你好，陌生人。什么风把你吹到帝国之城门口来了？}
#{501}{}{Greetings, stranger. What brings you before the gate to the Imperial City?}
{501}{}{你好，陌生人。什么风把你吹到帝国之城门口来了？}
#{502}{}{Gate? I thought we were already inside the city.}
{502}{}{大门？我以为我们已经进城了。}
#{503}{}{Gate? I thought we were already inside the city.}
{503}{}{大门？我以为我们已经进城了。}
#{504}{}{I'd like to enter.}
{504}{}{我想进去。}
#{505}{}{I'd like to enter.}
{505}{}{我想进去。}
#{506}{}{I have important information for the Advisers. You must let me in immediately.}
{506}{}{我有重要消息要告诉顾问们。你必须马上让我进去。}
#{507}{}{Nothing at all. Goodbye.}
{507}{}{没什么。再见。}
#{508}{}{Burghl bul?}
{508}{}{伯格 白？}
#{550}{}{Don't be deceived, you've only seen the ruins of the former metropolis so far. The real civilization starts in the empire itself. Under the leadership of our wise emperor Myzrael, we're trying to maintain the technology and values of old. That is our task, as descendants of the Vault dwellers.}
{550}{}{别被骗了，到目前为止，你只看到了前大都市的废墟。真正的文明始于帝国本身。在我们英明的米泽列皇帝的领导下，我们正努力保持古老的技术和价值观。作为避难所居民的后代，这是我们的任务。}
#{551}{}{Don't be deceived, you've only seen the ruins of the former metropolis so far. The real civilization starts in the empire itself. Under the leadership of our wise emperor Myzrael, we're trying to maintain the technology and values of old. That is our task, as descendants of the Vault dwellers.}
{551}{}{别被骗了，到目前为止，你只看到了前大都市的废墟。真正的文明始于帝国本身。在我们英明的米泽列皇帝的领导下，我们正努力保持古老的技术和价值观。作为避难所居民的后代，这是我们的任务。}
#{552}{}{I doubt that the people of Albuquerque see it the same way.}
{552}{}{我怀疑阿尔伯克基的人也这么看。}
#{553}{}{I see. In that case, I'd like to visit your City.}
{553}{}{我明白了。那样的话，我想去参观你们的城市。}
#{554}{}{I see. In that case, I'd like to visit your City.}
{554}{}{我明白了。那样的话，我想去参观你们的城市。}
#{555}{}{Good luck with that. Bye.}
{555}{}{祝你好运。再见。}
#{600}{}{I can believe that. Unfortunately, the entrance to the Imperial City is strictly regulated. I can only let you in with an official invitation from one of the dwellers. Do you have one?}
{600}{}{我相信这一点。不幸的是，进入帝国之城是受到严格管制的。只有收到居民的正式邀请我才能让你进去。你有吗？}
#{601}{}{Very well. Do you have an invitation?}
{601}{}{很好。你有邀请函吗？}
#{602}{}{Not exactly, I was sent here by lieutenant Terrak. I'm supposed to see Adviser Elisa for work.}
{602}{}{不完全是，我是泰瑞克中尉派来的。我要去见伊莉莎顾问。}
#{603}{}{I have an invitation from Adviser Elisa.}
{603}{}{我收到了伊莉莎顾问的邀请。}
#{604}{}{I was invited by private Brad Sneed.}
{604}{}{我收到了二等兵布拉德·斯内德的邀请。}
#{605}{}{I was invited by private Brad Sneed.}
{605}{}{我收到了二等兵布拉德·斯内德的邀请。}
#{606}{}{Lorain Velasquez invited me.}
{606}{}{洛雷恩·维拉斯克斯邀请了我。}
#{607}{}{There's no time for that. I have important information for the Advisers. You must let me in!}
{607}{}{没时间了。我有重要消息要告诉顾问们。你必须让我进去！}
#{608}{}{No, nobody invited me.}
{608}{}{不，没人邀请我。}
#{609}{}{I have an invitation from empress Elisa.}
{609}{}{我收到了伊莉莎女王的邀请。}
#{650}{}{I'm sorry, but I simply cannot let you into the City without an invitation.}
{650}{}{很抱歉，但没有邀请我不能让你进城。}
#{651}{}{I'm sorry, but I simply cannot let you into the City without an invitation.}
{651}{}{很抱歉，但没有邀请我不能让你进城。}
#{652}{}{I respect your adherence to the law, but this is an exceptional case. You must understand that this is a matter of utmost urgency. For it concerns... [Lean close to him and whisper.] the Anonym. If you do not let me see the Advisers immediately, you could place the whole empire in great danger. Do you want that on your conscience?}
{652}{}{我尊重你遵守法律，但这是一个特殊情况。你必须明白这是非常紧急的事情。因为它涉及到……[靠向他耳语。]匿名者。如果你不让我马上见顾问们，整个帝国就会陷入巨大的危险。你想良心不安吗？}
#{653}{}{I respect your adherence to the law, but this is an exceptional case. You must understand that this is a matter of utmost urgency. For it concerns... [Lean close to him and whisper.] the Anonym. If you do not let me see the Advisers immediately, you could place the whole empire in great danger. Do you want that on your conscience?}
{653}{}{我尊重你遵守法律，但这是一个特殊情况。你必须明白这是非常紧急的事情。因为它涉及到……[靠向他耳语。]匿名者。如果你不让我马上见顾问们，整个帝国就会陷入巨大的危险。你想良心不安吗？？}
#{654}{}{But I really need to talk to them.}
{654}{}{但我真的需要和他们谈谈。}
#{655}{}{As you wish. Goodbye.}
{655}{}{如你所愿。再见。}
#{700}{}{The laws are clear. I refuse to talk about this any longer.}
{700}{}{法律很明确。我不想再谈这个了。}
#{701}{}{If you won't let me in, I'll just let myself in. Out of my way!}
{701}{}{如果你不让我进去，我就让自己进去。让开！}
#{702}{}{If you won't let me in, I'll just let myself in. Out of my way!}
{702}{}{如果你不让我进去，我就让自己进去。让开！}
#{703}{}{If you say so. Bye.}
{703}{}{既然你这么说。再见。}
#{750}{}{I'm sorry, but I don't understand you. Come back when you're feeling better.}
{750}{}{对不起，我不明白你的意思。等你感觉好些了再来吧。}
#{751}{}{Humph!}
{751}{}{哈哼！}
#{800}{}{It doesn't matter how they see it. They can't possibly understand our efforts here. One day, they will thank us.}
{800}{}{他们怎么看并不重要。他们不可能理解我们的努力。总有一天，他们会感谢我们的。}
#{801}{}{You can't be serious.}
{801}{}{你不是认真的吧。}
#{802}{}{Whatever. I'd like to enter the empire.}
{802}{}{管他呢。我想进入帝国。}
#{803}{}{Whatever. I'd like to enter the empire.}
{803}{}{管他呢。我想进入帝国。}
#{804}{}{Sure. I'll be going now.}
{804}{}{当然。现在我要走了。}
#{850}{}{I see you don't understand. Let's not talk about this anymore. It's not my place to discuss the laws of the empire, only to obey them.}
{850}{}{我看你不明白。我们不要再谈这个了。我无权讨论帝国的法律，我只负责遵守。}
#{851}{}{As you wish. I'd like to enter the empire.}
{851}{}{如你所愿。我想进入帝国。}
#{852}{}{As you wish. I'd like to enter the empire.}
{852}{}{如你所愿。我想进入帝国。}
#{853}{}{In that case we have nothing to say to each other. Goodbye.}
{853}{}{那样的话，我们就没有什么好说的了。再见。}
#{900}{}{I'm sorry, but that's not enough. Lieutenant Terrak and the likes of him may find breaking rules completely normal, but I am not going to support such behavior. I will not let you enter the City without a proper invitation.}
{900}{}{我很抱歉，但这还不够。泰瑞克中尉和像他这样的人可能会觉得违反规则完全正常，但我不会支持这种行为。没有正式的邀请我是不会让你进城的。}
#{901}{}{I respect your adherence to the law, but this is an exceptional case. The lieutenant had a very good reason for breaking the protocol. For the matter concerns... [Lean close to him and whisper.] the Anonym. If you do not let me see Adviser Elisa immediately, you could place the whole empire in great danger. Do you want that on your conscience?}
{901}{}{我尊重你遵守法律，但这是一个特殊情况。中尉有充分的理由违反规定。关于……[靠向他耳语。]匿名者。如果你不让我马上见伊莉莎顾问，整个帝国就会陷入巨大的危险。你想为此感到良心不安吗？}
#{902}{}{I respect your adherence to the law, but this is an exceptional case. The lieutenant had a very good reason for breaking the protocol. For the matter concerns... [Lean close to him and whisper.] the Anonym. If you do not let me see Adviser Elisa immediately, you could place the whole empire in great danger. Do you want that on your conscience?}
{902}{}{我尊重你遵守法律，但这是一个特殊情况。中尉有充分的理由违反规定。关于……[靠向他耳语。]匿名者。如果你不让我马上见伊莉莎顾问，整个帝国就会陷入巨大的危险。你想为此感到良心不安吗？}
#{903}{}{But Terrak said that mentioning his name would be enough. Come on, it's no big deal, is it?}
{903}{}{但泰瑞克说，提到他的名字就足够了。得了吧，没什么大不了的，不是吗？}
#{904}{}{Got it. I'll be going now.}
{904}{}{明白了。现在我要走了。}
#{950}{}{[He looks into his Pip-Boy.] Yes, the invitation in her name is here and the description fits. I will open the gate for you then.}
{950}{}{[他看着他的哔哔小子。]是的，这里有她名字的邀请函，描述也符合。我将为你打开大门。}
#{951}{}{Thanks. Later.}
{951}{}{谢谢。以后再说。}
#{1000}{}{[He looks into his Pip-Boy.] I'm sorry, but you must be mistaken, there is no invitation in her name. Also, Elisa is no longer an Adviser, she's been crowned an empress. Please, do address her properly.}
{1000}{}{[他看着他的哔哔小子。]对不起，你一定搞错了，没有以她的名义发出的邀请函。此外，伊莉莎不再是顾问，她被加冕为女王。请一定要正确称呼她。}
#{1002}{}{Elisa is an empress? How did that happen?}
{1002}{}{伊莉莎是女王？这是怎么回事？}
#{1003}{}{Of course. Bye.}
{1003}{}{当然可以。再见。}
#{1050}{}{[He looks into his Pip-Boy.] Alright, the invitation in that name is here and the description fits. I'll open the gate right away.}
{1050}{}{[他看着他的哔哔小子。]好的，这个名字的邀请函在这里，描述也符合。我马上把门打开。}
#{1051}{}{Thanks. Later.}
{1051}{}{谢谢。以后再说。}
#{1100}{}{In that case, you may not enter the City. Only by obeying the law can we ensure the safety of the dwellers and allow them to work in peace.}
{1100}{}{那样的话，你就不能进城了。只有遵守法律，我们才能确保居民的安全，让他们安心工作。}
#{1101}{}{No need to exaggerate. How much do you want for forgetting about those laws of yours just this once?}
{1101}{}{不必夸大其词。就这一次，你忘了你的那些法律，你想要多少？}
#{1102}{}{Got it. I'm leaving.}
{1102}{}{明白了。我要走了。}
#{1150}{}{I know what you're trying to do. But you cannot bribe an imperial soldier. Without an invitation, you are simply not getting into the City.}
{1150}{}{我知道你想干什么。但你不能贿赂帝国士兵。没有邀请，你根本进不了这座城市。}
#{1151}{}{Then I have no choice but to resort to violence.}
{1151}{}{那我就只能诉诸暴力了。}
#{1152}{}{If you say so. Bye.}
{1152}{}{如果你这么说。再见。}
#{1200}{}{Emperor Myzrael died. Peacefully, according to those that were with him. Elisa, being his closest relative, became his rightful successor.}
{1200}{}{米泽列皇帝死了。据和他在一起的人说，很平静。伊莉莎作为他的至亲，成为了他的合法继承人。}
#{1201}{}{Thanks for the info. Now get out of my way before I rip you a new one!}
{1201}{}{谢谢你提供的信息。现在给我闪开，不然我就把你撕成碎片！}
#{1202}{}{I see. Goodbye then.}
{1202}{}{我明白了。再见了。}
#{1250}{}{What brings you here this time?}
{1250}{}{什么风把你吹来了？}
#{1251}{}{I'd like to enter the Imperial City.}
{1251}{}{我想去帝国之城。}
#{1252}{}{I'd like to enter the Imperial City.}
{1252}{}{我想去帝国之城。}
#{1253}{}{You must let me into the empire. I have important information for the Advisers.}
{1253}{}{你必须让我进入帝国。我有重要消息要告诉顾问们。}
#{1254}{}{Nothing really. I'm leaving.}
{1254}{}{没什么。我要走了。}
#{1255}{}{Uh.}
{1255}{}{呃。}
#{1300}{}{[He looks into his Pip-Boy.] Yes, the invitation in her name is here and the description fits. I will open the gate for you then. However, you should know that Elisa is no longer an Adviser, she's been crowned an empress. Please, do address her properly.}
{1300}{}{[他看着他的哔哔小子。]是的，这里有她名字的邀请函，描述也符合。我将为你打开大门。不过，你要知道伊莉莎不再是顾问了，她被加冕为女王。请一定要正确称呼她。}
#{1301}{}{[He looks into his Pip-Boy.] Yes, the invitation in her name is here and the description fits. I will open the gate for you then. However, you should know that Elisa is no longer an Adviser, she's been crowned an empress. Please, do address her properly.}
{1301}{}{[他看着他的哔哔小子。]是的，这里有她名字的邀请函，描述也符合。我将为你打开大门。不过，你要知道伊莉莎不再是顾问了，她被加冕为女王。请一定要正确称呼她。}
#{1302}{}{Elisa is an empress? How did that happen?}
{1302}{}{伊莉莎是女王？这是怎么回事？}
#{1303}{}{Sure. Later.}
{1303}{}{当然。以后再说。}
#{1350}{}{Emperor Myzrael died. Peacefully, according to those that were with him. Elisa, being his closest relative, became his rightful successor.}
{1350}{}{米泽列皇帝死了。据和他在一起的人说，很平静。伊莉莎作为他的至亲，成为了他的合法继承人。}
#{1351}{}{Thanks for the info. Farewell.}
{1351}{}{谢谢你的信息。再见。}
#{1400}{}{[Fear flashes in his eyes.] Ehh, I mean, of course not. My task is to protect the empire. I would never do anything that could threaten it. I... I will let you in. But this won't happen again. Next time, please, get yourself a proper invitation. It is important to follow the rules in any situation.}
{1400}{}{[恐惧在他的眼中闪过。]嗯，我的意思是，当然不是。我的任务是保护帝国。我绝不会做任何可能威胁到它的事。我…我会让你进去的。但这种事不会再发生了。下次，请给自己弄份正式的请柬。在任何情况下遵守规则都是重要的。}
#{1401}{}{You are completely right.}
{1401}{}{你是完全正确的。}
#{1450}{}{Before I open the gate, allow me to give you some basic instructions. While you're inside the City, you should keep your weapons holstered and avoid bothering the dwellers. Not doing so is considered extremely rude. Should you have any questions, ask one of the information robots. Answering questions about the empire is their primary function. But only address one of the dwellers when you have a reason to do so. Every one of them has an important task to do for the benefit of the City and shouldn't be disturbed unnecessarily.}
{1450}{}{在我打开大门之前，请允许我给你一些基本的指示。当你在城里的时候，你应该把你的武器放在枪套里避免打扰居民。不这样做会被认为是非常粗鲁的。如果你有任何问题，可以问其中一个信息机器人。回答有关帝国的问题是他们的主要职能。但只有当你有理由这样做的时候，你才可以这样做。为城市的利益，他们每一个人都有重要的任务要做，不应该被不必要的事情打扰。}
#{1451}{}{Before I open the gate, allow me to give you some basic instructions. While you're inside the City, you should keep your weapons holstered and avoid bothering the dwellers. Not doing so is considered extremely rude. Should you have any questions, ask one of the information robots. Answering questions about the empire is their primary function. But only address one of the dwellers when you have a reason to do so. Every one of them has an important task to do for the benefit of the City and shouldn't be disturbed unnecessarily.}
{1451}{}{在我打开大门之前，请允许我给你一些基本的指示。当你在城里的时候，你应该把你的武器放在枪套里避免打扰居民。不这样做会被认为是非常粗鲁的。如果你有任何问题，可以问其中一个信息机器人。回答有关帝国的问题是他们的主要职能。但只有当你有理由这样做的时候，你才可以这样做。为城市的利益，他们每一个人都有重要的任务要做，不应该被不必要的事情打扰。}
#{1452}{}{Understood. I really need to get inside now, though.}
{1452}{}{理解。不过我现在真的得进去了。}
