#{100}{}{You see a soldier.}
{100}{}{你看到一个士兵。}
#{200}{}{You see an imperial soldier.}
{200}{}{你看到一个帝国士兵。}
#{300}{}{Don't dawdle, stranger.}
{300}{}{别磨蹭了，陌生人。}
#{301}{}{Don't do anything stupid, we're watching you.}
{301}{}{别做傻事，我们看着你呢。}
#{302}{}{Try to behave properly.}
{302}{}{尽量举止得体。}
#{303}{}{You try anything stupid, we take you out.}
{303}{}{你敢做傻事，我们就干掉你。}
#{304}{}{Don't bother the dwellers. Or me.}
{304}{}{不要打扰我和居民。}
#{305}{}{We're trained to protect the empire and its dwellers. And we're damn good at it.}
{305}{}{我们被训练来保护帝国和它的居民。我们非常擅长这个。}
#{306}{}{Don't stay in the City longer than you need to. For the good of us both.}
{306}{}{为了我们俩好，别在城里待得太久。}
#{307}{}{If I have to, I can put you down immediately.}
{307}{}{如果有必要，我可以马上把你“安顿”下来。}
#{308}{}{No need to stop here.}
{308}{}{不要停在这里。}
#{309}{}{They've let you into the City, but that doesn't mean you can do whatever you like. You'd best keep that in mind.}
{309}{}{他们让你进城，但这并不意味着你可以为所欲为。你最好记住这一点。}
#{310}{}{No uncivilized behavior. I don't want to have to interfere.}
{310}{}{没有不文明的行为。我不想干涉你的事。}
#{311}{}{If you have questions, keep them to yourself. Or find an information robot.}
{311}{}{如果你有任何问题，请自行解决。或者找个信息机器人。}
#{312}{}{I'm not here to entertain you. We've got no reason to talk.}
{312}{}{我不是来招待你的，我们没有理由交谈。}
#{313}{}{This isn't the wasteland, so behave accordingly.}
{313}{}{这不是荒原，所以要守规矩。}
#{314}{}{Don't get used to this place too much.}
{314}{}{不习惯这个地方太多了。}
#{315}{}{Don't dawdle, stranger.}
{315}{}{别磨蹭了，陌生人。}
#{316}{}{Where did *you* get power armor?}
{316}{}{*你*从哪里得到动力装甲？}
#{317}{}{Aren't you supposed to be hunting mutants somewhere?}
{317}{}{你不是应该在某个地方猎杀变种人吗？}
#{318}{}{A Mutant Hunter, here? You do one little thing we don't like and you're dead.}
{318}{}{一个变种猎人，在这儿？你要是做了一点我们不喜欢的事，你就死定了。}
#{319}{}{You Mutant Hunters should stay away from our City.}
{319}{}{你们变种猎人应该离我们的城市远点。}
#{320}{}{We don't need you here, Hunter. We'll manage just fine without you.}
{320}{}{我们不需要你在这里，猎人。没有你我们也能行。}
#{321}{}{Did you exterminate all the mutants already? You should get on with it.}
{321}{}{你把变种人都消灭了吗？你应该继续做下去。}
#{322}{}{You won't find anything here. Go back to your base.}
{322}{}{你在这里什么也找不到。回你的基地去。}
#{323}{}{You Hunters have no discipline. No wonder Rebirth still threatens Albuquerque.}
{323}{}{你们猎人没有纪律。难怪“重生”仍然威胁着阿尔伯克基。}
#{324}{}{I hope you've got a damn good reason to be here. If not, I'd *love* to escort you away.}
{324}{}{我希望你来这里有充分的理由。如果没有，我很愿意护送你离开。}
#{325}{}{Long live emperor Myzrael!}
{325}{}{米泽列皇帝万岁！}
#{326}{}{Long live emperor Aran!}
{326}{}{阿郎皇帝万岁！}
#{327}{}{Long live empress Elisa!}
{327}{}{伊莉莎女王万岁！}
#{330}{}{So you're THAT foreigner.}
{330}{}{所以你就是那个外国人。}
#{331}{}{I bet you've never seen anything like the Vault in your life.}
{331}{}{我敢说你这辈子从没见过像避难所这样的东西。}
#{332}{}{I hear you're pretty capable for a foreigner. Time to prove it.}
{332}{}{我听说作为一个外国人，你很能干。是时候证明了。}
#{333}{}{We don't usually see foreigners here.}
{333}{}{我们在这里通常看不到外国人。}
#{334}{}{Being allowed to visit the Vault is a unique honor. I hope you appreciate it.}
{334}{}{被允许参观避难所是一种独特的荣誉。希望你能喜欢。}
#{335}{}{Don't do anything stupid, we're watching you.}
{335}{}{别做傻事，我们看着你呢。}
#{336}{}{Try to behave properly.}
{336}{}{尽量举止得体。}
#{337}{}{You have your job, don't tarry.}
{337}{}{你有你的工作，不要耽搁了。}
#{338}{}{You may have the permission to be here, but we'll be on our guard in case you do something stupid.}
{338}{}{你可以获准来这里，但我们会保持警惕以防你做傻事。}
#{339}{}{Colonel Parson has instructions for you.}
{339}{}{帕森上校有指示要告诉你。}
#{340}{}{Stick to the rules and everything will be fine.}
{340}{}{遵守规则，一切都会好起来的。}
#{341}{}{You know your mission, don't screw it up.}
{341}{}{你知道自己的任务，别搞砸了。}
#{342}{}{You don't look that special to me. Guess we'll see.}
{342}{}{我看你也没那么特别。让我们拭目以待吧。}
#{343}{}{So you're THAT foreigner.}
{343}{}{原来你就是那个外国人。}
#{344}{}{I bet you've never seen anything like the Vault in your life.}
{344}{}{我敢说你这辈子从没见过像避难所这样的东西。}
#{345}{}{I hear you're pretty capable for a foreigner. Time to prove it.}
{345}{}{我听说作为一个外国人，你很能干。是时候证明了。}
#{346}{}{Long live emperor Aran!}
{346}{}{阿郎皇帝万岁！}
#{347}{}{I trust the emperor knows what he's doing by allowing you entry here.}
{347}{}{我相信皇帝知道他允许你进来是为了什么。}
#{348}{}{Long live empress Elisa!}
{348}{}{伊莉莎女王万岁！}
#{349}{}{I trust the empress knows what she's doing by allowing you entry here.}
{349}{}{我相信女王知道他允许你进来是为了什么。}
#{350}{}{I hear you're not too bad. For a foreigner.}
{350}{}{对于一个外国人来说，我听说你还不错。}
#{351}{}{I've heard some of the soldiers say that you've helped the empire.}
{351}{}{我听一些士兵说你帮助了帝国。}
#{352}{}{At least there's one capable foreigner. Who would've thought.}
{352}{}{至少还有一个能干的外国人。谁能想到。}
#{353}{}{You're... a curious foreigner. Not like the others.}
{353}{}{你…一个奇怪的外国人。不像其他人。}
#{354}{}{You're welcome here as long as you keep behaving properly.}
{354}{}{只要你举止得体，这里欢迎你。}
#{355}{}{It is an honor to serve in the army.}
{355}{}{在军队服役是一种荣誉。}
#{356}{}{The army is one of the best careers the empire provides.}
{356}{}{军队是帝国提供的最好的职业之一。}
#{357}{}{Greetings.}
{357}{}{问候语。}
#{358}{}{The imperial army appreciates your assistance.}
{358}{}{帝国军队感谢你的帮助。}
#{359}{}{It is our duty to put our lives on the line for the empire.}
{359}{}{我们的职责就是为帝国出生入死。}
#{360}{}{I believe you can handle yourself in any situation.}
{360}{}{我相信你在任何情况下都能应付自如。}
#{361}{}{No time to chat, I'm on duty.}
{361}{}{没时间聊天，我在值班。}
#{362}{}{The Vault is ours again, as it should be.}
{362}{}{避难所又归我们了，应该如此。}
#{363}{}{A day will come when we take care of the Hunters once and for all.}
{363}{}{总有一天我们会彻底解决猎人的。}
#{364}{}{Good to have you on our side, no matter what your reasons are.}
{364}{}{很高兴你站在我们这边，不管你的理由是什么。}
#{365}{}{You may lack discipline, but I can't deny your accomplishments.}
{365}{}{你也许缺乏自律，但我不能否认你的成就。}
#{366}{}{I hear you're not too bad. For a foreigner.}
{366}{}{对于一个外国人来说，我听说你还不错。}
#{367}{}{I've heard some of the soldiers say that you've helped the empire.}
{367}{}{我听一些士兵说你帮助了帝国。}
#{368}{}{At least there's one capable foreigner. Who would've thought.}
{368}{}{至少还有一个能干的外国人。谁能想到。}
#{369}{}{You're... a curious foreigner. Not like the others.}
{369}{}{你…一个奇怪的外国人。不像其他人。}
#{370}{}{You're welcome here as long as you keep behaving properly.}
{370}{}{只要你举止得体，这里欢迎你。}
#{371}{}{Long live emperor Aran!}
{371}{}{阿郎皇帝万岁！}
#{372}{}{Long live empress Elisa!}
{372}{}{伊莉莎女王万岁！}
#{373}{}{Nice armor.}
{373}{}{漂亮的盔甲。}
#{380}{}{An armed foreigner!}
{380}{}{一个武装的外国人！}
#{381}{}{No weapons in the building!}
{381}{}{大楼里没有武器！}
#{382}{}{We don't tolerate foreigners with weapons here.}
{382}{}{我们不允许外国人在这里携带武器。}
#{383}{}{An armed foreigner!}
{383}{}{一个武装的外国人！}
#{384}{}{Security breach! Terminate.}
{384}{}{违反安全规定！停下。}
#{400}{}{You've bitten off more than you can chew.}
{400}{}{你真是贪多嚼不烂。}
#{401}{}{Surround him.}
{401}{}{包围他。}
#{402}{}{Just another savage that needs to be put down.}
{402}{}{又一个需要被镇压的野蛮人。}
#{403}{}{Stop him. This must end.}
{403}{}{阻止他。这种情况必须结束。}
#{404}{}{I've got him in my sights.}
{404}{}{我看到他了。}
#{405}{}{You've got what you wanted, we'll finish this quickly.}
{405}{}{你已经得到你想要的了，我们很快就能搞定。}
#{406}{}{For the empire!}
{406}{}{为了帝国！}
#{407}{}{We're trained for this.}
{407}{}{我们受过训练。}
#{408}{}{We can handle foreigners easily.}
{408}{}{我们很容易对付外国人。}
#{409}{}{You're not making a mess in the empire. And soon, anywhere else.}
{409}{}{你没有把帝国搞得一团糟。很快，其他地方也会如此。}
#{410}{}{We can handle worse than you.}
{410}{}{我们能应付比你更糟的情况。}
#{411}{}{I'll teach you how to act civilized.}
{411}{}{我来教你怎么文明行事。}
#{412}{}{Our job is to protect the City from scum like you.}
{412}{}{我们的任务是保护这座城市不受你们这种人渣的侵害。}
#{413}{}{We have to protect the dwellers.}
{413}{}{我们必须保护居民。}
#{414}{}{No enemy will get past us.}
{414}{}{没有敌人能越过我们。}
#{415}{}{No enemy can escape us!}
{415}{}{没有敌人能摆脱我们 ！}
#{416}{}{Just another savage. Nothing new.}
{416}{}{只是一个野蛮人。没什么新鲜的。}
#{417}{}{This isn't the wasteland, we take care of scum immediately here.}
{417}{}{这里不是荒原，我们要马上处理渣滓。}
#{418}{}{We have superior numbers, you don't stand a chance.}
{418}{}{我们的人数比你多，你没有机会。}
#{419}{}{You've bitten off more than you can chew.}
{419}{}{你真是贪多嚼不烂。}
#{420}{}{Surround her.}
{420}{}{包围她。}
#{421}{}{Just another savage that needs to be put down.}
{421}{}{又一个需要被镇压的野蛮人。}
#{422}{}{Stop her. This must end.}
{422}{}{阻止她。这种情况必须结束。}
#{423}{}{I've got her in my sights.}
{423}{}{我看到她了。}
#{424}{}{You've got what you wanted, we'll finish this quickly.}
{424}{}{你已经得到你想要的了，我们很快就能搞定。}
#{425}{}{For the emperor!}
{425}{}{为了皇帝！}
#{426}{}{For the empress!}
{426}{}{为了女王！}
#{427}{}{Exactly what you'd expect from a Mutant Hunter.}
{427}{}{跟变种猎人一样。}
#{450}{}{That didn't even get through the armor.}
{450}{}{连盔甲都没穿。}
#{451}{}{Stupid aggressive savages.}
{451}{}{愚蠢好斗的野蛮人。}
#{452}{}{Nothing can break an imperial soldier.}
{452}{}{没有什么能打败帝国士兵。}
#{453}{}{Damn. Do you really think you have a chance to survive?!}
{453}{}{该死的。你真的认为你有机会活下去吗？！}
#{454}{}{I can handle pain.}
{454}{}{我能承受痛苦。}
#{455}{}{I will lay down my life for the empire if I have to.}
{455}{}{如果有必要，我会为帝国牺牲自己。}
#{456}{}{Cover me!}
{456}{}{掩护我！}
#{457}{}{That won't stop me.}
{457}{}{那不能阻止我。}
#{458}{}{If I won't get you, the others will.}
{458}{}{就算我抓不到你，其他人也会的。}
#{459}{}{Medic!}
{459}{}{医生！}
#{460}{}{Fucking Hunters, you just can't trust them.}
{460}{}{该死的猎人，你不能相信他们。}
#{500}{}{Emperor Myzrael has no desire to see a foreigner.}
{500}{}{米兹雷尔皇帝不想见外国人。}
#{501}{}{The emperor will see no one.}
{501}{}{皇帝不会见任何人。}
#{502}{}{Emperor Myzrael doesn't wish to be disturbed.}
{502}{}{米泽列皇帝不想被打扰。}
#{503}{}{I won't allow any foreigner to come close to the emperor.}
{503}{}{我不会允许任何外国人接近皇帝。}
#{504}{}{If you really have something important to say, talk to the Advisers.}
{504}{}{如果你真的有重要的事情要说，就和顾问们谈谈。}
#{505}{}{Foreigners are not allowed in the emperor's chambers.}
{505}{}{外国人不允许进入皇帝的寝宫。}
#{506}{}{Leave. The emperor has no desire to see you.}
{506}{}{走开。皇帝不想见你。}
#{507}{}{Emperor Myzrael has no desire to see a foreigner.}
{507}{}{米泽列皇帝不想见一个外国人。}
#{600}{}{You've got no business down there.}
{600}{}{你没必要去那里。}
#{601}{}{The elevator leads to the Vault. Foreigners are not allowed there.}
{601}{}{电梯通向避难所。外国人是不允许进入的。}
#{602}{}{Leave the door alone.}
{602}{}{别碰门。}
#{603}{}{Foreigners are not allowed to enter the Vault.}
{603}{}{外国人是不允许进入避难所的。}
#{604}{}{Step away from the door.}
{604}{}{离门远点。}
#{605}{}{Don't try anything, you're simply not getting into the Vault.}
{605}{}{别做任何尝试，你根本进不了避难所。}
#{606}{}{You've been granted the permission to enter the City and the main building, but not the Vault.}
{606}{}{你被允许进入城市和主楼，但不能进入避难所。}
#{607}{}{Let it go, it's pointless.}
{607}{}{算了吧，这毫无意义。}
#{608}{}{The emperor has given you the permission to enter. Don't do anything stupid down here.}
{608}{}{皇帝已经允许你进去了。不要做傻事。}
#{609}{}{The empress has given you the permission to enter. Don't do anything stupid down here.}
{609}{}{女王已经允许你进去了。不要做傻事。}
#{610}{}{You may enter the Vault. You should feel honored.}
{610}{}{你可以进入避难所。你应该感到荣幸。}
#{700}{}{You're not supposed to have your weapons drawn in the main building. Just warning you.}
{700}{}{你不应该在主楼里拔出武器。只是提醒你一下。}
#{701}{}{Don't forget, no weapons in the building.}
{701}{}{别忘了，楼里不准带武器。}
#{702}{}{You so much as touch your weapon and the guards take you out.}
{702}{}{你敢碰你的武器守卫就会把你带出去。}
#{703}{}{Keep your weapons holstered while you're inside.}
{703}{}{进去的时候把武器收好。}
#{704}{}{No reason to have a weapon drawn in the main building. Remember that.}
{704}{}{没必要在主楼里拔枪。记住,。}
#{705}{}{Watch the weapons. Don't let the guards see them in your hands.}
{705}{}{小心武器。别让守卫看到你拿在手里。}
#{706}{}{You're not supposed to have your weapons drawn in the main building. Just warning you.}
{706}{}{你不应该在主楼里拔出武器。只是提醒你一下。}
#{800}{}{Colonel Parson isn't here. He's been assigned a special mission in Vault 16. If you have any business with the imperial army, you'll have to wait until he returns.}
{800}{}{帕森上校不在。他被派去16号避难所执行特殊任务。如果你和帝国军队有什么事，你得等他回来。}
#{801}{}{Colonel Parson's been assigned a special mission in the Vault. He won't be around in the near future.}
{801}{}{帕森上校被派去避难所执行一项特殊任务。近期内他是不会出现了。}
#{820}{}{You're in the imperial palace. Put that weapon away right now!}
{820}{}{你在皇宫里。马上把武器收起来！}
#{821}{}{If you won't put away your weapon willingly, I'll make you by force!}
{821}{}{如果你不愿意放下你的武器，我就强迫你！}
#{830}{}{Don't touch that, that's imperial property.}
{830}{}{别碰那个，那是帝国的财产。}
#{1000}{}{Wait, stranger. Just to be sure, I have to warn you not to draw your weapons in the building. We won't disarm you, you're a guest in our City and it wouldn't be respectful, but keep them holstered.}
{1000}{}{等等，陌生人。为了保险起见，我得警告你不要在楼里拔枪。我们不会解除你的武装，你是我们城市的客人，这是不礼貌的，但还是把枪收好吧。}
#{1001}{}{Wait, stranger. Just to be sure, I have to warn you not to draw your weapons in the building. We won't disarm you, you're a guest in our City and it wouldn't be respectful, but keep them holstered.}
{1001}{}{等等，陌生人。为了保险起见，我得警告你不要在楼里拔枪。我们不会解除你的武装，你是我们城市的客人，这是不礼貌的，但还是把枪收好吧。}
#{1002}{}{Why? What would happen?}
{1002}{}{为什么？会发生什么？}
#{1003}{}{He?}
{1003}{}{他？}
#{1050}{}{You're entering the main imperial building. Some call it a palace. Our highest representatives are here, including the members of the imperial family. Thus, foreigners waving weapons around are automatically deemed a threat, for security reasons.}
{1050}{}{你正在进入帝国的主楼。有人称它为宫殿。我们的最高代表都在这里，包括皇室成员。因此，出于安全原因，挥舞着武器的外国人自然会被视为威胁。}
#{1051}{}{Ah, yes, I see, that wouldn't be good. Thanks for the warning.}
{1051}{}{啊，是的，我明白了，那样不好。谢谢你的提醒。}
#{1052}{}{Ouk.}
{1052}{}{啊哟。}
