#{100}{}{You see a tribal.}
{100}{}{你看到一个部落人。}
#{200}{}{You see a hunter of the tribe.}
{200}{}{你看到一个部落的猎人。}
#{330}{}{Outsider fought bravely.}
{330}{}{外来者英勇作战。}
#{331}{}{Outsider can go now.}
{331}{}{外来者现在可以走了。}
#{332}{}{Hunters will take care of the rest.}
{332}{}{剩下的就交给猎人了。}
#{333}{}{Outsider fought bravely.}
{333}{}{外来者英勇作战。}
#{334}{}{Outsider can go now.}
{334}{}{外来者现在可以走了。}
#{340}{}{Outsider fought bravely.}
{340}{}{外来者英勇作战。}
#{341}{}{Gurgan must know what happened here.}
{341}{}{戈尔甘一定知道这里发生了什么。}
#{342}{}{Hunters will go back to Albuquerque now.}
{342}{}{猎人们现在要回阿尔伯克基了。}
#{343}{}{Outsider fought bravely.}
{343}{}{外来者英勇作战。}
#{400}{}{Hunters will fight to the last.}
{400}{}{猎人们会战斗到底。}
#{401}{}{Gecko cannot win.}
{401}{}{蜥蜴赢不了。}
#{402}{}{Ancestors smile on hunters.}
{402}{}{祖先会保佑猎人。}
#{403}{}{Hunters say sorry to geckos, but they need their skins to live.}
{403}{}{猎人对蜥蜴说对不起，但他们需要它们的皮才能生存。}
#{404}{}{The hunt is over. Hunters will take care of skinning the geckos.}
{404}{}{狩猎结束了。猎人们将负责剥蜥蜴的皮。}
