#{100}{}{You see a tribal.}
{100}{}{你看到一个部落人。}
#{200}{}{You see a hunter of the tribe.}
{200}{}{你看到一个部落的猎人。}
#{201}{}{ He is stunned.}
{201}{}{ 他惊呆了。}
#{300}{}{Hunting in the wasteland is more and more dangerous.}
{300}{}{在荒原上打猎越来越危险了。}
#{301}{}{Gurgan is a good chief.}
{301}{}{戈尔甘是个好酋长。}
#{302}{}{Ancestors protect the tribe.}
{302}{}{祖先保护部落。}
#{303}{}{We must be wary of city folk. They are too crafty.}
{303}{}{我们必须提防城里人。他们太狡猾了。}
#{304}{}{The tribe misses its old hunting grounds.}
{304}{}{这个部落失去了它古老的狩猎场。}
#{305}{}{The tribe would be helpless without a shaman. Ancestors talk only through him.}
{305}{}{没有萨满，部落会很无助。祖先们只能通过他说话。}
#{306}{}{Life in the city is hard. People of the tribe are getting used to it only slowly.}
{306}{}{城里的生活很艰难。部落的人们只能慢慢地适应它。}
#{307}{}{Outsider has proven that he is a brave warrior. Hunters respect him.}
{307}{}{外来者已经证明他是一个勇敢的战士。猎人很尊敬他。}
#{308}{}{Outsider has proven that she is a brave warrior. Hunters respect her.}
{308}{}{外来者已经证明她是一个勇敢的战士。猎人很尊敬他她。}
#{309}{}{Friend has helped the tribe much.}
{309}{}{朋友帮了部落很多忙。}
#{310}{}{May ancestors smile on friend.}
{310}{}{愿祖先保佑朋友。}
#{311}{}{Friend has helped the tribe much.}
{311}{}{朋友帮了部落很多忙。}
#{312}{}{May ancestors smile on friend.}
{312}{}{愿祖先保佑朋友。}
#{313}{}{Gurgan was a great chief. He is with ancestors now.}
{313}{}{戈尔甘是一位伟大的酋长。他现在和祖先们在一起。}
#{314}{}{What is that monster that follows outsider?}
{314}{}{跟在外来者后面的那个怪物是什么？}
#{315}{}{Is outsider not afraid that the beast might turn on him?}
{315}{}{外来者难道不怕野兽攻击他吗？}
#{316}{}{What is that monster that follows outsider?}
{316}{}{跟在外来者后面的那个怪物是什么？}
#{317}{}{Is outsider not afraid that the beast might turn on her?}
{317}{}{外来者难道不怕野兽攻击她吗？}
#{320}{}{Outsider has no business being here!}
{320}{}{外来者不该来这里！}
#{321}{}{Outsider should leave!}
{321}{}{外来者请离开！}
#{322}{}{Outsider is a bad man.}
{322}{}{外来者是坏人。}
#{323}{}{People of the tribe cannot forgive outsider.}
{323}{}{部落的人不能原谅外来者。}
#{324}{}{Outsider has no business being here!}
{324}{}{外来者不该来这里！}
#{325}{}{Outsider is a bad woman.}
{325}{}{外来者是个坏女人。}
#{326}{}{Outsider should leave!}
{326}{}{外来者请离开！}
#{400}{}{Outsider's life ends now.}
{400}{}{外来者的生命现在结束了。}
#{401}{}{Hunters will fight to the last.}
{401}{}{猎人们会战斗到底。}
#{402}{}{That will not stop hunter!}
{402}{}{这不会阻止猎人！}
#{403}{}{Enemies of the tribe must die!}
{403}{}{部落的敌人必须死！}
#{404}{}{Outsider's life ends now.}
{404}{}{外来者的生命现在结束了。}
#{410}{}{ loses consciousness and falls lifelessly to the ground.}
{410}{}{ 失去意识，毫无生气地倒在地上。}
