#{100}{}{You see a doctor.}
{100}{}{你看到一个医生。}
#{200}{}{You see a hospital doctor.}
{200}{}{你看到一个医院的医生。}
#{300}{}{We have enough muscle donors.}
{300}{}{我们有足够的肌体捐赠者。}
#{301}{}{Doctor Falber is the one you should talk to.}
{301}{}{你应该找福伯医生谈谈。}
#{302}{}{Try not to get in the way.}
{302}{}{不要碍事。}
#{303}{}{I have no time for you.}
{303}{}{我没时间陪你。}
#{304}{}{I work in research.}
{304}{}{我从事研究工作。}
#{305}{}{Please, stop bothering me.}
{305}{}{拜托，别再烦我了。}
#{306}{}{Talk to Doctor Falber.}
{306}{}{和福伯医生谈谈。}
#{307}{}{I'm busy.}
{307}{}{我很忙。}
#{308}{}{I can't afford the slightest carelessness.}
{308}{}{我不能有丝毫的疏忽。}
#{309}{}{I hope I won't have to do any more dissections today.}
{309}{}{我希望今天不用再做解剖了。}
#{310}{}{Doctor Falber is the one you should talk to.}
{310}{}{你应该找福伯医生谈谈。}
#{311}{}{Try not to get in the way.}
{311}{}{不要碍事。}
#{312}{}{We have enough muscle donors.}
{312}{}{我们有足够的肌体捐赠者。}
