#{100}{}{You see an important looking woman.}
{100}{}{你看到一个看起来很重要的女人。}
#{150}{}{You see Adviser Elisa.}
{150}{}{你看到伊莉莎顾问。}
#{151}{}{You see empress Elisa.}
{151}{}{你看到伊莉莎女王。}
#{200}{}{You see a tastefully dressed middle-aged woman. The most striking feature of her appearance is an elegant embroidered patch on the right sleeve of her jumpsuit - a bright, golden number 16.}
{200}{}{你看到一个衣着高雅的中年妇女。她的外表最引人注目的特点是在她的连体衣的右袖上有一块优雅的刺绣补丁——一个明亮的金色数字16。}
#{250}{}{You see Adviser Elisa. She seems to be deep in thought.}
{250}{}{你看到伊莉莎顾问。她似乎在深思。}
#{251}{}{You see empress Elisa. She seems to have gotten used to her new position very quickly.}
{251}{}{你看到伊莉莎女王。她似乎很快就适应了她的新职位。}
#{300}{}{The empire is grateful for the information you provided. You have made the right choice.}
{300}{}{帝国非常感谢你提供的信息。你做了正确的选择。}
#{301}{}{The empire is grateful for the information you provided. You have made the right choice.}
{301}{}{帝国非常感谢你提供的信息。你做了正确的选择。}
#{302}{}{Look after yourself in the meantime. We'll see each other again when the time comes to settle things with Anonym.}
{302}{}{在此期间你要照顾好自己。当我们和匿名者解决问题的时候，我们会再见面的。}
#{303}{}{Thank you for your services. I will require them no longer.}
{303}{}{谢谢你的服务。我不再需要它们了。}
#{304}{}{We have nothing to say to each other.}
{304}{}{我们没什么可说的。}
#{305}{}{My god, what has happened to you? You look terrible. I refuse to speak with you in such a state.}
{305}{}{天啊，你怎么了？你看起来糟透了。我拒绝在这种状态下和你说话。}
#{306}{}{Do not return until you take care of your mental condition.}
{306}{}{在你处理好你的精神状况之前不要回来。}
#{307}{}{We are done.}
{307}{}{我们做完了。}
#{308}{}{Don't bother me anymore.}
{308}{}{别再烦我了。}
#{400}{}{Guards! This person is trying to kill me. Protect me!}
{400}{}{卫兵！这个人想杀我。保护我！}
#{401}{}{That's insane! Do you really want to face the entire imperial army?}
{401}{}{这太疯狂了！你真的想面对整个帝国军队吗？}
#{402}{}{Aran, your desperate struggle will be in vain. You cannot defeat me.}
{402}{}{阿朗，你不顾一切的挣扎是徒劳的。你不可能打败我。}
#{403}{}{Only a few dead bodies separate me from my ascension to the throne. Your dead bodies.}
{403}{}{只要再牺牲几个人我就能登上王位，就是你们。}
#{404}{}{Guards! This foreigner is walking around armed.}
{404}{}{卫兵！这个外国人带着武器四处走动。}
#{405}{}{Guards! This foreigner is walking around armed.}
{405}{}{卫兵！这个外国人带着武器四处走动。}
#{500}{}{My apologies, stranger, but I really don't have the time to deal with your issues. My position involves many important tasks that can bear no delay. It would be best if you left immediately.}
{500}{}{抱歉，陌生人，但我真的没时间处理你的问题。我的职务涉及许多不容拖延的重要任务。你最好马上离开。}
#{501}{}{My apologies, stranger, but I really don't have the time to deal with your issues. My position involves many important tasks that can bear no delay. It would be best if you left immediately.}
{501}{}{抱歉，陌生人，但我真的没时间处理你的问题。我的职务涉及许多不容拖延的重要任务。你最好马上离开。}
#{502}{}{What tasks would those be?}
{502}{}{那是什么任务呢？}
#{503}{}{I'm not sure I like your tone.}
{503}{}{我不太喜欢你的语气。}
#{504}{}{I'm not sure I like your tone.}
{504}{}{我不太喜欢你的语气。}
#{505}{}{As you wish. I'm leaving.}
{505}{}{如你所愿。我要走了。}
#{506}{}{Argh. Bai den.}
{506}{}{啊。白登。}
#{550}{}{[She looks shocked.] That's really none of your business. Do you even know who you are talking to? I am Adviser Elisa. Asking about my duties could get you into a lot of trouble. It would be wise to avoid that and leave me alone.}
{550}{}{[她看起来很震惊。]那真不关你的事。你知道你在跟谁说话吗？我是伊莉莎顾问。问我的职责会给你带来很多麻烦。明智的做法是避免这种情况，别来烦我。}
#{551}{}{Wait, I've been looking for you. Lieutenant Shaun Terrak told me that you need a capable person for a job. I'd like to sign up.}
{551}{}{等等，我一直在找你。肖恩·泰瑞克中尉告诉我你需要一个能干的人来做这份工作。我想报名。}
#{552}{}{Wait, I've been looking for you. Lieutenant Shaun Terrak told me that you need a capable person for a job. I'd like to sign up.}
{552}{}{等等，我一直在找你。肖恩·泰瑞克中尉告诉我你需要一个能干的人来做这份工作。我想报名。}
#{553}{}{As you wish. Goodbye.}
{553}{}{如你所愿。再见。}
#{600}{}{Do you even know who you are talking to? I am Adviser Elisa. Such behavior could cost you your life. You'd best try to avoid that next time. Now leave me be.}
{600}{}{你知道你在跟谁说话吗？我是伊莉莎顾问。这样的行为会让你付出生命的代价。下次你最好避免这样。现在离我远点。}
#{601}{}{Wait, I've been looking for you. Lieutenant Shaun Terrak told me that you need a capable person for a job. I'd like to sign up.}
{601}{}{等等，我一直在找你。肖恩·泰瑞克中尉告诉我，你需要一个能干的人来做这份工作。我想报名。}
#{602}{}{Wait, I've been looking for you. Lieutenant Shaun Terrak told me that you need a capable person for a job. I'd like to sign up.}
{602}{}{等等，我一直在找你。肖恩·泰瑞克中尉告诉我，你需要一个能干的人来做这份工作。我想报名。}
#{603}{}{There won't be a next time. I'll deal with you right now.}
{603}{}{不会再有下次了。我现在就处理你。}
#{604}{}{As you wish. Goodbye.}
{604}{}{如你所愿。再见。}
#{650}{}{That good-for-nothing sent you? He really does try my patience. The only job he could know about was the one assigned to him. But he's been tarrying for an eternity. He likely hopes to pass it onto someone else this way. But... [She thinks for a moment.] that's not a completely stupid idea. This errand would indeed be more suited to someone without a connection to the empire. [She studies you carefully.] Do you really wish to work for the emperor?}
{650}{}{那个废物派你来的？他真的在考验我的耐心。他唯一知道的工作就是分配给他的工作。但他已经耽搁了很久了。他可能希望通过这种方式把它交给别人。但是…[她想了一会儿。]这也不是一个完全愚蠢的主意。这种差事确实更适合与帝国无关的人。[她仔细地研究你。]你真的想为皇帝工作吗?}
#{651}{}{I'd like nothing more.}
{651}{}{我不想再这样了。}
#{652}{}{If the reward is sufficient, I will gladly offer him my services.}
{652}{}{如果报酬足够的话，我很乐意为他效劳。}
#{653}{}{I have no desire to stand-in for someone. I'm sure the emperor will manage.}
{653}{}{我不想做别人的替身。我相信皇帝会处理好的。}
#{700}{}{I'm glad to hear that. But before you do so, you should know that I demand absolute loyalty. You may only serve the emperor unconditionally, or not at all. If you are willing to agree to this, I could have other uses for you as well. But I want to hear a clear answer from you. Don't even think of betraying us - I will be watching you closely. Actually, I'm afraid that even our enemy will know if you decide to work for us. The uncomfortable truth is that the whole empire is riddled with his informants.}
{700}{}{听你这么说我很高兴。但在你这么做之前，你要知道我要的是绝对的忠诚。你可以无条件地侍奉皇帝，也可以选择不侍奉。如果你愿意这么做，我还可以让你做其他事。但我想从你那里听到一个明确的答案。别想背叛我们-我会密切关注你的。实际上，如果你决定为我们工作，恐怕连我们的敌人都会知道。令人不安的事实就是整个帝国到处都是他的线人。}
#{701}{}{I'm glad to hear that. But before you do so, you should know that I demand absolute loyalty. You may only serve the emperor unconditionally, or not at all. If you are willing to agree to this, I could have other uses for you as well. But I want to hear a clear answer from you. Don't even think of betraying us - I will be watching you closely. Actually, I'm afraid that even our enemy will know if you decide to work for us. The uncomfortable truth is that the whole empire is riddled with his informants.}
{701}{}{听你这么说我很高兴。但在你这么做之前，你要知道我要的是绝对的忠诚。你可以无条件地侍奉皇帝，也可以选择不侍奉。如果你愿意这么做，我还可以让你做其他事。但我想从你那里听到一个明确的答案。别想背叛我们-我会密切关注你的。实际上，如果你决定为我们工作，恐怕连我们的敌人都会知道。令人不安的事实就是整个帝国到处都是他的线人。}
#{702}{}{I can't say it any clearer. I'm in, so tell me who I'm supposed to go up against already.}
{702}{}{我说得再清楚不过了。我加入了，告诉我应该和谁对抗。}
#{703}{}{I prefer not to tie myself with obligations this strict. I can't work for you.}
{703}{}{我不想把自己和这么严格的义务捆绑在一起。我不能为你工作。}
#{704}{}{I prefer not to tie myself with obligations this strict. I can't work for you.}
{704}{}{我不想把自己和这么严格的义务捆绑在一起。我不能为你工作。}
#{750}{}{Then we have an agreement. You will receive your orders from me and no one else. To that end, I will arrange you a pass into the City in my name. It is a great privilege, one that you must use with discretion. And now for your assignment. You've probably already heard of a person calling himself Anonym. He's a vicious terrorist trying to overthrow emperor Myzrael and the Advisers, so that he can institute his own dictatorship. We must prevent that from happening.}
{750}{}{那我们就达成协议了。命令你的人只有我，没有别人。为此，我会以我的名义给你办一张进城的通行证。这是很大的特权，你必须谨慎使用。现在是你的任务。你可能已经听说过一个自称为匿名者的人。他是一个邪恶的恐怖分子，试图推翻米泽列皇帝和顾问们，以便建立自己的独裁政权。我们必须防止这种情况发生。}
#{751}{}{Then we have an agreement. You will receive your orders from me and no one else. To that end, I will arrange you a pass into the City in my name. It is a great privilege, one that you must use with discretion. And now for your assignment. You've probably already heard of a person calling himself Anonym. He's a vicious terrorist trying to overthrow emperor Myzrael and the Advisers, so that he can institute his own dictatorship. We must prevent that from happening.}
{751}{}{那我们就达成协议了。命令你的人只有我，没有别人。为此，我会以我的名义给你办一张进城的通行证。这是很大的特权，你必须谨慎使用。现在是你的任务。你可能已经听说过一个自称为匿名者的人。他是一个邪恶的恐怖分子，试图推翻米泽列皇帝和顾问们，以便建立自己的独裁政权。我们必须防止这种情况发生。}
#{752}{}{As you say. Please, go on.}
{752}{}{就像你说的。请继续。}
#{800}{}{We were recently contacted by an informant that allegedly knew the location of Anonym's secret hideout. He was afraid to come into the empire, so, with Adviser Aran's permission, I sent a squad of soldiers to meet him in the Dead Quarter. Adviser Aran ordered them to report immediately after receiving the information, but we have not heard from them since. I'm afraid that they've been lured into a trap. That's why I need you to search the place and find out what happened to them. I don't know if it will help, but they were supposed to meet in the western end of the Dead Quarter, near the defensive wall.}
{800}{}{最近有个线人联系了我们，据说他知道匿名者的秘密藏身处。他不敢进入帝国，因此，在阿朗顾问的允许下，我派了一队士兵在死区与他会面。阿朗顾问命令他们在收到情报后立即报告，但我们此后一直没有收到他们的消息。恐怕他们中了圈套。所以我需要你去搜查那个地方找出他们到底怎么了。我不知道这是否有帮助，但他们应该在死区的西端，靠近防御墙的地方。}
#{801}{}{We were recently contacted by an informant that allegedly knew the location of Anonym's secret hideout. He was afraid to come into the empire, so, with Adviser Aran's permission, I sent a squad of soldiers to meet him in the Dead Quarter. Adviser Aran ordered them to report immediately after receiving the information, but we have not heard from them since. I'm afraid that they've been lured into a trap. That's why I need you to search the place and find out what happened to them. I don't know if it will help, but they were supposed to meet in the western end of the Dead Quarter, near the defensive wall.}
{801}{}{最近有个线人联系了我们，据说他知道匿名者的秘密藏身处。他不敢进入帝国，因此，在阿朗顾问的允许下，我派了一队士兵在死区与他会面。阿朗顾问命令他们在收到情报后立即报告，但我们此后一直没有收到他们的消息。恐怕他们中了圈套。所以我需要你去搜查那个地方找出他们到底怎么了。我不知道这是否有帮助，但他们应该在死区的西端，靠近防御墙的地方。}
#{802}{}{Who is this Aran, anyway? Can he be trusted?}
{802}{}{这个阿朗到底是谁？他可信吗？}
#{803}{}{Maybe you should know that a certain midget offered me a job for Anonym. The man lives in the Wild Paradise.}
{803}{}{也许你该知道有个侏儒给我提供了匿名者的工作。这个人住在狂野天堂。}
#{804}{}{I will go search for them right now. Goodbye, Adviser Elisa.}
{804}{}{我现在就去找他们。再见，伊莉莎顾问。}
#{850}{}{Adviser Aran has been faithfully serving the emperor for many years. He is the commander-in-chief of the imperial army, during the defense of the City from a ghoul attack he stood right at the front line. He almost paid with his life for his courage. Every soldier would be willing to fight for him to the bitter end. There can be no doubt that he is trustworthy. Still, I regret that he doesn't pay Anonym's threat as much attention as it deserves. But back to your assignment. Find out what happened to the squad of soldiers we sent out. This matter is of utmost importance to the empire.}
{850}{}{阿朗顾问多年来一直忠实地为皇帝服务。他是帝国军队的总司令，在保卫城市免受僵尸的攻击时，他就站在前线。他几乎为他的勇气付出了生命的代价。每个士兵都愿意为他战斗到底。毫无疑问，他是值得信赖的。不过，我还是很遗憾，他没有对“匿名者”的威胁给予应有的重视。回到你的任务上来。看看我们派去的那班士兵怎么样了。这件事对帝国至关重要。}
#{851}{}{Maybe you should know that a certain midget offered me a job for Anonym. The man lives in the Wild Paradise.}
{851}{}{也许你该知道有个侏儒给我提供了匿名者的工作。这个人住在狂野天堂。}
#{852}{}{That's the plan. Goodbye, Adviser Elisa.}
{852}{}{这就是我们的计划。再见，伊莉莎顾问。}
#{900}{}{As you wish. I won't bother you with useless attempts to persuade you otherwise. My offer will stay open for now, should you change your mind. But it won't be forever.}
{900}{}{如你所愿。我不会徒劳无功地试图说服你。如果你改变主意，我的报价暂时有效。但不会永远。}
#{901}{}{I'll remember that. Goodbye, Adviser Elisa.}
{901}{}{我会记住的。再见，伊莉莎顾问。}
#{950}{}{Is there a reason you sought me out again? I've already told you I'm extremely busy.}
{950}{}{你又找我有什么原因吗？我已经告诉过你我很忙。}
#{951}{}{Is there a reason you sought me out again? I've already told you I'm extremely busy.}
{951}{}{你又找我有什么原因吗？我已经告诉过你我很忙。}
#{952}{}{What exactly keeps you so busy?}
{952}{}{到底是什么让你这么忙？}
#{953}{}{I'm not sure I like your tone.}
{953}{}{我不太喜欢你的语气。}
#{954}{}{I'm not sure I like your tone.}
{954}{}{我不太喜欢你的语气。}
#{955}{}{Lieutenant Shaun Terrak told me that you need a capable person for a job. I'd like to sign up.}
{955}{}{肖恩·泰瑞克中尉告诉我，你需要一个能干的人来做这份工作。我想报名。}
#{956}{}{Lieutenant Shaun Terrak told me that you need a capable person for a job. I'd like to sign up.}
{956}{}{肖恩·泰瑞克中尉告诉我，你需要一个能干的人来做这份工作。我想报名。}
#{957}{}{No reason, actually. I'll be going now.}
{957}{}{事实上，没有原因。我要走了。}
#{958}{}{Uf. Bwah.}
{958}{}{呃。啊。}
#{1000}{}{I knew you'd be back soon. Serving the emperor is the highest honor attainable in life. It would be unwise to let such an opportunity slip between your fingers. Can I count on you, then?}
{1000}{}{我就知道你很快就会回来。侍奉皇帝是人生最高的荣誉。让这样的机会从指缝间溜走是不明智的。那我能指望你吗？}
#{1001}{}{Yes. I gladly offer him my services.}
{1001}{}{是的。我很乐意为他效劳。}
#{1002}{}{Yes, I've decided to accept your conditions.}
{1002}{}{是的，我决定接受你的条件。}
#{1003}{}{Yes, I've decided to accept your conditions.}
{1003}{}{是的，我决定接受你的条件。}
#{1004}{}{I stand by my decision. Goodbye, Adviser Elisa.}
{1004}{}{我坚持我的决定。再见，伊莉莎顾问。}
#{1005}{}{Uh.}
{1005}{}{呃。}
#{1050}{}{[The woman looks at you curiously.] Greetings, stranger. I am Adviser Elisa. Is there a reason you sought me out?}
{1050}{}{[女人好奇地看着你。]你好，陌生人。我是伊莉莎顾问。你找我有什么事吗？}
#{1051}{}{[The woman looks at you curiously.] Greetings, stranger. I am Adviser Elisa. Is there a reason you sought me out?}
{1051}{}{[女人好奇地看着你。]你好，陌生人。我是伊莉莎顾问。你找我有什么事吗？}
#{1052}{}{Yes, I have very important information concerning Anonym for you. If you hear me out, it could lead you straight to him.}
{1052}{}{是的，我有关于匿名者的重要信息要告诉你。如果你听我说完，就能直接找到他。}
#{1053}{}{No, there isn't. I'll be leaving now.}
{1053}{}{不，没有。我现在要走了。}
#{1054}{}{Uh.}
{1054}{}{呃。}
#{1100}{}{Stranger, as I have told you, I am extremely busy. Is there a reason you sought me out again?}
{1100}{}{陌生人，我已经告诉过你了，我非常忙。你又来找我有什么事吗？}
#{1101}{}{Stranger, as I have told you, I am extremely busy. Is there a reason you sought me out again?}
{1101}{}{陌生人，我已经告诉过你了，我非常忙。你又来找我有什么事吗？}
#{1102}{}{ As far as I know, you've refused my offer to serve the emperor. I'm afraid you've already missed your chance.}
{1102}{}{ 据我所知，你拒绝了我为皇帝效力的提议。恐怕你已经错过机会了。}
#{1103}{}{ As far as I know, you've refused my offer to serve the emperor. I'm afraid you've already missed your chance.}
{1103}{}{ 据我所知，你拒绝了我为皇帝效力的提议。恐怕你已经错过机会了。}
#{1104}{}{I have very important information concerning Anonym for you. If you hear me out, it could lead you straight to him.}
{1104}{}{我有关于匿名者的重要信息要告诉你。如果你听我说完，就能直接找到他。}
#{1105}{}{I insist - I have important information concerning Anonym. I lost my temper the last time. I apologize. Please, assemble the imperial council.}
{1105}{}{我坚持 - 我有关于匿名者的重要信息。上次我发脾气了。我道歉。请召集议会会议。}
#{1106}{}{I insist - I have important information concerning Anonym. I lost my temper the last time. I apologize. Please, assemble the imperial council.}
{1106}{}{我坚持 - 我有关于匿名者的重要信息。上次我发脾气了。我道歉。请召集议会会议。}
#{1107}{}{No, there isn't. I'll be leaving now.}
{1107}{}{不，没有。我现在要走了。}
#{1108}{}{Uh.}
{1108}{}{呃。}
#{1150}{}{What could *you* possibly know? How did you come by this information, anyway? I'm sure you understand my doubts about the credibility of your information.}
{1150}{}{“你”可能知道什么？你是怎么得到这个消息的？我相信你能理解我对你信息可信度的怀疑。}
#{1151}{}{What could *you* possibly know? How did you come by this information, anyway? I'm sure you understand my doubts about the credibility of your information.}
{1151}{}{“你”可能知道什么？你是怎么得到这个消息的？我相信你能理解我对你信息可信度的怀疑。}
#{1152}{}{In the Wild Paradise, I accidentally overheard a conversation of two mercenaries that I believe were working for Anonym. They talked about...}
{1152}{}{在狂野天堂，我无意中听到了两名雇佣兵的对话，我相信他们是为匿名者工作的。他们谈论了……}
#{1153}{}{In the Wild Paradise, I accidentally overheard a conversation of two mercenaries that I believe were working for Anonym. They talked about...}
{1153}{}{在狂野天堂，我无意中听到了两名雇佣兵的对话，我相信他们是为匿名者工作的。他们谈论了……}
#{1200}{}{Very well, that's enough. [She interrupts you by raising her hand.] If you are confident, I will believe that your information is credible enough. However, a report of this importance should be heard by the whole imperial council. I'm willing to assembly it right now. But you should know that wasting the council's time could get you into serious trouble. Should I do so, regardless?}
{1200}{}{很好，够了。[她举手打断你的话。]如果你有信心，我相信你的消息是可信的。然而，如此重要的报告应该被整个议会听取。我愿意现在就集合议会。但你要知道浪费议会的时间会让你惹上大麻烦。不管怎样，我应该这样做吗？}
#{1201}{}{Very well, that's enough. [She interrupts you by raising her hand.] If you are confident, I will believe that your information is credible enough. However, a report of this importance should be heard by the whole imperial council. I'm willing to assembly it right now. But you should know that wasting the council's time could get you into serious trouble. Should I do so, regardless?}
{1201}{}{很好，够了。[她举手打断你的话。]如果你有信心，我相信你的消息是可信的。然而，如此重要的报告应该被整个议会听取。我愿意现在就集合议会。但你要知道浪费议会的时间会让你惹上大麻烦。不管怎样，我应该这样做吗？}
#{1202}{}{Please, assemble the council. I'm absolutely certain that the information is valuable.}
{1202}{}{请召集议会。我绝对肯定这个信息很有价值。}
#{1203}{}{Please, assemble the council. I'm absolutely certain that the information is valuable.}
{1203}{}{请召集议会。我绝对肯定这个信息很有价值。}
#{1204}{}{In that case, forget it.}
{1204}{}{既然如此，还是算了吧。}
#{1250}{}{I'm not very surprised that a foreigner cannot keep his word. In that case, you have no reason to be here. Get out of my sight. And don't come back without information you're willing to vouch for.}
{1250}{}{我对一个外国人不能遵守诺言并不感到惊讶。那样的话，你就没理由待在这里了。滚出我的视线。没有你愿意担保的信息不要回来。}
#{1251}{}{I'm not very surprised that a foreigner cannot keep her word. In that case, you have no reason to be here. Get out of my sight. And don't come back without information you're willing to vouch for.}
{1251}{}{我对一个外国人不能遵守诺言并不感到惊讶。那样的话，你就没理由待在这里了。滚出我的视线。没有你愿意担保的信息不要回来。}
#{1252}{}{Goodbye, Adviser Elisa.}
{1252}{}{再见，伊莉莎顾问。}
#{1300}{}{I see you are confident. Under better circumstances, the presence of an outsider in a meeting of the council would be unthinkable. But desperate times call for desperate measures. Very well, I will assemble the council. Then you can tell us about what you found out.}
{1300}{}{我看你很有信心。在更好的情况下，一个外国人出现在议会会议上是不可想象的。但危急时刻需要采取危急措施。好吧，我来召集议会会议。然后你可以告诉我们你的发现。}
#{1301}{}{And I will. [Take part in the council meeting.]}
{1301}{}{我会的。[参加议会会议。]}
#{1350}{}{Did you manage to find out what happened to the soldiers we sent?}
{1350}{}{你弄清楚我们派去的士兵发生什么事了吗？}
#{1351}{}{I found them in a cellar in one of the houses in the Dead Quarter. All of them dead. Someone must've massacred them. It wasn't a pretty sight.}
{1351}{}{我在死区一所房子的地窖里发现了他们。他们都死了，有人屠杀了他们。那景象并不好看。}
#{1352}{}{I found them in a cellar in one of the houses in the Dead Quarter. All of them dead. Someone must've massacred them. It wasn't a pretty sight.}
{1352}{}{我在死区一所房子的地窖里发现了他们。他们都死了，有人屠杀了他们。那景象并不好看。}
#{1353}{}{I'd like to know what you found out about the suspicious man in the Wild Paradise. Is he really working for the Anonym as he said?}
{1353}{}{我想知道关于狂野天堂那个可疑的人你有什么发现。他真的像他说的那样为匿名者工作吗？}
#{1354}{}{I'd like to know what you found out about the suspicious man in the Wild Paradise. Is he really working for the Anonym as he said?}
{1354}{}{我想知道关于狂野天堂那个可疑的人你有什么发现。他真的像他说的那样为匿名者工作吗？}
#{1355}{}{Not yet. I need more time.}
{1355}{}{还没有。我需要更多的时间。}
#{1400}{}{[Elisa sighs.] I need to convene the council immediately. That is the greatest blow Anonym has ever dealt to the empire. I need you to take part as well. You are the only one who has seen the dead soldiers with your own eyes.}
{1400}{}{[伊莉莎叹了一口气。] 我需要立即召集议会。这是匿名者对帝国最大的打击。我需要你也参加。你是唯一亲眼见过阵亡士兵的人。}
#{1401}{}{[Elisa sighs.] I need to convene the council immediately. That is the greatest blow Anonym has ever dealt to the empire. I need you to take part as well. You are the only one who has seen the dead soldiers with your own eyes.}
{1401}{}{[伊莉莎叹了一口气。] 我需要立即召集议会。这是匿名者对帝国最大的打击。我需要你也参加。你是唯一亲眼见过阵亡士兵的人。}
#{1402}{}{As you wish. [Take part in a council meeting.]}
{1402}{}{如你所愿。[参加议会会议。]}
#{1450}{}{I must apologize to you. Council meetings aren't usually this explosive. The death of so many loyal men has hit us hard. As for your reward, you can collect it from supply officer Margaret Danridge. She works at the street to the side of the entrance to this building. I do not possess any sum of your money myself. [She goes silent for a moment.] There is also one other thing I need to talk to you about.}
{1450}{}{我必须向你道歉。议会会议通常不会这么激烈。这么多忠诚的人的死对我们打击很大。至于你的报酬，你可以从供应官玛格丽特·丹德里奇那里领取。她在这栋大楼入口旁边的街道上工作。我自己没有你的钱。[她沉默了一会儿。] 还有一件事我需要和你谈谈。}
#{1451}{}{Go on. What's the matter?}
{1451}{}{继续。怎么了？}
#{1452}{}{I hope you don't skimp on wages here. Go on then.}
{1452}{}{我希望你在这里不要克扣工资。接着说。}
#{1500}{}{The informant that was supposed to meet with the imperial squad contacted me again. In his message, he said that there wasn't anyone at the meeting spot. That's why he suggested another meeting in an abandoned house in the north-eastern Dead Quarter, where he's hiding now. I don't believe him a word. There's a real possibility that it's just another of Anonym's men. But we have no other lead, and as you've heard, I can no longer count on Aran's help. I want you to meet him alone. I hope you'll succeed where our soldiers have failed.}
{1500}{}{本该与帝国小队会面的线人又联系了我。他在留言中说，在会面地点没有人。这就是为什么他建议在死区东北部的一所废弃的房子里再见面，他现在就藏在那里。我一点也不相信他。很有可能只是匿名者的另一个手下。但我们没有其他线索，你也听说了，我不能再指望阿朗的帮助了。我想让你单独去见他。我希望你能在我们士兵失败的地方取得成功。}
#{1501}{}{The informant that was supposed to meet with the imperial squad contacted me again. In his message, he said that there wasn't anyone at the meeting spot. That's why he suggested another meeting in an abandoned house in the north-eastern Dead Quarter, where he's hiding now. I don't believe him a word. There's a real possibility that it's just another of Anonym's men. But we have no other lead, and as you've heard, I can no longer count on Aran's help. I want you to meet him alone. I hope you'll succeed where our soldiers have failed.}
{1501}{}{本该与帝国小队会面的线人又联系了我。他在留言中说，在会面地点没有人。这就是为什么他建议在死区东北部的一所废弃的房子里再见面，他现在就藏在那里。我一点也不相信他。很有可能只是匿名者的另一个手下。但我们没有其他线索，你也听说了，我不能再指望阿朗的帮助了。我想让你单独去见他。我希望你能在我们士兵失败的地方取得成功。}
#{1502}{}{I can try. Goodbye, Adviser Elisa.}
{1502}{}{我可以试试。再见，伊莉莎顾问。}
#{1550}{}{Have you spoken to the informant? I'd like to know if all this grief brought some results at least.}
{1550}{}{你和线人谈过了吗？我想知道这些悲伤是否至少带来了一些结果。}
#{1551}{}{Have you spoken to the informant? I'd like to know if all this grief brought some results at least.}
{1551}{}{你和线人谈过了吗？我想知道这些悲伤是否至少带来了一些结果。}
#{1552}{}{Relax. He told me what we needed to know. Anonym's secret hideout is located in a cellar beneath a certain abandoned house in the Dead Quarter. He and his accomplices supposedly regularly meet there in secret. The informant doesn't know the time of their next meeting yet, but as soon as he finds out, he'll contact you directly. I think we can rely on it.}
{1552}{}{放松。他告诉了我我们需要知道的。匿名者的秘密藏身之处位于死区一栋废弃房子下面的地窖里。据说他和他的同伙定期在那里秘密会面。线人还不知道他们下次见面的时间，但一旦他知道了，他会直接联系你。我想我们可以信赖它。}
#{1553}{}{I'll go to him right now. See you later.}
{1553}{}{我现在就去找他。待会儿见。}
#{1554}{}{There's been a bit of an inconvenience. Things got out of hand and... The informant is dead, I killed him. He gave me no choice, really.}
{1554}{}{有一点不方便。事情失去了控制…线人死了，是我杀了他。他让我别无选择，真的。}
#{1555}{}{There's been a bit of an inconvenience. Things got out of hand and... The informant is dead, I killed him. He gave me no choice, really.}
{1555}{}{有一点不方便。事情失去了控制…线人死了，是我杀了他。他让我别无选择，真的。}
#{1600}{}{Good work. You can collect your well-earned payment from the supply officer. I'll try to let you know as soon as the informant reports in. I see you have an older model of Pip-Boy. Is it still functional?}
{1600}{}{干得好。你可以从供应官那里领取你应得的报酬。线人一到我就会尽快通知你。我看到你有一款老式的哔哔小子。它还能用吗？}
#{1601}{}{Good work. You can collect your well-earned payment from the supply officer. I'll try to let you know as soon as the informant reports in. I see you have an older model of Pip-Boy. Is it still functional?}
{1601}{}{干得好。你可以从供应官那里领取你应得的报酬。线人一到我就会尽快通知你。我看到你有一款老式的哔哔小子。它还能用吗？}
#{1602}{}{As far as I know, yes. Why do you ask?}
{1602}{}{据我所知，是的。你为什么这么问？}
#{1650}{}{Excellent, that will save us a lot of time. I can send a message to it when I know the time of Anonym's next meeting. But first you'll have to connect it to the imperial network. All you need to do is enter the password "Theodor" into any free terminal here in the palace. A Pip-Boy connector will extend from it, so just connect your Pip-Boy and the computer will take care of the rest. The range of our network is limited to a small area around the City, so try to stay nearby. It won't reach you outside Albuquerque.}
{1650}{}{太好了，这会节省我们很多时间。我知道匿名者下次会议的时间后就可以给它发消息。但首先你得把它连接到帝国网络上。你所要做的就是输入密码“Theodor”进入宫殿里的任意一个免费终端。一个哔哔小子连接器将从它延伸出来，所以只需连接你的哔哔小子，计算机将负责其余部分。我们的网络范围仅限于城市周围的一小块区域，所以尽量留在附近。出了阿尔伯克基你就收不到。}
#{1651}{}{Alright, Adviser Elisa. I'll do that.}
{1651}{}{好了，伊莉莎顾问。我会这么做的。}
#{1700}{}{You're finally here. I was starting to get worried my message didn't reach you. A group that will set off for Anonym's base at night needs to be prepared immediately. Because there's a risk that the information could be leaked to our enemies, I couldn't initiate too many people into the plan, but I still managed to put together a small squad of volunteers from the imperial army. However, they won't accomplish a great task like this alone. They will need all the help they can get.}
{1700}{}{你终于来了。我都开始担心你没收到我的信息了。一个将在夜间出发前往匿名者基地的小队需要立即做好准备。因为有信息泄露给敌人的风险，所以我不能让太多人参与这个计划，但我还是设法从帝国军队中组织了一个小队。然而，他们无法独自完成这样一项伟大的任务。他们需要所有能得到的帮助。}
#{1701}{}{You're finally here. I was starting to get worried you'd never come back. I tried to send you a message, but your Pip-Boy still isn't connected to the imperial network. We have a chance to catch Anonym. We almost started without you. A group that will set off for Anonym's base at night needs to be prepared immediately. Because there's a risk that the information could be leaked to our enemies, I couldn't initiate too many people into the plan, but I still managed to put together a small squad of volunteers from the imperial army. However, they won't accomplish a great task like this alone. They will need all the help they can get.}
{1701}{}{你终于来了。我都开始担心你再也不会回来了，我试着给你发消息，但你的哔哔小子还是没有连接到帝国网络。我们有机会抓住匿名者。我们差点就开始了。一个将在夜间出发前往匿名者基地的小队需要立即做好准备。因为有信息泄露给敌人的风险，所以我不能让太多人参与这个计划，但我还是设法从帝国军队中组织了一个小队。然而，他们无法独自完成这样一项伟大的任务。他们需要所有能得到的帮助。}
#{1702}{}{I hope we won't fail you and finally capture Anonym.}
{1702}{}{我希望我们不会让你失望，最终抓住匿名者。}
#{1703}{}{Alright. I just hope your people won't get in my way.}
{1703}{}{好吧。我只希望你的人不会妨碍我。}
#{1750}{}{The imperial soldiers with you at your side surely won't. But you must be very careful. Anonym is capable of anything and will certainly try some deceit. You mustn't let him outsmart you.}
{1750}{}{与你并肩作战的帝国士兵当然不会，但你必须非常小心。匿名者无所不能，肯定会尝试一些欺骗。你不能让他比你聪明。}
#{1751}{}{You don't have to worry about that. Anonym's days are numbered. [Wait until midnight and head for his hideout with the soldiers.]}
{1751}{}{你不用担心这个。匿名者的日子屈指可数了。[等到午夜和士兵们一起去他的藏身处。]}
#{1800}{}{[Elisa looks tense.] Speak, quickly. Did you manage to kill the foul traitor?}
{1800}{}{[伊莉莎看起来很紧张。]快说。你杀了那个卑鄙的叛徒了吗？}
#{1801}{}{[Nod.] Anonym is dead. It was Adviser Aran.}
{1801}{}{[点头。] 匿名者死了。是阿朗顾问。}
#{1850}{}{So it's really true then. While you were gone, we found letters in Aran's quarters in which he wrote about his plans to assassinate emperor Myzrael and take his place. A handful of his most loyal followers was to help him with that. I was hoping that they were just fakes that someone planted there. But I have no choice but to believe them now.}
{1850}{}{所以这是真的。你不在的时候，我们在阿朗的住处发现了一些信件，他在信中说他计划刺杀米泽列皇帝并取代他的位置。他的几个最忠实的追随者帮了他。我还希望那只是有人栽赃的赝品。但现在我别无选择，只能相信他们。}
#{1851}{}{So it's really true then. While you were gone, we found letters in Aran's quarters in which he wrote about his plans to assassinate emperor Myzrael and take his place. A handful of his most loyal followers was to help him with that. I was hoping that they were just fakes that someone planted there. But I have no choice but to believe them now.}
{1851}{}{所以这是真的。你不在的时候，我们在阿朗的住处发现了一些信件，他在信中说他计划刺杀米泽列皇帝并取代他的位置。他的几个最忠实的追随者帮了他。我还希望那只是有人栽赃的赝品。但现在我别无选择，只能相信他们。}
#{1852}{}{What will you do then?}
{1852}{}{那你要做什么？}
#{1853}{}{I don't care about the empire's problems. I want my caps.}
{1853}{}{我不在乎帝国的问题。我要我的瓶盖。}
#{1900}{}{His betrayal must not come out. The people of the empire could not bear such a painful revelation. We must protect them from the slightest suspicion. And we'll start with you. You won't receive your reward publicly to avoid unnecessary turmoil. You'll get it from an officer that will be waiting for you in the Dead Quarter. And after that, try to avoid the empire. It will be for the best.}
{1900}{}{他的背叛不能泄露出去。帝国的人民无法忍受如此痛苦的揭露。我们必须保护他们不受丝毫怀疑。我们从你开始。为了避免不必要的混乱，你不会公开获得奖励。你会从一个在死区等着你的军官那里得到它。在那之后，尽量避开帝国。这是最好的结果。}
#{1901}{}{If you say so, Adviser Elisa. Goodbye.}
{1901}{}{依你所愿，伊莉莎顾问。再见。}
#{1950}{}{Yes, you have certainly earned them. However, you cannot receive them here. Aran's betrayal must not come out - for the good of the empire. Receiving your reward publicly would only bring unnecessary attention. You'll get your pay from an officer that will be waiting for you in the Dead Quarter. And after that, try to avoid the City. It will be for the best.}
{1950}{}{是的，这是你应得的。但是，您不能在这里接收。为了帝国的利益，阿朗的背叛不能被公之于众。公开接受奖励只会带来不必要的关注。你会从一个在死区等你的军官那里拿到报酬。在那之后，尽量避开城市。这是最好的结果。}
#{1951}{}{If you say so, Adviser Elisa. Goodbye.}
{1951}{}{依你所愿，伊莉莎顾问。再见。}
#{2000}{}{[Empress Elisa looks surprised.] I certainly didn't expect you here. Have you already collected your reward?}
{2000}{}{[伊莉莎女王看起来很惊讶。]我真没想到你会在这儿。你已经拿到报酬了吗？}
#{2001}{}{[Empress Elisa looks surprised.] I certainly didn't expect you here. Have you already collected your reward?}
{2001}{}{[伊莉莎女王看起来很惊讶。]我真没想到你会在这儿。你已经拿到报酬了吗？}
#{2002}{}{Stop pretending. I know about everything. Your plan with the mercenaries didn't work. I killed them all, so they won't be doing any of your dirty work anymore.}
{2002}{}{别装了。我什么都知道。你和雇佣兵的计划没有奏效。我把他们都杀了，这样他们就不会再为你做任何肮脏的勾当了。}
#{2003}{}{Stop pretending. I know about everything. Your plan with the mercenaries didn't work. I killed them all, so they won't be doing any of your dirty work anymore.}
{2003}{}{别装了。我什么都知道。你和雇佣兵的计划没有奏效。我把他们都杀了，这样他们就不会再为你做任何肮脏的勾当了。}
#{2004}{}{No, I completely forgot. Thanks for a reminder.}
{2004}{}{不，我完全忘了。谢谢提醒。}
#{2005}{}{Yees! Okies.}
{2005}{}{是啊！好啊啊。}
#{2006}{}{Noes! There bam bam. [Point a finger at her.] Bad!}
{2006}{}{不！砰砰。[用手指着她。]坏！}
#{2050}{}{[She grins.] Who would've thought you'd be of such good service to me. That band of cut-throats was starting to become a nuisance. Had they tried to blackmail me, my position would've been seriously threatened. But now, I don't have to worry about that anymore. As for you, our cooperation is over. Since you are completely powerless compared to me, I can afford to be generous and spare your pathetic life. You should be grateful and never bother me again.}
{2050}{}{[她笑着说。]谁能想到你会对我这么有帮助。那帮杀人如麻的家伙开始惹人讨厌了。如果他们试图敲诈我，我的职位就会受到严重威胁。但现在，我再也不用担心了。至于你，我们的合作结束了。既然你和我相比是完全无能为力的，我可以慷慨地饶了你可怜的生命。你应该心存感激，别再来烦我了。}
#{2051}{}{You'll excuse me for not dancing in joy over your mercy. But have it your way. There's nothing for me here anyway. Goodbye, empress Elisa.}
{2051}{}{请原谅我没有为你的仁慈高兴得手舞足蹈。但要按你的方式去做。反正这里也没什么适合我的。再见，伊莉莎女王。}
#{2052}{}{You won't get rid of me that easily. Remember, one day I will find a way to take my revenge. And that will be the day we meet again.}
{2052}{}{你没那么容易摆脱我。记住，总有一天我会找到复仇的方法。那将是我们重逢的日子。}
#{2053}{}{Enough of this. Time to pay for your sins, you treacherous whore!}
{2053}{}{够了。是时候为你的罪付出代价了，你这个背信弃义的婊子！}
#{2054}{}{ Don't make the same mistake as Lystra, who tried to gather support against me. Poor girl, our soldiers found her body outside the walls. It seems that the ghouls are to blame. She never should have left the empire. The outside world is too dangerous.}
{2054}{}{ 不要犯和莱斯特拉一样的错误，她试图集结力量反对我。可怜的姑娘，我们的士兵在墙外发现了她的尸体。看来僵尸是罪魁祸首。她根本就不该离开帝国。外面的世界太危险了。}
#{2100}{}{[Waiting in a dank, foul-smelling tunnel wasn't exactly pleasant. You seem to be in a part of the pre-war Albuquerque sewer system. Boredom slowly starts to overcome you, when the present silence is interrupted with the sound of approaching footsteps. The mercenaries stop glaring at you and turn their eyes to the approaching person in brown robes. Judging from the respect shown, it must be Anonym. He stands completely still for a moment, then turns to the mercenaries that gathered there. Under the hood, you spot the face of Adviser Elisa.]}
{2100}{}{[在潮湿、恶臭的隧道里等待并不是件愉快的事。你似乎置身于战前阿尔伯克基下水道系统的一部分。无聊慢慢地开始战胜你，此时的沉默被脚步声打断。雇佣兵不再盯着你，而是把目光转向穿着棕色长袍的人。从所表现出的尊重程度来看，这一定是匿名者。他一动不动地站了一会儿，然后转向聚集在那里的雇佣兵。在引擎盖下，你看到了顾问伊莉莎的脸。]}
#{2101}{}{But that's Elisa from the empire! Someone must've blown our cover.}
{2101}{}{但那是帝国的伊莉莎！肯定有人暴露了我们的身份。}
#{2102}{}{I wouldn't have expected that you, of all people, would be fighting for the other side.}
{2102}{}{我没想到在所有人中，你会为另一方而战。}
#{2103}{}{I wouldn't have expected that you, of all people, would be fighting for the other side.}
{2103}{}{我没想到在所有人中，你会为另一方而战。}
#{2104}{}{Nooo. Hoo! [Flail your arms around.] You baaad!}
{2104}{}{不。呼！[挥动你的手臂。] 你这个坏蛋！}
#{2150}{}{[Elisa pays you no attention and begins her speech.] You have all done much work, and even risked your lives for my sake. And you have been properly paid for it. But now, the time has come for the most important task yet. Soon, Aran and his elite squad will enter this place. They were given a tip that they would find Anonym here. But they will find only you, and it is you who must make sure that this place becomes their grave. If you succeed, your reward will be great.}
{2150}{}{[伊莉莎没有关注你，开始她的演讲。]你们都做了很多工作，甚至为了我冒着生命危险。你也因此得到了应得的报酬。但现在，最重要的任务已经到来。很快，阿郎和他的精英小队就会进入这个地方。他们得到消息说能在这里找到匿名者。但他们只会找到你，而你必须确保这个地方成为他们的坟墓。如果你成功了，你的回报将是巨大的。}
#{2151}{}{Now everything is finally starting to make sense...}
{2151}{}{现在一切终于开始有意义了…}
#{2200}{}{[Her speech is over, a few mercenaries whoop enthusiastically. Elisa turns to you.] We've seen each other already. You were very convincing during the council meeting. I'm sure you will succeed in the next task I'm planning to give you as well. When you send Adviser Aran to the next world, you need to take the patch on the right sleeve of his jumpsuit and bring it to me in the palace. From all the mercenaries, you're the only one that's ever been there. Therefore, you are the ideal person for delivering the proof of Aran's death.}
{2200}{}{[她的演讲结束了，几个雇佣兵热情地欢呼起来。伊莉莎转向你。]我们已经见过面了。你在议会上很有说服力。我相信你也会成功完成我计划交给你的下一个任务。当你把阿朗顾问送到另一个世界时，你需要取下他连体衣右袖上的补丁，带到宫殿里给我。在所有的雇佣兵中，你是唯一一个去过那里的。因此，你是传递阿郎死亡证据的最佳人选。}
#{2201}{}{[Her speech is over, a few mercenaries whoop enthusiastically. Elisa turns to you.] We've seen each other already. You were very convincing during the council meeting. I'm sure you will succeed in the next task I'm planning to give you as well. When you send Adviser Aran to the next world, you need to take the patch on the right sleeve of his jumpsuit and bring it to me in the palace. From all the mercenaries, you're the only one that's ever been there. Therefore, you are the ideal person for delivering the proof of Aran's death.}
{2201}{}{[她的演讲结束了，几个雇佣兵热情地欢呼起来。伊莉莎转向你。]我们已经见过面了。你在议会上很有说服力。我相信你也会成功完成我计划交给你的下一个任务。当你把阿朗顾问送到另一个世界时，你需要取下他连体衣右袖上的补丁，带到宫殿里给我。在所有的雇佣兵中，你是唯一一个去过那里的。因此，你是传递阿郎死亡证据的最佳人选。}
#{2202}{}{Understood. I'll go right to you when I have it.}
{2202}{}{理解。我拿到后马上去找你。}
#{2250}{}{[Elisa scowls.] How did this idiot get here? This was supposed to be a top secret meeting. Terminate him immediately!}
{2250}{}{[伊莉莎皱眉。]这个白痴是怎么到这儿来的？这本该是一次绝密会议。立刻杀了他！}
#{2251}{}{[Elisa scowls.] How did this idiot get here? This was supposed to be a top secret meeting. Terminate her immediately!}
{2251}{}{[伊莉莎皱眉。]这个白痴是怎么到这儿来的？这本该是一次绝密会议。立刻杀了他！}
#{2252}{}{Hue? Argh-Ar!}
{2252}{}{哈啥？啊！}
#{2300}{}{[Elisa seems agitated.] Come on, start talking. Is Aran dead? Show me the patch from his sleeve.}
{2300}{}{[伊莉莎似乎很激动。]来吧，快说。阿朗死了吗？给我看看他袖子上的补丁。}
#{2301}{}{You can see for yourself. [Show her the scrap of Aran's jumpsuit.]}
{2301}{}{你可以自己看看。[给她看阿朗的连身衣碎片。]}
#{2302}{}{Eh... There's been a slight complication. I'll be right back.}
{2302}{}{呃…有点小麻烦。我马上就回来。}
#{2450}{}{[She smiles.] I owe you my thanks for your services. I would've surely succeeded even without them, but I am grateful to you regardless. You can collect your well-earned reward from a supply officer on the street to the side of the entrance to this building. And should I have need of you again, I'll try to let you know. I see you have an older model of Pip-Boy. Is it still functional?}
{2450}{}{[她微笑着说。]我对你的服务表示感谢。即使没有他们，我也一定能成功，但我还是很感激你。你可以从这座大楼入口一侧的街道上供应官那里领取你应得的报酬。如果我再需要你，我会尽量让你知道的。我看到你有一款老式的哔哔小子。它还能用吗？}
#{2451}{}{Of course it is. Why do you ask?}
{2451}{}{当然了。你为什么这么问？}
#{2500}{}{[She smiles.] I owe you my thanks for your services. I would've surely succeeded even without them, but I am grateful to you regardless. You can collect your well-earned reward from a supply officer on the street to the side of the entrance to this building.}
{2500}{}{[她微笑着说。]我对你的服务表示感谢。即使没有他们，我也一定能成功，但我还是很感激你。你可以从这座大楼入口一侧的街道上供应官那里领取你应得的报酬。}
#{2501}{}{Thank you, empress. Farewell.}
{2501}{}{谢谢你，女王。再见。}
#{2502}{}{Can I ask you a few questions before I leave?}
{2502}{}{我走之前能问你几个问题吗？}
#{2550}{}{Through it, I can send you a message should I find other use for you. But don't count on it too much. All you need to do to connect into the network is to enter the password "Theodor" into any free terminal here in the palace. A Pip-Boy connector will extend from it, so just connect your Pip-Boy and the computer will take care of the rest.}
{2550}{}{通过它，我可以给你发送信息，如果我能为你找到其他的用途。但别指望太多。要连接到网络，只需在宫殿内的任何免费终端输入密码“Theodor”即可。一个哔哔小子连接器将从它延伸出来，所以只需连接你的哔哔小子，计算机将负责其余的工作。}
#{2551}{}{Very well, empress Elisa. I'll do that. Until we meet again.}
{2551}{}{很好，伊莉莎女王。我会这么做的。直到我们下次会面。}
#{2552}{}{Oh. Can I ask you a few questions before I leave?}
{2552}{}{哦。我走之前能问你几个问题吗？}
#{2600}{}{I don't see a reason why you couldn't. But don't take too much of my time.}
{2600}{}{我看不出你为什么不能。但不要占用我太多时间。}
#{2601}{}{I don't see a reason why you couldn't. But don't take too much of my time.}
{2601}{}{我看不出你为什么不能。但不要占用我太多时间。}
#{2602}{}{I want to know what actually led you to creating Anonym.}
{2602}{}{我想知道你为什么要创造匿名者。}
#{2603}{}{I want to know what actually led you to creating Anonym.}
{2603}{}{我想知道你为什么要创造匿名者。}
#{2604}{}{I was curious how Myzrael's subjects took his death.}
{2604}{}{我很好奇米泽列的臣民对他的死有何反应。}
#{2605}{}{Can you tell me about your plans for the future of the empire?}
{2605}{}{你能告诉我你对帝国未来的计划吗？}
#{2606}{}{Tell me what you're going to do with the Vault.}
{2606}{}{你打算怎么处理避难所。}
#{2607}{}{Actually, there's nothing I need to ask. Goodbye for now, empress Elisa.}
{2607}{}{实际上，我没什么需要问的。再见了，伊莉莎女王。}
#{2650}{}{What do you think? I wanted to rule the empire. There's no one more suited to that post than me. But, according to the succession line, my turn would come only after many years, or not at all. That's why I started to plan the coup. The intrigue with Anonym had a lot of holes, but given how loyal the imperial army is to Aran, I had no other choice. And, as you might have noticed, my plan worked. That is all that matters.}
{2650}{}{你怎么看？我想统治整个帝国。没有人比我更适合这个职位了。但是，根据继承顺序，我要在很多年之后才会轮到，或者根本就不会轮到我。这就是我开始策划政变的原因。与匿名者的阴谋有很多漏洞，但考虑到帝国军队对阿朗的忠诚，我别无选择。你可能已经注意到了，我的计划成功了。这才是最重要的。}
#{2651}{}{What do you think? I wanted to rule the empire. There's no one more suited to that post than me. But, according to the succession line, my turn would come only after many years, or not at all. That's why I started to plan the coup. The intrigue with Anonym had a lot of holes, but given how loyal the imperial army is to Aran, I had no other choice. And, as you might have noticed, my plan worked. That is all that matters.}
{2651}{}{你怎么看？我想统治整个帝国。没有人比我更适合这个职位了。但是，根据继承顺序，我要在很多年之后才会轮到，或者根本就不会轮到我。这就是我开始策划政变的原因。与匿名者的阴谋有很多漏洞，但考虑到帝国军队对阿朗的忠诚，我别无选择。你可能已经注意到了，我的计划成功了。这才是最重要的。}
#{2652}{}{So all you wanted was power?}
{2652}{}{所以你想要的只是权力？}
#{2653}{}{Got it. I was also curious how Myzrael's subjects took his death.}
{2653}{}{明白了。我也很好奇米泽列的臣民对他的死有何反应。}
#{2654}{}{Can you also tell me about your plans for the future of the empire?}
{2654}{}{你能告诉我你对帝国未来的计划吗？}
#{2655}{}{Tell me what you're going to do with the Vault.}
{2655}{}{你打算怎么处理避难所。}
#{2656}{}{That will be all. I won't keep you any longer.}
{2656}{}{就这样吧。我不耽误你时间了。}
#{2700}{}{*All* I wanted? I don't consider ruling the only civilized society left in the entire area a small thing. And this isn't just about me. The empire's potential is determined by the ability of its ruler. With Myzrael, it was weak. And with that dim-witted soldier Aran it would be no stronger. I will be different. I will not allow anyone to stand in the way of our progress.}
{2700}{}{“全部”是我想要的吗？我不认为统治整个地区仅存的文明社会是件小事。这不是我一个人的事。帝国的潜力取决于统治者的能力。对米泽列来说，它很脆弱。有了那个愚蠢的士兵阿朗，它也不会更强大。我会变得不一样。我不会允许任何人阻挡我们前进的道路。}
#{2701}{}{I was also curious how Myzrael's subjects took his death.}
{2701}{}{我也很好奇米泽列的臣民是如何看待他的死亡的。}
#{2702}{}{Can you tell me about your plans for the future of the empire?}
{2702}{}{你能告诉我你对帝国未来的计划吗？}
#{2703}{}{Tell me what you're going to do with the Vault.}
{2703}{}{你打算怎么处理避难所。}
#{2704}{}{That will be all. I won't keep you any longer.}
{2704}{}{就这样吧。我不耽误你时间了。}
#{2750}{}{I hope you mean *my* subjects. As for them, they all believe the official report. That tale of poor Myzrael, so crestfallen with the betrayal of his beloved Adviser that his heart couldn't take it. The people are so indoctrinated by imperial propaganda that they will believe almost anything.}
{2750}{}{我希望你指的是“我” 的臣民。至于他们，他们都相信官方的报道。关于可怜的米泽列的故事，因为他对心爱的顾问背叛而沮丧到他的心无法承受。人民被帝国的宣传灌输得如此之深，以至于他们几乎会相信任何事情。}
#{2751}{}{No doubt. And what actually led you to creating Anonym?}
{2751}{}{毫无疑问。是什么让你创造了匿名者？}
#{2752}{}{Can you also tell me about your plans for the future of the empire?}
{2752}{}{你能告诉我你对帝国未来的计划吗？}
#{2753}{}{Tell me what you're going to do with the Vault.}
{2753}{}{你打算怎么处理避难所。}
#{2754}{}{Thank you for your answer. Goodbye for now, empress Elisa.}
{2754}{}{谢谢你的解答。再见了，伊莉莎女王。}
#{2800}{}{First of all, I must make sure that the empire has any future at all. Myzrael's pathetic rule made it into a degenerate place. That will have to change. I have already disbanded the imperial council, next, I will gradually concentrate all the power in my hands. The renewal would not be possible without that. Only a strong empress can create a powerful empire. I will not stop until I succeed.}
{2800}{}{首先，我必须确保帝国还有未来。米泽列可悲的统治让它变成了堕落的地方。这种情况必须改变。我已经解散了帝国议会，接下来，我将逐步把所有的权力集中在我手中。如果没有这一点，复兴是不可能的。只有强大的女王才能创造强大的帝国。不成功我是不会罢休的。}
#{2801}{}{You sure don't aim low. And what actually led you to creating Anonym?}
{2801}{}{你的目标肯定不低。是什么促使你创建了匿名者？}
#{2802}{}{I was also curious how Myzrael's subjects took his death.}
{2802}{}{我也很好奇米泽列的臣民是如何看待他的死亡的。}
#{2803}{}{Tell me what you're going to do with the Vault.}
{2803}{}{你打算怎么处理避难所。}
#{2804}{}{Thank you for your answer. I won't keep you any longer.}
{2804}{}{谢谢你的解答。我不耽误你时间了。}
#{2850}{}{I find the trustworthiness of such a man to be rather dubious. It is likely he was simply bragging or trying to make a profit off you. Nothing unusual in that backwater world of yours. Still, I will have him investigated. You should concentrate on your task instead and find our soldiers as soon as possible.}
{2850}{}{我觉得这样一个人的可信度相当可疑。很可能他只是在吹牛或是想从你身上获利。在你那个闭塞的世界里没什么不寻常的。不过，我还是会让人调查他。你应该专注于你的任务，尽快找到我们的士兵。}
#{2851}{}{Who is this Aran you spoke of, anyway? Can he be trusted?}
{2851}{}{你说的阿朗是谁？他能被信任吗？}
#{2852}{}{I will go look for them immediately. Goodbye for now, Adviser Elisa.}
{2852}{}{我马上去找他们。再见了，伊莉莎顾问。}
#{2900}{}{There was no such man in the Wild Paradise. He probably managed to disappear in time. Any knowledge of Anonym that he might have had disappeared with him. But you don't have to worry about that. You are supposed to find the lost soldiers. Until then, don't waste your time on other things.}
{2900}{}{在狂野天堂里没有这样的人。他可能及时消失了。任何关于“匿名者”的信息都可能随他一起消失。但你不用担心这个。你应该去找那些失踪的士兵。在那之前，不要把时间浪费在其他事情上。}
#{2901}{}{I've already found them, in a cellar in one of the houses in the Dead Quarter. All of them dead. Someone must've massacred them. It wasn't a pretty sight.}
{2901}{}{我已经找到了，在死区一栋房子的地窖里。他们都死了。一定是有人屠杀了他们。那景象并不好看。}
#{2902}{}{I've already found them, in a cellar in one of the houses in the Dead Quarter. All of them dead. Someone must've massacred them. It wasn't a pretty sight.}
{2902}{}{我已经找到了，在死区一栋房子的地窖里。他们都死了。一定是有人屠杀了他们。那景象并不好看。}
#{2903}{}{Very well, Adviser Elisa.}
{2903}{}{很好，伊莉莎顾问。}
#{2950}{}{[Elisa seems hostile.] You had your task, and, as I have heard, you did not follow my instructions. Your negligence is threatening my plans. I will not tolerate that.}
{2950}{}{[伊莉莎怀有敌意。]你有你的任务，而且，正如我所听说的，你没有听从我的指示。你的疏忽正威胁着我的计划。我不会容忍的。}
#{2951}{}{[Elisa seems hostile.] You had your task, and, as I have heard, you did not follow my instructions. Your negligence is threatening my plans. I will not tolerate that.}
{2951}{}{[伊莉莎怀有敌意。]你有你的任务，而且，正如我所听说的，你没有听从我的指示。你的疏忽正威胁着我的计划。我不会容忍的。}
#{2952}{}{And what are you going to do about it?}
{2952}{}{你打算怎么办？}
#{2953}{}{He?}
{2953}{}{哈？}
#{3000}{}{I do not believe I sent for you. What do you want?}
{3000}{}{我不相信是我派人来找你的。你想要什么？}
#{3001}{}{Can I ask you a few questions?}
{3001}{}{我能问你几个问题吗？}
#{3002}{}{Can I ask you a few questions?}
{3002}{}{我能问你几个问题吗？}
#{3003}{}{Nothing at all, empress Elisa. I will leave immediately.}
{3003}{}{没什么，伊莉莎女王。我马上就走。}
#{3004}{}{Huh. Ech.}
{3004}{}{呵呵。呃。}
#{3050}{}{My message has reached you then, good. As you might have heard, the lower floors of the Vault have not been under empire's control for some time. The Mutant Hunters forced us out of them. That's a problem that requires an immediate solution. And that is why I would like to make use of your services once again. Our previous cooperation has been beneficial for both sides. It helped me to the position of an empress, and it helped you to a hefty profit. Why not continue for a time?}
{3050}{}{你收到我的信息了，很好。你可能已经听说了，避难所的下层已经有一段时间不受帝国的控制了。变种猎人把我们赶了出来。这是一个需要立即解决的问题。这就是为什么我想再次使用你的服务。我们过去的合作对双方都是有益的。它帮我登上了女王的位置，也帮你赚了一大笔钱。为什么不继续一段时间呢?}
#{3051}{}{My message has reached you then, good. As you might have heard, the lower floors of the Vault have not been under empire's control for some time. The Mutant Hunters forced us out of them. That's a problem that requires an immediate solution. And that is why I would like to make use of your services once again. Our previous cooperation has been beneficial for both sides. It helped me to the position of an empress, and it helped you to a hefty profit. Why not continue for a time?}
{3051}{}{你收到我的信息了，很好。你可能已经听说了，避难所的下层已经有一段时间不受帝国的控制了。变种猎人把我们赶了出来。这是一个需要立即解决的问题。这就是为什么我想再次使用你的服务。我们过去的合作对双方都是有益的。它帮我登上了女王的位置，也帮你赚了一大笔钱。为什么不继续一段时间呢？}
#{3052}{}{I won't say no to another opportunity. What exactly do you want to do about the Hunters?}
{3052}{}{我不会拒绝另一个机会的。你到底想拿猎人们怎么办？}
#{3053}{}{Not this time. I Have other things to worry about.}
{3053}{}{这次不行。我还有别的事要操心。}
#{3054}{}{Huh?!}
{3054}{}{呵呵？！}
#{3100}{}{I want the Hunters removed from the Vault. Whatever the cost! If that foolish band of ex-raiders refuses to leave willingly, they will be removed by force. I've put colonel Parson in charge of the operation. You'll find him on the first floor of the Vault. You are the very first foreigner that will be allowed entry into the Vault. You should be grateful for the privilege - don't even think of misusing it. Act quickly. The Vault must be taken back as soon as possible.}
{3100}{}{我要把猎人们赶出避难所。无论付出什么代价！如果那群愚蠢的前入侵者拒绝自愿离开，他们将被武力驱逐。我已经让帕森上校负责这次行动了。你会在避难所的一层找到他。你是第一个被允许进入避难所的外国人。你应该对这种特权心存感激——别想滥用它。赶快行动。必须尽快夺回避难所。}
#{3101}{}{I want the Hunters removed from the Vault. Whatever the cost! If that foolish band of ex-raiders refuses to leave willingly, they will be removed by force. I've put colonel Parson in charge of the operation. You'll find him on the first floor of the Vault. You are the very first foreigner that will be allowed entry into the Vault. You should be grateful for the privilege - don't even think of misusing it. Act quickly. The Vault must be taken back as soon as possible.}
{3101}{}{我要把猎人们赶出避难所。无论付出什么代价！如果那群愚蠢的前入侵者拒绝自愿离开，他们将被武力驱逐。我已经让帕森上校负责这次行动了。你会在避难所的一层找到他。你是第一个被允许进入避难所的外国人。你应该对这种特权心存感激——别想滥用它。赶快行动。必须尽快夺回避难所。}
#{3102}{}{Anything else you can tell me about it?}
{3102}{}{还有什么能告诉我的吗？}
#{3150}{}{[Elisa seems somewhat uneasy.] Besides the Hunters, there is also something else on the lower floor of the Vault. We were unable to find out exactly what it is, but it is extremely dangerous. You will find out more here. [She gives you a holodisk.] It's a report from the recon team we sent there. It was them who discovered the Hunters' presence in the Vault. Colonel Parson will tell you the rest.}
{3150}{}{[伊莉莎似乎有些不安。]除了猎人，避难所的下层还有别的东西。我们无法查明它到底是什么，但它非常危险。您将在这里了解更多信息。[她给你一张全息光盘。]这是我们派去的侦察队的报告，正是他们发现在避难所里猎人们的存在。帕森上校会告诉你剩下的的事情。}
#{3151}{}{Alright, I'll go to him. Farewell, empress Elisa.}
{3151}{}{好吧，我去找他。再见，伊莉莎女王。}
#{3200}{}{Removing the Hunters from the Vault is our highest priority right now. You have your instructions. Do not dare to fail me.}
{3200}{}{把猎人从避难所赶出去是我们现在的首要任务。你已经得到指示了。别让我失望。}
#{3201}{}{Don't worry, I'll can handle it.}
{3201}{}{别担心，我能搞定。}
#{3202}{}{Uh.}
{3202}{}{呃。}
#{3250}{}{As you wish. But I doubt anyone will pay more for your services than the empire. Should you change your mind, you know where to find me.}
{3250}{}{如你所愿。但我怀疑没有人会为你的服务付出比帝国更多的钱。如果你改变主意了，你知道去哪找我。}
#{3251}{}{As you wish. But I doubt anyone will pay more for your services than the empire. Should you change your mind, you know where to find me.}
{3251}{}{如你所愿。但我怀疑没有人会为你的服务付出比帝国更多的钱。如果你改变主意了，你知道去哪找我。}
#{3252}{}{Don't count on it. Goodbye, empress Elisa.}
{3252}{}{别指望了。再见，伊莉莎女王。}
#{3300}{}{I see you are not in the condition for any task at all. Come back after you put yourself in order.}
{3300}{}{我看你根本不适合做任何工作。等你安顿好了再回来。}
#{3301}{}{Yaay! Hrm.}
{3301}{}{耶！哈。}
#{3350}{}{Does your return mean that you are willing to take part in removing the Mutant Hunters from the Vault?}
{3350}{}{你的回归是否意味着你愿意参与将变种猎人从避难所中赶出去？}
#{3351}{}{Guess so. But what exactly do you want to do about them?}
{3351}{}{也许吧，但是你想怎么处理他们？}
#{3352}{}{Certainly not. Goodbye, empress Elisa.}
{3352}{}{当然不是。再见，伊莉莎女王。}
#{3353}{}{Huhla.}
{3353}{}{哈拉。}
#{3400}{}{Colonel Parson has informed me that the whole Vault is now under my control. I must admit, you've done a splendid job once again. The empire is grateful for your services.}
{3400}{}{帕森上校告诉我整个避难所都在我的掌控之中。我必须承认，你又一次做得很出色。帝国感谢你的服务。}
#{3401}{}{Colonel Parson has informed me that the whole Vault is now under my control. I must admit, you've done a splendid job once again. The empire is grateful for your services.}
{3401}{}{帕森上校告诉我整个避难所都在我的掌控之中。我必须承认，你又一次做得很出色。帝国感谢你的服务。}
#{3402}{}{Thank you for the recognition. It wasn't easy.}
{3402}{}{谢谢你的认可。这并不容易。}
#{3403}{}{Hrmm.}
{3403}{}{嗯嗯。}
#{3450}{}{By reconquering the Vault, I have gained a large amount of valuable technical equipment that I can use for the good of the empire. But, most importantly, its strategic location allows me to finally deal with the Mutant Hunters. Kicking them out of the third floor was just the beginning. Let them tell themselves that they are helping us. But as soon as the situation allows me, I'll finish that desert scum once and for all.}
{3450}{}{通过重新征服避难所，我获得了大量有价值的技术设备，我可以用来为帝国造福。但最重要的是，它的战略位置让我终于可以对付变种猎人了。把他们踢出三层只是个开始。让他们告诉自己，他们是在帮助我们。但只要形势允许，我会一劳永逸地解决掉那个沙漠渣滓。}
#{3451}{}{By reconquering the Vault, I have gained a large amount of valuable technical equipment that I can use for the good of the empire. But, most importantly, its strategic location allows me to finally deal with the Mutant Hunters. Kicking them out of the third floor was just the beginning. Let them tell themselves that they are helping us. But as soon as the situation allows me, I'll finish that desert scum once and for all.}
{3451}{}{通过重新征服避难所，我获得了大量有价值的技术设备，我可以用来为帝国造福。但最重要的是，它的战略位置让我终于可以对付变种猎人了。把他们踢出三层只是个开始。让他们告诉自己，他们是在帮助我们。但只要形势允许，我会一劳永逸地解决掉那个沙漠渣滓。}
#{3452}{}{I want to know what actually led you to creating Anonym.}
{3452}{}{我想知道是什么让你创造了匿名者。}
#{3453}{}{I want to know what actually led you to creating Anonym.}
{3453}{}{我想知道是什么让你创造了匿名者。}
#{3454}{}{I was curious how Myzrael's subjects took his death.}
{3454}{}{我很好奇米泽列的臣民是如何看待他的死亡的。}
#{3455}{}{Can you tell me about your plans for the future of the empire?}
{3455}{}{你能告诉我你对帝国未来的计划吗？}
#{3457}{}{That will be all, thank you. Goodbye for now, empress Elisa.}
{3457}{}{就这样吧，谢谢，再见，伊莉莎女王。}
#{3500}{}{Do you even realize that you may have ridden us of the only clue that could lead us to Anonym? I should have realized that assigning a task of this importance to a foreigner was a mistake. I cannot let your total incompetence go without the highest punishment.}
{3500}{}{你有没有意识到你可能让我们失去了找到匿名者的唯一线索？我应该意识到把这么重要的任务交给一个外国人是个错误。我不能让你这种无能的行为不受到最严厉的惩罚。}
#{3501}{}{Do you even realize that you may have ridden us of the only clue that could lead us to Anonym? I should have realized that assigning a task of this importance to a foreigner was a mistake. I cannot let your total incompetence go without the highest punishment.}
{3501}{}{你有没有意识到你可能让我们失去了找到匿名者的唯一线索？我应该意识到把这么重要的任务交给一个外国人是个错误。我不能让你这种无能的行为不受到最严厉的惩罚。}
#{3502}{}{What, are you trying to have me killed? If I'm to die, then I'm taking you with me.}
{3502}{}{怎么，你想杀了我吗？如果我要死了，我也要带着你一起去死。}
#{3550}{}{[She looks at the piece of cloth, satisfied.] Excellent. Everything is going exactly as I hoped. Without Aran and his most loyal supporters, nothing stands in my way. Soon, I will rule over the entire empire.}
{3550}{}{[她满意地看着那块布。]太好了。一切都如我所愿。没有阿朗和他最忠实的支持者，没有什么能阻挡我。很快，我就会统治整个帝国。}
#{3551}{}{No doubt. I was happy to help.}
{3551}{}{毫无疑问。我很乐意帮忙。}
#{3552}{}{No doubt. I was happy to help.}
{3552}{}{毫无疑问。我很乐意帮忙。}
#{3553}{}{I don't care about your schemes. When will I get my money?}
{3553}{}{我不在乎你的计划，我什么时候才能拿到钱？}
#{3600}{}{You have done well, stranger. Benicio was right to hire you. It is a shame that I will have to be so ungrateful to him. See, after Aran's death, I don't have any use for him or the other mercenaries. And I don't need a bunch of vagabonds that know about my plan wandering around Albuquerque. They will have to disappear.}
{3600}{}{你做得很好，陌生人。贝尼西奥雇你是对的。真遗憾，我将不得不对他如此忘恩负义。你看，在阿朗死后，他和其他雇佣兵对我都没用了。我也不需要一群知道我计划的流浪汉在阿尔伯克基游荡。他们必须消失。}
#{3601}{}{You have done well, stranger. Benicio was right to hire you. It is a shame that I will have to be so ungrateful to him. See, after Aran's death, I don't have any use for him or the other mercenaries. And I don't need a bunch of vagabonds that know about my plan wandering around Albuquerque. They will have to disappear.}
{3601}{}{你做得很好，陌生人。贝尼西奥雇你是对的。真遗憾，我将不得不对他如此忘恩负义。你看，在阿朗死后，他和其他雇佣兵对我都没用了。我也不需要一群知道我计划的流浪汉在阿尔伯克基游荡。他们必须消失。}
#{3602}{}{And why are you telling me all this?}
{3602}{}{你为什么要告诉我这些？}
#{3650}{}{We will speak about your reward, and everything else, when I see fit. Get that into your thick skull and do not anger me again. I wouldn't want to end our so far flawless cooperation by having you executed.}
{3650}{}{等我觉得合适的时候，我们再来谈谈你的奖励和其他事情。记住这点，别再惹我生气了。我可不想以处决你来结束我们迄今为止完美的合作。}
#{3651}{}{I apologize. It won't happen again. Please, go on.}
{3651}{}{我道歉，不会再发生了，请继续。}
#{3652}{}{Only one execution is scheduled now. Your own, bitch!}
{3652}{}{现在只安排了一次执行。你自己的，贱人！}
#{3700}{}{The same thing that brought them into this unfortunate situation opened up a great opportunity for you. Get rid of Benicio and his mercenaries for me and I will let you take their whole pay. All you need to do is meet with them and conclude this unpleasant business. I will inform Benicio that I'm sending a courier with the caps to the Dead Quarter, I'm sure he'll find you once you're there. The other mercenaries will no doubt accompany him. I don't care how you deal with them. Kill them all if you want. Just make sure that they are dealt with... permanently. I don't want to see them in Albuquerque ever again.}
{3700}{}{让他们陷入这种不幸境地的同时，为你你创造了一个绝佳的机会。帮我除掉贝尼西奥和他的雇佣兵，我就把他们的钱全给你。你所要做的就是和他们见面，然后了结这件不愉快的事。我会通知贝尼西奥我要派一个带着瓶盖的信使去死区，我相信你一到那里他就会找到你的。其他的雇佣兵肯定会跟着他。我不在乎你怎么对付他们。如果你愿意，可以把他们都杀了。只要确保他们得到了处理…永久的。我再也不想在阿尔伯克基看到他们了。}
#{3701}{}{How do I know you won't decide to kill me as well?}
{3701}{}{我怎么知道你不会把我也杀了？}
#{3702}{}{Not to worry. I will take care of Benicio and the others.}
{3702}{}{别担心。我会照顾好贝尼西奥和其他人。}
#{3703}{}{I'm not doing your dirty work for you anymore. Find someone else.}
{3703}{}{我不会再为你做那些肮脏的勾当了。找别人吧。}
#{3704}{}{Will I really get some caps for the meeting?}
{3704}{}{我真的要为会面准备一些瓶盖吗？}
#{3750}{}{[Elisa smiles.] You don't have to worry about your life. I have no intention to take it. If you deal with Benecio and the mercenaries, you'll be the only one outside the imperial walls who knows about my plan. And what is a word of one person against a word of someone with the whole imperial army behind her?}
{3750}{}{[伊莉莎微笑。]你不用担心你的生活。我无意改变。如果你对付贝内西奥和那些雇佣兵，你就是唯一一个知道我计划的人。一个人的话怎么能和一个背后有整个帝国军队支持的人的话相提并论呢？}
#{3751}{}{You've convinced me. I will take care of Benicio and the others.}
{3751}{}{你说服了我。我会照顾好贝尼西奥和其他人。}
#{3752}{}{I'm not doing your dirty work for you anymore. Find someone else.}
{3752}{}{我不会再为你做那些肮脏的勾当了。找别人吧。}
#{3753}{}{Will I really get some caps for the meeting?}
{3753}{}{我真的要为会面准备一些瓶盖吗？}
#{3800}{}{You have made the right decision. Return to me when you are done with your task.}
{3800}{}{你做了正确的决定。完成任务后再来找我。}
#{3801}{}{You have made the right decision. Return to me when you are done with your task.}
{3801}{}{你做了正确的决定。完成任务后再来找我。}
#{3802}{}{Goodbye for now, Adviser Elisa.}
{3802}{}{再见了，伊莉莎顾问。}
#{3850}{}{But that changes everything. I cannot afford to let you leave the City with all you've learned from me. You might inform Benicio and thwart my plans. Either you will immediately accept my offer, or you won't do anything... ever again.}
{3850}{}{但这改变了一切。我不能让你带着从我这里学到的一切离开这座城市。你可能会通知贝尼西奥，破坏我的计划。你要么马上接受我的提议，要么什么都不做…明白。}
#{3851}{}{But that changes everything. I cannot afford to let you leave the City with all you've learned from me. You might inform Benicio and thwart my plans. Either you will immediately accept my offer, or you won't do anything... ever again.}
{3851}{}{但这改变了一切。我不能让你带着从我这里学到的一切离开这座城市。你可能会通知贝尼西奥，破坏我的计划。你要么马上接受我的提议，要么什么都不做…明白。}
#{3852}{}{You've convinced me. I will take care of Benicio and the others.}
{3852}{}{你说服了我。我会照顾好贝尼西奥和其他人。}
#{3853}{}{Your threats won't work on me. Bring it on!}
{3853}{}{你的威胁对我没用，放马过来吧！}
#{3900}{}{Don't be ridiculous. Of course you won't get anything until you rid me of Benicio and the mercenaries. As I have found out a long time ago, desire for profit is the best kind of motivation for you foreigners. And I don't want to take that motivation from you too soon.}
{3900}{}{别傻了。当然，除非你帮我除掉贝尼西奥和那些雇佣兵，否则你什么都拿不到。我很久以前就发现，对你们外国人来说，对利益的渴望是最好的动力。我不想太快让你失去这种动力。}
#{3901}{}{Don't be ridiculous. Of course you won't get anything until you rid me of Benicio and the mercenaries. As I have found out a long time ago, desire for profit is the best kind of motivation for you foreigners. And I don't want to take that motivation from you too soon.}
{3901}{}{别傻了。当然，除非你帮我除掉贝尼西奥和那些雇佣兵，否则你什么都拿不到。我很久以前就发现，对你们外国人来说，对利益的渴望是最好的动力。我不想太快让你失去这种动力。}
#{3902}{}{How do I know you won't decide to kill me as well?}
{3902}{}{我怎么知道你不会把我也杀了？}
#{3903}{}{Not to worry. I will take care of Benicio and the others.}
{3903}{}{别担心。我会照顾好贝尼西奥和其他人。}
#{3904}{}{I'm not doing your dirty work for you anymore. Find someone else.}
{3904}{}{我不会再为你做那些肮脏的勾当了。找别人吧。}
#{3950}{}{Well? Did you take care of Benicio and the other mercenaries?}
{3950}{}{怎么样，你搞定贝尼西奥和其他雇佣兵了吗？}
#{3951}{}{Well? Did you take care of Benicio and the other mercenaries?}
{3951}{}{怎么样，你搞定贝尼西奥和其他雇佣兵了吗？}
#{3952}{}{I'm working on it.}
{3952}{}{我正在努力。}
#{3953}{}{Uh.}
{3953}{}{呃。}
#{4000}{}{[Elisa casually waves her hand to signal her personal guard. The soldiers immediately stop glaring at you suspiciously and and turn their eyes to the ground.] Welcome back, stranger. As you can see, I've been quite busy in your absence. The City has a new empress. And how about you? Did you take care of Benicio and the other mercenaries as I have asked?}
{4000}{}{[伊莉莎随意地挥挥手，示意她的私人护卫。士兵们立即停止怀疑地瞪着你，并把他们的眼睛转向地面。]欢迎回来，陌生人。你也看到了，你不在的时候我很忙。这个城市有了新女王。你呢？你按我说的处理好贝尼西奥和其他雇佣兵了吗？}
#{4001}{}{[Elisa casually waves her hand to signal her personal guard. The soldiers immediately stop glaring at you suspiciously and and turn their eyes to the ground.] Welcome back, stranger. As you can see, I've been quite busy in your absence. The City has a new empress. And how about you? Did you take care of Benicio and the other mercenaries as I have asked?}
{4001}{}{[伊莉莎随意地挥挥手，示意她的私人护卫。士兵们立即停止怀疑地瞪着你，并把他们的眼睛转向地面。]欢迎回来，陌生人。你也看到了，你不在的时候我很忙。这个城市有了新女王。你呢？你按我说的处理好贝尼西奥和其他雇佣兵了吗？}
#{4002}{}{Yes, I've dealt with them. So you are the ruler of the entire empire now? What happened to your predecessor?}
{4002}{}{是的，我和他们打过交道。那么你现在是整个帝国的统治者了? 你的前任怎么了？}
#{4003}{}{Yes, I've dealt with them. So you are the ruler of the entire empire now? What happened to your predecessor?}
{4003}{}{是的，我和他们打过交道。那么你现在是整个帝国的统治者了? 你的前任怎么了？}
#{4004}{}{Certainly. The problem has been solved - permanently. Nothing can threaten your rule now.}
{4004}{}{当然。问题已经解决了—永久解决了。现在没有什么能威胁到你的统治了。}
#{4005}{}{Uh.}
{4005}{}{呃。}
#{4050}{}{He was removed. That decrepit old man stood in my way for far too long. As long as he was under Aran's protection, I had no choice but to patiently bear all his weakness and arrogance, but that time is finally over. You cannot imagine how I enjoyed personally ending his life. Watching him slowly die, finally making way for my rule. The feeling was far beyond my expectations. [She stops herself. She probably said more than she intended.] Of course, the official version of Myzrael's passing is a little different. So kindly keep our little secret to yourself.}
{4050}{}{他被免职了。那个衰老的老人挡我的路太久了。只要他还在阿朗的保护下，我就别无选择，只能耐心地忍受他所有的软弱和傲慢，但那个时代终于结束了。你无法想象我有多享受亲手结束他的生命。看着他慢慢死去，最终为我的统治让路。这种感觉远远超出了我的预期。[她停下来。她可能说得太多了。]当然，官方版本的米泽列的去世有点不同。所以请你保守我们的小秘密。}
#{4051}{}{No need to worry. Congratulations on your promotion, empress Elisa.}
{4051}{}{不用担心。祝贺你升职了，伊莉莎女王。}
#{4100}{}{As a sign of my favor, the doors of the Vault will remain open to you. Use this privilege wisely. I doubt I'm ever going to need you again. You've done more than enough for me. I was almost starting to doubt that you really are a mere foreigner.}
{4100}{}{作为我的恩惠，避难所的大门将继续为你敞开。明智地使用这种特权。我觉得我不会再需要你了。你为我做的已经够多了。我几乎开始怀疑你真的只是个外国人了。}
#{4101}{}{As a sign of my favor, the doors of the Vault will remain open to you. Use this privilege wisely. I doubt I'm ever going to need you again. You've done more than enough for me. I was almost starting to doubt that you really are a mere foreigner.}
{4101}{}{作为我的恩惠，避难所的大门将继续为你敞开。明智地使用这种特权。我觉得我不会再需要你了。你为我做的已经够多了。我几乎开始怀疑你真的只是个外国人了。}
#{4102}{}{I'll take that as a compliment. Goodbye, empress Elisa.}
{4102}{}{我就当你是在恭维我吧。再见，伊莉莎女王。}
#{4103}{}{Before I go, can I ask you a few questions?}
{4103}{}{在我走之前，我能问你几个问题吗？}
#{4104}{}{Thanksies!}
{4104}{}{谢唔！}
#{4150}{}{Well? Did you take care of Benicio and the other mercenaries? As the new empress, I cannot afford any complications.}
{4150}{}{怎么样? 你搞定贝尼西奥和其他雇佣兵了吗？作为新女王，我不能再有任何麻烦了
好。}
#{4151}{}{Well? Did you take care of Benicio and the other mercenaries? As the new empress, I cannot afford any complications.}
{4151}{}{怎么样? 你搞定贝尼西奥和其他雇佣兵了吗？作为新女王，我不能再有任何麻烦了
好。}
#{4152}{}{Yes, I've deal with them. So you are the ruler of the entire empire now? What happened to your predecessor?}
{4152}{}{是的，我和他们打过交道。那么你现在是整个帝国的统治者了? 你的前任怎么了？}
#{4153}{}{Yes, I've deal with them. So you are the ruler of the entire empire now? What happened to your predecessor?}
{4153}{}{是的，我和他们打过交道。那么你现在是整个帝国的统治者了? 你的前任怎么了？}
#{4154}{}{Certainly. The problem has been solved - permanently. Nothing can threaten your rule now.}
{4154}{}{当然。问题已经解决了—永久解决了。现在没有什么能威胁到你的统治了。}
#{4155}{}{Uh.}
{4155}{}{呃。}
