#{100}{}{You see a man.}
{100}{}{你看到一个男人。}
#{150}{}{You see Falcon.}
{150}{}{你看到猎鹰了。}
#{200}{}{You see a caravan leader. He's enjoying his cigarette.}
{200}{}{你看到一个商队队长。他很喜欢抽烟。}
#{250}{}{You see Falcon, the caravan leader. He's enjoying the peace, quiet, and his cigarette.}
{250}{}{你看猎鹰，商队队长。他享受着宁静，安静，还有他的香烟。}
#{300}{}{::He blows smoke into your face. Apparently he's not in any mood to talk to you any more.::}
{300}{}{●他把烟吹到你脸上。显然他没有心情再和你说话了}
#{301}{}{Do you see that man near the caravan station? He should be the one that helped Sindian leave the city.}
{301}{}{你看到车队车站附近的那个人了吗？他应该是那个帮助辛迪安离开城市的人。}
#{500}{}{Yeah? Need anything carried across the wasteland? I'm your man. They call me Falcon. [He didn't seem particularly busy before you interrupted him. He was just slowly smoking a cigarette and observing his surroundings with interest.]}
{500}{}{是 啊？需要带什么东西穿过荒地吗？我是你的人。他们叫我猎鹰。[你打断他之前，他似乎并不特别忙。他只是慢慢地抽着烟，饶有兴趣地观察周围的环境}
#{501}{}{Yeah? Need anything carried across the wasteland? I'm your man. They call me Falcon. [He didn't seem particularly busy before you interrupted him. He was just slowly smoking a cigarette and observing his surroundings with interest.]}
{501}{}{是 啊？需要带什么东西穿过荒地吗？我是你的人。他们叫我猎鹰。[你打断他之前，他似乎并不特别忙。他只是慢慢地抽着烟，饶有兴趣地观察周围的环境}
#{502}{}{I need information about a man you took with your caravan away from here some time ago. It's possible that he was in trouble with the Mutant Hunters.}
{502}{}{我需要你前一段时间从这里带走的一个人的信息。很可能他和变种猎人有麻烦。}
#{503}{}{Uf.}
{503}{}{佛罗里达州。}
#{504}{}{I need to talk to you, but Lystra should be here to hear it. I'll be back.}
{504}{}{我要和你谈谈，但莱斯特应该来听的。我会回来的。}
#{550}{}{I've no idea what you're talking about, and I don't trade with information. Sure, I'll listen to a good story or gossip from time to time, just like everyone else with a caravan, but you shouldn't believe everything people say.}
{550}{}{我不知道你在说什么，我也不拿信息做交易。当然，我会时不时地听一个好故事或八卦，就像其他开着大篷车的人一样，但你不应该相信别人说的每一句话。}
#{551}{}{Don't bullshit me. His name is Sindian. And I know damn well you got him out of the city.}
{551}{}{别骗我。他的名字叫辛迪安。我很清楚你把他带出了城市。}
#{552}{}{Try to remember. His name is Sindian. His sister would be very happy to find him.}
{552}{}{试着记住。他的名字叫辛迪安。他姐姐会很高兴找到他的。}
#{553}{}{[Let Lystra talk to him.]}
{553}{}{[让莱斯特拉和他谈谈。]}
#{600}{}{I've heard someone's been asking around about me. I see that someone was you. Let me tell you something. I don't like you, and I'm not going to tell you a thing. Now get lost.}
{600}{}{我听说有人到处打听我。我看到有人是你。让我告诉你一件事。我不喜欢你，我什么都不会告诉你。现在滚开。}
#{601}{}{If you don't answer my questions, I might let it slip to the Hunters that you've helped a guy they're looking for. What do you think about that?}
{601}{}{如果你不回答我的问题，我可能会让猎人知道你帮助了他们要找的人。你觉得怎么样？}
#{602}{}{If you don't answer my questions, I might let it slip to the Hunters that you've helped a guy they're looking for. What do you think about that?}
{602}{}{如果你不回答我的问题，我可能会让猎人知道你帮助了他们要找的人。你觉得怎么样？}
#{603}{}{It's important. His sister really wants to find him.}
{603}{}{这很重要。他姐姐真的很想找到他。}
#{604}{}{[Let Lystra talk to him.]}
{604}{}{[让莱斯特拉和他谈谈。]}
#{650}{}{Right, like you wouldn't run straight to them even if I did answer. Didn't they send you? I got nothing to say to you.}
{650}{}{好吧，好像即使我回答了你也不会直奔他们。他们不是派你来的吗？我没什么好说的。}
#{651}{}{Right, like you wouldn't run straight to them even if I did answer. Didn't they send you? I got nothing to say to you.}
{651}{}{好吧，好像即使我回答了你也不会直奔他们。他们不是派你来的吗？我没什么好说的。}
#{652}{}{Alright, let's try something else. You say that you don't trade with information, but how about making a little exception? I'll give you... Say, 200 caps if you tell me what you know.}
{652}{}{好吧，我们试试别的。你说你不交易信息，但是破例一下怎么样？我会给你。。。如果你告诉我你知道的话，200个。}
#{653}{}{I'll kill you if you don't tell me what I want to know!}
{653}{}{如果你不告诉我我想知道什么，我就杀了你！}
#{700}{}{I've never heard of a Hunter that paid for information. They prefer to just beat it out people. [He blows a dense cloud of cigarette smoke while sizing you up for the second time.] Fine, make it 300 and I'll believe that you're not from the Hunters. Only then will I try to remember if I know anything about that guy.}
{700}{}{我从没听说过有猎人花钱买情报。他们宁愿打败别人。[他在第二次打量你的时候吹了一团浓烟。]好吧，定到300，我相信你不是猎人。只有到那时我才能试着回忆起我是否了解那个家伙。}
#{701}{}{I've never heard of a Hunter that paid for information. They prefer to just beat it out people. [He blows a dense cloud of cigarette smoke while sizing you up for the second time.] Fine, hand over 200 caps and I'll believe that you're not from the Hunters. Only then will I try to remember if I know anything about that guy.}
{701}{}{我从没听说过有猎人花钱买情报。他们宁愿打败别人。[他在第二次打量你的时候吹了一团浓烟。]好吧，交出200个瓶盖，我相信你不是猎人的。只有到那时我才能试着回忆起我是否了解那个家伙。}
#{702}{}{[Give him 300 caps.] Now start reminiscing.}
{702}{}{[给他300个瓶盖]现在开始回忆。}
#{703}{}{[Give him 200 caps.] Now start reminiscing.}
{703}{}{[给他200个瓶盖]现在开始回忆。}
#{704}{}{I'll come back when I have enough caps.}
{704}{}{我有足够的瓶盖就回来。}
#{750}{}{Pff, same old tune, huh. Go ahead an try. But I doubt you'll find something out when one of us is dead.}
{750}{}{Pff，还是老调子，哈。去试试吧。但我怀疑当我们中的一个人死后你会发现什么。}
#{751}{}{Alright, let's try something else. You say that you don't trade with information, but how about making a little exception? I'll give you... Say, 200 caps if you tell me what you know.}
{751}{}{好吧，我们试试别的。你说你不交易信息，但是破例一下怎么样？我会给你。。。如果你告诉我你知道的话，200个。}
#{800}{}{Anyone could say that. I already told you, people like to say all kinds of things, and I don't even know anything.}
{800}{}{任何人都可以这么说。我已经告诉过你了，人们喜欢说各种各样的话，而我什么都不知道。}
#{801}{}{Falcon, his sister, Lystra, is worried about him. She's here with me, as you can see. She hasn't seen him for ages, doesn't know where he is or what's happened to him. So please, stop playing games and tell us what you know.}
{801}{}{Falcon，他的妹妹，Lystra，很担心他。你看，她和我在一起。她好久没见他了，不知道他在哪里，也不知道他出了什么事。所以，请不要玩游戏了，告诉我们你知道什么。}
#{802}{}{If you don't answer my questions, I might let it slip to the Hunters that you've helped a guy they're looking for. What do you think about that?}
{802}{}{如果你不回答我的问题，我可能会让猎人知道你帮助了他们要找的人。你觉得怎么样？}
#{803}{}{If you don't answer my questions, I might let it slip to the Hunters that you've helped a guy they're looking for. What do you think about that?}
{803}{}{如果你不回答我的问题，我可能会让猎人知道你帮助了他们要找的人。你觉得怎么样？}
#{804}{}{[Let Lystra talk to him.]}
{804}{}{[让莱斯特拉和他谈谈。]}
#{850}{}{[He blows a dense cloud of cigarette smoke while sizing Lystra up. Then he speaks to her.] He mentioned you. He was sorry he couldn't say goodbye. But he said he sent some family to you who were supposed to tell you everything.}
{850}{}{[他一边吹着浓浓的烟，一边仔细打量着莱斯特拉。然后他对她说]他提到了你。他很抱歉不能说再见。但他说他派了一个家人来告诉你一切。}
#{851}{}{As far as I know, they never managed to get to Lystra.}
{851}{}{据我所知，他们一直没能到达莱斯特拉。}
#{900}{}{[He turns to you again.] Yeah, things rarely go the way we want them to in life. Well, what do you want to know? Sindian seemed like a nice fellow to me. I've only traveled with him once, but in a caravan, you have to rely on one another. You learn to be a good judge of character pretty damn quick.}
{900}{}{[他又转向你]是的，生活中的事情很少像我们希望的那样。你想知道什么？辛迪安在我看来是个好人。我只和他一起旅行过一次，但在大篷车里，你们必须互相依靠。你很快就学会了品行判断。}
#{901}{}{What happened here in Albuquerque? Why did he have to disappear?}
{901}{}{在阿尔伯克基发生了什么？他为什么要消失？}
#{950}{}{Well, he found out how Mutant Hunters really are and stood up to them. He, together with two other Hunters, was supposed to kill an entire family of immigrants just because one of them had a small mutation. With the whole family dead, Hunters would gain the rights to their property and the purity of humankind would be preserved. Probably standard procedure for the Hunters. Sindian refused and killed both the other Hunters to protect the family. So yeah, after that, he had a damn good reason to get the hell out of here.}
{950}{}{好吧，他发现了变种猎人的真实面目并勇敢地面对他们。他和另外两个猎人一起，本应该杀死整个移民家庭，仅仅因为其中一个有一个小的变异。全家人都死了，猎人们将获得他们财产的权利，人类的纯洁性将得到维护。可能是猎人的标准程序。辛迪安拒绝并杀死了其他两个猎人来保护这个家庭。所以是的，在那之后，他有一个很好的理由离开这里。}
#{951}{}{What happened to the family?}
{951}{}{那家人怎么了？}
#{1000}{}{He said they were weak, some of them ill. They couldn't have survived on the road, so Sindian sent them to his sister so she could help them and learn about what happened.}
{1000}{}{他说他们很虚弱，有些人病了。他们不可能在路上幸存下来，所以辛迪安把他们送到他姐姐那里，以便她能帮助他们并了解发生的事情。}
#{1001}{}{Where did Sindian travel to, then?}
{1001}{}{那么辛迪安去了哪里？}
#{1050}{}{To Corath. That's where he left the caravan. Haven't seen him since. That's all I know, honest. And now I'd like to enjoy a bit of peace before my caravan sets off again.}
{1050}{}{给科拉斯。那是他离开大篷车的地方。从那以后就没见过他了。老实说，我只知道这些。现在我想在我的大篷车再次出发前享受一点宁静。}
#{1051}{}{OK, thanks for the info.}
{1051}{}{好的，谢谢你的信息。}
#{1100}{}{Well, what do you want to know? Sindian seemed like a nice fellow to me. I've only traveled with him once, but in a caravan, you have to rely on one another. You learn to be a good judge of character pretty damn quick.}
{1100}{}{你想知道什么？辛迪安在我看来是个好人。我只和他一起旅行过一次，但在大篷车里，你们必须互相依靠。你很快就学会了品行判断。}
#{1101}{}{What happened here in Albuquerque? Why did he have to disappear?}
{1101}{}{在阿尔伯克基发生了什么？他为什么要消失？}
#{1150}{}{Listen, either bring me 300 caps and maybe learn something from me, or get lost. Both suit me fine.}
{1150}{}{听着，要么给我带300顶瓶盖，也许从我身上学点东西，要么就迷路。两者都很适合我。}
#{1151}{}{Listen, either bring me 300 caps and maybe learn something from me, or get lost. Both suit me fine.}
{1151}{}{听着，要么给我带300顶瓶盖，也许从我身上学点东西，要么就迷路。两者都很适合我。}
#{1152}{}{[Give him 300 caps.] Now start reminiscing.}
{1152}{}{[给他300个瓶盖]现在开始回忆。}
#{1153}{}{[Give him 200 caps.] Now start reminiscing.}
{1153}{}{[给他200个瓶盖]现在开始回忆。}
#{1154}{}{I'll be back.}
{1154}{}{我会回来的。}
#{1155}{}{Hoo-kay.}
{1155}{}{呼凯。}
#{2000}{}{Falcon, I'll speak plainly and I hope you'll do the same. The reason I was asking around about you was that I want to know what happened to Sindian. It's important.}
{2000}{}{法尔肯，我会直言不讳的，希望你也这么做。我四处打听你的原因是我想知道辛迪安发生了什么事。这很重要。}
#{2001}{}{Oh, so you're the inquisitive fellow, I've heard about. May I know why you care so much?}
{2001}{}{哦，我听说你是个爱打听的家伙。我能知道你为什么这么在乎吗？}
#{2002}{}{I'm Lystra, his sister. I have no idea why he had to leave, where he is or what happened to him. I'm worried about him, and there are certain... Things that he should know about. Please, tell me what you know.}
{2002}{}{我是莱斯特拉，他的妹妹。我不知道他为什么要离开，他在哪里，发生了什么事。我很担心他，而且肯定。。。他应该知道的事情。拜托，告诉我你知道什么。}
#{2003}{}{::He blows a dense cloud of cigarette smoke while sizing Lystra up.:: He mentioned you. He was sorry he couldn't say goodbye. But he said he sent some family to you who were supposed to tell you everything.}
{2003}{}{●他一边吹着浓浓的烟，一边仔细打量莱斯特。：：他提到过你。他很抱歉不能说再见。但他说他派了一个家人来告诉你一切。}
#{2004}{}{Someone did try to contact me. Unfortunately, I didn't manage to find him in time, at least, not alive.}
{2004}{}{有人试图联系我。不幸的是，我没能及时找到他，至少，他还活着。}
