#{100}{}{You see a man in a lab coat.}
{100}{}{你看到一个穿白大褂的男人。}
#{150}{}{You see doctor Falber.}
{150}{}{你看到福伯医生。}
#{200}{}{You see an elderly man wearing a lab coat. He has a small goatee, but his head is completely bald. He's wearing a circular earring in one of his ears.}
{200}{}{你看到一位穿着白大褂的老人。他留着小山羊胡，但他的头完全秃了。他的一只耳朵上戴着一只圆形耳环。}
#{250}{}{You see doctor Falber, the head of the hospital. His stare cuts into you like a scalpel.}
{250}{}{你看到医院的院长福伯医生，他的目光像手术刀一样刺入你的身体。}
#{300}{}{You're risking your life by bringing a floater into this city, as well as the lives of those around you - and, as I've already said, I have no desire to be one of them. Leave.}
{300}{}{你把一个流浪汉带进这座城市是在拿周围人的生命和自己的生命在冒险，正如我已经说过的，我不想成为他们中的一员。走开。}
#{301}{}{We need more donors.}
{301}{}{我们需要更多的捐赠者。}
#{302}{}{We need more young undamaged tissue.}
{302}{}{我们需要更多未受损的年轻组织。}
#{303}{}{The results of the last batch of tests were satisfactory.}
{303}{}{最后一批试验的结果令人满意。}
#{304}{}{I will perform the autopsy of that donor personally.}
{304}{}{我会亲自为捐献者进行尸检。}
#{305}{}{The last non-paying customer will have to be put into the test group.}
{305}{}{最后一个非付费客户将被放入测试组。}
#{306}{}{I need three more donors for additional brain research.}
{306}{}{我还需要三个捐赠者来做额外的大脑研究。}
#{307}{}{We'll remove subject 14's vocal cords; I need peace for my work.}
{307}{}{我们要切除14号实验对象的声带，我的工作需要安静。}
#{308}{}{We need to speed up the lung transplantation procedure.}
{308}{}{我们需要加快肺移植手术。}
#{309}{}{The mortality rate of the subjects in the last batch was too high.}
{309}{}{最后一批实验对象的死亡率太高。}
#{310}{}{We should have enough donors, at least for the time being.}
{310}{}{我们应该有足够的捐赠者，至少目前是这样。}
#{350}{}{Your strength has increased by 1 point.}
{350}{}{你的力量增加了1点。}
#{351}{}{Your perception has increased by 1 point.}
{351}{}{你的感知增加了1点。}
#{352}{}{Your endurance has increased by 1 point.}
{352}{}{你的耐力增加了1点。}
#{353}{}{Your charisma has increased by 1 point.}
{353}{}{你的魅力增加了1点。}
#{354}{}{Your intelligence has increased by 1 point.}
{354}{}{你的智力增加了1点。}
#{355}{}{Your agility has increased by 1 point.}
{355}{}{你的敏捷增加了1点。}
#{400}{}{Get rid of him.}
{400}{}{把他赶走。}
#{401}{}{Do you realize that you are our future donor?}
{401}{}{你知道你就是我们未来的捐献者吗？}
#{402}{}{You'll be taken care of soon.}
{402}{}{你很快就会得到照顾的。}
#{403}{}{How dare you do this in MY hospital?!}
{403}{}{你怎么敢在我的医院里这么做？！}
#{404}{}{I won't tolerate this in MY hospital!}
{404}{}{我不能容忍在我的医院里发生这种事！}
#{405}{}{I have no time for this.}
{405}{}{我没时间做这个。}
#{406}{}{Sometimes, it's necessary to use violence. We're prepared for that.}
{406}{}{有时候，使用暴力是必要的，我们已经做好了准备。}
#{407}{}{Don't worry, we know what to do with the likes of you.}
{407}{}{别担心，我们知道怎么对付你这种人。}
#{408}{}{Do you realize that you are our future donor?}
{408}{}{你知道你就是我们未来的捐赠者吗？}
#{409}{}{Get rid of her.}
{409}{}{把她赶走。}
#{500}{}{Ah, a customer. Welcome. I am doctor Falber, the head of this hospital. What can I do for you?}
{500}{}{啊，一位客人。欢迎光临。我是福伯医生，这家医院的院长。我能为你做些什么？}
#{501}{}{Ah, a customer. Welcome. I am doctor Falber, the head of this hospital. What can I do for you?}
{501}{}{啊，一位客人。欢迎光临。我是福伯医生，这家医院的院长。我能为你做些什么？}
#{502}{}{I need healing, my...}
{502}{}{我需要治疗，我的…}
#{503}{}{My companion needs healing.}
{503}{}{我的同伴需要治疗。}
#{504}{}{I have this peculiar problem...}
{504}{}{我有个特殊的问题…}
#{505}{}{What do you offer in this hospital besides healing?}
{505}{}{除了治疗，你们医院还能提供什么？}
#{506}{}{Do you think you might have some work for me?}
{506}{}{你觉得你有工作给我吗？}
#{507}{}{The tribals keep losing people. I was with them on a hunt when they were ambushed by a group of men, probably from Albuquerque. Would you happen to know anything about that?}
{507}{}{部落一直在失去人手。我和他们一起打猎的时候，他们遭到一伙人的伏击，可能是从阿尔伯克基来的。你知道这件事吗？}
#{508}{}{The tribals keep losing people. I was with them on a hunt when they were ambushed by a group of men, probably from Albuquerque. Would you happen to know anything about that?}
{508}{}{部落一直在失去人手。我和他们一起打猎的时候，他们遭到一伙人的伏击，可能是从阿尔伯克基来的。你知道这件事吗？}
#{509}{}{Nothing, my mistake.}
{509}{}{没什么，是我的错。}
#{510}{}{Hurt!}
{510}{}{受伤！}
#{511}{}{Dogsies hurt! [Point at Mutt.]}
{511}{}{狗狗受伤了！[指着穆特。]}
#{512}{}{Ugha-huha. Buka!}
{512}{}{啊，呼哈。布卡！}
#{513}{}{Baaai.}
{513}{}{巴艾。}
#{514}{}{I've seen mercenaries ambushing tribals that were out hunting geckos and I know they were your people. Why are you doing that?}
{514}{}{我见过雇佣兵伏击那些外出猎捕蜥蜴的部落，我知道他们是你的人。你为什么要这么做？}
#{515}{}{I've seen mercenaries ambushing tribals that were out hunting geckos and I know they were your people. Why are you doing that?}
{515}{}{我见过雇佣兵伏击那些外出猎捕蜥蜴的部落，我知道他们是你的人。你为什么要这么做？}
#{550}{}{Ah, a customer. Welcome. [He smiles like a cat that just caught a mouse.] I am doctor Falber, the head of this hospital. What can I do for you?}
{550}{}{啊，一位客人。欢迎光临。[他笑起来就像一只捉到老鼠的猫。]我是福伯医生，这家医院的院长。我能为你做些什么？}
#{551}{}{Ah, a customer. Welcome. [He smiles like a cat that just caught a mouse.] I am doctor Falber, the head of this hospital. What can I do for you?}
{551}{}{啊，一个顾客。欢迎光临。[他笑起来就像一只捉到老鼠的猫。]我是福伯医生，这家医院的院长。我能为你做些什么？}
#{600}{}{You should leave the diagnosis to us, we'll take care of everything. Of course, there is one other thing. I prefer not to talk about financial matters in advance, however, since you are new here, I must warn you that our services are not cheap. Quality service demands adequate pay. If you don't have enough caps, it would be best if you left.}
{600}{}{你应该把诊断交给我们，我们会处理好一切的。当然，还有一件事。我不喜欢提前谈论财务问题，但是，由于你是新来的，我必须警告你，我们的服务是不便宜的。优质的服务要求足够的报酬。如果你没有足够的瓶盖，你最好离开。}
#{601}{}{How much will the treatment cost me?}
{601}{}{治疗费用是多少？}
#{602}{}{Caps won't be a problem, go ahead and do your job.}
{602}{}{瓶盖不是问题，继续做你的工作吧。}
#{603}{}{You wouldn't heal me for free even if I was dying?!}
{603}{}{即使我快死了，你也不会免费治疗我吗？！}
#{604}{}{If you don't heal me for free, I'll gut you so that none of your colleagues will be able to piece your body back together!}
{604}{}{如果你不给我免费治疗，我就把你开膛破肚，碎尸万段，这样你的同事就没人能把你的身体拼回去了！}
#{605}{}{I'm sure I'll live... Hopefully. I've got no caps to spare.}
{605}{}{我相信我能活下去... 希望如此，我没有多余的瓶盖了。}
#{650}{}{The price is determined by the medical procedures that we will need to perform, and we won't know those until the examination is done.}
{650}{}{价格是由我们需要进行的医疗程序决定的，在检查完成之前我们不会知道。}
#{700}{}{Dear Sir, what we do here is not some shamanistic pseudo-medicine, but serious, brilliant medicine. It's not easy to get all the necessary medical supplies, substances and personnel, and they all cost a lot of caps.}
{700}{}{亲爱的先生，我们在这里做的不是什么萨满教的伪医学，而是严肃的、出色的医学。获得所有必要的医疗用品、物质和人员并不容易，而且这些都要花费很多钱。}
#{750}{}{If you insist, I'm sure we can come to an agreement, say... [Someone firmly grabs you from behind around your neck and plunges a syringe into your artery. You slowly lose consciousness.] That you just became a voluntary donor of all your healthy organs. [You fall asleep, never to wake again.]}
{750}{}{如果你坚持的话，我相信我们可以达成协议，比如... [有人从你脖子后面紧紧抓住你，把注射器插进你的动脉。你慢慢失去意识。]你刚刚自愿捐献了你所有的健康器官。[你睡着了，再也没有醒来。]}
#{751}{}{[End.]}
{751}{}{[结束。]}
#{800}{}{If you insist, I'm sure we can come to an agreement, say... [At the last moment, you notice a stocky man with a syringe trying to grab you from behind and narrowly dodge.]}
{800}{}{如果你坚持的话，我相信我们可以达成协议，比如... [在最后一刻，你注意到一个矮壮的男人拿着注射器试图从后面抓住你，然后勉强躲开。]}
#{801}{}{[Defend yourself.]}
{801}{}{[保护自己。]}
#{850}{}{You should leave the diagnosis to us, we'll take care of everything. Of course, there is one other thing. I prefer not to talk about financial matters in advance, however, since you are new here, I must warn you that our services are not cheap. Quality service demands adequate pay. If you don't have enough caps, it would be best if you left.}
{850}{}{你应该把诊断交给我们，我们会处理好一切的。当然，还有一件事。我不喜欢提前谈论财务问题，但是，由于你是新来的，我必须警告你，我们的服务是不便宜的。优质的服务要求足够的报酬。如果你没有足够的瓶盖，你最好离开。}
#{853}{}{You wouldn't heal me for free even if I was dying?!}
{853}{}{即使我快死了，你也不会免费治疗我吗？！}
#{900}{}{Dear Miss, what we do here is not some shamanistic pseudo-medicine, but serious, brilliant medicine. It's not easy to get all the necessary medical supplies, substances and personnel, and they all cost a lot of caps.}
{900}{}{亲爱的小姐，我们在这里做的不是什么萨满教的伪医学，而是严肃的、出色的医学。获得所有必要的医疗用品、物质和人员并不容易，而且这些都要花费很多钱。}
#{950}{}{If you insist, I'm sure we can come to an agreement, say... [Someone firmly grabs you from behind around your neck and plunges a syringe into your artery. You slowly lose consciousness.] That you just became a voluntary donor of all your healthy organs. [You fall asleep, never to wake again.]}
{950}{}{如果你坚持的话，我相信我们可以达成协议，比如... [有人从你脖子后面紧紧抓住你，把注射器插进你的动脉。你慢慢失去意识。]你刚刚自愿捐献了你所有的健康器官。[你睡着了，再也没有醒来。]}
#{1000}{}{If you insist, I'm sure we can come to an agreement, say... [At the last moment, you notice a stocky man with a syringe trying to grab you from behind and narrowly dodge him.]}
{1000}{}{如果你坚持的话，我相信我们可以达成协议，比如... [在最后一刻，你注意到一个矮壮的男人拿着注射器试图从后面抓住你，然后勉强躲开。]}
#{1050}{}{The price is determined by the medical procedures that we will need to perform, and we won't know those until the examination is done.}
{1050}{}{价格是由我们需要进行的医疗程序决定的，在检查完成之前我们不会知道。}
#{1100}{}{Very well, lie down on this bed and I will put you to sleep for a while. Don't worry, I'll oversee your treatment personally. [You're a bit nervous, but your worries slowly disappear along with your consciousness.]}
{1100}{}{很好，躺在这张床上，我让你睡一会儿。别担心，我会亲自监督你的治疗。[你有点紧张，但你的担心会随着你的意识慢慢消失。]}
#{1101}{}{[Fall asleep.]}
{1101}{}{[睡着了。]}
#{1150}{}{[You slowly awaken, but everything is blurry and every motion you make takes tremendous effort. You notice doctor Falber hunched over you, telling you something.] ...mere flesh wounds, which we have treated thoroughly. It will be 100 caps.}
{1150}{}{[你慢慢醒来，但一切都是模糊的，你做的每个动作都需要付出巨大的努力。你注意到福伯医生俯身在你身边，告诉你一些事情。]…只是皮肉之伤，我们已经彻底治疗过了。总共100瓶盖。}
#{1151}{}{Sure, I have them...}
{1151}{}{当然，我有…}
#{1152}{}{I don't have that much.}
{1152}{}{我没那么多钱。}
#{1200}{}{Don't strain yourself, my assistant will take care of it. [A man takes your pouch with caps, takes the appropriate sum and puts it back.] I like when business goes smoothly. [Falber lightly smiles and removes the end of the tube that was stuck in your arm, then helps you stand up.] The feeling of sluggishness should pass in a moment.}
{1200}{}{别紧张，我的助手会处理的。[一个男人拿起你装着瓶盖的袋子，取出适量的钱，又放回原处。]我喜欢生意顺利的时候。[福伯微微一笑，移开插在你胳膊上的管子的末端，然后帮助你站起来。]呆滞的感觉一会儿就会过去。}
#{1201}{}{Don't strain yourself, my assistant will take care of it. [A man takes your pouch with caps, takes the appropriate sum and puts it back.] I like when business goes smoothly. [Falber lightly smiles and removes the end of the tube that was stuck in your arm, then helps you stand up.] The feeling of sluggishness should pass in a moment.}
{1201}{}{别紧张，我的助手会处理的。[一个男人拿起你装着瓶盖的袋子，取出适量的钱，又放回原处。]我喜欢生意顺利的时候。[福伯微微一笑，移开插在你胳膊上的管子的末端，然后帮助你站起来。]呆滞的感觉一会儿就会过去。}
#{1202}{}{OK.}
{1202}{}{OK。}
#{1250}{}{[Falber touches a tube leading from your arm to a container with some clear liquid.] In that case, we'll take one of your organs to compensate. Someone with enough caps will surely make better use of it. Of course, removing the organ undamaged is a complicated and expensive procedure. You might also find it hard to live without it. Thus, it will be for the best of us all to simply take your whole body, I'm sure we'll be able to use most of it in some way. [Falber takes off a clamp on the tube, letting the liquid to flow into your bloodstream. You lose consciousness. Forever.]}
{1250}{}{[福伯摸了摸一根从你手臂延伸到一个装有透明液体的容器的管子。]那样的话，我们会取走你的一个器官来补偿。有足够瓶盖的人肯定会更好地使用它。当然，将器官完好无损地取出是一个复杂而昂贵的过程。你可能也会发现没有它你很难活下去。因此，把你的整个身体拿走对我们所有人来说都是最好的，我相信我们能以某种方式利用大部分身体。[福伯取下管子上的夹子，让液体流入你的血液。你会失去意识。永远。]}
#{1300}{}{[You slowly awaken, but everything is blurry and every motion you make takes tremendous effort. You notice doctor Falber hunched over you, telling you something.] ...mere flesh wounds, which we have treated thoroughly. Your organism has caught a few rads, so we had to do a decontamination. It will be 200 caps in total.}
{1300}{}{[你慢慢醒来，但一切都是模糊的，你做的每个动作都需要付出巨大的努力。你注意到福伯医生俯身在你身边，告诉你一些事情。]…只是皮肉之伤，我们已经彻底治疗过了。你的身体受到了一些辐射，所以我们必须进行净化处理。总共200瓶盖。}
#{1350}{}{[You slowly awaken, but everything is blurry and every motion you make takes tremendous effort. You notice doctor Falber hunched over you, telling you something.] ...mere flesh wounds, which we have treated thoroughly. You also had radscorpion or similar poison flowing in your bloodstream, but our antidote worked perfectly. It will be 200 caps in total.}
{1350}{}{[你慢慢醒来，但一切都是模糊的，你做的每个动作都需要付出巨大的努力。你注意到福伯医生俯身在你身边，告诉你一些事情。]…只是皮肉之伤，我们已经彻底治疗过了。你的血液里也有蝎子或者类似的毒素，但我们的解毒剂效果很好。总共200瓶盖。}
#{1400}{}{[You slowly awaken, but everything is blurry and every motion you make takes tremendous effort. You notice doctor Falber hunched over you, telling you something.] ...mere flesh wounds, which we have treated thoroughly. Your organism has caught a few rads, so we had to do a decontamination. You also had radscorpion or similar poison flowing in your bloodstream, but our antidote worked perfectly. It will be 300 caps in total.}
{1400}{}{[你慢慢醒来，但一切都是模糊的，你做的每个动作都需要付出巨大的努力。你注意到福伯医生俯身在你身边，告诉你一些事情。]…只是皮肉之伤，我们已经彻底治疗过了。你的身体受到了一些辐射，所以我们必须进行净化处理。你的血液里也有蝎子或者类似的毒素，但我们的解毒剂效果很好。总共300瓶盖。}
#{1450}{}{[You slowly awaken, but everything is blurry and every motion you make takes tremendous effort. You notice doctor Falber hunched over you, telling you something.] ...and other moderate injuries, but we've taken care of everything. It will be 200 caps.}
{1450}{}{[你慢慢醒来，但一切都是模糊的，你做的每个动作都需要付出巨大的努力。你注意到福伯医生俯身在你身边，告诉你一些事情。]…还有其他中度损伤，但我们已经处理好了。总共200瓶盖。}
#{1500}{}{[You slowly awaken, but everything is blurry and every motion you make takes tremendous effort. You notice doctor Falber hunched over you, telling you something.] ...and other moderate injuries, but we've taken care of everything. Your organism has caught a few rads, so we had to do a decontamination. It will be 300 caps in total.}
{1500}{}{[你慢慢醒来，但一切都是模糊的，你做的每个动作都需要付出巨大的努力。你注意到福伯医生俯身在你身边，告诉你一些事情。]…还有其他中度损伤，但我们已经处理好了。你的身体受到了一些辐射，所以我们必须进行净化处理。总共300瓶盖。}
#{1550}{}{[You slowly awaken, but everything is blurry and every motion you make takes tremendous effort. You notice doctor Falber hunched over you, telling you something.] ...and other moderate injuries, but we've taken care of everything. You also had radscorpion or similar poison flowing in your bloodstream, but our antidote worked perfectly. It will be 300 caps in total.}
{1550}{}{[你慢慢醒来，但一切都是模糊的，你做的每个动作都需要付出巨大的努力。你注意到福伯医生俯身在你身边，告诉你一些事情。]…还有其他中度损伤，但我们已经处理好了。你的血液里也有蝎子或者类似的毒素，但我们的解毒剂效果很好。总共300瓶盖。}
#{1600}{}{[You slowly awaken, but everything is blurry and every motion you make takes tremendous effort. You notice doctor Falber hunched over you, telling you something.] ...and other moderate injuries, but we've taken care of everything. Your organism has caught a few rads, so we had to do a decontamination. You also had radscorpion or similar poison flowing in your bloodstream, but our antidote worked perfectly. It will be 400 caps in total.}
{1600}{}{[你慢慢醒来，但一切都是模糊的，你做的每个动作都需要付出巨大的努力。你注意到福伯医生俯身在你身边，告诉你一些事情。]…还有其他中度损伤，但我们已经处理好了。你的身体受到了一些辐射，所以我们必须进行净化处理。你的血液里也有蝎子或者类似的毒素，但我们的解毒剂效果很好。总共400瓶盖。}
#{1650}{}{[You slowly awaken, but everything is blurry and every motion you make takes tremendous effort. You notice doctor Falber hunched over you, telling you something.] ...a few broken bones and other serious injuries, but we've fixed you up thoroughly. It will be 300 caps.}
{1650}{}{[你慢慢醒来，但一切都是模糊的，你做的每个动作都需要付出巨大的努力。你注意到福伯医生俯身在你身边，告诉你一些事情。]…有几处骨折和其他严重的伤，但我们已经彻底治好了你。一共300瓶盖。}
#{1700}{}{[You slowly awaken, but everything is blurry and every motion you make takes tremendous effort. You notice doctor Falber hunched over you, telling you something.] ...a few broken bones and other serious injuries, but we've fixed you up thoroughly. Your organism has caught a few rads, so we had to do a decontamination. It will be 400 caps in total.}
{1700}{}{[你慢慢醒来，但一切都是模糊的，你做的每个动作都需要付出巨大的努力。你注意到福伯医生俯身在你身边，告诉你一些事情。]…有几处骨折和其他严重的伤，但我们已经彻底治好了你。你的身体受到了一些辐射，所以我们必须进行净化处理。总共400瓶盖。}
#{1750}{}{[You slowly awaken, but everything is blurry and every motion you make takes tremendous effort. You notice doctor Falber hunched over you, telling you something.] ...a few broken bones and other serious injuries, but we've fixed you up thoroughly. You also had radscorpion or similar poison flowing in your bloodstream, but our antidote worked perfectly. It will be 400 caps in total.}
{1750}{}{[你慢慢醒来，但一切都是模糊的，你做的每个动作都需要付出巨大的努力。你注意到福伯医生俯身在你身边，告诉你一些事情。]…有几处骨折和其他严重的伤，但我们已经彻底治好了你。你的血液里也有蝎子或者类似的毒素，但我们的解毒剂效果很好。总共400瓶盖。}
#{1800}{}{[You slowly awaken, but everything is blurry and every motion you make takes tremendous effort. You notice doctor Falber hunched over you, telling you something.] ...a few broken bones and other serious injuries, but we've fixed you up thoroughly. Your organism has caught a few rads, so we had to do a decontamination. You also had radscorpion or similar poison flowing in your bloodstream, but our antidote worked perfectly. It will be 500 caps in total.}
{1800}{}{[你慢慢醒来，但一切都是模糊的，你做的每个动作都需要付出巨大的努力。你注意到福伯医生俯身在你身边，告诉你一些事情。]…有几处骨折和其他严重的伤，但我们已经彻底治好了你。你的身体受到了一些辐射，所以我们必须进行净化处理。你的血液里也有蝎子或者类似的毒素，但我们的解毒剂效果很好。总共500瓶盖。}
#{1850}{}{[You slowly awaken, but everything is blurry and every motion you make takes tremendous effort. You notice doctor Falber hunched over you, telling you something.] We found out an interesting thing during the examination. As I'm sure you know, you have one extra toe on your right foot. It's a small and unexceptional mutation, but even that is enough to provoke the ire of the Mutant Hunters both to you and our hospital if we treat you. Officially, I'm supposed to turn your body over to them, but getting rid of so much material because of one small flaw would be rather wasteful, so I will just keep it. I'm sure you won't tell the Hunters. [Falber takes off a clamp on a tube leading from your arm to a container with some clear liquid, letting it flow into your bloodstream. You lose consciousness. Forever.]}
{1850}{}{[你慢慢醒来，但一切都是模糊的，你做的每个动作都需要巨大的努力。你注意到福伯医生弯腰对你说了些什么。]我们在检查中发现了一件有趣的事。你肯定知道，你右脚上多了一个脚趾头。这是一个小而普通的突变，但即使是这样，如果我们治疗你，也足以激起变种猎人对你和我们医院的愤怒。按照规定，我应该把你的尸体交给他们，但因为一个小瑕疵就扔掉这么多材料太浪费了，所以我还是留着吧。我相信你不会告诉猎人的。[福伯取下一个从你手臂上延伸到一个装有透明液体容器的管子上的夹子，让液体流入你的血液。你失去了意识。永远。]}
#{1900}{}{There is one more thing, though I cannot help you with it. You have the HIV virus, which causes the acquired immune deficiency syndrome, or AIDS for short. As far as I know, the pre-war doctors knew the cure for this virus. It's extremely difficult to manufacture and I unfortunately do not know the process. I would like to, however. That cure would be tremendously valuable.}
{1900}{}{还有一件事，虽然我帮不了你。你感染了HIV病毒，它会导致获得性免疫缺陷综合征，或简称艾滋病（AIDS）。据我所知，战前的医生知道治疗这种病毒的方法。那是极其困难的治愈方法，不幸的是我不知道这个过程。不过我愿意去尝试。这种疗法将会非常有价值。}
#{1901}{}{If they knew a cure before the war, do you think they could help me in the local vault?}
{1901}{}{如果他们在战前知道治愈方法，你觉得他们能在当地的避难所帮我吗？}
#{1902}{}{What's going to happen to me?}
{1902}{}{我会怎么样？}
#{1903}{}{Hm, thanks for the info. Goodbye.}
{1903}{}{嗯，谢谢你的消息。再见。}
#{1950}{}{Theoretically, yes. I believe they have options that they cannot even fully use. However, nobody in the empire is willing to talk to poor vagabonds, let alone waste expensive medication on them, which is understandable.}
{1950}{}{从理论上说，是的。我相信他们有一些甚至无法充分发挥的方法。然而，帝国里没有人愿意与可怜的流浪汉交谈，更不用说在他们身上浪费昂贵的药物，这是可以理解的。}
#{2000}{}{For now you are only a carrier of the HIV virus, which will at some point develop into the AIDS disease and lead to an immunity failure, you will thus begin to lose your endurance. The clearest first symptom are malignant lesions, appearing as dark spots on the skin. Other common symptoms are fatigue, fever, diarrhea, and weight loss. Finally, because of the loss of the immune system, you can expect the arrival of some malignant infection.}
{2000}{}{因为现在你只是一个HIV病毒的携带者，它会在某个时候发展成艾滋病（AIDS）并导致免疫力衰竭，你将因此开始失去你的耐力。最明显的首发症状是恶性病变，表现为皮肤上的黑斑。其他常见症状包括疲劳、发烧、腹泻和体重减轻。最后，由于免疫系统的丧失，你可以预期一些恶性感染的到来。}
#{2001}{}{For now you are only a carrier of the HIV virus, which will at some point develop into the AIDS disease and lead to an immunity failure, you will thus begin to lose your endurance. The clearest first symptom are malignant lesions, appearing as dark spots on the skin. Other common symptoms are fatigue, fever, diarrhea, and weight loss. Finally, because of the loss of the immune system, you can expect the arrival of some malignant infection.}
{2001}{}{因为现在你只是一个HIV病毒的携带者，它会在某个时候发展成艾滋病（AIDS）并导致免疫力衰竭，你将因此开始失去你的耐力。最明显的首发症状是恶性病变，表现为皮肤上的黑斑。其他常见症状包括疲劳、发烧、腹泻和体重减轻。最后，由于免疫系统的丧失，你可以预期一些恶性感染的到来。}
#{2050}{}{HIV is already developing into the AIDS disease in you, which will lead to an immunity failure, you are thus beginning to lose your endurance. The clearest first symptom are malignant lesions, appearing as dark spots on the skin. Other common symptoms are fatigue, fever, diarrhea, and weight loss. Finally, because of the loss of the immune system, you can expect the arrival of some malignant infection.}
{2050}{}{HIV 病毒已经在你体内发展成艾滋病（AIDS），这会导致免疫系统失效，你开始失去耐力。最明显的第一个症状是恶性病变，表现为皮肤上的黑斑。其他常见症状有疲劳、发烧、腹泻和体重减轻。最后，由于免疫系统的丧失，你可以预料到一些恶性感染的到来。}
#{2100}{}{You have my interest.}
{2100}{}{我对你有兴趣。}
#{2101}{}{An extra toe has grown on my right foot. Do you think you could remove it?}
{2101}{}{我的右脚多长了一个脚趾，你能把它切除吗？}
#{2102}{}{I most likely have a sexually-transmitted disease. I think it's called AIDS.}
{2102}{}{我很可能得了性传播疾病，我想是艾滋病（AIDS）。}
#{2103}{}{Forget about it.}
{2103}{}{忘了它吧。}
#{2150}{}{Human mutations are a fascinating matter from a medical point of view, and removing it would not be difficult. Unfortunately, mutations are not looked upon kindly in this city, so I'm not willing to perform the operation. If you leave immediately and never return, I will forget about you instead of wasting my time and handing you over to the Mutant Hunters.}
{2150}{}{从医学的角度来看，人类突变是一件令人着迷的事情，去除它并不困难。不幸的是，基因突变在这个城市并不被看好，所以我不愿意做这个手术。如果你马上离开，再也不回来，我会忘记你，而不是浪费我的时间把你交给变种猎人。}
#{2200}{}{Surely you meant the acquired immune deficiency syndrome, which is caused by the HIV virus. As far as I know, the pre-war doctors knew the cure for this virus. It's extremely difficult to manufacture and I unfortunately do not know the process. I would like to, however. That cure would be tremendously valuable.}
{2200}{}{你指的是后天免疫缺陷综合症，是由HIV病毒引起的。据我所知，战前的医生知道治疗这种病毒的方法。那是极其困难的治愈方法，不幸的是我不知道这个过程。不过我愿意去尝试。这种疗法将会非常有价值。。}
#{2250}{}{Theoretically, yes. I believe they have options that they cannot even fully use. However, nobody in the empire is willing to talk to poor vagabonds, let alone waste expensive medication on them, which is understandable.}
{2250}{}{从理论上说，是的。我相信他们有一些甚至无法充分发挥的方法。然而，帝国里没有人愿意与可怜的流浪汉交谈，更不用说在他们身上浪费昂贵的药物，这是可以理解的。}
#{2300}{}{You are a carrier of the HIV virus, which will at some point develop into the AIDS disease and lead, or perhaps it already has, to an immunity failure, and you will thus start to lose your endurance. The clearest first symptom are malignant lesions, appearing as dark spots on the skin. Other common symptoms are fatigue, fever, diarrhea, and weight loss. Finally, because of the loss of the immune system, you can expect the arrival of some malignant infection.}
{2300}{}{你是HIV病毒的携带者，它将在某一时刻发展成艾滋病并导致，或者已经导致免疫功能衰竭，你将因此开始失去耐力。最明显的第一个症状是恶性病变，表现为皮肤上的黑斑。其他常见症状有疲劳、发烧、腹泻和体重减轻。最后，由于免疫系统的丧失，你可以预料到一些恶性感染的到来。}
#{2301}{}{You are a carrier of the HIV virus, which will at some point develop into the AIDS disease and lead, or perhaps it already has, to an immunity failure, and you will thus start to lose your endurance. The clearest first symptom are malignant lesions, appearing as dark spots on the skin. Other common symptoms are fatigue, fever, diarrhea, and weight loss. Finally, because of the loss of the immune system, you can expect the arrival of some malignant infection.}
{2301}{}{你是HIV病毒的携带者，它将在某一时刻发展成艾滋病并导致，或者已经导致免疫功能衰竭，你将因此开始失去耐力。最明显的第一个症状是恶性病变，表现为皮肤上的黑斑。其他常见症状有疲劳、发烧、腹泻和体重减轻。最后，由于免疫系统的丧失，你可以预料到一些恶性感染的到来。}
#{2350}{}{Our greatest interest lies in improving human abilities. Not only are we constantly researching the methods to achieve this, but now we are even able to make people stronger, tougher, quicker, smarter, more perceptive, as well as more attractive, by performing minor surgical procedures and transplanting higher quality organs. A noticeable improvement by, shall we say, one degree. Since it is hard for the human body to accept and make use of organs that are too powerful, you can only undergo each of the operations once. And I'm sure I don't have to tell you that they are quite expensive.}
{2350}{}{我们最大的兴趣在于提高人类的能力。我们不仅不断地研究实现这一目标的方法，而且现在我们甚至能够通过进行小型外科手术和移植更高质量的器官，使人变得更强壮、更坚韧、更快、更聪明、更有洞察力，以及更有吸引力。我们可以说，这是一个显著的进步。由于人体很难接受和利用过于强大的器官，所以每种手术只能进行一次。我相信我不必告诉你它们很贵。}
#{2351}{}{Where will you get the organs for the transplantation?}
{2351}{}{你从哪里得到移植用的器官？}
#{2352}{}{Expensive? Would it be possible to get a discount of some sort?}
{2352}{}{贵吗？有没有可能给我一些折扣？}
#{2353}{}{I wanted to ask about the individual surgeries.}
{2353}{}{我想问一下个别手术的情况。}
#{2354}{}{Not interested, bye.}
{2354}{}{不感兴趣，再见。}
#{2400}{}{From donors that can't afford them. But don't worry, there is no risk of us transplanting a defective or diseased organ; we carefully inspect each and every one of them. The unsuitable organs are mostly used for research.}
{2400}{}{来自那些负担不起的捐赠者。但别担心，我们不会有移植有缺陷或患病器官的风险；我们仔细检查了每一个。不合适的器官多用于研究。}
#{2401}{}{What kind of people are those? Could you be more specific?}
{2401}{}{他们是什么样的人? 你能说得具体点吗？}
#{2402}{}{Would it be possible to get some sort of a discount for the surgeries?}
{2402}{}{手术能不能给点折扣？}
#{2404}{}{In that case, I'm not interested. Goodbye.}
{2404}{}{那样的话，我不感兴趣。再见。}
#{2450}{}{I don't concern myself with who our mercenaries catch in the wasteland, they're of no importance. If necessary, we use one of the local homeless. You'd have to ask Paul about the details, he handles donor collecting.}
{2450}{}{我不关心我们的雇佣兵在荒地里抓谁，他们不重要。如果有必要，我们会找一个当地的流浪汉。你得问保罗细节，他负责收集捐赠者。}
#{2451}{}{Are you trying to tell me you kidnap people and steal their organs?! That's horrible!}
{2451}{}{你是想告诉我你绑架别人偷他们的器官吗？！太可怕了！}
#{2452}{}{Are you trying to tell me you kidnap people and steal their organs?! Can I work for you?}
{2452}{}{你是想告诉我你绑架别人偷他们的器官吗？！我能为你工作吗？}
#{2500}{}{The organs are a material that is wasted on tribals or junkies with no future. We use this material for the sake of people who can afford it. We can utilize nearly the whole body for surgeries, research, and the like.}
{2500}{}{这些器官在没有未来的部落或瘾君子身上是一种浪费。我们使用这种材料是为了那些买得起它的人。我们几乎可以利用整个身体进行手术、研究等等。}
#{2501}{}{I don't think it's right for one or more people to die so that someone else would have an easier life.}
{2501}{}{我不认为让一个或更多的人去死，让其他人过上更轻松的生活是正确的。}
#{2502}{}{Alright, tell me about the operations again.}
{2502}{}{好吧，再跟我说说手术的情况。}
#{2503}{}{Sounds reasonable. What kinds of surgeries are you talking about?}
{2503}{}{听起来很合理。你说的是什么样的手术？}
#{2504}{}{And you're telling me, just like that? What if I turn you in?}
{2504}{}{你就这么告诉我吗？如果我告发你呢？}
#{2505}{}{What you do here is abhorrent! I'll kill you all to stop you.}
{2505}{}{你在这里做的事太可恶了！我要杀了你们所有人来阻止你们。}
#{2506}{}{What you do here is abhorrent! I'll kill you all to stop you.}
{2506}{}{你在这里做的事太可恶了！我要杀了你们所有人来阻止你们。}
#{2507}{}{I refuse to talk to someone like you.}
{2507}{}{我拒绝和你这样的人说话。}
#{2550}{}{It is merely business. But were I to look at it the way you do, I would say that it's not right for someone to destroy his own body with drugs and the like when his organs could help someone who can afford them and will likely take much better care of them.}
{2550}{}{这只是生意。但是，如果我以你的方式看待这个问题，我会说，一个人用毒品等东西摧毁自己的身体是不对的，因为他的器官可以帮助那些负担得起它们的人，而且可能会更好地照顾它们。}
#{2551}{}{How about helping the poor who are not on drugs, then?}
{2551}{}{那么，帮助那些不吸毒的穷人怎么样？}
#{2600}{}{We can't help everyone in the world, we need to choose. I help myself. I do what I'm interested in, I make money, and I manage to move the boundaries of medical science as well. None of that would be possible if I acted according to your views.}
{2600}{}{我们不能帮助世界上的每一个人，我们需要做出选择。我自己动手。我做我感兴趣的事，我赚钱，我也设法突破医学科学的界限。如果我按照你的观点行事，这一切都是不可能的。}
#{2650}{}{The Mutant Hunters are in charge of Albuquerque, and, though you may find it surprising, there are intelligent people among them that can be reasoned with. Commander Herman is one of them. As long as we don't treat mutants, he doesn't interfere in our business. We could no doubt make quite a sum from the removal or treatment of mutations, but, in the interest of preserving good relations, we respect the Hunters' wishes.}
{2650}{}{变种猎人掌管着阿尔伯克基，虽然你可能会感到惊讶，但他们当中有聪明的人是可以讲道理的。赫尔曼指挥官就是其中之一。只要我们不治疗变种人，他就不会干涉我们的生意。毫无疑问，我们可以通过去除或治疗突变体获得可观的收益，但是，为了保持良好的关系，我们尊重猎人的意愿。}
#{2651}{}{But doctor Yaotzin doesn't seem to think of your hospital too highly.}
{2651}{}{但耀津医生似乎对你的医院评价不高。}
#{2652}{}{I won't give up that easily! I won't rest until I find someone in this city that will help me stop you!}
{2652}{}{我不会轻易放弃的！不找到能帮我阻止你的人我是不会善罢甘休的！}
#{2653}{}{If no one else will stop you, then I will!}
{2653}{}{如果没人能阻止你，那就我来！}
#{2654}{}{I guess it's pointless to try doing something about it.}
{2654}{}{我猜这是无意义的尝试做些什么。}
#{2700}{}{I doubt you would succeed. But, since I don't want to let you spread rumors about our hospital... [Someone firmly grabs you from behind around your neck and plunges a syringe into your artery. You slowly lose consciousness.] I think it would be better to turn you into a donor. [You fall asleep, never to wake again.]}
{2700}{}{我怀疑你会成功。但是既然我不想让你散播关于我们医院的谣言…[有人从你的脖子后面紧紧抓住你，然后把注射器插入你的动脉。你慢慢失去意识。]我想把你变成一个捐献者会更好。[你睡着了，再也不会醒来。]}
#{2701}{}{[End.]}
{2701}{}{[结束。]}
#{2750}{}{I doubt you would succeed. But, since I don't want to let you spread rumors about our hospital... [At the last moment, you notice a stocky man with a syringe trying to grab you from behind and narrowly dodge him.]}
{2750}{}{我怀疑你会成功。但是既然我不想让你散播关于我们医院的谣言…[在最后一刻，你注意到一个拿着注射器的矮壮男人试图从后面抓住你，并勉强躲过了他。]}
#{2751}{}{[Defend yourself.]}
{2751}{}{[保护自己。]}
#{2800}{}{I doubt you would succeed. But, since I don't want to let you spread rumors about our hospital... [Someone firmly grabs you from behind around your neck and plunges a syringe into your artery. You slowly lose consciousness.] I think it would be better to turn you into a donor. [You fall asleep, never to wake again.]}
{2800}{}{我怀疑你会成功。但是既然我不想让你散播关于我们医院的谣言…[有人从你的脖子后面紧紧抓住你，然后把注射器插入你的动脉。你慢慢失去意识。]我想把你变成一个捐献者会更好。[你睡着了，再也不会醒来。]}
#{2850}{}{I doubt you would succeed. But, since I don't want to let you spread rumors about our hospital... [At the last moment, you notice a stocky man with a syringe trying to grab you from behind and narrowly dodge him.]}
{2850}{}{我怀疑你会成功。但是既然我不想让你散播关于我们医院的谣言…[在最后一刻，你注意到一个拿着注射器的矮壮男人试图从后面抓住你，并勉强躲过了他。]}
#{2900}{}{I don't know doctor Yaotzin personally, but I've heard that he's not very fond of us. Fortunately, he has no say in this matter. His words about honor are nothing but arrogant bluster. His main interest is killing mutants, mine is healing people.}
{2900}{}{我不认识耀津医生，但我听说他不太喜欢我们。幸运的是，他在这件事上没有发言权。他那些关于荣誉的话不过是傲慢的吹嘘。他的主要兴趣是杀死变种人，而我的兴趣是治疗人类。}
#{2901}{}{Healing for large amounts of caps...}
{2901}{}{治疗需要大量的瓶盖…}
#{2902}{}{I think you're monsters! I won't rest until I find someone in this city that will help me stop you!}
{2902}{}{我觉得你们是怪物！不找到能帮我阻止你的人我是不会善罢甘休的！}
#{2903}{}{Doctor Yaotzin can't do anything about you, but I can; I'll shoot you all!}
{2903}{}{耀津医生对你无能为力，但我可以；我会杀了你们所有人！}
#{2904}{}{That's your opinion, but you're entitled to it.}
{2904}{}{那是你的想法，但你有权这么做。}
#{2950}{}{Quality work demands appropriate pay. I see nothing wrong about that.}
{2950}{}{高质量的工作需要适当的报酬。我看不出这有什么不对。}
#{3000}{}{Put simply, by performing minor surgical procedures and transplanting higher quality organs we are able to increase your strength, endurance, perception, and reaction speed, as well as make you more attractive. A noticeable improvement by, shall we say, one degree. Since it is hard for the human body to accept and make use of organs that are too powerful, you can only undergo each of the operations once. And I'm sure I don't have to tell you that they are quite expensive.}
{3000}{}{简单地说，通过进行小手术和移植更高质量的器官，我们能够提高你的力量、耐力、感知力和反应速度，并使你更有吸引力。我们可以说，这是一个显著的进步。由于人体很难接受和利用过于强大的器官，因此每次手术只能进行一次。我相信我不必告诉你它们很贵。}
#{3001}{}{Who will you get the organs from? Could you be more specific?}
{3001}{}{你将从谁那里得到器官？你能说得更具体些吗？}
#{3003}{}{I wanted to ask about the individual surgeries.}
{3003}{}{我想问一下个别手术的情况。}
#{3004}{}{In that case, I'm not interest. Goodbye.}
{3004}{}{那样的话，我不感兴趣。再见。}
#{3050}{}{We do not perform cheaper, lower quality procedures. If you need to ask for a discount, it would be better for you to just forget about the surgeries entirely. The only way to save money is to bring us a suitable donor yourself. We'll transplant the donors organs to you, and if we get to keep the rest of the body, the procedure will only cost half of the original price. Or, if you have a donor for sale but aren't interested in any of the procedures, I'm sure we can come to some sort of an agreement as well.}
{3050}{}{我们不做廉价、低质量的手术。如果你想要折扣，最好还是完全忘记手术的事。省钱的唯一办法就是你自己给我们找个合适的捐赠者。我们会把捐献者的器官移植给你，如果我们能保留身体的其余部分，手术只需原价的一半。或者，如果你有一个捐赠者要出售，但对任何手术都不感兴趣，我相信我们也可以达成某种协议。}
#{3051}{}{Alright, tell me about the surgeries again.}
{3051}{}{好吧，再跟我说说手术的事。}
#{3052}{}{If I won't bring you a donor, where will you get one?}
{3052}{}{如果我不给你带个捐赠者，你去哪找呢？}
#{3053}{}{What will you give me for Gabriel?}
{3053}{}{你拿什么换加百利？}
#{3054}{}{What will you give me for Keri?}
{3054}{}{你拿什么换凯莉？}
#{3055}{}{What will you give me for Lystra?}
{3055}{}{你拿什么换莱斯特拉？}
#{3056}{}{I could send a boy that recently left the empire to you.}
{3056}{}{我可以把一个最近离开帝国的男孩交给你。}
#{3057}{}{I'm guessing you're not interested in buying a dog?}
{3057}{}{我猜你对买狗不感兴趣？}
#{3058}{}{Perhaps I could send one of the local tribals to you.}
{3058}{}{也许我可以找一个当地部落的人给你。}
#{3059}{}{If you say so. I'm not interested in the surgeries anymore. Goodbye.}
{3059}{}{如果你这么说的话，我对手术不再感兴趣了。再见。}
#{3060}{}{If someone joins me, I might bring them here. Goodbye, for now.}
{3060}{}{如果有人加入我，我可能会把他们带到这里。现在，再见了。}
#{3100}{}{During this procedure we'll replace a large part of your musculature: the musculus pectoralis major, musculus biceps brachii, triceps brachii, and deltoideus too, if necessary, as well as others. We have more than enough muscle donors, and, though it may not sound that way, the procedure is nothing complicated, meaning it will only cost you 10000 caps. However, a three-week convalescence period will be necessary, as you will need to get used to the new muscles.}
{3100}{}{在这个过程中，我们将替换你的大部分肌肉组织：胸大肌，肱二头肌，肱三头肌，三角肌。如果必要的话，还有其他肌肉组织。我们有足够多的肌肉捐赠者，虽然听起来可能不是这样，但手术过程并不复杂，这意味着只需要花费10000个瓶盖。然而，三周的恢复期是必要的，因为你需要适应新的肌肉。}
#{3101}{}{I'm in, here's 10000 caps.}
{3101}{}{我同意，这有10000个瓶盖。}
#{3102}{}{Tell me about the procedures again.}
{3102}{}{再跟我说一遍手术过程。}
#{3103}{}{Not interested. Bye.}
{3103}{}{没兴趣，再见。}
#{3104}{}{I don't have that much. Bye.}
{3104}{}{我没那么多钱，再见。}
#{3150}{}{During this procedure we'll replace a large part of your musculature: the musculus pectoralis major, musculus biceps brachii, triceps brachii, and deltoideus too, if necessary, as well as others. We have more than enough muscle donors, and, though it may not sound that way, the procedure is nothing complicated, meaning it will only cost you 10000 caps. And it could cost you only half of that if you give us your companion. From what I can see, I'd say that his musculature would be perfect for you. However, a three-week convalescence period will be necessary, as you will need to get used to the new muscles.}
{3150}{}{在这个过程中，我们将替换你的大部分肌肉组织：胸大肌，肱二头肌，肱三头肌，三角肌。如果必要的话，还有其他肌肉组织。我们有足够多的肌肉捐赠者，虽然听起来可能不是这样，但手术过程并不复杂，这意味着只需要花费10000个瓶盖。如果你把你的同伴给我们，你只需要花一半的钱。在我看来，他的肌肉组织非常适合你。然而，三周的恢复期是必要的，因为你需要适应新的肌肉。}
#{3151}{}{I'm in, but I won't sacrifice Gabriel. Here's 10000 caps.}
{3151}{}{我同意，但我不会牺牲加百列。这有10000个瓶盖。}
#{3152}{}{I'm in, you can "use" Gabriel. Here's 5000 caps.}
{3152}{}{我同意，你可以“利用”加百列。这有5000个瓶盖。}
#{3154}{}{Not interested. Bye.}
{3154}{}{没兴趣。再见。}
#{3155}{}{I don't have 10000 caps and I won't sacrifice Gabriel. Goodbye.}
{3155}{}{我没有10000个瓶盖并且我也不会牺牲加百列。再见。}
#{3200}{}{You're not getting any stronger. I can see right away that your musculature is simply exemplary, and I must say that it would be tremendously valuable if had I the opportunity to transplant it to another customer.}
{3200}{}{你没有变得更强。我一眼就能看出你的肌肉组织简直就是典范，我必须说，如果我有机会把它移植给另一个客户，那将是非常有价值的。}
#{3201}{}{Tell me about the procedures again.}
{3201}{}{再跟我说一遍手术过程。}
#{3202}{}{You're sure as hell not getting my muscles. I'm leaving.}
{3202}{}{你肯定不会得到我的肌肉。我要走了。}
#{3250}{}{Lie on the bed and I will put you to sleep. The surgery will take a few hours. [Doctor Falber injects you with something and you lose consciousness.]}
{3250}{}{躺在床上，我会让你睡着的。手术需要几个小时。[福伯医生给你注射了某种东西，你失去了意识。]}
#{3251}{}{[Fall asleep.]}
{3251}{}{[睡着了。]}
#{3300}{}{[You feel weak like a child after the operation, you barely manage to move. After some exercise you slowly get back in shape, and after three weeks you feel stronger than ever before. Doctor Falber visits you for one last check up.] I see there were no complications. As always, my work was impeccable.}
{3300}{}{[手术后你感觉像个孩子一样虚弱，几乎无法动弹。经过一些锻炼后，你慢慢恢复了状态，三周后，你感觉比以往任何时候都更强壮。福伯医生来看你做最后一次检查。]看来没有并发症。一如既往，我的工作无懈可击。}
#{3301}{}{[You feel weak like a child after the operation, you barely manage to move. After some exercise you slowly get back in shape, and after three weeks you feel stronger than ever before. Doctor Falber visits you for one last check up.] I see there were no complications. As always, my work was impeccable.}
{3301}{}{[手术后你感觉像个孩子一样虚弱，几乎无法动弹。经过一些锻炼后，你慢慢恢复了状态，三周后，你感觉比以往任何时候都更强壮。福伯医生来看你做最后一次检查。]看来没有并发症。一如既往，我的工作无懈可击。}
#{3302}{}{[Doctor Falber operates on you for about half a day. You spend the rest of the week lying on the bed with bandages covering your eyes. You begin to notice that your hearing has become more sensitive and that you can discern smells that you didn't even know about before. When doctor Falber removes the bandages covering your eyes during a final check up, you immediately realize that your eyesight is sharper than it used to be.] I see there were no complications. As always, my work was impeccable.}
{3302}{}{[福伯医生为你做了大约半天的手术。接下来的一周你都躺在床上，眼睛上缠着绷带。你开始注意到你的听力变得更加敏感，你可以辨别出你以前甚至不知道的气味。在最后一次检查时，当 福伯医生取下你眼睛上的绷带时，你马上意识到你的视力比以前更敏锐了。]看来没有并发症。一如既往，我的工作无懈可击。}
#{3303}{}{[Doctor Falber operates on you for about half a day. You spend the rest of the week lying on the bed with bandages covering your eyes. You begin to notice that your hearing has become more sensitive and that you can discern smells that you didn't even know about before. When doctor Falber removes the bandages covering your eyes during a final check up, you immediately realize that your eyesight is sharper than it used to be.] I see there were no complications. As always, my work was impeccable.}
{3303}{}{[福伯医生为你做了大约半天的手术。接下来的一周你都躺在床上，眼睛上缠着绷带。你开始注意到你的听力变得更加敏感，你可以辨别出你以前甚至不知道的气味。在最后一次检查时，当 福伯医生取下你眼睛上的绷带时，你马上意识到你的视力比以前更敏锐了。]看来没有并发症。一如既往，我的工作无懈可击。}
#{3304}{}{[You were in the same shape as before on the day after the operation, and every passing day it got even better. You feel a bit tougher. As you were able to test during the convalescence, thanks to your new and stronger heart you can withstand heavier physical strain than before. Doctor Falber visits you for one last check up.] I see there were no complications. As always, my work was impeccable.}
{3304}{}{[手术后的第二天，你的身体状况还是和以前一样，而且一天比一天好。你感觉更强壮了。由于你能够在恢复期测试，感谢你新的和更强大的心脏，你可以承受比以前更重的身体压力。福伯医生来给你做最后一次检查。]看来没有并发症。一如既往，我的工作无懈可击。}
#{3305}{}{[You were in the same shape as before on the day after the operation, and every passing day it got even better. You feel a bit tougher. As you were able to test during the convalescence, thanks to your new and stronger heart you can withstand heavier physical strain than before. Doctor Falber visits you for one last check up.] I see there were no complications. As always, my work was impeccable.}
{3305}{}{[手术后的第二天，你的身体状况还是和以前一样，而且一天比一天好。你感觉更强壮了。由于你能够在恢复期测试，感谢你新的和更强大的心脏，你可以承受比以前更重的身体压力。福伯医生来给你做最后一次检查。]看来没有并发症。一如既往，我的工作无懈可击。}
#{3306}{}{[Even during your convalescence period you notice that people react more amiably to you. The image you used to see in the mirror has changed only subtly, but you can still feel a difference. It will be a while before you get used to it again. Doctor Falber visits you for one last check up.] I see there were no complications. As always, my work was impeccable.}
{3306}{}{[即使在你的恢复期，你也注意到人们对你的反应更友好了。你过去在镜子里看到的形象只发生了微妙的变化，但你仍然能感觉到不同。你需要一段时间才能重新适应。福伯医生来给你做最后一次检查。]看来没有并发症。一如既往，我的工作无懈可击。}
#{3307}{}{[Even during your convalescence period you notice that people react more amiably to you. The image you used to see in the mirror has changed only subtly, but you can still feel a difference. It will be a while before you get used to it again. Doctor Falber visits you for one last check up.] I see there were no complications. As always, my work was impeccable.}
{3307}{}{[即使在你的恢复期，你也注意到人们对你的反应更友好了。你过去在镜子里看到的形象只发生了微妙的变化，但你仍然能感觉到不同。你需要一段时间才能重新适应。福伯医生来给你做最后一次检查。]看来没有并发症。一如既往，我的工作无懈可击。}
#{3308}{}{[You spent most of the time asleep, dreaming. During the final check up, Doctor Falber gives you a series of tests to test your memory and logical thinking. He didn't even have to tell you the results, you noticed the increase in speed of your reasoning and recalling information by yourself.] I see there were no complications. As always, my work was impeccable.}
{3308}{}{[你大部分时间都在睡觉，做梦。在最后的检查中，福伯医生给你做了一系列的测试来测试你的记忆力和逻辑思维。他甚至不需要告诉你结果，你会发现自己推理和回忆信息的速度提高了。]
看来没有并发症。一如既往，我的工作无懈可击。}
#{3309}{}{[You spent most of the time asleep, dreaming. During the final check up, Doctor Falber gives you a series of tests to test your memory and logical thinking. He didn't even have to tell you the results, you noticed the increase in speed of your reasoning and recalling information by yourself.] I see there were no complications. As always, my work was impeccable.}
{3309}{}{[你大部分时间都在睡觉，做梦。在最后的检查中，福伯医生给你做了一系列的测试来测试你的记忆力和逻辑思维。他甚至不需要告诉你结果，你会发现自己推理和回忆信息的速度提高了。]
看来没有并发症。一如既往，我的工作无懈可击。}
#{3310}{}{[You spent the last two weeks alternately unconscious on the operating table and overcoming severe pain during convalescence. But it was worth it. All you need to do is stretch your muscles to feel that they react much faster and are more controllable. Doctor Falber visits you for one last check up.] I see there were no complications. As always, my work was impeccable.}
{3310}{}{[过去两周，你在手术台上时而昏迷，时而克服恢复期的剧烈疼痛。但这是值得的。你所需要做的就是伸展你的肌肉，感觉它们反应得更快，更可控。福伯医生来给你做最后一次检查。]看来没有并发症。一如既往，我的工作无懈可击。}
#{3311}{}{[You spent the last two weeks alternately unconscious on the operating table and overcoming severe pain during convalescence. But it was worth it. All you need to do is stretch your muscles to feel that they react much faster and are more controllable. Doctor Falber visits you for one last check up.] I see there were no complications. As always, my work was impeccable.}
{3311}{}{[过去两周，你在手术台上时而昏迷，时而克服恢复期的剧烈疼痛。但这是值得的。你所需要做的就是伸展你的肌肉，感觉它们反应得更快，更可控。福伯医生来给你做最后一次检查。]看来没有并发症。一如既往，我的工作无懈可击。}
#{3312}{}{Thanks, doctor.}
{3312}{}{谢谢，医生。}
#{3313}{}{Hee!}
{3313}{}{嘿！}
#{3350}{}{Since the procedure involves dealing with extremely sensitive parts, it will take several surgeries that need to be performed with utmost care. You will get new eyes, both from the same donor of course, to preserve symmetry. We will increase the size of the olfactory epithelium and transplant a more sensitive malleus, incus, and stapes. Finally, we'll fine tune the mesencephalon accordingly. It will cost you 20000 caps, but the convalescence period is only one week.}
{3350}{}{由于手术涉及到极其敏感的部位，需要进行几次手术，并且需要极其小心地进行。你会得到一双新的眼睛，当然是来自同一个捐献者，以保持对称性。我们将增加嗅觉上皮细胞的大小并移植更敏感的锤骨，砧骨和镫骨。最后，我们会相应地微调中脑。这将花费你20000瓶盖，但恢复期只需一周。}
#{3351}{}{I'm in, here's 20000 caps.}
{3351}{}{我同意，这有20000个瓶盖。}
#{3353}{}{Not interested. Bye.}
{3353}{}{没兴趣。再见。}
#{3354}{}{I don't have that much. Bye.}
{3354}{}{我没那么多钱，再见。}
#{3400}{}{Since the procedure involves dealing with extremely sensitive parts, it will take several surgeries that need to be performed with utmost care. You will get new eyes, both from the same donor of course, to preserve symmetry. We will increase the size of the olfactory epithelium and transplant a more sensitive malleus, incus, and stapes. Finally, we'll fine tune the mesencephalon accordingly. It will cost you 20000 caps, but the convalescence period is only one week. You companion seems like a suitable donor, and I'm sure we can use her other organs ourselves. Should you give her to us, the procedure will only cost half of the original amount.}
{3400}{}{由于手术涉及到极其敏感的部位，需要进行几次手术，并且需要极其小心地进行。你会得到一双新的眼睛，当然是来自同一个捐献者，以保持对称性。我们将增加嗅觉上皮细胞的大小并移植更敏感的锤骨，砧骨和镫骨。最后，我们会相应地微调中脑。这将花费你20000瓶盖，但恢复期只需一周。你的同伴看起来是个合适的捐赠者，我相信我们自己也可以用她的其他器官。如果你把她交给我们，手术费只需原来的一半。}
#{3401}{}{I'm in, but I won't sacrifice Keri. Here's 20000 caps.}
{3401}{}{我同意，但我不会牺牲凯莉。这是20000瓶盖。}
#{3402}{}{I'm in, you can "use" Keri. Here's 10000 caps.}
{3402}{}{我同意，你可以“利用”凯莉。这有10000个瓶盖。}
#{3404}{}{Not interested. Bye.}
{3404}{}{没兴趣。再见。}
#{3405}{}{I don't have 10000 caps and I won't sacrifice Keri. Goodbye.}
{3405}{}{我没有10000瓶盖并且我也不会牺牲凯莉。再见。}
#{3450}{}{I see how your pupils react, how you perceive even the slightest sound; your perception is unique. How I'd love to examine such a splendid nervous system... One thing is clear, though - we can't increase your perception any further.}
{3450}{}{我看到了你瞳孔的反应，看到了你对最轻微的声音的感知；你的感知是独一无二的。我是多么想检查如此出色的神经系统…但有一件事是明确的 - 我们不能再增加你的感知力了。}
#{3452}{}{You're not examining my anything. I'm leaving.}
{3452}{}{你不用检查我的任何东西。我要走了。}
#{3500}{}{Lie on the bed and I will put you to sleep. The surgery will take a few hours. [Doctor Falber injects you with something and you lose consciousness.]}
{3500}{}{躺在床上，我会让你睡着的。手术需要几个小时。[福伯医生给你注射了某种东西，你失去了意识。]}
#{3501}{}{[Fall asleep.]}
{3501}{}{[睡着了。]}
#{3550}{}{It's not a complicated procedure, and the convalescence period is only one week. What raises the price to 15000 caps is a special protective alloy containing biological elements that we will implant under your skin. You will thus gain increased endurance without the implant being visible or discernible by touch. We will also strengthen the bones that need it, certainly the coxae and sacrum at least. Finally, we'll transplant you a new heart for a complete increase in endurance and stamina.}
{3550}{}{这不是一个复杂的手术，恢复期只需一周。将价格提高到15000个瓶盖的是一种特殊的保护合金，其中含有生物元素，我们会把它植入你的皮肤下。因此，您将获得更高的耐力，并且不会通过触摸看到或被识别出植入物。我们也会加固需要的骨头，当然至少是髋骨和骶骨。最后，我们会给你移植一个新的心脏来提高你的耐力和力量。}
#{3551}{}{I'm in, here's 15000 caps.}
{3551}{}{我同意，这有15000个瓶盖。}
#{3553}{}{Not interested. Bye.}
{3553}{}{没兴趣。再见。}
#{3554}{}{I don't have that much. Bye.}
{3554}{}{我没那么多钱，再见。}
#{3600}{}{Just take a look at the structure of your body, granting you the best possible endurance. No operation could improve anything in this regard. Oh, if only I had the fascinating opportunity to examine at least you heart on the operating table.}
{3600}{}{只要看看你的身体结构，就能给你最好的耐力。任何手术都不能改善这方面的情况。噢，要是我能有个绝妙的机会至少在手术台上检查一下你的心脏就好了。}
#{3602}{}{I don't like you talking about my heart and operating table in one sentence. I'm leaving.}
{3602}{}{我不喜欢你每一句话都谈论我的心脏和手术台。我要走了。}
#{3650}{}{Lie on the bed and I will put you to sleep. The surgery will take a few hours. [Doctor Falber injects you with something and you lose consciousness.]}
{3650}{}{躺在床上，我会让你睡着的。手术需要几个小时。[福伯医生给你注射了某种东西，你失去了意识。]}
#{3651}{}{[Fall asleep.]}
{3651}{}{[睡着了。]}
#{3700}{}{A simple procedure, mostly involving a number of aesthetic plastic surgeries - changes in facial muscles, liposuction, silicon implants, and the like. You will get improved apocrine glands that emit pheromones and scents that help induce trust and sympathy in others. Skin that is too repulsive or damaged can be replaced in some spots without any visible scars, using better looking skin from one of the donors. It will be mere 5000 caps in total, and you will be able to leave after two days.}
{3700}{}{一个简单的手术，主要涉及一些美容整形手术-改变面部肌肉，吸脂，硅植入物，等等。你会得到改善顶分泌腺，释放信息素和气味，有助于诱导信任和同情他人。如果皮肤过于难看或受损，可以在没有任何明显疤痕的情况下，使用来自捐赠者更漂亮的皮肤进行替换。总共只要5000瓶盖，两天后你就可以离开了。}
#{3701}{}{I'm in, here's 5000 caps.}
{3701}{}{我同意，这有5000瓶盖。}
#{3702}{}{I know a local tribal that could make for a suitable donor for this operation.}
{3702}{}{我知道一个当地的部落可以为这次手术找到合适的捐赠者。}
#{3703}{}{I know a local immigrant that could make for a suitable donor for this operation.}
{3703}{}{我认识一个当地的移民可以成为这个手术的合适捐赠者。}
#{3705}{}{Not interested. Bye.}
{3705}{}{没兴趣。再见。}
#{3706}{}{I don't have that much. Bye.}
{3706}{}{我没那么多钱。再见。}
#{3750}{}{I have no doubts that you realize how exceptionally attractive you are, seeing how the others react to you. Not even I could do much to improve your appearance. I'm not entirely sure about all the factors comprising such high charisma myself. I'd have to dissect you carefully to discover them all.}
{3750}{}{我毫不怀疑，看看别人对你的反应，你会意识到自己多么有吸引力。就算是我也没办法改善你的外表。我自己也不完全确定构成如此高魅力的所有因素。我得仔细解剖你才能发现它们。}
#{3752}{}{You're sure as hell not dissecting me. I'm leaving.}
{3752}{}{你绝对不能解剖我。我要走了。}
#{3800}{}{Lie on the bed and I will put you to sleep. The surgery will take a few hours. [Doctor Falber injects you with something and you lose consciousness.]}
{3800}{}{躺在床上，我会让你睡着的。手术需要几个小时。[福伯医生给你注射了某种东西，你失去了意识。]}
#{3801}{}{[Fall asleep.]}
{3801}{}{[睡着了。]}
#{3850}{}{Increasing intelligence is the most difficult procedure that we are able to conduct. It costs 30000 caps, and involves a three week convalescence period. It consists of a long and complex brain surgery mostly aimed at the telencephalon, and the limbic system. Plus, a transplant of certain chemical compounds that stimulate faster association, and their donors are quite rare.}
{3850}{}{提高智力是我们能够进行的最困难的手术。它需要30000瓶盖，需要三周的恢复期。它包括一个长而复杂的脑部手术，主要针对大脑和边缘系统。此外，某些化学化合物的移植可以促进更快的联想，而它们的供体是相当罕见的。}
#{3851}{}{I'm in, here's 30000 caps.}
{3851}{}{我同意，这有30000个瓶盖。}
#{3853}{}{Not interested. Bye.}
{3853}{}{没兴趣。再见。}
#{3854}{}{I don't have that much. Bye.}
{3854}{}{我没那么多钱。再见。}
#{3900}{}{Increasing intelligence is the most difficult procedure that we are able to conduct. It costs 30000 caps, and involves a three week convalescence period. It consists of a long and complex brain surgery mostly aimed at the telencephalon, and the limbic system. Plus, a transplant of certain chemical compounds that stimulate faster association, and their donors are quite rare. Though your companion seems to be suitable for a donor.}
{3900}{}{提高智力是我们能够进行的最困难的手术。它需要30000瓶盖，需要三周的恢复期。它包括一个长而复杂的脑部手术，主要针对大脑和边缘系统。此外，某些化学化合物的移植可以促进更快的联想，而它们的供体是相当罕见的。不过你的同伴似乎很适合做捐赠者。}
#{3901}{}{I'm in, but I won't sacrifice Lystra. Here's 30000 caps.}
{3901}{}{我同意，但我不会牺牲莱斯特。这是30000瓶盖。}
#{3902}{}{I'm in, you can "use" Lystra. Here's 15000 caps.}
{3902}{}{我同意，你可以“利用”莱斯特拉。这有15000个瓶盖。}
#{3904}{}{Not interested. Bye.}
{3904}{}{没兴趣。再见。}
#{3905}{}{I don't have 30000 caps and I won't sacrifice Lystra. Goodbye.}
{3905}{}{我没有30000个瓶盖并且我也不会牺牲莱斯特拉。再见。}
#{3950}{}{I can see right away that your brain is exceptional even by its size. It would be quite interesting to test its reactions to various electric stimulations in vivo, but there is no point in trying to improve it any further.}
{3950}{}{我一眼就能看出你的大脑即使从体积上看也是与众不同的。在体内测试它对各种电刺激的反应将是非常有趣的，但试图进一步改善它是没有意义的。}
#{3952}{}{I can imagine how painful would such experiments be. I'm leaving.}
{3952}{}{我可以想象这样的实验有多痛苦。我要走了。}
#{4000}{}{Lie on the bed and I will put you to sleep. The surgery will take a few hours. [Doctor Falber injects you with something and you lose consciousness.]}
{4000}{}{躺在床上，我会让你睡着的。手术需要几个小时。[福伯医生给你注射了某种东西，你失去了意识。]}
#{4001}{}{[Fall asleep.]}
{4001}{}{[睡着了。]}
#{4050}{}{Improving agility is not difficult, but it is quite arduous. The operations take a long time, they are conducted gradually over a period of two weeks and require two or more donors, depending on the quality of their nervous pathways. We will need to implant you shorter ones to make your reflex arc faster, and replace your tendons with looser ones. And, just to make sure, we'll transplant bigger lungs, as you might need more oxygen to facilitate increased agility. It will be 25000 caps.}
{4050}{}{提高敏捷性并不困难，但相当艰巨。手术需要很长时间，需要在两周内逐步进行，需要两个或更多的供体，这取决于他们神经通路的质量。我们需要给你植入较短的肌腱，使你的反射弧更快，用较松的肌腱代替你的肌腱。为了保险起见，我们会移植更大的肺，因为你可能需要更多的氧气来提高灵活性。它将是25000个瓶盖。}
#{4051}{}{I'm in, here's 25000 caps.}
{4051}{}{我同意，这有25000瓶盖。}
#{4053}{}{Not interested. Bye.}
{4053}{}{没兴趣。再见。}
#{4054}{}{I don't have that much. Bye.}
{4054}{}{我没那么多钱。再见。}
#{4055}{}{I know about a boy from the empire that could be a suitable donor for this procedure.}
{4055}{}{我知道一个来自帝国的男孩可能是这个手术的合适捐赠者。}
#{4150}{}{Your moves are as smooth and quick as human limits allow. Operating on you would be pointless, unless you wanted to become a donor.}
{4150}{}{你的动作是人类极限所允许的最快最流畅的。给你做手术毫无意义，除非你想成为捐赠者。}
#{4152}{}{I've no intent of becoming a donor. I'm leaving.}
{4152}{}{我没打算捐献，我要走了。}
#{4200}{}{Lie on the bed and I will put you to sleep. The surgery will take a few hours. [Doctor Falber injects you with something and you lose consciousness.]}
{4200}{}{躺在床上，我会让你睡着的。手术需要几个小时。[福伯医生给你注射了某种东西，你失去了意识。]}
#{4201}{}{[Fall asleep.]}
{4201}{}{[睡着了。]}
#{4250}{}{We do not perform cheaper, lower quality procedures. If you need to ask for a discount, it would be better for you to just forget about the surgeries entirely. The only way to save money is to bring us a suitable donor yourself. We'll transplant the donors organs to you, and if we get to keep the rest of the body, the procedure will only cost half of the original price. Or, if you have a donor for sale but aren't interested in any of the procedures, I'm sure we can come to some sort of an agreement as well.}
{4250}{}{我们不做廉价、低质量的手术。如果你想要折扣，最好还是完全忘记手术的事。省钱的唯一办法就是你自己给我们找个合适的捐赠者。我们会把捐献者的器官移植给你，如果我们能保留身体的其余部分，手术只需原价的一半。或者，如果你有一个捐赠者要出售，但对任何手术都不感兴趣，我相信我们也可以达成某种协议。}
#{4258}{}{Perhaps I could send one of the local immigrants to you.}
{4258}{}{也许我可以给你当地的移民。}
#{4300}{}{I see he's rather muscular, we could use him in a strength enhancing procedure, or give you 5000 caps for him. I know it's not much, but we can get plenty similarly equipped donors from among the tribals, and he doesn't seem to be exceptional in any other way.}
{4300}{}{我看他肌肉发达，我们可以用他来加强力量，或者给你5000个瓶盖换他。我知道这不多，但我们可以从部落中得到很多类似的捐赠者，而且他在其他方面似乎也没什么特别。}
#{4301}{}{Tell me about the procedure.}
{4301}{}{告诉我手术过程。}
#{4302}{}{Give me 5000 and he's yours.}
{4302}{}{给我5000，他就是你的了。}
#{4303}{}{Why don't you rather tell me about all the operations.}
{4303}{}{你为什么不告诉我所有的手术呢。}
#{4304}{}{And what would you give me for Keri here?}
{4304}{}{你愿意给我多少钱来换凯莉？}
#{4305}{}{And what would you give me for Lystra here?}
{4305}{}{你愿意出多少钱换莱斯特拉？}
#{4306}{}{I could send a boy that recently left the empire to you.}
{4306}{}{我可以把一个最近离开帝国的男孩交给你。}
#{4307}{}{I'm guessing you're not interested in buying a dog?}
{4307}{}{我猜你对买狗不感兴趣？}
#{4308}{}{Not interested. Bye.}
{4308}{}{没兴趣。再见。}
#{4309}{}{Perhaps I could send one of the local tribals to you.}
{4309}{}{也许我可以找一个当地部落的人给你。}
#{4310}{}{Perhaps I could send one of the local immigrants to you.}
{4310}{}{也许我可以给你当地的移民。}
#{4350}{}{Excellent, I am quite fond of doing good business, and this one benefits us both.}
{4350}{}{太好了，我很喜欢做生意，这对我们双方都有利。}
#{4351}{}{My pleasure.}
{4351}{}{我的荣幸。}
#{4400}{}{Your companion's perception seems to be at quite a high level, and her eyes are also aesthetically pleasing. No doubt we could use her for the perception enhancing procedure at the very least, meaning that I can give you 10000 caps for her.}
{4400}{}{你同伴的感知能力似乎相当高，她的眼睛也很美。毫无疑问，我们至少可以用她来做感知增强手术，这意味着我可以为她给你10000个瓶盖。}
#{4402}{}{Give me 10000 caps and you can take Keri.}
{4402}{}{给我10000个瓶盖你就能带走凯莉。}
#{4404}{}{And what would you give me for Gabriel here?}
{4404}{}{你愿意用什么换加百利？}
#{4450}{}{Donors suitable for the intelligence enhancing brain surgery are quite rare, and I do believe I have one such specimen before me right now. I can give you 15000 caps for her, and trust me, it's not often I offer someone that much for a single donor.}
{4450}{}{适合做智力增强脑部手术的捐献者非常罕见，我相信我面前就有一个这样的样本。我可以出15000个瓶盖买她，相信我，我很少为一个捐赠者出那么多钱。}
#{4452}{}{Lystra is yours for 15000 caps.}
{4452}{}{15000个瓶盖莱斯特拉就是你的了。}
#{4500}{}{If you want to sell him, send him here. I'll have him examined to determine his worth, and then I'll pay you the appropriate sum when you visit us again, minus the examination fee, of course. This investment should prove to be more than profitable for you. It's not often that we get to work with young donors. And if the boy really comes from the empire, he should be of excellent health.}
{4500}{}{如果你想卖掉他，就把他送到这里来。我会让人检查一下，确定他的价值，然后当你再来我们这里时，我会付给你适当的钱，当然是扣除检查费用。这项投资对你来说应该不仅仅是有利可图的。我们与年轻捐赠者合作的机会并不多。如果这孩子真的来自帝国，他应该非常健康。}
#{4501}{}{Tell me about the procedures again.}
{4501}{}{告诉我手术过程。}
#{4502}{}{I might have another donor for sale.}
{4502}{}{我可能会有另一个捐赠者出售。}
#{4503}{}{I might have another donor for sale.}
{4503}{}{我可能会有另一个捐赠者出售。}
#{4504}{}{OK, I'll think about it.}
{4504}{}{OK，我会考虑的。}
#{4550}{}{We only perform serious surgery in this hospital. I'd never let an animal organ be transplanted to a customer. The only place you could possibly sell the dog is the meat vendor next to our hospital.}
{4550}{}{我们这家医院只做严肃的手术。我绝不会让一个动物器官被移植到顾客身上。你唯一能卖狗的地方就是我们医院旁边的肉贩子。}
#{4551}{}{My apologies. Please, tell me about the procedures again.}
{4551}{}{我道歉。请告诉我手术过程。}
#{4552}{}{Where do you get human donors?}
{4552}{}{你从哪里得到人类捐献者？}
#{4557}{}{Thanks for the tip. Later.}
{4557}{}{谢谢提醒，回见。}
#{4600}{}{If you want to sell someone, send them here. I'll have them examined to determine their worth, and I will pay you the appropriate sum when you visit us again. But I'm afraid there simply is not a lot of exceptional material amongst the local tribals that would exceed the price of the examination, for which I'm of course charging you.}
{4600}{}{如果你想卖人，把他们送到这里来。我会让人检查一下，看看它们的价值，等你再来我们这里时，我会付给你适当的钱。但恐怕当地部落中没有太多的特殊材料会超过已检查过的价值，当然我是会向你收费的。}
#{4601}{}{Tell me about the procedures again.}
{4601}{}{告诉我手术过程。}
#{4602}{}{I might have another donor for sale.}
{4602}{}{我可能会有另一个捐赠者出售。}
#{4603}{}{OK, I'll think about it.}
{4603}{}{OK，我会考虑的。}
#{4650}{}{If you want to sell someone, send them here. I'll have them examined to determine their worth, and I will pay you the appropriate sum when you visit us again. But I'm afraid there simply is not a lot of exceptional material amongst the local immigrants that would exceed the price of the examination, for which I'm of course charging you.}
{4650}{}{如果你想卖人，把他们送到这里来。我会让人检查一下，看看它们的价值，等你再来我们这里时，我会付给你适当的钱。但恐怕当地移民中没有太多的特殊材料会超过已检查过的价值，当然我是会向你收费的。}
#{4651}{}{Tell me about the procedures again.}
{4651}{}{告诉我手术过程。}
#{4652}{}{I might have another donor for sale.}
{4652}{}{我可能会有另一个捐赠者出售。}
#{4653}{}{OK, I'll think about it.}
{4653}{}{OK，我会考虑的。}
#{4700}{}{Welcome again. What services can our hospital offer you today?}
{4700}{}{欢迎再次光临。我们医院今天能为您提供什么服务？}
#{4702}{}{I need healing.}
{4702}{}{我需要治疗。}
#{4706}{}{Tell me about the procedures.}
{4706}{}{告诉我手术过程。}
#{4707}{}{I might have a suitable donor for sale.}
{4707}{}{我可能有合适的捐赠者出售。}
#{4708}{}{Did you know that doctor Yaotzin from the Mutant Hunters doesn't think too highly of your hospital?}
{4708}{}{你知道变种猎人的耀津医生并不看好你的医院吗？}
#{4709}{}{What happened here? Were you attacked?}
{4709}{}{这里发生了什么？你被袭击了吗？}
#{4712}{}{None, my mistake.}
{4712}{}{没有，我的错。}
#{4750}{}{I'm always willing to pay well for a quality donor. Do you have someone worthy of my attentions with you?}
{4750}{}{我总是愿意为高质量的捐赠者出高价。你身边有值得我关注的人吗？}
#{4751}{}{Actually, I was more interested in the procedures you use the donors for.}
{4751}{}{实际上，我更感兴趣的是你用捐献者做的手术。}
#{4753}{}{How about Gabriel?}
{4753}{}{加百利怎么样？}
#{4754}{}{How about Keri?}
{4754}{}{凯莉怎么样？}
#{4755}{}{How about Lystra?}
{4755}{}{莱斯特拉怎么样？}
#{4756}{}{I could send a boy that recently left the empire to you.}
{4756}{}{我可以把一个最近离开帝国的男孩交给你。}
#{4757}{}{I'm guessing you're not interested in buying a dog?}
{4757}{}{我猜你对买狗不感兴趣？}
#{4758}{}{Perhaps I could send one of the local tribals to you.}
{4758}{}{也许我可以找一个当地部落的人给你。}
#{4759}{}{Perhaps I could send one of the local immigrants to you.}
{4759}{}{也许我可以给你当地的移民。}
#{4760}{}{I don't actually have anyone to sell.}
{4760}{}{实际上我没有人可以卖。}
#{4800}{}{I prefer not to owe anyone, so let's conclude our transaction right now. The tribal you sent to us is physically unexceptional, and all her organs are healthy. Her only unique feature is her extraordinarily smooth skin, which we'll be able to use for the charisma enhancing procedure. Thus, I can either give you a fifty percent discount on the procedure, or pay you the 2500 caps.}
{4800}{}{我不想亏欠任何人，所以现在让我们结束我们的交易。你送来的部落成员身体状况平常，器官都很健康。她唯一的特点就是皮肤异常光滑，我们可以用来做魅力增强手术。因此，我可以给你50% 的折扣，或者付给你2500瓶盖。}
#{4801}{}{What if I happened to change my mind, would it be possible to get her back?}
{4801}{}{如果我改主意了，有没有可能让她回到我身边？}
#{4802}{}{Give me the 2500 caps.}
{4802}{}{给我2500个瓶盖。}
#{4803}{}{Alright, here's 2500 for the procedure.}
{4803}{}{好吧，这是手术的2500。}
#{4804}{}{Give me the 2500 caps, I don't have enough to pay for the rest of the procedure anyway.}
{4804}{}{给我2500瓶盖，反正我也没有足够的钱来支付剩下的手术费用。}
#{4850}{}{I'm afraid that's not possible. Not only would I have to charge you for her examination, but we've already used some of her organs and she's incapable of movement right now.}
{4850}{}{恐怕不行。我不仅要为她的检查收费，而且我们已经用了她的一些器官，她现在不能动弹了。}
#{4851}{}{I see. I'll take the 2500 caps then.}
{4851}{}{我明白了，那我就要2500瓶盖。}
#{4900}{}{I prefer not to owe anyone, so let's conclude our transaction right now. Here's 2500 caps for the tribal you sent to us. She's physically unexceptional, and all her organs are healthy. Her only unique feature is her extraordinarily smooth skin, which we'll be able to use for the charisma enhancing procedure.}
{4900}{}{我不想欠任何人，所以现在让我们结束我们的交易。这是你送来部落成员的2500个瓶盖。她的身体很普通，所有器官都很健康。她唯一的特点就是皮肤异常光滑，我们可以用来做魅力增强手术。}
#{4901}{}{What if I happened to change my mind, would it be possible to get her back?}
{4901}{}{如果我改主意了，有没有可能让她回到我身边？}
#{4902}{}{Thanks.}
{4902}{}{谢谢。}
#{4950}{}{I'm afraid that's not possible. Not only would I have to charge you for her examination, but we've already used some of her organs and she's incapable of movement right now.}
{4950}{}{恐怕不行。我不仅要为她的检查收费，而且我们已经用了她的一些器官，她现在不能动弹了。}
#{4951}{}{OK.}
{4951}{}{OK。}
#{5000}{}{I prefer not to owe anyone, so let's conclude our transaction right now. The young man you sent to us is physically unexceptional, and all his organs are healthy. His only unique feature is his extraordinarily smooth skin, which we'll be able to use for the charisma enhancing procedure. Thus, I can either give you a fifty percent discount on the procedure, or pay you the 2500 caps.}
{5000}{}{我不想亏欠任何人，所以现在让我们结束我们的交易。你送来的那个年轻人身体状况平常，器官都很健康。他唯一的特点就是皮肤异常光滑，我们可以用来做魅力增强手术。因此，我可以给你50% 的折扣，或者付给你2500瓶盖。}
#{5001}{}{What if I happened to change my mind, would it be possible to get him back?}
{5001}{}{如果我改主意了，有没有可能让他回到我身边？}
#{5050}{}{I'm afraid that's not possible. Not only would I have to charge you for his examination, but we've already used some of his organs and he's incapable of movement right now.}
{5050}{}{恐怕不行。我不仅要为他的检查收费，而且我们已经用了他的一些器官，他现在不能动弹了。}
#{5100}{}{I prefer not to owe anyone, so let's conclude our transaction right now. Here's 2500 for the young man you sent to us. He is physically unexceptional, and all his organs are healthy. His only unique feature is his extraordinarily smooth skin, which we'll be able to use for the charisma enhancing procedure.}
{5100}{}{我不想亏欠任何人，所以现在让我们结束我们的交易。这是你送来年轻人的2500个瓶盖。他的身体很普通，所有器官都很健康。他唯一的特点就是皮肤异常光滑，我们可以用来做魅力增强手术。}
#{5101}{}{What if I happened to change my mind, would it be possible to get him back?}
{5101}{}{如果我改主意了，有没有可能让他回到我身边？}
#{5102}{}{Thanks.}
{5102}{}{谢谢。}
#{5150}{}{I'm afraid that's not possible. Not only would I have to charge you for his examination, but we've already used some of his organs and he's incapable of movement right now.}
{5150}{}{恐怕不行。我不仅要为他的检查收费，而且我们已经用了他的一些器官，他现在不能动弹了。}
#{5151}{}{OK.}
{5151}{}{OK。}
#{5200}{}{I suppose it was to be expected. There was no doubt that even they could sooner or later find out what happened to their hunters. We can't let them kill themselves by attacking our hospital. That would be too wasteful. That's why I'm planning to have Paul organize the capture of all tribals in Albuquerque. Would you be interested in helping? We will need as many people as possible to minimize donor casualties.}
{5200}{}{我想这是意料之中的。毫无疑问，即使是他们迟早也会发现他们的猎人发生了什么事。
我们不能让他们因攻击我们的医院而死。那太浪费了。这就是为什么我计划让保罗组织抓捕阿尔伯克基所有部落的原因。你有兴趣帮忙吗？我们将需要尽可能多的人来尽量减少捐赠者的伤亡。}
#{5201}{}{I'm definitely interested.}
{5201}{}{我很感兴趣。}
#{5202}{}{No, I don't want to work for you anymore.}
{5202}{}{不，我不想再为你工作了。}
#{5250}{}{In that case, there is no reason to waste each other's time. Here's 500 caps for the information. And though we won't make use of your services anymore, you are of course welcome here as a customer.}
{5250}{}{既然如此，就没有必要浪费彼此的时间了。这是提供信息的500个瓶盖。虽然我们不会再使用你的服务，但我们依然欢迎你成为我们的客户。}
#{5251}{}{In that case, there is no reason to waste each other's time. Here's 500 caps for the information. And though we won't make use of your services anymore, you are of course welcome here as a customer.}
{5251}{}{既然如此，就没有必要浪费彼此的时间了。这是提供信息的500个瓶盖。虽然我们不会再使用你们的服务，但我们依然欢迎你成为我们的客户。}
#{5252}{}{Farewell.}
{5252}{}{再见。}
#{5300}{}{Excellent, here's 500 caps for the information. But first, I have a different task for you. We can't do something this big without the Mutant Hunters noticing and getting pointlessly suspicious. To prevent this, you must visit commander Herman, inform him of our plan, and, if necessary, assure him that will we hand over every donor showing signs of mutations. Then the Hunters won't have any reason to interfere.}
{5300}{}{太好了，这是提供信息的500个瓶盖。但首先，我有另一项任务给你。我们不可能做出这么大的事而不引起变种猎人的注意和毫无意义的怀疑。为了防止这种情况发生，你必须去见赫尔曼指挥官，告诉他我们的计划，如果有必要，向他保证我们会交出所有有变异迹象的捐献者。那猎人就没有任何理由干涉了。}
#{5301}{}{Excellent, here's 500 caps for the information. But first, I have another task for you. As you're no doubt aware, we can't do something this big without the Mutant Hunters noticing and getting pointlessly suspicious. To prevent this, you must visit commander Herman, inform him of our plan, and, if necessary, assure him that will we hand over every donor showing signs of mutations. Then the Hunters won't have any reason to interfere.}
{5301}{}{太好了，这是提供信息的500个瓶盖。但首先，我有另一个任务给你。我们不可能做出这么大的事而不引起变种猎人的注意和毫无意义的怀疑。为了防止这种情况发生，你必须去见赫尔曼指挥官，告诉他我们的计划，如果有必要，向他保证我们会交出所有有变异迹象的捐献者。那猎人就没有理由干涉了。}
#{5302}{}{OK.}
{5302}{}{OK。}
#{5350}{}{Excellent, here's 500 caps for the information. I'll inform the Hunters of our plan to avoid provoking any baseless suspicions and give them no reason to interfere. To maintain good relations, it will be necessary to promise them that we will hand over every donor showing signs of mutation, but I'm sure they'll be satisfied with just the few of them with the most apparent signs. There's no reason for you to stay here, go and join our mercenaries and catch as many tribals as you can.}
{5350}{}{太好了，这是提供信息的500个瓶盖。我会把我们的计划告诉猎人们以免引起毫无根据的怀疑，也不会让他们有任何理由干涉。为了保持良好的关系，我们有必要向他们承诺我们会交出所有有变异迹象的捐赠者，但我相信他们会满足于其中少数有明显变异迹象的人。你没有理由留在这里，去加入我们的雇佣兵，尽你所能抓住更多的部落。}
#{5351}{}{Excellent, here's 500 caps for the information. I'll inform the Hunters of our plan to avoid provoking any baseless suspicions and give them no reason to interfere. To maintain good relations, it will be necessary to promise them that we will hand over every donor showing signs of mutation, but I'm sure they'll be satisfied with just the few of them with the most apparent signs. There's no reason for you to stay here, go and join our mercenaries and catch as many tribals as you can.}
{5351}{}{太好了，这是提供信息的500个瓶盖。我会把我们的计划告诉猎人们以免引起毫无根据的怀疑，也不会让他们有任何理由干涉。为了保持良好的关系，我们有必要向他们承诺我们会交出所有有变异迹象的捐赠者，但我相信他们会满足于其中少数有明显变异迹象的人。你没有理由留在这里，去加入我们的雇佣兵，尽你所能抓住更多的部落。}
#{5352}{}{Excellent, here's 500 caps for the information. Don't worry, I'll inform your commander Herman to avoid provoking any baseless suspicions and give him no reason to interfere. There's no reason for you to stay here, go and join our mercenaries and catch as many tribals as you can.}
{5352}{}{太好了，这是提供信息的500个瓶盖。别担心，我会通知你的指挥官赫尔曼，避免引起任何毫无根据的怀疑，也不给他任何干涉的理由。你没有理由留在这里，去加入我们的雇佣军，尽可能多地抓捕部落。}
#{5353}{}{Excellent, here's 500 caps for the information. Don't worry, I'll inform your commander Herman to avoid provoking any baseless suspicions and give him no reason to interfere. There's no reason for you to stay here, go and join our mercenaries and catch as many tribals as you can.}
{5353}{}{太好了，这是提供信息的500个瓶盖。别担心，我会通知你的指挥官赫尔曼，避免引起任何毫无根据的怀疑，也不给他任何干涉的理由。你没有理由留在这里，去加入我们的雇佣军，尽可能多地抓捕部落。}
#{5354}{}{OK.}
{5354}{}{OK。}
#{5400}{}{Excellent, here's 500 caps for the information. I've been informed that commander Herman is dead, meaning that the Hunters have their hands full with their own problems and won't interfere with our plan. There's no reason for you to stay here, go and join our mercenaries and catch as many tribals as you can.}
{5400}{}{太好了，这是提供信息的500个瓶盖。我听说赫尔曼指挥官已经死了，这意味着猎人们忙于解决自己的问题，不会干涉我们的计划。你没有理由留在这里，去加入我们的雇佣军，尽可能多地抓捕部落。}
#{5401}{}{Excellent, here's 500 caps for the information. I've been informed that commander Herman is dead, meaning that the Hunters have their hands full with their own problems and won't interfere with our plan. There's no reason for you to stay here, go and join our mercenaries and catch as many tribals as you can.}
{5401}{}{太好了，这是提供信息的500个瓶盖。我听说赫尔曼指挥官已经死了，这意味着猎人们忙于解决自己的问题，不会干涉我们的计划。你没有理由留在这里，去加入我们的雇佣军，尽可能多地抓捕部落。}
#{5402}{}{Excellent, here's 500 caps for the information. I've been informed that commander Herman is dead. How unfortunate, we can only hope that it won't arouse any baseless suspicions that would cause you Hunters to interfere with our plan. There's no reason for you to stay here, go and join our mercenaries and catch as many tribals as you can.}
{5402}{}{太好了，这是提供信息的500个瓶盖。我听说赫尔曼指挥官死了。多么不幸，我们只能希望它不会引起任何毫无根据的怀疑，从而导致你们猎人干扰我们的计划。你没有理由留在这里，去加入我们的雇佣军，尽可能多地抓捕部落。}
#{5403}{}{Excellent, here's 500 caps for the information. I've been informed that commander Herman is dead. How unfortunate, we can only hope that it won't arouse any baseless suspicions that would cause you Hunters to interfere with our plan. There's no reason for you to stay here, go and join our mercenaries and catch as many tribals as you can.}
{5403}{}{太好了，这是提供信息的500个瓶盖。我听说赫尔曼指挥官死了。多么不幸，我们只能希望它不会引起任何毫无根据的怀疑，从而导致你们猎人干扰我们的计划。你没有理由留在这里，去加入我们的雇佣军，尽可能多地抓捕部落。}
#{5404}{}{OK.}
{5404}{}{OK。}
#{5450}{}{Very well. Given the fact that Hunters are our customers, and we'd like things to stay that way, it will be more beneficial to sacrifice a few donors with the most apparent signs of mutation in order to maintain good relations. There's no reason for you to stay here, go and join our mercenaries and catch as many tribals as you can.}
{5450}{}{很好。鉴于猎人是我们的客户，而且我们希望保持这种关系，牺牲一些突变最明显的捐献者来维持良好关系会更有好处。你没有理由留在这里，去加入我们的雇佣兵，尽可能多地抓捕部落。}
#{5451}{}{Very well. Given the fact that you Hunters are our customers, and we'd like things to stay that way, it will be more beneficial to agree to Herman's conditions. There's no reason for you to stay here, go and join our mercenaries and catch as many tribals as you can.}
{5451}{}{很好。考虑到你们猎人是我们的客户，我们希望保持这种关系，接受赫尔曼的条件会更有利。你没有理由留在这里，去加入我们的雇佣兵，尽可能多地抓捕部落。}
#{5452}{}{OK.}
{5452}{}{OK。}
#{5453}{}{I've no desire to take part in that until you pay me for negotiating with Herman.}
{5453}{}{除非你付钱让我和赫尔曼谈判，否则我是不会参与的。}
#{5500}{}{It's not a complicated procedure, and the convalescence period is only one week. What raises the price to 15000 caps is a special protective alloy containing biological elements that we will implant under your skin. You will thus gain increased endurance without the implant being visible or discernible by touch. We will also strengthen the bones that need it, certainly coxae and sacrum at least. Finally, we'll transplant you a new heart for a complete increase in endurance and stamina. And, of course, I have not forgotten about your fifty percent discount on this procedure.}
{5500}{}{手术并不复杂，恢复期只有一周。将价格提高到15000个瓶盖的是一种特殊的保护合金，其中含有生物元素，我们将植入您的皮肤下。因此，您将获得更高的耐力，而植入物不会被触摸或者看到而识别出。我们还会加强需要它的骨骼，至少是髋骨和骶骨。最后，我们将为您移植一颗新的心脏，以完全提高您的力量和耐力。当然，我也没有忘记这个手术有五折优惠。}
#{5501}{}{I'm in, here's 7500 caps.}
{5501}{}{我同意，这是7500个瓶盖。}
#{5502}{}{Tell me about the procedures.}
{5502}{}{告诉我手术过程。}
#{5503}{}{Not interested. Bye.}
{5503}{}{不感兴趣。再见。}
#{5504}{}{I don't have that much. Bye.}
{5504}{}{我没那么多钱。再见。}
#{5550}{}{Do you think we accept every self-taught quack who's greatest skill is using a stimpak? Certainly not. But if you can fight, as well as suppress your urge to kill, you could ask Paul. He told me he still wanted to take on a few more people. You'll find him in the second building of our hospital.}
{5550}{}{你认为我们接受每一个自学成才的庸医，他们最擅长的技能就是使用刺激药吗？当然不是。但如果你能战斗，也能抑制你杀人的欲望，你可以问问保罗。他告诉我他还想再雇几个人。你会在我们医院的二楼找到他的。}
#{5551}{}{What kind of a work did you have in mind?}
{5551}{}{你想做什么样的工作？}
#{5552}{}{OK, thanks.}
{5552}{}{OK，谢谢。}
#{5600}{}{We call it 'donor collecting'. As I've said, if you want to know more, you'll have to ask Paul, I won't waste my time on that. I only care about the donors when I need them for surgery or research, and Paul makes sure we always have enough of them.}
{5600}{}{我们称之为“捐献者收集”。就像我说的，如果你想知道更多，你得去问保罗，我不会在这上面浪费时间。我只关心那些需要手术或研究的捐赠者，保罗确保我们总是有足够的捐赠者。}
#{5601}{}{OK.}
{5601}{}{OK。}
#{5650}{}{Ask Paul. He told me he still wanted to take on a few more people. You'll find him in the second building of our hospital.}
{5650}{}{问保罗。他告诉我他还想再雇几个人。你可以在我们医院的二楼找到他。}
#{5651}{}{OK, but, please, tell me about the procedures again.}
{5651}{}{好的，但是，请再告诉我一次手术过程。}
#{5652}{}{OK.}
{5652}{}{OK。}
#{5700}{}{Greetings. Paul mentioned that you were doing rather well in donor collecting. But I have different work for you. The local tribals have been searching for their missing hunters and your last raid seems to have been the proverbial last straw. They're planning something. I want you to find out what it is and how much do they know.}
{5700}{}{哈喽。保罗提到你在收集捐赠者方面做得很好。但我有不同的工作给你。当地部落一直在寻找失踪的猎人，而你的最后一次突袭似乎是众所周知的最后一根稻草。他们在计划什么。我要你查出是什么，他们知道多少。}
#{5701}{}{Greetings. Paul mentioned that you were doing rather well in donor collecting. But I have different work for you. The local tribals have been searching for their missing hunters and your last raid seems to have been the proverbial last straw. They're planning something. I want you to find out what it is and how much do they know.}
{5701}{}{哈喽。保罗提到你在收集捐赠者方面做得很好。但我有不同的工作给你。当地部落一直在寻找失踪的猎人，而你的最后一次突袭似乎是众所周知的最后一根稻草。他们在计划什么。我要你查出是什么，他们知道多少。}
#{5702}{}{Why me?}
{5702}{}{为什么是我？}
#{5750}{}{You are the most suitable candidate. You're working for us, and, as I've said, you're doing a good job, meaning that I can hopefully rely on you. But, you've been here the shortest time from all the mercenaries and no one will associate you with us, meaning that you will be able to avoid unnecessary suspicion. You should have no problems getting the information we need from the tribals.}
{5750}{}{你是最合适的人选。你在为我们工作，正如我所说，你做得很好，这意味着我可以指望你。但是，在所有雇佣兵中，你来这里的时间最短，没有人会把你和我们联系起来，这意味着你将能够避免不必要的怀疑。从部落那里得到我们需要的信息应该不成问题。}
#{5751}{}{You are the most suitable candidate. You're working for us, and, as I've said, you're doing a good job, meaning that I can hopefully rely on you. But, you've been here the shortest time from all the mercenaries and no one will associate you with us, meaning that you will be able to avoid unnecessary suspicion. You should have no problems getting the information we need from the tribals.}
{5751}{}{你是最合适的人选。你在为我们工作，正如我所说，你做得很好，这意味着我可以指望你。但是，在所有雇佣兵中，你来这里的时间最短，没有人会把你和我们联系起来，这意味着你将能够避免不必要的怀疑。从部落那里得到我们需要的信息应该不成问题。}
#{5752}{}{OK. I'll see what I can do.}
{5752}{}{OK，我看看我能做什么。}
#{5800}{}{The fact that the Hunters trust us with this is very good for our hospital, as it allows us to safely use all the donors. Rest assured that you will get an appropriate bonus after everything's over. There's no reason for you to stay here, go and join our mercenaries and catch as many tribals as you can.}
{5800}{}{事实上，猎人们信任我们，这对我们医院来说是件好事，因为这样我们就可以安全地使用所有的捐赠者。放心，一切结束后你会得到适当的奖金。你没有理由留在这里，去加入我们的雇佣兵，尽可能多地抓捕部落。}
#{5801}{}{The fact that the Hunters trust us with this is very good for our hospital, as it allows us to safely use all the donors. Rest assured that you will get an appropriate bonus after everything's over. There's no reason for you to stay here, go and join our mercenaries and catch as many tribals as you can.}
{5801}{}{事实上，猎人们信任我们，这对我们医院来说是件好事，因为这样我们就可以安全地使用所有的捐赠者。放心，一切结束后你会得到适当的奖金。你没有理由留在这里，去加入我们的雇佣兵，尽可能多地抓捕部落。}
#{5802}{}{The fact that commander Herman trusts us with this is very good for our hospital. I won't go into details, I'm sure that, considering your position, you have no desire to hear them. But, you can rest assured that you will get an appropriate bonus after everything's over. There's no reason for you to stay here, go and join our mercenaries and catch as many tribals as you can.}
{5802}{}{赫尔曼指挥官信任我们，这对我们医院有好处。我不想说太多细节，我相信，考虑到你的处境，你不会想听的。但是，你可以放心，一切结束后你会得到适当的奖金。你没有理由留在这里，去加入我们的雇佣兵，尽可能多地抓捕部落。}
#{5803}{}{The fact that commander Herman trusts us with this is very good for our hospital. I won't go into details, I'm sure that, considering your position, you have no desire to hear them. But, you can rest assured that you will get an appropriate bonus after everything's over. There's no reason for you to stay here, go and join our mercenaries and catch as many tribals as you can.}
{5803}{}{赫尔曼指挥官信任我们，这对我们医院有好处。我不想说太多细节，我相信，考虑到你的处境，你不会想听的。但是，你可以放心，一切结束后你会得到适当的奖金。你没有理由留在这里，去加入我们的雇佣兵，尽可能多地抓捕部落。}
#{5804}{}{OK.}
{5804}{}{OK。}
#{5805}{}{I've no desire to take part in that until you pay me for negotiating with Herman.}
{5805}{}{除非你付钱让我和赫尔曼谈判，否则我是不会参与的。}
#{5806}{}{Are you trying to tell me you want to use the mutated bodies as well?! Commander Herman must know about this.}
{5806}{}{你是想告诉我你也想用变异的身体吗？！赫尔曼指挥官一定知道这件事。}
#{5850}{}{I prefer not to owe anyone money - here's 500 caps, but I'm afraid that we won't be making use of your services anymore because of your sudden unprofessional behavior.}
{5850}{}{我不想欠任何人钱-这里有500个瓶盖，但我们恐怕不会再使用你的服务了，因为你突然的不专业行为。}
#{5851}{}{As you wish. Bye.}
{5851}{}{如你所愿。再见。}
#{5900}{}{I think you still have some urgent work to do. Or has something changed?}
{5900}{}{我认为你还有一些紧急的工作要做。还是有什么变化了？}
#{5901}{}{I told the tribals the truth! Now, they know that you were behind the disappearance of their people.}
{5901}{}{我把真相告诉了部落！现在，他们知道你是他们族人失踪的幕后黑手。}
#{5902}{}{I told the tribals the truth! Now, they know that you were behind the disappearance of their people.}
{5902}{}{我把真相告诉了部落！现在，他们知道你是他们族人失踪的幕后黑手。}
#{5903}{}{The tribals know that someone from the city is behind the disappearance of their hunters, and they're planning to fight them when they find out who it is.}
{5903}{}{部落知道城里有人是他们猎人失踪的幕后主使，他们计划查出凶手后与之决一死战。}
#{5904}{}{I've informed Herman. He expects you to hand over every tribal showing any signs of mutation.}
{5904}{}{我已经通知赫尔曼了。他希望你交出所有有变异迹象的部落成员。}
#{5905}{}{I've informed Herman. I convinced him that you'll safely get rid of the mutant bodies on your own.}
{5905}{}{我已经通知赫尔曼了，我说服他你可以自己安全地处理掉变异体。}
#{5906}{}{I've informed Herman. He expects you to hand over every tribal showing any signs of mutation.}
{5906}{}{我已经通知赫尔曼了。他希望你交出所有有变异迹象的部落成员。}
#{5907}{}{I've informed Herman. I convinced him that you'll safely get rid of the mutant bodies on your own.}
{5907}{}{我已经通知赫尔曼了，我说服他你可以自己安全地处理掉变异体。}
#{5908}{}{I need healing first, my...}
{5908}{}{我需要先治愈，我的...}
#{5909}{}{I need healing first.}
{5909}{}{我需要先治愈。}
#{5910}{}{Not yet, my companion requires healing first.}
{5910}{}{还不行，我的同伴需要治疗。}
#{5911}{}{I wanted to talk about this little problem I have first...}
{5911}{}{我想先谈谈我的这个小问题...}
#{5912}{}{Not yet. I wanted to know what else can this hospital offer me besides healing.}
{5912}{}{还没有。我想知道这家医院除了治疗之外还能给我提供什么。}
#{5913}{}{Tell me about the procedures.}
{5913}{}{告诉我手术过程。}
#{5914}{}{Not yet. But I might have a suitable donor for sale.}
{5914}{}{还没有。但我可能有合适的捐赠者出售。}
#{5915}{}{Did you know that doctor Yaotzin from the Mutant Hunters doesn't think too highly of your hospital?}
{5915}{}{你知道变种猎人的耀津医生并不看好你的医院吗？}
#{5916}{}{I'm working on it.}
{5916}{}{我正在努力。}
#{5917}{}{Herman is dead, he won't get in the way of your plan.}
{5917}{}{赫尔曼死了，他不会妨碍你的计划。}
#{5950}{}{That is unfortunate. It seems that Paul has overestimated your abilities. Regardless, thank you for at least informing us of the attack that the tribals are no doubt planning. There might be some casualties, but... [Someone firmly grabs you from behind around your neck and plunges a syringe into your artery. You slowly lose consciousness.] You can compensate for some of them with your body. [You fall asleep, never to wake again.]}
{5950}{}{这是不幸的。保罗似乎高估了你的能力。不管怎样，谢谢你至少告诉我们部落无疑正在计划的袭击。可能会有一些伤亡，但是...[有人从你脖子后面紧紧抓住你，将注射器插入你的动脉。你会慢慢失去意识。]你可以用身体来补偿其中的一些。[你睡着了，再也醒不过来了。]}
#{5951}{}{[End.]}
{5951}{}{[结束.]}
#{6000}{}{That is unfortunate. It seems that Paul has overestimated your abilities. Regardless, thank you for at least informing us of the attack that the tribals are no doubt planning. There might be some casualties, but... [At the last moment, you notice a stocky man with a syringe trying to grab you from behind and narrowly dodge him.]}
{6000}{}{这是不幸的。保罗似乎高估了你的能力。不管怎样，谢谢你至少告诉我们部落无疑正在计划的袭击。可能会有一些伤亡，但是...[在最后一刻，你注意到一个拿着注射器的矮壮男人试图从后面抓住你，并勉强躲过了他。]}
#{6001}{}{[Defend yourself.]}
{6001}{}{[保护自己。]}
#{6050}{}{That is unfortunate. It seems that Paul has overestimated your abilities. Regardless, thank you for at least informing us of the attack that the tribals are no doubt planning. There might be some casualties, but... [Someone firmly grabs you from behind around your neck and plunges a syringe into your artery. You slowly lose consciousness.] You can compensate for some of them with your body. [You fall asleep, never to wake again.]}
{6050}{}{这是不幸的。保罗似乎高估了你的能力。不管怎样，谢谢你至少告诉我们部落无疑正在计划的袭击。可能会有一些伤亡，但是...[有人从你脖子后面紧紧抓住你，将注射器插入你的动脉。你会慢慢失去意识。]你可以用身体来补偿其中的一些。[你睡着了，再也醒不过来了。]}
#{6100}{}{That is unfortunate. It seems that Paul has overestimated your abilities. Regardless, thank you for at least informing us of the attack that the tribals are no doubt planning. There might be some casualties, but... [At the last moment, you notice a stocky man with a syringe trying to grab you from behind and narrowly dodge him.]}
{6100}{}{这是不幸的。保罗似乎高估了你的能力。不管怎样，谢谢你至少告诉我们部落无疑正在计划的袭击。可能会有一些伤亡，但是...[在最后一刻，你注意到一个拿着注射器的矮壮男人试图从后面抓住你，并勉强躲过了他。]}
#{6150}{}{I believe I'll have to tell Paul to be more careful about strangers snooping around this place. I can assure you it's nothing personal. Our mercenaries catch tribals in the wasteland when they go hunting. They are among our regular organ donors. You can ask Paul if you want to know more, he's in charge of donor collecting.}
{6150}{}{我想我必须告诉保罗，要更加小心陌生人窥探这个地方。我可以向你保证这不是针对你个人的。我们的雇佣兵在荒原上猎捕部落。他们是我们的器官捐献者。如果你想知道更多，你可以去问保罗，他负责收集捐献者。}
#{6151}{}{So you really are behind the damn missing tribals.}
{6151}{}{所以你真的是那些失踪部落的幕后黑手。}
#{6200}{}{They are not missing at all. We made, or will make, full use of their bodies, and with far more purpose than they could've done alive. But I don't think you need to tell them about that. I have a far more lucrative offer for you.}
{6200}{}{他们根本没有失踪。我们充分利用了他们的身体，或者说将要充分利用他们的身体，而且比他们活着的时候更有意义。但我觉得你没必要告诉他们。我有个更有利可图的提议。}
#{6201}{}{What are you talking about?}
{6201}{}{你在说什么？}
#{6250}{}{I have no doubt that even they could sooner or later find out what happened to their hunters. We can't let them kill themselves by attacking our hospital. That would be too wasteful. That's why I'm planning to have Paul organize the capture of all tribals in Albuquerque. Would you be interested in helping? We will need as many people as possible to minimize donor casualties, and you could earn much more than if you warned them.}
{6250}{}{我毫不怀疑，即使是他们也迟早会发现猎人的遭遇。我们不能让他们因袭击我们的医院而死。那太浪费了。这就是为什么我计划让保罗组织抓捕阿尔伯克基所有部落的原因。你有兴趣帮忙吗？我们将需要尽可能多的人来减少捐赠者的伤亡，而且你可以赚到比你警告他们更多的钱。}
#{6251}{}{I have no doubt that even they could sooner or later find out what happened to their hunters. We can't let them kill themselves by attacking our hospital. That would be too wasteful. That's why I'm planning to have Paul organize the capture of all tribals in Albuquerque. Would you be interested in helping? We will need as many people as possible to minimize donor casualties, and you could earn much more than if you warned them.}
{6251}{}{我毫不怀疑，即使是他们也迟早会发现猎人的遭遇。我们不能让他们因袭击我们的医院而死。那太浪费了。这就是为什么我计划让保罗组织抓捕阿尔伯克基所有部落的原因。你有兴趣帮忙吗？我们将需要尽可能多的人来减少捐赠者的伤亡，而且你可以赚到比你警告他们更多的钱。}
#{6252}{}{Hot damn, of course I'm interested!}
{6252}{}{该死，我当然感兴趣了！}
#{6253}{}{That's horrible! They must be made aware of what you're planning to do to them.}
{6253}{}{太可怕了！必须让他们知道你打算对他们做什么。}
#{6300}{}{Of course, if you see things that way, you leave me no choice but to... [Someone firmly grabs you from behind around your neck and plunges a syringe into your artery. You slowly lose consciousness.] Use your organs for the sake of someone more reasonable. [You fall asleep, never to wake again.]}
{6300}{}{当然，如果你这么想，我别无选择，只能… [有人从你脖子后面紧紧抓住你，把注射器插进你的动脉。你会慢慢失去意识。]为了一个更理智的人使用你的器官。[你睡着了，再也醒不过来了。。]}
#{6301}{}{[End.]}
{6301}{}{[结束]}
#{6350}{}{Of course, if you see things that way, you leave me no choice but to... [At the last moment, you notice a stocky man with a syringe trying to grab you from behind and narrowly dodge him.]}
{6350}{}{当然，如果你这么想，我别无选择，只能…[在最后一刻，你注意到一个拿着注射器的矮壮男人试图从后面抓住你，并勉强躲过了他。]}
#{6351}{}{Of course, if you see things that way, you leave me no choice but to... [At the last moment, you notice a stocky man with a syringe trying to grab you from behind and narrowly dodge him.]}
{6351}{}{当然，如果你这么想，我别无选择，只能…[在最后一刻，你注意到一个拿着注射器的矮壮男人试图从后面抓住你，并勉强躲过了他。]}
#{6352}{}{[Defend yourself.]}
{6352}{}{[保护自己。]}
#{6360}{}{I didn't expect you to show your face here again. I'm sure you know that the tribals attacked us and I have no doubt that you were the reason why. You were supposed to find out how much they know, and not spill everything about their missing people. Many potential donors were lost because of you. It is unfortunate, but... [Someone firmly grabs you from behind around your neck and plunges a syringe into your artery. You slowly lose consciousness.] I'm sure we'll be able to use your body as a small compensation. [You fall asleep, never to wake again.]}
{6360}{}{我没想到你会再次出现在这里。我相信你知道部落袭击了我们，我毫不怀疑就是因为你的原因。你应该查出他们知道多少，而不是泄露他们失踪人口的全部信息。因为你，很多潜在的捐赠者都流失了。很不幸，但是... [有人从你的脖子后面紧紧抓住你，然后把注射器插入你的动脉。你会慢慢失去意识。]我相信我们可以用你的身体作为小小的补偿。[你睡着了，再也醒不过来了。]}
#{6361}{}{I didn't expect you to show your face here again. I'm sure you know that the tribals attacked us and I have no doubt that you were the reason why. You were supposed to find out how much they know, and not spill everything about their missing people. Many potential donors were lost because of you. It is unfortunate, but... [Someone firmly grabs you from behind around your neck and plunges a syringe into your artery. You slowly lose consciousness.] I'm sure we'll be able to use your body as a small compensation. [You fall asleep, never to wake again.]}
{6361}{}{我没想到你会再次出现在这里。我相信你知道部落袭击了我们，我毫不怀疑就是因为你的原因。你应该查出他们知道多少，而不是泄露他们失踪人口的全部信息。因为你，很多潜在的捐赠者都流失了。很不幸，但是... [有人从你的脖子后面紧紧抓住你，然后把注射器插入你的动脉。你会慢慢失去意识。]我相信我们可以用你的身体作为小小的补偿。[你睡着了，再也醒不过来了。]}
#{6362}{}{[End.]}
{6362}{}{[结束。]}
#{6370}{}{I didn't expect you to show your face here again. I'm sure you know that the tribals attacked us and I have no doubt that you were the reason why. You were supposed to find out how much they know, and not spill everything about their missing people. Many potential donors were lost because of you. It is unfortunate, but... [At the last moment, you notice a stocky man with a syringe trying to grab you from behind and narrowly dodge him.]}
{6370}{}{我没想到你会再次出现在这里。我相信你知道部落袭击了我们，我毫不怀疑就是因为你的原因。你应该查出他们知道多少，而不是泄露他们失踪人口的全部信息。因为你，很多潜在的捐赠者都流失了。很不幸，但是... [在最后一刻，你注意到一个拿着注射器的矮壮男人试图从后面抓住你，并勉强躲过了他。]}
#{6371}{}{I didn't expect you to show your face here again. I'm sure you know that the tribals attacked us and I have no doubt that you were the reason why. You were supposed to find out how much they know, and not spill everything about their missing people. Many potential donors were lost because of you. It is unfortunate, but... [At the last moment, you notice a stocky man with a syringe trying to grab you from behind and narrowly dodge him.]}
{6371}{}{我没想到你会再次出现在这里。我相信你知道部落袭击了我们，我毫不怀疑就是因为你的原因。你应该查出他们知道多少，而不是泄露他们失踪人口的全部信息。因为你，很多潜在的捐赠者都流失了。很不幸，但是... [在最后一刻，你注意到一个拿着注射器的矮壮男人试图从后面抓住你，并勉强躲过了他。]}
{6372}{}{[保护自己。]}
#{6380}{}{Yes, it was the local tribals. Our mercenaries were forced to kill the attackers to defend our lives. A tragic waste of resources, most of those tribals could've served as valuable organ donors. What a terrible waste. [He shakes his head over such great injustice.]}
{6380}{}{是的，是当地的部落。我们的雇佣兵被迫杀死袭击者以保卫我们的生命。这是一种悲惨的资源浪费，这些部落中的大多数人本可以成为有价值的器官捐赠者。多么可怕的浪费。[他对如此巨大的不公摇头。]}
#{6381}{}{Yes, very tragic. Goodbye, doctor.}
{6381}{}{是的，非常悲惨。再见，医生。}
#{6382}{}{You're a monster, doctor. You don't deserve to live. Time to finish what the tribals started.}
{6382}{}{你是个怪物，医生。你不配活下去。是时候完成部落的任务了。}
#{6400}{}{Certainly, the patient will be well taken care of. But there is one more thing - I prefer not to talk about financial matters in advance, however, since you are new here, I must warn you that our services are not cheap. Quality service demands adequate pay. If you don't have enough caps, it would be best if you left.}
{6400}{}{当然，病人会得到很好的照顾。但是还有一件事-我不想提前谈论财务问题，但是，既然你是新来的，我必须提醒你，我们的服务并不便宜。优质的服务需要足够的报酬。如果你没有足够的瓶盖，你最好离开。}
#{6401}{}{How much will the treatment cost?}
{6401}{}{治疗费用是多少？}
#{6402}{}{Caps won't be a problem, go ahead and do your job.}
{6402}{}{瓶盖不是问题，继续做你的工作吧。}
#{6403}{}{You wouldn't heal anyone for free even if they were dying?!}
{6403}{}{即使病人快死了你也不会免费给他们治病吗？！}
#{6404}{}{If you won't heal for free, I'll gut you so that none of your colleagues will be able to piece your body back together!}
{6404}{}{如果你不愿意免费治疗，我就把你开膛破肚、大卸八块，这样你的同事就没人能把你的身体拼回去了！}
#{6405}{}{No healing then, I don't have caps to spare.}
{6405}{}{那就不治疗了，我没有多余的瓶盖。}
#{6450}{}{The price is determined by the medical procedures that we will need to perform, and we won't know those until the examination is done.}
{6450}{}{价格是由我们需要执行的医疗手术决定的，在检查完成之前我们不会知道。}
#{6500}{}{Dear Sir, what we do here is not some shamanistic pseudo-medicine, but serious, brilliant medicine. It's not easy to get all the necessary medical supplies, substances and personnel, and they all cost a lot of caps.}
{6500}{}{尊敬的先生，我们在这里所做的不是一些萨满教的伪医学，而是严肃的、出色的医学。获得所有必要的医疗用品、物质和人员并不容易，而且这些都要花费很多瓶盖。}
#{6550}{}{Of course, who should we take care of specifically?}
{6550}{}{当然，我们应该具体照顾谁？}
#{6551}{}{Gabriel needs healing.}
{6551}{}{加百利需要治疗。}
#{6552}{}{Keri needs healing.}
{6552}{}{凯莉需要治疗。}
#{6553}{}{Lystra needs healing.}
{6553}{}{莱斯特拉需要治疗。}
#{6555}{}{Will you treat a dog?}
{6555}{}{你会给狗治病吗？}
#{6556}{}{I'd rather you don't treat anyone.}
{6556}{}{我宁愿你不要治疗任何人。}
#{6600}{}{Certainly, the patient will be well taken care of. But there is one more thing - I prefer not to talk about financial matters in advance, however, since you are new here, I must warn you that our services are not cheap. Quality service demands adequate pay. If you don't have enough caps, it would be best if you left.}
{6600}{}{当然，病人会得到很好的照顾。但是还有一件事-我不想提前谈论财务问题，但是，既然你是新来的，我必须提醒你，我们的服务并不便宜。优质的服务需要足够的报酬。如果你没有足够的瓶盖，你最好离开。}
#{6650}{}{The price is determined by the medical procedures that we will need to perform, and we won't know those until the examination is done.}
{6650}{}{价格是由我们需要执行的医疗手术决定的，在检查完成之前我们不会知道。}
#{6700}{}{Dear Miss, what we do here is not some shamanistic pseudo-medicine, but serious, brilliant medicine. It's not easy to get all the necessary medical supplies, substances and personnel, and they all cost a lot of caps.}
{6700}{}{亲爱的小姐，我们在这里所做的不是一些萨满教的伪医学，而是严肃的、出色的医学。获得所有必要的医疗用品、物质和人员并不容易，而且这些都要花费很多瓶盖。}
#{6750}{}{Wait here. [Falber starts to take him into another hospital building.] Don't worry, he'll get only the best service.}
{6750}{}{在这儿等着。[福伯开始把他带往另一座医院大楼里。]别担心，他只会得到最好的服务。}
#{6751}{}{[Wait.]}
{6751}{}{[等等。]}
#{6800}{}{[Falber comes back alone.] It was nothing serious; your friend had only minor injuries. He will come back as soon as you pay 100 caps.}
{6800}{}{[福伯独自回来了。]没什么大不了的，你朋友只是受了点轻伤。他会回来的，你只要支付100个瓶盖就行了。}
#{6801}{}{Sure, here you go.}
{6801}{}{当然，给你。}
#{6802}{}{I don't have that much.}
{6802}{}{我没那么多钱。}
#{6850}{}{[A man brings him back, healthy.] Everything went smoothly, and both sides are happy. That's how good business is done.}
{6850}{}{[一个男人把他带回来，身体健康。]一切都进行得很顺利，双方都很高兴。生意就是这样做的。}
#{6851}{}{Certainly. Farewell.}
{6851}{}{当然。再见。}
#{6900}{}{In that case, we'll take the body of your friend as compensation. I'm sure that someone who can pay will make better use of one of his organs.}
{6900}{}{这样的话，我们就把你朋友的尸体当做补偿。我相信有钱人会更好地利用他的器官。}
#{6901}{}{Are you serious?!}
{6901}{}{你说真的吗？！}
#{6902}{}{Keep him then, see if I care.}
{6902}{}{那就留着他，看我在不在乎。}
#{6950}{}{I'm completely serious. I warned you that we cannot offer quality service for free.}
{6950}{}{我完全是认真的。我警告过你，我们不可能免费提供优质服务。}
#{6951}{}{Can't I pay you in some other way? Or just wait until I get the caps.}
{6951}{}{我不能用其他方式付你钱吗？或者等我拿到瓶盖再说。}
#{6952}{}{I'll kill every last one of you if you don't bring him back right now!}
{6952}{}{如果你们不马上把他带回来我就把你们都杀了！}
#{6953}{}{Goddammit! Like hell I'm sending anyone to a doctor ever again...}
{6953}{}{该死的！我不会再让任何人去看医生了…}
#{7000}{}{This isn't a hotel where he could sleep until you get the money. This is a hospital; we'll use his organs as soon as we can. If you don't have enough to pay immediately then we have nothing else to discuss.}
{7000}{}{在你拿到钱之前他可不能在这里过夜。这是一家医院，我们会尽快使用他的器官。如果你没有足够的钱立即支付，那我们就没什么好谈的了。}
#{7050}{}{[Falber comes back alone.] Your friend had mostly moderate injuries. He will come back as soon as you pay 200 caps.}
{7050}{}{[福伯一个人回来了。]你的朋友伤得一般。只要你付200瓶盖，他就会回来了。}
#{7100}{}{[Falber comes back alone.] Your friend had a few broken bones and other serious injuries. He will come back as soon as you pay 300 caps.}
{7100}{}{[福伯一个人回来了。]你的朋友有几处骨折和其他严重的伤。只要你付300瓶盖，他就会回来了。}
#{7150}{}{Wait here. [Falber starts to take her to another hospital building.] Don't worry, she'll get only the best service.}
{7150}{}{在这里等着。[福伯开始带她去另一栋医院大楼。]别担心，她只会得到最好的服务。}
#{7200}{}{[Falber comes back alone.] It was nothing serious; your friend had only minor injuries. She will come back as soon as you pay 100 caps.}
{7200}{}{[福伯一个人回来了。]没什么大不了的，你朋友只是受了点轻伤。只要你付100瓶盖，她就会回来了。}
#{7250}{}{[A man brings her back, healthy.] Everything went smoothly, and both sides are happy. That's how good business is done.}
{7250}{}{[一个男人把她带回来，身体健康。]一切都很顺利，双方都很高兴。生意就是这样做的。}
#{7300}{}{In that case, we'll take the body of your friend as compensation. I'm sure that someone who can pay will make better use of one of her organs.}
{7300}{}{那样的话，我们就把你朋友的尸体作为补偿。我敢肯定，有能力付钱的人会更好地利用她的一个器官。}
#{7302}{}{Keep her then, see if I care.}
{7302}{}{那就留着她，看我在不在乎。}
#{7350}{}{I'm completely serious. I warned you that we cannot offer quality service for free.}
{7350}{}{我是认真的。我警告过你，我们不能免费提供优质的服务。}
#{7352}{}{I'll kill every last one of you if you don't bring her back right now!}
{7352}{}{如果你们现在不把她带回来，我就把你们都杀了！}
#{7400}{}{This isn't a hotel where she could sleep until you get the money. This is a hospital; we'll use her organs as soon as we can. If you don't have enough to pay immediately then we have nothing else to discuss.}
{7400}{}{在你拿到钱之前她可不能在这里过夜。这是一家医院，我们会尽快使用她的器官。如果你没有足够的钱立即支付，那我们就没什么好谈的了。}
#{7450}{}{[Falber comes back alone.] Your friend had mostly moderate injuries. She will come back as soon as you pay 200 caps.}
{7450}{}{[福伯一个人回来了。]你的朋友伤得一般。只要你付200瓶盖，她就会回来了。}
#{7500}{}{[Falber comes back alone.] Your friend had a few broken bones and other serious injuries. She will come back as soon as you pay 300 caps.}
{7500}{}{[福伯一个人回来了。]你的朋友有几处骨折和其他严重的伤。只要你付300瓶盖，她就会回来了。}
#{7550}{}{That filthy animal shouldn't even be here, let alone receive our services.}
{7550}{}{那只肮脏的动物根本不应该在这里，更不用说接受我们的服务了。}
#{7551}{}{Take care of Gabriel then.}
{7551}{}{那就照顾加百利吧。}
#{7552}{}{Take care of Keri then.}
{7552}{}{那就照顾好凯莉。}
#{7553}{}{Take care of Lystra then.}
{7553}{}{那就照顾好莱斯特拉吧。}
#{7555}{}{Nothing then.}
{7555}{}{那就没什么了。}
#{7600}{}{I warned you that I don't want to get in trouble with the Hunters by healing mutants. But if you insist on using our services that much... [Someone firmly grabs you from behind around your neck and plunges a syringe into your artery. You slowly lose consciousness.] We'll use your healthy organs at least. Don't worry, we'll make sure the Hunters won't find out. [You fall asleep, never to wake again.]}
{7600}{}{我警告过你，我不想因为治疗变种人惹上猎人的麻烦。但如果你坚持使用我们的服务…[有人从脖子后面紧紧抓住你，把注射器插进你的动脉。你慢慢失去意识。]我们至少会用你健康的器官。别担心，我们不会让猎人发现的。[你睡着了，再也不会醒来。]}
#{7650}{}{I warned you that I don't want to get in trouble with the Hunters by healing mutants. But if you insist on using our services that much... [At the last moment, you notice a stocky man with a syringe trying to grab you from behind and narrowly dodge him.]}
{7650}{}{我警告过你，我不想因为治疗变种人惹上猎人的麻烦。但如果你坚持使用我们的服务…[在最后一刻，你注意到一个拿着注射器的矮壮男人试图从后面抓住你，并勉强躲过了他。]}
#{7700}{}{I warned you that I don't want to get in trouble with the Hunters by healing mutants. But if you insist on using our services that much... [At the last moment, you notice a stocky man with a syringe trying to grab you from behind and narrowly dodge him.]}
{7700}{}{我警告过你，我不想因为治疗变种人惹上猎人的麻烦。但如果你坚持使用我们的服务…[在最后一刻，你注意到一个拿着注射器的矮壮男人试图从后面抓住你，并勉强躲过了他。]}
#{7750}{}{Ahh, certainly. Show me, I'll take a look. [The doctor comes close to you to examine you. He starts to touch you; it tickles a bit. After a while, he pulls something out of you! You start to panic, he can't just take one of your organs, you'd miss it! Wait... It was just your pouch with caps. Uff, what a relief.]}
{7750}{}{啊，当然。让我看看，我看看。[医生走到你身边给你检查。他开始触摸你；有点痒。过了一会儿，他从你身上拔出了东西！你开始恐慌，不相信他只拿走你的一个器官，你没察觉到！等等…那只是你的带瓶盖的袋子。哎呀，真是松了一口气。]}
#{7751}{}{Uff. Eh? Hue!}
{7751}{}{咦。额？哈！}
#{7800}{}{I'm afraid you don't have enough to pay for the treatment. [He gives you back the pouch with caps.]}
{7800}{}{恐怕你没有足够的钱支付治疗费用。[他把装瓶盖的袋子还给你。]}
#{7801}{}{Grrrargh!}
{7801}{}{呃呃！}
#{7802}{}{Brbleh, bubleh.}
{7802}{}{呜呜，呜呜。}
#{7850}{}{Our medical services are of the highest level and require appropriate payment. But, if you're not going to calm down... [Someone firmly grabs you from behind around your neck and plunges a syringe into your artery. You slowly lose consciousness.] We'll use you as an organ donor for those with enough caps. [You fall asleep, never to wake again.]}
{7850}{}{我们的医疗服务是最高水平的，需要适当的报酬。但是，如果你不冷静下来... [有人从你的脖子后面紧紧抓住你，将注射器插入你的动脉。你慢慢失去意识。]我们会把你作为器官捐献者给那些有足够瓶盖的人。[你睡着了，再也没有醒来。]}
#{7900}{}{Our medical services are of the highest level and require appropriate payment. But, if you're not going to calm down... [At the last moment, you notice a stocky man with a syringe trying to grab you from behind and narrowly dodge him.]}
{7900}{}{我们的医疗服务是最高水平的，需要适当的报酬。但是，如果你不打算冷静下来...[在最后一刻，你注意到一个矮壮的男人拿着注射器试图从背后抓住你，并勉强躲开了他。]}
#{7950}{}{Our medical services are of the highest level and require appropriate payment. But, if you're not going to calm down... [At the last moment, you notice a stocky man with a syringe trying to grab you from behind and narrowly dodge him.]}
{7950}{}{我们的医疗服务是最高水平的，需要适当的报酬。但是，如果你不打算冷静下来...[在最后一刻，你注意到一个矮壮的男人拿着注射器试图从背后抓住你，并勉强躲开了他。]}
#{8000}{}{It's not standard practice, but I'm afraid that I'll have to insist on an advance payment at the highest possible rate. Which is 500 caps. [He takes 500 capes and returns the pouch.] Now lie down on this bed and I will put you to sleep for a while. When you wake up, everything will be fine. Don't worry, I'll oversee your treatment personally. [You're a bit nervous, but your worries slowly disappear along with your consciousness.]}
{8000}{}{这不是这不是惯例，但恐怕我必须坚持以尽可能高的利率收预付款。这是500瓶盖。[他拿了500瓶盖，把袋子还了回来。]现在躺在这张床上，我让你睡一会儿。当你醒来的时候，一切都会好起来的。别担心，我会亲自监督你的治疗。[你有点紧张，但你的担忧会随着你的意识慢慢消失。]}
#{8050}{}{[You awaken feeling well. The doctor helps you on your feet and, though you're still a bit dizzy, you have no trouble leaving.]}
{8050}{}{[你醒来感觉很好。医生帮助你站起来，虽然你还有点头晕，但是离开没有问题。]}
#{8051}{}{[Leave.]}
{8051}{}{[离开。]}
#{8100}{}{Back again? Certainly, if you have enough caps, our services are at your disposal as well.}
{8100}{}{又回来了？当然，如果您有足够的瓶盖，我们的服务也可供您使用。}
#{8102}{}{ hurt! [Give him your pouch with caps.]}
{8102}{}{受伤！[把你装瓶盖的袋子给他。]}
#{8150}{}{Your dog being injured may be a tragic event for you, but it's not something I'll waste my time on. The dog shouldn't even be here. Take him away.}
{8150}{}{你的狗受伤对你来说可能是一件悲惨的事情，但这不是我要浪费时间的事情。狗根本不应该在这里。把他带走。}
#{8151}{}{Blurgh.}
{8151}{}{额。}
#{8200}{}{You seem to be suffering from a serious case of dementia, but perhaps we can help you. Our greatest interest lies in improving human abilities. Not only are we constantly researching the methods to achieve this, but now we are even able to make people stronger, tougher, quicker, smarter, more perceptive, as well as more attractive, by performing minor surgical procedures and transplanting higher quality organs. A noticeable improvement by, shall we say, one degree. Since it is hard for the human body to accept and make use of organs that are too powerful, you can only undergo each of the operations once. And I'm sure I don't have to tell you that they are quite expensive.}
{8200}{}{你似乎患有严重的痴呆症，但也许我们可以帮助你。我们最大的兴趣在于提高人类的能力。我们不仅不断地研究实现这一目标的方法，而且现在我们甚至能够通过进行小型外科手术和移植更高质量的器官，使人变得更强壮、更坚强、更快、更聪明、更敏锐，以及更有吸引力。可以这么说，明显的进步了一个程度。由于人体难以接受和利用过于强大的器官，因此每种手术只能进行一次。我相信我不必告诉你，它们很贵。}
#{8201}{}{Ghaa! [Try to lift the nearest table.]}
{8201}{}{嘎！[试着把最近的桌子抬起来。]}
#{8202}{}{Hoo! [Stab yourself in your eye with your finger.]}
{8202}{}{呼！[用手指戳自己的眼睛。]}
#{8203}{}{Uaa! [Beat your chest.]}
{8203}{}{Uaa！[捶胸顿足]}
#{8204}{}{Maha! [Run through your hair.]}
{8204}{}{玛哈！[揉搓头发。]}
#{8205}{}{Ehe? [Hit your palm against your forehead.]}
{8205}{}{他呢？[用手掌拍额头。]}
#{8206}{}{Fu-fu! [Wave your hand in front of his face.]}
{8206}{}{福福！[在他面前挥手。]}
#{8207}{}{Baibai bubu.}
{8207}{}{百白不布。}
#{8250}{}{You can be even stronger if we replace a large part of your musculature. We have more than enough muscle donors and, and it's not a complicated procedure, meaning it will only cost you 10000 caps. However, a three-week convalescence period will be necessary, as you will need to get used to the new muscles.}
{8250}{}{如果我们替换掉你大部分的肌肉组织，你会变得更强壮。我们有足够多的肌肉捐献者，而且手术并不复杂，也就是说你只需要花10000瓶盖。当然，三周的恢复期是必要的，因为你需要适应新的肌肉。}
#{8251}{}{Bhough! [Give him 10000 caps.]}
{8251}{}{噢！[给他10000个瓶盖。]}
#{8257}{}{Nu... Nuh-uh.}
{8257}{}{努... 嗯。}
#{8300}{}{It is obvious you're not getting any stronger. Please, put the table down. Your musculature would be tremendously valuable had I the opportunity to transplant it to another customer.}
{8300}{}{很明显你并没有变得更强壮。请把桌子放下来。如果我有机会把你的肌肉移植到另一个客户身上，那将是非常有价值的。}
#{8306}{}{Ugh.}
{8306}{}{额。}
#{8350}{}{Improving perception involves dealing with extremely sensitive parts and thus takes several operations that need to be done with utmost care. It will cost you 20000 caps, but the convalescence period is only one week.}
{8350}{}{改善知觉涉及到处理极其敏感的部位，因此需要进行几次极其小心的手术。费用为20000瓶盖，但恢复期只有一周。}
#{8351}{}{Bhoo! [Give him 20000 caps.]}
{8351}{}{呜呜！[给他20000个瓶盖。]}
#{8400}{}{I see how your pupils react, how you perceive even the slightest sound; your perception is unique, and it will stay that way unless you poke out your eye by such gestures. How I'd love to examine such a splendid nervous system...}
{8400}{}{我看到了你瞳孔的反应，看到了你对最轻微的声音的感知；你的感知是独一无二的，它将一直保持这种状态，除非你用这种手势戳瞎了你的眼睛。我是多么想检查如此出色的神经系统…}
#{8450}{}{Increasing your endurance would take a simple operation with only a week long convalescence period, however, what raises the price to 15000 caps is a special protective alloy containing biological elements that we will implant under your skin. You will thus gain increased endurance without the implant being visible or discernible by touch.}
{8450}{}{增加你的耐力只需要一个简单的手术和一周的恢复期，然而，将价格提高到15000瓶盖的是一种含有生物元素的特殊保护合金，我们将植入你的皮肤下。因此，你将获得更高的耐力，而不会通过触摸看到或识别植入物。}
#{8451}{}{Bhoo! [Give him 15000 caps.]}
{8451}{}{呜呜！[给他15000瓶盖。]}
#{8500}{}{There is no need for such gestures, it is obvious that no surgery could improve your endurance. Oh, if only I had the fascinating opportunity to examine at least you heart on the operating table.}
{8500}{}{没有必要做这样的手势，很明显，没有手术可以提高你的耐力。要是我能有个绝妙的机会至少在手术台上检查一下你的心脏就好了。}
#{8550}{}{We can improve your appearance as well, if that is what you mean. The procedure is rather simple and involves mostly a number of aesthetic plastic surgeries and the like which I won't bother explaining to you. It will be mere 5000 caps in total, and you will be able to leave after two days.}
{8550}{}{我们也可以改善你的外表，如果你是这个意思的话。手术过程相当简单，主要包括一些美容整形手术之类的，我就不跟你解释了。总共只要5000个瓶盖，两天后你就可以离开了。}
#{8551}{}{Bhoo! [Give him 5000 caps.]}
{8551}{}{呜呜！[给他5000个瓶盖。]}
#{8600}{}{I have no doubts that even someone like you realizes how exceptionally attractive you are, seeing how the others react to you. Not even I could do much to improve your appearance. I'm not entirely sure about all the factors comprising such high charisma myself. I'd have to dissect you carefully to discover them all.}
{8600}{}{我毫不怀疑，即使是像你这样的人，看到别人对你的反应，也会意识到你是多么有吸引力。就算是我也没办法改善你的容貌。我自己也不完全确定构成如此高魅力的所有因素。我得仔细解剖你才能全部发现。}
#{8650}{}{Improving agility is not difficult, but it is quite arduous. The operations take a long time - they are conducted gradually over a period of two weeks and require two or more donors, depending on the quality of their nervous pathways. It will be 25000 caps.}
{8650}{}{提高敏捷性并不困难，但相当艰巨。手术需要很长时间，需要在两周内逐步进行，需要两个或更多的供体，这取决于他们神经通路的质量。它将要25000个瓶盖。}
#{8651}{}{Bhoo! [Give him 25000 caps.]}
{8651}{}{呜呜！[给他25000个瓶盖。]}
#{8700}{}{Yes, I can see it. Your moves are as smooth and quick as human limits allow. Operating you would be pointless, unless you wanted to become a donor.}
{8700}{}{是的，我看到了。你的动作是人类极限所允许的最快最流畅的。给你做手术毫无意义，除非你想成为捐赠者。}
#{8750}{}{The intelligence increasing surgery could help you significantly, though it is also possible that it won't make much of a difference. The result will depend on the current state of your brain, and we won't find out what it is until we open up your skull. It's also the most complex surgery that we do here. It costs 30000 caps, and involves a three week convalescence period.}
{8750}{}{提高智力的手术可能会对你有很大的帮助，尽管它也有可能不会有太大的区别。结果将取决于你的大脑目前的状态，在我们打开你的头骨之前，我们不会知道它是什么。这也是我们这里做的最复杂的手术。费用为30000瓶盖，包括3周的恢复期。}
#{8751}{}{Bhoo! [Give him 30000 caps.]}
{8751}{}{呜呜！[给他30000个瓶盖]}
#{8800}{}{Lie on the bed and I will put you to sleep. The surgery will take a few hours. [Doctor Falber injects you with something and you lose consciousness.]}
{8800}{}{躺在床上，我会让你睡着的。手术需要几个小时。[福伯医生给你注射了一些东西，你失去了意识。]}
#{8801}{}{[Fall asleep.]}
{8801}{}{[睡着了。]}
#{8850}{}{You've had a small and stunted brain since birth, and you've also suffered permanent brain damage due to serious head injuries. I've done a remarkable work on improving your condition, and there has been an improvement, though not a very noticeable one. I'm afraid that nothing else can be done with you.}
{8850}{}{你从出生起就有一个小而发育不良的大脑，而且由于严重的头部损伤，你还遭受了永久性的脑损伤。我为改善你的状况做了大量的工作，确实有了改善，虽然不是很明显。恐怕我对你无能为力了。}
#{8851}{}{You've had a small and stunted brain since birth, and you've also suffered permanent brain damage due to serious head injuries. I've done a remarkable work on improving your condition, and there has been an improvement, though not a very noticeable one. I'm afraid that nothing else can be done with you.}
{8851}{}{你从出生起就有一个小而发育不良的大脑，而且由于严重的头部损伤，你还遭受了永久性的脑损伤。我为改善你的状况做了大量的工作，确实有了改善，虽然不是很明显。恐怕我对你无能为力了。}
#{8852}{}{Buhe.}
{8852}{}{布赫。}
#{8900}{}{You've had a small and stunted brain since birth, and you've also suffered heavy brain damage due to serious head injuries. Thankfully, the damage was not as permanent as it appeared. I did a splendid job - you can now coherently express yourself. That's much more than anyone could've hoped for in your case.}
{8900}{}{你从出生开始就有一个小而发育不良的大脑，而且由于严重的头部损伤，你也遭受了严重的大脑损伤。值得庆幸的是，这种损害并不像看上去的那样是永久性的。我做得很好—你现在可以连贯地表达自己了。这比任何人对你的期望都要高。}
#{8901}{}{You've had a small and stunted brain since birth, and you've also suffered heavy brain damage due to serious head injuries. Thankfully, the damage was not as permanent as it appeared. I did a splendid job - you can now coherently express yourself. That's much more than anyone could've hoped for in your case.}
{8901}{}{你从出生开始就有一个小而发育不良的大脑，而且由于严重的头部损伤，你也遭受了严重的大脑损伤。值得庆幸的是，这种损害并不像看上去的那样是永久性的。我做得很好—你现在可以连贯地表达自己了。这比任何人对你的期望都要高。}
#{8902}{}{Ech... Oh. Great! Thanks a lot, doctor.}
{8902}{}{呃...哦。太好了，谢谢你，医生。}
#{8950}{}{Are you interested in one of the procedures or are you just unforgivably wasting my time?}
{8950}{}{你是对其中一个手术感兴趣还是你只是在不可原谅地浪费我的时间？}
#{9000}{}{You have a floater? The fact that the Master and his scientists were able to create something like that shows their amazing skill, doesn't it? I'm surprised they let you into the city with it. Though I suppose not many know their real origin nowadays. Despite that, I'm not taking the risk of allowing a floater here in the hospital, so kindly take it away.}
{9000}{}{你有个浮游特？大师和他的科学家们能够创造出这样的东西，这表明了他们惊人的技能，不是吗？我很惊讶他们让你带着它进城。不过我想现在知道它们真正起源的人不多了。尽管如此，我不会冒险让一个浮游特在医院里，所以请你把它带走。}
#{9001}{}{Ugh.}
{9001}{}{啊。}
#{9050}{}{Welcome, Hunter. I am doctor Falber, the head of this hospital. What brings you to us? If you are looking for quality medical services then look no further.}
{9050}{}{欢迎，猎人。我是福伯医生，医院的院长。什么风把你吹来了？如果你正在寻找高质量的医疗服务，那么不用再找了。}
#{9056}{}{My mistake.}
{9056}{}{我的错误。}
#{9100}{}{Welcome, Hunter. [He smiles like a cat that just caught a mouse.] I am doctor Falber, the head of this hospital. What brings you to us? If you are looking for quality medical services then look no further.}
{9100}{}{欢迎，猎人。[他笑得像一只刚逮到老鼠的猫。]我是福伯医生，这家医院的院长，什么风把你吹来了？如果你正在寻找高质量的医疗服务，那么不用再找了。}
#{9150}{}{Welcome again. There is no need to worry, many Hunters count themselves among our customers.}
{9150}{}{欢迎再次光临。不用担心，很多猎人都是我们的客户。}
#{9160}{}{Considering we defend the city from mutants, how about you give us Hunters a discount?}
{9160}{}{考虑到我们要保护城市不受变种人的侵害，不如你给我们猎人打个折吧？}
#{9161}{}{I'll be on my way, bye.}
{9161}{}{我要走了，再见。}
#{9200}{}{As I'm sure you know, commander Herman decides what happens in the city. And since he's a reasonable man, he won't interfere in our business as long as we neither treat nor make use of mutants. And I can assure you that when we do discover a mutant, we send his body to your base right away. Of course, that happens only rarely. Your people are quite diligent in preventing mutants from entering Albuquerque.}
{9200}{}{我相信你知道，赫尔曼指挥官决定着这个城市会发生什么。因为他是个通情达理的人，只要我们既不治疗也不利用变种人，他就不会干涉我们的生意。我可以向你保证，当我们发现一个变种人时，我们会立即将他的尸体送到你的基地。当然，这种情况很少发生。你们的人非常努力地阻止变种人进入阿尔伯克基。}
#{9201}{}{But doctor Yaotzin doesn't seem to think of your hospital too highly.}
{9201}{}{但耀津医生似乎对你的医院评价不高。}
#{9202}{}{I won't give up that easily! I won't rest until I find someone in this city that will help me stop you!}
{9202}{}{我不会那么轻易放弃的！不找到能帮我阻止你的人我是不会罢休的！}
#{9203}{}{If no one else will stop you, then I will!}
{9203}{}{如果没人能阻止你，那我来！}
#{9204}{}{I guess it's pointless to try doing something about it.}
{9204}{}{我想尝试做点什么都是没有意义的。}
#{9250}{}{I was hoping you were a reasonable man. But if that's how you see things, I have no choice but to exclude you from our plan. Should you try to tell anything to Herman, I will deny everything. And, as you had the opportunity to witness, he finds me quite trustworthy. Here is 500 caps, I never owe anyone anything, and now leave.}
{9250}{}{我希望你是个讲道理的人。但如果你是这么想的，我别无选择，只能把你排除在我们的计划之外。如果你试图告诉赫尔曼任何事，我会否认一切。而且，正如你所看到的那样，他觉得我很值得信任。这里是500瓶盖，我从来不欠任何人任何东西，现在离开。}
#{9251}{}{I was hoping you were a reasonable woman. But if that's how you see things, I have no choice but to exclude you from our plan. Should you try to tell anything to Herman, I will deny everything. And, as you had the opportunity to witness, he finds me quite trustworthy. Here is 500 caps, I never owe anyone anything, and now leave.}
{9251}{}{我希望你是个讲道理的女人。但如果你是这么想的，我别无选择，只能把你排除在我们的计划之外。如果你试图告诉赫尔曼任何事，我会否认一切。而且，正如你所看到的那样，他觉得我很值得信任。这里是500瓶盖，我从来不欠任何人任何东西，现在离开。}
#{9252}{}{As you wish. Goodbye.}
{9252}{}{如你所愿。再见。}
#{9253}{}{I will punish you right here and now for betraying the purity of mankind!}
{9253}{}{我现在就要惩罚你，因为你背叛了人类的纯洁！}
#{9350}{}{Our prices reflect the quality of our services. And we never lower the quality, and thus the price, for anyone.}
{9350}{}{我们的价格反映了我们服务的质量，我们从不降低任何人的质量，因此也不降低价格。}
#{9351}{}{If you won't give me a discount, I might shoot you and justify it by saying that you treat even mutants.}
{9351}{}{如果你不给我折扣，我可能会杀了你，然后说你连变种人都治疗。}
#{9352}{}{It was worth a try.}
{9352}{}{值得一试。}
#{9400}{}{I feel compelled to note that a large number of Hunters were treated here, thus, few would be willing to believe such a tale. The only thing you would accomplish by trying to kill me would be passing on your organs to one of your wiser compatriots, everything with commander Herman's permission.}
{9400}{}{我不得不指出，这里治疗过大量的猎人，因此，很少有人愿意相信这样的故事。你想杀我的唯一目的就是把你的器官交给一个更聪明的同胞，只要得到赫尔曼指挥官的允许。}
#{9401}{}{We'll see about that!}
{9401}{}{我们走着瞧！}
#{9402}{}{OK, I apologize. Forget about it.}
{9402}{}{OK，我道歉。算了吧。}
#{9450}{}{Paul has informed me that the donor collection went off without any serious complications. I never hold off paying for quality work, here's 10000 caps. We should have enough donors for a long time, especially thanks to your negotiation with Herman, so I doubt we'll make use of your services again. But, as compensation, I'd like to offer you a fifty percent discount on the endurance increasing procedure, which normally costs 15000. One of the tribals will surely serve as a suitable donor. We can perform the operation whenever you like.}
{9450}{}{保罗告诉我，捐赠者的收集工作顺利进行，没有出现任何严重的情况。我从不拖延为高质量的工作付钱，这里有10000个瓶盖。我们应该有足够的捐赠者维持很长一段时间，特别是多亏了你和赫尔曼的谈判，所以我怀疑我们不会再用你的服务了。但是，作为补偿，我想在给你做延长耐力手术上打五折，通常这个手术要15000瓶盖。其中一个部落肯定会成为合适的捐赠者。你想什么时候做手术我们都可以。}
#{9451}{}{Paul has informed me that a large number of potential donors died during the collection. That is unfortunate; I'll have to lower your pay to 5000 caps. Even so, we should have enough donors for a long time, especially thanks to your negotiation with Herman, so I doubt we'll make use of your services again. But, as compensation, I'd like to offer you a fifty percent discount on the endurance increasing procedure, which normally costs 15000. One of the tribals will surely serve as a suitable donor. We can perform the operation whenever you like.}
{9451}{}{保罗告诉我，大量潜在捐赠者在募捐过程中死亡。真不幸，我不得不把你的工资降到5000瓶盖。即便如此，我们还是有足够的捐赠者维持很长一段时间，特别是多亏了你和赫尔曼的谈判，所以我怀疑我们不会再用你的服务了。但是，作为补偿，我想在给你做延长耐力手术上打五折，通常这个手术要15000瓶盖。其中一个部落肯定会成为合适的捐赠者。你想什么时候做手术我们都可以。}
#{9452}{}{I'd prefer more cash to a discount.}
{9452}{}{比起折扣，我更喜欢现金。}
#{9453}{}{Here's 7500 for the operation.}
{9453}{}{这是7500的手术费。}
#{9454}{}{OK, I might come back for the surgery at some point. Goodbye for now.}
{9454}{}{OK，我可能会回来做手术的。再见了。}
#{9500}{}{Your presence was not that beneficial. I'm sure that you'll find the discount to be a suitable reward once you think it through. I have nothing more to say on the matter, goodbye.}
{9500}{}{你的出现并没有带来什么好处。我相信一旦你想清楚了，你会发现折扣是一个合适的奖励。关于这件事我没什么可说的了，再见。}
#{9501}{}{Farewell.}
{9501}{}{再见。}
#{9502}{}{Now way, if you won't cough up more, I'll gut you like a dog!}
{9502}{}{现在，如果你再咳出来，我会像宰狗一样宰了你！}
#{9550}{}{Paul has informed me that the donor collection went off without any serious complications. I never hold off paying for quality work, here's 10000 caps. We should have enough donors for a long time, so I doubt we'll make use of your services again. Of course, you are still welcome here as a customer.}
{9550}{}{保罗告诉我，捐赠者的收集工作顺利进行，没有出现任何严重的情况。我从不拖延为高质量的工作付钱，这里有10000个瓶盖。我们应该有足够的捐赠者维持很长一段时间，所以我怀疑我们不会再用你的服务了。当然，我们仍然欢迎您作为顾客光临。}
#{9551}{}{Paul has informed me that the donor collection went off without any serious complications. I never hold off paying for quality work, here's 10000 caps. We should have enough donors for a long time, so I doubt we'll make use of your services again. Of course, you are still welcome here as a customer.}
{9551}{}{保罗告诉我，捐赠者的收集工作顺利进行，没有出现任何严重的情况。我从不拖延为高质量的工作付钱，这里有10000个瓶盖。我们应该有足够的捐赠者维持很长一段时间，所以我怀疑我们不会再用你的服务了。当然，我们仍然欢迎您作为顾客光临。}
#{9552}{}{Paul has informed me that the donor collection went off without any serious complications. I never hold off paying for quality work, here's 10000 caps, as well as 2000 caps for your negotiation with Herman. We should have enough donors for a long time, so I doubt we'll make use of your services again. Of course, you are still welcome here as a customer.}
{9552}{}{保罗告诉我，捐赠者的收集工作顺利进行，没有出现任何严重的情况。我从不拖延为高质量的工作付钱，这里有10000个瓶盖，以及2000瓶盖作为您与赫尔曼谈判的报酬。我们应该有足够的捐赠者维持很长一段时间，所以我怀疑我们不会再用你的服务了。当然，我们仍然欢迎您作为顾客光临。}
#{9553}{}{Paul has informed me that the donor collection went off without any serious complications. I never hold off paying for quality work, here's 10000 caps, as well as 2000 caps for your negotiation with Herman. We should have enough donors for a long time, so I doubt we'll make use of your services again. Of course, you are still welcome here as a customer.}
{9553}{}{保罗告诉我，捐赠者的收集工作顺利进行，没有出现任何严重的情况。我从不拖延为高质量的工作付钱，这里有10000个瓶盖，以及2000瓶盖作为您与赫尔曼谈判的报酬。我们应该有足够的捐赠者维持很长一段时间，所以我怀疑我们不会再用你的服务了。当然，我们仍然欢迎您作为顾客光临。}
#{9554}{}{Paul has informed me that a large number of potential donors died during the collection. That is unfortunate; I'll have to lower your pay to 5000 caps. Even so, we should have enough donors for a long time, so I doubt we'll make use of your services again. Of course, you are still welcome here as a customer.}
{9554}{}{保罗告诉我，大量潜在捐赠者在募捐过程中死亡。真不幸，我不得不把你的工资降到5000瓶盖。即便如此，我们还是有足够的捐赠者维持很长一段时间，所以我怀疑我们不会再用你的服务了。当然，我们仍然欢迎您作为顾客光临。}
#{9555}{}{Paul has informed me that a large number of potential donors died during the collection. That is unfortunate; I'll have to lower your pay to 5000 caps. Even so, we should have enough donors for a long time, so I doubt we'll make use of your services again. Of course, you are still welcome here as a customer.}
{9555}{}{保罗告诉我，大量潜在捐赠者在募捐过程中死亡。真不幸，我不得不把你的工资降到5000瓶盖。即便如此，我们还是有足够的捐赠者维持很长一段时间，所以我怀疑我们不会再用你的服务了。当然，我们仍然欢迎您作为顾客光临。}
#{9556}{}{Paul has informed me that a large number of potential donors died during the collection. That is unfortunate; I'll have to lower your pay to 5000 caps. I will also give you an extra 2000 caps for your negotiation with Herman. Partly thanks to that, we should have enough donors for a long time, so I doubt we'll make use of your services again. Of course, you are still welcome here as a customer.}
{9556}{}{保罗告诉我，大量潜在捐赠者在募捐过程中死亡。真不幸，我不得不把你的工资降到5000瓶盖。我还会给你额外的2000瓶盖作为你和赫尔曼谈判的费用。部分得益于此，我们在很长一段时间内应该有足够的捐赠者，所以我怀疑我们不会再用你的服务了。当然，我们仍然欢迎您作为顾客光临。}
#{9557}{}{Paul has informed me that a large number of potential donors died during the collection. That is unfortunate; I'll have to lower your pay to 5000 caps. I will also give you an extra 2000 caps for your negotiation with Herman. Partly thanks to that, we should have enough donors for a long time, so I doubt we'll make use of your services again. Of course, you are still welcome here as a customer.}
{9557}{}{保罗告诉我，大量潜在捐赠者在募捐过程中死亡。真不幸，我不得不把你的工资降到5000瓶盖。我还会给你额外的2000瓶盖作为你和赫尔曼谈判的费用。部分得益于此，我们在很长一段时间内应该有足够的捐赠者，所以我怀疑我们不会再用你的服务了。当然，我们仍然欢迎您作为顾客光临。}
#{9558}{}{Thanks, see you later.}
{9558}{}{谢谢，回见。}
#{9600}{}{Paul has informed me that a large number of donors died during the collection, largely because of you. Here is 1000 caps for your effort, and we never intend to make use of your services ever again.}
{9600}{}{保罗告诉我有很多捐献者在募捐过程中死亡，很大程度上是因为你。这是你卖力工作的1000个瓶盖，我们再也不打算使用你的服务了。}
#{9601}{}{Paul has informed me that a large number of donors died during the collection, largely because of you. Here is 1000 caps for your effort, and we never intend to make use of your services ever again.}
{9601}{}{保罗告诉我有很多捐献者在募捐过程中死亡，很大程度上是因为你。这是你卖力工作的1000个瓶盖，我们再也不打算使用你的服务了。}
#{9602}{}{Goodbye.}
{9602}{}{再见。}
#{9603}{}{What?! You won't give me proper pay because a few more blasted tribals kicked the bucket?! No way, if you won't cough up more, I'll gut you like a dog!}
{9603}{}{什么？！你不给我适当的报酬就因为有几个该死的部落死了！不行，如果你再咳出来，我就把你当狗一样宰了！}
#{9650}{}{Certainly. Ask away.}
{9650}{}{当然。问吧。}
#{9651}{}{Tell me about the strength enhancing procedure.}
{9651}{}{告诉我增强力量的手术。}
#{9652}{}{Tell me about the perception enhancing procedure.}
{9652}{}{告诉我增强感知的手术。}
#{9653}{}{Tell me about the endurance enhancing procedure.}
{9653}{}{告诉我增强耐力的手术。}
#{9654}{}{Tell me about the charisma enhancing procedure.}
{9654}{}{告诉我提升魅力的手术。}
#{9655}{}{Tell me about the intelligence enhancing procedure.}
{9655}{}{告诉我提高智力的手术。}
#{9656}{}{Tell me about the agility enhancing procedure.}
{9656}{}{告诉我增强敏捷的手术。}
#{9657}{}{Tell me again how the procedures work in general.}
{9657}{}{再告诉我一遍手术是怎样的。}
#{9658}{}{I don't actually want to ask anything. Goodbye.}
{9658}{}{我其实什么都不想问。再见。}
#{9700}{}{Considering the state of your mind, I'm willing to offer you the same services as any other customer, provided you can pay. However, I won't discuss business matters while you are like this.}
{9700}{}{考虑到你的精神状态，我愿意为你提供和其他顾客一样的服务，只要你愿意付钱。不过，我不会在你这样的时候讨论生意上的事情。}
#{9750}{}{Welcome. I prefer not to owe anyone, so let's conclude our transaction right now. The boy you sent to us is a curious specimen indeed. Though he recently started to destroy his body with drugs, it is still quite valuable thanks to the imperial medical care he previously received. He is also suitable for use in the agility enhancing procedure. Here is 12500 caps for him.}
{9750}{}{欢迎光临。我不想欠任何人的，所以我们现在就完成交易吧。你送来的那个男孩确实是个奇怪的样本。虽然他最近开始用药物摧毁自己的身体，但由于他以前接受的皇家医疗照顾，他仍然是相当有价值的。他也适合用于敏捷增强手术。这是他的12500个瓶盖。}
#{9751}{}{Welcome. I prefer not to owe anyone, so let's conclude our transaction right now. The boy you sent to us is a curious specimen indeed. Though he recently started to destroy his body with drugs, it is still quite valuable thanks to the imperial medical care he previously received. He is also suitable for use in the agility enhancing procedure. Here is 12500 caps for him.}
{9751}{}{欢迎光临。我不想欠任何人的，所以我们现在就完成交易吧。你送来的那个男孩确实是个奇怪的样本。虽然他最近开始用药物摧毁自己的身体，但由于他以前接受的皇家医疗照顾，他仍然是相当有价值的。他也适合用于敏捷增强手术。这是他的12500个瓶盖。}
#{9752}{}{What if I happened to change my mind, would it be possible to get the boy back?}
{9752}{}{如果我碰巧改变了主意，有可能把那个男孩弄回来吗？}
#{9753}{}{What if I happened to change my mind, would it be possible to get the boy back?}
{9753}{}{如果我碰巧改变了主意，有可能把那个男孩弄回来吗？}
#{9754}{}{Thanks.}
{9754}{}{谢谢。}
#{9800}{}{I beg your pardon? I didn't ask you to remove him. That is most unfortunate, it seems that Paul has severely overestimated your abilities and your intelligence. It will be hard to convince the Hunters that I had nothing to do with what you did. But, if I give them your corpse... [Someone firmly grabs you from behind around your neck and plunges a syringe into your artery. You slowly lose consciousness.] I'm sure they will realize that I never do anything against their interests. [You fall asleep, never to wake again.]}
{9800}{}{你说什么？我没让你除掉他。太不幸了，看来保罗严重高估了你的能力和智商。很难让猎人们相信我和你的所作所为毫无关系。但是，如果我把你的尸体给他们…[有人从脖子后面紧紧抓住你，把注射器插进你的动脉。你慢慢失去意识。]我相信他们会意识到我从不做任何违背他们利益的事。[你睡着了，再也不会醒来。]}
#{9801}{}{[End.]}
{9801}{}{[结束。]}
#{9850}{}{I beg your pardon? I didn't ask you to remove him. That is most unfortunate, it seems that Paul has severely overestimated your abilities and your intelligence. It will be hard to convince the Hunters that I had nothing to do with what you did. But, if I give them your corpse... [At the last moment, you notice a stocky man with a syringe trying to grab you from behind and narrowly dodge him.]}
{9850}{}{你说什么？我没让你除掉他。太不幸了，看来保罗严重高估了你的能力和智商。很难让猎人们相信我和你的所作所为毫无关系。但是，如果我把你的尸体给他们…[在最后一刻，你注意到一个矮壮的男人拿着注射器试图从后面抓住你，并勉强躲开了他。]}
#{9851}{}{I beg your pardon? I didn't ask you to remove him. That is most unfortunate, it seems that Paul has severely overestimated your abilities and your intelligence. It will be hard to convince the Hunters that I had nothing to do with what you did. But, if I give them your corpse... [At the last moment, you notice a stocky man with a syringe trying to grab you from behind and narrowly dodge him.]}
{9851}{}{你说什么？我没让你除掉他。太不幸了，看来保罗严重高估了你的能力和智商。很难让猎人们相信我和你的所作所为毫无关系。但是，如果我把你的尸体给他们…[在最后一刻，你注意到一个矮壮的男人拿着注射器试图从后面抓住你，并勉强躲开了他。]}
#{9852}{}{[Defend yourself.]}
{9852}{}{[保护自己。]}
#{9900}{}{Welcome. I prefer not to owe anyone, so let's conclude our transaction right now. The boy you sent to us is a curious specimen indeed. Though he recently started to destroy his body with drugs, it is still quite valuable thanks to the imperial medical care he previously received. He is also suitable for use in the agility enhancing procedure. I can either give you a fifty percent discount on the procedure, reducing the price to 12500 caps, or simply pay you the same amount.}
{9900}{}{欢迎光临。我不想欠任何人的，所以我们现在就完成交易吧。你送来的那个男孩确实是个奇怪的样本。虽然他最近开始用药物摧毁自己的身体，但由于他以前接受的皇家医疗照顾，他仍然是相当有价值的。他也适合用于敏捷增强手术。我可以在手术上给你打五折，把价格降到12500个瓶盖，或者直接付给你同样的钱。}
#{9901}{}{Welcome. I prefer not to owe anyone, so let's conclude our transaction right now. The boy you sent to us is a curious specimen indeed. Though he recently started to destroy his body with drugs, it is still quite valuable thanks to the imperial medical care he previously received. He is also suitable for use in the agility enhancing procedure. I can either give you a fifty percent discount on the procedure, reducing the price to 12500 caps, or simply pay you the same amount.}
{9901}{}{欢迎光临。我不想欠任何人的，所以我们现在就完成交易吧。你送来的那个男孩确实是个奇怪的样本。虽然他最近开始用药物摧毁自己的身体，但由于他以前接受的皇家医疗照顾，他仍然是相当有价值的。他也适合用于敏捷增强手术。我可以在手术上给你打五折，把价格降到12500个瓶盖，或者直接付给你同样的钱。}
#{9902}{}{What if I happened to change my mind, would it be possible to get the boy back?}
{9902}{}{如果我碰巧改变了主意，有可能把那个男孩弄回来吗？}
#{9903}{}{What if I happened to change my mind, would it be possible to get the boy back?}
{9903}{}{如果我碰巧改变了主意，有可能把那个男孩弄回来吗？}
#{9904}{}{Give me the 12500 caps.}
{9904}{}{给我12500个瓶盖。}
#{9905}{}{Alright, here's 12500 for the procedure.}
{9905}{}{好的，这是12500瓶盖的手术费。}
#{9906}{}{Give me the 12500 caps, I don't have enough to pay for the rest of the procedure anyway.}
{9906}{}{给我12500瓶盖吧，反正我也没钱支付剩下的费用了。}
#{9950}{}{I'm afraid that's not possible. Not only would I have to charge you for his examination, but we've already used some of his organs. He's currently incapable of speech or significant movement.}
{9950}{}{恐怕不行。我不仅要为他的检查收费，而且我们已经用了他的一些器官。他现在不能说话，也不能活动。}
#{9951}{}{I see, I'll take the 12500 caps then.}
{9951}{}{我明白了，那我就拿12500个瓶盖吧。}
#{9952}{}{Alright, here's 12500 for the procedure.}
{9952}{}{好的，这是12500瓶盖的手术费。}
#{9953}{}{Give me the 12500 caps, I don't have enough to pay for the rest of the procedure anyway.}
{9953}{}{给我12500瓶盖吧，反正我也没钱支付剩下的费用了。}
#{10000}{}{I'm afraid that's not possible. Not only would I have to charge you for his examination, but we've already used some of his organs. He's currently incapable of speech or significant movement.}
{10000}{}{恐怕不行。我不仅要为他的检查收费，而且我们已经用了他的一些器官。他现在不能说话，也不能活动。}
#{10001}{}{OK.}
{10001}{}{OK。}
#{10050}{}{Interesting, that does explain a lot. But I'm afraid I really don't know anything about the tribals. As I'm sure you realize, they aren't often our customers, so I don't care about their lives much.}
{10050}{}{有意思，这解释了很多问题。但恐怕我对部落一无所知。我相信你也知道，他们通常不是我们的客户，所以我不太关心他们的生活。}
#{10051}{}{What do you mean it explains a lot?}
{10051}{}{什么叫解释了很多事？}
#{10100}{}{That's none of your business. And that's all I'm going to say on this matter. Goodbye.}
{10100}{}{那不关你的事。这就是我要说的。再见。}
#{10101}{}{Goodbye.}
{10101}{}{再见。}
#{10150}{}{Hold on. We found out that you received a number of transplants in the past. I'm curious why and, more importantly, who performed them? They were done so expertly that, were it not for our meticulous diagnosis both before and after the surgery, we wouldn't have even noticed.}
{10150}{}{等一下。我们发现你过去接受过多次移植手术。我很好奇为什么，更重要的是，是谁做的？他们做得非常专业，如果不是我们在手术前后都进行了细致的诊断，我们甚至都不会注意到。}
#{10151}{}{Hold on. We found out that you received a number of transplants in the past. I'm curious why and, more importantly, who performed them? They were done so expertly that, were it not for our meticulous diagnosis both before and after the surgery, we wouldn't have even noticed.}
{10151}{}{等一下。我们发现你过去接受过多次移植手术。我很好奇为什么，更重要的是，是谁做的？他们做得非常专业，如果不是我们在手术前后都进行了细致的诊断，我们甚至都不会注意到。}
#{10152}{}{Really? Could you tell me more? Do you have even an idea who could've done something like that?}
{10152}{}{真的吗？你能告诉我更多吗？你知道是谁干的吗？}
#{10153}{}{I've not intention to talk about it. I'm sorry. Goodbye.}
{10153}{}{我不想谈这个，对不起，再见。}
#{10200}{}{You're asking me? I doubt anyone could've performed surgery this complex on you without your knowing. I don't know anyone with access to technology that would be advanced enough to perform the transplants. I'd certainly like to meet such people. We're talking about a fully equipped medical facility and a team of surgeons trained specifically for this task. Not even the empire has the capacity for that. Or were they experimenting on you? If I were to dissect your body, I'm sure I could find out the reason for it all.}
{10200}{}{你在问我吗？我怀疑没人能在你不知情的情况下给你做这么复杂的手术。我不知道有谁能掌握足够先进的技术来进行移植手术。我当然想认识这样的人。我们说的是一个设备齐全的医疗设施和一个受过专门训练的外科医生团队。即使是帝国也没有这个能力。还是他们在你身上做实验？如果我解剖你的身体，我肯定能找出原因。}
#{10201}{}{You're not dissecting me, forget about it. Anyway, thanks for the information. Later.}
{10201}{}{你不能解剖我，算了吧，不管怎样，谢谢你的信息，以后再说。}
