#{100}{}{You see a muscular tribal.}
{100}{}{你看到一个肌肉发达的部落。}
#{150}{}{You see Gurgan.}
{150}{}{你看到古根了。}
#{200}{}{You see a stout tribal with a surly expression. His body is adorned with several tattoos.}
{200}{}{你看到一个粗壮的部落，表情粗暴。他的身上有好几个纹身。}
#{201}{}{ He is stunned.}
{201}{}{他惊呆了。}
#{250}{}{You see Gurgan, the chief of the tribe.}
{250}{}{你看古尔根，部落首领。}
#{300}{}{The time has come. Enemies shall know the fury of the tribe.}
{300}{}{时间到了。敌人会知道部落的愤怒。}
#{301}{}{Friend must not disturb Gurgan now. He is training his dog.}
{301}{}{朋友现在不能打扰古根。他正在训练他的狗。}
#{302}{}{Friend must not disturb Gurgan now. He is training her dog.}
{302}{}{朋友现在不能打扰古根。他正在训练她的狗。}
#{303}{}{Outsider has caused the loss of one of the tribe's hunters. Gurgan does not wish to see him here again.}
{303}{}{外人造成了部落一名猎人的死亡。古根不想再在这里见到他。}
#{304}{}{Outsider has caused the loss of one of the tribe's hunters. Gurgan does not wish to see her here again.}
{304}{}{外人造成了部落一名猎人的死亡。古根不想再在这里见到她。}
#{305}{}{Outsider has killed three of the tribe's hunters. Gurgan does not wish to see him here again.}
{305}{}{外人杀死了部落的三个猎人。古根不想再在这里见到他。}
#{306}{}{Outsider has killed three of the tribe's hunters. Gurgan does not wish to see her here again.}
{306}{}{外人杀死了部落的三个猎人。古根不想再在这里见到她。}
#{307}{}{Murderer should leave!}
{307}{}{凶手应该离开！}
#{308}{}{Murderer should leave!}
{308}{}{凶手应该离开！}
#{309}{}{Now the tribe will dispose of the rest!}
{309}{}{现在部落会处理剩下的！}
#{310}{}{Gurgan does not wish to see outsider ever again. The tribe has enough enemies without him. It does not need more.}
{310}{}{古尔根不想再见到外人。没有他这个部落的敌人已经够多了。它不需要更多。}
#{311}{}{Gurgan does not wish to see outsider ever again. The tribe has enough enemies without her. It does not need more.}
{311}{}{古尔根不想再见到外人。没有她这个部落的敌人已经够多了。它不需要更多。}
#{312}{}{Outsider should leave!}
{312}{}{外人该走了！}
#{313}{}{Outsider should leave!}
{313}{}{外人该走了！}
#{400}{}{Outsider made a big mistake.}
{400}{}{局外人犯了个大错。}
#{401}{}{Outsider made a big mistake.}
{401}{}{局外人犯了个大错。}
#{402}{}{Ancestors stand with Gurgan.}
{402}{}{祖先与古根站在一起。}
#{403}{}{Gurgan will fight to the end.}
{403}{}{古尔根将战斗到底。}
#{410}{}{The tribe will triumph! Gurgan will take care of that.}
{410}{}{部落会胜利的！古根会处理的。}
#{411}{}{Ancestors stand by the tribe.}
{411}{}{祖先支持部落。}
#{420}{}{Gurgan loses consciousness and falls lifelessly to the ground.}
{420}{}{古尔根失去知觉，毫无生气地倒在地上。}
#{500}{}{Why does outsider disturb Gurgan? Is the rest of the town too small for him? Gurgan's tent is a good place, but it is meant only for him and his dogs. Outsider should find his own.}
{500}{}{外人为什么要打扰古根？镇上其他地方对他来说太小了吗？古尔根的帐篷是个好地方，但它只适合他和他的狗。局外人应该自己找。}
#{501}{}{Why does outsider disturb Gurgan? Is the rest of the town too small for her? Gurgan's tent is a good place, but it is meant only for him and his dogs. Outsider should find her own.}
{501}{}{外人为什么要打扰古根？镇上其他地方对她来说太小了吗？古尔根的帐篷是个好地方，但它只适合他和他的狗。外人应该自己找。}
#{502}{}{That's not the reason I'm here. I just wanted to know who's in charge.}
{502}{}{这不是我来这里的原因。我只是想知道谁负责。}
#{503}{}{Whatever, I'm leaving.}
{503}{}{不管怎样，我要走了。}
#{504}{}{Eh, who you?}
{504}{}{呃，你是谁？}
#{550}{}{Outsider is curious indeed. Gurgan leads the tribe, he is the chief. What does outsider want from him?}
{550}{}{外人确实很好奇。古尔根领导着部落，他是酋长。外人想从他那里得到什么？}
#{551}{}{Outsider is curious indeed. Gurgan leads the tribe, he is the chief. What does outsider want from him?}
{551}{}{外人确实很好奇。古尔根领导着部落，他是酋长。外人想从他那里得到什么？}
#{552}{}{I just want to ask you a few questions.}
{552}{}{我只想问你几个问题。}
#{553}{}{I just want to ask you a few questions.}
{553}{}{我只想问你几个问题。}
#{554}{}{I've heard you've been losing many people lately. I was curious if it's true.}
{554}{}{我听说你最近失去了很多人。我很好奇这是不是真的。}
#{555}{}{Nothing. Bye, Gurgan.}
{555}{}{没有什么。再见，古根。}
#{556}{}{Uh? Wut tribe do here?!}
{556}{}{休斯敦大学？你在这里干什么？！}
#{557}{}{Nuffin! Bai Gurgan.}
{557}{}{努芬！白古根。}
#{600}{}{[He thinks.] Very well, outsider may ask. Gurgan will answer.}
{600}{}{[他想]很好，外人可能会问。古根会回答的。}
#{601}{}{[He thinks.] Very well, outsider may ask. Gurgan will answer.}
{601}{}{[他想]很好，外人可能会问。古根会回答的。}
#{602}{}{How did you get here?}
{602}{}{你怎么来的？}
#{603}{}{How do you make a living here?}
{603}{}{你怎么在这里谋生？}
#{604}{}{How do you get along with others?}
{604}{}{你和别人相处得怎么样？}
#{605}{}{I've heard you've been losing many people lately. Is it true?}
{605}{}{我听说你最近失去了很多人。是真的吗？}
#{606}{}{Actually, I don't want to know anything. Goodbye.}
{606}{}{实际上，我什么都不想知道。再见。}
#{650}{}{That is not a pleasant tale, Gurgan's tribe suffered much misfortune. [He falls silent.] Once, Gurgan's home was far away from here, on ancestor's land. There was a river nearby, and much game. The tribe was mighty then, ruling over other tribes. But then came a disaster. Burned people attacked and killed most of the tribe. Only a few escaped. Gurgan led them. He decided to find a safe place and after a long journey brought the tribe here. The tribe would have perished anywhere else.}
{650}{}{这不是一个愉快的故事，古尔根的部落遭受了很多不幸。[他沉默了]有一次，古根的家离这里很远，在祖先的土地上。附近有一条河，有很多猎物。那个部落当时很强大，统治着其他部落。但随后发生了一场灾难。被烧死的人袭击并杀害了部落的大部分人。只有少数人逃脱了。古尔根领导了他们。他决定找个安全的地方，经过长途旅行把部落带到了这里。这个部落在其他任何地方都会灭亡。}
#{651}{}{Got it. Another question.}
{651}{}{知道了。另一个问题。}
#{652}{}{I need to go now. Bye.}
{652}{}{我得走了。再见。}
#{700}{}{Making a living here is hard. The town people refuse to help, and there is almost no game in the surrounding wasteland. Only geckos are left. Thankfully, their skins fetch a good price from the traders. As long as Gurgan's hunters get enough of them, the tribe will survive. But that is now threatened. Many hunters did not come back from the hunt, and Gurgan does not know what could have happened to them. If it goes on, the whole tribe will perish.}
{700}{}{在这里谋生很难。镇上的人拒绝帮助，周围的荒地几乎没有游戏。只剩下壁虎了。谢天谢地，他们的皮从商人那里卖了个好价钱。只要古尔根的猎人得到足够的数量，这个部落就会生存下去。但这一点现在受到威胁。许多猎人没有打完猎回来，古尔根也不知道他们会发生什么。如果继续下去，整个部落都会灭亡。}
#{701}{}{Maybe I could help. I'd love to join the hunt.}
{701}{}{也许我能帮上忙。我很想参加狩猎。}
#{702}{}{Maybe I could help. I'd love to join the hunt.}
{702}{}{也许我能帮上忙。我很想参加狩猎。}
#{703}{}{I'm sure you'll do fine. Another question.}
{703}{}{我相信你会做得很好。另一个问题。}
#{704}{}{I need to go. Bye.}
{704}{}{我得走了。再见。}
#{750}{}{People of the city look down on the tribe. They want only to harm, and think Gurgan does not see it. But he is no fool. He is watching them, and Mutant Hunters above all. Many times they took people who they considered unclean away from the tribe. But that cannot be allowed. Only shaman Rua can decide such things. Ancestors are very angry with Hunters now.}
{750}{}{城里人瞧不起这个部落。他们只想伤害，认为古尔根看不到。但他不是傻瓜。他在监视他们，尤其是变种猎人。他们多次把他们认为不洁净的人从支派中带走。但这是不允许的。只有阮萨满能决定这样的事情。祖先现在对猎人很生气。}
#{751}{}{Got it. Another question.}
{751}{}{知道了。另一个问题。}
#{752}{}{I have to go. Goodbye, Gurgan.}
{752}{}{我得走了。再见，古根。}
#{800}{}{[He studies you.] Gurgan does not know outsider, but he shall trust him. He is in need of another hunter. Hopefully, he will not come to regret this.}
{800}{}{[他研究你]古尔根不认识外人，但他应该信任他。他需要另一个猎人。希望他不会为此后悔。}
#{801}{}{[He studies you.] Gurgan does not know outsider, but he shall trust her. He is in need of another hunter. Hopefully, he will not come to regret this.}
{801}{}{[他研究你]古根不认识外人，但他应该信任她。他需要另一个猎人。希望他不会为此后悔。}
#{802}{}{Certainly not. When's the next hunt?}
{802}{}{当然不是。下一次狩猎是什么时候？}
#{803}{}{Regret nuffin! Hunt when?}
{803}{}{抱歉，努芬！什么时候打猎？}
#{850}{}{[He studies you.] Gurgan does not know outsider, he cannot trust him. He must refuse his offer.}
{850}{}{[他研究你]古根不认识外人，他不能信任他。他必须拒绝他的提议。}
#{851}{}{[He studies you.] Gurgan does not know outsider, he cannot trust her. He must refuse her offer.}
{851}{}{[他研究你]古根不认识外人，他不能信任她。他必须拒绝她的提议。}
#{852}{}{If you say so. Another question.}
{852}{}{如果你这样说。另一个问题。}
#{853}{}{Whatever, I'm leaving.}
{853}{}{不管怎样，我要走了。}
#{854}{}{Me sad. Bai.}
{854}{}{我很伤心。白。}
#{900}{}{Gurgan's hunters can go right now, if outsider is ready.}
{900}{}{如果外人准备好了，古根的猎人们现在就可以走了。}
#{901}{}{Gurgan's hunters can go right now, if outsider is ready.}
{901}{}{如果外人准备好了，古根的猎人们现在就可以走了。}
#{902}{}{Let's go then.}
{902}{}{那我们走吧。}
#{903}{}{Not right now. Maybe I'll join in later.}
{903}{}{现在不行。也许我稍后会加入。}
#{904}{}{Not right now. Maybe I'll join in later.}
{904}{}{现在不行。也许我稍后会加入。}
#{905}{}{Yaaay!}
{905}{}{耶！}
#{906}{}{Ehh, no go now. Bai.}
{906}{}{呃，现在不行。白。}
#{950}{}{Outsider may ask. Gurgan will answer.}
{950}{}{外人可能会问。古根会回答的。}
#{951}{}{Outsider may ask. Gurgan will answer.}
{951}{}{外人可能会问。古根会回答的。}
#{952}{}{How did you get here?}
{952}{}{你怎么来的？}
#{953}{}{How do you make a living here?}
{953}{}{你怎么在这里谋生？}
#{954}{}{How do you get along with others?}
{954}{}{你和别人相处得怎么样？}
#{955}{}{I've heard you've been losing many people lately. Is it true?}
{955}{}{我听说你最近失去了很多人。是真的吗？}
#{956}{}{Actually, I don't want to know anything. Goodbye.}
{956}{}{实际上，我什么都不想知道。再见。}
#{1000}{}{[He scowls.] It is true. The tribe has lost many hunters, who have not returned from the wasteland. Gurgan does not believe that geckos killed them. Neither did burned people, for the tribe has learned how to evade their patrols. It must have been someone from the city! And when Gurgan finds the guilty, the tribe shall take its revenge. Let outsider have no doubt of that.}
{1000}{}{这是真的。这个部落失去了许多猎人，他们还没有从荒地回来。古根不相信壁虎杀死了他们。也没有烧死人，因为部落已经学会如何躲避巡逻。一定是城里人！当古尔干发现有罪的时候，部落会报仇。让外人对此毫不怀疑。}
#{1001}{}{[He scowls.] It is true. The tribe has lost many hunters, who have not returned from the wasteland. Gurgan does not believe that geckos killed them. Neither did burned people, for the tribe has learned how to evade their patrols. It must have been someone from the city! And when Gurgan finds the guilty, the tribe shall take its revenge. Let outsider have no doubt of that.}
{1001}{}{这是真的。这个部落失去了许多猎人，他们还没有从荒地回来。古根不相信壁虎杀死了他们。也没有烧死人，因为部落已经学会如何躲避巡逻。一定是城里人！当古尔干发现有罪的时候，部落会报仇。让外人对此毫不怀疑。}
#{1002}{}{I... I know who's behind that. Part of the guilt is mine. The doctors from Dead Quarter did it.}
{1002}{}{一、 。。。我知道幕后黑手是谁。一部分罪过是我的。死区的医生做的。}
#{1003}{}{I... I know who's behind that. Part of the guilt is mine. The doctors from Dead Quarter did it.}
{1003}{}{一、 。。。我知道幕后黑手是谁。一部分罪过是我的。死区的医生做的。}
#{1004}{}{Certainly. Another question.}
{1004}{}{当然。另一个问题。}
#{1005}{}{I wouldn't dream of doing that. See you later, Gurgan.}
{1005}{}{我做梦也不想那样做。再见，古根。}
#{1050}{}{Gurgan's tribe is simply trying to survive here. It avoids people of the city and hunts geckos in the wastes for a living. Gurgan knows nothing else.}
{1050}{}{古尔根的部落只是想在这里生存。它避开城里的人，在荒地里猎食壁虎为生。古尔根什么都不知道。}
#{1051}{}{Me whack gecko too!}
{1051}{}{我也打壁虎！}
#{1052}{}{Gots it. Bai!}
{1052}{}{明白了。小白！}
#{1100}{}{Why does outsider return to Gurgan? Does he need something?}
{1100}{}{外人为什么要回到古尔干？他需要什么吗？}
#{1101}{}{Why does outsider return to Gurgan? Does she need something?}
{1101}{}{外人为什么要回到古尔干？她需要什么吗？}
#{1102}{}{I wanted to ask you a few things.}
{1102}{}{我想问你几件事。}
#{1103}{}{I wanted to ask you a few things.}
{1103}{}{我想问你几件事。}
#{1104}{}{I want to go on another hunt.}
{1104}{}{我想再去打猎。}
#{1105}{}{I know who's behind ambushing your people. It's the doctors from the Dead Quarter.}
{1105}{}{我知道谁在背后伏击你的人。是死区的医生。}
#{1106}{}{I know who's behind ambushing your people. It's the doctors from the Dead Quarter.}
{1106}{}{我知道谁在背后伏击你的人。是死区的医生。}
#{1107}{}{Nothing right now. See you later.}
{1107}{}{现在什么都没有。再见。}
#{1108}{}{Uh? Wut tribe do here?}
{1108}{}{休斯敦大学？你在这儿干什么？}
#{1109}{}{Hunt!}
{1109}{}{亨特！}
#{1110}{}{More hunt!}
{1110}{}{更多的狩猎！}
#{1111}{}{ know who bad guy. Them docturs!}
{1111}{}{知道谁是坏人。他们是医生！}
#{1112}{}{Nuffin. Bai Gurgan.}
{1112}{}{努芬。白古根。}
#{1113}{}{I want to hunt.}
{1113}{}{我想打猎。}
#{1114}{}{Me hunt!}
{1114}{}{我打猎！}
#{1150}{}{Outsider acted like a coward. There is no place for him among hunters.}
{1150}{}{局外人表现得像个懦夫。他在猎人中没有立足之地。}
#{1151}{}{Outsider acted like a coward. There is no place for her among hunters.}
{1151}{}{局外人表现得像个懦夫。她在猎人中没有立足之地。}
#{1152}{}{Whatever. Bye.}
{1152}{}{无论什么。再见。}
#{1153}{}{Hue! Me go.}
{1153}{}{色调！让我走。}
#{1200}{}{Hunters told Gurgan that outsider has done well. Here is his share [He gives you }
{1200}{}{猎人告诉古尔根，外人做得很好。这是他的一份[他给你的]}
#{1201}{}{Hunters told Gurgan that outsider has done well. Here is her share [He gives you }
{1201}{}{猎人告诉古尔根，外人做得很好。这是她的一份[他给你的]}
#{1202}{}{ golden gecko skins.] And, if outsider wants, Gurgan can also teach him to to skin geckos now.}
{1202}{}{如果外人愿意，古根现在也可以教他剥壁虎皮了。}
#{1203}{}{ golden gecko skins.] And, if outsider wants, Gurgan can also teach her to to skin geckos now.}
{1203}{}{如果外人愿意，古根现在也可以教她剥壁虎皮了。}
#{1204}{}{Thanks, that should come in handy.}
{1204}{}{谢谢，那应该会派上用场的。}
#{1205}{}{Woo! Thankies.}
{1205}{}{求爱！谢谢。}
#{1250}{}{It is not too hard. You simply have to... [Gurgan shows you how to peel off a gecko skin without damaging it.] Outsider should do fine, with a bit of practice. But he must remember to let hunters skin geckos when he goes hunting with them. The spoils must be shared fairly.}
{1250}{}{这并不难。你只需要。。。[古根教你如何剥下壁虎的皮肤而不损伤它]局外人应该做得很好，需要一点练习。但他必须记住，当他和壁虎一起去打猎时，一定要让他们去剥壁虎的皮。战利品必须公平分享。}
#{1251}{}{It is not too hard. You simply have to... [Gurgan shows you how to peel off a gecko skin without damaging it.] Outsider should do fine, with a bit of practice. But she must remember to let hunters skin geckos when she goes hunting with them. The spoils must be shared fairly.}
{1251}{}{这并不难。你只需要。。。[古根教你如何剥下壁虎的皮肤而不损伤它]局外人应该做得很好，需要一点练习。但她必须记住，当她和壁虎一起去打猎时，一定要让他们去剥壁虎的皮。战利品必须公平分享。}
#{1252}{}{Got it. When can I come on another hunt?}
{1252}{}{知道了。我什么时候能再来一次狩猎？}
#{1253}{}{Don't worry, Gurgan. See you later}
{1253}{}{别担心，古根。回头见}
#{1254}{}{No worry. Bai!}
{1254}{}{不用担心。小白！}
#{1300}{}{Outsider must wait, it is not the right time yet. He should come back later.}
{1300}{}{外人必须等待，现在还不是时候。他应该晚点回来。}
#{1301}{}{Outsider must wait, it is not the right time yet. She should come back later.}
{1301}{}{外人必须等待，现在还不是时候。她应该晚点回来。}
#{1302}{}{Alright. Bye for now, Gurgan.}
{1302}{}{好吧。再见，古根。}
#{1303}{}{Okies.}
{1303}{}{好的。}
#{1350}{}{Gurgan's hunters are ready. They can go right now.}
{1350}{}{古尔根的猎人们准备好了。他们现在可以走了。}
#{1351}{}{Let's go then.}
{1351}{}{那我们走吧。}
#{1352}{}{Actually, I've changed my mind. Forget about it.}
{1352}{}{实际上，我改变主意了。算了吧。}
#{1353}{}{Actually, I've changed my mind. Forget about it.}
{1353}{}{实际上，我改变主意了。算了吧。}
#{1354}{}{We gooo!}
{1354}{}{我们太棒了！}
#{1355}{}{Eh, no now. Seeya.}
{1355}{}{呃，现在不行。再见。}
#{1400}{}{Gurgan is pleased with outsider. The skins will help the tribe much. Especially now that it has suffered another painful blow. While outsider was gone, another hunting party was lost. Gurgan fears for poor hunters. Only ancestors know what happened to them. [He sighs heavily.] But Gurgan should not worry outsider with that. Here is his share. [He gives you }
{1400}{}{古尔根对外人很满意。这些皮对部落很有帮助。尤其是现在它又遭受了一次痛苦的打击。当外人不在的时候，另一个狩猎队也不见了。古根害怕可怜的猎人。只有祖先知道他们的遭遇。[他沉重地叹了口气]但古根不应该让外人担心。这是他的一份。[他给了你}
#{1401}{}{Gurgan is pleased with outsider. The skins will help the tribe much. Especially now that it has suffered another painful blow. While outsider was gone, another hunting party was lost. Gurgan fears for poor hunters. Only ancestors know what happened to them. [He sighs heavily.] But Gurgan should not worry outsider with that. Here is her share. [He gives you }
{1401}{}{古尔根对外人很满意。这些皮对部落很有帮助。尤其是现在它又遭受了一次痛苦的打击。当外人不在的时候，另一个狩猎队也不见了。古根害怕可怜的猎人。只有祖先知道他们的遭遇。[他沉重地叹了口气]但古根不应该让外人担心。这是她的份。[他给了你}
#{1402}{}{Gurgan is pleased with outsider. Here is his share [He gives you }
{1402}{}{古尔根对外人很满意。这是他的一份[他给你的]}
#{1403}{}{Gurgan is pleased with outsider. Here is her share [He gives you }
{1403}{}{古尔根对外人很满意。这是她的一份[他给你的]}
#{1404}{}{ golden gecko skins.]}
{1404}{}{金壁虎皮。]}
#{1405}{}{Thanks, when is the next hunt?}
{1405}{}{谢谢，下一次狩猎是什么时候？}
#{1406}{}{Thanks for that. See you later, Gurgan.}
{1406}{}{谢谢你。再见，古根。}
#{1407}{}{Me thanks! Bai bai.}
{1407}{}{谢谢你！白白。}
#{1450}{}{Gurgan has heard what happened on the hunt. He is angry. And he has no doubt that people of the city are behind it. They have hated the tribe since the beginning. Does outsider know which one of them is guilty?}
{1450}{}{古尔根听说了狩猎的事。他很生气。他毫不怀疑城市里的人是幕后黑手。他们从一开始就憎恨这个部落。外人知道他们中谁有罪吗？}
#{1451}{}{Gurgan has heard what happened on the hunt. He is angry. And he has no doubt that people of the city are behind it. They have hated the tribe since the beginning. Does outsider know which one of them is guilty?}
{1451}{}{古尔根听说了狩猎的事。他很生气。他毫不怀疑城市里的人是幕后黑手。他们从一开始就憎恨这个部落。外人知道他们中谁有罪吗？}
#{1452}{}{Not yet, but I intend to find out. Those bastards tried to kill me. I must know who they are.}
{1452}{}{还没有，但我想知道。那些混蛋想杀了我。我必须知道他们是谁。}
#{1453}{}{Nopes! But look!}
{1453}{}{不！但是你看！}
#{1500}{}{Outsider is doing the right thing. Gurgan knows he will find out who did this. And when that happens, the tribe will take its revenge.}
{1500}{}{局外人在做正确的事。古根知道他会查出是谁干的。当这种情况发生时，部落会报仇。}
#{1501}{}{Outsider is doing the right thing. Gurgan knows he will find out who did this. And when that happens, the tribe will take its revenge.}
{1501}{}{局外人在做正确的事。古根知道他会查出是谁干的。当这种情况发生时，部落会报仇。}
#{1502}{}{I take you for your word. I'll be back, Gurgan.}
{1502}{}{我相信你的话。我会回来的，古根。}
#{1503}{}{Okies!}
{1503}{}{好的！}
#{1550}{}{If outsider is telling the truth, then they must pay with their blood. No one shall be spared! Gurgan will go and gather all hunters for attack.}
{1550}{}{如果外人说的是真话，那么他们必须付出血债。谁也不能幸免！古尔根会去召集所有的猎人来进攻。}
#{1551}{}{If outsider is telling the truth, then they must pay with their blood. No one shall be spared! Gurgan will go and gather all hunters for attack.}
{1551}{}{如果外人说的是真话，那么他们必须付出血债。谁也不能幸免！古尔根会去召集所有的猎人来进攻。}
#{1552}{}{Count me in. I'm not leaving you alone in this.}
{1552}{}{把我算进去。我不会把你一个人留在这里。}
#{1553}{}{Count me in. I owe you that much.}
{1553}{}{把我算进去。我欠你那么多。}
#{1554}{}{Hold on, Gurgan. You'd be sending your people to certain death. They can't succeed against the doctors' mercenaries, at least not without some support.}
{1554}{}{等等，古根。你会送你的人去死的。他们不可能成功对抗医生的雇佣兵，至少没有一些支持。}
#{1555}{}{Well, if you say so. Good luck.}
{1555}{}{好吧，如果你这么说的话。祝你好运。}
#{1556}{}{That won't be necessary. I already took care of them.}
{1556}{}{那没必要。我已经照顾好他们了。}
#{1557}{}{That won't be necessary. I already took care of them.}
{1557}{}{那没必要。我已经照顾好他们了。}
#{1558}{}{Me go smash too!}
{1558}{}{我也去砸！}
#{1559}{}{Eh... bai then.}
{1559}{}{呃。。。那就去吧。}
#{1560}{}{Nooo! }
{1560}{}{不！}
#{1561}{}{ crush bad guy already.}
{1561}{}{我已经杀了坏人了。}
#{1600}{}{Outsider underestimates the tribe. Does he even know of anyone who would support us?}
{1600}{}{局外人低估了这个部落。他知道有谁会支持我们吗？}
#{1601}{}{Outsider underestimates the tribe. Does he even know of anyone who would support us?}
{1601}{}{局外人低估了这个部落。他知道有谁会支持我们吗？}
#{1602}{}{Maybe I'll find someone. Just wait with the attack for a bit.}
{1602}{}{也许我会找到人。等一下攻击。}
#{1603}{}{I guess you're right. Let's face them on our own.}
{1603}{}{我想你是对的。让我们自己面对他们。}
#{1604}{}{Not really. Well, do whatever you want, it's none of my business anyway.}
{1604}{}{不是真的。好吧，随你怎么做，反正不关我的事。}
#{1650}{}{[He thinks for a while.] Alright, Gurgan will wait, but not longer than three days. The tribe must take revenge soon.}
{1650}{}{[他想了一会儿]好吧，古根会等的，但不会超过三天。部落必须尽快复仇。}
#{1651}{}{I'll see what I can do. Bye for now, Gurgan.}
{1651}{}{我看看我能做什么。再见，古根。}
#{1700}{}{Has outsider been successful? Gurgan cannot wait much longer.}
{1700}{}{外人成功了吗？古尔根不能再等了。}
#{1701}{}{Has outsider been successful? Gurgan cannot wait much longer.}
{1701}{}{外人成功了吗？古尔根不能再等了。}
#{1702}{}{Everything is taken care of. The imperial soldiers will be joining the attack.}
{1702}{}{一切都搞定了。帝国士兵将加入进攻。}
#{1703}{}{Nope, sorry. No help is coming.}
{1703}{}{不，对不起。没有人来帮忙。}
#{1704}{}{I'm working on it.}
{1704}{}{我正在努力。}
#{1705}{}{Uh.}
{1705}{}{休斯敦大学。}
#{1750}{}{In that case, there is no time to lose. Gurgan will go and gather all hunters right now.}
{1750}{}{那样的话，就没时间浪费了。古尔根马上去召集所有的猎人。}
#{1751}{}{You can count me in, too. No way I'm missing on that.}
{1751}{}{你也可以把我算进去。我不会错过的。}
#{1752}{}{You can count me in, too. I'm not leaving you alone in this.}
{1752}{}{你也可以把我算进去。我不会把你一个人留在这里。}
#{1753}{}{If you say so, Gurgan. Good luck.}
{1753}{}{如果你这么说的话，古根。祝你好运。}
#{1800}{}{Outsider has shown great courage. From now on, he is forever tribe friend. Gurgan wishes to show his thanks. [He gives you five golden gecko skins.] Gurgan also sees that friend has a dog. Gurgan is very good at training dogs, he has been training them for years and he can make great hunters of them. If friend wishes, he could train his dog as well. All he needs is one day.}
{1800}{}{局外人表现出了极大的勇气。从现在起，他是永远的朋友。古尔根表示感谢。[他给了你五张金壁虎皮]古根还看到他的朋友有一条狗。古尔根很擅长训练狗，他已经训练狗很多年了，他可以成为伟大的猎手。如果朋友愿意，他也可以训练他的狗。他只需要一天。}
#{1801}{}{Outsider has shown great courage. From now on, he is forever tribe friend. Gurgan wishes to show his thanks. [He gives you five golden gecko skins.] Gurgan also sees that friend has a dog. Gurgan is very good at training dogs, he has been training them for years and he can make great hunters of them. If friend wishes, he could train her dog as well. All he needs is one day.}
{1801}{}{局外人表现出了极大的勇气。从现在起，他是永远的朋友。古尔根表示感谢。[他给了你五张金壁虎皮]古根还看到他的朋友有一条狗。古尔根很擅长训练狗，他已经训练狗很多年了，他可以成为伟大的猎手。如果朋友愿意，他也可以训练她的狗。他只需要一天。}
#{1802}{}{Outsider has shown great courage. From now on, he is forever tribe friend. Gurgan wishes to show his thanks. [He gives you five golden gecko skins.] He values friend's help greatly.}
{1802}{}{局外人表现出了极大的勇气。从现在起，他是永远的朋友。古尔根表示感谢。[他给你五张金壁虎皮]他非常珍惜朋友的帮助。}
#{1803}{}{Outsider has shown great courage. From now on, he is forever tribe friend. Gurgan wishes to show his thanks. [He gives you five golden gecko skins.] He values friend's help greatly.}
{1803}{}{局外人表现出了极大的勇气。从现在起，他是永远的朋友。古尔根表示感谢。[他给你五张金壁虎皮]他非常珍惜朋友的帮助。}
#{1804}{}{Thanks, a bit of training would do him some good. Just make sure nothing happens to him. I'll come back for him tomorrow.}
{1804}{}{谢谢，训练一下对他有好处。确保他不会出事。我明天回来接他。}
#{1805}{}{Sorry, I'll have to decline for now. Mutt stays with me. Farewell, Gurgan.}
{1805}{}{对不起，我现在不得不拒绝。穆特和我在一起。再见，古根。}
#{1806}{}{I was glad to help.}
{1806}{}{我很乐意帮忙。}
#{1807}{}{I was glad to help.}
{1807}{}{我很乐意帮忙。}
#{1808}{}{Okies, give Mutt. Bai.}
{1808}{}{好的，把羊肉给我。白。}
#{1809}{}{No take Mutt! Bai Gurgan.}
{1809}{}{不，带上小狗！白古根。}
#{1810}{}{Thanks you. Bai.}
{1810}{}{谢谢你。白。}
#{1850}{}{Friend's dog is very smart. Gurgan taught him everything he knew. He will be useful in battle.}
{1850}{}{朋友的狗很聪明。古根教了他所知道的一切。他在战斗中会有用的。}
#{1851}{}{Friend's dog is very smart. Gurgan taught him everything he knew. He will be useful in battle.}
{1851}{}{朋友的狗很聪明。古根教了他所知道的一切。他在战斗中会有用的。}
#{1852}{}{Thanks Gurgan, I appreciate it. I'll take Mutt back then.}
{1852}{}{谢谢古根，我很感激。那我就把穆特带回去。}
#{1853}{}{Thank mucho!}
{1853}{}{谢谢你！}
#{1900}{}{Gurgan greets tribe friend. He is glad to see him again.}
{1900}{}{古尔根问候部落的朋友。他很高兴再次见到他。}
#{1901}{}{Gurgan greets tribe friend. He is glad to see her again.}
{1901}{}{古尔根问候部落的朋友。他很高兴再次见到她。}
#{1902}{}{So am I, Gurgan. Farewell.}
{1902}{}{我也是，古根。再会。}
#{1903}{}{I've changed my mind about your offer, a little training would do Mutt some good. But nothing must happen to him, OK?.}
{1903}{}{我对你的提议改变了主意，稍加训练会有好处的。但他不能出什么事，好吗？。}
#{1904}{}{I've changed my mind about your offer, a little training would do Mutt some good. But nothing must happen to him, OK?.}
{1904}{}{我对你的提议改变了主意，稍加训练会有好处的。但他不能出什么事，好吗？。}
#{1905}{}{Hi Gurgan.}
{1905}{}{嗨，古根。}
#{1906}{}{ leave Mutt here. Gurgan train.}
{1906}{}{把穆特留在这里。古尔干火车。}
#{1950}{}{No hunter has returned. The whole tribe grieves their loss. Gurgan chose poorly when he let outsider come. He brought only misfortune. Gurgan will not let him on another hunt.}
{1950}{}{没有猎人回来。整个部落都为他们的损失而悲痛。古尔根让外人来的时候选择得很差。他带来的只是不幸。古根不会让他再去打猎了。}
#{1951}{}{No hunter has returned. The whole tribe grieves their loss. Gurgan chose poorly when he let outsider come. She brought only misfortune. Gurgan will not let her on another hunt.}
{1951}{}{没有猎人回来。整个部落都为他们的损失而悲痛。古尔根让外人来的时候选择得很差。她带来的只是不幸。古根不会让她再去打猎了。}
#{1952}{}{Whatever. Goodbye.}
{1952}{}{无论什么。再见。}
#{1953}{}{Hue! Me gone.}
{1953}{}{色调！我走了。}
#{2000}{}{Gurgan greets tribe friend. He is glad to see him again. Gurgan also sees that friend has a dog. Gurgan is very good at training dogs, he has been training them for years and he can make great hunters of them. If friend wishes, he could train his dog as well. All he needs is one day.}
{2000}{}{古尔根问候部落的朋友。他很高兴再次见到他。古根还看到他的朋友养了一条狗。古尔根很擅长训练狗，他已经训练狗很多年了，他可以成为伟大的猎手。如果朋友愿意，他也可以训练他的狗。他只需要一天。}
#{2001}{}{Gurgan greets tribe friend. He is glad to see her again. Gurgan also sees that friend has a dog. Gurgan is very good at training dogs, he has been training them for years and he can make great hunters of them. If friend wishes, he could train her dog as well. All he needs is one day.}
{2001}{}{古尔根问候部落的朋友。他很高兴再次见到她。古根还看到他的朋友养了一条狗。古尔根很擅长训练狗，他已经训练狗很多年了，他可以成为伟大的猎手。如果朋友愿意，他也可以训练她的狗。他只需要一天。}
#{2002}{}{Thanks, a bit of training would do him some good. Just make sure nothing happens to him. I'll come back for him tomorrow.}
{2002}{}{谢谢，训练一下对他有好处。确保他不会出事。我明天回来接他。}
#{2003}{}{Sorry, I'll have to decline for now. Mutt stays with me. Farewell, Gurgan.}
{2003}{}{对不起，我现在不得不拒绝。穆特和我在一起。再见，古根。}
#{2004}{}{Okies, give Mutt. Bai.}
{2004}{}{好的，把羊肉给我。白。}
#{2005}{}{No take Mutt! Bai Gurgan.}
{2005}{}{不，带上小狗！白古根。}
#{2050}{}{Friend made the right decision. He can come back for the dog in a day.}
{2050}{}{朋友做了正确的决定。他一天之内就可以回来找狗了。}
#{2051}{}{Friend made the right decision. She can come back for the dog in a day.}
{2051}{}{朋友做了正确的决定。她一天之内就可以回来取狗了。}
#{2052}{}{OK.}
{2052}{}{好 啊。}
#{2053}{}{Hu.}
{2053}{}{胡。}
#{2100}{}{No hunter has returned. The whole tribe grieves their loss. Gurgan does not believe geckos could have done this. Hunters and outsider were strong enough to defeat them. He must know what happened.}
{2100}{}{没有猎人回来。整个部落都为他们的损失而悲痛。古根不相信壁虎会这样做。猎人和外人都很强大，足以打败他们。他一定知道发生了什么。}
#{2101}{}{No hunter has returned. The whole tribe grieves their loss. Gurgan does not believe geckos could have done this. Hunters and outsider were strong enough to defeat them. He must know what happened.}
{2101}{}{没有猎人回来。整个部落都为他们的损失而悲痛。古根不相信壁虎会这样做。猎人和外人都很强大，足以打败他们。他一定知道发生了什么。}
#{2102}{}{You're right, we were ambushed. I don't know who it was, but they were well prepared. They must've been waiting for us.}
{2102}{}{你说得对，我们被伏击了。我不知道是谁，但他们准备得很好。他们一定在等我们。}
#{2103}{}{Strange peoples boom! Wham! Too many!}
{2103}{}{奇怪的人！哇！太多了！}
#{2150}{}{[He scowls.] Gurgan has no doubt that people of the city are being it. They have hated the tribe since the beginning. But which one of them could have done this?}
{2150}{}{[他愁眉不展]古尔根毫不怀疑这个城市的人们正在接受它。他们从一开始就憎恨这个部落。但他们中谁会这么做？}
#{2151}{}{I intend to find out. Those bastards tried to kill me. I must know who they are.}
{2151}{}{我想知道。那些混蛋想杀了我。我必须知道他们是谁。}
#{2152}{}{}
{2152}{}{}
#{2153}{}{ go look bad guy!}
{2153}{}{去看看坏人！}
#{2200}{}{Gurgan has heard that someone killed doctors. The attack will not be needed now.}
{2200}{}{古根听说有人杀了医生。现在不需要攻击了。}
#{2201}{}{I know. It was me.}
{2201}{}{我知道。是我。}
#{2202}{}{I know. It was me.}
{2202}{}{我知道。是我。}
#{2203}{}{Wuz me! Me crush them!}
{2203}{}{哇我！让我压扁他们！}
#{2250}{}{Outsider can come back in a day. That is when another hunt begins.}
{2250}{}{外人一天就能回来。那是另一场狩猎开始的时候。}
#{2251}{}{Outsider can come back in a day. That is when another hunt begins.}
{2251}{}{外人一天就能回来。那是另一场狩猎开始的时候。}
#{2252}{}{Alright. See you, Gurgan.}
{2252}{}{好吧。再见，古根。}
#{2300}{}{When outsider helped Mutant Hunters take away Kuggar, he has made an enemy of the tribe. Gurgan does not want to see him here ever again.}
{2300}{}{当外人帮助变种猎人带走库加尔时，他已成为部落的敌人。古根不想再在这里见到他。}
#{2301}{}{When outsider helped Mutant Hunters take away Kuggar, she has made an enemy of the tribe. Gurgan does not want to see her here ever again.}
{2301}{}{当外人帮助变种猎人带走库加尔时，她已成为部落的敌人。古根不想再在这里见到她。}
#{2302}{}{When outsider killed Kuggar and his brothers, he has made an enemy of the tribe. Gurgan does not want to see him here ever again.}
{2302}{}{当外人杀了库加尔和他的兄弟，他已经成为部落的敌人。古根不想再在这里见到他。}
#{2303}{}{When outsider killed Kuggar and his brothers, she has made an enemy of the tribe. Gurgan does not want to see her here ever again.}
{2303}{}{当外人杀了库加尔和他的兄弟，她已经成为部落的敌人。古根不想再在这里见到她。}
#{2304}{}{Calm down, I just want to ask you a question, nothing more. I've heard you've been losing many people lately. Is it true?}
{2304}{}{冷静点，我只想问你一个问题，没别的。我听说你最近失去了很多人。是真的吗？}
#{2305}{}{I'm not going anywhere! What are you going to do about it?}
{2305}{}{我哪儿也不去！你打算怎么办？}
#{2306}{}{As you wish. Farewell, Gurgan.}
{2306}{}{如你所愿。再见，古根。}
#{2307}{}{Uh.}
{2307}{}{休斯敦大学。}
#{2350}{}{[He scowls.] Gurgan will answer the question. But then outsider will leave. It is true. The tribe has lost many hunters, who have not returned from the wasteland. Gurgan does not believe that geckos killed them. Neither did burned people, for the tribe has learned how to evade their patrols. It must have been someone from the city! [He glares at you.] If Gurgan finds out that Mutant Hunters are responsible, then they will know the fury of the tribe. Let outsider have no doubt of that.}
{2350}{}{[他愁眉不展]古根会回答这个问题。但外人会离开。这是真的。这个部落失去了许多猎人，他们还没有从荒地回来。古根不相信壁虎杀死了他们。也没有烧死人，因为部落已经学会如何躲避巡逻。一定是城里人！[他瞪着你]如果古根发现变种猎人是凶手，那么他们就会知道部落的愤怒。让外人对此毫不怀疑。}
#{2351}{}{[He scowls.] Gurgan will answer the question. But then outsider will leave. It is true. The tribe has lost many hunters, who have not returned from the wasteland. Gurgan does not believe that geckos killed them. Neither did burned people, for the tribe has learned how to evade their patrols. It must have been someone from the city! [He glares at you.] If Gurgan finds out that Mutant Hunters are responsible, then they will know the fury of the tribe. Let outsider have no doubt of that.}
{2351}{}{[他愁眉不展]古根会回答这个问题。但外人会离开。这是真的。这个部落失去了许多猎人，他们还没有从荒地回来。古根不相信壁虎杀死了他们。也没有烧死人，因为部落已经学会如何躲避巡逻。一定是城里人！[他瞪着你]如果古根发现变种猎人是凶手，那么他们就会知道部落的愤怒。让外人对此毫不怀疑。}
#{2352}{}{I'm shaking. Bye, Gurgan.}
{2352}{}{我在发抖。再见，古根。}
