#{100}{}{You see an information robot.}
{100}{}{你看到一个信息机器人。}
#{200}{}{You see one of information robots slowly moving through the streets.}
{200}{}{你看到一个信息机器人在街上慢慢移动。}
#{500}{}{[The robot pays you no attention and continues to move along the set route. Its central processing unit is currently in energy-saving mode; a direct interaction is required to fully start it up.]}
{500}{}{[机器人不理会你，继续沿着设定的路线移动。其中央处理器目前处于节能模式；需要直接交互才能完全启动。]}
#{501}{}{[The robot pays you no attention and continues to move along the set route. Since it doesn't seem damaged, it's possible that not all its function are online. Talking to the robot directly should be enough to turn it back on.]}
{501}{}{[机器人不理会你，继续沿着设定的路线移动。因为它看起来没有损坏，所以可能不是所有的功能都在线。与机器人直接交谈应该足以使其重新启动。]}
#{502}{}{[The robot pays you no attention and continues to move the along way. It's probably broken.]}
{502}{}{[机器人不理会你，继续沿途移动。它可能坏了}
#{503}{}{Wait, robot. I want to talk to you.}
{503}{}{等等，机器人。我想和你谈谈。}
#{504}{}{[Leave it alone.]}
{504}{}{[别管它。]}
#{505}{}{Hrmm... bah-roken!}
{505}{}{嗯。。。巴罗肯！}
#{550}{}{[The robot reacts to being addressed and turns in your direction. Concurrently, it activates both its mechanical arms and starts searching its storage compartment containing a wealth of cassette tapes. After a short while, it takes one of them and inserts it into the record player in his chest. You hear a high-pitched male voice.] I wish you a pleasant day. I am an information robot programmed to answer questions pertaining to the empire. May I assist you?}
{550}{}{[机器人对你的地址做出反应，朝你的方向转动。同时，它启动了它的两个机械臂，开始搜索它的储藏室，里面有大量的盒式磁带。过了一会儿，它采取了其中一个，并插入到他的胸口录音机。你听到一个高亢的男声]祝你一天愉快。我是一个信息机器人，可以回答有关帝国的问题。我能帮你吗？}
#{551}{}{You certainly may. I have many questions.}
{551}{}{你当然可以。我有很多问题。}
#{552}{}{I don't think so. Bye.}
{552}{}{我不这么认为。再见。}
#{600}{}{[The robot continues to play the tape.] It will be my pleasure to answer your questions. What do you wish to know, specifically? [When the tape finishes, the robot puts it back among the others.]}
{600}{}{[机器人继续播放磁带]我很乐意回答你的问题。你具体想知道什么？[当磁带结束时，机器人将其放回其他磁带中。]}
#{601}{}{I'd like to know who's the ruler of the Imperial City.}
{601}{}{我想知道谁是皇城的统治者。}
#{602}{}{I'd like to know who's the ruler of the Imperial City.}
{602}{}{我想知道谁是皇城的统治者。}
#{603}{}{Tell me about the local vault.}
{603}{}{告诉我当地的保险库。}
#{604}{}{I was curious how the empire gets along with neighboring groups.}
{604}{}{我很好奇帝国是如何与邻国相处的。}
#{605}{}{Tell me where I can find a merchant around here.}
{605}{}{告诉我这附近哪里有商人。}
#{606}{}{I wanted to ask what rules are there for foreigners.}
{606}{}{我想问外国人有什么规矩。}
#{607}{}{I need to know everything you can tell me about Anonym.}
{607}{}{我要知道你能告诉我的关于匿名的一切。}
#{608}{}{I need to know about emperor Aran's ascension to the throne.}
{608}{}{我要知道阿兰皇帝登基的事。}
#{609}{}{I need to know about empress Elisa's ascension to the throne.}
{609}{}{我要知道伊利莎皇后登基的事。}
#{610}{}{Nothing, actually. I need to go.}
{610}{}{其实没什么。我得走了。}
#{650}{}{[The robot picks one of the tapes and inserts it into the record player.] The monarchy is ruled by the emperor and a three-member adviser council. It has been so since the beginning of the empire, which was established by the last overseer in accordance with the wishes of the dwellers. The current ruler is his brother, the wise emperor Myzrael. Adviser Elisa and adviser Aran help him with the heavy burden of leadership. Beldir, the third adviser, has passed away recently, and his successor has not yet been determined.}
{650}{}{[机器人挑选其中一盘磁带并将其插入唱机。]君主制由皇帝和一个三人顾问委员会统治。从帝国建立之初就一直如此，帝国是由最后一位督察按照居民的意愿建立的。现任统治者是他的兄弟，智慧的皇帝米兹雷尔。伊莉莎顾问和阿兰顾问帮助他承担起领导的重任。第三位顾问贝尔迪尔最近去世，他的继任者尚未确定。}
#{651}{}{Got it. There's something else I want to ask.}
{651}{}{知道了。我还有别的事要问。}
#{652}{}{That will be all. I'm leaving.}
{652}{}{就这些了。我要走了。}
#{700}{}{[The robot picks one of the tapes and inserts it into the record player.] Vault number 16 is located below the imperial palace. In it, the ancestors of the current dwellers found refuge during a time when radioactive doom made life on the surface impossible. Due to an administrative error, two people were given the role of the overseer. A large group of followers formed under each of them, and these groups frequently clashed. Over time, the clashes intensified so much that the vault nearly stood at the brink of a civil war. The threat of war, however, was averted at the last moment by an agreement made between the two overseers. The vault protected its dwellers for the next sixty years, until the decision to leave was made. Today, it is used for research and defense, which must be done in secret to ensure the safety of the empire.}
{700}{}{[机器人拿起其中一盘磁带插入唱机]16号金库位于故宫下方。在那里，现在居民的祖先们找到了避难所，当时放射性灾难使地表上的生命变得不可能。由于一个行政错误，两个人被任命为监督员。一大群追随者在他们下面形成，这些团体经常发生冲突。随着时间的推移，冲突愈演愈烈，金库几乎处于内战的边缘。然而，在最后一刻，两位监工达成了一项协议，避免了战争的威胁。金库在接下来的六十年里一直保护着这里的居民，直到他们决定离开。今天，它被用于研究和防御，这必须秘密进行，以确保帝国的安全。}
#{701}{}{Good to know. There's something else I want to ask.}
{701}{}{很高兴知道。我还有别的事要问。}
#{702}{}{I have to go now. Goodbye.}
{702}{}{我得走了。再见。}
#{750}{}{[The robot picks one of the tapes and inserts it into the record player.] The imperial dwellers feel no need to associate with people from the wasteland. They've always tried to keep their distance, and this conviction was only strengthened after the massive ghoul attack. The outside world cannot bring anything good for the City. The only contacts with the outside world is a contractual relation with the Mutant Hunters and a number of foreign traders for exchanging of goods.}
{750}{}{[机器人拿起其中一盘磁带，插入唱机]帝国居民觉得没有必要与来自荒地的人交往。他们一直试图保持距离，这一信念在大规模僵尸袭击后才得到加强。外界不能给城市带来任何好处。与外界的唯一联系是与变种猎人和一些外国商人交换货物的合同关系。}
#{751}{}{The Imperial City was attacked by ghouls?}
{751}{}{皇城被僵尸袭击了？}
#{752}{}{Contractual relations with the Hunters? Tell me more about that.}
{752}{}{与猎人的合同关系？告诉我更多。}
#{753}{}{Tell me what the empire trades with?}
{753}{}{告诉我帝国用什么交易？}
#{754}{}{There's something else I want to ask.}
{754}{}{我还有别的事要问。}
#{755}{}{That will be all. Goodbye.}
{755}{}{就这些了。再见。}
#{800}{}{[The robot changes the tape.] The great ghoul attack was the worst thing that's ever happened to the City. Many good, loyal soldiers fell or suffered grievous wounds. The empire had to use all its might to save itself. Consequences of that terrible battle are still apparent even today.}
{800}{}{[机器人换了磁带]僵尸的袭击是这座城市发生过的最糟糕的事情。许多忠心耿耿的好士兵倒下或受重伤。帝国不得不动用一切力量来拯救自己。即使在今天，那场可怕战斗的后果仍然显而易见。}
#{801}{}{Tell me about the contractual relation with the Hunters.}
{801}{}{告诉我和猎人的合同关系。}
#{802}{}{Now tell me what the empire trades with.}
{802}{}{现在告诉我帝国用什么交易。}
#{803}{}{I see. There's something else I want to ask.}
{803}{}{我懂了。我还有别的事要问。}
#{804}{}{I don't need to know anything else. Bye.}
{804}{}{我不需要知道任何其他事情。再见。}
#{850}{}{[The robot changes the tape.] The imperial army was greatly weakened after the massive ghoul attack. That's why a contract was made with the Mutant Hunter faction. Emperor Myzrael gave them the materials necessary for the construction of their base, and in return he expected them to clear the surrounding desert of the ghoul menace. But the Hunters have been lax in their mission. During the next attack, they even let the ghouls reach the walls of the City itself. It was only the discipline of the imperial soldiers that proved to be the decisive factor in victory again. Despite this, the Hunters still dare make demands on the empire. Were it not for the emperor's foresight, their growing greed would've surely bankrupted the City.}
{850}{}{[机器人换了磁带]在大规模的僵尸袭击之后，帝国军队被大大削弱了。这就是为什么和变异猎人派签订了合同。米兹雷尔皇帝给了他们建造基地所需的材料，作为回报，他希望他们清除周围沙漠中的僵尸威胁。但是猎人们在他们的任务中一直很松懈。在下一次袭击中，他们甚至让僵尸爬上了城墙。只有帝国士兵的纪律才再次证明是胜利的决定性因素。尽管如此，猎人们仍然敢于向帝国提出要求。如果不是皇帝的远见，他们日益增长的贪婪肯定会使这座城市破产。}
#{851}{}{I'd like to hear more about the ghoul attack.}
{851}{}{我想听听更多关于僵尸袭击的消息。}
#{852}{}{I'd like to hear more about the ghoul attack.}
{852}{}{我想听听更多关于僵尸袭击的消息。}
#{853}{}{Now tell me what the empire trades with.}
{853}{}{现在告诉我帝国用什么交易。}
#{854}{}{There's something else I want to ask.}
{854}{}{我还有别的事要问。}
#{855}{}{That will be all. Goodbye.}
{855}{}{就这些了。再见。}
#{900}{}{[The robot changes the tape.] The empire trades some of its technologies which can be safely used even in the outlying villages. In return, the empire receives several varieties of food and scarce goods. It is a mutually beneficial trade.}
{900}{}{[机器人换磁带]帝国交换了一些技术，这些技术甚至可以在偏远的村庄安全使用。作为回报，帝国获得了多种多样的食物和稀有商品。这是一种互利的贸易。}
#{901}{}{Go back to the ghoul attack. I want to hear more about that.}
{901}{}{回到僵尸的攻击。我想多听听。}
#{902}{}{Tell me about the contractual relation with the Hunters.}
{902}{}{告诉我和猎人的合同关系。}
#{903}{}{Certainly. There's something else I want to ask.}
{903}{}{当然。我还有别的事要问。}
#{904}{}{I have no other questions. Goodbye.}
{904}{}{我没有其他问题。再见。}
#{950}{}{[The robot inserts another tape into the record player.] The appointed supply administrator is responsible for trade. The administrator's office is located in the building across the street from the southern end of the imperial palace.}
{950}{}{[机器人将另一盘磁带插入录音机。]指定的供应管理员负责交易。行政官办公室位于故宫南端街对面的大楼里。}
#{951}{}{I wanted to ask about something else.}
{951}{}{我想问些别的事。}
#{952}{}{I don't need to know anything else. Bye.}
{952}{}{我不需要知道任何其他事情。再见。}
#{1000}{}{[The robot inserts another tape into the record player.] In the interests of the safety of the empire, the rules set for foreigners must be strict. They can only enter the City with an official invitation from one of the dwellers, and they shall be observed for the whole length of their stay by patrolling soldiers. They are expected to behave properly; the empire does not appreciate foreigners walking around the City with weapons drawn or bothering the dwellers. The foreigner should take care of his business as soon as possible and leave.}
{1000}{}{为了帝国的安全，对外国人的规定必须严格。他们只有在一个居民的正式邀请下才能进城，并由巡逻兵全程观察。人们期望他们举止得体；帝国不喜欢外国人拿着武器在城市里走来走去，也不喜欢骚扰居民。外国人应该尽快处理好自己的事情，然后离开。}
#{1001}{}{Is it possible for a foreigner to become one of the dwellers?}
{1001}{}{外国人有可能成为居民之一吗？}
#{1002}{}{What if a foreigner breaks the rules?}
{1002}{}{如果一个外国人违反了规则怎么办？}
#{1003}{}{I'll try. I had other questions.}
{1003}{}{我试试看。我还有其他问题。}
#{1004}{}{I have no other questions. Goodbye.}
{1004}{}{我没有其他问题。再见。}
#{1050}{}{[The robot rewinds part of the tape and plays it again.] The empire can only be a home to those that were born in it. Foreigners are not allowed to become part of the empire, as admitting them could threaten the old world values it is trying to uphold.}
{1050}{}{[机器人倒带一部分磁带并再次播放。]帝国只能是在其中出生的人的家。外国人不允许成为帝国的一部分，因为承认他们可能会威胁到它试图维护的旧世界价值观。}
#{1051}{}{What if a foreigner breaks the rules?}
{1051}{}{如果一个外国人违反了规则怎么办？}
#{1052}{}{Sure. I wanted to ask about something else.}
{1052}{}{当然。我想问些别的事。}
#{1053}{}{That will be all. I'm leaving.}
{1053}{}{就这些了。我要走了。}
#{1100}{}{[The robot rewinds part of the tape and plays it again.] Should the foreigner act aggressively, the information robots are well equipped to terminate him. The imperial soldiers will also not hesitate to intervene if necessary.}
{1100}{}{[机器人倒回部分磁带并再次播放。]如果外国人表现出攻击性，信息机器人会很好地终止他。如果有必要，帝国士兵也会毫不犹豫地进行干预。}
#{1101}{}{Is it possible for a foreigner to become one of the dwellers?}
{1101}{}{外国人有可能成为居民之一吗？}
#{1102}{}{I wanted to ask about something else.}
{1102}{}{我想问些别的事。}
#{1103}{}{I have no other questions. Goodbye.}
{1103}{}{我没有其他问题。再见。}
#{1150}{}{[It takes the robot a while before he finds the right tape.] Anonym is a dangerous terrorist that has committed many heinous crimes. His only goal is to overthrow the emperor and institute his own tyrant government. But there is no need to be concerned. Appropriate measures have been taken and we are searching for him extensively. There can be no doubt that he will soon be arrested and punished accordingly.}
{1150}{}{[机器人需要一段时间才能找到合适的磁带。]匿名者是一个危险的恐怖分子，犯下了许多令人发指的罪行。他唯一的目标就是推翻皇帝，建立自己的暴政。但没必要担心。已采取适当措施，我们正在广泛搜寻他。毫无疑问，他很快就会被逮捕并受到相应的惩罚。}
#{1151}{}{I wouldn't be so sure about that. There's something else I want to ask.}
{1151}{}{我不太确定。我还有别的事要问。}
#{1152}{}{I wouldn't be so sure about that. There's something else I want to ask.}
{1152}{}{我不太确定。我还有别的事要问。}
#{1153}{}{I don't need to know anything else. Bye.}
{1153}{}{我不需要知道任何其他事情。再见。}
#{1200}{}{[The robot selects a newer-looking tape.] The new emperor has ascended to the throne under grave circumstances. Adviser Elisa took advantage of her station and, using the identity of Anonym that she created, attempted a coup. She murdered emperor Myzrael, as well as a number of loyal soldiers that resisted. But her plan to take control of the empire was foiled at the last moment by adviser Aran. Leading a brave attack, he managed to breach into the palace with a group of faithful soldiers and kill the traitor Elisa. As Myzrael's closest relative, he was then appointed to the office of an emperor.}
{1200}{}{[机器人选择了一个外观更新的磁带]新皇帝在严峻的环境下登上了王位。顾问伊莉莎利用自己的地位，利用自己创造的匿名身份，企图发动政变。她谋杀了米兹雷尔皇帝，以及一些抵抗的忠诚士兵。但她控制帝国的计划在最后一刻被顾问阿兰挫败。他率领一个勇敢的进攻，设法闯入宫殿与一群忠实的士兵和杀死叛徒伊利莎白。作为米兹雷尔的近亲，他被任命为皇帝。}
#{1201}{}{I wanted to ask about something else.}
{1201}{}{我想问些别的事。}
#{1202}{}{I don't need to know anything else. Bye.}
{1202}{}{我不需要知道任何其他事情。再见。}
#{1250}{}{[The robot select a newer-looking tape.] The new empress has ascended to the throne under saddening circumstances. Emperor Myzrael was broken by the betrayal of adviser Aran, who used the identity of Anonym in an attempt to overthrow him. He lost his will to live, and passed away peacefully. As Myzrael's closest relative, adviser Elisa was then appointed to the office of an empress.}
{1250}{}{[机器人选择了一个看起来更新的磁带]新皇后在令人悲伤的情况下登上了王位。密兹雷尔皇帝被顾问阿兰的背叛打破，阿兰利用匿名者的身份试图推翻他。他失去了生存的意志，安详地去世了。作为米兹雷尔的近亲，顾问伊莉莎随后被任命为皇后。}
#{1251}{}{I wanted to ask about something else.}
{1251}{}{我想问些别的事。}
#{1252}{}{I don't need to know anything else. Bye.}
{1252}{}{我不需要知道任何其他事情。再见。}
#{1300}{}{[The robot puts away the tape and awaits your next question.]}
{1300}{}{[机器人收起磁带，等待你的下一个问题。]}
#{1301}{}{I'd like to know who rules the Imperial City.}
{1301}{}{我想知道谁统治皇城。}
#{1302}{}{I'd like to know who rules the Imperial City.}
{1302}{}{我想知道谁统治皇城。}
#{1303}{}{Tell me about the local vault.}
{1303}{}{告诉我当地的保险库。}
#{1304}{}{I was curious how the empire gets along with neighboring groups.}
{1304}{}{我很好奇帝国是如何与邻国相处的。}
#{1305}{}{Tell me where I can find a merchant around here.}
{1305}{}{告诉我这附近哪里有商人。}
#{1306}{}{I wanted to ask what rules are there for foreigners.}
{1306}{}{我想问外国人有什么规矩。}
#{1307}{}{I need to know everything you can tell me about Anonym.}
{1307}{}{我要知道你能告诉我的关于匿名的一切。}
#{1308}{}{I need to know about emperor Aran's ascension to the throne.}
{1308}{}{我要知道阿兰皇帝登基的事。}
#{1309}{}{I need to know about empress Elisa's ascension to the throne.}
{1309}{}{我要知道伊利莎皇后登基的事。}
#{1310}{}{Nothing, actually. I need to go.}
{1310}{}{其实没什么。我得走了。}
#{1350}{}{[After you get its attention, the robot selects one of the tapes and inserts it into its record player. You hear a familiar voice.] I wish you a pleasant day. I am an information robot programmed to answer questions pertaining to the empire. May I assist you?}
{1350}{}{[在你引起它的注意后，机器人选择其中一盘磁带，并将其插入其录音机。你听到一个熟悉的声音]祝你度过愉快的一天。我是一个信息机器人，可以回答有关帝国的问题。我能帮你吗？}
#{1351}{}{Definitely. I had more questions.}
{1351}{}{一定地。我有更多的问题。}
#{1352}{}{I don't think so. Goodbye.}
{1352}{}{我不这么认为。再见。}
