#{100}{}{Emperor Myzrael is here. The meeting of the council may begin.}
{100}{}{米兹雷尔皇帝来了。理事会会议可以开始了。}
#{200}{}{I hope you have a good reason for bothering me.}
{200}{}{我希望你有充分的理由来打扰我。}
#{201}{}{I'm risking a lot by coming here. Anonym's assassins could be anywhere.}
{201}{}{我冒着很大的风险来这里。匿名杀手可能在任何地方。}
#{300}{}{And it is Anonym that this matter concerns. This foreigner knows the location of his hideout.}
{300}{}{这件事和匿名有关。这个外国人知道他的藏身处。}
#{301}{}{And it is Anonym that this matter concerns. This foreigner knows the location of his hideout.}
{301}{}{这件事和匿名有关。这个外国人知道他的藏身处。}
#{400}{}{The foreigner merely claims to know it. Utmost caution is required.}
{400}{}{那个外国人只是声称知道。必须非常小心。}
#{500}{}{::He looks at you curiously.::}
{500}{}{●他好奇地看着你：}
#{501}{}{Well, what are you waiting for? Speak.}
{501}{}{你还在等什么？说吧。}
#{600}{}{Certainly, emperor. I've heard that Anonym is currently hiding in a cellar of an abandoned house in the western end of the Dead Quarter.}
{600}{}{当然可以，皇帝。我听说Anonyme现在躲在死区西端一所废弃房子的地窖里。}
#{601}{}{I have no doubt that a quick strike by the imperial army would put a stop to his plans. But you must act swiftly.}
{601}{}{我毫不怀疑，皇军的一次快速打击会阻止他的计划。但你必须迅速行动。}
#{700}{}{Where did you receive this information? Assuming it's not completely made up.}
{700}{}{你从哪里得到这些信息的？假设它不是完全虚构的。}
#{701}{}{Where did you receive this information? Assuming it's not completely made up.}
{701}{}{你从哪里得到这些信息的？假设它不是完全虚构的。}
#{800}{}{I overheard a conversation of two mercenaries in the Wild Paradise. It's an establishment...}
{800}{}{我无意中听到两个佣兵在野外天堂的谈话。这是一个机构。。。}
#{801}{}{I overheard a conversation of two mercenaries in the Wild Paradise. It's an establishment...}
{801}{}{我无意中听到两个佣兵在野外天堂的谈话。这是一个机构。。。}
#{900}{}{I know what kind of a place it is. I hope you don't seriously expect us to go after a fairy tale like that.}
{900}{}{我知道这是一个什么样的地方。我希望你不要真的指望我们去追求那样的童话故事。}
#{1000}{}{Patience, adviser Aran. The empire is desperate. We must consider all our options.}
{1000}{}{耐心点，阿兰顾问。帝国绝望了。我们必须考虑所有的选择。}
#{1100}{}{But that doesn't mean that we should chase every single rumor.}
{1100}{}{但这并不意味着我们应该追查每一个谣言。}
#{1101}{}{I refuse to risk the lives of my men because of...}
{1101}{}{我拒绝拿我手下的生命冒险因为。。。}
#{1200}{}{Silence! Anonym's threat should not be underestimated.}
{1200}{}{安静！匿名的威胁不容小觑。}
#{1201}{}{We need to dispatch a squad of soldiers there. Immediately.}
{1201}{}{我们需要派一队士兵去那里。马上。}
#{1300}{}{Of course, emperor Myzrael.}
{1300}{}{当然，米兹雷尔皇帝。}
#{1400}{}{As you wish, emperor.}
{1400}{}{如你所愿，皇帝。}
#{1500}{}{Make sure to inform me of the result. I consider this meeting over.}
{1500}{}{一定要把结果告诉我。我想这次会议结束了。}
#{1600}{}{And what about me? Will I be rewarded?}
{1600}{}{那我呢？我会得到奖励吗？}
#{1700}{}{Your reward is knowing that you had the opportunity to help the empire. Now you may leave.}
{1700}{}{你的回报是知道你有机会帮助帝国。现在你可以走了。}
#{1701}{}{Your reward is knowing that you had the opportunity to help the empire. Now you may leave.}
{1701}{}{你的回报是知道你有机会帮助帝国。现在你可以走了。}
#{2000}{}{Are we so desperate that we hire foreigners to solve internal issues of the empire?}
{2000}{}{我们是不是如此绝望以至于雇佣外国人来解决帝国内部的问题？}
#{2050}{}{I think that a stranger can find out more outside the walls of the City than our soldiers could. We have nothing to lose.}
{2050}{}{我认为一个陌生人能在城外发现比我们的士兵更多的东西。我们没有什么可失去的。}
#{2051}{}{I think that a stranger can find out more outside the walls of the City than our soldiers could. We have nothing to lose.}
{2051}{}{我认为一个陌生人能在城外发现比我们的士兵更多的东西。我们没有什么可失去的。}
#{2100}{}{We'll see.}
{2100}{}{我们拭目以待。}
#{2500}{}{Emperor Myzrael is here. The council meeting may begin.}
{2500}{}{米兹雷尔皇帝来了。理事会会议可以开始了。}
#{2550}{}{What's the matter? Do you have new information about Anonym? ::He looks at you disagreeably.::}
{2550}{}{怎么了？你有关于匿名的新信息吗？●他不高兴地看着你：}
#{2600}{}{I'm afraid that we have bad news, emperor. This foreigner has found our soldiers in the Dead Quarter.}
{2600}{}{恐怕我们有坏消息，皇帝。这个外国人在死区发现了我们的士兵。}
#{2601}{}{I'm afraid that we have bad news, emperor. This foreigner has found our soldiers in the Dead Quarter.}
{2601}{}{恐怕我们有坏消息，皇帝。这个外国人在死区发现了我们的士兵。}
#{2602}{}{::She gestures at you.:: Tell us what you saw.}
{2602}{}{●她向你做手势。：：告诉我们你看到了什么。}
#{2603}{}{::She gestures at you.:: Tell us what you saw.}
{2603}{}{●她向你做手势。：：告诉我们你看到了什么。}
#{2650}{}{I found them in the remains of a sewer under one of the houses. All of them dead.}
{2650}{}{我在一所房子下面的下水道里发现了它们。他们都死了。}
#{2651}{}{I found them in the remains of a sewer under one of the houses. All of them dead.}
{2651}{}{我在一所房子下面的下水道里发现了它们。他们都死了。}
#{2700}{}{What? How is that possible?!}
{2700}{}{什么？怎么可能？！}
#{2750}{}{They must've fallen into a trap. Someone probably planted explosives there. If there were any wounded, Anonym's people have finished them off.}
{2750}{}{他们一定掉进陷阱了。可能有人在那里安放了炸药。如果有伤员的话，匿名者的人已经把他们干掉了。}
#{2800}{}{That's because we act on every sketchy piece of information, Elisa.}
{2800}{}{那是因为我们对每一个粗略的信息都采取行动，伊莉莎。}
#{2801}{}{We're playing right into Anonym's hands!}
{2801}{}{我们就在匿名者手里玩！}
#{2850}{}{What do you suggest we do?}
{2850}{}{你建议我们怎么办？}
#{2900}{}{No more sending our soldiers out blind. I won't allow putting our people in danger any longer.}
{2900}{}{再也不让我们的士兵瞎了眼了。我不允许再把我们的人民置于危险之中。}
#{2901}{}{We'll fortify our position, and wait for Anonym to act. He will make a mistake sooner or later.}
{2901}{}{我们会加强阵地，等匿名者行动。他迟早会犯错误的。}
#{2902}{}{I will personally see to it that we are prepared.}
{2902}{}{我将亲自确保我们做好准备。}
#{2950}{}{The death of our soldiers is unfortunate, but you must continue searching, Elisa.}
{2950}{}{我们士兵的死是不幸的，但你必须继续寻找，伊莉莎。}
#{2951}{}{I'm not going to sit here and wait until Anonym sends his assassins after me. Find him. No more mistakes.}
{2951}{}{我不会坐在这里等匿名者派刺客来追我。找到他。别再犯错误了。}
#{2952}{}{I conclude the meeting of the council.}
{2952}{}{我结束安理会会议。}
#{3000}{}{Adviser Aran. They say that you're the Anonym, but that can't be true. We don't believe that. What's going on here?}
{3000}{}{阿兰顾问。他们说你是匿名者，但那不可能是真的。我们不相信。这是怎么回事？}
#{3050}{}{Elisa has to be the Anonym, she's trying to take over the throne. We must act quickly, or she will kill emperor Myzrael.}
{3050}{}{伊莉莎必须是匿名者，她想继承王位。我们必须迅速行动，否则她会杀了米兹雷尔皇帝。}
#{3100}{}{Yes sir. We're behind you.}
{3100}{}{是的，先生。我们在你后面。}
#{3500}{}{Stop, Elisa. Your treachery has been exposed.}
{3500}{}{停下，伊莉莎。你的背叛已经暴露了。}
#{3501}{}{If you put your weapons down immediately, you will be treated mercifully.}
{3501}{}{如果你立即放下武器，你将受到仁慈的对待。}
#{3550}{}{Adviser Aran, your intervention comes at the last possible moment. My life...}
{3550}{}{阿兰顾问，你的介入是在最后一刻。我的生活。。。}
#{3600}{}{How... How could you?! Right before my eyes...}
{3600}{}{怎样。。。你怎么能这样？！就在我眼前。。。}
#{3650}{}{I couldn't take his senile prattle anymore. I had to end it.}
{3650}{}{我再也受不了他那老掉牙的废话了。我必须结束它。}
#{3700}{}{You went too far. You committed the worst crime!}
{3700}{}{你太过分了。你犯了最严重的罪行！}
#{3701}{}{I hope you didn't think you could actually foil my plan. You played out precisely the role I prepared for you.}
{3701}{}{我希望你没想到你真的能挫败我的计划。你扮演了我为你准备的角色。}
#{3702}{}{You are the Anonym, who has just killed emperor Myzrael.}
{3702}{}{你就是那个匿名者，刚刚杀了米兹雷尔皇帝。}
#{3703}{}{Your little rebellion won't change anything at all. You'll see for yourself soon.}
{3703}{}{你的小小反抗根本改变不了什么。你很快就会明白的。}
#{3750}{}{You won't get rid of me that easily!}
{3750}{}{你不会那么容易摆脱我的！}
#{3800}{}{We shall see.}
{3800}{}{我们拭目以待。}
#{3801}{}{Kill him. Kill them all.}
{3801}{}{杀了他。把他们都杀了。}
#{4000}{}{The traitor is dead. The empire is saved.}
{4000}{}{叛徒死了。帝国得救了。}
#{4050}{}{The old emperor is dead. Long live emperor Aran.}
{4050}{}{老皇帝死了。阿兰皇帝万岁。}
#{4100}{}{All hail Aran.}
{4100}{}{阿兰万岁。}
#{4150}{}{Silence! There is no reason to celebrate. Only to grieve.}
{4150}{}{安静！没有理由庆祝。只是为了悲伤。}
#{4151}{}{Take the dead and bury them with honor. Throw the bodies of the traitors outside the City walls.}
{4151}{}{带着死者光荣地埋葬他们。把叛徒的尸体扔到城墙外。}
#{4152}{}{Arrest the survivors. We'll deal with them later.}
{4152}{}{逮捕幸存者。我们稍后再处理。}
#{4153}{}{Rebuilding the empire will take tremendous effort. We must not lose any time.}
{4153}{}{重建帝国需要付出巨大的努力。我们不能浪费任何时间。}
#{4500}{}{You walk away, leaving Aran to his fate. Regardless of how everything turns out, you won't be welcome in the empire anymore.}
{4500}{}{你走开了，让阿兰听天由命。不管结果如何，帝国不再欢迎你了。}
#{4501}{}{You walk away, leaving Aran to his fate. Regardless of how everything turns out, you won't be welcome in the empire anymore.}
{4501}{}{你走开了，让阿兰听天由命。不管结果如何，帝国不再欢迎你了。}
#{4502}{}{We surrender! We'll accept any punishment.}
{4502}{}{我们投降！我们将接受任何惩罚。}
#{4503}{}{I don't like this at all.}
{4503}{}{我一点也不喜欢这样。}
#{4504}{}{You will most likely face execution in the empire.}
{4504}{}{你很可能在帝国面临死刑。}
#{5000}{}{We protect your sorry asses, we're the only thing standing between you and the Rebirth.}
{5000}{}{我们保护你可怜的屁股，我们是你和重生之间唯一的障碍。}
#{5001}{}{Without any real support from you. And what do we get? Nothing but accusations.}
{5001}{}{没有你真正的支持。我们得到了什么？只有指控。}
#{5050}{}{Enough stalling, commander Tulsa. We are well aware that you are responsible for the current state of the Vault.}
{5050}{}{别拖延了，塔尔萨指挥官。我们很清楚你对保险库的现状负责。}
#{5051}{}{If you're not going to at least admit that, we'll be forced to start acting regardless of the Hunters.}
{5051}{}{如果你至少不承认这一点，我们就不得不开始行动，不管猎人是谁。}
#{5100}{}{We're all shaking in our boots. I've nothing else to say to you.}
{5100}{}{我们都在发抖。我没有别的话要对你说。}
#{5150}{}{In that case you may leave. Immediately.}
{5150}{}{那样的话你可以走了。马上。}
#{5200}{}{Suckers.}
{5200}{}{笨蛋。}
#{5201}{}{::He glares at you.:: The hell you looking at?}
{5201}{}{●他瞪着你。：：你在看什么？}
