#{100}{}{The whole floor is filling with nerve gas. }
{100}{}{整层楼都充满了神经毒气。}
#{101}{}{You will die if you don't get out of here immediately.}
{101}{}{如果你不马上离开这里，你会死的。}
#{102}{}{Your power armor should protect you.}
{102}{}{你的动力盔甲应该能保护你。}
#{103}{}{The nerve gas has filled the whole floor. Everyone who inhaled it died.}
{103}{}{神经毒气弥漫了整层楼。所有吸入它的人都死了。}
#{104}{}{The last alien living on the second floor was killed.}
{104}{}{最后一个住在二楼的外星人被杀死了。}
#{105}{}{You stepped on a skillfully hidden mine. It was the last mistake of your life.}
{105}{}{你踩到了一个隐藏得很好的地雷，那是你人生中最后一个错误。}
#{106}{}{You stepped on a skillfully hidden mine. It was the last mistake of your life.}
{106}{}{你踩到了一个隐藏得很好的地雷，那是你人生中最后一个错误。}
#{107}{}{The soldiers defuse the mines hidden in the floor.}
{107}{}{士兵们拆除了隐藏在地板下的地雷。}
#{108}{}{An alarm resounds through the floor. All the Hunters flee to their base. It seems they were afraid of an alien attack.}
{108}{}{警报声响彻楼层。所有的猎人都逃回他们的基地。看起来他们害怕外星人的袭击。}
#{109}{}{An alarm resounds through the floor. All the Hunters flee to their base. But the aliens remained and are your problem now.}
{109}{}{警报声响彻楼层。所有的猎人都逃回他们的基地。但是外星人留了下来，现在是你的问题了。}
#{110}{}{An explosion resounds throughout the floor, followed by a rumble of the entrance caving in. }
{110}{}{一声爆炸声响彻整个楼层，接着是入口坍塌的隆隆声。}
#{111}{}{Enemies of the empire remain imprisoned here.}
{111}{}{帝国的敌人仍被囚禁在这里。}
#{112}{}{You've ridden the Vault of all enemies. Mission accomplished.}
{112}{}{你已经征服了避难所里所有敌人。任务完成。}
#{113}{}{You've ridden the Vault of all enemies. Mission accomplished.}
{113}{}{你已经征服了避难所里所有敌人。任务完成。}
#{380}{}{The way is clear.}
{380}{}{道路畅通无阻。}
#{381}{}{Go for it. Don't blow your cover.}
{381}{}{尽力争取。别暴露自己。}
