#{100}{}{Hand over my money.}
{100}{}{把我的钱交出来。}
#{200}{}{You'll get it after you give us the boy.}
{200}{}{你把孩子交出来就能拿到。}
#{300}{}{You motherfucker! We're doing this my way! UNDERSTAND?!}
{300}{}{你个混蛋！我们按我的方式做！明白吗？！}
#{400}{}{Alright, calm down. Everything's here.}
{400}{}{好了，冷静点，东西都在这儿了。}
#{500}{}{This is how everything will go down - one of my people will go to you, check the contents of the backpack, and pick it up. While my man's on the way back to me, we'll send the brat to you.}
{500}{}{事情是这样的——我的人会去找你，检查背包里的东西，然后把它拿走。等我的人回来了，我们就把这小子交给你。}
#{600}{}{OK.}
{600}{}{OK。}
#{700}{}{Go.}
{700}{}{去吧。}
#{800}{}{The backpack is stuffed with caps.}
{800}{}{背包里塞满了瓶盖。}
#{801}{}{Alright.}
{801}{}{好吧。}
#{900}{}{You won't have it that easy, assholes!}
{900}{}{你们可没那么容易，混蛋！}
#{1000}{}{Noo! You'll burn in hell for this, you bastard!}
{1000}{}{不! 你会为此下地狱的，你个混蛋！}
