#{100}{}{What exactly is a mutant?}
{100}{}{什么是变种人？}
#{101}{}{Some say that it is a physically changed human.}
{101}{}{有人说，这是一个身体改变的人。}
#{102}{}{But they are WRONG!}
{102}{}{但他们错了！}
#{103}{}{A mutant may have been human once, but once he changes...}
{103}{}{一个变种人可能曾经是人类，但一旦他改变了。。。}
#{104}{}{...he loses all his humanity.}
{104}{}{…他失去了人性。}
#{105}{}{And that's why he must die!}
{105}{}{所以他必须死！}
#{106}{}{Even if the physical manifestations of mutation are minimal.}
{106}{}{即使突变的物理表现很小。}
#{107}{}{On the contrary, such a mutant is even more dangerous...}
{107}{}{相反，这样的变种人更危险。。。}
#{108}{}{...and must be ELIMINATED!}
{108}{}{…必须被消灭！}
#{109}{}{Have the mutants ever created anything of value?}
{109}{}{变种人创造过有价值的东西吗？}
#{110}{}{NO!}
{110}{}{不！}
#{111}{}{What did they ever accomplish?}
{111}{}{他们完成了什么？}
#{112}{}{Nothing but murder and destruction!}
{112}{}{只有谋杀和毁灭！}
#{113}{}{Only fools dare say that we should negotiate with mutants.}
{113}{}{只有傻瓜才敢说我们应该和变种人谈判。}
#{114}{}{It is NONSENSE!}
{114}{}{这是胡说八道！}
#{115}{}{The mutant minds are so changed that no discussion can be had with them.}
{115}{}{变种人的思想变化太大了，不能和他们讨论。}
#{116}{}{They are aggressive and violent!}
{116}{}{他们有攻击性和暴力！}
#{117}{}{They understand nothing else, and can't be dealt with in any other way!}
{117}{}{他们什么都不懂，不能用别的办法对付！}
#{118}{}{We must be stronger than them...}
{118}{}{我们必须比他们强大。。。}
#{119}{}{...and exterminate them all!}
{119}{}{…消灭他们！}
#{120}{}{Before they do the same to us.}
{120}{}{在他们对我们做同样的事之前。}
#{121}{}{How could there be any doubt, when their existence itself is the greatest proof?}
{121}{}{当它们的存在本身就是最好的证据时，怎么会有任何怀疑呢？}
#{122}{}{For if a mutant was capable of reason...}
{122}{}{因为如果一个变种人有推理能力。。。}
#{123}{}{...he would surely kill himself!}
{123}{}{……他一定会自杀的！}
#{124}{}{He would understand how hopeless and pointless his existence is...}
{124}{}{他会明白他的存在是多么无望和毫无意义。。。}
#{125}{}{...and would put an end to his torment!}
{125}{}{…结束他的痛苦！}
#{126}{}{But instead, they fight against us humans...}
{126}{}{但是相反，他们与我们人类作战。。。}
#{127}{}{...so we'll have to take them out ourselves.}
{127}{}{…所以我们得自己把他们干掉。}
#{128}{}{We must exterminate every last one of them!}
{128}{}{我们必须消灭他们中的每一个！}
#{129}{}{Mutants don't hesitate to use every opportunity they have to kill humans, and that is why we cannot afford any doubt...}
{129}{}{变种人会毫不犹豫地利用一切机会杀死人类，这就是为什么我们不能怀疑。。。}
#{130}{}{...and must eradicate them ALL!}
{130}{}{…必须把他们全部消灭！}
#{131}{}{We must not miss the slightest mutation...}
{131}{}{我们不能错过任何一点突变。。。}
#{132}{}{...because it would spread to other pure humans, and from them to others...}
{132}{}{…因为它会传播到其他纯人类，并从他们传播到其他人。。。}
#{133}{}{A world without humans, filled with senseless, violent mutants.}
{133}{}{一个没有人类的世界，充满了愚蠢的，暴力的变种人。}
#{134}{}{That's the future we are trying to prevent!}
{134}{}{这就是我们试图阻止的未来！}
#{135}{}{That is why EVERY SINGLE MUTANT MUST DIE!}
{135}{}{这就是为什么每个变种人都必须死亡！}
#{136}{}{That's what every one of you here is fighting for, and you should feel proud of that.}
{136}{}{你们每个人都在为之奋斗，你们应该为此感到骄傲。}
#{137}{}{As I am proud of you!}
{137}{}{我为你感到骄傲！}
#{138}{}{Because you're saving humanity!}
{138}{}{因为你在拯救人类！}
#{139}{}{Because you're saving THE WORLD!}
{139}{}{因为你在拯救世界！}
#{140}{}{But we mustn't rejoice yet, we mustn't relent...}
{140}{}{但我们不能高兴，我们不能松懈。。。}
#{141}{}{Until the mutants have been WIPED FROM THE FACE OF THE EARTH!}
{141}{}{直到变种人从地球上消失！}
#{150}{}{Yeah!}
{150}{}{是 啊！}
#{151}{}{Damn right!}
{151}{}{他妈的对！}
#{152}{}{Hooray!}
{152}{}{万岁！}
#{153}{}{We'll win!}
{153}{}{我们会赢的！}
#{154}{}{We'll get them all!}
{154}{}{我们会把他们都抓到的！}
#{155}{}{Hooah!}
{155}{}{哇！}
#{156}{}{Death to mutants!}
{156}{}{变种人死定了！}
#{157}{}{Bravo!}
{157}{}{好极了！}
#{158}{}{::roar::}
{158}{}{●咆哮：}
#{159}{}{::whistle::}
{159}{}{●口哨声：}
#{200}{}{You see Sebastian.}
{200}{}{你看到塞巴斯蒂安了。}
#{201}{}{You see Sebastian, the leader of the Mutant Hunters.}
{201}{}{你看塞巴斯蒂安，变种猎人的首领。}
#{300}{}{Skip Sebastian's speech?}
{300}{}{跳过塞巴斯蒂安的演讲？}
#{301}{}{Yes, I want to skip it.}
{301}{}{是的，我想跳过它。}
#{302}{}{No, I want to hear it all.}
{302}{}{不，我想听全部。}
#{500}{}{The empire has started to take interested in their Vault. You should be damn careful in case those clowns try something.}
{500}{}{帝国开始对他们的金库感兴趣了。你应该小心点，以防那些小丑想干什么。}
#{501}{}{What the fu... There's that henchman of theirs! Dammit, why do I have to take care of everything myself.}
{501}{}{怎么回事。。。那是他们的心腹！该死，为什么我要自己照顾一切。}
