#{100}{}{You see a Hunter.}
{100}{}{你看到一个猎人。}
#{200}{}{You see a Mutant Hunter with a dim look in his eyes.}
{200}{}{你看到一个眼神暗淡的变种猎人。}
#{400}{}{Die, asshole.}
{400}{}{死吧，混蛋。}
#{401}{}{You shouldn't have messed with the Hunters.}
{401}{}{你不该惹那些猎人。}
#{402}{}{So you like mutants, do ya'?}
{402}{}{所以你喜欢变种人，是吗？}
#{403}{}{You'll die like a dirty mutant.}
{403}{}{你会像个肮脏的变种人一样死去。}
#{404}{}{You're not gonna make no mess in our city!}
{404}{}{你不能把我们的城市搞得一团糟！}
#{405}{}{Who the fuck do you think you are?}
{405}{}{你他妈以为你是谁？}
#{406}{}{You'll end up like all the mutants.}
{406}{}{你会像所有的变种人一样。}
#{407}{}{Start diggin' a grave.}
{407}{}{开始挖坟墓。}
#{408}{}{This city is ours!}
{408}{}{这个城市是我们的！}
#{409}{}{Betrayer of the human race!}
{409}{}{人类的背叛者！}
#{410}{}{Die, bitch.}
{410}{}{死吧，婊子。}
#{411}{}{You shouldn't have messed with the Hunters.}
{411}{}{你不该惹那些猎人。}
#{412}{}{So you like mutants, do ya?}
{412}{}{所以你喜欢变种人，是吗？}
#{413}{}{Die, mutant!}
{413}{}{死吧，变种人！}
#{414}{}{Dirty mutant!}
{414}{}{肮脏的变种人！}
#{415}{}{You already stink like a corpse!}
{415}{}{你已经像尸体一样臭了！}
#{416}{}{That'll cost you.}
{416}{}{那会让你付出代价的。}
#{417}{}{I'll have your guts for that!}
{417}{}{我要你的胆量！}
#{418}{}{We've got a rat!}
{418}{}{我们有只老鼠！}
#{450}{}{Die, asshole.}
{450}{}{死吧，混蛋。}
#{451}{}{You really fucked up now.}
{451}{}{你现在真的搞砸了。}
#{452}{}{So you like mutants, eh?}
{452}{}{所以你喜欢变种人，嗯？}
#{453}{}{You'll die like a dirty mutant.}
{453}{}{你会像个肮脏的变种人一样死去。}
#{454}{}{You're not gonna make no mess in our city!}
{454}{}{你不能把我们的城市搞得一团糟！}
#{455}{}{Traitor!}
{455}{}{叛徒！}
#{456}{}{Enjoy your last moments alive.}
{456}{}{享受你活着的最后时刻。}
#{457}{}{Betrayer of the human race!}
{457}{}{人类的背叛者！}
#{458}{}{Who the fuck do you think you are?}
{458}{}{你他妈以为你是谁？}
#{459}{}{Start diggin' a grave.}
{459}{}{开始挖坟墓。}
#{460}{}{You'll end up like all mutants.}
{460}{}{你会像所有的变种人一样。}
#{461}{}{So you like mutants, eh?}
{461}{}{所以你喜欢变种人，嗯？}
#{462}{}{Die, bitch.}
{462}{}{死吧，婊子。}
#{463}{}{You really fucked up now.}
{463}{}{你现在真的搞砸了。}
#{464}{}{That'll cost you.}
{464}{}{那会让你付出代价的。}
#{465}{}{I'll have your guts for that!}
{465}{}{我要你的胆量！}
#{500}{}{Huh?}
{500}{}{嗯？}
#{501}{}{Hello, what are you doing here?}
{501}{}{你好，你在这里干什么？}
#{502}{}{Oh, nothing.}
{502}{}{哦，没什么。}
#{503}{}{Ugh?}
{503}{}{呃？}
#{550}{}{I guard the computer. You can see.}
{550}{}{我守护着电脑。你可以看到。}
#{551}{}{Why are you guarding it?}
{551}{}{你为什么要守着它？}
#{600}{}{Because it's important. Victor hooked the Vault controls to it. No need to climb the chair.}
{600}{}{因为这很重要。维克托把保险库的控制装置挂在上面。不用爬椅子。}
#{601}{}{Who is Victor?}
{601}{}{维克托是谁？}
#{602}{}{Do you have access to the computer?}
{602}{}{你能使用电脑吗？}
#{603}{}{That means that from it you can, say, sound the alarm here on the third floor?}
{603}{}{也就是说，你可以，比如说，在三楼拉响警报？}
#{604}{}{I see, goodbye.}
{604}{}{我明白了，再见。}
#{650}{}{Victor fixes things.}
{650}{}{维克多解决了问题。}
#{651}{}{Do you have access to the computer?}
{651}{}{你能使用电脑吗？}
#{652}{}{Can you, say, sound the alarm here on the third floor?}
{652}{}{你能把三楼的警报响一下吗？}
#{653}{}{Nice, see you.}
{653}{}{很好，再见。}
#{700}{}{I do. But I can only use it when very necessary. Very very necessary!}
{700}{}{我愿意。但我只能在非常必要的时候使用它。非常非常必要！}
#{701}{}{Well it's very necessary now, you must sound the alarm here!}
{701}{}{现在很有必要，你必须在这里拉响警报！}
#{702}{}{I'll leave you alone now.}
{702}{}{我现在就让你一个人呆着。}
#{750}{}{Yeah I could do that. Yeah.}
{750}{}{是的，我能做到。是 啊。}
#{751}{}{Well, sound the alarm. Quick!}
{751}{}{好吧，拉响警报。快点！}
#{752}{}{I need nothing more.}
{752}{}{我再也不需要了。}
#{800}{}{Huh? Nothing's happening, it's calm.}
{800}{}{呵呵？什么都没发生，很平静。}
#{802}{}{The aliens escaped from their cages! They're murdering the scientists and will be everywhere in a minute!}
{802}{}{外星人从笼子里逃了出来！他们在谋杀科学家，马上就要到各处去了！}
#{803}{}{You're right, false alarm.}
{803}{}{你说得对，虚惊一场。}
#{850}{}{No, that's impossible. You lie and I don't like that. I will hurt you now.}
{850}{}{不，那是不可能的。你撒谎，我不喜欢。我现在就伤害你。}
#{851}{}{You wouldn't dare.}
{851}{}{你不敢。}
#{900}{}{The monsters escaped?! I'll sound the alarm, then let's run!}
{900}{}{怪物逃走了？！我来拉响警报，然后我们快跑！}
#{901}{}{Yes, you do that!}
{901}{}{是的，你这样做！}
#{950}{}{Huh?}
{950}{}{嗯？}
#{951}{}{Who is this Victor you mentioned?}
{951}{}{你提到的那个维克托是谁？}
#{952}{}{Do you have access to the computer?}
{952}{}{你能使用电脑吗？}
#{953}{}{Can you, say, sound the alarm here on the third floor?}
{953}{}{你能把三楼的警报响一下吗？}
#{954}{}{Oh nothing.}
{954}{}{哦，没什么。}
#{1000}{}{What? [A moment of silence.] Wait! You shouldn't be here. I must hurt you.}
{1000}{}{什么？[沉默片刻]等等！你不应该在这里。我一定要伤害你。}
#{1001}{}{Aaargh!}
{1001}{}{啊！}
