#{100}{}{You see a scientist.}
{100}{}{你看到一个科学家。}
#{200}{}{You see a Mutant Hunter scientist.}
{200}{}{你看到一个变种猎人科学家。}
#{300}{}{Aiee!}
{300}{}{艾伊！}
#{301}{}{Help!}
{301}{}{救命啊！}
#{302}{}{Run away!}
{302}{}{快跑！}
#{350}{}{Test 013 is looking very promising.}
{350}{}{测试013看起来很有希望。}
#{351}{}{Might be a decimal point mistake...}
{351}{}{可能是小数点错误。。。}
#{352}{}{It seems to periodically repeat.}
{352}{}{它似乎周期性地重复。}
#{353}{}{Hmmm, interesting.}
{353}{}{嗯，很有趣。}
#{354}{}{Fascinating.}
{354}{}{迷人的。}
#{355}{}{I hope we'll have enough sedatives.}
{355}{}{我希望我们有足够的镇静剂。}
#{356}{}{This deviation does not seem to be statistically significant.}
{356}{}{这种偏差似乎没有统计意义。}
#{357}{}{Interesting.}
{357}{}{很有趣。}
#{358}{}{If only we had better equipment...}
{358}{}{如果我们有更好的设备。。。}
#{359}{}{We need more test samples.}
{359}{}{我们需要更多的样品。}
#{360}{}{We will need to create more of the physiological solution.}
{360}{}{我们需要创造更多的生理解决方案。}
#{361}{}{All parameters are at normal levels.}
{361}{}{所有参数均处于正常水平。}
#{362}{}{We will need to conduct more tests.}
{362}{}{我们需要进行更多的测试。}
#{363}{}{::Wipes sweat from his forehead.::}
{363}{}{●擦去额头上的汗水：}
#{364}{}{Hmmmm...}
{364}{}{嗯。。。}
#{365}{}{Maybe...}
{365}{}{也许 吧。。。}
#{366}{}{We will need to run these tests again.}
{366}{}{我们需要再次运行这些测试。}
#{367}{}{Further research is necessary.}
{367}{}{进一步的研究是必要的。}
#{368}{}{I need only the relevant data.}
{368}{}{我只需要相关数据。}
#{369}{}{::sigh::}
{369}{}{●叹息：}
#{370}{}{A formidable specimen.}
{370}{}{可怕的标本。}
#{371}{}{This sample shows some remarkable features.}
{371}{}{此示例显示了一些显著的特征。}
#{380}{}{Stop that! Are you nuts? They'd kills us all immediately.}
{380}{}{住手！你疯了吗？他们会立刻杀了我们。}
#{381}{}{Stop that! Are you nuts? They'd kills us all immediately.}
{381}{}{住手！你疯了吗？他们会立刻杀了我们。}
#{382}{}{Stop that! Are you nuts?!}
{382}{}{住手！你疯了吗？！}
#{383}{}{Stop that! Are you nuts?!}
{383}{}{住手！你疯了吗？！}
#{400}{}{Where are the guards when you need them?!}
{400}{}{你需要警卫的时候他们在哪？！}
#{401}{}{Help!}
{401}{}{救命啊！}
#{402}{}{Somebody help me.}
{402}{}{谁来帮帮我。}
#{403}{}{Will somebody do something already?!}
{403}{}{有人会做点什么吗？！}
#{404}{}{Guards!}
{404}{}{警卫！}
#{405}{}{Don't kill me!}
{405}{}{别杀我！}
#{500}{}{What? I don't have time to chat with soldiers.}
{500}{}{什么？我没有时间和士兵聊天。}
#{501}{}{Who are you?}
{501}{}{你是谁？}
#{502}{}{Ugle?}
{502}{}{丑？}
#{550}{}{I'm a scientist, can't you see that? We're doing research on aliens here.}
{550}{}{我是科学家，你看不出来吗？我们在研究外星人。}
#{551}{}{Can you tell me what you found out about the aliens?}
{551}{}{你能告诉我你对外星人有什么发现吗？}
#{552}{}{Why are the aliens here?}
{552}{}{为什么外星人在这里？}
#{553}{}{What's that big lever for?}
{553}{}{那个大杠杆是干什么用的？}
#{554}{}{That's all I needed.}
{554}{}{这就是我所需要的。}
#{600}{}{Don't even come close to that! That lever turns off the forcefield on the cages with aliens. They'd kill us all.}
{600}{}{别接近那个！这个杠杆关闭了外星人笼子里的力场。他们会杀了我们所有人。}
#{601}{}{Can you tell me what you found out about the aliens?}
{601}{}{你能告诉我你对外星人有什么发现吗？}
#{602}{}{Why are the aliens here?}
{602}{}{为什么外星人在这里？}
#{603}{}{OK, relax.}
{603}{}{好的，放松。}
#{650}{}{I told you already. They're here so we could do research on them. We've learned a lot about them, but it's still not enough. Imagine what we could do if we were able to control them. We could fight off the mutants so easily.}
{650}{}{我已经告诉过你了。他们在这里，所以我们可以对他们进行研究。我们对他们了解了很多，但还不够。想象一下，如果我们能控制他们，我们能做些什么。我们可以轻而易举地击退变种人。}
#{651}{}{Can you tell me what you found out about the aliens?}
{651}{}{你能告诉我你对外星人有什么发现吗？}
#{652}{}{What's that big lever for?}
{652}{}{那个大杠杆是干什么用的？}
#{653}{}{That's all I needed.}
{653}{}{这就是我所需要的。}
#{700}{}{I don't have time to explain the results of our research to you, so just take this holodisk. [He gives you a holodisk.] But don't come back to me if you find out you don't understand.}
{700}{}{我没有时间向你解释我们的研究结果，所以就拿这个全息光盘吧。[他给了你一张全息光盘]但是如果你发现你不明白，就不要再找我了。}
#{701}{}{Thanks.}
{701}{}{谢谢。}
#{750}{}{You again? I really don't have the time.}
{750}{}{又是你？我真的没有时间。}
#{751}{}{Can you tell me what you found out about the aliens?}
{751}{}{你能告诉我你对外星人有什么发现吗？}
#{752}{}{Why are the aliens here?}
{752}{}{为什么外星人在这里？}
#{753}{}{What's that big lever for?}
{753}{}{那个大杠杆是干什么用的？}
#{754}{}{I won't keep you anymore.}
{754}{}{我不会再留你了。}
#{800}{}{How dreadful, it seems that just about anyone can be accepted these days. Go away.}
{800}{}{太可怕了，现在几乎每个人都能被接受。走开。}
#{801}{}{Ech.}
{801}{}{Ech公司。}
