#{100}{}{You see a Hunter.}
{100}{}{你看到一个猎人。}
#{200}{}{You see a Mutant Hunter.}
{200}{}{你看到一个变种猎人。}
#{300}{}{Huh huh. Let him be, he's not in the mood for chatting.}
{300}{}{啊哈。别管他了，他没心情聊天。}
#{301}{}{Yeah, you're spoiling the view. Huh huh.}
{301}{}{是啊，你在破坏风景。啊哈。}
#{302}{}{That's right, the monsters will smell you and have you for dessert.}
{302}{}{没错，怪物会闻到你的味道，把你当成甜点。}
#{303}{}{Huh huh it might be fun to see them tear him to shreds.}
{303}{}{看到他们把他撕成碎片可能会很有趣。}
#{304}{}{Huh huh it might be fun to see them tear her to shreds.}
{304}{}{看到他们把她撕成碎片可能很有趣。}
#{305}{}{Wake up, you're snoring too loud.}
{305}{}{醒醒，你的鼾声太大了。}
#{306}{}{Yeah, but it's still better than having those monsters chargin' at us.}
{306}{}{是啊，但总比让那些怪兽来找我们好。}
#{307}{}{That's right. And I heard the bastard badmouthing us.}
{307}{}{这是正确的。我听到那个混蛋在说我们坏话。}
#{350}{}{Get out of there.}
{350}{}{离开那里。}
#{351}{}{Don't stand there.}
{351}{}{别站在那儿。}
#{352}{}{You'll just lure them.}
{352}{}{你只会引诱他们。}
#{353}{}{Yum yum, crunch crunch, slurp slurp.}
{353}{}{百胜，嘎吱嘎吱，咕噜咕噜。}
#{354}{}{::Snoooore::}
{354}{}{●斯努奥尔：}
#{355}{}{Boring.}
{355}{}{真无聊。}
#{356}{}{Right.}
{356}{}{正确的。}
#{357}{}{Victor is an asshole.}
{357}{}{维克托是个混蛋。}
#{500}{}{Die, asshole.}
{500}{}{死吧，混蛋。}
#{501}{}{You shouldn't have messed with the Hunters.}
{501}{}{你不该惹那些猎人。}
#{502}{}{So you like mutants, eh?}
{502}{}{所以你喜欢变种人，嗯？}
#{503}{}{You'll die like a dirty mutant.}
{503}{}{你会像个肮脏的变种人一样死去。}
#{504}{}{You're not gonna make no mess in our city!}
{504}{}{你不能把我们的城市搞得一团糟！}
#{505}{}{Who the fuck do you think you are?}
{505}{}{你他妈以为你是谁？}
#{506}{}{You'll end up like all the mutants.}
{506}{}{你会像所有的变种人一样。}
#{507}{}{Start diggin' a grave.}
{507}{}{开始挖坟墓。}
#{508}{}{This city is ours!}
{508}{}{这个城市是我们的！}
#{509}{}{Betrayer of the human race!}
{509}{}{人类的背叛者！}
#{510}{}{Die, bitch.}
{510}{}{死吧，婊子。}
#{511}{}{You shouldn't have messed with the Hunters.}
{511}{}{你不该惹那些猎人。}
#{512}{}{So you like mutants, eh?}
{512}{}{所以你喜欢变种人，嗯？}
#{513}{}{Die, mutant!}
{513}{}{死吧，变种人！}
#{514}{}{Goddamn mutant!}
{514}{}{该死的变种人！}
#{515}{}{You already stink like a corpse!}
{515}{}{你已经像尸体一样臭了！}
#{516}{}{That'll cost you.}
{516}{}{那会让你付出代价的。}
#{517}{}{I'll have your guts for that!}
{517}{}{我要你的胆量！}
#{518}{}{We've got a rat!}
{518}{}{我们有只老鼠！}
#{550}{}{Die, asshole.}
{550}{}{死吧，混蛋。}
#{551}{}{You really fucked up this time.}
{551}{}{你这次真的搞砸了。}
#{552}{}{So you like mutants, do ya'?}
{552}{}{所以你喜欢变种人，是吗？}
#{553}{}{You'll die like a dirty mutant.}
{553}{}{你会像个肮脏的变种人一样死去。}
#{554}{}{You're not gonna make no mess in our city!}
{554}{}{你不能把我们的城市搞得一团糟！}
#{555}{}{Traitor!}
{555}{}{叛徒！}
#{556}{}{Enjoy your last moments alive.}
{556}{}{享受你活着的最后时刻。}
#{557}{}{Betrayer of the human race!}
{557}{}{人类的背叛者！}
#{558}{}{Who the fuck do you think you are?}
{558}{}{你他妈以为你是谁？}
#{559}{}{Start diggin' a grave.}
{559}{}{开始挖坟墓。}
#{560}{}{You'll end up like all the mutants.}
{560}{}{你会像所有的变种人一样。}
#{561}{}{So you like mutants, do ya'?}
{561}{}{所以你喜欢变种人，是吗？}
#{562}{}{Die, bitch.}
{562}{}{死吧，婊子。}
#{563}{}{You really fucked up this time.}
{563}{}{你这次真的搞砸了。}
#{564}{}{That'll cost you.}
{564}{}{那会让你付出代价的。}
#{565}{}{I'll have your guts for that!}
{565}{}{我要你的胆量！}
#{600}{}{Yeah?}
{600}{}{是 啊？}
#{601}{}{What are you two doing here?}
{601}{}{你们两个在这里干什么？}
#{602}{}{Oh nothing.}
{602}{}{哦，没什么。}
#{603}{}{Ghe?}
{603}{}{啊？}
#{650}{}{We are making sure none of the fucking monsters from level two run in here.}
{650}{}{我们要确保二级的怪物都不会跑进来。}
#{651}{}{What monsters?}
{651}{}{什么怪物？}
#{652}{}{Do they come here often?}
{652}{}{他们经常来这里吗？}
#{653}{}{Bye.}
{653}{}{再见。}
#{700}{}{They call them aliens. The eggheads could tell you more, but the won't wanna' talk to you.}
{700}{}{他们叫他们外星人。书呆子可以告诉你更多，但他们不想和你说话。}
#{701}{}{Do they come here often?}
{701}{}{他们经常来这里吗？}
#{702}{}{Bye.}
{702}{}{再见。}
#{750}{}{No. They like darkness, so they stay put. This watch is a piece of cake.}
{750}{}{不，他们喜欢黑暗，所以他们呆在原地。这只表是小菜一碟。}
#{751}{}{Bye.}
{751}{}{再见。}
