#{100}{}{You see a computer.}
{100}{}{你看到一台电脑。}
#{200}{}{You see a computer terminal.}
{200}{}{你看到一个计算机终端。}
#{250}{}{There's no time to do that in combat.}
{250}{}{在战斗中没有时间这么做。}
#{300}{}{The computer is broken.}
{300}{}{电脑坏了。}
#{500}{}{[This computer provides access to several texts about the Mutant Hunters. You can read them, or download them into your Pip-Boy.]}
{500}{}{[这台电脑提供了一些关于变种猎人的文本。你可以阅读它们，或下载到你的皮普男孩。]}
#{501}{}{[Open 'Mutant Hunters' History'.]}
{501}{}{[打开'变种猎人'历史'。]}
#{502}{}{[Open 'Our greatest warriors'.]}
{502}{}{[打开'我们最伟大的勇士'。]}
#{503}{}{[Connect your Pip-Boy.]}
{503}{}{[连接你的小男孩。]}
#{504}{}{[Leave.]}
{504}{}{[离开]}
#{550}{}{[The computer reports that your Pip-Boy has been successfully connected.]}
{550}{}{[计算机报告您的Pip Boy已成功连接。]}
#{551}{}{[Download 'Mutant Hunters' History'.]}
{551}{}{[下载'变种猎人'历史'。]}
#{552}{}{[Download 'Our greatest warriors'.]}
{552}{}{[下载'我们最伟大的勇士'。]}
#{553}{}{[Download 'Record of Sebastian's speech'.]}
{553}{}{[下载“塞巴斯蒂安的演讲记录”。]}
#{554}{}{[Disconnect your Pip-Boy and leave.]}
{554}{}{[断开你的皮普男孩的连接，然后离开。]}
#{600}{}{[Pip-Boy signals: The file 'Mutant Hunters' History' has been successfully downloaded.]}
{600}{}{[皮普男孩信号：文件'变种猎人'历史'已成功下载。]}
#{601}{}{[Download 'Our greatest warriors'.]}
{601}{}{[下载'我们最伟大的勇士'。]}
#{602}{}{[Download 'Record of Sebastian's speech'.]}
{602}{}{[下载“塞巴斯蒂安的演讲记录”。]}
#{603}{}{[Disconnect your Pip-Boy and leave.]}
{603}{}{[断开你的皮普男孩的连接，然后离开。]}
#{650}{}{[Pip-Boy signals: File already exists. Download cancelled.]}
{650}{}{[Pip Boy]信号：文件已存在。下载已取消。]}
#{651}{}{[Download 'Mutant Hunters' History'.]}
{651}{}{[下载'变种猎人'历史'。]}
#{652}{}{[Download 'Our greatest warriors'.]}
{652}{}{[下载'我们最伟大的勇士'。]}
#{653}{}{[Download 'Record of Sebastian's speech'.]}
{653}{}{[下载“塞巴斯蒂安的演讲记录”。]}
#{654}{}{[Disconnect your Pip-Boy and leave.]}
{654}{}{[断开你的皮普男孩的连接，然后离开。]}
#{700}{}{[Pip-Boy signals: The file 'Our greatest warriors' has been successfully downloaded.]}
{700}{}{[皮普男孩信号：文件'我们最伟大的勇士'已成功下载。]}
#{701}{}{[Download 'Mutant Hunters' History'.]}
{701}{}{[下载'变种猎人'历史'。]}
#{702}{}{[Download 'Record of Sebastian's speech'.]}
{702}{}{[下载“塞巴斯蒂安的演讲记录”。]}
#{703}{}{[Disconnect your Pip-Boy and leave.]}
{703}{}{[断开你的皮普男孩的连接，然后离开。]}
#{750}{}{[Pip-Boy signals: The file 'Record of Sebastian's speech' has been successfully downloaded.]}
{750}{}{[皮普男孩信号：文件'塞巴斯蒂安的讲话记录'已成功下载。]}
#{751}{}{[Download 'Mutant Hunters' History'.]}
{751}{}{[下载'变种猎人'历史'。]}
#{752}{}{[Download 'Our greatest warriors'.]}
{752}{}{[下载'我们最伟大的勇士'。]}
#{753}{}{[Disconnect your Pip-Boy and leave.]}
{753}{}{[断开你的皮普男孩的连接，然后离开。]}
#{800}{}{[The computer is flickering, and the display is showing things that you don't understand.]}
{800}{}{[电脑在闪烁，显示屏上显示的是你不懂的东西。]}
#{801}{}{Grrhrag! [Angrily hit the computer.]}
{801}{}{格瑞拉格！[愤怒地打电脑。]}
#{802}{}{Huf [Leave.]}
{802}{}{休夫[离开]}
#{850}{}{[The computer stops flickering, and the display doesn't show anything anymore.]}
{850}{}{[计算机停止闪烁，显示器不再显示任何内容。]}
#{851}{}{Ech. [Leave.]}
{851}{}{Ech公司。[离开]}
#{900}{}{Foreword Our organization, the Mutant Hunters, grows with every passing day, and this gives me the conviction that we will one day reach our common goal - the salvation of pure humans from mutants. When that blessed time comes, however, it will be necessary to remember what preceded so that the people who fought for the safety of others, and everything they had to sacrifice, is not forgotten. It should also serve as a warning that this must not happen again, so that mutants and mutations may never threaten the lives of pure humans ever again.}
{900}{}{前言：我们的组织，突变体猎人，与日俱增，这让我坚信，我们终有一天会达到我们的共同目标——从突变体中拯救纯净的人类。然而，当那神圣的时刻到来时，我们必须记住之前发生的一切，这样，那些为他人的安全而战的人们，以及他们必须牺牲的一切，就不会被遗忘。它也应该作为一个警告，这绝不能再次发生，使突变和突变可能永远不会威胁到纯人类的生命。}
#{901}{}{[Continue reading.]}
{901}{}{[继续阅读。]}
#{902}{}{[Close the file and prepare your Pip-Boy for download.]}
{902}{}{[关闭文件并准备下载Pip Boy。]}
#{903}{}{[Leave.]}
{903}{}{[离开]}
#{904}{}{That's why I wrote this history of the Hunters, which may also be the only thing left after us should the last Mutant Hunter fall. If that happens, let this document be a moral support for those that would follow in our steps. Let them know there were people before them that were determined to fight against the mutants, so they may learn from the mistakes which may have led to our demise.  Sebastian}
{904}{}{这就是为什么我写了这部猎人的历史，这可能也是最后一个变种猎人倒下后留给我们的唯一东西。如果发生这种情况，就让这份文件成为我们后续行动的道义支持。让他们知道在他们之前有人决心与变种人作战，这样他们就可以从导致我们灭亡的错误中吸取教训。塞巴斯蒂安}
#{950}{}{I saw the mutants ravaging this already desolate land, I saw the super mutants killing, torturing and capturing people. I saw pure humans mating with mutants, I saw the hideous monsters that come from such unions, sometimes living no longer than a few hours. It made me sick. I saw that decline of humanity, I saw it rushing to its destruction, and decided to do something about it.}
{950}{}{我看到变种人蹂躏这片已经荒芜的土地，我看到超级变种人杀戮、折磨和俘虏人们。我看到纯人类与变种人交配，我看到来自这种结合体的可怕怪物，有时活不过几个小时。它让我恶心。我看到了人性的衰落，我看到了它的毁灭，我决定做点什么。}
#{951}{}{[Continue reading.]}
{951}{}{[继续阅读。]}
#{952}{}{[Close the file and prepare your Pip-Boy for download.]}
{952}{}{[关闭文件并准备下载Pip Boy。]}
#{953}{}{[Leave.]}
{953}{}{[离开]}
#{1000}{}{There were always enough groups of pure humans strong enough to survive, but their lives were without meaning, without purpose. They were merely surviving, and their existence meant nothing on its own. But when I showed them what I'd seen, they understood me, and saw the danger threatening all pure humans on their own. They joined me, and I united them with a promise that we'll rid the world of mutants - a promise that I hope we'll one day fulfill.}
{1000}{}{总有足够多的一群纯粹的人类坚强到足以生存，但他们的生活毫无意义，没有目标。他们只是在生存，他们的存在本身毫无意义。但是当我向他们展示我所看到的时，他们理解我，并且看到危险独自威胁着所有纯洁的人类。他们加入了我，我把他们团结在一起，承诺我们会消灭世界上的变种人——我希望有一天我们会实现这个承诺。}
#{1001}{}{[Continue reading.]}
{1001}{}{[继续阅读。]}
#{1002}{}{[Close the file and prepare your Pip-Boy for download.]}
{1002}{}{[关闭文件并准备下载Pip Boy。]}
#{1003}{}{[Leave.]}
{1003}{}{[离开]}
#{1050}{}{We helped villages and towns, ridding them of the foul mutants, despite the nonsensical resistance of the local people. But above all, we grew stronger. Not only were we joined by more and more pure humans willing to fight, we also searched for forgotten pre-war weapons and armor that would helps us in our fight. This was necessary because units created by the mad Master with the help of the betrayers of the human race, the Children of the Cathedral, were already spreading across the wasteland. We fought the super mutants many times. We killed many of them, but many brave Hunters died as well.}
{1050}{}{我们帮助了村庄和城镇，清除了肮脏的变种人，尽管当地人民进行了荒谬的抵抗。但最重要的是，我们变得更强大了。我们不仅有越来越多愿意战斗的纯人类加入，我们还寻找被遗忘的战前武器和盔甲来帮助我们战斗。这是必要的，因为疯狂的主人在人类叛徒的帮助下创造的单位，大教堂的孩子们，已经遍布荒地。我们和超级变种人打过很多次。我们杀了很多人，但也有很多勇敢的猎人死了。}
#{1051}{}{[Continue reading.]}
{1051}{}{[继续阅读。]}
#{1052}{}{[Close the file and prepare your Pip-Boy for download.]}
{1052}{}{[关闭文件并准备下载Pip Boy。]}
#{1053}{}{[Leave.]}
{1053}{}{[离开]}
#{1100}{}{Thanks to our efforts, the super mutants stopped appearing in our territory and remained far in the west. But then a new menace appeared - the Rebirth. The Rebirth is some new religion that spread amongst the ghouls, and they, armed with the best weapons people had created before the war, started to pillage towns and villages. We don't know where they got such equipment, or anything about their foolish faith. The ghouls talk only of someone called Savior, no doubt another disgusting mutant. Not only do they kill in his name, they also capture pure humans and take them away, but we don't know where or why.}
{1100}{}{多亏了我们的努力，超级变种人不再出现在我们的领土上，而留在遥远的西部。但随后一个新的威胁出现了——重生。重生是一些在僵尸中传播的新宗教，他们用战争前人们创造的最好的武器武装起来，开始掠夺城镇和村庄。我们不知道他们从哪里弄到这样的设备，也不知道他们愚蠢的信仰。僵尸只谈论一个叫救世主的人，毫无疑问是另一个恶心的变种人。他们不仅以他的名义杀人，还俘虏了纯洁的人类并将他们带走，但我们不知道在哪里，也不知道为什么。}
#{1101}{}{[Continue reading.]}
{1101}{}{[继续阅读。]}
#{1102}{}{[Close the file and prepare your Pip-Boy for download.]}
{1102}{}{[关闭文件并准备下载Pip Boy。]}
#{1103}{}{[Leave.]}
{1103}{}{[离开]}
#{1150}{}{So we continued to look for pre-war technology, as well as new allies. We found both in the only city that resisted the Rebirth in the area. Or at least we thought so. We came to Albuquerque, the city that had already endured a large ghoul attack, and offer our help and an alliance. But we were refused, offered only a twisted agreement concluded in 2157. In return for defending Albuquerque against the invaders, we were allowed to eradicate the threat within the city! They "graciously" gave us the permission to purge the city of mutants, when it should've been their natural duty as pure humans! And all we received was the minimum material required for the construction of our base. People of the empire, blinded by their easy lives, didn't realize the threat that Rebirth posed. And not only the Rebirth, but all mutants.}
{1150}{}{所以我们继续寻找战前的技术，以及新的盟友。我们在这个地区唯一一个抵制重生的城市发现了这两个。至少我们是这么想的。我们来到阿尔伯克基，这座城市已经经历了一次大规模的僵尸袭击，并提供了我们的帮助和联盟。但我们被拒绝了，只有一个扭曲的协议在2157年达成。作为对保卫阿尔伯克基抵抗侵略者的回报，我们被允许在城市内部消除威胁！他们“仁慈地”允许我们清除城市里的变种人，而这本应该是他们作为纯人类的自然职责！我们得到的只是建造基地所需的最低材料。帝国的人民被他们安逸的生活蒙蔽了双眼，没有意识到重生带来的威胁。不仅是重生，还有所有的变种。}
#{1151}{}{[Continue reading.]}
{1151}{}{[继续阅读。]}
#{1152}{}{[Close the file and prepare your Pip-Boy for download.]}
{1152}{}{[关闭文件并准备下载Pip Boy。]}
#{1153}{}{[Leave.]}
{1153}{}{[离开]}
#{1200}{}{In 2160, many dwellers paid for their foolishness with their lives. The ghouls mustered enough strength for a second large attack on the city. Without tactics or reason, they ferociously threw themselves at Albuquerque. Their better weapons and especially their numerical superiority allowed them to penetrate deep into the city. While confusion spread amongst the imperial soldiers, we Mutant Hunters eventually forced the ghouls to retreat. But not even after our triumph did the emperor offer us the technology and equipment that they have amply available. The only thing he agreed with was the construction of a wall around the entire city. There was plenty of material available. Not only from around the city, but especially from the ruins that remained after the ghoul invasion. That destroyed part of the city has been called the Dead Quarter ever since.}
{1200}{}{2160年，许多居民为自己的愚蠢付出了生命代价。僵尸们聚集了足够的力量，准备对这座城市进行第二次大规模袭击。没有策略和理由，他们凶猛地扑向阿尔伯克基。他们更好的武器，特别是他们的数字优势，使他们能够深入到城市。当混乱在帝国士兵中蔓延时，我们变异猎人最终迫使僵尸撤退。但即使在我们胜利之后，皇帝也没有向我们提供他们所拥有的技术和设备。他唯一同意的是在整个城市周围建一堵墙。有很多可用的材料。不仅来自城市周围，尤其是在僵尸入侵后留下的废墟上。这座城市被毁的部分从此被称为死亡区。}
#{1201}{}{[Continue reading.]}
{1201}{}{[继续阅读。]}
#{1202}{}{[Close the file and prepare your Pip-Boy for download.]}
{1202}{}{[关闭文件并准备下载Pip Boy。]}
#{1203}{}{[Leave.]}
{1203}{}{[离开]}
#{1250}{}{Our relentless search across the wasteland finally bore fruit in 2161. We discovered an old army warehouse, and turned it into our second base. Thanks to its excellent location, it remains hidden from the Rebirth patrols that frequently appear in the area. Thus, we don't have to take the captured ghouls far, and especially not into a city that we strive to keep clean from mutants. That's why the base, headed by commander Tunrida, is mostly use for interrogations and conducting tests on the mutants.}
{1250}{}{我们在荒地上的不懈搜寻终于在2161年取得了成果。我们发现了一个旧的军用仓库，把它变成了我们的第二个基地。由于其优越的地理位置，它仍然隐藏在重生巡逻，经常出现在该地区。因此，我们不必把俘虏的僵尸带得很远，尤其不必带到一个我们努力不让变种人进入的城市。这就是为什么这个由图里达指挥官领导的基地主要用于审问和测试突变体。}
#{1251}{}{[Continue reading.]}
{1251}{}{[继续阅读。]}
#{1252}{}{[Close the file and prepare your Pip-Boy for download.]}
{1252}{}{[关闭文件并准备下载Pip Boy。]}
#{1253}{}{[Leave.]}
{1253}{}{[离开]}
#{1300}{}{In 2166, we finally took at least a part of what rightfully belongs to us. We defend Albuquerque from mutants both inside and outside, and the empire still refuses to help us. We defend their lives, as well as the lives of all pure humans, and they refuse to give us the technology that would be of incredible help not only in our fight against the Rebirth, but all the mutants! That's why we took the third floor of their Vault by force. We used killers genetically engineered by pre-war scientists to capture the floor without the empire suspecting a thing. The emperor responded to the loss of the two floors of their Vault by shutting the Imperial City off from the rest of Albuquerque, proving that there was no one capable of sensible leadership among the descendants of the Vault 16 dwellers.}
{1300}{}{在2166年，我们终于拿走了至少一部分本该属于我们的东西。我们保护阿尔伯克基不受内外变异人的攻击，帝国仍然拒绝帮助我们。我们捍卫他们的生命，以及所有纯人类的生命，他们拒绝给我们技术，这将是难以置信的帮助，不仅在我们打击重生，但所有的变种人！所以我们强行占领了他们地下室的三楼。我们用战前科学家基因改造的杀手占领了地面，帝国对此毫无怀疑。皇帝对失去两层地窖的反应是，将皇城与阿尔伯克基的其他地方隔离开来，这证明在16号地窖的后代中，没有一个人能够胜任明智的领导。}
#{1301}{}{[Continue reading.]}
{1301}{}{[继续阅读。]}
#{1302}{}{[Close the file and prepare your Pip-Boy for download.]}
{1302}{}{[关闭文件并准备下载Pip Boy。]}
#{1303}{}{[Leave.]}
{1303}{}{[离开]}
#{1350}{}{Update December 9, 2169: A few days earlier, we received a message from Tunrida saying that they've finally managed to break one of the Rebirth ghouls during interrogation, and gain new information. She was apparently close to discovering the location of their base. However, the base has not responded to any of our calls since then. Until a group of our scouts discovered that it was occupied by super mutants. The foul beasts killed every Hunter stationed in the base, and it can be assumed that they destroyed everything there.}
{1350}{}{更新时间：2169年12月9日：几天前，我们收到一条来自Tunrida的消息，说他们终于在审讯中击破了一个重生的僵尸，并获得了新的信息。她很快就要找到他们基地的位置了。然而，基地从那时起就没有回应我们的任何电话。直到我们的侦察队发现这里被超级变种人占领。邪恶的野兽杀死了基地里的每一个猎人，可以认为他们摧毁了那里的一切。}
#{1351}{}{[Open 'Our greatest warriors'.]}
{1351}{}{[打开'我们最伟大的勇士'。]}
#{1352}{}{[Close the file and prepare your Pip-Boy for download.]}
{1352}{}{[关闭文件并准备下载Pip Boy。]}
#{1353}{}{[Leave.]}
{1353}{}{[离开]}
#{1400}{}{We fight not for glory, but for the salvation of mankind. However, the names and deeds of the great warriors who lost their lives fighting the mutants should not be forgotten. }
{1400}{}{我们战斗不是为了荣耀，而是为了拯救人类。然而，那些在与突变体战斗中牺牲的伟大战士的名字和事迹不应该被遗忘。}
#{1401}{}{[Continue reading.]}
{1401}{}{[继续阅读。]}
#{1402}{}{[Close the file and prepare your Pip-Boy for download.]}
{1402}{}{[关闭文件并准备下载Pip Boy。]}
#{1403}{}{[Leave.]}
{1403}{}{[离开]}
#{1450}{}{Cole Gassko Mercilessly kept purging Albuquerque of mutants hiding in the city. He was killed by one of those he so dutifully protected - a city dweller.}
{1450}{}{科尔·加斯科毫不留情地不断清除阿尔伯克基躲藏在城里的变种人。他被一个他尽职保护的人杀死了一个城市居民。}
#{1451}{}{[Continue reading.]}
{1451}{}{[继续阅读。]}
#{1452}{}{[Close the file and prepare your Pip-Boy for download.]}
{1452}{}{[关闭文件并准备下载Pip Boy。]}
#{1453}{}{[Leave.]}
{1453}{}{[离开]}
#{1500}{}{Leena Her unit was ambushed by a group of Rebirth ghouls. She was the only one to survive, and she chased the ghouls, even through irradiated areas, until she killed them all. She died a few days later due to radiation poisoning.}
{1500}{}{莉娜她的部队遭到一群重生僵尸的伏击。她是唯一幸存下来的人，她追赶僵尸，甚至穿过受辐射的区域，直到她把他们全部杀死。几天后她死于辐射中毒。}
#{1501}{}{[Continue reading.]}
{1501}{}{[继续阅读。]}
#{1502}{}{[Close the file and prepare your Pip-Boy for download.]}
{1502}{}{[关闭文件并准备下载Pip Boy。]}
#{1503}{}{[Leave.]}
{1503}{}{[离开]}
#{1550}{}{Bastel "the Merciless" Led the Hunters during the cleansing of many towns and villages from mutants. He fell during the second large attack on Albuquerque.}
{1550}{}{巴斯特尔“无情者”带领猎人们清除了许多城镇和村庄中的变种人。他在阿尔伯克基的第二次大规模袭击中倒下。}
#{1551}{}{[Continue reading.]}
{1551}{}{[继续阅读。]}
#{1552}{}{[Close the file and prepare your Pip-Boy for download.]}
{1552}{}{[关闭文件并准备下载Pip Boy。]}
#{1553}{}{[Leave.]}
{1553}{}{[离开]}
#{1600}{}{Andrew Ryamon Together with the Hunters under his command, he killed many of the Master's super mutants, until they were treacherously ambushed by a large group of them. He was killed along with the majority of his troops.}
{1600}{}{安德鲁·瑞蒙和他手下的猎人们一起，杀死了许多大师的超级变种人，直到他们被一大群人奸诈地伏击。他和他的大多数部队一起被杀。}
#{1601}{}{[Continue reading.]}
{1601}{}{[继续阅读。]}
#{1602}{}{[Close the file and prepare your Pip-Boy for download.]}
{1602}{}{[关闭文件并准备下载Pip Boy。]}
#{1603}{}{[Leave.]}
{1603}{}{[离开]}
#{1650}{}{"Mad" Sam A great fighter and slayer of mutants. Killed along with other Hunters by the first alien queen after she awakened.}
{1650}{}{“疯子”萨姆是一个伟大的战士和突变体杀手。与其他猎人一起被第一个外星女王在她醒来后杀死。}
#{1651}{}{[Continue reading.]}
{1651}{}{[继续阅读。]}
#{1652}{}{[Close the file and prepare your Pip-Boy for download.]}
{1652}{}{[关闭文件并准备下载Pip Boy。]}
#{1653}{}{[Leave.]}
{1653}{}{[离开]}
#{1700}{}{Soram Killed many mutants, defended Albuquerque during the second large attack and took part in the construction of the city wall. When he found out that his body was showing the signs of mutation, he correctly chose to shoot himself.}
{1700}{}{拉姆杀死了许多变种人，在第二次大规模袭击中保卫了阿尔伯克基，并参与了城墙的修建。当他发现自己的身体出现变异迹象时，他正确地选择了开枪自杀。}
#{1701}{}{[Continue reading.]}
{1701}{}{[继续阅读。]}
#{1702}{}{[Close the file and prepare your Pip-Boy for download.]}
{1702}{}{[关闭文件并准备下载Pip Boy。]}
#{1703}{}{[Leave.]}
{1703}{}{[离开]}
#{1750}{}{Anna Taylor Lured a patrol of the Master's super mutants to herself, and killed them all by detonating a powerful explosive charge strapped to her body.}
{1750}{}{安娜·泰勒引诱了一支巡逻队的主人的超级变种人来到自己身边，并引爆绑在她身上的强力炸药，将他们全部杀死。}
#{1751}{}{[Continue reading.]}
{1751}{}{[继续阅读。]}
#{1752}{}{[Close the file and prepare your Pip-Boy for download.]}
{1752}{}{[关闭文件并准备下载Pip Boy。]}
#{1753}{}{[Leave.]}
{1753}{}{[离开]}
#{1800}{}{Vukovich Valiantly fought against the Rebirth ghouls during the second large attack on Albuquerque. Died after sustaining extensive injuries.}
{1800}{}{武科维奇在阿尔伯克基的第二次大规模袭击中勇敢地与重生的僵尸战斗。受重伤后死亡。}
#{1801}{}{[Open 'Mutant Hunters' History'.]}
{1801}{}{[打开'变种猎人'历史'。]}
#{1802}{}{[Close the file and prepare your Pip-Boy for download.]}
{1802}{}{[关闭文件并准备下载Pip Boy。]}
#{1803}{}{[Leave.]}
{1803}{}{[离开]}
