#{100}{}{You see a computer.}
{100}{}{你看到一台电脑。}
#{200}{}{You see a computer connected to Vault control.}
{200}{}{你看到一台计算机连接到保险库控制。}
#{300}{}{There's no time to do that in combat.}
{300}{}{在战斗中没有时间这么做。}
#{500}{}{Enter password.}
{500}{}{输入密码。}
#{501}{}{[Enter 'Death to mutants'.]}
{501}{}{[输入'Death to mutants'。]}
#{502}{}{[Try to hack the computer.]}
{502}{}{[试图入侵计算机。]}
#{503}{}{[Try to guess the password.]}
{503}{}{[试着猜密码。]}
#{504}{}{[Leave.]}
{504}{}{[离开]}
#{505}{}{Huf [Leave.]}
{505}{}{休夫[离开]}
#{550}{}{[Most functions of the overseer chair have been rerouted to this computer. They are of no use to you.]}
{550}{}{[监工椅的大部分功能已被重新路由到此计算机。它们对你毫无用处。]}
#{551}{}{[Log off and leave.]}
{551}{}{[注销并离开。]}
#{600}{}{[Most functions of the overseer chair have been rerouted to this computer. Besides sounding the alarm on the third floor, they are of no use to you.]}
{600}{}{[监工椅的大部分功能已被重新路由到此计算机。除了在三楼拉响警报，它们对你也没用。]}
#{601}{}{[Sound the alarm on the third floor.]}
{601}{}{[在三楼拉响警报。]}
#{602}{}{[Log off and leave.]}
{602}{}{[注销并离开。]}
#{650}{}{[You managed to hack the computer. Most functions of the overseer chair have been rerouted to it. They are of no use to you.]}
{650}{}{[你设法入侵了电脑。监工主席的大部分职能都被重新安排到了这里。它们对你毫无用处。]}
#{651}{}{[Log off and leave.]}
{651}{}{[注销并离开。]}
#{700}{}{[You managed to hack the computer. Most functions of the overseer chair have been rerouted to it. Besides sounding the alarm on the third floor, they are of no use to you.]}
{700}{}{[你设法入侵了电脑。监工主席的大部分职能都被重新安排到了这里。除了在三楼拉响警报，它们对你也没用。]}
#{701}{}{[Sound the alarm on the third floor.]}
{701}{}{[在三楼拉响警报。]}
#{702}{}{[Log off and leave.]}
{702}{}{[注销并离开。]}
#{750}{}{[You fail to hack the computer.]}
{750}{}{[你没能破解电脑。]}
#{751}{}{[Leave.]}
{751}{}{[离开]}
#{800}{}{[You managed to guess the password 'Death to mutants'. Most functions of the overseer chair have been rerouted to this computer. They are of no use to you.]}
{800}{}{[你猜到了密码'变种人之死'。监工椅的大部分功能都被重新分配到了这台计算机上。它们对你毫无用处。]}
#{801}{}{[Log off and leave.]}
{801}{}{[注销并离开。]}
#{850}{}{[You managed to guess the password 'Death to mutants'. Most functions of the overseer chair have been rerouted to this computer. Besides sounding the alarm on the third floor, they are of no use to you.]}
{850}{}{[你猜到了密码'变种人之死'。监工椅的大部分功能都被重新分配到了这台计算机上。除了在三楼拉响警报，它们对你也没用。]}
#{851}{}{[Sound the alarm on the third floor.]}
{851}{}{[在三楼拉响警报。]}
#{852}{}{[Log off and leave.]}
{852}{}{[注销并离开。]}
#{900}{}{[You fail to guess the password.]}
{900}{}{[你猜不到密码。]}
#{901}{}{[Leave.]}
{901}{}{[离开]}
