#{100}{}{You see emperor Myzrael.}
{100}{}{你看到了米兹雷尔皇帝。}
#{200}{}{You see an old man in a blue robe made of high-quality cloth. He's doubtlessly Myzrael, the ruler of the empire.}
{200}{}{你看到一位老人穿着一件用高级布料做成的蓝色长袍。他无疑是帝国的统治者米兹雷尔。}
#{300}{}{How dare you!}
{300}{}{你怎么敢！}
#{301}{}{Guards!}
{301}{}{警卫！}
#{302}{}{Anonym's assassin!}
{302}{}{匿名杀手！}
#{303}{}{Do you know who I am?!}
{303}{}{你知道我是谁吗？！}
#{304}{}{The guards will take care of you.}
{304}{}{警卫会照顾你的。}
