#{100}{}{You see a woman.}
{100}{}{你看到一个女人。}
#{150}{}{You see Penny.}
{150}{}{你看到佩妮了。}
#{200}{}{You see an attractive woman. Her combed blonde hair brings out her beautiful face.}
{200}{}{你看到一个漂亮的女人。她梳好的金发露出了美丽的脸庞。}
#{250}{}{You see Penny, William's wife. She possesses both beauty and youthful appearance.}
{250}{}{你看彭妮，威廉的妻子。她既美丽又年轻。}
#{300}{}{I'm looking forward to it.}
{300}{}{我很期待。}
#{301}{}{See you tonight.}
{301}{}{今晚见。}
#{302}{}{::She blows you a kiss.::}
{302}{}{●她给了你一个飞吻：}
#{303}{}{Don't keep me waiting too long in that alley.}
{303}{}{别让我在那条巷子里等太久。}
#{400}{}{Guards!}
{400}{}{警卫！}
#{401}{}{I can handle thugs.}
{401}{}{我能对付暴徒。}
#{402}{}{Others have tried and failed.}
{402}{}{其他人尝试过，但失败了。}
#{403}{}{Don't think you'll get me that easily.}
{403}{}{别以为你会那么容易找到我。}
#{404}{}{I'll show you, you'll see.}
{404}{}{我给你看，你会看到的。}
#{405}{}{All kinds of thugs tried to cripple me. You won't surprise me.}
{405}{}{各种各样的暴徒都想把我弄瘸。你不会让我吃惊的。}
#{500}{}{Hello, I haven't seen you before, and you don't look like one of William's people. That's a pleasant surprise.}
{500}{}{你好，我以前没见过你，你看起来不像威廉的人。真是个惊喜。}
#{501}{}{Who are you?}
{501}{}{你是谁？}
#{502}{}{Hoo you?}
{502}{}{你呢？}
#{550}{}{I'm Penny, William's wife. Did you know he doesn't like strangers visiting us? You must be very brave to come here despite that.}
{550}{}{我是彭妮，威廉的妻子。你知道他不喜欢陌生人来看我们吗？尽管如此，你来这里一定很勇敢。}
#{551}{}{I'm Penny, William's wife. Did you know he doesn't like strangers visiting us? You must be very brave to come here despite that.}
{551}{}{我是彭妮，威廉的妻子。你知道他不喜欢陌生人来看我们吗？尽管如此，你来这里一定很勇敢。}
#{552}{}{'Us'? Who else do you mean?}
{552}{}{“我们”？你还说谁？}
#{553}{}{What can you tell me about William?}
{553}{}{关于威廉，你能告诉我什么？}
#{554}{}{Could you please tell me something about the Wild Paradise? I've heard you used to work there.}
{554}{}{你能告诉我一些关于野生天堂的事吗？我听说你以前在那里工作。}
#{555}{}{[Try to slit her throat before she can call for help.]}
{555}{}{[在她呼救之前割断她的喉咙。]}
#{556}{}{Vex wants one of William's wives dead. Might as well be you.}
{556}{}{维克斯想要威廉的一个妻子死。也许是你。}
#{557}{}{I didn't actually come to see you. Sorry.}
{557}{}{我其实不是来看你的。对不起的。}
#{558}{}{I didn't actually come to see you. Sorry.}
{558}{}{我其实不是来看你的。对不起的。}
#{600}{}{Doreen, of course, is also his wife. He married her earlier than me, back in Los Alamos.}
{600}{}{当然，多琳也是他的妻子。他在洛斯阿拉莫斯比我早娶了她。}
#{601}{}{How do you two get along?}
{601}{}{你们俩相处得怎么样？}
#{602}{}{What do you know about Los Alamos?}
{602}{}{你对洛斯阿拉莫斯了解多少？}
#{603}{}{What can you tell me about William?}
{603}{}{关于威廉，你能告诉我什么？}
#{604}{}{Could you please tell me something about the Wild Paradise? I've heard you used to work there.}
{604}{}{你能告诉我一些关于野生天堂的事吗？我听说你以前在那里工作。}
#{605}{}{[Try to slit her throat before she can call for help.]}
{605}{}{[在她呼救之前割断她的喉咙。]}
#{606}{}{Vex wants one of William's wives dead. Might as well be you.}
{606}{}{维克斯想要威廉的一个妻子死。也许是你。}
#{607}{}{I'd better get going.}
{607}{}{我得走了。}
#{650}{}{We get along well, and William wouldn't have it any other way. She's like my older sister. It's true that she's a bit... different from me. We don't have much to talk about.}
{650}{}{我们相处得很好，威廉也不会有别的办法。她就像我姐姐。她确实有点。。。和我不一样。我们没什么好谈的。}
#{651}{}{What do you know about Los Alamos?}
{651}{}{你对洛斯阿拉莫斯了解多少？}
#{652}{}{What can you tell me about William?}
{652}{}{关于威廉，你能告诉我什么？}
#{653}{}{Could you please tell me something about the Wild Paradise? I've heard you used to work there.}
{653}{}{你能告诉我一些关于野生天堂的事吗？我听说你以前在那里工作。}
#{654}{}{[Try to slit her throat before she can call for help.]}
{654}{}{[在她呼救之前割断她的喉咙。]}
#{655}{}{Vex wants one of William's wives dead. Might as well be you.}
{655}{}{维克斯想要威廉的一个妻子死。也许是你。}
#{656}{}{I'd better get going.}
{656}{}{我得走了。}
#{700}{}{I don't really know anything. William and Doreen came from there, but they don't want to talk about it. Maybe because it was destroyed by ghouls. Who wants to talk about something like that?}
{700}{}{我什么都不知道。威廉和多琳是从那里来的，但他们不想谈这个。可能是因为它被僵尸摧毁了。谁想谈那样的事？}
#{701}{}{How do you and Doreen get along?}
{701}{}{你和多琳相处得怎么样？}
#{702}{}{What can you tell me about William?}
{702}{}{关于威廉，你能告诉我什么？}
#{703}{}{Could you please tell me something about the Wild Paradise? I've heard you used to work there.}
{703}{}{你能告诉我一些关于野生天堂的事吗？我听说你以前在那里工作。}
#{704}{}{[Try to slit her throat before she can call for help.]}
{704}{}{[在她呼救之前割断她的喉咙。]}
#{705}{}{Vex wants one of William's wives dead. Might as well be you.}
{705}{}{维克斯想要威廉的一个妻子死。也许是你。}
#{706}{}{I'd better get going.}
{706}{}{我得走了。}
#{750}{}{My husband is a great man, he helps the other immigrants as much as he can. And if anyone says otherwise, he's wrong. I'm glad for every moment I can be with him. I just wish he'd appreciate me more... [She sighs almost imperceptibly.] In more than one meaning.}
{750}{}{我丈夫是个伟大的人，他尽可能地帮助其他移民。如果有人不这么说，他错了。我很高兴能和他在一起。我只希望他能更感激我。。。[她几乎不知不觉地叹了口气]不止一个意思。}
#{751}{}{Maybe I could... I must admit I came here with a certain goal. I've heard of you, and I wished to see you, to know more about you. And finally meeting you made me want that even more. You're so beautiful...}
{751}{}{也许我可以。。。我必须承认我来这里是有目的的。我听说过你，我希望见到你，了解你更多。最后见到你让我更加渴望。你真漂亮。。。}
#{752}{}{Maybe I could... I must admit I came here with a certain goal. I've heard of you, and I wished to see you, to know more about you. And finally meeting you made me want that even more. You're so beautiful...}
{752}{}{也许我可以。。。我必须承认我来这里是有目的的。我听说过你，我希望见到你，了解你更多。最后见到你让我更加渴望。你真漂亮。。。}
#{753}{}{Who else did you have in mind when you said William doesn't like strangers visiting you?}
{753}{}{当你说威廉不喜欢陌生人来拜访你时，你还想到了谁？}
#{754}{}{Could you please tell me something about the Wild Paradise? I've heard you used to work there.}
{754}{}{你能告诉我一些关于野生天堂的事吗？我听说你以前在那里工作。}
#{755}{}{[Try to slit her throat before she can call for help.]}
{755}{}{[在她呼救之前割断她的喉咙。]}
#{756}{}{Vex wants one of William's wives dead. Might as well be you.}
{756}{}{维克斯想要威廉的一个妻子死。也许是你。}
#{757}{}{I'd better get going.}
{757}{}{我得走了。}
#{800}{}{Madame Chow, who's in charge of that establishment, is a terrible woman. Oh, she's nice to her customers, sure, they can cripple her girls for all she cares, but she chews out her employees for every little thing. Like if they take something small from a customer, or if, according to her, they didn't satisfy him enough. Like the drunk horny pigs care about all the techniques that sloe-eyed bitch forced us to learn! [She stops herself.] Eh... I'm sorry, I... Let's not talk about that, in the end, the Wild Paradise was where I met William, so it wasn't all bad. My life's a lot better now.}
{800}{}{负责那个机构的周太太是个可怕的女人。哦，她对她的顾客很好，当然，她们会让她的女儿们一瘸一拐的，但她对员工的每一件小事都很挑剔。比如，如果他们从顾客那里拿走一些小东西，或者，根据她的说法，他们没有让顾客满意。就像喝醉了的角质猪关心的所有技术，懒眼婊子强迫我们学习！[她停下来]呃。。。对不起，我。。。我们先别说了，最后，荒野天堂是我遇见威廉的地方，所以也不全是坏事。我现在的生活好多了。}
#{801}{}{Who else did you have in mind when you said William doesn't like strangers visiting you?}
{801}{}{当你说威廉不喜欢陌生人来拜访你时，你还想到了谁？}
#{802}{}{What can you tell me about William?}
{802}{}{关于威廉，你能告诉我什么？}
#{803}{}{[Try to slit her throat before she can call for help.]}
{803}{}{[在她呼救之前割断她的喉咙。]}
#{804}{}{Vex wants one of William's wives dead. Might as well be you.}
{804}{}{维克斯想要威廉的一个妻子死。也许是你。}
#{805}{}{I'd better get going.}
{805}{}{我得走了。}
#{850}{}{[She smiles lightly.] You're sweet. I like having some fun with someone other than my husband. Don't get me wrong, William is a great lover. If his heart was about to burst, he could just buy a new one. But a woman like me needs a little change now and then. But I wouldn't want him to hurt you if he found out about it. I'm sure you're not that interested in me, perhaps you could pay for a girl in the Wild Paradise instead.}
{850}{}{[她微微一笑]你真好。我喜欢和我丈夫以外的人一起玩。别误会，威廉是个好情人。如果他的心脏快要破裂，他可以买一个新的。但是像我这样的女人时不时需要一些改变。但如果他发现了我不想让他伤害你。我敢肯定你对我没那么感兴趣，也许你可以花钱买一个在野外天堂的女孩。}
#{851}{}{[She smiles lightly.] You're sweet. I like having some fun with someone other than my husband. Don't get me wrong, William is a great lover. If his heart was about to burst, he could just buy a new one. But a woman like me needs a little change now and then. And what greater change than spending a few intimate moments with another woman... But I wouldn't want him to hurt you if he found out about it. I'm sure you're not that interested in me, perhaps you could pay for a girl in the Wild Paradise instead.}
{851}{}{[她微微一笑]你真好。我喜欢和我丈夫以外的人一起玩。别误会，威廉是个好情人。如果他的心脏快要破裂，他可以买一个新的。但是像我这样的女人时不时需要一些改变。还有什么比和另一个女人亲密相处更大的改变。。。但如果他发现了我不想让他伤害你。我敢肯定你对我没那么感兴趣，也许你可以花钱买一个在野外天堂的女孩。}
#{852}{}{I'm very interested in you. What if I paid you, instead?}
{852}{}{我对你很感兴趣。如果我付钱给你呢？}
#{853}{}{You're right, going to the Wild Paradise is a better idea.}
{853}{}{你说得对，去野生天堂是个更好的主意。}
#{854}{}{I'm very interested in you. What if I paid you, instead?}
{854}{}{我对你很感兴趣。如果我付钱给你呢？}
#{900}{}{I see you're serious. Alright, darling, let's meet in the alley between the Wild Paradise and the weapon shop. It's not the coziest place, but nobody will see us there; we'll be all alone. I know how to slip out without the guards noticing, William won't know a thing. I'll be waiting for you there around ten o'clock in the evening, but don't keep me waiting too long. And bring 500 caps. My husband doesn't always appreciate me as much as I deserve. Don't make the same mistake.}
{900}{}{我看你是认真的。好吧，亲爱的，让我们在荒野天堂和武器店之间的小巷见面。那不是最舒适的地方，但是没有人会在那里看到我们；我们会一个人呆着。我知道怎么在警卫不注意的情况下溜出去，威廉什么都不会知道。晚上十点左右我会在那里等你，但不要让我等太久。带上500顶瓶盖。我丈夫并不总是像我应得的那样感激我。别犯同样的错误。}
#{901}{}{I see you're serious. Alright, darling, let's meet in the alley between the Wild Paradise and the weapon shop. It's not the coziest place, but nobody will see us there; we'll be all alone. I know how to slip out without the guards noticing, William won't know a thing. I'll be waiting for you there tomorrow around ten o'clock in the evening, but don't keep me waiting too long. And bring 500 caps. My husband doesn't always appreciate me as much as I deserve. Don't make the same mistake.}
{901}{}{我看你是认真的。好吧，亲爱的，让我们在荒野天堂和武器店之间的小巷见面。那不是最舒适的地方，但是没有人会在那里看到我们；我们会一个人呆着。我知道怎么在警卫不注意的情况下溜出去，威廉什么都不会知道。我明天晚上十点左右在那里等你，但不要让我等太久。带上500顶瓶盖。我丈夫并不总是像我应得的那样感激我。别犯同样的错误。}
#{902}{}{I see it's probably not the first time you're doing this kind of thing. Alright, deal, I'm looking forward to it.}
{902}{}{我知道这可能不是你第一次做这种事了。好吧，成交，我很期待。}
#{950}{}{What? You'd really rather pay for one of Chow's girls than... Get out. [She's suddenly mad at you and you don't even know why.] Leave, before I call the guards and my husband learns you're bothering me.}
{950}{}{什么？你真的宁愿付周星驰的一个女孩的钱也不愿意。。。走出。[她突然生你的气，你甚至不知道为什么。]离开，在我打电话给警卫，我丈夫知道你在烦我之前。}
#{951}{}{Whatever you say. Bye.}
{951}{}{不管你说什么。再见。}
#{952}{}{I'm not in the mood to play your games. Time to play by my rules, bitch.}
{952}{}{我没心情玩你的游戏。是时候遵守我的规则了，婊子。}
#{1000}{}{I don't want to talk to you. I don't even want to look at you. Leave.}
{1000}{}{我不想和你说话。我甚至不想看你。离开。}
#{1001}{}{[Try to slit her throat before she can call for help.]}
{1001}{}{[在她呼救之前割断她的喉咙。]}
#{1002}{}{Vex wants one of William's wives dead. Might as well be you.}
{1002}{}{维克斯想要威廉的一个妻子死。也许是你。}
#{1003}{}{OK, I'm leaving.}
{1003}{}{好的，我要走了。}
#{1004}{}{Weelliam! Bash you!}
{1004}{}{威利安！揍你！}
#{1005}{}{Uf.}
{1005}{}{佛罗里达州。}
#{1006}{}{I waited in that filthy alley for over an hour and you didn't even show up?! I don't want to talk to you. I don't even want to look at you. Leave.}
{1006}{}{我在那肮脏的巷子里等了一个多小时，你都没出现？！我不想和你说话。我甚至不想看你。离开。}
#{1050}{}{[You try to cover her mouth with your left hand and slit her throat with your right, but Penny is faster than you. She quickly blocks your left hand and steps back, out of the reach of your blade.] Guards! [After shouting, she turns to you.] In the Wild Paradise I learned how to recognize when someone's about to try something like that, and how to defend myself. You'll pay for that, bastard.}
{1050}{}{[你试着用左手捂住她的嘴，用右手割开她的喉咙，但佩妮比你快。她迅速挡住你的左手，退后一步，让你的刀锋够不着！[喊叫之后，她转向你]在荒野的天堂里，我学会了如何识别别人什么时候要尝试这样的事情，以及如何保护自己。你会为此付出代价的，混蛋。}
#{1051}{}{[You try to cover her mouth with your left hand and slit her throat with your right, but Penny is faster than you. She quickly blocks your left hand and steps back, out of the reach of your blade.] Guards! [After shouting, she turns to you.] In the Wild Paradise I learned how to recognize when someone's about to try something like that, and how to defend myself. You'll pay for that, bitch.}
{1051}{}{[你试着用左手捂住她的嘴，用右手割开她的喉咙，但佩妮比你快。她迅速挡住你的左手，退后一步，让你的刀锋够不着！[喊叫之后，她转向你]在荒野的天堂里，我学会了如何识别别人什么时候要尝试这样的事情，以及如何保护自己。你会为此付出代价的，婊子。}
#{1052}{}{Fine, I guess we'll have to do this the loud way.}
{1052}{}{好吧，我想我们得大声点。}
#{1100}{}{[You cover Penny's mouth with your left hand and slit her throat with your right. You were so fast she didn't have any time to react. You catch her by the shoulders before her body falls to the floor and quietly put her down.]}
{1100}{}{[你用左手捂住佩妮的嘴，用右手割断她的喉咙。你太快了，她没时间反应。你抓住她的肩膀，在她的身体掉到地板上之前，悄悄地把她放下}
#{1101}{}{[You cover Penny's mouth with your left hand and slit her throat with your right. You were so fast she didn't have any time to react. You catch her by the shoulders before her body falls to the floor and quietly put her down.]}
{1101}{}{[你用左手捂住佩妮的嘴，用右手割断她的喉咙。你太快了，她没时间反应。你抓住她的肩膀，在她的身体掉到地板上之前，悄悄地把她放下}
#{1102}{}{That's that then.}
{1102}{}{那就这样吧。}
#{1150}{}{Hi, I'm glad to see you again. Talking to someone is always so refreshing. I don't have many visitors because William doesn't like strangers loitering among us.}
{1150}{}{嗨，很高兴再次见到你。与人交谈总是让人耳目一新。我的访客不多，因为威廉不喜欢陌生人在我们中间闲逛。}
#{1151}{}{'Us'? Who else do you mean?}
{1151}{}{“我们”？你还说谁？}
#{1152}{}{What can you tell me about William?}
{1152}{}{关于威廉，你能告诉我什么？}
#{1153}{}{Could you please tell me something about the Wild Paradise? I've heard you used to work there.}
{1153}{}{你能告诉我一些关于野生天堂的事吗？我听说你以前在那里工作。}
#{1154}{}{[Try to slit her throat before she can call for help.]}
{1154}{}{[在她呼救之前割断她的喉咙。]}
#{1155}{}{Vex wants one of William's wives dead. Might as well be you.}
{1155}{}{维克斯想要威廉的一个妻子死。也许是你。}
#{1156}{}{Penny, baby, how about another meeting?}
{1156}{}{佩妮，宝贝，下次见面怎么样？}
#{1157}{}{I'd better get going. Bye.}
{1157}{}{我得走了。再见。}
#{1158}{}{Weelliam! Bash you!}
{1158}{}{威利安！揍你！}
#{1159}{}{Uf.}
{1159}{}{佛罗里达州。}
#{1200}{}{[She hugs you.] Hi, honey, I almost couldn't take the waiting. [She kisses you.] You do have 500 caps, yes?}
{1200}{}{[她拥抱你]嗨，亲爱的，我差点受不了等待。[她吻你]你有500顶瓶盖，是吗？}
#{1201}{}{Yes, I do.}
{1201}{}{是的，我知道。}
#{1202}{}{Nope.}
{1202}{}{不。}
#{1203}{}{Ughe?}
{1203}{}{呃？}
#{1250}{}{What?! But we had an agreement. It's not easy for me to sneak out of the house unnoticed. Your loss, you missed out on a lot, and you'll never have the opportunity again. [She turns to leave.]}
{1250}{}{什么？！但我们有个协议。我不容易不被注意就溜出去。你的损失，你错过了很多，你再也没有机会了。[她转身离开。]}
#{1251}{}{What?! But we had an agreement. It's not easy for me to sneak out of the house unnoticed. Your loss, you missed out on a lot, and you'll never have the opportunity again. [She turns to leave.]}
{1251}{}{什么？！但我们有个协议。我不容易不被注意就溜出去。你的损失，你错过了很多，你再也没有机会了。[她转身离开。]}
#{1252}{}{You're not going anywhere. I just needed to lure you somewhere I could take you out quietly.}
{1252}{}{你哪儿也不能去。我只是想引诱你到一个我可以悄悄带你出去的地方。}
#{1253}{}{You're not going anywhere. I just needed to lure you somewhere I could take you out quietly.}
{1253}{}{你哪儿也不能去。我只是想引诱你到一个我可以悄悄带你出去的地方。}
#{1254}{}{[Let her leave.]}
{1254}{}{[让她离开。]}
#{1300}{}{I knew you wouldn't disappoint me. Come on, give them to me, let's have some fun. You'll like it more than anything you've ever experienced.}
{1300}{}{我知道你不会让我失望的。来吧，把它们给我，让我们玩个痛快。你会比你经历过的任何事情都更喜欢它。}
#{1301}{}{I knew you wouldn't disappoint me. Come on, give them to me, let's have some fun. You'll like it more than anything you've ever experienced.}
{1301}{}{我知道你不会让我失望的。来吧，把它们给我，让我们玩个痛快。你会比你经历过的任何事情都更喜欢它。}
#{1302}{}{[Pay and enjoy yourself.]}
{1302}{}{[尽情享受吧。]}
#{1303}{}{No thanks. I just needed to lure you somewhere I could take you out quietly.}
{1303}{}{不用了，谢谢。我只是想引诱你到一个我可以悄悄带你出去的地方。}
#{1304}{}{No thanks. I just needed to lure you somewhere I could take you out quietly.}
{1304}{}{不用了，谢谢。我只是想引诱你到一个我可以悄悄带你出去的地方。}
#{1350}{}{[Sex with her was really something. You're both panting heavily now, sweating. When you finish dressing, Penny kisses you goodbye.]}
{1350}{}{[和她做爱真的很了不起。你们现在都气喘吁吁，大汗淋漓。当你穿完衣服，佩妮吻你说再见。】}
#{1351}{}{[Sex with her was really something. You're both panting heavily now, sweating. When you finish dressing, Penny kisses you goodbye.]}
{1351}{}{[和她做爱真的很了不起。你们现在都气喘吁吁，大汗淋漓。当你穿完衣服，佩妮吻你说再见。】}
#{1352}{}{[Try to strangle her.]}
{1352}{}{[试图勒死她。]}
#{1353}{}{Can we see each other again?}
{1353}{}{我们能再见面吗？}
#{1354}{}{That's enough, now's the time to take you out.}
{1354}{}{够了，现在该带你出去了。}
#{1355}{}{[Sex with her was really something. Now you're both panting heavily, sweating. When you finish dressing, Penny hugs you and whispers into your ear.] That was amazing. I wish I had clients like you when I was still working for Madame Chow. All that flattery I had to give them would've been sincere for once.}
{1355}{}{[和她做爱真的很了不起。现在你们都气喘吁吁，大汗淋漓。当你穿完衣服，佩妮拥抱着你，对着你的耳朵低声说]真是太棒了。我希望在我还在为周太太工作的时候有你这样的客户。我要对他们说的那些恭维话只会是真诚的一次。}
#{1356}{}{[Sex with her was really something. Now you're both panting heavily, sweating. When you finish dressing, Penny hugs you and whispers into your ear.] That was amazing. I wish I had clients like you when I was still working for Madame Chow. All that flattery I had to give them would've been sincere for once.}
{1356}{}{[和她做爱真的很了不起。现在你们都气喘吁吁，大汗淋漓。当你穿完衣服，佩妮拥抱着你，对着你的耳朵低声说]真是太棒了。我希望在我还在为周太太工作的时候有你这样的客户。我要对他们说的那些恭维话只会是真诚的一次。}
#{1400}{}{[Still inflamed, Penny doesn't notice in time that you're not stroking her, but trying to strangle her. She opens her mouth to scream, but only wheezing comes out. She starts beating your chest, trying to pull your hands away. Since you're not strong enough, she manages to break from your hold.] You'll pay for that. [She hisses scornfully.]}
{1400}{}{[仍然发炎，佩妮没有及时注意到你没有抚摸她，而是试图勒死她。她张开嘴尖叫，但只发出喘息声。她开始拍你的胸脯，想把你的手拉开。因为你不够强壮，她设法挣脱了你的束缚。[她轻蔑地嘶嘶]}
#{1401}{}{[Still inflamed, Penny doesn't notice in time that you're not stroking her, but trying to strangle her. She opens her mouth to scream, but only wheezing comes out. She starts beating your chest, trying to pull your hands away. Since you're not strong enough, she manages to break from your hold.] You'll pay for that. [She hisses scornfully.]}
{1401}{}{[仍然发炎，佩妮没有及时注意到你没有抚摸她，而是试图勒死她。她张开嘴尖叫，但只发出喘息声。她开始拍你的胸脯，想把你的手拉开。因为你不够强壮，她设法挣脱了你的束缚。[她轻蔑地嘶嘶]}
#{1402}{}{Oh well, I'll just take you out in a different way.}
{1402}{}{哦，好吧，我就换个方式带你出去。}
#{1450}{}{[Still inflamed, Penny doesn't notice in time that you're not stroking her, but trying to strangle her. She opens her mouth to scream, but only wheezing comes out. She starts beating your chest, trying to pull your hands away, but she's not strong enough. After over a minute, you're holding a dead body, which collapses on the ground as soon as you let go.]}
{1450}{}{[仍然发炎，佩妮没有及时注意到你没有抚摸她，而是试图勒死她。她张开嘴尖叫，但只发出喘息声。她开始捶打你的胸部，试图把你的手拉开，但她不够强壮。过了一分钟，你手里拿着一具尸体，你一松手，尸体就倒在地上。]}
#{1451}{}{[Still inflamed, Penny doesn't notice in time that you're not stroking her, but trying to strangle her. She opens her mouth to scream, but only wheezing comes out. She starts beating your chest, trying to pull your hands away, but she's not strong enough. After over a minute, you're holding a dead body, which collapses on the ground as soon as you let go.]}
{1451}{}{[仍然发炎，佩妮没有及时注意到你没有抚摸她，而是试图勒死她。她张开嘴尖叫，但只发出喘息声。她开始捶打你的胸部，试图把你的手拉开，但她不够强壮。过了一分钟，你手里拿着一具尸体，你一松手，尸体就倒在地上。]}
#{1452}{}{That's that then.}
{1452}{}{那就这样吧。}
#{1500}{}{Sure, why not. You can afford it, right? Visit me in my house again and we'll arrange something. I could sneak out of the house once more. One of my husband's guards will do anything for me. He's so sweet... Almost like you. Bye.}
{1500}{}{当然，为什么不呢。你买得起，对吧？再到我家来看我，我们会安排一些事情的。我可以再溜出去一次。我丈夫的一个警卫会为我做任何事。他真可爱。。。几乎和你一样。再见。}
#{1501}{}{See you.}
{1501}{}{再见。}
#{1502}{}{You know what? I'd rather kill you right now.}
{1502}{}{你知道吗？我宁愿现在就杀了你。}
#{1550}{}{Maybe I told you that I like change. We're not meeting like that again, sorry, you just don't interest me anymore. You'll only have a memory of me. Bye.}
{1550}{}{也许我告诉过你我喜欢改变。我们不会再这样见面了，对不起，我对你不再感兴趣了。你只会记得我。再见。}
#{1551}{}{Goodbye.}
{1551}{}{再见。}
#{1552}{}{Memory of a corpse, bitch.}
{1552}{}{一具尸体的记忆，婊子。}
#{1600}{}{I want you too, darling. We'll meet tonight around ten o'clock in the alley between the Wild Paradise and the weapon shop. I'll be waiting.}
{1600}{}{我也想要你，亲爱的。我们今晚十点左右在野生天堂和武器店之间的小巷见面。我会等的。}
#{1601}{}{I want you too, darling. We'll meet tomorrow around ten o'clock in the evening in the alley between the Wild Paradise and the weapon shop. I'll be waiting.}
{1601}{}{我也想要你，亲爱的。我们明天晚上10点左右在野生天堂和武器店之间的小巷见面。我会等的。}
#{1602}{}{I'm looking forward to it.}
{1602}{}{我很期待。}
#{1650}{}{You poor thing. I'm Penny, William's wife. You probably don't know he doesn't like when strangers visit us. Still, it's very brave of you to come here.}
{1650}{}{你这个可怜的家伙。我是彭妮，威廉的妻子。你可能不知道他不喜欢陌生人来看我们。不过，你来这儿真是太勇敢了。}
#{1651}{}{You poor thing. I'm Penny, William's wife. You probably don't know he doesn't like when strangers visit us. Still, it's very brave of you to come here.}
{1651}{}{你这个可怜的家伙。我是彭妮，威廉的妻子。你可能不知道他不喜欢陌生人来看我们。不过，你来这儿真是太勇敢了。}
#{1652}{}{Weelliam! Bash you!}
{1652}{}{威利安！揍你！}
#{1653}{}{ much brave. Hehee. Bai.}
{1653}{}{非常勇敢。嘿嘿。白。}
#{1700}{}{What?! We had an agreement, and you come in that state? It's not easy for me to sneak out of the house unnoticed. Your loss, you missed out on a lot, and you'll never have the opportunity again. [She turns to leave.]}
{1700}{}{什么？！我们说好了，你就来了？我不容易不被注意就溜出去。你的损失，你错过了很多，你再也没有机会了。[她转身离开。]}
#{1701}{}{What?! We had an agreement, and you come in that state? It's not easy for me to sneak out of the house unnoticed. Your loss, you missed out on a lot, and you'll never have the opportunity again. [She turns to leave.]}
{1701}{}{什么？！我们说好了，你就来了？我不容易不被注意就溜出去。你的损失，你错过了很多，你再也没有机会了。[她转身离开。]}
#{1702}{}{Noooo Weelliam! Bash you!}
{1702}{}{不，威利安！揍你！}
#{1703}{}{[Let her leave.]}
{1703}{}{[让她离开。]}
