#{100}{}{You see a security robot.}
{100}{}{你看到一个安保机器人。}
#{200}{}{The robot isn't doing anything.}
{200}{}{机器人什么也没做。}
#{201}{}{The robot is active and ready to execute the commands it receives. It doesn't have any commands right now, though.}
{201}{}{机器人处于激活状态，并准备执行它收到的命令。不过，它现在没有任何命令。}
#{202}{}{The robot looks hostile.}
{202}{}{机器人看起来充满敌意。}
#{203}{}{The robot is active and is currently in search and destroy mode.}
{203}{}{机器人已启动，目前处于搜索和摧毁模式。}
