#{100}{}{You see a man in shabby rags.}
{100}{}{你看到一个衣衫褴褛的人。}
#{150}{}{You see Rua the shaman.}
{150}{}{你看到巫师阮了。}
#{200}{}{You see an elderly man in dirty clothes. An unpleasant smell emanates from him.}
{200}{}{你看到一个穿着脏衣服的老人。他身上散发出一股难闻的气味。}
#{201}{}{ He is stunned.}
{201}{}{他惊呆了。}
#{250}{}{You see Rua the shaman. It seems his mind is wandering somewhere else again.}
{250}{}{你看到巫师阮了。他好像又在想别的事情了。}
#{300}{}{Rua has no words for outsider.}
{300}{}{鲁阿对局外人说不出话来。}
#{301}{}{Rua has no words for outsider.}
{301}{}{鲁阿对局外人说不出话来。}
#{302}{}{Outsider may have done the tribe a great service, but on the inside, he has not changed. Rua will be watching him.}
{302}{}{局外人也许为部落做了很大的贡献，但在内部，他没有改变。Rua会看着他的。}
#{303}{}{Outsider may have done the tribe a great service, but on the inside, she has not changed. Rua will be watching her.}
{303}{}{局外人也许为部落做了很大的贡献，但在内部，她没有改变。Rua会看着她的。}
#{304}{}{This is our ancestors' holy ground. It must not be desecrated!}
{304}{}{这是我们祖先的圣地。不能亵渎！}
#{350}{}{Your luck has been increased by 1 point.}
{350}{}{你的运气提高了1点。}
#{351}{}{Your luck has been lowered by 1 point.}
{351}{}{你的运气降低了1分。}
#{400}{}{Ancestors shall avenge Rua!}
{400}{}{祖先要为阮报仇！}
#{420}{}{Rua loses consciousness and falls lifelessly to the ground.}
{420}{}{阮失去知觉，毫无生气地倒在地上。}
#{500}{}{[The old man pays you no attention. He's staring into space, occasionally mumbling some incoherent words. He does not seem to be in his senses.]}
{500}{}{[老人根本不理你。他凝视着太空，偶尔喃喃自语一些语无伦次的话。他似乎没有感觉到。]}
#{501}{}{Erm... Who are you?}
{501}{}{呃。。。你是谁？}
#{502}{}{[Leave.]}
{502}{}{[离开]}
#{503}{}{Hue?!}
{503}{}{色调？！}
#{550}{}{[He stops muttering and looks at you with surprise.] Outsider comes to shaman Rua. He has disturbed him from seeing spirits of ancestors. What does he want?}
{550}{}{[他不再喃喃自语，惊讶地看着你]外人来到阮萨满身边。他打扰了他看祖先的鬼魂。他想要什么？}
#{551}{}{[He stops muttering and looks at you with surprise.] Outsider comes to shaman Rua. She has disturbed him from seeing spirits of ancestors. What does she want?}
{551}{}{[他不再喃喃自语，惊讶地看着你]外人来到阮萨满身边。她打扰了他看祖先的鬼魂。她想要什么？}
#{552}{}{You can talk to the dead? What do they say?}
{552}{}{你能和死人说话吗？他们怎么说？}
#{553}{}{I'd rather not have anything to do with you. Goodbye, looney.}
{553}{}{我不想和你有任何关系。再见，鲁尼。}
#{554}{}{You blah blah wif deads?}
{554}{}{你说的那些废话？}
#{555}{}{Ugg, nuffin! Bai.}
{555}{}{乌格，努芬！白。}
#{600}{}{[He scowls.] Talking to ancestors is no simple thing. Rua must come close to their bones, mix the right herbs and focus his mind to create a bond. It is difficult, but the tribe needs ancestors' guidance. Without it, the tribe would forget their traditions, and even Rua could no longer help.}
{600}{}{[他愁眉不展]和祖先说话可不是件简单的事。Rua必须靠近他们的骨头，混合正确的草药，集中他的思想来创造一个纽带。这很难，但部落需要祖先的指引。没有它，部落就会忘记他们的传统，甚至连阮也帮不上忙了。}
#{601}{}{Traditions? Tell me about them.}
{601}{}{传统？告诉我关于他们的事。}
#{602}{}{What do you mean even you couldn't help?}
{602}{}{连你都帮不上忙是什么意思？}
#{603}{}{I see. I really gotta run now, though. Bye!}
{603}{}{我懂了。不过，我现在真的得走了。再见！}
#{604}{}{Ech?!}
{604}{}{呃？！}
#{650}{}{Rua's tribe has many old and wise traditions. But outsider would not understand most. It is enough to know that they tell us to be cautious, so every member of tribe is cautious of outsider. They also forbid relations with city folk, so outsider should stay away from men and women of the tribe.}
{650}{}{阮氏部落有许多古老而睿智的传统。但局外人对此并不理解。只要知道他们告诉我们要小心就够了，所以部落里的每个成员都要小心外人。他们也禁止与城里人交往，所以外人应该远离部落的男人和女人。}
#{651}{}{Rua's tribe has many old and wise traditions. But outsider would not understand most. It is enough to know that they tell us to be cautious, so every member of tribe is cautious of outsider. They also forbid relations with city folk, so outsider should stay away from men and women of the tribe.}
{651}{}{阮氏部落有许多古老而睿智的传统。但局外人对此并不理解。只要知道他们告诉我们要小心就够了，所以部落里的每个成员都要小心外人。他们也禁止与城里人交往，所以外人应该远离部落的男人和女人。}
#{652}{}{No need to worry. What did you say about your ancestors helping you?}
{652}{}{不用担心。你说你的祖先帮了你什么？}
#{653}{}{Whatever. I'd best get going.}
{653}{}{无论什么。我最好走了。}
#{700}{}{Ancestors give Rua the power to do things that help the tribe. He can heal wounds, and look into people's souls... [He stops talking and looks you in the eyes.] If outsider gives Rua his hand, he can look into his soul as well.}
{700}{}{祖先赋予了鲁阿力量去做帮助部落的事情。他可以治愈伤口，观察人们的灵魂。。。[他停止说话，看着你的眼睛]如果外人伸出手来，他也能看到自己的灵魂。}
#{701}{}{Ancestors give Rua the power to do things that help the tribe. He can heal wounds, and look into people's souls... [He stops talking and looks you in the eyes.] If friend gives Rua his hand, he can look into his soul as well.}
{701}{}{祖先赋予了鲁阿力量去做帮助部落的事情。他可以治愈伤口，观察人们的灵魂。。。[他停止说话，直视你的眼睛]如果朋友伸出手来，他也能看到自己的灵魂。}
#{702}{}{Ancestors give Rua the power to do things that help the tribe. He can heal wounds, and look into people's souls... [He stops talking and looks you in the eyes.] If outsider gives Rua her hand, he can look into her soul as well.}
{702}{}{祖先赋予了鲁阿力量去做帮助部落的事情。他可以治愈伤口，观察人们的灵魂。。。[他停止说话，看着你的眼睛]如果外人伸出手来，他也可以看着她的灵魂。}
#{703}{}{Ancestors give Rua the power to do things that help the tribe. He can heal wounds, and look into people's souls... [He stops talking and looks you in the eyes.] If friend gives Rua her hand, he can look into her soul as well.}
{703}{}{祖先赋予了鲁阿力量去做帮助部落的事情。他可以治愈伤口，观察人们的灵魂。。。[他停止了说话，看着你的眼睛]如果朋友伸出手来，他也可以看着她的灵魂。}
#{704}{}{Uhh... Alright then. [Give him your hand.]}
{704}{}{呃。。。那好吧。[把手给他]}
#{705}{}{I doubt that. Goodbye, shaman.}
{705}{}{我对此表示怀疑。再见，萨满。}
#{706}{}{Yaaay!}
{706}{}{耶！}
#{707}{}{Nooo. Bai bai!}
{707}{}{不。白白！}
#{750}{}{[The shaman stares at your hand for a while, muttering some words that make no sense together. Suddenly, he pulls out a knife from somewhere and cuts your wrist.]}
{750}{}{[巫师盯着你的手看了一会儿，嘴里咕哝着一些毫无意义的话。突然，他从某处掏出一把刀，割破了你的手腕}
#{751}{}{[Wait, see what happens.]}
{751}{}{[等等，看看会发生什么。]}
#{752}{}{What the hell are you doing?! [Try to shake him off.]}
{752}{}{你到底在干什么？！[试着摆脱他。]}
#{753}{}{Ouchie!}
{753}{}{哎哟！}
#{800}{}{[Blood starts seeping from your wound. Rua quickly puts a wooden bowl under it and waits until it's filled. He watches the light reflecting on the surface for a while and then drinks from it. Finally, he turns to you.] Rua has seen that outsider is a good man, one who has done many selfless deeds. Ancestors are sure to smile on him in his journey.}
{800}{}{[你的伤口开始渗血。阮很快地把一个木碗放在它下面，等它装满。他看了一会儿反射在水面上的光，然后喝了一口。最后，他转向你，]阮见外人是个好人，做了许多无私的事。祖先们一定会在他的旅途中对他微笑。}
#{801}{}{[Blood starts seeping from your wound. Rua quickly puts a wooden bowl under it and waits until it's filled. He watches the light reflecting on the surface for a while and then drinks from it. Finally, he turns to you.] Rua has seen that friend is a good man, one who has done many selfless deeds. Ancestors are sure to smile on him in his journey.}
{801}{}{[你的伤口开始渗血。阮很快地把一个木碗放在它下面，等它装满。他看了一会儿反射在水面上的光，然后喝了一口。最后，他转向你，]阮看到朋友是个好人，做了很多无私的事。祖先们一定会在他的旅途中对他微笑。}
#{802}{}{[Blood starts seeping from your wound. Rua quickly puts a wooden bowl under it and waits until it's filled. He watches the light reflecting on the surface for a while and then drinks from it. Finally, he turns to you.] Rua has seen that outsider is a good woman, one who has done many selfless deeds. Ancestors are sure to smile on her in her journey.}
{802}{}{[你的伤口开始渗血。阮很快地把一个木碗放在它下面，等它装满。他看了一会儿反射在水面上的光，然后喝了一口。最后，他转向你，]阮见外人是个好女人，做了许多无私的事。在她的旅途中，祖先一定会对她微笑。}
#{803}{}{[Blood starts seeping from your wound. Rua quickly puts a wooden bowl under it and waits until it's filled. He watches the light reflecting on the surface for a while and then drinks from it. Finally, he turns to you.] Rua has seen that friend is a good woman, one who has done many selfless deeds. Ancestors are sure to smile on her in her journey.}
{803}{}{[你的伤口开始渗血。阮很快地把一个木碗放在它下面，等它装满。他看了一会儿反射在水面上的光，然后喝了一口。最后，他转向你，]阮看到朋友是个好女人，做了很多无私的事。在她的旅途中，祖先一定会对她微笑。}
#{804}{}{Ehh, thanks... I think.}
{804}{}{呃，谢谢。。。我想。}
#{805}{}{Hmm... Mucho thanks!}
{805}{}{隐马尔可夫模型。。。非常感谢！}
#{850}{}{[Blood starts seeping from your wound. Rua quickly puts a wooden bowl under it and waits until it's filled. He watches the light reflecting on the surface for a while and then drinks from it. Finally, he turns to you.] Rua has seen that outsider is an indecisive man, one who cannot choose a path to walk on. Ancestors hope that one day, he is able to change that.}
{850}{}{[你的伤口开始渗血。阮很快地把一个木碗放在它下面，等它装满。他看了一会儿反射在水面上的光，然后喝了一口。最后，他转向你，]阮已经看到外人是一个优柔寡断的人，一个不能选择一条路走的人。祖先希望有一天，他能够改变这一点。}
#{851}{}{[Blood starts seeping from your wound. Rua quickly puts a wooden bowl under it and waits until it's filled. He watches the light reflecting on the surface for a while and then drinks from it. Finally, he turns to you.] Rua has seen that friend is an indecisive man, one who cannot choose a path to walk on. Ancestors hope that one day, he is able to change that.}
{851}{}{[你的伤口开始渗血。阮很快地把一个木碗放在它下面，等它装满。他看了一会儿反射在水面上的光，然后喝了一口。最后，他转向你，]阮已经看到朋友是一个优柔寡断的人，一个不能选择一条路走的人。祖先希望有一天，他能够改变这一点。}
#{852}{}{[Blood starts seeping from your wound. Rua quickly puts a wooden bowl under it and waits until it's filled. He watches the light reflecting on the surface for a while and then drinks from it. Finally, he turns to you.] Rua has seen that outsider is an indecisive woman, one who cannot choose a path to walk on. Ancestors hope that one day, she is able to change that.}
{852}{}{[你的伤口开始渗血。阮很快地把一个木碗放在它下面，等它装满。他看了一会儿反射在水面上的光，然后喝了一口。最后，他转向你，]阮已经看到外人是一个优柔寡断的女人，一个不能选择一条路走的女人。祖先希望有一天，她能够改变这种状况。}
#{853}{}{[Blood starts seeping from your wound. Rua quickly puts a wooden bowl under it and waits until it's filled. He watches the light reflecting on the surface for a while and then drinks from it. Finally, he turns to you.] Rua has seen that friend is an indecisive woman, one who cannot choose a path to walk on. Ancestors hope that one day, she is able to change that.}
{853}{}{[你的伤口开始渗血。阮很快地把一个木碗放在它下面，等它装满。他看了一会儿反射在水面上的光，然后喝了一口。最后，他转向你，]阮已经看到朋友是一个优柔寡断的女人，一个不能选择一条路走的女人。祖先希望有一天，她能够改变这种状况。}
#{854}{}{Ehh, thanks then... I think.}
{854}{}{呃，谢谢你。。。我想。}
#{855}{}{Okies.}
{855}{}{好的。}
#{900}{}{[Blood starts seeping from your wound. Rua quickly puts a wooden bowl under it and waits until it's filled. He watches the light reflecting on the surface for a while and then drinks from it. Finally, he turns to you. His face is twisted with anger.] Rua has seen that hatred has possessed outsider. His life is full of violence and vile deeds. Ancestors curse him!}
{900}{}{[你的伤口开始渗血。阮很快地把一个木碗放在它下面，等它装满。他看了一会儿反射在水面上的光，然后喝了一口。最后，他转向你。他的脸因愤怒而扭曲，]阮已经看到仇恨已经占据了局外人。他的生活充满了暴力和恶行。祖先诅咒他！}
#{901}{}{[Blood starts seeping from your wound. Rua quickly puts a wooden bowl under it and waits until it's filled. He watches the light reflecting on the surface for a while and then drinks from it. Finally, he turns to you. His face is twisted with anger.] Rua has seen that hatred has possessed outsider. Her life is full of violence and vile deeds. Ancestors curse her!}
{901}{}{[你的伤口开始渗血。阮很快地把一个木碗放在它下面，等它装满。他看了一会儿反射在水面上的光，然后喝了一口。最后，他转向你。他的脸因愤怒而扭曲，]阮已经看到仇恨已经占据了局外人。她的生活充满了暴力和恶行。祖先诅咒她！}
#{902}{}{Go to hell, you're nothing but a lying quack.}
{902}{}{去死吧，你不过是个说谎的庸医。}
#{903}{}{What a load of crap. Let's see what those ancestors of yours say when I kill you and dance on your corpse.}
{903}{}{真是一派胡言。我杀了你，在你的尸体上跳舞，看看你的祖先怎么说。}
#{904}{}{What a load of crap. Let's see what those ancestors of yours say when I kill you and dance on your corpse.}
{904}{}{真是一派胡言。我杀了你，在你的尸体上跳舞，看看你的祖先怎么说。}
#{905}{}{Shaman dumb! Me go.}
{905}{}{萨满哑巴！让我走。}
#{906}{}{Me crush them! Shaman too!}
{906}{}{让我压扁他们！萨满也是！}
#{950}{}{[It seems he is not in his senses; he doesn't let go of your hand.]}
{950}{}{[他似乎没有感觉到；他没有放开你的手。]}
#{951}{}{[Wait, see what happens.]}
{951}{}{[等等，看看会发生什么。]}
#{952}{}{Let go you freak! [Strike him with your free hand.]}
{952}{}{放开你这个怪胎！[用你的自由之手打他。]}
#{1000}{}{Why does outsider disturb Rua again? Can he not see that he is trying to talk to spirits of ancestors?}
{1000}{}{为什么外人又来打扰阮？难道他看不出他在试图与祖先的灵魂对话吗？}
#{1001}{}{Why does outsider disturb Rua again? Can she not see that he is trying to talk to spirits of ancestors?}
{1001}{}{为什么外人又来打扰阮？难道她看不出他在试图和祖先的灵魂对话吗？}
#{1002}{}{You can talk to the dead? What do they say?}
{1002}{}{你能和死人说话吗？他们怎么说？}
#{1003}{}{Why do you need to talk to them anyway?}
{1003}{}{你为什么要和他们谈谈？}
#{1004}{}{I'm curious if you know anything about the people that attacked your hunters. Any leads?}
{1004}{}{我很好奇你是否知道袭击你猎人的人的事。有线索吗？}
#{1005}{}{My apologies. I'll leave now.}
{1005}{}{我很抱歉。我现在就走。}
#{1006}{}{You blah blah wif deads?}
{1006}{}{你说的那些废话？}
#{1007}{}{Ugg, sorries! Bai.}
{1007}{}{对不起！白。}
#{1050}{}{Rua said that before. Tribe needs ancestors' guidance. Without it, the tribe would forget their traditions, and he could no longer help.}
{1050}{}{阮之前说过。部落需要祖先的指引。没有它，部落就会忘记他们的传统，他也帮不上忙了。}
#{1051}{}{Traditions? Tell me more about them.}
{1051}{}{传统？告诉我更多关于他们的事。}
#{1052}{}{What do you mean you couldn't help?}
{1052}{}{你不能帮忙是什么意思？}
#{1053}{}{I see. I really gotta run now, though. Bye!}
{1053}{}{我懂了。不过，我现在真的得走了。再见！}
#{1100}{}{Why does outsider disturb Rua again? Has he found enough courage to let him look into his soul?}
{1100}{}{为什么外人又来打扰阮？他有足够的勇气让他审视自己的灵魂吗？}
#{1101}{}{Why does outsider disturb Rua again? Has she found enough courage to let him look into her soul?}
{1101}{}{为什么外人又来打扰阮？她是否有足够的勇气让他审视她的灵魂？}
#{1102}{}{Well... Yes. [Give him your hand.]}
{1102}{}{好。。。对。[把手给他]}
#{1103}{}{Maybe later. Now, I'd rather know if you know anything about your hunters disappearing. Any leads?}
{1103}{}{也许以后吧。现在，我想知道你是否知道你的猎人消失了。有线索吗？}
#{1104}{}{No way in hell. Bye, shaman.}
{1104}{}{绝对不行。再见，萨满。}
#{1105}{}{Yups!}
{1105}{}{是的！}
#{1106}{}{Noes! Bai.}
{1106}{}{不！白。}
#{1150}{}{Why does outsider return to shaman?}
{1150}{}{外人为什么要回归萨满？}
#{1151}{}{Why does outsider return to shaman?}
{1151}{}{外人为什么要回归萨满？}
#{1152}{}{I'm curious if you know anything about the people that attacked your hunters. Any leads?}
{1152}{}{我很好奇你是否知道袭击你猎人的人的事。有线索吗？}
#{1153}{}{Just dropping by. See you later, Rua.}
{1153}{}{只是顺道过来。再见，鲁阿。}
#{1154}{}{Why nots! Seeya.}
{1154}{}{为什么不呢！再见。}
#{1200}{}{Rua welcomes tribe friend. He and ancestors are grateful for his help. Now that its enemies lie dead, the tribe will surely fare much better.}
{1200}{}{Rua欢迎部落朋友。他和他的祖先都很感激他的帮助。既然敌人死了，这个部落肯定会过得更好。}
#{1201}{}{Rua welcomes tribe friend. He and ancestors are grateful for her help. Now that its enemies lie dead, the tribe will surely fare much better.}
{1201}{}{Rua欢迎部落朋友。他和祖先们都很感激她的帮助。既然敌人死了，这个部落肯定会过得更好。}
#{1202}{}{I hope so. Thanks.}
{1202}{}{希望如此。谢谢。}
#{1203}{}{Dat right! Thankses.}
{1203}{}{没错！谢谢。}
#{1250}{}{Rua wants to thank outsider. He and ancestors are grateful for what he has done for the tribe. From now on, he shall forever be tribe friend. Gurgan would surely be pleased with him. Though his death was a great loss for the tribe, he died fighting for a good thing. Now that its enemies are dead, the tribe will surely fare much better.}
{1250}{}{阮想感谢外人。他和他的祖先都很感激他为部落所做的一切。从现在起，他将永远是部落的朋友。古尔根肯定会喜欢他的。虽然他的死对部落来说是一个巨大的损失，但他是为了一件好事而牺牲的。既然它的敌人死了，这个部落肯定会过得更好。}
#{1251}{}{Rua wants to thank outsider. He and ancestors are grateful for what she has done for the tribe. From now on, he shall forever be tribe friend. Gurgan would surely be pleased with her. Though his death was a great loss for the tribe, he died fighting for a good thing. Now that its enemies are dead, the tribe will surely fare much better.}
{1251}{}{阮想感谢外人。他和祖先们都很感激她为部落所做的一切。从现在起，他将永远是部落的朋友。古根肯定会对她满意的。虽然他的死对部落来说是一个巨大的损失，但他是为了一件好事而牺牲的。既然它的敌人死了，这个部落肯定会过得更好。}
#{1252}{}{I hope so. Thanks.}
{1252}{}{希望如此。谢谢。}
#{1253}{}{Dat right! Thankses.}
{1253}{}{没错！谢谢。}
#{1300}{}{Why does tribe friend return to shaman?}
{1300}{}{为什么部落朋友要回到萨满？}
#{1301}{}{Why does tribe friend return to shaman?}
{1301}{}{为什么部落朋友要回到萨满？}
#{1302}{}{You've mentioned something about ancestors before. Can you really talk with the dead?}
{1302}{}{你以前提到过祖先。你真的能和死人说话吗？}
#{1303}{}{I'd like to know more about those ancestors. Why do you need to talk to them anyway?}
{1303}{}{我想更多地了解那些祖先。你为什么要和他们谈谈？}
#{1304}{}{I'd like to know more about those ancestors. Why do you need to talk to them anyway?}
{1304}{}{我想更多地了解那些祖先。你为什么要和他们谈谈？}
#{1305}{}{Just dropping by. See you later, Rua.}
{1305}{}{只是顺道过来。再见，鲁阿。}
#{1306}{}{Why nots! Seeya.}
{1306}{}{为什么不呢！再见。}
#{1350}{}{Why does tribe friend return to Rua? Has he found enough courage to let him look into his soul?}
{1350}{}{为什么部落朋友要回阮？他有足够的勇气让他审视自己的灵魂吗？}
#{1351}{}{Why does tribe friend return to Rua? Has she found enough courage to let him look into her soul?}
{1351}{}{为什么部落朋友要回阮？她是否有足够的勇气让他审视她的灵魂？}
#{1352}{}{Well... Yes. [Give him your hand.]}
{1352}{}{好。。。对。[把手给他]}
#{1353}{}{No way in hell. Bye, shaman.}
{1353}{}{绝对不行。再见，萨满。}
#{1354}{}{Yups!}
{1354}{}{是的！}
#{1355}{}{Noes! Bai.}
{1355}{}{不！白。}
#{1400}{}{Rua does not know why outsider decided to help the tribe. But he doubts his intent is good. He may have gained chief's trust, but he has not seen into his soul. Now that he is dead, Rua will be even more watchful of outsider.}
{1400}{}{阮不知道为什么外人决定帮助部落。但他怀疑他的意图是好的。他也许得到了酋长的信任，但他没有看清自己的灵魂。现在他已经死了，阮将更加警惕外人。}
#{1401}{}{Rua does not know why outsider decided to help the tribe. But he doubts her intent is good. She may have gained chief's trust, but he has not seen into her soul. Now that he is dead, Rua will be even more watchful of outsider.}
{1401}{}{阮不知道为什么外人决定帮助部落。但他怀疑她的意图是好的。她也许得到了酋长的信任，但他没有看透她的灵魂。现在他已经死了，阮将更加警惕外人。}
#{1402}{}{Whatever you say. Bye, shaman.}
{1402}{}{不管你说什么。再见，萨满。}
#{1403}{}{You've really crossed the line now. Time to meet those ancestors of yours, asshole!}
{1403}{}{你现在真的越界了。是时候见见你的祖先了，混蛋！}
#{1404}{}{Blah blah. Byes.}
{1404}{}{诸如此类。是的。}
#{1405}{}{Scary! Me punch face!}
{1405}{}{吓人的！打我的脸！}
#{1450}{}{Rua thinks outsider should not come back here. He has brought only misfortune to the tribe. Without its chief and its hunters, who fell in a hopeless battle, the tribe will surely die.}
{1450}{}{阮认为外人不应该回来。他只给部落带来了不幸。没有首领和猎人，他们在一场无望的战斗中倒下了，部落肯定会死。}
#{1451}{}{Rua thinks outsider should not come back here. She has brought only misfortune to the tribe. Without its chief and its hunters, who fell in a hopeless battle, the tribe will surely die.}
{1451}{}{阮认为外人不应该回来。她只给部落带来了不幸。没有首领和猎人，他们在一场无望的战斗中倒下了，部落肯定会死。}
#{1452}{}{Whatever you say. Bye, shaman.}
{1452}{}{不管你说什么。再见，萨满。}
#{1453}{}{You've really crossed the line now. Time to meet those ancestors of yours, asshole!}
{1453}{}{你现在真的越界了。是时候见见你的祖先了，混蛋！}
#{1454}{}{Blah blah. Byes.}
{1454}{}{诸如此类。是的。}
#{1455}{}{Scary! Me punch face!}
{1455}{}{吓人的！打我的脸！}
#{1500}{}{Ancestors were not wrong. Outsider has brought only misfortune to the tribe. Without its chief and its hunters, who fell in a hopeless battle, the tribe will surely die.}
{1500}{}{祖先没有错。外人只给部落带来了不幸。没有首领和猎人，他们在一场无望的战斗中倒下了，部落肯定会死。}
#{1501}{}{Ancestors were not wrong. Outsider has brought only misfortune to the tribe. Without its chief and its hunters, who fell in a hopeless battle, the tribe will surely die.}
{1501}{}{祖先没有错。外人只给部落带来了不幸。没有首领和猎人，他们在一场无望的战斗中倒下了，部落肯定会死。}
#{1502}{}{Whatever you say. Bye, shaman.}
{1502}{}{不管你说什么。再见，萨满。}
#{1503}{}{You've really crossed the line now. Time to meet those ancestors of yours!}
{1503}{}{你现在真的越界了。是时候见见你的祖先了！}
#{1504}{}{Blah blah. Byes.}
{1504}{}{诸如此类。是的。}
#{1505}{}{Scary! Me punch face!}
{1505}{}{吓人的！打我的脸！}
#{1550}{}{[He sighs.] Rua is trying to find them, but without success. Even ancestors cannot help. He suspects that there are dark forces behind it, forces that might one day destroy the whole tribe.}
{1550}{}{[他叹了口气]阮正试图找到他们，但没有成功。即使是祖先也无能为力。他怀疑背后有黑暗势力，这些势力有朝一日可能会摧毁整个部落。}
#{1551}{}{It can't be that bad. Later, Rua.}
{1551}{}{不会那么糟的。稍后，Rua。}
#{1600}{}{Before outsider leaves, Rua must ask him something. A girl named Aleea has ran away from the tribe not long ago. Rua has heard that outsider was talking to her. Does he know where she went?}
{1600}{}{在外人离开之前，阮必须问他一些事情。不久前，一个名叫阿莱娅的女孩从部落里逃跑了。Rua听说有外人在和她说话。他知道她去哪了吗？}
#{1601}{}{Before friend leaves, Rua must ask him something. A girl named Aleea has ran away from the tribe not long ago. Rua has heard that outsider talked to her. Does he know where she went?}
{1601}{}{在朋友离开之前，阮必须问他一些事情。不久前，一个名叫阿莱娅的女孩从部落里逃跑了。Rua听说外人跟她谈过。他知道她去哪了吗？}
#{1602}{}{Before outsider leaves, Rua must ask her something. A girl named Aleea has ran away from the tribe not long ago. Rua has heard that outsider talked to her. Does she know where she went?}
{1602}{}{在外人离开之前，阮必须问她一些事情。不久前，一个名叫阿莱娅的女孩从部落里逃跑了。Rua听说外人跟她谈过。她知道她去哪儿了吗？}
#{1603}{}{Before friend leaves, Rua must ask her something. A girl named Aleea has ran away from the tribe not long ago. Rua has heard that outsider talked to her. Does she know where she went?}
{1603}{}{在朋友离开之前，阮必须问她一些事情。不久前，一个名叫阿莱娅的女孩从部落里逃跑了。Rua听说外人跟她谈过。她知道她去哪儿了吗？}
#{1604}{}{Wherever she went, I'm sure she had a good reason. Bye, shaman.}
{1604}{}{无论她去哪里，我相信她都有充分的理由。再见，萨满。}
#{1605}{}{That's none of your business. Bye, shaman.}
{1605}{}{那不关你的事。再见，萨满。}
