#{100}{}{You see the leader of the Hunters.}
{100}{}{你看到猎人的首领了。}
#{150}{}{You see Sebastian.}
{150}{}{你看到塞巴斯蒂安了。}
#{200}{}{You see the leader of the Mutant Hunters. A peculiar kind of certainty and determination radiates from him.}
{200}{}{你看到变种猎人的首领了。他散发出一种特殊的确定感和决心。}
#{250}{}{You see Sebastian, the leader of the Mutant Hunters.}
{250}{}{你看塞巴斯蒂安，变种猎人的首领。}
#{300}{}{Betrayer of the human race!}
{300}{}{人类的背叛者！}
#{301}{}{Stop wasting time here, }
{301}{}{别再浪费时间了，}
#{302}{}{. The attack must begin as soon as possible.}
{302}{}{. 进攻必须尽快开始。}
#{500}{}{Yes? [The man gives you a piercing stare, as if he thoroughly assessed you in a single moment. You have a strange, hard to describe feeling about him.]}
{500}{}{对？[那人瞪了你一眼，好像他在一瞬间就彻底地评估了你。你对他有一种奇怪的、难以形容的感觉。]}
#{501}{}{Who are you?}
{501}{}{你是谁？}
#{502}{}{Sorry, wrong door.}
{502}{}{对不起，走错门了。}
#{550}{}{My name is Sebastian. And you are? More importantly, what are you doing here if you don't even know who I am?}
{550}{}{我叫塞巴斯蒂安。你呢？更重要的是，如果你连我是谁都不知道你在这里干什么？}
#{551}{}{I'm }
{551}{}{我是}
#{552}{}{My name is not important.}
{552}{}{我的名字不重要。}
#{553}{}{.}
{553}{}{.}
#{600}{}{In that case, there is no need to talk to you.}
{600}{}{那样的话，就没必要和你说话了。}
#{601}{}{My apologies. I'm }
{601}{}{我很抱歉。我是}
#{602}{}{If you say so.}
{602}{}{如果你这样说。}
#{650}{}{Very well. What is it you wish then?}
{650}{}{很好。那你的愿望是什么？}
#{651}{}{I want to know more about the Rebirth.}
{651}{}{我想知道更多关于重生的事。}
#{652}{}{What's the purpose of this organization - the Mutant Hunters?}
{652}{}{这个组织的目的是什么-变种猎人？}
#{653}{}{I want to join the Hunters.}
{653}{}{我想加入猎人队。}
#{654}{}{Nothing actually.}
{654}{}{实际上什么都没有。}
#{700}{}{I'm sure I can't tell you anything that you haven't already heard from one of the Hunters.}
{700}{}{我肯定我不能告诉你任何你还没有从猎人那里听说的事情。}
#{701}{}{Please, tell me everything you know about the Rebirth.}
{701}{}{请告诉我你所知道的关于重生的一切。}
#{702}{}{Do they have a base somewhere?}
{702}{}{他们有基地吗？}
#{703}{}{Tell me everything you know or I'll blow your fucking head off!}
{703}{}{把你知道的都告诉我，否则我就把你的脑袋炸了！}
#{704}{}{I guess not.}
{704}{}{我想不是。}
#{750}{}{In that case, you should talk to Kraig. Perhaps we'll talk again when you're a Hunter.}
{750}{}{那样的话，你应该和克莱格谈谈。当你是猎人的时候，也许我们还会再谈。}
#{751}{}{I wanted to ask about the Rebirth as well.}
{751}{}{我也想问问重生的事。}
#{752}{}{OK.}
{752}{}{好 啊。}
#{800}{}{I don't like your behavior one bit.}
{800}{}{我一点也不喜欢你的行为。}
#{801}{}{I'm very sorry. I shouldn't have said that.}
{801}{}{我很抱歉。我不该那么说。}
#{802}{}{I'm very sorry. I shouldn't have said that.}
{802}{}{我很抱歉。我不该那么说。}
#{803}{}{Fuck that!}
{803}{}{去他妈的！}
#{850}{}{Make sure it doesn't happen again.}
{850}{}{确保不会再发生这种事。}
#{851}{}{OK.}
{851}{}{好 啊。}
#{900}{}{You know, our doctor Yaotzin developed many methods of torturing both mutants and humans for hours while keeping them fully conscious, making sure they feel every second of it. If you're lucky, I'll kill you before the guards take you to him.}
{900}{}{你知道，我们的医生亚辛发明了很多方法，折磨变种人和人类几个小时，同时让他们保持清醒，确保他们每一秒都能感觉到。如果你幸运的话，我会在警卫把你带到他面前之前杀了你。}
#{901}{}{We'll see about that.}
{901}{}{我们拭目以待。}
#{950}{}{That was the second time. I'll teach you how to behave properly. Too bad you won't live long enough to make use of it.}
{950}{}{那是第二次了。我来教你如何举止得体。可惜你活不长，不能好好利用它。}
#{951}{}{I'm shaking.}
{951}{}{我在发抖。}
#{1000}{}{It seems to be a new ghoul religion of some kind. We know next to nothing about it, only that they speak of a certain Savior, their leader. Every ghoul belonging to them wears a talisman, a symbol of the Rebirth. They somehow managed to gain access to advanced pre-war weapons, and they use them to attack villages as well as large cities. They always raze the place to the ground, capture as many humans as they can and lead them somewhere we don't know.}
{1000}{}{它似乎是某种新的僵尸宗教。我们几乎一无所知，只知道他们说的是某个救世主，他们的领袖。每一个属于他们的僵尸都戴着一个护身符，一个重生的象征。他们设法获得了先进的战前武器，并用它们攻击村庄和大城市。他们总是把这个地方夷为平地，抓捕尽可能多的人，把他们带到我们不知道的地方。}
#{1001}{}{And what about Albuquerque?}
{1001}{}{那阿尔伯克基呢？}
#{1002}{}{I wanted to ask something else.}
{1002}{}{我想问点别的。}
#{1003}{}{That's all I needed.}
{1003}{}{这就是我所需要的。}
#{1050}{}{It's the only city still standing in this area, thanks to our tireless efforts. Despite that, it still suffered two attacks by a large number of Rebirth ghouls.}
{1050}{}{多亏了我们的不懈努力，它是这个地区唯一一座屹立不倒的城市。尽管如此，它仍然遭受了大量重生僵尸的两次袭击。}
#{1051}{}{Tell me about the attacks.}
{1051}{}{告诉我袭击的事。}
#{1052}{}{I wanted to ask something else.}
{1052}{}{我想问点别的。}
#{1053}{}{That's all I needed.}
{1053}{}{这就是我所需要的。}
#{1100}{}{The first attack occurred when we weren't here yet. The second attack took place about ten years ago. That unbelievable amount of ghouls must've convinced even the staunchest doubters that the mutant threat is real. The ghouls violently threw themselves at the city without any sort of tactics and almost overwhelmed us. We managed to push them back in the end, but the city has suffered extensive damage. Even today, the Dead Quarter serves as a remainder of that time.}
{1100}{}{第一次袭击发生在我们还没来的时候。第二次袭击发生在大约十年前。数量惊人的僵尸肯定让最坚定的怀疑者相信变种人的威胁是真的。僵尸们毫无策略地猛烈地扑向城市，几乎把我们压倒。我们最终设法把他们推回，但这座城市遭受了巨大的破坏。即使在今天，死区仍然是这段时间的剩余部分。}
#{1101}{}{Does the Rebirth have a base somewhere?}
{1101}{}{重生有什么根据吗？}
#{1102}{}{I wanted to ask something else.}
{1102}{}{我想问点别的。}
#{1103}{}{That's all I needed.}
{1103}{}{这就是我所需要的。}
#{1150}{}{No doubt. All their actions point to it. And considering the equipment they have at their disposal, it's possible that they're using and old army complex of some sort.}
{1150}{}{毫无疑问。他们所有的行动都表明了这一点。考虑到他们拥有的装备，他们有可能使用的是某种旧的军队建筑群。}
#{1151}{}{But where is it?}
{1151}{}{但它在哪里？}
#{1200}{}{Why do you want to know that?}
{1200}{}{你为什么想知道？}
#{1201}{}{I want to find out who I am. [Tell him your story.]}
{1201}{}{我想知道我是谁。[告诉他你的故事。]}
#{1202}{}{I want to destroy the Rebirth.}
{1202}{}{我要毁灭重生。}
#{1203}{}{I want to help them in their fight.}
{1203}{}{我想帮助他们打仗。}
#{1250}{}{You want to help them wipe out humans? You're completely deranged! They wouldn't care anyway, they'd just kill you on the spot. I'd better just take care of you myself.}
{1250}{}{你想帮他们消灭人类？你完全疯了！反正他们也不会在乎，他们会当场杀了你。我最好自己照顾你。}
#{1251}{}{Go ahead and try.}
{1251}{}{去试试吧。}
#{1300}{}{You want to help them wipe out humans? You're completely deranged! They wouldn't care anyway, they'd just kill you on the spot. I'd better just take care of you myself.}
{1300}{}{你想帮他们消灭人类？你完全疯了！反正他们也不会在乎，他们会当场杀了你。我最好自己照顾你。}
#{1301}{}{Go ahead and try.}
{1301}{}{去试试吧。}
#{1350}{}{And you think we don't? They're becoming more and more dangerous, they keep getting stronger and closer to their goal, whatever it is. But it can't be anything good for genetically pure humans. If we knew the location of their base, we would've long since razed it to the ground, leaving no mutant alive! We were so close, but the super mutants ruined everything again.}
{1350}{}{你觉得我们没有？他们变得越来越危险，他们越来越强大，越来越接近他们的目标，不管是什么。但这对基因纯正的人类来说并不是什么好事。如果我们知道他们基地的位置，我们早就把它夷为平地了，没有留下一个变种人活着！我们很接近，但超级变种人又毁了一切。}
#{1351}{}{What are you talking about?}
{1351}{}{你在说什么？}
#{1400}{}{We have a forward base southeast of the city that we use for external operations. We keep radio contact only rarely to avoid exposing its location to the Rebirth. But commander Tunrida has recently reported that an interrogation of one of the ghouls revealed some new information about the Rebirth and that she'll soon know the location of their base. We waited for someone to arrive with the full report, but nothing happened, nobody even answered the radio. Our scouts later discovered that the base has been taken over by a group of super mutants that massacred our people.}
{1400}{}{我们在城市东南部有一个前线基地，用于对外作战。我们很少保持无线电联系，以避免它的位置暴露给重生。但是指挥官Tunrida最近报告说，对其中一个僵尸的审讯揭示了一些关于重生的新信息，她很快就会知道他们基地的位置。我们等着有人带着完整的报告来，但什么也没发生，甚至没有人接收音机。我们的侦察兵后来发现基地被一群屠杀我们人民的超级变种人占领了。}
#{1401}{}{Why don't you attack the super mutants?}
{1401}{}{你为什么不攻击超级变种人？}
#{1450}{}{They've barricaded themselves in, dug a moat around the base and filled it with some radioactive crap - they're ready for any attack. If we attacked, there wouldn't be anyone left to defend the city, making it an easy target for the Rebirth.}
{1450}{}{他们把自己围起来，在基地周围挖了一条护城河，里面装满了一些放射性废物——他们已经做好了任何攻击的准备。如果我们进攻，就不会有人留下来保卫这座城市，使它成为重生的容易目标。}
#{1451}{}{If that's where the location of the Rebirth base can be learned, then I will go there. Where is it?}
{1451}{}{如果在那里可以知道重生基地的位置，那我就去那里。它在哪里？}
#{1500}{}{Did you hear what I just said? Are you willing to face a well equipped group of super mutants by yourself? If you want to stupidly throw your life away like this instead of joining us and fighting against all mutants, you're a fool. But I won't stop you. The base is here. [He shows you the location on a map.]}
{1500}{}{你听到我刚才说的话了吗？你愿意独自面对一群装备精良的超级变种人吗？如果你想像这样愚蠢地放弃你的生命而不是加入我们和所有的变种人战斗，你就是个傻瓜。但我不会阻止你。基地就在这里。[他给你看地图上的位置。]}
#{1501}{}{Thanks.}
{1501}{}{谢谢。}
#{1550}{}{Did you hear what I just said? Are you willing to face a well equipped group of super mutants by yourself? If you want to stupidly throw your life away like this instead of joining us and fighting against all mutants, you're a fool. But I won't stop you. The base is here. [He shows you the location on a map.]}
{1550}{}{你听到我刚才说的话了吗？你愿意独自面对一群装备精良的超级变种人吗？如果你想像这样愚蠢地放弃你的生命而不是加入我们和所有的变种人战斗，你就是个傻瓜。但我不会阻止你。基地就在这里。[他给你看地图上的位置。]}
#{1551}{}{Thanks.}
{1551}{}{谢谢。}
#{1600}{}{Since you don't stand the slightest chance, it's pointless to tell you, but if you do happen to get some of the information that Tunrida has gathered, I would be quite interested. It could be the deciding factor in our fight for pure humans.}
{1600}{}{既然你一点机会都没有，告诉你是没有意义的，但是如果你碰巧得到了图丽达收集到的一些信息，我会很感兴趣的。它可能是我们为纯人类而战的决定性因素。}
#{1601}{}{OK.}
{1601}{}{好 啊。}
#{1650}{}{I've already told you that Kraig handles that.}
{1650}{}{我已经告诉过你了，克莱格会处理的。}
#{1651}{}{OK.}
{1651}{}{好 啊。}
#{1700}{}{I'm sure I can't tell you anything that you haven't already heard from one of the Hunters.}
{1700}{}{我肯定我不能告诉你任何你还没有从猎人那里听说的事情。}
#{1701}{}{Please, tell me everything you know about the Rebirth.}
{1701}{}{请告诉我你所知道的关于重生的一切。}
#{1702}{}{Do they have a base somewhere?}
{1702}{}{他们有基地吗？}
#{1703}{}{Tell me everything you know or I'll blow your fucking head off!}
{1703}{}{把你知道的都告诉我，否则我就把你的脑袋炸了！}
#{1704}{}{I guess not.}
{1704}{}{我想不是。}
#{1750}{}{Interesting. If only you could remember! The Rebirth ghouls haul off many of the people that they manage to take alive. It's possible you're one of them. Perhaps you managed to escape, and they want to stop you because you know what they're up to! You must remember, for the sake of all pure humans, we must find out what's going on!}
{1750}{}{很有趣。如果你还记得的话！重生的僵尸带走了许多他们设法活捉的人。有可能你就是其中之一。也许你设法逃走了，他们想阻止你，因为你知道他们在干什么！你必须记住，为了所有纯洁的人类，我们必须找出到底发生了什么！}
#{1751}{}{But how?}
{1751}{}{但是怎么做呢？}
#{1800}{}{The only way is to get the info from our forward base. You must go there.}
{1800}{}{唯一的办法就是从前线基地得到情报。你必须去那里。}
#{1801}{}{What are you talking about?}
{1801}{}{你在说什么？}
#{1850}{}{We have a forward base southeast of the city that we use for external operations. We keep radio contact only rarely to avoid exposing its location to the Rebirth. But commander Tunrida has recently reported that an interrogation of one of the ghouls revealed some new information about the Rebirth and that she'll soon know the location of their base. We waited for someone to arrive with the full report, but nothing happened, nobody even answered the radio. Our scouts later discovered that the base has been taken over by a group of super mutants that massacred our people.}
{1850}{}{我们在城市东南部有一个前线基地，用于对外作战。我们很少保持无线电联系，以避免它的位置暴露给重生。但是指挥官Tunrida最近报告说，对其中一个僵尸的审讯揭示了一些关于重生的新信息，她很快就会知道他们基地的位置。我们等着有人带着完整的报告来，但什么也没发生，甚至没有人接收音机。我们的侦察兵后来发现基地被一群屠杀我们人民的超级变种人占领了。}
#{1851}{}{Why don't you attack the super mutants?}
{1851}{}{你为什么不攻击超级变种人？}
#{1852}{}{Is there no other way to get that info?}
{1852}{}{没有其他方法可以得到这些信息吗？}
#{1853}{}{What's the purpose of the base outside Albuquerque?}
{1853}{}{阿尔伯克基外基地的目的是什么？}
#{1854}{}{Alright, where is it? Any idea how to get inside?}
{1854}{}{好吧，在哪里？你知道怎么进去吗？}
#{1900}{}{They've barricaded themselves in, dug a moat around the base and filled it with some radioactive crap - they're ready for any attack. If we attacked, there wouldn't be anyone left to defend the city, making it an easy target for the Rebirth.}
{1900}{}{他们把自己围起来，在基地周围挖了一条护城河，里面装满了一些放射性废物——他们已经做好了任何攻击的准备。如果我们进攻，就不会有人留下来保卫这座城市，使它成为重生的容易目标。}
#{1901}{}{Is there no other way to get that info?}
{1901}{}{没有其他方法可以得到这些信息吗？}
#{1902}{}{What's the purpose of the base outside Albuquerque?}
{1902}{}{阿尔伯克基外基地的目的是什么？}
#{1903}{}{Where is that base? Any idea how to get inside?}
{1903}{}{基地在哪里？你知道怎么进去吗？}
#{1950}{}{No. We tried everything, but the ghouls refused to talk. Every bit of information that Tunrida may have discovered could be important, and could help you remember. I just hope the super mutants didn't destroy everything. Because of their mental deficiency, computers are worthless to them.}
{1950}{}{没有。我们什么都试过了，但僵尸拒绝说话。Tunrida发现的每一点信息都很重要，可以帮助你记忆。我只希望超级变种人没有毁掉一切。由于他们的智力缺陷，计算机对他们来说一文不值。}
#{1951}{}{Why don't you attack the super mutants?}
{1951}{}{你为什么不攻击超级变种人？}
#{1952}{}{What's the purpose of the base outside Albuquerque?}
{1952}{}{阿尔伯克基外基地的目的是什么？}
#{1953}{}{Alright, where is that base then? Any idea how to get inside?}
{1953}{}{好吧，那基地在哪里？你知道怎么进去吗？}
#{2000}{}{It's actually an old army warehouse - we found pre-war weapons and a few suits of power armor inside. We used it for researching mutation and interrogating Rebirth ghouls. We simply don't have the means to do that here, we need to be always ready for battle. And since we keep the city clean of mutants, bringing too many prisoners here would be too much of a risk.}
{2000}{}{这实际上是一个旧的陆军仓库-我们在里面发现了战前的武器和几套动力装甲。我们用它来研究变异和审问重生的僵尸。我们根本没有办法做到这一点，我们需要随时准备战斗。既然我们保持城市里没有变种人，把太多的囚犯带到这里就太危险了。}
#{2001}{}{Why don't you attack the super mutants?}
{2001}{}{你为什么不攻击超级变种人？}
#{2002}{}{Is there no other way to get that info?}
{2002}{}{没有其他方法可以得到这些信息吗？}
#{2003}{}{Alright, where is it it then? Any idea how to get inside?}
{2003}{}{好吧，那它在哪里？你知道怎么进去吗？}
#{2050}{}{Here. [He shows you the location on a map.] I can't spare a single man, so a direct attack on well-equipped super mutants would be suicidal. Reasoning with mutants is impossible, not even one of the Children of the Cathedral could probably do it. Hopefully you'll manage to sneak in somehow.}
{2050}{}{在这里。[他给你看地图上的位置]我不能放过一个人，所以直接攻击装备精良的超级变种人是自杀。与变种人进行推理是不可能的，甚至连大教堂的一个孩子都做不到。希望你能设法溜进去。}
#{2051}{}{Children of the Cathedral?}
{2051}{}{大教堂的孩子们？}
#{2052}{}{I'll head there and find out all I can.}
{2052}{}{我要去那里，尽我所能找出答案。}
#{2053}{}{Forget it, I'm not risking an encounter with super mutants.}
{2053}{}{算了吧，我可不想冒险遇到超级变种人。}
#{2100}{}{The Children of the Cathedral are the biggest traitors to the human race. They used to serve the Master and his super mutants. Of course, it didn't do them any good, because after the Master's death, the super mutants attacked them along with the rest of pure humans.}
{2100}{}{大教堂的孩子们是人类最大的叛徒。他们曾经为主人和他的超级变种人服务。当然，这对他们没有任何好处，因为在大师死后，超级变种人和其他纯人类一起攻击他们。}
#{2101}{}{I see. I'll head to the base and find out all I can.}
{2101}{}{我懂了。我要去基地，尽我所能找出答案。}
#{2102}{}{Forget it, I'm not risking an encounter with super mutants.}
{2102}{}{算了吧，我可不想冒险遇到超级变种人。}
#{2150}{}{Interesting. If only you could remember! The Rebirth ghouls haul off many of the people that they manage to take alive. It's possible you're one of them. Perhaps you managed to escape, and they want to stop you because you know what they're up to! You must remember, for the sake of all pure humans, we must find out what's going on!}
{2150}{}{很有趣。如果你还记得的话！重生的僵尸带走了许多他们设法活捉的人。有可能你就是其中之一。也许你设法逃走了，他们想阻止你，因为你知道他们在干什么！你必须记住，为了所有纯洁的人类，我们必须找出到底发生了什么！}
#{2151}{}{But how?}
{2151}{}{但是怎么做呢？}
#{2200}{}{Mr. nameless?}
{2200}{}{无名先生？}
#{2201}{}{I'm sorry, my name is }
{2201}{}{对不起，我的名字是}
#{2202}{}{Yep, and it's staying that way.}
{2202}{}{是的，而且一直是这样。}
#{2250}{}{Miss nameless?}
{2250}{}{无名小姐？}
#{2251}{}{I'm sorry, my name is }
{2251}{}{对不起，我的名字是}
#{2252}{}{Yep, and it's staying that way.}
{2252}{}{是的，而且一直是这样。}
#{2300}{}{Yes, }
{2300}{}{对，}
#{2301}{}{?}
{2301}{}{?}
#{2302}{}{I want to know more about the Rebirth.}
{2302}{}{我想知道更多关于重生的事。}
#{2303}{}{What's the purpose of this organization - the Mutant Hunters?}
{2303}{}{这个组织的目的是什么-变种猎人？}
#{2304}{}{I want to join the Hunters.}
{2304}{}{我想加入猎人队。}
#{2305}{}{I changed my mind, I'll head to the base occupied by super mutants and find out all I can.}
{2305}{}{我改变主意了，我要去超级变种人占领的基地，尽我所能找到一切。}
#{2306}{}{I changed my mind, I'll head to the base occupied by super mutants and find out all I can.}
{2306}{}{我改变主意了，我要去超级变种人占领的基地，尽我所能找到一切。}
#{2307}{}{I have the holodisk with Tunrida's report of the interrogation of the Rebirth ghoul. Including the location of their base! [Give it to him.]}
{2307}{}{我有通利达关于审讯重生僵尸的报告的全息光盘。包括他们基地的位置！[把它给他。]}
#{2308}{}{I've read the holodisk with the report of the interrogation of the Rebirth ghoul. Sadly, the holodisk was destroyed, but I managed to write down the coordinates of the Rebirth base. [Tell him the location of the base.]}
{2308}{}{我读了全息光盘，里面有审讯重生僵尸的报告。遗憾的是，全息盘被毁了，但我设法记下了重生基地的坐标。[告诉他基地的位置。]}
#{2309}{}{I've read the holodisk with the report of the interrogation of the Rebirth ghoul. Sadly, the holodisk was destroyed, but I managed to write down the coordinates of the Rebirth base. [Tell him the location of the base.]}
{2309}{}{我读了全息光盘，里面有审讯重生僵尸的报告。遗憾的是，全息盘被毁了，但我设法记下了重生基地的坐标。[告诉他基地的位置。]}
#{2310}{}{The super mutants that were occupying your forward base are gone.}
{2310}{}{占领你前方基地的超级变种人已经消失了。}
#{2311}{}{Wrong door.}
{2311}{}{开错门了。}
#{2350}{}{We're doing what every pure human should - defend the world from the mutant threat. We'll wipe out every last one of them.}
{2350}{}{我们在做每一个纯人类都应该做的事——保护世界免受变种人的威胁。我们会把他们全部消灭。}
#{2351}{}{Don't the mutants have the right to live like other humans?}
{2351}{}{难道变种人没有权利像其他人一样生活吗？}
#{2352}{}{Minor mutations are common. Do you kill people because of something like an extra finger or toe?}
{2352}{}{微小的突变很常见。你杀人是因为多了一根手指或脚趾吗？}
#{2353}{}{But the mutants aren't to blame. Even you would mutate easily if you were exposed to a sufficient dose of radiation.}
{2353}{}{但变种人不是罪魁祸首。即使你暴露在足够剂量的辐射下也很容易变异。}
#{2354}{}{How do you hope to exterminate all the mutants?}
{2354}{}{你希望如何消灭所有的变种人？}
#{2355}{}{What do you know about the Master?}
{2355}{}{你对师父了解多少？}
#{2356}{}{I wanted to ask something else.}
{2356}{}{我想问点别的。}
#{2357}{}{That's all I needed.}
{2357}{}{这就是我所需要的。}
#{2400}{}{Why should they? They are a defect. A mistake we're trying to correct.}
{2400}{}{他们为什么要这么做？它们是缺陷。我们正在努力纠正的错误。}
#{2401}{}{But the mutations of this age could be the product of natural evolution. People change to better adapt to their current environment and have a greater chance of survival.}
{2401}{}{但这个时代的突变可能是自然进化的产物。人们为了更好地适应当前的环境而改变，从而获得更大的生存机会。}
#{2402}{}{But exterminating them all? Is there no other way?}
{2402}{}{但是消灭他们？没有别的办法了吗？}
#{2403}{}{Can't we just get along with the mutants?}
{2403}{}{我们就不能和变种人相处吗？}
#{2404}{}{I wanted to ask about exterminating the mutants.}
{2404}{}{我想问一下消灭变种人的事。}
#{2405}{}{I wanted to ask something else.}
{2405}{}{我想问点别的。}
#{2406}{}{That's all I needed.}
{2406}{}{这就是我所需要的。}
#{2450}{}{The strong radiation that caused the mutations has nothing to do with natural evolution. It's the consequence of a war that was never supposed to happen. That's not evolution, but a dead end that threatens natural development and must be eliminated.}
{2450}{}{导致突变的强辐射与自然进化无关。这是一场本不该发生的战争的后果。这不是进化，而是威胁自然发展的死胡同，必须消除。}
#{2451}{}{But exterminating them all? Is there no other way?}
{2451}{}{但是消灭他们？没有别的办法了吗？}
#{2452}{}{Can't we just get along with the mutants?}
{2452}{}{我们就不能和变种人相处吗？}
#{2453}{}{I wanted to ask about exterminating the mutants.}
{2453}{}{我想问一下消灭变种人的事。}
#{2454}{}{I wanted to ask something else.}
{2454}{}{我想问点别的。}
#{2455}{}{That's all I needed.}
{2455}{}{这就是我所需要的。}
#{2500}{}{Like what? There is no cure for mutation. Our scientists have researched this and came to the clear conclusion that mutations are irreversible. When the tissue mutates, it can't be returned to it's former state ever again.}
{2500}{}{像什么？突变是无法治愈的。我们的科学家对此进行了研究，得出了突变是不可逆的明确结论。当组织发生变异时，就再也不能回到原来的状态了。}
#{2501}{}{Can't we just get along with the mutants? Find a common ground?}
{2501}{}{我们就不能和变种人相处吗？找到共同点？}
#{2502}{}{And what about people with minor mutations, like an extra finger or toe?}
{2502}{}{那些有微小变异的人呢，比如多了一个手指或脚趾？}
#{2503}{}{I wanted to ask about exterminating the mutants.}
{2503}{}{我想问一下消灭变种人的事。}
#{2504}{}{I wanted to ask something else.}
{2504}{}{我想问点别的。}
#{2505}{}{That's all I needed.}
{2505}{}{这就是我所需要的。}
#{2550}{}{Many say that we should deal with the mutants peacefully - but they are naive. There can be no discussion with mutants, their minds have been so damaged by mutation that they are incapable of reasoning. They are aggressive and violent.}
{2550}{}{许多人说我们应该和平地对待变种人，但他们太天真了。不能和变种人讨论，他们的大脑已经被变种破坏得无法推理。他们具有侵略性和暴力性。}
#{2551}{}{But not every mutation means that the person is completely incapable of reasoning.}
{2551}{}{但并不是每个变异都意味着这个人完全没有推理能力。}
#{2552}{}{I've heard that there are super mutants that aren't completely mentally deficient.}
{2552}{}{我听说有些超级变种人并不完全智力缺陷。}
#{2553}{}{I wanted to ask about exterminating the mutants.}
{2553}{}{我想问一下消灭变种人的事。}
#{2554}{}{I wanted to ask something else.}
{2554}{}{我想问点别的。}
#{2555}{}{That's all I needed.}
{2555}{}{这就是我所需要的。}
#{2600}{}{We have medical records that prove it. Moreover, the destructive effects of radiation are well-known to all. Brain cells are most sensitive to it, causing them to die first. And the super mutants, who were hit by it the most, are well known for their mental limitations. You can hardly deny such obvious facts.}
{2600}{}{我们有医疗记录证明。此外，辐射的破坏作用是众所周知的。脑细胞对它最敏感，导致它们先死。而超级变种人，他们受到的打击最大，是众所周知的精神局限性。你很难否认这样明显的事实。}
#{2601}{}{I've heard that there are super mutants that aren't completely mentally deficient.}
{2601}{}{我听说有些超级变种人并不完全智力缺陷。}
#{2602}{}{I've often heard the Master mentioned in connection with the super mutants. What do you know about him?}
{2602}{}{我经常听到大师提到超级变种人。你对他了解多少？}
#{2603}{}{I wanted to ask about exterminating the mutants.}
{2603}{}{我想问一下消灭变种人的事。}
#{2604}{}{I wanted to ask something else.}
{2604}{}{我想问点别的。}
#{2605}{}{That's all I needed.}
{2605}{}{这就是我所需要的。}
#{2650}{}{Those are mere fairy tales, the existence of an intelligent super mutant is completely preposterous.}
{2650}{}{那些仅仅是童话故事，一个聪明的超级变种人的存在是完全荒谬的。}
#{2651}{}{I've talked to one.}
{2651}{}{我和其中一个谈过。}
#{2652}{}{I've talked to one.}
{2652}{}{我和其中一个谈过。}
#{2653}{}{I've often heard the Master mentioned in connection with the super mutants. What do you know about him?}
{2653}{}{我经常听到大师提到超级变种人。你对他了解多少？}
#{2654}{}{I wanted to ask about exterminating the mutants.}
{2654}{}{我想问一下消灭变种人的事。}
#{2655}{}{I wanted to ask something else.}
{2655}{}{我想问点别的。}
#{2656}{}{That's all I needed.}
{2656}{}{这就是我所需要的。}
#{2700}{}{Lies like that undermine our efforts, and spreading them equals assisting the mutants.}
{2700}{}{像这样的谎言破坏了我们的努力，传播这些谎言等于帮助变种人。}
#{2701}{}{But it's the truth!}
{2701}{}{但这是事实！}
#{2750}{}{Not even the slightest mutation must go unnoticed because it could spread. But, in the case of an extra finger or toe, it is possible to save the person by amputating the relevant limb. But should the mutation develop further and deeper into the body, then they must be put to death.}
{2750}{}{即使是最微小的突变也不能不被注意，因为它可能会传播。但是，如果有多余的手指或脚趾，可以通过截肢相关的肢体来挽救病人。但是如果这种突变在体内发展得更深入，那么它们就必须被处死。}
#{2751}{}{Isn't that a bit too drastic?}
{2751}{}{是不是有点过激了？}
#{2752}{}{That's easy for you to say. What if it happened to you?}
{2752}{}{你说起来容易。万一发生在你身上呢？}
#{2753}{}{I wanted to ask about exterminating the mutants.}
{2753}{}{我想问一下消灭变种人的事。}
#{2754}{}{I wanted to ask something else.}
{2754}{}{我想问点别的。}
#{2755}{}{That's all I needed.}
{2755}{}{这就是我所需要的。}
#{2800}{}{If you have a dog with in incurable disease, you put him down. Especially when he's suffering and could infect others as well.}
{2800}{}{如果你有一只患绝症的狗，你就把它放下来。尤其是当他受苦的时候，也会传染给其他人。}
#{2801}{}{That's easy for you to say. What if it happened to you?}
{2801}{}{你说起来容易。万一发生在你身上呢？}
#{2802}{}{I wanted to ask about exterminating the mutants.}
{2802}{}{我想问一下消灭变种人的事。}
#{2803}{}{I wanted to ask something else.}
{2803}{}{我想问点别的。}
#{2804}{}{That's all I needed.}
{2804}{}{这就是我所需要的。}
#{2850}{}{I'd cut off my legs at the slightest sign of mutation in them. And should I be affected even further, I'd kill myself while I still could.}
{2850}{}{只要有一点点变异的迹象，我就会把腿砍掉。如果我受到更大的影响，我会在我还可以的时候自杀。}
#{2851}{}{What do you mean by 'while I still could'?}
{2851}{}{你说“趁我还可以”是什么意思？}
#{2852}{}{I wanted to ask about exterminating the mutants.}
{2852}{}{我想问一下消灭变种人的事。}
#{2853}{}{I wanted to ask something else.}
{2853}{}{我想问点别的。}
#{2854}{}{That's all I needed.}
{2854}{}{这就是我所需要的。}
#{2900}{}{We won't rest until they're all dead. We can only hope that our tireless efforts shall convince more and more pure humans to join us in our fight to save the genetic purity of mankind.}
{2900}{}{他们都死了我们才休息。我们只能希望，我们的不懈努力将说服越来越多的纯洁人类加入我们的战斗，拯救人类基因的纯洁性。}
#{2901}{}{Ah, so you don't have any concrete plan how to globally exterminate the mutants.}
{2901}{}{啊，所以你没有任何具体的计划如何在全球范围内消灭变种。}
#{2902}{}{Ah, so you don't have any concrete plan how to globally exterminate the mutants.}
{2902}{}{啊，所以你没有任何具体的计划如何在全球范围内消灭变种。}
#{2903}{}{I wanted to ask about exterminating the mutants.}
{2903}{}{我想问一下消灭变种人的事。}
#{2904}{}{I wanted to ask something else.}
{2904}{}{我想问点别的。}
#{2905}{}{That's all I needed.}
{2905}{}{这就是我所需要的。}
#{2950}{}{We're working on various options. For example, we're trying to develop a virus that would only kill mutants. Unfortunately, a large part of the research was being carried out under Tunrida's command in our base outside Albuquerque, which has been conquered by super mutants.}
{2950}{}{我们正在研究各种选择。例如，我们正试图开发一种只杀死变种的病毒。不幸的是，大部分的研究是在图里达的指挥下在我们位于阿尔伯克基郊外的基地进行的，那里已经被超级变种人征服了。}
#{2951}{}{I wanted to ask about exterminating the mutants.}
{2951}{}{我想问一下消灭变种人的事。}
#{2952}{}{I wanted to ask something else.}
{2952}{}{我想问点别的。}
#{2953}{}{That's all I needed.}
{2953}{}{这就是我所需要的。}
#{3000}{}{The Master was mad! No doubt due to the effects of the extensive mutations he suffered. He was somehow changing people into super mutants, and wanted to turn the whole human race into those dumb beasts! Thankfully, he was stopped. But the consequences of his atrocities remain a threat even today.}
{3000}{}{主人疯了！毫无疑问是由于他所遭受的广泛变异的影响。他不知怎么地把人变成了超级变种人，想把整个人类变成那些愚蠢的野兽！谢天谢地，他被拦住了。但即使在今天，他的暴行的后果仍然是一个威胁。}
#{3001}{}{I wanted to ask about exterminating the mutants.}
{3001}{}{我想问一下消灭变种人的事。}
#{3002}{}{I wanted to ask something else.}
{3002}{}{我想问点别的。}
#{3003}{}{That's all I needed.}
{3003}{}{这就是我所需要的。}
#{3050}{}{What do you wish to know?}
{3050}{}{你想知道什么？}
#{3051}{}{I want to know more about the Rebirth.}
{3051}{}{我想知道更多关于重生的事。}
#{3052}{}{What's the purpose of this organization - the Mutant Hunters?}
{3052}{}{这个组织的目的是什么-变种猎人？}
#{3053}{}{I want to join the Hunters.}
{3053}{}{我想加入猎人队。}
#{3054}{}{Nothing else.}
{3054}{}{没别的了。}
#{3100}{}{As I've already said, you won't learn more from me than from anyone else in this base.}
{3100}{}{我已经说过了，你从我身上学到的东西不会比从基地里其他人身上学到的更多。}
#{3101}{}{Please, tell me everything you know about the Rebirth again.}
{3101}{}{拜托，再告诉我你所知道的关于重生的一切。}
#{3102}{}{Does the Rebirth have a base somewhere?}
{3102}{}{重生有什么根据吗？}
#{3103}{}{Tell me everything you know or I'll blow your fucking head off!}
{3103}{}{把你知道的都告诉我，否则我就把你的脑袋炸了！}
#{3104}{}{I guess not.}
{3104}{}{我想不是。}
#{3150}{}{Mutation can affect the brain very quickly. Mutants are not capable of reasoning. They're like animals - aggressive and violent.}
{3150}{}{突变可以很快影响大脑。变种人没有推理能力。他们就像动物一样-攻击性和暴力。}
#{3151}{}{But not all mutations mean that the person is completely incapable of reasoning.}
{3151}{}{但并非所有的突变都意味着这个人完全没有推理能力。}
#{3152}{}{I wanted to ask about exterminating the mutants.}
{3152}{}{我想问一下消灭变种人的事。}
#{3153}{}{I wanted to ask something else.}
{3153}{}{我想问点别的。}
#{3154}{}{That's all I needed.}
{3154}{}{这就是我所需要的。}
#{3200}{}{What are your doubts?}
{3200}{}{你怀疑什么？}
#{3201}{}{Don't the mutants have the right to live like other humans?}
{3201}{}{难道变种人没有权利像其他人一样生活吗？}
#{3202}{}{Minor mutations are common. What about people with an extra finger or toe?}
{3202}{}{微小的突变很常见。有多余手指或脚趾的人呢？}
#{3203}{}{But the mutants aren't to blame. Even you would mutate easily if you were exposed to a sufficient dose of radiation.}
{3203}{}{但变种人不是罪魁祸首。即使你暴露在足够剂量的辐射下也很容易变异。}
#{3204}{}{How do you hope to exterminate all the mutants?}
{3204}{}{你希望如何消灭所有的变种人？}
#{3205}{}{How do we hope to exterminate all the mutants?}
{3205}{}{我们希望如何消灭所有的变种人？}
#{3206}{}{What do you know about the Master?}
{3206}{}{你对师父了解多少？}
#{3207}{}{I wanted to ask something else.}
{3207}{}{我想问点别的。}
#{3208}{}{That's all I needed.}
{3208}{}{这就是我所需要的。}
#{3250}{}{Any news, }
{3250}{}{任何消息，}
#{3251}{}{?}
{3251}{}{?}
#{3252}{}{I want to ask what you know about the Rebirth.}
{3252}{}{我想问你对重生了解多少。}
#{3253}{}{Can you tell me the purpose of this organization - the Mutant Hunters?}
{3253}{}{你能告诉我这个组织的目的吗？变种猎人？}
#{3254}{}{I want to join the Hunters.}
{3254}{}{我想加入猎人队。}
#{3255}{}{I have the holodisk with Tunrida's report of the interrogation of the Rebirth ghoul. Including the location of their base! [Give it to him.]}
{3255}{}{我有通利达关于审讯重生僵尸的报告的全息光盘。包括他们基地的位置！[把它给他。]}
#{3256}{}{I've read the holodisk with the report of the interrogation of the Rebirth ghoul. Sadly, the holodisk was destroyed, but I managed to write down the coordinates of the Rebirth base. [Tell him the location of the base.]}
{3256}{}{我读了全息光盘，里面有审讯重生僵尸的报告。遗憾的是，全息盘被毁了，但我设法记下了重生基地的坐标。[告诉他基地的位置。]}
#{3257}{}{I've read the holodisk with the report of the interrogation of the Rebirth ghoul. Sadly, the holodisk was destroyed, but I managed to write down the coordinates of the Rebirth base. [Tell him the location of the base.]}
{3257}{}{我读了全息光盘，里面有审讯重生僵尸的报告。遗憾的是，全息盘被毁了，但我设法记下了重生基地的坐标。[告诉他基地的位置。]}
#{3258}{}{The super mutants that were occupying your forward base are gone.}
{3258}{}{占领你前方基地的超级变种人已经消失了。}
#{3259}{}{Not yet.}
{3259}{}{还没有。}
#{3260}{}{Uf.}
{3260}{}{佛罗里达州。}
#{3300}{}{Excellent! Come back when you know anything new, then. If every pure human was as willing to fight for the salvation of mankind as you are, we would've purged the world of the mutant blight a long time ago.}
{3300}{}{杰出的！那你知道什么新鲜事就回来吧。如果每一个纯洁的人类都像你们一样愿意为拯救人类而战，我们早就清除了世界上的变异疫病了。}
#{3301}{}{OK.}
{3301}{}{好 啊。}
#{3350}{}{Really?! I'll take a look immediately. [He quickly connects the holodisk and reads its contents.] It's worse than I ever imagined. The insane mutants believe they can cure themselves! But all they will accomplish is killing scores of genetically pure humans. Only a sick mutant mind could come up with a plan like that.}
{3350}{}{真正地？！我马上去看看。[他迅速连接全息光盘并读取其内容]这比我想象的还要糟糕。疯狂的变种人相信他们能治愈自己！但他们所要做的就是杀死几十个基因纯正的人类。只有病态的变种人才能想出这样的计划。}
#{3351}{}{What now?}
{3351}{}{现在怎么办？}
#{3400}{}{The course is clear - we must stop them, for the sake of all pure humans. We must kill that Savior and destroy their base. Now that we know where it is, we can finally attack!}
{3400}{}{我们必须阻止他们，为了所有纯洁的人类。我们必须杀死救世主，摧毁他们的基地。现在我们知道它在哪里了，我们终于可以进攻了！}
#{3401}{}{I want to join that attack.}
{3401}{}{我想加入攻击。}
#{3402}{}{Will I get a reward for delivering the holodisk?}
{3402}{}{我送全息光盘会得到奖励吗？}
#{3403}{}{Hm, I'll be going then.}
{3403}{}{嗯，那我就去。}
#{3450}{}{We'll need all the help we can get. I can't send too many men, as we must always be ready in case of an attack on the city, and a small group will be more suitable for fighting in an underground complex. I will send a few Hunters to hide near the entrance and wait for you. Together you will attack, and put an end to the ghouls' foolish plan.}
{3450}{}{我们需要所有能得到的帮助。我不能派太多的人，因为我们必须随时准备好，以防城市遭到攻击，一小队人更适合在地下建筑群里作战。我会派几个猎人躲在门口等你。你们将一起攻击，结束僵尸的愚蠢计划。}
#{3451}{}{OK, I'll be on my way then.}
{3451}{}{好的，那我就上路了。}
#{3452}{}{Will I get a reward for delivering the holodisk?}
{3452}{}{我送全息光盘会得到奖励吗？}
#{3500}{}{You certainly will. Here's 5000 caps, you've definitely earned them. And an extra 2000 so you can properly equip yourself for the assault on the Rebirth base.}
{3500}{}{你一定会的。这是5000顶瓶盖，你一定赚了。另外还有2000英镑，这样你就可以为重生基地的攻击做好准备了。}
#{3501}{}{Thanks, I'll be on my way then.}
{3501}{}{谢谢，那我就上路了。}
#{3550}{}{You certainly will. Here's 5000 caps, you've definitely earned them. And an extra 2000 so you can properly equip yourself for the assault on the Rebirth base.}
{3550}{}{你一定会的。这是5000顶瓶盖，你一定赚了。另外还有2000英镑，这样你就可以为重生基地的攻击做好准备了。}
#{3551}{}{Thanks, I'll be on my way then.}
{3551}{}{谢谢，那我就上路了。}
#{3600}{}{Wait. Here's 5000 caps, you definitely deserve them for fighting against mutants. And an extra 2000 so you can properly equip yourself for the assault on the Rebirth base.}
{3600}{}{等待。这是5000顶瓶盖，你绝对配得上它们对抗变种人。另外还有2000英镑，这样你就可以为重生基地的攻击做好准备了。}
#{3601}{}{Thanks, I'll be on my way then.}
{3601}{}{谢谢，那我就上路了。}
#{3650}{}{Wait. Here's 5000 caps, you definitely deserve them for fighting against mutants. And an extra 2000 so you can properly equip yourself for the assault on the Rebirth base.}
{3650}{}{等待。这是5000顶瓶盖，你绝对配得上它们对抗变种人。另外还有2000英镑，这样你就可以为重生基地的攻击做好准备了。}
#{3651}{}{Thanks, I'll be on my way then.}
{3651}{}{谢谢，那我就上路了。}
#{3700}{}{You certainly will. Here's 5000 caps, you've definitely earned them.}
{3700}{}{你一定会的。这是5000顶瓶盖，你一定赚了。}
#{3701}{}{Cool. Can I join the attack on the Rebirth base?}
{3701}{}{很酷。我能加入对重生基地的攻击吗？}
#{3702}{}{Thanks, I'll be going now.}
{3702}{}{谢谢，我现在就走。}
#{3750}{}{We'll need all the help we can get. I can't send too many men, as we must always be ready in case of an attack on the city, and a small group will be more suitable for fighting in an underground complex. I will send a few Hunters to hide near the entrance and wait for you. Together you will attack, and put an end to the ghouls' foolish plan.}
{3750}{}{我们需要所有能得到的帮助。我不能派太多的人，因为我们必须随时准备好，以防城市遭到攻击，一小队人更适合在地下建筑群里作战。我会派几个猎人躲在门口等你。你们将一起攻击，结束僵尸的愚蠢计划。}
#{3751}{}{Thanks, I'll be on my way then.}
{3751}{}{谢谢，那我就上路了。}
#{3800}{}{Here's an extra 2000 caps so you can properly equip yourself for the attack.}
{3800}{}{这是额外的2000个瓶盖，这样你就可以正确装备自己的攻击。}
#{3801}{}{Thanks.}
{3801}{}{谢谢。}
#{3850}{}{Would you consider joining the attack? We'll need all the help we can get. I can't send too many men, as we must always be ready in case of an attack on the city, and a small group will be more suitable for fighting in an underground complex.}
{3850}{}{你会考虑加入攻击吗？我们需要所有能得到的帮助。我不能派太多的人，因为我们必须随时准备好，以防城市遭到攻击，一小队人更适合在地下建筑群里作战。}
#{3851}{}{I'm definitely in.}
{3851}{}{我肯定在。}
#{3852}{}{No, I'm not interested.}
{3852}{}{不，我不感兴趣。}
#{3900}{}{Excellent. I will send a few Hunters to hide near the entrance and wait for you. Together you will attack, and put an end to the ghouls' foolish plan. Here's an extra 2000 caps so you can properly equip yourself for the attack.}
{3900}{}{杰出的。我会派几个猎人躲在门口等你。你们将一起攻击，结束僵尸的愚蠢计划。这是额外的2000个瓶盖，这样你就可以正确装备自己的攻击。}
#{3901}{}{Thanks, I'll be on my way then.}
{3901}{}{谢谢，那我就上路了。}
#{3950}{}{Wait. Here's 5000 caps, you definitely deserve them for fighting against mutants.}
{3950}{}{等待。这是5000顶瓶盖，你绝对配得上它们对抗变种人。}
#{3951}{}{Thanks, I'll be going now.}
{3951}{}{谢谢，我现在就走。}
#{4000}{}{Was there any other important information in the holodisk? There must've been something about the Rebirth plans! Or something that could've helped you remember why they're after you?}
{4000}{}{全息盘中还有其他重要信息吗？一定有重生计划！或者一些能帮你记住他们为什么追你的东西？}
#{4001}{}{No, I still don't remember. Well, the holodisk also contained... Ehh, it's not easy to say this, but the ghouls want to eradicate all humans.}
{4001}{}{不，我还是不记得了。全息盘上还有。。。呃，这不好说，但僵尸想消灭所有人类。}
#{4002}{}{I used to be a ghoul, but my tissue was restored. The ghouls in the Rebirth believe they can all be cured this way, but their leader, called the Savior, is trying to keep secret that the change is only temporary. That's why he turned everyone against me.}
{4002}{}{我以前是个僵尸，但我的组织被修复了。重生中的僵尸相信他们都可以通过这种方式治愈，但他们的领袖，被称为救世主，正试图保守秘密，改变只是暂时的。所以他让大家都反对我。}
#{4003}{}{I used to be a ghoul, but my tissue was restored. The ghouls in the Rebirth believe they can all be cured this way, but their leader, called the Savior, is trying to keep secret that the change is only temporary. That's why he turned everyone against me.}
{4003}{}{我以前是个僵尸，但我的组织被修复了。重生中的僵尸相信他们都可以通过这种方式治愈，但他们的领袖，被称为救世主，正试图保守秘密，改变只是暂时的。所以他让大家都反对我。}
#{4050}{}{I knew it! They're just dumb, bloodthirsty beasts. They must me exterminated, for the sake of all pure humans. Now that we know the location of their base, we can finally attack the Rebirth.}
{4050}{}{我就知道！他们只是愚蠢，嗜血的野兽。为了所有纯洁的人类，他们必须消灭我。现在我们知道了他们基地的位置，我们终于可以攻击重生了。}
#{4051}{}{I want to join that attack.}
{4051}{}{我想加入攻击。}
#{4052}{}{Will I get a reward for delivering the holodisk?}
{4052}{}{我送全息光盘会得到奖励吗？}
#{4053}{}{Hm, I'll be going then.}
{4053}{}{嗯，那我就去。}
#{4100}{}{A mutant that looks like a human! Only mutants could create something so vile and devious. You'll never get out of here, you're too big of a threat to pure humans. But you might be useful to us when we lock you up.}
{4100}{}{一个看起来像人类的变种人！只有变种人才能创造出如此卑鄙和狡猾的东西。你永远不会离开这里，你对纯人类的威胁太大了。但当我们把你关起来的时候，你可能对我们有用。}
#{4101}{}{[Let them imprison you.]}
{4101}{}{[让他们把你关起来。]}
#{4102}{}{[Defend yourself.]}
{4102}{}{[为自己辩护。]}
#{4150}{}{Really? How is that possible?}
{4150}{}{真正地？这怎么可能？}
#{4151}{}{I've killed every single one of them.}
{4151}{}{我把他们都杀了。}
#{4152}{}{I've killed every single one of them.}
{4152}{}{我把他们都杀了。}
#{4153}{}{They just left. They probably never intended to stay there, it was just a stop on their way to the east.}
{4153}{}{他们刚离开。他们可能从来没有打算呆在那里，那只是他们去东部途中的一站。}
#{4200}{}{What are you trying to pull here? Nobody would fall for a pathetic lie like that.}
{4200}{}{你想拉什么？没有人会相信那种可悲的谎言。}
#{4201}{}{Can't blame me for trying to take credit. Sorry. To tell the truth, they just left. They probably never intended to stay there, it was just a stop on their way to the east.}
{4201}{}{不能怪我想占便宜。对不起的。说实话，他们刚离开。他们可能从来没有打算呆在那里，那只是他们去东部途中的一站。}
#{4202}{}{It's the truth! Why don't you go there and see for yourself?}
{4202}{}{这是事实！你为什么不亲自去看看呢？}
#{4250}{}{Are you trying to lure me into a trap? Are you helping the super mutants? You make me sick, betrayer of the human race!}
{4250}{}{你想把我诱入陷阱吗？你在帮助超级变种人吗？你让我恶心，背叛人类的人！}
#{4251}{}{And you make me sick!}
{4251}{}{你让我恶心！}
#{4300}{}{I hope the super mutants left at least something undamaged. I'll send a few men to search and eventually secure the base. Thank you for the information.}
{4300}{}{我希望超级变种人留下的东西至少完好无损。我会派几个人去搜索，最终确保基地的安全。谢谢你的信息。}
#{4301}{}{I've already searched the base. There was only one functional computer left. Tunrida stored the report from the interrogation of the ghoul there, but the file is protected. It can't even be copied without your fingerprints.}
{4301}{}{我已经搜查过基地了。只剩下一台功能正常的电脑了。Tunrida把审讯僵尸的报告存放在那里，但文件受到保护。没有你的指纹连复制都做不到。}
#{4302}{}{I've already searched the base. There was only one functional computer left. Tunrida stored the report from the interrogation of the ghoul there, but the file is protected. It can't even be copied without your fingerprints.}
{4302}{}{我已经搜查过基地了。只剩下一台功能正常的电脑了。Tunrida把审讯僵尸的报告存放在那里，但文件受到保护。没有你的指纹连复制都做不到。}
#{4303}{}{Uh, OK then.}
{4303}{}{呃，那好吧。}
#{4304}{}{No, you should go there personally. There's something you really have to see. It's hard to describe. Just come with me. I already told you there's no danger.}
{4304}{}{不，你应该亲自去。有些东西你真的得去看看。很难形容。跟我来。我已经告诉过你没有危险了。}
#{4350}{}{The information could be vital. Let's go there immediately.}
{4350}{}{这些信息可能至关重要。我们马上去那儿吧。}
#{4351}{}{OK. [Head to the base with Sebastian.]}
{4351}{}{好 啊。[和塞巴斯蒂安一起去基地。]}
#{4370}{}{[Sebastian ponders for a moment, never taking his eyes off you.] Very well. If you insist, I will go with you. But I can't leave just like that. I need to give orders to my officers telling them what do in my absence. Wait here, it won't take more than an hour, we can go then.}
{4370}{}{[塞巴斯蒂安沉思了一会儿，眼睛一直盯着你]很好。如果你坚持，我就和你一起去。但我不能就这样离开。我需要给我的官员下达命令，告诉他们我不在的时候该怎么办。在这儿等，不超过一个小时，我们就可以走了。}
#{4371}{}{Sure, a little wait won't kill me. [Wait until Sebastian comes back and head to the base with him.]}
{4371}{}{当然，稍等不会害死我。[等塞巴斯蒂安回来和他一起去基地。]}
#{4400}{}{Stop wasting time here, }
{4400}{}{别再浪费时间了，}
#{4401}{}{. The attack must begin as soon as possible.}
{4401}{}{. 进攻必须尽快开始。}
#{4402}{}{I want to ask what you know about the Rebirth.}
{4402}{}{我想问你对重生了解多少。}
#{4403}{}{Can you tell me the purpose of this organization - the Mutant Hunters?}
{4403}{}{你能告诉我这个组织的目的吗？变种猎人？}
#{4404}{}{I want to join the Hunters.}
{4404}{}{我想加入猎人队。}
#{4405}{}{OK.}
{4405}{}{好 啊。}
#{4450}{}{What is it you wish... }
{4450}{}{你想要什么。。。}
#{4451}{}{, yes? [Sebastian gives you a piercing stare, as if he thoroughly assessed you in a single moment. You have a strange, hard to describe feeling about him.]}
{4451}{}{，是吗？[塞巴斯蒂安瞪了你一眼，好像他在一瞬间就彻底地评估了你。你对他有一种奇怪的、难以形容的感觉。]}
#{4452}{}{What is it you wish, }
{4452}{}{你想要什么，}
#{4453}{}{?}
{4453}{}{?}
#{4454}{}{I want to know more about the Rebirth.}
{4454}{}{我想知道更多关于重生的事。}
#{4455}{}{I had some questions about our goal - the eradication of all mutants.}
{4455}{}{我对我们的目标有些疑问-消灭所有变种人。}
#{4456}{}{I have some questions.}
{4456}{}{我有一些问题。}
#{4457}{}{I have the holodisk with Tunrida's report of the interrogation of the Rebirth ghoul. Including the location of their base! [Give it to him.]}
{4457}{}{我有通利达关于审讯重生僵尸的报告的全息光盘。包括他们基地的位置！[把它给他。]}
#{4458}{}{I've read the holodisk with the report of the interrogation of the Rebirth ghoul. Sadly, the holodisk was destroyed, but I managed to write down the coordinates of the Rebirth base. [Tell him the location of the base.]}
{4458}{}{我读了全息光盘，里面有审讯重生僵尸的报告。遗憾的是，全息盘被毁了，但我设法记下了重生基地的坐标。[告诉他基地的位置。]}
#{4459}{}{I've read the holodisk with the report of the interrogation of the Rebirth ghoul. Sadly, the holodisk was destroyed, but I managed to write down the coordinates of the Rebirth base. [Tell him the location of the base.]}
{4459}{}{我读了全息光盘，里面有审讯重生僵尸的报告。遗憾的是，全息盘被毁了，但我设法记下了重生基地的坐标。[告诉他基地的位置。]}
#{4460}{}{The super mutants that were occupying our forward base are gone.}
{4460}{}{占领我们前线基地的超级变种人已经消失了。}
#{4461}{}{Nothing, sorry for bothering you.}
{4461}{}{没什么，抱歉打扰你了。}
#{4462}{}{Uf.}
{4462}{}{佛罗里达州。}
#{4500}{}{You're one of the Hunters, so you should know everything about our greatest current enemy that I or any other Hunter already knows.}
{4500}{}{你是猎人中的一员，所以你应该知道我或其他猎人已经知道的关于我们目前最大敌人的一切。}
#{4501}{}{I want to make sure I didn't miss anything. Please, tell me about the Rebirth.}
{4501}{}{我想确保我没有错过任何东西。请告诉我重生的事。}
#{4502}{}{Do they have a base somewhere?}
{4502}{}{他们有基地吗？}
#{4503}{}{Tell me everything you know or I'll blow your fucking head off!}
{4503}{}{把你知道的都告诉我，否则我就把你的脑袋炸了！}
#{4504}{}{I guess so.}
{4504}{}{我想是的。}
#{4550}{}{I'm always glad to see the determination to rid the world of mutants in a Hunter, but we would've taken care of that a long time ago if we knew the location of the base. Tunrida was close to reaching our goal, but super mutants ruined everything.}
{4550}{}{我一直很高兴看到猎人有决心消灭世界上的变种人，但如果我们知道基地的位置，我们早就搞定了。Tunrida接近我们的目标，但是超级变种人毁了一切。}
#{4551}{}{What are you talking about?}
{4551}{}{你在说什么？}
#{4600}{}{We have a forward base southeast of the city that we use for external operations. We keep radio contact only rarely to avoid exposing its location to the Rebirth. But commander Tunrida has recently reported that an interrogation of one of the ghouls revealed some new information about the Rebirth and that she'll soon know the location of their base. We waited for someone to arrive with the full report, but nothing happened, nobody even answered the radio. Our scouts later discovered that the base has been taken over by a group of super mutants that massacred our people.}
{4600}{}{我们在城市东南部有一个前线基地，用于对外作战。我们很少保持无线电联系，以避免它的位置暴露给重生。但是指挥官Tunrida最近报告说，对其中一个僵尸的审讯揭示了一些关于重生的新信息，她很快就会知道他们基地的位置。我们等着有人带着完整的报告来，但什么也没发生，甚至没有人接收音机。我们的侦察兵后来发现基地被一群屠杀我们人民的超级变种人占领了。}
#{4601}{}{Why don't we attack the super mutants?}
{4601}{}{为什么我们不攻击超级变种人？}
#{4602}{}{Is there no other way to get that info?}
{4602}{}{没有其他方法可以得到这些信息吗？}
#{4603}{}{What's the purpose of our base outside Albuquerque?}
{4603}{}{我们在阿尔伯克基外的基地有什么目的？}
#{4604}{}{Where is it? I'll go there and get that info for us.}
{4604}{}{它在哪里？我去那里为我们获取信息。}
#{4650}{}{They've barricaded themselves in, dug a moat around the base and filled it with some radioactive crap - they're ready for any attack. If we attacked, there wouldn't be anyone left to defend the city, making it an easy target for the Rebirth.}
{4650}{}{他们把自己围起来，在基地周围挖了一条护城河，里面装满了一些放射性废物——他们已经做好了任何攻击的准备。如果我们进攻，就不会有人留下来保卫这座城市，使它成为重生的容易目标。}
#{4651}{}{Is there no other way to get that info?}
{4651}{}{没有其他方法可以得到这些信息吗？}
#{4652}{}{What's the purpose of our base outside Albuquerque?}
{4652}{}{我们在阿尔伯克基外的基地有什么目的？}
#{4653}{}{Where is that base? I'll go there and get that info for us.}
{4653}{}{基地在哪里？我去那里为我们获取信息。}
#{4700}{}{No. We tried everything, but the ghouls refused to talk. Every bit of information that Tunrida may have discovered could be important. I just hope the super mutants didn't destroy everything. Because of their mental deficiency, computers are worthless to them.}
{4700}{}{没有。我们什么都试过了，但僵尸拒绝说话。Tunrida发现的每一点信息都可能很重要。我只希望超级变种人没有毁掉一切。由于他们的智力缺陷，计算机对他们来说一文不值。}
#{4701}{}{Why don't we attack the super mutants?}
{4701}{}{为什么我们不攻击超级变种人？}
#{4702}{}{What's the purpose of our base outside Albuquerque?}
{4702}{}{我们在阿尔伯克基外的基地有什么目的？}
#{4703}{}{Where is that base? I'll go there and get that info for us.}
{4703}{}{基地在哪里？我去那里为我们获取信息。}
#{4750}{}{It's actually an old army warehouse - we found pre-war weapons and a few suits of power armor inside. We used it for researching mutation and interrogating Rebirth ghouls. We simply don't have the means to do that here, we need to be always ready for battle. And since we keep the city clean of mutants, bringing too many prisoners here would be too much of a risk.}
{4750}{}{这实际上是一个旧的陆军仓库-我们在里面发现了战前的武器和几套动力装甲。我们用它来研究变异和审问重生的僵尸。我们根本没有办法做到这一点，我们需要随时准备战斗。既然我们保持城市里没有变种人，把太多的囚犯带到这里就太危险了。}
#{4751}{}{Why don't we attack the super mutants?}
{4751}{}{为什么我们不攻击超级变种人？}
#{4752}{}{Is there no other way to get that info?}
{4752}{}{没有其他方法可以得到这些信息吗？}
#{4753}{}{Where is that base? I'll go there and get that info for us.}
{4753}{}{基地在哪里？我去那里为我们获取信息。}
#{4800}{}{Excellent, if everyone was as determined to fight for our cause as you are, we would've cleansed the world of the mutant blight a long time ago. I can't spare a single man - you'll have to go in alone. I recommend trying to sneak in instead of a frontal attack. I doubt you'll be able to reason with the filthy mutants, not even one of the Children of the Cathedral could probably do it. The base is located here. [He shows you the location on a map.]}
{4800}{}{好极了，如果每个人都像你们一样决心为我们的事业而战，我们早就清除了这个世界上的变异疫病了。我不能放过一个人，你得一个人进去。我建议试着偷袭而不是正面攻击。我怀疑你能不能跟那些肮脏的变种人讲道理，甚至连大教堂的孩子都做不到。基地就在这里。[他给你看地图上的位置。]}
#{4801}{}{Children of the Cathedral?}
{4801}{}{大教堂的孩子们？}
#{4802}{}{I'll go there and find out all I can.}
{4802}{}{我要去那里尽我所能找出答案。}
#{4850}{}{The Children of the Cathedral are the biggest traitors to the human race. They used to serve the Master and his super mutants. Of course, it didn't do them any good, because after the Master's death, the super mutants attacked them along with the rest of pure humans.}
{4850}{}{大教堂的孩子们是人类最大的叛徒。他们曾经为主人和他的超级变种人服务。当然，这对他们没有任何好处，因为在大师死后，超级变种人和其他纯人类一起攻击他们。}
#{4851}{}{I see. I'll head to the base and find out all I can.}
{4851}{}{我懂了。我要去基地，尽我所能找出答案。}
#{4900}{}{What questions?}
{4900}{}{什么问题？}
#{4901}{}{Don't the mutants have the right to live like other humans?}
{4901}{}{难道变种人没有权利像其他人一样生活吗？}
#{4902}{}{Minor mutations are common. What about people with an extra finger or toe?}
{4902}{}{微小的突变很常见。有多余手指或脚趾的人呢？}
#{4903}{}{The mutants aren't to blame. Even you would mutate easily if you were exposed to a sufficient dose of radiation.}
{4903}{}{变种人不是罪魁祸首。即使你暴露在足够剂量的辐射下也很容易变异。}
#{4904}{}{How do we hope to exterminate all the mutants?}
{4904}{}{我们希望如何消灭所有的变种人？}
#{4905}{}{What do you know about the Master?}
{4905}{}{你对师父了解多少？}
#{4906}{}{I wanted to ask something else.}
{4906}{}{我想问点别的。}
#{4907}{}{None.}
{4907}{}{没有。}
#{4950}{}{What do you wish to know?}
{4950}{}{你想知道什么？}
#{4951}{}{I want to know more about the Rebirth.}
{4951}{}{我想知道更多关于重生的事。}
#{4952}{}{I had some questions about our goal - the eradication of all mutants.}
{4952}{}{我对我们的目标有些疑问-消灭所有变种人。}
#{4953}{}{I have some general questions.}
{4953}{}{我有一些一般性的问题。}
#{4954}{}{Nothing else.}
{4954}{}{没别的了。}
#{5000}{}{Really?! I'll take a look immediately. [He quickly connects the holodisk and reads its contents.] It's worse than I ever imagined. The insane mutants believe they can cure themselves! But all they will accomplish is killing scores of genetically pure humans. Only a sick mutant mind could come up with a plan like that.}
{5000}{}{真正地？！我马上去看看。[他迅速连接全息光盘并读取其内容]这比我想象的还要糟糕。疯狂的变种人相信他们能治愈自己！但他们所要做的就是杀死几十个基因纯正的人类。只有病态的变种人才能想出这样的计划。}
#{5001}{}{What now?}
{5001}{}{现在怎么办？}
#{5050}{}{The course is clear - we must stop them, for the sake of all pure humans. We must kill that Savior and destroy their base. Now that we know where it is, we can finally attack! And I'm sure you want to take part in the attack.}
{5050}{}{我们必须阻止他们，为了所有纯洁的人类。我们必须杀死救世主，摧毁他们的基地。现在我们知道它在哪里了，我们终于可以进攻了！我肯定你想参加这次袭击。}
#{5051}{}{I sure do.}
{5051}{}{我当然知道。}
#{5052}{}{Frontal attack doesn't seem like a good idea to me.}
{5052}{}{正面进攻在我看来不是个好主意。}
#{5100}{}{No matter. The assault on the main Rebirth base will require determined people who know what has to be done. Cowards like you would only threaten our success. Regardless, you deserve 5000 caps for getting the holodisk.}
{5100}{}{没关系。对主要重生基地的攻击将需要有决心的人知道必须做什么。像你这样的懦夫只会威胁我们的成功。不管怎样，你应该得到5000顶瓶盖才能得到全息光盘。}
#{5101}{}{Thanks.}
{5101}{}{谢谢。}
#{5150}{}{Excellent. I will send a few Hunters to hide near the entrance and wait for you. Together you will attack, and put an end to the ghouls' foolish plan. Here's 2000 caps so you can properly equip yourself for the assault.}
{5150}{}{杰出的。我会派几个猎人躲在门口等你。你们将一起攻击，结束僵尸的愚蠢计划。这里有2000顶瓶盖，你可以好好装备一下。}
#{5151}{}{Very well, I'll be on my way.}
{5151}{}{很好，我马上就来。}
#{5200}{}{Wait. Here's 5000 caps, you definitely deserve them for fighting against mutants. You will also receive a suit of power armor - we must leave nothing to chance during the attack on the Rebirth. Kraig will give it to you.}
{5200}{}{等待。这是5000顶瓶盖，你绝对配得上它们对抗变种人。你也将得到一套强力护甲-在重生的攻击中，我们不能留下任何机会。克莱格会给你的。}
#{5201}{}{Cool.}
{5201}{}{很酷。}
#{5250}{}{Stop wasting time here, }
{5250}{}{别再浪费时间了，}
#{5251}{}{. The attack must begin as soon as possible.}
{5251}{}{. 进攻必须尽快开始。}
#{5252}{}{I want to ask what you know about the Rebirth.}
{5252}{}{我想问你对重生了解多少。}
#{5253}{}{I had some questions about our goal - the eradication of all mutants.}
{5253}{}{我对我们的目标有些疑问-消灭所有变种人。}
#{5254}{}{I have some questions.}
{5254}{}{我有一些问题。}
#{5255}{}{OK.}
{5255}{}{好 啊。}
#{5300}{}{What is it?}
{5300}{}{这是怎么一回事？}
#{5301}{}{What can you tell me about the city?}
{5301}{}{关于这个城市你能告诉我什么？}
#{5302}{}{Could you tell me the history of the Mutant Hunters?}
{5302}{}{你能告诉我变种猎人的历史吗？}
#{5303}{}{What can you tell me about your officers?}
{5303}{}{你能告诉我关于你们军官的什么情况吗？}
#{5304}{}{What would you do if there weren't any more mutants?}
{5304}{}{如果没有更多的变种你会怎么做？}
#{5305}{}{I actually wanted to ask about something else.}
{5305}{}{我其实还想问点别的。}
#{5306}{}{That's all, actually.}
{5306}{}{事实上，仅此而已。}
#{5350}{}{When the time comes, we'll solve all the problems of this city, including the biggest two - the empire and the immigrants. Then Albuquerque will be the first clean city, and other cities will surely follow its example.}
{5350}{}{到时候，我们会解决这个城市的所有问题，包括最大的两个问题——帝国和移民。届时，阿尔伯克基将成为第一个清洁城市，其他城市肯定会效仿它。}
#{5351}{}{What's wrong with the empire?}
{5351}{}{帝国怎么了？}
#{5352}{}{What's wrong with the immigrants?}
{5352}{}{移民怎么了？}
#{5353}{}{Another question.}
{5353}{}{另一个问题。}
#{5354}{}{I wanted to ask something else.}
{5354}{}{我想问点别的。}
#{5355}{}{That's all I needed.}
{5355}{}{这就是我所需要的。}
#{5400}{}{They refuse to recognize the mutant threat, and that puts us all in danger. We came here and offered our help, and the emperor took it as a business offer. We rid the city of the mutated inhabits and they said it was a concession to us! We protect them not only from the Rebirth, but from all the other mutants as well, and despite all the resources they have at their disposal, they gave us so little.}
{5400}{}{他们拒绝承认变种人的威胁，这使我们都处于危险之中。我们来到这里提供帮助，皇帝把它当作生意上的提议。我们清除了城市里变异的居民，他们说这是对我们的让步！我们不仅保护它们不受重生的伤害，而且也保护它们不受所有其他变种的伤害，尽管它们拥有所有可以支配的资源，但它们给我们的却很少。}
#{5401}{}{Why are we still helping them then?}
{5401}{}{那我们为什么还要帮助他们？}
#{5402}{}{Another question.}
{5402}{}{另一个问题。}
#{5403}{}{I wanted to ask something else.}
{5403}{}{我想问点别的。}
#{5404}{}{That's all I needed.}
{5404}{}{这就是我所需要的。}
#{5450}{}{We're not going to lose so many genetically pure humans because of a few fools. When the emperor didn't give us what we needed, we had to take it. If we hadn't, we wouldn't have lasted here this long with the meagre resources we had.}
{5450}{}{我们不会因为几个傻瓜而失去这么多基因纯正的人类。当皇帝没有给我们所需要的东西时，我们只好接受。如果我们没有，我们就不会在这里用我们仅有的微薄资源维持这么长时间。}
#{5451}{}{What are you talking about?}
{5451}{}{你在说什么？}
#{5452}{}{Another question.}
{5452}{}{另一个问题。}
#{5453}{}{I wanted to ask something else.}
{5453}{}{我想问点别的。}
#{5454}{}{That's all I needed.}
{5454}{}{这就是我所需要的。}
#{5500}{}{You have access to the entire base, so you can go see for yourself that we've taken over the third floor of the Vault without the emperor suspecting anything. And his reaction proved his cowardice. Instead of fighting, he simply closed off the Imperial City.}
{5500}{}{你可以进入整个基地，所以你可以亲自去看看，我们已经接管了金库的第三层，皇帝没有任何怀疑。他的反应证明了他的懦弱。他没有战斗，只是封锁了皇城。}
#{5501}{}{You have access to the entire base, so you can go see for yourself that we've taken over the third floor of the Vault without the emperor suspecting anything. And his reaction proved what a coward he was. Instead of fighting, he simply closed off the Imperial City.}
{5501}{}{你可以进入整个基地，所以你可以亲自去看看，我们已经接管了金库的第三层，皇帝没有任何怀疑。他的反应证明了他是个懦夫。他没有战斗，只是封锁了皇城。}
#{5502}{}{What will happen next?}
{5502}{}{接下来会发生什么？}
#{5503}{}{Another question.}
{5503}{}{另一个问题。}
#{5504}{}{I wanted to ask something else.}
{5504}{}{我想问点别的。}
#{5505}{}{That's all I needed.}
{5505}{}{这就是我所需要的。}
#{5550}{}{The empire only admitted that building a decent defense is necessary when the second great attack of the Rebirth destroyed a part of the city and took many of their soldiers. The wall of debris from the Dead Quarter shows how blind the imperial dwellers are, especially considering that the mutants hate the vault dwellers the most of all pure humans. Once we dispose of the Rebirth, we'll have to gain control of the whole of Albuquerque to make sure the city is clean and safe.}
{5550}{}{帝国只承认，当重生的第二次大攻击摧毁了城市的一部分并带走了他们的许多士兵时，建立一个体面的防御是必要的。死区的废墟墙显示出帝国居民是多么的盲目，特别是考虑到变种人最讨厌地窖居民，而所有的纯人类。一旦我们处理了重生，我们就必须控制整个阿尔伯克基，以确保城市的清洁和安全。}
#{5551}{}{What's wrong with the immigrants?}
{5551}{}{移民怎么了？}
#{5552}{}{Another question.}
{5552}{}{另一个问题。}
#{5553}{}{I wanted to ask something else.}
{5553}{}{我想问点别的。}
#{5554}{}{That's all I needed.}
{5554}{}{这就是我所需要的。}
#{5600}{}{The Rebirth is destroying cities and villages on a large scale. Those who escaped are hiding here in Albuquerque. Instead of defending their homes, they simply fled. Most of them are useless cowards. Additionally, many mutants try to get into the city with them - and some traitorous immigrants even help them.}
{5600}{}{重生正在大规模地摧毁城市和村庄。那些逃跑的人躲在阿尔伯克基。他们没有保卫家园，而是逃跑了。他们大多数都是没用的懦夫。此外，许多变种人试图和他们一起进城，一些叛国移民甚至帮助他们。}
#{5601}{}{What are we going to do about it?}
{5601}{}{我们该怎么办？}
#{5602}{}{Another question.}
{5602}{}{另一个问题。}
#{5603}{}{I wanted to ask something else.}
{5603}{}{我想问点别的。}
#{5604}{}{That's all I needed.}
{5604}{}{这就是我所需要的。}
#{5650}{}{In our current situation, we're happy that we can keep Albuquerque clean. But in the future, everyone will have to take part in the fight against mutants - the fight for their own survival. If not personally, then by contributing supplies or services. In addition, helping the mutants in any way - including the failure to report them - will warrant a public execution. Everyone must be made aware that the survival of mankind is the responsibility of all pure humans.}
{5650}{}{在我们目前的情况下，我们很高兴能保持阿尔伯克基的清洁。但在未来，每个人都必须参与对抗突变体的战斗——为自己的生存而战。如果不是个人，则通过提供供应品或服务。此外，以任何方式帮助变种人——包括不报告他们——都将被公开处决。每个人都必须意识到，人类的生存是所有纯人类的责任。}
#{5651}{}{What's wrong with the empire?}
{5651}{}{帝国怎么了？}
#{5652}{}{Another question.}
{5652}{}{另一个问题。}
#{5653}{}{I wanted to ask something else.}
{5653}{}{我想问点别的。}
#{5654}{}{That's all I needed.}
{5654}{}{这就是我所需要的。}
#{5700}{}{There is a computer in the room behind the lecture hall that is available to all Hunters and contains our history. You can learn everything you need to know there.}
{5700}{}{报告厅后面的房间里有一台电脑，所有的猎人都可以使用，里面有我们的历史。你可以在那里学到你需要知道的一切。}
#{5701}{}{Another question.}
{5701}{}{另一个问题。}
#{5702}{}{I wanted to ask something else.}
{5702}{}{我想问点别的。}
#{5703}{}{That's all I needed.}
{5703}{}{这就是我所需要的。}
#{5750}{}{Dutch is in charge of defending the city, meaning that no Rebirth attack has a chance. Thanks to Herman, the city is clean of all mutants, despite the only small number of Hunters I can spare for him. Tulsa makes sure the base keeps running. Truth be told, I've always been a bit sceptical about his abilities, but the base is working perfectly.}
{5750}{}{荷兰人负责保卫这座城市，这意味着没有重生的机会。多亏了赫尔曼，这座城市没有任何变种人，尽管我只能为他保留少量的猎人。塔尔萨确保基地继续运转。说实话，我一直有点怀疑他的能力，但基地运作得很好。}
#{5751}{}{And the fourth officer?}
{5751}{}{四副呢？}
#{5752}{}{Another question.}
{5752}{}{另一个问题。}
#{5753}{}{I wanted to ask something else.}
{5753}{}{我想问点别的。}
#{5754}{}{That's all I needed.}
{5754}{}{这就是我所需要的。}
#{5800}{}{Tunrida was always uncompromising, strong, and ready to do anything to destroy mutants. But since she wasn't able to defend our forward base from the super mutants, I may have overestimated her abilities.}
{5800}{}{Tunrida总是毫不妥协，坚强，随时准备做任何事情来消灭变种人。但既然她没能保护我们的前线基地免受超级变种人的攻击，我可能高估了她的能力。}
#{5801}{}{Another question.}
{5801}{}{另一个问题。}
#{5802}{}{I wanted to ask something else.}
{5802}{}{我想问点别的。}
#{5803}{}{That's all I needed.}
{5803}{}{这就是我所需要的。}
#{5850}{}{What are we going to do after we purge humanity of the mutant scum? Make sure it stays that way, of course.}
{5850}{}{在我们清除人类的变种人渣之后，我们该怎么办？当然，一定要保持这种状态。}
#{5851}{}{Another question.}
{5851}{}{另一个问题。}
#{5852}{}{I wanted to ask something else.}
{5852}{}{我想问点别的。}
#{5853}{}{That's all I needed.}
{5853}{}{这就是我所需要的。}
#{5900}{}{Yes? [The man gives you a piercing stare, as if he thoroughly assessed you in a single moment. You have a strange, hard to describe feeling about him.]}
{5900}{}{对？[那人瞪了你一眼，好像他在一瞬间就彻底地评估了你。你对他有一种奇怪的、难以形容的感觉。]}
#{5901}{}{Hee, who you?}
{5901}{}{嘿，你是谁？}
#{5902}{}{Naah.}
{5902}{}{啊。}
#{5950}{}{My name is Sebastian. And I'm very curious who you are and, more importantly, what you're doing here.}
{5950}{}{我叫塞巴斯蒂安。我很好奇你是谁，更重要的是，你在这里做什么。}
#{5951}{}{Me }
{5951}{}{我}
#{5952}{}{.}
{5952}{}{.}
#{6000}{}{Very well }
{6000}{}{很好}
#{6001}{}{. What are you doing here then?}
{6001}{}{. 那你在这里干什么？}
#{6002}{}{Uh, tah-lisman. He?}
{6002}{}{呃，塔赫里斯曼。他？}
#{6003}{}{Wut yu do here?}
{6003}{}{你在这儿干什么？}
#{6004}{}{Me bai bai.}
{6004}{}{我叫白白。}
#{6005}{}{Uh, tah-lisman. [Start waving your arms around to signify the circular shapes of the symbol.] He?}
{6005}{}{呃，塔赫里斯曼。[开始挥舞你的手臂来表示符号的圆形。]他？}
#{6050}{}{A talisman of the Rebirth.}
{6050}{}{重生的护身符。}
#{6051}{}{Re-burf?}
{6051}{}{你打嗝了？}
#{6100}{}{The talisman is the symbol of the Rebirth, worn by every ghoul belonging to it. The Rebirth seems to be a new ghoul religion of some kind. We know next to nothing about it, only that they speak of a certain Savior, their leader. They somehow managed to gain access to advanced pre-war weapons, and they use them to attack villages as well as large cities. They always raze the place to the ground, capture as many humans as they can and lead them somewhere we don't know.}
{6100}{}{护身符是重生的象征，属于它的每一个僵尸都戴着它。重生似乎是某种新的僵尸宗教。我们几乎一无所知，只知道他们说的是某个救世主，他们的领袖。他们设法获得了先进的战前武器，并用它们攻击村庄和大城市。他们总是把这个地方夷为平地，抓捕尽可能多的人，把他们带到我们不知道的地方。}
#{6101}{}{Where sumwhere?}
{6101}{}{哪里？哪里？}
#{6150}{}{I told you we don't know where. Their actions indicate that they must have a large base of some sort, likely in an old army complex.}
{6150}{}{我告诉过你我们不知道在哪里。他们的行动表明他们一定有一个很大的基地，很可能是在一个旧的军事基地。}
#{6151}{}{Waah! Want find!}
{6151}{}{哇！想要找到！}
#{6200}{}{I have no idea why you want to find it, but we've been trying to do so for quite some time. As soon as we find its location, we'll raze it to the ground and leave no mutant alive! We were so close, but the super mutants ruined everything again.}
{6200}{}{我不知道你为什么要找它，但我们已经试了很长时间了。一旦我们找到它的位置，我们会把它夷为平地，不让变种人活着！我们很接近，但超级变种人又毁了一切。}
#{6201}{}{He?}
{6201}{}{他？}
#{6250}{}{We have a forward base southeast of the city that we use for external operations. We keep radio contact only rarely to avoid exposing its location to the Rebirth. But commander Tunrida has recently reported that an interrogation of one of the ghouls revealed some new information about the Rebirth and that she'll soon know the location of their base. We waited for someone to arrive with the full report, but nothing happened, nobody even answered the radio. Our scouts later discovered that the base has been taken over by a group of super mutants that massacred our people.}
{6250}{}{我们在城市东南部有一个前线基地，用于对外作战。我们很少保持无线电联系，以避免它的位置暴露给重生。但是指挥官Tunrida最近报告说，对其中一个僵尸的审讯揭示了一些关于重生的新信息，她很快就会知道他们基地的位置。我们等着有人带着完整的报告来，但什么也没发生，甚至没有人接收音机。我们的侦察兵后来发现基地被一群屠杀我们人民的超级变种人占领了。}
#{6251}{}{Uh, where?}
{6251}{}{呃，在哪？}
#{6300}{}{If you want to face certain death at the hands of super mutants that share your mental deficiency then I won't stop you. The base is here. [He shows you the location on a map.]}
{6300}{}{如果你想面对超级变种人的死亡，他们和你一样有智力缺陷，那么我不会阻止你。基地就在这里。[他给你看地图上的位置。]}
#{6301}{}{Hoo!}
{6301}{}{呼！}
#{6350}{}{We're the Mutant Hunters, and this is our base. We're doing what every genetically pure human should - defend the world from the mutant threat. We'll wipe out every last one of them.}
{6350}{}{我们是变种猎人，这是我们的基地。我们在做每一个基因纯正的人类都应该做的事情——保护世界免受突变的威胁。我们会把他们全部消灭。}
#{6351}{}{Supah!}
{6351}{}{苏帕！}
#{6352}{}{Ptui! [Spit at him.]}
{6352}{}{普图伊！[朝他吐口水]}
#{6400}{}{You're a disgrace to all genetically pure humans. Now you can only hope that I'll kill you before the guards take you to doctor Yaotzin, who will try new methods of long and very painful torture on you.}
{6400}{}{你是所有基因纯正人类的耻辱。现在你只能希望我在卫兵带你去见姚津医生之前杀了你，姚津医生会用新的方法对你进行长期痛苦的折磨。}
#{6401}{}{Grr!}
{6401}{}{格瑞！}
#{6450}{}{What do you want now, }
{6450}{}{你现在想要什么，}
#{6451}{}{?}
{6451}{}{?}
#{6452}{}{Uh, tah-lisman. He?}
{6452}{}{呃，塔赫里斯曼。他？}
#{6453}{}{Wut yu do here?}
{6453}{}{你在这儿干什么？}
#{6454}{}{Heehee, you want? [Give him the shiny thing you found in the base occupied by super mutants.]}
{6454}{}{嘿嘿，你想要什么？[把你在超级变种人占领的基地里发现的闪闪发光的东西给他。]}
#{6455}{}{Heehee, you want? [Give him the shiny thing you found in the base occupied by super mutants.]}
{6455}{}{嘿嘿，你想要什么？[把你在超级变种人占领的基地里发现的闪闪发光的东西给他。]}
#{6456}{}{Me bai bai.}
{6456}{}{我叫白白。}
#{6457}{}{Uh, tah-lisman. [Start waving your arms around to signify the circular shapes of the symbol.] He?}
{6457}{}{呃，塔赫里斯曼。[开始挥舞你的手臂来表示符号的圆形。]他？}
#{6500}{}{What's on it? [He takes the shiny thing, connects it to something and stares at it for a while.] Those are the results of the interrogation of the Rebirth ghoul by Tunrida. It's worse than I ever imagined. The insane mutants believe they can cure themselves! But all they will accomplish is killing scores of genetically pure humans. Only a sick mutant mind could come up with a plan like that.}
{6500}{}{上面有什么？[他拿着闪闪发光的东西，把它和什么东西连在一起，盯着它看了一会儿]这是通利达审问重生僵尸的结果。比我想象的还要糟。疯狂的变种人相信他们能治愈自己！但他们所要做的就是杀死几十个基因纯正的人类。只有病态的变种人才能想出这样的计划。}
#{6501}{}{Ghe?}
{6501}{}{啊？}
#{6550}{}{We must stop them for the sake of all pure humans. We must kill that Savior and destroy their base. Thankfully, the holodisk also contained its location. Now that we know where it is, we can finally attack! Do you want to join the assault? We'll need all the help we can get.}
{6550}{}{为了所有纯洁的人类，我们必须阻止他们。我们必须杀死救世主，摧毁他们的基地。谢天谢地，全息盘也包含了它的位置。现在我们知道它在哪里了，我们终于可以进攻了！你想加入突击队吗？我们需要所有能得到的帮助。}
#{6551}{}{Yaah!}
{6551}{}{耶！}
#{6552}{}{Bleh.}
{6552}{}{呜呜。}
#{6600}{}{Excellent. I can't send too many men, as we must always be ready in case of an attack on the city, and a small group will be more suitable for fighting in an underground complex. I will send a few Hunters to hide near the entrance and wait for you. Together you will attack, and put an end to the ghouls' foolish plan. I hope you understand what needs to be done. My people definitely do and if someone tries to stop them, they'll take care of him.}
{6600}{}{杰出的。我不能派太多的人，因为我们必须随时准备好，以防城市遭到攻击，一小队人更适合在地下建筑群里作战。我会派几个猎人躲在门口等你。你们将一起攻击，结束僵尸的愚蠢计划。我希望你明白需要做什么。我的人肯定会的，如果有人试图阻止他们，他们会照顾他的。}
#{6601}{}{Buaha.}
{6601}{}{布阿哈。}
#{6650}{}{Here's 5000 caps for your help in revealing the location of the base. And an extra 2000 so you can properly equip yourself for the assault on the Rebirth base.}
{6650}{}{这里有5000个瓶盖，可以帮你找出基地的位置。另外还有2000英镑，这样你就可以为重生基地的攻击做好准备了。}
#{6651}{}{Gogo.}
{6651}{}{果戈。}
#{6700}{}{Alright, in that case, here's 5000 caps for your help in revealing the location of the base.}
{6700}{}{好吧，这样的话，这里有5000个大写字母，可以帮你找出基地的位置。}
#{6701}{}{Ghe.}
{6701}{}{唉。}
#{6750}{}{Really?! I'll take a look immediately. [He quickly connects the holodisk and reads its contents.] It's worse than I ever imagined. The insane mutants believe they can cure themselves! But all they will accomplish is killing scores of genetically pure humans. Only a sick mutant mind could come up with a plan like that. Wait! The Rebirth is searching for an escaped ghoul that underwent that vile transformation. That matches the story you told me before. You must be the Thirteenth Reborn!}
{6750}{}{真正地？！我马上去看看。[他迅速连接全息光盘并读取其内容]这比我想象的还要糟糕。疯狂的变种人相信他们能治愈自己！但他们所要做的就是杀死几十个基因纯正的人类。只有病态的变种人才能想出这样的计划。等待！重生是寻找一个逃脱的僵尸，经历了邪恶的转变。和你之前告诉我的故事吻合。你一定是第十三个重生！}
#{6751}{}{Really?! I'll take a look immediately. [He quickly connects the holodisk and reads its contents.] It's worse than I ever imagined. The insane mutants believe they can cure themselves! But all they will accomplish is killing scores of genetically pure humans. Only a sick mutant mind could come up with a plan like that. Wait! The Rebirth is searching for an escaped ghoul that underwent that vile transformation. That matches the story you told me before. You must be the Thirteenth Reborn!}
{6751}{}{真正地？！我马上去看看。[他迅速连接全息光盘并读取其内容]这比我想象的还要糟糕。疯狂的变种人相信他们能治愈自己！但他们所要做的就是杀死几十个基因纯正的人类。只有病态的变种人才能想出这样的计划。等待！重生是寻找一个逃脱的僵尸，经历了邪恶的转变。和你之前告诉我的故事吻合。你一定是第十三个重生！}
#{6752}{}{What are you going to do about it?}
{6752}{}{你打算怎么办？}
#{6800}{}{What's on it? [He takes the shiny thing, connects it to something and stares at it for a while.] Those are the results of the interrogation of the Rebirth ghoul by Tunrida. It's worse than I ever imagined. The insane mutants believe they can cure themselves! But all they will accomplish is killing scores of genetically pure humans. Only a sick mutant mind could come up with a plan like that. Wait! The Rebirth is searching for an escaped ghoul that underwent that vile transformation. That matches the story you told me before. You must be the Thirteenth Reborn!}
{6800}{}{上面有什么？[他拿着闪闪发光的东西，把它和什么东西连在一起，盯着它看了一会儿]这是通利达审问重生僵尸的结果。比我想象的还要糟。疯狂的变种人相信他们能治愈自己！但他们所要做的就是杀死几十个基因纯正的人类。只有病态的变种人才能想出这样的计划。等待！重生是寻找一个逃脱的僵尸，经历了邪恶的转变。和你之前告诉我的故事吻合。你一定是第十三个重生！}
#{6801}{}{What's on it? [He takes the shiny thing, connects it to something and stares at it for a while.] Those are the results of the interrogation of the Rebirth ghoul by Tunrida. It's worse than I ever imagined. The insane mutants believe they can cure themselves! But all they will accomplish is killing scores of genetically pure humans. Only a sick mutant mind could come up with a plan like that. Wait! The Rebirth is searching for an escaped ghoul that underwent that vile transformation. That matches the story you told me before. You must be the Thirteenth Reborn!}
{6801}{}{上面有什么？[他拿着闪闪发光的东西，把它和什么东西连在一起，盯着它看了一会儿]这是通利达审问重生僵尸的结果。比我想象的还要糟。疯狂的变种人相信他们能治愈自己！但他们所要做的就是杀死几十个基因纯正的人类。只有病态的变种人才能想出这样的计划。等待！重生是寻找一个逃脱的僵尸，经历了邪恶的转变。和你之前告诉我的故事吻合。你一定是第十三个重生！}
#{6802}{}{He?}
{6802}{}{他？}
