#{100}{}{You see a jovial looking man.}
{100}{}{你看到一个看上去很快乐的人。}
#{150}{}{You see Terrak.}
{150}{}{你看到泰拉克了。}
#{200}{}{You see a man in shining armor. He's observing what goes around him with an amused look.}
{200}{}{你看到一个穿着闪亮盔甲的人。他用一种有趣的眼神观察着周围发生的事情。}
#{250}{}{You see Shaun Terrak, an imperial army lieutenant.}
{250}{}{你看肖恩·泰瑞克，一个帝国陆军中尉。}
#{300}{}{I have nothing to say to you.}
{300}{}{我没什么好说的。}
#{400}{}{You shouldn't have done that.}
{400}{}{你不该那么做。}
#{401}{}{You shouldn't have done that.}
{401}{}{你不该那么做。}
#{500}{}{Greetings, friend. Is there something I can help you with?}
{500}{}{你好，朋友。有什么我能帮你的吗？}
#{501}{}{A pleasant day to you, miss. Is there something I can help you with?}
{501}{}{祝你愉快，小姐。有什么我能帮你的吗？}
#{502}{}{Perhaps there is. That depends on who you are.}
{502}{}{也许有。那要看你是谁了。}
#{503}{}{I doubt that. Bye.}
{503}{}{我对此表示怀疑。再见。}
#{504}{}{Ogar?!}
{504}{}{奥加？！}
#{550}{}{I'm lieutenant Shaun Terrak of the second imperial regiment. [He casually salutes you.] Currently working on a secret mission outside the City. [He grins.] The commander intended it to be punishment for sabotaging the morale of the men. But he actually did me a great service. I needed to take some rest from the empire anyway. Now, can I do something for you or not?}
{550}{}{我是帝国第二团的肖恩·特拉克中尉。[他漫不经心地向你致敬]目前正在城外执行一项秘密任务。[他咧嘴笑了笑]指挥官打算用它来惩罚那些破坏士气的人。但他确实为我做了很大的贡献。无论如何，我需要从帝国那里休息一下。我能为你做点什么吗？}
#{551}{}{Secret mission? What is it?}
{551}{}{秘密任务？这是怎么一回事？}
#{552}{}{You could tell me about the Imperial City.}
{552}{}{你可以告诉我皇城的情况。}
#{553}{}{Nothing. Goodbye.}
{553}{}{没有什么。再见。}
#{600}{}{You want me to divulge top secret information to you? Actually, why not. [He laughs.] It doesn't matter anyway. I'm supposed to track down someone called the Anonym. According to my superiors, he's hiding somewhere in Albuquerque, trying to overthrow our emperor. And that's about all I know about him. As an imperial soldier, I've got no chance of finding out anything, so I've narrowed my responsibilities down to drinking away army funds. No one from the command has complained yet.}
{600}{}{你想让我泄露绝密信息给你？实际上，为什么不呢。[他笑了]反正没关系。我应该去找一个叫匿名者的人。据我的上级说，他躲在阿尔伯克基的某个地方，试图推翻我们的皇帝。这就是我对他的全部了解。作为一名帝国士兵，我没有任何发现的机会，所以我把责任缩小到耗尽军队资金。指挥部还没有人抱怨。}
#{601}{}{That could come back to haunt you. But tell me about the empire as well.}
{601}{}{可能会再次困扰你。但也跟我说说帝国。}
#{602}{}{Any idea if there's any work to be found in the empire?}
{602}{}{你知道帝国里有没有工作吗？}
#{603}{}{Got it. I'll be on my way now.}
{603}{}{知道了。我马上就来。}
#{650}{}{I expected you to ask that. They say a lot of nonsense about the empire. We're actually people like all the rest. The only difference between us is that our ancestors came from a vault. They lived there for a long time, cramped in small space, under constant supervision and completely dependent on technology. That changed them. And when they finally emerged to the surface, old habits remained. Then they passed them to us, and they still cling to us today. Nothing unusual, really. But even the empire is slowly losing it from the drawn-out isolation. That's why I'm so glad I got away from it.}
{650}{}{我以为你会问这个。他们说了很多关于帝国的废话。我们其实和其他人一样。我们之间唯一的区别是我们的祖先来自一个地下室。他们在那里住了很长一段时间，狭小的空间里，在不断的监督下，完全依赖技术。这改变了他们。当它们最终浮出水面时，旧习惯依然存在。然后他们把它们传给我们，直到今天它们仍然依附着我们。没什么不寻常的，真的。但即使是帝国也在慢慢地从长期的孤立中失去它。这就是为什么我很高兴我摆脱了它。}
#{651}{}{I'm also interested in your secret mission. What is it?}
{651}{}{我也对你的秘密任务感兴趣。这是怎么一回事？}
#{652}{}{Any idea if there's any work to be found in the empire?}
{652}{}{你知道帝国里有没有工作吗？}
#{653}{}{I see. See you later.}
{653}{}{我懂了。再见。}
#{700}{}{[He studies you for a moment.] The imperial dwellers usually hire foreigners only rarely, but today's your lucky day. [He grins.] I've heard that Adviser Elisa is currently looking for someone capable to run a few errands for her. She might give you the job. All you need to do is tell the guards at the gate that lieutenant Terrak sent you, then you'll be able to talk to Elisa directly. You'll find her in the great hall of the imperial palace.}
{700}{}{[他研究了你一会儿]帝国居民通常很少雇用外国人，但今天是你的幸运日。[他咧嘴一笑]我听说伊莉莎顾问正在找一个能帮她跑腿的人。她可能会给你这份工作。你要做的就是告诉门口的卫兵是泰拉克中尉派你来的，然后你就可以直接和伊莉莎说话了。你会在皇宫的大殿里找到她。}
#{701}{}{Thanks. I'm also interested in your secret mission. What is it?}
{701}{}{谢谢。我也对你的秘密任务感兴趣。这是怎么一回事？}
#{702}{}{Thanks. Tell me about the empire as well.}
{702}{}{谢谢。跟我说说帝国吧。}
#{703}{}{I owe you one. See you later.}
{703}{}{我欠你一个人情。再见。}
#{750}{}{[He sighs.] The city sure is going downhill. You should leave, tribal. There's nothing for your here.}
{750}{}{[他叹了口气]这座城市肯定要走下坡路了。你应该离开，部落。这里没有你的东西。}
#{751}{}{[He sighs.] The city sure is going downhill. You should leave, tribal. There's nothing for your here.}
{751}{}{[他叹了口气]这座城市肯定要走下坡路了。你应该离开，部落。这里没有你的东西。}
#{752}{}{Uh.}
{752}{}{休斯敦大学。}
#{800}{}{Greetings again, friend. What brings you to me this time?}
{800}{}{再次问候，朋友。这次是什么风把你吹来的？}
#{801}{}{Greetings again, miss. What brings you to me this time?}
{801}{}{再次问候，小姐。这次是什么风把你吹来的？}
#{802}{}{I'd like to know who you are.}
{802}{}{我想知道你是谁。}
#{803}{}{I'd like to know who you are.}
{803}{}{我想知道你是谁。}
#{804}{}{There's something important I have to tell you. Your superiors found out that you're ignoring their orders. They want to arrest you and make an example of you. A court-martial is already being prepared. You should get out of here as soon as possible.}
{804}{}{我有件重要的事要告诉你。你的上级发现你无视他们的命令。他们想逮捕你，以身作则。军事法庭已经准备好了。你应该尽快离开这里。}
#{805}{}{There's something important I have to tell you. Your bosses in the empire are pissed that you're not doing anything. They want to lock you up. You might want to disappear as soon as possible.}
{805}{}{我有件重要的事要告诉你。你在帝国的老板很生气你什么都没做。他们想把你关起来。你可能想尽快消失。}
#{806}{}{What was the secret mission you mentioned before?}
{806}{}{你之前提到的秘密任务是什么？}
#{807}{}{Tell me about the empire.}
{807}{}{告诉我帝国的事。}
#{808}{}{Any idea if there's any work to be found in the empire?}
{808}{}{你知道帝国里有没有工作吗？}
#{809}{}{What do you think about the new emperor?}
{809}{}{你觉得新皇帝怎么样？}
#{810}{}{A man in this establishment tried to offer me a job for the Anonym. Maybe he could help you with your search.}
{810}{}{这个机构里有个人想给我一份匿名的工作。也许他能帮你找。}
#{811}{}{You were right about the job for the empire. Elisa really did offer it to me. She also told me that it was originally your job.}
{811}{}{你对帝国工作的看法是对的。伊莉莎真的给了我。她还告诉我这本来是你的工作。}
#{812}{}{Nothing actually. Goodbye.}
{812}{}{实际上什么都没有。再见。}
#{813}{}{Uh.}
{813}{}{休斯敦大学。}
#{850}{}{[He scowls.] What the hell are you trying to pull here? You wouldn't scare even the dumbest private with that load of crap. If the army was about to court-martial me, I'd know it already. Have no doubt that I still have my sources in the empire. If you were trying to be funny, it didn't work. But you know what? I'm in a good mood right now. Buy us few drinks and I'll forget about the whole nonsense. Whaddaya say?}
{850}{}{[他皱着眉头.]你到底想拉什么？你连最笨的士兵都吓不到。如果军队要对我进行军事审判，我早就知道了。毫无疑问，我在帝国里还有我的消息来源。如果你想搞笑，那就没用了。但你知道吗？我现在心情很好。请我们喝几杯，我就忘了那些废话。你说什么？}
#{851}{}{[He scowls.] What the hell are you trying to pull here? You wouldn't scare even the dumbest private with that load of crap. If the army was about to court-martial me, I'd know it already. Have no doubt that I still have my sources in the empire. If you were trying to be funny, it didn't work. But you know what? I'm in a good mood right now. Buy us few drinks and I'll forget about the whole nonsense. Whaddaya say?}
{851}{}{[他皱着眉头.]你到底想拉什么？你连最笨的士兵都吓不到。如果军队要对我进行军事审判，我早就知道了。毫无疑问，我在帝国里还有我的消息来源。如果你想搞笑，那就没用了。但你知道吗？我现在心情很好。请我们喝几杯，我就忘了那些废话。你说什么？}
#{852}{}{I'm not against it. You might find what I said more reasonable after a few drinks. [Order the strongest drinks they offer in the Wild Paradise.]}
{852}{}{我不反对。喝了几杯后你可能会觉得我说的更合理。[点他们在野外天堂提供的烈性饮料。]}
#{853}{}{No way. I'm not buying you any booze.}
{853}{}{不可能。我不会给你买酒的。}
#{854}{}{Sorry, but I don't have enough caps for that.}
{854}{}{对不起，我没有足够的瓶盖。}
#{900}{}{Calm down, nobody is forcing you. Feel free to leave. If you change your mind, you know where to find me.}
{900}{}{冷静点，没人强迫你。请随意离开。如果你改变主意，你就知道在哪里能找到我。}
#{901}{}{Calm down, nobody is forcing you. Feel free to leave. If you change your mind, you know where to find me.}
{901}{}{冷静点，没人强迫你。请随意离开。如果你改变主意，你就知道在哪里能找到我。}
#{902}{}{Don't count on it. Goodbye.}
{902}{}{别指望了。再见。}
#{950}{}{Now that's bad. You know what, I'll just stay here while you try to get some caps. OK?}
{950}{}{现在这很糟糕。你知道吗，我就呆在这儿等你去拿瓶盖。好 啊？}
#{951}{}{OK.}
{951}{}{好 啊。}
#{1000}{}{[Terrak starts gulping down round after round without noticing that you didn't drink much at all. But the alcohol didn't seem to have much effect on him.] Well, friend? I hope you're not done yet.}
{1000}{}{[泰拉克开始一轮又一轮地大口大口地喝下去，却没有注意到你一点也不喝。但是酒精似乎对他没有多大影响？我希望你还没做完。}
#{1001}{}{[Terrak starts gulping down round after round without noticing that you didn't drink much at all. But the alcohol didn't seem to have much effect on him.] Well, miss? I hope you're not done yet.}
{1001}{}{[泰拉克开始一轮又一轮地大口大口地喝下去，却没有注意到你一点也不喝。但是酒精似乎对他没有多大影响？我希望你还没做完。}
#{1002}{}{That depends mostly on you, lieutenant. You were right - you're in no danger of being arrested yet. But how long will it last? You know the empire won't tolerate your idleness forever. You'll have to run away some day. So why not do it now?}
{1002}{}{那主要取决于你，中尉。你是对的-你还没有被逮捕的危险。但它能持续多久？你知道帝国不会永远容忍你的懒惰。总有一天你会逃跑的。那为什么现在不做呢？}
#{1003}{}{Listen, I'm sorry about lying to you. But you shouldn't forget that some dangers are real. What about the Anonym? Your mission makes you a prime target for his people. Is the empire really worth putting yourself at risk this way?}
{1003}{}{听着，我很抱歉对你撒谎。但你不应该忘记有些危险是真实存在的。匿名者呢？你的任务使你成为他手下的首要目标。帝国真的值得这样冒险吗？}
#{1004}{}{Listen, I'm sorry about lying to you. But you shouldn't forget that some dangers are real. What about the Anonym? Your mission makes you a prime target for his people. Is the empire really worth putting yourself at risk this way?}
{1004}{}{听着，我很抱歉对你撒谎。但你不应该忘记有些危险是真实存在的。匿名者呢？你的任务使你成为他手下的首要目标。帝国真的值得这样冒险吗？}
#{1005}{}{I... Sorry about the whole arrest crap. But don't you think that something like that is inevitable sooner or later? They're not going to let you slack off forever. You should disappear while there's still time.}
{1005}{}{一、 。。。很抱歉逮捕的事。但你不觉得这样的事情迟早是不可避免的吗？他们不会让你永远懈怠的。你应该趁着还有时间就消失。}
#{1006}{}{Listen, I'm sorry about lying to you. But there are some real dangers, too. What about the Anonym? You're a great target for his people now. You don't want to get shot over that emperor of yours, right?}
{1006}{}{听着，我很抱歉对你撒谎。但也有一些真正的危险。匿名者呢？你现在是他手下的大目标。你不想因为你的皇帝而中弹吧？}
#{1007}{}{Listen, I'm sorry about lying to you. But there are some real dangers, too. What about the Anonym? You're a great target for his people now. You don't want to get shot over that emperor of yours, right?}
{1007}{}{听着，我很抱歉对你撒谎。但也有一些真正的危险。匿名者呢？你现在是他手下的大目标。你不想因为你的皇帝而中弹吧？}
#{1050}{}{Nobody asked for your opinion. So stop being so pushy. And order one more round.}
{1050}{}{没有人征求你的意见。所以别再那么急于求成了。再来一轮。}
#{1051}{}{Do I have a choice? [Order more drinks.]}
{1051}{}{我有选择吗？[多点饮料。]}
#{1052}{}{Forget it. I'm not buying you anything else.}
{1052}{}{算了吧。我不会再给你买别的了。}
#{1053}{}{Sorry, but I don't have enough money anymore.}
{1053}{}{对不起，我没有足够的钱了。}
#{1100}{}{[Your arguments seem to finally convince Terrak. He gulps down a double shot of whiskey and throws the empty glass to the ground.] Damn, you're right. Living here is like sitting on a big ticking time bomb. No need to be around when it blows. Thanks for opening my eyes. I'll get out of this city right with the first caravan.}
{1100}{}{[你的论点似乎终于说服了泰瑞克。他大口喝了两杯威士忌，然后把空杯子扔到地上。住在这里就像坐在一颗定时炸弹上。风吹的时候不需要在附近。谢谢你睁开我的眼睛。我会带着第一辆大篷车离开这个城市。}
#{1101}{}{[Your arguments seem to finally convince Terrak. He gulps down a double shot of whiskey and throws the empty glass to the ground.] Damn, you're right. Living here is like sitting on a big ticking time bomb. No need to be around when it blows. Thanks for opening my eyes. I'll get out of this city right with the first caravan.}
{1101}{}{[你的论点似乎终于说服了泰瑞克。他大口喝了两杯威士忌，然后把空杯子扔到地上。住在这里就像坐在一颗定时炸弹上。风吹的时候不需要在附近。谢谢你睁开我的眼睛。我会带着第一辆大篷车离开这个城市。}
#{1102}{}{You've made the right choice. Good luck, Terrak.}
{1102}{}{你做了正确的选择。祝你好运，泰瑞克。}
#{1150}{}{[You drink another round of drinks. Terrak's probably drank the bigger share again, though you're not sure. The alcohol is starting to get to you, though Terrak still seems fine. That guy must be a seasoned drinker.] I'm sure you understand now why I spend so much time here. Nothing in the whole Albuquerque beats the Wild Paradise.}
{1150}{}{[你再喝一轮酒。Terrak可能又喝了一杯，尽管你不确定。酒精开始影响你了，尽管泰拉克看起来还不错。那家伙一定是个老练的酒鬼。）我相信你现在明白我为什么在这里花这么多时间了。整个阿尔伯克基没有什么能比得上野生天堂。}
#{1151}{}{[You drink another round of drinks. Terrak's probably drank the bigger share again, though you're not sure. The alcohol is starting to get to you, though Terrak still seems fine. That guy must be a seasoned drinker.] I'm sure you understand now why I spend so much time here. Nothing in the whole Albuquerque beats the Wild Paradise.}
{1151}{}{[你再喝一轮酒。Terrak可能又喝了一杯，尽管你不确定。酒精开始影响你了，尽管泰拉克看起来还不错。那家伙一定是个老练的酒鬼。）我相信你现在明白我为什么在这里花这么多时间了。整个阿尔伯克基没有什么能比得上野生天堂。}
#{1152}{}{Guess not. I wanted to talk to you about the whole arrest thing again. You're in no danger now, true, but don't you think it's just a matter of time? You know the empire won't tolerate your idleness forever. You'll have to run away some day. So why not do it now?}
{1152}{}{我猜不是。我想再跟你谈谈逮捕的事。你现在没有危险了，是的，但你不觉得这只是时间问题吗？你知道帝国不会永远容忍你的懒惰。总有一天你会逃跑的。那为什么现在不做呢？}
#{1153}{}{I guess not, but I wanted to talk to you about something else. Maybe you don't have to worry about being arrested, but there are other dangers. What about the Anonym? Your mission makes you a prime target for his people. Is the empire really worth putting yourself at risk this way?}
{1153}{}{我想不是，但我想和你谈谈别的事。也许你不必担心被逮捕，但还有其他危险。匿名者呢？你的任务使你成为他手下的首要目标。帝国真的值得这样冒险吗？}
#{1154}{}{I guess not, but I wanted to talk to you about something else. Maybe you don't have to worry about being arrested, but there are other dangers. What about the Anonym? Your mission makes you a prime target for his people. Is the empire really worth putting yourself at risk this way?}
{1154}{}{我想不是，但我想和你谈谈别的事。也许你不必担心被逮捕，但还有其他危险。匿名者呢？你的任务使你成为他手下的首要目标。帝国真的值得这样冒险吗？}
#{1155}{}{I guess not, but let's go back to you being arrested by the empire. Perhaps it won't happen now, but don't you think that something like that is inevitable sooner or later? They're not going to let you slack off forever. You should disappear while there's still time.}
{1155}{}{我想不是，但是让我们回到你被帝国逮捕的问题上。也许现在不会发生，但你不认为这样的事情迟早是不可避免的吗？他们不会让你永远懈怠的。你应该趁着还有时间就消失。}
#{1156}{}{I guess not, but there's something else I want to talk about. You may not be in danger of being arrested, but there are worse things than that. What about the Anonym? You're a great target for his people now. You don't want to get shot over that emperor of yours, right?}
{1156}{}{我想不是，但我还有别的事想谈。你可能没有被逮捕的危险，但还有比这更糟糕的事情。匿名者呢？你现在是他手下的大目标。你不想因为你的皇帝而中弹吧？}
#{1157}{}{I guess not, but there's something else I want to talk about. You may not be in danger of being arrested, but there are worse things than that. What about the Anonym? You're a great target for his people now. You don't want to get shot over that emperor of yours, right?}
{1157}{}{我想不是，但我还有别的事想谈。你可能没有被逮捕的危险，但还有比这更糟糕的事情。匿名者呢？你现在是他手下的大目标。你不想因为你的皇帝而中弹吧？}
#{1200}{}{You really are annoying. Just shut up already. And get some more alcohol.}
{1200}{}{你真烦人。已经闭嘴了。再喝点酒。}
#{1201}{}{You really are annoying. Just shut up already. And get some more alcohol.}
{1201}{}{你真烦人。已经闭嘴了。再喝点酒。}
#{1202}{}{This will ruin me. [Order more drinks again.]}
{1202}{}{这会毁了我的。[再来点饮料。]}
#{1203}{}{I've had enough. I'm not buying you anything else.}
{1203}{}{我受够了。我不会再给你买别的了。}
#{1204}{}{Sorry, but I don't have enough money anymore.}
{1204}{}{对不起，我没有足够的钱了。}
#{1250}{}{[You start to feel sick after the next round of drinks. You probably won't last much longer. Thankfully, the alcohol finally seems to be slowly affecting Terrak as well. He becomes chattier and chattier and starts to confide in you. He's in the exact state you want him to be.] Yeah, that's the life I always wanted. No orders, plenty of booze. The only thing that worries me is being called back to the empire. After all the time I spent here, I don't want to go back. I couldn't stand all those civilized losers and their bullshit rules. I just couldn't take it!}
{1250}{}{[你喝了下一轮酒后开始感到恶心。你可能撑不了多久了。谢天谢地，酒精最终似乎也慢慢影响了泰拉克。他变得越来越健谈，开始向你倾诉。他正处于你想要的状态。-是的，这就是我一直想要的生活。没有命令，有很多酒。唯一让我担心的是被召回帝国。在这里待了这么久，我不想回去了。我受不了那些文明的失败者和他们的胡说八道。我就是受不了！}
#{1251}{}{[You start to feel sick after the next round of drinks. You probably won't last much longer. Thankfully, the alcohol finally seems to be slowly affecting Terrak as well. He becomes chattier and chattier and starts to confide in you. He's in the exact state you want him to be.] Yeah, that's the life I always wanted. No orders, plenty of booze. The only thing that worries me is being called back to the empire. After all the time I spent here, I don't want to go back. I couldn't stand all those civilized losers and their bullshit rules. I just couldn't take it!}
{1251}{}{[你喝了下一轮酒后开始感到恶心。你可能撑不了多久了。谢天谢地，酒精最终似乎也慢慢影响了泰拉克。他变得越来越健谈，开始向你倾诉。他正处于你想要的状态。-是的，这就是我一直想要的生活。没有命令，有很多酒。唯一让我担心的是被召回帝国。在这里待了这么久，我不想回去了。我受不了那些文明的失败者和他们的胡说八道。我就是受不了！}
#{1252}{}{[Try to overcome drunkenness and make use of Terrak's exasperation.] Tell me... One thing. If you hate the imperial fuckers so much, why don't you just chuck 'em?! Just... Uff. Just flee from the city and they'll leave you alone forever. Why keep wasting time here?}
{1252}{}{[试着克服醉意，利用Terrak的愤怒]告诉我。。。有一件事。如果你这么恨帝国的混蛋，为什么不把他们扔了？！只是。。。不明飞行物。只要逃离城市，他们就会永远不理你。为什么一直在这里浪费时间？}
#{1300}{}{[Your arguments seem to finally convince Terrak. He gulps down a double shot of whiskey and throws the empty glass to the ground.] Damn, you're right. Both Myzrael and the empire can burn in hell for all I care. No need to be around when it happens. Thanks for opening my eyes. I'll get out of this city with the first caravan.}
{1300}{}{[你的论点似乎终于说服了泰瑞克。他大口喝了两杯威士忌，然后把空杯子扔到地上。迈兹雷尔和帝国都可以在地狱里燃烧。发生的时候不需要在身边。谢谢你睁开我的眼睛。我会带着第一辆大篷车离开这个城市。}
#{1301}{}{[Your arguments seem to finally convince Terrak. He gulps down a double shot of whiskey and throws the empty glass to the ground.] Damn, you're right. Both Myzrael and the empire can burn in hell for all I care. No need to be around when it happens. Thanks for opening my eyes. I'll get out of this city with the first caravan.}
{1301}{}{[你的论点似乎终于说服了泰瑞克。他大口喝了两杯威士忌，然后把空杯子扔到地上。迈兹雷尔和帝国都可以在地狱里燃烧。发生的时候不需要在身边。谢谢你睁开我的眼睛。我会带着第一辆大篷车离开这个城市。}
#{1302}{}{Yeah... Great! Farewell, lieutenant!}
{1302}{}{是 啊。。。太好了！再见，中尉！}
#{1350}{}{I couldn't be happier. Aran swamped the commander with work and I was completely forgotten in all that commotion. With some luck, I still have a long vacation ahead of me. I wouldn't have it any other way.}
{1350}{}{我再高兴不过了。阿兰让指挥官忙得不可开交，我在那一片混乱中完全被遗忘了。运气好的话，我还有一个长假。我没有别的办法。}
#{1351}{}{I couldn't be happier. Elisa swamped the commander with work and I was completely forgotten in all that commotion. With some luck, I still have a long vacation ahead of me. I wouldn't have it any other way.}
{1351}{}{我再高兴不过了。伊莉莎让指挥官忙得不可开交，我在混乱中完全被遗忘了。运气好的话，我还有一个长假。我没有别的办法。}
#{1352}{}{Good for you. Goodbye, Terrak.}
{1352}{}{真为你高兴。再见，泰瑞克。}
#{1400}{}{Well? Can we have a drink together now?}
{1400}{}{好？我们现在能一起喝一杯吗？}
#{1401}{}{Let's do it. [Order the strongest drinks available.]}
{1401}{}{我们开始吧。[点最烈的饮料。]}
#{1402}{}{Let's do it. [Order more drinks.]}
{1402}{}{我们开始吧。[多点饮料。]}
#{1403}{}{Hold on for a while longer.}
{1403}{}{再坚持一会儿。}
#{1404}{}{Uh.}
{1404}{}{休斯敦大学。}
#{1450}{}{Well? Did you decide to buy me a drink after all? You still owe me for all that crap you tried to pull on me.}
{1450}{}{好？你到底决定请我喝一杯吗？你还欠我你想对我说的那些废话。}
#{1451}{}{Well? Did you decide to buy me a drink after all? You still owe me for all that crap you tried to pull on me.}
{1451}{}{好？你到底决定请我喝一杯吗？你还欠我你想对我说的那些废话。}
#{1452}{}{That's why I'm here. [Order the strongest drinks available.]}
{1452}{}{所以我才在这里。[点最烈的饮料。]}
#{1453}{}{That's why I'm here. [Order more drinks.]}
{1453}{}{所以我才在这里。[多点饮料。]}
#{1454}{}{No way. Bye.}
{1454}{}{不可能。再见。}
#{1455}{}{Uh.}
{1455}{}{休斯敦大学。}
#{1500}{}{Yeah, sure. [He lazily waves his hand.] Don't worry about it. Some drunkard was just trying to impress you, nothing more. No reason to waste time on that.}
{1500}{}{是的，当然。[他懒洋洋地挥挥手]别担心。有个酒鬼只是想给你留下深刻印象，没别的。没有理由在这上面浪费时间。}
#{1501}{}{I guess that's a possibility. Goodbye, Terrak.}
{1501}{}{我想这是可能的。再见，泰瑞克。}
#{1550}{}{I hope you're not going to complain or something. You were looking for work and I was trying to get rid of it. Now we can both be happy. That's all there is to it.}
{1550}{}{我希望你不要抱怨什么的。你在找工作，而我却想摆脱它。现在我们都可以快乐了。就这些。}
#{1551}{}{I hope you're not going to complain or something. You were looking for work and I was trying to get rid of it. Now we can both be happy. That's all there is to it.}
{1551}{}{我希望你不要抱怨什么的。你在找工作，而我却想摆脱它。现在我们都可以快乐了。就这些。}
#{1552}{}{I guess you're right about that. I'll let it slide.}
{1552}{}{我想你是对的。我就顺其自然吧。}
