#{100}{}{You see a man.}
{100}{}{你看到一个男人。}
#{150}{}{You see Stan.}
{150}{}{你看到斯坦了。}
#{200}{}{You see a dirty man in tattered clothes.}
{200}{}{你看见一个衣衫褴褛的脏男人。}
#{250}{}{You see Stan. One could say he is the spokesman of the beggars that took over the shelter.}
{250}{}{你看到斯坦了。可以说，他是接管收容所的乞丐的代言人。}
#{300}{}{You made me let you in among us. But don't expect me to talk to you.}
{300}{}{你让我让你加入我们。但别指望我跟你说话。}
#{301}{}{You made me let you in among us. But don't expect me to talk to you.}
{301}{}{你让我让你加入我们。但别指望我跟你说话。}
#{500}{}{Hello. Take it easy, please. There's no need to be hostile. We're not looking for trouble.}
{500}{}{你好。请放轻松。没有必要怀有敌意。我们不是在找麻烦。}
#{501}{}{What? Who are you? What are you doing here?}
{501}{}{什么？你是谁？你在这里干什么？}
#{502}{}{Huh?}
{502}{}{嗯？}
#{550}{}{My name is Stan. Me and my friends have been living on the street for a long time... Perhaps even too long. People like us belong to the Dead Quarter, where it's not really easy to survive. But a few days ago, I accidentally discovered this place, this shelter. It's nothing special, everything is rotten and falling apart down here, but for us, it's a place where we can live in peace and safety.}
{550}{}{我叫斯坦。我和我的朋友在街上住了很长时间。。。也许太久了。像我们这样的人属于死亡区，在那里生存并不容易。但几天前，我意外地发现了这个地方，这个庇护所。这没什么特别的，这里的一切都腐烂了，四分五裂，但对我们来说，这是一个我们可以安居乐业的地方。}
#{551}{}{It was me who found the place and you only got in after I uncovered the entrance.}
{551}{}{是我找到了那个地方，我打开入口后你才进来。}
#{552}{}{It was me who found the place and you only got in after I uncovered the entrance.}
{552}{}{是我找到了那个地方，我打开入口后你才进来。}
#{553}{}{My hole! My!}
{553}{}{我的洞！我的天哪！}
#{600}{}{Please, do not take this amiss, but anyone could say that. If you are not lying, then I thank you, even though it may not have been your intention to help us. But I still have to ask you not to tell anyone about this place. I'm afraid there isn't enough room for more people down here.}
{600}{}{请不要生气，但任何人都可以这么说。如果你没有撒谎，那么我感谢你，尽管你可能无意帮助我们。但我还是得请你不要告诉任何人这个地方。恐怕这里没有足够的地方容纳更多的人。}
#{601}{}{Please, do not take this amiss, but anyone could say that. If you are not lying, then I thank you, even though it may not have been your intention to help us. But I still have to ask you not to tell anyone about this place. I'm afraid there isn't enough room for more people down here.}
{601}{}{请不要生气，但任何人都可以这么说。如果你没有撒谎，那么我感谢你，尽管你可能无意帮助我们。但我还是得请你不要告诉任何人这个地方。恐怕这里没有足够的地方容纳更多的人。}
#{602}{}{Let me get this straight. You took over the shelter, and you're planning to stay here?}
{602}{}{让我说清楚。你接管了庇护所，打算留在这里？}
#{603}{}{Maybe you didn't understand me. I found the shelter, it is mine so get lost!}
{603}{}{也许你不理解我。我找到了庇护所，它是我的，所以滚开！}
#{650}{}{I'm sorry you see it that way. This place is the only thing we have and we'll have to protect it, even if it costs us our lives. We have nothing to lose.}
{650}{}{很抱歉你这么看。这个地方是我们唯一拥有的东西，我们必须保护它，即使它让我们付出生命的代价。我们没有什么可失去的。}
#{651}{}{If you are willing to die for this hellhole, have it your way.}
{651}{}{如果你愿意为这个地狱而死，那就随你的便。}
#{652}{}{If you want to stay, I don't really care. But I want to get in.}
{652}{}{如果你想留下来，我不在乎。但我想进去。}
#{700}{}{I think we can find place for one more if you're interested. But everyone of us has to contribute somehow, be it only by something small. Give us 20 caps, I'm certain it won't be a problem for you, and we will accept you. You will have a place to stay here.}
{700}{}{如果你有兴趣的话，我想我们可以再找一个地方。但我们每个人都必须做出贡献，哪怕只是一些小事。给我们20个瓶盖，我肯定这对你不会有问题，我们会接受你的。你在这里会有地方住的。}
#{701}{}{Here you have the 20 caps.}
{701}{}{给你20个瓶盖。}
#{702}{}{How about I just kill you all?}
{702}{}{不如我把你们都杀了？}
#{703}{}{What if I told everyone in the Dead Quarter about this place?}
{703}{}{如果我把这个地方告诉死区的每个人呢？}
#{704}{}{Screw you, I'm out of here.}
{704}{}{去你的，我要走了。}
#{750}{}{Sure, you can try and I believe you may actually succeed. But we will still protect this place, even if it costs us our lives. We have nothing to lose, this shelter is the only thing we have.}
{750}{}{当然，你可以尝试，我相信你会成功的。但我们仍然会保护这个地方，即使这会让我们付出生命的代价。我们没有什么可失去的，只有这个避难所。}
#{751}{}{As you wish. Prepare to bite the dust.}
{751}{}{如你所愿。准备咬灰尘。}
#{752}{}{Very well, if you insist, here is 20 caps.}
{752}{}{很好，如果你坚持的话，这是20个瓶盖。}
#{753}{}{What if I told everyone in the Dead Quarter about this place?}
{753}{}{如果我把这个地方告诉死区的每个人呢？}
#{754}{}{Screw you, I'm out of here.}
{754}{}{去你的，我要走了。}
#{800}{}{You know just too well that sooner than later, someone would come and take it over by force and I have no way of stopping you from telling everyone about the shelter. But I implore you not to do it.}
{800}{}{你知道得太清楚了，迟早会有人来强行接管，我没办法阻止你告诉所有人避难所的事。但我恳求你不要这样做。}
#{801}{}{You know just too well that sooner than later, someone would come and take it over by force and I have no way of stopping you from telling everyone about the shelter. But I implore you not to do it.}
{801}{}{你知道得太清楚了，迟早会有人来强行接管，我没办法阻止你告诉所有人避难所的事。但我恳求你不要这样做。}
#{802}{}{You just have to let me in, I won't tell anyone.}
{802}{}{你只要让我进去，我不会告诉任何人。}
#{803}{}{No worries, I won't tell anyone. Here is the 20 caps, just as you wanted.}
{803}{}{别担心，我不会告诉任何人的。这是你想要的20顶瓶盖。}
#{804}{}{What if I just kill you all?}
{804}{}{如果我把你们都杀了呢？}
#{805}{}{Screw you, I'm out of here.}
{805}{}{去你的，我要走了。}
#{850}{}{Thank you and welcome. You can come here whenever you want and stay for as long as you want. We'll always be happy to see you here. You'll always have a bed here and a box to store your stuff. No one will dare touch your things, even when you're not around, that I guarantee. In case we manage to gather enough food, we'll leave a few pieces of meat in there for you. You never know when you might need them.}
{850}{}{谢谢，欢迎。你想什么时候来就什么时候来，想呆多久就呆多久。在这里见到你我们会很高兴的。你总是在这里有一张床和一个箱子来存放你的东西。没人敢碰你的东西，即使你不在，我保证。万一我们能弄到足够的食物，我们会在里面留几块肉给你。你永远不知道什么时候你可能需要它们。}
#{851}{}{Can I ask a few more questions about the Dead Quarter?}
{851}{}{我能再问几个关于死区的问题吗？}
#{852}{}{Thank you, Stan. Take care.}
{852}{}{谢谢你，斯坦。当心。}
#{853}{}{Hahaa.}
{853}{}{哈哈。}
#{900}{}{[He sighs.] Very well. You can come here whenever you want and stay for as long as you want. You'll always have a bed here and a box to store your stuff. No one'll dare touch your things, even when you're not around, that I guarantee. But don't expect any warm welcome in the light of your attitude.}
{900}{}{[他叹了口气]很好。你想什么时候来就什么时候来，想呆多久就呆多久。你总是在这里有一张床和一个箱子来存放你的东西。我保证，即使你不在，也没人敢碰你的东西。但别指望你的态度会受到热烈欢迎。}
#{901}{}{A bed and a stash is just what I need. Nothing more.}
{901}{}{一张床和一个储藏室正是我需要的。没别的了。}
#{950}{}{You... Why are you coming back? What do you want from us?}
{950}{}{你。。。你为什么回来？你想从我们这里得到什么？}
#{951}{}{I want to get in to the shelter.}
{951}{}{我想去避难所。}
#{952}{}{Nothing. I'm out of here.}
{952}{}{没有什么。我要走了。}
#{953}{}{Me holee!}
{953}{}{我是霍利！}
#{1000}{}{Hello, nice to see you again. I hope you're doing well.}
{1000}{}{你好，很高兴再次见到你。我希望你做得很好。}
#{1001}{}{Can I ask a few questions about the Dead Quarter?}
{1001}{}{我能问几个关于死区的问题吗？}
#{1002}{}{Stan, I would like to give you 20 more caps.}
{1002}{}{斯坦，我想再给你20顶瓶盖。}
#{1003}{}{Stan, I would like to give you 20 more caps.}
{1003}{}{斯坦，我想再给你20顶瓶盖。}
#{1004}{}{Take care, Stan.}
{1004}{}{保重，斯坦。}
#{1005}{}{Byee.}
{1005}{}{再见。}
#{1050}{}{Go ahead, I know the Dead Quarter very well. I've been living here a long time.}
{1050}{}{去吧，我很了解死区。我在这里住了很长时间。}
#{1051}{}{What can you tell me about the hospital?}
{1051}{}{你能告诉我医院的情况吗？}
#{1052}{}{What do you know about Pus' stand?}
{1052}{}{你对Pus'stand了解多少？}
#{1053}{}{Have you heard the stories of Anonym hiding in the Quarter while the Empire is looking for him?}
{1053}{}{你听说过帝国在找匿名者的时候，他躲在这个地方的故事吗？}
#{1054}{}{Never mind, I don't want to bother you.}
{1054}{}{没关系，我不想打扰你。}
#{1100}{}{Us people of the street like to avoid the hospital, there are strange stories about that place going around. Or I should say about the people who had gone there to find help, to beg, or to score some drugs. No one saw them ever again.}
{1100}{}{我们街上的人喜欢避开医院，那里到处都是奇怪的故事。或者我应该说那些去那里寻求帮助、乞讨或吸毒的人。再也没有人见过他们了。}
#{1101}{}{What do you know about Pus' stand?}
{1101}{}{你对Pus'stand了解多少？}
#{1102}{}{Have you heard the stories of Anonym hiding in the Quarter while the Empire is looking for him?}
{1102}{}{你听说过帝国在找匿名者的时候，他躲在这个地方的故事吗？}
#{1103}{}{Thanks, that's all I need.}
{1103}{}{谢谢，这就是我所需要的。}
#{1150}{}{We go buy food from him when we collect enough caps. It's not very tasty, but it scares hunger away for a while and it is cheap.}
{1150}{}{当我们收集到足够的瓶盖时，我们就去给他买食物。它不太好吃，但它能暂时把饥饿吓跑，而且很便宜。}
#{1151}{}{What can you tell me about the hospital?}
{1151}{}{你能告诉我医院的情况吗？}
#{1152}{}{Have you heard the stories of Anonym hiding in the Quarter while the Empire is looking for him?}
{1152}{}{你听说过帝国在找匿名者的时候，他躲在这个地方的故事吗？}
#{1153}{}{Thanks, that's all I need.}
{1153}{}{谢谢，这就是我所需要的。}
#{1200}{}{Yeah, I heard about it but I know nothing. There are all sorts of business conducted in the Dead Quarter but when a person like me intends to survive here, they have to learn how to not notice these things, for their own good. This quarter is ideal if you want to get lost.}
{1200}{}{是的，我听说了，但我什么都不知道。在死角有各种各样的生意，但当我这样的人打算在这里生存时，他们必须学会如何不去注意这些事情，为了他们自己的利益。如果你想迷路，这个季度是理想的。}
#{1201}{}{What can you tell me about the hospital?}
{1201}{}{你能告诉我医院的情况吗？}
#{1202}{}{What do you know about Pus' stand?}
{1202}{}{你对Pus'stand了解多少？}
#{1203}{}{Thanks, that's all I need.}
{1203}{}{谢谢，这就是我所需要的。}
#{1250}{}{Gee, you know you don't have to do it. You already paid your share.}
{1250}{}{天哪，你知道你不必这么做。你已经付了你的那份了。}
#{1251}{}{Gee, you know you don't have to do it. You already paid your share.}
{1251}{}{天哪，你知道你不必这么做。你已经付了你的那份了。}
#{1252}{}{I would like to contribute anyway.}
{1252}{}{不管怎样，我还是愿意贡献。}
#{1253}{}{OK, I'm sorry. I see you don't feel too good about accepting any more caps from me.}
{1253}{}{好吧，对不起。我看你不太愿意再接受我的瓶盖了。}
#{1300}{}{Oh, thank you, then. For all of them.}
{1300}{}{哦，谢谢你。为了他们所有人。}
#{1301}{}{Don't mention it.}
{1301}{}{不用谢。}
#{1350}{}{Ehm... sorry, but we discovered the shelter ourselves, we were the first here. However, we could still find a place for one more down here. We don't judge anyone. But all of us had to contribute a little something to be able to stay here. Give me 20 caps and we will welcome you among us, you will be able to stay here.}
{1350}{}{嗯。。。对不起，我们自己发现了避难所，我们是第一个来的。不过，我们还是可以在这里再找一个地方。我们不评判任何人。但我们所有人都必须贡献一点东西才能留在这里。给我20顶瓶盖，我们欢迎你加入我们，你就可以留在这里了。}
#{1351}{}{Okaaay. Take.}
{1351}{}{好的。拿着。}
#{1352}{}{Naah! Make you dead, make all dead!}
{1352}{}{啊！让你死，让所有人都死！}
#{1353}{}{Uh... Bye.}
{1353}{}{休斯敦大学。。。再见。}
