#{300}{}{You cannot use the computer in combat.}
{300}{}{你不能在战斗中使用电脑。}
#{500}{}{[Someone left a film running on the computer, but the recording is stuck. The monitors show a one-second loop that is not very useful to you.]}
{500}{}{[有人在电脑上放了一部电影，但录音被卡住了。监视器显示一秒钟的循环，这对您不是很有用。]}
#{501}{}{[Try to make the computer work with a well-aimed blow.]}
{501}{}{[试着用一个有针对性的打击使计算机工作。]}
#{502}{}{[Hit the machine hard.]}
{502}{}{[用力打机器。]}
#{550}{}{[After your blow, the screen turned off and back on, flashed a few times and then suddenly restored to the film running.]}
{550}{}{[在你的打击之后，屏幕关闭并重新打开，闪烁了几次，然后突然恢复到电影运行状态。]}
#{551}{}{Ayyy!}
{551}{}{哎呀！}
#{600}{}{Mr. Handy vacuums. [The screen says in large letters and shows a scene with a robot driving around the room with a vacuum cleaner. He even effortlessly lifts heavy furniture to clean under it.]}
{600}{}{汉迪先生用吸尘器。[屏幕上用大字写着，显示了一个机器人拿着吸尘器在房间里转来转去的场景。他甚至不费吹灰之力地举起沉重的家具在下面打扫}
#{601}{}{[Continue watching.]}
{601}{}{[继续观察。]}
#{650}{}{Mr. Handy cooks and bakes. [The robot is pulling a delicious looking pastry on one pan, and a crispy turkey on another out of the oven.]}
{650}{}{汉迪先生做饭和烤肉。[机器人正在把一个看起来很好吃的糕点放在一个平底锅上，把一个酥脆的火鸡放在另一个平底锅上从烤箱里拿出来。]}
#{651}{}{[Continue watching.]}
{651}{}{[继续观察。]}
#{700}{}{Mr. Handy irons. [In the scene, the robot is a wizard with the flat-iron.]}
{700}{}{汉迪·艾恩斯先生。[在场景中，机器人是一个拿着熨斗的巫师。]}
#{701}{}{[Continue watching.]}
{701}{}{[继续观察。]}
#{750}{}{Mr. Handy walks your dog. [The robot is walking on the sidewalk with a small dog pacing calmly in front of it. After the puppy does her business on the lawn, Mr. Handy picks the... business... up and places it neatly in a bag.]}
{750}{}{汉迪先生帮你遛狗。[机器人在人行道上行走，一只小狗在它前面平静地踱步。小狗在草坪上做生意后，汉迪先生挑选。。。业务。。。把它整齐地放在一个袋子里。]}
#{751}{}{[Continue watching.]}
{751}{}{[继续观察。]}
#{800}{}{Mr. Handy cuts your lawn. [The robot is pushing a lawnmower in front of it and at racing speed, cuts its way through an overgrown yard, leaving a perfect, even lawn in its wake.]}
{800}{}{汉迪先生修剪你的草坪。[机器人正推着前面的割草机，以极快的速度穿过一个杂草丛生的院子，留下一片完美、平整的草坪。]}
#{801}{}{[Continue watching.]}
{801}{}{[继续观察。]}
#{850}{}{Mr. Handy protects your home from communist aggressors. [Two gruesomely disfigured Chinese soldiers are kneeling in horror in front of the robot's arms raised in warning.]}
{850}{}{汉迪先生保护你的家不受共产主义侵略者的侵扰。[两名丑陋的中国士兵惊恐地跪在机器人手臂前以示警告。]}
#{851}{}{[Continue watching.]}
{851}{}{[继续观察。]}
#{900}{}{[The film goes on to show the robot with numerous compartments designed to store just about anything one can find in a household, and finishes with large letters across the screen.] Mr. Handy. He's so handy! [For a few seconds the writing remains lit up on the screen, followed by sparks and smoke puffing out of the cooling fan, whereupon the computer goes dark.]}
{900}{}{[影片接着展示了这个机器人，它有许多隔间，设计用来存放人们在家里能找到的任何东西，最后用屏幕上的大字来结束。]汉迪先生。他真手巧！[几秒钟后，屏幕上的文字一直亮着，接着冷却风扇冒出火花和烟雾，电脑随即变暗。]}
#{901}{}{Damn, I have no idea what that was all about but I feel a strong desire to own one of those Mr. Handys. That makes no sense, what would I need it for... ?}
{901}{}{妈的，我不知道这是怎么回事，但我有强烈的愿望拥有一个汉迪先生。没道理，我需要它做什么？}
#{902}{}{Handeey!}
{902}{}{汉迪！}
#{950}{}{The stench of burned circuit boards is a clear signal that the computer does not work.}
{950}{}{烧焦的电路板发出的恶臭是电脑无法工作的明显信号。}
