#{100}{}{You see a gang member.}
{100}{}{你看到一个帮派成员。}
#{101}{}{You see a gang member.}
{101}{}{你看到一个帮派成员。}
#{200}{}{You see a man from the local gang.}
{200}{}{你看到一个当地帮派的人。}
#{201}{}{You see a woman from the local gang.}
{201}{}{你看到一个当地黑帮的女人。}
#{300}{}{Asshole!}
{300}{}{混蛋！}
#{301}{}{Go to hell.}
{301}{}{去死吧。}
#{302}{}{Vex won't go easy on you.}
{302}{}{烦恼对你不会轻易的。}
#{303}{}{You better watch the fuck out.}
{303}{}{你最好小心点。}
#{304}{}{Vex is the boss here, no matter what anyone tells themselves.}
{304}{}{不管别人怎么说，维克斯都是这里的老板。}
#{305}{}{Stop trying to piss me off.}
{305}{}{别想惹我生气。}
#{306}{}{You wanna die here?}
{306}{}{你想死在这里？}
#{307}{}{You better get lost, Vex is in charge here.}
{307}{}{你最好滚开，这里是维克斯负责的。}
#{308}{}{Am I supposed to give a fuck?}
{308}{}{我是不是该去死？}
#{309}{}{Stop bothering me, you piece of shit.}
{309}{}{别再烦我了，你这个混蛋。}
#{310}{}{Vex isn't afraid of the Hunters.}
{310}{}{维克斯不怕猎人。}
#{311}{}{Whore!}
{311}{}{妓女！}
#{312}{}{You're not another damn immigrant, are you?}
{312}{}{你不是另一个该死的移民，是吗？}
#{313}{}{Kiss my ass.}
{313}{}{亲我的屁股。}
#{314}{}{Get lost, we don't have any mutants here.}
{314}{}{滚开，我们这里没有变种人。}
#{315}{}{The air sure tastes better without those dumbass savages around.}
{315}{}{没有那些愚蠢的野蛮人在身边，空气真是好极了。}
#{316}{}{Hehe, William must've shit his pants.}
{316}{}{呵呵，威廉一定是尿裤子了。}
#{317}{}{Fuck the Hunters.}
{317}{}{去他妈的猎人。}
#{318}{}{We're filthy rich! Hell yeah!}
{318}{}{我们太有钱了！见鬼，耶！}
#{319}{}{Go back to your retard friends.}
{319}{}{回到你的弱智朋友那里去。}
#{320}{}{You smell like the tribals, it's sickening.}
{320}{}{你闻起来像部落的味道，真恶心。}
#{321}{}{Hey man, careful with that beastie.}
{321}{}{嘿，伙计，小心那只野兽。}
#{322}{}{Shit, that's disgusting! You and the filthy animal both.}
{322}{}{妈的，真恶心！你和那肮脏的动物。}
#{323}{}{Hey girl, careful with that beastie.}
{323}{}{嘿，姑娘，小心那只野兽。}
#{330}{}{Get the hell outta there.}
{330}{}{滚出去。}
#{331}{}{Fuck off.}
{331}{}{滚开。}
#{332}{}{Don't try anything, asshole.}
{332}{}{什么都别想，混蛋。}
#{333}{}{Should I tear off your arms?}
{333}{}{我应该把你的胳膊撕下来吗？}
#{334}{}{I guess it's OK. You can go downstairs.}
{334}{}{我想没关系。你可以下楼去。}
#{350}{}{It was a fucking bad idea to come here!}
{350}{}{来这儿真是个糟糕的主意！}
#{351}{}{You don't belong here. I'd remember a moron like you.}
{351}{}{你不属于这里。我记得像你这样的白痴。}
#{352}{}{You don't belong here. I'd remember a bitch like you.}
{352}{}{你不属于这里。我记得像你这样的婊子。}
#{353}{}{You don't belong here. I'd remember a moron like you.}
{353}{}{你不属于这里。我记得像你这样的白痴。}
#{354}{}{You don't belong here. I'd remember a bitch like you.}
{354}{}{你不属于这里。我记得像你这样的婊子。}
#{355}{}{We got a dumbass over here!}
{355}{}{我们这里有个笨蛋！}
#{356}{}{You came to steal to the wrong fucking place!}
{356}{}{你来偷错地方了！}
#{357}{}{You came to steal to the wrong fucking place!}
{357}{}{你来偷错地方了！}
