#{100}{}{You see an old man.}
{100}{}{你看到一个老人。}
#{150}{}{You see William.}
{150}{}{你看到威廉了。}
#{200}{}{You see an elderly man with a??penetrating gaze.}
{200}{}{你看到一位目光敏锐的老人。}
#{250}{}{You see William, the local rich man.}
{250}{}{你看威廉，当地的富人。}
#{300}{}{Go away.}
{300}{}{走开。}
#{301}{}{I don't need anything. Leave.}
{301}{}{我什么都不需要。离开。}
#{302}{}{I'm not going to talk to you in this state. Leave.}
{302}{}{在这种情况下我不会和你说话的。离开。}
#{350}{}{Please, be respectful in here and leave my personal belongings alone.}
{350}{}{请尊重我，不要乱动我的私人物品。}
#{400}{}{You'll regret this. Guards!}
{400}{}{你会后悔的。警卫！}
#{500}{}{[The old man gives you a quizzical look.] I don't believe I have seen you before. And I know almost everyone round here. Who are you? Speak up!}
{500}{}{[老人疑惑地看了你一眼]我想我以前没见过你。我几乎认识这里的每一个人。你是谁？说话！}
#{501}{}{My name is }
{501}{}{我的名字是}
#{502}{}{. I haven't been too long in the city.}
{502}{}{. 我在城里待的时间不长。}
#{503}{}{No one of importance.}
{503}{}{没有重要人物。}
#{504}{}{That's none of your business.}
{504}{}{那不关你的事。}
#{505}{}{Haargh?!}
{505}{}{哈？！}
#{550}{}{I'm William. I suppose you heard of me before. The other immigrants tend to see me as their leader. But that has never been my intention. Let's just say that I have certain power here and I'm the only one with enough bottle caps able to keep some sort of peace in the area. [He makes a dramatic pause.] Tell me, what is it that you want from me.}
{550}{}{我是威廉。我想你以前听说过我吧。其他移民倾向于把我当作他们的领袖。但这不是我的本意。就说我在这里有一定的权力，我是唯一一个有足够瓶盖的人，能够在这个地区保持某种和平。[他戏剧性地停顿了一下]告诉我，你想从我这里得到什么。}
#{551}{}{I'm William. I suppose you heard of me before. The other immigrants tend to see me as their leader. But that has never been my intention. Let's just say that I have certain power here and I'm the only one with enough bottle caps able to keep some sort of peace in the area. [He makes a dramatic pause.] Tell me, what is it that you want from me.}
{551}{}{我是威廉。我想你以前听说过我吧。其他移民倾向于把我当作他们的领袖。但这不是我的本意。就说我在这里有一定的权力，我是唯一一个有足够瓶盖的人，能够在这个地区保持某种和平。[他戏剧性地停顿了一下]告诉我，你想从我这里得到什么。}
#{552}{}{I only have a couple of questions. I'd like to know more about your community.}
{552}{}{我只有几个问题。我想更多地了解你们的社区。}
#{553}{}{I only have a couple of questions. I'd like to know more about your community.}
{553}{}{我只有几个问题。我想更多地了解你们的社区。}
#{554}{}{Alvarez told me you were looking for someone to get some work done for you. What is it?}
{554}{}{阿尔瓦雷斯告诉我你在找人帮你完成一些工作。这是怎么一回事？}
#{555}{}{It's nothing. Goodbye William.}
{555}{}{没什么。再见，威廉。}
#{556}{}{Someone like you could have work for me.}
{556}{}{像你这样的人可以为我工作。}
#{600}{}{Very well, I'm William. I suppose you heard of me before. The other immigrants tend to see me as their leader. But that has never been my intention. Let's just say that I have certain power here and I'm the only one with enough bottle caps who is able to keep some sort of peace in the area. [He makes a dramatic pause.] Tell me, what is it that you want from me.}
{600}{}{很好，我是威廉。我想你以前听说过我吧。其他移民倾向于把我当作他们的领袖。但这不是我的本意。就说我在这里有一定的权力，我是唯一一个有足够的瓶盖，能够在这个地区保持某种和平的人。[他戏剧性地停顿了一下]告诉我，你想从我这里得到什么。}
#{601}{}{Very well, I'm William. I suppose you heard of me before. The other immigrants tend to see me as their leader. But that has never been my intention. Let's just say that I have certain power here and I'm the only one with enough bottle caps who is able to keep some sort of peace in the area. [He makes a dramatic pause.] Tell me, what is it that you want from me.}
{601}{}{很好，我是威廉。我想你以前听说过我吧。其他移民倾向于把我当作他们的领袖。但这不是我的本意。就说我在这里有一定的权力，我是唯一一个有足够的瓶盖，能够在这个地区保持某种和平的人。[他戏剧性地停顿了一下]告诉我，你想从我这里得到什么。}
#{602}{}{I only have a couple of questions. I'd like to know more about your community.}
{602}{}{我只有几个问题。我想更多地了解你们的社区。}
#{603}{}{Alvarez told me you were looking for someone to get some work done for you. What is it?}
{603}{}{阿尔瓦雷斯告诉我你在找人帮你完成一些工作。这是怎么一回事？}
#{604}{}{It's nothing. Goodbye William.}
{604}{}{没什么。再见，威廉。}
#{605}{}{Someone like you could have work for me.}
{605}{}{像你这样的人可以为我工作。}
#{650}{}{Go on. I just hope it won't take too long.}
{650}{}{继续。我只是希望不要花太长时间。}
#{651}{}{How did you get here?}
{651}{}{你怎么来的？}
#{652}{}{What do you do here for a living?}
{652}{}{你在这里做什么工作？}
#{653}{}{How do you get along with the others?}
{653}{}{你和其他人相处得怎么样？}
#{654}{}{Actually, I have to go now. Goodbye.}
{654}{}{实际上，我得走了。再见。}
#{700}{}{All immigrants got to Albuquerque the same way. Ghouls destroyed their homes and they decided to seek refuge in the only somewhat safe place that remains. I myself come from Los Alamos. As a merchant, I was lucky enough to flee with some goods. There is a lot of people from that city here. Many also came from Duluth. That was the very first larger metropolis those rotten ghouls were able to take down.}
{700}{}{所有移民到阿尔伯克基的方式都一样。僵尸摧毁了他们的家园，他们决定在仅存的安全地方寻求庇护。我自己来自洛斯阿拉莫斯。作为一个商人，我很幸运带着一些货物逃走了。这里有很多从那个城市来的人。许多人也来自德卢斯。那是那些腐烂的僵尸能够摧毁的第一个更大的大都市。}
#{701}{}{Oh. I have another question.}
{701}{}{哦。我还有一个问题。}
#{702}{}{I'll have to be going now. Goodbye.}
{702}{}{我得走了。再见。}
#{750}{}{Most immigrants must take what they can get. They unload goods from caravans, they process gecko skins or try to look for valuables among the ruins. It's a tough life.}
{750}{}{大多数移民必须尽其所能。他们从大篷车上卸货，加工壁虎皮，或者在废墟中寻找贵重物品。生活很艰难。}
#{751}{}{I understand. I have another question.}
{751}{}{我理解。我还有一个问题。}
#{752}{}{I'll have to be going now. Goodbye.}
{752}{}{我得走了。再见。}
#{800}{}{We try to stay as far back as possible from other inhabitants of Albuquerque. They are all just a bunch of cut-throats. Mutant Hunters kill off anyone with even the slightest sign of mutation and not one day goes by that those murderers from Vex's gang would not beat to death some immigrant. What one can expect from the tribe of savages camping at the gate I don't even want to guess. That long wall may protect us from the ghouls outside, but we have to deal with the rest ourselves. It is not easy by any means.}
{800}{}{我们尽量远离阿尔伯克基的其他居民。他们都只是一群割喉者。变种猎人会杀死任何有一点点变异迹象的人，而且没有一天那些来自维克斯帮派的杀人犯不会打死某个移民。在大门口露营的野人部落能给我们带来什么我都不想猜。那堵长墙也许能保护我们不受外面僵尸的伤害，但我们必须自己处理剩下的事情。无论如何，这并不容易。}
#{801}{}{We try to stay as far back as possible from other inhabitants of Albuquerque. They are all just a bunch of cut-throats. Mutant Hunters ... well, you know best what y'all are up to. I just hope those mutants are a real threat to us. [He pauses for a moment.] The worst are those murderers from Vex's gang. Not one day goes by that they would not beat to death some immigrant. What one can expect from the tribe of savages camping at the gate I don't even want to guess. That long wall may protect us from the ghouls outside, but we have to deal with the rest ourselves. It is not easy by any means.}
{801}{}{我们尽量远离阿尔伯克基的其他居民。他们都只是一群割喉者。变种猎人。。。好吧，你们最清楚你们在干什么。我只希望那些变种人对我们是真正的威胁。[他停顿了一下]最糟糕的是维克斯帮派的那些杀人犯。他们没有一天不打死某个移民。在大门口露营的野人部落能给我们带来什么我都不想猜。那堵长墙也许能保护我们不受外面僵尸的伤害，但我们必须自己处理剩下的事情。无论如何，这并不容易。}
#{802}{}{We try to stay as far back as possible from other inhabitants of Albuquerque. They are all just a bunch of cut-throats. Mutant Hunters ... well, you know best what y'all are up to. I just hope those mutants are a real threat to us. [He pauses for a moment.] The worst are those murderers from Vex's gang. Not one day goes by that they would not beat to death some immigrant. What one can expect from the tribe of savages camping at the gate I don't even want to guess. That long wall may protect us from the ghouls outside, but we have to deal with the rest ourselves. It is not easy by any means.}
{802}{}{我们尽量远离阿尔伯克基的其他居民。他们都只是一群割喉者。变种猎人。。。好吧，你们最清楚你们在干什么。我只希望那些变种人对我们是真正的威胁。[他停顿了一下]最糟糕的是维克斯帮派的那些杀人犯。他们没有一天不打死某个移民。在大门口露营的野人部落能给我们带来什么我都不想猜。那堵长墙也许能保护我们不受外面僵尸的伤害，但我们必须自己处理剩下的事情。无论如何，这并不容易。}
#{803}{}{I understand. I have another question.}
{803}{}{我理解。我还有一个问题。}
#{804}{}{I'll have to be going now. Goodbye.}
{804}{}{我得走了。再见。}
#{850}{}{Yes, he was correct. It's a rather unpleasant thing. I need to have the boss of the local gang removed. His name is Vex. His gang's been causing me nothing but trouble for quite some time now, and lately they seem to have lost all restrains. They've started to interfere with my business and that must end. The only way to resolve the situation's to have Vex dead. Without his command, the gang will certainly fall apart before long. I'm looking for someone who could make it happen.}
{850}{}{是的，他是对的。这是一件相当不愉快的事。我要把当地帮派的头目除掉。他的名字叫维克斯。他的帮派给我带来的麻烦已经有一段时间了，最近他们似乎已经失去了所有的约束。他们已经开始干涉我的生意，这必须结束。解决问题的唯一办法就是让维克斯死。如果没有他的指挥，这个团伙不久就会瓦解。我在找一个能成功的人。}
#{851}{}{If the price is right, I could take care of that.}
{851}{}{如果价格合适的话，我可以处理。}
#{852}{}{I hope you find someone. Goodbye, William.}
{852}{}{我希望你能找到人。再见，威廉。}
#{900}{}{I tend to pay more than well, don't you worry about that. I don't care how you do it, but I have one condition. You must bring me his head.}
{900}{}{我付的钱往往不止这些，你不用担心。我不管你怎么做，但我有一个条件。你必须把他的头给我。}
#{901}{}{Eh, what do you need that for?}
{901}{}{呃，你要这个干什么？}
#{950}{}{As you wish. If you change your mind, my offer still stands.}
{950}{}{如你所愿。如果你改变主意，我的提议仍然有效。}
#{951}{}{As you wish. If you change your mind, my offer still stands.}
{951}{}{如你所愿。如果你改变主意，我的提议仍然有效。}
#{952}{}{I doubt that. Goodbye, William.}
{952}{}{我对此表示怀疑。再见，威廉。}
#{1000}{}{I want to know who you are. So get talking!}
{1000}{}{我想知道你是谁。所以说吧！}
#{1001}{}{Ugh... I }
{1001}{}{呃。。。我}
#{1002}{}{. No long here.}
{1002}{}{. 不在这里了。}
#{1003}{}{You bad... Bam!}
{1003}{}{你太坏了。。。砰！}
#{1050}{}{Before you go, there is one thing you should know. You can come by any time, but for you own sake, keep away from the first floor. My two wives, Doreen and Penny, live there and I really don't like it when someone bothers them. I hope you catch my drift.}
{1050}{}{在你走之前，有一件事你应该知道。你什么时候都可以来，但为了你自己的缘故，离一楼远点。我的两个妻子，多琳和佩妮，住在那里，我真的不喜欢有人打扰他们。我希望你明白我的意思。}
#{1051}{}{Before you go, there is one thing you should know. You can come by any time, but for you own sake, keep away from the first floor. My two wives, Doreen and Penny, live there and I really don't like it when someone bothers them. I hope you catch my drift.}
{1051}{}{在你走之前，有一件事你应该知道。你什么时候都可以来，但为了你自己的缘故，离一楼远点。我的两个妻子，多琳和佩妮，住在那里，我真的不喜欢有人打扰他们。我希望你明白我的意思。}
#{1052}{}{Sure, see you.}
{1052}{}{当然，再见。}
#{1053}{}{You have two wives? How is that working out for you?}
{1053}{}{你有两个妻子？你觉得怎么样？}
#{1100}{}{[He frowns.] That is something you needn't worry about. Goodbye.}
{1100}{}{[他皱眉]这是你不必担心的事。再见。}
#{1101}{}{If you say so.}
{1101}{}{如果你这样说。}
#{1102}{}{That wasn't really helpful. I guess I will have to find out for myself.}
{1102}{}{那没什么用。我想我得自己去弄清楚。}
#{1103}{}{That wasn't really helpful. I guess I will have to find out for myself.}
{1103}{}{那没什么用。我想我得自己去弄清楚。}
#{1150}{}{Go ahead, ask your questions.}
{1150}{}{去吧，问你的问题。}
#{1151}{}{How did you get here?}
{1151}{}{你怎么来的？}
#{1152}{}{What do you do here for a living?}
{1152}{}{你在这里做什么工作？}
#{1153}{}{How do you get along with the others?}
{1153}{}{你和其他人相处得怎么样？}
#{1154}{}{Actually, I have to go now. Goodbye.}
{1154}{}{实际上，我得走了。再见。}
#{1200}{}{I strongly advise against such tone of voice, you have no right to address me like that, not in my own house. Go on, who the hell are you?}
{1200}{}{我强烈建议不要用这种语气说话，你无权这样称呼我，不能在我自己家里。去吧，你到底是谁？}
#{1201}{}{Sorry, my name is }
{1201}{}{对不起，我的名字是}
#{1202}{}{. I haven't been too long in the city.}
{1202}{}{. 我在城里待的时间不长。}
#{1203}{}{For a balding oldtimer, you sure have some big balls. I may have to end your suffering a little prematurely.}
{1203}{}{对于一个秃顶的老家伙来说，你确实有一些大球。我可能不得不过早地结束你的痛苦。}
#{1250}{}{What do you want this time?}
{1250}{}{这次你想要什么？}
#{1251}{}{I have some questions. I'd like to know more about your community.}
{1251}{}{我有一些问题。我想更多地了解你们的社区。}
#{1252}{}{I have some questions. I'd like to know more about your community.}
{1252}{}{我有一些问题。我想更多地了解你们的社区。}
#{1253}{}{Alvarez told me you were looking for someone to get some work done for you. What is it?}
{1253}{}{阿尔瓦雷斯告诉我你在找人帮你完成一些工作。这是怎么一回事？}
#{1254}{}{Vex is dead. [Give him his head.]}
{1254}{}{维克斯死了。[把他的头给他。]}
#{1255}{}{Vex dead. [Give him his head.]}
{1255}{}{烦恼死了。[把他的头给他。]}
#{1256}{}{I changed my mind, I'll take care of Vex. I'll get back with his head.}
{1256}{}{我改变主意了，我会照顾维克斯的。我去拿他的头回来。}
#{1257}{}{I changed my mind, I'll take care of Vex. I'll get back with his head.}
{1257}{}{我改变主意了，我会照顾维克斯的。我去拿他的头回来。}
#{1258}{}{The local tribe has been attacked by a band of raiders. It seems that they are from Albuquerque. Do you by any chance know who they could be?}
{1258}{}{当地部落遭到一群袭击者的袭击。他们好像是从阿尔伯克基来的。你知道他们可能是谁吗？}
#{1259}{}{The tribe is planning an attack on the doctors from the hospital. They want to take revenge for the raids on their hunters. Do you think your people could support them?}
{1259}{}{这个部落正计划袭击医院的医生。他们想为突袭猎人报仇。你认为你的人民能支持他们吗？}
#{1260}{}{Absolutely nothing. Goodbye, William.}
{1260}{}{完全没有。再见，威廉。}
#{1261}{}{Ugh, nuting.}
{1261}{}{呃，发疯了。}
#{1262}{}{Someone like you could have work for me.}
{1262}{}{像你这样的人可以为我工作。}
#{1300}{}{I have absolutely no idea. I have always tried to get involved with the savages as little as possible. I have the same advice for you. For what it's worth, you can be absolutely sure that no one from the Suburbs has anything to do with this. If not anything else, the tribe has always been good for trade. Their gecko skins bring good revenue.}
{1300}{}{我完全不知道。我总是尽量少和野蛮人来往。我也有同样的建议给你。值得一提的是，你完全可以肯定，郊区没有人与此有关。如果不是别的，这个部落一直是贸易的好地方。他们的壁虎皮带来了可观的收入。}
#{1301}{}{I have absolutely no idea. I have always tried to get involved with the savages as little as possible. I have the same advice for you. For what it's worth, you can be absolutely sure that no one from the Suburbs has anything to do with this. If not anything else, the tribe has always been good for trade. Their gecko skins bring good revenue.}
{1301}{}{我完全不知道。我总是尽量少和野蛮人来往。我也有同样的建议给你。值得一提的是，你完全可以肯定，郊区没有人与此有关。如果不是别的，这个部落一直是贸易的好地方。他们的壁虎皮带来了可观的收入。}
#{1302}{}{Thanks, goodbye, William.}
{1302}{}{谢谢，再见，威廉。}
#{1350}{}{We try to stay as far back as possible from other inhabitants of Albuquerque. They are all just a bunch of cut-throats. Mutant Hunters kill off anyone with even the slightest sign of mutation and not one day goes by that those murderers from Vex's gang would not beat to death some immigrant. To make things even worse, someone made mincemeat out of that savage tribe at the gate recently. That long wall may protect us from the ghouls outside, but we have to deal with the rest ourselves. It is not easy by any means.}
{1350}{}{我们尽量远离阿尔伯克基的其他居民。他们都只是一群割喉者。变种猎人会杀死任何有一点点变异迹象的人，而且没有一天那些来自维克斯帮派的杀人犯不会打死某个移民。更糟的是，最近有人在大门口把那个野蛮部落的人弄得一团糟。那堵长墙也许能保护我们不受外面僵尸的伤害，但我们必须自己处理剩下的事情。无论如何，这并不容易。}
#{1351}{}{We try to stay as far back as possible from other inhabitants of Albuquerque. They are all just a bunch of cut-throats. Mutant Hunters ... well, you know best what y'all are up to. I just hope those mutants are a real threat to us. [He pauses for a moment.] The worst are those murderers from Vex's gang. Not one day goes by that they would not beat to death some immigrant. To make things even worse, someone made mincemeat out of that savage tribe at the gate recently. That long wall may protect us from the ghouls outside, but we have to deal with the rest ourselves. It is not easy by any means.}
{1351}{}{我们尽量远离阿尔伯克基的其他居民。他们都只是一群割喉者。变种猎人。。。好吧，你们最清楚你们在干什么。我只希望那些变种人对我们是真正的威胁。[他停顿了一下]最糟糕的是维克斯帮派的那些杀人犯。他们没有一天不打死某个移民。更糟的是，最近有人在大门口把那个野蛮部落的人弄得一团糟。那堵长墙也许能保护我们不受外面僵尸的伤害，但我们必须自己处理剩下的事情。无论如何，这并不容易。}
#{1352}{}{We try to stay as far back as possible from other inhabitants of Albuquerque. They are all just a bunch of cut-throats. Mutant Hunters ... well, you know best what y'all are up to. I just hope those mutants are a real threat to us. [He pauses for a moment.] The worst are those murderers from Vex's gang. Not one day goes by that they would not beat to death some immigrant. To make things even worse, someone made mincemeat out of that savage tribe at the gate recently. That long wall may protect us from the ghouls outside, but we have to deal with the rest ourselves. It is not easy by any means.}
{1352}{}{我们尽量远离阿尔伯克基的其他居民。他们都只是一群割喉者。变种猎人。。。好吧，你们最清楚你们在干什么。我只希望那些变种人对我们是真正的威胁。[他停顿了一下]最糟糕的是维克斯帮派的那些杀人犯。他们没有一天不打死某个移民。更糟的是，最近有人在大门口把那个野蛮部落的人弄得一团糟。那堵长墙也许能保护我们不受外面僵尸的伤害，但我们必须自己处理剩下的事情。无论如何，这并不容易。}
#{1353}{}{I understand. I have another question.}
{1353}{}{我理解。我还有一个问题。}
#{1354}{}{I'll have to be going now. Goodbye.}
{1354}{}{我得走了。再见。}
#{1400}{}{[He has a good look at the head.] So the motherfucker is finally dead. You've done a good job. [He gives you 2500 caps.] It was high time for the Suburbs to get back to normal, or at least close to normal.}
{1400}{}{[他仔细看了看脑袋]那混蛋终于死了。你做得很好。[他给你2500个上限]现在是郊区恢复正常的时候了，或者至少接近正常。}
#{1401}{}{[He has a good look at the head.] So the motherfucker is finally dead. You've done a good job. [He gives you 2500 caps.] It was high time for the Suburbs to get back to normal, or at least close to normal.}
{1401}{}{[他仔细看了看脑袋]那混蛋终于死了。你做得很好。[他给你2500个上限]现在是郊区恢复正常的时候了，或者至少接近正常。}
#{1402}{}{[He has a good look at the head.] So the motherfucker is finally dead. You've done a good job. [He gives you 500 caps.] You are free to go now, goodbye.}
{1402}{}{[他仔细看了看脑袋]那混蛋终于死了。你做得很好。[他给你500顶瓶盖]你现在可以走了，再见。}
#{1403}{}{[He has a good look at the head.] So the motherfucker is finally dead. You've done a good job. [He gives you 500 caps.] You are free to go now, goodbye.}
{1403}{}{[他仔细看了看脑袋]那混蛋终于死了。你做得很好。[他给你500顶瓶盖]你现在可以走了，再见。}
#{1404}{}{Of course. Take care, William.}
{1404}{}{当然。保重，威廉。}
#{1405}{}{Thankie. Bye.}
{1405}{}{谢谢。再见。}
#{1450}{}{It will serve as a warning. I will have it put on a stick and displayed in front of my house for everyone to see for themselves how we treat trouble-makers round here. No more gangs in the Suburb.}
{1450}{}{它将作为一个警告。我会把它放在一根棍子上，展示在我家门口，让大家亲眼看看我们是如何对待这里的捣蛋鬼的。郊区没有帮派了。}
#{1451}{}{I understand, William. I will get you that head.}
{1451}{}{我明白，威廉。我会给你那头的。}
#{1452}{}{No, I'm not doing that. Forget about it.}
{1452}{}{不，我不会那样做的。算了吧。}
#{1500}{}{Greetings. What can I do for you?}
{1500}{}{问候语。有什么事吗？}
#{1501}{}{The local tribe has been attacked by a band of raiders. It seems that they are from Albuquerque. Do you by any chance know who they could be?}
{1501}{}{当地部落遭到一群袭击者的袭击。他们好像是从阿尔伯克基来的。你知道他们可能是谁吗？}
#{1502}{}{The tribe is planning an attack on the doctors from the hospital. They want to take revenge for the raids on their hunters. Do you think your people could support them?}
{1502}{}{这个部落正计划袭击医院的医生。他们想为突袭猎人报仇。你认为你的人民能支持他们吗？}
#{1503}{}{Nothing at the moment. Take care, William.}
{1503}{}{现在什么都没有。保重，威廉。}
#{1504}{}{Ugh.}
{1504}{}{啊。}
#{1550}{}{No, absolutely not. I don't give a damn about the savages, not to mention about their fairy stories. I honor the doctors. When I had a heart attack, they saved my life transplanting me a new heart. I'm not sending a single man against them.}
{1550}{}{不，绝对不是。我不在乎野蛮人，更不在乎他们的童话故事。我向医生致敬。当我心脏病发作时，他们为我移植了一颗新心脏，救了我的命。我不会派一个人去反对他们。}
#{1551}{}{Whatever you say, William. Goodbye.}
{1551}{}{随你怎么说，威廉。再见。}
#{1600}{}{Nothing. My problem took care of itself. I don't need anyone anymore.}
{1600}{}{没有什么。我的问题自行解决了。我不再需要任何人了。}
#{1601}{}{Oh well, in that case, goodbye.}
{1601}{}{哦，那么，再见。}
#{1650}{}{So a stranger, huh? And a complete retard at that. [He pauses.] Listen, would you like to earn a couple of caps? The work I have in mind may be a little on the dangerous side, but you surely wouldn't mind that, would you?}
{1650}{}{所以是个陌生人，嗯？完全是个笨蛋。[他停顿了一下]听着，你想挣几杯吗？我想做的工作可能有点危险，但你肯定不会介意吧？}
#{1651}{}{So a stranger, huh? And a complete retard at that. [He pauses.] Listen, would you like to earn a couple of caps? The work I have in mind may be a little on the dangerous side, but you surely wouldn't mind that, would you?}
{1651}{}{所以是个陌生人，嗯？完全是个笨蛋。[他停顿了一下]听着，你想挣几杯吗？我想做的工作可能有点危险，但你肯定不会介意吧？}
#{1652}{}{ brave. No feer!}
{1652}{}{勇敢。没有感觉！}
#{1653}{}{ brave. No feer!}
{1653}{}{勇敢。没有感觉！}
#{1654}{}{Do mind! Bye!}
{1654}{}{别介意！再见！}
#{1700}{}{Good. There is a very bad man here, his name is Vex. He hurts people in my quarter and that is why I need you to kill him. If you succeed, I will reward you. Just bring me his head. Whaddaya say?}
{1700}{}{很好。这里有一个很坏的人，他的名字叫维克斯。他伤害了我这一带的人，所以我要你杀了他。如果你成功了，我会奖励你的。把他的头给我。你说什么？}
#{1701}{}{Good. There is a very bad man here, his name is Vex. He hurts people in my quarter and that is why I need you to kill him. If you succeed, I will reward you. Just bring me his head. Whaddaya say?}
{1701}{}{很好。这里有一个很坏的人，他的名字叫维克斯。他伤害了我这一带的人，所以我要你杀了他。如果你成功了，我会奖励你的。把他的头给我。你说什么？}
#{1702}{}{Haed? Okay. Bye.}
{1702}{}{哈德？可以。再见。}
#{1703}{}{Bleh, no-oh. Bye.}
{1703}{}{哦，不，哦。再见。}
#{1750}{}{Yes, now that you mention it, there's something you could help me with. It's a rather unpleasant thing. I need to have the boss of the local gang removed. His name is Vex. His gang's been causing me nothing but trouble for quite some time now, and lately they seem to have lost all restrains. They've started to interfere with my business and that must end. The only way to resolve the situation's to have Vex dead. Without his command, the gang will certainly fall apart before long. I'm looking for someone who could make it happen.}
{1750}{}{是的，既然你提到了，有件事你可以帮我。这是一件相当不愉快的事。我要把当地帮派的头目除掉。他的名字叫维克斯。他的帮派给我带来的麻烦已经有一段时间了，最近他们似乎已经失去了所有的约束。他们已经开始干涉我的生意，这必须结束。解决问题的唯一办法就是让维克斯死。如果没有他的指挥，这个团伙不久就会瓦解。我在找一个能成功的人。}
#{1751}{}{If the price is right, I could take care of that.}
{1751}{}{如果价格合适的话，我可以处理。}
#{1752}{}{I'm not interested in that. I hope you find someone who will be. Goodbye, William.}
{1752}{}{我对此不感兴趣。我希望你能找到一个愿意的人。再见，威廉。}
#{1800}{}{There was one thing I needed, but my problem took care of itself. So no, I don't have any work for you.}
{1800}{}{我需要一件事，但我的问题自己解决了。所以不，我没有工作给你。}
#{1801}{}{Oh well, in that case, goodbye.}
{1801}{}{哦，那么，再见。}
