#{100}{}{You see a prostitute.}
{100}{}{你看到一个妓女。}
#{150}{}{You see Abby.}
{150}{}{你看到艾比了。}
#{200}{}{You see a very attractive prostitute.}
{200}{}{你看到一个很有魅力的妓女。}
#{250}{}{You see Abby, looking very seductive.}
{250}{}{你看艾比，看起来很诱人。}
#{300}{}{I'm happy that you enjoyed it.}
{300}{}{我很高兴你喜欢。}
#{301}{}{Come again next time, honey.}
{301}{}{下次再来，亲爱的。}
#{302}{}{Sweetheart, that was really amazing.}
{302}{}{亲爱的，真是太棒了。}
#{303}{}{Looking forward to your next visit...}
{303}{}{期待你的下次访问。。。}
#{310}{}{You better go. Wanda wouldn't want to see you here.}
{310}{}{你最好走。万达不想在这里见到你。}
#{500}{}{Hey sweetheart. [She winked at you.]}
{500}{}{嘿，亲爱的。[她向你眨了眨眼。]}
#{501}{}{Who are you?}
{501}{}{你是谁？}
#{502}{}{[Ignore her.]}
{502}{}{[别理她。]}
#{503}{}{Homina homina homina!}
{503}{}{人类人类人类人类人类人类！}
#{550}{}{My name is Abby, and I'll do you any way you want. You just need to pay.}
{550}{}{我叫艾比，你想怎么做我就怎么做。你只需要付钱。}
#{551}{}{How is life for prostitutes in this town?}
{551}{}{这个镇上妓女的生活怎么样？}
#{552}{}{Where can I pay?}
{552}{}{我在哪里付款？}
#{553}{}{You are Valery's sister, aren't you?}
{553}{}{你是瓦莱里的妹妹，是吗？}
#{554}{}{Maybe some other time.}
{554}{}{也许改天吧。}
#{600}{}{Hey sweetheart. [She winked at you.]}
{600}{}{嘿，亲爱的。[她向你眨了眨眼。]}
#{601}{}{Who are you?}
{601}{}{你是谁？}
#{602}{}{[Ignore her.]}
{602}{}{[别理她。]}
#{603}{}{Wawawiwa!}
{603}{}{哇哇哇！}
#{650}{}{Wanda arranges everything, surely you saw her on the way in. Hurry, before someone else takes me.}
{650}{}{万达安排了一切，你肯定在进来的路上见过她。快点，在别人带走我之前。}
#{651}{}{Wanda arranges everything, surely you saw her on the way in. Hurry, before someone else takes me.}
{651}{}{万达安排了一切，你肯定在进来的路上见过她。快点，在别人带走我之前。}
#{652}{}{How is life for prostitutes in this town?}
{652}{}{这个镇上妓女的生活怎么样？}
#{653}{}{You're Valery's sister, aren't you?}
{653}{}{你是瓦莱里的妹妹，是吗？}
#{654}{}{OK.}
{654}{}{好 啊。}
#{700}{}{Considering the alternatives, it's probably the best job for a woman in Corath. I am very popular. [She winks at you.] I do very well.}
{700}{}{考虑到其他的选择，这可能是科拉斯最好的工作。我很受欢迎。[她向你眨眼]我做得很好。}
#{701}{}{And where can I pay?}
{701}{}{我在哪付钱？}
#{702}{}{You are Valery's sister, aren't you?}
{702}{}{你是瓦莱里的妹妹，是吗？}
#{703}{}{Thanks, bye.}
{703}{}{谢谢，再见。}
#{750}{}{You know my hypocrite sister? I feel for you.}
{750}{}{你认识我的伪君子妹妹吗？我同情你。}
#{751}{}{Your sister wants to help you. She doesn't want you to do this job anymore.}
{751}{}{你姐姐想帮你。她不想让你再做这份工作了。}
#{752}{}{I see this conversation is not leading anywhere.}
{752}{}{我看这次谈话没有任何意义。}
#{800}{}{Bah, she can't even come and tell me herself, because she's worried what people will say about her.}
{800}{}{呸，她甚至不能亲自来告诉我，因为她担心人们会怎么评价她。}
#{801}{}{Are you saying that you enjoy doing it? With those filthy miners? And I'm not even talking about all those creeps from the wasteland who can afford someone like you. Surely, you must have to do some disgusting people, who can leave you with nasty diseases, or even hurt you just for the fun of it.}
{801}{}{你是说你喜欢做吗？和那些肮脏的矿工在一起？我也不是说那些从荒地里爬出来的人能买得起像你这样的人。当然，你必须做一些恶心的人，谁可以离开你与恶劣的疾病，甚至伤害你只是为了好玩。}
#{802}{}{Seems like I can't convince you, goodbye.}
{802}{}{看来我说服不了你，再见。}
#{850}{}{You're right. I sometimes hate myself for what I do, and several bastards have beaten me already. But what else can I do?}
{850}{}{你说得对。我有时会因为我所做的事而恨自己，已经有几个混蛋打过我了。但我还能做什么呢？}
#{851}{}{Valery told me that you can come and live with her and her husband, if you decide to leave this life.}
{851}{}{瓦莱里告诉我，如果你决定离开这个世界，你可以来和她和她丈夫一起生活。}
#{900}{}{Live with my sister? That wouldn't be the best thing for me, but probably it would still be better than this. Maybe I should try.}
{900}{}{和我妹妹住在一起？这对我来说不是最好的，但可能还是比这个好。也许我应该试试。}
#{901}{}{Good. In that case, pack your things and go to her, she's waiting for you.}
{901}{}{很好。那样的话，收拾好你的东西去找她，她在等你。}
#{950}{}{Hi, you're glad to see me again, aren't you? [She winked at you.]}
{950}{}{嗨，你很高兴再次见到我，是吗？[她向你眨了眨眼。]}
#{951}{}{Hi, you're glad to see me again, aren't you? [She winked at you.]}
{951}{}{嗨，你很高兴再次见到我，是吗？[她向你眨了眨眼。]}
#{952}{}{How is life for prostitutes in this town?}
{952}{}{这个镇上妓女的生活怎么样？}
#{953}{}{And I am here to get some more of you, where do I pay?}
{953}{}{我来这里是为了得到更多的你，我在哪里付钱？}
#{954}{}{You are Valery's sister, aren't you?}
{954}{}{你是瓦莱里的妹妹，是吗？}
#{955}{}{I don't need anything else, goodbye.}
{955}{}{我不需要别的了，再见。}
#{956}{}{Uff.}
{956}{}{不明飞行物。}
#{1000}{}{Hi, you're glad to see both of us again, aren't you? [She winked at you.]}
{1000}{}{嗨，你很高兴再次见到我们，是吗？[她向你眨了眨眼。]}
#{1001}{}{Hi, you're glad to see both of us again, aren't you? [She winked at you.]}
{1001}{}{嗨，你很高兴再次见到我们，是吗？[她向你眨了眨眼。]}
#{1002}{}{What do you think about your sister being a prostitute too?}
{1002}{}{你觉得你妹妹也是妓女怎么样？}
#{1003}{}{We might meet again soon.}
{1003}{}{我们可能很快再见面。}
#{1004}{}{Uff.}
{1004}{}{不明飞行物。}
#{1050}{}{You're weird. Most men in this town would be happy to spend a single night with me and you are willing to pay for a whole week just to make me listen to my sister's tiresome prattle.}
{1050}{}{你真奇怪。这个镇上的大多数男人都很乐意和我共度一个晚上，而你却愿意花整整一个星期的时间让我听我姐姐那无聊的闲话。}
#{1051}{}{Hopefully, you will understand in a week.}
{1051}{}{希望你能在一周内明白。}
#{1052}{}{Uf.}
{1052}{}{佛罗里达州。}
#{1100}{}{You're weird. Most men in this town, and some women too, would be happy to spend a single night with me and you are willing to pay for a whole week just to make me listen to my sister's tiresome prattle.}
{1100}{}{你真奇怪。这个镇上的大多数男人，还有一些女人，都会很乐意和我共度一个晚上，而你愿意花整整一个星期的时间来让我听我姐姐那无聊的闲话。}
#{1101}{}{Hopefully, you will understand in a week.}
{1101}{}{希望你能在一周内明白。}
#{1102}{}{Uf.}
{1102}{}{佛罗里达州。}
#{1150}{}{For the moment, I'm yours and I'm gonna fulfill all your wildest dreams. Don't be shy, come closer baby...}
{1150}{}{现在，我是你的，我要实现你最疯狂的梦想。别害羞，靠近点宝贝。。。}
#{1151}{}{[Beat her up and rape her to teach her a rough lesson about selling herself.]}
{1151}{}{[殴打她并强奸她，让她好好教训一下如何出卖自己。]}
#{1152}{}{[Sleep with her.]}
{1152}{}{[和她睡觉。]}
#{1200}{}{[Abby lies naked and beaten on the bed. She seems to be bleeding.]}
{1200}{}{[艾比光着身子躺在床上挨打。她好像在流血}
#{1201}{}{Fucking whore! If you tell anyone about this, next time I'll kill you!}
{1201}{}{他妈的婊子！如果你告诉任何人，下次我就杀了你！}
#{1250}{}{[When Abby caught the sight of you, her whole body started to tremble in fear, she pulled herself away from you and started to move her head erratically from side to side. At the same time she is opening and closing her mouth as if trying to say something, but no words come out.]}
{1250}{}{[当艾比看到你时，她的全身开始害怕地颤抖，她把自己从你身边拉开，开始不规则地左右移动她的头。同时，她张嘴闭嘴，好像在说什么，但什么也说不出来}
#{1251}{}{[When Abby caught the sight of Gabriel, her whole body started to tremble in fear, she pulled herself away from you and started to move her head erratically from side to side. At the same time she is opening and closing her mouth as if trying to say something, but no words come out.]}
{1251}{}{[当艾比看到加布里埃尔时，她的全身开始害怕地颤抖，她把自己从你身边拉开，开始不规则地左右移动她的头。同时，她张嘴闭嘴，好像在说什么，但什么也说不出来}
#{1252}{}{[Abby is not reacting. She is trembling lightly.]}
{1252}{}{[艾比没有反应。她轻轻地颤抖着}
#{1253}{}{[Leave.]}
{1253}{}{[离开]}
#{1300}{}{Oh, you poor thing. Better leave now, Wanda wouldn't want to see you here.}
{1300}{}{哦，你这个可怜的家伙。最好现在就走，旺达不想在这里见到你。}
#{1301}{}{Bhaaa.}
{1301}{}{巴阿。}
#{1350}{}{Oh, you poor thing. Better leave now, Wanda wouldn't want to see you here.}
{1350}{}{哦，你这个可怜的家伙。最好现在就走，旺达不想在这里见到你。}
#{1351}{}{Bhaaa.}
{1351}{}{巴阿。}
#{1400}{}{It's funny. I know that she never liked what I do, but now she's becoming better at it than me.}
{1400}{}{很有趣。我知道她从不喜欢我做的事，但现在她比我做得更好了。}
#{1401}{}{I see.}
{1401}{}{我懂了。}
#{1450}{}{Oh, hi, it's you. Sorry, but I don't think you should come here anymore.}
{1450}{}{哦，嗨，是你。对不起，但我认为你不应该再到这里来了。}
#{1451}{}{Oh, hi, it's you. Sorry, but I don't think you should come here anymore.}
{1451}{}{哦，嗨，是你。对不起，但我认为你不应该再到这里来了。}
#{1452}{}{So how is life treating you here?}
{1452}{}{你在这里过得怎么样？}
#{1453}{}{As you wish.}
{1453}{}{如你所愿。}
#{1454}{}{Uff.}
{1454}{}{不明飞行物。}
#{1500}{}{It's a change, I have to get used to it... Especially to Bill, it needs some time. But I am glad that I don't have to sleep with any old creep whoever can scrape together enough caps.}
{1500}{}{这是一个变化，我必须适应它。。。尤其是对比尔来说，这需要一些时间。但我很高兴我不用和任何能凑够瓶盖的老家伙睡觉。}
#{1501}{}{Yep, take care.}
{1501}{}{是的，保重。}
