#{100}{}{You see a man.}
{100}{}{你看到一个男人。}
#{150}{}{You see Ademar.}
{150}{}{你看阿德玛。}
#{200}{}{You see a man with a scornful look on his face.}
{200}{}{你看到一个满脸鄙视的人。}
#{250}{}{You see Ademar, Nestor's leading man.}
{250}{}{你看阿德玛，内斯特的男主角。}
#{300}{}{I'm going to kill the next annoying tribesman who comes looking for a holy artifact.}
{300}{}{我要杀了下一个来寻找神圣神器的烦人部落人。}
#{301}{}{PISS-OFF! Retard.}
{301}{}{滚开！延缓。}
#{302}{}{Fuck off.}
{302}{}{滚开。}
#{303}{}{Don't even come near me.}
{303}{}{别靠近我。}
#{304}{}{PISS-OFF! Piece of shit.}
{304}{}{滚开！他妈的。}
#{305}{}{Fuck, don't even try to speak to me. Unless you stop drooling all over your chin, I am not interested in your crap, urgent or not.}
{305}{}{妈的，别跟我说话。除非你别再流口水了，否则我对你的废话不感兴趣，急不急。}
#{306}{}{Look who we have here: The asshole who went against Nestor. I'll let Francis deal with you. I'm sure he'll be delighted that you returned.}
{306}{}{看看我们这里有谁：那个和内斯特作对的混蛋。我让弗朗西斯来处理你。我相信你回来他会很高兴的。}
#{307}{}{Look who we have here: The piece of shit that went against Nestor. I'll let Francis deal with you. I'm sure he'll be delighted that you returned.}
{307}{}{看看我们这里有谁：一个对内斯特不利的混蛋。我让弗朗西斯来处理你。我相信你回来他会很高兴的。}
#{308}{}{Look who we have here: The asshole who fucked up his work. I'll let Francis deal with you. I'm sure he'll be delighted that you returned.}
{308}{}{看看我们这里有谁：那个把工作搞砸的混蛋。我让弗朗西斯来处理你。我相信你回来他会很高兴的。}
#{309}{}{Look who we have here: The little cunt who fucked up her work. I'll let Francis deal with you. I'm sure he'll be delighted that you returned.}
{309}{}{看看我们这里有谁：那个把工作搞砸的小贱人。我让弗朗西斯来处理你。我相信你回来他会很高兴的。}
#{310}{}{We'll teach you to respect our laws.}
{310}{}{我们会教你尊重我们的法律。}
#{311}{}{What? You forgot how to walk? Move your ass to Nestor!}
{311}{}{什么？你忘了怎么走路了？快去内斯特！}
#{312}{}{What? You forgot how to walk? Move your ass to Nestor!}
{312}{}{什么？你忘了怎么走路了？快去内斯特！}
#{313}{}{Well, that's something we've never seen here. And I hope we never do again.}
{313}{}{好吧，这是我们在这里从没见过的。我希望我们再也不要这样了。}
#{314}{}{Splendid, another idiot who doesn't know where to go.}
{314}{}{好极了，又一个不知道去哪儿的白痴。}
#{315}{}{Go block someone else's view.}
{315}{}{去挡住别人的视线。}
#{316}{}{Are you trying to grow roots into the ground here or what?}
{316}{}{你是想在这里把根扎进地里还是怎么了？}
#{317}{}{Livestock is having a reunion here.}
{317}{}{家畜们在这里团聚。}
#{318}{}{Do what you're supposed to and stop with the chitchat. It's time to do some killing.}
{318}{}{做你该做的，别再闲聊了。是时候杀戮了。}
#{400}{}{It seems that you've heard more action stories than would be healthy.}
{400}{}{看来你听到的动作故事比健康的多。}
#{401}{}{Why do I always have to deals with such cretins?!}
{401}{}{为什么我总是要和这些白痴打交道？！}
#{402}{}{You're suicidal, aren't you?}
{402}{}{你想自杀，是吗？}
#{403}{}{Someone here started something they couldn't handle.}
{403}{}{这里有人开始了他们无法处理的事情。}
#{404}{}{It seems that you've heard more action stories than would be healthy.}
{404}{}{看来你听到的动作故事比健康的多。}
#{405}{}{Fuck, I have blood all over me! You destroyed my rags!}
{405}{}{妈的，我全身都是血！你毁了我的衣服！}
#{406}{}{Fuck, I have blood all over me! You destroyed my rags!}
{406}{}{妈的，我全身都是血！你毁了我的衣服！}
#{410}{}{Fuck, watch your aim dickhead!}
{410}{}{操，小心瞄准，笨蛋！}
#{411}{}{Fuck, watch your aim you cow!}
{411}{}{妈的，小心瞄准，你这头牛！}
#{412}{}{I've had it with you, moron!}
{412}{}{我受够你了，白痴！}
#{413}{}{I've had it with you, bitch!}
{413}{}{我受够你了，婊子！}
#{500}{}{I am not in the mood to inspect the face of every rascal who decides to show up here, off with you.}
{500}{}{我没心情去检查每一个决定和你一起出现在这里的流氓的脸。}
#{501}{}{I am not in the mood to inspect the face of every harlot who decides to show up here, off with you.}
{501}{}{我没心情去检查每一个决定来这里和你一起的妓女的脸。}
#{502}{}{Who the hell do you think you are?}
{502}{}{你以为你是谁？}
#{503}{}{Relax, I'll be on my way.}
{503}{}{别紧张，我马上就来。}
#{504}{}{Huuyeee!}
{504}{}{惠耶！}
#{550}{}{As far as I know, I'm still Ademar. And you better remember that I'm sort of a bouncer here that crushes anyone who wants to bother Nestor without a good reason. And there are always bums like that around here. I advise you to piss off before I crush you too.}
{550}{}{据我所知，我还是阿德玛。你最好记住，我是这里的一个保镖，我会压垮任何想无缘无故打扰内斯特的人。这附近总有这样的流浪汉。我劝你在我压扁你之前滚开。}
#{551}{}{I want to talk to Nestor.}
{551}{}{我想和内斯特谈谈。}
#{552}{}{I am looking for work, would Nestor have anything for me?}
{552}{}{我在找工作，内斯特有什么要给我的吗？}
#{553}{}{I am here to challenge Nestor to fight me in the ring.}
{553}{}{我是来挑战内斯特在拳击场上和我对抗的。}
#{554}{}{I am here to challenge Nestor to fight me in the ring.}
{554}{}{我是来挑战内斯特在拳击场上和我对抗的。}
#{555}{}{Relax, I'll be on my way.}
{555}{}{别紧张，我马上就来。}
#{600}{}{Are you deaf or is it your idea of fun to ignore what I just said? Do you have important business with Nestor? Save your breath, I will reply for you - YOU DON'T!}
{600}{}{你聋了吗？还是你认为忽视我刚才说的话很有趣？你和内斯特有重要业务吗？省省你的呼吸，我会回答你-你不！}
#{601}{}{I am looking for work, so I wanted to ask whether Nestor has anything for me.}
{601}{}{我正在找工作，所以我想问内斯特是否有什么东西给我。}
#{602}{}{I am here to challenge Nestor to fight me in the ring.}
{602}{}{我是来挑战内斯特在拳击场上和我对抗的。}
#{603}{}{Relax, I'll be on my way.}
{603}{}{别紧张，我马上就来。}
#{650}{}{Are you deaf or is it your idea of fun to ignore what I just said? Do you have important business with Nestor? Save your breath, I'll reply for you - YOU DON'T!}
{650}{}{你聋了吗？还是你认为忽视我刚才说的话很有趣？你和内斯特有重要业务吗？省省你的呼吸吧，我会替你回答的-你不要！}
#{651}{}{I am looking for work, so I wanted to ask whether Nestor has anything for me.}
{651}{}{我正在找工作，所以我想问内斯特是否有什么东西给我。}
#{652}{}{I am here to challenge Nestor to fight me in the ring.}
{652}{}{我是来挑战内斯特在拳击场上和我对抗的。}
#{653}{}{Relax, I'll be on my way.}
{653}{}{别紧张，我马上就来。}
#{700}{}{You could've spilled that out to start with and save both of us precious time. As a matter of fact, something needs to be done and Nestor doesn't want to involve his own people. You have more luck than brains to come here just now. You'll be dealing with me on this little issue, of course, unless you have some inexplicable problem with that.}
{700}{}{你本来可以把这些都说出来的，这样我们两个都能省下宝贵的时间。事实上，有些事情需要做，内斯特不想牵扯到自己的人。你刚才来这儿真是太幸运了。当然，你要在这个小问题上和我打交道，除非你对此有什么莫名其妙的问题。}
#{701}{}{No problem. What's the matter?}
{701}{}{没问题。怎么了}
#{702}{}{I'd rather stay unemployed than deal with you. Farewell.}
{702}{}{我宁愿失业也不愿和你打交道。再会。}
#{750}{}{You could've spilled that out to start with and save both of us precious time. As a matter of fact, something needs to be done and Nestor doesn't want to involve his own people. You have more luck than brains to come here just now. You'll be dealing with me on this little issue, of course, unless you have some inexplicable problem with that.}
{750}{}{你本来可以把这些都说出来的，这样我们两个都能省下宝贵的时间。事实上，有些事情需要做，内斯特不想牵扯到自己的人。你刚才来这儿真是太幸运了。当然，你要在这个小问题上和我打交道，除非你对此有什么莫名其妙的问题。}
#{751}{}{No problem. What's the matter?}
{751}{}{没问题。怎么了}
#{752}{}{I'd rather stay unemployed than deal with you. Farewell.}
{752}{}{我宁愿失业也不愿和你打交道。再会。}
#{800}{}{One miner was causing trouble in the mine, encouraging others to revolt, instead of keeping his mouth shut and doing his work. So we had him locked up. But Nestor thinks that the guy was hired by Uncle. True, he sees Uncle behind everything, but in this case he's probably right.}
{800}{}{一名矿工在矿井里制造麻烦，鼓励其他人反抗，而不是闭嘴干活。所以我们把他关起来了。但是内斯特认为那家伙是叔叔雇的。没错，他看到叔叔在幕后操纵一切，但在这种情况下，他可能是对的。}
#{801}{}{So?}
{801}{}{所以呢？}
#{850}{}{So? I think it's clear! Get him out of jail and bring him here! His name is Richie. Someone here will take care of him and make sure that he shares with us just how close he is with Uncle. And no crazy shit, Nestor has no need to make enemies with the cops.}
{850}{}{所以呢？我想很清楚！把他从监狱里弄出来，带到这里来！他叫里奇。这里会有人照顾他，确保他和我们分享他和叔叔有多亲密。也不疯狂，内斯特没有必要和警察树敌。}
#{851}{}{Any ideas how to go about it?}
{851}{}{你知道怎么做吗？}
#{852}{}{And what is the pay?}
{852}{}{工资是多少？}
#{853}{}{I'll see what can be done.}
{853}{}{我看看能做些什么。}
#{900}{}{[He smiled.] That's for you to find out. Try to use that thing between your ears for once and come up with something to earn your pay.}
{900}{}{[他笑了笑]这是你要知道的。试着用你的耳朵之间的东西一次，想出一些东西来赚取你的报酬。}
#{901}{}{And what will be the pay?}
{901}{}{工资是多少？}
#{902}{}{I'll see what can be done.}
{902}{}{我看看能做些什么。}
#{950}{}{All you need to know is that you'll be rewarded. But only when you've actually done something! Now you should be more worried about your task than the money.}
{950}{}{你只需要知道你会得到回报。但只有当你真的做了什么！现在你应该更担心你的任务而不是钱。}
#{951}{}{Any ideas how to go about it?}
{951}{}{你知道怎么做吗？}
#{952}{}{I'll see what can be done.}
{952}{}{我看看能做些什么。}
#{1000}{}{I advise you not to fuck up. Nestor is not too fond of outsiders right now. [He smiled.] I mean, even less than usual.}
{1000}{}{我劝你不要搞砸了。内斯特现在不太喜欢外人。[他笑了笑]我是说，比平常还要少。}
#{1001}{}{Does it have something to do with that outsider who died in the ring?}
{1001}{}{这和那个死在拳击场上的外人有关吗？}
#{1002}{}{OK.}
{1002}{}{好 啊。}
#{1050}{}{I have a strong feeling that this isn't the first time you are blocking my view. Could you please fuck off again? This time for good!}
{1050}{}{我有一种强烈的感觉，这不是你第一次挡住我的视线。你能再滚一次吗？这次是永远的！}
#{1051}{}{Who the fuck do you think you are?}
{1051}{}{你他妈以为你是谁？}
#{1052}{}{Relax, I'll be on my way.}
{1052}{}{别紧张，我马上就来。}
#{1053}{}{Huuyeeee!}
{1053}{}{火影忍者！}
#{1100}{}{Not that my view here is particularly great, but your ugly face certainly doesn't make it any better.}
{1100}{}{不是说我这里的风景特别好，但你丑陋的脸肯定不会让它变得更好。}
#{1101}{}{I want to talk to Nestor.}
{1101}{}{我想和内斯特谈谈。}
#{1102}{}{I am looking for work, would Nestor have anything for me?}
{1102}{}{我在找工作，内斯特有什么要给我的吗？}
#{1103}{}{I'm here to challenge Nestor to fight me in the ring.}
{1103}{}{我是来挑战内斯特在拳击场上和我对抗的。}
#{1104}{}{I'm here to challenge Nestor to fight me in the ring.}
{1104}{}{我是来挑战内斯特在拳击场上和我对抗的。}
#{1105}{}{Relax, I'll be on my way.}
{1105}{}{别紧张，我马上就来。}
#{1106}{}{Huuyeeee!}
{1106}{}{火影忍者！}
#{1150}{}{Fuck my life, is this for real? Something about me must be attracting all the idiots from far and wide so they can drool all over me. Leave me be, dammit. You're getting my shoes wet!}
{1150}{}{操我的命，这是真的吗？我身上的某些东西一定吸引了来自四面八方的白痴，这样他们就可以流我的口水了。别管我，该死的。你把我的鞋弄湿了！}
#{1151}{}{Go, he.}
{1151}{}{去吧，他。}
#{1200}{}{You're loitering around here even though I'm pretty sure you should be somewhere else doing your work. Seems like one of us is stupid. And it's not me!}
{1200}{}{你在这里闲逛，尽管我很确定你应该在别的地方工作。好像我们中有人很蠢。不是我！}
#{1201}{}{I'm here to challenge Nestor to fight me in the ring.}
{1201}{}{我是来挑战内斯特在拳击场上和我对抗的。}
#{1202}{}{I'm here to challenge Nestor to fight me in the ring.}
{1202}{}{我是来挑战内斯特在拳击场上和我对抗的。}
#{1203}{}{I'm working on it.}
{1203}{}{我正在努力。}
#{1250}{}{Richie came here racing and blabbered something about a reward for information. Now the dummy is singing for free. The reward belongs to you, here you go, 500 caps. Don't make that face at me, I never said it would be a fortune. After all, it wasn't a very difficult task, but there is something else that you need to take care of right now, and the pay will be much better.}
{1250}{}{里奇跑来这里，喋喋不休地说要悬赏情报。现在假人免费唱歌。奖赏属于你，给你，500顶瓶盖。别对我做鬼脸，我从没说过那会是一笔财富。毕竟，这不是一个非常困难的任务，但还有一些事情，你需要照顾的权利，现在的薪酬将更好。}
#{1251}{}{But...}
{1251}{}{但是。。。}
#{1300}{}{Shut up. I wouldn't trust you with guarding a rotting corpse, if I had a choice, but right now there is no one better. That's because there is no one else at all. Richie really stirred it up down in the mines and now the boneheaded miners are refusing to work and they are threatening us with a revolt. They should be happy that they have jobs at all and they get paid for it. But not them, they have to cause trouble, the ungrateful shits.}
{1300}{}{闭嘴。如果我有选择的话，我不会相信你会守护一具腐烂的尸体，但现在没有比这更好的了。那是因为根本没有其他人。里奇真的在矿井里挑起了事端，现在那些骨瘦如柴的矿工拒绝工作，他们用反抗来威胁我们。他们应该高兴的是，他们有工作，他们得到了报酬。但不是他们，他们要制造麻烦，忘恩负义的大便。}
#{1301}{}{[Stay silent.]}
{1301}{}{[保持沉默。]}
#{1302}{}{And what does it have to do with me?}
{1302}{}{这跟我有什么关系？}
#{1350}{}{If one of Nestor's men tries to deal with them, it's not gonna make them any less restless. But you're not from here, so head to the mines and force them to work again. I don't care how you do it, just make sure it doesn't turn against us and that it stays in the mines. The police prefer to have a peaceful town where they don't have to lift a finger, and Nestor certainly doesn't want them to turn against him.}
{1350}{}{如果内斯特手下有人想对付他们，那也不会让他们不安。但你不是从这里来的，所以去矿场强迫他们再工作。我不在乎你怎么做，只要确保它不会对我们不利，它会留在矿井里。警察更喜欢一个安静的小镇，在那里他们不必动一根手指，内斯特当然不想让他们转而反对他。}
#{1351}{}{I'll check it out.}
{1351}{}{我去看看。}
#{1352}{}{Oukeeey.}
{1352}{}{奥基。}
#{1400}{}{Yep, move your ass. The entrance to the mines is nearby.}
{1400}{}{是的，快走。矿场的入口就在附近。}
#{1401}{}{OK.}
{1401}{}{好 啊。}
#{1450}{}{Didn't I tell you to shut up? I did! So shut your trap! If one of Nestor's men tries to deal with them, it's not gonna make them any less restless. But you're not from here, so head to the mines and force them to work again. I don't care how you do it, just make sure it doesn't turn against us and that it stays in the mines. The police prefer to have a peaceful town where they don't have to lift a finger, and Nestor certainly doesn't want them to turn against him.}
{1450}{}{我不是叫你闭嘴吗？我做到了！所以闭上你的陷阱！如果内斯特手下有人想对付他们，那也不会让他们不安。但你不是从这里来的，所以去矿场强迫他们再工作。我不在乎你怎么做，只要确保它不会对我们不利，它会留在矿井里。警察更喜欢一个安静的小镇，在那里他们不必动一根手指，内斯特当然不想让他们转而反对他。}
#{1451}{}{I'll check it out.}
{1451}{}{我去看看。}
#{1500}{}{You really are slower than a one-legged gecko, or did you just decide to have your way with some whore before doing your work? Actually, in the second case it wouldn't take you that long either. Someone already finished Richie off in the jail! No doubt it was Uncle making sure his little birdie wouldn't sing ever again. I'm sure that I'll regret it, but I have another task for you. I have no choice.}
{1500}{}{你真的比一条腿的壁虎还慢，还是你在工作前就决定和妓女混在一起了？实际上，在第二种情况下，你也不会花那么长时间。有人已经把里奇关进监狱了！毫无疑问，是叔叔确保他的小鸟不再唱歌了。我肯定我会后悔的，但我还有一件事要做。我别无选择。}
#{1501}{}{But...}
{1501}{}{但是。。。}
#{1550}{}{You really are slower than a one-legged gecko, or did you just decide to go and get drunk before doing your work? Actually, in the second case it wouldn't take you that long either. Someone already finished Richie off in the jail! No doubt it was Uncle making sure his little birdie wouldn't sing ever again. I'm sure that I'll regret it, but I have another task for you. I have no choice.}
{1550}{}{你真的比一条腿的壁虎还慢，还是你只是决定在工作前喝一杯？实际上，在第二种情况下，你也不会花那么长时间。有人已经把里奇关进监狱了！毫无疑问，是叔叔确保他的小鸟不再唱歌了。我肯定我会后悔的，但我还有一件事要做。我别无选择。}
#{1551}{}{But...}
{1551}{}{但是。。。}
#{1600}{}{It's hard to believe that you forced those lazy asses to get back to work, but it sure seems like it. Here, take 1500 caps. Most people in this town never see that many caps together in their long sorry lives. If you're interested, Nestor has another job he'd like to talk to you about in person. I can't imagine one fucking reason why you wouldn't be interested.}
{1600}{}{很难相信你强迫那些懒汉回去工作，但看起来确实是这样。给，拿1500个瓶盖。这个镇上的大多数人在漫长的一生中从来没有见过这么多的瓶盖在一起。如果你感兴趣的话，内斯特还有另一份工作想亲自和你谈谈。我想不出你有什么理由不感兴趣。}
#{1601}{}{I'm interested.}
{1601}{}{我很感兴趣。}
#{1602}{}{Not interested.}
{1602}{}{不感兴趣。}
#{1650}{}{That's the stupidest decision I've witnessed in a very long time. Your bad. If you change your mind, move your ass back here. But don't think too long, the offer won't last forever.}
{1650}{}{这是我很长时间以来看到的最愚蠢的决定。你的错。如果你改变主意，把你的屁股移回来。但不要想太久，这个提议不会永远持续下去。}
#{1651}{}{OK.}
{1651}{}{好 啊。}
#{1700}{}{And why wouldn't you be? As I said, Nestor wants to explain this personally, so you will have the honor of meeting him. And dammit, at least try to seem like you're happy about it, even when you aren't anymore.}
{1700}{}{你为什么不呢？正如我所说，内斯特想亲自解释这一点，所以你将有幸见到他。该死的，至少试着让自己看起来很开心，即使你已经不开心了。}
#{1701}{}{What can you tell me about Nestor?}
{1701}{}{关于内斯特你能告诉我什么？}
#{1702}{}{Well, let me go to him.}
{1702}{}{好吧，让我去找他。}
#{1750}{}{He's a son of a bitch. But an insanely rich and merciless son of a bitch. The smartest thing to do in this town is to always be on his side.}
{1750}{}{他是个狗娘养的。但是一个疯狂的富有和无情的狗娘养的。在这个镇上最聪明的事就是永远站在他的一边。}
#{1751}{}{Well, let me go to him then.}
{1751}{}{好吧，那我去找他。}
#{1800}{}{Certainly, the door is free. I don't say that very often, so I hope you appreciate it.}
{1800}{}{当然，门是免费的。我不常这么说，希望你能理解。}
#{1801}{}{Yeah, yeah, as long as you get out of the way.}
{1801}{}{是的，是的，只要你让开。}
#{1850}{}{It's hard to believe that you forced those lazy asses to get back to work, but it sure seems like it. Here, take 1500 caps. Most people in this town never see that many caps together in their long sorry lives. If you're interested, Nestor has another job he'd like to talk to you about in person. I can't imagine one fucking reason why you wouldn't be interested.}
{1850}{}{很难相信你强迫那些懒汉回去工作，但看起来确实是这样。给，拿1500个瓶盖。这个镇上的大多数人在漫长的一生中从来没有见过这么多的瓶盖在一起。如果你感兴趣的话，内斯特还有另一份工作想亲自和你谈谈。我想不出你有什么理由不感兴趣。}
#{1851}{}{I'm interested.}
{1851}{}{我很感兴趣。}
#{1852}{}{Not interested.}
{1852}{}{不感兴趣。}
#{1900}{}{That's the stupidest decision I've witnessed in a very long time. Your bad. If you change your mind, move your ass back here. But don't think too long, the offer won't last forever.}
{1900}{}{这是我很长时间以来看到的最愚蠢的决定。你的错。如果你改变主意，把你的屁股移回来。但不要想太久，这个提议不会永远持续下去。}
#{1901}{}{OK.}
{1901}{}{好 啊。}
#{1950}{}{Oh shit, that didn't work out at all. Not only we lost the miners, but we lost several capable men too. And what's worse, the cops are really pissed at Nestor that they had to intervene. And what the hell were YOU doing? I'll tell you what - YOU FUCKED UP!}
{1950}{}{哦，妈的，那根本没用。我们不仅失去了矿工，而且还失去了几个能干的人。更糟糕的是，警察们对内斯特非常恼火，他们不得不干预。你到底在干什么？我告诉你-你搞砸了！}
#{1951}{}{So?}
{1951}{}{所以呢？}
#{2000}{}{You're lucky that you brought that Richie here. It seems like that dumb look on your face is not the only thing you are capable of, so Nestor would like to give you another job himself, if you're interested. Although, personally, I would prefer to kick you in the ass so hard that you would spend the rest of your life doing somersaults.}
{2000}{}{你很幸运把里奇带来了。看起来你脸上那种傻乎乎的表情并不是你唯一的能力，所以如果你感兴趣的话，内斯特想亲自给你另一份工作。不过，就我个人而言，我宁愿狠狠地踢你的屁股，让你一辈子都在翻筋斗。}
#{2001}{}{You're lucky that you brought that Richie here. It seems like that dumb look on your face is not the only thing you are capable of, so Nestor would like to give you another job himself, if you're interested. Although, personally, I would prefer to kick you in the ass so hard that you would spend the rest of your life doing somersaults.}
{2001}{}{你很幸运把里奇带来了。看起来你脸上那种傻乎乎的表情并不是你唯一的能力，所以如果你感兴趣的话，内斯特想亲自给你另一份工作。不过，就我个人而言，我宁愿狠狠地踢你的屁股，让你一辈子都在翻筋斗。}
#{2002}{}{I'm interested.}
{2002}{}{我很感兴趣。}
#{2003}{}{Not interested.}
{2003}{}{不感兴趣。}
#{2050}{}{So nothing! Due to the police being so pissed off, we can't afford to make any moves. You better take your sorry ass far from this town and back to the dunghole you came from.}
{2050}{}{所以没什么！由于警察非常生气，我们不能采取任何行动。你最好把你可怜的屁股带离这个镇远点，回到你原来的粪坑里去。}
#{2051}{}{I have to think about that.}
{2051}{}{我得好好想想。}
#{2100}{}{Oh shit, that didn't work out at all. Not only we lost the miners, but we lost several capable men too. And what's worse, the cops are really pissed at Nestor that they had to intervene. And what the hell were YOU doing? I'll tell you what - YOU FUCKED UP!}
{2100}{}{哦，妈的，那根本没用。我们不仅失去了矿工，而且还失去了几个能干的人。更糟糕的是，警察们对内斯特非常恼火，他们不得不干预。你到底在干什么？我告诉你-你搞砸了！}
#{2101}{}{So?}
{2101}{}{所以呢？}
#{2150}{}{You're lucky that you brought that Richie here. It seems that dumb look on your face is not the only thing you are capable of, so Nestor would like to give you another job himself, if you're interested. Although, personally, I would prefer to kick you in the ass so hard that you would spend the rest of your life doing somersaults.}
{2150}{}{你很幸运把里奇带来了。看起来你脸上傻乎乎的表情并不是你唯一的能力，所以如果你感兴趣的话，内斯特想亲自给你另一份工作。不过，就我个人而言，我宁愿狠狠地踢你的屁股，让你一辈子都在翻筋斗。}
#{2151}{}{I'm interested.}
{2151}{}{我很感兴趣。}
#{2152}{}{Not interested.}
{2152}{}{不感兴趣。}
#{2200}{}{So nothing! Due to the police being so pissed off, we can't afford to make any moves. You better take your sorry ass far from this town and return to the same dunghole that you came from.}
{2200}{}{所以没什么！由于警察非常生气，我们不能采取任何行动。你最好把你可怜的屁股带离这个镇远点，回到你原来的地牢里去。}
#{2201}{}{Whatever. I'll leave whenever I want to.}
{2201}{}{无论什么。我想走的时候就走。}
#{2250}{}{But it doesn't work just like that, you need a good reason for that, numbnuts. If it wasn't like that, Blaster could just move into the ring and live there. Damn, something is seriously wrong with this world full of suicidal people.}
{2250}{}{但事情不是这样的，你需要一个很好的理由，笨蛋。如果不是那样的话，爆炸机就可以搬进拳击场，住在那里。妈的，这个世界上有很多自杀的人，真是出了大问题。}
#{2251}{}{Who is Blaster?}
{2251}{}{爆炸机是谁？}
#{2252}{}{Screw it, I'm just gonna wipe you all out.}
{2252}{}{去他妈的，我要把你们都干掉。}
#{2253}{}{I'm here in Uncle's name. He demands Nestor to be expelled from Corath for causing the miners' revolt, which recently spilled into the town. Uncle's people are already arranging it with the police and the Lawteller.}
{2253}{}{我是以叔叔的名义来的。他要求内斯特被驱逐出科拉斯，因为他引起了矿工的反抗，而这场反抗最近蔓延到了科拉斯镇。叔叔的人已经和警察和执法人员安排好了。}
#{2254}{}{I'm here in Uncle's name. He's in possession of evidence proving that Nestor had a man named Richie killed, and he demands that he is expelled from Corath. Uncle's people are already arranging it with the police and the Lawteller.}
{2254}{}{我是以叔叔的名义来的。他有证据证明内斯特杀害了一个叫里奇的人，他要求把他从科拉斯开除。叔叔的人已经和警察和执法人员安排好了。}
#{2255}{}{Stupid laws. Forget about it.}
{2255}{}{愚蠢的法律。算了吧。}
#{2300}{}{But it doesn't work just like that, you need a good reason for that, ya ditz. If it wasn't like that, Blaster could just move into the ring and live there. Damn', something is seriously wrong with this world full of suicidal people.}
{2300}{}{但事情不是这样的，你需要一个很好的理由。如果不是那样的话，爆炸机就可以搬进拳击场，住在那里。妈的，这个世界上到处都是自杀的人，出了严重的问题。}
#{2301}{}{Who is Blaster?}
{2301}{}{爆炸机是谁？}
#{2302}{}{Screw it, I'm just gonna wipe you all out.}
{2302}{}{去他妈的，我要把你们都干掉。}
#{2303}{}{I'm here in Uncle's name. He demands Nestor to be expelled from Corath for causing the miners' revolt, which recently spilled into the town. Uncle's people are already arranging it with the police and the Lawteller.}
{2303}{}{我是以叔叔的名义来的。他要求内斯特被驱逐出科拉斯，因为他引起了矿工的反抗，而这场反抗最近蔓延到了科拉斯镇。叔叔的人已经和警察和执法人员安排好了。}
#{2304}{}{I'm here in Uncle's name. He's in possession of evidence proving that Nestor had a man called Richie killed, and he demands that he is expelled from Corath. Uncle's people are already arranging it with the police and the Lawteller.}
{2304}{}{我是以叔叔的名义来的。他有证据证明内斯特杀害了一个叫里奇的人，他要求把他从科拉斯开除。叔叔的人已经和警察和执法人员安排好了。}
#{2305}{}{Stupid laws. Forget about it.}
{2305}{}{愚蠢的法律。算了吧。}
#{2350}{}{You want to challenge Nestor and you don't know who Blaster is? I almost feel sorry for you. Blaster is a mountain of mutated flesh who turns everyone who challenges Nestor into meatloaf.}
{2350}{}{你想挑战内斯特却不知道爆破手是谁？我几乎为你感到难过。爆能者是一座变异的肉体之山，他把所有挑战内斯特的人变成肉饼。}
#{2351}{}{Screw it, I'm just gonna wipe you all out.}
{2351}{}{去他妈的，我要把你们都干掉。}
#{2352}{}{I'm here in Uncle's name. He demands Nestor to be expelled from Corath for causing the miners' revolt, which recently spilled into the town. Uncle's people are already arranging it with the police and the Lawteller.}
{2352}{}{我是以叔叔的名义来的。他要求内斯特被驱逐出科拉斯，因为他引起了矿工的反抗，而这场反抗最近蔓延到了科拉斯镇。叔叔的人已经和警察和执法人员安排好了。}
#{2353}{}{I'm here in Uncle's name. He's in possession of evidence proving that Nestor had a man called Richie killed, and he demands that he is expelled from Corath. Uncle's people are already arranging it with the police and the Lawteller.}
{2353}{}{我是以叔叔的名义来的。他有证据证明内斯特杀害了一个叫里奇的人，他要求把他从科拉斯开除。叔叔的人已经和警察和执法人员安排好了。}
#{2354}{}{Stupid laws. Forget about it.}
{2354}{}{愚蠢的法律。算了吧。}
#{2400}{}{And Blaster will 'arrange' it very quickly with you. Uncle is not even willing to sacrifice one of his own people. But that's no surprise when he found such a willing suicide in you.}
{2400}{}{爆炸机会很快和你安排好的。叔叔甚至不愿意牺牲自己的一个民族。但当他发现你如此愿意自杀时，这并不奇怪。}
#{2401}{}{[Go to the ring.]}
{2401}{}{[去拳击场]}
#{2500}{}{Hey, aren't you the one who got Richie out of jail? Yeah, it's you, he told us about you. I should've recognized you from the start, but his prattle was so full of crap, for example he thought we should pay him for his information about Uncle. Now the fool is already singing, free of charge. But we have a job for you here. Not that freeing one donkey from jail made a big impression on any of us. However, there is no one else right now.}
{2500}{}{嘿，是你让里奇出狱的吗？是的，是你，他告诉我们你的事。我本该从一开始就认出你来的，但他的闲话里全是废话，比如他认为我们应该付钱给他，让他知道他叔叔的情况。现在傻子已经在免费唱歌了。但我们这里有份工作给你。并不是说把一头驴从监狱里解救出来对我们每个人都有很大的影响。然而，现在没有其他人。}
#{2501}{}{And how about some reward for freeing Richie?}
{2501}{}{释放里奇的报酬怎么样？}
#{2502}{}{What's the deal?}
{2502}{}{怎么回事？}
#{2550}{}{I think I just heard wrong. Did I, or one of Nestor's people, ever ask you to get that troublemaker out of there? We did not! I don't know why you did it and I don't care either. You did not do it for us, so you will get nothing from us.}
{2550}{}{我想我听错了。我或者内斯特的人有没有让你把那个捣蛋鬼弄出来？我们没有！我不知道你为什么这么做，我也不在乎。你不是为我们做的，所以你不会从我们那里得到什么。}
#{2551}{}{So how about that job?}
{2551}{}{那工作怎么样？}
#{2600}{}{Richie took the job in the mines only to stir up the miners to rebellion. And sure enough, those impressionable oxen are already threatening us with a revolt instead of doing their work. They should be happy to have a job for which they are paid. But not them, they must cause trouble.}
{2600}{}{里奇在矿井里干这项工作只是为了激起矿工们的叛乱。毫无疑问，那些易受影响的牛已经在用反抗来威胁我们，而不是做他们的工作。他们应该很高兴有一份有报酬的工作。但不是他们，他们必须制造麻烦。}
#{2601}{}{Continue.}
{2601}{}{继续。}
#{2650}{}{Hey, aren't you the one who got Richie out of jail? Yeah, it's you, he told us about you. I should've recognized you from the start, but his rattle was so full of crap, for example he thought we should pay him for his information about Uncle. Now the fool is already singing, free of charge. But we have a job for you here. Not that freeing one donkey from jail made a big impression on any of us. However, there is no one else right now.}
{2650}{}{嘿，是你让里奇出狱的吗？是的，是你，他告诉我们你的事。我本该从一开始就认出你来的，但他说的话全是废话，比如他以为我们应该付钱给他，让他知道他叔叔的情况。现在傻子已经在免费唱歌了。但我们这里有份工作给你。并不是说把一头驴从监狱里解救出来对我们每个人都有很大的影响。然而，现在没有其他人。}
#{2651}{}{And how about some reward for freeing Richie?}
{2651}{}{释放里奇的报酬怎么样？}
#{2652}{}{What's the deal?}
{2652}{}{怎么回事？}
#{2700}{}{I think I just heard wrong. Did I, or one of Nestor's people, ever ask you to get that troublemaker out of there? We did not! I don't know why you did it and I don't care either. You did not do it for us, so you will get nothing from us.}
{2700}{}{我想我听错了。我或者内斯特的人有没有让你把那个捣蛋鬼弄出来？我们没有！我不知道你为什么这么做，我也不在乎。你不是为我们做的，所以你不会从我们那里得到什么。}
#{2701}{}{So how about that job?}
{2701}{}{那工作怎么样？}
#{2750}{}{You could've spilled that out to start with and save both of us precious time. As a matter of fact, something needs to be done and Nestor doesn't want to involve his own people. You have more luck than sense to come here just now. You'll be dealing with me on this little issue, of course, unless you have some inexplicable problem with that.}
{2750}{}{你本来可以把这些都说出来的，这样我们两个都能省下宝贵的时间。事实上，有些事情需要做，内斯特不想牵扯到自己的人。你刚才来这儿真是太幸运了。当然，你要在这个小问题上和我打交道，除非你对此有什么莫名其妙的问题。}
#{2751}{}{No problem. What is the matter?}
{2751}{}{没问题。怎么了？}
#{2752}{}{I'd rather stay unemployed than deal with you. Farewell.}
{2752}{}{我宁愿失业也不愿和你打交道。再会。}
#{2800}{}{One miner was causing trouble in the mine, encouraging others to revolt, instead of shutting his mouth and doing his work. So we had him locked up. But Nestor thought that the guy was hired by Uncle. True, he sees Uncle behind everything, but in this case he was right. Turns out, some hired rat twisted Richie's neck in the joint! No doubt it was Uncle making sure his little birdie wouldn't sing ever again.}
{2800}{}{一名矿工在矿井里制造麻烦，鼓励其他人反抗，而不是闭嘴干活。所以我们把他关起来了。但是内斯特认为那家伙是叔叔雇的。是的，他看到叔叔在幕后操纵一切，但这次他是对的。原来，有个雇来的老鼠把里奇的脖子扭到了关节里！毫无疑问，是叔叔确保他的小鸟不再唱歌了。}
#{2801}{}{And what can I do about it?}
{2801}{}{我能做些什么呢？}
#{2850}{}{If your grace lets me, I will explain! The mines are already boiling, and those impressionable oxen are refusing to work and threatening to revolt. They should be happy to have paying jobs. But not them, they must cause trouble.}
{2850}{}{如果陛下允许，我会解释的！矿井已经沸腾，那些易受影响的牛拒绝工作，并威胁要反抗。他们应该很高兴有带薪工作。但不是他们，他们必须制造麻烦。}
#{2851}{}{Continue.}
{2851}{}{继续。}
#{2900}{}{You could've spilled that out to start with and save both of us precious time. As a matter of fact, something needs to be done and Nestor doesn't want to involve his own people. You have more luck than brains to come here just now. You'll be dealing with me on this little issue, of course, unless you have some inexplicable problem with that.}
{2900}{}{你本来可以把这些都说出来的，这样我们两个都能省下宝贵的时间。事实上，有些事情需要做，内斯特不想牵扯到自己的人。你刚才来这儿真是太幸运了。当然，你要在这个小问题上和我打交道，除非你对此有什么莫名其妙的问题。}
#{2901}{}{No problem. What is the matter?}
{2901}{}{没问题。怎么了？}
#{2902}{}{I'd rather stay unemployed than deal with you. Farewell.}
{2902}{}{我宁愿失业也不愿和你打交道。再会。}
#{2950}{}{Hey, aren't you the one who got Richie out of jail? Yeah, it's you, he told us about you. I should've recognized you from the start, but his prattle was so full of crap. Like, he thought we should pay him for his information about Uncle. Now the fool is already singing, free of charge. Nestor would have a job for you here. Not that freeing one donkey from jail made a big impression on any of us. However, there is no one else right now.}
{2950}{}{嘿，是你让里奇出狱的吗？是的，是你，他告诉我们你的事。我本该从一开始就认出你来的，但他的话全是废话。比如说，他觉得我们应该付钱给他关于叔叔的信息。现在傻子已经在免费唱歌了。内斯特会在这里给你找份工作。并不是说把一头驴从监狱里解救出来对我们每个人都有很大的影响。然而，现在没有其他人。}
#{2951}{}{And how about some reward for freeing Richie?}
{2951}{}{释放里奇的报酬怎么样？}
#{2952}{}{What's the deal?}
{2952}{}{怎么回事？}
#{3000}{}{I think I just heard wrong. Did I, or one of Nestor's people, ever ask you to get that troublemaker out of there? We did not! I don't know why you did it and I don't care either. You did not do it for us, so you will get nothing from us.}
{3000}{}{我想我听错了。我或者内斯特的人有没有让你把那个捣蛋鬼弄出来？我们没有！我不知道你为什么这么做，我也不在乎。你不是为我们做的，所以你不会从我们那里得到什么。}
#{3001}{}{So, how about that work?}
{3001}{}{那工作怎么样？}
#{3050}{}{As I said, Nestor wants to explain this personally, so you will have the honor to meet him. And dammit, at least try to seem like your happy about it, even when you aren't anymore.}
{3050}{}{正如我所说，内斯特想亲自解释这一点，所以你将有幸见到他。该死的，至少试着让自己看起来很开心，即使你已经不开心了。}
#{3051}{}{What can you tell me about Nestor?}
{3051}{}{关于内斯特你能告诉我什么？}
#{3052}{}{Well, let me go to him.}
{3052}{}{好吧，让我去找他。}
#{3100}{}{Hey, aren't you the one who got Richie out of jail? Yeah, it's you, he told us about you. I should've recognized you from the start, but his prattle was so full of crap. Like, he thought we should pay him for his information about Uncle. Now the fool is already singing, free of charge. Nestor would have a job for you here. Not that freeing one donkey from jail made a big impression on any of us. However, there is no one else right now.}
{3100}{}{嘿，是你让里奇出狱的吗？是的，是你，他告诉我们你的事。我本该从一开始就认出你来的，但他的话全是废话。比如说，他觉得我们应该付钱给他关于叔叔的信息。现在傻子已经在免费唱歌了。内斯特会在这里给你找份工作。并不是说把一头驴从监狱里解救出来对我们每个人都有很大的影响。然而，现在没有其他人。}
#{3101}{}{And how about some reward for freeing Richie?}
{3101}{}{释放里奇的报酬怎么样？}
#{3102}{}{What is the deal?}
{3102}{}{怎么回事？}
#{3150}{}{I think I just heard wrong. Did I, or one of Nestor's people, ever ask you to get that troublemaker out of there? I did not! I don't know why you did it and I don't care either. You did not do it for us, so you will get nothing from us.}
{3150}{}{我想我听错了。我或者内斯特的人有没有让你把那个捣蛋鬼弄出来？我没有！我不知道你为什么这么做，我也不在乎。你不是为我们做的，所以你不会从我们那里得到什么。}
#{3151}{}{So, how about that work?}
{3151}{}{那工作怎么样？}
#{3200}{}{There are rumors about a bloke who talked our barricaded miners out of their little rebellion, and the description fits you quite well. Be that as it may, you're here just at the right time, and Nestor has a job for you. Even though, to me you're more suspicious than a supermutant in a whorehouse.}
{3200}{}{有传言说，有个家伙说服我们的路障矿工脱离他们的小叛乱，这个描述很适合你。不管怎样，你来得正是时候，内斯特给你找了份工作。尽管如此，对我来说，你比妓院里的超人更可疑。}
#{3201}{}{Yeah, it was me. How about some reward?}
{3201}{}{是的，是我。奖励怎么样？}
#{3202}{}{What is the matter?}
{3202}{}{怎么了？}
#{3250}{}{I think I just heard wrong. You want a reward for something no one asked you to do? And I know no one did. You should be glad that my foot will not visit all your sensitive spots, because Nestor usually isn't too happy when strangers sniff around the mines.}
{3250}{}{我想我听错了。你想因为没人叫你做的事得到报酬吗？我知道没人这么做。你应该高兴，我的脚不会访问你所有的敏感点，因为内斯特通常不太高兴时，陌生人嗅周围的地雷。}
#{3251}{}{So, how about that work?}
{3251}{}{那工作怎么样？}
#{3300}{}{There are rumors about some broad who talked our barricaded miners out of their little rebellion, and the description fits you quite well. Be that as it may, you're here just at the right time, and Nestor has a job for you. Even though, to me you're more suspicious than a supermutant in a whorehouse.}
{3300}{}{有传言说，有一些人说服我们的路障矿工走出他们的小叛乱，描述很适合你。不管怎样，你来得正是时候，内斯特给你找了份工作。尽管如此，对我来说，你比妓院里的超人更可疑。}
#{3301}{}{Yeah, it was me. How about some reward?}
{3301}{}{是的，是我。奖励怎么样？}
#{3302}{}{What is the matter?}
{3302}{}{怎么了？}
#{3350}{}{I think I just heard wrong. You want a reward for something no one asked you to do? And I know no one did. You should be glad that my foot will not visit all your sensitive spots, because Nestor usually isn't too happy when strangers sniff around the mines.}
{3350}{}{我想我听错了。你想因为没人叫你做的事得到报酬吗？我知道没人这么做。你应该高兴，我的脚不会访问你所有的敏感点，因为内斯特通常不太高兴时，陌生人嗅周围的地雷。}
#{3351}{}{So, how about that work?}
{3351}{}{那工作怎么样？}
#{3400}{}{You could've spilled that out to start with and save both of us precious time. I would tell you right away that there is no work for you here and you can be on your way. And never come back, preferably.}
{3400}{}{你本来可以把这些都说出来的，这样我们两个都能省下宝贵的时间。我马上告诉你，这里没有你的工作，你可以上路了。最好不要再回来了。}
#{3401}{}{OK.}
{3401}{}{好 啊。}
#{3450}{}{You could've spilled that out to start with and save both of us precious time. I would tell you right away that there is no work for you here and you can be on your way. And never come back, preferably.}
{3450}{}{你本来可以把这些都说出来的，这样我们两个都能省下宝贵的时间。我马上告诉你，这里没有你的工作，你可以上路了。最好不要再回来了。}
#{3451}{}{OK.}
{3451}{}{好 啊。}
#{3500}{}{Why are you sniffing around here again? Didn't I make it clear?! If you can't do things properly, better not even start with them. And you should especially avoid me! Your incompetence has caused us enough troubles already.}
{3500}{}{你为什么又在这里嗅来嗅去？我没说清楚吗？！如果你不能把事情做好，最好不要从一开始就做。你应该特别避开我！你的无能已经给我们带来了足够多的麻烦。}
#{3501}{}{I am here to challenge Nestor to fight me in the ring.}
{3501}{}{我是来挑战内斯特在拳击场上和我对抗的。}
#{3502}{}{I am here to challenge Nestor to fight me in the ring.}
{3502}{}{我是来挑战内斯特在拳击场上和我对抗的。}
#{3503}{}{Relax, I'll be on my way.}
{3503}{}{别紧张，我马上就来。}
#{3550}{}{Look whom we have here. Isn't this Mr. "I'm not interested in working for the most powerful man in Corath"? Oh, no, someone so stupid would likely blow up his own head a long time ago.}
{3550}{}{看看我们这里有谁。这不是“我对为科拉斯最有权势的人工作不感兴趣”先生吗？哦，不，这么蠢的人很可能早就炸了自己的头。}
#{3551}{}{I came to challenge Nestor to fight me in the ring.}
{3551}{}{我是来挑战内斯特在拳击场上和我比赛的。}
#{3552}{}{I changed my mind, I want the job.}
{3552}{}{我改变主意了，我想要这份工作。}
#{3553}{}{I'm not interested and that's final. Goodbye.}
{3553}{}{我不感兴趣，这是最后的决定。再见。}
#{3600}{}{I just heard YOU say that you want to work for Nestor. Could you please repeat it and real loud, so I can be sure I'm not imagining it?}
{3600}{}{我刚听到你说你想为内斯特工作。你能大声重复一遍吗？这样我就可以确定我不是在想象了？}
#{3601}{}{I WANT THE JOB FROM NESTOR!}
{3601}{}{我想要内斯特的工作！}
#{3602}{}{You know what? Forget it!}
{3602}{}{你知道吗？算了吧！}
#{3650}{}{[He smiled.] Oh yeah, you really did say it. Well, as I said before, Nestor wants to explain this personally, so you'll have the honor of meeting him. And at least try to pretend that you are happy about it, even after the initial excitement is past.}
{3650}{}{[他笑了]哦，是的，你真的说了。嗯，就像我之前说的，内斯特想亲自解释，所以你有幸见到他。即使最初的兴奋已经过去了，至少要假装你对此感到高兴。}
#{3651}{}{[He smiled.] Oh yeah, you really did say it. Well, as I said before, Nestor wants to explain this personally, so you'll have the honor of meeting him. And at least try to pretend that you are happy about it, even after the initial excitement is past.}
{3651}{}{[他笑了]哦，是的，你真的说了。嗯，就像我之前说的，内斯特想亲自解释，所以你有幸见到他。即使最初的兴奋已经过去了，至少要假装你对此感到高兴。}
#{3652}{}{What can you tell me about Nestor?}
{3652}{}{关于内斯特你能告诉我什么？}
#{3653}{}{Well, let me go to him then.}
{3653}{}{好吧，那我去找他。}
#{3700}{}{Look who we have here. Isn't this Ms. "I'm not interested in working for the most powerful man in Corath"? Oh, no, someone so stupid would likely blow up her own head a long time ago.}
{3700}{}{看看我们这里有谁。这不是“我对为科拉斯最有权势的人工作不感兴趣”女士吗？哦，不，这么蠢的人很可能早就炸了自己的头。}
#{3701}{}{I'm here to challenge Nestor to fight me in the ring.}
{3701}{}{我是来挑战内斯特在拳击场上和我对抗的。}
#{3702}{}{I changed my mind, I want the job.}
{3702}{}{我改变主意了，我想要这份工作。}
#{3703}{}{I'm not interested and that's final. Goodbye.}
{3703}{}{我不感兴趣，这是最后的决定。再见。}
#{3750}{}{Richie wound up here and babbled something about a reward for information. Now the dummy is singing for free. The reward belongs to you, here you go, 500 caps. Don't make that face at me, I never said it would be a fortune. After all, it wasn't a difficult job. As far as the revolt that Richie tried to spark...}
{3750}{}{里奇突然来到这里，唠叨着要悬赏情报。现在假人免费唱歌。奖赏属于你，给你，500顶瓶盖。别对我做鬼脸，我从没说过那会是一笔财富。毕竟，这不是一个困难的工作。至于里奇试图激起的反抗。。。}
#{3751}{}{Yes?}
{3751}{}{对？}
#{3800}{}{Well, it broke out. The miners decided that instead of working they will get themselves killed and cause trouble for Nestor. Not only we lost mine workers, but several capable men too. And the worst of it all is that the cops are mad at Nestor for having to interfere.}
{3800}{}{好吧，它爆发了。矿工们决定不工作，他们会自杀，给内斯特制造麻烦。我们不仅失去了矿工，还失去了几个能干的人。最糟糕的是警察对内斯特的干涉很生气。}
#{3801}{}{So?}
{3801}{}{所以呢？}
#{3850}{}{There are rumors about a bloke who talked our barricaded miners out of their little rebellion, and the description fits you quite well. Be that as it may, Nestor himself would have another job for you, if you're interested. And I can't think of one good reason why you shouldn't be interested.}
{3850}{}{有传言说，有个家伙说服我们的路障矿工脱离他们的小叛乱，这个描述很适合你。不管怎样，如果你感兴趣的话，内斯特本人会给你另一份工作的。我想不出一个好的理由让你不感兴趣。}
#{3851}{}{There are rumors about a broad who talked our barricaded miners out of their little rebellion, and the description fits you quite well. Be that as it may, Nestor himself would have another job for you, if you're interested. And I can't think of one good reason why you shouldn't be interested.}
{3851}{}{有传言说，有一个大家伙说服我们的路障矿工走出他们的小叛乱，描述很适合你。不管怎样，如果你感兴趣的话，内斯特本人会给你另一份工作的。我想不出一个好的理由让你不感兴趣。}
#{3852}{}{Yes, I talked them out of their revolt. How about some reward?}
{3852}{}{是的，我劝他们不要反抗。奖励怎么样？}
#{3853}{}{Yes, I talked them out of their revolt. How about some reward?}
{3853}{}{是的，我劝他们不要反抗。奖励怎么样？}
#{3854}{}{I'm in.}
{3854}{}{我加入了。}
#{3855}{}{Not interested.}
{3855}{}{不感兴趣。}
#{3900}{}{I think I just heard wrong. You want a reward for something no one asked you to do? And I know no one did. You should be glad that my foot will not visit all of your most sensitive spots, because Nestor usually isn't too happy when strangers sniff around the mines.}
{3900}{}{我想我听错了。你想因为没人叫你做的事得到报酬吗？我知道没人这么做。你应该高兴，我的脚不会访问所有你最敏感的地方，因为内斯特通常是不太高兴时，陌生人嗅周围的地雷。}
#{3901}{}{I think I just heard wrong. You want a reward for something no one asked you to do? And I know no one did. You should be glad that my foot will not visit all of your most sensitive spots, because Nestor usually isn't too happy when strangers sniff around the mines.}
{3901}{}{我想我听错了。你想因为没人叫你做的事得到报酬吗？我知道没人这么做。你应该高兴，我的脚不会访问所有你最敏感的地方，因为内斯特通常是不太高兴时，陌生人嗅周围的地雷。}
#{3902}{}{Ok then, what about the other job? I'm interested.}
{3902}{}{好吧，那另一份工作呢？我很感兴趣。}
#{3903}{}{In that case, I'm not interested in any more work.}
{3903}{}{那样的话，我对更多的工作不感兴趣了。}
#{3950}{}{You really are slower than a one-legged gecko, or did you just decide to have your way with some whore before doing your work? Actually, in the second case it wouldn't take you that long either. Someone already finished Richie off in the jail! No doubt it was Uncle making sure his little birdie wouldn't sing ever again. As far as the revolt that Richie tried to spark goes...}
{3950}{}{你真的比一条腿的壁虎还慢，还是你在工作前就决定和妓女混在一起了？实际上，在第二种情况下，你也不会花那么长时间。有人已经把里奇关进监狱了！毫无疑问，是叔叔确保他的小鸟不再唱歌了。至于里奇试图激起的反抗。。。}
#{3951}{}{You really are slower than a one-legged gecko, or did you just decide to get drunk before doing your work? Actually, in the second case it wouldn't take you that long either. Someone already finished Richie off in the jail! No doubt it was Uncle making sure his little birdie wouldn't sing ever again. As far as the revolt that Richie tried to spark goes....}
{3951}{}{你真的比一条腿的壁虎还慢，还是你只是决定在工作前先喝醉？实际上，在第二种情况下，你也不会花那么长时间。有人已经把里奇关进监狱了！毫无疑问，是叔叔确保他的小鸟不再唱歌了。至于里奇试图激起的反抗。。。。}
#{3952}{}{Yes?}
{3952}{}{对？}
#{4000}{}{Do I look like someone who publicly prattles about Nestor's private affairs? I don't! That's because I don't do it! The stranger is not one of your worries. He is no one's worry now.}
{4000}{}{我看起来像是公开谈论内斯特私事的人吗？我不！那是因为我不做！陌生人不是你的烦恼之一。他现在没人担心了。}
#{4001}{}{OK.}
{4001}{}{好 啊。}
#{4050}{}{Good job in the ring, it was about time that someone squashed Cedrick's face. Now Uncle's time has come. As you can see, suddenly he finds it hard to comply with Corath's laws. It was to be expected. [He grins.]}
{4050}{}{干得好，是时候有人压扁塞德里克的脸了。现在叔叔的时候到了。如你所见，他突然发现很难遵守科拉斯的法律。这是意料之中的。[他咧嘴一笑。]}
#{4051}{}{The police will take care of that, won't they?}
{4051}{}{警察会处理的，不是吗？}
#{4052}{}{Egh... yaaaaa.}
{4052}{}{呃。。。是啊。}
#{4100}{}{Nestor, being a responsible and dutiful citizen, sent me to help the police with maintaining order. If you join us, you'll get extra dough from Nestor. I don't think you're going to be dumb enough to decline; the history of Corath is being written here today.}
{4100}{}{内斯特是一个负责任、尽职尽责的公民，派我来帮助警察维持秩序。如果你加入我们，你会从内斯特那里得到额外的钱。我不认为你会蠢到拒绝；科拉斯的历史今天就写在这里。}
#{4101}{}{Nestor, being a responsible and dutiful citizen, sent me to help the police with maintaining order. If you join us, you'll get extra dough from Nestor. I don't think you're going to be dumb enough to decline; the history of Corath is being written here today.}
{4101}{}{内斯特是一个负责任、尽职尽责的公民，派我来帮助警察维持秩序。如果你加入我们，你会从内斯特那里得到额外的钱。我不认为你会蠢到拒绝；科拉斯的历史今天就写在这里。}
#{4102}{}{I'm in.}
{4102}{}{我加入了。}
#{4103}{}{I'm gonna stay out of it.}
{4103}{}{我不会插手的。}
#{4150}{}{Sure, first shots are about to be fired and you're suddenly shitting your pants like a toddler... As you wish, come to me when I'm done here and I'll give you your pay. But now I have to blow away a fatty.}
{4150}{}{当然，第一枪就要开了，你突然像个小孩一样大便。。。如你所愿，等我来了就来找我，我会给你报酬的。但现在我得吹走一个胖子。}
#{4151}{}{Sure, first shots are about to be fired and you're suddenly shitting your pants like a toddler... As you wish, come to me when I'm done here and I'll give you your pay. But now I have to blow away a fatty.}
{4151}{}{当然，第一枪就要开了，你突然像个小孩一样大便。。。如你所愿，等我来了就来找我，我会给你报酬的。但现在我得吹走一个胖子。}
#{4152}{}{OK.}
{4152}{}{好 啊。}
#{4200}{}{Ok, let's blow that fatso away. Try to be a little useful and don't get in my way.}
{4200}{}{好吧，让我们把那个胖子吹走。尽量有用一点，别挡我的路。}
#{4201}{}{Ok, let's blow that fatso away. Try to be a little useful and don't get in my way.}
{4201}{}{好吧，让我们把那个胖子吹走。尽量有用一点，别挡我的路。}
#{4202}{}{No worries.}
{4202}{}{别担心。}
#{4203}{}{Ok, let's blow that fatso away. Cedrick really beat you up well, you're hard to look upon. This will get you going again [he took out an ultra stimpak and injected it in your vein without asking], and you are at least a little useful.}
{4203}{}{好吧，让我们把那个胖子吹走。塞德里克真的打了你一顿，你真难看。这会让你重新开始（他不请自来地拿出一个ultra stimpak注射到你的静脉中），你至少有一点用处。}
#{4204}{}{Ok, let's blow that fatso away. Cedrick really beat you up well, you're hard to look upon. This will get you going again [he took out an ultra stimpak and injected it in your vein without asking], and you are at least a little useful.}
{4204}{}{好吧，让我们把那个胖子吹走。塞德里克真的打了你一顿，你真难看。这会让你重新开始（他不请自来地拿出一个ultra stimpak注射到你的静脉中），你至少有一点用处。}
#{4250}{}{I see that your courage extends only to collecting the money. Nestor left 2500 caps for you for fighting in the ring [he gives them to you], but he doesn't want to see you here again. The thing is, he doesn't like cravens and neither do I.}
{4250}{}{我知道你的勇气只限于收钱。内斯特给你留下了2500顶瓶盖，让你在拳击场上战斗（他给了你），但他不想再看到你在这里。问题是，他不喜欢克雷文，我也不喜欢。}
#{4251}{}{Keep your wisdoms to yourself. Bye.}
{4251}{}{把你的智慧留给自己。再见。}
#{4300}{}{What else do you want? You got paid for your work and there is no need for you to poison my air with your foul smell.}
{4300}{}{你还想要什么？你的工作得到了报酬，你没有必要用你的臭味毒害我的空气。}
#{4301}{}{What else do you want? You got paid for your work and there is no need for you to poison my air with your foul smell.}
{4301}{}{你还想要什么？你的工作得到了报酬，你没有必要用你的臭味毒害我的空气。}
#{4302}{}{Nice talking to you... NOT!}
{4302}{}{很高兴和你谈话。。。不！}
#{4303}{}{Uff.}
{4303}{}{不明飞行物。}
#{4350}{}{Uncle will finally get to rest six feet under. It made my day when the halfwit fatso refused to leave town. Otherwise I would have to chase him from one stinky hole to another. Nestor would never let him live and he couldn't rely on anyone else but me not to fuck up such an important task. Now, Nestor is beaming with joy, well, at least to the extent he is capable of it. He wants to hand you the reward personally, go see him.}
{4350}{}{叔叔终于可以在六英尺深的地方休息了。那个笨蛋胖子不肯出城，这使我很高兴。否则我就得把他从一个臭洞追到另一个臭洞。内斯特决不会让他活下来，他不能指望除了我以外的任何人不会把这么重要的任务搞砸。现在，内斯特喜气洋洋，嗯，至少在他能做到的程度上。他想亲自给你报酬，去见他。}
#{4351}{}{OK.}
{4351}{}{好 啊。}
#{4400}{}{Hey, it's true that you did quite some good work for Nestor and you were with me during the assault on Uncle, but none of that means that we will be buddies from now on, or anything.}
{4400}{}{嘿，你确实为内斯特做了不少不错的工作，而且在袭击叔叔的时候你也和我在一起，但这些都不意味着我们从现在起就成了好朋友，或者别的什么。}
#{4401}{}{Hey, it's true that you did quite some good work for Nestor and you were with me during the assault on Uncle, but none of that means that we will be buddies from now on, or anything.}
{4401}{}{嘿，你确实为内斯特做了不少不错的工作，而且在袭击叔叔的时候你也和我在一起，但这些都不意味着我们从现在起就成了好朋友，或者别的什么。}
#{4402}{}{I want to talk to Nestor.}
{4402}{}{我想和内斯特谈谈。}
#{4403}{}{Ok, I'm leaving.}
{4403}{}{好的，我要走了。}
#{4450}{}{I don't know what for, but be my guest. I'm not stopping you. Nestor said you can visit him anytime. But I'm sure he will think better of his rash words, if you visit too often.}
{4450}{}{我不知道为什么，但请你做我的客人。我不会阻止你的。内斯特说你可以随时来看他。但我相信，如果你经常去看他，他会对自己鲁莽的话想得更好些的。}
#{4451}{}{No worries.}
{4451}{}{别担心。}
#{5000}{}{Let's go, we're going ahead. These cowards seem like they're planning to make a camp here before going further.}
{5000}{}{我们走，我们走。这些胆小鬼似乎打算在这里扎营，然后再继续前进。}
#{5100}{}{Hey greaseball, don't hide, I'm coming for you!}
{5100}{}{嘿，小胖子，别躲，我来找你！}
