#{100}{}{You see a shopkeeper.}
{100}{}{你看到一个店主。}
#{150}{}{You see the shopkeeper Coffield.}
{150}{}{你看到店主科菲尔了。}
#{200}{}{You see a local shopkeeper. He looks bored.}
{200}{}{你看到一个当地的店主。他看起来很无聊。}
#{250}{}{You see the shopkeeper Davis Coffield. He is wearily staring into the empty air.}
{250}{}{你看到店主戴维斯·科菲尔了。他疲倦地凝视着空荡荡的空气。}
#{300}{}{Don't touch it!}
{300}{}{别碰它！}
#{400}{}{I'm gonna run a bullet through your head you trash!}
{400}{}{我要用子弹射穿你的头你这个废物！}
#{401}{}{I'm gonna run a bullet through your head you trash!}
{401}{}{我要用子弹射穿你的头你这个废物！}
#{500}{}{What do you want from me?}
{500}{}{你想从我这里得到什么？}
#{501}{}{Who are you?}
{501}{}{你是谁？}
#{502}{}{Depends on what you're offering.}
{502}{}{取决于你提供什么。}
#{503}{}{I want to have a look at your goods.}
{503}{}{我想看看你们的货物。}
#{504}{}{Nothing at all, actually. Goodbye.}
{504}{}{实际上，什么都没有。再见。}
#{505}{}{Wa-want?!}
{505}{}{你想要什么？！}
#{506}{}{Hugh, go outs.}
{506}{}{休，出去。}
#{550}{}{I'm Davis Coffield, the owner of the only shop in Corath - this shop. So, do you plan to buy anything or is that all? I haven't got time for chatter.}
{550}{}{我是戴维斯·科菲尔，科拉斯唯一一家店的老板——这家店。那么，你打算买什么东西还是就这些？我没时间闲聊了。}
#{551}{}{Depends on what you're offering.}
{551}{}{取决于你提供什么。}
#{552}{}{I want to have a look at your goods.}
{552}{}{我想看看你们的货物。}
#{553}{}{Me neither. Bye Davis.}
{553}{}{我也是。再见，戴维斯。}
#{600}{}{I'm selling all kinds of stuff - armor, weapons, ammunition, medical supplies and various stimulants. I get most of my goods from Sedit, but Uncle arranged a supplier from Albuquerque for a share in my profits. Everyone will certainly find something useful here.}
{600}{}{我卖各种各样的东西-盔甲，武器，弹药，医疗用品和各种兴奋剂。我的大部分货物都是从塞迪特买来的，但是叔叔从阿尔伯克基安排了一个供应商来分享我的利润。大家一定会在这里找到有用的东西。}
#{601}{}{That's what I hope for. Can I have a look?}
{601}{}{这就是我的希望。我能看看吗？}
#{602}{}{I see. And who are you, actually?}
{602}{}{我懂了。你到底是谁？}
#{603}{}{I have to go. Bye.}
{603}{}{我得走了。再见。}
#{650}{}{This is my offer.}
{650}{}{这是我的提议。}
#{651}{}{[Barter.]}
{651}{}{[易货]}
#{700}{}{Is that all?}
{700}{}{就这些吗？}
#{701}{}{I want to have a look at your goods again.}
{701}{}{我想再看看你们的货。}
#{702}{}{Thanks. Goodbye.}
{702}{}{谢谢。再见。}
#{750}{}{I have no time for this. Do you want to see my goods or not?}
{750}{}{我没时间做这个。你要不要看我的货？}
#{751}{}{Yaaay!}
{751}{}{耶！}
#{752}{}{N-no!}
{752}{}{不，不！}
#{800}{}{Now you can go.}
{800}{}{现在你可以走了。}
#{801}{}{Go!}
{801}{}{快走！}
#{850}{}{In that case, piss off idiot!}
{850}{}{那样的话，白痴滚开！}
#{851}{}{Grrrr... Vrrr!}
{851}{}{Grrrr。。。Vrrr！}
#{852}{}{[Leave.]}
{852}{}{[离开]}
#{900}{}{What do you want?}
{900}{}{你想要什么？}
#{901}{}{Who are you?}
{901}{}{你是谁？}
#{902}{}{Depends on what you're offering.}
{902}{}{取决于你提供什么。}
#{903}{}{I want to see your goods.}
{903}{}{我想看看你的货。}
#{904}{}{Nothing at all. Bye.}
{904}{}{什么都没有。再见。}
#{905}{}{Me wanna?!}
{905}{}{我想要什么？！}
#{906}{}{Stuffs!}
{906}{}{东西！}
#{907}{}{Huh, away.}
{907}{}{啊，走开。}
