#{100}{}{You see a miner.}
{100}{}{你看到一个矿工。}
#{200}{}{You see a miner. He looks exhausted.}
{200}{}{你看到一个矿工。他看起来筋疲力尽。}
#{300}{}{I'm off-duty, so leave me alone.}
{300}{}{我下班了，别烦我。}
#{301}{}{I want to enjoy my time off. In peace.}
{301}{}{我想好好享受我的假期。在和平中。}
#{302}{}{Leave me alone.}
{302}{}{别管我。}
#{303}{}{I'm really tired...}
{303}{}{我真的很累。。。}
#{304}{}{Damn, my shift starts again in a few moments.}
{304}{}{妈的，我马上就要轮班了。}
#{305}{}{Do you want to toil like a miner or what?}
{305}{}{你想像矿工一样辛苦吗？}
#{306}{}{I'm so thirsty I'd drink all of Penep's beer supply.}
{306}{}{我渴得连佩内普的啤酒都喝了。}
#{307}{}{Oh hi there! Once the shift is over I always like to see a good fight.}
{307}{}{哦，你好！轮班结束后，我总是喜欢看一场精彩的比赛。}
#{308}{}{Have you been to Wanda's brothel yet? It's worth it.}
{308}{}{你去过万达的妓院了吗？这是值得的。}
#{309}{}{Have you been to Wanda's brothel yet? It's worth it.}
{309}{}{你去过万达的妓院了吗？这是值得的。}
#{310}{}{You don't work at the brothel, do you? I'd certainly pay for you, beautiful.}
{310}{}{你不是在妓院工作吧？我当然会为你付钱的，美女。}
#{311}{}{Shit, I need a fuck bad, and all I can afford is Dolly.}
{311}{}{妈的，我他妈的很需要，我能负担得起的只有多莉。}
#{312}{}{Damn, that Marylin is really good.}
{312}{}{妈的，马里林真不错。}
#{313}{}{Have you tried it with Susan yet? She's really wild, if you know what I mean.}
{313}{}{你和苏珊试过了吗？如果你知道我的意思的话，她真的很野。}
#{314}{}{I really like fucking Trixie, she's a real pussycat.}
{314}{}{我真的很喜欢他妈的崔茜，她真是个小猫咪。}
#{315}{}{Abby, she's really something, let me tell you.}
{315}{}{艾比，她真了不起，让我告诉你。}
#{316}{}{Abby's working at the brothel with her sister Valery now. Both of them are really something and you can have them together! I mean, if you can afford it.}
{316}{}{艾比现在和她妹妹瓦莱里在妓院工作。他们两个都是真正的东西，你可以有他们在一起！我是说，如果你买得起的话。}
#{317}{}{They really kicked our asses because of the strike. Oh well, best not to think about it.}
{317}{}{他们真的因为罢工踢了我们的屁股。哦，好吧，最好别想了。}
#{318}{}{Haven't you heard? We're on strike.}
{318}{}{你没听说吗？我们在罢工。}
#{319}{}{The conditions in the mines are horrible.}
{319}{}{矿井里的条件糟透了。}
#{320}{}{Our wages are terrible, that's why we're striking.}
{320}{}{我们的工资很低，这就是我们罢工的原因。}
#{321}{}{Nestor is a bastard.}
{321}{}{内斯特是个混蛋。}
#{322}{}{Working in the mines was always pretty shitty.}
{322}{}{在矿井里工作总是很差劲。}
#{323}{}{I hope the strike doesn't last too long, I need the money.}
{323}{}{我希望罢工不要持续太久，我需要钱。}
#{324}{}{We shall prevail, Nestor must back down in the end.}
{324}{}{我们会胜利的，内斯特最终必须让步。}
#{325}{}{Haven't you heard? We're on strike.}
{325}{}{你没听说吗？我们在罢工。}
#{326}{}{I wonder what will change now.}
{326}{}{我不知道现在会有什么变化。}
#{327}{}{I'm not sorry for Nestor.}
{327}{}{我不为内斯特难过。}
#{328}{}{Nothing ever changes around here.}
{328}{}{这里什么都没变。}
#{329}{}{Uncle is just like Nestor used to be.}
{329}{}{叔叔和内斯特以前一样。}
