#{100}{}{You see a prostitute.}
{100}{}{你看到一个妓女。}
#{150}{}{You see Marylin.}
{150}{}{你看马里林。}
#{200}{}{You see a prostitute. The first thing anyone notices about her are her gorgeous breasts.}
{200}{}{你看到一个妓女。人们首先注意到她的是她美丽的胸部。}
#{250}{}{You see Marylin, being her usual provocative self.}
{250}{}{你看，玛丽琳，像往常一样挑衅。}
#{300}{}{We can go once more straight away, if you pay.}
{300}{}{如果你付钱的话，我们可以马上再去一次。}
#{301}{}{Baby, you have to go. There's another customer waiting.}
{301}{}{宝贝，你得走了。还有一个顾客在等。}
#{302}{}{You hog you, you sure know how to please a woman.}
{302}{}{你知道怎样取悦一个女人。}
#{303}{}{You do like doing it with a woman as I do, don't you honey?}
{303}{}{你和我一样喜欢和女人在一起，不是吗，亲爱的？}
#{304}{}{You want me, don't you? Well, forget it.}
{304}{}{你想要我，不是吗？算了吧。}
#{305}{}{You want me, don't you? Well, forget it.}
{305}{}{你想要我，不是吗？算了吧。}
#{500}{}{Hi, my name is Marylin. You like what you see? [She strokes her breasts.] Want to feel them? Or something more?}
{500}{}{嗨，我叫马里林。你喜欢你看到的吗？[她抚摸她的乳房]想摸一下吗？还是别的什么？}
#{501}{}{Hi, my name is Marylin. You like what you see? [She strokes her breasts.] Want to feel them? Or something more?}
{501}{}{嗨，我叫马里林。你喜欢你看到的吗？[她抚摸她的乳房]想摸一下吗？还是别的什么？}
#{502}{}{More?}
{502}{}{更多？}
#{503}{}{Um... I'll think about it. Bye.}
{503}{}{嗯……我会考虑的。再见。}
#{550}{}{[She approaches you and whispers in your ear.] I'll do you like no other. You can fuck me any way you like, I'm open to anything. [She is so close you can almost feel the touch of her breasts.]}
{550}{}{[她走近你，在你耳边低语]我不会像其他人那样对你。你想干什么就干什么，我什么都愿意干。[她离你很近，你几乎能感觉到她胸部的触感。]}
#{551}{}{[She approaches you and whispers in your ear.] We can do each other any way you like, I'm open to anything. [She is so close you can almost feel her breasts brushing against yours.]}
{551}{}{[她走近你，在你耳边窃窃私语]我们可以做任何你想做的事，我对任何事都敞开心扉。[她离你太近了，你几乎能感觉到她的乳房在你的乳房上摩擦。]}
#{552}{}{[Touch those incredible breasts.]}
{552}{}{[触摸这不可思议的乳房！]}
#{553}{}{Well... I better be going. See you, Marylin.}
{553}{}{好……我最好走了。再见，马里林。}
#{600}{}{[She deftly pushes you away.] Not so fast, pretty boy. If you want to have fun, you must pay Wanda first.}
{600}{}{[她巧妙地把你推开]别那么快，帅哥。如果你想玩得开心，你必须先付钱给万达。}
#{601}{}{[She deftly pushes you away.] Not so fast, princess. If you want to have fun, you must pay Wanda first.}
{601}{}{[她巧妙地把你推开]别那么快，公主。如果你想玩得开心，你必须先付钱给万达。}
#{602}{}{Maybe I will.}
{602}{}{也许我会的。}
#{603}{}{Oh no you don't. You can't stop now you bitch!}
{603}{}{哦，不，你不能停下来，你这个婊子！}
#{650}{}{Honey, I told you, you must pay for me first. I'll wait. [She licks her luscious lips.]}
{650}{}{亲爱的，我告诉过你，你必须先为我付钱。我会等的。[她舔着甜美的嘴唇。]}
#{651}{}{Maybe I will.}
{651}{}{也许我会的。}
#{700}{}{[She puts her finger on your lips.] You don't have to say anything, I know you liked it. I liked it too. But if you want to go again, you must pay first.}
{700}{}{[她把手指放在你的嘴唇上]你什么都不用说，我知道你喜欢。我也喜欢。但是如果你想再去，你必须先付钱。}
#{701}{}{[Lick her finger.] We'll see.}
{701}{}{[舔她的手指]我们拭目以待。}
