#{100}{}{You see a man.}
{100}{}{你看到一个男人。}
#{150}{}{You see Melkyr.}
{150}{}{你看到梅尔凯尔了。}
#{200}{}{You see a common local elderly man.}
{200}{}{你看到一个普通的当地老人。}
#{250}{}{You see old Melkyr. He's watching the ring.}
{250}{}{你看到老梅尔凯尔了。他在看戒指。}
#{300}{}{Damn, that must have hurt!}
{300}{}{该死，一定很疼！}
#{350}{}{When's the next fight?}
{350}{}{下一场比赛是什么时候？}
#{351}{}{Howdy. How's it going?}
{351}{}{你好。怎么样？}
#{352}{}{I saw you fight. You were pretty good.}
{352}{}{我看见你打架了。你做得很好。}
#{353}{}{Thanks to you there's plenty entertainment around here.}
{353}{}{多亏了你，这里有很多娱乐活动。}
#{354}{}{Your friend is unstoppable in the ring.}
{354}{}{你的朋友在拳击场上势不可挡。}
#{355}{}{Your friend was really good in the ring.}
{355}{}{你的朋友在拳击场上很出色。}
#{356}{}{I'm sorry you lost your friend.}
{356}{}{很抱歉你失去了朋友。}
#{357}{}{I'm sorry you lost your friend.}
{357}{}{很抱歉你失去了朋友。}
#{358}{}{That was one hell of a performance with Blaster.}
{358}{}{那是一个地狱的表现与爆炸机。}
#{359}{}{That was one hell of a performance with Cedrick.}
{359}{}{塞德里克的表演真是太棒了。}
#{360}{}{I saw you fight. You were pretty good.}
{360}{}{我看见你打架了。你做得很好。}
#{361}{}{I'm sorry you lost your friend.}
{361}{}{很抱歉你失去了朋友。}
#{362}{}{I'm sorry you lost your friend.}
{362}{}{很抱歉你失去了朋友。}
#{400}{}{The law will take care of you!}
{400}{}{法律会照顾你的！}
#{500}{}{Who do we have here? Not another stranger! [The old man smirks.] I sincerely hope you'll be luckier than the last one.}
{500}{}{我们这里有谁？不是另一个陌生人！我真诚地希望你比上一个幸运。}
#{501}{}{Who are you talking about?}
{501}{}{你在说谁？}
#{502}{}{Spare me your babble, old man.}
{502}{}{别再唠叨了，老头子。}
#{503}{}{[Ignore him.]}
{503}{}{[别理他。]}
#{504}{}{Huh?!}
{504}{}{呵呵？！}
#{550}{}{[He points to the ring and smirks again.] About that poor dead guy. He came to the city and as soon as he got his bearings, he started making trouble. Death was the only thing coming to him.}
{550}{}{[他指着戒指又笑了起来]关于那个可怜的死人。他来到这个城市，一有了方向，就开始制造麻烦。他只有死亡。}
#{551}{}{Why did he die in the ring of all places?}
{551}{}{他为什么死在所有的地方？}
#{552}{}{Who was that supermutant?}
{552}{}{那个超级变种人是谁？}
#{553}{}{I see. I have to go now. Bye.}
{553}{}{我懂了。我得走了。再见。}
#{600}{}{As you wish. But the next time, better watch your mouth. Or you'll end up in there pretty soon. [He points to the ring.]}
{600}{}{如你所愿。但下次，最好小心你的嘴。否则你很快就会死在那里。[他指着戒指。]}
#{601}{}{In the ring?}
{601}{}{在拳击场上？}
#{602}{}{Oh shut up, daddy.}
{602}{}{哦，闭嘴，爸爸。}
#{650}{}{We have one just law here. If two people have a dispute, they fight to the death in the ring and there they determine who was in the right.}
{650}{}{我们这里有一条公正的法律。如果两个人有争执，他们会在拳击场上决一死战，并在那里决定谁是正确的。}
#{651}{}{An interesting rule. But what about that supermutant?}
{651}{}{一条有趣的规则。但那个超级变异体呢？}
#{652}{}{I see. Have you ever seen this talisman before? [Show him.]}
{652}{}{我懂了。你以前见过这个护身符吗？[给他看。]}
#{653}{}{Thanks for the information. Bye.}
{653}{}{谢谢你的消息。再见。}
#{700}{}{That heap of mutated muscle was Blaster. Nestor uses him as his personal meatgrinder, killing every challenger in the ring. Uncle must really be pissed. It was actually Uncle, you know, who sent this latest suicide-man against Blaster. Uncle and Nestor have been at it for very long now.}
{700}{}{那堆变异的肌肉是爆炸机。内斯特把他当作自己的绞肉机，杀死了拳击场上所有的挑战者。叔叔一定很生气。实际上是叔叔，你知道的，派了这个最新的自杀者去对付爆炸机。叔叔和内斯特已经干了很长时间了。}
#{701}{}{Tell me more about those two.}
{701}{}{告诉我更多关于那两个人的事。}
#{702}{}{I'll go now. Bye.}
{702}{}{我现在就去。再见。}
#{750}{}{Yeah, right there. You know, we have one just rule here. If two people have a dispute, they fight to the death in the ring and there they determine who was in the right. And you look like the kind of person who provokes disputes wherever you go.}
{750}{}{是的，就在那里。你知道，我们这里只有一条规则。如果两个人有争执，他们会在拳击场上决一死战，并在那里决定谁是正确的。你看起来是那种无论走到哪里都会挑起争端的人。}
#{751}{}{Pardon my rudeness. But pray tell me, who was that supermutant.}
{751}{}{请原谅我的无礼。但请告诉我，谁是那个超级变种人。}
#{752}{}{Well you saw right through me, didn't you. Bye you mongrel.}
{752}{}{你看穿了我，不是吗。再见，杂种。}
#{800}{}{Nestor owns the local iron ore mine. He's a degenerate fucking dwarf, just as ugly as his supermutant. But don't let his looks fool you. He knows exactly what he wants, and he'll walk over dead bodies to get it. The whole city is afraid of him. And Uncle? Well, he's a former caravaneer, now he trades with the caravans. He's trying to put up an image of a good guy, but frankly I'm too old to believe this game of his any more. They hate each other to the grave, and if it weren't for the sheriff and the Law of the Ring, they would have murdered each other a long time ago.}
{800}{}{内斯特拥有当地的铁矿。他是一个堕落的侏儒，和他的超级毛驴一样丑陋。但别让他的外表骗了你。他很清楚自己想要什么，他会走过尸体去得到它。整个城市都害怕他。叔叔呢？他以前是商队的，现在跟商队做生意。他想树立一个好人的形象，但坦率地说，我太老了，不能再相信他的这个游戏了。他们恨对方到死，如果不是警长和魔戒的法律，他们早就互相谋杀了。}
#{801}{}{And why do they solve their quarrels in the ring of all the places?}
{801}{}{他们为什么在各地的环城解决争吵呢？}
#{802}{}{I see. Say, have you ever seen a talisman like this before? [Show him.]}
{802}{}{我懂了。喂，你以前见过这样的护身符吗？[给他看。]}
#{803}{}{I have to go now. Bye.}
{803}{}{我得走了。再见。}
#{850}{}{Sorry, this is the first time I've ever seen a thing like that. What I can tell you is that it's certainly not from the local mine. I used to work there for donkey's years, and I know the mine never yielded anything like this quality of metal.}
{850}{}{对不起，这是我第一次看到这样的东西。我能告诉你的是，它肯定不是从当地的矿山。我以前在那里干了好几年，我知道矿里从来没有产出过这种质量的金属。}
#{851}{}{Thanks for the information. Bye.}
{851}{}{谢谢你的消息。再见。}
#{900}{}{[He smirks even more.] Seems like I can't have much of a chat with you, eh? In that case we'll have to part. But before we do, a little advice. Stay out of trouble, boy, and stay out of the ring. This city is more dangerous than meets the eye.}
{900}{}{[他笑得更厉害了]看来我不能和你多聊了，嗯？那样的话，我们只好分手了。但在此之前，我有一点建议。别惹麻烦，孩子，别碰拳击场。这个城市比我们想象的要危险。}
#{901}{}{[He smirks even more.] Seems like I can't have much of a chat with you, eh? In that case we'll have to part. But before we do, a little advice. Stay out of trouble, girl, and stay out of the ring. This city is more dangerous than meets the eye.}
{901}{}{[他笑得更厉害了]看来我不能和你多聊了，嗯？那样的话，我们只好分手了。但在此之前，我有一点建议。别惹麻烦，姑娘，别碰拳击场。这个城市比我们想象的要危险。}
#{902}{}{Ugh? I go.}
{902}{}{呃？我走了。}
