#{100}{}{You see a busy man.}
{100}{}{你看到一个大忙人。}
#{150}{}{You see Morton the accountant.}
{150}{}{你看会计莫顿。}
#{200}{}{You see an overworked, middle-aged man. He seems deeply immersed in some paperwork.}
{200}{}{你看到一个过度劳累的中年人。他似乎沉浸在一些文书工作中。}
#{250}{}{You see Morton the accountant. He is totally focused on his work.}
{250}{}{你看会计莫顿。他全神贯注于工作。}
#{300}{}{I'll need to recalculate these figures.}
{300}{}{我需要重新计算这些数字。}
#{301}{}{Now where did I put that report?}
{301}{}{我把报告放哪儿了？}
#{302}{}{The books must correspond, down to the last cap.}
{302}{}{这些书必须一致，一直到最后一个封顶。}
#{303}{}{Leave me alone, you thug!}
{303}{}{别管我，你这个暴徒！}
#{304}{}{I have no more to say to you.}
{304}{}{我没什么好说的了。}
#{305}{}{Sorry, I can't understand you.}
{305}{}{对不起，我听不懂你的话。}
#{306}{}{Come back when you're feeling better.}
{306}{}{当你感觉好些的时候再来。}
#{307}{}{Get out of my sight you damn thief!}
{307}{}{滚开，你这个该死的小偷！}
#{308}{}{Sorry, but I do need to work.}
{308}{}{对不起，我确实需要工作。}
#{500}{}{Hmm... Good day. [He stops working and looks at you with distraction.] I'm Morton. I'm the accountant for the iron ore trade. Is there anything I can do for you? Oh, and please be brief. I have a ton of things I need to finish today.}
{500}{}{隐马尔可夫模型。。。很好的一天。[他停止工作，心烦意乱地看着你]我是莫顿。我是铁矿石贸易的会计。有什么需要我帮忙的吗？哦，请简短一点。我今天有很多事情要完成。}
#{501}{}{Hmm... Good day. [He stops working and looks at you with distraction.] I'm Morton. I'm the accountant for the iron ore trade. Is there anything I can do for you? Oh, and please be brief. I have a ton of things I need to finish today.}
{501}{}{隐马尔可夫模型。。。很好的一天。[他停止工作，心烦意乱地看着你]我是莫顿。我是铁矿石贸易的会计。有什么需要我帮忙的吗？哦，请简短一点。我今天有很多事情要完成。}
#{502}{}{I see you are a busy man. What is it you do here exactly?}
{502}{}{我看你是个大忙人。你到底在这里干什么？}
#{503}{}{Can you answer a few questions about Corath for me?}
{503}{}{你能回答我几个关于科拉斯的问题吗？}
#{504}{}{Nothing that I know of. Goodbye, Morton.}
{504}{}{我什么都不知道。再见，莫顿。}
#{505}{}{Ughagh?!}
{505}{}{啊？！}
#{550}{}{I doubt it would interest you. [He forms a small smile.] My job isn't very exciting. It would only bore you.}
{550}{}{我怀疑你会感兴趣。[他微微一笑]我的工作不太令人兴奋。那只会让你厌烦。}
#{551}{}{Oh come on, I'm all ears.}
{551}{}{别这样，我洗耳恭听。}
#{552}{}{I see. Well, in that case I just have a few questions about the city.}
{552}{}{我懂了。好吧，那样的话，我就有几个关于这个城市的问题。}
#{553}{}{If you say so. Goodbye, Morton.}
{553}{}{如果你这样说。再见，莫顿。}
#{600}{}{All right. Most of the time I just do simple accounting. I check the books, write down various important figures. The amount of ore Nestor sold us, the total price, the caravan companies' offers, capacities, Uncle's profits, and so on. The most demanding are the handovers of the iron ore, be it from us to the caravans, or from Nestor's people to us. At those times, my work even seems slightly dangerous.}
{600}{}{好吧。大多数时候我只是做简单的会计。我查账，写下各种重要的数字。内斯特卖给我们的矿石数量、总价、商队公司的报价、产能、叔叔的利润等等。最苛刻的是铁矿石的移交，无论是从我们手中移交给商队，还是从内斯特的人手中移交给我们。在那些时候，我的工作甚至显得有点危险。}
#{601}{}{Tell me more about Uncle.}
{601}{}{告诉我更多关于叔叔的事。}
#{602}{}{What do you know about Nestor?}
{602}{}{你对内斯特了解多少？}
#{603}{}{I don't understand. What's the problem with Nestor's people?}
{603}{}{我不明白。内斯特的人有什么问题？}
#{604}{}{Why do you trade iron ore to the caravans anyway? Wouldn't it be more profitable to sell them processed iron?}
{604}{}{你为什么要把铁矿石卖给商队？卖给他们加工过的铁不是更有利可图吗？}
#{605}{}{Don't let it get you down, Morton. Bye.}
{605}{}{别让它让你失望，莫顿。再见。}
#{650}{}{Sorry, I spend all my time accounting. The books constantly require inspections, and data is coming in all the time. My knowledge of Corath ends at my office door. You'll have to find someone else to tell you.}
{650}{}{对不起，我把时间都花在会计上了。这些书经常需要检查，而且数据总是源源不断地传来。我对科拉斯的了解在我办公室门口就结束了。你得找别人告诉你。}
#{651}{}{Don't you ever even meet anyone? I have difficulty believing that.}
{651}{}{你没见过任何人吗？我很难相信这一点。}
#{652}{}{In that case I won't bother you any more. Goodbye, Morton.}
{652}{}{那样的话，我就不打扰你了。再见，莫顿。}
#{700}{}{Oh yes I do. From time to time people see me about ore handovers. I've been taking care of that for Uncle for a long time now. Either there's ore coming to us from Nestor's people, or it's going from us to the caravans. Mind you it's the kind of work I try to take care of as quickly as possible. Dealing with Nestor's guards is not a pleasant experience at all.}
{700}{}{哦，是的，我知道。不时有人看到我关于矿石交接的事。我已经为叔叔照顾了很久了。要么是内斯特人的矿石，要么是我们的商队的矿石。请注意，这是我想尽快处理的工作。与内斯特的警卫打交道一点也不愉快。}
#{701}{}{Tell me more about Uncle.}
{701}{}{告诉我更多关于叔叔的事。}
#{702}{}{What do you know about Nestor?}
{702}{}{你对内斯特了解多少？}
#{703}{}{I don't understand. What's the problem with Nestor's people?}
{703}{}{我不明白。内斯特的人有什么问题？}
#{704}{}{Why do you trade iron ore to the caravans anyway? Wouldn't it be more profitable to sell them processed iron?}
{704}{}{你为什么要把铁矿石卖给商队？卖给他们加工过的铁不是更有利可图吗？}
#{705}{}{Don't let it get you down, Morton. Bye.}
{705}{}{别让它让你失望，莫顿。再见。}
#{750}{}{Uncle is my boss. He prospers on the trade with the caravans. He arranged transactions with every company in Sedit and thus he became the sole exporter of Corath iron ore. He must be a very capable and tough businessman if he managed to strike such a prosperous deal.}
{750}{}{叔叔是我的老板。他与商队的贸易兴旺发达。他与塞迪特的每家公司都安排了交易，因此他成了科拉斯铁矿石的唯一出口商。如果他能成功地达成这样一笔生意，他一定是一个非常能干和强硬的商人。}
#{751}{}{Now tell me about Nestor.}
{751}{}{现在告诉我关于内斯特的事。}
#{752}{}{Coming back to the handovers. What's the problem with Nestor's people?}
{752}{}{回到讲义上来。内斯特的人有什么问题？}
#{753}{}{Why do you trade iron ore to the caravans anyway? Wouldn't it be more profitable to sell them processed iron?}
{753}{}{你为什么要把铁矿石卖给商队？卖给他们加工过的铁不是更有利可图吗？}
#{754}{}{I'm sure he is. Bye, Morton.}
{754}{}{我肯定他是的。再见，莫顿。}
#{800}{}{Nestor controls all the ore mining in the city. He's an unpredictable character, very cruel towards his employees. You won't find a miner who'd have a single good word to say about him. They all hate him. They dream of the day he gets chased out and they claim the mine for themselves. But those are very dangerous dreams. The miners alone couldn't keep the mine running, let alone be better off than under Nestor. Nestor may have many flaws, but he's a better mine manager than most.}
{800}{}{内斯特控制着城市里所有的矿石开采。他性格难以捉摸，对员工很残忍。你找不到一个能对他说一句好话的矿工。他们都恨他。他们梦想着有一天他被赶出去，他们为自己认领了矿。但这些都是非常危险的梦。单靠矿工们是无法维持矿井运转的，更别说比在内斯特领导下过得更好了。内斯特也许有很多缺点，但他是一个比大多数人更好的矿长。}
#{801}{}{Tell me more about Uncle.}
{801}{}{告诉我更多关于叔叔的事。}
#{802}{}{Coming back to the handovers. What's the problem with Nestor's people?}
{802}{}{回到讲义上来。内斯特的人有什么问题？}
#{803}{}{Why do you trade iron ore to the caravans anyway? Wouldn't it be more profitable to sell them processed iron?}
{803}{}{你为什么要把铁矿石卖给商队？卖给他们加工过的铁不是更有利可图吗？}
#{804}{}{You're right. Bye, Morton.}
{804}{}{你说得对。再见，莫顿。}
#{850}{}{Well, Nestor's guards bring me the extracted ore every month. The price has been stable for several years now, but the amount depends on the conditions and performance of the miners. So far we've always sold everything Nestor supplied us. Luckily, not even his bad relations with Uncle have provoked him to stop the supply. But lately there's been trouble... Although I shouldn't be telling you about that. It's a problem which I need to solve myself.}
{850}{}{好吧，内斯特的警卫每个月都会把提取出来的矿石带给我。价格已经稳定了好几年了，但是数量取决于矿工的条件和表现。到目前为止，我们一直出售内斯特提供给我们的一切。幸运的是，即使是他和叔叔的坏关系也没有促使他停止供应。但是最近有麻烦。。。尽管我不该告诉你。这是一个我需要自己解决的问题。}
#{851}{}{Don't worry. I promise not to tell anyone.}
{851}{}{别担心。我保证不告诉任何人。}
#{852}{}{As you wish. In that case I have another question.}
{852}{}{如你所愿。既然如此，我还有一个问题。}
#{853}{}{Well, I have to go anyway. Bye.}
{853}{}{好吧，反正我得走了。再见。}
#{900}{}{[He sighs.] OK, but make sure you keep your word. In the latest batches from Nestor there was less ore than his guards claimed there was. First I thought it was an error in my books, but it kept repeating. And when Uncle wanted to bill the caravans, the loss was too great to overlook - almost 600 caps. For Uncle and Nestor this is just peanuts, but somebody had to pay it. So I paid it out of my own pocket, because admitting the error to Uncle would cost me my job. Now I'm completely without money and I honestly don't know what to do.}
{900}{}{[他叹了口气]好吧，但你一定要遵守诺言。在最近一批来自内斯特的矿石中，矿石的含量比他的警卫声称的要少。起初我以为这是我书中的一个错误，但它一直在重复。当舅舅想给商队开账单时，损失太大了，几乎600顶瓶盖。对叔叔和内斯特来说，这不过是小菜一碟，但总得有人付钱。所以我自掏腰包，因为向叔叔承认错误会让我失去工作。现在我完全没钱了，我真的不知道该怎么办。}
#{901}{}{And who's to blame in your opinion?}
{901}{}{你认为谁该受责备？}
#{902}{}{Uncle would most likely be very interested in hearing about this little secret of yours. What would you be willing to do to keep it a secret?}
{902}{}{叔叔很可能对你的这个小秘密很感兴趣。你愿意做什么来保守秘密？}
#{950}{}{The trouble with the ore deliveries started when Nestor's new guard took over. He introduces himself as Clint. He's a young rude buck. I can't shake the feeling that it's him who's responsible. But what can I do? I can't tell Uncle, and I can't do anything myself. I guess I'll never see my money again.}
{950}{}{当内斯特的新警卫接手后，矿石运输的麻烦就开始了。他自称克林特。他是个年轻粗鲁的家伙。我不由得觉得是他负责。但我能做什么呢？我不能告诉叔叔，我自己也无能为力。我想我再也见不到我的钱了。}
#{951}{}{Maybe I could talk to this Clint character and convince him to give the missing money back.}
{951}{}{也许我可以和这个克林特的角色谈谈，说服他把丢失的钱还给我。}
#{952}{}{Maybe I could talk to this Clint character and convince him to give the missing money back.}
{952}{}{也许我可以和这个克林特的角色谈谈，说服他把丢失的钱还给我。}
#{953}{}{Uncle would most likely be very interested to hear about this little secret of yours. What would you be willing to do so that this remains a secret?}
{953}{}{叔叔很可能对你的这个小秘密很感兴趣。你愿意做些什么让这成为一个秘密？}
#{954}{}{I guess not. See you, Morton.}
{954}{}{我想不是。再见，莫顿。}
#{1000}{}{Do you think you could? [He looks at you with mistrust.] Whoever starts trouble with Nestor's people usually ends up worse off, or even dead. I don't know whether any money is worth the risk. But if you really want to help me, you'll find young Clint in the Iron District. You'll know him by the large earring in his right ear.}
{1000}{}{你觉得你可以吗？[他不信任地看着你]不管是谁惹了内斯特的人的麻烦，结果都会更糟，甚至是死。我不知道有没有钱值得冒这个险。但如果你真的想帮我，你会在铁区找到年轻的克林特。你从他右耳的大耳环就知道他了。}
#{1001}{}{Do you think you could? [He looks at you with mistrust.] Whoever starts trouble with Nestor's people usually ends up worse off, or even dead. I don't know whether any money is worth the risk. But if you really want to help me, you'll find young Clint in the Iron District. You'll know him by the large earring in his right ear.}
{1001}{}{你觉得你可以吗？[他不信任地看着你]不管是谁惹了内斯特的人的麻烦，结果都会更糟，甚至是死。我不知道有没有钱值得冒这个险。但如果你真的想帮我，你会在铁区找到年轻的克林特。你从他右耳的大耳环就知道他了。}
#{1002}{}{I'll see what I can do. Don't go anywhere.}
{1002}{}{我看看我能做什么。哪儿也别去。}
#{1050}{}{[He frowns.] You won't get anything from me. I settled the difference myself, and the accounts are now in complete order. It would be your word against mine. He'd never believe you.}
{1050}{}{[他皱眉]你从我这里什么也得不到。我自己结清了差额，现在帐都清了。你的话会对我不利。他不会相信你的。}
#{1051}{}{Calm down, Morton. You don't have to get angry right away.}
{1051}{}{冷静点，莫顿。你不必马上生气。}
#{1100}{}{[He pauses to think.] I guess it would be. But Corath lacks the means to smelt so much ore. Nestor can process only a part of his ore, and he always uses that to manufacture the tools and machinery for the mine. And Uncle is only interested in trade. I don't expect anything will change with that any time soon.}
{1100}{}{[他停下来思考]我想是的。但是科拉斯没有能力冶炼这么多矿石，内斯特只能加工一部分矿石，他总是用这些来制造矿山的工具和机械。叔叔只对贸易感兴趣。我不指望很快会有什么变化。}
#{1101}{}{Now tell me more about Uncle.}
{1101}{}{现在告诉我更多关于叔叔的事。}
#{1102}{}{What do you know about Nestor?}
{1102}{}{你对内斯特了解多少？}
#{1103}{}{Coming back to the handovers. What's the problem with Nestor's people?}
{1103}{}{回到讲义上来。内斯特的人有什么问题？}
#{1104}{}{I guess not. Bye, Morton.}
{1104}{}{我想不是。再见，莫顿。}
#{1150}{}{What is it?}
{1150}{}{这是怎么一回事？}
#{1151}{}{Tell me about Uncle.}
{1151}{}{告诉我叔叔的事。}
#{1152}{}{What do you know about Nestor?}
{1152}{}{你对内斯特了解多少？}
#{1153}{}{Coming back to the handovers. What's the problem with Nestor's people?}
{1153}{}{回到讲义上来。内斯特的人有什么问题？}
#{1154}{}{Coming back to the handovers. What didn't you want to tell me? I promise not to tell anyone.}
{1154}{}{回到讲义上来。你不想告诉我什么？我保证不告诉任何人。}
#{1155}{}{Why do you trade iron ore to the caravans anyway? Wouldn't it be more profitable to sell them processed iron?}
{1155}{}{你为什么要把铁矿石卖给商队？卖给他们加工过的铁不是更有利可图吗？}
#{1156}{}{Oh, nothing. Bye, Morton.}
{1156}{}{哦，没什么。再见，莫顿。}
#{1200}{}{Hmm... Yes? [Morton interrupts his work.] Please be brief. I must go back to accounting as soon as possible.}
{1200}{}{隐马尔可夫模型。。。对？[莫顿打断他的工作]请简短一点。我必须尽快回去做会计。}
#{1201}{}{Hmm... Yes? [Morton interrupts his work.] Please be brief. I must go back to accounting as soon as possible.}
{1201}{}{隐马尔可夫模型。。。对？[莫顿打断他的工作]请简短一点。我必须尽快回去做会计。}
#{1202}{}{I see you're a busy man. What is it exactly you do?}
{1202}{}{我看你是个大忙人。你到底是做什么的？}
#{1203}{}{I really want to know more about your work.}
{1203}{}{我真的很想了解你的工作。}
#{1204}{}{I really want to know more about your work.}
{1204}{}{我真的很想了解你的工作。}
#{1205}{}{Can you answer a few questions about Corath for me?}
{1205}{}{你能回答我几个关于科拉斯的问题吗？}
#{1206}{}{I want to ask you a couple of questions.}
{1206}{}{我想问你几个问题。}
#{1207}{}{I've been thinking about your predicament. Maybe I could talk to this Clint character and convince him to give back the missing money.}
{1207}{}{我一直在想你的困境。也许我可以和这个克林特的角色谈谈，说服他把丢失的钱还给我。}
#{1208}{}{I've been thinking about your predicament. Maybe I could talk to this Clint character and convince him to give back the missing money.}
{1208}{}{我一直在想你的困境。也许我可以和这个克林特的角色谈谈，说服他把丢失的钱还给我。}
#{1209}{}{I've brought you the missing money from Clint.}
{1209}{}{我把克林特丢失的钱给你带来了。}
#{1210}{}{I've brought you the missing money from Clint.}
{1210}{}{我把克林特丢失的钱给你带来了。}
#{1211}{}{I managed to get the missing money. But it seems to me that losing it was your own fault in the first place. Besides, if I gave you back caps you lost with your own incompetence, how would you ever learn? I figure this experience would be more educational for you if the caps stayed nice and safe with me. What do you think?}
{1211}{}{我设法弄到了丢失的钱。但在我看来，失去它首先是你自己的错。再说，如果我把你因自己的无能而失去的瓶盖还给你，你会怎么学呢？我想如果瓶盖和我呆在一起安全又漂亮的话，这种经历对你会更有教育意义。你怎么认为？}
#{1212}{}{Don't let me disturb you.}
{1212}{}{别让我打扰你。}
#{1213}{}{Ugh!}
{1213}{}{啊！}
#{1250}{}{[He looks at you in disbelief.] You really managed to get it. But... It wasn't too risky, was it? If there only were some way to reward you. [He rummages through his papers, and finally hands you a crumpled stack of manuals and magazines.] Here, take these. It's not much, just some forgotten collection I found when moving my office. But maybe you'll find them useful.}
{1250}{}{[他难以置信地看着你]你真的成功了。但是。。。不是太冒险吧？如果有什么办法奖励你就好了。[他翻遍了他的文件，最后递给你一堆皱巴巴的手册和杂志]来，拿着这些。不多，只是我搬家时发现的一些被遗忘的收藏品。但也许你会发现它们很有用。}
#{1251}{}{Thanks Morton. I can sure use these. See you.}
{1251}{}{谢谢莫顿。我当然可以用这些。再见。}
#{1300}{}{Sorry, I have no time for you now. I need to go through all the accounting records on trade with Nestor and prepare a business estimate for the mine. Uncle needs it urgently, now that he controls the mine.}
{1300}{}{对不起，我现在没有时间给你。我需要检查所有与内斯特贸易的会计记录，并为该矿准备一份商业估算。舅舅现在控制了矿场，急需它。}
#{1301}{}{I won't be long. I just brought you the money from Clint.}
{1301}{}{我一会儿就回来。我刚从克林特那里给你带了钱。}
#{1302}{}{I won't be long. I just brought you the money from Clint.}
{1302}{}{我一会儿就回来。我刚从克林特那里给你带了钱。}
#{1303}{}{I'll only take a minute. I only wanted to tell you that there's no way to get your missing money. All of Nestor's guards have fled the city, Clint among them. Sorry.}
{1303}{}{我只需要一分钟。我只想告诉你没有办法得到你丢失的钱。内斯特的所有警卫都逃离了城市，克林特也在其中。对不起的。}
#{1304}{}{I guess in that case you won't be needing the money Clint gave me for you. Good. I'll put it to better use than you anyway.}
{1304}{}{我想那样的话你就不需要克林特给我的钱了。很好。不管怎样，我会比你更好地利用它。}
#{1305}{}{In that case I won't disturb you. Bye, Morton.}
{1305}{}{那样的话，我就不打扰你了。再见，莫顿。}
#{1306}{}{Ugh.}
{1306}{}{啊。}
#{1350}{}{That's OK. I wasn't counting on getting that money back anyway. Don't worry about it.}
{1350}{}{没关系。反正我也没指望能拿回那笔钱。别担心。}
#{1351}{}{Thanks, Morton. Goodbye.}
{1351}{}{谢谢，莫顿。再见。}
#{1400}{}{Sorry, I have no time for you now. Nestor has offered me a job provided I can prepare a report about Uncle's ore trade for him post haste. I have more work than I can handle.}
{1400}{}{对不起，我现在没有时间陪你。内斯特给我提供了一份工作，只要我能尽快为他准备一份有关叔叔矿石贸易的报告。我的工作多得应付不了。}
#{1401}{}{Isn't that a bit disloyal towards your previous boss?}
{1401}{}{这不是对你以前的老板有点不忠吗？}
#{1402}{}{I won't be long. I just brought you the money from Clint.}
{1402}{}{我一会儿就回来。我刚从克林特那里给你带了钱。}
#{1403}{}{I won't be long. I just brought you the money from Clint.}
{1403}{}{我一会儿就回来。我刚从克林特那里给你带了钱。}
#{1404}{}{I guess in that case you won't be needing the money Clint gave me for you. Good. I'll put it to better use than you anyway.}
{1404}{}{我想那样的话你就不需要克林特给我的钱了。很好。不管怎样，我会比你更好地利用它。}
#{1405}{}{In that case I won't disturb you. Bye, Morton.}
{1405}{}{那样的话，我就不打扰你了。再见，莫顿。}
#{1406}{}{Ugh.}
{1406}{}{啊。}
#{1450}{}{[He smiles a sad smile.] I'm only an accountant, not a hero. I have to make a living.}
{1450}{}{[他伤心地笑了笑]我只是个会计，不是英雄。我必须谋生。}
#{1451}{}{Whatever you say, Morton. Goodbye.}
{1451}{}{不管你说什么，莫顿。再见。}
