#{100}{}{You tripped over an inconspicuous wire and set off a trap. The explosion has completely destroyed the contents of the shelf.}
{100}{}{你被一根不显眼的电线绊倒了，并设下陷阱。爆炸把架子上的东西完全炸毁了。}
#{101}{}{You tripped over an inconspicuous wire and set off a trap. The explosion has completely destroyed the contents of the shelf.}
{101}{}{你被一根不显眼的电线绊倒了，并设下陷阱。爆炸把架子上的东西完全炸毁了。}
#{200}{}{You have discovered an explosive booby trap. Touching the contents of the shelf will most likely lead to an explosion and destroy everything.}
{200}{}{你发现了一个爆炸诱杀装置。碰一下架子上的东西很可能会导致爆炸，毁掉一切。}
#{201}{}{You have discovered an explosive booby trap. Touching the contents of the shelf will most likely lead to an explosion and destroy everything.}
{201}{}{你发现了一个爆炸诱杀装置。碰一下架子上的东西很可能会导致爆炸，毁掉一切。}
#{300}{}{This trap is too sophisticated for your skills. You cannot disarm it safely.}
{300}{}{这个陷阱对你的技能来说太复杂了。你不能安全地解除它。}
#{400}{}{It wasn't easy, but you finally managed to disarm the trap. You can now safely access the contents of the shelf.}
{400}{}{这并不容易，但你终于解除了陷阱。您现在可以安全地访问书架上的内容。}
