#{100}{}{You see a short man.}
{100}{}{你看到一个矮个子。}
#{150}{}{You see Nestor.}
{150}{}{你看内斯特。}
#{200}{}{You see an unsightly little man with a confident look on his face.}
{200}{}{你看到一个难看的小个子男人，脸上带着自信的神情。}
#{250}{}{You see Nestor. He certainly wasn't blessed with good looks.}
{250}{}{你看内斯特。他当然没有美貌。}
#{400}{}{Get rid of this pathetic loser!}
{400}{}{摆脱这个可怜的失败者！}
#{401}{}{Get rid of this pathetic loser!}
{401}{}{摆脱这个可怜的失败者！}
#{500}{}{[He looks up.] So, you're the stranger who ended the miners' strike? A pleasure to make your acquaintance. My name is Nestor, but I'm sure you already knew that.}
{500}{}{[他抬起头来]那么，你就是那个结束矿工罢工的陌生人？很高兴认识你。我叫内斯特，但我相信你已经知道了。}
#{501}{}{[He looks up.] So, you're the stranger who ended the miners' strike? A pleasure to make your acquaintance. My name is Nestor, but I'm sure you already knew that.}
{501}{}{[他抬起头来]那么，你就是那个结束矿工罢工的陌生人？很高兴认识你。我叫内斯特，但我相信你已经知道了。}
#{502}{}{[He looks up.] So, you're the stranger who brought Richie to me? A pleasure to make your acquaintance. My name is Nestor, but I'm sure you already knew that.}
{502}{}{[他抬起头来]那么，你就是那个把里奇带到我这里来的陌生人？很高兴认识你。我叫内斯特，但我相信你已经知道了。}
#{503}{}{[He looks up.] So, you're the stranger who brought Richie to me? A pleasure to make your acquaintance. My name is Nestor, but I'm sure you already knew that.}
{503}{}{[他抬起头来]那么，你就是那个把里奇带到我这里来的陌生人？很高兴认识你。我叫内斯特，但我相信你已经知道了。}
#{504}{}{I thought you would be taller.}
{504}{}{我以为你会更高。}
#{505}{}{I thought you would be taller.}
{505}{}{我以为你会更高。}
#{506}{}{Ademar told me you had work for me.}
{506}{}{阿德玛告诉我你有工作给我。}
#{507}{}{Forget the pleasantries. I'm here to challenge you to the ring.}
{507}{}{忘了那些寒暄吧。我是来向你挑战的。}
#{508}{}{This must be the wrong door.}
{508}{}{这一定是开错门了。}
#{509}{}{This must be the wrong door.}
{509}{}{这一定是开错门了。}
#{510}{}{Guh?!}
{510}{}{嗯？！}
#{550}{}{[He points to his mercenaries.] I've had people killed for more innocent remarks than that. Tell me, was that pathetic joke really worth an agonizing and painful death?}
{550}{}{[他指了指他的雇佣兵]我已经有人因为比这更无辜的言论而被杀了。告诉我，那个可悲的笑话真的值得一个痛苦的死亡吗？}
#{551}{}{No sir. I'm sorry.}
{551}{}{没有，先生。我很抱歉。}
#{552}{}{You want to threaten me? I'll deal with you, short and sweet!}
{552}{}{你想威胁我？我来对付你，又矮又甜！}
#{553}{}{Let's play by the rules. I challenge you to the ring.}
{553}{}{让我们按规则玩吧。我向你挑战拳击场。}
#{600}{}{Alright, I'll give you one more chance. As you've already heard from Ademar, I have a job for you. And it's important enough that I have to tell you about it myself. As you know, Uncle's been on my back for too long. These constant attempts of his to run me out of town, those people facing Blaster to their deaths... My patience is up. I want you to take care of Uncle, once and for all.}
{600}{}{好吧，我再给你一次机会。你已经听阿德玛说过了，我有份工作给你。很重要的是我必须亲自告诉你。你知道，叔叔背着我太久了。他不停地想把我赶出镇子，那些人面临着死亡的威胁。。。我的耐心到了。我要你一劳永逸地照顾叔叔。}
#{601}{}{Alright, I'll give you one more chance. As you've already heard from Ademar, I have a job for you. And it's important enough that I have to tell you about it myself. As you know, Uncle's been on my back for too long. These constant attempts of his to run me out of town, those people facing Blaster to their deaths... My patience is up. I want you to take care of Uncle, once and for all.}
{601}{}{好吧，我再给你一次机会。你已经听阿德玛说过了，我有份工作给你。很重要的是我必须亲自告诉你。你知道，叔叔背着我太久了。他不停地想把我赶出镇子，那些人面临着死亡的威胁。。。我的耐心到了。我要你一劳永逸地照顾叔叔。}
#{602}{}{And how should I do that?}
{602}{}{我该怎么做？}
#{603}{}{And how should I do that?}
{603}{}{我该怎么做？}
#{650}{}{The only possible way we have in this city, of course. You'll challenge him to the ring. You yourself took care of the necessary reasons for us when you brought Richie to us. In the end, that idiot gladly disclosed that he had been hired by Uncle to stir up trouble in the mine. If you take this to Cedrick, his deputy, he'll need to defend himself. My people will take care of things with the police and Lawteller in the meantime. Most likely, Cedrick himself will face you in the ring on behalf of Uncle. He's quite good with his fists. If you manage to defeat him, Uncle will be forced to clear out of Corath. The sheriff won't give him other options. [He forms a crooked smile.] And that's all I need.}
{650}{}{当然，这是我们在这个城市唯一可能的办法。你要向他挑战拳击场。当你把里奇带到我们这里来的时候，你自己为我们考虑了必要的理由。最后，那个白痴高兴地说他是叔叔雇来在矿井里捣乱的。如果你把这个交给塞德里克，他的副手，他需要为自己辩护。同时我的人会和警察和执法人员一起处理事情。很可能，塞德里克本人会代表叔叔在拳击场上面对你。他的拳头很好。如果你设法打败他，叔叔将被迫离开科拉斯。警长不会给他其他的选择。[他歪歪着笑]这就是我所需要的。}
#{651}{}{The only possible way we have in this city, of course. You'll challenge him to the ring. You yourself took care of the necessary reasons for us when you brought Richie to us. In the end, that idiot gladly disclosed that he had been hired by Uncle to stir up trouble in the mine. If you take this to Cedrick, his deputy, he'll need to defend himself. My people will take care of things with the police and Lawteller in the meantime. Most likely, Cedrick himself will face you in the ring on behalf of Uncle. He's quite good with his fists. If you manage to defeat him, Uncle will be forced to clear out of Corath. The sheriff won't give him other options. [He forms a crooked smile.] And that's all I need.}
{651}{}{当然，这是我们在这个城市唯一可能的办法。你要向他挑战拳击场。当你把里奇带到我们这里来的时候，你自己为我们考虑了必要的理由。最后，那个白痴高兴地说他是叔叔雇来在矿井里捣乱的。如果你把这个交给塞德里克，他的副手，他需要为自己辩护。同时我的人会和警察和执法人员一起处理事情。很可能，塞德里克本人会代表叔叔在拳击场上面对你。他的拳头很好。如果你设法打败他，叔叔将被迫离开科拉斯。警长不会给他其他的选择。[他歪歪着笑]这就是我所需要的。}
#{652}{}{The only possible way we have in this city, of course. You'll challenge him to the ring. Use Richie's murder as an excuse. I have no doubt in my mind it was Uncle's doing. To defend his reputation, he'll have to accept the challenge. My people will take care of things with the police and Lawteller in the meantime. Most likely, Cedrick, Uncle's deputy, will face you in the ring. He's quite good with his fists. If you manage to defeat him, Uncle will be forced to clear out of Corath. The sheriff won't give him other options. [He forms a crooked smile.] And that's all I need.}
{652}{}{当然，这是我们在这个城市唯一可能的办法。你要向他挑战拳击场。以里奇被杀为借口。我毫不怀疑这是叔叔干的。为了维护自己的名誉，他必须接受挑战。同时我的人会和警察和执法人员一起处理事情。很可能，塞德里克，叔叔的副手，会在拳击场上面对你。他的拳头很好。如果你设法打败他，叔叔将被迫离开科拉斯。警长不会给他其他的选择。[他歪歪着笑]这就是我所需要的。}
#{653}{}{What if I lose?}
{653}{}{如果我输了怎么办？}
#{654}{}{Why don't you put Blaster in the ring?}
{654}{}{你为什么不把爆能枪放在拳击场上？}
#{655}{}{How much will you pay me for this job?}
{655}{}{这份工作你付我多少钱？}
#{656}{}{OK, I'll do it.}
{656}{}{好的，我来做。}
#{657}{}{You need to find someone else to do this for you.}
{657}{}{你需要找别人帮你做这件事。}
#{700}{}{In that case, you'll die. Or your substitute in the ring will die, if you manage to find one. But it's a risk I am willing to take. Nothing can happen to me. Only Uncle, being the accused, will be in any danger.}
{700}{}{那样的话，你会死的。否则你的替补会死的，如果你设法找到一个。但我愿意冒这个险。我什么都不会发生。只有叔叔，作为被告，才会有危险。}
#{701}{}{In that case, you'll die. Or your substitute in the ring will die. But it's a risk I am willing to take. Nothing can happen to me. Only Uncle, being the accused, will be in any danger.}
{701}{}{那样的话，你会死的。否则你的替补就会死。但我愿意冒这个险。我什么都不会发生。只有叔叔，作为被告，才会有危险。}
#{702}{}{Why don't you put Blaster in the ring?}
{702}{}{你为什么不把爆能枪放在拳击场上？}
#{703}{}{How much will you pay me for this job?}
{703}{}{这份工作你付我多少钱？}
#{704}{}{OK, I'll do it.}
{704}{}{好的，我来做。}
#{705}{}{You need to find someone else to do this for you.}
{705}{}{你需要找别人帮你做这件事。}
#{750}{}{Because I have my reputation to think of. Many locals see Blaster as the only reason why Uncle hasn't been able to chase me out of the city so far. I can't have them attributing my final victory to Blaster too. It would be way too easy to lose any power built solely on the fists of one supermutant.}
{750}{}{因为我有我的名声。许多当地人认为爆炸机是叔叔到目前为止没能把我赶出城市的唯一原因。我不能让他们把我最后的胜利也归因于爆破手。仅仅依靠一个超级变种人的拳头就很容易失去任何力量。}
#{751}{}{What if I lose?}
{751}{}{如果我输了怎么办？}
#{752}{}{How much will you pay me for this job?}
{752}{}{这份工作你付我多少钱？}
#{753}{}{OK, I'll do it.}
{753}{}{好的，我来做。}
#{754}{}{You need to find someone else to do this job for you.}
{754}{}{你需要找别人帮你做这项工作。}
#{800}{}{If the situation warrants, I can be generous. 2500 caps.}
{800}{}{如果情况允许，我可以很慷慨。2500个盖子。}
#{801}{}{What if I lose?}
{801}{}{如果我输了怎么办？}
#{802}{}{Why don't you put Blaster in the ring?}
{802}{}{你为什么不把爆能枪放在拳击场上？}
#{803}{}{OK, I'll do it.}
{803}{}{好的，我来做。}
#{804}{}{You need to find someone else to do this job for you.}
{804}{}{你需要找别人帮你做这项工作。}
#{850}{}{Yes, I have a job for you. And it's important enough that I have to tell you about it myself. As you know, Uncle's been on my back for too long. These constant attempts of his to run me out of town, those people facing Blaster to their deaths... My patience is up. I want you to take care of Uncle, once and for all.}
{850}{}{是的，我有份工作给你。很重要的是我必须亲自告诉你。你知道，叔叔背着我太久了。他不停地想把我赶出镇子，那些人面临着死亡的威胁。。。我的耐心到了。我要你一劳永逸地照顾叔叔。}
#{851}{}{Yes, I have a job for you. And it's important enough that I have to tell you about it myself. As you know, Uncle's been on my back for too long. These constant attempts of his to run me out of town, those people facing Blaster to their deaths... My patience is up. I want you to take care of Uncle, once and for all.}
{851}{}{是的，我有份工作给你。很重要的是我必须亲自告诉你。你知道，叔叔背着我太久了。他不停地想把我赶出镇子，那些人面临着死亡的威胁。。。我的耐心到了。我要你一劳永逸地照顾叔叔。}
#{852}{}{And how should I do that?}
{852}{}{我该怎么做？}
#{853}{}{And how should I do that?}
{853}{}{我该怎么做？}
#{900}{}{I knew I picked the right person for the job. When you're done, come see me.}
{900}{}{我知道我选对了这个工作的人。当你做完后，来看我。}
#{901}{}{I knew I picked the right person for the job. When you're done, come see me.}
{901}{}{我知道我选对了这个工作的人。当你做完后，来看我。}
#{902}{}{Before I go, can you answer a few questions for me?}
{902}{}{在我走之前，你能回答我几个问题吗？}
#{903}{}{We'll see. See you later, Nestor.}
{903}{}{我们拭目以待。再见，内斯特。}
#{950}{}{Well, that's too bad. I was counting on you. Should you change your mind, my offer is still open for now.}
{950}{}{好吧，那太糟糕了。我就指望你了。如果你改变主意的话，我的报价现在仍然有效。}
#{951}{}{Well, that's too bad. I was counting on you. Should you change your mind, my offer is still open for now.}
{951}{}{好吧，那太糟糕了。我就指望你了。如果你改变主意的话，我的报价现在仍然有效。}
#{952}{}{Don't hold your breath. Bye.}
{952}{}{别屏住呼吸。再见。}
#{1000}{}{I can, provided it doesn't take too much time.}
{1000}{}{我可以，只要不花太多时间。}
#{1001}{}{What will you do once you get rid of Uncle?}
{1001}{}{除掉叔叔后你会怎么做？}
#{1002}{}{What will you do now that Uncle is gone?}
{1002}{}{叔叔走了，你打算怎么办？}
#{1003}{}{How did you manage to acquire Blaster?}
{1003}{}{你是怎么得到爆炸机的？}
#{1004}{}{I'm supposed to give you a message from deputy sheriff Gordon. He'd like to work for you.}
{1004}{}{我要给你个戈登副警长的口信。他想为你工作。}
#{1005}{}{Actually, I have no questions. I'll be going.}
{1005}{}{实际上，我没有问题。我要走了。}
#{1050}{}{I'll take over his trade with Sedit. The caravan companies will have to buy iron ore directly from me. Finally, I'll have enough resources to expand the mining operation and partly switch over to machine labor. I'll also build huge furnaces to smelt all the ore. I'll make Corath iron the most sought-after commodity in the whole region.}
{1050}{}{我来接管他和塞迪特的生意。商队公司将不得不直接从我这里购买铁矿石。最后，我将有足够的资源来扩大采矿作业，并部分转向机器劳动。我还将建造巨大的熔炉来冶炼所有的矿石。我将使科拉斯铁矿成为整个地区最受欢迎的商品。}
#{1051}{}{Sound like you have big plans. Oh, and how did you manage to acquire Blaster, anyway?}
{1051}{}{听起来你有很大的计划。哦，你是怎么弄到爆炸机的？}
#{1052}{}{You set your own bar pretty high. Oh yeah, I'm supposed to give you a message from deputy sheriff Gordon. He would like to work for you.}
{1052}{}{你把自己的标准定得很高。哦，是的，我应该给你一个副警长戈登的口信。他愿意为你工作。}
#{1053}{}{I see. See you later, Nestor.}
{1053}{}{我懂了。再见，内斯特。}
#{1100}{}{That was a lucky coincidence. My mercenaries found Blaster some years ago when scouting at the far side of the mountains. He was heavily wounded and almost unconscious. God only knows how he ever got there. When they brought me to him he was mumbling his name over and over again. One guard wanted to finish him, but I knew right away I could have use for him. I had Blaster brought to the city and hired a private doctor for him. And ever since, he's been helping me in the ring with bastards who dare to challenge me.}
{1100}{}{那是个幸运的巧合。我的佣兵几年前在山的另一边侦察时发现了布雷斯特。他受了重伤，几乎失去知觉。只有上帝知道他是怎么到那里的。当他们把我带到他身边时，他一次又一次地咕哝着他的名字。一个警卫想干掉他，但我马上就知道我可以利用他。我把布拉斯特带到城里，为他雇了一个私人医生。从那以后，他一直在帮我对付那些胆敢挑战我的混蛋。}
#{1101}{}{That was a lucky coincidence. My mercenaries found Blaster some years ago when scouting at the far side of the mountains. He was heavily wounded and almost unconscious. God only knows how he ever got there. When they brought me to him he was mumbling his name over and over again. One guard wanted to finish him, but I knew right away I could have use for him. I had Blaster brought to the city and hired a private doctor for him. And ever since, he's been helping me in the ring with bastards who dare to challenge me.}
{1101}{}{那是个幸运的巧合。我的佣兵几年前在山的另一边侦察时发现了布雷斯特。他受了重伤，几乎失去知觉。只有上帝知道他是怎么到那里的。当他们把我带到他身边时，他一次又一次地咕哝着他的名字。一个警卫想干掉他，但我马上就知道我可以利用他。我把布拉斯特带到城里，为他雇了一个私人医生。从那以后，他一直在帮我对付那些胆敢挑战我的混蛋。}
#{1102}{}{How did he come by his heavy wounds?}
{1102}{}{他是怎么受重伤的？}
#{1103}{}{What will you do once you get rid of Uncle?}
{1103}{}{除掉叔叔后你会怎么做？}
#{1104}{}{What will you do now that Uncle is gone?}
{1104}{}{叔叔走了，你打算怎么办？}
#{1105}{}{I see. Oh, by the way, I'm supposed to give you a message from deputy sheriff Gordon. He would like to work for you.}
{1105}{}{我懂了。哦，顺便说一句，我要给你个戈登副警长的口信。他愿意为你工作。}
#{1106}{}{That will be all. See you, Nestor.}
{1106}{}{就这些了。再见，内斯特。}
#{1150}{}{That remains a mystery to me. I only know it must have been someone with a pretty good arsenal. Blaster's skin can repel most bullets, but back then he was riddled with them.}
{1150}{}{这对我来说仍然是个谜。我只知道那一定是一个兵工厂很好的人。爆能者的皮肤可以击退大多数子弹，但那时他被子弹打得千疮百孔。}
#{1151}{}{Interesting. What will you do once you get rid of Uncle?}
{1151}{}{很有趣。除掉叔叔后你会怎么做？}
#{1152}{}{Interesting. What will you do now that Uncle is gone?}
{1152}{}{很有趣。叔叔走了，你打算怎么办？}
#{1153}{}{I see. Oh, by the way, I'm supposed to give you a message from deputy sheriff Gordon. He would like to work for you.}
{1153}{}{我懂了。哦，顺便说一句，我要给你个戈登副警长的口信。他愿意为你工作。}
#{1154}{}{That will be all. See you later.}
{1154}{}{就这些了。再见。}
#{1200}{}{Gordon will stay where he is. It's useful to have a corruptible person in the police force. As my employee he would be useless.}
{1200}{}{戈登会呆在原地。在警察队伍里有一个腐败的人是有用的。作为我的雇员，他将一无是处。}
#{1201}{}{I understand. What will you do once you get rid of Uncle?}
{1201}{}{我理解。除掉叔叔后你会怎么做？}
#{1202}{}{I understand. What will you do now that Uncle is gone?}
{1202}{}{我理解。叔叔走了，你打算怎么办？}
#{1203}{}{I understand. How did you manage to acquire Blaster, anyway?}
{1203}{}{我理解。你是怎么弄到爆炸机的？}
#{1204}{}{That will be all. See you later, Nestor.}
{1204}{}{就这些了。再见，内斯特。}
#{1250}{}{[His small mouth twists into a surprised grin uncovering his bad teeth including his golden molar.] What? You? And what's your damn reason?!}
{1250}{}{[他的小嘴扭成一个惊讶的笑容，露出他的坏牙，包括他的金臼齿。]什么？你呢？你他妈的为什么？！}
#{1251}{}{I am here on Uncle's behalf. He asks you be ousted from Corath for the miner unrest which has recently spread to the city itself. Uncle's people are already taking care of things with the police and Lawteller.}
{1251}{}{我是代表叔叔来的。他要求你因为最近蔓延到城市本身的矿工骚乱被驱逐出科拉斯。叔叔的人已经在和警察和执法人员一起处理事情了。}
#{1252}{}{I am here on behalf of Uncle. He asks you to be ousted from Corath for murdering a man named Richie. Uncle's people are already taking care of things with the police and Lawteller.}
{1252}{}{我是代表叔叔来的。他要求你因谋杀一个叫里奇的人而被驱逐出科拉斯。叔叔的人已经在和警察和执法人员一起处理事情了。}
#{1253}{}{Fuck the reasons. I'll just kill you now!}
{1253}{}{去他的理由。我现在就杀了你！}
#{1254}{}{I was only joking. I better go.}
{1254}{}{我只是开玩笑。我得走了。}
#{1255}{}{I was only joking. I better go.}
{1255}{}{我只是开玩笑。我得走了。}
#{1300}{}{So, Uncle's found another ring fighter. No matter. At least the city will know once more that facing me means facing Blaster. And facing Blaster means death.}
{1300}{}{叔叔又找到了一个拳击手。没关系。至少这座城市会再次明白，面对我意味着面对爆能者。面对爆炸机意味着死亡。}
#{1301}{}{We'll see about that. [Go to the ring.]}
{1301}{}{我们拭目以待。[去拳击场]}
#{1350}{}{I doubt it. Ademar sent you, did he not? And think twice before you answer.}
{1350}{}{我怀疑。阿德玛派你来的，不是吗？在你回答之前三思而后行。}
#{1351}{}{Sorry. Yes, Ademar sent me.}
{1351}{}{对不起的。是的，阿德玛派我来的。}
#{1353}{}{I'll say one thing, and one thing only. Die, you degenerate cripple!}
{1353}{}{我只想说一件事。死吧，你这个堕落的瘸子！}
#{1360}{}{I doubt it. Ademar sent you, did he not? And think twice before you answer.}
{1360}{}{我怀疑。阿德玛派你来的，不是吗？在你回答之前三思而后行。}
#{1361}{}{Sorry. Yes, Ademar sent me.}
{1361}{}{对不起的。是的，阿德玛派我来的。}
#{1362}{}{I actually want to challenge you to the ring.}
{1362}{}{我真的想向你挑战拳击场。}
#{1363}{}{I'll say one thing, and one thing only. Die, you degenerate cripple!}
{1363}{}{我只想说一件事。死吧，你这个堕落的瘸子！}
#{1400}{}{What kind of an idiot did Ademar think he was sending?!}
{1400}{}{阿德玛以为他派的是什么白痴？！}
#{1401}{}{Guuh?}
{1401}{}{嗯？}
#{1450}{}{Did you change your mind about the job? My offer is still open.}
{1450}{}{你对这份工作改变主意了吗？我的报价仍然有效。}
#{1451}{}{Did you change your mind about the job? My offer is still open.}
{1451}{}{你对这份工作改变主意了吗？我的报价仍然有效。}
#{1452}{}{Alright. I'll challenge Uncle and defeat his substitute Cedrick in the ring.}
{1452}{}{好吧。我要挑战叔叔，打败他的替补塞德里克。}
#{1453}{}{I'm not interested in your offer. I challenge you to the ring.}
{1453}{}{我对你的提议不感兴趣。我向你挑战拳击场。}
#{1454}{}{As is my refusal. Bye.}
{1454}{}{我的拒绝也是如此。再见。}
#{1455}{}{Ugh.}
{1455}{}{啊。}
#{1500}{}{As far as I know, Uncle is still in the city. So don't linger, unless you have to.}
{1500}{}{据我所知，叔叔还在城里。所以不要逗留，除非你不得不。}
#{1501}{}{Can you answer a few questions?}
{1501}{}{你能回答几个问题吗？}
#{1502}{}{This is the right place. I challenge you to the ring.}
{1502}{}{这是正确的地方。我向你挑战拳击场。}
#{1503}{}{I'm just leaving.}
{1503}{}{我要走了。}
#{1504}{}{Ugh.}
{1504}{}{啊。}
#{1550}{}{[His small mouth twists into a surprised grin, uncovering bad teeth including his golden molar.] What? You? And what's your damn reason?!}
{1550}{}{[他的小嘴扭成惊讶的笑容，露出坏牙，包括他的金磨牙]什么？你呢？你他妈的为什么？！}
#{1551}{}{I am here on Uncle's behalf. He asks you be ousted from Corath for the miner unrest which has recently spread to the city itself. Uncle's people are already taking care of things with the police and Lawteller.}
{1551}{}{我是代表叔叔来的。他要求你因为最近蔓延到城市本身的矿工骚乱被驱逐出科拉斯。叔叔的人已经在和警察和执法人员一起处理事情了。}
#{1552}{}{I am here on behalf of Uncle. He asks you to be ousted from Corath for murdering a man named Richie. Uncle's people are already taking care of things with the police and Lawteller.}
{1552}{}{我是代表叔叔来的。他要求你因谋杀一个叫里奇的人而被驱逐出科拉斯。叔叔的人已经在和警察和执法人员一起处理事情了。}
#{1553}{}{Fuck the reasons. I'll just kill you now!}
{1553}{}{去他的理由。我现在就杀了你！}
#{1554}{}{I was only joking. I better go.}
{1554}{}{我只是开玩笑。我得走了。}
#{1555}{}{I was only joking. I better go.}
{1555}{}{我只是开玩笑。我得走了。}
#{1600}{}{I've already heard the good news. I always thought Uncle was an idiot, but opposing the sheriff was his stupidest decision ever. The city is mine now and mine alone. And I have mainly you to thank, stranger. Here's your reward as promised. For taking part in the siege of Uncle's villa, I'll add another 3500 caps to it. You've earned them.}
{1600}{}{我已经听到好消息了。我一直认为叔叔是个白痴，但反对警长是他有史以来最愚蠢的决定。这座城市现在是我的，只有我一个人。我主要要感谢你，陌生人。这是你答应的报酬。参加围攻叔叔的别墅，我再加3500个瓶盖。你赢得了他们。}
#{1601}{}{I've already heard the good news. I always thought Uncle was an idiot, but opposing the sheriff was his stupidest decision ever. The city is mine now and mine alone. And I have mainly you to thank, stranger. Here's your reward as promised. For taking part in the siege of Uncle's villa, I'll add another 3500 caps to it. You've earned them.}
{1601}{}{我已经听到好消息了。我一直认为叔叔是个白痴，但反对警长是他有史以来最愚蠢的决定。这座城市现在是我的，只有我一个人。我主要要感谢你，陌生人。这是你答应的报酬。参加围攻叔叔的别墅，我再加3500个瓶盖。你赢得了他们。}
#{1602}{}{I've already heard the good news. I always thought Uncle was an idiot, but opposing the sheriff was his stupidest decision ever. Too bad Ademar died. He was my best guy. But more importantly, the city is mine and mine alone now. And I have mainly you to thank, stranger. Here's your reward as promised. For taking part in the siege of Uncle's villa, I'll add another 3500 caps to it. You've earned them.}
{1602}{}{我已经听到好消息了。我一直认为叔叔是个白痴，但反对警长是他有史以来最愚蠢的决定。可惜阿德玛死了。他是我最好的人。但更重要的是，这座城市是我的，现在只有我一个人了。我主要要感谢你，陌生人。这是你答应的报酬。参加围攻叔叔的别墅，我再加3500个瓶盖。你赢得了他们。}
#{1603}{}{I've already heard the good news. I always thought Uncle was an idiot, but opposing the sheriff was his stupidest decision ever. Too bad Ademar died. He was my best guy. But more importantly, the city is mine and mine alone now. And I have mainly you to thank, stranger. Here's your reward as promised. For taking part in the siege of Uncle's villa, I'll add another 3500 caps to it. You've earned them.}
{1603}{}{我已经听到好消息了。我一直认为叔叔是个白痴，但反对警长是他有史以来最愚蠢的决定。可惜阿德玛死了。他是我最好的人。但更重要的是，这座城市是我的，现在只有我一个人了。我主要要感谢你，陌生人。这是你答应的报酬。参加围攻叔叔的别墅，我再加3500个瓶盖。你赢得了他们。}
#{1604}{}{Thanks Nestor, they will come in handy.}
{1604}{}{谢谢内斯特，他们会派上用场的。}
#{1605}{}{Thankee much!}
{1605}{}{非常感谢！}
#{1650}{}{And that's basically all. I won't need you any more. But feel free to visit Corath whenever you want. [His face twists into a smile.] You're now a friend of this city's ruler.}
{1650}{}{基本上就这些。我不再需要你了。但你想什么时候去看科拉斯都可以。你现在是这个城市统治者的朋友了。}
#{1651}{}{How useful. Goodbye Nestor.}
{1651}{}{多有用啊。再见，内斯特。}
#{1652}{}{Wonderful. Before I go, can you answer a few questions?}
{1652}{}{精彩的。在我走之前，你能回答几个问题吗？}
#{1653}{}{Wooow!}
{1653}{}{喔！}
#{1700}{}{I'll take over his trade with Sedit. The caravan companies will have to buy iron ore directly from me. Finally I'll have enough resources to expand the mining operation and partly switch over to machine labor. I'll also build huge furnaces to smelt all the ore. I'll make Corath iron the most sought-after commodity in the whole region.}
{1700}{}{我来接管他和塞迪特的生意。商队公司将不得不直接从我这里购买铁矿石。最后，我将有足够的资源来扩大采矿作业，并部分转向机器劳动。我还将建造巨大的熔炉来冶炼所有的矿石。我将使科拉斯铁矿成为整个地区最受欢迎的商品。}
#{1701}{}{You've got big plans. How did you manage to acquire Blaster, anyway?}
{1701}{}{你有远大的计划。你是怎么弄到爆炸机的？}
#{1702}{}{I'm sure you will. Oh, by the way, I've got a message for you from deputy sheriff Gordon. He would like to work for you.}
{1702}{}{我相信你会的。哦，顺便说一下，戈登副警长给你留了个口信。他愿意为你工作。}
#{1703}{}{I see. See you later, Nestor.}
{1703}{}{我懂了。再见，内斯特。}
#{1750}{}{Hello. What do you need?}
{1750}{}{你好。你需要什么？}
#{1751}{}{You could answer a few questions for me.}
{1751}{}{你可以回答我几个问题。}
#{1752}{}{I just stopped by to say hi.}
{1752}{}{我只是过来打个招呼。}
#{1753}{}{I just stopped by to say hi.}
{1753}{}{我只是过来打个招呼。}
#{1754}{}{Ugh.}
{1754}{}{啊。}
#{1800}{}{[There is a crazy look on Nestor's face.] My my, what a meeting. Say, you have got some nerve showing up here just like that. You destroyed everything I've worked years to build up, and you let that fat thieving bastard devour my mine! It's because of you that I ended up in this stinking hole. But now it's my turn. [He turns to his people.] Shoot this fucking son of a bitch!}
{1800}{}{[内斯特的脸上有一种疯狂的表情]天哪，真是一次会面。喂，你有点胆量就这样出现在这里。你毁了我多年来努力建立起来的一切，还让那个偷东西的混蛋吃掉了我的！就是因为你，我才进了这个臭洞。但现在轮到我了。[他转向他的人]开枪打这个狗娘养的！}
#{1801}{}{[There is a crazy look on Nestor's face.] My my, what a meeting. Say, you have got some nerve showing up here just like that. You destroyed everything I've worked years to build up, and you let that fat thieving bastard devour my mine! It's because of you that I ended up in this stinking hole. But now it's my turn. [He turns to his people.] Shoot this fucking whore!}
{1801}{}{[内斯特的脸上有一种疯狂的表情]天哪，真是一次会面。喂，你有点胆量就这样出现在这里。你毁了我多年来努力建立起来的一切，还让那个偷东西的混蛋吃掉了我的！就是因为你，我才进了这个臭洞。但现在轮到我了。[他转向他的人]射杀这个该死的婊子！}
#{1802}{}{[There is a crazy look on Nestor's face.] My my, what a meeting. Say, you have got some nerve showing up here just like that. You destroyed everything I've worked years to build up, and you let that fat thieving bastard devour my mine! Don't think I don't know what you did to Blaster. The doctor has already paid for it, and now it's your turn. [He turns to his people.] Shoot this fucking son of a bitch!}
{1802}{}{[内斯特的脸上有一种疯狂的表情]天哪，真是一次会面。喂，你有点胆量就这样出现在这里。你毁了我多年来努力建立起来的一切，还让那个偷东西的混蛋吃掉了我的！别以为我不知道你对Blaster做了什么。医生已经付了钱，现在轮到你了。[他转向他的人]开枪打这个狗娘养的！}
#{1803}{}{[There is a crazy look on Nestor's face.] My my, what a meeting. Say, you have got some nerve showing up here just like that. You destroyed everything I've worked years to build up, and you let that fat thieving bastard devour my mine! Don't think I don't know what you did to Blaster. The doctor has already paid for it, and now it's your turn. [He turns to his people.] Shoot this fucking whore!}
{1803}{}{[内斯特的脸上有一种疯狂的表情]天哪，真是一次会面。喂，你有点胆量就这样出现在这里。你毁了我多年来努力建立起来的一切，还让那个偷东西的混蛋吃掉了我的！别以为我不知道你对Blaster做了什么。医生已经付了钱，现在轮到你了。[他转向他的人]射杀这个该死的婊子！}
#{1804}{}{Uncle knew why he sent me to kill you.}
{1804}{}{叔叔知道他为什么派我来杀你。}
#{1805}{}{This'll be the last mistake of your life, Nestor!}
{1805}{}{这将是你生命中的最后一个错误，内斯特！}
#{1806}{}{Uncie!}
{1806}{}{叔叔！}
