#{100}{}{You see a man.}
{100}{}{你看到一个男人。}
#{101}{}{You see a woman.}
{101}{}{你看到一个女人。}
#{200}{}{You see an inhabitant of Corath.}
{200}{}{你看到一个科拉斯的居民。}
#{201}{}{You see an inhabitant of Corath.}
{201}{}{你看到一个科拉斯的居民。}
#{300}{}{Have you been to Wanda's brothel yet? That's the only thing strangers are ever interested in around here.}
{300}{}{你去过万达的妓院了吗？这是这里陌生人唯一感兴趣的事。}
#{301}{}{Francis is a good sheriff.}
{301}{}{弗朗西斯是个好治安官。}
#{302}{}{Try to stay out of trouble.}
{302}{}{别惹麻烦。}
#{303}{}{We don't see strangers around here much.}
{303}{}{我们在这附近很少见到陌生人。}
#{304}{}{There's a crazy murderer on the loose in the city. He cuts out the tongues of his victims.}
{304}{}{城里有个疯狂的杀人犯逍遥法外。他割下受害者的舌头。}
#{305}{}{Nestor should get rid of that repulsive mutant as soon as possible.}
{305}{}{内斯特应该尽快清除那个讨厌的变种。}
#{306}{}{If you're looking for work, try the mine. If you're desperate enough.}
{306}{}{如果你在找工作，试试我的。如果你够绝望的话。}
#{307}{}{If you're looking for work, try the mine. If you're desperate enough.}
{307}{}{如果你在找工作，试试我的。如果你够绝望的话。}
#{308}{}{There are more and more fights in the ring. We see Lawteller much more often than ever before.}
{308}{}{拳击场上的打斗越来越多。我们比以往任何时候都更经常见到律师。}
#{309}{}{You won't find a better place to drink around here than Penep's.}
{309}{}{你在这附近找不到比佩内普更好的地方喝酒了。}
#{310}{}{They say Uncle's hired more mercenaries. Who knows what he's up to.}
{310}{}{他们说叔叔雇佣了更多的雇佣军。谁知道他在干什么。}
#{311}{}{They've finally hung that murdering lunatic.}
{311}{}{他们终于绞死了那个杀人的疯子。}
#{312}{}{They've finally killed that murdering lunatic.}
{312}{}{他们终于杀了那个杀人的疯子。}
#{313}{}{The miners are supposed to be on a strike. I don't know what they're trying to prove.}
{313}{}{矿工们应该罢工了。我不知道他们想证明什么。}
#{314}{}{Have you heard about the unrest in the mine? A good thing Francis has intervened.}
{314}{}{你听说过矿场的骚乱吗？弗朗西斯介入是件好事。}
#{315}{}{Have you heard about the unrest in the mine? A good thing Francis has intervened.}
{315}{}{你听说过矿场的骚乱吗？弗朗西斯介入是件好事。}
#{316}{}{Aren't you the one who took care of Blaster?}
{316}{}{你不是那个照顾布拉斯特的人吗？}
#{317}{}{Aren't you the one who took care of Cedrick?}
{317}{}{你不是照顾塞德里克的人吗？}
#{318}{}{So Nestor's been chased out of the city. About time.}
{318}{}{所以内斯特被赶出了城市。是时候了。}
#{319}{}{Uncle shouldn't have messed with the sheriff. Now he's dead.}
{319}{}{叔叔不该惹警长。现在他死了。}
#{320}{}{Apparently, Nestor is looking to expand the mine. Have you heard?}
{320}{}{很明显，内斯特正打算扩建矿井。你听说了吗？}
#{321}{}{Where did you get them ironpants?}
{321}{}{你从哪儿弄来的铁裤子？}
#{322}{}{Have you tried walking through a wall with that?}
{322}{}{你试过用它穿墙吗？}
#{323}{}{You're scary.}
{323}{}{你真吓人。}
#{324}{}{Isn't that armor too heavy for you?}
{324}{}{你的盔甲不是太重了吗？}
#{325}{}{You better stay away from me.}
{325}{}{你最好离我远点。}
#{326}{}{Have you tried walking through a wall with that?}
{326}{}{你试过用它穿墙吗？}
#{327}{}{Where did you get them ironpants?}
{327}{}{你从哪儿弄来的铁裤子？}
#{328}{}{Where the hell did you find that?}
{328}{}{你在哪儿找到的？}
#{329}{}{Damn, what is that?!}
{329}{}{该死，那是什么？！}
#{330}{}{Yuck! Get that creep away from here.}
{330}{}{讨厌！把那家伙从这里带走。}
#{331}{}{That's disgusting!}
{331}{}{太恶心了！}
#{332}{}{Why do you drag that monster around with you?}
{332}{}{你为什么把那怪物拖来拖去？}
#{333}{}{Get rid of it before it eats you.}
{333}{}{在它吃掉你之前把它处理掉。}
#{334}{}{You must be crazy!}
{334}{}{你一定是疯了！}
#{335}{}{Where the hell did you find that?}
{335}{}{你在哪儿找到的？}
