#{100}{}{You see a child.}
{100}{}{你看到一个孩子。}
#{200}{}{You see a child from Corath.}
{200}{}{你看到一个科拉斯的孩子。}
#{300}{}{Did you come with a caravan?}
{300}{}{你是带着大篷车来的吗？}
#{301}{}{My ma told me not to talk to strangers.}
{301}{}{我妈告诉我不要和陌生人说话。}
#{302}{}{You stink like a mutant.}
{302}{}{你臭得像个变种人。}
#{303}{}{What is Sedit like?}
{303}{}{它是什么样子的？}
#{304}{}{Were you ever attacked by raiders?}
{304}{}{你被袭击过吗？}
#{305}{}{Will you stay long?}
{305}{}{你会待很久吗？}
#{306}{}{Did you come with a caravan?}
{306}{}{你是带着大篷车来的吗？}
#{307}{}{Will you also fight Blaster?}
{307}{}{你还会和爆能者战斗吗？}
#{308}{}{When I grow up I want to kill people in the ring like you.}
{308}{}{当我长大后，我想在拳击场上杀死像你这样的人。}
#{309}{}{You're the strongest person I know.}
{309}{}{你是我认识的最强壮的人。}
#{330}{}{Wooow!}
{330}{}{喔！}
#{331}{}{Wait!}
{331}{}{等待！}
#{332}{}{Coool!}
{332}{}{酷！}
#{333}{}{Oh man!}
{333}{}{哦，天哪！}
#{340}{}{Will you let me play with that?}
{340}{}{你能让我玩吗？}
#{341}{}{What does it do?}
{341}{}{它有什么作用？}
#{342}{}{Where do they sell that?}
{342}{}{他们在哪里卖？}
#{343}{}{Awesome!}
{343}{}{令人惊叹的！}
#{344}{}{You could face even Blaster in that.}
{344}{}{你可能会在这方面面临更大的挑战。}
#{350}{}{Is that your friend?}
{350}{}{那是你的朋友吗？}
#{351}{}{It's ugly!}
{351}{}{太难看了！}
#{352}{}{I'm scared.}
{352}{}{我很害怕。}
#{353}{}{Can I touch it? Wait... better not.}
{353}{}{我能摸一下吗？等待。。。最好不要。}
#{354}{}{Is that your brother?}
{354}{}{那是你哥哥吗？}
