#{99}{}{Sheriff Francis and the other policemen have escorted Nestor and his faithful into the wilderness. Their days in Corath are over. There is tension in the air.}
{99}{}{弗朗西斯警长和其他警察已经护送内斯特和他的信徒进入荒野。他们在科拉斯的日子结束了。空气中有紧张气氛。}
#{100}{}{I hope you realize what must now happen.}
{100}{}{我希望你知道现在必须发生什么。}
#{101}{}{You are no longer welcome in Corath.}
{101}{}{科拉斯不再欢迎你了。}
#{200}{}{Don't do it, Francis. Don't you understand it's all just another one of Uncle's dirty tricks? And you're doing his dirty work for him!}
{200}{}{别这样，弗朗西斯。你不明白这只是叔叔的又一个下流伎俩吗？你在替他干脏活！}
#{300}{}{Don't waste more time than you need to, Nestor. You're finished around here. If I see you ever again, you are a dead man.}
{300}{}{别浪费太多时间了，内斯特。你在这里完了。如果我再见到你，你就死定了。}
#{400}{}{I don't think so. Corath is my city. I will be back one day, whether you like it or not!}
{400}{}{我不这么认为。科拉斯是我的城市。不管你喜不喜欢，我总有一天会回来的！}
#{500}{}{I'm not seeing you leaving...}
{500}{}{我不会看到你离开。。。}
