#{100}{}{Sheriff Francis and a detachment of police arrive at Uncle's villa. But Uncle and his people don't seem to be ready to leave the city. There is tension in the air.}
{100}{}{弗朗西斯警长和一队警察到达叔叔的别墅。但是叔叔和他的人似乎还没有准备好离开这个城市。空气中有紧张气氛。}
#{600}{}{Why's Uncle wasting our time like this?}
{600}{}{叔叔为什么这样浪费我们的时间？}
#{601}{}{He knows the Law's for everybody. Even him.}
{601}{}{他知道法律适用于所有人。甚至是他。}
#{700}{}{Uncle thinks there was something off about that fight. He's decided he isn't going anywhere.}
{700}{}{舅舅认为那场打架有点不对劲。他决定哪儿也不去。}
#{800}{}{If he won't go willingly, I'll make him go.}
{800}{}{如果他不愿意去，我就让他去。}
#{900}{}{Sure, copper. We're all shitting ourselves in here. Buzz off.}
{900}{}{当然，库珀。我们都在这里拉屎。走开。}
#{1000}{}{Alright, looks like we'll have to go and get him ourselves.}
{1000}{}{好吧，看来我们得自己去找他了。}
#{1100}{}{Take care of those inside! We'll stay here and make sure none escape.}
{1100}{}{小心里面的人！我们待在这里确保没有人逃脱。}
