#{100}{}{You see a bartender.}
{100}{}{你看到一个酒保。}
#{150}{}{You see Penep.}
{150}{}{你看佩内普。}
#{200}{}{You see a chummy-looking bartender. He's looking around the bar.}
{200}{}{你看到一个看起来很亲密的酒保。他在酒吧里四处张望。}
#{250}{}{You see Penep the bartender. He's watching the customers with a friendly look on his face.}
{250}{}{你看酒保佩内普。他脸上带着友好的神情看着顾客。}
#{400}{}{You watch it. I won in the ring, this one time!}
{400}{}{你看吧。我在拳击场赢了，这一次！}
#{401}{}{I'll show you!}
{401}{}{我给你看！}
#{500}{}{Howdy pilgrim, I'm Penep. I'm in charge of this cozy establishment. What can I get you?}
{500}{}{你好，朝圣者，我是佩内普。我负责这个舒适的机构。我能给你拿什么？}
#{501}{}{A drink couldn't hurt.}
{501}{}{喝一杯也无妨。}
#{502}{}{Nothing yet. Could you answer a few questions for me?}
{502}{}{还没有。你能回答我几个问题吗？}
#{503}{}{Nothing at all. Bye.}
{503}{}{什么都没有。再见。}
#{504}{}{Drink! A drink! Gimmie drink!}
{504}{}{喝酒！喝一杯！给我喝一杯！}
#{505}{}{Noonie! Bye.}
{505}{}{诺尼！再见。}
#{550}{}{I have whatever has at least a drop of decent alcohol in it - beer, Rot Gut, hooch or rum. What's yer poison?}
{550}{}{我有任何东西至少有一滴像样的酒精在里面-啤酒，烂肠，胡说八道或朗姆酒。你的毒药是什么？}
#{551}{}{Give me a beer.}
{551}{}{给我一杯啤酒。}
#{552}{}{Give me some Rot Gut.}
{552}{}{给我一些烂肠子。}
#{553}{}{Give me the hooch.}
{553}{}{把枪给我。}
#{554}{}{Give me some rum.}
{554}{}{给我点朗姆酒。}
#{555}{}{Suddenly I don't feel thirsty any more. Could you answer a few questions for me?}
{555}{}{突然我不再感到口渴了。你能回答我几个问题吗？}
#{556}{}{Actually, never mind. Goodbye bartender.}
{556}{}{其实，没关系。再见，酒保。}
#{557}{}{Wanna beer!}
{557}{}{想喝啤酒吗！}
#{558}{}{Ugh?! Rot Gut!}
{558}{}{啊？！烂肠！}
#{559}{}{Hoochie.}
{559}{}{胡奇。}
#{560}{}{Rummy!}
{560}{}{拉米！}
#{561}{}{Mee nothee. Byebye.}
{561}{}{我什么也不见。再见。}
#{600}{}{Anything else?}
{600}{}{还有别的吗？}
#{601}{}{Give me a beer.}
{601}{}{给我一杯啤酒。}
#{602}{}{Give me some Rot Gut.}
{602}{}{给我一些烂肠子。}
#{603}{}{Give me the hooch.}
{603}{}{把枪给我。}
#{604}{}{Give me some rum.}
{604}{}{给我点朗姆酒。}
#{605}{}{No more. Could you answer a few questions for me?}
{605}{}{再也没有了。你能回答我几个问题吗？}
#{606}{}{No, that was enough. I'll be going now.}
{606}{}{不，够了。我要走了。}
#{607}{}{Wanna beer!}
{607}{}{想喝啤酒吗！}
#{608}{}{Ugh?! Rot Gut!}
{608}{}{啊？！烂肠！}
#{609}{}{Hoochie.}
{609}{}{胡奇。}
#{610}{}{Rummy!}
{610}{}{拉米！}
#{611}{}{Mee nothee. Byebye.}
{611}{}{我什么也不见。再见。}
#{650}{}{What do you need to know?}
{650}{}{你需要知道什么？}
#{651}{}{Why is there a ring in the middle of the city square?}
{651}{}{为什么城市广场中央有一个圆环？}
#{652}{}{Who's the boss around here?}
{652}{}{谁是这里的老板？}
#{653}{}{Heard any interesting stories?}
{653}{}{听说过什么有趣的故事吗？}
#{656}{}{Who's that scarred guy at the bar?}
{656}{}{酒吧里那个伤痕累累的家伙是谁？}
#{654}{}{Enough talk. Gimme a drink.}
{654}{}{别说了。给我一杯。}
#{655}{}{On nothing. Goodbye bartender.}
{655}{}{什么都没有。再见，酒保。}
#{700}{}{Just one, but it's pretty scary. There's some kinda psycho around, kills people and cuts out their tongues. He's already killed four locals, and the sheriff still can't find him. The whole city's completely flabbergasted.}
{700}{}{只有一个，但很可怕。周围有个神经病，杀人割舌头。他已经杀了四个当地人，警长仍然找不到他。整个城市都目瞪口呆。}
#{701}{}{No wonder. Can I ask you something else?}
{701}{}{难怪。我能问你点别的吗？}
#{702}{}{I need to be going now. Goodbye bartender.}
{702}{}{我得走了。再见，酒保。}
#{750}{}{That's the local Law. It determines which party of a dispute is in the right. Instead of long hassle, the Lawteller schedules a fight where the challenger fights the defender. Two enter, one comes out. Maybe this seems too savage to you, but it has its merits. Most of the people around here, with the prospect of fighting in the ring, prefer to resolve their quarrels peacefully, and whenever worst comes to worst, the conflict is resolved once-and-for-all. The Law makes Corath a safer place.}
{750}{}{这是当地的法律。它决定了争端的哪一方是正确的。与长期的争论不同，执法者安排了一场挑战者和防御者的战斗。两个进来，一个出来。也许这对你来说太野蛮了，但它有它的优点。这里的大多数人，有可能在拳击场上打仗，他们更愿意和平解决他们的争吵，每当最坏的情况出现时，冲突就会一劳永逸地解决。法律使科拉斯更安全。}
#{751}{}{If you say so. I have another question.}
{751}{}{如果你这样说。我还有一个问题。}
#{752}{}{I'll be going. Goodbye bartender.}
{752}{}{我要走了。再见，酒保。}
#{800}{}{There are three bosses in Corath, in a way: Uncle, Nestor and sheriff Francis. Though each one of them would like to be the only boss around here. Especially Uncle and Nestor, who are harsh rivals. If it weren't for the sheriff, their mercenaries would have started shooting up the place long ago.}
{800}{}{科拉斯有三个老板：叔叔、内斯特和弗朗西斯警长。尽管他们每个人都想成为这里唯一的老板。尤其是叔叔和内斯特，他们是残酷的对手。如果不是警长，他们的雇佣兵早就开始向这里开枪了。}
#{801}{}{What can you tell me about Uncle?}
{801}{}{关于叔叔你能告诉我什么？}
#{802}{}{Tell me about Nestor.}
{802}{}{告诉我内斯特的事。}
#{803}{}{Tell me more about the sheriff.}
{803}{}{告诉我更多关于警长的事。}
#{804}{}{I want to ask you something else.}
{804}{}{我想问你点别的。}
#{805}{}{I have to go. Goodbye.}
{805}{}{我得走了。再见。}
#{850}{}{Uncle used to be a great traveler and he's been to all kinds of places with his caravan, but that was a long time ago. Now he's a wealthy trader and has all the trade between our city and Sedit under his thumb. As you'd expect, this gives him quite a bit of influence in Corath.}
{850}{}{叔叔曾经是一个伟大的旅行者，他和他的大篷车去过各种各样的地方，但那是很久以前的事了。现在他是一个富有的商人，掌握着我们城市和塞迪特之间的所有交易。正如你所料，这给了他在科拉斯相当大的影响力。}
#{851}{}{I understand. Now tell me about Nestor.}
{851}{}{我理解。现在告诉我关于内斯特的事。}
#{852}{}{Now tell me about the sheriff.}
{852}{}{现在告诉我治安官的事。}
#{853}{}{I want to ask you something else.}
{853}{}{我想问你点别的。}
#{854}{}{I have to go. Goodbye bartender.}
{854}{}{我得走了。再见，酒保。}
#{900}{}{Nestor is the owner of the local iron ore mine. He manages it with an iron fist and the miners hate him for it. But his ore is the main source of wealth for us. If it weren't for that damned hole in the rock, Corath wouldn't exist.}
{900}{}{内斯特是当地铁矿的所有者。他用铁腕管理，矿工们因此恨他。但他的矿石是我们的主要财富来源。如果不是岩石上那个该死的洞，科拉斯就不存在了。}
#{901}{}{I understand. What can you tell me about Uncle?}
{901}{}{我理解。关于叔叔你能告诉我什么？}
#{902}{}{I want to know about the sheriff. Tell me more about him.}
{902}{}{我想知道治安官的事。告诉我更多关于他的事。}
#{903}{}{I want to ask you something else.}
{903}{}{我想问你点别的。}
#{904}{}{I have to go. Goodbye bartender.}
{904}{}{我得走了。再见，酒保。}
#{950}{}{Sheriff Francis is a guy as hard as a rock, and the Law means everything to him. He brought order to Corath, such that nobody dares violate it. Not even Uncle or Nestor.}
{950}{}{弗朗西斯警长是个铁石心肠的人，法律对他来说意味着一切。他给科拉斯带来了秩序，这样就没人敢违抗了。连叔叔和内斯特都没有。}
#{951}{}{I understand. What can you tell me about Uncle?}
{951}{}{我理解。关于叔叔你能告诉我什么？}
#{952}{}{Now tell me about Nestor.}
{952}{}{现在告诉我关于内斯特的事。}
#{953}{}{I want to ask you something else.}
{953}{}{我想问你点别的。}
#{954}{}{I have to go. Goodbye bartender.}
{954}{}{我得走了。再见，酒保。}
#{1000}{}{Welcome. What'll you have?}
{1000}{}{欢迎光临。你要什么？}
#{1001}{}{I've heard you helped apprehend that crazy murderer. I can't begin to tell you how grateful I am. That spectre has been haunting Corath for too long. What'll you have?}
{1001}{}{我听说你帮助逮捕了那个疯狂的杀人犯。我无法告诉你我有多感激你。那个幽灵在科拉斯身边已经太久了。你要什么？}
#{1002}{}{I've heard you helped apprehend that crazy murderer. I can't begin to tell you how grateful I am. That spectre has been haunting Corath for too long. What'll you have?}
{1002}{}{我听说你帮助逮捕了那个疯狂的杀人犯。我无法告诉你我有多感激你。那个幽灵在科拉斯身边已经太久了。你要什么？}
#{1003}{}{So, Uncle has managed to chase-off Nestor. 'Bout time. The entire city has hated Nestor since he brought in that supermutant of his. What'll you have?}
{1003}{}{所以，叔叔设法赶走了内斯特是时候了。自从内斯特把他的超级变种带来后，整个城市都恨他。你要什么？}
#{1004}{}{So, Nestor has finally taken care of Uncle. I would've expected anything, but that Uncle would turn against the Law... never that. What'll you have?}
{1004}{}{所以，内斯特终于照顾好了叔叔。我本以为什么都会发生的，但那个叔叔会违反法律。。。从来没有。你要什么？}
#{1005}{}{A little drink couldn't hurt.}
{1005}{}{喝一点也不疼。}
#{1006}{}{Can you answer a few questions for me?}
{1006}{}{你能回答我几个问题吗？}
#{1007}{}{Nothing at all. Bye.}
{1007}{}{什么都没有。再见。}
#{1008}{}{Drink! A drink! Gimmie drink!}
{1008}{}{喝酒！喝一杯！给我喝一杯！}
#{1009}{}{Noonie! Bye.}
{1009}{}{诺尼！再见。}
#{1050}{}{That's Vodka and I suggest you leave him be. He doesn't get on well with people. He used to work for Uncle but now he just spends most of his time here at my bar. Only when his money runs out does he join a caravan, and comes right back with the next one. He's a loner. It's sometimes tough to put up with his rude manners, even for me, but he always pays his bills right up to the last cap. I wish I had more regulars like that.}
{1050}{}{那是伏特加，我建议你别管他了。他和人相处不好。他以前为叔叔工作，但现在他大部分时间都在我的酒吧里。只有当他的钱用完了，他才会加入一个商队，然后带着下一个商队回来。他是个孤独的人。即使对我来说，有时也很难忍受他粗鲁的举止，但他总是付到最后一笔账。我希望有更多这样的常客。}
#{1051}{}{I'm sure you do. I have another question.}
{1051}{}{我相信你会的。我还有一个问题。}
#{1052}{}{I have to go now. Goodbye bartender.}
{1052}{}{我得走了。再见，酒保。}
