#{100}{}{You see an armed man.}
{100}{}{你看到一个持枪的人。}
#{101}{}{You see an armed woman.}
{101}{}{你看到一个持枪的女人。}
#{200}{}{You see an armed man. He looks bored.}
{200}{}{你看到一个持枪的人。他看起来很无聊。}
#{201}{}{You see an armed woman. She looks bored.}
{201}{}{你看到一个持枪的女人。她看起来很无聊。}
#{300}{}{Buzz off.}
{300}{}{走开。}
#{301}{}{If you want anything, go talk to Cedrick.}
{301}{}{如果你想要什么，去和塞德里克谈谈。}
#{302}{}{You work for Uncle?}
{302}{}{你为叔叔工作？}
#{303}{}{Without Uncle, Corath would go to hell.}
{303}{}{没有叔叔，科拉斯会下地狱。}
#{304}{}{Avoid the Iron District.}
{304}{}{避开铁区。}
#{305}{}{Cedrick is satisfied with you.}
{305}{}{塞德里克对你很满意。}
#{306}{}{So Blaster's kicked the bucket. Unbelievable.}
{306}{}{所以爆能工被解雇了。难以置信。}
#{307}{}{How's it going?}
{307}{}{怎么样？}
#{308}{}{Nestor is finally gone. Good work.}
{308}{}{内斯特终于走了。干得好。}
#{309}{}{Nestor is finally dead. Good work.}
{309}{}{内斯特终于死了。干得好。}
#{310}{}{Why are you wearing that junk?}
{310}{}{你为什么穿那件破烂衣服？}
#{311}{}{Just don't step on my toes with that.}
{311}{}{别用那个踩我的脚。}
#{312}{}{You look silly.}
{312}{}{你看起来很傻。}
#{313}{}{Don't let that creature try anything on.}
{313}{}{别让那家伙穿任何东西。}
#{314}{}{Why do you drag this trash around?}
{314}{}{你为什么把这些垃圾拖来拖去？}
#{315}{}{Keep that monster away from me.}
{315}{}{别让那怪物靠近我。}
#{320}{}{We've got the miners on a short leash. They mustn't even think they could become sloppy under Uncle.}
{320}{}{我们把矿工拴得很紧。他们甚至不能认为在叔叔的领导下他们会变得马虎。}
#{321}{}{For now, the miners are working well. Let's see if it lasts.}
{321}{}{目前，矿工们的工作情况良好。让我们看看它是否持续。}
#{322}{}{Uncle will take good care of the mines.}
{322}{}{舅舅会好好照顾这些矿的。}
#{400}{}{You shouldn't have done that.}
{400}{}{你不该那么做。}
#{401}{}{You shouldn't have done that.}
{401}{}{你不该那么做。}
#{402}{}{Now you're in trouble!}
{402}{}{现在你有麻烦了！}
#{403}{}{Uncle doesn't like troublemakers.}
{403}{}{叔叔不喜欢捣乱。}
#{404}{}{I'm going to enjoy this!}
{404}{}{我要好好享受这一切！}
#{405}{}{Damn! I'll get you for that.}
{405}{}{该死！我会为此找你的。}
#{410}{}{You're all dead!}
{410}{}{你们都死定了！}
#{411}{}{This is for Cedrick!}
{411}{}{这是给塞德里克的！}
#{412}{}{You shouldn't have come here.}
{412}{}{你不该来这里。}
#{413}{}{You shall not pass!}
{413}{}{你不能通过！}
