#{100}{}{You see a fat man.}
{100}{}{你看到一个胖子。}
#{150}{}{You see Uncle.}
{150}{}{你看叔叔。}
#{200}{}{You see an elderly fat man with fox eyes.}
{200}{}{你看到一个长着狐狸眼的老胖子。}
#{250}{}{You see Uncle. He has a fox-like look on his fat face.}
{250}{}{你看叔叔。他胖胖的脸上有一副狐狸似的表情。}
#{300}{}{Uncle has explained the basis of trade bargaining to you. Your bartering skill has increased.}
{300}{}{叔叔已经向你解释了贸易谈判的基础。你的易货技巧提高了。}
#{400}{}{Kill him!}
{400}{}{杀了他！}
#{401}{}{Kill her!}
{401}{}{杀了她！}
#{402}{}{Kill them!}
{402}{}{杀了他们！}
#{403}{}{You'll never get out of here alive!}
{403}{}{你永远不会活着离开这里！}
#{404}{}{You'll never get out of here alive!}
{404}{}{你永远不会活着离开这里！}
#{500}{}{So, you're here. [He looks you over.] I am Uncle, and if I am not mistaken, you must be }
{500}{}{所以，你来了。[他看着你]我是叔叔，如果我没弄错的话，你一定是}
#{501}{}{.}
{501}{}{.}
#{502}{}{Pleasure. What do you want to talk about?}
{502}{}{很荣幸。你想谈什么？}
#{503}{}{You're not my uncle.}
{503}{}{你不是我叔叔。}
#{504}{}{None of your business. I challenge you to the ring.}
{504}{}{不关你的事。我向你挑战拳击场。}
#{505}{}{There's been some mistake. I better leave right now.}
{505}{}{出了点差错。我最好现在就走。}
#{506}{}{Huh?!}
{506}{}{呵呵？！}
#{507}{}{Yup! Hi uncle. Where auntie?!}
{507}{}{是的！嗨，叔叔。阿姨在哪？！}
#{550}{}{I have a proposition for you. As you have undoubtedly found out, I am trying to eliminate Nestor. Corath is too small for the two of us. Only one can remain. The situation has already reached critical mass. What I need from you is to resolve this thing once and for all. You did a swell job with the miners down the mine, but no single revolt, no matter how big, can ever resolve this dispute we have here. You need to take care of Nestor himself.}
{550}{}{我有个建议给你。毫无疑问，你已经发现了，我正试图消灭内斯特。科拉斯对我们俩来说太小了。只有一个可以留下。形势已经到了危急关头。我需要你一劳永逸地解决这件事。你在井下的矿工中干得很出色，但无论多么大的叛乱，都无法解决我们这里的争端。你得照顾好内斯特自己。}
#{551}{}{I have a proposition for you. As you have undoubtedly found out, I am trying to eliminate Nestor. Corath is too small for the two of us. Only one can remain. The situation has already reached critical mass. What I need from you is to resolve this thing once and for all. You did a swell job with the miners down the mine, but no single revolt, no matter how big, can ever resolve this dispute we have here. You need to take care of Nestor himself.}
{551}{}{我有个建议给你。毫无疑问，你已经发现了，我正试图消灭内斯特。科拉斯对我们俩来说太小了。只有一个可以留下。形势已经到了危急关头。我需要你一劳永逸地解决这件事。你在井下的矿工中干得很出色，但无论多么大的叛乱，都无法解决我们这里的争端。你得照顾好内斯特自己。}
#{552}{}{I have a proposition for you. As you have undoubtedly found out, I am trying to eliminate Nestor. Corath is too small for the two of us. Only one can remain. The situation has already reached critical mass. What I need from you is to resolve this thing once and for all.}
{552}{}{我有个建议给你。毫无疑问，你已经发现了，我正试图消灭内斯特。科拉斯对我们俩来说太小了。只有一个可以留下。形势已经到了危急关头。我需要你一劳永逸地解决这件事。}
#{553}{}{I have a proposition for you. As you have undoubtedly found out, I am trying to eliminate Nestor. Corath is too small for the two of us. Only one can remain. The situation has already reached critical mass. What I need from you is to resolve this thing once and for all.}
{553}{}{我有个建议给你。毫无疑问，你已经发现了，我正试图消灭内斯特。科拉斯对我们俩来说太小了。只有一个可以留下。形势已经到了危急关头。我需要你一劳永逸地解决这件事。}
#{554}{}{What exactly do you have in mind?}
{554}{}{你到底在想什么？}
#{555}{}{What exactly do you have in mind?}
{555}{}{你到底在想什么？}
#{600}{}{Around here there's only one way to go, and that's in the ring. You must challenge Nestor to a fight there. Thanks to you we have the perfect pretense - the whole of Corath sees him as the root of all these miner uprisings. If you accuse Nestor of causing them, he will have to defend himself. In the meantime, my people will take care of things with the police and Lawteller. However, as you perhaps also know, Nestor is prepared for such an eventuality. His supermutant has so far destroyed any and every challenger I sent his way.}
{600}{}{在这里只有一条路要走，那就是拳击场。你必须在那里挑战内斯特。多亏了你，我们才有了完美的伪装——整个科拉都把他看作是所有矿工起义的根源。如果你指控内斯特制造了这一切，他将不得不为自己辩护。同时，我的人会和警察和执法人员一起处理事情。然而，正如你可能也知道的，内斯特已经准备好面对这种情况。到目前为止，他的超级变种已经摧毁了我派来的所有挑战者。}
#{601}{}{Around here there's only one way to go, and that's in the ring. You must challenge Nestor to a fight there. Thanks to you we have the perfect pretense - the whole of Corath sees him as the root of all these miner uprisings. If you accuse Nestor of causing them, he will have to defend himself. In the meantime, my people will take care of things with the police and Lawteller. However, as you perhaps also know, Nestor is prepared for such an eventuality. His supermutant has so far destroyed any and every challenger I sent his way.}
{601}{}{在这里只有一条路要走，那就是拳击场。你必须在那里挑战内斯特。多亏了你，我们才有了完美的伪装——整个科拉都把他看作是所有矿工起义的根源。如果你指控内斯特制造了这一切，他将不得不为自己辩护。同时，我的人会和警察和执法人员一起处理事情。然而，正如你可能也知道的，内斯特已经准备好面对这种情况。到目前为止，他的超级变种已经摧毁了我派来的所有挑战者。}
#{602}{}{Around here there's only one way to go, and that's in the ring. You must challenge Nestor to a fight there. Thanks to his bad reputation and your discretion we have the perfect pretense - the whole of Corath thinks that Richie's murder was Nestor's doing. If you accuse him of that, he will have to defend himself. In the meantime, my people will take care of things with the police and Lawteller. However, as you perhaps also know, Nestor is prepared for such an eventuality. His supermutant has so far destroyed any and every challenger I sent his way.}
{602}{}{在这里只有一条路要走，那就是拳击场。你必须在那里挑战内斯特。多亏了他的坏名声和你的谨慎，我们才有了完美的借口——整个科拉斯都认为里奇的谋杀是内斯特干的。如果你指控他那样做，他将不得不为自己辩护。同时，我的人会和警察和执法人员一起处理事情。然而，正如你可能也知道的，内斯特已经准备好面对这种情况。到目前为止，他的超级变种已经摧毁了我派来的所有挑战者。}
#{603}{}{Around here there's only one way to go, and that's in the ring. You must challenge Nestor to a fight there. Thanks to his bad reputation and your discretion we have the perfect pretense - the whole of Corath thinks that Richie's murder was Nestor's doing. If you accuse him of that, he will have to defend himself. In the meantime, my people will take care of things with the police and Lawteller. However, as you perhaps also know, Nestor is prepared for such an eventuality. His supermutant has so far destroyed any and every challenger I sent his way.}
{603}{}{在这里只有一条路要走，那就是拳击场。你必须在那里挑战内斯特。多亏了他的坏名声和你的谨慎，我们才有了完美的借口——整个科拉斯都认为里奇的谋杀是内斯特干的。如果你指控他那样做，他将不得不为自己辩护。同时，我的人会和警察和执法人员一起处理事情。然而，正如你可能也知道的，内斯特已经准备好面对这种情况。到目前为止，他的超级变种已经摧毁了我派来的所有挑战者。}
#{604}{}{And I'm supposed to be next in line? Why would I want that?}
{604}{}{我应该是下一个？我为什么要那样？}
#{605}{}{And I'm supposed to be next in line? Why would I want that?}
{605}{}{我应该是下一个？我为什么要那样？}
#{650}{}{[A shadow of irritation crosses his face.] I never forced any one of those people to go in the ring, they all went willingly. If, mind you, any of them had defeated Blaster and had rid me of Nestor, they would have had a fortune in caps coming to them. And these same conditions I offer to you. Furthermore, I don't maintain it has to be you in person who fights in the ring. If you can find a substitute for yourself, that would not change anything in our agreement.}
{650}{}{[愤怒的阴影掠过他的脸]我从来没有强迫那些人中的任何一个去拳击场，他们都是自愿去的。请注意，如果他们中的任何一个打败了布雷斯特，让我摆脱了内斯特，他们会得到一大笔钱。和我给你的条件一样。而且，我不认为你必须亲自在拳击场上打斗。如果你能找到一个替代品，那不会改变我们协议中的任何内容。}
#{651}{}{How many caps are we talking about here, exactly?}
{651}{}{我们到底在说几顶瓶盖？}
#{652}{}{What if I lose?}
{652}{}{如果我输了怎么办？}
#{653}{}{OK. I'm up for it.}
{653}{}{好 啊。我准备好了。}
#{654}{}{I won't do it.}
{654}{}{我不会做的。}
#{700}{}{I promised the last challenger 3000 caps. I offer you the same.}
{700}{}{我答应给最后一个挑战者3000个盖帽。我给你同样的条件。}
#{701}{}{And what if I lose?}
{701}{}{如果我输了呢？}
#{702}{}{OK. I'm up for it.}
{702}{}{好 啊。我准备好了。}
#{703}{}{I won't do it.}
{703}{}{我不会做的。}
#{750}{}{You've already answered that yourself - you would die. That is, you or your substitute, if you find one. As far as I am concerned, I would have to start looking for somebody else. The duty to leave the city after one's defeat only concerns the accused party.}
{750}{}{你自己已经回答过了-你会死的。也就是说，你或者你的替代者，如果你找到的话。就我而言，我得开始找别人了。败诉后离开这座城市的责任只与被告有关。}
#{751}{}{You've already answered that yourself - you would die. That is, you or your substitute, if you find one. As far as I am concerned, I would have to start looking for somebody else. The duty to leave the city after one's defeat only concerns the accused party.}
{751}{}{你自己已经回答过了-你会死的。也就是说，你或者你的替代者，如果你找到的话。就我而言，我得开始找别人了。败诉后离开这座城市的责任只与被告有关。}
#{752}{}{And how much would you pay me, exactly?}
{752}{}{你到底要付我多少钱？}
#{753}{}{OK. I'm up for it.}
{753}{}{好 啊。我准备好了。}
#{754}{}{I won't do it.}
{754}{}{我不会做的。}
#{800}{}{[His fat face expands into an enormous smile.] I didn't say that. A few of my guards started calling me that back when I used to travel with caravans. The nickname stuck, even after I settled in Corath. I can't even recall my original name any more. But, let's get back to why I wanted to talk to you.}
{800}{}{[他肥胖的脸上绽放出灿烂的笑容]我没那么说。我以前和大篷车一起旅行时，我的几个警卫就开始这么叫我。即使我在科拉斯定居下来，这个绰号仍然存在。我甚至想不起我原来的名字了。但是，让我们回到为什么我想和你说话。}
#{801}{}{I'm listening.}
{801}{}{我在听。}
#{850}{}{[He sighs.] That is a disappointment. I had high hopes for you. If you change your mind, my door remains open to you.}
{850}{}{[他叹了口气]真令人失望。我对你寄予厚望。如果你改变主意，我的门对你敞开。}
#{851}{}{[He sighs.] That is a disappointment. I had high hopes for you. If you change your mind, my door remains open to you.}
{851}{}{[他叹了口气]真令人失望。我对你寄予厚望。如果你改变主意，我的门对你敞开。}
#{852}{}{Don't count on it. Bye.}
{852}{}{别指望了。再见。}
#{900}{}{I was hoping you'd say that. You seem to be the right man for the job. I would hate to be wrong... for your sake, especially.}
{900}{}{我希望你会这么说。你似乎是这个工作的合适人选。我不想犯错。。。尤其是为了你。}
#{901}{}{I was hoping you'd say that. You seem to be the right woman for the job. I would hate to be wrong... for your sake, especially.}
{901}{}{我希望你会这么说。你似乎是这份工作的合适人选。我不想犯错。。。尤其是为了你。}
#{902}{}{Don't worry about me, I can manage.}
{902}{}{别担心我，我能行。}
#{903}{}{No worries. Before I go, can I ask you about something?}
{903}{}{别担心。在我走之前，我能问你一些事吗？}
#{950}{}{Absolutely. Ask away.}
{950}{}{当然。去问吧。}
#{951}{}{What will you do once Nestor leaves the city?}
{951}{}{一旦内斯特离开这座城市，你会怎么做？}
#{952}{}{What do you want to do now that you have Corath to yourself?}
{952}{}{你现在有了科拉斯你想做什么？}
#{953}{}{Your accountant Morton told me you have a monopoly on the trade with Sedit here in Corath. How did you manage it - so that the caravan companies only buy ore from you?}
{953}{}{你的会计莫顿告诉我你在科拉斯和塞迪特的交易上有垄断权。你是怎么做到的，以至于商队公司只从你这里购买矿石？}
#{954}{}{I can't think of anything. I better go.}
{954}{}{我什么都想不出来。我得走了。}
#{1000}{}{[He frowns.] Mate, you come back when you're yourself again. I have nothing to say to you in this state.}
{1000}{}{[他皱着眉头]伙计，你再恢复自我的时候再来。在这种情况下我没什么好说的。}
#{1001}{}{[He frowns.] Girl, you come back when you're yourself again. I have nothing to say to you in this state.}
{1001}{}{[他皱眉]女孩，当你重新恢复自我时你会回来的。在这种情况下我没什么好说的。}
#{1002}{}{Ugh.}
{1002}{}{啊。}
#{1050}{}{As the formal challenger, I will take possession of his mine. After that, I will finally control the mining of iron ore and I will not need to share my sales profits with anyone. The whole of Corath will prosper with me.}
{1050}{}{作为正式的挑战者，我将占有他的矿。之后，我将最终控制铁矿石的开采，我将不需要与任何人分享我的销售利润。整个科拉斯都会和我一起繁荣。}
#{1051}{}{There is one more thing. Your accountant Morton told me you have a monopoly on the trade with Sedit here in Corath. How did you manage it - so that the caravan companies only buy ore from you?}
{1051}{}{还有一件事。你的会计莫顿告诉我你在科拉斯和塞迪特的交易上有垄断权。你是怎么做到的，以至于商队公司只从你这里购买矿石？}
#{1052}{}{I'm sure. See you, Uncle.}
{1052}{}{我肯定。再见，叔叔。}
#{1100}{}{There is no mystery there. My entire success is based on a simple truth I came to understand back when I travelled with my own caravan. Every acquisition and sale is mainly about negotiating. Over the years I've come to understand when to be tough and when to withdraw. If you can convince a raider or a stranger who doesn't even speak your language to trade with you, you can even convince the proud companies of Sedit to close a good contract with you. It's just a game you play with a fixed set of rules. As soon as you master them, the way to riches is wide open.}
{1100}{}{那里没有什么神秘的东西。我的全部成功是建立在一个简单的事实上的，当我带着自己的大篷车旅行时，我明白了这个道理。每一次收购和出售主要是谈判。这些年来，我逐渐明白什么时候该强硬，什么时候该退出。如果你能说服一个甚至不会说你的语言的袭击者或陌生人与你交易，你甚至可以说服Sedit引以为豪的公司与你签订一份好合同。这只是一个游戏，你玩一套固定的规则。一旦你掌握了它们，致富之路就敞开了。}
#{1101}{}{That's good to know. What will you do once Nestor leaves the city?}
{1101}{}{很高兴知道。一旦内斯特离开这座城市，你会怎么做？}
#{1102}{}{What do you want to do, now that you have Corath to yourself?}
{1102}{}{既然你有了科拉斯，你想做什么？}
#{1103}{}{Interesting. See you later, Uncle.}
{1103}{}{很有趣。再见，叔叔。}
#{1150}{}{Cedrick must have had his reasons to let you in here. And I want to know them.}
{1150}{}{塞德里克一定有他的理由让你进来。我想认识他们。}
#{1151}{}{Uh, actually, it's me. What did you want to talk about?}
{1151}{}{呃，实际上，是我。你想谈什么？}
#{1152}{}{Never mind. I came to challenge you to the ring.}
{1152}{}{不要介意。我是来挑战你的。}
#{1153}{}{Never mind. I came to challenge you to the ring.}
{1153}{}{不要介意。我是来挑战你的。}
#{1154}{}{Well, that's just too bad. 'Cause it's time to die, fatty!}
{1154}{}{好吧，那太糟糕了因为是时候死了，胖子！}
#{1200}{}{[A look of surprise forms on his face.] Well that is unexpected. I think I know who sent you. But may I know what your excuse is?}
{1200}{}{[他脸上露出惊讶的表情]那是出乎意料的。我想我知道是谁派你来的。但我能知道你的借口是什么吗？}
#{1201}{}{I was sent by Nestor. He asks for your exile from the city because of the miner unrest you helped provoke through Richie. Nestor's people are already taking care of the formalities with the police and Lawteller.}
{1201}{}{我是内斯特派来的。他要求你从城里流放出去，因为你通过里奇挑起了矿工骚乱。内斯特的人已经在处理警察和律师的手续了。}
#{1202}{}{I was sent by Nestor. He asks for your exile from the city because of the miner unrest you were trying to provoke through Richie. Nestor's people are already taking care of the formalities with the police and Lawteller.}
{1202}{}{我是内斯特派来的。他要求你离开城市，因为你试图通过里奇挑起矿工骚乱。内斯特的人已经在处理警察和律师的手续了。}
#{1203}{}{I was sent by Nestor. He asks for your exile from the city for having a man named Richie killed. Nestor's people are already taking care of the formalities with the police and Lawteller.}
{1203}{}{我是内斯特派来的。他要求你离开这个城市，因为你杀了一个叫里奇的人。内斯特的人已经在处理警察和律师的手续了。}
#{1204}{}{I have no time for this. I'll just kill you!}
{1204}{}{我没时间做这个。我就杀了你！}
#{1205}{}{Sorry, pal, I was just teasing. What did you want to talk to me about?}
{1205}{}{抱歉，伙计，我只是在开玩笑。你想跟我说什么？}
#{1206}{}{Sorry, pal, I was just teasing. What did you want to talk to me about?}
{1206}{}{抱歉，伙计，我只是在开玩笑。你想跟我说什么？}
#{1250}{}{So, Nestor's really trying it on. He will regret that. And as far as you're concerned, you're dead already. That is, if you are brave enough to stand in the ring yourself. Cedrick will make sure your last minutes on Earth end in the appropriate level of misery.}
{1250}{}{所以，内斯特真的在试穿。他会后悔的。就你而言，你已经死了。也就是说，如果你有足够的勇气自己站在拳击场上。塞德里克将确保你在地球上的最后一分钟结束在适当的痛苦水平。}
#{1251}{}{So, Nestor's really trying it on. He will regret that. And as far as you're concerned, you're dead already. That is, if you are brave enough to stand in the ring yourself. Cedrick will make sure your last minutes on Earth end in the appropriate level of misery.}
{1251}{}{所以，内斯特真的在试穿。他会后悔的。就你而言，你已经死了。也就是说，如果你有足够的勇气自己站在拳击场上。塞德里克将确保你在地球上的最后一分钟结束在适当的痛苦水平。}
#{1252}{}{We shall see which one of us will suffer in the end. [Go to the ring.]}
{1252}{}{我们将看看我们中的哪一个最终会受苦。[去拳击场]}
#{1300}{}{Well, feeling better?}
{1300}{}{感觉好些了吗？}
#{1301}{}{Well, feeling better?}
{1301}{}{感觉好些了吗？}
#{1302}{}{Uh, I'm fine. What did you want to talk about?}
{1302}{}{呃，我很好。你想谈什么？}
#{1303}{}{Never mind. I came to challenge you to the ring.}
{1303}{}{不要介意。我是来挑战你的。}
#{1304}{}{Never mind. I came to challenge you to the ring.}
{1304}{}{不要介意。我是来挑战你的。}
#{1305}{}{Give me a moment longer.}
{1305}{}{再给我一点时间。}
#{1306}{}{Ugh.}
{1306}{}{啊。}
#{1350}{}{Have you changed your mind? Like I said, we can still strike a deal.}
{1350}{}{你改变主意了吗？就像我说的，我们还是可以达成协议的。}
#{1351}{}{Have you changed your mind? Like I said, we can still strike a deal.}
{1351}{}{你改变主意了吗？就像我说的，我们还是可以达成协议的。}
#{1352}{}{Alright. I will challenge Nestor and take care of his supermutant.}
{1352}{}{好吧。我要挑战内斯特，照顾他的超级变异体。}
#{1353}{}{I doubt that. I came to challenge you to the ring.}
{1353}{}{我对此表示怀疑。我是来挑战你的。}
#{1354}{}{I doubt that. I came to challenge you to the ring.}
{1354}{}{我对此表示怀疑。我是来挑战你的。}
#{1355}{}{Not interested. Bye.}
{1355}{}{不感兴趣。再见。}
#{1356}{}{Ugh.}
{1356}{}{啊。}
#{1400}{}{So far, I don't seem to have registered Blaster's death, nor Nestor's expulsion from the city. Come back when it's arranged.}
{1400}{}{到目前为止，我似乎还没有记录爆炸机的死亡，也没有内斯特被驱逐出这个城市。安排好了再来。}
#{1401}{}{Before I go, can I ask you something?}
{1401}{}{在我走之前，我能问你一件事吗？}
#{1402}{}{Just leaving.}
{1402}{}{就要走了。}
#{1403}{}{Not on my agenda. I came to challenge you to the ring.}
{1403}{}{不在我的议事日程上。我是来挑战你的。}
#{1404}{}{Not on my agenda. I came to challenge you to the ring.}
{1404}{}{不在我的议事日程上。我是来挑战你的。}
#{1405}{}{Ugh.}
{1405}{}{啊。}
#{1450}{}{Cedrick has already told me everything. You've made me the new owner of the mine, and thus the richest person in Corath. It's only fair that you receive your share of the profits. [He gives you 3000 caps.] But there is one more thing which you could take care of for me.}
{1450}{}{塞德里克已经把一切都告诉我了。你让我成为了新的矿主，从而成为科拉斯最富有的人。你得到你应得的那份利润才是公平的。[他给你3000顶瓶盖]但是还有一件事你可以帮我处理。}
#{1451}{}{Cedrick has already told me everything. You've made me the new owner of the mine, and thus the richest person in Corath. It's only fair that you receive your share of the profits. [He gives you 3000 caps.] But there is one more thing which you could take care of for me.}
{1451}{}{塞德里克已经把一切都告诉我了。你让我成为了新的矿主，从而成为科拉斯最富有的人。你得到你应得的那份利润才是公平的。[他给你3000顶瓶盖]但是还有一件事你可以帮我处理。}
#{1452}{}{Thanks. What is this other thing?}
{1452}{}{谢谢。另一件事是什么？}
#{1453}{}{Thanks!}
{1453}{}{谢谢！}
#{1500}{}{You know, Cedrick also told me that Nestor didn't accept his fate with a cool head. Apparently, he is planning to return. Even though his defeat in the ring took away pretty much all of his assets, I cannot take this threat lightly. So, I want you to find Nestor and finish him off. Only then will our quarrel be definitively over. After all, the same goes for you too. I doubt Nestor will easily forgive you for killing Blaster and for his own forced exile.}
{1500}{}{你知道，塞德里克还告诉我内斯特没有冷静地接受自己的命运。显然，他正打算回来。尽管他在拳击场上的失败夺走了他几乎所有的财产，但我不能对这种威胁掉以轻心。所以，我要你找到内斯特，干掉他。只有到那时，我们的争吵才会彻底结束。毕竟，你也一样。我怀疑内斯特会轻易原谅你杀了布雷斯特和他自己被迫流放。}
#{1501}{}{You know, Cedrick also told me that Nestor didn't accept his fate with a cool head. Apparently, he is planning to return. Even though his defeat in the ring took away pretty much all of his assets, I cannot take this threat lightly. So, I want you to find Nestor and finish him off. Only then will our quarrel be definitively over. After all, the same goes for you too. I doubt Nestor will easily forgive you for killing Blaster and for his own forced exile.}
{1501}{}{你知道，塞德里克还告诉我内斯特没有冷静地接受自己的命运。显然，他正打算回来。尽管他在拳击场上的失败夺走了他几乎所有的财产，但我不能对这种威胁掉以轻心。所以，我要你找到内斯特，干掉他。只有到那时，我们的争吵才会彻底结束。毕竟，你也一样。我怀疑内斯特会轻易原谅你杀了布雷斯特和他自己被迫流放。}
#{1502}{}{You know, Cedrick also told me that Nestor didn't accept his fate with a cool head. Apparently, he is planning to return. Even though his defeat in the ring took a lot from him, he still has enough mercenaries for me to take his threat seriously. So, I want you to find Nestor and finish him off. Only then will our quarrel be definitively over. After all, the same goes for you too. I doubt Nestor will easily forgive you for killing Blaster and for his own forced exile.}
{1502}{}{你知道，塞德里克还告诉我内斯特没有冷静地接受自己的命运。显然，他正打算回来。尽管他在拳击场上的失败让他付出了很多，但他仍然有足够的雇佣兵让我认真对待他的威胁。所以，我要你找到内斯特，干掉他。只有到那时，我们的争吵才会彻底结束。毕竟，你也一样。我怀疑内斯特会轻易原谅你杀了布雷斯特和他自己被迫流放。}
#{1503}{}{You know, Cedrick also told me that Nestor didn't accept his fate with a cool head. Apparently, he is planning to return. Even though his defeat in the ring took a lot from him, he still has enough mercenaries for me to take his threat seriously. So, I want you to find Nestor and finish him off. Only then will our quarrel be definitively over. After all, the same goes for you too. I doubt Nestor will easily forgive you for killing Blaster and for his own forced exile.}
{1503}{}{你知道，塞德里克还告诉我内斯特没有冷静地接受自己的命运。显然，他正打算回来。尽管他在拳击场上的失败让他付出了很多，但他仍然有足够的雇佣兵让我认真对待他的威胁。所以，我要你找到内斯特，干掉他。只有到那时，我们的争吵才会彻底结束。毕竟，你也一样。我怀疑内斯特会轻易原谅你杀了布雷斯特和他自己被迫流放。}
#{1504}{}{OK, you've convinced me. Nestor must die. But first I need to know where to look for him.}
{1504}{}{好吧，你说服我了。内斯特必须死。但首先我要知道去哪里找他。}
#{1505}{}{You will need to find someone else for this job.}
{1505}{}{你需要找其他人来做这份工作。}
#{1506}{}{Uh... Noooo?}
{1506}{}{休斯敦大学。。。不知道？}
#{1550}{}{Unfortunately, I don't know the location of his hideout exactly. Although I would like to know where he'd need to crawl under with all his hired killers so as not to attract unwanted attention. But I doubt he would have gone far. I guess he just withdrew to one of the surrounding towns where he's trying to recruit enough mercenaries to attack Corath. Try Sedit or Albuquerque.}
{1550}{}{不幸的是，我不知道他藏身处的确切位置。尽管我想知道他需要在哪里和他雇佣的杀手混在一起以免引起不必要的注意。但我怀疑他会走得很远。我猜他刚刚撤退到附近的一个城镇，在那里他试图招募足够的雇佣军来攻击科拉斯。试试塞迪特或阿尔伯克基。}
#{1551}{}{I'll look for him there.}
{1551}{}{我在那里找他。}
#{1600}{}{I suggest eliminating Nestor as soon as possible. You mustn't give him time to regain strength. As proof of his demise, bring me back his golden tooth. I'd like to have something to remember him by. [He smiles his widest smile.]}
{1600}{}{我建议尽快淘汰内斯特。你不能给他时间恢复体力。作为他死亡的证据，把他的金牙还给我。我想借点东西来纪念他。[他笑得最灿烂。]}
#{1601}{}{I suggest eliminating Nestor as soon as possible. You mustn't give him time to regain strength. As proof of his demise, bring me back his golden tooth. I'd like to have something to remember him by. [He smiles his widest smile.}
{1601}{}{我建议尽快淘汰内斯特。你不能给他时间恢复体力。作为他死亡的证据，把他的金牙还给我。我想借点东西来纪念他。[他笑得最灿烂。}
#{1602}{}{OK, Uncle, you'll get your souvenir.}
{1602}{}{好的，叔叔，你会拿到纪念品的。}
#{1603}{}{And have it you shall. Before I go, can I ask you something?}
{1603}{}{你应该拥有它。在我走之前，我能问你一件事吗？}
#{1650}{}{As the formal challenger, I have been awarded with Nestor's mine. Now I finally control the extraction of iron ore and I don't have to split the profits with anyone. The whole of Corath will prosper from my wealth.}
{1650}{}{作为正式的挑战者，我获得了内斯特的奖章。现在我终于控制了铁矿石的开采，我不必和任何人分享利润。我的财富将使整个科拉斯兴旺发达。}
#{1651}{}{I'm sure it will. I'll be going now.}
{1651}{}{我肯定会的。我要走了。}
#{1700}{}{Not a wise decision, but it's what you have chosen. At any rate, make sure to be careful.}
{1700}{}{这不是一个明智的决定，但这是你的选择。无论如何，一定要小心。}
#{1701}{}{Don't worry about me. Bye.}
{1701}{}{别担心我。再见。}
#{1702}{}{Ugh.}
{1702}{}{啊。}
#{1750}{}{[A look of surprise forms on his face.] Well, that is unexpected. I think I know who sent you. But may I know what your excuse is?}
{1750}{}{[他脸上露出惊讶的表情]好吧，那是出乎意料的。我想我知道是谁派你来的。但我能知道你的借口是什么吗？}
#{1751}{}{I was sent by Nestor. He asks for your exile from the city because of the miner unrest you helped provoke through Richie. Nestor's people are already taking care of the formalities with the police and Lawteller.}
{1751}{}{我是内斯特派来的。他要求你从城里流放出去，因为你通过里奇挑起了矿工骚乱。内斯特的人已经在处理警察和律师的手续了。}
#{1752}{}{I was sent by Nestor. He asks for your exile from the city because of the miner unrest you were trying to provoke through Richie. Nestor's people are already taking care of the formalities with the police and Lawteller.}
{1752}{}{我是内斯特派来的。他要求你离开城市，因为你试图通过里奇挑起矿工骚乱。内斯特的人已经在处理警察和律师的手续了。}
#{1753}{}{I was sent by Nestor. He asks for your exile from the city for having a man named Richie killed. Nestor's people are already taking care of the formalities with the police and Lawteller.}
{1753}{}{我是内斯特派来的。他要求你离开这个城市，因为你杀了一个叫里奇的人。内斯特的人已经在处理警察和律师的手续了。}
#{1754}{}{I have no time for this. I'll just kill you!}
{1754}{}{我没时间做这个。我就杀了你！}
#{1755}{}{Oh forget it. Bye.}
{1755}{}{算了吧。再见。}
#{1800}{}{Good to see you again. What brings you here?}
{1800}{}{很高兴再次见到你。什么风把你吹来了？}
#{1801}{}{I've thought about what you said. Nestor really needs to be killed. But first I need to know where to look for him.}
{1801}{}{我考虑过你说的话。内斯特真的需要被杀。但首先我要知道去哪里找他。}
#{1802}{}{I've thought about what you said. Nestor really needs to be killed. But first I need to know where to look for him.}
{1802}{}{我考虑过你说的话。内斯特真的需要被杀。但首先我要知道去哪里找他。}
#{1803}{}{I have some important news about Nestor for you.}
{1803}{}{我有一些关于内斯特的重要消息要告诉你。}
#{1804}{}{Can I ask you something?}
{1804}{}{我能问你件事吗？}
#{1805}{}{I just wanted to say "hi".}
{1805}{}{我只是想说声“嗨”。}
#{1806}{}{I just wanted to say "hi".}
{1806}{}{我只是想说声“嗨”。}
#{1807}{}{Ugh.}
{1807}{}{啊。}
#{1850}{}{Well, tell me. I'm all ears.}
{1850}{}{好吧，告诉我。我洗耳恭听。}
#{1851}{}{He's dead. He sends his regards, and also this. [Give him Nestor's gold tooth.]}
{1851}{}{他死了。他向你问好，还有这个。[把内斯特的金牙给他。]}
#{1852}{}{Oh, it's nothing. I have to go now.}
{1852}{}{哦，没什么。我得走了。}
#{1900}{}{[He inspects the tooth carefully.] So Nestor's no longer in the land of the living. I must say, that takes a load off me. Even without his iron mine he was a dangerous enemy. You've done a damn fine job. [He gives you 4000 caps.] You deserve every last one of them.}
{1900}{}{[他仔细检查牙齿]所以内斯特已经不在活人的土地上了。我必须说，这减轻了我的负担。即使没有他的铁矿，他也是一个危险的敌人。你做得很好。[他给了你4000顶瓶盖]你配得上每一顶。}
#{1901}{}{[He inspects the tooth carefully.] So Nestor's no longer in the land of the living. I must say, that takes a load off me. Even without his iron mine he was a dangerous enemy. You've done a damn fine job. [He gives you 4000 caps.] You deserve every last one of them.}
{1901}{}{[他仔细检查牙齿]所以内斯特已经不在活人的土地上了。我必须说，这减轻了我的负担。即使没有他的铁矿，他也是一个危险的敌人。你做得很好。[他给了你4000顶瓶盖]你配得上每一顶。}
#{1902}{}{Thanks. I'll put them to good use.}
{1902}{}{谢谢。我会好好利用它们的。}
#{1950}{}{I have no more work for you. I'm grateful for your services. Remember, you'll always be welcome in this city. At least as long as I'm in charge.}
{1950}{}{我没有更多的工作给你了。我很感谢你的服务。记住，这个城市永远欢迎你。至少在我负责的时候。}
#{1951}{}{I have no more work for you. I'm grateful for your services. Remember, you'll always be welcome in this city. At least as long as I'm in charge.}
{1951}{}{我没有更多的工作给你了。我很感谢你的服务。记住，这个城市永远欢迎你。至少在我负责的时候。}
#{1952}{}{Maybe I'll stop by sometime. Goodbye, Uncle.}
{1952}{}{也许我什么时候过来看看。再见，叔叔。}
#{1953}{}{Appreciate it. Before I go, can I ask you something?}
{1953}{}{谢谢你。在我走之前，我能问你一件事吗？}
#{2000}{}{Oh, hello. Cedrick warned me you'd be strange, but he didn't mention how much. Auntie is not in right now, but I have your reward for you. [He gives you the caps.] Enjoy them any way you can.}
{2000}{}{哦，你好。塞德里克警告过我你会很奇怪，但他没说有多奇怪。阿姨现在不在，但我有你的赏金给你。[他给你瓶盖]尽情享受吧。}
#{2001}{}{Thankee Uncle!}
{2001}{}{谢谢叔叔！}
#{2050}{}{Yes, I am your uncle, and I need something from you. You beat that evil mutant, but his master Nestor is still at large. Do you think you could find him and kill him for me? It would really help me a lot.}
{2050}{}{是的，我是你叔叔，我需要你的帮助。你打败了那个邪恶的变种人，但他的主人内斯特仍然逍遥法外。你能帮我找到他然后杀了他吗？这对我真的很有帮助。}
#{2051}{}{Yes, I am your uncle, and I need something from you. You beat that evil mutant, but his master Nestor is still at large. Do you think you could find him and kill him for me? It would really help me a lot.}
{2051}{}{是的，我是你叔叔，我需要你的帮助。你打败了那个邪恶的变种人，但他的主人内斯特仍然逍遥法外。你能帮我找到他然后杀了他吗？这对我真的很有帮助。}
#{2052}{}{}
{2052}{}{}
#{2053}{}{ will do for uncle!}
{2053}{}{会为叔叔做的！}
#{2054}{}{Ugm, must that?}
{2054}{}{嗯，一定是吗？}
#{2100}{}{I knew you wouldn't fail your uncle. Nestor will likely hide among murderers and criminals. That is where he belongs now. Oh, and bring me something to remember him by. I would like to get his gold tooth. Do you understand?}
{2100}{}{我就知道你不会辜负你叔叔。内斯特很可能躲在杀人犯和罪犯中间。那是他现在的归属。哦，给我带点东西来纪念他。我想要他的金牙。你明白吗？}
#{2101}{}{[Nod.] Goldie chomper yeah!}
{2101}{}{[点头]戈尔迪·乔珀耶！}
#{2150}{}{Oh, come now, we are family. And family should help each other. You know that much, don't you?}
{2150}{}{哦，来吧，我们是一家人。家人应该互相帮助。你知道那么多，不是吗？}
#{2151}{}{Ugh, oh yeah.}
{2151}{}{啊，哦，是的。}
