#{100}{}{You see a man with a burned face.}
{100}{}{你看到一个脸被烧伤的人。}
#{150}{}{You see Vodka.}
{150}{}{你看伏特加。}
#{200}{}{You see a man with profound burns on his face. He doesn't look like anyone to mess with.}
{200}{}{你看到一个脸上有严重烧伤的人。他看起来不像是什么人惹的祸。}
#{250}{}{You see the man everyone calls Vodka. As usual, he is spending his time in a bar, but alcohol doesn't seem to affect him at all.}
{250}{}{大家都叫他伏特加。像往常一样，他在酒吧里度过时光，但酒精似乎一点也不影响他。}
#{300}{}{Hurry up, I want Cedrick in the ring. I'm going to enjoy that fight.}
{300}{}{快点，我要塞德里克上场。我会喜欢那场比赛的。}
#{301}{}{::He ignores you.::}
{301}{}{●他不理你。：：}
#{302}{}{Goodbye, stinkhole!}
{302}{}{再见，臭洞！}
#{303}{}{::He nods in greeting.::}
{303}{}{●他点头致意：}
#{304}{}{There is no point in sticking around here any more.}
{304}{}{再呆在这里也没有意义了。}
#{350}{}{Cedrick, you're not going to hide from me any longer! You and Uncle are finished.}
{350}{}{塞德里克，你不能再瞒着我了！你和叔叔完了。}
#{351}{}{I'm not afraid of you, Vodka. You're a wash-out, just in case you don't know.}
{351}{}{我不怕你，伏特加。如果你不知道的话，你就是个废物。}
#{500}{}{[Even though you approach him, he does not acknowledge your presence. He finishes the drink in front of him and puts a fresh cigarette in his mouth.]}
{500}{}{[即使你接近他，他也不承认你的存在。他喝完面前的酒，嘴里叼着一支新烟。]}
#{501}{}{[Even though you approach him, he does not acknowledge your presence. He finishes the drink in front of him and puts a fresh cigarette in his mouth.]}
{501}{}{[即使你接近他，他也不承认你的存在。他喝完面前的酒，嘴里叼着一支新烟。]}
#{502}{}{[Light his cigarette.]}
{502}{}{[点燃他的香烟。]}
#{503}{}{[Wait.]}
{503}{}{[等等。]}
#{504}{}{Hey man, I want to talk to you.}
{504}{}{嘿，伙计，我想和你谈谈。}
#{550}{}{[In the glow of the lighter you can clearly see deep burns on one entire half of his face. As if he was waiting for someone to light him up, he doesn't move a muscle and keeps ignoring you. The bartender approaches and refills his empty glass.]}
{550}{}{[在打火机的辉光下，你可以清楚地看到他整个半张脸上的深度烧伤。就好像他在等别人把他点燃一样，他一动不动，一直不理你。酒保走过来，把空杯子倒满了}
#{551}{}{[In the glow of the lighter you can clearly see deep burns on one entire half of his face. As if he was waiting for someone to light him up, he doesn't move a muscle and keeps ignoring you. The bartender approaches and refills his empty glass.]}
{551}{}{[在打火机的辉光下，你可以清楚地看到他整个半张脸上的深度烧伤。就好像他在等别人把他点燃一样，他一动不动，一直不理你。酒保走过来，把空杯子倒满了}
#{552}{}{I'd like to ask you a few questions.}
{552}{}{我想问你几个问题。}
#{553}{}{I'd like to ask you a few questions.}
{553}{}{我想问你几个问题。}
#{554}{}{Look, I'm over here, man. Don't ignore me! I have some questions.}
{554}{}{听着，我在这里，伙计。别忽视我！我有一些问题。}
#{600}{}{[The man doesn't bother looking for a lighter; the bartender comes and lights up for him, before refilling his empty glass. In the glow of the lighter you can clearly see deep burns on one entire half of the man's face. He keeps ignoring you.]}
{600}{}{[那人懒得找打火机；酒保过来为他点灯，然后再倒满他的空杯子。在打火机的辉光下，你可以清楚地看到这个人的整个半张脸上都有深度烧伤。他一直不理你}
#{601}{}{[The man doesn't bother looking for a lighter; the bartender comes and lights up for him, before refilling his empty glass. In the glow of the lighter you can clearly see deep burns on one entire half of the man's face. He keeps ignoring you.]}
{601}{}{[那人懒得找打火机；酒保过来为他点灯，然后再倒满他的空杯子。在打火机的辉光下，你可以清楚地看到这个人的整个半张脸上都有深度烧伤。他一直不理你}
#{602}{}{I'd like to ask you a few questions.}
{602}{}{我想问你几个问题。}
#{603}{}{I'd like to ask you a few questions.}
{603}{}{我想问你几个问题。}
#{604}{}{Look, I'm over here, man. Don't ignore me! I have some questions.}
{604}{}{听着，我在这里，伙计。别忽视我！我有一些问题。}
#{605}{}{Maan! What you?!}
{605}{}{马恩！你说什么？！}
#{650}{}{[He looks at you with disgust.]}
{650}{}{[他厌恶地看着你。]}
#{651}{}{I'd like to learn more about the city.}
{651}{}{我想更多地了解这个城市。}
#{652}{}{I'd like to learn more about you.}
{652}{}{我想进一步了解你。}
#{653}{}{I'll buy you a drink and we can talk.}
{653}{}{我请你喝一杯，我们可以谈谈。}
#{654}{}{Are you Vodka? They say you used to work for Uncle. Perhaps you could tell me something about him. Or perhaps about Nestor?}
{654}{}{你是伏特加吗？他们说你以前为叔叔工作。也许你能告诉我一些关于他的事。或者关于内斯特？}
#{655}{}{OK. Forget it.}
{655}{}{好 啊。算了吧。}
#{656}{}{Ugh... Um-huh.}
{656}{}{呃。。。嗯哼。}
#{700}{}{Find some loser to do that. I'm sure there are plenty people who couldn't imagine anything more entertaining than blabbing about this hole. And you don't even need to go too far. [He glances at the bartender.]}
{700}{}{找个失败者来做。我相信有很多人想象不出有什么比在这个洞里唠叨更有趣的了。你甚至不需要走得太远。[他瞥了一眼酒保。]}
#{701}{}{I'd like to learn more about you.}
{701}{}{我想进一步了解你。}
#{702}{}{I'll buy you a drink and we can talk.}
{702}{}{我请你喝一杯，我们可以谈谈。}
#{703}{}{Are you Vodka? They say you used to work for Uncle. Perhaps you could tell me something about him. Or perhaps about Nestor?}
{703}{}{你是伏特加吗？他们说你以前为叔叔工作。也许你能告诉我一些关于他的事。或者关于内斯特？}
#{704}{}{OK. Forget it.}
{704}{}{好 啊。算了吧。}
#{750}{}{Never you mind. I don't intend to talk to you. That's all you need to know about me.}
{750}{}{别介意。我不想和你说话。你只需要知道我这些。}
#{751}{}{I'd like to learn more about the city.}
{751}{}{我想更多地了解这个城市。}
#{752}{}{I'll buy you a drink and we can talk.}
{752}{}{我请你喝一杯，我们可以谈谈。}
#{753}{}{Are you Vodka? They say you used to work for Uncle. Perhaps you could tell me something about him. Or perhaps about Nestor?}
{753}{}{你是伏特加吗？他们说你以前为叔叔工作。也许你能告诉我一些关于他的事。或者关于内斯特？}
#{754}{}{OK. Forget it.}
{754}{}{好 啊。算了吧。}
#{800}{}{Yeah, I did. I was his deputy, or so Uncle called it. I don't intend to spend time talking about either of those bastards to someone who doesn't know shit about how this city works. It's better you stay away from them. You can't trust them.}
{800}{}{是的，我做了。我是他的副手，或者叔叔这么叫。我不想花时间跟一个对这个城市的运作一无所知的人谈论那些混蛋。你最好离他们远点。你不能相信他们。}
#{801}{}{Yeah, I did. I was his deputy, or so Uncle called it. I don't intend to spend time talking about either of those bastards to someone who doesn't know shit about how this city works. It's better you stay away from them. You can't trust them.}
{801}{}{是的，我做了。我是他的副手，或者叔叔这么叫。我不想花时间跟一个对这个城市的运作一无所知的人谈论那些混蛋。你最好离他们远点。你不能相信他们。}
#{802}{}{A little too late for that advice, I'm already involved with them.}
{802}{}{有点太迟了，我已经和他们扯上关系了。}
#{803}{}{A little too late for that advice, I'm already involved with them.}
{803}{}{有点太迟了，我已经和他们扯上关系了。}
#{804}{}{Dammit, I was asking precisely to learn how things run around here. Nuts to you, I'll find out myself.}
{804}{}{该死，我问的正是要了解这里的情况。你疯了，我自己会发现的。}
#{805}{}{Dammit, I was asking precisely to learn how things run around here. Nuts to you, I'll find out myself.}
{805}{}{该死，我问的正是要了解这里的情况。你疯了，我自己会发现的。}
#{850}{}{Your funeral. You can't trust them. Uncle or Nestor. They don't keep their word. What is it? Are they after each other? I don't know why I even ask...}
{850}{}{你的葬礼。你不能相信他们。叔叔或内斯特。他们不遵守诺言。它是什么？他们在互相追逐吗？我不知道我为什么问。。。}
#{851}{}{So can you tell me anything about Nestor?}
{851}{}{你能告诉我关于内斯特的事吗？}
#{852}{}{What can you tell me about Uncle? I'm sure he pays well.}
{852}{}{关于叔叔你能告诉我什么？我肯定他薪水很高。}
#{854}{}{Anyway, what happened? I mean, why don't you work for Uncle any more? Did you not have the balls for it anymore?}
{854}{}{不管怎样，发生了什么？我是说，你为什么不再为叔叔工作了？你不再有胆量了吗？}
#{855}{}{Yeah, something like. You know what? I'll come by another time.}
{855}{}{是的，差不多。你知道吗？我改天再来。}
#{900}{}{That pathetic midget sure knows how to get what he wants, I'll give him that. It was hard enough to ensure Uncle's influence around here, with him constantly undermining us. He proved to be a tougher enemy than either Uncle or me had thought back then. In case you didn't know, Nestor goes way back in this shithole. But all in all, he's just a loser hiding behind a mutant. He makes me sick.}
{900}{}{那个可怜的侏儒知道怎么得到他想要的东西，我会给他的。很难保证叔叔在这里的影响力，因为他一直在暗中破坏我们。事实证明，他是一个比我和叔叔当时想的都要厉害的敌人。如果你不知道的话，内斯特早就在这鬼地方了。但总而言之，他只是个躲在变种人后面的失败者。他让我恶心。}
#{901}{}{I'd like to learn more.}
{901}{}{我想了解更多。}
#{902}{}{Thanks for your opinion. I don't need to hear any more.}
{902}{}{谢谢你的意见。我不需要再听了。}
#{950}{}{That's why I used to work for him. He paid well even back when we used to caravaneer together. I took care of security, he took care of trading. He always managed to strike a winning deal for all parties, or so it seemed at first glance. We got pretty rich and Uncle made many friends. Well, perhaps not friends. More like people who owe him something, or have a beneficial agreement with him.}
{950}{}{这就是我以前为他工作的原因。我们以前一起当大篷车时，他甚至还付了很多钱。我负责保安，他负责交易。他总是设法为各方达成一个双赢的协议，乍一看似乎是这样。我们很富有，叔叔交了很多朋友。嗯，也许不是朋友。更像是欠他一些东西，或者和他有一个有益的协议的人。}
#{951}{}{Why has he chosen Corath?}
{951}{}{他为什么选择科拉斯？}
#{1000}{}{He just didn't feel like traveling with caravans any more; the fucker got lazy. He wanted to settle down and he saw Corath as a city where he could get richer while sitting on his fat ass. I wasn't thrilled but by then I was used to working for him. Since he was generous with money, I had no problem helping him fight for power in this fucking hole.}
{1000}{}{他只是不想再和大篷车一起旅行了，他妈的变懒了。他想安顿下来，他把科拉斯看作一个坐在肥屁股上就能变得更富有的城市。我并不激动，但那时我已经习惯了为他工作。既然他对钱很慷慨，我就可以帮他在这个该死的洞里争取权力。}
#{1001}{}{Don't you like Corath?}
{1001}{}{你不喜欢科拉斯吗？}
#{1002}{}{I'm sure he didn't just come along and start making money on Corath.}
{1002}{}{我肯定他不是来找科拉斯赚钱的。}
#{1003}{}{I need to know something else about Uncle.}
{1003}{}{我需要知道一些关于叔叔的其他事情。}
#{1004}{}{Thanks for your help. I'll be going now.}
{1004}{}{谢谢你的帮助。我要走了。}
#{1050}{}{This place stinks. [He takes a hefty swig from his glass.] It stinks from the sweat of a whole lot of losers who can't do anything better with their lives but complain. It's as if they congregate here from all over the place, just to let Nestor or Uncle grind them down to dirt. And it serves them right. Dealing with people who shit their pants the first time you even talk to them isn't worth shit. I'd rather shoot me some fucking raiders any day. At least they try fighting for their lives, after a fashion.}
{1050}{}{这地方真臭。[他从杯子里大口大口地喝了一口]这是很多失败者的汗水散发出来的臭味，他们的生活再好不过了，只能抱怨。就好像他们从四面八方聚集在这里，只是为了让内斯特或叔叔把他们碾成泥。它为他们服务。和那些你第一次和他们说话就把裤子拉屎的人打交道是不值得的。我哪天都宁愿向我开枪。至少他们试着为自己的生命而战，在一种时尚之后。}
#{1051}{}{How did Uncle start making money around here? It couldn't have come all on its own.}
{1051}{}{叔叔是怎么开始在这里赚钱的？它不可能一个人来的。}
#{1052}{}{I need to know something else about Uncle.}
{1052}{}{我需要知道一些关于叔叔的其他事情。}
#{1053}{}{Thanks for your help. I'll be going now.}
{1053}{}{谢谢你的帮助。我要走了。}
#{1100}{}{You watch your mouth. [He says this calmly without looking at you. Still, you feel a decisive threat in his voice.] Cedrick happened. The sonofawhore that I hired myself after we settled down in Corath. He was capable, so I gave him more and more responsibilities, and I paid him accordingly. But he wanted more. He wanted my job.}
{1100}{}{小心你的嘴。[他平静地说这话，没看你一眼。不过，你还是感觉到他的声音中有一种决定性的威胁。我在科拉斯安顿下来后雇的那个婊子。他很能干，所以我给了他越来越多的责任，我也相应地给了他报酬。但他想要更多。他想要我的工作。}
#{1101}{}{How did he get it?}
{1101}{}{他怎么得到的？}
#{1150}{}{Certainly not by taking me on in person. He would never have dared, that cowardly fucker. He had my house set on fire. I just woke up one night to find out I couldn't breathe. The entire house was in flames, doors barricaded so I couldn't get out. I ran through the blaze, punched through a burning wall to get out. Next thing I remember is waking up at Linsday's. You can probably still see the burned ruins on Uncle Street, over where the latrines are. Fitting, seeing as how everything turned out for shit. Serves me right for letting such a sucker get a hand over me.}
{1150}{}{当然不是亲自带我去的。他根本不敢，那个胆小鬼。他放火烧了我的房子。一天晚上我醒来发现我无法呼吸。整个房子都着火了，门都被挡住了，所以我不能出去。我冲破大火，冲破燃烧的墙壁逃出去。我记得的下一件事是在林斯戴家醒来。你可能仍然可以看到叔叔街上被烧毁的废墟，在厕所所在的地方。合适，看看一切都变成了狗屎。让这样一个蠢货控制了我，这对我很有好处。}
#{1151}{}{And so he got your job?}
{1151}{}{所以他得到了你的工作？}
#{1200}{}{Yeah. Linsday was patching me up for several weeks, Uncle needed someone else to push his business through. Once I was kickin' again he refused to take me back, he just offered me some miserable watchman post. I didn't want any favors from Uncle, I could have done my old job just the same. But this way I would be working under Cedrick. Uncle didn't even let me to repay Cedrick in kind. He'll pay for that one day. They'll both pay.}
{1200}{}{是 啊。林斯戴给我打了好几个星期的电话，叔叔需要别人帮他把生意做下去。有一次我又被踢了，他拒绝带我回去，他只是给了我一个可怜的看守所。我不想得到叔叔的任何帮助，我可以照样做我以前的工作。但这样我就可以在塞德里克手下工作了。舅舅甚至不让我回报塞德里克。总有一天他会为此付出代价的。他们都会付钱的。}
#{1201}{}{You want to take revenge on Cedrick and Uncle? How come you're just sitting here, then?}
{1201}{}{你想报复塞德里克和叔叔？那你怎么就坐在这里？}
#{1202}{}{How do you know it was Cedrick who set your house on fire?}
{1202}{}{你怎么知道是塞德里克放火烧了你的房子？}
#{1203}{}{I need to know something else about Uncle.}
{1203}{}{我需要知道一些关于叔叔的其他事情。}
#{1204}{}{Anyway. I think I'll go now.}
{1204}{}{不管怎样。我想我现在要走了。}
#{1250}{}{I just know, OK? There are enough people around who would shit themselves silly with happiness if I croaked. But not a single one of those losers has the guts to try anything like that, and I don't intend to make it easy for them. Even if it were Nestor's people - if Nestor accumulated enough chutzpah to send them at me - someone would overhear, and later... I would. Such fuckers would be boasting all the way. It was Cedrick. I knew even then he was out to get me. Uncle should have believed my word when I told him, he shouldn't have dismissed it as a load of hooey. My word is always good as gold, and he of all people should've known that.}
{1250}{}{我就知道，好吗？如果我呱呱叫的话，周围有足够多的人会用快乐把自己拉得傻乎乎的。但这些失败者中没有一个有胆量去尝试这样的事情，我也不打算让他们这么容易。即使是内斯特的人-如果内斯特积累了足够的厚脸皮，让他们在我-有人会偷听到，后来。。。我会的。这样的混蛋会自吹自擂的。是塞德里克。我当时就知道他是来抓我的。当我告诉叔叔时，他应该相信我的话，他不应该把它当作一堆胡说八道。我的话总是金玉良言，他应该知道这一点。}
#{1251}{}{You want to take revenge on Cedrick and Uncle? How come you're just sitting here, then?}
{1251}{}{你想报复塞德里克和叔叔？那你怎么就坐在这里？}
#{1252}{}{Why don't you join Nestor to take your revenge? He wants to eliminate Uncle too.}
{1252}{}{你为什么不加入内斯特来报仇？他也想除掉叔叔。}
#{1253}{}{So you want to take revenge, but so far you've only sat in a bar?}
{1253}{}{所以你想报仇，但到目前为止你只在酒吧里坐过？}
#{1254}{}{I know how you could take your revenge. Nestor wants me to challenge Uncle, and I'm sure it'll be Cedrick in the ring in Uncle's place.}
{1254}{}{我知道你怎么报仇。内斯特想让我挑战伯父，我肯定是塞德里克代替伯父在拳击场上。}
#{1255}{}{I know how you could take your revenge. Nestor wants me to challenge Uncle, and I'm sure it'll be Cedrick in the ring in Uncle's place.}
{1255}{}{我知道你怎么报仇。内斯特想让我挑战伯父，我肯定是塞德里克代替伯父在拳击场上。}
#{1256}{}{I need to know something else about Uncle.}
{1256}{}{我需要知道一些关于叔叔的其他事情。}
#{1257}{}{Anyway. I think I'll go now.}
{1257}{}{不管怎样。我想我现在要走了。}
#{1300}{}{I'll take my revenge, you can bet I will, even if it takes forever and even if it kills me. I want to make sure they both die. So far, the only thing I can do is wait for the proper moment. I didn't keep it secret when Uncle fucked me, what I wanted to do. All his people are on the lookout for me now, there's no way I can get through them alive. I'm no idiot, I want to take revenge, not commit suicide.}
{1300}{}{我会报仇的，你可以打赌，我会报仇的，即使这需要永远，即使它杀了我。我想确保他们都死了。到目前为止，我唯一能做的就是等待合适的时机。叔叔上我的时候我没有保密，我想做什么。他所有的人都在看着我，我不可能活过他们。我不是白痴，我想报仇，不是自杀。}
#{1301}{}{How do you know it was Cedrick who set your house on fire?}
{1301}{}{你怎么知道是塞德里克放火烧了你的房子？}
#{1302}{}{Why don't you join Nestor to take your revenge? He wants to eliminate Uncle too.}
{1302}{}{你为什么不加入内斯特来报仇？他也想除掉叔叔。}
#{1303}{}{So you sit around at the bar?}
{1303}{}{所以你坐在酒吧里？}
#{1304}{}{I know how you could take your revenge. Nestor wants me to challenge Uncle, and I'm sure it'll be Cedrick in the ring in Uncle's place.}
{1304}{}{我知道你怎么报仇。内斯特想让我挑战伯父，我肯定是塞德里克代替伯父在拳击场上。}
#{1305}{}{I know how you could take your revenge. Nestor wants me to challenge Uncle, and I'm sure it'll be Cedrick in the ring in Uncle's place.}
{1305}{}{我知道你怎么报仇。内斯特想让我挑战伯父，我肯定是塞德里克代替伯父在拳击场上。}
#{1306}{}{I need to know something else about Uncle.}
{1306}{}{我需要知道一些关于叔叔的其他事情。}
#{1307}{}{Anyway. I think I'll go now.}
{1307}{}{不管怎样。我想我现在要走了。}
#{1350}{}{That little mutantfucker? He can be trusted even less so than Uncle, he will happily sacrifice anyone just to keep his mutant. He just hides behind people instead of taking care of Uncle. Besides, I made enough trouble for Nestor while working for Uncle. I'm not stupid enough to put myself at Nestor's mercy.}
{1350}{}{那个小变态？他比叔叔更不可信，他愿意牺牲任何人来留住他的变种人。他只是躲在人后面，而不是照顾叔叔。另外，我在为叔叔工作的时候给内斯特惹了不少麻烦。我还没蠢到任由内斯特摆布自己。}
#{1351}{}{So you sit around at the bar?}
{1351}{}{所以你坐在酒吧里？}
#{1352}{}{I know how you could take your revenge. Nestor wants me to challenge Uncle, and I'm sure it'll be Cedrick in the ring in Uncle's place.}
{1352}{}{我知道你怎么报仇。内斯特想让我挑战伯父，我肯定是塞德里克代替伯父在拳击场上。}
#{1353}{}{I know how you could take your revenge. Nestor wants me to challenge Uncle, and I'm sure it'll be Cedrick in the ring in Uncle's place.}
{1353}{}{我知道你怎么报仇。内斯特想让我挑战伯父，我肯定是塞德里克代替伯父在拳击场上。}
#{1354}{}{I need to know more about Uncle.}
{1354}{}{我需要更多地了解叔叔。}
#{1355}{}{Anyway. I think I'll go now.}
{1355}{}{不管怎样。我想我现在要走了。}
#{1400}{}{When I'm out of caps, I join a caravan that travels to Sedit and back here again. Crimson's is the best, they pay a lot due to the high risk their caravans undertake. Nothing I haven't done a hundred times before.}
{1400}{}{当我没有瓶盖的时候，我加入了一个大篷车，去塞迪特再回来。深红的是最好的，他们付出了很大的风险，由于他们的商队承担。我以前没做过一百次。}
#{1401}{}{Why don't you join Nestor to take your revenge? He wants to eliminate Uncle too.}
{1401}{}{你为什么不加入内斯特来报仇？他也想除掉叔叔。}
#{1402}{}{I know how you could take your revenge. Nestor wants me to challenge Uncle, and I'm sure it'll be Cedrick in the ring in Uncle's place.}
{1402}{}{我知道你怎么报仇。内斯特想让我挑战伯父，我肯定是塞德里克代替伯父在拳击场上。}
#{1403}{}{I know how you could take your revenge. Nestor wants me to challenge Uncle, and I'm sure it'll be Cedrick in the ring in Uncle's place.}
{1403}{}{我知道你怎么报仇。内斯特想让我挑战伯父，我肯定是塞德里克代替伯父在拳击场上。}
#{1404}{}{I need to know something else about Uncle.}
{1404}{}{我需要知道一些关于叔叔的其他事情。}
#{1405}{}{Anyway. I think I'll go now.}
{1405}{}{不管怎样。我想我现在要走了。}
#{1450}{}{This damn city lives off the local mine. Uncle just grabbed a share of the iron ore trade. I'm telling you that's what that bastard is best at. He's got agreements with Nici from way back. I mean Nicol, from Sedit Caravans. She helped him with the other companies. Now, none of them wants to trade with Nestor while Uncle is around. So Nestor has no choice but to sell his ore to Uncle, because otherwise I guess he might as well just stick it up his ass and starve to death.}
{1450}{}{这个该死的城市离当地的矿不远。叔叔刚从铁矿石贸易中分了一杯羹。我告诉你那混蛋最擅长这个。他和尼奇早就有协议了。我是说尼科尔，来自塞迪特商队。她帮助他在其他公司工作。现在，他们都不想在叔叔在的时候和内斯特交易。所以内斯特别无选择，只好把他的矿石卖给叔叔，否则我想他还不如把它竖起来饿死。}
#{1451}{}{You don't like Corath, do you?}
{1451}{}{你不喜欢科拉斯，是吗？}
#{1452}{}{I need to know something else about Uncle.}
{1452}{}{我需要知道一些关于叔叔的其他事情。}
#{1453}{}{Thanks for your help. I'll be going now.}
{1453}{}{谢谢你的帮助。我要走了。}
#{1500}{}{That's your fight. We all have to die someday, so why not at the hands of a supermutant. Except you'll die for that fatass. Tough... [He takes a drink, as if he were drinking to your corpse already.]}
{1500}{}{那是你的战斗。我们总有一天会死的，为什么不交给一个超级变种人呢。除非你会为那个混蛋而死。很难。。。[他喝了一杯，好像他已经在给你的尸体喝酒了。]}
#{1501}{}{Doesn't that mutant piss you off, don't you just hate him? I'm sure you wouldn't grieve if he died. When you worked for Uncle, I'm sure you contemplated ways to get Blaster if it ever came to a fight in the ring.}
{1501}{}{那个变种人让你生气了，你不是恨他吗？如果他死了你肯定不会伤心的。当你为叔叔工作的时候，我肯定你考虑过如果拳击场上有人打架的话，你会得到Blaster的。}
#{1550}{}{OK, dammit. You want to take on a supermutant? No problem, but you don't stand a chance. Blaster is kept on drugs all the time, just so they can control him. A former local quack does the sedating. Nestor hired him just to do that. I guess it can't be too much of a problem to get a few more anti-stimulants into that muscle-berg before the fight, and no one's the wiser. But don't think your chances are high. Even a dampened supermutant is still a killing machine. I can't give you any more advice.}
{1550}{}{好吧，该死。你想和超级变形金刚较量？没问题，但你没有机会。布雷斯特一直吸毒，只是为了控制他。一个以前的本地庸医做镇静剂。内斯特雇他就是为了这么做。我想在比赛前多给那块肌肉注射一些抗兴奋剂不会有太大的问题，没人会更聪明。但不要认为你的机会很大。即使是一个受潮的超级变种仍然是一个杀人机器。我不能再给你什么建议了。}
#{1551}{}{Thanks for your help.}
{1551}{}{谢谢你的帮助。}
#{1600}{}{And you want me to fight for you? It's just so that an opportunity comes along, is it? If I had a chance of a fair fight with Cedrick he wouldn't stand a chance. I would gladly beat him to a bloody pulp. But I'm not so dumb as to be drawn into one of Uncle's traps.}
{1600}{}{你想让我为你而战？只是因为机会来了，是吗？如果我有机会和塞德里克公平竞争，他就没有机会了。我很乐意把他打得血肉模糊。但我不会笨到被叔叔的陷阱所吸引。}
#{1601}{}{Uncle and Cedrick clearly don't give a shit about you any more. Why would they try to lure you into a trap now? You spend all your time at the bar, anyway. Do you really want to waste a chance like this? There won't be a better one.}
{1601}{}{叔叔和塞德里克显然不再在乎你了。为什么他们现在要把你诱入陷阱？不管怎样，你都是在酒吧里度过的。你真的想浪费这样的机会吗？不会有更好的了。}
#{1602}{}{As you think is best. Don't believe me. Your loss.}
{1602}{}{你认为最好的。别相信我。你的损失。}
#{1620}{}{Even if it were true and I do waste that fucker Cedrick, what about Uncle? I want to be sure I take him out too. He always slithers away from any danger. That's just how that fatass works. I doubt he respects the fights in the ring, anyway.}
{1620}{}{即使这是真的，我浪费了那个混蛋塞德里克，那叔叔呢？我想确定我也带他出去。他总是躲开任何危险。那混蛋就是这么干的。我怀疑他是否尊重拳击场上的比赛。}
#{1621}{}{Nestor is really going all the way this time. Uncle looses this fight, and he's finished. There is nowhere to go anymore. So, are you in, then? Or do you intend to sit here and wait for Uncle and Cedrick to serve themselves to you on a silver platter? If so, you might as well fall in line with the other locals.}
{1621}{}{内斯特这次真的是大有作为。叔叔打输了，他就完了。已经无处可去了。那么，你在吗？或者你打算坐在这里等着叔叔和塞德里克用银盘招待你？如果是这样的话，你不妨和其他当地人保持一致。}
#{1622}{}{As you wish. Rot away all you like.}
{1622}{}{如你所愿。你想怎么烂就怎么烂。}
#{1650}{}{You dare compare me to the local trash?! [Vodka jumps up and seizes you by the throat. From up close he gazes in your eyes. It is discomforting to see his burnt face in such minute detail.] What you say about the fight better be the goddamn truth. For your own interests. If so, I will fight. Challenge Uncle and tell Lawteller I will represent you. [He lets you go, you take some time to catch your breath.] Go.}
{1650}{}{你敢把我和当地的垃圾相比？！[伏特加跳起来抓住你的喉咙。他近距离凝视着你的眼睛。看到他那张烧焦的脸上如此细微的细节，真是令人不安。]你说的那场战斗最好是他妈的真话。为了你自己的利益。如果是这样，我会战斗。挑战叔叔，告诉律师我代表你。[他让你走，你花点时间喘口气]走。}
#{1651}{}{You dare compare me to the local trash?! [Vodka jumps up and seizes you by the throat. From up close he gazes in your eyes. It is discomforting to see his burnt face in such minute detail.] What you say about the fight better be the goddamn truth. For your own interests. If so, I will fight. Challenge Uncle and tell Lawteller I will represent you. [He lets you go, you take some time to catch your breath.] Go.}
{1651}{}{你敢把我和当地的垃圾相比？！[伏特加跳起来抓住你的喉咙。他近距离凝视着你的眼睛。看到他那张烧焦的脸上如此细微的细节，真是令人不安。]你说的那场战斗最好是他妈的真话。为了你自己的利益。如果是这样，我会战斗。挑战叔叔，告诉律师我代表你。[他让你走，你花点时间喘口气]走。}
#{1652}{}{OK, we're agreed.}
{1652}{}{好的，我们同意了。}
#{1700}{}{Not interested. I can pay for my own drinks. I'm not interested in no fucking alms, I'm no loser. Get lost.}
{1700}{}{不感兴趣。我可以自己付酒钱。我对他妈的施舍不感兴趣，我不是失败者。滚开。}
#{1701}{}{I want to learn more about this city.}
{1701}{}{我想更多地了解这个城市。}
#{1702}{}{I want to learn more about you.}
{1702}{}{我想更多地了解你。}
#{1703}{}{Are you Vodka? They say you used to work for Uncle. Maybe you could tell me something about him. Or maybe about Nestor?}
{1703}{}{你是伏特加吗？他们说你以前为叔叔工作。也许你可以告诉我一些关于他的事。或者关于内斯特？}
#{1704}{}{OK. Forget it.}
{1704}{}{好 啊。算了吧。}
#{1750}{}{[He drinks his drink, smokes his smoke. He's lost in thought and completely ignores you.]}
{1750}{}{[他喝他的饮料，抽他的烟。他陷入沉思，完全无视你。]}
#{1751}{}{I want to learn more about this city.}
{1751}{}{我想更多地了解这个城市。}
#{1752}{}{I want to learn more about you.}
{1752}{}{我想更多地了解你。}
#{1753}{}{Look, let me buy you a drink and let's talk.}
{1753}{}{听着，我请你喝一杯，我们谈谈。}
#{1754}{}{Are you Vodka? They say you used to work for Uncle. Maybe you could tell me something about him. Or maybe about Nestor?}
{1754}{}{你是伏特加吗？他们说你以前为叔叔工作。也许你可以告诉我一些关于他的事。或者关于内斯特？}
#{1755}{}{I could use some information about Uncle. I took on a job and somehow found myself between Uncle and Nestor.}
{1755}{}{我需要一些关于叔叔的信息。我接受了一份工作，不知怎的我发现自己在叔叔和内斯特之间。}
#{1756}{}{I could use some information about Uncle. I took on a job and somehow found myself between Uncle and Nestor.}
{1756}{}{我需要一些关于叔叔的信息。我接受了一份工作，不知怎的我发现自己在叔叔和内斯特之间。}
#{1757}{}{Could we talk some more? I'd like some information pertaining to my employer.}
{1757}{}{我们能再谈吗？我想要一些有关我雇主的资料。}
#{1758}{}{[Let him be.]}
{1758}{}{[让他去吧。]}
#{1800}{}{Your own stupidity put you between Uncle and Nestor. And now you want information? I don't intend to save you from your own idiocy. [He takes a drink, hoping you will leave.] All right, ask away. I don't have anything better to do, anyway.}
{1800}{}{你自己的愚蠢把你置于叔叔和内斯特之间。现在你想要信息？我不想把你从自己的白痴中拯救出来。[他喝了一杯，希望你离开]好吧，去问吧。不管怎样，我没有更好的事要做。}
#{1801}{}{Your own stupidity put you between Uncle and Nestor. And now you want information? I don't intend to save you from your own idiocy. [He takes a drink, hoping you will leave.] All right, ask away. I don't have anything better to do, anyway.}
{1801}{}{你自己的愚蠢把你置于叔叔和内斯特之间。现在你想要信息？我不想把你从自己的白痴中拯救出来。[他喝了一杯，希望你离开]好吧，去问吧。不管怎样，我没有更好的事要做。}
#{1802}{}{So could you tell me something about Nestor?}
{1802}{}{你能告诉我关于内斯特的事吗？}
#{1803}{}{What can you tell me about Uncle? I bet he pays well.}
{1803}{}{关于叔叔你能告诉我什么？我打赌他薪水很高。}
#{1805}{}{So anyway, what happened? Why don't you work for Uncle any more? Didn't have the balls for it any longer?}
{1805}{}{不管怎样，发生了什么？你为什么不再为叔叔工作了？再也没有勇气了？}
#{1806}{}{If you want to take revenge against Cedrick and Uncle, what are you doing here?}
{1806}{}{如果你想报复塞德里克和叔叔，你在这里干什么？}
#{1807}{}{How do you know it was Cedrick who set your house on fire?}
{1807}{}{你怎么知道是塞德里克放火烧了你的房子？}
#{1808}{}{Working for Uncle is really causing trouble for me. He wants to challenge Nestor, so I'm supposed to fight Blaster in the ring.}
{1808}{}{为叔叔工作真是给我添麻烦。他想挑战内斯特，所以我应该在拳击场上和爆能者对抗。}
#{1809}{}{I know how you could take your revenge. Nestor wants me to challenge Uncle, and I'm sure it'll be Cedrick in the ring in Uncle's place.}
{1809}{}{我知道你怎么报仇。内斯特想让我挑战伯父，我肯定是塞德里克代替伯父在拳击场上。}
#{1810}{}{I know how you could take your revenge. Nestor wants me to challenge Uncle, and I'm sure it'll be Cedrick in the ring in Uncle's place.}
{1810}{}{我知道你怎么报仇。内斯特想让我挑战伯父，我肯定是塞德里克代替伯父在拳击场上。}
#{1811}{}{Forget it. You wouldn't tell me anything useful anyway.}
{1811}{}{算了吧。反正你也不会告诉我什么有用的。}
#{1850}{}{[Vodka nods in acknowledgment of you. Save for a few bruises, the leftovers from his fight with Cedrick, he looks the same. Shot glass in hand and all.]}
{1850}{}{[伏特加点头致谢。除了一些瘀伤，还有他和塞德里克打架时留下的残羹剩饭，他看起来还是一样。手里拿着玻璃丸}
#{1851}{}{So, you've had your revenge. Was it worth it?}
{1851}{}{所以，你已经报仇了。值得吗？}
#{1900}{}{It was. I needed to do that. To personally bash Cedrick's head in and finish Uncle in doing so. While he was waiting to die barricaded in his house, he knew it happened because of me. He shouldn't have pissed me off. I didn't even need to be there. Uncle proved to be a damn coward. It's good we're rid of him.}
{1900}{}{是的。我需要这么做。亲自砸了塞德里克的头，干掉了叔叔。当他被关在家里等死的时候，他知道这是因为我。他不该惹我生气。我甚至不需要去那里。叔叔是个胆小鬼。很好我们摆脱了他。}
#{1901}{}{What will you do now?}
{1901}{}{你现在要做什么？}
#{1950}{}{I don't know, but the main thing is I can finally get out of this stinking hole. I'll join the first caravan to come in and then, we'll see. A man can always make a good living, if he's not a coward.}
{1950}{}{我不知道，但最重要的是我终于可以走出这个臭洞了。我会加入第一个进来的商队，然后，我们拭目以待。如果一个人不是懦夫，他总能过上好日子。}
#{1951}{}{Well, goodbye, Vodka. Godspeed.}
{1951}{}{好吧，再见，伏特加。祝你好运。}
#{2000}{}{And he'll rot with Cedrick. I wanted to take them on in person, but now the chance will never come. Ah, fuck it, at least I can get out of this hole. There's nothing for me here.}
{2000}{}{他会和塞德里克一起腐烂。我本想亲自和他们较量，但现在机会永远不会来了。啊，去他妈的，至少我能走出这个洞。这里没有适合我的东西。}
#{2001}{}{Well, goodbye, Vodka.}
{2001}{}{好吧，再见，伏特加。}
#{2050}{}{Damn surprise. That fucker is always lucky, always slips away from trouble. But one day it won't work and I'll be there. Without Nestor he might get careless, so I'd have a better chance of taking him out.}
{2050}{}{他妈的惊喜。那个混蛋总是很幸运，总是从麻烦中溜走。但总有一天我会在那里的。没有内斯特，他可能会粗心，所以我有更好的机会带他出去。}
#{2051}{}{Well, good luck, you'll need it.}
{2051}{}{好吧，祝你好运，你会需要它的。}
#{2100}{}{[There is a freshly opened bottle next to Vodka's glass. He himself remains unchanged.]}
{2100}{}{[伏特加酒杯旁边有一个新开的瓶子。他本人保持不变。]}
#{2101}{}{What do you say about Uncle being dead?}
{2101}{}{你说叔叔死了怎么办？}
#{2102}{}{What do you say about Uncle taking over Corath?}
{2102}{}{你觉得叔叔接管科拉斯怎么样？}
#{2103}{}{[Let him be.]}
{2103}{}{[让他去吧。]}
