#{100}{}{You see a man.}
{100}{}{你看到一个男人。}
#{150}{}{You see a thief.}
{150}{}{你看见一个小偷。}
#{200}{}{You see a man quietly creeping through the darkness.}
{200}{}{你看见一个人悄悄地在黑暗中爬行。}
#{250}{}{You see a grave robber.}
{250}{}{你看见一个盗墓贼。}
#{500}{}{Damn, man, you scared me to death!}
{500}{}{该死的，你把我吓死了！}
#{501}{}{What are you doing here?}
{501}{}{你在这里干什么？}
#{502}{}{Bad evil! Boom boom!}
{502}{}{邪恶！砰砰！}
#{550}{}{Whaddya mean what I'm doing here? What are YOU doing here?!}
{550}{}{你说我在这里干什么？你在这里干什么？！}
#{551}{}{The gravedigger asked me to guard this place. Apparently, there's a grave robber.}
{551}{}{掘墓人让我看守这个地方。显然，有个盗墓贼。}
#{600}{}{I see... I just went for a stroll, and I must have lost my way. If, as you say, this is a graveyard.}
{600}{}{我懂了。。。我刚出去散步，一定是迷路了。如果像你说的，这是个墓地。}
#{601}{}{Do you think I'm completely stupid?! That grave robber is you!}
{601}{}{你觉得我很蠢吗？！那个盗墓贼就是你！}
#{602}{}{Well, make sure you're more careful in the future. I could have shot you.}
{602}{}{好吧，以后一定要小心点。我本可以杀了你的。}
#{650}{}{Thanks, I will. Good luck catching that thief.}
{650}{}{谢谢，我会的。祝你抓住那个小偷好运。}
#{651}{}{Thanks.}
{651}{}{谢谢。}
#{700}{}{OK, OK, you got me, it's me. You wanna cut, is that it?}
{700}{}{好吧，好吧，你抓住我了，是我。你想剪，是吗？}
#{701}{}{A cut, you say? I'm listening...}
{701}{}{你说是伤口？我在听。。。}
#{702}{}{No, I want you to stop. I want you to get out of here and never come back.}
{702}{}{不，我要你停下来。我要你离开这里，永远不要回来。}
#{703}{}{No. To be honest, I'd rather just kill you to stop you.}
{703}{}{不。说实话，我宁愿杀了你来阻止你。}
#{750}{}{My plan was to rob this place over several nights. But this changes the game. Look, the old geezer is relying on you guarding the place, so he's dead asleep, more so than usual. With the both of us digging, we could have this place cleaned out by sunrise. Then we can split the profits 50-50. Whaddya say?}
{750}{}{我的计划是抢劫这个地方好几个晚上。但这改变了游戏。听着，那个老家伙是靠你来守卫这个地方的，所以他睡着了，比平常更厉害。我们两个都在挖，我们可以在日出前把这个地方打扫干净。然后我们可以平分利润。你说什么？}
#{751}{}{I want a bigger cut.}
{751}{}{我想要一个更大的伤口。}
#{752}{}{Damn, that's not a bad idea. Let's get to it, if we're going to be done by sunrise.}
{752}{}{妈的，这主意不错。让我们开始吧，如果我们要在日出前完成的话。}
#{753}{}{You want me to work? Fuck that, I'd rather kill you.}
{753}{}{你想让我工作？操，我宁愿杀了你。}
#{800}{}{I'm the expert here. This is my beat and it's my plan, so if anyone's asking for more it should be me. Half and half or nothing.}
{800}{}{我是这里的专家。这是我的节拍，也是我的计划，所以如果有人要求更多，应该是我。半途而废或者什么都没有。}
#{801}{}{You're right. Let's get to it, we must get it done before the sun comes up.}
{801}{}{你说得对。让我们开始吧，我们必须在太阳升起之前完成。}
#{802}{}{In that case I'll rather shoot you.}
{802}{}{那样的话，我宁愿杀了你。}
#{850}{}{Not bad, not bad at all! We're lucky that some miners are so greedy that they'd rather get buried with their property than leave it to the wife and kids. Here's half of the entire loot, as agreed.}
{850}{}{不错，一点也不错！我们很幸运，一些矿工非常贪婪，他们宁愿把自己的财产埋在地下，也不愿把它留给妻子和孩子。按约定，这是全部战利品的一半。}
#{851}{}{Thanks for the good cooperation. And now get lost, the sun is starting to rise.}
{851}{}{谢谢你的合作。现在迷失方向，太阳开始升起。}
#{852}{}{I want more!}
{852}{}{我想要更多！}
#{853}{}{You know what? I'll take the lot. You won't mind, not when you're dead.}
{853}{}{你知道吗？我要一大笔钱。你不会介意的，你死的时候不会。}
#{900}{}{I'm going. It's celebration time! See you.}
{900}{}{我要走了。庆祝时间到了！再见。}
#{901}{}{See you.}
{901}{}{再见。}
#{950}{}{Like hell you do! We agreed on 50-50 and I don't intend to change that now!}
{950}{}{真他妈的！我们达成了50比50的协议，我现在不打算改变这一点！}
#{951}{}{OK, you're right, sorry. Now get lost, it's going to be light soon.}
{951}{}{好吧，你说得对，对不起。快滚，天快亮了。}
#{952}{}{In that case, I'll take the lot. You won't mind, not when you're dead.}
{952}{}{如果那样的话，我就要了。你不会介意的，你死的时候不会。}
#{1000}{}{Yeah? And who's gonna stop me from coming back? I doubt you'll be guarding this place forever.}
{1000}{}{是 啊？谁来阻止我回来？我怀疑你会永远守护这个地方。}
#{1001}{}{Why do you even do this? Don't you have any respect for the dead?}
{1001}{}{你为什么这么做？你不尊重死者吗？}
#{1002}{}{I won't, but I'll stop by from time to time. If I learn that one more grave's been robbed, I'll find you and turn your life into a living hell! You can believe me: I know how to do it, and I will.}
{1002}{}{我不会的，但我会不时过来看看。如果我知道又有一个坟墓被抢了，我会找到你，把你的生活变成活生生的地狱！你可以相信我：我知道怎么做，我会的。}
#{1003}{}{Well, you'll be dead for one thing.}
{1003}{}{好吧，有一件事你会死的。}
#{1050}{}{Oh shit-fuck, you're totally crazy. I'll... Alright, I'll go quietly and I'll stay gone.}
{1050}{}{妈的，你疯了。我会。。。好吧，我会安静地走，我会一直走。}
#{1051}{}{Disappear.}
{1051}{}{消失。}
#{1100}{}{No, I don't think you'd make such an effort for this retarded-ass town and its graveyard.}
{1100}{}{不，我不认为你会为这个弱智的小镇和它的墓地付出这么大的努力。}
#{1101}{}{Yeah, you're right. I guess I'll just have to kill you.}
{1101}{}{是的，你说得对。我想我得杀了你。}
#{1150}{}{Shit, you're still around?!}
{1150}{}{妈的，你还在吗？！}
#{1151}{}{Lost your way again? A curious coincidence, isn't it? You're that thief!}
{1151}{}{又迷路了？一个奇怪的巧合，不是吗？你就是那个小偷！}
#{1200}{}{Damn, woman, you scared me to death!}
{1200}{}{妈的，女人，你把我吓死了！}
#{1201}{}{What are you doing here?}
{1201}{}{你在这里干什么？}
#{1202}{}{Bad evil! Boom boom!}
{1202}{}{邪恶！砰砰！}
#{1250}{}{Whaddya mean what I'm doing here? What are YOU doing here?!}
{1250}{}{你说我在这里干什么？你在这里干什么？！}
#{1251}{}{The gravedigger asked me to guard this place. Apparently, there's a grave robber.}
{1251}{}{掘墓人让我看守这个地方。显然，有个盗墓贼。}
#{1300}{}{I see... I just went for a stroll, and I must have lost my way. If, as you say, this is a graveyard.}
{1300}{}{我懂了。。。我刚出去散步，一定是迷路了。如果像你说的，这是个墓地。}
#{1301}{}{Do you think I'm completely stupid?! That grave robber is you!}
{1301}{}{你觉得我很蠢吗？！那个盗墓贼就是你！}
#{1302}{}{Well, make sure you're more careful in the future. I could have shot you.}
{1302}{}{好吧，以后一定要小心点。我本可以杀了你的。}
#{1350}{}{OK, OK, you got me, it's me. You wanna cut, is that it?}
{1350}{}{好吧，好吧，你抓住我了，是我。你想剪，是吗？}
#{1351}{}{A cut, you say? I'm listening...}
{1351}{}{你说是伤口？我在听。。。}
#{1352}{}{No, I want you to stop. I want you to get out of here and never come back.}
{1352}{}{不，我要你停下来。我要你离开这里，永远不要回来。}
#{1353}{}{No. To be honest, I'd rather just kill you to stop you.}
{1353}{}{不。说实话，我宁愿杀了你来阻止你。}
#{1400}{}{Damn, calm down. Why would you do a thing like that?!}
{1400}{}{妈的，冷静点。你为什么要做那样的事？！}
#{1401}{}{Gravy diggy wanna boom boom bad!}
{1401}{}{肉汁迪吉想砰砰坏了！}
#{1450}{}{I'm not bad, I just need to make some money and I don't want to end up like some dead miner in a mass grave. But you'd never understand... Would you like to make some money? The gravedigger can't pay you much. If you help me, you can have much more.}
{1450}{}{我不坏，我只需要挣点钱，我不想像死矿工一样死在乱葬坑里。但你永远不会明白。。。你想赚点钱吗？掘墓人付不了你多少钱。如果你帮助我，你可以得到更多。}
#{1451}{}{Muchy much reward? }
{1451}{}{多少报酬？}
#{1452}{}{ want much reward!}
{1452}{}{想要很多奖励！}
#{1453}{}{Nooo, diggy reward, bad boom!}
{1453}{}{不，数字奖励，糟糕的繁荣！}
#{1500}{}{Great. My plan was to rob this place over several nights. But if we both dig, we can have this place cleaned out by sunrise. And then we can split the profits.}
{1500}{}{伟大的。我的计划是抢劫这个地方好几个晚上。但如果我们都挖，我们就能在日出前把这个地方清理干净。然后我们可以分享利润。}
#{1501}{}{Wooo!}
{1501}{}{喔！}
#{1502}{}{That bad, I boom!}
{1502}{}{太糟糕了，我砰！}
#{1550}{}{That's not bad, not bad at all! We're lucky that some miners are so greedy that they'd rather get buried with their property than leave it to the wife and kids. Here's your cut.}
{1550}{}{不错，一点也不差！我们很幸运，一些矿工非常贪婪，他们宁愿把自己的财产埋在地下，也不愿把它留给妻子和孩子。这是你的份。}
#{1551}{}{Woo, whoopee!}
{1551}{}{呜呜，呜呜！}
#{1552}{}{Nooo! Want more reward! More! Gimme!}
{1552}{}{不！想要更多的奖励！更多！给我！}
#{1600}{}{Oh sure, whatever that meant. I'm outta here before the sun comes up. Bye, my special friend.}
{1600}{}{哦，当然，不管那意味着什么。太阳还没出来我就走了。再见，我特别的朋友。}
#{1601}{}{Bye.}
{1601}{}{再见。}
#{1650}{}{Look you greedy goof, you should be happy you got anything at all! Now, let me leave before the sun comes up.}
{1650}{}{看你这个贪婪的傻瓜，你应该很高兴你得到了任何东西！现在，让我在太阳升起之前离开。}
#{1651}{}{Ugh, OK.}
{1651}{}{呃，好吧。}
#{1652}{}{Ugh, no. More, all, boom you!}
{1652}{}{啊，不。更多，所有，轰你！}
#{1700}{}{Damn, calm down. Why would you do a thing like that?!}
{1700}{}{妈的，冷静点。你为什么要做那样的事？！}
#{1701}{}{Gravy diggy wanna' boom boom bad!}
{1701}{}{肉汁迪吉想要'砰砰坏！}
#{1750}{}{Look you greedy goof, you should be happy you got anything at all! Now, let me leave before the sun comes up.}
{1750}{}{看你这个贪婪的傻瓜，你应该很高兴你得到了任何东西！现在，让我在太阳升起之前离开。}
#{1751}{}{Ugh, OK.}
{1751}{}{呃，好吧。}
#{1752}{}{Ugh, no. More, all, boom you!}
{1752}{}{啊，不。更多，所有，轰你！}
#{1800}{}{Why? I'm trying to survive! The only thing a normal man can do around here is work down a mine. To toil his ass off for a few measly caps and, after a few months, end up as just another X on a marker in the graveyard. No way, man, I'm not gonna let 'em destroy me like those other guys.}
{1800}{}{为什么？我在努力生存！一个普通人在这里唯一能做的就是在矿井里干活。为了几个微不足道的瓶盖，他拼命工作，几个月后，他就成了墓地里一个标记上的另一个X。不可能，伙计，我不会让他们像其他人一样毁了我。}
#{1801}{}{An X on a marker?}
{1801}{}{记号笔上的X？}
#{1802}{}{Do you think you're somehow better than the miners because you rob their corpses? In my book, you're a bigger loser than they are. And if things are so damn bad here, go elsewhere. Even if you shoveled brahmin shit in Sedit for a living, it would stink less than what you're doing now.}
{1802}{}{你认为你比矿工们强是因为你抢了他们的尸体？在我看来，你比他们更失败。如果这里的情况如此糟糕，那就去别处。即使你在塞迪特铲双头牛大便为生，它的臭味也比你现在做的要少。}
#{1803}{}{It ends now. Get the fuck out and never come back or you'll have to deal with me.}
{1803}{}{现在结束了。滚出去，再也不要回来了，否则你就得对付我。}
#{1804}{}{Boo-hoo for you. Let me put you out of your misery, then.}
{1804}{}{嘘嘘给你。那就让我把你从痛苦中解救出来吧。}
#{1850}{}{Haven't you noticed there are markers here where you'll find nothing but a whole bunch of Xs? Every X like that means one dead miner who ended his miserable life down a mine shaft. If, say, a few men are crushed by a cave-in, they dig out the bodies, and throw them down a single grave. Nobody bothers to identify the mutilated bodies, they just mark the number on the marker.}
{1850}{}{你没注意到这里有标记，除了一堆X你什么也找不到吗？像这样的每一个X都意味着一个死去的矿工在矿井里结束了他的悲惨生活。比方说，如果有几个人被山洞压垮了，他们就把尸体挖出来，扔在一个坟墓里。没有人费心去辨认残缺的尸体，他们只是在记号笔上标记数字。}
#{1851}{}{Haven't you noticed there are markers here where you'll find nothing but a whole bunch of Xs? Every X like that means one dead miner who ended his miserable life down a mine shaft. If, say, a few men are crushed by a cave-in, they dig out the bodies, and throw them down a single grave. Nobody bothers to identify the mutilated bodies, they just mark the number on the marker.}
{1851}{}{你没注意到这里有标记，除了一堆X你什么也找不到吗？像这样的每一个X都意味着一个死去的矿工在矿井里结束了他的悲惨生活。比方说，如果有几个人被山洞压垮了，他们就把尸体挖出来，扔在一个坟墓里。没有人费心去辨认残缺的尸体，他们只是在记号笔上标记数字。}
#{1852}{}{And you think you're somehow better than the miners because you rob their corpses? In my book, you're a bigger loser than they are. And if things are so damn bad here, go elsewhere. Even if you shoveled brahmin shit in Sedit for a living, it would stink less than what you're doing now.}
{1852}{}{你觉得你比矿工们强是因为你抢了他们的尸体？在我看来，你比他们更失败。如果这里的情况如此糟糕，那就去别处。即使你在塞迪特铲双头牛大便为生，它的臭味也比你现在做的要少。}
#{1853}{}{Well, your luck has run out. Get the fuck out and never come back or you'll have to deal with me.}
{1853}{}{好吧，你的运气不好了。滚出去，再也不要回来了，否则你就得对付我。}
#{1854}{}{Enough bullshit. I'll kill you to make sure you don't stir up any more trouble.}
{1854}{}{胡说够了。我要杀了你，以确保你不再惹麻烦。}
#{1900}{}{That's bullshit, you know nothin'! If it makes you so sick that I'm trying to survive here, then leave me alone and vanish!}
{1900}{}{胡说，你什么都不知道！如果它让你如此恶心以至于我试图在这里生存，那就让我一个人呆着消失吧！}
#{1901}{}{If you won't leave, I'll have to kill you.}
{1901}{}{如果你不走，我就杀了你。}
#{1950}{}{That's bullshit, you know nothin'! But you're right about one thing. This damn city ain't worth a lame brahmin's ass. I'll get out of this hole. I can't turn a profit on these dead guys forever anyway.}
{1950}{}{胡说，你什么都不知道！但有一件事你是对的。这该死的城市不值得一个跛脚双头牛的屁股。我要离开这个洞。反正我也不能永远从这些死人身上获利。}
#{1951}{}{Well, then go.}
{1951}{}{好吧，那就走吧。}
#{2000}{}{Hell no. I doubt you'll be guarding this place forever.}
{2000}{}{不，我怀疑你会永远守护这个地方。}
#{2001}{}{Do you think you're somehow better than the miners because you rob their corpses? In my book, you're a bigger loser than they are. And if things are so damn bad here, go elsewhere. Even if you shoveled brahmin shit in Sedit for a living, it would stink less than what you're doing now.}
{2001}{}{你认为你比矿工们强是因为你抢了他们的尸体？在我看来，你比他们更失败。如果这里的情况如此糟糕，那就去别处。即使你在塞迪特铲双头牛大便为生，它的臭味也比你现在做的要少。}
#{2002}{}{No, but I'll stop by from time to time. If I learn that one more grave's been robbed, I'll find you and turn your life into a living hell! And you can believe me: I know how to do it, and I will.}
{2002}{}{不，但我会不时过来看看。如果我知道又有一个坟墓被抢了，我会找到你，把你的生活变成活生生的地狱！你可以相信我：我知道怎么做，我会的。}
#{2003}{}{Then I guess I'll kill you right now.}
{2003}{}{那我现在就杀了你。}
