#{100}{}{You see a mercenary.}
{100}{}{你看到一个雇佣兵。}
#{101}{}{You see a mercenary.}
{101}{}{你看到一个雇佣兵。}
#{200}{}{A man from a group of mercenaries. None of them look exactly friendly.}
{200}{}{一群雇佣兵中的人。他们看起来都不友好。}
#{201}{}{A woman from a group of mercenaries. None of them look exactly friendly.}
{201}{}{一群雇佣兵中的女人。他们看起来都不友好。}
#{250}{}{A man from a group of mercenaries hired by the hospital. They are apparently looking for some suitable donors.}
{250}{}{医院雇佣的雇佣兵中的一个人。他们显然在寻找合适的捐赠者。}
#{251}{}{A woman from a group of mercenaries hired by the hospital. They are apparently looking for some suitable donors.}
{251}{}{医院雇佣的雇佣兵中的一个女人。他们显然在寻找合适的捐赠者。}
#{300}{}{Howdy partner.}
{300}{}{你好，搭档。}
#{301}{}{Haven't seen any good donors have you?}
{301}{}{没见过好的捐赠者吧？}
#{302}{}{Well, well! What a coincidence. How's it going?}
{302}{}{好吧，好吧！真是巧合。怎么样？}
#{303}{}{It's bad. Most people are afraid of Rebirth. They only travel in large armed groups.}
{303}{}{很糟糕。大多数人害怕重生。他们只在大型武装团体中旅行。}
#{304}{}{We can't doddle. We've got a job, you know.}
{304}{}{我们不能躲闪。你知道，我们有工作。}
#{305}{}{No worries, we ain't picking you up.}
{305}{}{别担心，我们不会接你的。}
#{306}{}{We mostly pick up savages.}
{306}{}{我们主要抓野人。}
#{307}{}{Falber needs some fresh meet. Ha, ha.}
{307}{}{法伯需要新的会面。哈，哈。}
#{308}{}{Some savage tribes hide away in caves like rats.}
{308}{}{一些野蛮部落像老鼠一样躲在洞穴里。}
#{309}{}{If you see any good prey, you let us know, would ya? Come on, be a sport.}
{309}{}{如果你看到什么好猎物，请告诉我们，好吗？来吧，做个运动。}
#{310}{}{We shouldn't stand around here. Somebody'll spot us.}
{310}{}{我们不应该站在这附近。有人会发现我们的。}
#{311}{}{It ain't easy to hit them so that they only get stunned. You must know what I mean.}
{311}{}{打他们不容易，他们只会被打晕。你一定知道我的意思。}
#{312}{}{No luck so far today.}
{312}{}{今天运气不好。}
#{313}{}{Apparently the hospital is doing good business. They certainly don't spare any expense on our salaries.}
{313}{}{显然医院生意不错。他们当然不会在我们的工资上花一分钱。}
#{314}{}{Howdy partner.}
{314}{}{你好，搭档。}
#{315}{}{Haven't seen any good donors have you?}
{315}{}{没见过好的捐赠者吧？}
#{400}{}{Attack!}
{400}{}{进攻！}
#{401}{}{Get him!}
{401}{}{抓住他！}
#{402}{}{Take him!}
{402}{}{抓住他！}
#{403}{}{Get him in a corner!}
{403}{}{把他弄到角落里去！}
#{404}{}{We already have a waiting list for your body, heh-heh.}
{404}{}{我们已经有你尸体的等待名单了，嘿嘿。}
#{405}{}{Quick, hurry!}
{405}{}{快点，快点！}
#{406}{}{Don't let 'em get away.}
{406}{}{别让他们跑了。}
#{407}{}{Attack!}
{407}{}{进攻！}
#{408}{}{Get her!}
{408}{}{抓住她！}
#{409}{}{Take her!}
{409}{}{带上她！}
#{410}{}{Get her in a corner!}
{410}{}{把她弄到角落里去！}
#{420}{}{Attack!}
{420}{}{进攻！}
#{421}{}{Get them!}
{421}{}{抓住他们！}
#{422}{}{Take them!}
{422}{}{抓住他们！}
#{423}{}{Get them in a corner!}
{423}{}{把他们带到角落里！}
#{424}{}{We already have a waiting list for your bodies, heh-heh.}
{424}{}{我们已经有了你尸体的等待名单，嘿嘿。}
#{425}{}{Quick, hurry!}
{425}{}{快点，快点！}
#{426}{}{Don't let 'em get away.}
{426}{}{别让他们跑了。}
