#{100}{}{Spammer Nekrotyrael.}
{100}{}{垃圾邮件发送者Nekrotyrael。}
#{111}{}{I am a spammer, appreciate me.}
{111}{}{我是一个垃圾邮件发送者，感谢我。}
#{112}{}{Pretty good... Heeeeeeee.}
{112}{}{不错。。。嘿，嘿。}
#{113}{}{Well, I guess so.}
{113}{}{嗯，我想是的。}
#{114}{}{And that's the way it goes.}
{114}{}{事情就是这样。}
#{115}{}{Oh boy, oh boy, give me back my toy...}
{115}{}{天啊，天啊，把玩具还给我。。。}
#{116}{}{The chosen one for death is heeere.}
{116}{}{被选为死神的是希耶尔。}
#{117}{}{I am not small, that's an optical illusion.}
{117}{}{我不小，那是一种错觉。}
