#{100}{}{You see a wanderer.}
{100}{}{你看到一个流浪者。}
#{101}{}{You see a wanderer.}
{101}{}{你看到一个流浪者。}
#{200}{}{You see a man traveling the wasteland.}
{200}{}{你看见一个人在荒地上旅行。}
#{201}{}{You see a wanderer. You cannot tell whether he has a destination or simply lives in the wasteland.}
{201}{}{你看到一个流浪者。你不知道他是有目的地，还是住在荒地里。}
#{202}{}{You see a man. You never know what you can expect from a stranger who you meet in the wilderness.}
{202}{}{你看到一个男人。你永远不知道你能从一个在荒野中遇见的陌生人那里得到什么。}
#{203}{}{You see a wanderer. By his looks he's been underway for several weeks now.}
{203}{}{你看到一个流浪者。从他的外表看，他已经航行了好几个星期了。}
#{204}{}{You see a woman traveling the wasteland.}
{204}{}{你看到一个女人在荒地上旅行。}
#{205}{}{You see a wanderer. You cannot tell whether she has a destination or simply lives in the wasteland.}
{205}{}{你看到一个流浪者。你分不清她是有目的地还是住在荒地里。}
#{206}{}{You see a woman. You never know what you can expect from a stranger who you meet in the wilderness.}
{206}{}{你看到一个女人。你永远不知道你能从一个在荒野中遇见的陌生人那里得到什么。}
#{207}{}{You see a wanderer. By her looks she's been underway for several weeks now.}
{207}{}{你看到一个流浪者。从她的外表来看，她已经航行了好几个星期了。}
#{300}{}{We don't want no trouble. Let's be on our way both of us. OK?}
{300}{}{我们不想惹麻烦。让我们一起上路吧。好 啊？}
#{301}{}{Howdy. We're just passing. I have a few things for sale if you're interested.}
{301}{}{你好。我们只是路过。如果你感兴趣的话，我有一些东西要卖。}
#{302}{}{Howdy. We're just passing. I have a few things for sale if you're interested.}
{302}{}{你好。我们只是路过。如果你感兴趣的话，我有一些东西要卖。}
#{303}{}{I've been traveling the wilderness for long enough to know there are plenty of nutjobs walking about. I hope you ain't one of them.}
{303}{}{我在荒野中旅行了很长时间，知道到处都是疯子。我希望你不是他们中的一员。}
#{304}{}{I've been traveling the wilderness for long enough to know there are plenty of nutjobs walking about. I hope you ain't one of them.}
{304}{}{我在荒野中旅行了很长时间，知道到处都是疯子。我希望你不是他们中的一员。}
#{305}{}{Hi there! It's nice to finally see a human again.}
{305}{}{你好！很高兴终于又见到人类了。}
#{306}{}{Howdy, traveler. Have you been underway long?}
{306}{}{你好，旅行者。你开了很久了吗？}
#{307}{}{Calm down. Keep your hands where I can see them! Don't try to rob me, I know all the tricks in the book.}
{307}{}{冷静。把手放在我能看见的地方！别想抢我，我知道书中所有的窍门。}
#{308}{}{I don't know what you are. You could be a common raider or just a traveler like me. One must be careful.}
{308}{}{我不知道你是什么。你可以是一个普通的袭击者，也可以只是一个像我一样的旅行者。一个人必须小心。}
#{309}{}{I don't know what you are. You could be a common raider or just a traveler like me. One must be careful.}
{309}{}{我不知道你是什么。你可以是一个普通的袭击者，也可以只是一个像我一样的旅行者。一个人必须小心。}
#{310}{}{Howdy. You know what I like best about the wilderness? There are no witnesses.}
{310}{}{你好。你知道我最喜欢荒野的什么吗？没有目击者。}
#{311}{}{Well, lookie here, easy pray. We need to get a piece of that.}
{311}{}{好吧，听着，祈祷吧。我们得从中分一杯羹。}
#{312}{}{Howdy. We need to replenish our supplies. Your stuff will come in handy.}
{312}{}{你好。我们需要补充补给。你的东西会派上用场的。}
#{313}{}{Traveling, are you? I'm afraid we will need to take all your possessions now.}
{313}{}{旅行，是吗？恐怕我们现在需要拿走你所有的东西。}
#{314}{}{I know your kind! You want to kill and rob us. Well, we figure we better kill you first!}
{314}{}{我认识你这种人！你想杀人抢劫我们。好吧，我们想我们最好先杀了你！}
#{315}{}{You know your caps will help us. Don't worry, you won't need them.}
{315}{}{你知道你的瓶盖会帮我们的。别担心，你不会需要的。}
#{316}{}{I'll take all your money now. Sorry, but I haven't eaten in a long while. If one of us must die, it's better you than me.}
{316}{}{我现在要拿走你所有的钱。对不起，我好久没吃东西了。如果我们中有一个人死了，你总比我强。}
#{317}{}{Hello. You look like you have something valuable on you. And you don't look like you can defend yourself.}
{317}{}{你好。你看起来身上有值钱的东西。你看起来也没法保护自己。}
#{318}{}{Howdy. You know what I like best about the wilderness? There are no witnesses.}
{318}{}{你好。你知道我最喜欢荒野的什么吗？没有目击者。}
#{320}{}{I've seen things in the wilderness... If I told you, you wouldn't believe me.}
{320}{}{我见过荒野里的东西。。。如果我告诉你，你不会相信我的。}
#{321}{}{Damn, I don't even know how long we've been underway anymore. I've lost count.}
{321}{}{妈的，我都不知道我们已经开了多久了。我数不清了。}
#{322}{}{We want to stop in that town... Damn, I forgot its stupid name.}
{322}{}{我们想停在那个镇上。。。该死，我忘了它愚蠢的名字。}
#{323}{}{Hello. Been long on the road?}
{323}{}{你好。在路上很久了？}
#{324}{}{The weather hasn't changed at all these past few days.}
{324}{}{这几天天气一点也没变。}
#{325}{}{We've been on the road for a damn long time.}
{325}{}{我们已经在路上走了很长时间了。}
#{326}{}{I don't know 'bout you, but to me the wilderness is cozier than any old town. There, you never know who's stabbin' your back.}
{326}{}{我不知道你怎么样，但对我来说，荒野比任何一个古老的城镇都要舒适。你永远不知道谁在背后捅你。}
#{327}{}{It's nice to chat from time to time.}
{327}{}{偶尔聊天真好。}
#{328}{}{We saw some raiders a while back. Lucky they didn't see us.}
{328}{}{不久前我们看到一些袭击者。幸好他们没看到我们。}
#{329}{}{Watch out in the rocks. You never know what hole a radscopion might be hiding in.}
{329}{}{小心岩石。你永远都不知道一个radscopion可能藏在什么洞里。}
#{330}{}{Geckos are treacherous bastards. A few years back one of them almost damn bit my leg off.}
{330}{}{壁虎是奸诈的杂种。几年前，他们中的一个差点把我的腿咬下来。}
#{331}{}{Don't you have any proper meat? I'm positively sick of roasting rats.}
{331}{}{你没有正宗的肉吗？我真的厌倦了烤老鼠。}
#{332}{}{You never know who you'll meet out here. I hope you're not up to trouble.}
{332}{}{你永远不知道在这里会遇到谁。我希望你不会惹麻烦。}
#{333}{}{I'm watching you. You must be careful if you want to survive.}
{333}{}{我在看着你。你要想活下去就得小心。}
#{334}{}{I guess we still have some supplies.}
{334}{}{我想我们还有一些补给。}
#{335}{}{We've already met some desperate people. They were hungry and wanted to rob us because that was the only way they were going to help themselves.}
{335}{}{我们已经遇到了一些绝望的人。他们饿了，想抢劫我们，因为那是他们唯一能自救的方法。}
#{336}{}{I prefer traveling to being stuck in one place.}
{336}{}{我宁愿旅行也不愿被困在一个地方。}
#{337}{}{If you want something, say it quick. I don't like this place. And I don't like you.}
{337}{}{如果你想要什么，快说出来。我不喜欢这个地方。我不喜欢你。}
#{338}{}{We met a guy who stayed too long in the sun. He went completely crazy. So we put him out of his misery. Better that way.}
{338}{}{我们遇到一个在阳光下呆得太久的人。他完全疯了。所以我们把他从痛苦中救了出来。那样更好。}
#{339}{}{The sun can really screw your head. You start seeing things which aren't there. Watch out for that.}
{339}{}{太阳真的能把你的头晒坏。你开始看到一些不存在的东西。小心点。}
#{340}{}{Don't try to rob us, it's not worth it. We can fight and we don't have anything valuable.}
{340}{}{别想抢劫我们，这不值得。我们可以战斗，但我们没有任何有价值的东西。}
#{341}{}{We haven't met any friendlies for a long time now. It's nice to meet someone who doesn't attack you right away.}
{341}{}{我们好久没见朋友了。很高兴见到一个不会马上攻击你的人。}
#{342}{}{I've seen things in the wilderness... If I told you, you wouldn't believe me.}
{342}{}{我见过荒野里的东西。。。如果我告诉你，你不会相信我的。}
#{343}{}{Damn, I don't even know how long we've been underway anymore. I've lost count.}
{343}{}{妈的，我都不知道我们已经开了多久了。我数不清了。}
#{344}{}{We want to stop in that town... Damn, I forgot its stupid name.}
{344}{}{我们想停在那个镇上。。。该死，我忘了它愚蠢的名字。}
#{500}{}{Well if you want we can trade something. But don't try anything funny.}
{500}{}{如果你愿意，我们可以做点交易。但是不要尝试任何有趣的事情。}
#{501}{}{I think, since we've come across each other, we might as well make a profit, eh?}
{501}{}{我想，既然我们相遇了，我们还是盈利吧？}
#{502}{}{We can trade, but if you try anything funny, we cut you down. Got that?}
{502}{}{我们可以交易，但如果你想搞笑，我们就把你砍掉。明白了吗？}
#{503}{}{I don't often meet people who don't want to kill or rob me. You don't, right? I don't have too many things...}
{503}{}{我不常遇到不想杀我或抢劫我的人。你不会吧？我没有太多东西。。。}
#{504}{}{If you need to resupply, I guess we can trade something.}
{504}{}{如果你需要补给，我想我们可以交换一些东西。}
#{505}{}{You want to trade? OK. But I'll be watching you.}
{505}{}{你想交易吗？好 啊。但我会看着你的。}
#{506}{}{I don't like staying in one place with strangers for too long. If you want to trade, be quick. I don't have so many things anyway.}
{506}{}{我不喜欢和陌生人呆在一个地方太久。如果你想交易，就快点。反正我没有那么多东西。}
#{507}{}{Let's trade. Show me whatcha got.}
{507}{}{我们交易吧。给我看看你有什么。}
#{508}{}{I'll take everything you have. I'll take it off of your corpses, if I have to.}
{508}{}{我要你所有的东西。如果有必要的话，我会把它从你的尸体上取下来。}
#{509}{}{I don't want anything. I better go.}
{509}{}{我什么都不要。我得走了。}
#{510}{}{Show... whaaaa?!}
{510}{}{显示。。。什么？！}
#{511}{}{Wanna cap! Bang you!}
{511}{}{想要瓶盖！砰的一声！}
#{512}{}{Meeeeh... Bye.}
{512}{}{再见。。。再见。}
#{550}{}{Right. I think it's for the best if we both go our separate ways now.}
{550}{}{正确的。我认为我们现在各奔东西是最好的。}
#{551}{}{And now I'll take everything you've got. I'll take it off of your corpses, if I have to.}
{551}{}{现在我要拿走你所有的东西。如果有必要的话，我会把它从你的尸体上取下来。}
#{552}{}{Goodbye.}
{552}{}{再见。}
#{553}{}{Wanna all cap! Bang you!}
{553}{}{想要所有的瓶盖！砰的一声！}
#{554}{}{Bye!}
{554}{}{再见！}
