#{100}{}{You see a junkie.}
{100}{}{你看到一个瘾君子。}
#{101}{}{You see a junkie.}
{101}{}{你看到一个瘾君子。}
#{200}{}{You see a heavily drugged junkie.}
{200}{}{你看到一个吸毒成性的瘾君子。}
#{201}{}{You see a heavily drugged junkie.}
{201}{}{你看到一个吸毒成性的瘾君子。}
#{300}{}{Heehow, you've got a funny, darkish glow.}
{300}{}{嘿，你有一个有趣的，暗发光。}
#{301}{}{Sheesh, you're one big cub.}
{301}{}{嘘，你真是个大家伙。}
#{302}{}{Don't tell them what we know, not here.}
{302}{}{别告诉他们我们知道的，别在这儿。}
#{303}{}{Ahhh ...}
{303}{}{啊。。。}
#{304}{}{D'ya see me?}
{304}{}{你看见我了吗？}
#{305}{}{Shhh, I'm hiding.}
{305}{}{嘘，我躲起来了。}
#{306}{}{I can run faster'n a wolf!}
{306}{}{我能跑得比狼快！}
#{307}{}{My veins are coming apart.}
{307}{}{我的血管都裂开了。}
#{308}{}{Right there, baby.}
{308}{}{就在那里，宝贝。}
#{309}{}{Oooohhh, can you feel that kick?}
{309}{}{噢，你能感觉到那一脚吗？}
#{310}{}{Howdy, you're glowing.}
{310}{}{你好，你容光焕发。}
#{311}{}{I love you, man!}
{311}{}{我爱你，伙计！}
#{312}{}{Life's been so nice to me. To you, too?}
{312}{}{生活对我很好。对你也是？}
#{313}{}{Peewee flies at night.}
{313}{}{夜猫子在晚上飞。}
#{314}{}{Say hello to my little friend.}
{314}{}{向我的小朋友问好。}
#{315}{}{Tssk, right behind you...}
{315}{}{茨克，就在你后面。。。}
#{316}{}{Mine!}
{316}{}{我的！}
#{317}{}{Oooh, my head.}
{317}{}{哦，我的头。}
#{318}{}{Everything hurts me.}
{318}{}{一切都伤害了我。}
#{319}{}{I'm getting chills.}
{319}{}{我开始发冷了。}
#{320}{}{Oh, I need somethin' more.}
{320}{}{哦，我还需要些东西。}
#{321}{}{I need something to get me goin'.}
{321}{}{我需要些东西让我走。}
#{322}{}{I can't wait, I need it now.}
{322}{}{我等不及了，我现在就要。}
#{323}{}{Ah, leave me alone.}
{323}{}{啊，别管我。}
#{324}{}{I just want to die.}
{324}{}{我只想死。}
#{325}{}{Got some shit?}
{325}{}{有东西吗？}
#{326}{}{I can't stand this too long.}
{326}{}{我受不了这么久。}
#{327}{}{I think I have a fever.}
{327}{}{我想我发烧了。}
#{328}{}{I think I'mnna bend and send.}
{328}{}{我想我要弯下腰来。}
#{329}{}{::Knocks on your armor.:: Is anybody home?}
{329}{}{有人在家吗？}
#{330}{}{Awesome shit!}
{330}{}{太棒了！}
#{331}{}{I'm sleepy ...}
{331}{}{我困了。。。}
#{332}{}{I feel like I'm alive!}
{332}{}{我觉得我还活着！}
#{333}{}{I got tremors, man.}
{333}{}{我有点颤抖，伙计。}
#{334}{}{Maybe if I just slept a bit ...}
{334}{}{也许我只要睡一会儿。。。}
#{335}{}{I'm sleepy ...}
{335}{}{我困了。。。}
#{336}{}{I feel like I'm alive!}
{336}{}{我觉得我还活着！}
#{337}{}{I got tremors, man.}
{337}{}{我有点颤抖，伙计。}
#{338}{}{Maybe if I just slept a bit...}
{338}{}{也许我只要睡一会儿。。。}
#{339}{}{How did you find the way outta here?}
{339}{}{你怎么找到离开这里的路的？}
#{340}{}{You seen my dog yet?}
{340}{}{你看到我的狗了吗？}
#{341}{}{You fell for that and I gotcha?}
{341}{}{你上当了我明白了？}
#{342}{}{How do you find your way out of here?}
{342}{}{你怎么找到离开这里的路？}
#{343}{}{You seen my dog yet?}
{343}{}{你看到我的狗了吗？}
#{344}{}{You fell for that and I gotcha?}
{344}{}{你上当了我明白了？}
#{350}{}{Hello, Mr. Daisy.}
{350}{}{你好，黛西先生。}
#{351}{}{I'm floating...}
{351}{}{我在漂浮。。。}
#{352}{}{I've got the power!}
{352}{}{我有力量！}
#{353}{}{And spinning and spinning and spinning...}
{353}{}{旋转，旋转，旋转。。。}
#{354}{}{All the colors...}
{354}{}{所有的颜色。。。}
#{355}{}{Much higher friend see the heaven?}
{355}{}{更高的朋友看到天堂了吗？}
#{356}{}{They're not listening...}
{356}{}{他们没在听。。。}
#{357}{}{Where am I?}
{357}{}{我在哪？}
#{358}{}{Right here!}
{358}{}{就在这里！}
#{359}{}{No, for God's sake! Stop! Wait...! Ok, go on.}
{359}{}{不，看在上帝的份上！住手！等待。。。！好吧，继续。}
#{360}{}{There, there... Ahhh...}
{360}{}{好了，好了。。。啊。。。}
#{361}{}{Yeah, baby!}
{361}{}{是的，宝贝！}
#{362}{}{What's that?}
{362}{}{那是什么？}
#{363}{}{Colors fading!}
{363}{}{褪色了！}
#{364}{}{Mummy?}
{364}{}{妈妈？}
#{365}{}{Hey! Get away from me! Oh...}
{365}{}{嘿！离我远点！哦。。。}
#{366}{}{Stop doin' that!}
{366}{}{别这样！}
#{367}{}{I can't see... again.}
{367}{}{我看不见。。。再一次。}
#{368}{}{Needin'...}
{368}{}{需要。。。}
#{369}{}{Get more...}
{369}{}{获取更多。。。}
#{370}{}{There? No.}
{370}{}{在那里？不。}
#{371}{}{No. Can't find it.}
{371}{}{不，找不到。}
#{372}{}{Stop it.}
{372}{}{住手。}
#{373}{}{Ugh.}
{373}{}{啊。}
#{374}{}{Oh, the pain.}
{374}{}{哦，痛。}
#{375}{}{::coughs::}
{375}{}{●咳嗽：}
#{376}{}{Oooh, my head!}
{376}{}{噢，我的头！}
#{377}{}{Hello, Mrs. Daisy.}
{377}{}{你好，黛西太太。}
