#{100}{}{You see a ghoul.}
{100}{}{你看到一个僵尸。}
#{150}{}{You see Aaron.}
{150}{}{你看到亚伦了。}
#{200}{}{You see a ghoul. When he moves his mouth, you can see that his jaw doesn't close properly.}
{200}{}{你看到一个僵尸。当他动嘴的时候，你可以看到他的下巴没有合好。}
#{250}{}{You see Aaron, to talk with him is like to talk with a snake that is wrapping slowly around you.}
{250}{}{你看亚伦，跟他说话就像跟一条蛇说话，蛇慢慢地缠着你。}
#{300}{}{Ehm... I assume that the Savior let you go. Well okay theeen...}
{300}{}{嗯。。。我想救世主放了你。好吧，恩。。。}
#{500}{}{Well well weeeell... What are you doing heeere? [The ghoul constantly protracts syllables while talking. You're not sure if it's because his dislocated jaw or if he talks like that on purpose.]}
{500}{}{好吧，我们。。。你在这儿干什么？[僵尸说话的时候不断地拖长音节。你不确定是因为他的下颚脱臼，还是他故意那样说话}
#{501}{}{Who are you?}
{501}{}{你是谁？}
#{502}{}{I want-waaant.}
{502}{}{我要旺特。}
#{550}{}{You don't know? Interesting... I'm Aaron, I'm here so nobody disturbs the Savior over some nonseeense.}
{550}{}{你不知道？有趣。。。我是亚伦，我在这里，所以没有人会因为一些不合理的事情打扰救世主。}
#{551}{}{I want to talk to the Savior.}
{551}{}{我想和救世主谈谈。}
#{552}{}{Is it possible to talk with some of the reborn?}
{552}{}{有没有可能和一些重生的人谈谈？}
#{553}{}{What's on Blue 6?}
{553}{}{蓝色6上有什么？}
#{554}{}{What happened to your mouth?}
{554}{}{你的嘴怎么了？}
#{555}{}{I see, I'm going to mind my own business then.}
{555}{}{我明白了，那我就管好自己的事了。}
#{600}{}{Of course you waaant. Everybody waaants.}
{600}{}{你当然想。大家都很高兴。}
#{601}{}{So, can I talk with him?}
{601}{}{我能和他谈谈吗？}
#{650}{}{Of course nooot. The Savior has to take caaare of the whole Rebirth, he doesn't have time for some hollow taaalk.}
{650}{}{当然没有。救世主必须接受所有的重生，他没有时间做一些空洞的祈祷。}
#{651}{}{It's important.}
{651}{}{这很重要。}
#{652}{}{I have to talk to him!}
{652}{}{我得和他谈谈！}
#{653}{}{Forget it.}
{653}{}{算了吧。}
#{654}{}{Enough, if you won't let me talk to him, I'll shoot your brain out of your ugly head.}
{654}{}{够了，如果你不让我和他说话，我就把你丑陋的脑袋打爆。}
#{700}{}{Suuure, suuure that it's important. For you. No doubt about it. But it doesn't chaaange a thing.}
{700}{}{我知道这很重要。为你。毫无疑问。但这一点也不奇怪。}
#{701}{}{I have to talk to him!}
{701}{}{我得和他谈谈！}
#{702}{}{Forget it.}
{702}{}{算了吧。}
#{703}{}{Enough, if you won't let me talk to him, I'll shoot your brain out of your ugly head.}
{703}{}{够了，如果你不让我和他说话，我就把你丑陋的脑袋打爆。}
#{750}{}{And may I know who you aaare? What makes you feeel so impooortant?}
{750}{}{我能知道你是谁吗？是什么让你觉得自己如此重要？}
#{751}{}{Geoff.}
{751}{}{杰夫。}
#{752}{}{Erick.}
{752}{}{埃里克。}
#{753}{}{Richard.}
{753}{}{理查德。}
#{754}{}{Tramell.}
{754}{}{特拉梅尔。}
#{755}{}{I'm the Thirteenth Reborn.}
{755}{}{我是第十三个重生。}
#{756}{}{I'm the Thirteenth Reborn.}
{756}{}{我是第十三个重生。}
#{757}{}{You're right, I'm not important at all. Goodbye.}
{757}{}{你说得对，我一点都不重要。再见。}
#{800}{}{You know that the Savior always loves to listen about the progress of the research, but now it's not a good time. I'm suuure you understand.}
{800}{}{你知道救世主总是喜欢听研究的进展，但现在不是时候。我很高兴你能理解。}
#{801}{}{But I want to know...}
{801}{}{但我想知道。。。}
#{802}{}{OK.}
{802}{}{好 啊。}
#{850}{}{Please, have some respect. Thank you. Byeee. [He dismisses you and doesn't pay attention to you anymore. He obviously considers the discussion over.]}
{850}{}{请尊重我。非常感谢。再见。[他辞退了你，不再理你。他显然考虑过这次讨论。]}
#{851}{}{Dammit... Goodbye.}
{851}{}{该死的。。。再见。}
#{900}{}{Weeell... Erick, if it's something that you can't discuss with Geoff, the Savior will talk to you, when he feeels like it.}
{900}{}{威尔。。。埃里克，如果有什么事你不能和杰夫讨论，救世主会在他喜欢的时候跟你说的。}
#{901}{}{OK.}
{901}{}{好 啊。}
#{950}{}{The Savior is excited about your work and especially about your tirelessness and your resolve. That's why he would prefer that you continue working, instead of distracting him.}
{950}{}{救世主对你的工作感到兴奋，尤其是你的不懈努力和决心。这就是为什么他希望你继续工作，而不是分散他的注意力。}
#{951}{}{OK.}
{951}{}{好 啊。}
#{1000}{}{Have you caught the Thirteenth yet? Nooo? There is no other reason for you to distract the Savior or yourseeelf.}
{1000}{}{你赶上十三号了吗？没有？你没有别的理由去分散救世主或你自己的注意力。}
#{1001}{}{I'm sorry.}
{1001}{}{我很抱歉。}
#{1050}{}{Have you caught the Thirteenth yet? Nooo? There is no other reason for you to distract the Savior or yourseeelf.}
{1050}{}{你赶上十三号了吗？没有？你没有别的理由去分散救世主或你自己的注意力。}
#{1051}{}{I'm sorry.}
{1051}{}{我很抱歉。}
#{1100}{}{Well weeell... Threats? It won't help you much against the guards. They'll be heeere right awaaay.}
{1100}{}{weeell。。。威胁？这对你对付守卫没什么帮助。他们马上就到。}
#{1101}{}{We'll see about that.}
{1101}{}{我们拭目以待。}
#{1150}{}{Oh really? Weeell... When the Savior said that you might try to get in here, I had doubts. But heeere you are... He would like to talk to you, you can go visit him. [Aaron uses the computer to open the door to the Savior.]}
{1150}{}{哦，真的吗？威尔。。。当救世主说你可以进来的时候，我有点怀疑。但在你面前。。。他想和你谈谈，你可以去拜访他。[亚伦用电脑打开了通往救世主的门。]}
#{1151}{}{OK, thanks.}
{1151}{}{好的，谢谢。}
#{1200}{}{Oh really? Weeell... When the Savior said that you might try to get in here, I had doubts. But heeere you are... He would like to talk to you, you can go visit him. [Aaron uses the computer to open the door to the Savior.]}
{1200}{}{哦，真的吗？威尔。。。当救世主说你可以进来的时候，我有点怀疑。但在你面前。。。他想和你谈谈，你可以去拜访他。[亚伦用电脑打开了通往救世主的门。]}
#{1201}{}{OK, thanks.}
{1201}{}{好的，谢谢。}
#{1250}{}{What do you meeean?}
{1250}{}{你知道什么？}
#{1251}{}{Why do you need special permission to go there?}
{1251}{}{你去那里为什么需要特别许可？}
#{1300}{}{So that only people who have something to do there can go theeere, of course.}
{1300}{}{当然，只有有事可做的人才能去那里。}
#{1301}{}{Can I get permission?}
{1301}{}{我能得到许可吗？}
#{1350}{}{Nooo, you surely have nothing to do there.}
{1350}{}{不，你在那里肯定没什么事可做。}
#{1351}{}{I want to talk to the Savior, then.}
{1351}{}{我想和救世主谈谈。}
#{1352}{}{Is it possible to talk with some of the reborn?}
{1352}{}{有没有可能和一些重生的人谈谈？}
#{1354}{}{What happened to your mouth?}
{1354}{}{你的嘴怎么了？}
#{1355}{}{I see, I won't bother you anymore.}
{1355}{}{我明白了，我不会再打扰你了。}
#{1400}{}{I'm afraid nooot... for their own security, of course.}
{1400}{}{恐怕没有。。。当然是为了他们自己的安全。}
#{1401}{}{I want to talk to the Savior, then.}
{1401}{}{我想和救世主谈谈。}
#{1402}{}{What's on Blue 6?}
{1402}{}{蓝色6上有什么？}
#{1403}{}{What happened to your mouth?}
{1403}{}{你的嘴怎么了？}
#{1404}{}{I see, I won't bother you anymore.}
{1404}{}{我明白了，我不会再打扰你了。}
#{1450}{}{What do you mean what happened?}
{1450}{}{你说发生什么事是什么意思？}
#{1451}{}{Your jaw...}
{1451}{}{你的下巴。。。}
#{1500}{}{Looook, I have no time for your nonseeense.}
{1500}{}{瞧，我没时间听你胡说八道。}
#{1501}{}{I want to talk to the Savior.}
{1501}{}{我想和救世主谈谈。}
#{1502}{}{Is it possible to talk with some of the reborn?}
{1502}{}{有没有可能和一些重生的人谈谈？}
#{1503}{}{Tell me what's on Blue 6 then.}
{1503}{}{那告诉我蓝6上有什么。}
#{1504}{}{I see, I won't bother you anymore.}
{1504}{}{我明白了，我不会再打扰你了。}
#{1550}{}{Well well weeeell... What are you doing heeere? [The ghoul constantly protracts syllables while talking. You're not sure if it's because his dislocated jaw or if he talks like that on purpose.]}
{1550}{}{好吧，我们。。。你在这儿干什么？[僵尸说话的时候不断地拖长音节。你不确定是因为他的下颚脱臼，还是他故意那样说话}
#{1551}{}{Who are you?}
{1551}{}{你是谁？}
#{1552}{}{I want-waaant.}
{1552}{}{我要旺特。}
#{1600}{}{Weren't you here just recently? Don't you have anything to dooo?}
{1600}{}{你不是最近才来吗？你没什么要做的吗？}
#{1601}{}{I want to talk to the Savior.}
{1601}{}{我想和救世主谈谈。}
#{1602}{}{Is it possible to talk with some of the reborn?}
{1602}{}{有没有可能和一些重生的人谈谈？}
#{1603}{}{What's on Blue 6?}
{1603}{}{蓝色6上有什么？}
#{1604}{}{What happened to your mouth?}
{1604}{}{你的嘴怎么了？}
#{1605}{}{I see, I won't bother you anymore.}
{1605}{}{我明白了，我不会再打扰你了。}
#{1606}{}{I want-waaant.}
{1606}{}{我要旺特。}
#{1650}{}{You haven't talked to the Savior yet. You don't want to talk to the guards instead, do you? They don't talk much, geeet it?}
{1650}{}{你还没和救世主谈过。你不想和警卫说话吧？他们不怎么说话，是吗？}
#{1651}{}{Don't you worry.}
{1651}{}{别担心。}
#{1652}{}{Ugh.}
{1652}{}{啊。}
#{1700}{}{You haven't talked to the Savior yet. You don't want to talk to the guards instead, do you? They don't talk much, geeet it?}
{1700}{}{你还没和救世主谈过。你不想和警卫说话吧？他们不怎么说话，是吗？}
#{1701}{}{Don't you worry.}
{1701}{}{别担心。}
#{1702}{}{Ugh.}
{1702}{}{啊。}
#{1750}{}{I'm afraid I'll have to call the guards nooow. We can't let you waaalk around here, if you refuse to talk to the Savior.}
{1750}{}{恐怕我现在得给警卫打电话了。如果你拒绝和救世主说话，我们不能让你在这里闲逛。}
#{1751}{}{Damn.}
{1751}{}{该死。}
#{1752}{}{Ghagha.}
{1752}{}{嘎嘎。}
#{1800}{}{Well well weeell! You surely shouldn't be heeere. The guards will explain it to you.}
{1800}{}{好吧，好吧！你当然不该来这儿。警卫会向你解释的。}
#{1801}{}{Me Thirteenth!}
{1801}{}{我是第十三个！}
#{1802}{}{Oh kay.}
{1802}{}{哦，凯。}
#{1850}{}{Were you trying to say that you're the Thirteenth Reborn? Reaaaly? Weeell... When the Savior said that you might try to get in here, I had doubts. But heeere you are... He would like to talk to you, you can go visit him. [Aaron uses the computer to open the door to the Savior.]}
{1850}{}{你想说你是第十三次重生吗？真的吗？威尔。。。当救世主说你可以进来的时候，我有点怀疑。但在你面前。。。他想和你谈谈，你可以去拜访他。[亚伦用电脑打开了通往救世主的门。]}
#{1851}{}{Ohoooh.}
{1851}{}{哦哦哦。}
#{1900}{}{Well well weeell! You surely shouldn't be heeere. The guards will explain it to you.}
{1900}{}{好吧，好吧！你当然不该来这儿。警卫会向你解释的。}
#{1901}{}{Me Thirteenth!}
{1901}{}{我是第十三个！}
#{1902}{}{Oh kay.}
{1902}{}{哦，凯。}
#{1950}{}{Were you trying to say that you're the Thirteenth Reborn? Reaaaly? Weeell... When the Savior said that you might try to get in here, I had doubts. But heeere you are... He would like to talk to you, you can go visit him. [Aaron uses the computer to open the door to the Savior.]}
{1950}{}{你想说你是第十三次重生吗？真的吗？威尔。。。当救世主说你可以进来的时候，我有点怀疑。但在你面前。。。他想和你谈谈，你可以去拜访他。[亚伦用电脑打开了通往救世主的门。]}
#{1951}{}{Ohoooh.}
{1951}{}{哦哦哦。}
#{2000}{}{Well weeell... What are you doooing? It's not nice. Don't dooo it again.}
{2000}{}{weeell。。。你在干什么？这不好。别再这样了。}
#{2001}{}{OK.}
{2001}{}{好 啊。}
#{2002}{}{Ugh.}
{2002}{}{啊。}
#{2050}{}{Well weeell... This is the second time, you can't say I didn't waaarn you.}
{2050}{}{weeell。。。这是第二次了，你不能说我没有打你。}
#{2051}{}{I just...}
{2051}{}{我只是。。。}
#{2052}{}{Ghagha.}
{2052}{}{嘎嘎。}
#{2100}{}{I'm sure you got a perfect explanation. But nobody caaares. Especially not the guards.}
{2100}{}{我相信你有一个完美的解释。但没人能做到。尤其是警卫。}
#{2101}{}{Dammit.}
{2101}{}{该死的。}
#{2150}{}{Weren't you here just recently? Don't you have anything to dooo?}
{2150}{}{你不是最近才来吗？你没什么要做的吗？}
#{2151}{}{I want to talk to the Savior.}
{2151}{}{我想和救世主谈谈。}
#{2152}{}{Is it possible to talk with some of the reborn?}
{2152}{}{有没有可能和一些重生的人谈谈？}
#{2153}{}{What's on Blue 6?}
{2153}{}{蓝色6上有什么？}
#{2154}{}{What happened to your mouth?}
{2154}{}{你的嘴怎么了？}
#{2155}{}{I see, I won't bother you anymore.}
{2155}{}{我明白了，我不会再打扰你了。}
#{2156}{}{I want-waaant.}
{2156}{}{我要旺特。}
#{2200}{}{Well well weeeell... You're the Thirteenth Reborn, riiight? [The ghoul constantly protracts syllables while talking. You're not sure if it's because his dislocated jaw or if he talks like that on purpose.] When the Savior said that you might try to get in here, I had doubts. But heeere you are ... He would like to talk to you, you can go visit him. [Aaron uses the computer to open the door to the Savior.]}
{2200}{}{好吧，我们。。。你是第十三次重生，莱特？[僵尸说话的时候不断地拖长音节。你不确定是因为他的下颚脱臼，还是他故意那样说话。但在你面前。。。他想和你谈谈，你可以去拜访他。[亚伦用电脑打开了通往救世主的门。]}
#{2201}{}{Well well weeeell... You're the Thirteenth Reborn, riiight? [The ghoul constantly protracts syllables while talking. You're not sure if it's because his dislocated jaw or if he talks like that on purpose.] When the Savior said that you might try to get in here, I had doubts. But heeere you are ... He would like to talk to you, you can go visit him. [Aaron uses the computer to open the door to the Savior.]}
{2201}{}{好吧，我们。。。你是第十三次重生，莱特？[僵尸说话的时候不断地拖长音节。你不确定是因为他的下颚脱臼，还是他故意那样说话。但在你面前。。。他想和你谈谈，你可以去拜访他。[亚伦用电脑打开了通往救世主的门。]}
#{2202}{}{The Savior awaits me? All right, I'll go meet him.}
{2202}{}{救世主在等我？好吧，我去见他。}
#{2203}{}{I don't care for favors. I'll get to the Savior over your dead body.}
{2203}{}{我不喜欢别人帮忙。我会找到你尸体的救世主。}
#{2204}{}{Ohoooh.}
{2204}{}{哦哦哦。}
