#{100}{}{You see a computer.}
{100}{}{你看到一台电脑。}
#{200}{}{You see a computer terminal. The welcome text signals that it's ready to use.}
{200}{}{你看到一个计算机终端。欢迎文本表示它已准备好使用。}
#{300}{}{You have no time for this during combat.}
{300}{}{在战斗中你没有时间这样做。}
#{400}{}{By switching off the generator you helped the prisoners from the 4th floor escape violently.}
{400}{}{你关掉了发电机，帮助4楼的囚犯们猛烈逃跑。}
#{401}{}{By switching off the generator you helped the prisoners from the 4th floor escape violently.}
{401}{}{你关掉了发电机，帮助4楼的囚犯们猛烈逃跑。}
#{402}{}{By switching off the generator you helped the prisoners from the 4th floor escape silently.}
{402}{}{你关掉了发电机，帮助4楼的囚犯安静地逃走了。}
#{403}{}{By switching off the generator you helped the prisoners from the 4th floor escape silently.}
{403}{}{你关掉了发电机，帮助4楼的囚犯安静地逃走了。}
#{550}{}{The service terminal for the generators. Status: Generator No. 1 - Runs on 100% Generator No. 2 - Runs on 100%}
{550}{}{发电机的服务终端。状态：1号发电机-100%运行2号发电机-100%运行}
#{551}{}{[Read "Notification".]}
{551}{}{[阅读“通知”。]}
#{552}{}{[Switch off generator No. 1.]}
{552}{}{[关闭1号发电机。]}
#{553}{}{[Switch off generator No. 2.]}
{553}{}{[关闭2号发电机。]}
#{554}{}{[Leave.]}
{554}{}{[离开]}
#{555}{}{Ugh.}
{555}{}{啊。}
#{600}{}{Because of the botched work of technicians the majority of the systems of Red 4 were connected to these two generators. Generator No. 1 (to your left) powers everything in the lab and its surroundings, generator No. 2 (to your right) powers the rest of the rooms. By switching off one of the generators half of the level will be without power, which could lead to problems because of our involuntary smoothskin guests. That's why I programmed a couple of security protocols preventing the generators from being so easily switched off. It's just to be sure, don't take it as a distrust in your reliability.-Scott}
{600}{}{由于技术人员的拙劣工作，红4号的大部分系统都与这两台发电机相连。1号发电机（在你的左边）为实验室及其周围的一切提供动力，2号发电机（在你的右边）为其余的房间提供动力。关闭其中一台发电机，一半的水位将断电，这可能会因为我们的客人不自觉而导致问题。这就是为什么我编写了几个安全协议来防止发电机如此容易关闭。只是想确定一下，不要把它看作是对你可靠性的不信任。—斯科特}
#{601}{}{[Switch off generator No. 1.]}
{601}{}{[关闭1号发电机。]}
#{602}{}{[Switch off generator No. 2.]}
{602}{}{[关闭2号发电机。]}
#{603}{}{[Leave.]}
{603}{}{[离开]}
#{650}{}{It is not possible to switch off generator No. 1 at this moment.}
{650}{}{此时无法关闭1号发电机。}
#{651}{}{[Bypass the security protocols.]}
{651}{}{[绕过安全协议。]}
#{652}{}{[Leave.]}
{652}{}{[离开]}
#{700}{}{Generator No. 1 was switched off.}
{700}{}{1号发电机已关闭。}
#{701}{}{[Leave.]}
{701}{}{[离开]}
#{750}{}{Attempt to gain unauthorized access detected. Activating alarm.}
{750}{}{检测到试图获得未经授权的访问。启动警报。}
#{751}{}{Damn.}
{751}{}{该死。}
#{800}{}{It is not possible to switch off generator No. 2 at this moment.}
{800}{}{此时无法关闭2号发电机。}
#{801}{}{[Bypass the security protocols.]}
{801}{}{[绕过安全协议。]}
#{802}{}{[Leave.]}
{802}{}{[离开]}
#{850}{}{Generator No. 2 was switched off.}
{850}{}{2号发电机已关闭。}
#{851}{}{[Leave.]}
{851}{}{[离开]}
#{900}{}{The service terminal for the generators. Status: Generator No. 1 - Switched off Generator No. 2 - Runs on 100%}
{900}{}{发电机的服务终端。状态：1号发电机-关闭2号发电机-100%运行}
#{901}{}{[Leave.]}
{901}{}{[离开]}
#{950}{}{The service terminal for the generators. Status: Generator No. 1 - Runs on 100% Generator No. 2 - Switched off}
{950}{}{发电机的服务终端。状态：1号发电机-100%运行2号发电机-关闭}
#{951}{}{[Leave.]}
{951}{}{[离开]}
#{1000}{}{The service terminal for the generators. Status: Generator No. 1 - Damaged Generator No. 2 - Runs on 100%}
{1000}{}{发电机的服务终端。状态：1号发电机-2号发电机损坏-100%运行}
#{1001}{}{[Leave.]}
{1001}{}{[离开]}
#{1002}{}{Ugh.}
{1002}{}{啊。}
#{1050}{}{The service terminal for the generators. Status: Generator No. 1 - Runs on 100% Generator No. 2 - Damaged}
{1050}{}{发电机的服务终端。状态：1号发电机-100%运行2号发电机-损坏}
#{1051}{}{[Leave.]}
{1051}{}{[离开]}
#{1052}{}{Ugh.}
{1052}{}{啊。}
#{1100}{}{The service terminal for the generators. Status: Generator No. 1 - Damaged Generator No. 2 - Damaged}
{1100}{}{发电机的服务终端。状态：1号发电机-损坏2号发电机-损坏}
#{1101}{}{[Leave.]}
{1101}{}{[离开]}
#{1102}{}{Ugh.}
{1102}{}{啊。}
#{1150}{}{The service terminal for the generators. Status: Generator No. 1 - Damaged Generator No. 2 - Switched off}
{1150}{}{发电机的服务终端。状态：1号发电机-损坏的2号发电机-关闭}
#{1151}{}{[Leave.]}
{1151}{}{[离开]}
#{1200}{}{The service terminal for the generators. Status: Generator No. 1 - Switched off  Generator No. 2 - Damaged}
{1200}{}{发电机的服务终端。状态：1号发电机-关闭2号发电机-损坏}
#{1201}{}{[Leave.]}
{1201}{}{[离开]}
