#{100}{}{You see a computer.}
{100}{}{你看到一台电脑。}
#{200}{}{You see a computer terminal. The welcome text signals that it's ready to use.}
{200}{}{你看到一个计算机终端。欢迎文本表示它已准备好使用。}
#{300}{}{You have no time for this during combat.}
{300}{}{在战斗中你没有时间这样做。}
#{500}{}{TecNet 4.1 welcomes you. Log in:}
{500}{}{TecNet 4.1欢迎您。登录：}
#{501}{}{                                      User - Richard}
{501}{}{用户-Richard}
#{502}{}{                                                        Password - ?}
{502}{}{密码-？}
#{503}{}{[Hack this access.]}
{503}{}{[侵入此访问。]}
#{504}{}{[Leave.]}
{504}{}{[离开]}
#{505}{}{Ugh.}
{505}{}{啊。}
#{550}{}{Login was successful.}
{550}{}{登录成功。}
#{551}{}{                                                  You have 2 received messages in inbox.}
{551}{}{收件箱中有2封收到的邮件。}
#{552}{}{                          You have 1 unfinished message.}
{552}{}{您有1封未完成的邮件。}
#{553}{}{Open received messages.}
{553}{}{打开收到的消息。}
#{554}{}{Open unfinished messages.}
{554}{}{打开未完成的邮件。}
#{555}{}{[Log off.]}
{555}{}{[注销。]}
#{600}{}{Attempt to gain unauthorized access detected. Activating alarm.}
{600}{}{检测到试图获得未经授权的访问。启动警报。}
#{601}{}{Damn.}
{601}{}{该死。}
#{650}{}{Received messages:}
{650}{}{收到的消息：}
#{651}{}{                                                     Request to repeat the test 3-571A. Sent by: Erick}
{651}{}{请求重复试验3-571A。发送人：埃里克}
#{652}{}{           Notification on power lines on Red 4. Sent by: Scott}
{652}{}{红色4上的电线通知。发送人：斯科特}
#{653}{}{Read "Request to repeat the test 3-571A"}
{653}{}{阅读“要求重复试验3-571A”}
#{654}{}{Read "Notification on power lines on Red 4"}
{654}{}{阅读“红色4上的电源线通知”}
#{655}{}{Open unfinished messages.}
{655}{}{打开未完成的邮件。}
#{656}{}{[Log off.]}
{656}{}{[注销。]}
#{700}{}{Unfinished messages: }
{700}{}{未完成的消息：}
#{701}{}{                                                  Entry of the test 3-571B.}
{701}{}{试验3-571B的输入。}
#{702}{}{Read "Entry of the test 3-571B"}
{702}{}{阅读“测试条目3-571B”}
#{703}{}{Open received messages.}
{703}{}{打开收到的消息。}
#{704}{}{[Log off.]}
{704}{}{[注销。]}
#{750}{}{Subject No. 01: Man, approximately 30 years old}
{750}{}{第01号受试者：男子，约30岁}
#{751}{}{                  Level of radiation: 34 R}
{751}{}{辐射水平：34 R}
#{752}{}{                                              Died during the 2nd phase}
{752}{}{在第二阶段死亡}
#{753}{}{                                          Note: He was without left arm by the time he was caught.}
{753}{}{注意：他被抓时没有左臂。}
#{754}{}{[Next.]}
{754}{}{[下一步。]}
#{755}{}{Open received messages.}
{755}{}{打开收到的消息。}
#{756}{}{Open unfinished messages.}
{756}{}{打开未完成的邮件。}
#{757}{}{[Log off.]}
{757}{}{[注销。]}
#{800}{}{Subject No. 02: Man, approximately 25 years old}
{800}{}{研究对象02：男子，约25岁}
#{801}{}{                  Level of radiation: 30 R}
{801}{}{辐射水平：30R}
#{802}{}{                                              Died during the 3rd phase}
{802}{}{在第三阶段死亡}
#{803}{}{[Next.]}
{803}{}{[下一步。]}
#{804}{}{[Back.]}
{804}{}{[后退。]}
#{805}{}{Open received messages.}
{805}{}{打开收到的消息。}
#{806}{}{Open unfinished messages.}
{806}{}{打开未完成的邮件。}
#{807}{}{[Log off.]}
{807}{}{[注销。]}
#{850}{}{Subject No. 03: Woman, approximately 20 years old}
{850}{}{第03号受试者：女性，约20岁}
#{851}{}{               Level of radiation: 10 R}
{851}{}{辐射水平：10R}
#{852}{}{                                              Died during the 3rd phase}
{852}{}{在第三阶段死亡}
#{853}{}{[Next.]}
{853}{}{[下一步。]}
#{854}{}{[Back.]}
{854}{}{[后退。]}
#{855}{}{Open received messages.}
{855}{}{打开收到的消息。}
#{856}{}{Open unfinished messages.}
{856}{}{打开未完成的邮件。}
#{857}{}{[Log off.]}
{857}{}{[注销。]}
#{900}{}{Subject No. 04: Woman, approximately 18 years old}
{900}{}{第04号受试者：女性，约18岁}
#{901}{}{               Level of radiation: 9 R}
{901}{}{辐射水平：9R}
#{902}{}{                                               Died during the 4th phase}
{902}{}{在第四阶段死亡}
#{903}{}{                                          Note: A more detailed analysis of thyroid gland is needed during the autopsy.}
{903}{}{注：尸检时需要对甲状腺进行更详细的分析。}
#{904}{}{[Next.]}
{904}{}{[下一步。]}
#{905}{}{[Back.]}
{905}{}{[后退。]}
#{906}{}{Open received messages.}
{906}{}{打开收到的消息。}
#{907}{}{Open unfinished messages.}
{907}{}{打开未完成的邮件。}
#{908}{}{[Log off.]}
{908}{}{[注销。]}
#{950}{}{Subject No. 05: Woman, approximately 40 years old}
{950}{}{05号受试者：女性，约40岁}
#{951}{}{               Level of radiation: 52 R}
{951}{}{辐射水平：52 R}
#{952}{}{                                              Died during the 1st phase}
{952}{}{在第一阶段死亡}
#{953}{}{[Next.]}
{953}{}{[下一步。]}
#{954}{}{[Back.]}
{954}{}{[后退。]}
#{955}{}{Open received messages.}
{955}{}{打开收到的消息。}
#{956}{}{Open unfinished messages.}
{956}{}{打开未完成的邮件。}
#{957}{}{[Log off.]}
{957}{}{[注销。]}
#{1000}{}{Subject No. 06: Man, approximately 30 years old}
{1000}{}{第06号受试者：男子，约30岁}
#{1001}{}{                  Level of radiation: 27 R}
{1001}{}{辐射水平：27 R}
#{1002}{}{                                              Died during the 2nd phase}
{1002}{}{在第二阶段死亡}
#{1003}{}{                                          Note: Extremely large stomach and liver in very poor condition, visible at first sight.}
{1003}{}{注意：胃和肝非常大，状况非常差，一目了然。}
#{1004}{}{[Next.]}
{1004}{}{[下一步。]}
#{1005}{}{[Back.]}
{1005}{}{[后退。]}
#{1006}{}{Open received messages.}
{1006}{}{打开收到的消息。}
#{1007}{}{Open unfinished messages.}
{1007}{}{打开未完成的邮件。}
#{1008}{}{[Log off.]}
{1008}{}{[注销。]}
#{1050}{}{Subject No. 07: Man, approximately 35 years old}
{1050}{}{第07号受试者：男性，约35岁}
#{1051}{}{                  Level of radiation: 89 R}
{1051}{}{辐射水平：89 R}
#{1052}{}{                                              Died during the 1st phase}
{1052}{}{在第一阶段死亡}
#{1053}{}{                                           Note: Subject's health was in a bad condition, he almost died before the testing.}
{1053}{}{注：受试者的健康状况很差，在测试前几乎死亡。}
#{1054}{}{[Next.]}
{1054}{}{[下一步。]}
#{1055}{}{[Back.]}
{1055}{}{[后退。]}
#{1056}{}{Open received messages.}
{1056}{}{打开收到的消息。}
#{1057}{}{Open unfinished messages.}
{1057}{}{打开未完成的邮件。}
#{1058}{}{[Log off.]}
{1058}{}{[注销。]}
#{1100}{}{Subject No. 08: Boy, approximately 6 years old}
{1100}{}{受试者08：男孩，大约6岁}
#{1101}{}{                   Level of radiation: 12 R}
{1101}{}{辐射水平：12R}
#{1102}{}{                                              Died during the 3rd phase}
{1102}{}{在第三阶段死亡}
#{1103}{}{[Next.]}
{1103}{}{[下一步。]}
#{1104}{}{[Back.]}
{1104}{}{[后退。]}
#{1105}{}{Open received messages.}
{1105}{}{打开收到的消息。}
#{1106}{}{Open unfinished messages.}
{1106}{}{打开未完成的邮件。}
#{1107}{}{[Log off.]}
{1107}{}{[注销。]}
#{1150}{}{Subject No. 09: Girl, approximately 8 years old}
{1150}{}{主题09：女孩，大约8岁}
#{1151}{}{                    Level of radiation: 7 R}
{1151}{}{辐射水平：7R}
#{1152}{}{                                               Died during the 4th phase}
{1152}{}{在第四阶段死亡}
#{1153}{}{                                          Note: Some visual similarity with subject No. 04, testing of possible kinship is needed.}
{1153}{}{注：与04号受试者有一定的视觉相似性，需要进行可能的亲属关系测试。}
#{1154}{}{[Next.]}
{1154}{}{[下一步。]}
#{1155}{}{[Back.]}
{1155}{}{[后退。]}
#{1156}{}{Open received messages.}
{1156}{}{打开收到的消息。}
#{1157}{}{Open unfinished messages.}
{1157}{}{打开未完成的邮件。}
#{1158}{}{[Log off.]}
{1158}{}{[注销。]}
#{1200}{}{Subject No. 10: Man, approximately 30 years old}
{1200}{}{研究对象10：男子，约30岁}
#{1201}{}{                  Level of radiation: 28 R}
{1201}{}{辐射水平：28R}
#{1202}{}{                                              Died during the 3rd phase}
{1202}{}{在第三阶段死亡}
#{1203}{}{[Next.]}
{1203}{}{[下一步。]}
#{1204}{}{[Back.]}
{1204}{}{[后退。]}
#{1205}{}{Open received messages.}
{1205}{}{打开收到的消息。}
#{1206}{}{Open unfinished messages.}
{1206}{}{打开未完成的邮件。}
#{1207}{}{[Log off.]}
{1207}{}{[注销。]}
#{1250}{}{Subject No. 11: Man, approximately 35 years old}
{1250}{}{受试者11：男性，约35岁}
#{1251}{}{                   Level of radiation: 41 R}
{1251}{}{辐射水平：41 R}
#{1252}{}{                                              Died during the 2nd phase}
{1252}{}{在第二阶段死亡}
#{1253}{}{                                          Note: It seems like the subject's heart was successfully transplanted in the past.}
{1253}{}{注：受试者的心脏似乎在过去被成功移植。}
#{1254}{}{[Next.]}
{1254}{}{[下一步。]}
#{1255}{}{[Back.]}
{1255}{}{[后退。]}
#{1256}{}{Open received messages.}
{1256}{}{打开收到的消息。}
#{1257}{}{Open unfinished messages.}
{1257}{}{打开未完成的邮件。}
#{1258}{}{[Log off.]}
{1258}{}{[注销。]}
#{1300}{}{Subject No. 12: Woman, approximately 25 years old}
{1300}{}{主题12：女性，约25岁}
#{1301}{}{               Level of radiation: 14 R}
{1301}{}{辐射水平：14R}
#{1302}{}{                                              Died during the 3rd phase}
{1302}{}{在第三阶段死亡}
#{1303}{}{                                           Note: Subject was possibly pregnant, confirmation needed.}
{1303}{}{注：受试者可能怀孕，需要确认。}
#{1304}{}{[Next.]}
{1304}{}{[下一步。]}
#{1305}{}{[Back.]}
{1305}{}{[后退。]}
#{1306}{}{Open received messages.}
{1306}{}{打开收到的消息。}
#{1307}{}{Open unfinished messages.}
{1307}{}{打开未完成的邮件。}
#{1308}{}{[Log off.]}
{1308}{}{[注销。]}
#{1350}{}{Subject No. 13: Man, approximately 20 years old}
{1350}{}{13号受试者：男子，约20岁}
#{1351}{}{                  Level of radiation: 17 R}
{1351}{}{辐射水平：17 R}
#{1352}{}{                                              Died during the 3rd phase}
{1352}{}{在第三阶段死亡}
#{1353}{}{[Next.]}
{1353}{}{[下一步。]}
#{1354}{}{[Back.]}
{1354}{}{[后退。]}
#{1355}{}{Open received messages.}
{1355}{}{打开收到的消息。}
#{1356}{}{Open unfinished messages.}
{1356}{}{打开未完成的邮件。}
#{1357}{}{[Log off.]}
{1357}{}{[注销。]}
#{1450}{}{One of the useless idiots that I have the misfortune to have in my team, broke the test-tubes with blood samples from subjects No. 01 to 05 from the 3-571A test. The rest of the samples were already disposed of. Repeat the test with another five subjects and then send the bodies back to me. As soon as possible. It will be sufficient if they're approximately the same age. - Erick}
{1450}{}{其中一个无用的白痴，我有幸在我的团队中，打破了试管的血液样本从01号到05号受试者从3-571A测试。剩下的样本已经处理掉了。对另外五名受试者重复测试，然后把尸体送回给我。尽快。如果他们年龄差不多就足够了。-埃里克}
#{1451}{}{Open received messages.}
{1451}{}{打开收到的消息。}
#{1452}{}{Open unfinished messages.}
{1452}{}{打开未完成的邮件。}
#{1453}{}{[Log off.]}
{1453}{}{[注销。]}
#{1500}{}{My notifications on the faulty power lines were of the same effect as trying to convince the Mutant Hunters to stop killing ghouls. If you were the one asking for repairs, things might be different. Maybe you're thinking that I only care because I have more work to do by keeping those generators running, and if anything goes wrong, I'd be the one to blame. But you should realize that if such an event occurs, some of the smoothskins could easily tickle your back with a knife. Because I seriously doubt that they glow in the dark, unlike me. - Scott}
{1500}{}{我在有故障的电线上发出的通知与试图说服变种猎人停止捕杀僵尸的效果是一样的。如果你是那个要求修理的人，事情可能会不同。也许你认为我在乎只是因为我有更多的工作要做，让那些发电机继续运转，如果出了什么问题，我就要受到责备。但你应该意识到，如果这样的事件发生，一些光滑的皮肤可以很容易地用刀挠你的背。因为我很怀疑他们在黑暗中发光，不像我。-斯科特}
#{1501}{}{Open received messages.}
{1501}{}{打开收到的消息。}
#{1502}{}{Open unfinished messages.}
{1502}{}{打开未完成的邮件。}
#{1503}{}{[Log off.]}
{1503}{}{[注销。]}
