#{100}{}{You see a security terminal.}
{100}{}{你看到一个安全终端。}
#{200}{}{You see a security terminal. It reports that security hasn't been breached.}
{200}{}{你看到一个安全终端。报告说安全系统没有被破坏。}
#{201}{}{You see a security terminal. It reports that security has been breached, the alarm is on.}
{201}{}{你看到一个安全终端。它报告说安全系统被破坏了，警报打开了。}
#{300}{}{You have no time for this during combat.}
{300}{}{在战斗中你没有时间这样做。}
#{500}{}{Security terminal, level - Red 4, status - security on. Notification: Unauthorized entry will be severely punished.}
{500}{}{安全终端，级别-红色4，状态-安全开启。通知：未经许可擅自进入将受到严厉处罚。}
#{501}{}{[Hack the security robots setup.]}
{501}{}{[破解安全机器人设置。]}
#{502}{}{Activate alarm.}
{502}{}{启动警报。}
#{503}{}{[Leave.]}
{503}{}{[离开]}
#{504}{}{Ugh.}
{504}{}{啊。}
#{550}{}{Security terminal, level - Red 4, status - security breached. All personnel: Report immediately to your workplaces. Anybody out of their designated workplace can be considered an intruder.}
{550}{}{安全终端，红色4级，状态-安全被破坏。所有人员：立即向工作场所报告。任何离开指定工作场所的人都可以被视为入侵者。}
#{551}{}{[Hack the security robots setup.]}
{551}{}{[破解安全机器人设置。]}
#{552}{}{[Try to deactivate security force fields.]}
{552}{}{[尝试停用安全部队字段。]}
#{553}{}{[Try to activate security force fields.]}
{553}{}{[尝试激活安全部队字段。]}
#{554}{}{[Leave.]}
{554}{}{[离开]}
#{555}{}{Ugh.}
{555}{}{啊。}
#{600}{}{Security robots setup on level Red 4. Access - Security technician. Access restricted.}
{600}{}{安全机器人设置在红色4层。进入-安全技术人员。访问受限。}
#{601}{}{Deactivate robots.}
{601}{}{停用机器人。}
#{602}{}{Activate robots.}
{602}{}{启动机器人。}
#{603}{}{Back to the main menu.}
{603}{}{返回主菜单。}
#{604}{}{[Log off.]}
{604}{}{[注销。]}
#{650}{}{Security robots deactivated.}
{650}{}{安全机器人停用。}
#{651}{}{Activate robots.}
{651}{}{启动机器人。}
#{652}{}{Back to the main menu.}
{652}{}{返回主菜单。}
#{653}{}{[Log off.]}
{653}{}{[注销。]}
#{700}{}{Security robots activated.}
{700}{}{安全机器人启动。}
#{701}{}{Deactivate robots.}
{701}{}{停用机器人。}
#{702}{}{Back to the main menu.}
{702}{}{返回主菜单。}
#{703}{}{[Log off.]}
{703}{}{[注销。]}
#{750}{}{Security robots setup on level Red 4. Access - Security forces. Access restricted.}
{750}{}{安全机器人设置在红色4层。进入-安全部队。访问受限。}
#{751}{}{Deactivate robots.}
{751}{}{停用机器人。}
#{752}{}{Activate robots.}
{752}{}{启动机器人。}
#{753}{}{Set all persons as enemy targets.}
{753}{}{把所有人都当作敌人的目标。}
#{754}{}{Restore the standard target setup.}
{754}{}{恢复标准目标设置。}
#{755}{}{Back to the main menu.}
{755}{}{返回主菜单。}
#{756}{}{[Log off.]}
{756}{}{[注销。]}
#{800}{}{Security robots deactivated.}
{800}{}{安全机器人停用。}
#{801}{}{Activate robots.}
{801}{}{启动机器人。}
#{802}{}{Set all persons as enemy targets.}
{802}{}{把所有人都当作敌人的目标。}
#{803}{}{Restore the standard target setup.}
{803}{}{恢复标准目标设置。}
#{804}{}{Back to the main menu.}
{804}{}{返回主菜单。}
#{805}{}{[Log off.]}
{805}{}{[注销。]}
#{850}{}{Security robots activated.}
{850}{}{安全机器人启动。}
#{851}{}{Deactivate robots.}
{851}{}{停用机器人。}
#{852}{}{Set all persons as enemy targets.}
{852}{}{把所有人都当作敌人的目标。}
#{853}{}{Restore the standard target setup.}
{853}{}{恢复标准目标设置。}
#{854}{}{Back to the main menu.}
{854}{}{返回主菜单。}
#{855}{}{[Log off.]}
{855}{}{[注销。]}
#{900}{}{The alteration in target setup completed.}
{900}{}{目标设置中的更改已完成。}
#{901}{}{Deactivate robots.}
{901}{}{停用机器人。}
#{902}{}{Activate robots.}
{902}{}{启动机器人。}
#{903}{}{Set all persons as enemy targets.}
{903}{}{把所有人都当作敌人的目标。}
#{904}{}{Restore the standard target setup.}
{904}{}{恢复标准目标设置。}
#{905}{}{Back to the main menu.}
{905}{}{返回主菜单。}
#{906}{}{[Log off.]}
{906}{}{[注销。]}
#{950}{}{Security robots setup on level Red 4. Access - Executive personnel. Full access granted.}
{950}{}{安全机器人设置在红色4层。访问-执行人员。已授予完全访问权限。}
#{951}{}{Deactivate robots.}
{951}{}{停用机器人。}
#{952}{}{Activate robots.}
{952}{}{启动机器人。}
#{953}{}{Set all persons as enemy targets.}
{953}{}{把所有人都当作敌人的目标。}
#{954}{}{Restore the standard target setup.}
{954}{}{恢复标准目标设置。}
#{955}{}{Switch friendly and enemy targets according to the standard setup.}
{955}{}{根据标准设置切换友方和敌方目标。}
#{956}{}{Back to the main menu.}
{956}{}{返回主菜单。}
#{957}{}{[Log off.]}
{957}{}{[注销。]}
#{1000}{}{Security robots deactivated.}
{1000}{}{安全机器人停用。}
#{1001}{}{Activate robots.}
{1001}{}{启动机器人。}
#{1002}{}{Set all persons as enemy targets.}
{1002}{}{把所有人都当作敌人的目标。}
#{1003}{}{Restore the standard target setup.}
{1003}{}{恢复标准目标设置。}
#{1004}{}{Switch friendly and enemy targets according to the standard setup.}
{1004}{}{根据标准设置切换友方和敌方目标。}
#{1005}{}{Back to the main menu.}
{1005}{}{返回主菜单。}
#{1006}{}{[Log off.]}
{1006}{}{[注销。]}
#{1050}{}{Security robots activated.}
{1050}{}{安全机器人启动。}
#{1051}{}{Deactivate robots.}
{1051}{}{停用机器人。}
#{1052}{}{Set all persons as enemy targets.}
{1052}{}{把所有人都当作敌人的目标。}
#{1053}{}{Restore the standard target setup.}
{1053}{}{恢复标准目标设置。}
#{1054}{}{Switch friendly and enemy targets according to the standard setup.}
{1054}{}{根据标准设置切换友方和敌方目标。}
#{1055}{}{Back to the main menu.}
{1055}{}{返回主菜单。}
#{1056}{}{[Log off.]}
{1056}{}{[注销。]}
#{1100}{}{The alteration in target setup completed.}
{1100}{}{目标设置中的更改已完成。}
#{1101}{}{Deactivate robots.}
{1101}{}{停用机器人。}
#{1102}{}{Activate robots.}
{1102}{}{启动机器人。}
#{1103}{}{Set all persons as enemy targets.}
{1103}{}{把所有人都当作敌人的目标。}
#{1104}{}{Restore the standard target setup.}
{1104}{}{恢复标准目标设置。}
#{1105}{}{Switch friendly and enemy targets according to the standard setup.}
{1105}{}{根据标准设置切换友方和敌方目标。}
#{1106}{}{Back to the main menu.}
{1106}{}{返回主菜单。}
#{1107}{}{[Log off.]}
{1107}{}{[注销。]}
#{1150}{}{Attempt to gain unauthorized access detected. Activating alarm.}
{1150}{}{检测到试图获得未经授权的访问。启动警报。}
#{1151}{}{Back to the main menu.}
{1151}{}{返回主菜单。}
#{1152}{}{[Log off.]}
{1152}{}{[注销。]}
#{1200}{}{Security force fields deactivated.}
{1200}{}{安全部队已关闭。}
#{1201}{}{Activate security force fields.}
{1201}{}{启动安全部队区域。}
#{1202}{}{Back to the main menu.}
{1202}{}{返回主菜单。}
#{1203}{}{[Log off.]}
{1203}{}{[注销。]}
#{1250}{}{Access denied.}
{1250}{}{拒绝访问。}
#{1251}{}{Back to the main menu.}
{1251}{}{返回主菜单。}
#{1252}{}{[Log off.]}
{1252}{}{[注销。]}
#{1300}{}{Activating alarm. The security staff will reach your location in a few seconds.}
{1300}{}{启动警报。保安人员会在几秒钟内到达你的位置。}
#{1301}{}{Back to the main menu.}
{1301}{}{返回主菜单。}
#{1302}{}{[Log off.]}
{1302}{}{[注销。]}
#{1350}{}{Security force fields activated.}
{1350}{}{安全部队已启动。}
#{1351}{}{Deactivate security force fields.}
{1351}{}{关闭安全部队区域。}
#{1352}{}{Back to the main menu.}
{1352}{}{返回主菜单。}
#{1353}{}{[Log off.]}
{1353}{}{[注销。]}
