#{100}{}{You see a computer.}
{100}{}{你看到一台电脑。}
#{200}{}{You see a computer terminal. The welcome text signals that it's ready to use.}
{200}{}{你看到一个计算机终端。欢迎文本表示它已准备好使用。}
#{300}{}{You have no time for this during combat.}
{300}{}{在战斗中你没有时间这样做。}
#{500}{}{TecNet 4.1 welcomes you. Log in:}
{500}{}{TecNet 4.1欢迎您。登录：}
#{501}{}{                                      User - Dave}
{501}{}{用户-Dave}
#{502}{}{                                                           Password - ?}
{502}{}{密码-？}
#{503}{}{[Hack this access.]}
{503}{}{[侵入此访问。]}
#{504}{}{[Leave.]}
{504}{}{[离开]}
#{505}{}{Ugh.}
{505}{}{啊。}
#{550}{}{Login to the storeroom database successful. Enter the name you want to search.}
{550}{}{成功登录到库房数据库。输入要搜索的名称。}
#{551}{}{Leonard.}
{551}{}{伦纳德。}
#{552}{}{James.}
{552}{}{詹姆斯。}
#{553}{}{Tramell.}
{553}{}{特拉梅尔。}
#{554}{}{Jess.}
{554}{}{杰斯。}
#{555}{}{Erick.}
{555}{}{埃里克。}
#{556}{}{Cecilia.}
{556}{}{塞西莉亚。}
#{557}{}{Robert.}
{557}{}{罗伯特。}
#{558}{}{Darrell.}
{558}{}{达雷尔。}
#{559}{}{Chris.}
{559}{}{克里斯。}
#{560}{}{Feargus.}
{560}{}{费格斯。}
#{561}{}{Max.}
{561}{}{最大值。}
#{562}{}{[Log off.]}
{562}{}{[注销。]}
#{563}{}{[Next.]}
{563}{}{[下一步。]}
#{564}{}{[Previous.]}
{564}{}{[上一页]}
#{600}{}{Attempt to gain unauthorized access detected. Activating alarm.}
{600}{}{检测到试图获得未经授权的访问。启动警报。}
#{601}{}{Damn.}
{601}{}{该死。}
#{650}{}{Enter the name you want to search.}
{650}{}{输入要搜索的名称。}
#{700}{}{This person is not eligible for receiving any new equipment at the moment.}
{700}{}{此人目前没有资格接收任何新设备。}
#{701}{}{Search a different name.}
{701}{}{搜索其他名称。}
#{702}{}{[Log off.]}
{702}{}{[注销。]}
#{750}{}{This person will receive: Microfusion cell (1 item).}
{750}{}{此人将收到：微融合细胞（1项）。}
#{751}{}{Search a different name.}
{751}{}{搜索其他名称。}
#{752}{}{[Log off.]}
{752}{}{[注销。]}
#{800}{}{This person will receive: First aid kit (2 items), doctor's bag (2 items).}
{800}{}{此人将收到：急救箱（2件）、医生包（2件）。}
#{801}{}{Search a different name.}
{801}{}{搜索其他名称。}
#{802}{}{[Log off.]}
{802}{}{[注销。]}
#{850}{}{This person will receive: Plasma pistol (1 item).}
{850}{}{此人将获得：等离子手枪（1件）。}
#{851}{}{Search a different name.}
{851}{}{搜索其他名称。}
#{852}{}{[Log off.]}
{852}{}{[注销。]}
#{900}{}{This person will receive: Power armor (1 item), Gatling laser (1 item), microfusion cell (1 item), stimpak (5 items).}
{900}{}{此人将获得：能量护甲（1件），关灯激光（1件），微聚变电池（1件），史汀帕克（5件）。}
#{901}{}{Search a different name.}
{901}{}{搜索其他名称。}
#{902}{}{[Log off.]}
{902}{}{[注销。]}
#{950}{}{This person will receive: }
{950}{}{此人将收到：}
#{951}{}{Heavy weapon (1 item)}
{951}{}{重武器（1件）}
#{952}{}{Laser pistol (1 item)}
{952}{}{激光手枪（1件）}
#{953}{}{ultra stimpak (2 items)}
{953}{}{ultra stimpak（2项）}
#{954}{}{, }
{954}{}{,}
#{955}{}{.}
{955}{}{.}
#{956}{}{Search a different name.}
{956}{}{搜索其他名称。}
#{957}{}{[Log off.]}
{957}{}{[注销。]}
