#{100}{}{You see a computer.}
{100}{}{你看到一台电脑。}
#{200}{}{You see a computer terminal. The welcome text signals that it's ready to use.}
{200}{}{你看到一个计算机终端。欢迎文本表示它已准备好使用。}
#{300}{}{You have no time for this during combat.}
{300}{}{在战斗中你没有时间这样做。}
#{500}{}{[You see letters, a lot of letters. You don't like letters, your head is spinning around.]}
{500}{}{[你看到字母，很多字母。你不喜欢字母，你的脑袋在转}
#{501}{}{Ugh.}
{501}{}{啊。}
#{550}{}{The Vault-Tec uranium nuclear reactor service terminal. Reactor condition is normal.}
{550}{}{铀核反应堆服务终端。反应堆状态正常。}
#{551}{}{Status?}
{551}{}{状态？}
#{552}{}{Eject control rods.}
{552}{}{弹出控制棒。}
#{553}{}{Command the service robot.}
{553}{}{指挥服务机器人。}
#{554}{}{[Leave.]}
{554}{}{[离开]}
#{600}{}{It is not possible to execute. Critical reactor overheating would be imminent. This action can be authorized only from the main computer in Red 5.}
{600}{}{无法执行。临界反应堆过热将迫在眉睫。此操作只能从红色5的主计算机授权。}
#{601}{}{Command the service robot.}
{601}{}{指挥服务机器人。}
#{602}{}{[Leave.]}
{602}{}{[离开]}
#{650}{}{Service robot active and ready.}
{650}{}{服务机器人已启动并准备就绪。}
#{651}{}{Perform standard cooling system maintenance.}
{651}{}{执行标准冷却系统维护。}
#{652}{}{Perform standard thermal shield maintenance.}
{652}{}{执行标准隔热板维护。}
#{653}{}{Perform standard coil maintenance.}
{653}{}{执行标准线圈维护。}
#{654}{}{Perform standard central computer maintenance.}
{654}{}{执行标准中央计算机维护。}
#{655}{}{Perform standard wave compiler maintenance.}
{655}{}{执行标准wave编译器维护。}
#{656}{}{Move onto reactor service.}
{656}{}{进入反应堆服务。}
#{657}{}{[Leave.]}
{657}{}{[离开]}
#{700}{}{Action ready. Execute?}
{700}{}{行动准备就绪。执行？}
#{701}{}{Yes.}
{701}{}{对。}
#{702}{}{Cancel.}
{702}{}{取消。}
#{703}{}{[Leave.]}
{703}{}{[离开]}
#{750}{}{Performing... [The robot comes to a device which it cleans, and continues by checking its parts for a couple of minutes. Then it comes back.] Action done.}
{750}{}{表演。。。[机器人来到它清洁的设备前，继续检查它的部件几分钟。然后它又回来了。]行动完成了。}
#{751}{}{Perform different action.}
{751}{}{执行不同的操作。}
#{752}{}{Move onto reactor service.}
{752}{}{进入反应堆服务。}
#{753}{}{[Leave.]}
{753}{}{[离开]}
#{800}{}{Action ready. Execute?}
{800}{}{行动准备就绪。执行？}
#{801}{}{Yes.}
{801}{}{对。}
#{802}{}{[Reroute the robot trajectory so he will crash into computer.]}
{802}{}{[重新安排机器人的轨迹，让他撞上电脑。]}
#{803}{}{Cancel.}
{803}{}{取消。}
#{804}{}{[Leave.]}
{804}{}{[离开]}
#{850}{}{The service robot is performing standard central computer maintenance. It is not possible to perform another action before the current one is finished.}
{850}{}{服务机器人正在执行标准的中央计算机维护。在当前操作完成之前，不可能执行其他操作。}
#{851}{}{Move onto reactor service.}
{851}{}{进入反应堆服务。}
#{852}{}{[Leave.]}
{852}{}{[离开]}
#{900}{}{It is not possible to save this trajectory. Reason: Possibility of collision.}
{900}{}{无法保存此轨迹。原因：可能发生碰撞。}
#{901}{}{[Bypass the security protocols.]}
{901}{}{[绕过安全协议。]}
#{902}{}{Cancel.}
{902}{}{取消。}
#{903}{}{[Leave.]}
{903}{}{[离开]}
#{950}{}{New trajectory saved. Action ready. Execute?}
{950}{}{新轨迹已保存。行动准备就绪。执行？}
#{951}{}{Yes.}
{951}{}{对。}
#{952}{}{Cancel.}
{952}{}{取消。}
#{953}{}{[Leave.]}
{953}{}{[离开]}
#{1000}{}{The Vault-Tec uranium nuclear reactor service terminal. The central computer is not working. Reactor condition critical!}
{1000}{}{铀核反应堆服务终端。中央计算机坏了。反应堆情况危急！}
#{1001}{}{Status?}
{1001}{}{状态？}
#{1002}{}{[Leave.]}
{1002}{}{[离开]}
#{1050}{}{The Vault-Tec uranium nuclear reactor service terminal. The cooling device is not working. Reactor condition critical!}
{1050}{}{铀核反应堆服务终端。冷却装置不工作。反应堆情况危急！}
#{1051}{}{Status?}
{1051}{}{状态？}
#{1052}{}{[Leave.]}
{1052}{}{[离开]}
#{1100}{}{Thermal performance: 6000 MW Electrical performance: 1900 MW Steam production: 10200t/hour Temperature: 318}
{1100}{}{热性能：6000MW电性能：1900MW产汽量：10200t/小时温度：318}
#{1101}{}{Eject control rods.}
{1101}{}{弹出控制棒。}
#{1102}{}{Command the service robot.}
{1102}{}{指挥服务机器人。}
#{1103}{}{[Leave.]}
{1103}{}{[离开]}
#{1150}{}{Thermal performance: 6000 MW Electrical performance: 1900 MW Steam production: 10200t/hour Temperature: 1200 ... 1400 ... 1600 }
{1150}{}{热性能：6000MW电性能：1900MW产汽量：10200t/小时温度：1200。。。1400 ... 1600}
#{1151}{}{[Leave.]}
{1151}{}{[离开]}
#{1200}{}{The central computer does not provide information.}
{1200}{}{中央计算机不提供信息。}
#{1201}{}{[Leave.]}
{1201}{}{[离开]}
#{1250}{}{Action ready. Execute?}
{1250}{}{行动准备就绪。执行？}
#{1251}{}{Yes.}
{1251}{}{对。}
#{1252}{}{Cancel.}
{1252}{}{取消。}
#{1253}{}{[Leave.]}
{1253}{}{[离开]}
#{1300}{}{Performing... [The robot cleans all parts of the cooling system and checks if all parts are sealed. Then it comes back.] Action done.}
{1300}{}{表演。。。[机器人清洁冷却系统的所有部件，并检查所有部件是否密封。然后它又回来了。]行动完成了。}
#{1301}{}{Perform different action.}
{1301}{}{执行不同的操作。}
#{1302}{}{Move onto reactor service.}
{1302}{}{进入反应堆服务。}
#{1303}{}{[Leave.]}
{1303}{}{[离开]}
#{1350}{}{Action ready. Execute?}
{1350}{}{行动准备就绪。执行？}
#{1351}{}{Yes.}
{1351}{}{对。}
#{1352}{}{Cancel.}
{1352}{}{取消。}
#{1353}{}{[Leave.]}
{1353}{}{[离开]}
#{1400}{}{Performing... [The robot passes around whole reactor coil and checks if it's damaged somewhere. It doesn't find any damage, so it comes back.] Action done.}
{1400}{}{表演。。。[机器人绕过整个反应堆线圈，检查是否有损坏。它没有发现任何损坏，所以它回来了。}
#{1401}{}{Perform different action.}
{1401}{}{执行不同的操作。}
#{1402}{}{Move onto reactor service.}
{1402}{}{进入反应堆服务。}
#{1403}{}{[Leave.]}
{1403}{}{[离开]}
#{1450}{}{The Vault-Tec uranium nuclear reactor service terminal. Control rods ejected. Reactor condition critical!}
{1450}{}{铀核反应堆服务终端。控制棒弹出。反应堆情况危急！}
#{1451}{}{[Leave.]}
{1451}{}{[离开]}
