#{100}{}{You see a computer.}
{100}{}{你看到一台电脑。}
#{200}{}{You see a computer terminal. The welcome text signals that it's ready to use.}
{200}{}{你看到一个计算机终端。欢迎文本表示它已准备好使用。}
#{300}{}{You have no time for this during combat.}
{300}{}{在战斗中你没有时间这样做。}
#{500}{}{[You see letters, a lot of letters. You don't like letters, your head is spinning around.]}
{500}{}{[你看到字母，很多字母。你不喜欢字母，你的脑袋在转}
#{501}{}{Ugh.}
{501}{}{啊。}
#{550}{}{Controls for robotic practice targets.}
{550}{}{机器人练习目标的控制。}
#{551}{}{Information.}
{551}{}{信息。}
#{552}{}{Setup.}
{552}{}{设置。}
#{553}{}{[Leave.]}
{553}{}{[离开]}
#{600}{}{Robots serving as practice targets during live munition shooting practice lack, despite their standard look, a lot of standard devices, which are replaced by a thick anti-shock layer capable of absorbing even the strongest bullets. The corresponding sensors then evaluate the hits, on which the robot reacts and deactivate itself when a hit capable of destroying a default robot is recorded. In the highly unlikely case of the anti-shock layer being damaged, the robots are capable of self-repair. In that case they deactivate themselves immediately and start with internal repairs.}
{600}{}{在实弹射击练习中，作为练习目标的机器人，尽管外观标准，但缺乏许多标准装置，取而代之的是能够吸收最强子弹的厚防震层。然后，相应的传感器评估撞击，当记录到能够摧毁默认机器人的撞击时，机器人会在撞击上做出反应并自行关闭。在极不可能的情况下，防冲击层被损坏，机器人能够自我修复。在这种情况下，他们立即停用自己，并开始内部维修。}
#{601}{}{Setup.}
{601}{}{设置。}
#{602}{}{[Leave.]}
{602}{}{[离开]}
#{650}{}{Connection with robots established. Enter your selection.}
{650}{}{与机器人建立联系。输入您的选择。}
#{651}{}{Restart robots.}
{651}{}{重启机器人。}
#{652}{}{Show the status of the robot number 1.}
{652}{}{显示1号机器人的状态。}
#{653}{}{Show the status of the robot number 2.}
{653}{}{显示2号机器人的状态。}
#{654}{}{Show the status of the robot number 3.}
{654}{}{显示3号机器人的状态。}
#{655}{}{Back to the main menu.}
{655}{}{返回主菜单。}
#{656}{}{[Leave.]}
{656}{}{[离开]}
#{700}{}{Robotic practice targets restarted.}
{700}{}{机器人练习目标重新启动。}
#{701}{}{Show the status of the robot number 1.}
{701}{}{显示1号机器人的状态。}
#{702}{}{Show the status of the robot number 2.}
{702}{}{显示2号机器人的状态。}
#{703}{}{Show the status of the robot number 3.}
{703}{}{显示3号机器人的状态。}
#{704}{}{Back to the main menu.}
{704}{}{返回主菜单。}
#{705}{}{[Leave.]}
{705}{}{[离开]}
#{750}{}{Damage }
{750}{}{损坏}
#{751}{}{% }
{751}{}{%}
#{752}{}{Robot deactivated.}
{752}{}{机器人已停用。}
#{753}{}{Restart robots.}
{753}{}{重启机器人。}
#{754}{}{Show the status of the robot number 1.}
{754}{}{显示1号机器人的状态。}
#{755}{}{Show the status of the robot number 2.}
{755}{}{显示2号机器人的状态。}
#{756}{}{Show the status of the robot number 3.}
{756}{}{显示3号机器人的状态。}
#{757}{}{Back to the main menu.}
{757}{}{返回主菜单。}
#{758}{}{[Leave.]}
{758}{}{[离开]}
