#{100}{}{You see a ghoul.}
{100}{}{你看到一个僵尸。}
#{101}{}{You see a female ghoul.}
{101}{}{你看到一个女僵尸。}
#{200}{}{You see a doctor working at the infirmary.}
{200}{}{你看到一个医生在医务室工作。}
#{201}{}{You see a doctor working at the infirmary.}
{201}{}{你看到一个医生在医务室工作。}
#{300}{}{Are you hurt?}
{300}{}{你受伤了吗？}
#{301}{}{Are you in pain?}
{301}{}{你疼吗？}
#{302}{}{Jess is head of the infirmary.}
{302}{}{杰斯是医务室主任。}
#{303}{}{If you're OK, get out of here.}
{303}{}{如果你没事，离开这里。}
#{304}{}{The wounded need to remain calm.}
{304}{}{伤员需要保持冷静。}
#{305}{}{They still send us quite a lot of wounded.}
{305}{}{他们仍然送我们很多伤员。}
#{306}{}{I'm sure it's nothing serious.}
{306}{}{我肯定没什么大不了的。}
#{307}{}{Jess is quite OK. When you get to know her better.}
{307}{}{杰斯很好。当你更了解她。}
#{308}{}{Are you hurt?}
{308}{}{你受伤了吗？}
