#{100}{}{You see a massive door made of metal.}
{100}{}{你看到一扇巨大的金属门。}
#{200}{}{The door is hermetically closed and the lock is sealed.}
{200}{}{门是密封的，锁是密封的。}
#{300}{}{It is not possible to pry open the door. There is no space to fit the crowbar.}
{300}{}{撬开这扇门是不可能的。没有地方放撬棍。}
#{301}{}{The electronic lock on the door is sealed. It is not possible to open it.}
{301}{}{门上的电子锁是密封的。不可能打开它。}
#{302}{}{The explosion hasn't destroyed the door, it left only minimal damage.}
{302}{}{爆炸没有摧毁门，只留下了很小的损坏。}
#{303}{}{You weren't able to find any traps on this door.}
{303}{}{你在这扇门上找不到任何陷阱。}
#{304}{}{The door is sealed, it is impossible to open it.}
{304}{}{门是密封的，不可能打开。}
