#{100}{}{You see a massive door made of metal.}
{100}{}{你看到一扇巨大的金属门。}
#{200}{}{The door doesn't have any visible lock. It must be handled from some other place.}
{200}{}{门上看不见锁。必须从别的地方处理。}
#{300}{}{You weren't able to pry the door. It seems like the door was somehow reinforced.}
{300}{}{你没能撬开门。门好像被加固了。}
#{302}{}{The explosion hasn't destroyed the door, it left only minimal damage.}
{302}{}{爆炸没有摧毁门，只留下了很小的损坏。}
#{303}{}{You weren't able to find any traps on this door.}
{303}{}{你在这扇门上找不到任何陷阱。}
