#{100}{}{You see a ghoul.}
{100}{}{你看到一个僵尸。}
#{150}{}{You see Geoff.}
{150}{}{你看杰夫。}
#{200}{}{You see a ghoul in a robe, he's without a doubt an important scientist.}
{200}{}{你看到一个穿着长袍的僵尸，他无疑是个重要的科学家。}
#{201}{}{You see a ghoul in a robe, he's without a doubt an important scientist. He looks like he's being bothered by all the problems of the world.}
{201}{}{你看到一个穿着长袍的僵尸，他无疑是个重要的科学家。他看起来好像被世界上所有的问题困扰着。}
#{250}{}{You see Geoff, leading scientist of rebirth research. He probably never smiles.}
{250}{}{你看杰夫，再生研究的首席科学家。他可能从来不笑。}
#{300}{}{It's awful that these tests need to be repeated.}
{300}{}{太可怕了，这些测试需要重复。}
#{301}{}{We're still missing the solution.}
{301}{}{我们仍然没有找到解决办法。}
#{302}{}{Check the third and fifth sequence again.}
{302}{}{再次检查第三和第五顺序。}
#{303}{}{Send it for further analysis.}
{303}{}{送去做进一步分析。}
#{304}{}{Protraction costs us more lives.}
{304}{}{旷日持久使我们付出更多的生命。}
#{305}{}{This data didn't shed much light on the problem.}
{305}{}{这些数据并没有说明这个问题。}
#{306}{}{I need the exact data of the composition.}
{306}{}{我需要作文的准确数据。}
#{307}{}{The necessary components are in the storeroom.}
{307}{}{必要的部件在储藏室里。}
#{500}{}{Yes?}
{500}{}{对？}
#{501}{}{Who are you?}
{501}{}{你是谁？}
#{502}{}{Never mind, I'm sorry.}
{502}{}{没关系，对不起。}
#{503}{}{Hooga - chaka.}
{503}{}{呼嘎-查卡。}
#{550}{}{My name is Geoff, I'm the leading scientist of rebirth research. Are you new here? Surely not as a scientist, I would've been notified about it.}
{550}{}{我叫杰夫，我是再生研究的领军科学家。你是新来的吗？当然不是作为一个科学家，我会被通知的。}
#{551}{}{Isn't the Savior the leading researcher?}
{551}{}{救世主不是研究的领头羊吗？}
#{552}{}{How's the research going?}
{552}{}{研究进展如何？}
#{553}{}{Were you in the group of people that came here first after the Savior?}
{553}{}{你是在救世主之后第一个来到这里的人吗？}
#{554}{}{I'm curious if the current reborn know that they'll die as a result of rebirth.}
{554}{}{我很好奇现在的重生者是否知道他们会因为重生而死去。}
#{555}{}{Hasn't it ever occurred to you that neither the machine nor the process of rebirth ever worked properly?}
{555}{}{难道你没有想过，机器和重生的过程都不能正常工作吗？}
#{556}{}{I'm looking for someone else. I'm sorry that I disturbed you.}
{556}{}{我在找别人。很抱歉打扰了你。}
#{600}{}{The Savior is in charge of a lot of stuff and despite of what you might have heard of him, he isn't qualified enough for such research. But, naturally, he's quite interested in our results and he advises us from time to time, when he knows, based on his experience with his own rebirth, that our research efforts would be unavailing. It's such a shame that he doesn't remember much.}
{600}{}{救世主掌管着很多事情，尽管你可能听说过他，但他不足以胜任这样的研究。但是，很自然地，他对我们的研究结果很感兴趣，他时不时地建议我们，根据他自己重生的经历，当他知道我们的研究努力将是徒劳的时候。真遗憾，他记不太清楚了。}
#{601}{}{Does he even know what he was doing when he performed the first successful rebirth?}
{601}{}{他知道他第一次成功重生时在做什么吗？}
#{602}{}{And how is the research going?}
{602}{}{研究进展如何？}
#{603}{}{Can you answer a completely different question for me?}
{603}{}{你能为我回答一个完全不同的问题吗？}
#{604}{}{Thank you for answers. Goodbye.}
{604}{}{谢谢你的回答。再见。}
#{650}{}{You have to understand that he did it all alone, it was physically and mentally exhausting and according to what he told us, his body was extensively affected by radiation and changed by mutations, which really affected his memory from the time before the rebirth.}
{650}{}{你必须明白，他是一个人做的，身心都很疲惫，根据他告诉我们的，他的身体受到辐射的广泛影响和变异的改变，这确实影响了他从重生前的记忆。}
#{651}{}{And how is the research going?}
{651}{}{研究进展如何？}
#{700}{}{It hurts me to say it, but badly. So much time came and went and we still haven't found any solution. We're almost sure that the machine isn't damaged in any way, it was tested many times. Even then we still continue to test all the components and its software. But the problem is probably in the actual process of rebirth.}
{700}{}{说这话我很伤心，但很难受。时间来了又去，我们仍然没有找到任何解决办法。我们几乎可以肯定这台机器没有任何损坏，它经过多次测试。即便如此，我们仍然继续测试所有组件及其软件。但问题可能出在重生的实际过程中。}
#{701}{}{What aspects of the process are you focusing on now?}
{701}{}{你现在关注的是这个过程的哪些方面？}
#{702}{}{What aspects of the process are you focusing on in the long term?}
{702}{}{从长远来看，你关注的是这个过程的哪些方面？}
#{703}{}{Why does it take so long?}
{703}{}{为什么要花这么长时间？}
#{704}{}{Can you answer a completely different question for me?}
{704}{}{你能为我回答一个完全不同的问题吗？}
#{705}{}{Thank you for answers. Goodbye.}
{705}{}{谢谢你的回答。再见。}
#{750}{}{In the long term, we dedicate ourselves to research on an auxiliary substance that is being pumped into the body during the process of rebirth. Its effect is similar to the substance used in stimpaks, for instance, but it's highly modified and lethal when pure. Only aided by the machine it starts a specific regenerative process. In the worst case scenario, it's possible that the substance was contaminated and finding the original composition will take a lot of time, given that there's no documentation.}
{750}{}{从长远来看，我们致力于研究一种辅助物质，在重生的过程中被泵入体内。例如，它的作用类似于Stimpak中使用的物质，但它是高度改性的，纯的时候会致命。只有在机器的帮助下，它才能启动一个特定的再生过程。在最坏的情况下，有可能是物质被污染了，如果没有文件证明，找到原始成分将花费大量时间。}
#{751}{}{What aspects of the process are you focusing on now?}
{751}{}{你现在关注的是这个过程的哪些方面？}
#{752}{}{Why does it take so long?}
{752}{}{为什么要花这么长时间？}
#{753}{}{Can you answer a completely different question for me?}
{753}{}{你能为我回答一个完全不同的问题吗？}
#{754}{}{Thank you for answers. Goodbye.}
{754}{}{谢谢你的回答。再见。}
#{800}{}{Richard thinks that we can only use specific subjects as donors, and he's trying to find such subjects. I just hope that he'll come up with some results soon. Any results. Testing his theories cost the lives of too many donors. And what terrifies me even more is the possibility that only an individual with specific, distinctive aspects can be successfully reborn. Hopefully, Erick will soon disprove this theory.}
{800}{}{理查德认为我们只能用特定的对象作为捐赠者，他正在努力寻找这样的对象。我只希望他很快会有结果。任何结果。对他的理论进行检验，牺牲了太多捐赠者的生命。更让我害怕的是，只有一个有着特定、独特方面的人才能成功重生。希望埃里克能很快驳倒这个理论。}
#{801}{}{What aspects of the process are you focusing on in the long term?}
{801}{}{从长远来看，你关注的是这个过程的哪些方面？}
#{802}{}{Why does it take so long?}
{802}{}{为什么要花这么长时间？}
#{803}{}{Can you answer a completely different question for me?}
{803}{}{你能为我回答一个完全不同的问题吗？}
#{804}{}{Thank you for answers. Goodbye.}
{804}{}{谢谢你的回答。再见。}
#{850}{}{Please realize that we've got no documentation nor any data, and since we don't know what the problem is, we have to analyze indeed everything. It's as if we were reinventing the whole process of rebirth, including the machine.}
{850}{}{请注意，我们没有任何文档或数据，因为我们不知道问题出在哪里，所以我们必须分析所有东西。就好像我们在重塑重生的整个过程，包括机器。}
#{851}{}{Why is it that you've got no documentation?}
{851}{}{为什么你没有文件？}
#{852}{}{Were you in the group of people that came here first after the Savior?}
{852}{}{你是在救世主之后第一个来到这里的人吗？}
#{853}{}{Can you answer a completely different question for me?}
{853}{}{你能为我回答一个完全不同的问题吗？}
#{854}{}{Thank you for answers. Goodbye.}
{854}{}{谢谢你的回答。再见。}
#{900}{}{Everything was erased, probably by a virus or due to a computer failure, even though the closure of the rest of the complex was without problems. It's also possible that it was erased on purpose during the closure, for safety reasons, so the data couldn't be stolen. Given the mood of the world back then and Vault-Tec's tendency towards secrecy, it's quite possible.}
{900}{}{所有的东西都被删除了，可能是因为病毒或是电脑故障，尽管关闭大楼的其他部分没有问题。也有可能是出于安全考虑，在关闭过程中故意删除的，所以数据不能被盗。考虑到当时世界的情绪和金库技术公司倾向于保密，这是很有可能的。}
#{901}{}{Were you in the group of people that came here first after the Savior?}
{901}{}{你是在救世主之后第一个来到这里的人吗？}
#{902}{}{Can you answer a completely different question for me?}
{902}{}{你能为我回答一个完全不同的问题吗？}
#{903}{}{Thank you for answers. Goodbye.}
{903}{}{谢谢你的回答。再见。}
#{950}{}{Yes. I was among those who lead the group of people here. The only thing we knew was that this place exists and that they conducted research of radiation and mutation treatment here, but we didn't know how far they got with the research and if we could find the complex. We just had a vague hope, but it was at least something. Now it's probably even worse. Now we know that we can cure everyone, but we still can't figure how.}
{950}{}{对。我是领导这群人的人之一。我们唯一知道的是这个地方的存在，他们在这里进行了辐射和突变治疗的研究，但我们不知道他们的研究进展如何，我们是否能找到这个复合体。我们只是有一个模糊的希望，但它至少是一些东西。现在可能更糟了。现在我们知道我们可以治愈所有人，但我们仍然不知道如何治愈。}
#{951}{}{And the Savior was already here?}
{951}{}{救世主已经来了？}
#{952}{}{Can you answer a completely different question for me?}
{952}{}{你能为我回答一个完全不同的问题吗？}
#{953}{}{Thank you for answers. Goodbye.}
{953}{}{谢谢你的回答。再见。}
#{1000}{}{At first we thought that the complex was empty. All the equipment was intact and dead bodies of the people who worked here were lying around. It wasn't a nice sight to see, and on each level it was the same. Only on the fifth level did it change. It took us a couple of days to get to the fifth level. The complex was running on as low power as possible and all the elevators were blocked. On the fifth level, everything worked, the bodies were removed and we met him. I don't know who was more surprised. He had been here for a few weeks, not remembering anything from his past, not even his own name. He was interested in the machine. And how happy we were when we found out that his goal was the same as ours - the rebirth for all, even if he didn't need it himself anymore. You surely know how it went after that.}
{1000}{}{起初我们以为这个建筑群是空的。所有的设备都完好无损，在这里工作的人的尸体到处都是。这不是一个好看的景象，而且在每个层面上都是一样的。只有到了第五级才有所改变。我们花了几天时间才升到第五级。综合大楼的电力尽可能低，所有电梯都被封锁了。在第五层，一切正常，尸体被移走，我们见到了他。我不知道谁更惊讶。他在这里呆了几个星期，不记得过去的任何事，甚至连自己的名字都不记得了。他对这台机器感兴趣。当我们发现他的目标和我们的一样时，我们是多么的高兴——所有人的重生，即使他自己不再需要了。你肯定知道那之后是怎么回事。}
#{1001}{}{How did you learn about the complex?}
{1001}{}{你是怎么知道这个情结的？}
#{1002}{}{Can you answer a completely different question for me?}
{1002}{}{你能为我回答一个完全不同的问题吗？}
#{1003}{}{Thank you for answers. Goodbye.}
{1003}{}{谢谢你的回答。再见。}
#{1050}{}{Before the war, we worked for the Army on a classified project in the field of genetics. Vault-Tec ran this complex together with the Army, so we knew about it. But no details. We were useful enough for our employers to get reservation in a vault, even with our families. To get reservation in a vault was like to get a voucher for life, I couldn't decline something like that, especially when it applied to my wife and daughter as well. But not even 30 years passed before the ventilation gave up the ghost, it let irradiated air leak into the vault. Those who didn't die from radiation or due to the riots that started, turned into ghouls. Some decided to stay in the vault. The rest of us went searching for this place, it didn't make sense to stay. Especially for me, since I lost my wife and daughter there.}
{1050}{}{战前，我们在陆军从事遗传学领域的一个机密项目。金库技术公司和军队一起管理这个建筑群，所以我们知道了。但没有细节。我们很有用，我们的雇主甚至可以和我们的家人一起在金库里预订房间。在保险库里预订房间就像是拿一张终身优惠券，我不能拒绝这样的事情，尤其是当它也适用于我的妻子和女儿的时候。但就在30年后，通风系统就停止了鬼魂的活动，它让被辐射的空气漏进了地下室。那些没有死于辐射或骚乱的人变成了僵尸。一些人决定留在地下室。我们其他人都去寻找这个地方了，留下来是没有意义的。尤其是对我来说，因为我在那里失去了妻子和女儿。}
#{1051}{}{You didn't know by then that you need donors for the rebirth. Don't you mind now that people have to die, so others can be reborn?}
{1051}{}{那时你还不知道重生需要捐赠者。你不介意现在人必须死，别人才能重生吗？}
#{1052}{}{I was just wondering, how old is a person after rebirth? Some ghouls live for more than a hundred years.}
{1052}{}{我只是在想，一个人重生后多大了？有些僵尸活了一百多年。}
#{1053}{}{Can you answer a completely different question for me?}
{1053}{}{你能为我回答一个完全不同的问题吗？}
#{1054}{}{Thank you for answers. Goodbye.}
{1054}{}{谢谢你的回答。再见。}
#{1055}{}{Wait, have you worked by any chance in the army complex PROGEMA?}
{1055}{}{等等，你有没有在陆军综合项目工作过？}
#{1100}{}{I know, it's terrible. The only hope is, after we fix the problem in the process of rebirth, we'll be able to search for a method to omit donors from the process. The people will hopefully realize that solving this problem will take less time than the acquisition of as many donors would be needed for everyone in the Rebirth. We can't stop now, our efforts cost too many lives, lives of both ghouls and normals, and success would at least give it some purpose.}
{1100}{}{我知道，太可怕了。唯一的希望是，在我们修复了重生过程中的问题之后，我们将能够找到一种方法，在这个过程中省略捐赠者。人们将有希望认识到，解决这个问题所需的时间将比获得更多的捐赠者所需的时间要少。我们现在不能停止，我们的努力付出了太多的生命，僵尸和普通人的生命，成功至少会给它一些目的。}
#{1101}{}{So the promise of the day of rebirth for everybody is still valid?}
{1101}{}{所以对每个人来说，重生之日的承诺仍然有效？}
#{1102}{}{I was just wondering, how old is a person after rebirth? Some ghouls live for more than a hundred years.}
{1102}{}{我只是在想，一个人重生后多大了？有些僵尸活了一百多年。}
#{1103}{}{Can you answer a completely different question for me?}
{1103}{}{你能为我回答一个完全不同的问题吗？}
#{1104}{}{Thank you for answers. Goodbye.}
{1104}{}{谢谢你的回答。再见。}
#{1150}{}{I firmly believe so. I would be opposed to the policy that rebirth is only for certain individuals. Even if I alone decided to not undergo rebirth myself, I understand their impatience, but it wouldn't be right.}
{1150}{}{我坚信是这样。我反对只有某些人才能重生的政策。即使只有我自己决定不重生，我理解他们的不耐烦，但那是不对的。}
#{1151}{}{Why don't you want to be reborn?}
{1151}{}{你为什么不想重生？}
#{1200}{}{I'm too old, it wouldn't make sense to have people die because of me. I guess I wouldn't be able to cope with it.}
{1200}{}{我太老了，让人因为我而死是没有意义的。我想我应付不了了。}
#{1201}{}{I was just wondering, how old is a person after rebirth? Some ghouls live for more than a hundred years.}
{1201}{}{我只是在想，一个人重生后多大了？有些僵尸活了一百多年。}
#{1202}{}{Can you answer a completely different question for me?}
{1202}{}{你能为我回答一个完全不同的问题吗？}
#{1203}{}{Thank you for answers. Goodbye.}
{1203}{}{谢谢你的回答。再见。}
#{1250}{}{I'm too old, it wouldn't make sense to have people die because of me. I guess I wouldn't be able to cope with it. [He sighs sadly.] But I don't want to dissuade you. I'm probably just lying to myself. The main reason is the fact that as a normal human I would be too much reminded of my past life. Of my wife and daughter that I lost. Various kind of people got into the vault where we survived the war. Even the kind that shouldn't be there. They did anything to get in, including murder. But we didn't know that by then, or we just didn't realize it. Less than half a year in and one of them brutally raped and murdered my daughter. She was only fourteen. My wife broke down, and when she heard that they hadn't found the murderer and canceled the investigation, she killed herself. I almost followed in her footsteps.}
{1250}{}{我太老了，让人因为我而死是没有意义的。我想我应付不了了。但我不想劝阻你。我可能只是在骗自己。主要原因是，作为一个正常人，我会过多地想起我过去的生活。我失去的妻子和女儿。各种各样的人进入了我们在战争中幸存下来的地下室。即使是不该在那里的那种。他们什么都没做，包括谋杀。但那时我们并不知道，或者我们只是没有意识到。不到半年的时间，其中一人残忍地强奸并谋杀了我的女儿。她只有十四岁。我妻子崩溃了，当她听说他们没有找到凶手并取消调查时，她自杀了。我几乎跟随着她的脚步。}
#{1251}{}{I was just wondering, how old is a person after rebirth? Some ghouls live for more than a hundred years.}
{1251}{}{我只是在想，一个人重生后多大了？有些僵尸活了一百多年。}
#{1252}{}{I'm sorry about that. Could you answer me another question?}
{1252}{}{对此我很抱歉。你能再回答我一个问题吗？}
#{1253}{}{I'm sorry. Goodbye.}
{1253}{}{我很抱歉。再见。}
#{1300}{}{The Savior makes a selection, and if the said person doesn't know about it, we try to hide it from them. It's cruel, but they can live their last days without worries. Unfortunately, the Thirteenth showed us what it can lead to in the opposite case. Until now, four of the reborn were well acquainted with the fact, yet they didn't refuse the process. It's an honor and another way to serve the Rebirth. The annual rebirth incredibly raises morale and what's more, we collect important data about the very process and its consequences. One person a year, what is that against so many who are killed in combat?}
{1300}{}{救世主做了一个选择，如果说的人不知道，我们试图向他们隐瞒。这很残酷，但他们可以过完最后的日子而不担心。不幸的是，第十三条告诉了我们在相反的情况下它会导致什么。直到现在，四个重生的人都很清楚这个事实，但他们并没有拒绝这个过程。这是一种荣誉，也是为重生服务的另一种方式。每年的重生难以置信地鼓舞了士气，更重要的是，我们收集了有关这个过程及其后果的重要数据。一年一个人，对这么多在战斗中牺牲的人是什么？}
#{1301}{}{Where are the living reborn?}
{1301}{}{生命在哪里重生？}
#{1302}{}{Can you answer a completely different question for me?}
{1302}{}{你能为我回答一个完全不同的问题吗？}
#{1303}{}{Thank you for answers. Goodbye.}
{1303}{}{谢谢你的回答。再见。}
#{1350}{}{Normally they work on this level while they're medically fit, then they're moved to sixth, where they receive quality care. They get good care, and with sedatives they die painlessly. Due to the escape of the Thirteenth the Savior ordered us to place the Eleventh and the Twelfth there immediately. The rest of the reborn had already died, except the Savior of course.}
{1350}{}{正常情况下，当他们身体健康时，他们在这个级别工作，然后他们被转移到第六级，在那里他们接受优质护理。他们得到了很好的照顾，在镇静剂的帮助下，他们无痛地死去。因为第十三个逃走了，救主命令我们立即把第十一个和第十二个放在那里。其余的重生者已经死了，当然除了救世主。}
#{1351}{}{How much comfort do they have on the sixth level?}
{1351}{}{他们在第六层有多舒服？}
#{1352}{}{What if neither the machine nor the process of rebirth ever worked properly?}
{1352}{}{如果机器和重生的过程都不能正常工作呢？}
#{1353}{}{Can you answer a completely different question for me?}
{1353}{}{你能为我回答一个完全不同的问题吗？}
#{1354}{}{Thank you for answers. Goodbye.}
{1354}{}{谢谢你的回答。再见。}
#{1400}{}{I'm sure that the Savior arranged the best care for them. I've never been there myself. To tell you the truth, I don't want to see them die. When I think about how they could've live on if we'd already solved our problem, I don't feel very good. The best thing I can do is to not lose time and to keep trying so nobody else has to die like that.}
{1400}{}{我相信救世主为他们安排了最好的照顾。我自己从没去过那里。说实话，我不想看到他们死。当我想到如果我们已经解决了我们的问题，他们怎么能活下去的时候，我感觉不太好。我能做的最好的事情就是不要浪费时间，继续努力，这样就没有人会像那样死去。}
#{1401}{}{What if there is no solution? What if neither the machine nor the process of rebirth ever worked properly?}
{1401}{}{如果没有解决办法怎么办？如果机器和重生的过程都不能正常工作呢？}
#{1402}{}{Can you answer a completely different question for me?}
{1402}{}{你能为我回答一个完全不同的问题吗？}
#{1403}{}{Thank you for answers. Goodbye.}
{1403}{}{谢谢你的回答。再见。}
#{1450}{}{Our bodies practically don't age, it's probably an effect of a virus unknown to us. After rebirth, our physical age is the same as the age before the ghoulification, maybe a couple years more at most.}
{1450}{}{我们的身体几乎不会衰老，这可能是一种我们不知道的病毒的作用。在重生之后，我们的身体年龄和僵尸之前的年龄是一样的，最多可能多几年。}
#{1451}{}{Tell me, do the current reborn know that they'll die as a result of rebirth?}
{1451}{}{告诉我，现在的重生者知道他们会因为重生而死去吗？}
#{1452}{}{Can you answer a completely different question for me?}
{1452}{}{你能为我回答一个完全不同的问题吗？}
#{1453}{}{Thank you for answers. Goodbye.}
{1453}{}{谢谢你的回答。再见。}
#{1500}{}{Excuse me? How did you think of something like that?}
{1500}{}{请原谅我？你怎么会想到那样的事？}
#{1501}{}{If you want to know, Thomas told me that.}
{1501}{}{如果你想知道，托马斯告诉我的。}
#{1502}{}{I'm just asking.}
{1502}{}{我只是问问。}
#{1550}{}{I can answer you that. The Savior is unquestionable evidence of the functionality of the whole process. And the fact that all the data even remotely related to the machine was erased, probably on purpose, indicates that Vault-Tec was protecting a successful invention.}
{1550}{}{我可以回答你。救世主无疑是整个过程功能的证据。事实上，所有的数据，甚至远程相关的机器被删除，可能是故意的，表明金库科技是保护一个成功的发明。}
#{1551}{}{Have you ever found or recovered any of the data?}
{1551}{}{您是否发现或恢复过任何数据？}
#{1552}{}{Can you answer a completely different question for me?}
{1552}{}{你能为我回答一个完全不同的问题吗？}
#{1553}{}{Thank you for answers. Goodbye.}
{1553}{}{谢谢你的回答。再见。}
#{1600}{}{What?! How's he doing, tell me, hurry, what do you know?}
{1600}{}{什么？！他怎么样了，告诉我，快点，你知道什么？}
#{1601}{}{When he left, Mutant Hunters got a hold of him. They tortured him so he would tell them all he knew about the Rebirth, but he didn't tell them much. When the Hunters' base, where Thomas was kept, was captured by the supermutants, they couldn't help him anymore. He's dead.}
{1601}{}{当他离开时，变种猎人抓住了他。他们折磨他，让他告诉他们他所知道的关于重生的一切，但他没有告诉他们太多。当托马斯所在的猎人基地被超级变种人抓获时，他们再也帮不了他了。他死了。}
#{1650}{}{After he disappeared, some really nasty rumors started to surface, but I knew something must've happened to him. He'd never betray us, I knew him well from our time in the vault, he was a good man. He helped me overcome the loss of my wife and daughter. But why did he leave?}
{1650}{}{他失踪后，一些非常恶劣的谣言开始浮出水面，但我知道他一定出了什么事。他从不背叛我们，从我们在金库的时候起我就很了解他，他是个好人。他帮助我克服了失去妻子和女儿的痛苦。但他为什么要离开？}
#{1651}{}{As I said, he found out that the machine never worked properly, so he went looking for me.}
{1651}{}{正如我所说，他发现机器一直不能正常工作，所以他去找我。}
#{1700}{}{In that case, you must be the Thirteenth! I find it hard to believe, especially coming from a traitor.}
{1700}{}{那样的话，你一定是第十三个了！我很难相信，尤其是来自一个叛徒。}
#{1701}{}{He was able to find and recover some files with the data about the machine and that's how he found the truth!}
{1701}{}{他能够找到和恢复一些文件与数据有关的机器，这就是他如何找到真相！}
#{1702}{}{You still believe Thomas after everything that you must've heard about him. They surely connected him to me and to the Hunters. He was marked as a traitor, just like me, because it was convenient.}
{1702}{}{你一定听说过托马斯的事，但你还是相信他。他们肯定把他和我和猎人联系起来了。他被标记为叛徒，就像我一样，因为这很方便。}
#{1750}{}{The recovered files about the machine, that's some kind of local tall tale, one of Erick's assistants came up with it some time ago, but, of course, nothing was confirmed. I don't even know where that man works today. Thomas would never make up something like that, but he could be wrong or you can be lying to me. I'm sorry, I have to report you.}
{1750}{}{找到的关于这台机器的文件，这是当地的一种荒诞说法，埃里克的一个助手不久前提出了，但是，当然，什么都没有得到证实。我甚至不知道那个人今天在哪里工作。托马斯永远不会编造那样的事，但他可能是错的，或者你在骗我。对不起，我得告发你。}
#{1751}{}{Damn!}
{1751}{}{该死！}
#{1800}{}{You're right, you were Thomas' friend and he always trusted you, so I will trust you too. I remember he was always telling me that I really should talk to some soldier or some other person unhampered by the knowledge of our problem. Those people are supposedly overflowing with hope and one can get a feeling that his work here does make sense. [He smiles, slightly.] I've never done that... Forget it. What and how did Thomas find out?}
{1800}{}{你说得对，你是托马斯的朋友，他一直信任你，所以我也会信任你。我记得他总是告诉我，我真的应该和某个士兵或其他人谈谈，不要因为知道我们的问题而受到阻碍。这些人被认为充满希望，人们可以得到一种感觉，他在这里的工作是有意义的。[他微微一笑]我从来没这么做过。。。算了吧。托马斯是怎么发现的？}
#{1801}{}{He found and restored some files with the data about the machine. He found out that it never worked any better, the process of rebirth will never be absolutely successful.}
{1801}{}{他发现并恢复了一些包含机器数据的文件。他发现，它从来没有更好的工作，重生的过程永远不会是绝对成功的。}
#{1850}{}{So the files indeed exist. One of Erick's assistants once spoke about them, but nothing was confirmed. I don't even know where that man works today. But that's terrible, everything what we've ever done was meaningless. So much dead on both sides and it was for nothing. The Savior is responsible, but we're his accomplices. Even if we haven't known that, we're all to blame still...}
{1850}{}{所以这些文件确实存在。埃里克的一个助手曾经谈到过他们，但没有得到证实。我甚至不知道那个人今天在哪里工作。但那太可怕了，我们所做的一切都毫无意义。两边都死了那么多人，都是白费力气。救世主有责任，但我们是他的同谋。即使我们不知道这一点，我们仍然应该受到责备。。。}
#{1851}{}{Try to get over it.}
{1851}{}{试着克服它。}
#{1900}{}{It's hard to accept something like that. The Savior deceived us. Look, we just recently improved our estimate on how much time will pass until the cells decay after the process of rebirth, by conducting tests on the reborn ones. This data indicates that the Savior should be dead already. There is no way he could undergo the process and live until today. He couldn't have been a ghoul, ever, he was always a normal human.}
{1900}{}{很难接受这样的事情。救世主欺骗了我们。看，我们最近通过对再生细胞进行测试，改进了对再生细胞在再生过程中衰变所需时间的估计。这个数据表明救世主应该已经死了。他不可能经历这个过程，活到今天。他不可能是一个僵尸，永远，他总是一个正常的人。}
#{1901}{}{So what are you going to do now?}
{1901}{}{那你现在打算怎么办？}
#{1950}{}{What can I do? Nobody will believe me, Thomas knew that. I can't do anything, now it's on you. I assume that that's the reason you're here. Please, try your best, so more people will die only if necessary. If you activate the self-destruction with an alarm, hopefully most of the people will evacuate themselves. But it would be good to somehow set the prisoners free as well.}
{1950}{}{我能做什么？没人会相信我，托马斯知道的。我什么都做不了，现在全靠你了。我想这就是你来这里的原因。请尽你最大的努力，这样只有在必要的时候才会有更多的人死去。如果你用警报激活自我毁灭，希望大多数人都能自行撤离。不过，以某种方式释放囚犯也是件好事。}
#{1951}{}{How do I activate the self-destruction?}
{1951}{}{如何激活自我毁灭？}
#{2000}{}{Only by using the main computer, which is accessible only through the commander's office, where you'll find none other than the Savior. Maybe, instead of that, you could try to bring the reactor on Blue 6 to a critical state, but count on that level being heavily guarded and the reactor having substantial security measures. Take my key from this storeroom, it's not much, but hopefully you'll find something useful there. I'm leaving. I have to make peace with myself, I'm weighed down with guilt. Goodbye, Thirteenth... The last reborn.}
{2000}{}{只有使用主计算机，这是只能通过指挥官的办公室，在那里你会发现没有其他人比救世主。或许，你可以试着把蓝6号上的反应堆调到临界状态，但要指望那个高度有严密的防护，反应堆有足够的安全措施。从这个储藏室拿我的钥匙，不多，但希望你能在那里找到有用的东西。我要走了。我必须让自己平静下来，我被内疚压得喘不过气来。再见，十三。。。最后的重生。}
#{2001}{}{Goodbye.}
{2001}{}{再见。}
#{2050}{}{Sure, what are you interested in?}
{2050}{}{当然，你对什么感兴趣？}
#{2051}{}{Isn't the Savior the leading researcher?}
{2051}{}{救世主不是研究的领头羊吗？}
#{2052}{}{How is the research going?}
{2052}{}{研究进展如何？}
#{2053}{}{Were you in the group of people that came here first after the Savior?}
{2053}{}{你是在救世主之后第一个来到这里的人吗？}
#{2054}{}{I'm interested if the current reborn know that they'll die as a result of rebirth.}
{2054}{}{我很感兴趣，如果现在的重生者知道他们会因为重生而死去。}
#{2055}{}{What if neither the machine nor the process of rebirth ever worked properly?}
{2055}{}{如果机器和重生的过程都不能正常工作呢？}
#{2056}{}{Actually, nothing, I'm sorry.}
{2056}{}{其实，没什么，对不起。}
#{2100}{}{There's some kind of a local tall tale that some of the files were recovered, one of Erick's assistants came up with it some time ago, but, of course, nothing was confirmed. I don't even know where that man works today.}
{2100}{}{当地流传着这样一个荒诞的传说：一些文件被找到了，埃里克的一个助手不久前提出了，但是，当然，什么都没有得到证实。我甚至不知道那个人今天在哪里工作。}
#{2101}{}{Can you answer a completely different question for me?}
{2101}{}{你能为我回答一个完全不同的问题吗？}
#{2102}{}{Thank you for answers. Goodbye.}
{2102}{}{谢谢你的回答。再见。}
#{2150}{}{Yes?}
{2150}{}{对？}
#{2151}{}{I've got some more questions. May I?}
{2151}{}{我还有一些问题。我可以吗？}
#{2152}{}{I'm sorry, I won't disturb you anymore.}
{2152}{}{对不起，我不会再打扰你了。}
#{2153}{}{Ugh.}
{2153}{}{啊。}
#{2200}{}{I think that you shouldn't be here. I'm sorry, I have to report you.}
{2200}{}{我觉得你不应该在这里。对不起，我得告发你。}
#{2201}{}{Ghe?}
{2201}{}{啊？}
#{2250}{}{Yes?}
{2250}{}{对？}
#{2251}{}{Who are you?}
{2251}{}{你是谁？}
#{2252}{}{Never mind, I'm sorry.}
{2252}{}{没关系，对不起。}
#{2253}{}{Hooga - chaka.}
{2253}{}{呼嘎-查卡。}
#{2300}{}{My name is Geoff, I'm the leading scientist of rebirth research. Are you new here? Surely not as a scientist, I would've been notified about it.}
{2300}{}{我叫杰夫，我是再生研究的领军科学家。你是新来的吗？当然不是作为一个科学家，我会被通知的。}
#{2301}{}{Isn't the Savior the leading researcher?}
{2301}{}{救世主不是研究的领头羊吗？}
#{2302}{}{How is the research going?}
{2302}{}{研究进展如何？}
#{2303}{}{Were you in the group of people that came here first after the Savior?}
{2303}{}{你是在救世主之后第一个来到这里的人吗？}
#{2304}{}{I'm interested if the current reborn know that they'll die as a result of rebirth.}
{2304}{}{我很感兴趣，如果现在的重生者知道他们会因为重生而死去。}
#{2305}{}{Hasn't it ever occurred to you that neither the machine nor the process of rebirth ever worked properly?}
{2305}{}{难道你没有想过，机器和重生的过程都不能正常工作吗？}
#{2306}{}{I'm looking for someone else. I'm sorry that I disturbed you.}
{2306}{}{我在找别人。很抱歉打扰了你。}
#{2350}{}{The Savior is in charge of a lot of stuff and despite of what you might have heard of him, he isn't qualified enough for such research. But, naturally, he's quite interested in our results and he advises us from time to time, when he knows, based on his experience with his own rebirth, that our research efforts would be unavailing. It's such a shame that he doesn't remember much.}
{2350}{}{救世主掌管着很多事情，尽管你可能听说过他，但他不足以胜任这样的研究。但是，很自然地，他对我们的研究结果很感兴趣，他时不时地建议我们，根据他自己重生的经历，当他知道我们的研究努力将是徒劳的时候。真遗憾，他记不太清楚了。}
#{2351}{}{Does he even know what he was doing when he performed the first successful rebirth?}
{2351}{}{他知道他第一次成功重生时在做什么吗？}
#{2352}{}{And how is the research going?}
{2352}{}{研究进展如何？}
#{2353}{}{Can you answer a completely different question for me?}
{2353}{}{你能为我回答一个完全不同的问题吗？}
#{2354}{}{Thank you for answers. Goodbye.}
{2354}{}{谢谢你的回答。再见。}
#{2400}{}{The Savior makes a selection, and if the said person doesn't know about it, we try to hide it from them. It's cruel, but they can live their last days without worries. Unfortunately, the Thirteenth showed us what it can lead to in the opposite case. Until now, four of the reborn were well acquainted with the fact, yet they didn't refuse the process. It's an honor and another way to serve the Rebirth. The annual rebirth incredibly raises morale and what's more, we collect important data about the very process and its consequences. One person a year, what is that against so many who are killed in combat?}
{2400}{}{救世主做了一个选择，如果说的人不知道，我们试图向他们隐瞒。这很残酷，但他们可以过完最后的日子而不担心。不幸的是，第十三条告诉了我们在相反的情况下它会导致什么。直到现在，四个重生的人都很清楚这个事实，但他们并没有拒绝这个过程。这是一种荣誉，也是为重生服务的另一种方式。每年的重生难以置信地鼓舞了士气，更重要的是，我们收集了有关这个过程及其后果的重要数据。一年一个人，对这么多在战斗中牺牲的人是什么？}
#{2401}{}{Where are the living reborn?}
{2401}{}{生命在哪里重生？}
#{2402}{}{Can you answer a completely different question for me?}
{2402}{}{你能为我回答一个完全不同的问题吗？}
#{2403}{}{Thank you for answers. Goodbye.}
{2403}{}{谢谢你的回答。再见。}
#{2450}{}{Normally they work on this level while they're medically fit, then they're moved to sixth, where they receive quality care. They get good care, and with sedatives they die painlessly. Due to the escape of the Thirteenth the Savior ordered us to place the Eleventh and the Twelfth there immediately. The rest of the reborn had already died, except the Savior of course.}
{2450}{}{正常情况下，当他们身体健康时，他们在这个级别工作，然后他们被转移到第六级，在那里他们接受优质护理。他们得到了很好的照顾，在镇静剂的帮助下，他们无痛地死去。因为第十三个逃走了，救主命令我们立即把第十一个和第十二个放在那里。其余的重生者已经死了，当然除了救世主。}
#{2451}{}{How much comfort do they have on the sixth level?}
{2451}{}{他们在第六层有多舒服？}
#{2452}{}{What if neither the machine nor the process of rebirth ever worked properly?}
{2452}{}{如果机器和重生的过程都不能正常工作呢？}
#{2453}{}{Can you answer a completely different question for me?}
{2453}{}{你能为我回答一个完全不同的问题吗？}
#{2454}{}{Thank you for answers. Goodbye.}
{2454}{}{谢谢你的回答。再见。}
#{2500}{}{Excuse me? How did you think of something like that?}
{2500}{}{请原谅我？你怎么会想到那样的事？}
#{2501}{}{If you want to know, Thomas told me that.}
{2501}{}{如果你想知道，托马斯告诉我的。}
#{2502}{}{I'm just asking.}
{2502}{}{我只是问问。}
#{2550}{}{I can answer you that. The Savior is unquestionable evidence of the functionality of the whole process. And the fact that all the data even remotely related to the machine was erased, probably on purpose, indicates that Vault-Tec was protecting a successful invention.}
{2550}{}{我可以回答你。救世主无疑是整个过程功能的证据。事实上，所有的数据，甚至远程相关的机器被删除，可能是故意的，表明金库科技是保护一个成功的发明。}
#{2551}{}{Have you ever found or recovered any of the data?}
{2551}{}{您是否发现或恢复过任何数据？}
#{2552}{}{Can you answer a completely different question for me?}
{2552}{}{你能为我回答一个完全不同的问题吗？}
#{2553}{}{Thank you for answers. Goodbye.}
{2553}{}{谢谢你的回答。再见。}
#{2600}{}{What?! How's he doing, tell me, hurry, what do you know?}
{2600}{}{什么？！他怎么样了，告诉我，快点，你知道什么？}
#{2601}{}{When he left, Mutant Hunters got a hold of him. They tortured him so he would tell them all he knew about the Rebirth, but he didn't tell them much. When the Hunters' base, where Thomas was kept, was captured by the supermutants, they couldn't help him anymore. He's dead.}
{2601}{}{当他离开时，变种猎人抓住了他。他们折磨他，让他告诉他们他所知道的关于重生的一切，但他没有告诉他们太多。当托马斯所在的猎人基地被超级变种人抓获时，他们再也帮不了他了。他死了。}
#{2650}{}{After he disappeared, some really nasty rumors started to surface, but I knew something must've happened to him. He'd never betray us, I knew him well from our time in the vault, he was a good man. He helped me overcome the loss of my wife and daughter. But why did he leave?}
{2650}{}{他失踪后，一些非常恶劣的谣言开始浮出水面，但我知道他一定出了什么事。他从不背叛我们，从我们在金库的时候起我就很了解他，他是个好人。他帮助我克服了失去妻子和女儿的痛苦。但他为什么要离开？}
#{2651}{}{As I said, he found out that the machine never worked properly, so he went looking for me.}
{2651}{}{正如我所说，他发现机器一直不能正常工作，所以他去找我。}
#{2700}{}{In that case, you must be the Thirteenth! I find it hard to believe, especially coming from a traitor.}
{2700}{}{那样的话，你一定是第十三个了！我很难相信，尤其是来自一个叛徒。}
#{2701}{}{He was able to find and recover some files with the data about the machine and that's how he found the truth!}
{2701}{}{他能够找到和恢复一些文件与数据有关的机器，这就是他如何找到真相！}
#{2702}{}{You still believe Thomas after everything that you must've heard about him. They surely connected him to me and to the Hunters. He was marked as a traitor, just like me, because it was convenient.}
{2702}{}{你一定听说过托马斯的事，但你还是相信他。他们肯定把他和我和猎人联系起来了。他被标记为叛徒，就像我一样，因为这很方便。}
#{2750}{}{You're right, you were Thomas' friend and he always trusted you, so I will trust you too. I remember he was always telling me that I really should talk to some soldier or some other person unhampered by the knowledge of our problem. Those people are supposedly overflowing with hope and one can get a feeling that his work here does make sense. [He smiles, slightly.] I've never done that... Forget it. What and how did Thomas find out?}
{2750}{}{你说得对，你是托马斯的朋友，他一直信任你，所以我也会信任你。我记得他总是告诉我，我真的应该和某个士兵或其他人谈谈，不要因为知道我们的问题而受到阻碍。这些人被认为充满希望，人们可以得到一种感觉，他在这里的工作是有意义的。[他微微一笑]我从来没这么做过。。。算了吧。托马斯是怎么发现的？}
#{2751}{}{He found and restored some files with the data about the machine. He found out that it never worked any better, the process of rebirth will never be absolutely successful.}
{2751}{}{他发现并恢复了一些包含机器数据的文件。他发现，它从来没有更好的工作，重生的过程永远不会是绝对成功的。}
#{2800}{}{Only by using the main computer, which is accessible only through the commander's office, where you'll find none other than the Savior. Maybe, instead of that, you could try to bring the reactor on Blue 6 to a critical state, but count on that level being heavily guarded and the reactor having substantial security measures. Take my key from this storeroom, it's not much, but hopefully you'll find something useful there. I'm leaving. I have to make peace with myself, I'm weighed down with guilt. Goodbye, Thirteenth... The last reborn.}
{2800}{}{只有使用主计算机，这是只能通过指挥官的办公室，在那里你会发现没有其他人比救世主。或许，你可以试着把蓝6号上的反应堆调到临界状态，但要指望那个高度有严密的防护，反应堆有足够的安全措施。从这个储藏室拿我的钥匙，不多，但希望你能在那里找到有用的东西。我要走了。我必须让自己平静下来，我被内疚压得喘不过气来。再见，十三。。。最后的重生。}
#{2801}{}{Goodbye.}
{2801}{}{再见。}
#{2850}{}{I think that you shouldn't be here. I'm sorry, I have to report you.}
{2850}{}{我觉得你不应该在这里。对不起，我得告发你。}
#{2851}{}{Ghe?}
{2851}{}{啊？}
#{2900}{}{Yes, I worked there on the main project. How do you know that? Do we know each other?}
{2900}{}{是的，我在那里做主要项目。你怎么知道的？我们认识吗？}
#{2901}{}{We don't. I recently visited the base and saw your holographic recording.}
{2901}{}{我们没有。我最近参观了基地，看到了你的全息记录。}
#{2902}{}{We don't. I recently visited the base and saw your holographic recording.}
{2902}{}{我们没有。我最近参观了基地，看到了你的全息记录。}
#{2950}{}{Do you mean to say that the base is accessible?! After the war I stopped thinking about what was going on there. It didn't seem important, but... Do you know what they were researching there?}
{2950}{}{你的意思是说基地可以接近吗？！战后我不再去想那里发生了什么。看起来并不重要，但是。。。你知道他们在研究什么吗？}
#{2951}{}{Yes. I'm afraid that one of the creatures escaped.}
{2951}{}{对。恐怕其中一个生物逃走了。}
#{3000}{}{Oh my God, it could be anywhere. Laying eggs somewhere, it's offspring spreading out and killing. Damn project, I shouldn't have ever taken part in it, at any cost. No wonder civilization destroyed itself. If it wasn't by using nuclear weapons, it would've inevitably happened some other way.}
{3000}{}{天哪，它可能在任何地方。在某个地方产卵，它的后代会扩散并杀死。该死的项目，我不应该不惜任何代价参与。难怪文明毁灭了自己。如果不是使用核武器，那就不可避免地以其他方式发生了。}
#{3001}{}{What can be done about it? Shouldn't we tell somebody?}
{3001}{}{我们能做些什么？我们不应该告诉别人吗？}
#{3050}{}{No one would believe us and besides, it would be useless. That creature could cross tens or hundreds of miles before settling somewhere. We can only hope that whoever confronts it will be strong enough. [Geoff looks really crushed. You decide that you won't tell him what happened with the other exemplar of the killing creature.]}
{3050}{}{没有人会相信我们，而且，这也没用。这种生物可以穿越几十英里或几百英里，然后在某处定居下来。我们只能希望，无论谁面对它，都会足够强大。[杰夫看起来真的崩溃了。你决定不告诉他另一个杀人犯的例子发生了什么}
#{3051}{}{No one would believe us and besides, it would be useless. That creature could cross tens or hundreds of miles before settling somewhere. We can only hope that whoever confronts it will be strong enough. [Geoff looks really crushed. You decide that you won't tell him what happened with the other exemplar of the killing creature.]}
{3051}{}{没有人会相信我们，而且，这也没用。这种生物可以穿越几十英里或几百英里，然后在某处定居下来。我们只能希望，无论谁面对它，都会足够强大。[杰夫看起来真的崩溃了。你决定不告诉他另一个杀人犯的例子发生了什么}
#{3052}{}{Let's change the subject.}
{3052}{}{我们换个话题吧。}
#{3053}{}{As you wish, goodbye.}
{3053}{}{如你所愿，再见。}
