#{100}{}{You see a glowing one.}
{100}{}{你看到一个发光的。}
#{200}{}{You see a ghoul whose burned body glows.}
{200}{}{你看到一个僵尸，他燃烧的身体发光。}
#{300}{}{Ugh.}
{300}{}{啊。}
#{301}{}{A visitor, here?}
{301}{}{有客人吗？}
#{302}{}{Scott will talk to you.}
{302}{}{斯科特会和你谈谈。}
#{303}{}{My whole body hurts.}
{303}{}{我全身都疼。}
#{304}{}{The reactor is OK.}
{304}{}{反应堆正常。}
#{305}{}{You're just hindering us here.}
{305}{}{你只是在妨碍我们。}
#{306}{}{Don't rush me.}
{306}{}{别催我。}
