#{100}{}{You see a guard.}
{100}{}{你看到一个警卫。}
#{200}{}{You see a guard in power armor.}
{200}{}{你看到一个身穿强力盔甲的卫兵。}
#{300}{}{You may go in.}
{300}{}{你可以进去。}
#{301}{}{You may enter.}
{301}{}{你可以进去。}
#{302}{}{Go already.}
{302}{}{已经走了。}
#{303}{}{Don't stand here for so long.}
{303}{}{别在这儿站这么久。}
#{400}{}{Alarm!}
{400}{}{警报！}
#{500}{}{Identify yourself.}
{500}{}{表明你的身份。}
#{501}{}{New life. [Show him the talisman.]}
{501}{}{新生活。[给他看护身符]}
#{502}{}{New life.}
{502}{}{新生活。}
#{503}{}{I'm here for the first time, I want to join you.}
{503}{}{我是第一次来这里，我想加入你们。}
#{504}{}{I'm }
{504}{}{我是}
#{505}{}{, the Thirteenth Reborn.}
{505}{}{第十三次重生。}
#{506}{}{What is this place?}
{506}{}{这是什么地方？}
#{507}{}{Die, you ugly mutant!}
{507}{}{死吧，你这个丑陋的变种人！}
#{508}{}{Life neeew.}
{508}{}{新生活。}
#{509}{}{Whass dat?}
{509}{}{什么数据？}
#{510}{}{Mutie-yuck!}
{510}{}{真恶心！}
#{550}{}{All right, you can go.}
{550}{}{好吧，你可以走了。}
#{551}{}{What happened here? [Point at the dead bodies.]}
{551}{}{这里发生了什么？[指向尸体。]}
#{552}{}{OK.}
{552}{}{好 啊。}
#{600}{}{And where's your talisman?}
{600}{}{你的护身符呢？}
#{601}{}{I must've lost it.}
{601}{}{我一定是把它弄丢了。}
#{602}{}{I don't have it. The Mutant Hunters ambushed and almost killed me. Luckily they thought I was dead, so they took my stuff and left me to rot in wasteland. If you haven't heard about it yet, they pay rewards for our talismans in Albuquerque.}
{602}{}{我没有。变种猎人伏击了我，差点杀了我。幸运的是他们以为我死了，所以他们拿走了我的东西，让我在荒地里烂掉。如果你还没听说，他们会为我们在阿尔伯克基的护身符支付报酬。}
#{603}{}{I see I can't get through without a fight.}
{603}{}{我看不打一架我是熬不过去的。}
#{650}{}{Every one of us protects their talisman with their own life and you're telling me that you just lost it?! Show me your face.}
{650}{}{我们每个人都用自己的生命来保护他们的护身符，而你却告诉我你刚刚失去了它？！给我看看你的脸。}
#{651}{}{[Show him your face.]}
{651}{}{[让他看看你的脸。]}
#{652}{}{I see I can't get through without a fight.}
{652}{}{我看不打一架我是熬不过去的。}
#{700}{}{I've heard something like that. All right, you can go, you went through a lot, but just make sure to ask for a new talisman.}
{700}{}{我听过类似的话。好吧，你可以去，你经历了很多，但一定要找一个新的护身符。}
#{701}{}{What happened here? [Point at the dead bodies.]}
{701}{}{这里发生了什么？[指向尸体。]}
#{702}{}{Of course.}
{702}{}{当然。}
#{750}{}{What about the normals?}
{750}{}{法线呢？}
#{751}{}{These are captives, I have to take them away.}
{751}{}{这些是俘虏，我必须把他们带走。}
#{752}{}{I see I can't get through without a fight.}
{752}{}{我看不打一架我是熬不过去的。}
#{800}{}{You can't just take them inside like that! I'll call the guards and they'll take them safely, they're not your business anymore.}
{800}{}{你不能就这样把他们带进去！我会打电话给警卫，他们会把他们安全带走，他们不再是你的事了。}
#{801}{}{OK.}
{801}{}{好 啊。}
#{802}{}{I won't let you take them, you filthy ghoul!}
{802}{}{我不会让你拿走的，你这个肮脏的僵尸！}
#{850}{}{What about the normal?}
{850}{}{正常人呢？}
#{851}{}{That's a captive that I have to take away.}
{851}{}{那是我必须带走的俘虏。}
#{852}{}{I see I can't get through without a fight.}
{852}{}{我看不打一架我是熬不过去的。}
#{900}{}{You can't just take a captive inside like that! I'll call the guards and they'll take the captive safely, it's not your business anymore.}
{900}{}{你不能就这样把俘虏关在里面！我会打电话给警卫，他们会把俘虏安全带走，这不关你的事了。}
#{901}{}{OK.}
{901}{}{好 啊。}
#{902}{}{I won't allow you to do that, you filthy ghoul!}
{902}{}{我不允许你这么做，你这个肮脏的僵尸！}
#{950}{}{What about the little normal?}
{950}{}{小普通怎么办？}
#{951}{}{I took him here because he got a huge dose of radiation. He'll either die soon or he'll become a ghoul, in which case he's got the right to be reborn just like every one of us.}
{951}{}{我带他来是因为他受到了大量的辐射。他要么很快就会死，要么变成僵尸，在这种情况下，他有权像我们每个人一样重生。}
#{952}{}{That's a captive that I have to take away.}
{952}{}{那是我必须带走的俘虏。}
#{953}{}{I see I can't get through without a fight.}
{953}{}{我看不打一架我是熬不过去的。}
#{1000}{}{I'm sorry, you can go.}
{1000}{}{对不起，你可以走了。}
#{1001}{}{OK.}
{1001}{}{好 啊。}
#{1050}{}{Welcome. But, before I let you in, I have to see your face.}
{1050}{}{欢迎光临。但是，在我让你进来之前，我得看看你的脸。}
#{1051}{}{[Show him your face.]}
{1051}{}{[让他看看你的脸。]}
#{1052}{}{I see I can't get through without a fight.}
{1052}{}{我看不打一架我是熬不过去的。}
#{1100}{}{Traitor! The Savior ordered us to take you to him if you ever came back and were willing to cooperate. But I won't miss the opportunity to kill you. So I don't think you're cooperating.}
{1100}{}{叛徒！救主命令我们，如果你回来愿意合作，就带你去见他。但我不会错过杀你的机会。所以我不认为你在合作。}
#{1101}{}{You want fight, you got it, fucker!}
{1101}{}{你想打架，你知道的，混蛋！}
#{1150}{}{You don't know that? Show me your face and maybe I'll tell you.}
{1150}{}{你不知道吗？给我看看你的脸，也许我会告诉你。}
#{1151}{}{[Show him your face.]}
{1151}{}{[让他看看你的脸。]}
#{1152}{}{I see I can't get through without a fight.}
{1152}{}{我看不打一架我是熬不过去的。}
#{1200}{}{A normal! Kill... Wait, you're the Thirteenth! Traitor! The Savior ordered us to take you to him if you ever came back and were willing to cooperate. But I won't miss the opportunity to kill you. So I don't think you're cooperating.}
{1200}{}{一个普通人！杀死。。。等等，你是第十三个！叛徒！救主命令我们，如果你回来愿意合作，就带你去见他。但我不会错过杀你的机会。所以我不认为你在合作。}
#{1201}{}{You want fight, you got it, fucker!}
{1201}{}{你想打架，你知道的，混蛋！}
#{1250}{}{I'm sorry. But you haven't showed me your talisman yet!}
{1250}{}{我很抱歉。但你还没给我看你的护身符呢！}
#{1251}{}{I must've lost it.}
{1251}{}{我一定是把它弄丢了。}
#{1252}{}{I don't have it. The Mutant Hunters ambushed and almost killed me. Luckily they thought I was dead, so they took my stuff and left me to rot in wasteland. If you haven't heard about it yet, they pay rewards for our talismans in Albuquerque.}
{1252}{}{我没有。变种猎人伏击了我，差点杀了我。幸运的是他们以为我死了，所以他们拿走了我的东西，让我在荒地里烂掉。如果你还没听说，他们会为我们在阿尔伯克基的护身符支付报酬。}
#{1253}{}{I see I can't get through without a fight.}
{1253}{}{我看不打一架我是熬不过去的。}
#{1300}{}{Identify yourself.}
{1300}{}{表明你的身份。}
#{1301}{}{New life. [Show him the talisman.]}
{1301}{}{新生活。[给他看护身符]}
#{1302}{}{New life.}
{1302}{}{新生活。}
#{1303}{}{I'm here for the first time, I want to join you.}
{1303}{}{我是第一次来这里，我想加入你们。}
#{1304}{}{I'm }
{1304}{}{我是}
#{1305}{}{, the Thirteenth Reborn.}
{1305}{}{第十三次重生。}
#{1306}{}{What is this place?}
{1306}{}{这是什么地方？}
#{1307}{}{Die, you ugly mutant!}
{1307}{}{死吧，你这个丑陋的变种人！}
#{1308}{}{Life neeew.}
{1308}{}{新生活。}
#{1309}{}{Whass dat?}
{1309}{}{什么数据？}
#{1310}{}{Mutie-yuck!}
{1310}{}{真恶心！}
#{1350}{}{And where's your talisman?}
{1350}{}{你的护身符呢？}
#{1351}{}{I must've lost it.}
{1351}{}{我一定是把它弄丢了。}
#{1352}{}{I don't have it. The Mutant Hunters ambushed and almost killed me. Luckily they thought I was dead, so they took my stuff and left me to rot in wasteland. If you haven't heard about it yet, they pay rewards for our talismans in Albuquerque.}
{1352}{}{我没有。变种猎人伏击了我，差点杀了我。幸运的是他们以为我死了，所以他们拿走了我的东西，让我在荒地里烂掉。如果你还没听说，他们会为我们在阿尔伯克基的护身符支付报酬。}
#{1353}{}{I see I can't get through without a fight.}
{1353}{}{我看不打一架我是熬不过去的。}
#{1400}{}{Every one of us protects their talisman with their own life and you're telling me that you just lost it?! Show me your face.}
{1400}{}{我们每个人都用自己的生命来保护他们的护身符，而你却告诉我你刚刚失去了它？！给我看看你的脸。}
#{1401}{}{[Show him your face.]}
{1401}{}{[让他看看你的脸。]}
#{1402}{}{I see I can't get through without a fight.}
{1402}{}{我看不打一架我是熬不过去的。}
#{1450}{}{I've heard something like that. All right, you can go, you went through a lot, but just make sure to ask for a new talisman.}
{1450}{}{我听过类似的话。好吧，你可以去，你经历了很多，但一定要找一个新的护身符。}
#{1451}{}{What happened here? [Point at the dead bodies.]}
{1451}{}{这里发生了什么？[指向尸体。]}
#{1452}{}{Of course.}
{1452}{}{当然。}
#{1500}{}{What about the little normal?}
{1500}{}{小普通怎么办？}
#{1501}{}{I took him here because he got a huge dose of radiation. He'll either die soon or he'll become a ghoul, in which case he's got the right to be reborn just like every one of us.}
{1501}{}{我带他来是因为他受到了大量的辐射。他要么很快就会死，要么变成僵尸，在这种情况下，他有权像我们每个人一样重生。}
#{1502}{}{That's a captive that I have to take away.}
{1502}{}{那是我必须带走的俘虏。}
#{1503}{}{I see I can't get through without a fight.}
{1503}{}{我看不打一架我是熬不过去的。}
#{1550}{}{Welcome. But, before I let you in, I have to see your face.}
{1550}{}{欢迎光临。但是，在我让你进来之前，我得看看你的脸。}
#{1551}{}{[Show him your face.]}
{1551}{}{[让他看看你的脸。]}
#{1552}{}{I see I can't get through without a fight.}
{1552}{}{我看不打一架我是熬不过去的。}
#{1600}{}{Traitor! The Savior ordered us to take you to him if you ever came back and were willing to cooperate. But I won't miss the opportunity to kill you. So I don't think you're cooperating.}
{1600}{}{叛徒！救主命令我们，如果你回来愿意合作，就带你去见他。但我不会错过杀你的机会。所以我不认为你在合作。}
#{1601}{}{You want fight, you got it, fucker!}
{1601}{}{你想打架，你知道的，混蛋！}
#{1650}{}{You don't know that? Show me your face and maybe I'll tell you.}
{1650}{}{你不知道吗？给我看看你的脸，也许我会告诉你。}
#{1651}{}{[Show him your face.]}
{1651}{}{[让他看看你的脸。]}
#{1652}{}{I see I can't get through without a fight.}
{1652}{}{我看不打一架我是熬不过去的。}
#{1700}{}{A normal! Kill... Wait, you're the Thirteenth! Traitor! The Savior ordered us to take you to him if you ever came back and were willing to cooperate. But I won't miss the opportunity to kill you. So I don't think you're cooperating.}
{1700}{}{一个普通人！杀死。。。等等，你是第十三个！叛徒！救主命令我们，如果你回来愿意合作，就带你去见他。但我不会错过杀你的机会。所以我不认为你在合作。}
#{1701}{}{You want fight, you got it, fucker!}
{1701}{}{你想打架，你知道的，混蛋！}
#{1750}{}{I'm sorry. But you haven't showed me your talisman yet!}
{1750}{}{我很抱歉。但你还没给我看你的护身符呢！}
#{1751}{}{I must've lost it.}
{1751}{}{我一定是把它弄丢了。}
#{1752}{}{I don't have it. The Mutant Hunters ambushed and almost killed me. Luckily they thought I was dead, so they took my stuff and left me to rot in wasteland. If you haven't heard about it yet, they pay rewards for our talismans in Albuquerque.}
{1752}{}{我没有。变种猎人伏击了我，差点杀了我。幸运的是他们以为我死了，所以他们拿走了我的东西，让我在荒地里烂掉。如果你还没听说，他们会为我们在阿尔伯克基的护身符支付报酬。}
#{1753}{}{I see I can't get through without a fight.}
{1753}{}{我看不打一架我是熬不过去的。}
#{1800}{}{What?!}
{1800}{}{什么？！}
#{1801}{}{Eh... Neeew life!}
{1801}{}{呃。。。新生活！}
#{1802}{}{Me make you dead.}
{1802}{}{我让你死。}
#{1850}{}{OK, it seems like you know the password. And where's your talisman?}
{1850}{}{好吧，看来你知道密码了。你的护身符呢？}
#{1851}{}{Shiny, here! [Show him the talisman.]}
{1851}{}{闪亮，这里！[给他看护身符]}
#{1852}{}{Heh?}
{1852}{}{嘿？}
#{1853}{}{Me make you dead.}
{1853}{}{我让你死。}
#{1900}{}{All right, you can go.}
{1900}{}{好吧，你可以走了。}
#{1901}{}{Heh.}
{1901}{}{嘿。}
#{1950}{}{Look, idiot, I don't know who told you the password, but you obviously have no business here. Show me your face.}
{1950}{}{听着，白痴，我不知道是谁告诉你密码的，但你显然没什么事。给我看看你的脸。}
#{1951}{}{[Show him your face.]}
{1951}{}{[让他看看你的脸。]}
#{1952}{}{Me make you dead.}
{1952}{}{我让你死。}
#{2000}{}{A normal! Kill... Wait, you're the Thirteenth! Traitor! The Savior ordered us to take you to him if you ever came back and were willing to cooperate. But I won't miss the opportunity to kill you. So I don't think you're cooperating.}
{2000}{}{一个普通人！杀死。。。等等，你是第十三个！叛徒！救主命令我们，如果你回来愿意合作，就带你去见他。但我不会错过杀你的机会。所以我不认为你在合作。}
#{2001}{}{Me make you dead.}
{2001}{}{我让你死。}
#{2050}{}{You don't even know what you're doing here? Show me your face.}
{2050}{}{你甚至不知道你在这里做什么？给我看看你的脸。}
#{2051}{}{[Show him your face.]}
{2051}{}{[让他看看你的脸。]}
#{2052}{}{Me make you dead.}
{2052}{}{我让你死。}
#{2100}{}{Look, idiot, I don't know who told you the password, but you obviously have no business here. Show me your face.}
{2100}{}{听着，白痴，我不知道是谁告诉你密码的，但你显然没什么事。给我看看你的脸。}
#{2101}{}{[Show him your face.]}
{2101}{}{[让他看看你的脸。]}
#{2102}{}{Me make you dead.}
{2102}{}{我让你死。}
#{2150}{}{A normal! Kill... Wait, you're the Thirteenth! Traitor! The Savior ordered us to take you to him if you ever came back and were willing to cooperate. But I won't miss the opportunity to kill you. So I don't think you're cooperating.}
{2150}{}{一个普通人！杀死。。。等等，你是第十三个！叛徒！救主命令我们，如果你回来愿意合作，就带你去见他。但我不会错过杀你的机会。所以我不认为你在合作。}
#{2151}{}{Me make you dead.}
{2151}{}{我让你死。}
#{2200}{}{A group of Mutant Hunters attacked us. I hope they found us only by accident. We got them all, so they won't reveal our location to anybody.}
{2200}{}{一群变种猎人袭击了我们。我希望他们只是偶然找到我们。我们都拿到了，所以他们不会向任何人透露我们的位置。}
#{2201}{}{I see that the Rebirth is still safe.}
{2201}{}{我看到重生仍然是安全的。}
