#{100}{}{You see a female ghoul.}
{100}{}{你看到一个女僵尸。}
#{150}{}{You see Jess.}
{150}{}{你看到杰斯了。}
#{200}{}{You see a female ghoul in a robe, she's a doctor, without a doubt.}
{200}{}{你看到一个穿着长袍的女僵尸，她无疑是个医生。}
#{250}{}{You see Jess, the head doctor of the infirmary.}
{250}{}{你看，杰西，医务室的主任医生。}
#{300}{}{Give him adrenalin.}
{300}{}{给他肾上腺素。}
#{301}{}{He needs another ultra stimpak.}
{301}{}{他需要另一个超刺激剂。}
#{302}{}{The next couple of hours will be critical.}
{302}{}{接下来的几个小时很关键。}
#{303}{}{It'll be necessary to open him up again.}
{303}{}{有必要再让他开口。}
#{304}{}{The patient is stabilized.}
{304}{}{病人情况稳定了。}
#{305}{}{He needs to rest in bed.}
{305}{}{他需要在床上休息。}
#{306}{}{Just a couple more days and he can go back to combat.}
{306}{}{再过几天他就可以回去战斗了。}
#{307}{}{Let's hope he won't suffer a relapse.}
{307}{}{希望他不会复发。}
#{308}{}{Give him the medications every four hours.}
{308}{}{每四小时给他一次药。}
#{500}{}{What's your problem?}
{500}{}{你怎么回事啊？}
#{501}{}{Problem?}
{501}{}{有问题吗？}
#{502}{}{None.}
{502}{}{没有。}
#{503}{}{Ugh?}
{503}{}{呃？}
#{550}{}{Ah, a newbie, what else. I'm Jess, I'm a doctor and I'm the head of this infirmary, so excuse me if I pay more attention to the patients in need than to you.}
{550}{}{啊，一个新手，还有什么。我是杰西，我是一名医生，我是这个医务室的负责人，所以如果我对需要帮助的病人比你更关心的话，请原谅。}
#{551}{}{A doctor? Great, I need treatment.}
{551}{}{医生？太好了，我需要治疗。}
#{553}{}{Can I get some medical supplies here?}
{553}{}{我能在这里买些医疗用品吗？}
#{554}{}{Do you usually have a lot of wounded here?}
{554}{}{你这里经常有很多伤员吗？}
#{555}{}{OK, I won't disturb you.}
{555}{}{好吧，我不会打扰你的。}
#{600}{}{Sure, but you need to take off your clothes, so I can take a look at you.}
{600}{}{当然可以，但是你得脱掉衣服，这样我才能看看你。}
#{601}{}{OK.}
{601}{}{好 啊。}
#{602}{}{Actually, my wounds aren't that serious, they'll heal themselves.}
{602}{}{实际上，我的伤口没那么严重，它们会自己愈合的。}
#{650}{}{What the... the Thirteenth! The guards must've been sleeping on the job if you could get in here. [She turns on the alarm.]}
{650}{}{怎么了。。。十三号！如果你能进来的话，警卫肯定是在工作时睡着了。[她打开闹钟。]}
#{651}{}{That was the last mistake of your life.}
{651}{}{那是你生命中最后一个错误。}
#{700}{}{What the... the Thirteenth! The guards must've been sleeping on the job if you could get in here. [She turns on the alarm.]}
{700}{}{怎么了。。。十三号！如果你能进来的话，警卫肯定是在工作时睡着了。[她打开闹钟。]}
#{701}{}{That was the last mistake of your life.}
{701}{}{那是你生命中最后一个错误。}
#{750}{}{You may find it funny, but I don't have time for this "funny" stuff. Next time ask me for treatment only if you really need it.}
{750}{}{你可能会觉得很好笑，但我没时间说这些“好笑”的东西。下次只要你真的需要就请我治疗。}
#{752}{}{Can I at least get some medical supplies?}
{752}{}{我至少能弄点医疗用品吗？}
#{753}{}{Do you usually have a lot of wounded here?}
{753}{}{你这里经常有很多伤员吗？}
#{754}{}{Sorry.}
{754}{}{对不起的。}
#{850}{}{What do you think? That I just give away stimpaks to anyone who asks? Everybody gets as much supplies - and this doesn't only apply to medical ones - as they need, from Dave on Yellow 3. Don't ask me, who's in charge of that, because I don't know it.}
{850}{}{你怎么认为？我把Stimpak送给任何人？每个人都能从黄色3的戴夫那里得到他们所需要的东西——这不仅仅适用于医疗用品。别问我，谁负责，因为我不知道。}
#{851}{}{Is it just me or do you feel that you don't get enough supplies?}
{851}{}{只是我还是你觉得你没有足够的补给？}
#{852}{}{So, can you treat me?}
{852}{}{那么，你能请我吗？}
#{854}{}{Do you usually have a lot of wounded here?}
{854}{}{你这里经常有很多伤员吗？}
#{855}{}{I see, thanks for the advice.}
{855}{}{我明白了，谢谢你的建议。}
#{900}{}{Fortunately, we've got enough medical supplies, nobody would leave our wounded soldiers without treatment. But they could allocate them to me in greater quantities at a time, so I don't have to run to the third level so often. The next batch of supplies is waiting there for me and I surely won't have time to go and get them for a while.}
{900}{}{幸运的是，我们有足够的医疗用品，没有人会让我们受伤的士兵得不到治疗。但是他们可以一次分配给我更多的数量，所以我不必经常跑到第三级。下一批物资在那里等着我，我肯定有一段时间没有时间去拿。}
#{901}{}{A doctor? Great, I need treatment.}
{901}{}{医生？太好了，我需要治疗。}
#{903}{}{Do you usually have a lot of wounded here?}
{903}{}{你这里经常有很多伤员吗？}
#{904}{}{I won't disturb you anymore then.}
{904}{}{那我就不打扰你了。}
#{950}{}{Of course, those people here aren't doctors bumming around, they are wounded. I can't catch a break, even for a while. The infirmary is full, I have to store some patients in the rooms on this floor.}
{950}{}{当然，这里的那些人不是医生，他们受伤了。我不能休息，哪怕是一段时间。医务室已经满了，我得把一些病人放在这层的房间里。}
#{951}{}{What do you treat here generally?}
{951}{}{你在这里一般治疗什么？}
#{952}{}{I know, I spoke with Darrell.}
{952}{}{我知道，我和达雷尔谈过。}
#{953}{}{I know, I spoke with Darrell.}
{953}{}{我知道，我和达雷尔谈过。}
#{954}{}{I'm interested in the medical examinations of reborn ones.}
{954}{}{我对重生者的体检很感兴趣。}
#{955}{}{How do you, a doctor, cope with all that goes on around here? To kill ones so others might live.}
{955}{}{你，一个医生，怎么应付这一切？为了让别人活着而杀人。}
#{956}{}{I need something from you.}
{956}{}{我需要你的东西。}
#{957}{}{Sorry that I asked. Goodbye.}
{957}{}{抱歉我问了。再见。}
#{1000}{}{Whatever you can think of. Newbies often carry some exotic illness. Contagious, of course. And we've got all kinds of wounds here. Soldiers fight not only normals, but all kinds of beasts that want to eat them for dinner as well.}
{1000}{}{不管你能想到什么。新手经常携带一些异国的疾病。当然会传染的。我们这里有各种各样的伤口。士兵们不仅与普通人作战，还与各种想把它们当晚餐吃的野兽作战。}
#{1001}{}{Yeah, I spoke with Darrell.}
{1001}{}{是的，我和达雷尔谈过。}
#{1002}{}{Yeah, I spoke with Darrell.}
{1002}{}{是的，我和达雷尔谈过。}
#{1003}{}{I'm interested in the medical examinations of reborn ones.}
{1003}{}{我对重生者的体检很感兴趣。}
#{1004}{}{How do you, a doctor, cope with all that goes on around here? To kill ones so others might live.}
{1004}{}{你，一个医生，怎么应付这一切？为了让别人活着而杀人。}
#{1005}{}{I need something from you.}
{1005}{}{我需要你的东西。}
#{1006}{}{Thanks for answers, take care.}
{1006}{}{谢谢你的回答，保重。}
#{1050}{}{He should be resting, undisturbed, dammit. It's more than enough that bonehead would love to go straight back to combat. He just doesn't realize that in his current state one wrong move or badly timed jump, and some wound could open up, which could cost him his life in combat.}
{1050}{}{他应该休息，不受干扰，该死的。白痴愿意直接回去战斗已经足够了。他只是没有意识到，在他目前的状态下，一个错误的举动或错误的时机跳跃，一些伤口可能会打开，这可能会导致他的生命在战斗中。}
#{1051}{}{What do you treat here generally?}
{1051}{}{你在这里一般治疗什么？}
#{1052}{}{I'm interested in the medical examinations of reborn ones.}
{1052}{}{我对重生者的体检很感兴趣。}
#{1053}{}{How do you, a doctor, cope with all that goes on around here? To kill ones so others might live.}
{1053}{}{你，一个医生，怎么应付这一切？为了让别人活着而杀人。}
#{1054}{}{I need something from you.}
{1054}{}{我需要你的东西。}
#{1055}{}{Thanks for answers, take care.}
{1055}{}{谢谢你的回答，保重。}
#{1100}{}{Who isn't? But the scientists on the red levels are the ones who take care of that. I don't have access to their examination files, let alone to examine them myself.}
{1100}{}{谁不是？但是红层的科学家们才是解决这个问题的人。我没有权限查看他们的考试档案，更不用说亲自检查了。}
#{1101}{}{So, if there was something wrong with them, you wouldn't know.}
{1101}{}{所以，如果他们有什么问题，你不会知道的。}
#{1102}{}{What do you treat here generally?}
{1102}{}{你在这里一般治疗什么？}
#{1103}{}{I spoke with Darrell, can't you release him already?}
{1103}{}{我和达雷尔谈过了，你不能放了他吗？}
#{1104}{}{I spoke with Darrell, can't you release him already?}
{1104}{}{我和达雷尔谈过了，你不能放了他吗？}
#{1105}{}{How do you, a doctor, cope with all that goes on around here? To kill ones so others might live.}
{1105}{}{你，一个医生，怎么应付这一切？为了让别人活着而杀人。}
#{1106}{}{I need something from you.}
{1106}{}{我需要你的东西。}
#{1107}{}{Thanks for answers, take care.}
{1107}{}{谢谢你的回答，保重。}
#{1150}{}{What should be wrong with them? If there were some problems, they would without a doubt tell us. But the reborn ones are under strong protection and control. And even that wasn't enough, as was shown to us by the Thirteenth.}
{1150}{}{他们怎么了？如果有什么问题，他们肯定会告诉我们的。但重生的人受到强有力的保护和控制。即使是这样也不够，正如十三世纪时我们所看到的那样。}
#{1151}{}{The machine doesn't work properly and they can easily keep that in secret this way!}
{1151}{}{这台机器不能正常工作，他们可以很容易地用这种方式保密！}
#{1152}{}{What do you treat here generally?}
{1152}{}{你在这里一般治疗什么？}
#{1153}{}{I spoke with Darrell, can't you release him already?}
{1153}{}{我和达雷尔谈过了，你不能放了他吗？}
#{1154}{}{I spoke with Darrell, can't you release him already?}
{1154}{}{我和达雷尔谈过了，你不能放了他吗？}
#{1155}{}{How do you, a doctor, cope with all that goes on around here? To kill ones so others might live.}
{1155}{}{你，一个医生，怎么应付这一切？为了让别人活着而杀人。}
#{1156}{}{I need something from you.}
{1156}{}{我需要你的东西。}
#{1157}{}{Thanks for answers, take care.}
{1157}{}{谢谢你的回答，保重。}
#{1200}{}{That's utter nonsense. It seems you need treatment. I'll give you something to soothe you, just take this off. [She's about to uncover your head.]}
{1200}{}{那完全是胡说八道。看来你需要治疗。我给你点安慰的，把这个脱了。[她就要揭开你的头了。]}
#{1201}{}{[Let her.]}
{1201}{}{[让她来。]}
#{1202}{}{I won't let you touch me. I'd rather kill you!}
{1202}{}{我不会让你碰我的。我宁愿杀了你！}
#{1250}{}{What should be wrong with them? If there were some problems, they would without a doubt tell us. But the reborn ones are under strong protection and control. And even that wasn't enough, as was shown to us by the Thirteenth.}
{1250}{}{他们怎么了？如果有什么问题，他们肯定会告诉我们的。但重生的人受到强有力的保护和控制。即使是这样也不够，正如十三世纪时我们所看到的那样。}
#{1251}{}{The machine doesn't work properly and they can easily keep that in secret this way!}
{1251}{}{这台机器不能正常工作，他们可以很容易地用这种方式保密！}
#{1252}{}{What do you treat here generally?}
{1252}{}{你在这里一般治疗什么？}
#{1253}{}{I spoke with Darrell, can't you release him already?}
{1253}{}{我和达雷尔谈过了，你不能放了他吗？}
#{1254}{}{I spoke with Darrell, can't you release him already?}
{1254}{}{我和达雷尔谈过了，你不能放了他吗？}
#{1255}{}{How do you, a doctor, cope with all that goes on around here? To kill ones so others might live.}
{1255}{}{你，一个医生，怎么应付这一切？为了让别人活着而杀人。}
#{1256}{}{I need something from you.}
{1256}{}{我需要你的东西。}
#{1257}{}{Thanks for answers, take care.}
{1257}{}{谢谢你的回答，保重。}
#{1300}{}{Every normal lives at the expense of some ghoul, we're just turning it around. Am I glad that normals must die? No. But I certainly don't feel sorry for them.}
{1300}{}{每一个正常人的生活都是以僵尸为代价的，我们只是在扭转局面。我很高兴正常人都死了吗？不。但我当然不为他们感到难过。}
#{1301}{}{How do you mean that?}
{1301}{}{你什么意思？}
#{1302}{}{What do you treat here generally?}
{1302}{}{你在这里一般治疗什么？}
#{1303}{}{I spoke with Darrell, can't you release him already?}
{1303}{}{我和达雷尔谈过了，你不能放了他吗？}
#{1304}{}{I spoke with Darrell, can't you release him already?}
{1304}{}{我和达雷尔谈过了，你不能放了他吗？}
#{1305}{}{I'm interested in the medical examinations of reborn ones.}
{1305}{}{我对重生者的体检很感兴趣。}
#{1306}{}{I need something from you.}
{1306}{}{我需要你的东西。}
#{1307}{}{Thanks for answers, take care.}
{1307}{}{谢谢你的回答，保重。}
#{1350}{}{Some of those that didn't die had to become ghouls so others could live happily. Some lived in a badly constructed vault, while others lived in a vault where there was enough money during its construction. A lot of people turned to ghouls, when they had to explore irradiated locations for the good of the whole community. Others had to leave their living space for normals who were strong enough to expel them. And I could go on like this forever. All these bigheads from Vault 16 live happily only thanks to the fact that the Hunters are killing everybody who's a little bit different for them.}
{1350}{}{一些没死的人必须变成僵尸，这样其他人才能快乐地生活。一些人住在一个建造得很糟糕的金库里，而另一些人住在一个金库里，那里在建造过程中有足够的钱。为了整个社区的利益，很多人不得不探索受辐射的地点，于是他们转向了僵尸。另一些人不得不离开他们的生活空间给那些强壮到足以驱逐他们的正常人。我可以一直这样下去。所有这些16号地下室的大头怪都过着幸福的生活，这要归功于猎人们杀死了每一个对他们来说有点不同的人。}
#{1351}{}{Why do I have a feeling that you've got personal experience with it? How did you become a ghoul?}
{1351}{}{为什么我觉得你有亲身经历？你是怎么变成僵尸的？}
#{1352}{}{What do you treat here generally?}
{1352}{}{你在这里一般治疗什么？}
#{1353}{}{I spoke with Darrell, can't you release him already?}
{1353}{}{我和达雷尔谈过了，你不能放了他吗？}
#{1354}{}{I spoke with Darrell, can't you release him already?}
{1354}{}{我和达雷尔谈过了，你不能放了他吗？}
#{1355}{}{I'm interested in the medical examinations of reborn ones.}
{1355}{}{我对重生者的体检很感兴趣。}
#{1356}{}{I need something from you.}
{1356}{}{我需要你的东西。}
#{1357}{}{Thanks for answers, take care.}
{1357}{}{谢谢你的回答，保重。}
#{1400}{}{That's none of your business. I don't want to talk about it.}
{1400}{}{那不关你的事。我不想谈这个。}
#{1401}{}{Please, I'm trying to understand it all and accept it. Maybe your story could help me with it.}
{1401}{}{求你了，我试着理解它并接受它。也许你的故事能帮我。}
#{1402}{}{As you wish.}
{1402}{}{如你所愿。}
#{1450}{}{If it would truly help you. OK then, here you go. I was born in Vault 16 and became a doctor there. That's right, in that Vault under Albuquerque. They started to talk about populating the surface, so parties were send to explore the nearby and distant surroundings. I was a part of one of them.}
{1450}{}{如果它真的能帮到你。好吧，给你。我出生在16号地下室，在那里当了医生。没错，在阿尔伯克基的地下室里。他们开始讨论如何在地表上定居，于是派了一些人去探索附近和远处的环境。我是其中一员。}
#{1451}{}{What happened?}
{1451}{}{怎么搞的？}
#{1500}{}{We were set to explore an irradiated location. Of course we took Rad-X prior to that, but at one point we got attacked by geckos. I saw how a couple of them knocked down a man and started to feast on him, and in a moment I myself was lying down, feeling claws and teeth all over me. Then there were gunshots. Before I completely lost consciousness I saw the rest of our party running, while constantly shooting, and all of the geckos chasing them.}
{1500}{}{我们准备去探索一个受辐射的地方。当然在那之前我们用了Rad-X，但有一次我们被壁虎袭击了。我看到有几个人把一个男人打倒，开始大吃大喝，不一会儿我自己也躺了下来，感觉爪子和牙齿都在我身上。然后是枪声。在我完全失去知觉之前，我看到我们队的其他人在奔跑，不停地射击，所有的壁虎都在追赶他们。}
#{1501}{}{Are you mad at them for letting you behind?}
{1501}{}{你生他们让你落后的气了吗？}
#{1550}{}{Not because of that. They were in danger and they thought that I was dead, they couldn't act differently. When I woke up, I was glad that I wasn't being eaten by any animal, but it was immediately clear to me that the effect of Rad-X had worn off a long time ago and I was getting huge doses of radiation. Sadly I was wounded in such a way that I wasn't able to move from that place. I was trying to heal myself and ate whatever little I had with me. I don't know how long it took, it could be two weeks, or it could be four. But I already started to notice changes that radiation caused to me.}
{1550}{}{不是因为这个。他们处于危险之中，他们认为我已经死了，他们不能采取不同的行动。当我醒来的时候，我很高兴我没有被任何动物吃掉，但我立刻清楚地意识到Rad-X的作用在很久以前就消失了，我受到了巨大剂量的辐射。可悲的是，我受了伤，无法离开那个地方。我试着治愈自己，吃了我身上的所有东西。我不知道花了多长时间，可能是两个星期，也可能是四个星期。但我已经开始注意到辐射给我带来的变化。}
#{1551}{}{What happened next?}
{1551}{}{接下来发生了什么？}
#{1600}{}{When I finally gathered enough strength, after a few days I crawled to the Vault door... And they didn't let me in! For the safety of the Vault, supposedly, they couldn't risk radiation. Not only did they turn me down, they expelled me, after everything I'd done for the Vault!}
{1600}{}{当我终于有了足够的力量，过了几天我爬到了金库的门前。。。他们不让我进去！为了保险库的安全，他们不能冒辐射的危险。他们不仅拒绝了我，还开除了我，在我为金库所做的一切之后！}
#{1601}{}{They couldn't act in another way.}
{1601}{}{他们不能以另一种方式行事。}
#{1650}{}{They could've at least tried! Or helped me somehow! But those hypocrites didn't even think about it. The only thing I saw was the closed door to the Vault, and when I had been standing there for quite some time, they told me via the intercom that if the next group coming out of Vault saw me there, they'd shoot me. I once saved the life of the guy who was telling me that! So there you go, I'm a ghoul and I'm here because the inhabitants of Vault 16 didn't want to risk their pure lives. Think about it, I've got to work.}
{1650}{}{他们至少可以试一下！或者帮助我！但那些伪君子根本没想过。我唯一看到的是金库的大门紧闭，当我站在那里很长一段时间后，他们通过对讲机告诉我，如果下一批从金库出来的人看到我在那里，他们会开枪打死我。有一次我救了那个告诉我的人的命！好了，我是一个僵尸，我在这里是因为16号地下室的居民不想冒生命危险。想想看，我得工作了。}
#{1651}{}{[Let her work.]}
{1651}{}{[让她工作。]}
#{1700}{}{If it's about treatment, that's why I'm here. If it's about something else, you can shove it up your... you know where.}
{1700}{}{如果是为了治疗，那就是我来这里的原因。如果是关于别的事，你可以把它塞进你的。。。你知道在哪里。}
#{1701}{}{A doctor? Great, I need treatment.}
{1701}{}{医生？太好了，我需要治疗。}
#{1703}{}{Can I get some medical supplies here?}
{1703}{}{我能在这里买些医疗用品吗？}
#{1704}{}{I've got a couple of short questions.}
{1704}{}{我有几个简短的问题。}
#{1705}{}{OK, I won't disturb you.}
{1705}{}{好吧，我不会打扰你的。}
#{1750}{}{If you won't mind that I'll be taking care of patients that need me, unlike you. You may ask and I might give you answers.}
{1750}{}{如果你不介意的话，我会照顾那些需要我的病人，不像你。你可以问，我可以给你答案。}
#{1751}{}{What do you treat here generally?}
{1751}{}{你在这里一般治疗什么？}
#{1752}{}{I spoke with Darrell.}
{1752}{}{我和达雷尔谈过了。}
#{1753}{}{I spoke with Darrell.}
{1753}{}{我和达雷尔谈过了。}
#{1754}{}{I'm interested in the medical examinations of reborn ones.}
{1754}{}{我对重生者的体检很感兴趣。}
#{1755}{}{How do you, a doctor, cope with all that goes on around here? To kill ones so others might live.}
{1755}{}{你，一个医生，怎么应付这一切？为了让别人活着而杀人。}
#{1756}{}{I need something from you.}
{1756}{}{我需要你的东西。}
#{1757}{}{Sorry that I asked. Goodbye.}
{1757}{}{抱歉我问了。再见。}
#{1800}{}{Great, I figured I'd see you again. And I bet that you don't need treatment this time as well.}
{1800}{}{太好了，我想我还会再见到你的。我打赌你这次也不需要治疗。}
#{1801}{}{Well, this time I do.}
{1801}{}{好吧，这次我知道了。}
#{1803}{}{Can I get some medical supplies here?}
{1803}{}{我能在这里买些医疗用品吗？}
#{1804}{}{Do you usually have a lot of wounded here?}
{1804}{}{你这里经常有很多伤员吗？}
#{1805}{}{I've got a couple of short questions.}
{1805}{}{我有几个简短的问题。}
#{1806}{}{I'll stop by again, since you like to see me so much.}
{1806}{}{既然你这么想见我，我就再过来看看。}
#{1850}{}{Yeah, I do.}
{1850}{}{是的，我知道。}
#{1851}{}{What do you treat here generally?}
{1851}{}{你在这里一般治疗什么？}
#{1852}{}{I spoke with Darrell.}
{1852}{}{我和达雷尔谈过了。}
#{1853}{}{I spoke with Darrell.}
{1853}{}{我和达雷尔谈过了。}
#{1854}{}{I'm interested in the medical examinations of reborn ones.}
{1854}{}{我对重生者的体检很感兴趣。}
#{1855}{}{How do you, a doctor, cope with all that goes on around here? To kill ones so others might live.}
{1855}{}{你，一个医生，怎么应付这一切？为了让别人活着而杀人。}
#{1856}{}{I need something from you.}
{1856}{}{我需要你的东西。}
#{1857}{}{Sorry that I asked. Goodbye.}
{1857}{}{抱歉我问了。再见。}
#{1900}{}{Oh look, what a surprise, we've got another mentally challenged one. Easy, don't be afraid of me. Do you need treatment? Are you hurt, do you feel pain?}
{1900}{}{哦，看，真是个惊喜，我们又有一个智障者。别紧张，别怕我。你需要治疗吗？你受伤了吗？你觉得痛吗？}
#{1901}{}{Hooo!}
{1901}{}{呼！}
#{1902}{}{Groohoola.}
{1902}{}{格罗胡拉。}
#{1903}{}{Ugh-bye.}
{1903}{}{啊，再见。}
#{1950}{}{All right, I'll take a look at you. You just need to take this off. [She's about to uncover your head.]}
{1950}{}{好吧，我来看看你。你只要把这个脱下来。[她就要揭开你的头了。]}
#{1951}{}{[Let her.]}
{1951}{}{[让她来。]}
#{1952}{}{Ugh! Grr!}
{1952}{}{啊！格瑞！}
#{2000}{}{What the... the Thirteenth! The guards must've been sleeping on the job if you could get in here. [She turns on the alarm.]}
{2000}{}{怎么了。。。十三号！如果你能进来的话，警卫肯定是在工作时睡着了。[她打开闹钟。]}
#{2001}{}{Graah!}
{2001}{}{格拉！}
#{2050}{}{What the... the Thirteenth! The guards must've been sleeping on the job if you could get in here. [She turns on the alarm.]}
{2050}{}{怎么了。。。十三号！如果你能进来的话，警卫肯定是在工作时睡着了。[她打开闹钟。]}
#{2051}{}{Graah!}
{2051}{}{格拉！}
#{2100}{}{I bet you're trying to say something really smart, but I don't understand you. Listen to me now and try to focus, maybe you'll understand something. There is a small hope that your mental retardation is caused by small mutations and by radiation, so a rebirth could provide a treatment for you. But if you've had this condition since your birth or as a result of some injury, even our machine won't help you. I would have to run some tests to figure out what your condition is, but I don't have time for that.}
{2100}{}{我打赌你想说些很聪明的话，但我不明白你说的。听我说，集中注意力，也许你会明白些什么。有一个小希望，你的智力迟钝是由小突变和辐射引起的，所以重生可以为你提供治疗。但是如果你从出生起就有这种情况，或者是由于某种伤害，即使是我们的机器也帮不了你。我得做些测试来确定你的病情，但我没有时间。}
#{2101}{}{Ugh.}
{2101}{}{啊。}
#{2150}{}{But it doesn't matter. Just keep in mind that even if your condition endures, you will be taken care of. The Rebirth doesn't deny anybody.}
{2150}{}{但这不重要。只要记住，即使你的情况持续下去，你会得到照顾。重生并不否认任何人。}
#{2151}{}{Ugh, boo boo!}
{2151}{}{啊，嘘嘘！}
#{2152}{}{Ugh-bye!}
{2152}{}{啊，再见！}
#{2200}{}{Oh look, what a surprise, we've got another mentally challenged one. Easy, don't be afraid of me. Do you need treatment? Are you hurt, do you feel pain?}
{2200}{}{哦，看，真是个惊喜，我们又有一个智障者。别紧张，别怕我。你需要治疗吗？你受伤了吗？你觉得痛吗？}
#{2201}{}{Hooo!}
{2201}{}{呼！}
#{2202}{}{Groohoola.}
{2202}{}{格罗胡拉。}
#{2203}{}{Ugh-bye.}
{2203}{}{啊，再见。}
#{2250}{}{I really don't want to force you away, but I must tend to my patients and not waste my time with you. And I've still got plenty of wounded here. Unless, well, you need treatment as well.}
{2250}{}{我真的不想强迫你离开，但我必须照顾我的病人，不要浪费时间和你在一起。我这里还有很多伤员。除非你也需要治疗。}
#{2251}{}{Hooo!}
{2251}{}{呼！}
#{2252}{}{Groohoola.}
{2252}{}{格罗胡拉。}
#{2253}{}{Uh-bye.}
{2253}{}{呃，再见。}
