#{100}{}{You see a ghoul.}
{100}{}{你看到一个僵尸。}
#{150}{}{You see Kath.}
{150}{}{你看到凯丝了。}
#{200}{}{You see a ghoul in a robe. It looks like she's bored.}
{200}{}{你看到一个穿着长袍的僵尸。她看起来很无聊。}
#{201}{}{You see a ghoul in a robe.}
{201}{}{你看到一个穿着长袍的僵尸。}
#{250}{}{You see Kath. As usual, she has nothing to do and it doesn't make her happy.}
{250}{}{你看到凯丝了。像往常一样，她无事可做，也不会让她高兴。}
#{251}{}{You see Kath. With the empty expression on her decomposing face it almost looks as though she were dead already.}
{251}{}{你看到凯丝了。她腐烂的脸上空空荡荡的表情，看起来她几乎已经死了。}
#{300}{}{Oh man. Guards!}
{300}{}{哦，伙计。警卫！}
#{500}{}{Hi, what brings you to this almost forgotten room? My name's Kath, if we haven't met before that is.}
{500}{}{嗨，是什么把你带到这个几乎被遗忘的房间来的？我叫凯丝，如果我们以前没见过的话。}
#{501}{}{What is it you do here?}
{501}{}{你在这里干什么？}
#{502}{}{I'm here by mistake.}
{502}{}{我来错了。}
#{503}{}{Kunth?}
{503}{}{昆斯？}
#{550}{}{This machine here makes vault jumpsuits, robes and other resistant clothing. It's fully automated, you just flip a switch and then supervise. That's my job, so I practically do nothing here.}
{550}{}{这台机器在这里制造跳马服，长袍和其他抵抗力的衣服。它是全自动的，你只需扳动开关，然后监督。那是我的工作，所以我几乎什么都不做。}
#{551}{}{Why vault jumpsuits?}
{551}{}{为什么穿跳马服？}
#{552}{}{Could I have a robe?}
{552}{}{能给我一件长袍吗？}
#{553}{}{What kind of research takes place on this floor?}
{553}{}{什么样的研究在这层楼进行？}
#{554}{}{I need to be elsewhere. Bye.}
{554}{}{我要去别处。再见。}
#{600}{}{This complex originally supplied jumpsuits to several of the nearest vaults. That's why it was built here too. But we make jumpsuits only for the reborn, no one else. That makes it one jumpsuit per year, just each time with a different number.}
{600}{}{这个建筑群最初为最近的几个金库提供了连体衣。所以它也建在这里。但我们只为重生而做连身衣，没有其他人。这使得它每年一件连身衣，只是每次都有不同的号码。}
#{601}{}{Why is it the reborn wear those jumpsuits, anyway?}
{601}{}{为什么重生的人会穿连身衣呢？}
#{602}{}{What about when you get to reborn 100? The number won't fit their back anymore.}
{602}{}{当你重生100岁的时候呢？这个号码再也装不下了。}
#{603}{}{I don't think I need to know more about that.}
{603}{}{我想我不需要知道更多。}
#{604}{}{Thanks for the information. Bye.}
{604}{}{谢谢你的消息。再见。}
#{650}{}{It symbolizes a body free from mutations, which is what the vaults were originally for, and it's also a kind of a slap in the face for all the lucky people from functional vaults. The number indicates the order of the reborn. I guess that's obvious. And anyway, if the others clearly see a reborn among them, instead of the reborns wearing robes like everyone else, it gives them more hope. Not that you would see a reborn here or even on floors with a lower clearance other than on security tapes. I don't know who though it up, but it's the same as with that talisman of ours - which is actually just a biohazard sign.}
{650}{}{它象征着一个没有突变的身体，这是拱顶最初的用途，也是对所有功能性拱顶幸运人士的一记耳光。数字表示重生的顺序。我想这是显而易见的。不管怎样，如果其他人清楚地看到他们中间的重生，而不是像其他人一样穿着长袍的重生，这给了他们更多的希望。并不是说你会看到一个重生在这里，甚至在地板上与较低的净空以外的安全磁带。我不知道是谁想出来的，但这和我们的护身符是一样的——实际上这只是一个生物危害的标志。}
#{651}{}{What about when you get to reborn 100? The number won't fit their back anymore.}
{651}{}{当你重生100岁的时候呢？这个号码再也装不下了。}
#{652}{}{I don't think I need to know more about that.}
{652}{}{我想我不需要知道更多。}
#{653}{}{Thanks for the information. Bye.}
{653}{}{谢谢你的消息。再见。}
#{700}{}{Haha, funny. We won't have to wait a hundred years for the day of rebirth for all. I hope.}
{700}{}{哈哈，好笑。我们不必等上百年才等到重生的那一天。希望如此。}
#{701}{}{Why is it the reborn wear those jumpsuits, anyway?}
{701}{}{为什么重生的人会穿连身衣呢？}
#{702}{}{I don't think I need to know more about that.}
{702}{}{我想我不需要知道更多。}
#{703}{}{Thanks for the information. Bye.}
{703}{}{谢谢你的消息。再见。}
#{750}{}{Sure, I've got a regular stockpile here. Here you go, you can make a blanket out of it or whatever. [She gives you a robe.]}
{750}{}{当然，我这里有固定库存。给你，你可以用它做个毯子什么的。[她给了你一件长袍。]}
#{751}{}{Tell me, why do you make vault jumpsuits here, anyway?}
{751}{}{告诉我，你为什么在这里做跳马服？}
#{752}{}{I'd like to know what kind of research takes place on this floor.}
{752}{}{我想知道在这层楼进行什么样的研究。}
#{753}{}{Thanks. Bye.}
{753}{}{谢谢。再见。}
#{800}{}{Apparently they're trying to lower the number of donors needed for a single rebirth. That's about as much as I know. But they never tell me anything, nobody cares about me. I guess one of these days I'll die of boredom here. I tried talking with those normals, but they weren't interested. Which one can understand, given their situation.}
{800}{}{很明显，他们试图减少一次重生所需的捐赠者数量。我就知道这么多。但他们什么都不告诉我，没人关心我。我想总有一天我会在这里无聊死的。我试着和那些正常人交谈，但他们不感兴趣。哪一个能理解，考虑到他们的处境。}
#{801}{}{Why won't anyone tell you anything about the research?}
{801}{}{为什么没人告诉你关于这项研究的事？}
#{802}{}{You really know nothing about the research?}
{802}{}{你真的对研究一无所知？}
#{803}{}{It looks like you can't tell me anything I wouldn't already know.}
{803}{}{看来你不能告诉我任何我还不知道的事情。}
#{804}{}{I don't want you to die of boredom, but I have to go now.}
{804}{}{我不想你无聊死，但我得走了。}
#{850}{}{Really really. I just wonder sometimes if once they only need a few donors thanks to the research, whether there'll be any more left. Many of them tend to die after Richards' tests.}
{850}{}{真的真的。有时我只是在想，一旦他们因为研究而只需要几个捐赠者，是否还会有更多的捐赠者。他们中的许多人往往在理查兹的测试后死亡。}
#{851}{}{Who's Richard?}
{851}{}{理查德是谁？}
#{852}{}{That would indeed be a shame.}
{852}{}{那真是太可惜了。}
#{853}{}{Why won't anyone tell you anything about the research?}
{853}{}{为什么没人告诉你关于这项研究的事？}
#{854}{}{It looks like you can't tell me anything I wouldn't already know.}
{854}{}{看来你不能告诉我任何我还不知道的事情。}
#{855}{}{I'll go ask someone else. Goodbye.}
{855}{}{我去问问别人。再见。}
#{900}{}{He's the head of research on this level. The research towards lowering the number of donors. At least he says so. You can try talking to him, but unless you have the necessary clearance, he won't tell you much.}
{900}{}{他是这一级别的研究负责人。减少捐赠者数量的研究。至少他是这么说的。你可以试着和他谈谈，但除非你有必要的许可，否则他不会告诉你太多。}
#{901}{}{It would really be a shame if there were no more donors after his research.}
{901}{}{如果在他的研究之后没有更多的捐赠者，那真是太遗憾了。}
#{902}{}{Why won't anyone tell you anything about the research?}
{902}{}{为什么没人告诉你关于这项研究的事？}
#{903}{}{It looks like you can't tell me anything I wouldn't already know.}
{903}{}{看来你不能告诉我任何我还不知道的事情。}
#{904}{}{I'll try. Bye.}
{904}{}{我试试看。再见。}
#{950}{}{It really wouldn't surprise me anymore. Not that I believe in fate or any bullshit like that. But sometimes I just think that the world's governed by Murphy's Law. For instance, there had never been problems with the reborns, then the Thirteenth had to go crazy all of a sudden! Makes you think.}
{950}{}{我再也不会感到惊讶了。不是说我相信命运或者任何类似的废话。但有时我觉得世界是由墨菲定律统治的。比如说，重生从来就没有问题，然后第十三个就突然疯了！让你思考。}
#{951}{}{You really believe it's because of the number 13?}
{951}{}{你真的相信是因为13号？}
#{952}{}{Who did you say this Richard was?}
{952}{}{你说这个理查德是谁？}
#{953}{}{And why won't anyone tell you anything about the research?}
{953}{}{为什么没人告诉你关于这项研究的事？}
#{954}{}{It looks like you can't tell me anything I wouldn't already know.}
{954}{}{看来你不能告诉我任何我还不知道的事情。}
#{955}{}{Uh, I have to go now.}
{955}{}{呃，我得走了。}
#{1000}{}{Of course not. I'm just joking. What else can I do, given that our lives are full of irony like that?}
{1000}{}{当然不是。我只是开玩笑。既然我们的生活充满了这样的讽刺，我还能做什么呢？}
#{1001}{}{Who did you say this Richard was?}
{1001}{}{你说这个理查德是谁？}
#{1002}{}{And why won't anyone tell you anything about the research?}
{1002}{}{为什么没人告诉你关于这项研究的事？}
#{1003}{}{It looks like you can't tell me anything I wouldn't already know.}
{1003}{}{看来你不能告诉我任何我还不知道的事情。}
#{1004}{}{Uh, I have to go now.}
{1004}{}{呃，我得走了。}
#{1050}{}{I'm too young to them. Most of them are people born before the war or shortly after it in a vault. But I'm a child of the wasteland, so nobody really trusts my knowledge. Never mind that I read every single book on science I've come across. It's only here that my scientific knowledge has taken off, I'm always studying something. Mostly to kill time.}
{1050}{}{我对他们来说太年轻了。他们大多是战前出生的人，或是战后不久出生在地下室的人。但我是一个荒原的孩子，所以没有人真正相信我的知识。别介意，我读了我遇到的每一本关于科学的书。只有在这里，我的科学知识才有了飞跃，我总是在学习一些东西。主要是为了消磨时间。}
#{1051}{}{What happened to you - how did you become a ghoul?}
{1051}{}{你怎么了-你是怎么变成僵尸的？}
#{1052}{}{Are you sure you don't know anything about the research here?}
{1052}{}{你确定你对这里的研究一无所知吗？}
#{1053}{}{It looks like you can't tell me anything I wouldn't already know.}
{1053}{}{看来你不能告诉我任何我还不知道的事情。}
#{1054}{}{I don't want you to die of boredom, but I have to go now.}
{1054}{}{我不想你无聊死，但我得走了。}
#{1100}{}{That was bad luck extraordinaire. You sure you want to know? I wouldn't want to bore you.}
{1100}{}{那真是倒霉非凡。你确定你想知道？我不想让你厌烦。}
#{1101}{}{Yes I do.}
{1101}{}{是的。}
#{1102}{}{Perhaps another time.}
{1102}{}{也许下次吧。}
#{1150}{}{OK. I'll start with how I used to live in the Hub. That used to be large city, far away to the west from here. I sort of liked it there and I stayed despite the warnings that the city might be attacked and destroyed by supermutants that had gone crazy after their Master died or whatever. I made my living mostly by guarding caravans, my last assignment being with the Crimson Caravan. That company was run by madmen, their caravans took the most dangerous routes, but also they paid the best. And I wanted to buy, get a load of this, a Geiger counter.}
{1150}{}{好 啊。我先说说我以前在中心的生活。那曾经是个大城市，离这里很远。我有点喜欢那里，尽管有人警告说这座城市可能会被主人死后发疯的超级变种人袭击和摧毁，我还是留下来了。我主要靠守卫商队谋生，我的最后一项任务是在深红色商队。那家公司是由疯子经营的，他们的商队走的是最危险的路线，但他们的报酬也是最高的。我想买一个盖革计数器。}
#{1151}{}{Go on...}
{1151}{}{继续。。。}
#{1200}{}{The caravan was, as you can expect, attacked by raiders. It was a numerous bunch, we never stood a chance. When things got ugly I managed to escape with just one bullet in my leg. You can think I'm a coward, but I'm alive unlike the heroes who uselessly defended the caravan to the death. Anyway, with a leg wound and without stimpaks the wasteland's more inhospitable than usual. Not to mention I got lost a little.}
{1200}{}{正如你所料，商队遭到了袭击者的袭击。那是一堆人，我们从来没有机会。当事情变得难看时，我只腿上中了一颗子弹就成功逃脱了。你可以认为我是个懦夫，但我活着不像那些徒劳地保卫商队至死的英雄。不管怎么说，腿受伤了，没有刺激，荒地比平常更荒凉。更不用说我迷路了。}
#{1201}{}{What happened next?}
{1201}{}{接下来发生了什么？}
#{1250}{}{What do you think? I tried to patch myself up and survive somehow. Nothing interesting. Finally after several weeks I got back to the Hub, or rather what was left of it. The threat was real, it turned out, the supermutants razed the city to the ground. There were ruins everywhere and lots of bodies. Not a pretty sight. I had to get as far away as possible, and I headed east. I don't really know why, I could have ended up heading anywhere.}
{1250}{}{你怎么认为？我试着修补自己，设法活下来。没什么有趣的。几周后，我终于回到了中心，或者更确切地说，回到了它剩下的地方。事实证明，这种威胁是真实存在的，超级变种人把这座城市夷为平地。到处都是废墟和很多尸体。不太好看。我必须尽可能地离开，然后向东走去。我真的不知道为什么，我可能会去任何地方。}
#{1251}{}{So how did you mutate into a ghoul?}
{1251}{}{你是怎么变异成僵尸的？}
#{1300}{}{Oh yeah... well I don't really know. Maybe I crossed some irradiated territory on my trip through the wasteland, or maybe it's from how I was searching all those supermutant corpses for something useful... which turned out to be a waste of time, of course. Hard to say. I couldn't buy that Geiger counter. Apart from not having enough caps there was no place left to buy it.}
{1300}{}{哦，是的。。。我真的不知道。也许我在穿越荒地的旅途中穿越了一些受辐射的区域，或者也许是因为我在搜寻那些超级变形虫的尸体寻找有用的东西。。。这当然是浪费时间。很难说。我买不起盖革计数器。除了没有足够的瓶盖，没有地方买了。}
#{1301}{}{I see. A very interesting story.}
{1301}{}{我懂了。一个非常有趣的故事。}
#{1350}{}{So how can I help you?}
{1350}{}{我能帮你什么？}
#{1351}{}{Tell me why you're manufacturing vault jumpsuits.}
{1351}{}{告诉我你为什么要生产保险箱连体衣。}
#{1352}{}{Could you give me a robe?}
{1352}{}{你能给我一件长袍吗？}
#{1353}{}{Tell me about the research on this floor.}
{1353}{}{告诉我这层楼的研究情况。}
#{1354}{}{I'm all set. Thanks.}
{1354}{}{我准备好了。谢谢。}
#{1400}{}{It really wouldn't surprise me anymore. Not that I believe in fate or any bullshit like that. But sometimes I just think that the world's governed by Murphy's Law. For instance, there had never been problems with the reborns, then the Thirteenth had to go crazy all of a sudden! Makes you think.}
{1400}{}{我再也不会感到惊讶了。不是说我相信命运或者任何类似的废话。但有时我觉得世界是由墨菲定律统治的。比如说，重生从来就没有问题，然后第十三个就突然疯了！让你思考。}
#{1401}{}{You really believe it's because of the number 13?}
{1401}{}{你真的相信是因为13号？}
#{1402}{}{Who did you say this Richard was?}
{1402}{}{你说这个理查德是谁？}
#{1403}{}{And why won't anyone tell you anything about the research?}
{1403}{}{为什么没人告诉你关于这项研究的事？}
#{1404}{}{It looks like you can't tell me anything I wouldn't already know.}
{1404}{}{看来你不能告诉我任何我还不知道的事情。}
#{1405}{}{Uh, I have to go now.}
{1405}{}{呃，我得走了。}
#{1450}{}{Whenever anyone happens to venture to these boring quarters once, they make sure they never set foot in here again. So what the hell are you doing here? Calm down, just joking. I'm glad whenever someone snaps me out of my boredom.}
{1450}{}{每当有人碰巧到这些无聊的地方冒险一次，他们就确保再也不到这里来了。你到底在这里干什么？冷静点，开个玩笑。每当有人把我从无聊中解救出来，我都很高兴。}
#{1451}{}{Tell me, why do you make vault jumpsuits here?}
{1451}{}{告诉我，你为什么在这里做跳马服？}
#{1452}{}{Can you give me a robe?}
{1452}{}{你能给我一件长袍吗？}
#{1453}{}{I'd like to know what research is done on this floor.}
{1453}{}{我想知道这层楼做了什么研究。}
#{1454}{}{Just wanted to say hello.}
{1454}{}{只是想打个招呼。}
#{1455}{}{Kunth?}
{1455}{}{昆斯？}
#{1500}{}{Haha, it seems Murphy's Law strikes again. We have such tight security, not a mouse could slip through. And yet the guards let you in? Now listen to me, dummy, you can't stay here! Go back to the yellow levels. If I see you here again, I'll have to report you to the guards. I don't want to, but I'm not getting into trouble over you.}
{1500}{}{哈哈，看来墨菲定律又来了。我们有如此严密的安全措施，一只老鼠也不能溜过去。但是警卫让你进去了？听我说，笨蛋，你不能呆在这里！回到黄色水平。如果我再在这里见到你，我就得向警卫报告。我不想，但我不会为你惹麻烦的。}
#{1501}{}{Ooga.}
{1501}{}{哦。}
#{1550}{}{It's unbelievable that Richard just killed all those normals. He's always so sure of himself, fully concentrated on his research and all of a sudden he goes crazy.}
{1550}{}{真不敢相信理查德竟然杀死了所有的正常人。他总是那么自信，全神贯注于自己的研究，一下子就疯了。}
#{1551}{}{Do you know why he did it?}
{1551}{}{你知道他为什么这么做吗？}
#{1552}{}{Whyhee?}
{1552}{}{为什么？}
#{1600}{}{Hard to imagine. He must've gone crazy for real, maybe he was under too much stress. They say he wanted to send the recording of their deaths to everyone in the complex, but he didn't manage to in time. We're supposed to keep it a secret, because it could be the last straw for many people. I'm unsure myself as to what comes next. We need so many normals as donors for rebirth for all us, but now we have none.}
{1600}{}{很难想象。他一定是真的疯了，也许压力太大了。他们说他想把他们的死亡记录发给建筑群里的每个人，但他没能及时收到。我们应该保守秘密，因为这可能是许多人的最后一根稻草。我不确定接下来会发生什么。我们需要这么多正常人作为我们所有人重生的捐赠者，但现在我们一个也没有了。}
#{1601}{}{Could you help me with something?}
{1601}{}{你能帮我做点什么吗？}
#{1602}{}{Who you?}
{1602}{}{你是谁？}
#{1650}{}{Sure I can. But what can I do for you?}
{1650}{}{我当然可以。但我能为你做些什么？}
#{1651}{}{Sorry, my name's Kath. What can I do for you?}
{1651}{}{对不起，我叫凯丝。有什么事吗？}
#{1652}{}{Tell me, why do you make vault jumpsuits here?}
{1652}{}{告诉我，你为什么在这里做跳马服？}
#{1653}{}{Can you give me a robe?}
{1653}{}{你能给我一件长袍吗？}
#{1654}{}{Nothing right now. See you.}
{1654}{}{现在什么都没有。再见。}
#{1655}{}{Bye.}
{1655}{}{再见。}
#{1700}{}{Sorry if I'm not in the best mood. But I'm still coping with what Richard did. I just can't understand it.}
{1700}{}{对不起，如果我心情不好。但我还在应付理查德的所作所为。我就是不明白。}
#{1701}{}{Tell me, why do you make vault jumpsuits here?}
{1701}{}{告诉我，你为什么在这里做跳马服？}
#{1702}{}{Can you give me a robe?}
{1702}{}{你能给我一件长袍吗？}
#{1703}{}{In that case I better go.}
{1703}{}{那样的话我最好走了。}
#{1704}{}{Kunth?}
{1704}{}{昆斯？}
