#{150}{}{You see Mimi.}
{150}{}{你看到咪咪了。}
#{250}{}{You see Mimi. She hasn't changed since your last meeting.}
{250}{}{你看到咪咪了。自从你上次见面后她就没变过。}
#{251}{}{You see Mimi the ghoul.}
{251}{}{你看到僵尸咪咪了。}
#{500}{}{Hi, I'm Mimi. If you need something, I think you should talk to someone else. Me and Rene are quite new here, so we don't really know how things work around here.}
{500}{}{嗨，我是咪咪。如果你需要什么，我想你应该和别人谈谈。我和雷内是新来的，所以我们不知道这里的情况。}
#{501}{}{Hi, I'm Mimi. If you need something, I think you should talk to someone else. Me and Rene are quite new here, so we don't really know how things work around here.}
{501}{}{嗨，我是咪咪。如果你需要什么，我想你应该和别人谈谈。我和雷内是新来的，所以我们不知道这里的情况。}
#{502}{}{I understand. How did you get here?}
{502}{}{我理解。你怎么来的？}
#{503}{}{So what's your impression of the Rebirth so far?}
{503}{}{到目前为止你对重生的印象如何？}
#{504}{}{I won't bother you then. Goodbye.}
{504}{}{那我就不打扰你了。再见。}
#{505}{}{Uh.}
{505}{}{休斯敦大学。}
#{550}{}{[Mimi sighs.] It's not a very cheerful story. We suffered a great deal on our way here. We had to flee Sedit, which had been our home for years, like we were some kind of criminals. We were helped by... a stranger. He arranged a caravan we were allowed to join secretly. But our paths soon went different ways, so we had to continue on our own. That's when the worst part of the journey began. Our friend Ivet was torn apart by a pack of wild dogs and Rene was badly wounded by radscorpions. He would've died, but a Rebirth patrol saved us in the last moment. They led us here afterwards.}
{550}{}{[咪咪叹了口气]这不是一个令人愉快的故事。我们在来的路上吃了很多苦。我们不得不逃离塞迪特，这是我们多年的家，就像我们是某种罪犯一样。我们得到了。。。一个陌生人。他安排了一个大篷车让我们秘密加入。但我们很快就走上了不同的道路，所以我们不得不继续自己的路。就在那时，旅程最糟糕的部分开始了。我们的朋友艾维特被一群野狗撕碎了，雷内被蝎子打成重伤。他本来会死的，但重生巡逻队在最后一刻救了我们。后来他们把我们带到这里。}
#{551}{}{[Mimi sighs.] It's not a very cheerful story. We suffered a great deal on our way here. We had to flee Sedit, which had been our home for years, like we were some kind of criminals. We were helped by... a stranger. She arranged a caravan we were allowed to join secretly. But our paths soon went different ways, so we had to continue on our own. That's when the worst part of the journey began. Our friend Ivet was torn apart by a pack of wild dogs and Rene was badly wounded by radscorpions. He would've died, but a Rebirth patrol saved us in the last moment. They led us here afterwards.}
{551}{}{[咪咪叹了口气]这不是一个令人愉快的故事。我们在来的路上吃了很多苦。我们不得不逃离塞迪特，这是我们多年的家，就像我们是某种罪犯一样。我们得到了。。。一个陌生人。她安排了一个我们被允许秘密加入的商队。但我们很快就走上了不同的道路，所以我们不得不继续自己的路。就在那时，旅程最糟糕的部分开始了。我们的朋友艾维特被一群野狗撕碎了，雷内被蝎子打成重伤。他本来会死的，但重生巡逻队在最后一刻救了我们。后来他们把我们带到这里。}
#{552}{}{A sad story. What's your impression of the Rebirth so far?}
{552}{}{一个悲伤的故事。到目前为止你对重生的印象如何？}
#{553}{}{[Reveal your face.] Mimi, it's me, }
{553}{}{咪咪，是我，}
#{554}{}{. I'm sorry about Ivet, but I'm glad at least you two are OK.}
{554}{}{. 我很抱歉，但我很高兴至少你们两个没事。}
#{555}{}{. I'm sorry about Ivet, but I'm glad at least you two are OK.}
{555}{}{. 我很抱歉，但我很高兴至少你们两个没事。}
#{556}{}{I'll have to go. Goodbye.}
{556}{}{我得走了。再见。}
#{600}{}{I think they're doing the right thing here. Ghouls have been suffering for too long. I know many people will die because of this, but is there another option for us? Dying will be those who attack us themselves, anyway. This work must continue.}
{600}{}{我认为他们在这里做的是对的。僵尸受苦太久了。我知道很多人会因此而死，但我们还有别的选择吗？不管怎样，那些袭击我们的人终将死去。这项工作必须继续下去。}
#{601}{}{I understand. What do you think about the Thirteenth, anyway?}
{601}{}{我理解。你觉得十三号怎么样？}
#{602}{}{I understand. What do you think about the Thirteenth, anyway?}
{602}{}{我理解。你觉得十三号怎么样？}
#{603}{}{If you think so. How did you get here, anyway?}
{603}{}{如果你这么认为的话。你怎么来的？}
#{604}{}{[Reveal your face.] You can't be serious, Mimi. It's monstrous!}
{604}{}{你不可能是认真的，咪咪。太可怕了！}
#{605}{}{I'll have to go. Goodbye Mimi.}
{605}{}{我得走了。再见，咪咪。}
#{650}{}{[Mimi doesn't know what to say for a while.] I don't think he's as bad as everybody says. But what he did was horrible. He betrayed all ghouls, he wanted to take away from them a chance for a better life. And it seems like he's still trying. He must be stopped. Until that happens, we ghouls won't be able to reach our goal.}
{650}{}{[咪咪一时不知该说什么]我觉得他没有大家说的那么坏。但他的所作所为很可怕。他背叛了所有的僵尸，他想夺走他们过上更好生活的机会。他似乎还在努力。必须阻止他。在那之前，我们这些僵尸将无法达到我们的目标。}
#{651}{}{[Mimi doesn't know what to say for a while.] I don't think she's as bad as everybody says. But what she did was horrible. She betrayed all ghouls, she wanted to take away from them a chance for a better life. And it seems like she's still trying. She must be stopped. Until that happens, we ghouls won't be able to reach our goal.}
{651}{}{[咪咪一时不知该说什么]我觉得她没有大家说的那么坏。但她做的很可怕。她背叛了所有的僵尸，她想夺走他们过上更好生活的机会。看来她还在努力。必须阻止她。在那之前，我们这些僵尸将无法达到我们的目标。}
#{652}{}{I guess you're right. How did you get here, anyway?}
{652}{}{我想你是对的。你怎么来的？}
#{653}{}{[Reveal your face.] Despite what he did for you? You know I'm him. Am I right?}
{653}{}{不管他为你做了什么？你知道我就是他。我说得对吗？}
#{654}{}{[Reveal your face.] Despite what she did for you? You know I'm her. Am I right?}
{654}{}{不管她为你做了什么？你知道我就是她。我说得对吗？}
#{655}{}{As you wish. I'll have to go. Goodbye.}
{655}{}{如你所愿。我得走了。再见。}
#{700}{}{The Thirteenth! [She makes a scared face.] You... You have to surrender. Don't you understand what danger you present to the whole Rebirth? You're not that evil. The Savior'll spare you if you surrender to him now.}
{700}{}{十三号！[她吓了一跳]你。。。你必须投降。你不明白你给整个重生带来了什么危险吗？你没那么邪恶。如果你现在向他投降，救世主会饶了你的。}
#{701}{}{The Thirteenth! [She makes a scared face.] You... You have to surrender. Don't you understand what danger you present to the whole Rebirth? You're not that evil. The Savior'll spare you if you surrender to him now.}
{701}{}{十三号！[她吓了一跳]你。。。你必须投降。你不明白你给整个重生带来了什么危险吗？你没那么邪恶。如果你现在向他投降，救世主会饶了你的。}
#{702}{}{I'm sorry, Mimi. I can't do that.}
{702}{}{对不起，咪咪。我不能那样做。}
#{703}{}{OK. I'll have myself escorted to him.}
{703}{}{好 啊。我会让人护送我去见他。}
#{750}{}{Hi. What can I do for you?}
{750}{}{你好。有什么事吗？}
#{751}{}{I'd like to know how you managed to get here.}
{751}{}{我想知道你是怎么来的。}
#{752}{}{I'd like to know your opinion on the Rebirth.}
{752}{}{我想知道你对重生的看法。}
#{753}{}{I'd like to know your opinion on the Rebirth.}
{753}{}{我想知道你对重生的看法。}
#{754}{}{What do you think about the Thirteenth, anyway?}
{754}{}{你觉得十三号怎么样？}
#{755}{}{What do you think about the Thirteenth, anyway?}
{755}{}{你觉得十三号怎么样？}
#{756}{}{[Reveal your face.] You weren't serious about the Rebirth, were you, Mimi? The things they're doing. It's monstrous!}
{756}{}{你对重生不是认真的吧，咪咪？他们正在做的事情。太可怕了！}
#{757}{}{[Reveal your face.] Do you really wish me death? Even after what I did for you? You know I'm the Thirteenth. Am I right?}
{757}{}{你真的希望我死吗？即使在我为你所做的一切之后？你知道我是第十三个。我说得对吗？}
#{758}{}{[Reveal your face.] Do you really wish me death? Even after what I did for you? You know I'm the Thirteenth. Am I right?}
{758}{}{你真的希望我死吗？即使在我为你所做的一切之后？你知道我是第十三个。我说得对吗？}
#{759}{}{Nothing right now. Goodbye.}
{759}{}{现在什么都没有。再见。}
#{760}{}{Uh.}
{760}{}{休斯敦大学。}
#{800}{}{You haven't given me another option. [She turns away from you.] Guards! He's here... The Thirteenth's here!}
{800}{}{你没有给我别的选择。[她转身离开你]守卫！他在这里。。。十三号来了！}
#{801}{}{You haven't given me another option. [She turns away from you.] Guards! She's here... The Thirteenth's here!}
{801}{}{你没有给我别的选择。[她转身离开你]守卫！她在这里。。。十三号来了！}
#{802}{}{You've made a big mistake...}
{802}{}{你犯了个大错。。。}
#{850}{}{[She makes a scared face.] Eh, you... You have to surrender. Don't you understand what danger you present to the whole Rebirth? You're not that evil. The Savior'll spare you if you surrender to him now.}
{850}{}{[她吓了一跳]呃，你。。。你必须投降。你不明白你给整个重生带来了什么危险吗？你没那么邪恶。如果你现在向他投降，救世主会饶了你的。}
#{851}{}{[She makes a scared face.] Eh, you... You have to surrender. Don't you understand what danger you present to the whole Rebirth? You're not that evil. The Savior'll spare you if you surrender to him now.}
{851}{}{[她吓了一跳]呃，你。。。你必须投降。你不明白你给整个重生带来了什么危险吗？你没那么邪恶。如果你现在向他投降，救世主会饶了你的。}
#{852}{}{I'm sorry, Mimi. I can't do that.}
{852}{}{对不起，咪咪。我不能那样做。}
#{853}{}{OK. I'll have myself escorted to him.}
{853}{}{好 啊。我会让人护送我去见他。}
