#{100}{}{You see a man.}
{100}{}{你看到一个男人。}
#{200}{}{You see a prisoner standing right in front of the force field, watching you intently.}
{200}{}{你看到一个囚犯站在原力场的正前方，目不转睛地看着你。}
#{300}{}{Damn, man!}
{300}{}{该死，伙计！}
#{301}{}{Hey, over here!}
{301}{}{嘿，这边！}
#{302}{}{Come on over here!}
{302}{}{过来！}
#{303}{}{I want to talk to you!}
{303}{}{我想和你谈谈！}
#{304}{}{Damn, woman!}
{304}{}{妈的，女人！}
#{500}{}{How 'bout it ghoulie? Come to see us suffer?!}
{500}{}{怎么了，僵尸？来看我们受苦？！}
#{501}{}{I want to save you.}
{501}{}{我想救你。}
#{502}{}{I don't even want to talk to you.}
{502}{}{我甚至不想和你说话。}
#{550}{}{Yeah right. A ghoul that doesn't want to become a normal human! Try telling that to someone else, mutant.}
{550}{}{是的，没错。一个不想变成正常人的僵尸！试着告诉别人，变种人。}
#{551}{}{I'm not a ghoul. [Show him your face so that only he can see it.]}
{551}{}{我不是僵尸。[把你的脸给他看，这样只有他才能看到。]}
#{552}{}{If you don't want my help, then goodbye.}
{552}{}{如果你不需要我的帮助，那么再见。}
#{600}{}{Well shoot me shitless, a human! Damn fine job getting all the way here, man. I already have an escape plan. Let me tell you what to do.}
{600}{}{好吧，把我射得屁滚尿流，一个人！干得好，老兄。我已经有逃跑计划了。我来告诉你该怎么办。}
#{601}{}{Well shoot me shitless, a human! Damn fine job getting all the way here, woman. I already have an escape plan. Let me tell you what to do.}
{601}{}{好吧，把我射得屁滚尿流，一个人！干得好，女人。我已经有逃跑计划了。我来告诉你该怎么办。}
#{602}{}{I'm listening.}
{602}{}{我在听。}
#{650}{}{Some of us have been here for a fucking long time, we listen and watch those bastards, finding out what we can. We know that this floor is powered by two generators. These assholes have been rerouting power, digging in anything they find, and really fucked-up bad. If you disable generator number 1, the lab with the adjacent rooms, including force fields in our prison on that side, will be offline for a few minutes.}
{650}{}{我们中的一些人已经在这里他妈的很长时间了，我们听着看着那些混蛋，找出我们能做的。我们知道这层楼由两台发电机供电。这些混蛋一直在重新分配权力，挖掘他们发现的任何东西，真的搞砸了。如果你关闭了1号发电机，与相邻房间的实验室，包括那边监狱里的力场，将离线几分钟。}
#{651}{}{What will you do?}
{651}{}{你会怎么做？}
#{700}{}{Those few minutes are enough for us to seize weapons and shoot our way to the surface. There are a damn lot of us here and most of us are ready to fight for our lives. We just need the chance. There are plenty of weapons, they have them next to the cells for their disgusting tests and for suppressing any escape attempts, those assholes. So all you need to do is get to the sixth floor of this complex and blow up generator number 1 there.}
{700}{}{这几分钟足以让我们缴获武器，一路向水面射击。我们这里有很多人，我们大多数人都准备好为自己的生命而战。我们只需要机会。那里有很多武器，他们把它们放在牢房旁边，用来做恶心的测试，压制任何逃跑企图，那些混蛋。所以你所要做的就是到这个综合楼的六楼，在那里炸掉1号发电机。}
#{701}{}{I'll see what I can do.}
{701}{}{我看看我能做什么。}
#{750}{}{[The instant the man finishes speaking, another prisoner speaks up from an adjacent cell.] That's madness, walking among them without weapons! One tiny mistake and it all fucks up! They reveal one of us and the rest will immediately get shot! You'd better disable generator number 1. That will put the lab and the adjacent rooms including the force fields in our prison offline for several minutes.}
{750}{}{[那人一说完，隔壁牢房里又来了一个囚犯。]真是疯了，没带武器就走在他们中间！一个小小的错误就把事情搞砸了！他们发现了我们中的一个，其他人马上就会被枪杀！你最好关掉一号发电机。这将使实验室和邻近的房间，包括我们监狱里的力场，离线几分钟。}
#{751}{}{What will you do then?}
{751}{}{那你怎么办？}
#{800}{}{Damn, if you stick around here for much longer, you'll only draw attention to yourself and you'll mess up the whole plan.}
{800}{}{妈的，如果你在这儿呆久了，你只会引起别人对你自己的注意，你会把整个计划搞砸的。}
#{801}{}{What do you think about the other plan?}
{801}{}{你觉得另一个计划怎么样？}
#{802}{}{What if I just kill all the ghouls?}
{802}{}{如果我杀了所有的僵尸呢？}
#{803}{}{OK, I'm going.}
{803}{}{好的，我要走了。}
#{850}{}{That's bullshit! We can't just walk around among them unarmed. One tiny mistake and it all fucks up! They reveal one of us and the rest gets shot! You'd better stick to my plan, and destroy generator number 1.}
{850}{}{胡说八道！我们不能手无寸铁地在他们中间走来走去。一个小小的错误就把事情搞砸了！他们发现了我们中的一个，剩下的就被枪杀了！你最好坚持我的计划，摧毁1号发电机。}
#{851}{}{What if I just kill all the ghouls?}
{851}{}{如果我杀了所有的僵尸呢？}
#{852}{}{I'll think about it. Be ready though.}
{852}{}{我会考虑的。但要做好准备。}
#{900}{}{Oh sure. One man against an army. You better keep low, dumbass. You can't help us escape if you're dead.}
{900}{}{哦，当然。一个人对抗军队。你最好保持低调，笨蛋。如果你死了，你不能帮我们逃走。}
#{901}{}{Oh sure. One woman against an army. You better keep low, dumbass. You can't help us escape if you're dead.}
{901}{}{哦，当然。一个女人反对军队。你最好保持低调，笨蛋。如果你死了，你不能帮我们逃走。}
#{902}{}{What do you think about the other plan?}
{902}{}{你觉得另一个计划怎么样？}
#{903}{}{I'll think about it. Be ready though.}
{903}{}{我会考虑的。但要做好准备。}
#{950}{}{Well shoot me shitless, a human! Damn good job getting all the way here, man. You gotta get us out of here. I have a plan how you can do it. Let me tell you what to do.}
{950}{}{好吧，把我射得屁滚尿流，一个人！干得好，老兄。你得把我们弄出去。我有个计划你怎么做。我来告诉你该怎么办。}
#{951}{}{Well shoot me shitless, a human! Damn good job getting all the way here, woman. You gotta get us out of here. I have a plan how you can do it. Let me tell you what to do.}
{951}{}{好吧，把我射得屁滚尿流，一个人！干得好，女人。你得把我们弄出去。我有个计划你怎么做。我来告诉你该怎么办。}
#{952}{}{I'm listening.}
{952}{}{我在听。}
#{1000}{}{How 'bout it ghoulie? Come to see us suffer?!}
{1000}{}{怎么了，僵尸？来看我们受苦？！}
#{1001}{}{Boo! [Show your face.]}
{1001}{}{喝倒采！[露脸]}
#{1002}{}{Yuck.}
{1002}{}{讨厌。}
#{1050}{}{Oh shoot me shitless, I finally meet a human in here and he just has to be a fucking retard! Look, you gotta get us out of here. I have a plan and I'll tell you what to do.}
{1050}{}{噢，射死我吧，我终于在这里遇到一个人了，他一定是个笨蛋！听着，你得把我们弄出去。我有个计划，我会告诉你该怎么做。}
#{1051}{}{Oh shoot me shitless, I finally meet a human in here and she just has to be a fucking retard! Look, you gotta get us out of here. I have a plan and I'll tell you what to do.}
{1051}{}{噢，射死我吧，我终于在这里遇到一个人了，她一定是个他妈的白痴！听着，你得把我们弄出去。我有个计划，我会告诉你该怎么做。}
#{1052}{}{Ugh.}
{1052}{}{啊。}
#{1100}{}{Some of us have been here for a fucking long time, we listen and watch those bastards, finding out what we can. We know that this floor is powered by two generators. These assholes have been rerouting power, digging in anything they find, and really fucked-up bad. If you disable generator number 1, the lab with the adjacent rooms, including force fields in our prison on that side, will be offline for a few minutes.}
{1100}{}{我们中的一些人已经在这里他妈的很长时间了，我们听着看着那些混蛋，找出我们能做的。我们知道这层楼由两台发电机供电。这些混蛋一直在重新分配权力，挖掘他们发现的任何东西，真的搞砸了。如果你关闭了1号发电机，与相邻房间的实验室，包括那边监狱里的力场，将离线几分钟。}
#{1101}{}{Huh?}
{1101}{}{嗯？}
#{1150}{}{Those few minutes are enough for us to seize weapons and shoot our way to the surface. There are a damn lot of us here and most of us are ready to fight for our lives. We just need the chance. There are plenty of weapons, they have them next to the cells for their disgusting tests and for suppressing any escape attempts, those assholes. You, and now listen very well, need to get to the sixth floor of this complex and blow up generator number 1 there.}
{1150}{}{这几分钟足以让我们缴获武器，一路向水面射击。我们这里有很多人，我们大多数人都准备好为自己的生命而战。我们只需要机会。那里有很多武器，他们把它们放在牢房旁边，用来做恶心的测试，压制任何逃跑企图，那些混蛋。你，现在好好听着，需要到这个综合楼的六楼，在那里炸掉1号发电机。}
#{1151}{}{Uh-huh.}
{1151}{}{啊哈。}
#{1200}{}{[The instant the man finishes speaking, another prisoner speaks up from an adjacent cell.] That's madness, walking among them without weapons! One tiny mistake and it all fucks up! They reveal one of us and the rest will immediately get shot! You'd better disable generator number 1. That will put the lab and the adjacent rooms including the force fields in our prison offline for several minutes.}
{1200}{}{[那人一说完，隔壁牢房里又来了一个囚犯。]真是疯了，没带武器就走在他们中间！一个小小的错误就把事情搞砸了！他们发现了我们中的一个，其他人马上就会被枪杀！你最好关掉一号发电机。这将使实验室和邻近的房间，包括我们监狱里的力场，离线几分钟。}
#{1201}{}{Hows?}
{1201}{}{怎么样？}
#{1250}{}{Well shoot me shitless, a human! Damn good job getting all the way here, man. You gotta get us out of here. I have a plan how you can do it. Let me tell you what to do.}
{1250}{}{好吧，把我射得屁滚尿流，一个人！干得好，老兄。你得把我们弄出去。我有个计划你怎么做。我来告诉你该怎么办。}
#{1251}{}{Well shoot me shitless, a human! Damn good job getting all the way here, woman. You gotta get us out of here. I have a plan how you can do it. Let me tell you what to do.}
{1251}{}{好吧，把我射得屁滚尿流，一个人！干得好，女人。你得把我们弄出去。我有个计划你怎么做。我来告诉你该怎么办。}
#{1252}{}{Ugha.}
{1252}{}{乌哈。}
#{1300}{}{Oh shit, you're a retard. Fuck this! Just try to listen. Some of us have been here for a fucking long time, we listen and watch those bastards, finding out what we can. We know that this floor is powered by two generators. These assholes have been rerouting power, digging in anything they find, and really fucked-up bad. If you disable generator number 1, the lab with the adjacent rooms, including force fields in our prison on that side, will be offline for a few minutes.}
{1300}{}{哦，妈的，你是个白痴。去他妈的！试着去听。我们中的一些人已经在这里他妈的很长时间了，我们听着看着那些混蛋，找出我们能做的。我们知道这层楼由两台发电机供电。这些混蛋一直在重新分配权力，挖掘他们发现的任何东西，真的搞砸了。如果你关闭了1号发电机，与相邻房间的实验室，包括那边监狱里的力场，将离线几分钟。}
#{1301}{}{Oh shit, you're a retard. Fuck this! Just try to listen. Some of us have been here for a fucking long time, we listen and watch those bastards, finding out what we can. We know that this floor is powered by two generators. These assholes have been rerouting power, digging in anything they find, and really fucked-up bad. If you disable generator number 1, the lab with the adjacent rooms, including force fields in our prison on that side, will be offline for a few minutes.}
{1301}{}{哦，妈的，你是个白痴。去他妈的！试着去听。我们中的一些人已经在这里他妈的很长时间了，我们听着看着那些混蛋，找出我们能做的。我们知道这层楼由两台发电机供电。这些混蛋一直在重新分配权力，挖掘他们发现的任何东西，真的搞砸了。如果你关闭了1号发电机，与相邻房间的实验室，包括那边监狱里的力场，将离线几分钟。}
#{1302}{}{Huh?}
{1302}{}{嗯？}
#{1350}{}{Shit, retard, if you stick around too much, you'll only draw attention to yourself and you'll fuck up the whole plan.}
{1350}{}{妈的，笨蛋，如果你呆得太久，你只会引起别人对你自己的注意，你会把整个计划搞砸的。}
#{1351}{}{Shit, retard, if you stick around too much, you'll only draw attention to yourself and you'll fuck up the whole plan.}
{1351}{}{妈的，笨蛋，如果你呆得太久，你只会引起别人对你自己的注意，你会把整个计划搞砸的。}
#{1352}{}{Huh friend plan?}
{1352}{}{嗯，朋友计划？}
#{1353}{}{I strong! Boom ghouls. All!}
{1353}{}{我很坚强！猛击僵尸。全部！}
#{1354}{}{Okay!}
{1354}{}{可以！}
#{1400}{}{That other plan is bullshit! We can't just walk around among them unarmed. One small mistake and it all fucks up! They reveal one and they shoot the rest! You better stick to my plan, and take care of generator number 1.}
{1400}{}{另一个计划是胡说八道！我们不能手无寸铁地在他们中间走来走去。一个小错误就把事情搞砸了！他们揭穿了一个，射杀了其余的！你最好坚持我的计划，照顾好1号发电机。}
#{1401}{}{I strong! Boom ghouls. All!}
{1401}{}{我很坚强！猛击僵尸。全部！}
#{1402}{}{Okay!}
{1402}{}{可以！}
#{1450}{}{Sure, you against an army. Try to think, retard. You can't help us escape if you're dead.}
{1450}{}{当然，你反对军队。试着想想，笨蛋。如果你死了，你不能帮我们逃走。}
#{1451}{}{Sure, you against an army. Try to think, retard. You can't help us escape if you're dead.}
{1451}{}{当然，你反对军队。试着想想，笨蛋。如果你死了，你不能帮我们逃走。}
#{1452}{}{Huh friend plan?}
{1452}{}{嗯，朋友计划？}
#{1453}{}{Okay!}
{1453}{}{可以！}
