#{100}{}{You see a ghoul.}
{100}{}{你看到一个僵尸。}
#{150}{}{You see Richard.}
{150}{}{你看到理查德了。}
#{200}{}{You see a ghoul in a robe. He looks fully immersed in his work.}
{200}{}{你看到一个穿着长袍的僵尸。他看上去全神贯注于工作。}
#{250}{}{You see Richard. He is fully concentrated on his research.}
{250}{}{你看到理查德了。他全神贯注于他的研究。}
#{400}{}{Guards! How the hell did this intruder get in here?!}
{400}{}{警卫！这个入侵者是怎么进来的？！}
#{401}{}{Guards! An intruder!}
{401}{}{警卫！入侵者！}
#{402}{}{You're living in a dream. You must see reality!}
{402}{}{你活在梦里。你必须看到现实！}
#{500}{}{Do you have the latest test results for me?}
{500}{}{你有最新的测试结果给我吗？}
#{501}{}{No. I'm new here.}
{501}{}{不，我是新来的。}
#{502}{}{No. I'm new here.}
{502}{}{不，我是新来的。}
#{503}{}{Boogoo-ooga.}
{503}{}{博古-奥加。}
#{550}{}{Well, that's something. We need more personnel, but there's still a lack of able and cleared scientists. My name is Richard.}
{550}{}{好吧，那是件事。我们需要更多的人员，但仍然缺乏有能力和有经验的科学家。我叫理查德。}
#{551}{}{Tell me about your research.}
{551}{}{告诉我你的研究。}
#{552}{}{They told me I could get a robot CPU card here.}
{552}{}{他们告诉我我可以在这里得到一个机器人CPU卡。}
#{553}{}{There are suspicions that somebody's using your access card without authorization. Could you please show me you have it with you?}
{553}{}{有人怀疑有人擅自使用了你的门禁卡。你能给我看看你带着它吗？}
#{554}{}{Let's talk another time.}
{554}{}{我们改天再谈吧。}
#{600}{}{Are you doing Robert's job? You can program a CPU card in the IT lab. There should be plenty of them lying around.}
{600}{}{你在做罗伯特的工作吗？你可以在IT实验室编程一个CPU卡。应该有很多这样的卡。}
#{601}{}{Thank you for telling me.}
{601}{}{谢谢你告诉我。}
#{650}{}{I'm not sure I'm allowed to.}
{650}{}{我不确定我是否被允许。}
#{651}{}{It's all right. I know the machine isn't working.}
{651}{}{没事的。我知道机器坏了。}
#{700}{}{Well, OK. But be careful who you tell that. There are several workers on this floor who aren't fully aware of the state of affairs. As you certainly know, I'm in charge of research on this floor. We test donors here. It may be the problem is in them. Perhaps we require somehow specific donors, or it may be necessary for donor tissue to undergo certain procedures. At any rate, if the problem lies therein, we'll crack it in the end.}
{700}{}{好吧，好吧。但你要小心告诉谁。这层楼有几个工人对事态还不完全了解。你当然知道，我负责这层楼的研究。我们在这里测试捐赠者。问题可能出在他们身上。也许我们需要某种特定的捐赠者，或者捐赠者组织需要接受某些程序。无论如何，如果问题出在这里，我们最终会解决的。}
#{701}{}{The research trying to achieve a lowered number of required donors for rebirth is just a ruse then?}
{701}{}{试图降低再生所需供体数量的研究只是一个诡计？}
#{702}{}{Are you one of those who came here first after the Savior?}
{702}{}{你是在救世主之后第一个来到这里的人吗？}
#{703}{}{How is it even possible to cure mutations? It almost sounds like scientific mumbo-jumbo.}
{703}{}{怎么可能治愈突变呢？听起来像是科学上的胡言乱语。}
#{704}{}{That's all I need to know.}
{704}{}{我只想知道这些。}
#{750}{}{Why certainly. First we must resolve our main problem, and only then can we indulge in trivialities such as lowering the number of donors or even their elimination from the process. Although our current focus on the degree of donor irradiation could bring secondary results even in areas such as those.}
{750}{}{当然可以。首先，我们必须解决我们的主要问题，只有这样，我们才能沉溺于琐碎的事情，例如减少捐助者的数目，甚至把他们从这一进程中除名。尽管我们目前对供体辐射程度的关注可能会带来次要的结果，即使是在这些领域。}
#{751}{}{Tell me more about the current focus of your research.}
{751}{}{告诉我更多关于你目前研究的重点。}
#{752}{}{So a complete removal of donors from the process is possible?}
{752}{}{那么，完全把捐赠者从这个过程中剔除是可能的？}
#{753}{}{I thought it was the machine itself that was malfunctioning.}
{753}{}{我以为是机器本身出了故障。}
#{754}{}{I thought it was the machine itself that was malfunctioning.}
{754}{}{我以为是机器本身出了故障。}
#{755}{}{Will there be enough donors left for everyone once you solve this problem?}
{755}{}{一旦你解决了这个问题，会有足够的捐赠者留给每个人吗？}
#{756}{}{I need to ask you about something else.}
{756}{}{我要问你一些别的事。}
#{757}{}{That's all I need to know.}
{757}{}{我只想知道这些。}
#{800}{}{Thanks to the possibility of observing the development of the reborn over a longer term, we discovered that an important factor is the degree of irradiation, as far as the total decay times of regenerated tissue are concerned. That's why we're now focusing specifically on this factor. However, we're having trouble maintaining a sufficient supply of donors with low radiation levels. I gather the offspring of Vault 16's inhabitants would be the best in that regard.}
{800}{}{由于有可能长期观察再生组织的发育，我们发现，就再生组织的总衰变时间而言，一个重要因素是辐照程度。这就是为什么我们现在特别关注这个因素。然而，我们很难维持足够的低辐射供体。我想16号地下室居民的后代在这方面是最好的。}
#{801}{}{So the annual rebirth takes place for research purposes?}
{801}{}{所以每年的重生都是为了研究目的？}
#{802}{}{Is it even realistic to eliminate donors out of the process completely?}
{802}{}{把捐赠者完全排除在这一进程之外是否现实？}
#{803}{}{I thought it was the machine itself that was malfunctioning.}
{803}{}{我以为是机器本身出了故障。}
#{804}{}{I thought it was the machine itself that was malfunctioning.}
{804}{}{我以为是机器本身出了故障。}
#{805}{}{Will there be enough donors left for everyone once you solve the problem?}
{805}{}{一旦你解决了这个问题，会有足够的捐赠者留给每个人吗？}
#{806}{}{I need to ask you about something else.}
{806}{}{我要问你一些别的事。}
#{807}{}{That's all I need to know.}
{807}{}{我只想知道这些。}
#{850}{}{Only using cloning, either of entire bodies or at least individual organs, could we replace donors. Thomas used to be in charge of starting up our cloning research, but fortunately the Savior put a stop to that. We can hardly rely on the research of something so complex that it lasted several decades of pre-war research without showing any proper success.}
{850}{}{只有通过克隆，无论是整个身体还是至少是单个器官，我们才能取代捐赠者。托马斯曾经负责启动我们的克隆研究，但幸运的是救世主阻止了这一点。我们很难依赖于对如此复杂的东西的研究，它在战前持续了几十年的研究却没有取得任何适当的成功。}
#{851}{}{I believe the pre-war scientists were successful with cloning.}
{851}{}{我相信战前的科学家在克隆方面取得了成功。}
#{852}{}{What is Thomas working on now?}
{852}{}{托马斯现在在做什么？}
#{853}{}{I thought it was the machine itself that was malfunctioning.}
{853}{}{我以为是机器本身出了故障。}
#{854}{}{I thought it was the machine itself that was malfunctioning.}
{854}{}{我以为是机器本身出了故障。}
#{855}{}{Will there be enough donors left for everyone once you solve the problem?}
{855}{}{一旦你解决了这个问题，会有足够的捐赠者留给每个人吗？}
#{856}{}{I need to ask you about something else.}
{856}{}{我要问你一些别的事。}
#{857}{}{That's all I need to know.}
{857}{}{我只想知道这些。}
#{900}{}{Yes, partially, but not to the extent that we'd require. Apart from the fact, of course, that there are very few records remaining about their cloning research.}
{900}{}{是的，有一部分，但没有达到我们需要的程度。当然，除了这一事实之外，关于他们的克隆研究的记录很少。}
#{901}{}{So what is Thomas working on now?}
{901}{}{那么托马斯现在在做什么呢？}
#{902}{}{I thought it was the machine itself that was malfunctioning.}
{902}{}{我以为是机器本身出了故障。}
#{903}{}{I thought it was the machine itself that was malfunctioning.}
{903}{}{我以为是机器本身出了故障。}
#{904}{}{Will there be enough donors left for everyone once you solve the problem?}
{904}{}{一旦你解决了这个问题，会有足够的捐赠者留给每个人吗？}
#{905}{}{I need to ask you about something else.}
{905}{}{我要问你一些别的事。}
#{906}{}{That's all I need to know.}
{906}{}{我只想知道这些。}
#{950}{}{As far as we know Thomas has deserted. What else could you expect from a friend of that traitor the Thirteenth? I think they were in it together from the start. Maybe he even sabotaged our work.}
{950}{}{据我们所知，托马斯已经离开了。你还能指望十三号那个叛徒的朋友做什么？我想他们从一开始就在一起。也许他甚至破坏了我们的工作。}
#{951}{}{I believe the pre-war scientists were successful with cloning.}
{951}{}{我相信战前的科学家在克隆方面取得了成功。}
#{952}{}{I thought it was the machine itself that was malfunctioning.}
{952}{}{我以为是机器本身出了故障。}
#{953}{}{Will there be enough donors left for everyone once you solve the problem?}
{953}{}{一旦你解决了这个问题，会有足够的捐赠者留给每个人吗？}
#{954}{}{I need to ask you about something else.}
{954}{}{我要问你一些别的事。}
#{955}{}{That's all I need to know.}
{955}{}{我只想知道这些。}
#{1000}{}{I think the Savior started that really just as a morale-improvement program. But in the end it has been effective for our research as well.}
{1000}{}{我认为救世主开始这样做其实只是为了提高士气。但最终对我们的研究也是有效的。}
#{1001}{}{Is it even realistic to eliminate donors out of the process completely?}
{1001}{}{把捐赠者完全排除在这一进程之外是否现实？}
#{1002}{}{I thought it was the machine itself that was malfunctioning.}
{1002}{}{我以为是机器本身出了故障。}
#{1003}{}{I thought it was the machine itself that was malfunctioning.}
{1003}{}{我以为是机器本身出了故障。}
#{1004}{}{Will there be enough donors left for everyone once you solve the problem?}
{1004}{}{一旦你解决了这个问题，会有足够的捐赠者留给每个人吗？}
#{1005}{}{I need to ask you about something else.}
{1005}{}{我要问你一些别的事。}
#{1006}{}{That's all I need to know.}
{1006}{}{我只想知道这些。}
#{1050}{}{The rebirth of everyone in a single day is just to draw away attention from the fact that the machine isn't working. I wholeheartedly believe that once the machine is fully operational, us scientists along with the other members of the inner-circle, will be first in line to be reborn. It's our right, especially if we contribute to restoring the process. Otherwise I wouldn't bother at all. With all the waiting around for donors for everyone and given the size of Rebirth nowadays, I could die before I get reborn.}
{1050}{}{每个人在一天内的重生只是为了把人们的注意力从机器不工作的事实上引开。我全心全意地相信，一旦这台机器全面投入使用，美国科学家和其他核心圈子的成员，将首先排队重生。这是我们的权利，特别是如果我们有助于恢复进程。否则我一点也不麻烦。由于所有人都在等待捐赠者，再加上现在的重生规模，我可能在重生之前就死了。}
#{1051}{}{Tell me about the current focus of your research.}
{1051}{}{告诉我你目前的研究重点。}
#{1052}{}{Is it even realistic to eliminate donors out of the process completely?}
{1052}{}{把捐赠者完全排除在这一进程之外是否现实？}
#{1053}{}{I thought it was the machine itself that was malfunctioning.}
{1053}{}{我以为是机器本身出了故障。}
#{1054}{}{I thought it was the machine itself that was malfunctioning.}
{1054}{}{我以为是机器本身出了故障。}
#{1055}{}{I need to ask you about something else.}
{1055}{}{我要问你一些别的事。}
#{1056}{}{That's all I need to know.}
{1056}{}{我只想知道这些。}
#{1100}{}{The machine has been checked thoroughly and is still undergoing examination. But so far they haven't discovered anything wrong. That's why we need to look at all aspects of the process. The only thing we know for sure is that the Savior was reborn successfully. But later when he performed tests, the results were never at 100% anymore. Unfortunately we don't have any schematics for the machine, nor any records on the biological material used, so we can't tell what it was that the Savior transplanted himself.}
{1100}{}{这台机器已被彻底检查过，仍在接受检查。但到目前为止他们还没有发现任何问题。这就是为什么我们需要审视整个过程的方方面面。我们唯一确定的是救世主成功地重生了。但后来当他进行测试时，结果再也不是100%。不幸的是，我们没有任何机器的原理图，也没有任何关于所用生物材料的记录，所以我们无法判断救世主移植的是什么。}
#{1101}{}{Testing the Savior might reveal a thing or two.}
{1101}{}{测试救世主可能会发现一两件事。}
#{1102}{}{Tell me about the current focus of your research.}
{1102}{}{告诉我你目前的研究重点。}
#{1103}{}{Is it even realistic to eliminate donors out of the process completely?}
{1103}{}{把捐赠者完全排除在这一进程之外是否现实？}
#{1104}{}{Will there be enough donors left for everyone once you solve this problem?}
{1104}{}{一旦你解决了这个问题，会有足够的捐赠者留给每个人吗？}
#{1105}{}{I need to ask you about something else.}
{1105}{}{我要问你一些别的事。}
#{1106}{}{That's all I need to know.}
{1106}{}{我只想知道这些。}
#{1150}{}{At the beginning he underwent a series of thorough tests. But they never revealed anything interesting. His body seems healthy just like that of any other normal. Just like in the case of the other Reborn.}
{1150}{}{一开始他接受了一系列彻底的检查。但他们从未透露任何有趣的事情。他的身体似乎和其他正常人一样健康。就像另一个重生一样。}
#{1151}{}{Tell me about the current focus of your research.}
{1151}{}{告诉我你目前的研究重点。}
#{1152}{}{Is it even realistic to eliminate donors out of the process completely?}
{1152}{}{把捐赠者完全排除在这一进程之外是否现实？}
#{1153}{}{Will there be enough donors left for everyone once you solve the problem?}
{1153}{}{一旦你解决了这个问题，会有足够的捐赠者留给每个人吗？}
#{1154}{}{I need to ask you about something else.}
{1154}{}{我要问你一些别的事。}
#{1155}{}{That's all I need to know.}
{1155}{}{我只想知道这些。}
#{1200}{}{No, those are mostly people born before the war. I was born in a vault, I grew up there, studied there and later became a ghoul there when one section of the vault collapsed and it didn't shield us from the radiation. I had to fight hard to get my place here, and I won't rest before I'm a real human again, and not just this zombie caricature.}
{1200}{}{不，他们大多是战前出生的人。我出生在一个地下室，在那里长大，在那里学习，后来在那里变成了一个僵尸，因为地下室的一部分坍塌了，它不能保护我们免受辐射。我必须努力奋斗才能在这里找到自己的位置，在我再次成为一个真正的人类之前，我不会休息，而不仅仅是这个僵尸漫画。}
#{1201}{}{I see. Let me ask you about something else.}
{1201}{}{我懂了。我再问你一件事。}
#{1202}{}{I wish you luck. Bye.}
{1202}{}{祝你好运。再见。}
#{1250}{}{The mutations themselves are not cured as such. The mutated tissue is replaced by transplanted tissue with no disruptions of its DNA in the required segments. The machine just regenerates the burnt cells and fuses the donor tissue with the body of the reborn subject. This process, taking place within the machine, however so far remains a mystery to us.}
{1250}{}{突变本身并没有被治愈。突变的组织被移植的组织所取代，所需片段中的DNA没有中断。这台机器只是让燃烧的细胞再生，并将供体组织与重生的受试者的身体融合。这个过程，发生在机器内部，然而到目前为止对我们来说仍然是个谜。}
#{1251}{}{Does the machine also regenerate cells in reproductive organs?}
{1251}{}{机器是否也能再生生殖器官中的细胞？}
#{1252}{}{But surely you can't replace all the mutated tissue, especially in the extent you would need to with ghouls.}
{1252}{}{但是你肯定不能替换所有的变异组织，尤其是在你需要用僵尸替换的程度上。}
#{1253}{}{I have a different question.}
{1253}{}{我有一个不同的问题。}
#{1254}{}{Thank you for clarifying a few things for me. Goodbye.}
{1254}{}{谢谢你为我澄清了一些事情。再见。}
#{1300}{}{Based on our estimates and according to the Savior's tests we know that it should, when working at 100%, but tests have shown that these most sensitive cells are not regenerated by the machine in its current state. Thus, the current reborn remain infertile.}
{1300}{}{根据我们的估计，根据救世主的测试，我们知道当它以100%的速度工作时，应该是这样的，但是测试表明，这些最敏感的细胞在当前状态下不会被机器再生。因此，目前的再生仍然不育。}
#{1301}{}{But surely you can't replace all the mutated tissue, especially in the extent you would need to with ghouls.}
{1301}{}{但是你肯定不能替换所有的变异组织，尤其是在你需要用僵尸替换的程度上。}
#{1302}{}{I have a different question.}
{1302}{}{我有一个不同的问题。}
#{1303}{}{Thank you for clarifying a few things for me. Goodbye.}
{1303}{}{谢谢你为我澄清了一些事情。再见。}
#{1350}{}{The deoxyribonucleic acid should, due to specific chemicals pumped into the body during the rebirth process, transform into its most stable form thus fixing the DNA strands of the non-transplanted tissue. Whereby the most stable form of DNA should be copied from the undisrupted DNA chain from the donor tissue.}
{1350}{}{由于在再生过程中被泵入体内的特定化学物质，脱氧核糖核酸应转化为最稳定的形式，从而固定非移植组织的DNA链。因此，最稳定的DNA形式应该从供体组织的未断裂DNA链中复制出来。}
#{1351}{}{But won't this cause a high incidence of flawed mitotic cross-overs?}
{1351}{}{但这不会导致有缺陷的有丝分裂交叉的高发生率吗？}
#{1352}{}{Does the machine also regenerate cells in reproductive organs?}
{1352}{}{机器是否也能再生生殖器官中的细胞？}
#{1353}{}{I have a different question.}
{1353}{}{我有一个不同的问题。}
#{1354}{}{Thank you for clarifying a few things for me. Goodbye.}
{1354}{}{谢谢你为我澄清了一些事情。再见。}
#{1400}{}{That is indeed what happens sooner or later to the current Reborn. It is our main problem, the solution to which still eludes us. But rest assured I have dedicated myself to resolving it.}
{1400}{}{这确实是现在的重生迟早会发生的事情。这是我们的主要问题，我们仍然没有找到解决办法。但请放心，我已经致力于解决这个问题。}
#{1401}{}{But this problem doesn't have any solutions!}
{1401}{}{但这个问题没有任何解决办法！}
#{1402}{}{Good luck with finding the solution.}
{1402}{}{祝你好运找到解决办法。}
#{1450}{}{Just because we've been unable to find a solution so far doesn't mean it doesn't exist. It must exist! The Savior is living proof! If you can't accept that, then at least stop wasting my time that I could be using towards finding a solution.}
{1450}{}{仅仅因为我们到目前为止还没有找到解决办法并不意味着它不存在。它一定存在！救世主是活生生的证明！如果你不能接受这一点，那么至少不要再浪费我的时间，我可以用来找到一个解决办法。}
#{1451}{}{But you said it yourself: You've dedicated yourself to finding the solution, and have failed. Isn't it more probable that the Savior is lying, than it is that you'll find a solution in the end by some miracle? The Thirteenth and Thomas realized this. That's why they ran away.}
{1451}{}{但你自己说的：你一直致力于寻找解决方案，但失败了。难道不是救世主撒谎的可能性比你最终会奇迹般地找到解决办法的可能性更大吗？十三和托马斯意识到了这一点。这就是他们逃跑的原因。}
#{1452}{}{Well good luck with that. The way I see it, you'll need all the luck you can get.}
{1452}{}{祝你好运。在我看来，你需要所有的运气。}
#{1470}{}{This is absurd. You're accusing the Savior of lying and you're basing this accusation on those two traitors? I can't believe the Savior would deceive us! Surely...}
{1470}{}{这太荒谬了。你在指控救世主撒谎而你却把这个指控建立在那两个叛徒身上？我不敢相信救世主会欺骗我们！当然。。。}
#{1471}{}{Just suppose for a second that the Savior isn't telling the truth. Would that not answer all your questions? Would that not resolve all your problems? And to me it makes more sense than to think that you, a brilliant scientist, hasn't found this supposedly real solution after all this time.}
{1471}{}{假设救世主没有说实话。这不能回答你所有的问题吗？这不能解决你所有的问题吗？对我来说，这比认为你，一个杰出的科学家，在这么长时间之后还没有找到这个被认为是真正的解决方案更有意义。}
#{1500}{}{Yes... That would answer them. All those tests... it would make sense all of a sudden. I don't know what to think. Is the Savior deceiving us or have I just been unable to find a solution? Either way all my hopes, everything I've done here, really has been for nothing... This has to end! [He enters commands into the computer.]}
{1500}{}{对。。。这就回答了他们。所有这些测试。。。这会突然变得有意义。我不知道该怎么想。救世主是在欺骗我们，还是我一直找不到解决办法？不管怎样，我所有的希望，我在这里所做的一切，都是徒劳的。。。这必须结束！[他把命令输入计算机。]}
#{1501}{}{What do you intend to do?}
{1501}{}{你打算做什么？}
#{1550}{}{I don't know if the Savior is telling the truth, nor what his intentions are. But I don't care anymore. I'll at least try to liberate some of us from this solutionless nonsense. Telling them the truth is a waste of time, nobody would believe me. But if I destroy their hopes, the main thing holding them here, many will leave by themselves in the end.}
{1550}{}{我不知道救世主说的是不是实话，也不知道他的意图是什么。但我不在乎了。我至少要把我们中的一些人从这种没有解决办法的胡说八道中解放出来。告诉他们真相是浪费时间，没有人会相信我。但如果我摧毁了他们的希望，最主要的是把他们留在这里，很多人最终会自己离开。}
#{1551}{}{What do you mean?}
{1551}{}{什么意思？}
#{1600}{}{[He answers you while constantly entering commands into the computer, his eyes never leaving the screen.] I'll release BX-8 in the normals' cells. It is a nerve agent that'll kill them in under a minute. The records of the death of all donors the Rebirth currently has will then be sent to the entire complex. The smarter ones will realize that waiting for the dreamed-of day of rebirth for everyone is hardly sensible anymore.}
{1600}{}{[他一边回答你，一边不断地向电脑输入命令，他的眼睛从不离开屏幕]我会在正常人的细胞里释放BX-8。是神经毒剂能在一分钟内杀死他们。所有捐赠者的死亡记录将被发送到整个建筑群。更聪明的人会意识到，等待每个人梦寐以求的重生之日已经不再明智。}
#{1601}{}{But you can't just kill so many people!}
{1601}{}{但你不能只杀这么多人！}
#{1602}{}{Good idea. Get to it.}
{1602}{}{好主意。开始吧。}
#{1650}{}{I have no doubts the guards will react to that. But I'm ready to die. After all, I lost my life all those years ago in the vault. I was young, strong, smart and ambitions, on my way to becoming the next overseer. But none of it came to pass because of that stupid accident. Since then I've been driven on by the vision of one day being like I was before. But now I know I was naive.}
{1650}{}{我毫不怀疑警卫会对此作出反应。但我已经准备好去死了。毕竟，那些年前我在金库里失去了生命。我年轻，强壮，聪明，雄心勃勃，正在成为下一个监工的路上。但这一切都不是因为那次愚蠢的事故。从那时起，我就被有一天会像以前一样的愿景所驱使。但现在我知道我太天真了。}
#{1651}{}{I won't let you kill them!}
{1651}{}{我不会让你杀了他们！}
#{1652}{}{Well, if that's the way you want it.}
{1652}{}{好吧，如果你想这样的话。}
#{1700}{}{[He turns to you with utter determination in his eyes.] And what will you do to stop me?! If you attack me, the guards will deem it an act of aggression and protect me. Perhaps you could try to go tell someone, but this will all be over before you find anyone. Apart from that I strongly doubt anyone would believe you. There's not a thing you can do. If you don't wish to die with me, get out of my way.}
{1700}{}{[他转向你，眼睛里充满了决心]你要怎么阻止我？！如果你攻击我，卫兵会认为这是侵略行为，并保护我。也许你可以试着去告诉别人，但在你找到任何人之前这一切都会结束的。除此之外，我强烈怀疑有人会相信你。你无能为力。如果你不想和我一起死，滚开。}
#{1701}{}{I'll stop you no matter what the cost!}
{1701}{}{不管付出什么代价，我都会阻止你！}
#{1702}{}{OK, I'm out of your way.}
{1702}{}{好吧，我不挡你的路。}
#{1750}{}{Don't waste time and ask.}
{1750}{}{不要浪费时间去问。}
#{1751}{}{The research trying to achieve a lowered number of required donors for rebirth is just a ruse then?}
{1751}{}{试图降低再生所需供体数量的研究只是一个诡计？}
#{1752}{}{Are you one of those who came here first after the Savior?}
{1752}{}{你是在救世主之后第一个来到这里的人吗？}
#{1753}{}{How is it even possible to cure mutations? It almost sounds like scientific mumbo-jumbo.}
{1753}{}{怎么可能治愈突变呢？听起来像是科学上的胡言乱语。}
#{1754}{}{There is nothing more I need to know.}
{1754}{}{我再也不需要知道什么了。}
#{1800}{}{Of course I have it with me. Here it is. [He shows you his access card.]}
{1800}{}{我当然带着它。给你。[他给你看他的通行证。]}
#{1801}{}{Oh no, that's a fake! Somebody must've stolen your card and planted this fake in its stead. If you don't mind, I'll take that and get you a new access card immediately.}
{1801}{}{哦，不，那是假的！一定是有人偷了你的卡，用这个假的来代替它。如果你不介意的话，我会马上给你换一张新的出入卡。}
#{1850}{}{Of course, here's the fake card. Make sure to investigate this immediately. It's unacceptable to have unauthorized people wandering around here!}
{1850}{}{当然，这是假卡。一定要立即调查。让未经授权的人在这里闲逛是不可接受的！}
#{1851}{}{Don't worry.}
{1851}{}{别担心。}
#{1900}{}{I hope you've become engaged in our research. We must crack this problem. It's in our own interest.}
{1900}{}{我希望你参与了我们的研究。我们必须解决这个问题。这符合我们自己的利益。}
#{1901}{}{Tell me about your research.}
{1901}{}{告诉我你的研究。}
#{1902}{}{I have a few important questions for you.}
{1902}{}{我有几个重要的问题要问你。}
#{1903}{}{They tell me I can get CPU card for a robot here.}
{1903}{}{他们告诉我我可以在这里买到机器人的CPU卡。}
#{1904}{}{There are suspicions that somebody's using your access card without authorization. Could you please show me you have it with you?}
{1904}{}{有人怀疑有人擅自使用了你的门禁卡。你能给我看看你带着它吗？}
#{1905}{}{Let's talk another time.}
{1905}{}{我们改天再谈吧。}
#{1906}{}{Boogoo-ooga.}
{1906}{}{博古-奥加。}
#{1950}{}{Has the security breach been resolved? We can't allow something like that to happen around here.}
{1950}{}{安全漏洞解决了吗？我们不能让这样的事情在这里发生。}
#{1951}{}{The guards took care of everything. Your new access card is on the way.}
{1951}{}{守卫们负责一切。你的新门禁卡马上就到。}
#{1952}{}{Boogoo-ooga.}
{1952}{}{博古-奥加。}
#{2000}{}{Excellent, I'm glad I don't need to waste my time on it.}
{2000}{}{太好了，我很高兴我不需要在这上面浪费时间。}
#{2001}{}{Tell me about your research.}
{2001}{}{告诉我你的研究。}
#{2002}{}{I have a few important questions for you.}
{2002}{}{我有几个重要的问题要问你。}
#{2003}{}{They tell me I can get CPU card for a robot here.}
{2003}{}{他们告诉我我可以在这里买到机器人的CPU卡。}
#{2004}{}{Let's talk another time.}
{2004}{}{我们改天再谈吧。}
#{2050}{}{As far as we know Thomas has deserted. What else could you expect from a friend of that traitor the Thirteenth? I think they were in it together from the start. Maybe he even sabotaged our work.}
{2050}{}{据我们所知，托马斯已经离开了。你还能指望十三号那个叛徒的朋友做什么？我想他们从一开始就在一起。也许他甚至破坏了我们的工作。}
#{2051}{}{I believe the pre-war scientists were successful with cloning.}
{2051}{}{我相信战前的科学家在克隆方面取得了成功。}
#{2052}{}{I thought it was the machine itself that was malfunctioning.}
{2052}{}{我以为是机器本身出了故障。}
#{2053}{}{Will there be enough donors left for everyone once you solve the problem?}
{2053}{}{一旦你解决了这个问题，会有足够的捐赠者留给每个人吗？}
#{2054}{}{I need to ask you about something else.}
{2054}{}{我要问你一些别的事。}
#{2055}{}{That's all I need to know.}
{2055}{}{我只想知道这些。}
#{2100}{}{Just because we've been unable to find a solution so far doesn't mean it doesn't exist. It must exist! The Savior is living proof! If you can't accept that, then at least stop wasting my time that I could be using towards finding a solution.}
{2100}{}{仅仅因为我们到目前为止还没有找到解决办法并不意味着它不存在。它一定存在！救世主是活生生的证明！如果你不能接受这一点，那么至少不要再浪费我的时间，我可以用来找到一个解决办法。}
#{2101}{}{But you said it yourself: You've dedicated yourself to finding the solution, and have failed. Isn't it more probable that the Savior is lying, than it is that you'll find a solution in the end by some miracle? The Thirteenth and Thomas realized this. That's why they ran away.}
{2101}{}{但你自己说的：你一直致力于寻找解决方案，但失败了。难道不是救世主撒谎的可能性比你最终会奇迹般地找到解决办法的可能性更大吗？十三和托马斯意识到了这一点。这就是他们逃跑的原因。}
#{2102}{}{Well good luck with that. The way I see it, you'll need all the luck you can get.}
{2102}{}{祝你好运。在我看来，你需要所有的运气。}
#{2150}{}{[He turns to you with utter determination in his eyes.] And what will you do to stop me?! If you attack me, the guards will deem it an act of aggression and protect me. Perhaps you could try to go tell someone, but this will all be over before you find anyone. Apart from that I strongly doubt anyone would believe you. There's not a thing you can do. If you don't wish to die with me, get out of my way.}
{2150}{}{[他转向你，眼睛里充满了决心]你要怎么阻止我？！如果你攻击我，卫兵会认为这是侵略行为，并保护我。也许你可以试着去告诉别人，但在你找到任何人之前这一切都会结束的。除此之外，我强烈怀疑有人会相信你。你无能为力。如果你不想和我一起死，滚开。}
#{2151}{}{I'll stop you no matter what the cost!}
{2151}{}{不管付出什么代价，我都会阻止你！}
#{2152}{}{OK, I'm out of your way.}
{2152}{}{好吧，我不挡你的路。}
#{2200}{}{I hope you've become engaged in our research. We must crack this problem. It's in our own interest.}
{2200}{}{我希望你参与了我们的研究。我们必须解决这个问题。这符合我们自己的利益。}
#{2201}{}{Tell me about your research.}
{2201}{}{告诉我你的研究。}
#{2202}{}{I have a few important questions for you.}
{2202}{}{我有几个重要的问题要问你。}
#{2203}{}{They tell me I can get CPU card for a robot here.}
{2203}{}{他们告诉我我可以在这里买到机器人的CPU卡。}
#{2204}{}{There are suspicions that somebody's using your access card without authorization. Could you please show me you have it with you?}
{2204}{}{有人怀疑有人擅自使用了你的门禁卡。你能给我看看你带着它吗？}
#{2205}{}{Let's talk another time.}
{2205}{}{我们改天再谈吧。}
#{2206}{}{Boogoo-ooga.}
{2206}{}{博古-奥加。}
