#{100}{}{You see practice target No. 1.}
{100}{}{你看到练习目标1了。}
#{101}{}{You see practice target No. 2.}
{101}{}{你看到练习目标2了。}
#{102}{}{You see practice target No. 3.}
{102}{}{你看到练习目标3了。}
#{200}{}{You see a robot used as a practice target for live ammunition shooting. It is marked with the number }
{200}{}{你看到一个机器人被用作实弹射击的练习靶。它标有数字}
#{201}{}{1.}
{201}{}{1}
#{202}{}{2.}
{202}{}{2}
#{203}{}{3.}
{203}{}{三。}
#{300}{}{The robot doesn't seem to want to communicate with you.}
{300}{}{机器人好像不想和你交流。}
