#{100}{}{You see a ghoul.}
{100}{}{你看到一个僵尸。}
#{200}{}{You see a Rebirth technician.}
{200}{}{你看到一个重生的技师。}
#{300}{}{Have you ever been kicked by 240 volts? I have.}
{300}{}{你曾经被240伏特的电压踢过吗？我有。}
#{301}{}{I'm busy.}
{301}{}{我很忙。}
#{302}{}{Can't you see I'm busy?}
{302}{}{你没看见我很忙吗？}
#{303}{}{There's always something to do for us.}
{303}{}{总有事情要为我们做。}
#{304}{}{What's broken down now?}
{304}{}{现在坏了什么？}
#{305}{}{I need a break.}
{305}{}{我需要休息一下。}
#{306}{}{I really don't know what to do first.}
{306}{}{我真的不知道该先做什么。}
#{307}{}{Damn, I've lost the chip.}
{307}{}{该死，我把芯片弄丢了。}
#{308}{}{The whole complex is filled with amazing pre-war technology.}
{308}{}{整个建筑群充满了令人惊叹的战前科技。}
#{309}{}{I prefer making things over mending them.}
{309}{}{我宁愿做东西也不愿修理。}
#{310}{}{Sometimes you just got to give it a kick. If it's your lucky day.}
{310}{}{有时候你就得踢它一下。如果今天是你的幸运日。}
#{311}{}{I can make anything work.}
{311}{}{我什么都能行。}
#{312}{}{I'll bet the glowing ones are just loitering around on Blue 6.}
{312}{}{我敢打赌那些发光的只是在蓝6上徘徊。}
#{313}{}{Have you ever been kicked by 240 volts? I have.}
{313}{}{你曾经被240伏特的电压踢过吗？我有。}
#{314}{}{Don't be startled by Chris. He's fine.}
{314}{}{别被克里斯吓到了。他很好。}
#{315}{}{The machine is a wonder.}
{315}{}{这台机器是个奇迹。}
