#{100}{}{You see a ghoul.}
{100}{}{你看到一个僵尸。}
#{150}{}{You see Tramell.}
{150}{}{你看到特拉梅尔了。}
#{200}{}{You see a ghoul in power armor. He's watching several screens and giving out orders to soldiers simultaneously.}
{200}{}{你看到一个穿着强力盔甲的僵尸。他在看几个屏幕，同时向士兵发出命令。}
#{250}{}{You see Tramell, the Rebirth's second in command.}
{250}{}{你看特拉梅尔，重生的二把手。}
#{300}{}{According to reports, the Thirteenth is somewhere in the area. He must be finally apprehended!}
{300}{}{据报道，13号就在这个地区的某个地方。他一定会被逮捕的！}
#{301}{}{There are still too many caravans getting through to Albuquerque.}
{301}{}{去阿尔伯克基的商队还是太多了。}
#{302}{}{The reports on Albuquerque are insufficient. We need detailed information about their defensive capabilities.}
{302}{}{关于阿尔伯克基的报道不够充分。我们需要关于他们防御能力的详细信息。}
#{303}{}{Each group of Hunters leaving the city must be attacked. They won't know rest.}
{303}{}{每一组离开城市的猎人都必须受到攻击。他们不会知道其他的。}
#{304}{}{We will have to reach further into the north in order to catch more normals.}
{304}{}{为了捕捉更多的常态，我们必须深入北方。}
#{305}{}{It will be necessary to speed up the training of new recruits.}
{305}{}{必须加快新兵的培训。}
#{306}{}{According to reports, the Thirteenth is somewhere in the area. She must be finally apprehended!}
{306}{}{据报道，13号就在这个地区的某个地方。她一定会被逮捕的！}
#{400}{}{We have an intruder!}
{400}{}{我们有入侵者！}
#{401}{}{Let's deal with this quickly.}
{401}{}{让我们快点处理。}
#{402}{}{You're trapped.}
{402}{}{你被困住了。}
#{403}{}{Now you won't escape.}
{403}{}{现在你逃不掉了。}
#{500}{}{Yes? [You can't see through the power armor visor, but it's clear he didn't even look at you. His attention is directed toward several screens with maps and reports.]}
{500}{}{对？[你看不透动力装甲面罩，但很明显他甚至没看你一眼。他的注意力集中在几个有地图和报告的屏幕上。]}
#{501}{}{Who are you?}
{501}{}{你是谁？}
#{502}{}{Nothing.}
{502}{}{没有什么。}
#{503}{}{Hoohaa!}
{503}{}{呼哈！}
#{504}{}{Oogh.}
{504}{}{哦。}
#{550}{}{Tramell, the Rebirth's second in command. If you're not coming to me with something important, you'd better leave me to my duties.}
{550}{}{特拉梅尔，重生的二把手。如果你不带重要的东西来找我，你最好让我履行我的职责。}
#{551}{}{And who's the first in command?}
{551}{}{谁是一把手？}
#{552}{}{So you're in charge of all the Rebirth's actions in the wasteland?}
{552}{}{所以你负责荒地里所有重生的行动？}
#{600}{}{The Savior, of course. He takes care of the whole of the Rebirth, but he can hardly look after every detail, despite his efforts. He only makes the most important decisions, the individual military operations are under my command.}
{600}{}{当然是救世主。他照顾整个重生，但他几乎不能照顾每一个细节，尽管他的努力。他只做最重要的决定，个人军事行动由我指挥。}
#{601}{}{So you're in charge of all the Rebirth's actions in the wasteland?}
{601}{}{所以你负责荒地里所有重生的行动？}
#{650}{}{That's correct! Caravan ambushes, searching for pre-war technologies, catching normals and so on. But the most pressing matter at present is apprehending the Thirteenth.}
{650}{}{没错！商队埋伏，寻找战前技术，捕捉常态等等。但目前最紧迫的问题是抓紧第十三条。}
#{651}{}{Why ambush caravans?}
{651}{}{为什么要伏击商队？}
#{652}{}{How successful have you been searching for pre-war technologies?}
{652}{}{你在寻找战前技术方面有多成功？}
#{653}{}{How's catching normals going?}
{653}{}{恢复正常了吗？}
#{654}{}{Any new developments about the Thirteenth?}
{654}{}{十三号有什么新进展吗？}
#{655}{}{I can see you're busy, I'll leave you alone.}
{655}{}{我看得出你很忙，我不理你了。}
#{700}{}{Supplies, why else? Apart from all kinds of useless stuff, they also transport food and water and it's always wise to have sufficient supplies of those. If we're lucky, we run into a caravan transporting weapons. And most importantly, this way we restrict the supplying of Albuquerque. We don't catch many normals from the caravans, they defend them very aggressively, so we usually have to shoot them.}
{700}{}{供应，为什么？除了各种无用的东西，他们还运输食物和水，有足够的食物和水总是明智的。如果幸运的话，我们会撞上一辆运送武器的大篷车。最重要的是，这样我们就限制了阿尔伯克基的供应。我们从大篷车上抓不到多少正常人，他们非常积极地保护他们，所以我们通常不得不射杀他们。}
#{701}{}{I'm not sure the profit from caravans is high enough to justify acting like filthy raiders.}
{701}{}{我不确定商队的利润是否高到足以证明自己是个肮脏的袭击者。}
#{702}{}{Tell me about Albuquerque.}
{702}{}{告诉我阿尔伯克基的事。}
#{703}{}{And how about catching normals? How's that going?}
{703}{}{那捕捉正常人呢？怎么样了？}
#{704}{}{How successful have you been searching for pre-war technologies?}
{704}{}{你在寻找战前技术方面有多成功？}
#{705}{}{Any new developments about the Thirteenth?}
{705}{}{十三号有什么新进展吗？}
#{706}{}{Any new developments about the Thirteenth?}
{706}{}{十三号有什么新进展吗？}
#{707}{}{Thanks for your time.}
{707}{}{谢谢你的时间。}
#{750}{}{Thanks to the cooperation between Vault-Tec and the Army, we managed to retrieve from local records the locations of several military objects in this area. We successfully reclaimed all functional equipment. Two objects were already empty. My bet is they were cleaned by the Mutant Hunters.}
{750}{}{由于金库科技公司和军队的合作，我们设法从地方记录中检索到这个地区的几个军事物体的位置。我们成功地回收了所有的功能设备。两个对象已经是空的。我敢打赌他们是被变种猎人清除的。}
#{751}{}{Why search for more technologies when you have this complex?}
{751}{}{既然你有这么复杂的技术，为什么还要寻找更多的技术呢？}
#{752}{}{One military warehouse not far from here probably didn't appear in the records. It was claimed by the Hunters.}
{752}{}{离这里不远的一个军事仓库可能没有出现在记录中。它被猎人们认领了。}
#{753}{}{And how's catching normals going?}
{753}{}{捕捉正常人怎么样了？}
#{754}{}{Any new developments about the Thirteenth?}
{754}{}{十三号有什么新进展吗？}
#{755}{}{Any new developments about the Thirteenth?}
{755}{}{十三号有什么新进展吗？}
#{756}{}{Thanks for your time.}
{756}{}{谢谢你的时间。}
#{800}{}{What, are you impatient?! You will have to wait for the day of rebirth, there are many new people joining us. Despite that, we managed to catch a large number of normals. With the exception of insignificant local tribes, Albuquerque's the only place left standing. Once we take care of it, we will continue north.}
{800}{}{什么，你不耐烦吗？！你要等待重生的那一天，有很多新人加入我们。尽管如此，我们还是设法捕捉到了大量的常态。除了微不足道的当地部落，阿尔伯克基是唯一的地方留下来。一旦我们搞定了，我们就继续向北走。}
#{801}{}{What about the local tribes?}
{801}{}{当地的部落呢？}
#{802}{}{Tell me about Albuquerque.}
{802}{}{告诉我阿尔伯克基的事。}
#{803}{}{And how successful have you been searching for pre-war technologies?}
{803}{}{你在寻找战前技术方面有多成功？}
#{804}{}{Any new developments about the Thirteenth?}
{804}{}{十三号有什么新进展吗？}
#{805}{}{Thanks for your time.}
{805}{}{谢谢你的时间。}
#{850}{}{We have taken care of the largest settlements a long time ago. Now all that remains are small groups hiding in caves and similar places. If our troops run into such a group, they naturally apprehend them, but it's not viable to search for them, the savages have a high level of irradiation.}
{850}{}{我们很早以前就处理过最大的定居点。现在剩下的都是藏在洞穴和类似地方的小团体。如果我们的军队遇到这样一个群体，他们自然会逮捕他们，但搜寻他们是不可行的，野蛮人有很高的辐射水平。}
#{851}{}{Tell me about Albuquerque.}
{851}{}{告诉我阿尔伯克基的事。}
#{852}{}{And how successful have you been searching for pre-war technologies?}
{852}{}{你在寻找战前技术方面有多成功？}
#{853}{}{Any new developments about the Thirteenth?}
{853}{}{十三号有什么新进展吗？}
#{854}{}{Any new developments about the Thirteenth?}
{854}{}{十三号有什么新进展吗？}
#{855}{}{Thanks for your time.}
{855}{}{谢谢你的时间。}
#{900}{}{A city full of normals who've managed to escape from us. Though some of them are normals originally from a vault there. Perfect donors for use in rebirth. And most importantly, it's the main base of the Mutant Hunters. They must be destroyed first, before they destroy us.}
{900}{}{一个充满了从我们这里逃出来的普通人的城市。尽管其中一些是来自于金库的法线。完美的捐赠者用于重生。最重要的是，它是变异猎人的主要基地。在他们消灭我们之前，必须先消灭他们。}
#{901}{}{How come Albuquerque's still resisting?}
{901}{}{为什么阿尔伯克基还在反抗？}
#{902}{}{And how successful have you been searching for pre-war technologies?}
{902}{}{你在寻找战前技术方面有多成功？}
#{903}{}{Any new developments about the Thirteenth?}
{903}{}{十三号有什么新进展吗？}
#{904}{}{Any new developments about the Thirteenth?}
{904}{}{十三号有什么新进展吗？}
#{905}{}{Thanks for your time.}
{905}{}{谢谢你的时间。}
#{950}{}{I have personally led two attacks against the city, but it has always resisted. We underestimated them in our first attack; the vault dwellers had the advantage of advanced weapons. During the second attack, the Hunters had already set up their base there. We knew that, though, so we charged with a tremendous force, managed to get into the city, but they fended us off. I won't allow that to happen the third time! Nothing will stop us, whatever the losses. Albuquerque will eventually fall!}
{950}{}{我亲自领导了两次对该市的袭击，但它一直在抵抗。我们在第一次进攻中低估了他们；地下室居民拥有先进武器的优势。在第二次进攻中，猎人们已经在那里建立了基地。不过，我们知道这一点，所以我们用巨大的力量冲进了城市，但他们把我们挡开了。我不允许第三次发生这种事！不管损失有多大，没有什么能阻止我们。阿尔伯克基终将沦陷！}
#{951}{}{Whatever the cost?}
{951}{}{不管付出什么代价？}
#{952}{}{What's your approach against Albuquerque at present?}
{952}{}{你现在对阿尔伯克基有什么办法？}
#{953}{}{And how successful have you been searching for pre-war technologies?}
{953}{}{你在寻找战前技术方面有多成功？}
#{954}{}{Any new developments about the Thirteenth?}
{954}{}{十三号有什么新进展吗？}
#{955}{}{Any new developments about the Thirteenth?}
{955}{}{十三号有什么新进展吗？}
#{956}{}{Thanks for your time.}
{956}{}{谢谢你的时间。}
#{1000}{}{Yes! Albuquerque must fall. I've made the mistake of minding the losses once. We had a good chance of prevailing with the second attack. But we would have paid with great losses to our side, so I commanded a retreat. The Savior said I should've finished the attack and, as usually, he was right. All of my men were willing to die for our cause, they would have done so without hesitation. Moreover, the Hunters are still out there, so our losses have possibly been even greater.}
{1000}{}{对！阿尔伯克基必须倒下。我犯了一个错误，把损失放在心上。我们很有可能在第二次进攻中获胜。但是我们会付出巨大的损失，所以我命令撤退。救世主说我应该完成攻击，像往常一样，他是对的。我所有的人都愿意为我们的事业献身，他们会毫不犹豫地这样做。而且，猎人还在外面，所以我们的损失可能更大。}
#{1001}{}{Did the Savior really say that?}
{1001}{}{救世主真的这么说吗？}
#{1002}{}{What's your approach against Albuquerque at present?}
{1002}{}{你现在对阿尔伯克基有什么办法？}
#{1003}{}{And how successful have you been searching for pre-war technologies?}
{1003}{}{你在寻找战前技术方面有多成功？}
#{1004}{}{Any new developments about the Thirteenth?}
{1004}{}{十三号有什么新进展吗？}
#{1005}{}{Any new developments about the Thirteenth?}
{1005}{}{十三号有什么新进展吗？}
#{1006}{}{Thanks for your time.}
{1006}{}{谢谢你的时间。}
#{1050}{}{From the moment we found out about the Hunters and their establishment of a camp in Albuquerque, the Savior insisted on a second attack as soon as we gather enough force. Even then he must have comprehended the threat the Mutant Hunters represent.}
{1050}{}{从我们发现猎人和他们在阿尔伯克基建立营地的那一刻起，救世主就坚持要在我们集结足够的兵力后发动第二次进攻。即便如此，他也一定理解了变异猎人所代表的威胁。}
#{1051}{}{What's your approach against Albuquerque at present?}
{1051}{}{你现在对阿尔伯克基有什么办法？}
#{1052}{}{And how successful have you been searching for pre-war technologies?}
{1052}{}{你在寻找战前技术方面有多成功？}
#{1053}{}{Any new developments about the Thirteenth?}
{1053}{}{十三号有什么新进展吗？}
#{1054}{}{Any new developments about the Thirteenth?}
{1054}{}{十三号有什么新进展吗？}
#{1055}{}{Thanks for your time.}
{1055}{}{谢谢你的时间。}
#{1100}{}{We're trying to isolate the city and prevent new people and caravans from entering. We catch normals who wander too far from it. But that usually means we get into fights with Mutant Hunters. Why are you asking me all these things? If you don't know about them, you're not supposed to! Stop wasting my time!}
{1100}{}{我们正试图隔离这座城市，阻止新的人和商队进入。我们抓到了远离它的正常人。但这通常意味着我们会和变种猎人打架。你为什么问我这些事？如果你不知道他们，你就不应该知道！别再浪费我的时间了！}
#{1101}{}{I was just interested in...}
{1101}{}{我只是对。。。}
#{1102}{}{OK, I'm leaving.}
{1102}{}{好的，我要走了。}
#{1150}{}{He was heading to the northwest the whole time, but something's changed recently. According to reports, he's turned around. He's even visiting cities. He would avoid them before. I suspect he aims to destroy us, maybe even by working with the Mutant Hunters. He's capable of such things.}
{1150}{}{他一直在往西北方向走，但最近有些事情发生了变化。据报道，他已经转身了。他甚至还去参观城市。他以前会避开他们。我怀疑他是想消灭我们，甚至可能是和变种猎人合作。他有这种能力。}
#{1151}{}{Tell me something about the Thirteenth.}
{1151}{}{告诉我一些关于十三号的事。}
#{1152}{}{You've mentioned the Hunters, what do you know about Albuquerque?}
{1152}{}{你提到过猎人，你对阿尔伯克基了解多少？}
#{1153}{}{And how successful have you been searching for pre-war technologies?}
{1153}{}{你在寻找战前技术方面有多成功？}
#{1154}{}{And how's catching normals going?}
{1154}{}{捕捉正常人怎么样了？}
#{1155}{}{Thanks for your time.}
{1155}{}{谢谢你的时间。}
#{1200}{}{I knew him personally, not particularly well, though. He was one of many under my command, but he was a capable and devoted warrior. He's still highly skilled and experienced, he's been successful in avoiding us so far.}
{1200}{}{不过，我对他个人并不太了解。他是我手下许多人中的一个，但他是一个能干而忠诚的战士。他仍然有很高的技能和经验，到目前为止他成功地避开了我们。}
#{1201}{}{You've mentioned the Hunters, what do you know about Albuquerque?}
{1201}{}{你提到过猎人，你对阿尔伯克基了解多少？}
#{1202}{}{And how successful have you been searching for pre-war technologies?}
{1202}{}{你在寻找战前技术方面有多成功？}
#{1203}{}{And how's catching normals going?}
{1203}{}{捕捉正常人怎么样了？}
#{1204}{}{Thanks for your time.}
{1204}{}{谢谢你的时间。}
#{1250}{}{Just interested? [Only now he looks at you properly.] Who are you anyway? Show me your face!}
{1250}{}{只是感兴趣？[现在他才正眼看着你]你到底是谁？给我看看你的脸！}
#{1251}{}{[Uncover your face.]}
{1251}{}{[揭开你的脸。]}
#{1252}{}{I'm nobody of importance. I won't take any more of your time.}
{1252}{}{我不是什么重要人物。我不会再占用你的时间了。}
#{1253}{}{To hell with hiding. I'll kill you just like the rest of the ghouls!}
{1253}{}{去他妈的躲起来。我会像其他僵尸一样杀了你！}
#{1300}{}{Show me your face! Guards, help him with it!}
{1300}{}{给我看看你的脸！卫兵，帮帮他！}
#{1301}{}{That's OK, I can manage on my own. [Show your face.]}
{1301}{}{没关系，我自己能应付。[露脸]}
#{1302}{}{You leave me no choice but to kill all of you.}
{1302}{}{你让我别无选择，只能杀了你们所有人。}
#{1350}{}{The Thirteenth. I should've known you'd try to get in. Shoot him!}
{1350}{}{十三号。我早该知道你想进去的。开枪打他！}
#{1351}{}{[Defend yourself.]}
{1351}{}{[为自己辩护。]}
#{1400}{}{You dare to question the decision of the command, even the Savior himself?! Who are you really?! [Only now does he look at you properly.]}
{1400}{}{你敢质疑指挥部的决定，甚至连救世主自己都不敢？！你到底是谁？！[直到现在他才正确地看着你。]}
#{1401}{}{You can guess. [Show your face.]}
{1401}{}{你可以猜。[露脸]}
#{1402}{}{I'm nobody of importance. I won't take any more of your time.}
{1402}{}{我不是什么重要人物。我不会再占用你的时间了。}
#{1403}{}{To hell with hiding. I'll kill you just like the rest of the ghouls!}
{1403}{}{去他妈的躲起来。我会像其他僵尸一样杀了你！}
#{1450}{}{Any technological advantage, especially when it comes to arms, can bring us closer to the day of rebirth. If you intend to subject me to more stupid questions, I suggest you leave.}
{1450}{}{任何技术优势，尤其是在武器方面，都能让我们更接近重生的那一天。如果你想问我更多愚蠢的问题，我建议你离开。}
#{1451}{}{I'd like to ask about catching normals.}
{1451}{}{我想问一下捕捉正常人的问题。}
#{1452}{}{How about some news about the Thirteenth?}
{1452}{}{关于十三号的新闻怎么样？}
#{1453}{}{How about some news about the Thirteenth?}
{1453}{}{关于十三号的新闻怎么样？}
#{1454}{}{I apologize, goodbye.}
{1454}{}{我道歉，再见。}
#{1500}{}{What nonsense is this? Where did you get that information? And who are you anyway? [Only now he looks at you properly.] Show me your face!}
{1500}{}{这是什么废话？你从哪里得到的信息？你到底是谁？[现在他才正眼看着你]给我看看你的脸！}
#{1501}{}{[Uncover your face.]}
{1501}{}{[揭开你的脸。]}
#{1502}{}{I'm nobody of importance. I won't take any more of your time.}
{1502}{}{我不是什么重要人物。我不会再占用你的时间了。}
#{1503}{}{To hell with hiding. I'll kill you just like the rest of the ghouls!}
{1503}{}{去他妈的躲起来。我会像其他僵尸一样杀了你！}
#{1550}{}{Yes? [You can't see through the power armor visor, but it's clear he didn't even look at you. His attention is directed toward several screens with maps and reports.]}
{1550}{}{对？[你看不透动力装甲面罩，但很明显他甚至没看你一眼。他的注意力集中在几个有地图和报告的屏幕上。]}
#{1551}{}{You mentioned you're the Rebirth's second in command. Who's the first?}
{1551}{}{你说过你是重生的二把手。谁是第一个？}
#{1552}{}{You mentioned caravan ambushes. Why do that?}
{1552}{}{你提到了商队伏击。为什么这么做？}
#{1553}{}{How successful have you been searching for pre-war technologies?}
{1553}{}{你在寻找战前技术方面有多成功？}
#{1554}{}{How's catching normals going?}
{1554}{}{恢复正常了吗？}
#{1555}{}{Any new developments about the Thirteenth?}
{1555}{}{十三号有什么新进展吗？}
#{1556}{}{Any new developments about the Thirteenth?}
{1556}{}{十三号有什么新进展吗？}
#{1557}{}{Nothing.}
{1557}{}{没有什么。}
#{1600}{}{The Savior, of course. He takes care of the whole of the Rebirth, but he can hardly look after every detail, despite his efforts. He only makes the most important decisions, the individual military operations are under my command.}
{1600}{}{当然是救世主。他照顾整个重生，但他几乎不能照顾每一个细节，尽管他的努力。他只做最重要的决定，个人军事行动由我指挥。}
#{1601}{}{You mentioned caravan ambushes. Why do that?}
{1601}{}{你提到了商队伏击。为什么这么做？}
#{1602}{}{How successful have you been searching for pre-war technologies?}
{1602}{}{你在寻找战前技术方面有多成功？}
#{1603}{}{How's catching normals going?}
{1603}{}{恢复正常了吗？}
#{1604}{}{Any new developments about the Thirteenth?}
{1604}{}{十三号有什么新进展吗？}
#{1605}{}{Any new developments about the Thirteenth?}
{1605}{}{十三号有什么新进展吗？}
#{1606}{}{In that case, I won't waste any more of your time.}
{1606}{}{那样的话，我就不会再浪费你的时间了。}
#{1650}{}{I don't have time for nonsense, don't waste my time.}
{1650}{}{我没有时间胡说，别浪费我的时间。}
#{1651}{}{Hoohaa!}
{1651}{}{呼哈！}
#{1652}{}{Oogh.}
{1652}{}{哦。}
#{1700}{}{Damn, how did you get here, anyway?! [Only now he looks at you properly.] Who are you, really?! Guards, take that thing off his head!}
{1700}{}{该死，你怎么来的？！[现在他才正眼看着你]你是谁，真的？！卫兵，把那东西从他头上拿下来！}
#{1701}{}{[Let them uncover your face.]}
{1701}{}{[让他们揭开你的面纱。]}
#{1702}{}{Grrhaaah!}
{1702}{}{啊哈！}
#{1750}{}{Tramell, the Rebirth's second in command. If you're not coming to me with something important, you'd better leave me to my duties.}
{1750}{}{特拉梅尔，重生的二把手。如果你不带重要的东西来找我，你最好让我履行我的职责。}
#{1751}{}{And who's the first in command?}
{1751}{}{谁是一把手？}
#{1752}{}{So you're in charge of all the Rebirth's actions in the wasteland?}
{1752}{}{所以你负责荒地里所有重生的行动？}
#{1800}{}{That's correct! Caravan ambushes, searching for pre-war technologies, catching normals and so on. But the most pressing matter at present is apprehending the Thirteenth.}
{1800}{}{没错！商队埋伏，寻找战前技术，捕捉常态等等。但目前最紧迫的问题是抓紧第十三条。}
#{1801}{}{Why ambush caravans?}
{1801}{}{为什么要伏击商队？}
#{1802}{}{How successful have you been searching for pre-war technologies?}
{1802}{}{你在寻找战前技术方面有多成功？}
#{1803}{}{How's catching normals going?}
{1803}{}{恢复正常了吗？}
#{1804}{}{Any new developments about the Thirteenth?}
{1804}{}{十三号有什么新进展吗？}
#{1805}{}{I can see you're busy, I'll leave you alone.}
{1805}{}{我看得出你很忙，我不理你了。}
#{1850}{}{What, are you impatient?! You will have to wait for the day of rebirth, there are many new people joining us. Despite that, we managed to catch a large number of normals. With the exception of insignificant local tribes, Albuquerque's the only place left standing. Once we take care of it, we will continue north.}
{1850}{}{什么，你不耐烦吗？！你要等待重生的那一天，有很多新人加入我们。尽管如此，我们还是设法捕捉到了大量的常态。除了微不足道的当地部落，阿尔伯克基是唯一的地方留下来。一旦我们搞定了，我们就继续向北走。}
#{1851}{}{What about the local tribes?}
{1851}{}{当地的部落呢？}
#{1852}{}{Tell me about Albuquerque.}
{1852}{}{告诉我阿尔伯克基的事。}
#{1853}{}{And how successful have you been searching for pre-war technologies?}
{1853}{}{你在寻找战前技术方面有多成功？}
#{1854}{}{Any new developments about the Thirteenth?}
{1854}{}{十三号有什么新进展吗？}
#{1855}{}{Thanks for your time.}
{1855}{}{谢谢你的时间。}
#{1900}{}{She was heading to the northwest the whole time, but something's changed recently. According to reports, she's turned around. She's even visiting cities. She would avoid them before. I suspect she aims to destroy us, maybe even by working with the Mutant Hunters. She's capable of such things.}
{1900}{}{她一直在往西北方向走，但最近有些事情改变了。据报道，她已经转身了。她甚至还去了很多城市。她以前会避开他们。我怀疑她是想消灭我们，甚至可能通过与变种猎人合作。她有这种能力。}
#{1901}{}{Tell me something about the Thirteenth.}
{1901}{}{告诉我一些关于十三号的事。}
#{1902}{}{You've mentioned the Hunters, what do you know about Albuquerque?}
{1902}{}{你提到过猎人，你对阿尔伯克基了解多少？}
#{1903}{}{And how successful have you been searching for pre-war technologies?}
{1903}{}{你在寻找战前技术方面有多成功？}
#{1904}{}{And how's catching normals going?}
{1904}{}{捕捉正常人怎么样了？}
#{1905}{}{Thanks for your time.}
{1905}{}{谢谢你的时间。}
#{1950}{}{I knew her personally, not particularly well, though. She was one of many under my command, but she was a capable and devoted warrior. She's still highly skilled and experienced, she's been successful in avoiding us so far.}
{1950}{}{不过，我对她不是很了解。她是我手下许多人中的一个，但她是一个能干而忠诚的战士。她仍然有很高的技能和经验，到目前为止她成功地避开了我们。}
#{1951}{}{You've mentioned the Hunters, what do you know about Albuquerque?}
{1951}{}{你提到过猎人，你对阿尔伯克基了解多少？}
#{1952}{}{And how successful have you been searching for pre-war technologies?}
{1952}{}{你在寻找战前技术方面有多成功？}
#{1953}{}{And how's catching normals going?}
{1953}{}{捕捉正常人怎么样了？}
#{1954}{}{Thanks for your time.}
{1954}{}{谢谢你的时间。}
#{2000}{}{Show me your face! Guards, help her with it!}
{2000}{}{给我看看你的脸！卫兵，帮帮她！}
#{2001}{}{That's OK, I can manage on my own. [Show your face.]}
{2001}{}{没关系，我自己能应付。[露脸]}
#{2002}{}{You leave me no choice but to kill all of you.}
{2002}{}{你让我别无选择，只能杀了你们所有人。}
#{2050}{}{The Thirteenth. I should've known you'd try to get in. Shoot her!}
{2050}{}{十三号。我早该知道你想进去的。开枪打她！}
#{2051}{}{[Defend yourself.]}
{2051}{}{[为自己辩护。]}
#{2100}{}{What nonsense is this? Where did you get that information? And who are you anyway? [Only now he looks at you properly.] Show me your face!}
{2100}{}{这是什么废话？你从哪里得到的信息？你到底是谁？[现在他才正眼看着你]给我看看你的脸！}
#{2101}{}{[Uncover your face.]}
{2101}{}{[揭开你的脸。]}
#{2102}{}{I'm nobody of importance. I won't take any more of your time.}
{2102}{}{我不是什么重要人物。我不会再占用你的时间了。}
#{2103}{}{To hell with hiding. I'll kill you just like the rest of the ghouls!}
{2103}{}{去他妈的躲起来。我会像其他僵尸一样杀了你！}
#{2150}{}{Damn, how did you get here, anyway?! [Only now he looks at you properly.] Who are you, really?! Guards, take that thing off her head!}
{2150}{}{该死，你怎么来的？！[现在他才正眼看着你]你是谁，真的？！卫兵，把那东西从她头上拿开！}
#{2151}{}{[Let them uncover your face.]}
{2151}{}{[让他们揭开你的面纱。]}
#{2152}{}{Grrhaaah!}
{2152}{}{啊哈！}
