#{100}{}{You see a nightkin.}
{100}{}{你看到了夜猫子。}
#{150}{}{You see Dernus.}
{150}{}{你看到德努斯了。}
#{200}{}{You see a nightkin, he's a fearsome creature.}
{200}{}{你看夜猫子，他是个可怕的生物。}
#{250}{}{You see Dernus, leader of the group of supermutants.}
{250}{}{你看德努斯，超级变种人的首领。}
#{500}{}{Human?! What are you doing here? You best speak the truth!}
{500}{}{人类？！你在这里干什么？你最好说实话！}
#{501}{}{I'm just an explorer, I'm interested in this place.}
{501}{}{我只是个探险家，我对这个地方很感兴趣。}
#{502}{}{Mutant Hunters sent me here, they need some information from the computer on the lower level.}
{502}{}{变种猎人派我来这里，他们需要一些来自下层电脑的信息。}
#{503}{}{I need to find the location of the Rebirth base. I was told it's recorded in the computer on the lower level.}
{503}{}{我要找到重生基地的位置。有人告诉我这是在下层电脑里录的。}
#{504}{}{Don't you see that I'm with the Children of the Cathedral?! Let me pass! In the name of the Master!}
{504}{}{你没看到我和主教大教堂在一起吗？！让我过去！以主人的名义！}
#{505}{}{I... umm... Well, I'll just be leaving now.}
{505}{}{我 ……嗯……好吧，我现在就走。}
#{506}{}{Ugly monster, eww!}
{506}{}{丑陋的怪物，哇！}
#{550}{}{It was a mistake to come here. [He's about to open fire.]}
{550}{}{来这儿是个错误。[他正要开火。]}
#{551}{}{You can't just kill me like that!}
{551}{}{你不能就这样杀了我！}
#{552}{}{I'll kill you!}
{552}{}{我要杀了你！}
#{600}{}{Sure I can.}
{600}{}{我当然可以。}
#{601}{}{Shit.}
{601}{}{倒霉。}
#{650}{}{You're telling me that a Hunter spy is strolling in here just like that?}
{650}{}{你是说一个猎人间谍就这样进来了？}
#{651}{}{I've got nothing to do with the Hunters. I told them that I'd get the information for them because I needed the location of this place. The truth is, I just need to find out where the Rebirth base is.}
{651}{}{我和猎人没关系。我告诉他们我会为他们得到信息，因为我需要这个地方的位置。事实是，我只需要找出重生的基地在哪里。}
#{652}{}{I've got nothing to do with the Hunters. I told them that I'd get the information for them because I needed the location of this place. The truth is, I just need to find out where the Rebirth base is.}
{652}{}{我和猎人没关系。我告诉他们我会为他们得到信息，因为我需要这个地方的位置。事实是，我只需要找出重生的基地在哪里。}
#{653}{}{I'm not a Hunter, I just have to get the information for them.}
{653}{}{我不是猎手，我只需要为他们获取信息。}
#{654}{}{Actually, yes, and you should do something about the security here.}
{654}{}{事实上，是的，你应该对这里的安全做点什么。}
#{700}{}{It doesn't matter if you are with them or not. You shouldn't have come here.}
{700}{}{不管你是否和他们在一起。你不该来这里。}
#{701}{}{Shit.}
{701}{}{倒霉。}
#{750}{}{It doesn't matter if you are with them or not. You shouldn't have come here.}
{750}{}{不管你是否和他们在一起。你不该来这里。}
#{751}{}{Shit.}
{751}{}{倒霉。}
#{800}{}{You will die.}
{800}{}{你会死的。}
#{801}{}{Shit.}
{801}{}{倒霉。}
#{850}{}{Funny. You clearly were never a member of the Children, they wouldn't try such a stupid thing, giving orders to a nightkin. What do you really want here?}
{850}{}{好笑。很明显，你从来都不是孩子们的一员，他们不会做这种蠢事，对夜猫子发号施令。你到底想要什么？}
#{851}{}{I'm an explorer, I'm interested in this place.}
{851}{}{我是个探险家，我对这个地方很感兴趣。}
#{852}{}{Mutant Hunters sent me here, they need some information from the computer on the lower level.}
{852}{}{变种猎人派我来这里，他们需要一些来自下层电脑的信息。}
#{853}{}{I need to find the location of the Rebirth base. I was told it's recorded in the computer on the lower level.}
{853}{}{我要找到重生基地的位置。有人告诉我这是在下层电脑里录的。}
#{854}{}{I think I better hit the road again.}
{854}{}{我想我最好再上路。}
#{900}{}{Funny. You clearly were never a member of the Children, they wouldn't try such a stupid thing, giving orders to a nightkin. What do you really want here?}
{900}{}{好笑。很明显，你从来都不是孩子们的一员，他们不会做这种蠢事，对夜猫子发号施令。你到底想要什么？}
#{901}{}{I'm an explorer, I'm interested in this place.}
{901}{}{我是个探险家，我对这个地方很感兴趣。}
#{902}{}{Mutant Hunters sent me here, they need some information from the computer on the lower level.}
{902}{}{变种猎人派我来这里，他们需要一些来自下层电脑的信息。}
#{903}{}{I need to find the location of the Rebirth base. I was told it's recorded in the computer on the lower level.}
{903}{}{我要找到重生基地的位置。有人告诉我这是在下层电脑里录的。}
#{904}{}{I think I better hit the road again.}
{904}{}{我想我最好再上路。}
#{950}{}{I can't let you leave, nor do I want to.}
{950}{}{我不能让你离开，我也不想。}
#{951}{}{Shit.}
{951}{}{倒霉。}
#{1000}{}{Why do you need to know that?}
{1000}{}{你为什么要知道这些？}
#{1001}{}{I lost my memory. I have a reason to believe I've got something to do with the Rebirth, because they're trying to kill me. I hope to find out who I am once I'm there.}
{1001}{}{我失去了记忆。我有理由相信我和重生有关，因为他们想杀了我。我希望一旦到了那里就知道我是谁。}
#{1002}{}{I lost my memory. I have a reason to believe I've got something to do with the Rebirth, because they're trying to kill me. I hope to find out who I am once I'm there.}
{1002}{}{我失去了记忆。我有理由相信我和重生有关，因为他们想杀了我。我希望一旦到了那里就知道我是谁。}
#{1003}{}{No reason, just out of curiosity.}
{1003}{}{没有理由，只是出于好奇。}
#{1004}{}{I want to destroy the Rebirth.}
{1004}{}{我要毁灭重生。}
#{1050}{}{I don't believe you human! I'm sure you're just a Hunter spy. But it doesn't really matter.}
{1050}{}{我不相信你是人类！我相信你只是个猎手间谍。但这并不重要。}
#{1051}{}{Shit.}
{1051}{}{倒霉。}
#{1100}{}{Curiosity can lead you to trouble. And it did.}
{1100}{}{好奇心会给你带来麻烦。它做到了。}
#{1101}{}{Shit.}
{1101}{}{倒霉。}
#{1150}{}{So you're just a poor fella infected by the Hunters' madness, then.}
{1150}{}{所以你只是一个被猎人的疯狂感染的可怜的家伙。}
#{1151}{}{But...}
{1151}{}{但是……}
#{1200}{}{So you're just a poor girl infected by the Hunters' madness, then.}
{1200}{}{所以你只是一个被猎人的疯狂感染的可怜女孩。}
#{1201}{}{But...}
{1201}{}{但是……}
#{1250}{}{You? Lost memory... It would explain a lot. [He looks at you for a moment, thinking.] Yes, you could be him. But I have to be sure.}
{1250}{}{你呢？失去记忆……这可以解释很多。[他看了你一会儿，心想]是的，你可能就是他。但我必须确定。}
#{1251}{}{What? What do you know about me? What are you talking about?!}
{1251}{}{什么？你对我了解多少？你在说什么？！}
#{1300}{}{You? Lost memory... It would explain a lot. [He looks at you for a moment, thinking.] Yes, you could be her. But I have to be sure.}
{1300}{}{你呢？失去记忆……这可以解释很多。[他看了你一会儿，心想]是的，你可能就是她。但我必须确定。}
#{1301}{}{What? What do you know about me? What are you talking about?!}
{1301}{}{什么？你对我了解多少？你在说什么？！}
#{1350}{}{For now you should know that you'll find the information you're looking for here, but I won't reveal any more until you do as told. We have use of you, at the very least it will prove that you're not a member of the Mutant Hunters.}
{1350}{}{现在你应该知道你会在这里找到你想要的信息，但我不会透露更多，直到你告诉我。我们利用了你，至少可以证明你不是变种猎人。}
#{1351}{}{What do you want me to do?}
{1351}{}{你要我做什么？}
#{1352}{}{No! Tell me everything you know, now!}
{1352}{}{不！告诉我你知道的一切，现在！}
#{1353}{}{But I AM a member of Hunters!}
{1353}{}{但我是猎人的一员！}
#{1400}{}{In that case, you'll die.}
{1400}{}{那样的话，你会死的。}
#{1401}{}{We'll see who will die, mutant.}
{1401}{}{我们看看谁会死，变种人。}
#{1450}{}{Either you promise that you'll do it, or I'll kill you. I don't usually bargain with humans about their death. Make up your mind quickly.}
{1450}{}{要么你保证你会做，要么我杀了你。我通常不会和人类讨价还价他们的死。快下定决心。}
#{1451}{}{All right then, what do you want me to do?}
{1451}{}{好吧，那你想让我怎么做？}
#{1452}{}{I better kill you.}
{1452}{}{我最好杀了你。}
#{1500}{}{I want to see Sebastian, the leader of Hunters, dead. I want to be personally at his execution and I want to do it myself. Your task is to bring him here. With minimum escort.}
{1500}{}{我想看到猎人首领塞巴斯蒂安死了。我想亲自去执行他的死刑，我想自己去做。你的任务是把他带到这里来。最少的护送。}
#{1501}{}{Why do you want to kill him?}
{1501}{}{你为什么要杀他？}
#{1502}{}{All right, I'll bring him here. But how should I do that?}
{1502}{}{好吧，我带他来。但我该怎么做呢？}
#{1503}{}{I won't do that.}
{1503}{}{我不会那么做的。}
#{1504}{}{Sebastian is already dead, I killed him.}
{1504}{}{塞巴斯蒂安已经死了，我杀了他。}
#{1505}{}{Sebastian is already dead, I killed him.}
{1505}{}{塞巴斯蒂安已经死了，我杀了他。}
#{1550}{}{Do I have to have a reason for killing a human? But in this case, I do. Humans don't deserve to live and Hunters are the worst of the humans. They hate all mutants, and for them mutant is everybody who differs from "normal." I saw what they did in this base. They called it "research and interrogation." But it was torture. Sebastian must die.}
{1550}{}{我必须有杀人的理由吗？但在这种情况下，我知道。人类不配活下去，猎人是人类中最坏的。他们讨厌所有的变种人，对他们来说，变种人就是所有不同于“正常人”的人。他们称之为“调查和审讯”，但这是折磨。塞巴斯蒂安必须死。}
#{1551}{}{Why just him?}
{1551}{}{为什么只有他？}
#{1552}{}{Why don't you attack Albuquerque and destroy their base?}
{1552}{}{你为什么不攻击阿尔伯克基摧毁他们的基地？}
#{1553}{}{All right, I'll bring him here. But how should I do that?}
{1553}{}{好吧，我带他来。但我该怎么做呢？}
#{1554}{}{I won't bring Sebastian here for an execution.}
{1554}{}{我不会带塞巴斯蒂安来执行死刑。}
#{1600}{}{He's their leader, and he believes all that stuff. I saw his speeches here on records. Without him the Hunters won't be able to stay organized for long.}
{1600}{}{他是他们的领袖，他相信所有这些。我在这里看过他的演讲记录。没有他，猎人们将无法长期保持组织。}
#{1601}{}{Why don't you attack Albuquerque and destroy their base?}
{1601}{}{你为什么不攻击阿尔伯克基摧毁他们的基地？}
#{1602}{}{All right, I'll bring him here. But how should I do that?}
{1602}{}{好吧，我带他来。但我该怎么做呢？}
#{1603}{}{I won't bring Sebastian here for an execution.}
{1603}{}{我不会带塞巴斯蒂安来执行死刑。}
#{1650}{}{We could. And we might even succeed, but at what cost? There isn't enough of us in our group to survive that kind of attack. We don't intend to die in this land. Death awaits us further east. Death of a lot of people, and eventually our death as well.}
{1650}{}{我们可以。我们甚至可能成功，但代价是什么？我们小组里没有足够的人能在那样的袭击中幸存下来。我们不想死在这片土地上。死亡在更远的东方等待着我们。很多人的死亡，最终我们的死亡。}
#{1651}{}{Why do you only care about Sebastian?}
{1651}{}{你为什么只关心塞巴斯蒂安？}
#{1652}{}{All right, I'll bring him here. But how should I do that?}
{1652}{}{好吧，我带他来。但我该怎么做呢？}
#{1653}{}{I won't bring Sebastian here for an execution.}
{1653}{}{我不会带塞巴斯蒂安来执行死刑。}
#{1700}{}{Tell him that we're not here anymore. We'll hide, so he'll believe it when he arrives. Just get him in front of the entrance to the building. Then he'll be trapped.}
{1700}{}{告诉他我们不在了。我们会躲起来，等他来的时候他会相信的。把他带到大楼门口。那他就被困住了。}
#{1701}{}{Understood.}
{1701}{}{理解。}
#{1750}{}{Now leave. If I see you here again without Sebastian, I'll kill you.}
{1750}{}{现在离开。如果我再看到你在这里没有塞巴斯蒂安，我会杀了你。}
#{1751}{}{OK.}
{1751}{}{好 啊。}
#{1800}{}{You were supposed to bring Sebastian here. I gave you a chance, human, and you blew it.}
{1800}{}{你应该带塞巴斯蒂安来的。我给了你一个机会，人类，你却搞砸了。}
#{1801}{}{But...}
{1801}{}{但是……}
#{1802}{}{Huh?}
{1802}{}{嗯？}
#{1850}{}{You were supposed to bring Sebastian here. I gave you a chance, human, and you blew it.}
{1850}{}{你应该带塞巴斯蒂安来的。我给了你一个机会，人类，你却搞砸了。}
#{1851}{}{But..}
{1851}{}{但是。。}
#{1852}{}{Huh?}
{1852}{}{嗯？}
#{1900}{}{Good, you kept your word, human. Take this power armor that we found in this base, as a reward for your help. It's useless for us supermutants. And now, tell me - do you remember your own name?}
{1900}{}{很好，你信守诺言，人类。拿着我们在基地找到的这件强力盔甲，作为对你帮助的奖励。对我们这些超级变种人来说没用。现在，告诉我-你还记得你自己的名字吗？}
#{1901}{}{Yes, my name is }
{1901}{}{是的，我的名字是}
#{1902}{}{.}
{1902}{}{.}
#{1903}{}{Me }
{1903}{}{我}
#{1904}{}{!}
{1904}{}{!}
#{1905}{}{Good, you kept your word, human. Now, tell me - do you remember your own name?}
{1905}{}{很好，你信守诺言，人类。现在，告诉我-你还记得你自己的名字吗？}
#{1950}{}{So it is indeed you. My name is Dernus. You could say that I lead this group of supermutants.}
{1950}{}{所以它确实是你。我叫德努斯。你可以说我领导着这群超级变种人。}
#{1951}{}{I'd be happy if you could finally tell me what you know about me.}
{1951}{}{如果你能告诉我你对我的了解我会很高兴的。}
#{1952}{}{I'd be happy if you could finally tell me what you know about me.}
{1952}{}{如果你能告诉我你对我的了解我会很高兴的。}
#{2000}{}{You can find the information that you're looking for in the computer on the lower level. You should know, however, that Hunters got it by torturing a captured ghoul. The ghoul is still alive, but we weren't able to heal him, just keep him alive for a while longer to prolong his suffering. He wanted it that way.}
{2000}{}{你可以在下层的电脑里找到你要找的信息。不过，你应该知道，猎人们是通过折磨一个被抓获的僵尸而得逞的。僵尸还活着，但我们没能治愈他，只是让他再活一段时间来延长他的痛苦。他想这样。}
#{2001}{}{You can find the information that you're looking for in the computer on the lower level. You should know, however, that Hunters got it by torturing a captured ghoul. The ghoul is still alive, but we weren't able to heal him, just keep him alive for a while longer to prolong his suffering. He wanted it that way.}
{2001}{}{你可以在下层的电脑里找到你要找的信息。不过，你应该知道，猎人们是通过折磨一个被抓获的僵尸而得逞的。僵尸还活着，但我们没能治愈他，只是让他再活一段时间来延长他的痛苦。他想这样。}
#{2002}{}{Where can I find him?}
{2002}{}{我在哪能找到他？}
#{2050}{}{He lies in his cell on lower level. We disabled the force fields. You can walk here freely, nobody is going to get in your way. Hurry up, he doesn't have much time left.}
{2050}{}{他躺在下层的牢房里。我们禁用了力场。你可以自由地走在这里，没有人会妨碍你的。快点，他没多少时间了。}
#{2051}{}{Can I ask you something else?}
{2051}{}{我能问你点别的吗？}
#{2052}{}{I'm going there right away.}
{2052}{}{我马上就去。}
#{2100}{}{Good, you kept your word, human. Take this power armor that we found in this base, as a reward for your help. It's useless for us supermutants. And now, tell me - do you remember your own name?}
{2100}{}{很好，你信守诺言，人类。拿着我们在基地找到的这件强力盔甲，作为对你帮助的奖励。对我们这些超级变种人来说没用。现在，告诉我-你还记得你自己的名字吗？}
#{2101}{}{Yes, my name is }
{2101}{}{是的，我的名字是}
#{2102}{}{.}
{2102}{}{.}
#{2103}{}{Me }
{2103}{}{我}
#{2104}{}{!}
{2104}{}{!}
#{2105}{}{Good, you kept your word, human. Now, tell me - do you remember your own name?}
{2105}{}{很好，你信守诺言，人类。现在，告诉我-你还记得你自己的名字吗？}
#{2150}{}{Speak.}
{2150}{}{说吧。}
#{2151}{}{What is this place?}
{2151}{}{这是什么地方？}
#{2152}{}{Who exactly are you?}
{2152}{}{你到底是谁？}
#{2153}{}{What's your plan?}
{2153}{}{你的计划是什么？}
#{2154}{}{You talked to the ghoul, so you know what's going on here. Are you going to do something about it?}
{2154}{}{你和僵尸谈过了，所以你知道这里发生了什么。你打算做点什么吗？}
#{2155}{}{I have to go.}
{2155}{}{我得走了。}
#{2156}{}{Ugh.}
{2156}{}{啊。}
#{2200}{}{It looks like this building is just a part of an old military complex. There was originally some warehouse here. According to their records the Hunters discovered this place a few years ago. Thus they obtained a lot of high quality military equipment. That's all I know. We didn't let anybody live long enough to talk. It's already enough to know what they did with this place.}
{2200}{}{看起来这座建筑只是一座旧军事建筑的一部分。这里原来有个仓库。根据他们的记录，猎人几年前发现了这个地方。因此他们获得了许多高质量的军事装备。我只知道这些。我们没有让任何人活得足够长来说话。知道他们对这个地方做了什么已经足够了。}
#{2201}{}{What did they do with this place?}
{2201}{}{他们对这个地方做了什么？}
#{2202}{}{I want to ask about something else.}
{2202}{}{我想问些别的事。}
#{2203}{}{I have to go.}
{2203}{}{我得走了。}
#{2250}{}{They built a scientific station here. They called it "research and interrogation." Never mind what they called it, it was just unrelenting torture.}
{2250}{}{他们在这里建了一个科学站。他们称之为“研究和审讯”。不管他们怎么称呼，这只是无情的折磨。}
#{2251}{}{Why here?}
{2251}{}{为什么在这里？}
#{2252}{}{I want to ask about something else.}
{2252}{}{我想问些别的事。}
#{2253}{}{I have to go.}
{2253}{}{我得走了。}
#{2300}{}{I don't know. I assume it would attract some unwanted attention in Albuquerque.}
{2300}{}{我不知道。我想它会在阿尔伯克基引起一些不必要的注意。}
#{2301}{}{I want to ask about something else.}
{2301}{}{我想问些别的事。}
#{2302}{}{I have to go.}
{2302}{}{我得走了。}
#{2350}{}{You've never heard of supermutants? Our father created us in perfection. He is known as the Master. He had a vision of peace, of the Unity. But humans destroyed everything, especially the Children of the Cathedral. The actions of the Vault Dweller were just the consequences.}
{2350}{}{你从没听说过超级变种人？我们的父亲完美地创造了我们。他被称为大师。他憧憬着和平，憧憬着团结。但是人类摧毁了一切，尤其是主教大教堂。金库居民的行为只是后果。}
#{2351}{}{Tell me about the Master.}
{2351}{}{告诉我师父的事。}
#{2352}{}{Tell me about the Children of the Cathedral.}
{2352}{}{告诉我主教大教堂。}
#{2353}{}{Tell me about the Vault Dweller.}
{2353}{}{跟我说说那个地下室的人。}
#{2354}{}{I want to ask about something else.}
{2354}{}{我想问些别的事。}
#{2355}{}{I have to go.}
{2355}{}{我得走了。}
#{2400}{}{The Master wanted to eliminate the differences that make us fight against each other by creating single perfect race. We are the result of that vision, or at least what's left of it. We are better than humans in any aspect, but even if we can live to a much higher age, we can't reproduce. Our kind is destined to extinction because of the scientists of the Children of the Cathedral who concealed this problem from the Master, and didn't even care to solve it.}
{2400}{}{大师想通过创造一个完美的种族来消除使我们互相争斗的差异。我们是这个愿景的结果，或者至少是它留下的东西。我们在任何方面都比人类优秀，但即使我们能活到更高的年龄，我们也无法繁衍后代。我们这种人注定要灭绝，因为大教堂孩子们的科学家们向大师隐瞒了这个问题，甚至不想解决它。}
#{2401}{}{No offense, but most supermutants don't seem that smart.}
{2401}{}{无意冒犯，但大多数超级变种人看起来没那么聪明。}
#{2402}{}{Tell me about the Children of the Cathedral.}
{2402}{}{告诉我主教大教堂。}
#{2403}{}{I want to ask about something else.}
{2403}{}{我想问些别的事。}
#{2404}{}{I have to go.}
{2404}{}{我得走了。}
#{2450}{}{Yes. [You can sense bitterness in his voice.] Unfortunately, the virus that changes people into supermutants reacts adversely with tissues damaged by radiation. That omnipresent reminder of destruction that humans brought upon themselves caused many supermutants to have damaged minds, and to not remember anything from their previous lives.}
{2450}{}{对。[你可以从他的声音中感受到痛苦]不幸的是，这种病毒会使人变成超级变种，对受辐射损伤的组织产生不良反应。人类给自己带来的毁灭的无所不在的提醒，导致许多超级变种人的大脑受损，不再记得他们前世的任何东西。}
#{2451}{}{And you, do you remember something?}
{2451}{}{你还记得什么吗？}
#{2452}{}{I want to ask about something else.}
{2452}{}{我想问些别的事。}
#{2453}{}{I have to go.}
{2453}{}{我得走了。}
#{2500}{}{I come from a vault, I remember quite a lot. Fear, jealousy, constant desire to possess and the resulting competition, anger... and hatred. We learned that again, with the death of our Master.}
{2500}{}{我来自金库，我记得很多。恐惧，嫉妒，持续的占有欲和由此产生的竞争，愤怒……还有仇恨。随着主人的去世，我们又学到了这一点。}
#{2501}{}{What do you mean by that?}
{2501}{}{你这是什么意思？}
#{2502}{}{I want to ask about something else.}
{2502}{}{我想问些别的事。}
#{2503}{}{I have to go.}
{2503}{}{我得走了。}
#{2550}{}{The Master created us. He was like a father to us, and even something more. A human with an independent mind can't understand something like that. He offered a better direction for mankind and they destroyed him for that. His death led us to hatred towards humans. We charged against them furiously, even if we never felt any hatred towards them before.}
{2550}{}{主人创造了我们。他对我们来说就像个父亲，甚至更多。一个有独立思想的人不能理解那样的事情。他为人类提供了一个更好的方向，他们为此摧毁了他。他的死使我们憎恨人类。尽管我们以前从未对他们怀恨在心，但我们还是猛烈地向他们发起了攻击。}
#{2551}{}{Do you still hate humans so much?}
{2551}{}{你还那么恨人类吗？}
#{2552}{}{I want to ask about something else.}
{2552}{}{我想问些别的事。}
#{2553}{}{I have to go.}
{2553}{}{我得走了。}
#{2600}{}{I don't think I could ever forgive humans, but I'm already tired from the perpetual fighting. Humankind will destroy itself anyway, as it has almost done a few times already. But a mind damaged by the virus during transformation into a supermutant is controlled solely by emotions. The hatred towards humans is the only thing that keeps most of my brothers going forward. That's the reason why a lot of people will die during our journey to the east, before we settle down.}
{2600}{}{我不认为我能原谅人类，但我已经厌倦了长期的战斗。人类无论如何都会毁灭自己，就像它已经做过几次的那样。但是在转化为超级变种的过程中，被病毒破坏的大脑完全由情绪控制。对人类的仇恨是唯一能让我的大多数兄弟继续前进的东西。这就是为什么很多人会在我们去东方的旅途中，在我们安顿下来之前死去。}
#{2601}{}{What exactly are your plans?}
{2601}{}{你的计划是什么？}
#{2602}{}{I want to ask about something else.}
{2602}{}{我想问些别的事。}
#{2603}{}{I have to go.}
{2603}{}{我得走了。}
#{2650}{}{You've never heard of supermutants? Our father created us in perfection. He is known as the Master. He had a vision of peace, of the Unity. But humans destroyed everything, especially the Children of the Cathedral. The actions of the Vault Dweller were just the consequences.}
{2650}{}{你从没听说过超级变种人？我们的父亲完美地创造了我们。他被称为大师。他憧憬着和平，憧憬着团结。但是人类摧毁了一切，尤其是主教大教堂。金库居民的行为只是后果。}
#{2651}{}{Tell me about the Master.}
{2651}{}{告诉我师父的事。}
#{2652}{}{Tell me about the Children of the Cathedral.}
{2652}{}{告诉我主教大教堂。}
#{2653}{}{Tell me about the Vault Dweller.}
{2653}{}{跟我说说那个地下室的人。}
#{2654}{}{I want to ask about something else.}
{2654}{}{我想问些别的事。}
#{2655}{}{I have to go.}
{2655}{}{我得走了。}
#{2700}{}{The Master wanted to give humans a choice to join the Unity, not to force them violently. That's why he created the church of the Children of the Cathedral, whose objectives were same as his. Through this church it was possible to voluntarily join the Unity.}
{2700}{}{大师想要给人类一个选择加入统一，而不是暴力地强迫他们。这就是为什么他创建了主教大教堂的教堂，其目标和他的一样。通过这个教会可以自愿加入联合会。}
#{2701}{}{What went wrong?}
{2701}{}{出什么事了？}
#{2702}{}{I want to ask about something else.}
{2702}{}{我想问些别的事。}
#{2703}{}{I have to go.}
{2703}{}{我得走了。}
#{2750}{}{Religion is the best way to control people. Most of the Children's "churchmen" didn't long for the Unity, they just wanted the power and the comfort their position provided. The same thing that the Master was trying to eradicate thrived right by his side and was also behind his downfall. Some supermutants even today would obey a human just because he's wearing the robe of the Children. But we were never supposed to be their servants. On the contrary, they should be worshipping us, because we were what they should crave to become.}
{2750}{}{宗教是控制人的最好方式。大多数孩子们的“教士”并不渴望团结，他们只想要他们的地位所提供的力量和安慰。同样的事情，大师正试图消除蓬勃发展的权利在他的身边，也是他的垮台背后。即使在今天，有些超级变种人也会因为人类穿着孩子们的长袍而服从人类。但我们不应该是他们的仆人。相反，他们应该崇拜我们，因为我们是他们渴望成为的。}
#{2751}{}{And what about the Vault Dweller?}
{2751}{}{那个地下室的人呢？}
#{2752}{}{I want to ask about something else.}
{2752}{}{我想问些别的事。}
#{2753}{}{I have to go.}
{2753}{}{我得走了。}
#{2800}{}{The Vault Dweller is the human who killed the Master. I can't feel anything good towards him, but his acts are understandable. He saw the true face of the Children of the Cathedral, and he was aware that supermutants will come to an end within a generation. He did what he had to do to protect not only his vault, but all humankind as well.}
{2800}{}{地下室的居住者就是杀死主人的人。我对他没有好感，但他的行为是可以理解的。他看到了大教堂里孩子们的真实面目，他意识到超级变种人将在一代人之内走向灭亡。他做了他必须做的，不仅保护他的金库，而且保护全人类。}
#{2801}{}{I want to ask about something else.}
{2801}{}{我想问些别的事。}
#{2802}{}{I have to go.}
{2802}{}{我得走了。}
#{2850}{}{We want to travel far east. To find places that are hard to reach for humans, where they could barely survive. Places with strong radiation, which doesn't affect us. And there will we settle down, to live there, far from all the humans, for the rest of our lives.}
{2850}{}{我们想去远东旅行。去寻找人类难以到达的地方，在那里他们几乎无法生存。有强辐射的地方，对我们没有影响。我们将在那里安顿下来，在那里生活，远离所有的人类，度过余生。}
#{2851}{}{I want to ask about something else.}
{2851}{}{我想问些别的事。}
#{2852}{}{I have to go.}
{2852}{}{我得走了。}
#{2900}{}{That's not our fight. No supermutant will ever fight for the salvation of the humankind, even if the threat of their destruction comes from such an absurd reason. It is up to them if they succumb to this or some other threat, or if they'll destroy themselves in the future.}
{2900}{}{那不是我们的战斗。没有一个超级变种人会为拯救人类而战斗，即使他们的毁灭威胁来自这样一个荒谬的理由。这取决于他们是否屈服于这种或其他威胁，或者他们是否会在未来毁灭自己。}
#{2901}{}{I want to ask about something else.}
{2901}{}{我想问些别的事。}
#{2902}{}{I have to go.}
{2902}{}{我得走了。}
#{2950}{}{So it is indeed you. My name is Dernus. You could say that I lead this group of supermutants. You can find the information that you're looking for in the computer on the lower level. You should know that Hunters got it by torturing a captured ghoul. The ghoul is still alive, but we weren't able to heal him, just keep him alive for a while longer to prolong his suffering. He wanted it that way. He lies in his cell on lower level. We disabled the force fields. You can walk here freely, nobody is going to get in your way. Hurry up, he doesn't have much time left.}
{2950}{}{所以它确实是你。我叫德努斯。你可以说我领导着这群超级变种人。你可以在下层的电脑里找到你要找的信息。你应该知道猎人是通过折磨一个被抓获的僵尸而得到的。僵尸还活着，但我们没能治愈他，只是让他再活一段时间来延长他的痛苦。他想这样。他躺在下层的牢房里。我们禁用了力场。你可以自由地走在这里，没有人会妨碍你的。快点，他没多少时间了。}
#{2951}{}{So it is indeed you. My name is Dernus. You could say that I lead this group of supermutants. You can find the information that you're looking for in the computer on the lower level. You should know that Hunters got it by torturing a captured ghoul. The ghoul is still alive, but we weren't able to heal him, just keep him alive for a while longer to prolong his suffering. He wanted it that way. He lies in his cell on lower level. We disabled the force fields. You can walk here freely, nobody is going to get in your way. Hurry up, he doesn't have much time left.}
{2951}{}{所以它确实是你。我叫德努斯。你可以说我领导着这群超级变种人。你可以在下层的电脑里找到你要找的信息。你应该知道猎人是通过折磨一个被抓获的僵尸而得到的。僵尸还活着，但我们没能治愈他，只是让他再活一段时间来延长他的痛苦。他想这样。他躺在下层的牢房里。我们禁用了力场。你可以自由地走在这里，没有人会妨碍你的。快点，他没多少时间了。}
#{2952}{}{Okay.}
{2952}{}{可以。}
#{3000}{}{I'm sorry, human. You may be telling the truth, but I can't trust you.}
{3000}{}{对不起，人类。你可能说的是实话，但我不能相信你。}
#{3001}{}{What? So you're going to kill me, just like that?}
{3001}{}{什么？所以你就这样杀了我？}
#{3050}{}{Good, even if it didn't all go according to plan, you kept your word, human. Take this power armor that we found in this base as a reward for your help. It's useless for us supermutants. And now, tell me - do you remember your own name?}
{3050}{}{很好，即使一切都不按计划进行，你也信守诺言，人类。把我们在这个基地找到的能量护甲作为对你帮助的奖励。对我们这些超级变种人来说没用。现在，告诉我-你还记得你自己的名字吗？}
#{3051}{}{Good, even if it didn't all go according to plan, you kept your word, human. Take this power armor that we found in this base as a reward for your help. It's useless for us supermutants. And now, tell me - do you remember your own name?}
{3051}{}{很好，即使一切都不按计划进行，你也信守诺言，人类。把我们在这个基地找到的能量护甲作为对你帮助的奖励。对我们这些超级变种人来说没用。现在，告诉我-你还记得你自己的名字吗？}
#{3052}{}{Yes, my name is }
{3052}{}{是的，我的名字是}
#{3053}{}{.}
{3053}{}{.}
#{3054}{}{Me }
{3054}{}{我}
#{3055}{}{!}
{3055}{}{!}
#{3056}{}{Good, even if it didn't all go according to plan, you kept your word, human. Now, tell me - do you remember your own name?}
{3056}{}{很好，即使一切都不按计划进行，你也信守诺言，人类。现在，告诉我-你还记得你自己的名字吗？}
#{3057}{}{Good, even if it didn't all go according to plan, you kept your word, human. Now, tell me - do you remember your own name?}
{3057}{}{很好，即使一切都不按计划进行，你也信守诺言，人类。现在，告诉我-你还记得你自己的名字吗？}
