#{100}{}{You see an older man.}
{100}{}{你看到一个老人。}
#{101}{}{You see an older man.}
{101}{}{你看到一个老人。}
#{150}{}{You see Adam.}
{150}{}{你看到亚当了。}
#{200}{}{You see an old man. He seems distrait.}
{200}{}{你看到一个老人。他似乎不信任。}
#{250}{}{You see old Adam.}
{250}{}{你看老亚当。}
#{251}{}{You see old Adam.}
{251}{}{你看老亚当。}
#{300}{}{I wonder how my brother is doing...}
{300}{}{我想知道我弟弟怎么样了……}
#{301}{}{I miss my family.}
{301}{}{我想念我的家人。}
#{350}{}{You have done me a great service. Thank you.}
{350}{}{你帮了我大忙。非常感谢。}
#{351}{}{You have done me a great service. Thank you.}
{351}{}{你帮了我大忙。非常感谢。}
#{352}{}{Get out of here!}
{352}{}{离开这里！}
#{500}{}{Greetings, I'm Adam. I heard what you went through in that cave. It's a good thing it didn't end up worse than it did. I assume you aren't planning to stay here long?}
{500}{}{你好，我是亚当。我听到你在山洞里经历了什么。幸好最后没有比现在更糟。我猜你不打算在这里呆很久吧？}
#{501}{}{Probably not. Why are you asking?}
{501}{}{可能不会。你为什么这么问？}
#{503}{}{That's none of your business.}
{503}{}{那不关你的事。}
#{504}{}{Yea, travel! Here! There!}
{504}{}{是的，旅行！在这里！在那里！}
#{550}{}{I'm glad to see you again. Have you managed to deliver my message?}
{550}{}{很高兴再次见到你。你把我的信息传达出去了吗？}
#{551}{}{Yes, and your brother immediately wrote you a reply. [Give him the letter.]}
{551}{}{是的，你哥哥马上给你回信了。[把信给他。]}
#{552}{}{I certainly did. I even have your brother's reply. But if you want it, you'll have to pay me first.}
{552}{}{我当然知道。我甚至收到了你哥哥的回信。但如果你想要的话，你得先付钱给我。}
#{553}{}{I'm working on it.}
{553}{}{我正在努力。}
#{554}{}{Me finish!}
{554}{}{让我说完！}
#{555}{}{Na-ah.}
{555}{}{不，啊。}
#{600}{}{I assume you're going to pass Kirtland... I mean Rat Hole, that's what it's called now that it's been destroyed by a local dispute. It's the closest town from here. Just like everyone else in the settlement, I'm originally from Kirtland. And like many others, I left part of my family there. [He sighs.] I'd like to know how they are doing.}
{600}{}{我猜你要经过克特兰……我是说老鼠洞，这就是它现在的名字，因为它被当地的争端摧毁了。这是离这儿最近的城镇。就像定居点里的其他人一样，我来自科特兰。和其他许多人一样，我把我的一部分家人留在了那里。[他叹了口气]我想知道他们怎么样了。}
#{601}{}{I understand. How do you want to do this?}
{601}{}{我理解。你想怎么做？}
#{602}{}{And how much are you willing to pay for this?}
{602}{}{你愿意为此付多少钱？}
#{603}{}{Your problem, not mine. I'm leaving.}
{603}{}{你的问题，不是我的。我要走了。}
#{650}{}{You don't have to get upset. I meant no harm.}
{650}{}{你不必生气。我没有恶意。}
#{651}{}{I hope so. So why are you asking, then?}
{651}{}{希望如此。那你为什么要问？}
#{653}{}{I don't care. I don't deal with people who ask too many questions.}
{653}{}{我不在乎。我不和问太多问题的人打交道。}
#{700}{}{Ehm... I'm not sure you're the right person, but I have no choice. I need something from you. [He shows you a letter.] You think you can bring this where I tell you?}
{700}{}{嗯……我不确定你是不是合适的人，但我别无选择。我需要你的东西。[他给你看了封信]你觉得你能把这个带到我告诉你的地方吗？}
#{701}{}{Can!}
{701}{}{我可以！}
#{702}{}{Eh. [Shake your head.]}
{702}{}{嗯。[摇摇头]}
#{750}{}{Good. You must bring this letter to my family in Rat Hole, which is here. [He shows you the location on a map.] Their house should be somewhere on the south end of the town. Do you understand? If you do this, you'll get a reward.}
{750}{}{很好。你必须把这封信带给我在老鼠洞的家人，也就是这里。[他给你看地图上的位置]他们的房子应该在镇的南端。你明白吗？如果你这样做，你会得到奖励。}
#{751}{}{Yea! Go now.}
{751}{}{赞成！现在就走。}
#{800}{}{I wrote them a letter. This was some time ago, but nothing much has changed since then. I'm still just trying to survive. I'd appreciate if you brought it to them. Rat Hole is here. [He shows you the location on a map.] Their house should be somewhere on the south end of the town. That's all I remember. I hope they'll still be there.}
{800}{}{我给他们写了封信。这是很久以前的事了，但从那以后没有什么变化。我只是想活下去。如果你把它带给他们我会很感激的。老鼠洞在这里。[他给你看地图上的位置]他们的房子应该在镇的南端。我只记得这些。我希望他们还在那里。}
#{801}{}{[Take the letter.] I hope so too. Goodbye for now, Adam.}
{801}{}{我也希望如此。再见，亚当。}
#{802}{}{How much will you pay me for this?}
{802}{}{你要付我多少钱？}
#{900}{}{Very well. Goodbye then.}
{900}{}{很好。那就再见了。}
#{901}{}{Bye.}
{901}{}{再见。}
#{902}{}{Bye-bye!}
{902}{}{再见！}
#{950}{}{Hi. Did you change your mind? I'd really appreciate your help.}
{950}{}{你好。你改变主意了吗？我非常感谢你的帮助。}
#{951}{}{Oh, alright. What do you want me to do?}
{951}{}{哦，好吧。你要我做什么？}
#{952}{}{Not a chance. Bye.}
{952}{}{不可能。再见。}
#{953}{}{OKAY!}
{953}{}{可以！}
#{954}{}{Na-ah! Bye.}
{954}{}{不，啊！再见。}
#{1000}{}{[He eagerly examines his brother's letter.] Thank you so much! I thought I'd never hear from them again. Here, take this. [He hands you 50 caps.] I know it's not much, but I'm afraid that's all I have.}
{1000}{}{[他急切地检查他哥哥的信]非常感谢！我想我再也听不到他们的消息了。给，拿着这个。[他递给你50顶瓶盖]我知道不多，但恐怕我只有这些了。}
#{1001}{}{Keep the caps. You need them more than I do. Goodbye, Adam.}
{1001}{}{留着瓶盖。你比我更需要他们。再见，亚当。}
#{1002}{}{That's all right. Take care.}
{1002}{}{没关系。当心。}
#{1003}{}{Thanks for nothing, you miser. Go to hell.}
{1003}{}{什么都不用谢，你这个吝啬鬼。去死吧。}
#{1050}{}{Please hurry. It's very important to me.}
{1050}{}{请快点。这对我很重要。}
#{1051}{}{Bye now.}
{1051}{}{再见。}
#{1052}{}{Hu.}
{1052}{}{胡。}
#{1100}{}{Ehm, very good. Thank you. Here is your reward. [He hands you meat jerky.] I hope you like it.}
{1100}{}{嗯，很好。非常感谢。这是你的奖赏。[他递给你肉干]希望你喜欢。}
#{1101}{}{Yay, tasty! Nom-nom!}
{1101}{}{耶，好吃！不，不！}
#{1150}{}{Ehm, I can give you five caps. Will that be enough?}
{1150}{}{嗯，我可以给你五个瓶盖。够了吗？}
#{1151}{}{Keep the caps. And please, continue.}
{1151}{}{留着瓶盖。请继续。}
#{1152}{}{[Take the caps.] So what is it you actually want me to do?}
{1152}{}{你到底想让我做什么？}
#{1153}{}{Five caps?! Screw that.}
{1153}{}{五个瓶盖？！去他的。}
#{1200}{}{First things first. I don't have much, but if you deliver the letter, I'm sure I'll be able to get some money for your reward. Don't worry about that.}
{1200}{}{第一件事。我的钱不多，但如果你把信寄出去，我肯定能得到一些钱作为你的报酬。别担心这个。}
#{1201}{}{We have a deal then.}
{1201}{}{我们说好了。}
#{1202}{}{Forget about it. You'll have to take care of this yourself.}
{1202}{}{算了吧。你得自己处理。}
#{1250}{}{Thank you. I hope you will succeed.}
{1250}{}{非常感谢。我希望你会成功。}
#{1251}{}{Goodbye.}
{1251}{}{再见。}
#{1300}{}{Thank you. I wrote a letter to my family. This was some time ago, but nothing much has changed since then. I'd appreciate if you could bring it to them. Rat Hole is here. [He shows you the location on a map.] Their house should be somewhere on the south end of the town. That's all I remember. I hope they'll still be there.}
{1300}{}{非常感谢。我给家人写了一封信。这是很久以前的事了，但从那以后没有什么变化。如果你能把它带给他们，我将不胜感激。老鼠洞在这里。[他给你看地图上的位置]他们的房子应该在镇的南端。我只记得这些。我希望他们还在那里。}
#{1301}{}{[Take the letter.] I hope so too. Goodbye, Adam.}
{1301}{}{我也希望如此。再见，亚当。}
#{1350}{}{I wrote a letter to my family. This was some time ago, but nothing much has changed since then. I'd appreciate if you brought it to them. Rat Hole is here. [He shows you the location on a map.] Their house should be somewhere on the south end of the town. That's all I remember. I hope they'll still be there.}
{1350}{}{我给家人写了一封信。这是很久以前的事了，但从那以后没有什么变化。如果你把它带给他们我会很感激的。老鼠洞在这里。[他给你看地图上的位置]他们的房子应该在镇的南端。我只记得这些。我希望他们还在那里。}
#{1351}{}{[Take the letter.] I hope so too. Goodbye, Adam.}
{1351}{}{我也希望如此。再见，亚当。}
#{1400}{}{I... Certainly. Here's 50 caps. That's all I have.}
{1400}{}{我 ……当然。这是50顶瓶盖。我只有这些了。}
#{1401}{}{That will do. [Give him the letter.] Goodbye, Adam.}
{1401}{}{那就行了。[把信给他]再见，亚当。}
#{1402}{}{[Take the caps.] Unfortunately that's not enough. You are not entitled to this letter. [Tear it up.] Who knows what he wanted to tell you. But you will never know...}
{1402}{}{很遗憾，这还不够。你无权得到这封信。谁知道他想告诉你什么。但你永远不会知道……}
#{1450}{}{Greetings, I'm Adam. I heard what you went through in that cave. It's a good thing it didn't end up worse than it did. I assume you aren't planning to stay here long?}
{1450}{}{你好，我是亚当。我听到你在山洞里经历了什么。幸好最后没有比现在更糟。我猜你不打算在这里呆很久吧？}
#{1451}{}{Probably not. Why are you asking?}
{1451}{}{可能不会。你为什么这么问？}
#{1453}{}{That's none of your business.}
{1453}{}{那不关你的事。}
#{1454}{}{Yea, travel! Here! There!}
{1454}{}{是的，旅行者！在这里！在那里！}
#{1500}{}{I wrote them a letter. This was some time ago, but nothing much has changed since then. I'm still just trying to survive. I'd appreciate if you brought it to them. Rat Hole is here. [He shows you the location on a map.] Their house should be somewhere on the south end of the town. That's all I remember. I hope they'll still be there.}
{1500}{}{我给他们写了封信。这是很久以前的事了，但从那以后没有什么变化。我只是想活下去。如果你把它带给他们我会很感激的。老鼠洞在这里。[他给你看地图上的位置]他们的房子应该在镇的南端。我只记得这些。我希望他们还在那里。}
#{1501}{}{[Take the letter.] I hope so too. Goodbye for now, Adam.}
{1501}{}{我也希望如此。再见，亚当。}
#{1502}{}{How much will you pay me for this?}
{1502}{}{你要付我多少钱？}
#{1550}{}{Hi. Did you change your mind? I'd really appreciate your help.}
{1550}{}{你好。你改变主意了吗？我非常感谢你的帮助。}
#{1551}{}{Oh, alright. What do you want me to do?}
{1551}{}{哦，好吧。你要我做什么？}
#{1552}{}{Not a chance. Bye.}
{1552}{}{不可能。再见。}
#{1553}{}{OKAY!}
{1553}{}{可以！}
#{1554}{}{Na-Ah! Bye.}
{1554}{}{不，啊！再见。}
#{1600}{}{I'm glad to see you again. Have you managed to deliver my message?}
{1600}{}{很高兴再次见到你。你把我的信息传达出去了吗？}
#{1601}{}{Yes, and your brother immediately wrote you a reply. [Give him the letter.]}
{1601}{}{是的，你哥哥马上给你回信了。[把信给他。]}
#{1602}{}{I certainly did. I even have your brother's reply. But if you want it, you'll have to pay me first.}
{1602}{}{我当然知道。我甚至收到了你哥哥的回信。但如果你想要的话，你得先付钱给我。}
#{1603}{}{I'm working on it.}
{1603}{}{我正在努力。}
#{1604}{}{Me finish!}
{1604}{}{让我说完！}
#{1605}{}{Na-ah.}
{1605}{}{不，啊。}
