#{100}{}{}
{100}{}{}
#{101}{}{}
{101}{}{}
#{110}{}{Your feet really itch.}
{110}{}{你的脚真痒。}
#{120}{}{You're developing a nasty bunion on your right foot.}
{120}{}{你的右脚长了一个讨厌的拇趾囊炎。}
#{130}{}{Your shoe feels really tight; that bunion is really getting inflamed.}
{130}{}{你的鞋摸起来很紧，那只拇趾囊炎真的发炎了。}
#{140}{}{That nasty bunion on your foot seems to have turned into an extra toe. But at least that persistent, burning itch is gone.}
{140}{}{你脚上那讨厌的包皮疙瘩好像变成了多余的脚趾。但至少那种持续的烧灼感已经消失了。}
#{141}{}{Oh my God, it's gross!}
{141}{}{天哪，太恶心了！}
#{150}{}{You gain }
{150}{}{你得到了什么}
#{151}{}{xp for getting the GECK.}
{151}{}{xp获取GECK。}
#{200}{}{You see a robot.}
{200}{}{你看到一个机器人。}
#{201}{}{You see a maintenance robot controlled via the terminal on the first floor. To disconnect, use Science on it.}
{201}{}{你看到一个维护机器人通过一楼的终端控制。要断开连接，请使用科学。}
#{202}{}{Disconnecting remote control...}
{202}{}{正在断开远程控制。。。}
#{203}{}{Damn, all of a sudden you can't make head or tail of controlling the robot. Pushing random buttons has only disconnected it.}
{203}{}{妈的，突然之间你就不能控制机器人了。随意按下按钮只会断开连接。}
#{204}{}{The robot doesn't have anything. There is nothing to drop.}
{204}{}{机器人什么都没有。没有东西可以扔。}
#{300}{}{Damn, I didn't want to do that!}
{300}{}{妈的，我不想那么做！}
#{301}{}{Stay out of my line of fire, idiot!}
{301}{}{离我的火线远点，白痴！}
#{302}{}{Sorry, my bad.}
{302}{}{对不起，我的错。}
#{400}{}{Suddenly you feel weaker, as if coming down with some disease. You lose 1 point of endurance.}
{400}{}{突然你感到虚弱，好像得了某种疾病。你失去1点耐力。}
#{401}{}{You feel weaker than usual. Clearly, something is not right with you. You lose 1 point of endurance.}
{401}{}{你觉得比平时虚弱。很明显，你有点不对劲。你失去1点耐力。}
#{402}{}{You feel extremely weak. You feel like a sneeze could kill you. And you've broken out with an ugly red-purple rash. You lose 2 points of endurance and 1 point of charisma.}
{402}{}{你觉得非常虚弱。你觉得打个喷嚏就要死了。你得了难看的红紫色皮疹。你失去2点耐力和1点魅力。}
