#{100}{}{You see a computer.}
{100}{}{你看到一台电脑。}
#{200}{}{The computer looks functional but doesn't have enough power.}
{200}{}{这台电脑看起来功能正常，但功率不够。}
#{201}{}{A slightly damaged but otherwise operational computer.}
{201}{}{一种稍有损坏但能正常工作的计算机。}
#{300}{}{The computer doesn't respond.}
{300}{}{计算机没有响应。}
#{301}{}{There is no time for this during combat.}
{301}{}{在战斗中没有时间这样做。}
#{500}{}{[The monitor is slightly cracked but still functional.] You are connected to the PROGEMA facility network. This terminal is located on the 1st floor near the backup generator 3 and 4. Enter desired command.}
{500}{}{[监视器有点破裂，但仍能正常工作。]您已连接到PROGEMA设备网络。该终端位于1楼，靠近备用发电机3和4。输入所需命令。}
#{501}{}{ - Warning! You are cleared to review classified documents. It is your duty to ensure no unauthorized personnel will access classified information.}
{501}{}{-警告！你可以查看机密文件。您有责任确保未经授权的人员不会访问机密信息。}
#{502}{}{Display information about the PROGEMA facility.}
{502}{}{显示有关PROGEMA设施的信息。}
#{503}{}{Display the main computer report log.}
{503}{}{显示主计算机报告日志。}
#{504}{}{Turn on the main computer.}
{504}{}{打开主计算机。}
#{505}{}{[Switch to 3rd floor remote-controlled robot.]}
{505}{}{[切换到三楼遥控机器人。]}
#{506}{}{Open all facility doors.}
{506}{}{打开所有设施门。}
#{507}{}{[Exit.]}
{507}{}{[退出。]}
#{508}{}{Uhm... [Leave.]}
{508}{}{嗯……[离开]}
#{550}{}{The Project: Genetic Manipulation (a.k.a. PROGEMA) research facility is operated by the United States Army. For security and confidentiality reasons, this four story facility is set deep inside the local rock formation. The main purpose of the project is the creation of a brand new organism for battle deployment. The secondary goal is to improve human abilities and characteristics for military units.}
{550}{}{该项目：基因操纵（又称PROGEMA）研究设施由美国陆军运营。出于安全和保密的原因，这座四层楼高的设施被设置在当地岩层的深处。该项目的主要目的是为作战部署创造一个全新的有机体。第二个目标是提高军事单位的人的能力和特点。}
#{551}{}{Display the main goal of the project.}
{551}{}{显示项目的主要目标。}
#{552}{}{Display the secondary goal of the project.}
{552}{}{显示项目的次要目标。}
#{553}{}{Display the main computer report log.}
{553}{}{显示主计算机报告日志。}
#{554}{}{Return to main menu.}
{554}{}{返回主菜单。}
#{555}{}{[Exit.]}
{555}{}{[退出。]}
#{600}{}{You are not cleared to review classified documents.}
{600}{}{你不能查看机密文件。}
#{601}{}{[Try to hack the computer and gain access to classified documents.]}
{601}{}{[试图入侵电脑并获取机密文件。]}
#{602}{}{Return to main menu.}
{602}{}{返回主菜单。}
#{603}{}{[Exit.]}
{603}{}{[退出。]}
#{650}{}{[You weren't successful.]}
{650}{}{[你没有成功。]}
#{651}{}{Return to main menu.}
{651}{}{返回主菜单。}
#{652}{}{[Exit.]}
{652}{}{[退出。]}
#{700}{}{[You successfully hack the computer.] You are cleared to review classified documents. It is your duty to ensure no unauthorized personnel will access classified information.}
{700}{}{[你成功入侵了电脑]你可以查看机密文件了。您有责任确保未经授权的人员不会访问机密信息。}
#{701}{}{Display the main goal of the project.}
{701}{}{显示项目的主要目标。}
#{702}{}{Display the secondary goal of the project.}
{702}{}{显示项目的次要目标。}
#{703}{}{Display the main computer report log.}
{703}{}{显示主计算机报告日志。}
#{704}{}{Return to main menu.}
{704}{}{返回主菜单。}
#{705}{}{[Exit.]}
{705}{}{[退出。]}
#{750}{}{Task: Creation of the most effective killing organism. It should be possible to deploy the organism behind enemy lines where it should be able to start operating independently. It should be able to reproduce rapidly when hidden and start eliminating human targets after reaching high individual count for combat viability. Each specimen, including the newly reproduced ones, should incorporate a kill switch to use when all enemy units have been eliminated. Such kill switches should not be easy to spot to avoid their use by the enemy. To prevent any kind of abuse, no remote control of the organism should be envisaged. The organism's behavior should be based on its innate nature.}
{750}{}{任务：创造最有效的杀灭生物。它应该可以部署在敌后的生物线，它应该能够开始独立运作。它应该能够迅速繁殖时隐藏，并开始消除人类目标后，达到高个人计数的战斗能力。每一个标本，包括新复制的标本，都应该包含一个杀戮开关，以便在消灭所有敌人单位后使用。这种杀戮开关应该不容易被发现，以避免它们被敌人使用。为了防止任何形式的滥用，不应设想对生物体进行远程控制。有机体的行为应该以其固有的本性为基础。}
#{751}{}{[Read next.]}
{751}{}{[阅读下一页。]}
#{752}{}{Display the secondary goal of the project.}
{752}{}{显示项目的次要目标。}
#{753}{}{Display the main computer report log.}
{753}{}{显示主计算机报告日志。}
#{754}{}{Return to main menu.}
{754}{}{返回主菜单。}
#{755}{}{[Exit.]}
{755}{}{[退出。]}
#{800}{}{Results: No data. Any relevant data has been deleted during a security breach to protect classified content.}
{800}{}{结果：无数据。任何相关数据都已在安全漏洞期间被删除，以保护机密内容。}
#{801}{}{Display the secondary goal of the project.}
{801}{}{显示项目的次要目标。}
#{802}{}{Display the main computer report log.}
{802}{}{显示主计算机报告日志。}
#{803}{}{Return to main menu.}
{803}{}{返回主菜单。}
#{804}{}{[Exit.]}
{804}{}{[退出。]}
#{850}{}{Task: Development of new methods for improving human skills through genetic engineering. Presently used methods include more suitable donor transplantation and microscopic implants. Disadvantages include: the need for available, compatible, and disposable donors and acceptance of microscopic implants. Newly developed methods of genetic engineering should remove both disadvantages and provide a faster development of human skills.}
{850}{}{任务：开发通过基因工程提高人类技能的新方法。目前使用的方法包括更合适的供体移植和显微植入。缺点包括：需要可用的，兼容的，一次性的捐赠者和接受显微植入物。新开发的基因工程方法应该消除这两个缺点，并提供人类技能的更快发展。}
#{851}{}{[Read next.]}
{851}{}{[阅读下一页。]}
#{852}{}{Display the main goal of the project.}
{852}{}{显示项目的主要目标。}
#{853}{}{Display the main computer report log.}
{853}{}{显示主计算机报告日志。}
#{854}{}{Return to main menu.}
{854}{}{返回主菜单。}
#{855}{}{[Exit.]}
{855}{}{[退出。]}
#{900}{}{Results: A new method was found for affecting embryos in vitro. It makes it possible to set embryo predispositions for gender, physical constitution, and mental competence. It is possible to create a subject with exceptional physical features, a high threshold of pain, high resistance to fear, and a high sense of loyalty. By applying suitable post-natal education, these individuals may grow into extremely capable and completely loyal soldiers. This method was approved for creating a new type of special-ops units and security teams for high government officials. These achievements are to be followed by continued research of unaltered human specimens in a short time.}
{900}{}{结果：发现了一种新的体外影响胚胎的方法。它使人们有可能为性别、体质和智力设定胚胎倾向。创造一个具有特殊身体特征、高痛阈、高恐惧抵抗力和高忠诚感的主体是可能的。通过适当的产后教育，这些人可以成长为非常有能力和完全忠诚的士兵。这一方法被批准用于为高级政府官员建立一种新型的特别行动单位和安全小组。在取得这些成就之后，将在短时间内继续对未改变的人类标本进行研究。}
#{901}{}{Display the main goal of the project.}
{901}{}{显示项目的主要目标。}
#{902}{}{Display the main computer report log.}
{902}{}{显示主计算机报告日志。}
#{903}{}{Return to main menu.}
{903}{}{返回主菜单。}
#{904}{}{[Exit.]}
{904}{}{[退出。]}
#{950}{}{Error! Memory data integrity compromised. Some records may be missing.}
{950}{}{错误！内存数据完整性受损。某些记录可能丢失。}
#{951}{}{[Read next.]}
{951}{}{[阅读下一页。]}
#{952}{}{Display information about the PROGEMA facility.}
{952}{}{显示有关PROGEMA设施的信息。}
#{953}{}{Return to main menu.}
{953}{}{返回主菜单。}
#{954}{}{[Exit.]}
{954}{}{[退出。]}
#{1000}{}{1. Oct. 2077 - PROGEMA facility closed and sealed on the order of the president of the USA. Military personnel moved. Scientific and auxiliary personnel evacuated to secure areas.}
{1000}{}{12077年10月-根据美国总统的命令，普罗格玛设施关闭并封存。军事人员转移。科学和辅助人员撤离到安全地区。}
#{1001}{}{[Read next.]}
{1001}{}{[阅读下一页。]}
#{1002}{}{Display information about the PROGEMA facility.}
{1002}{}{显示有关PROGEMA设施的信息。}
#{1003}{}{Return to main menu.}
{1003}{}{返回主菜单。}
#{1004}{}{[Exit.]}
{1004}{}{[退出。]}
#{1050}{}{Error! Data medium integrity compromised. Some records may be missing.}
{1050}{}{错误！数据媒体完整性受损。某些记录可能丢失。}
#{1100}{}{13. Nov. 2165 - Security detected 6 targets in vicinity. Identified as humans. Unarmed. Defense zone not compromised. No sign of aggression.}
{1100}{}{1311月2165日-安全部门在附近发现了6个目标。确认为人类。手无寸铁。防御区未被破坏。没有侵略的迹象。}
#{1150}{}{6. Jan. 2166 - Security detected 8 targets in vicinity. Identified as scorpions of unknown type with signs of radioactive mutation. Defense zone compromised. 8 targets eliminated.}
{1150}{}{61月2166日-安全部门在附近发现了8个目标。被鉴定为具有放射性突变迹象的未知类型的蝎子。防御区被破坏了。消除了8个目标。}
#{1200}{}{8. Jan. 2166 - Security detected 3 targets in vicinity. Identified as dogs. Defense zone compromised. 3 targets eliminated.}
{1200}{}{81月2166日-安全部门在附近发现了3个目标。确认为狗。防御区被破坏了。消除3个目标。}
#{1250}{}{15. Mar. 2166 - Security detected 5 targets in vicinity. Identified as humans with signs of heavy viral mutation. Armed with heavy weapons. Defense zone compromised. Evident signs of aggression. 5 targets eliminated.}
{1250}{}{153月2166日-安全部门在附近发现了5个目标。被确认为有严重病毒变异迹象的人类。装备重型武器。防御区被破坏了。明显的侵略迹象。消除了5个目标。}
#{1300}{}{20. Apr. 2166 - Security detected 26 targets in vicinity. Identified as humans. Armed with heavy weapons. Defense zone compromised. Evident signs of aggression. 3 targets eliminated. Attempt to eliminate all targets unsuccessful. Outer defense system destroyed.}
{1300}{}{204月2166日-安全部门在附近发现了26个目标。确认为人类。装备重型武器。防御区被破坏了。明显的侵略迹象。消除3个目标。试图消除所有目标失败。外部防御系统被摧毁。}
#{1350}{}{20. Apr. 2166 - Facility breach detected. Security compromised! Corresponding measures commenced. Security robots activated. 5 targets eliminated. Robots disabled. Facility occupied by the enemy. Security measures deactivated.}
{1350}{}{204月2166日-检测到设施漏洞。安全隐患！相应措施开始实施。安全机器人启动。消除了5个目标。机器人被禁用。被敌人占领的设施。安全措施已停用。}
#{1400}{}{21. Apr. 2166 - Defrosting test subject A7003 in stasis commenced. Escape of subject A7003 detected. Subject A7003 last detected on the 2nd floor. Detected wall breach on east side of the 2nd floor.}
{1400}{}{214月2166日-解冻试验受试者A7003在停滞期开始。检测到受试者A7003逃逸。受试者A7003最后一次被发现是在2楼。检测到2楼东侧的墙壁破裂。}
#{1450}{}{21. Apr. 2166 - Defrosting test subject A7002 in stasis commenced. Subject moved out of facility premises.}
{1450}{}{214月2166日-解冻试验受试者A7002在停滞期开始。受试者搬出了设施。}
#{1500}{}{21. Apr. 2166 - High number of explosions on facility premises detected. Ceiling damage on all floors. Wall damage on south side of 2nd floor. Wall damage on north and west side of the 4th floor. Reactor damage on 4th floor. Radiation leak from the reactor detected! Insufficient energy. Unable to start backup generator. Main computer shutdown.}
{1500}{}{214月2166日-在设施内发现大量爆炸。所有楼层天花板损坏。二楼南侧墙体损坏。四楼北侧和西侧墙壁损坏。四楼反应堆损坏。检测到反应堆辐射泄漏！能量不足。无法启动备份生成器。主计算机关闭。}
#{1501}{}{Display information about PROGEMA facility.}
{1501}{}{显示有关PROGEMA设施的信息。}
#{1502}{}{Return to main menu.}
{1502}{}{返回主菜单。}
#{1503}{}{[Exit.]}
{1503}{}{[退出。]}
#{1550}{}{Line corrupt, unable to connect to the main computer. Enter command into primary terminal on the 3rd floor to restart the main computer.}
{1550}{}{线路损坏，无法连接到主计算机。在三楼主终端输入命令重启主计算机。}
#{1551}{}{[Attempt to connect to a computer on the 3rd floor.]}
{1551}{}{[尝试连接到三楼的计算机。]}
#{1552}{}{Return to main menu.}
{1552}{}{返回主菜单。}
#{1553}{}{[Exit.]}
{1553}{}{[退出。]}
#{1600}{}{[All your attempts were unsuccessful. You failed to connect to any computer on the 3rd floor.]}
{1600}{}{[你所有的尝试都失败了。您未能连接到三楼的任何计算机。]}
#{1601}{}{Return to main menu.}
{1601}{}{返回主菜单。}
#{1602}{}{[Exit.]}
{1602}{}{[退出。]}
#{1650}{}{[You were unable to connect to any terminal on the 3rd floor. However, you connected to a working service robot. You should be able to operate it after a few program modifications.]}
{1650}{}{[您无法连接到三楼的任何终端。但是，您已连接到正在工作的服务机器人。经过几次程序修改后，您应该能够操作它。]}
#{1651}{}{[You were unable to connect to any terminal on the 3rd floor. However, you connected to a working service robot. You should be able to operate it after a few program modifications.]}
{1651}{}{[您无法连接到三楼的任何终端。但是，您已连接到正在工作的服务机器人。经过几次程序修改后，您应该能够操作它。]}
#{1652}{}{[Make the necessary modifications to fully operate the service bot.]}
{1652}{}{[进行必要的修改以完全运行服务bot。]}
#{1653}{}{Return to main menu.}
{1653}{}{返回主菜单。}
#{1654}{}{[Exit.]}
{1654}{}{[退出。]}
#{1700}{}{[You have reprogrammed the robot and gained full control of it. NOTE: To quit the robot interface, use SCIENCE on it.]}
{1700}{}{[你已经对机器人重新编程并完全控制了它。注意：要退出robot界面，请在其上使用SCIENCE。]}
#{1701}{}{[You have reprogrammed the robot and gained full control of it. NOTE: To quit the robot interface, use SCIENCE on it.]}
{1701}{}{[你已经对机器人重新编程并完全控制了它。注意：要退出robot界面，请在其上使用SCIENCE。]}
#{1702}{}{[Start using the service bot.]}
{1702}{}{[开始使用服务bot。]}
#{1750}{}{Safety measure! Unable to perform when the main computer is offline.}
{1750}{}{安全措施！主计算机脱机时无法执行。}
#{1751}{}{Display information about the PROGEMA facility.}
{1751}{}{显示有关PROGEMA设施的信息。}
#{1752}{}{Display the main computer report log.}
{1752}{}{显示主计算机报告日志。}
#{1753}{}{Turn on the main computer.}
{1753}{}{打开主计算机。}
#{1754}{}{[Switch to 3rd floor remote-controlled robot.]}
{1754}{}{[切换到三楼遥控机器人。]}
#{1755}{}{[Exit.]}
{1755}{}{[退出。]}
#{1800}{}{You are connected to the PROGEMA facility network. This terminal is located on the 1st floor near backup generators 3 and 4. Enter desired command.}
{1800}{}{您已连接到PROGEMA设备网络。该航站楼位于1楼，靠近备用发电机3和4。输入所需命令。}
#{1801}{}{ - Warning! You are cleared to review classified documents. It is your duty to ensure no unauthorized personnel will access classified information.}
{1801}{}{-警告！你可以查看机密文件。您有责任确保未经授权的人员不会访问机密信息。}
#{1802}{}{Display information about the PROGEMA facility.}
{1802}{}{显示有关PROGEMA设施的信息。}
#{1803}{}{Display the main computer report log.}
{1803}{}{显示主计算机报告日志。}
#{1804}{}{Turn on the main computer.}
{1804}{}{打开主计算机。}
#{1805}{}{[Switch to 3rd floor remote-controlled robot.]}
{1805}{}{[切换到三楼遥控机器人。]}
#{1806}{}{Open all facility doors.}
{1806}{}{打开所有设施门。}
#{1807}{}{[Exit.]}
{1807}{}{[退出。]}
#{1850}{}{Unauthorized personnel use detected on this terminal. As a safety precaution, this terminal has been temporarily disabled.}
{1850}{}{在此终端上检测到未经授权的人员使用。为安全起见，该终端已暂时停用。}
#{1851}{}{[Exit.]}
{1851}{}{[退出。]}
#{1852}{}{Erm? [Leave.]}
{1852}{}{呃？[离开]}
