#{100}{}{You see a security robot.}
{100}{}{你看到一个保安机器人。}
#{200}{}{You see a large security robot. It's still operational even though it's not in good shape. It must have been hit by a section of the ceiling as it collapsed.}
{200}{}{你看到一个大的安全机器人。虽然情况不好，但它仍然可以运行。它一定是在倒塌时被天花板的一部分击中的。}
#{300}{}{Unable to carry out tasks. Weapon and movement systems damaged.}
{300}{}{无法执行任务。武器和移动系统受损。}
#{301}{}{Commencing clearing the rubble.}
{301}{}{开始清理废墟。}
#{302}{}{Energy cell damage detected. Danger! Explosion immi...}
{302}{}{检测到能量电池损坏。危险！爆炸来袭。。。}
#{303}{}{::zzzt::}
{303}{}{：zzzt:：}
#{304}{}{Malfunction!}
{304}{}{故障！}
#{305}{}{Motion detected.}
{305}{}{检测到运动。}
#{306}{}{This unit is not operational.}
{306}{}{这个单位不工作。}
#{307}{}{Impending energy cell damage. Keep clear.}
{307}{}{即将发生的能量细胞损伤。保持安全。}
#{310}{}{Repairs unsuccessful.}
{310}{}{维修不成功。}
#{311}{}{This is as good as fixing this robot will get.}
{311}{}{这和修理这个机器人一样好。}
#{400}{}{The robot's weapons are crushed. But you managed to fix its legs, so it can move now.}
{400}{}{机器人的武器被压碎了。但是你把它的腿修好了，它现在可以动了。}
#{500}{}{Motion systems operational. This unit can now carry out tasks not requiring use of weapon systems.}
{500}{}{运动系统运行。该部队现在可以执行不需要使用武器系统的任务。}
#{501}{}{[Input clearing rubble from access routes.]}
{501}{}{[输入清除通道中的碎石。]}
#{502}{}{[Leave the robot alone.]}
{502}{}{[别碰机器人。]}
