#{100}{}{The inconspicuous building before you suggests the presence of an underground complex. However the entrance is blocked. Around you there are human remains and several destroyed defense towers. There must have been a fight here at some point in the past.}
{100}{}{你面前那座不显眼的建筑暗示着地下建筑群的存在。但是入口被堵住了。在你周围有人类的遗骸和几座被摧毁的防御塔。在过去的某个时候这里一定发生过一场战斗。}
#{101}{}{You hear rubble falling above you.}
{101}{}{你听到碎石从你身上落下。}
#{102}{}{You hear rubble falling above you.}
{102}{}{你听到碎石从你身上落下。}
#{103}{}{What the hell?!}
{103}{}{我勒个去？！}
#{104}{}{A section of the ceiling by the elevator has caved-in. You barely had time to jump aside to avoid it. You are trapped here. }
{104}{}{电梯旁边的天花板有一部分塌陷了。你几乎没有时间跳到一边去躲避它。你被困在这里了。}
#{105}{}{A section of the ceiling by the elevator has caved-in. You barely had time to jump aside to avoid it. You are trapped here. }
{105}{}{电梯旁边的天花板有一部分塌陷了。你几乎没有时间跳到一边去躲避它。你被困在这里了。}
#{106}{}{The others are stuck topside.}
{106}{}{其他人被困在上面。}
#{107}{}{Gabriel is stuck topside.}
{107}{}{加布里埃尔被困在上面。}
#{109}{}{Keri is stuck topside.}
{109}{}{凯里被困在上面。}
#{110}{}{Lystra is stuck topside.}
{110}{}{莱斯特拉被困在上面。}
#{111}{}{David is stuck topside.}
{111}{}{大卫被困在上面。}
#{112}{}{Pooch is stuck topside.}
{112}{}{小狗被困在上面。}
#{113}{}{Drools is stuck topside.}
{113}{}{口水粘在上面。}
#{114}{}{Wow, that was close.}
{114}{}{哇，太接近了。}
#{120}{}{Eh?!}
{120}{}{嗯？！}
#{121}{}{Uf.}
{121}{}{佛罗里达州。}
#{200}{}{The robot exploded and in doing so dispersed a part of the cave-in at the entrance to the room.}
{200}{}{机器人爆炸了，在爆炸过程中，房间入口处的一部分塌方被驱散了。}
