#{100}{}{You successfully disable the lock.}
{100}{}{您成功禁用了锁。}
#{101}{}{You fail to disable the lock.}
{101}{}{你没能解除锁。}
#{102}{}{You successfully lock the object.}
{102}{}{您已成功锁定对象。}
#{103}{}{You fail to lock the object.}
{103}{}{无法锁定对象。}
#{200}{}{ successfully disables the lock.}
{200}{}{成功禁用锁定。}
#{201}{}{ fails to disable the lock.}
{201}{}{无法禁用锁。}
#{202}{}{ successfully locks the object.}
{202}{}{成功锁定对象。}
#{203}{}{ fails to lock the object.}
{203}{}{无法锁定对象。}
#{300}{}{The explosion destroys the lock on the object.}
{300}{}{爆炸破坏了物体上的锁。}
#{301}{}{The explostion fails to remove the lock from the object.}
{301}{}{爆炸无法从对象中移除锁。}
#{400}{}{You successfully pry open the lock on the object.}
{400}{}{你成功地撬开了物体上的锁。}
#{401}{}{You fail to pry the lock on the object open.}
{401}{}{你没能撬开物体上的锁。}
#{500}{}{ successfully pries open the lock on the object.}
{500}{}{成功撬开对象上的锁。}
#{501}{}{ fails to pry the lock on the object open.}
{501}{}{无法撬开物体上的锁。}
#{600}{}{It's locked.}
{600}{}{锁上了。}
