#{100}{}{You see a shabby older man.}
{100}{}{你看到一个衣衫褴褛的老人。}
#{150}{}{You see the former gravedigger.}
{150}{}{你看到前掘墓人了。}
#{200}{}{You see a shabby older man with really pale skin.}
{200}{}{你看到一个衣衫褴褛、皮肤苍白的老人。}
#{250}{}{You see the former gravedigger, he looks terrible.}
{250}{}{你看以前的掘墓人，他看起来很可怕。}
#{500}{}{The hell, why are you bothering me?}
{500}{}{见鬼，你为什么要烦我？}
#{501}{}{Easy now, I just want to ask you something.}
{501}{}{别紧张，我只想问你一件事。}
#{502}{}{I need to unearth some graves.}
{502}{}{我要挖一些坟墓。}
#{503}{}{Sorry for the disturbance, I'll be on my way.}
{503}{}{抱歉打扰了，我马上就来。}
#{504}{}{Eba! Eba!}
{504}{}{伊巴！伊巴！}
#{505}{}{Bai.}
{505}{}{白。}
#{550}{}{Yeah? And what that'd be?}
{550}{}{是 啊？那会是什么？}
#{551}{}{Who are you?}
{551}{}{你是谁？}
#{552}{}{What do you do here?}
{552}{}{你在这里做什么？}
#{553}{}{Why do you live in this graveyard?}
{553}{}{你为什么住在这个墓地？}
#{554}{}{Father Farley has told me you might know something about Maria's funeral.}
{554}{}{法利神父告诉我你可能知道玛丽亚葬礼的一些事。}
#{555}{}{Never mind, I'll go now.}
{555}{}{没关系，我现在就去。}
#{556}{}{What do you know about Maria's funeral? Howcome even her father doesn't know where her grave is?}
{556}{}{你对玛丽亚的葬礼了解多少？为什么连她父亲都不知道她的坟墓在哪里？}
#{600}{}{I am who I am, you don't need to know anything else. Is that all?}
{600}{}{我就是我，你不需要知道别的。就这些吗？}
#{601}{}{Erm, okay, so what exactly do you do here?}
{601}{}{呃，好吧，那你到底在这里做什么？}
#{602}{}{Why do you live in this graveyard?}
{602}{}{你为什么住在这个墓地？}
#{603}{}{I want to ask something else, actually.}
{603}{}{事实上，我想问些别的问题。}
#{650}{}{What do you think? I'm scraping along; there's actually nothing else to do in this town. I ran out of money for drugs a long time ago, and since then this town seems more and more fucked up to me.}
{650}{}{你怎么认为？我在勉强度日，实际上在这个镇上没有别的事可做。我很久以前就没钱买毒品了，从那以后这个小镇对我来说越来越糟。}
#{651}{}{So why do you live in this graveyard?}
{651}{}{那你为什么住在这个墓地？}
#{652}{}{Who are you?}
{652}{}{你是谁？}
#{653}{}{I want to ask something else.}
{653}{}{我想问点别的。}
#{700}{}{Hah! That's one good question! Why? Because I got used to it. I used to be a gravedigger, but nobody cares about burials nowadays. People here immediately strip every corpse of its property and sometimes of its meat. Rats take care of the rest. Just look at these graves; not a single new one in years.}
{700}{}{没错！这是个好问题！为什么？因为我已经习惯了。我以前是个掘墓人，但现在没人关心墓葬了。这里的人们立即剥夺了每具尸体的财产，有时甚至是肉。剩下的都是老鼠。看看这些坟墓，好几年没有一个新的了。}
#{701}{}{Hmm, I've been thinking... wouldn't you like to go back to your profession for a while and dig around again?}
{701}{}{嗯，我一直在想。。。你不想回到你的职业中去，再四处挖掘一下吗？}
#{702}{}{I want to ask something else.}
{702}{}{我想问点别的。}
#{750}{}{What? Are you serious? Who do you want me to bury?}
{750}{}{什么？你是认真的吗？你要我埋葬谁？}
#{751}{}{Not to bury, but rather to unearth.}
{751}{}{不是埋葬，而是发掘。}
#{752}{}{Oh, no one. I want to ask you something else.}
{752}{}{哦，没人。我想问你点别的。}
#{800}{}{Hold on, are you talking about excavating graves?}
{800}{}{等等，你是说挖坟墓吗？}
#{801}{}{Exactly.}
{801}{}{确切地。}
#{802}{}{No, you probably didn't understand. Let's change the topic, I want to ask you something else.}
{802}{}{不，你可能不明白。我们换个话题吧，我想问你别的问题。}
#{850}{}{Hmm, okay, I have no moral dilemma about that, but it'll cost you. How about twenty per a grave. Deal?}
{850}{}{嗯，好吧，我没有道德上的两难，但这会让你付出代价的。一个坟墓二十英镑怎么样。处理？}
#{851}{}{OK, good, it's a deal.}
{851}{}{好的，很好，成交。}
#{852}{}{What about half that? Drugs are cheap here, you'll get enough anyway and we'll both be satisfied.}
{852}{}{那一半呢？这里的毒品很便宜，不管怎样你会得到足够的，我们都会满意的。}
#{853}{}{No, no. That's too much. I want to ask you something else.}
{853}{}{不，不。太过分了。我想问你点别的。}
#{900}{}{Well then, which one should I unearth?}
{900}{}{那么，我该发掘哪一个呢？}
#{901}{}{Here's 100, excavate the row of five graves.}
{901}{}{这是100个，挖掘一排五个坟墓。}
#{902}{}{Here's 50, excavate the row of five graves.}
{902}{}{这里有50个，挖掘一排五个坟墓。}
#{903}{}{One from the row of five graves.}
{903}{}{五座坟墓中的一座。}
#{904}{}{Here's 80, excavate the row of four graves.}
{904}{}{这是80瓶盖，挖一排四个坟墓。}
#{905}{}{Here's 40, excavate the row of four graves.}
{905}{}{这是40瓶盖，挖一排四个坟墓。}
#{906}{}{One from the row of four graves.}
{906}{}{四座坟墓中的一座。}
#{907}{}{Excavate the two next to each other.}
{907}{}{把两个相邻的挖出来。}
#{908}{}{Forget about it, I need to ask you something else.}
{908}{}{算了吧，我还要问你点别的。}
#{909}{}{I don't have enough cash. I'll be back later.}
{909}{}{我没有足够的现金。我一会儿回来。}
#{950}{}{Phew, done.}
{950}{}{呸，搞定了。}
#{951}{}{Thanks, lemme have a look.}
{951}{}{谢谢，让我看看。}
#{952}{}{Thanks, I need you to excavate one more.}
{952}{}{谢谢，我需要你再挖一个。}
#{1000}{}{Okay, you're right. It'll be enough. So it's a deal?}
{1000}{}{好吧，你说得对。就够了。那就这么说定了？}
#{1001}{}{Of course.}
{1001}{}{当然。}
#{1002}{}{Actually, no. I'd like to ask you something else.}
{1002}{}{事实上，没有。我想问你另外一件事。}
#{1050}{}{No, I don't think so. That'd be too much work for such little money. Dig it up yourself.}
{1050}{}{不，我不这么认为。花这么少的钱干那么多活儿。你自己挖吧。}
#{1051}{}{No, I don't think so. That'd be too much work for such little money. Dig it up yourself.}
{1051}{}{不，我不这么认为。花这么少的钱干那么多活儿。你自己挖吧。}
#{1052}{}{Okay, have it your way.}
{1052}{}{好吧，随你的便。}
#{1053}{}{Oh you bet. If you don't mind, I'd like to ask you something else.}
{1053}{}{当然了。如果你不介意的话，我想问你别的问题。}
#{1100}{}{Which one?}
{1100}{}{哪一个？}
#{1101}{}{First from the left.}
{1101}{}{从左边开始。}
#{1102}{}{Second from the left.}
{1102}{}{左边第二个。}
#{1103}{}{Third from the left.}
{1103}{}{左边第三个。}
#{1104}{}{Fourth from the left.}
{1104}{}{左四。}
#{1105}{}{Fifth from the left.}
{1105}{}{左边第五个。}
#{1106}{}{Wait, I want a grave from a different row.}
{1106}{}{等等，我想换一排坟墓。}
#{1107}{}{None, forget about it.}
{1107}{}{没有，算了吧。}
#{1150}{}{Which one?}
{1150}{}{哪一个？}
#{1151}{}{First from the left.}
{1151}{}{从左边开始。}
#{1152}{}{Second from the left.}
{1152}{}{左边第二个。}
#{1153}{}{Third from the left.}
{1153}{}{左边第三个。}
#{1154}{}{Fourth from the left.}
{1154}{}{左四。}
#{1155}{}{Wait, I want a grave from a different row.}
{1155}{}{等等，我想换一排坟墓。}
#{1156}{}{None, forget about it.}
{1156}{}{没有，算了吧。}
#{1200}{}{What should I know? I know nothing at all!}
{1200}{}{我应该知道什么？我什么都不知道！}
#{1201}{}{I think you're full of crap. You used to be a gravedigger here, and moreover you've been stuck in the graveyard to this very day, so you surely know about every funeral that's been here.}
{1201}{}{我觉得你全是废话。你以前是这里的一个掘墓人，而且你一直被困在墓地直到今天，所以你肯定知道这里的每一个葬礼。}
#{1202}{}{I won't bother you then.}
{1202}{}{那我就不打扰你了。}
#{1250}{}{Damn, do you want to get me into deep shit? [He looks around, and then continues quietly.] If I told you what I know, it could cost me my life.}
{1250}{}{妈的，你想把我弄得一团糟吗？[他环顾四周，然后静静地继续说]如果我告诉你我所知道的一切，我可能要付出生命的代价。}
#{1251}{}{If you don't tell me, it'll cost you your life for sure, because I'll kill you.}
{1251}{}{如果你不告诉我，你肯定要付出生命代价，因为我会杀了你。}
#{1252}{}{What if I give you 100 caps. Will you tell me?}
{1252}{}{如果我给你100个瓶盖呢。你能告诉我吗？}
#{1253}{}{What if I give you Buffout. Will you tell me?}
{1253}{}{如果我把它给你怎么办。你能告诉我吗？}
#{1254}{}{I don't want to put you in danger, I won't ask you anymore.}
{1254}{}{我不想让你陷入危险，我不会再问你了。}
#{1300}{}{You're bluffing! You can't kill anyone, you're too weak, so stop with those threats of yours.}
{1300}{}{你在虚张声势！你不能杀任何人，你太软弱了，所以别再威胁我了。}
#{1301}{}{I'm not bluffing! Now you're gonna die!}
{1301}{}{我不是在虚张声势！现在你要死了！}
#{1302}{}{What if I give you 100 caps. Will you tell me?}
{1302}{}{如果我给你100个瓶盖呢。你能告诉我吗？}
#{1303}{}{What if I give you Buffout. Will you tell me?}
{1303}{}{如果我把它给你怎么办。你能告诉我吗？}
#{1304}{}{OK, take it easy. I'm leaving.}
{1304}{}{好吧，别紧张。我要走了。}
#{1350}{}{God damn! Life's not worth shit without some junk, and it's been a long time since I had a dose of something strong. Give them caps to me so I can buy something stronger this time.}
{1350}{}{他妈的！没有垃圾，生活就一文不值，我很久没吃过什么烈性的东西了。把瓶盖给我，这样我这次可以买些烈性的。}
#{1351}{}{[Give him 100 caps.] So talk.}
{1351}{}{[给他100个瓶盖]说吧。}
#{1352}{}{You know what? I don't want to know for such a price.}
{1352}{}{你知道吗？我不想知道这么贵。}
#{1400}{}{God damn! Life's not worth shit without some junk, and it's been a long time since I had a dose of something strong. Give it to me.}
{1400}{}{他妈的！没有垃圾，生活就一文不值，我很久没吃过什么烈性的东西了。把它给我。}
#{1401}{}{[Give him Buffout.] So talk.}
{1401}{}{[把他弄出来]那就说吧。}
#{1402}{}{You know what? I don't want to know for such a price.}
{1402}{}{你知道吗？我不想知道这么贵。}
#{1450}{}{Sometime after Maria's death some woman visited me during the night. She had this hood on, so I couldn't see her face at all. I don't know who she was. She paid me to dig two graves. I left the grave with Maria's name empty and threw her body into the other, unmarked grave along with doctor Reed's body. And of course she wanted me to stay silent. She sounded really persuasive, and not only because she was aiming a pistol at me.}
{1450}{}{玛丽亚死后的某个时候，有个女人在夜里来看我。她戴着头巾，所以我根本看不见她的脸。我不知道她是谁。她付钱让我挖两座坟墓。我让玛丽亚的名字空着的坟墓，把她的尸体和里德医生的尸体一起扔进另一个没有标记的坟墓。她当然希望我保持沉默。她听起来很有说服力，不仅因为她用手枪瞄准我。}
#{1451}{}{Interesting...}
{1451}{}{有趣。。。}
#{1500}{}{I hope it's clear you shouldn't go around and yell this everywhere. If I don't know who it was, I don't know who shouldn't hear it, and I don't know how long I should keep my mouth shut. Maybe the only reason I'm still alive today is because there were enough deaths back then. But one more dead won't bother anyone anymore, so I'm staying silent.}
{1500}{}{我希望很明显你不应该到处大喊大叫。如果我不知道是谁，我不知道谁不该听，我也不知道我该闭嘴多久。也许我今天还活着的唯一原因是因为那时的死亡人数已经够多了。但再死一个就不会再打扰任何人了，所以我保持沉默。}
#{1501}{}{Who was doctor Reed?}
{1501}{}{里德医生是谁？}
#{1502}{}{If I give you 40 caps, will you dig up those graves?}
{1502}{}{如果我给你40瓶盖，你会把那些坟墓挖出来吗？}
#{1503}{}{If I give you 20 caps, will you dig up those graves?}
{1503}{}{如果我给你20瓶盖，你会把那些坟墓挖出来吗？}
#{1504}{}{Thanks, you helped me a lot.}
{1504}{}{谢谢，你帮了我很多。}
#{1550}{}{Simply a doctor! I hadn't even known she'd been dead until I saw her body. Maybe she knew something she wasn't supposed to know, and that's why I surely won't care about it.}
{1550}{}{只是个医生！直到看到她的尸体我才知道她已经死了。也许她知道一些不该知道的事情，所以我肯定不会在意。}
#{1551}{}{If I give you 40 caps, will you dig up those graves?}
{1551}{}{如果我给你40瓶盖，你会把那些坟墓挖出来吗？}
#{1552}{}{If I give you 20 caps, will you dig up those graves?}
{1552}{}{如果我给你20瓶盖，你会把那些坟墓挖出来吗？}
#{1553}{}{Thanks, you helped me a lot.}
{1553}{}{谢谢，你帮了我很多。}
#{1600}{}{Damn, I'll tell you if you insist.}
{1600}{}{妈的，如果你坚持，我就告诉你。}
#{1601}{}{So tell me.}
{1601}{}{所以告诉我。}
#{1650}{}{Are you nuts?! I just told you nobody can know, and you want to excavate those graves?!}
{1650}{}{你疯了吗？！我告诉过你没人知道，你想挖那些坟墓？！}
#{1651}{}{I'd love to look inside because of your story. You can make some money or I'll do it alone. I'd prefer the first option.}
{1651}{}{因为你的故事我想看看里面。你可以赚点钱，否则我一个人干。我更喜欢第一种选择。}
#{1652}{}{I'd love to look inside because of your story. You can make some money or I'll do it alone. I'd prefer the first option.}
{1652}{}{因为你的故事我想看看里面。你可以赚点钱，否则我一个人干。我更喜欢第一种选择。}
#{1653}{}{Whatever...}
{1653}{}{无论什么。。。}
#{1700}{}{Okay, have it your way. Give me those caps.}
{1700}{}{好吧，随你的便。把那些瓶盖给我。}
#{1701}{}{[Hand him the caps.]}
{1701}{}{[把瓶盖递给他。]}
#{1702}{}{I've changed my mind, I'm no longer interested.}
{1702}{}{我改变主意了，不再感兴趣了。}
#{1703}{}{I've changed my mind, I'm no longer interested.}
{1703}{}{我改变主意了，不再感兴趣了。}
#{1750}{}{Are you nuts?! I already told you about these graves, and yet you want to excavate them?}
{1750}{}{你疯了吗？！我已经告诉过你这些坟墓的事了，你还想把它们挖出来？}
#{1751}{}{I'd love to look inside because of your story. You can make some money or I'll do it alone. I'd prefer the first option.}
{1751}{}{因为你的故事，我想看看里面。你可以赚点钱，否则我自己挖坟，你一分钱也别想要。我觉得你更喜欢第一种选择。}
#{1752}{}{I'd love to look inside because of your story. You can make some money or I'll do it alone. I'd prefer the first option.}
{1752}{}{因为你的故事，我想看看里面。你可以赚点钱，否则我自己挖坟，你一分钱也别想要。我觉得你更喜欢第一种选择。}
#{1753}{}{Fine, forget it.}
{1753}{}{好吧，算了吧。}
#{1800}{}{No way. I'll dig up any but these two. Forget about them.}
{1800}{}{不可能。除了这两个，我什么都要挖。忘了他们吧。}
#{1801}{}{Why not?}
{1801}{}{为什么不呢？}
#{1802}{}{Take it easy. So let's pick another one.}
{1802}{}{别紧张。我们再挑一个吧。}
#{1803}{}{If you think so...}
{1803}{}{如果你这么认为。。。}
#{1850}{}{Because! I don't want to talk about it.}
{1850}{}{因为！我不想谈这个。}
#{1851}{}{Take it easy. So let's pick another one.}
{1851}{}{别紧张。我们再挑一个吧。}
#{1852}{}{If you say so...}
{1852}{}{如果你这样说。。。}
#{1900}{}{That's great, another wasted cretin. GET THE FUCK OUT before I beat the living shit out of you.}
{1900}{}{太好了，又一个白痴。在我把你打得屁滚尿流之前给我滚出去。}
#{1901}{}{Boohoo, hoooo.}
{1901}{}{呜呜，呜呜。}
#{1950}{}{Well sucks to be you. Somebody stole my shovel and I'm not gonna dig with bare hands.}
{1950}{}{你太差劲了。有人偷了我的铲子，我不会徒手挖的。}
#{1951}{}{Hmmm, I guess it can't be helped.}
{1951}{}{嗯，我想没办法了。}
