#{100}{}{You see a mercenary.}
{100}{}{你看到一个雇佣兵。}
#{101}{}{You see a mercenary.}
{101}{}{你看到一个雇佣兵。}
#{200}{}{You see one of Julian's mercenaries.}
{200}{}{你看到朱利安的雇佣兵了。}
#{201}{}{You see one of Julian's mercenaries.}
{201}{}{你看到朱利安的雇佣兵了。}
#{300}{}{Go search the house and find Leonard! We will secure the perimeter so he can't get away.}
{300}{}{去搜房子找到伦纳德！我们会保护好周围的安全，这样他就逃不掉了。}
#{301}{}{Take care of the house, we will take care of the surroundings. Leonard cannot escape us!}
{301}{}{照顾好房子，我们会照顾好周围的环境。伦纳德逃不了我们！}
#{302}{}{Report to Julian, we'll check it out around here, just to be sure.}
{302}{}{向朱利安报告，我们会在这附近查清楚的。}
#{303}{}{Don't stare at me, go talk to Leonard.}
{303}{}{别盯着我看，去和莱纳德谈谈。}
#{304}{}{That was one hell of a fight.}
{304}{}{那是一场可怕的战斗。}
#{305}{}{Thanks for your help.}
{305}{}{谢谢你的帮助。}
#{360}{}{Julian's dead! It's all fucked.}
{360}{}{朱利安死了！都完了。}
#{400}{}{You're gonna die!}
{400}{}{你会死的！}
#{401}{}{You will die for that!}
{401}{}{你会为此而死的！}
#{402}{}{Fuck you!}
{402}{}{去你妈的！}
#{403}{}{You're dead, you Leonard's shit!}
{403}{}{你死定了，你这个伦纳德的混蛋！}
#{404}{}{You're dead, you Leonard's bitch!}
{404}{}{你死定了，你这个伦纳德的婊子！}
#{405}{}{GET THEM!}
{405}{}{抓住他们！}
#{406}{}{Blind retard.}
{406}{}{盲目的迟钝。}
#{407}{}{Fuck! Shit! Where are my bowels?!}
{407}{}{性交！倒霉！我的肠子呢？！}
