#{100}{}{You see a young girl.}
{100}{}{你看到一个年轻女孩。}
#{150}{}{You see Katrin.}
{150}{}{你看到凯特琳了。}
#{200}{}{You see a very young girl. Despite being covered in dirt, she looks somewhat attractive.}
{200}{}{你看到一个非常年轻的女孩。尽管身上沾满了污垢，她看起来还是有点迷人。}
#{250}{}{You see Katrin, she's dirty and desperate as usual.}
{250}{}{你看凯特琳，她和往常一样肮脏绝望。}
#{251}{}{You see Katrin, it seems nothing's bothering her at the moment.}
{251}{}{你看，凯特琳，她现在好像没什么心事。}
#{300}{}{Yipee yay!}
{300}{}{耶！耶！}
#{301}{}{And it spins and spins and spins...}
{301}{}{它旋转，旋转，旋转。。。}
#{302}{}{Heh heh heh, what fun.}
{302}{}{嘿嘿，多有趣啊。}
#{303}{}{Hee heh hee!}
{303}{}{嘿嘿嘿！}
#{304}{}{Ahhh...}
{304}{}{啊。。。}
#{305}{}{Yahoo!}
{305}{}{雅虎！}
#{306}{}{All them colors...}
{306}{}{所有的颜色。。。}
#{307}{}{Awesome!}
{307}{}{令人惊叹的！}
#{310}{}{Glowing, everything's glowing!}
{310}{}{发光，一切都发光！}
#{311}{}{::Wipes her nose::}
{311}{}{●擦鼻子：}
#{312}{}{::Stares at the sky in awe::}
{312}{}{●敬畏地望着天空：}
#{313}{}{Oh my, you're aglow.}
{313}{}{哦，天哪，你发红了。}
#{314}{}{Hi.}
{314}{}{你好。}
#{315}{}{Howdy.}
{315}{}{你好。}
#{316}{}{Yay! Helloooo!}
{316}{}{耶！你好！}
#{317}{}{Bud!}
{317}{}{巴德！}
#{318}{}{Hehee! Hey there.}
{318}{}{嘿嘿！你好。}
#{350}{}{You've saved me from a damn terrible withdrawal.}
{350}{}{你把我从可怕的撤退中救了出来。}
#{351}{}{You really helped me.}
{351}{}{你真的帮了我。}
#{352}{}{Thank you.}
{352}{}{非常感谢。}
#{353}{}{Thanks a lot.}
{353}{}{谢谢。}
#{354}{}{If you'll get some caps for me, I'll be here.}
{354}{}{如果你能给我拿些瓶盖，我就在这儿。}
#{355}{}{Hey, thanks for helping.}
{355}{}{嘿，谢谢你的帮助。}
#{356}{}{You're cool.}
{356}{}{你很酷。}
#{357}{}{See ya.}
{357}{}{再见。}
#{358}{}{You really helped me.}
{358}{}{你真的帮了我。}
#{359}{}{You've saved me from a damn terrible withdrawal.}
{359}{}{你把我从可怕的撤退中救了出来。}
#{360}{}{Asshole!}
{360}{}{混蛋！}
#{361}{}{Filthy pig!}
{361}{}{肮脏的猪！}
#{362}{}{Get away from me!}
{362}{}{离我远点！}
#{363}{}{Leave me alone!}
{363}{}{别管我！}
#{364}{}{Go away!}
{364}{}{走开！}
#{365}{}{Don't get any closer to me!}
{365}{}{别靠近我！}
#{366}{}{Swine!}
{366}{}{猪！}
#{367}{}{You bitch!}
{367}{}{你这个婊子！}
#{370}{}{I... don't want to have anything to do with you anymore.}
{370}{}{一、 。。。我不想再和你有任何关系了。}
#{371}{}{Please, leave me be.}
{371}{}{拜托，别管我。}
#{372}{}{Leave me alone.}
{372}{}{别管我。}
#{373}{}{I don't want anything from you.}
{373}{}{我不想要你的任何东西。}
#{374}{}{Go away.}
{374}{}{走开。}
#{375}{}{Not interested!}
{375}{}{不感兴趣！}
#{380}{}{Alexa's dead. It's all fucked, totally fucked! No more junk. Fuck!}
{380}{}{亚历克斯死了。全他妈的，全他妈的！再也没有垃圾了。性交！}
#{500}{}{Hi, I'm Katrin and you? I haven't seen you here before, you aren't local then, right?}
{500}{}{嗨，我是凯特琳，你呢？我以前没见过你，你不是本地人，对吧？}
#{501}{}{You're right, I'm not. I'm new around here.}
{501}{}{你是对的，我不是。我是新来的。}
#{502}{}{You're right, I'm not. I'm new around here.}
{502}{}{你是对的，我不是。我是新来的。}
#{503}{}{What is it to you?}
{503}{}{这和你有什么关系？}
#{504}{}{Ugahaahaaah!}
{504}{}{Ugahaahaaah！}
#{550}{}{You? Will you finally give me something? Please, just a few caps, I'm hitting rock bottom.}
{550}{}{你呢？你最后能给我点什么吗？求你了，就几顶瓶盖，我就要触底了。}
#{551}{}{Hi, could you give me something again? Come on, for our friendship's sake. I'm all out again.}
{551}{}{嗨，你能再给我点东西吗？拜托，为了我们的友谊。我又筋疲力尽了。}
#{552}{}{What do you need the caps for anyway?}
{552}{}{你要这些瓶盖干嘛？}
#{553}{}{I won't give you caps, but I have some quality stuff on me.}
{553}{}{我不给你瓶盖，但我身上有些好东西。}
#{554}{}{Sure thing. I'll give you some caps.}
{554}{}{当然。我给你一些瓶盖。}
#{555}{}{Underneath that dirt, you're actually a pretty girl. Come to think of it, you could... do something to earn some caps.}
{555}{}{在那脏东西下面，你其实是个漂亮的女孩。想想看，你可以。。。做点什么来赚些钱。}
#{556}{}{Here's 300 caps, go to Alexa and buy some goods. [List the goods doctor Moore needs.] If you have any caps left, they're yours. And I'll give you even more when you hand the goods to me.}
{556}{}{这是300顶瓶盖，去亚历克斯买些东西。[列出摩尔医生需要的物品]如果你还有瓶盖，就归你了。当你把货交给我的时候，我会给你更多。}
#{557}{}{I don't have, I won't give.}
{557}{}{我没有，我不会放弃。}
#{558}{}{Heeere! [Give her a few caps.]}
{558}{}{嘿！[给她几顶瓶盖。]}
#{559}{}{Eee!}
{559}{}{嘿！}
#{600}{}{Heh, it's something that our hellhole still gets visitors. You got lost, right? Look now, I was thinking that... Well, would you happen to have a few caps to spare?}
{600}{}{嘿，这是我们的地狱仍然吸引游客的东西。你迷路了，对吧？听着，我在想。。。好吧，你有多余的瓶盖吗？}
#{601}{}{Heh, it's something that our hellhole still gets visitors. You got lost, right? Look now, I was thinking that... Well, would you happen to have a few caps to spare?}
{601}{}{嘿，这是我们的地狱仍然吸引游客的东西。你迷路了，对吧？听着，我在想。。。好吧，你有多余的瓶盖吗？}
#{602}{}{What do you want caps for?}
{602}{}{你想要瓶盖干什么？}
#{603}{}{Sure thing. I'll give you some caps.}
{603}{}{当然。我给你一些瓶盖。}
#{604}{}{Underneath that dirt, you're actually a pretty girl. Come to think of it, you could... do something to earn some caps.}
{604}{}{在那脏东西下面，你其实是个漂亮的女孩。想想看，你可以。。。做点什么来赚些钱。}
#{605}{}{I don't have, I won't give.}
{605}{}{我没有，我不会放弃。}
#{650}{}{What do you think? I haven't had my dose for a long time, withdrawal's kicking in. Please, just a few caps.}
{650}{}{你怎么认为？我很长时间没服药了，戒断开始了。拜托，就几顶瓶盖。}
#{651}{}{Why caps when I can give you some quality stuff?}
{651}{}{既然我能给你一些高质量的东西，为什么还要戴瓶盖？}
#{652}{}{If you keep doing drugs, your withdrawals will get worse and worse. You'll become a complete wreck in the end. Maybe I could tell you how to at least try quitting.}
{652}{}{如果你继续吸毒，你的戒毒情况会越来越糟。你最终会变成一个彻底的失败者。也许我可以告诉你怎么至少试着戒烟。}
#{653}{}{Sure thing. I'll give you some caps.}
{653}{}{当然。我给你一些瓶盖。}
#{654}{}{Underneath that dirt, you're actually a pretty girl. Come to think of it, you could... do something to earn some caps.}
{654}{}{在那脏东西下面，你其实是个漂亮的女孩。想想看，你可以。。。做点什么来赚些钱。}
#{655}{}{I won't give you anything, you junkie.}
{655}{}{我什么都不给你，你这个瘾君子。}
#{700}{}{Really?! What do you have? I'll take anything that makes me feel good. I'm pretty damn dry right now.}
{700}{}{真正地？！你有什么？我要吃任何让我感觉好的东西。我现在他妈的很干。}
#{701}{}{And how about stopping? If you keep doing drugs, your withdrawals will get worse and worse. You'll become a complete wreck in the end. Maybe I could tell you how to at least try quitting.}
{701}{}{停下来怎么样？如果你继续吸毒，你的戒毒情况会越来越糟。你最终会变成一个彻底的失败者。也许我可以告诉你怎么至少试着戒烟。}
#{702}{}{Here, have some Psycho.}
{702}{}{来，来点精神病。}
#{703}{}{Here, have some Buffout.}
{703}{}{来，吃点东西。}
#{704}{}{Here, have some Mentats.}
{704}{}{来，吃点薄荷糖。}
#{705}{}{Sucks to be you then, because I'm not going to waste top stuff on you.}
{705}{}{那你就糟透了，因为我不会在你身上浪费太多。}
#{750}{}{You can shove your goddamn advice, it won't make me feel any better! I need caps, get it? Caps!}
{750}{}{你他妈的别提建议了，我不会好受的！我需要瓶盖，明白吗？瓶盖！}
#{751}{}{I'm going to tell you even though you don't want to hear it! You have two options. Either you stop right now and overcome it, although it'll be hard and it'll hurt a lot. Or you can gradually decrease the amount you take till you can do without drugs at all.}
{751}{}{即使你不想听，我也要告诉你！你有两个选择。要么你现在就停下来克服它，尽管它会很难，也会很痛。或者你可以逐渐减少你的服用量，直到你可以完全不用药物。}
#{752}{}{Alright, I'll give you something.}
{752}{}{好吧，我给你点东西。}
#{753}{}{I'll give you nothing.}
{753}{}{我什么也不给你。}
#{800}{}{Right, thanks for the advice. You're really cool being this concerned. So won't you help me and give me a few caps so I can buy a smaller dose? I won't be able to get through the withdrawal, I'd rather bash my head against a rock.}
{800}{}{好的，谢谢你的建议。你这么担心真的很酷。你能不能帮我，给我几顶瓶盖，这样我就可以买小剂量的？我不能通过撤军，我宁愿把头撞在石头上。}
#{801}{}{Alright, here you go, 20 caps.}
{801}{}{好吧，给你，20个瓶盖。}
#{802}{}{Sorry, you'll have to do it the hard way.}
{802}{}{对不起，你得用很难的方法。}
#{850}{}{Well fuck you then! And shove that bullshit of yours down someone else's throat!}
{850}{}{去你妈的！把你的废话塞进别人的喉咙！}
#{851}{}{Good bye.}
{851}{}{再见。}
#{900}{}{Oh come on, you can spare a few caps! Please!}
{900}{}{哦，拜托，你可以多留几顶瓶盖！拜托！}
#{901}{}{Okay, I'll give you something then.}
{901}{}{好吧，那我给你点东西。}
#{902}{}{Actually, you're a very pretty girl. Come to think of it, you could... do something to earn some caps.}
{902}{}{实际上，你是个很漂亮的女孩。想想看，你可以。。。做点什么来赚些钱。}
#{903}{}{I'll give you nothing.}
{903}{}{我什么也不给你。}
#{950}{}{Well screw you, tightwad!}
{950}{}{去你的，吝啬鬼！}
#{951}{}{Well screw you, tightwad!}
{951}{}{去你的，吝啬鬼！}
#{952}{}{And same to you.}
{952}{}{你也一样。}
#{1000}{}{Really, you will? [Her eyes twinkle.] So how much, eh?}
{1000}{}{真的，你会吗？[她的眼睛闪闪发光]那要多少钱，嗯？}
#{1001}{}{Here you go - 10 caps.}
{1001}{}{给你-10个瓶盖。}
#{1002}{}{Hopefully 20 caps will be enough.}
{1002}{}{希望20个盖帽就足够了。}
#{1003}{}{30 caps, that's more than enough.}
{1003}{}{30个瓶盖，够了。}
#{1004}{}{Sorry, but it seems I have no caps to spare.}
{1004}{}{对不起，我好像没有多余的瓶盖了。}
#{1005}{}{Screw you, I won't give you anything!}
{1005}{}{去你的，我什么都不会给你！}
#{1050}{}{What? Just ten? Don't you have more? Please, I really need them.}
{1050}{}{什么？只有十个？你没有更多吗？拜托，我真的需要他们。}
#{1051}{}{What? Just ten? Don't you have more? Please, I really need them.}
{1051}{}{什么？只有十个？你没有更多吗？拜托，我真的需要他们。}
#{1052}{}{Okay, I'll give you 10 more then.}
{1052}{}{好吧，那我再给你10块。}
#{1053}{}{Alright, here's 20 more caps.}
{1053}{}{好吧，这里还有20个瓶盖。}
#{1054}{}{I won't give you more.}
{1054}{}{我不会给你更多的。}
#{1100}{}{Great, thanks. You helped me a lot. And if you ever have some caps to spare, you know where to find me.}
{1100}{}{太好了，谢谢。你帮了我很多。如果你有多余的瓶盖，你知道哪里可以找到我。}
#{1101}{}{Great, thanks. You helped me a lot. And if you ever have some caps to spare, you know where to find me.}
{1101}{}{太好了，谢谢。你帮了我很多。如果你有多余的瓶盖，你知道哪里可以找到我。}
#{1102}{}{Wait! Can I ask you something?}
{1102}{}{等待！我能问你件事吗？}
#{1103}{}{My pleasure, take care.}
{1103}{}{不客气，保重。}
#{1150}{}{Oh wow, thanks a lot. You helped me a bunch. And if you ever have some caps to spare, you know where to find me.}
{1150}{}{哦，哇，非常感谢。你帮了我很多。如果你有多余的瓶盖，你知道哪里可以找到我。}
#{1151}{}{Oh wow, thanks a lot. You helped me a bunch. And if you ever have some caps to spare, you know where to find me.}
{1151}{}{哦，哇，非常感谢。你帮了我很多。如果你有多余的瓶盖，你知道哪里可以找到我。}
#{1152}{}{Wait! Can I ask you something?}
{1152}{}{等待！我能问你件事吗？}
#{1153}{}{My pleasure, take care.}
{1153}{}{不客气，保重。}
#{1200}{}{Well, thanks anyway, even though you could've given me more...}
{1200}{}{不管怎样，谢谢你，尽管你可以给我更多。。。}
#{1201}{}{Well, thanks anyway, even though you could've given me more...}
{1201}{}{不管怎样，谢谢你，尽管你可以给我更多。。。}
#{1202}{}{Wait! Can I ask you something?}
{1202}{}{等待！我能问你件事吗？}
#{1203}{}{My pleasure, take care.}
{1203}{}{不客气，保重。}
#{1250}{}{Questions? [It looks like she would rather leave now.] Well, ask away, but I'll hardly be of any assistance.}
{1250}{}{问题？[看起来她宁愿现在就走。]好吧，去问吧，但我几乎帮不上什么忙。}
#{1251}{}{Tell me about yourself. Howcome such a young girl begs on the street?}
{1251}{}{跟我说说你自己。为什么这么年轻的女孩在街上乞讨？}
#{1252}{}{What about some current gossip? Do you know about anything worth mentioning?}
{1252}{}{最近的流言蜚语呢？你知道有什么值得一提的吗？}
#{1253}{}{Do you know anything about Maria?}
{1253}{}{你了解玛丽亚吗？}
#{1254}{}{Where can I get medicine or similar stuff here?}
{1254}{}{我在哪能买到药或类似的东西？}
#{1255}{}{Actually I have no idea what to ask. Take care.}
{1255}{}{实际上我不知道该问什么。当心。}
#{1300}{}{Watch it! I'm no longer a kid. I've been living here alone since they shot my parents. They got into a firefight by accident. No idea why we were staying in this town, especially when it all went downhill. I was way too young so my parents didn't explain it to me.}
{1300}{}{小心点！我不再是个孩子了。自从他们枪杀我父母后，我就一个人住在这里。他们不小心发生了交火。不知道我们为什么要留在这个镇上，尤其是当一切都走下坡路的时候。我太小了，所以我父母没有给我解释。}
#{1301}{}{That's sad. But can I ask you something else?}
{1301}{}{那太可悲了。但我能问你点别的吗？}
#{1302}{}{Thanks for the story, but I have to go now.}
{1302}{}{谢谢你的报道，但我现在得走了。}
#{1350}{}{Nothing interesting going on; Leonard and Julian's henchmen being at each other's throats, that never changes.}
{1350}{}{没什么有趣的事情发生了；伦纳德和朱利安的心腹互相纠缠，这一点从未改变。}
#{1351}{}{Ah, thanks. I'll ask you something else then.}
{1351}{}{啊，谢谢。那我再问你点别的。}
#{1352}{}{That's enough, I don't need to know more, take care.}
{1352}{}{够了，我不需要知道更多，保重。}
#{1400}{}{I know fuck all about her. Only that the entire town is fucked thanks to her, but nothing else. I was way too young when they killed her.}
{1400}{}{我对她了如指掌。只是因为她整座城市都完蛋了，别的什么都没有。他们杀她的时候我还太小。}
#{1401}{}{I want to ask you something else.}
{1401}{}{我想问你点别的。}
#{1402}{}{Too bad, take care and maybe we'll meet again.}
{1402}{}{太糟糕了，保重，也许我们还会再见面。}
#{1450}{}{All you need to do is to go to Leonard's, to that big house. You can get a lot of cool stuff there. But beware, Alexa is really suspicious when it comes to strangers, she won't give you a good price; And if she thinks you work for Julian, you're gonna have a bad time.}
{1450}{}{你要做的就是去莱纳德家，去那所大房子。你可以在那里买到很多很酷的东西。但要小心，亚历克莎对陌生人真的很怀疑，她不会给你一个好价钱；如果她认为你为朱利安工作，你会过得很不愉快。}
#{1451}{}{Who's this Alexa?}
{1451}{}{这个亚历克斯是谁？}
#{1452}{}{Now when I think about it, how about you go there and buy something for me? I'll pay you.}
{1452}{}{现在我想起来了，你去那里给我买点东西怎么样？我会付钱给你的。}
#{1453}{}{Can I ask you something else?}
{1453}{}{我能问你点别的吗？}
#{1454}{}{Thanks, take care.}
{1454}{}{谢谢，保重。}
#{1500}{}{Alexa takes care of everything for Leonard, while he's holed up somewhere. He's probably enjoying his goods. If I had such a stock, I'd have done that for sure.}
{1500}{}{亚历克斯替伦纳德处理一切，而他却躲在某个地方。他可能很喜欢他的东西。如果我有这样的股票，我肯定会这么做。}
#{1501}{}{How about you go to Alexa and buy something for me? I'll pay you for it.}
{1501}{}{你去Alexa给我买点东西怎么样？我会付钱给你的。}
#{1502}{}{Can I ask you something else?}
{1502}{}{我能问你点别的吗？}
#{1503}{}{Thanks, take care.}
{1503}{}{谢谢，保重。}
#{1550}{}{Oh? But it's a big risk, you better pay me handsomely.}
{1550}{}{哦？但这是一个很大的风险，你最好给我丰厚的报酬。}
#{1551}{}{[List the goods doctor Moore needs.] If you have any caps left, they're yours. And I'll give you even more when you hand the goods to me.}
{1551}{}{[列出摩尔医生需要的物品]如果你还有瓶盖，就归你了。当你把货交给我的时候，我会给你更多。}
#{1552}{}{We'll talk when I get enough caps. See ya for now.}
{1552}{}{等我拿到足够的瓶盖再谈。再见。}
#{1553}{}{You know what? Forget about it. I don't trust you.}
{1553}{}{你知道吗？算了吧。我不相信你。}
#{1600}{}{Wowie, I haven't seen 300 caps all together before. You must be doing fine. Meet you in an hour, okay?}
{1600}{}{哇，我以前没见过300个瓶盖。你一定做得很好。一小时后见，好吗？}
#{1601}{}{OK.}
{1601}{}{好 啊。}
#{1650}{}{W-wait. What do you mean?}
{1650}{}{等等。什么意思？}
#{1651}{}{Oh come on, you get the idea. You're no longer a kid, but quite a pretty girl a guy could have some fun with.}
{1651}{}{哦，拜托，你明白了。你不再是个孩子了，而是个漂亮的女孩，一个男人可以和她一起玩。}
#{1652}{}{Oh come on, you get the idea. You're no longer a kid, but quite a pretty girl even a woman could have some fun with.}
{1652}{}{哦，拜托，你明白了。你不再是个孩子了，但还是个漂亮的女孩，即使是女人也可以和你一起玩。}
#{1653}{}{Eh, nevermind, I'll give you some caps.}
{1653}{}{呃，没关系，我给你一些瓶盖。}
#{1654}{}{Oh nothing at all. Forget about it.}
{1654}{}{哦，没什么。算了吧。}
#{1700}{}{But I've never... And right here? On the street? Well... fine, but you'll pay me afterwards, right?}
{1700}{}{但我从来没有。。。就在这里？在街上？好。。。好吧，但你以后会付钱给我的，对吗？}
#{1701}{}{Don't worry, we'll settle it after that...}
{1701}{}{别担心，我们会解决的。。。}
#{1750}{}{[Katrin gets up from the pile of junk you pinned her on.] And now pay up, since you're done.}
{1750}{}{[凯特琳从你压在她身上的那堆垃圾堆里站起来]现在付钱，既然你做完了。}
#{1751}{}{[Katrin gets up from the pile of junk you pinned her on.] And now pay up, since you're done.}
{1751}{}{[凯特琳从你压在她身上的那堆垃圾堆里站起来]现在付钱，既然你做完了。}
#{1752}{}{[Throw her 50 caps and leave.]}
{1752}{}{[扔掉她的50个瓶盖然后离开。]}
#{1753}{}{[Throw her one Psycho and leave.]}
{1753}{}{[扔给她一个疯子然后离开。]}
#{1754}{}{[Throw her one Buffout and leave.]}
{1754}{}{[把她扔出去然后离开。]}
#{1755}{}{[Throw her one Mentats and leave.]}
{1755}{}{[扔给她一颗薄荷糖然后离开。]}
#{1756}{}{Here, you get 10 caps, it wasn't worth more anyway.}
{1756}{}{在这里，你得到10个瓶盖，反正也不值钱。}
#{1757}{}{No way. Take it as a free lesson. You can try your luck with some of Leonard's men. Maybe they'll give you something in exchange.}
{1757}{}{不可能。把它当作免费课。你可以和伦纳德的人碰碰运气。也许他们会给你一些东西作为交换。}
#{1800}{}{You fucking bastard! [She spits on you.]}
{1800}{}{你这个混蛋！[她朝你吐口水。]}
#{1801}{}{You fucking cunt! [She spits on you.]}
{1801}{}{你这个混蛋！[她朝你吐口水。]}
#{1802}{}{Take care.}
{1802}{}{当心。}
#{1850}{}{Hey, take it easy! I just wanted to talk a bit and... erm... I was thinking... Well, would you happen to have any spare caps you could give me?}
{1850}{}{嘿，别紧张！我只是想谈谈。。。呃。。。我在想。。。好吧，你有多余的瓶盖可以给我吗？}
#{1851}{}{Hey, take it easy! I just wanted to talk a bit and... erm... I was thinking... Well, would you happen to have any spare caps you could give me?}
{1851}{}{嘿，别紧张！我只是想谈谈。。。呃。。。我在想。。。好吧，你有多余的瓶盖可以给我吗？}
#{1852}{}{What do you need the caps for?}
{1852}{}{你要这些瓶盖干什么？}
#{1853}{}{Sure thing. I'll give you some caps.}
{1853}{}{当然。我给你一些瓶盖。}
#{1854}{}{Underneath that dirt, you're actually a pretty girl. Come to think of it, you could... do something to earn some caps.}
{1854}{}{在那脏东西下面，你其实是个漂亮的女孩。想想看，你可以。。。做点什么来赚些钱。}
#{1855}{}{I don't have, I won't give.}
{1855}{}{我没有，我不会放弃。}
#{1900}{}{Oooh, heeeey! Nice to see you again.}
{1900}{}{哦，嘿！很高兴再次见到你。}
#{1901}{}{What the? You're tripping balls! Where's my stuff?!}
{1901}{}{怎么回事？你把球绊倒了！我的东西呢？！}
#{1902}{}{Egh? My thingies?!}
{1902}{}{呃？我的东西？！}
#{1950}{}{Gone. Alexa took all the caps and I have pre-paid stuff for the entire month, heh. Sorry but such an offer couldn't be refused.}
{1950}{}{跑了。Alexa拿走了所有的瓶盖，我已经预付了整个月的费用，呵呵。对不起，这样的提议不能拒绝。}
#{1951}{}{Sorry, really. I wanted to buy all that stuff. You're an okay guy. I even bought two stimpaks. [She gives them to you.] But for the rest of the caps, Alexa offered me pre-paid drugs for 2 weeks, heh. Sorry but I couldn't turn down such an offer.}
{1951}{}{对不起，真的。我想买那些东西。你是个好人。我甚至买了两个Stimpak。[她给你的。]但是剩下的瓶盖，亚历克斯给了我2周的预付费药物，呵呵。对不起，我不能拒绝这样的提议。}
#{1952}{}{Sorry, really. I wanted to buy all that stuff. You're an okay girl. I even bought two stimpaks. [She gives them to you.] But for the rest of the caps, Alexa offered me pre-paid drugs for 2 weeks, heh. Sorry but I couldn't turn down such an offer.}
{1952}{}{对不起，真的。我想买那些东西。你是个好女孩。我甚至买了两个Stimpak。[她给你的。]但是剩下的瓶盖，亚历克斯给了我2周的预付费药物，呵呵。对不起，我不能拒绝这样的提议。}
#{1953}{}{You stupid junkie, you'll pay for double crossing me!}
{1953}{}{你这个愚蠢的瘾君子，你要为欺骗我付出代价！}
#{1954}{}{You bitch... Damn, fuck you! There's no way I'm getting the caps back anyway.}
{1954}{}{你这个婊子。。。妈的，去你妈的！反正我也不可能把瓶盖拿回来。}
#{1955}{}{Yooou, dead!}
{1955}{}{哟，死了！}
#{1956}{}{Egh.}
{1956}{}{埃格。}
#{2000}{}{Right, whatever you say. Look, do you have any caps to spare? Share some of those pieces of metal, eh?}
{2000}{}{好吧，随你怎么说。你有多余的瓶盖吗？分享一些金属片，嗯？}
#{2001}{}{Right, whatever you say. Look, do you have any caps to spare? Share some of those pieces of metal, eh?}
{2001}{}{好吧，随你怎么说。你有多余的瓶盖吗？分享一些金属片，嗯？}
#{2002}{}{Taaaake. [Give her some of those pretty pieces of metal so she's happy.]}
{2002}{}{塔亚克。[给她一些漂亮的金属片，让她高兴。]}
#{2003}{}{No-no.}
{2003}{}{不，不。}
#{2050}{}{Heh, I didn't see that coming from you! Thanks, you helped me a bunch.}
{2050}{}{嘿，我没看到你这么说！谢谢，你帮了我不少忙。}
#{2051}{}{Heh, I didn't see that coming from you! Thanks, you helped me a bunch.}
{2051}{}{嘿，我没看到你这么说！谢谢，你帮了我不少忙。}
#{2052}{}{Bai bai.}
{2052}{}{白白。}
#{2100}{}{Go fuck yourself! First you promise and then nothing... But look, you could spare a few caps, right? How about that?}
{2100}{}{去你妈的！先是你答应，然后什么都没有。。。不过，你可以多留几顶瓶盖，对吧？怎么样？}
#{2101}{}{Go fuck yourself! First you promise and then nothing... But look, you could spare a few caps, right? How about that?}
{2101}{}{去你妈的！先是你答应，然后什么都没有。。。不过，你可以多留几顶瓶盖，对吧？怎么样？}
#{2102}{}{Well okay, I'll give you some caps then.}
{2102}{}{好吧，那我给你一些瓶盖。}
#{2103}{}{Well, underneath that dirt you're actually a pretty girl. Come to think of it, you could... do something to earn some caps.}
{2103}{}{好吧，在那脏东西下面你其实是个漂亮的女孩。想想看，你可以。。。做点什么来赚些钱。}
#{2104}{}{Nope, I won't give you anything.}
{2104}{}{不，我什么都不会给你。}
#{2150}{}{Thanks, I wasn't even expecting it from you anymore. In case you get some extra caps, you know where to find me. These won't last long.}
{2150}{}{谢谢，我都没想到你会这么说了。万一你有多余的瓶盖，你知道在哪儿能找到我。这些不会持续太久。}
#{2151}{}{Thanks, I wasn't even expecting it from you anymore. In case you get some extra caps, you know where to find me. These won't last long.}
{2151}{}{谢谢，我都没想到你会这么说了。万一你有多余的瓶盖，你知道在哪儿能找到我。这些不会持续太久。}
#{2152}{}{What? Those caps are for your addiction treatment!}
{2152}{}{什么？那些瓶盖是用来戒毒的！}
#{2200}{}{They're already mine, right? So I'll do anything I want with them. You don't really think you can help anyone with your bullshit, do you? Heh.}
{2200}{}{它们已经是我的了，对吧？所以我想对他们做什么就做什么。你不会真的认为你能帮到任何人吧？嘿。}
#{2201}{}{At least I tried.}
{2201}{}{至少我试过了。}
#{2202}{}{At least I tried.}
{2202}{}{至少我试过了。}
