#{100}{}{You see a bartender.}
{100}{}{你看到一个酒保。}
#{200}{}{You see a bartender, and he doesn't look very friendly.}
{200}{}{你看到一个酒保，他看起来不太友好。}
#{400}{}{Get outta here!}
{400}{}{离开这里！}
#{500}{}{Yeah?}
{500}{}{是 啊？}
#{501}{}{I'll have something to drink.}
{501}{}{我要喝点东西。}
#{502}{}{I'll have something to drink.}
{502}{}{我要喝点东西。}
#{503}{}{Do you sell any dope here?}
{503}{}{你们这儿卖毒品吗？}
#{504}{}{Where can a person make money around here?}
{504}{}{一个人在这附近哪里能赚钱？}
#{505}{}{Who's that tough guy at the bar?}
{505}{}{酒吧里那个硬汉是谁？}
#{506}{}{Ghe.}
{506}{}{唉。}
#{507}{}{Nothing.}
{507}{}{没有什么。}
#{550}{}{What?}
{550}{}{什么？}
#{551}{}{Give me Nuka-Cola.}
{551}{}{给我努卡可乐。}
#{552}{}{Give me a beer.}
{552}{}{给我一杯啤酒。}
#{553}{}{Give me spirits.}
{553}{}{给我精神。}
#{554}{}{Give me rum.}
{554}{}{给我朗姆酒。}
#{555}{}{Give me Rot Gut.}
{555}{}{把腐烂的肠子给我。}
#{556}{}{I don't have enough money, sorry.}
{556}{}{我没有足够的钱，对不起。}
#{557}{}{I want something else instead.}
{557}{}{我想要点别的。}
#{600}{}{Anything else?}
{600}{}{还有别的吗？}
#{601}{}{I'll have something to drink.}
{601}{}{我要喝点东西。}
#{602}{}{I'll have something to drink.}
{602}{}{我要喝点东西。}
#{603}{}{Do you sell any dope?}
{603}{}{你们卖毒品吗？}
#{604}{}{Where can a person make money around here?}
{604}{}{一个人在这附近哪里能赚钱？}
#{605}{}{Who's that tough guy at the bar?}
{605}{}{酒吧里那个硬汉是谁？}
#{606}{}{Later.}
{606}{}{以后再说。}
#{650}{}{If you got enough caps.}
{650}{}{如果你有足够的瓶盖。}
#{651}{}{I do.}
{651}{}{我愿意。}
#{652}{}{I don't, I want something else.}
{652}{}{我不想，我想要别的东西。}
#{700}{}{Talk to Sanchez, it's that guy at the staircase. Or ask Cristos, if you want to try your luck in the ring. That's where you'll find him.}
{700}{}{和桑切斯谈谈，是楼梯上的那个家伙。或者问克里斯托斯，如果你想在拳击场上碰碰运气的话。你可以在那里找到他。}
#{701}{}{OK, but I want something else.}
{701}{}{好吧，但我想要点别的。}
#{702}{}{OK, see you.}
{702}{}{好的，再见。}
#{750}{}{Get lost!}
{750}{}{滚开！}
#{751}{}{Bubblee.}
{751}{}{布布利。}
#{800}{}{Yeah?}
{800}{}{是 啊？}
#{801}{}{I'll have something to drink.}
{801}{}{我要喝点东西。}
#{802}{}{I'll have something to drink.}
{802}{}{我要喝点东西。}
#{803}{}{Do you sell any dope?}
{803}{}{你们卖毒品吗？}
#{804}{}{Who's that tough guy at the bar?}
{804}{}{酒吧里那个硬汉是谁？}
#{805}{}{Nothing.}
{805}{}{没有什么。}
#{806}{}{Uff.}
{806}{}{不明飞行物。}
#{850}{}{Sure, for you, everything's for free.}
{850}{}{当然，对你来说，一切都是免费的。}
#{851}{}{Give me Nuka-Cola.}
{851}{}{给我努卡可乐。}
#{852}{}{Give me a beer.}
{852}{}{给我一杯啤酒。}
#{853}{}{Give me spirits.}
{853}{}{给我精神。}
#{854}{}{Give me rum.}
{854}{}{给我朗姆酒。}
#{855}{}{Give me Rot Gut.}
{855}{}{把腐烂的肠子给我。}
#{856}{}{I want something else instead.}
{856}{}{我想要点别的。}
#{900}{}{If you got enough caps.}
{900}{}{如果你有足够的瓶盖。}
#{901}{}{I do.}
{901}{}{我愿意。}
#{902}{}{I don't, I want something else.}
{902}{}{我不想，我想要别的东西。}
#{950}{}{Anything else?}
{950}{}{还有别的吗？}
#{951}{}{I'll have something to drink.}
{951}{}{我要喝点东西。}
#{952}{}{I'll have something to drink.}
{952}{}{我要喝点东西。}
#{953}{}{Do you sell any dope?}
{953}{}{你们卖毒品吗？}
#{954}{}{Who's that tough guy at the bar?}
{954}{}{酒吧里那个硬汉是谁？}
#{955}{}{Later.}
{955}{}{以后再说。}
#{1000}{}{I got nothing to tell you. Better leave him alone.}
{1000}{}{我没什么要告诉你的。最好别管他。}
#{1001}{}{I'll have something to drink.}
{1001}{}{我要喝点东西。}
#{1002}{}{I'll have something to drink.}
{1002}{}{我要喝点东西。}
#{1003}{}{Do you sell any dope?}
{1003}{}{你们卖毒品吗？}
#{1004}{}{Where can a person make money around here?}
{1004}{}{一个人在这附近哪里能赚钱？}
#{1005}{}{Well, see you.}
{1005}{}{好吧，再见。}
#{1050}{}{He's a hit man. Senor hired him a couple of times, but he wasn't too into him 'cause he's not a made man. Better stay away from him.}
{1050}{}{他是个杀手。先生雇过他几次，但他对他不太感兴趣，因为他不是一个成功的人。最好离他远点。}
#{1051}{}{I'll have something to drink.}
{1051}{}{我要喝点东西。}
#{1052}{}{I'll have something to drink.}
{1052}{}{我要喝点东西。}
#{1053}{}{Do you sell any dope?}
{1053}{}{你们卖毒品吗？}
#{1054}{}{Well, see you.}
{1054}{}{好吧，再见。}
#{1100}{}{You've had enough for today. Leave something for the guests.}
{1100}{}{今天你受够了。给客人留点东西。}
#{1101}{}{You've had enough for today. Leave something for the guests.}
{1101}{}{今天你受够了。给客人留点东西。}
#{1102}{}{Fine, something else then.}
{1102}{}{好吧，还有别的事。}
#{1103}{}{OK, I'll come back some other time.}
{1103}{}{好的，我改天再来。}
