#{100}{}{You see a bartender.}
{100}{}{你看到一个酒保。}
#{200}{}{You see a bartender with a look on her face that says "I have seen it all".}
{200}{}{你看到一个酒保脸上带着“我都看过”的表情。}
#{400}{}{Nobody's messing around here.}
{400}{}{没人在这捣乱。}
#{401}{}{The cops will make a door rug out of you.}
{401}{}{警察会把你当门毯的。}
#{500}{}{What'll it be, tough guy?}
{500}{}{会是什么，硬汉？}
#{501}{}{I'll have something to drink.}
{501}{}{我要喝点东西。}
#{502}{}{How much are the girls here?}
{502}{}{这里的女孩多少钱？}
#{503}{}{Pheewee!}
{503}{}{菲维！}
#{504}{}{Nothing.}
{504}{}{没有什么。}
#{550}{}{Nuka-Cola, beer, spirits, rum, Rot Gut. So?}
{550}{}{努卡可乐，啤酒，烈酒，朗姆酒，烂肠。所以呢？}
#{551}{}{Nuka-Cola.}
{551}{}{努卡可乐。}
#{552}{}{Beer.}
{552}{}{啤酒。}
#{553}{}{Spirits.}
{553}{}{精神。}
#{554}{}{Rum.}
{554}{}{朗姆酒。}
#{555}{}{Rot Gut.}
{555}{}{腐烂的肠子。}
#{556}{}{I changed my mind.}
{556}{}{我改变主意了。}
#{600}{}{No money, no drinking.}
{600}{}{没钱，没喝酒。}
#{601}{}{OK.}
{601}{}{好 啊。}
#{650}{}{Anything else?}
{650}{}{还有别的吗？}
#{651}{}{Nuka-Cola.}
{651}{}{努卡可乐。}
#{652}{}{Beer.}
{652}{}{啤酒。}
#{653}{}{Spirits.}
{653}{}{精神。}
#{654}{}{Rum.}
{654}{}{朗姆酒。}
#{655}{}{Rot Gut.}
{655}{}{腐烂的肠子。}
#{656}{}{That's all.}
{656}{}{这就是全部。}
#{700}{}{3 caps.}
{700}{}{3个盖子。}
#{701}{}{I haven't got that much.}
{701}{}{我没有那么多。}
#{702}{}{Here.}
{702}{}{在这里。}
#{703}{}{Not interested.}
{703}{}{不感兴趣。}
#{750}{}{5 caps.}
{750}{}{5个盖子。}
#{751}{}{I haven't got that much.}
{751}{}{我没有那么多。}
#{752}{}{Here.}
{752}{}{在这里。}
#{753}{}{Not interested.}
{753}{}{不感兴趣。}
#{800}{}{10 caps.}
{800}{}{10个瓶盖。}
#{801}{}{I haven't got that much.}
{801}{}{我没有那么多。}
#{802}{}{Here.}
{802}{}{在这里。}
#{803}{}{Not interested.}
{803}{}{不感兴趣。}
#{850}{}{15 caps.}
{850}{}{15个瓶盖。}
#{851}{}{I haven't got that much.}
{851}{}{我没有那么多。}
#{852}{}{Here.}
{852}{}{在这里。}
#{853}{}{Not interested.}
{853}{}{不感兴趣。}
#{900}{}{20 caps.}
{900}{}{20个瓶盖。}
#{901}{}{I haven't got that much.}
{901}{}{我没有那么多。}
#{902}{}{Here.}
{902}{}{在这里。}
#{903}{}{Not interested.}
{903}{}{不感兴趣。}
#{950}{}{250 for a number.}
{950}{}{250代表一个数字。}
#{951}{}{I don't have that much.}
{951}{}{我没有那么多。}
#{952}{}{Deal, here's the money.}
{952}{}{成交，钱来了。}
#{953}{}{OK, I'll pay for Keri, she deserves some fun.}
{953}{}{好吧，我会付钱给凯丽的，她应该得到一些乐趣。}
#{954}{}{OK, I'll pay for Lystra, she deserves some fun.}
{954}{}{好吧，我付钱给莱斯特拉，她应该得到一些乐趣。}
#{955}{}{How about two girls at once?}
{955}{}{一次两个女孩怎么样？}
#{956}{}{Not interested.}
{956}{}{不感兴趣。}
#{1000}{}{Your loss.}
{1000}{}{你的损失。}
#{1001}{}{OK.}
{1001}{}{好 啊。}
#{1050}{}{Why not, but no discount. Two girls, 500 caps.}
{1050}{}{为什么不呢，但不打折。两个女孩，500顶瓶盖。}
#{1051}{}{I don't have that much.}
{1051}{}{我没有那么多。}
#{1052}{}{Deal, here's the money.}
{1052}{}{成交，钱来了。}
#{1053}{}{Not interested}
{1053}{}{不感兴趣}
#{1100}{}{Go away. I'm not gonna guess what you want from your stupid face.}
{1100}{}{走开。我猜不出你想从你愚蠢的脸上得到什么。}
#{1101}{}{Bye-bye.}
{1101}{}{再见。}
#{1150}{}{What'll it be, handsome?}
{1150}{}{怎么样，帅哥？}
#{1151}{}{I'll have something to drink.}
{1151}{}{我要喝点东西。}
#{1152}{}{How much are the girls here?}
{1152}{}{这里的女孩多少钱？}
#{1153}{}{Pheewee!}
{1153}{}{菲维！}
#{1154}{}{Nothing.}
{1154}{}{没有什么。}
#{1200}{}{What'll it be, lass?}
{1200}{}{怎么了，姑娘？}
#{1201}{}{I'll have something to drink.}
{1201}{}{我要喝点东西。}
#{1202}{}{How much are the girls here?}
{1202}{}{这里的女孩多少钱？}
#{1203}{}{Pheewee!}
{1203}{}{菲维！}
#{1204}{}{Nothing.}
{1204}{}{没有什么。}
#{1250}{}{You like it with girls, do you? 250 for a number.}
{1250}{}{你喜欢和女孩子在一起，是吗？250代表一个数字。}
#{1251}{}{I don't have that much.}
{1251}{}{我没有那么多。}
#{1252}{}{Deal, here's the money.}
{1252}{}{成交，钱来了。}
#{1253}{}{OK, I'll pay for Keri, she deserves some fun.}
{1253}{}{好吧，我会付钱给凯丽的，她应该得到一些乐趣。}
#{1254}{}{OK, I'll pay for Lystra, she deserves some fun.}
{1254}{}{好吧，我付钱给莱斯特拉，她应该得到一些乐趣。}
#{1255}{}{How about two girls at once?}
{1255}{}{一次两个女孩怎么样？}
#{1256}{}{Not interested.}
{1256}{}{不感兴趣。}
#{1300}{}{Why not, but no discount. Two girls, 500 caps.}
{1300}{}{为什么不呢，但不打折。两个女孩，500顶瓶盖。}
#{1301}{}{I don't have that much.}
{1301}{}{我没有那么多。}
#{1302}{}{Deal, here's the money.}
{1302}{}{成交，钱来了。}
#{1303}{}{Not interested.}
{1303}{}{不感兴趣。}
#{1350}{}{Hey, I recognize that guy!}
{1350}{}{嘿，我认得那个家伙！}
#{1351}{}{Gabriel? What do you mean you "recognize" him?}
{1351}{}{加布里埃尔？你“认出”他是什么意思？}
#{1400}{}{He beat one of our girls so bad she couldn't work for a week. He's gonna get paid the same way by the cops now, with a little extra.}
{1400}{}{他打了我们的一个女孩，打得她一个星期都不能工作。现在警察也会给他同样的报酬，再加一点。}
#{1401}{}{Can we settle it somehow?}
{1401}{}{我们能解决它吗？}
#{1402}{}{Try calling the cops and I'll beat you to pulp.}
{1402}{}{试着报警，我会把你揍得体无完肤。}
#{1403}{}{OK, I won't stand in the way of the police.}
{1403}{}{好吧，我不会妨碍警察的。}
#{1450}{}{I could forget that it happened if you paid for the lost profits for the time she wasn't working. I'd say... 1000 caps.}
{1450}{}{如果你为她不工作的时候损失的利润买单的话，我会忘记这件事的。我想说。。。1000个瓶盖。}
#{1451}{}{Here, take them.}
{1451}{}{来，拿着。}
#{1452}{}{How about we don't go telling people how lousy the girls in this place are? I'm sure we wouldn't be the first, and it's not the kind of advertising you're looking for right now.}
{1452}{}{我们不去告诉别人这个地方的女孩有多糟糕怎么样？我肯定我们不会是第一个，而且这不是你现在想要的那种广告。}
#{1453}{}{No way, I'd sooner twist your neck.}
{1453}{}{不可能，我宁愿扭你的脖子。}
#{1454}{}{You'd better call the cops, then. I won't stand in their way.}
{1454}{}{那你最好报警。我不会妨碍他们的。}
#{1500}{}{All is forgotten. Want anything else?}
{1500}{}{一切都忘记了。还要别的吗？}
#{1501}{}{I'll have something to drink.}
{1501}{}{我要喝点东西。}
#{1502}{}{How much are the girls here?}
{1502}{}{这里的女孩多少钱？}
#{1503}{}{Nothing.}
{1503}{}{没有什么。}
#{1550}{}{Fine! That's off the table.}
{1550}{}{好的！那不在桌子上。}
#{1551}{}{That's how I like it.}
{1551}{}{我就是喜欢这样。}
#{1600}{}{If you want to protect that bastard, the cops'll take care of you, too. [She signals to the closest policeman with her hand.]}
{1600}{}{如果你想保护那个混蛋，警察也会照顾你的。[她用手向最近的警察示意。]}
#{1601}{}{There will be blood.}
{1601}{}{会有血的。}
