#{100}{}{You see an enormous black steel safe.}
{100}{}{你看到一个巨大的黑色钢制保险箱。}
#{101}{}{You see a black square thing with a big wheel.}
{101}{}{你看到一个黑色方形的东西，上面有一个大轮子。}
#{200}{}{You see an enormous black steel safe which seems too heavy for anyone to move. It has a combination lock.}
{200}{}{你看到一个巨大的黑色钢制保险箱，似乎太重了，任何人都无法移动。它有一把组合锁。}
#{201}{}{You see a huge black metal square thing with a wheel on the front side.}
{201}{}{你看到一个巨大的黑色金属正方形的东西，前面有一个轮子。}
#{202}{}{The safe is already unlocked.}
{202}{}{保险箱已经打开了。}
#{203}{}{You managed to unlock the safe.}
{203}{}{你设法打开了保险箱。}
#{204}{}{You failed to unlock the safe.}
{204}{}{你没能打开保险箱。}
#{205}{}{By slowly turning the dial and listening to the clicking you managed to find out the correct combination. The safe is unlocked.}
{205}{}{通过慢慢地转动表盘，听声音，你找到了正确的组合。保险箱没锁。}
#{206}{}{By turning the dial you completely accidentally managed to hit the right combination. The safe is unlocked.}
{206}{}{通过转动表盘，你完全不小心找到了正确的组合。保险箱没锁。}
#{207}{}{Random turning of the dial yielded no result.}
{207}{}{随意转动表盘没有结果。}
#{343}{}{You don't have time to examine the safe in combat.}
{343}{}{你没有时间在战斗中检查保险箱。}
#{344}{}{The explosion didn't do any damage to the safe.}
{344}{}{爆炸没有对保险箱造成任何损坏。}
