#{100}{}{You see a man staring at the ground.}
{100}{}{你看到一个男人盯着地面。}
#{150}{}{You see Charlie.}
{150}{}{你看到查理了。}
#{200}{}{You see a man who's constantly scanning the ground with his eyes.}
{200}{}{你会看到一个不断用眼睛扫视地面的人。}
#{250}{}{You see Charlie the junk collector.}
{250}{}{你看到了垃圾收藏家查理。}
#{300}{}{This is the spot, yes, this is it.}
{300}{}{就是这个地方，是的，就是这个。}
#{301}{}{Another one! Yes. And another one.}
{301}{}{另一个！对。再来一个。}
#{302}{}{Good spot, good, very good.}
{302}{}{很好，很好，很好。}
#{303}{}{Shoo! Shoo! You'll stamp on and break something.}
{303}{}{嘘！嘘！你会踩坏东西的。}
#{304}{}{Go away, go! Leave me alone!}
{304}{}{走开，走开！别管我！}
#{305}{}{My spot! Find your own!}
{305}{}{我的位置！找到你自己的！}
#{306}{}{Go away! This is my collecting spot.}
{306}{}{走开！这是我的收藏点。}
#{400}{}{You, you want my spot, but it's mine!}
{400}{}{你，你想要我的位置，但那是我的！}
#{401}{}{Ouch, I'm leaving, quick.}
{401}{}{哎哟，我要走了，快。}
#{500}{}{What do you want here, huh? This is my place, if you want to collect, you have to go someplace else. Go, go!}
{500}{}{你想在这里干什么？这是我的地方，如果你想收集，你必须去别的地方。快走，快走！}
#{501}{}{What are you talking about?}
{501}{}{你在说什么？}
#{502}{}{OK, I'm going.}
{502}{}{好的，我要走了。}
#{503}{}{Huh?}
{503}{}{嗯？}
#{504}{}{Buuuuh!}
{504}{}{好啊！}
#{550}{}{What? You're asking me what I'm talking about? You know too well what, don't act like you don't know! Scram, off with you!}
{550}{}{什么？你在问我在说什么？你太清楚了，别装作不知道！快滚，跟你走！}
#{551}{}{I really have no idea.}
{551}{}{我真的不知道。}
#{552}{}{OK, I'm going.}
{552}{}{好的，我要走了。}
#{600}{}{Hm? You're not a collector? What are you doing here, in my spot? Well? Who are you?}
{600}{}{嗯？你不是收藏家？你在这里干什么，在我的位置？好？你是谁？}
#{601}{}{In fact, I don't really know, I've lost my memory.}
{601}{}{事实上，我真的不知道，我已经失去了记忆。}
#{602}{}{In fact, I don't really know, I've lost my memory.}
{602}{}{事实上，我真的不知道，我已经失去了记忆。}
#{603}{}{You could say I'm a traveler.}
{603}{}{你可以说我是个旅行者。}
#{604}{}{I'm an assassin! I kill people for money. Sometimes for pleasure.}
{604}{}{我是个刺客！我杀人是为了钱。有时是为了消遣。}
#{650}{}{So you dunno if you're a collector or not? You don't, huh?! Go away, my spot, shoo!}
{650}{}{你不知道你是不是收藏家？你不会吧？！走开，我的位置，嘘！}
#{651}{}{No, I'm sure of that.}
{651}{}{不，我肯定。}
#{652}{}{No, I'm sure of that.}
{652}{}{不，我肯定。}
#{653}{}{Ok, I'm going.}
{653}{}{好的，我要走了。}
#{700}{}{So go kill someone, go! What're you doing here? This spot's mine. You don't care about junk, shoo!}
{700}{}{所以去杀人，去！你在这里干什么？这个地方是我的。你不在乎垃圾，嘘！}
#{701}{}{You collect junk? Is it possible to make money that way?}
{701}{}{你收集垃圾？那样能赚钱吗？}
#{702}{}{Did you hear me? I kill people, so you better watch your tongue.}
{702}{}{你听见了吗？我杀人，所以你最好小心你的舌头。}
#{703}{}{OK, I'm going.}
{703}{}{好的，我要走了。}
#{750}{}{So why don't you go travel again? Go!}
{750}{}{那你为什么不再去旅行呢？快走！}
#{751}{}{OK, I'm going.}
{751}{}{好的，我要走了。}
#{752}{}{OK, I'm going.}
{752}{}{好的，我要走了。}
#{800}{}{Wait. You, wouldn't you want to make some money? Caps, you want some?}
{800}{}{等待。你，你不想赚点钱吗？瓶盖，你要吗？}
#{801}{}{What would I have to do?}
{801}{}{我该怎么办？}
#{802}{}{No, thanks.}
{802}{}{不用了，谢谢。}
#{850}{}{Wait. You, wouldn't you want to make some money? Caps, you want some?}
{850}{}{等待。你，你不想赚点钱吗？瓶盖，你要吗？}
#{851}{}{What would I have to do?}
{851}{}{我该怎么办？}
#{852}{}{No, thanks.}
{852}{}{不用了，谢谢。}
#{900}{}{Travel, that's it. Easy, innit? Carry some stuff, useful stuff, huh?}
{900}{}{旅行，就是这样。很简单，不是吗？带些有用的东西，嗯？}
#{901}{}{What stuff?}
{901}{}{什么东西？}
#{950}{}{Here, [He shows you a pile of junk.] Still useful! For Jonathan, he'll buy these. You'll give me }
{950}{}{在这里，[他给你看了一堆垃圾。]还是有用的！为了乔纳森，他会买这些。你会给我}
#{951}{}{ caps. It's all worth }
{951}{}{瓶盖。一切都值得}
#{952}{}{, yeah, that much. So you earn something. I'll show you where to find him. So, what d'ya say, huh?}
{952}{}{是的，就这么多。所以你赚了点钱。我带你去哪里找他。你说呢？}
#{953}{}{You want me to give you }
{953}{}{你想让我给你}
#{954}{}{You want me to give you }
{954}{}{你想让我给你}
#{955}{}{ bucks for junk?!}
{955}{}{垃圾要多少钱？！}
#{956}{}{Oh well, give it here. Where did you say I can find him?}
{956}{}{哦，好吧，给我。你说我在哪能找到他？}
#{957}{}{I'm sorry, I don't have }
{957}{}{对不起，我没有时间}
#{958}{}{ caps.}
{958}{}{瓶盖。}
#{1000}{}{Good price. Very good! You'll earn }
{1000}{}{好价钱。非常好！你会赢的}
#{1001}{}{ caps just for making the journey. That's good.}
{1001}{}{只是为了旅行。那很好。}
#{1002}{}{And why don't you take the junk to Jonathan yourself?}
{1002}{}{你为什么不自己把垃圾带给乔纳森？}
#{1003}{}{Oh well, give it here. Where did you say I can find him?}
{1003}{}{哦，好吧，给我。你说我在哪能找到他？}
#{1004}{}{I'm sorry, I don't have }
{1004}{}{对不起，我没有时间}
#{1005}{}{ caps.}
{1005}{}{瓶盖。}
#{1050}{}{It's quite a stretch and I gotta be here. There's lotsa' things here, big, big money! Someone might pick 'em up before I do. I gotta collect!}
{1050}{}{这是一段很长的路，我必须在这里。这里有很多东西，大的，大的钱！也许有人会在我之前把它们捡起来。我要收集！}
#{1051}{}{Fine then, give me the junk, here's your }
{1051}{}{好吧，把垃圾给我，这是你的}
#{1052}{}{ caps.}
{1052}{}{瓶盖。}
#{1053}{}{I don't believe you, I'm not interested.}
{1053}{}{我不相信你，我不感兴趣。}
#{1054}{}{I'm sorry, I don't have }
{1054}{}{对不起，我没有时间}
#{1055}{}{ caps.}
{1055}{}{瓶盖。}
#{1100}{}{Me neither, damn. That's bad. Know what, huh? Go get 'em, fetch 'em. Come back once you have enough, we'll do a trade. Go now, hurry.}
{1100}{}{我也是，该死。那太糟糕了。知道吗？去拿，拿回来。等你够了再来，我们做交易。快走，快点。}
#{1101}{}{See you.}
{1101}{}{再见。}
#{1150}{}{Show me the map, yeah, show it. Here! [He dabbed with his finger at a place on the map of your Pip-Boy.] Jonathan, he lives in a scrapyard. Tell him it's from Charlie. He'll give you a good price. So go now, hurry! Go!}
{1150}{}{给我看地图，是的，给我看。在这里！[他用手指在你的皮普男孩的地图上的一个地方轻拍。]乔纳森，他住在一个垃圾场里。告诉他是查理送的。他会给你一个好价钱的。快走，快点！快走！}
#{1151}{}{OK, see you.}
{1151}{}{好的，再见。}
#{1152}{}{OK, but if you've conned me and there's nothing there, I'll be back. And you're not going to like that.}
{1152}{}{好吧，但如果你骗了我，我会回来的。你不会喜欢的。}
#{1153}{}{Who's Charlie?}
{1153}{}{查理是谁？}
#{1200}{}{Lotsa' stuff here. I'll be here. Now you go, shoo!}
{1200}{}{洛萨的东西在这里。我会来的。现在你走，嘘！}
#{1201}{}{OK.}
{1201}{}{好 啊。}
#{1250}{}{I'm Charlie. The best collector in the world. Yes. And you go, you're wasting my time, vamoose!}
{1250}{}{我是查理。世界上最好的收藏家。对。你走，你在浪费我的时间，瓦穆斯！}
#{1251}{}{Possibly the only one in the world. Bye.}
{1251}{}{可能是世界上唯一的一个。再见。}
#{1252}{}{OK, but if you've conned me and there's nothing there, I'll be back. And you're not going to like that.}
{1252}{}{好吧，但如果你骗了我，我会回来的。你不会喜欢的。}
#{1300}{}{You, you're sure you're not a junk collector, huh? You're sure?}
{1300}{}{你，你确定你不是垃圾收藏家？你确定？}
#{1301}{}{Absolutely.}
{1301}{}{当然。}
#{1302}{}{Actually no, I'm leaving.}
{1302}{}{实际上不，我要走了。}
#{1350}{}{You, you're sure you're not a junk collector? You're sure?}
{1350}{}{你，你确定你不是垃圾收藏家？你确定？}
#{1351}{}{Absolutely.}
{1351}{}{当然。}
#{1352}{}{Actually no, I'm leaving.}
{1352}{}{实际上不，我要走了。}
#{1400}{}{Fine, then. Good. Wouldn't you want to make some money? Caps, you want some?}
{1400}{}{那好吧。很好。你不想赚点钱吗？瓶盖，你要吗？}
#{1401}{}{What would I have to do?}
{1401}{}{我该怎么办？}
#{1402}{}{No, thanks.}
{1402}{}{不用了，谢谢。}
#{1450}{}{Wait. You, wouldn't you want to make some money? Caps, you want some?}
{1450}{}{等待。你，你不想赚点钱吗？瓶盖，你要吗？}
#{1451}{}{What would I have to do?}
{1451}{}{我该怎么办？}
#{1452}{}{No, thanks.}
{1452}{}{不用了，谢谢。}
#{1500}{}{Not interested, you're wasting my time, gotta go looking for stuff. Go away, shoo, shoo!}
{1500}{}{不感兴趣，你在浪费我的时间，得去找东西了。走开，嘘，嘘！}
#{1501}{}{I've had enough of this, die!}
{1501}{}{我受够了，死吧！}
#{1502}{}{Fine, I'm leaving.}
{1502}{}{好吧，我要走了。}
#{1550}{}{Shh, not a word! Don't tell anyone. Yes. Money, lots of money! Yes. You, you want to make some money, too, huh?}
{1550}{}{嘘，一句话也别说！不要告诉任何人。对。钱，很多钱！对。你，你也想赚点钱吗？}
#{1551}{}{Sure, what do I have to do?}
{1551}{}{当然，我该怎么办？}
#{1552}{}{No, I don't want anything that's connected to junk.}
{1552}{}{不，我不想要任何和垃圾有关的东西。}
#{1600}{}{What? You go, move, shoo!}
{1600}{}{什么？你走，走，嘘！}
#{1601}{}{Shoo!}
{1601}{}{嘘！}
#{1602}{}{[Run away.]}
{1602}{}{[逃跑]}
#{1650}{}{You, strange, hm. You're not a collector, are you? Wanna make some money? Caps, lots of 'em.}
{1650}{}{你，奇怪，嗯。你不是收藏家，是吗？想赚钱吗？瓶盖，很多。}
#{1651}{}{Make monee!}
{1651}{}{做莫奈！}
#{1652}{}{Naah!}
{1652}{}{啊！}
#{1700}{}{Good, very good. This stuff right here's still useful! [He points at a pile of junk.] For Jonathan, he'll buy these. You'll give me }
{1700}{}{很好，很好。这里的东西还是有用的！[他指着一堆垃圾]对于乔纳森，他会买这些。你会给我}
#{1701}{}{ caps. It's worth much, much more, he'll pay you. So, what d'ya say, huh?}
{1701}{}{瓶盖。他会给你更多的钱。你说呢？}
#{1702}{}{He pay, goodie!}
{1702}{}{他付钱了，古蒂！}
#{1703}{}{ poor. Booo!}
{1703}{}{可怜的。嘘！}
#{1704}{}{Junk, eeew!}
{1704}{}{垃圾，eeew！}
#{1800}{}{Me too, damn. That's bad. What're we gonna do, huh? Oh, I know. I do. Go get 'em, fetch 'em. Come back once you have enough, we'll do a trade. Go now, hurry.}
{1800}{}{我也是，该死。那太糟糕了。我们该怎么办？哦，我知道。我愿意。去拿，拿回来。等你够了再来，我们做交易。快走，快点。}
#{1801}{}{Uff.}
{1801}{}{不明飞行物。}
#{1850}{}{Show me the map, yeah, show it. Here! [He dabbed with his finger at a place on the map of your Pip-Boy.] Jonathan, he lives in a scrapyard. Tell him it's from Charlie, you get it, do you? He'll give you a good price. So go now, hurry! Go!}
{1850}{}{给我看地图，是的，给我看。在这里！[他用手指在你的皮普男孩的地图上的一个地方轻拍。]乔纳森，他住在一个垃圾场里。告诉他是查理送的，你明白了吧？他会给你一个好价钱的。快走，快点！快走！}
#{1851}{}{Run, yeah.}
{1851}{}{快跑，是的。}
#{1900}{}{It's you again, huh? You're not supposed to be here, this here's mine. Told ya to go away. Shoo, move now!}
{1900}{}{又是你，嗯？你不应该在这里，这是我的。叫你走开。嘘，快走！}
#{1901}{}{What are you talking about?}
{1901}{}{你在说什么？}
#{1902}{}{OK, I'm going.}
{1902}{}{好的，我要走了。}
#{1903}{}{Huh?}
{1903}{}{嗯？}
#{1904}{}{Boo.}
{1904}{}{喝倒采。}
#{1950}{}{Do you have it, huh? Money, do you? }
{1950}{}{你有吗？钱，是吗？}
#{1951}{}{ caps.}
{1951}{}{瓶盖。}
#{1952}{}{No, not yet.}
{1952}{}{不，还没有。}
#{1953}{}{Here, take it.}
{1953}{}{来，拿着。}
#{1954}{}{Yeah, haha!}
{1954}{}{是啊，哈哈！}
#{1955}{}{Nah, huh.}
{1955}{}{不，嗯。}
#{2000}{}{Go get 'em, then come back. Run, hurry!}
{2000}{}{去找他们，然后回来。快跑，快点！}
#{2001}{}{OK.}
{2001}{}{好 啊。}
#{2002}{}{Ook.}
{2002}{}{哦。}
