#{100}{}{You see a woman.}
{100}{}{你看到一个女人。}
#{150}{}{You see the nanny.}
{150}{}{你看到保姆了。}
#{200}{}{You see a troubled-looking woman.}
{200}{}{你看到一个看起来很麻烦的女人。}
#{250}{}{You see David Carpenter's nanny.}
{250}{}{你看到大卫·卡彭特的保姆了。}
#{300}{}{::She cries.::}
{300}{}{●她哭了：}
#{301}{}{Don't talk to him, please go mind your own business.}
{301}{}{别跟他说话，请少管闲事。}
#{302}{}{Please don't kill me!}
{302}{}{请不要杀我！}
#{303}{}{Come when we are in the garden.}
{303}{}{我们在花园的时候来。}
#{500}{}{[She gave you a frightened look.] I don't want to know anything. Do what you have to do and go away quickly.}
{500}{}{[她惊恐地看了你一眼]我什么都不想知道。做你该做的，赶快离开。}
#{501}{}{OK.}
{501}{}{好 啊。}
#{502}{}{Okee.}
{502}{}{好的。}
#{550}{}{Who are you? What do you want?}
{550}{}{你是谁？你想要什么？}
#{551}{}{Are you David's nanny?}
{551}{}{你是大卫的保姆吗？}
#{552}{}{Uff.}
{552}{}{不明飞行物。}
#{600}{}{Yes, why?}
{600}{}{是的，为什么？}
#{601}{}{Tell me exactly what happened.}
{601}{}{告诉我到底发生了什么事。}
#{650}{}{I've already told the boss, and a few policemen after that.}
{650}{}{我已经告诉了老板，还有几个警察。}
#{651}{}{That doesn't matter, please tell me as well.}
{651}{}{没关系，也请告诉我。}
#{700}{}{I don't think this'll help to find David, but if you want: David was playing in the garden as is usually the case that time of day. I was sitting on the bench watching him. Then someone hit me in the head from behind and I lost consciousness. When I woke up, David was gone.}
{700}{}{我不认为这有助于找到大卫，但如果你愿意的话：大卫在花园里玩耍，就像平时一样。我坐在长凳上看着他。然后有人从后面打了我的头，我失去了知觉。当我醒来时，大卫不见了。}
#{701}{}{So he was usually in the garden at the time when he was kidnapped? Who knew about this?}
{701}{}{所以他被绑架时通常在花园里？谁知道这件事？}
#{702}{}{How much did you get paid?}
{702}{}{你拿了多少钱？}
#{750}{}{Everybody who works at the villa.}
{750}{}{所有在别墅工作的人。}
#{751}{}{One more question.}
{751}{}{还有一个问题。}
#{752}{}{Thanks, I'll be back.}
{752}{}{谢谢，我会回来的。}
#{800}{}{Yes?}
{800}{}{对？}
#{801}{}{The wound on your head doesn't look too serious.}
{801}{}{你头上的伤看起来不太严重。}
#{802}{}{Is it true that everybody in the villa is a police officer? Except you and the cook. And the sheriff's family, naturally.}
{802}{}{别墅里的人都是警察，这是真的吗？除了你和厨师。当然还有警长的家人。}
#{803}{}{It's strange that from every spot in the garden you have a terrific view. So what I don't get is how it is possible to overlook someone coming.}
{803}{}{奇怪的是，从花园里的每一个地方你都能看到极好的景色。所以我不明白的是怎么可能忽略一个人的到来。}
#{804}{}{How long have you been unconscious?}
{804}{}{你昏迷多久了？}
#{805}{}{How much does the sheriff pay you?}
{805}{}{治安官付给你多少钱？}
#{806}{}{How does the sheriff treat you?}
{806}{}{治安官对你怎么样？}
#{807}{}{So how much did you get paid?}
{807}{}{你的薪水是多少？}
#{808}{}{Thanks, I'll be back.}
{808}{}{谢谢，我会回来的。}
#{850}{}{I don't care how it looks, it wasn't very pleasant.}
{850}{}{我不在乎它看起来怎么样，它不是很令人愉快。}
#{851}{}{Of course, one more question...}
{851}{}{当然，还有一个问题。。。}
#{852}{}{Of course. Thanks, I'll be back.}
{852}{}{当然。谢谢，我会回来的。}
#{900}{}{Yes, that's true.}
{900}{}{是的，没错。}
#{901}{}{Hm, one more question...}
{901}{}{嗯，还有一个问题。。。}
#{902}{}{Hm, thanks, I'll be back.}
{902}{}{嗯，谢谢，我会回来的。}
#{950}{}{I actually get paid with my apartment and food. And when I need something else, like clothing, I am given caps, when Mr. Carpenter decides it's really necessary.}
{950}{}{我的公寓和食物都是我的报酬。当我需要别的东西时，比如衣服，我会得到瓶盖，当卡彭特先生认为这是真的必要的时候。}
#{951}{}{I see, I have another question....}
{951}{}{我明白了，我还有一个问题。。。。}
#{952}{}{I see, thanks, I'll be back.}
{952}{}{我明白了，谢谢，我会回来的。}
#{1000}{}{I'd like to know that as well. And I don't like where you're going with this.}
{1000}{}{我也想知道。我不喜欢你拿着这个去哪儿。}
#{1001}{}{Whether you like it or not, another question...}
{1001}{}{不管你喜不喜欢，还有一个问题。。。}
#{1002}{}{Whether you like it or not, I'll come back to talk to you later...}
{1002}{}{不管你喜不喜欢，我等会再来和你谈谈。。。}
#{1050}{}{About ten minutes.}
{1050}{}{大约十分钟。}
#{1051}{}{How can you tell if you were unconscious?}
{1051}{}{你怎么知道自己是不是昏迷了？}
#{1100}{}{I... I'm just guessing.}
{1100}{}{一、 。。。我只是在猜测。}
#{1101}{}{OK, one more question.}
{1101}{}{好的，还有一个问题。}
#{1102}{}{OK, thanks, I'll be back.}
{1102}{}{好的，谢谢，我会回来的。}
#{1150}{}{Well, he... I'm not allowed to talk about anything. That's none of your business, actually.}
{1150}{}{嗯，他。。。我什么都不许说。实际上，那不关你的事。}
#{1151}{}{Fine, one more question.}
{1151}{}{好吧，还有一个问题。}
#{1152}{}{Fine, thanks, I'll be back.}
{1152}{}{好的，谢谢，我会回来的。}
#{1200}{}{What are you talking about?}
{1200}{}{你在说什么？}
#{1201}{}{I'm telling you that the kidnappers must have worked with an insider. Someone to tell them where and when they could find David. Someone with access to him, someone who'll let them kidnap him when that person's with him. I can't see any cop doing it because now there are some hot times ahead for all of them. You barely get paid, God knows how Carpenter treats you and your fainting doesn't sound very convincing.}
{1201}{}{我告诉你绑匪肯定和一个内鬼合作过。告诉他们何时何地能找到大卫。有人能接近他，有人在他身边时会让他们绑架他。我看不到任何一个警察这么做，因为现在他们所有人都面临着一些危险时期。你几乎拿不到工资，天知道卡彭特是怎么对待你的，你的晕倒听起来不是很有说服力。}
#{1250}{}{Fine, then, I admit! I didn't want it to happen. They said they'll just kidnap him to get some money from Carpenter. They said they would return him unharmed. Still I refused, I'm too fond of David, but they threatened to kill me. There was nothing I could do!}
{1250}{}{好吧，那么，我承认！我不想发生这种事。他们说要绑架他，从卡彭特那里弄点钱。他们说会把他毫发无损地送回来。我还是拒绝了，我太喜欢大卫了，但是他们威胁要杀了我。我无能为力！}
#{1251}{}{Fine, where can I find them?}
{1251}{}{好吧，我在哪能找到它们？}
#{1300}{}{I... [She keeps whining.] I don't know. It was always them who contacted me. But they said someone'd be waiting at the Crimson Caravan brahmin pens in Little Hub exactly at eleven at night. In case of any troubles, they said. Just there and precisely at eleven, they said they wouldn't wait for long.}
{1300}{}{一、 。。。我不知道。总是他们联系我的。但是他们说晚上11点会有人在小中心的深红色大篷车双头牛围栏等着。他们说，万一有什么麻烦。就在那里，正好十一点，他们说他们不会等太久。}
#{1301}{}{I guess that's something.}
{1301}{}{我想这是个问题。}
#{1350}{}{Please! [She cries.] Please don't tell Mr. Carpenter. He'll surely beat me to death. I honestly didn't want it to happen. I hope David'll be alright. Please don't tell him.}
{1350}{}{拜托！请不要告诉卡彭特先生。他一定会把我打死的。我真的不想发生这种事。我希望大卫会好起来。请不要告诉他。}
#{1351}{}{We'll see.}
{1351}{}{我们拭目以待。}
#{1400}{}{What are you talking about?}
{1400}{}{你在说什么？}
#{1401}{}{I'm telling you that the kidnappers must have worked with an insider. Someone to tell them where and when they could find David. Someone with access to him, someone who'll let them kidnap him when that person's with him. I can't see any cop doing it because now there are some hot times ahead for all of them. I presume you barely get paid, God knows how Carpenter treats you and your fainting doesn't sound very convincing.}
{1401}{}{我告诉你绑匪肯定和一个内鬼合作过。告诉他们何时何地能找到大卫。有人能接近他，有人在他身边时会让他们绑架他。我看不到任何一个警察这么做，因为现在他们所有人都面临着一些危险时期。我猜你几乎拿不到工资，天知道卡彭特是怎么对待你的，你的晕倒听起来不太有说服力。}
#{1450}{}{Yes?}
{1450}{}{对？}
#{1451}{}{The wound on your head doesn't look too serious.}
{1451}{}{你头上的伤看起来不太严重。}
#{1452}{}{Is it true that everybody in the villa is a police officer? Except you and the cook. And the sheriff's family, naturally.}
{1452}{}{别墅里的人都是警察，这是真的吗？除了你和厨师。当然还有警长的家人。}
#{1453}{}{It's strange that from every spot in the garden you have a terrific view so what I don't get is how it is possible to overlook someone coming.}
{1453}{}{奇怪的是，从花园里的每一个地方你都能看到美妙的景色，所以我不明白的是，怎么可能忽视一个人的到来。}
#{1454}{}{How long have you been unconscious?}
{1454}{}{你昏迷多久了？}
#{1455}{}{How much does the sheriff pay you?}
{1455}{}{治安官付给你多少钱？}
#{1456}{}{How does the sheriff treat you?}
{1456}{}{治安官对你怎么样？}
#{1457}{}{So how much did you get paid?}
{1457}{}{你的薪水是多少？}
#{1458}{}{I'll be back.}
{1458}{}{我会回来的。}
#{1459}{}{Uff.}
{1459}{}{不明飞行物。}
#{1500}{}{Oh, it's you.}
{1500}{}{哦，是你。}
#{1501}{}{What's going on?}
{1501}{}{发生什么事？}
#{1502}{}{Huh?}
{1502}{}{嗯？}
#{1550}{}{You know, they interrogated me. They didn't believe my story. Please listen to me! It was terrible but I didn't say anything! I've come to warn you they're after something. [As she's speaking, you've noticed a few cops heading your direction.]}
{1550}{}{你知道，他们审问了我。他们不相信我的故事。请听我说！太可怕了，但我什么也没说！我来警告你他们在找什么东西。[她说话的时候，你注意到有几个警察朝你的方向走去。]}
#{1551}{}{Cops! You stupid bitch, you've brought them here! They must have followed you.}
{1551}{}{警察！你这个愚蠢的婊子，你把他们带到这里来了！他们一定跟踪了你。}
#{1552}{}{Copses!}
{1552}{}{警察！}
#{1600}{}{Yes?}
{1600}{}{对？}
#{1601}{}{Who are you?}
{1601}{}{你是谁？}
#{1602}{}{That's a mistake.}
{1602}{}{那是个错误。}
#{1603}{}{Uff.}
{1603}{}{不明飞行物。}
#{1650}{}{I don't know what your job here is but you should focus on it and leave me alone.}
{1650}{}{我不知道你在这里的工作是什么，但你应该专注于它，让我一个人呆着。}
#{1651}{}{I apologize.}
{1651}{}{我道歉。}
#{1700}{}{I don't know what your job here is but you should focus on it and leave me alone.}
{1700}{}{我不知道你在这里的工作是什么，但你应该专注于它，让我一个人呆着。}
#{1701}{}{I apologize.}
{1701}{}{我道歉。}
