#{100}{}{You see a bartender.}
{100}{}{你看到一个酒保。}
#{150}{}{You see Clark.}
{150}{}{你看到克拉克了。}
#{200}{}{You see a grubby bartender with a fatter build. There are flies swarming around him.}
{200}{}{你看到一个身材更胖的肮脏的酒保。苍蝇成群地围着他。}
#{250}{}{You see Clark, the bartender and owner of the Crater. There are flies swarming around him.}
{250}{}{你看克拉克，酒保和火山口的主人。苍蝇成群地围着他。}
#{300}{}{Says "make me a Pan Galactic Gargle Blaster"! Who ever heard of such a steaming pile of crap?!}
{300}{}{说“让我成为泛银河漱口爆破手”！谁听说过这么一堆废话？！}
#{301}{}{::smile:: The third glass gets everyone.}
{301}{}{●微笑：：第三杯让所有人都喝。}
#{302}{}{Ha! I warned you it's pretty darn strong.}
{302}{}{哈！我警告过你，它真是太强了。}
#{303}{}{What... Holy shit! My distillery!}
{303}{}{什么。。。天啊！我的酒厂！}
#{304}{}{You must have been out for a few minutes.}
{304}{}{你一定出去几分钟了。}
#{305}{}{You must have been out for a few minutes.}
{305}{}{你一定出去几分钟了。}
#{306}{}{The situation's gotten so much out of your hands that the police can no longer ignore it. It's going to be really hot for you in Sedit soon.}
{306}{}{情况已经从你手中失控了，警察再也不能无视了。很快你在赛迪特会很热的。}
#{307}{}{The situation's gotten so much out of your hands that the police can no longer ignore it. It's going to be really hot for you in Sedit soon.}
{307}{}{情况已经从你手中失控了，警察再也不能无视了。很快你在赛迪特会很热的。}
#{400}{}{I'll teach you to behave in my bar!}
{400}{}{我要教你在我的酒吧里规矩点！}
#{500}{}{What'll it be?}
{500}{}{会是什么？}
#{501}{}{Who are you?}
{501}{}{你是谁？}
#{502}{}{I'll have something to drink.}
{502}{}{我要喝点东西。}
#{503}{}{I'll have something to drink.}
{503}{}{我要喝点东西。}
#{504}{}{What if I'm looking for a little "fun"? If you know what I mean.}
{504}{}{如果我想找点“乐趣”呢？如果你明白我的意思。}
#{505}{}{Hoogh.}
{505}{}{呼。}
#{506}{}{Nuffin', ghee!}
{506}{}{努芬，酥油！}
#{507}{}{Sedit Caravan are unhappy about your place being a competition for their establishment.}
{507}{}{赛迪特商队不高兴你的地方是他们的建立竞争。}
#{508}{}{Actually, nothing.}
{508}{}{实际上，没什么。}
#{550}{}{I'm standing here behind the bar, so who do you think I am? I'm the bartender. And I also happen to be the owner of this place.}
{550}{}{我站在吧台后面，你以为我是谁？我是酒保。我也是这个地方的主人。}
#{551}{}{Hi, I'm }
{551}{}{嗨，我是}
#{552}{}{This bar is one ghastly hole! It looks like you've been visited by a bomb recently.}
{552}{}{这酒吧真是个可怕的洞！你最近好像被炸弹袭击了。}
#{553}{}{I'm leaving.}
{553}{}{我要走了。}
#{600}{}{And I'm Clark. Who the hell cares, anyway?! Will you have something to drink or are you going to flap your tongue dry like that?}
{600}{}{我是克拉克。不管怎样，谁在乎？！你要喝点什么吗？还是要那样把舌头擦干？}
#{601}{}{Yeah, I intend to continue flapping my tongue just as dry as it is!}
{601}{}{是的，我打算继续拍我的舌头就像它是干！}
#{602}{}{Sure I'll have something to drink.}
{602}{}{我当然要喝点东西。}
#{603}{}{Actually, I'd like to have a little "fun", if you know what I mean.}
{603}{}{事实上，如果你知道我的意思，我想找点乐子。}
#{604}{}{Actually, I'd like to have a little "fun", if you know what I mean.}
{604}{}{事实上，如果你知道我的意思，我想找点乐子。}
#{605}{}{I'm leaving.}
{605}{}{我要走了。}
#{650}{}{Yeah, that's why it's called the Crater. You gonna have something already?}
{650}{}{是啊，这就是为什么叫火山口。你已经有东西了？}
#{651}{}{So what've you got?}
{651}{}{你有什么发现？}
#{652}{}{Actually, I'd like to have a little "fun", if you know what I mean.}
{652}{}{事实上，如果你知道我的意思，我想找点乐子。}
#{653}{}{Actually, I'd like to have a little "fun", if you know what I mean.}
{653}{}{事实上，如果你知道我的意思，我想找点乐子。}
#{654}{}{No, I'm out of here.}
{654}{}{不，我要走了。}
#{700}{}{Then go flap it somewhere else! I'm not interested in your bullshit.}
{700}{}{那就去别的地方吧！我对你的胡说八道不感兴趣。}
#{701}{}{And what if I'm not going anywhere?}
{701}{}{如果我哪儿也不去呢？}
#{702}{}{Fine, I'm leaving.}
{702}{}{好吧，我要走了。}
#{750}{}{[He pulls a sawn-off shotgun from under the counter and points it in your face.] I'll blow your bloody head off!}
{750}{}{[他从柜台底下掏出一把锯下来的猎枪指着你的脸]我要把你该死的脑袋轰下来！}
#{751}{}{Calm down. I think I'll have something to drink, after all.}
{751}{}{冷静。我想我还是要喝点东西。}
#{752}{}{Calm down. I think I'll have something to drink, after all.}
{752}{}{冷静。我想我还是要喝点东西。}
#{753}{}{Try it!}
{753}{}{试试看！}
#{800}{}{I got beer, rum, and booze I make myself. Damn strong stuff.}
{800}{}{我有啤酒，朗姆酒，还有我自己做的酒。该死的强壮的东西。}
#{801}{}{Give me beer.}
{801}{}{给我啤酒。}
#{802}{}{Give me rum.}
{802}{}{给我朗姆酒。}
#{803}{}{I'll try the booze.}
{803}{}{我来试试酒。}
#{804}{}{I'd better pass.}
{804}{}{我还是过去吧。}
#{850}{}{Strong, ain't it?}
{850}{}{很强，不是吗？}
#{851}{}{I can feel it eating through my insides. Give me another one.}
{851}{}{我能感觉到它在吞噬我的内脏。再给我一个。}
#{852}{}{Yeah, I'd say. I'd better stop right now.}
{852}{}{是的，我想说。我最好现在就停下来。}
#{900}{}{Dammit, man, not everybody stays on their feet after the second glass.}
{900}{}{该死的，伙计，不是每个人喝了第二杯后都能站起来的。}
#{901}{}{I want it, I want... Heh... I want it! Anotha'wun!}
{901}{}{我想要它，我想要。。。嘿。。。我想要它！阿诺莎温！}
#{902}{}{Woa jeez! Heeh... I got enough.}
{902}{}{哇天哪！嘿。。。我受够了。}
#{950}{}{That there's my slut, name of Loiz. She's a bit sloppy, alright, but she knows her stuff.}
{950}{}{那是我的荡妇，名叫洛伊兹。她有点邋遢，好吧，但她知道自己的事。}
#{951}{}{Now I'd like to have a drink.}
{951}{}{现在我想喝一杯。}
#{952}{}{Fine, I'll go see her.}
{952}{}{好吧，我去看她。}
#{1000}{}{You can have it with me, and more than just a little. On top of that, you'll get it for free that way. [He smiles and reveals a line of black teeth.] Otherwise, that there's my girl Loiz. She's a bit sloppy, alright, but she knows her stuff.}
{1000}{}{你可以和我在一起，不仅仅是一点点。除此之外，你还可以通过这种方式免费获得。[他微笑着露出一排黑色的牙齿]否则，那就是我的女儿洛伊兹。她有点邋遢，好吧，但她知道自己的事。}
#{1001}{}{Come on, you stud.}
{1001}{}{快点，你这个笨蛋。}
#{1002}{}{Now I'd like to have a drink.}
{1002}{}{现在我想喝一杯。}
#{1003}{}{I guess I'll go see her.}
{1003}{}{我想我会去看她。}
#{1050}{}{Dammit, woman, not everybody stays on their feet after the second glass.}
{1050}{}{妈的，女人，不是每个人喝了第二杯后都能站起来的。}
#{1051}{}{I want it, I want... Heh... I want it! Anotha'wun!}
{1051}{}{我想要它，我想要。。。嘿。。。我想要它！阿诺莎温！}
#{1052}{}{Woah jeez! Heeh... I got enough.}
{1052}{}{哇天哪！嘿。。。我受够了。}
#{1100}{}{Can I be of service with anything else?}
{1100}{}{我能为您效劳吗？}
#{1101}{}{Now I need a drink.}
{1101}{}{现在我需要喝一杯。}
#{1102}{}{No, thank you.}
{1102}{}{不用了，谢谢。}
#{1150}{}{I mean, man, you look like you've got enough. I don't give a hoot, just don't barf in my bar. You want a beer, rum or my booze?}
{1150}{}{我是说，伙计，你看起来已经受够了。我一点也不在乎，只是不要在我的酒吧里呕吐。你要啤酒，朗姆酒还是我的酒？}
#{1151}{}{Beer.}
{1151}{}{啤酒。}
#{1152}{}{Brum.}
{1152}{}{布鲁姆。}
#{1153}{}{Booooze.}
{1153}{}{酗酒。}
#{1154}{}{Yuck.}
{1154}{}{讨厌。}
#{1200}{}{I mean, woman, you look like you've got enough. I don't give a hoot, just don't barf in my bar. You want a beer, rum or my booze?}
{1200}{}{我是说，女人，你看起来已经受够了。我一点也不在乎，只是不要在我的酒吧里呕吐。你要啤酒，朗姆酒还是我的酒？}
#{1201}{}{Beer.}
{1201}{}{啤酒。}
#{1202}{}{Brum.}
{1202}{}{布鲁姆。}
#{1203}{}{Booooze.}
{1203}{}{酗酒。}
#{1204}{}{Yuck.}
{1204}{}{讨厌。}
#{1250}{}{Strong, ain't it?}
{1250}{}{很强，不是吗？}
#{1251}{}{Hee. [You point at the glass.]}
{1251}{}{嘿。[你指着玻璃。]}
#{1252}{}{Uff.}
{1252}{}{不明飞行物。}
#{1300}{}{Damn good. No one who's drunk has managed to stay on their feet after two shots of my booze. You want more?}
{1300}{}{太好了。喝了两杯我的酒，没人能站起来。你还要吗？}
#{1301}{}{Hee. [You're trying to point at your glass but you're having difficulties locking onto it.]}
{1301}{}{嘿。[你试图指着你的杯子，但你很难把它锁上。]}
#{1302}{}{Uff.}
{1302}{}{不明飞行物。}
#{1350}{}{[He puts the shotgun away.] I got beer, rum, and booze I make myself. Damn strong stuff.}
{1350}{}{[他把猎枪收起来]我有啤酒，朗姆酒，还有我自己做的酒。该死的强壮的东西。}
#{1351}{}{Give me beer.}
{1351}{}{给我啤酒。}
#{1352}{}{Give me rum.}
{1352}{}{给我朗姆酒。}
#{1353}{}{I'll try the booze.}
{1353}{}{我来试试酒。}
#{1354}{}{I'll better pass.}
{1354}{}{我还是过去吧。}
#{1400}{}{So?}
{1400}{}{所以呢？}
#{1401}{}{You see, Nicol sent me to put this place out of business. But I don't want to spill blood if it isn't necessary. Destroy the distillery and leave Sedit, that should do the trick.}
{1401}{}{你看，尼科尔派我来是为了让这个地方停业。但如果没有必要的话我不想流血。毁掉酒厂，留下塞迪特，这样就行了。}
#{1402}{}{You see, Nicol sent me to put this place out of business. But I don't want to spill blood if it isn't necessary. Destroy the distillery and leave Sedit, that should do the trick.}
{1402}{}{你看，尼科尔派我来是为了让这个地方停业。但如果没有必要的话我不想流血。毁掉酒厂，留下塞迪特，这样就行了。}
#{1403}{}{You know what? Forget it.}
{1403}{}{你知道吗？算了吧。}
#{1450}{}{I'm not going to leave everything here just because that's what Nicol wants. So get out.}
{1450}{}{我不会因为尼科尔想要什么就把一切都留在这里。所以出去吧。}
#{1451}{}{I'll give you 1000 caps and you'll never show your face around here again. That's more than enough for this flea pit.}
{1451}{}{我给你1000顶瓶盖，你再也不会在这里露面了。对于这个跳蚤坑来说这已经足够了。}
#{1452}{}{If you don't leave now, I'll make sure you'll die a slow and painful death. First, we'll see if your bitch can scream in pain more than when she's faking an orgasm. Then I'll carve you to pieces just like they do with brahmins in a slaughterhouse.}
{1452}{}{如果你现在不走，我会让你慢慢痛苦地死去。首先，我们来看看你的婊子在痛苦中的尖叫是否比假装高潮时更厉害。然后我会把你切成碎片就像屠宰场里的双头牛一样。}
#{1453}{}{Suit yourself.}
{1453}{}{随便你。}
#{1500}{}{It's a deal.}
{1500}{}{就这么定了。}
#{1501}{}{Fine, now make like a tree and leave.}
{1501}{}{好吧，现在像棵树一样离开。}
#{1550}{}{Damn. This town's always been full of shit, anyway.}
{1550}{}{该死。不管怎么说，这个镇上一直都是狗屎。}
#{1551}{}{Fine, now make like a tree and leave.}
{1551}{}{好吧，现在像棵树一样离开。}
#{1600}{}{I think I'll blow your head off instead! [He pulls out the sawn-off shotgun.]}
{1600}{}{我想我会把你的头打爆的！[他拿出锯下来的猎枪。]}
#{1601}{}{We'll see.}
{1601}{}{我们拭目以待。}
