#{100}{}{You find yourself in the outskirts of a huge metropolis spreading around the crossroads of pre-war motorways. The very first glance at the city reveals that the place is vibrant with life; you hear the clamor of people arguing and brahmins mooing.}
{100}{}{你会发现自己身处一座大都市的郊区，遍布战前高速公路的十字路口。第一眼看到这座城市，你就会发现这个地方充满了生机；你会听到人们的吵闹声和双头牛的呻吟声。}
#{101}{}{You find yourself in the outskirts of a huge metropolis spreading around the crossroads of pre-war motorways. The very first glance at the city reveals that the place is vibrant with life; you hear the clamor of people arguing and brahmins mooing.}
{101}{}{你会发现自己身处一座大都市的郊区，遍布战前高速公路的十字路口。第一眼看到这座城市，你就会发现这个地方充满了生机；你会听到人们的吵闹声和双头牛的呻吟声。}
#{200}{}{You've killed all the brahmin from the herd belonging to Frederyk's Dream.}
{200}{}{你杀死了所有属于弗雷德里克梦想的双头牛。}
#{201}{}{You've killed all the brahmin from the herd belonging to Frederyk's Dream.}
{201}{}{你杀死了所有属于弗雷德里克梦想的双头牛。}
