#{100}{}{So what's this about?}
{100}{}{这是怎么回事？}
#{200}{}{I'd like to discuss the sheriff's demotion with senor Rodriguez.}
{200}{}{我想和罗德里格斯先生讨论一下治安官的降职问题。}
#{201}{}{I know that Carpenter's ignorance is of use to Senor, but a sheriff who would work with respect directly for Senor...}
{201}{}{我知道卡彭特的无知对先生是有用的，但是一个直接尊重先生的警长。。。}
#{202}{}{...just as I've been doing it as a deputy for a generous reward from Senor until now, might seem like a more suitable arrangement to him.}
{202}{}{……就像我作为副手一直在做的那样，为了得到参议员的慷慨奖励，对他来说，这似乎是一个更合适的安排。}
#{203}{}{I'm not asking for help, I am merely asking for Senor's permission and I'd like to know whether he's going to continue supporting me in the sheriff's post.}
{203}{}{我不是在请求帮助，我只是请求参议员的允许，我想知道他是否会继续支持我担任治安官。}
#{300}{}{I'll inform Senor and let you know when you can talk to him.}
{300}{}{我会通知先生，告诉你什么时候可以和他谈谈。}
#{301}{}{And now make like a tree.}
{301}{}{现在变成一棵树。}
#{400}{}{Thank you.}
{400}{}{非常感谢。}
