#{101}{}{You see iron door.}
{101}{}{你看到铁门了。}
#{132}{}{You see solid door. It seems there's no chance of prying them open.}
{132}{}{你看到一扇实心门。看来没有机会撬开它们。}
#{193}{}{The explosives didn't leave as much as a scratch on this door.}
{193}{}{爆炸物没有在这扇门上留下一点划痕。}
#{195}{}{You failed to find any traps on the door.}
{195}{}{你没发现门上有陷阱。}
#{212}{}{The door cannot be unlocked.}
{212}{}{门不能开锁。}
#{213}{}{The door won't budge.}
{213}{}{门一动也不动。}
