#{100}{}{You see a ghoul.}
{100}{}{你看到一个僵尸。}
#{150}{}{You see Ivet.}
{150}{}{你看艾薇特。}
#{200}{}{You see a strange ghoul. He's well groomed, with earrings and lipstick on his lips.}
{200}{}{你看到一个奇怪的僵尸。他打扮得很好，嘴唇上戴着耳环和口红。}
#{250}{}{You see Ivet, the waitress at Falcon's Flight. She's prettying herself up.}
{250}{}{你看艾薇特，猎鹰航班的女服务员。她在打扮自己。}
#{251}{}{You see Ivet, the waitress at Falcon's Flight. She has a satisfied look on her face.}
{251}{}{你看艾薇特，猎鹰航班的女服务员。她脸上露出满意的神情。}
#{300}{}{Welcome to Falcon's Flight.}
{300}{}{欢迎来到Falcon的航班。}
#{301}{}{I'm very glad to see you again, sugar.}
{301}{}{很高兴再次见到你，甜心。}
#{302}{}{Get out of here!}
{302}{}{离开这里！}
#{303}{}{I don't ever want to see you again!}
{303}{}{我再也不想见到你了！}
#{304}{}{You're not welcome in Falcon's Flight.}
{304}{}{猎鹰号不欢迎你。}
#{350}{}{Ah.}
{350}{}{啊。}
#{500}{}{[As soon as you enter the place, a ghoul dressed in a short apron with lipstick and women's earrings speaks to you in a woman's voice.] Welcome to Falcon's Flight, stranger. What brought you here? Whether you are hungry, thirsty or just looking for a place to lay down your head, you've come to the right place. All you have to do is go directly to the bar.}
{500}{}{[当你进入这个地方的时候，一个穿着口红和女人耳环的僵尸用女人的声音跟你说话]欢迎来到猎鹰的飞行，陌生人。什么风把你吹来了？不管你是饿了，渴了，还是只是想找个地方躺下，你来对地方了。你只要直接去酒吧就行了。}
#{501}{}{[As soon as you enter the place, a ghoul dressed in a short apron with lipstick and women's earrings speaks to you in a woman's voice.] Welcome to Falcon's Flight, stranger. What brought you here? Whether you are hungry, thirsty or just looking for a place to lay down your head, you've come to the right place. All you have to do is go directly to the bar.}
{501}{}{[当你进入这个地方的时候，一个穿着口红和女人耳环的僵尸用女人的声音跟你说话]欢迎来到猎鹰的飞行，陌生人。什么风把你吹来了？不管你是饿了，渴了，还是只是想找个地方躺下，你来对地方了。你只要直接去酒吧就行了。}
#{502}{}{You look... Ahem... like a waitress.}
{502}{}{你看起来。。。啊哼。。。像个女招待。}
#{503}{}{I like this place. Who works here besides you?}
{503}{}{我喜欢这个地方。除了你还有谁在这里工作？}
#{504}{}{You make me sick. Get away from me, filthy ghoul!}
{504}{}{你让我恶心。离我远点，肮脏的僵尸！}
#{505}{}{Uhh?}
{505}{}{嗯？}
#{506}{}{Thanks for the info. I'll go there right away.}
{506}{}{谢谢你的信息。我马上就去。}
#{550}{}{Why are you saying it as if you were surprised? I've worked as a waitress for many years. There's no one better than me when it comes to welcoming and serving guests. It's a terrible shame I don't get enough of any of those lately. You know, we rarely get more than one or two customers a day. I don't understand why there are so few of them. But I don't want to trouble you with this. That's purely our business.}
{550}{}{你为什么说得好像很惊讶似的？我做服务员已经很多年了。在招待客人方面，没有人比我更好。真遗憾，我最近对这些东西都不够了解。你知道，我们一天的顾客很少超过一两个。我不明白为什么他们这么少。但我不想给你添麻烦。那纯粹是我们的事。}
#{552}{}{I'm sure you'll manage to sort it all out. Who works here besides you?}
{552}{}{我相信你会把一切都解决的。除了你还有谁在这里工作？}
#{553}{}{Thanks for the info. I'm leaving.}
{553}{}{谢谢你的信息。我要走了。}
#{600}{}{How dare you insult me like this, you ruffian? People who can't behave themselves are not welcome in Falcon's Flight. Leave immediately!}
{600}{}{你竟敢这样侮辱我，你这个恶棍？不守规矩的人不受欢迎。马上离开！}
#{601}{}{How dare you insult me like this, foul mouth? People who can't behave themselves are not welcome in Falcon's Flight. Leave immediately!}
{601}{}{你竟敢这样侮辱我，臭嘴？不守规矩的人不受欢迎。马上离开！}
#{602}{}{I'm not going anywhere until I've cleaned this place of all ghoul filth. And I'm going to start with you.}
{602}{}{我哪也不去，除非我把这里所有的僵尸的脏东西都清理干净。我要从你开始。}
#{603}{}{As you wish.}
{603}{}{如你所愿。}
#{650}{}{There's three of us. The place is run by Rene. He's a very nice and hard working boss. I'm sure you'll like him when you get to know him. Then there's Mimi. But you'd do better not to speak to her at all. She's been acting obsessively ever since we were attacked. She doesn't leave the kitchen and is permanently lost in all kinds of crazy plans. I don't understand her at all, poor girl.}
{650}{}{我们有三个人。这个地方是雷内经营的。他是一个非常好而且工作努力的老板。我相信你了解他以后会喜欢他的。然后是咪咪。但你最好不要和她说话。自从我们被袭击后，她就一直很痴迷。她不离开厨房，永远沉浸在各种疯狂的计划中。我一点也不了解她，可怜的姑娘。}
#{651}{}{And you're a... a waitress?}
{651}{}{你是个。。。服务员？}
#{653}{}{Thanks for the info. I'm leaving.}
{653}{}{谢谢你的信息。我要走了。}
#{700}{}{Go see Rene. He's right there behind the bar.}
{700}{}{去见雷内。他就在吧台后面。}
#{701}{}{Yeah! Bye.}
{701}{}{是 啊！再见。}
#{750}{}{Hold on for a while. Wouldn't you want to come upstairs and have a look at something in my room? [She tries to produce a lascivious smile that fully reveals blackened remains of her teeth and rotting gums.] You're a very handsome man and it's been a long time since I've felt a man's gentle touch.}
{750}{}{等等。你不想上楼看看我房间里的东西吗？[她试图露出一个淫荡的微笑，露出她发黑的牙齿和腐烂的牙龈。]你是个非常英俊的男人，我很久没有感受到男人的温柔抚摸了。}
#{751}{}{You can forget about any gentle touching, freak! I wouldn't touch you with a pole seven feet long.}
{751}{}{你可以忘记任何温柔的抚摸，怪胎！我不会用七英尺长的杆子碰你。}
#{752}{}{I'm not sure that's a good idea.}
{752}{}{我不确定那是个好主意。}
#{753}{}{Why not? That could be... Interesting.}
{753}{}{为什么不？那可能是。。。很有趣。}
#{800}{}{You're a stupid foul mouth! I don't understand what I saw in you. Get out of my sight!}
{800}{}{你是个愚蠢的臭嘴！我不明白我在你身上看到了什么。快离开我的视线！}
#{801}{}{Gladly, you ghoul freak. Good-bye forever.}
{801}{}{很高兴，你这个僵尸。永远再见。}
#{850}{}{Please. I promise you won't regret it. [She leans towards you and gives you a long kiss. You feel burnt skin touch your lips and a stench of cadaverous decay punched you in the nose. The ghoul woman is so close you can recognize even the tiniest elements of the blistered tissue on her monstrous face.]}
{850}{}{拜托。我保证你不会后悔的。[她向你倾斜，给了你一个长长的吻。你感觉到灼伤的皮肤接触到你的嘴唇，一股腐烂的恶臭打在你的鼻子上。僵尸的女人离我们如此之近，你甚至可以认出她那可怕的脸上起泡组织中最微小的元素。]}
#{851}{}{[Push her away.] What are you trying on me, disgusting ghoul?! You want me to catch some kind of infection?}
{851}{}{[把她推开]你想对我做什么，恶心的僵尸？！你想让我染上某种传染病？}
#{852}{}{Fine, then. I'll trust you.}
{852}{}{那好吧。我相信你。}
#{853}{}{Eh, I think not. Neither of us would like it. Bye.}
{853}{}{呃，我想不是。我们都不喜欢。再见。}
#{900}{}{[Her bony claw violently squeezes your wrist.] Come on, then. My room's right opposite the staircase.}
{900}{}{[她那骨瘦如柴的爪子使劲捏你的手腕。]那就来吧。我的房间就在楼梯对面。}
#{901}{}{[Follow her.]}
{901}{}{[跟着她。]}
#{950}{}{Aah, I've long forgotten what it feels like to make love to somebody. Thank you. You were great.}
{950}{}{啊，我早就忘了和别人做爱的感觉了。非常感谢。你太棒了。}
#{951}{}{You were great, too.}
{951}{}{你也很棒。}
#{952}{}{I'm sorry I can't say the same thing about you. It felt like doing it with a rotting corpse.}
{952}{}{对不起，我不能对你说同样的话。感觉就像和一具腐烂的尸体在一起。}
#{953}{}{Yeah, sure. I'm gonna have to go. Bye.}
{953}{}{是的，当然。我得走了。再见。}
#{954}{}{Aah, I've long forgotten what it feels like to make love to somebody. This was a very wild reminder. I thought all the bones in my body would rattle apart. You were great. Thank you.}
{954}{}{啊，我早就忘了和别人做爱的感觉了。这是一个非常疯狂的提醒。我以为我身上所有的骨头都会嘎嘎作响。你太棒了。非常感谢。}
#{1000}{}{[She giggles. A hoarse chortle resounds in the room.] Aren't you a cutie pie. You've completely made my day.}
{1000}{}{[她咯咯地笑。房间里回荡着沙哑的笑声。]你不是个可爱的派吗。你完全让我开心。}
#{1001}{}{I was glad to do so. Now rest for a while. I'll see myself out.}
{1001}{}{我很高兴这么做。现在休息一会儿。我自己出去。}
#{1050}{}{You're a stupid foul mouth! I don't understand what I saw in you. Leave my room immediately!}
{1050}{}{你是个愚蠢的臭嘴！我不明白我在你身上看到了什么。马上离开我的房间！}
#{1051}{}{Gladly, you clumsy freak of a ghoul. Good-bye forever.}
{1051}{}{很高兴，你这个笨手笨脚的僵尸。永远再见。}
