#{100}{}{You see a man from the caravans.}
{100}{}{你看到一个大篷车里的人。}
#{101}{}{You see a woman from the caravans.}
{101}{}{你看到一个大篷车里的女人。}
#{200}{}{You see a man from the caravans. He works for Sedit Caravan.}
{200}{}{你看到一个大篷车里的人。他为赛迪特商队工作。}
#{201}{}{You see a woman from the caravans. She works for Sedit Caravan.}
{201}{}{你看到一个大篷车里的女人。她为赛迪特商队工作。}
#{300}{}{I love working with the caravans. Lots of money and adventure.}
{300}{}{我喜欢和大篷车一起工作。很多钱和冒险。}
#{301}{}{Can't talk to you right now.}
{301}{}{现在不能和你说话。}
#{302}{}{Kevin can really get on your nerves sometimes.}
{302}{}{凯文有时真的会惹你生气。}
#{303}{}{Only the best work for Sedit Caravan.}
{303}{}{只有塞迪特商队最好的作品。}
#{304}{}{Sedit Caravan was the first caravan company in this town.}
{304}{}{塞迪特商队是这个镇上第一个商队。}
#{305}{}{Sedit Caravan's the best.}
{305}{}{塞迪特商队是最好的。}
#{306}{}{I have to shovel the manure.}
{306}{}{我得铲粪肥。}
#{307}{}{I have to get the brahmins ready.}
{307}{}{我得把双头牛准备好。}
#{308}{}{I have carts to load.}
{308}{}{我有手推车要装。}
#{309}{}{Raiders are becoming a bigger problem every day.}
{309}{}{袭击者每天都在成为一个更大的问题。}
#{310}{}{It's been swarming with raiders out there recently.}
{310}{}{最近到处都是袭击者。}
#{311}{}{Hope the weather'll be better next time we depart.}
{311}{}{希望我们下次出发时天气会好些。}
#{312}{}{If you're looking for work, go find Kevin.}
{312}{}{如果你在找工作，去找凯文。}
#{313}{}{Talk to Kevin if you want a job.}
{313}{}{如果你想找工作，就和凯文谈谈。}
#{314}{}{Hey there, pal.}
{314}{}{嘿，伙计。}
#{315}{}{You gonna join the next caravan?}
{315}{}{你要加入下一个商队吗？}
#{316}{}{Don't worry, the next caravan's gettin' ready.}
{316}{}{别担心，下一个车队已经准备好了。}
#{317}{}{Hey there, girl.}
{317}{}{嘿，姑娘。}
#{318}{}{Someone oughta kick your ass for leaving the caravan.}
{318}{}{有人应该因为你离开商队而揍你一顿。}
#{319}{}{It's the cargo that matters.}
{319}{}{重要的是货物。}
#{320}{}{You don't run away from the caravan.}
{320}{}{你不能逃离大篷车。}
#{321}{}{Coward.}
{321}{}{胆小鬼。}
#{322}{}{Someone oughta kick your ass for leaving the caravan.}
{322}{}{有人应该因为你离开商队而揍你一顿。}
#{350}{}{I'm supposed to pay ya. Here's 500 caps. Good job. Go see Kevin if you wanna make more money.}
{350}{}{我应该付钱给你的。这是500顶瓶盖。干得好。如果你想赚更多的钱，去找凯文。}
