#{100}{}{You see a caravan leader.}
{100}{}{你看到一个商队队长。}
#{101}{}{You see a caravan guard.}
{101}{}{你看到一个大篷车守卫。}
#{200}{}{You see a caravan leader working for Sedit Caravan.}
{200}{}{你看到一个商队队长为塞迪特商队工作。}
#{201}{}{You see a caravan guard working for Sedit Caravan.}
{201}{}{你看到一个商队警卫为塞迪特商队工作。}
#{300}{}{Well, that's that. Let's go!}
{300}{}{好吧，就是这样。走吧！}
#{301}{}{Don't waste time.}
{301}{}{不要浪费时间。}
#{302}{}{Look to your work.}
{302}{}{注意你的工作。}
#{303}{}{Move it.}
{303}{}{移动它。}
#{304}{}{We don't pay you to stand around.}
{304}{}{我们不会付钱让你站在那里。}
#{305}{}{Hey, better buzz off.}
{305}{}{嘿，最好走开。}
#{350}{}{Scat. We don't like your kind.}
{350}{}{赶快走开。我们不喜欢你们这种人。}
#{400}{}{I'm with the caravans. I can deal with the likes of you.}
{400}{}{我和大篷车在一起。我能对付像你这样的人。}
#{401}{}{You're a miserable dangerous psychopath!}
{401}{}{你是个可怜的危险的精神病患者！}
#{450}{}{We're under attack!}
{450}{}{我们受到攻击了！}
#{451}{}{Deal with them. Quick!}
{451}{}{对付他们。快点！}
#{452}{}{Defend the cargo!}
{452}{}{保护货物！}
#{500}{}{Well, here we are, here's your 500 caps. It was easier than I thought. Will you come back with us? You surely could use another 500, no?}
{500}{}{好吧，我们到了，这是你的500顶瓶盖。这比我想象的要容易。你愿意和我们一起回来吗？你肯定还需要500块，不是吗？}
#{501}{}{What can you tell me about Albuquerque?}
{501}{}{关于阿尔伯克基你能告诉我什么？}
#{502}{}{What can you tell me about Corath?}
{502}{}{你能告诉我关于科拉斯的事吗？}
#{503}{}{How long will the caravan be staying here?}
{503}{}{商队要在这里呆多久？}
#{504}{}{I'm not coming back with you. I'll stay here.}
{504}{}{我不跟你回去了。我会留在这里。}
#{505}{}{Glug glug?}
{505}{}{闷闷不乐？}
#{506}{}{Not good, us losing the leader. Kevin won't like that. Here's your 400 caps. If you want, you can earn the same again if you come back to Sedit with us.}
{506}{}{不好，我们失去了领袖。凯文不会喜欢的。这是你的400顶瓶盖。如果你愿意的话，如果你和我们一起回来的话，你可以再赚同样的钱。}
#{550}{}{As you wish, we're not waiting for you. Time is caps. We stay here for one day as usual.}
{550}{}{如你所愿，我们不会等你的。时间是有限的。我们像往常一样在这里呆一天。}
#{551}{}{Bye.}
{551}{}{再见。}
#{650}{}{We leave one day after arriving, as usual. We can't wait for anyone.}
{650}{}{我们像往常一样，在到达一天后离开。我们不能等任何人。}
#{651}{}{I'll wait here and I'll come back to Sedit with you.}
{651}{}{我在这儿等着，我会回来和你一起吃的。}
#{652}{}{I'll come back with you, but first I'd like to take a look around.}
{652}{}{我会和你一起回来的，但首先我想四处看看。}
#{700}{}{A really large city, bigger than Sedit. Mutant Hunters are in charge. And they, as you might have guessed, hate all mutants.}
{700}{}{一个非常大的城市，比塞迪特还要大。变种猎人负责。你可能已经猜到了，他们讨厌所有的变种人。}
#{701}{}{How long will the caravan be staying here?}
{701}{}{商队要在这里呆多久？}
#{702}{}{I'm not coming back with you, I'll stay here.}
{702}{}{我不会和你一起回来的，我会留在这里。}
#{750}{}{A mining city, nothing more. If it weren't for the iron ore, it wouldn't be worth it coming here.}
{750}{}{矿业城市，仅此而已。如果不是因为铁矿石，来这里是不值得的。}
#{751}{}{How long will the caravan be staying here?}
{751}{}{商队要在这里呆多久？}
#{752}{}{I'm not coming back with you, I'll stay here.}
{752}{}{我不会和你一起回来的，我会留在这里。}
#{850}{}{Hi there. Looking for work? We need someone to help us guard the caravan on the way back to Sedit. The pay is 500 caps.}
{850}{}{你好。找工作？我们需要有人在回塞迪特的路上帮我们看守车队。工资是500英镑。}
#{851}{}{Sure, I can leave immediately.}
{851}{}{当然，我可以马上离开。}
#{852}{}{Sure, but give me some time to pack.}
{852}{}{当然，不过给我点时间收拾行李。}
#{853}{}{No thanks, not interested.}
{853}{}{不，谢谢，不感兴趣。}
#{854}{}{Ugh.}
{854}{}{啊。}
#{900}{}{Ready to earn more caps?}
{900}{}{准备好赚更多的钱了吗？}
#{901}{}{Ready to earn more caps?}
{901}{}{准备好赚更多的钱了吗？}
#{902}{}{Sure!}
{902}{}{当然！}
#{903}{}{Nope. I'm still looking around.}
{903}{}{不。我还在四处寻找。}
#{904}{}{Glug glug?}
{904}{}{闷闷不乐？}
#{1000}{}{Want to earn the same again for the return trip, eh?}
{1000}{}{想在返程时再赚同样的钱吗？}
#{1001}{}{You're right, I'll come back to Sedit with you.}
{1001}{}{你说得对，我会和你一起回来的。}
#{1002}{}{I just stopped by to say hello.}
{1002}{}{我只是过来打个招呼。}
#{1003}{}{I just stopped by to say hello.}
{1003}{}{我只是过来打个招呼。}
#{1004}{}{Glug glug?}
{1004}{}{闷闷不乐？}
#{1050}{}{Well here we are, here's your 500 caps. Will you return to Sedit with us? I'd hate losing more people. The pay is 500 caps again. What do you say?}
{1050}{}{我们到了，这是你的500顶瓶盖。你愿意和我们一起回塞迪特吗？我不想失去更多的人。工资又是500英镑。你怎么说？}
#{1051}{}{What can you tell me about Albuquerque?}
{1051}{}{关于阿尔伯克基你能告诉我什么？}
#{1052}{}{What can you tell me about Corath?}
{1052}{}{你能告诉我关于科拉斯的事吗？}
#{1053}{}{How long will the caravan be staying here?}
{1053}{}{商队要在这里呆多久？}
#{1054}{}{I'm not coming back with you. I'll stay here.}
{1054}{}{我不跟你回去了。我会留在这里。}
#{1055}{}{Glug glug?}
{1055}{}{闷闷不乐？}
#{1100}{}{Well here we are. Here's your 500 caps. Damn! I still can't understand how we could've lost all the guards. Kevin'll be furious. Well, anyway, I can give you the same pay once more if you come back with me. Hopefully I can hire some more people too.}
{1100}{}{我们到了。这是你的500顶瓶盖。该死！我还是不明白我们怎么会失去所有的警卫。凯文会生气的。好吧，不管怎样，如果你和我一起回来，我可以再给你同样的报酬。希望我也能多雇些人。}
#{1101}{}{What can you tell me about Albuquerque?}
{1101}{}{关于阿尔伯克基你能告诉我什么？}
#{1102}{}{What can you tell me about Corath?}
{1102}{}{你能告诉我关于科拉斯的事吗？}
#{1103}{}{How long will the caravan be staying here?}
{1103}{}{商队要在这里呆多久？}
#{1104}{}{I'm not coming back with you. I'll stay here.}
{1104}{}{我不跟你回去了。我会留在这里。}
#{1105}{}{Glug glug?}
{1105}{}{闷闷不乐？}
#{1150}{}{OK, but move it, time is caps.}
{1150}{}{好的，但是移动它，时间到了。}
#{1151}{}{Right.}
{1151}{}{正确的。}
#{1200}{}{If you won't talk sense, I can't hire you.}
{1200}{}{如果你不讲道理，我就雇不了你。}
#{1201}{}{Bugh.}
{1201}{}{天哪。}
#{1250}{}{Sorry, you don't look like you could handle caravan work. Put yourself together first.}
{1250}{}{抱歉，你看起来不能胜任大篷车的工作。先振作起来。}
#{1251}{}{Bugh.}
{1251}{}{天哪。}
#{1300}{}{I heard about you. You're the guy who abandoned our caravan. You better get lost.}
{1300}{}{我听说你了。你就是那个抛弃我们车队的人。你最好滚开。}
#{1301}{}{I heard about you. You're the gal who abandoned our caravan. You better get lost.}
{1301}{}{我听说你了。你就是那个抛弃我们商队的女孩。你最好滚开。}
#{1302}{}{Whatever you say.}
{1302}{}{不管你说什么。}
#{1303}{}{Ooof.}
{1303}{}{噢。}
#{1350}{}{So, feeling better? Ready to join our caravan for Sedit?}
{1350}{}{感觉好些了吗？准备好加入我们的车队了吗？}
#{1351}{}{So, feeling better? Ready to join our caravan for Sedit?}
{1351}{}{感觉好些了吗？准备好加入我们的车队了吗？}
#{1352}{}{Yep, ready to leave now.}
{1352}{}{是的，准备走了。}
#{1353}{}{Yep, just give me a moment to pack.}
{1353}{}{是的，给我一点时间收拾行李。}
#{1354}{}{Yep, but not interested any more.}
{1354}{}{是的，但我不再感兴趣了。}
#{1355}{}{Ugh.}
{1355}{}{啊。}
#{1400}{}{Howdy. Would you like to join our caravan? As you can see, we can handle attackers. But having an extra hand can always come in handy.}
{1400}{}{你好。你愿意加入我们的车队吗？如你所见，我们可以对付攻击者。但是有一只额外的手总是可以派上用场的。}
#{1401}{}{Howdy. Would you like to join our caravan? As you can see, we can handle attackers. But having an extra hand can always come in handy.}
{1401}{}{你好。你愿意加入我们的车队吗？如你所见，我们可以对付攻击者。但是有一只额外的手总是可以派上用场的。}
#{1402}{}{Where are you headed and what's the pay?}
{1402}{}{你要去哪里？薪水是多少？}
#{1403}{}{I can use some cash. I'll join you. Ready?}
{1403}{}{我可以用些现金。我和你一起去。准备好了吗？}
#{1404}{}{Thanks for the offer, but I'm not interested.}
{1404}{}{谢谢你的提议，但我不感兴趣。}
#{1405}{}{I think I'd rather take everything you have. Right after I kill you that is.}
{1405}{}{我想我宁愿拿走你所有的东西。就在我杀了你之后。}
#{1406}{}{Ugh.}
{1406}{}{啊。}
#{1450}{}{Howdy. Are you headed someplace specific? I thought you might like to join our caravan. We can use an extra hand.}
{1450}{}{你好。你要去某个特定的地方吗？我想你可能想加入我们的车队。我们可以多用一只手。}
#{1451}{}{Where are you headed and how much is the pay?}
{1451}{}{你要去哪里？薪水是多少？}
#{1452}{}{I can use some cash. I'll join you. Ready?}
{1452}{}{我可以用些现金。我和你一起去。准备好了吗？}
#{1453}{}{Thanks for the offer, but I'm not interested.}
{1453}{}{谢谢你的提议，但我不感兴趣。}
#{1454}{}{I think I'd rather take everything you have. Right after I kill you that is.}
{1454}{}{我想我宁愿拿走你所有的东西。就在我杀了你之后。}
#{1455}{}{Ugh.}
{1455}{}{啊。}
#{1500}{}{We're headed for }
{1500}{}{我们要去}
#{1501}{}{Sedit. }
{1501}{}{塞迪特。}
#{1502}{}{Corath. }
{1502}{}{科拉斯。}
#{1503}{}{Albuquerque. }
{1503}{}{阿尔伯克基。}
#{1504}{}{This caravan belongs to Sedit Caravans, you'll get 500 caps, if we reach our destination.}
{1504}{}{这辆大篷车属于塞迪特大篷车，如果我们到达目的地，你将得到500顶瓶盖。}
#{1505}{}{I can use some cash. I'll join you. Ready?}
{1505}{}{我可以用些现金。我和你一起去。准备好了吗？}
#{1506}{}{I see. I'm not interested.}
{1506}{}{我懂了。我不感兴趣。}
#{1507}{}{I think I'd rather take everything you have. Right after I kill you that is.}
{1507}{}{我想我宁愿拿走你所有的东西。就在我杀了你之后。}
#{1550}{}{As you wish. If you change your mind, let me know. It'll take a while for us to get going again.}
{1550}{}{如你所愿。如果你改变主意，请告诉我。我们还需要一段时间才能重新开始。}
#{1551}{}{OK.}
{1551}{}{好 啊。}
#{1600}{}{I see... we're not interested in your kind. Forget I said anything.}
{1600}{}{我懂了。。。我们对你们这种人不感兴趣。忘了我说过什么。}
#{1601}{}{Ouchie.}
{1601}{}{哎哟。}
#{1650}{}{Well?}
{1650}{}{好？}
#{1651}{}{Where are you headed anyway, and how much is the pay?}
{1651}{}{你到底要去哪里，薪水是多少？}
#{1652}{}{I'm thinking I could use the cash. I'll join you. Ready?}
{1652}{}{我想我可以用现金。我和你一起去。准备好了吗？}
#{1653}{}{Oh nothing, sorry.}
{1653}{}{哦，没什么，对不起。}
#{1654}{}{I think I'd rather take everything you have. Right after I kill you that is.}
{1654}{}{我想我宁愿拿走你所有的东西。就在我杀了你之后。}
#{1655}{}{Ugh.}
{1655}{}{啊。}
