#{100}{}{You see a caravan guard.}
{100}{}{你看到一个大篷车守卫。}
#{101}{}{You see the caravan leader.}
{101}{}{你看到商队队长了。}
#{200}{}{You see a caravan guard working for Sedit Caravan.}
{200}{}{你看到一个商队警卫为塞迪特商队工作。}
#{201}{}{You see a caravan guard working for the Crimson Caravan.}
{201}{}{你看到一个商队警卫在为深红色的商队工作。}
#{202}{}{You see a caravan guard working for Frederyk's Dream.}
{202}{}{你看到一个大篷车守卫为弗雷德里克的梦想工作。}
#{203}{}{You see the caravan leader working for Sedit Caravan.}
{203}{}{你看到车队队长为塞迪特车队工作。}
#{204}{}{You see the caravan leader working for the Crimson Caravan.}
{204}{}{你看到商队队长在为深红色商队工作。}
#{205}{}{You see the caravan leader working for Frederyk's Dream.}
{205}{}{你看到车队队长为弗雷德里克的梦想工作。}
#{340}{}{Hey, buzz off.}
{340}{}{嘿，走开。}
#{341}{}{I don't have time to chat.}
{341}{}{我没时间聊天。}
#{342}{}{Don't fool around the caravan.}
{342}{}{别在大篷车里鬼混。}
#{343}{}{I'll make our caravan safe at all costs.}
{343}{}{我会不惜一切代价保护我们的商队。}
#{344}{}{If you want to earn good money and live a little, join the caravans.}
{344}{}{如果你想赚大钱，过一点日子，就加入商队吧。}
#{345}{}{We can't waste our time.}
{345}{}{我们不能浪费时间。}
#{346}{}{I don't know you, I don't trust you. Better be on your way.}
{346}{}{我不认识你，我不信任你。最好在路上。}
#{347}{}{I'm just here to guard the caravan.}
{347}{}{我只是来守卫车队的。}
#{348}{}{The goods we're protecting are more valuable than you. So watch it.}
{348}{}{我们保护的货物比你的值钱。所以小心点。}
#{400}{}{I'm with the caravans. I can deal with the likes of you.}
{400}{}{我和大篷车在一起。我能对付像你这样的人。}
#{401}{}{Have you gone mad?!}
{401}{}{你疯了吗？！}
#{402}{}{Have you gone mad?!}
{402}{}{你疯了吗？！}
#{403}{}{I should get a bonus for this.}
{403}{}{我应该为此得到奖金。}
#{404}{}{I should get a bonus for this.}
{404}{}{我应该为此得到奖金。}
#{450}{}{Defend the brahmin.}
{450}{}{保卫双头牛。}
#{451}{}{Mind the carts.}
{451}{}{小心手推车。}
#{452}{}{Take cover!}
{452}{}{躲起来！}
#{453}{}{Maybe I'll get a bonus for you.}
{453}{}{也许我会给你奖金。}
#{454}{}{Time to earn our pay.}
{454}{}{是时候挣钱了。}
#{455}{}{It just wouldn't be the same without a single raid.}
{455}{}{没有一次突袭就不一样了。}
#{456}{}{You're not taking this caravan!}
{456}{}{你不能开这辆大篷车！}
#{457}{}{Make my job easier and give up.}
{457}{}{让我的工作轻松一点，然后放弃。}
