#{100}{}{You see a slut.}
{100}{}{你看到一个荡妇。}
#{150}{}{You see Loiz.}
{150}{}{你看到洛伊兹了。}
#{200}{}{You see an ordinary filthy slut.}
{200}{}{你看到一个普通的肮脏荡妇。}
#{250}{}{You see Loiz, the slut from the Crater.}
{250}{}{你看洛伊兹，从火山口出来的荡妇。}
#{300}{}{Come here, we'll play cat and dog.}
{300}{}{过来，我们玩猫捉狗游戏。}
#{301}{}{You won't find better sex 'n with me!}
{301}{}{你再也找不到更好的性生活了！}
#{302}{}{Don't be shy, honey.}
{302}{}{别害羞，亲爱的。}
#{310}{}{You contracted HIV.}
{310}{}{你感染了艾滋病。}
#{311}{}{You contracted HIV.}
{311}{}{你感染了艾滋病。}
#{400}{}{You think that just 'cause I'm a woman you're in some kind of advantage? You're awfully wrong!}
{400}{}{你以为就因为我是女人你就有优势？你大错特错了！}
#{500}{}{Hi, honey. Wanna have some fun?}
{500}{}{嗨，亲爱的。想找点乐子吗？}
#{501}{}{Who are you?}
{501}{}{你是谁？}
#{502}{}{Yeah, sure!}
{502}{}{是的，当然！}
#{503}{}{It was a pleasure meeting you but I have to go.}
{503}{}{很高兴见到你，但我得走了。}
#{504}{}{Mommy!}
{504}{}{妈妈！}
#{550}{}{I'm Loiz.}
{550}{}{我是洛伊兹。}
#{551}{}{That's quite a strange name.}
{551}{}{那是个很奇怪的名字。}
#{552}{}{I'm }
{552}{}{我是}
#{553}{}{. How much do you charge?}
{553}{}{. 你们收多少钱？}
#{600}{}{If you don't like it, I can be, let's say, Esmeralda for you.}
{600}{}{如果你不喜欢，我可以，比方说，为你做埃斯梅拉达。}
#{601}{}{That's better. So, what do you do?}
{601}{}{这样更好。那么，你是做什么的？}
#{602}{}{No, I don't have a problem with your name, it's just that I haven't heard it before. Do you like your job?}
{602}{}{不，我对你的名字没意见，只是我以前没听说过。你喜欢你的工作吗？}
#{603}{}{It was a pleasure meeting you but I have to go.}
{603}{}{很高兴见到你，但我得走了。}
#{650}{}{Well, I can't complain. I do like it and I got plenty of it, I can't say I don't.}
{650}{}{嗯，我不能抱怨。我确实喜欢，而且我有很多，我不能说我不喜欢。}
#{651}{}{How about you get to work right now?}
{651}{}{你现在去工作怎么样？}
#{652}{}{I was glad to meet you and maybe I'll stop by some other time for a word or two.}
{652}{}{我很高兴见到你，也许我会在别的时间过来说一两句话。}
#{700}{}{I quite like you so I'm gonna give you a special price. I'll blow you for 40 caps, the classic'll cost you 80 and if you're looking for something special, that'll be for 150. For you, I'll do anything for that money.}
{700}{}{我很喜欢你，所以我会给你一个特别的价格。我给你吹40个瓶盖，经典的要80美元，如果你想买特别的，那就150美元。为了你，为了那笔钱我什么都愿意做。}
#{701}{}{The blowjob, then.}
{701}{}{那就是口交。}
#{702}{}{Now I'd like to try the classic one.}
{702}{}{现在我想试试经典的。}
#{703}{}{I feel like trying something special today.}
{703}{}{今天我想尝试一些特别的东西。}
#{704}{}{I'm feeling a bit tired, maybe some other time.}
{704}{}{我觉得有点累，也许改天吧。}
#{750}{}{So, did you like it?}
{750}{}{你喜欢吗？}
#{751}{}{It was OK given the price.}
{751}{}{考虑到价格还可以。}
#{800}{}{So, did you like it?}
{800}{}{你喜欢吗？}
#{801}{}{Well... I got what I paid for.}
{801}{}{好。。。我得到了我付的钱。}
#{802}{}{So, did you like it? I for one did. You're one hell of a buck. I'll have to rest for a while to shake that off.}
{802}{}{你喜欢吗？我就是其中之一。你真是个混蛋。我得休息一会儿才能摆脱这种状况。}
#{900}{}{Yeah, I forgot to tell you I got some kind of a disease, Ays or somethin' like that. They say it can kill you but I think that's just rubbish. I've had it for a long time and I'm fine.}
{900}{}{是啊，我忘了告诉你我得了某种疾病，是什么病。他们说它会杀了你，但我认为那只是垃圾。我吃了很久了，我很好。}
#{901}{}{What?!}
{901}{}{什么？！}
#{950}{}{I'll blow you for 50 caps, the classic'll cost you 100 and if you're looking for something special, that'll be for 200. For that money, I'll do anything you want me to do, I don't have a problem with anything.}
{950}{}{我要给你50顶瓶盖，经典的要花你100英镑，如果你想买特别的，那就花200英镑。为了那笔钱，你要我做什么我都会做，我什么都没问题。}
#{951}{}{The blowjob, then.}
{951}{}{那就是口交。}
#{952}{}{Now I'd like to try the classic one.}
{952}{}{现在我想试试经典的。}
#{953}{}{I feel like trying something special today.}
{953}{}{今天我想尝试一些特别的东西。}
#{954}{}{I'm feeling a bit tired, maybe some other time.}
{954}{}{我觉得有点累，也许改天吧。}
#{1000}{}{Hey, pretty girl, wanna have some fun?}
{1000}{}{嘿，漂亮女孩，想找点乐子吗？}
#{1001}{}{Who are you?}
{1001}{}{你是谁？}
#{1002}{}{Yeah, sure!}
{1002}{}{是的，当然！}
#{1003}{}{It was a pleasure meeting you but I have to go.}
{1003}{}{很高兴见到你，但我得走了。}
#{1004}{}{Mommy!}
{1004}{}{妈妈！}
#{1050}{}{I'm Loiz.}
{1050}{}{我是洛伊兹。}
#{1051}{}{That's quite a strange name.}
{1051}{}{那是个很奇怪的名字。}
#{1052}{}{I'm }
{1052}{}{我是}
#{1053}{}{. How much do you charge?}
{1053}{}{. 你们收多少钱？}
#{1100}{}{If you don't like it, I can be, let's say, Esmeralda for you.}
{1100}{}{如果你不喜欢，我可以，比方说，为你做埃斯梅拉达。}
#{1101}{}{That's better. So, what do you do?}
{1101}{}{这样更好。那么，你是做什么的？}
#{1102}{}{No, I don't have a problem with your name, it's just that I haven't heard it before. Do you like your job?}
{1102}{}{不，我对你的名字没意见，只是我以前没听说过。你喜欢你的工作吗？}
#{1103}{}{It was a pleasure meeting you but I have to go.}
{1103}{}{很高兴见到你，但我得走了。}
#{1250}{}{Well, I can't complain. I do like it and I got plenty of it, I can't say I don't.}
{1250}{}{嗯，我不能抱怨。我确实喜欢，而且我有很多，我不能说我不喜欢。}
#{1251}{}{How about you get to work right now?}
{1251}{}{你现在去工作怎么样？}
#{1252}{}{I was glad to meet you and maybe I'll stop by some other time for a word or two.}
{1252}{}{我很高兴见到你，也许我会在别的时间过来说一两句话。}
#{1300}{}{I quite like you so I'm gonna give you a special price. We'll cuddle and I'll lick you off for 40 caps, proper sex'll cost you 80 and if you're looking for something special, that'll be for 150. For you, I'll do anything for that money.}
{1300}{}{我很喜欢你，所以我会给你一个特别的价格。我们会拥抱，我会舔掉你的40个瓶盖，适当的性行为将花费你80，如果你正在寻找特别的东西，那将是150。为了你，为了那笔钱我什么都愿意做。}
#{1301}{}{The licking, then.}
{1301}{}{那就舔吧。}
#{1302}{}{Proper sex then, so it's worth it.}
{1302}{}{那就好好做爱吧，值得。}
#{1303}{}{I feel like trying something special today.}
{1303}{}{今天我想尝试一些特别的东西。}
#{1304}{}{I'm feeling a bit tired, maybe some other time.}
{1304}{}{我觉得有点累，也许改天吧。}
#{1350}{}{So, did you like it?}
{1350}{}{你喜欢吗？}
#{1351}{}{It was OK given the price.}
{1351}{}{考虑到价格还可以。}
#{1400}{}{So, did you like it?}
{1400}{}{你喜欢吗？}
#{1401}{}{Well... I got what I paid for.}
{1401}{}{好。。。我得到了我付的钱。}
#{1402}{}{So, did you like it? I for one did. You're a goddess of love, come see me some other time.}
{1402}{}{你喜欢吗？我就是其中之一。你是爱的女神，改天再来找我吧。}
#{1450}{}{We'll cuddle and I'll lick you off for 50 caps, proper sex'll cost you 100 and if you're looking for something special, that'll be for 200. For that money, I'll do anything you want me to do, I don't have a problem with anything.}
{1450}{}{我们会拥抱，我会舔掉你50个瓶盖，适当的性行为会花你100美元，如果你要找特别的东西，那就花200美元。为了那笔钱，你要我做什么我都会做，我什么都没问题。}
#{1451}{}{The licking, then.}
{1451}{}{那就舔吧。}
#{1452}{}{Proper sex then, so it's worth it.}
{1452}{}{那就好好做爱吧，值得。}
#{1453}{}{I feel like trying something special today.}
{1453}{}{今天我想尝试一些特别的东西。}
#{1454}{}{I'm feeling a bit tired, maybe some other time.}
{1454}{}{我觉得有点累，也许改天吧。}
#{1500}{}{Ew, stop drooling on me and fuck off, you're scaring my customers away!}
{1500}{}{呃，别再对我流口水了，滚开，你吓跑我的顾客了！}
#{1501}{}{Bye-bye.}
{1501}{}{再见。}
