#{2100}{}{What the hell are you doing here? Where's Frederyk? I'm supposed to be meeting him, not you... whoever you are.}
{2100}{}{你到底在这里干什么？弗雷德里克在哪？我应该去见他，不是你。。。不管你是谁。}
#{2101}{}{Frederyk asked me to represent him.}
{2101}{}{弗雷德里克让我代表他。}
#{2102}{}{Watch your mouth, bitch! It could get you into trouble.}
{2102}{}{小心你的嘴，婊子！会给你带来麻烦的。}
#{2150}{}{Yeah? Well, I'm not going to waste my time with you. [She turns to her people.] Take care of him.}
{2150}{}{是 啊？好吧，我不会和你浪费时间的。[她转向她的人]照顾好他。}
#{2151}{}{Yeah? Well, I'm not going to waste my time with you. [She turns to her people.] Take care of her.}
{2151}{}{是 啊？好吧，我不会和你浪费时间的。[她转向她的人]照顾好她。}
#{2152}{}{You're making a mistake, whore!}
{2152}{}{你搞错了，婊子！}
#{2153}{}{Come on, can't we talk about this?}
{2153}{}{拜托，我们不能谈谈吗？}
#{2200}{}{I'm not wasting my time with you. [She turns to her people.] Take care of this shit.}
{2200}{}{我不是在浪费时间和你在一起。[她转向她的人]处理好这件事。}
#{2201}{}{You're making a mistake, whore!}
{2201}{}{你搞错了，婊子！}
#{2202}{}{Come on, can't we talk about this?}
{2202}{}{拜托，我们不能谈谈吗？}
