#{100}{}{You see a merchant.}
{100}{}{你看到一个商人。}
#{200}{}{You see a common merchant.}
{200}{}{你看到一个普通的商人。}
#{500}{}{How can I help?}
{500}{}{我能帮忙吗？}
#{501}{}{I have a few questions.}
{501}{}{我有几个问题。}
#{502}{}{What do you sell?}
{502}{}{你们卖什么？}
#{503}{}{You can't.}
{503}{}{你不能。}
#{504}{}{Heelp, heehee!}
{504}{}{嘿，嘿！}
#{505}{}{Uff.}
{505}{}{不明飞行物。}
#{550}{}{So tuck 'em up your ass. I ain't got the time to chat to every stranger that goes past my shop. You either buy something or get out.}
{550}{}{所以把它们塞进你的屁股里。我没时间跟每一个经过我店里的陌生人聊天。你要么买东西要么出去。}
#{551}{}{So what have you got?}
{551}{}{你有什么发现？}
#{552}{}{In that case I'm leaving.}
{552}{}{那样的话我就走了。}
#{600}{}{Come visit again.}
{600}{}{再来看看。}
#{601}{}{We'll see, maybe I'll stop by.}
{601}{}{我们拭目以待，也许我会过来看看。}
#{602}{}{Bye-bye.}
{602}{}{再见。}
#{650}{}{We're closed. Get outta my shop or I'm calling the police!}
{650}{}{我们关门了。滚出我的店否则我就报警！}
#{651}{}{OK, I'm leaving. I apologize for getting in like that.}
{651}{}{好的，我要走了。我很抱歉那样进来。}
#{652}{}{I'm leaving right after I get your revenue.}
{652}{}{我一拿到你的收入就走。}
#{653}{}{Ook.}
{653}{}{哦。}
#{654}{}{Grr! Your'n'mine!}
{654}{}{格瑞！你的不是我的！}
