#{100}{}{You see a cop.}
{100}{}{你看到一个警察。}
#{101}{}{You see a cop.}
{101}{}{你看到一个警察。}
#{200}{}{You see a cop, he looks occupied.}
{200}{}{你看到一个警察，他看起来很忙。}
#{201}{}{You see a cop, she looks occupied.}
{201}{}{你看到一个警察，她看起来很忙。}
#{500}{}{Who are you?}
{500}{}{你是谁？}
#{501}{}{I'm, eh... the new guy! I'm the new one.}
{501}{}{我，呃……新来的人！我是新来的。}
#{502}{}{I'm, eh... the new girl! I'm new here.}
{502}{}{我，呃……新来的女孩！我是新来的。}
#{503}{}{If I wasn't supposed to be here, I wouldn't have gotten here. I have a private meeting with the sheriff and it's none of your business. Make yourself useful and leave me alone.}
{503}{}{如果我不在这里，我就不会回来了。我和警长有个私人会议，不关你的事。你自己干自己的事，别来烦我。}
#{504}{}{If I wasn't supposed to be here, I wouldn't have gotten here. I have a private meeting with the sheriff and it's none of your business. Make yourself useful and leave me alone.}
{504}{}{如果我不在这里，我就不会回来了。我和警长有个私人会议，不关你的事。你自己干自己的事，别来烦我。}
#{505}{}{Ugh.}
{505}{}{啊。}
#{550}{}{Nonsense! Morrow's not hiring anyone right now. You're not supposed to be here!}
{550}{}{胡说！莫罗现在不雇人。你不应该在这里！}
#{551}{}{Damn.}
{551}{}{该死。}
#{600}{}{I apologize.}
{600}{}{我道歉。}
#{601}{}{OK.}
{601}{}{好啊。}
#{650}{}{Try looking as busy as you can, whatever you're doing. Carpenter usually pours his bad mood on the ones who give him the slightest pretext.}
{650}{}{不管你在做什么，尽量显得忙碌。木匠通常把他的坏心情发泄在那些给他一点点借口的人身上。}
#{651}{}{Phew, thanks for the advice.}
{651}{}{呸，谢谢你的建议。}
#{652}{}{Uff.}
{652}{}{不明飞行物。}
#{700}{}{Thanks for saving David, hope Carpenter'll cool down now.}
{700}{}{谢谢你救了大卫，希望卡彭特现在冷静下来。}
#{701}{}{OK.}
{701}{}{好啊。}
#{702}{}{Uff.}
{702}{}{不明飞行物。}
