#{100}{}{You see a pretty, black haired woman.}
{100}{}{你看到一个漂亮的黑发女人。}
#{150}{}{You see Sabrina.}
{150}{}{你看到萨布丽娜了。}
#{200}{}{You see a black haired woman, her pretty face is spoiled by a big scar on her right cheek.}
{200}{}{你看一个黑发女人，她漂亮的脸被右脸颊上的一个大伤疤给毁了。}
#{250}{}{You see Sabrina. Her pretty face is spoiled by a big scar on her right cheek.}
{250}{}{你看到萨布丽娜了。她漂亮的脸被右脸颊上的一个大伤疤给毁了。}
#{500}{}{Yeah? How can I help you?}
{500}{}{是 啊？我能帮你什么？}
#{501}{}{Hi, I'm }
{501}{}{嗨，我是}
#{502}{}{What's on offer?}
{502}{}{有什么优惠？}
#{503}{}{What's your relation to Sedit Caravan?}
{503}{}{你和塞迪特商队有什么关系？}
#{504}{}{Nicol says you're to give me a discount.}
{504}{}{尼科尔说你要给我打折。}
#{505}{}{Hoo!}
{505}{}{呼！}
#{506}{}{Thank you, I'm leaving.}
{506}{}{谢谢，我要走了。}
#{507}{}{You're supposed to give me a discount for my services for Sedit Caravan.}
{507}{}{你应该给我一个折扣我为赛迪特车队服务。}
#{550}{}{What's written on the board on the house. So, weapons. All kinds of small guns ?? pistols, SMGs, rifles, shotguns, related ammo, and I also got a few frag granades. They come in handy when you need to get a rat out of a hole. I also make special modifications for some weapons.}
{550}{}{房子的黑板上写着什么。所以，武器。各种各样的小枪，手枪，SMG，步枪，猎枪，相关的弹药，还有一些碎片。当你需要把老鼠从洞里弄出来的时候，它们就派上用场了。我也对一些武器做了特殊的修改。}
#{551}{}{So show me what you've got.}
{551}{}{让我看看你有什么。}
#{552}{}{Can you modify one of my weapons?}
{552}{}{你能改装我的武器吗？}
#{553}{}{Do you know where I could get my hands on something heavier? Some real heavy big guns?}
{553}{}{你知道我在哪里可以弄到更重的东西吗？一些真正的大炮？}
#{554}{}{In that case, I'm not interested.}
{554}{}{那样的话，我不感兴趣。}
#{600}{}{Definitely not here in town, you might wanna try Albuquerque. If you got lots of cash, you might be able to buy a heavy piece or two.}
{600}{}{绝对不是在城里，你可以试试阿尔伯克基。如果你有很多现金，你也许可以买一两件重的。}
#{601}{}{So show me what you've got.}
{601}{}{让我看看你有什么。}
#{602}{}{So can you modify one of my weapons?}
{602}{}{你能改装我的武器吗？}
#{603}{}{You've got something against big guns?}
{603}{}{你反对大炮？}
#{604}{}{Thanks for the tip.}
{604}{}{谢谢你的小费。}
#{650}{}{They're useless unless you're actually trying to bring a whole damn building down. You need a small gun that's easy to carry around, fast to fire and precise enough for a headshot. That way, with animals you can use the rest of for food. With humans, you get to keep everything they had on them. On top of that, getting your hands on big guns ammo is quite difficult and there's never enough.}
{650}{}{除非你真的想拆掉整栋该死的大楼，否则它们是没用的。你需要一把携带方便，射击迅速，足够精确的小型枪。那样的话，你就可以用剩下的动物做食物了。对于人类，你可以保留他们身上所有的东西。除此之外，获得大炮弹药是相当困难的，从来没有足够的。}
#{651}{}{So show me what you've got.}
{651}{}{让我看看你有什么。}
#{652}{}{So can you modify one of my weapons?}
{652}{}{你能改装我的武器吗？}
#{653}{}{I'm still looking for big guns, see you.}
{653}{}{我还在找大炮呢，再见。}
#{700}{}{Well hello, I'm Sabrina. How can I help?}
{700}{}{你好，我是萨布丽娜。我能帮忙吗？}
#{701}{}{How did you get by that scar on your face?}
{701}{}{你脸上的伤疤是怎么熬过来的？}
#{702}{}{You can start by giving in to my charm, honey.}
{702}{}{你可以先屈服于我的魅力，亲爱的。}
#{703}{}{What's on offer?}
{703}{}{有什么优惠？}
#{750}{}{None of your business. I made a mistake and I'm reminded of it every day so that I'm better prepared next time.}
{750}{}{不关你的事。我犯了一个错误，我每天都会被提醒，这样下次我就有更好的准备了。}
#{751}{}{OK, I was just asking. So, what's on offer?}
{751}{}{好吧，我只是问问。有什么优惠？}
#{752}{}{OK, I was just asking. So, what's on offer?}
{752}{}{好吧，我只是问问。有什么优惠？}
#{753}{}{I want you, honey.}
{753}{}{我想要你，亲爱的。}
#{800}{}{I hope you got enough cash on you... So I can pay the cops for clearing your corpse once I run a bullet through that stupid face of yours.}
{800}{}{我希望你身上有足够的现金。。。所以一旦我把子弹射穿你那张愚蠢的脸，我就可以付钱给警察帮你清理尸体。}
#{801}{}{I apologize. So, what's on offer?}
{801}{}{我道歉。有什么优惠？}
#{802}{}{It really gets me going when a girl resists me. So come on, you whore.}
{802}{}{当一个女孩反抗我时，我真的很激动。来吧，你这个婊子。}
#{850}{}{This house previously belonged to them, so we have certain agreements. That's all you need to know.}
{850}{}{这房子以前是他们的，所以我们有一些协议。你只需要知道这些。}
#{851}{}{I'd say I've become part of those agreements. Nicol says you're to give me a discount.}
{851}{}{我想说我已经成为这些协议的一部分了。尼科尔说你要给我打折。}
#{852}{}{I'd say I've become part of those agreements. Nicol says you're to give me a discount.}
{852}{}{我想说我已经成为这些协议的一部分了。尼科尔说你要给我打折。}
#{853}{}{I'd say I've become part of those agreements. You're supposed to give me a discount for my services for Sedit Caravan.}
{853}{}{我想说我已经成为这些协议的一部分了。你应该给我一个折扣我为赛迪特车队服务。}
#{854}{}{I'd say I've become part of those agreements. You're supposed to give me a discount for my services for Sedit Caravan.}
{854}{}{我想说我已经成为这些协议的一部分了。你应该给我一个折扣我为赛迪特车队服务。}
#{900}{}{OK, you're looking for something at the moment?}
{900}{}{好吧，你现在在找什么？}
#{901}{}{Yes, show me what you've got.}
{901}{}{是的，让我看看你有什么。}
#{902}{}{Yes, can you modify one of my weapons?}
{902}{}{是的，你能改装我的武器吗？}
#{903}{}{Not right now, I'll stop by some other time.}
{903}{}{现在不行，我改天再来。}
#{950}{}{Damn, this ain't no shelter for the idiotic. If you're not buying a gun, get outta here. Got it?}
{950}{}{该死，这不是白痴的庇护所。如果你不买枪，离开这里。知道了？}
#{951}{}{Wham, bam! Yaay!}
{951}{}{砰，砰！耶！}
#{952}{}{Eeeew.}
{952}{}{哎哟。}
#{1000}{}{Yeah? What'll it be today?}
{1000}{}{是 啊？今天是什么日子？}
#{1001}{}{Hi, I'm }
{1001}{}{嗨，我是}
#{1002}{}{What's on offer?}
{1002}{}{有什么优惠？}
#{1003}{}{What's your relation to Sedit Caravan?}
{1003}{}{你和塞迪特商队有什么关系？}
#{1004}{}{Nicol says you're to give me a discount.}
{1004}{}{尼科尔说你要给我打折。}
#{1005}{}{Hoo!}
{1005}{}{呼！}
#{1006}{}{Thanks, I'm leaving.}
{1006}{}{谢谢，我要走了。}
#{1007}{}{You're supposed to give me a discount for my services for Sedit Caravan.}
{1007}{}{你应该给我一个折扣我为赛迪特车队服务。}
#{1050}{}{We're closed, go away and come in the morning.}
{1050}{}{我们关门了，走吧，明早再来。}
#{1051}{}{OK.}
{1051}{}{好 啊。}
#{1052}{}{Okee.}
{1052}{}{好的。}
#{1100}{}{It was a pleasure doing business with you.}
{1100}{}{很高兴和你做生意。}
#{1101}{}{See you.}
{1101}{}{再见。}
#{1150}{}{Fine. And now you can go.}
{1150}{}{好的。现在你可以走了。}
#{1151}{}{Bye.}
{1151}{}{再见。}
#{1200}{}{You don't have any weapons suitable for a useful modification.}
{1200}{}{你没有任何适合改装的武器。}
#{1201}{}{OK.}
{1201}{}{好 啊。}
#{1250}{}{Hm, Desert Eagle, .44 caliber Magnum. Its only disadvantage is probably its small magazine. I can make you one for 20 rounds. It's not exactly a standard mod but I've tried it before and it works. It'll cost you 2000 caps.}
{1250}{}{嗯，沙漠之鹰，.44口径大酒瓶。它唯一的缺点可能是它的小杂志。我可以给你做20发子弹。这不完全是一个标准的模式，但我已经尝试过它之前，它的工作。你要花2000个瓶盖。}
#{1251}{}{OK, I'm in. [Hand her the weapon.]}
{1251}{}{好的，我进去了。[把武器递给她。]}
#{1252}{}{I don't have enough money for that. Can you modify one of my other guns?}
{1252}{}{我没有足够的钱。你能改装一下我的其他枪吗？}
#{1253}{}{Can you modify a different weapon for me?}
{1253}{}{你能为我改装一件不同的武器吗？}
#{1254}{}{Actually, I'm not interested in modifications anymore.}
{1254}{}{实际上，我对修改已经不感兴趣了。}
#{1300}{}{I could equip that Colt Rangemaster hunting rifle with a telescope. That won't make it a proper sniping rifle but you can bet you'll be able to hunt at greater distances with efficiency. Whatever'll be in your crosshair. It's not a demanding job, the most expensive thing'll be a good quality telescope, so that'll be 2000 caps total.}
{1300}{}{我可以用望远镜装备骑兵猎枪。这不会使它成为一个合适的狙击步枪，但你可以打赌，你将能够在更大的距离与效率狩猎。不管你的十字准星上会有什么。这不是一项要求很高的工作，最贵的是一台高质量的望远镜，所以总共需要2000个。}
#{1301}{}{OK, I'm in. [Hand her the weapon.]}
{1301}{}{好的，我进去了。[把武器递给她。]}
#{1302}{}{I don't have enough money for that. Can you modify one of my other weapons?}
{1302}{}{我没有足够的钱。你能改装我的其他武器吗？}
#{1303}{}{Can you modify a different weapon for me?}
{1303}{}{你能为我改装一件不同的武器吗？}
#{1304}{}{Actually, I'm not interested in modifications anymore.}
{1304}{}{实际上，我对修改已经不感兴趣了。}
#{1350}{}{I can shorten the barrel of your Winchester double-barrel shotgun. It'll shorten the range even more but you'll gain more spread. Not much use in the wastes, but if a pack of fuckers jump on you in town, you'll shred them to pieces with this. It'll cost you only 1500 caps.}
{1350}{}{我可以缩短你的温彻斯特双管猎枪的枪管。它会进一步缩短射程，但你会得到更多的散布。在垃圾堆里没什么用，但如果镇上有一群混蛋跳到你身上，你会用这个把他们撕成碎片的。你只需要1500顶瓶盖。}
#{1351}{}{OK, I'm in. [Hand her the weapon.]}
{1351}{}{好的，我进去了。[把武器递给她。]}
#{1352}{}{I don't have enough money for that. Can you modify one of my other weapons?}
{1352}{}{我没有足够的钱。你能改装我的其他武器吗？}
#{1353}{}{Can you modify a different weapon for me?}
{1353}{}{你能为我改装一件不同的武器吗？}
#{1354}{}{Actually, I'm not interested in modifications anymore.}
{1354}{}{实际上，我对修改已经不感兴趣了。}
#{1400}{}{Kalashnikov AK-112 is a standard army assault rifle, the 5mm rounds are a bit unusual for a rifle, though. Anyways, for 4000 caps, I can equip yours with an additional magazine that'll considerably extend the capacity.}
{1400}{}{卡拉什尼科夫AK-112是一种标准的陆军突击步枪，5毫米口径的子弹对于步枪来说有点不寻常。不管怎样，4000个瓶盖，我可以为你的装备一个额外的杂志，这将大大扩大容量。}
#{1401}{}{OK, I'm in. [Hand her the weapon.]}
{1401}{}{好的，我进去了。[把武器递给她。]}
#{1402}{}{I don't have enough money for that. Can you modify one of my other guns?}
{1402}{}{我没有足够的钱。你能改装一下我的其他枪吗？}
#{1403}{}{Can you modify a different weapon for me?}
{1403}{}{你能为我改装一件不同的武器吗？}
#{1404}{}{Actually, I'm not interested in modifications anymore.}
{1404}{}{实际上，我对修改已经不感兴趣了。}
#{1410}{}{DKS-501 is a quality sniper rifle, there's not much I can do with that. But I always wanted to try making it into a gun. Saw off the barrel and modify the grip so you could shoot faster. It won't be as good as the rifle, that's understood, but you'll get a pistol with an unusually high range and precision. I'm sure it'll work, but I'm going to need 3000 caps for the job.}
{1410}{}{DKS-501是一支高质量的狙击步枪，我对此无能为力。但我一直想把它做成枪。锯下枪管，修改握拍方式，这样你可以射得更快。它不会像步枪那么好，这是明白的，但你会得到一支射程和精度异常高的手枪。我肯定行得通，但这项工作我需要3000顶瓶盖。}
#{1411}{}{OK, I'm in. [Hand her the weapon.]}
{1411}{}{好的，我进去了。[把武器递给她。]}
#{1412}{}{I don't have enough money for that. Can you modify one of my other guns?}
{1412}{}{我没有足够的钱。你能改装一下我的其他枪吗？}
#{1413}{}{Can you modify a different weapon for me?}
{1413}{}{你能为我改装一件不同的武器吗？}
#{1414}{}{Actually, I'm not interested in modifications anymore.}
{1414}{}{实际上，我对修改已经不感兴趣了。}
#{1420}{}{I don't get to lay my eyes on Revolver Magnum .44 very often. [She weighs it in her hand, ejects, then closes the drum magazine.] Nice piece. I can make you a special reloader that'll reload the gun with all six bullets in one go. It'll cost you 2000 caps.}
{1420}{}{我不会经常盯着万能左轮手枪。[她用手称了称，弹了出来，然后合上了鼓盒。]不错。我可以给你做一个特殊的重新装弹器，一次装完六颗子弹。你要花2000个瓶盖。}
#{1421}{}{OK, I'm in. [Hand her the weapon.]}
{1421}{}{好的，我进去了。[把武器递给她。]}
#{1422}{}{I don't have enough money for that. Can you modify one of my other guns?}
{1422}{}{我没有足够的钱。你能改装一下我的其他枪吗？}
#{1423}{}{Can you modify a different weapon for me?}
{1423}{}{你能为我改装一件不同的武器吗？}
#{1424}{}{Actually, I'm not interested in modifications anymore.}
{1424}{}{实际上，我对修改已经不感兴趣了。}
#{1430}{}{Burst shooting with a combat shotgun is a good thing, unless you mind wasting precious ammo. I can dismantle the automatic parts and anti-dust fitting while giving it extra kick and improving the gun-stock. You won't be able to shoot in bursts but you'll be the proud owner of a handheld cannon that will tear to pieces everything in its way in one shot, given the correct distance. I'll want 4000 caps for that.}
{1430}{}{用猎枪射击是件好事，除非你介意浪费宝贵的弹药。我可以拆卸自动零件和防尘装置，同时给它额外的踢和改善枪械库存。你将无法在爆炸射击，但你将是一个手持大炮，将撕裂在一个正确的距离，所有的东西在一枪自豪的拥有者。我要4000个瓶盖。}
#{1431}{}{OK, I'm in. [Hand her the weapon.]}
{1431}{}{好的，我进去了。[把武器递给她。]}
#{1432}{}{I don't have enough money for that. Can you modify one of my other weapons?}
{1432}{}{我没有足够的钱。你能改装我的其他武器吗？}
#{1433}{}{Can you modify a different weapon for me?}
{1433}{}{你能为我改装一件不同的武器吗？}
#{1434}{}{Actually, I'm not interested in modifications anymore.}
{1434}{}{实际上，我对修改已经不感兴趣了。}
#{1450}{}{You don't have any weapons suitable for a useful modification.}
{1450}{}{你没有任何适合改装的武器。}
#{1451}{}{I'm interested in expanding the magazine on my Desert Eagle. [Hand her the weapon.]}
{1451}{}{我有兴趣扩大我的沙漠鹰杂志。[把武器递给她。]}
#{1452}{}{I'm interested in a telescope for my hunting rifle. [Hand her the weapon.]}
{1452}{}{我对我猎枪的望远镜感兴趣。[把武器递给她。]}
#{1453}{}{I'm interested in shortening the barrels of my shotgun. [Hand her the weapon.]}
{1453}{}{我有兴趣缩短我的猎枪枪管。[把武器递给她。]}
#{1454}{}{I'm interested in an additional magazine for my assault rifle. [Hand her the weapon.]}
{1454}{}{我想再给我的突击步枪买一本杂志。[把武器递给她。]}
#{1455}{}{I'm interested in turning my sniper rifle into a pistol. [Hand her the weapon.]}
{1455}{}{我想把我的狙击步枪变成手枪。[把武器递给她。]}
#{1456}{}{I'm interested in a Revolver Magnum reloader. [Hand her the weapon.]}
{1456}{}{我对一把万能左轮手枪感兴趣。[把武器递给她。]}
#{1457}{}{I'm interested in reinforcing my combat shotgun. [Hand her the weapon.]}
{1457}{}{我有兴趣加强我的战斗猎枪。[把武器递给她。]}
#{1458}{}{I'm not interested in any modifications.}
{1458}{}{我对任何修改都不感兴趣。}
#{1500}{}{Fine, come back tomorrow.}
{1500}{}{好的，明天再来。}
#{1501}{}{OK.}
{1501}{}{好 啊。}
#{1550}{}{OK, come back in two days.}
{1550}{}{好的，两天后再来。}
#{1551}{}{OK.}
{1551}{}{好 啊。}
#{1600}{}{Fine, come back in three days.}
{1600}{}{好吧，三天后再来。}
#{1601}{}{OK.}
{1601}{}{好 啊。}
#{1650}{}{OK, come back in four days.}
{1650}{}{好的，四天后再来。}
#{1651}{}{OK.}
{1651}{}{好 啊。}
#{1700}{}{Your weapon's not ready yet.}
{1700}{}{你的武器还没准备好。}
#{1701}{}{Never mind, I want to buy something.}
{1701}{}{没关系，我想买点东西。}
#{1702}{}{OK, I'll come back later.}
{1702}{}{好的，我一会儿再来。}
#{1703}{}{Wham, bam! Yaay!}
{1703}{}{砰，砰！耶！}
#{1704}{}{Uff.}
{1704}{}{不明飞行物。}
#{1750}{}{You're finally here. Good, your weapon's ready as we agreed. Here you go, have fun with it.}
{1750}{}{你终于来了。很好，你的武器已经准备好了。给你，玩得开心点。}
#{1751}{}{You bet.}
{1751}{}{当然。}
#{1752}{}{Heehee.}
{1752}{}{嘿嘿。}
