#{100}{}{You see a salesman.}
{100}{}{你看到一个推销员。}
#{150}{}{You see Salem.}
{150}{}{你看到塞勒姆了。}
#{200}{}{You see a short, fat salesman.}
{200}{}{你看到一个又矮又胖的推销员。}
#{250}{}{You see Salem, a short, fat salesman.}
{250}{}{你看塞勒姆，一个又矮又胖的推销员。}
#{500}{}{Welcome! You must be new here! And you've come to the right place! Everybody will end up at Salem's one way or the other! I've got everything!}
{500}{}{欢迎光临！你一定是新来的！你来对地方了！每个人都会以这样或那样的方式来到塞勒姆大家庭！我什么都有！}
#{501}{}{What does it mean, everything?}
{501}{}{什么意思，一切？}
#{502}{}{Ugh, I think I got the wrong door.}
{502}{}{呃，我想我走错门了。}
#{503}{}{Bhe?}
{503}{}{额？}
#{550}{}{Absolutely everything you might need, my friend! Even things you don't yet know you need! I've got supplies, wasteland equipment, things for entertainment, and some weapons, too. Nothing too complicated, yet simple to kill with. I'm sure you don't have time to spend setting up some complicated rifle when a raider jumps on you, he-he.}
{550}{}{你可能需要的一切，我的朋友！即使是你还不知道你需要的东西！我有补给，荒地设备，娱乐用品，还有一些武器。没有什么太复杂，但简单的杀戮。他说：“我敢肯定，当一个袭击者向你扑过来时，你没有时间去安装一把复杂的步枪。”。}
#{551}{}{Surely, so...}
{551}{}{当然，所以……}
#{600}{}{And hear this! Here on these shelves behind me are the special goods! Things you won't even see in other places! Each thing a unique, one-of-a-kind piece!}
{600}{}{听我说！在我身后的这些架子上有特殊的商品！你在其他地方都看不到的东西！每件事都是独一无二的！}
#{601}{}{Fine, fine, show me what you've got.}
{601}{}{好吧，好吧，让我看看你有什么。}
#{602}{}{I'll have a look at those special goods of yours.}
{602}{}{我要看看你的那些特产。}
#{603}{}{I'm not interested in any of this.}
{603}{}{我对这些都不感兴趣。}
#{650}{}{I can see my huge range of goods paralyzed you! No wonder! And you haven't seen my amazing prices yet! You can start purchasing as soon as you recover! Ain't it great?! It is great!}
{650}{}{我可以看到我的大范围的货物瘫痪你！难怪！你还没看到我惊人的价格呢！你一康复就可以开始购买了！是不是很棒？！太好了！}
#{651}{}{Hoo... Hee?}
{651}{}{呼……嘿？}
#{700}{}{And I haven't told you that right here behind me I keep my special goods! You won't see things like these anywhere else! Each thing a unique, one-of-a-kind piece! So? What'll it be?}
{700}{}{我还没告诉你，就在我身后，我保存着我的特殊物品！你在别的地方看不到这样的东西！每件事都是独一无二的！所以呢？会是什么？}
#{701}{}{Want shop!!}
{701}{}{想要商店！！}
#{702}{}{There pretty! Wot it?}
{702}{}{真漂亮！是吗？}
#{703}{}{Yell too much! Booo!}
{703}{}{喊太多了！嘘！}
#{750}{}{Welcome! You must be new here! And you've come to the right place! Everybody will end up at Salem's one way or the other! I've got everything!}
{750}{}{欢迎光临！你一定是新来的！你来对地方了！每个人都会以这样或那样的方式来到塞勒姆大家庭！我什么都有！}
#{751}{}{What does it mean, everything?}
{751}{}{什么意思，一切？}
#{752}{}{Ugh, I think I got the wrong door.}
{752}{}{呃，我想我走错门了。}
#{753}{}{Bhe?}
{753}{}{Bhe公司？}
#{800}{}{Absolutely everything you might need, my dear! Even things you don't yet know you need! I've got supplies, wasteland equipment, things for entertainment, and some weapons, too. Nothing too complicated, yet simple to kill with. I'm sure you don't have time to spend setting up some complicated rifle when a raider jumps on you, he-he.}
{800}{}{你可能需要的一切，亲爱的！即使是你还不知道你需要的东西！我有补给，荒地设备，娱乐用品，还有一些武器。没有什么太复杂，但简单的杀戮。他说：“我敢肯定，当一个袭击者向你扑过来时，你没有时间去安装一把复杂的步枪。”。}
#{801}{}{Surely, so...}
{801}{}{当然，所以……}
#{850}{}{Welcome back. I'll bet you won't resist this time and let me tell you about the amazing range of goods I'm offering!}
{850}{}{欢迎回来。我敢打赌这次你不会反抗的，让我告诉你我提供的各种各样的商品！}
#{851}{}{So, what do you offer?}
{851}{}{那么，你提供什么？}
#{852}{}{You'd lose that bet. Good-bye.}
{852}{}{你会输的。再见。}
#{900}{}{Welcome back. I'll bet you won't resist this time and let me tell you about the amazing range of goods I'm offering!}
{900}{}{欢迎回来。我敢打赌这次你不会反抗的，让我告诉你我提供的各种各样的商品！}
#{901}{}{So, what do you offer?}
{901}{}{那么，你提供什么？}
#{902}{}{You'd lose that bet. Good-bye.}
{902}{}{你会输的。再见。}
#{950}{}{Welcome! Everybody keeps coming back to Salem's shop! It's because of the amazing range of goods I offer! You won't believe it but you're my absolute most favorite customer! What'll it be today?}
{950}{}{欢迎光临！每个人都会回到塞勒姆的店里！这是因为我提供的商品种类繁多！你不会相信的，但你绝对是我最喜欢的顾客！今天是什么日子？}
#{951}{}{Show me what you've got.}
{951}{}{给我看看你有什么。}
#{952}{}{I'll have a look at the special goods.}
{952}{}{我去看看特价商品。}
#{953}{}{You're right. I don't.}
{953}{}{你说得对。我不。}
#{954}{}{Show stuff!}
{954}{}{表演吧！}
#{955}{}{Pretty! Wot it?}
{955}{}{漂亮！是吗？}
#{956}{}{Yell too much! Booo!}
{956}{}{喊太多了！嘘！}
#{1000}{}{Come back another time! But you'll surely come, it's simply impossible to resist my wonderful range of goods!}
{1000}{}{下次再来！但你一定会来的，简直无法抵挡我的精彩商品！}
#{1001}{}{Bye.}
{1001}{}{再见。}
#{1002}{}{Uff.}
{1002}{}{不明飞行物。}
#{1050}{}{[You're looking at the shelf with what's supposed to be special goods. This is what you see: }
{1050}{}{[你在看架子上放的应该是特殊商品。这就是你看到的：}
#{1051}{}{A picture of some kind. }
{1051}{}{某种照片。}
#{1052}{}{A doll. }
{1052}{}{一个洋娃娃。}
#{1053}{}{A magazine. }
{1053}{}{一本杂志。}
#{1054}{}{A rubber doll. }
{1054}{}{一个橡胶娃娃。}
#{1055}{}{A very familiar-looking talisman. }
{1055}{}{一个看起来很熟悉的护身符。}
#{1056}{}{]}
{1056}{}{]}
#{1070}{}{}
{1070}{}{}
#{1057}{}{What's on that picture?}
{1057}{}{那张照片上是什么？}
#{1058}{}{Show me the doll.}
{1058}{}{给我看洋娃娃。}
#{1059}{}{What's so interesting about that magazine?}
{1059}{}{那本杂志有什么有趣的地方？}
#{1060}{}{An inflatable doll?}
{1060}{}{充气娃娃？}
#{1061}{}{That talisman looks exactly like... Can I have a closer look at it?}
{1061}{}{那个护身符看起来很像……我能仔细看看吗？}
#{1062}{}{These are all useless junk.}
{1062}{}{这些都是无用的垃圾。}
#{1100}{}{[Salem hands you a framed picture of a man whose face has faded away long ago. There's some text beneath the picture saying "El". The rest is gone.] That's the great El! He must have been a holy man of some kind. I bet the picture brings luck to its owner. Great thing for a 50, huh? Sure it is!}
{1100}{}{[塞勒姆递给你一张镶好镜框的照片，照片上的人的脸早已褪色。图片下面有些文字写着“El”。剩下的都不见了。]这就是伟大的艾尔！他一定是个什么样的圣人。我打赌这幅画会给主人带来好运。对一个50岁的人来说是件好事，是吗？当然是！}
#{1101}{}{OK, I'll take it.}
{1101}{}{好的，我买了。}
#{1102}{}{I don't have enough cash, I'll be back.}
{1102}{}{我没有足够的现金，我会回来的。}
#{1103}{}{What else have you got?}
{1103}{}{你还有什么？}
#{1104}{}{Not interested.}
{1104}{}{不感兴趣。}
#{1150}{}{[Salem hands you a small ragdoll with a red nose. The words "Mr. Nixon" are written on its t-shirt.] Great innocent thing for kids to play with. Every kid'll surely be glad to have it! For just a hundred caps!}
{1150}{}{[塞勒姆递给你一个红鼻子的小布娃娃。“尼克松先生”的字样写在它的t恤上，]对于孩子们来说，这是一件非常天真的事情。每个孩子都会高兴的！只要一百个瓶盖！}
#{1151}{}{OK, I'll take it.}
{1151}{}{好的，我买了。}
#{1152}{}{I don't have enough cash, I'll be back.}
{1152}{}{我没有足够的现金，我会回来的。}
#{1153}{}{What else have you got?}
{1153}{}{你还有什么？}
#{1154}{}{Not interested.}
{1154}{}{不感兴趣。}
#{1200}{}{[Very carefully and slowly, as if it could fall apart any minute now, Salem gives you the "Cat's Paw" magazine.] Very spicy "reading", if you know what I mean, ha ha. If I were you, I'd wipe my ass with a cactus rather than lose this! Great price of 60 caps!}
{1200}{}{[非常小心地慢慢地，好像随时都可能分崩离析一样，塞勒姆给了你一本“猫爪”杂志。]非常辛辣的“阅读”，如果你知道我的意思，哈哈。如果我是你，我宁愿用仙人掌擦屁股也不愿失去这个！60个瓶盖的好价钱！}
#{1201}{}{OK, I'll take it.}
{1201}{}{好的，我买了。}
#{1202}{}{I don't have enough cash, I'll be back.}
{1202}{}{我没有足够的现金，我会回来的。}
#{1203}{}{What else have you got?}
{1203}{}{你还有什么？}
#{1204}{}{Not interested.}
{1204}{}{不感兴趣。}
#{1250}{}{[Very carefully and slowly, as if it could fall apart any minute now, Salem gives you the "Cat's Paw" magazine.] If the miss is interested in a men's magazine, it's hers for a mere 60 caps. I can't go lower as it'd be to difficult for me to give it away, ha ha.}
{1250}{}{[非常小心地慢慢地，好像随时都可能分崩离析似的，塞勒姆给了你一本“猫爪”杂志。]如果小姐对一本男性杂志感兴趣，那就是她的杂志，只要60英镑。我不能再低了，因为我很难把它送出去，哈哈。}
#{1251}{}{OK, I'll take it.}
{1251}{}{好的，我买了。}
#{1252}{}{I don't have enough cash, I'll be back.}
{1252}{}{我没有足够的现金，我会回来的。}
#{1253}{}{What else have you got?}
{1253}{}{你还有什么？}
#{1254}{}{Not interested.}
{1254}{}{不感兴趣。}
#{1300}{}{[Salem shows you the inflatable doll with a wide smile.] Traveler's best friend. She doesn't speak and is always willing. And this one doesn't even leak! True, she's got a few unplanned holes but they've all been properly sealed, ha ha. 300 caps, just 'cause it's you!}
{1300}{}{[塞勒姆微笑着向你展示充气娃娃。.]旅行者最好的朋友。她不说话，总是心甘情愿。而这个甚至不漏！是的，她有几个计划外的洞，但都封好了，哈哈。300个瓶盖，就因为是你，伙计！}
#{1301}{}{OK, I'll take it.}
{1301}{}{好的，我买了。}
#{1302}{}{I don't have enough cash, I'll be back.}
{1302}{}{我没有足够的现金，我会回来的。}
#{1303}{}{What else have you got?}
{1303}{}{你还有什么？}
#{1304}{}{Not interested.}
{1304}{}{不感兴趣。}
#{1350}{}{Well, you know, miss. A lone wanderer in the wasteland needs to entertain himself, he he. I don't know what you might use it for but I can't sell it for less than 300 caps. It's very sought-after item. On top of that, this one doesn't leak!}
{1350}{}{嗯，你知道的，小姐。一个孤独的流浪者需要自娱自乐，他说。我不知道你会用它做什么，但我不能以低于300顶的价格出售。这是很受欢迎的商品。最重要的是，这个不会漏！}
#{1351}{}{OK, I'll take it.}
{1351}{}{好的，我买了。}
#{1352}{}{I don't have enough cash, I'll be back.}
{1352}{}{我没有足够的现金，我会回来的。}
#{1353}{}{What else have you got?}
{1353}{}{你还有什么？}
#{1354}{}{Not interested.}
{1354}{}{不感兴趣。}
#{1400}{}{[When you take Salem's talisman in your hand, you find out it is the same as the one you'd had when you woke up in the cave. The talisman is your best clue to your forgotten life.] A finely crafted talisman! It may possess magical powers, who knows! It's worth trying for a mere 10 caps!}
{1400}{}{[当你拿着塞勒姆的护身符时，你会发现它和你在山洞里醒来时的护身符是一样的。护身符是你忘记生活的最好线索。]一个精心制作的护身符！它可能拥有神奇的力量，谁知道呢！只要10个瓶盖就值得一试！}
#{1401}{}{Deal.}
{1401}{}{处理。}
#{1402}{}{I don't have enough cash, I'll be back.}
{1402}{}{我没有足够的现金，我会回来的。}
#{1403}{}{What else have you got?}
{1403}{}{你还有什么？}
#{1404}{}{Not interested.}
{1404}{}{不感兴趣。}
#{1405}{}{Where did you get that talisman?}
{1405}{}{你从哪儿弄来的护身符？}
#{1450}{}{Well, my, such questions. Things are bought and sold, people come and go. Who's supposed to remember. But now that you mention it, I'm sure I got this from a man who traveled with a caravan. So? You buying?}
{1450}{}{好吧，我的天，这样的问题。东西买卖，人来人往。应该记得的人。但既然你提到了，我肯定是从一个开着大篷车旅行的人那里得到的。所以呢？你要买吗？}
#{1451}{}{Give it here, take the money.}
{1451}{}{给我，拿钱。}
#{1452}{}{I don't have enough cash, I'll be back.}
{1452}{}{我没有足够的现金，我会回来的。}
#{1453}{}{What else have you got?}
{1453}{}{你还有什么？}
#{1454}{}{Not interested.}
{1454}{}{不感兴趣。}
#{1455}{}{Where did that caravan come from? Try to remember!}
{1455}{}{那辆大篷车是从哪里来的？试着记住！}
#{1500}{}{It could only have been from Corath or Albuquerque. I don't have time to watch every caravan, I got to earn a living! That brings me back to the talisman. The amazing price of 10 caps is still on the table!}
{1500}{}{可能是科拉斯或阿尔伯克基的。我没时间看每一辆大篷车，我得谋生！我又回到了护身符。10顶瓶盖的惊人价格仍然摆在桌面上！}
#{1501}{}{Give it here, take the money.}
{1501}{}{给我，拿钱。}
#{1502}{}{I don't have enough cash, I'll be back.}
{1502}{}{我没有足够的现金，我会回来的。}
#{1503}{}{What else have you got?}
{1503}{}{你还有什么？}
#{1504}{}{Not interested.}
{1504}{}{不感兴趣。}
#{1505}{}{Suppose you'd make 40 caps, would that make you remember?}
{1505}{}{假设你做了40个瓶盖，你会记得吗？}
#{1550}{}{I've just remembered! [The 40 caps disappear almost instantly.] That caravan came from Albuquerque, I'm sure of that. But you don't have to go there to get a talisman like that, you can get one from me for just 10 caps!}
{1550}{}{我刚想起来！[那40顶瓶盖几乎立刻就消失了]我敢肯定，那辆大篷车是从阿尔伯克基来的。但你不必去那里得到这样的护身符，你可以从我那里得到一个只要10个瓶盖！}
#{1551}{}{Give it here so I'm finally done with you.}
{1551}{}{把它给我，这样我就和你完了。}
#{1552}{}{I don't have enough cash, I'll be back.}
{1552}{}{我没有足够的现金，我会回来的。}
#{1553}{}{What else have you got?}
{1553}{}{你还有什么？}
#{1554}{}{Thanks, but I already have one.}
{1554}{}{谢谢，但我已经有了。}
#{1600}{}{[When you take Salem's talisman into your hand, you find out it is the same as the one you'd had when you woke up in the cave. The talisman is your best clue to your forgotten life.] A finely crafted talisman! It may possess magical powers, who knows! It's worth trying for a mere 10 caps!}
{1600}{}{[当你把塞勒姆的护身符拿到手里时，你会发现它和你在山洞里醒来时的护身符是一样的。护身符是你忘记生活的最好线索。]一个精心制作的护身符！它可能拥有神奇的力量，谁知道呢！只要10个瓶盖就值得一试！}
#{1601}{}{Deal.}
{1601}{}{处理。}
#{1602}{}{I don't have enough cash, I'll be back.}
{1602}{}{我没有足够的现金，我会回来的。}
#{1603}{}{What else have you got?}
{1603}{}{你还有什么？}
#{1604}{}{Not interested.}
{1604}{}{不感兴趣。}
#{1605}{}{Where did you get that talisman?}
{1605}{}{你从哪儿弄来的护身符？}
#{1650}{}{I'm all out of stock right now. Never mind, though! I still have lots of regular goods for great prices!}
{1650}{}{我现在没货了。不过，没关系！我还有很多价格优惠的普通货！}
#{1651}{}{Fine, show me.}
{1651}{}{好吧，给我看看。}
#{1652}{}{Not interested.}
{1652}{}{不感兴趣。}
#{1653}{}{Shooow!}
{1653}{}{嘘！}
#{1654}{}{Yuck!}
{1654}{}{讨厌！}
#{1700}{}{[You're looking at a shelf full of all kinds of stuff. This is what you see: }
{1700}{}{[你看到的是一个装满各种各样东西的架子。这就是你看到的：}
#{1701}{}{A picture of some kind. }
{1701}{}{某种照片。}
#{1702}{}{A doll. }
{1702}{}{一个洋娃娃。}
#{1703}{}{A magazine. }
{1703}{}{一本杂志。}
#{1704}{}{A rubber doll. }
{1704}{}{一个橡胶娃娃。}
#{1705}{}{A talisman. }
{1705}{}{护身符。}
#{1706}{}{]}
{1706}{}{]}
#{1707}{}{Pikchoor!}
{1707}{}{皮克丘！}
#{1708}{}{Pretty dolly!}
{1708}{}{漂亮的多莉！}
#{1709}{}{Paper!}
{1709}{}{纸！}
#{1710}{}{Hee, inflatalabable dollee!}
{1710}{}{嘿，充气娃娃！}
#{1711}{}{Shiny glass-thingie! Shooow!}
{1711}{}{闪亮的玻璃！嘘！}
#{1712}{}{Eew stuff!}
{1712}{}{哎哟！}
#{1750}{}{[Salem hands you a framed picture of a man. His face has faded away long time ago but you're convinced he must have been an AMAZING man. There's part of a description below the picture.] That's the great El! A holy man, that picture surely brings luck! Great price of 60 caps, isn't it? Sure it is!}
{1750}{}{[塞勒姆递给你一张带框的男人照片。他的脸很久以前就不见了，但你确信他一定是个了不起的人。图片下面有一部分描述。]这就是伟大的艾尔！一个圣人，那幅画一定会带来好运！60顶瓶盖的价钱很好，不是吗？当然是！}
#{1751}{}{Mee want!}
{1751}{}{我想要！}
#{1752}{}{Boo.}
{1752}{}{喝倒采。}
#{1753}{}{More?}
{1753}{}{更多？}
#{1754}{}{Ugly, eeew!}
{1754}{}{丑陋，恶心！}
#{1800}{}{[Salem hands you a small ragdoll with a red nose. There's something written on its t-shirt. It's so cute you instantly grab and cuddle with it.] I can see you like it, he he. It can be yours for only 200 caps!}
{1800}{}{[塞勒姆递给你一个红鼻子的小布娃娃。它的t恤上写着什么。它是如此可爱，你立刻抓住它，拥抱它。]我可以看到你喜欢它，他。它可以是你的只有200个上限！}
#{1801}{}{Mee want!}
{1801}{}{我想要！}
#{1802}{}{Boo.}
{1802}{}{喝倒采。}
#{1803}{}{More?}
{1803}{}{更多？}
#{1804}{}{Ugly, eeew!}
{1804}{}{丑陋，恶心！}
#{1850}{}{[Salem hands you a magazine of some sort. He does so with great care, and very slowly.] Very spicy "reading", if you know what I mean, ha ha. If I were you, I'd wipe my ass with a cactus rather than lose this! Great price, only a hundred caps!}
{1850}{}{[塞勒姆递给你一本杂志。他做得很小心，而且很慢。]非常辛辣的“阅读”，如果你知道我的意思，哈哈。如果我是你，我宁愿用仙人掌擦屁股也不愿失去这个！好价钱，只有一百个瓶盖！}
#{1851}{}{Mee want!}
{1851}{}{我想要！}
#{1852}{}{Boo.}
{1852}{}{喝倒采。}
#{1853}{}{More?}
{1853}{}{更多？}
#{1854}{}{Ugly, eeew!}
{1854}{}{丑陋，恶心！}
#{1900}{}{[Salem hands you a magazine of some sort. He does so with great care, and very slowly.] If the miss is interested in a men's magazine, it's hers for a mere 100 caps, whatever she's going to use it for.}
{1900}{}{[塞勒姆递给你一本杂志。如果小姐对一本男性杂志感兴趣的话，只要100顶瓶盖，不管她打算用它做什么，都是她的。}
#{1901}{}{Mee want!}
{1901}{}{我想要！}
#{1902}{}{Boo.}
{1902}{}{喝倒采。}
#{1903}{}{More?}
{1903}{}{更多？}
#{1904}{}{Ugly, eeew!}
{1904}{}{丑陋，恶心！}
#{1950}{}{[Salem shows you the inflatable doll with a wide smile.] Yeah, you can have lotsa fun with this thing or you can use it as an inflatable boat. All you have to do is find a big enough body of water... Somewhere out in the desert, ha ha. Just because it's you, I'll give it to you for a lousy 500 caps!}
{1950}{}{【塞勒姆带着灿烂的笑容向你展示充气娃娃。】是的，你可以玩得很开心，也可以把它当作充气船。你要做的就是找到一个足够大的水体……在沙漠的某个地方，哈哈。就因为是你，我就给你500英镑！}
#{1951}{}{Mee want!}
{1951}{}{我想要！}
#{1952}{}{Boo.}
{1952}{}{喝倒采。}
#{1953}{}{More?}
{1953}{}{更多？}
#{1954}{}{Ugly, eeew!}
{1954}{}{丑陋，恶心！}
#{2000}{}{Well, miss... A fantastic new item! An inflatable boat ideally formed to copy the shape of human body! All you have to do is find a body of water big enough... Somewhere out in the desert, ha ha. Just because it's you, I'll give it to you for a lousy 500 caps!}
{2000}{}{嗯，小姐……一个奇妙的新项目！一个理想的充气船形成复制人体的形状！你要做的就是找到一个足够大的水体……在沙漠的某个地方，哈哈。就因为是你，我就给你500英镑！}
#{2001}{}{Mee want!}
{2001}{}{我想要！}
#{2002}{}{Boo.}
{2002}{}{喝倒采。}
#{2003}{}{More?}
{2003}{}{更多？}
#{2004}{}{Ugly, eeew!}
{2004}{}{丑陋，恶心！}
#{2050}{}{[Salem hands you a nice shiny talisman. You like it, but... Of course! You already have one just like that!] A beautiful magic talisman! And how it reflects the light! Costs only 30 caps!}
{2050}{}{[塞勒姆递给你一个漂亮闪亮的护身符。你喜欢，但是……当然！你已经有这样一个了！]一个美丽的魔法护身符！以及它如何反射光线！只需要30个瓶盖！}
#{2051}{}{[Salem hands you a nice shiny talisman. You like it, but... Of course! You already had one just like that!] A beautiful magic talisman! And how it reflects the light! Costs only 30 caps!}
{2051}{}{[塞勒姆递给你一个漂亮闪亮的护身符。你喜欢，但是……当然！你已经有一个这样的了！]一个美丽的魔法护身符！以及它如何反射光线！只需要30个瓶盖！}
#{2052}{}{[Salem hands you a nice shiny talisman. You like it, but... Of course! You already had one just like that!] A beautiful magic talisman! And how it reflects the light! Costs only 30 caps!}
{2052}{}{[塞勒姆递给你一个漂亮闪亮的护身符。你喜欢，但是……当然！你已经有一个这样的了！]一个美丽的魔法护身符！以及它如何反射光线！只需要30个瓶盖！}
#{2053}{}{Mee want!}
{2053}{}{我想要！}
#{2054}{}{Boo.}
{2054}{}{喝倒采。}
#{2055}{}{More?}
{2055}{}{更多？}
#{2056}{}{Ugly, eeew!}
{2056}{}{丑陋，恶心！}
#{2057}{}{Pretty! }
{2057}{}{漂亮！}
#{2058}{}{ also have! Lookee! [Show him your talisman.]}
{2058}{}{也有！瞧！[给他看你的护身符。]}
#{2100}{}{Damn, that guy from the caravan was full of shit when he said it was one of a kind! Well, never mind that. Won't you buy it? It'd be great to have two, wouldn't it?}
{2100}{}{该死的，车队里的那个家伙说这是独一无二的，真是狗屎！好吧，没关系。你不买吗？有两个就好了，不是吗？}
#{2101}{}{Mee want!}
{2101}{}{我想要！}
#{2102}{}{Boo.}
{2102}{}{喝倒采。}
#{2103}{}{More?}
{2103}{}{更多？}
#{2104}{}{Naah!}
{2104}{}{啊！}
#{2150}{}{I got it, I got it! My goods're so great and prices so low you can't wait to shop at my store! Unfortunately, you'll have to wait a little. Please leave and come back during the opening hours.}
{2150}{}{我明白了，我明白了！我的商品很好，价格也很低，你等不及要到我的店里买了！不幸的是，你得等一会儿。请在营业时间离开并回来。}
#{2151}{}{Eehm... Yeah, just as you say. Me and my patience. I'll come back later.}
{2151}{}{嗯……是的，就像你说的。我和我的耐心。我一会儿回来。}
#{2152}{}{I'm not going anywhere. I'll choose from your sortiment right away. And I certainly don't intend to pay.}
{2152}{}{我哪儿也不去。我马上就从你的悲伤中选择。我当然不打算付钱。}
#{2153}{}{Huh? Oh. Goodie.}
{2153}{}{呵呵？哦。很好。}
#{2154}{}{Naah. Now, you bam!}
{2154}{}{啊。现在，你砰！}
