#{100}{}{You see an elderly woman.}
{100}{}{你看到一个老妇人。}
#{150}{}{You see Mrs. Stapleton.}
{150}{}{你看到斯台普顿太太了。}
#{200}{}{You see an elderly woman with a Desert Eagle in her hand.}
{200}{}{你看到一个老妇人手里拿着一只沙漠鹰。}
#{250}{}{You see Mrs. Stapleton, local librarian.}
{250}{}{你看到当地图书管理员斯台普顿太太了。}
#{300}{}{I'm sorry but I'm not letting you take anything without paying.}
{300}{}{对不起，我不会让你不付钱就拿走任何东西。}
#{500}{}{What do you want here? [She's holding a Desert Eagle in her hand. She's not aiming at you, but even though it looks like that weapon's too heavy for her, she seems determined to start shooting at any moment.]}
{500}{}{你想在这里干什么？[她手里拿着一只沙漠鹰。她没有瞄准你，但即使那武器看起来对她来说太重了，她似乎决心随时开始射击。]}
#{501}{}{Isn't this a shop?}
{501}{}{这不是一家商店吗？}
#{502}{}{Isn't that gun too big for you, lady? I'll bet you it's empty. Let's find out.}
{502}{}{那把枪对你来说是不是太大了，女士？我敢打赌它是空的。让我们看看。}
#{503}{}{Hoo!}
{503}{}{呼！}
#{504}{}{Just calm down, madam, I'm already on my way.}
{504}{}{冷静点，夫人，我已经在路上了。}
#{550}{}{Sure it is. The only things I'm selling are books. I don't know whether my goods can satisfy you enough.}
{550}{}{当然是。我只卖书。我不知道我的货是否能让你满意。}
#{551}{}{I'm certainly interested in books.}
{551}{}{我当然对书感兴趣。}
#{552}{}{Great, I need a good supply of paper sheets. If you haven't been caught by mother nature calling out there in the wastes, where there's nothing at hand but cactuses, you can't imagine what it is to suffer.}
{552}{}{太好了，我需要大量的纸张。如果你还没有被大自然在荒野中呼唤，那里除了仙人掌什么都没有，你无法想象会遭受什么样的痛苦。}
#{553}{}{Bullshit, I'm sure you've got some valuable stuff hidden in here. I'm just going to look around.}
{553}{}{胡说，我肯定你这里藏了一些有价值的东西。我只是四处看看。}
#{554}{}{You're right, I'm not interested in any books, bye.}
{554}{}{你说得对，我对任何书都不感兴趣，再见。}
#{600}{}{Please leave. [She makes an annoyed grimace and aims the Desert Eagle at you, barely holding it up in both hands.]}
{600}{}{请离开。[她做了一个恼怒的鬼脸，把沙漠之鹰对准你，双手几乎不举起来。]}
#{601}{}{No. No one's gonna behave to me like this.}
{601}{}{不，没人会这样对我。}
#{602}{}{I don't think I've said that much. Fine, I'm leaving.}
{602}{}{我想我没说那么多。好吧，我要走了。}
#{603}{}{I don't think I've said that much. Fine, I'm leaving.}
{603}{}{我想我没说那么多。好吧，我要走了。}
#{650}{}{And I hope you're also willing to pay.}
{650}{}{我希望你也愿意付钱。}
#{651}{}{Naturally.}
{651}{}{当然。}
#{652}{}{But maybe I could get a small discount for not cutting your throat for how you're treating me.}
{652}{}{但也许我可以得到一个小折扣，因为你对我的态度没有割破你的喉咙。}
#{700}{}{And I hope you're also willing to pay.}
{700}{}{我希望你也愿意付钱。}
#{701}{}{Naturally.}
{701}{}{当然。}
#{702}{}{But maybe I could get a small discount for not cutting your throat for how you're treating me.}
{702}{}{但也许我可以得到一个小折扣，因为你对我的态度没有割破你的喉咙。}
#{750}{}{I don't have anything that might be of any use to you. Please leave.}
{750}{}{我没有任何对你有用的东西。请离开。}
#{751}{}{Grr!}
{751}{}{格瑞！}
#{752}{}{Bah.}
{752}{}{呸。}
#{800}{}{In that case, welcome, I'm Mrs. Stapleton. [She lowers the gun to the ground but she's still holding it in her hands.] Would you like to see the books I sell or are you looking for something specific?}
{800}{}{既然如此，欢迎光临，我是斯台普顿夫人。[她把枪放在地上，但她手里还拿着枪]你想看看我卖的书，还是想找些特别的？}
#{801}{}{I'll have a look at what you've got.}
{801}{}{我看看你有什么。}
#{802}{}{Do you know by any chance what this sign could mean? [Show her the talisman.]}
{802}{}{你知道这个标志是什么意思吗？[给她看护身符。]}
#{803}{}{Why such caution?}
{803}{}{为什么如此谨慎？}
#{804}{}{You live in this part of town. Does that mean you too were originally from the Hub?}
{804}{}{你住在城里的这个地方。那是不是说你也是从中心来的？}
#{805}{}{I'm not looking for anything in particular right now.}
{805}{}{我现在不想找什么特别的东西。}
#{850}{}{I've run across this in several publications. It's a warning sign against biological hazards. Judging by the form of this one ?? a talisman, I'd say it serves today as a symbol to some new religion or cult without the knowledge of its previous meaning. It's nothing unusual. Children of the Cathedral, for example, used the sign for radiation as their symbol.}
{850}{}{我在几本出版物上都见过这个。这是对生物危害的警告标志。从这个“护身符”的形式来看，我认为它在今天是一个新宗教或邪教的象征，而不知道它以前的含义。没什么不寻常的。例如，大教堂的孩子们就用辐射标志作为他们的象征。}
#{851}{}{Children of the Cathedral?}
{851}{}{大教堂的孩子们？}
#{852}{}{Thank you. Now I'd like to browse your stock.}
{852}{}{非常感谢。现在我想浏览一下你们的股票。}
#{853}{}{Show me the holodisks you sell.}
{853}{}{给我看看你卖的全息光盘。}
#{854}{}{Why such caution before you even started talking to me?}
{854}{}{为什么在你跟我说话之前就这么小心？}
#{855}{}{You live in this part of town. Does that mean you too were originally from the Hub?}
{855}{}{你住在城里的这个地方。那是不是说你也是从中心来的？}
#{856}{}{Thanks, that'll be all.}
{856}{}{谢谢，就这些。}
#{900}{}{I suppose you know what kind of world we live in. Violence is often the most persuasive argument. Just because I'm living alone, many people think I'm easy prey. And it's hard for them to understand that the only things I have are my books.}
{900}{}{我想你知道我们生活在什么样的世界。暴力往往是最有说服力的论据。就因为我一个人住，很多人认为我很容易成为猎物。他们很难理解我只有书。}
#{901}{}{What about the police?}
{901}{}{警察呢？}
#{902}{}{I'd like to have a look at the books you sell.}
{902}{}{我想看看你们卖的书。}
#{903}{}{Show me the holodisks you sell.}
{903}{}{给我看看你卖的全息光盘。}
#{904}{}{Do you know by any chance what this sign could mean? [Show her the talisman.]}
{904}{}{你知道这个标志是什么意思吗？[给她看护身符。]}
#{905}{}{You live in this part of town. Does that mean you too were originally from the Hub?}
{905}{}{你住在城里的这个地方。那是不是说你也是从中心来的？}
#{906}{}{I see, good-bye, then.}
{906}{}{我明白了，那么再见。}
#{950}{}{There's no police. There're just individual cops and none of them care about you unless they can get a buck or two out of you. I refuse to pay for something I should be able to take for granted.}
{950}{}{没有警察。只有个别警察，他们都不关心你，除非他们能从你身上弄到一两块钱。我拒绝为一些我本可以认为理所当然的事情付钱。}
#{951}{}{I'll have a look at what you've got.}
{951}{}{我看看你有什么。}
#{952}{}{Show me the holodisks you sell.}
{952}{}{给我看看你卖的全息光盘。}
#{953}{}{Do you know by any chance what this sign could mean? [Show her the talisman.]}
{953}{}{你知道这个标志是什么意思吗？[给她看护身符。]}
#{954}{}{You live in this part of town. Does that mean you too were originally from the Hub?}
{954}{}{你住在城里的这个地方。那是不是说你也是从中心来的？}
#{955}{}{That's all I need right now.}
{955}{}{这就是我现在所需要的。}
#{1000}{}{Yes. [She sighs.] Please let's talk about something else.}
{1000}{}{对。[她叹了口气]请让我们谈点别的。}
#{1001}{}{I'm sorry if you don't want to talk about it. I'd just like to know what actually happened there.}
{1001}{}{如果你不想谈的话，我很抱歉。我只想知道那里到底发生了什么。}
#{1002}{}{I'm sorry if you don't want to talk about it. I'd just like to know what actually happened there.}
{1002}{}{如果你不想谈的话，我很抱歉。我只想知道那里到底发生了什么。}
#{1003}{}{I'll have a look at what you're selling instead, then.}
{1003}{}{那我来看看你们卖什么。}
#{1004}{}{Show me the holodisks you sell.}
{1004}{}{给我看看你卖的全息光盘。}
#{1005}{}{Do you know by any chance what this sign could mean? [Show her the talisman.]}
{1005}{}{你知道这个标志是什么意思吗？[给她看护身符。]}
#{1006}{}{Fine, let's talk about why you're so cautious.}
{1006}{}{好吧，我们来谈谈你为什么这么谨慎。}
#{1007}{}{Bye, then.}
{1007}{}{那么，再见。}
#{1050}{}{You really want to hear about it? Ask anyone who was living there, you'll always get a slightly different version of the same story. Supermutants attacked and destroyed the Hub. I managed to escape before the fighting began. Because of this, I wasn't able to take much with me. Most of my collection of books burned down along with the rest of the town. I've told myself many times that I should have died there in my feeble effort to defend.}
{1050}{}{你真的想听吗？如果问住在那里的人，你总是会得到同一个故事稍有不同的版本。超级变种人袭击并摧毁了中心。我在战斗开始前设法逃走了。因为这个，我不能带太多东西。我收藏的大部分书和镇上其他的书一起被烧毁了。我已经告诉自己很多次了，我应该死在那里，在我无力的努力捍卫。}
#{1051}{}{And why did you come to Sedit in particular?}
{1051}{}{你为什么特别来这里？}
#{1052}{}{Nobody tried to rebuild the Hub?}
{1052}{}{没有人试图重建中心？}
#{1053}{}{I'll have a look at what you've got.}
{1053}{}{我看看你有什么。}
#{1054}{}{Show me the holodisks you sell.}
{1054}{}{给我看看你卖的全息光盘。}
#{1055}{}{Do you know by any chance what this sign could mean? [Show her the talisman.]}
{1055}{}{你知道这个标志是什么意思吗？[给她看护身符。]}
#{1056}{}{Why such caution before you even started talking to me?}
{1056}{}{为什么在你跟我说话之前就这么小心？}
#{1057}{}{I have to go.}
{1057}{}{我得走了。}
#{1100}{}{I don't know myself, I guess I just wanted to go as far away as possible, away from all those things and this town had been known in the Hub for a short while before the attack. In the end, I'm doing the same here what I did there, even though I suppose I'll never collect as many books as I did there. There's not many left and there are even less people interested in them.}
{1100}{}{我不了解我自己，我想我只是想走得越远越好，远离所有这些东西，在袭击发生前，这个小镇在市中心已经有一段时间了。最后，我在这里做的和在那里做的一样，尽管我想我永远不会像在那里那样收集那么多的书。剩下的不多了，对他们感兴趣的人更少了。}
#{1101}{}{Nobody tried to rebuild the Hub?}
{1101}{}{没有人试图重建中心？}
#{1102}{}{I'll have a look at what you've got.}
{1102}{}{我看看你有什么。}
#{1103}{}{Show me the holodisks you sell.}
{1103}{}{给我看看你卖的全息光盘。}
#{1104}{}{Do you know by any chance what this sign could mean? [Show her the talisman.]}
{1104}{}{你知道这个标志是什么意思吗？[给她看护身符。]}
#{1105}{}{Why such caution before you even started talking to me?}
{1105}{}{为什么在你跟我说话之前就这么小心？}
#{1106}{}{I have to go.}
{1106}{}{我得走了。}
#{1150}{}{A religion that had the Master as their living god. But the only Master's achievement was the creation of supermutants who accomplished only destruction. Just as they destroyed the Hub.}
{1150}{}{一种以主人为他们的活神的宗教。但大师唯一的成就是创造了只完成毁灭的超级变种人。就像他们摧毁了中心一样。}
#{1151}{}{What happened to the Hub?}
{1151}{}{中心怎么了？}
#{1152}{}{I'll have a look at what you've got.}
{1152}{}{我看看你有什么。}
#{1153}{}{Show me the holodisks you sell.}
{1153}{}{给我看看你卖的全息光盘。}
#{1154}{}{Why such caution before you even started talking to me?}
{1154}{}{为什么在你跟我说话之前就这么小心？}
#{1155}{}{That's all, bye.}
{1155}{}{就这些，再见。}
#{1200}{}{That's strange, it's true I've heard some rumors about rebuilding the Hub. But I don't pay much attention to them. I don't want to waste time reminiscing. Moreover, I suppose it's just someone's wishful thinking.}
{1200}{}{真奇怪，我确实听说过一些关于重建中心的传言。但我不太注意他们。我不想浪费时间回忆。而且，我想这只是某人的一厢情愿。}
#{1201}{}{And why did you go to Sedit in particular?}
{1201}{}{你为什么特别去赛迪特？}
#{1202}{}{I'll have a look at what you've got.}
{1202}{}{我看看你有什么。}
#{1203}{}{Show me the holodisks you sell.}
{1203}{}{给我看看你卖的全息光盘。}
#{1204}{}{Do you know by any chance what this sign could mean? [Show her the talisman.]}
{1204}{}{你知道这个标志是什么意思吗？[给她看护身符。]}
#{1205}{}{Why such caution before you even started talking to me?}
{1205}{}{为什么在你跟我说话之前就这么小心？}
#{1206}{}{I have to go.}
{1206}{}{我得走了。}
#{1250}{}{Come again whenever you're in need of a book.}
{1250}{}{你需要书的时候再来。}
#{1251}{}{I have to say your prices are a little steep.}
{1251}{}{我不得不说你们的价格有点高。}
#{1252}{}{Can I ask about something?}
{1252}{}{我能问一下吗？}
#{1253}{}{Bye.}
{1253}{}{再见。}
#{1300}{}{Yeah, I admit. Surely you understand that getting my hands on any books is nothing easy. Their price is given solely by their rarity.}
{1300}{}{是的，我承认。你一定明白，让我拿到任何一本书都不容易。它们的价格完全取决于它们的稀有性。}
#{1301}{}{Can I ask about something?}
{1301}{}{我能问一下吗？}
#{1302}{}{Bye.}
{1302}{}{再见。}
#{1350}{}{Sure, what would you like to know?}
{1350}{}{当然，你想知道什么？}
#{1351}{}{In fact, I'd like to buy something else.}
{1351}{}{事实上，我想买点别的东西。}
#{1352}{}{Show me the holodisks you sell.}
{1352}{}{给我看看你卖的全息光盘。}
#{1353}{}{Do you know by any chance what this sign could mean? [Show her the talisman.]}
{1353}{}{你知道这个标志是什么意思吗？[给她看护身符。]}
#{1354}{}{Why such caution before you even started talking to me?}
{1354}{}{为什么在你跟我说话之前就这么小心？}
#{1355}{}{You live in this part of town. Does that mean you too were originally from the Hub?}
{1355}{}{你住在城里的这个地方。那是不是说你也是从中心来的？}
#{1356}{}{Actually, that'll be all.}
{1356}{}{实际上，就这些了。}
#{1400}{}{I'm glad to see you again. What are you looking for this time? [She's being nice but the gun's still in her hands.]}
{1400}{}{很高兴再次见到你。这次你在找什么？[她很好，但枪还在她手里。]}
#{1401}{}{I'd like to buy some books.}
{1401}{}{我想买一些书。}
#{1402}{}{Show me the holodisks you sell.}
{1402}{}{给我看看你卖的全息光盘。}
#{1403}{}{Do you know by any chance what this sign could mean? [Show her the talisman.]}
{1403}{}{你知道这个标志是什么意思吗？[给她看护身符。]}
#{1404}{}{Why still so cautious?}
{1404}{}{为什么还这么谨慎？}
#{1405}{}{You live in this part of town. Does that mean you too were originally from the Hub?}
{1405}{}{你住在城里的这个地方。那是不是说你也是从中心来的？}
#{1406}{}{I'm not looking for anything in particular right now.}
{1406}{}{我现在不想找什么特别的东西。}
#{1407}{}{Hoo!}
{1407}{}{呼！}
#{1450}{}{What are you doing here again? Please leave. [She aims the Desert Eagle at you, barely holding it up in both hands.]}
{1450}{}{你又在这里干什么？请离开。[她把沙漠之鹰对准你，双手几乎举不起来。]}
#{1451}{}{I want to apologize. My behavior was inexcusable. Can you forgive me?}
{1451}{}{我想道歉。我的行为是不可原谅的。你能原谅我吗？}
#{1452}{}{I'm not going anywhere, old hag!}
{1452}{}{我哪儿也不去，老巫婆！}
#{1453}{}{Fine, I'm leaving.}
{1453}{}{好吧，我要走了。}
#{1454}{}{Ugh.}
{1454}{}{啊。}
#{1500}{}{No. I'm sorry, but I can't.}
{1500}{}{不，对不起，我不能。}
#{1501}{}{You'll regret this!}
{1501}{}{你会后悔的！}
#{1502}{}{Good-bye, then.}
{1502}{}{那么，再见。}
#{1550}{}{You look like you mean it. Fine, I forgive you.}
{1550}{}{你看起来是认真的。好吧，我原谅你。}
#{1551}{}{Can I have a look at what you're selling, now?}
{1551}{}{我能看看你们现在卖什么吗？}
#{1552}{}{Please show me the holodisks you sell.}
{1552}{}{请给我看看你们卖的全息光盘。}
#{1553}{}{Do you know by any chance what this sign could mean? [Show her the talisman.]}
{1553}{}{你知道这个标志是什么意思吗？[给她看护身符。]}
#{1554}{}{Why such caution?}
{1554}{}{为什么如此谨慎？}
#{1555}{}{You live in this part of town. Does that mean you too were originally from the Hub?}
{1555}{}{你住在城里的这个地方。那是不是说你也是从中心来的？}
#{1556}{}{Thank you.}
{1556}{}{非常感谢。}
#{1580}{}{Interesting...}
{1580}{}{有趣。。。}
#{1581}{}{Yes?}
{1581}{}{对？}
#{1600}{}{I've noticed you own a Pip-Boy. I might have some pre-war holodisks, if you'd be interested.}
{1600}{}{我注意到你有个小男孩。如果你有兴趣的话，我可能有一些战前的全息光盘。}
#{1601}{}{Of course I'm interested.}
{1601}{}{我当然有兴趣。}
#{1602}{}{Well, I have to say that just your books cost quite a lot.}
{1602}{}{好吧，我得说你的书就花了不少钱。}
#{1603}{}{I'm interested in something else.}
{1603}{}{我对别的东西感兴趣。}
#{1604}{}{Not at the moment, bye.}
{1604}{}{现在不行，再见。}
#{1650}{}{As you can see, I don't have many, but all of them have been recorder before the war. They cost 600 caps each and I don't negotiate.}
{1650}{}{正如你所看到的，我没有多少，但所有的都是战前的录音机。他们每顶600顶，我不谈判。}
#{1651}{}{How exactly do holodisks work?}
{1651}{}{全息盘到底是怎么工作的？}
#{1652}{}{Can you tell me in more detail what's on those holodisks?}
{1652}{}{你能更详细地告诉我那些全息磁盘上有什么吗？}
#{1653}{}{I'll take the "Nuclear Attacks and You" holodisk. Here's 600 caps.}
{1653}{}{我要“核攻击和你”的全息光盘。这是600顶瓶盖。}
#{1654}{}{I'll take the holodisk "Vault Locations v12.004". Here's 600 caps.}
{1654}{}{我要全息磁盘“保险库位置v12.004”。这是600顶瓶盖。}
#{1655}{}{I'll take the "A Treatise on Mutations". Here's 600 caps.}
{1655}{}{我要“突变论”。这是600顶瓶盖。}
#{1656}{}{I'm interested in something else right now.}
{1656}{}{我现在对别的东西感兴趣。}
#{1657}{}{I don't want any holodisks, bye.}
{1657}{}{我不要全息光盘，再见。}
#{1658}{}{I don't have 600 caps. I'm interested in something else.}
{1658}{}{我没有600个瓶盖。我对别的东西感兴趣。}
#{1659}{}{Maybe I'll come back when I have 600 caps, bye.}
{1659}{}{也许我有600顶瓶盖就回来，再见。}
#{1700}{}{A holodisk contains information that can be read by certain special devices. I've noticed you own Pip-Boy. You can use it to decode, read and archive information stored on the holodisk.}
{1700}{}{全息磁盘包含某些特殊设备可以读取的信息。我注意到你有个皮普小子。你可以用它来解码，读取和存档存储在全息磁盘上的信息。}
#{1701}{}{Can you tell me in more detail what's on those holodisks?}
{1701}{}{你能更详细地告诉我那些全息磁盘上有什么吗？}
#{1702}{}{I'll take the "Nuclear Attacks and You" holodisk. Here's 600 caps.}
{1702}{}{我要“核攻击和你”的全息光盘。这是600顶瓶盖。}
#{1703}{}{I'll take the holodisk "Vault Locations v12.004". Here's 600 caps.}
{1703}{}{我要全息磁盘“保险库位置v12.004”。这是600顶瓶盖。}
#{1704}{}{I'll take the "A Treatise on Mutations". Here's 600 caps.}
{1704}{}{我要“突变论”。这是600顶瓶盖。}
#{1705}{}{I'm interested in something else right now.}
{1705}{}{我现在对别的东西感兴趣。}
#{1706}{}{I don't want any holodisks, bye.}
{1706}{}{我不要全息光盘，再见。}
#{1707}{}{I don't have 600 caps. I'm interested in something else.}
{1707}{}{我没有600个瓶盖。我对别的东西感兴趣。}
#{1708}{}{Maybe I'll come back when I have 600 caps, bye.}
{1708}{}{也许我有600顶瓶盖就回来，再见。}
#{1750}{}{I'm sorry, but I no longer own a device that would read them. You'll have to do with what's written on the tags.}
{1750}{}{很抱歉，我已经没有可以读取它们的设备了。你得处理标签上写的东西。}
#{1751}{}{How exactly do holodisks work?}
{1751}{}{全息盘到底是怎么工作的？}
#{1752}{}{I'll take the "Nuclear Attacks and You" holodisk. Here's 600 caps.}
{1752}{}{我要“核攻击和你”的全息光盘。这是600顶瓶盖。}
#{1753}{}{I'll take the holodisk "Vault Locations v12.004". Here's 600 caps.}
{1753}{}{我要全息磁盘“保险库位置v12.004”。这是600顶瓶盖。}
#{1754}{}{I'll take the "A Treatise on Mutations". Here's 600 caps.}
{1754}{}{我要“突变论”。这是600顶瓶盖。}
#{1755}{}{I'm interested in something else right now.}
{1755}{}{我现在对别的东西感兴趣。}
#{1756}{}{I don't want any holodisks, bye.}
{1756}{}{我不要全息光盘，再见。}
#{1757}{}{I don't have 600 caps. I'm interested in something else.}
{1757}{}{我没有600个瓶盖。我对别的东西感兴趣。}
#{1758}{}{Maybe I'll come back when I have 600 caps, bye.}
{1758}{}{也许我有600顶瓶盖就回来，再见。}
#{1800}{}{Are you interested in any other holodisks or books?}
{1800}{}{你对其他全息光盘或书感兴趣吗？}
#{1801}{}{Books.}
{1801}{}{书。}
#{1802}{}{Show me those holodisks.}
{1802}{}{给我看看那些全息光盘。}
#{1803}{}{Do you know by any chance what this sign could mean? [Show her the talisman.]}
{1803}{}{你知道这个标志是什么意思吗？[给她看护身符。]}
#{1804}{}{Why such caution before you even started talking to me?}
{1804}{}{为什么在你跟我说话之前就这么小心？}
#{1805}{}{You live in this part of town. Does that mean you too were originally from the Hub?}
{1805}{}{你住在城里的这个地方。那是不是说你也是从中心来的？}
#{1806}{}{Actually, that'll be all.}
{1806}{}{实际上，就这些了。}
#{1850}{}{We're closed. Please leave or I'll be forced to start shooting.}
{1850}{}{我们关门了。请离开，否则我就被迫开枪了。}
#{1851}{}{I apologize and I'm leaving.}
{1851}{}{我道歉，我要走了。}
#{1852}{}{Feel free to try it. We'll see who'll remain standing.}
{1852}{}{尽管试试吧。我们看看谁还能站着。}
#{1853}{}{No boom! Bye-bye.}
{1853}{}{没有轰！再见。}
#{1854}{}{Wham bam to you, you dead.}
{1854}{}{砰的一声，你死定了。}
