#{100}{}{You see a suspicious man.}
{100}{}{你看到一个可疑的人。}
#{200}{}{You see a man, he seems to be waiting for someone.}
{200}{}{你看到一个男人，他好像在等人。}
#{300}{}{Fuck, nosey parker!}
{300}{}{操，多管闲事的帕克！}
#{310}{}{The man stubs out the cigarette, takes a look around for the last time, checking to see if he's being followed, and sets off.}
{310}{}{那人掐灭香烟，最后一次环顾四周，看看是否有人跟踪他，然后出发了。}
#{500}{}{Fuck off.}
{500}{}{滚开。}
#{501}{}{You waiting for somebody?}
{501}{}{你在等人吗？}
#{502}{}{Why so grumpy? I'm just trying to spare a word or two. Did you hear the latest word on the street?}
{502}{}{为什么这么暴躁？我只是想说一两句话。你听到街上最新的消息了吗？}
#{503}{}{Easy does it, man.}
{503}{}{放轻松，伙计。}
#{504}{}{Uff.}
{504}{}{不明飞行物。}
#{550}{}{Why the fuck do you keep talking to me? Leave me alone. [He tries to look cool, but he clearly became nervous.]}
{550}{}{你他妈的为什么一直跟我说话？别管我。[他试图装酷，但显然变得紧张起来。]}
#{551}{}{Where's the sheriff's son? Spit it out!}
{551}{}{警长的儿子呢？吐出来！}
#{552}{}{OK, have it your way.}
{552}{}{好吧，随你的便。}
#{553}{}{Take it easy. Haven't you heard the word on the street?}
{553}{}{别紧张。你没听到街上有这个词吗？}
#{554}{}{OK, as you wish. [Step aside and wait for him to leave so you can follow.]}
{554}{}{好的，如你所愿。[站到一边等他离开，这样你就可以跟着了。]}
#{555}{}{As you wish. [Step aside and wait for him to leave so you can follow.]}
{555}{}{如你所愿。[站到一边等他离开，这样你就可以跟着了。]}
#{600}{}{Damn, that bitch talked!}
{600}{}{该死，那婊子说话了！}
#{601}{}{Spit it...}
{601}{}{吐出来。。。}
#{650}{}{Fuck, get lost.}
{650}{}{妈的，滚开。}
#{651}{}{They say the sheriff's boy's been kidnapped.}
{651}{}{他们说警长的儿子被绑架了。}
#{700}{}{Yeah? Why should I give a fuck?}
{700}{}{是 啊？我为什么要管他妈的？}
#{701}{}{Well, the word is the kidnappers have a hiding place in Little Hub. And right now this spot's surrounded by cops because they think one of the kidnappers is supposed to be waiting here. Now you get what I'm trying to say to you?}
{701}{}{嗯，据说绑匪在小中心有个藏身之处。现在这个地方被警察包围了，因为他们认为一个绑匪应该在这里等着。现在你明白我想对你说的了吗？}
#{750}{}{Damn, that bitch talked!}
{750}{}{该死，那婊子说话了！}
#{751}{}{Bingo.}
{751}{}{答对 了。}
#{800}{}{Look, I got nothing to do with that. I'm just a messenger. Honest, mum's the word. Nobody needs to shoot or anything. How 'bout I tell you where that hiding place is and you let me go? Do we have a deal?}
{800}{}{听着，我和那没关系。我只是个信使。老实说，妈妈说了算。没人需要开枪什么的。不如我告诉你那个藏身处在哪里，然后你放我走？我们有协议吗？}
#{801}{}{OK, spill it.}
{801}{}{好吧，说出来。}
#{802}{}{No deal, bonehead.}
{802}{}{没什么，笨蛋。}
#{850}{}{Really? Thanks. There's an alley leading to that house right between Falcon's Flight and the house of that Stapleton woman. I'm off. You won't see me 'round here, you can bet.}
{850}{}{真正地？谢谢。在Falcon的航班和Stapleton女人的房子之间有一条小巷通往那所房子。我走了。你肯定在这附近看不到我。}
#{851}{}{Get lost.}
{851}{}{滚开。}
#{852}{}{Not so fast. I can take you down, now.}
{852}{}{别那么快。我现在可以把你干掉。}
