#{100}{}{You see a regular domesticated brahmin.}
{100}{}{你看到一个普通的驯化的双头牛。}
#{101}{}{The reason for brahmin having two heads is due to early exposure of radation to what used to be called a cow.}
{101}{}{双头牛之所以有两个头，是因为过去存放牛的地方被暴露在辐射中。}
#{102}{}{You don??t notice anything unusual about the brahmin.}
{102}{}{你不会注意到双头牛有什么不寻常的地方。}
#{103}{}{Brahmin aren't much for conversations.}
{103}{}{双头牛不太适合交谈。}
#{104}{}{Have you nothing better to do than sit around talking to a two headed cow?}
{104}{}{你除了坐在那儿和一头双头牛说话之外，没有别的事可做吗？}
#{105}{}{It's a brahmin. It has two heads.}
{105}{}{是双头牛。它有两个头。}
#{201}{}{Mooo...}
{201}{}{牟牟牟牟...}
#{202}{}{Mooo Mooo Mooo...}
{202}{}{牟牟牟牟...牟牟牟牟...}
#{203}{}{Mooo...}
{203}{}{牟牟牟牟...}
#{204}{}{Moooooo...}
{204}{}{牟牟牟牟...}
#{205}{}{Mooooooooo...}
{205}{}{牟牟牟牟...}
#{206}{}{:: GRUNT ::}
{206}{}{咕噜声...}
