##############################
#???????: ???
#???: ???
#??????? ????????: ????????? ?????? ???
#???? ????????: 28.05.2014
##############################
#??? ???? "????? 2207"
#?????? "Zoomer" ???????
##############################
#
#???????? ????????
#
# ?? ??????????
### {1}{}{You see a big man. He is smiling.}
{1}{}{你看到一个大个子，他在微笑。}
### {2}{}{Despite his size and age, he looks lively and dashing.}
{2}{}{尽管他身材魁梧，年事已高，但他看起来活泼潇洒。}
#
# ????? ??????????
### {3}{}{You see Burns.}
{3}{}{你看到伯恩斯了。}
### {4}{}{He is smiling at you. As usual.}
{4}{}{他在对你微笑。和往常一样。}
#
#????? ?????????? ??????
#
#Node001
### {10}{}{[Yo see a massive man in his thirties. He is smiling through a huge mustache, rubbing his old machinegun.] Whoa! Suddenly, we have someone new-and-screwed here!}
{10}{}{[你看到一个三十多岁的魁梧男人。他留着大胡子，摩擦着他的旧机枪，面带微笑。]哇！突然间，我们有了一个新的，搞砸了这里！}
### {11}{002}{Do you know what "lexical reduplication" means?}
{11}{002}{你知道“词汇重叠”是什么意思吗？}
### {12}{007}{Hello to you too, old-and-bold.}
{12}{007}{你好，老大胆。}
### {13}{998}{You are practically a king of jokes. Want me to shove your crown up your ass?}
{13}{998}{你简直是个笑话大王。想让我把你的皇冠塞到屁股上吗？}
### {14}{011}{[don't say a word, drilling him with your stare]}
{14}{011}{[一句话也不要说，用你的眼神折磨他]}
### {15}{008}{Not funny.}
{15}{008}{一点也不好笑。}
### {16}{011}{[start to laugh loudly. When the joker laughs as loud as you, stop and stare at him with a stone face.]}
{16}{011}{[开始大声大笑。当小丑笑得和你一样大声时，停下来，板着脸盯着他看。]}

#Node002
### {20}{}{Redu... What?}
{20}{}{雷杜。。。什么}
### {21}{003}{...plication. Your jokes correspond to the level of your intellect. I must say, it's quite low.}
{21}{003}{你的笑话符合你的智力水平。我必须说，它很低。}
### {22}{006}{...plication. Nevermind. I got my joke. I'm }
{22}{006}{…复制。永不终止。我明白我的笑话了。我是}
### {23}{006}{.}
{23}{006}{。}

#Node003
### {29}{}{[his face becomes serious, he is silently looking right into your eyes. You have a feeling that his nostrils are about to let off some steam.]}
{29}{}{[他的脸变得严肃起来，他默默地看着你的眼睛。你有一种感觉，他的鼻孔快要泄出一些蒸汽了。]}
### {30}{004}{Relax, man. Just take it a little easy on jokes. If it was somebody else, I'd already started a fistfight. But I see that you are quite alright. Peace? I'm }
{30}{004}{放松点，伙计，别开玩笑了。如果是别人，我早就开始打架了。但我看到你很好。和平我是}
### {31}{004}{.}
{31}{004}{。}
### {32}{998}{In fact, you look just like your jokes - like shit.}
{32}{998}{事实上，你看起来就像你的笑话——像大便。}


#Node004
### {40}{}{[he slightly calms down, although he isn't smiling anymore] The name's Burns. I'm the head of security around here. The kind of guys who can convince you that you are wrong and want to do the right thing. Hehe. [he grins]}
{40}{}{[他稍微平静下来，尽管他不再微笑了。]这个名字叫伯恩斯。我是这里的安全负责人。那种能让你相信自己错了并想做正确事情的人。呵呵。[他咧嘴笑着]}
### {41}{005}{Oh, you mean your low-ranking hominids, like you?}
{41}{005}{哦，你是说像你这样的低级原始人？}
### {42}{010}{I came here recently and have some questions. Of course, if the head of security can spare some time to answer them.}
{42}{010}{我最近来过这里，有一些问题。当然，如果安全负责人能抽出一些时间回答他们的话。}

#Node005
### {50}{}{F- What?! }
{50}{}{F-什么？！}
### {51}{010}{Nevermind. I came here recently and have some questions. Of course, if the head of security can spare some time to answer them.}
{51}{010}{没关系。我最近来过这里，有一些问题。当然，如果安全负责人能抽出一些时间回答他们的话。}
### {52}{998}{I'm saying that you are a retarded ape.}
{52}{998}{我是说你是一只弱智的猿猴。}

#Node006
### {60}{}{I'm Burns. I'm the head of security in NWO. }
{60}{}{我叫伯恩斯。我是NWO的安全负责人。}
### {61}{010}{I'm new here. I'd like to ask some questions.}
{61}{010}{我是新来的。我想问一些问题。}

#Node007
### {70}{}{I see you are a funny guy too? I think we'll get along just fine.}
{70}{}{我看你也是个有趣的家伙？我想我们会相处得很好。}
### {71}{008}{That was sarcasm, actually.}
{71}{008}{实际上，那是讽刺。}
### {72}{006}{Yeah, kinda.}
{72}{006}{是的，有点。}
### {73}{009}{No, I'm not funny. And you are not very funny too.}
{73}{009}{不，我一点也不好笑。你也不是很有趣。}
### {74}{006}{I hope so. And you are... }
{74}{006}{我希望如此。而你。。。}

#Node008
### {80}{}{Yeah? Oh... Screw it then. I'm Burns, the head of security in this wonderful town.}
{80}{}{是 啊哦那就去死吧。我是伯恩斯，这个美丽小镇的安全负责人。}
### {81}{010}{I'm new here. I'd like to ask some questions.}
{81}{010}{我是新来的。我想问一些问题。}

#Node009
### {90}{}{[he gets silent] My name is Burns. I'm in charge of the town's security. }
{90}{}{[他沉默了]我叫伯恩斯。我负责镇上的安全。}
### {91}{010}{Uh-huh. Okay. I hope the head of security has some time to answer my questions?}
{91}{010}{嗯。可以我希望安全负责人有时间回答我的问题？}

#Node010
### {1001}{}{Hello there! What do you want?}
{1001}{}{你好！你想要什么？}
### {1002}{}{Come on, get it on. What do you want to know?}
{1002}{}{来吧，穿上它。你想知道什么？}
### {1003}{}{Mark said that you are his successor now. And I think it is a wise choice. You can count on me.}
{1003}{}{马克说你现在是他的继任者。我认为这是一个明智的选择。你可以相信我。}
### {1004}{}{Boss? Did you want something?}
{1004}{}{老板你想要什么吗？}
### {101}{013}{What can you say about this place?}
{101}{013}{关于这个地方你能说些什么？}
### {102}{014}{Tell me about locals.}
{102}{014}{告诉我当地人的情况。}
### {103}{035}{You must be thinking that you are a great joker.}
{103}{035}{你一定认为你是个爱开玩笑的人。}
### {104}{045}{I've heard that Mark is going to put Sam in charge of NWO. What do you think about it?}
{104}{045}{我听说马克要让萨姆负责NWO。你怎么看？}
### {105}{999}{Nice talking to you, but I need to go.}
{105}{999}{很高兴和你交谈，但我得走了。}

#Node011
### {110}{}{[he hesitantly stares at you, waiting for your answer.]}
{110}{}{[他犹豫地盯着你，等着你的回答。]}
### {111}{012}{I would be VERY grateful if you saved your hilarious jokes for your mom. And if you could talk not like a five-year-old child, that would also be great. I'm }
{111}{012}{如果你能把你的搞笑笑话留给你妈妈，我将不胜感激。如果你能不像一个五岁的孩子那样说话，那也太好了。我是}
### {112}{012}{.}
{112}{012}{。}
### {113}{006}{Okay, I'll introduce myself first. I'm }
{113}{006}{好的，我先自我介绍。我是}
### {114}{006}{.}
{114}{006}{。}

#Node012
### {120}{}{You wouldn't make it here without jokes. Don't listen, if you don't like it. I'm Burns, the head of security.}
{120}{}{如果没有笑话，你是不会来这里的。如果你不喜欢，就别听。我是伯恩斯，安全部门负责人。}
### {121}{010}{I'm new here. I'd like to ask some questions.}
{121}{010}{我是新来的。我想问一些问题。}

#Node013
### {136}{}{[Burns points below his belt] I can tell you about THIS place for sure, haha!! Okay, this town is called NWO, short for New World Order. We live peacefully and quietly, like in Lavash's ass. And I'm responsible for it to continue to be that way.}
{136}{}{我可以肯定地告诉你这个地方，哈哈！！好吧，这个小镇叫NWO，是新世界秩序的缩写。我们平静地生活着，就像在拉瓦什的屁股里一样。我有责任继续这样下去。}
### {130}{}{I won't tell you anything new, boss. If only you are not interested in local catfights.}
{130}{}{老板，我不会告诉你什么新鲜事。如果你对当地的猫打架不感兴趣就好了。}
### {131}{014}{Tell me about NWO's locals.}
{131}{014}{告诉我NWO的当地人。}
### {132}{022}{What can I do around here?}
{132}{022}{我在这附近能做什么？}
### {133}{010}{Another question.}
{133}{010}{另一个问题。}
### {134}{999}{Good. You know, I need to go now.}
{134}{999}{好的你知道，我现在需要走了。}

#Node014
### {140}{}{I don't like to brag about others, except the ones who got caught with his pants down between the legs of some beauty, hahaha!! I'm Burns, I work for NWO's mayor. Now it's Mark, so for now - I work for him.}
{140}{}{我不喜欢吹嘘别人，除了那些被美女夹在两腿之间的人，哈哈哈！！我是伯恩斯，我为西北大西洋区的市长工作。现在是马克，所以现在-我为他工作。}
### {141}{015}{"For now"? Why, are you leaving?}
{141}{015}{“暂时”？为什么，你要走吗？}
### {142}{016}{Tell me about Mark.}
{142}{016}{告诉我关于马克的事。}
### {143}{019}{Tell me more about yourself.}
{143}{019}{告诉我更多关于你自己的信息。}
### {144}{010}{Another question then.}
{144}{010}{那又是一个问题。}
### {145}{}{I don't like to brag about others, except the ones who got caught with his pants down between the legs of some beauty, hahaha!! Actually, I don't have much to say. You'd better talk with everyone personally.}
{145}{}{我不喜欢吹嘘别人，除了那些被美女夹在两腿之间的人，哈哈哈！！事实上，我没什么好说的。你最好亲自和大家谈谈。}
### {146}{016}{Tell me about Mark.}
{146}{016}{告诉我关于马克的事。}
### {147}{019}{Tell me more about yourself.}
{147}{019}{告诉我更多关于你自己的信息。}
### {148}{010}{Another question then.}
{148}{010}{那又是一个问题。}

#Node015
### {150}{}{Hah, I'm leaving this place only when I'm dead, protecting Mayor! The thing is, his health is shittier than shit. His ass is one cheek in the grave, and soon there will be a new Leader in NWO. And I will protect the new Mayor until I die.}
{150}{}{哈，我只有死了才会离开这里，保护市长！问题是，他的健康状况比糟糕还要糟糕。他的屁股就在坟墓里，很快NWO就会有一位新的领导人。我会保护新市长直到我死。}
### {151}{016}{I want to learn about Mark.}
{151}{016}{我想了解马克。}
### {152}{019}{Can you tell me about yourself?}
{152}{019}{你能告诉我你自己的情况吗？}
### {153}{010}{I want to ask something else.}
{153}{010}{我想问别的问题。}

#Node016
### {1601}{}{Mark is our Mayor, I respect him the most. He is the hell of a man! He handles everything, without him, it would already be nothing here! But now he is sick and, unfortunately, soon will be counting the worms. And who knows what will NWO become after it!}
{1601}{}{马克是我们的市长，我最尊敬他。他真是个混蛋！他处理一切，没有他，这里就什么都不是了！但现在他病了，不幸的是，很快就会数虫子了。谁知道NWO之后会变成什么样子呢！}
### {1602}{}{Mark is our Mayor, I respect him the most. He is the hell of a man! Too bad he's leaving his post... But such times. I hope that you, boss, will be as good as him.}
{1602}{}{马克是我们的市长，我最尊敬他。他真是个混蛋！可惜他要离职了。。。但是这样的时代。我希望你，老板，能像他一样优秀。}
### {1603}{}{Mark is our Mayor, I respect him the most. He is the hell of a man! Too bad he's leaving his post... But such times. I hope that new management won't screw things here with their rotten brains.}
{1603}{}{马克是我们的市长，我最尊敬他。他真是个混蛋！可惜他要离职了。。。但是这样的时代。我希望新的管理层不要用他们腐朽的头脑把事情搞砸。}
### {161}{017}{Who could become a new Mayor?}
{161}{017}{谁能成为新市长？}
### {162}{018}{What would happen with NWO if there's no Mayor, or if there's someone unsuited for the position?}
{162}{018}{如果没有市长，或者有人不适合担任这个职位，NWO会发生什么？}
### {163}{010}{I want to ask something else.}
{163}{010}{我想问别的问题。}

#Node017
### {1701}{}{After Mark dies, his son Daniel should succeed him. But everybody says that Daniel is a wussie and a total moron, so I suppose there are some options... Listen, I was thinking that you could help me sort this shit out. I will protect a new Mayor in any case, whoever he would be. But every person has weaknesses, enemies, and such. So, I need to prepare. Try to find out who will succeed Mark. Talk to Mark himself, and ask others around here, what do they think about it. Will you do this for me?}
{1701}{}{马克死后，他的儿子但以理应该继承他的王位。但每个人都说丹尼尔是个胆小鬼和十足的白痴，所以我想还有一些选择。。。听着，我在想你可以帮我解决这个问题。无论如何，我都会保护新市长，不管他是谁。但每个人都有弱点、敌人等等。所以，我需要做好准备。试着找出谁将接替马克。和马克自己谈谈，问问周围的人，他们对此有什么看法。你会为我这样做吗？}
### {1702}{}{Shit, that's what I want to know! I'd like you to talk to people and figure it out. Would you?}
{1702}{}{妈的，这就是我想知道的！我希望你能与人们交谈并找出答案。你愿意吗？}
### {171}{010}{Probably not, I have a lot of things to do. I'd better ask a question.}
{171}{010}{可能不会，我有很多事情要做。我最好问个问题。}
### {172}{010}{Sure. I'll talk to Mark about his successor. And now - to other questions.}
{172}{010}{当然我将和马克谈谈他的继任者。现在再谈其他问题。}

#Node018
### {180}{}{NWO will quickly descend into the depths of the same ass from which Mark tried to pull it out the most of his life! The town will drown in Lavash shit and dissolve in it, like a piss in the river.}
{180}{}{NWO将迅速潜入马克一生中试图将其拉出的同一只屁股的深处！这个小镇会淹没在熔岩的粪便中，然后溶解在其中，就像河里的尿一样。}
### {181}{017}{Who would be better as Mayor and won't let that happen?}
{181}{017}{作为市长，谁会更好，不会让这种情况发生？}
### {182}{010}{Sounds like quite a grim future. I'd like to ask another question.}
{182}{010}{听起来是一个相当严峻的未来。我想再问一个问题。}

#Node019
### {195}{}{[Burns's smile covers most of his face] What can I say! I'm the head of security, always ready to kick ass for a crime or just because, hahaha!! People call me Burns, it's my moniker. I will tear off the balls of anyone who dares to threaten Mayor, and I'm ready to die protecting his ass!}
{195}{}{[伯恩斯的笑容遮住了大半张脸]我能说什么呢！我是安全主管，随时准备为犯罪或仅仅因为，哈哈哈！！人们叫我伯恩斯，这是我的绰号。我会撕掉任何胆敢威胁市长的人的蛋蛋，我准备为保护他的屁股而死！}
### {190}{}{[Burns's smile covers most of his face] What can I say! Despite being the head of security, I'm always ready to kick ass for a crime or just because, hahaha!! If you didn't hear, people call me Burns. It's my moniker. I will tear off the balls of anyone who dares to threaten you, and I'm ready to die protecting your ass!}
{190}{}{[伯恩斯的笑容遮住了大半张脸]我能说什么呢！尽管我是安全部门的负责人，但我总是准备为犯罪或仅仅因为，哈哈哈！！如果你没听到，人们都叫我伯恩斯。这是我的绰号。我会撕掉任何胆敢威胁你的人的蛋蛋，我准备为保护你的屁股而死！}
### {191}{020}{Are you really willing to do anything for Mayor?}
{191}{020}{你真的愿意为市长做点什么吗？}
### {192}{021}{How did you get your moniker?}
{192}{021}{你的绰号是怎么来的？}
### {193}{023}{How did you become the head of security?}
{193}{023}{你是如何成为安全部门负责人的？}
### {194}{010}{Okay, let me ask another question.}
{194}{010}{好吧，让我再问一个问题。}

#Node020
### {200}{}{[Burns becomes serious. His eyes glow with steel] I'll tear a new one to anyone who plans to hurt Mayor. I'll cover him from bullets with my chest if I have to. And let me be buried together with previous Mayors, as the most loyal to the very end. Even if everyone in the Radius wage war on us, I'll be in the front row, murdering these bastards, until the last one of them dies! Let everyone know - Burns won't be hiding like some lousy rat!}
{200}{}{[伯恩斯变得严肃起来。他的眼睛里闪烁着钢铁般的光芒]我会给任何计划伤害市长的人撕一个新的。如果必须的话，我会用我的胸部保护他免受子弹的伤害。让我和前几任市长一起埋葬，作为最忠诚的市长。即使Radius的每个人都对我们发动战争，我也会站在前排，谋杀这些混蛋，直到他们中的最后一个死去！让每个人都知道——伯恩斯不会像一只糟糕的老鼠一样躲起来！}
### {201}{021}{Burns, why do people call you that?}
{201}{021}{伯恩斯，为什么人们这么叫你？}
### {202}{010}{I see. Let me ask another question.}
{202}{010}{我明白了。让我再问一个问题。}

#Node021
### {210}{}{[he twirls his mustache, pondering about the past] Man, it was so long time ago. I wasn't even the head of security back then. With some other guys, I had been walking around the Radius, doing all kinds of shit. Nothing special. And I had these beautiful sideburns, completed with an amazing mustache. Not one dick in the whole Radius had something like this! And one day, the smartest asshole around my fellas decided to take all the loot we had for himself. And planted a bomb into our campfire. I just went to take a piss when it detonated, so I guess I was lucky - all I got was a little scorched face and completely burned mustache and sideburns. I chased the bastard, unloading all my gun into his back. And I've been walking around with burned sideburns until they grew back. So, people started calling me sideburns, then it was shortened for just Burns. That's it.}
{210}{}{[他捻着胡子，沉思着过去]伙计，那是很久以前的事了。当时我甚至不是安全部门的负责人。和其他人一起，我一直在Radius周围散步，做各种各样的事情。没什么特别的。我留着美丽的鬓角，留着令人惊叹的小胡子。整个Radius没有一个老二有这样的事！有一天，我身边最聪明的混蛋决定把我们所有的战利品都据为己有。在我们的营火里放了一枚炸弹。爆炸时我只是去撒尿，所以我想我很幸运——我得到的只是一张有点烧焦的脸，胡子和鬓角完全烧焦了。我追着那个混蛋，把所有的枪都倒在他的背上。我一直带着烧焦的鬓角四处走动，直到它们长回来。所以，人们开始叫我鬓角，然后它被缩短为伯恩斯。就是这样。}
### {211}{010}{What a story. I have other questions.}
{211}{010}{真是个故事。我还有其他问题。}

#Node022
### {220}{}{[Burns smiles and, without any threat in his voice, answers] If you do problems, you could end up catching a bullet with your forehead. And If you behave, just like Lavash after copulation, then you'll be safe. People even could like you here. You don't look like Lavash herder or factory worker type, so you probably won't be interested in this boring and shitty kind of job. Maybe some of the folks would ask you to do something they are afraid to do themselves.}
{220}{}{[伯恩斯微笑着，声音中没有任何威胁，回答道]如果你遇到问题，你的前额可能会中弹。如果你表现得像交配后的熔岩一样，那么你就安全了。人们甚至可以喜欢你在这里。你看起来不像熔岩牧民或工厂工人，所以你可能不会对这种无聊而糟糕的工作感兴趣。也许有些人会要求你做一些他们自己害怕做的事情。}
### {221}{010}{I won't cause problems then. Another question. }
{221}{010}{那我就不会惹麻烦了。另一个问题。}
### {222}{998}{Now you're getting a bullet in your head!}
{222}{998}{现在你的脑袋中了一颗子弹！}
### {223}{999}{Okay, I'll go talk to others about work.}
{223}{999}{好吧，我去和其他人谈谈工作。}

#Node023
### {230}{}{[Burns flexes his muscles] Very fast and easy, haha!! When I arrived here, there was another head of security. A wuss and sucker. He was shot down in front of me by some dickhead asshole, from this exact machinegun. That asshole's next move was to send the Mayor to heaven's ass, but I interrupted his plan by beating the shit out of him with my bare hands. Took the gun as a souvenir. And that's when Mayor offered me to work for him. Of course, there were other candidates for my position, but none of them could kick my ass. So there.}
{230}{}{[伯恩斯展示了他的肌肉]非常快和容易，哈哈！！当我到达这里时，还有另一位安全负责人。一个胆小鬼。他在我面前被一个混蛋用这把机关枪击落了。那个混蛋的下一步行动是把市长送上天堂，但我徒手把他打得落花流水，打断了他的计划。把枪当作纪念品。就在那时，市长让我为他工作。当然，我的职位还有其他候选人，但没有一个能踢我的屁股。}
### {231}{025}{You don't look too strong, you know.}
{231}{025}{你看起来不太强壮，你知道的。}
### {232}{024}{Yeah, I see. You look pretty strong. I wouldn't like to squabble with you.}
{232}{024}{是的，我明白了。你看起来很强壮。我不想和你吵架。}
### {233}{010}{I see. Let me ask something else. }
{233}{010}{我明白了。让我再问一个问题。}

#Node024
### {240}{}{[Burns smiles even more. He is definitely flattered] Yes, I am!! But don't be afraid, I won't pick fights with you. I don't beat up the weaker ones, haha!!}
{240}{}{[伯恩斯笑得更厉害了。他肯定受宠若惊]是的，我是！！但别害怕，我不会和你打架的。我不打较弱的，哈哈！！}
### {241}{025}{Although, scratch that, you actually don't look that strong.}
{241}{025}{不过，请注意，实际上你看起来并没有那么强壮。}
### {242}{010}{Yeah, no fights then. I want to ask something else.}
{242}{010}{是的，那就不打架了。我想问别的问题。}

#Node025
### {250}{}{[he instantly gets fierce] WHAT??? You... Fucking milksop!! I will tear your ass into pieces with my one hand!! One punch from me will make you lay down!! Didn't have your face beaten up lately?! }
{250}{}{[他立刻变得凶狠]什么？？？你该死的奶昔！！我会用我的一只手把你的屁股撕成碎片！！我一拳就能让你躺下！！你最近没被打过脸吗？！}
### {251}{026}{One punch will make me lay down? I really doubt that. Wanna bet?}
{251}{026}{一拳就能让我躺下？我真的对此表示怀疑。想打赌吗？}
### {252}{998}{You are making me sick already. It is I who is going to tear your ass, right now!}
{252}{998}{你已经让我恶心了。现在是我要撕裂你的屁股！}
### {253}{010}{Come on, calm down. It was a joke. I'd better ask a question.}
{253}{010}{来吧，冷静下来。这是个笑话。我最好问个问题。}
### {254}{999}{Come on, calm down. It was a joke. I'd better go wait for you to calm down. I don't want to quarrel with you.}
{254}{999}{来吧，冷静下来。这是个笑话。我最好去等你冷静下来。我不想和你吵架。}

#Node026
### {260}{}{[His eyes are flashing with excitement] A bet? Sure! Don't forget to put down something soft, so you could sleep comfortably when you fall! Don't worry, I'll punch carefully, so I wouldn't break something. Handle one blow - and you win, drop down - and I win. Are you in, or your knees are trembling too much? Haha!!}
{260}{}{[他的眼睛兴奋地闪烁]打赌？当然别忘了放下一些柔软的东西，这样你跌倒时就能睡得舒服！别担心，我会小心地打，这样我就不会打碎什么东西。只需一击，你就赢了，倒下，我就赢了。你是在里面，还是你的膝盖抖得太厉害了？哈哈！！}
### {261}{027}{Let's do it! What we are going to bet with?}
{261}{027}{让我们来做吧！我们要赌什么？}
### {262}{010}{Nah, I don't really feel like getting punched in the face. I'd like to ask something.}
{262}{010}{不，我真的不想被打在脸上。我想问个问题。}
### {263}{999}{Uh, no, thank you. I'd better go.}
{263}{999}{不用了，谢谢。我最好去。}

#Node027
### {270}{}{Whatever. I don't care. Let's bet a noogie!}
{270}{}{无论什么我不在乎。我们赌一个套子吧！}
### {271}{028}{Hah! Okay! Go!}
{271}{028}{哈哈！可以去}
### {272}{010}{To get my face punched for a noogie? No way in hell. I better ask something.}
{272}{010}{为了一个套索而打我的脸？地狱里没有路。我最好问问。}

#Node028
### {280}{}{Hahaha! Here we go!!}
{280}{}{哈哈哈！我们来了！！}
### {281}{999}{[brace yourself for a punch]}
{281}{999}{[准备好挨一拳]}

#Node029
### {290}{}{[You barely managed to keep yourself on your feet, your head is buzzing - but you are standing. Burns looks at you with respect] Hah, aren't you a tough one? Well, looks like I lost. Give me a noogie, I deserved that.}
{290}{}{[你几乎没能站起来，你的头嗡嗡作响，但你站着。伯恩斯尊重地看着你]哈，你不是个坚强的人吗？看起来我输了。给我一个套索，这是我应得的。}
### {291}{032}{[You concentrate all of your strength and give Burns a noogie]}
{291}{032}{[你集中所有的力量给伯恩斯一个套索]}

#Node030
### {300}{}{[You fall on your back after a powerful blow. You see flashes, you almost pass out. Burns hoarsely laughs] Hahaha!! I told you that you will fall, like a pushed Lavash!! Now - here's your noogie!}
{300}{}{【你被重重一击后倒在地上。你看到闪光，差点晕过去。伯恩斯嘶哑地笑了起来】哈哈哈！！我告诉过你，你会摔倒的，就像推过的熔岩！！现在，这是你的套索！}
### {301}{033}{[You concentrate all of your remaining strength to take a noogie]}
{301}{033}{[你把剩下的力气都集中起来玩套索游戏]}

#Node031
### {310}{}{[You fall down and pass out. You come to your senses in a few minutes, Burns looks concerned] Phew, it's good that you are alright. I began to think that you're done for. Okay, no noogie for you, I think you had enough.}
{310}{}{[你摔倒了，昏倒了。几分钟后你就恢复了理智，Burns看起来很担心]Phew，还好你没事。我开始觉得你受够了。好吧，没有套索给你，我想你受够了。}
### {311}{034}{[You concentrate all of your strength to just get up]}
{311}{034}{[你集中所有的力量站起来]}

#Node032
### {320}{}{[Burns doesn't react at all. Looks like your finger hurts more than he is] That's it? Hahaha!!! Okay, it was great.}
{320}{}{[伯恩斯一点反应都没有。看起来你的手指比他更疼]就是这样？哈哈哈！！！好吧，太棒了。}
### {321}{010}{Yeah, just wonderful. I want to ask something else.}
{321}{010}{是的，太棒了。我想问别的问题。}
### {322}{999}{Agreed, that was great. I need to come to my senses, let's talk later.}
{322}{999}{同意，太棒了。我需要恢复理智，我们稍后再谈。}

#Node033
### {330}{}{[His noogie almost knocks you over. Burns hoarsely laughs] That's it? Hahaha!!! Okay, it was great.}
{330}{}{[他的套索差点把你撞倒。伯恩斯嘶哑地笑着]就这样？哈哈哈！！！好吧，太棒了。}
### {331}{010}{Yeah, just wonderful. I want to ask something else.}
{331}{010}{是的，太棒了。我想问别的问题。}
### {332}{999}{Agreed, that was great. I need to come to my senses, let's talk later.}
{332}{999}{同意，太棒了。我需要恢复理智，我们稍后再谈。}

#Node034
### {340}{}{[Burns helps you to get up. Then he hoarsely laughs] Hahaha, you almost died!! Still, that was great.}
{340}{}{[伯恩斯扶你站起来，然后沙哑地笑了起来]哈哈哈，你差点死了！！尽管如此，那还是很棒。}
### {341}{010}{Yeah, just wonderful. I want to ask something else.}
{341}{010}{是的，太棒了。我想问别的问题。}
### {342}{999}{Agreed, that was great. I need to come to my senses, let's talk later.}
{342}{999}{同意，太棒了。我需要恢复理智，我们稍后再谈。}

#Node035
### {350}{}{[he looks offended] That's how it is! I'm the funniest guy here! Not like that boring shits around. I can make a joke about anything!!}
{350}{}{[他看起来很生气]事情就是这样！我是这里最有趣的人！不像那些无聊的废话。我可以拿任何事开玩笑！！}
### {351}{036}{I bet you can't. What if I give you a word? Would you make a joke about it? Maybe, a rhyme?}
{351}{036}{我打赌你不能。我给你一句话怎么样？你会开个玩笑吗？也许，押韵？}
### {352}{010}{Yes, looks like you are the funniest guy. I want to ask something else.}
{352}{010}{是的，看起来你是最有趣的人。我想问别的问题。}

#Node036
### {360}{}{[he starts shouting] Yeah! Come on! Give me a word and I'll rhyme so hard that you'll tear your ass from laughing! Let's bet on a noogie!}
{360}{}{[他开始大喊]是的！来吧给我一个词，我就会押韵得让你笑得前仰后合！让我们在套索上下注吧！}
### {361}{037}{Let's do it! I'll give you a word...}
{361}{037}{让我们来做吧！我给你一句话。。。}
### {362}{010}{Nah, I don't want a noogie. Let me ask something else.}
{362}{010}{不，我不想要套索。让我再问一个问题。}


#Node037
### {370}{}{[Burns is rubbing his hands, awaiting for your word]}
{370}{}{[伯恩斯在搓手，等着你的话]}
### {371}{038}{Rifle}
{371}{038}{步枪}
### {372}{042}{Lavash}
{372}{042}{熔岩}
### {373}{039}{Triangle}
{373}{039}{三角形}
### {374}{043}{Ass}
{374}{043}{助理}
### {375}{044}{Transcendence}
{375}{044}{超越}
### {376}{040}{Battery}
{376}{040}{电池}
### {377}{041}{Bottle}
{377}{041}{瓶子}

#Node038
### {380}{}{Rifle, rifle, shooting is delightful! Hahaha!! Here's a noogie!}
{380}{}{步枪，步枪，射击很愉快！哈哈哈！！这是一个套索！}
### {381}{033}{Uhhh...}
{381}{033}{啊。。。}

#Node039
### {390}{}{Triangle, triangle, my dick is phalangal! Hahaha!! Here's a noogie!}
{390}{}{三角，三角，我的老二是指骨！哈哈哈！！这是一个套索！}
### {391}{033}{Uhhh...}
{391}{033}{啊。。。}

#Node040
### {400}{}{Battery, battery, making me flattery! Hahaha!! Here's a noogie!}
{400}{}{炮台，炮台，让我拍马屁！哈哈哈！！这是一个套索！}
### {401}{033}{Uhhh...}
{401}{033}{啊。。。}

#Node041
### {410}{}{Bottle with a model, ended in a brothel! Hahaha!! Here's a noogie!}
{410}{}{瓶子里有一个模特，最后进了妓院！哈哈哈！！这是一个套索！}
### {411}{033}{Uhhh...}
{411}{033}{啊。。。}

#Node042
### {420}{}{Lavash, oh gosh, I'm not going to wash it! Hahaha!! Here's a noogie!}
{420}{}{熔岩，哦，天哪，我不洗了！哈哈哈！！这是一个套索！}
### {421}{033}{Uhhh...}
{421}{033}{啊。。。}

#Node043
### {430}{}{[Burns is confused] Uhhh... Damn, ass is fine as it is! I don't know what to say...}
{430}{}{[伯恩斯很困惑]啊。。。妈的，屁股就这么好！我不知道该说什么。。。}
### {431}{032}{Hah, so you lose! Here's a noogie!}
{431}{032}{哈，你输了！这是一个套索！}

#Node044
### {440}{}{[Burns is confused] Uhhh... What? What the hell is this shit? I don't know what to say...}
{440}{}{[伯恩斯很困惑]啊。。。什么这是什么鬼东西？我不知道该说什么。。。}
### {441}{032}{Hah, so you lose! Here's a noogie!}
{441}{032}{哈，你输了！这是一个套索！}

#Node045
### {450}{}{[Burns starts twirling his mustache] Hmm, Mark is a really smart-ass Mayor. I think good old Sam is the best possible option, even if he stinks like Lavash ass. Sam is an experienced leader, he started it all here. Mark, you son of a bitch, that is a great idea!}
{450}{}{[伯恩斯开始转动他的胡子]嗯，马克是一个非常聪明的市长。我认为老好人山姆是最好的选择，即使他臭得像熔岩屁股。山姆是一个经验丰富的领导者，他在这里开始了这一切。马克，你这个婊子养的，真是个好主意！}
### {451}{999}{I see you don't mind. Okay, I need to go, bye.}
{451}{999}{我看你不介意。好的，我得走了，再见。}
