##############################
#???????: ???
#???: ???????
#??????? ????????: ??? ???????????? ???
#???? ????????: 05.08.2014
##############################
#??? ???? "????? 2207"
#????? "Rainman" ????????
##############################
#
#???????? ????????
#
# ?? ??????????
### {1}{}{You see a young man.}
{1}{}{你看到一个年轻人。}
### {2}{}{All his look says that he's the boss here.}
{2}{}{他所有的表情都表明他是这里的老板。}
#
# ????? ??????????
### {3}{}{You see Daniel.}
{3}{}{你看到丹尼尔了。}
### {4}{}{As usual, he looks just like a young rooster in a henhouse.}
{4}{}{和往常一样，他看起来就像鸡舍里的一只小公鸡。}
#
#????? ?????????? ??????
#
### {10}{}{[Before you is a man in his twenties. His clothes are covered with rivets, chains and pieces of metal] Hey there! }
{10}{}{[你面前是一个二十多岁的男人。他的衣服上布满了铆钉、链条和金属片]嘿！}
### {11}{002}{Hello. I came here recently, I'm just looking around the town.}
{11}{002}{你好我最近来这里，只是在城里四处看看。}

### {20}{}{[he gives you a wide smile] Hah, I'm going to tell you something about this town. It should be blown the hell up, to build a new one in its place! I'm Daniel, Mayor's son. After my dad kicks the bucket, I'll be in charge. And I'm going to turn this place upside down!}
{20}{}{[他笑了笑]哈，我要告诉你一些关于这个小镇的事情。它应该被炸得天翻地覆，在它的位置上建造一个新的！我是丹尼尔，市长的儿子。等我爸爸出尔反尔后，我来负责。我要把这个地方搞得天翻地覆！}
### {21}{010}{Glad to meet you. I'd like to ask some questions.}
{21}{010}{很高兴见到你。我想问一些问题。}
### {22}{999}{Glad to meet you, but I need to go.}
{22}{999}{很高兴见到你，但我得走了。}

### {1000}{}{Hello again, wanna talk?}
{1000}{}{又是你好，想谈谈吗？}
### {1001}{}{You are talking to the future Leader of NWO, so show me respect! Haha, just kidding! You helped me greatly to become Mayor! Did you want something?}
{1001}{}{你正在和未来的NWO领导人交谈，请尊重我！哈哈，开玩笑！你对我成为市长帮助很大！你想要什么吗？}
### {1002}{}{And here's our new Mayor. How cunningly you took my place. I can still give you some advice about what to do with the town.}
{1002}{}{这是我们的新市长。你多么狡猾地取代了我的位置。我仍然可以给你一些关于如何处理这个城镇的建议。}
### {1003}{}{Okay!}
{1003}{}{可以}
### {101}{011}{What can you tell me about the town?}
{101}{011}{你能告诉我关于这个小镇的什么？}
### {102}{030}{It's you who is going to be a new Mayor?}
{102}{030}{是你要当新市长吗？}
### {103}{024}{Tell me about your father.}
{103}{024}{告诉我你父亲的情况。}
### {104}{029}{What do you do here?}
{104}{029}{你在这里做什么？}
### {105}{036}{Yes, I'm the new Mayor. And I'd like you to keep your gimmicks to yourself.}
{105}{036}{是的，我是新市长。我希望你把你的噱头留给自己。}
### {106}{999}{Let's talk later, I need to go.}
{106}{999}{我们稍后再谈，我得走了。}

### {110}{}{[Daniel spits on the ground] This place is a dirty pile of heap. Everything is wrong here. And something needs to be done about it! But everyone's afraid to act because they are afraid of my pops. And I'm the only one who doesn't hesitate to openly say that he is wrong. Also, Arsene and Dan, his father, agrees with me.  }
{110}{}{[但以理在地上吐唾沫]这地方是一堆脏东西。这里一切都不对劲。需要做点什么！但每个人都害怕行动，因为他们害怕我的爸爸。我是唯一一个毫不犹豫地公开说他错了的人。此外，阿森和他的父亲丹也同意我的观点。}
### {111}{012}{How do you want to change the town?}
{111}{012}{你想怎样改变这个城市？}
### {112}{013}{Tell me more about Arsene.}
{112}{013}{告诉我更多关于阿森的信息。}
### {113}{019}{I'd like to learn about Arsene's father.}
{113}{019}{我想了解一下阿森的父亲。}
### {114}{}{[Daniel spits on the ground] This town is a dirty pile of heap. I could lead it to a great future, but then you appeared. Let's see what you can do.}
{114}{}{[但以理在地上吐唾沫]这个城市是一堆肮脏的垃圾。我本可以带领它走向美好的未来，但后来你出现了。让我们看看你能做些什么。}
### {115}{010}{Yeah, we'll see. And now - another question.}
{115}{010}{是的，我们拭目以待。现在——另一个问题。}

### {120}{}{[you see a fire in his eyes] I will knock down half of the local buildings to build new ones! I'll chase all the shits out of town, so only the cool guys would stay! Arsene is going to help, Dan too. And mom. Together we are strong!}
{120}{}{[你从他的眼睛里看到了火]我会推倒一半的当地建筑来建造新的！我会把所有的混蛋都赶出城，所以只有酷家伙才会留下来！阿森会帮忙的，丹也是。还有妈妈。我们在一起是强大的！}
### {121}{013}{Can you tell me about Arsene?}
{121}{013}{你能告诉我关于阿森的事吗？}
### {122}{019}{Tell me about Dan.}
{122}{019}{告诉我关于丹的事。}
### {123}{020}{I'd like to hear about your mom.}
{123}{020}{我想听听你妈妈的情况。}
### {124}{021}{How are you going to build new buildings?}
{124}{021}{你打算如何建造新建筑？}
### {125}{022}{Who exactly do you want to chase out of town?}
{125}{022}{你到底想把谁赶出城外？}

### {130}{}{[Daniel starts proudly talking] Arsene is my best bud! He is the smartest one around. We are doing big things together, all town knows about them.}
{130}{}{[丹尼尔开始骄傲地说]阿森是我最好的宝贝！他是周围最聪明的人。我们正在一起做大事，镇上所有人都知道。}
### {131}{014}{Tell me details about your doings.}
{131}{014}{告诉我你的所作所为的细节。}
### {132}{010}{I want to ask another question.}
{132}{010}{我想再问一个问题。}

### {140}{}{[Daniel satisfyingly smiles] Big things, all the time - that's what we do. We rock the place! Last of our jobs include political stand-off resolvement, production rate improvement, and disaster prevention. What do you want to hear about?}
{140}{}{[丹尼尔满意地笑了笑]大事总是发生——这就是我们所做的。我们震撼了这个地方！我们最后的工作包括解决政治僵局、提高生产率和防灾。你想听些什么？}
### {141}{015}{Sounds serious. Tell me about political stand-off resolvement.}
{141}{015}{听起来很严肃。告诉我关于政治对峙的解决方案。}
### {142}{016}{I see you actually care about the town. Tell me about production rate improvement.}
{142}{016}{我看你真的很关心这个小镇。告诉我生产率提高的情况。}
### {143}{018}{You guys must be heroes. Tell me about disaster prevention.}
{143}{018}{你们一定是英雄。告诉我有关防灾的事。}
### {144}{010}{I want to ask something else.}
{144}{010}{我想问别的问题。}
### {145}{999}{Let's talk later. I need to go.}
{145}{999}{我们稍后再谈。我得走了。}

### {150}{}{There was some chick here, trying to get on Dan, saying that he knows nothing about politics. So, me and Arsene threw a rotten Lavash head into her window! Can you imagine that?! Now she keeps her mouth shut! You could say it's plus additional vote for us!}
{150}{}{这里有个小妞，试图讨好丹，说他对政治一无所知。所以，我和阿森把一个腐烂的熔岩头扔进了她的窗户！你能想象吗？！现在她守口如瓶！你可以说这是对我们的额外投票！}
### {151}{016}{Oh, I see. Tell me about production rate improvement.}
{151}{016}{哦，我明白了。告诉我生产率提高的情况。}
### {152}{018}{Okay. What about disaster prevention?}
{152}{018}{可以防灾怎么办？}
### {153}{010}{I want to ask other questions.}
{153}{010}{我想问其他问题。}

### {160}{}{A day before we secretly snuck into the canned meat factory. And Arsene poured a whole bucket of machine oil into the meat! Which lead to producing ten cans of meat more than usual! People didn't notice anything. The taste and smell got worse though, but they still eat it, no worries. }
{160}{}{前一天，我们偷偷溜进了罐头肉工厂。阿森把一整桶机油倒进肉里！这导致比平时多生产了十罐肉！人们什么也没注意到。虽然味道和气味都变差了，但他们仍然会吃，不用担心。}
### {161}{017}{You didn't happen to pour something like this into the Lavash food, did you?}
{161}{017}{你没有把这样的东西倒进熔岩食物里，是吗？}
### {162}{015}{Right. Tell me about political stand-off resolvement.}
{162}{015}{正确的告诉我关于政治对峙的解决方案。}
### {163}{018}{Tell me about disaster prevention.}
{163}{018}{告诉我有关防灾的事。}
### {164}{035}{[As in all conversation, you are carefully observing the one you speak to. You notice the silhouette of the oil bottle in his inner pocket] You do smell some machine oil now, you know that? Here's the bottle sticking out. Do you want to pour it somewhere again? }
{164}{035}{[在所有的谈话中，你都在仔细观察与你交谈的人。你注意到他内口袋里油瓶的轮廓]你现在确实闻到了一些机油的味道，你知道吗？瓶子伸出来了。你想再倒一次吗？}
### {165}{010}{Another question then.}
{165}{010}{那又是一个问题。}

### {170}{}{Of course! We added some oil into it too. There's more food this way!}
{170}{}{当然我们也往里面加了一些油。这边有更多的食物！}
### {171}{010}{I want to ask something else.}
{171}{010}{我想问别的问题。}
### {172}{999}{I see. I'll go do my things, see you.}
{172}{999}{我明白了。我会去做我的事情，再见。}

### {180}{}{One asshole wanted to get two of his friends into NWO, so they agreed to meet at dawn, on the outskirts of the town. Can you imagine three assholes in the NWO? It is a disaster! I can barely tolerate one. So, we boarded up his doors and windows at night, he didn't make it to his friends, and they left. That's it!}
{180}{}{一个混蛋想把他的两个朋友带到NWO，所以他们同意在黎明时分在城郊见面。你能想象NWO里有三个混蛋吗？这是一场灾难！我几乎无法忍受。所以，我们晚上用木板封住了他的门窗，他没能去见他的朋友，他们就走了。就是这样！}
### {181}{015}{Tell me about political stand-off resolvement.}
{181}{015}{告诉我关于政治对峙的解决方案。}
### {182}{016}{I want to hear about production rate improvement.}
{182}{016}{我想听听生产率提高的情况。}
### {183}{010}{I'll ask something else.}
{183}{010}{我会问别的问题。}

### {190}{}{Dan is Arsene's father. A wise man! Knows politics like nobody else. He talks the right things, me and Arsene like to listen to him. Sometimes I don't quite get what Dan tries to tell us, but it is definitely important.}
{190}{}{丹是阿森的父亲。一个聪明的人！对政治的了解无人能及。他说的是对的，我和阿尔塞纳都喜欢听他的。有时我不太明白丹想告诉我们什么，但这绝对很重要。}
### {191}{012}{I see. Tell me, what do you want to do with a town?}
{191}{012}{我明白了。告诉我，你想对一个城镇做什么？}
### {192}{010}{I'll ask something else.}
{192}{010}{我会问别的问题。}
### {193}{999}{I see. I need to go.}
{193}{999}{我明白了。我得走了。}

### {200}{}{My mom helps me greatly. She keeps my pops away when I screw up. And she does all my stuff at home, so I could have time to do more serious things.}
{200}{}{我妈妈帮了我很大的忙。我搞砸了她就不理我。她在家里做我所有的事情，所以我可以有时间做更严肃的事情。}
### {201}{012}{I see. Tell me about your plans for a town.}
{201}{012}{我明白了。告诉我你的城镇计划。}
### {202}{010}{I'll ask something else.}
{202}{010}{我会问别的问题。}
### {203}{999}{I'll go talk to her. Bye.}
{203}{999}{我去和她谈谈。再见}

### {210}{}{[Daniel ponders] I have no idea. Somehow? What matters is that I know how to knock them down, and the locals will handle building new ones. What else they would do? }
{210}{}{[丹尼尔沉思]我不知道。以某种方式重要的是，我知道如何拆除它们，当地人会负责建造新的。他们还会做什么？}
### {211}{012}{Okay. So, what are your plans for the town?}
{211}{012}{可以那么，你对这个城市有什么计划？}
### {212}{010}{I'll ask something else.}
{212}{010}{我会问别的问题。}

### {2200}{}{I will throw all the shits out of the town, all of them! Though, I still need to decide, which ones. Ghouls for sure, I hate them! I'll drive them all off, except Sam.}
{2200}{}{我会把所有的垃圾都扔出去的，所有的！不过，我仍然需要决定，哪一个。食尸鬼当然，我讨厌他们！我会把他们都赶走，除了萨姆。}
### {2201}{}{I will throw all the shits out of the town, all of them! Especially Sam! This asshole took my place of Mayor!}
{2201}{}{我会把所有的垃圾都扔出去的，所有的！尤其是山姆！这个混蛋取代了我的市长职位！}
### {221}{023}{Why won't you drive off Sam?}
{221}{023}{你为什么不开车离开萨姆？}
### {222}{010}{Another question then.}
{222}{010}{那又是一个问题。}

### {230}{}{Because he is my grandpa. He can stay. Even if he smells a mile away... But the other ones will be chased away!}
{230}{}{因为他是我爷爷。他可以留下来。即使他闻起来有一英里远。。。但其他人会被赶走的！}
### {231}{012}{Okay. So, what did you want to do with the town?}
{231}{012}{可以那么，你想对这个小镇做什么？}
### {232}{010}{Another question, on different topics.}
{232}{010}{另一个问题，关于不同的主题。}
### {233}{999}{I see. I'll go talk to Sam. Bye.}
{233}{999}{我明白了。我去和萨姆谈谈。再见。}

### {2400}{}{My father is a Mayor, his name is Mark. I don't want to talk about him, we don't see each other much. I hang out with Arsene mostly, so I talk to his father more than with mine.}
{2400}{}{我父亲是市长，他的名字叫马克。我不想谈论他，我们很少见面。我大部分时间都和阿尔塞纳在一起，所以我和他的父亲交谈比和我的父亲交谈更多。}
### {2401}{}{My father is an ex-Mayor, his name is Mark. Also known as an old and dumb jerk, who trusted the leadership of this town to a complete stranger.}
{2401}{}{我父亲是前市长，他的名字叫马克。也被称为一个又老又笨的混蛋，他把这个小镇的领导权交给了一个完全陌生的人。}
### {2402}{}{My father is an ex-Mayor, his name is Mark. Also known as an old and dumb jerk, who trusted the leadership of this town to a half-dead rotten corpse.}
{2402}{}{我父亲是前市长，他的名字叫马克。也被称为一个又老又笨的混蛋，他把这个小镇的领导权托付给了一具半死的腐烂尸体。}
### {2403}{}{My father is a Mayor, his name is Mark. He is a bore and a fool. Although he is smart enough to put me in charge of NWO.}
{2403}{}{我父亲是市长，他的名字叫马克。他是个无聊的傻瓜。尽管他足够聪明，让我负责NWO。}
### {241}{025}{If he is a Mayor, you can learn many things from him.}
{241}{025}{如果他是市长，你可以从他身上学到很多东西。}
### {242}{010}{I'll ask something else.}
{242}{010}{我会问别的问题。}

### {250}{}{[Daniel cringes] Meh, pops doesn't know what he is doing. He lost it for a long time already. Look what swamp NWO has become! As Arsene says, "Dying Lavash won't give a good offspring". And I completely agree.}
{250}{}{[丹尼尔退缩了]哦，爸爸不知道他在做什么。他已经丢了很长时间了。看看NWO变成了什么沼泽！正如阿森所说，“死亡的熔岩不会产生好的后代”。我完全同意。}
### {251}{026}{What Arsene actually means by that?}
{251}{026}{阿森的话到底是什么意思？}
### {252}{027}{It's not so bad around here. You have food, water. Work.}
{252}{027}{这里还不错。你有食物和水。工作}
### {253}{010}{I want to ask something else.}
{253}{010}{我想问别的问题。}

### {260}{}{No idea. I'm not a philosopher.}
{260}{}{不知道。我不是哲学家。}
### {261}{010}{Um, okay. I'll ask something else.}
{261}{010}{嗯，好吧。我会问别的问题。}
### {262}{027}{But what is actually the problem? It's not so bad around here. You have food, water. Work.}
{262}{027}{但问题到底出在哪里呢？这里还不错。你有食物和水。工作}

### {270}{}{[Daniel starts actively gesturing. Metal things on his clothes start to chime a little] This is all bullshit! We are capable of doing much more! We could run the whole world if we want to!}
{270}{}{[丹尼尔开始积极地做手势。他衣服上的金属物开始有点叮当作响]这都是胡说八道！我们有能力做得更多！如果我们愿意，我们可以管理整个世界！}
### {271}{028}{And what needs to be done about it?}
{271}{028}{对此需要做些什么？}
### {272}{010}{I'll ask something else.}
{272}{010}{我会问别的问题。}

### {280}{}{[Daniel is waving hands even more energetically, metal things on his clothes are chiming loudly] Who the hell cares! First, we need to destroy everything old around here, and then to think about what to do next!}
{280}{}{[但以理更用力地挥着手，衣服上的金属物在大声鸣叫]谁在乎呢！首先，我们需要摧毁这里的一切旧东西，然后考虑下一步该怎么办！}
### {281}{010}{Okay, I'll ask something else.}
{281}{010}{好吧，我再问别的问题。}
### {282}{999}{I see. Okay, we'll talk later.}
{282}{999}{我明白了。好的，我们稍后再谈。}

### {290}{}{I have a lot of things to do in NWO! Arsene is helping. We are the coolest guys around. }
{290}{}{我在NWO有很多事情要做！阿尔塞纳在帮忙。我们是周围最酷的人。}
### {291}{013}{Tell me about Arsene.}
{291}{013}{告诉我关于阿森的事。}
### {292}{014}{What exactly are you doing with Arsene?}
{292}{014}{你到底在和阿森做什么？}
### {293}{010}{I'll ask something else.}
{293}{010}{我会问别的问题。}
### {294}{}{Working.}
{294}{}{工作}
### {295}{010}{Okay. Another question.}
{295}{010}{可以另一个问题。}

### {300}{}{Yeah, pops is pretty sick. And soon I'll inherit the Mayor's position. I feel sorry for the pops, of course, but he is doing his job pretty sick. Would be better if he put me into Mayor already, and got some rest.}
{300}{}{是的，爸爸病得很重。很快我将继承市长的职位。当然，我为爸爸们感到难过，但他工作得很糟糕。如果他已经让我当市长，休息一下会更好。}
### {301}{034}{I talked to your father. He doesn't want you to be the Mayor. But I think you are right, so just pretend you want to reform. When you become Mayor, you can do whatever you want.}
{301}{034}{我和你父亲谈过了。他不想让你当市长。但我认为你是对的，所以假装你想改革。当你成为市长后，你可以做任何你想做的事。}
### {302}{031}{I talked to your father. I think he is right. You should reform to become a better Mayor. If you do, you could carry the legacy of your father.}
{302}{031}{我和你父亲谈过了。我认为他是对的。你应该改革成为一个更好的市长。如果你这样做，你可以继承你父亲的遗产。}
### {303}{032}{I think you'll make a bad Mayor. I don't like your ideas.}
{303}{032}{我认为你会成为一个糟糕的市长。我不喜欢你的想法。}
### {304}{033}{You'll probably do good as a Mayor.}
{304}{033}{作为市长，你可能会做得很好。}
### {305}{010}{Let's talk about something else.}
{305}{010}{让我们谈谈其他事情。}
### {306}{999}{I'll go talk to your father. See you around.}
{306}{999}{我去和你爸爸谈谈。回头见。}

### {310}{}{You don't know shit about it! I won't change myself for this hole NWO turned into!}
{310}{}{你根本不知道！我不会为了NWO变成的这个洞而改变自己！}
### {311}{010}{Okay then... Maybe I don't understand it. Let me ask something else.}
{311}{010}{好吧。。。也许我不明白。让我问问别的。}
### {312}{999}{Suit yourself. I need to go.}
{312}{999}{随你便。我得走了。}

### {320}{}{You are just like my pops! You don't know shit! NWO is rotting because of people like you!}
{320}{}{你就像我爸爸一样！你根本不知道！NWO因为像你这样的人而腐烂！}
### {321}{010}{Okay then... Maybe I don't understand it. Let me ask something else.}
{321}{010}{好吧。。。也许我不明白。让我问问别的。}
### {322}{999}{Suit yourself. I need to go.}
{322}{999}{随你便。我得走了。}

### {330}{}{[Daniel jumps in excitement. The chiming of his metal sounds like a melody] That's it! You know, you're cool! You noticed straight away that this place needs changes!}
{330}{}{[丹尼尔兴奋地跳了起来。他的金属声听起来像旋律]就是这样！你知道，你很酷！你马上就注意到这个地方需要改变！}
### {331}{010}{Yes, a lot of changes. I'll ask something else.}
{331}{010}{是的，有很多变化。我会问别的问题。}
### {332}{999}{Of course! You start changing, and I need to finish something. See you.}
{332}{999}{当然你开始改变，我需要完成一些事情。再见}

### {340}{}{[Daniel blushes. but quickly calms down] Yes, pops can put me into trouble. Your idea might work... Okay, I'll pretend. And then I'll show them!!}
{340}{}{[丹尼尔脸红了。但很快平静下来]是的，爸爸会给我带来麻烦。你的想法可能会奏效。。。好吧，我假装。然后我给他们看！！}
### {341}{010}{Deal then. Another question.}
{341}{010}{那就交易吧。另一个问题。}
### {342}{999}{Agreed. I'll go talk to your father.}
{342}{999}{同意。我去和你爸爸谈谈。}

### {350}{}{[Daniel seems a little confused] Uh, I thought it's well-hidden in my pocket... Okay, here's a secret for you - me and Arsene decided to put some of the machine oil into Lavash food, to cut costs, so to say. They don't care, we have profit.}
{350}{}{[丹尼尔似乎有点困惑]嗯，我以为它藏在我的口袋里。。。好吧，这是你的一个秘密——我和阿森决定在熔岩食品中加入一些机油，可以说是为了降低成本。他们不在乎，我们有利润。}
### {351}{010}{I see. I want to ask something else.}
{351}{010}{我明白了。我想问别的问题。}
### {352}{999}{Understood. I need to go, see you later.}
{352}{999}{明白了。我得走了，回头见。}

### {360}{}{Meh. What?}
{360}{}{嗯。什么}
### {361}{037}{I'll think you'll do fine on a factory line. On the loading stage.}
{361}{037}{我认为你在生产线上会做得很好。在装载阶段。}
### {362}{040}{I'm watching you.}
{362}{040}{我在看着你。}
### {363}{999}{Nevermind. I'll go.}
{363}{999}{没关系。我去。}

### {370}{}{Wh- What? What did you say?}
{370}{}{什么？你说什么？}
### {371}{038}{I said that starting today you work in a factory. We are all equal here, so it doesn't look good when someone does nothing for the common good. }
{371}{038}{我说从今天开始你在工厂工作。我们在这里都是平等的，所以当有人不为共同利益做任何事情时，这看起来并不好。}

### {380}{}{But...}
{380}{}{但是}
### {381}{039}{I suggest you start working. Or the guards will be making you work every day. With their boots }
{381}{039}{我建议你开始工作。否则警卫会让你每天工作。穿着他们的靴子}

### {390}{}{[the boy gazes at you with an open mouth. He is, to put it mildly, bedazzled.]}
{390}{}{[那男孩张着嘴看着你。说得委婉一点，他是个迷。]}
### {391}{999}{Okay, I need to go. See you.}
{391}{999}{好的，我得走了。再见}

### {400}{}{So? Watch me. Watch me all you like.}
{400}{}{所以看着我，随便你怎么看着我。}
### {401}{999}{Sure. [end dialogue]}
{401}{999}{当然[结束对话]}
### {402}{037}{I think it would be more convenient for me to watch if you will take a job in a factory in a loading stage.}
{402}{037}{我想如果你愿意在工厂的装载阶段工作，我会更方便地观看。}

#????????? ????? ?? ??????
### {410}{}{Oh... It's you...}
{410}{}{哦是你。。。}
### {411}{}{I'm working, I'm working! Can't you see?}
{411}{}{我在工作，我在工作！你看不见吗？}
### {412}{}{I was just having a break!}
{412}{}{我只是在休息！}
### {413}{}{What do you want?}
{413}{}{你想要什么？}
