##############################
#??????: NWO
#???: ???
#???? ??????: ???????? NWO
#??? ??????: 31.07.2014
##############################
#??? ???? "????? 2207" 
#??? "Rainman" ????????
##############################
#
#???????? ????????
#
# ?? ????????
### {1}{}{You see a sick, old man.}
{1}{}{你看到一个生病的老人。}
### {2}{}{The man looks at you with a shrewd, wise look.}
{2}{}{这个男人用一种精明而睿智的眼光看着你。}
#
# ??? ????????
### {3}{}{You see Mark.}
{3}{}{你看到马克了。}
### {4}{}{He is carefully looking through some documents.}
{4}{}{他正在仔细翻阅一些文件。}
#
#????? ?????????? ??????
#
### {10}{}{[the man looks at you for some time. Then he suddenly breaks silence with a quiet, but strong voice] New?}
{10}{}{[那个男人看了你一会儿。然后他突然用一个安静但有力的声音打破了沉默]新的？}

### {11}{002}{Yeah, kinda. And you are? Old?}
{11}{002}{是的，有点。你是吗？古老的}
### {12}{003}{Yes. By the way, nice town you have here.}
{12}{003}{对顺便说一句，这里是个不错的小镇。}
### {13}{004}{[lie] No, actually I am already living here for a long time. I guess you didn't recognize me...}
{13}{004}{不，实际上我已经在这里住了很长时间了。我猜你没认出我。。。}
### {14}{999}{[pretend you didn't hear him and walk away]}
{14}{999}{[假装你没听到他说话然后走开]}


### {20}{}{[he gets quiet again, probably thinking about the next thing to say. His studying look is still coming through you] I'm afraid there's no place here for ones like you. We have nothing to talk about. At least for now... Probably, we can try again later - if you are capable of showing that you can be trusted. [without waiting for your reaction, he turns back to some papers]}
{20}{}{[他又安静下来了，可能在想下一句话。他那学习的神情仍在你脑海中浮现]恐怕这里没有像你这样的人的容身之地。我们没有什么可谈的。至少现在。。。也许，我们可以稍后再试——如果你能够证明你是可以信任的。[不等你的反应，他又回头看了一些报纸]}
### {21}{005}{Such manners. Can I ask your name, at least?}
{21}{005}{这样的礼貌。我至少可以问一下你的名字吗？}
### {22}{005}{What's your name then?}
{22}{005}{那你叫什么名字？}


### {30}{}{A good manners in Radius. Good. Welcome to NWO. Most likely, you are familiar with the rules by now. I can only additionally empathize that I strongly recommend following them. My name is Mark. I do the duty to my town by managing things here and keeping it safe. Unfortunately, there are some problems presented at the moment, so I don't have any time to spare speaking to you. Probably, if the situation changes, I could be available for conversation. [he turns away from you and starts going through some papers, indicating that this dialog is over]}
{30}{}{在Radius有礼貌。好的欢迎来到NWO。最有可能的是，你现在已经熟悉规则了。我只能感同身受地说，我强烈建议遵循它们。我的名字叫马克。我对我的城市负有责任，管理这里的一切并确保它的安全。不幸的是，目前出现了一些问题，所以我没有多余的时间和你说话。也许，如果情况发生变化，我可以进行交谈。[他转身离开你，开始翻阅一些文件，表示对话已经结束]}
### {31}{999}{Umm... Well... Was nice meeting you, Mark.}
{31}{999}{嗯。。。好很高兴见到你，马克。}
### {32}{999}{[silently turn back and go away]}
{32}{999}{[默默地转身离去]}


### {40}{}{Really? What's my name then?}
{40}{}{真正地那我叫什么名字？}
### {41}{006}{Uh... Steve?}
{41}{006}{嗯史蒂夫？}
### {42}{006}{Kyle?}
{42}{006}{凯尔？}
### {43}{006}{Leonard?}
{43}{006}{伦纳德？}
### {44}{007}{Okay, you got me. I came here recently.}
{44}{007}{好吧，你抓住我了。我最近来过这里。}


### {50}{}{[he doesn't even look in your direction] Mark, in charge of this settlement.}
{50}{}{[他甚至没有朝你的方向看]马克，负责这个和解。}
### {51}{999}{Well, it was, "nice" meeting you, "Mark". }
{51}{999}{很高兴见到你，“马克”。}
### {52}{999}{[silently turn back and go away]}
{52}{999}{[默默地转身离去]}


### {60}{}{[he patiently looks at you and waits]}
{60}{}{[他耐心地看着你等着]}
### {61}{007}{What?}
{61}{007}{什么}
### {62}{007}{Is that incorrect? I was sure I've beaten my sclerosis...}
{62}{007}{这不正确吗？我确信我已经战胜了我的硬化症。。。}


### {70}{}{The name's Mark, I'm in charge of this settlement. And I don't have time to fool around. This place is not for the likes of you. We have nothing to talk about. [he pondered] At least for now... But probably, we can try again later - if you are capable of showing that you can do something more useful for the town than wasting my time. [he turns away from you and starts to look through some documents]}
{70}{}{我的名字叫马克，我负责这个结算。我没有时间闲逛。这个地方不适合你这样的人。我们没有什么可谈的。[他沉思]至少现在。。。但也许，我们可以稍后再试——如果你能证明你可以为这个小镇做一些比浪费我的时间更有用的事情。[他转身离开你，开始翻阅一些文件]}
### {71}{999}{[end the conversation]}
{71}{999}{[结束对话]}


### {100}{}{[Mark takes his eyes off some old journal in plain dark-green cover, now he's looking at you, waiting for you to say something]}
{100}{}{[马克把目光从一本普通墨绿色封面的旧日记上移开，现在他正看着你，等着你说些什么]}
### {101}{013}{I've recently helped some of your folks...}
{101}{013}{我最近帮助了你的一些人。。。}
### {102}{012}{[lie] I've recently helped some of your folks...}
{102}{012}{[谎言]我最近帮助了你的一些人。。。}
### {103}{011}{I'm just wandering around. Looking for what I can do for the town.}
{103}{011}{我只是四处闲逛。想知道我能为这个小镇做些什么。}
### {104}{018}{I wanted to talk to you about Sam and Lucy...}
{104}{018}{我想和你谈谈山姆和露西。。。}
### {105}{024}{So... I think I've done it. Sam and Lucy apologized to each other and gave their word that they will behave in the future.}
{105}{024}{所以…我想我已经做到了。山姆和露西互相道歉，并保证他们将来会表现得很好。}
### {106}{031}{Can you tell me about this town?}
{106}{031}{你能告诉我这个小镇的情况吗？}
### {107}{062}{Mark... I'd like to talk about your successor, the future head of the settlement.}
{107}{062}{做记号我想谈谈你的继任者，未来的定居点负责人。}
### {108}{103}{Hey, Mark! What's up?}
{108}{103}{嘿，马克！怎么了？}
### {112}{108}{I'd like to talk about Skeet.}
{112}{108}{我想谈谈斯基特。}
### {109}{999}{Nothing, just walking around. I see you are busy. I'll come by later.}
{109}{999}{没什么，只是四处走走。我看你很忙。我稍后再来。}


### {110}{}{Here? }
{110}{}{在这里}
### {111}{999}{Okay. I got it, already leaving...}
{111}{999}{可以我明白了，已经离开了。。。}


### {120}{}{Is that so? [he stops what he has been doing and moves closer] I asked people to keep an eye on you. If you would do something, I would immediately know. So, stop wasting my time! Go make yourself useful or try your luck somewhere else. With the Jackals, for example. They like your kind. }
{120}{}{是这样吗？[他停止了他一直在做的事情，走得更近了]我让人们关注你。如果你愿意做点什么，我马上就会知道。所以，别再浪费我的时间了！去让自己变得有用，或者去别的地方碰碰运气。例如，与豺狼。他们喜欢你这种人。}
### {121}{999}{Okay, okay! I'm going!}
{121}{999}{好的，好的！我要走了！}


### {130}{}{Good [he nods], so I've been told. So, does it feel good to help people?}
{130}{}{很好[他点头]，所以我被告知。那么，帮助别人感觉好吗？}
### {131}{015}{Yeah, sure.}
{131}{015}{是的，当然。}
### {132}{014}{Frankly, not much. I prefer not to waste myself on charity - 'cause I don't produce batteries in my basement out of nothing.}
{132}{014}{坦率地说，不多。我宁愿不把自己浪费在慈善事业上——因为我不会在地下室里无中生有地生产电池。}


### {140}{}{It's good that you are honest about this. Much better than to lie. I appreciate honesty.}
{140}{}{你对这件事很诚实，这很好。比撒谎要好得多。我欣赏诚实。}
### {141}{016}{[keep listening]}
{141}{016}{[继续听]}


### {150}{}{So, yes, we could find some use of your services. Kindness, loyalty, and reliability are not common qualities of people in Radius, unfortunately...}
{150}{}{所以，是的，我们可以找到一些使用您的服务。善良、忠诚和可靠不是Radius人的共同品质，不幸的是。。。}
### {151}{016}{[keep listening]}
{151}{016}{[继续听]}


### {160}{}{I have a small favor to ask. It's personal. You are new here, so you have a clean, unjudged look. It can help solve one little problem. You are, probably, already met Sam and Lucy. The former is my friend and my grandfather. The latter is my wife. And I'd be damned if there's at least one day without them quarreling! Every day, any reason.}
{160}{}{我有一个小小的请求。这是针对个人的。你是新来的，所以你有一个干净的，没有偏见的样子。它可以帮助解决一个小问题。你可能已经见过山姆和露西了。前者是我的朋友和祖父。后者是我的妻子。如果至少有一天他们不吵架，我会被诅咒的！每一天，任何原因。}
### {161}{017}{Family stuff... Is that even okay to put a stranger like me into this?}
{161}{017}{家庭用品。。。把一个像我这样的陌生人放在这里面可以吗？}
### {162}{018}{Such a strange request. For a start, I have some questions about this... "problem".}
{162}{018}{这么奇怪的要求。首先，我对此有一些疑问。。。“问题”。}
### {163}{019}{Well... Any whim for your batteries...}
{163}{019}{好任何对电池的突发奇想。。。}
### {164}{020}{Frankly speaking, I'm not the best therapist. Actually, I'm no therapist at all!}
{164}{020}{坦率地说，我不是最好的治疗师。事实上，我根本不是治疗师！}


### {170}{}{I agree, it might look stupid. The thing is - no one here wants to try anymore. Most of them already did... It's impenetrable... But, as I said, you are a fresh person with an unjudged look.}
{170}{}{我同意，这可能看起来很愚蠢。问题是，这里没有人想再尝试了。他们中的大多数人已经做了。。。它是无法穿透的。。。但是，正如我所说，你是一个全新的人，一副没有偏见的样子。}
### {171}{018}{Well... maybe I'll take the job. Still, I need to know more about Sam and Lucy...}
{171}{018}{好也许我会接受这份工作。尽管如此，我还是需要更多地了解山姆和露西。。。}
### {172}{019}{I think I'll handle it. For a price, of course.}
{172}{019}{我想我会处理的。当然要付出代价。}
### {173}{020}{Honestly, I doubt I will be of any help. Especially, if even close friends and relatives are already tried to do something with it and failed.}
{173}{020}{老实说，我怀疑我会帮上什么忙。尤其是，即使是亲密的朋友和亲戚也已经试图用它做点什么，但失败了。}


### {180}{}{Of course. I'll try to give you the answers to all of your questions.}
{180}{}{当然我会尽力给你所有问题的答案。}
### {181}{021}{Tell me about reasons for their mutual dislike for each other.}
{181}{021}{告诉我他们互相不喜欢对方的原因。}
### {182}{022}{Tell me about Sam.}
{182}{022}{告诉我关于山姆的事。}
### {183}{023}{Tell me about Lucy.}
{183}{023}{告诉我关于露西的事。}


### {190}{}{The reward will be worth it, I promise. I have some... Available resources. Personal resources, don't take me wrong!}
{190}{}{我保证，报酬是值得的。我有一些。。。可用资源。个人资源，别误会我！}
### {191}{018}{Well... Okay. Why not? I'm not making any promises, but I'll try. I have some questions about this "problem".}
{191}{018}{好可以为什么不呢？我没有做出任何承诺，但我会努力的。我对这个“问题”有一些疑问。}


### {200}{}{I don't think that it's the main thing to focus on. Just try to hear both of them out, to convince them that you are not allied with the other one- [he suddenly bends over, coughing. After he stands up, wiping the sweat from his forehead, his face is still red]. You have to excuse me... Lately, it's happening more often than usual. So, what do you say?}
{200}{}{我不认为这是重点。只要试着把他们两个都听清楚，让他们相信你和另一个没有结盟——[他突然弯下腰，咳嗽。站起来擦了擦额头上的汗水后，脸还是红的]。对不起……最近，这种事比平时更频繁了。那么，你怎么说呢？}
### {201}{018}{Uh... I can try. But I'd like to hear some details about their quarrel...}
{201}{018}{嗯我可以试试。但我想听听他们吵架的细节。。。}
### {202}{019}{If there's a reward in it, I will clean the dirty laundry of your family for you.}
{202}{019}{如果有报酬的话，我会帮你打扫你家的脏衣服。}


### {210}{}{I don't know the whole picture, but it seems it's about my son, Daniel. Sam tries to prepare him for the position of leading the town and he is not fine with his mother's... Parenting methods. You know, I don't want to talk about it... Just ask themselves.}
{210}{}{我不知道全貌，但似乎是关于我儿子丹尼尔的。山姆试图让他为领导小镇的职位做好准备，但他对母亲的。。。育儿方法。你知道，我不想谈论它…问问自己就好了。}
### {211}{018}{I have more questions...}
{211}{018}{我还有更多的问题。。。}
### {212}{999}{Okay, I'm out of questions for now. I will try to go and talk to your family.}
{212}{999}{好吧，我现在没有问题了。我会设法去和你的家人谈谈。}


### {220}{}{Sam used to be a leader here, preceding my father. He is my grandfather - and also one of a few ghouls here in NWO. He is very wise, I consider him not only my relative but also my friend and teacher. I trust him completely.}
{220}{}{在我父亲之前，山姆曾是这里的领导者。他是我的祖父，也是北威州为数不多的食尸鬼之一。他非常聪明，我认为他不仅是我的亲戚，也是我的朋友和老师。我完全信任他。}
### {221}{018}{I have more questions...}
{221}{018}{我还有更多的问题。。。}
### {222}{999}{Okay, I'm out of questions for now. I will try to go and talk to your family.}
{222}{999}{好吧，我现在没有问题了。我会设法去和你的家人谈谈。}
### {223}{026}{You know, sometimes I have a hard time interacting with dicks who think they are kings of this world because of different skin color... And I suppose that Sam must have had problems like that on a much larger scale. Maybe you could provide some personal information about him? Like an ace in the hole. It would be easier for me to solve conflict then.}
{223}{026}{你知道，有时我很难与那些因为肤色不同而认为自己是世界之王的白痴互动。。。我想山姆一定在更大范围内遇到了这样的问题。也许你可以提供一些关于他的个人信息？就像洞里的王牌。那对我来说解决冲突会更容易。}


### {230}{}{Lucy... my wife. She is pretty simple at times, yet still manages to surprise me. The one and only champion in sports of getting on the nerves of her husband... Don't take me wrong, I love her very much. I'm just... tired of this conflict. Her main weak spot is our son, Daniel.}
{230}{}{露西。。。我的妻子。她有时很简单，但仍然让我感到惊讶。她是唯一一个能让她丈夫紧张的体育冠军。。。别误会我，我非常爱她。我只是。。。厌倦了这种冲突。她的主要弱点是我们的儿子丹尼尔。}
### {231}{018}{I have more questions...}
{231}{018}{我还有更多的问题。。。}
### {232}{999}{Okay, I'm out of questions for now. I will try to go and talk to your family.}
{232}{999}{好吧，我现在没有问题了。我会设法去和你的家人谈谈。}


### {240}{}{[Mark silently looks at you almost for a minute, saying nothing. He probably tries to understand if that's true. Then he suddenly smiles] That's great news! [almost immediately he becomes serious again] It means a lot to me. It may look like some family matters, but it will strongly affect the future of the whole town. I think you deserve a reward... And I have something special here, very rare in our times... Take it. }
{240}{}{[马克默默地看了你一分钟，什么也没说。他可能想知道这是不是真的。然后他突然笑了起来]这是个好消息！[几乎立刻他又严肃起来了]这对我来说意义重大。这看起来像是一些家庭事务，但它将强烈影响整个城镇的未来。我认为你应该得到奖励。。。我在这里有一些特别的东西，在我们这个时代非常罕见。。。接受它。}
### {241}{025}{Thank you, Mark. Lucy still asked you to talk to Daniel about his future.}
{241}{025}{谢谢你，马克。露西仍然让你和丹尼尔谈谈他的未来。}
### {242}{999}{Thank you, Mark. I have to go, but I'll come by sometimes.}
{242}{999}{谢谢你，马克。我得走了，但有时我会来的。}


### {250}{}{Yeah... I think this is what I'm going to do now. Thanks. }
{250}{}{是 啊我想这就是我现在要做的。谢谢}
### {251}{999}{Bye, Mark.}
{251}{999}{再见，马克。}


### {260}{}{I don't think it's a good idea. Frankly speaking, it makes me feel like a traitor... Still, this stuff is beyond any borders now... [He stays silent for some time, probably, weighting choices] ...Okay, listen. Sam is not liked here in the town not only because he is a walking corpse, who although looks more lively than many. And more smart, for that matter. It's because he also has a lot of pride in him, he won't start apologizing just like that. In the case of Lucy - definitely. He takes her for... Narrow-minded chick. }
{260}{}{我认为这不是个好主意。坦率地说，这让我觉得自己像个叛徒。。。尽管如此，这些东西现在已经超越了任何边界。。。[他可能会沉默一段时间，权衡选择]。。。好的，听着。山姆在城里不受欢迎，不仅因为他是一个行尸走肉，尽管看起来比很多人都活泼。而且更聪明。这是因为他也有很多自豪感，他不会那样开始道歉。就露西而言——当然。他把她当成。。。心胸狭窄的小妞。}
### {261}{027}{How is this of any help to me?}
{261}{027}{这对我有什么帮助？}


### {270}{}{Wait, I'm not done yet. So, considering that Lucy is also stubborn as a ram when it comes to arguing, she will never take the initiative in peaceful negotiations. They are both waiting for another one to crawl down to them with apologies. And, well... To move this somehow, you could... Probably, you could try to persuade Sam with a little fact...}
{270}{}{等等，我还没做完。因此，考虑到露西在争吵时也很固执，她永远不会在和平谈判中占据主动。他们都在等待另一个向他们道歉的人。而且，嗯。。。为了以某种方式移动它，你可以。。。也许，你可以试着用一点事实来说服山姆。。。}
### {271}{028}{Interesting.}
{271}{028}{有趣的}


### {280}{}{We had the doctor coming through here once, who knew some stuff about ghouls. The name was dr. Spencer, I think. He treated Sam. Didn't tell from what, Sam also kept it a secret. Doctor-patient confidentiality, all that. But Spencer loved good booze. And one time, when he got wasted, he spilled out that Sam has some... Consequences from his condition. His brains are naturally rotting, decreasing his mental competence and shortening his lifespan. He also told that he prescripted Sam some antibiotics, rare ones and pretty expensive. I bid my time waiting for the chance to talk to Sam about it, offer some help. But couldn't - I know he would refuse my help, he is very prideful. And then we started to notice that amount of batteries in the town treasury is decreasing.}
{280}{}{我们曾经有一位医生来过这里，他对食尸鬼有些了解。我想他叫Spencer医生。他对待萨姆。没有说出来，萨姆也保守了秘密。医患保密，诸如此类。但斯宾塞喜欢好酒。有一次，当他喝醉了，他说山姆有一些。。。他的病情造成的后果。他的大脑自然腐烂，降低了他的智力，缩短了他的寿命。他还说，他给山姆开了一些抗生素，罕见的，而且很贵。我等着有机会和山姆谈谈，提供一些帮助。但不能——我知道他会拒绝我的帮助，他非常自豪。然后我们开始注意到，镇财政部的电池数量正在减少。}
### {281}{029}{I think I get it...}
{281}{029}{我想我明白了。。。}


### {290}{}{I didn't tell the guards. I didn't tell anyone. I followed him. Of course, it was Sam, quietly stealing the batteries. And he still does. I never confronted him about it. And I would like the situation to change, for him to take all the money he needs, and to no one to know that it's him, who does it. If this leaks out - he will be destroyed.}
{290}{}{我没有告诉警卫。我没有告诉任何人。我跟着他。当然，是山姆在悄悄地偷电池。他现在依然如此。我从未就此与他对质。我希望情况有所改变，让他拿走他需要的所有钱，让没有人知道是他干的。如果这件事泄露出去，他将被摧毁。}
### {291}{030}{Wow... Mark, you're such a pussy.}
{291}{030}{哇！马克，你真是个胆小鬼。}
### {292}{999}{I see. I think that's enough for me, at least for now. I promise not to ruin his reputation. It will stay between us. I'll come back when the matter is settled.}
{292}{999}{我明白了。我认为这对我来说已经足够了，至少现在是这样。我保证不会毁了他的名声。我们之间不会有任何关系。事情解决后我会回来的。}


### {300}{}{It would just be better this way. [his facial expression looks even more like a stone than usual] And know this, if you'll use this information for harm - everyone in the whole Radius will know that you're the one who stole the batteries and tried to blame Sam for it. Take my word for it. [his looks softens] Now, do you have any questions?}
{300}{}{这样会更好。[他的面部表情看起来比平时更像一块石头]要知道，如果你利用这些信息进行伤害，整个Radius的每个人都会知道，是你偷了电池，并试图为此责怪Sam。相信我的话。[他的表情软化了]现在，你有什么问题吗？}
### {301}{018}{Yeah... Would be nice for you to answer in a more peaceful way...}
{301}{018}{是 啊如果你能以一种更平和的方式回答就好了。。。}
### {302}{999}{No. For your information: I didn't plan to ruin his life. The threats were unnecessary. [turn back and leave]}
{302}{999}{不。告诉你：我没打算毁了他的生活。这些威胁是没有必要的。[转身离开]}
### {303}{999}{No, no questions. [turn back and leave]}
{303}{999}{不，没有问题。[转身离开]}


### {310}{}{Is that so? What do you want to know?}
{310}{}{是这样吗？你想知道什么？}
### {311}{032}{I'm interested in the town's history. You have a pretty strong community here. As if all of you are a family...}
{311}{032}{我对这个小镇的历史很感兴趣。这里有一个相当强大的社区。就好像你们都是一家人。。。}
### {312}{037}{What makes NWO nowadays? How do you survive?}
{312}{037}{是什么造就了如今的NWO？你是如何生存的？}
### {313}{038}{Tell me about residents. At least about the ones worth talking to, from your point of view. }
{313}{038}{告诉我有关居民的情况。至少从你的角度来看，是关于那些值得交谈的人。}
### {314}{102}{You know, I'm interested in something called the encyclopedia. I've heard of it a lot. Would like to study it. There were some rumors you know more than anyone about the matter.}
{314}{102}{你知道，我对百科全书很感兴趣。我听说过很多。我想研究一下。关于这件事，有一些传言你比任何人都了解得多。}
### {315}{999}{You know, I've just remembered I have some things to do... I'll come by later!}
{315}{999}{你知道，我刚刚想起我有一些事情要做……我稍后再来！}


### {320}{}{[he pulls back, strangely staring at you] So... If you want me to make comments on the rumors about the first leader's death, I have nothing. No one does. Everyone babble all kinds of nonsense... The testaments are also blank on the matter.}
{320}{}{[他退缩了，奇怪地盯着你]所以……如果你想让我对第一任领导人去世的传言发表评论，我什么都没有。没有人这样做。每个人都胡言乱语。。。遗嘱在这个问题上也是空白的。}
### {321}{033}{The first leader?}
{321}{033}{第一任领导人？}
### {322}{035}{The testaments?}
{322}{035}{遗嘱？}
### {323}{031}{Actually, I'm not talking about that. Let's get back to questions about the town...}
{323}{031}{事实上，我不是在说这个。让我们回到关于这个小镇的问题上来。。。}
### {324}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{324}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {330}{}{[he bites his lip] Oh, you didn't know... I was talking about Jim Reynolds. Judging by the testaments, he was a bad leader and not a good man either. He was removed from his position, the leader's status transferred to a more... adequate person. And about the rumors... You'll come by them eventually if you still didn't. So it's better to hear from me, I suppose. The talk was that people beat him to death, minced him into mash, put it into tin cans, and then ritually ate. Some kind of bullshit.}
{330}{}{[他咬着嘴唇]哦，你不知道。。。我说的是吉姆·雷诺兹。从遗嘱来看，他是个坏领导，也不是个好人。他被免职了，领导人的地位转移到了一个更。。。合适的人。关于谣言。。。如果你还是不去的话，你最终会遇到他们的。所以，我想最好听听我的意见。据说人们把他打死，把他切成泥，放进锡罐里，然后按照仪式吃。有些扯淡。}
### {331}{034}{Oh wow... You guys are scary...}
{331}{034}{哦，哇。。。你们太可怕了。。。}
### {332}{035}{What testaments did you mention?}
{332}{035}{你提到了哪些遗嘱？}
### {333}{999}{You know, I've just remembered I have some things to do... I'll come by later...}
{333}{999}{你知道，我刚刚想起我有一些事情要做…我稍后会来。。。}


### {340}{}{Scary? I tell you - this is all bullshit talk. Let's get back to your questi- [he suddenly gnarls forward, coughing. After a minute, he continues] -questions about the town.}
{340}{}{恐怖的我告诉你，这都是胡说八道。让我们回到你的问题上来——[他突然向前咳嗽。过了一分钟，他继续]——关于这个小镇的问题。}
### {341}{035}{Wait, I wanted to ask about the testaments... What is it anyway?}
{341}{035}{等等，我想问一下遗嘱。。。到底是什么？}
### {342}{031}{I still have a couple of questions...}
{342}{031}{我还有几个问题。。。}
### {343}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{343}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {350}{}{Testaments... I guess it sounds too pompous when you say it. It's something akin to a set of rules, which the first leader left to his successors to follow. I think they are quite smart. Although, don't confuse them with the laws... And no one knows them well enough, except the town leaders.}
{350}{}{遗嘱。。。我想这听起来太浮夸了。这类似于一套规则，第一任领导人留给他的继任者来遵循。我认为他们很聪明。不过，不要把它们和法律混为一谈。。。除了镇上的领导之外，没有人对他们足够了解。}
### {351}{036}{So you follow them?}
{351}{036}{所以你跟着他们？}
### {352}{031}{Let's get back to questions about your town...}
{352}{031}{让我们回到关于你所在城镇的问题上来。。。}
### {353}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{353}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {360}{}{It should be none of your concern.}
{360}{}{这不应该与你有关。}
### {361}{031}{Okay, let's get back to questions about your town...}
{361}{031}{好吧，让我们回到关于你所在城镇的问题上来。。。}
### {362}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{362}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {370}{}{We feed the whole Radius. Everyone would be long dead, if not for us. Well, most of them. Or they would have had to learn to feed on sunlight, wind, and the holy spirit. All in all, we are in a pretty good position here. We trade with everyone and live here as one big "family".}
{370}{}{我们喂养整个半径。如果不是我们，每个人都早就死了。嗯，他们中的大多数人。或者他们必须学会以阳光、风和圣灵为食。总而言之，我们在这里处于一个相当好的位置。我们与每个人进行贸易，并作为一个大“家庭”生活在这里。}
### {371}{031}{I see. A couple more questions...}
{371}{031}{我明白了。还有几个问题。。。}
### {372}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{372}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {380}{}{Everyone is equal to me here, I can't say someone stands out much. Maybe you'll ask more specific question? Who do you want to know about?}
{380}{}{在这里，每个人都和我平等，我不能说有人很突出。也许你会问更具体的问题？你想了解谁？}
### {381}{041}{Burns}
{381}{041}{烧伤}
### {382}{042}{Daniel}
{382}{042}{丹尼尔}
### {383}{044}{Dan}
{383}{044}{丹}
### {384}{047}{Arsene}
{384}{047}{砷}
### {385}{048}{Maurissa}
{385}{048}{毛里萨}
### {386}{049}{Juan}
{386}{049}{胡安}
### {387}{039}{[next]}
{387}{039}{[下一个]}
### {388}{031}{I guess I'd like to go back to questions about the town.}
{388}{031}{我想我想回到关于这个城镇的问题上来。}
### {389}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{389}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {390}{}{Everyone is equal to me here, I can't say someone stands out much. Maybe you'll ask more specific question? Who do you want to know about?}
{390}{}{在这里，每个人都和我平等，我不能说有人很突出。也许你会问更具体的问题？你想了解谁？}
### {391}{050}{Cyren}
{391}{050}{赛伦}
### {392}{053}{Hinder}
{392}{053}{阻碍}
### {393}{054}{Philipp}
{393}{054}{菲利普}
### {394}{055}{Seth}
{394}{055}{赛斯}
### {395}{055}{Matt}
{395}{055}{马特}
### {396}{040}{[next]}
{396}{040}{[下一个]}
### {397}{038}{[previous]}
{397}{038}{[以前的]}
### {398}{031}{I guess I'd like to go back to questions about the town.}
{398}{031}{我想我想回到关于这个城镇的问题上来。}
### {399}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{399}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {400}{}{Everyone is equal to me here, I can't say someone stands out much. Maybe you'll ask a more specific question? Who do you want to know about?}
{400}{}{在这里，每个人都和我平等，我不能说有人很突出。也许你会问一个更具体的问题？你想了解谁？}
### {401}{056}{Flint}
{401}{056}{打火石}
### {402}{057}{Owen}
{402}{057}{欧文}
### {403}{058}{Skeet}
{403}{058}{斯基特}
### {404}{059}{Blanca}
{404}{059}{布兰卡}
### {405}{060}{I'm more interested in hearing about you.}
{405}{060}{我更想听听你的消息。}
### {406}{038}{[first page]}
{406}{038}{[第一页]}
### {407}{039}{[second page]}
{407}{039}{[第二页]}
### {408}{031}{I guess I'd like to go back to questions about the town.}
{408}{031}{我想我想回到关于这个城镇的问题上来。}
### {409}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{409}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {410}{}{Burns... He is a good man, despite having manners more suitable to a Lavash corral janitor, than to the head of guards. But I'm fully confident with him. He is ready to do anything to keep us and our home safe. A piece of advice for you: do not talk to him about women - he will tire you with his success stories, filled with a lot more toilet humor than his usual conversations...}
{410}{}{烧伤。。。他是一个好人，尽管他的举止更适合拉瓦什畜栏的看门人，而不是警卫长。但我对他充满信心。他准备做任何事情来保护我们和我们家的安全。给你一条建议：不要和他谈论女人——他的成功故事会让你厌烦，比他平时的谈话充满了更多的厕所幽默。。。}
### {411}{038}{[ask about someone else]}
{411}{038}{[询问其他人]}
### {412}{031}{A valuable advice... but I'd like to go back to questions about the town.}
{412}{031}{一个宝贵的建议。。。但我想回到关于这个小镇的问题上来。}
### {413}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{413}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {420}{}{Daniel... My joy, my sadness. He is so young and juvenile. He can get back at you in a nasty tone, or to say something stupid - not because he really thinks so, but because he finds it "cool-looking". I know my ways towards every member of our community, excluding my own son. I don't even think I'm familiar with him well enough...}
{420}{}{丹尼尔。。。我的快乐，我的悲伤。他是如此的年轻和幼稚。他可以用一种恶劣的语气回击你，或者说一些愚蠢的话——不是因为他真的这么认为，而是因为他觉得这“很酷”。我知道我对待我们社区每一位成员的方式，不包括我自己的儿子。我甚至认为我对他不够熟悉。。。}
### {421}{043}{Listen, Mark, do you even spend time together? Did you talk to him about the future?}
{421}{043}{听着，马克，你们有时间在一起吗？你和他谈过未来吗？}
### {422}{038}{I see - you don't like to talk about this. I'll ask about other ones in NWO now, okay?}
{422}{038}{我明白了——你不喜欢谈论这个。我现在会问一下NWO的其他人，好吗？}
### {423}{031}{I see - you don't like to talk about this. I'd like to get back to questions about the town.}
{423}{031}{我明白了——你不喜欢谈论这个。我想回到关于这个城镇的问题上来。}
### {424}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{424}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {430}{}{[Mark gives you a long, tired look, saying nothing. Looks like he waits for you to change the subject.]}
{430}{}{[马克疲惫地看了你一眼，什么也没说。看起来他在等你换个话题。]}
### {431}{038}{Oh... sorry. Let's talk about other ones in NWO, okay?}
{431}{038}{哦很抱歉让我们谈谈NWO的其他人，好吗？}
### {432}{031}{I'd like to get back to questions about the town.}
{432}{031}{我想回到关于这个城镇的问题上来。}
### {433}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{433}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {440}{}{Dan? Rude, harsh, and sneaky. Burns used to notice him doing little mean things a couple of times. A petty crook, in my view. }
{440}{}{丹？粗鲁、粗鲁、狡猾。伯恩斯曾经注意到他做过几次卑鄙的小事。在我看来，这是个小骗子。}
### {441}{045}{Why won't you throw him out then?}
{441}{045}{那你为什么不把他赶出去？}
### {442}{038}{I don't think he's of interest to me. Let's talk about someone else?}
{442}{038}{我觉得我对他不感兴趣。我们谈谈其他人吧？}
### {443}{031}{Yeah... Let's get back to questions about the town.}
{443}{031}{是 啊让我们回到关于这个城镇的问题上来。}
### {444}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{444}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {450}{}{If you still don't get it, we are all family here. You can't just throw someone out. I serve my town not by being paranoid about its inhabitants, or something. I have neither the power nor inclination to do so.}
{450}{}{如果你仍然不明白，我们在这里都是一家人。你不能把别人赶出去。我为我的城市服务，不是因为我对它的居民或其他什么偏执。我既没有权力也没有意愿这样做。}
### {451}{046}{I could do a little surveillance on him.}
{451}{046}{我可以监视一下他。}
### {452}{038}{I see. Would you mind telling me about the others in NWO?}
{452}{038}{我明白了。你介意告诉我关于NWO的其他人吗？}
### {453}{031}{Okay. Then I'd like to know something else about the town.}
{453}{031}{可以然后我想了解一下这个小镇的其他情况。}
### {454}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{454}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {460}{}{Drop it. We are not talking about this.}
{460}{}{放下它。我们不是在谈论这个。}
### {461}{038}{Okay, okay! Relax, Mark, let's talk about something else.}
{461}{038}{好的，好的！放松点，马克，让我们谈谈别的事情。}
### {462}{031}{Fine then, back to questions about the town.}
{462}{031}{好吧，回到关于小镇的问题上来。}
### {463}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{463}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {470}{}{Arsene? Good for nothing mess without his own opinion. My son's buddy. Can't say I'm delighted to interact with him. He has a very cluttered mind.}
{470}{}{阿森？如果没有他自己的意见，那就一无是处。我儿子的好友。不能说我很高兴能和他互动。他头脑非常混乱。}
### {471}{038}{Looks like I'll hardly get any value from communicating with him... let's talk about someone else?}
{471}{038}{看来我和他交流几乎没有任何价值。。。让我们谈谈其他人？}
### {472}{031}{Yeah... Let's get back to questions about the town.}
{472}{031}{是 啊让我们回到关于这个城镇的问题上来。}
### {473}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{473}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {480}{}{I kindly ask you to not mock her. She is the strange one, very strange. But that does not make her a bad person. Have some compassion for her obsessive ideas. You can even agree with her, but I dare you to do anything she asks about - be safer. And way less stupidly looking...}
{480}{}{我恳请你不要嘲笑她。她就是那个奇怪的人，非常奇怪。但这并不意味着她是个坏人。对她痴迷的想法要有点同情。你甚至可以同意她的意见，但我敢说，她要求你做什么你就做什么——要更安全。而且看起来不那么愚蠢。。。}
### {481}{038}{I like your town more with every minute... how did you manage not to kill off each other by now? Would you mind telling me more about such wackos?}
{481}{038}{我每分钟都更喜欢你的小镇。。。你们现在是怎么做到不互相残杀的？你介意多告诉我一些关于这些疯子的事吗？}
### {482}{031}{Such a madhouse. Let's get back to questions about the town.}
{482}{031}{这样的疯人院。让我们回到关于这个城镇的问题上来。}
### {483}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{483}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {490}{}{He is an incredible man. A master of his craft and a strong link in the chain of our community. A pity he doesn't have kids. Only I wouldn't recommend you to ask him to teach you something. But if you are suffering from insomnia, he's the man for the job. He can put to sleep even the ones who just got up from a night full of dreams.}
{490}{}{他是一个令人难以置信的人。他是一位技艺大师，也是我们社区链条中的重要一环。很遗憾他没有孩子。只是我不建议你让他教你一些东西。但是，如果你失眠了，他就是这份工作的合适人选。即使是那些刚从充满梦境的夜晚醒来的人，他也能入睡。}
### {491}{038}{You have such a dream team here. Mind me asking about someone else?}
{491}{038}{你们有这样一支梦之队。介意我问问其他人吗？}
### {492}{031}{I still have some questions about the town...}
{492}{031}{我对这个小镇还有一些疑问。。。}
### {493}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{493}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {500}{}{Our scout. The man of steel nerves and infinite courage. He's an important part of our society. Wish we had more ones like him...}
{500}{}{我们的侦察兵。钢铁般的神经和无限的勇气。他是我们社会的重要组成部分。希望我们有更多像他一样的人。。。}
### {501}{051}{Maybe I'll upset you, but your heroic scout is actually a coward. I accompanied him to Tin Industries at his request - he told me that his previous partner "has perished". In reality, he left his partner to die as a burden. And he also did the same to me. I advise you to look carefully at this loser - at least don't give him any partners.}
{501}{051}{也许我会让你不高兴，但你英勇的侦察兵实际上是个胆小鬼。应他的要求，我陪他去了锡工业公司——他告诉我，他的前合伙人“已经去世”。事实上，他离开了他的伴侣，让他作为负担死去。他也对我做了同样的事。我建议你仔细看看这个失败者——至少不要给他任何伙伴。}
### {502}{038}{Okay... I'm interested in someone else...}
{502}{038}{可以我对其他人感兴趣。。。}
### {503}{031}{I see... Let's get back to questions about the town.}
{503}{031}{我明白了。。。让我们回到关于这个城镇的问题上来。}
### {504}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{504}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {510}{}{[Mark froze like he just stepped in shit] What?}
{510}{}{[马克像踩了屎一样僵住了]什么？}
### {511}{052}{I am saying that your hero is a gutless puppy who runs away with tail between his legs at the first chance he gets.}
{511}{052}{我是说，你的英雄是一只没有勇气的小狗，一有机会就夹着尾巴逃跑了。}


### {520}{}{I see... You know, I have to ask you not to talk wide about the matter... This could lead only to lynching from the town's folk. I'll talk to him myself. He will pay fully to the community, believe me. And... Thank you, not only for getting tin from Tin Industries but also for telling me everything about this... Here, take it. It's well-deserved.}
{520}{}{我明白了。。。你知道，我不得不要求你不要对这件事大谈特谈。。。这只会导致该镇民众私刑处死。我会亲自和他谈谈。相信我，他会为社区付出全部。而且。。。谢谢你，不仅从锡工业公司得到了锡，还告诉了我关于这件事的一切。。。给，拿着，这是应得的。}
### {521}{038}{Thanks, Mark, glad to be of help, you know. Would you tell me more about someone else?}
{521}{038}{谢谢你，马克，很高兴能为你提供帮助。你能告诉我更多关于其他人的情况吗？}
### {522}{031}{Thanks, Mark. Let's get back to questions about the town.}
{522}{031}{谢谢，马克。让我们回到关于这个城镇的问题上来。}
### {523}{999}{Thanks, Mark. By the way, I gotta go. I'll come by.}
{523}{999}{谢谢，马克。顺便说一句，我得走了。我会过来的。}


### {530}{}{Our doctor. Has hands of gold. I don't recommend bothering him with stupid questions. The talk is, once he had a patient who wouldn't shut up. So, instead of painkillers, he injected the poor guy with some stuff, which caused itches for a whole week straight. That idiot got himself fully cut and scratched. And a cherry on the cake - in the end, his eyebrows fell off.}
{530}{}{我们的医生。拥有金子般的双手。我不建议用愚蠢的问题来打扰他。据说，有一次他有一个病人不肯闭嘴。所以，他没有给这个可怜的家伙注射止痛药，而是给他注射了一些东西，这导致他连续一周发痒。那个白痴把自己弄得遍体鳞伤。还有蛋糕上的樱桃——最后，他的眉毛掉了下来。}
### {531}{038}{I'll keep that in mind... I'm interested in someone else.}
{531}{038}{我会记住的。。。我对别人感兴趣。}
### {532}{031}{I'll keep that in mind... Let's get back to questions about the town.}
{532}{031}{我会记住的。。。让我们回到关于这个城镇的问题上来。}
### {533}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{533}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {540}{}{He's the only one I can't talk much about. I had no interactions with him. }
{540}{}{他是我唯一不能多谈的人。我和他没有互动。}
### {541}{038}{Okay, then I have some questions about other inhabitants.}
{541}{038}{好吧，那么我有一些关于其他居民的问题。}
### {542}{031}{I see... Let's get back to questions about the town then.}
{542}{031}{我明白了。。。那么让我们回到关于这个城镇的问题上来。}
### {543}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{543}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {550}{}{Seth and Matt. They are brothers, although often treat each other worse than anybody around them. I suppose it's the usual thing - we don't appreciate what we have. Anyway, they are good guys.}
{550}{}{赛斯和马特。他们是兄弟，尽管彼此之间的待遇往往比他们周围的任何人都差。我想这是通常的事情——我们不欣赏我们所拥有的。不管怎样，他们都是好人。}
### {551}{038}{As you say, but in my opinion, these two are not right in their heads. Let's talk about someone else.}
{551}{038}{正如你所说，但在我看来，这两个人的想法是不对的。让我们谈谈其他人。}
### {552}{031}{Good guys, but strange... Let's get back to the questions about the town.}
{552}{031}{好人，但奇怪。。。让我们回到关于这个城镇的问题上来。}
### {553}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{553}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {560}{}{Oh... He's our hereditary caravaneer. Keep him away from your booze if you have some, and take lightly everything he says about himself.}
{560}{}{哦他是我们世袭的旅行家。如果你有酒的话，让他远离你的酒，对他说的关于自己的一切都要掉以轻心。}
### {561}{038}{Okay, then I have some questions about other inhabitants.}
{561}{038}{好吧，那么我有一些关于其他居民的问题。}
### {562}{031}{I see... Let's get back to questions about the town then.}
{562}{031}{我明白了。。。那么让我们回到关于这个城镇的问题上来。}
### {563}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{563}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {570}{}{He's one of our best butchers. For as long as I can remember - never met anyone else who can be so enthusiastic about dismembering the Lavash. He is doing it so precisely it's scary and beautiful at the same time. Especially considering that you can't always say if he's serious, or fooling around...}
{570}{}{他是我们最好的屠夫之一。从我记事起，从未见过其他人如此热衷于肢解熔岩。他做得如此精确，既可怕又美丽。尤其是考虑到你不能总是说他是认真的，还是鬼混的。。。}
### {571}{038}{Okay, then I have some questions about other inhabitants.}
{571}{038}{好吧，那么我有一些关于其他居民的问题。}
### {572}{031}{I see... Let's get back to questions about the town then.}
{572}{031}{我明白了。。。那么让我们回到关于这个城镇的问题上来。}
### {573}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{573}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {5801}{}{Skeet... You know, I don't want to talk about him. I trusted the man - and turns out he has been stealing our canned meat from storage... Let's talk about something else.}
{5801}{}{Skeet。。。你知道，我不想谈论他。我信任那个人，结果发现他一直在从仓库里偷我们的罐头肉。。。让我们谈谈其他事情。}
### {581}{038}{Okay, then I have some questions about other inhabitants.}
{581}{038}{好吧，那么我有一些关于其他居民的问题。}
### {582}{031}{I see... Let's get back to questions about the town then.}
{582}{031}{我明白了。。。那么让我们回到关于这个城镇的问题上来。}
### {583}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{583}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}
### {5802}{}{Um... By the way, thank you, for clearing out the Skeet's reputation... You know, I've been accusing him too, of stealing. So I suppose you know him better than me, and I have nothing new to say.}
{5802}{}{嗯…顺便说一句，谢谢你为斯基特家族洗脱了名声。。。你知道，我也一直在指责他偷窃。所以我想你比我更了解他，我没有什么新鲜事要说。}
### {584}{038}{Okay, then let's get back to questions about the town's inhabitants.}
{584}{038}{好吧，那么让我们回到关于该镇居民的问题上来。}
### {585}{031}{I'd like to ask about the town.}
{585}{031}{我想问一下这个城镇的情况。}
### {586}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{586}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {590}{}{Blanca? She's young and not very smart. Quite fond of our scout, Cyren. Nothing more to say about her...}
{590}{}{布兰卡？她年轻，不太聪明。很喜欢我们的侦察兵，赛伦。关于她没什么好说的了。。。}
### {591}{038}{Okay, then I have some questions about other inhabitants.}
{591}{038}{好吧，那么我有一些关于其他居民的问题。}
### {592}{031}{I see... Let's get back to questions about the town then.}
{592}{031}{我明白了。。。那么让我们回到关于这个城镇的问题上来。}
### {593}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{593}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {600}{}{About me? [he ponders for a while, then coughs and scratches his chin] I am the leader of this town; I've been prepared for this position since my childhood: I was forced to learn a lot. I also had to spend a lot of time in factory bays, watching workers. How they do they labor from day to day, wearing out their backs for the good of our society. Now my conscience doesn't allow me to just sit here doing nothing, making myself a local god to worship.}
{600}{}{关于我？[他沉思了一会儿，然后咳嗽并挠了挠下巴]我是这个小镇的领袖；我从小就为这个职位做好了准备：我被迫学习了很多。我还不得不花很多时间在工厂的隔间里观察工人。他们是如何日复一日地工作的，为了我们社会的利益而疲惫不堪。现在我的良心不允许我坐在这里无所事事，让自己成为当地的神来崇拜。}
### {601}{061}{As far as I see, your son was left out of this kind of upbringing?}
{601}{061}{据我所知，你的儿子被排除在这种教养之外？}
### {602}{038}{Okay, then I have some questions about other inhabitants.}
{602}{038}{好吧，那么我有一些关于其他居民的问题。}
### {603}{031}{I see... Let's get back to questions about the town then.}
{603}{031}{我明白了。。。那么让我们回到关于这个城镇的问题上来。}
### {604}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{604}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {610}{}{[Mark gets silent for a moment] Yes. Lucy strongly objected to such parenting methods. Maybe it would be better not to listen to her opinion in such matters, then he would have grown up a fine man. Let's change the subject, okay?}
{610}{}{[马克沉默了一会儿]是的。露西强烈反对这种育儿方式。也许在这样的事情上最好不要听她的意见，这样他就会成长为一个好人。让我们换个话题，好吗？}
### {611}{038}{Okay, then I have some questions about other inhabitants.}
{611}{038}{好吧，那么我有一些关于其他居民的问题。}
### {612}{031}{Sure, Mark... Let's get back to questions about the town then.}
{612}{031}{当然，马克。。。那么让我们回到关于这个城镇的问题上来。}
### {613}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{613}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {620}{}{Yes?}
{620}{}{对}
### {621}{063}{I spoke to Burns... He told me that you have some kind of problem regarding your successor. He didn't get much into details, only said it would be better to discuss it with you.}
{621}{063}{我和伯恩斯谈过了。。。他告诉我，你对你的继任者有某种问题。他没有透露太多细节，只是说最好和你讨论一下。}
### {622}{073}{Mark, I talked to everyone, just as you asked.}
{622}{073}{马克，我和每个人都谈过了，就像你问的那样。}
### {623}{072}{I'm still in the process of doing my job. Just came by.}
{623}{072}{我仍在做我的工作。刚过来。}
### {624}{097}{About Sam's election...}
{624}{097}{关于山姆的当选。。。}
### {625}{098}{About talking some sense into your son...}
{625}{098}{关于对你儿子讲一些道理。。。}
### {626}{999}{Uh... Mark, I need to run now, have some stuff to take care of...}
{626}{999}{嗯马克，我现在需要跑步，有一些事情要处理。。。}


### {6301}{}{I wonder why someone who has nothing to do with my problems just comes around and offers to help?}
{6301}{}{我想知道为什么一个与我的问题无关的人会过来帮忙？}
### {631}{064}{Well, uh... I like politics and currency, you know. Hey, relax! I'll make my benefit. Pretty sure that there's a reward for helping in the main town matters, am I right?}
{631}{064}{嗯。。。我喜欢政治和货币。嘿，放松！我会从中受益。我很确定在主要城镇事务中提供帮助会得到奖励，对吗？}
### {632}{064}{Because I want to make life better. I meant my life, of course. Is there a reward?}
{632}{064}{因为我想让生活变得更好。当然，我指的是我的生命。有奖励吗？}
### {633}{065}{I had a really good talk with Burns. And I've seen how you all live here. Just want to help. Honestly.}
{633}{065}{我和伯恩斯谈得很愉快。我看到你们是如何生活在这里的。只是想帮忙。真的}
### {6302}{}{Glad to see you. Yeah, your help might come in handy...}
{6302}{}{很高兴见到你。是的，你的帮助可能会派上用场。。。}
### {635}{066}{[listen]}
{635}{066}{[听]}


### {640}{}{[Mark carefully studies your face. It takes a really long time. Seems like he is torn between the urge to throw you out and being completely powerless in his situation] Yes. If you can be of any value. So...}
{640}{}{[马克仔细研究了你的脸。这需要很长时间。看起来他在想把你赶出去的冲动和在这种情况下完全无能为力之间左右为难]是的。如果你能有任何价值。所以}
### {641}{066}{[listen]}
{641}{066}{[听]}


### {650}{}{I somehow hardly believe you. But what do I lose? Okay then...}
{650}{}{不知怎么的，我几乎不相信你。但我失去了什么？好吧。。。}
### {651}{066}{[listen]}
{651}{066}{[听]}


### {660}{}{Are you already acquantained with my son Daniel?}
{660}{}{你已经和我儿子丹尼尔交往了吗？}
### {661}{067}{Yes}
{661}{067}{对}
### {662}{071}{No}
{662}{071}{不}
### {663}{071}{No [lie]}
{663}{071}{不[撒谎]}
### {664}{067}{Yes [lie]}
{664}{067}{是[谎言]}


### {670}{}{And what do you think about him?}
{670}{}{你觉得他怎么样？}
### {671}{068}{He's okay.}
{671}{068}{他没事。}
### {672}{068}{He's... kind of stupid.}
{672}{068}{他。。。有点愚蠢。}
### {673}{068}{I wouldn't trust him with cleaning the toilet, let alone managing the town...}
{673}{068}{我不会相信他会打扫厕所，更不用说管理这个小镇了。。。}
### {674}{068}{Still don't have an opinion.}
{674}{068}{仍然没有意见。}


### {680}{}{[Mark is silent. Probably thinks about what to say] Ah, well, doesn't matter. It's not about him.}
{680}{}{[马克沉默了。可能在想该说什么]啊，好吧，没关系。这与他无关。}
### {681}{069}{[listen]}
{681}{069}{[听]}


### {690}{}{The thing is that lately, I feel... shitty. Doc says I don't have much time left. So, I need to present a new future leader to the community. According to tradition, it should be my son, but... Let's put it like this - I don't think he is ready. And more so - I don't think he is capable of leading the community to a better future, instead, he's more likely to put an end to everything we achieved here. You will understand me better when you'll talk to him.}
{690}{}{问题是，最近，我觉得。。。糟透了。医生说我剩下的时间不多了。因此，我需要向社区介绍一位新的未来领导者。按照传统，应该是我的儿子，但是。。。让我们这样说吧——我认为他还没有准备好。更重要的是，我认为他没有能力带领社区走向更美好的未来，相反，他更有可能结束我们在这里取得的一切。当你和他谈话时，你会更了解我的。}
### {691}{070}{So what is needed from me?}
{691}{070}{那么，我需要什么呢？}


### {700}{}{You have a fresh eye. Talk to Daniel, try to assess what's going on in his head. Maybe there's also some point in talking with Burns about Daniel first. Or maybe to his friend, Arsene. And talk to Sam, he's his grandfather and spends much more time with him. Do not talk to Lucy though. She'll try to put things in a better light, stuff like that. We don't need it. Get back to me when you'll find out what's what.}
{700}{}{你的眼光很新鲜。和丹尼尔谈谈，试着评估他脑子里在想什么。也许先和伯恩斯谈谈丹尼尔也有意义。或者可能是给他的朋友，阿森。和山姆谈谈，他是他的爷爷，和他在一起的时间要多得多。不过不要和露西说话。她会尽量把事情放在一个更好的角度，诸如此类的事情。我们不需要它。当你发现是什么的时候给我回电话。}
### {701}{999}{Okay. Be right back.}
{701}{999}{可以马上回来。}


### {710}{}{If you want to be of any help, you'll have to meet him...}
{710}{}{如果你想得到任何帮助，你必须去见他。。。}
### {711}{069}{[listen]}
{711}{069}{[听]}


### {720}{}{When you're done, meet me here.}
{720}{}{等你做完，在这里等我。}
### {721}{999}{Okay.}
{721}{999}{可以}


### {730}{}{It's great. So how is it?}
{730}{}{太棒了。那是怎么回事？}
### {731}{074}{Mark, I wouldn't say "it's great". I have pretty bad news for you. Uh... You might want to sit, maybe... Because your son... Is not quite your son.}
{731}{074}{马克，我不会说“太棒了”。我有个坏消息要告诉你。嗯你可能想坐着，也许。。。因为你的儿子。。。不完全是你的儿子。}
### {732}{095}{Mark, he is a mess. Maybe this is none of my business, but... I think he is not ready.}
{732}{095}{马克，他一团糟。也许这不关我的事，但是。。。我认为他还没有准备好。}


### {740}{}{What? [he doesn't move and just stares at you]}
{740}{}{什么[他一动不动，只是盯着你看]}
### {741}{075}{He is Lucy's son, alright. But not from you. That's how it is.}
{741}{075}{他是露西的儿子，好吧。但不是来自你。事情就是这样。}


### {750}{}{[Mark breath becomes very heavy, he sits down, covering his face]}
{750}{}{[马克的呼吸变得非常沉重，他坐了下来，遮住了脸]}
### {751}{076}{[wait silently]}
{751}{076}{[静静地等待]}
### {752}{094}{Mark... Are you alright?}
{752}{094}{做记号你还好吗？}
### {753}{094}{Mark... You ain't helping the situation. The problem needs to be solved.}
{753}{094}{做记号你帮不了什么忙。这个问题需要解决。}


### {760}{}{Okay. Okay... About Lucy... I will deal with her later. As for now... I need to put an end to this successor thing... I can't die without managing the situation. I have no right to do so!}
{760}{}{可以可以关于露西。。。我稍后会处理她的。就目前而言。。。我需要结束这个继承人的事情。。。如果不控制局势，我死不了。我无权这样做！}
### {761}{077}{[listen silently]}
{761}{077}{[静静地听着]}


### {7701}{}{I think I have an idea about what to do. While you've been busy helping our town, I did some research. And all of my people have a very good opinion about you. So, here's the thing - are you ready to lead the NWO?}
{7701}{}{我想我知道该怎么办了。当你一直忙于帮助我们镇的时候，我做了一些研究。我所有的人都对你有很好的评价。那么，事情是这样的——你准备好领导NWO了吗？}
### {771}{078}{Oh wow... Mark, it is a huge honor for me. But - how? Don't you inherit the leader position by birth?}
{771}{078}{哦，哇。。。马克，这对我来说是一个巨大的荣誉。但是——怎么做呢？你不是天生就继承了领导的职位吗？}
### {772}{086}{That would be, uh... A very generous proposition... But think - what kind of leader am I? I have many things to do outside of NWO. I won't be here often... All in all, I don't think I'm the best option for this job.}
{772}{086}{那将是，呃。。。一个非常慷慨的提议。。。但想想看，我是一个什么样的领导者？除了NWO，我还有很多事情要做。我不会经常在这里。。。总而言之，我认为我不是这份工作的最佳人选。}
### {773}{093}{Me? Sure! Are there girls and booze attached to it?}
{773}{093}{我当然这里有女孩和酒吗？}
### {7702}{}{I think I have an idea about what to do. I suppose my people will not be very happy about it, but I'm out of other options. Sam... He was a leader here once. He knows how to run the town. He is willing to sacrifice himself for the needs of NWO's people. But he can't be put into a leader's position just like this. [Mark stares at you - probably waiting for some reaction]}
{7702}{}{我想我已经知道该怎么办了。我想我的员工对此不会很高兴，但我别无选择。山姆…他曾经是这里的领导人。他知道如何管理这个城市。他愿意为了NWO人民的需要而牺牲自己。但他不能像这样被置于领导者的地位。[马克盯着你看——可能是在等待反应]}
### {774}{092}{Let me guess. I'm gonna help?}
{774}{092}{让我猜猜看。我要帮忙吗？}
### {775}{088}{And?}
{775}{088}{和}
### {776}{088}{But what's the problem? Can't you just put him in or put him out?}
{776}{088}{但问题出在哪里？你就不能把他放进去还是放出去？}


### {780}{}{Yeah. By the right of birth, exactly that. Still, I have currently no heirs, after everything that happened. But I still can adopt, right? I can adopt you and make you my successor. The townspeople will be glad, considering their attitude about you and Daniel. So... What do you say?}
{780}{}{是 啊根据出生权，正是这样。尽管如此，在发生了这一切之后，我目前没有继承人。但我还是可以领养的，对吧？我可以收养你，让你成为我的接班人。考虑到他们对你和但以理的态度，城里人会很高兴的。那么…你怎么说？}
### {781}{079}{That is quite sudden, I must say... Probably could work... Yeah, this is a great idea!}
{781}{079}{那太突然了，我必须说。。。也许可以。。。是的，这是个好主意！}
### {782}{079}{Yes. I accept.}
{782}{079}{对我接受。}
### {783}{086}{But what I would do in this position? I mean... I'd have to deal with everything you deal with... And I know jack shit about anything of it.}
{783}{086}{但在这个职位上我会怎么做？我的意思是。。。我必须处理你处理的一切。。。我对这一切都很了解。}
### {784}{087}{That is... Very kind of you. But... I think that for your society would be better if the leader position would be taken by someone else. Sam, for example. He has been a leader, right? He is experienced...}
{784}{087}{你真是太好了。但是我认为，如果领导职位由其他人担任，对你们的社会来说会更好。比如山姆。他一直是个领导者，对吧？他经验丰富。。。}


### {790}{}{Very good. I'm glad about your decision. I have to brief you about activities, do the adoption part, and so on. There's a lot of work to do, but now I also have one problem less... So - I'd like you to ask all your questions of interest right now.}
{790}{}{很好。我很高兴你的决定。我必须向你简要介绍活动，做收养的部分，等等。有很多工作要做，但现在我也少了一个问题。。。所以，我希望你现在就提出你感兴趣的所有问题。}
### {791}{080}{[continue]}
{791}{080}{[持续]}


### {800}{}{[Mark still watches you with a studying look. It seems like he already assessed every wrinkle and pore on your face.]}
{800}{}{[马克仍然用一副认真的样子看着你。他似乎已经评估了你脸上的每一条皱纹和毛孔。]}
### {801}{081}{What responsibilities would I carry? You've been preparing for this since childhood... I, on the other hand, know nothing about how you do things here...}
{801}{081}{我将承担什么责任？你从小就在为这个做准备。。。I、 另一方面，对你在这里的所作所为一无所知。。。}
### {802}{082}{When should I start? }
{802}{082}{我什么时候开始上班？}
### {803}{083}{About the adoption... How one does it, anyway?}
{803}{083}{关于领养。。。无论如何，一个人是怎么做到的？}
### {804}{084}{I see. In general, I have no more questions. Maybe you want to say some words of encouragement?}
{804}{084}{我明白了。总的来说，我没有更多的问题了。也许你想说些鼓励的话？}


### {810}{}{Hmm... You'll manage. Sam and Burns will be there for you with their advice if you need it. Generally, the leader defines external and internal politics, from dividing the revenue and supplies to the war duties and trade activities. The responsibility is pretty big, but don't be afraid - I'm not going to the cemetery so soon. So I will provide help as long as I can, slowly introducing you to our key matters. Anyway, everyone else will already consider you as a leader. I need a couple more days to finish some preparations and announce my successor. Don't be surprised if people will suddenly start to pester you with their requests.}
{810}{}{嗯…你会搞定的。如果你需要，Sam和Burns会为你提供建议。一般来说，领导人会定义外部和内部政治，从分配收入和物资到战争职责和贸易活动。责任很大，但别害怕，我不会这么快就去墓地。因此，我将尽我所能提供帮助，慢慢地向您介绍我们的关键事项。不管怎样，其他人都会认为你是领导者。我还需要几天时间来完成一些准备工作并宣布我的继任者。如果人们突然开始用他们的要求纠缠你，不要感到惊讶。}
### {811}{080}{Okay, I understood that part. Still, I have some questions...}
{811}{080}{好吧，我理解那部分。尽管如此，我还是有一些问题。。。}
### {812}{084}{I see. In general, I have no more questions. Maybe you want to say some words of encouragement?}
{812}{084}{我明白了。总的来说，我没有更多的问题了。也许你想说些鼓励的话？}


### {820}{}{You won't have to deal with town businesses right away. First I will fill you in details. So, for some time you will be more like playing a role of a symbol of a new beginning for NWO. With the teaching part, we will deal later, I'll keep you posted. It should happen right after I will finish with my wife and... Son.}
{820}{}{你不必马上处理城镇事务。首先，我将向您详细介绍。因此，在一段时间内，你将更像是NWO新开始的象征。关于教学部分，我们稍后处理，我会随时通知您。这应该发生在我和我的妻子和。。。儿子}
### {821}{080}{Okay, I understood that part. Still, I have some questions...}
{821}{080}{好吧，我理解那部分。尽管如此，我还是有一些问题。。。}
### {822}{084}{I see. In general, I have no more questions. Maybe you want to say some words of encouragement?}
{822}{084}{我明白了。总的来说，我没有更多的问题了。也许你想说些鼓励的话？}


### {830}{}{Oh, it's nothing difficult. I'll do everything myself, it's just a few formalities. If it wasn't about putting you in a leader's seat, we would've just told the people and were done with it.}
{830}{}{哦，没什么难的。我会自己做每件事，这只是一些手续。如果不是让你坐在领导的位置上，我们只会告诉人民，并就此结束。}
### {831}{080}{Okay, I understood that part. Still, I have some questions...}
{831}{080}{好吧，我理解那部分。尽管如此，我还是有一些问题。。。}
### {832}{084}{I see. In general, I have no more questions. Maybe you want to say some words of encouragement?}
{832}{084}{我明白了。总的来说，我没有更多的问题了。也许你想说些鼓励的话？}


### {840}{}{Words? [Mark smiles for a brief moment] You will get so many of them from me that you'll be tired... But I have something better. [he puts out and hands to you what seems to be a very old book. It is covered with a thick layer of dirt and loads of patches]. This is one of the most important things in NWO. A collection of every leader's notes... Also known as the encyclopedia. As you are now a leader of NWO, I suggest you take a look into it. In any case, you will be responsible for its safety and actuality.}
{840}{}{言语？[马克微笑了一下]你会从我那里得到很多，你会累的。。。但我有更好的东西。[他拿出一本看起来很旧的书递给你。上面覆盖着厚厚的一层污垢和大量的补丁]。这是NWO最重要的事情之一。每一位领导人的笔记集。。。也被称为百科全书。你现在是NWO的领导，我建议你去调查一下。无论如何，你将对它的安全和现实负责。}
### {841}{085}{Thanks, Mark. }
{841}{085}{谢谢，马克。}


### {850}{}{[he nods] Now, I have a lot of work to do. Come around in a few days. We'll talk.}
{850}{}{[他点点头]现在，我有很多工作要做。过几天再来。我们来谈谈。}
### {851}{999}{Okay. Bye, Mark.}
{851}{999}{可以再见，马克。}


### {860}{}{Make a decision first. Do you really think I would make such an offer if I wasn't sure you'll handle it?}
{860}{}{先做决定。如果我不确定你会接受，你真的认为我会提出这样的报价吗？}
### {861}{079}{Yes... Yes, okay. I accept!}
{861}{079}{对是的，好的。我接受！}
### {862}{087}{That is... Very kind of you. But... I think that for your society would be better if the leader position would be taken by someone else. Sam, for example. He has been a leader, right? He is experienced...}
{862}{087}{你真是太好了。但是我认为，如果领导职位由其他人担任，对你们的社会来说会更好。比如山姆。他一直是个领导者，对吧？他经验丰富。。。}


### {870}{}{[Mark starts to think. He put his hand on a chin, scratching it]. Sam... Yeah. I mostly agree with you, but his reputation in this town is... not very good. I'm going to need some help with this.}
{870}{}{[马克开始思考。他把手放在下巴上，抓了抓]。山姆…是的。我基本上同意你的看法，但他在城里的名声……不是很好。我需要一些帮助。}
### {871}{088}{Sure, no problem, Mark. What kind of help are we talking about?}
{871}{088}{当然，没问题，马克。我们在谈论什么样的帮助？}
### {872}{088}{As if it could be anything else... Okay, what help?}
{872}{088}{好像它可以是其他任何东西。。。好的，有什么帮助吗？}


### {880}{}{Do you know what elections are? [Mark throws a quick look at you and goes on, making the question rhetorical] That's when people of the community choose their leader from a set of candidates. And we don't have elections here. The position is inherited, like under the monarchy. Still, to stay in the lead you need to not only be a selfless manager, ready to make sacrifices for the community. You also need the people to know about your good deeds and plans for the town. And, most importantly, they should like you. Sounds pretty strange, but that's how it is.}
{880}{}{你知道什么是选举吗？[马克快速看了你一眼，然后继续说，让这个问题变得有修辞意义]这就是社区的人们从一组候选人中选择他们的领导人的时候。我们这里没有选举。这个职位是继承下来的，就像在君主制时期一样。尽管如此，要保持领先地位，你不仅需要成为一名无私的管理者，还要准备好为社区做出牺牲。你还需要人们了解你的善举和对小镇的计划。而且，最重要的是，他们应该喜欢你。听起来很奇怪，但事实就是这样。}
### {881}{089}{Uhhhh - soooo?}
{881}{089}{嗯-苏？}


### {890}{}{To participate in elections you need to set up an election campaign. Basically, that's where the candidate tells everyone how great he is. So - the people here must be reminded about Sam's good deeds - and persuaded that his brains are not completely rotten. That he will make for a great leader.}
{890}{}{要参加选举，你需要建立一个竞选活动。基本上，这就是候选人告诉每个人他有多伟大的地方。所以，必须提醒这里的人们萨姆的善行，并说服他们相信他的大脑并没有完全腐烂。他将成为一位伟大的领袖。}
### {891}{090}{And how the hell do you think I'm going to do that?}
{891}{090}{你以为我会怎么做？}


### {900}{}{I would be seen as biased, if I'd start delivering speeches about Sam. And it shouldn't look like I'm imposing my opinion. I think it's a generally bad idea to say "let's put Sam in the leader's shoes". The message should be more subtle. Try to make it look like people made this decision themselves.}
{900}{}{如果我开始发表关于山姆的演讲，我会被认为是有偏见的。而且看起来我不应该把我的观点强加给别人。我认为说“让我们设身处地为领导着想”通常是个坏主意。这个信息应该更加微妙。试着让它看起来像是人们自己做出的决定。}
### {901}{091}{Should I talk to every resident here? Really?}
{901}{091}{我应该和这里的每一位居民谈谈吗？真正地}


### {910}{}{No, not to everyone. Only to the ones that folk listens to. Talk to Juan, Cyren, Flint, Owen, Burns, and Hinder.}
{910}{}{不，不是对所有人。只听那些人们听的。和胡安、塞伦、弗林特、欧文、伯恩斯和辛德谈谈。}
### {911}{999}{Well... Okay. I'll try to do something with it. Will be back when Sam's reputation is equal to one of the saints, or something.}
{911}{999}{好可以我会试着用它做点什么。等山姆的名声和其中一个圣人差不多的时候，我会回来的。}

### {920}{}{One more thing, if you are worried about the reward - there will be, once you're done with this. }
{920}{}{还有一件事，如果你担心回报，一旦你完成了这件事，就会有回报。}
### {921}{088}{Well... Okay. Tell me, what can I do.}
{921}{088}{好可以告诉我，我能做什么。}


### {930}{}{Still joking around? Tell me straight - yes or no.}
{930}{}{还在开玩笑吗？直截了当地告诉我——是或否。}
### {931}{078}{Yes. But I still don't get it - you have an inheritance of leader's position here, right?}
{931}{078}{对但我还是不明白——你继承了这里的领导人职位，对吧？}
### {932}{087}{Sounds promising, yes... but I don't think this is where I should belong. It's like dressing me as a stripper and putting me on the pole. Why don't you... Why don't you put Sam in this position?}
{932}{087}{听起来很有希望，是的。。。但我认为这不是我应该去的地方。这就像把我打扮成脱衣舞娘，然后把我放在杆子上。你为什么不。。。你为什么不把山姆放在这个位置上？}


### {940}{}{I-... Ye-... Hold on a second...}
{940}{}{我。。。叶。。。等一下。。。}
### {941}{076}{[wait for Mark to calm down]}
{941}{076}{[等马克冷静下来]}


### {950}{}{Ohh... As sad as it is - everyone thinks that. But he is young! Wind in the head. I am sure he will become wiser with time.}
{950}{}{哦。。。尽管这很可悲，但每个人都这么认为。但他还年轻！头上有风。我相信他会随着时间的推移变得更聪明。}
### {951}{096}{But still. He seriously thinks that when put in the leader's position, he'll conquer the whole Radius. He is ready to starve your neighboring communities to death. I don't think he can be dissuaded.}
{951}{096}{但仍然如此。他认真地认为，当他被放在领导的位置上时，他会征服整个半径。他已经准备好饿死你们邻近的社区了。我认为他不能被劝阻。}


### {960}{}{Listen... Talk to him. Dig a little deeper. I'm sure he is not completely lost. Please.}
{960}{}{听和他谈谈。挖得更深一点。我确信他并没有完全迷失方向。请}
### {961}{999}{As you say, Mark. But I'm starting to get tired from all the hassle with your relatives... [leave]}
{961}{999}{正如你所说，马克。但我开始厌倦了和你亲戚的麻烦。。。[离开]}
### {962}{999}{Ugh, yeah. [turn around and walk away]}
{962}{999}{啊，是的。[转身走开]}
### {963}{999}{[Sigh, grin, nod your head, and go away]}
{963}{999}{[叹气，咧嘴笑，点点头，然后走开]}


### {970}{}{Yes?}
{970}{}{对}
### {971}{099}{Those who you pointed on are ready to support Sam. But they warned me that there will be a lot of dissatisfaction with the decision.}
{971}{099}{你指出的那些人已经准备好支持萨姆了。但他们警告我，人们会对这个决定感到非常不满。}


### {980}{}{Yes?}
{980}{}{对}
### {981}{074}{Mark, I have pretty bad news for you. Uh... You might want to sit, maybe... Because your son... Is not quite your son.}
{981}{074}{马克，我有个坏消息要告诉你。嗯你可能想坐着，也许。。。因为你的儿子。。。不完全是你的儿子。}
### {982}{100}{I would really want to tell you that it's all good... But your son is absolutely not ready for this. More so, he pretended to care about your demise and tried to act like he's ready to learn when put in power. Long story short, he just waits for you to kick the bucket.}
{982}{100}{我真的很想告诉你一切都很好。。。但你儿子绝对没有做好准备。更重要的是，他假装关心你的死，并试图表现得像他掌权后准备学习一样。长话短说，他只是在等你把桶踢开。}
### {983}{101}{Daniel promised me to become more sensible. He told me he didn't know that it would be so soon for him to fill this position. He is ready to learn.}
{983}{101}{丹尼尔答应我要变得更理智。他告诉我，他不知道自己这么快就能胜任这个职位。他已经准备好学习了。}


### {990}{}{Good. I already spoke to him. It's going to be a hard time, so I have another request. [he puts out and hands to you what seems to be a very old book. It is covered with a thick layer of dirt and loads of patches] This is called the encyclopedia. Probably in the future, it may be the basis for writing our history. It was passed from one leader to another. I'm afraid it can be lost because of the problems with succession. So I ask you to keep it. Return it when there's a better situation here. And, of course, here's the reward... [Mark gives you a small bag of batteries]. I've got a lot of work to do, so excuse me. And thank you for everything.}
{990}{}{好的我已经和他谈过了。这将是一个艰难的时刻，所以我有另一个请求。[他拿出一本看起来很旧的书递给你。上面覆盖着厚厚的一层污垢和大量的补丁]这就是百科全书。也许在未来，它可能是书写我们历史的基础。它是从一位领导人传给另一位领导人的。恐怕它可能会因为继承问题而丢失。所以我要求你保留它。当这里的情况好转时，把它还回来。当然，这是奖励。。。[马克给你一小袋电池]。我有很多工作要做，对不起。谢谢你所做的一切。}
### {991}{999}{Bye, Mark. Good luck.}
{991}{999}{再见，马克。祝你好运}


### {1000}{}{Damn... I am so tired of it. Okay... Looks like... Looks like I have no other choice... So it's Sam. Sam is the only one who can lead the town...}
{1000}{}{该死我已经厌倦了。好吧。。。看起来。。。看来我别无选择。。。所以是山姆。山姆是唯一一个能领导这个小镇的人。。。}
### {1001}{088}{[keep listening]}
{1001}{088}{[继续听]}


### {1010}{}{That's... That's wonderful! Even better than I expected! [Mark smiles, but looks like he is staring into emptiness] This looks very promising. [he focuses on you] But there will definitely be problems... It's going to be a hard time, so I have another request. [he puts out and hands to you what seems to be a very old book. It is covered with a thick layer of dirt and loads of patches] This is called the encyclopedia. Probably in the future, it may be the basis for writing our history. It was passed from one leader to another. I'm afraid it would be lost, because no matter what my son says - he is not very reliable. So I ask you to keep it. Return it when there's a better situation here. And, of course, here's the reward... [Mark gives you a small bag of batteries]. I've got a lot of work to do, so excuse me. And thank you for everything.}
{1010}{}{那是。。。太棒了！比我预想的还要好！[马克微笑着，但看起来他正凝视着空虚]这看起来很有希望。[他专注于你]但肯定会有问题。。。这将是一个艰难的时刻，所以我有另一个请求。[他拿出一本看起来很旧的书递给你。上面覆盖着厚厚的一层污垢和大量的补丁]这就是百科全书。也许在未来，它可能是书写我们历史的基础。它是从一位领导人传给另一位领导人的。我担心它会丢失，因为不管我儿子怎么说，他都不是很可靠。所以我要求你保留它。当这里的情况好转时，把它还回来。当然，这是奖励。。。[马克给你一小袋电池]。我有很多工作要做，对不起。谢谢你所做的一切。}
### {1011}{999}{Bye, Mark. Good luck.}
{1011}{999}{再见，马克。祝你好运}


### {1020}{}{Yes. I know everything about it - I am its current keeper. The encyclopedia shall not be issued. And access to it can be given only to those NWO's residents who have proven their loyalty and goodwill to the community. It contains the knowledge and expertise of all NWO's leaders. Make something of yourself here and we will talk about it.}
{1020}{}{对我知道它的一切——我是它现在的饲养员。百科全书不予发行。只有那些已经证明对社区忠诚和善意的NWO居民才能使用它。它包含了NWO所有领导人的知识和专业知识。在这里做点什么，我们会讨论的。}
### {1021}{031}{I see... Then I have a couple of other questions.}
{1021}{031}{我明白了。。。然后我还有几个其他问题。}


### {1030}{}{Everything is quite alright, thank you. You know, a lot of work, as usual. Seems like it never ends...}
{1030}{}{一切都很好，谢谢。你知道，像往常一样，有很多工作要做。似乎它永远不会结束。。。}
### {1031}{104}{How's Daniel doing?}
{1031}{104}{丹尼尔怎么样？}
### {1032}{105}{How is Sam?}
{1032}{105}{山姆怎么样？}
### {1033}{106}{When should I start fulfilling my role as a leader?}
{1033}{106}{我应该什么时候开始履行我作为领导者的职责？}
### {1034}{107}{How are you? How is your condition?}
{1034}{107}{你好吗你的情况如何？}
### {1035}{999}{Okay. I see you are pretty busy... So long then. I'll come by.}
{1035}{999}{可以我看你很忙。。。那就太久了。我会过来的。}


### {1040}{}{Studying, just as he promised. Some rumors are going that he still hangs out with Arsene, although I forbade it. But while everything looks so good - I prefer not to touch this topic very often.}
{1040}{}{学习，正如他承诺的那样。有传言说他仍然和阿森在一起，尽管我禁止这样做。但是，虽然一切看起来都很好，但我不想经常提及这个话题。}
### {1041}{107}{And what about you? Think you can handle tutoring him before your time comes?}
{1041}{107}{你呢？你认为你能在时机成熟之前辅导他吗？}
### {1042}{999}{Okay. I see you are pretty busy... So long then. I'll come by.}
{1042}{999}{可以我看你很忙。。。那就太久了。我会过来的。}


### {1050}{}{The folks are not happy, some just spit out the poison... They say that "all that's left is for Mark to become a ghoul, then he and Sam could rule here forever, changing places over time, until other people die out..." [he sighs]. So upsetting to hear that, especially after everything I've given to this town. I hope this is temporary. Our people are conservative. Not much could be done about it, I suppose.}
{1050}{}{人们并不高兴，有些人只是吐出毒药。。。他们说，“剩下的就是马克成为一个食尸鬼，然后他和山姆可以永远统治这里，随着时间的推移改变地方，直到其他人死去……”（他叹了口气）。听到这个消息我很难过，尤其是在我为这个小镇付出了一切之后。我希望这是暂时的。我们的人民是保守的。我想对此无能为力。}
### {1051}{107}{What about you? Does this malicious talk have any influence? It's not going to put you into an early grave, is it?}
{1051}{107}{你呢？这种恶意言论有什么影响吗？这不会让你过早地陷入坟墓，是吗？}
### {1052}{999}{I see. Be strong. I'll come by later.}
{1052}{999}{我明白了。要坚强。我稍后再来。}


### {1060}{}{I don't know yet. I have some problems to solve. When I'm done - I'll let you know. For your safety, do not talk much about you being a leader of this community outside of this place. It could lead to some consequences, for example - prevent you from acquiring some good trade deals. Or it could even lead to some robbers being more interested in your person than usual. And one more thing: I announced you as my successor to some of our people. Don't be surprised if they will suddenly start to pester you with requests..}
{1060}{}{我还不知道。我有一些问题要解决。等我做完了，我会告诉你的。为了你的安全，不要过多地谈论你是这个地方以外这个社区的领导者。例如，这可能会导致一些后果——阻止你获得一些好的贸易协议。或者这甚至可能导致一些劫匪对你的人比平时更感兴趣。还有一件事：我宣布你为我的一些人的继任者。如果他们突然开始纠缠你提出要求，不要感到惊讶。。}
### {1061}{107}{Okay, but what about you? This amount of work is not going to put you into an early grave, is it?}
{1061}{107}{好吧，但你呢？这么多的工作不会让你早死，是吗？}
### {1062}{999}{Okay. I see you are pretty busy... So long then. I'll come by.}
{1062}{999}{可以我看你很忙。。。那就太久了。我会过来的。}


### {1070}{}{I'm good. Still going. Walking by myself, not being fed with a spoon. No nanny is put to watch me.}
{1070}{}{我很好。还在继续。独自行走，没有人用勺子喂养。没有保姆照看我。}
### {1071}{999}{Okay. I see you are pretty busy... So long then. I'll come by.}
{1071}{999}{可以我看你很忙。。。那就太久了。我会过来的。}

### {1080}{}{Skeet? That thief of our canned food? What do you want to tell me about him?}
{1080}{}{斯基特？那个偷我们罐头食品的贼？你想告诉我关于他的什么？}
### {1081}{109}{He had nothing to do with stealing! The canned food has been eaten by an old Chimera. I killed it.}
{1081}{109}{他与偷窃无关！罐头食品被一个老奇美拉吃掉了。我杀了它。}
### {1082}{999}{Nothing... Except I think he is innocent here. I will find a way to prove it.}
{1082}{999}{没有什么只是我认为他在这里是无辜的。我会想办法证明这一点。}
### {1083}{}{Well, that fits. Our watchmen detected an old Chimera in our warehouse. It's so good that no one got hurt... As for Skeet - of course, we'll release him. And... Yeah, we owe him an apology.}
{1083}{}{这很合适。我们的值班人员在我们的仓库里发现了一个旧的奇美拉。这太好了，没有人受伤。。。至于斯基特，我们当然会释放他。和是的，我们应该向他道歉。}
### {1084}{999}{Great. Glad that justice was served.}
{1084}{999}{太棒了很高兴正义得到伸张。}

### {1090}{}{So it's true. Amazing! When I was told about that dead Chimera - I couldn't believe it. And turns out it's you who killed it! It's so good that no one got hurt. You did a big favor to us! As for Skeet - of course, we'll release him. And... Yeah, we owe him an apology.}
{1090}{}{所以这是真的。太神了当我被告知那个死去的奇美拉时，我简直不敢相信。原来是你杀了它！太好了，没有人受伤。你帮了我们很大的忙！至于斯基特，我们当然会释放他。和是的，我们应该向他道歉。}
### {1091}{109}{Great. Glad that justice was served.}
{1091}{109}{太棒了很高兴正义得到伸张。}
