##############################
#???????: ???
#???: ????
#??????? ????????: ??????????? ??????
#???? ????????: 18.05.2014
##############################
#??? ???? "????? 2207"
#????? "Rainman" ????????
##############################
#
#???????? ????????
#
# ?? ??????????
### {1}{}{You see a man with a huge cleaver.}
{1}{}{你看到一个男人拿着一把巨大的切肉刀。}
### {2}{}{A big man with an eerily happy smile, wearing a blood-stained apron. }
{2}{}{一个大个子男人，带着诡异的幸福微笑，穿着血迹斑斑的围裙。}
#
# ????? ??????????
### {3}{}{You see Owen.}
{3}{}{你看到欧文了。}
### {4}{}{It seems like his sledgehammer has even more stains from splattered brains than last time.}
{4}{}{看起来他的大锤上溅满了大脑的污渍比上次还要多。}
#
#????? ?????????? ??????
#
#Node001
### {10}{}{[You see a very big man. His face never saw a razor, and his butcher's apron has two colors - of fresh blood and dried blood. You try to say something, but he greets you first] Hello. Have we met before?}
{10}{}{[你看到一个很大的男人。他的脸上从来没有见过剃刀，他的屠夫围裙有两种颜色——新鲜血液和干血液。你想说点什么，但他先向你打招呼]你好。我们以前见过面吗？}
### {11}{002}{My name is }
{11}{002}{我的名字是}
### {12}{002}{. And you are a local butcher, I suppose? }
{12}{002}{。我想你是当地的屠夫吧？}
### {13}{999}{No. I think you took me for someone else. I should go.}
{13}{999}{不，我想你把我当成别人了。我该走了。}
### {14}{999}{No. Somehow, I don't feel like getting acquainted with you. }
{14}{999}{不，不知怎么的，我不想和你认识。}

#Node002
### {20}{}{Yes, I'm Owen, the cattle slaughterer. I put Lavash to sleep with my sledgehammer, debone their carcasses, and pass them further along the chain of technological progress, so to say. [he wipes sweat from his forehead with a bloody hand] Phew... So, what do you want, }
{20}{}{是的，我叫欧文，那个屠宰牛的人。可以说，我用大锤让熔岩入睡，给它们的尸体去骨，然后沿着技术进步的链条继续前行。[他用一只沾满鲜血的手擦去额头上的汗水]哇。。。那么，你想要什么，}
### {21}{}{? Come on, ask!}
{21}{}{？来吧，问问！}
### {22}{004}{Tell me more about what you do here.}
{22}{004}{告诉我更多关于你在这里做什么的信息。}
### {23}{005}{Tell me about the local community.}
{23}{005}{告诉我当地社区的情况。}
### {24}{999}{I have nothing for now, Owen. Just coming by. See you later.}
{24}{999}{我现在什么都没有，欧文。来吧，回头见。}

#Node003
### {30}{}{Oh, no big deal, just a dislocated arm. A minor inconvenience. [He twitches in pain] Ooow, goddammit!! I should swing my sledge more careful...}
{30}{}{哦，没什么大不了的，只是手臂脱臼了。一个小小的不便。[他痛苦地抽搐]哦，该死的！！我应该更小心地摆动雪橇。。。}
### {31}{006}{Let me see that...}
{31}{006}{让我看看。。。}
### {32}{999}{I'll try to go ask the doctor for advice. Wait here.}
{32}{999}{我会试着去请教医生。在这里等着。}
### {33}{007}{Why don't you walk yourself to the doctor? Your legs are still alright.}
{33}{007}{你为什么不自己去看医生呢？你的腿还可以。}
### {34}{999}{You see, Owen, it's not very interesting to me. Deal with your problems.}
{34}{999}{你看，欧文，这对我来说不是很有趣。处理好你的问题。}

#Node004
### {40}{}{As I said, my job is to put down an animal and carve the carcass. It's actually not hard - I bash the Lavash's head with that big-ass sledgehammer [he imitates the movement]. Then I take the saw and knives, separate meat from the bone, pick up the steak cuts, and put them away from the rest. A dirty job, I should say, but most of the time - I love it! [he kindly smiles]}
{40}{}{正如我所说，我的工作是放下一只动物并雕刻尸体。这其实并不难——我用那把大屁股大锤砸拉瓦什的头[他模仿动作]。然后我拿起锯子和刀子，把肉和骨头分开，拿起切好的牛排，把它们和其他的分开。我应该说，这是一项肮脏的工作，但大多数时候——我喜欢它！[他和蔼地微笑]}
### {41}{008}{Care to demonstrate? Bashing a head with a sledge must be very spectacular.}
{41}{008}{想演示一下吗？用雪橇撞击头部一定非常壮观。}
### {42}{003}{[carefully observing Owen, you notice that his movements are a little unnatural] Why are you so clumsy with your claw?}
{42}{003}{[仔细观察欧文，你注意到他的动作有点不自然]你为什么用爪子这么笨拙？}
### {43}{005}{Tell me about the local community. }
{43}{005}{告诉我当地社区的情况。}
### {44}{999}{Okay, Owen, I need to go. See you later.}
{44}{999}{好的，欧文，我得走了。回头见。}

#Node005
### {50}{}{Community? What a word! Did you overhear that somewhere? [widely smiling, Owen slightly pushes you in the shoulder with the back of his palm] I'd put it like that - we are a family. New World Order supplies the whole Radius with meat! Without us, everyone would eat each other already.}
{50}{}{社区多好的一个词！你是在什么地方无意中听到的吗？[笑容满面，欧文用手掌轻轻地推你的肩膀]我会这么说的——我们是一家人。新世界秩序为整个Radius供应肉类！如果没有我们，每个人都会互相吃掉。}
### {51}{004}{Remind me about your role in this "family", please.}
{51}{004}{请提醒我你在这个“家庭”中的角色。}
### {52}{999}{This is really great, Owen. Was nice talking to you. Good luck.}
{52}{999}{这真的很棒，欧文。很高兴和你交谈。祝你好运}

#Node006
### {601}{}{[you glance over Owen's hand. Everything seems better than you thought, so, knowingly turning the patient's limb, you successfully put the bone into a joint!] OW! Damn! [Owen pauses and slowly moves his arm. His wide smile becomes even wider] Thanks! You are really good at this medical stuff! You know, }
{601}{}{[你瞥了一眼欧文的手。一切似乎都比你想象的要好，所以，你故意转动病人的肢体，成功地将骨头放入了关节！]哇！该死[欧文停顿了一下，慢慢地移动他的手臂。他灿烂的笑容变得更加灿烂]谢谢！你真的很擅长这种医学！你知道，}
### {602}{}{, your help really came in handy. Here, take this. [Owen hands you a piece of Lavash meat]}
{602}{}{，你的帮助真的派上了用场。给，拿着这个。[欧文递给你一块熔岩肉]}
### {61}{999}{Glad to be of help, Owen. Take care!}
{61}{999}{很高兴能提供帮助，欧文。小心！}
### {603}{}{[You clumsily grab the butcher by the hand, inflicting him severe pain, which leads to you getting punched in the face with an elbow. You are lucky it wasn't hard] God frigging damn it! I told you, it hurts! Are you trying to completely drive me crazy?!}
{603}{}{[你笨拙地抓住屠夫的手，给他带来剧烈的疼痛，导致你的肘部被打在脸上。你很幸运，这并不难]该死的！我告诉过你，很疼！你想把我逼疯吗？！}
### {62}{020}{Okay, I need to think... }
{62}{020}{好吧，我需要思考。。。}
### {63}{007}{Hm... Looks more serious than I thought. Why don't you walk yourself to the doctor? Your legs are still alright.}
{63}{007}{嗯…看起来比我想象的更严重。你为什么不自己去看医生呢？你的腿还可以。}

#Node007
### {70}{}{Don't say it like that! The last thing I need is a problem with my legs. And about the doc, well... We had a little disagreement. It's entirely his fault, by the way! But he won't apologize. As for me, I'm too proud to go to this sadist first. So, don't think it's an option.}
{70}{}{不要那样说！我最不需要的就是我的腿出了问题。关于医生，嗯。。。我们有点意见分歧。顺便说一句，这完全是他的错！但他不会道歉。至于我，我太骄傲了，不能先去找这个虐待狂。所以，不要认为这是一种选择。}
### {71}{011}{What if I bring doc to you, to heal you here?}
{71}{011}{如果我把医生带到你身边，在这里治好你呢？}

#Node008
### {80}{}{Oh, }
{80}{}{哦}
### {81}{}{, Of course, I will gladly show it to you sometime! But I'm done for today. If I put down more, they won't be able to process so much meat and it will be spoiled.}
{81}{}{，当然，我很乐意有时间给你看！但我今天完了。如果我多放一些，他们就无法加工这么多肉，而且会变质。}
### {82}{004}{Remind me about your role in this "family", please.}
{82}{004}{请提醒我你在这个“家庭”中的角色。}

#Node010
### {100}{}{Hello, }
{100}{}{你好}
### {101}{}{! What brings you to me?}
{101}{}{！什么风把你吹到我这里来？}
### {102}{016}{How's your hand?}
{102}{016}{你的手怎么样？}
### {103}{018}{How's the hand? Is everything alright?}
{103}{018}{手怎么样？一切都好吗？}
### {104}{010a}{I was wondering, what do you think about Sam being a new Mayor?}
{104}{010a}{我在想，你觉得山姆当新市长怎么样？}
### {105}{999}{Just came by to say hi. See you!}
{105}{999}{只是过来打个招呼。再见}

#Node010a
### {106}{}{I don't know... [Owen starts to scratch his chin with his huge hand, pondering] Sam is a relative of Mark, right? He will probably do fine as a Mayor. I mean, he already was a fine Mayor... Yes, I think it wouldn't be so bad.}
{106}{}{我不知道。。。[欧文开始用他那只巨大的手抓着下巴沉思]山姆是马克的亲戚，对吧？作为市长，他可能会做得很好。我的意思是，他已经是一位优秀的市长了。。。是的，我想不会那么糟糕。}
### {107}{}{Good, noted. See you then!}
{107}{}{很好，注意到。到时见！}

#Node011
### {110}{}{I won't apologize, that's for sure. But if he'll silently do his job... Then I don't mind.}
{110}{}{我不会道歉，这是肯定的。但如果他能默默地做好自己的工作。。。那我不介意。}
### {111}{999}{Let's settle with that. See you soon.}
{111}{999}{让我们将就吧。再见。}

#Node012
### {120}{}{Really? [Owen even stops smiling in surprise] This sadist said it himself? [suddenly, Hinder steps into the door. He silently approaches Owen, puts his bag on the ground, and starts examining the butcher's arm. Without saying a word.]}
{120}{}{真正地[欧文惊讶地停止了微笑]这个虐待狂是自己说的吗？[突然，辛德走进门。他默默地走近欧文，把包放在地上，开始检查屠夫的手臂。二话不说。]}
### {121}{013}{[wait]}
{121}{013}{[等待]}

#Node013
### {130}{}{[the doctor finishes, proudly turns around, and walks away. Owen looks dazzled] How? How did you talk him into this?}
{130}{}{[医生说完，骄傲地转过身，走开了。欧文看起来眼花缭乱]怎么回事？你是怎么说服他的？}
### {131}{014}{Let it be our little secret. How's the hand?}
{131}{014}{让它成为我们的小秘密。手怎么样？}
### {132}{014}{Diplomacy can take you places - from NWO to Jackals and back. How's the hand?}
{132}{014}{外交可以带你去一些地方——从NWO到Jackals再到回来。手怎么样？}
### {133}{014}{He's a wonderful person, by the way. How's the hand?}
{133}{014}{顺便说一句，他是个了不起的人。手怎么样？}
### {134}{014}{Don't remind me. How's the hand?}
{134}{014}{别提醒我，手怎么样？}

#Node014
### {140}{}{Great. Your help really came in handy. Here, take this. [Owen hands you a piece of Lavash meat]. You are a good man. I wish there were more like you in NWO!}
{140}{}{太棒了你的帮助真的派上了用场。给，拿着这个。[欧文递给你一块熔岩肉]。你是个好人。我希望NWO有更多像你一样的人！}
### {141}{015}{Thanks for your kind words. }
{141}{015}{谢谢你的客气话。}

#Node015
### {150}{}{Thank you, I mean it! [you think that if he hugs you now, it would be your last breath] The Mayor sent for me, so I can't talk to you right now. But come by next time.}
{150}{}{谢谢你，我是认真的！[你认为如果他现在拥抱你，那将是你的最后一口气]市长派人来找我，所以我现在不能和你说话。但下次再来吧。}
### {151}{999}{Okay.}
{151}{999}{可以}
### {152}{999}{Will do, Owen. Bye.}
{152}{999}{会的，欧文。再见}

#Node016
### {160}{}{Shitty, to be honest.}
{160}{}{说实话，希蒂。}
### {161}{012}{I had a talk with Hinder. He agreed to help you. No questions, Just as you asked. He should be here any minute.}
{161}{012}{我和辛德谈过了。他同意帮助你。没有问题，正如你所问。他应该随时在这里。}
### {162}{017}{You know, the doc explained to me how I can help you. Ready to try again?}
{162}{017}{你知道，医生向我解释了我能帮你什么。准备好再试一次了吗？}
### {163}{006}{Okay, let me see it...}
{163}{006}{好吧，让我看看。。。}
### {164}{999}{I'm looking for a way to help you. Now I'm just checking how are you doing. Be back soon.}
{164}{999}{我在想办法帮你。现在我只是想看看你过得怎么样。很快回来。}
### {165}{999}{I'll come by later.}
{165}{999}{我稍后再来。}

#Node017
### {170}{}{[he pauses] Okay, do it. I am pretty sick of this pain already. [you glance over Owen's hand. Everything seems better than you thought, so, knowingly turning the patient's limb, you successfully put the bone into a joint!] OW! Damn! [Owen pauses and slowly moves his arm. His wide smile becomes even wider] Thanks! You are really good at this medical stuff! You know, your help really came in handy. Here, take this. [Owen hands you a piece of Lavash meat]}
{170}{}{[他停顿了一下]好吧，做吧。我已经受够了这种疼痛。[你瞥了一眼欧文的手。一切似乎都比你想象的要好，所以，你故意转动病人的肢体，成功地将骨头放入了关节！]哇！该死[欧文停顿了一下，慢慢地移动他的手臂。他灿烂的笑容变得更加灿烂]谢谢！你真的很擅长这种医学！你知道，你的帮助真的派上了用场。给，拿着这个。[欧文递给你一块熔岩肉]}
### {171}{015}{Glad to help, Owen.}
{171}{015}{很高兴能帮忙，欧文。}
### {172}{015}{Next time don't try to swing around your sledgehammers like drumsticks.}
{172}{015}{下次不要像鼓槌一样在大锤上晃来晃去。}

#Node018
### {180}{}{Perfect. I think I'm able to juggle medium-sized sledgehammers.}
{180}{}{完美的我想我能玩中型大锤。}
### {181}{999}{Neat. Okay, I see you are good. I'll come by later.}
{181}{999}{整洁的好吧，我看到你很好。我稍后再来。}
### {182}{999}{Just don't harm yourself. Okay, I see you are good. I'll come by later.}
{182}{999}{只是不要伤害自己。好吧，我看到你很好。我稍后再来。}


#Node020
### {200}{}{[Owen's face is distorted with pain] Think faster, damn you... Shit!!}
{200}{}{[欧文的脸因疼痛而扭曲]想得快一点，该死的你。。。妈的！！}
### {201}{999}{I'll fix this. Wait here! [leave to ask advice from the doctor]}
{201}{999}{我会解决的。在这里等着！[请假征求医生的意见]}
### {202}{007}{Hm... Looks more serious than I thought. Why don't you walk yourself to the doctor? Your legs are still alright.}
{202}{007}{嗯…看起来比我想象的更严重。你为什么不自己去看医生呢？你的腿还可以。}
