# ????? ?? ??????? ??饭??,
# ??????騥?? ? ???? ?業??
#
# Created by Artem "Rainman" Samoylov
# 19/06/2014
#
# ??? ????
# ?? - ????? ???? ??? ???? ? ???, ????? ??? ??稭???
#
# ?????? 1
### {1}{}{You see some kind of mechanism.} 
{1}{}{你看到了某种机制。}
### {2}{}{You see conveyor machinery.}
{2}{}{你可以看到输送机。}

# ?????? 2
### {3}{}{Looks like this thing does not work.}
{3}{}{看起来这个东西不起作用。}
### {4}{}{Fixed with your hands of gold!}
{4}{}{用你的金子之手修复！}
### {5}{}{No worries, Juan will repair this.}
{5}{}{不用担心，胡安会修复的。}
### {6}{}{Need to make this junk work.}
{6}{}{需要让这些垃圾工作。}

# ??????
### {6}{}{Hrrrmhrm... Something's missing here.}
{6}{}{小时。。。这里少了一些东西。}
### {7}{}{Well now... There should definitely be allocator here..}
{7}{}{现在。。。这里肯定应该有分配器。。}
### {8}{}{Oh! Someone ripped the allocator out, together with parts and cords...}
{8}{}{哦有人把分配器连同零件和电线一起拆了。。。}
### {9}{}{No, Juan will do this job a lot better.}
{9}{}{不，胡安会做得更好。}
### {10}{}{Just a little more... Yes! Now it should work without the needed part!}
{10}{}{再多一点。。。对现在，它应该在没有所需部件的情况下工作！}
### {11}{}{You failed to repair it. Maybe you should try harder.}
{11}{}{你没能修好。也许你应该更努力一点。}
### {12}{}{No, you are too inexperienced with this task.}
{12}{}{不，你对这项任务太缺乏经验了。}
{13}{}{}
{14}{}{}
{15}{}{}
{16}{}{}
{17}{}{}
{18}{}{}
{19}{}{}
{20}{}{}
