##############################
#???????: "?????"
#???: ????
#??????? ????????: ????????-????? ? ????????????? ???
#???? ????????: 42231,????.????
##############################
#??? ???? "????? 2207"
#?????? "Zoomer" ???????
##############################
#
#???????? ????????
#
# ?? ??????????
### {1}{}{You see a tough guard in a decorated leather jacket.}
{1}{}{你看到一个穿着装饰皮夹克的强硬警卫。}
### {2}{}{He tries to make it look like he's in charge.}
{2}{}{他试图让它看起来像是他在掌权。}
#
# ????? ??????????
### {3}{}{You see Jock.}
{3}{}{你看到了乔克。}
### {4}{}{Still as brazen and confident as before.}
{4}{}{仍然像以前一样厚颜无耻和自信。}
#
#????? ?????????? ??????
#
### {10}{}{[The leather jacket has several faded patches on it, some of which are pretty rare, maybe even pre-war. One patch is inscribed with the word "Jock". The owner must really care about this jacket. When you approach, he looks at you as if you were a piece of dirt on his boot.] What the fuck do you want from me? Get the hell off, I'm busy.}
{10}{}{[这件皮夹克上有几块褪色的补丁，有些甚至在战前都很罕见。其中一块补丁上刻着“Jock”字样。主人一定很关心这件夹克。当你走近时，他看着你，好像你是他靴子上的一块泥土。]你他妈的想从我这里得到什么？滚吧，我很忙。}
### {11}{022}{Continue like that, and I'll break your jaw.}
{11}{022}{继续这样下去，我会打断你的下巴。}
### {12}{011}{Richards sent me. For an inspection.}
{12}{011}{理查兹派我来检查。}
### {13}{027}{Where's your uniform, soldier? Why do you look like a cheap whore? Answer, when the senior officer asks a question!!}
{13}{027}{你的制服在哪里，士兵？你为什么看起来像个贱婊子？回答，当高级军官问问题时！！}
### {14}{999}{[leave silently]}
{14}{999}{[默默地离开]}


### {20}{}{[Jock is breathing heavily]}
{20}{}{[乔克呼吸急促]}
### {21}{}{::sniffles::}
{21}{}{::流鼻涕::}
### {22}{}{[Jock tries to pull himself together]}
{22}{}{[乔克试图振作起来]}

### {30}{}{Sir, I'm not done yet, sir!}
{30}{}{先生，我还没做完，先生！}
### {31}{}{[operating plunger with a sad look]}
{31}{}{[带着悲伤的表情操作柱塞]}
### {32}{}{::phhhheeewwww::}
{32}{}{::phhhheeewwww::}

### {40}{}{I hate snitches!!!}
{40}{}{我讨厌告密者！！！}
### {41}{}{[stands at attention]}
{41}{}{[立正]}

### {101}{}{Sir, awaiting for orders, sir!}
{101}{}{长官，等待命令，长官！}
### {102}{033}{Recovered? Good. Give me an update.}
{102}{033}{恢复了吗？好的给我一个最新消息。}
### {103}{999}{Recovered? Good. Stay tight, I'll come by later.}
{103}{999}{恢复了吗？好的请稍等，我稍后再来。}
### {104}{043}{You can prepare your corn cob, soldier. Kelly is coming to you. }
{104}{043}{你可以准备好你的玉米棒，士兵。凯利来找你了。}
### {105}{}{You again? I have everything alright here, you can stop trying to find screw-ups to report captain.}
{105}{}{你又来了？我这里一切都很好，你可以停止找麻烦向船长报告。}
### {106}{025}{I convinced her. Your dream is coming to you.}
{106}{025}{我说服了她。你的梦想就要实现了。}
### {107}{018}{Here's the thing... Your Kelly toppled a wrong vial over herself.}
{107}{018}{事情是这样的。。。你的凯莉把一个错误的瓶子倒在了自己身上。}
### {108}{014}{That's for me to decide. You were saying something about a business. Spill it.}
{108}{014}{那由我来决定。你说的是一桩生意。撒出去。}
### {109}{021}{I see you are not on the best terms with Richards?}
{109}{021}{我看你和理查兹的关系不是很好？}
### {1010}{}{[Jock is cleaning his jacket, whistling something. He looks pleased.] Who we have here? Want to grab a drink? Just let me finish with the jacket - this dumb whore got her blood all over it again.}
{1010}{}{[乔克正在清洗他的夹克，吹着口哨。他看起来很高兴。]我们这里有谁？想喝一杯吗？让我说完这件夹克吧——这个愚蠢的妓女又浑身是血。}
### {1011}{023}{Can't get enough of Kelly now, I see?}
{1011}{023}{我明白了，凯利现在受够了吗？}
### {1012}{999}{Maybe later. See you around, Jock.}
{1012}{999}{也许以后吧。再见，乔克。}
### {1013}{999}{Don't twitch, I was just coming by. At ease, sergeant.}
{1013}{999}{别急，我刚过来。放心，中士。}

### {110}{}{[Hearing captain's name, he gets pale] I... What's the problem? Everything's cool! Tell captain Richards not to worry, sergeant Jock knows his stuff! And, uh... Sorry for that, seriously. Let's start again, maybe? I'm Jock, the sergeant of security. [he extends a hand]}
{110}{}{[听到队长的名字，他脸色苍白]我……怎么了？一切都很酷！告诉理查兹上尉别担心，乔克中士知道他的事！而且，呃。。。很抱歉，说真的。也许我们重新开始吧？我叫乔克，是保安警长。[他伸出一只手]}
### {111}{012}{[ignore his hand] Sergeant? Seriously?}
{111}{012}{[无视他的手]中士？认真地}
### {112}{013}{[shake his hand] Okay, nevermind. I see it's definitely quiet around here.}
{112}{013}{[和他握手]好的，没关系。我看这里绝对很安静。}

### {120}{}{[he tucks his lips and starts to clean a spot from the jacket] I appointed myself. And no one seems to mind. Even captain Richards. Besides, who watches the order around here and coaches the guys? That's right, good old Jock.}
{120}{}{[他收起嘴唇，开始清理夹克上的一个斑点]我指定了自己。似乎没有人介意。就连理查兹船长也不例外。此外，谁在这里看着秩序并指导这些人？没错，老乔克。}
### {121}{022}{That's why you need this jacket? By the way, do you know that you look like a twat wearing it?}
{121}{022}{这就是你需要这件夹克的原因？顺便问一下，你知道你戴着它看起来像个白痴吗？}
### {122}{013}{Better tell me how it's going. I still need to make a report for Richards, you know.}
{122}{013}{最好告诉我进展如何。你知道，我还需要为理查兹做一份报告。}

### {130}{}{ Well - it's boring, mostly. My hands are itching to punch someone. And there's this Kelly... [he pauses] Listen, maybe you can help me with one delicate matter? I'll make it worth your while! And it would definitely be more interesting than run errands for the captain.}
{130}{}{嗯，大部分时间都很无聊。我的手很想打别人。还有这个凯利。。。[他停顿了一下]听着，也许你能帮我处理一件微妙的事情？我会让你值得的！这肯定比为船长跑腿更有趣。}
### {131}{014}{Tell me more.}
{131}{014}{告诉我更多。}
### {132}{014}{Errands? You're lucky I'm in a good mood. So, what do you want?}
{132}{014}{错误？你很幸运，我的心情很好。那么，你想要什么？}

### {140}{}{[he gets lively] So, here's the thing - there's one lab assistant at the biologists, the name's Kelly. She hangs out with smart-asses, but her brain is the size of a Lavash testicle. Still, why would a girl need to have a brain when she has awesome junk and a pair of big boobs, am I right? I bet every guy around here polishes his barrel thinking about her. And this treasure was supposed to belong to that moron Timmy! Can you believe that? But now, when Timmy is gone in Tartarus, the place is vacant... Know what I'm saying?}
{140}{}{[他变得活泼起来]所以，事情是这样的——生物学家有一个实验室助理，名叫凯利。她和聪明的屁股在一起，但她的大脑有熔岩睾丸那么大。尽管如此，为什么一个女孩需要有头脑，因为她有很棒的垃圾和一对大胸部，我说得对吗？我敢打赌，这里的每一个男人都在想着她。这个宝藏本应该属于那个白痴蒂米的！你能相信吗？但现在，当蒂米在塔尔塔罗斯离开时，这个地方就空了。。。知道我在说什么吗？}
### {141}{015}{I think I do. What do you want from ME?}
{141}{015}{我想我会的。你想从我这里得到什么？}

### {150}{}{Talk her into coming to me! I tried it myself, but she passed, saying "boo-hoo, only Timmy, he will get back soon". Stupid bitches... There are only two things they're good for - help us release the tension, and give birth to our future soldiers. So, would you help? You're Richard's man, after all, and he is well-respected around here. I will give you something good - here! [he swiftly pulls out a colt "python" from a holster] Good one, right? Don't worry, it's my personal. Ony, uh... Don't tell Richards, okay? [he nervously looks around]}
{150}{}{说服她来找我！我自己试过了，但她通过了，说“嘘，只有蒂米，他很快就会回来”。愚蠢的婊子。。。他们只有两件事有好处——帮助我们缓解紧张局势，培养我们未来的士兵。那么，你能帮忙吗？毕竟，你是理查德的人，他在这里很受尊敬。我会给你一些好东西的——在这里！[他迅速从皮套里掏出一条小马“蟒蛇”]不错，对吧？别担心，这是我的私事。Ony，呃。。。别告诉理查兹，好吗？[他紧张地环顾四周]}
### {151}{016}{Before answering, I need to ask you a couple of questions.}
{151}{016}{在回答之前，我需要问你几个问题。}
### {152}{017}{We'll see, Jock. No promises.}
{152}{017}{我们拭目以待，乔克。没有承诺。}
### {153}{030}{And that's the kind of bullshit you are busy with here? I think I need to note it in my report. }
{153}{030}{这就是你在这里忙的那种狗屁？我想我需要在报告中注明这一点。}

### {160}{}{[he shrugs] Okay, ask. What's there to not understand?}
{160}{}{[他耸耸肩]好的，问问。有什么不能理解的？}
### {161}{020}{I see your relationship with Richards is quite strained. What does he think about your intentions?}
{161}{020}{我看你和理查兹的关系很紧张。他怎么看你的意图？}
### {162}{024}{What did Kelly have with this Timmy?}
{162}{024}{凯莉和这个蒂米有什么关系？}
### {163}{017}{Actually, I understood enough. I agree.}
{163}{017}{事实上，我已经足够理解了。我同意。}
### {164}{999}{I think this job is not for me. See you. [leave]}
{164}{999}{我觉得这份工作不适合我。再见。[离开]}

### {170}{}{I knew it! I knew you're a nice guy! Okay, here. [gives you a keycard] It's the thing that makes guards around here ready to cut each other's throats - access to a Biology level... To Kelly. [he smugly scoffs] Only Richards has one. And me.}
{170}{}{我就知道！我就知道你是个好人！好的，给你。[给你一张钥匙卡]正是这种东西让这里的警卫们准备好割断彼此的喉咙——进入生物学级别。。。致凯利。[他得意地嘲笑道]只有理查兹有一个。还有我。}
### {171}{999}{Aren't you a lucky one. Okay, I'll tell you when it's done. [take the keycard and leave]}
{171}{999}{你不是很幸运吗。好的，做完后我会告诉你的。[拿着钥匙卡离开]}

### {180}{}{[he stares at you, looking confused] So? If she had her clothes dirty, it's okay - the bitch won't be needing it with me. }
{180}{}{[他瞪着你，看起来很困惑]那么？如果她把衣服弄脏了，那没关系——那婊子就不需要和我在一起了。}
### {181}{019}{It's not so simple. That vial had some virus strain. Which is highly sexually transmittable. Long story short, I wouldn't risk banging her.}
{181}{019}{事情没那么简单。那个小瓶里有某种病毒株。这是高度性传播的。长话短说，我不会冒险撞她。}

### {190}{}{ That... Stupid bitch! Stupid, stupid bitch!! Science, my ass... Why are you standing here? The deal is off now! Go.}
{190}{}{那个愚蠢的婊子！愚蠢，愚蠢的婊子！！科学，我的屁股…你为什么站在这里？交易现在取消了！去}
### {191}{999}{Screw you! Waste of my time. [turn around and leave]}
{191}{999}{去你的！浪费我的时间。[转身离开]}
### {192}{999}{There-there, don't cry, soldier! You can always make yourself happy in the shower. [leave]}
{192}{999}{在那里，别哭，士兵！淋浴时你总能让自己开心。[离开]}

### {200}{}{[he tries to look careless, but you notice fear in his voice] Uh, what? We are cool with captain Richards! He trusts me completely. By the way... Don't tell the captain about Kelly. Why would you need to distract such a busy man with something this petty?}
{200}{}{[他试图看起来漫不经心，但你注意到他的声音里有恐惧]呃，什么？我们对理查兹船长很冷静！他完全信任我。顺便说一句不要把凯利的事告诉船长。你为什么要用这么琐碎的事情来分散这么忙碌的人的注意力？}
### {201}{016}{You already asked me. Another question.}
{201}{016}{你已经问过我了。又是一个问题。}
### {202}{017}{You can stop reminding me. I agree.}
{202}{017}{你可以别再提醒我了。我同意。}
### {203}{999}{I think this job is not for me. See you. [leave]}
{203}{999}{我觉得这份工作不适合我。再见。[离开]}

### {210}{}{[he tries to look careless, but you notice fear in his voice] Uh, what? We are cool with captain Richards! He trusts me completely. By the way... Don't tell the captain about Kelly. Why would you need to distract such a busy man with something this petty?}
{210}{}{[他试图看起来漫不经心，但你注意到他的声音里有恐惧]呃，什么？我们对理查兹船长很冷静！他完全信任我。顺便说一句不要把凯利的事告诉船长。你为什么要用这么琐碎的事情来分散这么忙碌的人的注意力？}
### {211}{999}{Right. Stay tense, sergeant. [nod and leave]}
{211}{999}{正确的保持紧张，中士。[点头离开]}

### {220}{}{[he looks dazzled] Are you serious? Okay, you're going to get a good lesson. Try to not get my jacket dirty.}
{220}{}{[他看起来眼花缭乱]你是认真的吗？好吧，你会得到一个很好的教训。尽量不要把我的夹克弄脏。}
### {221}{998}{You're going to be buried in it!}
{221}{998}{你会被埋在里面的！}
### {233}{027}{I'm gonna cut your jacket in little slices and make you scrub toilets with it, you clown! Did you hear about subordination? I'm your superior officer! And I'll teach you some discipline!}
{233}{027}{我要把你的夹克切成小块，让你用它擦洗厕所，你这个小丑！你听说过从属关系吗？我是你的上级军官！我会教你一些纪律！}

### {230}{}{You bet! [he pats his pands] I have a whole month's supply in here, so I need to load it off as soon as I can. I broke her claws already, so now it's a little boring - I don't even need a rope. No resistance at all. }
{230}{}{你敢打赌！[他拍拍屁股]我这里有整整一个月的供应，所以我需要尽快把它装上。我已经打断了她的爪子，所以现在有点无聊——我甚至不需要绳子。没有任何阻力。}
### {231}{999}{Too bad I have no time for something like this. See you around, lucky boy.}
{231}{999}{可惜我没有时间做这样的事。再见，幸运儿。}
### {232}{999}{[leave silently]}
{232}{999}{[默默地离开]}

### {240}{}{[he cringes] What to say about it? Our eggheads are lost their stupid minds if they picked a thin moron like Timmy for such a good chick. Damn selection... I mean, Timmy was okay, but I'm glad he disappeared in Tartarus. Yes, I'm honest about it. What would he do with such a girl?}
{240}{}{[他畏缩]该怎么说？如果我们的书呆子们选了一个像蒂米这样的瘦白痴做这么好的女孩，他们就会失去愚蠢的头脑。该死的选择。。。我的意思是，蒂米还好，但我很高兴他在塔尔塔罗斯失踪了。是的，我说实话。他会对这样一个女孩做什么？}
### {241}{016}{I see. Another question then.}
{241}{016}{我明白了。那又是一个问题。}
### {242}{017}{I heard enough. I agree.}
{242}{017}{我听够了。我同意。}
### {243}{999}{I think this job is not for me. See you. [leave]}
{243}{999}{我觉得这份工作不适合我。再见。[离开]}

### {250}{}{Man, you've really helped me out! I won't forget that! Okay, now someone is going to learn what true love is. Wait here, okay? I'll be right back, won't beat her hard this time. [he hastily leaves]}
{250}{}{伙计，你真的帮了我！我不会忘记的！好吧，现在有人要学会什么是真爱了。在这里等着，好吗？我马上回来，这次不会狠狠地打她。[他匆匆离去]}
### {251}{026}{[wait]}
{251}{026}{[等待]}

### {260}{}{[Jock returns. His face is shining with a smile] That was such a good fuck! If you could only see it! I almost tore the bitch in half! She resisted, can you imagine? I had to subdue her and punch her face, just in case. Anyway, here. It's yours now. [he hands you a pistol] I have another gun prioritized now! [he winks]}
{260}{}{[乔克回来了。他的脸上露出了灿烂的笑容]他妈的太棒了！如果你能看到它就好了！我差点把那个婊子撕成两半！她抗拒了，你能想象吗？我不得不制服她，打她的脸，以防万一。不管怎样，在这里。现在是你的了。[他递给你一把手枪]我现在有另一把枪优先！[他眨眼]}
### {261}{999}{Glad for you. I wish I could have fun as you do. Okay, see you. [take the gun and leave]}
{261}{999}{为你高兴。我希望我能像你一样玩得开心。好吧，再见。[拿着枪离开]}
### {262}{999}{[silently take the pistol and leave]}
{262}{999}{[默默地拿着手枪离开]}

### {270}{}{[Jock freezes in surprise] Superior? What?}
{270}{}{[乔克惊讶地僵住了]上级？什么}
### {271}{028}{Not "what" me! You will call me SIR! Thirty push-ups, you clown!}
{271}{028}{不是“什么”我！你会叫我先生的！三十个俯卧撑，你这个小丑！}
### {272}{029}{Yes, superior! You're gonna get five shifts of guarding the Purgatory for this!}
{272}{029}{是的，上级！你会因此得到五个守卫炼狱的轮班！}

### {280}{}{[Jock stares at you, he doesn't seem to understand what's going on. He starts to slowly descend on the floor]}
{280}{}{[乔克盯着你看，他似乎不明白发生了什么。他开始慢慢地倒在地板上]}
### {281}{999}{["help" him by punching his back] One! Two! One! Two! Keep up, clown! Maybe you have some potential!}
{281}{999}{[用拳头打他的背来“帮助”他]一个！二一二跟上，小丑！也许你有一些潜力！}
### {282}{999}{[grab his jacket's collar and shake it] Too slow! Time to teach you some discipline, you mutt...}
{282}{999}{[抓住他的夹克领子摇一摇]太慢了！是时候教你一些纪律了，你这个白痴。。。}

### {290}{}{But... I...}
{290}{}{但是我}
### {291}{028}{Shut your pie hole, mouthy guy! I see you fail to comprehend what discipline is! Then I'm personally taking care of you, clown! Thirty push-ups! Go!}
{291}{028}{闭上你的馅饼洞，嘴皮子！我看你不明白什么是纪律！那我亲自照顾你，小丑！三十个俯卧撑！去}

### {300}{}{Hey! I treat you like my own, and you want to snitch on me? We don't do things this way here!}
{300}{}{嘿我待你如己，你还想告发我？我们在这里不这样做！}
### {301}{998}{You'd better pray for me to have a good mood when I'll go reporting the captain.}
{301}{998}{当我去报告船长的时候，你最好祈祷我有一个好心情。}
### {302}{031}{Oh yeah? We can figure something out. If there's nothing to report, I'll be very sad. But if I were to receive something to not be sad...}
{302}{031}{哦，是吗？我们可以想办法。如果没有什么可报告的，我会很难过的。但如果我能得到一些不悲伤的东西。。。}
### {303}{032}{Relax, I won't put it into my report. Just keeping you on your toes. But I'll remember that.}
{303}{032}{别紧张，我不会把它写进报告里。只是让你保持警觉。但我会记住的。}

### {310}{}{No shit. A deal is a deal. Help me - and you'll get the gun. Don't - go screw yourself. This was my personal request, it doesn't concern my duties. And it still stays. }
{310}{}{没什么。一言为定帮帮我，你会拿到枪的。不要去搞砸自己。这是我个人的要求，与我的职责无关。它仍然存在。}
### {311}{016}{Okay, I'll think about it. But I have some questions first.}
{311}{016}{好的，我会考虑的。但我首先有一些问题。}
### {312}{999}{No promises, but I'll think about it. }
{312}{999}{没有承诺，但我会考虑的。}

### {320}{}{Yeah-yeah. My offer still stands.}
{320}{}{是的是的。我的报价仍然有效。}
### {321}{016}{Okay, I'll think about it. But I have some questions first.}
{321}{016}{好的，我会考虑的。但我首先有一些问题。}
### {322}{999}{No promises, but I'll think about it. }
{322}{999}{没有承诺，但我会考虑的。}

### {330}{}{Sir, everything's alright. There's only a lack of shag. I mean, not with my duties, with normal chicks. [Jock gets silent, assessing your reaction] Permission to make a request, sir?}
{330}{}{先生，一切都好。只是缺少绒毛。我的意思是，与我的职责无关，与普通的小鸡无关。[乔克沉默了，评估你的反应]先生，允许提出请求吗？}
### {331}{034}{Granted.}
{331}{034}{当然。}
### {332}{042}{Granted. Explain your request while doing push-ups.}
{332}{042}{当然。在做俯卧撑时解释你的要求。}
### {333}{038}{Denied.}
{333}{038}{拒绝。}

### {340}{}{Sir, as part of the alleged problem, I'd like to apply for a sexual partner. Unofficially. One of the lab assistants had lost her potential partner, and I want to take his place. Official requests through the captain don't have any effect... I learned that if she agrees once, we can shag as much as I want - at least until a new partner is chosen. And I would really want to give her a full ride.}
{340}{}{先生，作为所谓问题的一部分，我想申请性伴侣。非官方的。其中一名实验室助理失去了她的潜在伴侣，我想接替他的位置。通过船长提出的正式请求没有任何效果。。。我了解到，如果她同意一次，我们可以随心所欲地做爱——至少在选择新伴侣之前。我真的很想载她一程。}
### {341}{035}{Why don't you carry your ass to her and try to deal with it personally, instead of bugging your superiors with such requests?}
{341}{035}{你为什么不亲自去找她，而不是用这样的要求来骚扰你的上级呢？}

### {350}{}{Sir, she is against it. I can't subdue and bonk her at the Biology level. I'd like to lure her here, to our floor, but I failed to do so until now. I have an access keycard, maybe you could help me with this problem?}
{350}{}{先生，她反对。我不能在生物学水平上制服她。我想把她引诱到这里，引诱到我们的楼层，但直到现在我都没能这么做。我有一个门禁卡，也许你能帮我解决这个问题？}
### {351}{036}{Keycard? Where did you get it? Should you even have one?}
{351}{036}{钥匙卡？你从哪里得到的？你应该有一个吗？}
### {352}{999}{Well... Let's see what can be done. Hand over the keycard. I'll consider your request.}
{352}{999}{好让我们看看能做些什么。交出钥匙卡。我会考虑你的要求。}
### {353}{999}{Tired of abstinence? I'll show you! Hand over the keycard! Thirty push-ups!}
{353}{999}{厌倦了禁欲？我给你看！交出钥匙卡！三十个俯卧撑！}

### {360}{}{Uh... Yes, sir!}
{360}{}{嗯是的，先生！}
### {361}{037}{Of course. Hand over the keycard, clown.}
{361}{037}{当然交出钥匙卡，小丑。}
### {362}{999}{Well... Your needs are influencing your duties. So, I'll consider your request. }
{362}{999}{好你的需求正在影响你的职责。所以，我会考虑你的要求。}
### {363}{999}{No you don't smart-ass! Hand over the keycard! Thirty push-ups!}
{363}{999}{不，你不聪明！交出钥匙卡！三十个俯卧撑！}

### {370}{}{[Jock reluctantly gives you a keycard]}
{370}{}{[乔克不情愿地给了你一张钥匙卡]}
### {371}{999}{Good boy. Now, thirty push-ups!}
{371}{999}{好孩子。现在，30个俯卧撑！}
### {372}{999}{About your request - your needs are influencing you doing your duties. So, I'll consider it. }
{372}{999}{关于你的请求——你的需求正在影响你履行职责。所以，我会考虑的。}

### {380}{}{[Jock looks visibly nervous, his hands are trembling. It leads to him accidentally dropping the keycard he was holding in his hand. He looks at you with his eyes wide open.]}
{380}{}{[乔克看起来很紧张，双手颤抖。这导致他不小心把手里的钥匙卡掉了下来。他睁大眼睛看着你。]}
### {381}{039}{A keycard? Why do you have it? By your rank, you shouldn't be issued with one! [pick it up]}
{381}{039}{钥匙卡？你为什么有它？以你的级别，你不应该被发给一个！[捡起来]}

### {390}{}{Sir, it's about my request. It's...}
{390}{}{先生，这是关于我的请求。这是。。。}
### {391}{999}{Didn't I forbid you to pester me with your problems? Thirty push-ups!}
{391}{999}{我不是禁止你用你的问题纠缠我吗？三十个俯卧撑！}
### {392}{040}{Tell me. But do it quickly.}
{392}{040}{告诉我，但要快。}

### {400}{}{Sir, as part of the alleged problem, I'd like to apply for a sexual partner. Unofficially. One of the lab assistants had lost her potential partner, and I want to take his place. Official requests through the captain don't have any effect... I learned that if she agrees once, we can shag as much as I want - at least until a new partner is chosen. And I would really want to give her a full ride.}
{400}{}{先生，作为所谓问题的一部分，我想申请性伴侣。非官方的。其中一名实验室助理失去了她的潜在伴侣，我想接替他的位置。通过船长提出的正式请求没有任何效果。。。我了解到，如果她同意一次，我们可以随心所欲地做爱——至少在选择新伴侣之前。我真的很想载她一程。}
### {401}{041}{Why don't you carry your ass to her and try to deal with it personally, instead of bugging your superiors with such requests?}
{401}{041}{你为什么不亲自去找她，而不是用这样的要求来骚扰你的上级呢？}

### {410}{}{Sir, she is against it. I can't subdue and bonk her at the Biology level. I'd like to lure her here, to our floor, but I failed to do so until now. I had an access keycard, but now all I can do is ask you. Would you help me with this problem?}
{410}{}{先生，她反对。我不能在生物学水平上制服她。我想把她引诱到这里，引诱到我们的楼层，但直到现在我都没能这么做。我有一个门禁卡，但现在我所能做的就是问你。你能帮我解决这个问题吗？}
### {411}{999}{Well... Let's see what can be done. I'll consider your request.}
{411}{999}{好让我们看看能做些什么。我会考虑你的要求。}
### {412}{999}{Tired of abstinence? I'll show you! Thirty push-ups!}
{412}{999}{厌倦了禁欲？我给你看！三十个俯卧撑！}

### {420}{}{[Jock starts doing push-ups and talk. Because of his grunting and mumbling, you didn't understand anything he said.]}
{420}{}{[乔克开始做俯卧撑并讲话。因为他的咕哝和喃喃自语，你什么都听不懂他说的。]}
### {421}{034}{Okay, stand up! Atten-shun! I didn't get shit from what you were babbling. You talk like a scared weakling. Now, repeat.}
{421}{034}{好的，站起来！小心！我没有从你的胡言乱语中得到什么。你说话像个胆小鬼。现在，重复一遍。}

### {430}{}{Sir, thank you, sir! }
{430}{}{先生，谢谢您，先生！}
### {431}{999}{Gods forbid you to give me additional problems. I'll give you to the eggheads, they're going to test your durability with the help of Chimera males.}
{431}{999}{上帝禁止你给我更多的问题。我把你交给蛋头们，他们将在奇美拉雄性的帮助下测试你的耐力。}
