##############################
#Location: NWO
#Name: Sunny
#Short Description: Girl who lost her father in Pearson Town
#Date of creation: 17.08.2015
############################## 
#For the game "Olympus 2207"
#Artem "Rainman" Samoilov
##############################
#
#CRITTER DESCRIPTION
#
# before meeting
### {1}{}{You see a dirty girl.}
{1}{}{你看到一个脏女孩。}
### {2}{}{Her clothes are covered in dirt and torn in several places.}
{2}{}{她的衣服上满是污垢，好几个地方都破了。}
#
# after meeting
### {3}{}{You see Sunny.}
{3}{}{你看到Sunny了。}
### {4}{}{Her clothes are covered in dirt and torn in several places.}
{4}{}{她的衣服上满是污垢，好几个地方都破了。}
#
#HERE BEGINS A DIALOGUE
#
### {5}{}{Did you find a paramedic's bag?}
{5}{}{你找到医护人员的包了吗？}
### {6}{}{We cannot leave without a paramedic's bag.}
{6}{}{没有医护人员的包我们不能离开。}
### {7}{}{Thank you so much! Becky and I are forever in your debt!}
{7}{}{非常感谢！贝基和我永远欠你的债！}
### {8}{}{Thanks again! You saved our lives!}
{8}{}{再次感谢！你救了我们的命！}
#Node001
### {10}{}{[A young girl rushes to you as soon as you get into the room. It's rather dark here, but you notice that she looks like she was tortured or lacked sleep for a really long time. She holds a metal pipe in her trembling hands] You are not insane. [she lowers her "weapon" and her shoulders limp down] Thank god... I almost gave up... Wait! Did you see a man there?}
{10}{}{[你一进房间，一个年轻女孩就冲到你面前。这里很黑，但你注意到她看起来像是被折磨了很长一段时间或睡眠不足。她颤抖的手里拿着一根金属管]你没有疯。[她放下“武器”，肩膀一瘸一拐]感谢上帝。。。我差点放弃。。。等待你在那里看到一个人了吗？}
### {11}{002}{Sunny, is it?}
{11}{002}{阳光，是吗？}

#Node002
### {20}{}{[the girl starts enthusiastically nodding her head] Yes, I am Sunny. And you are?}
{20}{}{[女孩开始热情地点头]是的，我是Sunny。你是吗？}
### {21}{003}{.}
{21}{003}{。}
### {22}{003}{Henry asked me to help you.}
{22}{003}{亨利让我帮你。}
### {23}{003}{Doesn't matter, the thing is that you need to get out of here.}
{23}{003}{没关系，问题是你需要离开这里。}

#Node003
### {30}{}{[as if suddenly having come to her senses, she rushes to the door and swiftly locks it. She freezes, listening, then sighs] Sorry, it's just in case. I don't want these creatures to burst in here. So! You're here to get us out, right?}
{30}{}{[好像突然恢复了理智，她冲到门口，迅速锁上了门。她听着，僵住了，然后叹了口气]对不起，这只是以防万一。我不想这些生物闯进这里。所以你是来救我们的，对吧？}
### {31}{004}{Yes, exactly. Your friend Henry asked me to find you.}
{31}{004}{是的，没错。你的朋友亨利让我去找你。}

#Node004
### {40}{}{Henry... [the girl smiles, but next second her joy instantly evaporates] Did you see an adult man in the town?}
{40}{}{亨利。。。[女孩微笑着，但下一秒她的喜悦就烟消云散了]你在镇上看到一个成年男子了吗？}
### {41}{005}{Is he your father? No. What happened?}
{41}{005}{他是你的父亲吗？没有。发生了什么事？}
### {42}{005}{Is he your father? No. And judging by what I've seen here - he is probably already dead.}
{42}{005}{他是你的父亲吗？没有。从我在这里看到的情况来看，他可能已经死了。}

#Node005
### {50}{}{[you hear a faint moan nearby. You didn't notice at first that there is someone else here] Sunny... Who is there? Your father? [you notice a girl lying on the floor. She leans slightly to the side on her elbow.]}
{50}{}{[你听到附近有微弱的呻吟声。你一开始没有注意到这里还有其他人]Sunny。。。谁在那里？你爸爸？[你注意到一个女孩躺在地板上。她用胳膊肘微微向一侧倾斜。]}
### {51}{006}{[continue]}
{51}{006}{[持续]}

#Node006
### {60}{}{[Sunny turns her head] Becky, get some rest. You shouldn't waste your energy. Help came. From the NWO.}
{60}{}{贝基，休息一下。你不应该浪费精力。救援来了。来自NWO。}
### {61}{007}{[continue]}
{61}{007}{[持续]}

#Node007
### {70}{}{[Becky leans back, mumbling something about how no one in the NWO cared about them and it's very strange that someone came. Sunny turns back to you, holding her thumb up to the temple.] So... Where were we... Ah! Did you see my father there?}
{70}{}{【贝基向后倾身，喃喃自语地说，NWO里怎么没有人关心他们，很奇怪有人来了。Sunny转过身来，把拇指举到太阳穴前。】所以……我们在哪里。。。啊！你在那里看到我父亲了吗？}
### {71}{008}{No.}
{71}{008}{不}

#Node008
### {80}{}{It's very bad. [she shakes her head] When we entered the town, these "locals" attacked us. At first, there was only one - father fended him off. But then more of them appeared. He drew their attention and ran, shouting us to leave... We were trying to find a secluded place but bumped into a huge jackal. He chased us to this mall. I slammed its head with something heavy, but he still got Becky - she has her leg wounded, it's covered in blood and she can't walk... So, we decided to wait for the father here. So far I made several forays to the town for medicines and water. The pharmacy in the mall is looted completely, I only found some painkillers and bandages. }
{80}{}{非常糟糕。[她摇摇头]当我们进入小镇时，这些“当地人”袭击了我们。起初，只有一个人——父亲挡住了他。但后来更多的人出现了。他引起了他们的注意，然后跑了，大声叫我们离开。。。我们试图找一个僻静的地方，却碰到了一只巨大的豺狼。他追着我们来到这个商场。我用重物猛砸它的头，但他还是抓住了贝基——她的腿受伤了，浑身是血，她不能走路。。。所以，我们决定在这里等父亲。到目前为止，我多次到城里去买药和水。商场里的药店被洗劫一空，我只找到了一些止痛药和绷带。}
### {81}{009}{How much time did you spend in this basement?}
{81}{009}{你在这个地下室呆了多少时间？}
### {82}{012}{Any idea where you can get something to help Becky?}
{82}{012}{你知道在哪里可以帮贝基吗？}

#Node009
### {90}{}{Around two days, probably.}
{90}{}{大概两天左右。}
### {91}{011}{Yeah... I think it's unlikely that your father survived...}
{91}{011}{是 啊我认为你父亲不太可能活下来。。。}
### {92}{012}{Any idea where to find anything to help Becky?}
{92}{012}{知道在哪里可以找到帮助贝基的东西吗？}

#Node010
### {100}{}{[Sunny takes the paramedic's bag from you] Great! What about father?}
{100}{}{[Sunny从你手里拿走了医护人员的包]太好了！父亲呢？}
### {101}{015}{I didn't see him.}
{101}{015}{我没看见他。}
### {102}{015}{You know, I'd prefer not to talk about it.}
{102}{015}{你知道，我宁愿不谈论它。}

#Node011
### {110}{}{You know, you could stop reminding me about it.}
{110}{}{你可以别再提醒我了。}
### {111}{012}{Any idea where you can get anything to help Becky?}
{111}{012}{你知道在哪里可以帮贝基吗？}

#Node012
### {120}{}{Yes. I found an old town map in the mall. There's a hospital somewhere nearby. Sorry, but I do not know which way to go, this map was in very bad condition and I didn't really understand it. But I explored as much of town as I could. And if I understood everything correctly, the hospital is somewhere not far from where we were attacked. Maybe... Maybe you'll even find our father. What if he's in a similar basement?}
{120}{}{对我在商场里找到了一张旧的城镇地图。附近有一家医院。对不起，但我不知道该走哪条路，这张地图的状况很糟糕，我也不太理解它。但我尽可能多地探索了这个城市。如果我正确地理解了一切，医院就在离我们被袭击的地方不远的地方。大概也许你会找到我们的父亲。如果他在一个类似的地下室呢？}
### {121}{013}{So, what exactly should I be looking for?}
{121}{013}{那么，我到底应该寻找什么呢？}

#Node013
### {130}{}{A paramedic's bag dad told us about. He said that if we find a few - even one - it would help us get into the NWO.}
{130}{}{一个护理人员的包爸爸告诉我们。他说，如果我们找到几个——甚至一个——这将有助于我们进入NWO。}
### {131}{014}{Okay, I'll look for it.}
{131}{014}{好的，我去找。}
### {132}{010}{Like this one?}
{132}{010}{像这个？}

#Node014
### {140}{}{Good luck out there. }
{140}{}{祝你好运。}
### {141}{999}{[end of dialogue]}
{141}{999}{[对话结束]}

#Node015
### {150}{}{[Sunny hides her eyes. Her joy from receiving the bag quickly disappears.] Okay. Let's get out of here. We'll need your help. I can inject the painkiller and apply a splint, but dragging her and fighting off the beasts - that's out of the question for me. [the girl is about to get to Becky, but stops and smiles at you] Thanks. I really appreciate your help, although I may be bad at showing it. After attitude we got in the NWO - to get some help is even nicer. A pity that I lost my father in this. I still hope he fled the town and we will meet with him eventually.}
{150}{}{[Sunny闭上眼睛。她收到袋子后的喜悦很快消失了。]好吧。让我们离开这里。我们需要你的帮助。我可以注射止痛药和夹板，但拖着她和野兽搏斗——这对我来说是不可能的。（女孩正要接近贝基，但停下来对你微笑）谢谢。我真的很感激你的帮助，尽管我可能不善于表现出来。在我们进入NWO后，得到一些帮助会更好。很遗憾我在这件事上失去了父亲。我仍然希望他逃离小镇，我们最终会见到他。}
### {151}{016}{[treat Becky]}
{151}{016}{[招待贝基]}

### {160}{}{#Node016}
{160}{}{#节点016}
### {161}{}{[Sunny handled the task so well as if she had been taught this. Becky looks much better now. When Sunny changes the bandage on her leg, you have a glance at a very nasty-looking wound. But in the end, the girl finally feels relieved. Probably, for the first time for days.] Well... We are ready. No more waiting for father. Let's go.}
{161}{}{[Sunny很好地完成了这项任务，就好像她被教过一样。Becky现在看起来好多了。当Sunny换下腿上的绷带时，你会看到一个看起来很难看的伤口。但最终，女孩终于松了一口气。可能是几天来的第一次。]嗯。。。我们已经准备好了。不再等爸爸了。我们走吧。}
### {163}{999}{[lead girls out of town]}
{163}{999}{[带女孩出城]}

#Node017
### {170}{}{[When the first joys and troubles of arriving at the NWO end, Sunny focuses her attention on you] You know, no one has ever been so good to us. I don't even know what to say... We survived only because of your help. A paramedic's bag that helped to get Becky to the NWO became our ticket to life here. Even their cheap doctor Hinder acknowledged that we can be helpful. So now we have a house. And also, we were told that "this is more than a house! This is a family!", but I would have kept their mouth shut if I were them. I lost my father, and he meant more to me than anyone from the "family" of this place. Anyway - I don't know how to thank you. I just wanted to say it. Know that I will always be in your debt.}
{170}{}{【当来到NWO的第一次快乐和烦恼结束时，Sunny把注意力集中在你身上】你知道，从来没有人对我们这么好。我甚至不知道该说什么。。。我们之所以能活下来，是因为你的帮助。一个帮助贝基去NWO的护理包成了我们在这里的生活门票。即使是他们的廉价医生辛德也承认我们可以提供帮助。所以现在我们有了房子。此外，我们被告知“这不仅仅是一所房子！这是一个家庭！”，但如果我是他们，我会对他们守口如瓶。我失去了我的父亲，他对我来说比这个地方“家庭”的任何人都重要。不管怎样，我不知道该怎么感谢你。我只是想说出来。要知道我将永远欠你的债。}
### {171}{999}{I'm glad that you are alright. See you around!}
{171}{999}{我很高兴你没事。回头见！}
### {172}{999}{I'll remember this part, about the debt!}
{172}{999}{我会记住这部分，关于债务！}
### {173}{999}{I would prefer payment, but it's fine. See you.}
{173}{999}{我宁愿付款，但没关系。再见}
