##############################
#Location: Sunset Dogs
#Name: Shiva 
#Short Description: Screamer Toy
#Date of creation: 27.09.2014
##############################
#For the game "Olympus 2207"
#Artem "Rainman" Samoilov	 
##############################	
#	
#CRITTER DESCRIPTION	
#NEED TO TEST THIS ONE
#	
# before meeting
### {1}{}{You see a pretty, albeit very dirty girl.}
{1}{}{你看到了一个漂亮的，虽然很脏的女孩。}
### {2}{}{She looks damn attractive in these clothes.}
{2}{}{她穿这些衣服看起来很有魅力。}
#
# after meeting
### {3}{}{You see a pretty, albeit very dirty girl.}
{3}{}{你看到了一个漂亮的，虽然很脏的女孩。}
### {4}{}{She looks damn attractive in these clothes.}
{4}{}{她穿这些衣服看起来很有魅力。}
#
### {5}{}{Let's talk another time.}
{5}{}{我们改天再说吧。}
### {6}{}{You again? Pfft...}
{6}{}{你又来了？Pfft。。。}
### {7}{}{Shiva's nose breaks with a crunch, she falls on her back, squealing. Her blood drips from your fist.}
{7}{}{湿婆的鼻子嘎吱一声断了，她仰面摔倒，尖叫着。她的血从你的拳头上滴下来。}
#
#HERE BEGINS A DIALOGUE
#
### {10}{}{[the girl starts talking before you have any chance to open your mouth] Another newcomer to the camp! Hello there. My name is Shiva.}
{10}{}{[你还没来得及开口，女孩就开始说话]又是一个新来的露营者！你好。我的名字叫湿婆。}
### {11}{002}{Hello, I'm }
{11}{002}{你好，我是}
### {12}{002}{...}
{12}{002}{。。。}


### {20}{}{Yeah-yeah. So, what brings you to this extremely beautiful and interesting place? Wait a minute, let me guess: you came here from some half-dead farm because you could barely make ends meet, and decided to live by the robbery and alcoholism, like a real thug.}
{20}{}{是的是的。那么，是什么把你带到这个美丽而有趣的地方呢？等一下，让我猜猜：你从一个半死不活的农场来到这里，因为你几乎入不敷出，决定像一个真正的暴徒一样，靠抢劫和酗酒生活。}
### {21}{003}{Well... you can say that.}
{21}{003}{好你可以这么说。}
### {22}{006}{No, it is not like that at all.}
{22}{006}{不，根本不是那样的。}


### {30}{}{Pffft... [girl rolls her eyes] How interesting.}
{30}{}{Pffft。。。[女孩翻白眼]真有趣。}
### {31}{004}{Listen, I have a couple of questions.}
{31}{004}{听着，我有几个问题。}
### {32}{997}{Well, I AM quite interesting. All right, I'll go. To do other interesting things.}
{32}{997}{嗯，我很有趣。好吧，我走。做其他有趣的事情。}


### {40}{}{I don't like to answer questions. I like asking them. And you are hardly going to tell me anything interesting...}
{40}{}{我不喜欢回答问题。我喜欢问他们。你几乎不会告诉我任何有趣的事情。。。}
### {41}{005}{Oh my, you are such a bore.}
{41}{005}{哦，天哪，你真无聊。}
### {42}{997}{Don't care. I'll go find a more talkative companion.}
{42}{997}{不要在意。我会去找一个更健谈的同伴。}


### {50}{}{Me? Bore? It is you who is boring, you asshole! We have nothing to talk about!}
{50}{}{我令人厌烦无聊的是你，你这个混蛋！我们没什么好说的！}
### {51}{997}{Yeah-yeah [wave hand and leave]}
{51}{997}{是的是的[挥手离开]}
### {52}{998}{Did you just call me an asshole!? [punch her face]}
{52}{998}{你刚才是不是说我混蛋！？[打她的脸]}


### {60}{}{Oh well. Tell me something interesting about yourself!}
{60}{}{哦，好吧。告诉我一些关于你自己的有趣的事情！}
### {61}{011}{I am from Olympus!}
{61}{011}{我来自奥林巴斯！}
### {62}{008}{I can punch the helmet so hard it caves in.}
{62}{008}{我能把头盔打得很厉害，它会塌陷。}
### {63}{007}{I can flay corpses.}
{63}{007}{我能剥皮。}
### {64}{009}{I can assemble and disassemble almost any device with my eyes closed.}
{64}{009}{我几乎可以闭着眼睛组装和拆卸任何设备。}


### {72}{}{So what? Ursul can skin Ursa before he gets eaten by one.}
{72}{}{那又怎样？乌尔苏拉可以在被一只熊吃掉之前把它剥皮。}
### {70}{005}{Oh my, you are such a bore.}
{70}{005}{哦，天哪，你真无聊。}
### {71}{997}{Don't care. I'll go find a more talkative companion.}
{71}{997}{不要在意。我会去找一个更健谈的同伴。}


### {80}{}{So? Brick is literally breaking bricks with his head. He giggles while doing it, like he is tickled.}
{80}{}{所以布里克实际上是在用头打砖。他一边做一边咯咯地笑，就像被挠了一样。}
### {81}{005}{Oh my, you are such a bore.}
{81}{005}{哦，天哪，你真无聊。}
### {82}{997}{Don't care. I'll go find a more talkative companion.}
{82}{997}{不要在意。我会去找一个更健谈的同伴。}


### {90}{}{Yeah? Yesterday Carl disassembled, cleaned, and assembled back Vince's rifle in seven minutes. And Vince's rifle was fully covered in shit.}
{90}{}{是 啊昨天，卡尔在七分钟内拆开、清洗并装回了文斯的步枪。文斯的步枪上全是屎。}
### {91}{005}{Oh my, you are such a bore.}
{91}{005}{哦，天哪，你真无聊。}
### {92}{997}{Don't care. I'll go find a more talkative companion.}
{92}{997}{不要在意。我会去找一个更健谈的同伴。}


### {110}{}{You're lying!}
{110}{}{你在撒谎！}
### {111}{013}{I'm not lying!}
{111}{013}{我没有撒谎！}
### {112}{012}{You can believe me or not. I don't give a shit. }
{112}{012}{你信不信由你。我一点也不在乎。}


### {120}{}{As I think that you are full of shit. Dickhead.}
{120}{}{就像我认为的那样，你满是垃圾。Dickhead。}
### {121}{997}{Yeah-yeah [wave hand and leave]}
{121}{997}{是的是的[挥手离开]}
### {122}{998}{What did you say to me!? [punch her nose]}
{122}{998}{你对我说了什么！？[打她的鼻子]}


### {130}{}{Well, prove it.}
{130}{}{好吧，证明一下。}
### {131}{014}{[tell your story]}
{131}{014}{[讲述你的故事]}
### {132}{012}{You wish. I have one less problem if you won't be prattling about me around here.}
{132}{012}{想得美！如果你不在这里喋喋不休，我就少了一个问题。}


### {140}{}{[Shiva hears you out. At first, she was mostly rolling her eyes, but after a couple of minutes in, you had her full attention.] You are really from there! This is nuts! Usually, we are not very fond of their people, because when we approach the tower, they tend to kill us. So I wouldn't advise you to talk around here about where you are from. The others won't listen to your story and will beat the shit out of you right after the phrase "I am from Olympus." But I'll keep it a secret. [she smiles, scratching her forehead, and moves a lock of hair from her eyes] It was really interesting... Well, don't hang around here for long - one of my boyfriends could think that you are a competitor [she giggles]}
{140}{}{[湿婆听你说完。一开始，她大部分时间都在翻白眼，但几分钟后，你就完全注意到了。]你真的来自那里！这太疯狂了！通常，我们不太喜欢他们的人，因为当我们走近塔楼时，他们往往会杀了我们。所以我不建议你在这里谈论你来自哪里。其他人不会听你的故事，会在“我来自奥林巴斯”这句话之后把你打得落花流水。但我会保守秘密。[她微笑着，抓着额头，移开眼睛里的一缕头发]这真的很有趣。。。好吧，不要在这里呆太久——我的一个男朋友可能会认为你是竞争对手[她咯咯笑着说]}
### {141}{996}{Okay, I'm leaving already.}
{141}{996}{好吧，我已经走了。}
