##############################
#???????: ??? ??????
#???: ????? 
#??????? ????????: ??????? ???????
#???? ????????: 18.09.2014
##############################
#??? ???? "????? 2207"
#????? "Rainman" ????????
##############################
#
#???????? ????????
#
# ?? ??????????
### {1}{}{You see a big guy with a grim face.}
{1}{}{你看到一个脸色冷酷的大个子。}
### {2}{}{With a facial expression like this he must be very much used to bury people.}
{2}{}{有了这样的表情，他一定非常习惯于埋葬别人。}
#
# ????? ??????????
### {3}{}{You see Ursul.}
{3}{}{你看到了乌苏。}
### {4}{}{He digs through his inventory again.}
{4}{}{他又翻遍了他的存货。}
#
### {5}{}{Let's finish the cubs and return back.}
{5}{}{让我们完成幼崽并返回。}
### {6}{}{Look around you! Ursa is a dangerous prey.}
{6}{}{看看你周围！熊是一种危险的猎物。}
### {7}{}{Talk less. Shoot more.}
{7}{}{少说话。拍摄更多。}
### {8}{}{No, we are not coming back without the prey.}
{8}{}{不，没有猎物我们不会回来的。}
#
#????? ?????????? ??????
#
### {10}{}{[A huge man is sharpening his knife, periodically checking it with a finger. He's very well-built - and dressed quite well too, especially by the local standards. His foot rests on the skull of an enormous beast.]}
{10}{}{[一个身材魁梧的男人正在磨刀，不时地用手指检查。他身材很好，穿着也很好，尤其是按照当地的标准。他的脚搁在一只巨大野兽的头骨上。]}
### {11}{002}{Hello.}
{11}{002}{你好}
### {12}{002}{[cough silently]}
{12}{002}{[无声地咳嗽]}
### {13}{002}{Hey, big guy!}
{13}{002}{嘿，大个子！}


### {20}{}{[He stops what he was doing and looks at you. You notice that he's wearing a necklace made of little stones, empty shells, and pieces of glass. On his bandolier you see a patch which reads "Angel of Anaheim"] The name?}
{20}{}{[他停下来看着你。你注意到他戴着一条由小石头、空贝壳和玻璃碎片制成的项链。在他的手帕上，你可以看到一块写着“阿纳海姆天使”的补丁。]名字是什么？}
### {21}{003}{Does it matter?}
{21}{003}{这有关系吗？}
### {22}{003}{A pain in the ass.}
{22}{003}{屁股疼。}
### {23}{003}{Name's }
{23}{003}{姓名}
### {24}{003}{. Why does it matter?}
{24}{003}{。为什么这很重要？}


### {30}{}{[Looks like he didn't hear that] Now you are no one. No name. At least until the local authorities start to show you some respect. You are a newbie. And newbies don't last long here.}
{30}{}{[看起来他没有听到]现在你已经不是一个人了。没有名字。至少在地方当局开始对你表示尊重之前。你是个新手。新手在这里呆不了多久。}
### {31}{006}{Gee, thanks for a warm welcome. }
{31}{006}{哎呀，谢谢你的热情欢迎。}
### {32}{005}{How enlightening. I actually don't care about what the old geezer like you says.}
{32}{005}{多么有启发性。我其实不在乎你这样的老家伙说什么。}
### {33}{004}{So what? }
{33}{004}{那又怎样？}


### {40}{}{Just so you'd understand what you are dealing with here. I'm Ursul. Although I don't actually responsible for the newbies, I often involve them in doing something useful. So maybe we'll have something to talk about.}
{40}{}{只是为了让你明白你在这里处理的是什么。我叫乌苏。虽然我实际上并不负责新手，但我经常让他们参与一些有用的事情。所以也许我们会有话要说。}
### {41}{007}{Please do continue. I'm intrigued. }
{41}{007}{请继续。我很感兴趣。}
### {42}{999}{Curious, but now I'm busy. I have to go.}
{42}{999}{很好奇，但现在我很忙。我得走了。}
### {43}{999}{I don't think I'm interested. [end of dialogue]}
{43}{999}{我想我不感兴趣。[对话结束]}


### {50}{}{If there was some other Jackal instead of me here, you would have been already rectally pleased with a nailed bat, or something. [he stops talking, studying you for a moment] I'm Ursul. I can provide you with a job which would kick some experience into you. Still, there's a chance that you'll kick be bucket instead. When you'll drop your cockfighting attitude and get a little smarter, we can talk details. [he goes back to sharpening the knife]}
{50}{}{如果这里有其他的豺狼而不是我，你会对一只钉好的蝙蝠或其他什么东西感到满意。[他停止了说话，研究了你一会儿]我是乌苏。我可以为你提供一份能给你带来一些经验的工作。尽管如此，你还是有可能会被吊脚踢。当你放弃斗鸡的态度，变得更聪明时，我们可以讨论细节。[他又开始磨刀]}
### {51}{999}{[end of dialogue]}
{51}{999}{[对话结束]}


### {60}{}{Just so you'd understand what you are dealing with here. I'm Ursul. Although I don't actually responsible for the newbies, I often involve them in doing something useful. So maybe we'll have something to talk about.}
{60}{}{只是为了让你明白你在这里处理的是什么。我叫乌苏。虽然我实际上并不负责新手，但我经常让他们参与一些有用的事情。所以也许我们会有话要说。}
### {61}{007}{Please do continue. I'm intrigued. }
{61}{007}{请继续。我很感兴趣。}
### {62}{999}{Curious, but now I'm busy. I have to go.}
{62}{999}{很好奇，但现在我很忙。我得走了。}
### {63}{999}{I don't think I'm interested. [end of dialogue]}
{63}{999}{我想我不感兴趣。[对话结束]}


### {70}{}{[He laughs, not stopping the sharpening process] Do you like animals?}
{70}{}{[他笑着，没有停止磨砺的过程]你喜欢动物吗？}
### {71}{009}{What?}
{71}{009}{什么}
### {72}{008}{No.}
{72}{008}{不}
### {73}{008}{Yes.}
{73}{008}{对}


### {80}{}{Alright, forget it. [he smiles again] You'll help me on the hunt. If you're in, I'd recommend stocking some meds, ammo and get the biggest gun you can. }
{80}{}{好吧，算了。（他又笑了）你会帮我打猎的。如果你在，我建议你储备一些药物和弹药，并尽可能多地拿一把最大的枪。}
### {81}{999}{I'm ready, let's go.}
{81}{999}{我准备好了，走吧。}
### {82}{011}{I changed my mind - I don't really like hunting...}
{82}{011}{我改变了主意——我真的不喜欢打猎。。。}
### {83}{999}{I need some time to prepare.}
{83}{999}{我需要一些时间来准备。}
### {84}{013}{Tell me more about the hunt.}
{84}{013}{告诉我更多关于狩猎的信息。}


### {90}{}{Do you like bear cubs? [he nods at a huge carcass near him]}
{90}{}{你喜欢小熊吗？[他朝旁边的一具巨大的尸体点点头]}
### {91}{008}{What??}
{91}{008}{什么}


### {100}{}{[Ursul nods to you.]}
{100}{}{[乌尔向你点头。]}
### {101}{}{Ask your questions.}
{101}{}{问你的问题。}
### {102}{}{It was a good hunt, wasn't it?}
{102}{}{这是一次很好的狩猎，不是吗？}
### {103}{012}{About the help you needed...}
{103}{012}{关于你需要的帮助。。。}
### {104}{014}{You promised that there will be a reward.}
{104}{014}{你答应过会有奖励的。}
### {105}{030}{You should have traveled a lot. Can you point me to some notable locations in Radius?}
{105}{030}{你应该经常旅行。你能给我指一下Radius的一些著名地点吗？}
### {106}{034}{Maybe we could go hunting again?}
{106}{034}{也许我们可以再去打猎？}
### {107}{999}{Bye, Ursul.}
{107}{999}{再见，乌苏。}




### {110}{}{Stop wasting my time then.}
{110}{}{那就别浪费我的时间了。}
### {111}{999}{[end of dialogue]}
{111}{999}{[对话结束]}
### {112}{010}{I have some questions...}
{112}{010}{我有一些问题。。。}


### {120}{}{Yes. I need help on the hunt. Interested?}
{120}{}{对我狩猎需要帮助。感兴趣的}
### {121}{013}{Tell me more about the hunt.}
{121}{013}{告诉我更多关于狩猎的信息。}


### {130}{}{I found a place not far away from here, which has been chosen as a lair by the huge pack of Ursa. The goal is simple - travel there and kill them all. After that, we'll carry their corpses to the camp. The rest is not our business. If you're in, I'd recommend stocking some meds, ammo and get the biggest gun you can. If you are ready, we can leave right away. If the hunt is good, you'll get some batteries as a reward. }
{130}{}{我在离这里不远的地方找到了一个地方，它被巨大的熊群选为巢穴。目标很简单——去那里旅行并杀死他们。之后，我们将把他们的尸体运到营地。剩下的不关我们的事。如果你在，我建议你储备一些药物和弹药，并尽可能多地拿一把最大的枪。如果你准备好了，我们可以马上离开。如果狩猎很好，你会得到一些电池作为奖励。}
### {131}{999}{I'm ready, let's go.}
{131}{999}{我准备好了，走吧。}
### {132}{011}{I changed my mind - I don't really like hunting...}
{132}{011}{我改变了主意——我真的不喜欢打猎。。。}
### {133}{999}{I need some time to prepare.}
{133}{999}{我需要一些时间来准备。}

### {140}{}{Sure. Here. [he pulls out a handful of batteries from his pocket and gives it to you] }
{140}{}{当然在这里[他从口袋里掏出一把电池递给你]}
### {141}{015}{[count the batteries] 67? Not much, considering the risks taken.}
{141}{015}{[数电池]67？考虑到所承担的风险，不多。}
### {142}{016}{[put the batteries into your pocket]}
{142}{016}{[把电池放进口袋]}


### {150}{}{You got exactly what you deserved. }
{150}{}{你得到了你应得的。}
### {151}{016}{[grumble]}
{151}{016}{[咕哝]}
### {152}{016}{[be silent]}
{152}{016}{[保持沉默]}


### {160}{}{You are not from Radius. Am I right?}
{160}{}{您不是来自Radius。我说得对吗？}
### {161}{017}{What?}
{161}{017}{什么}
### {162}{017}{How's that?}
{162}{017}{怎么样？}
### {163}{017}{What do you mean?}
{163}{017}{你是什么意思？}
### {164}{018}{Maybe.}
{164}{018}{大概}


### {170}{}{I'm not blind. You are fighting not like the people who lived all their lives in Radius. It looks as you first laid hands on a weapon around a month ago. You kill, but lack the skill and your moves are not smooth enough. In Radius every child knows how to disassemble and assemble back the rifle, and how to shoot it in a way that brings maximum pain and suffering to the target. [he looks at you, waiting for an answer]}
{170}{}{我不是瞎子。你不像在Radius生活了一辈子的人那样在战斗。看起来就像你一个月前第一次拿到武器一样。你杀了，但缺乏技巧，你的动作不够流畅。在Radius中，每个孩子都知道如何拆卸和组装步枪，以及如何以给目标带来最大痛苦的方式射击。[他看着你，等待回答]}
### {171}{019}{I'm from the Olympus.}
{171}{019}{我来自奥林巴斯。}
### {172}{021}{Why do you care?}
{172}{021}{你为什么在乎？}
### {173}{022}{What if I don't tell you?}
{173}{022}{如果我不告诉你呢？}


### {180}{}{Did you come from the Olympus?}
{180}{}{你是从奥林匹斯山来的吗？}
### {181}{024}{[keep silent]}
{181}{024}{[保持沉默]}
### {182}{020}{Yes.}
{182}{020}{对}
### {183}{023}{How did you know?}
{183}{023}{你怎么知道的？}


### {190}{}{From what I know, fighters from the Olympus can give hell to anyone in Radius. You are definitely not one of them.}
{190}{}{据我所知，来自奥林巴斯的战士可以给Radius的任何人下地狱。你绝对不是他们中的一员。}
### {191}{020}{Because I'm no soldier. I'm a Servant.}
{191}{020}{因为我不是军人。我是一个仆人。}


### {200}{}{[He nods] Once me and my partner stumbled onto someone from the Olympus. Already dead, wearing a strange uniform - something with the NCASTR logo. My man Fred took it. That's all experience I have about meeting people from the Olympus.}
{200}{}{[他点点头]有一次，我和我的搭档偶然发现了一个来自奥林匹斯山的人。已经死了，穿着一件奇怪的制服——有NCASTR标志的东西。我的人弗雷德拿走了它。这就是我遇到奥林匹斯人的全部经验。}
### {201}{025}{NCASTR, you say? Where can I find Fred?}
{201}{025}{NCASTR，你说？我在哪里能找到弗雷德？}


### {210}{}{My knowledge helps me to survive.}
{210}{}{我的知识帮助我生存。}
### {211}{022}{What if I don't tell you?}
{211}{022}{如果我不告诉你呢？}


### {220}{}{You'll get the same attitude back.}
{220}{}{你会得到同样的态度。}
### {221}{019}{Olympus. I'm from Olympus.}
{221}{019}{奥林巴斯。我来自奥林巴斯。}

### {230}{}{I'm not blind. You are fighting not like the people who lived all their lives in Radius. It looks as you first laid hands on a weapon around a month ago. You kill, but lack the skill and your moves are not smooth enough. In Radius every child knows how to disassemble and assemble back the rifle, and how to shoot it in a way that brings maximum pain and suffering to the target. [he looks at you, waiting for an answer]}
{230}{}{我不是瞎子。你不像在Radius生活了一辈子的人那样在战斗。看起来就像你一个月前第一次拿到武器一样。你杀了，但缺乏技巧，你的动作不够流畅。在Radius中，每个孩子都知道如何拆卸和组装步枪，以及如何以给目标带来最大痛苦的方式射击。[他看着你，等待回答]}
### {231}{020}{[continue]}
{231}{020}{[持续]}


### {240}{}{I'll take that as a yes.}
{240}{}{我会同意的。}
### {241}{020}{[continue]}
{241}{020}{[持续]}


### {250}{}{Far away. Why do you care?}
{250}{}{在远处你为什么在乎？}
### {251}{026}{I need that uniform.}
{251}{026}{我需要那套制服。}


### {260}{}{Won't even ask why someone would need the clothes taken off from a corpse. [he pauses for a while, then continues] I'll tell you where to find Fred. But you promise me in return, that you'll make no mention of him to anyone. Not that someone here cares, but still.}
{260}{}{甚至不会问为什么有人需要把尸体上的衣服脱下来。[他停顿了一会儿，然后继续说]我会告诉你在哪里可以找到弗雷德。但你答应我作为回报，你不会向任何人提及他。并不是说这里有人在乎，但仍然如此。}
### {261}{027}{Okay.}
{261}{027}{可以}


### {270}{}{[Ursul stares at you for a couple of moments, then starts to explain how to get to Fred's hideout.] }
{270}{}{[乌苏尔盯着你看了一会儿，然后开始解释如何去弗雷德的藏身处。]}
### {271}{028}{Great. Thanks.}
{271}{028}{太棒了谢谢}
### {272}{029}{How the hell did Fred manage to wind up so fucking far?}
{272}{029}{弗雷德到底是怎么走到这么远的？}


### {280}{}{Something else?}
{280}{}{还有别的吗？}
### {281}{010}{Yes, I have a couple of questions.}
{281}{010}{是的，我有几个问题。}
### {282}{999}{No, thanks again for the directions.}
{282}{999}{不，再次感谢你的指示。}


### {290}{}{On one of our hunts we wandered off - had some troubles catching up to the prey. Came across a mansion. An empty one. There was a skeleton inside, maybe from before the war, but the house itself was untouched. Looks like we were the first ones to find this place in years. We never told about it to anyone. And then Fred laid his eyes on one of our trophy girls. Snuck her out. I advised him to take shelter in that house. As paranoid as he is, he should still be there. Not sure for how long though. }
{290}{}{在一次狩猎中，我们迷路了——在追赶猎物时遇到了一些困难。偶然发现了一座豪宅。一个空的。里面有一具骨架，可能是战前的，但房子本身没有动过。看起来我们是多年来第一个发现这个地方的人。我们从来没有告诉任何人这件事。然后弗雷德把目光投向了我们的一个奖杯女孩。把她抱出去。我劝他躲在那所房子里。尽管他很偏执，但他应该还在那里。但不确定要持续多久。}
### {291}{010}{Great, thanks. I have some questions.}
{291}{010}{太好了，谢谢。我有一些问题。}
### {292}{999}{Great, thanks. I've got to go.}
{292}{999}{太好了，谢谢。我得走了。}


### {300}{}{I better know the surrounding wastelands than Radius. I'm a hunter, I hunt on my territory. Was never very amused by human settlements. Although, there is one place that every Jackal knows about: Rainbow. Know where it is?}
{300}{}{我比Radius更了解周围的荒地。我是一个猎人，我在我的领地上狩猎。从来没有被人类住区逗乐过。尽管如此，每个豺狼都知道一个地方：彩虹。知道它在哪里吗？}
### {301}{031}{Yes.}
{301}{031}{对}
### {302}{032}{No.}
{302}{032}{不}


### {310}{}{Then I won't tell you anything new.}
{310}{}{那我就不告诉你什么新鲜事了。}
### {311}{010}{Okay. I have some more questions.}
{311}{010}{可以我还有一些问题。}
### {312}{999}{Okay. I've got to go now.}
{312}{999}{可以我现在得走了。}


### {320}{}{Let me show you how to get there...}
{320}{}{让我告诉你怎么去那里。。。}
### {321}{033}{[continue]}
{321}{033}{[持续]}


### {330}{}{[Ursul explains in detail how to get to the Rainbow] The best place if you started to miss woman's tight ass, or just looking to have a fun time. }
{330}{}{【Ursul详细解释了如何到达彩虹】如果你开始错过女人的紧身屁股，或者只是想玩得开心，那就是最好的地方。}
### {331}{010}{Okay. I have some more questions.}
{331}{010}{可以我还有一些问题。}
### {332}{999}{Okay. I've got to go now.}
{332}{999}{可以我现在得走了。}


### {340}{}{At the time there are no orders neither for meat nor for fur. Nor for anything else. We are not good with long-term storage here, that's why I hunt only when our supplies begin to run dry.}
{340}{}{当时既没有肉的订单，也没有毛皮的订单。也不是为了别的。我们不擅长在这里长期储存，这就是为什么我只有在物资开始枯竭时才狩猎。}
### {341}{010}{Okay. I have some more questions.}
{341}{010}{可以我还有一些问题。}
### {342}{999}{Okay. I've got to go now.}
{342}{999}{可以我现在得走了。}
