# ????? ?? ??????? ??饭??,
# ??????騥?? ? ???? ?業??
#
# Created by Artem "Rainman" Samoylov
# 30/07/2013
#
# ??? ????
# ?? - ????? ??????? ???窮?
#
# ?????? 1
### {1}{}{You see a strange gravestone with a niche in it.}
{1}{}{你看到一块奇怪的墓碑，上面有一个壁龛。}
### {2}{}{You see an unusual gravestone.} 
{2}{}{你看到了一块不同寻常的墓碑。}

# ??????? ??????
### {3}{}{You can't see any inscribing or niche. This looks more like a pedestal.}
{3}{}{你看不到任何铭文或壁龛。这看起来更像一个基座。}
### {4}{}{You can still read the letters here. The carved inscription says: "Hoban Washburn".}
{4}{}{你仍然可以在这里阅读这些信件。雕刻的铭文上写着：“霍班沃什本”。}
### {5}{}{You can hardly see the letters: "Shepherd Derrial Book".}
{5}{}{你几乎看不到字母：“牧羊人的Derrial书”。}
### {6}{}{Looks like the sign reads: "Mr. Universe".}
{6}{}{看起来标牌上写着：“宇宙先生”。}

# ??????
### {7}{}{Digging around, you find a human skeleton hugging some robotic remains.}
{7}{}{在周围挖掘，你会发现一具人类骨架拥抱着一些机器人遗骸。}
{8}{}{}
{9}{}{}
{10}{}{}
{11}{}{}
{12}{}{}
{13}{}{}
{14}{}{}
{15}{}{}
{16}{}{}
{17}{}{}
{18}{}{}
{19}{}{}
{20}{}{}
