##############################
#???????: ??????
#???: ??????
#??????? ????????: ???????? ??????-????????? ?? ??????????? ?????? ???????
#???? ????????: 03.05.2014
##############################
#??? ???? "????? 2207"
#????? "Rainman" ????????
##############################
#
#???????? ????????
#
# ?? ??????????
### {1}{}{You see Smitty.}
{1}{}{你看到史密蒂了。}
### {2}{}{A good old Smitty. Chewing something, as always.}
{2}{}{一个好的老史密蒂。像往常一样嚼东西。}
#
# ????? ??????????
### {3}{}{You see Smitty.}
{3}{}{你看到史密蒂了。}
### {4}{}{A good old Smitty. Chewing something, as always.}
{4}{}{一个好的老史密蒂。像往常一样嚼东西。}
#
#????? ?????????? ??????
#
### {100}{}{Look who we have here! Nice suit you got yourself! Did you think I wouldn't recognize you, }
{100}{}{看看我们这里有谁！你自己穿的衣服不错！你以为我认不出你了吗，}
### {101}{}{? Of course it's you, I can tell by the way you walk that your hands are growing straight from your ass, HAH-HAHAHAHA! [he wipes tear] Well then, tell me, what brings you here?}
{101}{}{？当然是你，我可以从你走路的方式看出你的手是从屁股上长出来的，哈哈哈哈！[他擦眼泪]那么，告诉我，是什么把你带到这里来的？}
### {102}{}{Oh! It's you again! [he smiles] You scared me, little devil. So? What do you want?}
{102}{}{哦又是你！[他笑了笑]你吓到我了，小恶魔。所以你想要什么？}
### {103}{011}{Smitty, I have to travel a lot, and I will probably get myself into all kinds of situations... Maybe you could teach me something? So I could assemble a helpful thing or two from some junk.}
{103}{011}{史密蒂，我要经常旅行，我可能会遇到各种各样的情况。。。也许你可以教我一些东西？所以我可以从一些垃圾中收集一两件有用的东西。}
### {104}{020}{I have, uh... A specific task here. I need to unclog one to-i-let. It has too much... Sewage. Dangerous, and very smelly.}
{104}{020}{我。。。这里有一项具体任务。我需要打开一个。它有太多。。。污水危险，而且很臭。}
### {105}{021}{Remember you told me about repairing a plunger using a hammer?}
{105}{021}{还记得你告诉我用锤子修理柱塞吗？}
### {106}{Barter}{Can you show me what you have in your stash?}
{106}{Barter}{你能给我看看你藏的东西吗？}
### {107}{999}{I just came by to say hi. Okay, see you!}
{107}{999}{我只是来打招呼的。好的，再见！}


### {110}{}{Aren't you a little weasel? [he winks]. Okay, for a pack of sugar I can show you how to make a hand-grenade. Or I can teach you how to make a rusty breastplate, for two rolls of good tin. Well, you know, your hands are still pretty crooked, so I can't promise you can handle making these, but maybe in time you would do something about it? So - deal?}
{110}{}{你不是个小黄鼠狼吗？[他眨眼]。好吧，只要一包糖，我就可以教你如何制作手榴弹。或者我可以教你如何为两卷好锡做一个生锈的胸甲。嗯，你知道，你的手仍然很弯曲，所以我不能保证你能做好这些，但也许你会及时做点什么？那么，交易？}
### {111}{012}{Deal! Here's your pack of sugar, teach me to make a grenade!}
{111}{012}{处理这是你的糖包，教我做手榴弹！}
### {112}{013}{Deal, here,s your tin. Show me how to make a breastplate.}
{112}{013}{成交，这是你的罐头。教我怎么做胸甲。}
### {113}{014}{I have none of these things for now... Maybe you could just tell me this, as a friend?}
{113}{014}{我现在没有这些东西。。。也许你可以告诉我，作为一个朋友？}
### {114}{999}{No, that doesn't sound interesting. I'll come by later.}
{114}{999}{不，这听起来并不有趣。我稍后再来。}


### {120}{}{[the sugar instantly disappears from your hand] Okay, here goes: you take a tin can... [Smitty starts to thoroughly explain the process of assembling hand-made grenades from junk.] ...And that's it, mostly. If you didn't get the details - it's your problem. And, of course, these grenades are not very powerful, but you still can scare the rats with them. Here, take one, for a start. Try it sometime.}
{120}{}{[糖立即从你手中消失]好吧，来吧：你拿一个锡罐。。。[Smitty开始彻底解释用垃圾组装手工手榴弹的过程。]……主要就是这样。如果你没有得到细节，那就是你的问题。当然，这些手榴弹的威力不是很大，但你仍然可以用它们吓唬老鼠。给，先拿一个。找个时间试试。}
### {121}{013}{Thanks, old man. By the way, I have a tin too. Tell me about making the breastplate.}
{121}{013}{谢谢，老人。顺便说一句，我也有一罐。告诉我做胸甲的事。}
### {122}{999}{Thanks, old man. This will come in handy.}
{122}{999}{谢谢，老人。这会派上用场的。}


### {130}{}{What a beauuuutiful tin! Look at how shiny it is! And the whole two rolls! I appreciate it greatly, now I have something to patch water tanks with. Oh, and you can use it to make a breastplate too! It will give you some protection in the wilds, which is quite good. So, here goes: you take one tin roll, and... [Smitty thoroughly explains how to create the breastplate from tin, using rolls you brought as a practical illustration] ...And there. Oh, look! While I was explaining it, I assembled a fine one! Take it, you need it more than me. Or give it to your brother, he likes to wage war against rats, heh-heh.}
{130}{}{多么漂亮的锡罐！看看它有多亮！还有整整两卷！我非常感激，现在我有东西可以修补水箱了。哦，你也可以用它做胸甲！它会在野外给你一些保护，这很好。所以，这是：你拿一个锡卷，然后。。。[Smitty用你带来的面包卷作为一个实用的插图，彻底解释了如何用锡制作胸甲。。。就在那里。哦，看！当我解释它的时候，我组装了一个很好的！拿着吧，你比我更需要它。或者把它给你哥哥，他喜欢和老鼠开战，呵呵。}
### {131}{012}{Thanks! This is very helpful. Hey, you know what? I also have some sugar! Come on, tell me, how do I make grenades?}
{131}{012}{谢谢这很有帮助。嘿，你知道吗？我还有一些糖！来吧，告诉我，我怎么做手榴弹？}
### {132}{999}{That's how it is? Thank you, it will come in handy.}
{132}{999}{事情就是这样？谢谢你，它会派上用场的。}

### {1401}{}{Hah, you're good at talking! And I can feel that you're a good man. Why wouldn't I help a good man? Okay, listen [and Smitty starts to thoroughly explain in smallest details talk about creating hand-made grenades and breastplate] ...And that's it, I hope it would come in handy.}
{1401}{}{哈，你很会说话！我能感觉到你是个好人。我为什么不帮助一个好人呢？好吧，听着[Smitty开始以最微小的细节彻底解释关于制造手工手榴弹和胸甲的话题]。。。就这样，我希望它能派上用场。}
### {141}{999}{Thanks, Smitty, it definitely will!}
{141}{999}{谢谢，史密蒂，肯定会的！}
### {1402}{}{What a sly man! No, that doesn't work like that! You give me, then I give you, not the other way around. Sorry, friend. [he squints]}
{1402}{}{多么狡猾的人！不，那样不行！你给我，然后我给你，而不是反过来。对不起，朋友。[他斜视]}
### {142}{015}{Okay, okay. When I find sugar and tin, I'll come back. Don't go anywhere! [wink]}
{142}{015}{好的，好的。当我找到糖和锡的时候，我会回来的。哪儿也不要去！[眨眼]}


### {150}{}{Where am I gonna go from here?}
{150}{}{我该何去何从？}
### {151}{999}{[leave Smitty to think about the meaning of your words]}
{151}{999}{[让Smitty想想你的话的意思]}


### {200}{}{Oh, so, you need that, uh, how was it called... A PLUNGER! Of course, I had one somewhere... Around... Here! Wait, looks like the handle is broken... Yes, it is. I could fix it, of course, but I need a new handle. Bring me some hammer, it should do nicely.}
{200}{}{哦，所以，你需要，呃，它是怎么叫的。。。柱塞！当然，我在某个地方有一个。。。围绕在这里等等，看起来把手坏了。。。是的。我当然可以修，但我需要一个新把手。给我拿些锤子，应该很好。}
### {201}{022}{Smitty, you're always like this: you have everything, but broken!}
{201}{022}{史密蒂，你总是这样：你什么都有，但都坏了！}
### {202}{023}{What a fine coincidence - I have a spare hammer with me!}
{202}{023}{多巧啊，我随身带着一把备用锤子！}
### {203}{999}{I see. I'll go look for it.}
{203}{999}{我明白了。我去找它。}


### {210}{}{Of course I remember! So? Did you bring me the hammer? Or some handle?}
{210}{}{我当然记得！所以你给我带来锤子了吗？还是一些把手？}
### {211}{023}{Sure. Here.}
{211}{023}{当然在这里}
### {212}{999}{No, I'm still looking.}
{212}{999}{不，我还在找。}


### {220}{}{What do you think? That everything is easy? I'm ALWAYS making something useful practically from NOTHING. And sometimes you have to re-use the stuff you have, you know - but just to make those OTHER things better!}
{220}{}{你怎么看？一切都很容易？我总是从无到有地做出有用的东西。有时你不得不重复使用你所拥有的东西，你知道——但只是为了让其他东西变得更好！}
### {221}{999}{Yeah, for example, your Moonshine Machina Magnifico. I get it. Okay, I'll go look for a hammer.}
{221}{999}{是的，例如，你的Moonshine Machina Magnifico。我明白了。好吧，我去找一把锤子。}
### {222}{023}{Okay, okay. Don't get so defensive. Here's a hammer for you, give me that damn plunger.}
{222}{023}{好的，好的。别这么守势。给你一把锤子，把那个该死的柱塞给我。}


### {230}{}{See? So many worries, so few actual problems! [Smitty instantly replaces the handle of a plunger with the one from a hammer] Here, take your "treasure", heh-heh. I hope you'll figure out how to use it.}
{230}{}{看见那么多的担忧，那么少的实际问题！[Smitty立即用锤子上的柱塞手柄替换柱塞手柄]给，拿上你的“宝贝”，呵呵。我希望你能想出如何使用它。}
### {231}{999}{Come on, give it to me already.}
{231}{999}{来吧，已经给我了。}
### {232}{999}{Don't you worry about it!}
{232}{999}{别担心！}

#
#????????? ????????? (????????????? ???????)
# ????????????? ?????????
### {1000}{}{Hey, friend!}
{1000}{}{嘿，朋友！}
### {1001}{}{Hello! How are you doing?}
{1001}{}{你好你好吗？}
### {1002}{}{Hello there!}
{1002}{}{你好！}
### {1003}{}{Hey, friend! How are you?}
{1003}{}{嘿，朋友！你好吗}
### {1004}{}{I would gladly stop and chat... But let's do it some other time.}
{1004}{}{我很乐意停下来聊聊。。。但让我们改天再做吧。}
### {1005}{}{So good to see you!}
{1005}{}{很高兴见到你！}
### {1006}{}{Wanna chat? Suit yourself.}
{1006}{}{想聊聊吗？随你便。}
### {1007}{}{Listen, I stashed something for you. Okay, talk later.}
{1007}{}{听着，我给你藏了些东西。好的，稍后再谈。}
### {1008}{}{You should come to me more often.}
{1008}{}{你应该多来找我。}
### {1009}{}{Of course! Come by anytime!}
{1009}{}{当然随时来！}
# ??????????? ?????????
### {1010}{}{Don't bother me, I'm busy.}
{1010}{}{别打扰我，我很忙。}
### {1011}{}{Can't you see? I have no time to spare.}
{1011}{}{你看不见吗？我没有多余的时间。}
### {1012}{}{Hey! I'm trying to make these damn mechanisms here to work again!}
{1012}{}{嘿我正试图让这些该死的机制再次发挥作用！}
### {1013}{}{Listen, maybe not now? Good.}
{1013}{}{听着，也许现在不行？好的}
### {1014}{}{Instead of bugging me with questions, hand me over that wrench.}
{1014}{}{与其问我问题，不如把扳手递给我。}
### {1015}{}{Listen, don't touch me, let me rest a little.}
{1015}{}{听着，别碰我，让我休息一下。}
### {1016}{}{What do you want?}
{1016}{}{你想要什么？}
### {1017}{}{...And then I'm like - you are sparking here! Hilarious.}
{1017}{}{…然后我就想——你在这里闪闪发光！令人捧腹的}
### {1018}{}{...And then he's like - that's E-LEC-TREE-SEE-TEE!}
{1018}{}{…然后他说——那是E-LEC-TREE-SEE-TEE！}
### {1019}{}{Oh. Listen, let's talk a little later, okay?}
{1019}{}{哦听着，我们稍后再谈，好吗？}
# ????????????? ?????????
### {1020}{}{Get lost, dumbass!}
{1020}{}{迷路吧，蠢蛋！}
### {1021}{}{Get the hell out!}
{1021}{}{滚出去！}
### {1022}{}{Better don't take your chances, you freak!}
{1022}{}{最好不要冒险，你这个怪胎！}
### {1023}{}{Screw you!!!}
{1023}{}{去你的！！！}
### {1024}{}{Make like a tree and get out of here.}
{1024}{}{像棵树一样，离开这里。}
### {1025}{}{You're gonna get punched in the face if you don't get lost!}
{1025}{}{如果你不迷路，你会被打在脸上的！}
### {1026}{}{Make yourself invisible!}
{1026}{}{让自己隐形！}
### {1027}{}{What the heck do you want from me?!}
{1027}{}{你到底想从我这里得到什么？！}
### {1028}{}{How dare you?!}
{1028}{}{你怎么敢？！}
### {1029}{}{You piss me off! Go away!}
{1029}{}{你惹我生气！走开！}
#
#????????? ????????? (?????????????)
#
### {1030}{}{Alright, let's put this thingie here...}
{1030}{}{好吧，让我们把这个东西放在这里。。。}
### {1031}{}{This thing into that thing, aaand... Damn it!}
{1031}{}{这个东西变成那个东西，啊。。。该死！}
### {1032}{}{Wires, cords... And nothing works.}
{1032}{}{电线、电线。。。什么都不管用。}
### {1033}{}{Oh! My favorite screws...}
{1033}{}{哦我最喜欢的螺丝。。。}
### {1034}{}{My hands are so shaky...}
{1034}{}{我的手太颤抖了。。。}
### {1035}{}{I definitely need a drink!}
{1035}{}{我绝对需要喝一杯！}
### {1036}{}{Yeah, that's a pretty bad case of hand-crookery...}
{1036}{}{是的，这是一个非常糟糕的骗术案例。。。}
### {1037}{}{It's alright, we're gonna patch you up.}
{1037}{}{没关系，我们会给你包扎的。}
### {1038}{}{May it burn in hell!}
{1038}{}{愿它在地狱里燃烧！}
### {1039}{}{[rummages through some mechanism]}
{1039}{}{[翻找某种机制]}
