# This file describes the messages,
# used in the pop-up help scripts
#
# Created by Artem "Rainman" Samoylov
# 16/11/2010
#
#General
#
### {10}{}{Welcome to "Olympus 2207"!}
{10}{}{欢迎光临“奥林巴斯2207”！}
### {11}{}{If you are playing the game for the first time, we strongly recommend that you enable hints.}
{11}{}{如果您是第一次玩游戏，我们强烈建议您启用提示。}
### {12}{}{Do you want to get hints during gameplay?}
{12}{}{你想在游戏过程中得到提示吗？}
{13}{}{}
{14}{}{}
### {15}{}{You have completed enough tasks to move on to the next part of the game. To do this, "use" your bed on the first level.}
{15}{}{你已经完成了足够的任务，可以进入游戏的下一部分。要做到这一点，请在第一层“使用”你的床。}
### {16}{}{You have completed all the tasks and can now move on to the next part of the game. To do this, "use" your bed on the first level.}
{16}{}{您已经完成了所有任务，现在可以进入游戏的下一部分。要做到这一点，请在第一层“使用”你的床。}
### {17}{}{You have received your first item assembling task. To access the build panel, click on the "-HMS-" icon on the right side of the interface panel (see figure below) and follow the instructions. To gain access to the collection of other items, your hero must learn about the possibility of assembling them.}
{17}{}{您已收到第一个项目组装任务。要访问构建面板，请单击界面面板右侧的“-HMS-”图标（参见下图），然后按照说明进行操作。为了获得其他物品的集合，你的英雄必须了解组装它们的可能性。}
### {18}{}{To repair the fuse box, you can apply the "science" skill to it and fix it manually. Also, you can hack electronic locks, after opening their electric panel with a screwdriver.}
{18}{}{要修理保险丝盒，您可以将“科学”技能应用于保险丝盒并手动固定。此外，你可以在用螺丝刀打开电子锁的配电板后破解电子锁。}
### {19}{}{Be careful when trying to steal from someone, because in case of your "steal" skill being too low, there is a 25% chance that the victim will notice your malicious intentions and attack you! Keep in mind that to steal from merchants, your skill must be around at least 100-120%.}
{19}{}{当试图从某人那里偷东西时要小心，因为如果你的“偷”技能太低，受害者有25%的机会会注意到你的恶意并攻击你！请记住，要从商人那里偷东西，你的技能必须至少在100-120%左右。}
### {20}{}{By killing someone, you not only increase your kill count but also change your karma! Be extremely careful shooting the next person between the eyes, because if he turns out to be a character vital to the plot, you will have to pave the way through a mountain of corpses!}
{20}{}{通过杀人，你不仅增加了你的杀人次数，还改变了你的因果报应！拍摄下一个人时要格外小心，因为如果他是对情节至关重要的人物，你就必须在堆积如山的尸体中铺平道路！}
### {21}{}{When solving the tasks you face, remember that each decision you make affects your karma and the attitude of individual characters and entire locations towards you. The level of your karma depends on the options for lines available in dialogues, options for solving quests, and even the availability of quests.}
{21}{}{在解决你所面临的任务时，请记住，你所做的每一个决定都会影响你的因果报应以及各个角色和整个位置对你的态度。你的因果报应水平取决于对话中可用行的选项、解决任务的选项，甚至任务的可用性。}
### {22}{}{Fixing a sparking fuse box is a complicated and unsafe task! If your "Repair" skill is high enough, you can try to use it for repairs. If you doubt your repair abilities use the "Science" skill and try your luck with your hands and wits. Or if you have a silver tongue, you can just ask someone else to fix the fuse box for you. For example, Smitty at the Maintenance level.}
{22}{}{修理有火花的保险丝盒是一项复杂而不安全的任务！如果你的“修理”技能足够高，你可以试着用它来修理。如果你怀疑自己的修复能力，请使用“科学”技能，用你的双手和智慧碰碰运气。或者，如果你有一个银舌头，你可以请别人帮你修理保险丝盒。例如，“维护”级别的Smitty。}
### {23}{}{You must go down to the Farms and get a list of the daily tasks from the Herald. To move between the floors of Tartarus, "use" the passageways/stairs behind the guards.}
{23}{}{你必须去农场，从《先驱报》上得到一份每日任务清单。要在塔尔塔罗斯的楼层之间移动，请“使用”警卫后面的通道/楼梯。}
### {24}{}{RADIATION! Monitor your body's radiation levels using the "Rad-O-Meter" or the accumulated radiation messages in the information display on the left side of the control panel. If you have accumulated more than 300 rad, your Strength and Agility will decrease. Even after cleansing the body of radiation, it will take another couple of days for these stats to recover. If you accumulate more than 400-500 rad, you risk losing health points, also, your reduced stats might not recover. If you do not want to suffer from radiation - set the difficulty of the game to "easy" right now.}
{24}{}{辐射！使用“Rad-O-Meter”或控制面板左侧信息显示屏上的累积辐射信息来监测身体的辐射水平。如果你已经累积了超过300拉德，你的力量和敏捷将会降低。即使在清除了身体的辐射后，这些数据还需要几天才能恢复。如果你累积超过400-500拉德，你就有失去生命值的风险，而且，你减少的统计数据可能无法恢复。如果你不想遭受辐射，现在就把游戏的难度设置为“容易”。}
### {25}{}{Anderson is dead. Standing over the body of a defeated enemy, you look back at your long and difficult journey from a naive Servant to the conqueror of Olympus who defeated its "God". You are the first to reach the end of this path - and you are the first to be presented with the toughest choice. To take the highest power, the responsibility for mankind's survival, making the ultimate sacrifice in the hope to make things better - or to completely forfeit the vicious cycle, and let the inhabitants of Olympus create their destiny with their own will, choices, and mistakes.                                                        The fate of the whole Radius is in your hands.                                    Will you take Anderson's place as the head of Olympus?}
{25}{}{安德森死了。站在一个战败的敌人的尸体上，回顾你从一个天真的仆人到战胜“上帝”的奥林巴斯征服者的漫长而艰难的旅程。你是第一个到达这条道路尽头的人，也是第一个面临最艰难选择的人。为了获得最高的权力，承担人类生存的责任，做出最终的牺牲，希望让事情变得更好——或者完全放弃恶性循环，让奥林巴斯的居民用自己的意志、选择和错误创造自己的命运。整个Radius的命运掌握在你手中。你会接替安德森成为奥林巴斯的首领吗？}
### {26}{}{If this is not the first time you have decided to explore the world of "Olympus 2207", you can skip the initial stages of the game in Tartarus right now. This resolves all skipped quests at the lower end of possible experience points, with every outcome being neutral by default. Do you want to skip the initial stages of Tartarus?}
{26}{}{如果这不是你第一次决定探索“奥林巴斯2207”的世界，你现在可以跳过塔尔塔罗斯游戏的初始阶段。这将在可能的经验点的低端解决所有跳过的任务，默认情况下，每个结果都是中性的。你想跳过塔尔塔罗斯的初始阶段吗？}
### {27}{}{As the game progresses, you will encounter a large number of different items. The most important and interesting ones are marked with a * in the title. If you find such an item, hold on to it! Most likely it is an important part of a quest or the key to some amazing place in the game world!}
{27}{}{随着游戏的进行，你会遇到大量不同的物品。最重要和最有趣的在标题中用*标记。如果你找到这样的物品，就抓紧它！很可能它是任务的重要组成部分，或者是游戏世界中某个神奇地方的关键！}
### {28}{}{Your current resolution is too small to play the game comfortably. If you continue, you'll encounter problems, crashes and generally bad impression about everything. It is recommended to use resolution not less than 800x600 (and if you use "x2 Scaling", then 1600x1050).                                                                                                                               Press "Yes" to continue with the current resolution. "Close" to return to main menu.}
{28}{}{您当前的分辨率太小，无法舒适地玩游戏。如果你继续下去，你会遇到问题、崩溃和对每件事的普遍负面印象。建议使用不低于800x600的分辨率（如果使用“x2缩放”，则为1600x1050）。按“是”继续执行当前决议。“关闭”返回主菜单。}
