# ????? ?? ??????? ??饭??,
# ??????騥?? ? ???? ?業??
#
# Created by Artem "Rainman" Samoylov
# 30/07/2013
#
# ??? ????
# ?? - ?? ? ??? ???????? ????, ??? ????? ???? ???? ??? ??????? ?????? 
#
# ?????? 1
### {1}{}{You see a durable safe.}
{1}{}{你看到了一个耐用的保险箱。}
### {2}{}{This safe looks very durable.}
{2}{}{这个保险箱看起来很耐用。}

# ?????? 2
### {3}{}{The safe is locked with a magnetic lock. The nearby wall is torn apart, you can see all the wires.}
{3}{}{保险箱是用磁力锁锁住的。附近的墙被撕裂了，你可以看到所有的电线。}
### {4}{}{You could try to pick the right wires to unlock the magnetic lock.}
{4}{}{你可以试着挑选合适的电线来解锁磁锁。}

# ??????
### {5}{}{You should stop putting your fingers into live wires.}
{5}{}{你应该停止把手指伸进带电的电线里。}
### {6}{}{You see no switch on the generator. Looks like everything is in a fuse box.}
{6}{}{你看不到发电机上有开关。看起来所有东西都在保险丝盒里。}
### {7}{}{You thoroughly study the structure... but don't understand a thing.}
{7}{}{你彻底研究了结构。。。但什么都不懂。}
### {8}{}{It seems like the defense system is powered by the generator.}
{8}{}{看起来防御系统是由发电机供电的。}
### {9}{}{Someone with the skills of a mechanic could easily turn off the defense.}
{9}{}{一个拥有机械师技能的人可以很容易地关闭防御。}
#
#??????祭?? ??????
#
### {10}{}{Do you want to try different combinations of wires? If you fail, you could get electrocuted, while the security system changes the scheme.}
{10}{}{你想尝试不同的电线组合吗？如果你失败了，你可能会触电身亡，而安全系统会改变方案。}
### {11}{}{Yeah, let's try!}
{11}{}{是的，让我们试试！}
### {12}{}{No way, I don't want to get free electrocution!}
{12}{}{不可能，我不想免费触电！}
### {13}{}{I don't want to poke around these wires anymore.}
{13}{}{我不想再绕着这些电线转了。}
### {14}{}{Screw this, I'm no electrician! I'll somehow manage without it.}
{14}{}{去他妈的，我不是电工！没有它我会设法应付的。}
### {15}{}{You see 3 wires: red, blue, and green. You need to connect two of them. Which ones?}
{15}{}{您可以看到3根电线：红色、蓝色和绿色。你需要连接其中两个。哪一个？}
### {16}{}{Red + Blue}
{16}{}{红色+蓝色}
### {17}{}{Green + Red}
{17}{}{绿色+红色}
### {18}{}{Blue + Red}
{18}{}{蓝色+红色}
### {19}{}{Now you need to connect the third wire. To which one?}
{19}{}{现在你需要连接第三根电线。去哪一个？}
### {20}{}{Connect Red and Green}
{20}{}{连接红色和绿色}
### {21}{}{Connect Red and Blue}
{21}{}{连接红蓝}
### {22}{}{Connect Green and Red}
{22}{}{连接绿色和红色}
### {23}{}{Connect Green and Blue}
{23}{}{连接绿色和蓝色}
### {24}{}{Connect Blue and Red}
{24}{}{连接蓝色和红色}
### {25}{}{Connect Blue and Green}
{25}{}{连接蓝色和绿色}
### {26}{}{You got electrocuted.}
{26}{}{你触电了。}
### {27}{}{Oops! You had your finger electrocuted.}
{27}{}{哎呀！你的手指触电了。}
### {28}{}{You got bit by an electric current. The finger still hurts.}
{28}{}{你被电流咬了。手指仍然很疼。}
### {29}{}{You got electrocuted very badly.}
{29}{}{你触电得很厉害。}
#
#
#
### {30}{}{You did it! The safe is open!}
{30}{}{你做到了！保险箱打开了！}
