#############################################################
#????????? ???? ??? ???????? << ???????? >> 
#????? ?????? ? scripts.lst << 394 >>
#############################################################
#????????? ?????:
#?????? 1-9 - ???????? ?????????;
#?????? 10-29 - ?????????? ? ?????????;
#?????? 30-99 - ???? ?? ????, ?? ?????, ??? ??????????...
#?????, ?? ?????? ???????.
#?????? ????? ?????? 100, ?.?. 100 - ???? ???? ???????, 200 - ??????.
#??????? ????????? ???? ????? 10, ?.?. 100, 110, 120 ? ?.?. ??? ??? 
#??? ??????? 100 ???????????? Node010, ??? ??????? 240 - Node024.
#??? ??????? ?????? - ???????? ?????????, ?.?. ?? ??????? 650 ?????? ????? 651, 652, 653 ? ?.?. 
#??? ?????? ??????????? ???????????? ?????????????? ????? (????????, ??????? 360 ??????? ?? 3601 ? 3602,
#??? ?? ???????? ????????? Node, ?????? ?? ????? ? ??????? ????? - 361, 362 ? ?.?.)
#############################################################
#????? ??????????????? ??????? ?? ????????? ????????? ??????? ??????? ???????,
#??? ??? ???? ????? ????? ??????!!!
############################################################
#?????????? ??? "????? 2207", by Rainman, 06/11/2010
#############################################################
#
#???????? ????????
#
### {1}{}{You see a Defender.}
{1}{}{你看到了一个卫士。}
### {2}{}{You see a Defender.}
{2}{}{你看到了一个卫士。}
### {3}{}{You see a Defender.}
{3}{}{你看到了一个卫士。}
### {4}{}{You see a Defender.}
{4}{}{你看到了一个卫士。}
### {5}{}{You see a Defender.}
{5}{}{你看到了一个卫士。}
### {6}{}{A sight of his armor makes you stare in awe.}
{6}{}{看到他的盔甲，你会敬畏地凝视。}
### {7}{}{Black smoke billows from the exhaust pipes behind him.}
{7}{}{他身后的排气管冒出滚滚黑烟。}
### {8}{}{Every move of this warrior shows his impenetrability and power.}
{8}{}{这位战士的一举一动都显示出他的坚不可摧和威力。}
### {9}{}{...Although, there's probably just a normal human body under all this metal...}
{9}{}{…虽然，在所有这些金属下面可能只有一个正常的人体。。。}
#
#????? ?????????? ??????
#
### {10}{}{Seeker?}
{10}{}{探索者}
### {11}{}{Now's not the time.}
{11}{}{现在不是时候。}
### {12}{}{Continue your mission.}
{12}{}{继续你的使命。}
### {13}{}{What are you doing here?}
{13}{}{你在这里干什么？}
### {14}{}{On a mission, aren't you?}
{14}{}{执行任务，不是吗？}
### {15}{}{Herald!? What the hell are you doing here?}
{15}{}{预示你到底在这里干什么？}
### {16}{}{You don't belong here, return to Tartarus.}
{16}{}{你不属于这里，回到塔尔塔罗斯。}
### {17}{}{Get back to Tartarus before I report about you.}
{17}{}{在我报告你的情况之前，先回到塔尔塔罗斯。}
### {18}{}{Herald shouldn't be here. It's dangerous.}
{18}{}{先驱不应该在这里。这很危险。}
### {19}{}{Decided to remember the old days in Radius?}
{19}{}{决定回忆在Radius的旧时光吗？}
### {20}{}{You see a scout.}
{20}{}{你看到一个侦察兵。}
### {21}{}{You see a Seeker.}
{21}{}{你看到一个探索者。}
### {22}{}{You see a military.}
{22}{}{你看到了一支军队。}
### {23}{}{Judging by his uniform, he definitely belongs to the military.}
{23}{}{从他的制服来看，他肯定是军人。}
### {24}{}{His armor is adjusted to his body and looks very comfortable.}
{24}{}{他的盔甲根据他的身体进行了调整，看起来非常舒适。}
### {30}{}{Seeker?}
{30}{}{探索者}
### {31}{}{Just returned? Relax, enjoy yourself.}
{31}{}{刚回来？放松，尽情享受。}
### {32}{}{Yeah, Radius got you pretty bad...}
{32}{}{是的，Radius把你弄得很惨。。。}
### {33}{}{Wondering what to do? Ask Richards!}
{33}{}{想知道该怎么办？问问理查兹！}
### {34}{}{On a mission?}
{34}{}{执行任务？}
### {35}{}{Herald!? What the hell are you doing here?}
{35}{}{预示你到底在这里干什么？}
### {36}{}{You don't belong here, return to Tartarus.}
{36}{}{你不属于这里，回到塔尔塔罗斯。}
### {37}{}{Get back to Tartarus before I report about you.}
{37}{}{在我报告你的情况之前，先回到塔尔塔罗斯。}
### {38}{}{I hope you're not going to preach here, right? [laughs]}
{38}{}{我希望你不会在这里说教，对吧？[笑]}
### {39}{}{Taking a breath of fresh air? Don't let the superiors see you.}
{39}{}{呼吸一口新鲜空气？不要让上级看到你。}
####
### {40}{}{You see an engineer.}
{40}{}{你看到一个工程师。}
### {41}{}{You see a techie.}
{41}{}{你看到一个技术人员。}
### {42}{}{A man wearing a dirty lab coat of a scientist.}
{42}{}{一个穿着科学家的脏实验服的男人。}
### {43}{}{You can tell for sure that this man knows his stuff about tech.}
{43}{}{你可以肯定地看出，这个人对科技很了解。}
### {44}{}{A Seeker? Don't get in my way!}
{44}{}{探索者？别挡我的路！}
### {45}{}{Military, you're always useless.}
{45}{}{军人，你总是没用。}
### {46}{}{You, Seekers, are only good to be sent into Radius.}
{46}{}{你们，探索者，只适合被派往Radius。}
### {47}{}{Herald!? What are you doing around here!?}
{47}{}{预示你在这附近干什么！？}
### {48}{}{What? Did they destroy something in Tartarus again?}
{48}{}{什么他们又在鞑靼摧毁了什么吗？}
### {49}{}{Did the slaves break the converter again? Seriously?}
{49}{}{奴隶们又把转换器弄坏了吗？认真地}
### {50}{}{Who the hell are you?}
{50}{}{你到底是谁？}
### {51}{}{Get lost, or I call the guards!}
{51}{}{迷路，否则我叫警卫！}
### {52}{}{I don't care who you are, or what do you need. Just leave me alone.}
{52}{}{我不在乎你是谁，也不在乎你需要什么。别管我。}
### {53}{}{Can't you see!? I'm trying to work here!!!}
{53}{}{你看不见！？我想在这里工作！！！}
### {54}{}{No, NO! I don't know what you need!}
{54}{}{不，不！我不知道你需要什么！}
### {55}{}{I can't get used to this armor.}
{55}{}{我不习惯这种盔甲。}
### {56}{}{It's great to be a Defender! I wish I could take a shower though.}
{56}{}{成为一名后卫真是太棒了！不过我希望我能洗个澡。}
### {57}{}{A great armor, isn't it? I feel sorry for the previous owner. Whoever he was.}
{57}{}{一件伟大的盔甲，不是吗？我为前主人感到难过。不管他是谁。}
### {58}{}{I'm gonna make some smoke here, alright? ::metallic laugh::}
{58}{}{我要在这里抽点烟，好吗？：金属笑声：}
### {59}{}{I feel INDESTRUCTIBLE!}
{59}{}{我感到难以忍受！}
####
### {60}{}{You see a female scientist.}
{60}{}{你看到一位女科学家。}
### {61}{}{You see a female techie.}
{61}{}{你看到一个女性技术人员。}
### {62}{}{This woman in a dirty lab coat looks very focused.}
{62}{}{这个穿着脏实验服的女人看起来很专注。}
### {63}{}{She looks quite beautiful even with this dark circles under her eyes.}
{63}{}{即使有黑眼圈，她看起来也很漂亮。}
### {64}{}{Military, stop coming in here!!}
{64}{}{军人，别进来了！！}
### {65}{}{You are strong, of course, and good-looking in this uniform - but I have work to do.}
{65}{}{当然，你穿着这身制服很强壮，也很好看——但我还有工作要做。}
### {66}{}{No, NO! And tell your friends that I don't have time for you all!}
{66}{}{不，不！告诉你的朋友，我没有时间和你们所有人在一起！}
### {67}{}{Hey, old man! What are you doing here?}
{67}{}{嘿，老头！你在这里干什么？}
### {68}{}{Listen, you'd better go back to Tartarus, to calm slaves!}
{68}{}{听着，你最好回到塔尔塔罗斯，让奴隶们平静下来！}
### {69}{}{Herald, did you pick the wrong elevator? You should press down, not up!}
{69}{}{先驱，你选错电梯了吗？你应该往下压，而不是往上压！}
####
### {70}{}{Oh, you! Push that gun, be so kind. It's jammed again.}
{70}{}{哦，你！推那把枪，别客气。它又卡住了。}
### {71}{}{Yes, just push it. It's a prototype, it gets jammed sometimes.}
{71}{}{是的，推一下就行了。这是一个原型，有时会卡住。}
### {72}{}{Whoa! YES! Such POWER! Did everybody see that!? That's my baby!}
{72}{}{哇！是的！这样的力量！大家都看到了吗！？那是我的宝贝！}
### {73}{}{Look at how messed up he is! I'll never get tired of watching!}
{73}{}{看看他有多糟糕！我永远不会厌倦观看！}
### {74}{}{Thanks for helping me with testing.}
{74}{}{谢谢你帮我做测试。}
####
### {75}{}{You see the head of the Punishers.}
{75}{}{你看到了惩罚者的首领。}
### {76}{}{This Defender is a ruthless leader of cleaners.}
{76}{}{这位卫士是一位无情的清洁工领袖。}
### {77}{}{Alright boys, let's take care of this filthy scum!}
{77}{}{好了，孩子们，让我们来照顾这个肮脏的渣滓！}
### {78}{}{I brought some music so it wouldn't be too boring!}
{78}{}{我带来了一些音乐，这样就不会太无聊了！}
### {79}{}{Want to go home already, rookie? We are returning when we're done, not before.}
{79}{}{想回家了吗，菜鸟？我们在结束后回来，而不是之前。}
### {80}{}{I'm not sure, rookie. Do you think they had enough? I don't want to waste bullets...}
{80}{}{我不确定，菜鸟。你认为他们受够了吗？我不想浪费子弹。。。}
### {81}{}{Yes, the rest will scatter anyway. It's time to get back.}
{81}{}{是的，其余的都会散开的。是时候回去了。}
### {82}{}{No one should be left alive! Each of these scums must be murdered! Every last one of them!}
{82}{}{任何人都不应该活着！这些卑鄙小人中的每一个都必须被谋杀！他们中的每一个人！}
### {83}{}{Yes, maybe you're right.}
{83}{}{是的，也许你是对的。}
### {84}{}{Hah, that's the spirit! Let's look for survivors and tear them apart like a herd of fucking Lavash!}
{84}{}{哈，这就是精神！让我们寻找幸存者，像一群该死的熔岩一样把他们撕裂！}
### {85}{}{[more]}
{85}{}{[更多]}
### {86}{}{You see Defender from Punishers.}
{86}{}{你可以看到惩罚者的捍卫者。}
### {87}{}{His armored suit, covered in blood, speaks for itself.}
{87}{}{他那身沾满鲜血的盔甲，不言自明。}
### {88}{}{Repeat after me, rookie: aim - shoot - thrill!}
{88}{}{跟我重复一遍，菜鸟：瞄准-射击-刺激！}
### {89}{}{They are all guilty! And we are just protecting our home.}
{89}{}{他们都有罪！我们只是在保护我们的家园。}
### {90}{}{Don't think! Enjoy the process!}
{90}{}{别想！享受这个过程！}
### {91}{}{Where did you come from, big-mouth? Relax and shoot!}
{91}{}{你从哪里来的，大嘴？放松并拍摄！}
### {92}{}{We're not done here.}
{92}{}{我们在这里还没有结束。}
### {93}{}{The leader of Punisher is dead. Your mission is over. You return to "Olympus".}
{93}{}{惩罚者的首领死了。你的任务结束了。你回到“奥林巴斯”。}
### {94}{}{You left the location. Your mission is over. You return to "Olympus".}
{94}{}{你离开了这个地方。你的任务结束了。你回到“奥林巴斯”。}
{95}{}{}
{96}{}{}
####
### {97}{}{INTRUDER! GUARDS!!!}
{97}{}{入侵者！警卫！！！}
### {98}{}{AN INTRUDER IS HERE! ATTACK HIM!!}
{98}{}{入侵者来了！攻击他！！}
### {99}{}{INTRUDER IS IN THE TOWER!! KILL HIM!!}
{99}{}{闯入者在塔里！！杀了他！！}
#
#????????? ????????? (????????????? ???????)
#
{1000}{}{}
{1001}{}{}
{1002}{}{}
{1003}{}{}
{1004}{}{}
{1005}{}{}
{1006}{}{}
{1007}{}{}
{1008}{}{}
{1009}{}{}
#
#????????? ????????? (??????????? ???????)
#
{1010}{}{}
{1011}{}{}
{1012}{}{}
{1013}{}{}
{1014}{}{}
{1015}{}{}
{1016}{}{}
{1017}{}{}
{1018}{}{}
{1019}{}{}
#
#????????? ????????? (????????????? ???????)
#
{1020}{}{}
{1021}{}{}
{1022}{}{}
{1023}{}{}
{1024}{}{}
{1025}{}{}
{1026}{}{}
{1027}{}{}
{1028}{}{}
{1029}{}{}
#
#????????? ????????? (?????? ?????)
#
{1030}{}{}
{1031}{}{}
{1032}{}{}
{1033}{}{}
{1034}{}{}
{1035}{}{}
{1036}{}{}
{1037}{}{}
{1038}{}{}
{1039}{}{}
