#######################################################
#
# Map Level Names -- AUTOMAP Names
#
#######################################################

#----------------------------------------
# 00: Desert Encounter 1, desert1.MAP
#----------------------------------------
### {200}{}{Barren desert}
{200}{}{贫瘠的沙漠}
### {201}{}{}
{201}{}{error : string is empty}
### {202}{}{}
{202}{}{error : string is empty}
#----------------------------------------
# 01: Desert Encounter 2, desert2.MAP
#----------------------------------------
### {203}{}{Desecrated Wasteland}
{203}{}{荒芜的荒原}
### {204}{}{}
{204}{}{error : string is empty}
### {205}{}{}
{205}{}{error : string is empty}
#----------------------------------------
# 02: Desert Encounter 3, desert3.MAP
#----------------------------------------
### {206}{}{Cactus Forest}
{206}{}{仙人掌林}
### {207}{}{}
{207}{}{error : string is empty}
### {208}{}{}
{208}{}{error : string is empty}
#----------------------------------------
# 03: Desert Encounter 4, desert4.MAP
#----------------------------------------
### {209}{}{Desert camp}
{209}{}{沙漠营地}
### {210}{}{}
{210}{}{error : string is empty}
### {211}{}{}
{211}{}{error : string is empty}
#----------------------------------------
# 04: Road Encounter 1, ROAD1.MAP
#----------------------------------------
### {212}{}{ Federal highway}
{212}{}{联邦公路}
### {213}{}{}
{213}{}{error : string is empty}
### {214}{}{}
{214}{}{error : string is empty}
#----------------------------------------
# 05: Road Encounter 2, ROAD2.MAP
#----------------------------------------
### {215}{}{Federal Highway}
{215}{}{联邦公路}
### {216}{}{}
{216}{}{error : string is empty}
### {217}{}{}
{217}{}{error : string is empty}
#----------------------------------------
# 06: Road Encounter 3, ROAD3.MAP
#----------------------------------------
### {218}{}{Deserted highway}
{218}{}{废弃公路}
### {219}{}{}
{219}{}{error : string is empty}
### {220}{}{}
{220}{}{error : string is empty}
#----------------------------------------
# 07: Road Encounter 4, ROAD4.MAP
#----------------------------------------
### {221}{}{Deserted highway}
{221}{}{废弃公路}
### {222}{}{}
{222}{}{error : string is empty}
### {223}{}{}
{223}{}{error : string is empty}
#----------------------------------------
# 08: City Encounter 1, city1.MAP
#----------------------------------------
### {224}{}{Ruins of the sleeping area}
{224}{}{睡眠区废墟}
### {225}{}{}
{225}{}{error : string is empty}
### {226}{}{}
{226}{}{error : string is empty}
#----------------------------------------
# 09: City Encounter 2, city2.MAP
#----------------------------------------
### {227}{}{Ruins of the business district}
{227}{}{商业区废墟}
### {228}{}{Collector}
{228}{}{收集器}
### {229}{}{}
{229}{}{error : string is empty}
#----------------------------------------
# 10: City Encounter 3, city3.MAP
#----------------------------------------
### {230}{}{Dilapidated house}
{230}{}{破旧的房子}
### {231}{}{}
{231}{}{error : string is empty}
### {232}{}{}
{232}{}{error : string is empty}
#----------------------------------------
# 11: City Encounter 4, city4.MAP
#----------------------------------------
### {233}{}{Camp among the ruins}
{233}{}{废墟中的营地}
### {234}{}{}
{234}{}{error : string is empty}
### {235}{}{}
{235}{}{error : string is empty}
#----------------------------------------
#12: Mountain Encounter 1, MOUNT1.MAP
#----------------------------------------
### {236}{}{ Gorge}
{236}{}{峡}
### {237}{}{}
{237}{}{error : string is empty}
### {238}{}{}
{238}{}{error : string is empty}
#----------------------------------------
# 13: Mountain Encounter 2, MOUNT2.MAP
#----------------------------------------
### {239}{}{ Gorge}
{239}{}{峡}
### {240}{}{}
{240}{}{error : string is empty}
### {241}{}{}
{241}{}{error : string is empty}
#----------------------------------------
# 14: Mountain Encounter 3, MOUNT3.MAP
#----------------------------------------
### {242}{}{Camp in the mountains}
{242}{}{在山上露营}
### {243}{}{}
{243}{}{error : string is empty}
### {244}{}{}
{244}{}{error : string is empty}
#----------------------------------------
# 15: Mountain Encounter 4, MOUNT4.MAP
#----------------------------------------
### {245}{}{Gorge}
{245}{}{峡}
### {246}{}{Rocky Cave}
{246}{}{Rocky Cave}
### {247}{}{}
{247}{}{error : string is empty}
#----------------------------------------
# 16: Mountain Encounter 5, MOUNT5.MAP
#----------------------------------------
### {248}{}{ Gorge}
{248}{}{峡}
### {249}{}{Ring Cave}
{249}{}{环形洞穴}
### {250}{}{}
{250}{}{error : string is empty}
#----------------------------------------
# 17: Mountain Encounter 6, MOUNT6.MAP
#----------------------------------------
### {251}{}{Gorge}
{251}{}{峡}
### {252}{}{Rocky Cave}
{252}{}{Rocky Cave}
### {253}{}{}
{253}{}{error : string is empty}
#----------------------------------------
# 18: Coast Encounter 1, COAST1.MAP
#----------------------------------------
### {254}{}{Dirty beach}
{254}{}{肮脏的海滩}
### {255}{}{}
{255}{}{error : string is empty}
### {256}{}{}
{256}{}{error : string is empty}
#----------------------------------------
# 19: Coast Encounter 2, COAST2.MAP
#----------------------------------------
### {257}{}{Rocky shore}
{257}{}{岩石海岸}
### {258}{}{}
{258}{}{error : string is empty}
### {259}{}{}
{259}{}{error : string is empty}
#----------------------------------------
# 20: Coast Encounter 3, COAST3.MAP
#----------------------------------------
### {260}{}{ Hut on the shore}
{260}{}{岸边的小屋}
### {261}{}{}
{261}{}{error : string is empty}
### {262}{}{}
{262}{}{error : string is empty}
#----------------------------------------
# 21: Villa1, artemple.MAP
#----------------------------------------
### {263}{}{ Sleeping area}
{263}{}{睡眠区}
### {264}{}{}
{264}{}{error : string is empty}
### {265}{}{}
{265}{}{error : string is empty}
#----------------------------------------
# 22: Villa2, VLPlaza.MAP
#----------------------------------------
### {266}{}{Plaza de la Sombra}
{266}{}{索布拉广场}
### {267}{}{The bottom of the well}
{267}{}{井底}
### {268}{}{Upper floor of the Town Hall}
{268}{}{市政厅上层}
#----------------------------------------
# 23: Villa3, VLCave.MAP
#----------------------------------------
### {269}{}{Cellars of the sleeping area}
{269}{}{睡眠区地窖}
### {270}{}{Cellars of the central district}
{270}{}{中区地窖}
### {271}{}{Basement of the Town Hall}
{271}{}{市政厅地下室}
#----------------------------------------
# 24: Villa4, VLGard.MAP
#----------------------------------------
### {272}{}{Maize plantations}
{272}{}{玉米种植园}
### {273}{}{}
{273}{}{error : string is empty}
### {274}{}{}
{274}{}{error : string is empty}
#----------------------------------------
# 25: FlagstaffCity, PoolCity.MAP
#----------------------------------------
### {275}{}{ Residential area}
{275}{}{住宅区}
### {276}{}{Church basement}
{276}{}{教堂地下室}
### {277}{}{}
{277}{}{error : string is empty}
#----------------------------------------
# 26: FlagstaffSlave, PoolSlav.MAP
#----------------------------------------
### {278}{}{Garrison and prison}
{278}{}{驻军和监狱}
### {279}{}{}
{279}{}{error : string is empty}
### {280}{}{}
{280}{}{error : string is empty}
#----------------------------------------
# 27: FlagstaffMine, PoolMine.MAP
#----------------------------------------
### {281}{}{ Mine Administration}
{281}{}{矿山管理}
### {282}{}{}
{282}{}{error : string is empty}
### {283}{}{}
{283}{}{error : string is empty}
#----------------------------------------
# 28: FlagstaffGard, PoolGard.MAP
#----------------------------------------
### {284}{}{ Abandoned area}
{284}{}{废弃区域}
### {285}{}{Ranger's Hideout}
{285}{}{游骑兵的藏身处}
### {286}{}{}
{286}{}{error : string is empty}
#----------------------------------------
# 29: GarageSign, GCSign.MAP
#----------------------------------------
### {287}{}{Business district}
{287}{}{商业区}
### {288}{}{}
{288}{}{error : string is empty}
### {289}{}{}
{289}{}{error : string is empty}
#----------------------------------------
# 30: GarageHome, GCHome.MAP
#----------------------------------------
### {290}{}{Scavenger shacks}
{290}{}{拾荒者棚屋}
### {291}{}{}
{291}{}{error : string is empty}
### {292}{}{}
{292}{}{error : string is empty}
#----------------------------------------
# 31: GarageDsrt, GCDstr.MAP
#----------------------------------------
### {293}{}{ Abandoned factory}
{293}{}{废弃工厂}
### {294}{}{Abandoned factory}
{294}{}{废弃工厂}
### {295}{}{Abandoned factory}
{295}{}{废弃工厂}
#----------------------------------------
# 32: SanBrahminSign, SBSign.MAP
#----------------------------------------
### {296}{}{Missionaries' Camp}
{296}{}{传教士营地}
### {297}{}{Dry collector}
{297}{}{干式收集器}
### {298}{}{}
{298}{}{error : string is empty}
#----------------------------------------
# 33: SanBrahminCity, SBChurch.MAP
#----------------------------------------
### {299}{}{Ancient Pueblo}
{299}{}{古代普韦布洛}
### {300}{}{Sanctuary Dungeon}
{300}{}{避难所地牢}
### {301}{}{The Sanctuary of the Divine Brahmin}
{301}{}{神圣婆罗门的圣地}
#----------------------------------------
# 34: SanBrahminTabl, SBTabl.MAP
#----------------------------------------
### {302}{}{ Brahmin pens}
{302}{}{婆罗门笔}
### {303}{}{}
{303}{}{error : string is empty}
### {304}{}{}
{304}{}{error : string is empty}
#----------------------------------------
# 35: TwoSunCity, TSCity.MAP
#----------------------------------------
### {305}{}{Settlement of tinsmiths}
{305}{}{锡匠的安置}
### {306}{}{}
{306}{}{error : string is empty}
### {307}{}{}
{307}{}{error : string is empty}
#----------------------------------------
# 36: TwoSunAngar, TSGarage.MAP
#----------------------------------------
### {308}{}{Workshop}
{308}{}{车间}
### {309}{}{}
{309}{}{error : string is empty}
### {310}{}{}
{310}{}{error : string is empty}
#----------------------------------------
# 37: TwoSunDstr, TSDstr.MAP
#----------------------------------------
### {311}{}{Ruins of a business center}
{311}{}{商业中心废墟}
### {312}{}{Hiding of runaway slaves}
{312}{}{逃亡奴隶的藏匿}
### {313}{}{Hiding of runaway slaves}
{313}{}{逃亡奴隶的藏匿}
#----------------------------------------
#38: TwoSunZAX, TSGrave.MAP
#----------------------------------------
### {314}{}{ Control Center, level 1}
{314}{}{控制中心，1级}
### {315}{}{Control Center, level 4}
{315}{}{控制中心，4级}
### {316}{}{Control Center, level 5}
{316}{}{控制中心，5级}
#----------------------------------------
# 39: Puerto1, PSSign.MAP
#----------------------------------------
### {317}{}{Old Town}
{317}{}{老城}
### {318}{}{The second floor of the hotel}
{318}{}{酒店二楼}
### {319}{}{Top floor of the hotel}
{319}{}{酒店顶层}
#----------------------------------------
# 40: Puerto2, PSDocs.MAP
#----------------------------------------
### {320}{}{Pier}
{320}{}{码头}
### {321}{}{Add-on}
{321}{}{加载项}
### {322}{}{Wheelhouse}
{322}{}{驾驶室}
#----------------------------------------
# 41: Puerto3, PSBasa.MAP
#----------------------------------------
### {323}{}{Upper deck}
{323}{}{上层甲板}
### {324}{}{Lower deck}
{324}{}{下层甲板}
### {325}{}{Middle deck}
{325}{}{中间甲板}
#----------------------------------------
# 42: RangersRoad, RRoad.MAP
#----------------------------------------
### {326}{}{The road to the dam}
{326}{}{通往大坝的道路}
### {327}{}{Vault from the raiders}
{327}{}{躲避袭击者}
### {328}{}{}
{328}{}{error : string is empty}
#----------------------------------------
# 43: RangersBasa, RBasa.MAP
#----------------------------------------
### {329}{}{Rangers Infocenter}
{329}{}{游骑兵信息中心}
### {330}{}{Superstructure, 1st floor}
{330}{}{上层建筑，一层}
### {331}{}{Superstructure, 2nd floor}
{331}{}{二层上部结构}
#----------------------------------------
# 44: RangersRadio, RRadio.MAP
#----------------------------------------
### {332}{}{Ranger Radio Station}
{332}{}{Ranger电台}
### {333}{}{Radio transmitter utility room}
{333}{}{无线电发射机杂物间}
### {334}{}{}
{334}{}{error : string is empty}
#----------------------------------------
# 45: RangersDumba, RDumba.MAP
#----------------------------------------
### {335}{}{Power plant}
{335}{}{发电厂}
### {336}{}{Control Center}
{336}{}{控制中心}
### {337}{}{Elevator shaft}
{337}{}{电梯井}
#----------------------------------------
# 46: PhoenixSign, PXSign.MAP
#----------------------------------------
### {338}{}{City gates}
{338}{}{城门}
### {339}{}{Collector Chamber}
{339}{}{收集器室}
### {340}{}{}
{340}{}{error : string is empty}
#----------------------------------------
# 47: PhoenixCenter, PXCenter.MAP
#----------------------------------------
### {341}{}{Business center}
{341}{}{商务中心}
### {342}{}{Casino Basement}
{342}{}{赌场地下室}
### {343}{}{Second floor of the casino}
{343}{}{赌场二楼}
#----------------------------------------
# 48: PhoenixBndcs, PXBndcs.MAP
#----------------------------------------
### {344}{}{Slums}
{344}{}{贫民窟}
### {345}{}{Arena}
{345}{}{竞技场}
### {346}{}{Bandit district}
{346}{}{班迪特区}
#----------------------------------------
# 49: PhoenixCity, PXCity.MAP
#----------------------------------------
### {347}{}{Entrance to the Cathedral}
{347}{}{大教堂入口}
### {348}{}{Crater}
{348}{}{坑}
### {349}{}{}
{349}{}{error : string is empty}
#----------------------------------------
# 50: PhoenixVlt, PXVault.MAP
#----------------------------------------
### {350}{}{Vault 25, passage}
{350}{}{拱顶25，通道}
### {351}{}{Vault 25, laboratory}
{351}{}{25号仓库，实验室}
### {352}{}{Vault 25, control center}
{352}{}{保险库25，控制中心}
#----------------------------------------
# 51: PhoenixAnal, PXAnal.MAP
#----------------------------------------
### {353}{}{ Southern Collector}
{353}{}{南方收藏家}
### {354}{}{Eastern Collector}
{354}{}{东方收藏家}
### {355}{}{Western Collector}
{355}{}{西方收藏家}
#----------------------------------------
# 52: PhoenixDstr, PXDstr.MAP
#----------------------------------------
### {356}{}{Union Station}
{356}{}{联合车站}
### {357}{}{Northern Collector}
{357}{}{北方收藏家}
### {358}{}{The Secret Lodge}
{358}{}{秘密小屋}
#----------------------------------------
# 53: Car Desert out-of-gas, CarDesrt.MAP
#----------------------------------------
### {359}{}{Desert}
{359}{}{沙漠}
### {360}{}{}
{360}{}{error : string is empty}
### {361}{}{}
{361}{}{error : string is empty}
#----------------------------------------
# 54: PhoenixElctr, PXElectr.MAP
#----------------------------------------
### {362}{}{Power plant pass-through}
{362}{}{发电厂通道}
### {363}{}{Power plant basements}
{363}{}{发电厂地下室}
### {364}{}{Power plant premises}
{364}{}{发电厂厂房}
#----------------------------------------
# 55: Vault27a, VaultA.MAP
#----------------------------------------
### {365}{}{Parking lot}
{365}{}{停车场}
### {366}{}{Underground descent}
{366}{}{地下下降}
### {367}{}{}
{367}{}{error : string is empty}
#----------------------------------------
# 56: Vault27b, VaultB.MAP
#----------------------------------------
### {368}{}{ Residential premises}
{368}{}{住宅}
### {369}{}{Control Center}
{369}{}{控制中心}
### {370}{}{Reactor level}
{370}{}{反应堆液位}
#----------------------------------------
# 57: CGrandeWater, CGWater.MAP
#----------------------------------------
### {371}{}{Water station}
{371}{}{供水站}
### {372}{}{}
{372}{}{error : string is empty}
### {373}{}{}
{373}{}{error : string is empty}
#----------------------------------------
# 58: CGrandeHomes, CGGrande.MAP
#----------------------------------------
### {374}{}{Hacienda of Count Bustos}
{374}{}{布斯托斯伯爵庄园}
### {375}{}{Hacienda, basement}
{375}{}{Hacienda，地下室}
### {376}{}{Hacienda, 2nd floor}
{376}{}{Hacienda，2楼}
#----------------------------------------
# 59: CGrandeGrave, CGGrave.MAP
#----------------------------------------
### {377}{}{The territory of the burial ground}
{377}{}{墓地的范围}
### {378}{}{Dilapidated basement}
{378}{}{破旧的地下室}
### {379}{}{}
{379}{}{error : string is empty}
#----------------------------------------
# 60: InfernoRoad, INFERNOa.MAP
#----------------------------------------
### {380}{}{Motorway}
{380}{}{高速公路}
### {381}{}{Sewage system}
{381}{}{污水系统}
### {382}{}{}
{382}{}{error : string is empty}
#----------------------------------------
# 61: InfernoCity, InfCity.MAP
#----------------------------------------
### {383}{}{Destroyed quarter}
{383}{}{被摧毁的季度}
### {384}{}{Sewage system}
{384}{}{污水系统}
### {385}{}{}
{385}{}{error : string is empty}
#----------------------------------------
# 62: InfernoShop, InfShop.Map
#----------------------------------------
### {386}{}{Destroyed supermarket}
{386}{}{超市被毁}
### {387}{}{Sewage system}
{387}{}{污水系统}
### {388}{}{}
{388}{}{error : string is empty}
#----------------------------------------
# 63: InfernoPolic, InfPolic.MAP
#----------------------------------------
### {389}{}{Destroyed police station}
{389}{}{被摧毁的警察局}
### {390}{}{Sewage system}
{390}{}{污水系统}
### {391}{}{}
{391}{}{error : string is empty}
#----------------------------------------
# 64: CNuevaCity, CNCity.MAP
#----------------------------------------
### {392}{}{Casa Nueva Settlement}
{392}{}{Casa Nueva定居点}
### {393}{}{Basements of Casa Nueva}
{393}{}{Casa Nueva的地下室}
### {394}{}{Upper floor of the Town Hall}
{394}{}{市政厅上层}
#----------------------------------------
# 65: CNuevaGard, CNGard.MAP
#----------------------------------------
### {395}{}{Plantations of fire agave}
{395}{}{火龙舌兰种植园}
### {396}{}{}
{396}{}{error : string is empty}
### {397}{}{}
{397}{}{error : string is empty}
#----------------------------------------
#66: CNuevaLab, CNLab.MAP
#----------------------------------------
### {398}{}{ Administration of the complex}
{398}{}{综合体的管理}
### {399}{}{Complex A}
{399}{}{综合体A}
### {400}{}{Complex B}
{400}{}{综合体B}
#----------------------------------------
# 67: RaidersMap, RAIDERS.MAP
#----------------------------------------
### {401}{}{The mainline workers' camp}
{401}{}{主线工人营地}
### {402}{}{The Leader's Shack}
{402}{}{领袖的枷锁}
### {403}{}{Fuel depot}
{403}{}{燃料库}
#----------------------------------------
# 68: JackalsMap, JACKALS.MAP
#----------------------------------------
### {404}{}{A house in the desert}
{404}{}{沙漠中的一所房子}
### {405}{}{Jackal Burrows}
{405}{}{Jackal Burrows}
### {406}{}{Jackal Warehouses}
{406}{}{豺狼仓库}
#----------------------------------------
# 69: PuertoDestroy, PSDstr.MAP
#----------------------------------------
### {407}{}{The affected area}
{407}{}{受影响区域}
### {408}{}{}
{408}{}{error : string is empty}
### {409}{}{}
{409}{}{error : string is empty}
#----------------------------------------
# 70: FlagstaffCave, FlagCave.MAP
#----------------------------------------
### {410}{}{Main drift}
{410}{}{主巷道}
### {411}{}{Depleted drift}
{411}{}{贫化漂移}
### {412}{}{Ore production}
{412}{}{矿石产量}
#----------------------------------------
# 71: MotelMap, MOTEL.MAP
#----------------------------------------
### {413}{}{The territory of the motel}
{413}{}{汽车旅馆的地盘}
### {414}{}{Old Vault}
{414}{}{旧保险库}
### {415}{}{}
{415}{}{error : string is empty}
#----------------------------------------
# 72: SanFelipeLight, FelipeA.MAP
#----------------------------------------
### {416}{}{Settlement at the lighthouse}
{416}{}{灯塔定居点}
### {417}{}{Artificial grotto}
{417}{}{人工石窟}
### {418}{}{Old Lighthouse}
{418}{}{旧灯塔}
#----------------------------------------
# 73: BSCamp1, BSCampA.MAP
#----------------------------------------
### {419}{}{Camp of the Brotherhood of Steel}
{419}{}{钢铁兄弟会营地}
### {420}{}{Enemy camp}
{420}{}{敌人营地}
### {421}{}{Enemy camp}
{421}{}{敌人营地}
#----------------------------------------
# 74: BSCamp2, BSCampB.MAP
#----------------------------------------
### {422}{}{Enemy camp}
{422}{}{敌人营地}
### {423}{}{Enemy camp}
{423}{}{敌人营地}
### {424}{}{Enemy camp}
{424}{}{敌人营地}
#----------------------------------------
# 75: BSCamp3, BSCampC.MAP
#----------------------------------------
### {425}{}{Enemy camp}
{425}{}{敌人营地}
### {426}{}{Enemy camp}
{426}{}{敌人营地}
### {427}{}{Enemy camp}
{427}{}{敌人营地}
#----------------------------------------
# 76: PhoenixChrch, PXChrch.MAP
#----------------------------------------
### {428}{}{The first floor of the Cathedral}
{428}{}{大教堂一楼}
### {429}{}{The second floor of the Cathedral}
{429}{}{大教堂二楼}
### {430}{}{The top floor of the Cathedral}
{430}{}{大教堂的顶层}
#----------------------------------------
# 77: TwoSunGrave, TSGrave.MAP
#----------------------------------------
### {431}{}{Entrance to the landfill}
{431}{}{垃圾填埋场入口}
### {432}{}{Cemetery of decommissioned equipment}
{432}{}{退役设备墓地}
### {433}{}{Waste recycling area}
{433}{}{废物回收区}
#----------------------------------------
# 78: TwoSunInn, TSInn.MAP
#----------------------------------------
### {434}{}{The place of the attack on the caravan}
{434}{}{袭击商队的地点}
### {435}{}{}
{435}{}{error : string is empty}
### {436}{}{}
{436}{}{error : string is empty}
#----------------------------------------
# 79: VillaRuins, VLRUINS.MAP
#----------------------------------------
### {437}{}{Old ruins}
{437}{}{古老的废墟}
### {438}{}{Chris' Hideout}
{438}{}{克里斯的藏身之处}
### {439}{}{}
{439}{}{error : string is empty}
#----------------------------------------
# 80: RangersParom, RParom.MAP
#----------------------------------------
### {440}{}{The left bank of Colorado}
{440}{}{科罗拉多州左岸}
### {441}{}{}
{441}{}{error : string is empty}
### {442}{}{}
{442}{}{error : string is empty}
#----------------------------------------
# 81: RangersRetrns, RRetrns.MAP
#----------------------------------------
### {443}{}{A shack in the desert}
{443}{}{沙漠中的棚屋}
### {444}{}{}
{444}{}{error : string is empty}
### {445}{}{}
{445}{}{error : string is empty}
#----------------------------------------
# 82. RangersQuartz, RQuartz.MAP
#----------------------------------------
### {446}{}{Quartzsite, ruins of the city}
{446}{}{Quartzsite，城市废墟}
### {447}{}{Quartzsite, basements}
{447}{}{石英矿、地下室}
### {448}{}{Quartz site, gas station}
{448}{}{石英场地、加油站}
#----------------------------------------
# 83. RangersCave, RCave.MAP
#----------------------------------------
### {449}{}{The village of Giers Wash}
{449}{}{Giers-Wash村}
### {450}{}{Giers Wash Cave}
{450}{}{Giers Wash洞穴}
### {451}{}{}
{451}{}{error : string is empty}
#----------------------------------------
# 84: RangersCity, RCity.MAP
#----------------------------------------
### {452}{}{A village on the Colorado coast}
{452}{}{科罗拉多海岸的一个村庄}
### {453}{}{Aqueduct catacombs}
{453}{}{渡槽地下墓穴}
### {454}{}{Entrance to the aqueduct}
{454}{}{渡槽入口}
#----------------------------------------
# 85. GarageHist, GCHist.MAP
#----------------------------------------
### {455}{}{Historical highway}
{455}{}{历史高速公路}
### {456}{}{}
{456}{}{error : string is empty}
### {457}{}{}
{457}{}{error : string is empty}
#----------------------------------------
# 86. GarageBram, GCBram.MAP
#----------------------------------------
### {458}{}{Cattle breeders' camp}
{458}{}{养牛人营地}
### {459}{}{}
{459}{}{error : string is empty}
### {460}{}{}
{460}{}{error : string is empty}
#----------------------------------------
# 87. FlagstaffFarm, FlagFarm.MAP
#----------------------------------------
### {461}{}{ Farm "Windmill"}
{461}{}{农场“风车”}
### {462}{}{}
{462}{}{error : string is empty}
### {463}{}{}
{463}{}{error : string is empty}
#----------------------------------------
# 88. Hermosillo1, HERMO1.MAP
#----------------------------------------
### {464}{}{Rancho Dominguez}
{464}{}{兰乔·多明格斯}
### {465}{}{}
{465}{}{error : string is empty}
### {466}{}{}
{466}{}{error : string is empty}
#----------------------------------------
# 89. Hermosillo2, HERMO2.MAP
#----------------------------------------
### {467}{}{Garrison}
{467}{}{驻军}
### {468}{}{Lower drainage chamber}
{468}{}{下部排水室}
### {469}{}{Garrison roofs}
{469}{}{驻军屋顶}
#----------------------------------------
# 90. Hermosillo3, HERMO3.MAP
#----------------------------------------
### {470}{}{Point of view}
{470}{}{观点}
### {471}{}{Upper drainage chamber}
{471}{}{上部排水室}
### {472}{}{General Staff}
{472}{}{总参谋部}
#----------------------------------------
# 91. CGrandeSchool, CGSchool.MAP
#----------------------------------------
### {473}{}{Ruins of the old school}
{473}{}{旧学校的废墟}
### {474}{}{The cache of the mainline workers}
{474}{}{主线工人的缓存}
### {475}{}{Old school premises}
{475}{}{旧校舍}
#----------------------------------------
# 92. CGrandeBar, CGBar.MAP
#----------------------------------------
### {476}{}{ Abandoned bar}
{476}{}{废弃酒吧}
### {477}{}{}
{477}{}{error : string is empty}
### {478}{}{}
{478}{}{error : string is empty}
#----------------------------------------
# 93. CGrandeStan, CGStan.MAP
#----------------------------------------
### {479}{}{ Railway station}
{479}{}{火车站}
### {480}{}{}
{480}{}{error : string is empty}
### {481}{}{}
{481}{}{error : string is empty}
#----------------------------------------
# 94. RangersWater, RMohave.MAP
#----------------------------------------
### {482}{}{Mojave Water Pump}
{482}{}{莫哈韦水泵}
### {483}{}{}
{483}{}{error : string is empty}
### {484}{}{}
{484}{}{error : string is empty}
#----------------------------------------
# 95. InfernoChurch, InfChrch.MAP
#----------------------------------------
### {485}{}{Entrance to the Mysterious Mansion}
{485}{}{神秘大厦入口}
### {486}{}{Laboratory of the Mysterious Mansion}
{486}{}{神秘大厦实验室}
### {487}{}{The Chambers of the Mysterious Mansion}
{487}{}{神秘大厦的房间}
#----------------------------------------
# 96. Special Gold Encounter, rndGold.MAP
#----------------------------------------
### {488}{}{The road to the wilderness}
{488}{}{通往荒野的道路}
### {489}{}{Vault in a cave}
{489}{}{洞穴中的拱顶}
### {490}{}{}
{490}{}{error : string is empty}
#----------------------------------------
# 97. Special Bibl Encounter, rndBibl.MAP
#----------------------------------------
### {491}{}{Somewhere in the Sonoran Wasteland}
{491}{}{索诺兰荒原的某个地方}
### {492}{}{}
{492}{}{error : string is empty}
### {493}{}{}
{493}{}{error : string is empty}
#----------------------------------------
# 98. Special Cafe Encounter, rndCafe.MAP
#----------------------------------------
### {494}{}{Cafe}
{494}{}{咖啡馆}
### {495}{}{Vault}
{495}{}{金库}
### {496}{}{}
{496}{}{error : string is empty}
#----------------------------------------
# 99. Special Bomber Encounter, rndBomber.MAP
#----------------------------------------
### {497}{}{Somewhere in the Sonoran Wasteland}
{497}{}{索诺兰荒原的某个地方}
### {498}{}{}
{498}{}{error : string is empty}
### {499}{}{}
{499}{}{error : string is empty}
#----------------------------------------
# 100. Special Petro Encounter, rndPetro.MAP
#----------------------------------------
### {500}{}{Somewhere in the Sonoran Wasteland}
{500}{}{索诺兰荒原的某个地方}
### {501}{}{}
{501}{}{error : string is empty}
### {502}{}{}
{502}{}{error : string is empty}
#----------------------------------------
# 101. Special Cry Encounter, rndCry.MAP
#----------------------------------------
### {503}{}{Somewhere in the Sonoran Wasteland}
{503}{}{索诺兰荒原的某个地方}
### {504}{}{}
{504}{}{error : string is empty}
### {505}{}{}
{505}{}{error : string is empty}
#----------------------------------------
# 102. Special DriveIn Encounter, rndDrive.MAP
#----------------------------------------
### {506}{}{Somewhere in the Sonoran Wasteland}
{506}{}{索诺兰荒原的某个地方}
### {507}{}{}
{507}{}{error : string is empty}
### {508}{}{}
{508}{}{error : string is empty}
#----------------------------------------
# 103. Special Padre Encounter, rndPadre.MAP
#----------------------------------------
### {509}{}{Somewhere in the Sonoran Wasteland}
{509}{}{索诺兰荒原的某个地方}
### {510}{}{}
{510}{}{error : string is empty}
### {511}{}{}
{511}{}{error : string is empty}
#----------------------------------------
# 104. Special Baron Encounter, rndBaron.MAP
#----------------------------------------
### {512}{}{Somewhere in the Sonoran Wasteland}
{512}{}{索诺兰荒原的某个地方}
### {513}{}{}
{513}{}{error : string is empty}
### {514}{}{}
{514}{}{error : string is empty}
#---------------------------------------
- #105. Special Snow Encounter, rndSnow.MAP
#----------------------------------------
### {515}{}{Somewhere in the Sonoran Wasteland}
{515}{}{索诺兰荒原的某个地方}
### {516}{}{}
{516}{}{error : string is empty}
### {517}{}{}
{517}{}{error : string is empty}
#----------------------------------------
# 106. Special Vault Encounter, rndVault.MAP
#----------------------------------------
### {518}{}{Ruins of an ancient city}
{518}{}{古城遗址}
### {519}{}{Bomb Vault}
{519}{}{炸弹库}
### {520}{}{Ruins of an ancient city}
{520}{}{古城遗址}
#----------------------------------------
# 107. Special Army Encounter, rndArmy.MAP
#----------------------------------------
### {521}{}{Camp at the platform}
{521}{}{在平台上露营}
### {522}{}{Technical compartments}
{522}{}{技术舱}
### {523}{}{Living quarters}
{523}{}{生活区}
#----------------------------------------
# 108. Special LegendCity Encounter, rndRail.MAP
#----------------------------------------
### {524}{}{Somewhere in the Sonoran Wasteland}
{524}{}{索诺兰荒原的某个地方}
### {525}{}{Somewhere in the Sonoran Wasteland}
{525}{}{索诺兰荒原的某个地方}
### {526}{}{Somewhere in the Sonoran Wasteland}
{526}{}{索诺兰荒原的某个地方}
#----------------------------------------
# 109. VillaCrypt, VLCrypt.MAP
#----------------------------------------
### {527}{}{Passage to the crypt}
{527}{}{通往地下室的通道}
### {528}{}{Lower galleries}
{528}{}{下部廊道}
### {529}{}{Founder's Crypt}
{529}{}{创始人的地穴}
#----------------------------------------
# 110. PhoenixCola, PXCola.MAP
#----------------------------------------
### {530}{}{Warehouse of Nuka-Cola}
{530}{}{努卡可乐仓库}
### {531}{}{}
{531}{}{error : string is empty}
### {532}{}{}
{532}{}{error : string is empty}
#----------------------------------------
# 111. InfernoMonument, InfMnmt.MAP
#----------------------------------------
### {533}{}{ Main highway}
{533}{}{主要公路}
### {534}{}{Car tunnel}
{534}{}{汽车隧道}
### {535}{}{}
{535}{}{error : string is empty}
#----------------------------------------
# 112. CNuevaCarier, CNCarier.MAP
#----------------------------------------
### {536}{}{ Concrete mixing plant}
{536}{}{混凝土搅拌站}
### {537}{}{Lair of El Gigante}
{537}{}{El Gigante的Lair}
### {538}{}{}
{538}{}{error : string is empty}
#----------------------------------------
# 113. CNuevaGidro, CNGidr.MAP
#----------------------------------------
### {539}{}{Dome}
{539}{}{穹顶}
### {540}{}{Oriental greenhouses}
{540}{}{东方温室}
### {541}{}{Western greenhouses}
{541}{}{西方温室}
#----------------------------------------
# 114. SanBrahminCave, SBCave.MAP
#----------------------------------------
### {542}{}{The Buried City}
{542}{}{被埋葬的城市}
### {543}{}{Catacombs of the Buried City}
{543}{}{被埋葬的城市的地下墓穴}
### {544}{}{Ancient collector}
{544}{}{古代收藏家}
#----------------------------------------
# 115. SanFelipeCoast, FelipeB.MAP
#----------------------------------------
### {545}{}{ Hut on the shore}
{545}{}{岸边的小屋}
### {546}{}{Old ship}
{546}{}{旧船}
### {547}{}{Old ship}
{547}{}{旧船}
#----------------------------------------
# 116. SanFelipeCave, FelipeC.MAP
#----------------------------------------
### {548}{}{Monster Lair}
{548}{}{怪物赖}
### {549}{}{Monster Lair}
{549}{}{怪物赖}
### {550}{}{Monster Lair}
{550}{}{怪物赖}
#----------------------------------------
# 117. GarageTrailer, GCTrlr.MAP
#----------------------------------------
### {551}{}{Lonely trailer}
{551}{}{孤独的预告片}
### {552}{}{The stash of the fake rat}
{552}{}{藏匿的假老鼠}
### {553}{}{Lonely trailer}
{553}{}{孤独的预告片}
#----------------------------------------
# 118. FlagstaffWinon, FlagCamp.MAP
#----------------------------------------
### {554}{}{Hunter Camp}
{554}{}{猎人营地}
### {555}{}{Hunter Camp}
{555}{}{猎人营地}
### {556}{}{Hunter Camp}
{556}{}{猎人营地}
#----------------------------------------
# 119. SanBrahminOasis, SBOasis.MAP
#----------------------------------------
### {557}{}{Sullivan Lake}
{557}{}{沙利文湖}
### {558}{}{Sullivan Lake}
{558}{}{沙利文湖}
### {559}{}{Sullivan Lake}
{559}{}{沙利文湖}
#----------------------------------------
# 120. SantaAnaPlaza, SAPlaza.MAP
#----------------------------------------
### {560}{}{Plaza Zaragoza}
{560}{}{萨拉戈萨广场}
### {561}{}{Basement of the old church}
{561}{}{旧教堂的地下室}
### {562}{}{Premises of the old church}
{562}{}{旧教堂的场地}
#----------------------------------------
# 121. SantaAnaMonument, SAMnmnt.MAP
#----------------------------------------
### {563}{}{Ancient monument}
{563}{}{古代纪念碑}
### {564}{}{Ancient monument}
{564}{}{古代纪念碑}
### {565}{}{Ancient monument}
{565}{}{古代纪念碑}
#----------------------------------------
# 122. SantaAnaGrave, SAGrave.MAP
#----------------------------------------
### {566}{}{Ancient cemetery}
{566}{}{古代墓地}
### {567}{}{Ancient cemetery}
{567}{}{古代墓地}
### {568}{}{Ancient cemetery}
{568}{}{古代墓地}
#----------------------------------------
# 123. SanBrahminCaravanA, SBCrvnA.MAP
#----------------------------------------
### {569}{}{Wasteland}
{569}{}{荒地}
### {570}{}{}
{570}{}{error : string is empty}
### {571}{}{}
{571}{}{error : string is empty}
#----------------------------------------
# 124. SanBrahminCaravanB, SBCrvnB.MAP
#----------------------------------------
### {572}{}{ Federal highway}
{572}{}{联邦公路}
### {573}{}{}
{573}{}{error : string is empty}
### {574}{}{}
{574}{}{error : string is empty}
#----------------------------------------
# 125. SanBrahminCaravanC, SBCrvnC.MAP
#----------------------------------------
### {575}{}{Phoenix Suburb}
{575}{}{菲尼克斯郊区}
### {576}{}{}
{576}{}{error : string is empty}
### {577}{}{}
{577}{}{error : string is empty}
#----------------------------------------
# 126. OilCity, OilA.MAP
#----------------------------------------
### {578}{}{Fishermen's Village}
{578}{}{渔民村}
### {579}{}{Fishermen's Village}
{579}{}{渔民村}
### {580}{}{The Sea of Cortez}
{580}{}{科尔特斯海}
#----------------------------------------
# 127. OilPlatformB, OilB.MAP
#----------------------------------------
### {581}{}{Ascent to the platform}
{581}{}{上升到平台}
### {582}{}{Platform}
{582}{}{站台}
### {583}{}{Landing pad}
{583}{}{着陆台}
#----------------------------------------
# 128. OilPlatformC, OilC.MAP
#----------------------------------------
### {584}{}{ Residential level}
{584}{}{居住水平}
### {585}{}{Recreation area}
{585}{}{娱乐区}
### {586}{}{Administrative level}
{586}{}{行政级别}
#----------------------------------------
# 129. OilPlatformD, OilD.MAP
#----------------------------------------
### {587}{}{Drilling deck}
{587}{}{钻井平台}
### {588}{}{Oil warehouse}
{588}{}{石油仓库}
### {589}{}{Drilling rig}
{589}{}{钻机}
#----------------------------------------
# 130. OilCoast, OilE.MAP
#----------------------------------------
### {590}{}{ Black Lagoon}
{590}{}{黑礁}
### {591}{}{Black Lagoon}
{591}{}{黑礁}
### {592}{}{Black Lagoon}
{592}{}{黑礁}
#----------------------------------------
# 131. DiegoTijuana, DiegoA.MAP
#----------------------------------------
### {593}{}{Tijuana, border checkpoint}
{593}{}{蒂华纳，边境检查站}
### {594}{}{Tijuana, Revolution Avenue}
{594}{}{蒂华纳，革命大道}
### {595}{}{Monumental Plaza de Toros}
{595}{}{托罗斯纪念碑广场}
#----------------------------------------
# 132. DiegoCampA, DiegoC1.MAP
#----------------------------------------
### {596}{}{San Isidro, ghoul camp}
{596}{}{圣伊西德罗，食尸鬼营地}
### {597}{}{San Isidro tunnel}
{597}{}{San Isidro隧道}
### {598}{}{San Isidro, monorail stop}
{598}{}{圣伊西德罗，单轨车站}
#----------------------------------------
# 133. DiegoCampB, DiegoC2.MAP
#----------------------------------------
### {599}{}{ Bonita Dam}
{599}{}{博尼塔大坝}
### {600}{}{Bonita Dam, engine room}
{600}{}{博尼塔大坝，机舱}
### {601}{}{Bonita Dam, control center}
{601}{}{博尼塔大坝，控制中心}
#----------------------------------------
# 134. DiegoCampC, DiegoC3.MAP
#----------------------------------------
### {602}{}{Old town, ghoul camp}
{602}{}{老城，食尸鬼营地}
### {603}{}{Old town, road junction}
{603}{}{老城区、路口}
### {604}{}{Old Town, monorail stop}
{604}{}{老城，单轨车站}
#----------------------------------------
# 135. DiegoPatrulOffice, DiegoB1.MAP
#----------------------------------------
### {605}{}{Border Patrol Office}
{605}{}{边境巡逻办公室}
### {606}{}{Bridge on Route 5}
{606}{}{5号公路上的桥梁}
### {607}{}{Bridge on Highway 805}
{607}{}{805公路上的桥梁}
#----------------------------------------
# 136. DiegoChulaVista, DiegoB2.MAP
#----------------------------------------
### {608}{}{Chula Vista, mall}
{608}{}{Chula Vista购物中心}
### {609}{}{Chula Vista, storm sewer}
{609}{}{Chula Vista，雨水下水道}
### {610}{}{Chula Vista, Otei tract}
{610}{}{Chula Vista，Otei地区}
#----------------------------------------
# 137. DiegoHospital, DiegoB3.MAP
#----------------------------------------
### {611}{}{National City Hospital}
{611}{}{国立城市医院}
### {612}{}{National City, La Maz cafe}
{612}{}{国家城市，La Maz咖啡馆}
### {613}{}{Aviation Electronics Factory}
{613}{}{航空电子厂}
#----------------------------------------
# 138. DiegoCityHeart, DiegoHrt.MAP
#----------------------------------------
### {614}{}{Heart of San Diego, street}
{614}{}{圣地亚哥市中心，街道}
### {615}{}{Heart of San Diego, publishing house}
{615}{}{圣地亚哥之心出版社}
### {616}{}{Heart of San Diego, upper floors}
{616}{}{圣地亚哥市中心，上层}
#----------------------------------------
# 139. DiegoPirs, DiegoPir.MAP
#----------------------------------------
### {617}{}{U.S. Navy Piers}
{617}{}{美国海军码头}
### {618}{}{Italian Quarter}
{618}{}{意大利区}
### {619}{}{Balboa Park}
{619}{}{巴尔博亚公园}
#----------------------------------------
# 140. DiegoVault, DiegoVlt.MAP
#----------------------------------------
### {620}{}{Upper level of the Vault 24}
{620}{}{保险库的上层24}
### {621}{}{The average Vault level is 24}
{621}{}{Vault的平均级别为24}
### {622}{}{Lower level of the Vault 24}
{622}{}{保险库24的下层}
#----------------------------------------
# 141. DiegoCoronado, DiegoCor.MAP
#----------------------------------------
### {623}{}{The destroyed US Navy base}
{623}{}{被摧毁的美国海军基地}
### {624}{}{Navy base, surviving bunker}
{624}{}{海军基地，幸存地堡}
### {625}{}{Naval base, ammunition depot}
{625}{}{海军基地、弹药库}
#----------------------------------------
# 142. Mountain Encounter 9, MOUNT9.MAP
#----------------------------------------
### {626}{}{ Gorge}
{626}{}{峡}
### {627}{}{}
{627}{}{error : string is empty}
### {628}{}{}
{628}{}{error : string is empty}
#----------------------------------------
# 143. Mountain Encounter 8, MOUNT8.MAP
#----------------------------------------
### {629}{}{Burnt Forest}
{629}{}{烧毁的森林}
### {630}{}{}
{630}{}{error : string is empty}
### {631}{}{}
{631}{}{error : string is empty}
#----------------------------------------
# 144. Desert Encounter 9, desert9.MAP
#----------------------------------------
### {632}{}{Irradiated Wasteland}
{632}{}{辐照荒地}
### {633}{}{}
{633}{}{error : string is empty}
### {634}{}{}
{634}{}{error : string is empty}
#----------------------------------------
# 145. Coast Encounter 4, COAST4.MAP
#----------------------------------------
### {635}{}{Camp on the shore}
{635}{}{岸上露营}
### {636}{}{}
{636}{}{error : string is empty}
### {637}{}{}
{637}{}{error : string is empty}
#----------------------------------------
# 146. Road Encounter 5, ROAD5.MAP
#----------------------------------------
### {638}{}{A halt by the road}
{638}{}{停在路边}
### {639}{}{}
{639}{}{error : string is empty}
### {640}{}{}
{640}{}{error : string is empty}
#----------------------------------------
# 147. Mountain Encounter 7, MOUNT7.MAP
#----------------------------------------
### {641}{}{ Hut in the forest}
{641}{}{森林里的小屋}
### {642}{}{}
{642}{}{error : string is empty}
### {643}{}{}
{643}{}{error : string is empty}
#----------------------------------------
# 148. City Encounter 9, CITY9.MAP
#----------------------------------------
### {644}{}{Irradiated ruins}
{644}{}{辐照过的废墟}
### {645}{}{}
{645}{}{error : string is empty}
### {646}{}{}
{646}{}{error : string is empty}
#----------------------------------------
# 149. In Game Movie, gammovie.MAP
#----------------------------------------
### {647}{}{Slave convoy}
{647}{}{奴隶车队}
### {648}{}{}
{648}{}{error : string is empty}
### {649}{}{}
{649}{}{error : string is empty}
#----------------------------------------
# 150. mapreserv150
#----------------------------------------
### {650}{}{Wasteland}
{650}{}{荒地}
### {651}{}{}
{651}{}{error : string is empty}
### {652}{}{}
{652}{}{error : string is empty}

#######################################################
#
# Names of locations on the world map and in the mini-map
# Numbering: 1500+Area. For the area number, see CITY.TXT sections like [Area ??]
#
#######################################################

### {1500}{}{Villa}
{1500}{}{别墅}
### {1501}{}{Flagstaff}
{1501}{}{Flagstaff}
### {1502}{}{Garage City}
{1502}{}{车库城}
### {1503}{}{San Brahmin}
{1503}{}{San Brahmin}
### {1504}{}{Two-Sun}
{1504}{}{两个太阳}
### {1505}{}{Puerto}
{1505}{}{Puerto}
### {1506}{}{Rangers}
{1506}{}{Rangers}
### {1507}{}{Phoenix}
{1507}{}{凤凰}
### {1508}{}{Platform}
{1508}{}{站台}
### {1509}{}{Casa Grande}
{1509}{}{格兰德之家}
### {1510}{}{Hermosillo}
{1510}{}{赫莫西洛}
### {1511}{}{San Felipe}
{1511}{}{圣菲利佩}
### {1512}{}{Inferno}
{1512}{}{无法控制的大火}
### {1513}{}{Casa Nueva}
{1513}{}{努瓦之家}
### {1517}{}{US Navy Base}
{1517}{}{美国海军基地}
### {1515}{}{The motel}
{1515}{}{汽车旅馆}
### {1516}{}{The Dayglow}
{1516}{}{The Dayglow}
### {1517}{}{-}
{1517}{}{-}
### {1518}{}{Santa Ana}
{1518}{}{圣安娜}
### {1519}{}{-}
{1519}{}{-}
### {1520}{}{Jackals}
{1520}{}{千斤顶}
### {1521}{}{Pit stop}
{1521}{}{进站}
### {1522}{}{Villa}
{1522}{}{别墅}
### {1523}{}{Vault 27}
{1523}{}{保险库27}
### {1524}{}{Brotherhood Camp}
{1524}{}{兄弟会营地}
### {1525}{}{Raiders}
{1525}{}{突袭者}
### {1526}{}{Wasteland}
{1526}{}{荒地}
### {1527}{}{Mountainous terrain}
{1527}{}{山地地形}
### {1528}{}{Ruins}
{1528}{}{废墟}
### {1529}{}{The coast}
{1529}{}{海岸}
### {1530}{}{Puerto}
{1530}{}{Puerto}
### {1531}{}{Gold!}
{1531}{}{金}
### {1532}{}{Henry Beamis}
{1532}{}{亨利·比米斯}
### {1533}{}{Roadside cafe}
{1533}{}{路边咖啡馆}
### {1534}{}{Bomber}
{1534}{}{轰炸机}
### {1535}{}{Petro-Chico truck}
{1535}{}{Petro Chico卡车}
### {1536}{}{The cry of silence}
{1536}{}{沉默的呐喊}
### {1537}{}{Outdoor cinema}
{1537}{}{户外影院}
### {1538}{}{Padre}
{1538}{}{Padre}
### {1539}{}{Baron of Arizona}
{1539}{}{亚利桑那男爵}
### {1540}{}{Snowfall}
{1540}{}{降雪}
### {1541}{}{The Lost Refuge}
{1541}{}{失落的避难所}
### {1542}{}{Mobile Fortress}
{1542}{}{移动堡垒}
### {1543}{}{Legend City}
{1543}{}{传奇城市}
### {1544}{}{-}
{1544}{}{-}
### {1545}{}{-}
{1545}{}{-}
### {1546}{}{Quartzsite}
{1546}{}{石英岩}
### {1547}{}{A chance meeting}
{1547}{}{偶遇}
### {1548}{}{Winon Camp}
{1548}{}{Winon营地}
