### {110}{}{Now this boat is only suitable for sailing to the seabed. Her hull needs repair, and the motor needs energy.}
{110}{}{现在这艘船只适合航行到海底。她的船体需要修理，发动机需要能量。 -- Now this boat is only suitable for sailing to the seabed. Her hull needs repair, and the motor needs energy.}
### {111}{}{The engine won't start. The indicator indicates that the nuclear battery has run out.}
{111}{}{发动机无法起动。指示灯表示核电池已经耗尽。 -- The engine won't start. The indicator indicates that the nuclear battery has run out.}
### {112}{}{The boat is ready to sail. Use scientific methods to navigate.}
{112}{}{船已准备启航。使用科学的方法导航。 -- The boat is ready to sail. Use scientific methods to navigate.}
### {113}{}{You have patched up the cracks and holes in the hull.}
{113}{}{你已经修补了船体上的裂缝和洞。 -- You have patched up the cracks and holes in the hull.}
### {114}{}{The battery is charged. This is enough for one long swim.}
{114}{}{电池已充电。这足够游一次长距离了。 -- The battery is charged. This is enough for one long swim.}
### {115}{}{The battery is already fully charged.}
{115}{}{电池已充满电。 -- The battery is already fully charged.}
### {116}{}{You have nowhere to go now.}
{116}{}{你现在无处可去。 -- You have nowhere to go now.}
### {117}{}{The boat can't stand the weight. Remove all unnecessary items from the backpack.}
{117}{}{船承受不住重量。从背包里取出所有不必要的物品。 -- The boat can't stand the weight. Remove all unnecessary items from the backpack.}
### {118}{}{You can return to the shore on this boat. Use scientific methods to navigate.}
{118}{}{你可以坐这艘船回到岸边。使用科学的方法导航。 -- You can return to the shore on this boat. Use scientific methods to navigate.}
### {119}{}{This boat has enough fuel to get back to shore.}
{119}{}{这艘船有足够的燃料返回岸边。 -- This boat has enough fuel to get back to shore.}
