### {100}{}{Here is Ruiz.}
{100}{}{这是鲁伊斯。 -- Here is Ruiz.}
### {101}{}{You see a local. He is wearing a bandana and a light cape.}
{101}{}{你看到一个当地人。他戴着一条手帕和一件浅色斗篷。 -- You see a local. He is wearing a bandana and a light cape.}
### {102}{}{We meet near the treasure.}
{102}{}{我们在宝藏附近相遇。 -- We meet near the treasure.}
### {103}{}{Better not try my patience.}
{103}{}{最好不要考验我的耐心。 -- Better not try my patience.}
### {104}{}{If I come across another treasure map, I will definitely call you.}
{104}{}{如果我遇到另一张藏宝图，我一定会打电话给你。 -- If I come across another treasure map, I will definitely call you.}
### {105}{}{Are you looking for treasures? There are none here.}
{105}{}{你在找宝藏吗？这里没有。 -- Are you looking for treasures? There are none here.}
### {106}{}{Don't even think about hiding here. The undead will surely smell your scent.}
{106}{}{别想躲在这里。不死生物肯定会闻到你的气味。 -- Don't even think about hiding here. The undead will surely smell your scent.}

### {200}{}{Hey, new guy! My name is Jose Rene Ruiz. What are the fates in our town?}
{200}{}{嘿，新来的家伙！我的名字叫Jose Rene Ruiz。我们镇上的命运是什么？ -- Hey, new guy! My name is Jose Rene Ruiz. What are the fates in our town?}
### {1200}{}{Hey, new girl! My name is Jose Rene Ruiz. What are the fates in our town?}
{1200}{}{嘿，新来的女孩！我的名字叫Jose Rene Ruiz。我们镇上的命运是什么？ -- Hey, new girl! My name is Jose Rene Ruiz. What are the fates in our town?}
### {201}{}{I'm looking for something.}
{201}{}{我在找东西。 -- I'm looking for something.}
### {202}{}{Looking for someone.}
{202}{}{找人。 -- Looking for someone.}
### {203}{}{I see. You know, I'm looking for something too. If you help me, I'll help you.}
{203}{}{我明白了。你知道，我也在寻找一些东西。如果你帮我，我就帮你。 -- I see. You know, I'm looking for something too. If you help me, I'll help you.}
### {204}{}{Really? And what is it?}
{204}{}{真正地它是什么？ -- Really? And what is it?}
### {205}{}{Well, an old man hid a treasure somewhere on the coast. And then he gave up. I don't know exactly where the treasure is. There is a map, but he tore it into four fragments and hid it in different corners.}
{205}{}{嗯，一个老人在海岸的某个地方藏了一个宝藏。然后他放弃了。我不知道宝藏到底在哪里。有一张地图，但他把它撕成四块碎片，藏在不同的角落里。 -- Well, an old man hid a treasure somewhere on the coast. And then he gave up. I don't know exactly where the treasure is. There is a map, but he tore it into four fragments and hid it in different corners.}
### {206}{}{Tricky.}
{206}{}{棘手的 -- Tricky.}
### {207}{}{I have one fragment. If you find the rest, bring it to me, we'll divide the treasure in half.}
{207}{}{我有一个碎片。如果你找到剩下的，把它带给我，我们会把宝藏一分为二。 -- I have one fragment. If you find the rest, bring it to me, we'll divide the treasure in half.}
### {208}{}{How do I know you won't cheat?}
{208}{}{我怎么知道你不会作弊？ -- How do I know you won't cheat?}
### {209}{}{Okay. If I find it, I'll come straight to you.}
{209}{}{可以如果我找到了，我会直接找你。 -- Okay. If I find it, I'll come straight to you.}
### {210}{}{And how do I know that you won't cheat? It's just a contract. If you don't like it, forget it and pass by.}
{210}{}{我怎么知道你不会作弊？这只是一份合同。如果你不喜欢它，就忘掉它，然后路过。 -- And how do I know that you won't cheat? It's just a contract. If you don't like it, forget it and pass by.}
### {211}{}{I'll think about it.}
{211}{}{我会考虑的。 -- I'll think about it.}
### {212}{}{What a freak you are! How are you tolerated here? However, maybe you'll be useful to me... Listen, new guy, my name is Jose Rene Ruiz. First of all, tell me why you're here?}
{212}{}{你真是个怪胎！你在这里是怎么被容忍的？不过，也许你会对我有用…听着，新人，我叫何塞·雷内·鲁伊斯。首先，告诉我你为什么来这里？ -- What a freak you are! How are you tolerated here? However, maybe you'll be useful to me... Listen, new guy, my name is Jose Rene Ruiz. First of all, tell me why you're here?}
### {1212}{}{You're so ugly! How are you tolerated here? However, maybe you'll be useful to me... Listen, new girl, my name is Jose Rene Ruiz. First of all, tell me why you're here?}
{1212}{}{你太丑了！你在这里是怎么被容忍的？不过，也许你会对我有用…听着，新来的女孩，我的名字叫何塞·雷内·鲁伊斯。首先，告诉我你为什么来这里？ -- You're so ugly! How are you tolerated here? However, maybe you'll be useful to me... Listen, new girl, my name is Jose Rene Ruiz. First of all, tell me why you're here?}

### {220}{}{What news?}
{220}{}{什么消息？ -- What news?}
### {221}{}{None yet.}
{221}{}{还没有。 -- None yet.}
### {222}{}{Did you find anything?}
{222}{}{你找到什么了吗？ -- Did you find anything?}
### {223}{}{Not yet.}
{223}{}{还没有。 -- Not yet.}

### {230}{}{Have you been on the platform?}
{230}{}{你上过站台吗？ -- Have you been on the platform?}
### {231}{}{No. And there's nothing to do there. If there was a machine for the production of bottle caps, I would be the first to go there.}
{231}{}{不，那里没有什么可做的。如果有一台生产瓶盖的机器，我会第一个去那里。 -- No. And there's nothing to do there. If there was a machine for the production of bottle caps, I would be the first to go there.}
### {232}{}{Do you know where to get a battery for a boat?}
{232}{}{你知道在哪里可以买到船用电池吗？ -- Do you know where to get a battery for a boat?}
### {233}{}{All batteries are distributed by the owners of the boats. I won't give up my battery. Look for fools among the other owners, they usually gather at the bar.}
{233}{}{所有电池都由船主分配。我不会放弃我的电池。在其他店主中寻找傻瓜，他们通常聚集在酒吧里。 -- All batteries are distributed by the owners of the boats. I won't give up my battery. Look for fools among the other owners, they usually gather at the bar.}
### {234}{}{Clear.}
{234}{}{清楚的 -- Clear.}

### {240}{}{I have the missing map fragments.}
{240}{}{我有丢失的地图碎片。 -- I have the missing map fragments.}
### {241}{}{Come here!}
{241}{}{过来！ -- Come here!}
### {242}{}{Uh, okay...}
{242}{}{好吧。。。 -- Uh, okay...}
### {243}{}{The hell with it! I'll find the treasure without you.}
{243}{}{见鬼去吧！没有你我会找到宝藏的。 -- The hell with it! I'll find the treasure without you.}
### {244}{}{Ta-ak... (Takes out his fragment, connects everything together and twirls them together for a long time) Here it is...}
{244}{}{Ta ak。。。（拿出他的碎片，把所有的东西连接在一起，旋转了很长一段时间）就在这里。。。 -- Ta-ak... (Takes out his fragment, connects everything together and twirls them together for a long time) Here it is...}
### {245}{}{Are you sure?}
{245}{}{你确定吗？ -- Are you sure?}
### {246}{}{Precisely! It remains to come and take it. Now find a shovel and go to the place. The treasure is buried next to the old lighthouse on the coast north of the village.}
{246}{}{精确地它还有待来拿。现在找一把铲子去那个地方。宝藏被埋葬在村庄北部海岸的老灯塔旁边。 -- Precisely! It remains to come and take it. Now find a shovel and go to the place. The treasure is buried next to the old lighthouse on the coast north of the village.}
### {247}{}{I'm already running!}
{247}{}{我已经在跑步了！ -- I'm already running!}

### {250}{}{Admit it - did you kill Johnny?}
{250}{}{承认吧，你杀了强尼吗？ -- Admit it - did you kill Johnny?}
### {251}{}{What the hell are you talking about?!}
{251}{}{你在说什么？！ -- What the hell are you talking about?!}
### {252}{}{He was strangled with your rope. How do you explain it?}
{252}{}{他被你的绳子勒死了。你怎么解释？ -- He was strangled with your rope. How do you explain it?}
### {253}{}{Ha! I sold this rope to several fishermen. And why on earth would I kill anyone at all? Are you an idiot?}
{253}{}{哈我把这根绳子卖给了几个渔夫。我到底为什么要杀人？你是个白痴吗？ -- Ha! I sold this rope to several fishermen. And why on earth would I kill anyone at all? Are you an idiot?}
### {254}{}{And who did you sell it to?}
{254}{}{你把它卖给了谁？ -- And who did you sell it to?}
### {255}{}{I even have it in my notes, look here... Only Tin-Tan has been buying rope lately. Hey, isn't he like Uncle Johnny? No wonder he had my rope.}
{255}{}{我的笔记里都有，看这里。。。最近只有田谭在买绳子。嘿，他不像强尼叔叔吗？怪不得他有我的绳子。 -- I even have it in my notes, look here... Only Tin-Tan has been buying rope lately. Hey, isn't he like Uncle Johnny? No wonder he had my rope.}
### {256}{}{Okay. I'll talk to this uncle.}
{256}{}{可以我会和这位叔叔谈谈。 -- Okay. I'll talk to this uncle.}
### {257}{}{I'm asking questions here, you idiot. Who was the last person to buy a rope from you?}
{257}{}{我在这里问问题，你这个白痴。谁是最后一个从你那里买绳子的人？ -- I'm asking questions here, you idiot. Who was the last person to buy a rope from you?}
