### {100}{}{There is a guard in front of you.}
{100}{}{你面前有一个警卫。 -- There is a guard in front of you.}
### {101}{}{You see a man of Mexican appearance.}
{101}{}{你看到一个墨西哥长相的男人。 -- You see a man of Mexican appearance.}
### {102}{}{Muchas gracias, se?or.}
{102}{}{Muchas gracias，se?or。 -- Muchas gracias, se?or.}
### {1102}{}{Muchas gracias, se?or.}
{1102}{}{Muchas gracias，se?or。 -- Muchas gracias, se?or.}
### {103}{}{The guard breaks into a smile. It looks like he's not up to his duties right now.}
{103}{}{警卫突然笑了。看来他现在没有履行职责。 -- The guard breaks into a smile. It looks like he's not up to his duties right now.}

### {110}{}{Vete, traidor!}
{110}{}{兽医，开拓者！ -- Vete, traidor!}
### {111}{}{No hay nada.}
{111}{}{没有干草。 -- No hay nada.}
### {112}{}{No toques la puerta.}
{112}{}{没有puerta的帽子。 -- No toques la puerta.}

### {120}{}{Get out!}
{120}{}{滚出去！ -- Get out!}
### {121}{}{No entry allowed.}
{121}{}{不允许进入。 -- No entry allowed.}
### {122}{}{Don't touch that door.}
{122}{}{不要碰那扇门。 -- Don't touch that door.}
### {123}{}{You can't go there.}
{123}{}{你不能去那里。 -- You can't go there.}
