### {100}{}{Here is the bartender.}
{100}{}{这是酒保。 -- Here is the bartender.}
### {101}{}{You see an ordinary bartender.}
{101}{}{你看到一个普通的酒保。 -- You see an ordinary bartender.}
### {102}{}{I'm sorry, but you can't come here in THIS.}
{102}{}{对不起，你不能穿着这件衣服来这儿。 -- I'm sorry, but you can't come here in THIS.}

### {110}{}{Hey, come in to get your throat wet from the road.}
{110}{}{嘿，进来把你的喉咙弄湿。 -- Hey, come in to get your throat wet from the road.}
### {111}{}{Do you want a drink?}
{111}{}{你想喝一杯吗？ -- Do you want a drink?}
### {112}{}{I thought there would be more customers.}
{112}{}{我以为会有更多的顾客。 -- I thought there would be more customers.}
### {113}{}{Don't worry, everyone's here.}
{113}{}{别担心，大家都来了。 -- Don't worry, everyone's here.}
### {114}{}{Oh, I finally see a client.}
{114}{}{哦，我终于见到一位客户了。 -- Oh, I finally see a client.}

### {200}{}{Hey, hello! Well done for stopping by.}
{200}{}{嘿，你好！干得好，顺便来了。 -- Hey, hello! Well done for stopping by.}
### {1200}{}{Oh, lady. My respects. Thanks for stopping by.}
{1200}{}{哦，女士。我的敬意。谢谢你的光临。 -- Oh, lady. My respects. Thanks for stopping by.}
### {201}{}{Wasn't this bar abandoned?}
{201}{}{这家酒吧不是废弃了吗？ -- Wasn't this bar abandoned?}
### {202}{}{Yes, it was. But now things have gone up in the city, and I decided to restore this bar.}
{202}{}{是的，确实如此。但现在这个城市的情况有所好转，我决定修复这家酒吧。 -- Yes, it was. But now things have gone up in the city, and I decided to restore this bar.}
### {203}{}{And the mayor was not against it?}
{203}{}{市长没有反对吗？ -- And the mayor was not against it?}
### {204}{}{Previously, he didn't even allow you to enter this bar, and now suddenly he's got a lot of money. I don't know what came over him, but I'd better take this place before it's too late.}
{204}{}{以前，他甚至不允许你进入这家酒吧，现在他突然赚了很多钱。我不知道他发生了什么事，但我最好在一切都太迟之前占领这个地方。 -- Previously, he didn't even allow you to enter this bar, and now suddenly he's got a lot of money. I don't know what came over him, but I'd better take this place before it's too late.}
### {205}{}{Clear. Can I have a drink?}
{205}{}{清楚的我能喝一杯吗？ -- Clear. Can I have a drink?}

### {210}{}{Have a seat. The choice is small, but it's better than nothing.}
{210}{}{请坐选择很小，但总比什么都没有好。 -- Have a seat. The choice is small, but it's better than nothing.}
### {211}{}{I have to go.}
{211}{}{我得走了。 -- I have to go.}
