### {110}{}{This pump is working, but one of its filters has been dismantled and is lying in the house awaiting repair.}
{110}{}{这台水泵正在工作，但它的一个过滤器已经被拆除，躺在房子里等待修理。 -- This pump is working, but one of its filters has been dismantled and is lying in the house awaiting repair.}
### {111}{}{This pump successfully pumps clean water from underground.}
{111}{}{这台水泵成功地从地下抽水。 -- This pump successfully pumps clean water from underground.}
### {112}{}{you have repaired a damaged filter. It will still serve for some time for the benefit of the city.}
{112}{}{你已经修复了一个损坏的过滤器。它仍将在一段时间内为城市的利益服务。 -- you have repaired a damaged filter. It will still serve for some time for the benefit of the city.}
