### {100}{}{You see the reactor.}
{100}{}{你看到反应堆了。 -- You see the reactor.}
### {101}{}{Here is a reactor that powers a mobile platform.}
{101}{}{这是一个为移动平台提供动力的反应堆。 -- Here is a reactor that powers a mobile platform.}
### {102}{}{The reactor is no longer functioning.}
{102}{}{反应堆不再运行。 -- The reactor is no longer functioning.}
### {103}{}{The reactor is not functioning.}
{103}{}{反应堆无法运行。 -- The reactor is not functioning.}
