### {100}{}{This is Fred Stadtmaller.}
{100}{}{我是Fred Stadtmaller。 -- This is Fred Stadtmaller.}
### {101}{}{You see the padre in simple and ascetic clothes.}
{101}{}{你可以看到牧师穿着朴素而禁欲的衣服。 -- You see the padre in simple and ascetic clothes.}
### {102}{}{Goodbye, my child}
{102}{}{再见，我的孩子 -- Goodbye, my child}

### {200}{}{Greetings, my son. I didn't think I'd meet a man in the middle of the desert. Are you lost? Do you need help?}
{200}{}{你好，我的儿子。我没想到我会在沙漠中央遇到一个男人。你迷路了吗？你需要帮助吗？ -- Greetings, my son. I didn't think I'd meet a man in the middle of the desert. Are you lost? Do you need help?}
### {1200}{}{Greetings, my child. I didn't think I'd meet a man in the middle of the desert. Are you lost? Do you need help?}
{1200}{}{问候，我的孩子。我没想到我会在沙漠中央遇到一个男人。你迷路了吗？你需要帮助吗？ -- Greetings, my child. I didn't think I'd meet a man in the middle of the desert. Are you lost? Do you need help?}
### {201}{}{Who are you?}
{201}{}{你是谁？ -- Who are you?}
### {202}{}{I'm Padre Fred Stadtmaller. And I travel around Arizona in search of those whose soul needs my help - the offended, the sick, just the dead.}
{202}{}{我是Fred Stadtmaller神父。我在亚利桑那州四处旅行，寻找那些灵魂需要我帮助的人——被冒犯的人、病人、死者。 -- I'm Padre Fred Stadtmaller. And I travel around Arizona in search of those whose soul needs my help - the offended, the sick, just the dead.}
### {203}{}{Glad to meet you, Holy Father.}
{203}{}{很高兴见到你，圣父。 -- Glad to meet you, Holy Father.}
### {1203}{}{Glad to meet you, Holy Father.}
{1203}{}{很高兴见到你，圣父。 -- Glad to meet you, Holy Father.}
### {204}{}{You're not my padre.}
{204}{}{你不是我的牧师。 -- You're not my padre.}
### {205}{}{Oh, no, no. Of course I'm not your father. Holy Father - that's how people of my rank have been called since ancient times. I'm sorry if it bothered you somehow.}
{205}{}{哦，不，不。我当然不是你爸爸。圣父——自古以来，我这种级别的人就是这样称呼的。如果它不知怎么困扰了你，我很抱歉。 -- Oh, no, no. Of course I'm not your father. Holy Father - that's how people of my rank have been called since ancient times. I'm sorry if it bothered you somehow.}
### {206}{}{Okay.}
{206}{}{可以 -- Okay.}

### {210}{}{Is there anything I can help you with, my child?}
{210}{}{有什么我能帮你的吗，我的孩子？ -- Is there anything I can help you with, my child?}
### {211}{}{No, I'll figure it out somehow without divine intervention. Have a nice day, Padre.}
{211}{}{不，如果没有上帝的干预，我会设法解决的。祝你今天愉快，神父。 -- No, I'll figure it out somehow without divine intervention. Have a nice day, Padre.}

### {220}{}{In the meantime, I'd like to talk to you.}
{220}{}{在此期间，我想和你谈谈。 -- In the meantime, I'd like to talk to you.}
### {221}{}{Sure. What do you want to know?}
{221}{}{当然你想知道什么？ -- Sure. What do you want to know?}
### {222}{}{Shall we go back a bit?}
{222}{}{我们回去一点好吗？ -- Shall we go back a bit?}
### {223}{}{Who are you?}
{223}{}{你是谁？ -- Who are you?}
### {224}{}{My name is Fred Stadtmaller. I am engaged in spreading the word of God in these lands. Just as before the Great War, the clergy of the Catholic Church were engaged in this... But many have already forgotten this and see me as just a strange person.}
{224}{}{我的名字叫弗雷德·斯塔德马勒。我致力于在这些土地上传播上帝的话语。就像大战前一样，天主教会的神职人员也参与了这项工作。。。但许多人已经忘记了这一点，并将我视为一个陌生的人。 -- My name is Fred Stadtmaller. I am engaged in spreading the word of God in these lands. Just as before the Great War, the clergy of the Catholic Church were engaged in this... But many have already forgotten this and see me as just a strange person.}
### {225}{}{One more question, please.}
{225}{}{请再问一个问题。 -- One more question, please.}
### {226}{}{Who gave you this rank, priest?}
{226}{}{是谁给你这个级别的，牧师？ -- Who gave you this rank, priest?}
### {227}{}{It was in a monastic order on the outskirts of Phoenix. Even before the Phoenix was mired in the abyss of discord, and the order settled in the Cathedral of the Sacred Fire and began to interfere in worldly life.}
{227}{}{它在凤凰城郊区的一个修道院里。甚至在凤凰陷入不和的深渊之前，骑士团就定居在圣火大教堂，开始干预世俗生活。 -- It was in a monastic order on the outskirts of Phoenix. Even before the Phoenix was mired in the abyss of discord, and the order settled in the Cathedral of the Sacred Fire and began to interfere in worldly life.}
### {228}{}{So you're from the Sacred Fire Church? And why did you leave your cell?}
{228}{}{那么你是来自圣火教堂的？你为什么离开牢房？ -- So you're from the Sacred Fire Church? And why did you leave your cell?}
### {229}{}{We have disagreements with the current bishop of the Cathedral. Previously, our little church did not seek either power or wealth. We didn't meddle in the affairs of big cities. We only helped the suffering and kept ancient relics.}
{229}{}{我们与大教堂现任主教意见相左。以前，我们的小教会既不追求权力也不追求财富。我们没有干涉大城市的事务。我们只是帮助那些受苦受难的人，保留着古老的遗迹。 -- We have disagreements with the current bishop of the Cathedral. Previously, our little church did not seek either power or wealth. We didn't meddle in the affairs of big cities. We only helped the suffering and kept ancient relics.}
### {230}{}{Go on.}
{230}{}{继续 -- Go on.}
### {231}{}{But there have been big changes in the Cathedral, I can no longer carry my mass in this accumulation of evil and vice. Now I conduct my mass as the monks of the order would have conducted it before. That is, I continue the old traditions.}
{231}{}{但是大教堂发生了很大的变化，我再也不能在这种罪恶和罪恶的积累中承载我的弥撒了。现在我做弥撒，就像修会的僧侣以前做弥撒一样。也就是说，我延续了古老的传统。 -- But there have been big changes in the Cathedral, I can no longer carry my mass in this accumulation of evil and vice. Now I conduct my mass as the monks of the order would have conducted it before. That is, I continue the old traditions.}
### {232}{}{In truth, your deeds are admirable, Holy Father.}
{232}{}{事实上，你的行为令人钦佩，圣父。 -- In truth, your deeds are admirable, Holy Father.}
### {233}{}{I don't think the order likes to tolerate crazy fanatics.}
{233}{}{我不认为骑士团喜欢容忍疯狂的狂热分子。 -- I don't think the order likes to tolerate crazy fanatics.}

### {240}{}{How did you learn to control an iron bird?}
{240}{}{你是怎么学会控制铁鸟的？ -- How did you learn to control an iron bird?}
### {241}{}{Ancient books store not only knowledge about civil aviation... But what am I talking about if Phoenix and other settlements lived by candlelight a few years ago.}
{241}{}{古籍不仅保存着有关民航的知识。。。但是，如果几年前凤凰城和其他定居点靠烛光生活，我在说什么呢。 -- Ancient books store not only knowledge about civil aviation... But what am I talking about if Phoenix and other settlements lived by candlelight a few years ago.}

### {250}{}{Yes, I need your help.}
{250}{}{是的，我需要你的帮助。 -- Yes, I need your help.}
### {251}{}{Think as best you can, because they are waiting for me. I'll be leaving soon, and maybe we'll never see each other again.}
{251}{}{你想的最好，因为他们在等我。我很快就会离开，也许我们再也见不到对方了。 -- Think as best you can, because they are waiting for me. I'll be leaving soon, and maybe we'll never see each other again.}
### {252}{}{Actually, I'd just like to talk to you.}
{252}{}{事实上，我只是想和你谈谈。 -- Actually, I'd just like to talk to you.}
### {253}{}{In that case, I won't detain you any longer, Padre.}
{253}{}{那样的话，我就不会再拘留你了，神父。 -- In that case, I won't detain you any longer, Padre.}
### {254}{}{I need treatment.}
{254}{}{我需要治疗。 -- I need treatment.}
### {255}{}{Now your body is in perfect order. I'm not sure about the soul. But you'll have to deal with this on your own. It's time for me to hurry - sick children are waiting for me in St. Mary's Chapel.}
{255}{}{现在你的身体状况良好。我对灵魂没有把握。但你必须自己处理。我该抓紧时间了——生病的孩子们正在圣玛丽教堂等我。 -- Now your body is in perfect order. I'm not sure about the soul. But you'll have to deal with this on your own. It's time for me to hurry - sick children are waiting for me in St. Mary's Chapel.}
### {256}{}{Adios, santo padre.}
{256}{}{再见，圣托神父。 -- Adios, santo padre.}
### {257}{}{I want to repent, Holy Father. There have been many transgressions in my past.}
{257}{}{我想忏悔，圣父。在我的过去有许多违法行为。 -- I want to repent, Holy Father. There have been many transgressions in my past.}
### {258}{}{I will not relieve you of your burden. But I can make it easier. Get down on your knees, my child....}
{258}{}{我不会减轻你的负担。但我可以让它变得更容易。跪下来，我的孩子。。。。 -- I will not relieve you of your burden. But I can make it easier. Get down on your knees, my child....}
### {259}{}{Thank you, Padre.}
{259}{}{谢谢你，神父。 -- Thank you, Padre.}
### {260}{}{I need all your stuff. Come on, give me everything you've got. And take off your clothes too.}
{260}{}{我需要你所有的东西。来吧，把你所有的都给我。还脱下你的衣服。 -- I need all your stuff. Come on, give me everything you've got. And take off your clothes too.}
### {261}{}{May Saint Joseph forgive you...}
{261}{}{愿圣约瑟夫原谅你。。。 -- May Saint Joseph forgive you...}
### {262}{}{Shut up.}
{262}{}{闭嘴。 -- Shut up.}
### {263}{}{I'm tired of the cactus society and I want to get back to people. Can you carry me on your iron bird?}
{263}{}{我厌倦了仙人掌社会，我想回到人们身边。你能用你的铁鸟载我吗？ -- I'm tired of the cactus society and I want to get back to people. Can you carry me on your iron bird?}
### {1263}{}{I'm tired of the cactus society and I want to get back to people. Can you carry me on your iron bird?}
{1263}{}{我厌倦了仙人掌社会，我想回到人们身边。你能用你的铁鸟载我吗？ -- I'm tired of the cactus society and I want to get back to people. Can you carry me on your iron bird?}
### {264}{}{Of course. It won't take long.}
{264}{}{当然这不会花很长时间。 -- Of course. It won't take long.}
### {265}{}{Where would you recommend to go?}
{265}{}{你建议去哪里？ -- Where would you recommend to go?}
### {266}{}{Hmm. It all depends on what your soul desires.}
{266}{}{嗯，这完全取决于你的灵魂渴望什么。 -- Hmm. It all depends on what your soul desires.}
### {267}{}{Give me a little time to think.}
{267}{}{给我一点时间思考。 -- Give me a little time to think.}
### {268}{}{She wants revenge for my family. They were taken away to the east of the Villa.}
{268}{}{她想为我的家人报仇。他们被带到了别墅的东边。 -- She wants revenge for my family. They were taken away to the east of the Villa.}
### {269}{}{So be it. I think you need to get to Garage City or Flagstaff.}
{269}{}{那就这样吧。我想你需要去车库城或弗拉格斯塔夫。 -- So be it. I think you need to get to Garage City or Flagstaff.}
### {270}{}{We flew to Garage City.}
{270}{}{我们飞往车库城。 -- We flew to Garage City.}
### {271}{}{Flew to Flagstaff.}
{271}{}{逃到弗拉格斯塔夫。 -- Flew to Flagstaff.}
### {272}{}{No, not now.}
{272}{}{不，现在不行。 -- No, not now.}
### {273}{}{All I need now is to get hold of a good weapon and ammunition. And earn extra money for daily bread.}
{273}{}{我现在所需要的就是拿到一件好武器和弹药。并为日常面包赚取额外的钱。 -- All I need now is to get hold of a good weapon and ammunition. And earn extra money for daily bread.}
### {274}{}{Then the road will certainly lead you to Phoenix. It is the largest and most developed city for miles around.}
{274}{}{那么这条路一定会把你带到凤凰城。它是方圆数英里内最大、最发达的城市。 -- Then the road will certainly lead you to Phoenix. It is the largest and most developed city for miles around.}
### {275}{}{Flew to Phoenix.}
{275}{}{逃到凤凰城。 -- Flew to Phoenix.}
### {276}{}{I just want to settle down in some quiet place.}
{276}{}{我只想在一个安静的地方安顿下来。 -- I just want to settle down in some quiet place.}
### {277}{}{I know this right in the middle of the Sonoran desert. It is called Casa Nueva for a reason. This is a real oasis in the middle of the desert.}
{277}{}{我知道这就在索诺兰沙漠的中部。它被称为努瓦之家是有原因的。这是沙漠中央的一片真正的绿洲。 -- I know this right in the middle of the Sonoran desert. It is called Casa Nueva for a reason. This is a real oasis in the middle of the desert.}
### {278}{}{Flew to Casa Nueva.}
{278}{}{逃到努瓦之家。 -- Flew to Casa Nueva.}
### {279}{}{She dreams of exploring new worlds.}
{279}{}{她梦想探索新的世界。 -- She dreams of exploring new worlds.}
### {280}{}{Then you will probably want to go south, far into the Mexican territory.}
{280}{}{然后你可能会想往南走，深入墨西哥领土。 -- Then you will probably want to go south, far into the Mexican territory.}
### {281}{}{Then we flew south to the nearest Mexican city.}
{281}{}{然后我们向南飞到最近的墨西哥城市。 -- Then we flew south to the nearest Mexican city.}
