### {100}{}{You see the computer.}
{100}{}{你看到电脑了。 -- You see the computer.}
### {101}{}{Here is a computer controlling the life support system.}
{101}{}{这是一台控制生命支持系统的计算机。 -- Here is a computer controlling the life support system.}
### {102}{}{A more thoughtful approach is required here.}
{102}{}{这里需要一个更深思熟虑的方法。 -- A more thoughtful approach is required here.}
### {103}{}{Not enough power to activate the Vault support system.}
{103}{}{电源不足，无法激活Vault支持系统。 -- Not enough power to activate the Vault support system.}
### {104}{}{You have successfully repaired the Vault's life support system.}
{104}{}{您已成功修复Vault的生命支持系统。 -- You have successfully repaired the Vault's life support system.}
### {105}{}{The Vault's life support system is functioning normally.}
{105}{}{保险库的生命支持系统运行正常。 -- The Vault's life support system is functioning normally.}
