### {100}{}{You see a resident of the asylum.}
{100}{}{你看到的是收容所的一位居民。 -- You see a resident of the asylum.}
### {101}{}{Here is a local resident. It looks unusually clean and fresh.}
{101}{}{这是一位当地居民。它看起来异常干净和新鲜。 -- Here is a local resident. It looks unusually clean and fresh.}

### {110}{}{Good afternoon... or the night? What's going on outside?}
{110}{}{下午好还是晚上？外面发生了什么事？ -- Good afternoon... or the night? What's going on outside?}
### {111}{}{Please don't hurt us, we are peaceful people!}
{111}{}{请不要伤害我们，我们是和平的人！ -- Please don't hurt us, we are peaceful people!}
### {112}{}{We have been living in this Vault for a long time. And where did you come from?}
{112}{}{我们在这个金库里住了很长时间。你从哪里来的？ -- We have been living in this Vault for a long time. And where did you come from?}
### {113}{}{The raiders have been trying to get in here for months.}
{113}{}{袭击者几个月来一直试图进入这里。 -- The raiders have been trying to get in here for months.}
### {114}{}{How did you manage to get inside?}
{114}{}{你是怎么进去的？ -- How did you manage to get inside?}
### {115}{}{This is our home. We have nowhere else to go.}
{115}{}{这是我们的家。我们无处可去。 -- This is our home. We have nowhere else to go.}
### {116}{}{We won't survive in the desert. Please don't send us away!}
{116}{}{我们无法在沙漠中生存。请不要把我们赶走！ -- We won't survive in the desert. Please don't send us away!}

### {120}{}{Thank you, you are saving us from the terrible outside world!}
{120}{}{谢谢你，你把我们从可怕的外部世界救了出来！ -- Thank you, you are saving us from the terrible outside world!}
### {121}{}{Thank you for fixing the life support system}
{121}{}{感谢您修复生命支持系统 -- Thank you for fixing the life support system}
### {122}{}{Ah, what fresh air in the Vault!}
{122}{}{啊，金库里的空气多新鲜啊！ -- Ah, what fresh air in the Vault!}
### {123}{}{If it wasn't for you, we would have had to leave the Vault.}
{123}{}{如果不是你，我们就不得不离开金库。 -- If it wasn't for you, we would have had to leave the Vault.}
### {124}{}{You're a good person. Not like these raiders.}
{124}{}{你是个好人。不像这些袭击者。 -- You're a good person. Not like these raiders.}
### {125}{}{You know, the first caretaker of the Vault was a man named Van Buren.}
{125}{}{你知道，金库的第一个管理员是一个叫范布伦的人。 -- You know, the first caretaker of the Vault was a man named Van Buren.}
### {126}{}{Thanks for the help.}
{126}{}{谢谢你的帮助。 -- Thanks for the help.}
### {127}{}{We wouldn't have survived in the desert.}
{127}{}{我们在沙漠里是活不下去的。 -- We wouldn't have survived in the desert.}
