### {100}{}{Here is Preacher Hiram.}
{100}{}{这是海勒姆牧师。 -- Here is Preacher Hiram.}
### {101}{}{You see a man in a shabby cassock.}
{101}{}{你看到一个穿着破旧袈裟的男人。 -- You see a man in a shabby cassock.}
### {102}{}{What... what are you doing...}
{102}{}{什么你在干什么。。。 -- What... what are you doing...}
### {103}{}{...kx-x... hr-r-r...}
{103}{}{…kx-x…hr-r-。。。 -- ...kx-x... hr-r-r...}
### {104}{}{Heretic! The technology of the Ancients is not for simple walks. This armor belongs in our main temple, in Phoenix.}
{104}{}{异教徒古人的技术不适合简单的散步。这件盔甲属于我们在凤凰城的主庙。 -- Heretic! The technology of the Ancients is not for simple walks. This armor belongs in our main temple, in Phoenix.}

#The first dialog
### {200}{}{Hello, traveler. It was a big mistake on your part to come to this city.}
{200}{}{你好，旅行家。你来这个城市是个大错误。 -- Hello, traveler. It was a big mistake on your part to come to this city.}
### {1200}{}{Hello, traveler. It was a big mistake on your part to come to this city.}
{1200}{}{你好，旅行家。你来这个城市是个大错误。 -- Hello, traveler. It was a big mistake on your part to come to this city.}
### {201}{}{Why is that?}
{201}{}{为什么？ -- Why is that?}
### {202}{}{Flagstaff is one of the few places in the wastelands where order is accepted... in a way. Some outsiders in this city are condemned to forced labor, and some to the death penalty in order to become fuel for the Sacred Fire. But ultimately it's up to you.}
{202}{}{弗拉格斯塔夫是荒原上为数不多的接受订单的地方之一。。。在某种程度上这个城市的一些外来者被判处强迫劳动，一些人被判处死刑，以成为圣火的燃料。但最终取决于你。 -- Flagstaff is one of the few places in the wastelands where order is accepted... in a way. Some outsiders in this city are condemned to forced labor, and some to the death penalty in order to become fuel for the Sacred Fire. But ultimately it's up to you.}
### {203}{}{Clearly. I want to talk to you.}
{203}{}{清晰地我想和你谈谈。 -- Clearly. I want to talk to you.}
### {204}{}{Okay, I'll take that into account. Goodbye.}
{204}{}{好的，我会考虑的。再见 -- Okay, I'll take that into account. Goodbye.}
### {205}{}{Hello, traveler. What a blessing that the rays of the Sacred Fire sent you to this city. I hope you won't condemn the local order?}
{205}{}{你好，旅行家。圣火的光芒把你送到这座城市，真是一件幸事。我希望你不要谴责当地的秩序？ -- Hello, traveler. What a blessing that the rays of the Sacred Fire sent you to this city. I hope you won't condemn the local order?}
### {206}{}{What other orders?}
{206}{}{还有什么订单？ -- What other orders?}
### {207}{}{Hello, traveler. Is there anything I can do to help you?}
{207}{}{你好，旅行家。有什么我能帮你的吗？ -- Hello, traveler. Is there anything I can do to help you?}
### {208}{}{Perhaps. I'm new here, I could use some advice.}
{208}{}{可能我是新来的，我需要一些建议。 -- Perhaps. I'm new here, I could use some advice.}
### {209}{}{Well, not the best start for dating. Learn to accept faith as it is. Words are just a shell for meaning.}
{209}{}{嗯，这不是约会的最佳开始。学会接受信仰的本来面目。言语只是意义的外壳。 -- Well, not the best start for dating. Learn to accept faith as it is. Words are just a shell for meaning.}

#Repeat dialog
### {210}{}{How can I help?}
{210}{}{我能帮上什么忙？ -- How can I help?}
### {211}{}{Goodbye.}
{211}{}{再见 -- Goodbye.}
### {212}{}{Who are you and what is this place?}
{212}{}{你是谁，这个地方是什么？ -- Who are you and what is this place?}
### {213}{}{This is the temple of the Great Sacred Fire. And I am Hiram, his priest. Welcome to His radiant abode.}
{213}{}{这是伟大的圣火神庙。我就是希兰，他的祭司。欢迎来到他容光焕发的住所。 -- This is the temple of the Great Sacred Fire. And I am Hiram, his priest. Welcome to His radiant abode.}
### {214}{}{Why so many pretentious words?}
{214}{}{为什么有那么多做作的话？ -- Why so many pretentious words?}
### {215}{}{Well... to be honest, I'm already forgetting the days when I said otherwise. The teaching of the Sacred Fire changed my whole life.}
{215}{}{好老实说，我已经忘记了我说过其他话的日子了。圣火的教导改变了我的一生。 -- Well... to be honest, I'm already forgetting the days when I said otherwise. The teaching of the Sacred Fire changed my whole life.}

# About knowledge
### {216}{}{Is your temple somehow useful to Flagstaff?}
{216}{}{你的神庙对弗拉格斯塔夫有用吗？ -- Is your temple somehow useful to Flagstaff?}
### {217}{}{Oh, of course! Let's start with the fact that Flagstaff is built on the roof of our church... or rather, the main temple, which is located in Phoenix.}
{217}{}{哦，当然！让我们从弗拉格斯塔夫建在我们教堂的屋顶上开始。。。或者更确切地说，是位于凤凰城的主庙。 -- Oh, of course! Let's start with the fact that Flagstaff is built on the roof of our church... or rather, the main temple, which is located in Phoenix.}
### {218}{}{Why do you need this?}
{218}{}{你为什么需要这个？ -- Why do you need this?}
### {219}{}{Uranium is one of the sacred resources inherited from our ancestors. We collect its radiant energy and use it for the glory of the Sacred Fire...}
{219}{}{铀是从我们祖先那里继承下来的神圣资源之一。我们收集它的辐射能量，并将其用于神圣之火的荣耀。。。 -- Uranium is one of the sacred resources inherited from our ancestors. We collect its radiant energy and use it for the glory of the Sacred Fire...}
### {220}{}{More?}
{220}{}{更多 -- More?}
### {221}{}{We teach literacy and pre-war knowledge to everyone who expresses such a desire. And I, a humble servant of the Sacred Fire, am endowed with the gift of healing.}
{221}{}{我们向每一个表达这种愿望的人传授识字和战前知识。我，一个神圣之火的卑微仆人，被赋予了治愈的天赋。 -- We teach literacy and pre-war knowledge to everyone who expresses such a desire. And I, a humble servant of the Sacred Fire, am endowed with the gift of healing.}
### {222}{}{I don't think you're doing this for free.}
{222}{}{我不认为你这样做是免费的。 -- I don't think you're doing this for free.}
### {223}{}{Skeptics! Skeptics are all around! However, I have to admit - it is. To get closer to the ancient wisdom, you need to pay with caps or become a member of our church. After all, not all people are ready to accept the knowledge of the Old World.}
{223}{}{怀疑论者！怀疑论者无处不在！然而，我不得不承认，事实确实如此。为了更接近古老的智慧，你需要带着上限付费，或者成为我们教会的一员。毕竟，并不是所有人都准备好接受旧世界的知识。 -- Skeptics! Skeptics are all around! However, I have to admit - it is. To get closer to the ancient wisdom, you need to pay with caps or become a member of our church. After all, not all people are ready to accept the knowledge of the Old World.}
### {224}{}{Clearly. Tell me more.}
{224}{}{清晰地告诉我更多。 -- Clearly. Tell me more.}
### {225}{}{That's the end of it. Goodbye.}
{225}{}{到此结束，再见。 -- That's the end of it. Goodbye.}
### {226}{}{I would like to share your knowledge.}
{226}{}{我想分享你的知识。 -- I would like to share your knowledge.}
### {227}{}{Oh, undoubtedly. But I'm afraid I can't accept you as a brother in faith until I get consent from the main temple. That is, you will have to pay. Can you read?}
{227}{}{哦，毫无疑问。但恐怕在得到主寺的同意之前，我不能接受你作为信仰上的兄弟。也就是说，你必须付钱。你会读书吗？ -- Oh, undoubtedly. But I'm afraid I can't accept you as a brother in faith until I get consent from the main temple. That is, you will have to pay. Can you read?}
### {1227}{}{Oh, absolutely. But I'm afraid I can't accept you as a sister in faith until I get consent from the main temple. That is, you will have to pay. Can you read?}
{1227}{}{哦，当然。但恐怕在得到主庙的同意之前，我不能接受你的信仰。也就是说，你必须付钱。你会读书吗？ -- Oh, absolutely. But I'm afraid I can't accept you as a sister in faith until I get consent from the main temple. That is, you will have to pay. Can you read?}
### {228}{}{Yes.}
{228}{}{对 -- Yes.}
### {229}{}{I can barely read the syllables.}
{229}{}{我几乎看不懂音节。 -- I can barely read the syllables.}
### {230}{}{So the secrets of the Sacred Fire will not reach your mind! We will start with the basics - with literacy. One lesson will cost a hundred caps.}
{230}{}{所以圣火的秘密不会到达你的脑海！我们将从基础知识开始——识字。一节课要花一百顶帽子。 -- So the secrets of the Sacred Fire will not reach your mind! We will start with the basics - with literacy. One lesson will cost a hundred caps.}
### {231}{}{Here are the bottlecaps. I want to get smarter!}
{231}{}{这是水瓶。我想变得更聪明！ -- Here are the bottlecaps. I want to get smarter!}
### {232}{}{Not now. Answer the other questions first.}
{232}{}{现在不行。先回答其他问题。 -- Not now. Answer the other questions first.}
### {233}{}{I can't afford such expenses yet.}
{233}{}{我还负担不起这样的费用。 -- I can't afford such expenses yet.}
### {234}{}{Well, that's enough for today. From now on, you will be able to learn pre-war knowledge yourself if you practice reading and writing more. And don't forget who revealed this sacrament to you!}
{234}{}{好吧，今天就够了。从现在起，如果你多练习阅读和写作，你将能够自己学习战前的知识。别忘了是谁向你展示了这份圣礼！ -- Well, that's enough for today. From now on, you will be able to learn pre-war knowledge yourself if you practice reading and writing more. And don't forget who revealed this sacrament to you!}
### {235}{}{So... a lot... information. I already have a headache. Let's take a break.}
{235}{}{所以…很多。。。信息我已经头疼了。让我们休息一下。 -- So... a lot... information. I already have a headache. Let's take a break.}
### {236}{}{Anyone should not be allowed to enter the mysteries of the Sacred Fire. After all, this knowledge can be used both for good and for harm. Prove your devotion to our faith - make a solid donation. 300 caps - that's the price.}
{236}{}{任何人都不应该被允许进入神圣之火的奥秘。毕竟，这些知识既可以用来做好事，也可以用来做坏事。证明你对我们信仰的忠诚——做出坚定的捐赠。300顶——这就是价格。 -- Anyone should not be allowed to enter the mysteries of the Sacred Fire. After all, this knowledge can be used both for good and for harm. Prove your devotion to our faith - make a solid donation. 300 caps - that's the price.}
### {237}{}{I think I've had enough donations for your church.}
{237}{}{我想我已经为你们的教堂捐够了。 -- I think I've had enough donations for your church.}
### {238}{}{Then I want to make a donation.}
{238}{}{然后我想捐款。 -- Then I want to make a donation.}
### {239}{}{Oh, yeah. Really. Well, I have to keep my word. Welcome to my abode. Ancient writings are kept there. Treat them with care and respect.}
{239}{}{哦，是的。真正地好吧，我必须信守诺言。欢迎来到我的住处。那里保存着古代著作。以关心和尊重的态度对待他们。 -- Oh, yeah. Really. Well, I have to keep my word. Welcome to my abode. Ancient writings are kept there. Treat them with care and respect.}
### {240}{}{Great, there will be something to read before going to bed.}
{240}{}{太好了，睡前会有东西读。 -- Great, there will be something to read before going to bed.}
### {241}{}{Thank you, your benefactor knows no bounds!}
{241}{}{谢谢你，你的恩人是无止境的！ -- Thank you, your benefactor knows no bounds!}
### {242}{}{Enough about the temple, now I know enough.}
{242}{}{关于寺庙的事已经够多了，现在我知道的够多了。 -- Enough about the temple, now I know enough.}

# About faith
### {245}{}{Tell us about your faith.}
{245}{}{告诉我们你的信仰。 -- Tell us about your faith.}
### {246}{}{I can talk about this forever. The world was created by the Sacred Fire that fell to earth a hundred years ago. He incinerated the sinful people and left only small families for the human race to continue its existence.}
{246}{}{我可以永远谈论这个。这个世界是由一百年前坠落地球的圣火创造的。他焚烧了罪恶的人民，只留下了小家庭让人类继续生存。 -- I can talk about this forever. The world was created by the Sacred Fire that fell to earth a hundred years ago. He incinerated the sinful people and left only small families for the human race to continue its existence.}
### {247}{}{[Next]}
{247}{}{[下一个 -- Next]}
### {248}{}{Now we, the descendants of the survivors, are trying to build a New World devoid of the mistakes and vices of the past.}
{248}{}{现在，我们，幸存者的后代，正在努力建立一个没有过去错误和罪恶的新世界。 -- Now we, the descendants of the survivors, are trying to build a New World devoid of the mistakes and vices of the past.}
### {249}{}{Who are we?}
{249}{}{我们是谁？ -- Who are we?}
### {250}{}{Our church and its followers, of course. Other people, alas, have forgotten the lessons of the past. We are called to reason with them.}
{250}{}{当然，我们的教会及其信徒。唉，其他人已经忘记了过去的教训。我们被要求和他们讲道理。 -- Our church and its followers, of course. Other people, alas, have forgotten the lessons of the past. We are called to reason with them.}
### {251}{}{I thought it was a war.}
{251}{}{我以为这是一场战争。 -- I thought it was a war.}
### {252}{}{This is the trouble of many living people. You have lost faith in the soul and have condescended to simple material truths. The Great War is only a disguise of what the Sacred Fire was. It was not nuclear bombs that punished humanity, but human stupidity and greed. That's the point.}
{252}{}{这是许多活着的人的烦恼。你对灵魂失去了信心，屈尊于简单的物质真理。伟大的战争只是神圣之火的伪装。惩罚人类的不是核弹，而是人类的愚蠢和贪婪。这就是重点。 -- This is the trouble of many living people. You have lost faith in the soul and have condescended to simple material truths. The Great War is only a disguise of what the Sacred Fire was. It was not nuclear bombs that punished humanity, but human stupidity and greed. That's the point.}
### {253}{}{How far has your faith spread?}
{253}{}{你的信仰传播了多远？ -- How far has your faith spread?}
### {254}{}{Our main temple is in Phoenix, but it's not that important. After all, many tribes carry faith in the Sacred Fire, calling It by other names and interpreting ancient events differently. That's why our church is expanding so easily. Our teaching is known throughout Sonora.}
{254}{}{我们的主庙在凤凰城，但没那么重要。毕竟，许多部落都对圣火抱有信仰，用其他名字称呼它，并以不同的方式解释古代事件。这就是为什么我们的教会如此容易扩张的原因。我们的教学在整个索诺拉州都很有名。 -- Our main temple is in Phoenix, but it's not that important. After all, many tribes carry faith in the Sacred Fire, calling It by other names and interpreting ancient events differently. That's why our church is expanding so easily. Our teaching is known throughout Sonora.}
### {255}{}{How do the colonists relate to this faith?}
{255}{}{殖民者与这种信仰有何联系？ -- How do the colonists relate to this faith?}
### {256}{}{Most of the inhabitants believe in the Sacred Fire or pretend to believe. But alas, Faber's mercenaries are mostly godless, and there are skeptics among the population. Do not worry, the Sacred Fire will open their eyes sooner or later. I am more concerned about those who are hiding from His X-ray vision.}
{256}{}{大多数居民相信或假装相信圣火。但遗憾的是，费伯的雇佣兵大多是无神的，民众中也有怀疑论者。别担心，圣火迟早会睁开他们的眼睛。我更关心那些躲在他的X光视野之外的人。 -- Most of the inhabitants believe in the Sacred Fire or pretend to believe. But alas, Faber's mercenaries are mostly godless, and there are skeptics among the population. Do not worry, the Sacred Fire will open their eyes sooner or later. I am more concerned about those who are hiding from His X-ray vision.}
### {257}{}{}
{257}{}{error : string is empty -- }
### {258}{}{Allow me, Holy Father, to stay with you a little longer.}
{258}{}{请允许我，圣父，和你多呆一会儿。 -- Allow me, Holy Father, to stay with you a little longer.}
### {259}{}{Eh, goodbye.}
{259}{}{呃，再见。 -- Eh, goodbye.}

#Donation
### {260}{}{I would like to help your church.}
{260}{}{我想帮助你们的教会。 -- I would like to help your church.}
### {261}{}{Any donation will bring us closer to the spirit of the Sacred Fire. What can you offer?}
{261}{}{任何捐赠都将使我们更接近圣火的精神。你能提供什么？ -- Any donation will bring us closer to the spirit of the Sacred Fire. What can you offer?}
### {262}{}{Unfortunately, nothing of value. But I have a bunch of questions.}
{262}{}{不幸的是，没有任何价值。但我有很多问题。 -- Unfortunately, nothing of value. But I have a bunch of questions.}
### {263}{}{Nothing today. Goodbye.}
{263}{}{今天什么都没有。再见 -- Nothing today. Goodbye.}
### {264}{}{Only 10 caps.}
{264}{}{只有10顶帽子。 -- Only 10 caps.}
### {265}{}{Here are 50 caps.}
{265}{}{这里有50顶帽子。 -- Here are 50 caps.}
### {266}{}{As many as 100 caps.}
{266}{}{多达100顶帽子。 -- As many as 100 caps.}
### {267}{}{(quickly hides a handful of caps in the folds of his cassock) Thank you.}
{267}{}{（很快在他的袈裟褶皱里藏了一把帽子）谢谢你。 -- (quickly hides a handful of caps in the folds of his cassock) Thank you.}
### {268}{}{(hastily pours your caps into a leather pouch on his belt) Truly, your generosity knows no bounds!}
{268}{}{（匆忙地把帽子倒进他腰带上的皮包里）真的，你的慷慨是无止境的！ -- (hastily pours your caps into a leather pouch on his belt) Truly, your generosity knows no bounds!}
### {269}{}{(pours your caps into a leather pouch on his belt) May the Sacred Fire be with you!}
{269}{}{（把你的帽子倒进他腰带上的皮包里）愿圣火与你同在！ -- (pours your caps into a leather pouch on his belt) May the Sacred Fire be with you!}

#Treatment
### {270}{}{I need treatment.}
{270}{}{我需要治疗。 -- I need treatment.}
### {271}{}{In the name of the Sacred Fire, what happened?}
{271}{}{以圣火的名义，发生了什么？ -- In the name of the Sacred Fire, what happened?}
### {272}{}{Injury.}
{272}{}{损伤 -- Injury.}
### {273}{}{Injury.}
{273}{}{损伤 -- Injury.}
### {274}{}{Irradiation.}
{274}{}{放射 -- Irradiation.}
### {275}{}{Poisoning.}
{275}{}{中毒。 -- Poisoning.}
### {276}{}{However, nothing significant.}
{276}{}{然而，没有什么重要的。 -- However, nothing significant.}
### {277}{}{Of course, the church will help you, but don't you want to reward her with a small donation? It 's about the amount in }
{277}{}{当然，教会会帮助你，但你不想用一点捐款来奖励她吗？大约是 -- Of course, the church will help you, but don't you want to reward her with a small donation? It 's about the amount in }
### {278}{}{ caps.}
{278}{}{帽子。 --  caps.}
### {279}{}{Here are the bottlecaps.}
{279}{}{这是水瓶。 -- Here are the bottlecaps.}
### {280}{}{I don't have so many bottlecaps!}
{280}{}{我没有那么多瓶子！ -- I don't have so many bottlecaps!}
### {281}{}{Very sorry. In that case, I can't do anything to help.}
{281}{}{非常抱歉。在这种情况下，我无能为力。 -- Very sorry. In that case, I can't do anything to help.}
### {282}{}{How so...}
{282}{}{为什么呢 -- How so...}
### {283}{}{No need, it will heal itself.}
{283}{}{不需要，它会自愈的。 -- No need, it will heal itself.}
### {284}{}{Praise the Sacred Fire for giving you a little more time!}
{284}{}{赞美圣火给了你更多的时间！ -- Praise the Sacred Fire for giving you a little more time!}
### {285}{}{Uh, that's much better.}
{285}{}{那好多了。 -- Uh, that's much better.}
### {286}{}{}
{286}{}{error : string is empty -- }
### {287}{}{ The man in the bag! Gee!}
{287}{}{包里的那个人！哇 --  The man in the bag! Gee!}
### {288}{}{Are you talking about my cassock? (shakes his head) Oh, poor Atom child, I feel sorry for you. I would like to help you regain the Atoms of Consciousness you have lost, but I am powerless here. Go outside, Child of Radiation.}
{288}{}{你在说我的袈裟吗？（摇摇头）哦，可怜的Atom孩子，我为你感到难过。我想帮助你重新获得你失去的意识原子，但我在这里无能为力。出去吧，辐射之子。 -- Are you talking about my cassock? (shakes his head) Oh, poor Atom child, I feel sorry for you. I would like to help you regain the Atoms of Consciousness you have lost, but I am powerless here. Go outside, Child of Radiation.}
### {289}{}{Street? The street is what I love.}
{289}{}{大街我喜欢这条街。 -- Street? The street is what I love.}

#Receiving a letter of recommendation
### {290}{}{I can help the church a lot more if I get closer to its top leadership.}
{290}{}{如果我能更接近教会的最高领导层，我可以帮助教会更多。 -- I can help the church a lot more if I get closer to its top leadership.}
### {291}{}{Perhaps. It is in my power to write a letter of recommendation in your name for the main temple. But it looks like you haven't penetrated our faith enough yet.}
{291}{}{可能我有权以你的名义为主庙写一封推荐信。但你似乎还没有深入我们的信仰。 -- Perhaps. It is in my power to write a letter of recommendation in your name for the main temple. But it looks like you haven't penetrated our faith enough yet.}
### {1291}{}{Perhaps. It is in my power to write a letter of recommendation in your name for the main temple. But it looks like you haven't penetrated our faith enough yet.}
{1291}{}{可能我有权以你的名义为主庙写一封推荐信。但你似乎还没有深入我们的信仰。 -- Perhaps. It is in my power to write a letter of recommendation in your name for the main temple. But it looks like you haven't penetrated our faith enough yet.}
### {292}{}{As you say.}
{292}{}{正如你所说。 -- As you say.}
### {293}{}{Perhaps. It is in my power to write a letter of recommendation in your name for the main temple in Phoenix. This will be the beginning of your thorny path. Are you sure you're ready to accept this burden?}
{293}{}{可能我有权以你的名义为凤凰城的主庙写一封推荐信。这将是你荆棘之路的开始。你确定你已经准备好接受这个负担了吗？ -- Perhaps. It is in my power to write a letter of recommendation in your name for the main temple in Phoenix. This will be the beginning of your thorny path. Are you sure you're ready to accept this burden?}
### {1293}{}{Perhaps. It is in my power to write a letter of recommendation in your name for the main temple in Phoenix. This will be the beginning of your thorny path. Are you sure you're ready to accept this burden?}
{1293}{}{可能我有权以你的名义为凤凰城的主庙写一封推荐信。这将是你荆棘之路的开始。你确定你已经准备好接受这个负担了吗？ -- Perhaps. It is in my power to write a letter of recommendation in your name for the main temple in Phoenix. This will be the beginning of your thorny path. Are you sure you're ready to accept this burden?}
### {294}{}{Undoubtedly!}
{294}{}{毋庸置疑地 -- Undoubtedly!}
### {295}{}{I need to think.}
{295}{}{我需要思考。 -- I need to think.}
### {296}{}{Very good. Very. Here's the letter. Take care of it until you come to the main temple. This will be your first test.}
{296}{}{很好。非常这是信。好好照顾它，直到你来到主庙。这将是你的第一次测试。 -- Very good. Very. Here's the letter. Take care of it until you come to the main temple. This will be your first test.}
### {297}{}{I will carry this letter in the name of the Sacred Fire! Well, or something like that.}
{297}{}{我将以圣火的名义携带这封信！好吧，或者类似的东西。 -- I will carry this letter in the name of the Sacred Fire! Well, or something like that.}
### {298}{}{Taking into account your reputation in Flagstaff, I doubt that you will be of use in the main temple.}
{298}{}{考虑到你在弗拉格斯塔夫的声誉，我怀疑你在主庙是否有用。 -- Taking into account your reputation in Flagstaff, I doubt that you will be of use in the main temple.}
### {299}{}{}
{299}{}{error : string is empty -- }

#Quest - start:
### {300}{}{Are the bottlecaps the only problem?}
{300}{}{瓶子是唯一的问题吗？ -- Are the bottlecaps the only problem?}
### {301}{}{Many despise our faith, but usually keep it to themselves. Some are not so restrained.}
{301}{}{许多人鄙视我们的信仰，但通常对自己保密。有些人没有那么克制。 -- Many despise our faith, but usually keep it to themselves. Some are not so restrained.}
### {302}{}{Is someone threatening you?}
{302}{}{有人在威胁你吗？ -- Is someone threatening you?}
### {303}{}{Someone unknown commits despicable acts at night - draws crosses on the walls, sets fires, dirties the door with mud. Obviously, he is trying to intimidate me and persuade me to escape from the colony. But I did not manage to meet this infidel face to face.}
{303}{}{一个不知名的人在晚上做出卑鄙的行为——在墙上画十字架，纵火，用泥弄脏门。很明显，他试图恐吓我，说服我逃离殖民地。但我没能和这个异教徒面对面。 -- Someone unknown commits despicable acts at night - draws crosses on the walls, sets fires, dirties the door with mud. Obviously, he is trying to intimidate me and persuade me to escape from the colony. But I did not manage to meet this infidel face to face.}
### {304}{}{Maybe I can find him. It's interesting to find out why he disliked you so much.}
{304}{}{也许我能找到他。弄清楚他为什么这么不喜欢你是件有趣的事。 -- Maybe I can find him. It's interesting to find out why he disliked you so much.}
### {305}{}{I don't want to get involved in such dark matters. Let's change the subject.}
{305}{}{我不想卷入这种黑暗的事情。让我们换个话题。 -- I don't want to get involved in such dark matters. Let's change the subject.}
### {306}{}{I would be extremely grateful.}
{306}{}{我将不胜感激。 -- I would be extremely grateful.}
### {307}{}{Okay.}
{307}{}{可以 -- Okay.}
### {308}{}{I'm not going to "plunge anyone into darkness."}
{308}{}{我不会“让任何人陷入黑暗” -- I'm not going to "plunge anyone into darkness."}

#Quest - detection of a saboteur:
### {310}{}{Let's talk about night stalking.}
{310}{}{让我们谈谈夜间跟踪。 -- Let's talk about night stalking.}
### {311}{}{Did you find out anything?}
{311}{}{你发现什么了吗？ -- Did you find out anything?}
### {312}{}{Not yet, but I want to ask about something else.}
{312}{}{还没有，但我想问一些其他的事情。 -- Not yet, but I want to ask about something else.}
### {313}{}{Nothing new. I'll come back when I know more.}
{313}{}{没有什么新鲜事。当我知道更多的时候我会回来的。 -- Nothing new. I'll come back when I know more.}
### {314}{}{I managed to catch this vandal by surprise. It turned out to be a balding colonist from a house to the south.}
{314}{}{我出其不意地抓住了这个破坏者。原来是一个来自南方一所房子的秃头殖民者。 -- I managed to catch this vandal by surprise. It turned out to be a balding colonist from a house to the south.}
### {315}{}{Festus... A hopeless victim of atomic fission.}
{315}{}{费斯图斯。。。原子裂变的无望受害者。 -- Festus... A hopeless victim of atomic fission.}
### {316}{}{Do you know each other?}
{316}{}{你们彼此认识吗？ -- Do you know each other?}
### {317}{}{He came to the sermons, but could not penetrate the radiant truths of Fire. When the time came, Festus was blinded by anger and pride. And I closed the doors of the temple before him.}
{317}{}{他参加了讲道，但无法穿透火的光辉真理。时间到了，非斯都被愤怒和骄傲蒙蔽了双眼。我在他面前关上殿的门。 -- He came to the sermons, but could not penetrate the radiant truths of Fire. When the time came, Festus was blinded by anger and pride. And I closed the doors of the temple before him.}
### {318}{}{What happened?}
{318}{}{发生了什么？ -- What happened?}
### {319}{}{Festus' child became a quantum of discord. I begged to send this gifted youngster to study at the temple, but Festus refused in a rage. Alas, even in Flagstaff, many do not understand the value of knowledge and rely only on brute force.}
{319}{}{费斯图斯的孩子成了一个不和的人。我恳求派这个有天赋的年轻人去寺庙学习，但费斯图斯愤怒地拒绝了。遗憾的是，即使在弗拉格斯塔夫，许多人也不理解知识的价值，只依靠暴力。 -- Festus' child became a quantum of discord. I begged to send this gifted youngster to study at the temple, but Festus refused in a rage. Alas, even in Flagstaff, many do not understand the value of knowledge and rely only on brute force.}
### {320}{}{[Next]}
{320}{}{[下一个 -- Next]}
### {321}{}{When the boy was seized by a radiant illness, I promised free treatment if the father changed his mind and gave his son to the temple. But Festus' hatred proved irresistible. Obviously, he's taking revenge now.}
{321}{}{当这个男孩得了一场光怪陆离的病时，我答应，如果父亲改变主意，把儿子送到寺庙，我会免费治疗。但事实证明，费斯图的仇恨是无法抗拒的。很明显，他现在正在报复。 -- When the boy was seized by a radiant illness, I promised free treatment if the father changed his mind and gave his son to the temple. But Festus' hatred proved irresistible. Obviously, he's taking revenge now.}
### {322}{}{What can I do?}
{322}{}{我能做什么？ -- What can I do?}
### {323}{}{To reason with Festus so that he would abandon the threats and give the child to the temple? This is extremely difficult.}
{323}{}{跟非斯都讲道理，让他放弃威胁，把孩子交给圣殿？这是非常困难的。 -- To reason with Festus so that he would abandon the threats and give the child to the temple? This is extremely difficult.}
### {324}{}{It remains... murder?}
{324}{}{它仍然。。。谋杀 -- It remains... murder?}
### {325}{}{Uh, I'll try the first option.}
{325}{}{呃，我会试试第一种选择。 -- Uh, I'll try the first option.}
### {326}{}{I need time to think.}
{326}{}{我需要时间思考。 -- I need time to think.}
### {327}{}{When nuclear fuel becomes harmful, it is isolated and plunged into darkness. Otherwise it will be dangerous to others.}
{327}{}{当核燃料变得有害时，它就会被孤立并陷入黑暗。否则会对他人造成危险。 -- When nuclear fuel becomes harmful, it is isolated and plunged into darkness. Otherwise it will be dangerous to others.}
### {328}{}{Well, may the Sacred Fire help you.}
{328}{}{愿圣火帮助你。 -- Well, may the Sacred Fire help you.}
### {329}{}{Uh, okay.}
{329}{}{好吧。 -- Uh, okay.}

#Quest - quest completion:
### {330}{}{Let's talk about the Festus problem.}
{330}{}{让我们来谈谈费斯图斯问题。 -- Let's talk about the Festus problem.}
### {331}{}{I'm listening.}
{331}{}{我在听。 -- I'm listening.}
### {332}{}{I would like to ask questions about something else.}
{332}{}{我想问一些其他的问题。 -- I would like to ask questions about something else.}
### {333}{}{I'll come back when I solve the problem.}
{333}{}{我解决问题后会回来的。 -- I'll come back when I solve the problem.}
### {334}{}{I managed to convince Festus. He will give his son to study and stop the persecution.}
{334}{}{我设法说服了费斯图斯。他会让他的儿子学习并停止迫害。 -- I managed to convince Festus. He will give his son to study and stop the persecution.}
### {335}{}{Truly great is the Power of the Atom! Festus is waiting for public repentance, but his son has a great future as a scribe and scientist in the temple of Fire. Great job.}
{335}{}{真正伟大的是原子的力量！费斯图正在等待公众的忏悔，但他的儿子作为火神庙的抄写员和科学家有着美好的未来。干得好。 -- Truly great is the Power of the Atom! Festus is waiting for public repentance, but his son has a great future as a scribe and scientist in the temple of Fire. Great job.}
### {336}{}{It happened to Festus... accident. He's not a problem anymore.}
{336}{}{这件事发生在费斯图斯身上。。。事故他不再是个问题了。 -- It happened to Festus... accident. He's not a problem anymore.}
### {337}{}{May the Sacred Fire incinerate his soul! Festus could not be reformed anyway, and his conversion to our faith would only serve to harm. But his son has a great future as a scribe and scientist in the temple of Fire. Good job.}
{337}{}{愿圣火焚烧他的灵魂！费斯图无论如何都不能被改造，他皈依我们的信仰只会带来伤害。但他的儿子作为一名抄写员和科学家在火神庙有着美好的未来。干得好 -- May the Sacred Fire incinerate his soul! Festus could not be reformed anyway, and his conversion to our faith would only serve to harm. But his son has a great future as a scribe and scientist in the temple of Fire. Good job.}
### {338}{}{How can I reward you for your efforts?}
{338}{}{我怎样才能报答你的努力？ -- How can I reward you for your efforts?}
### {339}{}{Do not mention it. All for the sake of faith.}
{339}{}{别提了，都是为了信仰。 -- Do not mention it. All for the sake of faith.}
### {340}{}{I need medications - Radaway and two stimpacks.}
{340}{}{我需要药物-Radaway和两个刺激包。 -- I need medications - Radaway and two stimpacks.}
### {341}{}{Can I count on a 20% discount for treatment?}
{341}{}{我可以指望20%的治疗折扣吗？ -- Can I count on a 20% discount for treatment?}
### {342}{}{I need caps to release my fellow tribesmen from prison.}
{342}{}{我需要帽子才能把我的部落同胞从监狱里释放出来。 -- I need caps to release my fellow tribesmen from prison.}
### {343}{}{I have a big dream - to get to the main temple of Fire and turn to its leader.}
{343}{}{我有一个远大的梦想——去主火神庙，向它的领袖求助。 -- I have a big dream - to get to the main temple of Fire and turn to its leader.}
### {344}{}{I need access to your library.}
{344}{}{我需要进入你们的图书馆。 -- I need access to your library.}
### {345}{}{[Next]}
{345}{}{[下一个 -- Next]}
### {346}{}{}
{346}{}{error : string is empty -- }
### {347}{}{But how to do this without drawing the wrath of the rest of the colonists?}
{347}{}{但是如何做到这一点而不引起其他殖民者的愤怒呢？ -- But how to do this without drawing the wrath of the rest of the colonists?}
### {348}{}{Hmm. Festus suffers from the effects of radiation. It is enough to throw him something highly radioactive to speed up the process of decomposition of his soul into atoms. Surely there is such an object in the uranium mine.}
{348}{}{费斯图斯受到辐射的影响。只要扔给他一些高放射性的东西就足以加速他的灵魂分解成原子的过程。铀矿里肯定有这样一个物体。 -- Hmm. Festus suffers from the effects of radiation. It is enough to throw him something highly radioactive to speed up the process of decomposition of his soul into atoms. Surely there is such an object in the uranium mine.}
### {349}{}{An accident? Lethal radiation dose? Poison? I am not an expert on such issues.}
{349}{}{意外？致命辐射剂量？毒药我不是这方面的专家。 -- An accident? Lethal radiation dose? Poison? I am not an expert on such issues.}

### {350}{}{Thank you.}
{350}{}{非常感谢。 -- Thank you.}
### {351}{}{May the Flame of Heaven protect you. At the next sermon I will tell you about your benefactor. I'm sure it will raise your reputation in the eyes of ordinary colonists.}
{351}{}{愿天堂之火保护你。在下一次布道时，我会告诉你你的恩人。我相信这会提高你在普通殖民者眼中的声誉。 -- May the Flame of Heaven protect you. At the next sermon I will tell you about your benefactor. I'm sure it will raise your reputation in the eyes of ordinary colonists.}
### {352}{}{Well, it's deserved. Take it.}
{352}{}{这是应得的。拿着。 -- Well, it's deserved. Take it.}
### {353}{}{Well, it's deserved. You can count on... "discount".}
{353}{}{这是应得的。你可以指望…“折扣”。 -- Well, it's deserved. You can count on... "discount".}
### {354}{}{I can only offer 100 caps, as parishioners are stingy with donations. However, this is enough to get Faber to talk.}
{354}{}{我只能提供100顶帽子，因为教区居民对捐款很吝啬。然而，这足以让费伯开口说话。 -- I can only offer 100 caps, as parishioners are stingy with donations. However, this is enough to get Faber to talk.}
### {355}{}{Hmm. I can write a letter of recommendation to the main Fire temple in Phoenix. But still your merit is not so great. We'll have to make some more donations.}
{355}{}{嗯。我可以写一封推荐信给凤凰城的主火神庙。但是你的优点还是不那么大。我们还得再捐款。 -- Hmm. I can write a letter of recommendation to the main Fire temple in Phoenix. But still your merit is not so great. We'll have to make some more donations.}
### {356}{}{This collection of priceless pre-war knowledge requires special treatment. Treat him with respect.}
{356}{}{这些珍贵的战前知识需要特殊处理。尊重他。 -- This collection of priceless pre-war knowledge requires special treatment. Treat him with respect.}
### {357}{}{Forget about Festus and his baby. You're late.}
{357}{}{忘掉费斯图斯和他的孩子吧。你迟到了。 -- Forget about Festus and his baby. You're late.}
### {358}{}{Is he cured again? It seemed to me that this problem would never be solved without my intervention. Well, with great regret I have to give up my demands.}
{358}{}{他又治好了吗？在我看来，如果没有我的干预，这个问题永远无法解决。很遗憾，我不得不放弃我的要求。 -- Is he cured again? It seemed to me that this problem would never be solved without my intervention. Well, with great regret I have to give up my demands.}
### {359}{}{This will be a lesson to you.}
{359}{}{这将是你的一个教训。 -- This will be a lesson to you.}

#Treatment of Festus' son
### {360}{}{Festus' son needs treatment.}
{360}{}{费斯图斯的儿子需要治疗。 -- Festus' son needs treatment.}
### {361}{}{And I will gladly help him if he agrees to visit the temple.}
{361}{}{如果他同意参观寺庙，我会很乐意帮助他。 -- And I will gladly help him if he agrees to visit the temple.}
### {362}{}{Okay.}
{362}{}{可以 -- Okay.}
### {363}{}{We've already eliminated Festus. It's time to fulfill the promise.}
{363}{}{我们已经淘汰了费斯图斯。是时候兑现承诺了。 -- We've already eliminated Festus. It's time to fulfill the promise.}
### {364}{}{Delaying the process will not please the main temple of Fire.}
{364}{}{推迟这个过程不会让主火神庙满意。 -- Delaying the process will not please the main temple of Fire.}
### {365}{}{Your integrity will only turn people against us.}
{365}{}{你的正直只会让人们反对我们。 -- Your integrity will only turn people against us.}
### {366}{}{The temple will increase its reputation if it concedes in this situation.}
{366}{}{如果寺庙在这种情况下让步，它的声誉会提高。 -- The temple will increase its reputation if it concedes in this situation.}
### {367}{}{Then I'll start treatment as soon as I'm ready.}
{367}{}{那我一准备好就开始治疗。 -- Then I'll start treatment as soon as I'm ready.}
### {368}{}{That's good.}
{368}{}{这很好。 -- That's good.}
### {369}{}{I'll stay on my own.}
{369}{}{我会一个人呆着。 -- I'll stay on my own.}
### {370}{}{Expected...}
{370}{}{应为。。。 -- Expected...}
### {371}{}{Why such unscrupulousness?}
{371}{}{为什么如此肆无忌惮？ -- Why such unscrupulousness?}
### {372}{}{It's hard to change adults. And often it doesn't make much sense. It is through children that the roots of faith must be planted. And the treatment will be forgotten. After all, people are not distinguished by gratitude now.}
{372}{}{很难改变成年人。而且这通常没有多大意义。必须通过儿童来种植信仰的根。这种治疗方式将被遗忘。毕竟，现在人们不以感恩来区分。 -- It's hard to change adults. And often it doesn't make much sense. It is through children that the roots of faith must be planted. And the treatment will be forgotten. After all, people are not distinguished by gratitude now.}
### {373}{}{I see.}
{373}{}{我明白了。 -- I see.}

#Dialogue corrections after the events at the Phoenix Temple
### {400}{}{Leave me in the po... Oh, it's you. Nevermind.}
{400}{}{把我留在办公室。。。哦，是你。永远不会。 -- Leave me in the po... Oh, it's you. Nevermind.}
### {401}{}{Is someone bothering you?}
{401}{}{有人打扰你吗？ -- Is someone bothering you?}
### {402}{}{The colonists became intolerant of my faith when they learned about the events in the south. Some people want to expel me from the city. But from now on I have nowhere to go.}
{402}{}{当殖民者了解到南方发生的事件时，他们对我的信仰变得无法容忍。有些人想把我逐出这个城市。但从现在起我无处可去。 -- The colonists became intolerant of my faith when they learned about the events in the south. Some people want to expel me from the city. But from now on I have nowhere to go.}
### {403}{}{Looks like you're in big trouble. I'd better get out of here.}
{403}{}{看起来你有大麻烦了。我最好离开这里。 -- Looks like you're in big trouble. I'd better get out of here.}
### {404}{}{Greetings to you. I am glad to see a brother in faith in my monastery. Welcome to the radiant Flagstaff!}
{404}{}{问候你。我很高兴在我的修道院里看到一个有信仰的兄弟。欢迎来到光芒四射的Flagstaff！ -- Greetings to you. I am glad to see a brother in faith in my monastery. Welcome to the radiant Flagstaff!}
### {1404}{}{Greetings to you. I am glad to see a sister in faith in my monastery. Welcome to the radiant Flagstaff!}
{1404}{}{问候你。我很高兴在我的修道院里看到一个有信仰的姐姐。欢迎来到光芒四射的Flagstaff！ -- Greetings to you. I am glad to see a sister in faith in my monastery. Welcome to the radiant Flagstaff!}
### {405}{}{How did you find out about my promotion?}
{405}{}{你是怎么知道我升职的？ -- How did you find out about my promotion?}
### {406}{}{For our faith, distance is an insignificant barrier. The Messengers of Rebirth have reported about you.}
{406}{}{对于我们的信仰来说，距离是一个微不足道的障碍。重生使者已经报道了你的情况。 -- For our faith, distance is an insignificant barrier. The Messengers of Rebirth have reported about you.}
### {407}{}{Oh yes, the postal service...}
{407}{}{哦，是的，邮政服务。。。 -- Oh yes, the postal service...}
### {408}{}{}
{408}{}{error : string is empty -- }
### {409}{}{}
{409}{}{error : string is empty -- }
### {410}{}{So how can I help, brother?}
{410}{}{那我该怎么帮你，兄弟？ -- So how can I help, brother?}
### {1410}{}{So how can I help, Sister?}
{1410}{}{姐姐，我能帮什么忙？ -- So how can I help, Sister?}
### {411}{}{Stop! And what do you, brother in faith, know about what happened in Phoenix?}
{411}{}{停止你，信仰的兄弟，对凤凰城发生的事情了解多少？ -- Stop! And what do you, brother in faith, know about what happened in Phoenix?}
### {1411}{}{Stop! And what do you, a sister in faith, know about what happened in Phoenix?}
{1411}{}{停止作为一个有信仰的姐妹，你对凤凰城发生的事情了解多少？ -- Stop! And what do you, a sister in faith, know about what happened in Phoenix?}
### {412}{}{Uh, the same as you.}
{412}{}{和你一样。 -- Uh, the same as you.}
### {413}{}{I blew up the temple of Fire. Because of him, a tragedy has befallen the Villa, so taste the same.}
{413}{}{我炸毁了火神庙。因为他，一场悲剧降临在维拉身上，所以请品尝同样的味道。 -- I blew up the temple of Fire. Because of him, a tragedy has befallen the Villa, so taste the same.}
### {1413}{}{I blew up the temple of Fire. Because of him, a tragedy struck the Villa, so taste the same.}
{1413}{}{我炸毁了火神庙。因为他，一场悲剧袭击了维拉，所以味道一样。 -- I blew up the temple of Fire. Because of him, a tragedy struck the Villa, so taste the same.}
### {414}{}{Hmm. Very sorry. Very.}
{414}{}{嗯，非常抱歉。非常 -- Hmm. Very sorry. Very.}
### {415}{}{Uh, I think I'll go.}
{415}{}{呃，我想我会去的。 -- Uh, I think I'll go.}
### {416}{}{That's how. It was revenge... What a barbaric motive! But if I am not a member of the cult now, then it remains to throw off the robe of a preacher and get away from Flagstaff. Your action gives me the right to start all over again. Maybe it's not so bad.}
{416}{}{就是这样。这是复仇。。。多么野蛮的动机！但是，如果我现在不是邪教的一员，那么脱下传教士的长袍，离开弗拉格斯塔夫就是了。你的行为给了我重新开始的权利。也许还没那么糟。 -- That's how. It was revenge... What a barbaric motive! But if I am not a member of the cult now, then it remains to throw off the robe of a preacher and get away from Flagstaff. Your action gives me the right to start all over again. Maybe it's not so bad.}
### {417}{}{Well, come on.}
{417}{}{好吧，来吧。 -- Well, come on.}
### {418}{}{I have received news of your expulsion from the Brotherhood of Fire. I need to know the reasons.}
{418}{}{我收到了你被火兄弟会开除的消息。我需要知道原因。 -- I have received news of your expulsion from the Brotherhood of Fire. I need to know the reasons.}
### {419}{}{Do you need reasons? Shove them up your ass, sectarian!}
{419}{}{你需要理由吗？把他们推上你的屁股，宗派主义者！ -- Do you need reasons? Shove them up your ass, sectarian!}
### {420}{}{I will not tolerate abuse of my faith! The Sacred Fire is not a fiction. He was actually a hundred years ago! If even after all my sermons you do not believe the obvious, we can only hope for your speedy splitting into atoms.}
{420}{}{我不会容忍滥用我的信仰！《圣火》不是虚构的。他实际上是一百年前的人了！即使在我所有的布道之后，你也不相信显而易见的，我们只能希望你能迅速分裂成原子。 -- I will not tolerate abuse of my faith! The Sacred Fire is not a fiction. He was actually a hundred years ago! If even after all my sermons you do not believe the obvious, we can only hope for your speedy splitting into atoms.}
### {421}{}{Well, well.}
{421}{}{嗯，嗯。 -- Well, well.}
### {422}{}{Your faith preaches the wrong ideas.}
{422}{}{你的信仰宣扬错误的思想。 -- Your faith preaches the wrong ideas.}
### {423}{}{Are you saying there was no Sacred Fire? And that we shouldn't restore the world to its former greatness by correcting its arrogant mistakes? What should we do then? Still dragging out a miserable existence among the ruins and barren wasteland? Then stay in your blissful blindness.}
{423}{}{你是说没有圣火吗？我们不应该通过纠正傲慢的错误来恢复世界昔日的伟大吗？那我们该怎么办？还在废墟和贫瘠的荒地中艰难地生存？那就呆在你幸福的盲目中吧。 -- Are you saying there was no Sacred Fire? And that we shouldn't restore the world to its former greatness by correcting its arrogant mistakes? What should we do then? Still dragging out a miserable existence among the ruins and barren wasteland? Then stay in your blissful blindness.}
### {424}{}{Well, well.}
{424}{}{嗯，嗯。 -- Well, well.}
### {425}{}{I still believe in Fire and still long for Rebirth, brother.}
{425}{}{我仍然相信火，仍然渴望重生，兄弟。 -- I still believe in Fire and still long for Rebirth, brother.}
### {426}{}{Your lies are only an outrage on faith. Get out of Flagstaff until the Fire opens your eyes to the truth.}
{426}{}{你的谎言只是对信仰的愤怒。离开弗拉格斯塔夫，直到大火让你看到真相。 -- Your lies are only an outrage on faith. Get out of Flagstaff until the Fire opens your eyes to the truth.}
### {427}{}{Well, well.}
{427}{}{嗯，嗯。 -- Well, well.}
### {428}{}{Can I trust you... brother? Perhaps you are not lost to our mission yet. Go ahead. And show your devotion to the faith with real deeds. Under the flag of the temple or without it.}
{428}{}{我能相信你吗。。。兄弟也许你还没有迷失在我们的使命中。着手用实际行动表明你对信仰的虔诚。在寺庙的旗帜下或没有它。 -- Can I trust you... brother? Perhaps you are not lost to our mission yet. Go ahead. And show your devotion to the faith with real deeds. Under the flag of the temple or without it.}
### {1428}{}{Can I trust you... sister? Perhaps you are not lost to our mission yet. Go ahead. And show your devotion to the faith with real deeds. Under the flag of the temple or without it.}
{1428}{}{我能相信你吗。。。姐妹也许你还没有迷失在我们的使命中。着手用实际行动表明你对信仰的虔诚。在寺庙的旗帜下或没有它。 -- Can I trust you... sister? Perhaps you are not lost to our mission yet. Go ahead. And show your devotion to the faith with real deeds. Under the flag of the temple or without it.}
### {429}{}{Okay.}
{429}{}{可以 -- Okay.}
### {430}{}{By your very existence you are already helping the church. But we always need bottlecaps from any hands.}
{430}{}{由于你的存在，你已经在帮助教会了。但我们总是需要任何人的瓶装水。 -- By your very existence you are already helping the church. But we always need bottlecaps from any hands.}
### {431}{}{Anyone should not be allowed to enter the mysteries of the Sacred Fire. After all, this knowledge can be used both for good and for harm...}
{431}{}{任何人都不应该被允许进入神圣之火的奥秘。毕竟，这些知识既可以用来做好事，也可以用来做坏事。。。 -- Anyone should not be allowed to enter the mysteries of the Sacred Fire. After all, this knowledge can be used both for good and for harm...}
### {432}{}{Of course. And I have already proved my devotion to the faith.}
{432}{}{当然我已经证明了我对信仰的虔诚。 -- Of course. And I have already proved my devotion to the faith.}
### {1432}{}{Of course. And I have already proved my devotion to faith.}
{1432}{}{当然我已经证明了我对信仰的虔诚。 -- Of course. And I have already proved my devotion to faith.}
### {433}{}{A strange question for a fellow believer. I am Hiram, the priest of this temple.}
{433}{}{对于一个信徒来说，这是一个奇怪的问题。我叫希兰，是这庙的祭司。 -- A strange question for a fellow believer. I am Hiram, the priest of this temple.}
### {1433}{}{A strange question for a sister in faith. I am Hiram, the priest of this temple.}
{1433}{}{对于一个有信仰的姐姐来说，这是一个奇怪的问题。我叫希兰，是这庙的祭司。 -- A strange question for a sister in faith. I am Hiram, the priest of this temple.}
### {434}{}{Oh, absolutely. But can you read?}
{434}{}{哦，当然。但是你会读书吗？ -- Oh, absolutely. But can you read?}
