### {100}{}{Here is a colonist.}
{100}{}{这是一位殖民者。 -- Here is a colonist.}
### {101}{}{You see a citizen of the colony.}
{101}{}{你看到一个殖民地的公民。 -- You see a citizen of the colony.}
### {102}{}{I want to sleep, leave me alone.}
{102}{}{我想睡觉，别管我。 -- I want to sleep, leave me alone.}
### {103}{}{Z-z-z...}
{103}{}{Z-Z-Z。。。 -- Z-z-z...}
### {104}{}{...}
{104}{}{。。。 -- ...}
### {105}{}{ }
{105}{}{error : string is empty --  }
### {106}{}{*Yawns*}
{106}{}{*Yawns* -- *Yawns*}
### {107}{}{Where did you come from?}
{107}{}{你从哪里来的？ -- Where did you come from?}
### {108}{}{I want to sleep, leave me alone.}
{108}{}{我想睡觉，别管我。 -- I want to sleep, leave me alone.}

#Floating replicas (they are responses when trying to speak)
### {110}{}{Do you know about the curfew? You can't go outside after it.}
{110}{}{你知道宵禁吗？之后你不能出去。 -- Do you know about the curfew? You can't go outside after it.}
### {111}{}{So far it is the safest city in Arizona.}
{111}{}{到目前为止，它是亚利桑那州最安全的城市。 -- So far it is the safest city in Arizona.}
### {112}{}{Sometimes I miss the Phoenix night lights.}
{112}{}{有时我会想念凤凰城的夜灯。 -- Sometimes I miss the Phoenix night lights.}
### {113}{}{My hamstrings tremble when I see Faber.}
{113}{}{当我看到费伯时，我的腿筋都在发抖。 -- My hamstrings tremble when I see Faber.}
### {114}{}{They say there are bandits in the abandoned ruins.}
{114}{}{他们说废弃的废墟里有土匪。 -- They say there are bandits in the abandoned ruins.}
### {115}{}{When will the new stagecoach arrive?}
{115}{}{新的驿站马车什么时候到？ -- When will the new stagecoach arrive?}
### {116}{}{Never trust a servant.}
{116}{}{永远不要相信仆人。 -- Never trust a servant.}
### {117}{}{I'm a little afraid to go into the garrison area.}
{117}{}{我有点害怕进入警备区。 -- I'm a little afraid to go into the garrison area.}
### {118}{}{Don't forget about the evening sermon.}
{118}{}{别忘了晚上的布道。 -- Don't forget about the evening sermon.}
### {119}{}{Taxes are high here, but it's worth it.}
{119}{}{这里的税收很高，但这是值得的。 -- Taxes are high here, but it's worth it.}
### {120}{}{Humphries Peak has a great view.}
{120}{}{汉弗莱斯峰的景色很好。 -- Humphries Peak has a great view.}

### {150}{}{Now I'm afraid to go outside.}
{150}{}{现在我不敢出门了。 -- Now I'm afraid to go outside.}
### {151}{}{Even in the den of scorpions is safer than here.}
{151}{}{即使在蝎子窝里也比这里更安全。 -- Even in the den of scorpions is safer than here.}
### {152}{}{We shouldn't have moved here.}
{152}{}{我们不应该搬到这里。 -- We shouldn't have moved here.}
### {153}{}{How could we be wrong about the Faber Swarm?}
{153}{}{我们怎么会对Faber Swarm说错了？ -- How could we be wrong about the Faber Swarm?}
### {154}{}{They say there are bandits in the suburbs.}
{154}{}{他们说郊区有土匪。 -- They say there are bandits in the suburbs.}
### {155}{}{There are fewer and fewer caravans.}
{155}{}{大篷车越来越少了。 -- There are fewer and fewer caravans.}
### {156}{}{Hire a maid? Well, no.}
{156}{}{雇个女佣？嗯，没有。 -- Hire a maid? Well, no.}
### {157}{}{Not a step into the garrison now.}
{157}{}{现在一步也没进驻军。 -- Not a step into the garrison now.}
### {158}{}{Let this preacher bring the bandits to reason first.}
{158}{}{让这位传教士先给土匪讲道理。 -- Let this preacher bring the bandits to reason first.}
### {159}{}{And what do we pay taxes for?}
{159}{}{我们纳税的目的是什么？ -- And what do we pay taxes for?}
### {160}{}{As soon as it smells fried, I'll run to Humphries Peak.}
{160}{}{一闻到油炸的味道，我就去汉弗莱斯峰。 -- As soon as it smells fried, I'll run to Humphries Peak.}
