### {100}{}{Here is a robber.}
{100}{}{这是一个强盗。 -- Here is a robber.}
### {101}{}{You see an escaped prisoner. He is armed and very dangerous.}
{101}{}{你看到一个逃犯。他带着武器，非常危险。 -- You see an escaped prisoner. He is armed and very dangerous.}
### {102}{}{Come closer and you're dead!}
{102}{}{走近一点，你就死定了！ -- Come closer and you're dead!}
### {103}{}{It seems that the city has become unsafe.}
{103}{}{这座城市似乎变得不安全了。 -- It seems that the city has become unsafe.}
### {104}{}{Put your weapon away, otherwise I'll cut everyone here!}
{104}{}{把你的武器收起来，否则我会把这里的人都砍了！ -- Put your weapon away, otherwise I'll cut everyone here!}

#Floating replicas
### {110}{}{caps on the table! Quickly!}
{110}{}{桌子上的帽子！迅速地 -- caps on the table! Quickly!}
### {111}{}{If you don't want it in a good way, it will be in a bad way.}
{111}{}{如果你不想以好的方式得到它，它就会以坏的方式得到。 -- If you don't want it in a good way, it will be in a bad way.}
### {112}{}{Drive the bottlecaps, I said!}
{112}{}{我说，开瓶车！ -- Drive the bottlecaps, I said!}
### {113}{}{I'm going to lose my temper.}
{113}{}{我要发脾气了。 -- I'm going to lose my temper.}
### {114}{}{You're going to die, bitch, if you don't give up all the caps.}
{114}{}{你会死的，婊子，如果你不放弃所有的帽子。 -- You're going to die, bitch, if you don't give up all the caps.}
### {115}{}{Face down! Quickly!}
{115}{}{脸朝下！迅速地 -- Face down! Quickly!}

#Dialog
### {200}{}{Hey, you. Give me all your caps. Now!}
{200}{}{嘿，你。把你所有的帽子都给我。现在 -- Hey, you. Give me all your caps. Now!}
### {201}{}{Okay, okay, here are 50 caps for you, just don't use violence...}
{201}{}{好吧，好吧，这里有50顶帽子给你，只是不要使用暴力。。。 -- Okay, okay, here are 50 caps for you, just don't use violence...}
### {202}{}{This is all? Damn, I won't get far this way... Now stand by the wall and count to a thousand. Do you understand?}
{202}{}{这就是全部？妈的，我这条路走不了多远。。。现在站在墙边数一千。你明白吗？ -- This is all? Damn, I won't get far this way... Now stand by the wall and count to a thousand. Do you understand?}
### {203}{}{Uh, whatever you say...}
{203}{}{不管你说什么。。。 -- Uh, whatever you say...}
### {204}{}{That's it, I've had enough. It's time to beat the shit out of you!}
{204}{}{就这样，我受够了。是时候把你打得落花流水了！ -- That's it, I've had enough. It's time to beat the shit out of you!}
### {205}{}{Calm down, it's not worth shedding blood. You still have a way out.}
{205}{}{冷静点，流血是不值得的。你还有一条路要走。 -- Calm down, it's not worth shedding blood. You still have a way out.}
### {206}{}{I said, give-all-your-caps. Immediately!}
{206}{}{我说，把你所有的帽子都给我。立即 -- I said, give-all-your-caps. Immediately!}
### {207}{}{Okay, okay, here are all my bottlecaps, just don't use violence...}
{207}{}{好吧，好吧，这是我所有的瓶子，只是不要使用暴力。。。 -- Okay, okay, here are all my bottlecaps, just don't use violence...}
### {208}{}{What the hell are you talking about?! After escaping, I can only go to another city, and what will I do there without bottlecaps?}
{208}{}{你在说什么？！逃离后，我只能去另一个城市，如果没有水瓶，我在那里该怎么办？ -- What the hell are you talking about?! After escaping, I can only go to another city, and what will I do there without bottlecaps?}
### {209}{}{But on the way, the bottlecaps will definitely not help you.}
{209}{}{但在路上，瓶装水肯定不会帮助你。 -- But on the way, the bottlecaps will definitely not help you.}
### {210}{}{Damn, that's right... So, this... Turn to the wall and count to a thousand. Understand?}
{210}{}{该死，没错。。。所以，这个。。。转向墙，数一千。懂 -- Damn, that's right... So, this... Turn to the wall and count to a thousand. Understand?}
### {211}{}{You won't get anything.}
{211}{}{你什么都得不到。 -- You won't get anything.}
### {212}{}{Really? Let's take a look at it!}
{212}{}{真正地让我们来看看吧！ -- Really? Let's take a look at it!}
### {213}{}{Hey, be careful with that!}
{213}{}{嘿，小心！ -- Hey, be careful with that!}
### {214}{}{Great, let's start the fun!}
{214}{}{太好了，让我们开始玩吧！ -- Great, let's start the fun!}
### {215}{}{I don't have caps. Honestly!}
{215}{}{我没有帽子。真的 -- I don't have caps. Honestly!}
### {216}{}{You'RE LYING!}
{216}{}{你在撒谎！ -- You'RE LYING!}
