### {100}{}{You have a child in front of you.}
{100}{}{你面前有个孩子。 -- You have a child in front of you.}
### {101}{}{You see the child of one of the colonists.}
{101}{}{你看到一个殖民者的孩子。 -- You see the child of one of the colonists.}
### {102}{}{I'll tell everyone that you're pushing!}
{102}{}{我会告诉大家你在努力！ -- I'll tell everyone that you're pushing!}

### {104}{}{A real doctor is needed here. Or several servings of Radawaye.}
{104}{}{这里需要一位真正的医生。或者几份Radawaye。 -- A real doctor is needed here. Or several servings of Radawaye.}

#Retaliatory remarks
### {110}{}{Hello.}
{110}{}{你好 -- Hello.}
### {111}{}{Z-z-z}
{111}{}{Z-Z-Z -- Z-z-z}
### {112}{}{Here are my ulcers. Here and here. And here too.}
{112}{}{这是我的溃疡。这里和这里。这里也是。 -- Here are my ulcers. Here and here. And here too.}
### {113}{}{I feel much better now!}
{113}{}{我现在感觉好多了！ -- I feel much better now!}

### {116}{}{The situation is running.}
{116}{}{情况正在恶化。 -- The situation is running.}
### {117}{}{As soon as you find an exhausted vein, you inject an Radaway solution. This will significantly facilitate the treatment process.}
{117}{}{一旦你发现耗尽的静脉，你就注射Radaway溶液。这将大大促进治疗过程。 -- As soon as you find an exhausted vein, you inject an Radaway solution. This will significantly facilitate the treatment process.}
### {118}{}{Now you can start treatment.}
{118}{}{现在你可以开始治疗了。 -- Now you can start treatment.}
### {119}{}{The patient is on the mend. Great job!}
{119}{}{病人正在好转。干得好！ -- The patient is on the mend. Great job!}
### {120}{}{Keep it up.}
{120}{}{坚持下去。 -- Keep it up.}
