### {100}{}{There is a guard in front of you.}
{100}{}{你面前有一个警卫。 -- There is a guard in front of you.}
### {101}{}{You see an ordinary mercenary who watches the entrance to the colony.}
{101}{}{你看到一个普通的雇佣兵在监视殖民地的入口。 -- You see an ordinary mercenary who watches the entrance to the colony.}
### {102}{}{That would be right away.}
{102}{}{那就马上。 -- That would be right away.}
### {103}{}{Until this guard comes to his senses, you can sneak into the pen.}
{103}{}{在这个警卫苏醒过来之前，你可以偷偷溜进围栏。 -- Until this guard comes to his senses, you can sneak into the pen.}
### {104}{}{Hr-r-r... Eh? Come in...}
{104}{}{小时-小时。。。呃？进来吧 -- Hr-r-r... Eh? Come in...}
### {105}{}{Wait, closed territory, entrance only with the permission of the boss.}
{105}{}{等等，封闭的区域，只有在老板允许的情况下才能进入。 -- Wait, closed territory, entrance only with the permission of the boss.}
### {106}{}{I warned you!}
{106}{}{我警告过你！ -- I warned you!}
### {107}{}{This is a high-security area. Don't try to create problems.}
{107}{}{这是一个高度安全的区域。不要试图制造问题。 -- This is a high-security area. Don't try to create problems.}

#Retaliatory remarks - a good attitude
### {110}{}{I'm watching you.}
{110}{}{我在看着你。 -- I'm watching you.}
### {111}{}{Don't try to get into the pen without permission.}
{111}{}{未经允许，不要试图进入钢笔。 -- Don't try to get into the pen without permission.}
### {112}{}{What's behind that door? Your death if you go there.}
{112}{}{那扇门后面是什么？如果你去那里，你就会死。 -- What's behind that door? Your death if you go there.}
### {113}{}{Login only with the permission of the boss.}
{113}{}{只有在老板允许的情况下才能登录。 -- Login only with the permission of the boss.}
### {114}{}{You can't go there.}
{114}{}{你不能去那里。 -- You can't go there.}

### {120}{}{That's right, you have a security clearance.}
{120}{}{没错，你有安全许可。 -- That's right, you have a security clearance.}
### {121}{}{You can go to the pen.}
{121}{}{你可以去钢笔那里。 -- You can go to the pen.}
### {122}{}{Come in, the door is open.}
{122}{}{进来，门开着。 -- Come in, the door is open.}
### {123}{}{Do you have a security clearance? Then come on in.}
{123}{}{你有安全许可证吗？那就进来吧。 -- Do you have a security clearance? Then come on in.}
