### {101}{}{Here is an old table equipped for the repair of collars.}
{101}{}{这是一张用来修理项圈的旧桌子。 -- Here is an old table equipped for the repair of collars.}
### {110}{}{Prisoners' collars are being repaired on this table.}
{110}{}{犯人的项圈正在这张桌子上修理。 -- Prisoners' collars are being repaired on this table.}
### {111}{}{All components are used up. There's nothing else to do here.}
{111}{}{所有部件都用完了。这里没有别的事可做。 -- All components are used up. There's nothing else to do here.}
### {112}{}{Having disassembled the details, you received a micro-core battery for 8 charges.}
{112}{}{拆开细节后，您收到了一个充电8次的微芯电池。 -- Having disassembled the details, you received a micro-core battery for 8 charges.}
### {113}{}{Having disassembled the details, you received a micro-core battery for 16 charges.}
{113}{}{拆开细节后，您收到了一个可充电16次的微芯电池。 -- Having disassembled the details, you received a micro-core battery for 16 charges.}
### {114}{}{Having disassembled the details, you received a 20-charge micro-core battery.}
{114}{}{拆开细节后，您收到了一个20充电的微芯电池。 -- Having disassembled the details, you received a 20-charge micro-core battery.}
