### {100}{}{Here is the bartender.}
{100}{}{这是酒保。 -- Here is the bartender.}
### {101}{}{You see a strong man in an apron. Apparently, he owns this place.}
{101}{}{你看到一个穿着围裙的强壮男人。显然，他拥有这个地方。 -- You see a strong man in an apron. Apparently, he owns this place.}
### {102}{}{So, I won't serve you while this armor is in the bar. Is that clear?}
{102}{}{所以，当这件盔甲在酒吧的时候，我不会为你服务。清楚吗？ -- So, I won't serve you while this armor is in the bar. Is that clear?}
### {103}{}{Sorry, but no guns in the bar.}
{103}{}{对不起，酒吧里没有枪。 -- Sorry, but no guns in the bar.}

#The first dialog
### {200}{}{(Approaching the bar, you notice the wariness in the eyes of the bartender and the surrounding visitors). What do you want?}
{200}{}{（走近酒吧，你会注意到酒保和周围游客眼中的谨慎）。你想要什么？ -- (Approaching the bar, you notice the wariness in the eyes of the bartender and the surrounding visitors). What do you want?}
### {201}{}{Please, empty coffee and a bun with sweet syrup for me.}
{201}{}{请给我空咖啡和一个甜糖浆面包。 -- Please, empty coffee and a bun with sweet syrup for me.}
### {202}{}{(the alertness of others is replaced by bewilderment and laughter) I don't have anything like that. Do you really not understand where you are?}
{202}{}{（其他人的警觉被困惑和笑声所取代）我没有那样的经历。你真的不明白自己在哪里吗？ -- (the alertness of others is replaced by bewilderment and laughter) I don't have anything like that. Do you really not understand where you are?}
### {203}{}{Well then I want to know more about this place.}
{203}{}{那么我想了解更多关于这个地方的信息。 -- Well then I want to know more about this place.}
### {204}{}{I just wanted to take a look. Interesting place you have.}
{204}{}{我只是想看看。你有一个有趣的地方。 -- I just wanted to take a look. Interesting place you have.}
### {205}{}{ (raises one eyebrow, then returns to his daily business, cleaning the bar from some stains) It's a bar. I hope you know what "drinking establishment" means.}
{205}{}{（扬起一条眉毛，然后回到他的日常事务中，清理酒吧里的污渍）这是一家酒吧。我希望你知道“饮酒场所”是什么意思。 --  (raises one eyebrow, then returns to his daily business, cleaning the bar from some stains) It's a bar. I hope you know what "drinking establishment" means.}
### {206}{}{Then I would like to rest here.}
{206}{}{那么我想在这里休息。 -- Then I would like to rest here.}
### {207}{}{I'm chasing a slave convoy.}
{207}{}{我在追捕一支奴隶车队。 -- I'm chasing a slave convoy.}
### {208}{}{(visitors fall silent and turn tensely in your direction) A slave convoy? No. There were no such people here.}
{208}{}{（来访者陷入沉默，紧张地转向你的方向）奴隶车队？没有。这里没有这样的人。 -- (visitors fall silent and turn tensely in your direction) A slave convoy? No. There were no such people here.}
### {209}{}{Hmm. I think I'm going to stay here a little longer.}
{209}{}{嗯。我想我会在这里多呆一会儿。 -- Hmm. I think I'm going to stay here a little longer.}

#Repeat dialog
### {210}{}{Yes?}
{210}{}{对 -- Yes?}
### {211}{}{Be there.}
{211}{}{在那里。 -- Be there.}

#Pocket trash
### {220}{}{There is nothing easier. But do you have something to pay with?}
{220}{}{没有什么比这更容易的了。但是你有什么东西可以付钱吗？ -- There is nothing easier. But do you have something to pay with?}
### {221}{}{Listen, I've got a lot of trash in my pockets here. Take a look, which of these can be useful?}
{221}{}{听着，我口袋里有很多垃圾。看看，其中哪些有用？ -- Listen, I've got a lot of trash in my pockets here. Take a look, which of these can be useful?}
### {222}{}{Wait a minute, I'm rummaging in my pockets...}
{222}{}{等一下，我在口袋里翻找。。。 -- Wait a minute, I'm rummaging in my pockets...}
### {223}{}{(you dump pocket garbage on the counter, the bartender is perplexed sorting through this stuff) If I had such pockets, I would have become rich a long time ago. Look, there's a pre-war bill here, a couple of caps and a cartridge. With all this you can buy... a whole tail from a fried iguana, ha ha!}
{223}{}{（你把口袋里的垃圾倒在柜台上，酒保在整理这些东西时很困惑）如果我有这样的口袋，我早就发财了。看，这里有一张战前账单，几顶帽子和一个子弹。有了这些，你可以买到。。。炸鬣蜥的整条尾巴，哈哈！ -- (you dump pocket garbage on the counter, the bartender is perplexed sorting through this stuff) If I had such pockets, I would have become rich a long time ago. Look, there's a pre-war bill here, a couple of caps and a cartridge. With all this you can buy... a whole tail from a fried iguana, ha ha!}
### {224}{}{Ugh, finally, at least some benefit from this garbage.}
{224}{}{啊，最后，至少从这些垃圾中得到了一些好处。 -- Ugh, finally, at least some benefit from this garbage.}

# Chris from the Villa
### {230}{}{Did a guy from my area pass by here? His name is Chris.}
{230}{}{我住的地方有人经过这里吗？他的名字叫克里斯。 -- Did a guy from my area pass by here? His name is Chris.}
### {231}{}{By the way. There was a guy who passed by, wasn't he from your area? His name was Chris.}
{231}{}{顺便说一句有一个人路过，他不是你们地区的人吗？他的名字叫克里斯。 -- By the way. There was a guy who passed by, wasn't he from your area? His name was Chris.}
### {232}{}{Yes, he was. Where did he go?}
{232}{}{是的，他是。他去哪儿了？ -- Yes, he was. Where did he go?}
### {233}{}{He left with a caravan, but he doesn't know where he's going.}
{233}{}{他带着一辆大篷车离开了，但他不知道要去哪里。 -- He left with a caravan, but he doesn't know where he's going.}
### {234}{}{Great. Looks like I won't hear from him again.}
{234}{}{太棒了看来我不会再收到他的消息了。 -- Great. Looks like I won't hear from him again.}
### {235}{}{Chris? I don't know that.}
{235}{}{克里斯？我不知道。 -- Chris? I don't know that.}
### {236}{}{Ah, well, then I'm sorry.}
{236}{}{啊，那么我很抱歉。 -- Ah, well, then I'm sorry.}

### {240}{}{Hmm. You look like an inveterate brawler.}
{240}{}{嗯。你看起来像个老爱打架的人。 -- Hmm. You look like an inveterate brawler.}
### {1240}{}{Hmm. You look like an inveterate rebel.}
{1240}{}{嗯。你看起来像一个根深蒂固的反叛者。 -- Hmm. You look like an inveterate rebel.}
### {241}{}{Are you sure?}
{241}{}{你确定吗？ -- Are you sure?}
### {242}{}{I am sure. I hope you're not going to make trouble for me?}
{242}{}{我确信。我希望你不会给我添麻烦？ -- I am sure. I hope you're not going to make trouble for me?}
### {243}{}{No, no problem, sir. I'm a regular visitor.}
{243}{}{不，没问题，先生。我是常客。 -- No, no problem, sir. I'm a regular visitor.}
### {1243}{}{No, no problem, sir. I'm an ordinary visitor.}
{1243}{}{不，没问题，先生。我是一个普通的访客。 -- No, no problem, sir. I'm an ordinary visitor.}
### {244}{}{And it seems to me that bars were invented just for fights.}
{244}{}{在我看来，酒吧的发明只是为了打架。 -- And it seems to me that bars were invented just for fights.}
### {245}{}{Then remember a simple rule. If someone decides to make a scandal here, he will immediately be on the street and will not come back.}
{245}{}{然后记住一条简单的规则。如果有人决定在这里制造丑闻，他将立即流落街头，再也不会回来了。 -- Then remember a simple rule. If someone decides to make a scandal here, he will immediately be on the street and will not come back.}
### {246}{}{I understand. No problem, sir.}
{246}{}{我理解。没问题，先生。 -- I understand. No problem, sir.}
### {247}{}{Don't tell me. Otherwise I'll get angry.}
{247}{}{别告诉我，否则我会生气的。 -- Don't tell me. Otherwise I'll get angry.}

#About the bar
### {250}{}{What drinks do you sell?}
{250}{}{你们卖什么饮料？ -- What drinks do you sell?}
### {251}{}{Watch and choose. This is the best alcohol you can find in our area.}
{251}{}{观看并选择。这是我们地区最好的酒。 -- Watch and choose. This is the best alcohol you can find in our area.}
### {252}{}{Let me think.}
{252}{}{让我想想。 -- Let me think.}

### {253}{}{So all this is firewater? I should have warned you right away!}
{253}{}{所以这一切都是消防水？我应该马上警告你！ -- So all this is firewater? I should have warned you right away!}
### {254}{}{It looks like you're from a place where no one has ever heard of bars. It's hard to imagine what will happen to you after a couple of sips. Still want to try it?}
{254}{}{看起来你来自一个从未听说过酒吧的地方。很难想象你喝了几口之后会发生什么。还想试试吗？ -- It looks like you're from a place where no one has ever heard of bars. It's hard to imagine what will happen to you after a couple of sips. Still want to try it?}
### {255}{}{Wow, I've never seen so many hot drinks before!}
{255}{}{哇，我从来没有见过这么多热饮！ -- Wow, I've never seen so many hot drinks before!}
### {1255}{}{Wow, I've never met so many hot drinks before!}
{1255}{}{哇，我以前从未见过这么多热饮！ -- Wow, I've never met so many hot drinks before!}
### {256}{}{Then congratulations on joining civilization. So what will you order?}
{256}{}{然后祝贺你加入文明。那么你要点什么？ -- Then congratulations on joining civilization. So what will you order?}
### {257}{}{Where did you get this alcohol from?}
{257}{}{你从哪里弄来的酒？ -- Where did you get this alcohol from?}
### {258}{}{Some are brought by caravans, and some are brought by scavengers. All this is missing. I was thinking of starting my own production, but the business stopped giving the necessary income to recoup the raw materials.}
{258}{}{有些是大篷车带来的，有些是拾荒者带来的。所有这些都不见了。我本想开始自己的生产，但公司停止提供必要的收入来收回原材料。 -- Some are brought by caravans, and some are brought by scavengers. All this is missing. I was thinking of starting my own production, but the business stopped giving the necessary income to recoup the raw materials.}
### {259}{}{I see.}
{259}{}{我明白了。 -- I see.}

### {260}{}{Any hot drinks that you can get in these parts.}
{260}{}{你能在这些地方买到的任何热饮。 -- Any hot drinks that you can get in these parts.}
### {261}{}{Why are you paying with caps here? We usually sell something *useful*.}
{261}{}{你为什么在这里用上限付款？我们通常卖一些有用的东西。 -- Why are you paying with caps here? We usually sell something *useful*.}
### {262}{}{Ah, you're from the wasteland. I don't know the whole story myself, but in big cities they came up with the idea of using caps as currency. It's like money before the Great War... You don't know anything about money either? Well... In general, this is all for exchange.}
{262}{}{啊，你来自荒原。我自己不知道整个故事，但在大城市，他们想出了用上限作为货币的主意。这就像大战前的钱。。。你对钱也一无所知？好总的来说，这都是为了交换。 -- Ah, you're from the wasteland. I don't know the whole story myself, but in big cities they came up with the idea of using caps as currency. It's like money before the Great War... You don't know anything about money either? Well... In general, this is all for exchange.}
### {263}{}{[Next]}
{263}{}{[下一个 -- Next]}
### {264}{}{However, the bottlecaps have taken root only in large cities, and in the wastelands they are rarely used.}
{264}{}{然而，瓶装水只在大城市扎根，在荒地上很少使用。 -- However, the bottlecaps have taken root only in large cities, and in the wastelands they are rarely used.}
### {265}{}{A curious idea.}
{265}{}{一个奇怪的想法。 -- A curious idea.}
### {266}{}{And what kind of assholes thought of that?}
{266}{}{这是什么混蛋的想法？ -- And what kind of assholes thought of that?}

### {270}{}{Hey, where did you get this flour?}
{270}{}{嘿，你从哪里弄来的面粉？ -- Hey, where did you get this flour?}
### {271}{}{A couple of strangers sold it on the cheap. Do you want to buy?}
{271}{}{几个陌生人把它廉价卖掉了。你想买吗？ -- A couple of strangers sold it on the cheap. Do you want to buy?}
### {272}{}{This flour was stolen from the Villa by looters. You're selling stolen goods!}
{272}{}{这些面粉是抢劫者从别墅里偷来的。你在卖赃物！ -- This flour was stolen from the Villa by looters. You're selling stolen goods!}
### {273}{}{Maybe so, but I honestly purchased this product.}
{273}{}{也许是这样，但我确实购买了这款产品。 -- Maybe so, but I honestly purchased this product.}
### {274}{}{[Next]}
{274}{}{[下一个 -- Next]}
### {275}{}{Now listen to me. You're a new person here and you don't deserve respect yet. If you dig around, you'll find yourself outside the door. This is at best. So, will you calm down? That's the same.}
{275}{}{现在听我说，你是一个新人，你还不值得尊重。如果你四处挖掘，你会发现自己在门外。这充其量也是。那么，你能冷静下来吗？这是一样的。 -- Now listen to me. You're a new person here and you don't deserve respect yet. If you dig around, you'll find yourself outside the door. This is at best. So, will you calm down? That's the same.}
### {276}{}{Not angry. I'm not to blame for your tragedy.}
{276}{}{不生气。你的悲剧不怪我。 -- Not angry. I'm not to blame for your tragedy.}
### {277}{}{Now you're on my blacklist, huckster.}
{277}{}{现在你在我的黑名单上，小贩。 -- Now you're on my blacklist, huckster.}
### {278}{}{Okay. I forgive you this time.}
{278}{}{可以这次我原谅你。 -- Okay. I forgive you this time.}

### {280}{}{Get a drink for everyone here. I }
{280}{}{给这里的每个人喝一杯。我 -- Get a drink for everyone here. I }
### {281}{}{ from the Villa. And I'm buying.}
{281}{}{别墅。我在买。 --  from the Villa. And I'm buying.}
### {282}{}{Do you want to earn a good reputation among scavengers? It would be like that right away. But it will cost you 50 caps.}
{282}{}{你想在拾荒者中赢得好名声吗？马上就会变成那样。但这将花费你50场比赛。 -- Do you want to earn a good reputation among scavengers? It would be like that right away. But it will cost you 50 caps.}
### {283}{}{No problem, here are the bottlecaps.}
{283}{}{没问题，瓶子在这儿。 -- No problem, here are the bottlecaps.}
### {284}{}{So many caps for all these beggars? So, I'm leaving here.}
{284}{}{这么多帽子给这些乞丐？所以，我要离开这里。 -- So many caps for all these beggars? So, I'm leaving here.}
### {285}{}{I can't afford it right now. Another time.}
{285}{}{我现在买不起。下次 -- I can't afford it right now. Another time.}
### {286}{}{And you're having trouble counting cash, right?}
{286}{}{你数现金有困难，对吧？ -- And you're having trouble counting cash, right?}
### {287}{}{...}
{287}{}{。。。 -- ...}
### {288}{}{Hey, guys! A newcomer from the wasteland wishes to introduce himself. It's at his expense.}
{288}{}{嘿，伙计们！一位来自荒原的新来者希望自我介绍。这是以他为代价的。 -- Hey, guys! A newcomer from the wasteland wishes to introduce himself. It's at his expense.}
### {1288}{}{Hey, guys! A stranger from the wasteland wants to introduce herself. It's at her expense.}
{1288}{}{嘿，伙计们！一个来自荒原的陌生人想自我介绍。这是以她为代价的。 -- Hey, guys! A stranger from the wasteland wants to introduce herself. It's at her expense.}
### {289}{}{Stretch out the fun, guys!}
{289}{}{尽情享受吧，伙计们！ -- Stretch out the fun, guys!}

### {290}{}{Hi. We're celebrating the extermination of Jackals here. These savages caused problems for scavengers and travelers, now it will be easier without them.}
{290}{}{你好我们在这里庆祝灭绝豺狼。这些野蛮人给拾荒者和旅行者带来了问题，现在没有他们会更容易。 -- Hi. We're celebrating the extermination of Jackals here. These savages caused problems for scavengers and travelers, now it will be easier without them.}
### {291}{}{Yes, they fought like wild dogs.}
{291}{}{是的，他们像野狗一样战斗。 -- Yes, they fought like wild dogs.}
### {292}{}{Are you trying to tell me that you're involved in this?}
{292}{}{你是想告诉我你和这件事有牵连吗？ -- Are you trying to tell me that you're involved in this?}
### {1292}{}{Do you really want to say that you are involved in this?}
{1292}{}{你真的想说你参与了这件事吗？ -- Do you really want to say that you are involved in this?}
### {293}{}{We went camping with your people. The gatekeeper knows about it.}
{293}{}{我们和你们的人一起去露营了。看门人知道这件事。 -- We went camping with your people. The gatekeeper knows about it.}
### {294}{}{Damn it, is it true? For the sake of such a case, I'll buy you a drink on the house. Thanks, buddy.}
{294}{}{该死，这是真的吗？为了这个案子，我请你喝一杯。谢谢，伙计。 -- Damn it, is it true? For the sake of such a case, I'll buy you a drink on the house. Thanks, buddy.}
### {295}{}{Please.}
{295}{}{请 -- Please.}
### {296}{}{I told the rangers, and they exterminated the tribe.}
{296}{}{我告诉了护林员，他们消灭了这个部落。 -- I told the rangers, and they exterminated the tribe.}
### {1296}{}{I told the rangers, and they exterminated the tribe.}
{1296}{}{我告诉了护林员，他们消灭了这个部落。 -- I told the rangers, and they exterminated the tribe.}
### {297}{}{Well, well. In general, whoever did this did us a great favor.}
{297}{}{嗯，嗯。总的来说，不管是谁干的，都帮了我们很大的忙。 -- Well, well. In general, whoever did this did us a great favor.}
### {298}{}{Uh, so celebrate, guys. And my exploits are waiting in other places.}
{298}{}{伙计们，庆祝一下。我的功绩还在其他地方等待着。 -- Uh, so celebrate, guys. And my exploits are waiting in other places.}
### {299}{}{Yes, just rumors.}
{299}{}{是的，只是谣言。 -- Yes, just rumors.}

### {300}{}{Can you tell me about this city?}
{300}{}{你能告诉我这个城市的情况吗？ -- Can you tell me about this city?}
### {301}{}{What do you want to know?}
{301}{}{你想知道什么？ -- What do you want to know?}
### {302}{}{Nothing else.}
{302}{}{没有别的。 -- Nothing else.}
### {303}{}{You either order something, or get others.}
{303}{}{你要么点点什么，要么买其他的。 -- You either order something, or get others.}
### {304}{}{Why is everyone squinting at me?}
{304}{}{为什么每个人都斜视我？ -- Why is everyone squinting at me?}
### {305}{}{Uh, okay. The hint is understood.}
{305}{}{好吧。提示已被理解。 -- Uh, okay. The hint is understood.}
### {306}{}{Don't be rude to me, bartender.}
{306}{}{别对我无礼，酒保。 -- Don't be rude to me, bartender.}
### {307}{}{Why don't you ask them about it?}
{307}{}{你为什么不问问他们呢？ -- Why don't you ask them about it?}
### {308}{}{What's going on here anyway?}
{308}{}{这里到底发生了什么？ -- What's going on here anyway?}
### {309}{}{Nothing special. The city is impoverished, and no one knows what to do about it.}
{309}{}{没什么特别的。这个城市很穷，没有人知道该怎么办。 -- Nothing special. The city is impoverished, and no one knows what to do about it.}
### {310}{}{The good news is that the cartel has finally launched one of the factories. It will breathe life into a dying city.}
{310}{}{好消息是，卡特尔终于开办了其中一家工厂。它将为一座垂死的城市注入生命。 -- The good news is that the cartel has finally launched one of the factories. It will breathe life into a dying city.}
### {311}{}{Why do you live in such terrible huts?}
{311}{}{你为什么住在这么糟糕的小屋里？ -- Why do you live in such terrible huts?}
### {312}{}{And you find better houses among the local ruins.}
{312}{}{你可以在当地的废墟中找到更好的房子。 -- And you find better houses among the local ruins.}
### {313}{}{I have no more questions about the city.}
{313}{}{我对这座城市没有更多的疑问了。 -- I have no more questions about the city.}

### {320}{}{If you're going to get rowdy, then go outside. I don't need drunken brawls here.}
{320}{}{如果你想变得吵闹，那就到外面去。我不需要在这里醉酒斗殴。 -- If you're going to get rowdy, then go outside. I don't need drunken brawls here.}
### {321}{}{He was looking for it himself.}
{321}{}{他自己在找。 -- He was looking for it himself.}
### {322}{}{I don't care which one of you started the fight. Just watch yourself and don't let go of your hands while you're here.}
{322}{}{我不在乎你们谁挑起了这场争斗。你在这里的时候要注意自己，不要松开你的手。 -- I don't care which one of you started the fight. Just watch yourself and don't let go of your hands while you're here.}
### {323}{}{Don't worry, it won't happen again.}
{323}{}{别担心，这种事不会再发生了。 -- Don't worry, it won't happen again.}
### {324}{}{Yes, in this hole, only drunken fights can entertain.}
{324}{}{是的，在这个洞里，只有酒后打架才能娱乐。 -- Yes, in this hole, only drunken fights can entertain.}

#Slave convoy
### {330}{}{I'm chasing a slave convoy. What do you know about it?}
{330}{}{我在追捕一支奴隶车队。你对此了解多少？ -- I'm chasing a slave convoy. What do you know about it?}
### {331}{}{I don't know anything. How about a glass of something hot?}
{331}{}{我什么都不知道。来杯热的怎么样？ -- I don't know anything. How about a glass of something hot?}
### {332}{}{Okay, forget it, I'll ask someone else.}
{332}{}{好吧，算了，我会问别人的。 -- Okay, forget it, I'll ask someone else.}
### {333}{}{You should know.}
{333}{}{你应该知道。 -- You should know.}
### {334}{}{Look, I don't want any trouble with Mr. Kogan. He did business with these slaveholders. So talk to him.}
{334}{}{听着，我不想和Kogan先生有任何麻烦。他和这些奴隶主做生意。所以和他谈谈。 -- Look, I don't want any trouble with Mr. Kogan. He did business with these slaveholders. So talk to him.}
### {335}{}{Maybe later. I want to sit here a little longer.}
{335}{}{也许以后吧。我想在这里多坐一会儿。 -- Maybe later. I want to sit here a little longer.}
### {336}{}{Okay, I'll go to him.}
{336}{}{好吧，我去找他。 -- Okay, I'll go to him.}
### {337}{}{Don't worry, Kogan and I don't have any friction.}
{337}{}{别担心，Kogan和我没有任何摩擦。 -- Don't worry, Kogan and I don't have any friction.}
### {338}{}{Tell it to someone else. But don't involve me.}
{338}{}{告诉别人。但不要牵扯到我。 -- Tell it to someone else. But don't involve me.}
### {339}{}{Looks like you're all tied up here.}
{339}{}{看来你们都被绑在这里了。 -- Looks like you're all tied up here.}
### {340}{}{Really? You know, there are rumors about you... not particularly flattering.}
{340}{}{真正地你知道，有传言说你。。。不是特别讨人喜欢。 -- Really? You know, there are rumors about you... not particularly flattering.}
### {341}{}{Seriously? I didn't notice something.}
{341}{}{认真地我没有注意到什么。 -- Seriously? I didn't notice something.}
### {1341}{}{Seriously? I didn't notice something.}
{1341}{}{认真地我没有注意到什么。 -- Seriously? I didn't notice something.}
### {342}{}{If you don't tell me, I'll blow up this bar like the mug of that harasser.}
{342}{}{如果你不告诉我，我会像那个骚扰者一样炸毁这家酒吧。 -- If you don't tell me, I'll blow up this bar like the mug of that harasser.}
### {343}{}{Okay, okay. No need to deliver anything. Agreed?}
{343}{}{好吧，好吧。无需交付任何东西。同意吗？ -- Okay, okay. No need to deliver anything. Agreed?}
### {344}{}{Then be a good girl and tell me everything you know.}
{344}{}{那就做个好女孩，告诉我你所知道的一切。 -- Then be a good girl and tell me everything you know.}

### {350}{}{Yes, they stopped by on their way back to the city. It's been a long time since I've had such an influx of customers.}
{350}{}{是的，他们在回城的路上顺道经过。我已经很久没有这么多顾客了。 -- Yes, they stopped by on their way back to the city. It's been a long time since I've had such an influx of customers.}
### {351}{}{It's good that your business has developed. But I need to know where the convoy went.}
{351}{}{你的生意发展了，这很好。但我需要知道车队去了哪里。 -- It's good that your business has developed. But I need to know where the convoy went.}
### {352}{}{I don't care about your bar. Tell me where they went.}
{352}{}{我不在乎你的酒吧。告诉我他们去了哪里。 -- I don't care about your bar. Tell me where they went.}
### {353}{}{Wait a minute, do you mean to say that the city has only benefited from this story with slaves?}
{353}{}{等等，你的意思是说这座城市只从这个有奴隶的故事中受益吗？ -- Wait a minute, do you mean to say that the city has only benefited from this story with slaves?}
### {354}{}{The motel guy and I made good money, and Mr. Kogan signed a couple of new contracts. Even ordinary scavengers found a use. These slavers seemed to breathe life into our dump. At least for a little while.}
{354}{}{我和那个汽车旅馆老板赚了不少钱，Kogan先生签了几份新合同。即使是普通的拾荒者也找到了用武之地。这些奴隶贩子似乎给我们的垃圾场注入了活力。至少有一段时间。 -- The motel guy and I made good money, and Mr. Kogan signed a couple of new contracts. Even ordinary scavengers found a use. These slavers seemed to breathe life into our dump. At least for a little while.}
### {355}{}{The convoy went east to the city of Flagstaff. By the way, Mr. Kogan did business with the slave owners. Now that he's dead, you can study his records in the garage, if that's so important to you.}
{355}{}{车队向东驶向弗拉格斯塔夫市。顺便说一句，Kogan先生和奴隶主做生意。既然他死了，你可以在车库里研究他的记录，如果这对你很重要的话。 -- The convoy went east to the city of Flagstaff. By the way, Mr. Kogan did business with the slave owners. Now that he's dead, you can study his records in the garage, if that's so important to you.}
### {356}{}{The convoy went east to the city of Flagstaff. Go along the 40th federal highway, you won't miss. The way there should take about a week.}
{356}{}{车队向东驶向弗拉格斯塔夫市。沿着40号联邦高速公路走，你不会错过的。去那里的路大约需要一周的时间。 -- The convoy went east to the city of Flagstaff. Go along the 40th federal highway, you won't miss. The way there should take about a week.}
### {357}{}{Thanks for the information. I have to go.}
{357}{}{谢谢你提供的信息。我得走了。 -- Thanks for the information. I have to go.}
### {358}{}{Now I know that you are also to blame for the raid. And I'll remember that.}
{358}{}{现在我知道你也应该为这次突袭负责。我会记住的。 -- Now I know that you are also to blame for the raid. And I'll remember that.}

### {360}{}{What's the problem with getting alcohol?}
{360}{}{喝酒有什么问题？ -- What's the problem with getting alcohol?}
### {361}{}{Previously, tequila and beer were brought from the south. And now this route is closed. I don't mind buying booze from Flagstaff at an increased price, but we don't have a permanent caravan even with this neighboring town. I need at least a courier for negotiations.}
{361}{}{以前，龙舌兰酒和啤酒是从南方带来的。现在这条路线被关闭了。我不介意以更高的价格从弗拉格斯塔夫买酒，但即使在这个邻近的城镇，我们也没有永久的房车。我至少需要一个谈判信使。 -- Previously, tequila and beer were brought from the south. And now this route is closed. I don't mind buying booze from Flagstaff at an increased price, but we don't have a permanent caravan even with this neighboring town. I need at least a courier for negotiations.}
### {362}{}{I'm just going there. I can talk to someone about the supply of alcohol.}
{362}{}{我只是去那里。我可以和某人谈谈酒精供应的问题。 -- I'm just going there. I can talk to someone about the supply of alcohol.}
### {363}{}{Things are really bad for you. I hope you'll figure it out somehow.}
{363}{}{事情对你来说真的很糟糕。我希望你能想出办法。 -- Things are really bad for you. I hope you'll figure it out somehow.}
### {364}{}{Try. Otherwise I can't even send a letter there. Find a local bartender and convince him to send drinks here.}
{364}{}{尝试否则我甚至不能在那里寄信。找一个当地的酒保，说服他把饮料送到这里。 -- Try. Otherwise I can't even send a letter there. Find a local bartender and convince him to send drinks here.}
### {365}{}{Agreed. I'll find him and come back with an answer.}
{365}{}{同意。我会找到他并给他答复的。 -- Agreed. I'll find him and come back with an answer.}
### {366}{}{Bye.}
{366}{}{再见 -- Bye.}
### {367}{}{The bartender from Flagstaff agrees to supply drinks.}
{367}{}{弗拉格斯塔夫的酒保同意供应饮料。 -- The bartender from Flagstaff agrees to supply drinks.}
### {368}{}{Great job! Let alcohol go up in price, but my shelves will stop being so empty.}
{368}{}{干得好！让酒精涨价吧，但我的货架将不再那么空了。 -- Great job! Let alcohol go up in price, but my shelves will stop being so empty.}
### {369}{}{Ahem. You're not thinking of leaving my job unpaid, are you?}
{369}{}{嗯。你没有想过让我无薪离职，是吗？ -- Ahem. You're not thinking of leaving my job unpaid, are you?}
### {370}{}{I'm happy for you, my friend. Now the whole city will cheer up.}
{370}{}{我为你感到高兴，我的朋友。现在整个城市都将振作起来。 -- I'm happy for you, my friend. Now the whole city will cheer up.}
### {371}{}{Here are 100 caps for the courier service and my old gun. I know it's not much, but I'm expecting big expenses!}
{371}{}{这是快递服务的100顶帽子和我的旧枪。我知道不多，但我预计会有大笔开支！ -- Here are 100 caps for the courier service and my old gun. I know it's not much, but I'm expecting big expenses!}
### {372}{}{I've never had to endure such a scam before. Goodbye, miser.}
{372}{}{我以前从未忍受过这样的骗局。再见，吝啬鬼。 -- I've never had to endure such a scam before. Goodbye, miser.}
### {373}{}{Thank you, that's enough. And I'll sell the gun in the next town. Happily.}
{373}{}{谢谢，够了。我会在下一个城镇卖掉枪。高兴地 -- Thank you, that's enough. And I'll sell the gun in the next town. Happily.}
### {374}{}{Agreed. But for now, I'll stay here a little longer.}
{374}{}{同意。但现在，我会在这里多呆一段时间。 -- Agreed. But for now, I'll stay here a little longer.}

#Trade Route Quest
### {400}{}{Do you have anything edible?}
{400}{}{你有吃的吗？ -- Do you have anything edible?}
### {401}{}{Something like meat? There are problems with this.}
{401}{}{像肉一样的东西？这是有问题的。 -- Something like meat? There are problems with this.}
### {402}{}{Why?}
{402}{}{为什么？ -- Why?}
### {403}{}{Trade turnover has fallen recently. Fewer and fewer caravans with provisions come into the city, because we have nothing to trade with. We have to survive on our own. Someone hunts coyotes, someone catches lizards, and someone unsuccessfully tries to grow crops.}
{403}{}{最近贸易额下降了。越来越少的大篷车带着食物进城，因为我们没有什么可交易的。我们必须靠自己生存。有人猎杀郊狼，有人抓蜥蜴，还有人试图种植作物却没有成功。 -- Trade turnover has fallen recently. Fewer and fewer caravans with provisions come into the city, because we have nothing to trade with. We have to survive on our own. Someone hunts coyotes, someone catches lizards, and someone unsuccessfully tries to grow crops.}
### {404}{}{Hunting? I would have participated.}
{404}{}{狩猎？我会参加的。 -- Hunting? I would have participated.}
### {1404}{}{Hunting? I would have participated.}
{1404}{}{狩猎？我会参加的。 -- Hunting? I would have participated.}
### {405}{}{Is there really nothing you can do?}
{405}{}{你真的无能为力吗？ -- Is there really nothing you can do?}
### {406}{}{And that's all you can do?}
{406}{}{这就是你能做的吗？ -- And that's all you can do?}
### {407}{}{Well, the gatekeeper said that wild Brahmins were spotted in the desert. Some scavengers are going to find them. You can join the hunt too.}
{407}{}{看门人说在沙漠里发现了野生婆罗门。一些拾荒者会找到它们。你也可以参加狩猎。 -- Well, the gatekeeper said that wild Brahmins were spotted in the desert. Some scavengers are going to find them. You can join the hunt too.}
### {408}{}{Interesting. I'll talk to this gatekeeper first. See you again.}
{408}{}{有趣的我先和这个看门人谈谈。再见。 -- Interesting. I'll talk to this gatekeeper first. See you again.}
### {409}{}{It's not in my line. Be there.}
{409}{}{这不在我的队伍里。在那里。 -- It's not in my line. Be there.}

### {410}{}{The gatekeeper says, did you also participate in the search for a brahmin?}
{410}{}{看门人说，你也参与了寻找婆罗门的活动吗？ -- The gatekeeper says, did you also participate in the search for a brahmin?}
### {1410}{}{The gatekeeper says, did you also participate in the search for a Brahmin?}
{1410}{}{看门人说，你也参与了寻找婆罗门的活动吗？ -- The gatekeeper says, did you also participate in the search for a Brahmin?}
### {411}{}{Yes, there was a case.}
{411}{}{是的，有一个案例。 -- Yes, there was a case.}
### {412}{}{Maybe so. Do you have something against it?}
{412}{}{也许是这样。你反对吗？ -- Maybe so. Do you have something against it?}
### {413}{}{Then explain what the hell happened there and where are our people?!}
{413}{}{然后解释一下那里到底发生了什么，我们的人在哪里？！ -- Then explain what the hell happened there and where are our people?!}
### {414}{}{Your people, uh, fell to a wild brahmin. He was stronger than anyone could have imagined.}
{414}{}{你们的人民，呃，堕落到一个野蛮的婆罗门。他比任何人想象的都强壮。 -- Your people, uh, fell to a wild brahmin. He was stronger than anyone could have imagined.}
### {415}{}{Damn it. No meat, no people. Eh, it looks like the hungry season is waiting for us again...}
{415}{}{该死，没有肉，没有人。呃，看来饥饿的季节又在等着我们了。。。 -- Damn it. No meat, no people. Eh, it looks like the hungry season is waiting for us again...}
### {416}{}{Is it really that bad?}
{416}{}{真的那么糟糕吗？ -- Is it really that bad?}
### {417}{}{So you know what really happened there. You're not going to talk about it, are you?}
{417}{}{所以你知道那里到底发生了什么。你不会谈论它的，是吗？ -- So you know what really happened there. You're not going to talk about it, are you?}
### {418}{}{I? Nope. I won't.}
{418}{}{我没有。我不会的。 -- I? Nope. I won't.}
### {419}{}{Cut off my tongue if I tell you that you stole a tame brahmin.}
{419}{}{如果我告诉你你偷了一个驯服的婆罗门，请割断我的舌头。 -- Cut off my tongue if I tell you that you stole a tame brahmin.}
### {420}{}{OK. Here's your share of the total carcass. Thank you, you are saving us from hunger.}
{420}{}{好的，这是你的份额。谢谢你，你把我们从饥饿中拯救了出来。 -- OK. Here's your share of the total carcass. Thank you, you are saving us from hunger.}
### {421}{}{So are you having a hungry season?}
{421}{}{那么你正经历一个饥饿的季节吗？ -- So are you having a hungry season?}
### {422}{}{It turns out that you just ran away, leaving the others alone with the problem. Do you even know how much our guys had to endure there?}
{422}{}{事实证明，你只是逃跑了，让其他人独自处理这个问题。你知道我们的人在那里忍受了多少吗？ -- It turns out that you just ran away, leaving the others alone with the problem. Do you even know how much our guys had to endure there?}
### {1422}{}{So you just ran away. I left the others alone with the problem. Do you even know how much our guys had to endure there?}
{1422}{}{所以你就跑了。我让其他人单独处理这个问题。你知道我们的人在那里忍受了多少吗？ -- So you just ran away. I left the others alone with the problem. Do you even know how much our guys had to endure there?}
### {423}{}{Don't even ask.}
{423}{}{甚至不要问。 -- Don't even ask.}
### {424}{}{I guessed it. Don't think that such a thing is quickly forgotten in these parts. Especially in conditions of hungry time.}
{424}{}{我猜到了。不要以为这样的事情会在这些地方很快被遗忘。尤其是在饥饿的时候。 -- I guessed it. Don't think that such a thing is quickly forgotten in these parts. Especially in conditions of hungry time.}
### {425}{}{So you have a hungry season?}
{425}{}{所以你有一个饥饿的季节？ -- So you have a hungry season?}
### {426}{}{Because of you, we lost a whole carcass of pure meat! She could feed one person for a whole year!}
{426}{}{因为你，我们失去了一整具纯肉！她可以养活一个人一整年！ -- Because of you, we lost a whole carcass of pure meat! She could feed one person for a whole year!}
### {427}{}{I have some ideas in stock.}
{427}{}{我有一些想法。 -- I have some ideas in stock.}
### {428}{}{Really? Very good. Because otherwise we'll have to roast you instead of a brahmin. We have a hungry season here, there is not enough food for everyone.}
{428}{}{真正地很好。因为否则我们只能烤你而不是婆罗门。我们这里有一个饥饿的季节，没有足够的食物给每个人。 -- Really? Very good. Because otherwise we'll have to roast you instead of a brahmin. We have a hungry season here, there is not enough food for everyone.}
### {429}{}{Is it that bad?}
{429}{}{有那么糟糕吗？ -- Is it that bad?}

### {430}{}{Exactly. We used to trade with southern cities, exchanging parts for products. But not only do we now have almost nothing to trade with, they have also announced a boycott in San Brahmin. They don't sell their meat to anyone anymore.}
{430}{}{确切地我们过去常与南方城市进行贸易，用零件换取产品。但我们现在不仅几乎没有什么可交易的，他们还宣布在圣婆罗门抵制。他们不再把肉卖给任何人。 -- Exactly. We used to trade with southern cities, exchanging parts for products. But not only do we now have almost nothing to trade with, they have also announced a boycott in San Brahmin. They don't sell their meat to anyone anymore.}
### {431}{}{And nothing can be done?}
{431}{}{什么都做不了？ -- And nothing can be done?}
### {432}{}{I don't know. We don't have any more caravans. I can't even contact the merchants.}
{432}{}{我不知道。我们没有更多的大篷车了。我甚至连商家都联系不上。 -- I don't know. We don't have any more caravans. I can't even contact the merchants.}
### {433}{}{Looks like you have a problem here.}
{433}{}{看起来你这里有问题。 -- Looks like you have a problem here.}
### {434}{}{And another one. Listen, you're going to those parts, aren't you? If you find yourself nearby, let the merchant in the square know, maybe he will open our trade route.}
{434}{}{还有另一个。听着，你要去那些地方，不是吗？如果你发现自己在附近，让广场上的商人知道，也许他会开通我们的贸易路线。 -- And another one. Listen, you're going to those parts, aren't you? If you find yourself nearby, let the merchant in the square know, maybe he will open our trade route.}
### {435}{}{I doubt I'll ever be in those places.}
{435}{}{我怀疑我是否会去那些地方。 -- I doubt I'll ever be in those places.}
### {436}{}{Okay, I'll talk to him if I'm around.}
{436}{}{好吧，如果我在的话，我会和他谈谈。 -- Okay, I'll talk to him if I'm around.}
### {437}{}{I can do it.}
{437}{}{我能做到。 -- I can do it.}
### {438}{}{You'll be doing this a great favor. Find a merchant in the square in San Brahmin and persuade him to reopen the trade route.}
{438}{}{你会帮我一个很大的忙。在圣婆罗门的广场上找到一位商人，说服他重新开放贸易路线。 -- You'll be doing this a great favor. Find a merchant in the square in San Brahmin and persuade him to reopen the trade route.}

### {440}{}{So, have the caravans from the south returned?}
{440}{}{那么，南方的商队回来了吗？ -- So, have the caravans from the south returned?}
### {441}{}{Business is coming to life. Thanks to you, we are getting meat from the San Brahmin again. So hunger does not threaten the city. And the turnover of caps in the bar has also increased. Thanks! Here, take a hundred as a share of the deal.}
{441}{}{商业正在复苏。多亏了你，我们又从圣婆罗门那里得到了肉。因此，饥饿不会威胁到这座城市。酒吧里的帽子营业额也有所增加。谢谢在这里，拿一百作为交易的一部分。 -- Business is coming to life. Thanks to you, we are getting meat from the San Brahmin again. So hunger does not threaten the city. And the turnover of caps in the bar has also increased. Thanks! Here, take a hundred as a share of the deal.}
### {442}{}{You're welcome.}
{442}{}{不客气。 -- You're welcome.}
### {443}{}{The resumption of trade will increase the turnover of dried meat and caps in the bar.}
{443}{}{贸易的恢复将增加酒吧肉干和鸭舌帽的营业额。 -- The resumption of trade will increase the turnover of dried meat and caps in the bar.}
### {444}{}{There will be no caravans. San Brahmin made an alliance with the Rangers.}
{444}{}{不会有大篷车。圣婆罗门与游骑兵结盟。 -- There will be no caravans. San Brahmin made an alliance with the Rangers.}
### {445}{}{It's bad... The city will not last long on the meat of coyotes and iguanas.}
{445}{}{这很糟糕。。。这座城市靠郊狼和鬣蜥的肉撑不了多久。 -- It's bad... The city will not last long on the meat of coyotes and iguanas.}
### {446}{}{And what should we do now?}
{446}{}{我们现在该怎么办？ -- And what should we do now?}
### {447}{}{So now buy meat from the rangers.}
{447}{}{所以现在从护林员那里买肉。 -- So now buy meat from the rangers.}
### {448}{}{I can buy meat from the rangers. But it will be much more expensive. And I'm not at all happy about the prospect of walking under the heel of these guys. We have a pretty strained relationship with them in the Garage, you know. But it seems that there is no choice anymore.}
{448}{}{我可以从护林员那里买肉。但它会贵得多。我对被这些家伙踩在脚下的前景一点也不高兴。你知道，我们在车库里和他们的关系很紧张。但似乎已经别无选择了。 -- I can buy meat from the rangers. But it will be much more expensive. And I'm not at all happy about the prospect of walking under the heel of these guys. We have a pretty strained relationship with them in the Garage, you know. But it seems that there is no choice anymore.}
### {449}{}{It's better than nothing. I'll talk to someone on their territory.}
{449}{}{总比什么都没有好。我会和他们领地上的人谈谈。 -- It's better than nothing. I'll talk to someone on their territory.}
### {450}{}{It's better than nothing. Good luck.}
{450}{}{总比什么都没有好。祝你好运 -- It's better than nothing. Good luck.}
### {451}{}{Unfortunately, none of the locals will listen to me. This is already a passed stage.}
{451}{}{不幸的是，没有一个当地人会听我的。这已经是一个过时的阶段了。 -- Unfortunately, none of the locals will listen to me. This is already a passed stage.}
### {452}{}{I have some bad news. No one from Ranger territory wants to trade food with you.}
{452}{}{我有一些坏消息。流浪者地区没有人愿意和你交换食物。 -- I have some bad news. No one from Ranger territory wants to trade food with you.}
### {453}{}{I understand. Thanks for trying.}
{453}{}{我理解。谢谢你的尝试。 -- I understand. Thanks for trying.}
### {454}{}{Good luck. You're holding on here.}
{454}{}{祝你好运你坚持住了。 -- Good luck. You're holding on here.}
### {455}{}{Someone in Ranger territory has agreed to trade food with you.}
{455}{}{游骑兵领地的某个人同意和你交换食物。 -- Someone in Ranger territory has agreed to trade food with you.}
### {456}{}{Business is coming to life. Thanks to you, we are getting food again. So hunger does not threaten the city. But the boots of the rangers have already trampled the entrance to my establishment. Or maybe it's for the best? I don't know. In any case, thank you. Take a hundred as a share of the deal.}
{456}{}{商业正在复苏。多亏了你，我们又有饭吃了。因此，饥饿不会威胁到这座城市。但是护林员的靴子已经践踏了我的住所的入口。或者也许这是最好的？我不知道。不管怎样，谢谢你。拿一百作为交易的一部分。 -- Business is coming to life. Thanks to you, we are getting food again. So hunger does not threaten the city. But the boots of the rangers have already trampled the entrance to my establishment. Or maybe it's for the best? I don't know. In any case, thank you. Take a hundred as a share of the deal.}
### {457}{}{You're welcome.}
{457}{}{不客气。 -- You're welcome.}
### {458}{}{There will be no caravans. The tribe became angry at the outsiders after a series of murders.}
{458}{}{不会有大篷车。在一系列谋杀案发生后，部落对外来者感到愤怒。 -- There will be no caravans. The tribe became angry at the outsiders after a series of murders.}
