### {100}{}{Here is a sick scavenger.}
{100}{}{这是一个生病的拾荒者。 -- Here is a sick scavenger.}
### {101}{}{You see one of Trayvon's scavengers. He is suffering from the effects of some kind of illness.}
{101}{}{你看到一个Trayvon的拾荒者。他正遭受某种疾病的影响。 -- You see one of Trayvon's scavengers. He is suffering from the effects of some kind of illness.}
### {102}{}{You have successfully cured the scavenger's disease.}
{102}{}{你已经成功地治愈了清道夫病。 -- You have successfully cured the scavenger's disease.}
### {103}{}{You are unable to analyze the disease and even more so to cure a person without medication.}
{103}{}{你无法分析疾病，更无法在没有药物的情况下治愈一个人。 -- You are unable to analyze the disease and even more so to cure a person without medication.}
### {104}{}{This scavenger is suffering from the effects of radiation sickness. Your skills do not allow you to cure him without special medications.}
{104}{}{这个拾荒者正遭受辐射病的影响。你的技术不允许你在没有特殊药物的情况下治愈他。 -- This scavenger is suffering from the effects of radiation sickness. Your skills do not allow you to cure him without special medications.}

### {110}{}{*Cough-cough*}
{110}{}{*咳嗽* -- *Cough-cough*}
### {111}{}{I'm sorry, I'm not feeling well.}
{111}{}{对不起，我感觉不舒服。 -- I'm sorry, I'm not feeling well.}
### {112}{}{I got sick after another trip to the ruins.}
{112}{}{我又一次去废墟旅行后生病了。 -- I got sick after another trip to the ruins.}
### {113}{}{*hack* ...I'm sick, as you can see.}
{113}{}{*破解*。。。正如你所看到的，我病了。 -- *hack* ...I'm sick, as you can see.}
### {114}{}{...It's not contagious, don't worry.}
{114}{}{……它不会传染，别担心。 -- ...It's not contagious, don't worry.}

### {115}{}{Thank you for your help, I have already said goodbye to life.}
{115}{}{谢谢你的帮助，我已经告别了生活。 -- Thank you for your help, I have already said goodbye to life.}
### {116}{}{If it wasn't for you, I would have suffered until I was completely exhausted.}
{116}{}{如果不是你，我会痛苦到筋疲力尽。 -- If it wasn't for you, I would have suffered until I was completely exhausted.}
### {117}{}{There is no price for doctors like you.}
{117}{}{像你这样的医生是没有价格的。 -- There is no price for doctors like you.}
### {118}{}{I got sick after another foray into the ruins.}
{118}{}{我又一次闯入废墟后生病了。 -- I got sick after another foray into the ruins.}
### {119}{}{Are you looking for your people? They were taken east, that's all I know.}
{119}{}{你在找你的人吗？他们被带到了东部，我只知道这些。 -- Are you looking for your people? They were taken east, that's all I know.}

### {120}{}{Oh...}
{120}{}{哦 -- Oh...}
### {121}{}{*Cough-cough*}
{121}{}{*咳嗽* -- *Cough-cough*}
### {122}{}{*Hack*}
{122}{}{*哈克* -- *Hack*}
### {123}{}{Uv...}
{123}{}{Uv。。。 -- Uv...}
### {124}{}{*Groan*}
{124}{}{*Groan* -- *Groan*}
### {125}{}{Hr-r...}
{125}{}{小时-小时。。。 -- Hr-r...}
