### {100}{}{Here is a settler.}
{100}{}{这是一位定居者。 -- Here is a settler.}
### {101}{}{You see one of the few residents of Garage City.}
{101}{}{你可以看到车库城为数不多的居民之一。 -- You see one of the few residents of Garage City.}

### {110}{}{So you're here in passing? That's good.}
{110}{}{所以你是路过这里的？这很好。 -- So you're here in passing? That's good.}
### {111}{}{You'd better go. There is no place for new settlers here.}
{111}{}{你最好走。这里没有新移民的容身之地。 -- You'd better go. There is no place for new settlers here.}
### {112}{}{For the first time in a big city?}
{112}{}{第一次在大城市？ -- For the first time in a big city?}
### {113}{}{Garage City is a great place, you'll love it here.}
{113}{}{车库城是一个很棒的地方，你会喜欢这里的。 -- Garage City is a great place, you'll love it here.}
### {114}{}{Are you going to stay here?}
{114}{}{你打算留在这里吗？ -- Are you going to stay here?}
### {115}{}{We have our own rules here, peasant.}
{115}{}{我们这里有自己的规则，农民。 -- We have our own rules here, peasant.}
### {116}{}{I don't understand why people still go to this forgotten city.}
{116}{}{我不明白为什么人们仍然去这个被遗忘的城市。 -- I don't understand why people still go to this forgotten city.}

### {120}{}{Hi! How are you?}
{120}{}{你好你好吗 -- Hi! How are you?}
### {121}{}{Wow, what people. Are you here for a long time?}
{121}{}{哇，真是人啊。你在这里很长时间了吗？ -- Wow, what people. Are you here for a long time?}
### {122}{}{How is the harvest, amigo, on the rise?}
{122}{}{亲爱的，收成怎么样？ -- How is the harvest, amigo, on the rise?}
### {123}{}{Hello, amigo.}
{123}{}{你好，朋友。 -- Hello, amigo.}
### {124}{}{Sorry we didn't meet you very well.}
{124}{}{很抱歉，我们没有很好地认识你。 -- Sorry we didn't meet you very well.}
### {125}{}{We didn't know that the peasants of the Villa were so friendly.}
{125}{}{我们不知道别墅里的农民如此友好。 -- We didn't know that the peasants of the Villa were so friendly.}
### {126}{}{Do you need help?}
{126}{}{你需要帮助吗？ -- Do you need help?}

### {130}{}{Stay away from me.}
{130}{}{离我远点。 -- Stay away from me.}
### {131}{}{Dig in your garden beds, peasant, but don't come near me.}
{131}{}{挖你花园里的床，农民，但不要靠近我。 -- Dig in your garden beds, peasant, but don't come near me.}
### {132}{}{Tell your headman that he is a greedy and arrogant bastard.}
{132}{}{告诉你的校长他是个贪婪自大的混蛋。 -- Tell your headman that he is a greedy and arrogant bastard.}
### {133}{}{Your Villa has never been distinguished by good people.}
{133}{}{你的别墅从来没有受到过好人的尊敬。 -- Your Villa has never been distinguished by good people.}
### {134}{}{Are all the residents in your Villa as cunning and greedy?}
{134}{}{你别墅里的所有居民都是那么狡猾和贪婪吗？ -- Are all the residents in your Villa as cunning and greedy?}
### {135}{}{Now it is clear why the Villa set such high prices.}
{135}{}{现在很清楚为什么维拉开出这么高的价格了。 -- Now it is clear why the Villa set such high prices.}
### {136}{}{I'll tell you how it is. I was glad to see your relatives on their knees.}
{136}{}{我来告诉你情况如何。我很高兴看到你的亲戚跪下来。 -- I'll tell you how it is. I was glad to see your relatives on their knees.}
### {137}{}{When we were hungry, you raised prices.}
{137}{}{当我们饿的时候，你们提高了价格。 -- When we were hungry, you raised prices.}
### {138}{}{Fuck off, you dirty peasant.}
{138}{}{滚吧，你这个肮脏的农民。 -- Fuck off, you dirty peasant.}
### {139}{}{The villa got what it deserved.}
{139}{}{别墅得到了它应得的。 -- The villa got what it deserved.}
