### {100}{}{Here is a refugee.}
{100}{}{这是一个难民。 -- Here is a refugee.}
### {101}{}{You see one of the new arrivals.}
{101}{}{你看到一个新来的。 -- You see one of the new arrivals.}
### {102}{}{To feed a refugee, use food on him.}
{102}{}{要养活一个难民，就用食物喂他。 -- To feed a refugee, use food on him.}

#The first dialog
### {200}{}{ (a piercing wild look stared at you from under dirty curls) What do you want? What do you want? Eh?}
{200}{}{（从肮脏的卷发下，一种尖锐而狂野的目光盯着你）你想要什么？你想要什么？呃？ --  (a piercing wild look stared at you from under dirty curls) What do you want? What do you want? Eh?}
### {201}{}{Don't worry so much. I won't hurt you.}
{201}{}{别那么担心。我不会伤害你的。 -- Don't worry so much. I won't hurt you.}
### {202}{}{And you're not too trusting of strangers, right?}
{202}{}{你也不太信任陌生人，对吧？ -- And you're not too trusting of strangers, right?}
### {203}{}{What do you want? I haven't eaten for the second day and I'm being kicked out of this city. Give me something to eat or leave me alone.}
{203}{}{你想要什么？我已经第二天没吃东西了，我要被赶出这个城市了。给我点吃的，或者让我一个人呆着。 -- What do you want? I haven't eaten for the second day and I'm being kicked out of this city. Give me something to eat or leave me alone.}
### {204}{}{Okay, I'll look for something edible in my backpack.}
{204}{}{好的，我会在背包里找一些可食用的东西。 -- Okay, I'll look for something edible in my backpack.}
### {205}{}{Feed you? Go to hell, beggar!}
{205}{}{喂饱你？见鬼去吧，乞丐！ -- Feed you? Go to hell, beggar!}
### {206}{}{I will feed you with my fist so that it will not seem enough.}
{206}{}{我会用拳头喂你，这样看起来就不够了。 -- I will feed you with my fist so that it will not seem enough.}
### {207}{}{Rub it again - and you'll eat your own hand.}
{207}{}{再擦一次，你就会吃掉自己的手。 -- Rub it again - and you'll eat your own hand.}
### {208}{}{Stop! Don't touch me!}
{208}{}{停止别碰我！ -- Stop! Don't touch me!}
### {209}{}{Okay, calm down. I just want to ask a question.}
{209}{}{好吧，冷静下来。我只想问一个问题。 -- Okay, calm down. I just want to ask a question.}
### {210}{}{I won't if you answer my questions.}
{210}{}{如果你回答我的问题，我不会的。 -- I won't if you answer my questions.}
### {211}{}{Leave me alone.}
{211}{}{别管我。 -- Leave me alone.}
### {212}{}{Well, that's fine.}
{212}{}{好吧，没关系。 -- Well, that's fine.}
### {213}{}{So it was your group that went to the Rangers and turned off the path?}
{213}{}{所以是你的团队去了游骑兵队，然后离开了小路？ -- So it was your group that went to the Rangers and turned off the path?}

#Repeat dialog
### {220}{}{What do you want?}
{220}{}{你想要什么？ -- What do you want?}
### {221}{}{Bye.}
{221}{}{再见 -- Bye.}
### {222}{}{Thanks for the food. How can I thank you?}
{222}{}{谢谢你的食物。我该怎么感谢你？ -- Thanks for the food. How can I thank you?}
### {223}{}{Nothing today. Bye.}
{223}{}{今天什么都没有。再见 -- Nothing today. Bye.}
### {224}{}{I see.}
{224}{}{我明白了。 -- I see.}

### {230}{}{What are you doing in this city?}
{230}{}{你在这个城市干什么？ -- What are you doing in this city?}
### {231}{}{We're running from trouble. Terrible things are happening in the southeast: power is changing in cities, people are being enslaved, farmers are being driven from their legitimate lands. We hoped to find salvation in the Ranger lands, but they turned out to be no better.}
{231}{}{我们正在躲避麻烦。可怕的事情正在东南部发生：城市的权力正在改变，人们被奴役，农民被赶出合法的土地。我们希望在流浪者队的土地上找到救赎，但他们并没有好到哪里去。 -- We're running from trouble. Terrible things are happening in the southeast: power is changing in cities, people are being enslaved, farmers are being driven from their legitimate lands. We hoped to find salvation in the Ranger lands, but they turned out to be no better.}
### {232}{}{How did you manage to get across the desert?}
{232}{}{你是怎么穿越沙漠的？ -- How did you manage to get across the desert?}
### {233}{}{It was an ordeal. It's cold at night, and it was so hot during the day that we fried lizards right on the rocks. The main way was overcome in the evening and early in the morning. Sometimes it seemed that we would not survive. We will definitely not survive the second such way.}
{233}{}{这是一场磨难。晚上很冷，白天又很热，我们在岩石上炸蜥蜴。主要的道路是在傍晚和清晨克服的。有时我们似乎活不下去了。我们肯定不会以这种方式度过第二次。 -- It was an ordeal. It's cold at night, and it was so hot during the day that we fried lizards right on the rocks. The main way was overcome in the evening and early in the morning. Sometimes it seemed that we would not survive. We will definitely not survive the second such way.}
### {234}{}{Yes, it's really not easy.}
{234}{}{是的，这真的不容易。 -- Yes, it's really not easy.}
### {235}{}{Tell me again, how did you end up here?}
{235}{}{再说一遍，你是怎么来到这里的？ -- Tell me again, how did you end up here?}

### {240}{}{What made you leave the Ranger lands?}
{240}{}{是什么让你离开了游骑兵队？ -- What made you leave the Ranger lands?}
### {241}{}{Rangers? Ha! We were told that they protect law and order. But in fact they are ordinary bandits.}
{241}{}{游骑兵队？哈我们被告知他们保护法律和秩序。但实际上他们是普通的土匪。 -- Rangers? Ha! We were told that they protect law and order. But in fact they are ordinary bandits.}
### {242}{}{Why did you decide that?}
{242}{}{你为什么这么决定？ -- Why did you decide that?}
### {243}{}{How dare you talk about Rangers like that?}
{243}{}{你怎么敢那样谈论流浪者队？ -- How dare you talk about Rangers like that?}
### {244}{}{First they took away everything of value from us, and then they told us to get out of their lands.}
{244}{}{首先，他们夺走了我们所有有价值的东西，然后他们告诉我们离开他们的土地。 -- First they took away everything of value from us, and then they told us to get out of their lands.}
### {245}{}{But why would they send you away?}
{245}{}{但他们为什么要把你赶走？ -- But why would they send you away?}
### {246}{}{Look at these rags - there is nothing to take from us, we are poor refugees. And we have neither the strength nor the desire to work for them as free slaves. They don't need us. So they drove us away like useless garbage.}
{246}{}{看看这些破烂的东西，我们什么都拿不走，我们是可怜的难民。我们既没有力量也没有欲望作为自由奴隶为他们工作。他们不需要我们。所以他们把我们像无用的垃圾一样赶走了。 -- Look at these rags - there is nothing to take from us, we are poor refugees. And we have neither the strength nor the desire to work for them as free slaves. They don't need us. So they drove us away like useless garbage.}
### {247}{}{Why did you decide it was the Rangers?}
{247}{}{你为什么决定是游骑兵队？ -- Why did you decide it was the Rangers?}
### {248}{}{One of them showed a badge. Besides, the bandits wouldn't chase us away, but would simply rob or kill us.}
{248}{}{其中一人展示了徽章。此外，土匪不会把我们赶走，只是简单地抢劫或杀害我们。 -- One of them showed a badge. Besides, the bandits wouldn't chase us away, but would simply rob or kill us.}
### {249}{}{A strange story... I need to know the details, and you don't leave town yet.}
{249}{}{一个奇怪的故事。。。我需要知道细节，而你还没有离开小镇。 -- A strange story... I need to know the details, and you don't leave town yet.}

### {250}{}{I need to find these rangers.}
{250}{}{我需要找到这些护林员。 -- I need to find these rangers.}
### {251}{}{Find it? What for? Don't push your luck. They'll rob you or kill you.}
{251}{}{找到了吗？为何不要碰运气。他们会抢劫你或者杀了你。 -- Find it? What for? Don't push your luck. They'll rob you or kill you.}
### {252}{}{I'll deal with them. Just show me this place.}
{252}{}{我会处理他们的。带我看看这个地方。 -- I'll deal with them. Just show me this place.}
### {253}{}{Really, it's too dangerous. Forget it.}
{253}{}{真的，太危险了。算了。 -- Really, it's too dangerous. Forget it.}
### {254}{}{Uh no, I'm too weak to travel. I would like to refresh myself before the road.}
{254}{}{不，我太虚弱了，不能旅行。我想在上路前恢复一下精神。 -- Uh no, I'm too weak to travel. I would like to refresh myself before the road.}
### {255}{}{I'll come back when you're stronger. Later.}
{255}{}{我会在你更强壮的时候回来。后来 -- I'll come back when you're stronger. Later.}
### {256}{}{You'll chew your own teeth if you don't show me this place.}
{256}{}{如果你不带我去这个地方，你会自食其力的。 -- You'll chew your own teeth if you don't show me this place.}
### {257}{}{Fair. Here are 20 caps, you can buy food at a local bar with them.}
{257}{}{公平的这里有20顶帽子，你可以用它们在当地的酒吧买食物。 -- Fair. Here are 20 caps, you can buy food at a local bar with them.}
### {258}{}{(greedily watching you rummage through your pockets)}
{258}{}{（贪婪地看着你在口袋里翻找） -- (greedily watching you rummage through your pockets)}
### {259}{}{Uh, I think I left cash at the motel.}
{259}{}{我想我把现金忘在汽车旅馆了。 -- Uh, I think I left cash at the motel.}
### {1259}{}{Uh, I think I left cash at the motel.}
{1259}{}{我想我把现金忘在汽车旅馆了。 -- Uh, I think I left cash at the motel.}
