### {100}{}{Here is a scavenger.}
{100}{}{这是一个拾荒者。 -- Here is a scavenger.}
### {101}{}{You see a bandit in a protective welding mask.}
{101}{}{你看到一个戴着焊接面罩的土匪。 -- You see a bandit in a protective welding mask.}

### {110}{}{What are you doing here?}
{110}{}{你在这里干什么？ -- What are you doing here?}
### {111}{}{Spying?}
{111}{}{间谍？ -- Spying?}
### {112}{}{Did Kogan send you?}
{112}{}{是Kogan派你来的吗？ -- Did Kogan send you?}

### {120}{}{Lucas knows what he's doing.}
{120}{}{卢卡斯知道自己在做什么。 -- Lucas knows what he's doing.}
### {121}{}{Lucas and I have been through a lot together.}
{121}{}{卢卡斯和我一起经历了很多。 -- Lucas and I have been through a lot together.}
### {122}{}{I can imagine how angry Trayvon is right now.}
{122}{}{我可以想象Trayvon现在有多生气。 -- I can imagine how angry Trayvon is right now.}
### {123}{}{This plant is the last hope for us.}
{123}{}{这种植物是我们最后的希望。 -- This plant is the last hope for us.}
### {124}{}{We were the first to open the plant, so now it's ours.}
{124}{}{我们是第一个开放工厂的，所以现在是我们的了。 -- We were the first to open the plant, so now it's ours.}
### {125}{}{Kogan will have to make concessions.}
{125}{}{Kogan将不得不做出让步。 -- Kogan will have to make concessions.}

### {130}{}{We are very lucky to have you.}
{130}{}{我们很幸运有你。 -- We are very lucky to have you.}
### {131}{}{Thanks for the help.}
{131}{}{谢谢你的帮助。 -- Thanks for the help.}
### {132}{}{You're always welcome here.}
{132}{}{这里永远欢迎你。 -- You're always welcome here.}
### {133}{}{We're in charge here now. Thank you.}
{133}{}{我们现在负责这里。非常感谢。 -- We're in charge here now. Thank you.}
### {134}{}{I don't know how it would have ended if it wasn't for you.}
{134}{}{如果不是你，我不知道结局会怎样。 -- I don't know how it would have ended if it wasn't for you.}
