### {100}{}{Here is a scavenger.}
{100}{}{这是一个拾荒者。 -- Here is a scavenger.}
### {101}{}{You see a rude and unfriendly resident of Garage City.}
{101}{}{你看到车库城的一位粗鲁而不友好的居民。 -- You see a rude and unfriendly resident of Garage City.}
### {102}{}{What are you staring at?}
{102}{}{你在看什么？ -- What are you staring at?}
### {103}{}{If you're lying about Jackals, it's going to cost you dearly.}
{103}{}{如果你对豺狼撒谎，你会付出高昂的代价。 -- If you're lying about Jackals, it's going to cost you dearly.}
