### {100}{}{This is the security terminal.}
{100}{}{这是安全终端。 -- This is the security terminal.}
### {101}{}{In front of you, the terminal manages the security system. Recently, someone has already used it$.}
{101}{}{在你面前，终端管理着安全系统。最近，有人已经用了它$。 -- In front of you, the terminal manages the security system. Recently, someone has already used it$.}
### {102}{}{they have restored the security system.}
{102}{}{他们已经恢复了安全系统。 -- they have restored the security system.}
### {103}{}{they have changed the parameters of working robots for their protection.}
{103}{}{为了保护他们，他们改变了工作机器人的参数。 -- they have changed the parameters of working robots for their protection.}
