### {100}{}{You see a private.}
{100}{}{你看到一个私人。 -- You see a private.}
### {101}{}{Here is a private in standard army armor with a recognizable symbol.}
{101}{}{这是一位身穿标准陆军盔甲的士兵，上面有一个可识别的符号。 -- Here is a private in standard army armor with a recognizable symbol.}
### {102}{}{Intruso!}
{102}{}{Intruso！ -- Intruso!}
### {103}{}{Intruder!}
{103}{}{入侵者 -- Intruder!}
### {104}{}{Esta todo bien.}
{104}{}{直到现在。 -- Esta todo bien.}
### {105}{}{Everything is fine.}
{105}{}{一切都很好。 -- Everything is fine.}
