### {100}{}{Here is a Nocturnal Beast.}
{100}{}{这是一只夜行野兽。 -- Here is a Nocturnal Beast.}
### {101}{}{You see the guardian of the Jackals. He faithfully guards the warehouses of his tribe.}
{101}{}{你看到了豺狼的守护者。他忠实地守卫着部落的仓库。 -- You see the guardian of the Jackals. He faithfully guards the warehouses of his tribe.}
### {102}{}{Sh-what for sh-jokes?!}
{102}{}{嘘，你开什么玩笑？！ -- Sh-what for sh-jokes?!}

#Replicas floating
### {120}{}{No one will dare to take my place.}
{120}{}{没有人敢取代我的位置。 -- No one will dare to take my place.}
### {121}{}{Only I can guard these burrows, only I!}
{121}{}{只有我才能守卫这些洞穴，只有我！ -- Only I can guard these burrows, only I!}
### {122}{}{R-I will tear anyone who breaks into the warehouses!}
{122}{}{R-I会撕裂任何闯入仓库的人！ -- R-I will tear anyone who breaks into the warehouses!}
### {123}{}{The tribe needs me.}
{123}{}{部落需要我。 -- The tribe needs me.}
### {124}{}{The Crazy Bitch wants me to guard the warehouses. And I'm guarding.}
{124}{}{疯婊子要我看守仓库。我在守护。 -- The Crazy Bitch wants me to guard the warehouses. And I'm guarding.}
### {125}{}{They say a stranger is wandering in the burrows.}
{125}{}{他们说一个陌生人在洞穴里游荡。 -- They say a stranger is wandering in the burrows.}
### {126}{}{R-r-r! I smell c-surveillance!}
{126}{}{R-R-R！我闻到了剖腹产的味道！ -- R-r-r! I smell c-surveillance!}
### {127}{}{*Sniffing*}
{127}{}{*嗅探* -- *Sniffing*}
### {128}{}{I smell a stranger.}
{128}{}{我闻到一股陌生人的味道。 -- I smell a stranger.}
### {129}{}{These burrows lack the heart-rending moan of strangers.}
{129}{}{这些洞穴没有陌生人令人心碎的呻吟声。 -- These burrows lack the heart-rending moan of strangers.}

#Retaliatory remarks
### {200}{}{Get out! A stranger has no place in these warehouses!}
{200}{}{滚出去！陌生人在这些仓库里没有立足之地！ -- Get out! A stranger has no place in these warehouses!}
### {201}{}{Okay.}
{201}{}{可以 -- Okay.}
