### {100}{}{Here is a raider.}
{100}{}{这是一个袭击者。 -- Here is a raider.}
### {101}{}{You see your partner in the raid on the burrows.}
{101}{}{你在洞穴突袭中看到了你的伙伴。 -- You see your partner in the raid on the burrows.}
### {102}{}{It was a glorious battle, wasn't it?}
{102}{}{这是一场光荣的战斗，不是吗？ -- It was a glorious battle, wasn't it?}

#Retaliatory remarks
### {200}{}{It's time for an offensive. Are you still with us?}
{200}{}{是时候发动攻势了。你还和我们在一起吗？ -- It's time for an offensive. Are you still with us?}
### {201}{}{What do you recommend for an effective fight?}
{201}{}{你对有效的战斗有什么建议？ -- What do you recommend for an effective fight?}
### {202}{}{The jackals are pretty weak, so we won't need any serious weapons. But they are pressed by numbers and huddle in packs in cramped corridors. It would be nice to throw a grenade there or charge them with a shot.}
{202}{}{豺狼很弱，所以我们不需要任何严重的武器。但他们被人数所迫，成群结队地挤在狭窄的走廊里。如果能在那里扔一枚手榴弹或向他们开枪，那就太好了。 -- The jackals are pretty weak, so we won't need any serious weapons. But they are pressed by numbers and huddle in packs in cramped corridors. It would be nice to throw a grenade there or charge them with a shot.}
### {203}{}{Sure. Let's go.}
{203}{}{当然我们走吧。 -- Sure. Let's go.}
### {204}{}{Let's go.}
{204}{}{我们走吧。 -- Let's go.}
### {205}{}{More?}
{205}{}{更多 -- More?}
### {206}{}{Beware of their poisoned blades and claws. And we need to do something about this impenetrable darkness. Surely there are torches in the burrows, it's worth finding them and setting them on fire.}
{206}{}{小心它们中毒的刀刃和爪子。我们需要对这种无法穿透的黑暗做点什么。洞穴里肯定有火把，找到它们并点燃它们是值得的。 -- Beware of their poisoned blades and claws. And we need to do something about this impenetrable darkness. Surely there are torches in the burrows, it's worth finding them and setting them on fire.}
### {207}{}{This is not a good time to chat. Let's move on.}
{207}{}{现在不是聊天的好时机。让我们继续前进。 -- This is not a good time to chat. Let's move on.}
### {208}{}{I didn't expect to see a ranger here. Yes, even in custody. They don't seem to be as cool as everyone thinks they are.}
{208}{}{我没想到会在这里看到护林员。是的，即使在拘留期间。他们似乎并不像大家想象的那么酷。 -- I didn't expect to see a ranger here. Yes, even in custody. They don't seem to be as cool as everyone thinks they are.}
### {209}{}{What do you think - were these the last ones?}
{209}{}{你觉得这是最后一批吗？ -- What do you think - were these the last ones?}
### {210}{}{It looks like it. These burrows are cleared of parasites. It remains to feel the corpses for valuables and get home.}
{210}{}{看起来像。这些洞穴里没有寄生虫。剩下的就是摸尸体找贵重物品然后回家。 -- It looks like it. These burrows are cleared of parasites. It remains to feel the corpses for valuables and get home.}
### {211}{}{OK.}
{211}{}{好啊 -- OK.}
### {212}{}{[Next]}
{212}{}{[下一个 -- Next]}
