### {100}{}{Here is the mutant Edmond.}
{100}{}{这是变种人爱德蒙。 -- Here is the mutant Edmond.}
### {101}{}{You see a terribly disfigured person.}
{101}{}{你看到一个严重毁容的人。 -- You see a terribly disfigured person.}
### {102}{}{A mutant suddenly appears from the shadows.}
{102}{}{一个变种人突然从阴影中出现。 -- A mutant suddenly appears from the shadows.}

### {110}{}{Go away and don't touch us}
{110}{}{走开，别碰我们 -- Go away and don't touch us}
### {111}{}{Leave me alone!}
{111}{}{别管我！ -- Leave me alone!}
### {112}{}{I don't want to talk to you}
{112}{}{我不想和你说话 -- I don't want to talk to you}
### {113}{}{Strangers cannot be trusted}
{113}{}{陌生人不可信任 -- Strangers cannot be trusted}

### {120}{}{Uh-oh! U-a!}
{120}{}{哦！U-a！ -- Uh-oh! U-a!}
### {121}{}{Ar-r!}
{121}{}{Ar-r！ -- Ar-r!}
### {122}{}{Ar-r-r!}
{122}{}{Ar-r-r！ -- Ar-r-r!}
### {123}{}{Ba! Ba-ba!}
{123}{}{巴！巴巴！ -- Ba! Ba-ba!}

### {200}{}{ (The mutant blocks your way, but only swings something dangerous.) Uh-oh!}
{200}{}{（变种人挡住了你的去路，但只会摆动一些危险的东西。）哦！ --  (The mutant blocks your way, but only swings something dangerous.) Uh-oh!}

### {201}{}{[Step back, showing your friendliness]}
{201}{}{[退后一步，表示友好 -- Step back, showing your friendliness]}
### {202}{}{Ar-r! (sensing your softness and unwillingness to fight, the mutant decides to attack!)}
{202}{}{Ar-r！（感觉到你的软弱和不愿意战斗，变种人决定攻击！） -- Ar-r! (sensing your softness and unwillingness to fight, the mutant decides to attack!)}
### {203}{}{No, don't touch me!}
{203}{}{不，别碰我！ -- No, don't touch me!}
### {204}{}{You brute!}
{204}{}{你这个野蛮人！ -- You brute!}
### {205}{}{Stop! Not a step forward!}
{205}{}{停止没有前进一步！ -- Stop! Not a step forward!}
### {206}{}{ (your words only angered the mutant, he decides to attack!)}
{206}{}{（你的话激怒了变种人，他决定攻击！） --  (your words only angered the mutant, he decides to attack!)}

### {210}{}{[Take a provocative step forward]}
{210}{}{[向前迈出挑衅性的一步 -- Take a provocative step forward]}
### {211}{}{Ar-r! (mutant backs away, his gaze becomes even crazier)}
{211}{}{Ar-r！（变种人后退，目光变得更加疯狂） -- Ar-r! (mutant backs away, his gaze becomes even crazier)}
### {212}{}{Look, I don't want a fight. Trust me.}
{212}{}{听着，我不想打架。相信我。 -- Look, I don't want a fight. Trust me.}
### {213}{}{Die, monster!}
{213}{}{死吧，怪物！ -- Die, monster!}
### {214}{}{Stop! Not a step to the side!}
{214}{}{停止一步也不偏！ -- Stop! Not a step to the side!}

### {220}{}{(The mutant slows down sharply and takes a step back. It looks like your determination scared him.)}
{220}{}{（变种人的速度急剧放缓，后退了一步。看起来你的决心吓坏了他。） -- (The mutant slows down sharply and takes a step back. It looks like your determination scared him.)}
### {221}{}{What is it, handsome? You don't want a fight, right?}
{221}{}{这是什么，帅？你不想打架，对吧？ -- What is it, handsome? You don't want a fight, right?}
### {222}{}{That's better. And don't try to twitch, you piece of shit.}
{222}{}{这样更好。别想抽搐，你这个混蛋。 -- That's better. And don't try to twitch, you piece of shit.}
### {223}{}{(The mutant stands in numbness and indecision. You look closely at his disfigured face, on which horror and years of pain are imprinted. His body turns out to be thin and skewed.)}
{223}{}{（变种人站在麻木和优柔寡断中。你仔细看他那张毁容的脸，脸上印着恐惧和多年的痛苦。他的身体变得又瘦又歪斜。） -- (The mutant stands in numbness and indecision. You look closely at his disfigured face, on which horror and years of pain are imprinted. His body turns out to be thin and skewed.)}
### {224}{}{Ha, no wonder you're holed up in the basement when the others are fighting upstairs. How did you even survive with such pathologies?}
{224}{}{哈，难怪你躲在地下室，而其他人在楼上打架。你是如何在这种疾病中幸存下来的？ -- Ha, no wonder you're holed up in the basement when the others are fighting upstairs. How did you even survive with such pathologies?}
### {225}{}{Poor guy, have you been like this from the very beginning? It's a miracle you're even still alive.}
{225}{}{可怜的家伙，你从一开始就这样吗？你还活着真是奇迹。 -- Poor guy, have you been like this from the very beginning? It's a miracle you're even still alive.}
### {226}{}{(Suddenly, behind the mutant's back, someone is crying hysterically from the next room. The sound brings the mutant to his senses, and he stands in a defensive pose, blocking the passage into the room.)}
{226}{}{（突然，在变种人的背后，有人从隔壁房间歇斯底里地哭泣。声音让变种人恢复了理智，他站成防御姿势，堵住了进入房间的通道。） -- (Suddenly, behind the mutant's back, someone is crying hysterically from the next room. The sound brings the mutant to his senses, and he stands in a defensive pose, blocking the passage into the room.)}
### {227}{}{Who's there? Who are you torturing there?}
{227}{}{谁在那里？你在折磨谁？ -- Who's there? Who are you torturing there?}
### {228}{}{Ar-r! (shows you to go away)}
{228}{}{Ar-r！（让你走开） -- Ar-r! (shows you to go away)}
### {229}{}{Answer your mother!}
{229}{}{回答你妈妈！ -- Answer your mother!}
### {230}{}{A-r-r! A-r-r!}
{230}{}{A-r-r！A-r-r！ -- A-r-r! A-r-r!}
### {231}{}{Damn son of a bitch! Die!}
{231}{}{该死的婊子养的！死亡 -- Damn son of a bitch! Die!}
### {232}{}{Step aside and don't get in the way, you piece of shit.}
{232}{}{靠边站，别挡道，你这个混蛋。 -- Step aside and don't get in the way, you piece of shit.}
### {233}{}{Can't you talk? Then I'll go through and find out what's going on there.}
{233}{}{你不会说话吗？然后我会去看看那里发生了什么。 -- Can't you talk? Then I'll go through and find out what's going on there.}
### {234}{}{(shakes his head piteously)}
{234}{}{（可怜地摇摇头） -- (shakes his head piteously)}
### {235}{}{Get out of here. If you come back, you'll die. Is that clear?}
{235}{}{离开这里。如果你回来，你会死的。清楚吗？ -- Get out of here. If you come back, you'll die. Is that clear?}
### {236}{}{I won't kill you if you leave and don't get in the way. Come on, get some fresh air.}
{236}{}{如果你离开并且不妨碍我，我不会杀了你。来吧，呼吸新鲜空气。 -- I won't kill you if you leave and don't get in the way. Come on, get some fresh air.}
