### {100}{}{Here is Alexandra.}
{100}{}{这是亚历山德拉。 -- Here is Alexandra.}
### {101}{}{You see a smiling girl. It seems as if she doesn't quite understand where she got to yet.}
{101}{}{你看到一个微笑的女孩。她似乎还不太明白自己到了哪里。 -- You see a smiling girl. It seems as if she doesn't quite understand where she got to yet.}
### {102}{}{Sorry, you can't bring weapons here.}
{102}{}{对不起，你不能带武器来这里。 -- Sorry, you can't bring weapons here.}
### {103}{}{Sorry, you can't come here in armor.}
{103}{}{对不起，你不能穿着盔甲来这里。 -- Sorry, you can't come here in armor.}
### {104}{}{I... uh-huh... I want to sleep. Come back in the morning...}
{104}{}{我…嗯。。。我想睡觉。早上回来。。。 -- I... uh-huh... I want to sleep. Come back in the morning...}

### {200}{}{Oh, hello! This is the first time I've seen you.}
{200}{}{哦，你好！这是我第一次见到你。 -- Oh, hello! This is the first time I've seen you.}
### {201}{}{I }
{201}{}{我 -- I }
### {202}{}{. What's your name?}
{202}{}{.你叫什么名字？ -- . What's your name?}
### {203}{}{Similarly. Who are you anyway?}
{203}{}{同样。你到底是谁？ -- Similarly. Who are you anyway?}
### {204}{}{Alexandra Titova. I'm Nestor's assistant. Nice to meet you.}
{204}{}{亚历山德拉·蒂托娃。我是内斯特的助手。很高兴认识你。 -- Alexandra Titova. I'm Nestor's assistant. Nice to meet you.}
### {205}{}{You have an unusual surname.}
{205}{}{你有一个不同寻常的姓氏。 -- You have an unusual surname.}
### {206}{}{What a ridiculous name?}
{206}{}{多么荒谬的名字？ -- What a ridiculous name?}
### {207}{}{My ancestors were from another part of the globe. But it doesn't matter now. And the name is just a tribute to memory.}
{207}{}{我的祖先来自世界的另一个地方。但现在已经不重要了。这个名字只是对记忆的致敬。 -- My ancestors were from another part of the globe. But it doesn't matter now. And the name is just a tribute to memory.}
### {208}{}{I see.}
{208}{}{我明白了。 -- I see.}
### {209}{}{In my opinion, this is a tribute to senility.}
{209}{}{在我看来，这是对衰老的致敬。 -- In my opinion, this is a tribute to senility.}

### {220}{}{Can I help you with something?}
{220}{}{我能帮你做点什么吗？ -- Can I help you with something?}
### {221}{}{I don't need any help right now. See you later.}
{221}{}{我现在不需要任何帮助。回头见。 -- I don't need any help right now. See you later.}
### {222}{}{What's going on? Why are there so many people in the square?}
{222}{}{怎么回事？为什么广场上有这么多人？ -- What's going on? Why are there so many people in the square?}
### {223}{}{Residents are excited about the explosion in Puerto. It is unclear how we will survive now without the Brotherhood of Steel. I really hope that they will not start a revolution and will calm down soon.}
{223}{}{居民们对波多黎各的爆炸感到兴奋。现在还不清楚没有钢铁兄弟会我们将如何生存。我真的希望他们不要发动革命，尽快冷静下来。 -- Residents are excited about the explosion in Puerto. It is unclear how we will survive now without the Brotherhood of Steel. I really hope that they will not start a revolution and will calm down soon.}
### {224}{}{That's how it is...}
{224}{}{事情就是这样。。。 -- That's how it is...}
### {225}{}{I need medical supplies.}
{225}{}{我需要医疗用品。 -- I need medical supplies.}

### {230}{}{Tell me about Nestor.}
{230}{}{告诉我内斯特的情况。 -- Tell me about Nestor.}
### {231}{}{Well, he's the only real doctor in town. He's also boring, but cool.}
{231}{}{他是城里唯一真正的医生。他也很无聊，但很酷。 -- Well, he's the only real doctor in town. He's also boring, but cool.}
### {232}{}{What about you?}
{232}{}{你呢？ -- What about you?}
### {233}{}{I'm just learning from him. I'm still a long way from being a doctor. But I can sew up the wound already... I think so.}
{233}{}{我只是在向他学习。我离成为一名医生还有很长的路要走。但我已经可以缝合伤口了。。。我想是的。 -- I'm just learning from him. I'm still a long way from being a doctor. But I can sew up the wound already... I think so.}
### {234}{}{I see.}
{234}{}{我明白了。 -- I see.}
### {235}{}{And what is this place?}
{235}{}{这个地方是什么？ -- And what is this place?}
### {236}{}{Charity Clinic of the Followers of the Apocalypse named after St. Diego.}
{236}{}{启示录信徒慈善诊所以圣迭戈命名。 -- Charity Clinic of the Followers of the Apocalypse named after St. Diego.}
### {237}{}{Now it's clear why it stinks so much here.}
{237}{}{现在很清楚为什么这里这么臭了。 -- Now it's clear why it stinks so much here.}
### {238}{}{Wow, a real hospital! So can I heal the wounds here?}
{238}{}{哇，真是一家医院！那么我能在这里疗伤吗？ -- Wow, a real hospital! So can I heal the wounds here?}
### {239}{}{We treat all those in need, conduct experiments and manufacture medicines. Yes, because of all this, it sometimes smells bad here. But you get used to it quickly.}
{239}{}{我们治疗所有需要帮助的人，进行实验并生产药物。是的，正因为如此，这里有时闻起来很难闻。但你很快就会习惯。 -- We treat all those in need, conduct experiments and manufacture medicines. Yes, because of all this, it sometimes smells bad here. But you get used to it quickly.}
### {240}{}{And here you can buy medicines for the road? I could use an antidote to radscorpions.}
{240}{}{在这里你可以买到路上的药吗？我可以用一种治疗蝎子的解药。 -- And here you can buy medicines for the road? I could use an antidote to radscorpions.}
### {241}{}{Sure. Just tell me what you need. But we hope that in return you will also contribute something useful to our hospital.}
{241}{}{当然告诉我你需要什么。但我们希望作为回报，你也能为我们的医院做出一些有用的贡献。 -- Sure. Just tell me what you need. But we hope that in return you will also contribute something useful to our hospital.}
### {242}{}{Great. I will know.}
{242}{}{太棒了我会知道的。 -- Great. I will know.}
### {243}{}{Hey, you're back! However, we have difficult times here.}
{243}{}{嘿，你回来了！然而，我们在这里遇到了困难。 -- Hey, you're back! However, we have difficult times here.}
### {1243}{}{Hey, you're back! However, we have difficult times here.}
{1243}{}{嘿，你回来了！然而，我们在这里遇到了困难。 -- Hey, you're back! However, we have difficult times here.}
### {244}{}{What do you mean?}
{244}{}{你是什么意思？ -- What do you mean?}
### {245}{}{Imagine, the Brotherhood of Steel fort exploded! They say the explosion was like a nuclear bomb. Well, without them, trade in Casa Nueva is declining. And you will have to spend a lot of caps on security...}
{245}{}{想象一下，钢铁兄弟会的堡垒爆炸了！他们说这次爆炸就像一枚核弹。好吧，没有他们，Casa Nueva的贸易正在下降。你将不得不在安全上花费大量的上限。。。 -- Imagine, the Brotherhood of Steel fort exploded! They say the explosion was like a nuclear bomb. Well, without them, trade in Casa Nueva is declining. And you will have to spend a lot of caps on security...}
### {246}{}{And?}
{246}{}{和 -- And?}
### {247}{}{In general, keep in mind that prices have increased. Including the services of our clinic.}
{247}{}{总的来说，请记住价格已经上涨。包括我们诊所的服务。 -- In general, keep in mind that prices have increased. Including the services of our clinic.}
### {248}{}{I see. I'll keep that in mind.}
{248}{}{我明白了。我会记住的。 -- I see. I'll keep that in mind.}

### {250}{}{Listen, is there anything stronger than bandages and stimpacks?}
{250}{}{听着，还有什么比绷带和刺激包更强的东西吗？ -- Listen, is there anything stronger than bandages and stimpacks?}
### {251}{}{What, for example?}
{251}{}{例如，什么？ -- What, for example?}
### {252}{}{No, forget it.}
{252}{}{不，忘了它。 -- No, forget it.}
### {253}{}{Well, you know, pre-war medicine was clearly better than the current one.}
{253}{}{你知道，战前的医学显然比现在的要好。 -- Well, you know, pre-war medicine was clearly better than the current one.}
### {254}{}{Yes, I think so too. But we are forbidden to sell some old medicines and chemicals like buffout and psycho. They are considered unsafe.}
{254}{}{是的，我也这么认为。但我们被禁止销售一些老药和化学品，如buffout和psychoc。他们被认为是不安全的。 -- Yes, I think so too. But we are forbidden to sell some old medicines and chemicals like buffout and psycho. They are considered unsafe.}
### {255}{}{Then it's not even worth discussing. Let's change the subject?}
{255}{}{那就不值得讨论了。我们换个话题吧？ -- Then it's not even worth discussing. Let's change the subject?}
### {256}{}{Yes, that's exactly what I'm looking for. Is there really no way to get at least a pinch? For scientific purposes?}
{256}{}{是的，这正是我想要的。真的没有办法至少得到一点帮助吗？为了科学目的？ -- Yes, that's exactly what I'm looking for. Is there really no way to get at least a pinch? For scientific purposes?}
### {257}{}{I don't know what your scientific goals are there, but I have clear instructions. Talk to Nestor if you don't like it.}
{257}{}{我不知道你的科学目标是什么，但我有明确的指示。如果你不喜欢，可以和内斯特谈谈。 -- I don't know what your scientific goals are there, but I have clear instructions. Talk to Nestor if you don't like it.}
### {258}{}{Okay. There doesn't seem to be any point in continuing. Later.}
{258}{}{可以继续下去似乎没有任何意义。后来 -- Okay. There doesn't seem to be any point in continuing. Later.}
### {259}{}{Come on - it's a mountain of caps!}
{259}{}{来吧，这是一座帽子山！ -- Come on - it's a mountain of caps!}
### {260}{}{Ahem. In my opinion, you urgently need fresh air. The door is over there.}
{260}{}{嗯。在我看来，你急需新鲜空气。门在那边。 -- Ahem. In my opinion, you urgently need fresh air. The door is over there.}
### {261}{}{Don't even think about blabbing!}
{261}{}{甚至别想胡言乱语！ -- Don't even think about blabbing!}
### {262}{}{Okay, I don't want any problems. I'm leaving.}
{262}{}{好吧，我不想有任何问题。我要走了。 -- Okay, I don't want any problems. I'm leaving.}
### {263}{}{Think about it, what good is your clinic from a damaged product that is not bought and not used?}
{263}{}{想想看，你的诊所对一个没有购买也没有使用的损坏产品有什么好处？ -- Think about it, what good is your clinic from a damaged product that is not bought and not used?}
### {264}{}{Yes... of course... Hmm, maybe Nestor will make an exception for you. We really don't have enough caps.}
{264}{}{对当然嗯，也许内斯特会为你破例。我们真的没有足够的帽子。 -- Yes... of course... Hmm, maybe Nestor will make an exception for you. We really don't have enough caps.}
### {265}{}{Thank you.}
{265}{}{非常感谢。 -- Thank you.}
### {266}{}{Please make an exception for me. I won't tell anyone.}
{266}{}{请替我破例，我不会告诉任何人。 -- Please make an exception for me. I won't tell anyone.}
### {267}{}{Nestor will allow it. You could say I'm already a member of your team.}
{267}{}{内斯特会允许的。你可以说我已经是你团队的一员了。 -- Nestor will allow it. You could say I'm already a member of your team.}
### {268}{}{I need a dose for... what's their name... for experiments, yes.}
{268}{}{我需要一剂。。。他们叫什么名字。。。对于实验来说，是的。 -- I need a dose for... what's their name... for experiments, yes.}
### {269}{}{I have a purely scientific interest, colleague. We both understand how important it is for scientists to support each other.}
{269}{}{我有一个纯粹的科学兴趣，同事。我们都明白科学家相互支持是多么重要。 -- I have a purely scientific interest, colleague. We both understand how important it is for scientists to support each other.}
### {270}{}{You'd be surprised, but it really became a problem in Phoenix. I personally know the story of a drug addict from the slums.}
{270}{}{你可能会感到惊讶，但这在凤凰城真的成了一个问题。我个人知道一个来自贫民窟的瘾君子的故事。 -- You'd be surprised, but it really became a problem in Phoenix. I personally know the story of a drug addict from the slums.}
### {271}{}{Poor devils. That's how science suffers because of someone's stupidity. Is drug addiction the fault of medicine?}
{271}{}{可怜的魔鬼。这就是科学因为某人的愚蠢而遭受痛苦的原因。毒瘾是医学的错吗？ -- Poor devils. That's how science suffers because of someone's stupidity. Is drug addiction the fault of medicine?}
### {272}{}{So is there really no way to purchase at least a pinch of the drug? For scientific purposes?}
{272}{}{那么，真的没有办法购买至少一小撮这种药物吗？为了科学目的？ -- So is there really no way to purchase at least a pinch of the drug? For scientific purposes?}
### {273}{}{It's not worth discussing any more. Let's change the subject?}
{273}{}{这不值得再讨论了。我们换个话题吧？ -- It's not worth discussing any more. Let's change the subject?}
### {274}{}{Diana knows I won't do anything stupid.}
{274}{}{戴安娜知道我不会做傻事。 -- Diana knows I won't do anything stupid.}
