### {100}{}{Here is Nick.}
{100}{}{这是尼克。 -- Here is Nick.}
### {101}{}{Here is one of the inhabitants of Casa Nueva.}
{101}{}{这是努瓦之家的一位居民。 -- Here is one of the inhabitants of Casa Nueva.}
### {102}{}{At night we sleep and do not interfere with each other. It is better not to break this rule.}
{102}{}{晚上我们睡觉，互不干扰。最好不要违反这个规则。 -- At night we sleep and do not interfere with each other. It is better not to break this rule.}

### {200}{}{Hi, I'm Nick. How can I help you?}
{200}{}{嗨，我是尼克。我能帮你什么？ -- Hi, I'm Nick. How can I help you?}
### {201}{}{Nice to meet you, Nick. Can I ask you a few questions?}
{201}{}{很高兴认识你，尼克。我能问你几个问题吗？ -- Nice to meet you, Nick. Can I ask you a few questions?}
### {202}{}{I'm not interested in your name. But I need to know something.}
{202}{}{我对你的名字不感兴趣。但我需要知道一些事情。 -- I'm not interested in your name. But I need to know something.}
### {203}{}{Nothing. I'll go.}
{203}{}{没有什么我去。 -- Nothing. I'll go.}

### {210}{}{How can I help you?}
{210}{}{我能帮你什么？ -- How can I help you?}
### {211}{}{What do you need from me?}
{211}{}{你需要我做什么？ -- What do you need from me?}
### {212}{}{I'll go.}
{212}{}{我去。 -- I'll go.}
### {213}{}{Can I ask you a few questions?}
{213}{}{我能问你几个问题吗？ -- Can I ask you a few questions?}

### {220}{}{Of course.}
{220}{}{当然 -- Of course.}
### {221}{}{Thanks, Nick. Goodbye.}
{221}{}{谢谢，尼克。再见 -- Thanks, Nick. Goodbye.}
### {222}{}{I'm sorry, uh, but you'd better talk to the mayor first. Otherwise we will have problems.}
{222}{}{对不起，呃，你最好先和市长谈谈。否则我们会有问题。 -- I'm sorry, uh, but you'd better talk to the mayor first. Otherwise we will have problems.}
### {223}{}{Are you serious? Well, okay...}
{223}{}{你是认真的吗？好吧。。。 -- Are you serious? Well, okay...}

### {230}{}{Who are you?}
{230}{}{你是谁？ -- Who are you?}
### {231}{}{My name is Nick, I'm telling you.}
{231}{}{我告诉你，我叫尼克。 -- My name is Nick, I'm telling you.}
### {232}{}{What are you doing here, Nick?}
{232}{}{你在这里干什么，尼克？ -- What are you doing here, Nick?}
### {233}{}{What can a person with that name do in a place like this?}
{233}{}{一个叫这个名字的人在这样的地方能做什么？ -- What can a person with that name do in a place like this?}
### {234}{}{I'm working, you know. I used to work at a concrete plant, but the plant has recently been closed.}
{234}{}{我在工作，你知道的。我以前在一家混凝土厂工作，但这家工厂最近已经关闭了。 -- I'm working, you know. I used to work at a concrete plant, but the plant has recently been closed.}
### {235}{}{Your diligence is commendable. Few are willing to give themselves up to their work. But I wanted to ask something else.}
{235}{}{你的勤奋值得称赞。很少有人愿意献身于自己的工作。但我想问别的问题。 -- Your diligence is commendable. Few are willing to give themselves up to their work. But I wanted to ask something else.}
### {236}{}{And that's all you've achieved? Then do at least something valuable - answer me a couple of questions.}
{236}{}{这就是你所取得的全部成就？然后至少做一些有价值的事情——回答我几个问题。 -- And that's all you've achieved? Then do at least something valuable - answer me a couple of questions.}
### {237}{}{Surely you have plenty of free time. Will you answer a couple more questions?}
{237}{}{你肯定有很多空闲时间。你能再回答几个问题吗？ -- Surely you have plenty of free time. Will you answer a couple more questions?}

### {240}{}{How did you end up in this city?}
{240}{}{你是怎么来到这个城市的？ -- How did you end up in this city?}
### {241}{}{You know, it's not customary to ask about the past here. We are building a new life to replace the old one. But if that's what you're worried about, I came from Casa Grande. It's a small town on the way to Phoenix. Surely you've been through it?}
{241}{}{你知道，在这里询问过去是不习惯的。我们正在建立一种新的生活来取代旧的生活。但如果这是你担心的，我来自格兰德之家。这是去凤凰城的路上的一个小镇。你肯定经历过吗？ -- You know, it's not customary to ask about the past here. We are building a new life to replace the old one. But if that's what you're worried about, I came from Casa Grande. It's a small town on the way to Phoenix. Surely you've been through it?}
### {242}{}{Casa Grande, you say? Thanks for the information. What else can you tell me?}
{242}{}{格兰德之家，你说？谢谢你提供的信息。你还能告诉我什么？ -- Casa Grande, you say? Thanks for the information. What else can you tell me?}
### {243}{}{Too smart? Of course I know about this place. Better tell me something else.}
{243}{}{太聪明了？我当然知道这个地方。最好告诉我别的事。 -- Too smart? Of course I know about this place. Better tell me something else.}
### {244}{}{I see. What about the rest of the questions?}
{244}{}{我明白了。剩下的问题呢？ -- I see. What about the rest of the questions?}
### {245}{}{How free are you here? Can you leave if you want?}
{245}{}{你在这里有多自由？如果你愿意，你能离开吗？ -- How free are you here? Can you leave if you want?}
### {246}{}{Why leave this paradise? There is only a desert around, and in large settlements there is nothing but suffering. Yes, I'm losing some of my freedom here. But in exchange I get Vault and food. First we have to survive and build a new world, and only after that we can talk about freedom. Such times.}
{246}{}{为什么要离开这个天堂？周围只有一片沙漠，在大型定居点，除了苦难什么都没有。是的，我在这里失去了一些自由。但作为交换，我得到了金库和食物。首先，我们必须生存并建立一个新世界，只有在那之后，我们才能谈论自由。这样的时代。 -- Why leave this paradise? There is only a desert around, and in large settlements there is nothing but suffering. Yes, I'm losing some of my freedom here. But in exchange I get Vault and food. First we have to survive and build a new world, and only after that we can talk about freedom. Such times.}
### {247}{}{Inspiring speech, Nick. Life is really better here than in the rest of Arizona. Will you tell me something else?}
{247}{}{鼓舞人心的演讲，尼克。这里的生活确实比亚利桑那州其他地方好。你能告诉我别的事吗？ -- Inspiring speech, Nick. Life is really better here than in the rest of Arizona. Will you tell me something else?}
### {248}{}{Only weak people don't go against the wind. I hope you have the strength to at least answer a couple of questions.}
{248}{}{只有软弱的人才不会逆风而行。我希望你至少有能力回答几个问题。 -- Only weak people don't go against the wind. I hope you have the strength to at least answer a couple of questions.}
### {249}{}{I understand you. Let me ask you one more question?}
{249}{}{我理解你。让我再问你一个问题？ -- I understand you. Let me ask you one more question?}
### {250}{}{Casa Grande is where?}
{250}{}{格兰德之家在哪里？ -- Casa Grande is where?}
### {251}{}{In the middle of the tenth highway between Phoenix and Two-Sun. I can show it on the map.}
{251}{}{在凤凰城和双阳之间的第十条高速公路的中间。我可以把它显示在地图上。 -- In the middle of the tenth highway between Phoenix and Two-Sun. I can show it on the map.}
### {252}{}{Thank you.}
{252}{}{非常感谢。 -- Thank you.}
