### {100}{}{Before you Himador.}
{100}{}{在你面前，希玛多。 -- Before you Himador.}
### {101}{}{You see a very tanned man in a straw hat and a fresh linen shirt.}
{101}{}{你看到一个晒得黝黑的男人，戴着草帽，穿着一件崭新的亚麻衬衫。 -- You see a very tanned man in a straw hat and a fresh linen shirt.}
### {102}{}{Guns are prohibited in the city. Hide it quickly.}
{102}{}{市内禁止携带枪支。快把它藏起来。 -- Guns are prohibited in the city. Hide it quickly.}
### {103}{}{Oh, my respects, sir... I, uh, need to work... if I may...}
{103}{}{哦，尊敬的先生。。。I、 呃，需要工作。。。如果可以的话。。。 -- Oh, my respects, sir... I, uh, need to work... if I may...}
### {104}{}{Don't talk to me while there's a curfew in town...}
{104}{}{镇上有宵禁的时候别跟我说话。。。 -- Don't talk to me while there's a curfew in town...}

#First meeting
### {200}{}{Hola, se?or. My name is Juan. But I haven't seen you before.}
{200}{}{你好，塞尼奥。我的名字叫胡安。但我以前没见过你。 -- Hola, se?or. My name is Juan. But I haven't seen you before.}
### {1200}{}{Hola, se?ora. My name is Juan. But I haven't seen you before.}
{1200}{}{你好，塞诺拉。我的名字叫胡安。但我以前没见过你。 -- Hola, se?ora. My name is Juan. But I haven't seen you before.}
### {201}{}{Do you always meet new people so unfriendly?}
{201}{}{你总是遇到这么不友好的新人吗？ -- Do you always meet new people so unfriendly?}
### {202}{}{Listen, we have a semi-closed community here. Everyone knows each other. I just want to understand what to expect from you, and that's it.}
{202}{}{听着，我们这里有一个半封闭的社区。每个人都互相认识。我只是想了解你的期望，仅此而已。 -- Listen, we have a semi-closed community here. Everyone knows each other. I just want to understand what to expect from you, and that's it.}
### {203}{}{Okay. Sorry.}
{203}{}{可以很抱歉 -- Okay. Sorry.}
### {204}{}{You've already shown your attitude towards outsiders. I don't think I'll be here long.}
{204}{}{你已经表明了你对外人的态度。我想我不会在这里呆太久。 -- You've already shown your attitude towards outsiders. I don't think I'll be here long.}
### {205}{}{Nice to meet you, Juan. I }
{205}{}{很高兴认识你，胡安。我 -- Nice to meet you, Juan. I }
### {206}{}{from a distant village in the north.}
{206}{}{来自北方一个遥远的村庄。 -- from a distant village in the north.}
### {207}{}{Ah, so you're a peasant too! Then welcome.}
{207}{}{啊，原来你也是农民！那么欢迎。 -- Ah, so you're a peasant too! Then welcome.}
### {1207}{}{Ah, so you're a peasant too! Then welcome.}
{1207}{}{啊，原来你也是农民！那么欢迎。 -- Ah, so you're a peasant too! Then welcome.}
### {208}{}{Thank you. I see good people live here.}
{208}{}{非常感谢。我看到这里住着好人。 -- Thank you. I see good people live here.}
### {209}{}{Otherwise, you would have sent me away, right? You're so "hospitable."}
{209}{}{否则，你会把我赶走的，对吧？你太“好客”了 -- Otherwise, you would have sent me away, right? You're so "hospitable."}

#Repeat meeting
### {210}{}{Hola. Buenas noches.}
{210}{}{Hola。布埃纳斯·诺切斯。 -- Hola. Buenas noches.}
### {211}{}{Hola. Buenos dias.}
{211}{}{Hola。布宜诺斯艾利斯。 -- Hola. Buenos dias.}
### {212}{}{Adios, hombre.}
{212}{}{再见，伙计。 -- Adios, hombre.}
### {213}{}{I need fire agave juice.}
{213}{}{我需要火龙舌兰汁。 -- I need fire agave juice.}

### {220}{}{Tell me about this city. Who's in charge here?}
{220}{}{告诉我这个城市的情况。谁是这里的负责人？ -- Tell me about this city. Who's in charge here?}
### {221}{}{You need to see Mayor Alvaro. He likes to chat with strangers.}
{221}{}{你需要去见阿尔瓦罗市长。他喜欢和陌生人聊天。 -- You need to see Mayor Alvaro. He likes to chat with strangers.}
### {222}{}{Thanks, I'll talk to him later.}
{222}{}{谢谢，我稍后再和他谈谈。 -- Thanks, I'll talk to him later.}
### {223}{}{Tell me about yourself.}
{223}{}{告诉我你自己。 -- Tell me about yourself.}
### {224}{}{I'm Himador Juan. What else can I tell you?}
{224}{}{我是希玛多·胡安。我还能告诉你什么？ -- I'm Himador Juan. What else can I tell you?}
### {225}{}{What are you doing here, Himador Juan?}
{225}{}{你在这里干什么，希玛多·胡安？ -- What are you doing here, Himador Juan?}
### {226}{}{I process fire agave and other crops. And while he is still not in time, I am engaged in shipping goods to caravans and other household.}
{226}{}{我加工火龙舌兰和其他作物。虽然他还没来得及，但我正在为大篷车和其他家庭运送货物。 -- I process fire agave and other crops. And while he is still not in time, I am engaged in shipping goods to caravans and other household.}
### {227}{}{Juan, tell me... are you here of your own free will?}
{227}{}{胡安，告诉我…你是自愿来的吗？ -- Juan, tell me... are you here of your own free will?}
### {228}{}{Si, se?or. I work as a peon. I could have left at any moment, but there's nowhere to go. We have to live by the rules and work out the contract.}
{228}{}{Si，se?or。我是工人。我本可以随时离开的，但无处可去。我们必须遵守规则并签订合同。 -- Si, se?or. I work as a peon. I could have left at any moment, but there's nowhere to go. We have to live by the rules and work out the contract.}
### {1228}{}{Si, se?ora. I work as a peon. I could have left at any moment, but there's nowhere to go. We have to live by the rules and work out the contract.}
{1228}{}{Si，se?ora。我是工人。我本可以随时离开的，但无处可去。我们必须遵守规则并签订合同。 -- Si, se?ora. I work as a peon. I could have left at any moment, but there's nowhere to go. We have to live by the rules and work out the contract.}
### {229}{}{I see. Thanks for the answer.}
{229}{}{我明白了。谢谢你的回答。 -- I see. Thanks for the answer.}

### {230}{}{I want to ask you about the plantations.}
{230}{}{我想问你种植园的情况。 -- I want to ask you about the plantations.}
### {231}{}{We mainly grow maize and fire agave. But why are you suddenly interested in this?}
{231}{}{我们主要种植玉米和火龙舌兰。但你为什么突然对此感兴趣？ -- We mainly grow maize and fire agave. But why are you suddenly interested in this?}
### {232}{}{Yes, just curious - what else is a "fiery agave"?}
{232}{}{是的，只是好奇——“火红龙舌兰”还有什么？ -- Yes, just curious - what else is a "fiery agave"?}
### {233}{}{I know about the usual agave, but this is the first time I hear about the fiery one. What is it?}
{233}{}{我知道常见的龙舌兰，但这是我第一次听说火红的。它是什么？ -- I know about the usual agave, but this is the first time I hear about the fiery one. What is it?}
### {234}{}{Followers say it's a mutated agave that was grown before the Great War. Since then, the plant has become bigger, more poisonous and needle-like. But there is still a useful pulp inside. That's what we get mainly.}
{234}{}{追随者们说这是一种变异龙舌兰，生长在大战之前。从那时起，这种植物变得更大、更毒、更像针。但里面仍然有有用的果肉。这是我们主要得到的。 -- Followers say it's a mutated agave that was grown before the Great War. Since then, the plant has become bigger, more poisonous and needle-like. But there is still a useful pulp inside. That's what we get mainly.}
### {235}{}{But what's the use of this plant?}
{235}{}{但是这种植物有什么用？ -- But what's the use of this plant?}
### {236}{}{Uh, amigo, everything comes from the plant. Pulp and juice - for food. And the stems are for fertilizer and straw. Followers even make medicines from agave pomace!}
{236}{}{嗯，朋友，所有的东西都来自植物。果肉和果汁——用于食品。茎是用来施肥和稻草的。追随者们甚至用龙舌兰渣做药！ -- Uh, amigo, everything comes from the plant. Pulp and juice - for food. And the stems are for fertilizer and straw. Followers even make medicines from agave pomace!}
### {237}{}{And where are the plantations?}
{237}{}{种植园在哪里？ -- And where are the plantations?}
### {238}{}{In the east... But I do not advise you to go there. Many of us won't like it.}
{238}{}{在东方。。。但我不建议你去那里。我们中的许多人不会喜欢它。 -- In the east... But I do not advise you to go there. Many of us won't like it.}
### {239}{}{How interesting. Can I buy some crops?}
{239}{}{真有趣。我能买些庄稼吗？ -- How interesting. Can I buy some crops?}
### {240}{}{Actually, there is not enough harvest for everyone. Therefore, I am forbidden to trade with everyone in a row.}
{240}{}{事实上，并不是每个人都有足够的收成。因此，我被禁止与所有人连续交易。 -- Actually, there is not enough harvest for everyone. Therefore, I am forbidden to trade with everyone in a row.}
### {241}{}{I see. Thanks for the answer.}
{241}{}{我明白了。谢谢你的回答。 -- I see. Thanks for the answer.}
### {242}{}{I really need agave juice. Sell, please.}
{242}{}{我真的需要龙舌兰汁。请卖掉。 -- I really need agave juice. Sell, please.}
### {243}{}{Sorry, amigo. Can't. If the mayor finds out who the buyer is, he'll probably yell at me.}
{243}{}{对不起，朋友。不能如果市长发现买家是谁，他可能会对我大喊大叫。 -- Sorry, amigo. Can't. If the mayor finds out who the buyer is, he'll probably yell at me.}
### {244}{}{Okay, forget it.}
{244}{}{好吧，算了。 -- Okay, forget it.}
### {245}{}{And who's in charge here?}
{245}{}{谁是这里的负责人？ -- And who's in charge here?}
### {246}{}{You probably have a surplus that no one will notice. And I have extra caps...}
{246}{}{你可能有盈余，没有人会注意到。我还有额外的帽子。。。 -- You probably have a surplus that no one will notice. And I have extra caps...}
### {247}{}{I see you know how to bargain. Okay, if you need agave juice, contact us. Although I don't understand why you need it. Do you really want to make tequila?}
{247}{}{我看你知道怎么讨价还价。好的，如果你需要龙舌兰汁，请联系我们。虽然我不明白你为什么需要。你真的想做龙舌兰酒吗？ -- I see you know how to bargain. Okay, if you need agave juice, contact us. Although I don't understand why you need it. Do you really want to make tequila?}
### {248}{}{I'm thinking about it.}
{248}{}{我正在考虑。 -- I'm thinking about it.}
### {249}{}{Come on, Juan, it's me. Is that the way to treat friends?}
{249}{}{来吧，胡安，是我。这是对待朋友的方式吗？ -- Come on, Juan, it's me. Is that the way to treat friends?}

### {250}{}{Why are weapons prohibited here?}
{250}{}{为什么这里禁止携带武器？ -- Why are weapons prohibited here?}
### {251}{}{Don't go against the rules, dear viajero. These prohibitions at the front gate are written in blood.}
{251}{}{不要违反规则，亲爱的维亚杰罗。前门的这些禁令是用鲜血写的。 -- Don't go against the rules, dear viajero. These prohibitions at the front gate are written in blood.}
### {252}{}{Sorry, that was an unnecessary question. Forget about it.}
{252}{}{对不起，这是一个不必要的问题。忘掉它吧。 -- Sorry, that was an unnecessary question. Forget about it.}
### {253}{}{Why are you carrying this strange spear?}
{253}{}{你为什么带着这奇怪的长矛？ -- Why are you carrying this strange spear?}
### {254}{}{A-ha-ha, it's not a weapon, it's a koa. I chop agave leaves with them when I harvest. And I have permission from the mayor for this. And if there is no permission, then even the koa cannot be worn openly.}
{254}{}{哈哈，这不是武器，这是考拉。我收割的时候用它们切龙舌兰叶子。我得到了市长的许可。如果没有许可，那么即使是考拉也不能公开佩戴。 -- A-ha-ha, it's not a weapon, it's a koa. I chop agave leaves with them when I harvest. And I have permission from the mayor for this. And if there is no permission, then even the koa cannot be worn openly.}
### {255}{}{I've never seen anything like it.}
{255}{}{我从来没有见过这样的东西。 -- I've never seen anything like it.}
### {1255}{}{I've never seen anything like it.}
{1255}{}{我从来没有见过这样的东西。 -- I've never seen anything like it.}
### {256}{}{The mayor was making an order from the tinsmiths. They then took payment with the harvest. It is very expensive, but without tools we will have a hard time working. And besides tinsmiths, no one else can do it.}
{256}{}{市长正在向锡匠们下命令。然后，他们用收获来支付。它很贵，但如果没有工具，我们将很难工作。除了打锡匠，没有其他人能做到。 -- The mayor was making an order from the tinsmiths. They then took payment with the harvest. It is very expensive, but without tools we will have a hard time working. And besides tinsmiths, no one else can do it.}
### {257}{}{How familiar. At our Villa, we also have to do everything manually.}
{257}{}{多么熟悉啊。在我们的别墅，我们还必须手动完成所有事情。 -- How familiar. At our Villa, we also have to do everything manually.}
### {258}{}{Really? I've never heard of other plantations. Aren't you lying?}
{258}{}{真正地我从未听说过其他种植园。你不是在撒谎吗？ -- Really? I've never heard of other plantations. Aren't you lying?}
### {259}{}{If you don't believe me, let's change the subject.}
{259}{}{如果你不相信我，我们换个话题吧。 -- If you don't believe me, let's change the subject.}
### {260}{}{Now it's clear. Let's talk about something else?}
{260}{}{现在很清楚了。我们谈谈别的吧？ -- Now it's clear. Let's talk about something else?}
### {261}{}{This is the first time I've seen such a tool.}
{261}{}{这是我第一次看到这样的工具。 -- This is the first time I've seen such a tool.}
### {262}{}{Is it me "all in a row"?}
{262}{}{是我“排成一排”吗？ -- Is it me "all in a row"?}
### {263}{}{Why?}
{263}{}{为什么？ -- Why?}
### {264}{}{Would you like it if someone walked around your house without asking? Besides, sometimes we catch crop robbers. Usually their fate is deplorable.}
{264}{}{如果有人不问就在你家里走来走去，你会喜欢吗？此外，有时我们还抓庄稼强盗。通常他们的命运是可悲的。 -- Would you like it if someone walked around your house without asking? Besides, sometimes we catch crop robbers. Usually their fate is deplorable.}
