### {100}{}{This is Frank.}
{100}{}{这是弗兰克。 -- This is Frank.}
### {101}{}{You see a sullen man in combat gear.}
{101}{}{你看到一个穿着作战装备的闷闷不乐的人。 -- You see a sullen man in combat gear.}
### {102}{}{Put your weapon away immediately.}
{102}{}{立即收起武器。 -- Put your weapon away immediately.}
### {103}{}{Leave this armor immediately.}
{103}{}{立刻离开这件盔甲。 -- Leave this armor immediately.}
### {104}{}{Weapons! Remove!}
{104}{}{武器！去除 -- Weapons! Remove!}
### {105}{}{There is a hostile personality in the city. Everyone find Vault!}
{105}{}{这个城市里有一个充满敌意的人。每个人都找到保险库！ -- There is a hostile personality in the city. Everyone find Vault!}

### {200}{}{Did something happen?}
{200}{}{发生什么事了吗？ -- Did something happen?}
### {201}{}{No. Should it have?}
{201}{}{没有。应该有吗？ -- No. Should it have?}
### {202}{}{I'm not going to waste a lot of time on you. Can you read? Then remember the rules written at the main gate, and nothing will happen to you.}
{202}{}{我不会在你身上浪费很多时间。你会读书吗？然后记住大门上写的规则，你就不会出事了。 -- I'm not going to waste a lot of time on you. Can you read? Then remember the rules written at the main gate, and nothing will happen to you.}
### {203}{}{Oh yes, the rules...}
{203}{}{哦，是的，规则。。。 -- Oh yes, the rules...}
### {204}{}{Glad to meet you, brother! Congratulations on the promotion.}
{204}{}{很高兴见到你，兄弟！祝贺你升职。 -- Glad to meet you, brother! Congratulations on the promotion.}
### {1204}{}{Glad to meet you, Sister! Congratulations on the promotion.}
{1204}{}{很高兴认识你，姐姐！祝贺你升职。 -- Glad to meet you, Sister! Congratulations on the promotion.}
### {205}{}{Are you from the Brotherhood too?}
{205}{}{你也是兄弟会的吗？ -- Are you from the Brotherhood too?}
### {206}{}{That's right. The Order keeps order in this city. Our patrols stop here periodically. Don't worry, this place is calm and safe. Some fighters are even sent here for rest and treatment. On the ship, as you understand, the conditions are not the most pleasant.}
{206}{}{没错。骑士团维持着这个城市的秩序。我们的巡逻队定期在此停留。别担心，这里平静而安全。一些战士甚至被送到这里休息和治疗。正如你所理解的，船上的条件并不是最宜人的。 -- That's right. The Order keeps order in this city. Our patrols stop here periodically. Don't worry, this place is calm and safe. Some fighters are even sent here for rest and treatment. On the ship, as you understand, the conditions are not the most pleasant.}
### {207}{}{Well yes. Do you mind if I stay here for a while? Great.}
{207}{}{是的。你介意我在这里呆一段时间吗？太棒了 -- Well yes. Do you mind if I stay here for a while? Great.}

### {210}{}{I'm listening.}
{210}{}{我在听。 -- I'm listening.}
### {211}{}{I'm listening to you carefully.}
{211}{}{我在认真听你说话。 -- I'm listening to you carefully.}
### {212}{}{Are you still here?}
{212}{}{你还在这里吗？ -- Are you still here?}
### {213}{}{I won't distract you anymore. Later.}
{213}{}{我不会再分散你的注意力了。后来 -- I won't distract you anymore. Later.}

### {220}{}{They say people disappear on plantations, and you do nothing.}
{220}{}{他们说人们消失在种植园里，而你什么都不做。 -- They say people disappear on plantations, and you do nothing.}
### {221}{}{There must be serious grounds for such statements.}
{221}{}{这种说法必须有充分的理由。 -- There must be serious grounds for such statements.}
### {222}{}{That's what people say...}
{222}{}{人们就是这么说的。。。 -- That's what people say...}
### {223}{}{Remember, stranger, I don't like it when they create panic and spread rumors in my city. If you don't want problems, don't aggravate your situation. It's simple.}
{223}{}{记住，陌生人，我不喜欢他们在我的城市制造恐慌和散布谣言。如果你不想遇到问题，不要使你的处境恶化。这很简单。 -- Remember, stranger, I don't like it when they create panic and spread rumors in my city. If you don't want problems, don't aggravate your situation. It's simple.}
### {224}{}{Yes, indeed. I don't want any problems.}
{224}{}{是的，的确如此。我不想有任何问题。 -- Yes, indeed. I don't want any problems.}
### {225}{}{The same goes for you. Remember - sooner or later justice will overtake anyone.}
{225}{}{你也一样。记住，正义迟早会追上任何人。 -- The same goes for you. Remember - sooner or later justice will overtake anyone.}

### {230}{}{Isn't it forbidden to openly carry weapons here?}
{230}{}{这里不禁止公开携带武器吗？ -- Isn't it forbidden to openly carry weapons here?}
### {231}{}{That's right - it's forbidden. And you should honor our laws like your own mother.}
{231}{}{没错，这是被禁止的。你应该像你自己的母亲一样尊重我们的法律。 -- That's right - it's forbidden. And you should honor our laws like your own mother.}
### {232}{}{But why do you carry a gun?}
{232}{}{但你为什么带枪？ -- But why do you carry a gun?}
### {233}{}{I am the one who defines such rules.}
{233}{}{我是定义这些规则的人。 -- I am the one who defines such rules.}
### {234}{}{I understand now. I'm sorry for asking ridiculous questions. Can I go?}
{234}{}{我现在明白了。我很抱歉问了一些荒谬的问题。我能去吗？ -- I understand now. I'm sorry for asking ridiculous questions. Can I go?}
### {235}{}{Well yes. It's so convenient...}
{235}{}{是的。太方便了。。。 -- Well yes. It's so convenient...}
### {236}{}{I don't like you. You come to a place where you were not invited, and you dare to doubt our rules. But I'll give you a choice. One of two.}
{236}{}{我不喜欢你。你来到了一个没有被邀请的地方，你敢怀疑我们的规则。但我给你一个选择。二选一。 -- I don't like you. You come to a place where you were not invited, and you dare to doubt our rules. But I'll give you a choice. One of two.}
### {237}{}{And what is it?}
{237}{}{它是什么？ -- And what is it?}
### {238}{}{Or you accept the rules and stop annoying others. Either you get the hell out of here. Think carefully about the answer.}
{238}{}{或者你接受了规则，不再打扰别人。要么你滚出去。仔细思考答案。 -- Or you accept the rules and stop annoying others. Either you get the hell out of here. Think carefully about the answer.}
### {239}{}{The only one who bothers everyone here is you. And I'll do anything to ruin your watch.}
{239}{}{唯一让这里的每个人感到困扰的是你。我会做任何破坏你手表的事。 -- The only one who bothers everyone here is you. And I'll do anything to ruin your watch.}
### {240}{}{Good. I'll make a choice. The most correct choice.}
{240}{}{好的我会做出选择。最正确的选择。 -- Good. I'll make a choice. The most correct choice.}
### {241}{}{Yes - forbidden. The peasants must know who their master is. Yes, you should follow these rules too.}
{241}{}{是-禁止。农民必须知道他们的主人是谁。是的，你也应该遵守这些规则。 -- Yes - forbidden. The peasants must know who their master is. Yes, you should follow these rules too.}
### {242}{}{Of course.}
{242}{}{当然 -- Of course.}

### {250}{}{Any problems? Why are you violating public order?}
{250}{}{有什么问题吗？你为什么违反公共秩序？ -- Any problems? Why are you violating public order?}
### {251}{}{I just can't sleep. So I wanted to breathe the night air.}
{251}{}{我就是睡不着。所以我想呼吸夜晚的空气。 -- I just can't sleep. So I wanted to breathe the night air.}
### {252}{}{Don't talk your teeth into me. Everyone has to sleep in their holes during curfew. I'll give you two minutes to get into bed and not crawl out of there until six in the morning.}
{252}{}{别跟我说话。宵禁期间每个人都得睡在自己的洞里。我给你两分钟时间上床睡觉，直到早上六点才爬出来。 -- Don't talk your teeth into me. Everyone has to sleep in their holes during curfew. I'll give you two minutes to get into bed and not crawl out of there until six in the morning.}
### {253}{}{I will, sir. No problem, sir...}
{253}{}{我会的，先生。没问题，先生。。。 -- I will, sir. No problem, sir...}
### {254}{}{Any problems?}
{254}{}{有什么问题吗？ -- Any problems?}
### {255}{}{No, none.}
{255}{}{不，没有。 -- No, none.}
### {256}{}{I'm on patrol. If there are no good reasons, it is better not to go outside at this time. I might take you for a robber or a beast from the desert.}
{256}{}{我在巡逻。如果没有充分的理由，这个时候最好不要出门。我可能会把你当成强盗或沙漠里的野兽。 -- I'm on patrol. If there are no good reasons, it is better not to go outside at this time. I might take you for a robber or a beast from the desert.}
### {257}{}{Sorry, I'll be leaving soon.}
{257}{}{对不起，我马上就要走了。 -- Sorry, I'll be leaving soon.}
### {258}{}{You know the rules. Don't make me angry is the main one.}
{258}{}{你知道规则。不要让我生气是最重要的。 -- You know the rules. Don't make me angry is the main one.}
### {259}{}{Sorry, I'll be leaving soon.}
{259}{}{对不起，我马上就要走了。 -- Sorry, I'll be leaving soon.}
### {260}{}{You again. We've already discussed what not to do at night. So what's the problem?}
{260}{}{你又来了。我们已经讨论过晚上不该做什么了。那么问题出在哪里呢？ -- You again. We've already discussed what not to do at night. So what's the problem?}
### {261}{}{Uh, insomnia, sir. I'm sorry, sir...}
{261}{}{呃，失眠，先生。对不起，先生。。。 -- Uh, insomnia, sir. I'm sorry, sir...}
### {262}{}{Well, that's it, I was trying to be kind. It's time to teach you a lesson. You'll sit in a cell for a dozen hours and think about your behavior. Get moving. And don't try to run away from me.}
{262}{}{好吧，就是这样，我试着表现得善良。是时候教训你了。你会在牢房里坐上十几个小时，思考自己的行为。行动起来。不要试图逃离我。 -- Well, that's it, I was trying to be kind. It's time to teach you a lesson. You'll sit in a cell for a dozen hours and think about your behavior. Get moving. And don't try to run away from me.}
### {263}{}{Okay, sir, I won't resist...}
{263}{}{好吧，先生，我不会抗拒。。。 -- Okay, sir, I won't resist...}
### {264}{}{Suck it!}
{264}{}{吸吧！ -- Suck it!}
### {265}{}{I'm sick of it!}
{265}{}{我受够了！ -- I'm sick of it!}
### {266}{}{Oh, oh...}
{266}{}{哦，哦。。。 -- Oh, oh...}
### {267}{}{Suck it!}
{267}{}{吸吧！ -- Suck it!}

### {270}{}{So we met, scum. Good-I won't have to look for you. Do you think you'll just run away from the order?}
{270}{}{所以我们认识了，人渣。很好，我不用找你了。你认为你会逃避订单吗？ -- So we met, scum. Good-I won't have to look for you. Do you think you'll just run away from the order?}
### {271}{}{Sure. And you're not a hindrance to me.}
{271}{}{当然你不是我的障碍。 -- Sure. And you're not a hindrance to me.}
### {272}{}{Nothing will be hidden from the order. You're a criminal. The Brotherhood of Steel demands that you be brought to justice on the spot. Do you have the last word? No, to hell with it. You have no right to...}
{272}{}{订单中不会隐藏任何内容。你是个罪犯。钢铁兄弟会要求当场将你绳之以法。你知道最后一句话吗？不，见鬼去吧。你无权。。。 -- Nothing will be hidden from the order. You're a criminal. The Brotherhood of Steel demands that you be brought to justice on the spot. Do you have the last word? No, to hell with it. You have no right to...}
### {273}{}{Oops...}
{273}{}{哎呀。。。 -- Oops...}
### {274}{}{I don't know what you're talking about. Surely you are confusing me with someone...}
{274}{}{我不知道你在说什么。你肯定把我和某人搞混了。。。 -- I don't know what you're talking about. Surely you are confusing me with someone...}
### {275}{}{You're confusing me with someone else. I do not know about any order.}
{275}{}{你把我和别人搞混了。我不知道有什么订单。 -- You're confusing me with someone else. I do not know about any order.}
### {276}{}{Hmm, maybe. Although the description is very similar to you. Okay, for now I'll consider you a suspect.}
{276}{}{嗯，也许吧。尽管描述与您非常相似。好吧，现在我认为你是嫌疑犯。 -- Hmm, maybe. Although the description is very similar to you. Okay, for now I'll consider you a suspect.}
### {277}{}{Ugh, it's gone...}
{277}{}{啊，它不见了。。。 -- Ugh, it's gone...}

### {280}{}{Can you tell me about the city?}
{280}{}{你能告诉我这个城市的情况吗？ -- Can you tell me about the city?}
### {281}{}{Here's what I'll tell you about the city, stranger. Follow the rules and don't bother the residents. Then you can settle in if you want. In general, except for the mayor and Followers, it is better not to communicate with anyone.}
{281}{}{这是我要告诉你的关于这座城市的事情，陌生人。遵守规则，不要打扰居民。如果你愿意的话，你可以安顿下来。一般来说，除了市长和追随者，最好不要与任何人交流。 -- Here's what I'll tell you about the city, stranger. Follow the rules and don't bother the residents. Then you can settle in if you want. In general, except for the mayor and Followers, it is better not to communicate with anyone.}
### {1281}{}{Here's what I'll tell you about the city, stranger. Follow the rules and don't bother the residents. Then you can settle in if you want. And in general, except for the mayor and Followers, it is better not to communicate with anyone.}
{1281}{}{这是我要告诉你的关于这座城市的事情，陌生人。遵守规则，不要打扰居民。如果你愿意的话，你可以安顿下来。一般来说，除了市长和追随者，最好不要与任何人交流。 -- Here's what I'll tell you about the city, stranger. Follow the rules and don't bother the residents. Then you can settle in if you want. And in general, except for the mayor and Followers, it is better not to communicate with anyone.}
### {282}{}{Clear.}
{282}{}{清楚的 -- Clear.}
### {283}{}{Who's in charge here?}
{283}{}{谁是这里的负责人？ -- Who's in charge here?}
### {284}{}{The city is ruled by Mayor Alvaro. It's down the street in a big building with arches.}
{284}{}{这座城市由市长阿尔瓦罗统治。它就在街对面一栋带拱门的大建筑里。 -- The city is ruled by Mayor Alvaro. It's down the street in a big building with arches.}
### {285}{}{Clear.}
{285}{}{清楚的 -- Clear.}
### {286}{}{What are you doing?}
{286}{}{你在干什么？ -- What are you doing?}
### {287}{}{I am the commandant of this city. I am responsible for the security and enforcement of the law.}
{287}{}{我是这座城市的指挥官。我负责法律的安全和执行。 -- I am the commandant of this city. I am responsible for the security and enforcement of the law.}
### {288}{}{I see. I wish you a successful service.}
{288}{}{我明白了。我祝你服务成功。 -- I see. I wish you a successful service.}
### {289}{}{So how is security here?}
{289}{}{那么这里的安全性如何呢？ -- So how is security here?}
### {290}{}{Full order.}
{290}{}{全部订单。 -- Full order.}
### {291}{}{Really?}
{291}{}{真正地 -- Really?}
### {292}{}{I believe it willingly.}
{292}{}{我很乐意相信。 -- I believe it willingly.}
### {293}{}{The law. Security. Boring. Want to fight!}
{293}{}{法律。安全没趣的想要战斗！ -- The law. Security. Boring. Want to fight!}
### {294}{}{Hmm-m... There is one damn place where it is better not to go. I want to warn you right away so that I don't have to pull you out of there.}
{294}{}{嗯。。。有一个该死的地方最好不要去。我想马上警告你，这样我就不用把你从那里拉出来了。 -- Hmm-m... There is one damn place where it is better not to go. I want to warn you right away so that I don't have to pull you out of there.}
### {295}{}{Tell me.}
{295}{}{告诉我。 -- Tell me.}
### {296}{}{A concrete plant outside the city and a quarry near it. The plant was closed after people began to disappear there. There are various rumors, but still no one knows what happened there.}
{296}{}{城外的一家混凝土厂和附近的一个采石场。在人们开始消失后，工厂关闭了。有各种各样的传言，但仍然没有人知道那里发生了什么。 -- A concrete plant outside the city and a quarry near it. The plant was closed after people began to disappear there. There are various rumors, but still no one knows what happened there.}
### {297}{}{Clearly. Thanks for the warning.}
{297}{}{清晰地谢谢你的警告。 -- Clearly. Thanks for the warning.}

#El Gigante
### {300}{}{About the concrete plant.}
{300}{}{关于混凝土厂。 -- About the concrete plant.}
### {301}{}{Yes?}
{301}{}{对 -- Yes?}
### {302}{}{Please don't tell me any more about this creepy place.}
{302}{}{请不要再告诉我这个令人毛骨悚然的地方了。 -- Please don't tell me any more about this creepy place.}
### {303}{}{I will solve the problem for 300 caps.}
{303}{}{我会解决300顶帽子的问题。 -- I will solve the problem for 300 caps.}
### {304}{}{I have already heard these words from past mercenaries. If life is precious, then don't go to the silo.}
{304}{}{我已经从过去的雇佣军那里听到过这些话。如果生命是宝贵的，那么就不要去筒仓。 -- I have already heard these words from past mercenaries. If life is precious, then don't go to the silo.}
### {305}{}{Still, I'll try. Take me to the silo right now.}
{305}{}{尽管如此，我还是会努力的。现在带我去筒仓。 -- Still, I'll try. Take me to the silo right now.}
### {306}{}{I think I'll listen to your words.}
{306}{}{我想我会听你的话。 -- I think I'll listen to your words.}
### {307}{}{There was a monster in the factory. I managed to finish him off. The tenacious bastard got caught...}
{307}{}{工厂里有个怪物。我设法把他干掉了。那个顽强的混蛋被抓住了。。。 -- There was a monster in the factory. I managed to finish him off. The tenacious bastard got caught...}
### {308}{}{...I'll be damned! Death claw? Here? How far have these creatures made their way.}
{308}{}{…我会被诅咒的！死亡之爪？在这里这些生物已经走了多远。 -- ...I'll be damned! Death claw? Here? How far have these creatures made their way.}
### {309}{}{He's not threatening you now.}
{309}{}{他现在没有威胁你。 -- He's not threatening you now.}
### {310}{}{Great job. The whole city owes you. So be it, I will beat out a reward for you from the city treasury.}
{310}{}{干得好。整个城市都欠你。不管怎样，我会从城市金库里为你打赏的。 -- Great job. The whole city owes you. So be it, I will beat out a reward for you from the city treasury.}
### {311}{}{Thank you.}
{311}{}{非常感谢。 -- Thank you.}
### {312}{}{How do you know about the claws?}
{312}{}{你怎么知道爪子的？ -- How do you know about the claws?}
### {313}{}{I've heard a lot in school, but I've never encountered it myself. Veterans said that the claws live in the mountains in the west, where almost no one lives.}
{313}{}{我在学校里听过很多，但我自己从来没有遇到过。老兵们说，爪子生活在西部的山区，那里几乎没有人居住。 -- I've heard a lot in school, but I've never encountered it myself. Veterans said that the claws live in the mountains in the west, where almost no one lives.}
### {314}{}{Curious.}
{314}{}{好奇的 -- Curious.}
### {315}{}{I know of only one case when the claws were in the city and caused a lot of noise. It was in the Burial Ground. There was a uterus in an abandoned basement. She even laid eggs. But one brave mercenary found them and shot them, and broke their eggs. It's scary to think what would have happened if these creatures had hatched.}
{315}{}{我只知道一个案例，爪子在城市里，引起了很大的噪音。它在墓地里。在一个废弃的地下室里有一个子宫。她甚至下蛋了。但一名勇敢的雇佣兵发现了他们，开枪射杀了他们，并打碎了他们的蛋。想想如果这些生物孵化出来会发生什么，真是太可怕了。 -- I know of only one case when the claws were in the city and caused a lot of noise. It was in the Burial Ground. There was a uterus in an abandoned basement. She even laid eggs. But one brave mercenary found them and shot them, and broke their eggs. It's scary to think what would have happened if these creatures had hatched.}
### {316}{}{What a horror.}
{316}{}{真恐怖。 -- What a horror.}
### {317}{}{In general, well done, fighter. You should serve in our ranks.}
{317}{}{总的来说，干得好，战士。你应该加入我们的队伍。 -- In general, well done, fighter. You should serve in our ranks.}
### {318}{}{Bye.}
{318}{}{再见 -- Bye.}
### {319}{}{You let it slip about school. Where was it?}
{319}{}{你在学校里信口开河。它在哪里？ -- You let it slip about school. Where was it?}
### {320}{}{I am a paladin of the Brotherhood of Steel. Our local base is in Puerto Penasco, and the general staff is far away in California. That's where I learned the basics of service until I volunteered for a mission to this desert.}
{320}{}{我是钢铁兄弟会的圣骑士。我们当地的基地在佩纳斯科港，总参谋部远在加利福尼亚州。在那里我学到了服务的基本知识，直到我自愿前往沙漠执行任务。 -- I am a paladin of the Brotherhood of Steel. Our local base is in Puerto Penasco, and the general staff is far away in California. That's where I learned the basics of service until I volunteered for a mission to this desert.}
### {321}{}{Wow. I will know.}
{321}{}{哇！我会知道的。 -- Wow. I will know.}
### {322}{}{I want to help you with this problem. Will you show me this place?}
{322}{}{我想帮你解决这个问题。你能带我看看这个地方吗？ -- I want to help you with this problem. Will you show me this place?}

#Kicks
### {330}{}{I got Pinky here. They say you want him dead.}
{330}{}{我在这里找到了平基。他们说你想让他死。 -- I got Pinky here. They say you want him dead.}
### {331}{}{Chipo should be shortened for such words. I'm not bloodthirsty. But I have a mission - to ensure the safety of the city. Formally, there is no reason to exterminate the pig-rat yet. But let him give at least one reason - and he will begin his big rat journey to heaven.}
{331}{}{这样的单词应该缩写为Chipo。我不嗜血。但我有一个使命——确保城市的安全。从形式上讲，还没有理由消灭猪鼠。但让他至少给出一个理由——他将开始他的大鼠天堂之旅。 -- Chipo should be shortened for such words. I'm not bloodthirsty. But I have a mission - to ensure the safety of the city. Formally, there is no reason to exterminate the pig-rat yet. But let him give at least one reason - and he will begin his big rat journey to heaven.}
### {332}{}{Why do you dislike him so much?}
{332}{}{你为什么这么不喜欢他？ -- Why do you dislike him so much?}
### {333}{}{Now it's a harmless cub, but what will happen when it grows up and smells blood? Pig rats are aggressive predators, they have no place among people.}
{333}{}{现在它是一只无害的幼崽，但当它长大后闻到血腥味时会发生什么？猪鼠是攻击性的捕食者，它们在人类中没有立足之地。 -- Now it's a harmless cub, but what will happen when it grows up and smells blood? Pig rats are aggressive predators, they have no place among people.}
### {334}{}{Hmm.}
{334}{}{嗯。 -- Hmm.}
### {335}{}{Your position is clear. It couldn't be clearer.}
{335}{}{你的立场很明确。再清楚不过了。 -- Your position is clear. It couldn't be clearer.}
### {336}{}{What do you care about a pig-rat? Obviously, one curiosity. Then I have a suggestion. I'll pay 30 caps if you kill this beast. What do you say?}
{336}{}{你关心猪老鼠什么？显然，这是一种好奇。那我有个建议。如果你杀了这头野兽，我会付30顶帽子。你怎么说？ -- What do you care about a pig-rat? Obviously, one curiosity. Then I have a suggestion. I'll pay 30 caps if you kill this beast. What do you say?}
### {337}{}{Well, no. I don't want to hurt a teenager.}
{337}{}{不，我不想伤害一个青少年。 -- Well, no. I don't want to hurt a teenager.}
### {338}{}{Chipo is to blame! There was nothing to bring a cub into the house. Alvaro also did not have the courage and courage to put everything in its place. Sorry. It's a pity that there are only weaklings around.}
{338}{}{奇波应该受到谴责！没有什么东西可以把一只幼崽带进房子。阿尔瓦罗也没有勇气和勇气把一切都安排好。很抱歉很遗憾，周围只有弱者。 -- Chipo is to blame! There was nothing to bring a cub into the house. Alvaro also did not have the courage and courage to put everything in its place. Sorry. It's a pity that there are only weaklings around.}
### {339}{}{Bye, Commandant.}
{339}{}{再见，指挥官。 -- Bye, Commandant.}
### {340}{}{It won't take long. Count off the caps, buddy.}
{340}{}{这不会花很长时间。数帽子，伙计。 -- It won't take long. Count off the caps, buddy.}
### {341}{}{I'm counting on you.}
{341}{}{我指望着你。 -- I'm counting on you.}
### {342}{}{See you, Commandant.}
{342}{}{再见，指挥官。 -- See you, Commandant.}
### {343}{}{That pig-rat isn't breathing anymore.}
{343}{}{那只猪老鼠已经没有呼吸了。 -- That pig-rat isn't breathing anymore.}
### {344}{}{Chipo must have been very upset. Sorry for the kid, but it's his own fault. This loss will serve him as a good lesson.}
{344}{}{Chipo一定很沮丧。对不起孩子，但这是他自己的错。这次失利将给他一个很好的教训。 -- Chipo must have been very upset. Sorry for the kid, but it's his own fault. This loss will serve him as a good lesson.}
### {345}{}{Whatever you say.}
{345}{}{不管你说什么。 -- Whatever you say.}
### {346}{}{Make sure that the conclusions from the lesson are correct.}
{346}{}{确保这节课的结论是正确的。 -- Make sure that the conclusions from the lesson are correct.}
### {347}{}{You have a good grip. Maybe you'll come in handy again. So here are 30 caps, as I promised.}
{347}{}{你抓地很好。也许你会再次派上用场。正如我所承诺的，这里有30场比赛。 -- You have a good grip. Maybe you'll come in handy again. So here are 30 caps, as I promised.}
### {348}{}{See you later, Commandant.}
{348}{}{回头见，指挥官。 -- See you later, Commandant.}

### {350}{}{Listen, I really need to know if Tin-Tan has been here?}
{350}{}{听着，我真的想知道田是否来过这里？ -- Listen, I really need to know if Tin-Tan has been here?}
### {351}{}{Tin-Tan? Sounds like a nickname. Is there a real name?}
{351}{}{田？听起来像个昵称。有真名吗？ -- Tin-Tan? Sounds like a nickname. Is there a real name?}
### {352}{}{Herman Genaro Cipriano Gomez Valdez y Castillo. He traveled by stagecoach from Phoenix to the Platform.}
{352}{}{Herman Genaro Cipriano Gomez Valdez y Castillo。他乘马车从凤凰城到站台。 -- Herman Genaro Cipriano Gomez Valdez y Castillo. He traveled by stagecoach from Phoenix to the Platform.}
### {353}{}{Now I'll look at the migration log... Wait a minute. I have no record of him visiting Casa Nueva.}
{353}{}{现在我将查看迁移日志。。。等一下。我没有他访问努瓦之家的记录。 -- Now I'll look at the migration log... Wait a minute. I have no record of him visiting Casa Nueva.}
### {354}{}{What about the Sonora Express stagecoach?}
{354}{}{Sonora Express驿站马车怎么样？ -- What about the Sonora Express stagecoach?}
### {355}{}{Wait a minute... Yes, there is that name here, but... I have it recorded that the whole stagecoach died at the hands of highway robbers, never reaching us.}
{355}{}{等一下。。。是的，这里有这个名字，但是。。。我有记录说，整辆马车都死在了高速公路劫匪手中，从来没有到达我们身边。 -- Wait a minute... Yes, there is that name here, but... I have it recorded that the whole stagecoach died at the hands of highway robbers, never reaching us.}
### {356}{}{Well, not fate. Thanks, Cap.}
{356}{}{不是命运。谢谢，上尉。 -- Well, not fate. Thanks, Cap.}
