### {100}{}{+}
{100}{}{+ -- +}
### {101}{}{-}
{101}{}{- -- -}

#Using hands
### {110}{}{Without energy, the motorcycle will not go anywhere.}
{110}{}{没有能量，摩托车哪儿也跑不了。 -- Without energy, the motorcycle will not go anywhere.}
### {111}{}{Damn, I need to charge the power supply.}
{111}{}{该死，我需要给电源充电。 -- Damn, I need to charge the power supply.}
### {112}{}{The bike won't start. The on-board computer is locked and requires an access key.}
{112}{}{自行车发动不了。车载计算机已锁定，需要一把访问密钥。 -- The bike won't start. The on-board computer is locked and requires an access key.}
### {113}{}{Hmm, it seems that a key is needed here.}
{113}{}{嗯，这里好像需要一把钥匙。 -- Hmm, it seems that a key is needed here.}
### {114}{}{Now is not the right time for a remote trip.}
{114}{}{现在不是远程旅行的合适时机。 -- Now is not the right time for a remote trip.}
### {115}{}{I have unfinished business.}
{115}{}{我还有未竟之事。 -- I have unfinished business.}
### {116}{}{You stole a bike from bandits! I don't think they'll like it.}
{116}{}{你从土匪那里偷了一辆自行车！我想他们不会喜欢的。 -- You stole a bike from bandits! I don't think they'll like it.}
### {117}{}{The motorcycle can accommodate only two passengers.}
{117}{}{摩托车只能容纳两名乘客。 -- The motorcycle can accommodate only two passengers.}

#Using items
### {200}{}{Access has been obtained. Now the bike is ready to ride.}
{200}{}{已获得访问权限。现在自行车已经准备好了。 -- Access has been obtained. Now the bike is ready to ride.}
### {201}{}{It doesn't fit.}
{201}{}{它不合身。 -- It doesn't fit.}
### {202}{}{This transport is charged from another energy carrier.}
{202}{}{这种传输是由另一种能量载体充电的。 -- This transport is charged from another energy carrier.}
### {203}{}{The motorcycle does not need lubrication yet.}
{203}{}{摩托车还不需要润滑。 -- The motorcycle does not need lubrication yet.}
### {204}{}{The motorcycle does not need to change parts yet.}
{204}{}{摩托车还不需要更换零件。 -- The motorcycle does not need to change parts yet.}
### {205}{}{The onboard computer does not need repair yet.}
{205}{}{车载电脑还不需要修理。 -- The onboard computer does not need repair yet.}
### {206}{}{This skull will serve as a great decoration for your steering wheel. And remind others that you are not to be trifled with.}
{206}{}{这个头骨将成为你方向盘的绝佳装饰。并提醒他人，你不可被轻视。 -- This skull will serve as a great decoration for your steering wheel. And remind others that you are not to be trifled with.}
### {207}{}{You can't do this until the motorcycle belongs to you.}
{207}{}{除非摩托车属于你，否则你不能这样做。 -- You can't do this until the motorcycle belongs to you.}
### {208}{}{The steering wheel is already decorated with one skull.}
{208}{}{方向盘上已经装饰了一个头骨。 -- The steering wheel is already decorated with one skull.}
### {209}{}{You have restored the blind headlight. Now she will light your way.}
{209}{}{你已经修复了百叶窗前照灯。现在她会照亮你的路。 -- You have restored the blind headlight. Now she will light your way.}
### {210}{}{This motorcycle has all the headlights in working order.}
{210}{}{这辆摩托车的前灯都正常工作。 -- This motorcycle has all the headlights in working order.}
### {211}{}{This applies more to the luggage compartment.}
{211}{}{这更适用于行李箱。 -- This applies more to the luggage compartment.}

#Using skills
### {300}{}{There's nothing to hack here.}
{300}{}{这里没有什么可破解的。 -- There's nothing to hack here.}
### {301}{}{The onboard computer is already under your control.}
{301}{}{车载电脑已经在你的控制之下。 -- The onboard computer is already under your control.}
### {302}{}{It's too complicated for you. Try to find the access key.}
{302}{}{这对你来说太复杂了。尝试查找访问密钥。 -- It's too complicated for you. Try to find the access key.}
### {303}{}{There is nothing to repair here.}
{303}{}{这里没有什么可修的。 -- There is nothing to repair here.}
### {304}{}{There is nothing to repair here. However, you haven't examined the trunk yet.}
{304}{}{这里没有什么可修的。然而，你还没有检查行李箱。 -- There is nothing to repair here. However, you haven't examined the trunk yet.}
### {305}{}{You cannot repair this bike until it?s yours.}
{305}{}{你不能修理这辆自行车?是你的。 -- You cannot repair this bike until it?s yours.}
