### {100}{}{Here is a slum dweller.}
{100}{}{这是一个贫民窟的居民。 -- Here is a slum dweller.}
### {101}{}{You see a resident of the local slums.}
{101}{}{你看到一个当地贫民窟的居民。 -- You see a resident of the local slums.}
### {102}{}{Some bastard killed her!}
{102}{}{有个混蛋杀了她！ -- Some bastard killed her!}
### {103}{}{I don't mind talking, but my stomach is rumbling. Well, you know.}
{103}{}{我不介意说话，但我的肚子在咕咕叫。嗯，你知道。 -- I don't mind talking, but my stomach is rumbling. Well, you know.}
### {104}{}{Thank you for the meal, se?or.}
{104}{}{谢谢你的饭菜，塞诺。 -- Thank you for the meal, se?or.}
### {1104}{}{Thank you for the food, se?ora.}
{1104}{}{谢谢你的食物，塞诺拉。 -- Thank you for the food, se?ora.}

### {110}{}{Are you all right?}
{110}{}{你还好吗？ -- Are you all right?}
### {111}{}{What's up?}
{111}{}{怎么了？ -- What's up?}
### {112}{}{And everything is still the same with us.}
{112}{}{我们的一切都一样。 -- And everything is still the same with us.}
### {113}{}{Come again if you want.}
{113}{}{如果你想再来的话。 -- Come again if you want.}

### {200}{}{Hi. What can I do for you?}
{200}{}{你好我能为你做什么？ -- Hi. What can I do for you?}
### {201}{}{You? Probably nothing.}
{201}{}{你可能什么都没有。 -- You? Probably nothing.}

### {210}{}{Who are you?}
{210}{}{你是谁？ -- Who are you?}
### {211}{}{I'm Fred. My wife and I recently moved from the desert, where we raised a small herd of Brahmins. Or rather, they tried to grow it. In the end, our ranch collapsed due to drought and bandit raids. And so we decided to try our luck in the big city.}
{211}{}{我是弗雷德。我和妻子最近从沙漠搬来，在那里我们养育了一小群婆罗门。或者更确切地说，他们试图种植它。最后，由于干旱和土匪袭击，我们的牧场倒塌了。所以我们决定在大城市碰碰运气。 -- I'm Fred. My wife and I recently moved from the desert, where we raised a small herd of Brahmins. Or rather, they tried to grow it. In the end, our ranch collapsed due to drought and bandit raids. And so we decided to try our luck in the big city.}
### {212}{}{Bye, Fred.}
{212}{}{再见，弗雷德。 -- Bye, Fred.}

### {220}{}{Why do you live in this old building?}
{220}{}{你为什么住在这幢旧楼里？ -- Why do you live in this old building?}
### {221}{}{It's not that bad. Better than living on the street. Vernon made an agreement with one gang to protect the area. But to live here, you have to pay tribute or work out your place in some other way.}
{221}{}{没那么糟糕。比住在街上要好。弗农与一伙人达成了保护该地区的协议。但要在这里生活，你必须表达敬意，或者以其他方式找到自己的位置。 -- It's not that bad. Better than living on the street. Vernon made an agreement with one gang to protect the area. But to live here, you have to pay tribute or work out your place in some other way.}
### {222}{}{Who is Vernon?}
{222}{}{弗农是谁？ -- Who is Vernon?}
### {223}{}{The manager of the community house. His office is on the right down the corridor.}
{223}{}{社区住宅的经理。他的办公室在走廊的右边。 -- The manager of the community house. His office is on the right down the corridor.}
### {224}{}{What kind of gang?}
{224}{}{什么帮派？ -- What kind of gang?}
### {225}{}{Some muddy types in leather jackets and with nasty hairstyles. They're holed up in an old building in a nearby neighborhood. But it's better not to meddle with them.}
{225}{}{一些穿着皮夹克、发型恶劣的泥质人。他们躲在附近街区的一栋旧楼里。但最好不要干涉他们。 -- Some muddy types in leather jackets and with nasty hairstyles. They're holed up in an old building in a nearby neighborhood. But it's better not to meddle with them.}
### {226}{}{Clearly. Bye.}
{226}{}{清晰地再见 -- Clearly. Bye.}
### {227}{}{Remind me, what's your name?}
{227}{}{提醒我，你叫什么名字？ -- Remind me, what's your name?}
### {228}{}{And who are you?}
{228}{}{你是谁？ -- And who are you?}

### {230}{}{What can you tell us about this area?}
{230}{}{你能告诉我们这个地区的情况吗？ -- What can you tell us about this area?}
### {231}{}{Many believe that this is the worst residential area in the city. But to Rednecks like us, even this seems like a great achievement.}
{231}{}{许多人认为这是该市最糟糕的住宅区。但对于像我们这样的红脖子人来说，即使是这似乎也是一个伟大的成就。 -- Many believe that this is the worst residential area in the city. But to Rednecks like us, even this seems like a great achievement.}
