### {100}{}{Badie is in front of you.}
{100}{}{巴迪在你面前。 -- Badie is in front of you.}
### {101}{}{You see an ordinary beggar, incapable of anything. It's amazing that he's still alive.}
{101}{}{你看到一个普通的乞丐，什么都不会。他还活着真是太神奇了。 -- You see an ordinary beggar, incapable of anything. It's amazing that he's still alive.}
### {102}{}{Hello, partner. How are you?}
{102}{}{你好，合伙人。你好吗 -- Hello, partner. How are you?}

### {200}{}{It's here. Be careful, there must be robots inside. If you turn them off, then all the bottlecaps will be ours.}
{200}{}{它在这里。小心，里面一定有机器人。如果你关掉它们，那么所有的瓶子都将是我们的。 -- It's here. Be careful, there must be robots inside. If you turn them off, then all the bottlecaps will be ours.}
### {201}{}{Then let's not waste time. Wait here.}
{201}{}{那我们就不要浪费时间了。在这里等候。 -- Then let's not waste time. Wait here.}
### {202}{}{I know without you.}
{202}{}{我知道没有你。 -- I know without you.}
### {203}{}{I need to know about this place first.}
{203}{}{我需要先了解一下这个地方。 -- I need to know about this place first.}

### {210}{}{Don't stand here too long.}
{210}{}{不要在这里站太久。 -- Don't stand here too long.}
### {211}{}{Wait here.}
{211}{}{在这里等候。 -- Wait here.}
### {212}{}{Night is coming soon. Let's hurry up, okay?}
{212}{}{夜幕即将降临。我们快点，好吗？ -- Night is coming soon. Let's hurry up, okay?}
### {220}{}{What kind of place is this anyway?}
{220}{}{这到底是个什么地方？ -- What kind of place is this anyway?}

### {221}{}{Pre-war warehouse of Nuka-Cola. Apparently, the drink was stored here and then taken to the shops. The factory itself, where it was bottled, was destroyed by a nuclear explosion.}
{221}{}{努卡可乐的战前仓库。显然，这些饮料被存放在这里，然后被带到商店。装瓶子的工厂本身被核爆炸摧毁了。 -- Pre-war warehouse of Nuka-Cola. Apparently, the drink was stored here and then taken to the shops. The factory itself, where it was bottled, was destroyed by a nuclear explosion.}
### {222}{}{It's amazing why this place hasn't been looted by scavengers yet?}
{222}{}{令人惊讶的是，为什么这个地方还没有被拾荒者洗劫一空？ -- It's amazing why this place hasn't been looted by scavengers yet?}
### {223}{}{It's hard to get here because of the surrounding ruins, so many people just don't know about it. In addition, there is a nuclear explosion zone nearby, which scares many away. And, of course, the damn robots.}
{223}{}{由于周围都是废墟，很难到达这里，所以很多人都不知道。此外，附近还有一个核爆炸区，这让很多人望而却步。当然还有那些该死的机器人。 -- It's hard to get here because of the surrounding ruins, so many people just don't know about it. In addition, there is a nuclear explosion zone nearby, which scares many away. And, of course, the damn robots.}
### {224}{}{Any ideas on how to disable robots?}
{224}{}{关于如何禁用机器人有什么想法吗？ -- Any ideas on how to disable robots?}
### {225}{}{I thought you'd take it on yourself. There's probably a switch somewhere inside, or something. I don't know anything about technology. Especially pre-war. No one understands it at all, except the ministers of the Cathedral.}
{225}{}{我以为你会自己承担的。里面可能有个开关什么的。我对技术一无所知。尤其是战前。除了大教堂的牧师们，没有人能理解它。 -- I thought you'd take it on yourself. There's probably a switch somewhere inside, or something. I don't know anything about technology. Especially pre-war. No one understands it at all, except the ministers of the Cathedral.}
### {226}{}{Remind me, what are we looking for?}
{226}{}{提醒我，我们在找什么？ -- Remind me, what are we looking for?}
### {227}{}{bottlecaps! Lots and lots of bottle caps.}
{227}{}{装瓶！好多好多瓶盖。 -- bottlecaps! Lots and lots of bottle caps.}
### {228}{}{Clear.}
{228}{}{清楚的 -- Clear.}
### {229}{}{I'll be back soon.}
{229}{}{我很快就会回来。 -- I'll be back soon.}

### {250}{}{Here are all the bottlecaps that have been preserved in stock.}
{250}{}{这是所有保存在库存中的瓶子。 -- Here are all the bottlecaps that have been preserved in stock.}
### {251}{}{A full box? Hell, it's a fortune! That's luck. We are now richer than most of the residents of the city, can you imagine?}
{251}{}{一整盒？见鬼，这是一笔财富！这是运气。我们现在比这个城市的大多数居民都富有，你能想象吗？ -- A full box? Hell, it's a fortune! That's luck. We are now richer than most of the residents of the city, can you imagine?}
### {252}{}{Not so fast. Pay back the casino's debt first.}
{252}{}{没那么快。先还赌场的债。 -- Not so fast. Pay back the casino's debt first.}
### {253}{}{Oh, yes. Uh, right. In my joy, I completely forgot. Here you go.}
{253}{}{哦，是的。嗯，对。在我的喜悦中，我完全忘记了。给你。 -- Oh, yes. Uh, right. In my joy, I completely forgot. Here you go.}
### {254}{}{Great. Now give me my share - half of what's left.}
{254}{}{太棒了现在把剩下的一半给我。 -- Great. Now give me my share - half of what's left.}
### {255}{}{Ugh, it turned out to be less than I expected. The remaining caps are barely enough for me to pay off my rent and other debts. And I will find myself with nothing again.}
{255}{}{啊，结果比我预想的要少。剩下的上限几乎不足以让我还清房租和其他债务。我会发现自己一无所有。 -- Ugh, it turned out to be less than I expected. The remaining caps are barely enough for me to pay off my rent and other debts. And I will find myself with nothing again.}
### {256}{}{That's fair enough. There was nothing to bring yourself to such a state. And now it's time to go back to the city. Later.}
{256}{}{这很公平。没有什么能把你自己带到这样的状态。现在是时候回到城市了。后来 -- That's fair enough. There was nothing to bring yourself to such a state. And now it's time to go back to the city. Later.}
### {257}{}{You know, I've changed my mind. I'm taking ALL the caps for myself.}
{257}{}{你知道，我改变了主意。我把所有的帽子都给自己。 -- You know, I've changed my mind. I'm taking ALL the caps for myself.}
### {1257}{}{You know, I've changed my mind. I'm taking ALL the caps for myself.}
{1257}{}{你知道，我改变了主意。我把所有的帽子都给自己。 -- You know, I've changed my mind. I'm taking ALL the caps for myself.}
### {258}{}{No! You can't do that! We're partners, I showed you this place... Hell, someday... Someday I'll earn a lot of caps and hire mercenaries on your head. And then I'll play football with it. You'll remember this day again.}
{258}{}{不你不能那样做！我们是合作伙伴，我带你参观了这个地方。。。见鬼，总有一天。。。总有一天，我会赚很多帽子，在你头上雇佣雇佣兵。然后我会用它踢足球。你会再次记住这一天的。 -- No! You can't do that! We're partners, I showed you this place... Hell, someday... Someday I'll earn a lot of caps and hire mercenaries on your head. And then I'll play football with it. You'll remember this day again.}
### {259}{}{Well, well. Goodbye, loser.}
{259}{}{嗯，嗯。再见，失败者。 -- Well, well. Goodbye, loser.}
### {260}{}{In that case, you leave me no choice -I'll kill you right now.}
{260}{}{那样的话，你让我别无选择——我现在就杀了你。 -- In that case, you leave me no choice -I'll kill you right now.}
