### {100}{}{This is Veronica.}
{100}{}{这是维罗妮卡。 -- This is Veronica.}
### {101}{}{You see quite an attractive singer.}
{101}{}{你看到一个很有魅力的歌手。 -- You see quite an attractive singer.}
### {102}{}{Now the singer can't communicate with you.}
{102}{}{现在歌手不能和你交流了。 -- Now the singer can't communicate with you.}

#Song 1 "Nature Boy" 1947, translated from the Internet
### {110}{}{*Once upon a time there was a boy.*}
{110}{}{*从前有一个男孩* -- *Once upon a time there was a boy.*}
### {111}{}{*A very strange and enchanted boy.*}
{111}{}{*一个非常奇怪和着迷的男孩* -- *A very strange and enchanted boy.*}
### {112}{}{*They say he wandered far, far away.*}
{112}{}{*他们说他走得很远* -- *They say he wandered far, far away.*}
### {113}{}{*On the other side of land and sea.*}
{113}{}{*在陆地和海洋的另一边* -- *On the other side of land and sea.*}
### {114}{}{*A little shy and sad-eyed,*}
{114}{}{*有点害羞和悲伤的眼睛* -- *A little shy and sad-eyed,*}
### {115}{}{*But he was very wise.*}
{115}{}{*但他非常聪明* -- *But he was very wise.*}
### {116}{}{*And then one day, one magical day, *}
{116}{}{*然后有一天，一个神奇的日子* -- *And then one day, one magical day, *}
### {117}{}{*He was walking my way.*}
{117}{}{*他正朝我走来* -- *He was walking my way.*}
### {118}{}{*And we talked about different things,*}
{118}{}{*我们讨论了不同的事情* -- *And we talked about different things,*}
### {119}{}{*Fools and kings,*}
{119}{}{*傻瓜和国王* -- *Fools and kings,*}
### {120}{}{*And this is what he said to me:*}
{120}{}{*这是他对我说的：* -- *And this is what he said to me:*}
### {121}{}{*" The greatest thing you can know,*}
{121}{}{*“你能知道的最伟大的事情* -- *" The greatest thing you can know,*}
### {122}{}{*It's just loving and being loved in return."*}
{122}{}{*这只是爱和被爱的回报。“* -- *It's just loving and being loved in return."*}

#Song 2 "Mexicali Rose" of 1923, free translation by A.V. Poshelyuzhin
### {150}{}{*Mexicali Rose, don't cry.*}
{150}{}{*墨西卡利玫瑰，别哭* -- *Mexicali Rose, don't cry.*}
### {151}{}{*I'll come back to you on a sunny day.*}
{151}{}{*我会在一个阳光明媚的日子回来找你* -- *I'll come back to you on a sunny day.*}
### {152}{}{*I'll miss you, remember that every night.*}
{152}{}{*我会想念你的，记住每一个晚上* -- *I'll miss you, remember that every night.*}
### {153}{}{*Every hour while I'm gone.*}
{153}{}{*我离开的每一个小时* -- *Every hour while I'm gone.*}
### {154}{}{*Dry your brown eyes and smile.*}
{154}{}{*擦干棕色的眼睛，微笑* -- *Dry your brown eyes and smile.*}
### {155}{}{*Banish the tears and don't sigh.*}
{155}{}{*忍住眼泪，不要叹息* -- *Banish the tears and don't sigh.*}
### {156}{}{*Kiss me again and hug me.*}
{156}{}{*再次吻我，拥抱我* -- *Kiss me again and hug me.*}
### {157}{}{*Mexicali Rose, goodbye.*}
{157}{}{*墨西卡利玫瑰，再见* -- *Mexicali Rose, goodbye.*}

#Dialog
### {200}{}{Hey, hi.}
{200}{}{嗨，嗨。 -- Hey, hi.}
### {201}{}{Bye.}
{201}{}{再见 -- Bye.}

### {210}{}{Hey, hi.}
{210}{}{嗨，嗨。 -- Hey, hi.}
### {211}{}{Bye.}
{211}{}{再见 -- Bye.}
