### {100}{}{Here is a croupier.}
{100}{}{这是一个赌台。 -- Here is a croupier.}
### {101}{}{You see a neat man in a suit. For a while you watch in fascination how deftly he shuffles the cards.}
{101}{}{你看到一个穿着西装的整洁男人。有一段时间，你会着迷地看着他如何灵巧地洗牌。 -- You see a neat man in a suit. For a while you watch in fascination how deftly he shuffles the cards.}
### {102}{}{Uh, I'm afraid you won't be able to hold the cards in THIS...}
{102}{}{呃，恐怕你拿不住这张牌了。。。 -- Uh, I'm afraid you won't be able to hold the cards in THIS...}
### {103}{}{Sorry, sir, I'm forbidden to serve you.}
{103}{}{对不起，先生，我被禁止为您服务。 -- Sorry, sir, I'm forbidden to serve you.}
### {1103}{}{Sorry, ma'am, But I'm not allowed to serve you.}
{1103}{}{对不起，女士，但我不能为您服务。 -- Sorry, ma'am, But I'm not allowed to serve you.}

#Acquaintance
### {200}{}{(There is a table in front of you for playing card games, and at the table a neat man with a serious look deftly shuffles a deck of cards.) Do you play blackjack?}
{200}{}{（你面前有一张玩纸牌游戏的桌子，桌子旁一个神情严肃的整洁男子灵巧地洗牌。）你玩21点吗？ -- (There is a table in front of you for playing card games, and at the table a neat man with a serious look deftly shuffles a deck of cards.) Do you play blackjack?}
### {201}{}{Not today.}
{201}{}{今天不行。 -- Not today.}
### {202}{}{No, I don't know the rules.}
{202}{}{不，我不知道规则。 -- No, I don't know the rules.}
### {203}{}{The call is accepted. But first explain the rules.}
{203}{}{电话已被接受。但首先要解释一下规则。 -- The call is accepted. But first explain the rules.}
### {204}{}{For the most part, this is a kind of blackjack. You need to collect the sum of 21 points with the minimum number of cards with nuclear bombs. Having collected the right number, you can "bomb" the deck. This game requires a little more intelligence than roulette or a slot machine. But the stakes are higher here, too. If, of course, you are willing to take the risk.}
{204}{}{在大多数情况下，这是一种21点。你需要用最少的核弹牌数量来收集21分的总和。收集到正确的号码后，你就可以“轰炸”甲板了。这个游戏比轮盘赌或老虎机需要更多的智力。但这里的风险也更高。当然，如果你愿意冒险的话。 -- For the most part, this is a kind of blackjack. You need to collect the sum of 21 points with the minimum number of cards with nuclear bombs. Having collected the right number, you can "bomb" the deck. This game requires a little more intelligence than roulette or a slot machine. But the stakes are higher here, too. If, of course, you are willing to take the risk.}
### {205}{}{Undoubtedly.}
{205}{}{毋庸置疑地 -- Undoubtedly.}
### {206}{}{Are you playing?}
{206}{}{你在玩吗？ -- Are you playing?}
### {207}{}{Yes.}
{207}{}{对 -- Yes.}
### {208}{}{No.}
{208}{}{不 -- No.}

#Bids
### {210}{}{A new batch. Place your bets.}
{210}{}{新的一批。下注。 -- A new batch. Place your bets.}
### {211}{}{ chips)}
{211}{}{芯片） --  chips)}
### {212}{}{I'm not playing.}
{212}{}{我不玩了。 -- I'm not playing.}
### {213}{}{I would love to join, but I don't have any chips.}
{213}{}{我很想加入，但我没有筹码。 -- I would love to join, but I don't have any chips.}
### {1213}{}{I would love to join, but I don't have any chips.}
{1213}{}{我很想加入，但我没有筹码。 -- I would love to join, but I don't have any chips.}
### {214}{}{My bet is 10 chips.}
{214}{}{我的赌注是10个筹码。 -- My bet is 10 chips.}
### {215}{}{My bet is 20 chips.}
{215}{}{我的赌注是20个筹码。 -- My bet is 20 chips.}
### {216}{}{My bet is 30 chips.}
{216}{}{我的赌注是30个筹码。 -- My bet is 30 chips.}
### {217}{}{My bet is 40 chips.}
{217}{}{我的赌注是40个筹码。 -- My bet is 40 chips.}
### {218}{}{Bets are accepted. I'm starting the distribution.}
{218}{}{接受赌注。我正在开始分发。 -- Bets are accepted. I'm starting the distribution.}
### {219}{}{Start.}
{219}{}{开始 -- Start.}

### {220}{}{Remind me, what was the last bill?}
{220}{}{提醒我，最后一张账单是多少？ -- Remind me, what was the last bill?}
### {221}{}{Account }
{221}{}{账户 -- Account }
### {222}{}{ k }
{222}{}{k --  k }
### {223}{}{in your favor.}
{223}{}{对你有利。 -- in your favor.}
### {224}{}{in favor of the casino.}
{224}{}{支持赌场。 -- in favor of the casino.}
### {225}{}{Good. Let's continue.}
{225}{}{好的让我们继续。 -- Good. Let's continue.}
### {226}{}{My bet is 50 chips.}
{226}{}{我的赌注是50个筹码。 -- My bet is 50 chips.}

### {230}{}{(The dealer takes out two cards and puts them face down. Then he turns one of them over, showing the nominal value in }
{230}{}{（发牌人拿出两张牌，脸朝下放。然后他把其中一张翻过来，在里面显示面值 -- (The dealer takes out two cards and puts them face down. Then he turns one of them over, showing the nominal value in }
### {231}{}{ points)}
{231}{}{点） --  points)}
### {232}{}{Me.}
{232}{}{我 -- Me.}
### {233}{}{(You got two face value cards }
{233}{}{（你有两张面值卡 -- (You got two face value cards }
### {234}{}{ points)}
{234}{}{点） --  points)}
### {235}{}{[Next]}
{235}{}{[下一个 -- Next]}
### {236}{}{(On your hand are cards worth }
{236}{}{（你手里的牌值多少钱 -- (On your hand are cards worth }
### {237}{}{ points. The dealer has open cards worth }
{237}{}{点。经销商有价值的未结牌 --  points. The dealer has open cards worth }
### {238}{}{ points.) Your actions?}
{238}{}{点。）你的行为？ --  points.) Your actions?}

### {240}{}{I give up.}
{240}{}{我放弃了。 -- I give up.}
### {241}{}{The first player leaves the game. Half of the bet burns out.}
{241}{}{第一个玩家离开游戏。一半的赌注烧光了。 -- The first player leaves the game. Half of the bet burns out.}
### {242}{}{Gentlemen, I will leave you.}
{242}{}{先生们，我将离开你们。 -- Gentlemen, I will leave you.}
### {243}{}{Double the bet.}
{243}{}{加倍下注。 -- Double the bet.}
### {244}{}{The bid is doubled. Let me remind you that you can raise the bet only once per game.}
{244}{}{出价加倍。让我提醒你，你每场比赛只能下注一次。 -- The bid is doubled. Let me remind you that you can raise the bet only once per game.}
### {245}{}{The bid has been doubled.}
{245}{}{出价增加了一倍。 -- The bid has been doubled.}
### {246}{}{[Continue playing]}
{246}{}{[继续播放 -- Continue playing]}
### {247}{}{Pass.}
{247}{}{通过 -- Pass.}
### {248}{}{The first player skips a card. We continue the distribution ...}
{248}{}{第一个玩家跳过一张牌。我们继续分发。。。 -- The first player skips a card. We continue the distribution ...}
### {249}{}{[Continue playing]}
{249}{}{[继续播放 -- Continue playing]}
### {250}{}{More.}
{250}{}{更多 -- More.}
### {251}{}{The first player takes a card...}
{251}{}{第一个玩家拿一张牌。。。 -- The first player takes a card...}
### {252}{}{[Continue playing]}
{252}{}{[继续播放 -- Continue playing]}

### {260}{}{First player: Nuclear Jack! Would you like to play more?}
{260}{}{第一个玩家：核杰克！你想再玩一次吗？ -- First player: Nuclear Jack! Would you like to play more?}
### {261}{}{No thanks.}
{261}{}{不用了，谢谢。 -- No thanks.}
### {262}{}{Oh yes, I want to play more.}
{262}{}{哦，是的，我想多打球。 -- Oh yes, I want to play more.}
### {263}{}{Casino: Blackjack. Your bet is burning out. Do you want to recoup?}
{263}{}{赌场：21点。你的赌注正在耗尽。你想收回吗？ -- Casino: Blackjack. Your bet is burning out. Do you want to recoup?}
### {264}{}{Yes, I just need to recoup.}
{264}{}{是的，我只是需要弥补。 -- Yes, I just need to recoup.}
### {265}{}{Well, no.}
{265}{}{嗯，没有。 -- Well, no.}
### {266}{}{First player: defeat. Your bet is burning out. Do you want to recoup?}
{266}{}{第一名玩家：失败。你的赌注正在耗尽。你想收回吗？ -- First player: defeat. Your bet is burning out. Do you want to recoup?}
### {267}{}{Casino: defeat. Would you like to continue?}
{267}{}{赌场：失败。你想继续吗？ -- Casino: defeat. Would you like to continue?}
### {268}{}{Draw. The players stay with their own. Do you want to continue?}
{268}{}{画球员们和他们自己待在一起。是否要继续？ -- Draw. The players stay with their own. Do you want to continue?}
### {269}{}{The card limit is exhausted.}
{269}{}{卡的限制已用完。 -- The card limit is exhausted.}
