### {100}{}{Here is a pusher.}
{100}{}{这是一个推手。 -- Here is a pusher.}
### {101}{}{You see a drug dealer, or something like that.}
{101}{}{你看到一个毒贩，或者类似的东西。 -- You see a drug dealer, or something like that.}
### {102}{}{Pusher raised the prices of his goods.}
{102}{}{Pusher提高了商品的价格。 -- Pusher raised the prices of his goods.}
### {103}{}{You have received a discount on pusher products.}
{103}{}{您已收到促销产品的折扣。 -- You have received a discount on pusher products.}
### {104}{}{Be careful with that, baby. You're looking for serious trouble.}
{104}{}{小心点，宝贝。你在找严重的麻烦。 -- Be careful with that, baby. You're looking for serious trouble.}

#First meeting
### {200}{}{Hey, man, you look like a million. Don't you want to hang out in this city before Fortune turns around?}
{200}{}{嘿，伙计，你看起来像个百万富翁。难道你不想在命运逆转之前在这个城市闲逛吗？ -- Hey, man, you look like a million. Don't you want to hang out in this city before Fortune turns around?}
### {1200}{}{Hey, baby, you look like a million. Don't you want to hang out in this city before Fortune turns backwards?}
{1200}{}{嘿，宝贝，你看起来像个百万富翁。难道你不想在命运逆转之前在这个城市闲逛吗？ -- Hey, baby, you look like a million. Don't you want to hang out in this city before Fortune turns backwards?}
### {201}{}{What exactly are you suggesting?}
{201}{}{你到底在暗示什么？ -- What exactly are you suggesting?}
### {202}{}{Different kinds of pleasures. Just take this pill and you will get such a buzz that no gambling game gives. I know what I'm talking about. I checked it on myself.}
{202}{}{不同种类的快乐。只要吃这种药，你就会得到任何赌博游戏都不会给你带来的兴奋。我知道我在说什么。我自己检查了一下。 -- Different kinds of pleasures. Just take this pill and you will get such a buzz that no gambling game gives. I know what I'm talking about. I checked it on myself.}
### {203}{}{So are you selling drugs or something like that?}
{203}{}{你是在卖毒品还是类似的东西？ -- So are you selling drugs or something like that?}
### {204}{}{I doubt you can offer me anything worthwhile.}
{204}{}{我怀疑你能给我任何有价值的东西。 -- I doubt you can offer me anything worthwhile.}
### {205}{}{Of course, of course, whatever you say, man. But trust me, you're giving up the last pleasure in this lousy world.}
{205}{}{当然，当然，不管你说什么，伙计。但相信我，你正在放弃这个糟糕世界的最后乐趣。 -- Of course, of course, whatever you say, man. But trust me, you're giving up the last pleasure in this lousy world.}
### {206}{}{Pleasure? Come on, come on, that's where we should have started.}
{206}{}{高兴来吧，来吧，那是我们应该开始的地方。 -- Pleasure? Come on, come on, that's where we should have started.}
### {207}{}{What are you trying to sell me?}
{207}{}{你想卖给我什么？ -- What are you trying to sell me?}
### {208}{}{I don't know what you're talking about. I have absolutely pure stimpacks and mentats. Who would want to call it a drug? The question is how well you will use it. But this is already (winks) none of my business.}
{208}{}{我不知道你在说什么。我有绝对纯粹的刺激和心理战。谁会愿意称之为毒品？问题是你会用得多好。但这已经（眨眼）不关我的事了。 -- I don't know what you're talking about. I have absolutely pure stimpacks and mentats. Who would want to call it a drug? The question is how well you will use it. But this is already (winks) none of my business.}
### {209}{}{Everything is clear with you.}
{209}{}{你一切都很清楚。 -- Everything is clear with you.}

#Repeat dialog
### {210}{}{Hi. Do you need something?}
{210}{}{你好你需要什么吗？ -- Hi. Do you need something?}
### {211}{}{Ah, my regular customer. I am at your service.}
{211}{}{啊，我的老顾客。我随时为您服务。 -- Ah, my regular customer. I am at your service.}
### {212}{}{Do you want more?}
{212}{}{你想要更多吗？ -- Do you want more?}
### {213}{}{Are you looking for a new dose?}
{213}{}{你在找新剂量吗？ -- Are you looking for a new dose?}
### {214}{}{Didn't you have enough of the last portion? I'll do more for you.}
{214}{}{最后一份你还不够吃吗？我会为你做更多的事。 -- Didn't you have enough of the last portion? I'll do more for you.}
### {215}{}{I knew you'd be back. What kind of high will you try today?}
{215}{}{我就知道你会回来的。你今天要试什么高度？ -- I knew you'd be back. What kind of high will you try today?}

### {216}{}{See you.}
{216}{}{再见 -- See you.}
### {217}{}{Bye.}
{217}{}{再见 -- Bye.}
### {218}{}{Don't talk too much. See you later.}
{218}{}{不要说太多。回头见。 -- Don't talk too much. See you later.}
### {219}{}{We didn't see each other. Later.}
{219}{}{我们没有见面。后来 -- We didn't see each other. Later.}

#Rude response and going into battle
### {220}{}{Listen to me carefully, estupida. There are people behind me who *own* this area. And who are you to set your own rules here? Do you think they'll just let it go? Don't make any noise, otherwise there will be problems.}
{220}{}{仔细听我说，埃斯图皮达。我身后有人拥有这个地区。你是谁来制定你自己的规则？你认为他们会放手吗？不要发出任何噪音，否则会有问题的。 -- Listen to me carefully, estupida. There are people behind me who *own* this area. And who are you to set your own rules here? Do you think they'll just let it go? Don't make any noise, otherwise there will be problems.}
### {221}{}{I don't care, you're going to die anyway.}
{221}{}{我不在乎，你无论如何都会死的。 -- I don't care, you're going to die anyway.}
### {222}{}{Sorry, that was stupid. No problem, bro.}
{222}{}{对不起，那太愚蠢了。没问题，兄弟。 -- Sorry, that was stupid. No problem, bro.}
### {223}{}{Dude, you're starting to get on my nerves. Calm down, otherwise I'll call my guys.}
{223}{}{老兄，你开始让我紧张了。冷静点，否则我会打电话给我的人。 -- Dude, you're starting to get on my nerves. Calm down, otherwise I'll call my guys.}
### {1223}{}{Lady, you're getting on my nerves. Calm down, otherwise I will introduce you to my palm.}
{1223}{}{女士，你让我很紧张。冷静点，否则我会把你介绍给我的手掌。 -- Lady, you're getting on my nerves. Calm down, otherwise I will introduce you to my palm.}
### {224}{}{Come on, bitch! Come on!}
{224}{}{来吧，婊子！来吧 -- Come on, bitch! Come on!}
### {225}{}{Sorry, no need to call anyone. I'm already calming down.}
{225}{}{对不起，没必要给任何人打电话。我已经平静下来了。 -- Sorry, no need to call anyone. I'm already calming down.}
### {226}{}{You're crazy! Die, pendejo!}
{226}{}{你疯了！死吧，彭德霍！ -- You're crazy! Die, pendejo!}
### {1226}{}{You're crazy! Die, pendeja!}
{1226}{}{你疯了！死吧，彭德贾！ -- You're crazy! Die, pendeja!}
### {227}{}{Die yourself, faggot!}
{227}{}{你自己死吧，基佬！ -- Die yourself, faggot!}
### {228}{}{You need to be subdued.}
{228}{}{你需要克制。 -- You need to be subdued.}

#Questions
### {230}{}{So what kind of medicines are you selling?}
{230}{}{那么你们卖什么药呢？ -- So what kind of medicines are you selling?}
### {231}{}{And what do you need? Tell me, I can get a stimpack, Radawaye or... (winks) something more serious. Do you understand?}
{231}{}{你需要什么？告诉我，我可以得到一个刺激包，Radawaye或。。。（眨眼）更严重的事情。你明白吗？ -- And what do you need? Tell me, I can get a stimpack, Radawaye or... (winks) something more serious. Do you understand?}
### {232}{}{I'll keep that in mind. See you later.}
{232}{}{我会记住的。回头见。 -- I'll keep that in mind. See you later.}
### {233}{}{But where did you get all this chemistry from?}
{233}{}{但是你是从哪里得到这些化学反应的？ -- But where did you get all this chemistry from?}
### {234}{}{More serious? Like buffout and psycho?}
{234}{}{更严重？像小丑和神经病？ -- More serious? Like buffout and psycho?}
### {235}{}{I'm sorry, but the fire worshippers forbade me to sell such goods. They buy all the army drugs themselves.}
{235}{}{对不起，拜火者禁止我出售这种商品。所有的军药都是他们自己买的。 -- I'm sorry, but the fire worshippers forbade me to sell such goods. They buy all the army drugs themselves.}
### {236}{}{But why did they need old army drugs?}
{236}{}{但他们为什么需要旧的军药？ -- But why did they need old army drugs?}
### {237}{}{They hide behind caring for the residents of the city... look, I really don't know why they do this, but I don't want to go against the rules. However... (goes into a whisper)}
{237}{}{他们躲在后面照顾城市的居民。。。听着，我真的不知道他们为什么这么做，但我不想违反规则。然而（低声说） -- They hide behind caring for the residents of the city... look, I really don't know why they do this, but I don't want to go against the rules. However... (goes into a whisper)}
### {238}{}{Yes?}
{238}{}{对 -- Yes?}
### {239}{}{I have a lot of connections. For a modest reward of 100 caps, I can become your personal dealer. But this has to stay between us. Do you understand?}
{239}{}{我有很多关系。只要100顶帽子的适度奖励，我就可以成为你的私人经销商。但这必须是我们之间的事。你明白吗？ -- I have a lot of connections. For a modest reward of 100 caps, I can become your personal dealer. But this has to stay between us. Do you understand?}
### {240}{}{I'll think about your offer.}
{240}{}{我会考虑你的报价。 -- I'll think about your offer.}
### {241}{}{Yes, you are a danger to society. You need to be eliminated urgently.}
{241}{}{是的，你对社会构成了威胁。你急需被淘汰。 -- Yes, you are a danger to society. You need to be eliminated urgently.}
### {242}{}{Not so fast. First tell me where you got all this chemistry from?}
{242}{}{没那么快。首先告诉我这些化学反应是从哪里来的？ -- Not so fast. First tell me where you got all this chemistry from?}
### {243}{}{Here are the bottlecaps. Now show everything you hide from ordinary customers.}
{243}{}{这是水瓶。现在向普通客户展示你隐藏的一切。 -- Here are the bottlecaps. Now show everything you hide from ordinary customers.}
### {244}{}{We've been through this before. So do you need dope or not?}
{244}{}{我们以前也经历过这种情况。你需要毒品吗？ -- We've been through this before. So do you need dope or not?}
### {245}{}{No, not today.}
{245}{}{不，今天不行。 -- No, not today.}
### {246}{}{By the way, where do you get this chemistry from?}
{246}{}{顺便问一下，这种化学反应是从哪里来的？ -- By the way, where do you get this chemistry from?}
### {247}{}{I'm a Follower. Do you want the Cathedral to know about your deceptions? I can arrange it.}
{247}{}{我是一个追随者。你想让大教堂知道你的欺骗行为吗？我可以安排。 -- I'm a Follower. Do you want the Cathedral to know about your deceptions? I can arrange it.}
### {248}{}{Wait, don't rush! Why these fatal measures? We can always agree.}
{248}{}{等等，别急！为什么要采取这些致命措施？我们总是可以达成一致。 -- Wait, don't rush! Why these fatal measures? We can always agree.}
### {249}{}{Then I'm counting on full service.}
{249}{}{那我就指望全方位服务了。 -- Then I'm counting on full service.}
### {250}{}{S-listen, m-seth was shaking me. Don't break off and give treats!}
{250}{}{听着，m-seth在摇晃我。不要打断我，给我零食！ -- S-listen, m-seth was shaking me. Don't break off and give treats!}
### {251}{}{I need any dope that will allow me to win fights in the arena.}
{251}{}{我需要任何能让我在竞技场上赢得比赛的兴奋剂。 -- I need any dope that will allow me to win fights in the arena.}
### {252}{}{Forget. The sectarians have big problems now, they are not up to your nonsense.}
{252}{}{忘记宗派主义者现在有大问题，他们不能满足你的胡说八道。 -- Forget. The sectarians have big problems now, they are not up to your nonsense.}
### {253}{}{I'll be honest, I'm interested in your product.}
{253}{}{老实说，我对你的产品很感兴趣。 -- I'll be honest, I'm interested in your product.}
### {254}{}{Stay away from me.}
{254}{}{离我远点。 -- Stay away from me.}
### {255}{}{Orris advised me to contact you.}
{255}{}{奥建议我联系你。 -- Orris advised me to contact you.}
### {256}{}{Show me what you have.}
{256}{}{让我看看你有什么。 -- Show me what you have.}

### {260}{}{Damn, I have everything I need. Don't worry, you'll feel good now...}
{260}{}{该死，我有我需要的一切。别担心，你现在会感觉很好的。。。 -- Damn, I have everything I need. Don't worry, you'll feel good now...}
### {261}{}{Ugh, my eyes are running away from the choice. Now I will know where to buy dope.}
{261}{}{啊，我的眼睛在逃避选择。现在我知道在哪里买毒品了。 -- Ugh, my eyes are running away from the choice. Now I will know where to buy dope.}
### {262}{}{Another thing. But don't you dare talk. This will be our little secret.}
{262}{}{还有一件事但你不敢说话。这将是我们的小秘密。 -- Another thing. But don't you dare talk. This will be our little secret.}
### {263}{}{I don't see the point in that. I don't need third parties for sales.}
{263}{}{我不认为这有什么意义。我不需要第三方进行销售。 -- I don't see the point in that. I don't need third parties for sales.}
### {264}{}{I'll be back later.}
{264}{}{我稍后回来。 -- I'll be back later.}
### {265}{}{You're just a fool. Bye.}
{265}{}{你只是个傻瓜。再见 -- You're just a fool. Bye.}
### {266}{}{Then I'll break your fingers.}
{266}{}{那我就打断你的手指。 -- Then I'll break your fingers.}

### {270}{}{Where did you get all this chemistry from?}
{270}{}{你这些化学反应是从哪里来的？ -- Where did you get all this chemistry from?}
### {271}{}{From different places, obviously. I buy something from scavengers, something from caravans from the south, and I cook some preparations myself on the stove. Don't worry, everything is sterile.}
{271}{}{显然来自不同的地方。我从拾荒者那里买一些东西，从南方的大篷车那里买一些，我自己在炉子上做饭。别担心，一切都是无菌的。 -- From different places, obviously. I buy something from scavengers, something from caravans from the south, and I cook some preparations myself on the stove. Don't worry, everything is sterile.}
### {272}{}{Doesn't sound very reliable, don't you think?}
{272}{}{听起来不太可靠，你不觉得吗？ -- Doesn't sound very reliable, don't you think?}
### {273}{}{Calmly. Chemistry is almost without impurities. You can't find the best dope in the city... Except, perhaps, the Followers of Fire. But they don't share it with anyone.}
{273}{}{冷静。化学几乎没有杂质。你在这个城市找不到最好的毒品。。。也许除了火的追随者。但他们不会与任何人分享。 -- Calmly. Chemistry is almost without impurities. You can't find the best dope in the city... Except, perhaps, the Followers of Fire. But they don't share it with anyone.}
### {274}{}{And what kind of "dope" do you sell?}
{274}{}{你卖什么“毒品”？ -- And what kind of "dope" do you sell?}
### {275}{}{Almost? I need *really* quality medicines.}
{275}{}{几乎我需要高质量的药品。 -- Almost? I need *really* quality medicines.}
### {276}{}{I'm telling you - I have the best chemistry. If you don't trust me, then get out of here.}
{276}{}{我告诉你，我的化学反应最好。如果你不信任我，那就离开这里。 -- I'm telling you - I have the best chemistry. If you don't trust me, then get out of here.}
### {277}{}{Okay, okay, I'm leaving...}
{277}{}{好吧，好吧，我要走了。。。 -- Okay, okay, I'm leaving...}
### {278}{}{Just try to be rude to me again - you will be left without teeth.}
{278}{}{再对我无礼一次就好了——你会被弄得没牙的。 -- Just try to be rude to me again - you will be left without teeth.}
### {279}{}{I need *really* high-quality medicines. The lives of my patients depend on it.}
{279}{}{我需要高质量的药品。我的病人的生命取决于它。 -- I need *really* high-quality medicines. The lives of my patients depend on it.}
### {280}{}{So you're a doctor? That was the place to start. Doctors in our time can be counted on the fingers, I am glad of any such meeting. Don't worry, I'll give you the best. And also at a discount.}
{280}{}{你是医生吗？这就是开始的地方。在我们这个时代，医生是可以信赖的，我很高兴有这样的会议。别担心，我会给你最好的。而且还有折扣。 -- So you're a doctor? That was the place to start. Doctors in our time can be counted on the fingers, I am glad of any such meeting. Don't worry, I'll give you the best. And also at a discount.}
### {281}{}{Thank you, colleague, this will help me.}
{281}{}{谢谢你，同事，这对我有帮助。 -- Thank you, colleague, this will help me.}
### {282}{}{Another thing.}
{282}{}{还有一件事 -- Another thing.}
### {283}{}{It's still too doubtful. I'm leaving.}
{283}{}{这还是太令人怀疑了。我要走了。 -- It's still too doubtful. I'm leaving.}
### {284}{}{I'm from Murphy. And I need medicine for eternal sleep.}
{284}{}{我来自墨菲。我需要药物来保证永远的睡眠。 -- I'm from Murphy. And I need medicine for eternal sleep.}
### {285}{}{I don't know why you need it, and I don't want to know. But I have poison from the tail of a radscorpion and various drugs for overdose. Choose what you have enough caps for.}
{285}{}{我不知道你为什么需要它，我也不想知道。但我有一只蛇蝎尾巴上的毒药和各种过量服用的药物。选择你有足够的帽子。 -- I don't know why you need it, and I don't want to know. But I have poison from the tail of a radscorpion and various drugs for overdose. Choose what you have enough caps for.}
### {286}{}{Let's see...}
{286}{}{让我们看看。。。 -- Let's see...}
### {287}{}{But if anyone asks, I have nothing to do with it.}
{287}{}{但如果有人问我，我与之无关。 -- But if anyone asks, I have nothing to do with it.}
### {288}{}{OK.}
{288}{}{好啊 -- OK.}

### {290}{}{What's your name?}
{290}{}{你叫什么名字？ -- What's your name?}
### {291}{}{Call me Gonzalez.}
{291}{}{叫我冈萨雷斯。 -- Call me Gonzalez.}
### {292}{}{I doubt that's your real name.}
{292}{}{我怀疑那是你的真名。 -- I doubt that's your real name.}
### {293}{}{Ha. What an insight. What's it to you?}
{293}{}{哈多么有洞察力啊。你怎么了？ -- Ha. What an insight. What's it to you?}
### {294}{}{But why such secrecy?}
{294}{}{但为什么要这样保密呢？ -- But why such secrecy?}
### {295}{}{There are those who don't like my business. Competitors, fuck them. Or those sectarians from the Cathedral. They want to take over the entire turnover of medicines for themselves, and dealers like me are paid pennies. It's more profitable for me to work for myself, but you can't explain it to them.}
{295}{}{有些人不喜欢我的生意。竞争对手，操他们。或者那些来自大教堂的宗派主义者。他们想为自己接管药品的全部营业额，而像我这样的经销商只得到几分钱的报酬。为自己工作对我来说更有利可图，但你无法向他们解释。 -- There are those who don't like my business. Competitors, fuck them. Or those sectarians from the Cathedral. They want to take over the entire turnover of medicines for themselves, and dealers like me are paid pennies. It's more profitable for me to work for myself, but you can't explain it to them.}
### {296}{}{If not from Followers, then where do you get the drugs?}
{296}{}{如果不是来自追随者，那么你从哪里得到毒品？ -- If not from Followers, then where do you get the drugs?}
### {297}{}{Working for yourself in such a place is a risky business.}
{297}{}{在这样的地方为自己工作是件冒险的事。 -- Working for yourself in such a place is a risky business.}
### {298}{}{Damn, don't twist my balls. Do you know the Red Cardinals? They are usually cleaned in the old building of the sports club. Orris is their leader. He makes sure that nothing interferes with my business. Not for free, of course.}
{298}{}{该死，别扭我的蛋蛋。你认识红雀队吗？他们通常在体育俱乐部的旧楼里打扫。欧里斯是他们的领袖。他确保没有任何东西干扰我的生意。当然不是免费的。 -- Damn, don't twist my balls. Do you know the Red Cardinals? They are usually cleaned in the old building of the sports club. Orris is their leader. He makes sure that nothing interferes with my business. Not for free, of course.}
### {299}{}{Damn, don't twist my balls. I used to be protected by Orris's guys. But his death hurt my business. I don't know how I'm going to survive now.}
{299}{}{该死，别扭我的蛋蛋。我曾经被奥的人保护过。但他的死伤害了我的生意。我不知道我现在该怎么活下去。 -- Damn, don't twist my balls. I used to be protected by Orris's guys. But his death hurt my business. I don't know how I'm going to survive now.}

#Drug addict died at the hands of GG
### {300}{}{They say you killed Larry. Why the hell are you killing my clients?}
{300}{}{他们说你杀了拉里。你为什么要杀我的客户？ -- They say you killed Larry. Why the hell are you killing my clients?}
### {301}{}{I'm ridding the world of garbage. Any problems?}
{301}{}{我正在清除世界上的垃圾。有什么问题吗？ -- I'm ridding the world of garbage. Any problems?}
### {302}{}{Then do it somewhere else! Larry, though he was trash, but he had periods of epiphany. At such moments, he managed to earn caps and then lowered them to a new batch of dope. I had a good income from this, do you understand? And what will I have with a cold corpse?}
{302}{}{那就去别的地方吧！拉里，虽然他是个废物，但他有一段顿悟的时期。在这样的时刻，他设法赢得了上限，然后把它们降到了新的一批毒品中。我从中获得了不错的收入，你明白吗？一具冰冷的尸体会给我带来什么？ -- Then do it somewhere else! Larry, though he was trash, but he had periods of epiphany. At such moments, he managed to earn caps and then lowered them to a new batch of dope. I had a good income from this, do you understand? And what will I have with a cold corpse?}
### {303}{}{Eh, what?}
{303}{}{呃，什么？ -- Eh, what?}
### {304}{}{I don't care.}
{304}{}{我不在乎。 -- I don't care.}
### {305}{}{Um-M... Remember, it will cost you dearly. I will take my lost profit from our transactions.}
{305}{}{嗯。。。记住，这会让你付出高昂的代价。我将从我们的交易中获利。 -- Um-M... Remember, it will cost you dearly. I will take my lost profit from our transactions.}
### {306}{}{So now I won't be able to count on discounts? Sorry to hear that.}
{306}{}{所以现在我不能指望折扣了？很抱歉听到这个消息。 -- So now I won't be able to count on discounts? Sorry to hear that.}
### {307}{}{I'm not going to shop at your shady shop anyway. Bye.}
{307}{}{无论如何，我都不会去你那阴暗的商店购物。再见 -- I'm not going to shop at your shady shop anyway. Bye.}
### {308}{}{Sorry, it happened by accident.}
{308}{}{对不起，这是意外发生的。 -- Sorry, it happened by accident.}
### {309}{}{Excuse me? You killed my client and say I'm SORRY?! You son of a bitch, do you think I'm just going to let it go?}
{309}{}{打扰一下你杀了我的客户然后说我很抱歉？！你这个婊子养的，你以为我会放手吗？ -- Excuse me? You killed my client and say I'm SORRY?! You son of a bitch, do you think I'm just going to let it go?}
### {1309}{}{Excuse me? You killed my client and say I'm SORRY?! You son of a bitch, do you think I'm just going to let it go?}
{1309}{}{打扰一下你杀了我的客户然后说我很抱歉？！你这个婊子养的，你以为我会放手吗？ -- Excuse me? You killed my client and say I'm SORRY?! You son of a bitch, do you think I'm just going to let it go?}
### {310}{}{Uh, yeah.}
{310}{}{嗯，是的。 -- Uh, yeah.}
### {311}{}{What is it, are you looking for a fight?}
{311}{}{这是什么，你想打架吗？ -- What is it, are you looking for a fight?}
### {312}{}{This is our business with him.}
{312}{}{这是我们和他的事。 -- This is our business with him.}
### {313}{}{ (squinting) What business could you have with Larry?}
{313}{}{（斜视）你能和拉里做什么生意？ --  (squinting) What business could you have with Larry?}
### {314}{}{It doesn't concern you.}
{314}{}{这与你无关。 -- It doesn't concern you.}
### {315}{}{If I tell you, I'll have to kill you, too.}
{315}{}{如果我告诉你，我也得杀了你。 -- If I tell you, I'll have to kill you, too.}
### {316}{}{Damn, I hate it when someone takes away my clients.}
{316}{}{该死，我讨厌有人抢走我的客户。 -- Damn, I hate it when someone takes away my clients.}
### {317}{}{You mean that junkie... What's his name... Larry?}
{317}{}{你是说那个瘾君子。。。他叫什么名字。。。拉里？ -- You mean that junkie... What's his name... Larry?}
### {318}{}{Larry. Even though he was trash, he had periods of epiphany. At such moments, I managed to earn light caps on it. And what will I have now?}
{318}{}{拉里。尽管他是个废物，但他也有过顿悟的时期。在这样的时刻，我设法在上面赚了很多钱。现在我会有什么？ -- Larry. Even though he was trash, he had periods of epiphany. At such moments, I managed to earn light caps on it. And what will I have now?}
### {319}{}{You wouldn't be able to make money on someone else's problem for a long time. Think about it.}
{319}{}{你在很长一段时间内都无法在别人的问题上赚钱。想想看。 -- You wouldn't be able to make money on someone else's problem for a long time. Think about it.}

### {320}{}{With those guys who took your bike, you should be careful. They're from the Red Cardinals gang, and this gang practically owns this neighborhood. Make one of them angry, and you won't live. But of course it's yours.}
{320}{}{和那些拿走你自行车的人在一起，你应该小心。他们来自红雀队，而这个帮派实际上拥有这个社区。让他们中的一个生气，你就活不下去了。但它当然是你的。 -- With those guys who took your bike, you should be careful. They're from the Red Cardinals gang, and this gang practically owns this neighborhood. Make one of them angry, and you won't live. But of course it's yours.}
### {321}{}{I'll take that into account.}
{321}{}{我会考虑到的。 -- I'll take that into account.}
### {322}{}{I have a package for you from the Blue Shields.}
{322}{}{我有一个来自蓝盾的包裹给你。 -- I have a package for you from the Blue Shields.}
### {323}{}{Finally. Give it here. I've been waiting. Do you know how hard it is to get hydrocarbons?}
{323}{}{最后给我。我一直在等。你知道获取碳氢化合物有多难吗？ -- Finally. Give it here. I've been waiting. Do you know how hard it is to get hydrocarbons?}
### {324}{}{Eh, how?}
{324}{}{呃，怎么回事？ -- Eh, how?}
### {325}{}{No matter. Here, take the finished product. And tell your people that because of the fire worshippers, it's getting harder to do dope.}
{325}{}{不管怎样给，拿着成品。告诉你的人民，因为有了火崇拜者，吸毒变得越来越难了。 -- No matter. Here, take the finished product. And tell your people that because of the fire worshippers, it's getting harder to do dope.}
### {326}{}{Bye.}
{326}{}{再见 -- Bye.}
### {327}{}{There was an overlay with the last courier. You know how hard it is to cross the tenth highway.}
{327}{}{最后一个快递员在上面。你知道过第十条高速公路有多难。 -- There was an overlay with the last courier. You know how hard it is to cross the tenth highway.}
### {328}{}{Well yes. And how to make dope without raw materials, stupid? Okay, here's the finished product. Give it to Rio, let him take care of the courier before the fire worshippers shut down my shop.}
{328}{}{是的。愚蠢的人，如何在没有原料的情况下制造毒品？好的，这是成品。把它交给里奥，让他在拜火者关闭我的商店之前照顾快递员。 -- Well yes. And how to make dope without raw materials, stupid? Okay, here's the finished product. Give it to Rio, let him take care of the courier before the fire worshippers shut down my shop.}
### {329}{}{Bye.}
{329}{}{再见 -- Bye.}

### {330}{}{Are you supplying drugs to Larry?}
{330}{}{你在给拉里供应毒品吗？ -- Are you supplying drugs to Larry?}
### {331}{}{If not me, then someone else. What's it to you?}
{331}{}{如果不是我，那就是其他人。你怎么了？ -- If not me, then someone else. What's it to you?}
### {332}{}{You're right. None.}
{332}{}{你说得对。没有一个 -- You're right. None.}
### {333}{}{Then don't poke your nose into other people's business.}
{333}{}{那就不要干涉别人的事。 -- Then don't poke your nose into other people's business.}
### {334}{}{Uh, okay...}
{334}{}{好吧。。。 -- Uh, okay...}
### {335}{}{The residents of the house are dissatisfied with this.}
{335}{}{这所房子的居民对此感到不满。 -- The residents of the house are dissatisfied with this.}
### {336}{}{Let them figure it out for themselves. It's not my problem, it's Larry's problem. I'm just selling him medicine.}
{336}{}{让他们自己想办法。这不是我的问题，是拉里的问题。我只是卖给他药。 -- Let them figure it out for themselves. It's not my problem, it's Larry's problem. I'm just selling him medicine.}
### {337}{}{Medications? Really?}
{337}{}{药物？真正地 -- Medications? Really?}
### {338}{}{Well, you know, he was feverish from a wasteland disease. So he turned to me for treatment. How can I refuse urgent care to those in need?}
{338}{}{嗯，你知道，他是因为一种荒地疾病而发烧的。所以他转向我接受治疗。我怎么能拒绝为那些需要帮助的人提供紧急护理？ -- Well, you know, he was feverish from a wasteland disease. So he turned to me for treatment. How can I refuse urgent care to those in need?}
### {339}{}{How "nice" of you. Bye, doc.}
{339}{}{你真“好”。再见，医生。 -- How "nice" of you. Bye, doc.}
### {340}{}{If you sell him at least one more dose, you're in big trouble.}
{340}{}{如果你再卖给他至少一剂，你就麻烦大了。 -- If you sell him at least one more dose, you're in big trouble.}
### {341}{}{What did you say? Say it again, asshole, maybe I misheard?}
{341}{}{你说什么？再说一遍，混蛋，也许我听错了？ -- What did you say? Say it again, asshole, maybe I misheard?}
### {1341}{}{What did you say? Repeat, bitch, maybe I misheard?}
{1341}{}{你说什么？重复一遍，婊子，也许我听错了？ -- What did you say? Repeat, bitch, maybe I misheard?}
### {342}{}{Uh, we need to calm down a little. Goodbye, friend.}
{342}{}{我们需要冷静一点。再见，朋友。 -- Uh, we need to calm down a little. Goodbye, friend.}
### {343}{}{I repeat it only once. Stop bullying Larry. Or you will die.}
{343}{}{我只重复一遍。别欺负拉里了。否则你会死的。 -- I repeat it only once. Stop bullying Larry. Or you will die.}
### {344}{}{Sorry, I got confused. Of course, Larry won't get a single dose from me. No problem.}
{344}{}{对不起，我弄糊涂了。当然，拉里不会从我这里得到任何剂量。没问题。 -- Sorry, I got confused. Of course, Larry won't get a single dose from me. No problem.}
### {345}{}{I'll see to it.}
{345}{}{我会处理好的。 -- I'll see to it.}
### {346}{}{I don't recommend it. Arguing with me is the same as arguing with Orris.}
{346}{}{我不建议这样做。和我争论就像和奥里斯争论一样。 -- I don't recommend it. Arguing with me is the same as arguing with Orris.}
### {347}{}{Oh, so you're one of the cardinals now? Now, uh, I'll know. Just, uh, don't strain yourself, friend.}
{347}{}{哦，那么你现在是红衣主教了？现在，呃，我会知道的。只是，呃，别紧张，朋友。 -- Oh, so you're one of the cardinals now? Now, uh, I'll know. Just, uh, don't strain yourself, friend.}
### {348}{}{That's right.}
{348}{}{没错。 -- That's right.}
### {349}{}{Now Larry is under my protection. And therefore, under the patronage of Don Diego.}
{349}{}{现在拉里在我的保护之下。因此，在唐·迭戈的赞助下。 -- Now Larry is under my protection. And therefore, under the patronage of Don Diego.}
### {350}{}{I can tell Aaron about your business at any time. You're lucky I haven't done it yet.}
{350}{}{我可以随时告诉亚伦你的事。你很幸运，我还没做。 -- I can tell Aaron about your business at any time. You're lucky I haven't done it yet.}
### {1350}{}{I can tell Aaron about your business at any time. You're lucky I haven't done it yet.}
{1350}{}{我可以随时告诉亚伦你的事。你很幸运，我还没做。 -- I can tell Aaron about your business at any time. You're lucky I haven't done it yet.}
