### {100}{}{Here is a Phoenician.}
{100}{}{这是一个腓尼基人。 -- Here is a Phoenician.}
### {101}{}{You see an ordinary citizen of Phoenix. He seems tense and is clearly waiting for someone.}
{101}{}{你看到的是凤凰城的一位普通市民。他看起来很紧张，显然在等人。 -- You see an ordinary citizen of Phoenix. He seems tense and is clearly waiting for someone.}
### {102}{}{Go your own way.}
{102}{}{走你自己的路。 -- Go your own way.}

### {200}{}{Where are you in a hurry, sectarian? Decided to get out of town? The right decision. We will help you.}
{200}{}{你在哪里赶时间，宗派主义者？决定出城吗？正确的决定。我们会帮助你的。 -- Where are you in a hurry, sectarian? Decided to get out of town? The right decision. We will help you.}
### {201}{}{Really? That's so kind...}
{201}{}{真正地真是太好了。。。 -- Really? That's so kind...}
### {202}{}{You're confusing me with someone else.}
{202}{}{你把我和别人搞混了。 -- You're confusing me with someone else.}
### {203}{}{We know you're a fire worshipper. And you know what? We will no longer tolerate this "nuclear magic" of yours here. Get out of town, scum.}
{203}{}{我们知道你是个火崇拜者。你知道吗？我们将不再容忍你们在这里的这种“核魔法”。滚出去，人渣。 -- We know you're a fire worshipper. And you know what? We will no longer tolerate this "nuclear magic" of yours here. Get out of town, scum.}
### {204}{}{No, no, I'm not a member of this sect anymore.}
{204}{}{不，不，我已经不是这个教派的成员了。 -- No, no, I'm not a member of this sect anymore.}
### {205}{}{Shut your mouth! After the explosion in the cathedral, half of the city was destroyed, and a real war began among the people. We will not rest until there is not a single sectarian left in the city, active or former. Is that clear to you?}
{205}{}{闭上你的嘴！大教堂发生爆炸后，城市的一半被摧毁，人民之间开始了真正的战争。我们不会休息，直到城市里没有一个教派残余，无论是活跃的还是以前的。你清楚吗？ -- Shut your mouth! After the explosion in the cathedral, half of the city was destroyed, and a real war began among the people. We will not rest until there is not a single sectarian left in the city, active or former. Is that clear to you?}
### {206}{}{Yes, it's clear to me.}
{206}{}{是的，我很清楚。 -- Yes, it's clear to me.}
### {207}{}{Now get out of town. Pop in again and you're dead.}
{207}{}{现在出城吧。再来一次，你就死定了。 -- Now get out of town. Pop in again and you're dead.}
### {208}{}{Uh...}
{208}{}{嗯 -- Uh...}
### {209}{}{No, I don't understand. Explain it again, stupid.}
{209}{}{不，我不明白。再解释一遍，笨蛋。 -- No, I don't understand. Explain it again, stupid.}
### {210}{}{Now I'll explain everything, scum...}
{210}{}{现在我来解释一切，人渣。。。 -- Now I'll explain everything, scum...}
### {211}{}{What are you doing... stop...}
{211}{}{你在干什么。。。停止 -- What are you doing... stop...}
### {212}{}{Attack one at a time, guys.}
{212}{}{一次攻击一个，伙计们。 -- Attack one at a time, guys.}
### {213}{}{Wait, guys. We're in this together. It was thanks to me that the church was swallowed up by a big hole.}
{213}{}{等等，伙计们。我们在一起。多亏了我，教堂才被一个大洞吞没了。 -- Wait, guys. We're in this together. It was thanks to me that the church was swallowed up by a big hole.}
### {214}{}{Thu... Do you take me for a fool? No one will believe it.}
{214}{}{周四。。。你以为我是个傻瓜吗？没有人会相信。 -- Thu... Do you take me for a fool? No one will believe it.}
### {215}{}{In vain. These sectarians sponsored the slavers who kidnapped my relatives. The explosion was retribution.}
{215}{}{徒劳。这些宗派主义者资助了绑架我亲属的奴隶贩子。这次爆炸是报复。 -- In vain. These sectarians sponsored the slavers who kidnapped my relatives. The explosion was retribution.}
### {216}{}{Yeah... You're singing too sweetly. If that's true, then you're responsible for the destruction all over Phoenix. Do you think this should make us happy? Get out of town. You go back and you're dead. Is that clear to you?}
{216}{}{是 啊你唱得太甜美了。如果这是真的，那么你要为整个凤凰城的破坏负责。你认为这会让我们高兴吗？离开城镇。你回去就死定了。你清楚吗？ -- Yeah... You're singing too sweetly. If that's true, then you're responsible for the destruction all over Phoenix. Do you think this should make us happy? Get out of town. You go back and you're dead. Is that clear to you?}
### {217}{}{No problems. You won't see me again.}
{217}{}{没有问题。你再也见不到我了。 -- No problems. You won't see me again.}
### {218}{}{But you don't need to threaten me. Otherwise I'll see a corpse in front of me.}
{218}{}{但你不需要威胁我，否则我会看到一具尸体在我面前。 -- But you don't need to threaten me. Otherwise I'll see a corpse in front of me.}
### {219}{}{I don't care what you believe.}
{219}{}{我不在乎你相信什么。 -- I don't care what you believe.}
### {220}{}{It looks like this little bitch doesn't understand human language. I'll have to explain with my fists...}
{220}{}{看起来这个小婊子不懂人类语言。我得用拳头解释。。。 -- It looks like this little bitch doesn't understand human language. I'll have to explain with my fists...}
### {1220}{}{It looks like this bitch doesn't understand human language. We'll have to explain it by brute force...}
{1220}{}{这个婊子好像不懂人类语言。我们必须用蛮力来解释。。。 -- It looks like this bitch doesn't understand human language. We'll have to explain it by brute force...}
### {221}{}{Just be gentle, guys...}
{221}{}{只要温柔一点，伙计们。。。 -- Just be gentle, guys...}
### {222}{}{This is your last mistake.}
{222}{}{这是你最后一次犯错。 -- This is your last mistake.}
### {223}{}{You're threatening me. And those who threatened me ended their lives very quickly.}
{223}{}{你在威胁我。那些威胁我的人很快就结束了他们的生命。 -- You're threatening me. And those who threatened me ended their lives very quickly.}

### {230}{}{Hey, you. Your burnt skin.}
{230}{}{嘿，你。你烧焦的皮肤。 -- Hey, you. Your burnt skin.}
### {231}{}{Yes? What about her?}
{231}{}{对她呢？ -- Yes? What about her?}
### {232}{}{Who made you like this? I heard that experiments were conducted under the cathedral to create elite fighters. And you were just seen in the cathedral.}
{232}{}{是谁让你变成这样的？我听说在大教堂下面进行了实验，以培养精英战士。你刚刚在大教堂里被看到。 -- Who made you like this? I heard that experiments were conducted under the cathedral to create elite fighters. And you were just seen in the cathedral.}
### {233}{}{This is some kind of mistake. I'm just a victim of radiation, and I was looking for a cure in the cathedral.}
{233}{}{这是某种错误。我只是辐射的受害者，我在大教堂里寻找治疗方法。 -- This is some kind of mistake. I'm just a victim of radiation, and I was looking for a cure in the cathedral.}
### {1233}{}{This is some kind of mistake. I'm just a victim of radiation, and I was looking for a cure in the cathedral.}
{1233}{}{这是某种错误。我只是辐射的受害者，我在大教堂里寻找治疗方法。 -- This is some kind of mistake. I'm just a victim of radiation, and I was looking for a cure in the cathedral.}
### {234}{}{Maybe... We are looking for the remnants of the sectarians to expel them from the city. So don't get caught in the hot hand.}
{234}{}{大概我们正在寻找残余的宗派主义者，将他们驱逐出这个城市。所以，不要陷入困境。 -- Maybe... We are looking for the remnants of the sectarians to expel them from the city. So don't get caught in the hot hand.}
### {235}{}{Of course, I will behave peacefully.}
{235}{}{当然，我会表现得很平和。 -- Of course, I will behave peacefully.}
### {236}{}{Hmm... (looks around from head to toe, expressing undisguised disgust) You can go now.}
{236}{}{嗯……（从头到脚环顾四周，毫不掩饰地表示厌恶）你现在可以走了。 -- Hmm... (looks around from head to toe, expressing undisguised disgust) You can go now.}
### {237}{}{...}
{237}{}{。。。 -- ...}
### {238}{}{ It's hard for a person with my face to hide. What do you have against fire worshippers?}
{238}{}{像我这样的人很难掩饰。你对拜火者有什么反对意见？ --  It's hard for a person with my face to hide. What do you have against fire worshippers?}
### {239}{}{We are eradicating all sectarians in the city. After the explosion in the cathedral, they have no place here. And you too.}
{239}{}{我们正在铲除这个城市的所有宗派主义者。大教堂发生爆炸后，他们在这里没有立足之地。你也是。 -- We are eradicating all sectarians in the city. After the explosion in the cathedral, they have no place here. And you too.}
### {240}{}{Why so much rudeness? Didn't the fire worshippers teach patience and love?}
{240}{}{为什么这么粗鲁？拜火者不是教人耐心和爱吗？ -- Why so much rudeness? Didn't the fire worshippers teach patience and love?}
### {241}{}{In words, maybe. But they themselves were preparing a nuclear bomb in their dark dungeon. There is no faith for such anymore... In any case, you're not welcome here. Get out of town, atomic litter.}
{241}{}{换句话说，也许。但他们自己却在黑暗的地牢里准备核弹。再也没有这样的信仰了。。。无论如何，这里不欢迎你。滚出去，原子垃圾。 -- In words, maybe. But they themselves were preparing a nuclear bomb in their dark dungeon. There is no faith for such anymore... In any case, you're not welcome here. Get out of town, atomic litter.}
### {242}{}{I can't argue with you. Good luck, guys.}
{242}{}{我不能和你争论。祝你们好运。 -- I can't argue with you. Good luck, guys.}
### {243}{}{For such words I will tear out your eyes and suck the brains out of your cooling skull.}
{243}{}{为了这些话，我会撕裂你的眼睛，从你冰冷的头骨里吸出大脑。 -- For such words I will tear out your eyes and suck the brains out of your cooling skull.}
### {244}{}{It seems that this creature does not understand human language. Guys...}
{244}{}{这个生物似乎不懂人类的语言。伙计们。。。 -- It seems that this creature does not understand human language. Guys...}
### {245}{}{Oh, no violence...}
{245}{}{哦，没有暴力。。。 -- Oh, no violence...}
### {246}{}{You gulen-haters are all the same.}
{246}{}{你们这些憎恨葛兰的人都一样。 -- You gulen-haters are all the same.}
### {247}{}{Exactly. I am a victim, not a sectarian.}
{247}{}{确切地我是受害者，而不是宗派主义者。 -- Exactly. I am a victim, not a sectarian.}
### {248}{}{I don't believe you. Guys, don't let him escape...}
{248}{}{我不相信你。伙计们，别让他逃跑。。。 -- I don't believe you. Guys, don't let him escape...}
### {1248}{}{I don't believe you. Guys, don't let her escape...}
{1248}{}{我不相信你。伙计们，别让她逃跑。。。 -- I don't believe you. Guys, don't let her escape...}
### {249}{}{Just not in the face...}
{249}{}{只是不在脸上。。。 -- Just not in the face...}
### {250}{}{Maybe so... Okay, go ahead. But if we find out that you are a fire worshipper, then you will burn at the stake with the others.}
{250}{}{也许是这样…好吧，继续吧。但如果我们发现你是一个火崇拜者，那么你就会和其他人一起被烧死。 -- Maybe so... Okay, go ahead. But if we find out that you are a fire worshipper, then you will burn at the stake with the others.}

### {260}{}{Wait. I don't want to get into a fight, but I have to say it. We know that you are a former fire worshipper. In this city, such people are no longer welcome. Go away and don't come back. If you come back, all this ammunition will not save you from retribution.}
{260}{}{等待我不想打架，但我必须说出来。我们知道你以前是个拜火者。在这个城市，这样的人不再受欢迎。走开，别回来。如果你回来了，所有这些弹药都不会让你免于报复。 -- Wait. I don't want to get into a fight, but I have to say it. We know that you are a former fire worshipper. In this city, such people are no longer welcome. Go away and don't come back. If you come back, all this ammunition will not save you from retribution.}
### {261}{}{I understand. You won't see me again. Goodbye.}
{261}{}{我理解。你再也见不到我了。再见 -- I understand. You won't see me again. Goodbye.}
### {262}{}{I'm not going anywhere. Who dares to stop me?}
{262}{}{我哪儿也不去。谁敢阻止我？ -- I'm not going anywhere. Who dares to stop me?}
### {263}{}{(they look at each other nervously) We don't want a fight. We don't want to yet. But if necessary, we will arrange it. So that you won't be here tomorrow.}
{263}{}{（他们紧张地看着对方）我们不想打架。我们还不想。但如果有必要，我们会安排的。这样你明天就不会在这里了。 -- (they look at each other nervously) We don't want a fight. We don't want to yet. But if necessary, we will arrange it. So that you won't be here tomorrow.}
### {264}{}{Not so fast, pussy. Whether you like it or not, the fight is going to happen right now.}
{264}{}{没那么快，小猫咪。不管你喜不喜欢，这场战斗现在就要发生了。 -- Not so fast, pussy. Whether you like it or not, the fight is going to happen right now.}
### {265}{}{You're confusing me with someone else.}
{265}{}{你把我和别人搞混了。 -- You're confusing me with someone else.}
### {266}{}{Really? I don't think so. Get out of town. We don't want a fight, but if necessary, we will arrange it.}
{266}{}{真正地我不这么认为。滚出去。我们不想打架，但如果有必要，我们会安排的。 -- Really? I don't think so. Get out of town. We don't want a fight, but if necessary, we will arrange it.}
### {267}{}{Spit. Let's fight.}
{267}{}{吐让我们战斗吧。 -- Spit. Let's fight.}
### {268}{}{I'll think about your words.}
{268}{}{我会好好想想你的话。 -- I'll think about your words.}
