### {100}{}{There is a rebel in front of you.}
{100}{}{你面前有一个反叛者。 -- There is a rebel in front of you.}
### {101}{}{You see a man in a balaclava. He seems to be hiding from someone.}
{101}{}{你看到一个戴着巴拉克拉瓦帽的男人。他好像在躲避别人。 -- You see a man in a balaclava. He seems to be hiding from someone.}
### {102}{}{It seems to have passed. Then I'll find my way. See you at the base.}
{102}{}{它似乎已经过去了。然后我会找到路的。基地见。 -- It seems to have passed. Then I'll find my way. See you at the base.}
### {103}{}{Thanks for the help. Together we will achieve freedom for Phoenix.}
{103}{}{谢谢你的帮助。我们将共同实现凤凰城的自由。 -- Thanks for the help. Together we will achieve freedom for Phoenix.}
### {104}{}{In front of you are the ruins of a once large city. There's probably an increased level of radiation here.}
{104}{}{你面前是一座曾经的大城市的废墟。这里的辐射水平可能增加了。 -- In front of you are the ruins of a once large city. There's probably an increased level of radiation here.}

#The first dialog
### {200}{}{And... who else are you?}
{200}{}{和你还有谁？ -- And... who else are you?}
### {201}{}{Alice and Marcos sent me. They've lost touch with you.}
{201}{}{爱丽丝和马科斯派我来的。他们和你失去了联系。 -- Alice and Marcos sent me. They've lost touch with you.}
### {202}{}{Finally... But quiet! We must not be heard. I don't know how these monks figured me out. They're smarter than they look. Will you help me get back to base?}
{202}{}{最后但是安静！我们决不能被听到。我不知道这些和尚是怎么想出来的。他们比看上去更聪明。你能帮我回基地吗？ -- Finally... But quiet! We must not be heard. I don't know how these monks figured me out. They're smarter than they look. Will you help me get back to base?}
### {203}{}{What about your assignment?}
{203}{}{你的作业怎么样？ -- What about your assignment?}
### {204}{}{To hell with it. Now we need to get out of the clutches of these sectarians. In addition, the lighthouse remained in the opposite building, it is now impossible to get close to it.}
{204}{}{见鬼去吧。现在我们需要摆脱这些宗派主义者的控制。此外，灯塔还保留在对面的大楼里，现在已经无法靠近了。 -- To hell with it. Now we need to get out of the clutches of these sectarians. In addition, the lighthouse remained in the opposite building, it is now impossible to get close to it.}
### {205}{}{We need to leave.}
{205}{}{我们需要离开。 -- We need to leave.}
### {206}{}{It will not be possible to pass by the cultists unnoticed ... Hmm, but how did you manage it?}
{206}{}{不可能在不被注意的情况下与邪教分子擦肩而过。。。嗯，但是你是怎么做到的？ -- It will not be possible to pass by the cultists unnoticed ... Hmm, but how did you manage it?}
### {207}{}{We'll have to fight our way to the exit. Are you ready? Then let's go.}
{207}{}{我们必须奋力杀出出口。你准备好了吗？那我们走吧。 -- We'll have to fight our way to the exit. Are you ready? Then let's go.}
### {208}{}{First you need to finish your assignment. Wait here.}
{208}{}{首先你需要完成你的作业。在这里等候。 -- First you need to finish your assignment. Wait here.}

#Repeat dialog
### {210}{}{We need to get back to headquarters. And in no case bring the tail there.}
{210}{}{我们需要回到总部。在任何情况下都不要把尾巴带到那里。 -- We need to get back to headquarters. And in no case bring the tail there.}
### {211}{}{Sure. Let's get out of here.}
{211}{}{当然让我们离开这里。 -- Sure. Let's get out of here.}
### {212}{}{Wait here, I'll go scouting.}
{212}{}{在这里等着，我去侦察。 -- Wait here, I'll go scouting.}
### {213}{}{Let's go. They're waiting for us at the General Staff.}
{213}{}{我们走吧。他们在总参谋部等我们。 -- Let's go. They're waiting for us at the General Staff.}
### {214}{}{Wait here, I'll scout the situation.}
{214}{}{在这里等着，我来侦察情况。 -- Wait here, I'll scout the situation.}
### {215}{}{Remind me of your assignment?}
{215}{}{提醒我你的任务？ -- Remind me of your assignment?}
### {216}{}{I had to install a beacon in that old building. He's still there. I had to throw all the equipment in order not to get burned. And I'm not going back there, it's too risky. What if they set up an ambush?}
{216}{}{我不得不在那栋旧建筑里安装一个灯塔。他还在那里。为了不被烧伤，我不得不扔掉所有的设备。我不会再回去了，太冒险了。如果他们设下埋伏怎么办？ -- I had to install a beacon in that old building. He's still there. I had to throw all the equipment in order not to get burned. And I'm not going back there, it's too risky. What if they set up an ambush?}
### {217}{}{It seems to have passed. Then I'll find my way. See you at the base.}
{217}{}{它似乎已经过去了。然后我会找到路的。基地见。 -- It seems to have passed. Then I'll find my way. See you at the base.}
### {218}{}{OK, see you later.}
{218}{}{好的，回头见。 -- OK, see you later.}
### {219}{}{It seems to have passed. If it weren't for you, I'd be in for a sad fate. Thanks for the help.}
{219}{}{它似乎已经过去了。如果不是你，我的命运会很悲惨。谢谢你的帮助。 -- It seems to have passed. If it weren't for you, I'd be in for a sad fate. Thanks for the help.}
