### {100}{}{Here is a cardinal.}
{100}{}{这是一位红衣主教。 -- Here is a cardinal.}
### {101}{}{You see a bandit with a stylish hairstyle and a gang emblem on his back.}
{101}{}{你可以看到一个土匪，他的发型很时髦，背上有一个帮派徽章。 -- You see a bandit with a stylish hairstyle and a gang emblem on his back.}
### {102}{}{I wish I had armor like yours, the whole city is lying at my feet.}
{102}{}{我希望我有像你一样的盔甲，整个城市都躺在我的脚下。 -- I wish I had armor like yours, the whole city is lying at my feet.}

### {110}{}{Looking for trouble?}
{110}{}{找麻烦？ -- Looking for trouble?}
### {111}{}{Who are you anyway?}
{111}{}{你到底是谁？ -- Who are you anyway?}
### {112}{}{Our territory is our rules.}
{112}{}{我们的领土就是我们的规则。 -- Our territory is our rules.}
### {113}{}{Everyone in the area lies below us.}
{113}{}{这个地区的每个人都躺在我们下面。 -- Everyone in the area lies below us.}
### {114}{}{Be careful with the words.}
{114}{}{措辞要小心。 -- Be careful with the words.}
### {115}{}{Shut up if you don't want to get in the snout.}
{115}{}{如果你不想惹鼻子，就闭嘴。 -- Shut up if you don't want to get in the snout.}
### {116}{}{Do you even know who we are?}
{116}{}{你知道我们是谁吗？ -- Do you even know who we are?}
### {117}{}{Have an opinion? Shove it up your ass.}
{117}{}{有意见吗？把它塞进你的屁股。 -- Have an opinion? Shove it up your ass.}
### {118}{}{What are you selling there?}
{118}{}{你在那里卖什么？ -- What are you selling there?}
### {119}{}{Are you looking for something in our neighborhood?}
{119}{}{你在我们附近找东西吗？ -- Are you looking for something in our neighborhood?}

### {120}{}{Damn, we shouldn't have doubted you.}
{120}{}{该死，我们不应该怀疑你。 -- Damn, we shouldn't have doubted you.}
### {121}{}{And you're cooler than you look.}
{121}{}{而且你比看上去更酷。 -- And you're cooler than you look.}
### {122}{}{Hey, how are you?}
{122}{}{嘿，你好吗？ -- Hey, how are you?}
### {123}{}{Do you want a beer?}
{123}{}{你想喝啤酒吗？ -- Do you want a beer?}
### {124}{}{Shall we do some business? I'm only "for".}
{124}{}{我们做点生意好吗？我只是“支持”。 -- Shall we do some business? I'm only "for".}
### {125}{}{If anything, I'm with you.}
{125}{}{如果有什么不同的话，我支持你。 -- If anything, I'm with you.}
### {126}{}{Everyone's here. Make yourself comfortable.}
{126}{}{每个人都在这里。让自己舒服一点。 -- Everyone's here. Make yourself comfortable.}
### {127}{}{}
{127}{}{error : string is empty -- }
### {128}{}{}
{128}{}{error : string is empty -- }
### {129}{}{}
{129}{}{error : string is empty -- }
