### {100}{}{Here is Rico.}
{100}{}{这是Rico。 -- Here is Rico.}
### {101}{}{You see a huge fellow with a silly expression on his face, but a very impressive look.}
{101}{}{你可以看到一个巨大的家伙，脸上有一个愚蠢的表情，但他的表情非常令人印象深刻。 -- You see a huge fellow with a silly expression on his face, but a very impressive look.}

### {110}{}{Shlushayu?}
{110}{}{什鲁沙育？ -- Shlushayu?}
### {111}{}{Don't, talk like a dwarf.}
{111}{}{不要像个侏儒一样说话。 -- Don't, talk like a dwarf.}
### {112}{}{Angelo is in charge here.}
{112}{}{安吉洛在这里负责。 -- Angelo is in charge here.}
### {113}{}{What do you need?}
{113}{}{你需要什么？ -- What do you need?}
### {114}{}{I hit without a miss.}
{114}{}{我打得很好。 -- I hit without a miss.}
### {115}{}{I want to eat.}
{115}{}{我想吃东西。 -- I want to eat.}
### {116}{}{Keep your hands where I can see them.}
{116}{}{把手放在我能看到的地方。 -- Keep your hands where I can see them.}
### {117}{}{You're looking for it, aren't you?}
{117}{}{你在找它，不是吗？ -- You're looking for it, aren't you?}
### {118}{}{Sit. I say SIT DOWN!}
{118}{}{坐我说坐下！ -- Sit. I say SIT DOWN!}
### {119}{}{Suck it!}
{119}{}{吸吧！ -- Suck it!}
### {120}{}{*Grumbling*}
{120}{}{*抱怨* -- *Grumbling*}
### {121}{}{*Kneads his hands in response*}
{121}{}{*跪着回应* -- *Kneads his hands in response*}
### {122}{}{You smell like a baby.}
{122}{}{你闻起来像个婴儿。 -- You smell like a baby.}
### {123}{}{Don't burn me.}
{123}{}{别烧了我。 -- Don't burn me.}
### {124}{}{Stop talking.}
{124}{}{别说话了。 -- Stop talking.}
### {125}{}{It's time for me to go to sleep.}
{125}{}{我该睡觉了。 -- It's time for me to go to sleep.}
### {126}{}{Do you need a coach?}
{126}{}{你需要教练吗？ -- Do you need a coach?}
### {127}{}{Yeah}
{127}{}{是 啊 -- Yeah}
### {128}{}{The exit is there.}
{128}{}{出口就在那里。 -- The exit is there.}
### {129}{}{Don't come near me.}
{129}{}{不要靠近我。 -- Don't come near me.}
### {130}{}{*Looks at you blankly*}
{130}{}{*茫然地看着你* -- *Looks at you blankly*}
### {131}{}{What do you need?}
{131}{}{你需要什么？ -- What do you need?}

### {150}{}{(enviously) Otl-personal fight.}
{150}{}{（羡慕地）我个人打架。 -- (enviously) Otl-personal fight.}
### {151}{}{You fight like a mad dog.}
{151}{}{你像疯狗一样打架。 -- You fight like a mad dog.}
### {152}{}{Who taught you how to fight?}
{152}{}{谁教你怎么打架？ -- Who taught you how to fight?}
### {153}{}{Don't hit me!}
{153}{}{别打我！ -- Don't hit me!}
### {154}{}{You're cute. I'm weak.}
{154}{}{你很可爱。我很虚弱。 -- You're cute. I'm weak.}
### {155}{}{I'm far away from you}
{155}{}{我离你很远 -- I'm far away from you}
### {156}{}{I won't fight you.}
{156}{}{我不会和你打架的。 -- I won't fight you.}
### {157}{}{You're not human. You're a beast.}
{157}{}{你不是人。你是个野兽。 -- You're not human. You're a beast.}
### {158}{}{I need a coach.}
{158}{}{我需要一个教练。 -- I need a coach.}
### {159}{}{Finish me off.}
{159}{}{干掉我。 -- Finish me off.}
### {160}{}{*Grumbling*}
{160}{}{*抱怨* -- *Grumbling*}
### {161}{}{*Smiling with a toothless mouth*}
{161}{}{*无牙微笑* -- *Smiling with a toothless mouth*}
### {162}{}{*Nods stupidly*}
{162}{}{*愚蠢地点头* -- *Nods stupidly*}

### {200}{}{*Crying like a baby*}
{200}{}{*哭得像个婴儿* -- *Crying like a baby*}
### {201}{}{Ange-e-e!}
{201}{}{Ange-e-e！ -- Ange-e-e!}
### {202}{}{Ange-ate! Ange-ate!}
{202}{}{安吉吃了！安吉吃了！ -- Ange-ate! Ange-ate!}
### {203}{}{*Whimper*}
{203}{}{*Whimper* -- *Whimper*}
### {204}{}{Uh-uh...}
{204}{}{呃。。。 -- Uh-uh...}
### {205}{}{*Groan*}
{205}{}{*Groan* -- *Groan*}
### {206}{}{Don't look! Don't look!}
{206}{}{别看！别看！ -- Don't look! Don't look!}
### {207}{}{I'll kill you! I'll kill everyone!}
{207}{}{我要杀了你！我要杀了所有人！ -- I'll kill you! I'll kill everyone!}
### {208}{}{Bitches! Bitches!}
{208}{}{婊子们！婊子们！ -- Bitches! Bitches!}
### {209}{}{Angelo was smart, I was stupid.}
{209}{}{安吉洛很聪明，我很愚蠢。 -- Angelo was smart, I was stupid.}
### {210}{}{Who did this?!}
{210}{}{谁干的？！ -- Who did this?!}
### {211}{}{Show me who did it!}
{211}{}{让我看看是谁干的！ -- Show me who did it!}
### {212}{}{Who killed my Angelo?}
{212}{}{谁杀了我的Angelo？ -- Who killed my Angelo?}
### {213}{}{*Takes a deep breath*}
{213}{}{*深呼吸* -- *Takes a deep breath*}
