### {100}{}{Here is a fan.}
{100}{}{这是一个风扇。 -- Here is a fan.}
### {101}{}{You see a man waiting listlessly for a new fight.}
{101}{}{你看到一个男人无精打采地等待着一场新的战斗。 -- You see a man waiting listlessly for a new fight.}
### {102}{}{You see a wild-looking man. He shouts furiously at the top of his voice.}
{102}{}{你看到一个看起来很狂野的人。他声嘶力竭地喊道。 -- You see a wild-looking man. He shouts furiously at the top of his voice.}

#Retaliatory remarks
### {110}{}{Waiting for a new fight}
{110}{}{等待新的战斗 -- Waiting for a new fight}
### {111}{}{How do you like the last fight?}
{111}{}{你觉得最后一场比赛怎么样？ -- How do you like the last fight?}
### {112}{}{Iron Mike no longer trains fighters.}
{112}{}{铁迈克不再训练战士。 -- Iron Mike no longer trains fighters.}
### {113}{}{Not a single good fight after Iron Mike.}
{113}{}{在Iron Mike之后，没有一场精彩的比赛。 -- Not a single good fight after Iron Mike.}
### {114}{}{Boring. When is the new fight?}
{114}{}{没趣的新的战斗是什么时候？ -- Boring. When is the new fight?}
### {115}{}{I'm putting all my caps on this fighter.}
{115}{}{我把我所有的帽子都戴在这架战斗机上。 -- I'm putting all my caps on this fighter.}
### {116}{}{Are you betting or participating?}
{116}{}{您是在下注还是参与？ -- Are you betting or participating?}
### {117}{}{This bet will be the last one.}
{117}{}{这将是最后一次下注。 -- This bet will be the last one.}
### {118}{}{}
{118}{}{error : string is empty -- }
### {119}{}{}
{119}{}{error : string is empty -- }

### {150}{}{Hello, champion.}
{150}{}{你好，冠军。 -- Hello, champion.}
### {151}{}{How are you, champ?}
{151}{}{你好吗，冠军？ -- How are you, champ?}
### {152}{}{Are you talking to me?}
{152}{}{你在和我说话吗？ -- Are you talking to me?}
### {153}{}{Oh my God, the champion is talking to me!}
{153}{}{天啊，冠军在和我说话！ -- Oh my God, the champion is talking to me!}
### {154}{}{Why don't you fight anymore?}
{154}{}{你为什么不再打架？ -- Why don't you fight anymore?}
### {155}{}{Hit me! I will tell the children.}
{155}{}{打我！我会告诉孩子们的。 -- Hit me! I will tell the children.}
### {156}{}{Hey, let me touch your biceps!}
{156}{}{嘿，让我摸摸你的二头肌！ -- Hey, let me touch your biceps!}
### {157}{}{Thanks to you, I'm in a good win.}
{157}{}{多亏了你，我赢了。 -- Thanks to you, I'm in a good win.}
### {158}{}{}
{158}{}{error : string is empty -- }
### {159}{}{}
{159}{}{error : string is empty -- }

### {160}{}{Hi. }
{160}{}{你好 -- Hi. }
### {161}{}{Enjoying the victory?}
{161}{}{享受胜利吗？ -- Enjoying the victory?}
### {162}{}{Hey, hey, take it easy!}
{162}{}{嘿，嘿，别紧张！ -- Hey, hey, take it easy!}
### {163}{}{Cool, champ, but I bet on your opponent. So now I'm bankrupt...}
{163}{}{很酷，冠军，但我把赌注押在你的对手身上。所以现在我破产了。。。 -- Cool, champ, but I bet on your opponent. So now I'm bankrupt...}
### {164}{}{Why don't you fight anymore?}
{164}{}{你为什么不再打架？ -- Why don't you fight anymore?}
### {165}{}{Just try to hit me.}
{165}{}{试着打我。 -- Just try to hit me.}
### {166}{}{Aren't your biceps tight?}
{166}{}{你的二头肌不紧吗？ -- Aren't your biceps tight?}
### {167}{}{My bet went down because of you. Well, save-for.}
{167}{}{因为你，我的赌注降低了。好吧，除了。 -- My bet went down because of you. Well, save-for.}
### {168}{}{}
{168}{}{error : string is empty -- }
### {169}{}{}
{169}{}{error : string is empty -- }

#Random phrases outside of combat
### {170}{}{When is the new fight?}
{170}{}{新的战斗是什么时候？ -- When is the new fight?}
### {171}{}{Boring.}
{171}{}{没趣的 -- Boring.}
### {172}{}{The ring is missing something.}
{172}{}{戒指少了什么东西。 -- The ring is missing something.}
### {173}{}{   }
{173}{}{error : string is empty --    }
### {174}{}{  }
{174}{}{error : string is empty --   }
### {175}{}{   }
{175}{}{error : string is empty --    }
### {176}{}{   }
{176}{}{error : string is empty --    }
### {177}{}{   }
{177}{}{error : string is empty --    }
### {178}{}{   }
{178}{}{error : string is empty --    }
### {179}{}{   }
{179}{}{error : string is empty --    }

#Random phrases during combat
### {180}{}{I'm betting on this fighter.}
{180}{}{我把赌注押在这架战斗机上。 -- I'm betting on this fighter.}
### {181}{}{Go ahead!}
{181}{}{着手 -- Go ahead!}
### {182}{}{Finish him off!}
{182}{}{干掉他！ -- Finish him off!}
### {183}{}{I adore you!}
{183}{}{我崇拜你！ -- I adore you!}
### {184}{}{On the right! Right come in!}
{184}{}{在右边！进来！ -- On the right! Right come in!}
### {185}{}{Defend yourself!}
{185}{}{保护好自己！ -- Defend yourself!}
### {186}{}{You won't see a more boring fight.}
{186}{}{你再也看不到比这更无聊的打斗了。 -- You won't see a more boring fight.}
### {187}{}{I will never forget this fight.}
{187}{}{我永远不会忘记这场战斗。 -- I will never forget this fight.}
### {188}{}{I can't stand this heat.}
{188}{}{我受不了这么热。 -- I can't stand this heat.}
### {189}{}{*Whistles*}
{189}{}{*口哨* -- *Whistles*}
### {190}{}{*Screams*}
{190}{}{*尖叫* -- *Screams*}
### {191}{}{Hit him! Hit!}
{191}{}{打他！打 -- Hit him! Hit!}
### {192}{}{Come on!}
{192}{}{来吧 -- Come on!}
### {193}{}{Don't slow down!}
{193}{}{不要慢下来！ -- Don't slow down!}

### {194}{}{!}
{194}{}{！ -- !}
### {195}{}{Forward, }
{195}{}{向前地 -- Forward, }
### {196}{}{You're the best, }
{196}{}{你是最棒的， -- You're the best, }
### {197}{}{Finish him off, }
{197}{}{干掉他， -- Finish him off, }
### {198}{}{I'm betting on you, }
{198}{}{我在赌你， -- I'm betting on you, }
### {199}{}{Make it, }
{199}{}{成功吧， -- Make it, }
