### {100}{}{You see the squatter.}
{100}{}{你看到那个擅自占用者了。 -- You see the squatter.}
### {101}{}{In front of you is a thin man in dirty clothes.}
{101}{}{你面前是一个穿着脏衣服的瘦子。 -- In front of you is a thin man in dirty clothes.}
### {102}{}{*Crunch-crunch*}
{102}{}{*嘎吱嘎吱* -- *Crunch-crunch*}
### {103}{}{It was the cardinals! They blew up the station!}
{103}{}{是红衣主教们！他们炸毁了车站！ -- It was the cardinals! They blew up the station!}

#Dialog
### {200}{}{Oh, Mom, don't scare me like that! People rarely come here.}
{200}{}{哦，妈妈，别那样吓我！人们很少来这里。 -- Oh, Mom, don't scare me like that! People rarely come here.}
### {201}{}{Sorry, I didn't mean to. What are you doing here?}
{201}{}{对不起，我不是故意的。你在这里干什么？ -- Sorry, I didn't mean to. What are you doing here?}
### {1201}{}{Sorry, I didn't mean to. What are you doing here?}
{1201}{}{对不起，我不是故意的。你在这里干什么？ -- Sorry, I didn't mean to. What are you doing here?}
### {202}{}{Idiot! You made my heart sink into my heels. What are you doing here anyway?}
{202}{}{蠢人你让我心碎。你在这里干什么？ -- Idiot! You made my heart sink into my heels. What are you doing here anyway?}
### {203}{}{Catching rats. They are fast and cunning, they will not fall into the trap so easily. Sometimes you have to wait for hours in ambush.}
{203}{}{抓老鼠。他们又快又狡猾，不会那么容易落入陷阱。有时你不得不在伏击中等上几个小时。 -- Catching rats. They are fast and cunning, they will not fall into the trap so easily. Sometimes you have to wait for hours in ambush.}
### {204}{}{Well, good luck in your difficult task. Bye.}
{204}{}{祝你在艰巨的任务中好运。再见 -- Well, good luck in your difficult task. Bye.}
### {205}{}{If you've been here for a long time, then surely you know who passed into the eastern sewers?}
{205}{}{如果你在这里呆了很长时间，那么你肯定知道是谁进入了东部下水道？ -- If you've been here for a long time, then surely you know who passed into the eastern sewers?}
### {206}{}{Yeah. And what will happen to me if I tell you?}
{206}{}{是 啊如果我告诉你，我会怎么样？ -- Yeah. And what will happen to me if I tell you?}
### {207}{}{I'll give you some food. Wait, I'll get something now...}
{207}{}{我给你一些食物。等等，我现在就拿点东西。。。 -- I'll give you some food. Wait, I'll get something now...}
### {208}{}{You've already had enough food. Now tell me.}
{208}{}{你已经吃够了。现在告诉我。 -- You've already had enough food. Now tell me.}
### {209}{}{Here are ten caps for your food.}
{209}{}{这是你的食物的十顶帽子。 -- Here are ten caps for your food.}
### {210}{}{Oh, thank you very much.}
{210}{}{哦，非常感谢。 -- Oh, thank you very much.}
### {211}{}{Now tell me.}
{211}{}{现在告诉我。 -- Now tell me.}
### {212}{}{Sorry, but my wallet is empty.}
{212}{}{对不起，我的钱包是空的。 -- Sorry, but my wallet is empty.}
### {213}{}{I'll keep you alive, you piece of shit.}
{213}{}{我会让你活着的，你这个混蛋。 -- I'll keep you alive, you piece of shit.}
### {214}{}{Go away! Or I'll set a pack of rats on you. Shoo! Shoo!}
{214}{}{走开！否则我会把一群老鼠放在你身上。嘘！嘘！ -- Go away! Or I'll set a pack of rats on you. Shoo! Shoo!}
### {215}{}{Well, well. }
{215}{}{嗯，嗯。 -- Well, well. }
### {216}{}{Still have to get your hands dirty. Tell me what you saw!}
{216}{}{还是得把手弄脏。告诉我你看到了什么！ -- Still have to get your hands dirty. Tell me what you saw!}
### {217}{}{I'll keep you alive, you piece of shit.}
{217}{}{我会让你活着的，你这个混蛋。 -- I'll keep you alive, you piece of shit.}
### {218}{}{Have mercy! I'll tell you everything!}
{218}{}{宽恕吧！我会告诉你一切的！ -- Have mercy! I'll tell you everything!}
### {219}{}{Come on, tell me.}
{219}{}{来吧，告诉我。 -- Come on, tell me.}
### {220}{}{They were cardinals. There was also a monk and a dead man with them. They said they wanted to blow up some pipes in order to deceive the chief at the station. Well, they have some kind of complicated history, I didn't understand anything.}
{220}{}{他们是红衣主教。还有一个和尚和一个死人和他们在一起。他们说他们想炸毁一些管道，以欺骗车站的站长。他们有一些复杂的历史，我什么都不懂。 -- They were cardinals. There was also a monk and a dead man with them. They said they wanted to blow up some pipes in order to deceive the chief at the station. Well, they have some kind of complicated history, I didn't understand anything.}
### {221}{}{Well done, live for now.}
{221}{}{干得好，活在当下。 -- Well done, live for now.}
### {222}{}{Thanks, buddy. You've helped me a lot.}
{222}{}{谢谢，伙计。你帮了我很多。 -- Thanks, buddy. You've helped me a lot.}

### {250}{}{Hello. I've been seeing a lot of people here lately.}
{250}{}{你好我最近在这里见到很多人。 -- Hello. I've been seeing a lot of people here lately.}
### {251}{}{Thanks for the food. Is there more?}
{251}{}{谢谢你的食物。还有更多吗？ -- Thanks for the food. Is there more?}
### {252}{}{What are you doing here?}
{252}{}{你在这里干什么？ -- What are you doing here?}
### {253}{}{Bye.}
{253}{}{再见 -- Bye.}
