### {100}{}{There are ads in front of you.}
{100}{}{你面前有广告。 -- There are ads in front of you.}
### {101}{}{You see a board with some ads.}
{101}{}{你看到一块广告牌。 -- You see a board with some ads.}
### {102}{}{In front of you is a bulletin board. It is worth studying them more carefully.}
{102}{}{你面前是一块公告牌。值得更仔细地研究它们。 -- In front of you is a bulletin board. It is worth studying them more carefully.}

### {200}{}{(In front of you is a fairly scribbled bulletin board)}
{200}{}{（你面前是一块字迹潦草的公告牌） -- (In front of you is a fairly scribbled bulletin board)}
### {201}{}{Leave.}
{201}{}{离开 -- Leave.}
### {202}{}{I see.}
{202}{}{我明白了。 -- I see.}
### {203}{}{Back.}
{203}{}{返回 -- Back.}

### {210}{}{Dangerous areas.}
{210}{}{危险区域。 -- Dangerous areas.}
### {211}{}{(You are looking at the map of Phoenix, where the most unfavorable areas are marked. The largest of them are signed: "Orris Territory", "Atomic Scientists", "Red Cardinals".)}
{211}{}{（你正在看凤凰城的地图，地图上标出了最不利的地区。其中最大的地区署名：“奥利斯领地”、“原子科学家”、“红雀”。） -- (You are looking at the map of Phoenix, where the most unfavorable areas are marked. The largest of them are signed: "Orris Territory", "Atomic Scientists", "Red Cardinals".)}

### {220}{}{Beware of the mainline drivers!}
{220}{}{小心主线司机！ -- Beware of the mainline drivers!}
### {221}{}{Beware of highway robbers on highways 10 and 17. Most of them are poorly armed and few in number, but there are particularly dangerous clans. These bandits attack travelers and caravans without pity and regret. Don't even try to negotiate with them.}
{221}{}{小心10号和17号高速公路上的高速公路劫匪。他们中的大多数人装备简陋，人数很少，但也有特别危险的部族。这些土匪毫无怜悯和遗憾地袭击旅行家和商队。甚至不要试图与他们谈判。 -- Beware of highway robbers on highways 10 and 17. Most of them are poorly armed and few in number, but there are particularly dangerous clans. These bandits attack travelers and caravans without pity and regret. Don't even try to negotiate with them.}

### {230}{}{The Los Panchos Gang.}
{230}{}{洛斯潘乔斯帮。 -- The Los Panchos Gang.}
### {231}{}{Attention! Especially dangerous criminals are wanted - the atamans of the Los Panchos gang. (their portraits are attached) Payment of 500 caps per head of each.}
{231}{}{注意特别危险的罪犯被通缉——洛斯潘乔斯团伙的共济会成员。（附上他们的肖像）每人支付500顶帽子。 -- Attention! Especially dangerous criminals are wanted - the atamans of the Los Panchos gang. (their portraits are attached) Payment of 500 caps per head of each.}
### {232}{}{Hernando Aviles.}
{232}{}{埃尔南多·阿维莱斯。 -- Hernando Aviles.}
### {233}{}{[Crossed out] Hernando Aviles.}
{233}{}{[划掉]埃尔南多·阿维莱斯。 -- [Crossed out] Hernando Aviles.}
### {234}{}{Former security guard. Killed his own master and his entire family during a robbery. After that, he began to wander through the desert, where he joined the ranks of the Los Panchos gang. By nature, he is calm and cold-blooded. Likes to talk to his victims before killing.}
{234}{}{前保安。在一次抢劫中杀死了自己的主人和全家。在那之后，他开始在沙漠中游荡，在那里他加入了洛斯潘乔斯帮派的行列。他生性冷静、冷血。喜欢在杀人前与受害者交谈。 -- Former security guard. Killed his own master and his entire family during a robbery. After that, he began to wander through the desert, where he joined the ranks of the Los Panchos gang. By nature, he is calm and cold-blooded. Likes to talk to his victims before killing.}
### {235}{}{Chucho Navarro.}
{235}{}{Chucho Navarro。 -- Chucho Navarro.}
### {236}{}{[Crossed out] Chucho Navarro.}
{236}{}{Chucho Navarro。 -- [Crossed out] Chucho Navarro.}
### {237}{}{In the past, an ordinary handyman. He escaped from slavery after he got there for debts. He is known for a craving for torture. Mentally unstable.}
{237}{}{过去，一个普通的杂工。他因欠债到那里后逃离了奴隶制度。他以渴望酷刑而闻名。精神不稳定。 -- In the past, an ordinary handyman. He escaped from slavery after he got there for debts. He is known for a craving for torture. Mentally unstable.}
### {238}{}{Aidi Gorme.}
{238}{}{艾迪·戈姆。 -- Aidi Gorme.}
### {239}{}{[Crossed out] Aidy Gorme.}
{239}{}{Aidy Gorme。 -- [Crossed out] Aidy Gorme.}
### {240}{}{Former singer. Robbed the casino where she worked. After that, she disappeared with her accomplices in the desert, where she joined the Los Panchos gang. Having earned the respect of the gang, she eventually rose to the rank of ataman. She is known for her special cruelty, emotional intemperance and craving for cannibalism.}
{240}{}{前歌手。抢劫了她工作的赌场。在那之后，她和她的同伙一起消失在沙漠中，在那里她加入了洛斯潘乔斯帮派。她赢得了帮派的尊重，最终晋升为共济会会员。她以其特殊的残忍、情感上的放纵和对食人的渴望而闻名。 -- Former singer. Robbed the casino where she worked. After that, she disappeared with her accomplices in the desert, where she joined the Los Panchos gang. Having earned the respect of the gang, she eventually rose to the rank of ataman. She is known for her special cruelty, emotional intemperance and craving for cannibalism.}

### {250}{}{Gil McCord is wanted.}
{250}{}{吉尔·麦考德被通缉。 -- Gil McCord is wanted.}
### {251}{}{The former shooter Gil McCord is wanted for attacks on representatives of the mercenary guild. Reward 750 caps for dead or alive.}
{251}{}{前枪手吉尔·麦考德因袭击雇佣兵协会代表而被通缉。奖励750顶死亡或活着的帽子。 -- The former shooter Gil McCord is wanted for attacks on representatives of the mercenary guild. Reward 750 caps for dead or alive.}
### {252}{}{[Crossed out] Gil McCord is wanted.}
{252}{}{吉尔·麦考德被通缉。 -- [Crossed out] Gil McCord is wanted.}

### {260}{}{Wanted }
{260}{}{受通缉的 -- Wanted }
### {261}{}{ from the Villa... what?}
{261}{}{从别墅。。。什么 --  from the Villa... what?}
### {262}{}{Wanted for numerous crimes against Phoenix residents. Any contact with this person can cost you your life.}
{262}{}{因对凤凰城居民犯下多项罪行而被通缉。与这个人的任何接触都可能让你付出生命的代价。 -- Wanted for numerous crimes against Phoenix residents. Any contact with this person can cost you your life.}
### {263}{}{Wanted for numerous crimes against the Church of the Sacred Fire. Any contact with this heretic can cost you your reputation and well-being.}
{263}{}{因对圣火教会犯下多项罪行而被通缉。与这个异教徒的任何接触都会让你失去名誉和幸福。 -- Wanted for numerous crimes against the Church of the Sacred Fire. Any contact with this heretic can cost you your reputation and well-being.}
