### {102}{}{It won't help here.}
{102}{}{这对这里没有帮助。 -- It won't help here.}

### {110}{}{This is equipment for amplifying radio broadcasts.}
{110}{}{这是放大无线电广播的设备。 -- This is equipment for amplifying radio broadcasts.}
### {111}{}{This is equipment for amplifying radio broadcasts.}
{111}{}{这是放大无线电广播的设备。 -- This is equipment for amplifying radio broadcasts.}
### {112}{}{You have installed the hardware.}
{112}{}{您已经安装了硬件。 -- You have installed the hardware.}
### {113}{}{The equipment is already installed.}
{113}{}{设备已安装。 -- The equipment is already installed.}
