### {100}{}{You see the assistant.}
{100}{}{你看到助理了。 -- You see the assistant.}
### {101}{}{Here is one of the laboratory assistants. He is busy with calculations and does not pay attention to you.}
{101}{}{这是一位实验室助理。他忙于计算，不注意你。 -- Here is one of the laboratory assistants. He is busy with calculations and does not pay attention to you.}

### {110}{}{I'm too busy...}
{110}{}{我太忙了。。。 -- I'm too busy...}
### {111}{}{What's wrong? Why did the alarm go off?}
{111}{}{怎么了？为什么闹钟响了？ -- What's wrong? Why did the alarm go off?}
