### {100}{}{You can see the console.}
{100}{}{您可以看到控制台。 -- You can see the console.}
### {101}{}{In front of you is the console of the prison block. Force fields can be controlled through it.}
{101}{}{在你面前是监狱的控制台。力场可以通过它来控制。 -- In front of you is the console of the prison block. Force fields can be controlled through it.}
### {102}{}{The force fields of the prison block are disabled.}
{102}{}{监狱区的兵力场已禁用。 -- The force fields of the prison block are disabled.}
### {103}{}{The security clearance level is not high enough.}
{103}{}{安全许可级别不够高。 -- The security clearance level is not high enough.}

### {200}{}{Enter the command.}
{200}{}{输入命令。 -- Enter the command.}
### {201}{}{Disable the force field of camera 1.}
{201}{}{禁用摄像头1的力场。 -- Disable the force field of camera 1.}
### {202}{}{Activate the force field of camera 1.}
{202}{}{激活相机1的力场。 -- Activate the force field of camera 1.}
### {203}{}{Disable the force field of camera 2.}
{203}{}{禁用摄像机2的力场。 -- Disable the force field of camera 2.}
### {204}{}{Activate the force field of camera 2.}
{204}{}{激活相机2的力场。 -- Activate the force field of camera 2.}
### {205}{}{Disable the camera's force field 3.}
{205}{}{禁用相机的力场3。 -- Disable the camera's force field 3.}
### {206}{}{Activate the camera's force field 3.}
{206}{}{激活摄影机的力场3。 -- Activate the camera's force field 3.}
### {207}{}{Back.}
{207}{}{返回 -- Back.}
### {208}{}{End session.}
{208}{}{结束会话。 -- End session.}
