### {100}{}{This is Mr. Milton.}
{100}{}{这是米尔顿先生。 -- This is Mr. Milton.}
### {101}{}{You see the father of the Milton family.}
{101}{}{你看到了米尔顿家族的父亲。 -- You see the father of the Milton family.}

#Dialog
### {110}{}{We have nothing to pay with, but you won't leave us alone with these pig rats, will you?}
{110}{}{我们没有什么可付的，但你不会让我们一个人和这些猪老鼠在一起，是吗？ -- We have nothing to pay with, but you won't leave us alone with these pig rats, will you?}
### {111}{}{Stop him, you're rangers!}
{111}{}{阻止他，你们是护林员！ -- Stop him, you're rangers!}
### {112}{}{Thank you for saving us. Now I have a better opinion of you.}
{112}{}{谢谢你救了我们。现在我对你有了更好的看法。 -- Thank you for saving us. Now I have a better opinion of you.}
### {113}{}{Thank you for your help, but it won't bring my wife back.}
{113}{}{谢谢你的帮助，但这不会让我妻子回来。 -- Thank you for your help, but it won't bring my wife back.}
### {114}{}{What's the use of you, damn rangers?! Get out!}
{114}{}{你有什么用，该死的护林员？！滚出去！ -- What's the use of you, damn rangers?! Get out!}
### {115}{}{Don't come near me!}
{115}{}{不要靠近我！ -- Don't come near me!}
### {116}{}{Did Nat-Aani give up the ghost? Ugh, what a relief!}
{116}{}{Nat Aani放弃鬼魂了吗？啊，真是松了一口气！ -- Did Nat-Aani give up the ghost? Ugh, what a relief!}
