### {100}{}{You have a child in front of you.}
{100}{}{你面前有个孩子。 -- You have a child in front of you.}
### {101}{}{You see the child of the Milton family.}
{101}{}{你看到了米尔顿家族的孩子。 -- You see the child of the Milton family.}

#Dialog
### {110}{}{Hi. Have you come to rid us of rodents?}
{110}{}{你好你是来消灭我们的啮齿动物的吗？ -- Hi. Have you come to rid us of rodents?}
### {111}{}{Save my parents!}
{111}{}{救救我的父母！ -- Save my parents!}
### {112}{}{Rangers are really cool. When I grow up, I will also become a cadet.}
{112}{}{游骑兵真的很酷。当我长大后，我也将成为一名学员。 -- Rangers are really cool. When I grow up, I will also become a cadet.}
### {113}{}{It's all because of you! Go away!}
{113}{}{都是因为你！走开！ -- It's all because of you! Go away!}
### {114}{}{It's all because of you! Go away!}
{114}{}{都是因为你！走开！ -- It's all because of you! Go away!}
### {115}{}{Don't come near me!}
{115}{}{不要靠近我！ -- Don't come near me!}
### {116}{}{Thank you for saving us from this terrible monster.}
{116}{}{谢谢你把我们从这个可怕的怪物手中救了出来。 -- Thank you for saving us from this terrible monster.}

### {200}{}{Wait! There... there... There's a bandit!}
{200}{}{等待那里那里有个土匪！ -- Wait! There... there... There's a bandit!}
### {201}{}{Where is the bandit?}
{201}{}{土匪在哪里？ -- Where is the bandit?}
### {202}{}{Calm down, I won't understand what you're saying.}
{202}{}{冷静点，我听不懂你在说什么。 -- Calm down, I won't understand what you're saying.}
### {203}{}{The bandit is in our hut! He's got a gun, he's tied up Dad and Mom! Save them!}
{203}{}{土匪在我们的小屋里！他拿着枪，把爸爸妈妈捆起来了！拯救他们！ -- The bandit is in our hut! He's got a gun, he's tied up Dad and Mom! Save them!}
### {204}{}{Stay here. We'll see what we can do.}
{204}{}{待在这儿我们拭目以待。 -- Stay here. We'll see what we can do.}
### {205}{}{Then move over, little ones, this is a case for real pros.}
{205}{}{然后转移，小家伙，这是一个真正的专业人士的情况。 -- Then move over, little ones, this is a case for real pros.}
### {206}{}{No, kid, it was a big pig-rat...}
{206}{}{不，孩子，那是一只大猪鼠。。。 -- No, kid, it was a big pig-rat...}
