### {110}{}{This mechanism is started by means of a winch. But someone pulled the handle out of it.}
{110}{}{这个机构是通过绞盘启动的。但有人把它的把手拔了出来。 -- This mechanism is started by means of a winch. But someone pulled the handle out of it.}
### {111}{}{This mechanism sets the platform in motion.}
{111}{}{这个机构使平台运转起来。 -- This mechanism sets the platform in motion.}
### {112}{}{The mechanism is back in action. Now you can start the ferry.}
{112}{}{该机制已恢复运行。现在你可以开渡船了。 -- The mechanism is back in action. Now you can start the ferry.}
