### {110}{}{This lifting mechanism holds the dam gate with steel cables.}
{110}{}{该提升机构用钢索固定大坝闸门。 -- This lifting mechanism holds the dam gate with steel cables.}
### {111}{}{The lifting mechanism is out of order. It can hardly be repaired.}
{111}{}{升降机构失灵。它几乎无法修理。 -- The lifting mechanism is out of order. It can hardly be repaired.}
### {112}{}{There was not even a scratch on the mechanism.}
{112}{}{机械装置上甚至一点划痕都没有。 -- There was not even a scratch on the mechanism.}
### {113}{}{The lifting mechanism shatters into pieces, and the load-bearing cables fall into the darkness with a whoosh. Soon, at the bottom of the mine, you hear a strong rumble of a falling shutter.}
{113}{}{升降机构破碎成碎片，承重电缆“嗖”的一声落入黑暗。很快，在矿井底部，你会听到百叶窗掉下来的强烈隆隆声。 -- The lifting mechanism shatters into pieces, and the load-bearing cables fall into the darkness with a whoosh. Soon, at the bottom of the mine, you hear a strong rumble of a falling shutter.}
### {114}{}{It seems the Rangers are waiting... a small flood.}
{114}{}{看来游骑兵队在等着。。。小洪水。 -- It seems the Rangers are waiting... a small flood.}
