### {100}{}{Here is a soldier of the Brotherhood.}
{100}{}{这是兄弟会的一名士兵。 -- Here is a soldier of the Brotherhood.}
### {101}{}{You see a warrior of the Brotherhood of Steel.}
{101}{}{你看到的是钢铁兄弟会的战士。 -- You see a warrior of the Brotherhood of Steel.}

### {110}{}{Keep an eye on the rear.}
{110}{}{注意后方。 -- Keep an eye on the rear.}
### {111}{}{You should always be on your guard here.}
{111}{}{你应该时刻保持警惕。 -- You should always be on your guard here.}
### {112}{}{Watch your step. They could have set traps.}
{112}{}{小心脚下。他们本可以设置陷阱的。 -- Watch your step. They could have set traps.}
### {113}{}{These desperados are desperate guys.}
{113}{}{这些亡命之徒是绝望的家伙。 -- These desperados are desperate guys.}
### {114}{}{In this operation, you don't have to save ammo.}
{114}{}{在这次行动中，你不必节省弹药。 -- In this operation, you don't have to save ammo.}
