### {100}{}{This is the scribes' computer.}
{100}{}{这是抄写员的电脑。 -- This is the scribes' computer.}
### {101}{}{Here is a computer with access to a shared network.}
{101}{}{这是一台可以访问共享网络的计算机。 -- Here is a computer with access to a shared network.}
### {102}{}{You have successfully copied the scribes library.}
{102}{}{您已成功复制抄写员库。 -- You have successfully copied the scribes library.}
### {103}{}{You have already copied the library to the holodisk.}
{103}{}{您已经将库复制到全息光盘。 -- You have already copied the library to the holodisk.}

#Dialog
### {200}{}{Enter the command.}
{200}{}{输入命令。 -- Enter the command.}
### {201}{}{End session.}
{201}{}{结束会话。 -- End session.}
### {202}{}{Back.}
{202}{}{返回 -- Back.}
### {203}{}{Next.}
{203}{}{下一个 -- Next.}
### {204}{}{Go back to the main menu.}
{204}{}{返回主菜单。 -- Go back to the main menu.}

### {210}{}{Vault-Tec Vault Search.}
{210}{}{Vault Tec Vault搜索。 -- Vault-Tec Vault Search.}
### {211}{}{According to the latest data, Vault-Tec Vaults with numbers 25-28 may be located in the vicinity of Phoenix. The General Staff of the Brotherhood of Steel ordered to find all these Vaults, study the situation and use the resources and equipment available there for self-sufficiency or export to the General Staff.}
{211}{}{根据最新数据，编号为25-28的Vault Tec Vault可能位于菲尼克斯附近。钢铁兄弟会总参谋部下令找到所有这些金库，研究情况，并利用那里可用的资源和设备自给自足或出口给总参谋部。 -- According to the latest data, Vault-Tec Vaults with numbers 25-28 may be located in the vicinity of Phoenix. The General Staff of the Brotherhood of Steel ordered to find all these Vaults, study the situation and use the resources and equipment available there for self-sufficiency or export to the General Staff.}
### {212}{}{}
{212}{}{error : string is empty -- }
### {213}{}{}
{213}{}{error : string is empty -- }
### {214}{}{Vault 24.}
{214}{}{保险库24。 -- Vault 24.}
### {215}{}{Location: Otay Open Space National Nature Reserve, San Diego, California. The condition is unknown. The population is unknown. The Vault is probably located in a zone of high radioactive contamination.}
{215}{}{地点：奥泰开放空间国家自然保护区，圣地亚哥，加利福尼亚州。情况未知。人口不详。保险库可能位于高放射性污染区。 -- Location: Otay Open Space National Nature Reserve, San Diego, California. The condition is unknown. The population is unknown. The Vault is probably located in a zone of high radioactive contamination.}
### {216}{}{Vault 25.}
{216}{}{保险库25。 -- Vault 25.}
### {217}{}{The Vault was found in Phoenix and is in perfect condition. It is currently under the control of the Brotherhood of Steel and is used as a base for the Cathedral of Fire. Some equipment has been dismantled and taken to the outpost in Puerto Penasco.}
{217}{}{金库是在凤凰城发现的，目前状况良好。它目前由钢铁兄弟会控制，并被用作火之大教堂的基地。一些设备已被拆除，并被送往佩纳斯科港的前哨基地。 -- The Vault was found in Phoenix and is in perfect condition. It is currently under the control of the Brotherhood of Steel and is used as a base for the Cathedral of Fire. Some equipment has been dismantled and taken to the outpost in Puerto Penasco.}
### {218}{}{Vault 26.}
{218}{}{保险库26。 -- Vault 26.}
### {219}{}{The remains of the Vault were found to the west of Phoenix. Due to the severe damage sustained during the nuclear bombing, the Vault, along with its equipment, fell into complete disrepair.}
{219}{}{金库的遗迹是在凤凰城的西面发现的。由于核轰炸期间受到严重破坏，金库及其设备年久失修。 -- The remains of the Vault were found to the west of Phoenix. Due to the severe damage sustained during the nuclear bombing, the Vault, along with its equipment, fell into complete disrepair.}
### {220}{}{Vault 27.}
{220}{}{保险库27。 -- Vault 27.}
### {221}{}{There is information about the location of the Vault. At the moment, the search and excavation of the Vault is underway by the forces of the Cathedral of Fire under the leadership of Paladin Ulysses Grant.}
{221}{}{有关于Vault位置的信息。目前，在圣骑士尤利西斯·格兰特的领导下，火之大教堂的部队正在对金库进行搜索和挖掘。 -- There is information about the location of the Vault. At the moment, the search and excavation of the Vault is underway by the forces of the Cathedral of Fire under the leadership of Paladin Ulysses Grant.}
### {222}{}{Vault 28.}
{222}{}{金库28。 -- Vault 28.}
### {223}{}{The location and condition of the Vault are unknown.}
{223}{}{Vault的位置和状况未知。 -- The location and condition of the Vault are unknown.}

### {230}{}{Development of nanostructured cartridges.}
{230}{}{纳米结构药筒的开发。 -- Development of nanostructured cartridges.}
### {231}{}{Due to the shortage of armor-piercing ammunition and the periodic need for it, limited production of 10 mm cartridges made of nanostructured metal was established.}
{231}{}{由于穿甲弹的短缺和对它的周期性需求，由纳米结构金属制成的10毫米弹壳的生产受到限制。 -- Due to the shortage of armor-piercing ammunition and the periodic need for it, limited production of 10 mm cartridges made of nanostructured metal was established.}
### {232}{}{A tribe of tinsmiths in Two-Sun is engaged in the manufacture of bullets under a standard trade contract.}
{232}{}{两个太阳的一个锡匠部落根据标准贸易合同从事子弹制造。 -- A tribe of tinsmiths in Two-Sun is engaged in the manufacture of bullets under a standard trade contract.}
### {233}{}{}
{233}{}{error : string is empty -- }
### {234}{}{Food self-sufficiency.}
{234}{}{粮食自给自足。 -- Food self-sufficiency.}
### {235}{}{We managed to fully cover our food requests thanks to the Casa Nueva plantations. At the moment, the harvest is also being exported.}
{235}{}{多亏了Casa Nueva种植园，我们成功地满足了我们的食物需求。目前，收获的粮食也正在出口。 -- We managed to fully cover our food requests thanks to the Casa Nueva plantations. At the moment, the harvest is also being exported.}
### {236}{}{Development of nuclear weapons.}
{236}{}{发展核武器。 -- Development of nuclear weapons.}
### {237}{}{In accordance with the request of the General Staff, we are moving to the production of nuclear weapons. At the moment, the project documentation has been completed and the necessary amount of nuclear material is being extracted.}
{237}{}{根据总参谋部的要求，我们正在着手生产核武器。目前，项目文件已经完成，正在提取必要数量的核材料。 -- In accordance with the request of the General Staff, we are moving to the production of nuclear weapons. At the moment, the project documentation has been completed and the necessary amount of nuclear material is being extracted.}
### {238}{}{For reasons of security, logistics and time savings, the assembly of the final weapon is carried out by representatives of the Phoenix Cathedral of Fire under the strict control of the Brotherhood of Steel.}
{238}{}{出于安全、后勤和节省时间的考虑，最终武器的组装由凤凰城火焰大教堂的代表在钢铁兄弟会的严格控制下进行。 -- For reasons of security, logistics and time savings, the assembly of the final weapon is carried out by representatives of the Phoenix Cathedral of Fire under the strict control of the Brotherhood of Steel.}
