### {100}{}{Port on board!}
{100}{}{船上的港口！ -- Port on board!}
### {101}{}{Hey, on deck!}
{101}{}{嘿，在甲板上！ -- Hey, on deck!}
### {102}{}{Whistle everyone up!}
{102}{}{把所有人都吹起来！ -- Whistle everyone up!}
### {103}{}{Bunks down and ready to fight!}
{103}{}{蹲下来准备战斗！ -- Bunks down and ready to fight!}
### {104}{}{I'll be damned if this tin can moves...}
{104}{}{如果这个罐子能动，我会被诅咒的。。。 -- I'll be damned if this tin can moves...}
### {105}{}{Okay, that's enough. It already looks silly.}
{105}{}{好了，够了。它看起来已经很傻了。 -- Okay, that's enough. It already looks silly.}
