### {100}{}{You see the guard.}
{100}{}{你看到警卫了。 -- You see the guard.}
### {101}{}{In front of you is a caravan guard. He is resting after a tiring journey.}
{101}{}{你面前是一个大篷车警卫。经过一段劳累的旅程，他正在休息。 -- In front of you is a caravan guard. He is resting after a tiring journey.}

### {110}{}{Great.}
{110}{}{太棒了 -- Great.}
### {111}{}{Let me rest.}
{111}{}{让我休息。 -- Let me rest.}
### {112}{}{Do you want to travel with us?}
{112}{}{你想和我们一起旅行吗？ -- Do you want to travel with us?}
### {113}{}{There is a restless road between Phoenix and Fog.}
{113}{}{凤凰和雾之间有一条不安分的路。 -- There is a restless road between Phoenix and Fog.}
### {114}{}{Dust storms are sometimes more dangerous than raiders.}
{114}{}{沙尘暴有时比袭击者更危险。 -- Dust storms are sometimes more dangerous than raiders.}
### {115}{}{We have a dangerous job.}
{115}{}{我们的工作很危险。 -- We have a dangerous job.}
### {116}{}{Talk to the boss, I'm just guarding the cargo.}
{116}{}{跟老板说，我只是在看管货物。 -- Talk to the boss, I'm just guarding the cargo.}
### {117}{}{I'd stay away from tinsmiths if I were you.}
{117}{}{如果我是你，我会远离铁匠。 -- I'd stay away from tinsmiths if I were you.}
### {118}{}{Need some advice? Don't go to the local doctor.}
{118}{}{需要一些建议吗？不要去看当地的医生。 -- Need some advice? Don't go to the local doctor.}
### {119}{}{I'd rather go back to Phoenix.}
{119}{}{我宁愿回凤凰城。 -- I'd rather go back to Phoenix.}
### {120}{}{Tinsmiths don't like strangers and try to avoid unnecessary conversations.}
{120}{}{铁匠不喜欢陌生人，尽量避免不必要的谈话。 -- Tinsmiths don't like strangers and try to avoid unnecessary conversations.}
### {121}{}{I'm scared of these tinsmiths - they're like robots.}
{121}{}{我害怕这些铁匠，他们就像机器人。 -- I'm scared of these tinsmiths - they're like robots.}
