### {100}{}{You see the tinker.}
{100}{}{你看到修补匠了。 -- You see the tinker.}
### {101}{}{Here is one of the ordinary residents of Two-Sun.}
{101}{}{这是两个太阳的一位普通居民。 -- Here is one of the ordinary residents of Two-Sun.}

#Floating replicas
### {110}{}{The gods have become angry because of our slowness.}
{110}{}{因为我们行动迟缓，众神都生气了。 -- The gods have become angry because of our slowness.}
### {111}{}{Why did the gods become silent? Have they forgotten about us?}
{111}{}{为什么众神变得沉默？他们忘了我们了吗？ -- Why did the gods become silent? Have they forgotten about us?}
### {112}{}{The gods were pleased.}
{112}{}{众神很高兴。 -- The gods were pleased.}

### {113}{}{Casa Nueva can cut food.}
{113}{}{Casa Nueva可以切食物。 -- Casa Nueva can cut food.}
### {114}{}{Casa Nueva promised to send more food.}
{114}{}{Casa Nueva承诺会送更多的食物。 -- Casa Nueva promised to send more food.}
### {115}{}{Disturbing rumors are coming from Casa Nueva, now it's not safe there.}
{115}{}{令人不安的谣言来自努瓦之家，现在那里不安全。 -- Disturbing rumors are coming from Casa Nueva, now it's not safe there.}

### {116}{}{The Magistrals robbed another caravan from Phoenix.}
{116}{}{治安法官从凤凰城抢劫了另一辆商队。 -- The Magistrals robbed another caravan from Phoenix.}
### {117}{}{They say that the Blue Shields have finally been deposed.}
{117}{}{他们说蓝盾党终于被废黜了。 -- They say that the Blue Shields have finally been deposed.}
### {118}{}{The Blue Shields have become stronger. Now they have to be reckoned with.}
{118}{}{蓝盾队变得更强了。现在他们必须被考虑在内。 -- The Blue Shields have become stronger. Now they have to be reckoned with.}

### {119}{}{I've always found these fire worshippers funny.}
{119}{}{我一直觉得这些拜火者很有趣。 -- I've always found these fire worshippers funny.}
### {120}{}{The followers of Fire got what they dreamed of.}
{120}{}{火的追随者得到了他们的梦想。 -- The followers of Fire got what they dreamed of.}
### {121}{}{Brazen fire worshippers are trying to tell us what to do.}
{121}{}{厚颜无耻的拜火者正试图告诉我们该做什么。 -- Brazen fire worshippers are trying to tell us what to do.}

### {122}{}{This uranium from Flagstaff is not enough.}
{122}{}{这些来自弗拉格斯塔夫的铀是不够的。 -- This uranium from Flagstaff is not enough.}
### {123}{}{We must conserve energy until the Flagstaff mines start working again.}
{123}{}{我们必须节约能源，直到弗拉格斯塔夫煤矿重新开始工作。 -- We must conserve energy until the Flagstaff mines start working again.}
### {124}{}{Now you don't have to save energy thanks to the uranium reserves from Flagstaff.}
{124}{}{现在，由于弗拉格斯塔夫的铀储量，你不必节省能源。 -- Now you don't have to save energy thanks to the uranium reserves from Flagstaff.}

### {125}{}{Admission to the Restricted Area would change our whole lives.}
{125}{}{进入禁区将改变我们的一生。 -- Admission to the Restricted Area would change our whole lives.}
### {126}{}{We have to leave before ZAX finally unleashes his wrath on us.}
{126}{}{我们必须在ZAX最终向我们发泄愤怒之前离开。 -- We have to leave before ZAX finally unleashes his wrath on us.}
### {127}{}{Admission to the Restricted Area will change our whole life.}
{127}{}{进入禁区将改变我们的一生。 -- Admission to the Restricted Area will change our whole life.}

### {128}{}{After the last operation, Master Hard became insensitive.}
{128}{}{最后一次手术后，哈德大师变得麻木不仁。 -- After the last operation, Master Hard became insensitive.}
### {129}{}{Another visit to Doc Jones may be the last.}
{129}{}{再次拜访琼斯医生可能是最后一次了。 -- Another visit to Doc Jones may be the last.}
### {130}{}{Know your place in the Team.}
{130}{}{了解自己在团队中的位置。 -- Know your place in the Team.}

### {131}{}{Don't forget to pray to the god of technology before eating.}
{131}{}{吃饭前别忘了向科技之神祈祷。 -- Don't forget to pray to the god of technology before eating.}
### {132}{}{Pray to the gods of Steel for what we are.}
{132}{}{为我们的存在向钢铁之神祷告。 -- Pray to the gods of Steel for what we are.}
### {133}{}{I need to clean my joints.}
{133}{}{我需要清洁我的关节。 -- I need to clean my joints.}
