### {100}{}{You see the tinker.}
{100}{}{你看到修补匠了。 -- You see the tinker.}
### {101}{}{Here is one of the tinsmiths.}
{101}{}{这是一个铁匠。 -- Here is one of the tinsmiths.}

### {200}{}{(After a long journey along a deserted highway, you are brought to the settlement of tinsmiths. You are put in a row with the rest of the slaves, exhausted from waiting under the scorching sun)}
{200}{}{（在一条废弃的高速公路上走了很长一段路后，你被带到了锡匠的定居点。你和其他奴隶排成一排，因为在烈日下等待而疲惫不堪） -- (After a long journey along a deserted highway, you are brought to the settlement of tinsmiths. You are put in a row with the rest of the slaves, exhausted from waiting under the scorching sun)}
### {201}{}{[Next]}
{201}{}{[下一个 -- Next]}
### {202}{}{(One of the tinsmiths examines you and checks the data on the tablet) You. Also from the Villa? Send him to the Instructor, let him send him after his relatives... So, next...}
{202}{}{（其中一个铁匠检查了你，并检查了平板电脑上的数据）你。同样来自别墅？把他送到教官那里，让他跟着他的亲戚。。。那么，接下来。。。 -- (One of the tinsmiths examines you and checks the data on the tablet) You. Also from the Villa? Send him to the Instructor, let him send him after his relatives... So, next...}
### {203}{}{[Next]}
{203}{}{[下一个 -- Next]}

### {210}{}{I'm busy.}
{210}{}{我很忙。 -- I'm busy.}
### {211}{}{Whatever you say.}
{211}{}{不管你说什么。 -- Whatever you say.}
