### {100}{}{Here is the administrator.}
{100}{}{这是管理员。 -- Here is the administrator.}
### {101}{}{You see a middle-aged man. Judging by the way he speaks and moves, he is obsessed with order and neatness.}
{101}{}{你看到一个中年男人，从他说话和行动的方式来看，他痴迷于秩序和整洁。 -- You see a middle-aged man. Judging by the way he speaks and moves, he is obsessed with order and neatness.}

#Dialog
### {200}{}{Come in, wanderer. I have order and accounting here, so don't confuse anything for me here.}
{200}{}{进来吧，流浪者。我这里有订单和会计，所以不要把这里的任何东西弄糊涂。 -- Come in, wanderer. I have order and accounting here, so don't confuse anything for me here.}
### {1200}{}{Come in, wanderer. I have order and accounting here, so don't confuse anything for me here.}
{1200}{}{进来吧，流浪者。我这里有订单和会计，所以不要把这里的任何东西弄糊涂。 -- Come in, wanderer. I have order and accounting here, so don't confuse anything for me here.}
### {201}{}{Goodbye.}
{201}{}{再见 -- Goodbye.}
### {202}{}{To me again? Great. How can I help you?}
{202}{}{再次对我？太棒了我能帮你什么？ -- To me again? Great. How can I help you?}
### {203}{}{I need to send a package to Phoenix.}
{203}{}{我需要寄一个包裹到凤凰城。 -- I need to send a package to Phoenix.}
### {204}{}{I need to send a package to Flagstaff.}
{204}{}{我需要给弗拉格斯塔夫寄一个包裹。 -- I need to send a package to Flagstaff.}
### {205}{}{I need to send a package to Puerto.}
{205}{}{我需要寄一个包裹到波多黎各。 -- I need to send a package to Puerto.}

#Sending a parcel
### {210}{}{That's why I'm here. The price of the parcel will be }
{210}{}{这就是我来这里的原因。包裹的价格是 -- That's why I'm here. The price of the parcel will be }
### {211}{}{ bottlecaps. No more, no less. Put the things in that drawer over there by the wall. After payment, we will take them to their destination.}
{211}{}{装瓶。不多不少。把东西放在那边靠墙的抽屉里。付款后，我们将把他们送到目的地。 --  bottlecaps. No more, no less. Put the things in that drawer over there by the wall. After payment, we will take them to their destination.}
### {212}{}{Here is the fee, the parcel can be sent.}
{212}{}{这是费用，包裹可以寄了。 -- Here is the fee, the parcel can be sent.}
### {213}{}{Not now.}
{213}{}{现在不行。 -- Not now.}

### {214}{}{No, no, that's not enough.}
{214}{}{不，不，这还不够。 -- No, no, that's not enough.}
### {215}{}{Can we talk about something then?}
{215}{}{那我们能谈谈吗？ -- Can we talk about something then?}
### {216}{}{I'll be back when I earn it.}
{216}{}{我挣到钱就回来。 -- I'll be back when I earn it.}
### {217}{}{Now I will make an inventory and enter the data in the log. This is required by the protocol. Here... Thank you for choosing our company. The package will be waiting in Phoenix at the same Sonora Express office.}
{217}{}{现在我将进行盘点并在日志中输入数据。这是协议所要求的。在这里感谢您选择我们公司。包裹将在菲尼克斯的同一个索诺拉快递办公室等待。 -- Now I will make an inventory and enter the data in the log. This is required by the protocol. Here... Thank you for choosing our company. The package will be waiting in Phoenix at the same Sonora Express office.}
### {218}{}{Great.}
{218}{}{太棒了 -- Great.}

### {220}{}{Can I, as a member of the Brotherhood, count on special prices?}
{220}{}{作为兄弟会的一员，我能指望特价吗？ -- Can I, as a member of the Brotherhood, count on special prices?}
### {221}{}{Definitely, yes. We have special agreements with the Brotherhood.}
{221}{}{当然，是的。我们与兄弟会有特殊协议。 -- Definitely, yes. We have special agreements with the Brotherhood.}
### {222}{}{Wonderful. Just great.}
{222}{}{精彩的太棒了。 -- Wonderful. Just great.}
### {223}{}{Ah, it's you again... But I just have to inform you that the discount on our services has now been canceled. And don't be indignant. This is the decision of the management, I have nothing to do with it.}
{223}{}{啊，又是你。。。但我只想通知你，我们服务的折扣现在已经取消了。不要生气。这是管理层的决定，我与之无关。 -- Ah, it's you again... But I just have to inform you that the discount on our services has now been canceled. And don't be indignant. This is the decision of the management, I have nothing to do with it.}
### {224}{}{Yes, bad luck...}
{224}{}{是的，运气不好。。。 -- Yes, bad luck...}

#The first dialog
### {230}{}{What can I do for you?}
{230}{}{我能为你做什么？ -- What can I do for you?}
### {231}{}{Explain what this place is?}
{231}{}{解释一下这个地方是什么？ -- Explain what this place is?}
### {232}{}{The regional office of the courier company "Sonora Express". We are engaged in various types of delivery.}
{232}{}{快递公司“Sonora Express”的地区办事处。我们从事各种类型的交货。 -- The regional office of the courier company "Sonora Express". We are engaged in various types of delivery.}
### {233}{}{And how big is your caravan network?}
{233}{}{你的房车网络有多大？ -- And how big is your caravan network?}
### {234}{}{It all depends on the specific order. Our central office is located in Phoenix. Paths diverge from it to the nearest settlements.}
{234}{}{这完全取决于具体的顺序。我们的中心办公室位于凤凰城。小路从它分叉到最近的定居点。 -- It all depends on the specific order. Our central office is located in Phoenix. Paths diverge from it to the nearest settlements.}
### {235}{}{I see. I'll keep that in mind for the future.}
{235}{}{我明白了。我以后会记住这一点。 -- I see. I'll keep that in mind for the future.}
