### {110}{}{The barrier is destabilized for 5 seconds.}
{110}{}{屏障失稳5秒钟。 -- The barrier is destabilized for 5 seconds.}
### {111}{}{The barrier has already been destabilized.}
{111}{}{这道屏障已经不稳定了。 -- The barrier has already been destabilized.}
### {112}{}{The modulator action is over.}
{112}{}{调制器动作结束。 -- The modulator action is over.}
### {113}{}{At the moment, the modulator is useless.}
{113}{}{目前，调制器是无用的。 -- At the moment, the modulator is useless.}
### {114}{}{Some calculations will be required here.}
{114}{}{此处需要进行一些计算。 -- Some calculations will be required here.}
