### {101}{}{Here is a homemade workbench.}
{101}{}{这是一个自制的工作台。 -- Here is a homemade workbench.}
### {102}{}{You have made 20 signal cartridges from old festive pyrotechnics.}
{102}{}{你们用古老的节日烟火制作了20个信号弹。 -- You have made 20 signal cartridges from old festive pyrotechnics.}
### {110}{}{On this workbench are the components of a laser rifle.}
{110}{}{在这个工作台上是激光步枪的部件。 -- On this workbench are the components of a laser rifle.}
### {111}{}{All components are used up. There's nothing else to do here.}
{111}{}{所有部件都用完了。这里没有别的事可做。 -- All components are used up. There's nothing else to do here.}
### {112}{}{You have assembled a laser rifle.}
{112}{}{你组装了一支激光步枪。 -- You have assembled a laser rifle.}
