### {100}{}{This is Chris.}
{100}{}{这是克里斯。 -- This is Chris.}
### {101}{}{Here is one of the residents of the Villa. His gaze betrays a fair amount of puzzlement.}
{101}{}{这是别墅的一位居民。他的目光流露出相当多的困惑。 -- Here is one of the residents of the Villa. His gaze betrays a fair amount of puzzlement.}

### {110}{}{Chris's backpack was filled with provisions.}
{110}{}{克里斯的背包里装满了食物。 -- Chris's backpack was filled with provisions.}
### {111}{}{Thank you, that's enough... I hope.}
{111}{}{谢谢，够了。。。我希望。 -- Thank you, that's enough... I hope.}
### {112}{}{(}
{112}{}{( -- (}
### {113}{}{ of }
{113}{}{属于 --  of }
### {114}{}{) Chris's backpack is full of provisions, but it's not enough for the trip.}
{114}{}{)克里斯的背包里装满了食物，但还不够旅行。 -- ) Chris's backpack is full of provisions, but it's not enough for the trip.}
### {115}{}{Thank you. At least I won't starve to death.}
{115}{}{非常感谢。至少我不会饿死。 -- Thank you. At least I won't starve to death.}

### {200}{}{? It's you... Not surprisingly, I suspected that you, the new hero of the Villa, would be sent to search. Now they see you as a leader. I probably don't want to lose my special status, right?}
{200}{}{？是你。。。毫不奇怪，我怀疑你，别墅的新英雄，会被派去搜查。现在他们把你看作领导者。我可能不想失去我的特殊身份，对吧？ -- ? It's you... Not surprisingly, I suspected that you, the new hero of the Villa, would be sent to search. Now they see you as a leader. I probably don't want to lose my special status, right?}
### {201}{}{So why did you run away from the community?}
{201}{}{那你为什么要逃离社区？ -- So why did you run away from the community?}
### {202}{}{They want to execute me. You know. Why these unnecessary questions?}
{202}{}{他们想处决我。为什么这些不必要的问题？ -- They want to execute me. You know. Why these unnecessary questions?}
### {203}{}{I need to know for sure.}
{203}{}{我需要确定。 -- I need to know for sure.}
### {204}{}{You'd better stay here. Wait for my return.}
{204}{}{你最好留在这里。等我回来。 -- You'd better stay here. Wait for my return.}

### {210}{}{If this is my last day, I'd rather spend it with you.}
{210}{}{如果这是我的最后一天，我宁愿和你一起度过。 -- If this is my last day, I'd rather spend it with you.}
### {211}{}{If this is my last day, then I would rather meet him at the bottom of the well than next to you.}
{211}{}{如果这是我的最后一天，那么我宁愿在井底见到他，也不愿在你旁边。 -- If this is my last day, then I would rather meet him at the bottom of the well than next to you.}
### {212}{}{Don't go anywhere, I'll be back soon.}
{212}{}{哪儿也不要去，我很快就会回来。 -- Don't go anywhere, I'll be back soon.}
### {213}{}{I think I missed something in this story. Tell me more.}
{213}{}{我想我在这个故事中遗漏了一些东西。告诉我更多。 -- I think I missed something in this story. Tell me more.}
### {214}{}{Okay. There's no hurry anyway.}
{214}{}{可以无论如何都不着急。 -- Okay. There's no hurry anyway.}
### {215}{}{Tell me more.}
{215}{}{告诉我更多。 -- Tell me more.}

### {220}{}{Why are they mad at you?}
{220}{}{他们为什么生你的气？ -- Why are they mad at you?}
### {221}{}{Like you, I avoided the raiders. But only because he hid from them in the cellars. Now the residents cannot forgive this and consider me a traitor. And traitors in the Villa have always been disliked.}
{221}{}{和你一样，我避开了袭击者。但这只是因为他躲在地窖里躲避他们。现在居民们不能原谅我，认为我是叛徒。别墅里的叛徒一直都不受欢迎。 -- Like you, I avoided the raiders. But only because he hid from them in the cellars. Now the residents cannot forgive this and consider me a traitor. And traitors in the Villa have always been disliked.}
### {222}{}{What kind of execution are they preparing for you?}
{222}{}{他们在为你准备什么样的处决？ -- What kind of execution are they preparing for you?}
### {223}{}{I don't know for sure, but someone whispered about stoning. They used to do that. And now, after all this business with the raid, they can come up with something worse.}
{223}{}{我不确定，但有人私下说要用石头砸死。他们过去常这样做。现在，在经历了这么多突袭之后，他们可能会想出更糟糕的事情。 -- I don't know for sure, but someone whispered about stoning. They used to do that. And now, after all this business with the raid, they can come up with something worse.}
### {224}{}{What do you know about this place?}
{224}{}{你对这个地方了解多少？ -- What do you know about this place?}
### {225}{}{Ancient ruins of some settlement. Our ancestors took bricks from here to build their houses. The rest is destroyed by time. As you can see, there is almost nothing left...}
{225}{}{一些定居点的古代废墟。我们的祖先从这里取砖建造房屋。其余的都被时间摧毁了。正如你所看到的，几乎什么都没有了。。。 -- Ancient ruins of some settlement. Our ancestors took bricks from here to build their houses. The rest is destroyed by time. As you can see, there is almost nothing left...}
### {226}{}{[Next]}
{226}{}{[下一个 -- Next]}
### {227}{}{Funny. The villa exists thanks to these ruins. Now they keep me alive. But no one knows anything about their past and about the people who lived here. Perhaps in other cities with a different way of life, not like in a Villa, I will find my place.}
{227}{}{有趣的别墅因这些废墟而存在。现在他们让我活着。但没有人知道他们的过去和住在这里的人。也许在其他有着不同生活方式的城市，而不是在别墅里，我会找到自己的位置。 -- Funny. The villa exists thanks to these ruins. Now they keep me alive. But no one knows anything about their past and about the people who lived here. Perhaps in other cities with a different way of life, not like in a Villa, I will find my place.}
### {228}{}{What are you going to do?}
{228}{}{你打算怎么办？ -- What are you going to do?}
### {229}{}{I don't know. I can't hide for long, and there's nowhere much to run. I've heard about the rangers and the scavengers from the neighboring town. But to go there, you need provisions. (bitter smile) Don't follow her to the Villa.}
{229}{}{我不知道。我躲不了多久，也没什么可跑的。我听说过附近城镇的护林员和拾荒者。但要去那里，你需要食物。（苦笑）不要跟着她去别墅。 -- I don't know. I can't hide for long, and there's nowhere much to run. I've heard about the rangers and the scavengers from the neighboring town. But to go there, you need provisions. (bitter smile) Don't follow her to the Villa.}
### {230}{}{If I get you provisions, you can leave these places. But you'll never come back.}
{230}{}{如果我给你拿了食物，你就可以离开这些地方。但你再也回不来了。 -- If I get you provisions, you can leave these places. But you'll never come back.}
### {231}{}{I know! Maybe that's what I've always wanted, but I was afraid to admit it. Among our people, most did not even try to learn anything about the outside world. They have lived their way for decades and are ready to throw stones for any change in it... I want to be free, amigo. Give me a chance!}
{231}{}{我知道！也许这是我一直想要的，但我不敢承认。在我们的人民中，大多数人甚至没有尝试了解外面的世界。他们已经按照自己的方式生活了几十年，并准备为任何改变扔石头……我想自由，朋友。给我一个机会！ -- I know! Maybe that's what I've always wanted, but I was afraid to admit it. Among our people, most did not even try to learn anything about the outside world. They have lived their way for decades and are ready to throw stones for any change in it... I want to be free, amigo. Give me a chance!}
### {232}{}{Okay, I'll get you some provisions for the trip. Wait here.}
{232}{}{好的，我给你带些旅行的食物。在这里等候。 -- Okay, I'll get you some provisions for the trip. Wait here.}
### {233}{}{No. My reputation is important to me. And besides, you deserve to be punished. Pack up, we're going back to the community.}
{233}{}{不，我的名誉对我来说很重要。此外，你应该受到惩罚。收拾行李，我们要回到社区。 -- No. My reputation is important to me. And besides, you deserve to be punished. Pack up, we're going back to the community.}
### {234}{}{First of all, I need to know the details of this story.}
{234}{}{首先，我需要了解这个故事的细节。 -- First of all, I need to know the details of this story.}
### {1234}{}{First of all, I need to know the details of this story.}
{1234}{}{首先，我需要了解这个故事的细节。 -- First of all, I need to know the details of this story.}
### {235}{}{To give Chris supplies, use them on the character.}
{235}{}{要给克里斯补给，请在角色身上使用。 -- To give Chris supplies, use them on the character.}
### {236}{}{Now you have enough provisions to escape to the nearest town.}
{236}{}{现在你有足够的食物逃到最近的城镇。 -- Now you have enough provisions to escape to the nearest town.}
### {237}{}{I hope so. Let's get some fresh air. I want to take one last look around before I leave.}
{237}{}{我希望如此。让我们呼吸新鲜空气吧。我想在离开前最后看一眼。 -- I hope so. Let's get some fresh air. I want to take one last look around before I leave.}
### {238}{}{Let's go.}
{238}{}{我们走吧。 -- Let's go.}
### {239}{}{Escort Chris to the square at the Villa.}
{239}{}{护送克里斯去别墅广场。 -- Escort Chris to the square at the Villa.}

#GG takes Chris away from the location:
### {240}{}{Can we talk outside?}
{240}{}{我们可以在外面谈谈吗？ -- Can we talk outside?}
### {241}{}{Let's go.}
{241}{}{我们走吧。 -- Let's go.}
### {242}{}{Don't worry about me, I'll find my way.}
{242}{}{别担心我，我会找到路的。 -- Don't worry about me, I'll find my way.}
### {243}{}{Whatever you say.}
{243}{}{不管你说什么。 -- Whatever you say.}
### {244}{}{Escort Chris to the edge of the ruins, and then return to the Villa.}
{244}{}{护送克里斯到废墟边缘，然后返回别墅。 -- Escort Chris to the edge of the ruins, and then return to the Villa.}
### {245}{}{Come on, do what you have to do!}
{245}{}{来吧，做你必须做的事！ -- Come on, do what you have to do!}
### {1245}{}{Come on, do what you have to do!}
{1245}{}{来吧，做你必须做的事！ -- Come on, do what you have to do!}
### {246}{}{Better shut up.}
{246}{}{最好闭嘴。 -- Better shut up.}
### {247}{}{Look, I'm not in the mood for this decision either.}
{247}{}{听着，我也没有心情做这个决定。 -- Look, I'm not in the mood for this decision either.}
