### {100}{}{Here is a peasant.}
{100}{}{这是一个农民。 -- Here is a peasant.}
### {101}{}{You see a resident of the Villa.}
{101}{}{你看到别墅的一位居民。 -- You see a resident of the Villa.}
### {102}{}{It looks like someone is waiting for you at the exit!}
{102}{}{好像有人在出口等你！ -- It looks like someone is waiting for you at the exit!}
### {103}{}{Let's make a deal - this conversation didn't happen.}
{103}{}{让我们达成协议吧——这次谈话没有发生。 -- Let's make a deal - this conversation didn't happen.}
### {104}{}{I'll be damned! You... WHAT ARE you?}
{104}{}{我会被诅咒的！你你是什么？ -- I'll be damned! You... WHAT ARE you?}
### {105}{}{It's good to see you.}
{105}{}{很高兴见到你。 -- It's good to see you.}

### {200}{}{How are the searches going?}
{200}{}{搜索进展如何？ -- How are the searches going?}
### {201}{}{Great. So far.}
{201}{}{太棒了目前为止 -- Great. So far.}
### {202}{}{Well... to be honest, I'm not in the spirit of the Council's decision either. But this story will serve as an example to others. It will be better for everyone.}
{202}{}{好老实说，我也不符合安理会决定的精神。但这个故事将成为其他人的榜样。这对每个人都会更好。 -- Well... to be honest, I'm not in the spirit of the Council's decision either. But this story will serve as an example to others. It will be better for everyone.}
### {203}{}{I really hope so.}
{203}{}{我真的希望如此。 -- I really hope so.}
### {204}{}{Go to hell with your excuses!}
{204}{}{你的借口见鬼去吧！ -- Go to hell with your excuses!}

### {210}{}{(on the way out of the building, you unexpectedly encounter an old acquaintance; it looks like he was deliberately lying in wait for you) Well, well. We had a lot of one traitor, and now you! What the hell are you doing? Do you want to break the whole way of our life because of one cute and failed coward?}
{210}{}{（在出楼的路上，你意外地遇到了一位老熟人，看起来他是故意在等你的）嗯，嗯。我们有很多叛徒，现在你！你到底在干什么？你想因为一个可爱而失败的懦夫而毁掉我们的整个生活吗？ -- (on the way out of the building, you unexpectedly encounter an old acquaintance; it looks like he was deliberately lying in wait for you) Well, well. We had a lot of one traitor, and now you! What the hell are you doing? Do you want to break the whole way of our life because of one cute and failed coward?}
### {211}{}{The community made a mistake. Killing your own is the way to destroy the way of life.}
{211}{}{社区犯了一个错误。杀死自己的人是破坏生活方式的方式。 -- The community made a mistake. Killing your own is the way to destroy the way of life.}

### {212}{}{Maybe so... I don't know! We all changed after that raid. Before him, we lived in peace and no one was going to throw stones at a neighbor. Only in the old days, when the Villa was being rebuilt...}
{212}{}{也许是这样…我不知道！那次突袭后我们都变了。在他之前，我们过着平静的生活，没有人会向邻居扔石头。只是在过去，当别墅正在重建时。。。 -- Maybe so... I don't know! We all changed after that raid. Before him, we lived in peace and no one was going to throw stones at a neighbor. Only in the old days, when the Villa was being rebuilt...}
### {213}{}{[Next]}
{213}{}{[下一个 -- Next]}
### {214}{}{Here the ancestors took the material for building houses. And they say that life was tight then, a neighbor could steal from a neighbor. We survived that horror and became a big close-knit family. Everything changed after the raid.}
{214}{}{祖先在这里拿走了建造房屋的材料。他们说当时生活很紧张，邻居可以从邻居那里偷东西。我们熬过了那场恐怖，成为了一个紧密相连的大家庭。突袭后一切都变了。 -- Here the ancestors took the material for building houses. And they say that life was tight then, a neighbor could steal from a neighbor. We survived that horror and became a big close-knit family. Everything changed after the raid.}
### {215}{}{Then you must understand that this is not the way out. Let Chris go.}
{215}{}{那么你必须明白，这不是出路。放开克里斯。 -- Then you must understand that this is not the way out. Let Chris go.}
### {216}{}{I can't! He... he should be an example... so the community decided...}
{216}{}{我不能！他他应该成为一个榜样。。。所以社区决定。。。 -- I can't! He... he should be an example... so the community decided...}
### {217}{}{You are afraid. You are afraid that the Villa will change.}
{217}{}{你很害怕。你担心别墅会改变。 -- You are afraid. You are afraid that the Villa will change.}
### {218}{}{Yes! Cris... forgive me.}
{218}{}{对克里斯。。。原谅我。 -- Yes! Cris... forgive me.}
### {219}{}{Ugh, it seems we have solved this problem.}
{219}{}{啊，看来我们已经解决了这个问题。 -- Ugh, it seems we have solved this problem.}
### {220}{}{Then do what you have to do. I won't bother you.}
{220}{}{那就做你该做的吧。我不会打扰你的。 -- Then do what you have to do. I won't bother you.}
### {1220}{}{Then do what you have to do. I won't bother you.}
{1220}{}{那就做你该做的吧。我不会打扰你的。 -- Then do what you have to do. I won't bother you.}
### {221}{}{I don't care what the community decided. Chris will be free.}
{221}{}{我不在乎社区的决定。克里斯会有空的。 -- I don't care what the community decided. Chris will be free.}
### {222}{}{The community will not forgive you for such an act. (spits on your feet and leaves)}
{222}{}{社区不会原谅你的这种行为。（吐在你的脚上并离开） -- The community will not forgive you for such an act. (spits on your feet and leaves)}
### {223}{}{Come on, move back to the herd, you fool...}
{223}{}{来吧，回到牛群里去，你这个傻瓜。。。 -- Come on, move back to the herd, you fool...}
### {224}{}{Just let Chris go.}
{224}{}{让克里斯走吧。 -- Just let Chris go.}

### {230}{}{You got it all wrong - I'm taking him to execution.}
{230}{}{你完全错了——我要把他处死。 -- You got it all wrong - I'm taking him to execution.}
### {231}{}{Really? And why does he have a backpack full of provisions?}
{231}{}{真正地为什么他有一个装满食物的背包？ -- Really? And why does he have a backpack full of provisions?}
### {232}{}{These are my things. Let him bear it as punishment.}
{232}{}{这些是我的东西。让他承受惩罚吧。 -- These are my things. Let him bear it as punishment.}
### {233}{}{Hmm... Yes, he should be an example. It's nothing personal, Chris. So the community decided. Let's go to the execution.}
{233}{}{嗯…是的，他应该成为一个榜样。这不是针对个人的，克里斯。于是社区做出了决定。让我们去执行死刑吧。 -- Hmm... Yes, he should be an example. It's nothing personal, Chris. So the community decided. Let's go to the execution.}
### {234}{}{[Return to the square]}
{234}{}{[返回广场 -- Return to the square]}

### {240}{}{Yes, think what you want. I know what I'm doing.}
{240}{}{是的，想什么就想什么。我知道我在做什么。 -- Yes, think what you want. I know what I'm doing.}
### {241}{}{Hmm. People talk all sorts of things about you. And as it turned out, not in vain.}
{241}{}{嗯。人们谈论你的各种各样的事情。事实证明，这并非徒劳。 -- Hmm. People talk all sorts of things about you. And as it turned out, not in vain.}
### {242}{}{Hmm. People talk all sorts of things about you. But no one expected this!}
{242}{}{嗯。人们谈论你的各种各样的事情。但谁也没想到会这样！ -- Hmm. People talk all sorts of things about you. But no one expected this!}
### {243}{}{Damn it, I wouldn't want to be an outcast in my own homeland. Okay, take him to the execution, I won't bother you.}
{243}{}{该死的，我不想在自己的祖国成为一个被抛弃的人。好吧，带他去执行死刑，我不会打扰你的。 -- Damn it, I wouldn't want to be an outcast in my own homeland. Okay, take him to the execution, I won't bother you.}
### {244}{}{I don't care what the community thinks. Chris will be free.}
{244}{}{我不在乎社区怎么想。克里斯会有空的。 -- I don't care what the community thinks. Chris will be free.}
