### {101}{}{You see your fellow tribesman. His body is one continuous wound.}
{101}{}{你看到你的部落同胞了。他的身体是一个连续的伤口。 -- You see your fellow tribesman. His body is one continuous wound.}
### {102}{}{You see your fellow tribesman. After treatment, he is on the mend.}
{102}{}{你看到你的部落同胞了。经过治疗，他的病情正在好转。 -- You see your fellow tribesman. After treatment, he is on the mend.}
### {103}{}{You will not be able to treat such injuries yourself. We'll have to look for medicines.}
{103}{}{你自己将无法治疗这种伤害。我们得去找药。 -- You will not be able to treat such injuries yourself. We'll have to look for medicines.}
### {104}{}{Surgical intervention is required here.}
{104}{}{这里需要手术干预。 -- Surgical intervention is required here.}

### {105}{}{Thank you, amigo. So much better.}
{105}{}{谢谢你，朋友。好多了。 -- Thank you, amigo. So much better.}
### {106}{}{Thank you, amigo. That's much better.}
{106}{}{谢谢你，朋友。这样好多了。 -- Thank you, amigo. That's much better.}
### {107}{}{Uh, thanks, amigo. It's much better this way. That's just I don't trust this old chemistry.}
{107}{}{谢谢，朋友。这样好多了。只是我不相信这种古老的化学反应。 -- Uh, thanks, amigo. It's much better this way. That's just I don't trust this old chemistry.}
### {108}{}{Alien medicine is better than our poultices. You can't argue with that!}
{108}{}{外星人的药比我们的膏药好。你不能反驳！ -- Alien medicine is better than our poultices. You can't argue with that!}

### {110}{}{The raiders... I think they broke my rib...}
{110}{}{袭击者。。。我想他们打断了我的肋骨。。。 -- The raiders... I think they broke my rib...}

### {200}{}{Salute to our savior!}
{200}{}{向我们的救世主致敬！ -- Salute to our savior!}
### {201}{}{Bye.}
{201}{}{再见 -- Bye.}
### {202}{}{During the treatment, you were distrustful of pre-war medicine. Why?}
{202}{}{在治疗过程中，你不信任战前的药物。为什么？ -- During the treatment, you were distrustful of pre-war medicine. Why?}
### {203}{}{Our ancestors always taught us not to trust the things of the Old World. They said that these things were cursed by spirits and carried danger. But one of them just saved my life. Now I'm thinking, won't I be cursed?}
{203}{}{我们的祖先总是教导我们不要相信旧世界的东西。他们说这些东西被鬼魂诅咒，带有危险。但其中一个救了我的命。现在我在想，我不会被诅咒吗？ -- Our ancestors always taught us not to trust the things of the Old World. They said that these things were cursed by spirits and carried danger. But one of them just saved my life. Now I'm thinking, won't I be cursed?}
### {204}{}{But you're still alive. Now rest.}
{204}{}{但你还活着。现在休息。 -- But you're still alive. Now rest.}
### {205}{}{This stranger, of course, knows his business. And I've never been so fresh after an illness! But the ancestors always taught that you can't trust the things and traditions of the Old World. Now everyone will think that I am cursed by spirits!}
{205}{}{这个陌生人当然知道他的事。我从来没有在生病后如此精神抖擞！但祖先总是教导我们不能相信旧世界的事物和传统。现在每个人都会认为我被鬼魂诅咒了！ -- This stranger, of course, knows his business. And I've never been so fresh after an illness! But the ancestors always taught that you can't trust the things and traditions of the Old World. Now everyone will think that I am cursed by spirits!}
### {206}{}{But you're still alive. Now rest.}
{206}{}{但你还活着。现在休息。 -- But you're still alive. Now rest.}
### {207}{}{How do you feel after treatment?}
{207}{}{治疗后你感觉如何？ -- How do you feel after treatment?}
### {208}{}{I thought I was finished. But it's all right now. You're doing real miracles. After all, people with fractures in the Villa rarely survived. And how did we not notice you have this gift before?}
{208}{}{我以为我完了。但现在一切都好了。你正在创造真正的奇迹。毕竟，别墅里骨折的人很少能活下来。我们以前怎么没注意到你有这个礼物？ -- I thought I was finished. But it's all right now. You're doing real miracles. After all, people with fractures in the Villa rarely survived. And how did we not notice you have this gift before?}
### {209}{}{The main thing is that you're alive. Now rest.}
{209}{}{最重要的是你还活着。现在休息。 -- The main thing is that you're alive. Now rest.}

### {210}{}{What do you know about the world outside the Villa?}
{210}{}{你对别墅外的世界了解多少？ -- What do you know about the world outside the Villa?}
### {211}{}{Not much. All my life I have not been further from our desert. And I don't regret it at all. Talk to Jose, he knows something, because he occasionally does business with strangers.}
{211}{}{不多在我的一生中，我从未远离过我们的沙漠。我一点也不后悔。和何塞谈谈，他知道一些事情，因为他偶尔会和陌生人做生意。 -- Not much. All my life I have not been further from our desert. And I don't regret it at all. Talk to Jose, he knows something, because he occasionally does business with strangers.}
### {212}{}{I'm going on a trip. How can you help me?}
{212}{}{我要去旅行。你能帮我什么？ -- I'm going on a trip. How can you help me?}
### {213}{}{As you can see, I'm of little use. But I can give you this (takes out a handful of cartridges of different calibers). One of the raiders dropped it during the assault, and I hid it. I hope you'll find this useful.}
{213}{}{正如你所看到的，我没什么用。但我可以给你这个（拿出一把不同口径的子弹）。一个袭击者在袭击中扔了它，我把它藏了起来。我希望你会发现这很有用。 -- As you can see, I'm of little use. But I can give you this (takes out a handful of cartridges of different calibers). One of the raiders dropped it during the assault, and I hid it. I hope you'll find this useful.}
### {214}{}{Thank you.}
{214}{}{非常感谢。 -- Thank you.}
### {215}{}{Do you know those who have been outside the Villa?}
{215}{}{你认识那些出过别墅的人吗？ -- Do you know those who have been outside the Villa?}
### {216}{}{What are you! Who in their right mind would leave their home and go to the hot desert?}
{216}{}{你是什么！谁在头脑正常的情况下会离开家去炎热的沙漠？ -- What are you! Who in their right mind would leave their home and go to the hot desert?}
### {217}{}{Well, yes, I have to practice my skills on someone. Be there.}
{217}{}{嗯，是的，我必须在某人身上练习我的技能。在那里。 -- Well, yes, I have to practice my skills on someone. Be there.}
