### {110}{}{Bad people won't come back? Really?}
{110}{}{坏人不会回来了？真正地 -- Bad people won't come back? Really?}
### {111}{}{. . .}
{111}{}{。 -- . . .}
### {112}{}{Your coming in power armor has alarmed the local population.}
{112}{}{你的强力盔甲让当地居民感到震惊。 -- Your coming in power armor has alarmed the local population.}

### {200}{}{(the girl looks numbly at your iron armor, unable to understand whether to admire this sight or scream in horror)}
{200}{}{（女孩麻木地看着你的铁甲，不知道是欣赏这一幕，还是惊恐地尖叫） -- (the girl looks numbly at your iron armor, unable to understand whether to admire this sight or scream in horror)}
### {201}{}{Greetings, child. From now on, the Big Iron Man will be your protector. And bad people won't dare come here.}
{201}{}{问候，孩子。从现在起，大钢铁侠将成为你的保护者。坏人不敢来这里。 -- Greetings, child. From now on, the Big Iron Man will be your protector. And bad people won't dare come here.}
### {202}{}{(her eyes widen in admiration, then she runs away to tell about the Big Iron Defender)}
{202}{}{（她羡慕得睁大了眼睛，然后跑去讲述大铁卫士的故事） -- (her eyes widen in admiration, then she runs away to tell about the Big Iron Defender)}
### {203}{}{Don't be afraid anymore, child. You're in good hands.}
{203}{}{别再害怕了，孩子。你得到了很好的照顾。 -- Don't be afraid anymore, child. You're in good hands.}
### {204}{}{Yes, run, tell everyone, little gossip girl.}
{204}{}{是的，快跑，告诉大家，小八卦女孩。 -- Yes, run, tell everyone, little gossip girl.}
### {205}{}{[Ignore and move on]}
{205}{}{[忽略并继续 -- Ignore and move on]}

### {210}{}{What are you staring at? I will crush anyone who looks at me with an inappropriate look!}
{210}{}{你在看什么？我会碾压任何用不恰当的眼神看着我的人！ -- What are you staring at? I will crush anyone who looks at me with an inappropriate look!}
### {211}{}{A-a-a! El Diablo! El Diablo!}
{211}{}{啊啊啊！暗黑破坏神！暗黑破坏神！ -- A-a-a! El Diablo! El Diablo!}
### {212}{}{Eh, the new generation has become a pussy...}
{212}{}{呃，新一代变成了一个胆小鬼。。。 -- Eh, the new generation has become a pussy...}
### {213}{}{}
{213}{}{error : string is empty -- }
### {214}{}{[Ignore and move on]}
{214}{}{[忽略并继续 -- Ignore and move on]}
