### {110}{}{These shelves were destroyed. But they can still be repaired.}
{110}{}{这些架子被毁了。但它们仍然可以修复。 -- These shelves were destroyed. But they can still be repaired.}
### {111}{}{Ordinary shelves. Nothing special.}
{111}{}{普通货架。没什么特别的。 -- Ordinary shelves. Nothing special.}
### {112}{}{You have successfully restored the shelves. During the repair process, you discovered some useful things.}
{112}{}{您已成功恢复机框。在维修过程中，您发现了一些有用的东西。 -- You have successfully restored the shelves. During the repair process, you discovered some useful things.}
