### {110}{}{This well is as old as the Villa itself.}
{110}{}{这口井和别墅一样古老。 -- This well is as old as the Villa itself.}
### {111}{}{You lowered a strong rope to the bottom of the well.}
{111}{}{你把一根结实的绳子放在井底。 -- You lowered a strong rope to the bottom of the well.}
### {112}{}{You have already lowered one rope to the bottom of the well. There is no need for the second one.}
{112}{}{你已经把一根绳子放在井底了。不需要第二个。 -- You have already lowered one rope to the bottom of the well. There is no need for the second one.}
### {113}{}{Going down to the bottom of the well, you discover a very old hiding place. It looks like someone has hidden forbidden things here.}
{113}{}{下到井底，你发现了一个非常古老的藏身之处。看起来好像有人在这里藏了违禁物品。 -- Going down to the bottom of the well, you discover a very old hiding place. It looks like someone has hidden forbidden things here.}
### {114}{}{That's so unexpected.}
{114}{}{这太出乎意料了。 -- That's so unexpected.}
### {115}{}{ }
{115}{}{error : string is empty --  }
### {116}{}{It does not need repair.}
{116}{}{它不需要修理。 -- It does not need repair.}
