### {110}{}{You lowered the rope and secured it securely against the edge of the shaft.}
{110}{}{你放下绳子，把它牢牢地固定在竖井的边缘。 -- You lowered the rope and secured it securely against the edge of the shaft.}
### {111}{}{This mine cannot be repaired. But you can lower a rope into it.}
{111}{}{这个矿井无法修复。但是你可以把绳子放进去。 -- This mine cannot be repaired. But you can lower a rope into it.}
### {112}{}{The elevator does not work due to lack of electricity.}
{112}{}{由于电力不足，电梯不能工作。 -- The elevator does not work due to lack of electricity.}
