### {110}{}{Ventilation is not working. Obviously, she lacks energy.}
{110}{}{通风不起作用。显然，她缺乏活力。 -- Ventilation is not working. Obviously, she lacks energy.}
### {111}{}{You have started the ventilation system. We should expect air purification in the near future.}
{111}{}{你已经启动了通风系统。我们应该期待在不久的将来空气净化。 -- You have started the ventilation system. We should expect air purification in the near future.}
### {112}{}{Ventilation is already running.}
{112}{}{通风系统已经在运行。 -- Ventilation is already running.}

### {120}{}{*P-sh-sh*}
{120}{}{*P-sh-sh* -- *P-sh-sh*}
### {121}{}{*P-f-f*}
{121}{}{*P-f-f* -- *P-f-f*}
### {122}{}{*Kr-r-r*}
{122}{}{*Kr-r* -- *Kr-r-r*}
