### {100}{}{This is John D. Butler.}
{100}{}{我是约翰·D·巴特勒。 -- This is John D. Butler.}
### {101}{}{You see a ghoul in a worn business suit.}
{101}{}{你看到一个穿着破旧西装的食尸鬼。 -- You see a ghoul in a worn business suit.}
### {102}{}{Are you going to a military base? Private Heap wants it too!}
{102}{}{你要去军事基地吗？二等兵希普也想要！ -- Are you going to a military base? Private Heap wants it too!}

#Acquaintance
### {200}{}{Hi. I don't think we've ever met before. I am John Butler, the elected mayor of the Shining. And who are you?}
{200}{}{你好我想我们以前从未见过面。我是约翰·巴特勒，当选的闪灵市长。你是谁？ -- Hi. I don't think we've ever met before. I am John Butler, the elected mayor of the Shining. And who are you?}
### {201}{}{Nice to meet you, Butler. I }
{201}{}{很高兴见到你，巴特勒。我 -- Nice to meet you, Butler. I }
### {202}{}{, a random mutation victim on the wastelands.}
{202}{}{，荒原上的一个随机突变受害者。 -- , a random mutation victim on the wastelands.}
### {203}{}{It's better not to suck up to me, ghoul.}
{203}{}{最好不要讨好我，食尸鬼。 -- It's better not to suck up to me, ghoul.}
### {204}{}{(sigh) I never thought that one mutant would accuse another mutant of being a mutant.}
{204}{}{（叹气）我从没想过一个变种人会指责另一个变种人为变种人。 -- (sigh) I never thought that one mutant would accuse another mutant of being a mutant.}
### {205}{}{It doesn't happen on the wastelands.}
{205}{}{这不会发生在荒原上。 -- It doesn't happen on the wastelands.}
### {206}{}{*Attention!* I'm John Butler. I run this city... More precisely, what's left of it. And I'm glad to see any smooth-skinned people who behave decently in my city. * Fire! Fire!*}
{206}{}{*注意！*我是约翰·巴特勒。我管理着这座城市。。。更确切地说，还有什么。我很高兴在我的城市里看到任何皮肤光滑、举止得体的人。*火着火了* -- *Attention!* I'm John Butler. I run this city... More precisely, what's left of it. And I'm glad to see any smooth-skinned people who behave decently in my city. * Fire! Fire!*}
### {207}{}{I had no intention of somehow hooliganism here.}
{207}{}{我无意在这里耍流氓。 -- I had no intention of somehow hooliganism here.}
### {208}{}{Humans and super mutants drove us from our homes. You probably already know this story. But this is not a reason to hate everyone around. On the contrary, I want to prove to people that ghouls are also people... * Keep firing!*}
{208}{}{人类和超级变种人把我们赶出了家园。你可能已经知道这个故事了。但这并不是憎恨周围每一个人的理由。相反，我想向人们证明食尸鬼也是人…*继续开火* -- Humans and super mutants drove us from our homes. You probably already know this story. But this is not a reason to hate everyone around. On the contrary, I want to prove to people that ghouls are also people... * Keep firing!*}
### {209}{}{Aren't you trying to trick me? I thought ghouls hated normies.}
{209}{}{你不是想骗我吗？我以为食尸鬼讨厌正常人。 -- Aren't you trying to trick me? I thought ghouls hated normies.}
### {210}{}{We moved here because humans and super mutants drove us out of our homes. But this is not a reason to hate everyone around. On the contrary, I want to prove to people that ghouls are also people... * Keep firing!*}
{210}{}{我们搬到这里是因为人类和超级变种人把我们赶出了家。但这并不是憎恨周围每一个人的理由。相反，我想向人们证明食尸鬼也是人…*继续开火* -- We moved here because humans and super mutants drove us out of our homes. But this is not a reason to hate everyone around. On the contrary, I want to prove to people that ghouls are also people... * Keep firing!*}
### {211}{}{Puns aren't your strong suit, John.}
{211}{}{双关语不是你的强项，约翰。 -- Puns aren't your strong suit, John.}
### {212}{}{And that's right. This soldier has a hard time with humor. You can't get rid of old habits even in a hundred years. So how can I help you?}
{212}{}{没错。这个士兵很难幽默。即使一百年也无法改掉旧习惯。我能帮你什么？ -- And that's right. This soldier has a hard time with humor. You can't get rid of old habits even in a hundred years. So how can I help you?}
### {213}{}{Right now, probably nothing.}
{213}{}{现在，可能什么都没有。 -- Right now, probably nothing.}
### {214}{}{That's very noble of you.}
{214}{}{你真是太高尚了。 -- That's very noble of you.}
### {215}{}{To hell with us old people. We have survived many wars and battles, our fate will remain in the past. More importantly, what will happen to your generation... * Attack! Go ahead!* Uh, so how can I help you?}
{215}{}{让我们这些老人见鬼去吧。我们经历了许多战争和战斗，我们的命运将留在过去。更重要的是，你们这一代人会发生什么…*袭击继续！*呃，我能帮你什么？ -- To hell with us old people. We have survived many wars and battles, our fate will remain in the past. More importantly, what will happen to your generation... * Attack! Go ahead!* Uh, so how can I help you?}
### {216}{}{I just wanted to get to know you. But it's time for me to leave.}
{216}{}{我只是想了解你。但我该走了。 -- I just wanted to get to know you. But it's time for me to leave.}
### {1216}{}{I just wanted to meet you. But it's time for me to leave.}
{1216}{}{我只是想见你。但我该走了。 -- I just wanted to meet you. But it's time for me to leave.}

### {220}{}{It's our old buddy, a bunch. And a man with him? Deadly news! It's like a snake and a rabbit have made friends. I am very happy for you.}
{220}{}{是我们的老朋友，一群人。和他在一起的男人呢？致命的消息！就像蛇和兔子交了朋友一样。我为你感到高兴。 -- It's our old buddy, a bunch. And a man with him? Deadly news! It's like a snake and a rabbit have made friends. I am very happy for you.}
### {1220}{}{It's our old buddy, a bunch. And a man with him? Deadly news! It's like a snake and a rabbit have made friends. I am very happy for you. It's a pity we don't have a church to marry you.}
{1220}{}{是我们的老朋友，一群人。和他在一起的男人呢？致命的消息！就像蛇和兔子交了朋友一样。我为你感到高兴。遗憾的是，我们没有教堂可以嫁给你。 -- It's our old buddy, a bunch. And a man with him? Deadly news! It's like a snake and a rabbit have made friends. I am very happy for you. It's a pity we don't have a church to marry you.}
### {221}{}{Heap is my bodyguard.}
{221}{}{希普是我的保镖。 -- Heap is my bodyguard.}
### {222}{}{I'm the commander of the Pile. He can't even take a piss without my order.}
{222}{}{我是堆的指挥官。没有我的命令，他甚至不能撒尿。 -- I'm the commander of the Pile. He can't even take a piss without my order.}

#Repeat dialog
### {230}{}{Okay. How can I help you?}
{230}{}{可以我能帮你什么？ -- Okay. How can I help you?}
### {231}{}{Hello, smooth-skinned. Have a question?}
{231}{}{你好，皮肤光滑。有问题吗？ -- Hello, smooth-skinned. Have a question?}
### {1231}{}{Hello, smooth-skinned. Have a question?}
{1231}{}{你好，皮肤光滑。有问题吗？ -- Hello, smooth-skinned. Have a question?}
### {232}{}{Hello, young mutation victim. How can I help you?}
{232}{}{你好，年轻的突变受害者。我能帮你什么？ -- Hello, young mutation victim. How can I help you?}
### {233}{}{Hi, John. Just passing by. Bye.}
{233}{}{嗨，约翰。只是路过。再见。 -- Hi, John. Just passing by. Bye.}
### {234}{}{It's a pity we didn't talk so much. If you need anything, I'm always here... * Death! Smee-ert!*}
{234}{}{很遗憾我们没聊那么多。如果你需要什么，我总是在这里…*死Smee ert* -- It's a pity we didn't talk so much. If you need anything, I'm always here... * Death! Smee-ert!*}
### {235}{}{Later.}
{235}{}{后来 -- Later.}
### {236}{}{What do you need?}
{236}{}{你需要什么？ -- What do you need?}
### {237}{}{The time for jokes is over. It's time to get down to business.}
{237}{}{开玩笑的时间结束了。是时候开始谈正事了。 -- The time for jokes is over. It's time to get down to business.}

### {240}{}{Tell me, how did you all end up here?}
{240}{}{告诉我，你们是怎么来到这里的？ -- Tell me, how did you all end up here?}
### {241}{}{We lived in the north, in a city called Necropolis. But super mutants came there. And the normies came for them. They fought among themselves, but they forgot about us... * Aim! Fire!* When the dust settled, the normies decided that they didn't like ghouls either. We decided to find a new home.}
{241}{}{我们住在北方一个叫墓地的城市。但是超级变种人来了。正常人来找他们。他们互相打架，但他们忘记了我们…*瞄准！着火！*尘埃落定后，正常人决定他们也不喜欢食尸鬼。我们决定找一个新家。 -- We lived in the north, in a city called Necropolis. But super mutants came there. And the normies came for them. They fought among themselves, but they forgot about us... * Aim! Fire!* When the dust settled, the normies decided that they didn't like ghouls either. We decided to find a new home.}
### {242}{}{What city are you trying to build?}
{242}{}{你想建哪个城市？ -- What city are you trying to build?}
### {243}{}{Just a normal working city. With trade and economy, hotels and casinos, roads and skyscrapers. And so that there is enough room for everyone here ? ghouls, humans and mutants. * At ease, soldiers!*}
{243}{}{只是一个正常的工作城市。贸易和经济，酒店和赌场，道路和摩天大楼。这样这里的每个人都有足够的空间? 食尸鬼、人类和变种人。*放心，士兵们* -- Just a normal working city. With trade and economy, hotels and casinos, roads and skyscrapers. And so that there is enough room for everyone here ? ghouls, humans and mutants. * At ease, soldiers!*}
### {244}{}{Thanks for the reply. I have to go.}
{244}{}{谢谢你的回复。我得走了。 -- Thanks for the reply. I have to go.}
### {245}{}{Is there anything I can do to help?}
{245}{}{有什么我能帮忙的吗？ -- Is there anything I can do to help?}
### {246}{}{Do you really want to help? If it weren't for those glazed eyes, I'd be crying right now. Ask around for corpses, someone probably needs help.}
{246}{}{你真的想帮忙吗？如果不是那双呆滞的眼睛，我现在会哭的。四处打听尸体，可能有人需要帮助。 -- Do you really want to help? If it weren't for those glazed eyes, I'd be crying right now. Ask around for corpses, someone probably needs help.}
### {247}{}{I'll do that. Goodbye.}
{247}{}{我会那样做的。再见 -- I'll do that. Goodbye.}
### {248}{}{Is there anything else I can help with?}
{248}{}{还有什么我可以帮忙的吗？ -- Is there anything else I can help with?}
### {249}{}{Tell me about yourself.}
{249}{}{告诉我你自己。 -- Tell me about yourself.}
### {250}{}{I've already told you. My name is John Butler. I am the mayor of Glow... well, the future Glow.}
{250}{}{我已经告诉过你了。我的名字叫约翰·巴特勒。我是Glow的市长。。。好吧，未来的光辉。 -- I've already told you. My name is John Butler. I am the mayor of Glow... well, the future Glow.}
### {251}{}{Is San Isidro part of your domain?}
{251}{}{圣伊西德罗是你的领地吗？ -- Is San Isidro part of your domain?}
### {252}{}{This is one of the areas of the future Glow. There are several Gulian camps on the ruins. The Old Town and San Isidro are the largest of them. And each is managed by its own administrator. * God save America! *}
{252}{}{这是未来Glow的一个区域。废墟上有几个古里安营地。老城和圣伊西德罗是其中最大的。每个都由自己的管理员管理。*上帝保佑美国* -- This is one of the areas of the future Glow. There are several Gulian camps on the ruins. The Old Town and San Isidro are the largest of them. And each is managed by its own administrator. * God save America! *}

#Story quests
### {259}{}{Urgently! No wonder you had to fix a radio station. A caravan of Truckers has just contacted us. The guys were ambushed on the fifth highway. Ghouls are too slow and weak. All hope is in you. Come on, help your brothers in a difficult moment. *Step-march!*}
{259}{}{紧急地怪不得你必须修理一个电台。一个卡车司机车队刚刚和我们取得联系。他们在第五条高速公路上遭到伏击。食尸鬼太慢太弱。所有的希望都在你身上。来吧，在困难的时刻帮助你的兄弟们*大步前进* -- Urgently! No wonder you had to fix a radio station. A caravan of Truckers has just contacted us. The guys were ambushed on the fifth highway. Ghouls are too slow and weak. All hope is in you. Come on, help your brothers in a difficult moment. *Step-march!*}
### {260}{}{I'm already running as fast as I can!}
{260}{}{我已经在尽我所能地跑了！ -- I'm already running as fast as I can!}
### {261}{}{You, as usual, are of no use. Okay, I'll do it.}
{261}{}{你和往常一样没有用。好吧，我来做。 -- You, as usual, are of no use. Okay, I'll do it.}
### {262}{}{A caravan at a road junction. Go straight north on the main highway.}
{262}{}{路口的大篷车。在主干道上一直向北走。 -- A caravan at a road junction. Go straight north on the main highway.}
### {263}{}{Truckers ? are they alive?}
{263}{}{卡车司机? 他们还活着吗？ -- Truckers ? are they alive?}
### {264}{}{I haven't had a chance to see them yet. I'll be back when I find out.}
{264}{}{我还没有机会见到他们。我发现后会回来的。 -- I haven't had a chance to see them yet. I'll be back when I find out.}
### {265}{}{Mr. Rutger told me about your feat. Saving the caravan is only good for us, the ghouls. We need things from the north, and the Truckers are the most reliable caravan company. So ? thank you}
{265}{}{罗格先生告诉我你的壮举。拯救商队只对我们这些食尸鬼有好处。我们需要来自北方的东西，而卡车司机是最可靠的商队。所以? 非常感谢。 -- Mr. Rutger told me about your feat. Saving the caravan is only good for us, the ghouls. We need things from the north, and the Truckers are the most reliable caravan company. So ? thank you}
### {266}{}{.}
{266}{}{。 -- .}
### {267}{}{, smooth-skinned.}
{267}{}{，皮肤光滑。 -- , smooth-skinned.}
### {268}{}{No problem.}
{268}{}{没问题。 -- No problem.}
### {269}{}{I can see by your eyes that your mission has failed. Well, Rutger was the best trucker. Without him and his company, it will be more difficult to trade with people. But Gustavo will be glad to hear it. He does not want to share with the smooth-skinned finds of the Old World.}
{269}{}{从你的眼睛里我可以看出你的任务失败了。罗格是最好的卡车司机。没有他和他的公司，与人交易将更加困难。但古斯塔沃会很高兴听到这个消息。他不想与那些皮肤光滑的旧世界的发现分享。 -- I can see by your eyes that your mission has failed. Well, Rutger was the best trucker. Without him and his company, it will be more difficult to trade with people. But Gustavo will be glad to hear it. He does not want to share with the smooth-skinned finds of the Old World.}
### {270}{}{That was the calculation.}
{270}{}{这就是计算。 -- That was the calculation.}
### {271}{}{Sorry it happened like that. But I did my best.}
{271}{}{很抱歉发生这样的事。但我已经尽力了。 -- Sorry it happened like that. But I did my best.}
### {1271}{}{Sorry it happened like that. But I did my best.}
{1271}{}{很抱歉发生这样的事。但我已经尽力了。 -- Sorry it happened like that. But I did my best.}
### {272}{}{Now I need to check and think about something. In the meantime, you can rest.}
{272}{}{现在我需要检查并思考一些事情。在此期间，你可以休息。 -- Now I need to check and think about something. In the meantime, you can rest.}
### {273}{}{Okay.}
{273}{}{可以 -- Okay.}
### {274}{}{}
{274}{}{error : string is empty -- }
### {275}{}{}
{275}{}{error : string is empty -- }
### {276}{}{}
{276}{}{error : string is empty -- }
### {277}{}{}
{277}{}{error : string is empty -- }
### {278}{}{}
{278}{}{error : string is empty -- }
### {279}{}{}
{279}{}{error : string is empty -- }

#Story quests
### {300}{}{Gustavo asked me to give you this CD.}
{300}{}{古斯塔沃让我把这张CD给你。 -- Gustavo asked me to give you this CD.}
### {301}{}{Give it here. Let's see what this wheezer got into his head ... hmm. Yes, this is killer news! Now Glow has electricity and radio communication. Just like in the good old days. What could be better? *Everyone to the front! All for the war!*}
{301}{}{给我。让我们看看这个喘息者脑子里想的是什么。。。嗯。是的，这是个致命的消息！现在Glow拥有电力和无线电通信。就像过去一样。还有什么更好的呢*大家到前线去！一切为了战争* -- Give it here. Let's see what this wheezer got into his head ... hmm. Yes, this is killer news! Now Glow has electricity and radio communication. Just like in the good old days. What could be better? *Everyone to the front! All for the war!*}
### {302}{}{[Next]}
{302}{}{[下一个 -- Next]}
### {303}{}{Oh, and Gustavo again demands to break with the smooth-skinned. This senile old man doesn't understand anything. * Aim! Fire!* You see, Gustavo wants to protect the city from outsiders. And I think it's stupid. We need things and food from the Hub. And the Hub needs Glow technologies. Tell me, you're not going to indulge his nonsense, are you?}
{303}{}{哦，古斯塔沃再次要求与皮肤光滑的人分手。这个上了年纪的老人什么都不懂目标着火！*你看，古斯塔沃想保护这座城市不受外来者的影响。我觉得这很愚蠢。我们需要中心的东西和食物。集线器需要Glow技术。告诉我，你不会沉溺于他的胡言乱语吧？ -- Oh, and Gustavo again demands to break with the smooth-skinned. This senile old man doesn't understand anything. * Aim! Fire!* You see, Gustavo wants to protect the city from outsiders. And I think it's stupid. We need things and food from the Hub. And the Hub needs Glow technologies. Tell me, you're not going to indulge his nonsense, are you?}
### {304}{}{I'm not going to.}
{304}{}{我不会的。 -- I'm not going to.}
### {305}{}{I don't care which one of you pays for the work.}
{305}{}{我不在乎你们中的哪一个为这项工作付钱。 -- I don't care which one of you pays for the work.}
### {306}{}{Great. Then I have a couple of small and easy tasks for you.}
{306}{}{太棒了然后我有几个小而简单的任务给你。 -- Great. Then I have a couple of small and easy tasks for you.}
### {307}{}{I'm listening.}
{307}{}{我在听。 -- I'm listening.}
### {308}{}{What if I'm going to?}
{308}{}{如果我要去呢？ -- What if I'm going to?}
### {309}{}{It will be sad. And very stupid.}
{309}{}{这将是可悲的。而且非常愚蠢。 -- It will be sad. And very stupid.}
### {310}{}{Not convinced. I'm going back to San Ysidro.}
{310}{}{不相信。我要回圣伊西德罗。 -- Not convinced. I'm going back to San Ysidro.}
### {311}{}{Okay. Convinced. What do you need to do?}
{311}{}{可以深信。你需要做什么？ -- Okay. Convinced. What do you need to do?}
### {312}{}{It will be sad. And very stupid. Tell me, don't you care who pays for the work? I need your services too.}
{312}{}{这将是可悲的。而且非常愚蠢。告诉我，你不在乎谁来买单吗？我也需要你的服务。 -- It will be sad. And very stupid. Tell me, don't you care who pays for the work? I need your services too.}
### {313}{}{What do you need to do?}
{313}{}{你需要做什么？ -- What do you need to do?}

### {320}{}{Now the scavengers are disassembling the old aircraft factory by cogs. I don't mind that smooth muzzles do it. But they work without Seth's Seal and also force ghouls to work. And most importantly, we need electronics from this factory for the nearest caravan. * Attack!* Go to the Factory. Tell the scavengers that I'll give them Seth's Seal if they complete the chip collection order. Yes, and don't say a word to Gustavo!}
{320}{}{现在，拾荒者们正在用齿轮拆卸旧飞机工厂。我不介意光滑的枪口能做到这一点。但它们在没有赛斯之印的情况下工作，也会迫使食尸鬼工作。最重要的是，我们需要这家工厂的电子产品，以供最近的房车使用。*攻击！*去工厂。告诉拾荒者，如果他们完成了芯片收集订单，我会给他们赛斯封印。是的，不要对古斯塔沃说一句话！ -- Now the scavengers are disassembling the old aircraft factory by cogs. I don't mind that smooth muzzles do it. But they work without Seth's Seal and also force ghouls to work. And most importantly, we need electronics from this factory for the nearest caravan. * Attack!* Go to the Factory. Tell the scavengers that I'll give them Seth's Seal if they complete the chip collection order. Yes, and don't say a word to Gustavo!}
### {321}{}{What is the "Seal of Set"?}
{321}{}{什么是“套装印章”？ -- What is the "Seal of Set"?}
### {322}{}{This is a mining right in San Diego and its environs. Of course, in exchange for a portion of the profits. A kind of tax. * Don't give up!* If the scavengers take all the fossils for themselves, then our city will have nothing left.}
{322}{}{这是圣地亚哥及其周边地区的采矿权。当然，以换取一部分利润。一种税。*不要放弃！*如果拾荒者把所有的化石都据为己有，那么我们的城市将一无所有。 -- This is a mining right in San Diego and its environs. Of course, in exchange for a portion of the profits. A kind of tax. * Don't give up!* If the scavengers take all the fossils for themselves, then our city will have nothing left.}
### {323}{}{Clearly. I'll try to talk to them.}
{323}{}{清晰地我会试着和他们谈谈。 -- Clearly. I'll try to talk to them.}
### {324}{}{We need to talk about the situation with the scavengers at the Plant.}
{324}{}{我们需要和工厂的拾荒者谈谈情况。 -- We need to talk about the situation with the scavengers at the Plant.}
### {325}{}{So, has the mining plan been completed?}
{325}{}{那么，采矿计划完成了吗？ -- So, has the mining plan been completed?}
### {326}{}{No, unfortunately.}
{326}{}{不，很不幸。 -- No, unfortunately.}
### {327}{}{I just want to ask again, what is the "Seal of Set"?}
{327}{}{我只想再问一次，什么是“封印”？ -- I just want to ask again, what is the "Seal of Set"?}
### {328}{}{Ah, now I understand.}
{328}{}{啊，现在我明白了。 -- Ah, now I understand.}
### {329}{}{It so happened that all the scavengers at the plant died.}
{329}{}{碰巧工厂里所有的拾荒者都死了。 -- It so happened that all the scavengers at the plant died.}
### {330}{}{Did everyone die? Holy saints! And the chips? Did you manage to collect them?}
{330}{}{所有人都死了吗？圣斗士！芯片呢？你设法把它们收集起来了吗？ -- Did everyone die? Holy saints! And the chips? Did you manage to collect them?}
### {331}{}{You're always welcome.}
{331}{}{永远欢迎你。 -- You're always welcome.}
### {332}{}{Will I get something for trying?}
{332}{}{我能尝试一下吗？ -- Will I get something for trying?}
### {333}{}{We collected all the chips and sent them here.}
{333}{}{我们收集了所有的筹码并把它们送到这里。 -- We collected all the chips and sent them here.}
### {334}{}{Great job. * Take no prisoners!*}
{334}{}{干得好。*不准俘虏* -- Great job. * Take no prisoners!*}
### {335}{}{Here's your reward. But don't rush to the bar. We have a problem here.}
{335}{}{这是你的奖励。但是不要急着去酒吧。我们这里有个问题。 -- Here's your reward. But don't rush to the bar. We have a problem here.}
### {336}{}{Thank you. What happened?}
{336}{}{非常感谢。发生了什么？ -- Thank you. What happened?}
### {337}{}{No. Should I?}
{337}{}{不，我应该吗？ -- No. Should I?}
### {338}{}{They were the main point! Since the scavengers have failed, then all hope is on you. Bring the damn chips.}
{338}{}{他们是重点！既然拾荒者失败了，那么所有的希望都在你身上。把该死的薯片拿来。 -- They were the main point! Since the scavengers have failed, then all hope is on you. Bring the damn chips.}
### {339}{}{Okay.}
{339}{}{可以 -- Okay.}
### {340}{}{Yes. Here they are.}
{340}{}{对它们在这儿。 -- Yes. Here they are.}
### {341}{}{Only part of it.}
{341}{}{只是其中的一部分。 -- Only part of it.}
### {342}{}{They were the main point! Since the scavengers have failed, then all hope is on you. Collect the remaining chips.}
{342}{}{他们是重点！既然拾荒者失败了，那么所有的希望都在你身上。收集剩余的碎屑。 -- They were the main point! Since the scavengers have failed, then all hope is on you. Collect the remaining chips.}
### {343}{}{The factory is now under Gustavo's control. You won't see any chips.}
{343}{}{工厂现在由古斯塔沃控制。你不会看到任何筹码。 -- The factory is now under Gustavo's control. You won't see any chips.}
### {344}{}{Did Gustavo beat me to it? This is damning news! But now there is a more serious problem. We'll have to postpone this dispute.}
{344}{}{古斯塔沃打败我了吗？这是个该死的消息！但现在有一个更严重的问题。我们将不得不推迟这场争端。 -- Did Gustavo beat me to it? This is damning news! But now there is a more serious problem. We'll have to postpone this dispute.}
### {345}{}{What happened?}
{345}{}{发生了什么？ -- What happened?}
### {346}{}{Where is the aircraft factory located?}
{346}{}{飞机工厂在哪里？ -- Where is the aircraft factory located?}
### {347}{}{Get to Route 805. Find Paradise Valley Hospital there. The factory will be to the east.}
{347}{}{到达805号公路。在那里找到天堂谷医院。工厂将在东边。 -- Get to Route 805. Find Paradise Valley Hospital there. The factory will be to the east.}
### {348}{}{I see.}
{348}{}{我明白了。 -- I see.}
### {349}{}{}
{349}{}{error : string is empty -- }

### {350}{}{So, I thought it over and made a decision! You see, Mr. Rutger was carrying a valuable contract from the Hub to exchange technology from the Coronado Military Base. This is a HUGE profit for the city. We can restore the ruins. The dream of the Dayglow will be fulfilled! *Viva, America!*}
{350}{}{所以，我想了想，做了一个决定！你看，Rutger先生带着一份来自Hub的宝贵合同，从Coronado军事基地交换技术。这对这个城市来说是一笔巨大的利润。我们可以修复废墟。曙光的梦想将会实现*万岁，美国* -- So, I thought it over and made a decision! You see, Mr. Rutger was carrying a valuable contract from the Hub to exchange technology from the Coronado Military Base. This is a HUGE profit for the city. We can restore the ruins. The dream of the Dayglow will be fulfilled! *Viva, America!*}
### {351}{}{From a military base? Seriously?}
{351}{}{从军事基地来的？认真地 -- From a military base? Seriously?}
### {352}{}{Now you can't get there because of old military toys. Here are the access codes. They need to be sent over that radio link you set up in San Ysidro. We don't have another powerful signal source. When you do this, come to the pier, there will be an escort waiting there. And don't tell Gustavo about it!}
{352}{}{现在你不能去那里，因为旧的军用玩具。这是访问代码。他们需要通过你在圣伊西德罗建立的无线电连接发送。我们没有其他强大的信号源。当你这样做的时候，来到码头，会有一个护卫在那里等着。不要告诉古斯塔沃这件事！ -- Now you can't get there because of old military toys. Here are the access codes. They need to be sent over that radio link you set up in San Ysidro. We don't have another powerful signal source. When you do this, come to the pier, there will be an escort waiting there. And don't tell Gustavo about it!}
### {353}{}{[Leave]}
{353}{}{[离开 -- Leave]}
