### {100}{}{You see Rutger.}
{100}{}{你看到罗格了。 -- You see Rutger.}
### {101}{}{Here is the head of the Truckers squad.}
{101}{}{这是卡车司机队的队长。 -- Here is the head of the Truckers squad.}
### {102}{}{Hush! All conversations will be in the camp.}
{102}{}{安静所有对话都将在营地进行。 -- Hush! All conversations will be in the camp.}
### {103}{}{Rutger went to the caravan camp.}
{103}{}{罗格去了商队营地。 -- Rutger went to the caravan camp.}
### {104}{}{Stay away, mutant! I'll fucking kill you!}
{104}{}{走开，变种人！我他妈的要杀了你！ -- Stay away, mutant! I'll fucking kill you!}

### {200}{}{I expected to see anyone here, but not a normal person.}
{200}{}{我本以为会在这里看到任何人，但不是一个正常人。 -- I expected to see anyone here, but not a normal person.}
### {201}{}{I was sent to help the ghouls.}
{201}{}{我被派去帮助食尸鬼。 -- I was sent to help the ghouls.}
### {202}{}{The mutants were waiting for us in ambush. Fortunately, we spotted them in time and turned into warehouses. They don't dare to attack yet, but it's a matter of time. Can you sneak us out of here?}
{202}{}{变种人埋伏着等我们。幸运的是，我们及时发现了它们，并把它们变成了仓库。他们还不敢进攻，但这只是时间问题。你能偷偷带我们离开这里吗？ -- The mutants were waiting for us in ambush. Fortunately, we spotted them in time and turned into warehouses. They don't dare to attack yet, but it's a matter of time. Can you sneak us out of here?}
### {203}{}{I think I can. I managed to get here.}
{203}{}{我想我可以。我设法来到这里。 -- I think I can. I managed to get here.}
### {204}{}{Great. Then let's act one at a time. Get my subordinates out first.}
{204}{}{太棒了那我们一次演一个吧。先把我的下属赶出去。 -- Great. Then let's act one at a time. Get my subordinates out first.}
### {205}{}{Okay.}
{205}{}{可以 -- Okay.}
### {206}{}{I'll distract the mutants while you get the guards out. Together, it will be harder for us to hide from super mutants.}
{206}{}{我会分散变种人的注意力，而你把警卫弄出来。加在一起，我们将更难躲避超级变种人。 -- I'll distract the mutants while you get the guards out. Together, it will be harder for us to hide from super mutants.}
### {207}{}{Okay.}
{207}{}{可以 -- Okay.}
### {208}{}{I'm left alone, right? Then let's get out of here!}
{208}{}{我一个人待着，对吧？那我们离开这里吧！ -- I'm left alone, right? Then let's get out of here!}
### {209}{}{Leaving.}
{209}{}{离开。 -- Leaving.}
### {210}{}{It's dangerous to go out now. We need to wait a bit.}
{210}{}{现在出去很危险。我们需要等待一段时间。 -- It's dangerous to go out now. We need to wait a bit.}
### {211}{}{I saw the mutants leave along the highway. But it could be a trap. Try to get my subordinates out first.}
{211}{}{我看到变种人沿着高速公路离开。但这可能是一个陷阱。试着先把我的下属赶出去。 -- I saw the mutants leave along the highway. But it could be a trap. Try to get my subordinates out first.}
### {212}{}{It is unlikely that we will be able to leave unnoticed. How about attacking the enemy first?}
{212}{}{我们不太可能被忽视。先攻击敌人怎么样？ -- It is unlikely that we will be able to leave unnoticed. How about attacking the enemy first?}
### {213}{}{I can't risk my people. We will act with cunning. Get the guards out first.}
{213}{}{我不能拿我的人冒险。我们将采取狡猾的行动。先把警卫弄出去。 -- I can't risk my people. We will act with cunning. Get the guards out first.}
### {214}{}{Soon there will be more people here than ghouls. It seems you need help?}
{214}{}{很快这里的人就会比食尸鬼还多。你似乎需要帮助？ -- Soon there will be more people here than ghouls. It seems you need help?}
