### {100}{}{You see a guardian ghoul.}
{100}{}{你看到一个守护食尸鬼。 -- You see a guardian ghoul.}
### {101}{}{Here is a ghoul dressed in combat armor.}
{101}{}{这是一个穿着战斗盔甲的食尸鬼。 -- Here is a ghoul dressed in combat armor.}
### {102}{}{We do not tolerate competitors. Get out of here!}
{102}{}{我们不容忍竞争对手。滚出去！ -- We do not tolerate competitors. Get out of here!}
### {103}{}{If you were actually a patrol officer, you wouldn't have the power here.}
{103}{}{如果你真的是一名巡逻官，你在这里就没有权力了。 -- If you were actually a patrol officer, you wouldn't have the power here.}
### {104}{}{Were you allowed to be here?}
{104}{}{你被允许在这里吗？ -- Were you allowed to be here?}
### {105}{}{Big changes are waiting for us.}
{105}{}{巨大的变化正在等着我们。 -- Big changes are waiting for us.}

### {200}{}{Let's decide right away, an eccentric person, smooth people are not welcome here. But if you behave yourself, they won't touch you. Is that clear? Good. Come on, tell me what you need?}
{200}{}{让我们马上决定，这里不欢迎一个古怪、圆滑的人。但如果你表现得好一点，他们就不会碰你。清楚吗？好的来吧，告诉我你需要什么？ -- Let's decide right away, an eccentric person, smooth people are not welcome here. But if you behave yourself, they won't touch you. Is that clear? Good. Come on, tell me what you need?}
### {201}{}{Welcome, brother. Were you well received in San Ysidro? Do you need anything?}
{201}{}{欢迎你，兄弟。你在圣伊西德罗受到欢迎吗？你需要什么吗？ -- Welcome, brother. Were you well received in San Ysidro? Do you need anything?}
### {1201}{}{Welcome, Sister. Were you well received in San Ysidro? Do you need anything?}
{1201}{}{欢迎，姐姐。你在圣伊西德罗受到欢迎吗？你需要什么吗？ -- Welcome, Sister. Were you well received in San Ysidro? Do you need anything?}
### {202}{}{I just want to ask a few questions about the Dayglow.}
{202}{}{我只想问几个关于夜光的问题。 -- I just want to ask a few questions about the Dayglow.}
### {203}{}{What do you need?}
{203}{}{你需要什么？ -- What do you need?}
### {204}{}{Nothing. Bye.}
{204}{}{没有什么再见 -- Nothing. Bye.}
### {205}{}{Ask.}
{205}{}{问 -- Ask.}
### {206}{}{It's time for me to go. Thank you for your time.}
{206}{}{我该走了。谢谢你抽出时间。 -- It's time for me to go. Thank you for your time.}
### {207}{}{I see. I'll ask you something else, okay?}
{207}{}{我明白了。我再问你一些别的问题，好吗？ -- I see. I'll ask you something else, okay?}
### {208}{}{}
{208}{}{error : string is empty -- }
### {209}{}{}
{209}{}{error : string is empty -- }
### {210}{}{Tell me about yourself?}
{210}{}{告诉我你自己的情况？ -- Tell me about yourself?}
### {211}{}{Retired Sergeant Robert Newsom. Before the war, I kept order on the streets of Bakersfield, and now I keep order in the Glare of the Day. I love my job. And I will not allow anyone to bully in my domain.}
{211}{}{退役中士罗伯特·纽瑟姆。战前，我在贝克斯菲尔德的街道上维持秩序，现在我在阳光灿烂的日子里维持秩序。我热爱我的工作。我不会允许任何人在我的领域里欺负我。 -- Retired Sergeant Robert Newsom. Before the war, I kept order on the streets of Bakersfield, and now I keep order in the Glare of the Day. I love my job. And I will not allow anyone to bully in my domain.}
### {212}{}{What do you think of Gustavo?}
{212}{}{你觉得古斯塔沃怎么样？ -- What do you think of Gustavo?}
### {213}{}{He's a great fit for the role of mayor. And the ghouls respect him. At least not here in San Ysidro. Although not everyone in the Old City is as reasonable.}
{213}{}{他非常适合当市长。食尸鬼尊重他。至少在圣伊西德罗没有。虽然不是老城区的每个人都这么通情达理。 -- He's a great fit for the role of mayor. And the ghouls respect him. At least not here in San Ysidro. Although not everyone in the Old City is as reasonable.}
### {214}{}{And who runs the Old City?}
{214}{}{谁来管理老城？ -- And who runs the Old City?}
### {215}{}{John Butler. Ex-military. Therefore, his head is full of bedlam. He gathered around him not only ghouls, but also super mutants and normies. Everyone needs something from him.}
{215}{}{约翰·巴特勒。退役军人。因此，他的脑子里充满了混乱。他聚集在他周围的不仅是食尸鬼，还有超级变种人和正常人。每个人都需要他做点什么。 -- John Butler. Ex-military. Therefore, his head is full of bedlam. He gathered around him not only ghouls, but also super mutants and normies. Everyone needs something from him.}
### {216}{}{And in what relationship are Gustavo and Butler?}
{216}{}{古斯塔沃和巴特勒是什么关系？ -- And in what relationship are Gustavo and Butler?}
### {217}{}{They've had a lot of disagreements lately. But I'm sure it won't break their friendship.}
{217}{}{他们最近有很多分歧。但我相信这不会破坏他们的友谊。 -- They've had a lot of disagreements lately. But I'm sure it won't break their friendship.}
### {218}{}{}
{218}{}{error : string is empty -- }
### {219}{}{}
{219}{}{error : string is empty -- }
### {220}{}{Tell us about the area around.}
{220}{}{告诉我们周围的地区。 -- Tell us about the area around.}
### {221}{}{San Isidro and the Old Town are the main Gulian settlements. Radioactive ruins and burnt-out parks are spread out between them. Black scavengers and monsters are often found in them.}
{221}{}{圣伊西德罗和老城区是古里安的主要定居点。放射性废墟和被烧毁的公园散布在它们之间。黑色的拾荒者和怪物经常出现在它们身上。 -- San Isidro and the Old Town are the main Gulian settlements. Radioactive ruins and burnt-out parks are spread out between them. Black scavengers and monsters are often found in them.}
### {222}{}{[Next]}
{222}{}{[下一个 -- Next]}
### {223}{}{Most of the nuclear strikes hit a military base and an industrial zone. Downtown San Diego has been hit hard, too. Devastation, high radiation, skeletons ? that's what you'll find in the ruins. And there are military robots everywhere. They scattered after the sirens turned on at the military base.}
{223}{}{大部分核打击都是针对一个军事基地和一个工业区。圣地亚哥市中心也受到了沉重打击。毁灭性打击，高辐射，骷髅? 这就是你在废墟中能找到的。到处都是军用机器人。军事基地的警笛响起后，他们散开了。 -- Most of the nuclear strikes hit a military base and an industrial zone. Downtown San Diego has been hit hard, too. Devastation, high radiation, skeletons ? that's what you'll find in the ruins. And there are military robots everywhere. They scattered after the sirens turned on at the military base.}
### {224}{}{Tell me how to get to Chula Vista?}
{224}{}{告诉我怎么去Chula Vista？ -- Tell me how to get to Chula Vista?}
### {225}{}{You need to cross the valley of the Auteuil River. There is only one surviving bridge, but it is captured by robots and mined. So we go to the county or straight through the valley. But there are many terrible creatures in the valley.}
{225}{}{你需要穿过奥特伊河的山谷。只有一座幸存的桥梁，但它被机器人捕获并被布雷。所以我们去县城或者直接穿过山谷。但是山谷里有许多可怕的生物。 -- You need to cross the valley of the Auteuil River. There is only one surviving bridge, but it is captured by robots and mined. So we go to the county or straight through the valley. But there are many terrible creatures in the valley.}
### {226}{}{Tell me how to get to the Bonita Dam?}
{226}{}{告诉我怎么去博尼塔大坝？ -- Tell me how to get to the Bonita Dam?}
### {227}{}{Follow Federal Highway 805 to the signpost. And then turn right.}
{227}{}{沿着805号联邦公路走到路标。然后向右转。 -- Follow Federal Highway 805 to the signpost. And then turn right.}
### {228}{}{Tell me how to get to the Old Town?}
{228}{}{告诉我怎么去老城？ -- Tell me how to get to the Old Town?}
### {229}{}{It will be very difficult to get there straight through the ruins. The easiest way is to get on Route 805 and go to Balboa Park. Beware of monsters in the park. Go left to the Little Italy area. And then ? to the north.}
{229}{}{穿过废墟直接到达那里将非常困难。最简单的方法是走805路，然后去巴尔博亚公园。当心公园里的怪物。向左走到小意大利地区。然后? 往北。 -- It will be very difficult to get there straight through the ruins. The easiest way is to get on Route 805 and go to Balboa Park. Beware of monsters in the park. Go left to the Little Italy area. And then ? to the north.}
### {230}{}{What is your relationship with black scavengers?}
{230}{}{你和黑人拾荒者有什么关系？ -- What is your relationship with black scavengers?}
### {231}{}{They are mostly bandits. They collect fragments of the Old World, often without even understanding what they are needed for. And then they sell it to caravans. Thereby leaving the ghouls mere crumbs. Gustavo is trying to drive them away from our ruins, and Butler wants to tame them by giving Seth's Seal to the most obedient.}
{231}{}{他们大多是土匪。他们收集旧世界的碎片，通常甚至不了解它们的用途。然后他们把它卖给大篷车。因此，食尸鬼只剩下面包屑。古斯塔沃试图把他们从我们的废墟中赶走，巴特勒想把赛斯的封印交给最听话的人来驯服他们。 -- They are mostly bandits. They collect fragments of the Old World, often without even understanding what they are needed for. And then they sell it to caravans. Thereby leaving the ghouls mere crumbs. Gustavo is trying to drive them away from our ruins, and Butler wants to tame them by giving Seth's Seal to the most obedient.}
### {232}{}{What is your relationship with super mutants?}
{232}{}{你和超级变种人有什么关系？ -- What is your relationship with super mutants?}
### {233}{}{Super mutants? The army of the Creator was divided into many fragments and scattered through the ruins. There are many such groups in the vicinity. Some of them are aggressive, some cooperate with us, the rest are on their own. Lost lost souls.}
{233}{}{超级变种人？造物主的军队被分割成许多碎片，散落在废墟中。附近有许多这样的团体。他们中的一些人很有侵略性，一些人与我们合作，其他人则靠自己。迷失的灵魂。 -- Super mutants? The army of the Creator was divided into many fragments and scattered through the ruins. There are many such groups in the vicinity. Some of them are aggressive, some cooperate with us, the rest are on their own. Lost lost souls.}

### {241}{}{A bunch of us are looking for his squad. Maybe you've heard of him?}
{241}{}{我们一群人正在寻找他的球队。也许你听说过他？ -- A bunch of us are looking for his squad. Maybe you've heard of him?}
### {242}{}{I heard that super mutants have set up a camp in Balboa Park. They are not aggressive, rather the opposite. Maybe this is the squad you're looking for.}
{242}{}{我听说超级变种人在巴尔博亚公园建立了一个营地。他们没有攻击性，恰恰相反。也许这就是你要找的球队。 -- I heard that super mutants have set up a camp in Balboa Park. They are not aggressive, rather the opposite. Maybe this is the squad you're looking for.}
### {243}{}{Clear. Thank you.}
{243}{}{清楚的非常感谢。 -- Clear. Thank you.}
