### {100}{}{You see a super mutant shadow.}
{100}{}{你看到一个超级变种人的影子。 -- You see a super mutant shadow.}
### {101}{}{Here is a super mutant in combat gear.}
{101}{}{这是一个穿着战斗装备的超级变种人。 -- Here is a super mutant in combat gear.}
### {102}{}{We, the shadows, will remain faithful to the Creator and his ideas. Even if the normies leave us alone.}
{102}{}{我们，影子，将继续忠于造物主和他的思想。即使正常人不理我们。 -- We, the shadows, will remain faithful to the Creator and his ideas. Even if the normies leave us alone.}

### {200}{}{Hey, man, hold your gun. We won't touch you until you attack.}
{200}{}{嘿，伙计，拿好你的枪。在你攻击之前，我们不会碰你。 -- Hey, man, hold your gun. We won't touch you until you attack.}
### {201}{}{Hey, friend, don't worry. We won't hurt you if you don't attack.}
{201}{}{嘿，朋友，别担心。如果你不进攻，我们不会伤害你。 -- Hey, friend, don't worry. We won't hurt you if you don't attack.}
### {202}{}{Where does such benevolence come from?}
{202}{}{这样的仁慈从何而来？ -- Where does such benevolence come from?}
### {203}{}{Why would I believe you?}
{203}{}{我为什么会相信你？ -- Why would I believe you?}
### {204}{}{We're just tired of the war. Let people stop chasing! That's all we're asking.}
{204}{}{我们只是厌倦了战争。让人们停止追逐！这就是我们的全部要求。 -- We're just tired of the war. Let people stop chasing! That's all we're asking.}
### {205}{}{Clear. Well, bye then.}
{205}{}{清楚的好吧，再见。 -- Clear. Well, bye then.}
### {206}{}{Don't stare, little man. I don't like people staring.}
{206}{}{别盯着看，小个子。我不喜欢别人盯着看。 -- Don't stare, little man. I don't like people staring.}
### {207}{}{Whatever you say.}
{207}{}{不管你说什么。 -- Whatever you say.}
### {208}{}{}
{208}{}{error : string is empty -- }
### {209}{}{}
{209}{}{error : string is empty -- }

### {210}{}{Tell me, is it true that you drove a bunch out of your squad?}
{210}{}{告诉我，你真的把一群人赶出了你的小队吗？ -- Tell me, is it true that you drove a bunch out of your squad?}
### {211}{}{A bunch? We don't even want to hear about him. The traitor! He lost his loyalty to the squad. There is no excuse for him.}
{211}{}{一堆？我们甚至不想听到他的消息。叛徒！他失去了对球队的忠诚。他没有任何借口。 -- A bunch? We don't even want to hear about him. The traitor! He lost his loyalty to the squad. There is no excuse for him.}
### {212}{}{He can redeem himself.}
{212}{}{他可以自我救赎。 -- He can redeem himself.}
### {213}{}{I do not believe. A bunch of dumb. He's not even fit to carry a machine gun. It's a pity the captain is not with us to tell him off again...}
{213}{}{我不相信。一群蠢蛋。他甚至不适合带机关枪。遗憾的是，船长没有和我们在一起，再次斥责他。。。 -- I do not believe. A bunch of dumb. He's not even fit to carry a machine gun. It's a pity the captain is not with us to tell him off again...}
### {214}{}{And what happened to the captain?}
{214}{}{船长怎么了？ -- And what happened to the captain?}
### {215}{}{Captured in disgrace by the soldiers of the Brotherhood of Steel. Now he is being tortured at the patrol center near San Ysidro.}
{215}{}{被钢铁兄弟会的士兵可耻地俘虏了。现在，他在圣伊西德罗附近的巡逻中心受到折磨。 -- Captured in disgrace by the soldiers of the Brotherhood of Steel. Now he is being tortured at the patrol center near San Ysidro.}
### {216}{}{So why are you standing here and not saving him?}
{216}{}{你为什么站在这里不救他？ -- So why are you standing here and not saving him?}
### {217}{}{It's a trap, you stupid man! The Brotherhood soldiers want to catch us all. The captain himself said when he left: there is no need to save him.}
{217}{}{这是个陷阱，你这个蠢蛋！兄弟会的士兵想抓住我们所有人。船长自己在离开时说：没有必要救他。 -- It's a trap, you stupid man! The Brotherhood soldiers want to catch us all. The captain himself said when he left: there is no need to save him.}
### {218}{}{Well, you are stupid! If I were you, I'd do anything to get the captain out. Let's go, a bunch, from these losers.}
{218}{}{你真愚蠢！如果我是你，我愿意做任何事把船长救出来。我们走吧，一群失败者。 -- Well, you are stupid! If I were you, I'd do anything to get the captain out. Let's go, a bunch, from these losers.}
### {1218}{}{Well, you are stupid! If I were you, I would do anything to get the captain out. Let's go, a bunch, from these losers.}
{1218}{}{你真愚蠢！如果我是你，我愿意做任何事把船长救出来。我们走吧，一群失败者。 -- Well, you are stupid! If I were you, I would do anything to get the captain out. Let's go, a bunch, from these losers.}
### {219}{}{I understand. An order is an order. Come on, Bunch, we need to talk face to face.}
{219}{}{我理解。命令就是命令。来吧，邦奇，我们需要面对面交谈。 -- I understand. An order is an order. Come on, Bunch, we need to talk face to face.}
### {220}{}{Well, you are stupid! If I were you, I'd do anything to get the captain out. Bye, losers.}
{220}{}{你真愚蠢！如果我是你，我愿意做任何事把船长救出来。再见，失败者。 -- Well, you are stupid! If I were you, I'd do anything to get the captain out. Bye, losers.}
### {1220}{}{Well, you are stupid! If I were you, I would do anything to get the captain out. Bye, losers.}
{1220}{}{你真愚蠢！如果我是你，我愿意做任何事把船长救出来。再见，失败者。 -- Well, you are stupid! If I were you, I would do anything to get the captain out. Bye, losers.}
### {221}{}{I understand. An order is an order.}
{221}{}{我理解。命令就是命令。 -- I understand. An order is an order.}
### {222}{}{Your captain is dead. I failed to save him from the hands of the Brotherhood of Steel.}
{222}{}{你的船长死了。我没能把他从钢铁兄弟会手中救出来。 -- Your captain is dead. I failed to save him from the hands of the Brotherhood of Steel.}
### {223}{}{This was to be expected.}
{223}{}{这是意料之中的事。 -- This was to be expected.}
### {224}{}{What are you going to do without the captain?}
{224}{}{没有船长你打算怎么办？ -- What are you going to do without the captain?}
### {225}{}{And that's it? There will be no angry speeches and guttural roaring? Do you even know how to survive without a captain?}
{225}{}{就这样？不会有愤怒的演讲和喉音咆哮吗？你知道没有船长怎么活吗？ -- And that's it? There will be no angry speeches and guttural roaring? Do you even know how to survive without a captain?}
### {226}{}{Your captain is saved. Don't mention it.}
{226}{}{你的队长得救了。别提了。 -- Your captain is saved. Don't mention it.}
### {227}{}{Even though you weren't asked, you're still helping the shadows. Do you really think this is how you can reconcile humans and mutants? It's impossible. But we are grateful to you anyway. I would like to show you to the Creator.}
{227}{}{即使没有人问你，你仍然在帮助阴影。你真的认为这就是你调和人类和变种人的方法吗？这是不可能的。但我们还是很感激你。我想带你去见造物主。 -- Even though you weren't asked, you're still helping the shadows. Do you really think this is how you can reconcile humans and mutants? It's impossible. But we are grateful to you anyway. I would like to show you to the Creator.}
### {228}{}{What are you going to do now?}
{228}{}{你现在打算做什么？ -- What are you going to do now?}
### {229}{}{Do you have any further plan? Or will you be stuck in the middle of a burnt park?}
{229}{}{你有进一步的计划吗？还是你会被困在一个被烧毁的公园里？ -- Do you have any further plan? Or will you be stuck in the middle of a burnt park?}
### {230}{}{We want to go east. To a place where they don't know about us yet. Away from the Brotherhood and other haters of California.}
{230}{}{我们想往东走。去一个他们还不知道我们的地方。远离兄弟会和其他憎恨加州的人。 -- We want to go east. To a place where they don't know about us yet. Away from the Brotherhood and other haters of California.}
### {231}{}{What prevents you from doing this now that the captain is with you?}
{231}{}{既然船长和你在一起，是什么阻止你这么做？ -- What prevents you from doing this now that the captain is with you?}
### {232}{}{What prevents you from doing this now that the captain no longer holds you?}
{232}{}{既然船长不再抓你，是什么阻止你这么做？ -- What prevents you from doing this now that the captain no longer holds you?}
### {233}{}{Then good luck on the way.}
{233}{}{然后祝你好运。 -- Then good luck on the way.}
### {234}{}{Right. There is nothing to spoil the mood of normal people. I hope you won't bother anyone away.}
{234}{}{正确的没有什么能破坏正常人的情绪。我希望你不要打扰任何人。 -- Right. There is nothing to spoil the mood of normal people. I hope you won't bother anyone away.}
### {235}{}{What about the Pile? Will you take him with you?}
{235}{}{桩呢？你会带他去吗？ -- What about the Pile? Will you take him with you?}
### {236}{}{If he wants to, let him return to the squad.}
{236}{}{如果他愿意，就让他回到球队吧。 -- If he wants to, let him return to the squad.}
### {237}{}{Good. He's already got everyone here.}
{237}{}{好的他已经把所有人都带到这里了。 -- Good. He's already got everyone here.}
