### {100}{}{You see Jerry's knight.}
{100}{}{你看到杰瑞的骑士了。 -- You see Jerry's knight.}
### {101}{}{Here is a knight of the Brotherhood of Steel. He looks pretty battered.}
{101}{}{这是一位钢铁兄弟会的骑士。他看起来很疲惫。 -- Here is a knight of the Brotherhood of Steel. He looks pretty battered.}

### {200}{}{Hush! A mutant lurked at the entrance. He'll kill us if he sees us. I'm also wounded and can't fight. You are my last hope.}
{200}{}{安静一个变种人潜伏在入口处。如果他看到我们，他会杀了我们。我也受伤了，不能战斗。你是我最后的希望。 -- Hush! A mutant lurked at the entrance. He'll kill us if he sees us. I'm also wounded and can't fight. You are my last hope.}
### {201}{}{Is the mutant gone? Thank you, brother! And now I need to heal my wounds. Do you have a first aid kit?}
{201}{}{变种人走了吗？谢谢你，兄弟！现在我需要疗伤。你有急救箱吗？ -- Is the mutant gone? Thank you, brother! And now I need to heal my wounds. Do you have a first aid kit?}
### {1201}{}{Is the mutant gone? Thank you, Sister! And now I need to heal my wounds. Do you have a first aid kit?}
{1201}{}{变种人走了吗？谢谢你，姐姐！现在我需要疗伤。你有急救箱吗？ -- Is the mutant gone? Thank you, Sister! And now I need to heal my wounds. Do you have a first aid kit?}
### {202}{}{Is the mutant dead? Thank you, brother! And now I need to heal my wounds. Do you have a first aid kit?}
{202}{}{变种人死了吗？谢谢你，兄弟！现在我需要疗伤。你有急救箱吗？ -- Is the mutant dead? Thank you, brother! And now I need to heal my wounds. Do you have a first aid kit?}
### {1202}{}{Is the mutant dead? Thank you, Sister! And now I need to heal my wounds. Do you have a first aid kit?}
{1202}{}{变种人死了吗？谢谢你，姐姐！现在我需要疗伤。你有急救箱吗？ -- Is the mutant dead? Thank you, Sister! And now I need to heal my wounds. Do you have a first aid kit?}
### {203}{}{I'm doing what I can. Stop whining to me here!}
{203}{}{我正在尽我所能。别在这儿对我发牢骚了！ -- I'm doing what I can. Stop whining to me here!}
### {204}{}{I will do my best.}
{204}{}{我会尽力的。 -- I will do my best.}
### {205}{}{Thank you for the treatment. Now I can fight at full strength. Although I don't have enough bullets. Where is this mutant? Probably waiting at the entrance.}
{205}{}{谢谢你的治疗。现在我可以全力战斗了。虽然我没有足够的子弹。这个变种人在哪里？可能在门口等着。 -- Thank you for the treatment. Now I can fight at full strength. Although I don't have enough bullets. Where is this mutant? Probably waiting at the entrance.}
### {206}{}{Let's go, let's give him a hard time!}
{206}{}{我们走吧，让我们给他一个艰难的时刻！ -- Let's go, let's give him a hard time!}
### {207}{}{You'd better keep your head down so that old wounds don't open up. Stay here until I deal with that bully.}
{207}{}{你最好低着头，以免旧伤口裂开。待在这里直到我对付那个恶霸。 -- You'd better keep your head down so that old wounds don't open up. Stay here until I deal with that bully.}
### {208}{}{The danger has passed. That bully has already left.}
{208}{}{危险已经过去了。那个恶霸已经走了。 -- The danger has passed. That bully has already left.}
### {209}{}{That bully won't hurt anyone else. We can come out of hiding.}
{209}{}{那个恶霸不会伤害任何人。我们可以摆脱躲藏。 -- That bully won't hurt anyone else. We can come out of hiding.}
### {210}{}{But no! Here he is! Careful!}
{210}{}{但是没有！他来了！仔细的 -- But no! Here he is! Careful!}
### {211}{}{Don't shoot! It's a bunch, my partner.}
{211}{}{不要开枪！这是一群人，我的搭档。 -- Don't shoot! It's a bunch, my partner.}
### {212}{}{Which... Of course I am grateful to you for saving me, but this is too much! Mutants are evil! They destroyed entire human settlements. What the hell is this piece of shit doing with you?}
{212}{}{哪一个我当然很感激你救了我，但这太过分了！变种人是邪恶的！他们摧毁了整个人类住区。这混蛋跟你干什么？ -- Which... Of course I am grateful to you for saving me, but this is too much! Mutants are evil! They destroyed entire human settlements. What the hell is this piece of shit doing with you?}
### {213}{}{He's harmless. Do not hate all mutants because of the misconduct of one particular group.}
{213}{}{他是无害的。不要因为某个特定群体的不当行为而憎恨所有变种人。 -- He's harmless. Do not hate all mutants because of the misconduct of one particular group.}
### {214}{}{I don't know why I need it either. But he protects me and carries things. Just don't touch him, OK?}
{214}{}{我也不知道为什么我需要它。但他保护我，带东西。只是不要碰他，好吗？ -- I don't know why I need it either. But he protects me and carries things. Just don't touch him, OK?}
### {215}{}{Who are you? You know, I once knew a resident of the asylum. He was trying to help his brothers and sisters. And when he helped, he was simply thrown out. Good without weapons ends up with something sad.}
{215}{}{你是谁？你知道，我曾经认识一个收容所的居民。他试图帮助他的兄弟姐妹。当他帮忙时，他只是被赶了出去。没有武器的好结局是可悲的。 -- Who are you? You know, I once knew a resident of the asylum. He was trying to help his brothers and sisters. And when he helped, he was simply thrown out. Good without weapons ends up with something sad.}
### {1215}{}{Who are you? You know, I once knew a resident of the asylum. He was trying to help his brothers and sisters. And when he helped, he was simply thrown out. Good without weapons ends up with something sad.}
{1215}{}{你是谁？你知道，我曾经认识一个收容所的居民。他试图帮助他的兄弟姐妹。当他帮忙时，他只是被赶了出去。没有武器的好结局是可悲的。 -- Who are you? You know, I once knew a resident of the asylum. He was trying to help his brothers and sisters. And when he helped, he was simply thrown out. Good without weapons ends up with something sad.}
### {216}{}{Maybe so.}
{216}{}{也许是这样。 -- Maybe so.}
### {217}{}{Who knows?}
{217}{}{谁知道呢？ -- Who knows?}
### {218}{}{Oh, then, six years ago, we would have had people like you on the front line ? how many brothers could have been saved from super mutants!}
{218}{}{哦，那么，六年前，我们会有像你这样的人在前线? 有多少兄弟可以从超级变种人手中拯救出来！ -- Oh, then, six years ago, we would have had people like you on the front line ? how many brothers could have been saved from super mutants!}
### {219}{}{At that time I worked on plantations and didn't know about any war with super mutants. That's why I love my rural life.}
{219}{}{当时我在种植园工作，不知道与超级变种人有任何战争。这就是为什么我喜欢我的乡村生活。 -- At that time I worked on plantations and didn't know about any war with super mutants. That's why I love my rural life.}
### {220}{}{It's enough that I managed to save you.}
{220}{}{我救了你就够了。 -- It's enough that I managed to save you.}
### {221}{}{Okay, now I need to find a place to clean up. Thank you, brother.}
{221}{}{好吧，现在我需要找个地方打扫。谢谢你，兄弟。 -- Okay, now I need to find a place to clean up. Thank you, brother.}
### {222}{}{By the way, what is the Brotherhood doing here?}
{222}{}{顺便问一下，兄弟会在这里干什么？ -- By the way, what is the Brotherhood doing here?}
### {223}{}{When the elders found out that the mutants had rushed to San Diego, I was sent along with a squad to investigate. I couldn't even think that a real hell was going on here. Radiation, monsters, super mutants, ghouls, robots ? what's not here! I need to tell the commander about this. It is impossible for ordinary people to rush here too.}
{223}{}{当长老们发现变种人已经赶往圣地亚哥时，我和一个小组一起被派去调查。我甚至不敢想象这里真的发生了地狱。辐射，怪物，超级变种人，食尸鬼，机器人? 什么东西不在这儿！我需要把这件事告诉指挥官。普通人也不可能冲到这里来。 -- When the elders found out that the mutants had rushed to San Diego, I was sent along with a squad to investigate. I couldn't even think that a real hell was going on here. Radiation, monsters, super mutants, ghouls, robots ? what's not here! I need to tell the commander about this. It is impossible for ordinary people to rush here too.}
### {224}{}{Clearly. Well, then have a safe journey. Don't get caught by mutants anymore.}
{224}{}{清晰地好吧，那就有一个安全的旅程。别再被变种人抓住了。 -- Clearly. Well, then have a safe journey. Don't get caught by mutants anymore.}
### {225}{}{Thanks again.}
{225}{}{再次感谢。 -- Thanks again.}
