### {100}{}{This is Mr. Officer.}
{100}{}{我是军官先生。 -- This is Mr. Officer.}
### {101}{}{There is a pretty worn icon painted on the board of this robot. It seems that he represents some kind of authority here.}
{101}{}{这个机器人的板子上画着一个破旧的图标。他在这里似乎代表了某种权威。 -- There is a pretty worn icon painted on the board of this robot. It seems that he represents some kind of authority here.}
### {102}{}{Be vigilant, citizen. It's not safe on the road right now.}
{102}{}{提高警惕，公民。现在在路上不安全。 -- Be vigilant, citizen. It's not safe on the road right now.}

### {110}{}{Stop it! You are violating traffic rules.}
{110}{}{住手！你违反了交通规则。 -- Stop it! You are violating traffic rules.}
### {111}{}{Being on the motorway you are violating the current legislation.}
{111}{}{你在高速公路上违反了现行法规。 -- Being on the motorway you are violating the current legislation.}
### {112}{}{It is forbidden to be outside the vehicle on the motorway.}
{112}{}{在高速公路上禁止在车外。 -- It is forbidden to be outside the vehicle on the motorway.}
### {113}{}{You're under arrest. Leave the roadbed and lie face down on the ground.}
{113}{}{你被捕了。离开路基，面朝下躺在地上。 -- You're under arrest. Leave the roadbed and lie face down on the ground.}
### {114}{}{You're coming with me to the police station.}
{114}{}{你要和我一起去警察局。 -- You're coming with me to the police station.}
### {115}{}{Give up. You will not escape justice.}
{115}{}{放弃你不会逃脱审判的。 -- Give up. You will not escape justice.}
### {116}{}{I don't want to hurt you. You created this problem yourself.}
{116}{}{我不想伤害你。这个问题是你自己造成的。 -- I don't want to hurt you. You created this problem yourself.}
### {117}{}{My program demands to stop you.}
{117}{}{我的程序要求阻止你。 -- My program demands to stop you.}
### {118}{}{All claims can be processed in the presence of a lawyer.}
{118}{}{所有索赔都可以在律师在场的情况下处理。 -- All claims can be processed in the presence of a lawyer.}
### {119}{}{I won't let you escape until you pay the fine.}
{119}{}{除非你付罚款，否则我不会让你逃跑。 -- I won't let you escape until you pay the fine.}
### {120}{}{It's my duty to stop you before you cause a traffic accident.}
{120}{}{在你发生交通事故之前，我有责任阻止你。 -- It's my duty to stop you before you cause a traffic accident.}
