### {102}{}{???"?" ???" ?!}
{102}{}{???“?“???“?! -- ???"?" ???" ?!}
### {103}{}{"Does the shadow accompany the fuck? I don't like it?.}
{103}{}{“阴影伴随着他妈的吗？我不喜欢?. -- "Does the shadow accompany the fuck? I don't like it?.}
### {{104}{}{ Hey, the income is $ha, don't confuse it with $ under your feet.}
{{104}{}{嘿，收入是$ha，不要把它和你脚下的$ha混淆了。 --  Hey, the income is $ha, don't confuse it with $ under your feet.}
