### {100}{}{In front of you is Distraught.}
{100}{}{你面前是心烦意乱。 -- In front of you is Distraught.}
### {101}{}{You see a glowing creature. It's baring its rotten teeth and growling in your direction.}
{101}{}{你看到一个发光的生物。它露出腐烂的牙齿，朝你的方向咆哮。 -- You see a glowing creature. It's baring its rotten teeth and growling in your direction.}
### {102}{}{The distraught Gonzo does not react to you in any way.}
{102}{}{悲痛欲绝的贡佐对你没有任何反应。 -- The distraught Gonzo does not react to you in any way.}
### {103}{}{AR-R-R!}
{103}{}{AR-R-R！ -- AR-R-R!}
