### {100}{}{You have read the book from beginning to end and have not found any valuable information for yourself.}
{100}{}{你从头到尾都读过这本书，没有发现任何对自己有价值的信息。 -- You have read the book from beginning to end and have not found any valuable information for yourself.}
### {101}{}{You have already read this book.}
{101}{}{你已经读过这本书了。 -- You have already read this book.}
### {102}{}{All this is the work of a bygone era.}
{102}{}{所有这些都是过去时代的作品。 -- All this is the work of a bygone era.}
