### {200}{}{Enter the command.}
{200}{}{输入命令。 -- Enter the command.}
### {201}{}{Cancel.}
{201}{}{取消 -- Cancel.}
### {202}{}{The current regime at the military base?}
{202}{}{军事基地的现政权？ -- The current regime at the military base?}
### {203}{}{Full combat readiness mode has been introduced.}
{203}{}{全面战备模式已经引入。 -- Full combat readiness mode has been introduced.}
### {204}{}{Back.}
{204}{}{返回 -- Back.}
### {205}{}{Cancel the alert mode.}
{205}{}{取消警报模式。 -- Cancel the alert mode.}
### {206}{}{Full alert mode canceled.}
{206}{}{完全警报模式已取消。 -- Full alert mode canceled.}
### {207}{}{OK.}
{207}{}{好啊 -- OK.}
### {208}{}{You have already canceled the alert mode.}
{208}{}{您已经取消了警报模式。 -- You have already canceled the alert mode.}
