### {110}{}{"there is some noise coming from the ventilation. idimo, so the agony of ventilation.}
{110}{}{“有一些噪音来自通风。艾迪莫，所以通风的痛苦。”。 -- "there is some noise coming from the ventilation. idimo, so the agony of ventilation.}
### {111}{}{This ventilation has finally subsided. Rest in peace, child of the Industrial Revolution.}
{111}{}{这种通风终于平息了。安息吧，工业革命的孩子。 -- This ventilation has finally subsided. Rest in peace, child of the Industrial Revolution.}
### {112}{}{You have scraped a can of toxic ash from the ventilation.  The gratitude of the valve stopped making creepy noises.}
{112}{}{你从通风处刮下了一罐有毒的灰烬。阀门的感激之情停止了发出令人毛骨悚然的声音。 -- You have scraped a can of toxic ash from the ventilation.  The gratitude of the valve stopped making creepy noises.}
### {120}{}{*sh-sh-sh*}
{120}{}{*嘘嘘* -- *sh-sh-sh*}
### {121}{}{*Sp?k*}
{121}{}{*Sp?k* -- *Sp?k*}
### {122}{}{*?uk*}
{122}{}{*?英国* -- *?uk*}
### {123}{}{*?r-r-r*}
{123}{}{*?r-r-r* -- *?r-r-r*}
### {124}{}{* r?k*}
{124}{}{*r?k* -- * r?k*}
