### {100}{}{Here is a fisherman.}
{100}{}{这是一个渔夫。 -- Here is a fisherman.}
### {101}{}{You see a local savage.}
{101}{}{你看到一个当地的野蛮人。 -- You see a local savage.}

### {110}{}{Fish!}
{110}{}{鱼 -- Fish!}
### {111}{}{Don't understand.}
{111}{}{不明白。 -- Don't understand.}
### {112}{}{But!}
{112}{}{但是 -- But!}
### {113}{}{Not!}
{113}{}{不 -- Not!}
### {114}{}{Water!}
{114}{}{水 -- Water!}
### {115}{}{Fish?}
{115}{}{鱼 -- Fish?}
### {116}{}{Tuki-tuki.}
{116}{}{Tuki Tuki。 -- Tuki-tuki.}
### {117}{}{Water. Fish. Catch.}
{117}{}{水鱼接住 -- Water. Fish. Catch.}
### {118}{}{Ya. You. Speak.}
{118}{}{是的。你谈 -- Ya. You. Speak.}
### {119}{}{You. I. There is no war.}
{119}{}{你一、没有战争。 -- You. I. There is no war.}
