### {110}{}{This box is boarded up. It can only be opened by brute force.}
{110}{}{这个箱子是用木板封起来的。它只能用蛮力打开。 -- This box is boarded up. It can only be opened by brute force.}
### {111}{}{You don't have enough strength to use the tool.}
{111}{}{你没有足够的力量使用这个工具。 -- You don't have enough strength to use the tool.}
### {112}{}{You managed to open the lid of the box.}
{112}{}{你设法打开了箱子的盖子。 -- You managed to open the lid of the box.}

### {120}{}{You have only slightly opened the wall of the box. Push harder.}
{120}{}{你只稍微打开了盒子的墙壁。用力推。 -- You have only slightly opened the wall of the box. Push harder.}
### {121}{}{A little more and you're at the goal!}
{121}{}{再多一点，你就进球了！ -- A little more and you're at the goal!}
### {122}{}{Come on! This box is almost broken.}
{122}{}{来吧这个盒子几乎坏了。 -- Come on! This box is almost broken.}
### {123}{}{Almost... Come on, rookie, do it!}
{123}{}{几乎加油，菜鸟，加油！ -- Almost... Come on, rookie, do it!}
### {124}{}{It wasn't enough, we need to push a little more.}
{124}{}{这还不够，我们需要再努力一点。 -- It wasn't enough, we need to push a little more.}
### {125}{}{Almost got it! We need to push a little more.}
{125}{}{差点就搞定了！我们需要再努力一点。 -- Almost got it! We need to push a little more.}
