### {100}{}{Pip-Boy display: File found in the system. Download aborted.}
{100}{}{Pip Boy显示：在系统中找到文件。下载中止。 -- Pip-Boy display: File found in the system. Download aborted.}
### {101}{}{Pip-Boy display: Copying data... Download completed.}
{101}{}{Pip Boy显示：正在复制数据。。。下载完成。 -- Pip-Boy display: Copying data... Download completed.}
### {102}{}{Pip-Boy display: Data is not available. Download aborted.}
{102}{}{皮普男孩显示：数据不可用。下载中止。 -- Pip-Boy display: Data is not available. Download aborted.}
### {103}{}{To your shame, you still haven't learned how to use holodisks.}
{103}{}{遗憾的是，你还没有学会如何使用全息盘。 -- To your shame, you still haven't learned how to use holodisks.}
