### {110}{}{"To use the trap, you need the appropriate skills.}
{110}{}{“要使用陷阱，你需要适当的技能。 -- "To use the trap, you need the appropriate skills.}
### {111}{}{N-n-m! These iguanas were not quick enough, and soon they will be in someone's stomach.}
{111}{}{N-N-m！这些鬣蜥不够快，很快就会进入别人的胃里。 -- N-n-m! These iguanas were not quick enough, and soon they will be in someone's stomach.}
### {112}{}{- with such skills, this trap will be more useless than garbage.}
{112}{}{-有了这样的技能，这个陷阱将比垃圾更无用。 -- - with such skills, this trap will be more useless than garbage.}
### {113}{}{the feeding is over, this trap is now useless.}
{113}{}{喂食结束了，这个陷阱现在没用了。 -- the feeding is over, this trap is now useless.}
### {114}{}{two traps in one place? It's a useless$waste of time.}
{114}{}{一个地方有两个陷阱？这是浪费时间。 -- two traps in one place? It's a useless$waste of time.}
### {115}{}{You have successfully set the trap.}
{115}{}{您已成功设置陷阱。 -- You have successfully set the trap.}
### {116}{}{?orosha? ida?, but you have no idea how to do it.}
{116}{}{?orosha? ida?, 但是你不知道怎么做。 -- ?orosha? ida?, but you have no idea how to do it.}
