### {110}{}{It looks like this }
{110}{}{它看起来像这样 -- It looks like this }
### {111}{}{ short-circuited. But it can still be repaired.}
{111}{}{短路。但它仍然可以修复。 --  short-circuited. But it can still be repaired.}
### {112}{}{This one }
{112}{}{这个 -- This one }
### {113}{}{ works. And it will work for some more time.}
{113}{}{作品而且它还会持续一段时间。 --  works. And it will work for some more time.}
### {114}{}{Have you fixed this one yet }
{114}{}{你把这个修好了吗 -- Have you fixed this one yet }
### {115}{}{.}
{115}{}{。 -- .}
### {116}{}{You have successfully fixed this }
{116}{}{您已成功修复此问题 -- You have successfully fixed this }
### {117}{}{. Now it will give stable light for some more time.}
{117}{}{。现在它将在一段时间内提供稳定的光线。 -- . Now it will give stable light for some more time.}
### {118}{}{The repair failed. Maybe you should improve your repair skill.}
{118}{}{修复失败。也许你应该提高你的修理技术。 -- The repair failed. Maybe you should improve your repair skill.}
### {119}{}{You've done something wrong. Try again.}
{119}{}{你做错了什么。请重试。 -- You've done something wrong. Try again.}
### {120}{}{ due to your incompetence, it finally fails.}
{120}{}{由于你的无能，它最终失败了。 --  due to your incompetence, it finally fails.}
