### {110}{}{Explosives could be assembled from these components.}
{110}{}{爆炸物可以由这些部件组装而成。 -- Explosives could be assembled from these components.}
### {111}{}{The components for creating explosives have run out.}
{111}{}{制造炸药的部件已经用完了。 -- The components for creating explosives have run out.}
### {112}{}{You could try it if it wasn't so dangerous.}
{112}{}{如果不是那么危险的话，你可以试试。 -- You could try it if it wasn't so dangerous.}
### {113}{}{Using special skills, you got explosives with a timer.}
{113}{}{使用特殊技能，你可以获得带计时器的炸药。 -- Using special skills, you got explosives with a timer.}
### {114}{}{Other skills are needed here.}
{114}{}{这里还需要其他技能。 -- Other skills are needed here.}
