### {110}{}{Trap!}
{110}{}{陷阱 -- Trap!}
### {111}{}{You have found a trap.}
{111}{}{你发现了一个陷阱。 -- You have found a trap.}
### {112}{}{ falls into a trap.}
{112}{}{落入陷阱。 --  falls into a trap.}
### {113}{}{Your abilities have saved you from a dangerous trap.}
{113}{}{你的能力把你从一个危险的陷阱中救了出来。 -- Your abilities have saved you from a dangerous trap.}
### {114}{}{}
{114}{}{error : string is empty -- }
### {115}{}{This trap seems too dangerous.}
{115}{}{这个陷阱似乎太危险了。 -- This trap seems too dangerous.}
### {116}{}{The trap has been successfully defused.}
{116}{}{陷阱已成功解除。 -- The trap has been successfully defused.}
### {117}{}{You are afraid that you will not be able to set the trap here correctly.}
{117}{}{你担心你无法在这里正确设置陷阱。 -- You are afraid that you will not be able to set the trap here correctly.}
### {118}{}{The trap is set.}
{118}{}{陷阱已设置。 -- The trap is set.}
### {119}{}{This trap is currently safe.}
{119}{}{此陷阱当前是安全的。 -- This trap is currently safe.}
### {120}{}{This trap is too dangerous. We'll have to neutralize it first.}
{120}{}{这个陷阱太危险了。我们必须先消除它。 -- This trap is too dangerous. We'll have to neutralize it first.}
### {121}{}{You've shorted out the emitter.}
{121}{}{你把发射器短路了。 -- You've shorted out the emitter.}
### {122}{}{You couldn't short-circuit the emitter.}
{122}{}{你不能使发射器短路。 -- You couldn't short-circuit the emitter.}
### {123}{}{You can set a good trap here.}
{123}{}{你可以在这里设一个好陷阱。 -- You can set a good trap here.}
### {124}{}{You can build a good trap out of this.}
{124}{}{你可以从中建立一个好的陷阱。 -- You can build a good trap out of this.}
