{100}{}{You see a ragged-looking man.}
{101}{}{He doesn't look very healthy.}
#
{200}{}{You see a captive woman.}
{201}{}{She's filthy and seems to be malnourished.}
#
{300}{}{Someone help us!}
{301}{}{Hey! Can anyone hear me?}
{302}{}{This is wrong!}
{303}{}{We didn't do anything!}
{304}{}{Let us out of here!}
{305}{}{Someone get us out!}
{306}{}{What did we do?}
{307}{}{We didn't do anything.}
{308}{}{We don't deserve this.}
{309}{}{Those bastards!}
{310}{}{Help us!}
{311}{}{Let me out!}
{312}{}{We're not slaves!}
{313}{}{We're not primitives! Let us out of here!}
{314}{}{What's happening?}
{315}{}{Is someone there to save us?}
{316}{}{Over here!}
{317}{}{Help! Don't leave us!}
{318}{}{What was all that shooting?}
{319}{}{What's going on?}
