{100}{}{Greetings, traveler. What can I do for you?}
{101}{}{Who are you?}
{102}{}{Show me your supplies.}
{103}{}{Nothing.}
# who are you?
{104}{}{I'm Mark, local salesman. I’ve got some very nice stuff here. So what's it gonna be?}
{105}{}{How did you end up here?}
{106}{}{Know anything about the Falcon brothers?}
{107}{}{Sorry, got to go.}
# end up here.
{108}{}{Well, I used to travel a lot. After many years I just got tired of it and wanted to settle down for a while.
 This place looked very nice. [Smiles.] The air smells a whole lot better, plenty of water supplies... a small oasis,
 you know, like before the war. Villagers from around accepted me with great hospitality. Learned many skills from the
 locals. They know how to treat injuries with plants better than doctors do with all their fancy technology. Most people
 treat them bad. But once you get to know these "simple" people, you'll start to understand what life is all about.}
{109}{}{I guess it's not all about alternative healing methods, grassroots and natural resources... So what do you do
 here?}
# do here
{110}{}{I help these people, mostly by providing supplies. In return I get "ancient" medicines and other items I can use
 to trade. It works both ways.}
{111}{}{Let me ask you something else then.}
#anything about falcon brothers
{112}{}{Why no, I don't think I heard of them. Who are they?}
{113}{}{I've heard they were involved in some criminal activities in Farmers Town...}
{114}{}{I heard they have a caravan camp near this place, so I wanted to ask for a job.}
#some robbers
{115}{}{Like I said, never heard of them.}
{116}{}{Let me ask you something else then.}
# i heard they have a caravan...
{117}{}{You could try asking around. We don't have too many visitors these days. But locals told me some caravans
 were coming at night, spend some time around here, before departing again at the break of dawn.}
{118}{}{Okay. Thanks.}
#the stuff
{119}{}{It's always nice to see new people around here. Come back any time.}
{120}{}{Sure thing.}
#
{121}{}{Anything I can help you with?}
#at night
{122}{}{It's late, come back when the sun shines, and I can see you more clearly.}
{123}{}{This is my tent, and I don't remember inviting you.}
{124}{}{I'm open for business when I'm out there at my table. NOT when I'm in my pajamas.}
