{100}{}{It's a big mountain.}
{101}{}{This is not so bad.}
{102}{}{I find some food, here and there...}
{103}{}{At least I have a bed.}
{104}{}{What am I going to cook today?}
{105}{}{Roasted rat... mmmm...tasty!}
{106}{}{Hmm... Nothing here.}
{107}{}{Ah... Here it is.}
{108}{}{Isn't that a nice tree?}
#
{109}{}{The evil...}
{110}{}{Don't kill me please.}
{111}{}{I want to live!}
{112}{}{You murderer!}
{113}{}{Evil spirit...}
