{100}{}{Welcome to my casino. I'm Mary, so what can I do for you?}
{101}{}{Nice place you have here. Tell me something about it.}
{102}{}{Got any work for me?}
{103}{}{Nothing.}
#about the place
{104}{}{This casino is one of the oldest in these parts and it's still working... All thanks to these people. They made
 it possible. Ever since I opened this place for business, about ten years ago, those slot machines are making some
 decent profit. Enough to keep this place running. Roulette tables are very popular too, no complaints. I'm planning to
 serve some drinks here, but sheriff Milton has other plans. I understand he's concerned about public safety but I think
 this would be a good way for people to relax, feel comfortable, in other words enjoy themselves. Anyway, I'll sort it
 out somehow...}
{105}{}{Maybe I can help you.}
{106}{}{Sorry to hear that. I wish you luck.}
#
{107}{}{I don't think the sheriff would even listen but you are sure welcome to try. I would be very grateful if you
 somehow convince him to, at least, consider giving me another chance.}
{108}{}{I'll be glad to help you.}
#
{109}{}{How can I help you this time?}
#got any job?
{110}{}{Come back when you're in better shape.}
{111}{}{Sure thing.}
#
{112}{}{You're just on time. I have a small problem. One of my slot machines broke down, and the spare parts
 are in the basement...}
{113}{}{And... the basement is below us, right?}
#
{114}{}{Sounds funny but I'm scared to go down. Whole place is filled with those awful rats. Can't send any of my
 man either, security up here is top priority. Can you take care of this? I always reward good work.}
{115}{}{Sure.}
{116}{}{Later.}
#come back, job on hold
{117}{}{Want to take that job?}
#job taken, come back
{118}{}{About that job...}
#
{119}{}{Have you "cleaned" my basement?}
{120}{}{You won't be seeing those rats any more.}
{121}{}{Not yet.}
#uzeo posao i zavrsio
{122}{}{Excellent, you got me worried for a second [smiles]. Now I just need to repair that slot machine and that's
 the easy part. I got $400 for you, take it.}
{123}{}{Thanks.}
#
{124}{}{Come back some other time, I might have more jobs for you.}
{125}{}{See ya.}
#
{126}{}{Business is going as usual. Nothing interesting, but still... I know it could be better.}
{127}{}{I'll leave you to it.}
{128}{}{I talked about your "situation" with sheriff Milton, and... he will let you sell drinks but he has one condition.
 You have to be more careful about the kind of people you let in here. He's counting on you to keep your customers safe
 and as long you can keep that part of the deal you can count on his support.}
#
{129}{}{Well, I admit that I may have been less than cautious with my customers. Okay, I can still make some money
 even with this new rule. I assure you, my intentions were never aimed against these people. After all I live here. Let
 me show you what good hospitality is really about, [smiles] take a free drink! I'm sure you would like some caps, too,
 in case you wanna spend some time on the slot machines... And I've been keeping this old scout book for someone like
 you. I'm sure a traveler such as yourself will find it useful.}
{130}{}{Hey, thanks. Take care now.}
#
{131}{}{Things will change, for the better, I hope. All, thanks to you. Your money is always welcome here!}
{132}{}{Bye.}
#
{133}{}{You were saying something about drinks for your casino?}
#
{134}{}{The sheriff is having second thoughts about giving me permission to sell drinks. I thought it would be a
 good idea to give it a try, see how it goes... But he doesn’t like it and now I'm stuck here watching my customers
 walk away to spend time and money someplace else. It's all wrong I tell you!}
{135}{}{Maybe I'll talk to the sheriff, see if we can work something out?}
{136}{}{I'm sorry to hear that. I'll be going now.}
#
{137}{}{You have cleaned Mary's basement. You earn 100 exp. points.}
{138}{}{You've got Mary a permit to sell drinks. You earn 200 exp. points.}
