{100}{}{Greetings sir. ID check, your security card please.}
{101}{}{ID... What's that?}
{102}{}{I guess I don't have it.}
#what's that...
{103}{}{That's a personal security card, every member of our unit has one. You have to show me your ID card, if it
 passes the clearance check then you can go in.}
{104}{}{Sorry, I don't have one. I will be on my way then.}
{105}{}{Why didn't you just say so... Let me show you my ID.}
#
{106}{}{Alright, here you go...}
#
{107}{}{OK, everything seems to be in order. You can enter.}
{108}{}{Sorry sir, chemicals of a recreational or lethal nature are not allowed inside the base. You'll have to leave
 them if you want to go inside. You can use that locker, it's closely guarded.}
#
{109}{}{Hey, where do you think you're going!?}
{110}{}{Just looking around.}
{111}{}{Sorry, I'll be going now.}
#
{112}{}{Please, sir, this is a military facility, do your sightseeing somewhere else!}
{113}{}{I don't think so.}
{114}{}{Sorry, I'll be going now.}
#
{115}{}{Thanks.}
{116}{}{Alright, guess I'll have to trust you.}
{117}{}{Leave my stuff alone, I'll put them away somewhere else...}
#
{118}{}{You'll have to put away that weapon.}
{119}{}{Put away your weapon. Now!}
#
{120}{}{Going out, sir?}
{121}{}{Yep.}
#
{122}{}{Hey, wait... [Looking at the plasma pistol you have just stolen.] Where did you get this?}
{123}{}{The captain gave it to me...?}
{124}{}{That's a... gift, for my birthday.}
#123 or 124
{125}{}{Hmm... Wait here. [Talking over the radio.] Yes sir, I got the subject with me... [You hear some static coming
 from the speaker... suddenly he turns off the radio.] Sir, you'll have to hand over that item you have.}
{126}{}{What if I keep it!?}
{127}{}{Uh... sure, I wasn't planning to keep it.}
#
{128}{}{Your access to this base has been revoked. My orders are to escort you to the front gate and give you a
 warning. Sir, stay away from this base, or you'll be shot!}
{129}{}{[Leave.]}
#
{130}{}{Sorry sir, it's night time. Nobody can enter or exit at this hour.}
{131}{}{Alright.}
#
{132}{}{Not yet.}
#
{133}{}{Thieves are not allowed inside!}
{134}{}{Don't even think of sneaking in!}
{135}{}{Back off, traitor!}
{136}{}{Don't make me shoot you!}
#added 29.09.06, dude stole weapon plans...
{137}{}{You sir, stop right now! I have orders to search your inventory.}
{138}{}{Uh... what for?}
{139}{}{Sorry, time to go...}
