{100}{}{Good day sir.}
{101}{}{Want to buy something? Talk to Owen.}
{102}{}{Sorry, I can't help you.}
{103}{}{This place is huge. Yeah, I heard.}
{104}{}{No rest, just hard work.}
{105}{}{Do you need something from me?}
{106}{}{Do you think I'm standing here just for fun.}
{107}{}{I'm not sure what you want, who are you?}
{108}{}{Just don't try to steal something, I don't wanna use my gun.}
{109}{}{New here, right!?}
#
{110}{}{Yeah, I've heard of you.}
{111}{}{Wanna show me a few tricks?}
{112}{}{Nice talking to you, I must get back to work.}
{113}{}{Thank you stranger.}
{114}{}{Well, you're OK.}
#
{115}{}{Don't come any closer, I'll shoot you!}
{116}{}{Wasteland trash, that's what you are!}
{117}{}{So evil... I don't like it!}
{118}{}{Go bother somebody else you bastard!}
{119}{}{Get the hell away from me!}
