{100}{}{Good day. I'm Justin. With that out of the way, can I help you with something?}
{101}{}{What do you do here?}
{102}{}{Nope.}
#What do you do here...
{103}{}{As a scientist I conduct experiments on various fields of research. Most of it about robotics and cybernetics.
 Lately, I've been constructing a robot, more like an office assistant... but I encountered some difficulties...}
{104}{}{Sounds interesting, can I help in any way?}
#
{105}{}{You could but I'm not sure you're up for all this science stuff. Could be complicated. Still, if you are
 interested?}
{106}{}{Just say it.}
{107}{}{In that case, I'll leave you to your work.}
#
{108}{}{Robot design is complex and requires the use of some unconventional parts. So I started experimenting
 with biological replacements and their performance is even better than their mechanical counterparts. They are more
 aligned to our natural habitat because they don't rust, break or jam... Well, they do age, but I think that can be sorted
 out.}
{109}{}{Point being?}
#
{110}{}{There's a biological gel made especially for the purpose of preserving biological parts. This brainchild which
 dates back to the 20th century could save the day. Considering that this contribution could be invaluable to my project
 I'll probably need some. Point being, can you somehow get it for me?}
{111}{}{I can try. Know where I could find some?}
{112}{}{Is there some reward?}
{113}{}{Sounds complicated, you better hire somebody else.}
#i can try...
{114}{}{Back then it was used by the military... That reminds me, hmm... [He presses a finger against his forehead,
 looks like he's thinking really hard.] I've read something about an old medical research center from before the war. 
 That huge building in the middle of nowhere. [He points to far south.] That may be a start. Otherwise, I heard some rumors 
 about an old military base near Farmers Town. [He marks a spot on your map.] According to a traveler, they had an
 incident with poisonous gas spreading all over the place. The base was abandoned and sealed shortly after. They sure 
 took most of the equipment with them... but perhaps they left some behind...}
{115}{}{Right, what about that gas thing? Is it safe now?}
#
{116}{}{Without a proper air sealed suit? I doubt it. Although, it has been quite a while, maybe the molecules have
 dissolved into simpler compounds, forming... [He stops and a quick smile appears on his face.] Still with me?}
{117}{}{Yeah, here's one subatomic question. Where can I get the appropriate suit?}
#some reward...
{118}{}{If you are willing to get me what I need, I'm prepared to give you equipment, money... I ain't got much but
 you should be satisfied. What do you say?}
#
{119}{}{Hey, you're back. Did you find any of that biological gel I asked you for?}
{120}{}{Nothing yet.}
{121}{}{Yep, I found a can of this bio-something. Take it...}
#
{122}{}{This is great. [Looking into the jar you gave him.] Color looks good... [He puts a small tube in the jar and
 starts mixing it for a second.] Viscosity is good. I will put this on the shelf... Goes here...}
{123}{}{Yeah, about my reward...}
#
{124}{}{Ah yes... Here's $800 and some 10mm ammo for you... Also some special grenades... These are strong so be
 careful what you use them for. I'm going to test that gel you have brought. Now if you excuse me...}
{125}{}{Sure, good luck.}
#
{126}{}{Just got to put this in there...}
{127}{}{...and there should be some progress...}
{128}{}{Haha, I did it... my personal robot!}
{129}{}{Hello there... I'll call you Robo...}
{130}{}{Well, I have to program his functions now. It's gonna take some time.}
#
{131}{}{As you can see, it's going pretty well. Soon, it will be able to talk, move... And who knows what else, this is
 new even for me... All thanks to you!}
{132}{}{I'm glad it works, bye.}
#
{133}{}{You said you don't want to help, so get the hell out of my lab!}
{134}{}{Alright.}
{135}{}{Why don't you make me!?}
#answer added after line 104...
{136}{}{I'm sorry to hear that, I'll be back later.}
#
{137}{}{We meet again. Something I can help you with?}
#added after 104...
{138}{}{What's that scrap of metal you got there?}
#
{139}{}{That's my personal robot, and it's not a scrap of metal. As you can see it's not functional at the moment but I
 have faith in my work.}
{140}{}{Amen to that.}
#after 117...
{141}{}{I haven't seen one for a very long time, if you're looking for a place to search, it's definitely not around here.}
{142}{}{I'll try someplace else then.}
#
{143}{}{Is the robot not fully working, yet?}
#
{144}{}{No, I still have to run a few diagnostics, wire up some boards, program its functions... the usual.}
{145}{}{Mind if I help?}
#
{146}{}{As long as you don't break anything, be my guest.}
{147}{}{You have found bio gel for Justin. You earn 1000 exp. points.}
#
{148}{}{Hey, I've did it! A fully working AI, it can talk, think, operate. A great day for science and myself. Thanks for your help.}
#
{149}{}{I'm a bit busy at the moment.}
