{100}{}{Hey, do you work here?}
{101}{}{Of course, uh... I'm new. Why, is there a problem?}
{102}{}{No, just looking around. I'm interested in this high-tech stuff.}
{103}{}{I don't really know. Goodbye.}
#yes...
{104}{}{There's an urgent matter that can't wait any longer. Leonard doesn't understand but I need to replace that
 plasma transformer as soon as possible, we are just asking for trouble by not doing anything. You have to help me,
 everyone else thinks there's nothing to worry about but they are so wrong.}
{105}{}{What's a plasma transformer?}
{106}{}{I'm on it. Know where I could get one?}
#what's a plasma...
{107}{}{Simply, it's a part used by power generators. Ours is showing drastic efficiency drops since our transformer is
 too old to work like it used to. You get the picture?}
{108}{}{Oh, I see. Where can I find this part?}
#where can ifind...
{109}{}{Ask Leonard about the part. You just tell him it's really urgent. If the part isn't installed on time, we could
 have some serious problems.}
{110}{}{I'm off then.}
#looking around...
{111}{}{Looking around? What the hell?! Are you crazy? This is a nuclear power plant, not a town fair! Get out now...
 and don't touch anything!}
{112}{}{Alright, no need to shout.}
{113}{}{I think I like it here.}
#again...
{114}{}{If you are not working here, then stop wasting my time and get the hell out!}
{115}{}{Alright.}
{116}{}{I think I like it here.}
#Leonard don't have the part...
{117}{}{Did you get that plasma transformer I sent you for?}
{118}{}{Sorry, no luck. Leonard said we don't have any spare parts in the storage.}
{119}{}{No, I don't have it.}
#Leonard said we don't have the part...
{120}{}{Leonard said that...? Hm, I don't like this situation at all. Try looking for it someplace else and don't waste
 my time coming empty handed, got it?}
{121}{}{Right.}
#
{122}{}{You better brought me something this time.}
{123}{}{Sorry, I haven't found it yet.}
{124}{}{I got that part you need.}
#got that part...
{125}{}{Well, this looks like the real thing. Let me install it first to check its functionality, here goes nothing...}
{126}{}{OK.}
#
{127}{}{[A few moments after the part has been replaced, everything still works. Sounds better, you notice.] Nice...
 Even the sound is different, nice job. I'll run a few more tests to see how stable it is. Excuse me now...}
{128}{}{Sure thing.}
#
{129}{}{Are you stupid!? I told you not to come here again but you just don't listen, do you? I'll teach you how...}
{130}{}{Let's party!}
#
{131}{}{Leonard told me you are working on another assignment. I suggest you square things up with him and then
 you talk to me. Do I make myself clear?}
{132}{}{Sure thing.}
#
{133}{}{I'm too busy right now. About that part, I've never seen it working better. All thanks to you.}
{134}{}{I'm glad to hear that. So long.}
