{100}{}{Yep, do you want something?}
{101}{}{What is this place?}
{102}{}{Who are you?}
{103}{}{No, just passing by.}
#place...
{104}{}{This is my car workshop. I can fix anything on a car and make it run just like it was brand new. Well, I think I
 do... since I haven't seen any working cars for years, I haven't had a chance to check if I'm still in shape.
 Anyway, if you need any of my services I might give you a discount, just keep that in mind.}
{105}{}{OK, let me ask you something.}
{106}{}{Thanks, I'll remember that.}
#you...
{107}{}{Nick is my name and I'm the local mechanic. Back in the day, people used to come here and ask me to fix
 almost every possible problem on a car you could think of. To say the truth, that was a long time ago. I haven't had
 any customer for years but I never lost hope. You never know when you are gonna hear a loud klaxon in your back
 yard! Know what I mean? [Laughs.]}
{108}{}{Yeah... sure.}
{109}{}{OK, let me ask you something.}
{110}{}{That's a nice story but I have to be on my way.}
#yeah sure...
{111}{}{I'm so convinced that people are going to start coming anytime soon... I'd better be prepared. Damn, I need a
 lot of car parts but I hardly know where to find them...}
{112}{}{Can I help?}
{113}{}{Sorry to hear that.}
{114}{}{Thanks for your time. I'm off then.}
#help...
{115}{}{I don't know... Wait, there's something I need. You can see I already got plenty of tires here, but most of these
 are worn out or damaged beyond repair. I just want to be sure I don't have to tell my customers that we're out of tires...
 can you imagine. That could be bad for business. So you need to find me some, I prefer 'em with profile. Ten pieces
 will be enough to fill up some empty shelves I have, and we'll talk about your payment when you find something. It's a
 deal?}
{116}{}{You got it.}
{117}{}{I'll be back when I'm ready to take the job.}
#sorry to hear...
{118}{}{No need to be. I still have a few stacks left, so I'll hire somebody to find more if I run low on supplies.}
{119}{}{Thanks for your time. I'm off then.}
#you got it...
{120}{}{Good. I suggest that you go to Farmers Town, they have an old gas station. I don't know who runs the place
 now, if it's run at all. Either way, you should start your search there.}
{121}{}{OK, I'm off then.}
#
{122}{}{I see you have some tires. Want to sell those to me?}
{123}{}{They are all yours.}
{124}{}{I think I'll be keeping them.}
#all yours...
{125}{}{Alright. I'll take ten... Here's your money, $1000 for you.}
{126}{}{Thanks.}
#anything else...
{127}{}{What's on your mind?}
#again...
{128}{}{Back again stranger. Do you need something?}
#
{129}{}{About that job...}
#
{130}{}{Well, I see you have some decent looking tires but I told you I'm paying for ten, no less.}
{131}{}{Right, I'll find more.}
#
{132}{}{So, want to find some tires for me, about a stack of ten?}
{133}{}{Alright.}
{134}{}{Not yet.}
#
{135}{}{Well, I don't see you carrying any tires... So, what are you doing here then?}
{136}{}{Sorry, I'm going.}
#
{137}{}{Nothing, I'm going.}
#another job..
{138}{}{Come to think of it, I'll need some tools for my workshop, can't get enough of them. [Smiles.] Are you
 interested in another job?}
{139}{}{Sure, what do you need?}
{140}{}{Maybe later.}
#
{141}{}{About that job...}
#
{142}{}{Like I said. I got some old tools here but they are either broken or rusty and there's an old saying, you'll
 never repair one junk with another. So those must go. I'll need one screwdriver and an adjustable wrench to be
 able to continue my garage. Can you get me those?}
{143}{}{Sure thing.}
{144}{}{Maybe. Do I get something for this?}
{145}{}{I got something to do first, but I'll be back.}
#do i get...
{146}{}{Well, I have plenty of nuts and bolts. [Chuckles.] But I figured some money would be of better use.
 Only one condition though, bring me something useful.}
{147}{}{It's a deal, I'm off then.}
#job taken...
{148}{}{I told you. I need a working screwdriver and an adjustable wrench. Bring me those and then we'll talk.}
{149}{}{I'm on it.}
#dude brought...
{150}{}{Let me see... [Looking at the tools you brought]. They'll do just fine, thanks. Here's $1000 for them. Now I
 can finally do something useful here...}
{151}{}{Thanks, I'll leave you to your work.}
#
{152}{}{Got any work for me?}
