{100}{}{Wrong place, pal!}
{101}{}{I'm watching you so don't try to sneak!}
{102}{}{We don't have anything you need.}
{103}{}{I don't like strangers, they always cause trouble.}
{104}{}{This ain't a public library.}
{105}{}{You go back the way you came.}
{106}{}{We only deal with professionals.}
#
{107}{}{No, I don't like bad people.}
{108}{}{We don't deal with murderers.}
{109}{}{This is no place for you, outlaw!}
{110}{}{The killing of the innocent is not in my job description!}
{111}{}{You got some serious problems, murderer scum!}
