{100}{}{Hi there, stranger. Don't worry, we were just checking the site. Looks intact... [Tapping the ground.] You can
 return to whatever you were doing. I have to get back to my work now... [Takes his shovel.]}
{101}{}{I was just walking around, getting some fresh air...}
{102}{}{Sure, carry on. [Leave.]}
#
{103}{}{Hey, don't you think it's a little late for talking a walk?}
{104}{}{Nope, I'm doing just fine. Say, saw anything unusual around here?}
{105}{}{What do you need a shovel for?}
#doing fine...
{106}{}{That's dandy, but you'll have to do it somewhere else. You are disturbing us!}
{107}{}{It wasn't my intention... I'm just wondering, what do you use the shovel for?}
#showel for...
{108}{}{Why don't you come closer and take a look... I've got something... Right here... [Reaches for something under
 his robe.]}
{109}{}{That's it! You're going down, thieving scum!}
#
{110}{}{You again... Don't you think it's a little late to walk about!?}
{111}{}{That grave looks pretty empty to me. You're not telling me the whole story...}
