{100}{}{Hey, stranger. How can I help you?}
{101}{}{What is this place?}
{102}{}{I was told I could buy some slaves here.}
{103}{}{Sorry, I was just going.}
#this place...
{104}{}{This is our management office. We buy and sell stuff, almost everything money can afford. Let me assure you
 first, that our quality speaks for itself and that the variety of our stock gets bigger every day. By the way, I'm
 Pete, and I hope you'll be satisfied with our offer. Any questions?}
{105}{}{Where do you keep all that stuff?}
{106}{}{So, what kind of stuff do you sell?}
{107}{}{Thanks, see you later.}
#some slaves...
{108}{}{Sure, we prefer menial laborer... but we got it. If you're looking to buy some, I'll have to check your "bank
 account" [smiles]. Just to be sure you're not here to waste my time by looking around and buying nothing. You're fine
 with that?}
{109}{}{Alright...}
{110}{}{I think I'll pass.}
#all right...dude money > 5000
{111}{}{Everything seems to be in order, that means we can talk about business. Interested?}
{112}{}{Of course, that's why I'm here.}
{113}{}{Not right now, let me ask you something.}
#dude money < 5000
{114}{}{[He doesn't look happy.] It looks like you have insufficient funds to do any business here. I suggest you
 get your "account" refilled if you want to buy any of our fine labor force. I sell quality, and it costs! Have a nice
 day.}
{115}{}{Damn... I'll get more money.}
#where...
{116}{}{What you see here is just a small part for display purposes. Most of our stuff is stored in the underground
 warehouse, where it's kept safe and preserved. Originally, there was an old pre-war vault beneath this area. We
 transformed it into a big storage facility. You might want to check it out if you're one of those "picky" customers.}
{117}{}{Interesting, let me ask you something else.}
#what kind of stuff...
{118}{}{Almost everything. If you need firearms, we got rifles, small arms, all kinds of military stuff... Then, there are
 various medical items which you won't find anywhere else in the wasteland. We got some fine armors and high-tech
 equipment...}
{119}{}{Got any slaves for sale?}
{120}{}{Alright, I'm interested.}
{121}{}{Can I ask you something?}
#interested in items...
{122}{}{Before we proceed I'll have to check your "bank account". [He smiles.] Just to be sure you're not here to waste
 my time by looking around and buying nothing. If you're fine with that?}
{123}{}{Alright...}
{124}{}{I think I'll pass.}
#money ok...
{125}{}{We don't directly sell anything here, for safety reasons. So you take the path to the west, just outside this
 building. Our storage area is on the other side of the fence. My guard will open the front gate for you.}
{126}{}{Thanks.}
#
{127}{}{You're back. What can I do for you?}
#
{128}{}{If you're interested in trading, you are free to visit the storage area.}
#
{129}{}{Sure, what can I do for you?}
#
{130}{}{Guards! Stop this thief! I'll take back what's mine from your cold corpse.}
