{100}{}{There's nothing to see here.}
{101}{}{Move along.}
{102}{}{Talk to the manager if you want to buy something.}
{103}{}{The manager's the one in charge here.}
{104}{}{I'm not the one you should be talking to.}
{105}{}{I'm sure you'll find all you need here.}
{106}{}{I don't sell anything, talk to the manager.}
#
{107}{}{Hey you, stop right there!}
#
{108}{}{Put your weapon away!}
{109}{}{You better put your weapon away!}
{110}{}{No weapons here!}
