{100}{}{Yes? What do you want?}
{101}{}{Who are you?}
{102}{}{What is this place?}
{103}{}{Nothing.}
#who are you...
{104}{}{I'm Roy, the technician. I'm taking care of this old piece of junk. At least it's working, which means I'm doing
 something right. These machines are very old and each of them has a story of its own, nothing good though.}
{105}{}{What do you mean?}
{106}{}{So, you work for Pete?}
{107}{}{Well, I have to be going now.}
#this place...
{108}{}{Originally, this place was used as a shelter during the war. There were many underground vaults like this one.
 We changed most of the interior here... Did I mention this place was in ruins before we came? [Laughs.] I found a lot
 of data about this place in the computers, ordinary stuff. But...}
{109}{}{What?}
#
{110}{}{Some reports stored in the computer suggest that many of the vault inhabitants were exposed to various
 toxins. Apparently, they wanted to make some biochemical weapon... Many lives were lost before they figured the
 mess they'd made in the process. There were other experiments used to increase human endurance, they failed as
 well... Instead, they created mutated abominations...}
{111}{}{So, what happened?}
#
{112}{}{These mutants were tough and quite stupid, but smart enough to turn against their creators, normal humans.
 So the war went on for decades... There is not much else about it, I guess we won. [He shrugs.]}
{113}{}{That's a good story, thanks Roy.}
#work for pete...
{114}{}{Well, I was hired because of my skills... Never wanted to have anything to do with this type of
 "business". I still have the same opinion, but I stayed because I learned a lot about technical stuff and I feel this is what
 I always wanted.}
{115}{}{Alright, tell me something else.}
{116}{}{Thanks for your time.}
#
{117}{}{What do you want to know?}
#
{118}{}{I don't like what you did!}
{119}{}{Pete is going to be very angry with you!}
{120}{}{Get away from me!}
{121}{}{That was very stupid of you!}
