{100}{}{[Looks at you for a moment with a smile on his face.] Well, well, well... Look what we have here. So,
 you're the one who caused such a mess with your war against slavery... I'm not impressed really, something else has
 caught my attention... Your... determination to help those bastards from the wasteland prison... You really think you're
 doing the right thing?}
{101}{}{What are you talking about?}
{102}{}{Who the hell are you?}
#talking about... 101 and 124
{103}{}{Do you ever try to listen...? Look, you're alive just because they want you to be. Serving as an informer in the
 outside world proved a much better choice for them because you don't know shit and only do what you've been told.
 They are using you for their plans, whatever they are... But once you're not needed anymore, you will disappear, like
 many others before you...}
{104}{}{Why should I trust you?}
{105}{}{No, I don't believe you. Can you prove it?}
#trust... 104 and 105
{106}{}{That's a good question. Why do you think they let you go after they tortured you? Left you to die... What was
 your last memory, your last thought before you got there?}
{107}{}{Uh, I can't remember... How do you know all this?}
#know all this...
{108}{}{Just like you, I endured the same treatment... Dark chambers, torture, trials... But I always knew something
 wasn't right with their story. After a few months spent there, I devised a plan to escape. Eventually, after weeks of
 planning I finally saw my chance. A few inmates joined me and we broke free into the wasteland...}
{109}{}{So, what happened then?}
#
{110}{}{We were chased by mercenary groups, bounty hunters, you name it... But we managed to keep a low profile.
 Unexpectedly, my suspicions about the wasteland prison were confirmed after I met the person who knew all about
 me... My life before I was accused of murder and taken away...}
{111}{}{Did you know that person?}
#
{112}{}{Maybe, I don't know... I just couldn't live like that, everything seemed strange, people looking at me... So I
 decided to leave all that behind and continue my work, to unravel the truth behind the curtain. But one thing stands in
 front of others...}
{113}{}{What's that?}
#
{114}{}{The fact is, however absurd this may sound, they erased your memory! Sometimes, I have the same feeling
 that something is missing in there. [Scratching his forehead.] Anyway, there's nothing we can do while arguing here, so
 you'd better listen to me and start accepting the truth!}
{115}{}{Damn it! I don't feel any better by knowing this!}
{116}{}{Well, you're right. Something "is" missing in there. I can recognize a bonehead when I see one!}
#knowing this...
{117}{}{Believe me, you'll get used to it. The truth is painful but the sooner we accept it, the sooner we can go on with
 our lives. You know... this situation... we could both benefit from it. With my help, you can find out what happened to
 you if that's what you want.}
{118}{}{Yeah, I guess... What do you get from all this?}
#
{119}{}{I want to pay a visit to my old "friend". But we'll talk about it later. I suppose you want your stuff back, it's
 in the locker to my right. Follow me...}
{120}{}{Sure...}
#bonehead...
{121}{}{Oh, don't make me laugh... [Talking to his man.] Are you sure this is the right guy...? I don't think so. This is
 one stupid motherfucker... Kill the son of a bitch!}
{122}{}{Whoa...!}
#who the hell are you...
{123}{}{Let's just say, I had the same misfortune and it's been haunting me ever since...}
{124}{}{Since when...? What are you talking about?}
#
{125}{}{You'll get your stuff, don't worry.}
{126}{}{Can you wait for a second!?}
#
{127}{}{Alright, talk to you in a minute.}
#
{128}{}{I'm sorry, but I have to kill you now!}
#
{129}{}{Well, I must say I'm glad you agreed to help us. Believe me, this might be the only chance we have. We need
 to be sure if we're about to do this, let me know when you are ready.}
{130}{}{Alright, what's the plan?}
{131}{}{Sure, I'll get back to you.}
#the plan...
{132}{}{Since we don't have enough information about the prison security system, we need you to go there and find
 anything useful that could help us get past it without alerting the whole place.}
{133}{}{So, why do you need me in the first place?}
{134}{}{What if we are wrong about the whole thing?}
#need me...
{135}{}{Because YOU are not the one they are looking for. But most of all you were there, you've seen things, don't
 tell me you feel nothing about what they have done to you... what they have taken from you. Going back might be hard
 I know, but think about what you will earn from this... Answers about who you really are.}
{136}{}{Well, that's the only reason I'm doing this. I'll be back when I have something useful.}
{137}{}{I know who I am... And my mission is to take you back where you belong whether you like it or not!}
#wrong about the whole thing...
{138}{}{Then we wouldn't be here having this conversation. Look, if you don't understand it's in our best interest to
 help each other then our talk is done. Furthermore, I think you are trying to slow us down! Let me tell you something...
 [Turns to his men.] Get rid of this scumbag, he's useless!}
{139}{}{Come on, I was trying to talk you out of it in a peaceful way.}
#come back with the information...
{140}{}{Anything useful about the prison, any way to get in?}
{141}{}{It looks like the west wall is less guarded so it could be easy to cross over it with some ropes.}
{142}{}{No, nothing yet.}
#
{143}{}{Sounds like a good idea but how are we going to disable the security system?}
{144}{}{I'm not entirely sure... We could cut off the power supply by disabling the generator.}
{145}{}{I have stolen the security codes from the gate guard. I think that's all we need.}
{146}{}{Well, I haven't figured it out yet.}
#disable generator...
{147}{}{That doesn't seem like a good idea, what if they have a backup system? Or something goes wrong and the
 alarm sounds? You have to come up with something better because I would rather take my chances with something that
 CAN work than just MIGHT and hope for the best.}
{148}{}{Alright. I'll keep searching.}
#security code...
{149}{}{Well, this could be useful. And... you know what those codes are for, right?}
{150}{}{Uh, I didn't actually try to use them but I think they can be used to disable the front laser gate and... stuff...}
{151}{}{I have no idea. I'll be back when I find out more.}
#i didn't use them...
{152}{}{We appreciate your effort but this is, of little to no use... No way I'm going to rely on that piece of paper.
 What if they find out the codes are missing and change them by the time we get there? We could be in big trouble then.
 I think you have to find another way... Because, this one has little to no chance of success.}
{153}{}{Fine, I'll keep looking.}
#
{154}{}{There's a better way to get in...}
#
{155}{}{Alright, let's hear about it.}
{156}{}{I will need your help to convince the guard that you are my prisoner and while doing that your men can use
 the rope to climb over the west wall.}
{157}{}{I can talk my way in and keep the guard busy. You guys will have enough time to get inside before he realizes
 something's wrong.}
{158}{}{The gate could be disabled with an explosive charge. That would give us enough time to get in.}
{159}{}{I can take out the gate guard and disable the force field. Then I'll give you the signal when it's clear.}
{160}{}{Actually, I had something else on my mind. I'll see you later.}
#need help... answer to 156
{161}{}{And take out the generator. Hmm... Interesting. Tell you what... This one sounds good, at least from what I've
 heard so far. I'm not definitively sure this is it but we can't wait any longer. I'll tell my men to start their preparations.
 We have a long walk ahead of us, better bring something to read. [Smiles.]}
{162}{}{Yeah, sure, like I always do.}
#answer to 158,159...
{163}{}{No, you got it all wrong! Our plan is to disable the security system before we do anything so they won't be
 able to alert the whole base! We are lacking in manpower and equipment... I'm counting on you but we don't have
 much time. And you better bring me something good next time because this is starting to piss me off.}
{164}{}{Sure thing.}
{165}{}{And here I was thinking YOU had asked for MY help. Go to hell!}
#answer to 157...
{166}{}{Why do you think he's going to believe you anything? Even I have a hard time listening to this nonsense. It's
 not going to work... What if he sees us, huh? Are YOU going to convince him not to raise the alarm? So, this one is
 definitively out of the question.}
{167}{}{Guess I'll have to come up with something else.}
#
{168}{}{Nice to see you!}
{169}{}{How are you?}
{170}{}{Still traveling?}
{171}{}{How's life?}
#player got car, going out for the first time
{172}{}{Your vehicle is parked outside, good luck!}