{100}{}{Hey, I don't know you... You better not be here to bother old Greg... 'cause if you are...}
{101}{}{I just wanted to ask you something. What is this place?}
{102}{}{Not at all, sir. Old Ron from Philton asked me to bring you these...}
{103}{}{Sorry, I'm just passing by.}
#place...
{104}{}{This was the old storage unit. But it was too small to meet their daily demands. So Larry moved
 his stuff to a bigger place and let me use this as my workshop, and you know the rest... Something else you wanted?}
{105}{}{No, that's all.}
#all...
{106}{}{What? I can't hear you... Ah forget it, I'm just kidding with you. But now beat it, I'm working here, kid.}
{107}{}{Alright then.}
#
{108}{}{Hah, the old bastard... He can't do anything by himself. Hey, nice ore you got there. So, you want me to do
 something with these or what?}
{109}{}{Can you use them to make... something?}
{110}{}{I don't know... Ron told me you know what to do?}
{111}{}{Perhaps you could start making some barrels now, please...}
{112}{}{Don't ask me, you are the one who works here.}
{113}{}{Ah, the old folks... know nothing, forget everything.}
{114}{}{They could use some good cleaning, if you know what I mean.}
#109,110,112...
{115}{}{Unless you are giving these for free, I really don't know what you want me to do with 'em. Tell you what... I'll
 just put these on the shelf here and you let me know when you make up your mind. [He takes the ore and starts walking
 towards the shelves.]}
{116}{}{Wait, damn it! Make me some barrels, OK?}
{117}{}{Fine, take the damn stuff, I don't need it.}
{118}{}{Hey that's mine, give it back!}
#116,111...
{119}{}{I guess... [He starts counting with his fingers, constantly mumbling for about a minute.] I can do that. How
 many do you need?}
{120}{}{As many as you can make.}
{121}{}{Oh, for God's sake! I don't care, just make me something.}
# 120,121,117...
{122}{}{Alright, [chuckles] I'll take it from here... And, this could take a while, why don't you come back tomorrow...
 [Scratching his head.] No, wait... Better make it two days, yes... Oh, damn... [He opens his eyes wide like he just
 remembered something.]}
{123}{}{What?}
#123...
{124}{}{Oh, nothing. I just have so much work to do... I guess I'll be seeing you in three days.}
{125}{}{You just said two... Oh, nevermind.}
#113,114...
{126}{}{Hey, I'm old but I'm not stupid! And I can sure hear what you're saying you little piece o’ shit! The deal is off,
 grab your crap and get out!}
{127}{}{OK, grandpa... [Leave.]}
#back in less than 3 days...
{128}{}{You look familiar, I have seen you before, right?}
{129}{}{Sure, I asked you to make some barrels for old Ron...}
{130}{}{Whatever, I'm out of here.}
#for old Ron... finished
{131}{}{Ron, eh? Yeah, I got it... Hmm... [Turns around looking for something.] Where did I put those...? Ah, there
 they are. Here you go, don't drop them. And say hello to Ron for me.}
{132}{}{Alright, thanks.}
#for old Ron... not finished
{133}{}{You're a bit early... I'm not done yet, come back later.}
{134}{}{Sure.}
#
{135}{}{Get out!}
