{100}{}{Please don't hurt me!}
{101}{}{Are you my new master?}
{102}{}{Please set me free.}
{103}{}{I really want to be free.}
{104}{}{Run away!!}
{105}{}{Oh, God, please, why?}
{106}{}{Why do you hate us?}
#
{107}{}{Thank you, friend.}
{108}{}{Where do we go now?}
{109}{}{I hope we gonna make it. We're in the middle of nowhere.}
{110}{}{You saved us from a bad fate, we'll find our way home.}
#
{111}{}{They look tired and scared.}
