#description gangs
{100}{}{You see: a gang member.}
{101}{}{A tough looking man. He is guarding whatever is inside.}
#float messages
{102}{}{Hey you, punk. What are you doing here? This is no place to be wandering around.}
{103}{}{I'm on duty.}
{104}{}{No time to talk.}
#combat lines
{105}{}{You're one dumb son of a bitch.}
{106}{}{We're gonna chew you up, and spit you back to Miners!}
{107}{}{McKarty's gonna pay for this.}
{108}{}{Intruder!}
{109}{}{Base... We got an intruder, over. *Chchh...* Post one... Kill him!}
