{100}{}{Hi there. Hey, could you buy me a Nuka-Cola, I really don't have the money to pay for it but I can tell you one
 good story instead.}
#
{101}{}{Well, OK.}
{102}{}{Sorry, don't have time for this.}
#dude nije uzeo pice ali se vraca
{103}{}{Hey, you're back, you can still buy me that drink if you want...}
#
{104}{}{Here you go. Enjoy.}
{105}{}{Just saying hello.}
#
{106}{}{[He drinks.] Ah, man, this is good, thanks. I owe you that story, wanna hear it?}
{107}{}{Please.}
{108}{}{Not interested.}
#
{109}{}{A few years ago, while I was working on the fields, I found a map. When I first saw it, it looked just like some
 very old piece of paper. Later, after spending some time analyzing it, I discovered it was actually a map of some
 installation not far from here.}
#
{110}{}{Really? Where is it?}
#
{111}{}{I can just about show you on the map here, but I have never been able to find the place. The map has some
 military markings on it, so it could be the layout of some pre-war military base. Hey! If you happen to find anything
 just let me know. Okay?}
#
{112}{}{I will, thanks for the story.}
{113}{}{Well looks like I got to hit the road, so long.}
#
{114}{}{I don't have money at the moment. I'll be back.}
#
{115}{}{I hope you find what you're looking for.}
{116}{}{Thanks for that drink.}
{117}{}{Good luck, you'll need it.}
{118}{}{Good day, friend.}
{119}{}{Want to buy me some more...? Hehe.}
#
{120}{}{Good day, friend.}
{121}{}{Want to hear a story?}
{122}{}{Got any drinks, friend?}
{123}{}{Yep.}
{124}{}{What do you want?}
{125}{}{Good day, traveler.}
#
{126}{}{}
