##########################################################
#
# DESCRIPTIONS OF QUESTS IN PIP-BOY
# (start each new section with 100 and multiples of it)
#
##########################################################

#---------------------------------------------------------
# Villa
#---------------------------------------------------------

### {100}{}{Learn about the raiders in the neighboring city}
{100}{}{了解邻近城市的袭击者 -- Learn about the raiders in the neighboring city}
### {101}{}{Free your fellow tribesmen in Flagstaff}
{101}{}{解放你在弗拉格斯塔夫的部落同胞 -- Free your fellow tribesmen in Flagstaff}
### {102}{}{Free your fellow tribesmen in Two-Sun}
{102}{}{在两个太阳里解放你的部落同胞 -- Free your fellow tribesmen in Two-Sun}
### {103}{}{To address the Community Council}
{103}{}{向社区议会致辞 -- To address the Community Council}
### {104}{}{Find family heirlooms in the cellars}
{104}{}{在地窖里寻找传家宝 -- Find family heirlooms in the cellars}
### {105}{}{One of the residents needs medical help}
{105}{}{其中一位居民需要医疗帮助 -- One of the residents needs medical help}
### {106}{}{Stop the invasion of rats}
{106}{}{阻止老鼠的入侵 -- Stop the invasion of rats}
### {107}{}{Find and return the runaway child}
{107}{}{找到并归还逃跑的孩子 -- Find and return the runaway child}
### {108}{}{Drive the looters from the plantations}
{108}{}{把抢劫者赶出种植园 -- Drive the looters from the plantations}
### {109}{}{Fix the weather station}
{109}{}{修理气象站 -- Fix the weather station}
### {110}{}{Eliminate the sect in Phoenix}
{110}{}{消灭凤凰城门派 -- Eliminate the sect in Phoenix}
### {111}{}{Find Chris, he's probably hiding somewhere}
{111}{}{找到克里斯，他可能藏在什么地方 -- Find Chris, he's probably hiding somewhere}
### {112}{}{The council decided to undermine the Flagstaff mines}
{112}{}{委员会决定破坏弗拉格斯塔夫煤矿 -- The council decided to undermine the Flagstaff mines}
### {113}{}{The council decided to destroy the machine in Garage City}
{113}{}{市政委员会决定摧毁车库城的机器 -- The council decided to destroy the machine in Garage City}
### {114}{}{The Council believes that Villa needs allies}
{114}{}{安理会认为维拉需要盟友 -- The Council believes that Villa needs allies}

#---------------------------------------------------------
# Flagstaff
#---------------------------------------------------------

### {200}{}{Find Villa people in the Prisoner pen}
{200}{}{在囚犯围栏里寻找维拉人 -- Find Villa people in the Prisoner pen}
### {201}{}{In any way to release the tribesmen from prison}
{201}{}{以任何方式将部落成员从监狱中释放 -- In any way to release the tribesmen from prison}
### {202}{}{Rescue the tribesmen from the trap in the mine}
{202}{}{把部落成员从矿井里的陷阱里救出来 -- Rescue the tribesmen from the trap in the mine}
### {203}{}{Repair the drilling robot}
{203}{}{维修钻孔机器人 -- Repair the drilling robot}
### {204}{}{Eliminate the rat king in the mine}
{204}{}{消灭矿井里的老鼠王 -- Eliminate the rat king in the mine}
### {205}{}{Someone attacks patrols in an abandoned area}
{205}{}{有人袭击了一个废弃地区的巡逻队 -- Someone attacks patrols in an abandoned area}
### {206}{}{Take lunch to the mine administrator}
{206}{}{给矿长吃午饭 -- Take lunch to the mine administrator}
### {207}{}{Mercenary Davis owed the bar a hundred caps}
{207}{}{雇佣兵戴维斯欠酒吧一百顶帽子 -- Mercenary Davis owed the bar a hundred caps}
### {208}{}{Eliminate the infidel in the name of the Sacred Fire}
{208}{}{以圣火之名消灭异教徒 -- Eliminate the infidel in the name of the Sacred Fire}
### {209}{}{Cure a child of radiation sickness}
{209}{}{治好孩子的辐射病 -- Cure a child of radiation sickness}
### {210}{}{Drive the invaders from Randy's farm}
{210}{}{把入侵者赶出Randy的农场 -- Drive the invaders from Randy's farm}
### {211}{}{Find Miss Brandley's personal belongings}
{211}{}{找到布兰德利小姐的私人物品 -- Find Miss Brandley's personal belongings}
### {212}{}{To remove the supervisor of the Whip from his position}
{212}{}{罢免党鞭的上司 -- To remove the supervisor of the Whip from his position}
### {213}{}{Check out what's going on at Camp Winon}
{213}{}{查看Winon营地的情况 -- Check out what's going on at Camp Winon}

#---------------------------------------------------------
# Garage- City
#---------------------------------------------------------

### {300}{}{Stop the scavengers in the dorm}
{300}{}{阻止宿舍里的拾荒者 -- Stop the scavengers in the dorm}
### {301}{}{Get Mr. Kogan the parts from the factory}
{301}{}{把工厂的零件给Kogan先生 -- Get Mr. Kogan the parts from the factory}
### {302}{}{Participate in a deal with a caravan}
{302}{}{参与与商队的交易 -- Participate in a deal with a caravan}
### {303}{}{Lucas needs data from the computer in the garage}
{303}{}{Lucas需要车库里电脑的数据 -- Lucas needs data from the computer in the garage}
### {304}{}{Participate in a deal with a caravan}
{304}{}{参与与商队的交易 -- Participate in a deal with a caravan}
### {305}{}{Participate in the capture of a Brahmin}
{305}{}{参与捕捉婆罗门 -- Participate in the capture of a Brahmin}
### {306}{}{Restore the trade route to San Brahmin}
{306}{}{恢复通往圣婆罗门的贸易路线 -- Restore the trade route to San Brahmin}
### {307}{}{Organize a trade route to the Ranger lands}
{307}{}{组织一条通往游骑兵领地的贸易路线 -- Organize a trade route to the Ranger lands}
### {308}{}{Organize the supply of alcohol from Flagstaff}
{308}{}{组织Flagstaff的酒精供应 -- Organize the supply of alcohol from Flagstaff}
### {309}{}{Stop fake tire production}
{309}{}{停止生产假轮胎 -- Stop fake tire production}
### {310}{}{Find and return the welding machine}
{310}{}{找到并归还焊机 -- Find and return the welding machine}

#---------------------------------------------------------
# San- Brahmin
#---------------------------------------------------------

### {400}{}{To help the leader in the conclusion of an alliance}
{400}{}{帮助首领缔结联盟 -- To help the leader in the conclusion of an alliance}
### {401}{}{Missionaries offer the tribe a union}
{401}{}{传教士为部落建立联盟 -- Missionaries offer the tribe a union}
### {402}{}{Help the ranger drive away the missionaries}
{402}{}{帮助护林员赶走传教士 -- Help the ranger drive away the missionaries}
### {403}{}{Stop tequila production in Phoenix}
{403}{}{停止在凤凰城生产龙舌兰酒 -- Stop tequila production in Phoenix}
### {404}{}{Clear the paddock of brahmin excrement}
{404}{}{清除围场里的婆罗门排泄物 -- Clear the paddock of brahmin excrement}
### {405}{}{Uncover the mystery of the Buried City}
{405}{}{揭开被掩埋的城市之谜 -- Uncover the mystery of the Buried City}
### {406}{}{Clear the oasis of radscorpions}
{406}{}{清除雷达蝎子的绿洲 -- Clear the oasis of radscorpions}
### {407}{}{Protect the caravan on the way to Phoenix}
{407}{}{保护前往凤凰城的商队 -- Protect the caravan on the way to Phoenix}
### {408}{}{}
{408}{}{error : string is empty -- }
### {409}{}{}
{409}{}{error : string is empty -- }

#---------------------------------------------------------
# Tu- San
#---------------------------------------------------------

### {500}{}{Find a way to disable the force barrier}
{500}{}{找到禁用力屏障的方法 -- Find a way to disable the force barrier}
### {501}{}{Find your Padre in the Restricted Area}
{501}{}{在禁区内找到你的牧师 -- Find your Padre in the Restricted Area}
### {502}{}{Get the Villa people out of the Restricted Area}
{502}{}{让维拉的人离开禁区 -- Get the Villa people out of the Restricted Area}
### {503}{}{The padre asks to convince Carlos (and in case of failure - to eliminate)}
{503}{}{牧师要求说服卡洛斯（如果失败，则取消） -- The padre asks to convince Carlos (and in case of failure - to eliminate)}
### {504}{}{The Tinkerers want to deactivate the security of the Restricted Area}
{504}{}{Tinkerers想要解除限制区域的安全 -- The Tinkerers want to deactivate the security of the Restricted Area}
### {505}{}{Find out who attacked the caravan and stop this threat}
{505}{}{找出谁袭击了商队并阻止这种威胁 -- Find out who attacked the caravan and stop this threat}
### {506}{}{Find the missing tinker in Casa Grande}
{506}{}{在格兰德之家找到失踪的修补匠 -- Find the missing tinker in Casa Grande}
### {507}{}{Cody experiences a personality conflict and asks to find his family in Casa Grande}
{507}{}{Cody经历了性格冲突，要求在Casa Grande找到家人 -- Cody experiences a personality conflict and asks to find his family in Casa Grande}
### {508}{}{Get an energy cell for a peasant}
{508}{}{给农民买一个能量电池 -- Get an energy cell for a peasant}
### {509}{}{}
{509}{}{error : string is empty -- }

#---------------------------------------------------------
# Puerto-Penasco
#---------------------------------------------------------

### {600}{}{Take Ulysses Grant's holodisk to Puerto Penasco}
{600}{}{带尤利西斯·格兰特的全息盘去佩纳斯科港 -- Take Ulysses Grant's holodisk to Puerto Penasco}
### {601}{}{Find the missing Brotherhood Squad in Inferno}
{601}{}{在地狱寻找失踪的兄弟会小队 -- Find the missing Brotherhood Squad in Inferno}
### {602}{}{Paladin Bell suffers from a mental disorder}
{602}{}{圣骑士贝尔患有精神障碍 -- Paladin Bell suffers from a mental disorder}
### {603}{}{Conduct reconnaissance in the south}
{603}{}{在南方进行侦察 -- Conduct reconnaissance in the south}
### {604}{}{Eliminate the Rangers}
{604}{}{消灭游骑兵队 -- Eliminate the Rangers}
### {605}{}{Participate in raids on bandit camps}
{605}{}{参与对土匪营地的突袭 -- Participate in raids on bandit camps}
### {606}{}{Conduct a reconnaissance in San Felipe}
{606}{}{在圣菲利佩进行侦察 -- Conduct a reconnaissance in San Felipe}
### {607}{}{}
{607}{}{error : string is empty -- }
### {608}{}{}
{608}{}{error : string is empty -- }
### {609}{}{}
{609}{}{error : string is empty -- }

#---------------------------------------------------------
# Rangers
#---------------------------------------------------------

### {700}{}{Fix the water tank on the farm}
{700}{}{把水箱固定在农场上 -- Fix the water tank on the farm}
### {701}{}{Spy needs Ranger radio code}
{701}{}{间谍需要游侠无线电代码 -- Spy needs Ranger radio code}
### {702}{}{Repair the equipment at the power plant}
{702}{}{修理发电厂的设备 -- Repair the equipment at the power plant}
### {703}{}{Escort a young mechanic from Garage City to serve at the power plant}
{703}{}{护送一名年轻的机修工从车库城到发电厂工作 -- Escort a young mechanic from Garage City to serve at the power plant}
### {704}{}{Expand the broadcast area of the radio station}
{704}{}{扩大广播电台的广播区域 -- Expand the broadcast area of the radio station}
### {705}{}{Take the report to the ranger in San Brahmin}
{705}{}{把报告交给圣婆罗门的护林员 -- Take the report to the ranger in San Brahmin}
### {706}{}{Escort a rogue family to the ferry}
{706}{}{护送一个流氓家庭到渡口 -- Escort a rogue family to the ferry}
### {707}{}{Find the missing reconnaissance squad in the desert in the north}
{707}{}{在北部沙漠中找到失踪的侦察队 -- Find the missing reconnaissance squad in the desert in the north}
### {708}{}{Find out what happened to the residents of Quartz}
{708}{}{了解Quartz居民的遭遇 -- Find out what happened to the residents of Quartz}
### {709}{}{Collect cartographic data in Quartz}
{709}{}{在Quartz收集地图数据 -- Collect cartographic data in Quartz}
### {710}{}{Find out in Garage City what happened to the refugees}
{710}{}{在车库城了解难民的遭遇 -- Find out in Garage City what happened to the refugees}
### {711}{}{Help Cadet Presley}
{711}{}{帮助学员Presley -- Help Cadet Presley}
### {712}{}{Find out the cause of the epidemic in the Aqueduct}
{712}{}{找出渡槽疫情的原因 -- Find out the cause of the epidemic in the Aqueduct}
### {713}{}{Find and kill the legendary Radscorpion}
{713}{}{找到并杀死传说中的Radscorpion -- Find and kill the legendary Radscorpion}
### {714}{}{Find the missing gear}
{714}{}{找到丢失的齿轮 -- Find the missing gear}
### {715}{}{Assist the rebels in Phoenix}
{715}{}{协助凤凰城的叛军 -- Assist the rebels in Phoenix}
### {716}{}{Find the missing Aqueduct residents}
{716}{}{寻找失踪的渡槽居民 -- Find the missing Aqueduct residents}
### {717}{}{Conduct reconnaissance in Puerto Penasco}
{717}{}{在佩纳斯科港进行侦察 -- Conduct reconnaissance in Puerto Penasco}
### {718}{}{}
{718}{}{error : string is empty -- }
### {719}{}{}
{719}{}{error : string is empty -- }

#---------------------------------------------------------
# Phoenix
#---------------------------------------------------------

### {800}{}{Learn about slaves from the Villa in Phoenix}
{800}{}{从凤凰山庄了解奴隶 -- Learn about slaves from the Villa in Phoenix}
### {801}{}{Find your Uncle Miguel in Phoenix}
{801}{}{在凤凰城找到你的米格尔叔叔 -- Find your Uncle Miguel in Phoenix}
### {802}{}{Bring the heads of the chieftains of Los Panchos}
{802}{}{带上洛斯潘乔斯酋长的头颅 -- Bring the heads of the chieftains of Los Panchos}
### {803}{}{Kill the legendary shooter Gil McCord}
{803}{}{杀死传奇射手吉尔·麦考德 -- Kill the legendary shooter Gil McCord}
### {804}{}{Investigate recent attacks on monks}
{804}{}{调查最近对僧侣的袭击 -- Investigate recent attacks on monks}
### {805}{}{Infiltrate the ranks of the rebels}
{805}{}{渗透叛军队伍 -- Infiltrate the ranks of the rebels}
### {806}{}{Help George Crook in San Brahmin}
{806}{}{帮助乔治·克鲁克在圣婆罗门 -- Help George Crook in San Brahmin}
### {807}{}{Eliminate George Crook}
{807}{}{淘汰George Crook -- Eliminate George Crook}
### {808}{}{Find an agent of the Liberation Party in the ruins}
{808}{}{在废墟中找到解放党的代理人 -- Find an agent of the Liberation Party in the ruins}
### {809}{}{Sabotage in the Cathedral commissioned by the Liberation Party}
{809}{}{解放党委托破坏大教堂 -- Sabotage in the Cathedral commissioned by the Liberation Party}
### {810}{}{The client will owe the casino a large amount of caps}
{810}{}{客户将欠赌场一大笔上限 -- The client will owe the casino a large amount of caps}
### {811}{}{Return stolen emails}
{811}{}{归还被盗电子邮件 -- Return stolen emails}
### {812}{}{The Red Cardinals gang is in trouble}
{812}{}{红雀队有麻烦了 -- The Red Cardinals gang is in trouble}
### {813}{}{There was an accident at the nuclear power plant}
{813}{}{核电站发生事故 -- There was an accident at the nuclear power plant}
### {814}{}{Iron Mike craves justice}
{814}{}{铁迈克渴望正义 -- Iron Mike craves justice}
### {815}{}{To help slum dwellers in their difficult fate}
{815}{}{帮助陷入困境的贫民窟居民 -- To help slum dwellers in their difficult fate}
### {816}{}{}
{816}{}{error : string is empty -- }
### {817}{}{}
{817}{}{error : string is empty -- }
### {818}{}{}
{818}{}{error : string is empty -- }
### {819}{}{}
{819}{}{error : string is empty -- }

#---------------------------------------------------------
# Fishermen's Village (Oil platform)
#---------------------------------------------------------

### {900}{}{Stop the leak on the oil platform}
{900}{}{停止油平台上的泄漏 -- Stop the leak on the oil platform}
### {901}{}{Cure patients from oil poisoning}
{901}{}{治疗油中毒患者 -- Cure patients from oil poisoning}
### {902}{}{Thelma asks to find her uncle's memorabilia}
{902}{}{塞尔玛要求找她叔叔的纪念品 -- Thelma asks to find her uncle's memorabilia}
### {903}{}{Bring the Geiger counter to the merchant}
{903}{}{把盖革计数器带给商人 -- Bring the Geiger counter to the merchant}
### {904}{}{Ruiz is looking for treasure}
{904}{}{鲁伊斯正在寻找宝藏 -- Ruiz is looking for treasure}
### {905}{}{To catch a creature that plunders fish caches}
{905}{}{抓一个偷鱼的家伙 -- To catch a creature that plunders fish caches}
### {906}{}{Investigate a mysterious murder}
{906}{}{调查一起神秘的谋杀案 -- Investigate a mysterious murder}

#---------------------------------------------------------
# Casa Grande
#---------------------------------------------------------

### {1000}{}{Steve claims his rights to the bath}
{1000}{}{史蒂夫声称他有洗澡的权利 -- Steve claims his rights to the bath}
### {1001}{}{Sullivan will pay for the repair of the water pump}
{1001}{}{Sullivan将支付水泵的维修费用 -- Sullivan will pay for the repair of the water pump}
### {1002}{}{There was a mess in an abandoned bar}
{1002}{}{一家废弃的酒吧里一片狼藉 -- There was a mess in an abandoned bar}
### {1003}{}{Robbers have appeared in Casa Grande}
{1003}{}{抢劫犯出现在格兰德之家 -- Robbers have appeared in Casa Grande}
### {1004}{}{Save a resident at the railway station}
{1004}{}{在火车站救一个居民 -- Save a resident at the railway station}
### {1005}{}{Destroy the mainline fuel depot}
{1005}{}{摧毁主线燃料库 -- Destroy the mainline fuel depot}
### {1006}{}{The mayor pays for the head of the leader of the Blue Shields}
{1006}{}{市长为蓝盾党领袖的首领买单 -- The mayor pays for the head of the leader of the Blue Shields}
### {1007}{}{}
{1007}{}{error : string is empty -- }
### {1008}{}{}
{1008}{}{error : string is empty -- }
### {1009}{}{}
{1009}{}{error : string is empty -- }

#---------------------------------------------------------
# Hermosillo
#---------------------------------------------------------

### {1100}{}{Return the radio to the Dominguez Ranch}
{1100}{}{将收音机送回多明格斯牧场 -- Return the radio to the Dominguez Ranch}
### {1101}{}{Escort the prisoner to Puerto Penasco}
{1101}{}{护送犯人到佩纳斯科港 -- Escort the prisoner to Puerto Penasco}

#---------------------------------------------------------
# San-Felipe (Old Lighthouse)
#---------------------------------------------------------

### {1200}{}{Check out rumors about monsters in the graveyard of ships}
{1200}{}{查看关于船只墓地中怪物的传言 -- Check out rumors about monsters in the graveyard of ships}
### {1201}{}{Get rid of monsters}
{1201}{}{除掉怪物 -- Get rid of monsters}
### {1202}{}{Repair the lighthouse}
{1202}{}{修理灯塔 -- Repair the lighthouse}
### {1203}{}{Find and save Gloria}
{1203}{}{查找并保存Gloria -- Find and save Gloria}

#---------------------------------------------------------
# Inferno
#---------------------------------------------------------

### {1300}{}{Find Paladin Barkley's entire squad}
{1300}{}{找到圣骑士巴克利的整个小队 -- Find Paladin Barkley's entire squad}
### {1301}{}{Levi is trying to create a mutagen to save his flock}
{1301}{}{李维正试图制造一种诱变剂来拯救他的羊群 -- Levi is trying to create a mutagen to save his flock}
### {1302}{}{Escort Diana to Casa Nueva}
{1302}{}{护送戴安娜前往努瓦之家 -- Escort Diana to Casa Nueva}
### {1303}{}{}
{1303}{}{error : string is empty -- }
### {1304}{}{}
{1304}{}{error : string is empty -- }
### {1305}{}{}
{1305}{}{error : string is empty -- }
### {1306}{}{}
{1306}{}{error : string is empty -- }
### {1307}{}{}
{1307}{}{error : string is empty -- }
### {1308}{}{}
{1308}{}{error : string is empty -- }
### {1309}{}{}
{1309}{}{error : string is empty -- }

#---------------------------------------------------------
# Casa Nueva
#---------------------------------------------------------

### {1400}{}{}
{1400}{}{error : string is empty -- }
### {1401}{}{Find the missing peasant}
{1401}{}{找到失踪的农民 -- Find the missing peasant}
### {1402}{}{Followers are trying to stop the epidemic}
{1402}{}{追随者们正在努力阻止疫情 -- Followers are trying to stop the epidemic}
### {1403}{}{People are disappearing at the concrete plant}
{1403}{}{混凝土厂里的人正在消失 -- People are disappearing at the concrete plant}
### {1404}{}{Chipo asks to cure his pet despite the discontent of the residents}
{1404}{}{Chipo不顾居民的不满要求为他的宠物治病 -- Chipo asks to cure his pet despite the discontent of the residents}
### {1405}{}{The local school needs more books}
{1405}{}{当地学校需要更多的书 -- The local school needs more books}
### {1406}{}{}
{1406}{}{error : string is empty -- }
### {1407}{}{}
{1407}{}{error : string is empty -- }
### {1408}{}{}
{1408}{}{error : string is empty -- }
### {1409}{}{}
{1409}{}{error : string is empty -- }

#---------------------------------------------------------
# ! Free slot
#---------------------------------------------------------

### {1500}{}{}
{1500}{}{error : string is empty -- }

#---------------------------------------------------------
# Old the motel
#---------------------------------------------------------

### {1600}{}{}
{1600}{}{error : string is empty -- }

#---------------------------------------------------------
# !DLC Dayglow / San Diego
#---------------------------------------------------------

### {1700}{}{Visit the mysterious city of the dead}
{1700}{}{参观神秘的亡灵之城 -- Visit the mysterious city of the dead}
### {1701}{}{Find Vault 24}
{1701}{}{查找Vault 24 -- Find Vault 24}
### {1702}{}{Neutralize a military robot in the ruins of Tijuana}
{1702}{}{在蒂华纳废墟中消灭一个军用机器人 -- Neutralize a military robot in the ruins of Tijuana}
### {1703}{}{Neutralize the distraught Gonzo}
{1703}{}{中和悲痛欲绝的贡佐 -- Neutralize the distraught Gonzo}
### {1704}{}{Restore the city's electricity supply}
{1704}{}{恢复城市电力供应 -- Restore the city's electricity supply}
### {1705}{}{Restore urban radio broadcasting}
{1705}{}{恢复城市广播 -- Restore urban radio broadcasting}
### {1706}{}{Take the holodisk to the Old Town}
{1706}{}{带全息盘去老城 -- Take the holodisk to the Old Town}
### {1707}{}{Meet the caravan from the Hub}
{1707}{}{从枢纽迎接商队 -- Meet the caravan from the Hub}
### {1708}{}{Treasures of Coronado Island}
{1708}{}{科罗纳多岛的宝藏 -- Treasures of Coronado Island}
### {1709}{}{Restore monorail service}
{1709}{}{恢复单轨服务 -- Restore monorail service}
### {1710}{}{Organize mariachi performances}
{1710}{}{组织马里亚奇表演 -- Organize mariachi performances}
### {1711}{}{Find Donovan}
{1711}{}{查找Donovan -- Find Donovan}
### {1712}{}{Get chips from black miners at the Factory}
{1712}{}{从工厂的黑人矿工那里获取芯片 -- Get chips from black miners at the Factory}
### {1713}{}{Granny Judy is looking for her husband Rupert}
{1713}{}{朱迪奶奶正在找她的丈夫鲁伯特 -- Granny Judy is looking for her husband Rupert}
### {1714}{}{To work for Mr. De Santi}
{1714}{}{为德桑蒂先生工作 -- To work for Mr. De Santi}
### {1715}{}{}
{1715}{}{error : string is empty -- }
### {1716}{}{Truckers' contract to search for relics}
{1716}{}{卡车司机搜寻文物合约 -- Truckers' contract to search for relics}
### {1717}{}{Contract for the delivery of strong alcohol}
{1717}{}{烈性酒交付合同 -- Contract for the delivery of strong alcohol}
### {1718}{}{Coffee delivery contract}
{1718}{}{咖啡配送合同 -- Coffee delivery contract}
### {1719}{}{Lunch delivery contract}
{1719}{}{午餐配送合同 -- Lunch delivery contract}
### {1720}{}{Mortimer's New book Search Contract}
{1720}{}{莫蒂默的新书《搜索合同》 -- Mortimer's New book Search Contract}

#---------------------------------------------------------
# ! Free slot
#---------------------------------------------------------

### {1800}{}{}
{1800}{}{error : string is empty -- }

#---------------------------------------------------------
# Santa- Ana
#---------------------------------------------------------

### {1900}{}{Talk to the residents about the holiday}
{1900}{}{与居民谈论节日 -- Talk to the residents about the holiday}
### {1901}{}{Find the missing ceremonial wreath}
{1901}{}{找到丢失的仪式花圈 -- Find the missing ceremonial wreath}
### {1902}{}{Find and return Lucia}
{1902}{}{查找并返回Lucia -- Find and return Lucia}
### {1903}{}{Stop the headman Ilario}
{1903}{}{阻止头目伊拉里奥 -- Stop the headman Ilario}
### {1904}{}{Conclude a trade alliance with Casa Nueva}
{1904}{}{与Casa Nueva缔结贸易联盟 -- Conclude a trade alliance with Casa Nueva}

#---------------------------------------------------------
# ! Free slot
#---------------------------------------------------------

### {2000}{}{}
{2000}{}{error : string is empty -- }

#---------------------------------------------------------
# Jackals
#---------------------------------------------------------

### {2100}{}{Save the Ranger}
{2100}{}{拯救游骑兵 -- Save the Ranger}
### {2101}{}{The rabid Bitch is ready to make alliances with outsiders to solve the problem of hunger}
{2101}{}{疯狂的婊子准备与外来者结盟以解决饥饿问题 -- The rabid Bitch is ready to make alliances with outsiders to solve the problem of hunger}
### {2102}{}{Black Fang intends to leave the valley to solve the problem of hunger}
{2102}{}{黑方打算离开山谷去解决饥饿问题 -- Black Fang intends to leave the valley to solve the problem of hunger}
### {2103}{}{Eliminate the Jackals}
{2103}{}{消灭豺狼 -- Eliminate the Jackals}
### {2104}{}{To raid the burrows together with the thugs from Garage City}
{2104}{}{与车库城的暴徒一起突袭洞穴 -- To raid the burrows together with the thugs from Garage City}

#---------------------------------------------------------
# Car outta Gas Quests
#---------------------------------------------------------

### {2200}{}{}
{2200}{}{error : string is empty -- }

#---------------------------------------------------------
# ! Free slot
#---------------------------------------------------------

### {2300}{}{}
{2300}{}{error : string is empty -- }

#---------------------------------------------------------
# Vault 27
#---------------------------------------------------------

### {2400}{}{Find Vault 27}
{2400}{}{查找Vault 27 -- Find Vault 27}
### {2401}{}{Find information about the background of the asylum 27}
{2401}{}{查找有关庇护背景的信息27 -- Find information about the background of the asylum 27}
### {2402}{}{Start backup generator}
{2402}{}{启动备用发电机 -- Start backup generator}
### {2403}{}{Start backup generator and restore ventilation}
{2403}{}{启动备用发电机并恢复通风 -- Start backup generator and restore ventilation}
### {2404}{}{Meet the surviving member of the expedition}
{2404}{}{会见探险队中幸存的成员 -- Meet the surviving member of the expedition}
### {2405}{}{Escort Arthur Carrington to the safe zone}
{2405}{}{护送阿瑟·卡林顿到安全区 -- Escort Arthur Carrington to the safe zone}

#---------------------------------------------------------
# Camp Fraternities of Steel
#---------------------------------------------------------

### {2500}{}{}
{2500}{}{error : string is empty -- }

#---------------------------------------------------------
# Raiders (mainline workers)
#---------------------------------------------------------

### {2600}{}{Eliminate the raider in the Casa Grande prison}
{2600}{}{消灭卡萨格兰德监狱的袭击者 -- Eliminate the raider in the Casa Grande prison}
### {2601}{}{Conclude a truce of Blue Shields with the Tinsmiths}
{2601}{}{蓝盾与锡匠达成停战协议 -- Conclude a truce of Blue Shields with the Tinsmiths}
### {2602}{}{Conclude a truce of Blue Shields with Casa Grande}
{2602}{}{蓝盾与格兰德之家达成停战协议 -- Conclude a truce of Blue Shields with Casa Grande}
### {2603}{}{Take a questionable package to a pusher in Phoenix}
{2603}{}{把一个有问题的包裹带到凤凰城的一个售货员那里 -- Take a questionable package to a pusher in Phoenix}
### {2604}{}{Prepare Chuck for the initiation ceremony}
{2604}{}{为Chuck的入会仪式做准备 -- Prepare Chuck for the initiation ceremony}
### {2605}{}{}
{2605}{}{error : string is empty -- }
### {2606}{}{}
{2606}{}{error : string is empty -- }
### {2607}{}{}
{2607}{}{error : string is empty -- }
### {2608}{}{}
{2608}{}{error : string is empty -- }
### {2609}{}{}
{2609}{}{error : string is empty -- }

#---------------------------------------------------------
# Camp Winon
#---------------------------------------------------------
### {4900}{}{}
{4900}{}{error : string is empty -- }
