#######################################################
#
# Names of districts for the loading window of locations
#
#######################################################


# Villa
### {200}{}{Sleeping area}
{200}{}{睡眠区 -- Sleeping area}
### {201}{}{Plaza de la Sombra}
{201}{}{索布拉广场 -- Plaza de la Sombra}
### {202}{}{Villa Cellars}
{202}{}{别墅地窖 -- Villa Cellars}
### {203}{}{Maize plantations}
{203}{}{玉米种植园 -- Maize plantations}
### {204}{}{Ancient ruins}
{204}{}{古代遗迹 -- Ancient ruins}
### {205}{}{Founder's Crypt}
{205}{}{创始人的地穴 -- Founder's Crypt}
#
# Flagstaff
### {210}{}{Colony}
{210}{}{殖民地 -- Colony}
### {211}{}{Garrison}
{211}{}{驻军 -- Garrison}
### {212}{}{Uranium mine}
{212}{}{铀矿 -- Uranium mine}
### {213}{}{Abandoned area}
{213}{}{废弃区域 -- Abandoned area}
### {214}{}{Mine drifts}
{214}{}{矿井巷道 -- Mine drifts}
### {215}{}{Randy's Farm}
{215}{}{Randy的农场 -- Randy's Farm}
#
# Garage City
### {220}{}{Business district}
{220}{}{商业区 -- Business district}
### {221}{}{Shacks}
{221}{}{Shacks -- Shacks}
### {222}{}{Abandoned factory}
{222}{}{废弃工厂 -- Abandoned factory}
### {223}{}{Route 66}
{223}{}{66号公路 -- Route 66}
### {224}{}{Cattle breeders' camp}
{224}{}{养牛人营地 -- Cattle breeders' camp}
### {225}{}{Mojave Water Pump}
{225}{}{莫哈韦水泵 -- Mojave Water Pump}
### {226}{}{Clek Canyon}
{226}{}{克莱克峡谷 -- Clek Canyon}
#
# San Brahmin
### {230}{}{Missionaries' Camp}
{230}{}{传教士营地 -- Missionaries' Camp}
### {231}{}{Pueblo}
{231}{}{普韦布洛 -- Pueblo}
### {232}{}{Brahmin Pens}
{232}{}{婆罗门笔 -- Brahmin Pens}
### {233}{}{The Buried City}
{233}{}{被埋葬的城市 -- The Buried City}
### {234}{}{Oasis}
{234}{}{绿洲 -- Oasis}
#
# Two-Sun
### {240}{}{Settlement}
{240}{}{协议 -- Settlement}
### {241}{}{Workshop}
{241}{}{车间 -- Workshop}
### {242}{}{Storage}
{242}{}{存储 -- Storage}
### {243}{}{Control Center}
{243}{}{控制中心 -- Control Center}
### {244}{}{Ambush site}
{244}{}{伏击现场 -- Ambush site}
### {245}{}{Old Town}
{245}{}{老城 -- Old Town}
#
# Puerto Penasco
### {250}{}{Main Street}
{250}{}{主街 -- Main Street}
### {251}{}{Old port}
{251}{}{旧港口 -- Old port}
### {252}{}{Brotherhood of Steel Base}
{252}{}{钢铁基地兄弟会 -- Brotherhood of Steel Base}
#
# Rangers
### {260}{}{The road to the dam}
{260}{}{通往大坝的道路 -- The road to the dam}
### {261}{}{Dam}
{261}{}{水坝 -- Dam}
### {262}{}{Aqueduct}
{262}{}{渡槽 -- Aqueduct}
### {263}{}{Radio station}
{263}{}{无线电台 -- Radio station}
### {264}{}{Crossing}
{264}{}{十字路口 -- Crossing}
### {265}{}{Repeater}
{265}{}{中继器 -- Repeater}
### {266}{}{Giers-Wash}
{266}{}{Giers Wash -- Giers-Wash}
### {267}{}{Citadel}
{267}{}{城堡 -- Citadel}
#
# Phoenix
### {270}{}{City gates}
{270}{}{城门 -- City gates}
### {271}{}{Downtown}
{271}{}{市中心 -- Downtown}
### {272}{}{Slums}
{272}{}{贫民窟 -- Slums}
### {273}{}{Power plant}
{273}{}{发电厂 -- Power plant}
### {274}{}{The Area of the Atom}
{274}{}{原子的面积 -- The Area of the Atom}
### {275}{}{Cathedral}
{275}{}{大教堂 -- Cathedral}
### {276}{}{Vault 25}
{276}{}{保险库25 -- Vault 25}
### {277}{}{Phoenix Ruins}
{277}{}{凤凰城遗址 -- Phoenix Ruins}
### {278}{}{Collectors}
{278}{}{收集器 -- Collectors}
### {279}{}{Core-Cola Warehouse}
{279}{}{核心可乐仓库 -- Core-Cola Warehouse}
#
# Oil Platform
### {280}{}{Fishermen's Village}
{280}{}{渔民村 -- Fishermen's Village}
### {281}{}{Oil platform}
{281}{}{石油平台 -- Oil platform}
### {282}{}{Oil platform}
{282}{}{石油平台 -- Oil platform}
### {283}{}{Oil platform}
{283}{}{石油平台 -- Oil platform}
### {284}{}{Black Lagoon}
{284}{}{黑礁 -- Black Lagoon}
#
# Casa Grande
### {290}{}{Water station}
{290}{}{供水站 -- Water station}
### {291}{}{Hacienda}
{291}{}{庄园 -- Hacienda}
### {292}{}{Burial ground}
{292}{}{墓地 -- Burial ground}
### {293}{}{Ruins of the school}
{293}{}{学校废墟 -- Ruins of the school}
### {294}{}{Abandoned bar}
{294}{}{废弃酒吧 -- Abandoned bar}
### {295}{}{Railway station}
{295}{}{火车站 -- Railway station}
#
# Hermosillo
### {300}{}{Rancho Dominguez}
{300}{}{兰乔·多明格斯 -- Rancho Dominguez}
### {301}{}{Garrison}
{301}{}{驻军 -- Garrison}
### {302}{}{Fort}
{302}{}{要塞 -- Fort}
#
# San Felipe (Old Lighthouse)
### {310}{}{Settlement at the lighthouse}
{310}{}{灯塔定居点 -- Settlement at the lighthouse}
### {311}{}{Fondeport}
{311}{}{Fonporto -- Fondeport}
### {312}{}{Cerro Picacho del Diablo}
{312}{}{Cerro Picacho del Diablo -- Cerro Picacho del Diablo}
#
# Inferno
### {320}{}{Traffic congestion}
{320}{}{交通拥挤 -- Traffic congestion}
### {321}{}{Sleeping quarter}
{321}{}{睡眠区 -- Sleeping quarter}
### {322}{}{Supermarket}
{322}{}{超级市场 -- Supermarket}
### {323}{}{Police station}
{323}{}{警察局 -- Police station}
### {324}{}{The mysterious mansion}
{324}{}{神秘的豪宅 -- The mysterious mansion}
### {325}{}{Main Highway}
{325}{}{主要公路 -- Main Highway}
#
# Casa Nueva
### {330}{}{Settlement}
{330}{}{协议 -- Settlement}
### {331}{}{Agave plantations}
{331}{}{龙舌兰种植园 -- Agave plantations}
### {332}{}{Greenhouses}
{332}{}{温室 -- Greenhouses}
### {333}{}{Greenhouses}
{333}{}{温室 -- Greenhouses}
### {334}{}{Quarry}
{334}{}{采石场 -- Quarry}
#
# ! Empty slot
### {340}{}{Desert}
{340}{}{沙漠 -- Desert}
#
# Dead Motel
### {350}{}{Old Motel}
{350}{}{老汽车旅馆 -- Old Motel}
#
# Dayglow DLC
### {360}{}{Ruins of Tijuana}
{360}{}{蒂华纳遗址 -- Ruins of Tijuana}
### {361}{}{Camp in San Isidro}
{361}{}{San Isidro营地 -- Camp in San Isidro}
### {362}{}{Bonita Dam}
{362}{}{博尼塔大坝 -- Bonita Dam}
### {363}{}{Camp in the Old Town}
{363}{}{老城营地 -- Camp in the Old Town}
### {364}{}{Ruins of San Isidro}
{364}{}{圣伊西德罗遗址 -- Ruins of San Isidro}
### {365}{}{Chula Vista Nuclear Mines}
{365}{}{Chula Vista核矿山 -- Chula Vista Nuclear Mines}
### {366}{}{Ruins of National City}
{366}{}{国家城市遗址 -- Ruins of National City}
### {367}{}{The Heart of San Diego}
{367}{}{圣地亚哥的心脏 -- The Heart of San Diego}
### {368}{}{Piers}
{368}{}{桥墩 -- Piers}
### {369}{}{Vault 24}
{369}{}{保险库24 -- Vault 24}
### {370}{}{US Navy Base}
{370}{}{美国海军基地 -- US Navy Base}
#
# ! Empty slot
### {370}{}{Desert}
{370}{}{沙漠 -- Desert}
#
# Santa Ana
### {380}{}{Plaza Zaragoza}
{380}{}{萨拉戈萨广场 -- Plaza Zaragoza}
### {381}{}{Ancient monument}
{381}{}{古代纪念碑 -- Ancient monument}
### {382}{}{Ancient cemetery}
{382}{}{古代墓地 -- Ancient cemetery}
#
# ! Empty slot
### {390}{}{Desert}
{390}{}{沙漠 -- Desert}
#
# Jackals
### {400}{}{Lair of Jackals}
{400}{}{豺狼的巢穴 -- Lair of Jackals}
#
# Motorcycle without power
### {410}{}{Pit stop}
{410}{}{进站 -- Pit stop}
#
# Destroyed Arroyo (do not use!)
### {420}{}{Desert}
{420}{}{沙漠 -- Desert}
#
# Vault 27
### {430}{}{Entrance to the Vault}
{430}{}{金库入口 -- Entrance to the Vault}
### {431}{}{Vault Rooms}
{431}{}{保管室 -- Vault Rooms}
#
# Brotherhood Camp
### {440}{}{Desert camp}
{440}{}{沙漠营地 -- Desert camp}
### {441}{}{Camp in Kaborka}
{441}{}{卡博卡营地 -- Camp in Kaborka}
### {442}{}{Camp in the mountains}
{442}{}{在山上露营 -- Camp in the mountains}
#
# Raiders
### {450}{}{Mainline Camp}
{450}{}{主线营地 -- Mainline Camp}
#
# Random Encounter Desert (Wasteland)
### {460}{}{Desert}
{460}{}{沙漠 -- Desert}
### {461}{}{Desert}
{461}{}{沙漠 -- Desert}
### {462}{}{Desert}
{462}{}{沙漠 -- Desert}
### {463}{}{Desert}
{463}{}{沙漠 -- Desert}
### {464}{}{Desert}
{464}{}{沙漠 -- Desert}
#
# Random Encounter Mountain (Mountainous terrain)
### {470}{}{Gorge}
{470}{}{峡 -- Gorge}
### {471}{}{Gorge}
{471}{}{峡 -- Gorge}
### {472}{}{Gorge}
{472}{}{峡 -- Gorge}
### {473}{}{Gorge}
{473}{}{峡 -- Gorge}
### {474}{}{Gorge}
{474}{}{峡 -- Gorge}
### {475}{}{Gorge}
{475}{}{峡 -- Gorge}
### {476}{}{Chernolesye}
{476}{}{Chernolesye -- Chernolesye}
### {477}{}{Chernolesye}
{477}{}{Chernolesye -- Chernolesye}
### {478}{}{Gorge}
{478}{}{峡 -- Gorge}
#
# Random Encounter City (Ruins)
### {480}{}{Ruins}
{480}{}{废墟 -- Ruins}
### {481}{}{Ruins}
{481}{}{废墟 -- Ruins}
### {482}{}{Ruins}
{482}{}{废墟 -- Ruins}
### {483}{}{Ruins}
{483}{}{废墟 -- Ruins}
### {484}{}{Ruins}
{484}{}{废墟 -- Ruins}
### {485}{}{Autoroute}
{485}{}{自动布线 -- Autoroute}
### {486}{}{Autoroute}
{486}{}{自动布线 -- Autoroute}
### {487}{}{Autoroute}
{487}{}{自动布线 -- Autoroute}
### {488}{}{Autoroute}
{488}{}{自动布线 -- Autoroute}
### {489}{}{Highway}
{489}{}{公路 -- Highway}
#
# Random Encounter Coast
### {490}{}{The coast}
{490}{}{海岸 -- The coast}
### {491}{}{The coast}
{491}{}{海岸 -- The coast}
### {492}{}{The coast}
{492}{}{海岸 -- The coast}
### {493}{}{Coast}
{493}{}{海岸 -- Coast}
#
# Explosion crater in Puerto
### {500}{}{Defeat Zone}
{500}{}{失败区域 -- Defeat Zone}
#
# Special Encounter - Gold
### {510}{}{Sonora Wasteland}
{510}{}{索诺拉荒原 -- Sonora Wasteland}
#
# Special Encounter - Henry Beamis
### {520}{}{Sonora Wasteland}
{520}{}{索诺拉荒原 -- Sonora Wasteland}
#
# Special Encounter - Roadside Cafe
### {530}{}{Sonoran Wasteland}
{530}{}{索诺兰荒原 -- Sonoran Wasteland}
#
# Special Encounter - Bomber
### {540}{}{Sonora Wasteland}
{540}{}{索诺拉荒原 -- Sonora Wasteland}
#
# Special Encounter - Petro-Chico Truck
### {550}{}{Sonoran Wasteland}
{550}{}{索诺兰荒原 -- Sonoran Wasteland}
#
# Special Encounter - The Cry of Silence
### {560}{}{Sonora Wasteland}
{560}{}{索诺拉荒原 -- Sonora Wasteland}
#
# Special Encounter - Night Movie Screening
### {570}{}{Sonoran Wasteland}
{570}{}{索诺兰荒原 -- Sonoran Wasteland}
#
# Special Encounter - Padre
### {580}{}{Sonoran Wasteland}
{580}{}{索诺兰荒原 -- Sonoran Wasteland}
#
# Special Encounter - Baron of Arizona
### {590}{}{Sonora Wasteland}
{590}{}{索诺拉荒原 -- Sonora Wasteland}
#
# Special Encounter - Snowfall
### {600}{}{Sonoran Wasteland}
{600}{}{索诺兰荒原 -- Sonoran Wasteland}
#
# Special Encounter - The Lost Refuge (Van Buren)
### {610}{}{Sonoran Wasteland}
{610}{}{索诺兰荒原 -- Sonoran Wasteland}
#
# Special Encounter - Mobile Fortress of the Creator's Army
### {620}{}{Sonoran Wasteland}
{620}{}{索诺兰荒原 -- Sonoran Wasteland}
#
# Special Encounter - Rail Nomads
### {630}{}{Sonora Wasteland}
{630}{}{索诺拉荒原 -- Sonora Wasteland}
#
# ! Empty slot
### {640}{}{Sonora Wasteland}
{640}{}{索诺拉荒原 -- Sonora Wasteland}
#
# ! Empty slot
### {650}{}{Sonora Wasteland}
{650}{}{索诺拉荒原 -- Sonora Wasteland}
#
# Irradiated Village (Quartzsite)
### {660}{}{Ruins of the Quartzsite}
{660}{}{Quartzsite遗址 -- Ruins of the Quartzsite}
#
# Shadow Worlds
### {670}{}{Desert}
{670}{}{沙漠 -- Desert}
### {671}{}{Desert}
{671}{}{沙漠 -- Desert}
### {672}{}{Federal Highway}
{672}{}{联邦公路 -- Federal Highway}
### {673}{}{Phoenix Suburb}
{673}{}{菲尼克斯郊区 -- Phoenix Suburb}
### {674}{}{Desert}
{674}{}{沙漠 -- Desert}
### {675}{}{Desert}
{675}{}{沙漠 -- Desert}
### {676}{}{Desert}
{676}{}{沙漠 -- Desert}
### {677}{}{Desert}
{677}{}{沙漠 -- Desert}
### {678}{}{Desert}
{678}{}{沙漠 -- Desert}
### {679}{}{Desert}
{679}{}{沙漠 -- Desert}
#
# Winon Camp
### {680}{}{Camp in the mountains}
{680}{}{在山上露营 -- Camp in the mountains}


#######################################################
#
# Miscellaneous
#
#######################################################

# Signature when hovering the cursor over the GG marker (does not work, a vestige of Fallout 1):
### {1000}{}{Desert}
{1000}{}{沙漠 -- Desert}
### {1001}{}{Mountains}
{1001}{}{山脉 -- Mountains}
### {1002}{}{Ruins}
{1002}{}{废墟 -- Ruins}
### {1003}{}{The coast}
{1003}{}{海岸 -- The coast}

# Signature of the location not yet studied:
### {1004}{}{Unknown}
{1004}{}{未知的 -- Unknown}

# Miscellaneous:
### {1500}{}{You have gained 10,000 experience points!}
{1500}{}{您已获得10000点经验值！ -- You have gained 10,000 experience points!}
### {1501}{}{Ruins}
{1501}{}{废墟 -- Ruins}
### {1502}{}{Your motorcycle has run out of energy.}
{1502}{}{你的摩托车没电了。 -- Your motorcycle has run out of energy.}
### {1503}{}{It's a motorcycle. Apparently, it doesn't work.}
{1503}{}{这是一辆摩托车。显然，它不起作用。 -- It's a motorcycle. Apparently, it doesn't work.}


#######################################################
#
# Description of meetings on the world map
#
#######################################################

### {2998}{}{You encounter:}
{2998}{}{您会遇到： -- You encounter:}
### {2999}{}{Do you wish to encounter:}
{2999}{}{您是否希望遇到： -- Do you wish to encounter:}

# Encounter Table 0 -- TEST_D
### {3000}{}{Red Rider.}
{3000}{}{红色骑士。 -- Red Rider.}
### {3001}{}{Rockfall!}
{3001}{}{Rockfall！ -- Rockfall!}
### {3002}{}{Radioactive fog!}
{3002}{}{放射性雾！ -- Radioactive fog!}
### {3003}{}{Dust storm!}
{3003}{}{沙尘暴！ -- Dust storm!}
### {3004}{}{Dehydration!}
{3004}{}{脱水！ -- Dehydration!}
### {3005}{}{Giant ants.}
{3005}{}{巨型蚂蚁。 -- Giant ants.}
### {3006}{}{A group of radmurts.}
{3006}{}{一群小狗。 -- A group of radmurts.}
### {3007}{}{A swarm of mantises.}
{3007}{}{一群螳螂。 -- A swarm of mantises.}
### {3008}{}{A pack of rats.}
{3008}{}{一群老鼠。 -- A pack of rats.}
### {3009}{}{A flock of pig rats.}
{3009}{}{一群猪老鼠。 -- A flock of pig rats.}
### {3010}{}{A flock of mole rats.}
{3010}{}{一群鼹鼠。 -- A flock of mole rats.}
### {3011}{}{A pack of coyotes.}
{3011}{}{一群郊狼。 -- A pack of coyotes.}
### {3012}{}{A pack of stray dogs.}
{3012}{}{一群流浪狗。 -- A pack of stray dogs.}
### {3013}{}{A pack of wolves.}
{3013}{}{一群狼。 -- A pack of wolves.}
### {3014}{}{A group of radscorpions.}
{3014}{}{一群辐射蝎子。 -- A group of radscorpions.}
### {3015}{}{The radscorpion group.}
{3015}{}{radscorpion集团。 -- The radscorpion group.}
### {3016}{}{Wild Brahmins.}
{3016}{}{狂野的婆罗门。 -- Wild Brahmins.}
### {3017}{}{Monsters.}
{3017}{}{怪兽。 -- Monsters.}
### {3018}{}{The robot.}
{3018}{}{机器人。 -- The robot.}
### {3019}{}{Giant scolopendra.}
{3019}{}{巨大的scolopendra。 -- Giant scolopendra.}
### {3020}{}{Gold!}
{3020}{}{金 -- Gold!}
### {3021}{}{Henry Beamis.}
{3021}{}{亨利·比米斯。 -- Henry Beamis.}
### {3022}{}{Roadside cafe.}
{3022}{}{路边咖啡馆。 -- Roadside cafe.}
### {3023}{}{The crashed bomber.}
{3023}{}{坠毁的轰炸机。 -- The crashed bomber.}
### {3024}{}{Petro-Chico truck.}
{3024}{}{Petro Chico卡车。 -- Petro-Chico truck.}
### {3025}{}{The cry of silence.}
{3025}{}{沉默的呐喊。 -- The cry of silence.}
### {3026}{}{Night movie screening.}
{3026}{}{夜间电影放映。 -- Night movie screening.}
### {3027}{}{Snowfall.}
{3027}{}{雪花飘落。 -- Snowfall.}
### {3028}{}{Lost Vault.}
{3028}{}{丢失的保险库。 -- Lost Vault.}
### {3029}{}{Mobile fortress.}
{3029}{}{移动堡垒。 -- Mobile fortress.}
### {3030}{}{Legend City.}
{3030}{}{传奇之城。 -- Legend City.}

# Encounter Table 1 -- VILL_D
### {3050}{}{Giant ants.}
{3050}{}{巨型蚂蚁。 -- Giant ants.}
### {3051}{}{A pack of coyotes.}
{3051}{}{一群郊狼。 -- A pack of coyotes.}
### {3052}{}{A flock of pig rats.}
{3052}{}{一群猪老鼠。 -- A flock of pig rats.}
### {3053}{}{A group of radscorpions.}
{3053}{}{一群辐射蝎子。 -- A group of radscorpions.}
### {3054}{}{Jackals.}
{3054}{}{豺狼。 -- Jackals.}
### {3055}{}{Gang from Nevada.}
{3055}{}{来自内华达州的帮派。 -- Gang from Nevada.}
### {3056}{}{Gold!}
{3056}{}{金 -- Gold!}
### {3057}{}{Henry Beamis.}
{3057}{}{亨利·比米斯。 -- Henry Beamis.}
### {3058}{}{Roadside cafe.}
{3058}{}{路边咖啡馆。 -- Roadside cafe.}
### {3059}{}{A crashed bomber.}
{3059}{}{一架坠毁的轰炸机。 -- A crashed bomber.}
### {3060}{}{Petro-Chico truck.}
{3060}{}{Petro Chico卡车。 -- Petro-Chico truck.}
### {3061}{}{The cry of silence.}
{3061}{}{沉默的呐喊。 -- The cry of silence.}
### {3062}{}{Night movie screening.}
{3062}{}{夜间电影放映。 -- Night movie screening.}
### {3063}{}{Snowfall.}
{3063}{}{雪花飘落。 -- Snowfall.}
### {3064}{}{Lost Vault.}
{3064}{}{丢失的保险库。 -- Lost Vault.}
### {3065}{}{Mobile fortress.}
{3065}{}{移动堡垒。 -- Mobile fortress.}
### {3066}{}{Legend City.}
{3066}{}{传奇之城。 -- Legend City.}

# Encounter Table 2 -- FLAG_D
### {3100}{}{Red Rider.}
{3100}{}{红色骑士。 -- Red Rider.}
### {3101}{}{A flock of pig rats.}
{3101}{}{一群猪老鼠。 -- A flock of pig rats.}
### {3102}{}{A pack of wolves.}
{3102}{}{一群狼。 -- A pack of wolves.}
### {3103}{}{A herd of wild Brahmins.}
{3103}{}{一群野蛮的婆罗门。 -- A herd of wild Brahmins.}
### {3104}{}{Savages.}
{3104}{}{野蛮人。 -- Savages.}
### {3105}{}{The White Mountain Detachment.}
{3105}{}{白山支队。 -- The White Mountain Detachment.}
### {3106}{}{Hunter.}
{3106}{}{猎人 -- Hunter.}
### {3107}{}{Gold!}
{3107}{}{金 -- Gold!}
### {3108}{}{Henry Beamis.}
{3108}{}{亨利·比米斯。 -- Henry Beamis.}
### {3109}{}{Roadside cafe.}
{3109}{}{路边咖啡馆。 -- Roadside cafe.}
### {3110}{}{A crashed bomber.}
{3110}{}{一架坠毁的轰炸机。 -- A crashed bomber.}
### {3111}{}{Petro-Chico truck.}
{3111}{}{Petro Chico卡车。 -- Petro-Chico truck.}
### {3112}{}{The cry of silence.}
{3112}{}{沉默的呐喊。 -- The cry of silence.}
### {3113}{}{Night movie screening.}
{3113}{}{夜间电影放映。 -- Night movie screening.}
### {3114}{}{Flying Padre.}
{3114}{}{飞行教士。 -- Flying Padre.}
### {3115}{}{Snowfall.}
{3115}{}{雪花飘落。 -- Snowfall.}
### {3116}{}{Lost Refuge.}
{3116}{}{丢失的避难所。 -- Lost Refuge.}
### {3117}{}{Mobile fortress.}
{3117}{}{移动堡垒。 -- Mobile fortress.}
### {3118}{}{Legend City.}
{3118}{}{传奇之城。 -- Legend City.}

# Encounter Table 3 -- FLAG_M
### {3150}{}{Red Rider.}
{3150}{}{红色骑士。 -- Red Rider.}
### {3151}{}{Rockfall!}
{3151}{}{Rockfall！ -- Rockfall!}
### {3152}{}{A flock of mole rats.}
{3152}{}{一群鼹鼠。 -- A flock of mole rats.}
### {3153}{}{A pack of wolves.}
{3153}{}{一群狼。 -- A pack of wolves.}
### {3154}{}{A body gnawed by animals.}
{3154}{}{被动物啃咬的身体。 -- A body gnawed by animals.}
### {3155}{}{Hunter.}
{3155}{}{猎人 -- Hunter.}
### {3156}{}{Savages.}
{3156}{}{野蛮人。 -- Savages.}
### {3157}{}{Gold!}
{3157}{}{金 -- Gold!}
### {3158}{}{Henry Beamis.}
{3158}{}{亨利·比米斯。 -- Henry Beamis.}
### {3159}{}{Roadside cafe.}
{3159}{}{路边咖啡馆。 -- Roadside cafe.}
### {3160}{}{The crashed bomber.}
{3160}{}{坠毁的轰炸机。 -- The crashed bomber.}
### {3161}{}{Petro-Chico truck.}
{3161}{}{Petro Chico卡车。 -- Petro-Chico truck.}
### {3162}{}{A cry of silence.}
{3162}{}{沉默的呼喊。 -- A cry of silence.}
### {3163}{}{Night movie screening.}
{3163}{}{夜间电影放映。 -- Night movie screening.}
### {3164}{}{Lost Refuge.}
{3164}{}{丢失的避难所。 -- Lost Refuge.}
### {3165}{}{Legend City.}
{3165}{}{传奇之城。 -- Legend City.}

# Encounter Table 4 -- FLAG_R
### {3200}{}{Red Rider.}
{3200}{}{红色骑士。 -- Red Rider.}
### {3201}{}{A flock of pig rats.}
{3201}{}{一群猪老鼠。 -- A flock of pig rats.}
### {3202}{}{Robbers.}
{3202}{}{抢劫犯。 -- Robbers.}
### {3203}{}{Robbers.}
{3203}{}{抢劫犯。 -- Robbers.}
### {3204}{}{Fugitive criminal.}
{3204}{}{逃犯。 -- Fugitive criminal.}
### {3205}{}{Caravan.}
{3205}{}{大篷车 -- Caravan.}
### {3206}{}{Colonizer group.}
{3206}{}{殖民者小组。 -- Colonizer group.}
### {3207}{}{Stray dogs.}
{3207}{}{流浪狗。 -- Stray dogs.}

# Encounter Table 5 -- RNGR_D
### {3250}{}{Red Rider.}
{3250}{}{红色骑士。 -- Red Rider.}
### {3251}{}{Dust storm!}
{3251}{}{沙尘暴！ -- Dust storm!}
### {3252}{}{A pack of coyotes.}
{3252}{}{一群郊狼。 -- A pack of coyotes.}
### {3253}{}{A group of radscorpions.}
{3253}{}{一群辐射蝎子。 -- A group of radscorpions.}
### {3254}{}{Raiders.}
{3254}{}{突袭者。 -- Raiders.}
### {3255}{}{Farmer.}
{3255}{}{农民 -- Farmer.}
### {3256}{}{Rangers.}
{3256}{}{游骑兵队。 -- Rangers.}
### {3257}{}{The Rangers are chasing the rustlers.}
{3257}{}{游骑兵队正在追赶那些偷东西的人。 -- The Rangers are chasing the rustlers.}
### {3258}{}{Giant scolopendra.}
{3258}{}{巨大的scolopendra。 -- Giant scolopendra.}
### {3259}{}{Gold!}
{3259}{}{金 -- Gold!}
### {3260}{}{Henry Beamis.}
{3260}{}{亨利·比米斯。 -- Henry Beamis.}
### {3261}{}{Roadside cafe.}
{3261}{}{路边咖啡馆。 -- Roadside cafe.}
### {3262}{}{The crashed bomber.}
{3262}{}{坠毁的轰炸机。 -- The crashed bomber.}
### {3263}{}{Petro-Chico truck.}
{3263}{}{Petro Chico卡车。 -- Petro-Chico truck.}
### {3264}{}{The cry of silence.}
{3264}{}{沉默的呐喊。 -- The cry of silence.}
### {3265}{}{Night movie screening.}
{3265}{}{夜间电影放映。 -- Night movie screening.}
### {3266}{}{Snowfall.}
{3266}{}{雪花飘落。 -- Snowfall.}
### {3267}{}{Lost Refuge.}
{3267}{}{丢失的避难所。 -- Lost Refuge.}
### {3268}{}{Mobile fortress.}
{3268}{}{移动堡垒。 -- Mobile fortress.}
### {3269}{}{Legend City.}
{3269}{}{传奇之城。 -- Legend City.}
### {3270}{}{Bankrupt farmer.}
{3270}{}{破产的农民。 -- Bankrupt farmer.}
### {3271}{}{The terrible monster of La Fantasma!}
{3271}{}{La Fantasma的可怕怪物！ -- The terrible monster of La Fantasma!}

# Encounter Table 6 -- DSRT_A
### {3300}{}{Dust storm!}
{3300}{}{沙尘暴！ -- Dust storm!}
### {3301}{}{Dehydration!}
{3301}{}{脱水！ -- Dehydration!}
### {3302}{}{Radscorpion group.}
{3302}{}{Radscorpion集团。 -- Radscorpion group.}
### {3303}{}{The legendary radscorpion!}
{3303}{}{传说中的蛇蝎！ -- The legendary radscorpion!}
### {3304}{}{Giant scolopendra.}
{3304}{}{巨大的scolopendra。 -- Giant scolopendra.}
### {3305}{}{Gold!}
{3305}{}{金 -- Gold!}
### {3306}{}{Henry Beamis.}
{3306}{}{亨利·比米斯。 -- Henry Beamis.}
### {3307}{}{Roadside cafe.}
{3307}{}{路边咖啡馆。 -- Roadside cafe.}
### {3308}{}{The crashed bomber.}
{3308}{}{坠毁的轰炸机。 -- The crashed bomber.}
### {3309}{}{Petro-Chico truck.}
{3309}{}{Petro Chico卡车。 -- Petro-Chico truck.}
### {3310}{}{The cry of silence.}
{3310}{}{沉默的呐喊。 -- The cry of silence.}
### {3311}{}{Night movie screening.}
{3311}{}{夜间电影放映。 -- Night movie screening.}
### {3312}{}{Snowfall.}
{3312}{}{雪花飘落。 -- Snowfall.}
### {3313}{}{Lost Refuge.}
{3313}{}{丢失的避难所。 -- Lost Refuge.}
### {3314}{}{Mobile fortress.}
{3314}{}{移动堡垒。 -- Mobile fortress.}
### {3315}{}{Legend City.}
{3315}{}{传奇之城。 -- Legend City.}

# Encounter Table 7 -- DSRT_B
### {3350}{}{Dust storm!}
{3350}{}{沙尘暴！ -- Dust storm!}
### {3351}{}{Dehydration!}
{3351}{}{脱水！ -- Dehydration!}
### {3352}{}{Radscorpion group.}
{3352}{}{Radscorpion集团。 -- Radscorpion group.}
### {3353}{}{Giant scolopendra.}
{3353}{}{巨大的scolopendra。 -- Giant scolopendra.}
### {3354}{}{Swarm of mantises.}
{3354}{}{一群螳螂。 -- Swarm of mantises.}
### {3355}{}{Gold!}
{3355}{}{金 -- Gold!}
### {3356}{}{Henry Beamis.}
{3356}{}{亨利·比米斯。 -- Henry Beamis.}
### {3357}{}{Roadside cafe.}
{3357}{}{路边咖啡馆。 -- Roadside cafe.}
### {3358}{}{A crashed bomber.}
{3358}{}{一架坠毁的轰炸机。 -- A crashed bomber.}
### {3359}{}{Petro-Chico truck.}
{3359}{}{Petro Chico卡车。 -- Petro-Chico truck.}
### {3360}{}{The cry of silence.}
{3360}{}{沉默的呐喊。 -- The cry of silence.}
### {3361}{}{Night movie screening.}
{3361}{}{夜间电影放映。 -- Night movie screening.}
### {3362}{}{Shy robot.}
{3362}{}{害羞的机器人。 -- Shy robot.}
### {3363}{}{Snowfall.}
{3363}{}{雪花飘落。 -- Snowfall.}
### {3364}{}{Lost Refuge.}
{3364}{}{丢失的避难所。 -- Lost Refuge.}
### {3365}{}{Mobile fortress.}
{3365}{}{移动堡垒。 -- Mobile fortress.}
### {3366}{}{Legend City.}
{3366}{}{传奇之城。 -- Legend City.}
### {3367}{}{A wrecked car.}
{3367}{}{一辆失事的汽车。 -- A wrecked car.}

# Encounter Table 8 -- MEXI_D
### {3400}{}{Red Rider.}
{3400}{}{红色骑士。 -- Red Rider.}
### {3401}{}{Radscorpion group.}
{3401}{}{Radscorpion集团。 -- Radscorpion group.}
### {3402}{}{Swarm of mantises.}
{3402}{}{一群螳螂。 -- Swarm of mantises.}
### {3403}{}{Giant scolopendra.}
{3403}{}{巨大的scolopendra。 -- Giant scolopendra.}
### {3404}{}{Mexican Army patrol.}
{3404}{}{墨西哥军队巡逻队。 -- Mexican Army patrol.}
### {3405}{}{A group of immigrants.}
{3405}{}{一群移民。 -- A group of immigrants.}
### {3406}{}{The body of an immigrant who died in the desert.}
{3406}{}{一具死于沙漠的移民的尸体。 -- The body of an immigrant who died in the desert.}
### {3407}{}{Alejo vs. the Mexicans.}
{3407}{}{阿列霍对墨西哥人。 -- Alejo vs. the Mexicans.}
### {3408}{}{Gold!}
{3408}{}{金 -- Gold!}
### {3409}{}{Henry Beamis.}
{3409}{}{亨利·比米斯。 -- Henry Beamis.}
### {3410}{}{Roadside cafe.}
{3410}{}{路边咖啡馆。 -- Roadside cafe.}
### {3411}{}{A crashed bomber.}
{3411}{}{一架坠毁的轰炸机。 -- A crashed bomber.}
### {3412}{}{Petro-Chico truck.}
{3412}{}{Petro Chico卡车。 -- Petro-Chico truck.}
### {3413}{}{The cry of silence.}
{3413}{}{沉默的呐喊。 -- The cry of silence.}
### {3414}{}{Night movie screening.}
{3414}{}{夜间电影放映。 -- Night movie screening.}
### {3415}{}{Flying Padre.}
{3415}{}{飞行教士。 -- Flying Padre.}
### {3416}{}{Snowfall.}
{3416}{}{雪花飘落。 -- Snowfall.}
### {3417}{}{Mobile fortress.}
{3417}{}{移动堡垒。 -- Mobile fortress.}
### {3418}{}{Legend City.}
{3418}{}{传奇之城。 -- Legend City.}
### {3419}{}{The Mexican runs away from the scolopendra.}
{3419}{}{墨西哥人逃离了scolopendra。 -- The Mexican runs away from the scolopendra.}

# Encounter Table 9 -- MEXI_M
### {3450}{}{Red Rider.}
{3450}{}{红色骑士。 -- Red Rider.}
### {3451}{}{Rockfall!}
{3451}{}{Rockfall！ -- Rockfall!}
### {3452}{}{A flock of mole rats.}
{3452}{}{一群鼹鼠。 -- A flock of mole rats.}
### {3453}{}{Giant scolopendra.}
{3453}{}{巨大的scolopendra。 -- Giant scolopendra.}
### {3454}{}{Mexican Army patrol.}
{3454}{}{墨西哥军队巡逻队。 -- Mexican Army patrol.}
### {3455}{}{A group of immigrants.}
{3455}{}{一群移民。 -- A group of immigrants.}
### {3456}{}{Gold!}
{3456}{}{金 -- Gold!}
### {3457}{}{Henry Beamis.}
{3457}{}{亨利·比米斯。 -- Henry Beamis.}
### {3458}{}{Roadside cafe.}
{3458}{}{路边咖啡馆。 -- Roadside cafe.}
### {3459}{}{The crashed bomber.}
{3459}{}{坠毁的轰炸机。 -- The crashed bomber.}
### {3460}{}{Petro-Chico truck.}
{3460}{}{Petro Chico卡车。 -- Petro-Chico truck.}
### {3461}{}{The cry of silence.}
{3461}{}{沉默的呐喊。 -- The cry of silence.}
### {3462}{}{Night movie screening.}
{3462}{}{夜间电影放映。 -- Night movie screening.}
### {3463}{}{Flying Padre.}
{3463}{}{飞行教士。 -- Flying Padre.}
### {3464}{}{Legend City.}
{3464}{}{传奇之城。 -- Legend City.}

# Encounter Table 10 -- CALF_D
### {3500}{}{Red Rider.}
{3500}{}{红色骑士。 -- Red Rider.}
### {3501}{}{Radioactive fog!}
{3501}{}{放射性雾！ -- Radioactive fog!}
### {3502}{}{A pack of rats.}
{3502}{}{一群老鼠。 -- A pack of rats.}
### {3503}{}{A group of radscorpions.}
{3503}{}{一群辐射蝎子。 -- A group of radscorpions.}
### {3504}{}{A few scavengers.}
{3504}{}{一些拾荒者。 -- A few scavengers.}
### {3505}{}{A traveler with a dog.}
{3505}{}{一个带着狗的旅行者。 -- A traveler with a dog.}
### {3506}{}{Gold!}
{3506}{}{金 -- Gold!}
### {3507}{}{Henry Beamis.}
{3507}{}{亨利·比米斯。 -- Henry Beamis.}
### {3508}{}{Roadside cafe.}
{3508}{}{路边咖啡馆。 -- Roadside cafe.}
### {3509}{}{The crashed bomber.}
{3509}{}{坠毁的轰炸机。 -- The crashed bomber.}
### {3510}{}{Petro-Chico truck.}
{3510}{}{Petro Chico卡车。 -- Petro-Chico truck.}
### {3511}{}{The cry of silence.}
{3511}{}{沉默的呐喊。 -- The cry of silence.}
### {3512}{}{Night movie screening.}
{3512}{}{夜间电影放映。 -- Night movie screening.}
### {3513}{}{Snowfall.}
{3513}{}{雪花飘落。 -- Snowfall.}
### {3514}{}{Lost Refuge.}
{3514}{}{丢失的避难所。 -- Lost Refuge.}
### {3515}{}{Mobile fortress.}
{3515}{}{移动堡垒。 -- Mobile fortress.}
### {3516}{}{Legend City.}
{3516}{}{传奇之城。 -- Legend City.}

# Encounter Table 11 -- PHNX_D
### {3550}{}{Red Rider.}
{3550}{}{红色骑士。 -- Red Rider.}
### {3551}{}{A pack of rats.}
{3551}{}{一群老鼠。 -- A pack of rats.}
### {3552}{}{Stray dogs.}
{3552}{}{流浪狗。 -- Stray dogs.}
### {3553}{}{The Los Panchos Gang.}
{3553}{}{洛斯潘乔斯帮。 -- The Los Panchos Gang.}
### {3554}{}{The Los Panchos Gang.}
{3554}{}{洛斯潘乔斯帮。 -- The Los Panchos Gang.}
### {3555}{}{The Los Panchos Gang.}
{3555}{}{洛斯潘乔斯帮。 -- The Los Panchos Gang.}
### {3556}{}{Bandits.}
{3556}{}{土匪。 -- Bandits.}
### {3557}{}{Bandits.}
{3557}{}{土匪。 -- Bandits.}
### {3558}{}{A group of civilians.}
{3558}{}{一群平民。 -- A group of civilians.}
### {3559}{}{Psychomaniac.}
{3559}{}{精神病患者。 -- Psychomaniac.}
### {3560}{}{Gangsters take out the debtor.}
{3560}{}{歹徒把债务人抓了出来。 -- Gangsters take out the debtor.}
### {3561}{}{Snowfall.}
{3561}{}{雪花飘落。 -- Snowfall.}
### {3562}{}{Lost Refuge.}
{3562}{}{丢失的避难所。 -- Lost Refuge.}
### {3563}{}{Legend City.}
{3563}{}{传奇之城。 -- Legend City.}

# Encounter Table 12 -- PHNX_M
### {3600}{}{Radioactive fog!}
{3600}{}{放射性雾！ -- Radioactive fog!}
### {3601}{}{A group of radmurts.}
{3601}{}{一群小狗。 -- A group of radmurts.}
### {3602}{}{The body of an unlucky marauder.}
{3602}{}{不幸的掠夺者的尸体。 -- The body of an unlucky marauder.}
### {3603}{}{A lone scavenger.}
{3603}{}{一个孤独的拾荒者。 -- A lone scavenger.}
### {3604}{}{The Mad Mr. Assistant.}
{3604}{}{疯狂的助理先生。 -- The Mad Mr. Assistant.}

# Encounter Table 13 -- ROAD_D
### {3650}{}{Red Rider.}
{3650}{}{红色骑士。 -- Red Rider.}
### {3651}{}{Body abandoned on the road.}
{3651}{}{尸体被遗弃在路上。 -- Body abandoned on the road.}
### {3652}{}{A pack of rats.}
{3652}{}{一群老鼠。 -- A pack of rats.}
### {3653}{}{A group of radscorpions.}
{3653}{}{一群辐射蝎子。 -- A group of radscorpions.}
### {3654}{}{Raiders.}
{3654}{}{突袭者。 -- Raiders.}
### {3655}{}{Raiders.}
{3655}{}{突袭者。 -- Raiders.}
### {3656}{}{Warriors of the road.}
{3656}{}{公路勇士。 -- Warriors of the road.}
### {3657}{}{Caravan.}
{3657}{}{大篷车 -- Caravan.}
### {3658}{}{The looted wagon.}
{3658}{}{被洗劫一空的马车。 -- The looted wagon.}
### {3659}{}{Highway man vs bounty hunters.}
{3659}{}{高速公路男子vs赏金猎人。 -- Highway man vs bounty hunters.}
### {3660}{}{The Lost Refuge.}
{3660}{}{失落的避难所。 -- The Lost Refuge.}
### {3661}{}{Legend City.}
{3661}{}{传奇之城。 -- Legend City.}

# Encounter Table 14 -- TUSN_D
### {3700}{}{Red Rider.}
{3700}{}{红色骑士。 -- Red Rider.}
### {3701}{}{A pack of rats.}
{3701}{}{一群老鼠。 -- A pack of rats.}
### {3702}{}{A group of radscorpions.}
{3702}{}{一群辐射蝎子。 -- A group of radscorpions.}
### {3703}{}{Raiders.}
{3703}{}{突袭者。 -- Raiders.}
### {3704}{}{Raiders.}
{3704}{}{突袭者。 -- Raiders.}
### {3705}{}{A scout robot.}
{3705}{}{侦察机器人。 -- A scout robot.}
### {3706}{}{The corpse of a runaway slave.}
{3706}{}{逃亡奴隶的尸体。 -- The corpse of a runaway slave.}
### {3707}{}{Cyberpsih.}
{3707}{}{Cyberpsih。 -- Cyberpsih.}

# Encounter Table 15 -- TUSN_M
### {3750}{}{Rockfall!}
{3750}{}{Rockfall！ -- Rockfall!}
### {3751}{}{A flock of mole rats.}
{3751}{}{一群鼹鼠。 -- A flock of mole rats.}
### {3752}{}{A pack of wolves.}
{3752}{}{一群狼。 -- A pack of wolves.}
### {3753}{}{Males divide the territory.}
{3753}{}{雄性瓜分领土。 -- Males divide the territory.}
### {3754}{}{Hermit.}
{3754}{}{隐士 -- Hermit.}
### {3755}{}{Cannibal on the hunt.}
{3755}{}{正在狩猎的食人族。 -- Cannibal on the hunt.}
### {3756}{}{Gold!}
{3756}{}{金 -- Gold!}
### {3757}{}{Henry Beamis.}
{3757}{}{亨利·比米斯。 -- Henry Beamis.}
### {3758}{}{Roadside cafe.}
{3758}{}{路边咖啡馆。 -- Roadside cafe.}
### {3759}{}{The crashed bomber.}
{3759}{}{坠毁的轰炸机。 -- The crashed bomber.}
### {3760}{}{Petro-Chico truck.}
{3760}{}{Petro Chico卡车。 -- Petro-Chico truck.}
### {3761}{}{The cry of silence.}
{3761}{}{沉默的呐喊。 -- The cry of silence.}
### {3762}{}{Night movie screening.}
{3762}{}{夜间电影放映。 -- Night movie screening.}
### {3763}{}{The Lost Refuge.}
{3763}{}{失落的避难所。 -- The Lost Refuge.}
### {3764}{}{Legend City.}
{3764}{}{传奇之城。 -- Legend City.}

# Encounter Table 16 -- INFN_D
### {3800}{}{Radioactive fog!}
{3800}{}{放射性雾！ -- Radioactive fog!}
### {3801}{}{A group of radmurts.}
{3801}{}{一群小狗。 -- A group of radmurts.}
### {3802}{}{Scavengers.}
{3802}{}{拾荒者。 -- Scavengers.}
### {3803}{}{The Rippers.}
{3803}{}{开膛手。 -- The Rippers.}
### {3804}{}{Agent USBP.}
{3804}{}{代理USBP。 -- Agent USBP.}
### {3805}{}{Harvey.}
{3805}{}{哈维。 -- Harvey.}

# Encounter Table 17 -- PORT_D
### {3850}{}{Red Rider.}
{3850}{}{红色骑士。 -- Red Rider.}
### {3851}{}{Dehydration!}
{3851}{}{脱水！ -- Dehydration!}
### {3852}{}{Giant ants.}
{3852}{}{巨型蚂蚁。 -- Giant ants.}
### {3853}{}{A swarm of mantises.}
{3853}{}{一群螳螂。 -- A swarm of mantises.}
### {3854}{}{A group of radscorpions.}
{3854}{}{一群辐射蝎子。 -- A group of radscorpions.}
### {3855}{}{The Brotherhood of Steel Patrol.}
{3855}{}{钢铁巡警兄弟会。 -- The Brotherhood of Steel Patrol.}

# Encounter Table 18 -- ISLD_D
### {3900}{}{A group of radmuravs explores the coast.}
{3900}{}{一群拉德穆拉夫人探索海岸。 -- A group of radmuravs explores the coast.}
### {3901}{}{Monster.}
{3901}{}{怪物 -- Monster.}
### {3902}{}{Body washed ashore.}
{3902}{}{尸体被冲上岸。 -- Body washed ashore.}
### {3903}{}{Fishermen.}
{3903}{}{渔民。 -- Fishermen.}
### {3904}{}{The body of the scout.}
{3904}{}{侦察兵的尸体。 -- The body of the scout.}
### {3905}{}{Bandits are torturing the clerk.}
{3905}{}{土匪正在折磨店员。 -- Bandits are torturing the clerk.}

# Encounter Table 19 -- ISLD_M
### {3950}{}{Rockfall!}
{3950}{}{Rockfall！ -- Rockfall!}
### {3951}{}{Radioactive fog!}
{3951}{}{放射性雾！ -- Radioactive fog!}
### {3952}{}{Rad-Ant group.}
{3952}{}{Rad-Ant小组。 -- Rad-Ant group.}
### {3953}{}{Monsters.}
{3953}{}{怪兽。 -- Monsters.}
### {3954}{}{Army robot.}
{3954}{}{军用机器人。 -- Army robot.}
### {3955}{}{Pilgrims.}
{3955}{}{朝圣者。 -- Pilgrims.}
### {3956}{}{Gold!}
{3956}{}{金 -- Gold!}
### {3957}{}{Henry Beamis.}
{3957}{}{亨利·比米斯。 -- Henry Beamis.}
### {3958}{}{Roadside cafe.}
{3958}{}{路边咖啡馆。 -- Roadside cafe.}
### {3959}{}{The crashed bomber.}
{3959}{}{坠毁的轰炸机。 -- The crashed bomber.}
### {3960}{}{Petro-Chico truck.}
{3960}{}{Petro Chico卡车。 -- Petro-Chico truck.}
### {3961}{}{The cry of silence.}
{3961}{}{沉默的呐喊。 -- The cry of silence.}
### {3962}{}{Night movie screening.}
{3962}{}{夜间电影放映。 -- Night movie screening.}
### {3963}{}{Flying Padre.}
{3963}{}{飞行教士。 -- Flying Padre.}
### {3964}{}{Legend City.}
{3964}{}{传奇之城。 -- Legend City.}

# Encounter Table 20 -- OCEAN_O
### {4000}{}{Radioactive fog!}
{4000}{}{放射性雾！ -- Radioactive fog!}
