#
# ?????????????????????????????????????????????????????????????????????????????
#
# Text labels and messages used in OPTIONS.C
#
# (These MUST match "text message" enumeration on the top of OPTIONS.C)
#
# ????????????????????????????????????????????????????????????????????????????? 

# ?Main option panel ?
#
# Buttons
### {0}{}{SAVE GAME}
{0}{}{保存游戏 -- SAVE GAME}
### {1}{}{LOAD GAME}
{1}{}{负载游戏 -- LOAD GAME}
### {2}{}{PREFERENCES}
{2}{}{首选项 -- PREFERENCES}
### {3}{}{EXIT GAME}
{3}{}{退出游戏 -- EXIT GAME}
### {4}{}{DONE}
{4}{}{完成 -- DONE}
#
# Preferences
#
### {100}{}{GAME PREFERENCES}
{100}{}{游戏偏好 -- GAME PREFERENCES}
### {101}{}{GAME DIFFICULTY}
{101}{}{游戏难度 -- GAME DIFFICULTY}
### {102}{}{COMBAT DIFFICULTY}
{102}{}{作战难度 -- COMBAT DIFFICULTY}
### {103}{}{VIOLENCE LEVEL}
{103}{}{暴力程度 -- VIOLENCE LEVEL}
### {104}{}{TARGET HIGHLIGHT}
{104}{}{目标亮点 -- TARGET HIGHLIGHT}
### {105}{}{COMBAT LOOKS}  # Was: BURNING GUYS
{105}{}{战斗表情 -- COMBAT LOOKS}
### {106}{}{COMBAT MESSAGES}
{106}{}{作战信息 -- COMBAT MESSAGES}
### {107}{}{COMBAT TAUNTS}
{107}{}{战斗嘲讽 -- COMBAT TAUNTS}
### {108}{}{LANGUAGE FILTER}
{108}{}{语言过滤器 -- LANGUAGE FILTER}
### {109}{}{RUNNING}
{109}{}{运行 -- RUNNING}
### {110}{}{SUBTITLES}
{110}{}{字幕 -- SUBTITLES}
### {111}{}{ITEM HIGHLIGHT}
{111}{}{项目突出显示 -- ITEM HIGHLIGHT}
### {112}{}{COMBAT SPEED}
{112}{}{战斗速度 -- COMBAT SPEED}
### {113}{}{TEXT DELAY}
{113}{}{文本延迟 -- TEXT DELAY}
### {114}{}{MASTER AUDIO VOLUME}
{114}{}{主音频音量 -- MASTER AUDIO VOLUME}
### {115}{}{MUSIC/MOVIE VOLUME}
{115}{}{音乐/电影音量 -- MUSIC/MOVIE VOLUME}
### {116}{}{SOUND EFFECTS VOLUME}
{116}{}{音效音量 -- SOUND EFFECTS VOLUME}
### {117}{}{SPEECH VOLUME}
{117}{}{语音音量 -- SPEECH VOLUME}
### {118}{}{BRIGHTNESS LEVEL}
{118}{}{亮度等级 -- BRIGHTNESS LEVEL}
### {119}{}{MOUSE SENSITIVITY}
{119}{}{鼠标灵敏度 -- MOUSE SENSITIVITY}
### {120}{}{DEFAULT}
{120}{}{违约 -- DEFAULT}
### {121}{}{CANCEL}
{121}{}{取消 -- CANCEL}
### {122}{}{Affect player speed}
{122}{}{影响玩家速度 -- Affect player speed}
### {123}{}{Organizer speech}
{123}{}{主办单位致辞 -- Organizer speech}
#
# Label text
#
### {201}{}{On}             # 1
{201}{}{在…上 -- On}
### {202}{}{Off}            # 2
{202}{}{关 -- Off}
### {203}{}{Easy}           #  1
{203}{}{容易的 -- Easy}
### {204}{}{Normal}         #  2
{204}{}{典型的 -- Normal}
### {205}{}{Hard}           #  3
{205}{}{坚固的 -- Hard}
### {206}{}{Wimpy}          # 1
{206}{}{小淘气 -- Wimpy}
### {207}{}{Normal}         # 2
{207}{}{典型的 -- Normal}
### {208}{}{Rough}          # 3
{208}{}{粗糙的 -- Rough}
### {209}{}{Normal}         #  1
{209}{}{典型的 -- Normal}
### {210}{}{Fastest}        #  2
{210}{}{最快的 -- Fastest}
### {211}{}{Verbose}        # 1
{211}{}{冗长的 -- Verbose}
### {212}{}{Brief}          # 2
{212}{}{简明的 -- Brief}
### {213}{}{Targeting Only}
{213}{}{仅针对目标 -- Targeting Only}
### {214}{}{None}           # 1
{214}{}{没有一个 -- None}
### {215}{}{Minimal}        # 2
{215}{}{最小的 -- Minimal}
### {216}{}{Maximum Blood}  # 3
{216}{}{最大血液量 -- Maximum Blood}
### {217}{}{Slow}           #  1
{217}{}{缓慢的 -- Slow}
### {218}{}{Faster}         #  2
{218}{}{更快 -- Faster}
### {219}{}{Always}
{219}{}{总是 -- Always}
### {220}{}{Lots}
{220}{}{很多 -- Lots}
### {221}{}{Quiet}          # 1
{221}{}{轻声的 -- Quiet}
### {222}{}{Loud}           # 2
{222}{}{大声的 -- Loud}
### {223}{}{Brighter}
{223}{}{更明亮 -- Brighter}
### {224}{}{Wide}
{224}{}{宽的 -- Wide}
#
# Pause window
#
### {300}{}{DONE}
{300}{}{完成 -- DONE}
### {301}{}{PAUSED}
{301}{}{暂停 -- PAUSED}
#
# Demo versions only
#
### {1000}{}{Sorry, the preferences menu is not}  # 1
{1000}{}{抱歉，首选项菜单没有 -- Sorry, the preferences menu is not}
### {1001}{}{available in the demo version.}      # 2
{1001}{}{在演示版本中提供。 -- available in the demo version.}
