#{100}{}{You see a caravan merchant.}
{100}{}{你看到一个商队商人。 -- You see a caravan merchant.}
#{101}{}{You see a caravan leader.}
{101}{}{你看到一个商队队长。 -- You see a caravan leader.}
#{102}{}{Thanks, stranger. I'll see you in Black Rock!}
{102}{}{谢谢，陌生人。我们在黑岩见！ -- Thanks, stranger. I'll see you in Black Rock!}
#{103}{}{Keep it tight! They're close!}
{103}{}{抓紧点！他们很接近！ -- Keep it tight! They're close!}
#{110}{}{Didn't expect to see anyone else in here. Let me guess - you were walking along, minding your own business, when some ugly, dickless raider motherfucker with a face like a gecko turd, a voice like a wet rat, and the smell of both put together popped out of nowhere with a half-dozen of his raider friends, put a gun to your head, and told you to get in here and get us out. Am I close?}
{110}{}{没想到这里还有其他人。让我猜猜看——你正一边走，一边管着自己的事，突然一个丑陋的，没有胆量的掠夺者混蛋，脸像壁虎屎，声音像湿老鼠，和他的六个掠夺者朋友不知从哪里冒出来的气味，用枪指着你的头，叫你进来把我们弄出去。我接近了吗？ -- Didn't expect to see anyone else in here. Let me guess - you were walking along, minding your own business, when some ugly, dickless raider motherfucker with a face like a gecko turd, a voice like a wet rat, and the smell of both put together popped out of nowhere with a half-dozen of his raider friends, put a gun to your head, and told you to get in here and get us out. Am I close?}
#{111}{}{More or less, yeah.}
{111}{}{或多或少，是的。 -- More or less, yeah.}
#{112}{}{Raiders? There's no raiders out there!}
{112}{}{袭击者？外面没有袭击者！ -- Raiders? There's no raiders out there!}
#{113}{}{Those sneaking, spineless sons of bitches! Welcome to the trap, stranger.}
{113}{}{那些鬼鬼祟祟，没骨气的狗娘养的！欢迎来到陷阱，陌生人。 -- Those sneaking, spineless sons of bitches! Welcome to the trap, stranger.}
#{114}{}{Trap?}
{114}{}{陷阱？ -- Trap?}
#{115}{}{Oh, is that right, now? You were just passing by and decided to walk into some dank cave for no reason at all, huh?}
{115}{}{哦，现在是这样吗？你只是路过，无缘无故地决定走进一个潮湿的洞穴，是吗？ -- Oh, is that right, now? You were just passing by and decided to walk into some dank cave for no reason at all, huh?}
#{116}{}{I've been on my feet all day. I just wanted somewhere to take a nap.}
{116}{}{我已经站了一整天了。我只是想找个地方小睡一会儿。 -- I've been on my feet all day. I just wanted somewhere to take a nap.}
#{117}{}{I was being sarcastic. The raiders are right outside.}
{117}{}{我是在讽刺。袭击者就在外面。 -- I was being sarcastic. The raiders are right outside.}
#{118}{}{Excuse me if I find that pretty goddamn unlikely! But alright - here's what we're gonna do. We're gonna walk outside, you right here beside me, and we'll see what happens. And if you're doing anything funny, well - what I do to you then is gonna be *hilarious*. Come and get me when you're ready to go.}
{118}{}{如果我觉得这不太可能，请原谅！但好吧-我们要这么做。我们出去走走，你就在我身边，我们看看会发生什么。如果你做了什么有趣的事，那么-我对你所做的一切都会是“搞笑的”。准备好了就来接我。 -- Excuse me if I find that pretty goddamn unlikely! But alright - here's what we're gonna do. We're gonna walk outside, you right here beside me, and we'll see what happens. And if you're doing anything funny, well - what I do to you then is gonna be *hilarious*. Come and get me when you're ready to go.}
#{119}{}{Fine, I'll be back.}
{119}{}{好的，我会回来的。 -- Fine, I'll be back.}
#{120}{}{First, tell me what happened here.}
{120}{}{首先，告诉我这里发生了什么。 -- First, tell me what happened here.}
#{121}{}{What we've got here is a goddamn clusterfuck. The other exit's blocked off, we're running low on supplies, and worst of all, I'm behind schedule. I fucking HATE showing up late! It's do or die time, now, and I don't plan on dying. How do we get the fuck out of here?}
{121}{}{我们这里有一堆该死的东西。另一个出口被封锁了，我们的补给不足，最糟糕的是，我的进度落后了。我讨厌迟到！现在是该死还是该死的时候了，我不打算死。我们他妈的怎么离开这里？ -- What we've got here is a goddamn clusterfuck. The other exit's blocked off, we're running low on supplies, and worst of all, I'm behind schedule. I fucking HATE showing up late! It's do or die time, now, and I don't plan on dying. How do we get the fuck out of here?}
#{122}{}{How did this happen?}
{122}{}{这是怎么发生的？ -- How did this happen?}
#{123}{}{Let me think.}
{123}{}{让我想想。 -- Let me think.}
#{124}{}{Come up with any ideas yet, stranger?}
{124}{}{有什么想法吗，陌生人？ -- Come up with any ideas yet, stranger?}
#{125}{}{We were coming up from Reno to pick up some gecko skins. Coming up on the mountains, something didn't feel right. We busted out the binoculars to find, lo and behold, the raiders hadn't even put out their campfires. Pure amateur hour, I said to myself. Fortunately, I knew a cave that cut right through the side of the mountain. We'd just have to take the caravan through it and out the other side, and the raiders'd never even know we were there. Clever me, huh?}
{125}{}{我们从里诺过来取些壁虎皮。到了山上，感觉有些不对劲。我们拿出望远镜去发现，瞧，袭击者连营火都没熄灭。纯粹的业余时间，我对自己说。幸运的是，我知道一个山洞正好穿过山的一侧。我们只要带着商队穿过它，从另一边出去，袭击者根本不知道我们在那里。聪明的我，哈？ -- We were coming up from Reno to pick up some gecko skins. Coming up on the mountains, something didn't feel right. We busted out the binoculars to find, lo and behold, the raiders hadn't even put out their campfires. Pure amateur hour, I said to myself. Fortunately, I knew a cave that cut right through the side of the mountain. We'd just have to take the caravan through it and out the other side, and the raiders'd never even know we were there. Clever me, huh?}
#{126}{}{What happened next?}
{126}{}{接下来发生了什么？ -- What happened next?}
#{127}{}{Turns out they knew about the cave too. Fuck, I walked right into it! Just after we passed through, they detonated the cave behind us and sealed off the tunnel. There's no way in hell we're getting through that rubble. I don't know if they planned it from the beginning or they just got lucky, but it don't really matter now. There's only one exit - all they gotta do is wait. Either we come out and they shoot us or we sit here and starve.}
{127}{}{原来他们也知道那个洞。妈的，我直接就进去了！我们刚通过，他们就引爆了我们身后的山洞，封锁了隧道。我们根本不可能穿过那片废墟。我不知道他们是从一开始就计划好了，还是运气好，但现在已经不重要了。只有一个出口-他们要做的就是等待。要么我们出来，他们开枪打死我们，要么我们坐在这里挨饿。 -- Turns out they knew about the cave too. Fuck, I walked right into it! Just after we passed through, they detonated the cave behind us and sealed off the tunnel. There's no way in hell we're getting through that rubble. I don't know if they planned it from the beginning or they just got lucky, but it don't really matter now. There's only one exit - all they gotta do is wait. Either we come out and they shoot us or we sit here and starve.}
#{128}{}{That's an unpleasant story.}
{128}{}{那是一个令人不快的故事。 -- That's an unpleasant story.}
#{129}{}{The raiders are all dead. You can come out now.}
{129}{}{袭击者都死了。你现在可以出来了。 -- The raiders are all dead. You can come out now.}
#{130}{}{Alright, let's take a look. But if you're fucking with me...}
{130}{}{好吧，我们来看看。但如果你在耍我。。。 -- Alright, let's take a look. But if you're fucking with me...}
#{131}{}{[Wait]}
{131}{}{[等等] -- [Wait]}
#{132}{}{God DAMN, son! You did all that? Motherfucking masterful work! Now we can finally get out of this place. Find me in Black Rock - the beer's on me!}
{132}{}{他妈的，儿子！都是你干的？他妈的杰作！现在我们终于可以离开这里了。在黑岩找到我-我请客！ -- God DAMN, son! You did all that? Motherfucking masterful work! Now we can finally get out of this place. Find me in Black Rock - the beer's on me!}
#{133}{}{I'll see you there.}
{133}{}{到时候见。 -- I'll see you there.}
#{134}{}{The raiders must have run off. We should leave before they come back.}
{134}{}{袭击者一定逃跑了。我们应该在他们回来之前离开。 -- The raiders must have run off. We should leave before they come back.}
#{135}{}{Sure, let's go.}
{135}{}{当然，我们走吧。 -- Sure, let's go.}
#{136}{}{I just need to, uh, take a leak first. You go on ahead.}
{136}{}{我只需要，呃，先去小便一下。你去吧。 -- I just need to, uh, take a leak first. You go on ahead.}
#{1102}{}{Thanks, stranger. I'll see you in Black Rock!}
{1102}{}{谢谢，陌生人。我们在黑岩见！ -- Thanks, stranger. I'll see you in Black Rock!}
#{1115}{}{Oh, is that right, now? You were just passing by and decided to walk into some dank cave for no reason at all, huh?}
{1115}{}{哦，现在是这样吗？你只是路过，无缘无故地决定走进一个潮湿的洞穴，是吗？ -- Oh, is that right, now? You were just passing by and decided to walk into some dank cave for no reason at all, huh?}
#{1132}{}{God DAMN, girl! You did all that? Motherfucking masterful work! Now we can finally get out of this place. Find me in Black Rock - the beer's on me!}
{1132}{}{妈的，女孩！都是你干的？他妈的杰作！现在我们终于可以离开这里了。在黑岩找到我-我请客！ -- God DAMN, girl! You did all that? Motherfucking masterful work! Now we can finally get out of this place. Find me in Black Rock - the beer's on me!}
