#{100}{}{You have carefully studied the data on the memory card and put it on your Pip-Boy.}
{100}{}{你仔细研究了存储卡上的数据，并把它放在你的皮普男孩。 -- You have carefully studied the data on the memory card and put it on your Pip-Boy.}
#{101}{}{Wow, these guys were risking a lot.}
{101}{}{哇，这些家伙冒了很大的风险。 -- Wow, these guys were risking a lot.}
#{102}{}{Your knowledge in programming is not enough to decrypt the memory card.}
{102}{}{你的编程知识不足以解密存储卡。 -- Your knowledge in programming is not enough to decrypt the memory card.}
#{103}{}{You have already received all the necessary data from this memory card.}
{103}{}{您已经从该存储卡接收到所有必要的数据。 -- You have already received all the necessary data from this memory card.}
