#{100}{}{}
{100}{}{ -- }
#{101}{}{You left the fight. By now, the caravaneers are all dead.}
{101}{}{你离开了战斗。现在，商队都死了。 -- You left the fight. By now, the caravaneers are all dead.}
#{102}{}{You left the fight. By now, what's left of the caravan has returned to New Reno.}
{102}{}{你离开了战斗。现在，大篷车上剩下的东西已经回到了新雷诺。 -- You left the fight. By now, what's left of the caravan has returned to New Reno.}
#{103}{}{You left the fight. Thanks to you, the caravan made it to Black Rock.}
{103}{}{你离开了战斗。多亏了你，商队才到达黑岩。 -- You left the fight. Thanks to you, the caravan made it to Black Rock.}
