#{100}{}{You see a bandit.}
{100}{}{你看见一个强盗。 -- You see a bandit.}
#{101}{}{You see a marauder.}
{101}{}{你看到一个掠夺者。 -- You see a marauder.}
#{102}{}{You see a robber.}
{102}{}{你看见一个强盗。 -- You see a robber.}
#{103}{}{You see a convict.}
{103}{}{你看到一个罪犯。 -- You see a convict.}
#{104}{}{You see a rogue.}
{104}{}{你看到一个流氓。 -- You see a rogue.}
#{105}{}{You see a runaway prisoner in gear stolen from the guard.}
{105}{}{你看到一个逃跑的囚犯，穿着从警卫那里偷来的装备。 -- You see a runaway prisoner in gear stolen from the guard.}
#{200}{}{Surrender!}
{200}{}{投降！ -- Surrender!}
#{201}{}{Your money or your life.}
{201}{}{你的钱还是你的命。 -- Your money or your life.}
#{202}{}{This is a stick up.}
{202}{}{这是一个大棒。 -- This is a stick up.}
#{203}{}{Give me all your valuables.}
{203}{}{把你所有的贵重物品都给我。 -- Give me all your valuables.}
#{204}{}{I'll get you!}
{204}{}{我会抓住你的！ -- I'll get you!}
#{205}{}{Put yer hands up.}
{205}{}{把手举起来。 -- Put yer hands up.}
#{206}{}{Stick 'em up.}
{206}{}{把它们粘起来。 -- Stick 'em up.}
#{207}{}{Don't panic; this will be over in a minute.}
{207}{}{别慌，马上就结束了。 -- Don't panic; this will be over in a minute.}
#{208}{}{Let's see those hands there.}
{208}{}{让我们看看那些手。 -- Let's see those hands there.}
#{209}{}{Cover me, fellas.}
{209}{}{掩护我，伙计们。 -- Cover me, fellas.}
#{210}{}{Don't make this hard on yourself.}
{210}{}{别让自己难受。 -- Don't make this hard on yourself.}
#{211}{}{Hand over the loot.}
{211}{}{交出赃物。 -- Hand over the loot.}
#{212}{}{Get 'em, boys.}
{212}{}{抓住他们，孩子们。 -- Get 'em, boys.}
#{213}{}{Kill them all.}
{213}{}{把他们都杀了。 -- Kill them all.}
#{214}{}{I promise to make your death quick.}
{214}{}{我保证让你快点死。 -- I promise to make your death quick.}
#{215}{}{Reach for the sky.}
{215}{}{伸向天空。 -- Reach for the sky.}
#{216}{}{Don't move.}
{216}{}{别动。 -- Don't move.}
