#{100}{}{You see a scarred traveler.}
{100}{}{你看到一个伤痕累累的旅行者。 -- You see a scarred traveler.}
#{101}{}{You see the merchant's guard.}
{101}{}{你看到商人的守卫了。 -- You see the merchant's guard.}
#{200}{}{No drawn weapons near the boss.}
{200}{}{在老大附近禁止携带武器。 -- No drawn weapons near the boss.}
#{201}{}{No one comes to the boss armed.}
{201}{}{没有人持枪来找老板。 -- No one comes to the boss armed.}
#{202}{}{Put your weapon away before we shoot you.}
{202}{}{在我们开枪之前把你的武器收起来。 -- Put your weapon away before we shoot you.}
#{203}{}{Put 'em away or get away.}
{203}{}{把它们收起来或者走开。 -- Put 'em away or get away.}
#{250}{}{You were warned - now you will pay.}
{250}{}{你被警告了-现在你要付出代价。 -- You were warned - now you will pay.}
#{300}{}{Talk to the boss, he'll set you up right.}
{300}{}{跟老板说，他会给你安排好的。 -- Talk to the boss, he'll set you up right.}
#{301}{}{I take my job seriously. Mess with the boss, and you die.}
{301}{}{我认真对待我的工作。和老板乱搞，你就死定了。 -- I take my job seriously. Mess with the boss, and you die.}
#{302}{}{The boss is a good guy for the most part.}
{302}{}{老板在很大程度上是个好人。 -- The boss is a good guy for the most part.}
#{303}{}{Don't even think of stealing from the boss.}
{303}{}{别想偷老板的东西。 -- Don't even think of stealing from the boss.}
