#{100}{}{These will fetch a good price at market.}
{100}{}{这些将在市场上卖个好价钱。 -- These will fetch a good price at market.}
#{101}{}{Try not to damage the merchandise.}
{101}{}{尽量不要损坏商品。 -- Try not to damage the merchandise.}
#{102}{}{You'll make a spirited slave.}
{102}{}{你会成为一个精力充沛的奴隶。 -- You'll make a spirited slave.}
#{103}{}{This is not good.}
{103}{}{这不好。 -- This is not good.}
#{104}{}{Retreat!}
{104}{}{撤退！ -- Retreat!}
#{105}{}{Maybe I'll sell furniture instead.}
{105}{}{也许我会改卖家具。 -- Maybe I'll sell furniture instead.}
#{106}{}{Fellow slavers should not attack one another.}
{106}{}{奴隶同胞不应该互相攻击。 -- Fellow slavers should not attack one another.}
#{107}{}{The guild will hear of this!}
{107}{}{公会一定会知道的！ -- The guild will hear of this!}
#{108}{}{What are you doing?}
{108}{}{你在做什么？ -- What are you doing?}
#{109}{}{Any luck?}
{109}{}{有什么进展吗？ -- Any luck?}
#{110}{}{Find any good slaves?}
{110}{}{找到好奴隶了吗？ -- Find any good slaves?}
#{111}{}{We're looking for new stock.}
{111}{}{我们正在寻找新的存货。 -- We're looking for new stock.}
#{112}{}{This is our territory.}
{112}{}{这是我们的地盘。 -- This is our territory.}
