#{100}{}{You see a crane.}
{100}{}{你看到一个起重机。 -- You see a crane.}
#{101}{}{You see a rusted crane. You don't expect much.}
{101}{}{你看到一只生锈的起重机。你没什么期望。 -- You see a rusted crane. You don't expect much.}
#{102}{}{The chain is in no condition to be used. You'll have to replace it with something similar.}
{102}{}{链条处于不能使用的状态。你必须用类似的东西来代替它。 -- The chain is in no condition to be used. You'll have to replace it with something similar.}
#{103}{}{This crane could probably serve once more, but it has no chain.}
{103}{}{这台起重机可能还能再工作一次，但它没有链条。 -- This crane could probably serve once more, but it has no chain.}
#{104}{}{You replaced the chain with a rope. Should be enough for light loads.}
{104}{}{你用绳子代替了链条。应该足够轻载。 -- You replaced the chain with a rope. Should be enough for light loads.}
#{105}{}{You've already replaced the chain.}
{105}{}{你已经更换了链条。 -- You've already replaced the chain.}
#{106}{}{You don't need it anymore. Leave it to rust in peace.}
{106}{}{你不再需要它了。让它安静地生锈。 -- You don't need it anymore. Leave it to rust in peace.}
#{107}{}{Using the crane you've erected a garbage pyramid by the garage wall.}
{107}{}{你用起重机在车库的墙上竖起了一个垃圾金字塔。 -- Using the crane you've erected a garbage pyramid by the garage wall.}
