#{100}{}{This device generates the force field. If you destroy or deactivate it, then the field will vanish.}
{100}{}{这个装置产生力场。如果你摧毁或取消激活它，那么能量场就会消失。 -- This device generates the force field. If you destroy or deactivate it, then the field will vanish.}
#{101}{}{This device were generating the force field. Now it doesn't work.}
{101}{}{这个装置产生了力场。现在不行了。 -- This device were generating the force field. Now it doesn't work.}
#{102}{}{This skill is useless here.}
{102}{}{这技能在这里是没有用的。 -- This skill is useless here.}
#{103}{}{You failed to deactivate the device.}
{103}{}{您未能停用设备。 -- You failed to deactivate the device.}
#{104}{}{The generator no longer produces the field.}
{104}{}{发电机不再产生磁场。 -- The generator no longer produces the field.}
#{105}{}{It won't help here.}
{105}{}{在这里没用。 -- It won't help here.}
