#{100}{}{You see a skinny boy.}
{100}{}{你看到一个瘦男孩。 -- You see a skinny boy.}
#{101}{}{It's just an ordinary boy.}
{101}{}{只是个普通的男孩。 -- It's just an ordinary boy.}
#{102}{}{My mommy doesn't let me talk to strangers.}
{102}{}{我妈妈不让我和陌生人说话。 -- My mommy doesn't let me talk to strangers.}
#{103}{}{ }
{103}{}{  --  }
#{110}{}{Thank you, at least I now won't be so worried. But still I feel sorry for my dog...}
{110}{}{谢谢，至少我现在不会那么担心了。但我仍然为我的狗感到难过。。。 -- Thank you, at least I now won't be so worried. But still I feel sorry for my dog...}
#{111}{}{Thank you, I now know what happened to my dog... My dad will *kill* him! Honestly!}
{111}{}{谢谢，我现在知道我的狗怎么了。。。我爸爸会杀了他的！说真的？ -- Thank you, I now know what happened to my dog... My dad will *kill* him! Honestly!}
#{112}{}{[Frowning, looking away from you]}
{112}{}{[皱眉，看向别处] -- [Frowning, looking away from you]}
#{113}{}{Okay, boy, it's all over.}
{113}{}{好了，孩子，一切都结束了。 -- Okay, boy, it's all over.}
#{120}{}{(You see a boy walking among the leaves)}
{120}{}{（你看见一个男孩在树叶间散步） -- (You see a boy walking among the leaves)}
#{121}{}{Hey, what are you doing in such a dubious deserted place?}
{121}{}{嘿，你在这么荒芜的地方干什么？ -- Hey, what are you doing in such a dubious deserted place?}
#{122}{}{[Leave him]}
{122}{}{[离开他] -- [Leave him]}
#{123}{}{I'm looking for my doggy... Have you seen her? She has a collar and a white tag...}
{123}{}{我在找我的狗。。。你见过她吗？她有一个衣领和一个白色的标签。。。 -- I'm looking for my doggy... Have you seen her? She has a collar and a white tag...}
#{124}{}{No, I haven't. Tell me more, maybe I'll see her!}
{124}{}{不，我没有。告诉我更多，也许我会见到她！ -- No, I haven't. Tell me more, maybe I'll see her!}
#{125}{}{No, I haven't.}
{125}{}{不，我没有。 -- No, I haven't.}
#{126}{}{She's medium-sized, gray, with white spot on her chest. We always kept her chained, but she broke up and ran away somewhere. She wears a collar with attached tag that has her name. I miss her so much... Find her please! Please!!!}
{126}{}{她中等身材，灰色，胸部有白斑。我们总是把她拴在铁链上，但她分手了，跑掉了。她戴着一个带标签的项圈，上面有她的名字。我非常想念她。。。请找到她！拜托！！！ -- She's medium-sized, gray, with white spot on her chest. We always kept her chained, but she broke up and ran away somewhere. She wears a collar with attached tag that has her name. I miss her so much... Find her please! Please!!!}
#{127}{}{Alright-alright, I'll try. Do you have any ideas where did she run to?}
{127}{}{好吧，我试试。你知道她跑到哪里去了吗？ -- Alright-alright, I'll try. Do you have any ideas where did she run to?}
#{128}{}{Alright-alright, I'll try but can't promise anything.}
{128}{}{好吧，好吧，我会努力的，但我不能保证任何事。 -- Alright-alright, I'll try but can't promise anything.}
#{129}{}{I don't know... I afraid if she's got eaten! These are those dirty men from the slums! They always eat dogs! Maybe it's them? Look for her! Please! She's gone for two days! Please! I'm so afraid!}
{129}{}{我不知道。。。我怕她被吃了！这些是贫民窟里的那些肮脏的人！他们总是吃狗！也许是他们？去找她！拜托！她已经走了两天了！拜托！我好害怕！ -- I don't know... I afraid if she's got eaten! These are those dirty men from the slums! They always eat dogs! Maybe it's them? Look for her! Please! She's gone for two days! Please! I'm so afraid!}
#{130}{}{Nevermind, I'll look for her.}
{130}{}{别担心，我会去找她的。 -- Nevermind, I'll look for her.}
#{131}{}{Where are you...}
{131}{}{你在哪里。。。 -- Where are you...}
#{132}{}{Hey doggie, come!}
{132}{}{嘿，小狗，过来！ -- Hey doggie, come!}
#{133}{}{*Whistles*}
{133}{}{*口哨声* -- *Whistles*}
#{134}{}{Please come back!}
{134}{}{请回来！ -- Please come back!}
#{135}{}{I want you to return so much!}
{135}{}{我太想你回来了！ -- I want you to return so much!}
#{136}{}{I'm missing you so much, please come back!}
{136}{}{我好想你，请回来！ -- I'm missing you so much, please come back!}
#{137}{}{*wipes tears*}
{137}{}{*擦干眼泪* -- *wipes tears*}
#{150}{}{Did you find her?!!}
{150}{}{你找到她了吗？！！ -- Did you find her?!!}
#{151}{}{Sorry kid, but your dog went wild and attacked me. I had to kill her.}
{151}{}{对不起，孩子，你的狗发疯了，攻击了我。我不得不杀了她。 -- Sorry kid, but your dog went wild and attacked me. I had to kill her.}
#{152}{}{Sorry but your dog is dead. Someone in the slums have already digested her in his stomachs.}
{152}{}{对不起，你的狗死了。贫民窟里有人已经把她从肚子里消化了。 -- Sorry but your dog is dead. Someone in the slums have already digested her in his stomachs.}
#{153}{}{Sorry, didn't find her so far.}
{153}{}{抱歉，到目前为止还没找到她。 -- Sorry, didn't find her so far.}
#{154}{}{[Kid has changed in his face] But... It cannot be! [it seems like he's about to cry]}
{154}{}{[孩子脸色变了]但是。。。不可能！[他好像要哭了] -- [Kid has changed in his face] But... It cannot be! [it seems like he's about to cry]}
#{155}{}{You see, some of the most unfortunate, have to survive somehow. He maybe didn't want to eat your dog, but he had to. Sorry kid, but there's nothing more I can help you with.}
{155}{}{你看，一些最不幸的人，不得不以某种方式生存下来。他也许不想吃你的狗，但他不得不吃。对不起，孩子，我没什么能帮你的了。 -- You see, some of the most unfortunate, have to survive somehow. He maybe didn't want to eat your dog, but he had to. Sorry kid, but there's nothing more I can help you with.}
#{156}{}{WHAT?! No way!!! My doggy was normal! It could not be her! It wasn't her! No!}
{156}{}{什么？！不可能！！！我的狗很正常！不可能是她！不是她！不！ -- WHAT?! No way!!! My doggy was normal! It could not be her! It wasn't her! No!}
#{157}{}{Unfortunately, it was her. Apparently, she sniffed with the pack, and wild instincts leaped into her. Here's dog tag from her collar. Is it her tag?}
{157}{}{不幸的是，是她。显然，她用背包嗅了嗅，狂野的本能跃进了她的体内。这是她项圈上的狗标签。是她的标签吗？ -- Unfortunately, it was her. Apparently, she sniffed with the pack, and wild instincts leaped into her. Here's dog tag from her collar. Is it her tag?}
#{158}{}{Apparently, you're right. It might be other dog. I'll continue the searching.}
{158}{}{显然，你是对的。可能是另一只狗。我会继续搜寻的。 -- Apparently, you're right. It might be other dog. I'll continue the searching.}
#{159}{}{[Kid has changed in his face] Yes... It's... Hers... [sobs and begins to cry silently]}
{159}{}{[孩子脸色变了]是的。。。这是。。。她的。。。[抽泣着开始无声地哭泣] -- [Kid has changed in his face] Yes... It's... Hers... [sobs and begins to cry silently]}
#{160}{}{COme on now, pull yourself together! Sorry about the dog, but if she ran away, then she was happy there. Maybe she was tired of sitting on a chain. Imagine, how much she would suffer, if she continued to live chained?}
{160}{}{快点，振作起来！很抱歉那条狗，但如果她跑掉了，那她在那儿就很开心。也许她厌倦了坐在铁链上。想象一下，如果她继续被锁链锁住，她会遭受多大的痛苦？ -- COme on now, pull yourself together! Sorry about the dog, but if she ran away, then she was happy there. Maybe she was tired of sitting on a chain. Imagine, how much she would suffer, if she continued to live chained?}
#{161}{}{[Leave him]}
{161}{}{[离开他] -- [Leave him]}
#{162}{}{Yes?.. Really?.. [wipes tears with hand] Well, it's better for her to live in heavens then!}
{162}{}{对？。。真正地？。。[用手擦眼泪]好吧，那她最好住在天堂里！ -- Yes?.. Really?.. [wipes tears with hand] Well, it's better for her to live in heavens then!}
#{163}{}{Yes, the great kennel in heavens! She's alright there. And you stay firm before the problems, and not dissolve! Understood? Now go, wash your face and don't cry no more.}
{163}{}{是的，天堂里的大狗窝！她在那里很好。你在问题面前要坚定，不要解散！理解？去吧，洗脸，别再哭了。 -- Yes, the great kennel in heavens! She's alright there. And you stay firm before the problems, and not dissolve! Understood? Now go, wash your face and don't cry no more.}
#{164}{}{Thanks...}
{164}{}{谢谢。。。 -- Thanks...}
#{165}{}{Hey, nevermind! Bye!}
{165}{}{嘿，别客气！再见！ -- Hey, nevermind! Bye!}
#{166}{}{[It seems that your words didn't help much and the kid keeps crying more]}
{166}{}{[看来你的话帮不了什么忙，孩子哭得更厉害了] -- [It seems that your words didn't help much and the kid keeps crying more]}
#{167}{}{[Leave him in pain and loneliness]}
{167}{}{[让他在痛苦和孤独中] -- [Leave him in pain and loneliness]}
#{1124}{}{No, I haven't. Tell me more, maybe I'll see her!}
{1124}{}{不，我没有。告诉我更多，也许我会见到她！ -- No, I haven't. Tell me more, maybe I'll see her!}
#{1125}{}{No, I haven't.}
{1125}{}{不，我没有。 -- No, I haven't.}
#{1153}{}{Sorry, didn't find her so far.}
{1153}{}{抱歉，到目前为止还没找到她。 -- Sorry, didn't find her so far.}
