#{100}{}{This is Steven Quok.}
{100}{}{我是史蒂文·库克。 -- This is Steven Quok.}
#{101}{}{You see a weapon trader Steven Quok.}
{101}{}{你看到一个军火商史蒂文·库克。 -- You see a weapon trader Steven Quok.}
#{109}{}{Is there something else?}
{109}{}{还有别的事吗？ -- Is there something else?}
#{110}{}{Hello wanderer! Don't pass by Quok's family business! We always happy with new visitors and won't let you go without some excellent goodies! Check out my new weapon stock. Maybe you'll find something fitting your holster.}
{110}{}{你好，流浪者！别错过库克的家族事业！我们对新来的客人总是很满意，不会让你没有好东西就走的！看看我的新武器。也许你会找到适合你枪套的东西。 -- Hello wanderer! Don't pass by Quok's family business! We always happy with new visitors and won't let you go without some excellent goodies! Check out my new weapon stock. Maybe you'll find something fitting your holster.}
#{111}{}{What a cold-blooded move! But sorry, I have to raise the price since some bastard just robbed us...}
{111}{}{多么冷血的举动！但是对不起，我必须提高价格，因为有个混蛋刚刚抢劫了我们。。。 -- What a cold-blooded move! But sorry, I have to raise the price since some bastard just robbed us...}
#{112}{}{[Buy weapon]}
{112}{}{[购买武器] -- [Buy weapon]}
#{113}{}{Hey! I just saw someone jumping into your yard! I think that was the thief!}
{113}{}{嘿！我刚看见有人跳进你的院子！我想那是小偷！ -- Hey! I just saw someone jumping into your yard! I think that was the thief!}
#{114}{}{There's some poor fellow who can't find a job. Maybe you could make use of him somewhere in a storeroom? He won't ask much...}
{114}{}{有个可怜的家伙找不到工作。也许你可以在储藏室里利用他？他不会要求太多。。。 -- There's some poor fellow who can't find a job. Maybe you could make use of him somewhere in a storeroom? He won't ask much...}
#{115}{}{Don't need it, thanks.}
{115}{}{不用了，谢谢。 -- Don't need it, thanks.}
#{116}{}{Job you say? Well, I can think something out. Not for kid-gloves.  Tell him to visit me, we'll talk.}
{116}{}{你说的工作？嗯，我能想出来。不是给小手套的。叫他来看我，我们谈谈。 -- Job you say? Well, I can think something out. Not for kid-gloves.  Tell him to visit me, we'll talk.}
#{117}{}{Alright!}
{117}{}{好吧！ -- Alright!}
#{118}{}{You *sure* you don't need anything else?}
{118}{}{你确定你不需要其他东西？ -- You *sure* you don't need anything else?}
#{119}{}{Let's take a look again...}
{119}{}{让我们再看看。。。 -- Let's take a look again...}
#{120}{}{No, bye.}
{120}{}{不，再见。 -- No, bye.}
#{129}{}{Dammit! When I get him!!..}
{129}{}{该死！当我抓到他的时候！！。。 -- Dammit! When I get him!!..}
#{130}{}{[Look at capture scene from the outside]}
{130}{}{[从外面看拍摄现场] -- [Look at capture scene from the outside]}
#{131}{}{You have betrayed your partner!}
{131}{}{你背叛了你的搭档！ -- You have betrayed your partner!}
#{132}{}{Hey wanderer! Wouldn't mind coming in, there's one question to resolve.}
{132}{}{嘿，流浪者！我不介意进来，有一个问题要解决。 -- Hey wanderer! Wouldn't mind coming in, there's one question to resolve.}
#{133}{}{Stay where you are! I've got a shotgun!}
{133}{}{呆在原地别动！我有一把猎枪！ -- Stay where you are! I've got a shotgun!}
#{134}{}{NO!!! GODDAMMIT!!!}
{134}{}{不！！！他妈的！！！ -- NO!!! GODDAMMIT!!!}
#{135}{}{You should've think twice before! Now come out.}
{135}{}{你应该三思而后行！现在出来。 -- You should've think twice before! Now come out.}
#{136}{}{You did the right thing telling me about him. Sheriff looked for this wriggler for a long time. Now the town will be safer. You know, people these days don't help each other just because. I don't know *why* you sold him out but I just have to thank you. Here's 500 bucks and my favorite gun. Hope you like it.}
{136}{}{你告诉我他的事是对的。警长找了很久。现在镇上会更安全。你知道，现在的人们不会仅仅因为你而互相帮助。我不知道为什么你出卖了他，但我要谢谢你。这是500美元和我最喜欢的枪。希望你喜欢。 -- You did the right thing telling me about him. Sheriff looked for this wriggler for a long time. Now the town will be safer. You know, people these days don't help each other just because. I don't know *why* you sold him out but I just have to thank you. Here's 500 bucks and my favorite gun. Hope you like it.}
#{137}{}{Thanks! It's a worthy gun!}
{137}{}{谢谢！这是一把配得上的枪！ -- Thanks! It's a worthy gun!}
#{138}{}{You came in just in time! Prospectors found an excellent weapon - heavy machine gun, which fires rifle rounds. I was think about selling it someone. Sheriff would gladly buy it but for a small price. Maybe your money are more willing? Anyway, I'll just leave it here and you think about the offer.}
{138}{}{你来得正是时候！探矿者发现了一种极好的武器——重型机枪，可以发射步枪子弹。我想把它卖给别人。要不是价钱便宜，警长很乐意买下它。也许你的钱更愿意？不管怎样，我就把它留在这里，你考虑一下报价。 -- You came in just in time! Prospectors found an excellent weapon - heavy machine gun, which fires rifle rounds. I was think about selling it someone. Sheriff would gladly buy it but for a small price. Maybe your money are more willing? Anyway, I'll just leave it here and you think about the offer.}
#{140}{}{You know, your assortment lacks something serious - something that shoots... EXPLOSIVES! Might come in handy for me.}
{140}{}{你知道吗，你的产品缺乏严肃的东西-一些可以射击的东西。。。炸药！可能对我有用。 -- You know, your assortment lacks something serious - something that shoots... EXPLOSIVES! Might come in handy for me.}
#{141}{}{I see you value some heavy army weaponry. Such things are not for self defense. Anyway, the Sheriff instantly buys any serious weapon I find... For a cheap price, of course.}
{141}{}{我看你很看重一些重武器。这样的事情不是为了自卫。不管怎样，警长会立刻买下我找到的任何武器。。。当然是便宜的价格。 -- I see you value some heavy army weaponry. Such things are not for self defense. Anyway, the Sheriff instantly buys any serious weapon I find... For a cheap price, of course.}
#{142}{}{Cheap? You know, I can offer more than Sheriff. Let me know when you have something in stock.}
{142}{}{便宜的？你知道，我能提供的不仅仅是警长。有货时告诉我。 -- Cheap? You know, I can offer more than Sheriff. Let me know when you have something in stock.}
#{143}{}{[Smiles and nods] Why yes, there's grenade launcher and 40mm ammunition packs for it. If you want, you can buy it before Sheriff beats you. But don't tell the cops where did you get this baby.}
{143}{}{[微笑和点头]是的，有榴弹发射器和40毫米弹药包。如果你愿意，你可以在警长打你之前买下它。但别告诉警察你从哪儿弄来的孩子。 -- [Smiles and nods] Why yes, there's grenade launcher and 40mm ammunition packs for it. If you want, you can buy it before Sheriff beats you. But don't tell the cops where did you get this baby.}
#{144}{}{No problem!}
{144}{}{没问题！ -- No problem!}
#{150}{}{Tell me, kind man, who'd ride with me on a train?}
{150}{}{告诉我，好心人，谁会和我一起坐火车？ -- Tell me, kind man, who'd ride with me on a train?}
#{151}{}{Hm? Hardly any of the local will decide on this. Only newcomer in the city, or absolutely desperate, who would also want to catch a bullet from the sheriff at the railway depot. It's forbidden not only to go there, but even to speak publicly about it.}
{151}{}{嗯？几乎没有一个当地人会对此作出决定。城里唯一一个新来的人，或者说是绝对绝望的人，他们也想在火车站抓住警长的子弹。不仅禁止去那里，甚至禁止公开谈论此事。 -- Hm? Hardly any of the local will decide on this. Only newcomer in the city, or absolutely desperate, who would also want to catch a bullet from the sheriff at the railway depot. It's forbidden not only to go there, but even to speak publicly about it.}
#{152}{}{Eh, thanks for the tip.}
{152}{}{呃，谢谢你的小费。 -- Eh, thanks for the tip.}
#{160}{}{To say honestly, you weapon stock is shit.}
{160}{}{老实说，你的武器库是狗屎。 -- To say honestly, you weapon stock is shit.}
#{161}{}{[He throws up his hands in grief] Why everyone says the same to me?! A-ah, now I get it. You're from these regions where bombs did not send half of the town to hell and where civil war wasn't an issue. So now you know, we were much less fortunate. Have to appreciate what's left.}
{161}{}{[他悲伤地举起双手]为什么每个人都对我这么说？！啊，现在我明白了。你来自这些地区，在那里炸弹没有把半个城镇送进地狱，内战也不是问题。所以现在你知道了，我们可没那么幸运了。必须珍惜剩下的一切。 -- [He throws up his hands in grief] Why everyone says the same to me?! A-ah, now I get it. You're from these regions where bombs did not send half of the town to hell and where civil war wasn't an issue. So now you know, we were much less fortunate. Have to appreciate what's left.}
#{162}{}{Maybe you can advice someone with better stock?}
{162}{}{也许你可以建议一个有更好股票的人？ -- Maybe you can advice someone with better stock?}
#{163}{}{No one besides me... And police with mormons. But these ones won't be traded with, rather opposite - they buy all the good guns and give me away any kind of pipe trash. [he sniffs] And then they are surprised that I can't sell a damn thing...}
{163}{}{除了我没有人。。。警察和摩门教徒。但这些枪是不会被交易的，恰恰相反——他们买了所有的好枪，把任何一种烟斗垃圾都给了我。[他嗅了嗅]然后他们惊讶地发现我一个该死的东西都卖不出去。。。 -- No one besides me... And police with mormons. But these ones won't be traded with, rather opposite - they buy all the good guns and give me away any kind of pipe trash. [he sniffs] And then they are surprised that I can't sell a damn thing...}
#{164}{}{Understood, will keep in mind.}
{164}{}{明白了，会记住的。 -- Understood, will keep in mind.}
#{170}{}{Do you know anything about Sheriff Burton's weapon?}
{170}{}{你知道伯顿警长的武器吗？ -- Do you know anything about Sheriff Burton's weapon?}
#{171}{}{I know something. Mostly from an article in "Super-science". It describes such systems.}
{171}{}{我知道一些事情。主要来自《超级科学》的一篇文章。它描述了这样的系统。 -- I know something. Mostly from an article in "Super-science". It describes such systems.}
#{172}{}{What systems?}
{172}{}{什么系统？ -- What systems?}
#{173}{}{With the principle of electromagnetic acceleration. The bullet accelerates due to a stepped magnetic repulsion. Such weapons were only available to large military bases and military engineering laboratories. The sheriff Burton's gun, apparently, is from the northern military base, which was bombed in the year of 2077.}
{173}{}{利用电磁加速原理。子弹由于一个阶梯式的磁斥力而加速。这种武器只有大型军事基地和军事工程实验室才有。显然，伯顿警长的枪来自于2077年被轰炸的北方军事基地。 -- With the principle of electromagnetic acceleration. The bullet accelerates due to a stepped magnetic repulsion. Such weapons were only available to large military bases and military engineering laboratories. The sheriff Burton's gun, apparently, is from the northern military base, which was bombed in the year of 2077.}
#{174}{}{You've said something about bullets. It's just a cartridge, right?}
{174}{}{你说过子弹的事。只是个子弹，对吧？ -- You've said something about bullets. It's just a cartridge, right?}
#{175}{}{Oh no, it's a 2mm metal needle. Sounds simple, but you must really know what to do, to make them.}
{175}{}{哦，不，是一根2毫米的金属针。听起来很简单，但你必须真正知道该怎么做，使他们。 -- Oh no, it's a 2mm metal needle. Sounds simple, but you must really know what to do, to make them.}
#{176}{}{What's so difficult?}
{176}{}{什么这么难？ -- What's so difficult?}
#{177}{}{The magnetic properties of metals, aerodynamics, mass balance... To be clear, it's pure physics and mathematics. If you want to learn, the article had all the necessary explanations. Just pay 200 bucks for the information.}
{177}{}{金属的磁性，空气动力学，质量平衡。。。很明显，这是纯物理和数学。如果你想学习，这篇文章有所有必要的解释。只要花200美元就可以得到信息。 -- The magnetic properties of metals, aerodynamics, mass balance... To be clear, it's pure physics and mathematics. If you want to learn, the article had all the necessary explanations. Just pay 200 bucks for the information.}
#{178}{}{All right, here's the money.}
{178}{}{好吧，这是钱。 -- All right, here's the money.}
#{179}{}{Let's change the topic.}
{179}{}{我们换个话题吧。 -- Let's change the topic.}
#{180}{}{[You carefully study the excellent article about the Gauss system from the "Super-science" magazine. It seems that with the proper repairing skills, you could easily manufacture ammunition for weapons with electromagnetic acceleration.]}
{180}{}{[你仔细研究了《超级科学》杂志上关于高斯系统的优秀文章。看来只要有适当的修理技术，你就可以很容易地制造电磁加速武器的弹药。] -- [You carefully study the excellent article about the Gauss system from the "Super-science" magazine. It seems that with the proper repairing skills, you could easily manufacture ammunition for weapons with electromagnetic acceleration.]}
#{181}{}{[End]}
{181}{}{[结束] -- [End]}
#{1110}{}{Hello wanderer! Don't pass by Quok's family business! We always happy with new visitors and won't let you go without some excellent goodies! Check out my new weapon stock. Maybe you'll find something fitting your holster.}
{1110}{}{你好，流浪者！别错过库克的家族事业！我们对新来的客人总是很满意，不会让你没有好东西就走的！看看我的新武器。也许你会找到适合你枪套的东西。 -- Hello wanderer! Don't pass by Quok's family business! We always happy with new visitors and won't let you go without some excellent goodies! Check out my new weapon stock. Maybe you'll find something fitting your holster.}
#{1113}{}{Hey! I just saw someone jumping into your yard! I think that was the thief!}
{1113}{}{嘿！我刚看见有人跳进你的院子！我想那是小偷！ -- Hey! I just saw someone jumping into your yard! I think that was the thief!}
#{1132}{}{Hey wanderer! Wouldn't mind coming in, there's one question to resolve.}
{1132}{}{嘿，流浪者！我不介意进来，有一个问题要解决。 -- Hey wanderer! Wouldn't mind coming in, there's one question to resolve.}
#{1136}{}{You did the right thing telling me about him. Sheriff looked for this wriggler for a long time. Now the town will be safer place. You know, people these days don't help each other just because. I don't know *why* you sold him out but I just have to thank you. Here's 500 bucks and my favorite gun. Hope you like it.}
{1136}{}{你告诉我他的事是对的。警长找了很久。现在这个城镇会更安全。你知道，现在的人们不会仅仅因为你而互相帮助。我不知道为什么你出卖了他，但我要谢谢你。这是500美元和我最喜欢的枪。希望你喜欢。 -- You did the right thing telling me about him. Sheriff looked for this wriggler for a long time. Now the town will be safer place. You know, people these days don't help each other just because. I don't know *why* you sold him out but I just have to thank you. Here's 500 bucks and my favorite gun. Hope you like it.}
