#{100}{}{You see Beagle.}
{100}{}{你看到小猎犬了。 -- You see Beagle.}
#{101}{}{You see the sheriff's senior assistant.}
{101}{}{你去见警长的高级助理。 -- You see the sheriff's senior assistant.}
#{102}{}{If you came to sheriff, he's gone on business.}
{102}{}{如果你去找警长，他就出差了。 -- If you came to sheriff, he's gone on business.}
#{110}{}{What issue brought you here? If you came to sheriff, he's in his office.}
{110}{}{什么问题把你带到这里来的？如果你去找警长，他就在办公室里。 -- What issue brought you here? If you came to sheriff, he's in his office.}
#{111}{}{God, who's this?! Maybe, we should just shoot it?}
{111}{}{天哪，这是谁？！也许，我们应该开枪？ -- God, who's this?! Maybe, we should just shoot it?}
#{112}{}{You did the right thing regarding that thief! Good job!}
{112}{}{你对那个小偷做了正确的事！干得好！ -- You did the right thing regarding that thief! Good job!}
#{113}{}{Provo should have been eradicated long ago!}
{113}{}{普罗沃早就该被消灭了！ -- Provo should have been eradicated long ago!}
#{114}{}{About Gilmore - good job!}
{114}{}{关于吉尔摩-干得好！ -- About Gilmore - good job!}
#{115}{}{Weapon in holster! Now!}
{115}{}{枪套里有武器！现在！ -- Weapon in holster! Now!}
