#{100}{}{You see a cable.}
{100}{}{你看到一条电缆。 -- You see a cable.}
#{101}{}{You see a wires. Probably they just were taken down and cut in the middle.}
{101}{}{你看到一根电线。也许他们只是被砍倒在中间。 -- You see a wires. Probably they just were taken down and cut in the middle.}
#{102}{}{It's just some wires. You don't even know where they are going.}
{102}{}{只是一些电线。你甚至不知道他们要去哪里。 -- It's just some wires. You don't even know where they are going.}
#{103}{}{These are normal wires.}
{103}{}{这些是普通电线。 -- These are normal wires.}
#{104}{}{You connect the wires and thereby restore the electrical network of the hangar.}
{104}{}{你连接电线，从而恢复飞机库的电力网络。 -- You connect the wires and thereby restore the electrical network of the hangar.}
#{105}{}{May there be light, oh holy Plutonium!}
{105}{}{愿有光，哦，神圣的钚！ -- May there be light, oh holy Plutonium!}
