#{100}{}{This is hatch.}
{100}{}{这是哈奇。 -- This is hatch.}
#{101}{}{A powerful door with a powerful lock. You can only open it by a specific key.}
{101}{}{带强力锁的强力门。你只能用特定的键打开它。 -- A powerful door with a powerful lock. You can only open it by a specific key.}
#{102}{}{It's locked. You can only open it with a specific key.}
{102}{}{锁上了。你只能用特定的钥匙打开它。 -- It's locked. You can only open it with a specific key.}
#{103}{}{Locked, need a key}
{103}{}{锁上了，需要钥匙吗 -- Locked, need a key}
#{104}{}{This door will stand even in front of a small nuclear explosion. Joke. Ha-ha.}
{104}{}{即使在小型核爆炸面前，这扇门也会屹立不倒。开玩笑。哈哈。 -- This door will stand even in front of a small nuclear explosion. Joke. Ha-ha.}
#{110}{}{You unlock this huge hatch.}
{110}{}{你打开这个巨大的舱门。 -- You unlock this huge hatch.}
#{111}{}{Ready!}
{111}{}{准备好了！ -- Ready!}
#{112}{}{This is useless here.}
{112}{}{这里没用。 -- This is useless here.}
#{113}{}{The door is already open.}
{113}{}{门已经开了。 -- The door is already open.}
#{114}{}{Useless}
{114}{}{无用的 -- Useless}
#{115}{}{It will not help. Look for the key.}
{115}{}{这是无济于事的。找钥匙。 -- It will not help. Look for the key.}
