#{100}{}{You see Myers.}
{100}{}{你看迈尔斯。 -- You see Myers.}
#{101}{}{You see the head of the restaurant. He smiles, even though he's very busy.}
{101}{}{你看到餐厅的老板了。他笑了，尽管他很忙。 -- You see the head of the restaurant. He smiles, even though he's very busy.}
#{102}{}{I have a feeling like I'm being watched... [he shakes his head] It's all in my head, probably.}
{102}{}{我有种被人监视的感觉。。。[他摇头]可能都在我脑子里。 -- I have a feeling like I'm being watched... [he shakes his head] It's all in my head, probably.}
#{102}{}{Hey, when you're in here, the weapon stays in its holster.}
{102}{}{嘿，当你在这里的时候，武器就放在枪套里。 -- Hey, when you're in here, the weapon stays in its holster.}
#{103}{}{I know we say the customer with a knife is always right... But there's a limit!}
{103}{}{我知道我们说拿刀的顾客总是对的。。。但这是有限度的！ -- I know we say the customer with a knife is always right... But there's a limit!}
#{110}{}{One sandwich and beer...}
{110}{}{一份三明治和啤酒。。。 -- One sandwich and beer...}
#{111}{}{Who ordered gecko steak?}
{111}{}{谁点了壁虎牛排？ -- Who ordered gecko steak?}
#{112}{}{Forty-five bucks.}
{112}{}{四十五美元。 -- Forty-five bucks.}
#{113}{}{You want a take-out?}
{113}{}{你要外卖吗？ -- You want a take-out?}
#{114}{}{Special order from Avellone on the way...}
{114}{}{阿维隆的特别订单。。。 -- Special order from Avellone on the way...}
#{115}{}{No, no, no tabs.}
{115}{}{不，不，没有标签。 -- No, no, no tabs.}
#{116}{}{One "dive bomb" with ice, coming right up.}
{116}{}{一个带冰块的“潜水炸弹”，马上就来。 -- One "dive bomb" with ice, coming right up.}
#{117}{}{Keep it down, this ain't a casino!}
{117}{}{小声点，这不是赌场！ -- Keep it down, this ain't a casino!}
#{118}{}{Who didn't pay for his sandwich?!}
{118}{}{谁没付三明治的钱？！ -- Who didn't pay for his sandwich?!}
#{119}{}{Still waiting on that order of brahmin meat...}
{119}{}{还在等婆罗门的肉。。。 -- Still waiting on that order of brahmin meat...}
#{120}{}{[Whistles]}
{120}{}{[口哨声] -- [Whistles]}
#{130}{}{Are you interested in gecko eggs?}
{130}{}{你对壁虎蛋感兴趣吗？ -- Are you interested in gecko eggs?}
#{131}{}{Hell yeah! It's a delicacy around here. I'll pay you }
{131}{}{见鬼，耶！这附近很美味。我付钱给你 -- Hell yeah! It's a delicacy around here. I'll pay you }
#{132}{}{ bucks apiece!}
{132}{}{每人50美元！ --  bucks apiece!}
#{133}{}{Do you have regular suppliers?}
{133}{}{你们有固定的供应商吗？ -- Do you have regular suppliers?}
#{134}{}{Nah. Sometimes the hunters bring these eggs in from the north and northeast, but more often caravans buy 'em there, then sell 'em here at a profit. Hunters get money, caravans get money, and once I'm done with 'em, I get money. Everybody wins.}
{134}{}{不。有时猎人从北方和东北运来这些鸡蛋，但更多的时候商队在那里购买，然后在这里出售获利。猎人有钱，商队有钱，一旦我搞定他们，我就有钱了。人人都赢。 -- Nah. Sometimes the hunters bring these eggs in from the north and northeast, but more often caravans buy 'em there, then sell 'em here at a profit. Hunters get money, caravans get money, and once I'm done with 'em, I get money. Everybody wins.}
#{135}{}{I'll sell all the eggs I have.}
{135}{}{我要把所有的鸡蛋都卖了。 -- I'll sell all the eggs I have.}
#{136}{}{}
{136}{}{ -- }
#{137}{}{I'll think about it.}
{137}{}{我会考虑的。 -- I'll think about it.}
#{138}{}{Thanks! Here's your money.}
{138}{}{谢谢！这是你的钱。 -- Thanks! Here's your money.}
#{139}{}{You're welcome.}
{139}{}{不客气。 -- You're welcome.}
#{140}{}{Okay. Where's the eggs?}
{140}{}{可以。鸡蛋在哪里？ -- Okay. Where's the eggs?}
#{141}{}{Uh, just a second...}
{141}{}{呃，等一下。。。 -- Uh, just a second...}
#{142}{}{What? You're practically robbing me! Can I get another 10 dollars each?}
{142}{}{什么？你简直是在抢劫我！我能每人再要10美元吗？ -- What? You're practically robbing me! Can I get another 10 dollars each?}
#{143}{}{}
{143}{}{ -- }
#{144}{}{That'd be robbing *me!* No deal!}
{144}{}{那是在抢劫我！*没有交易！ -- That'd be robbing *me!* No deal!}
#{145}{}{Fine, I'll sell them at your price.}
{145}{}{好吧，我按你的价格卖。 -- Fine, I'll sell them at your price.}
#{146}{}{Then I'll take my eggs elsewhere.}
{146}{}{那我就把鸡蛋带到别处去。 -- Then I'll take my eggs elsewhere.}
#{147}{}{[He frowns and grumbles] These eggs have been hard to get lately, so... Fine. Another ten bucks. My customers will have to deal with the price hike.}
{147}{}{[他皱眉发牢骚]这些鸡蛋最近很难弄到，所以。。。好的。再来十块。我的顾客将不得不面对涨价。 -- [He frowns and grumbles] These eggs have been hard to get lately, so... Fine. Another ten bucks. My customers will have to deal with the price hike.}
#{149}{}{[He glares at you] Are you going to order something?}
{149}{}{[他瞪着你]你要点菜吗？ -- [He glares at you] Are you going to order something?}
#{150}{}{Hey, you hungry? What are you looking for?}
{150}{}{嘿，你饿了吗？你在找什么？ -- Hey, you hungry? What are you looking for?}
#{151}{}{Yes?}
{151}{}{对？ -- Yes?}
#{152}{}{Show me the menu.}
{152}{}{给我看菜单。 -- Show me the menu.}
#{153}{}{}
{153}{}{ -- }
#{154}{}{Thanks, that's all.}
{154}{}{谢谢，就这些。 -- Thanks, that's all.}
#{155}{}{Shit! [he recoils] Look, I'll make you whatever you want, but you gotta get right out after. And... Just don't touch anything!}
{155}{}{倒霉！听着，你要什么我就给你做什么，但你得马上出去。还有。。。别碰任何东西！ -- Shit! [he recoils] Look, I'll make you whatever you want, but you gotta get right out after. And... Just don't touch anything!}
#{156}{}{Mrs. Clover told me what you did for her. Look, any friend of the community's a friend of mine. Next time you're in here, it's 5% off on me. It's the least I can do!}
{156}{}{克洛弗太太告诉我你为她做了什么。听着，社区里的朋友都是我的朋友。下次你来这里，我可以打5%的折扣。这是我至少能做的！ -- Mrs. Clover told me what you did for her. Look, any friend of the community's a friend of mine. Next time you're in here, it's 5% off on me. It's the least I can do!}
#{157}{}{You? It's you! Please, ma'am, sit down, sit down! What can I make you? And don't worry about payment - I'm just happy to have you here.}
{157}{}{你呢？是你！请，女士，坐下，坐下！我能给你做什么？别担心付款问题-我很高兴你能来。 -- You? It's you! Please, ma'am, sit down, sit down! What can I make you? And don't worry about payment - I'm just happy to have you here.}
#{158}{}{Hey, thanks for stopping by! The whole town's talking about you, you know. For you, I'm cutting the prices by a quarter. What goes around, comes around, am I right?}
{158}{}{嘿，谢谢你过来！整个镇子都在谈论你，你知道的。对你来说，我要降价四分之一。什么会发生，什么会发生，我说的对吗？ -- Hey, thanks for stopping by! The whole town's talking about you, you know. For you, I'm cutting the prices by a quarter. What goes around, comes around, am I right?}
#{159}{}{Oh, uh, hey! You're the talk of the town. Hey, just so you know, I had to, uh, raise my prices by 25%. Nothing to do with you, of course... Just business.}
{159}{}{哦，呃，嘿！你是全城的话题。嘿，你知道的，我不得不，呃，把价格提高25%。当然，与你无关。。。只是生意。 -- Oh, uh, hey! You're the talk of the town. Hey, just so you know, I had to, uh, raise my prices by 25%. Nothing to do with you, of course... Just business.}
#{160}{}{You? It's you! Please, sir, sit down, sit down! What can I make you? And don't worry about payment - I'm just happy to have you here.}
{160}{}{你呢？是你！先生，请坐，请坐！我能给你做什么？别担心付款问题-我很高兴你能来。 -- You? It's you! Please, sir, sit down, sit down! What can I make you? And don't worry about payment - I'm just happy to have you here.}
#{161}{}{You have received a discount in the restaurant.}
{161}{}{你在餐馆里得到了折扣。 -- You have received a discount in the restaurant.}
#{170}{}{Who's that little urchin running around?}
{170}{}{那个小顽童是谁？ -- Who's that little urchin running around?}
#{171}{}{Billy? I picked him up off the street to wash the floors and clean the tables. Don't worry about him, he's happy as long as he's fed. So, what would you like to eat?}
{171}{}{比利？我把他从街上抱起来洗地板和擦桌子。别担心他，只要他有饭吃，他就很高兴。那么，你想吃什么？ -- Billy? I picked him up off the street to wash the floors and clean the tables. Don't worry about him, he's happy as long as he's fed. So, what would you like to eat?}
#{172}{}{Anything else?}
{172}{}{还有别的吗？ -- Anything else?}
#{173}{}{}
{173}{}{ -- }
#{174}{}{Have you seen the girl in this photo?}
{174}{}{你看到这张照片里的女孩了吗？ -- Have you seen the girl in this photo?}
#{175}{}{Maybe? She looks familiar. Wait, that's right! She lived across from the restaurant, on 75 Virginia Street. Ask around in the slums, they can probably help you.}
{175}{}{也许 吧？她看起来很眼熟。等等，没错！她住在餐馆对面，弗吉尼亚街75号。问问贫民窟里的人，他们可能会帮你。 -- Maybe? She looks familiar. Wait, that's right! She lived across from the restaurant, on 75 Virginia Street. Ask around in the slums, they can probably help you.}
#{176}{}{Please, help... I'm so hungry...}
{176}{}{拜托，救命啊。。。我太饿了。。。 -- Please, help... I'm so hungry...}
#{177}{}{No handouts. Show me some money or get out.}
{177}{}{没有施舍。给我点钱，不然就出去。 -- No handouts. Show me some money or get out.}
#{178}{}{Please... I'm dying... I need food...}
{178}{}{拜托。。。我要死了。。。我需要食物。。。 -- Please... I'm dying... I need food...}
#{179}{}{And I need to pay the rent! I'm running business here, I can't just give away food. Sorry.}
{179}{}{我要付房租！我在这里做生意，我不能只送食物。对不起的。 -- And I need to pay the rent! I'm running business here, I can't just give away food. Sorry.}
#{180}{}{[He sighs] Fine, here's *one* sandwich. Now get out! You're disturbing my customers.}
{180}{}{好吧，这是一个三明治。现在出去！你在打扰我的顾客。 -- [He sighs] Fine, here's *one* sandwich. Now get out! You're disturbing my customers.}
#{181}{}{Do bikers come by here?}
{181}{}{骑自行车的人到这儿来吗？ -- Do bikers come by here?}
#{182}{}{Not since that thing with the stagecoach. They used to come by the city before that, but even then they weren't welcome here.}
{182}{}{从马车那件事开始就没有了。在那之前，他们常来这座城市，但即使在那时，这里也不欢迎他们。 -- Not since that thing with the stagecoach. They used to come by the city before that, but even then they weren't welcome here.}
#{183}{}{What's the story with the stagecoach?}
{183}{}{驿站马车是怎么回事？ -- What's the story with the stagecoach?}
#{184}{}{You haven't heard? They hit one of the "Nevada Express"'s transports, dumb bastards. Once the Express figures out where they're hiding, they're gonna feed them their own ass. Good riddance, I say - they've been nothing but trouble every time I've seen 'em.}
{184}{}{你没听说吗？他们撞了一辆内华达快车，笨蛋。一旦特快找到他们的藏身之地，他们就要自食其果了。我说，真是解脱了，每次我见到他们，他们都是麻烦。 -- You haven't heard? They hit one of the "Nevada Express"'s transports, dumb bastards. Once the Express figures out where they're hiding, they're gonna feed them their own ass. Good riddance, I say - they've been nothing but trouble every time I've seen 'em.}
#{185}{}{Wow, you've got a whole mountain of meat on the street!}
{185}{}{哇，你街上有一大堆肉！ -- Wow, you've got a whole mountain of meat on the street!}
#{186}{}{Yeah, I managed to cut a deal with Mr. Luciano. He's got the best meat in the city... Most expensive, too. [he frowns]}
{186}{}{是的，我设法和卢西亚诺先生达成了协议。他有城里最好的肉。。。也是最贵的。[他皱眉] -- Yeah, I managed to cut a deal with Mr. Luciano. He's got the best meat in the city... Most expensive, too. [he frowns]}
#{187}{}{The best? How do you know?}
{187}{}{最好的？你怎么知道的？ -- The best? How do you know?}
#{188}{}{Mr. Luciano's always on time and his brahmin are always healthy. A lot of the smaller farmers I've worked were a lot less reliable, but I've never had a problem with Luciano's product.}
{188}{}{卢西亚诺先生总是准时，他的婆罗门总是健康的。我工作过的许多小农都不太可靠，但我从未对卢西亚诺的产品有过任何问题。 -- Mr. Luciano's always on time and his brahmin are always healthy. A lot of the smaller farmers I've worked were a lot less reliable, but I've never had a problem with Luciano's product.}
#{189}{}{Right.}
{189}{}{正确的。 -- Right.}
#{190}{}{How long has it been since Mr. Mordino visited you?}
{190}{}{摩迪诺先生来看你有多久了？ -- How long has it been since Mr. Mordino visited you?}
#{191}{}{[He stops what he's doing, then peers at you with narrowed eyes] Long. And it better be a long time before you ask me that again. Mordino's business is his own. I won't say anything more about it.}
{191}{}{[他停下来，眯着眼睛盯着你]很久了。你最好等很久再问我。摩迪诺的事是他自己的。我就不多说了。 -- [He stops what he's doing, then peers at you with narrowed eyes] Long. And it better be a long time before you ask me that again. Mordino's business is his own. I won't say anything more about it.}
#{192}{}{Who will, then?}
{192}{}{那谁来呢？ -- Who will, then?}
#{193}{}{Look. [he points one finger towards you] My lips are sealed, you get that? You really want to find out? Go ask someone else, somewhere else. You get me?}
{193}{}{你看。[他用一根手指指着你]我的嘴唇是密封的，你明白吗？你真的想知道吗？去问问其他人，其他地方。明白了吗？ -- Look. [he points one finger towards you] My lips are sealed, you get that? You really want to find out? Go ask someone else, somewhere else. You get me?}
#{194}{}{Yeah, I get you.}
{194}{}{是的，我明白了。 -- Yeah, I get you.}
#{300}{}{Hey, you want a steady supply of Nuka-Cola? Why not set up a contract with Salt Lake!}
{300}{}{嘿，你想要稳定的努卡可乐吗？为什么不和盐湖城签个合同呢！ -- Hey, you want a steady supply of Nuka-Cola? Why not set up a contract with Salt Lake!}
#{301}{}{[He looks you up and down] And *you're* the one offering the contract? Sorry, I don't even know you. I can't trust my customers' health to you!}
{301}{}{[他上下打量你]你就是那个提供合同的人？对不起，我都不认识你。我不能把顾客的健康托付给你！ -- [He looks you up and down] And *you're* the one offering the contract? Sorry, I don't even know you. I can't trust my customers' health to you!}
#{302}{}{That's a shame...}
{302}{}{真可惜。。。 -- That's a shame...}
#{303}{}{Do you really work for the Nuka-Cola factory? You don't look like the type.}
{303}{}{你真的在努卡可乐厂工作吗？你看起来不像那种人。 -- Do you really work for the Nuka-Cola factory? You don't look like the type.}
#{304}{}{You don't believe me? Just look at my license!}
{304}{}{你不相信我？看看我的驾照！ -- You don't believe me? Just look at my license!}
#{305}{}{What's that supposed to me? Oh, forget it.}
{305}{}{那对我来说是什么？哦，算了吧。 -- What's that supposed to me? Oh, forget it.}
#{306}{}{Uh-huh. [he crosses his arms] How do I know you didn't steal it? Thanks, but no thanks.}
{306}{}{啊哈。[他交叉双臂]我怎么知道你没偷？谢谢，不过不用了，谢谢。 -- Uh-huh. [he crosses his arms] How do I know you didn't steal it? Thanks, but no thanks.}
#{307}{}{Rude!}
{307}{}{粗鲁无礼！ -- Rude!}
#{308}{}{I'll find a way to gain your trust.}
{308}{}{我会想办法得到你的信任。 -- I'll find a way to gain your trust.}
#{309}{}{Nuka-Cola? Hmm. Maybe. It depends on the price.}
{309}{}{努卡可乐？嗯。也许吧。这取决于价格。 -- Nuka-Cola? Hmm. Maybe. It depends on the price.}
#{310}{}{The price is reasonable - I'm working directly with the Nuka-Cola factory.}
{310}{}{价格是合理的-我直接与努卡可乐厂工作。 -- The price is reasonable - I'm working directly with the Nuka-Cola factory.}
#{311}{}{You still don't strike me as the business type, but hey, who am I to argue? What's it gonna cost me?}
{311}{}{我还是不觉得你是生意人，但是嘿，我该和谁争论呢？我要花多少钱？ -- You still don't strike me as the business type, but hey, who am I to argue? What's it gonna cost me?}
#{312}{}{Oh yeah? Who's going to transport it?}
{312}{}{哦，是吗？谁来运送？ -- Oh yeah? Who's going to transport it?}
#{313}{}{Why does that matter?}
{313}{}{为什么这很重要？ -- Why does that matter?}
#{314}{}{This kind of stuff comes by caravan, usually by a lot of them. That means I've got to cut more deals and spend more money. I can't pay so much for a product that costs a few bucks to people, you know?}
{314}{}{这种东西是大篷车运来的，通常是很多人运来的。那就意味着我要做更多的交易，花更多的钱。我不能花这么多钱买一个对人来说只值几美元的产品，你知道吗？ -- This kind of stuff comes by caravan, usually by a lot of them. That means I've got to cut more deals and spend more money. I can't pay so much for a product that costs a few bucks to people, you know?}
#{315}{}{Don't worry about the delivery. I can line up cheap and effective deliveries. All you'll have to do is sell it.}
{315}{}{别担心送货。我可以安排廉价有效的送货。你只要把它卖掉就行了。 -- Don't worry about the delivery. I can line up cheap and effective deliveries. All you'll have to do is sell it.}
#{316}{}{Hmm... I'll think about it and come back with a solution.}
{316}{}{隐马尔可夫模型。。。我会考虑一下，然后再提出解决办法。 -- Hmm... I'll think about it and come back with a solution.}
#{317}{}{Well, if you can deal with all that yourself, then I'm in. Why not?}
{317}{}{好吧，如果你能自己处理这些，那我就加入了。为什么不呢？ -- Well, if you can deal with all that yourself, then I'm in. Why not?}
#{318}{}{So we have a deal?}
{318}{}{我们说好了？ -- So we have a deal?}
#{319}{}{Sure. I'll fix up one of those drink machines and sell it there. You can automatically calculate and take your cut of the profits right on it. You'll just have to make sure the product gets here, and pick up your money.}
{319}{}{当然。我去修理一台饮料机，然后在那里卖。你可以自动计算并从中提取利润。你只需要确保产品送到这里，然后拿钱就行了。 -- Sure. I'll fix up one of those drink machines and sell it there. You can automatically calculate and take your cut of the profits right on it. You'll just have to make sure the product gets here, and pick up your money.}
#{320}{}{Then let's get to work!}
{320}{}{那我们开始工作吧！ -- Then let's get to work!}
#{321}{}{Great! A deal's a deal!}
{321}{}{太好了！一言为定！ -- Great! A deal's a deal!}
#{322}{}{Let's do this...}
{322}{}{让我们这样做。。。 -- Let's do this...}
#{323}{}{Great deal! Thanks!}
{323}{}{太好了！谢谢！ -- Great deal! Thanks!}
#{324}{}{See you.}
{324}{}{再见。 -- See you.}
#{1176}{}{Please, help... I'm so hungry...}
{1176}{}{拜托，救命啊。。。我太饿了。。。 -- Please, help... I'm so hungry...}
