#{100}{}{You see a bartender.}
{100}{}{你看到一个酒保。 -- You see a bartender.}
#{101}{}{You see a short, fat man behind a bar counter. He gives you a slight nod.}
{101}{}{你看到一个矮胖子在吧台后面。他轻轻地向你点头。 -- You see a short, fat man behind a bar counter. He gives you a slight nod.}
#{102}{}{ }
{102}{}{  --  }
#{103}{}{I don't serve childkillers.}
{103}{}{我不为儿童杀手服务。 -- I don't serve childkillers.}
#{200}{}{One rotgut coming right up... }
{200}{}{一个罗格特马上就要来了。。。 -- One rotgut coming right up... }
#{201}{}{That'll be three bucks... }
{201}{}{一共三块钱。。。 -- That'll be three bucks... }
#{202}{}{Another one, friend?}
{202}{}{再来一杯，朋友？ -- Another one, friend?}
#{203}{}{Here's your medicine if you want it!}
{203}{}{这是你要的药！ -- Here's your medicine if you want it!}
#{204}{}{You can't barf here! Go outside and barf there!}
{204}{}{你不能在这里呕吐！出去吐吧！ -- You can't barf here! Go outside and barf there!}
#{205}{}{Two half-ounce bags or a tin?}
{205}{}{两袋半盎司还是一罐？ -- Two half-ounce bags or a tin?}
#{206}{}{Special order for Tim Cain... }
{206}{}{给蒂姆·凯恩的特别订单。。。 -- Special order for Tim Cain... }
#{207}{}{Let me guess: put it on your tab?}
{207}{}{让我猜猜：记在你的帐上？ -- Let me guess: put it on your tab?}
#{208}{}{One "dive bomb" with ice, coming right up.}
{208}{}{一个带冰块的“潜水炸弹”，马上就来。 -- One "dive bomb" with ice, coming right up.}
#{209}{}{Hey, you can't just shoot that shit here!}
{209}{}{嘿，你不能在这里开枪！ -- Hey, you can't just shoot that shit here!}
#{210}{}{You know why we need to hang these actors? 'Cause the theater begins with the hanger... Ha-ha-ha!}
{210}{}{你知道我们为什么要绞死这些演员吗因为戏剧从衣架开始。。。哈哈哈！ -- You know why we need to hang these actors? 'Cause the theater begins with the hanger... Ha-ha-ha!}
#{229}{}{How can I help you?}
{229}{}{我能帮你什么？ -- How can I help you?}
#{230}{}{Need something, chummer?}
{230}{}{需要什么吗，查默？ -- Need something, chummer?}
#{231}{}{Drink. Show me what you've got.}
{231}{}{喝酒。给我看看你有什么。 -- Drink. Show me what you've got.}
#{232}{}{No thanks.}
{232}{}{不用了，谢谢。 -- No thanks.}
#{233}{}{Anything else?}
{233}{}{还有别的吗？ -- Anything else?}
#{234}{}{I'll have another one.}
{234}{}{我再来一杯。 -- I'll have another one.}
#{235}{}{No thanks. I need to ask you something.}
{235}{}{不用了，谢谢。我要问你一件事。 -- No thanks. I need to ask you something.}
#{236}{}{Of course, of course. I think you'd like to know we have special prices for those who are *with us*}
{236}{}{当然，当然。我想你会想知道我们对和我们在一起的人有特别的价格* -- Of course, of course. I think you'd like to know we have special prices for those who are *with us*}
#{237}{}{Glad to hear.}
{237}{}{很高兴听到。 -- Glad to hear.}
#{238}{}{You received a big discount at the bar.}
{238}{}{你在酒吧得到了很大的折扣。 -- You received a big discount at the bar.}
#{240}{}{Sir! This is a casino, not a firing range!}
{240}{}{先生！这是赌场，不是射击场！ -- Sir! This is a casino, not a firing range!}
#{241}{}{Speaking of, where's your boss? I need to, err, talk to him.}
{241}{}{说到这里，你老板呢？我需要，呃，和他谈谈。 -- Speaking of, where's your boss? I need to, err, talk to him.}
#{242}{}{I haven't seen him in a while. No one has any idea where he is. It's a shame, too - I wanted to ask for a raise... }
{242}{}{我好久没见到他了。没人知道他在哪里。也很遗憾-我想要求加薪。。。 -- I haven't seen him in a while. No one has any idea where he is. It's a shame, too - I wanted to ask for a raise... }
#{243}{}{How are you handling things without him?}
{243}{}{没有他你怎么办？ -- How are you handling things without him?}
#{244}{}{Administration never rests. We can handle ourselves without Mister Bertolini... For a while, at least.}
{244}{}{政府从不休息。我们不用贝托里尼先生也能应付。。。至少有一段时间。 -- Administration never rests. We can handle ourselves without Mister Bertolini... For a while, at least.}
#{245}{}{Alright... }
{245}{}{好吧。。。 -- Alright... }
#{251}{}{Mom mentioned some guy named Ted Bundy. Heard of him?}
{251}{}{妈妈提到一个叫泰德·邦迪的家伙。听说过他吗？ -- Mom mentioned some guy named Ted Bundy. Heard of him?}
#{252}{}{Ugh. Yeah, I have. Not much though. Would've been better off if I didn't. He's a maniac. Ambushed some of our girls and carved them up with some mechanical knife. Fucking animal. Nobody knows where he lives or how to deal with him. But, as long as you're careful, you should be fine.}
{252}{}{啊。是的，我有。不过不多。如果我不这么做会更好的。他是个疯子。伏击了我们的一些女孩，用机械刀把她们切开。该死的动物。没人知道他住在哪里，也不知道该怎么对付他。但是，只要你小心，你应该没事的。 -- Ugh. Yeah, I have. Not much though. Would've been better off if I didn't. He's a maniac. Ambushed some of our girls and carved them up with some mechanical knife. Fucking animal. Nobody knows where he lives or how to deal with him. But, as long as you're careful, you should be fine.}
#{253}{}{Do you know anything about the girl in this picture?}
{253}{}{你知道这张照片里那个女孩的事吗？ -- Do you know anything about the girl in this picture?}
#{254}{}{Well, she's probably one of the previous dancers. But if that is so, she worked here before me. So, I probably can't help you there... Hold on... "Virginia 75"? I'm not sure, but I think that's somewhere around here.}
{254}{}{她可能是以前的舞者之一。但如果是这样的话，她比我先在这里工作。所以，我可能帮不了你。。。等等……”弗吉尼亚75”？我不确定，但我想就在这附近。 -- Well, she's probably one of the previous dancers. But if that is so, she worked here before me. So, I probably can't help you there... Hold on... "Virginia 75"? I'm not sure, but I think that's somewhere around here.}
#{255}{}{I'm new here. Mind telling me what working here is like?}
{255}{}{我是新来的。介意告诉我在这里工作是什么感觉吗？ -- I'm new here. Mind telling me what working here is like?}
#{256}{}{Well, you know, the collective's nice. But the clients cause problems from time to time. Something you should get used to. Might throw a bottle, or try to get across the railing to the dance floor. And there are complete retards like that pussy from the slums. Harding I think. Locked himself in the toilets and started crying like a little bitch. Had to carry him out in the streets, heh-heh... Point is, best to always keep an eye out.}
{256}{}{好吧，你知道，集体很好。但是客户们时不时地会引起问题。一些你应该习惯的东西。可能会扔一个瓶子，或者试图越过栏杆到舞池。还有像贫民窟里的女人一样的完全的弱智。我想是哈丁。把自己锁在厕所里，像个小婊子一样哭了起来。不得不把他抬到街上，嘿嘿。。。重点是，最好时刻保持警惕。 -- Well, you know, the collective's nice. But the clients cause problems from time to time. Something you should get used to. Might throw a bottle, or try to get across the railing to the dance floor. And there are complete retards like that pussy from the slums. Harding I think. Locked himself in the toilets and started crying like a little bitch. Had to carry him out in the streets, heh-heh... Point is, best to always keep an eye out.}
#{260}{}{Do you know anything about someone named Racer starting a fight?}
{260}{}{你知道一个叫Racer的人打架的事吗？ -- Do you know anything about someone named Racer starting a fight?}
#{261}{}{Yeah, I do. He didn't get far. We kicked his ass to the curb where he belonged. If only he'd gone down the drain, like the hobo piss he is. Hopefully he'll know better than to show his mug here again.}
{261}{}{是的，我知道。他没走多远。我们把他踢到了他该去的地方。要是他像流浪汉那样，一败涂地就好了。希望他不会再在这里展示他的杯子了。 -- Yeah, I do. He didn't get far. We kicked his ass to the curb where he belonged. If only he'd gone down the drain, like the hobo piss he is. Hopefully he'll know better than to show his mug here again.}
#{262}{}{You really don't like him, do you?}
{262}{}{你真的不喜欢他，是吗？ -- You really don't like him, do you?}
#{263}{}{Did you see his mirrored shades anywhere?}
{263}{}{你在哪里看到他的镜子了吗？ -- Did you see his mirrored shades anywhere?}
#{264}{}{Nevermind.}
{264}{}{没有关系。 -- Nevermind.}
#{265}{}{He's one of the bandits that always hangs around Stryker. They think themselves as revolutionaries or something, but bandit's the right word. What the hell are they even revolting against? Other tyrants like themselves? Although, I think I got carried away a little. Just can't bring myself to imagine what will happen if Stryker comes to power. Business isn't doing too well as it is.}
{265}{}{他是史崔克身边的强盗之一。他们认为自己是革命者什么的，但强盗这个词是对的。他们到底在反抗什么？像他们这样的暴君？不过，我想我有点失控了。只是无法想象如果史崔克上台会发生什么。生意做得不太好。 -- He's one of the bandits that always hangs around Stryker. They think themselves as revolutionaries or something, but bandit's the right word. What the hell are they even revolting against? Other tyrants like themselves? Although, I think I got carried away a little. Just can't bring myself to imagine what will happen if Stryker comes to power. Business isn't doing too well as it is.}
#{266}{}{Got 'em right under the counter. Still thinking if I should throw them out or sell them. Compensation for injured feelings and the such.}
{266}{}{就在柜台下面。还在想是该扔掉还是卖掉。感情伤害赔偿等。 -- Got 'em right under the counter. Still thinking if I should throw them out or sell them. Compensation for injured feelings and the such.}
#{267}{}{I wouldn't do that if I were you. I think you should give them to me so I can return them to Racer.}
{267}{}{如果我是你，我就不会那样做。我想你应该把它们给我，这样我就可以把它们还给赛车手了。 -- I wouldn't do that if I were you. I think you should give them to me so I can return them to Racer.}
#{268}{}{I want them. How much do you need?}
{268}{}{我想要他们。你需要多少钱？ -- I want them. How much do you need?}
#{269}{}{Throw them out for all I care.}
{269}{}{不管我怎么想，把它们扔出去。 -- Throw them out for all I care.}
#{270}{}{What? And why is that?}
{270}{}{什么？为什么会这样？ -- What? And why is that?}
#{271}{}{Why do you think? You're dealing with another man's property like it's your own. Sooner or later, he'll find out, and he's already on edge - just think about it!}
{271}{}{你觉得为什么？你在处理别人的财产，就像处理你自己的一样。迟早，他会发现的，他已经很紧张了——想想吧！ -- Why do you think? You're dealing with another man's property like it's your own. Sooner or later, he'll find out, and he's already on edge - just think about it!}
#{272}{}{True, true. Who knows what to expect from his type. Wouldn't want to wake up in a dumpster with a bullet in my gut after an evening walk home. Here you go, don't even mention me. If he asks, just say someone picked them up.}
{272}{}{没错，没错。谁知道从他的类型中能得到什么。我可不想在晚上步行回家后在垃圾桶里醒来，肚子里有颗子弹。给你，别提我。如果他问，就说有人捡到了。 -- True, true. Who knows what to expect from his type. Wouldn't want to wake up in a dumpster with a bullet in my gut after an evening walk home. Here you go, don't even mention me. If he asks, just say someone picked them up.}
#{273}{}{Wise choice.}
{273}{}{明智的选择。 -- Wise choice.}
#{274}{}{Alright, I'll just put them down. If you have something valuable to trade, I'll be more than happy.}
{274}{}{好吧，我把它们放下。如果你有值钱的东西可以交易，我会非常高兴的。 -- Alright, I'll just put them down. If you have something valuable to trade, I'll be more than happy.}
#{275}{}{Let's trade then.}
{275}{}{那我们交易吧。 -- Let's trade then.}
#{276}{}{We'll talk about it sometime later.}
{276}{}{我们稍后再谈。 -- We'll talk about it sometime later.}
#{277}{}{Trust me, I know what I'm talking about.}
{277}{}{相信我，我知道我在说什么。 -- Trust me, I know what I'm talking about.}
#{280}{}{I'm looking for a place to earn a few bucks. Mind pointing me in the right direction?}
{280}{}{我在找一个地方挣几块钱。介意给我指出正确的方向吗？ -- I'm looking for a place to earn a few bucks. Mind pointing me in the right direction?}
#{281}{}{Hmm... You're new in town, right? No friends, no connections... I doubt you have much chance. Unless... }
{281}{}{隐马尔可夫模型。。。你是新来的，对吧？没有朋友，没有关系。。。我怀疑你有多少机会。除非。。。 -- Hmm... You're new in town, right? No friends, no connections... I doubt you have much chance. Unless... }
#{282}{}{Unless?}
{282}{}{除非？ -- Unless?}
#{283}{}{Well, I'd suggest finding a common interest with a few... Influential people. [he looks around the room] Take that gentleman by the pool table, for example. Regular client. Respectable man! Always has money and always orders expensive drinks. I don't know who he works for, but those are the types of people you should look into meeting.}
{283}{}{好吧，我建议你和几个。。。有影响力的人。[他环顾了一下房间]以台球桌旁的那位先生为例。普通客户。可敬的人！总是有钱而且总是点昂贵的饮料。我不知道他是为谁工作的，但你应该去拜访那些类型的人。 -- Well, I'd suggest finding a common interest with a few... Influential people. [he looks around the room] Take that gentleman by the pool table, for example. Regular client. Respectable man! Always has money and always orders expensive drinks. I don't know who he works for, but those are the types of people you should look into meeting.}
#{284}{}{Thanks for the tip.}
{284}{}{谢谢你的小费。 -- Thanks for the tip.}
#{285}{}{Of course, any time... I hope you won't forget about me? [he smiles and winks]}
{285}{}{当然，任何时候。。。我希望你不会忘记我？[他微笑着眨眼] -- Of course, any time... I hope you won't forget about me? [he smiles and winks]}
#{286}{}{Oh yeah, here's a fiver. Thanks.}
{286}{}{哦，是的，这是5英镑。谢谢。 -- Oh yeah, here's a fiver. Thanks.}
#{287}{}{Sorry, but I really am empty today. Some other time.}
{287}{}{对不起，我今天真的空了。改天吧。 -- Sorry, but I really am empty today. Some other time.}
#{288}{}{A pleasure serving you!}
{288}{}{很高兴为您服务！ -- A pleasure serving you!}
#{289}{}{Of course.}
{289}{}{当然。 -- Of course.}
#{300}{}{Say, why do they call Mom that?}
{300}{}{喂，为什么他们这么叫妈妈？ -- Say, why do they call Mom that?}
#{301}{}{Well, as far as I know, she doesn't have kids of her own. But she really cares for those who work for her. And if you consider most of the girls here are orphans - Rose really became their mother.}
{301}{}{据我所知，她没有自己的孩子。但她真的很关心那些为她工作的人。如果你认为这里的大多数女孩都是孤儿——罗斯真的成了她们的母亲。 -- Well, as far as I know, she doesn't have kids of her own. But she really cares for those who work for her. And if you consider most of the girls here are orphans - Rose really became their mother.}
#{302}{}{So, her name is Rose?}
{302}{}{她叫罗斯？ -- So, her name is Rose?}
#{303}{}{Well, obviously it's not Mom! Her real name is Rose Lee. But nobody cares for that unless they're close.}
{303}{}{显然不是妈妈！她的真名是罗斯李。但是没有人会在意，除非他们离得很近。 -- Well, obviously it's not Mom! Her real name is Rose Lee. But nobody cares for that unless they're close.}
#{304}{}{Understood.}
{304}{}{理解。 -- Understood.}
#{1202}{}{Another one, friend?}
{1202}{}{再来一杯，朋友？ -- Another one, friend?}
#{1209}{}{Hey, you can't just shoot that shit here!}
{1209}{}{嘿，你不能在这里开枪！ -- Hey, you can't just shoot that shit here!}
#{1230}{}{Need something, chummer?}
{1230}{}{需要什么吗，查默？ -- Need something, chummer?}
#{1240}{}{Ma'am! This is a casino, not a firing range!}
{1240}{}{太太！这是赌场，不是射击场！ -- Ma'am! This is a casino, not a firing range!}
#{1241}{}{I don't get it. Why is there such a panic in the casino?}
{1241}{}{我不明白。为什么赌场里会有这样的恐慌？ -- I don't get it. Why is there such a panic in the casino?}
#{1244}{}{Chummer, even our boss can't handle money like *that!*}
{1244}{}{丘默，连我们老板都不能那样处理钱！* -- Chummer, even our boss can't handle money like *that!*}
#{1261}{}{We don't stock dope for the casino. Although, the one you're talking about did appear here. More than once. Our boys threw him straight into the streets. Didn't see him since then. And speaking of [he leans in] we're a *respectable casino* - not some hole. I'd keep the topic to myself if I were you. Okay?}
{1261}{}{我们不为赌场储存毒品。不过，你说的那个确实出现在这里。不止一次。我们的人直接把他扔到街上。从那以后就没见过他。说到[他靠进去]我们是一个“值得尊敬的赌场”-不是什么洞。如果我是你的话，我会把这个话题留给自己。可以？ -- We don't stock dope for the casino. Although, the one you're talking about did appear here. More than once. Our boys threw him straight into the streets. Didn't see him since then. And speaking of [he leans in] we're a *respectable casino* - not some hole. I'd keep the topic to myself if I were you. Okay?}
#{1262}{}{Got it.}
{1262}{}{知道了。 -- Got it.}
