#{100}{}{You see a sick resident.}
{100}{}{你看到一个生病的住院医生。 -- You see a sick resident.}
#{101}{}{You see a slum dweller. His eyes are sunken, his body is thin and bony, and his face looks mired in depression.}
{101}{}{你看到一个贫民窟的居民。他的眼睛凹陷，身体瘦骨嶙峋，脸上看起来深陷抑郁之中。 -- You see a slum dweller. His eyes are sunken, his body is thin and bony, and his face looks mired in depression.}
#{102}{}{You earn experience for giving the correct diagnosis.}
{102}{}{你为正确的诊断赢得了经验。 -- You earn experience for giving the correct diagnosis.}
#{110}{}{[He barely even looks up] ...you want something?}
{110}{}{[他甚至都没抬头]…你想要什么吗？ -- [He barely even looks up] ...you want something?}
#{111}{}{You look unhealthy. What's wrong with you?}
{111}{}{你看起来不健康。你怎么了？ -- You look unhealthy. What's wrong with you?}
#{112}{}{No, nothing.}
{112}{}{不，没什么。 -- No, nothing.}
#{113}{}{Your guess is as good as mine. Sometimes I get a pounding headache for no reason, even at night. I get tired easily, but I can't sleep, and sometimes I get the weirdest feeling that I'm at looking at myself from *outside* myself.}
{113}{}{你的猜测和我的一样好。有时我会无缘无故地头痛，即使是在晚上。我很容易累，但我睡不着，有时我会有一种奇怪的感觉，我在从外面看自己。 -- Your guess is as good as mine. Sometimes I get a pounding headache for no reason, even at night. I get tired easily, but I can't sleep, and sometimes I get the weirdest feeling that I'm at looking at myself from *outside* myself.}
#{114}{}{Have you ever seen a doctor?}
{114}{}{你看过医生吗？ -- Have you ever seen a doctor?}
#{115}{}{That sounds awful. I'll stop talking about it.}
{115}{}{听起来糟透了。我不说了。 -- That sounds awful. I'll stop talking about it.}
#{116}{}{Huh. Well, I can't help you. Bye.}
{116}{}{呵呵。我帮不了你。再见。 -- Huh. Well, I can't help you. Bye.}
#{117}{}{Doctor? Ha! Welcome to Reno... The only city without a real doctor, I think. Sometimes Patrick helps sick people, but he's never heard of anything like this. I'm just trying to do as much as I can for my family with the time I have left.}
{117}{}{医生？哈！欢迎来到雷诺。。。唯一没有真正医生的城市，我想。有时帕特里克帮助病人，但他从没听说过这样的事。我只想在剩下的时间里尽我所能为我的家人做点什么。 -- Doctor? Ha! Welcome to Reno... The only city without a real doctor, I think. Sometimes Patrick helps sick people, but he's never heard of anything like this. I'm just trying to do as much as I can for my family with the time I have left.}
#{118}{}{I have some medical experience. Let me examine you.}
{118}{}{我有一些医疗经验。让我给你检查一下。 -- I have some medical experience. Let me examine you.}
#{119}{}{I won't waste any more of your time, then.}
{119}{}{我不会再浪费你的时间了。 -- I won't waste any more of your time, then.}
#{120}{}{[You examine the patient, but you have no idea what's wrong with him.]}
{120}{}{[你检查了病人，但你不知道他怎么了。] -- [You examine the patient, but you have no idea what's wrong with him.]}
#{121}{}{I can't do anything else here. I'll have to leave you for now.}
{121}{}{我在这里什么也做不了。我现在不得不离开你。 -- I can't do anything else here. I'll have to leave you for now.}
#{122}{}{[After a series of questions, you realize the patient is suffering from an incurable brain tumor] So what do you say, Doc? How much I have - a month, a year?}
{122}{}{[在一系列问题之后，你意识到病人患有无法治愈的脑瘤]那你怎么说，医生？我有多少-一个月，一年？ -- [After a series of questions, you realize the patient is suffering from an incurable brain tumor] So what do you say, Doc? How much I have - a month, a year?}
#{123}{}{Not long. The only way to save your life is to remove parts of your brain, but you'd be left with the intelligence of a brahmin. I'm sorry.}
{123}{}{不久。拯救你生命的唯一方法是切除你的部分大脑，但你会被留下一个婆罗门的智慧。我很抱歉。 -- Not long. The only way to save your life is to remove parts of your brain, but you'd be left with the intelligence of a brahmin. I'm sorry.}
#{124}{}{I'll give it to you straight. You have a couple more months left before your terminal symptoms begin. Your brain will turn to slush, and you'll suffer hallucinations and loss of vision. Then comes impotence, refusal of food, and exhaustion... Leading to death.}
{124}{}{我直接告诉你。在你的晚期症状开始之前，你还有几个月的时间。你的大脑会变成泥浆，你会产生幻觉和失去视力。然后是阳痿，拒绝进食，精疲力竭。。。导致死亡。 -- I'll give it to you straight. You have a couple more months left before your terminal symptoms begin. Your brain will turn to slush, and you'll suffer hallucinations and loss of vision. Then comes impotence, refusal of food, and exhaustion... Leading to death.}
#{125}{}{I see. Somehow, I knew I was close to the end. Thanks for making it clear to me, Doc.}
{125}{}{我懂了。不知怎的，我知道我快结束了。谢谢你告诉我，医生。 -- I see. Somehow, I knew I was close to the end. Thanks for making it clear to me, Doc.}
#{126}{}{Take care.}
{126}{}{当心。 -- Take care.}
#{127}{}{Oh my god! I didn't think it would be so bad! I thought I'd just go to sleep one night and not wake up... What am I going to do? Once I'm not able to walk to the toilet, I should just kill myself. Or ask someone else..}
{127}{}{哦，我的上帝！我没想到会这么糟！我想我只会睡一晚而不醒来。。。我该怎么办？一旦我不能走路上厕所，我就应该自杀。或者问别人。。 -- Oh my god! I didn't think it would be so bad! I thought I'd just go to sleep one night and not wake up... What am I going to do? Once I'm not able to walk to the toilet, I should just kill myself. Or ask someone else..}
#{128}{}{Well, that's your decision, not mine.}
{128}{}{好吧，那是你的决定，不是我的。 -- Well, that's your decision, not mine.}
#{130}{}{You couldn't have lived this long without medication. Where do you get it?}
{130}{}{没有药物你不可能活这么久。你从哪儿弄来的？ -- You couldn't have lived this long without medication. Where do you get it?}
#{131}{}{It doesn't matter. I can get what I need. Why do you care?}
{131}{}{没关系。我能得到我需要的。你为什么在乎？ -- It doesn't matter. I can get what I need. Why do you care?}
#{132}{}{Because I bet your dealer is making a lot of money off of your condition, and you might not be getting what you need.}
{132}{}{因为我敢打赌你的经销商从你的情况下赚了很多钱，而你可能得不到你需要的东西。 -- Because I bet your dealer is making a lot of money off of your condition, and you might not be getting what you need.}
#{133}{}{Fine.}
{133}{}{好的。 -- Fine.}
#{134}{}{Heh... It's not like I think he's doing it out of the goodness of his heart. What does it matter, anyway, as long as my pain goes away? His name's Solomon. He deals out back of the El Dorado. You be careful if you're going to talk to him. He's twitchy... And dangerous.}
{134}{}{嘿。。。我不认为他这么做是出于好心。不管怎样，只要我的痛苦消失了又有什么关系？他叫所罗门。他在埃尔多拉多的后面交易。你要跟他说话要小心。他在抽搐。。。而且很危险。 -- Heh... It's not like I think he's doing it out of the goodness of his heart. What does it matter, anyway, as long as my pain goes away? His name's Solomon. He deals out back of the El Dorado. You be careful if you're going to talk to him. He's twitchy... And dangerous.}
#{135}{}{I'll be careful.}
{135}{}{我会小心的。 -- I'll be careful.}
#{136}{}{How can there be no doctor in such a big city?}
{136}{}{这么大的城市怎么会没有医生？ -- How can there be no doctor in such a big city?}
#{137}{}{Don't get me wrong, there were plenty ten years ago. But after the civil war started, they were all recruited by one side or another, sometimes by force. They've all died in the tug-of-war since then. There was an Auto-Doc below the City Hall, but with so many people using it, it didn't last long. Now, the only medicine we get is from chem dealers, and they're killing us as much as they're helping us. I think the caravans import more chems than anything else.}
{137}{}{别误会，十年前有很多。但内战开始后，他们都被一方或另一方招募，有时是武力。从那以后他们都死于拔河。市政厅下面有一个自动文档，但是有这么多人在用，没用多久。现在，我们唯一能得到的药物是化学药品商，他们在帮助我们的同时也在杀死我们。我认为商队进口的化学品比其他任何东西都多。 -- Don't get me wrong, there were plenty ten years ago. But after the civil war started, they were all recruited by one side or another, sometimes by force. They've all died in the tug-of-war since then. There was an Auto-Doc below the City Hall, but with so many people using it, it didn't last long. Now, the only medicine we get is from chem dealers, and they're killing us as much as they're helping us. I think the caravans import more chems than anything else.}
#{1119}{}{I won't waste any more of your time, then.}
{1119}{}{我不会再浪费你的时间了。 -- I won't waste any more of your time, then.}
