#{100}{}{You see Essie Gate.}
{100}{}{你看到埃西·盖特了。 -- You see Essie Gate.}
#{101}{}{You see a woman with sad, far-away look in her eyes.}
{101}{}{你看到一个女人，眼睛里带着悲伤、遥远的神情。 -- You see a woman with sad, far-away look in her eyes.}
#{102}{}{Thank you! Thank you for everything!}
{102}{}{谢谢您！谢谢你所做的一切！ -- Thank you! Thank you for everything!}
#{103}{}{Thank you for your efforts, but we still have to go.}
{103}{}{谢谢你的努力，但我们还得走。 -- Thank you for your efforts, but we still have to go.}
#{110}{}{[The woman looks up quickly when you enter the room, but when she sees you, only gives you a look of empty disappointment] Oh... If you're selling something, we're not buying. Or joining.}
{110}{}{[当你走进房间时，那个女人很快抬起头来，但当她看到你时，只给了你一个空洞失望的眼神]哦。。。如果你要卖东西，我们不买。或者加入。 -- [The woman looks up quickly when you enter the room, but when she sees you, only gives you a look of empty disappointment] Oh... If you're selling something, we're not buying. Or joining.}
#{111}{}{No, I just wanted to ask a local a few questions.}
{111}{}{不，我只是想问当地人几个问题。 -- No, I just wanted to ask a local a few questions.}
#{112}{}{Then you and I have nothing to talk about. [Leave]}
{112}{}{那我们就没什么好谈的了。[离开] -- Then you and I have nothing to talk about. [Leave]}
#{113}{}{Oh, you're not local? Sorry for my poor welcome, but you don't meet friendly strangers very often in Reno. What do you want?}
{113}{}{哦，你不是本地人？很抱歉我不欢迎你，但你在雷诺很少见到友好的陌生人。你想要什么？ -- Oh, you're not local? Sorry for my poor welcome, but you don't meet friendly strangers very often in Reno. What do you want?}
#{114}{}{Yes?}
{114}{}{对？ -- Yes?}
#{115}{}{Who are you?}
{115}{}{你是谁？ -- Who are you?}
#{116}{}{Can you tell me about the city?}
{116}{}{你能告诉我这个城市的情况吗？ -- Can you tell me about the city?}
#{117}{}{Sorry, we'll talk some other time.}
{117}{}{对不起，我们改天再谈。 -- Sorry, we'll talk some other time.}
#{118}{}{Let's talk about something else.}
{118}{}{我们再谈点别的吧。 -- Let's talk about something else.}
#{119}{}{}
{119}{}{ -- }
#{120}{}{Essie Gate. I'm just a housewife... So don't get any ideas.}
{120}{}{埃西门。我只是个家庭主妇。。。所以不要有任何想法。 -- Essie Gate. I'm just a housewife... So don't get any ideas.}
#{121}{}{What's there to tell? Walk around Reno and see everything you need to know. There's not much worth, and what little there is, everyone's already fighting over. But it's still better than the rest of Nevada, so what choice do we have?}
{121}{}{有什么好说的？绕着雷诺走一圈，看看你想知道的一切。没有多少价值，也没有多少价值，每个人都在为之奋斗。但它仍然比内华达州的其他地方好，那我们还有什么选择呢？ -- What's there to tell? Walk around Reno and see everything you need to know. There's not much worth, and what little there is, everyone's already fighting over. But it's still better than the rest of Nevada, so what choice do we have?}
#{122}{}{}
{122}{}{ -- }
#{123}{}{}
{123}{}{ -- }
#{124}{}{What's the story with your husband, again?}
{124}{}{你丈夫又怎么了？ -- What's the story with your husband, again?}
#{125}{}{About the situation with your husband... }
{125}{}{关于你丈夫的情况。。。 -- About the situation with your husband... }
#{126}{}{I'm new here. Can you tell me how to get settled in this town?}
{126}{}{我是新来的。你能告诉我怎么在这个镇上定居吗？ -- I'm new here. Can you tell me how to get settled in this town?}
#{127}{}{I have a note from a certain Robert that lived here. Do these mean anything to you?}
{127}{}{我有个住在这里的罗伯特的字条。这些对你有什么意义吗？ -- I have a note from a certain Robert that lived here. Do these mean anything to you?}
#{128}{}{}
{128}{}{ -- }
#{129}{}{}
{129}{}{ -- }
#{130}{}{I'm new here. Can you tell me how to get settled in this town?}
{130}{}{我是新来的。你能告诉我怎么在这个镇上定居吗？ -- I'm new here. Can you tell me how to get settled in this town?}
#{131}{}{I can't help you. But... If you don't mind... Oh, never mind. I have nothing to pay you anyway.}
{131}{}{我帮不了你。但是。。。如果你不介意。。。哦，没关系。反正我也没钱付你。 -- I can't help you. But... If you don't mind... Oh, never mind. I have nothing to pay you anyway.}
#{132}{}{Can't pay? Well, then we have nothing to talk about.}
{132}{}{付不起？好吧，那我们就没什么好谈的了。 -- Can't pay? Well, then we have nothing to talk about.}
#{133}{}{If you have nothing to pay, then pay me nothing. Tell me what you need.}
{133}{}{如果你没有什么要付的，那就什么也不付我。告诉我你需要什么。 -- If you have nothing to pay, then pay me nothing. Tell me what you need.}
#{134}{}{Just spit it and *I'll* decide whether I want to do it, okay?}
{134}{}{吐出来，我来决定我是否要做，好吗？ -- Just spit it and *I'll* decide whether I want to do it, okay?}
#{135}{}{[The woman sighs heavily, closing her eyes] I overheard Robert talking to Mark about going to some military base. I can only guess what happened to him. I didn't want to let him go, but how could I stop him? Mr. Wright gave the order himself!}
{135}{}{[那女人重重地叹了口气，闭上眼睛]我无意中听到罗伯特和马克谈论去某个军事基地的事。我只能猜他发生了什么事。我不想让他走，但我怎么能阻止他？赖特先生亲自下的命令！ -- [The woman sighs heavily, closing her eyes] I overheard Robert talking to Mark about going to some military base. I can only guess what happened to him. I didn't want to let him go, but how could I stop him? Mr. Wright gave the order himself!}
#{136}{}{Okay, wait, wait, wait, now slow down and tell me exactly what happened!}
{136}{}{好了，等等，等等，现在慢点告诉我到底发生了什么！ -- Okay, wait, wait, wait, now slow down and tell me exactly what happened!}
#{137}{}{Oh, sorry... }
{137}{}{哦，对不起。。。 -- Oh, sorry... }
#{138}{}{Who's Robert?}
{138}{}{罗伯特是谁？ -- Who's Robert?}
#{139}{}{Who's Mark?}
{139}{}{马克是谁？ -- Who's Mark?}
#{140}{}{Who is this Mr. Wright?}
{140}{}{怀特先生是谁？ -- Who is this Mr. Wright?}
#{141}{}{What kind of order?}
{141}{}{什么样的订单？ -- What kind of order?}
#{142}{}{What kind of military base?}
{142}{}{什么样的军事基地？ -- What kind of military base?}
#{143}{}{Do you think something happened to Robert?}
{143}{}{你觉得罗伯特出事了吗？ -- Do you think something happened to Robert?}
#{144}{}{That's all I need.}
{144}{}{这就是我所需要的。 -- That's all I need.}
#{145}{}{Robert is my husband. He's a... A prospector, is what they call them. He looks for useful pre-war things in old ruins, then sells them to merchants.}
{145}{}{罗伯特是我丈夫。他是个。。。他们称之为探矿者。他在旧废墟中寻找战前有用的东西，然后卖给商人。 -- Robert is my husband. He's a... A prospector, is what they call them. He looks for useful pre-war things in old ruins, then sells them to merchants.}
#{146}{}{He was my husband's partner. A prospector, like Robert, just less experienced.}
{146}{}{他是我丈夫的搭档。像罗伯特这样的探矿者，只是经验不足。 -- He was my husband's partner. A prospector, like Robert, just less experienced.}
#{147}{}{Be happy you don't know who Mr. Wright is. He's one of Reno's business leaders. He owns these slums, meaning he owns us.}
{147}{}{很高兴你不知道赖特先生是谁。他是雷诺的商业领袖之一。他拥有这些贫民窟，也就是说他拥有我们。 -- Be happy you don't know who Mr. Wright is. He's one of Reno's business leaders. He owns these slums, meaning he owns us.}
#{148}{}{I don't know. Mr. Wright needed something from the military base, but no one's ever gotten in. He hired Robert and his partner to be the first.}
{148}{}{我不知道。赖特先生需要军事基地的东西，但没人能进去。他雇用罗伯特和他的合伙人做第一个。 -- I don't know. Mr. Wright needed something from the military base, but no one's ever gotten in. He hired Robert and his partner to be the first.}
#{149}{}{Hawthorne, I think it's called. I don't know much about it, but they say no one's been inside since the War. Robert knew more.}
{149}{}{霍桑，我想应该叫它。我不太清楚，但他们说战后没人在里面。罗伯特知道更多。 -- Hawthorne, I think it's called. I don't know much about it, but they say no one's been inside since the War. Robert knew more.}
#{150}{}{Robert always sent us messages while he was out in the wasteland. But we... We haven't heard anything in a long time... }
{150}{}{罗伯特在荒地里时总是给我们发信息。但是我们。。。我们很久没听到任何消息了。。。 -- Robert always sent us messages while he was out in the wasteland. But we... We haven't heard anything in a long time... }
#{151}{}{So you will help us to find Robert?}
{151}{}{你能帮我们找到罗伯特吗？ -- So you will help us to find Robert?}
#{152}{}{First I need more information.}
{152}{}{首先我需要更多的信息。 -- First I need more information.}
#{153}{}{Oh, of course... }
{153}{}{哦，当然。。。 -- Oh, of course... }
#{154}{}{I'll be glad to help you.}
{154}{}{我很乐意帮助你。 -- I'll be glad to help you.}
#{155}{}{No, I don't have time to do it. [Leave]}
{155}{}{不，我没时间做。[离开] -- No, I don't have time to do it. [Leave]}
#{156}{}{Oh, thank you! Robert left these coordinates behind. I don't know what they mean, but I'm sure you'll understand. Please, be careful..}
{156}{}{哦，谢谢你！罗伯特留下了这些坐标。我不知道它们是什么意思，但我相信你会理解的。拜托，小心点。。 -- Oh, thank you! Robert left these coordinates behind. I don't know what they mean, but I'm sure you'll understand. Please, be careful..}
#{157}{}{Okay. Let's see what's what.}
{157}{}{可以。让我们看看是什么。 -- Okay. Let's see what's what.}
#{158}{}{[Her eyes momentarily light up with hope, but it immediately disappears] Yes?}
{158}{}{[她的眼睛瞬间充满希望，但立即消失]是吗？ -- [Her eyes momentarily light up with hope, but it immediately disappears] Yes?}
#{159}{}{I need more information.}
{159}{}{我需要更多的信息。 -- I need more information.}
#{160}{}{What?! What is this?! Show me, now!}
{160}{}{什么？！这是什么？！快给我看！ -- What?! What is this?! Show me, now!}
#{161}{}{Not so fast, woman. This delivery is worth money... }
{161}{}{别那么快，女人。这次运送物有所值。。。 -- Not so fast, woman. This delivery is worth money... }
#{162}{}{Of course. Take it.}
{162}{}{当然。拿去吧。 -- Of course. Take it.}
#{163}{}{Uh, shoot, I left it somewhere. I'll be right back.}
{163}{}{呃，天哪，我把它忘在什么地方了。我马上回来。 -- Uh, shoot, I left it somewhere. I'll be right back.}
#{164}{}{[She snaps up her last stash of money and shakes out }
{164}{}{[她抢走了最后一笔钱，摇摇晃晃地走了出去 -- [She snaps up her last stash of money and shakes out }
#{165}{}{ dollars] Here! It's all we have. Now give me that note!}
{165}{}{这里！我们只有这些了。把那张纸条给我！ --  dollars] Here! It's all we have. Now give me that note!}
#{166}{}{Is that all?! Hell, I risked my own life! Give me that picture, that pile of books and a fresh sandwich from the table, and *then* I'll give you the note.}
{166}{}{就这些？！见鬼，我冒着生命危险！把那张照片，那堆书和桌上的一个新鲜三明治给我，然后我把纸条给你。 -- Is that all?! Hell, I risked my own life! Give me that picture, that pile of books and a fresh sandwich from the table, and *then* I'll give you the note.}
#{167}{}{Sure.}
{167}{}{当然。 -- Sure.}
#{168}{}{[He lowers her head, looking at you] I'll pay it. Every last crust of bread we have! Just give me the note!}
{168}{}{[他低下头，看着你]我来付。我们所有的面包皮！把纸条给我！ -- [He lowers her head, looking at you] I'll pay it. Every last crust of bread we have! Just give me the note!}
#{169}{}{[She silently reads the text, then wearily closes her eyes] I knew it... I knew it would end like this... }
{169}{}{[她默默地读着课文，然后疲惫地闭上眼睛]我知道。。。我知道结局会是这样。。。 -- [She silently reads the text, then wearily closes her eyes] I knew it... I knew it would end like this... }
#{170}{}{What?}
{170}{}{什么？ -- What?}
#{171}{}{I don't really care... }
{171}{}{我真的不在乎。。。 -- I don't really care... }
#{172}{}{[She doesn't seem to hear you] Sooner or later it had to happen. Robert was good, but a military base? No, it was too dangerous... Too, too dangerous... }
{172}{}{[她好像没听见你说的]迟早会发生的。罗伯特很好，但是一个军事基地？不，太危险了。。。太，太危险了。。。 -- [She doesn't seem to hear you] Sooner or later it had to happen. Robert was good, but a military base? No, it was too dangerous... Too, too dangerous... }
#{173}{}{You can say that again.}
{173}{}{说得好。 -- You can say that again.}
#{174}{}{But wait, where's Mark?!}
{174}{}{等等，马克在哪？！ -- But wait, where's Mark?!}
#{175}{}{Who?}
{175}{}{谁？ -- Who?}
#{176}{}{Robert's partner! He should know what happened there... If he's still alive.}
{176}{}{罗伯特的搭档！他应该知道那里发生了什么。。。如果他还活着。 -- Robert's partner! He should know what happened there... If he's still alive.}
#{177}{}{There was no second body. But why do you need him?}
{177}{}{没有第二具尸体。但你为什么需要他？ -- There was no second body. But why do you need him?}
#{178}{}{Listen... It's complicated. Our family lived off their work. They paid the rent and electricity by prospecting for Mr. Wright. Without them, our debts... We'll be lucky if he don't sell us into slavery. If Mark is alive, he could finish the job.}
{178}{}{听。。。这很复杂。我们家靠工作为生。他们通过寻找赖特先生来支付房租和电费。没有他们，我们的债务。。。如果他不把我们卖作奴隶，我们就很幸运了。如果马克还活着，他就可以完成这项工作。 -- Listen... It's complicated. Our family lived off their work. They paid the rent and electricity by prospecting for Mr. Wright. Without them, our debts... We'll be lucky if he don't sell us into slavery. If Mark is alive, he could finish the job.}
#{179}{}{What cruel laws you have here... }
{179}{}{你这里有多么残酷的法律。。。 -- What cruel laws you have here... }
#{180}{}{Oh, yes. Mr. Wright is a heartless man. But you can't blame him. We are really in debt to him.}
{180}{}{哦，是的。赖特先生是个无情的人。但你不能怪他。我们真的欠他的债。 -- Oh, yes. Mr. Wright is a heartless man. But you can't blame him. We are really in debt to him.}
#{181}{}{What if I talk to Wright?}
{181}{}{如果我和赖特谈谈呢？ -- What if I talk to Wright?}
#{182}{}{Maybe Mark's family knows something?}
{182}{}{也许马克的家人知道些什么？ -- Maybe Mark's family knows something?}
#{183}{}{I'll try to find Mark and solve the situation.}
{183}{}{我会设法找到马克并解决这个问题。 -- I'll try to find Mark and solve the situation.}
#{184}{}{I've fulfilled my part of the deal. This isn't my concern.}
{184}{}{我已经履行了我的义务。这不关我的事。 -- I've fulfilled my part of the deal. This isn't my concern.}
#{185}{}{To Mr. Wright? He's not someone you can just... "talk" to. If you are going to step into his house, I can only give you this advice: choose your words carefully.}
{185}{}{给赖特先生？他不是那种你可以与…交谈。如果你要走进他的家，我只能给你一个忠告：小心用词。 -- To Mr. Wright? He's not someone you can just... "talk" to. If you are going to step into his house, I can only give you this advice: choose your words carefully.}
#{186}{}{Maybe, but they won't talk to us. They got so angry... I don't know why.}
{186}{}{也许吧，但他们不会和我们说话。他们很生气。。。我不知道为什么。 -- Maybe, but they won't talk to us. They got so angry... I don't know why.}
#{187}{}{Oh, thank you. Please, bring us news soon.}
{187}{}{哦，谢谢你。请尽快给我们带来消息。 -- Oh, thank you. Please, bring us news soon.}
#{188}{}{Bye.}
{188}{}{再见。 -- Bye.}
#{189}{}{Yes, we understand... }
{189}{}{是的，我们明白。。。 -- Yes, we understand... }
#{190}{}{Bye.}
{190}{}{再见。 -- Bye.}
#{200}{}{About Mark.}
{200}{}{关于马克。 -- About Mark.}
#{201}{}{You learned something?}
{201}{}{你学到了什么？ -- You learned something?}
#{202}{}{Mark left the city and ran north somewhere. I don't think you'll ever see him again.}
{202}{}{马克离开了城市，往北跑去。我想你再也见不到他了。 -- Mark left the city and ran north somewhere. I don't think you'll ever see him again.}
#{203}{}{No, not yet.}
{203}{}{不，还没有。 -- No, not yet.}
#{204}{}{So he cut and run? He could have at least told us what happened to Robert! That bastard! That... No, I can't think about that now. We have to leave. If no one completes that contract, then Mr. Wright will come for us. And you... Thank you for trying to help us.}
{204}{}{所以他逃走了？他至少可以告诉我们罗伯特发生了什么事！那个混蛋！那个。。。不，我现在想不起来。我们得走了。如果没有人完成那份合同，那么莱特先生就会来找我们。和你。。。谢谢你帮助我们。 -- So he cut and run? He could have at least told us what happened to Robert! That bastard! That... No, I can't think about that now. We have to leave. If no one completes that contract, then Mr. Wright will come for us. And you... Thank you for trying to help us.}
#{205}{}{We'll see. Maybe there's still hope... }
{205}{}{我们拭目以待。也许还有希望。。。 -- We'll see. Maybe there's still hope... }
#{206}{}{Is that all? Hell, not even fed after the road... }
{206}{}{就这些吗？他妈的，在路上之后连饭都没吃。。。 -- Is that all? Hell, not even fed after the road... }
#{207}{}{Mark fled the city, but I talked him into coming back. That's not going to solve your problem, though... }
{207}{}{马克逃离了城市，但我说服他回来。但这不能解决你的问题。。。 -- Mark fled the city, but I talked him into coming back. That's not going to solve your problem, though... }
#{208}{}{}
{208}{}{ -- }
#{209}{}{}
{209}{}{ -- }
#{210}{}{You won't have to worry about your debts anymore. Wright is dead.}
{210}{}{你不用再为你的债务担心了。赖特死了。 -- You won't have to worry about your debts anymore. Wright is dead.}
#{211}{}{I have good news. Someone fulfilled your husband's contract, so Wright's called off your debt.}
{211}{}{我有个好消息。有人履行了你丈夫的合同，所以莱特取消了你的债务。 -- I have good news. Someone fulfilled your husband's contract, so Wright's called off your debt.}
#{212}{}{Oh my God! You think *this* is a solution?! What will happen to the slums now?! His sons will fight each other for them - and kill us all in the crossfire! We have to leave. At least, thank you for warning us. It gives us time to figure something out.}
{212}{}{哦，我的上帝！你认为这是个解决办法？！贫民窟现在会怎么样？！他的儿子们会为了他们互相争斗——在交火中把我们都杀了！我们得走了。至少，谢谢你提醒我们。这让我们有时间想办法。 -- Oh my God! You think *this* is a solution?! What will happen to the slums now?! His sons will fight each other for them - and kill us all in the crossfire! We have to leave. At least, thank you for warning us. It gives us time to figure something out.}
#{213}{}{You're welcome.}
{213}{}{不客气。 -- You're welcome.}
#{214}{}{What?! But how? ...it was you, wasn't it? Thank you, thank you! No one else would have done this for us! Wait... In Reno, everything has a price. If you don't know that yet - learn. [she holds out some sort of round device with wires sticking out of it] Robert wanted to improve his metal detector with this. We don't need it anymore, but maybe you can find a use for it. Again, thank you for everything! You've saved our lives!}
{214}{}{什么？！但是怎么做。。。是你，不是吗？谢谢，谢谢！没有人会为我们做这些！等待。。。在雷诺，一切都有代价。如果你还不知道-学习。[她拿出一种圆形装置，里面有电线伸出]罗伯特想用这个改进他的金属探测器。我们不再需要它了，但也许你能找到它的用处。再次感谢你所做的一切！你救了我们的命！ -- What?! But how? ...it was you, wasn't it? Thank you, thank you! No one else would have done this for us! Wait... In Reno, everything has a price. If you don't know that yet - learn. [she holds out some sort of round device with wires sticking out of it] Robert wanted to improve his metal detector with this. We don't need it anymore, but maybe you can find a use for it. Again, thank you for everything! You've saved our lives!}
#{215}{}{Take care.}
{215}{}{当心。 -- Take care.}
#{1166}{}{Is that all?! Hell, I risked my own life! Give me that picture, that pile of books and a fresh sandwich from the table, and *then* I'll give you the note.}
{1166}{}{就这些？！见鬼，我冒着生命危险！把那张照片，那堆书和桌上的一个新鲜三明治给我，然后我把纸条给你。 -- Is that all?! Hell, I risked my own life! Give me that picture, that pile of books and a fresh sandwich from the table, and *then* I'll give you the note.}
