#{100}{}{You see an audience member.}
{100}{}{你看到一个听众。 -- You see an audience member.}
#{101}{}{You see a member of the audience. He waits for the show.}
{101}{}{你看到一个观众。他在等演出。 -- You see a member of the audience. He waits for the show.}
#{102}{}{The spectators scatter in terror!}
{102}{}{观众吓得四散了！ -- The spectators scatter in terror!}
#{103}{}{What the hell?! Shit, better get out of here...}
{103}{}{我勒个去？！妈的，最好离开这里。。。 -- What the hell?! Shit, better get out of here...}
#{104}{}{The situation is safe now.}
{104}{}{现在情况安全了。 -- The situation is safe now.}
#{105}{}{Don't you dare touching me!}
{105}{}{你敢碰我！ -- Don't you dare touching me!}
#{106}{}{Ah geez... *hic* I drank too much again... Maybe I should *hic* lie down for a few minutes...}
{106}{}{啊，天啊。。。*我又喝多了。。。也许我应该躺几分钟。。。 -- Ah geez... *hic* I drank too much again... Maybe I should *hic* lie down for a few minutes...}
#{107}{}{Ooh... I shouldn't have had that drink... I've got to lie down.}
{107}{}{哦。。。我不该喝那种酒。。。我得躺下了。 -- Ooh... I shouldn't have had that drink... I've got to lie down.}
#{108}{}{Yeah, so... Justice can prevail, and stuff.}
{108}{}{是的，所以。。。正义可以战胜一切。 -- Yeah, so... Justice can prevail, and stuff.}
#{109}{}{You got the audience member drunk.}
{109}{}{你把听众灌醉了。 -- You got the audience member drunk.}
#{110}{}{Uh, hi.}
{110}{}{呃，你好。 -- Uh, hi.}
#{111}{}{[The man pulls his ballcap lower and tries to avoid eye contact.]}
{111}{}{[男子把球帽拉低，尽量避免目光接触。] -- [The man pulls his ballcap lower and tries to avoid eye contact.]}
#{112}{}{Where are you going?}
{112}{}{你要去哪里？ -- Where are you going?}
#{113}{}{Enjoy the show.}
{113}{}{好好享受表演吧。 -- Enjoy the show.}
#{114}{}{None of your business.}
{114}{}{不关你的事。 -- None of your business.}
#{115}{}{Actually, it is my business. I'm Patrick's bodyguard. If you have something to say to him, say it to me.}
{115}{}{实际上，这是我的事。我是帕特里克的保镖。如果你有话要跟他说，就跟我说。 -- Actually, it is my business. I'm Patrick's bodyguard. If you have something to say to him, say it to me.}
#{116}{}{Oh, I've got something to say to him, asshole, just not with you around. Now get the fuck out of my way.}
{116}{}{噢，我有话要跟他说，混蛋，只是你不在身边。现在他妈的给我让开。 -- Oh, I've got something to say to him, asshole, just not with you around. Now get the fuck out of my way.}
#{117}{}{What did you just call me?! You'd better leave before I get angry. You wouldn't like me when I'm angry.}
{117}{}{你刚才叫我什么？！你最好在我生气之前离开。我生气的时候你不会喜欢我的。 -- What did you just call me?! You'd better leave before I get angry. You wouldn't like me when I'm angry.}
#{118}{}{I'll let "asshole" slide this one time, for Patrick. Now go take your place. Or leave.}
{118}{}{我就让“混蛋”滑一次，为了帕特里克。现在去接替你的位置。或者离开。 -- I'll let "asshole" slide this one time, for Patrick. Now go take your place. Or leave.}
#{119}{}{You know what? I don't care. Do whatever you want.}
{119}{}{你知道吗？我不在乎。你想干什么就干什么。 -- You know what? I don't care. Do whatever you want.}
#{120}{}{Oh yeah, *asshole*? What are you going to do, kneel down and pray at me? [he pulls aside his jacket to reveal a pistol] Yeah, that's right. You and your boy don't belong in Reno. Now get your ass out of my way, before I reach down your throat, pull out your guts, and hang you with them.}
{120}{}{哦，是的，混蛋？你要做什么，跪下来向我祈祷？[他拉开夹克露出手枪]是的，没错。你和你儿子不属于雷诺。别挡我的路，趁我还没够到你的喉咙，把你的肠子掏出来，把你和他们一起吊死。 -- Oh yeah, *asshole*? What are you going to do, kneel down and pray at me? [he pulls aside his jacket to reveal a pistol] Yeah, that's right. You and your boy don't belong in Reno. Now get your ass out of my way, before I reach down your throat, pull out your guts, and hang you with them.}
#{121}{}{Now I'm going to take that gun from you and march you into the desert. Every time you slow down, I'm going to put a bullet in your body part, somewhere, that won't kill you. Just enough to hurt you bad enough to get you marching again. You're going to walk further than you ever walked in your life, because when you finally stop and you *can't* move any more, that's when I'm going to put a bullet in your head and walk back. No one here will even notice we're gone. In fact, I bet no one in the city will ever miss you. What do you think?}
{121}{}{现在我要把你的枪拿走，带你去沙漠。每次你慢下来，我都会在你身体的某个地方放一颗子弹，那不会杀了你。足以伤害你，让你再次行军。你会走得比你一生中走得更远，因为当你最终停下来，你再也不能动了，那时候我会用子弹打你的头，然后走回去。没人会注意到我们走了。事实上，我敢打赌城里没有人会想念你的。你怎么认为？ -- Now I'm going to take that gun from you and march you into the desert. Every time you slow down, I'm going to put a bullet in your body part, somewhere, that won't kill you. Just enough to hurt you bad enough to get you marching again. You're going to walk further than you ever walked in your life, because when you finally stop and you *can't* move any more, that's when I'm going to put a bullet in your head and walk back. No one here will even notice we're gone. In fact, I bet no one in the city will ever miss you. What do you think?}
#{122}{}{You say violent things. I do violent things. Last warning - this is your chance to leave.}
{122}{}{你说暴力的话。我做暴力的事。最后警告-这是你离开的机会。 -- You say violent things. I do violent things. Last warning - this is your chance to leave.}
#{123}{}{[He freezes up, eyes wide, then closes his jacket] You'd better hope I never catch you in a dark alley, asshole! [he gives you the middle finger and turns away]}
{123}{}{[他僵住了，睁大眼睛，然后合上夹克]你最好希望我永远不会在黑暗的巷子里抓住你，混蛋！[他给了你中指然后转身离开] -- [He freezes up, eyes wide, then closes his jacket] You'd better hope I never catch you in a dark alley, asshole! [he gives you the middle finger and turns away]}
#{124}{}{[Attack.]}
{124}{}{[攻击] -- [Attack.]}
#{125}{}{[Let him go.]}
{125}{}{[放开他。] -- [Let him go.]}
#{126}{}{He's too far.}
{126}{}{他太远了。 -- He's too far.}
#{1116}{}{Oh, I've got something to say to him, bitch, just not with you around. Now get the fuck out of my way.}
{1116}{}{哦，我有话要对他说，婊子，只是你不在身边。现在他妈的给我让开。 -- Oh, I've got something to say to him, bitch, just not with you around. Now get the fuck out of my way.}
#{1118}{}{I'll let "bitch" slide this one time, for Patrick. Now go take your place. Or leave.}
{1118}{}{我就让“婊子”滑一次，为了帕特里克。现在去接替你的位置。或者离开。 -- I'll let "bitch" slide this one time, for Patrick. Now go take your place. Or leave.}
#{1120}{}{Oh yeah, *bitch*? What are you going to do, kneel down and pray at me? [he pulls aside his jacket to reveal a pistol] Yeah, that's right. You and your boy don't belong in Reno. Now get your ass out of my way, before I reach down your throat, pull out your guts, and hang you with them.}
{1120}{}{哦，是吗，婊子？你要做什么，跪下来向我祈祷？[他拉开夹克露出手枪]是的，没错。你和你儿子不属于雷诺。别挡我的路，趁我还没够到你的喉咙，把你的肠子掏出来，把你和他们一起吊死。 -- Oh yeah, *bitch*? What are you going to do, kneel down and pray at me? [he pulls aside his jacket to reveal a pistol] Yeah, that's right. You and your boy don't belong in Reno. Now get your ass out of my way, before I reach down your throat, pull out your guts, and hang you with them.}
#{1123}{}{[He hesitates for a second, watching you, then steps back] You'd better hope I never catch you in a dark alley, bitch! [he gives you the middle finger and turns away]}
{1123}{}{[他犹豫了一下，看着你，然后退后一步]你最好希望我永远不会在黑暗的巷子里抓住你，婊子！[他给了你中指然后转身离开] -- [He hesitates for a second, watching you, then steps back] You'd better hope I never catch you in a dark alley, bitch! [he gives you the middle finger and turns away]}
