#{100}{}{You see Terry Deveraux.}
{100}{}{你看到特里·德弗罗了。 -- You see Terry Deveraux.}
#{101}{}{You see a short, balding man. It looks like fortune handed him the short end of the stick.}
{101}{}{你看到一个矮个子秃顶的男人。看来命运给了他一根短棒。 -- You see a short, balding man. It looks like fortune handed him the short end of the stick.}
#{102}{}{Ohh, we should probably hurry.}
{102}{}{哦，我们应该快点。 -- Ohh, we should probably hurry.}
