#{100}{}{You see a guard.}
{100}{}{你看到一个警卫。 -- You see a guard.}
#{101}{}{You see the club security. His job is to be invisible until he's needed.}
{101}{}{你看到俱乐部保安了。他的工作是在需要他之前不被人发现。 -- You see the club security. His job is to be invisible until he's needed.}
#{102}{}{Sir, I am unlikely to be able to help you.}
{102}{}{先生，我不太可能帮你。 -- Sir, I am unlikely to be able to help you.}
#{103}{}{Ma'am, I am unlikely to be able to help you.}
{103}{}{夫人，我不太可能帮你。 -- Ma'am, I am unlikely to be able to help you.}
#{104}{}{[He smiles and nods]}
{104}{}{[他微笑着点头] -- [He smiles and nods]}
