#{100}{}{This is Chris Avellone.}
{100}{}{我是克里斯·阿维隆。 -- This is Chris Avellone.}
#{101}{}{You see Chris Avellone himself!}
{101}{}{你看到克里斯·阿维隆了！ -- You see Chris Avellone himself!}
#{102}{}{This is Feargus Urquhart.}
{102}{}{我是费格斯·厄克哈特。 -- This is Feargus Urquhart.}
#{103}{}{You see Feargus Urquhart himself!}
{103}{}{你看到了费格斯·厄克哈特本人！ -- You see Feargus Urquhart himself!}
#{110}{}{Chris, what the hell!? Who did this!?}
{110}{}{克里斯，怎么回事！？是谁干的！？ -- Chris, what the hell!? Who did this!?}
#{111}{}{Mmm... What's wrong THIS time?}
{111}{}{嗯。。。这次怎么了？ -- Mmm... What's wrong THIS time?}
#{112}{}{What's wrong!? The thing is stuffed with bugs - that's what's wrong! Beta testers are ripping their hair out!}
{112}{}{怎么了！？这东西塞满了虫子-这就是问题所在！测试人员正在把他们的头发扯下来！ -- What's wrong!? The thing is stuffed with bugs - that's what's wrong! Beta testers are ripping their hair out!}
#{113}{}{That's okay, boss, we'll fix that.}
{113}{}{没关系，老板，我们会解决的。 -- That's okay, boss, we'll fix that.}
#{114}{}{Grr... Let's assume this. And what's with the car?! Why does it disappear all the time?!}
{114}{}{Grr。。。让我们假设一下。那车怎么了？！为什么它总是消失？！ -- Grr... Let's assume this. And what's with the car?! Why does it disappear all the time?!}
#{115}{}{Err, the engine is a little rough...}
{115}{}{呃，引擎有点粗糙。。。 -- Err, the engine is a little rough...}
#{116}{}{Ooh, the engine! Fix it then, you goddamn nerds!}
{116}{}{哦，引擎！那就修好吧，你们这些该死的书呆子！ -- Ooh, the engine! Fix it then, you goddamn nerds!}
#{117}{}{At least we have a car in the game. That's cool...}
{117}{}{至少我们在比赛中有一辆车。太酷了。。。 -- At least we have a car in the game. That's cool...}
#{118}{}{Cool, yeah. Especially the fact that it doesn't drive!}
{118}{}{酷，是的。尤其是它不能开车！ -- Cool, yeah. Especially the fact that it doesn't drive!}
#{119}{}{Well, the engine is limited. The programmers insisted.}
{119}{}{嗯，引擎是有限的。程序员们坚持说。 -- Well, the engine is limited. The programmers insisted.}
#{120}{}{Damn right they did! So much work, and half of our scripts is broken!}
{120}{}{他们说得对！这么多工作，我们一半的剧本都坏了！ -- Damn right they did! So much work, and half of our scripts is broken!}
#{121}{}{Anything else?}
{121}{}{还有别的吗？ -- Anything else?}
#{122}{}{ELSE? Yes, I have a whole novel of your unfilled plot holes!}
{122}{}{还有别的吗？是的，我有一整本关于你未填补的情节漏洞的小说！ -- ELSE? Yes, I have a whole novel of your unfilled plot holes!}
#{123}{}{Such as?}
{123}{}{比如？ -- Such as?}
#{124}{}{For example, what's that stupidity with Myron? When did he manage to take over the drug business in Reno?}
{124}{}{例如，迈伦的愚蠢是什么？他什么时候接管了雷诺的毒品生意？ -- For example, what's that stupidity with Myron? When did he manage to take over the drug business in Reno?}
#{125}{}{Well, he, uh, he's a genius...}
{125}{}{他是个天才。。。 -- Well, he, uh, he's a genius...}
#{126}{}{Uh-huh, yeah-yeah. That explains everything. Okay, actually it counts as an excuse.}
{126}{}{嗯，是的。这就解释了一切。好吧，实际上这算是个借口。 -- Uh-huh, yeah-yeah. That explains everything. Okay, actually it counts as an excuse.}
#{127}{}{No, he really is a genius...}
{127}{}{不，他真的是个天才。。。 -- No, he really is a genius...}
#{128}{}{Also, there's, like, five more locations not done!}
{128}{}{还有，还有五个地方还没完工！ -- Also, there's, like, five more locations not done!}
#{129}{}{Mhm... Which is the fifth one, boss?}
{129}{}{嗯。。。哪一个是第五个，老板？ -- Mhm... Which is the fifth one, boss?}
#{130}{}{Err... What are the first four?}
{130}{}{呃。。。前四个是什么？ -- Err... What are the first four?}
#{131}{}{That's what I'm asking, which ones...}
{131}{}{这就是我要问的，哪些。。。 -- That's what I'm asking, which ones...}
#{132}{}{Fine, forget it. Don't write something about EPA or Sulik's village, if they don't exist!}
{132}{}{好吧，算了吧。不要写关于环保署或苏利克村的东西，如果他们不存在的话！ -- Fine, forget it. Don't write something about EPA or Sulik's village, if they don't exist!}
#{133}{}{Come on, boss, the players will love it! They'll be encouraged to start modding.}
{133}{}{加油，老大，队员们会喜欢的！他们会被鼓励开始改装。 -- Come on, boss, the players will love it! They'll be encouraged to start modding.}
#{134}{}{Then throw the mapper at them, and some tools. And what about the intro!? Nonsense!}
{134}{}{然后向他们扔地图和一些工具。那介绍呢！？胡说！ -- Then throw the mapper at them, and some tools. And what about the intro!? Nonsense!}
#{135}{}{A boy coming out of vault? Yeah, we should remake that.}
{135}{}{一个男孩从地下室出来？是的，我们应该重拍。 -- A boy coming out of vault? Yeah, we should remake that.}
#{136}{}{Exactly!}
{136}{}{确切地！ -- Exactly!}
#{137}{}{On the other hand, we have Armstrong, and also implemented sex.}
{137}{}{另一方面，我们有阿姆斯特朗，也实施了性。 -- On the other hand, we have Armstrong, and also implemented sex.}
#{138}{}{[Rolls his eyes] ...Implemented sex...}
{138}{}{[翻白眼]…实施性行为。。。 -- [Rolls his eyes] ...Implemented sex...}
#{139}{}{Uh?..}
{139}{}{休斯敦大学？。。 -- Uh?..}
#{140}{}{What? Oh, yes. Stop being lazy!}
{140}{}{什么？哦，是的。别偷懒了！ -- What? Oh, yes. Stop being lazy!}
#{141}{}{Okay. And what about the game in general?}
{141}{}{可以。一般来说，游戏怎么样？ -- Okay. And what about the game in general?}
#{142}{}{Well, you know, despite the bugs, I think that Fallout 2... Will live forever.}
{142}{}{好吧，你知道，尽管有虫子，我认为辐射2。。。将永远活下去。 -- Well, you know, despite the bugs, I think that Fallout 2... Will live forever.}
#{143}{}{Only until the era of 3D comes, and then...}
{143}{}{直到3D时代到来，然后。。。 -- Only until the era of 3D comes, and then...}
#{144}{}{What an interesting thought! Develop it further.}
{144}{}{多么有趣的想法！进一步发展。 -- What an interesting thought! Develop it further.}
#{145}{}{Develop?}
{145}{}{发展？ -- Develop?}
#{146}{}{Well, put more dialogue somewhere. To the dwarf in the New Reno boxing ring, for example.}
{146}{}{好吧，把更多的对话放在某个地方。比如在新里诺拳击场的侏儒。 -- Well, put more dialogue somewhere. To the dwarf in the New Reno boxing ring, for example.}
#{147}{}{Oh. Yeah, he conveniently has a dialogue branch with bullying...}
{147}{}{哦。是的，他有一个与欺凌的对话分支。。。 -- Oh. Yeah, he conveniently has a dialogue branch with bullying...}
#{148}{}{Great, get to work.}
{148}{}{太好了，开始工作吧。 -- Great, get to work.}
#{149}{}{Any more stupid instructions, boss?}
{149}{}{还有什么愚蠢的指示吗，老板？ -- Any more stupid instructions, boss?}
#{150}{}{Let me have a look. A-ha, here! Here!}
{150}{}{让我看看。哈哈，这里！在这里！ -- Let me have a look. A-ha, here! Here!}
#{151}{}{What is it?}
{151}{}{这是怎么一回事？ -- What is it?}
