#{100}{}{You pull the balaclava over your head.}
{100}{}{你把巴拉克拉过你的头。 -- You pull the balaclava over your head.}
#{101}{}{You pull the balaclava off your head.}
{101}{}{你把巴拉克拉瓦从你头上拔下来。 -- You pull the balaclava off your head.}
#{102}{}{The balaclava is off your head.}
{102}{}{巴拉克拉瓦从你头上掉下来了。 -- The balaclava is off your head.}
#{103}{}{Your balaclava is in your bag because it is incompatible with your other currently equipped items.}
{103}{}{你的巴拉克拉瓦在你的包里，因为它与你目前装备的其他物品不兼容。 -- Your balaclava is in your bag because it is incompatible with your other currently equipped items.}
#{104}{}{You cannot put on the balaclava. It is incompatible with your other equipped items.}
{104}{}{你不能戴上巴拉克拉瓦。它与您的其他装备不兼容。 -- You cannot put on the balaclava. It is incompatible with your other equipped items.}
#{105}{}{Your balaclava won't be very convincing while you're wearing a Luciano ranch security jacket.}
{105}{}{当你穿着卢西亚诺农场的安全夹克时，你的巴拉克拉瓦不会很有说服力。 -- Your balaclava won't be very convincing while you're wearing a Luciano ranch security jacket.}
#{106}{}{That mask doesn't fool me! I know who you are!}
{106}{}{那个面具骗不了我！我知道你是谁！ -- That mask doesn't fool me! I know who you are!}
#{107}{}{You've caused a ruckus with one of the casino's Tommy guns. Luciano will be pleased.}
{107}{}{你用赌场的汤米枪引起了骚动。卢西亚诺会很高兴的。 -- You've caused a ruckus with one of the casino's Tommy guns. Luciano will be pleased.}
