#{100}{}{A small generator. If you have the time, you could enjoy looking at it a little more.}
{100}{}{小型发电机。如果你有时间，你可以多看看。 -- A small generator. If you have the time, you could enjoy looking at it a little more.}
#{101}{}{You examine the generator, but don't learn anything interesting.}
{101}{}{你检查发电机，但没有学到任何有趣的东西。 -- You examine the generator, but don't learn anything interesting.}
#{102}{}{This generator does not need repairs.}
{102}{}{这台发电机不需要修理。 -- This generator does not need repairs.}
#{103}{}{Examining the generator you determine that it was, together with the other computer equipment, moved here from another place.}
{103}{}{通过检查发电机，你确定它和其他计算机设备是从另一个地方搬到这里的。 -- Examining the generator you determine that it was, together with the other computer equipment, moved here from another place.}
#{104}{}{Interesting, but useless...}
{104}{}{有趣，但没用。。。 -- Interesting, but useless...}
