#{100}{}{You see brahmin.}
{100}{}{你看婆罗门。 -- You see brahmin.}
#{101}{}{You see a normal brahmin.}
{101}{}{你看到一个正常的婆罗门。 -- You see a normal brahmin.}
#{102}{}{}
{102}{}{ -- }
#{103}{}{Moo-o!}
{103}{}{呜呜！ -- Moo-o!}
#{104}{}{Moo!}
{104}{}{哞！ -- Moo!}
#{105}{}{The brahmin are in the pen, where they are supposed to be.}
{105}{}{婆罗门在围栏里，他们应该在那里。 -- The brahmin are in the pen, where they are supposed to be.}
#{106}{}{You do not have enough strength to make the brahmin move. Perhaps they'll understand more familiar language of a cattle prod.}
{106}{}{你没有足够的力量使婆罗门移动。也许他们能听懂更熟悉的牛戳的语言。 -- You do not have enough strength to make the brahmin move. Perhaps they'll understand more familiar language of a cattle prod.}
#{107}{}{Brahmin returned to the corral.}
{107}{}{婆罗门回到畜栏。 -- Brahmin returned to the corral.}
