#{101}{}{The books, pamphlets and writing on these shelves may tell more about the history of Bridgeport.}
{101}{}{这些书架上的书籍、小册子和文字可能会更多地讲述布里奇波特的历史。 -- The books, pamphlets and writing on these shelves may tell more about the history of Bridgeport.}
#{102}{}{You cannot read in combat.}
{102}{}{你不能在战斗中阅读。 -- You cannot read in combat.}
#{103}{}{With your education it would be too difficult and utterly boring to dig in such a large quantity of papers.}
{103}{}{在你的教育背景下，翻阅这么多的论文太难了，也太无聊了。 -- With your education it would be too difficult and utterly boring to dig in such a large quantity of papers.}
#{104}{}{A greater understanding of scientific principles are required to use this computer.}
{104}{}{使用这台计算机需要对科学原理有更深入的了解。 -- A greater understanding of scientific principles are required to use this computer.}
#{105}{}{You will need not only your hands, but the also your head, to examine publications on these shelves.}
{105}{}{你不仅需要你的手，还需要你的头来检查这些书架上的出版物。 -- You will need not only your hands, but the also your head, to examine publications on these shelves.}
#{110}{}{These shelves are completely lined with a variety of pre-war pamphlets and books, as well as the personal records of the last owner. In general, these materials cover the history of Bridgeport.}
{110}{}{这些书架上摆满了各种战前的小册子和书籍，以及最后一位主人的个人记录。一般来说，这些材料涵盖了布里奇波特的历史。 -- These shelves are completely lined with a variety of pre-war pamphlets and books, as well as the personal records of the last owner. In general, these materials cover the history of Bridgeport.}
#{111}{}{Read the section on the pre-war history of the settlement.}
{111}{}{阅读关于战前定居点历史的部分。 -- Read the section on the pre-war history of the settlement.}
#{112}{}{Read the section on the year 2077.}
{112}{}{阅读2077年的章节。 -- Read the section on the year 2077.}
#{113}{}{Read the section on the postwar history of the settlement.}
{113}{}{阅读关于战后殖民地历史的章节。 -- Read the section on the postwar history of the settlement.}
#{114}{}{Leave.}
{114}{}{离开。 -- Leave.}
#{115}{}{It was a small town, inhabited mainly by two types of citizens - rich families and spa workers. Bridgeport was famous for its mountain resorts, including lakes filled with trout and pristine snowy slopes. A quiet place, almost a paradise, a place for a carefree life. Partly because of this a number of well-off citizens of Nevada and California made their vacation homes here for various holidays and weekends.}
{115}{}{这是一个小镇，主要居住着两种类型的市民-富裕家庭和温泉工人。布里奇波特以其山地度假胜地而闻名，包括布满鳟鱼的湖泊和原始的雪坡。一个安静的地方，几乎是一个天堂，一个无忧无虑的生活的地方。部分原因是，内华达州和加利福尼亚州的一些富裕市民在这里度假，度过各种各样的假期和周末。 -- It was a small town, inhabited mainly by two types of citizens - rich families and spa workers. Bridgeport was famous for its mountain resorts, including lakes filled with trout and pristine snowy slopes. A quiet place, almost a paradise, a place for a carefree life. Partly because of this a number of well-off citizens of Nevada and California made their vacation homes here for various holidays and weekends.}
#{116}{}{Judging from the scraps of information, during the Great War, the village was completely wiped out due to radiation. Local residents had nowhere to shelter from radiation, brought by winds from the destroyed nuclear explosions of Los Angeles to the south and Zone 51 in the north-east. Realizing their doomed situation, many residents had arranged a celebration right on the streets of the city as a farewell to life, choosing to face death with with a smile on their face.}
{116}{}{从零碎的信息来看，在大战期间，这个村庄由于核辐射而完全消失了。由于洛杉矶南部和东北部51区核爆炸造成的大风，当地居民无处躲避辐射。许多居民意识到自己的命运，就在城市的街道上安排了一个庆祝活动，作为对生命的告别，他们选择面带微笑地面对死亡。 -- Judging from the scraps of information, during the Great War, the village was completely wiped out due to radiation. Local residents had nowhere to shelter from radiation, brought by winds from the destroyed nuclear explosions of Los Angeles to the south and Zone 51 in the north-east. Realizing their doomed situation, many residents had arranged a celebration right on the streets of the city as a farewell to life, choosing to face death with with a smile on their face.}
#{117}{}{The village has probably been uninhabited since the day when the population was wiped out in 2077. Less than ten years ago, the first settlers returned life to this village - the refugees from Reno.}
{117}{}{从2077年人口被消灭的那一天起，这个村庄就可能一直无人居住。不到十年前，第一批定居者回到了这个村庄——里诺的难民。 -- The village has probably been uninhabited since the day when the population was wiped out in 2077. Less than ten years ago, the first settlers returned life to this village - the refugees from Reno.}
