#{100}{}{A frenzied raider.}
{100}{}{疯狂的袭击者。 -- A frenzied raider.}
#{101}{}{This is your first opponent in the raiders' ring.}
{101}{}{这是你在突袭者魔戒里的第一个对手。 -- This is your first opponent in the raiders' ring.}
#{102}{}{AHHH!!! SWEET PAIN!}
{102}{}{啊哈！！！甜蜜的痛苦！ -- AHHH!!! SWEET PAIN!}
#{103}{}{Is that all you got?!}
{103}{}{你就这些吗？！ -- Is that all you got?!}
#{104}{}{You're my bitch! You're my bitch!}
{104}{}{你是我的婊子！你是我的婊子！ -- You're my bitch! You're my bitch!}
#{105}{}{I'm gonna fuck you like I fucked your mother last night!}
{105}{}{我要和你上床就像我昨晚和你妈上床一样！ -- I'm gonna fuck you like I fucked your mother last night!}
#{106}{}{Let it bleed! HRAAUGH!!!}
{106}{}{让它流血！哈哈！！！ -- Let it bleed! HRAAUGH!!!}
#{107}{}{Somebody hold down this piece of shit! I'm gonna make this last!}
{107}{}{有人按住这狗屎！我要把这个留到最后！ -- Somebody hold down this piece of shit! I'm gonna make this last!}
#{108}{}{You're not sick, are you? 'CUZ I'M GONNA EAT YOUR LIVER AND WASH IT DOWN WITH YOUR BLOOD!}
{108}{}{你没生病吧？”因为我要吃掉你的肝脏，用你的血把它洗掉！ -- You're not sick, are you? 'CUZ I'M GONNA EAT YOUR LIVER AND WASH IT DOWN WITH YOUR BLOOD!}
#{109}{}{Goddamn...}
{109}{}{他妈的。。。 -- Goddamn...}
#{110}{}{I'LL SEE YOU IN HELL!!!}
{110}{}{在地狱见！！！ -- I'LL SEE YOU IN HELL!!!}
#{113}{}{Get ready, bitch! I'm gonna enjoy this!}
{113}{}{准备好，婊子！我会好好享受的！ -- Get ready, bitch! I'm gonna enjoy this!}
#{114}{}{I'll tear you apart!}
{114}{}{我要把你撕成碎片！ -- I'll tear you apart!}
#{200}{}{Hey! What the hell are you doing over there?!}
{200}{}{嘿！你他妈的在那边干什么？！ -- Hey! What the hell are you doing over there?!}
#{201}{}{You've been spotted.}
{201}{}{你被发现了。 -- You've been spotted.}
#{202}{}{Mommy! Mommy!}
{202}{}{妈妈！妈妈！ -- Mommy! Mommy!}
#{203}{}{Shoo!}
{203}{}{嘘！ -- Shoo!}
#{204}{}{Faster!}
{204}{}{快点！ -- Faster!}
#{205}{}{Help!!!}
{205}{}{救命！！！ -- Help!!!}
#{206}{}{Aaaah!!!}
{206}{}{啊啊！！！ -- Aaaah!!!}
#{207}{}{Oh shit, a bomb!}
{207}{}{妈的，炸弹！ -- Oh shit, a bomb!}
#{208}{}{Goddamn lowlife!}
{208}{}{该死的贱人！ -- Goddamn lowlife!}
#{210}{}{Children disperse at the sight of your dubious trinkets.}
{210}{}{孩子们一看到你可疑的小饰物就四散了。 -- Children disperse at the sight of your dubious trinkets.}
#{1108}{}{You're not sick, are you, girl? 'CUZ I'M GONNA EAT YOUR LIVER AND WASH IT DOWN WITH YOUR BLOOD!}
{1108}{}{你没生病吧，姑娘因为我要吃掉你的肝脏，用你的血把它洗掉！ -- You're not sick, are you, girl? 'CUZ I'M GONNA EAT YOUR LIVER AND WASH IT DOWN WITH YOUR BLOOD!}
