#{100}{}{You see a door.}
{100}{}{你看到一扇门。 -- You see a door.}
#{101}{}{You see a door controlled by access control system with strict authorization policy.}
{101}{}{您会看到一个由具有严格授权策略的访问控制系统控制的门。 -- You see a door controlled by access control system with strict authorization policy.}
#{110}{}{Access granted}
{110}{}{已授予访问权限 -- Access granted}
#{111}{}{Access denied}
{111}{}{拒绝访问 -- Access denied}
#{112}{}{Security system blocks the door. Find a way to gain access.}
{112}{}{安全系统挡住了门。想办法进入。 -- Security system blocks the door. Find a way to gain access.}
#{113}{}{You already have access to this door.}
{113}{}{你已经可以进入这扇门了。 -- You already have access to this door.}
#{114}{}{No use}
{114}{}{没用 -- No use}
#{115}{}{You can't pick this complex protection mechanism with your bare hands. Use a lockpick or find other ways to gain access.}
{115}{}{你不能徒手去挑选这种复杂的保护机制。使用开锁器或其他方式进入。 -- You can't pick this complex protection mechanism with your bare hands. Use a lockpick or find other ways to gain access.}
#{116}{}{Lockpick or authorization required}
{116}{}{需要开锁或授权 -- Lockpick or authorization required}
#{117}{}{This door is locked with a multilayer protection system. It can be opened with a keycard or from the control center.}
{117}{}{这扇门是用多层保护系统锁着的。可以用钥匙卡或从控制中心打开。 -- This door is locked with a multilayer protection system. It can be opened with a keycard or from the control center.}
#{118}{}{You successfully pick this complicated electronic lock.}
{118}{}{你成功地选择了这个复杂的电子锁。 -- You successfully pick this complicated electronic lock.}
#{119}{}{}
{119}{}{ -- }
#{120}{}{Done}
{120}{}{多恩 -- Done}
#{121}{}{You fail to pick this complex protection mechanism.}
{121}{}{你不能选择这种复杂的保护机制。 -- You fail to pick this complex protection mechanism.}
#{122}{}{Fail}
{122}{}{失败 -- Fail}
#{123}{}{The keycard grants you access.}
{123}{}{钥匙卡允许你进入。 -- The keycard grants you access.}
