#{100}{}{You see: a citizen.}
{100}{}{你看：公民。 -- You see: a citizen.}
#{101}{}{You see a fellow citizen of Vault 8.}
{101}{}{你看到8号保险库的一位市民。 -- You see a fellow citizen of Vault 8.}
#{102}{}{No! Leave me alone! I'm not going out there!}
{102}{}{不！别管我！我不出去！ -- No! Leave me alone! I'm not going out there!}
#{103}{}{M-maybe we should just go back downstairs?}
{103}{}{也许我们应该下楼去？ -- M-maybe we should just go back downstairs?}
#{104}{}{Can't we hurry up and get this over with?!}
{104}{}{我们不能快点结束这一切吗？！ -- Can't we hurry up and get this over with?!}
#{110}{}{I'm not going... I'm not going... I'm not going...}
{110}{}{我不去。。。我不去。。。我不去。。。 -- I'm not going... I'm not going... I'm not going...}
#{111}{}{What's wrong with you? Pull yourself together, we have to go!}
{111}{}{你怎么了？振作起来，我们得走了！ -- What's wrong with you? Pull yourself together, we have to go!}
#{112}{}{Suit yourself. We'll do just fine without you.}
{112}{}{随便你。没有你我们也会过得很好。 -- Suit yourself. We'll do just fine without you.}
#{113}{}{NO! NO! I'M NOT GOING!!!}
{113}{}{不！不！我不去！！！ -- NO! NO! I'M NOT GOING!!!}
#{114}{}{Come on, it's not that scary.}
{114}{}{拜托，没那么可怕。 -- Come on, it's not that scary.}
#{115}{}{[Slap his face] Snap out of it, you coward!}
{115}{}{[拍拍他的脸]振作起来，你这个胆小鬼！ -- [Slap his face] Snap out of it, you coward!}
#{116}{}{Leave me alone! I... I can't... Why me? Why does it have to be me?}
{116}{}{别管我！一、 。。。我不能。。。为什么是我？为什么一定是我？ -- Leave me alone! I... I can't... Why me? Why does it have to be me?}
#{117}{}{Strange, that the Overseer assigned you to this job. But we need you anyway, so pull yourself together.}
{117}{}{奇怪的是，监工派你来做这项工作。但我们需要你，所以振作起来。 -- Strange, that the Overseer assigned you to this job. But we need you anyway, so pull yourself together.}
#{118}{}{Ow! Ow, stop! Leave me alone! You can't do this to me!}
{118}{}{噢！噢，住手！别管我！你不能这样对我！ -- Ow! Ow, stop! Leave me alone! You can't do this to me!}
#{119}{}{Whatever you're afraid of out there, you should be more afraid of *me*.}
{119}{}{不管你在外面害怕什么，你应该更害怕我。 -- Whatever you're afraid of out there, you should be more afraid of *me*.}
#{120}{}{[He stops whining. He looks afraid, but his eyes are clear] Okay... Okay... I'm fine, really. Just give me a second... I'm ready to go now.}
{120}{}{[他停止抱怨。他看起来很害怕，但他的眼睛很清楚]好吧。。。可以。。。我很好，真的。给我一点时间。。。我准备好了。 -- [He stops whining. He looks afraid, but his eyes are clear] Okay... Okay... I'm fine, really. Just give me a second... I'm ready to go now.}
#{121}{}{Good. Follow me.}
{121}{}{很好。跟着我。 -- Good. Follow me.}
#{122}{}{How can you be so calm? The Overseer always told us it's forbidden to go out there. What's going to happen to us? Why is this happening now? Why does it have to be me?!}
{122}{}{你怎么能这么冷静？监工总是告诉我们禁止外出。我们会怎么样？为什么现在会这样？为什么一定是我？！ -- How can you be so calm? The Overseer always told us it's forbidden to go out there. What's going to happen to us? Why is this happening now? Why does it have to be me?!}
#{123}{}{I don't know why you were chosen, but we can't go without you. If we're quick and careful, everything will be fine. You'll have me, doctor Moreau, and an armed guard watching out for you. You have nothing to worry about.}
{123}{}{我不知道你为什么被选中，但我们不能没有你。如果我们迅速小心，一切都会好的。你会有我的，莫罗医生，还有一个武装警卫在守护着你。你没什么好担心的。 -- I don't know why you were chosen, but we can't go without you. If we're quick and careful, everything will be fine. You'll have me, doctor Moreau, and an armed guard watching out for you. You have nothing to worry about.}
#{124}{}{Really? Will you keep me safe? [he grabs you by the suit] Please, just don't leave me... I'm so scared...}
{124}{}{真正地？你能保证我的安全吗？[他抓住你的衣服]拜托，别离开我。。。我好害怕。。。 -- Really? Will you keep me safe? [he grabs you by the suit] Please, just don't leave me... I'm so scared...}
#{125}{}{Don't be. I'm here.}
{125}{}{别这样。我在这里。 -- Don't be. I'm here.}
