#{100}{}{You see: a citizen.}
{100}{}{你看：公民。 -- You see: a citizen.}
#{101}{}{You see a citizen, throwing darts.}
{101}{}{你看到一个市民在扔飞镖。 -- You see a citizen, throwing darts.}
#{102}{}{No, thanks.}
{102}{}{不用了，谢谢。 -- No, thanks.}
#{103}{}{Hey, get out of the way! You want me to put your eye out?}
{103}{}{嘿，让开！你要我把你的眼睛挖出来吗？ -- Hey, get out of the way! You want me to put your eye out?}
#{104}{}{Hello, citizen.}
{104}{}{你好，市民。 -- Hello, citizen.}
#{105}{}{ }
{105}{}{  --  }
#{110}{}{Nice throw.}
{110}{}{投得好。 -- Nice throw.}
#{111}{}{You need to practice.}
{111}{}{你需要练习。 -- You need to practice.}
#{112}{}{Try again!}
{112}{}{再试一次！ -- Try again!}
#{113}{}{Be careful not to hurt yourself.}
{113}{}{小心别伤到自己。 -- Be careful not to hurt yourself.}
#{1104}{}{Hello, citizen.}
{1104}{}{你好，市民。 -- Hello, citizen.}
