#{100}{}{You see a visitor.}
{100}{}{你看到一个访客。 -- You see a visitor.}
#{101}{}{You see a cafe client.}
{101}{}{你看到一个咖啡馆客户。 -- You see a cafe client.}
#{102}{}{Don't you see that I'm eating?}
{102}{}{你没看到我在吃饭吗？ -- Don't you see that I'm eating?}
#{110}{}{Vegas is a mad city.}
{110}{}{维加斯是个疯狂的城市。 -- Vegas is a mad city.}
#{111}{}{I was lucky to settle here.}
{111}{}{我很幸运能在这里定居下来。 -- I was lucky to settle here.}
#{112}{}{A few days more and I'm broke.}
{112}{}{再过几天我就破产了。 -- A few days more and I'm broke.}
#{113}{}{Finding a job in the city is like skinning a Gecko alive.}
{113}{}{在城里找工作就像活剥壁虎皮。 -- Finding a job in the city is like skinning a Gecko alive.}
#{114}{}{Whew! So much pepper...}
{114}{}{呼！这么多胡椒。。。 -- Whew! So much pepper...}
#{115}{}{Your pizza is nuclear!}
{115}{}{你的披萨是核的！ -- Your pizza is nuclear!}
#{116}{}{Is this toilet paper?.. Oh, the bill...}
{116}{}{这是卫生纸吗？。。哦，账单。。。 -- Is this toilet paper?.. Oh, the bill...}
#{117}{}{When's the next show, chief?}
{117}{}{下一场演出是什么时候，头儿？ -- When's the next show, chief?}
#{118}{}{Hey chief! Come on, we need music!}
{118}{}{嘿，头儿！快点，我们需要音乐！ -- Hey chief! Come on, we need music!}
#{119}{}{The stage's been empty for a long time.}
{119}{}{舞台已经空了很久了。 -- The stage's been empty for a long time.}
#{120}{}{Waiter! The bill!}
{120}{}{服务员！账单！ -- Waiter! The bill!}
#{121}{}{Waiter! Beer! Come on, move it!}
{121}{}{服务员！啤酒！快点，快点！ -- Waiter! Beer! Come on, move it!}
#{122}{}{Waiter! Menu!}
{122}{}{服务员！菜单！ -- Waiter! Menu!}
#{123}{}{Service is much better at "Monte".}
{123}{}{“蒙特”的服务好得多。 -- Service is much better at "Monte".}
#{124}{}{Caravaneers became frequent visitors in here.}
{124}{}{商队成了这里的常客。 -- Caravaneers became frequent visitors in here.}
#{125}{}{The city gets larger and larger.}
{125}{}{城市越来越大。 -- The city gets larger and larger.}
#{126}{}{The city has nowhere to grow, but people are still arriving.}
{126}{}{这座城市无处可发展，但仍有人来到。 -- The city has nowhere to grow, but people are still arriving.}
#{127}{}{I'm not going anywhere while they still sell pizza here !}
{127}{}{他们还在这儿卖披萨，我哪也不去！ -- I'm not going anywhere while they still sell pizza here !}
#{128}{}{I only come here for the pizza.}
{128}{}{我只是来吃披萨的。 -- I only come here for the pizza.}
#{129}{}{I would like to see a good gig.}
{129}{}{我想看一场好的演出。 -- I would like to see a good gig.}
#{150}{}{Vegas is a mad city.}
{150}{}{维加斯是个疯狂的城市。 -- Vegas is a mad city.}
#{151}{}{I was lucky to settle here.}
{151}{}{我很幸运能在这里定居下来。 -- I was lucky to settle here.}
#{152}{}{A few more days and I'm broke.}
{152}{}{再过几天我就破产了。 -- A few more days and I'm broke.}
#{153}{}{Finding a job in the city is like skinning a Gecko alive.}
{153}{}{在城里找工作就像活剥壁虎皮。 -- Finding a job in the city is like skinning a Gecko alive.}
#{154}{}{Whew! So much pepper...}
{154}{}{呼！这么多胡椒。。。 -- Whew! So much pepper...}
#{155}{}{Your pizza is nuclear!}
{155}{}{你的披萨是核的！ -- Your pizza is nuclear!}
#{156}{}{Is this a toilet paper?.. Oh, this is a bill.}
{156}{}{这是卫生纸吗？。。哦，这是账单。 -- Is this a toilet paper?.. Oh, this is a bill.}
#{157}{}{This big guy is a real man!}
{157}{}{这个大个子是个真正的男人！ -- This big guy is a real man!}
#{158}{}{I'm yet to hear a more delirious thing than this.}
{158}{}{我还没听到比这更疯狂的事。 -- I'm yet to hear a more delirious thing than this.}
#{159}{}{What's he singing about?}
{159}{}{他在唱什么？ -- What's he singing about?}
#{160}{}{Waiter! The bill!}
{160}{}{服务员！账单！ -- Waiter! The bill!}
#{161}{}{Waiter! Beer! Come on, move it!}
{161}{}{服务员！啤酒！快点，快点！ -- Waiter! Beer! Come on, move it!}
#{162}{}{Waiter! Menu!}
{162}{}{服务员！菜单！ -- Waiter! Menu!}
#{163}{}{Service is much better at "Monte".}
{163}{}{“蒙特”的服务好得多。 -- Service is much better at "Monte".}
#{164}{}{I don't understand, what is this black guy singing about?!}
{164}{}{我不明白，这个黑人在唱什么？！ -- I don't understand, what is this black guy singing about?!}
#{165}{}{The city gets larger and larger.}
{165}{}{城市越来越大。 -- The city gets larger and larger.}
#{166}{}{The city has nowhere to grow, but people are still arriving.}
{166}{}{这座城市无处可发展，但仍有人来到。 -- The city has nowhere to grow, but people are still arriving.}
#{167}{}{While the stage is occupied I'm not going anywhere!}
{167}{}{当舞台上有人的时候，我哪儿也不去！ -- While the stage is occupied I'm not going anywhere!}
#{168}{}{I came here just for the concert.}
{168}{}{我只是来听音乐会的。 -- I came here just for the concert.}
#{169}{}{I don't mind the money spent on this concert one bit.}
{169}{}{我一点也不介意花在这场音乐会上的钱。 -- I don't mind the money spent on this concert one bit.}
#{170}{}{I think this goon has no ear for music... But I like it!}
{170}{}{我觉得这个笨蛋不懂音乐。。。但我喜欢！ -- I think this goon has no ear for music... But I like it!}
#{171}{}{Hey, on the stage! Start the party!}
{171}{}{嘿，在舞台上！开始派对！ -- Hey, on the stage! Start the party!}
#{172}{}{Hey, on the stage! Give us our favorite!}
{172}{}{嘿，在舞台上！给我们最喜欢的！ -- Hey, on the stage! Give us our favorite!}
#{173}{}{Man, I'd dance while you sing!}
{173}{}{伙计，你唱歌的时候我会跳舞！ -- Man, I'd dance while you sing!}
#{174}{}{::burp::}
{174}{}{●打嗝： -- ::burp::}
#{175}{}{Yahoo!}
{175}{}{雅虎！ -- Yahoo!}
#{176}{}{C'mon!}
{176}{}{拜托！ -- C'mon!}
#{177}{}{Rock on, big boy!}
{177}{}{加油，大男孩！ -- Rock on, big boy!}
#{180}{}{Hey, we actually came to listen to Louie!}
{180}{}{嘿，我们其实是来听路易的！ -- Hey, we actually came to listen to Louie!}
#{181}{}{And who is this?}
{181}{}{这是谁？ -- And who is this?}
#{182}{}{I thought Louie performs solo?}
{182}{}{我以为路易是独唱？ -- I thought Louie performs solo?}
#{183}{}{Hey, who let the clown on stage?}
{183}{}{嘿，谁让小丑上台的？ -- Hey, who let the clown on stage?}
#{184}{}{So, is it jazz or porn?}
{184}{}{那么，是爵士乐还是色情片？ -- So, is it jazz or porn?}
#{185}{}{The cracker and the nigger on the same stage? Wild.}
{185}{}{爆竹和黑鬼在同一个舞台上？野性。 -- The cracker and the nigger on the same stage? Wild.}
