#{100}{}{You see a casino bouncer.}
{100}{}{你看到一个赌场保镖。 -- You see a casino bouncer.}
#{101}{}{You see a casino bouncer. He is STRONG.}
{101}{}{你看到一个赌场保镖。他很强壮。 -- You see a casino bouncer. He is STRONG.}
#{102}{}{You see a casino bouncer. He is hefty. And angry.}
{102}{}{你看到一个赌场保镖。他很胖。而且很生气。 -- You see a casino bouncer. He is hefty. And angry.}
#{103}{}{You see a casino bouncer. He suspiciously looks at you.}
{103}{}{你看到一个赌场保镖。他怀疑地看着你。 -- You see a casino bouncer. He suspiciously looks at you.}
#{104}{}{You see a casino bouncer. You thought previously that only the mutants could be of such a size.}
{104}{}{你看到一个赌场保镖。你以前以为只有突变体才有这么大。 -- You see a casino bouncer. You thought previously that only the mutants could be of such a size.}
#{105}{}{Get the hell out!}
{105}{}{滚出去！ -- Get the hell out!}
#{110}{}{Hey, you! Put the weapon away!}
{110}{}{嘿，你！把武器收起来！ -- Hey, you! Put the weapon away!}
#{111}{}{I'm warning you - put the weapon away!}
{111}{}{我警告你-把武器收起来！ -- I'm warning you - put the weapon away!}
#{112}{}{No weapons in the casino!}
{112}{}{赌场里没有武器！ -- No weapons in the casino!}
#{113}{}{Put your weapon away!}
{113}{}{把你的武器收起来！ -- Put your weapon away!}
#{114}{}{Weapons in the casino are forbidden!}
{114}{}{赌场禁止携带武器！ -- Weapons in the casino are forbidden!}
#{115}{}{Hey, hide a weapon!}
{115}{}{嘿，藏武器！ -- Hey, hide a weapon!}
#{116}{}{Again, put the weapon away!}
{116}{}{再次，把武器收起来！ -- Again, put the weapon away!}
#{117}{}{I repeat, you can't be inside with a weapon!}
{117}{}{我再说一遍，你不能拿着武器进去！ -- I repeat, you can't be inside with a weapon!}
#{118}{}{I repeat, no weapons in the casino!}
{118}{}{重复，赌场里没有武器！ -- I repeat, no weapons in the casino!}
#{119}{}{Put that weapon away IMMEDIATELY!}
{119}{}{马上把武器收起来！ -- Put that weapon away IMMEDIATELY!}
#{120}{}{Weapons in the casino are forbidden!}
{120}{}{赌场禁止携带武器！ -- Weapons in the casino are forbidden!}
#{121}{}{Hey, holster your barrel, I will not say twice!}
{121}{}{嘿，把你的枪管套起来，我不会再说两遍的！ -- Hey, holster your barrel, I will not say twice!}
#{122}{}{So, it looks like someone is looking for trouble.}
{122}{}{看来有人在找麻烦。 -- So, it looks like someone is looking for trouble.}
#{123}{}{I'm warning you for the last time.}
{123}{}{我最后一次警告你。 -- I'm warning you for the last time.}
#{124}{}{Have hearing problems? I can explain with gestures.}
{124}{}{有听力问题吗？我可以用手势来解释。 -- Have hearing problems? I can explain with gestures.}
#{125}{}{I think someone needs to be disarmed.}
{125}{}{我觉得有人需要解除武装。 -- I think someone needs to be disarmed.}
#{126}{}{Put your weapon away and nobody will get hurt.}
{126}{}{把你的武器收起来，没人会受伤的。 -- Put your weapon away and nobody will get hurt.}
#{127}{}{That's it, bastard, you've found your trouble!}
{127}{}{就这样，混蛋，你找到麻烦了！ -- That's it, bastard, you've found your trouble!}
#{128}{}{So be it, I warned you!}
{128}{}{就这样吧，我警告过你！ -- So be it, I warned you!}
#{129}{}{You think you're tough? We'll see about that!}
{129}{}{你觉得你很坚强？我们拭目以待！ -- You think you're tough? We'll see about that!}
#{130}{}{I'm gonna have to teach you manners!}
{130}{}{我得教你礼貌！ -- I'm gonna have to teach you manners!}
#{131}{}{That's it, consider yourself convicted!}
{131}{}{就这样，你被判有罪！ -- That's it, consider yourself convicted!}
#{132}{}{You've found your trouble, bastard!}
{132}{}{你找到麻烦了，混蛋！ -- You've found your trouble, bastard!}
#{133}{}{WARNING! THE HOSTILE PERSON WITHIN THE CASINO!}
{133}{}{警告！赌场里的敌手！ -- WARNING! THE HOSTILE PERSON WITHIN THE CASINO!}
#{150}{}{Good evening.}
{150}{}{晚上好。 -- Good evening.}
#{151}{}{I'm not allowed to talk with the clients, sorry.}
{151}{}{对不起，我不能和客户说话。 -- I'm not allowed to talk with the clients, sorry.}
#{152}{}{Any problems?}
{152}{}{有什么问题吗？ -- Any problems?}
#{153}{}{What do you want?}
{153}{}{你想要什么？ -- What do you want?}
#{154}{}{Sorry, I'm not the one you need.}
{154}{}{对不起，我不是你需要的人。 -- Sorry, I'm not the one you need.}
#{155}{}{I don't talk to the clients.}
{155}{}{我不跟客户说话。 -- I don't talk to the clients.}
#{156}{}{Better go ask the bartender.}
{156}{}{最好去问问酒保。 -- Better go ask the bartender.}
#{157}{}{Good day, ma'am.}
{157}{}{你好，女士。 -- Good day, ma'am.}
#{158}{}{Good day, sir.}
{158}{}{你好，先生。 -- Good day, sir.}
#{159}{}{Sorry, I don't talk with the clients.}
{159}{}{对不起，我不跟客户说话。 -- Sorry, I don't talk with the clients.}
#{180}{}{Hey, freak, this is a casino, not a pub.}
{180}{}{嘿，怪胎，这是赌场，不是酒吧。 -- Hey, freak, this is a casino, not a pub.}
#{181}{}{Get out to the rest of the freaks, you ghoul.}
{181}{}{去找其他怪物，你这个食尸鬼。 -- Get out to the rest of the freaks, you ghoul.}
#{182}{}{What have we come to, now we tolerate the ghouls in the casino.}
{182}{}{现在我们容忍赌场里的食尸鬼。 -- What have we come to, now we tolerate the ghouls in the casino.}
#{183}{}{Just give me a reason, freak, I'll personally throw you out of here.}
{183}{}{给我个理由，怪胎，我会亲自把你扔出去的。 -- Just give me a reason, freak, I'll personally throw you out of here.}
#{184}{}{Stay away from me, sick.}
{184}{}{离我远点，病人。 -- Stay away from me, sick.}
#{185}{}{Don't even try to sneeze in my direction...}
{185}{}{别朝我的方向打喷嚏。。。 -- Don't even try to sneeze in my direction...}
#{186}{}{Ghoul? Here?!}
{186}{}{食尸鬼？在这里？！ -- Ghoul? Here?!}
#{187}{}{What are you doing in here, freak?}
{187}{}{你在这里干什么，怪胎？ -- What are you doing in here, freak?}
#{1127}{}{That's it, bitch, you've found your trouble!}
{1127}{}{够了，婊子，你找到麻烦了！ -- That's it, bitch, you've found your trouble!}
#{1128}{}{So be it, I warned you, bitch!}
{1128}{}{就这样吧，我警告过你，婊子！ -- So be it, I warned you, bitch!}
#{1129}{}{You think you're tough? We'll see about that!}
{1129}{}{你觉得你很坚强？我们拭目以待！ -- You think you're tough? We'll see about that!}
#{1131}{}{That's it, consider yourself convicted!}
{1131}{}{就这样，你被判有罪！ -- That's it, consider yourself convicted!}
#{1132}{}{You've found your trouble, bitch!}
{1132}{}{你找到麻烦了，婊子！ -- You've found your trouble, bitch!}
#{1162}{}{Nothing. Leave.}
{1162}{}{没有什么。离开。 -- Nothing. Leave.}
