#{100}{}{You see an unknown person.}
{100}{}{你看到一个陌生人。 -- You see an unknown person.}
#{101}{}{You see a person unknown to you.}
{101}{}{你看到一个你不认识的人。 -- You see a person unknown to you.}
#{102}{}{I'm here to deliver a message! Here it is!}
{102}{}{我是来传递信息的！给你！ -- I'm here to deliver a message! Here it is!}
#{103}{}{You eliminated the killers. You wonder who hired them.}
{103}{}{你消灭了凶手。你想知道是谁雇的他们。 -- You eliminated the killers. You wonder who hired them.}
