#{100}{}{You see a whiteboard.}
{100}{}{你看到一块白板。 -- You see a whiteboard.}
#{101}{}{It's just a board with old ads and price tags. You could add your own notes.}
{101}{}{那只是一块有旧广告和价签的木板。你可以添加自己的笔记。 -- It's just a board with old ads and price tags. You could add your own notes.}
#{102}{}{You are going to read during the fight?! Not very smart, you know...}
{102}{}{你要在战斗中读书吗？！不是很聪明，你知道。。。 -- You are going to read during the fight?! Not very smart, you know...}
#{103}{}{Where would you like to park you truck to next time?}
{103}{}{下次你想把车停在哪里？ -- Where would you like to park you truck to next time?}
#{104}{}{Park the car in the garage.}
{104}{}{把车停在车库里。 -- Park the car in the garage.}
#{105}{}{Park the car next to the caravaneers.}
{105}{}{把车停在商队旁边。 -- Park the car next to the caravaneers.}
#{106}{}{Park the car at the Clean City entrance.}
{106}{}{把车停在干净的城市入口。 -- Park the car at the Clean City entrance.}
#{107}{}{Leave as it is.}
{107}{}{保持现状。 -- Leave as it is.}
#{108}{}{Finished.}
{108}{}{完成了。 -- Finished.}
#{109}{}{Done.}
{109}{}{完成。 -- Done.}
#{110}{}{OK.}
{110}{}{好 啊。 -- OK.}
#{111}{}{All right.}
{111}{}{好吧。 -- All right.}
#{112}{}{No problems.}
{112}{}{没问题。 -- No problems.}
#{113}{}{Whatever you say.}
{113}{}{不管你说什么。 -- Whatever you say.}
#{114}{}{However you want.}
{114}{}{随你怎么想。 -- However you want.}
#{115}{}{No question.}
{115}{}{毫无疑问。 -- No question.}
#{116}{}{Will do.}
{116}{}{就行了。 -- Will do.}
#{117}{}{Sure thing, boss.}
{117}{}{当然，老板。 -- Sure thing, boss.}
#{118}{}{You know better, boss.}
{118}{}{你更清楚，老板。 -- You know better, boss.}
#{119}{}{So be it.}
{119}{}{就这样吧。 -- So be it.}
#{120}{}{Once again.}
{120}{}{再一次。 -- Once again.}
#{121}{}{That's better.}
{121}{}{这样更好。 -- That's better.}
#{122}{}{I don't need that now}
{122}{}{我现在不需要 -- I don't need that now}
#{130}{}{Remember where I left the car.}
{130}{}{记得我把车停在哪儿了。 -- Remember where I left the car.}
#{131}{}{.}
{131}{}{. -- .}
#{132}{}{Okay, now back to the question about parking.}
{132}{}{好，现在回到停车的问题。 -- Okay, now back to the question about parking.}
#{133}{}{Now I remember! It's time to go get the car.}
{133}{}{现在我想起来了！该去买车了。 -- Now I remember! It's time to go get the car.}
#{1130}{}{Remember where I left the car.}
{1130}{}{记得我把车停在哪儿了。 -- Remember where I left the car.}
#{1133}{}{Now I remember! It's time to go get the car.}
{1133}{}{现在我想起来了！该去买车了。 -- Now I remember! It's time to go get the car.}
#{1499}{}{It's somewhere in the wasteland.}
{1499}{}{在荒地的某个地方。 -- It's somewhere in the wasteland.}
#{1500}{}{Vault City}
{1500}{}{地下掩体市 -- Vault City}
#{1501}{}{Wind of War}
{1501}{}{战争之风 -- Wind of War}
#{1502}{}{The 'Sigma' base}
{1502}{}{“西格玛”基础 -- The 'Sigma' base}
#{1503}{}{Lovelock}
{1503}{}{洛夫洛克 -- Lovelock}
#{1504}{}{Baydie}
{1504}{}{贝迪 -- Baydie}
#{1505}{}{Poseidon Oil NPP}
{1505}{}{波塞冬石油核电站 -- Poseidon Oil NPP}
#{1506}{}{Ailie}
{1506}{}{艾莉 -- Ailie}
#{1507}{}{New Reno}
{1507}{}{新里诺 -- New Reno}
#{1508}{}{Area 51}
{1508}{}{51区 -- Area 51}
#{1509}{}{Bridgeport}
{1509}{}{布里奇波特 -- Bridgeport}
#{1510}{}{Las Vegas}
{1510}{}{拉斯维加斯 -- Las Vegas}
#{1511}{}{Provo District}
{1511}{}{普罗沃区 -- Provo District}
#{1512}{}{Hawthorne Military Base}
{1512}{}{霍桑军事基地 -- Hawthorne Military Base}
#{1513}{}{Wendover}
{1513}{}{温多弗 -- Wendover}
#{1514}{}{Salt Lake City}
{1514}{}{盐湖城 -- Salt Lake City}
#{1515}{}{Old Rabbi}
{1515}{}{老拉比 -- Old Rabbi}
#{1516}{}{Governmental Vault}
{1516}{}{政府金库 -- Governmental Vault}
#{1517}{}{Gerlach}
{1517}{}{格拉赫 -- Gerlach}
#{1518}{}{Uranium City}
{1518}{}{铀城 -- Uranium City}
#{1519}{}{The Pound}
{1519}{}{英镑 -- The Pound}
#{1520}{}{Battle Mountain}
{1520}{}{战山 -- Battle Mountain}
#{1521}{}{Car Outta Power}
{1521}{}{汽车没电了 -- Car Outta Power}
#{1522}{}{Vault City}
{1522}{}{地下掩体市 -- Vault City}
#{1523}{}{Traffic Jam}
{1523}{}{交通堵塞 -- Traffic Jam}
#{1524}{}{Operation of Wind of War}
{1524}{}{战风行动 -- Operation of Wind of War}
#{1525}{}{Black Rock}
{1525}{}{黑岩 -- Black Rock}
#{1526}{}{Desert}
{1526}{}{沙漠 -- Desert}
#{1527}{}{Mountain}
{1527}{}{山 -- Mountain}
#{1528}{}{Ruined city}
{1528}{}{废墟城市 -- Ruined city}
#{1529}{}{Coast}
{1529}{}{海岸 -- Coast}
#{1530}{}{Gas Station}
{1530}{}{加油站 -- Gas Station}
#{1531}{}{Crossroad}
{1531}{}{十字路口 -- Crossroad}
#{1532}{}{Big hole}
{1532}{}{大洞 -- Big hole}
#{1533}{}{Dump of Tires}
{1533}{}{轮胎倾卸 -- Dump of Tires}
#{1534}{}{Tanker in the desert}
{1534}{}{沙漠中的油轮 -- Tanker in the desert}
#{1535}{}{Abnormal place}
{1535}{}{异常地点 -- Abnormal place}
#{1536}{}{Lost Office}
{1536}{}{失去办公室 -- Lost Office}
#{1537}{}{'The New Hopes' cafe}
{1537}{}{“新希望”咖啡馆 -- 'The New Hopes' cafe}
#{1538}{}{Giant Egg}
{1538}{}{巨蛋 -- Giant Egg}
#{1539}{}{Bobby's Hut}
{1539}{}{鲍比的小屋 -- Bobby's Hut}
#{1540}{}{House on wheels}
{1540}{}{车轮上的房子 -- House on wheels}
#{1541}{}{'Furthur'}
{1541}{}{“富图尔” -- 'Furthur'}
#{1542}{}{Abandoned Ranger's Station}
{1542}{}{废弃的护林员站 -- Abandoned Ranger's Station}
#{1543}{}{Picnic Area}
{1543}{}{野餐地点 -- Picnic Area}
#{1544}{}{Caravan}
{1544}{}{大篷车 -- Caravan}
#{1545}{}{"Dear John"}
{1545}{}{“亲爱的约翰” -- "Dear John"}
#{1546}{}{Harrelson}
{1546}{}{哈勒森 -- Harrelson}
#{1547}{}{Random encounter}
{1547}{}{随机相遇 -- Random encounter}
#{1548}{}{Broken stagecoach}
{1548}{}{驿站马车坏了 -- Broken stagecoach}
