#{110}{}{"Vending machine offers a wide range of various exciting and informative publications."}
{110}{}{“自动售货机提供各种令人兴奋和信息丰富的出版物。” -- "Vending machine offers a wide range of various exciting and informative publications."}
#{111}{}{[Select publication]}
{111}{}{[选择出版物] -- [Select publication]}
#{112}{}{[Leave the machine alone]}
{112}{}{[别碰机器] -- [Leave the machine alone]}
#{113}{}{Sorry, currently there is no item in the machine.}
{113}{}{抱歉，当前计算机中没有项目。 -- Sorry, currently there is no item in the machine.}
#{114}{}{"To make a purchase, select the number of the desired publication and insert the required amount of money in the slot. "(The price of each unit is - 500$)}
{114}{}{要购买，请选择所需出版物的编号，然后在槽中插入所需的金额（每件的价格是-500美元） -- "To make a purchase, select the number of the desired publication and insert the required amount of money in the slot. "(The price of each unit is - 500$)}
#{115}{}{"Thank you for your purchase! We wish you a pleasant reading."}
{115}{}{“谢谢您的购买！祝您阅读愉快。” -- "Thank you for your purchase! We wish you a pleasant reading."}
#{116}{}{[Back to the choice of publications]}
{116}{}{[回到出版物的选择] -- [Back to the choice of publications]}
#{117}{}{[Empty slot]}
{117}{}{[空插槽] -- [Empty slot]}
#{118}{}{.}
{118}{}{. -- .}
#{119}{}{"Please insert the required amount of money in the slot."}
{119}{}{“请在投币口插入所需金额。” -- "Please insert the required amount of money in the slot."}
#{120}{}{Obviously, I do not have that kind of money.}
{120}{}{显然，我没有那种钱。 -- Obviously, I do not have that kind of money.}
#{121}{}{[Pay]}
{121}{}{[支付] -- [Pay]}
#{122}{}{> Next list}
{122}{}{>下一个列表 -- > Next list}
#{123}{}{< Previous list}
{123}{}{<上一个列表 -- < Previous list}
