#{100}{}{You see private Derren.}
{100}{}{你看到二等兵德伦了。 -- You see private Derren.}
#{101}{}{You see young private Derren. Not a lot could be said about him.}
{101}{}{你看到年轻的二等兵德伦了。关于他说的不多。 -- You see young private Derren. Not a lot could be said about him.}
#{102}{}{My, uh, orders doesn't allow to speak with you.}
{102}{}{我的命令不允许和你说话。 -- My, uh, orders doesn't allow to speak with you.}
#{103}{}{"Thank you" very much. Now I won't be able to get rid of them in my lifetime. Though girl's nice, maybe we'll get along.}
{103}{}{非常感谢。现在我一辈子都摆脱不了他们。虽然女孩很好，也许我们能相处。 -- "Thank you" very much. Now I won't be able to get rid of them in my lifetime. Though girl's nice, maybe we'll get along.}
#{110}{}{I'm on my duty and can't fool around.}
{110}{}{我在值班，不能到处闲逛。 -- I'm on my duty and can't fool around.}
#{111}{}{So you're the private for whose soul that old redneck came for?}
{111}{}{你是那个老乡巴佬为谁的灵魂而来的？ -- So you're the private for whose soul that old redneck came for?}
#{112}{}{Bye.}
{112}{}{再见。 -- Bye.}
#{113}{}{Well, heh, ugh... They told you too? Oh, shame on me... Wait, who are you? I saw you with Wesker, but you're not from the garrison. Who are you?! Name yourself!}
{113}{}{嗯，嘿，呃。。。他们也告诉你了？哦，真丢脸。。。等等，你是谁？我看见你和韦斯克在一起，但你不是驻军的。你是谁？！说出你自己的名字！ -- Well, heh, ugh... They told you too? Oh, shame on me... Wait, who are you? I saw you with Wesker, but you're not from the garrison. Who are you?! Name yourself!}
#{114}{}{A freelancer, doing odd jobs for Wesker. And don't you think to dodge the question.}
{114}{}{一个自由职业者，为韦斯克打零工。别想回避这个问题。 -- A freelancer, doing odd jobs for Wesker. And don't you think to dodge the question.}
#{115}{}{I didn't! I just don't know, what to do... These rednecks aren't easy to fall behind. And I wouldn't want the rumors about me to spread around the garrison.}
{115}{}{我没有！我只是不知道该怎么办。。。这些乡巴佬不容易落在后面。我不想让关于我的谣言在驻军里传播。 -- I didn't! I just don't know, what to do... These rednecks aren't easy to fall behind. And I wouldn't want the rumors about me to spread around the garrison.}
#{116}{}{Which means, what pops said was true? You did his daughter, didn't you?}
{116}{}{也就是说，波普说的是真的？你杀了他的女儿，不是吗？ -- Which means, what pops said was true? You did his daughter, didn't you?}
#{117}{}{[Scratches his head] Yeah, it's true... I did. But I'm not some kind of barbarian! While quartermaster have been with the locals, I was patrolling around the barn, and - there she is. And she weren't in need of any asking. She herself fell on her back - woo-hoo, if only it worked like that every time!}
{117}{}{是的，是真的。。。是的。但我不是什么野蛮人！当军需官和当地人在一起时，我在谷仓周围巡逻，她在那里。她也不需要问。她自己倒在地上-呜呼，要是每次都这样就好了！ -- [Scratches his head] Yeah, it's true... I did. But I'm not some kind of barbarian! While quartermaster have been with the locals, I was patrolling around the barn, and - there she is. And she weren't in need of any asking. She herself fell on her back - woo-hoo, if only it worked like that every time!}
#{118}{}{So, now you have a box for a lifetime.}
{118}{}{所以，现在你一辈子都有一个盒子。 -- So, now you have a box for a lifetime.}
#{119}{}{Do you think Wesker would approve your behavior?}
{119}{}{你认为韦斯克会赞成你的行为吗？ -- Do you think Wesker would approve your behavior?}
#{120}{}{Why not go to them for negotiations and to confess?}
{120}{}{为什么不去找他们谈判并坦白呢？ -- Why not go to them for negotiations and to confess?}
#{121}{}{}
{121}{}{ -- }
#{122}{}{I can get rid of them. But not for free.}
{122}{}{我可以摆脱他们。但不是免费的。 -- I can get rid of them. But not for free.}
#{123}{}{Hey, who brewed all this mess? Clean up after yourself! And I'll go mind my own business.}
{123}{}{嘿，谁酿的这么乱？你自己收拾一下！我去管好自己的事。 -- Hey, who brewed all this mess? Clean up after yourself! And I'll go mind my own business.}
#{124}{}{What? Hey, you're not saying that... What the hell!? So this cretin wants to drop a fiancee on my neck!? Oh...}
{124}{}{什么？嘿，你不是说。。。我勒个去！？所以这个白痴想把未婚妻放在我脖子上！？哦。。。 -- What? Hey, you're not saying that... What the hell!? So this cretin wants to drop a fiancee on my neck!? Oh...}
#{125}{}{Aren't you a handsome. Apparently, it is mandatory to look after oneself in the garrison. No surprise this country girl gave herself to you so easily.}
{125}{}{你不帅吗。显然，在卫戍区必须照顾好自己。难怪这个乡下姑娘这么容易就把自己交给你了。 -- Aren't you a handsome. Apparently, it is mandatory to look after oneself in the garrison. No surprise this country girl gave herself to you so easily.}
#{126}{}{Huh? Did you see her?! All face is freckled and square-shaped muzzle. But yeah, there aren't many girls around here, it's true. Of course, it's better than nothing. But not with such a family! I saw these villagers, it's far better to pass as coward than enroll in their family.}
{126}{}{呵呵？你看见她了吗？！所有的脸都是雀斑和方形口吻。但是，是的，这附近的女孩不多，这是真的。当然，总比什么都没有强。但不能和这样的家庭在一起！我见过这些村民，当懦夫总比加入他们家好。 -- Huh? Did you see her?! All face is freckled and square-shaped muzzle. But yeah, there aren't many girls around here, it's true. Of course, it's better than nothing. But not with such a family! I saw these villagers, it's far better to pass as coward than enroll in their family.}
#{127}{}{Certainly not! In his case it's better to keep your mouth shut. Do you, eh, understand that? If not, then eh... Look, just know that it's better leave general out of this.}
{127}{}{当然不是！对他来说还是闭嘴好。你明白吗？如果不是，那么。。。听着，你要知道最好别把将军扯进来。 -- Certainly not! In his case it's better to keep your mouth shut. Do you, eh, understand that? If not, then eh... Look, just know that it's better leave general out of this.}
#{128}{}{Are you crazy!? Did you see that family! The girl might be cute, and there's not much to choose in these parts, but interacting with her family - I'd rather hang up myself. I didn't live so many years in garrison only to be left around rednecks for my entire life.}
{128}{}{你疯了吗！？你看到那家人了吗！这个女孩可能很可爱，在这些地方没有太多选择，但与家人互动——我宁愿自己挂断电话。我在卫戍区住了这么多年，却一辈子都被留在乡巴佬身边。 -- Are you crazy!? Did you see that family! The girl might be cute, and there's not much to choose in these parts, but interacting with her family - I'd rather hang up myself. I didn't live so many years in garrison only to be left around rednecks for my entire life.}
#{129}{}{Well, that's an exaggeration. More like pops just wants to drop his daughter on you to feed fewer mouths.}
{129}{}{嗯，那太夸张了。更像是爸爸想把女儿扔给你，让你少吃点东西。 -- Well, that's an exaggeration. More like pops just wants to drop his daughter on you to feed fewer mouths.}
#{130}{}{Maybe so. But imagine what kind of fame about me will be spread among ourselves. It's the villagers. Although we protect them from bandits, nobody rushes to cuddle with them.}
{130}{}{也许是吧。但是想象一下我的名声会在我们之间传播。是村民。虽然我们保护他们不受强盗的袭击，但没有人急于去拥抱他们。 -- Maybe so. But imagine what kind of fame about me will be spread among ourselves. It's the villagers. Although we protect them from bandits, nobody rushes to cuddle with them.}
#{131}{}{What a fool. A coward's fame is no better.}
{131}{}{真是个傻瓜。懦夫的名声再好不过了。 -- What a fool. A coward's fame is no better.}
#{132}{}{Until I'll be forced to - I won't go to them. And I don't care what are talking about.}
{132}{}{除非我被迫-我不会去找他们。我不在乎你在说什么。 -- Until I'll be forced to - I won't go to them. And I don't care what are talking about.}
#{133}{}{Really? Eh, look, I'm not asking anything extreme, just make them leave Wind of War. Okay? I will pay you all the money I had in the stash - 300 bucks. They have no reason to hang around here. Let them just go back to farming.}
{133}{}{真正地？呃，听着，我没有要求任何极端的事情，只是让他们离开战争之风。可以？我会付你我所有的钱-300美元。他们没有理由在这里闲逛。让他们回去种地吧。 -- Really? Eh, look, I'm not asking anything extreme, just make them leave Wind of War. Okay? I will pay you all the money I had in the stash - 300 bucks. They have no reason to hang around here. Let them just go back to farming.}
#{134}{}{Deal.}
{134}{}{处理。 -- Deal.}
#{135}{}{Rednecks won't bother you again. You can go check now.}
{135}{}{乡巴佬不会再打扰你了。你现在可以去看看了。 -- Rednecks won't bother you again. You can go check now.}
#{136}{}{Really? Phew, what a relief! You're not deceiving me? Of course, who could, everyone knows each other... I promised 300 bucks. Here, now they're yours. But don't reveal anything to general.}
{136}{}{真正地？呸，真是松了一口气！你没骗我？当然，谁能，每个人都认识。。。我答应给你300块。给，现在它们是你的了。但不要向将军透露任何事情。 -- Really? Phew, what a relief! You're not deceiving me? Of course, who could, everyone knows each other... I promised 300 bucks. Here, now they're yours. But don't reveal anything to general.}
#{137}{}{Not bad. Look, just don't get caught second time. You'll be on your own.}
{137}{}{不错。听着，别再被抓了。你自己去吧。 -- Not bad. Look, just don't get caught second time. You'll be on your own.}
#{138}{}{You again, to talk about these rednecks?}
{138}{}{又是你，说这些乡巴佬？ -- You again, to talk about these rednecks?}
#{1113}{}{Well, heh, ugh... They told you too? Oh, shame on me... Wait, who are you? I saw you with Wesker but you're not from the garrison. Who're you?! Name yourself!}
{1113}{}{嗯，嘿，呃。。。他们也告诉你了？哦，真丢脸。。。等等，你是谁？我看见你和韦斯克在一起，但你不是驻军的。你是谁？！说出你自己的名字！ -- Well, heh, ugh... They told you too? Oh, shame on me... Wait, who are you? I saw you with Wesker but you're not from the garrison. Who're you?! Name yourself!}
#{1128}{}{Are you crazy!? Did you see that family! The girl might be cute, and there's not much to choose in these parts, but interacting with her family - I'd rather hang up myself. I didn't live so many years in garrison only to hang around rednecks for my entire life.}
{1128}{}{你疯了吗！？你看到那家人了吗！这个女孩可能很可爱，在这些地方没有太多选择，但与家人互动——我宁愿自己挂断电话。我在卫戍区住了这么多年，可不是为了在乡巴佬家混一辈子。 -- Are you crazy!? Did you see that family! The girl might be cute, and there's not much to choose in these parts, but interacting with her family - I'd rather hang up myself. I didn't live so many years in garrison only to hang around rednecks for my entire life.}
