#{100}{}{Cell door.}
{100}{}{牢房门。 -- Cell door.}
#{101}{}{A heavy cell door.}
{101}{}{沉重的牢房门。 -- A heavy cell door.}
#{103}{}{The cell is locked}
{103}{}{牢房被锁上了 -- The cell is locked}
#{104}{}{The cell door is locked with a huge lock. It's not possible to kick it open.}
{104}{}{牢房的门是用一把大锁锁上的。不可能把它踢开。 -- The cell door is locked with a huge lock. It's not possible to kick it open.}
#{105}{}{The lock has already been picked.}
{105}{}{锁已经被撬开了。 -- The lock has already been picked.}
#{106}{}{Well, that wasn't hard at all!}
{106}{}{嗯，那一点也不难！ -- Well, that wasn't hard at all!}
#{107}{}{You pick the cell door lock.}
{107}{}{你撬开牢房的门锁。 -- You pick the cell door lock.}
#{108}{}{You fail to pick the lock.}
{108}{}{你没能开锁。 -- You fail to pick the lock.}
#{109}{}{Fail}
{109}{}{失败 -- Fail}
#{110}{}{Hey, you! Be quiet! Just don't give me any trouble, do your 24 hours and you'll be out just fine.}
{110}{}{嘿，你！安静点！别给我添麻烦了，只要你24小时不休息，你就没事了。 -- Hey, you! Be quiet! Just don't give me any trouble, do your 24 hours and you'll be out just fine.}
#{111}{}{Can you at least tell me what I'm in for?!}
{111}{}{你至少能告诉我我在干什么吗？！ -- Can you at least tell me what I'm in for?!}
#{112}{}{How the hell am I supposed to know.}
{112}{}{我怎么会知道呢。 -- How the hell am I supposed to know.}
#{113}{}{Shit...}
{113}{}{倒霉。。。 -- Shit...}
#{114}{}{There go your 24 hours. Out you go. Your stuff is in that locker.}
{114}{}{这就是你的24小时。你出去吧。你的东西在那个柜子里。 -- There go your 24 hours. Out you go. Your stuff is in that locker.}
#{115}{}{Wait a second, buddy, I just wanted to ask you something... [Take a convenient position]}
{115}{}{等等，伙计，我只是想问你一件事。。。[找个方便的位置] -- Wait a second, buddy, I just wanted to ask you something... [Take a convenient position]}
#{116}{}{Finally!}
{116}{}{终于！ -- Finally!}
#{117}{}{You can't unlock the door from this side.}
{117}{}{你不能从这边开门。 -- You can't unlock the door from this side.}
#{118}{}{Can't reach}
{118}{}{够不着 -- Can't reach}
#{1115}{}{Wait a second, buddy, I just wanted to ask you something... [Take a convenient position]}
{1115}{}{等等，伙计，我只是想问你一件事。。。[找个方便的位置] -- Wait a second, buddy, I just wanted to ask you something... [Take a convenient position]}
