#{100}{}{You see power distribution unit.}
{100}{}{你看配电装置。 -- You see power distribution unit.}
#{101}{}{You see a distributor by means of which the barracks is supplied with electricity.}
{101}{}{你看到一个配电盘，通过它向营房供电。 -- You see a distributor by means of which the barracks is supplied with electricity.}
#{102}{}{You see an idle power distributor.}
{102}{}{你看到一个闲置的配电盘。 -- You see an idle power distributor.}
#{103}{}{This distributor is buzzing, supplying the barracks with power.}
{103}{}{这个分配器嗡嗡作响，为营房供电。 -- This distributor is buzzing, supplying the barracks with power.}
#{104}{}{This distributor is already switched off.}
{104}{}{此分配器已关闭。 -- This distributor is already switched off.}
#{105}{}{You flip the switch, and the barracks is no longer supplied with electricity.}
{105}{}{你扳动开关，兵营就不再有电力供应了。 -- You flip the switch, and the barracks is no longer supplied with electricity.}
#{106}{}{You lack technical knowledge necessary to switch off the distributor.}
{106}{}{您缺乏关闭分配器所需的技术知识。 -- You lack technical knowledge necessary to switch off the distributor.}
#{107}{}{Scientific approach should better be used on computers, rather than distributors.}
{107}{}{科学的方法最好用在计算机上，而不是用在分销商上。 -- Scientific approach should better be used on computers, rather than distributors.}
#{108}{}{This won't help, you need to get technical.}
{108}{}{这没用，你需要技术支持。 -- This won't help, you need to get technical.}
#{109}{}{This won't help.}
{109}{}{这没用。 -- This won't help.}
#{110}{}{Hey, who turned off the light!?}
{110}{}{嘿，谁把灯关了！？ -- Hey, who turned off the light!?}
#{111}{}{Damn fuses blew again...}
{111}{}{该死的保险丝又断了。。。 -- Damn fuses blew again...}
#{112}{}{I'm afraid of the dark... Just kidding}
{112}{}{我害怕黑暗。。。开玩笑而已 -- I'm afraid of the dark... Just kidding}
#{113}{}{The time is inappropriate for sabotage.}
{113}{}{现在不适合搞破坏。 -- The time is inappropriate for sabotage.}
#{114}{}{*Script error*}
{114}{}{*脚本错误* -- *Script error*}
#{115}{}{Move it, Jesse!}
{115}{}{快点，杰西！ -- Move it, Jesse!}
#{116}{}{This is the key from a cache in the ruined house, you may have some use for it. Bye!}
{116}{}{这是破烂房子里的钥匙，你可能会用到它的。再见！ -- This is the key from a cache in the ruined house, you may have some use for it. Bye!}
