#{100}{}{}
{100}{}{ -- }
#{101}{}{You can't run the train during combat!}
{101}{}{你不能在战斗中驾驶火车！ -- You can't run the train during combat!}
#{102}{}{Your mission here is not over yet!}
{102}{}{你的任务还没有结束！ -- Your mission here is not over yet!}
#{103}{}{You can start the train and go back. Want to go back?}
{103}{}{你可以发动火车回去。想回去吗？ -- You can start the train and go back. Want to go back?}
#{104}{}{You can start the train and go back, but your driver is not here. Are you ready to leave him to the mercy of fate and go back?}
{104}{}{你可以发动火车回去，但你的司机不在这儿。你准备好让他任由命运摆布然后回去了吗？ -- You can start the train and go back, but your driver is not here. Are you ready to leave him to the mercy of fate and go back?}
#{105}{}{Warm up the turbine and go back.}
{105}{}{预热涡轮，然后返回。 -- Warm up the turbine and go back.}
#{106}{}{Cancel.}
{106}{}{取消。 -- Cancel.}
#{107}{}{Would you like to go to Salt Lake?}
{107}{}{你想去盐湖城吗？ -- Would you like to go to Salt Lake?}
#{108}{}{Let's go!}
{108}{}{走吧！ -- Let's go!}
#{109}{}{Cancel.}
{109}{}{取消。 -- Cancel.}
