#{100}{}{You see a caravan merchant.}
{100}{}{你看到一个商队商人。 -- You see a caravan merchant.}
#{101}{}{You see a leader of the caravan.}
{101}{}{你看到一个商队队长。 -- You see a leader of the caravan.}
#{110}{}{What took you so long? I was starting to think I wouldn't get the chance to thank you. So, uh... Thank you? Hell, I'm no good at this.}
{110}{}{你怎么这么久？我开始觉得我没有机会感谢你了。所以，呃。。。谢谢您？见鬼，我不擅长这个。 -- What took you so long? I was starting to think I wouldn't get the chance to thank you. So, uh... Thank you? Hell, I'm no good at this.}
#{111}{}{You're welcome.}
{111}{}{不客气。 -- You're welcome.}
#{112}{}{Hey, listen. We're gonna stick around for a little while, then head back to Reno. You're welcome to join us, if you're interested - always good to have an extra gun. You'll have to travel light though, we carry enough extra weight as it is.}
{112}{}{嘿，听着。我们要呆一会儿，然后回雷诺。如果你有兴趣的话，欢迎你加入我们-多带一把枪总是好的。不过你得轻装上阵，因为我们有足够的额外重量。 -- Hey, listen. We're gonna stick around for a little while, then head back to Reno. You're welcome to join us, if you're interested - always good to have an extra gun. You'll have to travel light though, we carry enough extra weight as it is.}
#{113}{}{Hey there, son! How are you?}
{113}{}{嘿，儿子！你好吗？ -- Hey there, son! How are you?}
#{114}{}{Before you leave, I wanted to ask...}
{114}{}{在你离开之前，我想问。。。 -- Before you leave, I wanted to ask...}
#{115}{}{Can you take me with you to New Reno?}
{115}{}{你能带我去新雷诺吗？ -- Can you take me with you to New Reno?}
#{116}{}{Did you do any trading on the way to Black Rock?}
{116}{}{你在去黑岩的路上做过交易吗？ -- Did you do any trading on the way to Black Rock?}
#{117}{}{I'll leave you alone for now. See you.}
{117}{}{我暂时不理你。再见。 -- I'll leave you alone for now. See you.}
#{118}{}{No problem. I know I can trust you.}
{118}{}{没问题。我知道我可以相信你。 -- No problem. I know I can trust you.}
#{119}{}{We won't stay long before we head back to Reno. You need anything, you'd better tell me now.}
{119}{}{我们很快就要回雷诺了。你需要什么，最好现在就告诉我。 -- We won't stay long before we head back to Reno. You need anything, you'd better tell me now.}
#{120}{}{Yeah?}
{120}{}{是 啊？ -- Yeah?}
#{121}{}{How often will you come to Black Rock?}
{121}{}{你多久来一次黑岩？ -- How often will you come to Black Rock?}
#{122}{}{Why did you travel so far?}
{122}{}{你为什么走这么远？ -- Why did you travel so far?}
#{123}{}{How did the raiders trap you?}
{123}{}{袭击者是怎么陷害你的？ -- How did the raiders trap you?}
#{124}{}{I want to ask you something else.}
{124}{}{我想问你点别的。 -- I want to ask you something else.}
#{125}{}{We come here every 10th of the month, rest up a few days, then move out to the course. It's good, that this place is here - for a long time, there was nowhere decent to rest this far north.}
{125}{}{我们每十个月来这里一次，休息几天，然后搬到球场去。很好，这个地方就在这里——很长一段时间以来，在这么远的北方没有一个像样的地方可以休息。 -- We come here every 10th of the month, rest up a few days, then move out to the course. It's good, that this place is here - for a long time, there was nowhere decent to rest this far north.}
#{126}{}{Gecko skins, that's why! Can't keep wearing pre-war clothing forever, you know. It's time for Nevada to update its wardrobe, and this year it's leather, leather, leather. It's a good time to be a gecko hunter, especially if you can take on the golden ones.}
{126}{}{壁虎皮，这就是原因！你知道，不能一直穿着战前的衣服。内华达是时候更新它的衣柜了，今年是皮革，皮革，皮革。现在是做壁虎猎人的好时机，尤其是如果你能和黄金壁虎对决的话。 -- Gecko skins, that's why! Can't keep wearing pre-war clothing forever, you know. It's time for Nevada to update its wardrobe, and this year it's leather, leather, leather. It's a good time to be a gecko hunter, especially if you can take on the golden ones.}
#{127}{}{We were coming up from Reno to pick up some gecko skins. Coming up on the mountains, something didn't feel right. We busted out the binoculars to find, lo and behold, the raiders hadn't even put out their campfires. Pure amateur hour, I said to myself. Fortunately, I knew a cave that cut right through the side of the mountain. We'd just have to take the caravan through it and out the other side, and the raiders'd never even know we were there. Clever me, huh?}
{127}{}{我们从里诺过来取些壁虎皮。到了山上，感觉有些不对劲。我们拿出望远镜去发现，瞧，袭击者连营火都没熄灭。纯粹的业余时间，我对自己说。幸运的是，我知道一个山洞正好穿过山的一侧。我们只要带着商队穿过它，从另一边出去，袭击者根本不知道我们在那里。聪明的我，哈？ -- We were coming up from Reno to pick up some gecko skins. Coming up on the mountains, something didn't feel right. We busted out the binoculars to find, lo and behold, the raiders hadn't even put out their campfires. Pure amateur hour, I said to myself. Fortunately, I knew a cave that cut right through the side of the mountain. We'd just have to take the caravan through it and out the other side, and the raiders'd never even know we were there. Clever me, huh?}
#{128}{}{What next?}
{128}{}{接下来呢？ -- What next?}
#{129}{}{Turns out they knew about the cave too. Fuck, I walked right into it! Just after we passed through, they detonated the cave behind us and sealed off the tunnel. I don't know if they planned it that way, or just got lucky, but it doesn't really matter now.}
{129}{}{原来他们也知道那个洞。妈的，我直接就进去了！我们刚通过，他们就引爆了我们身后的山洞，封锁了隧道。我不知道他们是这样计划的，还是运气好，但现在已经不重要了。 -- Turns out they knew about the cave too. Fuck, I walked right into it! Just after we passed through, they detonated the cave behind us and sealed off the tunnel. I don't know if they planned it that way, or just got lucky, but it doesn't really matter now.}
#{130}{}{You seem like a decent man. Why not? But you better travel light - no more than 35 pounds. Anything more than that and you'll slow us down. We're going to Reno, but I can drop you at Lovelock if you want. Ready to go?}
{130}{}{你看起来是个正派的人。为什么不？但你最好轻装上阵-不要超过35磅。再多些你就会拖我们的后腿。我们要去雷诺，但如果你愿意我可以把你送到洛夫洛克。准备好了吗？ -- You seem like a decent man. Why not? But you better travel light - no more than 35 pounds. Anything more than that and you'll slow us down. We're going to Reno, but I can drop you at Lovelock if you want. Ready to go?}
#{131}{}{Yes, drop me off at Lovelock.}
{131}{}{是的，让我在洛夫洛克下车。 -- Yes, drop me off at Lovelock.}
#{132}{}{Yes, let's go straight to Reno.}
{132}{}{是的，我们直接去雷诺吧。 -- Yes, let's go straight to Reno.}
#{133}{}{Not right now. I want to ask you something else.}
{133}{}{现在不行。我想问你点别的。 -- Not right now. I want to ask you something else.}
#{134}{}{No problem! Soon we'll finish up here and head back. But we can't let you slow us down. Travel light - no more than 35 pounds.}
{134}{}{没问题！很快我们就到这里，然后回去。但我们不能让你拖我们的后腿。旅行轻-不超过35磅。 -- No problem! Soon we'll finish up here and head back. But we can't let you slow us down. Travel light - no more than 35 pounds.}
#{135}{}{Great, let's go.}
{135}{}{太好了，我们走吧。 -- Great, let's go.}
#{136}{}{I have to take care of something first. I'll be right back.}
{136}{}{我得先处理一些事情。我马上回来。 -- I have to take care of something first. I'll be right back.}
#{137}{}{I need to dump some weight first. I'll be right back.}
{137}{}{我需要先卸下一些重量。我马上回来。 -- I need to dump some weight first. I'll be right back.}
#{138}{}{Aw, why are you bringing all that shit for? I told you, we can't let you slow us down dragging that crap around. Cut your equipment down to 35 pounds, then come back.}
{138}{}{啊，你为什么要带这些东西来？我告诉过你，我们不能让你拖我们的后腿。把你的装备减到35磅，然后回来。 -- Aw, why are you bringing all that shit for? I told you, we can't let you slow us down dragging that crap around. Cut your equipment down to 35 pounds, then come back.}
#{139}{}{Fine.}
{139}{}{好的。 -- Fine.}
#{140}{}{Yeah, and it'd be nice to unload some of it. You want to trade?}
{140}{}{是啊，能卸下一些就好了。你想交易吗？ -- Yeah, and it'd be nice to unload some of it. You want to trade?}
#{141}{}{Let's see what you've got.}
{141}{}{让我们看看你有什么。 -- Let's see what you've got.}
#{142}{}{That's it? Eh.}
{142}{}{就这样？嗯。 -- That's it? Eh.}
#{143}{}{Look, I would, but... You have not the best reputation around here. Kind of makes it hard to trust whatever you've got to trade, you know?}
{143}{}{听着，我会的，但是。。。你在这里名声不好。这让你很难相信你要交易的东西，你知道吗？ -- Look, I would, but... You have not the best reputation around here. Kind of makes it hard to trust whatever you've got to trade, you know?}
#{144}{}{Look, I would, but... There's talk going around the caravans about a guy who just happens to look a lot like you. Bad, BAD talk. That sort of thing makes a man nervous, you know? Like, maybe your deals aren't on the up-and-up.}
{144}{}{听着，我会的，但是。。。商队里到处都在谈论一个碰巧长得很像你的人。坏话，坏话。那种事让人紧张，你知道吗？比如，也许你的交易不是很顺利。 -- Look, I would, but... There's talk going around the caravans about a guy who just happens to look a lot like you. Bad, BAD talk. That sort of thing makes a man nervous, you know? Like, maybe your deals aren't on the up-and-up.}
#{145}{}{Look, I would, but... You've got kind of a reputation, you know? And it's not the kind that makes me want to trust whatever you've got to trade.}
{145}{}{听着，我会的，但是。。。你有点名气，知道吗？这不是那种让我想相信你所做的交易的人。 -- Look, I would, but... You've got kind of a reputation, you know? And it's not the kind that makes me want to trust whatever you've got to trade.}
#{150}{}{Sorry for the question, but - what did you eat while you were trapped?}
{150}{}{很抱歉问这个问题，但是-你被困的时候吃了什么？ -- Sorry for the question, but - what did you eat while you were trapped?}
#{151}{}{We had a few supplies left, but those didn't last long. We got water off the walls of the cave and ate any radscorpions or rats we could find in there. You can't be a trader without at least a few survival skills.}
{151}{}{我们还剩下一些补给品，但用不了多久。我们从洞壁上取了水，吃了里面能找到的任何蝎子或老鼠。你不可能成为一个没有生存技能的交易者。 -- We had a few supplies left, but those didn't last long. We got water off the walls of the cave and ate any radscorpions or rats we could find in there. You can't be a trader without at least a few survival skills.}
#{152}{}{Can you teach this skill to someone? Me, for example?}
{152}{}{你能教别人这个技能吗？比如我？ -- Can you teach this skill to someone? Me, for example?}
#{153}{}{Hell yeah, I can. Sit down by the campfire and I'll give you all my favorite wasteland recipes.}
{153}{}{是的，我可以。坐在篝火旁，我会给你我最喜欢的荒地食谱。 -- Hell yeah, I can. Sit down by the campfire and I'll give you all my favorite wasteland recipes.}
#{154}{}{[Sit down by the campfire...]}
{154}{}{[在营火旁坐下…] -- [Sit down by the campfire...]}
#{155}{}{The caravaneer taught you how to properly cook food on the campfire.}
{155}{}{商队教练教你如何在营火上正确烹饪食物。 -- The caravaneer taught you how to properly cook food on the campfire.}
#{1113}{}{Hey there, girl! How are you?}
{1113}{}{嘿，姑娘！你好吗？ -- Hey there, girl! How are you?}
#{1130}{}{You seem like a decent woman. Why not? But you better travel light - no more than 35 pounds. Anything more than that and you'll slow us down. We're going to Reno, but I can drop you at Lovelock if you want. Ready to go?}
{1130}{}{你看起来是个正派的女人。为什么不？但你最好轻装上阵-不要超过35磅。再多些你就会拖我们的后腿。我们要去雷诺，但如果你愿意我可以把你送到洛夫洛克。准备好了吗？ -- You seem like a decent woman. Why not? But you better travel light - no more than 35 pounds. Anything more than that and you'll slow us down. We're going to Reno, but I can drop you at Lovelock if you want. Ready to go?}
#{1144}{}{Look, I would, but... There's talk going around the caravans about a girl who just happens to look a lot like you. Bad, BAD talk. That sort of thing makes a man nervous, you know? Like maybe your deals aren't on the up-and-up.}
{1144}{}{听着，我会的，但是。。。商队里到处都在说一个女孩碰巧长得很像你。坏话，坏话。那种事让人紧张，你知道吗？好像你的交易不是很顺利。 -- Look, I would, but... There's talk going around the caravans about a girl who just happens to look a lot like you. Bad, BAD talk. That sort of thing makes a man nervous, you know? Like maybe your deals aren't on the up-and-up.}
