#{100}{}{You'd better not go down into this muddy water.}
{100}{}{你最好不要下到这泥水里去。 -- You'd better not go down into this muddy water.}
#{101}{}{Swarm down into this cesspool?! No way!}
{101}{}{蜂拥到这个粪池里？！不可能！ -- Swarm down into this cesspool?! No way!}
#{102}{}{You have dashingly jumped over the fence from the top of those boxes.}
{102}{}{你已经从那些箱子的顶部跳过了栅栏。 -- You have dashingly jumped over the fence from the top of those boxes.}
#{103}{}{You climbed on the roof using that big pile of boxes.}
{103}{}{你用那堆箱子爬上了屋顶。 -- You climbed on the roof using that big pile of boxes.}
#{104}{}{Looking at this huge station from this height, you decide, that there is no point in going down for you.}
{104}{}{从这个高度看这个巨大的空间站，你决定，你没有必要下去。 -- Looking at this huge station from this height, you decide, that there is no point in going down for you.}
#{105}{}{I have nothing to do there}
{105}{}{我在那里没什么事可做 -- I have nothing to do there}
#{106}{}{Because of the exhaustion, you couldn't hold it and fell down, breaking your legs.}
{106}{}{因为筋疲力尽，你扶不住，摔倒了，摔断了腿。 -- Because of the exhaustion, you couldn't hold it and fell down, breaking your legs.}
#{107}{}{Because of your inattention, you stumbled and rolled down the stairs, breaking your legs.}
{107}{}{因为你的疏忽，你跌跌撞撞地从楼梯上滚下来，摔断了腿。 -- Because of your inattention, you stumbled and rolled down the stairs, breaking your legs.}
#{108}{}{Because of your clumsiness, you slipped and rolled down like a ball, breaking your legs.}
{108}{}{因为你的笨拙，你像球一样滑倒了，摔断了腿。 -- Because of your clumsiness, you slipped and rolled down like a ball, breaking your legs.}
#{109}{}{You climbed to the roof of the building, and then jumped to the ground.}
{109}{}{你爬到楼顶，然后跳到地上。 -- You climbed to the roof of the building, and then jumped to the ground.}
