#{100}{}{You see Jasmine.}
{100}{}{你看到茉莉花了。}
#{101}{}{You see a girl wearing a red scarf on her neck.}
{101}{}{你看到一个女孩脖子上戴着红领巾。}
#{102}{}{Thanks for the cash. First chance I get, I'm out of here.}
{102}{}{谢谢你的现金。一有机会，我就离开这里。}
#{103}{}{I don't feel good... }
{103}{}{我感觉不太好。。。}
#{109}{}{. And yours?}
{109}{}{. 你的呢？}
#{110}{}{[You see a girl with beautiful hair and a red scarf around her neck. As soon as she makes eye contact with you, she gives a flirty smile.] Well, hello, handsome. New in town? I'd do *anything* for some conversation around here. Are you just passing by, or are you here to stay?}
{110}{}{[你看到一个长着漂亮头发，脖子上围着红领巾的女孩。她一和你眼神接触，就会露出调情的微笑。新来的？我愿意为这附近的谈话做任何事。你只是路过，还是要留下来？}
#{111}{}{Nice to meet you. My name is }
{111}{}{很高兴认识你。我的名字是}
#{112}{}{Who are you?}
{112}{}{你是谁？}
#{113}{}{Can't you converse with the people here?}
{113}{}{你不能和这里的人交谈吗？}
#{114}{}{Isn't it hot in that scarf?}
{114}{}{戴着那条围巾不是很热吗？}
#{115}{}{Baby? Why'd you call me "baby"?}
{115}{}{宝贝？你为什么叫我“宝贝”？}
#{116}{}{Why am I "baby"?}
{116}{}{为什么我是“宝贝”？}
#{117}{}{Don't worry, baby. It's just 'cuz I like you.}
{117}{}{别担心，宝贝。只是因为我喜欢你。}
#{120}{}{What a nice name! I'm Jasmine. Good to meet you.}
{120}{}{多好的名字啊！我是茉莉。很高兴见到你。}
#{121}{}{Hmm, how do I say this... I used to work in the fields, now I'm resting. Is that good enough, baby?}
{121}{}{嗯，我该怎么说。。。我以前在地里干活，现在在休息。够了吗，宝贝？}
#{122}{}{[She crosses her arms and scowls] Hmph! It's no good talking to the people here. Don't ask, baby, I have my reasons.}
{122}{}{[她交叉双臂，愁眉不展]哼！跟这里的人说话没用。别问，宝贝，我有我的理由。}
#{123}{}{Oh, my! [she smiles slyly, then begins to unbutton her shirt] I can take it all off if you want, baby.}
{123}{}{哦，天哪！[她狡黠地笑了笑，然后开始解开衬衫的扣子]如果你愿意，我可以把它全部脱下来，宝贝。}
#{124}{}{Uh... Why?}
{124}{}{休斯敦大学。。。为什么？}
#{125}{}{Really? You'd do that?}
{125}{}{真正地？你会这么做吗？}
#{126}{}{[She laughs] Are you serious? You really don't know? [she puts a finger under your chin and winks] Don't worry, baby. I'm a great teacher.}
{126}{}{你是认真的吗？你真的不知道？别担心，宝贝。我是个好老师。}
#{127}{}{[She places her hand on your shoulder] Baby, I'll do a lot more than that. Just put your hand here... }
{127}{}{[她把手放在你的肩膀上]宝贝，我会做更多。把手放在这里。。。}
#{128}{}{Woah! What's that under your scarf?!}
{128}{}{哇！你围巾下面是什么？！}
#{129}{}{[The flirty expression drops off her face and she pushes you away, turning her back on you] Every fuckin' time! It starts good, but you get one look and... [she sighs] Just... Go.}
{129}{}{[调情的表情从她脸上消失，她推开你，背对着你]他妈的每一次！开始不错，但你看一眼。。。只是。。。去吧。}
#{130}{}{Jasmine?}
{130}{}{茉莉花？}
#{150}{}{[She gives you a dead, silent stare, waiting for you to leave.]}
{150}{}{[她默默地盯着你，等着你离开。]}
#{151}{}{[Leave silently]}
{151}{}{[静静地离开]}
#{152}{}{Can I ask you few questions about Black Rock?}
{152}{}{我能问你几个关于黑岩的问题吗？}
#{153}{}{[She frowns] You think I know anything? Go ask at the bar, they never shut up. They won't even let me inside.}
{153}{}{你以为我知道什么？去酒吧问问，他们从不闭嘴。他们甚至不让我进去。}
#{154}{}{Bye.}
{154}{}{再见。}
#{155}{}{How did you end up here?}
{155}{}{你怎么到这里来的？}
#{156}{}{Daddy - my real Daddy - made me leave Reno. He thought he could save me from my life there. Then he got eaten by a pack of geckos, and now I'm gonna starve to death all alone. Ain't that ironic?}
{156}{}{爸爸-我真正的爸爸-让我离开雷诺。他以为他能把我从那里救出来。然后他被一群壁虎吃掉了，现在我要一个人饿死了。这不是很讽刺吗？}
#{157}{}{What where you doing there?}
{157}{}{你在那里干什么？}
#{158}{}{Oh my god, you really don't get it? I'm a whore, a cheap fucking whore! Any motherfucker could have me for fifty bucks, and that's before my pimp's cut.}
{158}{}{天哪，你真的不明白吗？我是个婊子，一个贱婊子！任何一个混蛋都可以花50块就把我抢走，那是在我的皮条客被裁之前。}
#{159}{}{I'm sorry. I didn't mean to upset you.}
{159}{}{我很抱歉。我不是故意让你难过的。}
#{160}{}{Let's talk about something else.}
{160}{}{我们再谈点别的吧。}
#{161}{}{About what?}
{161}{}{关于什么？}
#{162}{}{Work is work. That doesn't bother me.}
{162}{}{工作就是工作。我不介意。}
#{163}{}{So... What's a "whore"?}
{163}{}{所以。。。什么叫“妓女”？}
#{164}{}{[She stares at you with wide eyes] Are you fuckin' with me? Oh my god, I think you're really serious. Holy shit... A virgin, at your age.}
{164}{}{[她瞪大眼睛盯着你]你他妈的跟我在一起吗？天哪，我觉得你是认真的。天啊。。。像你这样年纪的处女。}
#{165}{}{What?}
{165}{}{什么？}
#{166}{}{If I weren't sick, baby, I'd show you... For fifty bucks. But right now, no one should touch me.}
{166}{}{如果我没有生病，宝贝，我会给你看。。。五十美元。但现在，没人能碰我。}
#{170}{}{Jasmine, what's happening to your skin?}
{170}{}{茉莉，你的皮肤怎么了？}
#{171}{}{[She sighs] You really wanna know? I've got this horrible shit on my skin - just a few places right now, but nobody knows what'll happen next. People stared and talked behind my back... I gotta wear this scarf so they don't see.}
{171}{}{你真的想知道吗？我的皮肤上有这种可怕的东西-现在只有几个地方，但没人知道接下来会发生什么。人们在我背后盯着我说话。。。我得戴上这条围巾，这样他们就看不见了。}
#{172}{}{May I see?}
{172}{}{我可以看看吗？}
#{173}{}{Wow, I think I'm going to be sick. I better go.}
{173}{}{哇，我想我要生病了。我得走了。}
#{174}{}{[She hesitates, then silently unwraps the scarf. On the side of her neck you see a large mound of swollen and painful-looking blisters.]}
{174}{}{[她犹豫了一下，然后默默地解开围巾。在她脖子的一侧，你可以看到一大堆肿胀疼痛的水泡。]}
#{175}{}{This is definitely an infection, probably sexually transmitted. I think it can be cured, but you'll need antibacterial medication.}
{175}{}{这肯定是感染，可能是性传播。我认为可以治愈，但你需要抗菌药物。}
#{176}{}{Really? I thought it'd just get worse and worse my whole life! But I can't buy any medicine. Even if I had the money, where the hell would I get it?}
{176}{}{真正地？我以为我的生活会越来越糟！但是我买不到药。即使我有钱，我他妈的从哪里弄到钱？}
#{177}{}{You earned 100 experience point for making the right diagnosis.}
{177}{}{做出正确的诊断，你获得了100点经验值。}
#{178}{}{That's pretty nasty. Do you know what it is?}
{178}{}{那太恶心了。你知道是什么吗？}
#{179}{}{[She shrugs sadly] No, except that it's bad.}
{179}{}{[她悲伤地耸耸肩]没有，只是很糟糕。}
#{180}{}{From me. [give her a bottle of Blood-purifier]}
{180}{}{从我这里。[给她一瓶血液净化器]}
#{181}{}{Where did you get this?}
{181}{}{你从哪儿弄来的？}
#{182}{}{Probably some junkie in Reno, or another one of the girls. You couldn't even imagine the types I had to sleep with... }
{182}{}{可能是里诺的某个瘾君子，或者其他女孩。你甚至无法想象我要和什么样的人上床。。。}
#{183}{}{You've known other people with this?}
{183}{}{你认识其他人吗？}
#{184}{}{Yeah. Something like every tenth whore in Reno's got it. No one lives for long with it - usually they take poison and die, so it's quicker.}
{184}{}{是 啊。里诺每十个妓女都有。没有人会因为它而活很长时间——通常他们会服毒而死，所以会更快。}
#{185}{}{If I'm ever in Reno, I'll remember that. Take care.}
{185}{}{如果我在里诺，我会记住的。当心。}
#{186}{}{I'll get you the medicine, don't worry.}
{186}{}{我给你拿药，别担心。}
#{187}{}{}
{187}{}{}
#{188}{}{}
{188}{}{}
#{189}{}{I'll try to find you the cure.}
{189}{}{我会给你找解药的。}
#{190}{}{I know this is unpleasant, but we have to talk about your skin.}
{190}{}{我知道这很不愉快，但我们得谈谈你的皮肤。}
#{191}{}{Haven't you tried going to a doctor?}
{191}{}{你没试过去看医生吗？}
#{192}{}{Show me your skin condition.}
{192}{}{给我看看你的皮肤状况。}
#{193}{}{You see any fuckin' doctors around here? Even in Reno you gotta keep buying anaesthetic from chem dealers to keep it from getting too bad. I think Jed, the old man that lives next to Justin, told me they managed to cure it in Reno a long time ago with some kinda plant, but that's it. I don't even know if it's true.}
{193}{}{你看到这附近有医生吗？即使在里诺，你也要不断地从化学药品商那里购买麻醉剂，以防病情恶化。我想杰德，住在贾斯汀旁边的老人，告诉我他们很久以前在里诺用某种植物治好了，但就是这样。我都不知道是不是真的。}
#{194}{}{No shit? You're really gonna help me? [she smiles] Thank you! I didn't think anyone even cared! Try talking to Jed - he said he knew of some medicine made out of a plant or something, but he didn't remember how to make it. Maybe you can get something more out of him.}
{194}{}{什么都没有？你真的要帮我？[她微笑]谢谢！我以为没人在乎！试着和杰德谈谈——他说他知道一些用植物什么的制成的药，但他不记得怎么做了。也许你能从他身上得到更多。}
#{195}{}{Fine.}
{195}{}{好的。}
#{200}{}{Let's talk about your cure.}
{200}{}{我们来谈谈你的治疗方法。}
#{201}{}{Yeah?}
{201}{}{是 啊？}
#{202}{}{I have this medicine for you. [give her the flask of Blood-purifier]}
{202}{}{我有这种药给你。[给她一瓶血液净化器]}
#{203}{}{I have this medicine for you. [give her the flask of poison]}
{203}{}{我有这种药给你。[给她一瓶毒药]}
#{204}{}{Sorry, nothing yet.}
{204}{}{对不起，还没有。}
#{205}{}{Oh my god! Thank you, thank you, thank you! [she grabs the medicine] I didn't think there were actually people like you in the world! You're my guardian fuckin' angel, you gave me my life back! I swear, I'll never fuck anyone for money again!}
{205}{}{哦，我的上帝！谢谢，谢谢，谢谢！[她抓起药]我没想到世界上真的有你这样的人！你是我的守护天使，你把我的生命还给了我！我发誓，我再也不会为了钱操任何人了！}
#{206}{}{I hope it helps.}
{206}{}{希望对你有帮助。}
#{207}{}{Make sure you drink it all.}
{207}{}{一定要把它喝光。}
#{208}{}{One way or another, you removed the infection from the community.}
{208}{}{不管怎样，你从社区中消除了感染。}
#{209}{}{Thanks to you, Jasmine is on the road to recovery.}
{209}{}{多亏了你，茉莉正在康复的路上。}
#{210}{}{What do you think could heal you?}
{210}{}{你认为什么能治愈你？}
#{211}{}{[She shrugs helplessly] How the fuck should I know? Old man Jed might know something - he told me there was this plant that could cure it, but he doesn't remember anything else.}
{211}{}{[她无助地耸耸肩]我他妈的怎么知道？杰德老人也许知道些什么——他告诉我有一种植物可以治愈它，但他什么都不记得了。}
#{220}{}{Someone told me they don't want your infection in this town. Nothing personal, Jasmine.}
{220}{}{有人告诉我他们不想让你在这个镇上感染。不是针对个人的，茉莉。}
#{221}{}{[She sighs] So they finally decided? God dammit, I knew this would happen. But I hoped they'd at least come here themselves so I could spit in their faces.}
{221}{}{他们最后决定了？天哪，我就知道会这样。但我希望他们至少自己来这里，这样我就可以朝他们脸上吐口水了。}
#{222}{}{You'll have to move somewhere else. For your own sake.}
{222}{}{你得搬到别的地方去。为了你自己。}
#{223}{}{I'm not here to talk. Get out now, or die!}
{223}{}{我不是来说话的。快滚出去，不然就死定了！}
#{224}{}{We'll discuss this later.}
{224}{}{我们稍后再讨论。}
#{225}{}{You think I don't belong here? You're probably right... But the caravan said I'd have to pay a hundred bucks to go with them! I don't have any money!}
{225}{}{你认为我不属于这里？你可能是对的。。。但是商队说我得付一百块钱才能跟他们一起去！我没有钱！}
#{226}{}{Here's a hundred dollars.}
{226}{}{这是一百美元。}
#{227}{}{[She looks stunned] You're... You're serious? I didn't think anyone would pay to get rid of me. Okay, I understand. I promise I'll go with the next caravan.}
{227}{}{[她看起来惊呆了]你。。。你说真的？我没想到会有人付钱把我赶走。好吧，我明白。我保证我会和下一个商队一起去。}
#{228}{}{You'd better. I'll be watching.}
{228}{}{你最好这样。我会看着的。}
#{229}{}{}
{229}{}{}
#{230}{}{But - but I can't!}
{230}{}{但是-但是我不能！}
#{231}{}{I warned you. [attack]}
{231}{}{我警告过你。[攻击]}
#{232}{}{And why not?}
{232}{}{为什么不呢？}
#{233}{}{You can stay for now, but we will talk about this later.}
{233}{}{你现在可以留下，但我们稍后再谈。}
#{234}{}{I have no money for a caravan! No one will help me, and I can't even sell myself! I can't even go back to Reno, Daddy sold our house! I'll be left in the street!}
{234}{}{我没钱买辆大篷车！没有人会帮我，我甚至不能出卖自己！我都回不了雷诺了，爸爸把我们的房子卖了！我会被留在街上！}
#{235}{}{No, you'll be in the ground. [attack]}
{235}{}{不，你会在地上的。[攻击]}
#{236}{}{Yeah, that's really sad. But the locals don't want you here anymore. You have to leave.}
{236}{}{是啊，真的很难过。但是当地人不想你再呆在这里了。你必须离开。}
#{250}{}{My guardian angel!}
{250}{}{我的守护天使！}
#{251}{}{How do you feel?}
{251}{}{你觉得怎么样？}
#{252}{}{Let's talk about your sickness again. How did you get infected?}
{252}{}{我们再谈谈你的病吧。你是怎么被感染的？}
#{253}{}{Where else? Reno. Every whore there got some kind of disease. It's just one of the million ways the big city tries to kill you.}
{253}{}{还有哪里？雷诺。那里的每个妓女都得了某种疾病。这只是大城市试图杀死你的百万方法之一。}
#{254}{}{Great! There are still marks on my skin, but I feel strong and healthy. And it's all because of you!}
{254}{}{太好了！我的皮肤上仍然有伤痕，但我感到强壮和健康。都是因为你！}
#{255}{}{Rest now.}
{255}{}{现在休息。}
#{260}{}{Now that you're cured, will you be alright in this town?}
{260}{}{既然你治好了，你在这个镇上还好吗？}
#{261}{}{Well... [she sighs] I'm... Lonely. No one's gonna try to make me leave or kill me now, but everyone still knows what I did in Reno. I've... I've always wanted a family, but... [she shakes her head] Never gonna happen.}
{261}{}{好。。。[她叹息]我。。。孤独。现在没人想逼我离开或者杀了我，但大家都知道我在雷诺干了什么。我已经。。。我一直想要一个家庭，但是。。。[她摇头]永远不会发生。}
#{262}{}{No one here will make a family with you?}
{262}{}{这里没人会和你成家？}
#{263}{}{Who would want me? No normal guy is going to want some used-up whore.}
{263}{}{谁会想要我？没有一个正常人会想要一个用光了的妓女。}
#{264}{}{Does he have to be normal? How about Gravedigger Bob?}
{264}{}{他一定要正常吗？掘墓人鲍勃呢？}
#{265}{}{Well, you never know. There's always hope.}
{265}{}{你永远不会知道。总有希望。}
#{266}{}{Oh, stop this nonsense.}
{266}{}{哦，别胡说了。}
#{267}{}{[She laughs] Bob?! That weird goofball? He's old! I mean, not too old for kids, but... Look at his head, and that tooth! He's so ugly, he... He wouldn't even be disgusted by a used up woman like me! And he's got that stutter, which is, y'know, kinda cute in a way, but... He lives alone, like I had to... And... And he's a hard worker, and really sort of sweet, and he doesn't smell *that* bad, compared to some of the guys in Reno, and... Hmmm. I mean... But, you know... That one thing.}
{267}{}{鲍勃？！那个怪球？他老了！我是说，对孩子来说不算太大，但是。。。看看他的头，还有那颗牙！他太丑了，他。。。他甚至不会对我这样的女人感到厌恶！他有口吃，你知道，在某种程度上有点可爱，但是。。。他一个人住，就像我不得不。。。还有。。。他是个勤奋的人，真的有点甜，和里诺的一些人相比，他闻起来没那么难闻，而且。。。嗯，我是说。。。但是，你知道。。。有一件事。}
#{268}{}{What thing?}
{268}{}{什么东西？}
#{269}{}{}
{269}{}{}
#{270}{}{He, uh... How should I put it? People say he, err... "defiles" the corpses. If that's true, he's a maniac! I don't want to live with a psycho! Do you think I can trust him?}
{270}{}{他，呃。。。我该怎么说呢？人们说他，呃……”玷污“尸体”。如果那是真的，他是个疯子！我不想和疯子住在一起！你认为我能相信他吗？}
#{271}{}{You trust me, right? I'm telling you - don't listen to those rumors.}
{271}{}{你相信我，对吧？我告诉你-别听那些谣言。}
#{272}{}{You're right, you'd better stay away from him.}
{272}{}{你说得对，你最好离他远点。}
#{273}{}{Wait here. I'll learn more and come back.}
{273}{}{在这里等着。我会学到更多回来的。}
#{274}{}{You're the only one I trust. Okay, I'll do it! You'll ask him about the date, right? I can't go myself. With my reputation, I don't want him to, you know... Misunderstand me?}
{274}{}{你是我唯一信任的人。好吧，我来！你会问他约会的事，对吗？我自己去不了。以我的名誉，我不想让他，你知道。。。你误解我了？}
#{275}{}{I'll set you up.}
{275}{}{我来安排你。}
#{276}{}{I'll go see what can be done.}
{276}{}{我去看看能做些什么。}
#{277}{}{This is great!}
{277}{}{这太好了！}
#{278}{}{See you.}
{278}{}{再见。}
#{279}{}{You see?}
{279}{}{你看到了吗？}
#{280}{}{I convinced Bob to go on a date with you. He's a little rough, but he is what he is.}
{280}{}{我说服鲍勃和你约会。他有点粗鲁，但他就是这样。}
#{281}{}{Oh, you're amazing! [she hugs you] No one's ever been so good to me. Thank you so much! Now I've got to get ready for my date. Oh, I'm so excited!}
{281}{}{哦，你太棒了！[她拥抱你]从来没有人对我这么好。非常感谢！现在我得为我的约会做准备了。哦，我太兴奋了！}
#{282}{}{Good luck.}
{282}{}{祝你好运。}
#{283}{}{Ex-prostitute and necrophiliac are united at the cemetery. You've never seen anything so heartwarming and sweet.}
{283}{}{前妓女和嗜尸癖者在公墓合二为一。你从没见过这么温馨甜蜜的东西。}
#{284}{}{Bob said no. Actually, that's not quite true. He said your body will be the first he burns instead of buries, because you're so sick and filthy that he doesn't want to contaminate the groundwater, and that he'd rather fuck corpses than you because they stink less and have more charming personalities.}
{284}{}{鲍勃说不。事实上，那不是真的。他说你的身体会是他第一个被烧伤而不是埋葬的，因为你病得很重，很脏，他不想污染地下水，他宁愿操尸体也不想操你，因为尸体的臭味更少，个性更迷人。}
#{285}{}{He said that? He... That... [she starts to cry] That bastard! He was my last chance... Thank you for trying, anyway. It's not your fault. After everything I've done, maybe I deserve to be alone... }
{285}{}{他这么说？他。。。那个。。。那个混蛋！他是我最后的机会。。。无论如何，谢谢你的努力。这不是你的错。在我做了这么多之后，也许我应该一个人呆着。。。}
#{286}{}{Sorry, Jasmine.}
{286}{}{对不起，茉莉。}
#{287}{}{Yeah, probably.}
{287}{}{是的，可能吧。}
#{288}{}{You snuffed out the last bit of hope in two damaged people. That's on you now.}
{288}{}{你扼杀了两个受伤的人的最后一点希望。现在你请客。}
#{290}{}{What do you know about the missing brahmin?}
{290}{}{你对失踪的婆罗门了解多少？}
#{291}{}{William's boy says he was watching the brahmin all night, but I saw him sleeping. He was even snoring. Ahh... Cute kid.}
{291}{}{威廉的儿子说他整晚都在看婆罗门，但我看到他在睡觉。他甚至在打鼾。啊。。。可爱的孩子。}
#{292}{}{Did anything unusual happen that night?}
{292}{}{那晚有什么不寻常的事吗？}
#{293}{}{Hmm, not really. Bolt used the toilet at night, and Justin used it in the morning. William woke me up when he was yelling at his boy for losing the brahmin.}
{293}{}{嗯，不是真的。博尔特晚上用厕所，贾斯汀早上用。威廉把我吵醒了，当时他正对他的儿子大喊大叫，说他失去了婆罗门。}
#{294}{}{Right.}
{294}{}{正确的。}
#{1110}{}{[You see a girl with a beautiful hair and red scarf around her neck. As soon as she makes eye contact with you, she gives a flirty smile.] Well, hello, beautiful. New in town? I'd do *anything* for some conversation around here. Are you just passing by, or are you here to stay?}
{1110}{}{[你看到一个长着漂亮头发，脖子上围着红领巾的女孩。她一和你眼神接触，就会露出调情的微笑。新来的？我愿意为这附近的谈话做任何事。你只是路过，还是要留下来？}
#{1126}{}{[She laughs] Are you serious? You really don't know? [she puts a finger under your chin and winks] Don't worry, baby. I'm a great teacher.}
{1126}{}{你是认真的吗？你真的不知道？别担心，宝贝。我是个好老师。}
#{1159}{}{I'm sorry. I didn't mean to upset you.}
{1159}{}{我很抱歉。我不是故意让你难过的。}
#{1164}{}{[She stares at you with wide eyes] Are you fuckin' with me? Oh my god, I think you're really serious. Holy shit... A virgin, at your age.}
{1164}{}{[她瞪大眼睛盯着你]你他妈的跟我在一起吗？天哪，我觉得你是认真的。天啊。。。像你这样年纪的处女。}
#{1178}{}{That's pretty nasty. Do you know what it is?}
{1178}{}{那太恶心了。你知道是什么吗？}
#{1227}{}{[She looks stunned] You're... You're serious? I didn't think anyone would pay to get rid of me. Okay, I understand. I promise I'll go with the next caravan.}
{1227}{}{[她看起来惊呆了]你。。。你说真的？我没想到会有人付钱把我赶走。好吧，我明白。我保证我会和下一个商队一起去。}
#{1250}{}{My guardian angel!}
{1250}{}{我的守护天使！}
#{1274}{}{You're the only one I trust. Okay, I'll do it! You'll ask him about the date, right? I can't go myself. With my reputation, I don't want him to, you know... Misunderstand me?}
{1274}{}{你是我唯一信任的人。好吧，我来！你会问他约会的事，对吗？我自己去不了。以我的名誉，我不想让他，你知道。。。你误解我了？}
