#{100}{}{You see a prospector.}
{100}{}{你看到一个探矿者。}
#{101}{}{You see a young man with a look of despair in his eyes.}
{101}{}{你看到一个眼神绝望的年轻人。}
#{102}{}{}
{102}{}{}
#{110}{}{Hello. And goodbye.}
{110}{}{你好。再见。}
#{111}{}{Hi, who are you?}
{111}{}{嗨，你是谁？}
#{112}{}{}
{112}{}{}
#{113}{}{Look, sorry, but I don't want to talk to anyone right now. Just let me sit here in peace.}
{113}{}{听着，对不起，我现在不想和任何人说话。让我安静地坐在这里。}
#{114}{}{Fine.}
{114}{}{好的。}
#{115}{}{Can you tell me anything interesting?}
{115}{}{你能告诉我什么有趣的事吗？}
#{116}{}{Bye.}
{116}{}{再见。}
#{117}{}{Um, no. I don't think so. I don't know anything "interesting".}
{117}{}{嗯，不。我不这么认为。我不知道什么“有趣的”。}
#{118}{}{You're not much fun to talk to.}
{118}{}{跟你说话没什么意思。}
#{119}{}{Mm-hmm. Yeah. You too.}
{119}{}{嗯。是的。你也是。}
#{150}{}{Someone told me a prospector from Reno is hiding in Black Rock. Do you know anything about that?}
{150}{}{有人告诉我一个来自雷诺的探矿者藏在黑岩里。你知道吗？}
#{151}{}{Er... Well, there's people here from all over Nevada. Why?}
{151}{}{呃。。。嗯，这里有来自内华达州各地的人。为什么？}
#{152}{}{No reason... It just so happens I have something from Mr. Wright.}
{152}{}{没有理由。。。碰巧我从赖特先生那里得到了一些东西。}
#{153}{}{[Furtively draws his head into shoulders] Mr. Who? N-never heard of him. Er... Why, who is he looking for?}
{153}{}{[偷偷地把头伸进肩膀]谁？从没听说过他。呃。。。为什么，他在找谁？}
#{154}{}{Well, well. I never said he was looking for anyone.}
{154}{}{好吧，好吧。我从没说过他在找人。}
#{155}{}{[He looks around agitatedly] Mister Wright put a hit on me, didn't he?}
{155}{}{[他激动地环顾四周]莱特先生打了我一拳，不是吗？}
#{156}{}{That's right. A thousand bucks. And believe me, someone's gonna collect it.}
{156}{}{这是正确的。一千块。相信我，会有人来收集的。}
#{157}{}{I'm not here on Wright's behalf. Someone else sent me.}
{157}{}{我不是代表赖特来的。是别人派我来的。}
#{158}{}{What, right here, in front of everybody? No, they- wait, did you say *thousand*? No, it can't be! Listen, Wright's not going to pay that. He's lying, don't you get it?}
{158}{}{什么，就在这里，在大家面前？不，他们-等等，你是说一千？不，不可能！听着，赖特不会付钱的。他在撒谎，你不明白吗？}
#{159}{}{There's nothing to get. I just want that money.}
{159}{}{没有什么可以得到的。我只想要那笔钱。}
#{160}{}{That's interesting to hear. What's the deal between you and Wright?}
{160}{}{这很有趣。你和赖特之间有什么交易？}
#{161}{}{Uh, just - just wait! Wright's not going to see my body anyway, right? How about this: I give you my contract with him and you get off me. You'll show him the contract and tell him you took it off my dead body. He'll never see me again. And I'll even give you my metal detector, I'm sure you can get some cash for it! Can... Can we make a deal?}
{161}{}{呃，等等！赖特无论如何也不会看到我的身体，对吧？不如这样：我把我和他的合同给你，你就滚开。你要给他看合同，告诉他你从我尸体上拿走了。他再也见不到我了。我甚至会把我的金属探测器给你，我相信你可以拿些现金！我可以。。。我们能做个交易吗？}
#{162}{}{Why not? Give me the contract and the metal detector. I'll take care of everything else.}
{162}{}{为什么不？把合同和金属探测器给我。其他的我都会处理。}
#{163}{}{First, tell me what happened between you and Wright.}
{163}{}{首先，告诉我你和赖特之间发生了什么。}
#{164}{}{Lying is a nasty habit, but in this case, a profitable one.}
{164}{}{说谎是一种讨厌的习惯，但在这种情况下，说谎是一种有利可图的习惯。}
#{165}{}{[He sighs in relief] Oh, thank god... Look, if it's another competing prospectors - good luck to them. I could never finish the contract anyway.}
{165}{}{[他松了口气]哦，感谢上帝。。。听着，如果是另一个竞争的探矿者-祝他们好运。无论如何，我永远也不能完成合同。}
#{166}{}{Tell me more.}
{166}{}{告诉我更多。}
#{167}{}{Where do I even start? My partner and I were supposed to get the explosives from Hawthorne, but it turned out to be not so easy. Robert died by the hands of some rival prospectors, and I alone couldn't get the job done. I snuck back into Reno to talk with my family, and we all decided it'll be better for me to leave the city, before Wright's sons kill me. That's the short version.}
{167}{}{我从哪里开始？我和我的搭档本来应该从霍桑那里拿到炸药的，但结果没那么容易。罗伯特死于一些竞争对手的探矿者之手，只有我一个人无法完成这项工作。我偷偷溜回里诺和家人谈谈，我们都决定在莱特的儿子们杀了我之前，我最好还是离开这座城市。这是简短的版本。}
#{168}{}{Why does Wright need explosives?}
{168}{}{为什么莱特需要炸药？}
#{169}{}{How did Robert die?}
{169}{}{罗伯特是怎么死的？}
#{170}{}{Why didn't you say anything to Robert's family?}
{170}{}{你为什么不告诉罗伯特的家人？}
#{171}{}{Why do you think Wright would kill you?}
{171}{}{你觉得赖特为什么会杀了你？}
#{172}{}{Why all the secrecy?}
{172}{}{为什么要保密？}
#{173}{}{Wright controls the electricity business in Reno. He used to make good money off it before, but now he's barely scraping by. There's a village south of Reno built around an old uranium mine, and he needs that uranium to make power. I don't know exactly where the explosives come in, but my guess is that he's expanding the mine.}
{173}{}{赖特控制着雷诺的电力业务。他以前靠这个赚大钱，但现在几乎过不去了。里诺南部有个村庄围绕着一个老铀矿而建，他需要铀来发电。我不知道炸药到底是从哪里来的，但我猜他在扩建矿井。}
#{174}{}{I was coming back from a exploration run, when I saw rival competitors in our camp. I hid, but Robert... [he sighs] I wanted to help, but it was one against four. It's pure luck I survived at all.}
{174}{}{我刚从探险队回来，突然在营地里看到了竞争对手。我藏起来了，但是罗伯特。。。[他叹了口气]我想帮忙，但那是一对四。我幸免于难。}
#{175}{}{How?! You want me to look in their eyes and tell them I just left their son to die? God, I can't even look myself in the mirror. How can I possibly face them?}
{175}{}{怎样？！你想让我看着他们的眼睛告诉他们我让他们的儿子死了？天哪，我甚至不能照镜子。我怎么可能面对他们？}
#{176}{}{Because that's what he fucking does! He's a gangster, like every other boss in Reno! He'd make an example of me. Honestly, I can't even blame him - I messed up, and my family already owes him a lot of money.}
{176}{}{因为他就是这么做的！他是个流氓，就像雷诺的其他老板一样！他会以我为榜样。老实说，我甚至不能怪他-我搞砸了，我的家人已经欠他很多钱了。}
#{177}{}{Wright didn't want the competition. Every boss in Reno is fighting for more territory and influence.}
{177}{}{赖特不想参加比赛。雷诺的每一位老板都在争取更多的地盘和影响力。}
#{178}{}{Tell me more about these explosives.}
{178}{}{告诉我更多关于这些炸药的事。}
#{179}{}{Wright wanted five crates of C-4. Hawthorne's the only place likely to have it, but we couldn't get past the defense systems. Robert wanted to repair a robot to take out the mines, but, in any case, you can't sneak past the turrets with those crates in hands. We figured the warehouse would have a car or something, but we didn't even have a plan for getting the C-4 to the mines. God, what a stupid plan that was.}
{179}{}{赖特想要五箱C-4。霍桑是唯一可能拥有它的地方，但我们无法通过防御系统。罗伯特想修理一个机器人来清除地雷，但无论如何，你不能手里拿着那些板条箱溜过炮塔。我们以为仓库里会有车什么的，但我们甚至没有把C-4运到矿上的计划。天哪，那是多么愚蠢的计划啊。}
#{180}{}{You know what I think about all of this?}
{180}{}{你知道我是怎么想的吗？}
#{181}{}{What?}
{181}{}{什么？}
#{182}{}{I'll just kill you and tell Wright the job is done. What do you say to that?}
{182}{}{我就杀了你，告诉赖特任务完成了。你怎么说？}
#{183}{}{You abandoned your family and left Robert's family to suffer. You have to help them.}
{183}{}{你抛弃了你的家人，让罗伯特的家人受苦受难。你必须帮助他们。}
#{184}{}{}
{184}{}{}
#{185}{}{Wait, I know, what you need! Wright's not going to see my body anyway, right? How about this: I give you my contract with him and you get off me. You'll show him the contract and tell him you took it off my dead body. He'll never see me again. And I'll even give you my metal detector, I'm sure you can get some cash for it! Can... Can we make a deal?}
{185}{}{等等，我知道，你需要什么！赖特无论如何也不会看到我的身体，对吧？不如这样：我把我和他的合同给你，你就滚开。你要给他看合同，告诉他你从我尸体上拿走了。他再也见不到我了。我甚至会把我的金属探测器给你，我相信你可以拿些现金！我可以。。。我们能做个交易吗？}
#{186}{}{Give me the contract and the metal detector. I'll take care of everything else.}
{186}{}{把合同和金属探测器给我。其他的我都会处理。}
#{187}{}{No. You have to pay your debt to your and Robert's family.}
{187}{}{不，你必须偿还你和罗伯特家人的债务。}
#{188}{}{BUT HOW!? Wright needs a lot of explosives, and I can't get it from Hawthorne by myself.}
{188}{}{但是怎么做！？赖特需要很多炸药，我一个人从霍桑那里拿不到。}
#{189}{}{Then I'll just kill you and tell Wright the job is done. What do you say to that?}
{189}{}{那我就杀了你，告诉赖特任务完成了。你怎么说？}
#{190}{}{I'll get the explosives and complete the contract for you. Trust me.}
{190}{}{我去拿炸药，帮你完成合同。相信我。}
#{193}{}{Really? But... Oh, what choice do I have? Here's the contract. And take this metal detector - it'll get you past the mines in Hawthorne. I'll go to Reno and wait for you. I'm counting on you, okay? Both of our families are depend on that contract.}
{193}{}{真正地？但是。。。哦，我还有什么选择？这是合同。带上这个金属探测器-它能让你通过霍桑的矿井。我去雷诺等你。我全靠你了，好吗？我们两家都依赖那份合同。}
#{194}{}{Stay safe.}
{194}{}{注意安全。}
