#{100}{}{You are going to die.}
{100}{}{你会死的。}
#{101}{}{So, you're the one marked for death.}
{101}{}{所以，你就是那个注定要死的人。}
#{102}{}{You should learn better manners.}
{102}{}{你应该学会更好的礼貌。}
#{103}{}{I am going to bring you back in a body bag.}
{103}{}{我要用尸袋把你带回来。}
#{104}{}{Die, you scum!}
{104}{}{死吧，你这个人渣！}
#{105}{}{Screw this - they can keep the bounty.}
{105}{}{去他妈的-他们可以留着赏金。}
#{106}{}{I'm outta here.}
{106}{}{我要走了。}
#{107}{}{The job isn't worth this.}
{107}{}{这份工作不值得这么做。}
