#{100}{}{You see a cannibal.}
{100}{}{你看到一个食人族。}
#{101}{}{Foood!}
{101}{}{笨蛋！}
#{102}{}{It's meal time!}
{102}{}{吃饭时间到了！}
#{103}{}{Hmmm... White meat.}
{103}{}{六羟甲基三聚氰胺六甲醚。。。白肉。}
#{104}{}{Yum!}
{104}{}{好极了！}
#{105}{}{Tasty!}
{105}{}{美味的！}
#{106}{}{It looks tender.}
{106}{}{它看起来很嫩。}
#{107}{}{::Slurp::}
{107}{}{●咕噜声：}
