#{100}{}{You already searched this machinery.}
{100}{}{你已经搜查过这台机器了。}
#{101}{}{You see nothing useful in this radioactive dust.}
{101}{}{你在这些放射性尘埃中看不到任何有用的东西。}
#{102}{}{You found this in the radioactive dust: }
{102}{}{你在放射性尘埃中发现了这个：}
#{103}{}{. Don't forget to wash hands after this.}
{103}{}{. 之后别忘了洗手。}
#{104}{}{This time you're unlucky, you didn't find anything in this radioactive dust.}
{104}{}{这次你真倒霉，你在放射性尘埃里什么也没发现。}
