#{100}{}{You see mine sweeper robot.}
{100}{}{你看扫雷机器人。}
#{101}{}{This recon robot was programmed to do mine sweeping. You can hardly expect more of it. Looks like the control program contains errors.}
{101}{}{这个侦察机器人被编程用来扫雷。你很难再期待了。看起来控制程序包含错误。}
#{102}{}{You cannot do that while in combat.}
{102}{}{你不能在战斗中那样做。}
#{103}{}{You need to use your head here, not your hands.}
{103}{}{你需要用你的头，而不是你的手。}
#{110}{}{You fail to fix the program's code, which is unsurprising with your skills...}
{110}{}{你无法修复程序的代码，这对你的技能来说并不奇怪。。。}
#{111}{}{To assemble the robot is pretty easy. But to make it work you'll have to fix errors in control program.}
{111}{}{组装机器人很容易。但要使它工作，你必须修复控制程序中的错误。}
