#{100}{}{You see the service computer.}
{100}{}{你看到服务计算机了。}
#{101}{}{You see an ordinary service computer.}
{101}{}{你看到一台普通的服务电脑。}
#{110}{}{System loaded.}
{110}{}{系统已加载。}
#{111}{}{[Sort documents by date]}
{111}{}{[按日期排序文档]}
#{112}{}{[Quit]}
{112}{}{[退出]}
#{113}{}{Done.}
{113}{}{完成。}
#{114}{}{Transcript of the last commission meeting.}
{114}{}{上次委员会会议记录。}
#{115}{}{The commission's resolution on the case of desertions.}
{115}{}{委员会关于遗弃案件的决议。}
#{116}{}{Tests of the new radio signal jamming system.}
{116}{}{新型无线电信号干扰系统的测试。}
#{117}{}{Acceptance act of the "dirty bombs".}
{117}{}{接受“肮脏炸弹”法案。}
#{118}{}{Monitoring data on the Vault 8.}
{118}{}{保险库8的监控数据。}
#{119}{}{Information about the military radio station in Lovelock.}
{119}{}{关于洛夫洛克军事电台的信息。}
#{120}{}{[Back]}
{120}{}{[后退]}
#{121}{}{}
{121}{}{}
#{122}{}{Due to the case of mass desertions, a commission was organized. The commission provided a report, which was handed over to the garrison commander.}
{122}{}{由于大规模逃兵的情况，组织了一个委员会。委员会提供了一份报告，交给了驻军指挥官。}
#{123}{}{The order to test a line of signal jammer of the next generation came through today. Tests are scheduled for October 17, 2077. The beginning of test scheduled at 18:28, the end at 21:02. Location: Hawthorne test site. All units must be fully operational. To the engineering department: prepare the device for testing, conduct an off-schedule inspection of the computer security systems from failures. Transfer the device from the warehouse to the hangar V9 under the receipt of the responsible quartermaster.}
{123}{}{测试下一代信号干扰机的命令今天通过了。测试定于2077年10月17日进行。考试开始时间安排在18:28，结束时间安排在21:02。地点：霍桑试验场。所有单位必须全面运作。工程部：准备设备进行测试，对计算机安全系统进行非计划的故障检查。在责任军需长的接收下，将设备从仓库转移到V9机库。}
#{124}{}{A cargo of 5 containers with a radioactive isotope arrived at the V9 hangar for temporary storage in army warehouses.}
{124}{}{一批装有5个放射性同位素集装箱的货物抵达V9机库，暂时存放在陆军仓库。}
#{125}{}{As it turned out, the military in Hawthorne kept the Vault 8 under constant monitoring. They mostly collected the computer and automated system's data and were engaged in wiretapping communications. Hawthorne was given the responsibility for the security of the Vault in case of the invasion of the enemy's army or natural disasters. The observation object is assigned with a high priority level.}
{125}{}{事实证明，霍桑的军方一直在监视8号金库。他们主要收集计算机和自动化系统的数据，从事窃听通信。霍桑被赋予了金库的安全责任，以防敌军入侵或自然灾害。观察对象被赋予高优先级。}
#{126}{}{The military radio station at Lovelock provided communications and engaged in surveillance on Vault 8.}
{126}{}{洛夫洛克的军事电台提供通信，并对8号金库进行监视。}
#{127}{}{Write down the Lovelock's coordinates.}
{127}{}{写下洛夫洛克的坐标。}
#{128}{}{Hmm. It is where Cheyennes live now. Maybe some of the locals know where this station is located.}
{128}{}{Hmm. It is where Cheyennes live now. Maybe some of the locals know where this station is located.}
#{129}{}{I have been there already.}
{129}{}{我已经去过那里了。}
