#{100}{}{You see a pharmacist.}
{100}{}{你看到一个药剂师。}
#{101}{}{It's a pharmacist, though he may be a doctor... But now he is a pharmacist.}
{101}{}{是个药剂师，虽然他可能是个医生。。。但现在他是个药剂师。}
#{102}{}{It must be an interesting task if you're a doctor or a chemist... But thank you for telling me.}
{102}{}{如果你是医生或化学家，那一定是个有趣的任务。。。但是谢谢你告诉我。}
#{103}{}{Well, it seems the issue has been resolved. It also means that I will have something to do sitting by the campfire in my free time. Goodbye, colleague!}
{103}{}{看来问题已经解决了。这也意味着我将有一些事情做我坐在篝火旁的空闲时间。再见，同事！}
#{104}{}{Thief! Help!}
{104}{}{小偷！救命啊！}
#{105}{}{I wonder, which?}
{105}{}{我想知道，哪个？}
#{110}{}{I'm listening.}
{110}{}{我在听。}
#{111}{}{Show me the goods.}
{111}{}{给我看看货物。}
#{112}{}{Do you need a worker for a modest fee? There is one poor guy that can't find a job.}
{112}{}{你需要一个中等费用的工人吗？有一个可怜的家伙找不到工作。}
#{113}{}{No. I can barely earn for a livelihood. Paying the workers is too much for me... Maybe the Sheriff needs someone. There are always people doing something around him.}
{113}{}{不，我只能勉强维持生计。给工人发工资对我来说太多了。。。也许警长需要人。他身边总有人在做什么。}
#{114}{}{Okay.}
{114}{}{可以。}
#{115}{}{Well, I've helped as much as I could. I have nothing more to offer.}
{115}{}{嗯，我已经尽我所能帮了很多忙。我没有什么可以提供的了。}
#{116}{}{One more time.}
{116}{}{再来一次。}
#{117}{}{Su-u-ure. Goodbye.}
{117}{}{Su-u-ure公司。再见。}
#{118}{}{Goodbye.}
{118}{}{再见。}
#{119}{}{Let's go back.}
{119}{}{我们回去吧。}
#{120}{}{About the healthcare in the city...}
{120}{}{关于城市的医疗保健。。。}
#{121}{}{What do you want to talk about?}
{121}{}{你想谈什么？}
#{122}{}{About the filter for the artesian water tower. I've found it! But how to run the tower? Is there anyone I can discuss this issue with?}
{122}{}{关于自流水塔的过滤器。我找到了！但是如何管理这座塔呢？我可以和谁讨论这个问题吗？}
#{123}{}{Well. with me, of course! Because all people here come to me with a damn dysentery. I would have ensured that the tower is running.}
{123}{}{好。当然是和我一起！因为这里的人都带着痢疾来找我。我会确保塔在运转。}
#{124}{}{And what will you do afterwards? Sell water?}
{124}{}{然后你会怎么做？卖水？}
#{125}{}{If I had my way, I would give it away for free. But, in our circumstances, I will have to act differently. First, it is necessary to pay a considerable amount to the guys who will fix everything and prepare the working area. Then I need to hire guys to protect it. Maybe I can ask the Sheriff for them, we'll see. At least, I wouldn't ask to high a price, unlike the Nuka-Cola factory. For them it is just business.}
{125}{}{如果我有办法，我会免费赠送。但是，在我们的情况下，我必须采取不同的行动。首先，有必要支付相当数量的人谁将修复一切和准备工作区。然后我需要雇人来保护它。也许我可以向警长要，我们拭目以待。至少，我不会要求很高的价格，不像努卡可乐厂。对他们来说，这只是生意。}
#{126}{}{So, the factory is also interested in buying this filter?}
{126}{}{那么，工厂是否也有意购买这种过滤器呢？}
#{127}{}{Well, of course! But mark my words. If the factory becomes the sole owner of clean water, it will be even worse than if there were no clean water at all!}
{127}{}{好吧，当然！但记住我的话。如果工厂成为清洁水的唯一拥有者，那将比没有清洁水更糟糕！}
#{128}{}{Why?}
{128}{}{为什么？}
#{129}{}{The sanitary catastrophe is looming in the city. I can see that. Nobody can be sure that after going to sleep one will wake up the next day. If there is clean water in the city, the people will start gnawing through the throats of each other. There will be serious conflicts.}
{129}{}{卫生灾难正在这个城市逼近。我看得出来。没有人能确定一个人睡觉后第二天会醒来。如果城市里有干净的水，人们就会开始互相咬牙切齿。会有严重的冲突。}
#{130}{}{How complicated. And how much you offer for the filter?}
{130}{}{多复杂啊。你给过滤器多少钱？}
#{131}{}{5 thousands and a 30% discount at my pharmacy for you personally. I can't offer more.}
{131}{}{5千美元，在我的药房为您个人提供30%的折扣。我不能提供更多。}
#{132}{}{It's a deal!}
{132}{}{成交了！}
#{133}{}{After listening to this heartbreaking story, I'll give the filter for free.}
{133}{}{听了这个令人心碎的故事后，我将免费赠送过滤器。}
#{134}{}{I'll think about your offer.}
{134}{}{我会考虑你的提议。}
#{135}{}{Thank you! It's the real salvation of our city!}
{135}{}{谢谢您！这是我们城市的真正救赎！}
#{136}{}{I understand. Goodbye.}
{136}{}{我理解。再见。}
#{137}{}{You delivered the filter for artesian water tower and significantly improved local living conditions.}
{137}{}{你们为自流水塔提供了过滤器，大大改善了当地的生活条件。}
#{138}{}{I visited the artesian water tower in the slums. Has anybody tried to fix it? It would provide a loads of clean water for the city!}
{138}{}{我参观了贫民窟里的自流水塔。有人试过修吗？它将为城市提供大量的清洁水！}
#{139}{}{It would, of course. This tower has been attracting everyone's attention for a long time. Nuka-Cola factory hired some people, the Sheriff tried to find repairers and even sent couriers to search for it in other cities. But all in vain.}
{139}{}{当然会的。这座塔吸引了大家的注意力很久了。努卡可乐厂雇佣了一些人，警长试图找到修理厂，甚至派快递员到其他城市寻找。但都是徒劳。}
#{140}{}{What's the problem?}
{140}{}{有什么问题吗？}
#{141}{}{Overall, the tower is in working condition. Only one thing doesn't work - the cleaning machine. A new filter is needed to fix this. But where one can be found - nobody knows. Things like this are not available in a local store. However, there were rumors that someone in Vegas has found a suitable one. But it's just a story, otherwise it would have been brought here long time ago.}
{141}{}{总体而言，该塔处于工作状态。只有一件事不起作用-清洁机。需要一个新的过滤器来解决这个问题。但是在哪里可以找到-没人知道。像这样的东西在本地商店是买不到的。然而，有传闻说拉斯维加斯有人找到了一个合适的。但这只是一个故事，否则它早就被带到这里了。}
#{142}{}{Hmm, a serious problem. I hope I come across such a filter.}
{142}{}{嗯，一个严重的问题。我希望我遇到这样一个过滤器。}
#{143}{}{Doubtful, but if you often move around the Wasteland, ask around the cities. Better to start from Vegas.}
{143}{}{不确定，但如果你经常在荒地里走动，问问城市里的人。最好从维加斯开始。}
#{144}{}{So, Vegas... I need to make a notch.}
{144}{}{所以，维加斯。。。我需要做一个缺口。}
#{145}{}{You got the Las Vegas coordinates.}
{145}{}{你拿到拉斯维加斯坐标了。}
#{154}{}{How can you live in such a wet and smelly climate? The visitors, perhaps, have breathing problems?}
{154}{}{你怎么能生活在这样又湿又臭的气候里？游客们，也许有呼吸问题？}
#{155}{}{That's right. One need to get used to to local conditions. But the body gradually adapts. Most importantly, do not stick your nose where it doesn't belong.}
{155}{}{这是正确的。一个人需要适应当地的条件。但身体逐渐适应。最重要的是，不要把鼻子伸到不该伸的地方。}
#{156}{}{And where it does not?}
{156}{}{哪里没有呢？}
#{157}{}{In the North there is a large radioactive area, a real cemetery. That was the part of the Salt Lake city agglomeration on which a nuclear bomb was dropped during the war. Periodically rains wash out radioactive dirt, which flows into the Great Salt Lake. Fortunately, we were lucky with the climate.}
{157}{}{在北部有一大片放射性区域，一个真正的墓地。那是盐湖城群的一部分，战争期间曾在那里投下核弹。周期性的降雨会冲走流入大盐湖的放射性污垢。幸运的是，我们在气候方面很幸运。}
#{158}{}{How so?}
{158}{}{怎么会这样？}
#{159}{}{Our landscape holds back any dirt. There are no harsh winds like in the deserts, and no fumes from heat. In addition, in local conditions one plant has mutated, the water lily. It grows on the banks of the Great Salt Lake. In other cities it is just a plant, but this one gives you a special kind of nutritious nuts.}
{159}{}{我们的风景可以阻挡任何灰尘。没有沙漠里那样的狂风，也没有酷热的烟雾。此外，在当地条件下，一种植物发生了变异，睡莲。它生长在大盐湖的岸边。在其他城市，它只是一种植物，但这种植物给你一种特殊的营养坚果。}
#{160}{}{Oh, that's why on the way here I saw people constantly chewing something...}
{160}{}{哦，这就是为什么在来这里的路上我看到人们不停地嚼东西。。。}
#{161}{}{These are Vocas nuts. They are very dense, you have to chew them hard, otherwise the effect will be small.}
{161}{}{这些都是疯子。它们很密，你得用力咀嚼，否则效果会很小。}
#{162}{}{What is the effect, exactly?}
{162}{}{具体效果如何？}
#{163}{}{These nuts remove radioactive elements from the body. Of course, this does not happen immediately. Radiation is excreted with sweat and urine during the day. The effect is not that strong, but if you use Vocas regularly, the degree of irradiation will come back to normal... More or less.}
{163}{}{这些坚果能清除体内的放射性元素。当然，这种情况不会立即发生。辐射在白天通过汗水和尿液排出。效果不是很好，但是如果你经常使用Vocas，辐射的程度会恢复正常。。。或多或少。}
#{164}{}{Apparently, a very useful plant. How to find it?}
{164}{}{显然，这是一种非常有用的植物。如何找到它？}
#{165}{}{You can buy them from me or in the "Tin angel". And if you want to collect them yourself, I suggest you to wander through the uninhabited areas with a lot of dirty water. Vocas grows in rather unpleasant conditions. Just keep in mind that it ripens twice a year - in spring and in fall. At those times of the year there are buckets of them lying on shelves.}
{165}{}{你可以从我这里或者在“锡天使”里买。如果你想自己收集的话，我建议你在有很多脏水的无人区漫步。人声在相当不愉快的环境中成长。只要记住它一年成熟两次——春天和秋天。在一年中的那些时候，架子上放着一桶桶的。}
#{166}{}{Okay. Thank you for telling me.}
{166}{}{可以。谢谢你告诉我。}
#{167}{}{Okay. Maybe you can clarify something on the subject?}
{167}{}{可以。也许你能澄清一下这个问题？}
#{168}{}{I think I know how to solve this problem. Fortunately, my experience of survival in the wild has saved my life during travels between cities.}
{168}{}{我想我知道怎么解决这个问题。幸运的是，我在野外生存的经历在城市之间的旅行中救了我的命。}
#{169}{}{...So, you're saying, we need to extract compounds from nuts and infuse them intravenously, and not orally? Brilliant! Just brilliant!}
{169}{}{……所以，你是说，我们需要从坚果中提取化合物，然后静脉注射，而不是口服？太棒了！太棒了！}
#{170}{}{It seems that the nuts with the radioprotective effect are in widespread here, but people are still suffering. Why is it so?}
{170}{}{看来，具有辐射防护作用的坚果在这里广为传播，但人们仍在受苦。为什么会这样？}
#{171}{}{Vocas has a weak effect, especially compared to pre-war drugs. The benefits will come only when people take them by handfuls and regularly. But even in this case there are limitations.}
{171}{}{Vocas的作用很弱，尤其是与战前的药物相比。只有当人们有规律地把它们一把一把地拿走时，这些好处才会出现。但即使在这种情况下也有局限性。}
#{172}{}{What stops the regular prophylactic?}
{172}{}{什么阻止了常规的预防措施？}
#{173}{}{Well, the nuts ripen only twice a year, so the regularity is difficult to achieve. In addition, the body is not very happy with such a tough food. I noticed recently, that the more often people eat Vocas, the smaller the useful effect of this plant. Organism becomes oversaturated and triggers a natural blocker. It's not a panacea, alas.}
{173}{}{嗯，坚果一年只成熟两次，所以很难做到规律。另外，身体对这样的硬性食物也不是很满意。我最近注意到，人们吃得越多，这种植物的效用就越小。有机体变得过饱和并触发一种天然阻滞剂。唉，这不是万能药。}
#{174}{}{I think I know how to solve this problem. Fortunately, I have plenty of scientific knowledge in chemistry.}
{174}{}{我想我知道怎么解决这个问题。幸运的是，我在化学方面有丰富的科学知识。}
#{175}{}{Are you serious? Oh, I'd love to chat with you over the lab table. And... What do you want to propose, colleague?}
{175}{}{你是认真的吗？哦，我很想和你在实验桌边聊天。还有。。。你有什么建议，同事？}
#{176}{}{My professional secrets are expensive. I will tell you for a reward of $350.}
{176}{}{我的职业秘密很昂贵。我会告诉你350美元的报酬。}
#{177}{}{I'll be very happy to share my knowledge with those who will be able to use it for the benefit of the people.}
{177}{}{我将非常高兴地与那些能够利用我的知识造福人民的人分享我的知识。}
#{178}{}{Sorry, but I can't right now - I have the work to do.}
{178}{}{对不起，我现在不行-我有工作要做。}
#{179}{}{Together with the pharmacist you have developed a drug for the prevention of radiation sickness. This will be very useful for the entire city.}
{179}{}{你和药剂师一起开发了一种预防辐射病的药物。这将对整个城市非常有用。}
#{180}{}{About the sanitary conditions in the city. What are they now, can you tell?}
{180}{}{关于城市的卫生条件。他们现在是什么，你能看出来吗？}
#{181}{}{Now it's calm. The pestilence seems to be over, but it is too early to draw final conclusions. People are less likely to get sick and suffer from intestinal infections. I hope it will continue like this.}
{181}{}{现在很平静。瘟疫似乎已经结束了，但现在下结论还为时过早。人们不太可能生病和遭受肠道感染。我希望它能继续这样下去。}
#{182}{}{Terrible conditions. Pestilence is in the city. People die from intestinal diseases and there is nothing to help them. My supplies are meager, and not everyone can afford to buy them. I don't know for how long will these conditions last.}
{182}{}{恶劣的环境。城里有瘟疫。人们死于肠道疾病，没有什么可以帮助他们。我的货源很少，不是每个人都买得起。我不知道这种情况会持续多久。}
#{183}{}{All as before. There are still pockets of intestinal diseases in the city, but so far very few deaths.}
{183}{}{一切照旧。该市仍有一些肠道疾病，但到目前为止死亡人数很少。}
#{184}{}{What can I tell... Every city of the Wastelands has problems with health. But the people manage to cope somehow, and most of them survive. What's happening In Salt Lake is complicated: on the one hand, nature has given us a lot of water and a wonderful plant Vocas, on the other, we are afraid even to approach the Great Salt Lake because of the danger of intoxication and irradiation. In addition, the Nuka-Cola factory obviously adds it's own share of dirt to the problem. A complicated case.}
{184}{}{我能说什么。。。荒地里的每个城市都有健康问题。但是人们设法应付，他们中的大多数人都活了下来。盐湖发生的事情是复杂的：一方面，大自然给了我们大量的水和美妙的植物，另一方面，我们甚至不敢接近大盐湖，因为有中毒和辐射的危险。此外，努卡可乐厂显然也增加了自己的一部分污垢问题。一个复杂的案子。}
#{185}{}{I have a set of different medicaster's accessories. Interested?}
{185}{}{我有一套不同的医生的配件。有兴趣吗？}
#{186}{}{Actually, I try to stick to civilized medicine. But in our time you will be glad to have any additional means. Let's see, maybe there will be something useful.}
{186}{}{事实上，我试着坚持文明医学。但在我们这个时代，你会很高兴有任何额外的手段。让我想想，也许会有一些有用的东西。}
#{187}{}{Look.}
{187}{}{你看。}
#{188}{}{Yeah, some trinkets can be useful, especially this one and this one. It seems that the medic who used it was quite experienced. I'll give you $1000 for this bag.}
{188}{}{是啊，有些小饰品很有用，尤其是这件和这件。看来使用它的医生很有经验。我给你1000美元买这个包。}
#{189}{}{That's a deal then.}
{189}{}{那就这么定了。}
#{190}{}{I'm going to look for more generous customers. Goodbye.}
{190}{}{我要找更慷慨的顾客。再见。}
#{191}{}{Yeah, some trinkets can be useful, especially this one and this one. It seems that the medic who used it, was quite experienced. But now since the city has not as much problems with diseases as before, I don't have much need in these tools. So I can give you only $500 for this.}
{191}{}{是啊，有些小饰品很有用，尤其是这件和这件。看来使用它的医生很有经验。但是现在由于城市没有以前那么多的疾病问题，我不需要这些工具。所以我只能给你500美元。}
#{192}{}{[Nods and gives you the money, taking the accessories away]}
{192}{}{[点点头，给你钱，拿走配件]}
#{193}{}{I think I know how to solve this problem. Fortunately, I have lots of medical experience.}
{193}{}{我想我知道怎么解决这个问题。幸运的是，我有很多医疗经验。}
#{194}{}{I think I know how to solve this problem. Fortunately, I have plenty of scientific knowledge in chemistry.}
{194}{}{我想我知道怎么解决这个问题。幸运的是，我在化学方面有丰富的科学知识。}
#{195}{}{With pleasure! It's timely, as the goods started stocking up after the city got rid of the problems with diseases. So keep in mind - now, coming to me, you won't see an empty shelf.}
{195}{}{很高兴见到你！这是及时的，因为在城市解决了疾病问题之后，货物开始囤积。所以请记住-现在，来找我，你不会看到一个空架子。}
#{196}{}{It's good... I mean. good for me, of course. Well, let's see what you have.}
{196}{}{很好。。。我是说。当然对我有好处。好吧，让我们看看你有什么。}
#{197}{}{Thanks to the improved ecological situation in the city, the goods in the pharmacy will be updated twice as often now.}
{197}{}{由于城市生态环境的改善，现在药房的商品更新频率将提高一倍。}
#{200}{}{Do you make medicaments?}
{200}{}{你们做药物吗？}
#{201}{}{I can make healing powders, antidotes, stimulants and the "blood-purifier". But I need your own components as mine are scarce. So what do you need?}
{201}{}{我可以做治疗粉，解毒剂，兴奋剂和“血液净化器”。但我需要你自己的零件，因为我的零件很少。你需要什么？}
#{202}{}{Antidote.}
{202}{}{解毒剂。}
#{203}{}{Stimulator.}
{203}{}{刺激器。}
#{204}{}{"Blood-purifier".}
{204}{}{“血液净化器”。}
#{205}{}{Healing powder.}
{205}{}{疗伤粉。}
#{209}{}{Let's change the subject.}
{209}{}{我们换个话题吧。}
#{210}{}{Nothing. Let's go back.}
{210}{}{没有什么。我们回去吧。}
#{211}{}{I'll do if you bring me the tail of a radscorpion. It will cost }
{211}{}{如果你给我一条蝎子的尾巴，我会做的。这要花很多钱}
#{212}{}{I'll do if you bring me an empty Great Salt Lake, a Xander root and a Broc flower. It will cost }
{212}{}{如果你给我带来一个空的大盐湖，一根仙人掌和一朵花椰，我会做的。这要花很多钱}
#{213}{}{I'll do if you bring me a Xander root, a Broc flower and two handfuls of nightshade berries. It will cost }
{213}{}{如果你给我一个香根草，一朵椰子花和两把茄果，我会的。这要花很多钱}
#{214}{}{I'll do if you bring me a Xander root and a Broc flower. It will cost }
{214}{}{如果你给我一根仙人掌和一朵椰子花，我就做。这要花很多钱}
#{218}{}{Again, what can you produce?}
{218}{}{再说一遍，你能生产什么？}
#{219}{}{ bucks a dose.}
{219}{}{一剂多少钱。}
#{220}{}{Make one dose.}
{220}{}{做一剂。}
#{221}{}{Make two doses.}
{221}{}{打两剂。}
#{222}{}{Make three doses.}
{222}{}{打三剂。}
#{223}{}{Make four doses.}
{223}{}{打四剂。}
#{224}{}{Make five doses.}
{224}{}{打五剂。}
#{225}{}{Make ten doses.}
{225}{}{打十剂。}
#{226}{}{Make the as many as possible.}
{226}{}{尽可能多的做。}
#{230}{}{[The pharmacist mockingly shakes his head as he watches at you nervously digging into empty pockets looking for the things that aren't there]}
{230}{}{[药剂师嘲笑地摇摇头，看着你紧张地往空口袋里掏，寻找那些不在那里的东西]}
#{231}{}{Oops...}
{231}{}{哎呀。。。}
#{232}{}{Ready. Anything else?}
{232}{}{准备好了。还有别的吗？}
#{233}{}{Another medicament, please.}
{233}{}{请再来一剂药。}
#{234}{}{Now let's talk, if you don't mind.}
{234}{}{现在我们谈谈，如果你不介意的话。}
#{235}{}{That's all I needed. See you.}
{235}{}{这就是我所需要的。再见。}
#{240}{}{Can you teach me how to do medicine?}
{240}{}{你能教我怎么行医吗？}
#{241}{}{Alas, no. It takes at least a little bit of knowledge about the properties of medicinal herbs of the modern Wasteland.}
{241}{}{唉，不，至少需要一点关于现代荒原中草药特性的知识。}
#{242}{}{A pity. I very much wanted to learn this skill...}
{242}{}{很遗憾。我非常想学这个技能。。。}
#{243}{}{Well, I wouldn't mind extra income. But how would I know what are you going to use your knowledge for? At one moment you may decide to become a competitor or even to produce drugs? And I don't want to have any problems with the Sheriff.}
{243}{}{嗯，我不介意额外的收入。但我怎么知道你要用你的知识做什么呢？在某一时刻，你可能会决定成为竞争对手，甚至生产毒品？我不想和警长有任何问题。}
#{244}{}{Well, I wouldn't mind extra income. For such a good person like you I am ready to trust my knowledge. But I hope to get something in return, okay?}
{244}{}{嗯，我不介意额外的收入。对于像你这样的好人，我愿意相信我的知识。但我希望能得到回报，好吗？}
#{245}{}{I'll pay $ 1,000 for tuition.}
{245}{}{我要付1000美元的学费。}
#{246}{}{We will decide on that question another time.}
{246}{}{我们下次再决定那个问题。}
#{247}{}{Since you have returned clean water to the city, I will help you with pleasure.}
{247}{}{既然你把干净的水还给了城市，我就乐意帮助你。}
#{248}{}{Great. Shall we?}
{248}{}{伟大的。让我们？}
#{249}{}{Not now, I have other things to do.}
{249}{}{现在不行，我还有别的事要做。}
#{250}{}{Hey, that's my stuff!}
{250}{}{嘿，那是我的东西！}
#{251}{}{But I acquired these things in an honest way. Therefore, if you want to take this you have to pay for it.}
{251}{}{但我是以诚实的方式得到这些东西的。因此，如果你想拿这个，你必须付钱。}
#{252}{}{Grr...}
{252}{}{Grr。。。}
#{260}{}{Thanks! Our city is saved now. But I can't let you go without a little reward. Here you go. [gives you a superstimpak and an ultra-antidote] These are very expensive medicaments. I could sell them to the rich, but you may need them more.}
{260}{}{谢谢！我们的城市现在得救了。但我不能不给你一点奖励就让你走。干得好。[给你一个超级兴奋剂和超级解毒剂]这些是非常昂贵的药物。我可以把它们卖给富人，但你可能更需要它们。}
#{261}{}{I won't refuse.}
{261}{}{我不会拒绝的。}
#{262}{}{Do you have heart disease medicine in stock?}
{262}{}{你们有心脏病药的存货吗？}
#{263}{}{Unfortunately, I don't. And I would not advise you to resort to such medicine. Who knows what side effects they might acquire in the years after the great War. You need to look for them in larger and cleaner cities such as Las Vegas.}
{263}{}{不幸的是，我没有。我也不建议你服用这种药。谁知道他们在大战后的几年里会有什么副作用。你需要在更大更干净的城市，比如拉斯维加斯，寻找它们。}
#{264}{}{Understood.}
{264}{}{理解。}
#{265}{}{I feel feverish and the cough is killing me... Is there any cure for such disease?}
{265}{}{我觉得发烧咳嗽得要命。。。这种病有什么治疗方法吗？}
#{266}{}{Let me examine you... This is the infectious disease. It can be handled quite well with nightshade berries mixed with alcohol. But that treatment is still much less effective than the properly made medicine based on the same berries. You can buy the latter from me, it's called "Blood-purifier"... If it's still available.}
{266}{}{让我检查一下你。。。这就是传染病。它可以很好地处理与酒精混合茄浆果。但是这种治疗方法仍然比用同样的浆果制成的药物效果差得多。你可以从我这里买后者，它叫“血液净化器”。。。如果还可以的话。}
#{267}{}{So let's see if you have something effective available for sale.}
{267}{}{所以让我们看看你们有没有什么有效的东西可以卖。}
#{268}{}{Oh, thanks for the tip! When I will set up a camp in the Wasteland and feel sick, there will be a chance to get cured on the spot, near the campfire.}
{268}{}{哦，谢谢你的小费！当我在荒地安营扎寨，感到不舒服时，就有机会在营火附近就地治愈。}
#{269}{}{Pharmacist taught you to treat the infection at the campfire with wild plants and alcohol.}
{269}{}{药剂师教你用野生植物和酒精治疗营火上的感染。}
#{270}{}{I need healing.}
{270}{}{我需要治疗。}
#{271}{}{Sure. But you will have to pay.}
{271}{}{当然。但你得付钱。}
#{272}{}{[The full treatment: }
{272}{}{[全面治疗：}
#{273}{}{[Treat wounds: }
{273}{}{[治疗伤口：}
#{274}{}{[Treat intoxication: }
{274}{}{[治疗中毒：}
#{275}{}{[Cure a mutilation: }
{275}{}{[治疗致残：}
#{276}{}{[Treat irradiation: }
{276}{}{[处理辐照：}
#{277}{}{That's enough for today. Let's talk.}
{277}{}{今天就够了。我们谈谈。}
#{278}{}{Goodbye, Doc.}
{278}{}{再见，医生。}
#{279}{}{$]}
{279}{}{$]}
#{280}{}{Those money won't be enough to recoup the costs of the treatment.}
{280}{}{这些钱不足以补偿治疗费用。}
#{281}{}{Now everything is alright.}
{281}{}{现在一切都好了。}
#{282}{}{Thanks, Doc. I'll better go.}
{282}{}{谢谢，医生。我还是走吧。}
#{283}{}{[Treat the infection: }
{283}{}{[治疗感染：}
#{290}{}{I'm doing some work for the Cola factory. And I was told not to discuss it with you. Why so?}
{290}{}{我在可乐厂工作。我被告知不要和你讨论。为什么会这样？}
#{291}{}{[Smiles sadly] I and various other activists had conflicts with the management of the factory in the past. Simply because the liquid wastes of the factory make the situation with already ruined nature in the city even more perilous. This issue affects all residents of the Salt Lake.}
{291}{}{[悲伤地微笑]我和其他一些积极分子过去曾与工厂的管理层发生过冲突。仅仅是因为工厂的液体废物使城市中已被破坏的自然环境更加危险。这个问题影响到盐湖城的所有居民。}
#{292}{}{So that's what happening...}
{292}{}{所以这就是发生的事。。。}
#{293}{}{So what kind of work you do for the factory?}
{293}{}{你为工厂做什么工作？}
#{294}{}{I got the contract to restore the controller that allows to use automatic equipment.}
{294}{}{我得到了恢复控制器的合同，允许使用自动设备。}
#{295}{}{I can't say. Goodbye.}
{295}{}{我不能说。再见。}
#{296}{}{Oh my God! I hope you are not going to carry out the contract?}
{296}{}{哦，我的上帝！我希望你不履行合同？}
#{297}{}{Why?}
{297}{}{为什么？}
#{298}{}{If the factory restores the automation, it will be bad for everyone, except a handful of the lead managers of this company! Now there is a lot being done manually. But if the conveyors start to work without human involvement, a lot of the workers will be kicked out to the street. In addition, it'll greatly increase the speed of operation of the factory, which will lead to the factory polluting the city with their wastes much more.}
{298}{}{如果工厂恢复自动化，那对每个人都不好，除了这家公司的少数主要经理！现在有很多工作是手工完成的。但如果输送机在没有人参与的情况下开始工作，许多工人将被踢到街上。此外，这将大大提高工厂的运行速度，这将导致工厂的废物污染城市更多。}
#{299}{}{Hmm. What a strange irony - it's bad for the city without the factory, and isn't good with it either. So, what are you proposing?}
{299}{}{嗯。真是奇怪的讽刺——没有工厂对城市不好，也不好用。那么，你有什么建议？}
#{300}{}{Give me that controller, I will destroy it. And in return I'll pay 350 bucks, I can offer no more. But you will do a good deed! And as for the factory, it won't make the situation WORSE for them.}
{300}{}{把控制器给我，我会毁了它。作为回报，我将支付350美元，我不能提供更多。但你会做好事的！至于工厂，这不会让情况变得更糟。}
#{301}{}{Okay then, take this device. Even if it's less money, I will save on the associated costs and would feel better doing good.}
{301}{}{好吧，拿着这个装置。即使它的钱少，我会节省相关费用，并会觉得做好事更好。}
#{302}{}{Give me time to think about it.}
{302}{}{给我时间想想。}
#{303}{}{Few will sacrifice potential earnings for the well being of the alien city. Thanks.}
{303}{}{很少有人会为了这个陌生城市的幸福而牺牲潜在的收入。谢谢。}
#{304}{}{You're welcome.}
{304}{}{不客气。}
#{1122}{}{About the filter for the artesian water tower. I've found it! But how to run the tower? Is there anyone I can discuss this issue with?}
{1122}{}{关于自流水塔的过滤器。我找到了！但是如何管理这座塔呢？我可以和谁讨论这个问题吗？}
#{1138}{}{I visited the artesian water tower in the slums. Has anybody tried to fix it? It would provide a loads of clean water for the city!}
{1138}{}{我参观了贫民窟里的自流水塔。有人试过修吗？它将为城市提供大量的清洁水！}
#{1160}{}{Oh, that's why on the way here I saw people constantly chewing something...}
{1160}{}{哦，这就是为什么在来这里的路上我看到人们不停地嚼东西。。。}
#{1177}{}{I'll be very happy to share my knowledge with those who will be able to use it for the benefit of the people.}
{1177}{}{我将非常高兴地与那些能够利用我的知识造福人民的人分享我的知识。}
