#{100}{}{You see a labourer.}
{100}{}{你看到一个工人。}
#{101}{}{You see a dodgy kid. As you continue looking him over, he narrows his eyes and looks back at you.}
{101}{}{你看到一个狡猾的孩子。当你继续看着他时，他眯起眼睛回头看你。}
#{102}{}{Leave me alone!}
{102}{}{别管我！}
#{103}{}{Shush!! Wait until I'm back...}
{103}{}{嘘！！等我回来。。。}
#{104}{}{ }
{104}{}{ }
#{105}{}{Well, time to get outta here!}
{105}{}{是时候离开这里了！}
#{120}{}{What do you need?}
{120}{}{你需要什么？}
#{121}{}{Tell me who you are and what you do here.}
{121}{}{告诉我你是谁，你在这里做什么。}
#{122}{}{Just looking for someone to talk to. How do you live in this city?}
{122}{}{只是想找个人谈谈。你在这个城市怎么生活？}
#{123}{}{Hey, do you know what's the problem with Gilmore? And what this Provo is?}
{123}{}{嘿，你知道吉尔摩有什么问题吗？这个普罗沃是什么？}
#{124}{}{}
{124}{}{}
#{125}{}{I think I confused you with someone else. I'll be going now.}
{125}{}{我想我把你和别人搞混了。我要走了。}
#{136}{}{Ah... You'll like it here then. We've had problems before, but now the city's beginning to get back to its feet. People are getting richer... [winks] So I would suggest sticking around a little.}
{136}{}{啊。。。你会喜欢这里的。我们以前也遇到过问题，但现在这个城市开始恢复元气了。人们越来越富有。。。[眨眼]所以我建议你多呆一会儿。}
#{137}{}{Ah... Well I'd get outta here if I were you. To Vegas maybe. To be honest, things here are shit. The only reason I'm still here is because I can't stand the wastes even more.}
{137}{}{啊。。。如果我是你，我就离开这里。去拉斯维加斯吧。老实说，这里的事情都是狗屎。我留在这里的唯一原因是我再也受不了浪费了。}
#{138}{}{Ah... Just a city, I guess. Nothing special. People are just living here, that's all. Still better than in Reno, that's for sure. I ran away from there, and think I've made the right choice.}
{138}{}{啊。。。我想只是一个城市。没什么特别的。人们只是住在这里，仅此而已。肯定还是比里诺好。我从那里逃跑了，我认为我做了正确的选择。}
#{139}{}{Alright, forget it.}
{139}{}{好吧，算了吧。}
#{140}{}{Well, everyone calls me Incorrigible Ned. Don't ask me why. I'm just a worker, like many others. Help people out with their junk, earning the odd dime here and there. Although there are times when I do rather... "profitable" jobs... [winks] Either way, I'm not complaining.}
{140}{}{好吧，大家都叫我无可救药的内德。别问我为什么。我只是个工人，和其他许多人一样。帮助人们解决他们的垃圾，赚取零碎的一角钱在这里和那里。虽然有时我宁愿……”有利可图的工作。。。不管怎样，我不是在抱怨。}
#{141}{}{Provo's a shithole that nobody in their right mind should visit. That's where all the exiles that the sheriff booted out of town live. Most of the people here will tell you they're all criminals, but it's more than that. I hear that they helped Burton sort things out during the civil war. And then he showed them the door, when they were no longer needed. Now they don't show their faces in Salt Lake, but I wouldn't put it past them to hold a grudge against the whole world. And Gilmore's just a bastard. Murderer, rapist and thief. Whip wants to send people after him, but I think he's scared that they'll get iced on the way there.}
{141}{}{普罗沃是个没人会去的鬼地方。那是所有被警长赶出城的流放者居住的地方。这里的大多数人都会告诉你他们都是罪犯，但不止这些。我听说他们在内战期间帮助伯顿解决了问题。当他们不再需要的时候，他给他们看了门。现在他们不在盐湖城露面，但我不会让他们对全世界怀恨在心。吉尔摩只是个混蛋。杀人犯，强奸犯和小偷。维普想派人去追他，但我想他害怕他们在去那里的路上会被冻住。}
#{142}{}{Well, everyone calls me Incorrigible Ned. Don't ask me why. If you want to know, I'm looking for... "enterprising" individuals for some easy work. Hm, you don't quite look the type.}
{142}{}{好吧，大家都叫我无可救药的内德。别问我为什么。如果你想知道，我在找……”有进取心的“个人”为一些简单的工作。嗯，你看起来不太像那种人。}
#{143}{}{Well, everyone calls me Incorrigible Ned. Don't ask me why. If you want to know, I'm looking for... "enterprising" individuals for some easy work. Don't think you need it though - you got yourself a good place in this city already.}
{143}{}{好吧，大家都叫我无可救药的内德。别问我为什么。如果你想知道，我在找……”有进取心的“个人”为一些简单的工作。不过，别以为你需要它——你已经在这个城市找到了一个好地方。}
#{149}{}{Hold on! You know, you look like quite the sly bastard. You know what I'm talking about? [winks]}
{149}{}{坚持住！你知道，你看起来像个狡猾的混蛋。你知道我在说什么吗？[眨眼]}
#{150}{}{[Open your eyes in surprise] I have no idea what you're talking about!}
{150}{}{我不知道你在说什么！}
#{151}{}{Oh, so you noticed my hidden talents. Then we could find a... Common interest, don't you think?}
{151}{}{哦，所以你注意到我隐藏的天赋了。然后我们就能找到。。。共同利益，你不觉得吗？}
#{152}{}{Err, you know what, I don't like what you're implying. I think I'm just going to go now...}
{152}{}{呃，你知道吗，我不喜欢你的意思。我想我现在就要走了。。。}
#{153}{}{Okay, no problem. Forget I said anything.}
{153}{}{好的，没问题。忘了我说过什么。}
#{154}{}{Wait, *what* did you want to say?}
{154}{}{等等，你想说什么？}
#{155}{}{Much better.}
{155}{}{好多了。}
#{156}{}{}
{156}{}{}
#{157}{}{Is that so? What about this? [pulls a coin out of your pocket that you're seeing for the first time in your life] I saw you! You just tried to pickpocket me!}
{157}{}{是这样吗？这个怎么样？我看见你了！你刚才想扒窃我！}
#{158}{}{What the... This is a fucking setup!}
{158}{}{怎么了。。。这是他妈的圈套！}
#{159}{}{Shit, you got me man. Yeah, I'm a thief. Question is, what do we do now?}
{159}{}{妈的，你抓住我了。是啊，我是小偷。问题是，我们现在该怎么办？}
#{160}{}{Yeah, yeah. I get it. But you know... I don't blame you.}
{160}{}{是的，是的。我明白了。但是你知道。。。我不怪你。}
#{161}{}{Oh, how honest! But you know... I don't blame you.}
{161}{}{哦，多诚实啊！但是你知道。。。我不怪你。}
#{162}{}{What, seriously?}
{162}{}{什么，说真的？}
#{163}{}{Fucking swindler! Get out of my way!}
{163}{}{他妈的骗子！让开！}
#{164}{}{You see, I'm also... Opportunistic, like you. [winks again]}
{164}{}{你看，我也。。。机会主义的，像你一样。[再次眨眼]}
#{165}{}{Well... Perhaps.}
{165}{}{好。。。也许。}
#{166}{}{Of course, I think we could easily find a common interest.}
{166}{}{当然，我认为我们很容易找到共同的兴趣。}
#{167}{}{Great.}
{167}{}{伟大的。}
#{168}{}{I knew it! We're masters of the same art. And, speaking of art... Anything on your mind?}
{168}{}{我就知道！我们是同一种艺术的大师。说到艺术。。。你有什么想法吗？}
#{169}{}{No-no, forget it! I quit and all that. Bye.}
{169}{}{不，不，算了吧！我辞职了。再见。}
#{170}{}{Hmm, I'm interested. Tell me more.}
{170}{}{嗯，我很感兴趣。告诉我更多。}
#{171}{}{[Without a word, he nods at the building across the street]}
{171}{}{[一言不发，他朝街对面的大楼点了点头]}
#{172}{}{You're crazy!}
{172}{}{你疯了！}
#{173}{}{Good choice!}
{173}{}{不错的选择！}
#{174}{}{There's an inner yard. I wonder why the traders piled it with junk? I think it's to stop thieves from getting in. What do you think... Could a *thief* get in?}
{174}{}{里面有个院子。我想知道为什么商人们把它和垃圾堆在一起？我想这是为了防止小偷进来。你怎么认为。。。小偷能进来吗？}
#{175}{}{Hm. What's the catch?}
{175}{}{嗯。有什么问题吗？}
#{176}{}{Maybe... I don't know.}
{176}{}{也许 吧。。。我不知道。}
#{177}{}{Straight to the point? I like it. Let me explain everything.}
{177}{}{直截了当？我喜欢。我来解释一下。}
#{178}{}{Of course.}
{178}{}{当然。}
#{179}{}{Hmph... You newbies always need the basics explained. I'll try and make it quick.}
{179}{}{嗯。。。你们这些新手总是需要一些基本的解释。我会尽快的。}
#{180}{}{Who're you calling a newbie? Although... I'd better hear you out.}
{180}{}{你说谁是新手？尽管。。。我最好听你说完。}
#{181}{}{First of all, getting inside alone will be very hard, we'll need to get in over the fence and then drag stuff across the other side. That means we need another person to support and keep a lookout.}
{181}{}{首先，一个人进去会很困难，我们需要越过栅栏进去，然后把东西拖到另一边。这意味着我们需要另一个人来支持和监视。}
#{182}{}{Right. And secondly?}
{182}{}{正确的。其次呢？}
#{183}{}{The road across is always patrolled by a damn cop. We'll need to figure out when we're out of his sight. That's why two people are needed.}
{183}{}{对面的路总是有个该死的警察在巡逻。我们得弄清楚什么时候才能离开他的视线。所以需要两个人。}
#{184}{}{Got it...}
{184}{}{知道了。。。}
#{185}{}{There's another problem. We'll need to act at night, but the street is lit up by the lamps. A huge risk, if you include the cop. Something should be done about that.}
{185}{}{还有一个问题。我们需要在晚上行动，但是街上的灯亮了。如果你把警察也包括在内，那是一个巨大的风险。对此应该采取措施。}
#{186}{}{What do I need to do?}
{186}{}{我需要做什么？}
#{187}{}{Try and do something about that street-light. Meanwhile, I'll keep an eye out on the situation and work out the finer details of the plan.}
{187}{}{试着对路灯做点什么。同时，我会密切关注形势，制定出更为详细的计划。}
#{188}{}{I like the way you're thinking! I'm with you!}
{188}{}{我喜欢你的思维方式！我支持你！}
#{189}{}{Great. See you in the evening.}
{189}{}{伟大的。晚上见。}
#{190}{}{Bye.}
{190}{}{再见。}
#{191}{}{Shh! There's still to many people in the streets. Too dangerous.}
{191}{}{嘘！街上还有很多人。太危险了。}
#{192}{}{Alright, I'll come later.}
{192}{}{好的，我晚点再来。}
#{193}{}{Looks like a good time to make our move. What do you think?}
{193}{}{看来是我们行动的好时机。你怎么认为？}
#{194}{}{I'm ready! Let's show these fat cats what's what!}
{194}{}{我准备好了！让我们给这些肥猫看什么是什么！}
#{195}{}{Not yet, we should wait a bit longer.}
{195}{}{还没有，我们应该再等一会儿。}
#{196}{}{You decided to take the thieving job. Your first objective - get to the trading center courtyard.}
{196}{}{你决定去偷东西。你的第一个目标是去交易中心。}
#{197}{}{Hold on, I wanna grab a smoke.}
{197}{}{等等，我想抽根烟。}
#{198}{}{You arrived to the potential thieving spot.}
{198}{}{你到达了潜在的盗窃地点。}
#{200}{}{Slow down. Act like you're coming home after work.}
{200}{}{慢下来。假装你下班后要回家。}
#{201}{}{Relax, the cops feel it when you're tense.}
{201}{}{别紧张，你紧张的时候警察会感觉到的。}
#{202}{}{Just watch the road, partner}
{202}{}{小心路，伙计}
#{205}{}{What a coincidence, the traders got geeked just when we decided to... You know.}
{205}{}{太巧了，就在我们决定。。。你知道的。}
#{206}{}{Err... I have no idea! Must be a coincidence.}
{206}{}{呃。。。我不知道！一定是巧合。}
#{207}{}{I thought it'd be easier if they weren't around.}
{207}{}{我想如果他们不在的话会容易些。}
#{208}{}{What the hell is wrong with you!? Oh god! We're doomed now. I want nothing to do with you anymore. That's it [crosses arms across chest] - I don't know you.}
{208}{}{你到底怎么了！？哦，上帝！我们现在注定要失败。我不想再和你有任何关系了。就这样[双臂交叉胸前]-我不认识你。}
#{209}{}{You're acting like you ever did. Now, out of my way, loser.}
{209}{}{你表现得跟以前一样。别挡我的路，失败者。}
#{210}{}{Ah shit! Where's that asshole!!!}
{210}{}{啊，妈的！那个混蛋在哪！！！}
#{211}{}{If he doesn't come out...}
{211}{}{如果他不出来。。。}
#{212}{}{Come on! Come out already!}
{212}{}{加油！快出来！}
#{213}{}{What is this - a setup?}
{213}{}{这是什么-设置？}
#{214}{}{Argh! Where's that fucker!?}
{214}{}{啊！那个混蛋在哪！？}
#{215}{}{Is this a setup?}
{215}{}{这是个圈套吗？}
#{216}{}{Well, shit!}
{216}{}{好吧，妈的！}
#{217}{}{Where'd he go?!}
{217}{}{他去哪了？！}
#{218}{}{I knew I couldn't trust him!}
{218}{}{我知道我不能相信他！}
#{219}{}{Hey you! I don't wanna go to prison!}
{219}{}{嘿，你！我不想进监狱！}
#{220}{}{Stop wasting time! I need you to boost me over the fence. Got it?}
{220}{}{别再浪费时间了！我需要你帮我翻过篱笆。知道了？}
#{221}{}{Let's go.}
{221}{}{走吧。}
#{222}{}{Not yet, we could be seen.}
{222}{}{还没有，我们可以被看见。}
#{223}{}{Okay. Wait for me. I'll be back.}
{223}{}{可以。等等我。我会回来的。}
#{230}{}{Let me know when we can go, okay?}
{230}{}{我们可以走的时候告诉我，好吗？}
#{300}{}{It's done. Help me outta here!}
{300}{}{完成了。帮我离开这里！}
#{301}{}{Are you sure? What if I just leave you here?}
{301}{}{你确定？如果我把你留在这里怎么办？}
#{302}{}{Of course, let's book it.}
{302}{}{当然，我们来订吧。}
#{303}{}{No, hold on, too dangerous.}
{303}{}{不，等等，太危险了。}
#{304}{}{You're bluffing! Don't forget that I have all the loot. Leave me here and you're getting *nothing!*}
{304}{}{你在虚张声势！别忘了我有所有的战利品。把我留在这里，你什么也得不到！*}
#{305}{}{You're right, let's get out of here.}
{305}{}{你说得对，我们离开这里。}
#{306}{}{And yet I'm going now...}
{306}{}{但我现在要走了。。。}
#{307}{}{Ughh... Alright, hold on. What do you want?}
{307}{}{呃。。。好的，等一下。你想要什么？}
#{308}{}{I want 75%.}
{308}{}{我要75%。}
#{309}{}{What!? Pfft! Fuck right off! I'll get out without your help! You won't even have time to call anyone and I'll be gone!}
{309}{}{什么！？Pfft！滚开！没有你的帮助我就出去！你甚至没有时间给任何人打电话，我就走了！}
#{310}{}{Right. We'll see about that.}
{310}{}{正确的。我们拭目以待。}
#{311}{}{You know, I think I feel pity for you. Let's get out of here.}
{311}{}{你知道，我觉得我很同情你。我们从这里出去吧。}
#{312}{}{Ugh you... Want to skin me and keep your hands clean? Shit, you can choke on your extra cut, just help me out!}
{312}{}{呃你。。。想帮我剥皮，保持双手清洁吗？妈的，你可以掐死你多余的伤口，帮帮我！}
#{313}{}{That's much better. Let's go.}
{313}{}{那好多了。走吧。}
#{314}{}{You'll have to wait. It's dangerous.}
{314}{}{你得等等。这很危险。}
#{315}{}{I'm leaving anyway. Bye.}
{315}{}{反正我要走了。再见。}
#{316}{}{Yeah, well fuck off! I can handle myself without your punk-ass!}
{316}{}{好吧，滚开！没有你的小混混我也能应付！}
#{317}{}{We'll see...}
{317}{}{我们拭目以待。。。}
#{320}{}{Phew! I thought I was gonna get caught there. What about you? Nothing happened? Great. Shit, I think it's about time to finish with this business... Alright, let's share this stuff and go our ways. Now, the money, your share - }
{320}{}{呸！我以为我会在那里被抓住。你呢？什么都没发生？伟大的。妈的，我想是时候结束这件事了。。。好吧，让我们分享这些东西，各奔东西。现在，钱，你的那份-}
#{321}{}{ percent. What about the goods?}
{321}{}{百分比。货物呢？}
#{322}{}{Let's see what Lady Fortune gave us.}
{322}{}{让我们看看命运女神给了我们什么。}
#{323}{}{You pulled off a grand heist in the middle of the city.}
{323}{}{你在市中心搞了一场大抢劫。}
#{324}{}{Good, I agree. I doubt the traders will figure out they've been hit any time soon. Although I'd suggest laying low anyway. Oh yes - we don't know each other and were in different places this evening. Got it?}
{324}{}{很好，我同意。我怀疑交易者很快就会发现他们被击中了。尽管我还是建议你低调点。哦，是的，我们不认识，今晚在不同的地方。知道了？}
#{325}{}{Got it. Take care, partner.}
{325}{}{知道了。保重，伙计。}
#{330}{}{Oh my god!}
{330}{}{哦，我的上帝！}
#{331}{}{O-o!!!}
{331}{}{哦哦！！！}
#{332}{}{And all this! For me!}
{332}{}{还有这一切！为了我！}
#{333}{}{Heh-heh-heh!}
{333}{}{嘿嘿！}
#{334}{}{Fucking tight-asses!}
{334}{}{他妈的混蛋！}
#{335}{}{Learn to share!}
{335}{}{学会分享！}
#{336}{}{What was yours is now ours}
{336}{}{以前是你的现在是我们的了}
#{337}{}{So much stuff!}
{337}{}{太多东西了！}
#{338}{}{Mhmm!}
{338}{}{嗯！}
#{339}{}{Well-well! What have we here!?}
{339}{}{好吧，好吧！我们这里有什么！？}
#{340}{}{Right... Don't need this... That's not it...}
{340}{}{正确的。。。不需要这个。。。不是这样的。。。}
#{350}{}{You failed the grand heist!}
{350}{}{你抢劫失败了！}
#{351}{}{Well-well, back to the old stuff?}
{351}{}{好吧，回到过去？}
#{352}{}{Err, whoops chief! Sorry we didn't invite you...}
{352}{}{呃，头儿！抱歉，我们没有邀请你。。。}
#{353}{}{You can apologize to the sheriff.}
{353}{}{你可以向警长道歉。}
#{354}{}{Why did I decide to do this!?}
{354}{}{我为什么要这么做！？}
#{360}{}{Show me what you got.}
{360}{}{给我看看你有什么。}
#{361}{}{[Continue]}
{361}{}{[继续]}
#{362}{}{WHAT!? Don't you think it's a bit much? What happened to percentages?! Right, hand it over! Now! I didn't risk my ass for nothing...}
{362}{}{什么！？你不觉得有点多吗？百分比怎么了？！好的，交出来！现在！我没有白白冒这个险。。。}
#{363}{}{[Continue]}
{363}{}{[继续]}
#{364}{}{Yeah, this seems fair to me. I can live with this.}
{364}{}{是啊，这对我来说很公平。我能忍受。}
#{365}{}{Then it is decided. Pleasure working with you.}
{365}{}{然后就决定了。很高兴和你一起工作。}
#{366}{}{No, hold on, I need to think this through.}
{366}{}{不，等等，我得好好想想。}
#{367}{}{Take it all. I don't need any of that junk.}
{367}{}{全部接受。我不需要那些垃圾。}
#{400}{}{[You see your old acquaintance, he's barely standing thanks to so much drink] He-e-e-e-y! Partner! Sit down!}
{400}{}{[你看你的老朋友，喝了这么多酒，他几乎站不住了]他，他，他，他！搭档！坐下来！}
#{401}{}{[Join him]}
{401}{}{[加入他]}
#{402}{}{Well, partner? WE DID IT! You hear me!? WE DID IT, ha-ha!}
{402}{}{好吧，搭档？我们做到了！你听见了吗！？我们做到了，哈哈！}
#{403}{}{Yeah, I hear you. Do you want everyone else to hear you too?}
{403}{}{是的，我听到了。你想让其他人也听到吗？}
#{404}{}{Uh-huh. And I see you already managed to blow half of your share.}
{404}{}{啊哈。我看你已经把一半的钱都花光了。}
#{405}{}{Now what?}
{405}{}{现在怎么办？}
#{406}{}{Big deal. Take care, partner.}
{406}{}{了不起的事。保重，伙计。}
#{407}{}{[He's still a little drunk] Ah, partner. Hey, everyone, this is my partner! We did such THINGS together!}
{407}{}{[他还是有点醉]啊，伙计。嘿，各位，这是我的搭档！我们一起干的！}
#{408}{}{You want everyone to hear?}
{408}{}{你想让每个人都听到吗？}
#{409}{}{Chill, everything's fine! [moves his fingers across his lips] Silent as a grave. Tee-hee.}
{409}{}{冷静点，一切都好！[手指拂过嘴唇]安静得像坟墓。泰姬。}
#{410}{}{I see you managed to blow everything here...}
{410}{}{我看到你把这里的一切都搞砸了。。。}
#{411}{}{What are you planning to do now?}
{411}{}{你现在打算做什么？}
#{412}{}{Well, take care.}
{412}{}{好吧，保重。}
#{413}{}{Who, me? Not a chance! Unlike someone, I chose the smart option. I stashed mine away for a rainy day. This? Just a little change to calm the nerves. Heh-heh...}
{413}{}{谁，我？一点机会也没有！与其他人不同，我选择了明智的选择。我把我的藏起来以备不时之需。这个？只是一个小小的改变来安抚神经。嘿嘿。。。}
#{414}{}{Stash? You sure nobody will find it?}
{414}{}{藏起来？你确定没人会找到吗？}
#{415}{}{[Makes a stoically calm face and moves his hand] NOBODY!}
{415}{}{[做一张冷静的脸，移动他的手]没人！}
#{416}{}{Ah, sounds like the right thing to do. What're you gonna do now?}
{416}{}{啊，听起来是对的。你现在打算怎么办？}
#{417}{}{[Wipes droplets of beer from his chin] Err... You see, it's not safe in the city. They could... You know? [winks] Hickok's quite the scumbag. He'll shake everyone up if he needs to. So, I don't even know, I'll lie low for a while - the money should make me last. I'll figure things out later. Not to mention I've always had a good income from the glassware "business". Get me? [winks]}
{417}{}{[擦去下巴上的啤酒滴]呃。。。你看，城里不安全。他们可以。。。你知道的？[眨眼]希科克真是个混蛋。如果需要的话，他会把每个人都摇醒的。所以，我甚至不知道，我会低调一段时间-钱应该让我最后。我待会再想办法。更不用说我在玻璃器皿“生意”上一直有不错的收入。明白吗？[眨眼]}
#{418}{}{Glassware?! Are you serious?!}
{418}{}{玻璃器皿？！你是认真的吗？！}
#{419}{}{Well, I'm not interested. Tell someone else, I'm out.}
{419}{}{嗯，我不感兴趣。告诉别人，我出去了。}
#{420}{}{Hell yeah!}
{420}{}{见鬼，耶！}
#{421}{}{Bullshit! You? Glassware?! How?}
{421}{}{瞎扯！你呢？玻璃器皿？！怎么用？}
#{422}{}{How? Ah, you know, there's many ways. For example, walk up to a Nuka-Cola vending machine...}
{422}{}{怎样？啊，你知道，有很多方法。例如，走到Nuka可乐自动售货机前。。。}
#{423}{}{Err... Why the vending machine? I don't think I get you...}
{423}{}{呃。。。为什么是自动售货机？我想我不明白你。。。}
#{424}{}{No-no, listen here! Nobody else will teach you!}
{424}{}{不不，听着！没有人会教你！}
#{425}{}{Uh, sorry. Keep talking, I'm interested.}
{425}{}{呃，对不起。继续说，我很感兴趣。}
#{426}{}{So, you go, all quiet-like. Almost like you're hungover so nobody suspects a thing. Then, just reach into you pocket and... Pull out this... Err... Round thing and stick it into the slot.}
{426}{}{所以，你走吧，安静的样子。就像你宿醉一样没人会怀疑什么。然后，把手伸进口袋。。。把这个拿出来。。。呃。。。把东西包起来，插进槽里。}
#{427}{}{Don't you put coins there...}
{427}{}{不要把硬币放在那里。。。}
#{428}{}{Yeah! That's the thing! Instead of a coin... [looks around, making sure nobody's listening] take the metal thing, stick it into the machine and, voila! A free bottle just for you!}
{428}{}{是 啊！就是这样！而不是硬币。。。[环顾四周，确保没有人在听]把金属的东西，插进机器里，瞧！给你一瓶免费的！}
#{429}{}{Sneaky! Where can I get these "things"?.}
{429}{}{鬼鬼祟祟的！我在哪能买到这些“东西”？。}
#{430}{}{Well, that's your problem. I already used most of mine. Actually, any tech whose hands aren't growing from his ass can stamp out a thousand for you. Unless he figures out what they're for. Although... There's another method.}
{430}{}{那是你的问题。我已经用了我的大部分了。事实上，任何一个手不是从屁股上长出来的技术人员都可以为你消灭一千个。除非他知道它们是用来干什么的。尽管。。。还有另外一种方法。}
#{431}{}{Another?! Speak then!}
{431}{}{又一个？！那就说吧！}
#{432}{}{Heh! Just like that?}
{432}{}{嘿！就这样？}
#{433}{}{Come on, don't hold back from your partner. You were gonna tell me anyway. So spill it!}
{433}{}{拜托，别对你的搭档隐瞒。反正你也要告诉我。所以说出来！}
#{434}{}{[Gulps down beer] Hrmm... Fine, I'll tell you. Actually, no, I won't. [pulls something out of his pocket] Here.}
{434}{}{[大口喝啤酒]嗯。。。好吧，我告诉你。实际上，不，我不会在这里。}
#{435}{}{What?! A coin with a hole and some rope? Are you serious?}
{435}{}{什么？！有洞和绳子的硬币？你是认真的吗？}
#{436}{}{Uhuh. Stick the coin in the slot. The machine works, you grab the bottle and then pull the coin right back up! [grins like he was just appointed governor of the state]}
{436}{}{嗯。把硬币塞进投币口。机器工作了，你抓起瓶子，然后把硬币拉回来！[笑着好像他刚被任命为州长]}
#{437}{}{What if it gets stuck?}
{437}{}{如果卡住了怎么办？}
#{438}{}{Eh, it happens. But it's not like it's a huge loss.}
{438}{}{呃，这是常有的事。但这并不是一个巨大的损失。}
#{439}{}{You're like a walking goldmine, friend!}
{439}{}{你就像一个活的金矿，朋友！}
#{440}{}{Oh yeah, I am... Speaking of, you can keep it! I'll make more. Now, I think I need to land face-first into this salad and get a few hours of sleep.}
{440}{}{哦，是的，我是。。。说到这里，你可以留着它！我会做更多的。现在，我想我得先吃沙拉，睡几个小时。}
#{441}{}{Thanks for sharing your experience.}
{441}{}{谢谢分享你的经验。}
#{442}{}{Heh, bye now, idiot. Shouldn't be throwing experience around just like that. Heh.}
{442}{}{嘿，再见，白痴。不应该就这样到处乱扔经验。嘿。}
#{1122}{}{Just looking for someone to talk to since I'm new in town. How do you live in this city?}
{1122}{}{我刚进城就想找个人谈谈。你在这个城市怎么生活？}
#{1125}{}{I think I confused you with someone else. I'll be going now.}
{1125}{}{我想我把你和别人搞混了。我要走了。}
#{1149}{}{Hold on! You know, you look like quite the sly bitch. You know what I'm talking about? [winks]}
{1149}{}{坚持住！你知道，你看起来像个狡猾的婊子。你知道我在说什么吗？[眨眼]}
#{1157}{}{Is that so? What about this? [pulls a coin out of your pocket that you're seeing for the first time in your life] I saw you! You just tried to pickpocket me!}
{1157}{}{是这样吗？这个怎么样？我看见你了！你刚才想扒窃我！}
#{1159}{}{Shit, you got me man. Yeah, I'm a thief. Question is, what do we do now?}
{1159}{}{妈的，你抓住我了。是啊，我是小偷。问题是，我们现在该怎么办？}
#{1169}{}{No-no, forget it! I quit and all that. Bye.}
{1169}{}{不，不，算了吧！我辞职了。再见。}
#{1220}{}{Quit wasting time. I need you to boost me over that fence. Understood?}
{1220}{}{别浪费时间了。我需要你把我推过栅栏。理解？}
#{1360}{}{Well-well, let's see what you've got.}
{1360}{}{好吧，让我们看看你有什么。}
#{1210}{}{Ah shit! Where's that bitch!!!}
{1210}{}{啊，妈的！那个婊子在哪！！！}
#{1211}{}{If she doesn't come out...}
{1211}{}{如果她不出来。。。}
#{1212}{}{Come on! Come out already!}
{1212}{}{加油！快出来！}
#{1213}{}{What is this - a setup?}
{1213}{}{这是什么-设置？}
#{1214}{}{Argh! Where's this bitch!?}
{1214}{}{啊！这婊子在哪！？}
#{1215}{}{What's this, a setup?}
{1215}{}{这是什么装置？}
#{1216}{}{Well, shit!}
{1216}{}{好吧，妈的！}
#{1217}{}{Where's she gone?!}
{1217}{}{她去哪了？！}
#{1218}{}{I knew I couldn't trust her!}
{1218}{}{我知道我不能相信她！}
#{1219}{}{Hey, you! I don't wanna go behind the bars!}
{1219}{}{嘿，你！我不想进监狱！}
#{1354}{}{Why did I decide to do this!?}
{1354}{}{我为什么要这么做！？}
