#{100}{}{You see a "shady man".}
{100}{}{你看到一个“黑鬼”。}
#{101}{}{You see a completely ordinary man from the streets who doesn't look suspicious at all.}
{101}{}{你在街上看到一个完全普通的人，一点也不可疑。}
#{102}{}{Don't worry.}
{102}{}{别担心。}
#{110}{}{Wow, look at those clothes! You aren't from around here, huh?}
{110}{}{哇，看那些衣服！你不是这附近来的吧？}
#{111}{}{Hey, didn't I see you in that other part of Reno with the serious looking fellow? It's... Surprising to see you among decent people.}
{111}{}{嘿，我没看见你和那个严肃的家伙在里诺的另一个地方吗？这是。。。在正派人群中见到你真令人惊讶。}
#{112}{}{Well, well, do my eyes deceive me? If it isn't another inhabitant of these beautiful slums? My regards!}
{112}{}{好吧，好吧，我的眼睛欺骗了我吗？如果不是这些美丽贫民窟的另一个居民？我的问候！}
#{113}{}{And who are you?}
{113}{}{你是谁？}
#{114}{}{Just another bum, sir, like any other. I'm just trying to warm myself up. Hope you don't mind.}
{114}{}{只是另一个流浪汉，先生，和其他流浪汉一样。我只是想让自己暖和一下。希望你不介意。}
#{115}{}{Quit bullshitting me! Who are you and what do you need in Wright's territory?}
{115}{}{别跟我胡扯了！你是谁，在赖特的地盘你需要什么？}
#{116}{}{My boss said you need to leave. You can do that either on your own, or in a box.}
{116}{}{我老板说你得走了。你可以自己做，也可以在盒子里做。}
#{117}{}{I don't know who you are, but you aren't meant to be here. I'll pay you 300 bucks if you disappear, okay?}
{117}{}{我不知道你是谁，但你不该在这里。如果你消失了，我给你300美元，好吗？}
#{118}{}{I don't mind. Stay... For now.}
{118}{}{我不介意。留下来。。。现在。}
#{119}{}{What are you talking about, sir?! I'm just an ordinary bum, you must be confusing me with someone!}
{119}{}{你在说什么，先生？！我只是个普通的流浪汉，你一定把我和别人搞混了！}
#{120}{}{Your skin is far too smooth for someone from the streets. Still going to play innocent?}
{120}{}{你的皮肤对街上的人来说太光滑了。还是要装无辜？}
#{121}{}{Me?! What for?! I didn't do nothing! Just keeping warm next to a barrel! Please sir, all I want is a single look at these magnificent slums and I'll leave.}
{121}{}{我？！为何？！我什么也没做！只是在桶边取暖！先生，我只想看一眼这些宏伟的贫民窟，我就走。}
#{122}{}{[Press him against a wall] Listen up, shithead. I don't know who sent you, but while I'm working for Wright, I won't let trash like you to slip by. Understood? Now get the fuck out!}
{122}{}{[把他按在墙上]听着，混蛋。我不知道是谁派你来的，但当我为莱特工作的时候，我不会让你这样的垃圾溜走。理解？给我滚出去！}
#{123}{}{Oh wow, you are so generous, sir! For that kind of money, I'd... Actually, if I think about it, this might be the best way.}
{123}{}{哇，你真大方，先生！为了那笔钱，我。。。实际上，如果我仔细想想，这可能是最好的办法。}
#{124}{}{Here's your money, I don't want to see you again.}
{124}{}{这是你的钱，我不想再见到你了。}
#{125}{}{Don't care.}
{125}{}{别在意。}
#{126}{}{Stay here, I'll be back.}
{126}{}{呆在这儿，我会回来的。}
#{127}{}{[You notice the scared faces of citizens peeking from windows and street corners] S-sure, s-sir, I won't disturb you again...}
{127}{}{[你注意到从窗户和街角偷看的市民惊恐的表情]当然，先生，我不会再打扰你了。。。}
#{128}{}{Damn right! Now get out.}
{128}{}{他妈的对！现在出去。}
#{129}{}{[He scowls at you] You think you see everything? Bet you've got eyes on the back of your head too.}
{129}{}{你以为你什么都看到了？我打赌你的后脑勺上也有眼睛。}
#{130}{}{You really think I'll fall for that?}
{130}{}{你真的认为我会上当？}
#{131}{}{Haha! You're blind like the rest of them. These... Bosses know a lot, but fail to notice simple things. You know what I'm talking about. They're confident, arrogant, knowing everything. But you're just a tool. They're using you, and you... You're probably using them too, but differently.}
{131}{}{哈哈！你和其他人一样瞎了。这些。。。老板知道的很多，但没注意到简单的事情。你知道我在说什么。他们自信，傲慢，无所不知。但你只是个工具。他们在利用你，而你。。。你可能也在使用它们，但不同。}
#{132}{}{What are you talking about?}
{132}{}{你在说什么？}
#{133}{}{I've had enough! I'm gonna put you back in the trash where you belong! [Attack]}
{133}{}{我受够了！我要把你放回属于你的垃圾桶！[攻击]}
#{134}{}{You can beat me to a pulp. Right here on the streets. But you'll only prove you're a piece of shit just like your boss. You do that and in under an hour everyone here will know about it. How does that sound? Yeah, I'll leave... Quietly.}
{134}{}{你可以把我打得体无完肤。就在街上。但你只能证明你和你老板一样是个混蛋。你这样做，不到一个小时这里的每个人都会知道的。听起来怎么样？是的，我要走了。。。安静地。}
#{135}{}{Good, now scram.}
{135}{}{很好，快滚。}
#{1114}{}{Just another bum, ma'am, like any other. I'm just trying to warm myself up. Hope you don't mind.}
{1114}{}{只是另一个流浪汉，女士，和其他流浪汉一样。我只是想让自己暖和一下。希望你不介意。}
#{1119}{}{What are you talking about, ma'am?! I'm just an ordinary bum, you must be confusing me with someone!}
{1119}{}{你在说什么，女士？！我只是个普通的流浪汉，你一定把我和别人搞混了！}
#{1121}{}{Me?! What for?! I didn't do nothing! Just keeping warm next to a barrel! Please ma'am, all I want is a single look at these magnificent slums and I'll leave.}
{1121}{}{我？！为何？！我什么也没做！只是在桶边取暖！夫人，我只想看一眼这些宏伟的贫民窟，我就走。}
#{1123}{}{Oh wow, you are so generous, ma'am! For that kind of money, I'd... Actually, if I think about it, this might be the best way.}
{1123}{}{哦，哇，你真慷慨，女士！为了那笔钱，我。。。实际上，如果我仔细想想，这可能是最好的办法。}
#{1127}{}{[You notice the scared faces of citizens peeking from windows and street corners] S-sure, m-ma'am, I won't disturb you again...}
{1127}{}{[你注意到从窗户和街角偷看的市民惊恐的表情]当然，女士，我不会再打扰你了。。。}
#{1131}{}{Haha! You're blind like the rest of them. These... Bosses know a lot, but fail to notice simple things. You know what I'm talking about. They're confident, arrogant, knowing everything. But you're just a tool. They're using you, and you... You're probably using them too, but differently.}
{1131}{}{哈哈！你和其他人一样瞎了。这些。。。老板知道的很多，但没注意到简单的事情。你知道我在说什么。他们自信，傲慢，无所不知。但你只是个工具。他们在利用你，而你。。。你可能也在使用它们，但不同。}
