#{100}{}{You see a stranger.}
{100}{}{你看到一个陌生人。}
#{101}{}{You see Solomon.}
{101}{}{你看到所罗门了。}
#{102}{}{You see a strange-looking man with a short beard and black sunglasses.}
{102}{}{你看到一个长得很奇怪的男人，留着短胡子，戴着黑色太阳镜。}
#{103}{}{You see an experienced chem dealer. His eyes are hidden behind black sunglasses.}
{103}{}{你看到一个有经验的化学经销商。他的眼睛藏在黑色太阳镜后面。}
#{104}{}{It's done. All that remains is to return the ring to Big Louie.}
{104}{}{完成了。剩下的就是把戒指还给大路易。}
#{105}{}{Racer}
{105}{}{赛车手}
#{106}{}{Stryker}
{106}{}{史崔克}
#{107}{}{A man with a brain tumor from the slums}
{107}{}{一个来自贫民窟的脑瘤患者}
#{108}{}{That dealer by the hotel}
{108}{}{旅馆旁边的那个商人}
#{109}{}{Stay cool. You were recommended by a mutual friend. [Name him.]}
{109}{}{保持冷静。你是一个共同的朋友推荐的。[说出他的名字]}
#{110}{}{[The man watches you intently. His eyes are hidden by black sunglasses, but you still sense coldness behind them.] The hell do you need, stranger?}
{110}{}{[那人目不转睛地看着你。他的眼睛被黑色太阳镜遮住了，但你仍然能感觉到眼镜后面的寒冷？}
#{111}{}{Hello... Solomon.}
{111}{}{你好。。。所罗门。}
#{112}{}{I'm looking to buy some... Specialty goods. I think you know what I'm talking about.}
{112}{}{我想买一些。。。特产。我想你知道我在说什么。}
#{113}{}{Just exploring, sorry for the trouble.}
{113}{}{只是探索一下，抱歉给你添麻烦了。}
#{114}{}{You again? You're starting to piss me off!}
{114}{}{又是你？你开始惹我生气了！}
#{115}{}{You want to make some money or not? Show me the goods.}
{115}{}{你想不想赚点钱？给我看看货物。}
#{116}{}{You again?}
{116}{}{又是你？}
#{117}{}{I'm looking to buy. What do you got?}
{117}{}{我想买。你有什么发现？}
#{118}{}{Just looking around.}
{118}{}{只是四处看看。}
#{119}{}{There's nothing like that around here. And even if - IF - there was, you're just some asshole off the street. What makes you worth the time?}
{119}{}{这附近没有这样的。即使-如果-有，你也只是街上的混蛋。是什么让你值得花时间？}
#{120}{}{More than you'd think... Solomon.}
{120}{}{比你想象的还要多。。。所罗门。}
#{121}{}{I'm not like some street trash looking for a fix. You have a real opportunity here. Are you going to take it, or am I wasting my time?}
{121}{}{我可不像街上的垃圾一样在找解决办法。你在这里有一个真正的机会。你是要接受，还是我在浪费时间？}
#{122}{}{Enough of this, I'm going.}
{122}{}{够了，我要走了。}
#{123}{}{[He stiffens and nervously adjusts his sunglasses] Solomon? Never heard of him. Who the hell is he, anyway?}
{123}{}{所罗门？从没听说过他。他到底是谁？}
#{124}{}{ Stay calm. }
{124}{}{保持冷静。}
#{125}{}{ gave me your name.}
{125}{}{告诉我你的名字。}
#{126}{}{Shut the hell up. Your only chance of surviving this is if I like you.}
{126}{}{闭嘴。你能活下来的唯一机会就是我喜欢你。}
#{127}{}{Hey, chill out. I'm just here to talk. You're making Big Louie nervous.}
{127}{}{嘿，冷静点。我只是来谈谈。你让大路易很紧张。}
#{128}{}{Oh? My mistake, sorry.}
{128}{}{哦？我错了，对不起。}
#{129}{}{I guess I don't have much to offer right now. I'll be back with more.}
{129}{}{我想我现在没有什么可以提供的了。我会带更多回来的。}
#{130}{}{[He seems torn. Eventually, his greed wins out over his caution.] Alright. What's up? I don't do small time shit, but for the right price I can solve all your problems... Eh, most of them.}
{130}{}{[他看起来很伤心。最终，他的贪婪战胜了他的谨慎。怎么了？我不做小时间的狗屎，但以适当的价格，我可以解决你所有的问题。。。呃，大多数人。}
#{131}{}{I've always been interested in chemistry, medicine, that sort of thing.}
{131}{}{我一直对化学、医学之类的东西感兴趣。}
#{132}{}{Why don't you introduce yourself? I want to know who I'm dealing with.}
{132}{}{你为什么不自我介绍一下呢？我想知道我在和谁打交道。}
#{133}{}{You want chems? I've got the best shit in Reno. You're talking to the one and only Solomon, baby. I'm THE master of chems in this city.}
{133}{}{你想要化学？我有雷诺最好的狗屎。你在和唯一的所罗门说话，宝贝。我是这个城市的化学硕士。}
#{134}{}{Actually, I've got something for you, courtesy of Big Louie.}
{134}{}{实际上，我有东西要给你，是大路易的恩惠。}
#{135}{}{That's S-O-L-O-M-O-N, right? Good. I want to make sure you're headstone's spelled right.}
{135}{}{那是-O-L-O-M-O-N，对吧？很好。我想确认你的墓碑拼写正确。}
#{136}{}{That's what I'm here for. Let's see what you've got for me.}
{136}{}{这就是我来这里的目的。让我看看你给我准备了什么。}
#{137}{}{What for? [he eyes you nervously] I don't need this sketchy shit. Get out of here.}
{137}{}{为何？[他紧张地盯着你]我不需要这些粗略的东西。离开这里。}
#{138}{}{Fine, I'm going.}
{138}{}{好吧，我去。}
#{139}{}{[He backs up fast] Big Louie? Hold on, just wait a minute, let's talk about this! I didn't mean for what happened! I can make it up to him!}
{139}{}{大路易？等等，等一下，我们谈谈这个！我不是故意的！我可以补偿他！}
#{140}{}{I'm listening, but this had better be VERY convincing.}
{140}{}{我在听，但这最好是很有说服力的。}
#{141}{}{Talk to who? Big Louie's not here. All you have is me. And I'm not listening.}
{141}{}{跟谁说话？大路易不在这儿。你只有我。我没在听。}
#{142}{}{Okay, first, things are more complicated here, alright? This is Reno, not Louie's bumfuck Indian village. You gotta play a different game here, get it?}
{142}{}{好吧，首先，这里的事情更复杂，好吗？这是雷诺，不是路易那该死的印第安村庄。你得在这里玩不同的游戏，明白吗？}
#{143}{}{Yeah, I got it. Someone told you to give the poison to Fatso. Who?}
{143}{}{是的，我知道了。有人叫你把毒药给胖子。谁？}
#{144}{}{What's complicated about it? I cut off your filthy head, bring it back to Louie, and go on with my life. Simple.}
{144}{}{有什么复杂的？我砍下你肮脏的头，把它还给路易，继续我的生活。很简单。}
#{145}{}{ Look, Louie wants you dead. Even if I don't kill you, you'll be looking over your shoulder for the rest of your life. But if I give him that ring on your finger, he won't ever think about you again. Do you understand what I'm saying?}
{145}{}{听着，路易要你死。即使我不杀你，你下半辈子也要回头看。但如果我把你手指上的戒指给他，他就再也不会想你了。你明白我的意思吗？}
#{146}{}{Fuck off!}
{146}{}{滚开！}
#{147}{}{[He glances out the door, but no one is coming to save him] I can't tell you who my boss is. But I can say this - he says he won't be working for Big Louie anymore. It'll be like he's going on strike, you know? A man who will be STRIKING against Big Louie? [he glares at you over the tops of his sunglasses] You could say he STRIKES out against a lot of people. Like the ones that kill his best chem pushers, understand?}
{147}{}{[他朝门外看了一眼，但没人来救他]我不能告诉你我的老板是谁。但我可以这么说-他说他不会再为大路易工作了。就像他要罢工一样，你知道吗？一个要和大路易作对的人？[他从太阳镜顶上瞪着你]你可以说他对很多人都大发雷霆。就像那些杀了他最好的化学推手，明白吗？}
#{148}{}{I've heard enough. }
{148}{}{我听够了。}
#{149}{}{Fuck this. Get out of here!}
{149}{}{去他妈的。离开这里！}
#{150}{}{You earn experience for getting Solomon's admission.}
{150}{}{你为获得所罗门的录取而获得经验。}
#{151}{}{But... [He starts pulling on the ring, but it's stuck fast on his finger. You can see how tightly the metal grips his flesh.] I can't just give it to you! I haven't been able to take it off for years!}
{151}{}{但是。。。[他开始拉戒指，但戒指牢牢地粘在他的手指上。你可以看到金属紧紧地抓住他的肉。]我不能把它给你！我已经好多年没脱了！}
#{152}{}{I'm planning to kill you and take your ring. Do I have to draw you a diagram?}
{152}{}{我打算杀了你，拿走你的戒指。我要给你画个图表吗？}
#{153}{}{We could cut off the finger. Better than your head, isn't it?}
{153}{}{我们可以切掉手指。比你的脑袋好，不是吗？}
#{154}{}{ Oh, simple as that, huh? [he starts sweating profusely] It's a part of me! You think I can just... Chop-chop, here you go?!}
{154}{}{哦，就这么简单吧？[他开始大汗淋漓]这是我的一部分！你以为我可以。。。砍砍砍，给你？！}
#{155}{}{You won't have to do a thing. I'll just cut it off myself.}
{155}{}{你什么都不用做。我自己把它剪掉。}
#{156}{}{Either you lose the finger or you lose your life. This is your last chance, Solomon.}
{156}{}{不是失去手指就是失去生命。这是你最后的机会，所罗门。}
#{157}{}{Don't worry, Solomon, I'm a doctor. I can amputate it quickly and cleanly... Well, as cleanly as amputations get, anyway.}
{157}{}{别担心，所罗门，我是医生。我可以迅速而干净地截肢它。。。好吧，不管怎样，就像截肢手术一样干净。}
#{158}{}{This is a lot to take in. I'll give you some time to think about it.}
{158}{}{这是一个很大的接受。我给你点时间考虑一下。}
#{159}{}{[He hems and haws anxiously. Just as you start losing your patience, he turns his head away and extends his hand to you.] Fine. Take the finger! There's no other choice, anyway. Just... Make it quick!}
{159}{}{[他焦急地哼哼着。就在你开始失去耐心的时候，他把头转过去，向你伸出手来。抓住手指！反正别无选择。只是。。。快点！}
#{160}{}{Then shut up and don't distract me.}
{160}{}{那就闭嘴，别让我分心。}
#{161}{}{[He looks down at his hand in a panic, then shakes his head] No. No, no, this is - this is some kind of trick! You conniving fucking bastard - get out! You can't touch me. Get the fuck out, I'm protected!}
{161}{}{[他惊恐地低头看着自己的手，然后摇摇头]不，不，不，这是-这是某种骗局！你这个纵容我的混蛋-滚出去！你不能碰我。滚出去，我受保护了！}
#{162}{}{[He hems and haws anxiously. Just as you start losing your patience, he slams his hand down on a table and pulls out a knife.] Fuck! You win! Okay, Solomon, you can do this... You'd better get this ring back to Louie, you fucker! You fuck me, and I'll find you! I can hire ten mercenaries to track you down with what I make in a day!}
{162}{}{[他焦急地哼哼着。就在你开始失去耐心的时候，他突然把手放在桌子上，掏出一把刀！你赢了！好吧，所罗门，你能做到的。。。你最好把戒指还给路易，你这个混蛋！你操我，我会找到你！我可以雇十个佣兵用我一天赚的钱来追踪你！}
#{163}{}{Yeah, yeah, get to work. I have other things to do today.}
{163}{}{是的，是的，开始工作吧。我今天还有别的事要做。}
#{164}{}{Oh, the drama. If this is so much trouble, I'll cut it off for you.}
{164}{}{哦，戏剧。如果这么麻烦，我就帮你把它剪掉。}
#{165}{}{Your hands are shaking so badly you'll probably slit your wrists! Give me the knife, Solomon, I'll get it done safely.}
{165}{}{你的手抖得厉害，可能会割破手腕！把刀给我，所罗门，我会安全地完成的。}
#{166}{}{You know what, Solomon? Do it yourself. I'm already going out of my way not to kill you, I'm not going to cut off your finger for you.}
{166}{}{你知道吗，所罗门？你自己动手吧。我已经尽力不杀你了，我不会为你割下你的手指。}
#{167}{}{[He perks up] Are you really a doctor? Oh, god, thank you! This ring has gotten so painful I can't sleep at night! If you can do this right, then... When can we get started? I want to get this done as soon as possible!}
{167}{}{你真的是医生吗？哦，上帝，谢谢你！这戒指疼得我晚上都睡不着！如果你能做到这一点，那么。。。我们什么时候开始？我想尽快完成！}
#{168}{}{We can do it now. Take these painkillers and we'll get started.}
{168}{}{我们现在可以做了。吃了这些止痛药我们就开始了。}
#{169}{}{We can't perform surgery with you thrashing around. We'll need anaesthetic. Wait here.}
{169}{}{我们不能在你到处乱动的情况下做手术。我们需要麻醉。在这里等着。}
#{170}{}{[He perks up] Can you? This ring has gotten so painful, lately... But you know, you don't seem like a doctor to me. There haven't been any doctors in Reno for a long time.}
{170}{}{[他振作起来]你能吗？这戒指最近很疼。。。但你知道，我觉得你不像个医生。里诺很久没有医生了。}
#{171}{}{That's it, you've exhausted my patience. Take the knife and cut off your own damn finger. How does that sound??}
{171}{}{就这样，你耗尽了我的耐心。拿刀切掉你自己该死的手指。听起来怎么样？？}
#{172}{}{ My patience is nearing its end. Just like Louie's. Cut your finger off if you want to live.}
{172}{}{我的耐心快要结束了。就像路易的一样。如果你想活下去就把你的手指砍掉。}
#{173}{}{Fine, wait here until I come up with something.}
{173}{}{好吧，在这儿等我想点什么。}
#{174}{}{[The dull knife grinds into the bone. This is a bit more laborious than you had expected. Solomon screams and stamps his feet in agony.] AAAAAUUGHHH! FUCKING SHIT, IT HURTS, FUCK! WHAT'S TAKING SO LONG?! AAAAAUUUGHHH!}
{174}{}{[钝刀磨成骨头。这比你想象的要费劲一些。所罗门尖叫着，痛苦地跺着脚！妈的，疼死了，妈的！怎么这么久？！啊啊啊！}
#{175}{}{Success!}
{175}{}{成功！}
#{176}{}{[The knife barely touches Solomon's skin before he starts squealing in pain. He sweats and writhes in agony, but he fears death more strongly than the pain. Meanwhile, your ears start to ring from his nonstop screaming.] FUCK! FUCKING GODDAMN! HOW DO THOSE FUCKING CHINESE DO THIS? Okay, okay, Sol, you can do this... FUCK! GOD, WON'T THIS FUCKING FINGER EVER COME OFF?!}
{176}{}{[刀几乎没碰到所罗门的皮肤，他就开始痛苦地尖叫。他在痛苦中出汗和扭动，但他比痛苦更害怕死亡。与此同时，你的耳朵也开始因为他不停的尖叫而响起来！他妈的！那些该死的中国人是怎么做到的？好吧，好吧，索尔，你能做到的。。。性交！天哪，这该死的手指不会掉下来吗？！}
#{177}{}{Is that all? You got the whole finger, right?}
{177}{}{就这些吗？整个手指都在你手上，对吧？}
#{178}{}{[The routine amputation isn't even a challenge. The only challenge is enduring Solomon's nonstop talking. Before long, you start to wish you'd given him more sedatives.] So the whore pours the booze on her head and lights it up, running around and screaming "I'm a light bulb! I'm a light bulb!" That's when I stopped mixing Mentats with Med-X... }
{178}{}{[常规截肢甚至不是一个挑战。唯一的挑战是忍受所罗门不停的说话。没过多久，你就开始希望你能给他更多的镇静剂]于是妓女把酒倒在头上，点燃了灯，跑来跑去，尖叫着“我是灯泡！我是个灯泡！”就在那时我不再把薄荷糖和Med-X混在一起。。。}
#{179}{}{All done.}
{179}{}{全部完成。}
#{180}{}{[You've got the finger and the ring. Solomon nurtures his bandaged hand, pale and clammy.] God, you fucked me up, you bastard. My vision's getting dark... Well, what are you waiting for? Get back to Big Louie! I've got to sleep this off... }
{180}{}{[你有手指和戒指。所罗门抚摸着他那缠着绷带的手，苍白而湿漉漉的。]上帝，你把我搞砸了，你这个混蛋。我的视线越来越暗。。。你还在等什么？回到大路易身边！我得好好睡一觉。。。}
#{181}{}{You got lucky today. Don't forget that.}
{181}{}{你今天很幸运。别忘了。}
#{182}{}{[You've got the finger and the ring. Solomon doesn't look too happy, but he's already experimenting with his bandaged hand.] Good work, doc. Don't think this'll get you a discount or anything. Now get that ring back to Big Louie. I'm sick of looking over my shoulder.}
{182}{}{[你有手指和戒指。所罗门看起来不太高兴，但他已经在用绷带手做实验了。别以为这能给你打折什么的。把戒指还给大路易。我讨厌回头看。}
#{183}{}{Wow, the gratitude is overwhelming. See you around, Solomon.}
{183}{}{哇，感激之情真是太强烈了。再见，所罗门。}
#{184}{}{Huh. Good for something, at least. So, what do you need from the great Solomon?}
{184}{}{呵呵。至少有好处。那么，你想从伟大的所罗门那里得到什么？}
#{185}{}{I want to know about the man with the brain tumor from the slums. You don't give him chems out of the goodness of your heart, do you?}
{185}{}{我想知道那个贫民窟脑瘤患者的情况。你不是出于好心才给他化学药品的吧？}
#{186}{}{You gain experience points for performing a successful surgery.}
{186}{}{你将获得成功手术的经验值。}
#{187}{}{So you're Solomon? Big Louie's told me so much about you.}
{187}{}{你是所罗门？大路易跟我说过很多关于你的事。}
#{188}{}{Tell me about your wares.}
{188}{}{告诉我你的商品。}
#{189}{}{Nothing right now. See you.}
{189}{}{现在什么都没有。再见。}
#{190}{}{Not as good as you think. I'm going to enjoy playing with your guts.}
{190}{}{不如你想的那么好。我会喜欢和你玩的。}
#{191}{}{What the fuck do you expect? I risk my life everyday and you want me to give my product out for free? This is Reno. Everything has a price here. If this guy didn't want to pay he could have died peacefully long ago, but he said he wanted to live for his family. Well, if it weren't for me he wouldn't even have that choice! So yeah, I take his money. Why the fuck wouldn't I?}
{191}{}{你他妈的还指望什么？我每天都在冒生命危险，你想让我免费赠送我的产品吗？我是雷诺。这里什么都有价。如果这家伙不想付钱，他早就可以平静地死去了，但他说他想为家人活着。好吧，如果不是我，他甚至没有选择！所以是的，我拿了他的钱。我他妈的为什么不呢？}
#{192}{}{You have no compassion. You disgust me.}
{192}{}{你没有同情心。你让我恶心。}
#{193}{}{Just wondering is all. Onto other matters, then.}
{193}{}{只是好奇而已。那就谈别的吧。}
#{194}{}{Yeah, they're lucky to have you. That's all, I'll be going now.}
{194}{}{是的，他们很幸运有你。就这样，我现在就走。}
#{195}{}{Time to cut off that finger of yours.}
{195}{}{是时候砍掉你的手指了。}
#{196}{}{I'll give you more, but not for free. Pay up.}
{196}{}{我会给你更多，但不是免费的。付钱。}
#{197}{}{That's not enough. I need more!}
{197}{}{这还不够。我需要更多！}
#{198}{}{No more for you. You need to learn your limits.}
{198}{}{你再也没有了。你需要学习你的极限。}
#{199}{}{}
{199}{}{}
#{200}{}{You're a pox on society. It's hard to imagine people letting you do this. How many people have died because of you?}
{200}{}{你是社会上的水痘。很难想象人们会让你这么做。有多少人因为你而死？}
#{201}{}{Hey, fuck off! People die because they're greedy and stupid, not because of me. Everyone who buys from me knows exactly what they're getting. If they can't handle it... Not my problem.}
{201}{}{嘿，滚开！人们死是因为贪婪和愚蠢，而不是因为我。每一个从我这里买东西的人都知道他们得到了什么。如果他们处理不了。。。不是我的问题。}
#{202}{}{ How many innocent people due to the addicts you've created?}
{202}{}{你造成了多少无辜的人？}
#{203}{}{Who do you think you're fucking with? This smells funny. You ought to know better than to try this!}
{203}{}{你以为你在和谁做爱？这闻起来很好笑。你应该知道不要试这个！}
#{204}{}{Alright, I'll check until the first irritation.}
{204}{}{好吧，我会查到第一次。}
#{205}{}{Fuck you, motherfucker! Anyone who buys from me made their own fucking choice! And wherever they get their money, that's their fucking choice too! You think if it weren't for the chems they'd be angels? No, fuck you! They're dumb motherfuckers who make dumb motherfucking choices, and they were dumb motherfuckers before they ever met me! And you're the dumbest motherfucker of them all if you don't get that! Now get the fuck out of here before I air out that empty fucking head of yours!}
{205}{}{去你妈的，混蛋！任何从我这里买东西的人都有自己的选择！不管他们在哪里拿到钱，那也是他们的选择！你觉得如果不是化学反应他们会是天使吗？不，去你妈的！他们是愚蠢的混蛋，做出愚蠢的选择，他们在遇见我之前就是愚蠢的混蛋！如果你不明白，你就是他们中最蠢的混蛋！现在他妈的滚出去，不然我就把你那该死的脑袋吐出来！}
#{206}{}{[Leave.]}
{206}{}{[离开]}
#{207}{}{Heh. [he grins slyly] Wanna hear an interesting story?}
{207}{}{嘿。想听个有趣的故事吗？}
#{208}{}{Sure.}
{208}{}{当然。}
#{209}{}{You're up to something, and I don't want to be part of it. Goodbye.}
{209}{}{你在搞什么，我不想参与其中。再见。}
#{210}{}{The guy who lived here before I moved in? He wasn't a bad guy, but he smelled like shit. You knew he was coming before you saw him. When he died, dogs ate his body and freaked out. Ran up and down the street all night long. You think there was something in the meat they ate?}
{210}{}{我搬进来之前住在这里的那个人？他不是坏人，但他闻起来像屎。你看到他之前就知道他要来了。他死后，狗吃了他的尸体，吓了一跳。整夜在街上跑来跑去。你觉得他们吃的肉里有什么？}
#{211}{}{What are you implying?}
{211}{}{你在暗示什么？}
#{212}{}{We should dig him up and make a nice chem soup out of him. What do you think?}
{212}{}{我们应该把他挖出来，用他做一个很好的化学汤。你怎么认为？}
#{213}{}{I've done worse than dig up corpses, but what am I going to get for it?}
{213}{}{我做的比挖尸体还糟，但我能得到什么呢？}
#{214}{}{I'll share a hit or two if it works out. Interested?}
{214}{}{如果成功的话，我会和你分享一两个。有兴趣吗？}
#{215}{}{Why don't you do it yourself?}
{215}{}{你为什么不自己做呢？}
#{216}{}{I got a reputation. I can't be seen digging up graves and I can't pay a bum to do it because they'll spread the word. You're from out of town, though. No one's gonna care what you get up to.}
{216}{}{我得到了名声。我不能让人看见我在挖坟墓，我也不能花钱雇一个流浪汉去做，因为他们会散布消息的。不过，你是从外地来的。没人会在乎你在干什么。}
#{217}{}{I'll do it. Where'd they bury him?}
{217}{}{我会的。他们把他埋在哪里了？}
#{218}{}{No, I'm done with the grave-robbing game.}
{218}{}{不，我不玩盗墓游戏了。}
#{219}{}{Near the railroad station to the south. Look for the crest of the sewer tubes.}
{219}{}{靠近火车站向南。寻找下水道的顶部。}
#{220}{}{Sounds great.}
{220}{}{听起来很棒。}
#{221}{}{Just an offer. No hard feelings.}
{221}{}{只是一个提议。没有痛苦的感觉。}
#{222}{}{Alright.}
{222}{}{好吧。}
#{223}{}{Here's what's left of him. Take it and get it away from here.}
{223}{}{这是他剩下的东西。把它带走。}
#{224}{}{Shit, that time in the ground sure didn't help his smell! Let's hurry this up, huh? Take this knife and cut the meat off the bone.}
{224}{}{妈的，在地上的那一次对他的气味毫无帮助！我们快点吧？拿这把刀把肉从骨头上切下来。}
#{225}{}{I did my part of the deal. You cut him up.}
{225}{}{我做了我该做的。你把他切开了。}
#{226}{}{Fine.}
{226}{}{好的。}
#{227}{}{[He glares at you] You want your fix or not? Take the knife and get cutting! Until you're done, no fix. You think I fucking owe you anything? You're lucky I'm even giving you this chance, you useless little bitch.}
{227}{}{[他瞪着你]你要不要修理？拿刀去切！在你完成之前，没有修复。你以为我欠你什么？你很幸运我给了你这个机会，你这个没用的小婊子。}
#{228}{}{Fuck you too.}
{228}{}{我也操你。}
#{229}{}{Fine, I'll do it if you can't handle it.}
{229}{}{好吧，如果你受不了我就去做。}
#{230}{}{[He gives you a look of smug contempt] Hurry up little junkie. Gotta get that fix!}
{230}{}{[他轻蔑地看了你一眼]快点，小瘾君子。一定要修好！}
#{231}{}{Right away, sir.}
{231}{}{马上，先生。}
#{232}{}{As soon as I get my fix, I'm going to fuck you up... }
{232}{}{我一修好，就要把你搞砸。。。}
#{233}{}{What was that?}
{233}{}{那是什么？}
#{234}{}{Uh, nothing. Just talking to myself.}
{234}{}{呃，没什么。只是自言自语。}
#{235}{}{[Having finally prepared the corpse, you give the necessary remains to Solomon] Alright, wait a couple of hours. I'll refine this shit and get you your cut.}
{235}{}{[最后准备好尸体，你把必要的遗体交给所罗门]好吧，等几个小时。我会把这些东西提炼出来，给你分一杯羹。}
#{236}{}{[Sit and wait.]}
{236}{}{[坐等]}
#{237}{}{[After several delightful hours of watching cockroaches scurry across the floor, Solomon returns with your pay] Fuck, this smell's never going to come out! Take this and go. I got shit to do.}
{237}{}{[在几个小时愉快地看着蟑螂在地板上飞奔之后，所罗门拿着你的薪水回来了]妈的，这味道永远不会出来！拿着这个走吧。我有他妈的事要做。}
#{238}{}{See you. Try not to end up like your friend here.}
{238}{}{再见。尽量不要像你的朋友那样结束。}
#{239}{}{Now I don't need you anymore. [Attack!]}
{239}{}{现在我不再需要你了。[进攻！]}
#{250}{}{I need a fix so bad. Please. I'll do anything... }
{250}{}{我太需要修理了。拜托。我会做任何事。。。}
#{251}{}{Anything? [he puts a hand on your buttocks and smiles sadistically] Wow, you're shaking all over. How long has it been since your last hit? You really don't have anywhere else to go, do you?}
{251}{}{有什么事吗？[他把手放在你屁股上，残忍地笑着]哇，你浑身都在发抖。你上次被击中有多久了？你真的没有别的地方可去了，是吗？}
#{252}{}{Anything... Just give me another hit... }
{252}{}{任何事。。。再打我一下。。。}
#{253}{}{[He pulls down your pants and slides into your rectum in one movement] Ohh, that's good... What else you got, huh? Give me everything you have, any maybe that's enough.}
{253}{}{[他拉下你的裤子，一个动作滑进你的直肠]哦，很好。。。你还有什么？把你所有的东西都给我，可能够了。}
#{254}{}{[Search your inventory for something of worth.]}
{254}{}{[在你的库存中搜索有价值的东西。]}
#{255}{}{[He grunts harshly, then pulls out of you] Alright, we're done here. You can go on your way.}
{255}{}{[他狠狠地哼了一声，然后从你身边抽了出来]好了，我们到此为止。你可以上路了。}
#{256}{}{What can you pay?}
{256}{}{你能付多少钱？}
#{257}{}{Alright... }
{257}{}{好吧。。。}
#{258}{}{Why did you give Fatso the poison?}
{258}{}{你为什么给胖子下毒？}
#{259}{}{Does it matter? You don't need to know that, anyway.}
{259}{}{有关系吗？不管怎样，你不需要知道。}
#{1119}{}{There's nothing like that around here. And even if - IF - there was, you're just some bitch off the street. What makes you worth the time?}
{1119}{}{这附近没有这样的。即使-如果-有，你只是街上的婊子。是什么让你值得花时间？}
#{1123}{}{[He stiffens and nervously adjusts his sunglasses] Solomon? Never heard of him. Who the hell is he, anyway?}
{1123}{}{所罗门？从没听说过他。他到底是谁？}
#{1128}{}{Oh? My mistake, sorry.}
{1128}{}{哦？我错了，对不起。}
#{1132}{}{Why don't you introduce yourself? I want to know who I'm dealing with.}
{1132}{}{你为什么不自我介绍一下呢？我想知道我在和谁打交道。}
#{1151}{}{But... [He starts pulling on the ring, but it's stuck fast on his finger. You can see how tightly the metal grips his flesh.] I can't just give it to you! I haven't been able to take it off for years!}
{1151}{}{但是。。。[他开始拉戒指，但戒指牢牢地粘在他的手指上。你可以看到金属紧紧地抓住他的肉。]我不能把它给你！我已经好多年没脱了！}
#{1161}{}{[He looks down at his hand in a panic, then shakes his head] No. No, no, this is - this is some kind of trick! You conniving fucking bitch - get out! You can't touch me. Get the fuck out, I'm protected!}
{1161}{}{[他惊恐地低头看着自己的手，然后摇摇头]不，不，不，这是-这是某种骗局！你这个纵容我的婊子-滚出去！你不能碰我。滚出去，我受保护了！}
#{1170}{}{[He perks up] Can you? This ring has gotten so painful, lately... But you know, you don't seem like a doctor to me. There haven't been any doctors in Reno for a long time.}
{1170}{}{[他振作起来]你能吗？这戒指最近很疼。。。但你知道，我觉得你不像个医生。里诺很久没有医生了。}
#{1180}{}{[You've got the finger and the ring. Solomon nurtures his bandaged hand, pale and clammy.] God, you fucked me up, you bitch. My vision's getting dark... Well, what are you waiting for? Get back to Big Louie! I've got to sleep this off... }
{1180}{}{[你有手指和戒指。所罗门抚摸着他那缠着绷带的苍白湿漉漉的手。]上帝，你把我搞砸了，你这个婊子。我的视线越来越暗。。。你还在等什么？回到大路易身边！我得好好睡一觉。。。}
#{1218}{}{No, I'm done with the grave-robbing game.}
{1218}{}{不，我不玩盗墓游戏了。}
#{1227}{}{[He glares at you] You want your fix or not? Take the knife and get cutting! Until you're done, no fix. You think I fucking owe you anything? You're lucky I'm even giving you this chance, you dumb fucking whore.}
{1227}{}{[他瞪着你]你要不要修理？拿刀去切！在你完成之前，没有修复。你以为我欠你什么？你很幸运我给了你这个机会，你这个该死的婊子。}
