#{100}{}{You see a guard.}
{100}{}{你看到一个警卫。}
#{101}{}{You see a guard of the ranch.}
{101}{}{你看到牧场的守卫。}
#{102}{}{Just give me a reason. I dare you.}
{102}{}{给我个理由。我敢说。}
#{103}{}{It's good to see you.}
{103}{}{很高兴见到你。}
#{104}{}{Watch yourself on Mr. Luciano's property.}
{104}{}{小心卢西亚诺先生的财产。}
#{110}{}{Stop! I don't know you. What are you doing on Mr. Luciano's ranch?}
{110}{}{住手！我不认识你。你在卢西亚诺先生的农场干什么？}
#{111}{}{I'm, uh, the new guy. See, they gave me this jacket and everything!}
{111}{}{我是，呃，新来的。看，他们给了我这件夹克什么的！}
#{112}{}{I work for Mr. Luciano.}
{112}{}{我为卢西亚诺先生工作。}
#{113}{}{Who do you think you're talking to? I'm Oliver's new right hand! I go where I want!}
{113}{}{你以为你在和谁说话？我是奥利弗的新右手！我想去哪里就去哪里！}
#{114}{}{Ranch?! Wow, did I get turned around! Sorry, I'll just go back to the gate now.}
{114}{}{大牧场？！哇，我被调头了！对不起，我现在就回大门去。}
#{115}{}{I've got my eye on you.}
{115}{}{我盯上你了。}
#{116}{}{Uh, sure.}
{116}{}{呃，当然。}
#{117}{}{Sorry, no witnesses. [Attack]}
{117}{}{抱歉，没有目击者。[攻击]}
#{118}{}{Fresh meat, huh? Okay, get to work. Just don't bother anyone - things are busy right now and we don't have time for questions.}
{118}{}{鲜肉，嗯？好了，开始工作吧。只是不要打扰任何人-现在事情很忙，我们没有时间提问。}
#{119}{}{Uh, sure.}
{119}{}{呃，当然。}
#{120}{}{Oh, I heard about you. Okay, go on. Just don't bother anyone - things are busy right now and we don't have time for questions.}
{120}{}{哦，我听说你了。好吧，继续。只是不要打扰任何人-现在事情很忙，我们没有时间提问。}
#{121}{}{Oh... Right. My mistake. Sorry to have bothered you.}
{121}{}{哦。。。正确的。我的错。抱歉打扰你了。}
#{122}{}{Yeah, that's right!}
{122}{}{是的，没错！}
#{123}{}{Many people work for the boss, but that doesn't give them the right to be here. Now turn around. Don't come back until Mr. Luciano gives you permission to be here.}
{123}{}{很多人为老板工作，但这并没有给他们在这里的权利。现在转身。在卢西亚诺先生允许你来之前不要回来。}
#{124}{}{I don't know you. Around here, that means you'd better mind your manners. Now get the hell out of here!}
{124}{}{我不认识你。在这里，你最好注意礼貌。现在给我滚出去！}
#{125}{}{Okay, that's it! Get him!}
{125}{}{好了，就这样！抓住他！}
#{126}{}{You'll have to catch me first!}
{126}{}{你得先抓住我！}
#{150}{}{What the - THIEF! Everyone get in here!}
{150}{}{什么贼！所有人都进来！}
#{151}{}{[Attack]}
{151}{}{[攻击]}
#{152}{}{[His hand goes for his gun] Sir, you can't be here. Leave the corridor, now.}
{152}{}{先生，你不能在这里。现在离开走廊。}
#{153}{}{I just wanted to see your boss...}
{153}{}{我只是想见你老板。。。}
#{154}{}{Okay, whatever you say.}
{154}{}{好吧，随你怎么说。}
#{155}{}{You should've shot first. [Attack]}
{155}{}{你应该先开枪。[攻击]}
#{156}{}{You don't have an appointment. I would know. If you must see Mr. Luciano, speak to Machete. Now, please leave.}
{156}{}{你没有预约。我会知道的。如果你一定要见卢西亚诺先生，跟弯刀谈谈。现在，请离开。}
#{1111}{}{I'm, uh, the new girl. See, they gave me this jacket and everything!}
{1111}{}{我是，呃，新来的女孩。看，他们给了我这件夹克什么的！}
#{1114}{}{Ranch?! Wow, did I get turned around! Sorry, I'll just go back to the gate now.}
{1114}{}{大牧场？！哇，我被调头了！对不起，我现在就回大门去。}
#{1124}{}{I don't know you. Around here, that means you'd better mind your manners. Now get the hell out of here!}
{1124}{}{我不认识你。在这里，你最好注意礼貌。现在给我滚出去！}
#{1125}{}{Okay, that's it! Get her!}
{1125}{}{好了，就这样！抓住她！}
#{1152}{}{[His hand goes for his gun] Ma'am, you can't be here. Leave the corridor, now.}
{1152}{}{[他的手去拿枪]女士，你不能在这里。现在离开走廊。}
#{1153}{}{I just wanted to see your boss...}
{1153}{}{我只是想见你老板。。。}
