#{100}{}{You see Michael the bartender.}
{100}{}{你看到调酒师迈克尔了。}
#{101}{}{This is Michael. His name is written on a worn-out badge on his shirt.}
{101}{}{我是迈克尔。他的名字写在他衬衫上破旧的徽章上。}
#{102}{}{Want a drink before the fight?}
{102}{}{打斗前想喝一杯吗？}
#{103}{}{Speaking of fights, can I place a bet?}
{103}{}{说到打架，我能打赌吗？}
#{104}{}{Speaking of fights, can I participate?}
{104}{}{说到打架，我能参加吗？}
#{105}{}{Sure, show me what you've got.}
{105}{}{当然，给我看看你有什么。}
#{106}{}{Nope, I'm going to go.}
{106}{}{不，我要走了。}
#{107}{}{That's it?}
{107}{}{就这样？}
#{108}{}{Another question.}
{108}{}{另一个问题。}
#{109}{}{Bye.}
{109}{}{再见。}
#{110}{}{We've got a guy for that. He accepts bets right before the fights start, see him then.}
{110}{}{我们已经找到一个人了。他在比赛开始前就接受了赌注，到时候见。}
#{111}{}{I doubt it... But anyway, it's not up to me. Take the hall on your right into the gym, then head up to the boss's office. Talk to him.}
{111}{}{我怀疑。。。但不管怎样，这不取决于我。从你右边的大厅进入健身房，然后前往老板办公室。和他谈谈。}
#{112}{}{Who's in the ring right now?}
{112}{}{现在谁在拳击场？}
#{113}{}{Hell if I know. Some tribals from the wastes. They're brought in from time to time by slavers. They're replaced so quickly, I don't even try to remember their names. And why should I? They're just meat. [he shrugs indifferently]}
{113}{}{如果我知道的话。从废物中得到的一些部落。他们不时被奴隶贩子带进来。他们很快就被替换了，我甚至都不记得他们的名字。我为什么要这么做？它们只是肉。[他冷漠地耸耸肩]}
#{114}{}{I'm looking for the girl in this picture. Ever seen her around here?}
{114}{}{我在找照片里的女孩。在这附近见过她吗？}
#{115}{}{Nope, don't think I have, but her body seems familiar... Weird, how could a body be familiar? [he screws up his face, scratching his head] Maybe from the night club? Oh yeah! I'm not really sure, but I think I saw her dancing there. A body like that... [he looks like he's about to start drooling]}
{115}{}{不，我想我没有，但她的身体看起来很熟悉。。。奇怪，一具尸体怎么会很熟悉？[他把脸弄得一团糟，挠头]也许是从夜总会来的？哦，是的！我不太确定，但我想我看到她在那儿跳舞了。像这样的尸体。。。[他看起来要流口水了]}
#{116}{}{I heard you had a guy running dope here. I really need some, you dig?}
{116}{}{我听说你有个家伙在这里经营毒品。我真的需要一些，明白吗？}
#{117}{}{Are you okay? What dealers?!}
{117}{}{你没事吧？什么经销商？！}
#{118}{}{These dealers. [show note]}
{118}{}{这些经销商。[显示注释]}
#{119}{}{Hm... You're right. Jackson must have screwed up.}
{119}{}{嗯。。。你说得对。杰克逊一定是搞砸了。}
#{120}{}{Ah, yeah, I heard something like that. Shady guys, made some deals before leaving. But Mr. Bishop kicked them all out.}
{120}{}{啊，是的，我听到了这样的话。见不得人的家伙，在离开前做了些交易。但毕晓普先生把他们全都赶了出去。}
#{121}{}{Got it.}
{121}{}{知道了。}
#{122}{}{Good to see you, champion.}
{122}{}{很高兴见到你，冠军。}
#{1102}{}{Want a drink before the fights, friendo?}
{1102}{}{打架前想喝一杯吗，朋友？}
#{1122}{}{Good to see you, champion.}
{1122}{}{很高兴见到你，冠军。}
