#{110}{}{Our boss says hello.}
{110}{}{我们老板打招呼。}
#{111}{}{You again?! I'm sick of seeing you!}
{111}{}{又是你？！我讨厌见到你！}
#{112}{}{Now, now, calm down. Aren't people trying to sleep here?}
{112}{}{现在，现在，冷静。人们不想睡在这里吗？}
#{113}{}{Heh-heh... Yeah! You get too excited, and we might just -}
{113}{}{嘿嘿。。。是 啊！你太兴奋了，我们可能-}
#{114}{}{Hold on a second. Who the hell is this?}
{114}{}{等一下。这到底是谁？}
#{115}{}{Who, me?}
{115}{}{谁，我？}
#{116}{}{This is my bodyguard. I'd suggest you go tell your boss the answer is still no.}
{116}{}{这是我的保镖。我建议你去告诉你老板答案仍然是否定的。}
#{117}{}{Fine... Fine. But we will be back.}
{117}{}{好的。。。好的。但我们会回来的。}
#{118}{}{Yeah! We'll be back!}
{118}{}{是 啊！我们会回来的！}
#{119}{}{And you, boy... Find a new job. Heroes don't live long in this city.}
{119}{}{你呢，孩子。。。找一份新工作。英雄在这个城市活不了多久。}
#{120}{}{What just happened?}
{120}{}{刚才发生了什么？}
#{121}{}{Forget it. This is not your business. Don't get involved.}
{121}{}{算了吧。这不关你的事。别扯进来。}
#{122}{}{You think you've just interrupted a shakedown.}
{122}{}{你以为你刚刚打断了一场洗牌。}
#{1115}{}{Who, me?}
{1115}{}{谁，我？}
#{1119}{}{And you, girl... Find a new job. Heroes don't live long in this city.}
{1119}{}{而你，女孩。。。找一份新工作。英雄在这个城市活不了多久。}
