#{100}{}{You see Lewis Mordino.}
{100}{}{你看刘易斯·摩迪诺。}
#{101}{}{You see a tired owner of "Silver" hotel.}
{101}{}{你看到一个疲惫的“银”旅馆老板。}
#{102}{}{Look, I have suffered enough, just leave me alone.}
{102}{}{听着，我受够了，别管我。}
#{106}{}{I'm listening.}
{106}{}{我在听。}
#{107}{}{You're the owner here? Tell me how it all started, please.}
{107}{}{你是这里的主人？请告诉我这一切是怎么开始的。}
#{108}{}{You've gotta know a lot about this city, right? Please, tell me about it.}
{108}{}{你对这个城市一定很了解吧？请告诉我。}
#{109}{}{Bye.}
{109}{}{再见。}
#{110}{}{What did those guys want?}
{110}{}{那些家伙想要什么？}
#{111}{}{Forget it, it does not concern you.}
{111}{}{算了吧，这与你无关。}
#{112}{}{Oh no, you called me your bodyguard. That makes me involved, from where I'm standing.}
{112}{}{哦不，你叫我保镖。从我的立场来看，这让我参与其中。}
#{113}{}{Hmm, is that so? Fine. Let's start from the beginning.}
{113}{}{嗯，是这样吗？好的。让我们从头开始。}
#{114}{}{Hmm. My apologies. But please understand, there is a war waging in the city. You won't be affected by it, as long as you keep to yourself and steer clear of it. Do you understand?}
{114}{}{嗯。我道歉。但是请理解，这座城市正在打仗。你不会受到它的影响，只要你保持对自己和远离它。你明白吗？}
#{115}{}{War? Tell me about it!}
{115}{}{战争？可不是吗！}
#{116}{}{There's a war between the business leaders, for about ten years now. The conflict got a lot bloodier about six years ago. Some idiot invited gangs of raiders to bring an end to it all. But the raiders made their own deal - and shifted the authority.}
{116}{}{商界领袖之间有一场战争，已经有十年了。大约六年前，冲突变得更加血腥。一些白痴邀请了一帮袭击者来结束这一切。但是袭击者做了他们自己的交易-并且转移了权力。}
#{117}{}{[Next]}
{117}{}{[下一步]}
#{118}{}{The problem is that these raiders cannot even agree amongst themselves. As a result, the city fell into a deep coma for a few years - the crisis is economic and social: street robbery, lack of food and a whole heap of problems. Only God knows what was on the mind of the person who started it all, but the current government is clearly unable to deal with any of things going on.}
{118}{}{问题是这些袭击者之间甚至无法达成一致。结果，这座城市陷入了几年的深度昏迷——危机是经济和社会方面的：街头抢劫、缺乏食物和一大堆问题。只有上帝知道这一切的始作俑者是怎么想的，但现在的政府显然无法处理任何正在发生的事情。}
#{119}{}{Which side are you on?}
{119}{}{你站在哪一边？}
#{120}{}{On my own. As everybody in this city is, really. Yet some do think it is easier to join some gang. I'm trying to stay away from all the conflict and to live a simple businessman's life. Therefore, I do not care who is at the helm of it all. As long as he doesn't put pressure on my way of living, he can sail as he likes.}
{120}{}{我一个人。就像这个城市的每个人一样，真的。但也有人认为加入帮派更容易。我试着远离所有的冲突，过一种简单的商人生活。因此，我不在乎谁在掌舵这一切。只要他不给我的生活方式带来压力，他就可以随心所欲地航行。}
#{121}{}{Right. Thanks for the clarification.}
{121}{}{正确的。谢谢你的澄清。}
#{130}{}{Well then, welcome to Reno! A truly breathing and bustling city, the Babylon of this hellscape we live in. If you'd like to stay longer, you can have a room. Talk to the receptionist, he's far more talkative when it comes to city's history.}
{130}{}{那么，欢迎来到雷诺！一个真正的呼吸和熙熙攘攘的城市，我们生活在这个地狱景观的巴比伦。如果你想住久一点，你可以住一个房间。和接待员谈谈，他在谈到城市历史时更健谈。}
#{131}{}{Well, I got this hotel through my inheritance, but for a long time the building was empty. When New Reno became an active trade center with all the other settlements, there was an influx of caravan merchants. This created the problem of the rowdy and displaced caravan merchants with no place to spend the night. Since I like to learn more about the good people from other parts of the wasteland, I gladly opened the doors of this here hotel, and the rest is, as they say, history.}
{131}{}{好吧，我继承了这家旅馆，但很长一段时间这座楼都空着。当新雷诺成为一个活跃的贸易中心与所有其他定居点，有一个大篷车商人涌入。这就造成了一个问题，即喧闹和流离失所的商队商人没有地方过夜。因为我喜欢更多地了解荒原上其他地方的好人，所以我很高兴地打开了这家旅馆的门，其余的正如他们所说，都是历史了。}
#{132}{}{Let's talk about something else.}
{132}{}{我们再谈点别的吧。}
#{140}{}{Hey. Ya know, I've heard some rumors that you and the bikers are old friends. Like, say, Jay Kukish?}
{140}{}{嘿。你知道吗，我听说你和摩托车手是老朋友了。比如说，杰伊·库基什？}
#{141}{}{I do not hide that I like those guys. We often share a few beers and stories when they're in town. But Jay is not like the other bikers. He's fixated on technology and not at all talkative. Even among his own, he is considered an odd one.}
{141}{}{我不隐瞒我喜欢那些家伙。当他们在城里时，我们经常分享一些啤酒和故事。但是杰伊不像其他的摩托车手。他专注于技术，一点也不健谈。即使在他自己的人当中，他也被认为是个怪人。}
#{142}{}{They say Jay rode through Reno recently. Is this true?}
{142}{}{他们说杰伊最近骑过雷诺。这是真的吗？}
#{143}{}{He stayed for the night and left in the morning. Obviously, he was in a real hurry. His eyes had this sparkle in them. Most likely, he found something special, but he didn't tell me jack shit about what it was.}
{143}{}{他住了一夜，早上就走了。显然，他真的很匆忙。他的眼睛闪闪发光。很可能，他发现了一些特别的东西，但他没有告诉我那是什么。}
#{144}{}{I know what's that sparkle is about. I need to contact him immediately, before it's too late!}
{144}{}{我知道那闪光是什么意思。我要马上联系他，免得太迟了！}
#{145}{}{Are you sure? These are not kind of people, who would listen to you if they don't like you. Not that it matters now. The bikers, last I checked, were migrating to the south-east. They didn't explain why or where they were going. Therefore, there is only one way to find out where they are now - contacting them through a very good radio equipment. Which is where I give you good and bad news; good news is that the city does have one suitable station you could use. The bad news - it is located in an old bunker under Stryker building, and the entrance to it is locked.}
{145}{}{你确定？如果他们不喜欢你，他们不会听你的。现在不重要了。我最后一次查到，骑自行车的人正在向东南部迁移。他们没有解释他们要去的原因和地点。因此，只有一种方法可以找到他们现在在哪里-通过一个非常好的无线电设备与他们联系。这就是我告诉你好消息和坏消息的地方；好消息是这个城市确实有一个合适的车站，你可以使用。坏消息是，它位于史崔克大楼下的一个旧地堡里，入口是锁着的。}
#{146}{}{That won't stop me. Do you know the call signs and channels I could use to contact them?}
{146}{}{这不能阻止我。你知道我可以用来联系他们的呼号和频道吗？}
#{147}{}{That, I've never known. Bikers use their own call signs and communication channels, so that no one can track them down.}
{147}{}{我从来都不知道。骑自行车的人使用自己的呼号和通讯渠道，这样就没有人能追踪到他们。}
#{148}{}{I think I may have come across those codes before. Thank you, and good bye.}
{148}{}{我想我以前可能遇到过这些代码。谢谢，再见。}
#{149}{}{I need to contact Jay before it's too late!}
{149}{}{我要在太迟之前联系杰伊！}
#{160}{}{My boss, Mr. Thompson, is losing patience with your stupidity.}
{160}{}{我的老板汤普森先生对你的愚蠢失去了耐心。}
#{161}{}{I said all I needed to say the last time we spoke, I'm my own boss. You're gonna find a very good reason to change my mind on that fact.}
{161}{}{上次我们谈话的时候我只想说，我是我自己的老板。你会找到一个很好的理由让我改变主意的。}
#{162}{}{Give me time to think.}
{162}{}{给我时间想想。}
#{163}{}{Perhaps we can make a deal? What are you afraid of?}
{163}{}{也许我们可以做笔交易？你害怕什么？}
#{164}{}{Wow - the diplomatic approach after all the intimidation and thugs? If Thompson decided to change the approach to a more delicate one, we could eventually come to a mutual understanding. But I'll never change my core beliefs. I'm a *free* businessman. Now, prove to me that aligning with Thompson is more beneficial to me than with Stryker or anyone else.}
{164}{}{哇-在所有的恐吓和暴徒之后的外交手段？如果汤普森决定把办法改为更微妙的办法，我们最终可以达成相互谅解。但我永远不会改变我的核心信念。我是个自由的商人。现在，向我证明，与汤普森结盟比与史崔克或其他任何人结盟对我都更有利。}
#{165}{}{I managed to get a recording of one Stryker's meetings. He called you a stubborn fool and plans to replace you, after he seizes power.}
{165}{}{我设法弄到了史崔克会议的录音。他称你为顽固的傻瓜，并计划取代你后，他夺权。}
#{166}{}{[Frowns] Stubborn - that's right. But with the rest I can not agree. Besides, Thompson has more chances to seize power in the city. Hmm...}
{166}{}{[皱眉]固执-没错。但其余的我不同意。此外，汤普森有更多的机会夺取权力的城市。隐马尔可夫模型。。。}
#{167}{}{So what is the final answer to my boss?}
{167}{}{那么，对我的老板来说，最后的答案是什么呢？}
#{168}{}{}
{168}{}{}
#{169}{}{}
{169}{}{}
#{170}{}{Hey, Daddy-o! They say that your little wife's titties aren't that bad, eh? Heh-heh...}
{170}{}{嘿，爸爸！他们说你小老婆的奶子没那么坏，嗯？嘿嘿。。。}
#{171}{}{[Mordino remains silent for some time, eyes lowered] Wh-what... Do you want...}
{171}{}{[摩迪诺沉默了一段时间，眼睛低着]什么。。。你想。。。}
#{172}{}{Nothing much. Mr. Thompson wants protection money, for you to cut any ties with Stryker, and use of the second-floor rooms for surveillance. Now choose.}
{172}{}{没什么。汤普森先生想要保护费，让你切断与史崔克的任何联系，并利用二楼的房间进行监视。现在选择。}
#{173}{}{[Long silence] I... Agree...}
{173}{}{[长时间的沉默]我。。。同意。。。}
#{174}{}{Finally. I'll pass that on to him. He'll want to meet you, so be ready.}
{174}{}{最后。我把这个传给他。他想见你，所以准备好了。}
#{175}{}{[Show him Mrs. Mordino's finger] You know what this means?}
{175}{}{[让他看看摩迪诺夫人的手指]你知道这是什么意思吗？}
#{176}{}{My boss is fed up with you. Either you cooperate, or you go the same way as Stryker. No more warnings.}
{176}{}{我老板受够你了。要么你合作，要么你和史崔克走同一条路。不再发出警告。}
#{177}{}{Stryker is dead? Hmm... I had thought this fight would never end. Well, then I don't really have a choice.}
{177}{}{史崔克死了？隐马尔可夫模型。。。我原以为这场战斗永远不会结束。好吧，那我真的没有选择。}
#{178}{}{Now choose.}
{178}{}{现在选择。}
#{180}{}{Would a distinguished gentleman like yourself be interested in some fine personal grooming products?}
{180}{}{像你这样的尊贵绅士会对一些精致的个人美容产品感兴趣吗？}
#{181}{}{[He curiously examines your things] Oh my God, that's a full "Pretty & Glamour" body care kit! Impressive. I've given many of these kits over the years, but when supplies ran low I had to keep them for the hotel. This kit could really help me out!}
{181}{}{[He curiously examines your things] Oh my God, that's a full "Pretty & Glamour" body care kit! Impressive. I've given many of these kits over the years, but when supplies ran low I had to keep them for the hotel. This kit could really help me out!}
#{182}{}{[Next]}
{182}{}{[下一步]}
#{183}{}{I'll be happy to buy this collection. How much do you want for it?}
{183}{}{我很乐意买这个系列。你想要多少钱？}
#{184}{}{$2000}
{184}{}{$2000}
#{185}{}{$1500}
{185}{}{$1500}
#{186}{}{$1000}
{186}{}{$1000}
#{187}{}{Hmm, I haven't really thought about it. Give me a hot minute to think it over and I'll discuss the price with you.}
{187}{}{嗯，我还没想过呢。给我一分钟时间考虑一下，我会和你讨论价格的。}
#{188}{}{That's far too much for just one kit! You'll have to lower the price.}
{188}{}{一套就够了！你得降低价格。}
#{189}{}{Uh, no, I'll just find customers who can afford it. Bye.}
{189}{}{呃，不，我会找到买得起的顾客。再见。}
#{190}{}{Well, that price seems about right. It's worth it. I'll take it.}
{190}{}{嗯，这个价格似乎差不多。这是值得的。我要了。}
#{191}{}{Excellent! Let's trade.}
{191}{}{杰出的！我们交易吧。}
#{192}{}{You know, I've changed my mind. Bye.}
{192}{}{你知道，我改变主意了。再见。}
#{193}{}{I don't need jokes right now. No.}
{193}{}{我现在不需要笑话。不。}
#{194}{}{Sorry, won't happen again.}
{194}{}{对不起，不会再发生了。}
#{200}{}{Did you know that someone is rigging the machines in the casino?}
{200}{}{你知道有人在赌场操纵机器吗？}
#{201}{}{What the hell did you just say! Our casino is the most honest one in the whole city.}
{201}{}{你刚才说什么！我们的赌场是全市最诚实的赌场。}
#{202}{}{Maybe so. But there is evidence that one of the machines has an additional counter. Strange, ain't it?}
{202}{}{也许是吧。但有证据表明其中一台机器有一个额外的计数器。很奇怪，不是吗？}
#{203}{}{Hmm. Well, I'll have to have one of my assistants check the machines. Just so our conscience stays clean.}
{203}{}{嗯。好吧，我得让我的一个助手检查一下机器。只是为了让我们的良心保持清白。}
#{204}{}{And what about the money lost by players?}
{204}{}{玩家损失的钱呢？}
#{205}{}{Nonsense! We will not return the money to anyone, even if you *do* find that one of the workers at the casino really is a swindler. We do won't know who lost money because of him, or even if we did, how much they lost was due to him. Now let me now go give instructions to my workers.}
{205}{}{胡说！我们不会把钱还给任何人，即使你发现赌场的一个工人真的是骗子。我们不知道是谁因为他损失了钱，或者即使我们损失了，他们损失了多少钱都是因为他。现在让我去指示我的工人。}
#{206}{}{Is that, so...}
{206}{}{是吗，所以。。。}
#{1187}{}{Hmm, I haven't really thought about it. Give me a hot minute to think it over and discuss the price with you.}
{1187}{}{嗯，我还没想过呢。给我一分钟时间考虑一下，然后和你讨论价格。}
#{1192}{}{You know, I've changed my mind. Bye.}
{1192}{}{你知道，我改变主意了。再见。}
