#{100}{}{This switchboard seems to control power to the entire second floor of the casino.}
{100}{}{这个配电盘似乎控制着整个赌场二楼的电源。}
#{101}{}{The electrical panel's cover is closed with a padlock.}
{101}{}{配电板的盖子是用挂锁锁上的。}
#{102}{}{There's a lot of current running through these wires. You probably shouldn't touch them with your bare hands.}
{102}{}{有很多电流流过这些电线。你可能不应该徒手触摸它们。}
#{103}{}{The second floor's lighting has been turned off.}
{103}{}{二楼的灯已经关了。}
#{104}{}{The second floor's lighting has been turned on.}
{104}{}{二楼的灯已经打开了。}
#{105}{}{You can stand here all day, but this panel won't open itself.}
{105}{}{你可以站在这里一整天，但这个面板不会自动打开。}
#{110}{}{The lock is broken already.}
{110}{}{锁已经坏了。}
#{111}{}{The lock holds strong against you.}
{111}{}{这把锁对你很紧。}
#{112}{}{You easily break the lock.}
{112}{}{你很容易把锁打破。}
#{113}{}{This keyhole lock is closed.}
{113}{}{这个锁孔是关着的。}
#{114}{}{Locked by key.}
{114}{}{用钥匙锁着。}
#{115}{}{The lock is open.}
{115}{}{锁是开着的。}
#{116}{}{You have unlocked the lock.}
{116}{}{你把锁打开了。}
