#{100}{}{You see a slot machine.}
{100}{}{你看到老虎机了。}
#{101}{}{You see a slot machine with flashing lights.}
{101}{}{你看到一个有闪光灯的老虎机。}
#{102}{}{This slot machine is currently occupied.}
{102}{}{此老虎机当前已被占用。}
#{103}{}{You get nothing from the machine.}
{103}{}{你从机器里什么也得不到。}
#{104}{}{This machine is in working order.}
{104}{}{这台机器运转正常。}
#{105}{}{Nothing.}
{105}{}{没有什么。}
#{106}{}{An ordinary slot machine, the same as every other one in this room.}
{106}{}{一台普通的老虎机，和这个房间里的其他老虎机一样。}
#{107}{}{You inspect the machine and find the reason behind high loss rate: someone misaligned the spinners, reducing the chances of a win.}
{107}{}{你检查机器，发现损失率高背后的原因：有人调整了纺纱机，降低了获胜的机会。}
#{108}{}{This explains everything!}
{108}{}{这就解释了一切！}
