#{100}{}{You see Evan.}
{100}{}{你看到埃文了。}
#{101}{}{You see Evan, a hardened trapper.}
{101}{}{你看埃文，一个冷酷的捕猎者。}
#{102}{}{}
{102}{}{}
#{103}{}{Head back to the village, I'll catch up.}
{103}{}{回村子去，我会赶上的。}
#{110}{}{There's a gecko nest in this cave, one of a few in the area. It'll be swarming with them, so be careful. If you're quick and quiet, you shouldn't have too much trouble.}
{110}{}{这个洞穴里有一个壁虎窝，是这个地区少数几个壁虎窝之一。他们会蜂拥而至的，所以要小心。如果你又快又安静，你就不应该有太多麻烦。}
#{111}{}{My job is to collect the eggs, right?}
{111}{}{我的工作是收集鸡蛋，对吗？}
#{112}{}{...without wiping out gecko's population, yeah. Keep at least half of them alive, or we won't have anything to eat next season.}
{112}{}{…不消灭壁虎的数量，是的。至少让一半的人活着，否则下一季我们就没有东西吃了。}
#{113}{}{You can count on me.}
{113}{}{你可以相信我。}
#{114}{}{I'll be waiting for you by the exit at the other side of a cave. Be careful and try not to run off in fear. You'll be shamed all over settlement. Won't lend you a helping hand then.}
{114}{}{我会在山洞另一边的出口等你。小心点，别害怕跑掉。你会被整个定居点蒙羞的。我不会帮你的。}
#{115}{}{I'll see you.}
{115}{}{再见。}
#{120}{}{That was quick. How's the hunt? Any luck?}
{120}{}{太快了。狩猎怎么样？有什么进展吗？}
#{121}{}{I'm just getting some fresh air. I'll be right back with the eggs.}
{121}{}{我只是呼吸点新鲜空气。我马上回来拿鸡蛋。}
#{122}{}{I heard screams! What the hell is going on in there?}
{122}{}{我听到尖叫声！里面到底发生了什么？}
#{123}{}{Things got messy, but I managed to get the eggs.}
{123}{}{事情变得一团糟，但我设法弄到了鸡蛋。}
#{124}{}{I'll explain later. Right now, I have to go back inside.}
{124}{}{我稍后再解释。现在，我得回去了。}
#{125}{}{I got the eggs. Are these enough?}
{125}{}{我拿到鸡蛋了。这些够了吗？}
#{126}{}{What?! Aww, I knew I shouldn't have trusted this to a rookie! We should be okay if you only killed a few, but if you wiped out more than half the pack...}
{126}{}{什么？！啊，我就知道我不该把这个交给菜鸟！如果你只杀了几个人我们会没事的，但是如果你消灭了一半以上的人。。。}
#{127}{}{Um, and the eggs?}
{127}{}{嗯，鸡蛋呢？}
#{128}{}{Show me.}
{128}{}{向我展示。}
#{129}{}{[Open the backpack]}
{129}{}{[打开背包]}
#{130}{}{I can get more. Wait here.}
{130}{}{我可以得到更多。在这里等着。}
#{131}{}{That's it? Listen, they won't send a caravan unless we have at least ten eggs. Any less than that, and we're wasting our time.}
{131}{}{就这样？听着，除非我们至少有十个鸡蛋，否则他们不会派大篷车。再少一点，我们就是在浪费时间。}
#{132}{}{Right...}
{132}{}{正确的。。。}
#{135}{}{That's enough, give them to me. Time to hurry back to village, before we get noticed.}
{135}{}{够了，给我。在我们被注意到之前，该赶紧回村子了。}
#{136}{}{[Give him all eggs]}
{136}{}{[把鸡蛋都给他]}
#{137}{}{Wait, hold on. I'm the one who risked my skin for these eggs. Why shouldn't I just take them and sell them myself?}
{137}{}{等等，等等。我是那个拿我的皮肤冒险去买这些蛋的人。我为什么不自己把它们卖了呢？}
#{138}{}{I'll try to get more, then.}
{138}{}{那我再多弄点。}
#{139}{}{Hey, careful with those! They're fragile!}
{139}{}{嘿，小心那些！他们很脆弱！}
#{140}{}{Okay, fine...}
{140}{}{好吧，好吧。。。}
#{141}{}{[Evan carefully wraps the eggs and packs them in skins and reeds for protection] Okay, done. We can go back now.}
{141}{}{[埃文小心地把鸡蛋包起来，用皮和芦苇包起来]好的，好的。我们现在可以回去了。}
#{142}{}{[Return to the settlement]}
{142}{}{[返回营地]}
#{143}{}{[He frowns] I made all this way here not to quarrel with you at the last moment. I've been teaching, you, you've been learning. Consider this as a payment for my work.}
{143}{}{[他皱眉]我到这儿来是为了在最后一刻不跟你吵架。我一直在教书，你，你一直在学习。把这当作我工作的报酬。}
#{144}{}{Fuck you, old man. These eggs are mine!}
{144}{}{去你妈的，老头子。这些蛋是我的！}
#{145}{}{That's fair. Take them.}
{145}{}{这很公平。拿着它们。}
#{146}{}{You - !! [he grits his teeth] Keep the damn eggs. I don't want to see your face again!}
{146}{}{你-！！[他咬紧牙关]把那些该死的蛋留下。我不想再看到你的脸！}
#{147}{}{The feeling's mutual. Get your ass out of here.}
{147}{}{这种感觉是相互的。滚出去。}
#{148}{}{Hey, don't get upset, I'll walk peacefully...}
{148}{}{嘿，别生气，我会平静地走。。。}
#{149}{}{The hunt is over.}
{149}{}{狩猎结束了。}
#{150}{}{You left Evan in the middle of the hunt. This won't be good for your reputation in Gerlach.}
{150}{}{你把埃文留在了追捕过程中。这对你在格拉赫的名声不好。}
#{151}{}{[He looks at you thoughtfully] ...you know, you did a damn good job today. I think you've earned a reward. [he counts out ten eggs, then hands you the rest] Remember, they'll pay a lot more for these in Reno, than you can get here.}
{151}{}{[他若有所思地看着你]…你知道，你今天做得非常好。我想你已经得到了回报。[他数了十个鸡蛋，然后把剩下的递给你]记住，在里诺他们会花很多钱买这些，比你在这里能买到的多得多。}
#{152}{}{How many eggs should I bring?}
{152}{}{我应该带多少个鸡蛋？}
#{153}{}{At least ten. No less!}
{153}{}{至少十个。一点也不！}
#{1125}{}{I got the eggs. Are these enough?}
{1125}{}{我拿到鸡蛋了。这些够了吗？}
#{1128}{}{Show me.}
{1128}{}{向我展示。}
#{1137}{}{Wait, hold on. I'm the one who risked my skin for these eggs. Why shouldn't I just take them and sell them myself?}
{1137}{}{等等，等等。我是那个拿我的皮肤冒险去买这些蛋的人。我为什么不自己把它们卖了呢？}
