#{100}{}{A tribal woman.}
{100}{}{部落妇女。}
#{101}{}{A Cheyenne woman working in the field.}
{101}{}{在田里干活的夏延妇女。}
#{102}{}{Awrite.}
{102}{}{阿怀特。}
#{103}{}{Me move.}
{103}{}{让我动起来。}
#{104}{}{You rude!}
{104}{}{你太粗鲁了！}
#{105}{}{Sky Mother protect me!}
{105}{}{天空母亲保护我！}
#{106}{}{No push!}
{106}{}{不要推！}
#{107}{}{You is glad me husband no see!}
{107}{}{你很高兴我老公不见了！}
#{108}{}{Go push gecko!}
{108}{}{去推壁虎！}
#{109}{}{Push me again - you regret!}
{109}{}{再推我一次-你后悔了！}
#{110}{}{Me scratch out you eyes!}
{110}{}{我把你的眼睛划破！}
#{111}{}{Help!!!}
{111}{}{救命！！！}
#{112}{}{Me no talk.}
{112}{}{别跟我说话。}
#{113}{}{Me watch crops and kids.}
{113}{}{我看着庄稼和孩子。}
#{114}{}{Uh...me no chatting.}
{114}{}{呃…别跟我聊天。}
#{115}{}{Go talk Ogima Black Cloud.}
{115}{}{去和乌云谈谈。}
#{116}{}{What you eat?}
{116}{}{你吃什么？}
#{117}{}{You awrite friend?}
{117}{}{你是我的朋友吗？}
#{118}{}{You look what?}
{118}{}{你看起来怎么样？}
#{119}{}{Me no like. Go!}
{119}{}{我不喜欢。快走！}
