#{100}{}{You see a raider.}
{100}{}{你看到一个袭击者。}
#{101}{}{You see a mean-looking, unwashed thug.}
{101}{}{你看到一个看起来很卑鄙，没洗衣服的暴徒。}
#{200}{}{Hey, you!}
{200}{}{嘿，你！}
#{201}{}{Kill the motherfucker!}
{201}{}{杀了他妈的！}
#{202}{}{Don't make it too quick! I wanna see 'em squirm!}
{202}{}{别开得太快！我要看他们蠕动！}
#{203}{}{Twenty bucks says I can make it a headshot!}
{203}{}{二十块钱说我能把它当头像！}
#{204}{}{Come on! Let's dance!}
{204}{}{加油！我们跳舞吧！}
#{205}{}{You better start digging your grave, you brahmin shit!}
{205}{}{你最好开始挖你的坟墓，你这个婆罗门混蛋！}
#{206}{}{Stand still! Let's get this over with!}
{206}{}{站住！让我们结束这一切！}
#{207}{}{Get over here! I'ma fuck you like I did your mother!}
{207}{}{过来！我要和你妈一样操你！}
#{208}{}{KILL 'EM ALL!}
{208}{}{把他们都杀了！}
#{210}{}{::spit::}
{210}{}{●吐痰：}
#{211}{}{I'm not looking for friends.}
{211}{}{我不是在找朋友。}
#{212}{}{Piss off.}
{212}{}{滚开。}
#{213}{}{I'm bored. Hey, you! Entertain me.}
{213}{}{我很无聊。嘿，你！娱乐我。}
#{214}{}{You looking at me? Get out of here, then.}
{214}{}{你看着我？那就离开这里。}
#{215}{}{I like your boots. Take 'em off.}
{215}{}{我喜欢你的靴子。把它们脱下来。}
#{216}{}{Big Daddy says you're alright. For now.}
{216}{}{大爸爸说你没事。现在。}
#{217}{}{Hey. What's up?}
{217}{}{嘿。怎么了？}
#{218}{}{Just doing my own thing.}
{218}{}{只是做我自己的事。}
#{219}{}{If you see a fight, call me.}
{219}{}{如果你看到打架，打电话给我。}
#{220}{}{You're pretty tight with the boss, huh?}
{220}{}{你和老板关系很好，是吗？}
#{221}{}{How's the boss? All good?}
{221}{}{老板怎么样了？一切都好吗？}
#{222}{}{Everything's quiet. The boss can sleep easy.}
{222}{}{一切都很安静。老板可以睡得安稳。}
#{223}{}{You need anything, just ask.}
{223}{}{你需要什么，就问吧。}
#{224}{}{Boss really likes you. I wonder how it feels...}
{224}{}{老板真的很喜欢你。我想知道感觉如何。。。}
