#{100}{}{Moonshine still.}
{100}{}{月光照旧。}
#{101}{}{You see a still. It has already distilled a whole can of moonshine!}
{101}{}{你看到一个静物台。它已经蒸馏出一整罐私酒了！}
#{102}{}{You see a still. The brew in it isn't ready yet.}
{102}{}{你看到一个静物台。里面的酒还没煮好。}
#{103}{}{You see a still. Abandoned and useless.}
{103}{}{你看到一个静物台。被遗弃和无用。}
#{104}{}{The still is empty.}
{104}{}{蒸馏器是空的。}
#{105}{}{Empty}
{105}{}{空的}
#{106}{}{That's not for you! Don't try Jackson's patience while he's near you.}
{106}{}{那不是给你的！当杰克逊在你身边时，不要考验他的耐心。}
#{107}{}{Just try it again - and you'll have a problem!}
{107}{}{再试一次-你会有问题的！}
#{108}{}{Done!}
{108}{}{完成！}
#{109}{}{You've expropriated a couple of bottles of booze.}
{109}{}{你没收了几瓶酒。}
#{110}{}{You've boldly stolen a couple of bottles of booze.}
{110}{}{你居然偷了几瓶酒。}
#{111}{}{The moonshine hasn't been distilled yet. Wait a couple of hours.}
{111}{}{私酒还没有蒸馏。等几个小时。}
#{112}{}{Hey! You shitheads! Which one of you's been chugging my booze? If I ever catch any of you at it, I'll rip your fucking arms off!}
{112}{}{嘿！你们这些混蛋！你们谁喝了我的酒？如果我逮到你们中的任何一个，我会把你们的胳膊撕下来！}
