#{0}{}{.}
{0}{}{.}
#{100}{}{It's a gas release system.}
{100}{}{这是一个气体释放系统。}
#{101}{}{You see an installation designed to release gas into the hangar ventilation system.}
{101}{}{你会看到一个设计用来向机库通风系统释放气体的装置。}
#{102}{}{You can't do this in combat!}
{102}{}{你不能在战斗中这样做！}
#{110}{}{You install a gas cylinder into the system.}
{110}{}{在系统中安装一个气瓶。}
#{111}{}{First cylinder attached}
{111}{}{连接的第一个气缸}
#{112}{}{Second cylinder attached}
{112}{}{连接第二个气缸}
#{113}{}{Third cylinder attached}
{113}{}{连接第三个气缸}
#{114}{}{The installation is fully functional. All that's left is to enter the code and push the button.}
{114}{}{安装功能齐全。只需输入代码并按下按钮。}
#{120}{}{This installation would release poison gas into the ventilation, but it doesn't have a single gas cylinder.}
{120}{}{这个装置会将毒气释放到通风系统中，但它没有一个单独的气瓶。}
#{121}{}{This installation can be run *only* when there are three gas cylinders attached.}
{121}{}{只有在连接了三个气瓶的情况下，才能运行该装置。}
#{122}{}{Needs gas cylinders}
{122}{}{需要气瓶}
#{123}{}{Not enough gas cylinders}
{123}{}{没有足够的气瓶}
#{124}{}{This installation has played its part.}
{124}{}{这个装置发挥了它的作用。}
#{125}{}{Installation useless}
{125}{}{安装无用}
#{126}{}{Finish.}
{126}{}{完成。}
#{127}{}{Enter code.}
{127}{}{输入代码。}
#{128}{}{The apparatus is completely filled. All that's left is to enter the code and push the button.}
{128}{}{仪器已完全充满。只需输入代码并按下按钮。}
#{129}{}{0}
{129}{}{0}
#{130}{}{1}
{130}{}{1}
#{131}{}{2}
{131}{}{2}
#{132}{}{3}
{132}{}{三}
#{133}{}{4}
{133}{}{4}
#{134}{}{5}
{134}{}{5}
#{135}{}{6}
{135}{}{6}
#{136}{}{7}
{136}{}{7}
#{137}{}{8}
{137}{}{8}
#{138}{}{9}
{138}{}{9}
#{139}{}{-more-.}
{139}{}{-更多-。}
#{140}{}{Back.}
{140}{}{回来。}
#{141}{}{Finish.}
{141}{}{完成。}
#{142}{}{Clear.}
{142}{}{清除。}
#{143}{}{ -- }
{143}{}{--}
#{144}{}{Code: }
{144}{}{代码：}
#{145}{}{Code incorrect.}
{145}{}{代码不正确。}
#{146}{}{Finish.}
{146}{}{完成。}
#{147}{}{Clear and start over.}
{147}{}{清除并重新开始。}
#{148}{}{The installation is fully functional. All that's left is to enter the code and push the button.}
{148}{}{安装功能齐全。只需输入代码并按下按钮。}
#{149}{}{Initiate the release.}
{149}{}{启动释放。}
#{150}{}{Code accepted! The installation is ready to run. All that's left to do is push the button.}
{150}{}{代码已接受！安装已准备好运行。剩下要做的就是按下按钮。}
#{151}{}{Warning! Lethal gas is about to be released into the ventilation system. Do you confirm?}
{151}{}{警告！致命气体即将被释放到通风系统中。你确认了吗？}
#{152}{}{Yes.}
{152}{}{对。}
#{153}{}{No, let's do this later.}
{153}{}{不，我们晚点再做。}
#{154}{}{Warning! Lethal gas is about to be released into the ventilation system! Evacuate the premises immediately. You have }
{154}{}{警告！致命气体即将释放到通风系统！立即撤离现场。你有}
#{155}{}{[Run]}
{155}{}{[跑步]}
#{156}{}{[Exit]}
{156}{}{[退出]}
#{157}{}{Warning! }
{157}{}{警告！}
#{158}{}{ seconds till release!}
{158}{}{离释放还有几秒钟！}
#{159}{}{ seconds till release.}
{159}{}{几秒钟后释放。}
#{160}{}{Gas has been released!}
{160}{}{气体已经释放了！}
#{1152}{}{Yes.}
{1152}{}{对。}
