#{100}{}{You see an old acquaintance.}
{100}{}{你看到一个老相识。}
#{101}{}{You see the prisoner from the Wind of War!}
{101}{}{你看到战风中的囚犯了！}
#{102}{}{You have got a hint of the existence of the secret laboratory outside the city.}
{102}{}{你得到了城外秘密实验室存在的线索。}
#{103}{}{Hrrm... Yah... It will be the drunkest state in America... Hrrm...}
{103}{}{人力资源管理。。。是的。。。这将是美国最醉的州。。。人力资源管理。。。}
#{104}{}{Hello there, friend!}
{104}{}{你好，朋友！}
#{110}{}{Heh-Hey! Man! Here you are! I knew you would come here! Let me get you a drink! Hey, bartender! Put it on my tab!}
{110}{}{嘿嘿！伙计！给你！我就知道你会来的！我给你拿杯喝的！嘿，酒保！把它记在我的账上！}
#{111}{}{So, you managed to escape from the Wind of War. Won't they look for you?}
{111}{}{所以，你设法逃离了战争之风。他们不会找你吗？}
#{112}{}{Hey! Those troopers are afraid of even coming near Vegas! Don't worry, buddy! We're safe here.}
{112}{}{嘿！那些骑警甚至害怕接近维加斯！别担心，伙计！我们在这里很安全。}
#{113}{}{They are not very liked here in Vegas?}
{113}{}{他们在维加斯不太受欢迎？}
#{114}{}{They are *hated* here. These bastards are being kicked out from the Clean City immediately at the gates.}
{114}{}{他们在这里被憎恨。这些混蛋马上就要被赶出干净的城市了。}
#{115}{}{What's the reason?}
{115}{}{原因是什么？}
#{116}{}{That's because they think they are tough and that they can do anything. So many of our guys got killed by them on the road between Vegas and the Wind... Oh... Let's have a drink over their grave! [chugs half a bottle of beer]}
{116}{}{那是因为他们认为自己很坚强，什么都能做。很多人在维加斯和风之间的路上被他们杀了。。。哦。。。让我们在他们墓前喝一杯！[喝了半瓶啤酒]}
#{117}{}{Hey! Isn't it too much?}
{117}{}{嘿！是不是太多了？}
#{118}{}{It's all right, mate! *burps*}
{118}{}{没事的，伙计！*打嗝*}
#{119}{}{You already look groggy!}
{119}{}{你看起来已经昏昏欲睡了！}
#{120}{}{Ha-ha-ha! Even drunk I'd knock down anyone! Wanna bet you won't stand too?!}
{120}{}{哈哈哈！即使喝醉了，我也会撞倒任何人！我敢打赌你也不会站起来？！}
#{121}{}{Hey! Stop!}
{121}{}{嘿！住手！}
#{122}{}{Ha-ha-ha! Don't be afraid, buddy! [taps you on the shoulder] in your honor, I'd slaughter everyone! Want me to knife the bartender?!}
{122}{}{哈哈哈！别害怕，伙计！[拍拍你的肩膀]以你的名誉，我会杀了所有人！要我给酒保开刀吗？！}
#{123}{}{Uh... No. I still need him.}
{123}{}{休斯敦大学。。。不，我还需要他。}
#{124}{}{Well... Yeah, he gives me beer too... Yep.}
{124}{}{好。。。是的，他也给我啤酒。。。是的。}
#{125}{}{Gives? Just like that? For free?}
{125}{}{给予？就这样？免费的？}
#{126}{}{Ha! What's the matter, buddy?! You know *who* you're talking to?! [weighty pokes himself in the chest with his thumb] WHO is in front of you?!}
{126}{}{哈！怎么了，伙计？！你知道你在和谁说话吗？！[笨重的拇指戳了戳自己的胸膛]谁在你前面？！}
#{127}{}{Yes. The crank who escaped the death penalty.}
{127}{}{对。逃过死刑的怪人。}
#{128}{}{Uh, no! Hal Wallace himself stands for me. Himself! Personally. He would have saved me from the prison, I'm sure.}
{128}{}{呃，不！哈尔·华莱士本人代表我。他自己！就我个人而言。他肯定会把我从监狱里救出来的。}
#{129}{}{Wow! The owner of this casino?! Why is that?}
{129}{}{哇！赌场的老板？！为什么？}
#{130}{}{Ha! Right, like I'd tell you just like that!}
{130}{}{哈！好吧，就像我告诉你的那样！}
#{131}{}{I won't tell anyone!}
{131}{}{我不会告诉任何人！}
#{132}{}{No-no-no! Don't even ask!}
{132}{}{不，不，不！别问了！}
#{133}{}{Oh, come on! I've saved you!}
{133}{}{哦，来吧！我救了你！}
#{134}{}{Damn! Right, okay! If it's you, I confess - I'm... This, what it's called...}
{134}{}{该死！好的，好的！如果是你，我承认-我。。。这就是所谓的。。。}
#{135}{}{Bodyguard?}
{135}{}{保镖？}
#{136}{}{What? The hell with bodyguard! No...}
{136}{}{什么？去他的保镖！不。。。}
#{137}{}{Administrator?}
{137}{}{管理员？}
#{138}{}{Eh?! Hey, don't confuse me... I'll remember...}
{138}{}{嗯？！嘿，别把我搞糊涂了。。。我会记得。。。}
#{139}{}{Clerk? Warehouseman? Cleaner? Masseur? Who?!}
{139}{}{职员？仓库管理员？清洁剂？按摩师？谁？！}
#{140}{}{Hey, stop it already! Let me remember!.. Ah, Yes! A courier!}
{140}{}{嘿，快住手！让我记住！。。啊，是的！一个信使！}
#{141}{}{Courier? Took you quite long to remember. What's so mysterious about it?}
{141}{}{信使？你花了很长时间才记起。有什么神秘的？}
#{142}{}{Well, you know, it puts me in such places. You'd better not to know. Outside the city.}
{142}{}{好吧，你知道，这让我陷入这样的境地。你最好不要知道。在城外。}
#{143}{}{Now you're being cunning... As if there are people living outside the city.}
{143}{}{现在你很狡猾。。。好像有人住在城外。}
#{144}{}{No, they don't live there. But there you can make some money... [winks and sips the second half of beer]}
{144}{}{不，他们不住在那里。但是在那里你可以赚点钱。。。[眨眼啜饮下半杯啤酒]}
#{145}{}{Oh, that's my department! So where is it, where can I make money?}
{145}{}{哦，那是我的部门！那么它在哪里，我在哪里能赚钱呢？}
#{146}{}{[Not hearing you] Ah, hell, it's over. Hey! Bartender! Give me beer! Now!}
{146}{}{[没听见]啊，见鬼，结束了。嘿！酒保！给我啤酒！现在！}
#{147}{}{[Continue]}
{147}{}{[继续]}
#{148}{}{What are you babbling about, you?! You won't give me beer?! I'm not asking you, I order you!}
{148}{}{你在胡说什么？！你不给我啤酒？！我不是问你，我命令你！}
#{149}{}{Hey, calm down. Let me order you a bottle. Bartender! Put it on my tab!}
{149}{}{嘿，冷静点。我给你订一瓶。酒保！把它记在我的账上！}
#{150}{}{[Leave them alone]}
{150}{}{[别管他们]}
#{151}{}{Pal... No - friend! Yes! Friend, you save me again. This eared creep always refuses to serve me after the second bottle... Oh, yeah, where were we?}
{151}{}{朋友。。。不-朋友！对！朋友，你又救了我。第二瓶酒后，这个长耳朵的家伙总是拒绝招待我。。。哦，是的，我们在哪儿？}
#{152}{}{On the spot outside the city, where one can make some money...}
{152}{}{在城外的地方，一个人可以赚点钱。。。}
#{153}{}{Ah, yes! There, in the laboratory, such big money's being made, oh gosh! For one serving... [looks like he'll be asleep soon] for a single dose they receive... Dose... Zzzz...}
{153}{}{啊，是的！在实验室里，赚了这么多钱，天哪！一份服务。。。[看起来他很快就要睡着了]只要给他们一剂。。。剂量。。。Zzzz。。。}
#{154}{}{[You can't hook out anything from him now]}
{154}{}{[你现在不能从他那里弄到任何东西]}
#{200}{}{Yeah, take care.}
{200}{}{是的，保重。}
#{201}{}{Friend, you said you work for the casino owner. Could you recommend me?}
{201}{}{朋友，你说你为赌场老板工作。你能推荐我吗？}
#{202}{}{[Nervously looks around] Uh, listen, my advice to you - go to work as a janitor. At the Hoover dam, for example, there are not enough slaves to do the work. Mr. Wallace needs experienced people, you don't look like you have a proper level of expertise.}
{202}{}{[紧张地环顾四周]呃，听着，我给你的建议是——去做个看门人。例如，在胡佛大坝，没有足够的奴隶来做这项工作。华莱士先生需要有经验的人，你看起来没有足够的专业知识。}
#{203}{}{Am I that bad? Oh, well...}
{203}{}{我有那么坏吗？哦，好吧。。。}
#{204}{}{[Nervously looks around] Look, I'll tell you seriously - Mr. Wallace offers... *tough* work, not for those who like their hands clean. You understand, right? [strangely winks at you]}
{204}{}{[紧张地环顾四周]听着，我认真地告诉你-华莱士先生提供。。。*艰苦的工作，不适合那些喜欢干净双手的人。你明白吧？[奇怪地向你眨眼]}
#{205}{}{Okay, I'm ready to do any work.}
{205}{}{好的，我准备好做任何工作了。}
#{206}{}{Then I will refrain. Bye.}
{206}{}{那我就克制一下。再见。}
#{207}{}{Damn, you're taking a responsibility, you understand? Mr. Wallace is on the third floor. Visit his first guard and tell him [makes very important and pompous look] that Sam Riley recommended you.}
{207}{}{妈的，你要承担责任，明白吗？华莱士先生在三楼。拜访他的第一个卫兵，告诉他（显得非常重要和傲慢）山姆·莱利推荐了你。}
#{208}{}{Thanks, man!}
{208}{}{谢谢，伙计！}
#{209}{}{Thank you doesn't pay the bills.}
{209}{}{谢谢你没付帐单。}
#{210}{}{Hmm, okay, here's 50 bucks.}
{210}{}{嗯，好吧，这是50美元。}
#{211}{}{Say what?! I saved your ass, what else do you want?}
{211}{}{说什么？！我救了你，你还想要什么？}
#{212}{}{Uh, okay. But now we're even - you saved me, and I introduced you to Mr. Wallace. [smiling and winking at you somewhat slyly; something tells you that this is not good]}
{212}{}{呃，好吧。但现在我们扯平了-你救了我，我把你介绍给华莱士先生。[有点狡猾地对你微笑和眨眼；有东西告诉你这不好]}
#{213}{}{Oh... Okay, bye.}
{213}{}{哦。。。好的，再见。}
#{214}{}{[Takes the money] Okay, we can work together. I want to warn you as a friend. Mr. Wallace does not like unnecessary talk. If he asks you to do something, don't ask any questions. Just do it, otherwise... [moves his thumb across his throat]}
{214}{}{好吧，我们可以一起工作。作为朋友，我想警告你。华莱士先生不喜欢不必要的谈话。如果他让你做某事，不要问任何问题。就这么做，否则。。。[拇指在喉咙上移动]}
#{215}{}{Understood.}
{215}{}{理解。}
#{1104}{}{Hello there, friend!}
{1104}{}{你好，朋友！}
#{1110}{}{Heh-Hey! Gal! Here you are! I knew you would come here! Let me get you a drink! Hey, bartender! Put it on my tab!}
{1110}{}{嘿嘿！女孩！给你！我就知道你会来的！我给你拿杯喝的！嘿，酒保！把它记在我的账上！}
#{1112}{}{Hey! Those troopers are afraid of even coming near Vegas! Don't worry, girl! We're safe here.}
{1112}{}{嘿！那些骑警甚至害怕接近维加斯！别担心，姑娘！我们在这里很安全。}
#{1118}{}{It's all right, babe! *burps*}
{1118}{}{没事的，宝贝！*打嗝*}
#{1122}{}{Ha-ha-ha! Don't be afraid, girl! [taps you on the shoulder] in your honor, I'd slaughter everyone! Want me to knife the bartender?!}
{1122}{}{哈哈哈！别害怕，姑娘！[拍拍你的肩膀]以你的名誉，我会杀了所有人！要我给酒保开刀吗？！}
#{1126}{}{Ha! What's the matter, girl?! You know *who* you're talking to?! [weighty pokes himself in the chest with his thumb] WHO is in front of you?!}
{1126}{}{哈！怎么了，姑娘？！你知道你在和谁说话吗？！[笨重的拇指戳了戳自己的胸膛]谁在你前面？！}
#{1133}{}{Oh, come on! I've saved you!}
{1133}{}{哦，来吧！我救了你！}
#{1151}{}{Friend... No - sister! Yes! Sis, you save me again. This eared creep always refuses to serve me after the second bottle... Oh, yeah, where were we?}
{1151}{}{朋友。。。不-姐姐！对！姐姐，你又救我了。第二瓶酒后，这个长耳朵的家伙总是拒绝招待我。。。哦，是的，我们在哪儿？}
#{1205}{}{Okay, I'm ready to do any work.}
{1205}{}{好的，我准备好做任何工作了。}
#{1207}{}{Any work? Seriously? [estimates you from head to toe] For such legs Mr. Wallace will find a pair of shoes... With *killing* heels, if you know what I mean. Mr. Wallace is on the third floor. Visit his first guard and tell him [makes very important and pompous look] that Sam Riley recommended you.}
{1207}{}{有工作吗？说真的？[从头到脚估计你]对于这样的腿，华莱士先生会找到一双鞋。。。如果你明白我的意思的话，那就穿高跟鞋。华莱士先生在三楼。拜访他的第一个卫兵，告诉他（显得非常重要和傲慢）山姆·莱利推荐了你。}
#{1211}{}{Say what?! I saved your ass, what else do you want?}
{1211}{}{说什么？！我救了你，你还想要什么？}
#{1212}{}{Uh, okay. But now we're even - you saved me, and I introduced you to Mr. Wallace. [smiling and winking at you somewhat slyly; something tells you that this is not good]}
{1212}{}{呃，好吧。但现在我们扯平了-你救了我，我把你介绍给华莱士先生。[有点狡猾地对你微笑和眨眼；有东西告诉你这不好]}
