#{113}{}{You found the "Speed Hawk" caravaner. He's dead.}
{113}{}{你找到了“速鹰”商队。他死了。}
#{114}{}{You found another "Speed Hawk" caravaner. Sadly, he's dead too.}
{114}{}{你找到了另一个“速度鹰”商队。可悲的是，他也死了。}
#{115}{}{Damn, this "Speed Hawk" caravaner was beaten with exceptional brutality.}
{115}{}{该死的，这个“速度鹰”商队被打得异常残忍。}
#{116}{}{This one was shot. Looks like he attempted to run away.}
{116}{}{这个是被枪杀的。看起来他想逃跑。}
#{117}{}{This one's skull is fractured. These raiders must have been quite the tough guys.}
{117}{}{这个人的头骨骨折了。这些袭击者一定是很厉害的家伙。}
#{118}{}{The guys were definitely on edge. This one must have been beaten for not less than two hours...}
{118}{}{那些家伙肯定很紧张。这个人肯定被打了不少于两个小时。。。}
#{119}{}{Wait a minute! What is this?}
{119}{}{等一下！这是什么？}
#{120}{}{Looks like a locket. Maybe it fell off one of the raiders...}
{120}{}{看起来像个小盒子。可能是从袭击者身上掉下来的。。。}
#{121}{}{You found some strange piece of evidence.}
{121}{}{你发现了一些奇怪的证据。}
