#{100}{}{Oxygen cylinders.}
{100}{}{氧气瓶。}
#{101}{}{Cylinders with emergency oxygen supply. Each has the word "EXPLOSIVE!" written in large letters.}
{101}{}{带应急氧气供应的钢瓶。每一个都有“爆炸性的！”用大字写的。}
#{102}{}{You could prepare the cart to explode and push it in the direction of turrets.}
{102}{}{你可以准备大车爆炸，并把它推向炮塔的方向。}
#{103}{}{Cylinders with emergency oxygen supply. They can be pushed to the turrets and blown up, but how to do that from a distance?}
{103}{}{带应急氧气供应的钢瓶。它们可以被推到炮塔上炸毁，但如何从远处做到这一点呢？}
#{104}{}{Looks like here comes the boom!}
{104}{}{看来是爆炸声来了！}
#{105}{}{Nothing.}
{105}{}{没有什么。}
#{106}{}{You cannot do that during combat!}
{106}{}{你不能在战斗中这样做！}
#{107}{}{You set the dynamite to the cart. All that's left is to set the timer and give a little push to this dangerous "baggage".}
{107}{}{你把炸药放在手推车上。剩下的就是设置计时器，稍微推一下这个危险的“行李”。}
#{108}{}{Mined}
{108}{}{开采}
#{109}{}{You already mined the cart, additional charges are not required.}
{109}{}{您已经挖掘了购物车，不需要额外收费。}
#{110}{}{That is unnecessary}
{110}{}{那是不必要的}
#{111}{}{You attached the cable to the gas cylinders and pushed the cart. All that's left is to give it a little charge.}
{111}{}{你把电缆连在煤气瓶上，推着推车。剩下的就是给它一点充电。}
