##############################
#???????: ???
#???: ?????
#??????? ????????: ??????? ?? ???
#???? ????????: 17.08.2015
##############################
#??? ???? "????? 2207"
#????? "Rainman" ????????
##############################
#
#???????? ????????
#
# ?? ??????????
### {1}{}{You see a kid with eyes wide open.}
{1}{}{你看到一个睁大眼睛的孩子。 -- You see a kid with eyes wide open.}
### {2}{}{His clothes look lousy. As many things around here.}
{2}{}{他的衣服看起来糟透了。这里有很多东西。 -- His clothes look lousy. As many things around here.}
#
# ????? ??????????
### {3}{}{You see Henry.}
{3}{}{你看到亨利了。 -- You see Henry.}
### {4}{}{His clothes look lousy. As many things around here.}
{4}{}{他的衣服看起来糟透了。这里有很多东西。 -- His clothes look lousy. As many things around here.}
#
#????? ?????????? ??????
#
#Node001
### {10}{}{Mister, you are not from around here, aren't you? [he doesn't pause, as if being afraid that you'll go away not listening to him] Why do I even ask, I know every local, I'm from here myself. Name's Henry, by the way. Henry... And we need help! [he looks at you with his big puppy eyes]}
{10}{}{先生，你不是这一带的人，不是吗？[他没有停顿，好像害怕你不听他的话就走了]我为什么要问，我认识每个当地人，我自己也是这里人。顺便说一句，我叫亨利。亨利。。。我们需要帮助！[他用小狗般的大眼睛看着你] -- Mister, you are not from around here, aren't you? [he doesn't pause, as if being afraid that you'll go away not listening to him] Why do I even ask, I know every local, I'm from here myself. Name's Henry, by the way. Henry... And we need help! [he looks at you with his big puppy eyes]}
### {11}{002}{"We"?}
{11}{002}{“我们”？ -- "We"?}
### {12}{004}{Help?}
{12}{004}{帮助 -- Help?}
### {13}{005}{Tell me. Not so hastily though. Slowly, in detail.}
{13}{005}{告诉我。不过不要那么匆忙。慢慢地，详细地。 -- Tell me. Not so hastily though. Slowly, in detail.}
### {14}{999}{Nah, kid. Get lost.}
{14}{999}{不，孩子。迷路 -- Nah, kid. Get lost.}

#Node002
### {20}{}{Well, uh, Becky, Sunny, and her dad. They are my friends, and they are in trouble!}
{20}{}{贝基，桑妮，还有她爸爸。他们是我的朋友，他们有麻烦了！ -- Well, uh, Becky, Sunny, and her dad. They are my friends, and they are in trouble!}
### {21}{005}{Tell me. Not so hastily though. Slowly, in detail.}
{21}{005}{告诉我。不过不要那么匆忙。慢慢地，详细地。 -- Tell me. Not so hastily though. Slowly, in detail.}
### {22}{003}{Nah, kid. I don't do charity helping. Talk to the town guards.}
{22}{003}{不，孩子。我不做慈善帮助。和镇上的警卫谈谈。 -- Nah, kid. I don't do charity helping. Talk to the town guards.}

#Node003
### {30}{}{I tried! They won't help me...}
{30}{}{我试过了！他们不会帮我的。。。 -- I tried! They won't help me...}
### {31}{005}{Oh, man. Okay, talk. }
{31}{005}{哦，伙计。好吧，谈谈。 -- Oh, man. Okay, talk. }
### {32}{999}{Why should I care? Get lost.}
{32}{999}{我为什么要在意？迷路 -- Why should I care? Get lost.}

#Node004
### {40}{}{Yes! Uh, my friends are in danger! They decided to risk their lives because the locals are so stubborn! And they are gone for a long time... They need to be rescued!}
{40}{}{对呃，我的朋友有危险！他们决定冒着生命危险，因为当地人太固执了！他们离开了很长一段时间。。。他们需要被拯救！ -- Yes! Uh, my friends are in danger! They decided to risk their lives because the locals are so stubborn! And they are gone for a long time... They need to be rescued!}
### {41}{005}{Whoa kid, you should do trading with your commitment. Tell me. Slowly, in detail.}
{41}{005}{哇，孩子，你应该用你的承诺做交易。告诉我。慢慢地，详细地。 -- Whoa kid, you should do trading with your commitment. Tell me. Slowly, in detail.}
### {42}{003}{Nah, kid. I don't do charity helping. Talk to the town guards.}
{42}{003}{不，孩子。我不做慈善帮助。和镇上的警卫谈谈。 -- Nah, kid. I don't do charity helping. Talk to the town guards.}

#Node005
### {50}{}{[The kid catches his breath, gathering thoughts] Okay, here's the thing, not long ago there was a family of outsiders here in NWO. I mean, they are good people, but the locals never cared, because if you didn't ruin your health for the good of the settlement, you're going to be looked down upon here. So it was with them. Got to a point where they couldn't get any job which gives you anything except worsening your health. The traders put up high prices for them, the locals didn't help either. So, I told them about Pearson Town, stupid me...}
{50}{}{[孩子喘着粗气，聚精会神]好吧，事情是这样的，不久前，NWO有一个外来家庭。我的意思是，他们是好人，但当地人从不在乎，因为如果你不为了定居点的利益而破坏你的健康，你在这里会被看不起的。他们也是如此。到了他们找不到任何能给你带来任何好处的工作的地步，除了恶化你的健康。商人们给他们报了很高的价格，当地人也没帮上忙。所以，我告诉他们关于皮尔逊镇的事，愚蠢的我。。。 -- [The kid catches his breath, gathering thoughts] Okay, here's the thing, not long ago there was a family of outsiders here in NWO. I mean, they are good people, but the locals never cared, because if you didn't ruin your health for the good of the settlement, you're going to be looked down upon here. So it was with them. Got to a point where they couldn't get any job which gives you anything except worsening your health. The traders put up high prices for them, the locals didn't help either. So, I told them about Pearson Town, stupid me...}
### {51}{006}{Pearson Town?}
{51}{006}{皮尔逊镇？ -- Pearson Town?}
### {52}{007}{I see folks are quite friendly around here.}
{52}{007}{我看到这里的人很友好。 -- I see folks are quite friendly around here.}

#Node006
### {60}{}{Pearson Town is a little, well-preserved settlement - if you don't take into account those who inhabit it. Some say that there was a power plant there, but after it was bombed, no one was willing to go into the place... If you believe the stories of old men. [the kid stumbles] So, mostly intact town was covered with a cloud of radiation, and then there appeared Ferals, monsters, and other bad stuff. And we always had problems with medical supplies around here, but there, presumably, could be enough of them, remained from before the war. A lot. Some people ventured into it, searching - but were unsuccessful. So I told the girls about the place.}
{60}{}{皮尔逊镇是一个保存完好的小定居点-如果你不考虑居住在那里的人的话。有人说那里有一座发电厂，但在它被轰炸后，没有人愿意进入这个地方。。。如果你相信老人的故事。[孩子跌跌撞撞]所以，大部分完好无损的城镇被辐射云覆盖，然后出现了野兽、怪物和其他坏东西。我们这里的医疗用品总是有问题，但据推测，战前留下的医疗用品可能已经足够了。很多。一些人冒险进入其中，进行搜索，但没有成功。所以我把这个地方告诉了女孩们。 -- Pearson Town is a little, well-preserved settlement - if you don't take into account those who inhabit it. Some say that there was a power plant there, but after it was bombed, no one was willing to go into the place... If you believe the stories of old men. [the kid stumbles] So, mostly intact town was covered with a cloud of radiation, and then there appeared Ferals, monsters, and other bad stuff. And we always had problems with medical supplies around here, but there, presumably, could be enough of them, remained from before the war. A lot. Some people ventured into it, searching - but were unsuccessful. So I told the girls about the place.}
### {61}{008}{You told them? Why?}
{61}{008}{你告诉他们了？为什么？ -- You told them? Why?}

#Node007
### {70}{}{Well, yeah. But if you are part of NWO, you can be sure that everyone would stand for you. You are a part of the family.}
{70}{}{嗯，是的。但如果你是NWO的一员，你可以肯定每个人都会支持你。你是这个家庭的一部分。 -- Well, yeah. But if you are part of NWO, you can be sure that everyone would stand for you. You are a part of the family.}
### {71}{006}{What were you saying about Pearson Town?}
{71}{006}{你刚才说皮尔逊镇怎么样？ -- What were you saying about Pearson Town?}

#Node008
### {80}{}{Uh, well, not exactly me. Becky got hurt once, came to doctor Hinder, but he chased her away. He told her that he doesn't have medicines for such lowlife as her. And that he wouldn't help her even if she'd brought the band-aids from the Pearson Town itself. Becky spoke with Sunny, and Sunny asked me about the place. And I told her. Stupid.}
{80}{}{嗯，不完全是我。贝基有一次受伤了，去找辛德医生，但他把她赶走了。他告诉她，他没有像她这样卑鄙的人的药。即使她从皮尔逊镇带来了创可贴，他也不会帮她。贝基和桑尼谈过，桑尼问我关于这个地方的事。我告诉了她。愚蠢的 -- Uh, well, not exactly me. Becky got hurt once, came to doctor Hinder, but he chased her away. He told her that he doesn't have medicines for such lowlife as her. And that he wouldn't help her even if she'd brought the band-aids from the Pearson Town itself. Becky spoke with Sunny, and Sunny asked me about the place. And I told her. Stupid.}
### {81}{009}{So, they headed into Pearson Town for medical supplies in hope of being accepted into NWO?}
{81}{009}{所以，他们前往皮尔逊镇购买医疗用品，希望被NWO接受？ -- So, they headed into Pearson Town for medical supplies in hope of being accepted into NWO?}

#Node009
### {90}{}{Yes.}
{90}{}{对 -- Yes.}
### {91}{012}{What the hell were they thinking?}
{91}{012}{他们到底在想什么？ -- What the hell were they thinking?}
### {92}{012}{This is genius. Considering the other ones from here couldn't handle it - guards, prospectors...}
{92}{012}{这是天才。考虑到这里的其他人无法处理——警卫、探矿者。。。 -- This is genius. Considering the other ones from here couldn't handle it - guards, prospectors...}
### {93}{011}{I see. Have something to add?}
{93}{011}{我明白了。有什么要补充的吗？ -- I see. Have something to add?}

#Node010
### {100}{}{Mister, did you change your mind? Will you help us?}
{100}{}{先生，你改变主意了吗？你能帮助我们吗？ -- Mister, did you change your mind? Will you help us?}
### {101}{999}{No, I was just walking by.}
{101}{999}{没有，我只是路过。 -- No, I was just walking by.}
### {102}{005}{Let's refresh my memory. Tell me everything from the beginning.}
{102}{005}{让我们刷新一下我的记忆。从头开始告诉我一切。 -- Let's refresh my memory. Tell me everything from the beginning.}
### {103}{}{Mister, how's the search for my friends going?}
{103}{}{先生，找我朋友的工作进展如何？ -- Mister, how's the search for my friends going?}
### {104}{999}{In the process, Henry. In the process.}
{104}{999}{在这个过程中，亨利。在这个过程中。 -- In the process, Henry. In the process.}
### {105}{}{Mister... You are the best person in the whole NWO! I will never forget that! It's a pity I have nothing to give you for my gratitude... But... Someday I'll repay my debt. I definitely will. And for now... I'll be praying for you. Thank you.}
{105}{}{先生。。。你是整个NWO最好的人！我永远不会忘记！很遗憾，我没有什么可以给你的感激之情。。。但是总有一天我会偿还我的债务。我一定会的。现在。。。我会为你祈祷。非常感谢。 -- Mister... You are the best person in the whole NWO! I will never forget that! It's a pity I have nothing to give you for my gratitude... But... Someday I'll repay my debt. I definitely will. And for now... I'll be praying for you. Thank you.}
### {106}{999}{Good luck, kid! And don't tell your friends about dangerous places anymore.}
{106}{999}{祝你好运，孩子！不要再告诉你的朋友危险的地方了。 -- Good luck, kid! And don't tell your friends about dangerous places anymore.}

#Node011
### {110}{}{I'm afraid, mister, I have nothing to offer you in return. And no one will. No one cares in NWO. But I can pray for you. I... Help me, please!}
{110}{}{恐怕，先生，我没有什么可以回报你的。没有人会。在NWO没有人关心。但我可以为你祈祷。我…请帮帮我！ -- I'm afraid, mister, I have nothing to offer you in return. And no one will. No one cares in NWO. But I can pray for you. I... Help me, please!}
### {111}{999}{Okay, kid. I'll see what I can do [take the coordinates of Pearson Town]}
{111}{999}{好吧，孩子。我看看我能做些什么[拿皮尔逊镇的坐标] -- Okay, kid. I'll see what I can do [take the coordinates of Pearson Town]}
### {112}{999}{Nah, kid. I don't do charity helping. Sorry. Maybe some another time.}
{112}{999}{不，孩子。我不做慈善帮助。很抱歉也许改天吧。 -- Nah, kid. I don't do charity helping. Sorry. Maybe some another time.}
### {113}{999}{Pray? I can pray myself. So I won't do anything without proper payment.}
{113}{999}{祈祷我可以自己祈祷。所以，如果没有适当的报酬，我什么都不会做。 -- Pray? I can pray myself. So I won't do anything without proper payment.}

#Node012
### {120}{}{All they ever wanted is to be accepted... But... [the kid sighs]}
{120}{}{他们想要的只是被接受。。。但是[孩子叹了口气] -- All they ever wanted is to be accepted... But... [the kid sighs]}
### {121}{011}{I see. Have something to add?}
{121}{011}{我明白了。有什么要补充的吗？ -- I see. Have something to add?}
