##############################
#???????: ?????? ??????
#???: ????
#???????????????: ??????- ??????????, ??????????????????????
#???? ???????: 07.05.2014
##############################
#??? ???? "?????2207"
#?????"Rainman" ???????? 
##############################
#
#???????? ????????
#
# ?? ??????????
### {1}{}{You see an old ghoul.}
{1}{}{你看到一个老食尸鬼。 -- You see an old ghoul.}
### {2}{}{This falling-apart ghoul looks ancient. He watches you with an unseeing gaze through his scant eyebrows.}
{2}{}{这个分崩离析的食尸鬼看起来很古老。他透过稀疏的眉毛，用一种看不见的目光看着你。 -- This falling-apart ghoul looks ancient. He watches you with an unseeing gaze through his scant eyebrows.}
#
# ???????????????
### {3}{}{You see Bono.}
{3}{}{你看到波诺了。 -- You see Bono.}
### {4}{}{Unspoken godfather to the family of unfortunate local exiles.}
{4}{}{对当地不幸流亡者家庭直言不讳的教父。 -- Unspoken godfather to the family of unfortunate local exiles.}
#
#??????????????? ??????
#
### {10}{}{[his eyebrows slowly move upward, revealing whitish eyes] A new one, aren't you? [sighs] Why won't you all stay put in Tartarus? How do I feed another mouth?}
{10}{}{[他的眉毛慢慢向上移动，露出苍白的眼睛]一个新的，不是吗？你们为什么不留在塔尔塔罗斯？我该如何喂养另一只嘴？ -- [his eyebrows slowly move upward, revealing whitish eyes] A new one, aren't you? [sighs] Why won't you all stay put in Tartarus? How do I feed another mouth?}
### {11}{002}{What? A new one? What is this place?}
{11}{002}{什么一个新的？这是什么地方？ -- What? A new one? What is this place?}
### {12}{999}{What? No, I don't have time for this.}
{12}{999}{什么不，我没有时间。 -- What? No, I don't have time for this.}


### {20}{}{New one - that's you, new one. Like the half of unfortunate seekers of a better life here, you just couldn't sit tight in one place...}
{20}{}{新的，就是你，新的。就像这里一半不幸寻求更好生活的人一样，你就是不能坐在一个地方。。。 -- New one - that's you, new one. Like the half of unfortunate seekers of a better life here, you just couldn't sit tight in one place...}
### {21}{003}{Okay, let's sort this out. Is it a part of Tartarus? I mean, is this even a Tartarus?}
{21}{003}{好吧，让我们来解决这个问题。它是鞑靼人的一部分吗？我的意思是，这甚至是鞑靼人吗？ -- Okay, let's sort this out. Is it a part of Tartarus? I mean, is this even a Tartarus?}
### {22}{004}{I don't understand, old man. What are you talking about? You ARE an old man, right? You don't look too good...}
{22}{004}{我不明白，老头。你在说什么？你是个老人，对吧？你看起来不太好。。。 -- I don't understand, old man. What are you talking about? You ARE an old man, right? You don't look too good...}
### {23}{999}{That's it, I'm out of here.}
{23}{999}{就这样，我要离开这里。 -- That's it, I'm out of here.}


### {30}{}{Listen, son... That's no Tartarus. I mean... There's THE REST of the world, except, Tartarus, you see? So now you are there, in THE REST of the world. We call this place "the caves of undead". I came up with the name. And I'm Bono if you are wondering.}
{30}{}{听着，儿子。。。那不是鞑靼人。我的意思是。。。除了塔尔塔罗斯，世界上还有其他地方，你看到了吗？所以现在你在那里，在世界的其他地方。我们称这里为“亡灵洞穴”。我想出了这个名字。如果你想知道的话，我是波诺。 -- Listen, son... That's no Tartarus. I mean... There's THE REST of the world, except, Tartarus, you see? So now you are there, in THE REST of the world. We call this place "the caves of undead". I came up with the name. And I'm Bono if you are wondering.}
### {31}{005}{Undead? So you all are undead? And you live here? All these people, wearing Tartarus clothes?.. Oh man...}
{31}{005}{不死？所以你们都是不死族？你住在这里吗？所有这些人，穿着鞑靼人的衣服？。。天啊。。。 -- Undead? So you all are undead? And you live here? All these people, wearing Tartarus clothes?.. Oh man...}


### {40}{}{Well, let's say I'm the next step of being an old man. You could even say I'm the next step of being a DEAD man. And not the last step, unfortunately... The name's Bono. This place is called "the caves of undead". Here live the likes of you. And me.}
{40}{}{好吧，比方说我是成为一个老人的下一步。你甚至可以说我是一个死去的人的下一步骤。不幸的是，这不是最后一步。。。我叫波诺。这个地方被称为“亡灵洞穴”。像你这样的人住在这里。还有我。 -- Well, let's say I'm the next step of being an old man. You could even say I'm the next step of being a DEAD man. And not the last step, unfortunately... The name's Bono. This place is called "the caves of undead". Here live the likes of you. And me.}
### {41}{005}{Undead... This is no Tartarus, although you have no sky here as well. Who are all these people?.. Oh man...}
{41}{005}{未发布。。。这不是鞑靼人，尽管你这里也没有天空。这些人都是谁？。。天啊。。。 -- Undead... This is no Tartarus, although you have no sky here as well. Who are all these people?.. Oh man...}


### {50}{}{Don't be hasty, new one. The understanding cannot be rushed, or it will become distorted, hazy, and tangled... Let's start with the basics: what's your name?}
{50}{}{不要操之过急，新来的。理解不能操之过急，否则就会变得扭曲、模糊和纠结。。。让我们从基础知识开始：你叫什么名字？ -- Don't be hasty, new one. The understanding cannot be rushed, or it will become distorted, hazy, and tangled... Let's start with the basics: what's your name?}
### {51}{006}{My name is }
{51}{006}{我的名字是 -- My name is }
### {52}{006}{, I came from Tartarus... And I need answers.}
{52}{006}{，我来自塔尔塔罗斯。。。我需要答案。 -- , I came from Tartarus... And I need answers.}
### {53}{999}{No, I need to think everything over first.}
{53}{999}{不，我需要先把一切都想清楚。 -- No, I need to think everything over first.}


### {60}{}{Of course. Like literally everyone else before you [he smiles with a toothless grin]. If you already pulled yourself together, we can look into the answers you need.}
{60}{}{当然就像你之前的其他人一样[他笑得没有牙齿]。如果你已经振作起来，我们可以找到你需要的答案。 -- Of course. Like literally everyone else before you [he smiles with a toothless grin]. If you already pulled yourself together, we can look into the answers you need.}
### {61}{010}{Yes, I'd like to.}
{61}{010}{是的，我愿意。 -- Yes, I'd like to.}
### {62}{999}{Not now, I need some time to think everything over first.}
{62}{999}{现在不行，我需要一些时间先把一切都想清楚。 -- Not now, I need some time to think everything over first.}


### {100}{}{Hmm... Hmm-hmm? Oh, it's you, }
{100}{}{嗯…嗯？哦，是你， -- Hmm... Hmm-hmm? Oh, it's you, }
### {101}{}{. What do you need?}
{101}{}{.你需要什么？ -- . What do you need?}
### {102}{}{Yeah? Something else?}
{102}{}{是 啊还有别的吗？ -- Yeah? Something else?}
### {103}{011}{Tell me about Tartarus!}
{103}{011}{告诉我关于塔尔塔罗斯的事！ -- Tell me about Tartarus!}
### {104}{020}{How do you all live here?}
{104}{020}{你们是怎么住在这里的？ -- How do you all live here?}
### {105}{030}{Do you know anything about Gods?}
{105}{030}{你知道神的事吗？ -- Do you know anything about Gods?}
### {106}{040}{My father is very sick, I need to get back to Tartarus.}
{106}{040}{我父亲病得很重，我需要回到塔尔塔罗斯。 -- My father is very sick, I need to get back to Tartarus.}
### {107}{050}{You promised to help me, remember? Return the favor and all that.}
{107}{050}{你答应过帮我的，记得吗？回报你的恩惠和所有这些。 -- You promised to help me, remember? Return the favor and all that.}
### {108}{060}{You look somehow distracted. Lost something?}
{108}{060}{你看起来有点分心。丢了什么？ -- You look somehow distracted. Lost something?}
### {199}{065}{About that speech you want to give...}
{199}{065}{关于你要发表的演讲。。。 -- About that speech you want to give...}
### {198}{069}{There's this guy Joe, he looks for his wife, Nadine.}
{198}{069}{有个家伙，乔，他在找他的妻子，纳丁。 -- There's this guy Joe, he looks for his wife, Nadine.}
### {197}{075}{I brought Priestley some fertilizer. So I've been thinking - maybe you need more of that?}
{197}{075}{我给普里斯特利带来了一些肥料。所以我一直在想——也许你还需要更多？ -- I brought Priestley some fertilizer. So I've been thinking - maybe you need more of that?}
### {196}{076}{I brought more fertilizer.}
{196}{076}{我带来了更多的肥料。 -- I brought more fertilizer.}
### {109}{999}{Nothing, we'll talk later.}
{109}{999}{没什么，我们稍后再谈。 -- Nothing, we'll talk later.}


### {110}{}{Tartarus... Yeah... Tartarus is a great place to, uh, live. It's interesting, really - you, who came from Tartarus, are asking me, who has never been there, to tell you about it. Better answer me, why did you run away from there?}
{110}{}{塔尔塔罗斯。。。是 啊塔尔塔罗斯是个不错的地方。这很有趣，真的-你，来自塔尔塔罗斯，问我，一个从未去过那里的人，告诉你这件事。最好回答我，你为什么要逃离那里？ -- Tartarus... Yeah... Tartarus is a great place to, uh, live. It's interesting, really - you, who came from Tartarus, are asking me, who has never been there, to tell you about it. Better answer me, why did you run away from there?}
### {111}{012}{Run away? This was an accident! I never even thought about running away from serving...}
{111}{012}{逃跑这是个意外！我甚至从来没有想过逃避服役。。。 -- Run away? This was an accident! I never even thought about running away from serving...}
### {112}{013}{Run away... Serving, serving, nothing except serving the Sons of Gods - and the Gods themselves. But I didn't run away, this was... A strange accident.}
{112}{013}{逃跑侍奉，侍奉，除了侍奉众神之子和众神本身，什么都没有。但我没有逃跑，这是。。。一个奇怪的事故。 -- Run away... Serving, serving, nothing except serving the Sons of Gods - and the Gods themselves. But I didn't run away, this was... A strange accident.}
### {113}{013}{Run away... Serving, serving, nothing except serving the Sons of Gods - and the Gods themselves. But I didn't run away, this was... A strange accident. Usually, the Sons of Gods don't make such fast accusations.}
{113}{013}{逃跑侍奉，侍奉，除了侍奉众神之子和众神本身，什么都没有。但我没有逃跑，这是。。。一个奇怪的事故。通常，众神之子不会这么快提出指控。 -- Run away... Serving, serving, nothing except serving the Sons of Gods - and the Gods themselves. But I didn't run away, this was... A strange accident. Usually, the Sons of Gods don't make such fast accusations.}
### {114}{014}{Uh, yeah, sure I ran away! I always knew that life is not only about serving Gods, there must be something more to it, some... Higher purpose, I suppose.}
{114}{014}{嗯，是的，我当然跑了！我一直知道，生活不仅仅是为上帝服务，它还必须有更多的东西，一些。。。我想目标更高。 -- Uh, yeah, sure I ran away! I always knew that life is not only about serving Gods, there must be something more to it, some... Higher purpose, I suppose.}


### {120}{}{So that's how it is, huh? Interesting, yeah... So interesting... And very unusual... [his eyes are wide open, but you see that ghoul fell into the depths of his subconsciousness. Then he comes to senses] It's not like with others here. You definitely have some kind of a mission. Or maybe not.}
{120}{}{事情就是这样，嗯？有趣，是的。。。太有趣了。。。而且非常不寻常。。。[他的眼睛睁得很大，但你看到食尸鬼陷入了潜意识的深处。然后他恢复了理智]这里的其他人就不一样了。你肯定有某种使命。也许不是。 -- So that's how it is, huh? Interesting, yeah... So interesting... And very unusual... [his eyes are wide open, but you see that ghoul fell into the depths of his subconsciousness. Then he comes to senses] It's not like with others here. You definitely have some kind of a mission. Or maybe not.}
### {121}{015}{Why is it not like with others? Which others?}
{121}{015}{为什么和其他人不一样？还有哪些？ -- Why is it not like with others? Which others?}
### {122}{015}{Well, of course... Others here, from Tartarus, they too ran away from serving, aren't they?}
{122}{015}{当然。。。这里的其他人，来自塔尔塔罗斯，他们也逃离了服务，不是吗？ -- Well, of course... Others here, from Tartarus, they too ran away from serving, aren't they?}
### {123}{015}{Others from Tartarus, they searched for a better life here, right? Everyone seeks what's best for them.}
{123}{015}{其他来自塔尔塔罗斯的人，他们在这里寻找更好的生活，对吧？每个人都在寻求对自己最好的东西。 -- Others from Tartarus, they searched for a better life here, right? Everyone seeks what's best for them.}


### {130}{}{Strange accident, you say? Every time I hear "accident", I can't help thinking about the causes. Is there anything that doesn't have cause?.. Who are we to judge about causes... Even about the reasons to leave Tartarus. Or to go back there. Did you see other people here, your fellow Tartarus dwellers? }
{130}{}{你说奇怪的事故？每次听到“意外”，我都会不由自主地思考原因。有什么没有原因的吗？。。我们该由谁来判断原因。。。甚至是关于离开塔尔塔罗斯的原因。或者回到那里。你在这里看到其他人了吗，你的鞑靼居民同伴？ -- Strange accident, you say? Every time I hear "accident", I can't help thinking about the causes. Is there anything that doesn't have cause?.. Who are we to judge about causes... Even about the reasons to leave Tartarus. Or to go back there. Did you see other people here, your fellow Tartarus dwellers? }
### {131}{015}{No. Who do you mean? Old man, are you sane?}
{131}{015}{不，你是说谁？老头，你神智正常吗？ -- No. Who do you mean? Old man, are you sane?}
### {132}{015}{Yes, I did.  They don't seem very happy. What happened to them?}
{132}{015}{是的，我做到了。他们看起来不太高兴。他们怎么了？ -- Yes, I did.  They don't seem very happy. What happened to them?}


### {140}{}{Just like everyone else, my boy. [he slowly wides his lips in a wrinkled smile] All of you... No, all of US are always looking for something better... More convenient place, warmer fire, tastier apple... But in search of that, we are forced to abandon what we already have. All these people abandoned Tartarus, just like you. And now they are all here. And you are too.}
{140}{}{和其他人一样，我的孩子。[他皱着眉头慢慢地张大嘴唇]你们所有人。。。不，我们所有人都在寻找更好的东西。。。更方便的地方，更温暖的火，更美味的苹果。。。但为了寻求这一点，我们被迫放弃我们已经拥有的东西。所有这些人都抛弃了塔尔塔罗斯，就像你一样。现在他们都来了。你也是。 -- Just like everyone else, my boy. [he slowly wides his lips in a wrinkled smile] All of you... No, all of US are always looking for something better... More convenient place, warmer fire, tastier apple... But in search of that, we are forced to abandon what we already have. All these people abandoned Tartarus, just like you. And now they are all here. And you are too.}
### {141}{015}{All these people? Who do you mean?}
{141}{015}{所有这些人？你是说谁？ -- All these people? Who do you mean?}
### {142}{015}{Of course! Others, from Tartarus, they ran off their serving too, right?}
{142}{015}{当然其他人，来自塔尔塔罗斯，他们也放弃了发球，对吧？ -- Of course! Others, from Tartarus, they ran off their serving too, right?}


### {150}{}{The others... All these men and women, ask any - everyone has their reasons to search for a better life. But they didn't know what they would get in return. In Tartarus, you had food, water, warmth, the roof over your head... Hah, it's funny to say, but even protection from monsters of the outside world! And here? You trade everything you had for freedom... Freedom to lay down wherever you want and wait for death from starvation, cold, or fangs.}
{150}{}{其他人。。。所有这些男人和女人，问任何人——每个人都有自己追求更好生活的理由。但他们不知道会得到什么回报。在塔尔塔罗斯，你有食物、水、温暖、头顶的屋顶。。。哈哈，说起来很有趣，但即使是保护自己免受外界怪物的伤害！这里呢？你用你所拥有的一切换取自由。。。自由躺在任何你想躺的地方，等待饥饿、寒冷或毒牙的死亡。 -- The others... All these men and women, ask any - everyone has their reasons to search for a better life. But they didn't know what they would get in return. In Tartarus, you had food, water, warmth, the roof over your head... Hah, it's funny to say, but even protection from monsters of the outside world! And here? You trade everything you had for freedom... Freedom to lay down wherever you want and wait for death from starvation, cold, or fangs.}
### {151}{016}{We... They didn't know. They had a choice and they made it. }
{151}{016}{我们他们不知道。他们有一个选择，他们做到了。 -- We... They didn't know. They had a choice and they made it. }
### {152}{017}{Yes, it was stupid - to abandon such a safe and warm place. Here it looks obvious.}
{152}{017}{是的，放弃这样一个安全温暖的地方太愚蠢了。这看起来很明显。 -- Yes, it was stupid - to abandon such a safe and warm place. Here it looks obvious.}
### {153}{017}{But they didn't know it would be so bad here.}
{153}{017}{但他们不知道这里会如此糟糕。 -- But they didn't know it would be so bad here.}
### {154}{018}{It's their choice, why should I care?}
{154}{018}{这是他们的选择，我为什么要在乎？ -- It's their choice, why should I care?}


### {160}{}{Who can blame them, really? [smiles] You made your choice too, and now you're here. Another mouth to feed, keep warm, protect... feed...}
{160}{}{谁能责怪他们，真的吗？[微笑]你也做出了选择，现在你来了。另一口要喂养、保暖、保护。。。喂养 -- Who can blame them, really? [smiles] You made your choice too, and now you're here. Another mouth to feed, keep warm, protect... feed...}
### {161}{010}{Okay, I got your point. Can I ask something?}
{161}{010}{好吧，我明白你的意思了。我能问点什么吗？ -- Okay, I got your point. Can I ask something?}
### {162}{010}{Even if so, I can take care of myself. I'd like to ask another question.}
{162}{010}{即使这样，我也能照顾好自己。我想再问一个问题。 -- Even if so, I can take care of myself. I'd like to ask another question.}


### {170}{}{The thing is, you'll never know if it's the best choice you make, or you have to go back eventually. Except there's nowhere to go back... I mean, there is, but nothing waits for you there anymore.}
{170}{}{问题是，你永远不会知道这是你做出的最佳选择，还是你最终不得不回去。除了无处可回。。。我的意思是，有，但没有什么在那里等你了。 -- The thing is, you'll never know if it's the best choice you make, or you have to go back eventually. Except there's nowhere to go back... I mean, there is, but nothing waits for you there anymore.}
### {171}{010}{But Tartarus is there! Although, it's not very wise for me to return. They think I'm a murderer... Can I ask something else?}
{171}{010}{但塔尔塔罗斯在那里！尽管如此，对我来说回来不是很明智。他们认为我是个杀人犯。。。我能问别的问题吗？ -- But Tartarus is there! Although, it's not very wise for me to return. They think I'm a murderer... Can I ask something else?}
### {172}{010}{I might go back if I wish to do so. Maybe. I have other questions.}
{172}{010}{如果我愿意的话，我可能会回去。也许吧。我还有其他问题。 -- I might go back if I wish to do so. Maybe. I have other questions.}
### {173}{010}{All of this is so... Philosophical. I'd like to ask something else.}
{173}{010}{所有这些都是如此…哲学。我想问些别的问题。 -- All of this is so... Philosophical. I'd like to ask something else.}


### {180}{}{They are only humans, right? Who even cares about the others... [his sight loses focus and you feel transparent] You know... I think this way of treating problems is the reason we are in this hole now. I mean, all of us.}
{180}{}{他们只是人类，对吧？谁还在乎别人。。。[他的视线失去了焦点，你感觉很透明]你知道。。。我认为这种处理问题的方式是我们现在陷入困境的原因。我的意思是，我们所有人。 -- They are only humans, right? Who even cares about the others... [his sight loses focus and you feel transparent] You know... I think this way of treating problems is the reason we are in this hole now. I mean, all of us.}
### {181}{019}{I... I think I understand. Mutual aid, working together, and such.}
{181}{019}{我…我想我明白了。互助、合作等等。 -- I... I think I understand. Mutual aid, working together, and such.}
### {182}{010}{Uh, yeah, maybe. Can I ask something else?}
{182}{010}{嗯，是的，也许吧。我能问别的问题吗？ -- Uh, yeah, maybe. Can I ask something else?}
### {183}{010}{Don't care. I'd like to ask another question.}
{183}{010}{不要在意。我想再问一个问题。 -- Don't care. I'd like to ask another question.}


### {190}{}{You are a smart young man, aren't you? People like you define the outcome of wars. Or start one [winks].}
{190}{}{你是个聪明的年轻人，不是吗？像你这样的人定义战争的结果。或者开始眨眼。 -- You are a smart young man, aren't you? People like you define the outcome of wars. Or start one [winks].}
### {191}{010}{Uh, thanks, I guess. I'd like to ask another question.}
{191}{010}{呃，我想谢谢。我想再问一个问题。 -- Uh, thanks, I guess. I'd like to ask another question.}


### {200}{}{You call this living? It's a tough one for sure... We got lucky with this station - it protects us not only from daily heat and cold at night but also from carnivorous creatures. A pity this station doesn't protect us from hunger, hahaha... Everyone here is contributing to the common good. Even elders and children help - pick up the soil for patches, warm each other at nights, watch for the entrance... There are so many things an old person can do, you know?}
{200}{}{你称之为活着？这肯定是一场艰苦的比赛。。。我们很幸运有了这个站——它不仅保护我们免受日常高温和夜间寒冷的影响，还保护我们免受食肉动物的伤害。遗憾的是，这个车站不能保护我们免受饥饿，哈哈哈。。。这里的每个人都在为共同利益做出贡献。甚至老人和孩子也会帮忙——收拾泥土，晚上互相取暖，留意入口。。。一个老人能做的事情太多了，你知道吗？ -- You call this living? It's a tough one for sure... We got lucky with this station - it protects us not only from daily heat and cold at night but also from carnivorous creatures. A pity this station doesn't protect us from hunger, hahaha... Everyone here is contributing to the common good. Even elders and children help - pick up the soil for patches, warm each other at nights, watch for the entrance... There are so many things an old person can do, you know?}
### {201}{021}{Why are there so many people here?}
{201}{021}{为什么这里有这么多人？ -- Why are there so many people here?}
### {202}{024}{Where do you get your food?}
{202}{024}{你在哪里吃的？ -- Where do you get your food?}


### {210}{}{Where do YOU come from? That's the answer... A lot of people here are runaways from Tartarus, from your favorite Gods. Some others came from Radius. Me, for example. There are even some who tried to enter the Olympus itself... And who stayed alive, of course.}
{210}{}{你从哪里来？这就是答案。。。这里的很多人都是从塔尔塔罗斯，从你最喜欢的神那里逃跑的。其他一些来自Radius。比如我。甚至还有一些人试图进入奥林匹斯山。。。当然还有谁还活着。 -- Where do YOU come from? That's the answer... A lot of people here are runaways from Tartarus, from your favorite Gods. Some others came from Radius. Me, for example. There are even some who tried to enter the Olympus itself... And who stayed alive, of course.}
### {211}{}{People... Well, they just come. From different places of Radius - wastelands, ruins... Anywhere. Any road eventually leads them here.}
{211}{}{人他们刚来。来自Radius的不同地方——荒原、废墟。。。在任何地方任何道路最终都会把他们带到这里。 -- People... Well, they just come. From different places of Radius - wastelands, ruins... Anywhere. Any road eventually leads them here.}
### {214}{023}{Why did someone try to enter the Olympus?}
{214}{023}{为什么有人试图进入奥林巴斯？ -- Why did someone try to enter the Olympus?}
### {212}{023}{Enter the Olympus? To the Gods!?}
{212}{023}{进入奥林巴斯？致上帝！？ -- Enter the Olympus? To the Gods!?}
### {213}{024}{And where do you get your food?}
{213}{024}{你在哪里吃的？ -- And where do you get your food?}


### {220}{}{Olympus, the last hope. Or so they say, new one. The rumor is this is the place where Gods live. Even if so, they are being guarded by the real Devils! Believe me, I know what I'm saying.}
{220}{}{奥林匹斯，最后的希望。或者他们是这么说的，新的。有传言说这是上帝居住的地方。即便如此，他们还是被真正的魔鬼守护着！相信我，我知道我在说什么。 -- Olympus, the last hope. Or so they say, new one. The rumor is this is the place where Gods live. Even if so, they are being guarded by the real Devils! Believe me, I know what I'm saying.}
### {221}{023}{Devils? You mean, some terrible creatures are guarding the Gods? You must be mistaken, old man.}
{221}{023}{魔鬼？你是说，一些可怕的生物在守护着众神？你一定错了，老头。 -- Devils? You mean, some terrible creatures are guarding the Gods? You must be mistaken, old man.}
### {222}{023}{Devils, you say? I should keep out of them, I suppose.}
{222}{023}{你说魔鬼？我想我应该避开他们。 -- Devils, you say? I should keep out of them, I suppose.}


### {230}{}{There is only one way for us: Tartarus. No one knows exactly what awaits us in the Olympus, but we know for sure that there are no Gods in Tartarus - and it's safer and calmer than here. We are getting there one day, I'm sure of it...}
{230}{}{我们只有一条路：塔尔塔罗斯。没有人确切地知道奥林匹斯山上等待我们的是什么，但我们确信塔尔塔罗斯没有上帝——这里比这里更安全、更平静。我们总有一天会到达那里，我确信。。。 -- There is only one way for us: Tartarus. No one knows exactly what awaits us in the Olympus, but we know for sure that there are no Gods in Tartarus - and it's safer and calmer than here. We are getting there one day, I'm sure of it...}
### {231}{024}{Well, there is plenty of food, that's true... And where do you get yours?}
{231}{024}{嗯，这里有很多食物，这是真的。。。你的在哪里？ -- Well, there is plenty of food, that's true... And where do you get yours?}


### {240}{}{Our seekers go to the road every day, searching for food, supplies, or something that could help us to live for another week. Sometimes they are lucky to put down a molerat - then it's a feast! But usually, they bring some weak crops and roots, which are pretty good if turned into flour and then baked into flatbread. And if they are not good enough, you can just wait for another day - then they taste like heavens, hahahahkhchh...}
{240}{}{我们的寻求者每天都在路上寻找食物、补给，或者可以帮助我们再活一周的东西。有时他们很幸运地放下了小题大做——那么这就是一场盛宴！但通常情况下，他们会带来一些脆弱的作物和根系，如果把它们变成面粉，然后烤成扁平面包，效果会很好。如果它们不够好，你可以再等一天——然后它们尝起来就像天堂，哈哈哈哈。。。 -- Our seekers go to the road every day, searching for food, supplies, or something that could help us to live for another week. Sometimes they are lucky to put down a molerat - then it's a feast! But usually, they bring some weak crops and roots, which are pretty good if turned into flour and then baked into flatbread. And if they are not good enough, you can just wait for another day - then they taste like heavens, hahahahkhchh...}
### {241}{026}{Have you ever tried to grow something? Corn, for example?}
{241}{026}{你有没有尝试过种植一些东西？比如玉米？ -- Have you ever tried to grow something? Corn, for example?}
### {242}{025}{Hunting and gathering, I see. Good thing it's not cannibalism, right? [wink]}
{242}{025}{狩猎和采集，我明白了。还好这不是吃人，对吧？[眨眼] -- Hunting and gathering, I see. Good thing it's not cannibalism, right? [wink]}
### {243}{021}{Where do all these people come from? I don't see any children.}
{243}{021}{这些人都是从哪里来的？我没有看到任何孩子。 -- Where do all these people come from? I don't see any children.}
### {244}{010}{I see... I'd like to ask more.}
{244}{010}{我明白了。。。我想问更多。 -- I see... I'd like to ask more.}


### {250}{}{[Bono looks at you with no response. Literally, zero reaction.]}
{250}{}{[波诺看着你，没有任何回应。从字面上看，零反应。 -- Bono looks at you with no response. Literally, zero reaction.]}
### {251}{010}{Uh, I'd like to ask about other things.}
{251}{010}{呃，我想问一下其他的事情。 -- Uh, I'd like to ask about other things.}


### {260}{}{Old fellow Priestley sure had. He tried to make some crops, but nothing grows on this barren land. I made an effort to come up with something akin to fertilizer, but with no results. Nothing grew up. Poor guy, he was so disappointed by that...}
{260}{}{老家伙普里斯特利当然有。他试着种些庄稼，但在这块贫瘠的土地上什么也种不出来。我努力想出一种类似肥料的东西，但没有结果。什么也没长出来。可怜的家伙，他很失望。。。 -- Old fellow Priestley sure had. He tried to make some crops, but nothing grows on this barren land. I made an effort to come up with something akin to fertilizer, but with no results. Nothing grew up. Poor guy, he was so disappointed by that...}
### {261}{010}{Hmm... A fertilizer? Maybe something will come out of this. I'd like to ask about something else.}
{261}{010}{嗯…肥料？也许会有什么结果。我想问一些其他的事情。 -- Hmm... A fertilizer? Maybe something will come out of this. I'd like to ask about something else.}
### {262}{010}{Yeah, no luck means no luck. Can I ask other questions?}
{262}{010}{是的，没有运气就意味着没有运气。我可以问其他问题吗？ -- Yeah, no luck means no luck. Can I ask other questions?}


### {300}{}{Gods? Which Gods? Oh, you mean the Olympus Gods. Olympus... I didn't meet anyone who would know exactly what it is, myself included. Not even talking about who - or what - lives inside. What is known is that the Olympus is... Alive. It's an organism, it's breathing together with the whole Radius.}
{300}{}{上帝？哪些神？哦，你是说奥林匹斯众神。奥林巴斯。。。包括我自己在内，我没有遇到任何人能确切地知道它是什么。甚至不谈论里面住着什么人。已知的是奥林匹斯是活着的。它是一个有机体，与整个Radius一起呼吸。 -- Gods? Which Gods? Oh, you mean the Olympus Gods. Olympus... I didn't meet anyone who would know exactly what it is, myself included. Not even talking about who - or what - lives inside. What is known is that the Olympus is... Alive. It's an organism, it's breathing together with the whole Radius.}
### {301}{031}{What? It's just a building! How can it breathe?}
{301}{031}{什么这只是一座建筑！它怎么能呼吸？ -- What? It's just a building! How can it breathe?}
### {302}{032}{No one knows then? A pity... But maybe there's someone who could tell more?}
{302}{032}{那时没人知道？很遗憾。。。但也许有人能说得更多？ -- No one knows then? A pity... But maybe there's someone who could tell more?}
### {303}{033}{Radius is breathing? What does it mean?}
{303}{033}{Radius在呼吸吗？这是什么意思？ -- Radius is breathing? What does it mean?}


### {310}{}{I have no easy way of explaining it. Let's put it like that - when you see a tree you know it's alive, despite that it doesn't have a single leaf on it. You just know, because in another case its roots wouldn't hold it in the soil. The Olympus is the same - it can't be not alive, or it would become a part of ruins long ago.}
{310}{}{我没有简单的方法来解释它。让我们这样说吧——当你看到一棵树时，你知道它是活着的，尽管它上面没有一片叶子。你只知道，因为在另一种情况下，它的根无法将它固定在土壤中。奥林匹斯山也是一样——它不可能没有生命，否则它早就成了废墟的一部分。 -- I have no easy way of explaining it. Let's put it like that - when you see a tree you know it's alive, despite that it doesn't have a single leaf on it. You just know, because in another case its roots wouldn't hold it in the soil. The Olympus is the same - it can't be not alive, or it would become a part of ruins long ago.}
### {311}{032}{Your metaphors are making me woozy... Do you know where I can find someone, who could tell more about the Olympus?}
{311}{032}{你的比喻让我晕头转向。。。你知道我在哪里能找到一个能告诉我更多关于奥林巴斯的人吗？ -- Your metaphors are making me woozy... Do you know where I can find someone, who could tell more about the Olympus?}
### {312}{032}{Alive or not alive, what? Where I can learn more about the Olympus?}
{312}{032}{活着还是不活着，什么？在哪里我可以了解更多关于奥林巴斯的信息？ -- Alive or not alive, what? Where I can learn more about the Olympus?}


### {320}{}{You know where - in Tartarus! [he hoarsely laughs] Whether you want it or not, but your path leads to the same place as ours, new one. You won't survive in Radius alone, that's for sure.}
{320}{}{你知道在哪里——在塔尔塔罗斯！[他嘶哑地笑着]不管你愿不愿意，但你的路通向和我们一样的地方，新的地方。你肯定无法独自在Radius生存。 -- You know where - in Tartarus! [he hoarsely laughs] Whether you want it or not, but your path leads to the same place as ours, new one. You won't survive in Radius alone, that's for sure.}
### {321}{033}{Radius? Can you tell me more?}
{321}{033}{半径你能告诉我更多吗？ -- Radius? Can you tell me more?}


### {330}{}{Radius is not only the place, the piece of land where we stuck. Radius is our whole world. When you go out into the wasteland, standing still into the night, looking around - it's Radius. When you open some chest in a haunted house, praying it doesn't have any trap on it - it's Radius. Even when you look deep into my white eyes, it's Radius. }
{330}{}{半径不仅仅是我们坚守的地方，那片土地。Radius是我们的整个世界。当你走进荒原，站在那里直到深夜，环顾四周——这就是Radius。当你在闹鬼的房子里打开某个箱子，祈祷它上面没有陷阱——它就是Radius。即使你深深地看着我的白眼，它也是Radius。 -- Radius is not only the place, the piece of land where we stuck. Radius is our whole world. When you go out into the wasteland, standing still into the night, looking around - it's Radius. When you open some chest in a haunted house, praying it doesn't have any trap on it - it's Radius. Even when you look deep into my white eyes, it's Radius. }
### {331}{034}{So Radius is everything that surrounds me, wherever I go?}
{331}{034}{半径就是我周围的一切，无论我走到哪里？ -- So Radius is everything that surrounds me, wherever I go?}
### {332}{035}{You mean, Radius is our whole life?}
{332}{035}{你的意思是，半径是我们的全部生活？ -- You mean, Radius is our whole life?}


### {340}{}{Yes. And to stay alive in it, you should let Radius into you, let it take you over. Cursed lands require cursed deeds.}
{340}{}{对为了在其中保持活力，你应该让Radius进入你，让它接管你。被诅咒的土地需要被诅咒的行为。 -- Yes. And to stay alive in it, you should let Radius into you, let it take you over. Cursed lands require cursed deeds.}
### {341}{010}{I got it, enough with your explanations. I want to ask something else...}
{341}{010}{我明白了，你的解释够了。我想问别的问题。。。 -- I got it, enough with your explanations. I want to ask something else...}


### {350}{}{Life and death, and everything after. Radius is everything except the Olympus. If you don't understand it now, you will later, new one.}
{350}{}{生与死，以及之后的一切。除了奥林巴斯，半径就是一切。如果你现在不明白，你以后会明白的，新的。 -- Life and death, and everything after. Radius is everything except the Olympus. If you don't understand it now, you will later, new one.}
### {351}{010}{Nah, enough with your explanations. I want to ask something else...}
{351}{010}{不，你的解释够了。我想问别的问题。。。 -- Nah, enough with your explanations. I want to ask something else...}


### {400}{}{Uh, you won't get there so easily, just saying "I wanna go to Tartarus", no... We are trying to find an approach for a very long time, but the guards ask so much that we could never afford it... Seems like they have an order not to let anyone outside in.}
{400}{}{呃，你不会那么容易到达那里，只是说“我想去塔尔塔罗斯”，不……我们很长一段时间都在努力寻找方法，但警卫要求太高，我们永远负担不起……似乎他们有命令，不让外面的人进来。 -- Uh, you won't get there so easily, just saying "I wanna go to Tartarus", no... We are trying to find an approach for a very long time, but the guards ask so much that we could never afford it... Seems like they have an order not to let anyone outside in.}
### {401}{041}{Wait, what guards? The ones that protect you from strange creatures?}
{401}{041}{等等，什么警卫？那些保护你免受奇怪生物伤害的人？ -- Wait, what guards? The ones that protect you from strange creatures?}
### {402}{042}{Find an approach? What exactly did you try to do?}
{402}{042}{找到方法吗？你到底想做什么？ -- Find an approach? What exactly did you try to do?}
### {403}{043}{Not to let anyone in? Why's that?}
{403}{043}{不让任何人进来？为什么？ -- Not to let anyone in? Why's that?}


### {410}{}{From WHO? [he raises his heavy eyebrows] Oh, you mean in the Purgatory... No, I'm talking about the other side. There are well-armed guards there too... The ones never let anyone out, the other ones never let anyone out. Mark my word, it has some higher goal behind it. The guards are guarding Tartarus from... From, uh... The likes of us, I suppose... But - why? No one knows.}
{410}{}{来自世界卫生组织？[他扬起沉重的眉毛]哦，你是说在炼狱。。。不，我说的是另一边。那里也有全副武装的警卫。。。那些人从不让任何人出去，另一些人从不让所有人出去。记住我的话，它背后有更高的目标。守卫们正在保护塔尔塔罗斯免受。。。来自，呃。。。我想，像我们这样的人。。。但是——为什么？没有人知道。 -- From WHO? [he raises his heavy eyebrows] Oh, you mean in the Purgatory... No, I'm talking about the other side. There are well-armed guards there too... The ones never let anyone out, the other ones never let anyone out. Mark my word, it has some higher goal behind it. The guards are guarding Tartarus from... From, uh... The likes of us, I suppose... But - why? No one knows.}
### {411}{044}{Okay but I still need to get there somehow.}
{411}{044}{好吧，但我还是需要以某种方式到达那里。 -- Okay but I still need to get there somehow.}
### {412}{044}{There MUST be a way to enter it. If I could get out - I will get in.}
{412}{044}{一定有办法进去。如果我能出去，我就进去。 -- There MUST be a way to enter it. If I could get out - I will get in.}


### {420}{}{We tried many things, actually - offered them hides of Ursa, a bottle of whiskey with a pack of sugar, even - but don't tell anyone! - tried to offer them our women... It's still not enough! And... Uh... Umm... Yeah... Where was I?...}
{420}{}{事实上，我们尝试了很多东西——给他们提供了熊果皮、一瓶威士忌和一包糖，甚至——但不要告诉任何人！——试图把我们的女人交给他们。。。这仍然不够！和嗯嗯。。。是 啊我在哪里？。。。 -- We tried many things, actually - offered them hides of Ursa, a bottle of whiskey with a pack of sugar, even - but don't tell anyone! - tried to offer them our women... It's still not enough! And... Uh... Umm... Yeah... Where was I?...}
### {421}{044}{I see. You don't know what the guards want. But I still need the way to get inside.}
{421}{044}{我明白了。你不知道警卫想要什么。但我仍然需要进去的路。 -- I see. You don't know what the guards want. But I still need the way to get inside.}
### {422}{044}{There must be another way, without offerings or batteries...}
{422}{044}{必须有另一种方式，没有产品或电池。。。 -- There must be another way, without offerings or batteries...}


### {430}{}{Hard to say. They are guards, after all, so they are guarding it. From... From us, I guess... Or from something we could carry with us, some disease maybe... Maybe they are afraid that it will turn all of them into worthless ghouls. Like me! Hahahahaahahh-chkhh... Oh... Or maybe they don't know themselves, what they are guarding. Do you say the Gods are the ones in charge? Then it's them, who should be asked.}
{430}{}{很难说。毕竟，他们是守卫，所以他们在守卫。。。我想是我们。。。或者是由于我们可能携带的某种疾病。。。也许他们害怕这会把他们变成毫无价值的食尸鬼。像我一样！哈哈哈哈。。。哦或者他们不了解自己，不知道自己在守护什么。你说上帝是掌权者吗？那么应该问的是他们。 -- Hard to say. They are guards, after all, so they are guarding it. From... From us, I guess... Or from something we could carry with us, some disease maybe... Maybe they are afraid that it will turn all of them into worthless ghouls. Like me! Hahahahaahahh-chkhh... Oh... Or maybe they don't know themselves, what they are guarding. Do you say the Gods are the ones in charge? Then it's them, who should be asked.}
### {431}{044}{I have no time for Gods now, I need a way to get back into Tartarus.}
{431}{044}{我现在没有时间去见上帝，我需要一条回到塔尔塔罗斯的路。 -- I have no time for Gods now, I need a way to get back into Tartarus.}
### {432}{044}{Gods can wait. First, I need a way to get into Tartarus.}
{432}{044}{上帝可以等待。首先，我需要一条进入塔尔塔罗斯的路。 -- Gods can wait. First, I need a way to get into Tartarus.}


### {440}{}{Get into Tartarus... Yeah, sure... Wait a second [his faces becomes stretched out] You told me that they tried to shoot you, right? So they must be looking for you, and you won't get there anyway, right? But I think there IS a way to help you get back into Tartarus. Alive. But you'll have to return the favor. What do you say, new one?}
{440}{}{进入塔尔塔罗斯。。。是的，当然。。。等一下[他的脸伸了出来]你告诉我他们试图向你开枪，对吧？所以他们一定在找你，你无论如何都不会到那里，对吧？但我认为有一种方法可以帮助你回到塔尔塔罗斯。活着的但你必须回心转意。你说呢，新的？ -- Get into Tartarus... Yeah, sure... Wait a second [his faces becomes stretched out] You told me that they tried to shoot you, right? So they must be looking for you, and you won't get there anyway, right? But I think there IS a way to help you get back into Tartarus. Alive. But you'll have to return the favor. What do you say, new one?}
### {441}{045}{You are just an old, decrepit extortionist, that's what I say. But I'm in. What do you need me to do?}
{441}{045}{我就是这么说的，你只是一个老掉牙的敲诈勒索者。但我在里面。你需要我做什么？ -- You are just an old, decrepit extortionist, that's what I say. But I'm in. What do you need me to do?}
### {442}{045}{Favor in exchange for a favor... Sounds fair. How do I help?}
{442}{045}{以恩惠换取恩惠。。。听起来很公平。我该怎么帮你？ -- Favor in exchange for a favor... Sounds fair. How do I help?}
### {443}{999}{Will I have to do something? I suppose it's something dangerous? I need to think it over.}
{443}{999}{我得做点什么吗？我想这是危险的事情吧？我需要好好想想。 -- Will I have to do something? I suppose it's something dangerous? I need to think it over.}


### {450}{}{We always have our hands full here, getting by as hard we can, but it's a tough time... Our seekers are already tired because they have to go further and further in search of supplies and they are exhausted afterwards... Talk to Robin, he usually stands near the entrance. Also, Gromus, our doctor, complained about the lack of materials for medical mixtures. You could stop by his bar and talk with him. He will tell better, what he needs. If you will be of any help to us, then you'll get my help in returning to Tartarus.}
{450}{}{我们在这里总是忙得不可开交，但这是一段艰难的时光。。。我们的寻求者已经很累了，因为他们必须越来越远地寻找物资，之后他们筋疲力尽。。。和罗宾说话，他通常站在入口附近。此外，我们的医生格罗姆斯抱怨医疗混合物缺乏材料。你可以在他的酒吧停下来和他谈谈。他会说得更好，他需要什么。如果你愿意帮助我们，那么你会得到我的帮助，回到塔尔塔罗斯。 -- We always have our hands full here, getting by as hard we can, but it's a tough time... Our seekers are already tired because they have to go further and further in search of supplies and they are exhausted afterwards... Talk to Robin, he usually stands near the entrance. Also, Gromus, our doctor, complained about the lack of materials for medical mixtures. You could stop by his bar and talk with him. He will tell better, what he needs. If you will be of any help to us, then you'll get my help in returning to Tartarus.}
### {451}{010}{What a puzzle... Okay, let's see what I can do.}
{451}{010}{真是个谜。。。好吧，让我们看看我能做些什么。 -- What a puzzle... Okay, let's see what I can do.}
### {452}{999}{I see... Okay then, off to help. You keep your word.}
{452}{999}{我明白了。。。好的，那就去帮忙。你信守诺言。 -- I see... Okay then, off to help. You keep your word.}
### {453}{999}{Uh... No, I'll find a way to Tartarus myself.}
{453}{999}{嗯不，我会自己找到去塔尔塔罗斯的路。 -- Uh... No, I'll find a way to Tartarus myself.}


### {500}{}{What? Help?... Oh yeah, yeah, I remember. How are you getting along?}
{500}{}{什么帮助哦，是的，我记得。你过得怎么样？ -- What? Help?... Oh yeah, yeah, I remember. How are you getting along?}
### {501}{051}{Still working on it.}
{501}{051}{还在努力。 -- Still working on it.}
### {502}{052}{I helped Robin, just as I promised. Your turn to help, Bono.}
{502}{052}{我帮助了罗宾，正如我所承诺的那样。轮到你帮忙了，波诺。 -- I helped Robin, just as I promised. Your turn to help, Bono.}
### {503}{053}{Gromus is now in possession of some very... Useful tails of scorpions. Your turn to help, Bono.}
{503}{053}{格罗姆斯现在拥有一些非常。。。有用的蝎子尾巴。轮到你帮忙了，波诺。 -- Gromus is now in possession of some very... Useful tails of scorpions. Your turn to help, Bono.}
### {504}{054}{I helped both. They are very happy now, said hi. Now tell me, how do I get into Tartarus?}
{504}{054}{我帮了他们两个。他们现在很高兴，打招呼说。现在告诉我，我该如何进入塔尔塔罗斯？ -- I helped both. They are very happy now, said hi. Now tell me, how do I get into Tartarus?}
### {505}{055}{Yes, I helped both Robin and Gromus. It wasn't easy, but I managed. Now it's your turn to help, Bono. }
{505}{055}{是的，我帮助了罗宾和格罗姆斯。这并不容易，但我成功了。现在轮到你帮忙了，波诺。 -- Yes, I helped both Robin and Gromus. It wasn't easy, but I managed. Now it's your turn to help, Bono. }


### {510}{}{Alright, alright... Any help is appreciated.}
{510}{}{好吧，好吧。。。感谢您的帮助。 -- Alright, alright... Any help is appreciated.}
### {511}{010}{Yeah, of course. I had something else in mind...}
{511}{010}{是的，当然。我还有别的想法。。。 -- Yeah, of course. I had something else in mind...}
### {512}{999}{I, uh, gotta go.}
{512}{999}{I、 呃，得走了。 -- I, uh, gotta go.}

### {520}{}{Good. At last, the seekers can have a little rest. Thanks. You know, you are not like others, from Tartarus, who hang around here... }
{520}{}{好的最后，寻求者可以休息一下了。谢谢。你知道，你不像其他人，来自塔尔塔罗斯，在这里闲逛。。。 -- Good. At last, the seekers can have a little rest. Thanks. You know, you are not like others, from Tartarus, who hang around here... }
### {521}{057}{Ahem... So, how do I get into Tartarus?}
{521}{057}{啊。。。那么，我该如何进入塔尔塔罗斯？ -- Ahem... So, how do I get into Tartarus?}
### {522}{057}{Hey, old man, what about Tartarus? }
{522}{057}{嘿，老头，塔尔塔罗斯怎么样？ -- Hey, old man, what about Tartarus? }

### {530}{}{Agh-hh... Ghuuugh... Thanks a lot, new one. Our only healer couldn't handle dealing with this... RADIVATION. Now he has the means to create his anti-radiation bitter drinks... And other bitter drinks...}
{530}{}{啊。。。啊。。。非常感谢，新来的。我们唯一的治疗者无法处理这个。。。辐射。现在他有办法制造他的抗辐射苦味饮料。。。还有其他苦味饮料。。。 -- Agh-hh... Ghuuugh... Thanks a lot, new one. Our only healer couldn't handle dealing with this... RADIVATION. Now he has the means to create his anti-radiation bitter drinks... And other bitter drinks...}
### {531}{057}{Ahem... So, how do I get into Tartarus?}
{531}{057}{啊。。。那么，我该如何进入塔尔塔罗斯？ -- Ahem... So, how do I get into Tartarus?}
### {532}{057}{Hey, old man, what about Tartarus?}
{532}{057}{嘿，老头，塔尔塔罗斯怎么样？ -- Hey, old man, what about Tartarus?}

### {540}{}{[he slyly squints his left eye] Helped, huh?.. I see you are the man of your word, so I won't go around asking how EXACTLY you helped. Instead, I'll tell you how to get into Tartarus right away, write it down: go to the platform, then follow the tracks until the end. After that you'll see the passage to the side, so - you go there. Walk until you bump into the guards. Come straight to them and say "get the hell out of my way, or else!" - and they'll let you in right away. And they'll give you food. And some medicine, I don't quite remember its name... Something like "fuk-yu-up" or "kill-yu-ded"... My memory is not serving me well lately.}
{540}{}{[他狡猾地眯起左眼]帮了忙，嗯？。。我知道你是个言而有信的人，所以我不会到处问你到底帮了什么忙。相反，我会告诉你如何立即进入塔尔塔罗斯，把它写下来：去站台，然后沿着轨道走到尽头。在那之后，你会看到旁边的通道，所以——你去那里。一直走到碰到警卫为止。直接走到他们面前，说“别挡我的路，否则！”——他们会马上让你进去的。他们会给你食物。还有一些药，我不太记得它的名字了。。。像“fuk-yu-up”或“kill-yu-ded”之类的。。。我最近记性不好。 -- [he slyly squints his left eye] Helped, huh?.. I see you are the man of your word, so I won't go around asking how EXACTLY you helped. Instead, I'll tell you how to get into Tartarus right away, write it down: go to the platform, then follow the tracks until the end. After that you'll see the passage to the side, so - you go there. Walk until you bump into the guards. Come straight to them and say "get the hell out of my way, or else!" - and they'll let you in right away. And they'll give you food. And some medicine, I don't quite remember its name... Something like "fuk-yu-up" or "kill-yu-ded"... My memory is not serving me well lately.}
### {541}{999}{No need for being sarcastic. I'll come by later.}
{541}{999}{没有必要讽刺。我稍后再来。 -- No need for being sarcastic. I'll come by later.}
### {542}{010}{Come on, I was just joking! I'll ask another question.}
{542}{010}{拜托，我只是在开玩笑！我再问一个问题。 -- Come on, I was just joking! I'll ask another question.}

### {550}{}{[he glares at you] Helped, huh? You are fast... Still, their tasks are always simple... Okay then, listen: you are, like, fugitive, right? So you can't show your face. But the guards in Tartarus have uniforms that keep their faces covered. So you just need to obtain such uniform, and you can freely walk into Tartarus, either through the station or through the Purgatory - assuming you are not afraid of Ferals...}
{550}{}{[他怒视你]帮了忙，是吗？你很快。。。尽管如此，他们的任务总是很简单。。。好吧，听着：你就像是逃犯，对吧？所以你不能露脸。但塔尔塔罗斯的警卫都穿着制服，遮住脸。所以你只需要获得这样的制服，你就可以自由地走进塔尔塔罗斯，无论是通过车站还是通过炼狱——假设你不怕野性。。。 -- [he glares at you] Helped, huh? You are fast... Still, their tasks are always simple... Okay then, listen: you are, like, fugitive, right? So you can't show your face. But the guards in Tartarus have uniforms that keep their faces covered. So you just need to obtain such uniform, and you can freely walk into Tartarus, either through the station or through the Purgatory - assuming you are not afraid of Ferals...}
### {551}{056}{Obtain such uniform, you say? Okay, where do I get it?}
{551}{056}{你说，得到这样的制服？好吧，我从哪里得到它？ -- Obtain such uniform, you say? Okay, where do I get it?}

### {560}{}{I know for sure that the Sunset Jackals are in possession of many different uniform suits. Let me point it on your map [he takes your organizer and puts coordinates into it] Hah, I remember some of our seekers had a couple of such things with them... So, the Jackals. They are scary people. Murderers, rapists - practically animals, not everyone can handle talking to them. But if you have a spine, you'll be fine. Look for Carl, the mechanic. He is alright. Should help you with the suit.}
{560}{}{我确信日落豺狼队拥有许多不同的制服。让我把它放在你的地图上[他拿着你的组织者，把坐标放进去]哈，我记得我们的一些寻求者随身携带了一些这样的东西。。。所以，豺狼。他们是可怕的人。杀人犯，强奸犯——实际上是动物，不是每个人都能应付得起和他们说话。但如果你有脊椎，你会没事的。找机械师卡尔。他没事。应该帮你穿西装。 -- I know for sure that the Sunset Jackals are in possession of many different uniform suits. Let me point it on your map [he takes your organizer and puts coordinates into it] Hah, I remember some of our seekers had a couple of such things with them... So, the Jackals. They are scary people. Murderers, rapists - practically animals, not everyone can handle talking to them. But if you have a spine, you'll be fine. Look for Carl, the mechanic. He is alright. Should help you with the suit.}
### {561}{999}{Sunset Jackals then... Frankly, I thought of more... Useful help. But thanks anyway.}
{561}{999}{日落豺狼。。。坦率地说，我想了更多。。。有用的帮助。不过还是要谢谢。 -- Sunset Jackals then... Frankly, I thought of more... Useful help. But thanks anyway.}
### {562}{999}{Oh, so I need to visit some bandits and steal away a suit of armor? Thanks a lot, old man, for your "help"... I'll manage somehow.}
{562}{999}{哦，所以我需要去拜访一些土匪，偷走一套盔甲？非常感谢，老人，你的“帮助”。。。我会设法的。 -- Oh, so I need to visit some bandits and steal away a suit of armor? Thanks a lot, old man, for your "help"... I'll manage somehow.}

### {570}{}{Tartarus? What Tar- Oh yeah, sure. I remember, new one. Okay then, listen: you are, like, fugitive, right? So you can't show your face. But the guards in Tartarus have uniforms that keep their faces covered. So you just need to obtain such uniform, and you can freely walk into Tartarus, either through the station or through the Purgatory - assuming you are not afraid of Ferals...}
{570}{}{塔尔塔罗斯？什么焦油-哦，是的，当然。我记得，新的。好吧，听着：你就像是逃犯，对吧？所以你不能露脸。但塔尔塔罗斯的警卫都穿着制服，遮住脸。所以你只需要获得这样的制服，你就可以自由地走进塔尔塔罗斯，无论是通过车站还是通过炼狱——假设你不怕野性。。。 -- Tartarus? What Tar- Oh yeah, sure. I remember, new one. Okay then, listen: you are, like, fugitive, right? So you can't show your face. But the guards in Tartarus have uniforms that keep their faces covered. So you just need to obtain such uniform, and you can freely walk into Tartarus, either through the station or through the Purgatory - assuming you are not afraid of Ferals...}
### {571}{056}{Obtain such uniform, you say? Okay, where do I get it?}
{571}{056}{你说，得到这样的制服？好吧，我从哪里得到它？ -- Obtain such uniform, you say? Okay, where do I get it?}

### {600}{}{Huh?.. No, no-no, not at all... It's just... We have so many problems and things to do here... Mostly problems... I think our dwellers need something to lift their spirits, except my legs are not good enough to run around... People need hope to survive. Maybe you could walk around the station and tell people that I'm going to give a speech? They should come and listen... Tell it at least 10 people and come back. I'll get the speech ready, okay?}
{600}{}{嗯？。。不，不，一点也不。。。只是。。。我们在这里有很多问题和事情要做。。。主要是问题。。。我认为我们的居民需要一些东西来振奋他们的精神，除了我的腿不够好，不能到处乱跑。。。人们需要生存的希望。也许你可以在车站周围走走，告诉人们我要发表演讲？他们应该来听。。。至少告诉10个人，然后回来。我会准备好演讲的，好吗？ -- Huh?.. No, no-no, not at all... It's just... We have so many problems and things to do here... Mostly problems... I think our dwellers need something to lift their spirits, except my legs are not good enough to run around... People need hope to survive. Maybe you could walk around the station and tell people that I'm going to give a speech? They should come and listen... Tell it at least 10 people and come back. I'll get the speech ready, okay?}
### {601}{QA}{Why not? 10 people, be right back.}
{601}{QA}{为什么不呢？10个人，马上回来。 -- Why not? 10 people, be right back.}
### {602}{999}{Uh, no, find yourself another errand boy.}
{602}{999}{不，找个跑腿的吧。 -- Uh, no, find yourself another errand boy.}
### {603}{999}{I have some business to do, I'll think about it.}
{603}{999}{我有一些事情要做，我会考虑一下的。 -- I have some business to do, I'll think about it.}


### {650}{}{So, did you talk to people? Are they coming?}
{650}{}{那么，你和别人说话了吗？他们来了吗？ -- So, did you talk to people? Are they coming?}
### {651}{999}{Actually, I'm working on it...}
{651}{999}{事实上，我正在努力。。。 -- Actually, I'm working on it...}
### {652}{066}{Yes, around a dozen of people should come.}
{652}{066}{是的，应该有十几个人来。 -- Yes, around a dozen of people should come.}
### {653}{}{It took too long, }
{653}{}{花了太长时间， -- It took too long, }
### {654}{}{, now I can't... Spare any time.}
{654}{}{，现在我不能。。。腾出时间。 -- , now I can't... Spare any time.}
### {655}{999}{I see, so all this running's been for nothing.}
{655}{999}{我明白了，所以这一切都是徒劳的。 -- I see, so all this running's been for nothing.}
### {656}{999}{I didn't know you needed it FAST. Oh well.}
{656}{999}{我不知道你需要它快。哦，好吧。 -- I didn't know you needed it FAST. Oh well.}


### {660}{}{Wonderful, I've just scribbled a couple of notes... Okay, let's go.}
{660}{}{太棒了，我刚刚写了几个笔记。。。好吧，我们走吧。 -- Wonderful, I've just scribbled a couple of notes... Okay, let's go.}
### {661}{StartBonoSpeach}{[follow Bono]}
{661}{StartBonoSpeach}{[跟随波诺 -- follow Bono]}

### {670}{}{Yeah... I think it went pretty well. Now everyone will remember that we are one big family and we'll survive only by taking care of each other. I hope it will boost the morale. Thank you for bringing everyone.}
{670}{}{是 啊我认为进展得很顺利。现在每个人都会记住，我们是一个大家庭，只有互相照顾才能生存。我希望这能鼓舞士气。谢谢你带大家来。 -- Yeah... I think it went pretty well. Now everyone will remember that we are one big family and we'll survive only by taking care of each other. I hope it will boost the morale. Thank you for bringing everyone.}
### {671}{068}{Uh... Well, you're welcome. I expected some reward though.}
{671}{068}{嗯不客气。不过我期待着一些奖励。 -- Uh... Well, you're welcome. I expected some reward though.}
### {672}{999}{No problem, it was nothing.}
{672}{999}{没问题，没什么。 -- No problem, it was nothing.}
### {673}{999}{Of course, don't sweat it, old man!}
{673}{999}{当然，别担心，老头！ -- Of course, don't sweat it, old man!}

### {680}{}{A reward? You want something from ME? From US? All I can give you is advice... Advice to watch carefully where are you now, }
{680}{}{奖励？你想从我这里得到什么？来自美国？我能给你的只是建议。。。建议小心观察你现在在哪里， -- A reward? You want something from ME? From US? All I can give you is advice... Advice to watch carefully where are you now, }
### {681}{}{. I have nothing more.}
{681}{}{。我什么都没有了。 -- . I have nothing more.}
### {682}{999}{I understand. See you later.}
{682}{999}{我理解。回头见。 -- I understand. See you later.}
### {683}{999}{I got it. Goodbye, Bono.}	
{683}{999}{我明白了。再见，波诺。 -- I got it. Goodbye, Bono.}


### {690}{}{He is looking for her again? I don't even know how to help the poor guy... He buried Nadine around 5 years ago. She was always sick, we tried to help as we could - but the death took her. Joe was very worried so much. I remembered how he locked himself inside of that old wagon for days, carving the memorial plaque for her grave. That plaque was so beautiful... I don't quite remember how it looked. Maybe you should go outside, find her grave near the fountain and look at it. Maybe if you remind Joe about the plaque, he'll get his memory back.}
{690}{}{他又在找她？我甚至不知道如何帮助这个可怜的家伙。。。大约5年前他埋葬了纳丁。她总是生病，我们尽力帮助她，但她去世了。乔非常担心。我记得他是如何把自己锁在那辆旧马车里好几天，为她的坟墓雕刻纪念牌匾的。那块牌匾太美了。。。我不太记得它看起来怎么样了。也许你应该走出去，在喷泉附近找到她的坟墓，看看它。也许如果你提醒乔这块牌匾，他会找回记忆的。 -- He is looking for her again? I don't even know how to help the poor guy... He buried Nadine around 5 years ago. She was always sick, we tried to help as we could - but the death took her. Joe was very worried so much. I remembered how he locked himself inside of that old wagon for days, carving the memorial plaque for her grave. That plaque was so beautiful... I don't quite remember how it looked. Maybe you should go outside, find her grave near the fountain and look at it. Maybe if you remind Joe about the plaque, he'll get his memory back.}
### {691}{999}{Oh man. Okay, I'll try.}
{691}{999}{哦，天哪。好吧，我试试看。 -- Oh man. Okay, I'll try.}

#
#????????? ?????????????????????????????????????																																																														
#
### {700}{}{[looks at you in anticipation]}
{700}{}{[期待地看着你 -- looks at you in anticipation]}
### {701}{}{Yes? Something else?}
{701}{}{对还有别的吗？ -- Yes? Something else?}
### {702}{}{Did you want to say something?}
{702}{}{你想说什么吗？ -- Did you want to say something?}
### {703}{}{What do you need?}
{703}{}{你需要什么？ -- What do you need?}
### {704}{}{Bono is going to give some speech. Something important.}
{704}{}{波诺将发表演讲。一些重要的事情。 -- Bono is going to give some speech. Something important.}
### {705}{}{You should come to listen to Bono speaking.}
{705}{}{你应该来听波诺讲话。 -- You should come to listen to Bono speaking.}
### {706}{}{Bono is going to give a speech soon, he asks to come by and listen.}
{706}{}{波诺很快就要发表演讲了，他要求过来听。 -- Bono is going to give a speech soon, he asks to come by and listen.}
### {707}{}{Go to Bono's place, he wants to share a couple of words.}
{707}{}{去波诺的住处，他想和大家分享几句话。 -- Go to Bono's place, he wants to share a couple of words.}
### {708}{}{Okay, I'll come around.}
{708}{}{好的，我会回心转意的。 -- Okay, I'll come around.}
### {709}{}{I don't know, so many things to do... But I'll tell my friends.}
{709}{}{我不知道，有很多事情要做…但我会告诉我的朋友。 -- I don't know, so many things to do... But I'll tell my friends.}
### {710}{}{Bono? Okay, I'll come to listen.}
{710}{}{波诺？好的，我来听。 -- Bono? Okay, I'll come to listen.}
### {711}{}{Yeah, this ghoul is worth listening to. Of course, I'll come.}
{711}{}{是的，这个食尸鬼值得听。当然，我会来的。 -- Yeah, this ghoul is worth listening to. Of course, I'll come.}
### {712}{}{No, nothing. Bye.}
{712}{}{不，什么都没有。再见 -- No, nothing. Bye.}
### {713}{}{I'm just wandering around. Everything's alright.}
{713}{}{我只是四处闲逛。一切都好。 -- I'm just wandering around. Everything's alright.}
### {714}{}{Good, we'll be waiting.}
{714}{}{很好，我们等着。 -- Good, we'll be waiting.}
### {715}{}{Very good! See you around!}
{715}{}{非常好！回头见！ -- Very good! See you around!}
### {716}{}{Okay, deal.}
{716}{}{好吧，成交。 -- Okay, deal.}
### {720}{}{You convinced enough dwellers to come, it's time to tell Bono that everything's ready.}	
{720}{}{你说服了足够多的居民来，是时候告诉波诺一切都准备好了。 -- You convinced enough dwellers to come, it's time to tell Bono that everything's ready.}
###
### ?????????
###
### {750}{}{Yes, I've heard... It's unbelievable how ANYTHING could grow there! I think we could make an arrangement... We could buy the fertilizer from you. Say, 20 batteries for a sack. What do you think? I can't offer more, but we need at least 10 sacks!}
{750}{}{是的，我听说。。。令人难以置信的是，任何东西都能在那里生长！我想我们可以做个安排。。。我们可以从你那里买肥料。比方说，一袋20个电池。你怎么看？我不能提供更多，但我们至少需要10袋！ -- Yes, I've heard... It's unbelievable how ANYTHING could grow there! I think we could make an arrangement... We could buy the fertilizer from you. Say, 20 batteries for a sack. What do you think? I can't offer more, but we need at least 10 sacks!}
### {751}{}{It's a deal! Wait, I'll bring the first batch.}
{751}{}{这是一笔交易！等等，我会带来第一批。 -- It's a deal! Wait, I'll bring the first batch.}
### {752}{}{I don't know. I need to think...}
{752}{}{我不知道。我需要思考。。。 -- I don't know. I need to think...}
### {760}{}{Very good. Put it here. Yes, like that. Peter will come by to take it. Thank you, here's your payment. [he gives you }
{760}{}{很好。放在这里。是的，就像那样。彼得会过来取的。谢谢你，这是你的付款。[他给你的 -- Very good. Put it here. Yes, like that. Peter will come by to take it. Thank you, here's your payment. [he gives you }
### {761}{}{ batteries] I'm waiting for another delivery, heh-heh.}
{761}{}{电池]我在等另一批货，呵呵。 --  batteries] I'm waiting for another delivery, heh-heh.}
### {762}{}{ batteries] Let's call it a day. This must be enough to grow food for everyone. Thanks a lot, you saved us all.}
{762}{}{电池]今天到此为止。这一定足以为每个人种植食物。非常感谢，你救了我们所有人。 --  batteries] Let's call it a day. This must be enough to grow food for everyone. Thanks a lot, you saved us all.}
### {763}{}{[take your reward] Sure, it won't be too long. See you soon.}
{763}{}{当然，不会太久。再见。 -- [take your reward] Sure, it won't be too long. See you soon.}
### {764}{}{[take your reward] Glad to be of help. Bye.}	
{764}{}{[接受你的奖励]很高兴能提供帮助。再见 -- [take your reward] Glad to be of help. Bye.}
###
#
#???? ????																																																														
#
{800}{}{}
### {801}{}{Greetings, my friends!}
{801}{}{问候，我的朋友们！ -- Greetings, my friends!}
### {802}{}{You all know that now we are facing a hard times,}
{802}{}{你们都知道，现在我们正面临一个艰难的时期， -- You all know that now we are facing a hard times,}
### {803}{}{But together we are capable of overcoming any difficulties!}
{803}{}{但是我们能够一起克服任何困难！ -- But together we are capable of overcoming any difficulties!}
### {804}{}{You know for sure that I am the man of my word!}
{804}{}{你肯定知道，我是信守诺言的人！ -- You know for sure that I am the man of my word!}
### {805}{}{And I promise you, sooner or later we will get our right to live in Tartarus!}
{805}{}{我向你保证，我们迟早会得到在塔尔塔罗斯生活的权利！ -- And I promise you, sooner or later we will get our right to live in Tartarus!}
### {806}{}{The guards almost agreed to let us in!}
{806}{}{警卫几乎同意让我们进去！ -- The guards almost agreed to let us in!}
### {807}{}{So it won't be long until all of us will be safe!}
{807}{}{所以用不了多久，我们所有人都会安全！ -- So it won't be long until all of us will be safe!}
### {808}{}{I assure you that in the nearest future everything will be alright again.}
{808}{}{我向你保证，在不久的将来，一切都会好起来的。 -- I assure you that in the nearest future everything will be alright again.}
### {809}{}{Be patient to yourself and to the ones around you, together we'll work through this hardships!}
{809}{}{对自己和周围的人要有耐心，我们会一起度过难关！ -- Be patient to yourself and to the ones around you, together we'll work through this hardships!}
### {810}{}{Thank you for your attention, my friends.}
{810}{}{谢谢你的关注，我的朋友们。 -- Thank you for your attention, my friends.}
{811}{}{}
{812}{}{}																																																											
#??????????????????(????????????? ???????)																																																														
#																																																															
{1000}{}{}																																																															
{1001}{}{}																																																															
{1002}{}{}																																																															
{1003}{}{}																																																															
{1004}{}{}																																																															
{1005}{}{}																																																															
{1006}{}{}																																																															
{1007}{}{}																																																															
{1008}{}{}																																																															
{1009}{}{}																																																															
#																																																															
#??????????????????(??????????? ???????)																																																															
#																																																															
{1010}{}{}																																																															
{1011}{}{}																																																															
{1012}{}{}																																																															
{1013}{}{}																																																															
{1014}{}{}																																																															
{1015}{}{}																																																															
{1016}{}{}																																																															
{1017}{}{}																																																															
{1018}{}{}																																																															
{1019}{}{}																																																															
#																																																															
#??????????????????(????????????? ???????)																																																														
#																																																															
{1020}{}{}																																																															
{1021}{}{}																																																															
{1022}{}{}																																																															
{1023}{}{}																																																															
{1024}{}{}																																																															
{1025}{}{}																																																															
{1026}{}{}																																																															
{1027}{}{}																																																															
{1028}{}{}																																																															
{1029}{}{}																																																															
#																																																															
#??????????????????(?????????????																																																															
#																																																															
### {1030}{}{Peter has told me everything about Hugo, we need to leave...}																																																															
{1030}{}{彼得告诉了我关于雨果的一切，我们需要离开。。。 -- Peter has told me everything about Hugo, we need to leave...}
### {1031}{}{We need to leave this place fast.}																																																															
{1031}{}{我们需要尽快离开这个地方。 -- We need to leave this place fast.}
### {1032}{}{Vultures from Olympus can be here at any moment.}																																																															
{1032}{}{奥林巴斯的秃鹫随时都可能在这里。 -- Vultures from Olympus can be here at any moment.}
### {1033}{}{We are doomed here, Defenders will kill us all.}																																																															
{1033}{}{我们在这里注定要失败，保卫者会杀了我们所有人。 -- We are doomed here, Defenders will kill us all.}
### {1034}{}{We need to decide where to go from here.}																																																															
{1034}{}{我们需要决定从这里走向何方。 -- We need to decide where to go from here.}
{1035}{}{}																																																															
{1036}{}{}																																																															
{1037}{}{}																																																															
{1038}{}{}																																																															
{1039}{}{}
