### {101}{}{When are you going to take me home?}
{101}{}{你打算什么时候带我回家？ -- When are you going to take me home?}
### {102}{}{Right away, let's go.}
{102}{}{马上，我们走。 -- Right away, let's go.}
### {103}{}{I'll be back.}
{103}{}{我会回来的。 -- I'll be back.}
### {104}{}{OK, sir, I'll follow you.}
{104}{}{好的，先生，我跟你来。 -- OK, sir, I'll follow you.}
### {105}{}{Can I ask you something?}
{105}{}{我能问你点什么吗？ -- Can I ask you something?}
### {106}{}{OK, Steve, let's go.}
{106}{}{好吧，史蒂夫，我们走吧。 -- OK, Steve, let's go.}
### {107}{}{About what?}
{107}{}{关于什么？ -- About what?}
### {108}{}{Can you use some weapons to protect yourself?}
{108}{}{你能用一些武器来保护自己吗？ -- Can you use some weapons to protect yourself?}
### {109}{}{Nothing now.}
{109}{}{现在什么都没有。 -- Nothing now.}
### {110}{}{Well, my father taught me how to handle throwing weapons. He says that I'm too young for a gun and that knives can be just as dangerous. }
{110}{}{嗯，我父亲教我如何处理投掷武器。他说，我还太年轻，拿不起枪，刀具也同样危险。 -- Well, my father taught me how to handle throwing weapons. He says that I'm too young for a gun and that knives can be just as dangerous. }
### {111}{}{OK, Steve, just don't hurt yourself with those.}
{111}{}{好吧，史蒂夫，只是不要用这些伤害你自己。 -- OK, Steve, just don't hurt yourself with those.}
### {112}{}{Let me ask you something else.}
{112}{}{让我再问你一件事。 -- Let me ask you something else.}
### {113}{}{Thank you, mister.}
{113}{}{谢谢你，先生。 -- Thank you, mister.}
### {114}{}{I'm going with my mom.}
{114}{}{我要和我妈妈一起去。 -- I'm going with my mom.}
### {115}{}{Goodbye, mister.}
{115}{}{再见，先生。 -- Goodbye, mister.}
### {116}{}{Am I going to see you again?}
{116}{}{我还会再见到你吗？ -- Am I going to see you again?}
### {117}{}{Bye!}
{117}{}{再见 -- Bye!}
### {118}{}{...(no response)...}
{118}{}{…（没有回应）。。。 -- ...(no response)...}
### {119}{}{...(he's breathing but lying very still)...}
{119}{}{…（他在呼吸，但躺得很稳）。。。 -- ...(he's breathing but lying very still)...}
### {120}{}{...(breathes shallow)...}
{120}{}{…（浅呼吸）。。。 -- ...(breathes shallow)...}
### {121}{}{...(he struggles to breathe)...}
{121}{}{…（他挣扎着呼吸）。。。 -- ...(he struggles to breathe)...}
### {122}{}{::surprised:: Oh, what did you do...}
{122}{}{：：惊讶：：哦，你做了什么。。。 -- ::surprised:: Oh, what did you do...}
### {123}{}{Thank you, I feel so much better.}
{123}{}{谢谢你，我感觉好多了。 -- Thank you, I feel so much better.}
