{101}{}{When are you going to take me home?}
{102}{}{Right away, let's go.}
{103}{}{I'll be back.}
#
{104}{}{OK, sir, I'll follow you.}
{105}{}{Can I ask you something?}
{106}{}{OK, Steve, let's go.}
#
{107}{}{About what?}
{108}{}{Can you use some weapons to protect yourself?}
{109}{}{Nothing now.}
#
{110}{}{Well, my father taught me how to handle throwing weapons. He says that I'm too young for a gun and that knives can be just as dangerous. }
{111}{}{OK, Steve, just don't hurt yourself with those.}
{112}{}{Let me ask you something else.}
#
{113}{}{Thank you, mister.}
{114}{}{I'm going with my mom.}
{115}{}{Goodbye, mister.}
{116}{}{Am I going to see you again?}
{117}{}{Bye!}
#
{118}{}{...(no response)...}
{119}{}{...(he's breathing but lying very still)...}
{120}{}{...(breathes shallow)...}
{121}{}{...(he struggles to breathe)...}
#
{122}{}{::surprised:: Oh, what did you do...}
{123}{}{Thank you, I feel so much better.}
