### {100}{}{I'm busy now.}
{100}{}{我现在很忙。 -- I'm busy now.}
### {101}{}{Sorry, sir.}
{101}{}{对不起，先生。 -- Sorry, sir.}
### {102}{}{I must get down to business.}
{102}{}{我必须开始谈正事了。 -- I must get down to business.}
### {103}{}{All this paperwork...}
{103}{}{所有这些文书工作。。。 -- All this paperwork...}
### {104}{}{Hm... where's letter A?}
{104}{}{嗯…字母A在哪里？ -- Hm... where's letter A?}
### {105}{}{Hey, you helped Fred. I'm glad that someone did the job right. But there's something more important you must do now. You see, there's a water problem in this region. The residents of Golden Valley are not experiencing this yet, because we are covering their water losses with our own reserves, but...}
{105}{}{嘿，你帮了弗雷德。我很高兴有人做得对。但你现在必须做一些更重要的事情。你看，这个地区有水资源问题。金谷的居民还没有经历这种情况，因为我们正在用自己的储备来弥补他们的水损失，但是。。。 -- Hey, you helped Fred. I'm glad that someone did the job right. But there's something more important you must do now. You see, there's a water problem in this region. The residents of Golden Valley are not experiencing this yet, because we are covering their water losses with our own reserves, but...}
### {106}{}{Let me guess... You are running low on water?}
{106}{}{让我猜猜。。。你缺水了？ -- Let me guess... You are running low on water?}
### {107}{}{Well, not quite... We have a different kind of problem. The water cleaning system is fully automated and it's using a water chip for the cleaning procedures. And that's where the problem starts: The water chip is very old and needs to be replaced.}
{107}{}{嗯，不完全。。。我们有另一种问题。水清洁系统是全自动的，它使用水芯片进行清洁程序。这就是问题的开始：水芯片很旧，需要更换。 -- Well, not quite... We have a different kind of problem. The water cleaning system is fully automated and it's using a water chip for the cleaning procedures. And that's where the problem starts: The water chip is very old and needs to be replaced.}
### {108}{}{Where can I find a new water chip?}
{108}{}{我在哪里可以找到新的水芯片？ -- Where can I find a new water chip?}
### {109}{}{Look woman! My job is to guard buildings, not to go on some holy quest looking for a water chip! That can only end in a vat of goo. (no idea, why I said that?)}
{109}{}{看女人！我的工作是守卫建筑物，而不是去寻找水芯片！这只能以一大桶粘稠物告终。（不知道，我为什么这么说？） -- Look woman! My job is to guard buildings, not to go on some holy quest looking for a water chip! That can only end in a vat of goo. (no idea, why I said that?)}
### {110}{}{Can I help you, private?}
{110}{}{我能帮你吗，二等兵？ -- Can I help you, private?}
### {111}{}{About your water situation...}
{111}{}{关于你的水资源状况。。。 -- About your water situation...}
### {112}{}{Just a routine check, miss.}
{112}{}{只是例行检查，小姐。 -- Just a routine check, miss.}
### {113}{}{Yes?}
{113}{}{对 -- Yes?}
### {114}{}{I've brought this water chip, looks new enough. I'm sure it will do.}
{114}{}{我带来了这个水芯片，看起来很新。我相信会的。 -- I've brought this water chip, looks new enough. I'm sure it will do.}
### {115}{}{I got this water chip. Here... take a look.}
{115}{}{我得到了这个水芯片。在这里看一看。 -- I got this water chip. Here... take a look.}
### {116}{}{This appears to be an upgraded model, but guess what... This damn thing is broken! There's a capacitor missing. [Shows you with her finger.] You got to get me one that works!}
{116}{}{这似乎是一个升级的型号，但你猜怎么着。。。这该死的东西坏了！缺少一个电容器。[用她的手指给你看。]你得给我一个有效的！ -- This appears to be an upgraded model, but guess what... This damn thing is broken! There's a capacitor missing. [Shows you with her finger.] You got to get me one that works!}
### {117}{}{It looks fine to me... but OK. Guess I'll have to visit somebody again.}
{117}{}{我觉得很好……但没关系。我想我得再去拜访一个人了。 -- It looks fine to me... but OK. Guess I'll have to visit somebody again.}
### {118}{}{Get your own water chip, damn it!}
{118}{}{拿你自己的水芯片，该死！ -- Get your own water chip, damn it!}
### {119}{}{Get lost, incapable one!}
{119}{}{迷路吧，无能的人！ -- Get lost, incapable one!}
### {120}{}{Your job is already taken.}
{120}{}{你的工作已经被录用了。 -- Your job is already taken.}
### {121}{}{Just let me be.}
{121}{}{让我去吧。 -- Just let me be.}
### {122}{}{Did you find a functioning water chip!?}
{122}{}{你找到一个正常工作的水芯片了吗！？ -- Did you find a functioning water chip!?}
### {123}{}{I sure did, here you go.}
{123}{}{我确实做到了，给你。 -- I sure did, here you go.}
### {124}{}{Nope. Not yet.}
{124}{}{没有。还没有。 -- Nope. Not yet.}
### {125}{}{Yes, this one will do... [Looking at you.] I'm sorry I was yelling at you earlier. This work makes me very nervous, lots of paperwork, you know? Thank you for your services, private. You may go back to your post now.}
{125}{}{是的，这个就行了…[看着你。]很抱歉我刚才对你大喊大叫。这项工作让我很紧张，有很多文书工作，你知道吗？感谢您的服务，私人。你现在可以回去工作了。 -- Yes, this one will do... [Looking at you.] I'm sorry I was yelling at you earlier. This work makes me very nervous, lots of paperwork, you know? Thank you for your services, private. You may go back to your post now.}
### {126}{}{Sure thing.}
{126}{}{当然可以 -- Sure thing.}
### {127}{}{Sorry, no clue. You'll just have to find it... It's old hardware, but still in use by most water systems. }
{127}{}{抱歉，没有线索。你只需要找到它……它是旧硬件，但大多数供水系统仍在使用。 -- Sorry, no clue. You'll just have to find it... It's old hardware, but still in use by most water systems. }
### {128}{}{Thanks, I guess. I'm off to find the chip then.}
{128}{}{谢谢，我想。那我就去找芯片。 -- Thanks, I guess. I'm off to find the chip then.}
### {129}{}{Hm... where's letter A?}
{129}{}{嗯…字母A在哪里？ -- Hm... where's letter A?}
### {130}{}{All this paperwork...}
{130}{}{所有这些文书工作。。。 -- All this paperwork...}
### {131}{}{I must get down to business.}
{131}{}{我必须开始谈正事了。 -- I must get down to business.}
### {132}{}{OK... This goes there...}
{132}{}{好的…这个去那里。。。 -- OK... This goes there...}
### {133}{}{Signature looks good, where's that seal...}
{133}{}{签名看起来不错，印章在哪里。。。 -- Signature looks good, where's that seal...}
### {134}{}{Letter B... Here.}
{134}{}{字母B…在这里。 -- Letter B... Here.}
### {135}{}{Is it from A to Z or reversed?}
{135}{}{是从A到Z还是反转？ -- Is it from A to Z or reversed?}
### {136}{}{Uh... I need a break...}
{136}{}{嗯我需要休息一下。。。 -- Uh... I need a break...}
