{100}{}{Brrr.... hic....}
{101}{}{Trrrrr....}
{102}{}{Hrrrr....}
{103}{}{...(snoring)...}
#622==1
{104}{}{It looks like this person had a lot of beer. You can smell it all around him.}
{105}{}{[As you open the door... he steers a bit in his bed, looks like he's trying to get up but either he's too lazy
 or intoxicated.] ...Ahh... What a nice day. What day is it? I don't know... who cares. Where's my beer? [He tries to
 reach the bottle but suddenly stops when he sees you.] ...Phh... Who the hell are you!?}
{106}{}{Tell me, are you Bob?}
#
{107}{}{Yes, I'm Bob... Whadaya want?}
{108}{}{What were you doing last night Bob?}
#
{109}{}{Well, I... I can't remember... Oh maaan, was it that bad?}
{110}{}{Besides the fact that you could have been killed, nothing serious... }
{111}{}{You have committed several housebreaks and you'll have to answer some questions to the sheriff.}
# nothing serious...
{112}{}{You know, I feel just fine. As far as I can see, I'm still in one piece... and you broke into my house. I want
 you to leave before you make me angry!}
{113}{}{But, the door was open...}
{114}{}{You're coming with me Bob, even if I have to drag you out in a bag!}
#the door was open...
{115}{}{You liar! I never leave my door open, whether I’m drunk or sober. Go now, this is your final warning!}
{116}{}{Alright, I'm going.}
{117}{}{That does it, you smelly piece of shit!}
# again
{118}{}{You again, didn’t I tell you to get lost?! Looking for trouble, huh! I'm gonna show you something my old
 man taught me!}
{119}{}{I have a hearing problem, what's that clicking sound... is that a gun!?}
#house breaks....
{120}{}{I can't remember... I did such terrible things? I suppose you have proof?}
{121}{}{Well I don't...}
{122}{}{Yes I do have, here's one. [You point a gun at his face.] And here's another one; The sheriff wants to see you.
 NOW!}
# proof...
{123}{}{OK, please... You don't have to prove it... I'll go peacefully.}
{124}{}{That's the spirit.}
#well I don't...
{125}{}{Then, I suggest that you get lost and out of my house, windbag!}
#
{126}{}{I get free food here. I can even get some Nukas!}
{127}{}{I don't like jail, but service is good.}
{128}{}{Beer? No thanks!}
{129}{}{The sheriff also gave me some books to read.}
#106
{130}{}{[You make a gesture like you want to reach for him.] Wooo... I'm the boogieman. I'm here to get you!}
#130
{131}{}{[Bob freaks out instantly, trying to run while still in his bed. His bedclothes wrap all around him as he
 tries to untangle himself, screaming like crazy.]}
{132}{}{[Wait a bit, he might get tired eventually]...}
{133}{}{[You decide to end this nonsense.] Oh my... Hey, Bob, I'm sorry. I thought that might sober you up a bit. Are
 you alright?}
#132
{134}{}{[Couple of seconds later, after all that commotion, you realize he's not moving or making any sound. He
 looks surprisingly still, which seems somewhat suspicious, after all that fuss...]}
{135}{}{[Leave him be, he obviously doesn't want to go... and looks peaceful from here.] There, go back to sleep.}
{136}{}{[Somehow you know something is wrong... but you won't know for sure until you check.] Bob, if this is
 one of your jokes, better stop it. Do you hear me!?}
#136
{137}{}{[You come closer to the bed, shake him a couple of times with your hand. No response whatsoever.] Damn.
 (There's no easy way of telling this but you are looking at some quality time in jail or worse, unless you weren't here at
 all or some mysterious force intervened and put this poor bastard out of his misery. It's up to your twisted mind to
 decide.)}
{138}{}{(Accidents do happen these days.) Well, looks like this poor guy is a victim of a robbery gone wrong.}
{139}{}{(Lets say his drinking problem took a deadly toll on him.) What were you thinking Bob...}
#
{140}{}{He looks: Dead.}
#
{141}{}{I'm sure he won't talk.}
{142}{}{You found Jasmine's missing book and poor Bob can have some peace at last.}
