### {100}{}{This is Kate's motel.}
{100}{}{这是凯特的汽车旅馆。 -- This is Kate's motel.}
### {101}{}{There are always free rooms.}
{101}{}{总是有空闲的房间。 -- There are always free rooms.}
### {102}{}{My mom runs this place.}
{102}{}{这个地方是我妈妈经营的。 -- My mom runs this place.}
### {103}{}{First class motel service.}
{103}{}{一流的汽车旅馆服务。 -- First class motel service.}
### {104}{}{We've got fresh drinks.}
{104}{}{我们有新鲜饮料。 -- We've got fresh drinks.}
### {105}{}{Best motel in these parts.}
{105}{}{这些地方最好的汽车旅馆。 -- Best motel in these parts.}
### {106}{}{Kate is my mom.}
{106}{}{凯特是我妈妈。 -- Kate is my mom.}
### {107}{}{If you wanna check in, talk to my mom.}
{107}{}{如果你想办理入住手续，可以和我妈妈谈谈。 -- If you wanna check in, talk to my mom.}
### {108}{}{Hey mister, got any spare change?}
{108}{}{嘿，先生，有零钱吗？ -- Hey mister, got any spare change?}
### {109}{}{What?}
{109}{}{什么 -- What?}
### {110}{}{I'm fine.}
{110}{}{我很好。 -- I'm fine.}
