### {100}{}{Wow, did you see that?}
{100}{}{哇，你看到了吗？ -- Wow, did you see that?}
### {101}{}{I'm getting better.}
{101}{}{我正在好转。 -- I'm getting better.}
### {102}{}{This is not so bad.}
{102}{}{这还不错。 -- This is not so bad.}
### {103}{}{This practice sucks...}
{103}{}{这种做法糟透了。。。 -- This practice sucks...}
### {104}{}{Where's the bullet?}
{104}{}{子弹在哪里？ -- Where's the bullet?}
### {105}{}{I want some live targets...}
{105}{}{我想要一些活靶子。。。 -- I want some live targets...}
### {106}{}{Here I come...}
{106}{}{我来了。。。 -- Here I come...}
### {107}{}{Oh, close one...}
{107}{}{哦，关闭一个。。。 -- Oh, close one...}
### {108}{}{Eh... Wrong target.}
{108}{}{呃…目标不对。 -- Eh... Wrong target.}
### {109}{}{I want the machine gun.}
{109}{}{我想要机关枪。 -- I want the machine gun.}
