### {100}{}{Hi there.}
{100}{}{你好。 -- Hi there.}
### {101}{}{Heya.}
{101}{}{Heya。 -- Heya.}
### {102}{}{Good day, stranger.}
{102}{}{你好，陌生人。 -- Good day, stranger.}
### {103}{}{Nothing unusual today.}
{103}{}{今天没什么异常。 -- Nothing unusual today.}
### {104}{}{Those caves scare me.}
{104}{}{那些洞穴吓到我了。 -- Those caves scare me.}
### {105}{}{Those casino slots are very cool.}
{105}{}{那些赌场的老虎机很酷。 -- Those casino slots are very cool.}
### {106}{}{That statue looks familiar.}
{106}{}{那座雕像看起来很眼熟。 -- That statue looks familiar.}
### {107}{}{Yep.}
{107}{}{是的。 -- Yep.}
### {108}{}{Got any spare change?}
{108}{}{有零钱吗？ -- Got any spare change?}
### {109}{}{Somebody did a good job.}
{109}{}{有人做得很好。 -- Somebody did a good job.}
### {110}{}{That was very heroic.}
{110}{}{这真是太英勇了。 -- That was very heroic.}
### {111}{}{Setting free those citizens... Great thing!}
{111}{}{释放那些公民。。。太棒了！ -- Setting free those citizens... Great thing!}
### {112}{}{Mr. Basil had us all fooled!}
{112}{}{巴兹尔先生愚弄了我们！ -- Mr. Basil had us all fooled!}
### {113}{}{Things got a lot better.}
{113}{}{情况好多了。 -- Things got a lot better.}
### {114}{}{Hey, it's you!}
{114}{}{嘿，是你！ -- Hey, it's you!}
### {115}{}{Checked out our statue, yet?}
{115}{}{检查了我们的雕像，好吗？ -- Checked out our statue, yet?}
### {116}{}{Howdy!}
{116}{}{你好！ -- Howdy!}
### {117}{}{I'm gonna buy you a drink one day!}
{117}{}{总有一天我要请你喝一杯！ -- I'm gonna buy you a drink one day!}
### {118}{}{Please... Don't hurt me!}
{118}{}{请别伤害我！ -- Please... Don't hurt me!}
### {119}{}{You murderer!}
{119}{}{你这个杀人犯！ -- You murderer!}
### {120}{}{Get away from me!}
{120}{}{离我远点！ -- Get away from me!}
### {121}{}{Oh my God, it's the killer!}
{121}{}{天哪，是凶手！ -- Oh my God, it's the killer!}
### {122}{}{I want to live.}
{122}{}{我想活下去。 -- I want to live.}
### {123}{}{Just go away.}
{123}{}{走开。 -- Just go away.}
### {124}{}{I don't want to die!}
{124}{}{我不想死！ -- I don't want to die!}
### {125}{}{You see: a male resident.}
{125}{}{你看：一个男性居民。 -- You see: a male resident.}
### {126}{}{You see: a female resident.}
{126}{}{你看：一位女性居民。 -- You see: a female resident.}
