### {100}{}{I'm not feeling so good.}
{100}{}{我感觉不太好。 -- I'm not feeling so good.}
### {101}{}{It hurts.}
{101}{}{很疼。 -- It hurts.}
### {102}{}{Got any painkillers?}
{102}{}{有止痛药吗？ -- Got any painkillers?}
### {103}{}{Gimme a drink to take my pain away.}
{103}{}{给我一杯饮料来减轻我的疼痛。 -- Gimme a drink to take my pain away.}
### {104}{}{Doctor is really good.}
{104}{}{医生真的很好。 -- Doctor is really good.}
### {105}{}{Nothing better than relaxing on a bed.}
{105}{}{没有什么比在床上放松更好的了。 -- Nothing better than relaxing on a bed.}
### {106}{}{I miss my old TV.}
{106}{}{我想念我的旧电视。 -- I miss my old TV.}
### {107}{}{At times I get really bored.}
{107}{}{有时我真的很无聊。 -- At times I get really bored.}
### {108}{}{I'm so sleepy.}
{108}{}{我太困了。 -- I'm so sleepy.}
### {109}{}{ZZZZZZzzzzz....}
{109}{}{ZZZZZZZZ。。。 -- ZZZZZZzzzzz....}
### {110}{}{Please don't hurt me.}
{110}{}{请不要伤害我。 -- Please don't hurt me.}
### {111}{}{I won't tell anyone.}
{111}{}{我不会告诉任何人。 -- I won't tell anyone.}
