{100}{}{}
### {101}{}{Hello there private, I'm doc Fred. What can I do for you?}
{101}{}{你好，私人，我是弗雷德医生。我能为你做什么？ -- Hello there private, I'm doc Fred. What can I do for you?}
### {102}{}{What is your job here, are you a doctor of some kind?}
{102}{}{你在这里的工作是什么？你是某种医生吗？ -- What is your job here, are you a doctor of some kind?}
### {103}{}{The sergeant told me that you need some help.}
{103}{}{中士告诉我你需要帮助。 -- The sergeant told me that you need some help.}
### {104}{}{Nothing.}
{104}{}{没有什么 -- Nothing.}
### {105}{}{Of course, I'm a military doctor and also a scientist.}
{105}{}{当然，我是一名军医，也是一名科学家。 -- Of course, I'm a military doctor and also a scientist.}
### {106}{}{So what kind of scientific work are you conducting here.}
{106}{}{那么你在这里从事什么样的科学工作呢。 -- So what kind of scientific work are you conducting here.}
### {107}{}{Thanks for you time. See you later, doc.}
{107}{}{谢谢你抽出时间。回头见，医生。 -- Thanks for you time. See you later, doc.}
### {108}{}{Well, I work on a wide range of scientific fields but only two of them showed any real progress so far: weapons development and genetic engineering. Lets say a lack of funding and resources caught up with the rest of my projects...}
{108}{}{嗯，我在广泛的科学领域工作，但到目前为止，只有两个领域取得了真正的进展：武器开发和基因工程。比方说，我的其他项目缺乏资金和资源。。。 -- Well, I work on a wide range of scientific fields but only two of them showed any real progress so far: weapons development and genetic engineering. Lets say a lack of funding and resources caught up with the rest of my projects...}
### {109}{}{Good for you, let me ask you something else doc.}
{109}{}{对你很好，让我问你一些其他的问题，医生。 -- Good for you, let me ask you something else doc.}
### {110}{}{[Smiles.] Indeed... I almost forgot, sarge finally took my advice to assign some more manpower to this project. Alright, enough talk. I need you to watch over my office, I'm going to take care of some business. Please, just don't touch anything, this equipment is already very sensitive even without anyone fiddling with it. I'll be back shortly, just keep your eyes on my experiments in the meantime.}
{110}{}{确实。。。我差点忘了，sarge终于接受了我的建议，为这个项目分配了更多的人力。好吧，说够了。我需要你照看我的办公室，我要处理一些事务。请不要碰任何东西，即使没有人摆弄，这个设备也已经很敏感了。我很快就会回来，在此期间请注意我的实验。 -- [Smiles.] Indeed... I almost forgot, sarge finally took my advice to assign some more manpower to this project. Alright, enough talk. I need you to watch over my office, I'm going to take care of some business. Please, just don't touch anything, this equipment is already very sensitive even without anyone fiddling with it. I'll be back shortly, just keep your eyes on my experiments in the meantime.}
### {111}{}{OK, doc. I'm gonna take good care of them.}
{111}{}{好的，医生。我会好好照顾他们的。 -- OK, doc. I'm gonna take good care of them.}
### {112}{}{[Looking around.] Good, everything seems to be in order. Thank you private, you can go back to your post now.}
{112}{}{[环顾四周。]很好，一切似乎都很正常。私下里谢谢你，你现在可以回到你的岗位了。 -- [Looking around.] Good, everything seems to be in order. Thank you private, you can go back to your post now.}
### {113}{}{Sure thing, doc.}
{113}{}{当然，医生。 -- Sure thing, doc.}
### {114}{}{Hey, didn't I ask you to watch over my work!? [Looks worried.] Where's my prototype weapon that was lying on this table...? I don't believe it. If you can't even stand guard, then what are you doing in uniform? Get away from my lab before you break something! I'll have to tell the sarge about this, and you private, your ass is going to peel potatoes for all eternity!}
{114}{}{嘿，我不是叫你照看我的工作吗！？[看起来很担心。]我放在桌子上的原型武器在哪里。。。？我不相信。如果你甚至都不能站岗，那么你穿着制服干什么？在你打碎东西之前离开我的实验室！我得把这件事告诉沙奇，而你这个私生子，你的屁股要永远削土豆皮了！ -- Hey, didn't I ask you to watch over my work!? [Looks worried.] Where's my prototype weapon that was lying on this table...? I don't believe it. If you can't even stand guard, then what are you doing in uniform? Get away from my lab before you break something! I'll have to tell the sarge about this, and you private, your ass is going to peel potatoes for all eternity!}
### {115}{}{Yeah, whatever.}
{115}{}{是的，不管怎样。 -- Yeah, whatever.}
### {116}{}{What if I put a gun in your mouth... Will that shut you up!?}
{116}{}{如果我把枪放进你嘴里。。。这会让你闭嘴吗！？ -- What if I put a gun in your mouth... Will that shut you up!?}
### {117}{}{Let me see that...}
{117}{}{让我看看。。。 -- Let me see that...}
### {118}{}{Maybe something...}
{118}{}{也许有什么。。。 -- Maybe something...}
### {119}{}{I don't know...}
{119}{}{我不知道。。。 -- I don't know...}
### {120}{}{...Hm....hm...}
{120}{}{…嗯…嗯。。。 -- ...Hm....hm...}
### {121}{}{No...no...no...}
{121}{}{不…不…不。。。 -- No...no...no...}
### {122}{}{This is not good.}
{122}{}{这不好。 -- This is not good.}
### {123}{}{I'm busy now.}
{123}{}{我现在很忙。 -- I'm busy now.}
### {124}{}{Watch my stuff!}
{124}{}{小心我的东西！ -- Watch my stuff!}
### {125}{}{Get away from my place!}
{125}{}{离开我的住处！ -- Get away from my place!}
### {126}{}{I'm gonna tell the sarge about this!}
{126}{}{我要把这件事告诉警长！ -- I'm gonna tell the sarge about this!}
### {127}{}{You'll regret this!}
{127}{}{你会后悔的！ -- You'll regret this!}
### {128}{}{Bad private! You're a shame to your kind.}
{128}{}{糟糕的私人！你是同类的耻辱。 -- Bad private! You're a shame to your kind.}
### {129}{}{Thank you!}
{129}{}{非常感谢。 -- Thank you!}
### {130}{}{Excellent job private, the sarge will know about that.}
{130}{}{出色的私人工作，中士会知道的。 -- Excellent job private, the sarge will know about that.}
### {131}{}{Carry on private, good job.}
{131}{}{继续私生活，干得好。 -- Carry on private, good job.}
### {132}{}{So, what can I help you with, private?}
{132}{}{那么，我能帮你什么吗，私人？ -- So, what can I help you with, private?}
