{100}{}{Sector clear.}
{101}{}{I'm on duty, what about you?}
{102}{}{No time to talk.}
{103}{}{Do your job and let me do mine.}
{104}{}{Be about your business, soldier.}
{105}{}{Nothing to see here.}
{106}{}{It looks fine...}
{107}{}{No, sir.}
{108}{}{Yes?}
{109}{}{Roger that...}
{110}{}{Nothing unusual.}
#
{111}{}{Don't touch the door!}
{112}{}{Last warning!}
{113}{}{That's it. You're out of here!}
