### {100}{}{Hello there.}
{100}{}{你好。 -- Hello there.}
### {101}{}{I'm watching you, too.}
{101}{}{我也在看着你。 -- I'm watching you, too.}
### {102}{}{Just keep your hands where I can see them.}
{102}{}{把你的手放在我能看到的地方。 -- Just keep your hands where I can see them.}
### {103}{}{You want something?}
{103}{}{你想要什么？ -- You want something?}
### {104}{}{I don't have anything to sell.}
{104}{}{我没有什么可卖的。 -- I don't have anything to sell.}
### {105}{}{Don't hurt the staff.}
{105}{}{不要伤害员工。 -- Don't hurt the staff.}
### {106}{}{I don't want any trouble.}
{106}{}{我不想惹麻烦。 -- I don't want any trouble.}
### {107}{}{I'd suggest you leave now.}
{107}{}{我建议你现在就走。 -- I'd suggest you leave now.}
### {108}{}{Don't make me shoot you.}
{108}{}{别逼我开枪打你。 -- Don't make me shoot you.}
### {109}{}{Don't touch my stuff!}
{109}{}{不要碰我的东西！ -- Don't touch my stuff!}
### {110}{}{Back off, pal!}
{110}{}{退后，伙计！ -- Back off, pal!}
