### {100}{}{You'll pay for your crimes against humanity.}
{100}{}{你将为你的反人类罪行付出代价。 -- You'll pay for your crimes against humanity.}
### {101}{}{That's what you get for being a real bastard.}
{101}{}{这就是你作为一个真正的混蛋所得到的。 -- That's what you get for being a real bastard.}
### {102}{}{You've doomed us all for generations, you idiot.}
{102}{}{你注定了我们几代人的命运，你这个白痴。 -- You've doomed us all for generations, you idiot.}
### {103}{}{Despite all the warnings you had to go and do it, didn't you.}
{103}{}{尽管有这么多警告，你还是得去做，不是吗。 -- Despite all the warnings you had to go and do it, didn't you.}
### {104}{}{People like you only learn one way and one way alone - the hard way.}
{104}{}{像你这样的人只学习一种方法，而且只有一种方法——艰难的方法。 -- People like you only learn one way and one way alone - the hard way.}
