{100}{}{The door is using some strange electronic lock mechanism.}
{101}{}{The storage door is electronically secured. You can't seem to break it.}
{102}{}{This lock is electronically secured. You can't seem to open it. May need some clearance code or gadget to
 break it.}
{103}{}{[Chance to avoid detection: Sneak: }
{104}{}{You've unlocked the door swiftly and without complications.}
{105}{}{You have failed to disable the lock.}
{106}{}{[Sneak: }
{107}{}{That does nothing.}
{108}{}{You see: the supply room door.}
{109}{}{You see: the door to the arsenal.}
{110}{}{A heavy blast door with a security lock.}
{111}{}{The door is electronically secured.}
{112}{}{The door is open.}
