### {100}{}{Talk to the boss.}
{100}{}{和老板谈谈。 -- Talk to the boss.}
### {101}{}{Get away from me.}
{101}{}{离我远点。 -- Get away from me.}
### {102}{}{Talk to my boss.}
{102}{}{和我的老板谈谈。 -- Talk to my boss.}
### {103}{}{Here for the job?}
{103}{}{来找工作？ -- Here for the job?}
### {104}{}{I don't have time for this.}
{104}{}{我没有时间做这个。 -- I don't have time for this.}
### {105}{}{I'm busy here.}
{105}{}{我在这里很忙。 -- I'm busy here.}
### {106}{}{Go...}
{106}{}{去 -- Go...}
### {107}{}{Talk to Mr. Aston.}
{107}{}{和阿斯顿先生谈谈。 -- Talk to Mr. Aston.}
