### {100}{}{Hello, traveler.}
{100}{}{你好，旅行家。 -- Hello, traveler.}
### {101}{}{Traveling makes me happy.}
{101}{}{旅行使我快乐。 -- Traveling makes me happy.}
### {102}{}{Somebody set us up.}
{102}{}{有人陷害了我们。 -- Somebody set us up.}
### {103}{}{Go now, you've done enough for us.}
{103}{}{走吧，你已经为我们做得够多了。 -- Go now, you've done enough for us.}
### {104}{}{We're gonna move to another place.}
{104}{}{我们要搬到另一个地方去。 -- We're gonna move to another place.}
### {105}{}{It's all set for the trip.}
{105}{}{一切都准备好了。 -- It's all set for the trip.}
### {106}{}{Nothing interesting for us here.}
{106}{}{我们在这里没什么有趣的。 -- Nothing interesting for us here.}
