{100}{}{Yes?}
{101}{}{The holy one knows.}
{102}{}{This is holy ground.}
{103}{}{Speak, my child.}
{104}{}{Keep up the faith.}
{105}{}{Listen to the words of salvation.}
{106}{}{Want to hear some prayers?}
{107}{}{What is it that your spirit wants?}
{108}{}{Do you believe in the holy words?}
#
{109}{}{The evil one is here!}
{110}{}{Why does this one seek death?}
{111}{}{Hope that God will forgive you.}
{112}{}{No mercy for you!}
{113}{}{You are true evil.}
{114}{}{Begone before I spill holy water over you!}
