### {100}{}{I got nothing to talk about.}
{100}{}{我没什么好说的。 -- I got nothing to talk about.}
### {101}{}{Mind your own business!}
{101}{}{管好你自己的事！ -- Mind your own business!}
### {102}{}{I'm quite busy here.}
{102}{}{我在这里很忙。 -- I'm quite busy here.}
### {103}{}{Where are those papers?}
{103}{}{那些文件在哪里？ -- Where are those papers?}
### {104}{}{Is somebody going to give me those papers I requested?!}
{104}{}{有人会把我要的那些文件给我吗？！ -- Is somebody going to give me those papers I requested?!}
### {105}{}{OK, I've got a minute. Say, what do you want?}
{105}{}{好的，我有一分钟的时间。说，你想要什么？ -- OK, I've got a minute. Say, what do you want?}
### {106}{}{Looks like you have some kind of an organization going on here. Tell me what's the deal?}
{106}{}{看起来你这里有某种组织。告诉我怎么回事？ -- Looks like you have some kind of an organization going on here. Tell me what's the deal?}
### {107}{}{Nothing.}
{107}{}{没有什么 -- Nothing.}
### {108}{}{You again. What is it now?}
{108}{}{你又来了。现在是什么？ -- You again. What is it now?}
### {109}{}{Well, it's not a real organization, more like a group of people helping each other to survive. Believe it or not, we actually live here. Collecting and repairing all kinds of junk became our way of living. If it can be sold, even better.}
{109}{}{嗯，这不是一个真正的组织，更像是一群互相帮助生存的人。信不信由你，我们实际上住在这里。收集和修理各种垃圾成了我们的生活方式。如果它能卖出去，那就更好了。 -- Well, it's not a real organization, more like a group of people helping each other to survive. Believe it or not, we actually live here. Collecting and repairing all kinds of junk became our way of living. If it can be sold, even better.}
### {110}{}{Do you happen to know anything about missing people, they were last seen in this area?}
{110}{}{你知道失踪人员的情况吗，他们最后一次出现在这个地区？ -- Do you happen to know anything about missing people, they were last seen in this area?}
### {111}{}{I have some bad news for you. Someone's blaming your group for the recent disappearances.}
{111}{}{我有个坏消息要告诉你。有人把最近的失踪事件归咎于你的团队。 -- I have some bad news for you. Someone's blaming your group for the recent disappearances.}
### {112}{}{We'll get to that. You see, everybody thinks if they're gone, something bad had happened to them and usually we're the first on the suspect list. This time however I'm sure of one thing, something bad did happen and I know who did it.}
{112}{}{我们会做到的。你看，每个人都认为如果他们走了，他们就发生了不好的事情，通常我们是嫌疑人名单上的第一个。然而，这一次我确信一件事，确实发生了一些不好的事情，我知道是谁干的。 -- We'll get to that. You see, everybody thinks if they're gone, something bad had happened to them and usually we're the first on the suspect list. This time however I'm sure of one thing, something bad did happen and I know who did it.}
### {113}{}{So, what's the truth?}
{113}{}{那么，真相是什么呢？ -- So, what's the truth?}
### {114}{}{Basil's men did it, and I saw the whole thing! It was late, almost midnight. I was coming back from the field and saw two men and Mr. Basil. At first I thought they were just looking for something they had lost, but when I came a little closer I saw another person laying on the ground. I couldn't tell if that person passed out or... gone for real, but they didn't leave the poor guy on the ground. Instead they dragged him all the way and quickly disappeared into the night. I don't know where they left after that, it was too dangerous to even think of following them in the middle of the night. I tried to tell what happened... got ridiculed every time.}
{114}{}{巴兹尔的人做到了，我看到了整件事！已经很晚了，快到半夜了。我刚从田里回来，看见两个人和巴兹尔先生。起初我以为他们只是在寻找他们丢失的东西，但当我走近一点时，我看到另一个人躺在地上。我不知道那个人是昏倒了还是。。。真的走了，但他们没有把那个可怜的家伙留在地上。相反，他们一路拖着他，很快就消失在夜色中。我不知道他们在那之后离开了哪里，甚至想在半夜跟着他们都太危险了。我试着告诉你发生了什么。。。每次都被嘲笑。 -- Basil's men did it, and I saw the whole thing! It was late, almost midnight. I was coming back from the field and saw two men and Mr. Basil. At first I thought they were just looking for something they had lost, but when I came a little closer I saw another person laying on the ground. I couldn't tell if that person passed out or... gone for real, but they didn't leave the poor guy on the ground. Instead they dragged him all the way and quickly disappeared into the night. I don't know where they left after that, it was too dangerous to even think of following them in the middle of the night. I tried to tell what happened... got ridiculed every time.}
### {115}{}{Hm, I will tell the sheriff about it. Thanks for your help.}
{115}{}{嗯，我会告诉警长的。谢谢你的帮助。 -- Hm, I will tell the sheriff about it. Thanks for your help.}
### {116}{}{So sad, but I don't buy it!}
{116}{}{很难过，但我不相信！ -- So sad, but I don't buy it!}
### {117}{}{You really want to help? That's very nice to hear but we need others to know the truth as well. Just make sure you tell them everything I told you.}
{117}{}{你真的想帮忙吗？很高兴听到这个消息，但我们也需要其他人知道真相。只要确保你把我告诉你的一切都告诉他们。 -- You really want to help? That's very nice to hear but we need others to know the truth as well. Just make sure you tell them everything I told you.}
### {118}{}{No problem.}
{118}{}{没问题。 -- No problem.}
### {119}{}{Why not?! I mean, what's wrong, don't you believe me? I think there's something wrong with you, you stupid fuck! Get the fuck out of here! And don't think you'll get away in one piece if you ever come back!}
{119}{}{为什么不呢？我的意思是，怎么了，你不相信我吗？我觉得你有什么毛病，你这个蠢蛋！滚出去！如果你回来了，不要以为你会安然无恙！ -- Why not?! I mean, what's wrong, don't you believe me? I think there's something wrong with you, you stupid fuck! Get the fuck out of here! And don't think you'll get away in one piece if you ever come back!}
### {120}{}{Easy, I'm going.}
{120}{}{别紧张，我要走了。 -- Easy, I'm going.}
### {121}{}{Wait, I've got some treats for you! Want some fucking ice with your bullet holes!?}
{121}{}{等等，我有点心给你！想在你的弹孔里放点冰吗！？ -- Wait, I've got some treats for you! Want some fucking ice with your bullet holes!?}
### {122}{}{What the hell are you talking about? What disappearances? I think you better go, I don't like your tongue!}
{122}{}{你到底在说什么？什么失踪？我想你最好走了，我不喜欢你的舌头！ -- What the hell are you talking about? What disappearances? I think you better go, I don't like your tongue!}
### {123}{}{Hey you're back. Have you told them about this misunderstanding?}
{123}{}{嘿，你回来了。你把这个误会告诉他们了吗？ -- Hey you're back. Have you told them about this misunderstanding?}
### {124}{}{Not yet.}
{124}{}{还没有。 -- Not yet.}
### {125}{}{Yes I did, it was well received.}
{125}{}{是的，我做到了，反响很好。 -- Yes I did, it was well received.}
### {126}{}{Thank you very much stranger. I got some money and stims, take these and be on your way.}
{126}{}{非常感谢陌生人。我有一些钱和兴奋剂，拿着这些就上路吧。 -- Thank you very much stranger. I got some money and stims, take these and be on your way.}
### {127}{}{Thanks, take care.}
{127}{}{谢谢，保重。 -- Thanks, take care.}
### {128}{}{You helped us very much. Thanks again.}
{128}{}{你帮了我们很多。再次感谢。 -- You helped us very much. Thanks again.}
### {129}{}{No problem.}
{129}{}{没问题。 -- No problem.}
