### {100}{}{I'm busy.}
{100}{}{我很忙。 -- I'm busy.}
### {101}{}{Have a nice day, stranger.}
{101}{}{祝你今天愉快，陌生人。 -- Have a nice day, stranger.}
### {102}{}{Enjoying it here?}
{102}{}{喜欢这里吗？ -- Enjoying it here?}
### {103}{}{Check those slots, they are really good.}
{103}{}{检查一下这些插槽，它们真的很好。 -- Check those slots, they are really good.}
### {104}{}{Mary is always glad to have new customers.}
{104}{}{玛丽总是很高兴有新客户。 -- Mary is always glad to have new customers.}
### {105}{}{You're gonna love it!}
{105}{}{你会喜欢的！ -- You're gonna love it!}
