### {100}{}{I'm busy.}
{100}{}{我很忙。 -- I'm busy.}
### {101}{}{Good luck, stranger.}
{101}{}{祝你好运，陌生人。 -- Good luck, stranger.}
### {102}{}{Enjoying your stay here?}
{102}{}{你在这里过得愉快吗？ -- Enjoying your stay here?}
### {103}{}{Check those slots, they are really good.}
{103}{}{检查一下这些插槽，它们真的很好。 -- Check those slots, they are really good.}
### {104}{}{Mary is always glad to have new customers.}
{104}{}{玛丽总是很高兴有新客户。 -- Mary is always glad to have new customers.}
### {105}{}{You're gonna love it!}
{105}{}{你会喜欢的！ -- You're gonna love it!}
### {106}{}{Please, stay away from that door.}
{106}{}{请离那扇门远点。 -- Please, stay away from that door.}
### {107}{}{Last warning sir, don't make me use this.}
{107}{}{最后警告先生，不要让我用这个。 -- Last warning sir, don't make me use this.}
### {108}{}{Sorry sir, now I have to shoot you.}
{108}{}{对不起，先生，现在我必须开枪打你。 -- Sorry sir, now I have to shoot you.}
