### {100}{}{Yes?}
{100}{}{对 -- Yes?}
### {101}{}{The holy one knows.}
{101}{}{圣人知道。 -- The holy one knows.}
### {102}{}{This is holy ground.}
{102}{}{这是圣地。 -- This is holy ground.}
### {103}{}{Speak, my child.}
{103}{}{说吧，我的孩子。 -- Speak, my child.}
### {104}{}{Keep up the faith.}
{104}{}{保持信念。 -- Keep up the faith.}
### {105}{}{Listen to the words of salvation.}
{105}{}{听听拯救的话语。 -- Listen to the words of salvation.}
### {106}{}{Want to hear some prayers?}
{106}{}{想听听祈祷吗？ -- Want to hear some prayers?}
### {107}{}{What is it that your spirit wants?}
{107}{}{你的灵魂想要什么？ -- What is it that your spirit wants?}
### {108}{}{Do you believe in the holy words?}
{108}{}{你相信神圣的话语吗？ -- Do you believe in the holy words?}
### {109}{}{The evil one is here!}
{109}{}{邪恶的人来了！ -- The evil one is here!}
### {110}{}{Why does this one seek death?}
{110}{}{为什么这个人要找死？ -- Why does this one seek death?}
### {111}{}{Hope that God will forgive you.}
{111}{}{希望上帝会原谅你。 -- Hope that God will forgive you.}
### {112}{}{No mercy for you!}
{112}{}{没有怜悯你！ -- No mercy for you!}
### {113}{}{You are true evil.}
{113}{}{你真是邪恶。 -- You are true evil.}
### {114}{}{Begone before I spill holy water over you!}
{114}{}{在我把圣水洒在你身上之前开始吧！ -- Begone before I spill holy water over you!}
