{100}{}{Are you new in town?}
{101}{}{Haven't seen you before.}
{102}{}{Usually tribals come here looking for food.}
{103}{}{Are you a tribal of some sort?}
{104}{}{We all work in the power plant.}
{105}{}{Ever had a thought about how boring you are?}
{106}{}{We don't like strangers at all.}
{107}{}{This happens to be my house and you are bothering me!}
{108}{}{I have nothing to say.}
{109}{}{This is no place for you.}
#
{110}{}{I'm sure we could get along.}
{111}{}{Well, I was wrong about you.}
{112}{}{Glad to have you here.}
{113}{}{Your help is really appreciated.}
{114}{}{We owe you for this.}
{115}{}{You have my thanks, traveler.}
#
{116}{}{Damn savage!}
{117}{}{You murderer!}
{118}{}{Who do you think you are... killing people...}
{119}{}{Please don't kill me!}
{120}{}{I don't want to die.}
{121}{}{Just get away from me.}
{122}{}{Don't come any closer.}
#
{123}{}{Don't touch that door!}
{124}{}{Stop that!}
