{100}{}{You see: a man geared for combat.}
{101}{}{His face seems to say “dead or alive” and no questions asked.}
#
{102}{}{Just move on. I have no interest in you.}
{103}{}{Why not?}
{104}{}{[Move on.]}
#after 103
{105}{}{[Stares at you.]}
#cheeky (male)
{106}{}{Some say I'm rather handsome.}
 #cheeky (female)
{1106}{}{Some say I'm rather pretty.}
{107}{}{Perhaps we have a mutual interest.}
{108}{}{Gee... some people. [Move on.]}
#after 106/1106
{109}{}{[Looks you up and down once more. Then continues to stare.]}
{110}{}{Your loss.}
#after 107
{111}{}{How come?}
{112}{}{You're looking for people. I'm looking for people. Maybe we're looking for the same bunch.}
#after 112
{113}{}{Maybe, but I don't get chummy.}
{114}{}{I see. Tough guy, and all. Lone wolf sitting by the fire, staring in the empty desert, listening to the coyote's
 howl, having a wank, then going to bed alone.}
{115}{}{Still did you see anything? Group of four. Kinda on the move. Wearing Robes.}
#after 115
{116}{}{Tell me more...}
{117}{}{Nevermind.}
#
{118}{}{}
{119}{}{}
#floats when prison timer ran out
{120}{}{Hold it, convict!}
{121}{}{You're going back to jail, one way or another.}
{122}{}{}
{123}{}{}
#floats when player is evil
{124}{}{There's a price on your head that needs collecting.}
{125}{}{Scum of the wasteland. DIE!}
{126}{}{}
{127}{}{}
#
{128}{}{You have failed to use your steal skill.}
{129}{}{[Chance: }
#non-verbal floats
{130}{}{::looks you up and down::}
{131}{}{::chews for a while then spits::}
{132}{}{::checks his gun::}
{133}{}{::stares at you::}
