{100}{}{Hello stranger, this is the mayor's house. State your business here?}
{101}{}{Can I see the mayor, please?}
{102}{}{Nothing, just passing by.}
#
{103}{}{Sorry, he's a very busy man and can't see you right now.}
{104}{}{I demand you let me see him.}
{105}{}{I'll be going then.}
#demand...
{106}{}{Listen mister, this is your final warning. Walk away peacefully or I'll have to make you leave, by any means
 necessary.}
{107}{}{I'd like to see you try!}
{108}{}{Easy, easy, I'm going.}
#
{109}{}{Hello again, I told you our mayor is a busy man and he doesn't want to be disturbed. I'm here to ensure he
 remains undisturbed.}
{110}{}{Alright.}
#
{111}{}{I have a good reason to believe the mayor's life is in danger.}
#
{112}{}{[Looks at you for a few moments.] Alright, you can go in. Just be quick about it. Mr. Donson doesn't like long
 speeches.}
{113}{}{Got it.}
#door closed...
{114}{}{You can't get through a closed door, so back off!}
{115}{}{You can't go in. Mr. Donson doesn't want to see you!}
{116}{}{I suggest you leave that door cause Mr. Donson doesn't wanna see you.}
#
{117}{}{You can talk with Mr. Donson if you want.}
{118}{}{You should talk to Mr.Donson, not me.}
{119}{}{Do whatever mayor says and you'll be fine.}
{120}{}{Mr. Donson is inside.}
#
{121}{}{Hello again, this is the mayor's house. May I inquire as to your business here?}
