### {100}{}{Move along.}
{100}{}{继续前进。 -- Move along.}
### {101}{}{Just keep walking.}
{101}{}{继续走吧。 -- Just keep walking.}
### {102}{}{Beat it, convict.}
{102}{}{打它，罪犯。 -- Beat it, convict.}
### {103}{}{I'm doing fine so... Beat it!}
{103}{}{我做得很好，所以……别这样！ -- I'm doing fine so... Beat it!}
### {104}{}{Move it!}
{104}{}{快！ -- Move it!}
### {105}{}{Don't do that.}
{105}{}{不要那样做。 -- Don't do that.}
### {106}{}{Stay away from that door.}
{106}{}{离那扇门远点。 -- Stay away from that door.}
### {107}{}{That's it, you're history!}
{107}{}{就是这样，你是历史！ -- That's it, you're history!}
