### {100}{}{Are you new here?}
{100}{}{你是新来的吗？ -- Are you new here?}
### {101}{}{Where did you come from?}
{101}{}{你从哪里来的？ -- Where did you come from?}
### {102}{}{What's your number, pal?}
{102}{}{你的电话号码是多少，朋友？ -- What's your number, pal?}
### {103}{}{What are you looking at?!}
{103}{}{你在看什么？！ -- What are you looking at?!}
### {104}{}{Get away from me.}
{104}{}{离我远点。 -- Get away from me.}
### {105}{}{I can't talk with you.}
{105}{}{我不能和你说话。 -- I can't talk with you.}
### {106}{}{Who are you?}
{106}{}{你是谁？ -- Who are you?}
