### {100}{}{Robobrain function...incomplete.}
{100}{}{Robobrain功能。。。不完整。 -- Robobrain function...incomplete.}
### {101}{}{Initial state...on line.}
{101}{}{初始状态。。。在线。 -- Initial state...on line.}
### {102}{}{Self analysis...complete.}
{102}{}{自我分析。。。完成 -- Self analysis...complete.}
### {103}{}{Repair required...}
{103}{}{需要修复。。。 -- Repair required...}
### {104}{}{Mechanical parts...in order.}
{104}{}{机械零件。。。整齐 -- Mechanical parts...in order.}
### {105}{}{Battery capacity...70%.}
{105}{}{电池容量。。。70%。 -- Battery capacity...70%.}
### {106}{}{Using solar power...if needed.}
{106}{}{使用太阳能。。。如果需要。 -- Using solar power...if needed.}
### {107}{}{Circuits integrity...85%.}
{107}{}{电路完整性。。。85%。 -- Circuits integrity...85%.}
### {108}{}{widi, widi, widi}
{108}{}{查看，查看，查看 -- widi, widi, widi}
### {109}{}{...are you my mother...?} #Monkey Island{110}{}{I want to see the world... widi, widi}
{109}{}{...are you my mother...?} #Monkey Island{110}{}{我想看看世界。。。威迪，威迪 -- I want to see the world... widi, widi}
### {111}{}{widi, widi... Justin is great... widi, widi... why can't he find a nice girl...}
{111}{}{威迪，威迪。。。贾斯汀很棒。。。威迪，威迪。。。为什么他找不到一个好女孩。。。 -- widi, widi... Justin is great... widi, widi... why can't he find a nice girl...}
### {112}{}{widi, widi... ...Justin is building me a friend...}
{112}{}{威迪，威迪。。。贾斯汀正在培养我一个朋友。。。 -- widi, widi... ...Justin is building me a friend...}
### {113}{}{POWER LEAK! POWER LEAK!} # :){114}{}{Would you like to play a game of Solitaire with me...} #lol{115}{}{I'm not saying machines are superior, I'm merely stating a fact from my database.}
{113}{}{POWER LEAK! POWER LEAK!} # :){114}{}{Would you like to play a game of Solitaire with me...} #lol{115}{}{我并不是说机器更优秀，我只是从我的数据库中陈述一个事实。 -- I'm not saying machines are superior, I'm merely stating a fact from my database.}
### {116}{}{I did say any question, but perhaps you'd rather ask a sport question instead?} # Holly from Red Dwarf{117}{}{widi, widi... I can see the sun... widi, widi}
{116}{}{I did say any question, but perhaps you'd rather ask a sport question instead?} # Holly from Red Dwarf{117}{}{威迪，威迪。。。我能看到太阳。。。威迪，威迪 -- widi, widi... I can see the sun... widi, widi}
### {118}{}{You fixed Justin's robot, a friend for life. You earn 500 XP.}
{118}{}{你修理了贾斯汀的机器人，一个终生的朋友。您可以获得500经验值。 -- You fixed Justin's robot, a friend for life. You earn 500 XP.}
### {119}{}{[Science required: 70%]}
{119}{}{[所需科学：70% -- Science required: 70%]}
