### {100}{}{OK, this looks clean.}
{100}{}{好的，这个看起来很干净。 -- OK, this looks clean.}
### {101}{}{I'm done here.}
{101}{}{我受够了。 -- I'm done here.}
### {102}{}{Another cleaning day.}
{102}{}{又是一个清洁日。 -- Another cleaning day.}
### {103}{}{What a piece of garbage - this is going out.}
{103}{}{真是一堆垃圾——这东西要出去了。 -- What a piece of garbage - this is going out.}
### {104}{}{Somebody has to check those vents.}
{104}{}{必须有人检查那些通风口。 -- Somebody has to check those vents.}
### {105}{}{To the next room...}
{105}{}{去隔壁房间。。。 -- To the next room...}
### {106}{}{I got a whole day ahead.}
{106}{}{我还有一整天的时间。 -- I got a whole day ahead.}
### {107}{}{As good as new.}
{107}{}{和新的一样好。 -- As good as new.}
### {108}{}{Where did I put that soap.}
{108}{}{我把肥皂放哪儿了。 -- Where did I put that soap.}
### {109}{}{I just clean.}
{109}{}{我只是打扫卫生。 -- I just clean.}
### {110}{}{I can't help you.}
{110}{}{我帮不了你。 -- I can't help you.}
### {111}{}{Do you work here, 'cause I don't remember you.}
{111}{}{你在这里工作吗，因为我不记得你了。 -- Do you work here, 'cause I don't remember you.}
### {112}{}{You better do something useful.}
{112}{}{你最好做一些有用的事。 -- You better do something useful.}
### {113}{}{Did you see my soap?}
{113}{}{你看到我的肥皂了吗？ -- Did you see my soap?}
### {114}{}{I'm sure I put my broom somewhere around here.}
{114}{}{我确信我把扫帚放在这附近的什么地方了。 -- I'm sure I put my broom somewhere around here.}
### {115}{}{I can't help you, sir.}
{115}{}{我帮不了你，先生。 -- I can't help you, sir.}
### {116}{}{Good day, sir.}
{116}{}{你好，先生。 -- Good day, sir.}
### {117}{}{Hello there. I can clean your room if you want.}
{117}{}{你好。如果你愿意，我可以打扫你的房间。 -- Hello there. I can clean your room if you want.}
### {118}{}{Yes, sir, I'm cleaning.}
{118}{}{是的，先生，我在打扫。 -- Yes, sir, I'm cleaning.}
### {119}{}{I'm doing fine. How are you?}
{119}{}{我做得很好。你好吗 -- I'm doing fine. How are you?}
### {120}{}{Hi!}
{120}{}{你好 -- Hi!}
### {121}{}{Oh, just leave me.}
{121}{}{哦，离开我吧。 -- Oh, just leave me.}
### {122}{}{I wouldn?t cause any trouble.}
{122}{}{我不会的?不要惹任何麻烦。 -- I wouldn?t cause any trouble.}
### {123}{}{You don't have to kill me.}
{123}{}{你不必杀了我。 -- You don't have to kill me.}
### {124}{}{I'm getting away from you.}
{124}{}{我要离开你了。 -- I'm getting away from you.}
