### {100}{}{Welcome, customer. The name is Samuel. This is my store Weapons & Ammo. So, are you interested in buying some of my finest weapons?}
{100}{}{欢迎光临，客户。这个名字叫塞缪尔。这是我的武器弹药商店。那么，你有兴趣买一些我最好的武器吗？ -- Welcome, customer. The name is Samuel. This is my store Weapons & Ammo. So, are you interested in buying some of my finest weapons?}
### {101}{}{Show me your merchandise.}
{101}{}{让我看看你的商品。 -- Show me your merchandise.}
### {102}{}{Can you upgrade or modify some weapons?}
{102}{}{你能升级或修改一些武器吗？ -- Can you upgrade or modify some weapons?}
### {103}{}{No thanks.}
{103}{}{不用了，谢谢。 -- No thanks.}
### {104}{}{I can fix almost anything for you, sir. I can do several upgrades for small arms and rifles. If you need modifications, show me what you have.}
{104}{}{我几乎可以为你做任何事，先生。我可以为小武器和步枪做几次升级。如果你需要修改，给我看看你有什么。 -- I can fix almost anything for you, sir. I can do several upgrades for small arms and rifles. If you need modifications, show me what you have.}
### {105}{}{OK, take a look.}
{105}{}{好的，看看。 -- OK, take a look.}
### {106}{}{Actually, I wanted to ask you something.}
{106}{}{事实上，我想问你一件事。 -- Actually, I wanted to ask you something.}
### {107}{}{Of course, my dear customer. Anything you need.}
{107}{}{当然，我亲爱的顾客。任何你需要的东西。 -- Of course, my dear customer. Anything you need.}
### {108}{}{Sorry, you got nothing I can work with. Can I do something else for you?}
{108}{}{对不起，你没有我能做的事。我能为你做点别的吗？ -- Sorry, you got nothing I can work with. Can I do something else for you?}
### {109}{}{Let me ask you something.}
{109}{}{让我问你一件事。 -- Let me ask you something.}
### {110}{}{Nothing, I'm out of here.}
{110}{}{没什么，我要离开这里。 -- Nothing, I'm out of here.}
### {111}{}{Welcome again, customer. What can I offer you today?}
{111}{}{再次欢迎，客户。今天我能为您提供什么？ -- Welcome again, customer. What can I offer you today?}
### {112}{}{Nothing, thanks.}
{112}{}{没什么，谢谢。 -- Nothing, thanks.}
### {113}{}{Nice doing business with you. Come back again.}
{113}{}{很高兴和你做生意。再来吧。 -- Nice doing business with you. Come back again.}
### {114}{}{Sure thing.}
{114}{}{当然可以 -- Sure thing.}
### {115}{}{You'll find nothing of interest there.}
{115}{}{你在那里找不到任何感兴趣的东西。 -- You'll find nothing of interest there.}
### {116}{}{Hands off!}
{116}{}{把手放开！ -- Hands off!}
### {117}{}{Don't touch that.}
{117}{}{别碰那个。 -- Don't touch that.}
### {126}{}{I can modify that 10mm pistol you have, for about $450.}
{126}{}{我可以修改你的10毫米手枪，大约450美元。 -- I can modify that 10mm pistol you have, for about $450.}
### {127}{}{Sure, here you go. [Give him the money.]}
{127}{}{当然，给你。[把钱给他。] -- Sure, here you go. [Give him the money.]}
### {128}{}{That's too much for me. I'll be back when I have the money.}
{128}{}{这对我来说太过分了。我有钱后会回来的。 -- That's too much for me. I'll be back when I have the money.}
### {129}{}{Alright, it's done. Take your time to test it. I can't guarantee it will work perfectly but I can assure you, when I do the job, you won't be back for a long time.}
{129}{}{好了，完成了。慢慢来测试一下。我不能保证它会完美工作，但我可以向你保证，当我完成这项工作时，你很长一段时间都不会回来。 -- Alright, it's done. Take your time to test it. I can't guarantee it will work perfectly but I can assure you, when I do the job, you won't be back for a long time.}
### {130}{}{Alright. Bye.}
{130}{}{好吧再见 -- Alright. Bye.}
### {131}{}{That hunting rifle could be upgraded. I can put a scope on it. It will improve your chances of hitting distant objects compared to the regular rifle. It will cost you just $500.}
{131}{}{那支猎枪可以升级。我可以在上面放一个瞄准镜。与普通步枪相比，它会提高你击中远处物体的机会。你只需花500美元。 -- That hunting rifle could be upgraded. I can put a scope on it. It will improve your chances of hitting distant objects compared to the regular rifle. It will cost you just $500.}
### {132}{}{That desert eagle you have... I could give it an expanded magazine for only $200.}
{132}{}{你拥有的那只沙漠鹰。。。我只要花200美元就能给它一本扩大版的杂志。 -- That desert eagle you have... I could give it an expanded magazine for only $200.}
### {133}{}{Your magnum looks like it could use some adjustments. You can purchase a speed loader for it, only $250.}
{133}{}{你的马格南看起来可能需要一些调整。你可以为它购买一台快速装载机，只需250美元。 -- Your magnum looks like it could use some adjustments. You can purchase a speed loader for it, only $250.}
### {134}{}{I can upgrade your pipe rifle, adding one extra gun barrel to it. Weapon will gain some weight but it will do more damage even with regular 10mm JHP. This adjustment will cost you $550.}
{134}{}{我可以升级你的管式步枪，增加一个额外的枪管。武器会增加一些重量，但即使使用普通的10毫米JHP也会造成更大的伤害。这次调整将花费550美元。 -- I can upgrade your pipe rifle, adding one extra gun barrel to it. Weapon will gain some weight but it will do more damage even with regular 10mm JHP. This adjustment will cost you $550.}
### {135}{}{Sorry, I've used up all my tools and materials.}
{135}{}{对不起，我用完了所有的工具和材料。 -- Sorry, I've used up all my tools and materials.}
### {136}{}{Alright, can I ask you something?}
{136}{}{好吧，我能问你点什么吗？ -- Alright, can I ask you something?}
### {137}{}{What can you tell me about this place?}
{137}{}{关于这个地方你能告诉我什么？ -- What can you tell me about this place?}
### {138}{}{It used to be an old storage room for coal and now I rent it. The best part is, I have to live in this filth. I actually pay money to our dear mayor just to let us sleep on the boxes and wake up with the refreshing smell of mold and rat droppings. And that's how my working day starts...}
{138}{}{它曾经是一个旧的煤炭储藏室，现在我把它租了下来。最棒的是，我不得不住在这种肮脏的地方。事实上，我付钱给我们亲爱的市长，只是为了让我们睡在盒子上，醒来时闻到令人耳目一新的霉菌和老鼠粪便的味道。这就是我工作日的开始。。。 -- It used to be an old storage room for coal and now I rent it. The best part is, I have to live in this filth. I actually pay money to our dear mayor just to let us sleep on the boxes and wake up with the refreshing smell of mold and rat droppings. And that's how my working day starts...}
### {139}{}{Oh, it can't be that bad... let me ask you something else.}
{139}{}{哦，不会那么糟糕。。。让我再问你一件事。 -- Oh, it can't be that bad... let me ask you something else.}
### {140}{}{I told you. If you like sleeping on cardboard and start enjoying the smell, you'll get used to it splendidly. Ah, who am I kidding... feels like modern middle ages...}
{140}{}{我告诉过你。如果你喜欢睡在纸板上并开始享受这种气味，你会非常习惯的。啊，我在跟谁开玩笑。。。感觉就像现代中世纪。。。 -- I told you. If you like sleeping on cardboard and start enjoying the smell, you'll get used to it splendidly. Ah, who am I kidding... feels like modern middle ages...}
### {141}{}{What about this place?}
{141}{}{这个地方怎么样？ -- What about this place?}
