### {100}{}{Move along.}
{100}{}{继续前进。 -- Move along.}
### {101}{}{Are you lost?}
{101}{}{你迷路了吗？ -- Are you lost?}
### {102}{}{If you need directions, talk to Brian.}
{102}{}{如果你需要指引，可以和布莱恩谈谈。 -- If you need directions, talk to Brian.}
### {103}{}{I'm not a tourist guide.}
{103}{}{我不是导游。 -- I'm not a tourist guide.}
### {104}{}{I'm busy.}
{104}{}{我很忙。 -- I'm busy.}
### {105}{}{Can't you see I'm working here?}
{105}{}{你看不出我在这里工作吗？ -- Can't you see I'm working here?}
### {106}{}{I can't help you.}
{106}{}{我帮不了你。 -- I can't help you.}
### {107}{}{Wrong person, pal.}
{107}{}{错人了，伙计。 -- Wrong person, pal.}
### {108}{}{Don't touch that!}
{108}{}{别碰那个！ -- Don't touch that!}
### {109}{}{That locker belongs to Leonard, so back off!}
{109}{}{那个储物柜是伦纳德的，退后！ -- That locker belongs to Leonard, so back off!}
### {110}{}{Stay away from that locker! I'm not going to repeat myself.}
{110}{}{离储物柜远点！我不打算重复我的话。 -- Stay away from that locker! I'm not going to repeat myself.}
