### {100}{}{Wrong place, pal!}
{100}{}{错地方了，伙计！ -- Wrong place, pal!}
### {101}{}{I'm watching you so don't try to sneak!}
{101}{}{我在监视你，所以不要偷偷溜！ -- I'm watching you so don't try to sneak!}
### {102}{}{We don't have anything you need.}
{102}{}{我们没有你需要的东西。 -- We don't have anything you need.}
### {103}{}{I don't like strangers, they always cause trouble.}
{103}{}{我不喜欢陌生人，他们总是制造麻烦。 -- I don't like strangers, they always cause trouble.}
### {104}{}{This ain't a public library.}
{104}{}{这不是公共图书馆。 -- This ain't a public library.}
### {105}{}{You go back the way you came.}
{105}{}{你回到你来的路上。 -- You go back the way you came.}
### {106}{}{We only deal with professionals.}
{106}{}{我们只与专业人士打交道。 -- We only deal with professionals.}
### {107}{}{No, I don't like bad people.}
{107}{}{不，我不喜欢坏人。 -- No, I don't like bad people.}
### {108}{}{We don't deal with murderers.}
{108}{}{我们不对付杀人犯。 -- We don't deal with murderers.}
### {109}{}{This is no place for you, outlaw!}
{109}{}{这里不适合你，歹徒！ -- This is no place for you, outlaw!}
### {110}{}{The killing of the innocent is not in my job description!}
{110}{}{杀害无辜者不在我的工作描述中！ -- The killing of the innocent is not in my job description!}
### {111}{}{You got some serious problems, murderer scum!}
{111}{}{你有一些严重的问题，杀人的渣滓！ -- You got some serious problems, murderer scum!}
