### {100}{}{Why me here?}
{100}{}{为什么我在这里？ -- Why me here?}
### {101}{}{Who you people?}
{101}{}{你们是谁？ -- Who you people?}
### {102}{}{Bad spirits came and took the good ones.}
{102}{}{坏灵魂来了，带走了好灵魂。 -- Bad spirits came and took the good ones.}
### {103}{}{I want home to my village.}
{103}{}{我想回到我的村庄。 -- I want home to my village.}
### {104}{}{Set us free, spirit good.}
{104}{}{让我们自由，精神好。 -- Set us free, spirit good.}
### {105}{}{Save us or be cursed.}
{105}{}{要么救我们，要么被诅咒。 -- Save us or be cursed.}
### {106}{}{How could this be? Gods never lie.}
{106}{}{这怎么可能呢？上帝从不说谎。 -- How could this be? Gods never lie.}
