### {100}{}{Hello.}
{100}{}{你好 -- Hello.}
### {101}{}{You want something?}
{101}{}{你想要什么？ -- You want something?}
### {102}{}{Where's the fire?}
{102}{}{火在哪里？ -- Where's the fire?}
### {103}{}{Do you work here?}
{103}{}{你在这里工作吗？ -- Do you work here?}
### {104}{}{You're new here, right?}
{104}{}{你是新来的，对吧？ -- You're new here, right?}
### {105}{}{Are you always bothering people like this?}
{105}{}{你总是这样打扰别人吗？ -- Are you always bothering people like this?}
### {106}{}{I must get back to work.}
{106}{}{我必须回去工作。 -- I must get back to work.}
### {107}{}{Wh... Who are you? What do you want?}
{107}{}{为什么。。。你是谁？你想要什么？ -- Wh... Who are you? What do you want?}
### {108}{}{I work for chief Brian, that's all you have to know. I've got some questions for you.}
{108}{}{我为布莱恩局长工作，你只需要知道这些。我有一些问题要问你。 -- I work for chief Brian, that's all you have to know. I've got some questions for you.}
### {109}{}{I'm... out of here.}
{109}{}{我是离开这里。 -- I'm... out of here.}
### {110}{}{Everybody here works for Brian. Questions... what questions? Can't I have peace just for one moment. Oh well... ask what you want.}
{110}{}{这里的每个人都为布莱恩工作。问题。。。什么问题？我就不能平静一下吗。哦，好吧。。。问问你想要什么。 -- Everybody here works for Brian. Questions... what questions? Can't I have peace just for one moment. Oh well... ask what you want.}
### {111}{}{What do you do here?}
{111}{}{你在这里做什么？ -- What do you do here?}
### {112}{}{Actually, I don't need to ask you anything right now.}
{112}{}{事实上，我现在什么都不需要问你。 -- Actually, I don't need to ask you anything right now.}
### {113}{}{I'm new here and I just wanted to get familiar with somebody.}
{113}{}{我是新来的，我只是想熟悉一些人。 -- I'm new here and I just wanted to get familiar with somebody.}
### {114}{}{I'm responsible for cleaning, collecting garbage, and stuff.}
{114}{}{我负责打扫卫生，收集垃圾等等。 -- I'm responsible for cleaning, collecting garbage, and stuff.}
### {115}{}{Thanks. Let me ask you something else.}
{115}{}{谢谢让我再问你一件事。 -- Thanks. Let me ask you something else.}
### {116}{}{New guy, nice to have you here. People call me Chris. I'm the only one who can get anything you need. So, if you want some stuff, talk to me. Right?}
{116}{}{新人，很高兴有你在这里。人们叫我克里斯。我是唯一一个能得到你需要的任何东西的人。所以，如果你想要一些东西，和我谈谈。对吧？ -- New guy, nice to have you here. People call me Chris. I'm the only one who can get anything you need. So, if you want some stuff, talk to me. Right?}
### {117}{}{Sure thing. Can you get some strong stuff, to keep me high but not too much?}
{117}{}{当然可以你能给我一些强壮的东西吗？让我保持兴奋，但不要太兴奋？ -- Sure thing. Can you get some strong stuff, to keep me high but not too much?}
### {118}{}{Let me ask you something else.}
{118}{}{让我再问你一件事。 -- Let me ask you something else.}
### {119}{}{Like I said, anything you need. Most of that stuff is legal everywhere else but that bastard Brian completely cut off the supplies, even if half of the population is addicted to it. There will be trouble if these people don't get what they paid for, sooner than he thinks.}
{119}{}{就像我说的，任何你需要的。大多数东西在其他地方都是合法的，但那个混蛋布莱恩完全切断了供应，即使一半的人对此上瘾。如果这些人不能比他想象的更快地得到他们所支付的，就会有麻烦。 -- Like I said, anything you need. Most of that stuff is legal everywhere else but that bastard Brian completely cut off the supplies, even if half of the population is addicted to it. There will be trouble if these people don't get what they paid for, sooner than he thinks.}
### {120}{}{Sounds bad. How's the situation?}
{120}{}{听起来很糟糕。情况怎么样？ -- Sounds bad. How's the situation?}
### {121}{}{I think he's right. But first he should prevent people from selling that shit.}
{121}{}{我认为他是对的。但首先，他应该阻止人们出售这些垃圾。 -- I think he's right. But first he should prevent people from selling that shit.}
### {122}{}{It's terrible! Brian ordered more inspections which affected my business... and it's getting worse. I have to find another way to bring some stuff down here before we run out of it, or we're screwed!}
{122}{}{太可怕了！布赖恩下令进行更多的检查，这影响了我的业务。。。而且情况越来越糟。在我们用完之前，我必须找到另一种方法把一些东西带到这里，否则我们就完蛋了！ -- It's terrible! Brian ordered more inspections which affected my business... and it's getting worse. I have to find another way to bring some stuff down here before we run out of it, or we're screwed!}
### {123}{}{What are you going to do?}
{123}{}{你打算怎么办？ -- What are you going to do?}
### {124}{}{Why do you suddenly care? You have been in this town for, what, five minutes and you already feel sad. I don't buy that crap! You are no better than these addicts that buy drugs from me. Look how desperate they are. Jet became their whole life...}
{124}{}{你为什么突然在意？你已经在这个小镇上呆了五分钟了，你已经感到难过了。我不买账！你并不比那些从我这里买毒品的瘾君子好。看看他们有多绝望。喷气式飞机成了他们的全部生活。。。 -- Why do you suddenly care? You have been in this town for, what, five minutes and you already feel sad. I don't buy that crap! You are no better than these addicts that buy drugs from me. Look how desperate they are. Jet became their whole life...}
### {125}{}{And I'm here to change that, you monster!}
{125}{}{我是来改变这一点的，你这个怪物！ -- And I'm here to change that, you monster!}
### {126}{}{You... to change!? Just being here makes you a loser. I remember a man who wanted to change things, Charles. Yep... but he choose the wrong way to do it. He thought that stealing money from Brian was going to pass unnoticed. He was too clumsy for his own good so I had to take over his work, and his money of course. It would be such a shame to spent it like he did, giving it to the poor...}
{126}{}{你改变！？只是在这里会让你成为失败者。我记得有个人想改变现状，查尔斯。是的。。。但他选择了错误的方式。他认为从布赖恩那里偷钱会被忽视。为了他自己的利益，他太笨拙了，所以我不得不接管他的工作，当然还有他的钱。如果像他那样把钱花掉，给穷人，那将是一种耻辱。。。 -- You... to change!? Just being here makes you a loser. I remember a man who wanted to change things, Charles. Yep... but he choose the wrong way to do it. He thought that stealing money from Brian was going to pass unnoticed. He was too clumsy for his own good so I had to take over his work, and his money of course. It would be such a shame to spent it like he did, giving it to the poor...}
### {127}{}{You took his money, and what about his life?}
{127}{}{你拿走了他的钱，他的生活怎么样？ -- You took his money, and what about his life?}
### {128}{}{I don't think I remember what happened to him. I'm going now, don't try to follow me!}
{128}{}{我想我不记得他发生了什么事了。我现在要走了，别跟我走！ -- I don't think I remember what happened to him. I'm going now, don't try to follow me!}
### {129}{}{Where are you going...}
{129}{}{你要去哪里。。。 -- Where are you going...}
### {130}{}{Stop there! Don't come any closer!}
{130}{}{停在那里！别再靠近了！ -- Stop there! Don't come any closer!}
### {131}{}{I killed Charles and I'm not going to give up. This is going to end now!}
{131}{}{我杀了查尔斯，我不会放弃。这就要结束了！ -- I killed Charles and I'm not going to give up. This is going to end now!}
### {132}{}{I'm coming, oh mighty one!}
{132}{}{我来了，哦，强大的一个！ -- I'm coming, oh mighty one!}
### {133}{}{You again, can I get you something?}
{133}{}{你再说一遍，我能给你拿点什么吗？ -- You again, can I get you something?}
### {134}{}{Sure thing, what do you need?}
{134}{}{当然，你需要什么？ -- Sure thing, what do you need?}
### {135}{}{Can you get me something strong, to keep me in a good mood?}
{135}{}{你能给我弄点烈性酒，让我保持好心情吗？ -- Can you get me something strong, to keep me in a good mood?}
### {136}{}{Nothing at the moment.}
{136}{}{现在什么都没有。 -- Nothing at the moment.}
