### {100}{}{You see: a man geared for combat.}
{100}{}{你看：一个为战斗做好准备的人。 -- You see: a man geared for combat.}
### {101}{}{His face seems to say ?dead or alive? and no questions asked.}
{101}{}{他的脸似乎在说?死的还是活的? 没有任何问题。 -- His face seems to say ?dead or alive? and no questions asked.}
### {102}{}{Just move on. I have no interest in you.}
{102}{}{继续吧，我对你没有兴趣。 -- Just move on. I have no interest in you.}
### {103}{}{Why not?}
{103}{}{为什么不呢？ -- Why not?}
### {104}{}{[Move on.]}
{104}{}{[继续前进。 -- Move on.]}
### {105}{}{[Stares at you.]}
{105}{}{[盯着你看。 -- Stares at you.]}
### {106}{}{Some say I'm rather handsome.}
{106}{}{有人说我很帅。 -- Some say I'm rather handsome.}
### {1106}{}{Some say I'm rather pretty.}
{1106}{}{有人说我相当漂亮。 -- Some say I'm rather pretty.}
### {107}{}{Perhaps we have a mutual interest.}
{107}{}{也许我们有共同的利益。 -- Perhaps we have a mutual interest.}
### {108}{}{Gee... some people. [Move on.]}
{108}{}{哇有些人。[继续。] -- Gee... some people. [Move on.]}
### {109}{}{[Looks you up and down once more. Then continues to stare.]}
{109}{}{[再次上下打量你。然后继续凝视。 -- Looks you up and down once more. Then continues to stare.]}
### {110}{}{Your loss.}
{110}{}{你的损失。 -- Your loss.}
### {111}{}{How come?}
{111}{}{为什么？ -- How come?}
### {112}{}{You're looking for people. I'm looking for people. Maybe we're looking for the same bunch.}
{112}{}{你在找人。我在找人。也许我们在找同一群人。 -- You're looking for people. I'm looking for people. Maybe we're looking for the same bunch.}
### {113}{}{Maybe, but I don't get chummy.}
{113}{}{也许吧，但我并不亲密。 -- Maybe, but I don't get chummy.}
### {114}{}{I see. Tough guy, and all. Lone wolf sitting by the fire, staring in the empty desert, listening to the coyote's howl, having a wank, then going to bed alone.}
{114}{}{我明白了。硬汉，等等。孤独的狼坐在炉火旁，凝视着空旷的沙漠，听着郊狼的嚎叫，咕咕叫着，然后独自上床睡觉。 -- I see. Tough guy, and all. Lone wolf sitting by the fire, staring in the empty desert, listening to the coyote's howl, having a wank, then going to bed alone.}
### {115}{}{Still did you see anything? Group of four. Kinda on the move. Wearing Robes.}
{115}{}{你还是看到什么了吗？四人一组。有点移动。穿着长袍。 -- Still did you see anything? Group of four. Kinda on the move. Wearing Robes.}
### {116}{}{Tell me more...}
{116}{}{告诉我更多。。。 -- Tell me more...}
### {117}{}{Nevermind.}
{117}{}{永远不会。 -- Nevermind.}
{118}{}{}
{119}{}{}
### {120}{}{Hold it, convict!}
{120}{}{住手，罪犯！ -- Hold it, convict!}
### {121}{}{You're going back to jail, one way or another.}
{121}{}{不管怎样，你都要回监狱了。 -- You're going back to jail, one way or another.}
{122}{}{}
{123}{}{}
### {124}{}{There's a price on your head that needs collecting.}
{124}{}{你头上有一个价格需要收集。 -- There's a price on your head that needs collecting.}
### {125}{}{Scum of the wasteland. DIE!}
{125}{}{荒原上的渣滓。死！ -- Scum of the wasteland. DIE!}
{126}{}{}
{127}{}{}
### {128}{}{You have failed to use your steal skill.}
{128}{}{你没有使用你的偷技。 -- You have failed to use your steal skill.}
### {129}{}{[Chance: }
{129}{}{[机会： -- [Chance: }
### {130}{}{::looks you up and down::}
{130}{}{::上下打量你 -- looks you up and down::}
### {131}{}{::chews for a while then spits::}
{131}{}{::嚼一会儿然后吐 -- chews for a while then spits::}
### {132}{}{::checks his gun::}
{132}{}{::检查他的枪 -- checks his gun::}
### {133}{}{::stares at you::}
{133}{}{::盯着你 -- stares at you::}
