### {100}{}{Duntown bulletin:}
{100}{}{邓敦公报： -- Duntown bulletin:}
### {101}{}{Jobs}
{101}{}{工作 -- Jobs}
### {102}{}{Drinks}
{102}{}{饮料 -- Drinks}
### {103}{}{Shops}
{103}{}{商店 -- Shops}
### {104}{}{[Exit.]}
{104}{}{[出口 -- Exit.]}
### {105}{}{[This column is empty.]}
{105}{}{[此列为空。 -- This column is empty.]}
### {106}{}{No news? This place must be boring as hell... [Back.]}
{106}{}{没有消息？这个地方一定很无聊。。。[返回。] -- No news? This place must be boring as hell... [Back.]}
### {107}{}{[One listed:]}
{107}{}{[列出的一个： -- One listed:]}
### {108}{}{Needed: One person for a job. Requirements: skilled gunman, otherwise do something useful and don't get yourself killed. For more info talk to Brian, chief of power plant security.}
{108}{}{需要：一个人做一份工作。要求：熟练的枪手，否则做一些有用的事情，不要让自己丧命。欲了解更多信息，请与发电厂安全主管Brian联系。 -- Needed: One person for a job. Requirements: skilled gunman, otherwise do something useful and don't get yourself killed. For more info talk to Brian, chief of power plant security.}
### {109}{}{[One place listed:]}
{109}{}{[列出了一个位置： -- One place listed:]}
### {110}{}{Susane's bar}
{110}{}{苏珊酒吧 -- Susane's bar}
### {111}{}{We serve drinks, food and a happy smile. Stop by and check it out.}
{111}{}{我们提供饮料、食物和愉快的微笑。顺便来看看。 -- We serve drinks, food and a happy smile. Stop by and check it out.}
### {112}{}{[Back.]}
{112}{}{[返回 -- Back.]}
### {113}{}{[Two places listed:]}
{113}{}{[列出了两个位置： -- Two places listed:]}
### {114}{}{Andy's plumber store}
{114}{}{安迪的水管工商店 -- Andy's plumber store}
### {115}{}{Laura's}
{115}{}{劳拉的 -- Laura's}
### {116}{}{I sell pipes with various profiles, valves, tools... you name it. My store is located on the north side of the residential area. Bring some cash so we can talk turkey. See you later.}
{116}{}{我销售各种型材、阀门、工具的管道。。。你能想到的。我的店在住宅区的北侧。带些现金来，这样我们就可以畅所欲言了。回头见。 -- I sell pipes with various profiles, valves, tools... you name it. My store is located on the north side of the residential area. Bring some cash so we can talk turkey. See you later.}
### {117}{}{Is this guy on a hunger strike or what... [Back.]}
{117}{}{这家伙是在绝食还是什么。。。[返回。] -- Is this guy on a hunger strike or what... [Back.]}
### {118}{}{All kinds of high valued commodities from the wasteland. Everybody's taste will be satisfied. I'm just south from the administration office.}
{118}{}{来自荒原的各种高价值商品。每个人的口味都会得到满足。我就在行政办公室的南边。 -- All kinds of high valued commodities from the wasteland. Everybody's taste will be satisfied. I'm just south from the administration office.}
### {119}{}{[Back.]}
{119}{}{[返回 -- Back.]}
