{100}{}{Hold it right there. You must complete your test to pass through this door.}
{101}{}{Excuse me, but what is this "test" thing all about?}
{102}{}{Who the hell are you... and why on earth are you all dressed like that?}
{103}{}{You let me pass or I'll make you pass through my fists!}
#excuse me...
{104}{}{Your task is to pass the tests, get certain items and only then can I let you go through.}
{105}{}{What items are you speaking of, and why do I have to pass the tests?}
#
{106}{}{As many others before, you must "try" to prove that you are responsible enough to live outside these walls.
 I said "try" because nobody succeeded so far... They all died trying, as you will if you let your mind wander. You must
 walk through the path of shadows and flames, try your strength against creatures of hell. And finally bring me from
 each test room, one stone of wisdom as proof.}
{107}{}{Oh, the dramatization... You said that nobody succeeded before, what's the purpose of going through all this?}
{108}{}{Is there any way I could prove myself other than going through these tests?}
# 107
{109}{}{Those who are of evil deeds are being put onto these, call them trials, as both punishment and purification
 process. There is no other way... Except if you chose to be executed, which is performed on those who see death as the
 easier way out. Right now, you do have a choice.}
{110}{}{I guess it'll be smarter collecting rocks then.}
# 108
{111}{}{Yes there is... you can choose between tests, the only true path to your salvation... or death by execution,
 which will also lead you to your final destination, only quicker. The only question is what will you choose?}
{112}{}{I'll take these tests, can't be that hard, right...}
{113}{}{I choose you let me through or you'll be the one taking the quick way out.}
#who are you?
{114}{}{I'm here to make sure you do what you have been told to do. And help in a way, with guidance and some
 advice, if needed. My first advice is, you better pass all the tests or you'll never see the light of day again.}
{115}{}{I'll remember that, let me ask you something else.}
#
{116}{}{Your freedom is waiting but your time is running short. Ask what you will.}
#
{117}{}{I brought you these rocks from each and every test room. So, I did my part, now let me through.}
# enough
{118}{}{[Looking at the rocks with surprise.] Good enough for me. You've proven yourself! This is just one small step
 on your journey, what you do in the future... it's all up to you. Let your mind be your guide and may your heart have
 the strength to resist temptation along the way.}
{119}{}{Thanks, I guess I'm ready for a new beginning.}
#  not enough...1 rock
{120}{}{[Looking at your lone rock.] That is all you got? [Laughs.] Haha... You've got to do a whole lot better, don't
 waste my time on your dust collection! You must complete "all" the tests if you don't want to try your luck in the
 afterlife!}
{121}{}{Damn it...}
#
{122}{}{[Looking at the rocks.] Good, but you haven't finished your task! You must complete "all" the tests.}
#
{123}{}{Sorry, no time for talking. I must finish those tests.}
{124}{}{Can you take a look at this...?}
