### {100}{}{A message appears on the display: copying successful.}
{100}{}{显示屏上将显示一条消息：复制成功。 -- A message appears on the display: copying successful.}
### {101}{}{The display reads: error copying source.}
{101}{}{显示内容为：复制源时出错。 -- The display reads: error copying source.}
### {102}{}{A message appears on the display: copying successful.}
{102}{}{显示屏上将显示一条消息：复制成功。 -- A message appears on the display: copying successful.}
### {103}{}{The display reads: error copying source.}
{103}{}{显示内容为：复制源时出错。 -- The display reads: error copying source.}
### {104}{}{This item can only be used from the interface bar.}
{104}{}{此项只能从界面栏中使用。 -- This item can only be used from the interface bar.}
### {105}{}{You have nothing to copy on you.}
{105}{}{你身上没有可复制的东西。 -- You have nothing to copy on you.}
