### {100}{}{Hi there, stranger. Don't worry, we were just checking the site. Looks intact... [Tapping the ground.] You can return to whatever you were doing. I have to get back to my work now... [Takes his shovel.]}
{100}{}{你好，陌生人。别担心，我们只是在查看网站。看起来完好无损。。。[敲击地面。]你可以回到你正在做的任何事情。我现在得回去工作了。。。[拿起铲子。] -- Hi there, stranger. Don't worry, we were just checking the site. Looks intact... [Tapping the ground.] You can return to whatever you were doing. I have to get back to my work now... [Takes his shovel.]}
### {101}{}{I was just walking around, getting some fresh air...}
{101}{}{我只是四处走走，呼吸新鲜空气。。。 -- I was just walking around, getting some fresh air...}
### {102}{}{Sure, carry on. [Leave.]}
{102}{}{当然，继续。[离开。] -- Sure, carry on. [Leave.]}
### {103}{}{Hey, don't you think it's a little late for talking a walk?}
{103}{}{嘿，你不觉得现在谈散步有点晚了吗？ -- Hey, don't you think it's a little late for talking a walk?}
### {104}{}{Nope, I'm doing just fine. Say, saw anything unusual around here?}
{104}{}{没有，我做得很好。说，看到这里有什么异常吗？ -- Nope, I'm doing just fine. Say, saw anything unusual around here?}
### {105}{}{What do you need a shovel for?}
{105}{}{你需要铲子干什么？ -- What do you need a shovel for?}
### {106}{}{That's dandy, but you'll have to do it somewhere else. You are disturbing us!}
{106}{}{这很不错，但你必须在别的地方做。你打扰我们了！ -- That's dandy, but you'll have to do it somewhere else. You are disturbing us!}
### {107}{}{It wasn't my intention... I'm just wondering, what do you use the shovel for?}
{107}{}{这不是我的本意。。。我只是想知道，你用铲子干什么？ -- It wasn't my intention... I'm just wondering, what do you use the shovel for?}
### {108}{}{Why don't you come closer and take a look... I've got something... Right here... [Reaches for something under his robe.]}
{108}{}{你为什么不走近一点看看。。。我有东西。。。就在这里。。。[伸手去拿长袍下的东西。] -- Why don't you come closer and take a look... I've got something... Right here... [Reaches for something under his robe.]}
### {109}{}{That's it! You're going down, thieving scum!}
{109}{}{就是这样！你要堕落了，偷窃的渣滓！ -- That's it! You're going down, thieving scum!}
### {110}{}{You again... Don't you think it's a little late to walk about!?}
{110}{}{你又。。。你不觉得走路有点晚了吗！？ -- You again... Don't you think it's a little late to walk about!?}
### {111}{}{That grave looks pretty empty to me. You're not telling me the whole story...}
{111}{}{那个坟墓在我看来很空。你没有告诉我整个故事。。。 -- That grave looks pretty empty to me. You're not telling me the whole story...}
