{100}{}{What are you doing here? This is private property!}
{101}{}{I was told I could buy some... Uh... Slaves here.}
{102}{}{Who's in charge here?}
{103}{}{Nothing, I'm just looking around.}
{104}{}{Sorry, I was just going...}
#some slaves...
{105}{}{I think you're at the wrong address, pal! I'm wondering how you walked past the security, but you shouldn't
 have come here. Start counting some bullets!}
{106}{}{You mean, one for you and one for me?}
#just looking...
{107}{}{Are you a fucking retard!? That's the worst excuse I've heard in my life... Time to die, lost one!}
{108}{}{Well, lucky me...}
#just going...
{109}{}{Yes, you are going... to be wasted!}
{110}{}{I've got a better idea. Why don't you drop dead, you bastard?!}
#in charge...
{111}{}{Who wants to know?}
{112}{}{I do. [Make an angry face.]}
{113}{}{Well, I was just asking nicely...}
{114}{}{Actually this was a bad idea, I'm out of here.}
#i do...
{115}{}{And who the hell are you, the postman?! [Laughs.]}
{116}{}{Hey, I'm well known where I come from. So you show some respect!}
{117}{}{That's right, and I'm going to kick your ass!}
#recpect...
{118}{}{Alright, you'll get a respectable funeral!}
{119}{}{You're a real fucking asshole!}
#asked boss...
{120}{}{Alright, you can go in.}
{121}{}{Thanks.}
#
{122}{}{Watch your step, there's a mine field on the west.}
{123}{}{I'm busy here, talk to you later.}
{124}{}{Be quick about your business.}
{125}{}{My boss doesn't like people sniffing around, so do what you have to and leave.}
#
{126}{}{You possess a certain item that doesn't belong to you and my boss ordered me to shoot down any thief,
 including you. Nothing personal, I have to earn my pay, you know. I'll just make sure you don't make any more trouble
 here!}
{127}{}{Wait... uh, I'll give it back...}
{128}{}{Sure, you people always make me laugh.}
