### {100}{}{I'm busy here.}
{100}{}{我在这里很忙。 -- I'm busy here.}
### {101}{}{I can't help you.}
{101}{}{我帮不了你。 -- I can't help you.}
### {102}{}{Are you lost or something?}
{102}{}{你迷路了吗？ -- Are you lost or something?}
### {103}{}{No, I'm not the one you're looking for.}
{103}{}{不，我不是你要找的那个人。 -- No, I'm not the one you're looking for.}
### {104}{}{You sure don't look like a slaver.}
{104}{}{你看起来肯定不像个奴隶贩子。 -- You sure don't look like a slaver.}
### {105}{}{Keep walking.}
{105}{}{继续走。 -- Keep walking.}
