### {100}{}{Yes, can I help you?}
{100}{}{是的，我能帮你吗？ -- Yes, can I help you?}
### {101}{}{Do you sell something here?}
{101}{}{你在这里卖东西吗？ -- Do you sell something here?}
### {102}{}{What is this place?}
{102}{}{这是什么地方？ -- What is this place?}
### {103}{}{No, I was just leaving.}
{103}{}{不，我正要离开。 -- No, I was just leaving.}
### {104}{}{Of course, you must be looking for some of our finest laborers. They are hard working and well trained slaves. You aren't going to find such a good offer anywhere else. Please, take your time. So, want to see our stock?}
{104}{}{当然，你一定在寻找我们最优秀的劳工。他们是辛勤工作、训练有素的奴隶。在其他任何地方你都找不到这么好的报价。请慢慢来。那么，想看看我们的股票吗？ -- Of course, you must be looking for some of our finest laborers. They are hard working and well trained slaves. You aren't going to find such a good offer anywhere else. Please, take your time. So, want to see our stock?}
### {105}{}{No thanks, let me ask you something.}
{105}{}{不，谢谢，让我问你一件事。 -- No thanks, let me ask you something.}
### {106}{}{Actually, I have to be going now.}
{106}{}{事实上，我现在得走了。 -- Actually, I have to be going now.}
### {107}{}{Alright, just be quick about it.}
{107}{}{好吧，快一点。 -- Alright, just be quick about it.}
### {108}{}{This is our storage facility. We've got two sectors, one at the upper level and this one. Well, we got a third level below but we have no use for it. This place was a real mess when we first came. Some cleaning did the job pretty well. We were surprised to see all critical life support systems working, guess we were lucky.}
{108}{}{这是我们的仓储设施。我们有两个部门，一个在上层，另一个在这个部门。好吧，我们拿到了第三级，但我们没有用。我们刚来的时候这个地方真是一团糟。一些清洁工作做得很好。我们惊讶地看到所有关键的生命支持系统都在工作，我想我们很幸运。 -- This is our storage facility. We've got two sectors, one at the upper level and this one. Well, we got a third level below but we have no use for it. This place was a real mess when we first came. Some cleaning did the job pretty well. We were surprised to see all critical life support systems working, guess we were lucky.}
### {109}{}{Sure, see you later.}
{109}{}{当然，回头见。 -- Sure, see you later.}
### {110}{}{Not yet, so you got a lot of work lately?}
{110}{}{还没有，所以你最近有很多工作要做？ -- Not yet, so you got a lot of work lately?}
### {111}{}{You bet. Every day, we can barely keep our stock full... But it's pure profit. Sometimes it can be a real pain in the ass. For example, I hate office paperwork... But my boss insists. I have to carry this account book with me all day long, because the boss said so... Bastard!}
{111}{}{当然了。每天，我们几乎都无法保持库存充足。。。但这纯粹是利润。有时这真的很痛苦。例如，我讨厌办公室的文书工作。。。但我的老板坚持。我不得不整天带着这本账簿，因为老板说…混蛋！ -- You bet. Every day, we can barely keep our stock full... But it's pure profit. Sometimes it can be a real pain in the ass. For example, I hate office paperwork... But my boss insists. I have to carry this account book with me all day long, because the boss said so... Bastard!}
### {112}{}{Sorry to hear that, I'll be going now.}
{112}{}{很抱歉听到这个消息，我现在就走。 -- Sorry to hear that, I'll be going now.}
### {113}{}{You said you sell slaves here?}
{113}{}{你说你在这里卖奴隶？ -- You said you sell slaves here?}
### {114}{}{Thanks for the story, can I ask you something?}
{114}{}{谢谢你的故事，我能问你点什么吗？ -- Thanks for the story, can I ask you something?}
### {115}{}{I see, I want to ask you something.}
{115}{}{我明白了，我想问你一件事。 -- I see, I want to ask you something.}
### {116}{}{It's you again, what can I do for you?}
{116}{}{又是你，我能为你做什么？ -- It's you again, what can I do for you?}
### {117}{}{Nothing, I was just leaving.}
{117}{}{没什么，我正要离开。 -- Nothing, I was just leaving.}
