### {100}{}{Yes? What do you want?}
{100}{}{对你想要什么？ -- Yes? What do you want?}
### {101}{}{Who are you?}
{101}{}{你是谁？ -- Who are you?}
### {102}{}{What is this place?}
{102}{}{这是什么地方？ -- What is this place?}
### {103}{}{Nothing.}
{103}{}{没有什么 -- Nothing.}
### {104}{}{I'm Roy, the technician. I'm taking care of this old piece of junk. At least it's working, which means I'm doing something right. These machines are very old and each of them has a story of its own, nothing good though.}
{104}{}{我是罗伊，技术员。我在处理这件旧垃圾。至少它在起作用，这意味着我正在做一些正确的事情。这些机器都很旧，每一台都有自己的故事，但没有什么好的。 -- I'm Roy, the technician. I'm taking care of this old piece of junk. At least it's working, which means I'm doing something right. These machines are very old and each of them has a story of its own, nothing good though.}
### {105}{}{What do you mean?}
{105}{}{你是什么意思？ -- What do you mean?}
### {106}{}{So, you work for Pete?}
{106}{}{那么，你为皮特工作？ -- So, you work for Pete?}
### {107}{}{Well, I have to be going now.}
{107}{}{好吧，我现在得走了。 -- Well, I have to be going now.}
### {108}{}{Originally, this place was used as a shelter during the war. There were many underground vaults like this one. We changed most of the interior here... Did I mention this place was in ruins before we came? [Laughs.] I found a lot of data about this place in the computers, ordinary stuff. But...}
{108}{}{最初，这个地方在战争期间被用作避难所。有很多像这样的地下金库。我们改变了这里的大部分内部。。。我有没有提到我们来之前这个地方已经成了废墟？[笑]我在电脑里发现了很多关于这个地方的数据，普通的东西。但是 -- Originally, this place was used as a shelter during the war. There were many underground vaults like this one. We changed most of the interior here... Did I mention this place was in ruins before we came? [Laughs.] I found a lot of data about this place in the computers, ordinary stuff. But...}
### {109}{}{What?}
{109}{}{什么 -- What?}
### {110}{}{Some reports stored in the computer suggest that many of the vault inhabitants were exposed to various toxins. Apparently, they wanted to make some biochemical weapon... Many lives were lost before they figured the mess they'd made in the process. There were other experiments used to increase human endurance, they failed as well... Instead, they created mutated abominations...}
{110}{}{存储在电脑中的一些报告表明，许多金库居民暴露在各种毒素中。显然，他们想制造一些生化武器。。。许多人在意识到自己在这个过程中造成的混乱之前就已经失去了生命。还有其他用来提高人类耐力的实验，它们也失败了。。。相反，他们制造了变异的可憎之物。。。 -- Some reports stored in the computer suggest that many of the vault inhabitants were exposed to various toxins. Apparently, they wanted to make some biochemical weapon... Many lives were lost before they figured the mess they'd made in the process. There were other experiments used to increase human endurance, they failed as well... Instead, they created mutated abominations...}
### {111}{}{So, what happened?}
{111}{}{那么，发生了什么？ -- So, what happened?}
### {112}{}{These mutants were tough and quite stupid, but smart enough to turn against their creators, normal humans. So the war went on for decades... There is not much else about it, I guess we won. [He shrugs.]}
{112}{}{这些变种人很强硬，也很愚蠢，但足够聪明，可以反对他们的创造者，正常人。所以战争持续了几十年。。。没什么别的，我想我们赢了。[他耸耸肩。] -- These mutants were tough and quite stupid, but smart enough to turn against their creators, normal humans. So the war went on for decades... There is not much else about it, I guess we won. [He shrugs.]}
### {113}{}{That's a good story, thanks Roy.}
{113}{}{真是个好故事，谢谢罗伊。 -- That's a good story, thanks Roy.}
### {114}{}{Well, I was hired because of my skills... Never wanted to have anything to do with this type of business. I still have the same opinion, but I stayed because I learned a lot about technical stuff and I feel this is what I always wanted.}
{114}{}{嗯，我被录用是因为我的技能。。。从来都不想与这种类型的业务有任何关系。我仍然有同样的看法，但我留下来是因为我学到了很多关于技术的东西，我觉得这是我一直想要的。 -- Well, I was hired because of my skills... Never wanted to have anything to do with this type of business. I still have the same opinion, but I stayed because I learned a lot about technical stuff and I feel this is what I always wanted.}
### {115}{}{Alright, tell me something else.}
{115}{}{好吧，告诉我其他的事情。 -- Alright, tell me something else.}
### {116}{}{Thanks for your time.}
{116}{}{谢谢你抽出时间。 -- Thanks for your time.}
### {117}{}{What do you want to know?}
{117}{}{你想知道什么？ -- What do you want to know?}
### {118}{}{I don't like what you did!}
{118}{}{我不喜欢你的所作所为！ -- I don't like what you did!}
### {119}{}{Pete is going to be very angry with you!}
{119}{}{皮特会对你很生气的！ -- Pete is going to be very angry with you!}
### {120}{}{Get away from me!}
{120}{}{离我远点！ -- Get away from me!}
### {121}{}{That was very stupid of you!}
{121}{}{你真愚蠢！ -- That was very stupid of you!}
