### {100}{}{I don't want to be here.}
{100}{}{我不想在这里。 -- I don't want to be here.}
### {101}{}{I don't like this place.}
{101}{}{我不喜欢这个地方。 -- I don't like this place.}
### {102}{}{This is a bad place.}
{102}{}{这是个糟糕的地方。 -- This is a bad place.}
### {103}{}{I want out!}
{103}{}{我想退出！ -- I want out!}
### {104}{}{Let me out!}
{104}{}{放我出去！ -- Let me out!}
### {105}{}{Please, help me!}
{105}{}{求你了，帮帮我！ -- Please, help me!}
### {106}{}{Thanks, we'll find the way out.}
{106}{}{谢谢，我们会找到出路的。 -- Thanks, we'll find the way out.}
### {107}{}{Thank you so much.}
{107}{}{非常感谢。 -- Thank you so much.}
### {108}{}{We are free!}
{108}{}{我们自由了！ -- We are free!}
### {109}{}{You set us free, thank you so much.}
{109}{}{你让我们自由了，非常感谢。 -- You set us free, thank you so much.}
