{100}{}{Hi there, what can I get for you?}
{101}{}{I don't know, what do you have for sale?}
{102}{}{Do you have any big weapons, I mean "really" big?}
{103}{}{What's going on here?}
{104}{}{Nothing.}
#you got...
{105}{}{Anything and everything you need, only the best, no bullshit. Here, take a look...}
{106}{}{Thanks.}
#
{107}{}{Anything else?}
{108}{}{I want to take another look at your wares.}
{109}{}{Nothing, thanks.}
#big weapons...
{110}{}{I think I have something for you, it's not the best but it'll do.}
{111}{}{OK, show me what you've got.}
#going on here...
{112}{}{Hey, I don't have time for this. You buy something or don't waste my time.}
{113}{}{Alright, let's trade...}
{114}{}{I guess I don't need anything from you right now.}
#added 17.4.22
{115}{}{What about upgrading gear?}
#power fist upgrade
{116}{}{Well, if you got a Big Frigger, I can wire it up, jam some volts in it, break the safety. May become a
 bit unstable, but if you want a fist that can smash faces into a pulp, it's the thing to do. Let, me think... material, labor,
 electricity, taxes, few drinks... should cost about $2000.}
{117}{}{Alright, here's $2000.}
{118}{}{I don't have that kind of money right now.}
#dude spent all upgrades...
{119}{}{Sorry, dude, I already spend all my materials. Nothing to do, I'm afraid.}
{120}{}{Thanks for your time anyway.}
#no upgrades at the moment...
{121}{}{Sorry, can't see nothing of interest on you. Anything else?}
