### {100}{}{Yeah!}
{100}{}{是 啊 -- Yeah!}
### {101}{}{What?}
{101}{}{什么 -- What?}
### {102}{}{You want something?}
{102}{}{你想要什么？ -- You want something?}
### {103}{}{Go bother somebody else.}
{103}{}{去麻烦别人吧。 -- Go bother somebody else.}
### {104}{}{I don't have time for this.}
{104}{}{我没有时间做这个。 -- I don't have time for this.}
### {105}{}{Just go.}
{105}{}{走吧。 -- Just go.}
### {106}{}{Hey.}
{106}{}{嘿 -- Hey.}
### {107}{}{Who are you?}
{107}{}{你是谁？ -- Who are you?}
### {108}{}{No, I'm not the one.}
{108}{}{不，我不是那个人。 -- No, I'm not the one.}
### {109}{}{Wrong person, pal!}
{109}{}{错人了，伙计！ -- Wrong person, pal!}
### {110}{}{Just keep walking.}
{110}{}{继续走吧。 -- Just keep walking.}
### {111}{}{Leave me alone.}
{111}{}{别管我。 -- Leave me alone.}
