{100}{}{Catch you later.}
{101}{}{This is our place.}
{102}{}{I don't like this place.}
{103}{}{Why do we have to hide here?}
{104}{}{Man, I want out.}
{105}{}{I bet they are looking for us.}
{106}{}{I say, let them wait!}
{107}{}{How long do you think we are going to stay here?}
{108}{}{I can't wait to get out of this hole.}
{109}{}{Hey, are you from the outside!?}
#guards outside...
{110}{}{Hey, watch yourself!}
{111}{}{Seen any bounty hunters?}
{112}{}{We have to keep this location a secret.}
{113}{}{Don't let anyone follow you.}
{114}{}{Pst... Be quiet.}
{115}{}{We can't be seen here.}
{116}{}{Keep your voice down.}
{117}{}{We're safe here, for now...}
{118}{}{I can't talk, I'm on the lookout.}
#wasteland prison destroyed
{119}{}{Yeah, we did it.}
{120}{}{Thanks for your help.}
{121}{}{Thank you stranger!}
{122}{}{We don't need to hide anymore.}
{123}{}{It's about time someone taught those bastards a lesson.}
{124}{}{Good luck in your travels.}
{125}{}{Hey there.}
{126}{}{Nice to see you.}
{127}{}{Catch you later.}
