### {100}{}{Hey, watch it, I'm working here.}
{100}{}{嘿，小心，我在这里工作。 -- Hey, watch it, I'm working here.}
### {101}{}{Do you even work here?}
{101}{}{你在这里工作吗？ -- Do you even work here?}
### {102}{}{Who are you?}
{102}{}{你是谁？ -- Who are you?}
### {103}{}{Where did you come from?}
{103}{}{你从哪里来的？ -- Where did you come from?}
### {104}{}{Talk to my boss Larry if you want a job.}
{104}{}{如果你想找工作，可以和我的老板拉里谈谈。 -- Talk to my boss Larry if you want a job.}
### {105}{}{Nice to see you.}
{105}{}{很高兴见到你。 -- Nice to see you.}
### {106}{}{You are welcome to stay. Ever thought about working here? We really need more workers.}
{106}{}{欢迎你留下来。有没有想过在这里工作？我们真的需要更多的工人。 -- You are welcome to stay. Ever thought about working here? We really need more workers.}
### {107}{}{I think I can trust you. Catch you later.}
{107}{}{我想我可以信任你。待会儿见。 -- I think I can trust you. Catch you later.}
### {108}{}{Anything I can help you with?}
{108}{}{有什么我能帮你的吗？ -- Anything I can help you with?}
### {109}{}{Hey stranger, nice to see you.}
{109}{}{嘿，陌生人，很高兴见到你。 -- Hey stranger, nice to see you.}
### {110}{}{Get away from me.}
{110}{}{离我远点。 -- Get away from me.}
### {111}{}{I don't want to be anywhere near you.}
{111}{}{我不想靠近你。 -- I don't want to be anywhere near you.}
### {112}{}{Yeah, we had some folks like you. They are dead now!}
{112}{}{是的，我们有一些像你一样的人。他们现在死了！ -- Yeah, we had some folks like you. They are dead now!}
### {113}{}{You're gonna pay for what you did.}
{113}{}{你要为你的所作所为付出代价。 -- You're gonna pay for what you did.}
### {114}{}{Watch your back!}
{114}{}{小心背后！ -- Watch your back!}
### {115}{}{You better watch yourself.}
{115}{}{你最好小心点。 -- You better watch yourself.}
