{100}{}{You see: the statue of a running man, still not fast enough to avoid the pigeons. The plaque reads: Founder
 and first mayor of the “golden” valley (2106 to 2132).}
#Description
{101}{}{[You read the plaque. It says:] John Doe (born 2072) left the vault after the great war. He traveled the
 mountains in search of his luck. He was down to his last 10mm bullet & half a stimpak, when in 2106 he found a valley
 of glittering gold. And John Doe decided that this was the place to build his home. The community grew, on the riches
 of golden rock, but it also brought from the waste a pack of villainous rats. Named mayor in 2116, John Doe promised
 to make a stand, and in a night of blazing guns, he drove the bandits to the desert and back to empty land. All was well,
 and all was fine.}
{102}{}{The valley prospered under John Doe, until 2132 when a villain by the name of Richard Roe came into
 town. This man was crooked and unfair, he would trick and lie, he would swindle and swear. John Doe, a man of
 honest character and fair, wouldn't stand for this wretched affair, and when Richard left with stolen goods, John
 Doe swore to never rest, to never sleep until he found and brought to law, this twisted crook, the villain Roe. He took
 his stimpak, he packed his pistol, just as he begun, and left north, always north, following the tracks of the devil
 Roe.}
{103}{}{And thus ends the ballad of John Doe, first mayor of Golden Valley, against Richard Roe. If he ever
 caught him? No one knows, as no one ever heard of the pair again. But to the people of this valley, it shall always be
 remembered to always stay true in the battle against injustice, as did our founder, John Doe. [That's all it says. A long
 story from a long time ago.]}
{104}{}{[Next.]}
{105}{}{[Exit.]}
