### {100}{}{I feel so strange... but was that her gardener or her best friend's second cousin's brother-in-law? My head hurts.}
{100}{}{我觉得很奇怪。。。但那是她的园丁还是她最好朋友的二表哥的妹夫？我的头很疼。 -- I feel so strange... but was that her gardener or her best friend's second cousin's brother-in-law? My head hurts.}
### {101}{}{That was beautiful... but he didn't deserve her.}
{101}{}{太美了。。。但他配不上她。 -- That was beautiful... but he didn't deserve her.}
### {102}{}{<sniff, sniff>}
{102}{}{<sniff，sniff> -- <sniff, sniff>}
### {103}{}{Why do I keep reading this crap?}
{103}{}{为什么我一直读这些垃圾？ -- Why do I keep reading this crap?}
### {200}{}{You feel all warm and fuzzy after finishing the book, but gain nothing useful out of it.}
{200}{}{读完这本书后，你会感到温暖和模糊，但却一无所获。 -- You feel all warm and fuzzy after finishing the book, but gain nothing useful out of it.}
