### {100}{}{Please don't hurt me!}
{100}{}{请不要伤害我！ -- Please don't hurt me!}
### {101}{}{Are you my new master?}
{101}{}{你是我的新主人吗？ -- Are you my new master?}
### {102}{}{Please set me free.}
{102}{}{请放我自由。 -- Please set me free.}
### {103}{}{I really want to be free.}
{103}{}{我真的很想自由。 -- I really want to be free.}
### {104}{}{Run away!!}
{104}{}{逃跑 -- Run away!!}
### {105}{}{Oh, God, please, why?}
{105}{}{天啊，求你了，为什么？ -- Oh, God, please, why?}
### {106}{}{Why do you hate us?}
{106}{}{你为什么恨我们？ -- Why do you hate us?}
### {107}{}{Thank you, friend.}
{107}{}{谢谢你，朋友。 -- Thank you, friend.}
### {108}{}{Where do we go now?}
{108}{}{我们现在要去哪里？ -- Where do we go now?}
### {109}{}{I hope we gonna make it. We're in the middle of nowhere.}
{109}{}{我希望我们能成功。我们在一个荒无人烟的地方。 -- I hope we gonna make it. We're in the middle of nowhere.}
### {110}{}{You saved us from a bad fate, we'll find our way home.}
{110}{}{你把我们从厄运中救了出来，我们会找到回家的路。 -- You saved us from a bad fate, we'll find our way home.}
### {111}{}{They look tired and scared.}
{111}{}{他们看起来又累又害怕。 -- They look tired and scared.}
