### {100}{}{You see: a salesman.}
{100}{}{你看：一个推销员。 -- You see: a salesman.}
### {101}{}{It's } #needs a space at the end{102}{}{A slick traveling salesman.}
{101}{}{It's } #needs a space at the end{102}{}{一个精明的旅行推销员。 -- A slick traveling salesman.}
### {103}{}{ and have I got a deal for you. [He seems to be reading from a card, and after a while you doze off.]} #needs a space at the start, first part in 201{104}{}{Zzzzzzz...}
{103}{}{ and have I got a deal for you. [He seems to be reading from a card, and after a while you doze off.]} #needs a space at the start, first part in 201{104}{}{Zzzzzzz。。。 -- Zzzzzzz...}
### {105}{}{[You groggily open your eyes as you finally notice that someone is kicking you.] Well, are you interested or not?}
{105}{}{[当你终于注意到有人在踢你时，你摇摇晃晃地睁开眼睛。]好吧，你感兴趣还是不感兴趣？ -- [You groggily open your eyes as you finally notice that someone is kicking you.] Well, are you interested or not?}
### {106}{}{Interested in what?}
{106}{}{对什么感兴趣？ -- Interested in what?}
### {107}{}{Erg?}
{107}{}{呃？ -- Erg?}
### {108}{}{Why, it slices it dices and it'll also come in handy against pesky critters. A bargain at any price, but for you it's on special for only }
{108}{}{为什么，它会把它切成丁，它也会在对付讨厌的动物时派上用场。任何价格都很便宜，但对你来说，这是特价商品 -- Why, it slices it dices and it'll also come in handy against pesky critters. A bargain at any price, but for you it's on special for only }
### {109}{}{Why it's made of only the finest wood around. Use it to jab at critters to keep them at bay or, if you're skilled enough, throw it. It's very aerodynamic and won't break on impact. What do you say? It's a steal at only }
{109}{}{为什么它只由周围最好的木材制成。用它戳动物以阻止它们，或者，如果你足够熟练的话，扔它。它非常符合空气动力学，不会在撞击时断裂。你怎么说？这只是一次偷窃 -- Why it's made of only the finest wood around. Use it to jab at critters to keep them at bay or, if you're skilled enough, throw it. It's very aerodynamic and won't break on impact. What do you say? It's a steal at only }
### {110}{}{This weapon is made of the finest recycled steel. Just feel how that fits comfortably into your hand. And don't worry, our engineers have tested it for safety and reliability. No robber in his right mind would dare try to steal from if you wave this baby around. And it'll only set you back }
{110}{}{这种武器是用最好的再生钢制成的。只要感觉一下它是如何舒适地放在你的手上。别担心，我们的工程师已经测试了它的安全性和可靠性。如果你把这个孩子晃来晃去，没有一个头脑正常的强盗敢偷。这只会让你倒退 -- This weapon is made of the finest recycled steel. Just feel how that fits comfortably into your hand. And don't worry, our engineers have tested it for safety and reliability. No robber in his right mind would dare try to steal from if you wave this baby around. And it'll only set you back }
### {111}{}{This little gem is truly one of a kind. From the far reaches of... It works by pointing it like- Look, I don't know what the hell this is. You want it or not? The price is }
{111}{}{这颗小宝石真是独一无二。从遥远的。。。它的工作原理是像-看，我不知道这到底是什么。你想要还是不想要？价格是 -- This little gem is truly one of a kind. From the far reaches of... It works by pointing it like- Look, I don't know what the hell this is. You want it or not? The price is }
### {112}{}{This little dandy just screams. Don't mess with me! The mere sight of it will send your enemies running. A bargain at }
{112}{}{这个小花花公子只是尖叫。别惹我！只要看到它就会让你的敌人逃跑。在 -- This little dandy just screams. Don't mess with me! The mere sight of it will send your enemies running. A bargain at }
### {113}{}{I can tell you're the type of person that likes to get close up and personal when dealing with riff raff. Well this little doohickey is just what you need, and it'll only cost you }
{113}{}{我可以告诉你，在与流氓打交道时，你是那种喜欢近距离接触的人。这个小家伙正是你所需要的，而且只会花你的钱 -- I can tell you're the type of person that likes to get close up and personal when dealing with riff raff. Well this little doohickey is just what you need, and it'll only cost you }
### {114}{}{I'll take it.}
{114}{}{我要它。 -- I'll take it.}
### {115}{}{I'll pass.}
{115}{}{我会通过的。 -- I'll pass.}
### {116}{}{Yes indeedy, you won't regret this. It was nice giving you the business. See you around.}
{116}{}{是的，你不会后悔的。很高兴能给你这笔生意。回头见。 -- Yes indeedy, you won't regret this. It was nice giving you the business. See you around.}
### {117}{}{[End.]}
{117}{}{[终止 -- End.]}
### {118}{}{Shit! What a waste of my time. Go on, beat it!}
{118}{}{妈的！真是浪费我的时间。继续，打败它！ -- Shit! What a waste of my time. Go on, beat it!}
### {119}{}{[End.]}
{119}{}{[终止 -- End.]}
### {120}{}{Well, that was a wasted speech. $} #continue on 152{121}{}{Yup.}
{120}{}{Well, that was a wasted speech. $} #continue on 152{121}{}{是的。 -- Yup.}
### {122}{}{Nope.}
{122}{}{没有。 -- Nope.}
### {123}{}{Hey, it's you again. I got some new stuff - you interested?}
{123}{}{嘿，又是你。我有一些新东西，你感兴趣吗？ -- Hey, it's you again. I got some new stuff - you interested?}
### {124}{}{Sure, let's hear what you got.}
{124}{}{当然，让我们听听你有什么收获。 -- Sure, let's hear what you got.}
### {125}{}{Not a chance, } #needs a space at the end{126}{}{Yup.}
{125}{}{Not a chance, } #needs a space at the end{126}{}{是的。 -- Yup.}
### {127}{}{Nope.}
{127}{}{没有。 -- Nope.}
### {128}{}{Beat it! I'm busy.}
{128}{}{打败它！我很忙。 -- Beat it! I'm busy.}
### {129}{}{Come back when you got some money.}
{129}{}{等你有钱了再来。 -- Come back when you got some money.}
### {130}{}{GO AWAY!}
{130}{}{走开！ -- GO AWAY!}
### {131}{}{No refunds.}
{131}{}{不退款。 -- No refunds.}
### {132}{}{No exchanges.}
{132}{}{没有交换。 -- No exchanges.}
### {133}{}{No credit.}
{133}{}{没有信用。 -- No credit.}
### {134}{}{Go away, I'm busy.}
{134}{}{走开，我很忙。 -- Go away, I'm busy.}
### {135}{}{Not a smart move.}
{135}{}{这不是明智之举。 -- Not a smart move.}
### {136}{}{Bastard!}
{136}{}{混蛋！ -- Bastard!}
### {137}{}{Is this supposed to get me to lower my prices?}
{137}{}{这是为了让我降低价格吗？ -- Is this supposed to get me to lower my prices?}
### {138}{}{All right, I'll lower the prices.}
{138}{}{好吧，我会降低价格。 -- All right, I'll lower the prices.}
### {139}{}{How about a 20% discount?}
{139}{}{打八折怎么样？ -- How about a 20% discount?}
### {140}{}{How about a 40% discount?}
{140}{}{打40%的折扣怎么样？ -- How about a 40% discount?}
### {141}{}{How about an 80% discount?}
{141}{}{打八折怎么样？ -- How about an 80% discount?}
### {142}{}{Okay, FREE; here, take it!}
{142}{}{好吧，免费；给，拿着！ -- Okay, FREE; here, take it!}
### {143}{}{Willy}
{143}{}{Willy -- Willy}
### {144}{}{George}
{144}{}{乔治 -- George}
### {145}{}{Mike}
{145}{}{Mike -- Mike}
### {146}{}{Walter}
{146}{}{Walter -- Walter}
### {147}{}{Charlie}
{147}{}{查理 -- Charlie}
### {148}{}{Freddy}
{148}{}{弗雷迪 -- Freddy}
### {149}{}{Mick}
{149}{}{米克 -- Mick}
### {150}{}{Smitty}
{150}{}{Smitty -- Smitty}
### {151}{}{Jack}
{151}{}{Jack -- Jack}
### {152}{}{. You want it or not?}
{152}{}{。你想要还是不想要？ -- . You want it or not?}
### {200}{}{.}
{200}{}{. -- .}
