{100}{}{Hello there, stranger. I'm sheriff McKarty. As you can see, this little town is working hard to become again what it was before the war. Well, we managed to hold off raiders and other gangs, but time is against us. Since my deputy Mike died everything is in withdrawal. We have troubles with local gangs and not enough men to hold them for much longer... I'm asking if you want to join us. Well, what do you say?}

{101}{}{Well, I wouldn't mind helping you out. But... how dangerous can this get?}

{102}{}{I really don't know. It depends on the situation we'll end up finding ourselves in. Mostly dangerous, I'd say, with some unpredictable outcomes. Of course, we'll always hand out some money to cover the expenses of whoever is helping us.}
{103}{}{OK, count me in. I can always use some extra money.}
