{100}{}{Hey, I'm Mike. Who are you?}
{101}{}{My name is not important, I'm just looking for some information.}
#
{102}{}{Right... Say, I saw you talking to that tree over there. Are you funny in the head or just a bit peculiar?}
{103}{}{Say, do you have any jobs around here?}
#
{104}{}{Jobs, jobs... I'm not sure. You might try... hmm... [Rubbing his thumb against index and middle finger.]}
{105}{}{[Give him $50.]}
{106}{}{[Give him $100.]}
{107}{}{[Give him $150.]}
# 50 chips
{108}{}{OK, let me see... [Scratching his head.] I've heard that the sheriff wants someone for a job. The sheriff is...
 Just go north and after the last house, take a right.}
{112}{}{Bye.}
# 100 chips
{113}{}{Right. [Big smile.] Here's what's going on: There's a cave down below, actually it's an unused mine. Murphy
 is looking for someone to clean it out. He wants to reopen it. The only problem is that the mine is full of rats,
 so if you're interested, I suggest you talk to him. His house is next to the sheriff's.}
{116}{}{Thanks.}
# 150 chips
{117}{}{Thanks. That's very generous of you. We got this holy man, he's at the church. [Points north with his hand.]
 He makes potions, but needs some plants. That's all from me. [Turns away.]}
{118}{}{No problemo.}
#dude talking to Mike again
{119}{}{Hey man. How's it going? What can I do for you?}
{120}{}{Any jobs around here, anything useful?}
#no more jobs
{121}{}{Sorry, I already told you everything I know.}
{122}{}{Right, nevermind then.}
#dude has no money
{123}{}{You want favors, but don't have any money. That's not gonna fly. Come back when you have some.}
{124}{}{What about doing me a favor?}
#dude stealing from Mike
{125}{}{Ehehe... Fine day to spend some bullets!}
#dude looking at Mike
{126}{}{You see: a local citizen.}
{127}{}{He's whistling. Like it's a nice day after a downpour of acid rain.}
#
{128}{}{Hey, you're the guy who's running around killing people! Fuck off before I blow your brains out!}
{129}{}{Alright.}
{130}{}{I don't think you fully grasp who I am. Let me show you.}
#talking to a tree...
{131}{}{What are you talking about?}
{132}{}{What tree, where?}
{133}{}{I was just um... thinking out loud...}
{134}{}{Maybe you are the one who's crazy. Stay away from me, weirdo!}
#131,132,133... dude has cloak
{135}{}{Don't try your tricks on me, I know your kind. I can smell trouble, and your stench is unbearable. There's
 only one place you could have come from. And it's that prison up north. I don't like you guys strolling around, taking
 away people... Hell, you may even take me away... I want nothing to do with you. Go away, I'm not gonna talk to you.}
{136}{}{Damn it.}
{137}{}{You'll sing like an angel. After the beating I'm gonna give you!}
#131,132,133... dude is wearing something else
{138}{}{Nevermind. I can see the prison mark on your wrist. Just one more burden to carry... You are welcome here,
 as long as you don't cause any trouble. People have become watchful of strangers recently, and although the sheriff
 may be fair, he won't take any risks either, one bad word from anyone, and you'll be right back to where you came
 from, got it?}
{139}{}{Right... You said "recently", were there others like me?}
{140}{}{What can you tell me about this place?}
{141}{}{Sure. Nice talking to you.}
#others....
{142}{}{Yeah, there were some folks asking around about a safe place to hide. I said I can't help them and they were
 gone not long after. Can't remember seeing them again. Then there was some guy looking for them but he
 was one of the prison guards. He was pushy, even threatened me... But I know them type and called the sheriff
 immediately...}
{143}{}{What happened then?}
{144}{}{So, did you whack him or what?}
#
{145}{}{The next thing I know... He was running away and suddenly vanished in front of my eyes. It happened so fast
 that I couldn't explain it to the sheriff and he certainly thought I was losing my mind. Damn, I'm not sure either
 anymore... A lot of weird stuff is going on here, you just stick around and you'll see what I'm talking about.}
{146}{}{I might do that, see you later.}
#this place...
{147}{}{This is a small community, mostly mine workers. You'll see a lot of locals selling something to survive. That's
 the way it goes these days. Above all, we have bandits gathering around town, like there is anything left to steal...
 Maybe some dirt! [He laughs.] If that isn't enough, patrols from the nearby prison pass through town at night,
 taking away our people.}
{148}{}{What about those bandits?}
{149}{}{What can you tell me about those night patrols?}
{150}{}{Is there anything worth staying for?}
{151}{}{I'll see you later, thanks Mike.}
#bandits...
{152}{}{Always the same, they come here to plunder and take away everything they can. So we started fighting back
 with everything we have. And of course, we are holding so far, mostly thanks to our sheriff. He put a lot of effort into
 organizing the town's defenses. But without any additional weaponry, it's hopeless.}
{153}{}{What are you going to do?}
{154}{}{What about those patrols?}
{155}{}{If it's hopeless, why do you stay here?}
{156}{}{I see, thanks for your time.}
#going to do... no walls...
{157}{}{Well, the sheriff decided that the best way to protect our town is to build a wall. Although, many
 complained that it's a waste of money and they would rather have more guns in town, the sheriff emphasized that more
 guns means more trouble for the community and convinced people to hold off.}
{158}{}{I guess you're doing the right thing, see you later.}
#going to do... walls built...
{159}{}{Well, since we built these walls, it's going better already, I think. But we put ourselves in greater isolation
 which means we have to find other ways than trading to produce food and goods. I just hope we won't run out of
 supplies or there will be some serious issues. At least we have less trouble with the bandits, that's got to be something.}
{160}{}{Better for sure...}
#patrols...
{161}{}{The worst kind I know of. From the very beginning they gave us promises and we got nothing but empty
 words and lies. But the town is still divided whether we should accept the technology they have to offer or stay
 defenseless against the raiders. Some of the locals think it's far better to join these "peace keepers" than watch our
 people suffer every day...}
{162}{}{Have you decided anything?}
{163}{}{And what's the price for joining them?}
{164}{}{I've had enough of this, see you later.}
#decided...
{165}{}{Well, sort of... But I'm glad the majority is strongly against any patrol presence in town. We don't need
 them and the only mistake we made was letting them poison our minds with the words we wanted to hear back then.
 Now, I know it's wrong and I'm helping others to realize that.}
{166}{}{I hope you are doing the right thing.}
#price...
{167}{}{It's... too much even to consider as an alternative. They needed new recruits, we might be simple folks but we
 are smart enough to see they were only interested in taking our people to work in their labor camps.}
{168}{}{Labor camps? Can you tell me more?}
{169}{}{Well, thanks for your time.}
#
{170}{}{Look, I can't tell you more because I don't know more... You better talk to the sheriff about it.}
{171}{}{I will, thanks.}
#hopeless... why stay?
{172}{}{Because there's nothing for me out there. Everything I ever needed is right here... And I have never asked for
 more. It makes me feel bitter when someone tries to take away our peace... Even our lives at some point. So I try to
 smile every time and think of the day when this will be over. That day will come, I can assure you that.}
{173}{}{I don't think it will be anytime soon, what are you going to do until then?}
{174}{}{I sure hope so.}
#anything worth staying...
{175}{}{Everything you see here is worth something to me. But it's the people we are fighting for, not rocks or trees!}
{176}{}{I get the point. There's nothing more I need to know.}
#floating messages after talking to Mike with cloak on...
{177}{}{I'm not gonna talk to you.}
{178}{}{Stay away from me.}
{179}{}{Man, you scare me!}
{180}{}{I don't know what you want, but I'm not telling you anything.}
{181}{}{Do you have a hearing problem? I told you to stay away from me.}
#
{182}{}{I'll come back when I have some money.}
#
{183}{}{Hey there, stranger.}
{184}{}{I'm watching you.}
{185}{}{There's nothing of interest here.}
{186}{}{Do you want something?}
#
{187}{}{Go away.}
{188}{}{Yeah, whatever...}
{189}{}{I'm not listening.}
{190}{}{Just leave me be.}
{191}{}{What? I can't hear you.}
#
{192}{}{::he follows you with his eyes::}
#generic
{193}{}{[Speech chance: }
{194}{}{You have failed to use your steal skill.}
{195}{}{[Chance: }
