### {100}{}{Hey there, friend... I *hic* ain't never seen you before, are you new here? [He smiles like you are his old fella.]}
{100}{}{嘿，朋友。。。我从没见过你，你是新来的吗？[他笑起来就像你是他的老朋友。] -- Hey there, friend... I *hic* ain't never seen you before, are you new here? [He smiles like you are his old fella.]}
### {101}{}{Yes... um... I arrived recently. So tell me about this place. What do you do here?}
{101}{}{对嗯…我最近到的。告诉我这个地方吧。你在这里做什么？ -- Yes... um... I arrived recently. So tell me about this place. What do you do here?}
### {102}{}{Hey hmm... [Scratches his head.] Don't really knowsh what... We have celebrationsh... [It shows he's a little bit drunk.] You know, we recently had a good catch. There were some hotshpurs at the Old Hotel. They were full of money and jewels... Man, that was my lucky day. One of them told ush that there is some hidden gold near the... near the hotel. What a fool... *hic*. He thought he was gonna make his life with the gold... [Hard laughter.] But there was no gold and no... no mercy for him... Hehe...}
{102}{}{嘿，嗯…[挠他的头。]真的不知道。。。我们有庆祝活动。。。[这表明他有点醉了。]你知道，我们最近玩得很开心。老旅馆里有些喧闹。他们装满了钱和珠宝。。。伙计，那是我的幸运日。其中一人告诉我们在。。。酒店附近。真傻*hic*。他以为他会用金子谋生。。。但没有金子，也没有……对他没有怜悯。。。呵呵。。。 -- Hey hmm... [Scratches his head.] Don't really knowsh what... We have celebrationsh... [It shows he's a little bit drunk.] You know, we recently had a good catch. There were some hotshpurs at the Old Hotel. They were full of money and jewels... Man, that was my lucky day. One of them told ush that there is some hidden gold near the... near the hotel. What a fool... *hic*. He thought he was gonna make his life with the gold... [Hard laughter.] But there was no gold and no... no mercy for him... Hehe...}
### {103}{}{Gold you say... Where did he say it was located?}
{103}{}{你说的金子。。。他说它在哪里？ -- Gold you say... Where did he say it was located?}
### {104}{}{How should I *hic* know, but if there ish gold, nobody... nobody took it yet. Boss was very clear about that, he said... Blah, blah, blah... I'm a fat motherfucker... Bring the gold to me and you'll get your cut... Blah, blah, blah! Anyway, if I knew where the gold is... I would be sooo far away from here by now. Why are you interested... Do you know shomething?}
{104}{}{我怎么会知道，但如果有金子，没有人。。。还没人拿。老板很清楚，他说。。。废话，废话，废话。。。我是个胖混蛋。。。把金子带给我，你会得到你的切割。。。废话，废话，废话！不管怎样，如果我知道金子在哪里…我现在离这里太远了。你为什么感兴趣。。。你知道shomething吗？ -- How should I *hic* know, but if there ish gold, nobody... nobody took it yet. Boss was very clear about that, he said... Blah, blah, blah... I'm a fat motherfucker... Bring the gold to me and you'll get your cut... Blah, blah, blah! Anyway, if I knew where the gold is... I would be sooo far away from here by now. Why are you interested... Do you know shomething?}
### {105}{}{No, I'm only asking... Maybe I can help you find it.}
{105}{}{不，我只是问。。。也许我可以帮你找到它。 -- No, I'm only asking... Maybe I can help you find it.}
### {106}{}{Tell you what, I got some *hic* work to do now... Come back anotha time and we'll talk, and of courshe... bring shome beer to the party! [He grins stupidly. Then falls asleep on the table.]}
{106}{}{告诉你吧，我现在有一些工作要做。。。下次再来，我们会谈谈，当然。。。带啤酒来参加聚会！[他傻傻地笑了笑。然后在桌子上睡着了。] -- Tell you what, I got some *hic* work to do now... Come back anotha time and we'll talk, and of courshe... bring shome beer to the party! [He grins stupidly. Then falls asleep on the table.]}
### {107}{}{You got it. Goodbye.}
{107}{}{你明白了，再见。 -- You got it. Goodbye.}
### {108}{}{I'm busy.}
{108}{}{我很忙。 -- I'm busy.}
### {109}{}{Catch you later.}
{109}{}{待会儿见。 -- Catch you later.}
### {110}{}{No time to talk right now.}
{110}{}{现在没有时间说话。 -- No time to talk right now.}
### {111}{}{Hey there, buddy.}
{111}{}{嘿，伙计。 -- Hey there, buddy.}
### {112}{}{Hey, you're back and you have something to drink. Wanna share that drink with me? [He looks eagerly at your beer.]}
{112}{}{嘿，你回来了，有点喝的。想和我一起喝那杯吗？[他急切地看着你的啤酒。] -- Hey, you're back and you have something to drink. Wanna share that drink with me? [He looks eagerly at your beer.]}
### {113}{}{Sure thing. Here you go.}
{113}{}{当然可以给你。 -- Sure thing. Here you go.}
### {114}{}{No way man, this beer is mine.}
{114}{}{没门，伙计，这啤酒是我的。 -- No way man, this beer is mine.}
### {115}{}{Thanks, ah... This is a good one. [Drinks the beer.]}
{115}{}{谢谢，啊。。。这是一个好的。[喝啤酒。] -- Thanks, ah... This is a good one. [Drinks the beer.]}
### {116}{}{Wanna tell me that story about the hidden gold?}
{116}{}{想告诉我关于隐藏黄金的故事吗？ -- Wanna tell me that story about the hidden gold?}
### {117}{}{Enjoy that one, see ya later.}
{117}{}{好好享受，回头见。 -- Enjoy that one, see ya later.}
### {118}{}{What gold? Oh, right, let me see... During our last action at the Old Hotel some blathering idiot told me this story. He said that his folks, when the war started, hid some gold in the well near the hotel... And people come, people go, but nobody ever checked the well! [He smiles.]}
{118}{}{什么金子？哦，好吧，让我看看。。。在我们最后一次在老酒店的活动中，一个胡言乱语的白痴告诉了我这个故事。他说，战争开始时，他的家人在酒店附近的井中藏了一些黄金。。。人们来了，人们走了，但从来没有人检查过井！[他笑了。] -- What gold? Oh, right, let me see... During our last action at the Old Hotel some blathering idiot told me this story. He said that his folks, when the war started, hid some gold in the well near the hotel... And people come, people go, but nobody ever checked the well! [He smiles.]}
### {119}{}{So why didn't you?}
{119}{}{那你为什么不呢？ -- So why didn't you?}
### {120}{}{Are you kidding? Who's crazy enough to go down there? You may get trapped! Anyway, I don't believe there's any pre-war gold. Just a crazy, old man's tale, if you ask me.}
{120}{}{你在开玩笑吗？谁疯到可以下去？你可能会被困住！无论如何，我不相信有任何战前的黄金。如果你问我的话，这只是一个疯狂的老人故事。 -- Are you kidding? Who's crazy enough to go down there? You may get trapped! Anyway, I don't believe there's any pre-war gold. Just a crazy, old man's tale, if you ask me.}
### {121}{}{Thanks anyway.}
{121}{}{无论如何，谢谢。 -- Thanks anyway.}
### {122}{}{I'm parched.}
{122}{}{我很渴。 -- I'm parched.}
### {123}{}{*chrr* *zzz* *chrrr*}
{123}{}{*chrr**zzz**chrrr* -- *chrr* *zzz* *chrrr*}
