{100}{}{You see: the local bar keeper, Anna.}
{101}{}{A young dolly, if you've ever seen one.}
#
{102}{}{Welcome to Anna's Bar... That's me! [She smiles.] What can I do for you today. Some drinks? Here's what we
 have... [Hands you a menu.]}
{103}{}{(Beer..............$5)}
{104}{}{(Nuka cola.........$4)}
{105}{}{(Booze.............$5)}
{106}{}{(Gamma gulp beer...$15)}
{107}{}{(Roentgen rum......$15)}
{108}{}{(Water.............$20)}
{109}{}{Good bye.}
#
{110}{}{Take your time.}
#
{111}{}{Nice to see you again, what's it gonna be?}
#
{112}{}{Gimme another round.}
#
{113}{}{Come back anytime.}
#
{114}{}{Sorry, you don't have enough money.}
#
{115}{}{I'll be back when I have some more.}
#
{116}{}{Some info?}
#
{117}{}{Sure, what do you want to know?}
{118}{}{Anything interesting going on here?}
{119}{}{Actually nothing, let me take a look at the menu.}
#anything interesting...
{120}{}{Not much. Here at my bar things are going as usual. People come, spend some money and that's that. [Smiles.]
 Can't complain. Do you travel often? 'Cause you look like the adventurous type.}
{121}{}{Yep, I'm traveling a lot these days.}
{122}{}{Not much, just to get some supplies.}
#yep...
{123}{}{I got one customer who is very different from the others. Sometimes, actually, very often, he sits alone at the
 bar and tells me some of his stories from the past. His latest story was about some old ruined city he found. Believe me,
 you have never heard stories like that before.}
{124}{}{I might want to hear one of them. When does he usually come?}
{125}{}{Thanks, but no thanks.}
#
{126}{}{Every night. And he usually sits at a table there in the corner. [She points to her right.] If you come here more
 often, you might get a story or maybe a free drink, if you get lucky.}
{127}{}{Thanks, I'll keep that in mind.}
#after 122
{128}{}{OK, nevermind, I don't want to bother you with stories. Is there something else you wanted?}
{129}{}{I was thinking about getting something to drink...}
{130}{}{Nothing else, bye.}
#
{131}{}{Anything else?}
#
{132}{}{Who's the guy at the bar?}
#
{133}{}{He's a regular here. People say he stays up in the forest most of the time, because he's a gecko hunter. But I
 think he's OK when you get to know him. Something else you want to know?}
{134}{}{Anything interesting going on here?}
{135}{}{Actually nothing, let me take a look at the menu.}
#
{136}{}{You feel refreshed after drinking some fine water.}
