### {100}{}{You're not supposed to be here.}
{100}{}{你不应该在这里。 -- You're not supposed to be here.}
### {101}{}{We Bulls don't take orders from anyone.}
{101}{}{我们公牛队不接受任何人的命令。 -- We Bulls don't take orders from anyone.}
### {102}{}{No, I don't talk with strangers.}
{102}{}{不，我不和陌生人说话。 -- No, I don't talk with strangers.}
### {103}{}{I don't like your kind.}
{103}{}{我不喜欢你这种人。 -- I don't like your kind.}
### {104}{}{I'm working, can't you see!?}
{104}{}{我在工作，你没看见吗！？ -- I'm working, can't you see!?}
