### {100}{}{You see: a holy man.}
{100}{}{你看：一个圣人。 -- You see: a holy man.}
### {101}{}{An old looking man, you think, but his long vestment prevents you from fully seeing his face.}
{101}{}{你想，一个看起来很老的男人，但他的长法衣让你无法完全看到他的脸。 -- An old looking man, you think, but his long vestment prevents you from fully seeing his face.}
### {102}{}{Yes, my child, who are you?}
{102}{}{是的，我的孩子，你是谁？ -- Yes, my child, who are you?}
### {103}{}{I'm new here. Say, what's going on here.} #script will add I'm dude name. to the start of this#odgovor priest-a{104}{}{Nothing is going on here! [Raises his hand.] As you can see I'm a local priest but I also make medicine, if somebody needs a cure for something I make it with my recipes. So my child, tell me, what is the purpose of your visit?}
{103}{}{I'm new here. Say, what's going on here.} #script will add I'm dude name. to the start of this#odgovor priest-a{104}{}{这里什么都没发生！[举起他的手。]正如你所看到的，我是当地的一名牧师，但我也会行医，如果有人需要治愈某种疾病，我会用我的食谱来做。那么，我的孩子，告诉我，你此行的目的是什么？ -- Nothing is going on here! [Raises his hand.] As you can see I'm a local priest but I also make medicine, if somebody needs a cure for something I make it with my recipes. So my child, tell me, what is the purpose of your visit?}
### {106}{}{Just came to say hello. I'll be going now.}
{106}{}{只是来打招呼的。我现在就去。 -- Just came to say hello. I'll be going now.}
### {107}{}{Mike told me that you need some ingredients for your potions.}
{107}{}{迈克告诉我你的药水需要一些原料。 -- Mike told me that you need some ingredients for your potions.}
### {108}{}{Well, if Mike told you... Yes, I do need someone to find me 3 broc flowers. There are plenty of them in the wild, but I'm sure you can find some in the garden. Now go my child.}
{108}{}{好吧，如果迈克告诉你。。。是的，我确实需要有人给我找3朵布罗克花。野外有很多，但我相信你可以在花园里找到一些。现在去吧，我的孩子。 -- Well, if Mike told you... Yes, I do need someone to find me 3 broc flowers. There are plenty of them in the wild, but I'm sure you can find some in the garden. Now go my child.}
### {109}{}{Alright.}
{109}{}{好吧 -- Alright.}
### {110}{}{So my child, you have returned. Have you found those broc flowers I need?}
{110}{}{所以我的孩子，你回来了。你找到我需要的那些碎花了吗？ -- So my child, you have returned. Have you found those broc flowers I need?}
### {111}{}{Yes, here they are.}
{111}{}{是的，它们在这儿。 -- Yes, here they are.}
### {112}{}{No, I don't have them.}
{112}{}{不，我没有。 -- No, I don't have them.}
### {113}{}{Thank you my child. This will help a lot. I can give you this healing powder as my thanks.}
{113}{}{谢谢你，我的孩子。这将大有帮助。我可以给你这种治疗粉末作为我的感谢。 -- Thank you my child. This will help a lot. I can give you this healing powder as my thanks.}
### {114}{}{Thanks, holy one.}
{114}{}{谢谢，天哪。 -- Thanks, holy one.}
### {115}{}{No, my child, you don't have them. Come back when you do.}
{115}{}{不，我的孩子，你没有。等你回来的时候再来。 -- No, my child, you don't have them. Come back when you do.}
### {116}{}{Of course.}
{116}{}{当然 -- Of course.}
### {117}{}{Yes, my child?}
{117}{}{是的，我的孩子？ -- Yes, my child?}
### {118}{}{You have done a great job, my child. Go in peace.}
{118}{}{你做得很好，我的孩子。平静地去吧。 -- You have done a great job, my child. Go in peace.}
### {119}{}{Take care, holy one.}
{119}{}{保重，圣子。 -- Take care, holy one.}
### {120}{}{Evil are your thoughts. If you're looking for salvation or forgiveness, then you are in the wrong place.}
{120}{}{邪恶是你的思想。如果你在寻求救赎或宽恕，那么你就错在了错误的地方。 -- Evil are your thoughts. If you're looking for salvation or forgiveness, then you are in the wrong place.}
### {121}{}{I sure am. And I'm out of here.}
{121}{}{我当然是。我要离开这里。 -- I sure am. And I'm out of here.}
### {122}{}{Let me show you what evil thoughts I'm having right now.}
{122}{}{让我告诉你我现在有什么邪恶的想法。 -- Let me show you what evil thoughts I'm having right now.}
### {123}{}{Can I ask you something, Father?}
{123}{}{我能问你点什么吗，神父？ -- Can I ask you something, Father?}
### {124}{}{Of course, my child. What wisdom do you seek?}
{124}{}{当然，我的孩子。你寻求什么智慧？ -- Of course, my child. What wisdom do you seek?}
### {125}{}{Did you see some strange people in robes coming here at night?}
{125}{}{你有没有看到一些穿着长袍的陌生人晚上来这里？ -- Did you see some strange people in robes coming here at night?}
### {126}{}{Just passing by, sorry for the disturbance.}
{126}{}{只是路过，很抱歉打扰你。 -- Just passing by, sorry for the disturbance.}
### {127}{}{I couldn't say my child. Your Father is not present here at night time, rather he is resting for tomorrow's service.}
{127}{}{我不能说我的孩子。你的父亲晚上不在这里，而是在为明天的仪式休息。 -- I couldn't say my child. Your Father is not present here at night time, rather he is resting for tomorrow's service.}
### {128}{}{So, people can enter this church whenever they want?}
{128}{}{所以，人们可以随时进入这个教堂？ -- So, people can enter this church whenever they want?}
### {129}{}{Of course, my child. This is the house of God and as the people are his children, it is only natural that they come here asking forgiveness from their Father.}
{129}{}{当然，我的孩子。这是上帝的家，因为人们是他的孩子，所以他们来到这里请求父亲的宽恕是很自然的。 -- Of course, my child. This is the house of God and as the people are his children, it is only natural that they come here asking forgiveness from their Father.}
### {130}{}{Yes but what if somebody...? Uh, nevermind. See you later, Father.}
{130}{}{是的，但如果有人…怎么办。。。？没关系。回头见，神父。 -- Yes but what if somebody...? Uh, nevermind. See you later, Father.}
### {131}{}{I have nothing more to say to you my child. Go in peace.}
{131}{}{我没有什么要对你说的了，我的孩子。平静地去吧。 -- I have nothing more to say to you my child. Go in peace.}
### {132}{}{Goodbye.}
{132}{}{再见 -- Goodbye.}
### {133}{}{Have you seen any strangers lately?}
{133}{}{你最近见过陌生人吗？ -- Have you seen any strangers lately?}
### {134}{}{I'm sorry but my memory does not serve me well. I can barely remember what I ate yesterday...}
{134}{}{对不起，我记性不好。我几乎记不清昨天吃了什么。。。 -- I'm sorry but my memory does not serve me well. I can barely remember what I ate yesterday...}
### {135}{}{Where do you keep those recipes of yours?}
{135}{}{你的食谱放在哪里？ -- Where do you keep those recipes of yours?}
### {136}{}{You wouldn't lie to me, am I right?}
{136}{}{你不会骗我吧？ -- You wouldn't lie to me, am I right?}
### {137}{}{Alright. I'll be going then.}
{137}{}{好吧那我就去。 -- Alright. I'll be going then.}
### {138}{}{In what people used to call books, but I'm sure a primitive such as yourself doesn't know what I'm talking about.}
{138}{}{人们过去称之为书，但我相信像你这样的原始人不知道我在说什么。 -- In what people used to call books, but I'm sure a primitive such as yourself doesn't know what I'm talking about.}
### {139}{}{No, I don't have a clue what you're talking about.}
{139}{}{不，我不知道你在说什么。 -- No, I don't have a clue what you're talking about.}
### {140}{}{Ah, those... Sorry, it was a misunderstanding. I'm going now.}
{140}{}{啊，那些。。。对不起，这是一个误会。我现在就走。 -- Ah, those... Sorry, it was a misunderstanding. I'm going now.}
### {141}{}{Well then, it's never too late to learn something... Here. [He hands you an old, dusty book.] I hope you enjoy it. Excuse me now, I have to continue with my prayers...}
{141}{}{那么，学到东西永远不会太迟。。。在这里[他递给你一本尘封已久的旧书。]我希望你喜欢。对不起，我得继续祈祷。。。 -- Well then, it's never too late to learn something... Here. [He hands you an old, dusty book.] I hope you enjoy it. Excuse me now, I have to continue with my prayers...}
### {142}{}{Hmm... I guess I'll be learning something from this.}
{142}{}{嗯…我想我会从中学到一些东西。 -- Hmm... I guess I'll be learning something from this.}
### {143}{}{You are too young to understand God's ways. Go in peace now, I have to continue with my prayers.}
{143}{}{你还太年轻，不了解上帝的方式。现在平静地去吧，我必须继续我的祈祷。 -- You are too young to understand God's ways. Go in peace now, I have to continue with my prayers.}
### {144}{}{I'm going; for now.}
{144}{}{我要去；目前。 -- I'm going; for now.}
### {145}{}{Can I ask you something?}
{145}{}{我能问你点什么吗？ -- Can I ask you something?}
