### {100}{}{Hi there. Hey, could you buy me a Nuka-Cola, I really don't have the money to pay for it but I can tell you one good story instead.}
{100}{}{你好。嘿，你能给我买一杯努卡可乐吗？我真的没钱买，但我可以给你讲一个好故事。 -- Hi there. Hey, could you buy me a Nuka-Cola, I really don't have the money to pay for it but I can tell you one good story instead.}
### {101}{}{Well, OK.}
{101}{}{好吧。 -- Well, OK.}
### {102}{}{Sorry, don't have time for this.}
{102}{}{对不起，没有时间。 -- Sorry, don't have time for this.}
### {103}{}{Hey, you're back, you can still buy me that drink if you want...}
{103}{}{嘿，你回来了，如果你想的话，你仍然可以请我喝。。。 -- Hey, you're back, you can still buy me that drink if you want...}
### {104}{}{Here you go. Enjoy.}
{104}{}{给你。享受 -- Here you go. Enjoy.}
### {105}{}{Just saying hello.}
{105}{}{只是打个招呼。 -- Just saying hello.}
### {106}{}{[He drinks.] Ah, man, this is good, thanks. I owe you that story, wanna hear it?}
{106}{}{[他喝酒了。]啊，伙计，这很好，谢谢。我欠你这个故事，想听吗？ -- [He drinks.] Ah, man, this is good, thanks. I owe you that story, wanna hear it?}
### {107}{}{Please.}
{107}{}{请 -- Please.}
### {108}{}{Not interested.}
{108}{}{不感兴趣。 -- Not interested.}
### {109}{}{A few years ago, while I was working on the fields, I found a map. When I first saw it, it looked just like some very old piece of paper. Later, after spending some time analyzing it, I discovered it was actually a map of some installation not far from here.}
{109}{}{几年前，当我在田里干活时，我发现了一张地图。当我第一次看到它的时候，它看起来就像一张很旧的纸。后来，经过一段时间的分析，我发现它实际上是离这里不远的某个装置的地图。 -- A few years ago, while I was working on the fields, I found a map. When I first saw it, it looked just like some very old piece of paper. Later, after spending some time analyzing it, I discovered it was actually a map of some installation not far from here.}
### {110}{}{Really? Where is it?}
{110}{}{真正地它在哪里？ -- Really? Where is it?}
### {111}{}{I can just about show you on the map here, but I have never been able to find the place. The map has some military markings on it, so it could be the layout of some pre-war military base. Hey! If you happen to find anything just let me know. Okay?}
{111}{}{我可以在地图上给你看一下，但我一直找不到那个地方。地图上有一些军事标记，所以它可能是战前军事基地的布局。嘿如果你碰巧发现什么，请告诉我。可以 -- I can just about show you on the map here, but I have never been able to find the place. The map has some military markings on it, so it could be the layout of some pre-war military base. Hey! If you happen to find anything just let me know. Okay?}
### {112}{}{I will, thanks for the story.}
{112}{}{我会的，谢谢你的故事。 -- I will, thanks for the story.}
### {113}{}{Well looks like I got to hit the road, so long.}
{113}{}{看来我要上路了，这么久了。 -- Well looks like I got to hit the road, so long.}
### {114}{}{I don't have money at the moment. I'll be back.}
{114}{}{我现在没有钱。我会回来的。 -- I don't have money at the moment. I'll be back.}
### {115}{}{I hope you find what you're looking for.}
{115}{}{我希望你能找到你想要的东西。 -- I hope you find what you're looking for.}
### {116}{}{Thanks for that drink.}
{116}{}{谢谢你的饮料。 -- Thanks for that drink.}
### {117}{}{Good luck, you'll need it.}
{117}{}{祝你好运，你会需要它的。 -- Good luck, you'll need it.}
### {118}{}{Good day, friend.}
{118}{}{你好，朋友。 -- Good day, friend.}
### {119}{}{Want to buy me some more...? Hehe.}
{119}{}{想再给我买点。。。？呵呵。 -- Want to buy me some more...? Hehe.}
### {120}{}{Good day, friend.}
{120}{}{你好，朋友。 -- Good day, friend.}
### {121}{}{Want to hear a story?}
{121}{}{想听个故事吗？ -- Want to hear a story?}
### {122}{}{Got any drinks, friend?}
{122}{}{有饮料吗，朋友？ -- Got any drinks, friend?}
### {123}{}{Yep.}
{123}{}{是的。 -- Yep.}
### {124}{}{What do you want?}
{124}{}{你想要什么？ -- What do you want?}
### {125}{}{Good day, traveler.}
{125}{}{你好，旅行家。 -- Good day, traveler.}
{126}{}{}
