### {100}{}{Not now, beat it.}
{100}{}{现在不行，打败它。 -- Not now, beat it.}
### {101}{}{Take a hike.}
{101}{}{徒步旅行。 -- Take a hike.}
### {102}{}{[He looks at you for a moment, his face expression doesn't change. Like he knows you're here for a reason.] Who are you? Speak up and you may get to live a little longer.}
{102}{}{[他看了你一会儿，脸上的表情没有改变。好像他知道你来这里是有原因的。]你是谁？大声说出来，你可能会活得更长一点。 -- [He looks at you for a moment, his face expression doesn't change. Like he knows you're here for a reason.] Who are you? Speak up and you may get to live a little longer.}
### {103}{}{What is this place?}
{103}{}{这是什么地方？ -- What is this place?}
### {104}{}{Are you in charge here?}
{104}{}{你是这里的负责人吗？ -- Are you in charge here?}
### {105}{}{Sorry, wrong room.}
{105}{}{对不起，房间不对。 -- Sorry, wrong room.}
### {106}{}{[Pointing to the floor.] This place? Why the hell do you want to know?}
{106}{}{[指着地板。]这个地方？你为什么想知道？ -- [Pointing to the floor.] This place? Why the hell do you want to know?}
### {107}{}{Maybe so. Who's asking?}
{107}{}{也许是这样。谁在问？ -- Maybe so. Who's asking?}
### {108}{}{[Raise your voice.] You are smuggling weapons, and I'm here to confiscate them.}
{108}{}{[提高你的声音。]你在走私武器，我是来没收它们的。 -- [Raise your voice.] You are smuggling weapons, and I'm here to confiscate them.}
### {109}{}{Let me tell you something. [Whispers.] Just between you and me. [Pulls out a gun.] You're going to suffer, just like my men who died during that operation!}
{109}{}{让我告诉你一件事。[窃窃私语]就在你和我之间。[拔出枪。]你会受苦的，就像我的手下在那次行动中死去一样！ -- Let me tell you something. [Whispers.] Just between you and me. [Pulls out a gun.] You're going to suffer, just like my men who died during that operation!}
### {110}{}{What operation? I can't hear you... Can you repeat that a bit louder?!}
{110}{}{什么操作？我听不见你说话。。。你能再大声一点吗？！ -- What operation? I can't hear you... Can you repeat that a bit louder?!}
### {111}{}{The people of this town don't need more weapons, they need capable men.}
{111}{}{这个城镇的人民不需要更多的武器，他们需要有能力的人。 -- The people of this town don't need more weapons, they need capable men.}
### {112}{}{[Throws you an angry look.] Who said anything about any weapons? What the fuck are you talking about?}
{112}{}{[愤怒地看了你一眼。]谁说了什么武器的事？你他妈的在说什么？ -- [Throws you an angry look.] Who said anything about any weapons? What the fuck are you talking about?}
### {113}{}{Hm... smuggled weapons, I guess, in here.}
{113}{}{嗯…走私武器，我想，在这里。 -- Hm... smuggled weapons, I guess, in here.}
### {114}{}{Those grenades your men smuggled in...}
{114}{}{你的人走私进来的那些手榴弹。。。 -- Those grenades your men smuggled in...}
### {115}{}{Smuggled weapons? Who told you that?}
{115}{}{走私武器？谁告诉你的？ -- Smuggled weapons? Who told you that?}
### {116}{}{One of the locals.}
{116}{}{一个当地人。 -- One of the locals.}
### {117}{}{Does that person have a name?}
{117}{}{那个人有名字吗？ -- Does that person have a name?}
### {118}{}{He lives, uh... Over there. [You point in a random direction.]}
{118}{}{他住在。。。在那边[你指向一个随机的方向。] -- He lives, uh... Over there. [You point in a random direction.]}
### {119}{}{Yeah sure, there's a bar... And it's possible some barfly whispered you the buzz. Are you sure you didn't drink a bit more than you can handle? Because I can smell it on you...}
{119}{}{是的，当然，有个酒吧。。。有可能是某个酒吧女招待悄悄地对你说嗡嗡声。你确定你没有喝得太多吗？因为我能在你身上闻到。。。 -- Yeah sure, there's a bar... And it's possible some barfly whispered you the buzz. Are you sure you didn't drink a bit more than you can handle? Because I can smell it on you...}
### {120}{}{(You can smell your own body, but other than that...) Odd you can tell over your own foul stench of crap!}
{120}{}{（你可以闻到自己的身体，但除此之外……）你很可能从自己身上散发出恶臭！ -- (You can smell your own body, but other than that...) Odd you can tell over your own foul stench of crap!}
### {121}{}{All right, hold him guys... this is going to be fun. [You try to struggle but are overpowered. James takes a bottle of booze and spills it over you, causing you to choke on the liquid and gasp desperately for air. The last second before your senses leave you they let go and you take a deep breath.] Now YOU smell like crap! [And they proceed to throw you outside.]}
{121}{}{好吧，抓住他，伙计们。。。这会很有趣。[你试图挣扎，但被制服了。詹姆斯拿了一瓶酒洒在你身上，导致你被液体窒息，拼命地喘着粗气。在你的感官离开你之前的最后一秒，他们放开了你，你深呼吸。]现在你闻起来像垃圾！[然后他们把你扔到外面。] -- All right, hold him guys... this is going to be fun. [You try to struggle but are overpowered. James takes a bottle of booze and spills it over you, causing you to choke on the liquid and gasp desperately for air. The last second before your senses leave you they let go and you take a deep breath.] Now YOU smell like crap! [And they proceed to throw you outside.]}
### {122}{}{Smuggled grenades? Where would you get such a crazy idea?}
{122}{}{走私手榴弹？你从哪里得到这么疯狂的想法？ -- Smuggled grenades? Where would you get such a crazy idea?}
### {123}{}{I saw you doing it.}
{123}{}{我看到你这么做了。 -- I saw you doing it.}
### {124}{}{I was told by someone who saw it.}
{124}{}{看到它的人告诉我。 -- I was told by someone who saw it.}
### {125}{}{That guy Derek told me. [You point to the building across the front door.]}
{125}{}{德里克告诉我的那个人。（你指着前门对面的大楼。） -- That guy Derek told me. [You point to the building across the front door.]}
### {126}{}{Ah... Derek told you. Why is he suddenly interested in our plans?}
{126}{}{啊。。。Derek告诉过你。为什么他突然对我们的计划感兴趣？ -- Ah... Derek told you. Why is he suddenly interested in our plans?}
### {127}{}{He is worried about the town's safety. He said too many people have died because of the increasing number of weapons around. He's asking if you are willing to let the explosives go.}
{127}{}{他担心镇上的安全。他说，由于周围武器数量的增加，已经有太多人死亡。他在问你是否愿意放过炸药。 -- He is worried about the town's safety. He said too many people have died because of the increasing number of weapons around. He's asking if you are willing to let the explosives go.}
### {128}{}{He personally saw you smuggling those weapons. And he wants them confiscated.}
{128}{}{他亲眼看到你走私这些武器。他想没收它们。 -- He personally saw you smuggling those weapons. And he wants them confiscated.}
### {129}{}{Well... In that case... Look, those weapons cost me a lot. I'll hand over the weapons if he can refund me, about $3000.}
{129}{}{好那样的话看，那些武器花了我很多钱。如果他能退还我3000美元，我会把武器交出来。 -- Well... In that case... Look, those weapons cost me a lot. I'll hand over the weapons if he can refund me, about $3000.}
### {130}{}{I'll come back with the money.}
{130}{}{我会带着钱回来的。 -- I'll come back with the money.}
### {131}{}{Derek already gave me some money. Here's your $3000. So where are those weapons?}
{131}{}{德里克已经给了我一些钱。这是你的3000美元。那么这些武器在哪里呢？ -- Derek already gave me some money. Here's your $3000. So where are those weapons?}
### {132}{}{Here's the key for the store-room. It's the guarded door just left from the front door. And tell Derek that with this I'm repaying that favor I owed him, that our debts are even. Got it?}
{132}{}{这是储藏室的钥匙。就在前门左边有人把守的门。告诉Derek，用这个我会偿还我欠他的人情，我们的债务是平的。明白了吗？ -- Here's the key for the store-room. It's the guarded door just left from the front door. And tell Derek that with this I'm repaying that favor I owed him, that our debts are even. Got it?}
### {133}{}{Alright, I'll let him know.}
{133}{}{好吧，我会让他知道的。 -- Alright, I'll let him know.}
### {134}{}{[A grim smile forms on his face.] Derek saw me? So I guess, the whole town is buzzing by now. Which means there's no way we can do it again... Well, one thing comes to mind. [Pulls out a gun.] I suggest you start running!}
{134}{}{[脸上露出冷酷的微笑。]德里克看到我了吗？所以我想，现在整个城镇都很热闹。这意味着我们不可能再这样做了。。。我想到一件事。[拔出枪。]我建议你开始跑步！ -- [A grim smile forms on his face.] Derek saw me? So I guess, the whole town is buzzing by now. Which means there's no way we can do it again... Well, one thing comes to mind. [Pulls out a gun.] I suggest you start running!}
### {135}{}{Yeah... [Run to the front door.]}
{135}{}{是 啊[跑到前门。] -- Yeah... [Run to the front door.]}
### {136}{}{If you must know... Nobody is in charge here. We are running this show all by ourselves. Why do you want to know?}
{136}{}{如果你一定要知道。。。这里没人管。我们一个人在主持这个节目。你为什么想知道？ -- If you must know... Nobody is in charge here. We are running this show all by ourselves. Why do you want to know?}
### {137}{}{There are some public safety matters I wanted to talk about.}
{137}{}{我想谈谈一些公共安全问题。 -- There are some public safety matters I wanted to talk about.}
### {138}{}{Why don't you say who you are...? [Mumbling: (Just some smartass asking questions...)] Get the fuck out of here!}
{138}{}{你为什么不说你是谁。。。？[喃喃自语：（只是一些聪明人在问问题…）]滚出去！ -- Why don't you say who you are...? [Mumbling: (Just some smartass asking questions...)] Get the fuck out of here!}
### {139}{}{You again. Did you bring money?}
{139}{}{你又来了。你带钱了吗？ -- You again. Did you bring money?}
### {140}{}{Yes, here it is. [Give him $3000.]}
{140}{}{是的，给他。[给他3000美元。] -- Yes, here it is. [Give him $3000.]}
### {141}{}{Not yet.}
{141}{}{还没有。 -- Not yet.}
### {142}{}{That's the biggest fuckin' lie I've ever heard. You'd better turn around and walk outta here. Any more of your nonsense and you'll be as dead as those raiders. Understood!?}
{142}{}{这是我听过的最大的谎言。你最好转身离开这里。你再胡说八道，你就会和那些袭击者一样死。明白了！？ -- That's the biggest fuckin' lie I've ever heard. You'd better turn around and walk outta here. Any more of your nonsense and you'll be as dead as those raiders. Understood!?}
### {143}{}{You're a real bastard!}
{143}{}{你真是个混蛋！ -- You're a real bastard!}
### {144}{}{I'm going.}
{144}{}{我要走了。 -- I'm going.}
### {145}{}{If you have some business with me, talk! Otherwise, get lost!}
{145}{}{如果你有什么事要跟我说！否则就迷路！ -- If you have some business with me, talk! Otherwise, get lost!}
### {146}{}{Sorry, my mistake.}
{146}{}{对不起，我的错误。 -- Sorry, my mistake.}
### {147}{}{We need to think of something better.}
{147}{}{我们需要想出更好的办法。 -- We need to think of something better.}
### {148}{}{Those damn thieves must pay.}
{148}{}{那些该死的小偷必须付钱。 -- Those damn thieves must pay.}
### {149}{}{Raiders, heh... They are nothing.}
{149}{}{突袭者，嘿。。。他们什么都不是。 -- Raiders, heh... They are nothing.}
### {150}{}{For the right cause. To the end.}
{150}{}{为了正确的事业。到底。 -- For the right cause. To the end.}
### {151}{}{...any suggestions?}
{151}{}{…有什么建议吗？ -- ...any suggestions?}
### {152}{}{Yep, we had some tough moments.}
{152}{}{是的，我们有一些艰难的时刻。 -- Yep, we had some tough moments.}
### {153}{}{We sure beat those tribals.}
{153}{}{我们肯定打败了那些部落。 -- We sure beat those tribals.}
### {154}{}{[Throws an angry look at you.] You again! What the hell do you want now?}
{154}{}{[愤怒地看了你一眼。]又是你！你现在到底想要什么？ -- [Throws an angry look at you.] You again! What the hell do you want now?}
### {155}{}{You tried to cover up that operation of your... well, how would you call it, legitimate business, but it didn't work.}
{155}{}{你试图掩盖你。。。好吧，你怎么称呼它，合法的生意，但它不起作用。 -- You tried to cover up that operation of your... well, how would you call it, legitimate business, but it didn't work.}
### {156}{}{So you admit there are plans, involving certain weapons?}
{156}{}{所以你承认有计划，涉及某些武器？ -- So you admit there are plans, involving certain weapons?}
### {157}{}{I have a better idea, drop dead asshole!}
{157}{}{我有个更好的主意，扔死混蛋！ -- I have a better idea, drop dead asshole!}
### {158}{}{(You know you don't have a drinking habit but decide to keep the situation under control.) Hm... I guess you're right, I'll come back when I'm sober.}
{158}{}{（你知道你没有喝酒的习惯，但决定控制住局面。）嗯……我想你是对的，我清醒后会回来的。 -- (You know you don't have a drinking habit but decide to keep the situation under control.) Hm... I guess you're right, I'll come back when I'm sober.}
### {159}{}{[Exit.]}
{159}{}{[出口 -- Exit.]}
### {160}{}{[Smiles.] Well, if it ain't my drinking buddy. What...? Did you say you want another one? Or did you come back to lick up the spillage? Haha, get lost scum!}
{160}{}{[微笑]好吧，如果不是我的酒友。什么你说你想要另一个吗？还是你回来舔舐溢出的东西？哈哈，迷路的人渣！ -- [Smiles.] Well, if it ain't my drinking buddy. What...? Did you say you want another one? Or did you come back to lick up the spillage? Haha, get lost scum!}
### {161}{}{[Leave.]}
{161}{}{[离开 -- Leave.]}
### {162}{}{What public safety matters?}
{162}{}{什么是公共安全？ -- What public safety matters?}
### {163}{}{Nothing, nevermind.}
{163}{}{没什么，没关系。 -- Nothing, nevermind.}
