### {100}{}{:Status active: -Welcome to O.C.P. security net. }
{100}{}{：状态激活：-欢迎使用O.C.P.安全网。 -- :Status active: -Welcome to O.C.P. security net. }
### {101}{}{[Power integrity]}
{101}{}{[电源完整性 -- Power integrity]}
### {102}{}{[Security integrity]}
{102}{}{[安全完整性 -- Security integrity]}
### {103}{}{[Exit]}
{103}{}{[出口 -- Exit]}
### {104}{}{:Power integrity: -Holding at 85%.}
{104}{}{：电源完整性：-保持在85%。 -- :Power integrity: -Holding at 85%.}
### {105}{}{[Shut down main power supply]}
{105}{}{[关闭主电源 -- Shut down main power supply]}
### {106}{}{[Help]}
{106}{}{[帮助 -- Help]}
### {107}{}{[Log off]}
{107}{}{[注销 -- Log off]}
### {108}{}{:Shut down power: -Unable to comply, backup circuit on line.}
{108}{}{：关闭电源：-无法遵守，线路上有备用电路。 -- :Shut down power: -Unable to comply, backup circuit on line.}
### {109}{}{[Log off]}
{109}{}{[注销 -- Log off]}
### {110}{}{:Help: -Currently unavailable due to network failure.}
{110}{}{：帮助：-由于网络故障，当前不可用。 -- :Help: -Currently unavailable due to network failure.}
### {111}{}{[Search help protocol]}
{111}{}{[搜索帮助协议 -- Search help protocol]}
### {112}{}{[Log off]}
{112}{}{[注销 -- Log off]}
### {113}{}{:Search help protocols: -None found. Database: empty. }
{113}{}{：搜索帮助协议：-未找到。数据库：空。 -- :Search help protocols: -None found. Database: empty. }
### {114}{}{[Log off]}
{114}{}{[注销 -- Log off]}
### {115}{}{:Security integrity: -Currently off line.}
{115}{}{：安全完整性：-当前离线。 -- :Security integrity: -Currently off line.}
### {116}{}{[Activate security protocol]}
{116}{}{[激活安全协议 -- Activate security protocol]}
### {117}{}{[Function]}
{117}{}{[作用 -- Function]}
### {118}{}{[Log off]}
{118}{}{[注销 -- Log off]}
### {119}{}{:Activation initiated: -Enter confirmation code:}
{119}{}{：激活已启动：-输入确认码： -- :Activation initiated: -Enter confirmation code:}
### {120}{}{[AX9HOOJKN]}
{120}{}{[AX9HOOJKN -- AX9HOOJKN]}
### {121}{}{[ADFTY78XC]}
{121}{}{[ADFTY78XC -- ADFTY78XC]}
### {122}{}{[AX8HYT334]}
{122}{}{[ax8yt334 -- AX8HYT334]}
### {123}{}{:Level1 initiated: -Enter command.}
{123}{}{：Level1已启动：-输入命令。 -- :Level1 initiated: -Enter command.}
### {124}{}{[Emergency cleaning sequence]}
{124}{}{[紧急清洁顺序 -- Emergency cleaning sequence]}
### {125}{}{[Log off]}
{125}{}{[注销 -- Log off]}
### {126}{}{:Command accepted: -Enter security code:}
{126}{}{：已接受命令：-输入安全代码： -- :Command accepted: -Enter security code:}
### {127}{}{[DZTDBHVNJ]}
{127}{}{[DZTDBHVNJ -- DZTDBHVNJ]}
### {128}{}{[ZDTDJHHVB]}
{128}{}{[zdtdjhvb -- ZDTDJHHVB]}
### {129}{}{[HVBZDTDJT]}
{129}{}{[HVBZDTDJT -- HVBZDTDJT]}
### {130}{}{:Activation error: -Canceling...}
{130}{}{：激活错误：-正在取消。。。 -- :Activation error: -Canceling...}
### {131}{}{[Log off]}
{131}{}{[注销 -- Log off]}
### {132}{}{:Level 2 security code:}
{132}{}{：2级安全代码： -- :Level 2 security code:}
### {133}{}{[DZTDBHVNJ]}
{133}{}{[DZTDBHVNJ -- DZTDBHVNJ]}
### {134}{}{[HVBZDTDJT]}
{134}{}{[HVBZDTDJT -- HVBZDTDJT]}
### {135}{}{[ZDTDJHHVB]}
{135}{}{[zdtdjhvb -- ZDTDJHHVB]}
### {136}{}{:Level 3 security code:}
{136}{}{：3级安全代码： -- :Level 3 security code:}
### {137}{}{[HVBZDTDJT]}
{137}{}{[HVBZDTDJT -- HVBZDTDJT]}
### {138}{}{[DZTDBHVNJ]}
{138}{}{[DZTDBHVNJ -- DZTDBHVNJ]}
### {139}{}{[ZDTDJHHVB]}
{139}{}{[zdtdjhvb -- ZDTDJHHVB]}
### {140}{}{:Security on line: -Status... pending.}
{140}{}{：安全性在线：-状态。。。悬而未决的 -- :Security on line: -Status... pending.}
### {141}{}{[Log off]}
{141}{}{[注销 -- Log off]}
### {142}{}{:Security code error: -Exiting...}
{142}{}{：安全代码错误：-正在退出。。。 -- :Security code error: -Exiting...}
### {143}{}{[Log off]}
{143}{}{[注销 -- Log off]}
### {144}{}{:Power supply shut down: -Status... on.}
{144}{}{：电源关闭：-状态。。。在…上 -- :Power supply shut down: -Status... on.}
### {145}{}{[Log off]}
{145}{}{[注销 -- Log off]}
### {146}{}{:Function error: -No data available.}
{146}{}{：函数错误：-没有可用的数据。 -- :Function error: -No data available.}
### {147}{}{[Log off]}
{147}{}{[注销 -- Log off]}
### {148}{}{:Power integrity: -Off line.}
{148}{}{：电源完整性：-离线。 -- :Power integrity: -Off line.}
### {149}{}{[Activate power supply]}
{149}{}{[激活电源 -- Activate power supply]}
### {150}{}{[Log off]}
{150}{}{[注销 -- Log off]}
### {151}{}{:Power supply activation: -Status active.}
{151}{}{：电源设备激活：-状态激活。 -- :Power supply activation: -Status active.}
### {152}{}{[Log off]}
{152}{}{[注销 -- Log off]}
### {153}{}{[Back]}
{153}{}{[返回 -- Back]}
