### {100}{}{You see: a gang leader.}
{100}{}{你看：一个帮派头目。 -- You see: a gang leader.}
### {101}{}{He looks like he doesn't like visitors.}
{101}{}{他看起来不喜欢访客。 -- He looks like he doesn't like visitors.}
### {102}{}{Who the hell are you? A mailman? Hah! This is no good place to be delivering mail. In fact, I can't let you leave this place alive, but hey! I can guarantee you a quick death. [Reaches for his gun.] Before I... remove you, say, what are you doing here anyway?}
{102}{}{你到底是谁？邮差？哈哈！这不是投递邮件的好地方。事实上，我不能让你活着离开这个地方，但是嘿！我可以保证你会很快死去。[伸手去拿他的枪。]在我把你赶走之前，说，你在这里干什么？ -- Who the hell are you? A mailman? Hah! This is no good place to be delivering mail. In fact, I can't let you leave this place alive, but hey! I can guarantee you a quick death. [Reaches for his gun.] Before I... remove you, say, what are you doing here anyway?}
### {103}{}{I'm a simple mercenary, wandering around... killing people... it pays well!}
{103}{}{我是一个简单的雇佣兵，四处游荡。。。杀人。。。它很划算！ -- I'm a simple mercenary, wandering around... killing people... it pays well!}
### {104}{}{[You can see traces of blood going into the building.] You've done a half-assed job cleaning up your mess. I'll do a better one - cleaning up your stench!}
{104}{}{[你可以看到血的痕迹进入大楼。]你把烂摊子收拾得干干净净。我会做得更好——清理你的恶臭！ -- [You can see traces of blood going into the building.] You've done a half-assed job cleaning up your mess. I'll do a better one - cleaning up your stench!}
### {105}{}{Hah! Hahaha, you're a comedian, too? If you say so. Could be useful having someone like you. If you are good enough with guns, maybe you can join us. You must prove yourself first, of course. So what's it gonna be?}
{105}{}{哈哈！哈哈哈，你也是个喜剧演员？如果你这么说的话。有一个像你这样的人可能会很有用。如果你足够擅长枪支，也许你可以加入我们。当然，你必须首先证明自己。那会是什么呢？ -- Hah! Hahaha, you're a comedian, too? If you say so. Could be useful having someone like you. If you are good enough with guns, maybe you can join us. You must prove yourself first, of course. So what's it gonna be?}
### {106}{}{Hey, thanks. I sure am funny, huh? Tell you what, I'm gonna take your head then. I like the smile on it, asshole! [You reach for your weapon.]}
{106}{}{嘿，谢谢。我确实很有趣，是吗？告诉你吧，那我就拿走你的脑袋。我喜欢上面的笑容，混蛋！[你伸手去拿武器。] -- Hey, thanks. I sure am funny, huh? Tell you what, I'm gonna take your head then. I like the smile on it, asshole! [You reach for your weapon.]}
### {107}{}{Prove myself? Maybe I'm crazy, but I'll do it. You've got yourself a deal.}
{107}{}{证明自己？也许我疯了，但我会做的。你已经为自己做了一笔交易。 -- Prove myself? Maybe I'm crazy, but I'll do it. You've got yourself a deal.}
### {108}{}{OK pal, I'll take you to my boss. We're gonna see how good you really are. There's just one more thing... you're going blindfolded or you don't go at all, that's the rule.}
{108}{}{好吧，朋友，我带你去见我的老板。我们会看看你到底有多优秀。还有一件事。。。你要么蒙上眼睛，要么根本不去，这是规则。 -- OK pal, I'll take you to my boss. We're gonna see how good you really are. There's just one more thing... you're going blindfolded or you don't go at all, that's the rule.}
### {109}{}{Well, if you have to... [Comply.]}
{109}{}{好吧，如果你必须…[顺从。] -- Well, if you have to... [Comply.]}
### {110}{}{Easy man. I'm just passing through. I don't want any trouble.}
{110}{}{放松点，我只是路过。我不想惹麻烦。 -- Easy man. I'm just passing through. I don't want any trouble.}
### {111}{}{I'm sure you don't, but I do. Perhaps if you give me all your stuff I will let you live.}
{111}{}{我相信你不会，但我会的。也许如果你把你所有的东西都给我，我会让你活着。 -- I'm sure you don't, but I do. Perhaps if you give me all your stuff I will let you live.}
### {112}{}{Why don't you drop dead, rat-face!}
{112}{}{你为什么不去死呢，老鼠脸！ -- Why don't you drop dead, rat-face!}
### {113}{}{You're supposed to be somewhere else.}
{113}{}{你应该去别的地方。 -- You're supposed to be somewhere else.}
### {114}{}{What are you doing here?}
{114}{}{你在这里干什么？ -- What are you doing here?}
### {115}{}{Stop your wandering and get to it!}
{115}{}{别再闲逛了，快去吧！ -- Stop your wandering and get to it!}
