### {100}{}{You see: Jack.}
{100}{}{你看：杰克。 -- You see: Jack.}
### {101}{}{It's Jack. The local drug-store owner.}
{101}{}{我是杰克。当地药店老板。 -- It's Jack. The local drug-store owner.}
### {102}{}{Hey there stranger. Didn't see ya before. Wanna take a look at my range of medical supplies.}
{102}{}{嘿，陌生人。以前没见过你。想看看我的医疗用品系列吗。 -- Hey there stranger. Didn't see ya before. Wanna take a look at my range of medical supplies.}
### {103}{}{Sure.}
{103}{}{当然 -- Sure.}
### {104}{}{Later.}
{104}{}{后来 -- Later.}
### {105}{}{Pleasure doing business with you.}
{105}{}{很高兴和你做生意。 -- Pleasure doing business with you.}
### {106}{}{Bye.}
{106}{}{再见 -- Bye.}
### {107}{}{Hello again. Can Jack offer you some of his goods?}
{107}{}{你好。杰克能给你一些他的商品吗？ -- Hello again. Can Jack offer you some of his goods?}
### {108}{}{Show me me what you've got.}
{108}{}{让我看看你有什么。 -- Show me me what you've got.}
### {109}{}{Nothing now.}
{109}{}{现在什么都没有。 -- Nothing now.}
### {110}{}{Do you have any heart pills in stock?}
{110}{}{你有心脏药存货吗？ -- Do you have any heart pills in stock?}
### {111}{}{I'm sorry to tell you, but a few days ago I was robbed. They took my money, the medical supplies I'd just bought, everything... I even had the pills you want, but they took those, too! And there won't be any more shipments neither, and even if, I don't have the money to resupply. Damn shame those bastards robbed me...}
{111}{}{很抱歉告诉你，但几天前我被抢劫了。他们拿走了我的钱，我刚买的医疗用品，所有的东西。。。我甚至有你想要的药，但他们也吃了！而且也不会有更多的货物了，即使这样，我也没有钱补给。真可耻，那些混蛋抢了我。。。 -- I'm sorry to tell you, but a few days ago I was robbed. They took my money, the medical supplies I'd just bought, everything... I even had the pills you want, but they took those, too! And there won't be any more shipments neither, and even if, I don't have the money to resupply. Damn shame those bastards robbed me...}
### {112}{}{Is there any way I could find who robbed you?}
{112}{}{我有办法找到抢劫你的人吗？ -- Is there any way I could find who robbed you?}
### {113}{}{I'm sorry to hear it. Guess I'm gonna try somewhere else then.} #quest cancel#{114}{}{I really don't know who robbed me. The first time I saw them was when they broke into my store swinging their guns around! I was so scared I hid under the table... When I got up, there was only a big mess left, some of my furniture is still broken. [He looks around.] Well, I s'pose it can't hurt to try and find those guys. Know what, if you return my stolen goods, I'll give you something in return.}
{113}{}{I'm sorry to hear it. Guess I'm gonna try somewhere else then.} #quest cancel#{114}{}{我真的不知道是谁抢了我。我第一次看到他们是在他们挥舞着枪闯入我的商店时！我吓得躲在桌子下面。。。当我起床的时候，只剩下一片狼藉，我的一些家具还坏着。[他环顾四周。]好吧，我想找那些家伙也无妨。知道吗，如果你还我的赃物，我会给你一些回报。 -- I really don't know who robbed me. The first time I saw them was when they broke into my store swinging their guns around! I was so scared I hid under the table... When I got up, there was only a big mess left, some of my furniture is still broken. [He looks around.] Well, I s'pose it can't hurt to try and find those guys. Know what, if you return my stolen goods, I'll give you something in return.}
### {115}{}{OK. Tell me what you know.}
{115}{}{好吧，告诉我你知道什么。 -- OK. Tell me what you know.}
### {116}{}{Right! I'm gonna question some people, and then I'm gonna shoot some. [You leave.]} #quest cancel{117}{}{Nah, that's not really my concern. I'll try somewhere else.} #quest cancel#{118}{}{Let me see... There were three of them if I recall correctly. I didn't really see their faces but they were wearing purple robes. That's all I can tell.}
{116}{}{Right! I'm gonna question some people, and then I'm gonna shoot some. [You leave.]} #quest cancel{117}{}{Nah, that's not really my concern. I'll try somewhere else.} #quest cancel#{118}{}{让我看看。。。如果我没记错的话，一共有三个。我没有真正看到他们的脸，但他们穿着紫色的长袍。我只能说这些。 -- Let me see... There were three of them if I recall correctly. I didn't really see their faces but they were wearing purple robes. That's all I can tell.}
### {119}{}{OK. If I find out something, you'll be the first to know. }
{119}{}{好的。如果我发现什么，你会第一个知道的。 -- OK. If I find out something, you'll be the first to know. }
### {120}{}{What did they steal exactly?}
{120}{}{他们到底偷了什么？ -- What did they steal exactly?}
### {121}{}{They stole $2000, five stimpaks, two mentats, two heart pills and... Yes, one antidote flask.}
{121}{}{他们偷走了2000美元，五支兴奋剂，两支mentat，两片心脏药和。。。是的，一个解药瓶。 -- They stole $2000, five stimpaks, two mentats, two heart pills and... Yes, one antidote flask.}
### {122}{}{Alright, that should be enough. I'm off to find them.}
{122}{}{好吧，这就足够了。我要去找他们。 -- Alright, that should be enough. I'm off to find them.}
### {123}{}{You're back. Did you find those bastards who robbed me?}
{123}{}{你回来了。你找到那些抢我的混蛋了吗？ -- You're back. Did you find those bastards who robbed me?}
### {124}{}{I'm still looking for them.}
{124}{}{我还在找他们。 -- I'm still looking for them.}
### {125}{}{Yes, I recovered your supplies. And those robbers are never gonna come back again.}
{125}{}{是的，我找到了你的补给。那些强盗再也回不来了。 -- Yes, I recovered your supplies. And those robbers are never gonna come back again.}
### {126}{}{I don't wanna know how you did it, but I want to thank you. Here's some money and medical supplies for you. [Hands you $2000 and 2 Stimpaks.] And, you told me Karl needs some heart pills? [Hands you two boxes.] I think this will do. Thank you again and stop by anytime! [He smiles at you.]}
{126}{}{我不想知道你是怎么做到的，但我想谢谢你。给你一些钱和医疗用品。[递给你2000美元和2个Stimpaks。]你告诉我卡尔需要一些心脏药吗？[递给你两个盒子。]我想这样就可以了。再次谢谢你，随时来！[他对你微笑。] -- I don't wanna know how you did it, but I want to thank you. Here's some money and medical supplies for you. [Hands you $2000 and 2 Stimpaks.] And, you told me Karl needs some heart pills? [Hands you two boxes.] I think this will do. Thank you again and stop by anytime! [He smiles at you.]}
### {127}{}{Thanks, I was glad to help.}
{127}{}{谢谢，我很乐意帮忙。 -- Thanks, I was glad to help.}
### {128}{}{I'm busy at the moment.}
{128}{}{我现在很忙。 -- I'm busy at the moment.}
### {129}{}{I was robbed, remember!?}
{129}{}{我被抢劫了，记得吗！？ -- I was robbed, remember!?}
### {130}{}{No, no, you just stay away from my store.}
{130}{}{不，不，你离我的店远点。 -- No, no, you just stay away from my store.}
### {131}{}{Don't you have anything better to do!?}
{131}{}{你没有更好的事情可做吗！？ -- Don't you have anything better to do!?}
### {132}{}{If I were you I would be getting as far away from this town as possible.}
{132}{}{如果我是你，我会尽可能远离这个小镇。 -- If I were you I would be getting as far away from this town as possible.}
### {133}{}{You're a bad person!}
{133}{}{你是个坏人！ -- You're a bad person!}
### {134}{}{Doc Karl asked me to find some heart pills for his patients. Do you have any of those in your stock?}
{134}{}{卡尔医生让我给他的病人找些心脏药。你的存货里有这些吗？ -- Doc Karl asked me to find some heart pills for his patients. Do you have any of those in your stock?}
### {135}{}{I don't wanna know how you dealt with those robbers, but I do want to thank you. Here's some money for you. [Hands you $2000.] And some old gun I found a while ago, it's not the best, but perhaps you can shoot some rats with it. [He smiles.]}
{135}{}{我不想知道你是怎么对付那些强盗的，但我真的想谢谢你。给你一些钱。[递给你2000美元。]还有我不久前发现的一把旧枪，它不是最好的，但也许你可以用它射杀一些老鼠。[他笑了。] -- I don't wanna know how you dealt with those robbers, but I do want to thank you. Here's some money for you. [Hands you $2000.] And some old gun I found a while ago, it's not the best, but perhaps you can shoot some rats with it. [He smiles.]}
### {136}{}{Can I see your stock?}
{136}{}{我能看看你的存货吗？ -- Can I see your stock?}
### {137}{}{What's the story behind that crashed Vertibird?}
{137}{}{迷魂鸟坠毁的背后是什么故事？ -- What's the story behind that crashed Vertibird?}
### {138}{}{It's an intricate piece of technology. From what I red in the ancient books, something that people used to fly around in and deliver death and destruction effectively by the push of a button. At present, people are more knee-deep in brahmin shit if you get my meaning. Its interior is completely stripped, some wiring is left hanging though... Ahem, are you here to buy something or what?}
{138}{}{这是一项复杂的技术。从我在古籍中看到的，人们过去常常在里面飞来飞去，只需按下一个按钮就能有效地传递死亡和毁灭。现在，如果你明白我的意思的话，人们更喜欢婆罗门的大便。它的内部被完全剥离，一些电线仍然挂着。。。嗯，你是来买东西还是什么的？ -- It's an intricate piece of technology. From what I red in the ancient books, something that people used to fly around in and deliver death and destruction effectively by the push of a button. At present, people are more knee-deep in brahmin shit if you get my meaning. Its interior is completely stripped, some wiring is left hanging though... Ahem, are you here to buy something or what?}
### {139}{}{You have failed to use your steal skill.}
{139}{}{你没有使用你的偷技。 -- You have failed to use your steal skill.}
### {140}{}{[Chance: }
{140}{}{[机会： -- [Chance: }
### {141}{}{.} #Unused{142}{}{You have returned Jack's stolen goods. You earn 1000 exp. points.}
{141}{}{.} #Unused{142}{}{你已经归还了杰克的赃物。你可以获得1000经验点。 -- You have returned Jack's stolen goods. You earn 1000 exp. points.}
