### {100}{}{You successfully disable the lock.}
{100}{}{您已成功禁用锁定。 -- You successfully disable the lock.}
### {101}{}{You fail to disable the lock.}
{101}{}{您未能禁用锁。 -- You fail to disable the lock.}
### {102}{}{You successfully lock the object.}
{102}{}{您已成功锁定对象。 -- You successfully lock the object.}
### {103}{}{You fail to lock the object.}
{103}{}{您未能锁定对象。 -- You fail to lock the object.}
### {200}{}{ successfully disabled the lock.}
{200}{}{已成功禁用锁定。 --  successfully disabled the lock.}
### {201}{}{ fails to disable the lock.}
{201}{}{无法禁用锁定。 --  fails to disable the lock.}
### {202}{}{ successfully locked the object.}
{202}{}{已成功锁定对象。 --  successfully locked the object.}
### {203}{}{ fails to lock the object.}
{203}{}{未能锁定对象。 --  fails to lock the object.}
### {300}{}{The explosion destroys the lock on the object.}
{300}{}{爆炸破坏了物体上的锁。 -- The explosion destroys the lock on the object.}
### {301}{}{The explosion fails to remove the lock from the object.}
{301}{}{爆炸未能将锁从物体上取下。 -- The explosion fails to remove the lock from the object.}
### {400}{}{You successfully pry open the lock on the object.}
{400}{}{你成功地撬开了物体上的锁。 -- You successfully pry open the lock on the object.}
### {401}{}{You fail to pry the lock on the object open.}
{401}{}{你没能撬开物体上的锁。 -- You fail to pry the lock on the object open.}
### {500}{}{ successfully pried open the lock on the object.}
{500}{}{成功地撬开了物体上的锁。 --  successfully pried open the lock on the object.}
### {501}{}{ fails to pry the lock on the object open.}
{501}{}{未能撬开物体上的锁。 --  fails to pry the lock on the object open.}
