### {100}{}{A wanted poster with a crude charcoal sketch of a wanted person. The person on the poster looks familiar.}
{100}{}{一张通缉海报，上面画着一个通缉犯的粗制滥造的木炭素描。海报上的人看起来很熟悉。 -- A wanted poster with a crude charcoal sketch of a wanted person. The person on the poster looks familiar.}
### {101}{}{The caption reads.}
{101}{}{标题如下。 -- The caption reads.}
### {102}{}{Wanted Dead or Alive for Child Killing and being a Rat Bastard. Reward $10,000 Dead or $5,000 Alive.}
{102}{}{因杀害儿童和做老鼠混蛋而被通缉。奖励10000美元死亡或5000美元活着。 -- Wanted Dead or Alive for Child Killing and being a Rat Bastard. Reward $10,000 Dead or $5,000 Alive.}
### {103}{}{Wanted Dead or Alive for Child Killing. Reward $10,000 Dead or $5,000 Alive.}
{103}{}{因杀害儿童而被通缉。奖励10000美元死亡或5000美元活着。 -- Wanted Dead or Alive for Child Killing. Reward $10,000 Dead or $5,000 Alive.}
### {104}{}{Wanted Dead or Alive for Being a Rat Bastard. Reward $10,000 Dead or $5,000 Alive.}
{104}{}{因做老鼠混蛋而被通缉。奖励10000美元死亡或5000美元活着。 -- Wanted Dead or Alive for Being a Rat Bastard. Reward $10,000 Dead or $5,000 Alive.}
