#{100}{}{You see a gang leader.}
{100}{}{你看到一个帮派头目。}
#{101}{}{You see the leader of the "Ferocious Molerats".}
{101}{}{你看到“凶恶的猥亵者”的首领了。}
#{102}{}{We have a lot of work to do. Stay out of our way.}
{102}{}{我们有很多工作要做。别挡我们的路。}
#{103}{}{Quiet! I hear them, they're close!}
{103}{}{安静的！我听见了，他们就在附近！}
#{110}{}{Hey, you! Yeah, you! You fucked up now, kiddo! Don't you even dare to move - I'll drill you six times before you can turn around!}
{110}{}{嘿，你！是的，你！你现在搞砸了，孩子！你都不敢动-我要给你打六下，你才能转身！}
#{111}{}{Woah, hold on! I'm here to help you.}
{111}{}{喔，等等！我是来帮你的。}
#{112}{}{Calm down. Tell me what you want, and I'll hear you out.}
{112}{}{冷静。告诉我你想要什么，我会听你说完的。}
#{113}{}{You're the one who needs help, fucknut! But it's your lucky day! I need some live bait to deal with a pain in my ass, so I'm gonna offer you a deal!}
{113}{}{你才是需要帮助的人，混蛋！但今天是你的幸运日！我需要一些活诱饵来对付我屁股上的疼痛，所以我要给你一个交易！}
#{114}{}{Uh-oh, guys, the big scary hero of the wastes is giving us one chance to explain ourselves! I'm shaking in my fuckin' boots over here! [he sneers] You're already dead, you cum-guzzling limpdick, you just don't know it yet. If you want to earn your life back, you'd better do exactly what I fucking say.}
{114}{}{哦，伙计们，废物的大英雄给了我们一个解释自己的机会！我他妈的在这里发抖！[他冷笑]你已经死了，你这个贪吃的跛子，你只是还不知道而已。如果你想夺回你的生命，你最好照我说的做。}
#{115}{}{And what's that?}
{115}{}{那是什么？}
#{116}{}{You know, I've changed my mind. I think the world will be better off without you in it. [attack]}
{116}{}{你知道，我改变主意了。我想没有你这个世界会更好。[攻击]}
#{117}{}{You see this cave? [he motions with his head towards a very obvious cave entrance] There's a bunch of pussies in there shitting themselves, too scared to come out and face us.}
{117}{}{你看到这个洞了吗？[他把头移向一个很明显的洞穴入口]那里有一群娘娘腔在拉屎，太害怕了，不敢出来面对我们。}
#{118}{}{And you want me to smoke them out.}
{118}{}{你想让我把它们抽出来。}
#{119}{}{Oooh, did you figure that out all by yourself, numbnuts? Get the fuck in there. Don't come out unless you're bringing them with you. Got it?}
{119}{}{哦，你自己想出来的吗，笨蛋？他妈的给我进去。除非你带着他们，否则别出来。知道了？}
#{120}{}{Fine, I'll see what I can do.}
{120}{}{好吧，我看看我能做什么。}
#{121}{}{[He whistles to the others] Clear a path! This one's going in! [he leans in close and snarls in your ear] Remember, don't even think of coming out without that caravan. Trust me, you'd rather starve to death in there than piss us off.}
{121}{}{[他对其他人吹口哨]让开一条路！这个要进去了！[他靠得很近，在你耳边怒吼]记住，别想没有那辆大篷车就出来。相信我，你宁愿饿死也不愿惹我们生气。}
#{122}{}{[Go inside]}
{122}{}{[进去]}
#{123}{}{[Resist]}
{123}{}{[抵抗]}
#{124}{}{I don't like any of those options. I'll be on my way now.}
{124}{}{我不喜欢这些选择。我马上就来。}
#{125}{}{[He readies his weapon] Halt, motherfucker!}
{125}{}{[他准备好武器]停下，混蛋！}
#{126}{}{Alright, man, relax, I'll do whatever you want.}
{126}{}{好吧，伙计，放松点，你想干什么我就干什么。}
#{127}{}{[Ignore]}
{127}{}{[忽略]}
#{128}{}{What the... Do you have a death wish, asshole?! Get the fuck back in there! And don't come out without that caravan next time!}
{128}{}{怎么了...你有死亡愿望吗，混蛋？！他妈的给我滚回去！下次没有那辆大篷车就别出来！}
#{129}{}{They're already dead. You can go in and get them.}
{129}{}{他们已经死了。你可以进去拿。}
#{130}{}{I just wanted some fresh air. I'm going back in now.}
{130}{}{我只是想呼吸点新鲜空气。我要回去了。}
#{131}{}{This has gone on far enough. [attack]}
{131}{}{这已经足够了。[攻击]}
#{132}{}{ARE YOU FUCKING WITH ME?! [he readies his weapon] You think this is funny?! Because you're gonna look fucking HILARIOUS when I blow your fucking head open, you understand?! The last thing you'll ever see is me eye-fucking your goddamn skull, you shit-eating prick!}
{132}{}{你在耍我吗？！[他准备好武器]你觉得这很有趣？！因为当我把你脑袋炸开的时候你会看起来很滑稽，明白吗？！你看到的最后一件事就是我的眼睛操你该死的脑袋，你这个吃屎的混蛋！}
#{133}{}{You should calm down. You'll live longer.}
{133}{}{你应该冷静下来。你会活得更长。}
#{134}{}{[The raiders draw their weapons.]}
{134}{}{[袭击者拔出武器。]}
#{135}{}{[Draw yours.]}
{135}{}{[画你的]}
#{136}{}{You'd better have good fucking news for me, or I'll bury you alive!}
{136}{}{你最好告诉我好消息，否则我会活埋你！}
#{137}{}{[He starts screaming in rage, his face turning red and his eyes almost popping out of their sockets] Who the FUCK do you FUCKING think you're fucking FUCKING with, you ass-gobbling dogfucker?! WE'RE THE FEROCIOUS FUCKING MOLERATS!!! We're the most vicious motherfucking killers in the wasteland, do you hear me?! We fucking OWN everyone in sight of these mountains, they live and die because WE say so! NOBODY fucks with us! NOBODY!!!}
{137}{}{[他开始愤怒地尖叫，他的脸变得通红，他的眼睛几乎从眼窝里蹦出来]你他妈的以为你在和谁做爱，你这狗娘养的？！我们是他妈的凶残的骚扰者！！！我们是这片荒原上最邪恶的杀手，你听见了吗？！我们他妈的把所有人都藏在山上，他们生死存亡都是因为我们这么说！没人和我们做爱！没有人！！！}
#{138}{}{Oh really? Then we'll go check it out - right after you. Gear up, guys!}
{138}{}{哦，真的吗？那我们就去看看-就在你后面。准备好，伙计们！}
#{139}{}{Here we go...}
{139}{}{我们走吧...}
#{1114}{}{Uh-oh, guys, the big, tough bitch of the wastes is giving us one chance to explain ourselves! I'm shaking in my fuckin' boots over here! [he sneers] You're already dead, you pus-dripping cunt, you just don't know it yet. If you want to earn your life back, you'd better do exactly what I fucking say.}
{1114}{}{哦，伙计们，这个又大又硬的废物婊子给了我们一个解释自己的机会！我他妈的在这里发抖！[他冷笑]你已经死了，你这个流脓的贱人，你只是还不知道而已。如果你想夺回你的生命，你最好照我说的做。}
#{1119}{}{Oooh, did you figure that out all by yourself, sugar tits? Get the fuck in there. Don't come out unless you're bringing them with you. Got it?}
{1119}{}{哦，你自己想出来的吗，甜心？他妈的给我进去。除非你带着他们，否则别出来。知道了？}
#{1128}{}{What the... Do you have a death wish, bitch?! Get the fuck back in there! And don't come out without that caravan next time!}
{1128}{}{怎么了...你有死亡愿望吗，婊子？！他妈的给我滚回去！下次没有那辆大篷车就别出来！}
#{1132}{}{ARE YOU FUCKING WITH ME?! [he readies his weapon] You think this is funny?! Because you're gonna look fucking HILARIOUS when I blow your fucking head open, you understand?! The last thing you'll ever see is me eye-fucking your goddamn skull, you dumb fucking whore!}
{1132}{}{你在耍我吗？！[他准备好武器]你觉得这很有趣？！因为当我把你脑袋炸开的时候你会看起来很滑稽，明白吗？！你看到的最后一件事就是我用眼睛盯着你那该死的脑袋，你这该死的婊子！}
#{1137}{}{[He starts screaming in rage, his face turning red and his eyes almost popping out of their sockets] Who the FUCK do you FUCKING think you're fucking FUCKING with, you dog-sucking cumguzzler?! WE'RE THE FEROCIOUS FUCKING MOLERATS!!! We're the most vicious motherfucking killers in the wasteland, do you hear me?! We fucking OWN everyone in sight of these mountains, they live and die because WE say so! NOBODY fucks with us! NOBODY!!!}
{1137}{}{[他开始愤怒地尖叫，他的脸变得通红，他的眼睛几乎要从眼窝里蹦出来]你他妈的以为你在和谁做爱，你这个吸狗的家伙？！我们是他妈的凶残的骚扰者！！！我们是这片荒原上最邪恶的杀手，你听见了吗？！我们他妈的把所有人都藏在山上，他们生死存亡都是因为我们这么说！没人和我们做爱！没有人！！！}
