#{100}{}{You see a local.}
{100}{}{你看到一个当地人。}
#{101}{}{You see one of Black Rock's citizens.}
{101}{}{你看到黑岩的一个市民。}
#{102}{}{I knew Jed would die soon.}
{102}{}{我知道杰德很快就会死。}
#{103}{}{Jed's done so much for us. I hope he's in a better place.}
{103}{}{杰德为我们做了很多。我希望他在一个更好的地方。}
#{104}{}{Not many people get to die of old age nowadays.}
{104}{}{现在没有多少人会死于老年。}
#{105}{}{Jed always said, "When I die, send me to the heavens." Whatever that means.}
{105}{}{杰德总是说，“当我死的时候，把我送到天堂去。”不管那是什么意思。}
#{106}{}{I dreamed that Smith was in heaven, but it was full of tribals. Bad luck.}
{106}{}{我梦见史密斯在天堂，但那里满是部落。运气不好。}
#{107}{}{Jed doesn't have much time left. I can feel it.}
{107}{}{杰德没有多少时间了。我能感觉到。}
#{108}{}{If Jed dies, I may cry. You know... Just a little.}
{108}{}{如果杰德死了，我可能会哭。你知道的...就一点点。}
#{109}{}{The heavens are waiting for Jed... Ah, whatever.}
{109}{}{天堂在等杰德...啊，随便了。}
#{110}{}{They say some outsider is digging up the graves, but I think it's Bob.}
{110}{}{他们说有外人在挖坟墓，但我想是鲍勃。}
#{111}{}{If I wake up to find one more defiled grave... Oh, Bob's gonna get it.}
{111}{}{如果我醒来发现另一个被玷污的坟墓...哦，鲍勃会明白的。}
#{112}{}{Bob's a good guy, but he needs to learn how to control himself.}
{112}{}{鲍勃是个好人，但他需要学会控制自己。}
#{113}{}{}
{113}{}{}
#{114}{}{}
{114}{}{}
#{115}{}{When I die, I hope geckos get to my body before Bob does.}
{115}{}{当我死的时候，我希望壁虎能比鲍勃先到我的身体。}
#{116}{}{We have to bring Bob to justice! How many times will he defile our dead?}
{116}{}{我们必须把鲍勃绳之以法！他要玷污我们的死人多少次？}
#{117}{}{Bob's a good guy, but he needs to learn how to control himself.}
{117}{}{鲍勃是个好人，但他需要学会控制自己。}
#{118}{}{}
{118}{}{}
#{119}{}{}
{119}{}{}
#{120}{}{Mike was one of our best hunters! Why did you do this?!}
{120}{}{迈克是我们最好的猎人之一！你为什么这么做？！}
#{121}{}{Did you really have to kill Mike?!}
{121}{}{你真的要杀迈克吗？！}
#{122}{}{How could you kill Mike?!}
{122}{}{你怎么能杀了迈克？！}
#{123}{}{I liked Mike, but I knew this would happen eventually.}
{123}{}{我喜欢迈克，但我知道这终究会发生。}
#{124}{}{}
{124}{}{}
#{125}{}{Mike sure loves to fight.}
{125}{}{迈克当然喜欢打架。}
#{126}{}{If there's one guy in town you shouldn't mess with, it's Mike.}
{126}{}{如果镇上有一个人你不该惹他，那就是迈克。}
#{127}{}{Mike is going to get drunk and go looking for a fight again.}
{127}{}{迈克要喝醉了，又要去打架了。}
#{128}{}{That Mike really needs an ass-kicking.}
{128}{}{迈克真的需要被揍一顿。}
#{129}{}{}
{129}{}{}
#{130}{}{Oh, did Mike beat you? Ha! Must have been fun.}
{130}{}{噢，迈克打败你了吗？哈！一定很有趣。}
#{131}{}{Damn, Mike really beat your ass, didn't he?}
{131}{}{妈的，迈克真的打了你的屁股，不是吗？}
#{132}{}{Man, I was really hoping for someone to kick Mike's ass. Too bad.}
{132}{}{伙计，我真希望有人能踢迈克的屁股。太糟糕了。}
#{133}{}{Don't give up. Mike hasn't been beaten since... Hmm, a couple of days ago, maybe.}
{133}{}{不要放弃。迈克从那以后就没被打过...嗯，也许是几天前吧。}
#{134}{}{}
{134}{}{}
#{135}{}{Were you the one that beat up Mike? It's an honor!}
{135}{}{是你打迈克的吗？很荣幸！}
#{136}{}{So you beat Mike, huh? That's impressive.}
{136}{}{所以你打败了迈克？真令人印象深刻。}
#{137}{}{Hey, good job on Mike!}
{137}{}{嘿，迈克干得好！}
#{138}{}{That should keep Mike from going looking for a fight for a while.}
{138}{}{这应该可以让迈克暂时不去打架。}
#{139}{}{Hahaha!! You kicked Mike's ass! High five!}
{139}{}{哈哈哈！！你踢了迈克的屁股！击掌！}
#{140}{}{There's been more raiders around lately. Hmm, how do I know you're not one of them?}
{140}{}{最近有更多的袭击者。嗯，我怎么知道你不是他们中的一员？}
#{141}{}{Raiders aren't welcome here.}
{141}{}{这里不欢迎袭击者。}
#{142}{}{Raiding ain't a life that ends well.}
{142}{}{劫掠不是一个好结局。}
#{143}{}{May god strike me down if I don't kill at least one raider this month!}
{143}{}{如果我这个月不杀至少一个袭击者，愿上帝击倒我！}
#{144}{}{}
{144}{}{}
#{145}{}{If raiders attack the next caravan, we won't get another.}
{145}{}{如果突袭者攻击下一个商队，我们就不会再有了。}
#{146}{}{More raiders this morning. How long is this going to go on?}
{146}{}{今早又来了袭击者。这要持续多久？}
#{147}{}{I wish those raiders would just die.}
{147}{}{我真希望那些袭击者会死。}
#{148}{}{}
{148}{}{}
#{149}{}{}
{149}{}{}
#{150}{}{Uh, hi.}
{150}{}{呃，你好。}
#{151}{}{What a shitty day. Just like yesterday.}
{151}{}{真是糟糕的一天。就像昨天一样。}
#{152}{}{Don't shake my hand. I was just in the toilet.}
{152}{}{别跟我握手。我刚才在厕所里。}
#{153}{}{It's getting crowded around here.}
{153}{}{这里越来越拥挤了。}
#{154}{}{You aren't gonna settle down here, I hope?}
{154}{}{我希望你不会在这里安顿下来？}
#{155}{}{Have you met William? He's a good guy. Not a lot of sense, though.}
{155}{}{你见过威廉吗？他是个好人。不过，没什么道理。}
#{156}{}{You talked to Justin yet? A harsh man, but irreplaceable.}
{156}{}{你和贾斯汀谈过了吗？一个严厉的人，但不可替代。}
#{157}{}{How could a whole brahmin just disappear?}
{157}{}{整个双头牛怎么会消失？}
#{158}{}{If I were William, I'd kick his boy's ass.}
{158}{}{如果我是威廉，我会踢他儿子的屁股。}
#{159}{}{Only in Black Rock could a whole brahmin just disappear.}
{159}{}{只有在黑岩中，整个双头牛才能消失。}
#{160}{}{Those slaves are nothing but trouble.}
{160}{}{那些奴隶只不过是麻烦。}
#{161}{}{Slaves belong with their master, not in Black Rock!}
{161}{}{奴隶属于他们的主人，而不是在黑岩！}
#{162}{}{The slaves are finally gone? That's good to hear.}
{162}{}{奴隶们终于走了？很高兴听到你这么说。}
#{163}{}{If we'll get any more escaped slaves, we'll do the same thing.}
{163}{}{如果我们再抓到逃跑的奴隶，我们也会这么做。}
#{164}{}{Has William lost his damn mind? We don't need escaped slaves hiding around here!}
{164}{}{威廉疯了吗？我们不需要逃跑的奴隶躲在这里！}
#{165}{}{William took in those slaves? He's too soft.}
{165}{}{威廉收留了那些奴隶？他太软了。}
#{166}{}{Well, I guess there's no danger if those slaves' collars are gone.}
{166}{}{好吧，我想如果那些奴隶的项圈不见了就没有危险了。}
#{167}{}{Those slaves shouldn't be a problem anymore, but who knows?}
{167}{}{那些奴隶应该不再是问题了，但谁知道呢？}
#{168}{}{}
{168}{}{}
#{169}{}{}
{169}{}{}
#{170}{}{Damn! William was really counting on that caravan... }
{170}{}{该死！威廉真的指望着那辆大篷车...}
#{171}{}{It's too bad that caravan deal fell through.}
{171}{}{商队交易失败了真是太可惜了。}
#{172}{}{I was hoping to buy something new from those caravans, too... }
{172}{}{我也想从那些大篷车里买点新东西...}
#{173}{}{I guess we won't be getting mail from Reno any time soon.}
{173}{}{我想我们很快就不会收到雷诺的邮件了。}
#{174}{}{Whoever saved that caravan must be one bad mother.}
{174}{}{救了那辆大篷车的人一定是个坏母亲。}
#{175}{}{Finally, things are looking up!}
{175}{}{终于，情况好转了！}
#{176}{}{I'm really getting sick of all these caravans.}
{176}{}{我真的厌倦了这些大篷车。}
#{177}{}{I heard William is waiting on Milo. He's not usually this late.}
{177}{}{我听说威廉在等米洛。他通常不会这么晚。}
#{178}{}{I wouldn't be surprised if Milo just ran away from his wife. Ha!}
{178}{}{如果米洛从他妻子身边跑了我也不会感到惊讶。哈！}
#{179}{}{I haven??t seen Milo for a long time.}
{179}{}{我好久没见到米洛了。}
#{199}{}{You see Dave.}
{199}{}{你看到戴夫了。}
#{200}{}{[He smiles and nods] Welcome! Always happy to see people like you in this shithole.}
{200}{}{[他微笑着点头]欢迎！总是很高兴看到像你这样的人在这鬼地方。}
#{201}{}{[He peers at you suspiciously] New in town? Interesting... Anyway, what do you want from me?}
{201}{}{[他怀疑地看着你]新来的？有趣...不管怎样，你想从我这里得到什么？}
#{202}{}{Are you Dave?}
{202}{}{你是戴夫吗？}
#{203}{}{Nothing.}
{203}{}{没有什么。}
#{204}{}{Ohh, I can't hide it anymore! I am... Dave. Everyone knows that, and now, so do you. Shit, how could it be so hard to hide in such a small settlement?}
{204}{}{哦，我再也藏不住了！我是...戴夫。每个人都知道，现在，你也知道了。妈的，躲在这么小的地方怎么这么难？}
#{205}{}{Quit screwing around. Do you know anything about this pistol?}
{205}{}{别胡闹了。你知道这把手枪吗？}
#{206}{}{Ah, yeah... My trusty partner Smiley would sometimes hunt with it. He was lucky, but not lucky enough to save him from raiders. We divvied up his stuff to sell, and that damned merchant William took the best of it, of course. But he made a mistake.}
{206}{}{啊，是的...我可信赖的搭档斯迈利有时会用它打猎。他很幸运，但幸运的是没有把他从袭击者手中救出来。我们把他的东西分给别人卖，那该死的商人威廉当然是占了上风。但他犯了个错误。}
#{207}{}{Which was?}
{207}{}{哪个是？}
#{208}{}{He forgot that it needs batteries! No one's going to buy a plasma pistol you can't power. Also, it's not as good as it seems. Smiley had to fix it up constantly just to keep it working.}
{208}{}{他忘了它需要电池！没人会买等离子手枪，你不能给它充电。而且，也不像看上去那么好。斯迈利必须不断地把它修好，才能让它继续工作。}
#{209}{}{Do you know how to fix it up?}
{209}{}{你知道怎么修理吗？}
#{210}{}{Hmm... [he rubs his chin] Well, I saw him clean it all the time. I must be the only one - no one even tried to maintain it after Smiley died. I'll be honest, that thing's never going to be a real killer, but with a bit of work you might get more "oomph" out of it.}
{210}{}{Hmm...[他揉着下巴]嗯，我看到他一直在擦。我一定是唯一的一个-在斯迈利死后，甚至没有人试图保持它。老实说，那东西永远不会是真正的杀手，但只要你努力一点，你可能会从中得到更多的“魅力”。}
#{211}{}{That sounds great. Can you do that?}
{211}{}{听起来不错。你能做到吗？}
#{212}{}{Sure... But it's gonna cost you.}
{212}{}{当然...但这会让你付出代价的。}
#{213}{}{What do you want?}
{213}{}{你想要什么？}
#{214}{}{William on my back about gecko skins, but hunting's been lean lately. Get me about, oh, 250 bucks' worth of skins and I'll clean that baby right up.}
{214}{}{威廉在我背后说壁虎皮的事，但最近打猎的事很少。给我拿250块钱的皮，我马上给孩子洗干净。}
#{215}{}{Let's talk about the pistol again.}
{215}{}{我们再谈谈手枪吧。}
#{216}{}{What types of gecko skin does William want?}
{216}{}{威廉想要什么样的壁虎皮？}
#{217}{}{I'll go, then.}
{217}{}{那我就去。}
#{218}{}{Golden gecko skins are more valuable than silver ones, but any will do. I just need to get William off my back.}
{218}{}{金壁虎皮比银壁虎皮值钱，但任何一张都可以。我只想让威廉离开我的背。}
#{219}{}{Here's a silver gecko skin.}
{219}{}{这是一张银色的壁虎皮。}
#{220}{}{Take a golden gecko skin.}
{220}{}{拿一张金色的壁虎皮。}
#{221}{}{Look! I have an acid gecko skin.}
{221}{}{你看！我的壁虎皮很酸。}
#{222}{}{Great! That's enough. Give me the pistol and I'll fix it up right away.}
{222}{}{太好了！够了。把手枪给我，我马上修好。}
#{223}{}{Here you go. It had better be worth it.}
{223}{}{干得好。最好是值得的。}
#{224}{}{Good, but this isn't enough. Bring me more.}
{224}{}{很好，但这还不够。再给我拿点。}
#{225}{}{[Dave carefully disassembles, cleans, and calibrates the weapon. Sometimes he seems not to know what he's doing, but finally, he reassembles the pistol and hands it to you.] Well, what did I tell you? Only I can fix it!}
{225}{}{[戴夫仔细地拆卸、清洁和校准武器。有时他似乎不知道自己在干什么，但最后，他把手枪重新组装好递给你？只有我能修好它！}
#{226}{}{Good work, Dave. Nevada's going to be a lot emptier soon.}
{226}{}{干得好，戴夫。内华达州很快就会空很多。}
#{227}{}{Thanks, Dave. You really helped me out.}
{227}{}{谢谢，戴夫。你真的帮了我。}
#{228}{}{No, this won??t cut it.}
{228}{}{不，这样不行。}
#{229}{}{Don't mention it. It was nothing.}
{229}{}{不用谢。没什么。}
#{235}{}{What now?}
{235}{}{现在怎么办？}
#{236}{}{I'll see you later, when I have the pistol.}
{236}{}{待会儿见，等我有枪了。}
#{237}{}{I'll do it as soon as you bring the pistol.}
{237}{}{你一带枪我就去。}
#{238}{}{I already told you, William's on my ass about gecko skins. Bring me about }
{238}{}{我已经告诉过你了，威廉对壁虎皮很生气。带我来}
#{239}{}{ dollars' worth, and I'll fix up that pistol for you.}
{239}{}{我会帮你修好那把手枪的。}
#{250}{}{You see Bolt.}
{250}{}{你看博尔特。}
#{251}{}{[He peers at you] What?}
{251}{}{[他看着你]什么？}
#{252}{}{Uh, nothing. Nothing at all.}
{252}{}{呃，没什么。什么都没有。}
#{253}{}{Are you Bolt?}
{253}{}{你是博尔特吗？}
#{254}{}{That's what they call me. What do you want?}
{254}{}{他们就是这么叫我的。你想要什么？}
#{255}{}{Why do they call you Bolt?}
{255}{}{他们为什么叫你博尔特？}
#{256}{}{What were you doing on the night the brahmin disappeared?}
{256}{}{双头牛失踪那晚你在干什么？}
#{257}{}{[He smirks] Maybe it's because I have a metal spark in my eyes.}
{257}{}{[他笑了]也许是因为我眼睛里有金属火花。}
#{258}{}{Sleeping, like I should have been. Don't pull any psychological crap on me - I didn't have anything to do with that fucking brahmin. Full stop.}
{258}{}{睡觉，就像我应该睡的那样。别在我身上胡扯-我和那个该死的双头牛一点关系都没有。句号。}
#{259}{}{Bolt, can I see your shotgun shells?}
{259}{}{博尔特，我能看看你的霰弹枪吗？}
#{260}{}{Err, my shotgun shells? Uh, why?}
{260}{}{呃，我的猎枪弹壳？呃，为什么？}
#{261}{}{I want to compare them with the ones left in the stolen brahmin's body.}
{261}{}{我想把它们和被偷走的双头牛身体里留下的那些比较一下。}
#{262}{}{[Looks around furtively and whispers to you] How the fuck... Dammit! I knew I'd get in trouble for this shit!}
{262}{}{[偷偷摸摸地环顾四周，低声对你说]他妈的...该死！我就知道我会有麻烦的！}
#{263}{}{Interesting. What do you have to say in your defense?}
{263}{}{很有趣。你有什么要说的？}
#{264}{}{Fuck it, I won't even try! I'm not that kind of person. You know what kind of person I am? I'm one of the "Molerats" gang, that's what! Well, *was* a Molerat. I'm retired... Or I thought I was, anyway.}
{264}{}{去他妈的，我连试都不试！我不是那种人。你知道我是什么样的人吗？我是“骚扰者”团伙的一员，就是这样！嗯，*是一只*鼹鼠。我退休了...或者我以为我是。}
#{265}{}{Tell about the gang.}
{265}{}{说说那帮人。}
#{266}{}{You left the gang?}
{266}{}{你离开了那帮人？}
#{267}{}{How is this connected to the missing brahmin?}
{267}{}{这和失踪的双头牛有什么关系？}
#{268}{}{What are you going to do now?}
{268}{}{你现在要做什么？}
#{269}{}{I have to decide what to do next.}
{269}{}{我得决定下一步做什么。}
#{270}{}{A bunch of scumbags, that couldn't hack it in Gerlach or Black Rock, but had enough ammo to feed themselves in the mountains. Not very glamorous, but you gotta eat.}
{270}{}{一群人渣，他们不能在格拉赫或黑岩砍，但有足够的弹药在山里养活自己。不是很迷人，但你得吃点东西。}
#{271}{}{Yeah. We controlled this whole valley once, but by the time I left, we were shaking down random travelers for crumbs. I came back here, and until you figured me out, no one knew about my past.}
{271}{}{是 啊。我们曾经控制过整个山谷，但当我离开的时候，我们正在打倒随机的旅行者寻找面包屑。我回到这里，直到你发现我，没有人知道我的过去。}
#{272}{}{The guys hadn't eaten in a while, so they came to me one night. I couldn't say no - they're weaker than they were, but they're sure as hell still tough enough to kill me! I mixed xander root powder into some water and gave it to that kid so he'd fall asleep, then managed to get the planks off the fence to get the brahmin out without making noise.}
{272}{}{他们有一阵子没吃东西了，所以有天晚上他们来找我。我不能说不-他们比以前更虚弱了，但他们仍然非常坚强，足以杀死我！我把仙人掌粉掺进水里，给了那个孩子，好让他睡着，然后设法把木板从篱笆上取下来，把双头牛弄出来，不发出声音。}
#{273}{}{Nothing. If they're gonna toss me out, so be it. I'll go to Big Louie and join up with him. It won't be as good as here, but at least I won't starve to death, like the Molerats. They don't have much time left.}
{273}{}{没有什么。如果他们要把我赶出去，就这样吧。我要去大路易和他会合。不会像这里那么好，但至少我不会像鼹鼠一样饿死。他们剩下的时间不多了。}
#{274}{}{Not much time left? Why not get rid of them right now?}
{274}{}{剩下的时间不多了？为什么不现在就把它们处理掉呢？}
#{275}{}{I know what you're thinking - get a posse together and take those guys out, right? Not a chance, buddy - that only happened in old movies. The gang's well hidden in the mountains, you won't get them that easily. I'll tell you this, though - if William gets that caravan route going, then that'll put some life back into the gang.}
{275}{}{我知道你在想什么-召集一队人把那些人带出去，对吗？一点机会也没有，老兄-那只发生在老电影里。那帮人藏在山里很好，你不会那么容易抓到他们的。不过，我要告诉你-如果威廉让那条商队路线走了，那会让那帮人恢复一些活力。}
#{276}{}{I'm going to tell everyone the truth, unless you can convince me not to.}
{276}{}{我要告诉所有人真相，除非你能说服我不要。}
#{277}{}{Oh, lah-dee-dah! Fuck that. William won't kill me, he'll just cast me out. So I'm breathing freely - see? [he inhales deeply] I smell adventure!}
{277}{}{哦，拉迪达！去他妈的。威廉不会杀我，他只会把我赶出去。所以我可以自由呼吸-看到了吗？[他深深地吸气]我闻到了冒险的味道！}
#{280}{}{I talked to William. He forgives you and says you can stay.}
{280}{}{我和威廉谈过了。他原谅了你，说你可以留下来。}
#{281}{}{William's furious. You have to leave Black Rock.}
{281}{}{威廉很生气。你必须离开黑岩。}
#{282}{}{He forgives me? After what I did? I... Hmm. I didn't expect that. But if that's what he says... Look, thanks. You did a good thing for me, better than I deserve.}
{282}{}{他原谅我了？在我做了什么之后？一、 ...嗯。我没想到。但如果他是这么说的...听着，谢谢。你为我做了一件好事，比我应得的要好。}
#{283}{}{Yeah, I won't say I don't deserve it. I'll pack up and go. I tried to go straight, but I couldn't - and that's fine. Tell William that, whether I'm here or not, the gang will be back. He'd better be ready.}
{283}{}{是的，我不会说我不配。我收拾行李走。我试着直走，但我做不到-那很好。告诉威廉，不管我在不在，那帮人都会回来的。他最好准备好。}
#{284}{}{Enjoy your life here.}
{284}{}{祝你在这里生活愉快。}
#{285}{}{Just shut up and go.}
{285}{}{闭嘴，走吧。}
#{286}{}{I have to do what I can to fix this.}
{286}{}{我必须尽我所能来解决这个问题。}
#{287}{}{You won't see me around here again.}
{287}{}{你不会再看到我了。}
#{1101}{}{You see one of Black Rock's citizens.}
{1101}{}{你看到黑岩的一个市民。}
#{1275}{}{I know what you're thinking - get a posse together and take those guys out, right? Not a chance, girl - that only happened in old movies. The gang's well hidden in the mountains, you won't get them that easily. I'll tell you this, though - if William gets that caravan route going, then that'll put some life back into the gang.}
{1275}{}{我知道你在想什么-召集一队人把那些人带出去，对吗？一点机会也没有，女孩-那只发生在老电影里。那帮人藏在山里很好，你不会那么容易抓到他们的。不过，我要告诉你-如果威廉让那条商队路线走了，那会让那帮人恢复一些活力。}
#{1280}{}{I talked to William. He forgives you and says you can stay.}
{1280}{}{我和威廉谈过了。他原谅了你，说你可以留下来。}
