#{100}{}{You encounter rogues and wolves.}
{100}{}{你会遇到盗贼和狼。}
#{101}{}{You encounter rogues.}
{101}{}{你会遇到流氓。}
#{102}{}{You encounter wolves.}
{102}{}{你会遇到狼。}
#{103}{}{You encounter scorpions.}
{103}{}{你会遇到蝎子。}
#{104}{}{You encounter spore plants.}
{104}{}{你会遇到孢子植物。}
#{105}{}{You encounter a Unity Patrol fighting rogues.}
{105}{}{你遇到了一个与流氓战斗的联合巡逻队。}
#{106}{}{You encounter a Unity Patrol fighting wolves.}
{106}{}{你遇到了一个与狼战斗的联合巡逻队。}
#{107}{}{You encounter a Unity Patrol.}
{107}{}{你遇到了一个联合巡逻队。}
#{150}{}{You encounter slavers and dogs.}
{150}{}{你会遇到奴隶主和狗。}
#{151}{}{You encounter slavers.}
{151}{}{你遇到奴隶贩子。}
#{152}{}{You encounter golden geckos.}
{152}{}{你会遇到金壁虎。}
#{153}{}{You encounter wild dogs.}
{153}{}{你会遇到野狗。}
#{154}{}{You encounter a patrol and dogs fighting slavers.}
{154}{}{你遇到一个巡逻队和狗打奴隶。}
#{155}{}{You encounter slavers fighting golden geckos.}
{155}{}{你会遇到奴隶主和金壁虎战斗。}
#{156}{}{You encounter a patrol fighting slavers.}
{156}{}{你遇到了一个和奴隶贩子战斗的巡逻队。}
#{157}{}{You encounter a patrol fighting golden geckos.}
{157}{}{你遇到一个巡逻队在和金壁虎战斗。}
#{158}{}{You encounter a patrol fighting wild dogs.}
{158}{}{你遇到一个巡逻队在和野狗搏斗。}
#{159}{}{You encounter a patrol.}
{159}{}{你遇到一个巡逻队。}
#{200}{}{You are ambushed by raiders.}
{200}{}{你被袭击者伏击了。}
#{201}{}{You encounter wolves.}
{201}{}{你会遇到狼。}
#{202}{}{You encounter a caravan fending off raiders.}
{202}{}{你遇到了一辆大篷车，挡住了袭击者。}
#{203}{}{You encounter a caravan fending off raiders.}
{203}{}{你遇到了一辆大篷车，挡住了袭击者。}
#{204}{}{You encounter a caravan fending off raiders}
{204}{}{你遇到一辆大篷车挡住了袭击者}
#{205}{}{You encounter a caravan fending off raiders.}
{205}{}{你遇到了一辆大篷车，挡住了袭击者。}
#{206}{}{You encounter a caravan.}
{206}{}{你遇到一辆大篷车。}
#{207}{}{You encounter a caravan.}
{207}{}{你遇到一辆大篷车。}
#{208}{}{You encounter a caravan.}
{208}{}{你遇到一辆大篷车。}
#{209}{}{You encounter a caravan.}
{209}{}{你遇到一辆大篷车。}
#{250}{}{You encounter marauders.}
{250}{}{你遇到掠夺者。}
#{251}{}{You encounter wolves.}
{251}{}{你会遇到狼。}
#{252}{}{You encounter scorpions.}
{252}{}{你会遇到蝎子。}
#{253}{}{You encounter a caravan fending off marauders.}
{253}{}{你遇到了一辆大篷车，挡住了掠夺者。}
#{254}{}{You encounter a caravan fending off marauders.}
{254}{}{你遇到了一辆大篷车，挡住了掠夺者。}
#{255}{}{You encounter a caravan fending off wolves.}
{255}{}{你遇到了一个大篷车挡着狼。}
#{256}{}{You encounter a caravan fending off scorpions.}
{256}{}{你遇到了一辆用来抵御蝎子的大篷车。}
#{257}{}{You encounter a caravan.}
{257}{}{你遇到一辆大篷车。}
#{258}{}{You encounter a caravan.}
{258}{}{你遇到一辆大篷车。}
#{259}{}{You encounter a caravan.}
{259}{}{你遇到一辆大篷车。}
#{260}{}{You encounter a caravan.}
{260}{}{你遇到一辆大篷车。}
#{261}{}{You encounter a traveler.}
{261}{}{你遇到一个旅行者。}
#{300}{}{You encounter remnants of the Master's army.}
{300}{}{你遇到了大师军队的残余。}
#{301}{}{You encounter marauders.}
{301}{}{你遇到掠夺者。}
#{302}{}{You encounter NCR Rangers battling remnants of the Master's army.}
{302}{}{你会遇到NCR护林员在和主人军队的残余作战。}
#{303}{}{You encounter NCR Rangers fighting marauders.}
{303}{}{你会遇到NCR流浪者和掠夺者战斗。}
#{304}{}{You encounter farmers fending off remnants of the Master's army.}
{304}{}{你会遇到农民们在抵挡主人军队的残余。}
#{305}{}{You encounter farmers fending off marauders.}
{305}{}{你会遇到农民抵御掠夺者。}
#{306}{}{You encounter NCR Rangers.}
{306}{}{你遇到了NCR护林员。}
#{307}{}{You encounter farmers.}
{307}{}{你会遇到农民。}
#{350}{}{You encounter a slaver caravan.}
{350}{}{你遇到一个奴隶商队。}
#{351}{}{You encounter highwaymen and robbers.}
{351}{}{你会遇到强盗和强盗。}
#{352}{}{You encounter highwaymen.}
{352}{}{你遇到了强盗。}
#{353}{}{You encounter robbers.}
{353}{}{你遇到强盗。}
#{354}{}{You encounter a caravan fending off highwaymen.}
{354}{}{你遇到一辆大篷车挡住了公路上的人。}
#{355}{}{You encounter a caravan fighting robbers.}
{355}{}{你遇到一个商队在和强盗搏斗。}
#{356}{}{You encounter a caravan fighting highwaymen.}
{356}{}{你遇到了一个商队在和强盗搏斗。}
#{357}{}{You encounter a caravan besieged by robbers.}
{357}{}{你遇到一个被强盗包围的商队。}
#{358}{}{You encounter a slave caravan fighting a caravan.}
{358}{}{你遇到一个奴隶商队和一个商队战斗。}
#{359}{}{You encounter highwaymen fighting robbers.}
{359}{}{你会遇到强盗和强盗搏斗。}
#{360}{}{You encounter a caravan.}
{360}{}{你遇到一辆大篷车。}
#{361}{}{You encounter a caravan.}
{361}{}{你遇到一辆大篷车。}
#{400}{}{You encounter highwaymen.}
{400}{}{你遇到了强盗。}
#{401}{}{You encounter robbers.}
{401}{}{你遇到强盗。}
#{402}{}{You encounter robbers and highwaymen.}
{402}{}{你会遇到强盗和强盗。}
#{403}{}{You encounter golden geckos and scorpions.}
{403}{}{你会遇到金壁虎和蝎子。}
#{404}{}{You encounter golden geckos.}
{404}{}{你会遇到金壁虎。}
#{405}{}{You encounter mole rats and pig rats.}
{405}{}{你会遇到鼹鼠和猪鼠。}
#{406}{}{You encounter scorpions.}
{406}{}{你会遇到蝎子。}
#{407}{}{You encounter spore plants.}
{407}{}{你会遇到孢子植物。}
#{408}{}{You encounter robbers fighting highwaymen.}
{408}{}{你遇到强盗和强盗搏斗。}
#{409}{}{You encounter a caravan fending off highwaymen.}
{409}{}{你遇到一辆大篷车挡住了公路上的人。}
#{410}{}{You encounter a caravan fending off robbers.}
{410}{}{你遇到了一辆大篷车挡开了强盗。}
#{411}{}{You encounter a caravan fending off scorpions.}
{411}{}{你遇到了一辆用来抵御蝎子的大篷车。}
#{412}{}{You encounter geckos fighting scorpions.}
{412}{}{你会遇到壁虎和蝎子搏斗。}
#{413}{}{You encounter a caravan.}
{413}{}{你遇到一辆大篷车。}
#{450}{}{You encounter highwaymen and robbers.}
{450}{}{你会遇到强盗和强盗。}
#{451}{}{You encounter highwaymen and geckos.}
{451}{}{你会遇到强盗和壁虎。}
#{452}{}{You encounter golden geckos.}
{452}{}{你会遇到金壁虎。}
#{453}{}{You encounter scorpions and spore plants.}
{453}{}{你会遇到蝎子和孢子植物。}
#{454}{}{You encounter robbers fighting scorpions.}
{454}{}{你会遇到强盗和蝎子搏斗。}
#{455}{}{You encounter scorpions fighting robbers.}
{455}{}{你会遇到蝎子和强盗搏斗。}
#{456}{}{You encounter a caravan fending off highwaymen.}
{456}{}{你遇到一辆大篷车挡住了公路上的人。}
#{457}{}{You encounter a caravan fending off robbers.}
{457}{}{你遇到了一辆大篷车挡开了强盗。}
#{458}{}{You encounter some highwaymen weeding out some spore plants.}
{458}{}{你遇到一些强盗在清除一些孢子植物。}
#{459}{}{You encounter a caravan.}
{459}{}{你遇到一辆大篷车。}
#{500}{}{You encounter highwaymen and wild dogs.}
{500}{}{你会遇到强盗和野狗。}
#{501}{}{You encounter robbers and wild dogs.}
{501}{}{你会遇到强盗和野狗。}
#{502}{}{You encounter robbers.}
{502}{}{你遇到强盗。}
#{503}{}{You encounter highwaymen.}
{503}{}{你遇到了强盗。}
#{504}{}{You encounter a swarm of mantis and some spore plants.}
{504}{}{你会遇到一群螳螂和一些孢子植物。}
#{505}{}{You encounter dogs and spore plants.}
{505}{}{你会遇到狗和孢子植物。}
#{506}{}{You encounter a swarm of mantis.}
{506}{}{你遇到一群螳螂。}
#{507}{}{You encounter wild dogs.}
{507}{}{你会遇到野狗。}
#{508}{}{You encounter robbers fighting dogs.}
{508}{}{你遇到强盗和狗搏斗。}
#{509}{}{You encounter a caravan fending off dogs.}
{509}{}{你会遇到一辆大篷车挡着狗。}
#{510}{}{You encounter a caravan fending off robbers.}
{510}{}{你遇到了一辆大篷车挡开了强盗。}
#{511}{}{You encounter a caravan fending off highwaymen.}
{511}{}{你遇到一辆大篷车挡住了公路上的人。}
#{512}{}{You encounter a caravan.}
{512}{}{你遇到一辆大篷车。}
#{550}{}{You encounter geckos and wolves.}
{550}{}{你会遇到壁虎和狼。}
#{551}{}{You encounter claim jumpers.}
{551}{}{你遇到了索赔跳跃者。}
#{552}{}{You encounter wolves.}
{552}{}{你会遇到狼。}
#{553}{}{You encounter golden geckos.}
{553}{}{你会遇到金壁虎。}
#{554}{}{You encounter prospectors fending off claim jumpers.}
{554}{}{你会遇到探矿者挡开索赔者。}
#{555}{}{You encounter trappers hunting geckos.}
{555}{}{你会遇到捕猎壁虎的捕猎者。}
#{556}{}{You encounter bootleggers fighting wolves.}
{556}{}{你会遇到与狼搏斗的走私犯。}
#{557}{}{You encounter homesteaders fighting claim jumpers}
{557}{}{你会遇到宅基地居民和索赔跳跃者打架}
#{558}{}{You encounter homesteaders fighting wolves.}
{558}{}{你遇到了与狼搏斗的农夫。}
#{559}{}{You encounter bootleggers.}
{559}{}{你遇到了走私犯。}
#{560}{}{You encounter trappers.}
{560}{}{你会遇到陷阱。}
#{561}{}{You encounter prospectors.}
{561}{}{你会遇到探矿者。}
#{600}{}{You encounter deathclaws.}
{600}{}{你会遇到死亡之爪。}
#{601}{}{You encounter fire geckos.}
{601}{}{你会遇到火壁虎。}
#{602}{}{You encounter a caravan fleeing from deathclaws.}
{602}{}{你遇到了一个从死亡之爪逃跑的商队。}
#{603}{}{You encounter a caravan fighting deathclaws.}
{603}{}{你遇到一个商队在与死亡之爪搏斗。}
#{604}{}{You encounter a caravan fighting fire geckos.}
{604}{}{你遇到一个商队在灭火壁虎。}
#{605}{}{You encounter a caravan fighting fire geckos.}
{605}{}{你遇到一个商队在灭火壁虎。}
#{606}{}{You encounter a caravan.}
{606}{}{你遇到一辆大篷车。}
#{607}{}{You encounter a caravan.}
{607}{}{你遇到一辆大篷车。}
#{608}{}{You encounter a caravan.}
{608}{}{你遇到一辆大篷车。}
#{609}{}{You encounter a caravan.}
{609}{}{你遇到一辆大篷车。}
#{650}{}{You encounter aliens and deathclaws.}
{650}{}{你会遇到外星人和死爪。}
#{651}{}{You encounter centaurs and floaters.}
{651}{}{你会遇到半人马和漂浮者。}
#{652}{}{You encounter fire geckos.}
{652}{}{你会遇到火壁虎。}
#{653}{}{You encounter aliens.}
{653}{}{你会遇到外星人。}
#{654}{}{You encounter deathclaws.}
{654}{}{你会遇到死亡之爪。}
#{655}{}{You encounter fire geckos.}
{655}{}{你会遇到火壁虎。}
#{656}{}{You encounter aliens.}
{656}{}{你会遇到外星人。}
#{657}{}{You encounter centaurs.}
{657}{}{你会遇到半人马。}
#{658}{}{You encounter floaters.}
{658}{}{你会遇到漂浮物。}
#{700}{}{You encounter some Yakuza.}
{700}{}{你遇到了黑帮。}
#{701}{}{You encounter a gang.}
{701}{}{你遇到一帮人。}
#{702}{}{You encounter some wolves.}
{702}{}{你遇到一些狼。}
#{703}{}{You encounter some mobsters fighting some Yakuza.}
{703}{}{你会遇到一些黑帮分子和黑帮搏斗。}
#{704}{}{You encounter some mobsters fighting a gang.}
{704}{}{你会遇到一些黑帮分子和帮派斗争。}
#{705}{}{You encounter some mobsters.}
{705}{}{你遇到了一些暴徒。}
#{706}{}{You encounter a traveler.}
{706}{}{你遇到一个旅行者。}
#{750}{}{You encounter a caravan fending off remnants of the Master's army.}
{750}{}{你遇到了一辆大篷车，挡住了主人军队的残余。}
#{751}{}{You encounter a caravan fighting remnants of the master's army.}
{751}{}{你遇到了一个商队在与主人军队的残余战斗。}
#{752}{}{You encounter a caravan fighting deathclaws.}
{752}{}{你遇到一个商队在与死亡之爪搏斗。}
#{753}{}{You encounter a caravan.}
{753}{}{你遇到一辆大篷车。}
#{754}{}{You encounter a caravan.}
{754}{}{你遇到一辆大篷车。}
#{755}{}{You encounter a caravan.}
{755}{}{你遇到一辆大篷车。}
