#{100}{}{You see a client.}
{100}{}{你看到一个客户。}
#{101}{}{You see Madison.}
{101}{}{你看麦迪逊。}
#{105}{}{Ave, goddess!}
{105}{}{阿芙，女神！}
#{106}{}{You come with me, asshole.}
{106}{}{你跟我来，混蛋。}
#{107}{}{Stay here, moron.}
{107}{}{呆在这儿，白痴。}
#{110}{}{Oh! My baby came back for me! I knew it, that you need me! Where shall we go this time? Maybe, to my home?}
{110}{}{哦！我的孩子回来找我了！我知道，你需要我！这次我们去哪儿？也许，去我家？}
#{111}{}{Come on, I need you.}
{111}{}{来吧，我需要你。}
#{112}{}{Never mind.}
{112}{}{不要介意。}
#{120}{}{What do you want, baby?}
{120}{}{你想要什么，宝贝？}
#{121}{}{Anything you want, beautiful!}
{121}{}{你想要什么都行，美女！}
#{122}{}{Well, what an old fart can do for a such a little girl like you?}
{122}{}{好吧，一个老屁能为你这样的小女孩做什么？}
#{123}{}{Hey, you know who to call when you need to! Yes, I'm your man.}
{123}{}{嘿，你知道需要的时候给谁打电话！是的，我是你的人。}
#{124}{}{I can't wait, when you're going to say it.}
{124}{}{我等不及了，你什么时候说。}
#{125}{}{Come on! Make up your mind! Tell me you want *that*?}
{125}{}{加油！下定决心！告诉我你想要那个？}
#{126}{}{Oh, I'm sorry for the stains on the pants... Will try harder to conceal them.}
{126}{}{噢，我很抱歉裤子上有污渍。。。会更努力地隐藏他们。}
#{127}{}{What? Want it harder?}
{127}{}{什么？想要更难一点吗？}
#{128}{}{[Looks at you and pulls his hands out of his pockets] Oh, uh... It all right. Honestly.}
{128}{}{[看着你，把手从口袋里掏出来]哦，呃。。。一切正常。说真的？}
#{129}{}{[Hums something about last kiss] ...Oh, sorry, got distracted again.}
{129}{}{[哼着最后一吻]…哦，抱歉，又分心了。}
#{130}{}{Let's chat.}
{130}{}{我们聊聊吧。}
#{131}{}{Let's change the distance between us.}
{131}{}{让我们改变我们之间的距离。}
#{132}{}{Hide you weapon away.}
{132}{}{把你的武器藏起来。}
#{133}{}{Take off your armor.}
{133}{}{脱下你的盔甲。}
#{134}{}{Stay here and wait for me.}
{134}{}{呆在这儿等我。}
#{135}{}{Tell me about your weapon skills.}
{135}{}{告诉我你的武器技能。}
#{136}{}{}
{136}{}{}
#{137}{}{}
{137}{}{}
#{138}{}{Anything you wish, baby!}
{138}{}{任何你想要的，宝贝！}
#{139}{}{Great.}
{139}{}{伟大的。}
#{140}{}{Oh, my baby wants to be closer! I've been waiting for this...}
{140}{}{哦，我的宝贝想靠近点！我一直在等这个。。。}
#{141}{}{Stay away from me as far as possible, maniac.}
{141}{}{离我远点，疯子。}
#{142}{}{Stay at a medium distance.}
{142}{}{保持中等距离。}
#{143}{}{Stay close, honey.}
{143}{}{靠近点，亲爱的。}
#{144}{}{I think this distance is enough.}
{144}{}{我觉得这个距离够了。}
#{145}{}{Ah! Okay, okay... I will stay away. But will see who will last longer!}
{145}{}{啊！好吧，好吧。。。我会离开的。但我要看看谁能撑得更久！}
#{146}{}{Not a good start for our relationship, baby. Believe me, I know it.}
{146}{}{对我们的关系来说不是一个好的开始，宝贝。相信我，我知道。}
#{147}{}{Ow! Baby, you're driving me crazy! I'll be a human shield for your firm butt!}
{147}{}{噢！宝贝，你快把我逼疯了！我会成为你坚强屁股的人盾！}
#{148}{}{Oh! Baby, I can even dance striptease! Just say a word!}
{148}{}{哦！宝贝，我甚至可以跳脱衣舞！说一句话！}
#{149}{}{Uh... Not today, Playboy. The armor is enough.}
{149}{}{休斯敦大学。。。今天不行，花花公子。盔甲够了。}
#{150}{}{Oh, no! [grabs his head] Has this day has come!? }
{150}{}{哦，不！[抓住他的头]这一天到了吗！？}
#{151}{}{Yes, you dog, I dump you. Forever.}
{151}{}{是的，你这条狗，我甩了你。永远。}
#{152}{}{Calm down, just wait for me, I'll be right back.}
{152}{}{冷静点，等我，我马上回来。}
#{153}{}{Well, okay, you can stay. I'll tolerate your arrogant mug some more.}
{153}{}{好吧，你可以留下来。我再容忍你的傲慢。}
#{154}{}{Phew! [defiantly grabs his heart] Oh! How my heart is relieved!}
{154}{}{呸！[挑衅地抓住他的心]哦！我的心真是松了一口气！}
#{155}{}{Oh, well, well.}
{155}{}{哦，好吧，好吧。}
#{156}{}{Okay! Well!!! The old dog will have to wait... As always. Uh... But you're coming back are you? You won't leave this faithful servant here right?}
{156}{}{可以！好！！！那只老狗得等。。。一如既往。休斯敦大学。。。但你会回来的，是吗？你不会把这个忠实的仆人留在这里吧？}
#{157}{}{You just wait.}
{157}{}{你就等着吧。}
#{158}{}{NO! NOOO!!! How could I! How could I leave my pussycat without attention and care! I'll be punished! I'm going to hell! But just give me one more chance! Please! I'm all yours!}
{158}{}{不！不！！！我怎么能！我怎么能离开我的猫没有注意和照顾！我会受到惩罚的！我要下地狱了！但再给我一次机会！拜托！我是你的！}
#{159}{}{Just wait, you moron. I'll be back.}
{159}{}{等等，你这个白痴。我会回来的。}
#{160}{}{Yes! YES, dear, I don't need you. Go away and don't come back!}
{160}{}{对！是的，亲爱的，我不需要你。走开，别回来！}
#{161}{}{Oh, those words cut me to pieces! What a pain! Mmm... WHAT a PAIN!!! [squeals] I can't STAND it! I'll kill myself!}
{161}{}{哦，那些话把我撕成碎片！多痛苦啊！嗯。。。多痛苦啊！！！我受不了了！我要自杀！}
#{162}{}{What do I care...}
{162}{}{我在乎什么。。。}
#{163}{}{[Breathing heavily, grabs his chest] What an idiot I am! Well, I'll wait... I hope that you come back... I believe it will happen! Believe me, I'll be good! Honestly!}
{163}{}{[呼吸沉重，抓住他的胸部]我真是个白痴！好吧，我等着。。。我希望你回来。。。我相信会发生的！相信我，我会很好的！说真的？}
#{164}{}{Wait, as long as you want to.}
{164}{}{等等，只要你愿意。}
#{165}{}{For you would master anything. But except the shotgun and a revolver never had to use anything else.}
{165}{}{因为你会掌握一切。但除了猎枪和左轮手枪，再也不用用别的东西了。}
#{166}{}{Ok.}
{166}{}{好 啊。}
#{200}{}{Again? Don't you want to go straight to the fun?}
{200}{}{再一次？你不想直接去玩吗？}
#{201}{}{I saw in a store those rubber things... If you that is what you mean.}
{201}{}{我在商店里看到那些橡胶制品。。。如果你知道，那就是你的意思。}
#{202}{}{Oh, yeah, let's see, where to settle down...}
{202}{}{哦，是的，让我想想，在哪里定居。。。}
#{203}{}{I suggest in position 26.}
{203}{}{我建议在26号位置。}
#{204}{}{Oh, itching, right? [smiling]}
{204}{}{哦，痒，对吧？[微笑]}
#{205}{}{Well, of course! Mature a little, right?}
{205}{}{好吧，当然！成熟一点，对吧？}
#{206}{}{I feel the most desired thing is coming!}
{206}{}{我觉得最渴望的东西来了！}
#{207}{}{I've waited so long! Tell me, how shall we do it?}
{207}{}{我等了这么久！告诉我，我们该怎么做？}
#{208}{}{How you prefer - with a beer or on an empty stomach?}
{208}{}{你喜欢喝啤酒还是空腹？}
#{209}{}{I'm not talking about that, you fool, don't get excited ahead of time.}
{209}{}{我不是在说这个，你这个傻瓜，别提前激动。}
#{210}{}{Damn, as always...}
{210}{}{该死，一如既往。。。}
#{211}{}{What do you know about this place?}
{211}{}{你对这个地方了解多少？}
#{212}{}{Look at my backpack, see something familiar?}
{212}{}{看看我的背包，看到熟悉的东西了吗？}
#{213}{}{Who can make poison in Reno?}
{213}{}{谁能在里诺制造毒药？}
#{214}{}{Do you know who is Oliver?}
{214}{}{你知道谁是奥利弗吗？}
#{215}{}{}
{215}{}{}
#{216}{}{}
{216}{}{}
#{217}{}{}
{217}{}{}
#{218}{}{}
{218}{}{}
#{219}{}{Okay, enough talking.}
{219}{}{好了，说够了。}
#{220}{}{Another question.}
{220}{}{另一个问题。}
#{221}{}{This is enough for today.}
{221}{}{今天就够了。}
#{230}{}{Oh, you're really dangerous, baby! I don't envy the one that you decided to kill. OK, I know where to do it. Striker, he lives in bowling stadium. Local gangster and manufacturer of drugs. Recommend.}
{230}{}{哦，你真危险，宝贝！我不羡慕你决定杀的那个人。好的，我知道在哪里做。前锋，他住在保龄球馆。当地黑帮和毒品制造商。推荐。}
#{231}{}{What else?}
{231}{}{还有什么？}
#{300}{}{Wasteland. Just a Wasteland.}
{300}{}{荒地。只是一片荒地。}
#{301}{}{Wasteland. Just a Wasteland.}
{301}{}{荒地。只是一片荒地。}
#{302}{}{Wasteland. Just a Wasteland.}
{302}{}{荒地。只是一片荒地。}
#{303}{}{Huh? And where am I? Oh, sorry, I was did too many pills and now I hallucinated about some beautiful city... Oh what a beautiful hallucination!}
{303}{}{呵呵？我在哪里？哦，对不起，我吃了太多药，现在我对某个美丽的城市产生了幻觉。。。哦，多美的幻觉啊！}
#{304}{}{Huh? And where am I? Oh, sorry, I was did too many pills and now I hallucinated about some beautiful city... Oh what a beautiful hallucination!}
{304}{}{呵呵？我在哪里？哦，对不起，我吃了太多药，现在我对某个美丽的城市产生了幻觉。。。哦，多美的幻觉啊！}
#{305}{}{Desert and the railroad. What else you want to know my curious one? Oh, there's a hut of some sort, certainly it has a bed...}
{305}{}{沙漠和铁路。你还想知道什么？哦，有个小屋，当然有床。。。}
#{306}{}{Never been here before, but heard about it. They say that the local military have not seen a female body in a long... Oops, I shouldn't have said.}
{306}{}{以前从没来过，但听说过。他们说当地军队很久没有看到一具女尸了。。。哎呀，我不该说的。}
#{307}{}{Some dirty bunker. Yes, I am a lover of exotic places to receive oral pleasure in, but not in such a dirty place.}
{307}{}{一些肮脏的掩体。是的，我是一个喜欢异国情调的地方接受口头上的乐趣，但不是在这样一个肮脏的地方。}
#{308}{}{Ruins, ruins, ruins everywhere. Hey, looks like we're not alone!}
{308}{}{废墟，废墟，到处都是废墟。嘿，看来我们不是一个人！}
#{309}{}{MAP_KLAMATH_1}
{309}{}{克拉马斯地图1}
#{310}{}{MAP_KLAMATH_MALL}
{310}{}{克拉马斯购物中心地图}
#{311}{}{MAP_KLAMATH_RATCAVES}
{311}{}{克拉马斯洞穴地图}
#{312}{}{Baby, it's a perfect place for lovers of brahmin ass. But I prefer the other kind of asses.}
{312}{}{宝贝，这是婆罗门驴子爱好者的完美去处。但我更喜欢其他类型的驴子。}
#{313}{}{MAP_KLAMATH_TRAPCAVES}
{313}{}{地图\u KLAMATH \u TRAPCAVES}
#{314}{}{MAP_KLAMATH_GRAZE}
{314}{}{地图\u KLAMATH \u GRAZE}
#{315}{}{MAP_VAULTCITY_COURTYARD}
{315}{}{城市庭院地图}
#{316}{}{MAP_VAULTCITY_DOWNTOWN}
{316}{}{市区地图}
#{317}{}{MAP_VAULTCITY_COUNCIL}
{317}{}{市议会地图}
#{318}{}{Savages? The baby wants exotics? Ah, I can relate - pure nature and no drugs, I guess they do *it* long and voluptuous.}
{318}{}{野蛮人？宝宝想要异国药？啊，我能理解-纯粹的自然和没有毒品，我猜他们会这么做的，长时间的，性感的。}
#{319}{}{[Looks around] I remember, just like in the good old days, before I broke in New Reno. Let's move - local rough stuff even for such a dangerous girl will be hard to survive through, believe me.}
{319}{}{[环顾四周]我记得，就像过去的好日子一样，在我闯进新里诺之前。让我们走吧-当地的粗野的东西，即使是这样一个危险的女孩将很难生存通过，相信我。}
#{320}{}{MAP_SHAIEM_RAIDERS_BASA}
{320}{}{地图\u SHAIEM \u RAIDERS \u BASA}
#{321}{}{Dark, damp, quiet, cool... A great place to dance on the mattress.}
{321}{}{黑暗，潮湿，安静，凉爽。。。在床垫上跳舞的好地方。}
#{322}{}{MAP_MODOC_DOWNTHESHITTER}
{322}{}{地图\u MODOC \u down the shitter}
#{323}{}{MAP_HOWTHORNE_POLIGON}
{323}{}{地图\u HOWTHORNE\u POLIGON}
#{324}{}{MAP_BATTL_OWL}
{324}{}{地图\u BATTL\u OWL}
#{325}{}{MAP_BATTL_BAIKERS}
{325}{}{巴特尔拜克斯地图}
#{326}{}{MAP_GHOST_LAKE}
{326}{}{幽灵湖地图}
#{327}{}{MAP_ZONA51_Toplivo}
{327}{}{地图｜区域51｜托普利沃}
#{328}{}{MAP_ZONA51_KASARMS}
{328}{}{区域地图}
#{329}{}{MAP_ZONA51_ANGAR}
{329}{}{地图51}
#{330}{}{MAP_VAULT_8_DESTROYVAULT}
{330}{}{地图\保险库\ 8\保险库}
#{331}{}{MAP_GECKO_SETTLEMENT}
{331}{}{壁虎营地地图}
#{332}{}{MAP_GECKO_POWER_PLANT}
{332}{}{壁虎发电厂地图}
#{333}{}{MAP_GECKO_JUNKYARD}
{333}{}{地图\壁虎\垃圾场}
#{334}{}{MAP_GECKO_ACCESS_TUNNELS}
{334}{}{地图\壁虎\通道\隧道}
#{335}{}{MAP_VAULT_8_CITY_DESTROY}
{335}{}{地图\u保险库\u 8 \u城市\u破坏}
#{336}{}{MAP_VAULT_15}
{336}{}{地图\保险库\ 15}
#{337}{}{MAP_THE_SQUAT_A}
{337}{}{绘制下蹲地图}
#{338}{}{MAP_THE_SQUAT_B}
{338}{}{绘制下蹲地图}
#{339}{}{MAP_VAULT_15_EAST_ENTRANCE}
{339}{}{地图\保险库\ 15 \东\入口}
#{340}{}{MAP_VAULT_13}
{340}{}{地图\保险库\ 13}
#{341}{}{MAP_VAULT_13_ENTRANCE}
{341}{}{地图\保险库\ 13\入口}
#{342}{}{MAP_VEGAS_STRIP}
{342}{}{拉斯维加斯大道地图}
#{343}{}{MAP_VEGAS_HARD_ROCK}
{343}{}{地图\u拉斯维加斯\u硬岩\u}
#{344}{}{MAP_VEGAS_SLAVERTOWN}
{344}{}{拉斯维加斯地图}
#{345}{}{MAP_VEGAS_GHOULTOWN}
{345}{}{拉斯维加斯和食尸鬼镇地图}
#{346}{}{MAP_VEGAS_SIGN}
{346}{}{拉斯维加斯地图标志}
#{347}{}{MAP_VEGAS_DAMBA}
{347}{}{拉斯维加斯和丹巴地图}
#{348}{}{MAP_KLAMATH_CANYON}
{348}{}{克拉马斯峡谷地图}
#{349}{}{MAP_HOWTHORNE_DEPOTS}
{349}{}{HOWTHORNE仓库地图}
#{350}{}{MAP_HOWTHORNE_TRAIN_DEPO}
{350}{}{火车站地图}
#{351}{}{I don't know what we're doing here, but I would prefer to do it in the hotel "Silver" in the sixth room.}
{351}{}{我不知道我们在这里做什么，但我更喜欢在第六个房间的“西尔弗”旅馆里做。}
#{352}{}{MAP_DEN_SLAVE_RUN}
{352}{}{地图\u DEN \u SLAVE \u RUN}
#{353}{}{MAP_CAR_DESERT}
{353}{}{地图\汽车\沙漠}
#{354}{}{MAP_RENO_SILVER}
{354}{}{里诺银地图}
#{355}{}{MAP_RENO_ELDORADO}
{355}{}{里诺埃尔多拉多地图}
#{356}{}{MAP_RENO_BILLRD}
{356}{}{雷诺比勒德地图}
#{357}{}{MAP_RENO_TRAINDEPO}
{357}{}{雷诺火车站地图}
#{358}{}{MAP_RENO_OLIVER}
{358}{}{里诺奥利弗地图}
#{359}{}{MAP_PEPGAZ}
{359}{}{佩普加斯地图}
#{360}{}{MAP_VEGAS_STABLES}
{360}{}{拉斯维加斯马厩地图}
#{361}{}{Oh, baby! Baby! Now I'm not going out of here, even for someone's ass. Hey, dwarf, five bucks for that one from Wendover! Five bucks!!!}
{361}{}{哦，宝贝！宝贝！现在我不想离开这里，哪怕是为了别人的屁股。嘿，侏儒，温多弗的那个五块钱！五块钱！！！}
#{362}{}{MAP_REDDING_WANAMINGO_ENT}
{362}{}{地图\u REDDING \u WANAMINGO\u ENT}
#{363}{}{MAP_REDDING_WANAMINGO_12}
{363}{}{地图\u REDDING \u WANAMINGO \u 12}
#{364}{}{MAP_REDDING_WANAMINGO_12}
{364}{}{地图\u REDDING \u WANAMINGO \u 12}
#{365}{}{MAP_REDDING_MINE_ENT}
{365}{}{雷丁矿地图}
#{366}{}{MAP_REDDING_DTOWN_TUNNEL}
{366}{}{地图\u REDDING \u DTOWN \u TUNNEL}
#{367}{}{MAP_REDDING_MINE_TUNNEL}
{367}{}{雷丁矿隧道图}
#{368}{}{Ruins. Just ruins.}
{368}{}{废墟。只是废墟。}
#{369}{}{Wasteland. Just a Wasteland.}
{369}{}{荒地。只是一片荒地。}
#{370}{}{Wasteland. Just a Wasteland.}
{370}{}{荒地。只是一片荒地。}
#{371}{}{Wasteland. Just a Wasteland.}
{371}{}{荒地。只是一片荒地。}
#{372}{}{Wasteland. Just a Wasteland.}
{372}{}{荒地。只是一片荒地。}
#{373}{}{Wasteland. Just a Wasteland.}
{373}{}{荒地。只是一片荒地。}
#{374}{}{Wasteland. Just a Wasteland.}
{374}{}{荒地。只是一片荒地。}
#{375}{}{Wasteland. Just a Wasteland.}
{375}{}{荒地。只是一片荒地。}
#{376}{}{Wasteland. Just a Wasteland.}
{376}{}{荒地。只是一片荒地。}
#{377}{}{Wasteland. Just a Wasteland.}
{377}{}{荒地。只是一片荒地。}
#{378}{}{MAP_BROKEN_HILLS1}
{378}{}{地图\u破碎的\u山丘1}
#{379}{}{MAP_BROKEN_HILLS2}
{379}{}{地图2}
#{380}{}{Wasteland. Just a Wasteland.}
{380}{}{荒地。只是一片荒地。}
#{381}{}{Wasteland. Just a Wasteland.}
{381}{}{荒地。只是一片荒地。}
#{382}{}{Wasteland. Just a Wasteland.}
{382}{}{荒地。只是一片荒地。}
#{383}{}{Wasteland. Just a Wasteland.}
{383}{}{荒地。只是一片荒地。}
#{384}{}{Wasteland. Just a Wasteland.}
{384}{}{荒地。只是一片荒地。}
#{385}{}{Wasteland. Just a Wasteland.}
{385}{}{荒地。只是一片荒地。}
#{386}{}{Wasteland. Just a Wasteland.}
{386}{}{荒地。只是一片荒地。}
#{387}{}{Wasteland. Just a Wasteland.}
{387}{}{荒地。只是一片荒地。}
#{388}{}{Wasteland. Just a Wasteland.}
{388}{}{荒地。只是一片荒地。}
#{389}{}{Wasteland. Just a Wasteland.}
{389}{}{荒地。只是一片荒地。}
#{390}{}{Wasteland. Just a Wasteland.}
{390}{}{荒地。只是一片荒地。}
#{391}{}{Wasteland. Just a Wasteland.}
{391}{}{荒地。只是一片荒地。}
#{392}{}{MAP_RAIDERS_CAMP1}
{392}{}{地图\突袭者\营地1}
#{393}{}{MAP_RAIDERS_CAMP2}
{393}{}{地图\突袭者\营地2}
#{394}{}{Wasteland. Just a Wasteland.}
{394}{}{荒地。只是一片荒地。}
#{395}{}{Wasteland. Just a Wasteland.}
{395}{}{荒地。只是一片荒地。}
#{396}{}{MAP_SPECIAL_RND_WHALE}
{396}{}{特别地图}
#{397}{}{This opening reminds me of something. I've seen it somewhere before.}
{397}{}{这个开口让我想起了一些事情。我以前在什么地方见过。}
#{398}{}{Watch your feet, baby, I would not want to collect such a beauty as you piece by piece.}
{398}{}{小心你的脚，宝贝，我可不想把你这样的美人一块一块地收藏起来。}
#{399}{}{Wasteland. Just a Wasteland. Somehow highlighted.}
{399}{}{荒地。只是一片荒地。不知怎么突出了。}
#{400}{}{Wasteland. Just a Wasteland. And some beautiful building. Probably there inside of elegant bed and a telephone to order corporate striptease.}
{400}{}{荒地。只是一片荒地。还有一些漂亮的建筑。可能是在优雅的床和电话里面订了公司的脱衣舞。}
#{401}{}{MAP_SPECIAL_RND_BRIDGE}
{401}{}{地图专用桥}
#{402}{}{Oh, this is some sort of cafe?. Want to go in have some fun?}
{402}{}{哦，这是什么咖啡馆？。想进去玩玩吗？}
#{403}{}{MAP_SPECIAL_RND_HOLY1}
{403}{}{地图\u特殊\u RND \u洞1}
#{404}{}{MAP_SPECIAL_RND_HOLY2}
{404}{}{地图2}
#{405}{}{MAP_SPECIAL_RND_GUARDIAN}
{405}{}{地图\u特殊\u RND \u监护人}
#{406}{}{Wasteland. Just A Wasteland.}
{406}{}{荒地。只是一片荒地。}
#{407}{}{MAP_SPECIAL_RND_PARIAH}
{407}{}{地图，特别的，被遗弃的}
#{408}{}{MAP_SPECIAL_RND_MAD_COW}
{408}{}{地图\u特殊\u RND \u疯牛}
#{409}{}{MAP_NAVARRO_ENTRANCE}
{409}{}{纳瓦罗入口地图}
#{410}{}{Wasteland. Just a Wasteland.}
{410}{}{荒地。只是一片荒地。}
#{411}{}{Wasteland. Just a Wasteland.}
{411}{}{荒地。只是一片荒地。}
#{412}{}{Wasteland. Just a Wasteland.}
{412}{}{荒地。只是一片荒地。}
#{413}{}{Wasteland. Just a Wasteland.}
{413}{}{荒地。只是一片荒地。}
#{414}{}{Wasteland. Just a Wasteland.}
{414}{}{荒地。只是一片荒地。}
#{415}{}{Wasteland. Just a Wasteland.}
{415}{}{荒地。只是一片荒地。}
#{416}{}{Wasteland. Just a Wasteland.}
{416}{}{荒地。只是一片荒地。}
#{417}{}{Wasteland. Just a Wasteland.}
{417}{}{荒地。只是一片荒地。}
#{418}{}{Wasteland. Just a Wasteland.}
{418}{}{荒地。只是一片荒地。}
#{419}{}{Wasteland. Just a Wasteland.}
{419}{}{荒地。只是一片荒地。}
#{420}{}{Wasteland. Just a Wasteland.}
{420}{}{荒地。只是一片荒地。}
#{421}{}{Wasteland. Just a Wasteland.}
{421}{}{荒地。只是一片荒地。}
#{422}{}{Wasteland. Just a Wasteland.}
{422}{}{荒地。只是一片荒地。}
#{423}{}{Wasteland. Just a Wasteland.}
{423}{}{荒地。只是一片荒地。}
#{424}{}{Wasteland. Just a Wasteland.}
{424}{}{荒地。只是一片荒地。}
#{425}{}{Ruins. Just ruins.}
{425}{}{废墟。只是废墟。}
#{426}{}{Wasteland. Just A Wasteland.}
{426}{}{荒地。只是一片荒地。}
#{427}{}{Ruins. Just ruins.}
{427}{}{废墟。只是废墟。}
#{428}{}{Gorgeous place. Fresh beds, clean water and a lot of free donuts from the machine. How about stop and relax in the double beds?}
{428}{}{美丽的地方。新鲜的床，干净的水和机器里的很多免费甜甜圈。在双人床上休息一下怎么样？}
#{429}{}{Mountains and cold wind. We have nothing to do here.}
{429}{}{高山和寒风。我们这里没什么事可做。}
#{430}{}{Why is it so dark? How will we find each other... That is, I wanted to say on each other.}
{430}{}{为什么这么黑？我们怎样才能找到彼此。。。也就是说，我想对对方说。}
#{431}{}{Wasteland. Just A Wasteland. Somewhere not far from Salt Lake. I can't wait to get to the soft beds in "the Sixth bullet"...}
{431}{}{荒地。只是一片荒地。离盐湖不远的地方。我迫不及待地想在“第六颗子弹”里找到柔软的床。。。}
#{432}{}{Baby, you know better what to do. Honestly. I just follow.}
{432}{}{宝贝，你更清楚该怎么做。说真的？我只是跟着。}
#{433}{}{Never mind. Some dirty rogues from Reno migrated here and admire brahmin ass in the evenings.}
{433}{}{不要介意。一些肮脏的流氓从雷诺迁移到这里，在晚上欣赏婆罗门驴。}
#{434}{}{MAP_ENCLAVE_TRAP_ROOM}
{434}{}{地图\飞地\陷阱\房间}
#{435}{}{MAP_SALT_TRAIN}
{435}{}{火车地图}
#{436}{}{Some retarded residential area, beautiful. Can't we find a place to sleep that is more solid?}
{436}{}{一些弱智的居民区，很漂亮。我们不能找个更结实的地方睡觉吗？}
#{437}{}{Salt Lake City, the most fucked up town in the Wasteland, but a place you with one bed will be provided to us for sure.}
{437}{}{盐湖城，荒原上最糟糕的城镇，但我们肯定会给你提供一个只有一张床的地方。}
#{438}{}{Whew! While you are here to solve all your big tasks, I'll stand here and look at your body.}
{438}{}{呼！当你在这里解决你所有的重大任务时，我会站在这里看着你的身体。}
#{439}{}{Some church... Hey, how about marriage?}
{439}{}{一些教堂。。。嘿，结婚怎么样？}
#{440}{}{The Slums. It's so wild and exciting...}
{440}{}{贫民窟。太疯狂了，太刺激了。。。}
#{441}{}{Ruins. Just ruins.}
{441}{}{废墟。只是废墟。}
#{442}{}{Ruins. Just ruins.}
{442}{}{废墟。只是废墟。}
#{443}{}{Ruins. Just ruins.}
{443}{}{废墟。只是废墟。}
#{444}{}{Ruins. Just ruins.}
{444}{}{废墟。只是废墟。}
#{445}{}{Ruins. Just ruins.}
{445}{}{废墟。只是废墟。}
#{446}{}{Ruins. Just ruins.}
{446}{}{废墟。只是废墟。}
#{447}{}{Ruins. Just ruins.}
{447}{}{废墟。只是废墟。}
#{448}{}{Great. Never thought I would ever see this manufacturer of the universal urine, which eclipsed all trade in the Wastes.}
{448}{}{伟大的。我从没想过我会看到这个万能尿液的制造商，它让所有的废物交易黯然失色。}
#{449}{}{Wasteland. Just A Wasteland.}
{449}{}{荒地。只是一片荒地。}
#{1000}{}{Here?}
{1000}{}{在这里？}
#{1001}{}{That's better, pussycat?}
{1001}{}{好多了，小猫咪？}
#{1002}{}{What about here?}
{1002}{}{这里呢？}
#{1003}{}{Yes, kitty.}
{1003}{}{是的，基蒂。}
#{1004}{}{What?}
{1004}{}{什么？}
#{1005}{}{Where are we going?}
{1005}{}{我们要去哪里？}
#{1006}{}{We're leaving, honey?}
{1006}{}{我们要走了，亲爱的？}
#{1007}{}{I go where you say}
{1007}{}{我去你说的地方}
#{1008}{}{Sorry, honey.}
{1008}{}{对不起，亲爱的。}
#{1009}{}{Better?}
{1009}{}{更好？}
#{1010}{}{Uh...}
{1010}{}{休斯敦大学。。。}
#{1011}{}{Well, how am I in this light?}
{1011}{}{好吧，在这种情况下我怎么样？}
#{1012}{}{Are you taking me on stage?}
{1012}{}{你要带我上台吗？}
#{1013}{}{I'll just go here.}
{1013}{}{我就去这里。}
#{1020}{}{I think I've had enough!}
{1020}{}{我想我受够了！}
#{1100}{}{Oh my goddess, have mercy! I don't feel good!}
{1100}{}{哦，我的女神，宽恕吧！我感觉不太好！}
#{1101}{}{I need a doctor, baby.}
{1101}{}{我需要一个医生，宝贝。}
#{1102}{}{Oh, boy. Ow, that hurt.}
{1102}{}{哦，孩子。噢，真疼。}
#{1103}{}{Ow!}
{1103}{}{噢！}
#{1104}{}{Oh...}
{1104}{}{哦。。。}
#{1105}{}{Damn...}
{1105}{}{该死。。。}
#{1106}{}{Doctor?}
{1106}{}{医生？}
#{1107}{}{Holding on... Barely...}
{1107}{}{坚持住。。。仅仅。。。}
#{1108}{}{Soon I will be dead...}
{1108}{}{很快我就死了。。。}
#{1200}{}{Oh La La...}
{1200}{}{哦啦啦。。。}
#{1201}{}{Very well}
{1201}{}{很好}
#{1202}{}{I wait my beauty...}
{1202}{}{我等待我的美丽。。。}
#{1203}{}{I'm waiting on my goddess}
{1203}{}{我在等我的女神}
#{1204}{}{Just waiting for her}
{1204}{}{只是在等她}
#{1205}{}{She won't cheat on me that's for sure...}
{1205}{}{她不会背叛我那是肯定的。。。}
#{1206}{}{Oh, these women's stuff...}
{1206}{}{哦，这些女人的东西。。。}
#{1207}{}{Women are like that - you always have to wait}
{1207}{}{女人就是这样-你总是要等}
#{1208}{}{She's is shopping again...}
{1208}{}{她又去买东西了。。。}
#{1209}{}{That, again, carry this stuff?}
{1209}{}{再说一遍，带着这些东西？}
#{1210}{}{Hey, I'm here! And I'm bored!}
{1210}{}{嘿，我来了！我很无聊！}
#{1211}{}{They always are like this, always have to wait for them.}
{1211}{}{他们总是这样，总是要等他们。}
#{1212}{}{Uh... Well, I at least have Cola, I'm too exhausted.}
{1212}{}{休斯敦大学。。。嗯，至少我有可乐，我太累了。}
#{1213}{}{I need to lay off the women... Nothing but trouble from them}
{1213}{}{我要解雇那些女人。。。只有他们的麻烦}
#{1214}{}{I'd rather watched a fight in the ring in "Eldorado"}
{1214}{}{我宁愿在“埃尔多拉多”里看拳击比赛}
#{1215}{}{So what? There won't be sex?}
{1215}{}{那又怎么样？不会有性吗？}
#{1300}{}{Whew! My rocket again fueled and ready for action!}
{1300}{}{呼！我的火箭又加油了，准备行动了！}
#{1301}{}{Now I am full of energy for a scene on the mattress.}
{1301}{}{现在我对床垫上的一幕充满了活力。}
#{1302}{}{That's right!}
{1302}{}{这是正确的！}
#{1303}{}{Great, now I'm in line}
{1303}{}{太好了，现在我排队了}
#{1304}{}{About time}
{1304}{}{是时候了}
#{1305}{}{And I really thought that was my end}
{1305}{}{我真的以为这就是我的结局}
#{1306}{}{Ah so good!}
{1306}{}{啊，太好了！}
#{1310}{}{You're right - I don't want to vomit}
{1310}{}{你说得对-我不想呕吐}
#{1311}{}{That stink so much of smoke from the mouth? Hell...}
{1311}{}{从嘴里冒出这么多烟？地狱。。。}
#{1312}{}{Oh, the famous "furious"! A hundred years have not seen.}
{1312}{}{哦，著名的“愤怒”！一百年没见了。}
#{1313}{}{Not so fast, dearest. If we die, we do it together!}
{1313}{}{别那么快，亲爱的。如果我们死了，我们一起做！}
#{1314}{}{Oh, right, baby values me too much}
{1314}{}{哦，对了，宝贝太看重我了}
#{1315}{}{Well, I'm not a fan of candies, but they say with it...}
{1315}{}{我不喜欢糖果，但他们说。。。}
#{1316}{}{I will never say no to a glass of bloody Mary!}
{1316}{}{我决不会拒绝一杯血腥玛丽！}
#{1317}{}{This stuff I just will not eat! Yes, I for you.}
{1317}{}{这东西我就是不吃！是的，我在等你。}
#{1318}{}{What is this shit? Well, if we have nothing else...}
{1318}{}{这是什么狗屎？好吧，如果我们没有别的。。。}
#{1319}{}{Just like in the good old days when I was held in the... Uh, doesn't matter}
{1319}{}{就像以前我被关在。。。呃，没关系}
#{1320}{}{Just like before. I remember Doc Gray with his experiments on... Well, forget it.}
{1320}{}{就像以前一样。我记得格雷博士在。。。算了吧。}
#{1330}{}{Uh, thanks, honey.}
{1330}{}{呃，谢谢，亲爱的。}
#{1331}{}{Thanks}
{1331}{}{谢谢}
#{1332}{}{Baby, you know what you are doing?}
{1332}{}{宝贝，你知道你在做什么吗？}
#{1333}{}{Can't we just slee... Rest?}
{1333}{}{我们不能就这样。。。休息？}
#{1334}{}{Maybe we just sleep together?}
{1334}{}{也许我们只是睡在一起？}
#{1335}{}{What, I got the worst of it?}
{1335}{}{什么，我最糟的？}
#{1336}{}{Not too helpful.}
{1336}{}{没什么帮助。}
#{1337}{}{Well, if you insist, my goddess.}
{1337}{}{好吧，如果你坚持的话，我的女神。}
#{1338}{}{Beautiful, my head won't explode, right?}
{1338}{}{漂亮，我的头不会爆炸，对吧？}
#{1339}{}{Looks like it's starting to grow on me.}
{1339}{}{看来我开始喜欢上它了。}
#{1340}{}{I feel a bit strange.}
{1340}{}{我觉得有点奇怪。}
#{1341}{}{Uh, sure you don't want to? Why don't you try it?}
{1341}{}{呃，你确定不想？你为什么不试试呢？}
#{1342}{}{Sure, baby. I'll take some.}
{1342}{}{当然，宝贝。我要一些。}
#{1343}{}{Thanks, kitty}
{1343}{}{谢谢，基蒂}
#{1344}{}{Not bad}
{1344}{}{不错}
#{1998}{}{[Looks at the object}
{1998}{}{[看着这个物体}
#{1999}{}{] }
{1999}{}{]}
#{2000}{}{Nothing interesting. I've seen those rubber things in the store near the "Silver legacy"...}
{2000}{}{没什么有趣的。我在“银色遗产”附近的商店里见过那些橡胶制品。。。}
#{2053}{}{A real rarity. They say, it not just heals, but also strengthens the immunity.}
{2053}{}{真是稀罕。他们说，它不仅能治愈疾病，还能增强免疫力。}
#{2097}{}{Hmm, yeah you test my observation, baby! Of course, I can see that this must be placed somewhere.}
{2097}{}{嗯，是的，你测试我的观察力，宝贝！当然，我可以看出这个必须放在某个地方。}
#{2120}{}{Effortless power and brutality. The real gold amongst all the shit that can be found in the Wasteland. The only minus is the heavy barrel. However, there are technicians that could give it a fix.}
{2120}{}{毫不费力的力量和残忍。在荒地里能找到的大便中有真金白银。唯一的缺点是沉重的桶。然而，有技术人员可以给它一个解决办法。}
#{2164}{}{Familiar! Recognize the work of Striker. However, many brake on this stuff in the ring. You're not going to try it, right?}
{2164}{}{熟悉！认可前锋的工作。然而，许多人在拳击场上踩刹车。你不会尝试的，对吧？}
#{2222}{}{It glows? Baby, these things are valued simply for what they are.}
{2222}{}{它会发光吗？宝贝，这些东西的价值只是因为它们是什么。}
#{2237}{}{Newspapers? Well, you don't want to force me to read it do you? Okay... Advertising "Pretty & Glamour" I've heard it before. Yes that's right, vending machine in "Silver Legacy".}
{2237}{}{Newspapers? Well, you don't want to force me to read it do you? Okay... Advertising "Pretty & Glamour" I've heard it before. Yes that's right, vending machine in "Silver Legacy".}
#{2239}{}{Little weak. Honestly.}
{2239}{}{有点虚弱。说真的？}
#{2255}{}{I can say - only a nerd botanist can fix this.}
{2255}{}{我可以说-只有书呆子植物学家才能解决这个问题。}
#{2278}{}{Mickey... Same horny male, just like me.}
{2278}{}{米奇。。。同一个性欲旺盛的男人，就像我一样。}
#{2281}{}{Well, ok. Come on, baby, I won't tell anyone how many locks were unable to stand under your sensitive fingers.}
{2281}{}{好吧，好吧。来吧，宝贝，我不会告诉任何人有多少锁在你敏感的手指下站不住。}
#{2301}{}{This is from the company 'Pretty & Glamour'. There is a vending machine in "Silver Legacy" hotel... Hey wait, are you trying to tell me I stink?}
{2301}{}{This is from the company 'Pretty & Glamour'. There is a vending machine in "Silver Legacy" hotel... Hey wait, are you trying to tell me I stink?}
#{2310}{}{The only thing in this world that with time only gets better.}
{2310}{}{这个世界上唯一一件随着时间而变得更好的事情。}
#{2311}{}{These poor people in Salt Lake are alive only thanks to vocas. A handful in your mouth and consider your problem solved with radiation.}
{2311}{}{盐湖城的这些穷人只有靠歌喉才能活下来。一把放在嘴里，想想你的问题用辐射解决了。}
#{2324}{}{An expensive thing. As we reach the well, try it.}
{2324}{}{一件昂贵的东西。我们到了井边，试试看。}
#{2333}{}{You think in the wasteland there are those who need it?}
{2333}{}{你认为荒地里有人需要它吗？}
#{2337}{}{Famous pre-war drug, which improves your mental abilities. You're not going to try it? Smart girls is like a trap in the dark forest.}
{2337}{}{战前著名的药物，可以提高你的智力。你不打算试试吗？聪明的女孩就像黑暗森林中的陷阱。}
#{2388}{}{Hmm, I remember around the Salt Lake they saw geckos, spitting acid.}
{2388}{}{嗯，我记得在盐湖周围他们看到壁虎，吐酸。}
#{2413}{}{And I remember her! Worked in a strip club. real hottie, but after Ted Bundy he was gone. I bet a hundred coins on that she ran away to another city.}
{2413}{}{我记得她！在脱衣舞俱乐部工作。真的很性感，但特德·邦迪死后他就走了。我打赌她逃到了另一个城市。}
#{2417}{}{Like a helmet from power armor. But of course it's not... Well, I seen them in a magazine.}
{2417}{}{就像盔甲上的头盔。但当然不是。。。我在杂志上见过他们。}
#{2430}{}{Ehh, if we could shoot some aliens in Area 51 with this, huh?!}
{2430}{}{呃，如果我们能用这个在51区射杀外星人，嗯？！}
#{2433}{}{Effective! You are desired without it, but in the cap you just Magadesired!}
{2433}{}{有效！没有它你是被渴望的，但是在帽子里你只是被渴望的！}
#{2441}{}{Hey, it has the name of the owner here. Although, what do we care, right?}
{2441}{}{嘿，这里有主人的名字。不过，我们在乎什么，对吗？}
#{2471}{}{Some nutty professor wrote this. You don't want to be the same are you? And yet, in a doctor's coat and a miniskirt you'd be quite sexy.}
{2471}{}{是某个疯子教授写的。你不想和以前一样，是吗？然而，穿上医生的外套和超短裙你会很性感。}
#{2499}{}{There was one nerd who was pushing this poison from a warehouse around Reno. I once ate a little and almost died. After a couple of broken bones never saw that asshole again.}
{2499}{}{有个书呆子在里诺附近的仓库里推这种毒药。我曾经吃了一点，差点就死了。几根骨头断了以后再也没见过那个混蛋。}
#{2516}{}{'Pretty & Glamour' collection!? Oh, now you can forget about feminine odor.}
{2516}{}{'Pretty & Glamour' collection!? Oh, now you can forget about feminine odor.}
#{2525}{}{Oh, the famous "furious"! Remember. There was a scientist in Reno who developed the methamphetamine lab, but then it was finished by the junkies, which he himself tamed to this stuff. I do not advise to even try it.}
{2525}{}{哦，著名的“愤怒”！记得。里诺有一位科学家发明了甲基苯丙胺实验室，但后来被吸毒者完成了，他自己也驯服了。我甚至不建议尝试。}
#{2551}{}{Oh come on!}
{2551}{}{哦，来吧！}
#{2552}{}{The main thing is - not to abuse it.}
{2552}{}{最重要的是-不要滥用它。}
#{2554}{}{Almost like a regular coin to the touch and cannot be distinguished.}
{2554}{}{几乎像一枚普通的硬币一样触碰而无法辨别。}
#{2556}{}{Is this an emulator of a dick? I mean, my too small? Hell, I will have to do augmentation.}
{2556}{}{这是老二的仿真器吗？我是说，我的头发太小了？见鬼，我得做增强手术。}
#{2557}{}{This is an emulator of a dick? I mean, my too small? Hell, I will have to do augmentation.}
{2557}{}{这是老二的仿真器？我是说，我的头发太小了？见鬼，我得做增强手术。}
#{2558}{}{Th-that's not m-mine! Honestly! Yes, I would have that man killed, if I saw him... Maybe...}
{2558}{}{那不是我的！说真的？是的，我会杀了那个人，如果我看到他。。。也许 吧。。。}
#{2560}{}{Rare thing. But you're not going to carry this on you? In the vault suit you look sexier!}
{2560}{}{Rare thing. But you're not going to carry this on you? In the vault suit you look sexier!}
#{2561}{}{Rare thing. But you're not going to carry this on you? In the vault suit you look sexier!}
{2561}{}{稀有的东西。但你不打算把这个带在身上？穿金库套装你看起来更性感！}
#{2562}{}{Again junk from 'Pretty & Glamour'...}
{2562}{}{Again junk from 'Pretty & Glamour'...}
#{2563}{}{Again junk from 'Pretty & Glamour'...}
{2563}{}{Again junk from 'Pretty & Glamour'...}
#{2564}{}{Again junk from 'Pretty & Glamour'...}
{2564}{}{Again junk from 'Pretty & Glamour'...}
#{2565}{}{I saw this in California. That was long time ago.}
{2565}{}{我在加利福尼亚见过这个。那是很久以前的事了。}
#{2566}{}{Again junk from 'Pretty & Glamour'...}
{2566}{}{Again junk from 'Pretty & Glamour'...}
#{2573}{}{You're a fan of the extreme kind of pleasure!}
{2573}{}{你是那种极度快乐的粉丝！}
#{2577}{}{Again junk from 'Pretty & Glamour'...}
{2577}{}{Again junk from 'Pretty & Glamour'...}
#{2593}{}{Uh, look, this Hal Wallace, must be, a sensible man. I'd work for him. But hardly I can pull it off.}
{2593}{}{呃，听着，这个哈尔·华莱士，一定是个明智的人。我会为他工作。但我很难做到。}
#{2595}{}{Uh, look, this Hal Wallace, must be, a sensible man. I'd work for him. But hardly I can pull it off.}
{2595}{}{呃，听着，这个哈尔·华莱士，一定是个明智的人。我会为他工作。但我很难做到。}
#{2596}{}{You now have the hots for corrupt Mexicans cops? Almost extreme!}
{2596}{}{你现在喜欢腐败的墨西哥人警察了？近乎极端！}
#{2597}{}{Surely, this Deputy did not get any time in the crotch.}
{2597}{}{当然，这位副手没有任何机会。}
#{2626}{}{Lucky! Good weapons and rare ammo. Under other circumstances, you would not be able to find it.}
{2626}{}{真幸运！好武器和稀有弹药。在其他情况下，你将无法找到它。}
#{2627}{}{Lucky! Great gun and rare ammunition. Under other circumstances, you would not be able to find it.}
{2627}{}{真幸运！大炮和稀有弹药。在其他情况下，你将无法找到它。}
#{2628}{}{Lucky! Awesome gun and rare ammunition. Under other circumstances, you would not be able to find it.}
{2628}{}{真幸运！可怕的枪和稀有的弹药。在其他情况下，你将无法找到它。}
