#{100}{}{This is Hardy, ghoul merchant.}
{100}{}{这是哈迪，食尸鬼商人。}
#{101}{}{You see a merchant with scorched skin.}
{101}{}{你看到一个皮肤焦黄的商人。}
#{102}{}{Don??t hurt ghouls, damn racist!}
{102}{}{别伤害食尸鬼，该死的种族主义者！}
#{103}{}{Welcome... Hold on, was that you people told me about in Reno? Now, any sudden move and I will order to shoot you!}
{103}{}{欢迎...等等，是你们告诉我里诺的事吗？现在，任何突然的举动，我都会下令向你开枪！}
#{110}{}{Wanderer? In these parts? [coughs] Interesting. You probably need new knickers for the trip. Think about it - maybe I'll find something for you among these items.}
{110}{}{流浪者？在这些地方？[咳嗽]有趣。这次旅行你可能需要新的内裤。想一想，也许我会在这些东西中为你找到一些。}
#{111}{}{Yeah, show me what you have.}
{111}{}{是啊，给我看看你有什么。}
#{112}{}{I guess I won??t buy anything right now.}
{112}{}{我想我现在什么都不买。}
#{113}{}{More?}
{113}{}{更多？}
#{114}{}{Yeah, let??s look at your thing again.}
{114}{}{是的，让我们再看看你的东西。}
#{115}{}{No, that will be enough.}
{115}{}{不，那就够了。}
#{116}{}{Enough talk, let's trade.}
{116}{}{说够了，我们交易吧。}
#{117}{}{Another question, if I may.}
{117}{}{另一个问题，如果可以的话。}
#{118}{}{This will be enough. Take care.}
{118}{}{这就够了。当心。}
#{119}{}{Hey, smoothskin, you're just in time! Why? Because couple more trades - and I quit. Yes, old Hardy finally decided to retire and hide somewhere. So don't be stingy - buy all my junk, there may not be another such opportunity!}
{119}{}{嘿，光滑的皮肤，你来得正是时候！为什么？因为还有几笔交易-我就辞职了。是的，老哈代终于决定退休，躲到某个地方去。所以不要吝啬-买我所有的垃圾，可能没有另一个这样的机会！}
#{120}{}{Can I ask few questions?}
{120}{}{我能问几个问题吗？}
#{121}{}{Make it fast - I have to rest.}
{121}{}{快点-我得休息了。}
#{122}{}{Where are you from?}
{122}{}{你从哪里来的？}
#{123}{}{From The Hub. It is far to the South. Or rather, not so far, but to walk this distance is really hard. Between the Hub and Reno there are almost no settlements, no roads. Besides, most of the way we have to eke out in a barren desert. This route is pretty tough to walk, even without the load. Probably, my caravan is the only one.}
{123}{}{从中心。它在遥远的南方。或者说，不是很远，但是走这么远真的很难。枢纽和雷诺之间几乎没有定居点，没有道路。此外，大多数情况下我们不得不在贫瘠的沙漠中勉强度日。这条路很难走，即使没有负载。可能，只有我的大篷车。}
#{124}{}{How is business?}
{124}{}{生意怎么样？}
#{125}{}{Not very good, actually. Each journey makes us good money, but everything is spent on the costs - security, water, brahmin... I think I'm gonna shut it down soon. So bear in mind - we may never meet again. Trade while you can.}
{125}{}{其实不是很好。每一次旅行都让我们赚了不少钱，但一切都花在了成本上——安全、水、双头牛...我想我很快就会关掉它。所以请记住，我们可能再也不会见面了。趁热打铁。}
#{126}{}{Tell me about yourself.}
{126}{}{跟我说说你自己。}
#{127}{}{Do you really care? What if I tell you, how I got out of my hiding place in the days of the Big Bang and got irradiated to the point my mother did not recognize me? Or how my kind smoothskin friends died from old age, right in front of my eyes? Or, maybe, you want to know how it feels - to carve the dirt and pus out of your body every day? No, I'd rather refrain from talking about myself.}
{127}{}{你真的在乎吗？如果我告诉你，在宇宙大爆炸的日子里，我是怎么从我的藏身处出来的，受到了辐射，以至于我母亲都认不出我来的呢？或者我的好朋友是怎么在我眼前死去的？或者，也许，你想知道每天从身上刻下污垢和脓的感觉？不，我宁愿不谈我自己。}
#{128}{}{If you are going to leave the business, perhaps you would do me a discount?}
{128}{}{如果你要离开这家公司，也许可以给我打折？}
#{129}{}{Makes sense - the sooner you get rid of this stuff, the faster I will get to Reno, to my white-titted girls.}
{129}{}{有道理-你越早摆脱这些东西，我就越快到雷诺，我的白奶子女孩。}
#{130}{}{Oh no - these tricks won??t work with me, I didn??t drag all this across the desert for nothing!}
{130}{}{哦，不-这些把戏对我不起作用，我不是白白把这些东西拖过沙漠的！}
#{131}{}{Fine, forget it. Let??s trade on your stubborn prices.}
{131}{}{好吧，算了吧。让我们用你的顽固价格来交换吧。}
#{132}{}{Then I refuse to buy anything. Stay with your stuff.}
{132}{}{那我什么都不买。留下你的东西。}
#{133}{}{Do you remember, how it was, before the Great War?}
{133}{}{你还记得吗，那是怎样的，在大战之前？}
#{134}{}{Same as now. Just little cleaner and more pleasant.}
{134}{}{和现在一样。更干净，更愉快。}
#{140}{}{I'm from Lewis Birch. He asked to take this to the Hub.}
{140}{}{我来自刘易斯·伯奇。他要求把这个带到中心。}
#{141}{}{Birch asked? Then no problem... Yeah, I recognize his holodisks. Give them here. When I return to the Hub, will visit the office of this chump. And oh they will be glad to see me!}
{141}{}{白桦问？那没问题...是的，我认得他的全息光盘。把它们给我。当我回到中心的时候，会拜访这个笨蛋的办公室。哦，他们会很高兴见到我的！}
#{142}{}{Well, my job is done.}
{142}{}{好吧，我的工作完成了。}
#{143}{}{You've completed the task of Lewis Birch.}
{143}{}{你已经完成了刘易斯·伯奇的任务。}
#{1110}{}{Wanderer? In these parts? [coughs] Interesting. You  probably need new knickers for the trip. Think about it - maybe I'll find something for you among these items.}
{1110}{}{流浪者？在这些地方？[咳嗽]有趣。这次旅行你可能需要新的内裤。想一想，也许我会在这些东西中为你找到一些。}
#{1119}{}{Hey, smoothskin, you're just in time! Why? Because couple more trades - and I quit. Yes, old Hardy finally decided to retire and hide somewhere. So don't be stingy - buy all my junk, there may not be another such opportunity!}
{1119}{}{嘿，光滑的皮肤，你来得正是时候！为什么？因为还有几笔交易-我就辞职了。是的，老哈代终于决定退休，躲到某个地方去。所以不要吝啬-买我所有的垃圾，可能没有另一个这样的机会！}
