#{100}{}{You see BlackDesigner.}
{100}{}{你看BlackDesigner。}
#{101}{}{You see an ordinary designer, like any other.}
{101}{}{你会看到一个普通的设计师，就像其他设计师一样。}
#{110}{}{Decided to drop by? Good!}
{110}{}{决定来拜访？很好！}
#{111}{}{There are all kinds of things going on in the wasteland.}
{111}{}{荒地里发生了各种各样的事情。}
#{112}{}{I'd travel myself, but not with an empty pockets.}
{112}{}{我会自己旅行，但不会带着空口袋。}
#{113}{}{I have to work for food.}
{113}{}{我得为食物而工作。}
#{114}{}{Who wants to lend me two million bucks for my project?}
{114}{}{谁想借给我两百万美元做我的项目？}
#{115}{}{Some petty two million!}
{115}{}{一些微不足道的两百万！}
#{116}{}{All right, forget I asked...}
{116}{}{好吧，忘了我问过...}
#{117}{}{There'll be no sequel. I think you've figured that out by now.}
{117}{}{不会再有续集了。我想你现在已经明白了。}
#{118}{}{What am I working on now? It's funny, I'm working on... You!}
{118}{}{我现在在做什么？很有趣，我正在...你！}
#{119}{}{Nooo, no, no! I don't have any kind of liquor here.}
{119}{}{不，不，不！我这里没有酒。}
#{120}{}{Hmm, so *this* is the way you want to roleplay?... Well, it's up to you after all.}
{120}{}{嗯，这就是你想要的角色扮演方式？...好吧，还是你说了算。}
#{121}{}{Are you one of those who don't like to read much text too?}
{121}{}{你也是不喜欢读太多课文的人吗？}
#{122}{}{If I called the whole team here, there'd be no room to swing a cat. Sorry.}
{122}{}{如果我把全队都叫到这里来，就没有回旋余地了。对不起的。}
#{123}{}{The "I know" kid? Don't mind him. He was not the first and certainly he won't be the last.}
{123}{}{那个“我知道”的孩子？别理他。他不是第一个，当然也不会是最后一个。}
#{200}{}{You think poking me repeatedly with this thing will get you somewhere?}
{200}{}{你认为用这个东西反复戳我会让你有所收获吗？}
#{201}{}{Hmm, from your persistence I can tell you think it will result in something useful. Ha!}
{201}{}{嗯，从你的坚持来看，我可以告诉你这会带来一些有用的结果。哈！}
#{202}{}{Yes, I know, you expect me to give you some kind of super-dooper device. Sorry to ruin your expectations, but this isn't happening.}
{202}{}{是的，我知道，你希望我给你一个超级垃圾装置。抱歉破坏了你的期望，但这不是真的。}
#{203}{}{What else would you like me to do? Beat the game for you?}
{203}{}{你还想让我做什么？为你赢得比赛？}
#{204}{}{Yes, go on, I still can't bring myself to break it to you...}
{204}{}{是的，继续，我还是不能让自己打破它给你...}
#{205}{}{What, you like poking a man with an arrow so much? But what wouldn't you do for a gift, right?}
{205}{}{什么，你这么喜欢用箭戳人？但你不会做什么礼物，对吗？}
#{206}{}{Yes, right! Almost there!}
{206}{}{是的，对！快到了！}
#{207}{}{Sure. You earned it. I'll go get it now... No, wait. Not yet.}
{207}{}{当然。这是你应得的。我现在就去拿...不，等等。还没有。}
#{210}{}{Damn, so much time and effort for some uber device? A round of applause is in order, I just have to reward you somehow now. Here, a limitless source of experience... Well, as long as you got the nerve.}
{210}{}{妈的，那么多的时间和精力在一些uber设备上？掌声已经准备好了，我现在要奖励你了。在这里，一个无限的经验来源...好吧，只要你有勇气。}
#{211}{}{[Leave]}
{211}{}{[离开]}
#{212}{}{I think I've said it all.}
{212}{}{我想我都说了。}
