#{100}{}{You see a punk.}
{100}{}{你看到一个朋克。}
#{101}{}{You see a punk with a very aggressive attitude. It seems that he is under the influence of drugs.}
{101}{}{你看到一个态度非常好斗的朋克。他似乎受了毒品的影响。}
#{110}{}{I'll dance on your grave!}
{110}{}{我要在你的坟墓上跳舞！}
#{111}{}{We, the cocaine vacuums of Salt Lake, are against the drunks of Las Vegas!}
{111}{}{我们，盐湖城的可卡因真空，反对拉斯维加斯的醉汉！}
#{112}{}{I'm in a plastic world eating plastic cereal.}
{112}{}{我在一个塑料世界里吃塑料谷类食品。}
#{113}{}{If people don??t like me, then I don't like people.}
{113}{}{如果人们不喜欢我，那我就不喜欢别人。}
#{114}{}{I'm fighting against the system... Actually, no, I'm just fighting.}
{114}{}{我在和体制抗争...实际上，不，我只是在打架。}
#{115}{}{I think all people in the neighborhood would look better with a hole in the head}
{115}{}{我想这附近的人脑袋上有个洞会好看些}
#{116}{}{I'm 18, so I can say "fuck you!!!"}
{116}{}{我18岁了，所以我可以说“去你妈的！！！”}
#{117}{}{Hey, look! It's like the Devil took a shit and it landed right here!}
{117}{}{嘿，看！就像魔鬼大便了，它就降落在这里！}
#{118}{}{I'll break the system! Starting with you!}
{118}{}{我要破坏系统！从你开始！}
#{119}{}{For a bottle of beer we'll skin you alive.}
{119}{}{为了一瓶啤酒，我们会活剥你的皮。}
