#{100}{}{You see a nomad.}
{100}{}{你看到一个游牧民族。}
#{101}{}{you see an experienced nomad of Great Basin.}
{101}{}{你看到一个经验丰富的大盆地游牧民族。}
#{110}{}{[Frowns with dislike at the sight of you] Shouldn't be standing so close. And it's hot in here already.}
{110}{}{[看到你皱眉]不应该站得这么近。这里已经很热了。}
#{111}{}{[Curiously looking at you] Hi! Traveling too?}
{111}{}{[好奇地看着你]嗨！也去旅行？}
#{112}{}{[Looks at you blankly] Just traveling or running from someone?}
{112}{}{[茫然地看着你]只是在旅行还是在逃避某人？}
#{113}{}{I'd like to get provisions for the journey. Could you share some with me?}
{113}{}{我想买旅行用品。你能和我分享一些吗？}
#{114}{}{I wonder, what people like you are doing in these uninhabited lands?}
{114}{}{我想知道，像你这样的人在这些无人居住的地方干什么？}
#{115}{}{I have been roaming for a while. Tell me, where is the closest town?}
{115}{}{我已经漫游了一段时间了。告诉我，最近的城镇在哪里？}
#{116}{}{I should probably continue my journey. Farewell.}
{116}{}{我应该继续我的旅程。再会。}
#{117}{}{That's all I can exchange. If this is not enough, you have to go into the city.}
{117}{}{我只能换这些了。如果这还不够，你就得进城去。}
#{118}{}{Speaking of the city. Tell me, where is it?}
{118}{}{说到城市。告诉我，它在哪里？}
#{119}{}{We wander from valley to valley in search of a suitable place to live. And we came from the North-East. There is now a series of wars and devastations. Many fled from there. Surely you will meet other nomads from those places.}
{119}{}{我们从一个山谷游荡到另一个山谷，寻找一个适合居住的地方。我们来自东北。现在有一系列的战争和破坏。许多人逃离那里。你一定会遇到那些地方的游牧民族。}
#{120}{}{Salt Lake City in the North. Go along the highway and you'll hit yourself straight into the city near a large lake.}
{120}{}{北部的盐湖城。沿着高速公路走，你会直接撞到一个大湖附近的城市。}
