#{100}{}{You see a robot.}
{100}{}{你看到一个机器人。}
#{101}{}{You see a robot. You got a hunch that it might be hostile.}
{101}{}{你看到一个机器人。你有预感那可能是敌对的。}
#{102}{}{Welcome}
{102}{}{欢迎光临}
#{110}{}{Alarm! Trespasser spotted!}
{110}{}{警报！发现入侵者！}
#{111}{}{Activate security system!}
{111}{}{启动安全系统！}
#{112}{}{Received command to eliminate trespassers! Engaging.}
{112}{}{收到了消灭非法闯入者的命令！迷人的。}
#{120}{}{Welcome to "Poseidon Oil" Power Plant! Please do not disrupt public order and keep facility grounds clean.}
{120}{}{欢迎来到“波塞冬石油”发电厂！请勿扰乱公共秩序，保持设施场地清洁。}
#{121}{}{We apologize for any further inconvenience. We hope no such incident occurs again.}
{121}{}{对于由此带来的不便，我们深表歉意。我们希望不会再发生这样的事件。}
#{122}{}{Welcome, visitor.}
{122}{}{欢迎光临，客人。}
#{123}{}{Welcome, visitor. We are always glad to see you.}
{123}{}{欢迎光临，客人。我们总是很高兴见到你。}
#{130}{}{Robot disabled.}
{130}{}{机器人已禁用。}
#{131}{}{This one is done for}
{131}{}{这一个已经完成了}
#{132}{}{You fail to make sense of the robot's systems and only draw unwanted attention.}
{132}{}{你无法理解机器人的系统，只会引起不必要的注意。}
#{133}{}{Unauthorized personnel shouldn't do this}
{133}{}{未经授权的人员不应该这样做}
#{134}{}{Don't make me use force}
{134}{}{别逼我用武力}
#{135}{}{Trespasser detected! Eliminate immediately!}
{135}{}{检测到非法闯入者！立即消除！}
#{136}{}{You lack the repair skill to successfully disable the robot.}
{136}{}{你缺乏修复技能，无法成功禁用机器人。}
