#{100}{}{Jammed door.}
{100}{}{门卡住了。}
#{101}{}{The door is so tightly jammed that you can't even move it.}
{101}{}{门堵得太紧了，你都动不了。}
#{102}{}{This metal door is too strong to just kick it open.}
{102}{}{这扇金属门太坚固了，不能直接踹开。}
#{103}{}{Your skills won't help you, the door is jammed shut.}
{103}{}{你的技术帮不了你，门被卡住了。}
#{104}{}{No use, the door is jammed.}
{104}{}{没用，门卡住了。}
#{105}{}{The door is so tightly jammed that you can't even move it.}
{105}{}{门堵得太紧了，你都动不了。}
#{106}{}{Can't be opened}
{106}{}{无法打开}
