#{100}{}{You see a raider.}
{100}{}{你看到一个袭击者。}
#{101}{}{One of Big Louie's vultures, chaperoning you to Hawthorne.}
{101}{}{路易的一只秃鹫，陪你去霍桑。}
#{102}{}{Oh my god! They killed Kenny!}
{102}{}{哦，我的上帝！他们杀了肯尼！}
#{104}{}{Goddammit!}
{104}{}{他妈的！}
#{105}{}{Where the hell are you leading us?!}
{105}{}{你到底要带我们去哪里？！}
#{106}{}{You little - ! I warned you!}
{106}{}{你这个小-！我警告过你！}
#{107}{}{Fuck this! I'm not your fucking bodyguard!}
{107}{}{去他妈的！我不是你的保镖！}
#{108}{}{When I'm done with him, you're next on my list, motherfucker!}
{108}{}{等我把他干掉，你就是我名单上的下一个，混蛋！}
#{109}{}{You asshole! I'll remember this!}
{109}{}{你个混蛋！我会记住的！}
#{110}{}{So what? Are you just gonna keep talking?}
{110}{}{那又怎么样？你要继续说下去吗？}
#{111}{}{Stay here while I check things out.}
{111}{}{待在这儿等我检查。}
#{112}{}{I found a safe passage. Come with me.}
{112}{}{我找到了一条安全的通道。跟我来。}
#{113}{}{Wait here, I have some scouting to do.}
{113}{}{等等，我有一些侦察工作要做。}
#{114}{}{Forget it.}
{114}{}{算了吧。}
#{115}{}{Don't bug me, I'm resting.}
{115}{}{别烦我，我在休息。}
#{116}{}{Give me a boost over the fence.}
{116}{}{把我推过篱笆。}
#{130}{}{The security systems are down! It's safe to search the storage rooms... What?}
{130}{}{安全系统坏了！搜查储藏室是安全的。。。什么？}
#{131}{}{I'll be damned... I thought you'd be useless, but the boss was right about you. Good job. Anyway, I got shit to do. You get back to the base.}
{131}{}{我会被诅咒的。。。我以为你没用，但老板对你的看法是对的。干得好。不管怎样，我还有事情要做。你回基地去。}
#{132}{}{Right. See you.}
{132}{}{正确的。再见。}
#{133}{}{Those turrets look nasty. Can you think of a way to get past them?}
{133}{}{那些炮塔看起来很恶心。你能想出一个办法克服他们吗？}
#{134}{}{Look, those turrets gotta run on electricity or something, right? Unplug the generator and that'll do it. I dunno, you figure it out.}
{134}{}{你看，那些炮塔得靠电什么的，对吧？把发电机的插头拔下来就行了。我不知道，你想好了。}
#{135}{}{Right.}
{135}{}{正确的。}
#{136}{}{Don't you want to come with me? Before, you wouldn't take your eyes off me.}
{136}{}{你不想和我一起去吗？以前，你不会把目光从我身上移开。}
#{137}{}{Nah. I'm gonna wait here until you get the job done. It'll be safer alone, and anyway, if you try running off - it's your funeral.}
{137}{}{不。我在这里等你把工作做完。独自一人会更安全，不管怎样，如果你想逃跑，那就是你的葬礼了。}
#{138}{}{Right.}
{138}{}{正确的。}
#{140}{}{This is the place. Here's the plan: Boss wants us to find a way into the military base so we can get some of those guns and ammo in storage. Actually, he wants YOU to find into the base, because I ain't risking my ass for this. And no funny stuff, or you can consider yourself dead. You got that?}
{140}{}{就是这个地方。计划是这样的：老板想让我们找到一条进入军事基地的路，这样我们就可以把一些枪和弹药储存起来。事实上，他想让你去基地调查，因为我可不想冒这个险。不要搞笑，否则你会认为自己死了。明白了吗？}
#{141}{}{I got that. Where are the guns and ammo stored?}
{141}{}{我明白了。枪和弹药存放在哪里？}
#{142}{}{Yeah, yeah, cut the attitude. And stay close, so I don't have to save your sorry ass every time there's trouble.}
{142}{}{是啊，是啊，别摆架子了。离我近一点，这样我就不用每次有麻烦的时候都救你了。}
#{143}{}{We're at the edge of a dead city. We gotta cut through it to get to the base. It's guarded by turrets, so watch your ass.}
{143}{}{我们在一个死城的边缘。我们必须切断它才能到达基地。有炮塔守卫，小心你的屁股。}
#{144}{}{I've got it. Let's do this.}
{144}{}{我知道了。我们开始吧。}
#{145}{}{You're right. Let's talk for a minute.}
{145}{}{你说得对。我们谈一下。}
#{150}{}{What? Something else?}
{150}{}{什么？还有别的吗？}
#{151}{}{What is this place?}
{151}{}{这是什么地方？}
#{152}{}{What's our mission?}
{152}{}{我们的任务是什么？}
#{153}{}{Where are the warehouses?}
{153}{}{仓库在哪里？}
#{154}{}{Another question.}
{154}{}{另一个问题。}
#{155}{}{Enough chit-chat. Let's go.}
{155}{}{闲聊够了。走吧。}
#{156}{}{Hawthorne, a dead city. Everyone that lived here died in the Great War. Now it's full of nothing but rats, turrets, lowlifes, and every other type of shit you can imagine.}
{156}{}{霍桑，一座死城。所有住在这里的人都死于大战。现在到处都是老鼠，炮塔，卑鄙小人，还有你能想象到的其他类型的东西。}
#{157}{}{Are you deaf? We have to get the guns and ammo in the base, and to do that, we need to take out those turrets. As long as they're around, we can't get in.}
{157}{}{你聋了吗？我们必须把枪和弹药运到基地，要做到这一点，我们必须摧毁那些炮塔。只要他们还在，我们就进不去。}
#{158}{}{Somewhere north. Inside the base.}
{158}{}{在北方某个地方。在基地里面。}
#{159}{}{Here. Right behind the fence.}
{159}{}{在这里。就在栅栏后面。}
#{160}{}{Does anyone live here?}
{160}{}{有人住在这里吗？}
#{161}{}{There's no one here but prospectors, and only the desperate ones. They fight each other for copper wire here. The radiation wiped out everyone that actually lived in this place - all that's left of them is bones in the streets.}
{161}{}{这里只有探矿者，只有绝望的探矿者。他们在这里为铜线打架。辐射摧毁了所有住在这里的人，只剩下街上的骨头。}
#{1104}{}{Goddammit!}
{1104}{}{他妈的！}
#{1105}{}{Where the hell are you leading us?!}
{1105}{}{你到底要带我们去哪里？！}
#{1106}{}{You little - ! I warned you!}
{1106}{}{你这个小-！我警告过你！}
#{1107}{}{Shit! I'm not your fucking bodyguard!}
{1107}{}{倒霉！我不是你的保镖！}
#{1108}{}{When I'm done with him, you're next on my list, you bitch!}
{1108}{}{等我把他干掉，你就是我名单上的下一个，婊子！}
#{1109}{}{You bitch! I'll remember this!}
{1109}{}{你这个婊子！我会记住的！}
#{1112}{}{I found a safe passage. Come with me.}
{1112}{}{我找到了一条安全的通道。跟我来。}
#{1114}{}{Forget it.}
{1114}{}{算了吧。}
#{1115}{}{Don't bug me, I'm resting.}
{1115}{}{别烦我，我在休息。}
