#{100}{}{You see the clerk Harry.}
{100}{}{你看到那个职员了吗。}
#{101}{}{You see a fussy, ever smiling clerk.}
{101}{}{你看到一个挑剔的，总是面带微笑的职员。}
#{110}{}{Yes-yes? How can I help?}
{110}{}{什么事？什么事？我能帮忙吗？}
#{111}{}{See you.}
{111}{}{再见。}
#{112}{}{Can I find a job here?}
{112}{}{我能在这里找到工作吗？}
#{113}{}{I don't know that. Talk to our director, he usually checks every worker himself. Director Skinner is in his office, behind me.}
{113}{}{我不知道。和我们的主任谈谈，他通常亲自检查每个工人。斯金纳主任在他的办公室，在我后面。}
#{114}{}{Thanks, I'll go to him.}
{114}{}{谢谢，我去找他。}
#{115}{}{I have a part that will allow to launch artesian tower. Who should I speak to, about the price?}
{115}{}{我有一个部件可以发射自流塔。我该和谁谈谈价格问题？}
#{116}{}{Oh, yes! Sure, the factory's in need of repairing this tower! Speak to our director immediately. He's in his office, behind me.}
{116}{}{哦，是的！当然，工厂需要修理这座塔！马上和我们的主管谈谈。他在办公室，在我后面。}
#{117}{}{Oh, it's you! We have heard about your courier achievements, and are glad that you want to work with us.}
{117}{}{哦，是你！我们听说了您的快递成就，很高兴您愿意与我们合作。}
#{150}{}{Ladies and gentlemen! That's how we should work!}
{150}{}{女士们先生们！我们应该这样工作！}
#{151}{}{No slacking.}
{151}{}{不能偷懒。}
#{152}{}{Clerk is a basis of any enterprise.}
{152}{}{办事员是任何企业的基础。}
#{153}{}{Clerk is like a God... Yes, exactly.}
{153}{}{店员就像上帝。。。是的，没错。}
#{154}{}{I can save the factory or bring it down. Do you understand how important I am?}
{154}{}{我可以拯救工厂，也可以摧毁它。你知道我有多重要吗？}
#{155}{}{The most important thing is to gain the trust of the client.}
{155}{}{最重要的是赢得客户的信任。}
#{156}{}{What is the most important for the client? Right, to be kissed in the ass.}
{156}{}{对客户来说什么是最重要的？对，被人亲屁股。}
#{157}{}{We'll have a lot of customers, if you work hard.}
{157}{}{如果你努力的话，我们会有很多顾客的。}
#{158}{}{Don't even think of slacking!}
{158}{}{别想偷懒！}
#{159}{}{Well, and where are our active clients?!}
{159}{}{那么，我们的活跃客户呢？！}
#{160}{}{There's no customers because you are lazy!}
{160}{}{因为你懒惰，所以没有顾客！}
#{161}{}{If you wouldn't be lazy and worked like me...}
{161}{}{如果你不懒，不象我一样工作。。。}
#{162}{}{No career progression! One either progresses, or doesn't.}
{162}{}{没有职业发展！要么进步，要么不进步。}
#{163}{}{Don't confuse marketing and management! It's not the same.}
{163}{}{别把营销和管理混为一谈！这不一样。}
#{164}{}{We need a decent designer...}
{164}{}{我们需要一个像样的设计师。。。}
#{165}{}{I knew a designer once...}
{165}{}{我认识一个设计师。。。}
#{166}{}{Our enterprise either good, or... Oops, no or.}
{166}{}{我们的企业要么很好，要么。。。哦，不，或者。}
#{167}{}{Well? Are you done being lazy?}
{167}{}{好？你懒散了吗？}
#{168}{}{Wake up! There's customers!}
{168}{}{醒醒！顾客来了！}
#{169}{}{Oh! Look - a customer!}
{169}{}{哦！看-一个顾客！}
#{170}{}{Watch how I'll sell to him!}
{170}{}{看我怎么卖给他！}
#{171}{}{Five percents! FIVE PERCENTS!!!}
{171}{}{百分之五！百分之五！！！}
#{172}{}{A man-clerk should be moderately unmarried.}
{172}{}{男性职员应适度未婚。}
#{173}{}{Hands-out-of-ass - that's about you!}
{173}{}{把手从屁股上拿开-那是关于你的！}
#{174}{}{When's lunch?}
{174}{}{什么时候吃午饭？}
#{175}{}{I'm starving here... Oooh...}
{175}{}{我饿死了。。。哦哦。。。}
#{176}{}{Is anyone going to the market? I want some jerky...}
{176}{}{有人要去市场吗？我想要些肉干。。。}
#{177}{}{The most important thing in management is to work with people.}
{177}{}{管理中最重要的是与人合作。}
#{178}{}{The clerk is the coolest job! You don't believe it? Too bad!}
{178}{}{办事员是最酷的工作！你不相信吗？太糟糕了！}
#{179}{}{Did you write everything? I will check!}
{179}{}{你什么都写了吗？我去查查！}
#{180}{}{Why don't you want to hire the caravan merchant that sells pre-war cola?}
{180}{}{你为什么不雇一个卖战前可乐的商队商人呢？}
#{181}{}{Oh, I remember, yes-yes. It's our rival with a very shady business, right? We don't need people of such... Uh, origin. Well, you know, peasants with tanned skin and working hands will not get people's affection.}
{181}{}{哦，我记得，是的。这是我们的竞争对手，生意很阴暗，对吧？我们不需要这样的人。。。呃，起源。嗯，你知道，皮肤晒得黝黑、双手劳动的农民不会得到人们的喜爱。}
#{182}{}{I think you're wrong. You should not throw away such a good worker.}
{182}{}{我觉得你错了。你不应该抛弃这样一个好工人。}
#{183}{}{Could I change your mind? No, not likely... Fine, see you.}
{183}{}{我能改变你的想法吗？不，不太可能。。。好的，再见。}
#{184}{}{Oh, really? And what should change my mind?}
{184}{}{哦，真的吗？什么会让我改变主意？}
#{185}{}{My recommendation as an experienced courier.}
{185}{}{我推荐你做一个有经验的信使。}
#{186}{}{My recommendation as an experienced trader.}
{186}{}{我推荐你做一个有经验的交易者。}
#{187}{}{This changes things. So what is so good about him?}
{187}{}{这改变了一切。那么他有什么优点呢？}
#{188}{}{You focus on communication and appearance, instead of real skills and experience. It's good in the urban environment, but with the villagers it's different. This trader will be accepted with them as his own, that makes it easier for him to negotiate.}
{188}{}{你专注于沟通和外表，而不是真正的技能和经验。在城市环境中是好的，但在村民中就不同了。这个交易者会被他们当作自己的交易者接受，这使他更容易谈判。}
#{189}{}{Hmm. I had never thought about this like that. Now I understand, why our couriers fail assignments in settlements. Perhaps we will have to reconsider the approach. Please, tell this merchant that we would like to conclude an agreement with him - provided that he will give us the remaining Nuka-Cola.}
{189}{}{嗯。我从没想过这个。现在我明白了，为什么我们的快递员不能完成任务。也许我们将不得不重新考虑这个方法。请告诉这位商人，我们想和他签订一项协议，只要他能给我们剩下的努卡可乐。}
#{190}{}{You made the right choice, Harry.}
{190}{}{你做了正确的选择，哈利。}
#{200}{}{How about a joint business?}
{200}{}{合资经营怎么样？}
#{201}{}{You want to sell cola in other cities, right?}
{201}{}{你想在其他城市卖可乐，对吗？}
#{202}{}{Maybe!}
{202}{}{也许 吧！}
#{203}{}{If so, then I am at your service! Welcome to the office of the *operating* Nuka-Cola factory! The only one in this region, and possibly the whole world. With us, you can at any time make a deal on the delivery of the drink to any locality and for any institution. But I warn you right away - we just accept the orders, you must deal with deliveries yourself.}
{203}{}{如果是这样，那我就为你效劳！欢迎来到努卡可乐工厂的办公室！这个地区唯一的一个，可能是整个世界。与我们合作，您可以随时为任何地方和任何机构提供饮料。但我马上警告你-我们只是接受订单，你必须自己处理交货。}
#{204}{}{In other words, you just give the license to trade the soft drink?}
{204}{}{换言之，你只是给了经营软饮料的许可证？}
#{205}{}{We produce the drink and give it in the form of a large wholesale batches. Of course, you can simply buy a lot of cola every time and deliver it to your companions. But for those who buy a license, we give a discount and reserve an order.}
{205}{}{我们生产这种饮料，并以大批量批发的形式提供。当然，你可以简单地每次买很多可乐，然后把它送给你的同伴。但对于购买许可证的客户，我们会给予折扣并保留订单。}
#{206}{}{Reserve?}
{206}{}{保留？}
#{207}{}{Yes. When we know the volume of your order, we just store it and wait for your caravan. Otherwise, we distribute the order to any incoming customers. And then your caravan is at least doomed to wait a few days until we again produce the required quantity.}
{207}{}{对。当我们知道你的订单数量时，我们就把它储存起来，等待你的商队。否则，我们会将订单分发给任何新来的客户。然后你们的商队至少注定要等几天，直到我们再次生产所需的数量。}
#{208}{}{So, by purchasing a license, I get a guarantee that my goods will stay in place, right?}
{208}{}{所以，通过购买许可证，我就可以保证我的货物会留在原地，对吧？}
#{209}{}{Correct! But we need to make one more remark. Now in the wastelands there are rumors of a low-quality commodity. This undermines the reputation of the factory. If you have proof that you work with us directly, your customers will have more incentive to make a deal with you and give you much more trust.}
{209}{}{对的！但我们需要再多说一句话。现在在荒地里有一种劣质商品的谣言。这损害了工厂的声誉。如果你有证据表明你直接与我们合作，你的客户将有更多的动力与你达成交易，给你更多的信任。}
#{210}{}{That is, I can enter into transactions without a license?}
{210}{}{也就是说，我可以在没有许可证的情况下进行交易？}
#{211}{}{Perhaps! If you look trustworthy enough. But believe me, most of the traders already learned the lesson and try to work only with those who have a license.}
{211}{}{也许！如果你看起来足够可靠。但相信我，大多数交易者已经吸取了教训，他们只会尝试与那些有执照的人合作。}
#{212}{}{How much for this license?}
{212}{}{这个执照多少钱？}
#{213}{}{We will sell it you for }
{213}{}{我们会卖给你的}
#{214}{}{ bucks. Very good price, if we count, how much you gain by selling.}
{214}{}{美元。很好的价格，如果我们计算一下，你卖了多少钱。}
#{215}{}{It's tempting. And what to do after?}
{215}{}{很诱人。之后该怎么办？}
#{216}{}{Only you can decide. You can buy a large shipment of cola. How to find a client and how to deliver it - is your job. We recommend talking to caravan merchants. Of course, they will take some percentage for their services, but they can transport a lot of bottles very fast.}
{216}{}{只有你能决定。你可以买一大批可乐。如何找到一个客户，如何提供它-是你的工作。我们建议和商队商人谈谈。当然，他们会为他们的服务收取一定比例的费用，但是他们可以很快地运送很多瓶子。}
#{217}{}{How many couriers are there right now? Will I be able to make money on such business?}
{217}{}{现在有多少快递员？我做这种生意能赚钱吗？}
#{218}{}{I think yes! You see, for a while, the factory worked mainly on the inner city market. The wastelands are poorly acquainted with our products, still consuming the reserves from a pre-war times.}
{218}{}{我想是的！你看，有一段时间，这家工厂主要经营内城市场。荒地对我们的产品不熟悉，仍在消耗战前的储备。}
#{219}{}{I want to purchase a license! How much?}
{219}{}{我想买个许可证！多少？}
#{220}{}{Thank you, for explaining, I will think about it. Take care.}
{220}{}{谢谢你的解释，我会考虑的。当心。}
#{221}{}{ bucks. That is director's price, he ordered not to haggle for it.}
{221}{}{美元。这是主任的价格，他命令不要讨价还价。}
#{222}{}{I'm buying!}
{222}{}{我要买！}
#{223}{}{Oh, I can't afford that. See you.}
{223}{}{哦，我负担不起。再见。}
#{224}{}{Don't drop your money! It's the most horrific thing I ever seen!}
{224}{}{别把钱掉了！这是我见过的最可怕的事！}
#{225}{}{Oops, sorry.}
{225}{}{哦，对不起。}
#{226}{}{[You sign a pile of papers and shake hands] Good luck in business, courier! We wish you and your humble cause prosperity and every success!}
{226}{}{[你在一堆文件上签名并握手]祝你好运，信使！我们祝愿你和你卑微的事业兴旺发达，万事如意！}
#{227}{}{Same to you!}
{227}{}{和你一样！}
#{228}{}{You became the official representative of the Nuka-Cola factory. Congratulations on your prestigious position!}
{228}{}{你成了努卡可乐厂的官方代表。恭喜你获得这一殊荣！}
