#{100}{}{You see a citizen.}
{100}{}{你看到一个公民。}
#{101}{}{You see a citizen.}
{101}{}{你看到一个公民。}
#{102}{}{You see a common citizen of Salt Lake City.}
{102}{}{你看到一个盐湖城的普通市民。}
#{103}{}{Don't bother me.}
{103}{}{别打扰我。}
#{104}{}{Don't bother Robert, please. He's yet to cut fruit for dinner because of that stupid puzzle of his.}
{104}{}{请不要打扰罗伯特。他还没切水果当晚餐，因为他那愚蠢的难题。}
#{120}{}{It's been a while since somebody threw up in front of the house.}
{120}{}{有一段时间没人在房前呕吐了。}
#{121}{}{I'm so worked up today!}
{121}{}{我今天太兴奋了！}
#{122}{}{I haven't had so much energy since forever.}
{122}{}{从那以后我就再也没有这么多精力了。}
#{123}{}{It's like I'm ten years younger!}
{123}{}{好像我年轻了十岁！}
#{124}{}{I'm ready to show my power!}
{124}{}{我准备好展示我的力量了！}
#{125}{}{I got an immense appetite today.}
{125}{}{我今天胃口很大。}
#{126}{}{Actually, I'm hungry as hell.}
{126}{}{事实上，我饿得要命。}
#{127}{}{I'd eat a full roasted gecko... Or a half of it, at least.}
{127}{}{我会吃一只烤好的壁虎...至少是一半。}
#{128}{}{I should start running in the morning. Running away from stray dogs or something.}
{128}{}{我应该早上开始跑步。逃离流浪狗什么的。}
#{129}{}{Don't wanna sleep at all.}
{129}{}{根本不想睡觉。}
#{130}{}{Somebody vomited in front of the house again...}
{130}{}{又有人在房前呕吐...}
#{131}{}{I'd better start stocking up vocas till the next growing season.}
{131}{}{我最好在下一个生长季节开始储备歌喉。}
#{132}{}{The drug store is empty.}
{132}{}{药店是空的。}
#{133}{}{Something has to be done about this bloody flux.}
{133}{}{必须对这该死的变化采取措施。}
#{134}{}{A whole evening of shitting bricks awaits me.}
{134}{}{一整晚的屎砖在等着我。}
#{135}{}{I need to find a restroom... Oh, shit... Not anymore...}
{135}{}{我要找个洗手间...哦，该死...不再是了...}
#{136}{}{I don't feel so good... I need... Some rest...}
{136}{}{我感觉不太好...我需要...休息一下...}
#{137}{}{They say drinking beer helps with diarrhea.}
{137}{}{他们说喝啤酒有助于腹泻。}
#{138}{}{Such a big turd came out of me yesterday! You won't believe it!}
{138}{}{昨天我出了这么大的一坨屎！你不会相信的！}
#{139}{}{It's better to drink Nuka-Cola than water.}
{139}{}{喝努卡可乐比喝水好。}
#{140}{}{I heard that the factory's been sabotaged.}
{140}{}{我听说工厂被人破坏了。}
#{141}{}{The sabotage was clearly done at the hands of those bastards from Provo.}
{141}{}{破坏活动显然是由普罗沃那些混蛋干的。}
#{142}{}{Damn. If the factory shuts down, it won't be good for anyone.}
{142}{}{该死。如果工厂倒闭，对任何人都没有好处。}
#{143}{}{I hope the factory holds out...}
{143}{}{我希望工厂能坚持下去...}
#{144}{}{Be strong, Salt Lake, the factory will soon become history.}
{144}{}{坚强起来，盐湖城的工厂很快就会成为历史。}
#{145}{}{There's some real crap going on at the factory, man.}
{145}{}{工厂里真是一团糟，伙计。}
#{146}{}{My sib is going to quit his job at the factory.}
{146}{}{我姐姐要辞掉他在工厂的工作。}
#{147}{}{The factory is cursed.}
{147}{}{工厂被诅咒了。}
#{148}{}{Remember how great the factory once was?..}
{148}{}{还记得那个工厂曾经有多伟大吗？。。}
#{149}{}{When will the factory director sort it out already?}
{149}{}{厂长什么时候会处理好？}
#{150}{}{There's never been so many caravans coming in for Nuka-Cola.}
{150}{}{从来没有这么多大篷车来买努卡可乐。}
#{151}{}{Nuka-Cola is in great demand.}
{151}{}{努卡可乐的需求量很大。}
#{152}{}{Wow, so much fuss around the factory!}
{152}{}{哇，工厂里太吵了！}
#{153}{}{So many people near the factory, like there's some sort of performance.}
{153}{}{工厂附近这么多人，好像有什么表演。}
#{154}{}{Never thought I'd see something like this.}
{154}{}{从没想过我会看到这样的事。}
#{155}{}{Hail, the Nuka-Cola factory director! The king of all directors!}
{155}{}{你好，努卡可乐厂厂长！所有导演之王！}
#{156}{}{It seems they hired some good clerks at the factory.}
{156}{}{看来他们在工厂雇了一些好职员。}
#{157}{}{The factory is back on its feet all of a sudden.}
{157}{}{这家工厂突然恢复了生产。}
#{158}{}{What? Another Nuka-Cola caravan? How many can there be...}
{158}{}{什么？又一辆努卡可乐商队？能有多少...}
#{159}{}{They only go to Salt Lake for Nuka-Cola...}
{159}{}{他们只去盐湖城买努卡可乐...}
#{160}{}{In my opinion, those rednecks from Provo deserved it.}
{160}{}{在我看来，那些来自普罗沃的乡巴佬活该。}
#{161}{}{It wasn't easy, I reckon - Gilmore was one hell of a moosey.}
{161}{}{这并不容易，我想-吉尔摩是一个地狱的moosey。}
#{162}{}{Provo won't come anywhere near here.}
{162}{}{普罗沃不会靠近这里的。}
#{163}{}{That's how you deal with Provo, should've done so from the start!}
{163}{}{你就是这么对付普罗沃的，从一开始就应该这么做！}
#{164}{}{The Sheriff used his cunning on that one, founding someone to deal with Provo.}
{164}{}{警长在那件事上耍了他的诡计，找了个人来对付普罗沃。}
#{165}{}{I wonder, who did they hire to deal with Provo? Burton surely didn't soil his own hands.}
{165}{}{我想知道，他们雇谁来对付普罗沃？伯顿肯定没有弄脏自己的手。}
#{166}{}{Nah, the Sheriff wouldn't get his hands dirty, not even for those assholes.}
{166}{}{不，警长不会弄脏他的手，即使是那些混蛋。}
#{167}{}{Gilmore, you sonovabitch, burn in Hell!}
{167}{}{吉尔摩，你个臭婊子，去死吧！}
#{168}{}{That's more like it! A proper response!}
{168}{}{更像是这样！正确的回答！}
#{169}{}{Those Provo jerks have long had it coming!}
{169}{}{那些普罗沃混蛋早就受够了！}
#{170}{}{Something odd's going on at the factory.}
{170}{}{工厂里发生了一些奇怪的事情。}
#{171}{}{The factory could use a capable manager.}
{171}{}{工厂需要一个能干的经理。}
#{172}{}{When will the factory start working to its full capacity?}
{172}{}{工厂什么时候开始满负荷运转？}
#{180}{}{That thief has finally been caught! Serves him right.}
{180}{}{那个小偷终于被抓住了！他是对的。}
#{181}{}{Hail, the Sheriff of Salt Lake, Burton the Whip! A menace to all thieves!}
{181}{}{你好，盐湖城的治安官，伯顿的鞭子！对所有小偷都是一种威胁！}
#{182}{}{That thief's fate will be an example to all other thieves.}
{182}{}{那个小偷的命运将是所有其他小偷的榜样。}
#{183}{}{That thief had it coming!}
{183}{}{那个小偷让它来了！}
#{184}{}{That's right! He deserves time in the clink!}
{184}{}{这是正确的！他应该在监狱里呆上一段时间！}
#{185}{}{Now, the criminal activity here will die down for sure.}
{185}{}{现在，这里的犯罪活动肯定会平息。}
#{186}{}{I hope there'll be less robberies in the city now.}
{186}{}{我希望现在城里的抢劫案少一些。}
#{187}{}{With that thief caught, I feel kinda better.}
{187}{}{小偷被抓了，我感觉好多了。}
#{188}{}{Thievery will not be tolerated!}
{188}{}{偷窃是不能容忍的！}
#{189}{}{Be scared, thieves of Salt Lake!}
{189}{}{害怕吧，盐湖城的小偷！}
#{200}{}{When will they get that thief?}
{200}{}{他们什么时候能抓到那个小偷？}
#{201}{}{Did they catch the person who was robbing the vending machines?}
{201}{}{他们抓到抢劫自动售货机的人了吗？}
#{202}{}{The Nuka-Cola vending machines may be discontinued because of the thefts.}
{202}{}{努卡可乐自动售货机可能会因为失窃而停产。}
#{203}{}{Somebody's been persistently robbing the vending machines.}
{203}{}{有人一直在抢劫自动售货机。}
#{204}{}{Some slickster has robbed half the Nuka-Cola vending machines in the city.}
{204}{}{一些狡猾的家伙抢劫了城里一半的努卡可乐自动售货机。}
#{205}{}{Have you noticed that the Nuka-Cola vending machines have been emptied?}
{205}{}{你注意到努卡可乐自动售货机被清空了吗？}
#{210}{}{I'm not moving anywhere from this city!}
{210}{}{我不会离开这个城市的！}
#{211}{}{The city is now awesom-er than it was.}
{211}{}{这座城市现在比以前更令人敬畏了。}
#{212}{}{I can't believe my own eyes! Is this really the Salt Lake City?}
{212}{}{我不敢相信自己的眼睛！这真的是盐湖城吗？}
#{213}{}{I would never have thought that Salt Lake would become like this.}
{213}{}{我从没想过盐湖城会变成这样。}
#{214}{}{Remember how we started? Those bad times are in the past now...}
{214}{}{还记得我们是怎么开始的吗？那些糟糕的时光已经过去了...}
#{215}{}{Is this Salt Lake? It's like only yesterday it was a completely different place.}
{215}{}{这是盐湖吗？就好像昨天，那是一个完全不同的地方。}
#{216}{}{The city is growing, that's a fact.}
{216}{}{这座城市正在发展，这是事实。}
#{217}{}{Perhaps, I should move closer to the downtown.}
{217}{}{也许，我应该搬到离市区更近的地方。}
#{218}{}{The city's become more interesting. Much better than before.}
{218}{}{这个城市变得更有趣了。比以前好多了。}
#{219}{}{Hail, great Salt Lake!}
{219}{}{万岁，大盐湖！}
#{220}{}{I feel sad.}
{220}{}{我感到难过。}
#{221}{}{I wish I had been born in New Reno.}
{221}{}{我真希望我出生在新里诺。}
#{222}{}{I can't believe my own eyes! Goddamned Salt Lake City!..}
{222}{}{我不敢相信自己的眼睛！该死的盐湖城！。。}
#{223}{}{It seems there are fewer and fewer caravans these days.}
{223}{}{现在看来商队越来越少了。}
#{224}{}{Remember how we started? And now it all has come to this...}
{224}{}{还记得我们是怎么开始的吗？现在一切都变成这样了...}
#{225}{}{Is this Salt Lake? It's like only yesterday it was blossoming...}
{225}{}{这是盐湖吗？就好像昨天才开花...}
#{226}{}{The city is in a decline, even more so than before.}
{226}{}{这座城市正在衰退，甚至比以前更为严重。}
#{227}{}{Damn it all to hell!}
{227}{}{见鬼去吧！}
#{228}{}{I'd better relocate to Vegas.}
{228}{}{我最好搬到维加斯去。}
#{229}{}{No, no, I must find my way out of this place.}
{229}{}{不，不，我必须想办法离开这里。}
#{230}{}{They say that the ghost train has recently run through the city.}
{230}{}{他们说鬼魂列车最近在城里开过。}
#{231}{}{The neighbors say they heard the ghost train again.}
{231}{}{邻居们说他们又听到了幽灵火车的声音。}
#{232}{}{I wonder for how low will that ghost train keep rumbling around here.}
{232}{}{我不知道那辆幽灵火车在这里隆隆作响到底有多低。}
#{233}{}{Did anyone hear wheels rumbling yesterday at night?}
{233}{}{昨天晚上有人听到车轮隆隆作响吗？}
#{234}{}{I swear to God, I saw it running from 30 feet away!}
{234}{}{我对天发誓，我看到它从30英尺外跑出来！}
#{235}{}{It exists, I swear it!}
{235}{}{它存在，我发誓！}
#{236}{}{Everyone's already heard it!}
{236}{}{大家都听过了！}
#{237}{}{The ghost train was collecting souls in the wasteland again.}
{237}{}{幽灵火车又在荒地里收集灵魂。}
#{238}{}{So it happens - you live a life and then the ghost train takes you away.}
{238}{}{所以它发生了-你过着一种生活，然后幽灵火车把你带走。}
#{239}{}{The ghost train is collecting souls again.}
{239}{}{幽灵火车又在收集灵魂了。}
#{240}{}{I wouldn't want to cross paths with the ghost train.}
{240}{}{我可不想和幽灵火车过马路。}
#{241}{}{Oh, we all are going to board the ghost train at some point.}
{241}{}{哦，我们总有一天会登上幽灵列车的。}
#{300}{}{Hey, how's it going?}
{300}{}{嘿，怎么样？}
#{301}{}{I'm looking for a train driver. A long journey is ahead.}
{301}{}{我在找火车司机。前面还有很长的路要走。}
#{302}{}{Everything's fine.}
{302}{}{一切都很好。}
#{303}{}{You must be crazy! Nobody in the city will even dare to come close to the railway station. The Sheriff won't let it slide just like that! You won't find any here willing to go with you. Let's not talk about it anymore. I have enough problems as it is.}
{303}{}{你一定是疯了！城里没有人敢靠近火车站。警长不会让它就这样滑下去的！你在这里找不到愿意和你一起去的人。我们别再说了。我现在的问题已经够多了。}
#{304}{}{Shame.}
{304}{}{羞愧。}
