#{100}{}{You see a drunkard.}
{100}{}{你看见一个醉汉。}
#{101}{}{You see a dirty and very rude man, he definitely drinks too much alcohol.}
{101}{}{你看到一个又脏又粗鲁的人，他肯定喝了太多酒。}
#{102}{}{The family issue have been solved.}
{102}{}{家庭问题已经解决了。}
#{103}{}{Shit! This cretin killed his wife!}
{103}{}{倒霉！这个白痴杀了他的妻子！}
#{104}{}{What have you done?!}
{104}{}{你做了什么？！}
#{105}{}{This cretin is unredeemable. Your conversation with him only made his self-convictions stronger.}
{105}{}{这个白痴是不可挽救的。你和他谈话只会使他的自信心更加坚定。}
#{106}{}{You solved the family issue without blood and violence.}
{106}{}{你解决了家庭问题没有流血和暴力。}
#{107}{}{The drunkard is so scared that he will remember this lesson for long.}
{107}{}{那个醉汉太害怕了，他会记住这一课很久的。}
#{108}{}{Mark is scared of you so much that he won't dare to be rude to his wife.}
{108}{}{马克非常害怕你，他不敢对妻子无礼。}
#{109}{}{ }
{109}{}{ }
#{110}{}{Who the hell are you?!}
{110}{}{你到底是谁？！}
#{111}{}{Noooo! What have I done!?}
{111}{}{不！我做了什么！？}
#{112}{}{::cries hysterically::}
{112}{}{●歇斯底里地哭着：}
#{113}{}{NO!!! Bitch, how could you do this to me!?}
{113}{}{不！！！婊子，你怎么能这样对我！？}
#{114}{}{Not this! How could I?!!}
{114}{}{不是这个！我怎么能？！！}
#{115}{}{ALL OF THIS BECAUSE OF YOU!!!}
{115}{}{所有这一切都是因为你！！！}
#{116}{}{Leave me alone!}
{116}{}{别管我！}
#{117}{}{Well, hi, I guess...}
{117}{}{嗨，我想...}
#{118}{}{You're right man, we need to help each other... Maybe a glass of moonshine?}
{118}{}{你说得对，我们需要互相帮助...或许喝杯私酒？}
#{119}{}{You're right man. You want to freshen up with "Bloody Mary" with me?}
{119}{}{你说得对。你想和我一起喝“血腥玛丽”吗？}
#{120}{}{I don't get it! Who the hell are you?! And what the fuck do you want with my wife?!}
{120}{}{我不明白！你到底是谁？！你他妈要我老婆怎么办？！}
#{121}{}{She just told me that it's difficult for her to communicate with you. A woman must let the pain off her chest, right?}
{121}{}{她刚告诉我她很难和你沟通。一个女人必须让她胸口的疼痛消失，对吗？}
#{122}{}{With her - nothing. But she wants you dead. Say goodbye now!}
{122}{}{和她-什么都没有。但她想让你死。现在说再见！}
#{123}{}{Well, maybe... Bitches always complain, if they don't like something...}
{123}{}{嗯，也许...婊子们总是抱怨，如果他们不喜欢什么...}
#{124}{}{And what's the thing you don't like?}
{124}{}{你不喜欢什么？}
#{125}{}{Well you're not right. You must be kind and gentle to your wife.}
{125}{}{你说得不对。你必须对你的妻子和蔼可亲。}
#{126}{}{I will wreck you for this!.. [punch him in the face]}
{126}{}{我要毁了你！。。[打他的脸]}
#{127}{}{Whaaa?! Do I look like a child to you? You want to teach me about life? Why everyone hates me?! What did I do?! I just wanted to relax, have some beer, but everyone is lashing out on me! You, my wife, everyone!}
{127}{}{什么？！你觉得我像个孩子吗？你想教我生活吗？为什么大家都恨我？！我做了什么？！我只是想放松一下，喝点啤酒，但是每个人都在骂我！你，我的妻子，所有人！}
#{128}{}{Strange to hear this from a man who is busy doing nothing. Bye.}
{128}{}{从一个无所事事的人那里听到这个消息很奇怪。再见。}
#{129}{}{You ego is too big. I'm gonna cut it shorter... Together with your life!}
{129}{}{你太自负了。我要把它剪短...和你的生活在一起！}
#{130}{}{*Me*? I don't like everything! I try to explain it to her - a man has his lows, yes, doesn't have a job, yadda-yadda. And what does she say?! She's not being kind, or gentle, or feeding me something! If a man has his lows - he needs help!}
{130}{}{*我*？我不是什么都喜欢！我试着向她解释-一个男人有他的低谷，是的，没有工作，雅达雅达。她说什么？！她不友善，不温柔，也不喂我东西！如果一个人情绪低落，他需要帮助！}
#{131}{}{You're right, man, we should help each other...}
{131}{}{你说得对，伙计，我们应该互相帮助...}
#{132}{}{You're right, man, we should help each other... Want some beer?}
{132}{}{你说得对，伙计，我们应该互相帮助...想喝点啤酒吗？}
#{133}{}{And why don't you help yourself, if you're so smart? Why someone should save you?}
{133}{}{既然你这么聪明，为什么不自便呢？为什么有人要救你？}
#{134}{}{That's what I tell her... Ahh! You won't understand.}
{134}{}{我就是这么跟她说的...啊！你不会明白的。}
#{135}{}{Won't understand? Hmm...}
{135}{}{你不明白吗？Hmm...}
#{136}{}{[You had a heartfelt time with this cretin, using your knowledge in psychology. Something's changed in his mind. Hopefully, everything will be okay from now on.]}
{136}{}{[你用你的心理学知识和这个白痴在一起度过了一段由衷的时光。他改变了主意。希望从现在起一切都会好起来。】}
#{137}{}{Well, I gotta go. Take care!}
{137}{}{好吧，我得走了。当心！}
#{138}{}{[You had a heartfelt time with this cretin. He poured a ton of spiritual shit into you, but after a couple of weeks he'll have even more, no doubt...]}
{138}{}{[你和这个白痴一起度过了一段由衷的时光。他向你倾注了大量的精神垃圾，但几周后他会得到更多，毫无疑问……]}
#{150}{}{We just know each other, don't pay any attention.}
{150}{}{我们只是认识对方，别在意。}
#{151}{}{I'm her consciousness. I let her cry into my shoulder, when the need comes.}
{151}{}{我是她的意识。当需要的时候，我让她在我肩上哭泣。}
#{152}{}{I... Er... Your new neighbor, wanted to say hi.}
{152}{}{一、 ...呃...你的新邻居，想打个招呼。}
#{153}{}{From her - nothing. She wants you dead. Say goodbye!}
{153}{}{她-什么都没有。她要你死。说再见！}
#{154}{}{Who do you take me for?! *I* - am the man in this house! If you want to talk to my wife - first you ask my permission!}
{154}{}{你以为我是谁？！*我是这房子里的男人！如果你想和我妻子谈谈-首先你得征得我的同意！}
#{155}{}{Is she your property? Is that what you're saying?}
{155}{}{她是你的财产吗？你是这么说的吗？}
#{156}{}{Here I am, in front of you. Calm down, man.}
{156}{}{我在这里，在你面前。冷静点，伙计。}
#{157}{}{You scum! Don't you dare treat her like this!}
{157}{}{你这个人渣！你不敢这样对待她！}
#{158}{}{Why is that? [makes silly sarcastic face] Oooh! Will you beat me up for this?}
{158}{}{为什么？[做出愚蠢的讽刺的表情]哦！你会为此痛打我吗？}
#{159}{}{Do not get so upset, we can solve this peacefully!}
{159}{}{别这么生气，我们可以和平解决的！}
#{160}{}{Yes, it will be one more enemy in your life. Is this what you want?}
{160}{}{是的，这将是你生命中的又一个敌人。这就是你想要的吗？}
#{161}{}{That's right, and you will believe it very soon!}
{161}{}{没错，你很快就会相信的！}
#{162}{}{You're just a piece of shit! Piss off!}
{162}{}{你就是个混蛋！滚开！}
#{163}{}{Hey, easy!}
{163}{}{嘿，别紧张！}
#{164}{}{How dare you! Take this, you fuck!}
{164}{}{你怎么敢！拿着这个，你他妈的！}
#{165}{}{[Looks at you with stoned look, opening his mouth] To insult me in my own house! You are such a bitch!}
{165}{}{在我自己家里侮辱我！你真是个婊子！}
#{166}{}{[Grab his arm pin it behind him]}
{166}{}{[抓住他的胳膊把它钉在身后]}
#{167}{}{Hey! Hey! Take it easy! I didn't do anything!}
{167}{}{嘿！嘿！别紧张！我什么都没做！}
#{168}{}{A minute ago you was such a tough man. What happened?}
{168}{}{一分钟前你还真是个硬汉。怎么搞的？}
#{169}{}{What the hell do you want from me!?}
{169}{}{你到底想从我这里得到什么！？}
#{170}{}{Do not pretend to be a fool, filth! Your wife can't stand you!}
{170}{}{别装傻了，混蛋！你妻子受不了你！}
#{171}{}{Nothing. Dry, you drunk.}
{171}{}{没有什么。干，你喝醉了。}
#{172}{}{This is *my* wife! Who the fuck are you to...}
{172}{}{这是我的妻子！你他妈的是谁...}
#{173}{}{Shut up and listen to me!}
{173}{}{闭嘴，听我说！}
#{174}{}{You're right. She's your wife, I won't get between you.}
{174}{}{你说得对。她是你妻子，我不会插手你的。}
#{175}{}{Ugh...}
{175}{}{呃...}
#{176}{}{If I'll see that you hit your wife one more time - it will be the last day of your life!}
{176}{}{如果我看到你再打你妻子一次-那将是你生命的最后一天！}
#{177}{}{Okay, okay, I get it... I... I'll restrain myself, no problem!}
{177}{}{好吧，好吧，我明白了...一、 ...我会克制自己的，没问题！}
#{178}{}{We'll see, I'll check on your miserable family.}
{178}{}{我们走着瞧，我去看看你那可怜的家人。}
#{179}{}{I get it, okay!}
{179}{}{我明白了，好吧！}
#{180}{}{Good. Now get sober, you drunk!}
{180}{}{很好。清醒点，你这个酒鬼！}
#{181}{}{Do you know how many people I've killed while wandering the wastes?}
{181}{}{你知道我在荒野里游荡时杀了多少人吗？}
#{182}{}{[It seems this drunk is getting sober!] Er... }
{182}{}{[看起来这个醉汉已经清醒了！]呃...}
#{183}{}{?}
{183}{}{?}
#{184}{}{. And you can become }
{184}{}{. 你可以成为}
#{185}{}{-th.}
{185}{}{-第。}
#{186}{}{Wha... No! Noo! Why!? Why!?}
{186}{}{什么...不！不！为什么？为什么？}
#{187}{}{Do not pretend to be a fool, you know why.}
{187}{}{别装傻，你知道为什么。}
#{188}{}{Let's stop here. The hands are already reaching for the gun!}
{188}{}{我们到此为止。手已经够到枪了！}
#{189}{}{Just because I want to. And now - piss off.}
{189}{}{只是因为我想。现在-滚开。}
#{190}{}{Just like that? Kill a man, because he let some steam off!?}
{190}{}{就这样？杀了一个人，因为他放火了！？}
#{191}{}{Shut up, scum! There is not a single city were things like this are forgiven.}
{191}{}{闭嘴，人渣！没有一个城市能原谅这样的事情。}
#{192}{}{[Swallows] Am I really that low? That's why she hired you - to finish me? }
{192}{}{我真的那么低吗？所以她雇你来干掉我？}
#{193}{}{I'm doing this out of my good will.}
{193}{}{我这么做是出于好意。}
#{194}{}{That's right, she paid a decent amount of money.}
{194}{}{没错，她付了不少钱。}
#{195}{}{To be honest, she gave me poison, but I decided you don't deserve that.}
{195}{}{说实话，她给了我毒药，但我觉得你不配。}
#{196}{}{That's enough! You have the right for the last word! After which you die!}
{196}{}{够了！你有权说最后一句话！然后你就死了！}
#{197}{}{Hell NO! I do not want to die! [Falls to his knees] Forgive me! Sorry! I realized my mistakes! I will behave! I swear! Just give me one more chance! A-ah!!!}
{197}{}{他妈的不！我不想死！[跪下]原谅我！对不起的！我意识到我的错误了！我会守规矩的！我发誓！再给我一次机会！啊！！！}
#{198}{}{You don't deserve a second chance. You should have thought about it earlier. Now - die!}
{198}{}{你不该有第二次机会。你应该早点考虑的。现在-去死吧！}
#{199}{}{Well, okay. You will get your second chance. And it will be the last.}
{199}{}{好吧，好吧。你会有第二次机会的。这将是最后一次。}
#{200}{}{I will change! I swear!!!}
{200}{}{我会改变的！我发誓！！！}
#{201}{}{I'll check that. Now get dry, drunk.}
{201}{}{我查一下。现在干杯，喝醉。}
#{202}{}{I am a MAN! A man, not a rag!}
{202}{}{我是个男人！一个男人，不是一块破布！}
#{203}{}{Okay, okay, macho, calm down!}
{203}{}{好了，好了，男子汉，冷静！}
#{204}{}{A real man shouldn't beat women.}
{204}{}{真正的男人不应该打女人。}
#{205}{}{Now let's see what a man you are! Come out to fight, scum!}
{205}{}{现在让我们看看你是个怎样的人！出来战斗吧，人渣！}
#{206}{}{I am a MAN! A man, not a rag! This is my house! And you?! Who are YOU in my house?}
{206}{}{我是个男人！一个男人，不是一块破布！这是我的房子！和你？！你在我家是谁？}
#{207}{}{Sure, here's a bottle of Rotgut.}
{207}{}{当然，这是一瓶罗古特。}
#{208}{}{Sure, here's a bottle of "Bloody Mary".}
{208}{}{当然，这是一瓶“血腥玛丽”。}
#{209}{}{Sure, here's a bottle of beer.}
{209}{}{当然，这里有一瓶啤酒。}
#{210}{}{Oh, these bitches are always dropping tears. It's already pissing me off! Hey, you, come here, bitch! I want to eat! And I don't care there is nothing to eat!..}
{210}{}{哦，这些婊子总是掉眼泪。已经让我生气了！嘿，你，过来，婊子！我想吃！我不在乎没有东西吃！。。}
#{211}{}{Ah! Neighbors are good. Hey, idiot! Bring something to eat, we have guests! What? Oh, you whore, I said BRING FOOD! And some booze.}
{211}{}{啊！邻居们都很好。嘿，白痴！带点吃的，我们有客人！什么？哦，你这个婊子，我说带食物来！喝点酒。}
#{212}{}{Forget it pal, I have some on me. Bottoms up, yes?}
{212}{}{算了吧，伙计，我身上有些。干杯，好吗？}
#{213}{}{Ohh!!! My kind of guy! You should've started with this! Don't pay any attention to this bitch, let her cry... Well, what was it? A drink, huh?}
{213}{}{哦！！！我喜欢的那种人！你应该从这个开始！别理这个婊子，让她哭吧...那是什么？喝一杯，嗯？}
#{214}{}{[Pour poisoned moonshine]}
{214}{}{【倒毒月光】}
#{215}{}{Of course, here's a bottle of moonshine.}
{215}{}{当然，这是一瓶私酒。}
#{216}{}{Leave it, I will not drink with such a boor. I'm leaving.}
{216}{}{别管它，我不会和这样一个笨蛋喝酒的。我要走了。}
#{217}{}{Oh, hell, I'm sorry, I need to go! Bye!}
{217}{}{哦，见鬼，对不起，我得走了！再见！}
#{218}{}{Ha! We need neighbors like you. Always welcome, so to speak.}
{218}{}{哈！我们需要像你这样的邻居。可以说，总是受欢迎的。}
#{219}{}{[Next]}
{219}{}{[下一步]}
#{220}{}{[Drinks a glass of moonshine] Urgh! Good, damn!.. Hey, neighbor, why do you not drinking? That's not right! Come on, for my health!}
{220}{}{[喝一杯私酒]呃！很好，该死！。。嘿，邻居，你为什么不喝酒？这不对！来吧，为了我的健康！}
#{221}{}{Aha! For your health, neighbor!}
{221}{}{啊哈！为了你的健康，邻居！}
#{222}{}{Ugghh! Oh, that's was good one! You have a decent moonshine, neighbor... Why don't you drink? I don't get it.}
{222}{}{哎呀！哦，真是个好主意！你的私酒不错，邻居...你为什么不喝酒？我不明白。}
#{223}{}{Weak kidneys.}
{223}{}{虚弱的肾脏。}
#{224}{}{Ahh... I even sweat a little! You know, when I worked in the police, me and my partner were on a lead on a whorehouse once. Well, you know, we had to get drug dealers trust, so we took a few doses... Uh...}
{224}{}{啊...我甚至有点出汗！你知道，当我在警察局工作的时候，我和我的搭档曾经在一个妓院里有过线索。嗯，你知道，我们必须得到毒贩的信任，所以我们吃了一些药...Uh...}
#{225}{}{What is it?}
{225}{}{这是怎么一回事？}
#{226}{}{My partner had the bad stuff... He died after two days. Nobody could save him. And I... [cries]}
{226}{}{我的搭档有不好的东西...两天后他就死了。没人能救他。我...[哭声]}
#{227}{}{My friend, it seems you two were close?}
{227}{}{我的朋友，你俩好像很亲近？}
#{228}{}{We were almost like *brothers*! I still can't forget... Damn, give me another one! Drink with me this time, okay? At least a couple of sips.}
{228}{}{我们就像兄弟一样！我还是忘不了...该死，再给我一个！这次和我一起喝，好吗？至少喝几口。}
#{229}{}{Yeah, er, sure.}
{229}{}{是的，呃，当然。}
#{230}{}{[Drinks] Ughrr! Oh, it's so hot in here... Where did you get that stuff? Is this from Harry the Pigrat?}
{230}{}{[饮料]呃！哦，这里太热了...你从哪儿弄来的？这是猪鼠哈利送的吗？}
#{231}{}{Err, no, it's from a bar.}
{231}{}{呃，不，是酒吧的。}
#{232}{}{[Grabs the edge of the table and falls on his knee] Ohhhh... Got me good... [laughs] Even with Russian vodka it's not like that! Oh... What did you gave me?}
{232}{}{[抓住桌子的边缘跪下]哦...很好...[笑]即使是俄罗斯伏特加也不是这样！哦...你给了我什么？}
#{233}{}{...Uh, so what was it about Harry the Pigrat?}
{233}{}{…呃，那猪鼠哈利是怎么回事？}
#{234}{}{...Lives nearby, makes moonshine and sells it at the bar... [crawls on the floor tries to lay down] Listen... Sit here, while I... Uhh... Tell me... About yourself...}
{234}{}{…住在附近，做私酒在酒吧卖...[爬在地板上试图躺下]听着...坐在这里，我...呃...告诉我...关于你自己...}
#{235}{}{About me? You know, that doesn't matter.}
{235}{}{关于我？你知道，那没关系。}
#{236}{}{Why?..}
{236}{}{为什么？}
#{237}{}{You sleep, just sleep, and when you wake up - I'll tell you everything.}
{237}{}{你睡吧，睡吧，当你醒来的时候-我会告诉你一切。}
#{238}{}{...About yourself?}
{238}{}{…关于你自己？}
#{239}{}{About myself, about wandering around the wastes - I'll tell you about everything. Do not worry, sleep.}
{239}{}{关于我自己，关于在荒野中徘徊-我会告诉你一切。别担心，睡觉吧。}
#{240}{}{...You... Promise... You don't... Try to mess with... Me...}
{240}{}{…你...我保证...你不...试图搞乱...我...}
#{241}{}{[Keep silent]}
{241}{}{[保持沉默]}
#{242}{}{So... I... Want... To hear it...}
{242}{}{所以...一、 ...想要...听到它...}
#{243}{}{[This was his last breath]}
{243}{}{[这是他的最后一口气]}
#{244}{}{You acted low, poisoning this drunkard, but all the better for the world.}
{244}{}{你表现得很低调，毒死了这个酒鬼，但对世界来说一切都好。}
#{245}{}{Why do you treat her like she's your property?}
{245}{}{你为什么把她当成你的财产？}
#{1104}{}{What have you done?!}
{1104}{}{你做了什么？！}
#{1152}{}{I... Err... Your new neighbor, wanted to say hi.}
{1152}{}{一、 ...呃...你的新邻居，想打个招呼。}
#{1172}{}{This is *my* wife! Who the fuck are you to...}
{1172}{}{这是我的妻子！你他妈的是谁...}
#{1181}{}{Do you know how many people I've killed while wandering the wastes?}
{1181}{}{你知道我在荒野里游荡时杀了多少人吗？}
#{1195}{}{To be honest, she gave me poison, but I decided you don't deserve that.}
{1195}{}{说实话，她给了我毒药，但我觉得你不配。}
#{1206}{}{I am a MAN! A man, not a rag! This is my house! And you?! Who are YOU in my house?}
{1206}{}{我是个男人！一个男人，不是一块破布！这是我的房子！和你？！你在我家是谁？}
#{1220}{}{[Drinks a glass of moonshine] Urgh! Good, damn!.. Hey, neighbor, why do you not drinking? That's not right! Come on, for my health!}
{1220}{}{[喝一杯私酒]呃！很好，该死！。。嘿，邻居，你为什么不喝酒？这不对！来吧，为了我的健康！}
#{1222}{}{Ugghh! Oh, that's was good one! You have a decent moonshine, neighbor... Why don't you drink? I don't get it.}
{1222}{}{哎呀！哦，真是个好主意！你的私酒不错，邻居...你为什么不喝酒？我不明白。}
#{1232}{}{[Grabs the edge of the table and falls on his knee] Ohhhh... Got me good... [laughs] Even with Russian vodka it's not like that! Oh... What did you gave me?}
{1232}{}{[抓住桌子的边缘跪下]哦...很好...[笑]即使是俄罗斯伏特加也不是这样！哦...你给了我什么？}
