#{10}{}{ }
{10}{}{ }
#{100}{}{You see a hobo.}
{100}{}{你看到一个流浪汉。}
#{101}{}{You see a messy and uncombed man.}
{101}{}{你看到一个邋遢的男人。}
#{102}{}{Eh... Thanks, but don't do this again.}
{102}{}{呃...谢谢，但别再这样了。}
#{103}{}{Thank you, kind person!}
{103}{}{谢谢你，善良的人！}
#{104}{}{Uh... Do you have a sandwich? I have troubles with winds with this one...}
{104}{}{Uh...有三明治吗？我有风的麻烦...}
#{105}{}{You drove the annoying beggar from the city.}
{105}{}{你把那个讨厌的乞丐赶出了城市。}
#{106}{}{You helped the hobo rise on his feet.}
{106}{}{你帮助流浪汉站起来。}
#{150}{}{Hey, kind person!}
{150}{}{嘿，好人！}
#{151}{}{Help please!}
{151}{}{救命啊！}
#{152}{}{Give food! I haven't eaten two days!}
{152}{}{给我食物！我两天没吃东西了！}
#{153}{}{Spare some change?}
{153}{}{给点零钱？}
#{154}{}{Lend till the salary?}
{154}{}{借到薪水？}
#{155}{}{I need medicines! Really!}
{155}{}{我需要药！真正地！}
#{156}{}{Do not leave a person in trouble!}
{156}{}{不要给人留下麻烦！}
#{157}{}{Please, give some to eat!}
{157}{}{请给点吃的！}
#{158}{}{I know you'll help unhealthy one.}
{158}{}{我知道你会帮助一个不健康的人。}
#{159}{}{Sorry, would you any spare change?}
{159}{}{对不起，您有零钱吗？}
#{160}{}{Where you go, kind person?! What about me?!}
{160}{}{你去哪，好人？！我呢？！}
#{200}{}{Could kind person help crippled one in his unhappy life? Please, with a bun at least...}
{200}{}{善良的人能帮助残废的人度过不幸的一生吗？拜托，至少要一个小面包...}
#{201}{}{Well then! Come on, let's dine in this cafe like normal people. Let's go!}
{201}{}{那好吧！来吧，让我们像正常人一样在这家咖啡馆吃饭。走吧！}
#{202}{}{[Give sandwich]}
{202}{}{[给我三明治]}
#{203}{}{[Give fruit]}
{203}{}{[送水果]}
#{204}{}{[Give iguana-on-a-stick]}
{204}{}{[给鬣蜥一根棍子]}
#{205}{}{Scram, filth!}
{205}{}{滚开，混蛋！}
#{206}{}{[Give dry meal]}
{206}{}{[给干粮]}
#{207}{}{[Give 10$]}
{207}{}{[给10美元]}
#{208}{}{Sorry, don't have money right now.}
{208}{}{对不起，我现在没钱。}
#{209}{}{Oh! Kind! Kind! Kind person! Thanks! Thank you! I'll never forget you!}
{209}{}{哦！善良！善良！善良的人！谢谢！谢谢您！我永远不会忘记你！}
#{210}{}{You're welcome, pal!}
{210}{}{不客气，伙计！}
#{211}{}{Oh! Kind! Kind! Kind person! Thanks! Thank you for everything! You're so kind, I don't even know how to express it! [you see tears of joy in the beggar's eyes]}
{211}{}{哦！善良！善良！善良的人！谢谢！谢谢你所做的一切！你真好，我都不知道怎么表达！[你看到乞丐眼中的喜悦之泪]}
#{212}{}{No problem, pal! See, life's getting better. Bye.}
{212}{}{没问题，伙计！看，生活越来越好了。再见。}
#{213}{}{Give up on this life, pal! Sheriff offers you a job. Sure, payment's not much, but enough to live. You just go to him and chat. Say that I've sent you. Okay?}
{213}{}{放弃这种生活，伙计！警长给你一份工作。当然，报酬不多，但足以维持生活。你只要去找他聊聊。说是我派你来的。可以？}
#{214}{}{Give up on this life, pal! I've got stable and easy job for you. You can do it. See that shop? They need a man to work in a storeroom. Say that I've sent you. Okay?}
{214}{}{放弃这种生活，伙计！我有一份稳定而轻松的工作给你。你能做到的。看到那家商店了吗？他们需要一个人在储藏室工作。说是我派你来的。可以？}
#{215}{}{What? Sheriff himself? [The beggar opens his mouth in amazement] Oh! Mister Whip wants to hire me! Kind! Kind person! I'm so happy! So happy!}
{215}{}{什么？警长本人？[乞丐惊奇地张开嘴]哦！维普先生想雇我！善良！善良的人！我太高兴了！太高兴了！}
#{216}{}{Come on, it was easy...}
{216}{}{拜托，这很简单...}
#{217}{}{Sheriff - he's fair one. He won't left me bullied! Not like some others!}
{217}{}{警长-他很漂亮。他不会让我受欺负的！不像其他人！}
#{218}{}{And who's bullying you?}
{218}{}{谁在欺负你？}
#{219}{}{No one! Just saying... There was one bandit wandered around the cafe. If you stumble upon him, don't even talk. Well, I'm off to sheriff, yes?}
{219}{}{没有人！只是说...有一个强盗在咖啡馆里闲逛。如果你偶然发现他，甚至不要说话。好吧，我要去见警长，是吗？}
#{220}{}{Yeah, now go. Take care.}
{220}{}{是的，现在走吧。当心。}
#{221}{}{Really?! They'll feed me? Oh! Kind! Kind person! I'm happy! So happy! Thank you! Thanks!}
{221}{}{真正地？！他们会喂我吗？哦！善良！善良的人！我很高兴！太高兴了！谢谢您！谢谢！}
#{222}{}{Come on, it was easy... Take care.}
{222}{}{拜托，这很简单...当心。}
#{223}{}{(Just think about how people can change! You washed, brushed, fed and amused this beggar, after which he even changed his face. If he were given a push to evolve, he would become a respectable citizen in the town.)}
{223}{}{（想想人们是如何改变的！你洗，刷，喂，逗这个乞丐，之后他甚至改变了他的脸。如果给他一个发展的动力，他将成为镇上受人尊敬的公民。）}
#{224}{}{[Leave]}
{224}{}{[离开]}
#{225}{}{[Beggar continues to stand by and wait, apparently insults are usual thing for him]}
{225}{}{【乞丐继续袖手旁观，显然侮辱对他来说是常事】}
#{226}{}{Alright, trash-humper, leave this place until I hit you right in the eye!}
{226}{}{好吧，垃圾汉普，离开这里直到我打到你的眼睛！}
#{227}{}{Uh, okay sorry, just came out that way... So what did you want?}
{227}{}{呃，好吧，抱歉，刚才从那边出来...那你想要什么？}
#{228}{}{[Ignore him and go about your business]}
{228}{}{[别理他，继续你的事]}
#{229}{}{Good person, could you find at least a slice of bread?}
{229}{}{好人，你能至少找一片面包吗？}
#{230}{}{Hm, you know what - just get out of my way!}
{230}{}{嗯，你知道吗-别挡我的路！}
#{231}{}{[Beggar continues to stay with lowered look]}
{231}{}{【乞丐继续低着头】}
#{232}{}{Well then, I've got enough of you! You want to fight, yes? You want it? Come on! Come here! Heya!!!}
{232}{}{那么，我受够你了！你想打架，是吗？你想要吗？加油！过来！呵呵！！！}
#{233}{}{Sorry, good person, I... I just wanted to ask...}
{233}{}{对不起，好人，我...我只是想问...}
#{234}{}{You deaf, right? I'll explain one last time - get out of town or I'll cut your throat!}
{234}{}{你聋了，对吧？我再解释最后一次-滚出去，不然我就割断你的喉咙！}
#{235}{}{Hell, maybe I need to give some grub, so you could get away?}
{235}{}{见鬼，也许我该给你点吃的，这样你就可以走了？}
#{236}{}{Uh, okay, buddy, let's not argue, there's enough room in the city. Bye.}
{236}{}{呃，好吧，伙计，我们别争论了，城里有足够的空间。再见。}
#{237}{}{Oh, yes, good person... Kind person won't ever see me, I get you...}
{237}{}{哦，是的，好人...善良的人永远见不到我，我明白你...}
#{238}{}{If you enter the town again - *no one* will ever see you besides rats on the junkyard! Well then, get out of here!}
{238}{}{如果你再进城-*除了垃圾场上的老鼠，没人会看到你！那么，离开这里！}
#{239}{}{That's better. Now I'm the sheriff here so don't argue and leave the town already.}
{239}{}{这样更好。现在我是这里的治安官，所以不要争吵，已经离开这个镇了。}
#{240}{}{Yes, the sheriff says - so be it... Sheriff won't see me and I won't interfere with sheriff, I'll go.}
{240}{}{是的，警长说-就这样吧...警长见不到我，我也不干涉警长，我去。}
#{241}{}{Move your ass, miserable fuck!}
{241}{}{快走，可悲的混蛋！}
#{242}{}{Yes, okay, Sometimes I get angry, but then I get back to normal. You can stay in town, but do not come across my eyes!}
{242}{}{是的，好吧，有时候我会生气，但后来我又恢复正常了。你可以呆在城里，但不要碰到我的眼睛！}
#{243}{}{Yeah, bye.}
{243}{}{好的，再见。}
#{1211}{}{Oh! Kind! Kind! Kind lady! Thanks! Thank you for everything! You're so kind, I don't even know how to express it! [you see tears of joy in the beggar's eyes]}
{1211}{}{哦！善良！善良！善良的女士！谢谢！谢谢你所做的一切！你真好，我都不知道怎么表达！[你看到乞丐眼中的喜悦之泪]}
