#{100}{}{You see cisterns.}
{100}{}{你看到蓄水池了。}
#{101}{}{You see large tanks with a smelly concoction that will soon become Nuka-Cola.}
{101}{}{你会看到一个大罐，里面有一种很难闻的混合物，很快就会变成努卡可乐。}
#{102}{}{You committed a dangerous act of sabotage at the Nuka-Cola factory.}
{102}{}{你在努卡可乐厂犯下了危险的破坏行为。}
#{103}{}{Nuka-Cola factory has suffered a diversion! Not without your help.}
{103}{}{努卡可乐厂遭遇分流！没有你的帮助不行。}
#{104}{}{This liquid has already been poisoned, re-injection will do nothing.}
{104}{}{这种液体已经中毒了，再注射也无济于事。}
#{105}{}{You have poisoned the tank with the liquid, but it's not enough. Poison another one.}
{105}{}{你用这种液体毒死了坦克，但这还不够。毒死另一个。}
#{106}{}{You see large tanks with a smelly concoction that could be Nuka-Cola, if you haven??t poisoned it.}
{106}{}{你会看到一个大罐，里面有一种很难闻的混合物，如果你没有下毒的话，可能是努卡可乐。}
#{107}{}{You've already poisoned enough liquid, do not waste the poison in vain.}
{107}{}{你已经下了足够的毒，不要白白浪费。}
#{108}{}{Done!}
{108}{}{完成！}
#{109}{}{This one is done}
{109}{}{这个已经完成了}
