#{100}{}{You see a drunkard.}
{100}{}{你看见一个醉汉。}
#{101}{}{You see an ordinary passerby who's had a little too much at the bar.}
{101}{}{你看到一个普通的过路人在酒吧喝多了。}
#{102}{}{Stealing from the drunk has a negative effect on your karma.}
{102}{}{从醉汉身上偷东西对你的业力有负面影响。}
#{103}{}{Hey you! ...I'm gonna!..}
{103}{}{嘿你...我要去！。。}
#{104}{}{Get... Out of the way...}
{104}{}{获取...让开...}
#{105}{}{Woah, the ground's moving!}
{105}{}{哇，地面在移动！}
#{110}{}{::hurrgh::}
{110}{}{●呼噜声：}
#{111}{}{This drunkard can barely stand. You don't matter much to him. Nothing does.}
{111}{}{这个酒鬼几乎站不住了。你对他没什么关系。什么也做不了。}
