#{100}{}{You see Theodore Wright.}
{100}{}{你看到西奥多·赖特了。}
#{101}{}{You see the rich owner of the local slums and a major authority in Reno.}
{101}{}{你会看到当地贫民窟的富人和里诺的一个主要权威。}
#{102}{}{Give me a chance to get to my table, you troglodyte!}
{102}{}{给我一个机会到我的桌子上去，你这个笨蛋！}
#{103}{}{*Zzzzzz...*}
{103}{}{*Zzzzzz*}
#{104}{}{Better not wake him right now.}
{104}{}{最好现在不要叫醒他。}
#{105}{}{Come back at a civilized hour.}
{105}{}{准时回来。}
#{106}{}{Thief! Guards! Thiiief!!!}
{106}{}{小偷！警卫！Thiiief！！！}
#{107}{}{Huh?! Wha... *mumbles*}
{107}{}{呵呵？！什么。。。*喃喃自语*}
#{110}{}{::stretches::}
{110}{}{●拉伸：}
#{111}{}{...hey! What the...}
{111}{}{……嘿！怎么了。。。}
#{112}{}{::rolls over::}
{112}{}{●翻滚：}
#{113}{}{Hrrmf...}
{113}{}{Hrrmf。。。}
#{115}{}{One more good day in hell.}
{115}{}{又是地狱里的好日子。}
#{116}{}{Maybe tonight I'll actually sleep...}
{116}{}{也许今晚我真的会睡。。。}
#{130}{}{Keep your distance. I don't know what's wrong with your face, but even if it's not contagious, I don't want it close to me.}
{130}{}{保持距离。我不知道你的脸怎么了，但即使没有传染性，我也不想让它靠近我。}
#{131}{}{I understand, Mr. Wright. We can talk from here.}
{131}{}{我明白，赖特先生。我们可以在这里谈。}
#{132}{}{[Sneeze in his direction] Oh, Mr. Wright, I've always wanted to shake your hand.}
{132}{}{[朝他打喷嚏]哦，赖特先生，我一直想和你握手。}
#{133}{}{I'm surprised such an... Important person has the time to see me. How can I "help" the only officer of the law around, Sheriff?}
{133}{}{我很惊讶这样一个。。。重要人物有时间见我。我怎样才能“帮助”唯一的执法人员，警长？}
#{134}{}{Everyone needs something from me... What brings you here?}
{134}{}{每个人都需要我的帮助。。。什么风把你吹来了？}
#{135}{}{Have you completed my... Errand?}
{135}{}{你完成我的。。。差事？}
#{136}{}{I'm glad to see you. But don't forget your place.}
{136}{}{很高兴见到你。但别忘了你住的地方。}
#{137}{}{Nothing.}
{137}{}{没有什么。}
#{138}{}{I just wanted to say hello.}
{138}{}{我只是想打个招呼。}
#{139}{}{I should be on my way.}
{139}{}{我该上路了。}
#{140}{}{Mr. Wright, I'm looking for work, and I've heard a lot about you. Maybe we can help each other?}
{140}{}{赖特先生，我在找工作，我听说过很多关于你的事。也许我们可以互相帮助？}
#{141}{}{[He looks you up and down, thinking] Do you know what's more important in this city than a fat wallet or a quick gun?}
{141}{}{[他上下打量着你，心想]你知道在这个城市，什么比一个大钱包或一把快手枪更重要吗？}
#{142}{}{What, Mr. Wright?}
{142}{}{什么，赖特先生？}
#{143}{}{I'm not in the mood for riddles. Do you have work, yes or no?}
{143}{}{我没心情猜谜语。你有工作吗？有还是没有？}
#{144}{}{Yes, Mr. Wright. It's reputation, isn't it?}
{144}{}{是的，赖特先生。这是名誉，不是吗？}
#{145}{}{Wilful ignorance. [he scoffs] Get out.}
{145}{}{故意的无知。[他嘲笑]出去。}
#{146}{}{[Get out.]}
{146}{}{[出去]}
#{147}{}{Reputation. And regardless of your wallet or gun, reputation is something you don't have. In my slums, no one knows you and no one recommends you. And I trust my people. If you want a job, show me your work... Where it counts.}
{147}{}{名誉。不管你的钱包和枪，名声都是你所没有的。在我的贫民窟，没有人认识你，也没有人推荐你。我信任我的人民。如果你想找份工作，给我看看你的工作。。。重要的地方。}
#{148}{}{You really haven't heard of me, Mr. Wright? I've done a lot in Reno.}
{148}{}{你真的没听说过我吗，赖特先生？我在雷诺做了很多。}
#{149}{}{Okay, Mr. Wright.}
{149}{}{好的，赖特先生。}
#{150}{}{Tch. I could care less how others in New Reno see you. My empire is here, in the slums.}
{150}{}{Tch公司。我不在乎新里诺的人怎么看你。我的帝国在这里，在贫民窟里。}
#{151}{}{Hmm... [he studies you again, as if he's seeing something new, then nods] Perhaps you do have potential. My people speak highly of you.}
{151}{}{隐马尔可夫模型。。。[他再次研究你，好像他看到了新的东西，然后点头]也许你确实有潜力。我的人民对你评价很高。}
#{152}{}{Does that mean you you have work for me?}
{152}{}{那是不是意味着你有工作给我？}
#{153}{}{[He raises an eyebrow] You think faster than most in this city. And yes, I'm speaking of reputation. Tell me, who can recommend you as a reliable employee?}
{153}{}{[他扬起眉毛]你比这个城市的大多数人想得都快。是的，我说的是名誉。告诉我，谁能推荐你做一个可靠的员工？}
#{154}{}{People in the slums have a lot of good things to say about me.}
{154}{}{贫民窟里的人对我有很多好话要说。}
#{155}{}{I've been active in other parts of town. Surely you've heard of me already.}
{155}{}{我在镇上其他地方也很活跃。你肯定已经听说过我了。}
#{156}{}{Uh, well, I'm kind of new in town, and...}
{156}{}{呃，我是新来的，而且。。。}
#{157}{}{Then we have nothing to discuss. There's the door.}
{157}{}{那我们就没什么可谈的了。门在那儿。}
#{158}{}{[Walk away.]}
{158}{}{[走开。]}
#{159}{}{[He nods] Perhaps you do have potential.}
{159}{}{[他点头]也许你确实有潜力。}
#{160}{}{I'll make one thing clear. The Wrights are a dignified family, and don't think this makes you one of us. You work for us, you do not *help* us. Don't you even dare use that word. We're not beggars, and we don't need charity. Do you understand me?}
{160}{}{我要说清楚一件事。莱特一家是有尊严的家庭，别以为这会让你成为我们中的一员。你为我们工作，却不帮助我们。你连那个词都不敢用。我们不是乞丐，也不需要施舍。你明白我的意思吗？}
#{161}{}{I understand, Mr. Wright.}
{161}{}{我明白，赖特先生。}
#{162}{}{Very well. [he leans back in his chair, interlacing his fingers on his stomach] I have some errands for a man like you...someone from out of town. I pay well, provided the job is completed correctly.}
{162}{}{很好。[他靠在椅子上，手指交叉放在肚子上]我有一些事情要给你这样的人…一个从外地来的人。我薪水很高，只要工作完成得正确。}
#{163}{}{I'm listening.}
{163}{}{我在听。}
#{164}{}{I heard of your prospector's contract. You're not satisfied with their performance?}
{164}{}{我听说你的探矿者的合同。你对他们的表现不满意？}
#{165}{}{I am not. They disappear for months, miss their deadlines, and think they can get away with it? No, they're done. I'm looking for a professional. Someone reliable. Someone... Loyal.}
{165}{}{我不是。他们消失了好几个月，错过了最后期限，以为自己能逃脱惩罚？不，他们完了。我在找专业人士。可靠的人。某人。。。忠诚。}
#{166}{}{I can be that professional.}
{166}{}{我可以那么专业。}
#{167}{}{Er, good luck with that. Bye.}
{167}{}{呃，祝你好运。再见。}
#{168}{}{Don't forget your place here! Hrm... [he massages the back of his neck]}
{168}{}{别忘了你在这儿的位置！人力资源管理。。。[他按摩后颈]}
#{169}{}{I'm glad we met, sheriff. But don't forget who you work for.}
{169}{}{很高兴见到你，警长。但别忘了你为谁工作。}
#{170}{}{Go to Uranium City. I want a full report on the mine's status...MY mine's status.}
{170}{}{去铀城。我要一份完整的矿井状况报告…我的矿井状况。}
#{171}{}{I'll investigate and return, Mr. Wright.}
{171}{}{我会调查并回来的，赖特先生。}
#{172}{}{You'll be paid when the job is done. You can go now.}
{172}{}{工作完成后你会得到报酬的。你现在可以走了。}
#{173}{}{[Walk away.]}
{173}{}{[走开。]}
#{174}{}{About that job...}
{174}{}{关于那份工作。。。}
#{175}{}{Why didn't you send your people there earlier?}
{175}{}{你为什么不早点派人去？}
#{176}{}{I need my people here... But that's not your concern.}
{176}{}{我需要我的人。。。但那不是你的问题。}
#{177}{}{I understand.}
{177}{}{我理解。}
#{180}{}{I'm listening.}
{180}{}{我在听。}
#{181}{}{Uh...actually, nothing.}
{181}{}{呃…实际上，没什么。}
#{182}{}{Then get back to work! Don't test my patience. I could have a line of people wanting your job leading out my door all the way to Luciano's ranch!}
{182}{}{那就回去工作吧！别考验我的耐心。我可以让一队人想要你的工作，把我的门一直引到卢西亚诺的农场！}
#{183}{}{[Walk away.]}
{183}{}{[走开。]}
#{184}{}{I'm back from Uranium City.}
{184}{}{我从铀城回来了。}
#{185}{}{Tell me everything.}
{185}{}{告诉我一切。}
#{186}{}{A local named Nelson took over. He's trying to take your mine.}
{186}{}{一个叫纳尔逊的当地人接管了。他想拿走你的我的。}
#{187}{}{A shady guy from the Hub is trying to seize your mine. He seems serious... And dangerous.}
{187}{}{一个黑鬼想抢你的地雷。他看起来很严肃。。。而且很危险。}
#{188}{}{All work has stopped and most of the miners have skipped town. People are questioning who really owns the mine and who's going to get it running again.}
{188}{}{所有的工作都停止了，大多数矿工都逃走了。人们在质疑谁真正拥有了这个矿，谁又会让它重新运转起来。}
#{189}{}{Some sort of dangerous mutant in the mine has scared off the workers. Most of them have left town.}
{189}{}{矿井里某种危险的变种人吓跑了工人。他们大多数人都离开了城里。}
#{190}{}{What else do you know?}
{190}{}{你还知道什么？}
#{191}{}{That's all for now. I'll be back when I learn more.}
{191}{}{现在就这些。当我了解更多的时候我会回来的。}
#{192}{}{Enough. I know enough to plan my next steps. I can't afford to lose the mine... But first, your payment: $200.}
{192}{}{够了。我有足够的知识来计划我的下一步。我不能失去矿。。。但首先，你的报酬是200美元。}
#{193}{}{That's it? Mr. Wright, be honest. You're broke, aren't you?}
{193}{}{就这样？赖特先生，说实话。你破产了，不是吗？}
#{194}{}{Thank you, Mr. Wright! I appreciate it!}
{194}{}{谢谢你，赖特先生！我很感激！}
#{195}{}{There'll be more coming, if you last that long. You've shown you can be trusted with more work.}
{195}{}{如果你坚持那么久，还会有更多的人来的。你已经证明你可以信任更多的工作。}
#{196}{}{I understand, Mr. Wright. What was that about more work?}
{196}{}{我明白，赖特先生。更多的工作是什么意思？}
#{197}{}{Watch your tongue! Don't forget your place here. But... This mob war has strained New Reno's economy to the breaking point. It's robbed my family of almost everything we've earned. I worked years for what I have. I *will not* allow it to be taken from me.}
{197}{}{小心你的舌头！别忘了你在这儿的位置。但是。。。这场暴民战争使新雷诺的经济紧张到了崩溃的地步。它夺走了我们家几乎所有的收入。我为我所拥有的东西工作了好几年。我不会让它从我身边夺走。}
#{198}{}{I need leverage to ensure that mine remains MINE. The mine will need resources, but chief among them are explosives. The stores there must be exhausted by now.}
{198}{}{我需要杠杆来确保我的仍然是我的。这个矿需要资源，但主要是炸药。那里的商店现在一定已经用完了。}
#{199}{}{Where will you get explosives?}
{199}{}{你在哪能买到炸药？}
#{200}{}{I contracted a couple of prospectors to retrieve explosives from an old military base. Instead, they... Disappeared. Now I must decide the fate of their families. Do you understand the... Subtlety of the situation?}
{200}{}{我雇了几个探矿者从一个旧军事基地取回炸药。相反，他们。。。消失。现在我必须决定他们家庭的命运。你明白。。。情况的微妙之处？}
#{201}{}{What should I do, Mr. Wright?}
{201}{}{我该怎么办，赖特先生？}
#{202}{}{I don't care how, but I want that contract fulfilled. Find out what happened to my prospectors.}
{202}{}{我不在乎怎么做，但我希望合同能履行。看看我的探矿者怎么了。}
#{203}{}{I'm on it, Mr. Wright.}
{203}{}{我会的，赖特先生。}
#{204}{}{Well, I'll see what I can do.}
{204}{}{好吧，我看看我能做什么。}
#{205}{}{First, talk to the Gates family. They must know something. They live in the slums in front of the hotel.}
{205}{}{首先，和盖茨一家谈谈。他们一定知道些什么。他们住在旅馆前面的贫民窟里。}
#{206}{}{I'm on my way.}
{206}{}{我在路上。}
#{207}{}{[He fixes you with a stare of contempt and disgust] I don't employ rapists and child-killers. I can't decide whether to have my guards shoot you, or to have the pleasure of doing so myself. You should leave before I make up my mind.}
{207}{}{[他用蔑视和厌恶的目光盯着你]我不雇佣强奸犯和儿童杀手。我不能决定是让我的警卫开枪打死你，还是让我自己高兴地开枪打死你。你应该在我下定决心之前离开。}
#{208}{}{[Walk away silently.]}
{208}{}{[静静地走开。]}
#{210}{}{About those prospectors...}
{210}{}{关于那些探矿者。。。}
#{211}{}{Where are my explosives?}
{211}{}{我的炸药呢？}
#{212}{}{They're already in Uranium City. Nelson has them.}
{212}{}{他们已经在铀城了。尼尔森有。}
#{213}{}{I have them right here, Mr. Wright.}
{213}{}{我就在这儿，赖特先生。}
#{214}{}{I don't know. But I found the prospectors.}
{214}{}{我不知道。但我找到了探矿者。}
#{215}{}{Stop wasting my time! All I care about are those explosives. It doesn't matter who gets them, as long as they get them to *me*!}
{215}{}{别再浪费我的时间了！我只关心那些炸药。不管是谁得到的，只要他们把它们交给我就行了！}
#{216}{}{I'll do it, then.}
{216}{}{那我就做。}
#{217}{}{They're what?! You imbecile! Those explosives are my leverage *against* that town! Get them back at any cost! If you have to kill this Nelson, do it. Now go. The next time I see you, you had better have my explosives.}
{217}{}{他们是什么？！你这个笨蛋！那些炸药是我对付那个城镇的筹码！不惜一切代价把他们弄回来！如果你非要杀了这个尼尔森，就杀了他。现在走吧。下次我见到你的时候，你最好拿着我的炸药。}
#{218}{}{[Walk away.]}
{218}{}{[走开。]}
#{219}{}{Finally. So long as I have these, I can dictate my terms to the miners there. [he hands the explosives to a guard] Now for the matter of payment. Who retrieved these explosives from the military base?}
{219}{}{最后。只要我有这些，我就可以向那里的矿工口授条件。[他把炸药交给一个警卫]现在是关于付款的问题。谁从军事基地取回了这些炸药？}
#{220}{}{The prospectors, Mr. Wright. They're the ones that retrieved the explosives. They only asked me to deliver it because they're afraid of you.}
{220}{}{探矿者，赖特先生。是他们找回了炸药。他们让我送是因为怕你。}
#{221}{}{I had to do everything, Mr. Wright. I even have the contract here. It's only fair you pay me.}
{221}{}{我什么都得做，赖特先生。我这里甚至还有合同。你付我钱才公平。}
#{222}{}{Hmm. You could have lied, told me you retrieved them from that base, but you didn't. I appreciate an honest man. Anyway, here's your pay for the assignment.}
{222}{}{嗯。你本可以撒谎，告诉我你从那个基地找回了他们，但你没有。我欣赏一个诚实的人。不管怎样，这是你的任务报酬。}
#{223}{}{Thank you, Mr. Wright.}
{223}{}{谢谢你，赖特先生。}
#{224}{}{That doesn't surprise me. I'm surrounded by incompetence. I'll have to take measures against the prospectors' families. You'll be paid appropriately for your work.}
{224}{}{我一点也不惊讶。我被无能包围着。我得对探矿者的家人采取措施。你的工作会得到适当的报酬。}
#{225}{}{I had to do everything, Mr. Wright. It's only fair you pay me.}
{225}{}{我什么都得做，赖特先生。你付我钱才公平。}
#{226}{}{You could be lying to me. Perhaps they retrieved the explosives and you only delivered them to me. But the job is done, and you are here, and they are not, so the reward goes to you.}
{226}{}{你可能在骗我。也许他们取回了炸药，而你只把它们交给了我。但是工作完成了，而你在这里，而他们没有，所以报酬归你。}
#{227}{}{I'll need more explosives than this to wrest my mine back from the usurpers in Uranium City. Say, who's in charge of the mine, now?}
{227}{}{我需要更多的炸药从铀城的篡夺者手中夺回我的矿。喂，现在谁在管我的矿？}
#{228}{}{Some guy from the Hub named Louis Birch. He seems like a tough customer.}
{228}{}{一个叫路易斯·伯奇的家伙。他似乎是个难对付的顾客。}
#{229}{}{Nelson, one of the locals.}
{229}{}{纳尔逊，当地人之一。}
#{230}{}{All work has stopped and most of the miners have skipped town. People are questioning who really owns the mine and who's going to get it running again.}
{230}{}{所有的工作都停止了，大多数矿工都逃走了。人们在质疑谁真正拥有了这个矿，谁又会让它重新运转起来。}
#{231}{}{Then get rid of him. That mine belongs to me, and only me. Everything that's there is due to my patronage.}
{231}{}{那就除掉他。我的属于我，只有我。那里的一切都是我的恩赐。}
#{232}{}{I'll get it done.}
{232}{}{我会搞定的。}
#{233}{}{You'll be paid upon completion. We're done here.}
{233}{}{完成后你会得到报酬。我们到此为止。}
#{234}{}{[Walk away.]}
{234}{}{[走开。]}
#{235}{}{In that case, you must remind Uranium City why it even exists. Everyone there is there because of my investment. You mentioned a Nelson in your report - I remember him. He was a good worker in the mine. Now he's the one trying to take it from me... Remove him.}
{235}{}{在这种情况下，你必须提醒铀城为什么存在。那里的每个人都是因为我的投资。你在报告中提到了一个尼尔森-我记得他。他在矿井里是个好工人。现在是他想夺走我的心。。。把他带走。}
#{236}{}{There's no one left to challenge your ownership of the mine, Mr. Wright.}
{236}{}{没有人可以挑战你对矿的所有权了，赖特先生。}
#{237}{}{Good. Here's your payment. If you lied to me, you'd better never return to this city.}
{237}{}{很好。这是你的报酬。如果你对我撒谎，你最好不要再回到这个城市。}
#{238}{}{No lies, Mr. Wright.}
{238}{}{别撒谎，赖特先生。}
#{250}{}{I'm looking for the lost miners from Uranium City.}
{250}{}{我在找铀城失踪的矿工。}
#{251}{}{I'd advise you start checking trash heaps, where they belong.}
{251}{}{我建议你开始检查垃圾堆，它们应该在哪里。}
#{252}{}{I'm looking for Joseph. He managed the mine crews.}
{252}{}{我在找约瑟夫。他管理着煤矿工人。}
#{253}{}{I'm looking for Carl. He manned the workbench.}
{253}{}{我在找卡尔。他操纵工作台。}
#{254}{}{I'm looking for Michael, a supplier.}
{254}{}{我在找迈克尔，一个供应商。}
#{255}{}{Thanks, that's all I need to know.}
{255}{}{谢谢，我只想知道这些。}
#{256}{}{That useless dullard had no business managing anyone. I sold him into slavery on Oliver's ranch. Maybe he'll finally learn something about leadership when he's on the receiving end.}
{256}{}{那个没用的笨蛋没必要管任何人。我把他卖到奥利弗的农场当奴隶。也许当他站在接受端的时候，他最终会学到一些关于领导力的知识。}
#{257}{}{That half-witted nigger doesn't know how lucky he is. I can't punish him until I find a suitable replacement, and they don't come easy. Until then, he's living with his family in my slums in front of the Silver Legacy hotel.}
{257}{}{那个愚蠢的黑人不知道自己有多幸运。在我找到合适的替代者之前我不能惩罚他，而且他们来之不易。在那之前，他和他的家人住在我的贫民窟，在银遗产酒店前面。}
#{258}{}{That man redefined "useless". He had nothing I could take from him. Even the slavers didn't want him. I kicked him to the streets - he's probably been eaten by dogs or his fellow beggars by now.}
{258}{}{那个人重新定义了“无用的”。他没有我能从他身上拿走的东西。甚至奴隶主也不想要他。我把他踢到街上-他现在可能已经被狗或他的乞丐同伴吃掉了。}
#{259}{}{[Leave.]}
{259}{}{[离开]}
#{260}{}{A resident in your slums, Mrs. Clover, has become the victim of another person's debts. What is your position on this?}
{260}{}{你贫民窟里的一个居民，克洛弗太太，成了另一个人债务的受害者。你对此持什么立场？}
#{261}{}{Another headache. Mrs. Clover is a a reliable cash cow due to her restaurant's income, so it's in my best interests to keep her solvent. On the other hand, it's not in my best interests to forgive debts... Even if I must take my pound of flesh from someone else. I must look upon this with distance and great care.}
{261}{}{又是头痛。克洛弗太太是一个可靠的摇钱树由于她的餐厅的收入，所以它是在我的最大利益保持她的偿付能力。另一方面，免除债务不符合我的最大利益。。。即使我必须从别人那里拿走我那一磅肉。我必须远远地、非常小心地看待这件事。}
#{262}{}{I understand. Let's talk about something else.}
{262}{}{我理解。我们再谈点别的吧。}
#{263}{}{That's all I needed. Goodbye, Mr. Wright.}
{263}{}{这就是我所需要的。再见，赖特先生。}
#{270}{}{Your work in Uranium City is done. My sons will take it from here... When we're ready. You have another job.}
{270}{}{你在铀城的工作结束了。我的儿子们会从这里拿走。。。当我们准备好的时候。你有另一份工作。}
#{271}{}{I'm listening.}
{271}{}{我在听。}
#{272}{}{I've been told of a strange man sniffing around my slums. I do not know him, but there will be no secrets from me in my domain. Go the east side of the slums and deal with him. Avoid causing a ruckus in my slums if you can, but do whatever you need to in order to get the job done.}
{272}{}{我听说有个陌生人在我的贫民窟里嗅来嗅去。我不认识他，但在我的领域里不会有我的秘密。去贫民窟的东边和他打交道。如果可以的话，尽量避免在我的贫民窟引起骚动，但是为了完成任务，你需要做什么就做什么。}
#{273}{}{I'm on my way, Mr. Wright.}
{273}{}{我马上就来，赖特先生。}
#{274}{}{I dealt with the stranger. It seems like he was watching the slums, but I couldn't find out more.}
{274}{}{我和陌生人打过交道。他好像在看贫民窟，但我找不到更多。}
#{275}{}{I figured he would be around sooner or later. This explains the reports I've received.}
{275}{}{我想他迟早会来的。这就解释了我收到的报告。}
#{276}{}{You expected someone to be watching the slums?}
{276}{}{你以为会有人监视贫民窟？}
#{277}{}{I'm being watched. I know that. I just wanted to see how you handled the situation. [his lips curl into a small, but very self-satisfied grin] You were also being watched.}
{277}{}{我被监视着。我知道。我只是想看看你是怎么处理这种情况的。[他的嘴唇蜷缩成一个小小的，但非常满意的笑容]你也被监视着。}
#{278}{}{Everyone's watching everyone... So what now?}
{278}{}{每个人都在看着每个人。。。那现在怎么办？}
#{279}{}{Now, your payment. [he counts out the money] This was your last job. From here on, I need someone smarter than you. Don't bother me again.}
{279}{}{现在，你的付款。[他数钱]这是你最后一份工作。从现在开始，我需要一个比你聪明的人。别再打扰我了。}
#{280}{}{Now, your payment. [he counts out the money] This was your last job. Your reputation in the slums makes it clear I can't rely on you. There's the door.}
{280}{}{现在，你的付款。[他数钱]这是你最后一份工作。你在贫民窟的名声清楚地表明我不能依赖你。门在那儿。}
#{281}{}{Now, your payment. [he counts out the money] You did well on this job. You've proven you're trustworthy. You're ready for more... Delicate jobs.}
{281}{}{现在，你的付款。[他数钱]你干得不错。你已经证明你是值得信赖的。你准备好接受更多。。。精致的工作。}
#{282}{}{I'm ready to hear it, Mr. Wright.}
{282}{}{我准备好听了，赖特先生。}
#{283}{}{At this point, you should know there's a war going on in Reno. It's quiet now, which benefits me, but my sons and I are being watched. It will be too dangerous for me to act alone. I have no other choice but to unite with my old enemy - Oliver Luciano.}
{283}{}{现在，你应该知道雷诺正在打仗。现在很安静，这对我有好处，但我和我的儿子们都被监视着。单独行动对我来说太危险了。我别无选择，只能和我的宿敌奥利弗·卢西亚诺联合起来。}
#{284}{}{[Next]}
{284}{}{[下一步]}
#{285}{}{Go to his ranch and relay my offer of alliance. *Politely.*}
{285}{}{去他的农场转达我的同盟提议。*礼貌地*}
#{286}{}{May I ask a few questions, Mr. Wright?}
{286}{}{我可以问几个问题吗，赖特先生？}
#{287}{}{On my way, Mr. Wright.}
{287}{}{在路上，赖特先生。}
#{288}{}{I don't deal with gangsters. I have no use for employees of mixed loyalties.}
{288}{}{我不跟黑帮打交道。我不喜欢忠心耿耿的雇员。}
#{289}{}{Wow, word travels fast...}
{289}{}{哇，消息传得真快。。。}
#{290}{}{If you must.}
{290}{}{如果你必须的话。}
#{291}{}{Another question, if I may.}
{291}{}{另一个问题，如果可以的话。}
#{292}{}{Thank you, Mr. Wright. That's all I needed.}
{292}{}{谢谢你，赖特先生。这就是我所需要的。}
#{293}{}{Why did you secure the Uranium City mine if you're not going to restore it?}
{293}{}{如果你不打算修复铀矿，为什么要保护它？}
#{294}{}{I will... Eventually. For now, it's enough to know I have it under control. I have greater concerns this moment, but I cannot allow it to fall into anyone else's hands.}
{294}{}{我会的。。。最终。现在，我已经控制住了。我现在有更大的担忧，但我不能让它落入任何人的手中。}
#{295}{}{You're broke, aren't you?}
{295}{}{你破产了，不是吗？}
#{296}{}{That's a blunt question, but in business there is a value to straight talking. My family is not as wealthy as it was before, but we have... Enough.}
{296}{}{这是一个直截了当的问题，但在商界，直言不讳是有价值的。我的家庭不像以前那么富有了，但是我们。。。够了。}
#{297}{}{How did Oliver Luciano become your enemy?}
{297}{}{奥利弗·卢西亚诺是怎么成为你的敌人的？}
#{298}{}{It was in a different Reno than this one. During its golden age, over ten years ago, we had peace here. But then the city grew beyond its resources and we were forced to turn on each other. That gave Big Louie his chance to devastate us all and leave his dogs to pick over what was left. Now I have to join my enemy to survive someone else's war. A bitter irony, isn't it?}
{298}{}{它在一个不同的雷诺比这个。在它的黄金时代，十多年前，我们这里有和平。但后来这个城市的发展超出了它的资源范围，我们被迫互相攻击。这让大路易有机会毁灭我们所有人，让他的狗去捡剩下的东西。现在我必须加入我的敌人，以生存别人的战争。很讽刺，不是吗？}
#{299}{}{May I ask a few questions about current situation, Mr. Wright?}
{299}{}{赖特先生，我可以问几个关于当前形势的问题吗？}
#{300}{}{I have bad news. Oliver Luciano is dead.}
{300}{}{我有个坏消息。奥利弗·卢西亚诺死了。}
#{301}{}{I've relayed your offer to Luciano. He's ready to hear you out - in person.}
{301}{}{我把你的提议转达给卢西亚诺了。他准备亲自听你说。}
#{302}{}{Whose side are you on in this war?}
{302}{}{在这场战争中你站在谁一边？}
#{303}{}{My own. I have no stake nor interest in politics, but these gangsters won't stop until they own all of Reno... Or die.}
{303}{}{我自己的。我对政治没有利害关系，也没有兴趣，但这些歹徒在他们拥有雷诺的所有土地之前是不会罢休的。。。否则就死定了。}
#{304}{}{I relayed your offer to Luciano, and he refused. I'm very sorry, Mr. Wright.}
{304}{}{我把你的提议转达给卢西亚诺，他拒绝了。非常抱歉，赖特先生。}
#{305}{}{I relayed your offer to Luciano, and he refused.}
{305}{}{我把你的提议转达给卢西亚诺，他拒绝了。}
#{308}{}{The museum is closed for the foreseeable future. I was robbed recently, and I will not allow the relics of a greater age to be fenced for some gutter trash's drug money.}
{308}{}{博物馆在可预见的将来关闭。我最近被抢劫了，我不会让那些更大时代的遗物被一些地沟垃圾的毒资围起来。}
#{309}{}{That's a shame.}
{309}{}{真可惜。}
#{310}{}{Mr. Wright, I've heard a lot about your collection of pre-war objects. Could you tell me more about it?}
{310}{}{赖特先生，我听说过很多关于你收集战前物品的事。你能告诉我更多的情况吗？}
#{311}{}{I collect relics of the old America. They are my monument to the rich culture of the America that was... The one that by all rights, my family should have been born into, rather than the ash heap we're in today. It includes a jazz trumpet, a deck of playing cards, photos from different eras and four full cabinets of assorted Americana...}
{311}{}{我收集旧美国的遗迹。他们是我的丰碑，以丰富的美国文化是。。。当然，我的家庭应该出生在这个地方，而不是我们今天所处的灰烬堆里。它包括一个爵士小号，一副扑克牌，来自不同时代的照片和四个各式各样的美式。。。}
#{312}{}{but you don't need to worry about that. It would be lost on you, anyway.}
{312}{}{但你不用担心。不管怎样，你都会失去它的。}
#{313}{}{rescued from the local boors who wouldn't recognize culture if it paved over their hovels and built an art gallery in their place. But you've served me well. Perhaps you may be enlightened by a tour.}
{313}{}{从当地的乡下人那里被解救出来，如果文化铺就在他们的小屋上，在他们的地方建一个美术馆，他们就不会承认文化。但你为我服务得很好。也许你会受到一次旅行的启发。}
#{314}{}{No? Well, maybe you'll change your mind later.}
{314}{}{不？好吧，也许你以后会改变主意。}
#{315}{}{You'd be surprised how interested I am in pre-war things, Mr. Wright. I'd love to see your collection.}
{315}{}{你会惊讶我对战前的事情有多感兴趣，赖特先生。我想看看你的收藏品。}
#{316}{}{I would be happy for a tour, but not right now. Sorry to disturb you.}
{316}{}{我很乐意去旅游，但现在不行。抱歉打扰你。}
#{317}{}{Look with your eyes, don't touch anything. Follow me. [he groans and rises from his chair, walking to the bedroom door]}
{317}{}{用你的眼睛看，不要碰任何东西。跟着我。[他呻吟着从椅子上站起来，走向卧室的门]}
#{318}{}{[Take a tour.]}
{318}{}{[游览]}
#{319}{}{...do you see now, how much we've lost? This was a great country, our city on a hill... And it could be still, were it not for the avarice and selfishness of its people.}
{319}{}{……你现在看到了吗，我们损失了多少？这是一个伟大的国家，我们的城市在山上。。。如果不是因为人民的贪婪和自私，它可能是静止的。}
#{320}{}{Thank you for the tour, Mr. Wright. It was very educational!}
{320}{}{谢谢你的参观，赖特先生。很有教育意义！}
#{321}{}{Word on the streets is you own a jazz trumpet, Mr. Wright.}
{321}{}{听说你有爵士小号，赖特先生。}
#{322}{}{Remember that jazz trumpet in your museum?}
{322}{}{还记得你们博物馆里的爵士小号吗？}
#{323}{}{It's a centerpiece of my collection of pre-war Americana. It is very dear to me.}
{323}{}{这是我收集的战前美国画的中心。它对我来说很珍贵。}
#{324}{}{Why is it so important?}
{324}{}{为什么这么重要？}
#{325}{}{Is it for sale?}
{325}{}{是卖的吗？}
#{326}{}{Mr. Wright, it is very important that I retrieve it for its former owner.}
{326}{}{赖特先生，我为它的前主人找回它是非常重要的。}
#{327}{}{I can tell it's very important to you. I won't bother you about it again.}
{327}{}{我知道这对你很重要。我不会再为这事打扰你了。}
#{328}{}{It belonged to a musician who played in the club ten years ago. His band is a part of Reno's history. It was where Big Louie "started" his career - yes, the same one who's brought so much suffering to this city. His band was a rare source of art and culture for Reno...but that humanity was crushed under the civil war, as it always is.}
{328}{}{它属于一位十年前在俱乐部演奏的音乐家。他的乐队是雷诺历史的一部分。这是大路易“开始”他的职业生涯-是的，同一个谁带来了这么多的痛苦，这个城市。他的乐队对雷诺来说是一个难得的艺术和文化资源…但是人类在内战中被摧毁了，一如既往。}
#{329}{}{I wouldn't want to let it go... But everything has a price. $1000.}
{329}{}{我不想让它过去。。。但一切都是有代价的。$1000.}
#{330}{}{As noble as that sounds, I can't hand away a piece of Reno's history just for one person's feelings.}
{330}{}{虽然听起来很高尚，但我不能仅仅为了一个人的感情而放弃雷诺的一段历史。}
#{331}{}{Then I'll buy it right now.}
{331}{}{那我现在就买。}
#{332}{}{Mr. Wright, you know me better than that. This relic can bring about life and culture again! I plan to form a new jazz band and bring art to the people!}
{332}{}{赖特先生，你更了解我。这个遗物可以再次带来生命和文化！我打算组建一支新的爵士乐队，把艺术带给人们！}
#{333}{}{The deal is done. [he pockets the money, enters his bedroom and emerges shortly with the trumpet] Appreciate your good timing. At any other time, I'd have refused to sell it for any price.}
{333}{}{交易完成了。[他把钱装进口袋，走进卧室，很快就拿着喇叭出来]感谢你的好时机。在其他任何时候，我都会拒绝以任何价格出售它。}
#{334}{}{Thanks.}
{334}{}{谢谢。}
#{335}{}{It's been a long time since I've felt this inspired. Alright...I'll trust you. You can have the trumpet, for the sake of the future.}
{335}{}{我已经很久没有这种灵感了。好吧…我相信你。为了未来，你可以拥有小号。}
#{350}{}{I'm surprised. I thought he was one of the most protected men in... Well, it doesn't matter. Thank you for being a reliable employee, but I have no more work for you. My sons can handle everything for the foreseeable future. }
{350}{}{我很惊讶。我以为他是世界上最受保护的人之一。。。好吧，没关系。谢谢你是一个可靠的雇员，但我没有更多的工作给你。在可预见的未来，我的儿子们可以处理一切。}
#{351}{}{Farewell.}
{351}{}{再会。}
#{352}{}{Good...perhaps Reno has a future after all. Here's your pay. From here, everything rests on me, so I won't have use for your services anymore. Perhaps Luciano will have some work for you - I expect him to be busy in the future. }
{352}{}{很好…也许雷诺终究有前途。这是你的薪水。从这里开始，一切都取决于我，所以我不再需要你的服务了。也许卢西亚诺会有一些工作给你-我希望他将来会很忙。}
#{353}{}{I see. That is unfortunate, but I don't blame you. Luciano is a careful man and doesn't trust easily. In any case, I have no more work for you. My sons can handle everything for the foreseeable future. }
{353}{}{我懂了。那很不幸，但我不怪你。卢西亚诺是个细心的人，不容易相信别人。无论如何，我没有更多的工作给你了。在可预见的未来，我的儿子们可以处理一切。}
#{354}{}{Wait! Maybe I could convince him?}
{354}{}{等待！也许我能说服他？}
#{355}{}{You've already had your chance. I don't expect another will make a difference. Nonetheless, I have nothing to lose, so you may as well try. }
{355}{}{你已经有机会了。我不指望另一个会有什么不同。尽管如此，我没有什么可失去的，所以你不妨试试。}
#{356}{}{You're right, it's just not going to happen. Let's put the matter to rest.}
{356}{}{你说得对，这是不可能的。让我们把这件事了结吧。}
#{357}{}{This time I won't let you down, Mr. Wright.}
{357}{}{这次我不会让你失望的，赖特先生。}
#{358}{}{Fine. }
{358}{}{好的。}
#{359}{}{Not surprising, considering your ignorance and arrogance. }
{359}{}{考虑到你的无知和傲慢，这并不奇怪。}
#{360}{}{[After some thought, he hands you $100] You're free to go.}
{360}{}{[想了想，他递给你100美元]你可以走了。}
#{370}{}{Mr. Wright, on Patrick's behalf, I request permission to show a night time movie.}
{370}{}{赖特先生，我代表帕特里克请求允许放映夜间电影。}
#{371}{}{[He speaks wistfully, sharpening every syllable] Night-time-moo-vie... I didn't expect Patrick to be cunning enough to send someone in his stead. I already told him his bullshit religion wasn't welcome in my domain. Tell Patrick I won't tolerate his attempts to undermine me.}
{371}{}{[他渴望地说，磨尖每一个音节]夜晚的moo vie。。。我没想到帕特里克会狡猾到派个人来代替他。我已经告诉过他，我不欢迎他的宗教信仰。告诉帕特里克我不会容忍他企图破坏我。}
#{372}{}{Mr. Wright, listen...}
{372}{}{赖特先生，听着。。。}
#{373}{}{No, YOU listen! He's lucky he still has the chance to walk out on his own legs after his actions against me! He instills MY tenants with hope for things they can't have! He gives MY tenants a false belief that they are strong, that they deserve better than what I provide them! Why should I turn a blind eye to this?}
{373}{}{不，你听着！他很幸运，在他对我采取行动之后，他还有机会自己走出来！他给我的房客灌输了他们无法拥有的希望！他让我的房客误以为他们很强大，他们应该得到比我提供给他们的更好的东西！我为什么要对此视而不见？}
#{374}{}{Can't we discuss this like businessmen? What if you were compensated for your patience?}
{374}{}{我们不能像商人一样讨论这个问题吗？如果你的耐心得到了补偿怎么办？}
#{375}{}{Patrick doesn't want to encourage a revolt. He just wants to show people a movie. Trust me.}
{375}{}{帕特里克不想鼓励反抗。他只是想给人们看一部电影。相信我。}
#{376}{}{I have no answer to that, Mr. Wright.}
{376}{}{我没有答案，赖特先生。}
#{377}{}{Finally, we're talking sense. If I can profit off his parasitism, then that sheds a different light on things... And he *would* keep things quiet. Maybe he can even stem the spread of that STD that's sweeping through Reno's prostitutes. Very well, I will grant him permission for a nominal fee of $1000.}
{377}{}{最后，我们谈的是理智。如果我能从他的寄生中获利，那就让事情变得不同了。。。他会保持沉默。也许他甚至可以阻止性病在雷诺妓女中的传播。很好，我会给他1000美元的名义费用。}
#{378}{}{Here's the money.}
{378}{}{这是钱。}
#{379}{}{I'll go collect the money.}
{379}{}{我去拿钱。}
#{380}{}{Then we're done. But tell Patrick that I only promise not to interfere with his show - I won't provide any security.}
{380}{}{那我们就完了。但是告诉帕特里克，我只保证不干扰他的表演-我不会提供任何安全措施。}
#{381}{}{You're... Trustworthy enough that I may trust him in holding this event. But security is up to you - all I promise is that I will not interfere myself. Now go.}
{381}{}{你是。。。值得信赖，我可以信任他举办这次活动。但安全由你决定-我只保证我不会干涉自己。现在走吧。}
#{382}{}{I appreciate that, boss.}
{382}{}{我很感激，老板。}
#{383}{}{I do not trust this Patrick, but you have a good reputation in my slums. Fine, I will interfere in his show. But I take no responsibility for his safety - that's up to you and him.}
{383}{}{我不相信这个帕特里克，但你在我的贫民窟里名声很好。好吧，我会干涉他的表演。但我对他的安全不负任何责任-这取决于你和他。}
#{384}{}{Thanks.}
{384}{}{谢谢。}
#{385}{}{And why should I trust you? You're nothing in this district.}
{385}{}{我为什么要相信你？你在这个地区什么都不是。}
#{386}{}{I guess I can't argue that.}
{386}{}{我想我不能这么说。}
#{387}{}{Mr. Wright, this could be a great opportunity for you. Let me explain...}
{387}{}{赖特先生，这对你来说是个好机会。让我解释一下。。。}
#{388}{}{[He listens carefully to your explanation, and finally nods] I see, I see. That preacher should use you for all his deals - you're a much better speaker than him. Fine, tell him I agree. But I won't provide any security - that's up to you and him.}
{388}{}{[他仔细听了你的解释，最后点了点头]我明白了，我明白了。那个传教士应该利用你来做所有的交易——你比他讲得好得多。好吧，告诉他我同意。但我不会提供任何安全保障-这取决于你和他。}
#{390}{}{I represent the Cotton club. We want to negotiate protection for a concert.}
{390}{}{我代表棉花俱乐部。我们想协商保护音乐会。}
#{391}{}{Excellent. Your boss should know I've always been interested in collaborating. We are neighbors, after all. Tell him I'll contribute to the concert, but I want 30% of the daily revenue.}
{391}{}{杰出的。你老板应该知道我一直对合作很感兴趣。毕竟我们是邻居。告诉他我会为音乐会捐款，但我要每天收入的30%。}
#{392}{}{We agree to those conditions.}
{392}{}{我们同意这些条件。}
#{393}{}{We will consider your offer get back to you.}
{393}{}{我们会考虑你方的报盘并尽快回复你方。}
#{394}{}{A wise decision. I'll send my men to work out the details.}
{394}{}{明智的决定。我会派我的人去解决细节问题。}
#{395}{}{Thank you. That will be all.}
{395}{}{非常感谢。就这些了。}
#{1135}{}{Have you completed my... Errand?}
{1135}{}{你完成我的。。。差事？}
#{1138}{}{I just wanted to say hello.}
{1138}{}{我只是想打个招呼。}
#{1147}{}{Reputation. And regardless of your wallet or gun, reputation is something you don't have. In my slums, no one knows you and no one recommends you. And I trust my people. If you want a job, show me your work... Where it counts.}
{1147}{}{名誉。不管你的钱包和枪，名声都是你所没有的。在我的贫民窟，没有人认识你，也没有人推荐你。我信任我的人民。如果你想找份工作，给我看看你的工作。。。重要的地方。}
#{1148}{}{You really haven't heard of me, Mr. Wright? I've done a lot in Reno.}
{1148}{}{你真的没听说过我吗，赖特先生？我在雷诺做了很多。}
#{1162}{}{Very well. [he leans back in his chair, interlacing his fingers on his stomach] I have some errands for a woman like you... Someone from out of town. I pay well, provided the job is completed correctly.}
{1162}{}{很好。[他靠在椅子上，手指交叉放在肚子上]我有一些事情要给你这样的女人做。。。从外地来的人。我薪水很高，只要工作完成得正确。}
#{1184}{}{I'm back from Uranium City.}
{1184}{}{我从铀城回来了。}
#{1210}{}{About those prospectors...}
{1210}{}{关于那些探矿者。。。}
#{1215}{}{Stop wasting my time! All I care about are those explosives. It doesn't matter who gets them, as long as they get them to *me*!}
{1215}{}{别再浪费我的时间了！我只关心那些炸药。不管是谁得到的，只要他们把它们交给我就行了！}
#{1217}{}{They're what?! You imbecile! Those explosives are my leverage *against* that town! Get them back at any cost! If you have to kill this Nelson, do it. Now go. The next time I see you, you had better have my explosives.}
{1217}{}{他们是什么？！你这个笨蛋！那些炸药是我对付那个城镇的筹码！不惜一切代价把他们弄回来！如果你非要杀了这个尼尔森，就杀了他。现在走吧。下次我见到你的时候，你最好拿着我的炸药。}
#{1220}{}{The prospectors, Mr. Wright. They're the ones that retrieved the explosives. They only asked me to deliver it because they're afraid of you.}
{1220}{}{探矿者，赖特先生。是他们找回了炸药。他们让我送是因为怕你。}
#{1222}{}{Hmm. You could have lied, told me you retrieved them from that base, but you didn't. I appreciate an honest woman. Anyway, here's your pay for the assignment.}
{1222}{}{嗯。你本可以撒谎，告诉我你从那个基地找回了它们，但你没有。我欣赏一个诚实的女人。不管怎样，这是你的任务报酬。}
#{1226}{}{You could be lying to me. Perhaps they retrieved the explosives and you only delivered them to me. But the job is done, and you are here, and they are not, so the reward goes to you.}
{1226}{}{你可能在骗我。也许他们取回了炸药，而你只把它们交给了我。但是工作完成了，而你在这里，而他们没有，所以报酬归你。}
#{1237}{}{Good. Here's your payment. If you lied to me, you'd better never return to this city.}
{1237}{}{很好。这是你的报酬。如果你对我撒谎，你最好不要再回到这个城市。}
#{1270}{}{Your work in Uranium City is done. My sons will take it from here... When we're ready. You have another job.}
{1270}{}{你在铀城的工作结束了。我的儿子们会从这里拿走。。。当我们准备好的时候。你有另一份工作。}
#{1274}{}{I dealt with the stranger. It seems like he was watching the slums, but I couldn't find out more.}
{1274}{}{我和陌生人打过交道。他好像在看贫民窟，但我找不到更多。}
#{1279}{}{Now, your payment. [he counts out the money] This was your last job. From here on, I need someone smarter than you. Don't bother me again.}
{1279}{}{现在，你的付款。[他数钱]这是你最后一份工作。从现在开始，我需要一个比你聪明的人。别再打扰我了。}
#{1281}{}{Now, your payment. [he counts out the money] You did well on this job. You've proven you're trustworthy. You're ready for more... Delicate jobs.}
{1281}{}{现在，你的付款。[他数钱]你干得不错。你已经证明你是值得信赖的。你准备好接受更多。。。精致的工作。}
#{1282}{}{I'm ready to hear it, Mr. Wright.}
{1282}{}{我准备好听了，赖特先生。}
#{1301}{}{I've relayed your offer to Luciano. He's ready to hear you out - in person.}
{1301}{}{我把你的提议转达给卢西亚诺了。他准备亲自听你说。}
#{1304}{}{I relayed your offer to Luciano, and he refused. I'm very sorry, Mr. Wright.}
{1304}{}{我把你的提议转达给卢西亚诺，他拒绝了。非常抱歉，赖特先生。}
#{1305}{}{I relayed your offer to Luciano, and he refused.}
{1305}{}{我把你的提议转达给卢西亚诺，他拒绝了。}
#{1310}{}{Mr. Wright, I've heard a lot about your collection of pre-war objects. Could you tell me more about it?}
{1310}{}{赖特先生，我听说过很多关于你收集战前物品的事。你能告诉我更多的情况吗？}
#{1312}{}{but you don't need to worry about that. It would be lost on you, anyway.}
{1312}{}{但你不用担心。不管怎样，你都会失去它的。}
#{1313}{}{rescued from the local boors who wouldn't recognize culture if it paved over their hovels and built an art gallery in their place. But you've served me well. Perhaps you may be enlightened by a tour.}
{1313}{}{从当地的乡下人那里被解救出来，如果文化铺就在他们的小屋上，在他们的地方建一个美术馆，他们就不会承认文化。但你为我服务得很好。也许你会受到一次旅行的启发。}
#{1316}{}{I would be happy for a tour, but not right now. Sorry to disturb you.}
{1316}{}{我很乐意去旅游，但现在不行。抱歉打扰你。}
#{1350}{}{I'm surprised. I thought he was one of the most protected men in... Well, it doesn't matter. Thank you for being a reliable employee, but I have no more work for you. My sons can handle everything for the foreseeable future. }
{1350}{}{我很惊讶。我以为他是世界上最受保护的人之一。。。好吧，没关系。谢谢你是一个可靠的雇员，但我没有更多的工作给你。在可预见的未来，我的儿子们可以处理一切。}
#{1352}{}{Good... Perhaps Reno has a future after all. Here's your pay. From here, everything rests on me, so I won't have use for your services anymore. Perhaps Luciano will have some work for you - I expect him to be busy in the future. }
{1352}{}{很好。。。也许雷诺终究还是有前途的。这是你的薪水。从这里开始，一切都取决于我，所以我不再需要你的服务了。也许卢西亚诺会有一些工作给你-我希望他将来会很忙。}
#{1353}{}{I see. That is unfortunate, but I don't blame you. Luciano is a careful man and doesn't trust easily. In any case, I have no more work for you. My sons can handle everything for the foreseeable future. }
{1353}{}{我懂了。那很不幸，但我不怪你。卢西亚诺是个细心的人，不容易相信别人。无论如何，我没有更多的工作给你了。在可预见的未来，我的儿子们可以处理一切。}
#{1355}{}{You've already had your chance. I don't expect another will make a difference. Nonetheless, I have nothing to lose, so you may as well try. }
{1355}{}{你已经有机会了。我不指望另一个会有什么不同。尽管如此，我没有什么可失去的，所以你不妨试试。}
#{1360}{}{[After some thought, he hands you $100] You're free to go.}
{1360}{}{[想了想，他递给你100美元]你可以走了。}
#{1381}{}{You're... Trustworthy enough that I may trust him in holding this event. But security is up to you - all I promise is that I will not interfere myself. Now go.}
{1381}{}{你是。。。值得信赖，我可以信任他举办这次活动。但安全由你决定-我只保证我不会干涉自己。现在走吧。}
#{1387}{}{Mr. Wright, this could be a great opportunity for you. Let me explain...}
{1387}{}{赖特先生，这对你来说是个好机会。让我解释一下。。。}
