#{100}{}{You see Nick Hauer.}
{100}{}{你看到尼克·豪尔了。}
#{101}{}{You see a man in dark shades and an old duster, which obviously seen many miles of wasteland. He holds a walking cane in both hands.}
{101}{}{你看到一个戴着墨镜的人和一把旧掸子，显然看到了好几英里的荒地。他双手拿着拐杖。}
#{102}{}{I'll wait here.}
{102}{}{我在这儿等。}
#{103}{}{Greetings!}
{103}{}{问候语！}
#{110}{}{So, we finally meet. You weren't followed, right?}
{110}{}{所以，我们终于见面了。你没有被跟踪，对吧？}
#{111}{}{Me? Followed? Why would I be?}
{111}{}{我？跟着？为什么我会这样？}
#{112}{}{I didn't notice anything. What's up?}
{112}{}{我什么都没注意到。怎么了？}
#{113}{}{You stand out in a crowd, and these gangsters have eyes and ears everywhere. Hell, one spy could be working for both sides. That's just how it is around here. So, you definitely attracted some attention.}
{113}{}{你在人群中脱颖而出，这些歹徒到处都有眼睛和耳朵。见鬼，一个间谍可能为双方工作。这里就是这样。所以，你确实引起了一些注意。}
#{114}{}{A little birdie told me you've been in Stryker's lab, and I thought you just *might* listen to the voice of reason. See, Stryker's holding my friend Terry against his will. I'd like to help him, but I can't get into the lab. Stryker keeps everyone out... Everyone but you, it seems.}
{114}{}{一只小鸟告诉我你去过史崔克的实验室，我想你应该听听理性的声音。你看，史崔克违心抓着我朋友特里。我想帮他，但我进不了实验室。史崔克把所有人都挡在外面。。。似乎除了你以外的所有人。}
#{115}{}{No. I'm a mercenary, but I'm not crazy.}
{115}{}{不，我是个唯利是图的人，但我没疯。}
#{116}{}{What are you offering?}
{116}{}{你提供什么？}
#{117}{}{I'll be happy to help cleanse this world of slavery.}
{117}{}{我很乐意帮你清除这个世界上的奴隶制度。}
#{118}{}{I hear you. I'm not asking you to storm the place, that would be crazy. I mean something with more... Finesse. Also, I've got to say - I haven't spoke with Terry for a long time, I don't know if he has changed over these ten years. But I have a feeling that he needs help.}
{118}{}{我听到了。我不是要你闯入这个地方，那太疯狂了。我是说有更多。。。精巧。另外，我得说-我很久没和特里谈过话了，我不知道他在这十年里有没有变。但我觉得他需要帮助。}
#{119}{}{Well... While traveling, I've managed to save 350 bucks. Not a whole lot for such a risky job, I understand, but it's all I've got.}
{119}{}{好。。。在旅行中，我设法节省了350美元。对这样一个冒险的工作来说，我不算太多，我明白，但这是我的全部。}
#{120}{}{You got no idea how happy I am to hear that, friend. I haven't talked to Terry in years, but I know he'd never want to be locked up, no matter what they're doing for him.}
{120}{}{你不知道听到这个我有多高兴，朋友。我已经好几年没和特里谈过话了，但我知道他永远都不想被关起来，不管他们为他做了什么。}
#{121}{}{What's your plan?}
{121}{}{你的计划是什么？}
#{122}{}{I'm out. This job isn't for me.}
{122}{}{我出去了。这份工作不适合我。}
#{123}{}{Hmm... That's not what I expected from you. Well, keep me in mind, anyway.}
{123}{}{隐马尔可夫模型。。。那不是我对你的期望。不管怎样，记住我。}
#{124}{}{First step? You gotta get a message to him. I'm offering him to make a run to San Francisco. It's way, way west of here - they're never find us. The hard part is getting him out.}
{124}{}{第一步？你得给他捎个口信。我提议他去旧金山。从这里往西走-他们永远找不到我们。最难的是把他弄出来。}
#{125}{}{If you want my help, I need to know more about you and Terry.}
{125}{}{如果你需要我的帮助，我需要更多地了解你和特里。}
#{126}{}{I'll see what I can do.}
{126}{}{我看看我能做什么。}
#{127}{}{Now is not the best time for such a long story. The short version is, we grew up together, went into business together. Then the civil war had separated us, ten years ago. I ended up in San Francisco. Now I'm back, to ask him to escape together.}
{127}{}{现在不是讲这么长故事的最佳时机。简而言之，我们一起长大，一起经商。十年前，内战把我们分开了。最后我去了旧金山。现在我回来了，要他一起逃走。}
#{128}{}{What happened ten years ago?}
{128}{}{十年前发生了什么？}
#{129}{}{What kind of business did you have?}
{129}{}{你有什么生意？}
#{130}{}{How did you end up in San Francisco?}
{130}{}{你怎么会去旧金山的？}
#{131}{}{You were gone for ten years and are just expecting to pick up where you left off with this guy?}
{131}{}{你离开了十年，只想重回你和这家伙分手的地方？}
#{132}{}{I've heard enough. Take care.}
{132}{}{我听够了。当心。}
#{133}{}{Businessmen around the city went into full-on war. My house burned down with my family with it, I got blind, Terry got snatched up, and it looks like he's been passed around from one leader to another ever since.}
{133}{}{全城的商人都投入了战争。我的房子和我的家人一起被烧毁了，我瞎了眼，特里被抓了起来，看起来他从一个领导人到另一个领导人好像一直被传来传去。}
#{134}{}{We dealt with booze, mostly. We were not half-bad - our stuff found its way into the local bars. Not pre-war quality, but better than the moonshine other people were churning out. Problem was, some of those moonshiners didn't appreciate the comparison. Some tough guys they were... Oh, and also, we lent some alcohol for medicinal purposes - obviously, health care in that times was not so good.}
{134}{}{我们主要是和酗酒打交道。我们还不错——我们的东西在当地的酒吧里很流行。不是战前的质量，而是比其他人生产的私酒更好。问题是，有些月光族不喜欢这种比较。他们是些硬汉。。。哦，还有，我们借了些酒作药用——显然，那个时代的医疗保健不太好。}
#{135}{}{[He sighs] Alright, so, someone set my house on fire. I ran in to find my family. I did, but not fast enough. Then a burning piece of wood fell on me and I got blind. Days of me being suicidal mood went by, until a caravan from San Francisco arrived. They said the doctors there could treat me. Funny sort people. Had funny kind of morals too - made me their lab rat. It was... I don't like to remember it. But I can see again. Better than ever, actually.}
{135}{}{好吧，有人放火烧了我的房子。我跑进去找我的家人。是的，但还不够快。然后一块燃烧的木头落在我身上，我失明了。几天来我一直有自杀倾向，直到一辆来自旧金山的大篷车来了。他们说那里的医生可以治疗我。有趣的人。也有很有趣的道德-让我成为他们的实验鼠。那是。。。我不想记住它。但我又能看见了。实际上，比以往任何时候都好。}
#{136}{}{I couldn't do it until now. It took me a long time to get out of San Francisco, and when I did, I was... I'll say it, I was scared. But I worked up the nerve, and I've worked out a plan. I've finally got the chance to help an old friend out... If he wants it.}
{136}{}{直到现在我才做得到。我花了很长时间才离开旧金山，当我离开的时候，我。。。我会说的，我很害怕。但我鼓起勇气，制定了一个计划。我终于有机会帮助一位老朋友。。。如果他想要的话。}
#{137}{}{Don't wait too long. This city could explode any day.}
{137}{}{不要等太久。这座城市随时可能爆炸。}
#{138}{}{Good luck.}
{138}{}{祝你好运。}
#{140}{}{Are you planning to go all the way to San Francisco with just a cane to defend yourself?}
{140}{}{你打算一路带着拐杖去旧金山自卫吗？}
#{141}{}{[He shrugs with a sly smile] You think I'd need more than a cane to handle a few geckos? I'm tougher than I look, you know. I wouldn't suggest you test that.}
{141}{}{[他狡猾地笑着耸耸肩]你认为我需要的不仅仅是一根手杖来对付几只壁虎吗？你知道，我比看上去更坚强。我不建议你测试一下。}
#{142}{}{I don't think that stick of yours can kill a gecko, and I've swung a few in my time. There's something special about it, right?}
{142}{}{我不认为你的棍子能杀死壁虎，在我的时间里我已经挥舞了一些。有什么特别的，对吧？}
#{143}{}{Hmm... You're pretty sharp, kid. [in one fluid motion, he pulls a blade from the cane; it looks a little dull, but perfectly balanced] It was made by my special inquiry, in San Francisco. I don't like to use it if I can avoid it, but sometimes, I don't have a choice. You tend to look like a target when you've got "just a cane". I still try to stay off the roads and away from settlements, if I can.}
{143}{}{隐马尔可夫模型。。。你真聪明，孩子。[在一个流畅的动作中，他从手杖上拔出一把刀片；它看起来有点迟钝，但非常平衡]这是我在旧金山特别调查时做的。如果可以避免的话，我不喜欢用它，但有时，我没有选择。当你“只有一根手杖”的时候，你看起来就像一个目标。如果可以的话，我还是尽量远离公路，远离定居点。}
#{144}{}{I'll be sure not to make that mistake. See you around.}
{144}{}{我一定不会犯那个错误。回头见。}
#{145}{}{You received }
{145}{}{你收到了}
#{146}{}{ experience for correctly identifying the weapon.}
{146}{}{正确识别武器的经验。}
#{150}{}{Thanks for the help, but we're not done yet. I've seen a couple serious-looking types checking us out. I think we're being watched.}
{150}{}{谢谢你的帮助，但我们还没做完。我见过几个长相严肃的人盯着我们。我想我们被监视了。}
#{151}{}{How do they know what we're up to? And why aren't they attacking?}
{151}{}{他们怎么知道我们在干什么？他们为什么不进攻？}
#{152}{}{I think they're just watching the exit until there's less people around. I don't think they'll wait around much longer, though.}
{152}{}{我想他们只是看着出口，直到周围人少了。不过，我想他们不会再等了。}
#{153}{}{[Next]}
{153}{}{[下一步]}
#{154}{}{We need a way to slip past them.}
{154}{}{我们需要一种方法从他们身边溜走。}
#{155}{}{How about the window?}
{155}{}{窗户怎么样？}
#{156}{}{Good idea, but we'll need rope. The shop across the road should have some. Hurry! They'll smell something soon enough.}
{156}{}{好主意，但我们需要绳子。马路对面的商店应该有一些。快点！他们很快就会闻到什么味道。}
#{157}{}{I have some rope right here, actually.}
{157}{}{实际上，我这里有绳子。}
#{158}{}{I'll see what I can do.}
{158}{}{我看看我能做什么。}
#{159}{}{Did you get the rope?}
{159}{}{你拿到绳子了吗？}
#{160}{}{Yeah, here you go.}
{160}{}{是的，给你。}
#{161}{}{Not yet, just wait a little longer.}
{161}{}{还没有，再等一会儿。}
#{162}{}{Thanks, friend. Listen - you've already done a lot for us, so if you want to leave now, I understand. But it would really help us out if you could escort us out of here. What do you say?}
{162}{}{谢谢，朋友。听着-你已经为我们做了很多，所以如果你现在想离开，我理解。但如果你能护送我们离开这里，我们会很有帮助的。你怎么说？}
#{163}{}{I say yes. You can count on me to cover your backs.}
{163}{}{我说是的。你可以指望我来掩护你。}
#{164}{}{I sorted out the thugs. The entrance is clear.}
{164}{}{我把那些暴徒都找出来了。入口是空的。}
#{165}{}{You what?! You are one mad dog, friend! Thanks! Listen - you've already done a lot, so if you want to leave now, I understand. But it would really help us out if you could escort us out of here. What do you say?}
{165}{}{你什么？！你真是个疯狗，朋友！谢谢！听着-你已经做了很多，所以如果你现在想离开，我理解。但如果你能护送我们离开这里，我们会很有帮助的。你怎么说？}
#{166}{}{I say no. The less people in your group, the easier it will be for you to slip out unnoticed.}
{166}{}{我说不。你们组的人越少，你就越容易不被注意地溜出去。}
#{167}{}{I guess that makes this goodbye. Good luck, friend. Come on, Terry!}
{167}{}{我想这就是再见了。祝你好运，朋友。快点，特里！}
#{168}{}{Good luck.}
{168}{}{祝你好运。}
#{169}{}{Before leaving, Nick gave you all his money - 350$.}
{169}{}{临走前，尼克把所有的钱都给了你——350美元。}
#{1112}{}{I didn't notice anything. what's up?}
{1112}{}{我什么都没注意到。怎么了？}
#{1114}{}{A little birdie told me you've been in Stryker's lab, and I thought you just *might* listen to the voice of reason. See, Stryker's holding my friend Terry against his will. I'd like to help him, but I can't get into the lab. Stryker keeps everyone out... Everyone but you, it seems.}
{1114}{}{一只小鸟告诉我你去过史崔克的实验室，我想你应该听听理性的声音。你看，史崔克违心抓着我朋友特里。我想帮他，但我进不了实验室。史崔克把所有人都挡在外面。。。似乎除了你以外的所有人。}
#{1115}{}{No. I'm a mercenary, but I'm not crazy.}
{1115}{}{不，我是个唯利是图的人，但我没疯。}
#{1117}{}{I'll be happy to help cleanse this world of slavery.}
{1117}{}{我很乐意帮你清除这个世界上的奴隶制度。}
#{1123}{}{Hmm... That's not what I expected from you. Well, keep me in mind, anyway.}
{1123}{}{隐马尔可夫模型。。。那不是我对你的期望。不管怎样，记住我。}
#{1125}{}{If you want my help, I need to know more about you and Terry.}
{1125}{}{如果你需要我的帮助，我需要更多地了解你和特里。}
#{1150}{}{Thanks for the help, but we're not done yet. I've seen a couple serious-looking types checking us out. I think we're being watched.}
{1150}{}{谢谢你的帮助，但我们还没做完。我见过几个长相严肃的人盯着我们。我想我们被监视了。}
#{1159}{}{Did you get the rope?}
{1159}{}{你拿到绳子了吗？}
#{1162}{}{Thanks, friend. Listen - you've already done a lot, so if you want to leave now, I understand. But it would really help us out if you could escort us out of here. What do you say?}
{1162}{}{谢谢，朋友。听着-你已经做了很多，所以如果你现在想离开，我理解。但如果你能护送我们离开这里，我们会很有帮助的。你怎么说？}
#{1165}{}{You what?! You are one crazy girl, friend! Thanks! Listen - you've already done a lot for us, so if you want to leave now, I understand. But it would really help us out if you could escort us out of here. What do you say?}
{1165}{}{你什么？！你真是个疯狂的女孩，朋友！谢谢！听着-你已经为我们做了很多，所以如果你现在想离开，我理解。但如果你能护送我们离开这里，我们会很有帮助的。你怎么说？}
#{1167}{}{I guess that makes this goodbye. Good luck, friend. Come on, Terry!}
{1167}{}{我想这就是再见了。祝你好运，朋友。快点，特里！}
