#{100}{}{You see Nick Hauer.}
{100}{}{你看到尼克·豪尔了。}
#{101}{}{You see a man in dark sunglasses and a duster that looks like it's a lot of trips across the desert.}
{101}{}{你看到一个戴着墨镜和掸子的男人，看起来像是穿越沙漠的旅行。}
#{102}{}{They're close...}
{102}{}{他们很接近。。。}
#{103}{}{Thank you, friend. We couldn't have done this without you.}
{103}{}{谢谢你，朋友。没有你我们不可能做到这一点。}
#{104}{}{Thanks for the help. We'll bury the dead and head off to San Francisco. This is gonna be a tough one to forget.}
{104}{}{谢谢你的帮助。我们将埋葬死者，然后前往旧金山。这件事很难忘记。}
#{105}{}{What? What's he saying, Terry?}
{105}{}{什么？他在说什么，特里？}
#{110}{}{Stop! You hear that?}
{110}{}{住手！你听到了吗？}
#{111}{}{They're hot on our trail. This is going to hell.}
{111}{}{他们在跟踪我们。这会下地狱的。}
#{112}{}{Dammit! Deveraux's family slowed us down. We've got no choice, friend. We'll can't slip away in this moonlight without being seen. Got any ideas?}
{112}{}{该死！德弗罗的家人拖我们的后腿。我们别无选择，朋友。我们不能在月光下溜走而不被人看见。有什么主意吗？}
#{113}{}{That thing will go up like a candle. You run, I'll hold them off.}
{113}{}{那东西会像蜡烛一样升起。你快跑，我来拦住他们。}
#{114}{}{If we make a stand in that house, we might just make it.}
{114}{}{如果我们在那所房子里站稳脚跟，我们可能就成功了。}
#{115}{}{Still playing the hero, huh, friend? Well, good luck - it'd be a terrible waste for a man like you to die for strangers.}
{115}{}{还在演英雄吗，朋友？好吧，祝你好运-像你这样的人为陌生人而死是一种可怕的浪费。}
#{116}{}{Just go. There isn't much time.}
{116}{}{走吧。时间不多了。}
#{117}{}{I can handle myself. You just focus on keeping them safe.}
{117}{}{我能控制自己。你只需要集中精力保护他们的安全。}
#{118}{}{You're right. This is gonna be a shitty night.}
{118}{}{你说得对。今晚会很糟的。}
#{119}{}{Let's go!}
{119}{}{走吧！}
#{1103}{}{Thank you, friend. We couldn't have done this without you.}
{1103}{}{谢谢你，朋友。没有你我们不可能做到这一点。}
#{1115}{}{Still playing the hero, huh, friend? Well, good luck - it'd be a terrible waste for a woman like you to die for strangers.}
{1115}{}{还在演英雄吗，朋友？好吧，祝你好运-像你这样的女人为陌生人而死是一种可怕的浪费。}
