#{100}{}{You see a stranger.}
{100}{}{你看到一个陌生人。}
#{101}{}{You see Maxson.}
{101}{}{你看到麦克森了。}
#{102}{}{You see Balder.}
{102}{}{你看巴尔德。}
#{103}{}{You see completely bald man. He keeps pulling on his collar.}
{103}{}{你看到的是一个完全秃顶的人。他不停地拉衣领。}
#{104}{}{You see Maxson. He seems to want to hide his neck under his collar.}
{104}{}{你看到麦克森了。他似乎想把脖子藏在衣领下。}
#{105}{}{You see Balder, the man that betrayed Big Louie and sneak out of town.}
{105}{}{你看，巴尔德，那个背叛大路易，偷偷出城的人。}
#{106}{}{Big Louie's dirty business is done. You earn 1000 experience points.}
{106}{}{大路易的肮脏勾当结束了。你可以获得1000点经验值。}
#{107}{}{Maxson is trying to escape!}
{107}{}{麦克森想逃跑！}
#{110}{}{Maxson is in front of you once again, showing off his dreams of Las Vegas. He's miming a cowboy swinging a lasso while trying to ride a bull.}
{110}{}{麦克森再次出现在你面前，展示他对拉斯维加斯的梦想。他在模仿一个牛仔在骑公牛时甩套索。}
#{111}{}{You still want to go to Vegas?}
{111}{}{你还想去拉斯维加斯吗？}
#{112}{}{Oh. Yes. Have a happy stay.}
{112}{}{哦。对。祝您入住愉快。}
#{120}{}{Hello, partner! You're waiting, too?}
{120}{}{你好，搭档！你也在等？}
#{121}{}{No, I'm not. Are you going somewhere?}
{121}{}{不，我没有。你要去什么地方吗？}
#{122}{}{No, I'm just passing through.}
{122}{}{不，我只是路过。}
#{123}{}{Ah, fine then. Take care.}
{123}{}{啊，那好吧。当心。}
#{124}{}{[Leave]}
{124}{}{[离开]}
#{125}{}{Yes, I'm getting a ride to Vegas. They say there's nowhere better in the wasteland to try your luck!}
{125}{}{是的，我要搭便车去维加斯。他们说在荒地里没有比这更好的地方可以试试你的运气了！}
#{126}{}{Las Vegas?}
{126}{}{拉斯维加斯？}
#{127}{}{And what's wrong with Reno?}
{127}{}{雷诺怎么了？}
#{128}{}{Why not go right now?}
{128}{}{为什么不现在就走？}
#{129}{}{And who are you, by the way?}
{129}{}{顺便问一下，你是谁？}
#{130}{}{Fine. Bye.}
{130}{}{好的。再见。}
#{131}{}{The city that never sleeps! They say the bombs barely touched it. Now THAT'S true civilization, brother! Casinos, hotels, and caravans from everywhere in Nevada! Vegas, baby, Vegas! I'M COMING TO YOU, BABY!!! [he dances in place, hooting joyfully]}
{131}{}{不眠之城！他们说炸弹几乎没碰到它。这才是真正的文明，兄弟！来自内华达州各地的赌场、酒店和商队！维加斯，宝贝，维加斯！我来找你了，宝贝！！！[他在原地跳舞，欢快地叫着]}
#{132}{}{In Reno you're either lucky, or dead. I like to have more options.}
{132}{}{在里诺，你不是幸运就是死亡。我喜欢有更多的选择。}
#{133}{}{Ah, these guys, you know - they're punctual, like clockwork. Too punctual! They won't change their schedule just for one passenger.}
{133}{}{啊，这些家伙，你知道-他们很守时，就像发条一样。太准时了！他们不会为了一个乘客而改变行程。}
#{134}{}{My name? It's... Maxson. Just Maxson.}
{134}{}{我的名字？这是...麦克森。只有麦克森。}
#{135}{}{Fine... Just Maxson. Maybe we'll meet again.}
{135}{}{好的...只有麦克森。也许我们还会再见面。}
#{136}{}{You said that very strangely.}
{136}{}{你说得很奇怪。}
#{137}{}{Just a sore throat. Forget it.}
{137}{}{只是喉咙痛。算了吧。}
#{150}{}{Maxson, right? Have you ever been called Balder?}
{150}{}{麦克森，对吧？你有人叫过巴尔德吗？}
#{151}{}{You earn 100 experience points for recognizing Maxson.}
{151}{}{识别Maxson可获得100点经验值。}
#{152}{}{[The smile doesn't leave his lips, but it disappears from his eyes] Hey, that's just low! I happen to think the bald look is good on me!}
{152}{}{[微笑没有离开他的嘴唇，但它从他的眼睛消失]嘿，这只是低！我碰巧觉得秃头的样子适合我！}
#{153}{}{I'm not talking about your head, idiot. Why don't we we step away and talk privately?}
{153}{}{我不是在说你的头，白痴。我们何不走开私下谈谈呢？}
#{154}{}{Yeah? How about I show it to Big Louie and get a second opinion?}
{154}{}{是 啊？我把它拿给大路易看，听听你的意见怎么样？}
#{155}{}{[He fixes you with a hard stare for a moment] Now... Listen. [he looks around and leans in towards you] I just want out. Out of that gang, out of that life. You want my advice, you'll do the same. I just want to disappear. Okay?}
{155}{}{[他盯着你看了一会儿]现在...听。[他环顾四周，向你靠过来]我只想出去。离开那帮人，离开那生活。你想要我的建议，你也会这么做的。我只想消失。可以？}
#{156}{}{I don't think so. I didn't come all the way here just to walk away.}
{156}{}{我不这么认为。我远道而来并不是为了走开。}
#{157}{}{Maybe. Why?}
{157}{}{也许 吧。为什么？}
#{158}{}{Hmm. I have a VERY lucrative deal lined up in Vegas, and I'm not going to miss it. So what are you going to do? Kill a valuable client of the "Nevada Express" right here in public? Go on, let's see it. Or did you shit your pants already?}
{158}{}{嗯。我在维加斯有一笔非常有利可图的交易，我不会错过的。那你打算怎么办？在公共场合杀死“内华达快车”的重要客户？去吧，让我们看看。还是你已经尿裤子了？}
#{159}{}{No, shithead, you're coming into the slums with me. I have you in my sights.}
{159}{}{不，混蛋，你要和我一起进贫民窟。我看到你了。}
#{160}{}{No, shithead, you're coming into the slums with me. Don't even think of running.}
{160}{}{不，混蛋，你要和我一起进贫民窟。别想跑了。}
#{161}{}{Damn right I will. I don't give a fuck! Just watch me!}
{161}{}{我会的。我才不管呢！看着我！}
#{162}{}{Honestly, I don't really care. I'm leaving.}
{162}{}{老实说，我真的不在乎。我要走了。}
#{163}{}{If you want out, I can help you.}
{163}{}{如果你想出去，我可以帮你。}
#{164}{}{You really think I'm going to believe that?}
{164}{}{你真的认为我会相信吗？}
#{165}{}{Why not? You think I want to spend the rest of my life with Big Louie? No, I'd rather have a good friend in Vegas.}
{165}{}{为什么不？你以为我想和大路易共度余生？不，我宁愿在维加斯有个好朋友。}
#{166}{}{Suit yourself. You're coming to the slums with me. I have you in my sights.}
{166}{}{随便你。你要和我一起去贫民窟。我看到你了。}
#{167}{}{Suit yourself. You're coming to the slums with me. Don't even think of running.}
{167}{}{随便你。你要和我一起去贫民窟。别想跑了。}
#{168}{}{Then I have my orders. You think I won't do it? Just watch me.}
{168}{}{那我有命令了。你认为我不会做吗？看着我。}
#{169}{}{Honestly, I don't really care. I'm leaving.}
{169}{}{老实说，我真的不在乎。我要走了。}
#{170}{}{I don't believe you. What will you tell Big Louie? That you let me go?}
{170}{}{我不相信你。你要告诉大路易什么？你放我走了？}
#{171}{}{I need to give him your shotgun as evidence.}
{171}{}{我要把你的猎枪给他作为证据。}
#{172}{}{I don't know yet. I'll come back when I think of something.}
{172}{}{我还不知道。我一想到什么就回来。}
#{173}{}{Nice try. I'm not giving you my only weapon that easily.}
{173}{}{不错的尝试。我不会那么容易就把我唯一的武器给你。}
#{174}{}{You want to trade for it?}
{174}{}{你想用它来交换吗？}
#{175}{}{What, tough choice?}
{175}{}{什么，艰难的选择？}
#{176}{}{Let's try again.}
{176}{}{让我们再试一次。}
#{177}{}{Have you changed your decision?}
{177}{}{你改变决定了吗？}
#{178}{}{Make your decision.}
{178}{}{做你的决定。}
#{179}{}{Naw. I'm only interested in shotguns and rifles.}
{179}{}{不。我只对猎枪和步枪感兴趣。}
#{180}{}{I'll come back when I find a solution for this.}
{180}{}{等我找到解决办法再回来。}
#{181}{}{You have found a peaceful solution to the Maxson dilemma.}
{181}{}{你找到了和平解决麦克森困境的办法。}
#{182}{}{Great. I'm sure everyone will be happy now.}
{182}{}{伟大的。我相信大家现在都会高兴的。}
#{183}{}{Yes, perhaps.}
{183}{}{是的，也许。}
#{184}{}{[He grits his teeth] Fine... Not like I have a choice. Let's get this over with... }
{184}{}{[咬紧牙关]好吧...我没有选择。让我们结束这一切...}
#{185}{}{[Follow him]}
{185}{}{[跟着他]}
#{186}{}{[He grits his teeth] Fine... This is the way it always ends... }
{186}{}{[咬紧牙关]好吧...总是这样结束...}
#{187}{}{[Follow him, before he escapes.]}
{187}{}{[在他逃跑之前，跟着他。]}
#{188}{}{Hey, guys, I've got some business to take care of. I'll be back.}
{188}{}{嘿，伙计们，我有事要处理。我会回来的。}
#{191}{}{Ha! You trying to scare me, sugar tits? Your job is to open your legs, not swing your little fists. Fuck off!}
{191}{}{哈！你想吓唬我吗，甜心？你的工作是张开双腿，而不是挥动你的小拳头。滚开！}
#{192}{}{That's it! Watch what my little fists do to your jaw!}
{192}{}{就这样！小心我的小拳头打你的下巴！}
#{193}{}{Fine, asshole, wait here. I'll be back!}
{193}{}{好吧，混蛋，在这儿等着。我会回来的！}
#{194}{}{Don't even have the balls to go around the corner where we can settle this, huh? Too much of a sissy to face me like a man?}
{194}{}{甚至都没有胆量到拐角处去解决这个问题，嗯？太娘娘腔了，不能像男人一样面对我？}
#{195}{}{[His eyes flare] Sissy?! You just fucked up, whore!}
{195}{}{娘娘腔？！你搞砸了，婊子！}
#{196}{}{Don't try to run. I'm watching you.}
{196}{}{别想跑。我在看着你。}
#{197}{}{Nice try. But you can't trick me that easily, lady.}
{197}{}{不错的尝试。但是你不能那么容易骗我，女士。}
#{198}{}{Suit yourself. Then we'll do it right here.}
{198}{}{随便你。那我们就在这里做。}
#{199}{}{Fine, shithead, wait here. I'll be back.}
{199}{}{好吧，混蛋，在这儿等着。我会回来的。}
#{200}{}{And leave me without a weapon? No, you can't pull that shit on me.}
{200}{}{让我没有武器？不，你不能把那狗屎推到我身上。}
#{201}{}{Let's get this over with.}
{201}{}{让我们结束这一切吧。}
#{202}{}{Well, well... }
{202}{}{好吧，好吧...}
#{203}{}{Wait, this won't take long... }
{203}{}{等等，这不会花很长时间...}
#{204}{}{You're making a mistake. A big mistake.}
{204}{}{你犯了个错误。一个大错误。}
#{205}{}{This won't take long.}
{205}{}{这不会花很长时间的。}
#{206}{}{What did I do to deserve this?!}
{206}{}{我做了什么才配得到这个？！}
#{207}{}{Oh shit, what the fuck... }
{207}{}{哦，妈的，他妈的...}
#{208}{}{And the day started so well... }
{208}{}{今天开始的很好...}
#{209}{}{We could solve this peacefully... }
{209}{}{我们可以和平解决这个问题...}
#{210}{}{Too late, you know... }
{210}{}{太晚了，你知道...}
#{220}{}{And... RUN!}
{220}{}{还有...快跑！}
#{221}{}{Time to get the fuck away!}
{221}{}{该走了！}
#{222}{}{Feet, don't fail me now!}
{222}{}{脚，别让我失望！}
#{223}{}{Time to run!}
{223}{}{该跑了！}
#{224}{}{Full speed!}
{224}{}{全速！}
#{225}{}{As long as I'm not seen, I can escape... }
{225}{}{只要我不被看见，我就可以逃走...}
#{228}{}{Yes, I'm coming! I'm coming!}
{228}{}{是的，我来了！我来了！}
#{229}{}{We could make a deal... }
{229}{}{我们可以做个交易...}
#{230}{}{It's your move! Just leave me alone!}
{230}{}{这是你的行动！别管我！}
#{231}{}{Well, well, what do we have here?}
{231}{}{好吧，好吧，我们这里有什么？}
#{232}{}{[Next]}
{232}{}{[下一步]}
#{1120}{}{Hey, little lady! You're waiting, too?}
{1120}{}{嘿，小姑娘！你也在等？}
#{1131}{}{The city that never sleeps! They say the bombs barely touched it. Now THAT'S true civilization, sister! Casinos, hotels, and caravans from everywhere in Nevada! Vegas, baby, Vegas! I'M COMING TO YOU, BABY!!! [he dances in place, hooting joyfully]}
{1131}{}{不眠之城！他们说炸弹几乎没碰到它。这才是真正的文明，修女！来自内华达州各地的赌场、酒店和商队！维加斯，宝贝，维加斯！我来找你了，宝贝！！！[他在原地跳舞，欢快地叫着]}
#{1156}{}{I don't think so. I didn't come all the way here just to walk away.}
{1156}{}{我不这么认为。我远道而来并不是为了走开。}
#{1158}{}{Hmm. I have a VERY lucrative deal lined up in Vegas, and I'm not going to miss it. So what are you going to do? Kill a valuable client of the "Nevada Express" right here in public? Go on, let's see it. Or did you piss your panties already?}
{1158}{}{嗯。我在维加斯有一笔非常有利可图的交易，我不会错过的。那你打算怎么办？在公共场合杀死“内华达快车”的重要客户？去吧，让我们看看。还是你已经尿裤子了？}
#{1170}{}{I don't believe you. What will you tell Big Louie? That you let me go?}
{1170}{}{我不相信你。你要告诉大路易什么？你放我走了？}
#{1204}{}{You're making a mistake. A big mistake.}
{1204}{}{你犯了个错误。一个大错误。}
#{1230}{}{It's your move! Just leave me alone!}
{1230}{}{这是你的行动！别管我！}
