#{100}{}{You see a visitor.}
{100}{}{你看到一个访客。}
#{101}{}{You see a visitor, intensely studying a glass of Nuka-Cola.}
{101}{}{你看到一位参观者，正在紧张地研究一杯努卡可乐。}
#{102}{}{Hey! You're the one supplying this swill? Good job! Keep it up!}
{102}{}{嘿！你是供应这种泔水的人？干得好！坚持下去！}
#{110}{}{Mind pouring me another glass?}
{110}{}{介意再给我倒一杯吗？}
#{111}{}{I hope I don't get gas...}
{111}{}{我希望我没有汽油...}
#{112}{}{Hmm... What an odd smell...}
{112}{}{Hmm...多奇怪的味道...}
#{113}{}{I wonder what it's made of.}
{113}{}{我想知道是什么做的。}
#{114}{}{You know, the pre-war stuff was better...}
{114}{}{你知道，战前的东西更好...}
#{115}{}{...but it's also all fizzled out, while this stuff is fresh!}
{115}{}{……但它也都枯萎了，而这些东西是新鲜的！}
#{116}{}{Tell me the truth, did you snatch this off a corpse or just steal it?}
{116}{}{说实话，你是从尸体上抢来的还是偷来的？}
#{117}{}{Salt Lake City? Never heard of it.}
{117}{}{盐湖城？从没听说过。}
#{118}{}{If they make Nuka there, then I'll definitely visit!}
{118}{}{如果他们在那里做努卡，那我一定会去的！}
#{119}{}{Who's your delivery partner? Must be quite the expert.}
{119}{}{谁是你的送货伙伴？一定是专家。}
#{120}{}{This is exactly what I needed!}
{120}{}{这正是我需要的！}
#{121}{}{I think I'll take a bottle for the road.}
{121}{}{我想我带一瓶酒上路。}
#{122}{}{As long as I don't get addicted...}
{122}{}{只要我不上瘾...}
