#{100}{}{You see a client.}
{100}{}{你看到一个客户。}
#{101}{}{You see a dirty wanderer with a pathetic-looking remnants of a bow-tie hanging around his neck.}
{101}{}{你看到一个肮脏的流浪者脖子上挂着一条可怜兮兮的领结。}
#{102}{}{[Wipes tears] Thank you, friend, I am eternally grateful!}
{102}{}{谢谢你，朋友，我永远感激你！}
#{103}{}{Need to get outta here before the "retribution" arrives.}
{103}{}{必须在“惩罚”到来之前离开这里。}
#{110}{}{Oh, I see a respectable gentleman has graced this city with his presence! Yes-yes, I'm talking to you, sir. May I say how hard it is to meet a man with good manners these days? ...Would you care to share a glass of Orvietto Classico Campogrande? - but wait! Oh dear! It seems I have left my wallet at home. That's rather unfortunate...}
{110}{}{哦，我看到一位可敬的绅士以他的出现使这座城市增色不少！是的，我在和你说话，先生。我可以说现在遇到一个有礼貌的人有多难吗...你愿意和我一起喝一杯奥维托古典露营车吗？-但是等等！哦，天哪！我好像把钱包忘在家里了。太不幸了...}
#{111}{}{Don't worry, err, sir. Bartender! A beer for this noble trash of society.}
{111}{}{别担心，呃，先生。酒保！为这个高贵的社会垃圾准备的啤酒。}
#{112}{}{The things people come up with to grab a free beer. Fuck off, drunk.}
{112}{}{人们想出的免费啤酒。滚开，醉鬼。}
#{113}{}{Did you change your mind and decide to keep me company, sir?}
{113}{}{先生，你改变主意决定和我作伴了吗？}
#{114}{}{Alright, grab yourself a beer from the bar. My treat.}
{114}{}{好吧，去酒吧喝杯啤酒。我请客。}
#{115}{}{Even if, the stench coming off you is more than enough to change my mind. Bye.}
{115}{}{即使你身上散发的恶臭足以让我改变主意。再见。}
#{120}{}{[He downs the bottle almost instantly, loudly belching as he wipes his mouth with the back of his hand] Ugh... You really shouldn't drink this swill. You're far too aristocratic for it, heh-heh... Thank you, just what I needed.}
{120}{}{[他几乎立刻放下瓶子，用手背擦嘴时大声打嗝]啊...你真的不该喝这种泔水。你太贵族化了，呵呵...谢谢你，正是我需要的。}
#{121}{}{Looks like that really put a damper on your politeness, eh?}
{121}{}{看来这真的让你的礼貌扫兴了，嗯？}
#{122}{}{Well, usually I'm very polite, but sometimes I'm tired of it... Are you really interested? Alright, I'll tell you, not like it's a secret. It's all thanks to my grandma, god bless her. Built herself up to be a prim and proper lady, dressed like she robbed a museum. Lace, junk around her neck... Quite the eckza... Exalted lady. And I lived with it. Even had this thing around my neck. You know why?}
{122}{}{嗯，通常我很有礼貌，但有时我厌倦了...你真的感兴趣吗？好吧，我告诉你，这不是秘密。这都要感谢我奶奶，上帝保佑她。把自己打扮成一个一本正经的淑女，打扮得像抢劫博物馆一样。蕾丝，脖子上的垃圾...真是太好了...尊贵的女士。我和它一起生活。甚至把这个东西挂在我脖子上。你知道为什么吗？}
#{123}{}{I hope it's not because you were... Too close. Why?}
{123}{}{我希望不是因为你...太近了。为什么？}
#{124}{}{I'm almost yawning. Anything interesting coming up?}
{124}{}{我都快打哈欠了。有什么有趣的事吗？}
#{125}{}{Apple pie! The way she cooked it... I'd not drink for a week, if only I could taste it. But, this world isn't for grandmothers like her. They made plenty of pies from her when times were tough, fifteen bucks a piece. Now, all that's left is this pendant. Even then, I lost it in the slums somewhere. It was quite the...  exquisite thing.}
{125}{}{苹果派！她做饭的方式...如果我能尝一尝的话，我一个星期都不会喝酒了。但是，这个世界不适合像她这样的祖母。日子不好过的时候，他们从她那儿弄了很多馅饼，一块15美元。现在，只剩下这个挂件了。即使在那时，我还是在贫民窟里丢了。真是太...精致的东西。}
#{126}{}{Sad story...}
{126}{}{悲伤的故事...}
#{127}{}{You weren't the one who made her into pies, were you? I'm kidding, I'm kidding.}
{127}{}{不是你把她做成馅饼的吧？我开玩笑，我开玩笑。}
#{128}{}{Shit, that's not funny! I really loved her. In a good way. But this damn swill from the bar that's swirling in my stomach every day. It's poisoning my life. Gran held me up, gave instructions, slapped my wrist when I drank too much. But, after I lost the pendant...}
{128}{}{妈的，一点都不好笑！我真的爱她。以一种好的方式。但是这该死的酒吧里的口水每天都在我肚子里打转。它在毒害我的生命。奶奶把我扶起来，给了我指示，当我喝得太多的时候，还拍了拍我的手腕。但是，在我丢了吊坠之后...}
#{129}{}{Everyone thinks that something else is always to blame. As long as it isn't them.}
{129}{}{每个人都认为总有别的事要怪。只要不是他们。}
#{130}{}{Well, that's life.}
{130}{}{好吧，这就是生活。}
#{131}{}{Either way, thanks for hearing me out. And an extra thanks for the beer. Come around sometime, I'll be happy to see you.}
{131}{}{不管怎样，谢谢你听我说完。多谢你的啤酒。有空过来，我很高兴见到你。}
#{132}{}{Alright, bye.}
{132}{}{好的，再见。}
#{133}{}{You listened to a sad drunk's story and were rewarded with 100 exp.}
{133}{}{你听了一个悲伤的醉汉的故事，得到了100英镑的奖励。}
#{140}{}{[He bows clumsily] Happy to see you, so to say.}
{140}{}{[他笨拙地鞠躬]很高兴见到你，可以这么说。}
#{141}{}{I got my hands on an antique piece. You don't recognize it, do you?}
{141}{}{我得到了一件古董。你不认识它，是吗？}
#{142}{}{Likewise.}
{142}{}{同样地。}
#{143}{}{That's... No way! You really are a noble gentleman! And here I thought that only happened in Gran's stories. Thank you, thank you and thank you once again!}
{143}{}{那是...不可能！你真是个高尚的绅士！我以为这只发生在奶奶的故事里。谢谢你，谢谢你，再次谢谢你！}
#{144}{}{Happy to help. Here you go, pie-lover.}
{144}{}{很乐意帮忙。给你，馅饼爱好者。}
#{145}{}{Hey, hands off! I don't work for "thanks".}
{145}{}{嘿，把手拿开！我不为“谢谢”而工作。}
#{146}{}{But... It's just a trinket! Barely worth a bottle cap! Gran would turn in her grave at your words! [he sobs, blowing his nose into his bow-tie]}
{146}{}{但是...只是个小饰物！几乎不值一个瓶盖！奶奶听了你的话会在坟墓里翻来覆去的！[他抽泣着，鼻子对着领结擤]}
#{147}{}{Yeah, yeah, same old song and dance... You going to pay or what?}
{147}{}{是啊，是啊，老样子的歌舞...你要付钱吗？}
#{148}{}{Fine, you can have it. Just quit whining, granny's boy.}
{148}{}{好吧，你可以拥有它。别发牢骚了，奶奶的孩子。}
#{149}{}{[He takes his time, digging through his stinking rags. Finally, he turns around, throwing everyone else in the room cautious looks before handing you a handful of dirty coins. You definitely don't want to know where those came from.] All I have... Bloodsucker.}
{149}{}{[他慢慢来，从他那发臭的破布里挖出来。最后，他转过身来，在递给你一把脏硬币之前，小心翼翼地看着房间里的其他人。你肯定不想知道那些是从哪里来的...吸血鬼。}
#{150}{}{That's much better. You can have your little trinket now.}
{150}{}{那好多了。你现在可以拥有你的小饰物了。}
#{151}{}{You returned the drunkard's family heirloom and restored his hopes. Perhaps he'll be more confident from now on.}
{151}{}{你归还了醉汉的传家宝，恢复了他的希望。也许从现在起他会更有信心。}
#{152}{}{You returned the drunkard's family heirloom and proved, once again, that this world is no place for the weak of will.}
{152}{}{你还了酒鬼的传家宝，再一次证明了这个世界不是意志薄弱的人的地方。}
#{1102}{}{[Wipes tears] Thank you, friend, I am eternally grateful!}
{1102}{}{谢谢你，朋友，我永远感激你！}
#{1110}{}{Oh, I see a respectable lady has graced this city! Yes-yes, I'm talking to you, miss. May I say how hard it is to meet a woman with good manners these days? ...Would you care to share a glass of Orvietto Classico Campogrande? - but wait! Oh dear! It seems I have left my wallet at home. That's rather unfortunate...}
{1110}{}{哦，我看到一位可敬的女士为这座城市增光添彩！是的，我在和你说话，小姐。我可以说现在遇到一个有礼貌的女人有多难吗...你愿意和我一起喝一杯奥维托古典露营车吗？-但是等等！哦，天哪！我好像把钱包忘在家里了。太不幸了...}
#{1113}{}{Did you change your mind and decide to keep me company, ma'am?}
{1113}{}{夫人，你改变主意决定和我作伴了吗？}
#{1120}{}{[He downs the bottle almost instantly, loudly belching as he wipes his mouth with the back of his hand] Ugh... You really shouldn't drink this swill. You're far too aristocratic for it, heh-heh... Thank you, just what I needed.}
{1120}{}{[他几乎立刻放下瓶子，用手背擦嘴时大声打嗝]啊...你真的不该喝这种泔水。你太贵族化了，呵呵...谢谢你，正是我需要的。}
#{1131}{}{Either way, thanks for hearing me out. And an extra thanks for the beer. Come around sometime, I'll be happy to see you.}
{1131}{}{不管怎样，谢谢你听我说完。多谢你的啤酒。有空过来，我很高兴见到你。}
#{1143}{}{That's... No way! You really are a noble lady! And here I thought that only happened in Gran's stories. Thank you, thank you and thank you once again!}
{1143}{}{那是...不可能！你真是个高贵的女人！我以为这只发生在奶奶的故事里。谢谢你，谢谢你，再次谢谢你！}
#{1144}{}{Happy to help. Here you go, pie-lover.}
{1144}{}{很乐意帮忙。给你，馅饼爱好者。}
