#{100}{}{You see a casino administrator.}
{100}{}{你看到一个赌场管理员。}
#{101}{}{You see a man in a fine suit with finer posture. You can tell he works hard to maintain both.}
{101}{}{你看到一个男人穿着漂亮的西装，有着更漂亮的姿势。你可以看出他努力维持这两个。}
#{110}{}{A word of advice: you do not belong here, and you'd best leave, before someone does something about it!}
{110}{}{一句忠告：你不属于这里，你最好在别人动手之前离开这里！}
#{111}{}{Welcome to our casino! I am the administrator. Can I do something to help?}
{111}{}{欢迎来到我们的赌场！我是管理员。我能帮忙吗？}
#{112}{}{Did you want something?}
{112}{}{你想要什么吗？}
#{113}{}{How does this place keep running now that Bertolini's gone?}
{113}{}{既然贝托里尼走了，这个地方怎么还能继续运转？}
#{114}{}{It's been a lot a difficult transition, but we have things well in hand. Please, don't be worried - we will not allow this tragedy to disrupt the casino's operations. Now, if you'll excuse me, I have a lot to do.}
{114}{}{这是一个非常困难的过渡，但我们有事情在手。请不要担心，我们不会让这场悲剧扰乱赌场的运作。现在，请原谅，我有很多事要做。}
#{115}{}{You seem evasive. Oh, well...}
{115}{}{你好像在回避。哦，好吧。。。}
#{116}{}{Let's talk about Mrs. Clover.}
{116}{}{我们来谈谈克洛弗太太吧。}
#{117}{}{Oh, yes. Her case has certainly been a nuisance for us, but the rules are clear. Mrs. Clover will have to pay her debt of 1000 dollars.}
{117}{}{哦，是的。她的案子对我们来说无疑是件麻烦事，但规则是明确的。克洛弗太太得还清1000美元的债务。}
#{118}{}{As I informed you previously, the rules apply to everyone. No exceptions.}
{118}{}{正如我之前告诉你的，规则适用于所有人。没有例外。}
#{119}{}{Goodbye.}
{119}{}{再见。}
#{120}{}{What can you tell me about this debt?}
{120}{}{关于这笔债务你能告诉我什么？}
#{121}{}{If it will help resolve this issue, then I'll tell you everything. Mrs. Clover's late husband owed our casino a rather large debt. After his death, his debt fell to his next of kin - in this case, Mrs. Clover. She must repay it in cash - 1000 dollars, to be exact - or arrange for alternative compensation.}
{121}{}{如果这有助于解决这个问题，那么我会告诉你一切。克洛弗太太已故的丈夫欠我们赌场一大笔债。在他死后，他的债务落到了他的近亲身上——在这种情况下，克洛弗太太。她必须用现金偿还——确切地说是1000美元——或者安排其他补偿。}
#{122}{}{Could someone else pay her debt?}
{122}{}{其他人能帮她还债吗？}
#{123}{}{Of course! This is business, not a personal vendetta. If anyone were to repay the debt in her name, then the matter will be concluded.}
{123}{}{当然！这是生意，不是个人恩怨。如果有人以她的名义偿还债务，那么事情就结束了。}
#{124}{}{Then I'll pay the debt.}
{124}{}{那我就还债。}
#{125}{}{Very well. Will you pay the full 1000 dollars now?}
{125}{}{很好。你现在能付清全部1000美元吗？}
#{126}{}{Yup. Here you go.}
{126}{}{是的。干得好。}
#{127}{}{A pleasure doing business! Please deliver this receipt to Mrs. Clover and inform her that her debt has been paid. We will be happy to see her at our casino any time!}
{127}{}{很高兴做生意！请把这张收据交给克洛弗太太，并告诉她她的债务已经付清了。我们会很高兴看到她在我们的赌场任何时候！}
#{128}{}{That's great. See you.}
{128}{}{太好了。再见。}
#{129}{}{No, I'll have to come back later.}
{129}{}{不，我一会儿再来。}
#{130}{}{Of course. [his head tilts almost imperceptibly downward] Please be aware that the El Dorado will continue to attempt to redeem Mrs. Clover's debt, regardless of any verbal assurances on her behalf, until it is paid.}
{130}{}{当然。[他的头几乎不知不觉地向下倾斜]请注意，埃尔多拉多号将继续试图赎回克洛弗夫人的债务，不管代表她作出任何口头保证，直到偿还为止。}
#{131}{}{}
{131}{}{}
#{132}{}{I have more questions about Mrs. Clover's debt.}
{132}{}{关于克洛弗太太的债务我还有更多的问题。}
#{133}{}{Mrs. Clover didn't run up this debt. Why should she have to pay?}
{133}{}{克洛弗太太没有欠这笔债。她为什么要付钱？}
#{134}{}{With her husband's death, Mrs. Clover inherited all of his assets. So did she inherit his liabilities. This is known as a "family guarantee". You may disagree, but with no formal authority figures in Reno, the responsibility falls to us to decide the obligations and consequences of our financial dealings.}
{134}{}{她丈夫死后，克洛弗太太继承了他所有的财产。她也继承了他的债务。这被称为“家庭担保”。您可能不同意，但由于雷诺没有正式的权威人士，我们有责任决定我们金融交易的义务和后果。}
#{135}{}{You shouldn't worry about me disagreeing. You should worry about my boss. You may know him as Reno's informal authority figure.}
{135}{}{你不应该担心我不同意。你应该担心我的老板。你可能知道他是雷诺非正式的权威人物。}
#{136}{}{Your... [he pales] ...your boss?}
{136}{}{你的。。。[他脸色苍白]…你老板？}
#{137}{}{Yes, he's disappointed with your casino's treatment of this woman. Very, very disappointed.}
{137}{}{是的，他对你赌场对待这个女人很失望。非常非常失望。}
#{138}{}{Well, I, ah... [he swallows] ...we would not want to disappoint such a... Respected figure. Of course, we can forgive Mrs. Clover's debts... If he thinks that's best.}
{138}{}{嗯，我，啊。。。[他吞咽]…我们不想让这样一个。。。尊敬的人物。当然，我们可以原谅克洛弗太太的债务。。。如果他认为那是最好的。}
#{139}{}{He does.}
{139}{}{是的。}
#{140}{}{I don't know, I'll have to ask him.}
{140}{}{我不知道，我得问问他。}
#{141}{}{That's a lot of cash. Is there any other way to pay off the debt?}
{141}{}{那可是一大笔钱。还有别的办法还债吗？}
#{142}{}{Hmm. [he studies you carefully] It's possible an accounting error could cause Mrs. Clover's debt to fall between the cracks. But such errors are usually the result of other, more *esoteric* errors. I could discuss such details with you, but it would have to remain between us...}
{142}{}{嗯。[他仔细研究了你]一个会计错误可能会导致克洛弗太太的债务落空。但这种错误通常是其他更为“深奥”的错误的结果。我可以和你讨论这样的细节，但这件事必须保密。。。}
#{143}{}{Go on.}
{143}{}{继续。}
#{144}{}{I could wipe Mrs. Clover's debt clean, but you'd have to get something for me. Specifically, a copper cigarette case, such as the type in Mr. Wright's collection.}
{144}{}{我可以帮克洛弗太太还清债务，但你得给我买点东西。特别是一个铜烟盒，比如莱特先生收藏的那种。}
#{145}{}{Of all the things you could want in Reno, why a cigarette case?}
{145}{}{在雷诺你想要的所有东西中，为什么是香烟盒？}
#{146}{}{In this case, a cigarette is not just a cigarette. Symbols of pre-war society are a sign of status. In my particular situation, such things are more powerful than guns or even money.}
{146}{}{在这种情况下，香烟不仅仅是一支香烟。战前社会的象征是地位的象征。在我的特殊情况下，这样的东西比枪甚至比钱更强大。}
#{147}{}{Who is Mr. Wright, and what's this about a collection?}
{147}{}{赖特先生是谁？这是什么收藏？}
#{148}{}{You don't know Mr. Wright? You should. He owns the slums opposite this casino and the Silver Legacy. He was once a very powerful man, but he's but a shadow of that now. Nonetheless, he retains his collection of pre-war memorabilia. He is a... Traditional man, and appreciates the America that was. He collects artifacts of that time, and sometimes shows his collection to those that would appreciate it. Like me.}
{148}{}{你不认识赖特先生？你应该。他拥有赌场对面的贫民窟和银遗产。他曾经是一个很有权势的人，但现在只是其中的一个影子。尽管如此，他仍保留着战前的纪念品收藏。他是个。。。传统的男人，欣赏曾经的美国。他收集当时的文物，有时会把他的收藏展示给那些会欣赏的人。像我一样。}
#{149}{}{What if your boss finds out about this?}
{149}{}{如果你老板发现了怎么办？}
#{150}{}{Well, he won't, will he? [he narrows his eyes] And as a matter of fact, I don't think he'd believe it anyway.}
{150}{}{他不会的，是吗？[他眯起眼睛]事实上，我不认为他会相信。}
#{151}{}{I'll think about your proposal.}
{151}{}{我会考虑你的建议。}
#{152}{}{It's your lucky day, because I just so happen to have this cigarette case. Take it.}
{152}{}{今天是你的幸运日，因为我正好有这个烟盒。拿去吧。}
#{153}{}{I got your cigarette case. Let's get this over with.}
{153}{}{我拿到你的烟盒了。让我们结束这一切吧。}
#{154}{}{Just a moment! I imagine Mr. Bertolini would appreciate the employ of such a resourceful person. If you're interested, pay him a visit and tell him I recommended you for a job. If not, well, good luck.}
{154}{}{请稍等！我想贝托里尼先生会很感激雇用这样一个足智多谋的人的。如果你感兴趣，去拜访他，告诉他我推荐你找工作。如果不是，那么祝你好运。}
#{155}{}{I'll keep that in mind. Thank you and goodbye.}
{155}{}{我会记住的。谢谢，再见。}
#{165}{}{It was Mr. Bertolini's personal cue. Without him, we have no reason to pay for its repair. You may keep it - I'm sure you'll manage to sell it to someone.}
{165}{}{这是贝托里尼先生的个人暗示。没有他，我们就没有理由支付修理费。你可以留着它-我相信你会设法把它卖给别人的。}
#{166}{}{Hey, we had a deal!}
{166}{}{嘿，我们说好的！}
#{167}{}{I see. Well, I'll go then.}
{167}{}{我懂了。好吧，那我就去。}
#{168}{}{The conditions of the deal no longer apply. I'm sure you understand. If not, then understand that our security will not hesitate to remove unruly guests from the premises, without said cue.}
{168}{}{交易条件不再适用。我相信你能理解。如果没有，那么请理解，我们的安全部门将毫不犹豫地将不守规矩的客人从酒店带走，而无需上述提示。}
#{169}{}{Maybe they will, but they won't get here in time to save you. [Attack.]}
{169}{}{也许他们会，但他们不会及时赶到这里来救你。[攻击]}
#{170}{}{Do you have any work for me?}
{170}{}{你有工作给我吗？}
#{171}{}{The casino is not currently looking for domestic workers, but thank you for your interest. Feel free to check back any time in case something changes.}
{171}{}{赌场目前不招聘家庭佣工，但感谢您的关注。随时欢迎回来查看，以防有什么变化。}
#{172}{}{The casino is not currently looking for domestic workers, but try talking to the owner, Mr. Bertolini. He's looking for talented individuals for, er, special assignments.}
{172}{}{赌场目前不找家政工人，但试着和老板贝托里尼谈谈。他在为特殊任务寻找有才华的人。}
#{173}{}{Okay.}
{173}{}{可以。}
#{174}{}{Actually... [he holds up one finger] ...there is one task you may be able to help with. Nothing elaborate, but it pays 200 dollars.}
{174}{}{事实上。。。[他伸出一根手指]…有一件事你可以帮忙。没什么，但要付200美元。}
#{175}{}{What is it?}
{175}{}{这是怎么一回事？}
#{176}{}{Too bad, I'm only looking for elaborate work.}
{176}{}{太糟糕了，我只想找些精细的工作。}
#{177}{}{[He reaches under his desk and pulls out a carrying case. He opens it to reveal a folding pool cue that has been snapped along its shaft.] This is Mr. Bertolini's favorite cue. Yesterday he became very angry about some bad news and broke it over a knee. The messenger's knee, specifically. We will pay 200 dollars for its repair.}
{177}{}{[他把手伸到桌子下面，拿出一个手提箱。他打开门，露出一根折叠泳池的球杆，球杆上的球杆被折断了]这是贝托里尼先生最喜欢的球杆。昨天他对一个坏消息非常生气，把它说得一塌糊涂。特别是信使的膝盖。我们将支付200美元修理费。}
#{178}{}{Bertolini broke his *favorite* cue?}
{178}{}{贝托里尼打破了他最喜欢的球杆？}
#{179}{}{One of Mr. Chase's bugs has been cleverly hidden among Bertolini's belongings.}
{179}{}{蔡斯的一个窃听器被巧妙地藏在贝托里尼的随身物品中。}
#{180}{}{No problem. I'll see to it.}
{180}{}{没问题。我会处理的。}
#{181}{}{That's not really my thing.}
{181}{}{那不是我的事。}
#{182}{}{Indeed. Mr. Bertolini is a man of conviction. He acts decisively, even concerning which is he attached to.}
{182}{}{的确。贝托里尼先生是个有信念的人。他采取果断的行动，即使是关于他所依附的东西。}
#{183}{}{[He gives you a sly look] But you already know that, don't you?}
{183}{}{[他狡猾地看了你一眼]但你已经知道了，不是吗？}
#{184}{}{But you don't need to know anything about that.}
{184}{}{但你不需要知道这些。}
#{185}{}{Neither is it mine. But the job must be done sooner or later, by someone or other. We are focused on results, here - so long as you return the cue in approprite condition, you will receive your pay, whether or not you carried out the repairs yourself.}
{185}{}{也不是我的。但这项工作迟早要由某人或其他人来完成。我们关注的是结果，在这里-只要你返回的线索在适当的条件下，你会收到你的报酬，无论你是否进行修理自己。}
#{186}{}{I'm happy to hear it. [he hands over the carrying case] I'd appreciate it if you could return it as quickly as possible. Oh, and the case itself is worn out, particularly at the bottom - please see to that as well.}
{186}{}{我很高兴听到。[他递上手提箱]如果您能尽快归还，我将不胜感激。哦，而且箱子本身也磨损了，尤其是底部——请你也注意一下。}
#{187}{}{Remember, appreciation is best expressed in money. I'll be going.}
{187}{}{记住，欣赏最好用金钱来表达。我要走了。}
#{188}{}{Goodbye.}
{188}{}{再见。}
#{189}{}{Is the pool cue job still available?}
{189}{}{台球球杆的工作还可以吗？}
#{190}{}{For the time being. I was just about to pay the cleaning boy to run it to the mechanic out at the train yard. Want to stay ahead of the competition?}
{190}{}{暂时。我正要付钱给清洁工，让他把车开到火车站的机修工那里。想在竞争中保持领先吗？}
#{191}{}{Yes. Give me the cue, I'll fix it.}
{191}{}{对。给我个提示，我来解决。}
#{192}{}{No, give it to him.}
{192}{}{不，给他。}
#{193}{}{About the pool cue...}
{193}{}{关于台球球杆。。。}
#{194}{}{Is it ready?}
{194}{}{准备好了吗？}
#{195}{}{I don't understand, why did Bertolini break his favorite cue?}
{195}{}{我不明白，为什么贝托里尼打破了他最喜欢的球杆？}
#{196}{}{Yes, here it is.}
{196}{}{是的，在这儿。}
#{197}{}{Not yet. I'll bring it later.}
{197}{}{还没有。我待会再拿来。}
#{198}{}{Sorry, I lost it.}
{198}{}{对不起，我弄丢了。}
#{199}{}{[He removes the cue from the case and carefully appraises the quality of the work] Hmm. The balance is even, and the length and curvature are intact. An excellent job! Here is your payment, thank you.}
{199}{}{[他把线索从箱子里移开，仔细地评估作品的质量]嗯，平衡是均匀的，长度和曲率是完整的。干得好！这是您的付款，谢谢。}
#{1168}{}{The conditions of the deal no longer apply. I'm sure you understand. If not, then understand that our security will not hesitate to remove unruly guests from the premises, without said cue.}
{1168}{}{交易条件不再适用。我相信你能理解。如果没有，那么请理解，我们的安全部门将毫不犹豫地将不守规矩的客人从酒店带走，而无需上述提示。}
