#{100}{}{You see hoodlum.}
{100}{}{你看到流氓了。}
#{101}{}{You see a hoodlum nicknamed Stinkin' Grizzly, carefully looking around.}
{101}{}{你看到一个绰号叫臭灰熊的流氓，仔细地四处张望。}
#{102}{}{This is *our* territory.}
{102}{}{这是我们的地盘。}
#{103}{}{Who do we have here? Oh, look, it's Mr. Nobody from yesterday!}
{103}{}{我们这里有谁？哦，看，是昨天的无名小卒先生！}
#{104}{}{Uh, I'll just go...}
{104}{}{呃，我就去。。。}
#{110}{}{Right, shut the fuck up and listen. You roughed up one of Mr. Thompson's girls. I'll listen to your excuse and then geek you like it's usually done.}
{110}{}{好吧，他妈的闭嘴听我说。你粗暴地对待了汤普森先生的一个女儿。我会听你的借口，然后像往常一样怪胎你。}
#{111}{}{W-what!? How was I meant to know?! They didn't tell me anything about that!}
{111}{}{什么！？我怎么会知道？！他们什么也没告诉我！}
#{112}{}{They? Tell me about this... Third party and I *might* let you go.}
{112}{}{他们？告诉我这个。。。第三方和我可能会放你走。}
#{113}{}{I don't give a fuck who hired you. I'm here to deal with you.}
{113}{}{我才不管是谁雇你的。我是来对付你的。}
#{114}{}{I don't know who they are! They looked like they're from out of town. Walk like they got a pole shoved up their ass, talk in orders. Paid me to rough up that girl and then left. That's it, honest!}
{114}{}{我不知道他们是谁！他们看起来像是从外地来的。走路就像他们屁股上插了根杆子，按顺序说话。付钱让我粗暴对待那个女孩然后离开了。就这样，老实说！}
#{115}{}{Uh-huh, you didn't spend the money yet, did you? Hand it over.}
{115}{}{啊哈，你还没把钱花掉，是吗？把它交出来。}
#{116}{}{Sure, sure! Here it is, just, err, let's forget about it, okay? I'll send my apologies to Mr. Thompson and then disappear from the streets. I promise!}
{116}{}{当然，当然！给你，算了吧，好吗？我会向汤普森先生道歉然后消失在街上。我保证！}
#{117}{}{Fine by me. Get the fuck out now.}
{117}{}{我很好。给我滚出去。}
#{118}{}{I don't think so. I changed my mind!}
{118}{}{我不这么认为。我改变主意了！}
#{119}{}{Enough! Please, stop!}
{119}{}{够了！拜托，住手！}
#{120}{}{This is enough to make Stinkin' Grizzly disappear from this hood.}
{120}{}{这足以让臭灰熊从引擎盖上消失。}
#{121}{}{Ah? Noo! I'm not afraid! Bite me, you corporate cog!}
{121}{}{啊？不！我不怕！咬我吧，你这个公司的齿轮！}
#{122}{}{[Fight]}
{122}{}{[战斗]}
#{150}{}{Hey you! Hold on a sec!}
{150}{}{嘿，你！等一下！}
#{151}{}{[Approach]}
{151}{}{[接近]}
#{152}{}{[Ignore]}
{152}{}{[忽略]}
#{153}{}{Hey friend, mind helping me out with a few bucks?}
{153}{}{嘿，朋友，能帮我拿点钱吗？}
#{154}{}{Sure thing, here's 2 bucks.}
{154}{}{当然，这是2块钱。}
#{155}{}{Here's 10, now leave me alone.}
{155}{}{给你10块，别烦我。}
#{156}{}{Why would I give you anything?}
{156}{}{我为什么要给你任何东西？}
#{157}{}{What, that's it?}
{157}{}{什么，就这样？}
#{158}{}{You did ask for a few bucks!}
{158}{}{你确实要了几块钱！}
#{159}{}{Ugh, here's another 10, just let me go.}
{159}{}{呃，还有10个，让我走吧。}
#{160}{}{Ah, yeah, sorry friend. You're free to go. [he grabs the money and walks off, smirking]}
{160}{}{啊，是的，对不起，朋友。你可以走了。[他抓起钱，笑着走了]}
#{161}{}{[Leave]}
{161}{}{[离开]}
#{162}{}{And I said - not enough! Cash in! Now! Or I'll spread you across the asphalt!}
{162}{}{我说-还不够！兑现！现在！不然我就把你铺在柏油路上！}
#{163}{}{Like hell! You're not getting one dollar from me!}
{163}{}{见鬼去吧！你不能从我这里得到一美元！}
#{164}{}{Good enough. Keep moving. [he grabs the money and walks off, chuckling]}
{164}{}{够好了。继续前进。[他抓起钱走了，咯咯笑着]}
#{165}{}{[Leave]}
{165}{}{[离开]}
#{170}{}{[He runs up and grabs your shoulder] Hey! I'm talking to you! I don't stand for that disrespect. Give me your money before I get pissed, hear me?}
{170}{}{[他跑上来抓住你的肩膀]嘿！我在和你说话！我不能容忍这种不尊重。在我生气之前把钱给我，听到了吗？}
#{171}{}{Can't spare a few bucks? Maybe me and my boys can change your mind. Why don't you come over and we'll talk it out?}
{171}{}{不能省点钱吗？也许我和我的孩子们可以改变你的想法。你为什么不过来我们谈谈？}
#{172}{}{What, that's it? My boys are tougher. I'll just go and get 'em...}
{172}{}{什么，就这样？我的孩子们更坚强。我去把他们。。。}
#{173}{}{Ha! I know everyone around here, you can't fool me. Come on, turn out those pockets! Quick! [he grabs your sleeve]}
{173}{}{哈！我认识这里的每个人，你骗不了我。快点，把那些口袋翻出来！快点！[他抓住你的袖子]}
#{174}{}{[Resist]}
{174}{}{[抵抗]}
#{175}{}{[Comply]}
{175}{}{[遵守]}
#{176}{}{[Your pockets are emptied of all of your cash] Wasn't someone rich?! Now *off* my street! I don't wanna see you again!}
{176}{}{[你口袋里的钱都花光了]不是有钱人吗？！现在离开我的街道！我不想再见到你！}
#{177}{}{[Leave]}
{177}{}{[离开]}
#{178}{}{I'll paint this street with your blood!}
{178}{}{我要用你的鲜血来粉刷这条街！}
#{300}{}{Hah! Lookie here! A weirdo with a stick.}
{300}{}{哈哈！看这里！一个拿着棍子的怪人。}
#{301}{}{Look, look! The hell is he carrying?}
{301}{}{看，看！他到底带了什么？}
#{302}{}{Look at that! A guy with a stick.}
{302}{}{看那个！一个拿着棍子的家伙。}
#{303}{}{Am I tripping or is this guy just carrying around a stick?}
{303}{}{我是绊倒了还是这家伙只是拿着根棍子？}
#{304}{}{Hey you, there's no treasure here, don't even look.}
{304}{}{嘿，你，这里没有宝藏，别看。}
#{305}{}{Looking for something? Need help?}
{305}{}{在找什么？需要帮助吗？}
#{306}{}{Hey, tell me if you find something, kay?}
{306}{}{嘿，告诉我你有什么发现吗，凯？}
#{307}{}{Looking for coins in the gutters, what a life...}
{307}{}{在排水沟里寻找硬币，多么美好的生活。。。}
#{308}{}{Yeah, find some money!}
{308}{}{是啊，找点钱！}
#{309}{}{We need people like you... When you find something useful.}
{309}{}{我们需要像你这样的人。。。当你发现有用的东西。}
#{1103}{}{Who have we here?}
{1103}{}{我们是谁？}
#{1153}{}{Hey girlfriend, mind helping me out with a few bucks?}
{1153}{}{嘿，女朋友，能帮我拿点钱吗？}
#{1160}{}{Ah, yeah, sorry girlfriend. You're free to go. [he grabs the money and walks off, smirking]}
{1160}{}{啊，是啊，对不起，女朋友。你可以走了。[他抓起钱，笑着走了]}
#{1170}{}{[He runs up and grabs your shoulder] Bitch! I'm talking to you! I don't stand for that disrespect. Give me your money before I get pissed, hear me?}
{1170}{}{[他跑上来抓住你的肩膀]婊子！我在和你说话！我不能容忍这种不尊重。在我生气之前把钱给我，听到了吗？}
#{1171}{}{Can't spare a few bucks? Maybe me and my boys can change your mind. Why don't you come over and we'll talk it out?}
{1171}{}{不能省点钱吗？也许我和我的孩子们可以改变你的想法。你为什么不过来我们谈谈？}
#{1176}{}{[Your pockets are emptied of all of your cash] Wasn't someone rich?! Now *off* my street! I don't wanna see you again!}
{1176}{}{[你口袋里的钱都花光了]不是有钱人吗？！现在离开我的街道！我不想再见到你！}
#{1300}{}{Hah! Lookie here! A weirdo with a stick.}
{1300}{}{哈哈！看这里！一个拿着棍子的怪人。}
#{1301}{}{Look, look! The hell is she carrying?}
{1301}{}{看，看！她到底带了什么？}
#{1302}{}{Look at that! A girl with a stick.}
{1302}{}{看那个！一个拿着棍子的女孩。}
#{1303}{}{Am I tripping or is this girl just carrying around a stick?}
{1303}{}{我是绊倒了还是这个女孩只是带着一根棍子？}
#{1304}{}{Hey you, there's no treasure here, don't even look.}
{1304}{}{嘿，你，这里没有宝藏，别看。}
#{1305}{}{Looking for something? Need help?}
{1305}{}{在找什么？需要帮助吗？}
#{1306}{}{Hey, tell me if you find something, kay?}
{1306}{}{嘿，告诉我你有什么发现吗，凯？}
#{1307}{}{Looking for coins in the gutters, what a life...}
{1307}{}{在排水沟里寻找硬币，多么美好的生活。。。}
#{1308}{}{Yeah, find some money!}
{1308}{}{是啊，找点钱！}
#{1309}{}{We need people like you...when you find something useful.}
{1309}{}{我们需要像你这样的人…当你发现有用的东西。}
