#{100}{}{You see a teenager.}
{100}{}{你看到一个少年。}
#{101}{}{You see a long haired teenager. There are many like him wandering the streets of Reno.}
{101}{}{你看到一个长发少年。有许多像他一样的人在雷诺的大街上游荡。}
#{102}{}{Behold! Before you is a talented graffiti artist, engrossed in his craft.}
{102}{}{看到！在你面前的是一个天才的涂鸦艺术家，全神贯注于他的手艺。}
#{105}{}{I don't talk to strangers.}
{105}{}{我不跟陌生人说话。}
#{106}{}{Don't even ask.}
{106}{}{别问了。}
#{107}{}{Touch me and my dad will tear your head off!}
{107}{}{碰我，我爸会把你的头撕下来！}
#{108}{}{Don't even think of touching me! My gang will paint the walls with your blood!}
{108}{}{别想碰我！我的帮派会把你的血涂在墙上！}
#{109}{}{Leave me alone!}
{109}{}{别管我！}
#{150}{}{[Upon noticing you, the kid looks around nervously] Leave me alone!}
{150}{}{[一看到你，孩子紧张地环顾四周]别来烦我！}
#{151}{}{What are you doing out here so late?!}
{151}{}{这么晚了你在这里干什么？！}
#{152}{}{With pleasure!}
{152}{}{很高兴见到你！}
#{153}{}{I?... I... I'm coming home from a party!}
{153}{}{我？...一、 ...我要从派对上回家了！}
#{154}{}{Really? Well, go on then! And don't let me catch you around here again.}
{154}{}{真正地？好吧，那就继续吧！别让我再在这里看到你。}
#{155}{}{I'M JUST GOING HOME!!!}
{155}{}{我要回家了！！！}
#{156}{}{Fine, fine, don't freak out...}
{156}{}{好吧，好吧，别紧张...}
#{200}{}{[Quietly, you sneak up on the vandal and grab his wrist] AAAAAH!!! SHIIIT!!!}
{200}{}{[悄悄地，你偷偷接近破坏公物的人，抓住他的手腕]AAAAAH！！！该死！！！}
#{201}{}{I knew it! You're the one vandalizing the hotel walls! I've got you, you little brat!}
{201}{}{我就知道！是你破坏了酒店的墙壁！我抓住你了，你这个小家伙！}
#{202}{}{SO WHAT?! THEY'RE JUST WALLS! LET ME GO, MAN!!!}
{202}{}{那又怎么样？！它们只是墙！放开我，伙计！！！}
#{203}{}{This is your one warning. If I see you again, I'm selling you to the slavers. Understood?}
{203}{}{这是你唯一的警告。如果我再见到你，我就把你卖给奴隶主。理解？}
#{204}{}{Too late, kid! Should've thought of this sooner. Now march your butt into the hotel and we'll see how they feel about your work on their "just walls". Move it!}
{204}{}{太晚了，孩子！我早该想到的。现在把你的屁股伸进酒店，我们会看到他们对你的工作的感觉。快点！}
#{205}{}{Thank you! Thank you! I won't tag these walls anymore! Promise!}
{205}{}{谢谢您！谢谢您！我不会再给这些墙贴标签了！答应我！}
#{206}{}{You'd better not! I'll be watching. Now, scram!}
{206}{}{你最好不要！我会看着的。快滚！}
#{207}{}{You solved the problem peacefully, but there is no guarantee that the kid will stop.}
{207}{}{你平静地解决了问题，但不能保证孩子会停下来。}
#{208}{}{Congratulations! You caught the elusive miscreant.}
{208}{}{祝贺 你！你抓住了那个难以捉摸的恶棍。}
#{209}{}{}
{209}{}{}
#{210}{}{I think I shit my pants. Can I go home?}
{210}{}{我想我尿裤子了。我能回家吗？}
#{211}{}{So this is the little bastard vandalizing our hotel! You've been a real pain in my ass, kid, you know that?}
{211}{}{这就是那个破坏我们酒店的小混蛋！孩子，你真让我讨厌，你知道吗？}
#{212}{}{I won't do it again!}
{212}{}{我不会再做了！}
#{213}{}{Yeah, right. Why'd you go and mess up our walls in the first place?}
{213}{}{是的，没错。你为什么一开始就把我们的墙弄乱了？}
#{214}{}{Well... Everyone does...}
{214}{}{好...每个人都有...}
#{215}{}{So you might as well, too, huh? All the cool kids are doing it!}
{215}{}{所以你也可以，嗯？所有的酷孩子都这么做了！}
#{216}{}{I... Just... I just wanted to paint.}
{216}{}{一、 ...只是...我只是想画画。}
#{217}{}{What?}
{217}{}{什么？}
#{218}{}{Hmm.}
{218}{}{隐马尔可夫模型。}
#{250}{}{Well, we got the little punk. What do you think we should do with him?}
{250}{}{好吧，我们抓到小朋克了。你觉得我们该拿他怎么办？}
#{251}{}{He'll only remember one kind of lesson - flog him!}
{251}{}{他只记得一个教训-鞭打他！}
#{252}{}{I think he's had enough. I doubt he'll do it again.}
{252}{}{我想他受够了。我怀疑他还会这样做。}
#{253}{}{Make him clean the walls. That should teach him a lesson.}
{253}{}{让他打扫墙壁。这应该给他一个教训。}
#{254}{}{Why not put him to work? Pay him to paint something nice on the wall. That'll bring in the tourists, won't it?}
{254}{}{为什么不让他工作呢？付钱让他在墙上画些漂亮的东西。那会吸引游客的，不是吗？}
#{255}{}{I guess you're right. We'll deal with him ourselves, thanks for your help. Oh yeah, and 100 bucks for a job well done. All the best!}
{255}{}{我想你是对的。我们自己来对付他，谢谢你的帮助。哦，是的，一份出色的工作要100美元。祝你一切顺利！}
#{256}{}{[Leave.]}
{256}{}{[离开]}
#{257}{}{Hmm... I hope you're right. Thanks for your help. Oh yeah, and 100 bucks for a job well done. All the best!}
{257}{}{Hmm...我希望你是对的。谢谢你的帮助。哦，是的，一份出色的工作要100美元。祝你一切顺利！}
#{258}{}{I like the way you think! We'll teach him a lesson and get some work done at the same time! Thank you for your help. Oh yeah, and 100 bucks for a job well done. All the best!}
{258}{}{我喜欢你的思维方式！我们要给他一个教训，同时完成一些工作！谢谢你的帮助。哦，是的，一份出色的工作要100美元。祝你一切顺利！}
#{259}{}{Hey, I think you're on to something there! The kid's not half-bad with a spray-can, you know... I'll have to talk to my boss, but I think the kid's got a job. Thanks for your help! Oh yeah, and 100 bucks for a job well done. All the best!}
{259}{}{嘿，我想你知道什么了！这孩子用喷雾罐还不错，你知道...我得和老板谈谈，但我想这孩子有工作了。谢谢你的帮助！哦，是的，一份出色的工作要100美元。祝你一切顺利！}
#{260}{}{You found a wise means of dealing with the graffiti artist.}
{260}{}{你找到了对付涂鸦艺术家的明智方法。}
#{1201}{}{I knew it! You're the one vandalizing the hotel walls! I've got you, you little brat!}
{1201}{}{我就知道！是你破坏了酒店的墙壁！我抓住你了，你这个小家伙！}
#{1202}{}{SO WHAT?! THEY'RE JUST WALLS! LET ME GO, LADY!!!}
{1202}{}{那又怎么样？！它们只是墙！放开我，女士！！！}
#{1205}{}{Thank you, lady! I won't tag these walls anymore! Promise!}
{1205}{}{谢谢你，女士！我不会再给这些墙贴标签了！答应我！}
#{1206}{}{You'd better not! I'll be watching. Now, scram!}
{1206}{}{你最好不要！我会看着的。快滚！}
