#{100}{}{You see Martin.}
{100}{}{你看到马丁了。}
#{101}{}{You see a hardened old black man.}
{101}{}{你看到一个冷酷的老黑人。}
#{102}{}{No, I'm not going to shoot the breeze with you about the good weather and shit.}
{102}{}{不，我不想和你吹毛求疵地谈论好天气。}
#{110}{}{[When he notices you, his lips curl into a grin. It seems he was waiting for you.] Oh, look who it is. What's the matter? Did I hurt your precious feelings? Does it just twist you up inside to know a lowly *black* man got the better of you? Hmph... For you, jazz is just business, a way to make a quick buck off the locals. You don't understand. *I* should be in your place. ME! Jazz was my *life!*}
{110}{}{[当他注意到你时，他的嘴唇会咧嘴笑。他好像在等你]哦，看看是谁。怎么了？我伤害了你珍贵的感情吗？是不是为了让你知道一个卑微的黑人比你强？嗯...对你来说，爵士乐只是一种生意，一种从当地人身上快速赚钱的方式。你不明白。*我应该在你的位置。我！爵士乐是我的生活！*}
#{111}{}{That's funny. Now, it's your time to die.}
{111}{}{真有趣。现在，你该死了。}
#{112}{}{You really shouldn't have done that, Martin.}
{112}{}{你真不该那么做，马丁。}
#{113}{}{Ha! You hurt one hair on my head, and you're done with us, Ornette most of all. We're a *people*. You're not one of us - you'll NEVER be one of us. Think about it.}
{113}{}{哈！你弄伤了我头上的一根头发，我们就完了，奥内特。我们是一个民族。你不是我们中的一员-你永远不会是我们中的一员。好好想想。}
#{114}{}{I've thought it over. Fuck the band. I just want you dead.}
{114}{}{我已经考虑过了。去他妈的乐队。我只想你死。}
#{115}{}{Fine, but don't get too comfortable. You never know when I'll change my mind.}
{115}{}{好吧，但是不要太舒服。你永远不知道我什么时候会改变主意。}
#{116}{}{Oh, you're back? Just couldn't stay away, huh?}
{116}{}{哦，你回来了？就是离不开，嗯？}
#{117}{}{As far as I know, jazz music is about happiness and love for others. It seems to me that you're the one that doesn't belong.}
{117}{}{据我所知，爵士乐是关于快乐和对他人的爱。在我看来，你不属于我。}
#{118}{}{Your pride has cost Reno's people their last chance at having actual culture. If you really care about the music, you need to step aside.}
{118}{}{你的骄傲让雷诺的人失去了拥有真正文化的最后机会。如果你真的在乎音乐，你就得退到一边去。}
#{119}{}{What the fuck do you know about... About... Shit. Maybe I've gone too far. But I stand by my principles. You should not... You *can* not play jazz! This is our culture, not yours!}
{119}{}{你他妈知道什么...关于...倒霉。也许我做得太过分了。但我坚持我的原则。你不应该...你不能演奏爵士乐！这是我们的文化，不是你的！}
#{120}{}{What a joke! Music - ha! Jazz isn't just music, it's a culture - our culture! You couldn't ever understand.}
{120}{}{真是个笑话！音乐-哈！爵士乐不仅仅是音乐，它是一种文化-我们的文化！你永远无法理解。}
#{121}{}{Fine, then. Take my place. They say your vocals are much better anyway.}
{121}{}{那好吧。代替我。他们说你的嗓音好多了。}
#{122}{}{Calm down so we can talk like adults.}
{122}{}{冷静点，这样我们才能像成年人一样说话。}
#{123}{}{You here to waste my time again? I'm not your minstrel, you know, I've got better things to do than entertain you.}
{123}{}{你又来浪费我的时间了？我不是你的吟游诗人，你知道，我有比招待你更好的事要做。}
#{124}{}{Tell me about your old band.}
{124}{}{告诉我你以前的乐队。}
#{125}{}{What are you so interested for? You wouldn't get it, anyway. You organized your band for - what? Fame? Money? But we had heart. It was the "golden age" of New Reno. The city was in balance, and even people like us could go on stage and play for the good of everyone - black and white.}
{125}{}{你对什么这么感兴趣？反正你也不会明白的。你组织乐队是为了什么？名声？钱？但我们有勇气。那是新雷诺的“黄金时代”。城市是平衡的，甚至像我们这样的人也可以站在舞台上为每个人——黑人和白人——表演。}
#{126}{}{Our main man was Big Louie. We called him that because the true Louie was short, and this guy couldn't get in the club without hitting his head against the door jamb. Heh... [he smiles nostalgically, looking into the distance] At first, only our people came to us. Then, the influential whites started to show... But not for the jazz, really. They wanted to show how "tolerant" they are. To them, we were... Zoo animals.}
{126}{}{我们的主角是大路易。我们这样叫他是因为真正的路易个子矮，而这家伙不把头撞在门框上就进不了俱乐部。嘿...[他怀旧地笑着，望着远方]起初，只有我们的人来找我们。然后，有影响力的白人开始显示...但不是为了爵士乐，真的。他们想展示自己的“宽容”。对他们来说，我们是...动物园里的动物。}
#{127}{}{And we were free. Money, power, politics - free of all of it. But that didn't last. Soon the "golden age" was over and the problems began. Big Louie moved to the wasteland. Me and Ornette are the only ones left... [he shakes himself free of his reverie] But don't think I told that to satisfy your curiosity! I wanted to give you a glimpse of what those times were like. But I don't expect you to understand.}
{127}{}{我们自由了。金钱，权力，政治-不受任何限制。但这并没有持续多久。很快“黄金时代”结束了，问题开始了。大路易搬到了荒地。我和奥内特是唯一剩下的...[他摆脱了幻想]但别以为我这么说是为了满足你的好奇心！我想让你看看那些日子是怎样的。但我不希望你明白。}
#{128}{}{[Next.]}
{128}{}{[下一步。]}
#{129}{}{What?! You mean it? I've... I've dreamed of this for a long time... [his expression hardens] But I'm just supposed to give you want you want? No way. First, I want an apology. Then, maybe I'll take your place.}
{129}{}{什么？！你说真的？我已经...我已经梦想了很久...[他的表情变得僵硬]但我应该给你想要的你想要的？不可能。首先，我要道歉。那么，也许我会代替你。}
#{130}{}{That's it, I'm sick of this from you. Get your goddamn head out of your ass, or there won't *be* any band! Ever!}
{130}{}{就这样，我受够了你的话。把你的头从你的屁股里拿开，否则就不会有乐队了！永远！}
#{131}{}{What kind of apology?}
{131}{}{什么样的道歉？}
#{132}{}{I'm done. Have fun dying alone. You'll be happy to know Reno's jazz culture will die with you.}
{132}{}{我受够了。享受孤独死去的乐趣。你会很高兴知道雷诺的爵士乐文化会和你一起消亡。}
#{133}{}{Blackmail? Heh... I knew it. You just can't stand to give the black man his due.}
{133}{}{勒索？嘿...我就知道。你就是受不了给黑人应得的。}
#{134}{}{Oh, an ultimatum, is it? [his eyes alight with fire] I'll show you. I'll show all your kind what real jazz is! Now get the hell out. I need to rehearse in privacy.}
{134}{}{哦，最后通牒，是吗？[他火眼金睛]我给你看。我要向你们展示真正的爵士乐！现在滚出去。我需要私下排练。}
#{135}{}{Fine.}
{135}{}{好的。}
#{136}{}{[He pulls his pants down and turns around] Kiss my ass, and I'll forget anything.}
{136}{}{[他把裤子拉下来，转过身来]亲我的屁股，我什么都忘了。}
#{137}{}{Uh...}
{137}{}{Uh...}
#{138}{}{Come on! [he shakes his ass and smirks over his shoulder] Do it! And not just a peck on the cheek - I want every square inch of my ass moist from your lips! That, and only that, will be enough!}
{138}{}{加油！[他摇了摇屁股，在肩上笑了笑]动手！不只是在脸颊上啄一下-我要你嘴唇上的每一寸屁股都湿润！那，只有那，就够了！}
#{139}{}{Well... In the name of art... [Do it.]}
{139}{}{好...以艺术的名义...[去做吧。]}
#{140}{}{Not now, not ever. Pull your pants up before I stick a chair leg in your colon.}
{140}{}{现在不行，永远不行。在我把椅子腿伸进你的结肠之前把你的裤子拉起来。}
#{141}{}{That's the last straw. The deal is off. You can wither away alone and forgotten for all I care.}
{141}{}{这是最后一根稻草。交易取消了。你可以独自一人凋零，忘记我所关心的一切。}
#{142}{}{Oh, yes! That's enough. Consider the hatchet buried. Now... Give me time to rehearse in privacy.}
{142}{}{哦，是的！够了。把斧头埋起来。现在...给我时间私下排练。}
