#{100}{}{You see a Reno local.}
{100}{}{你看到一个雷诺本地人。}
#{101}{}{You see a simple citizen of the slums.}
{101}{}{你看到一个贫民窟的普通市民。}
#{109}{}{Err, hello. We're always happy to see guests, but...}
{109}{}{呃，你好。我们总是很高兴见到客人，但是...}
#{110}{}{Err, hello. We're always happy to see guests... Unlike our neighbors...}
{110}{}{呃，你好。我们总是很高兴见到客人...不像我们的邻居...}
#{111}{}{Your neighbors don't talk much...}
{111}{}{你的邻居不怎么说话...}
#{112}{}{Goodbye.}
{112}{}{再见。}
#{113}{}{Exactly. They weren't like that all the time. But since Mark disappeared, it seems they're getting ready for "payback".}
{113}{}{确切地。他们不是一直这样。但自从马克失踪后，他们似乎正准备“报复”。}
#{114}{}{Uh, "payback"?}
{114}{}{呃，“回报”？}
#{115}{}{Mister Wright doesn't like people who let him down. Mark did. Now somebody has to pay, understand? I pity the old geezers, but they are gonna die soon anyway.}
{115}{}{赖特先生不喜欢让他失望的人。马克做到了。现在总得有人付钱，明白吗？我同情那些老家伙，但他们很快就会死的。}
#{116}{}{What happened to Mark?}
{116}{}{马克怎么了？}
#{117}{}{Well... I think I heard something about that, but I can't really remember anymore... Maybe you have something to refresh my memory... If you catch my drift.}
{117}{}{好...我想我听说了一些，但我已经记不起来了...也许你有什么东西可以让我记忆犹新...如果你明白我的意思。}
#{118}{}{Of course, I understand. Would 100 bucks be enough?}
{118}{}{当然，我明白。100美元够吗？}
#{119}{}{Do you know who I am or who my boss is? I think it's best if you don't. Let's just say he gets information out of people much more quickly than me.}
{119}{}{你知道我是谁还是我的老板？我想你最好不要这样。就说他从别人那里得到信息比我快得多吧。}
#{120}{}{I know one trick I can perform on your fingers that might help. Want to find out?}
{120}{}{我知道一个我可以在你手指上表演的把戏可能会有帮助。想知道吗？}
#{121}{}{How much? Why not...}
{121}{}{多少钱？为什么不...}
#{122}{}{Here's the cash.}
{122}{}{这是现金。}
#{123}{}{Oh, thank you sir. [he sticks the money into a pocket] It's good that you came to see us.}
{123}{}{哦，谢谢你，先生。[他把钱塞进口袋]你来看我们真好。}
#{124}{}{Now, what did you hear?}
{124}{}{你听到什么了？}
#{125}{}{It was late at night. Mark returned all thin, wounded and covered in road dust. He had an argument with his family, we listened through the wall... They wanted Mark to run away somewhere up north. Shit, that's exactly what he did, left his own family, damn coward! All because something happened when doing a job for Mr. Wright and he couldn't finish what he started. Yeah, pretty tough luck.}
{125}{}{已经是深夜了。马克回来时全身都很瘦，受了伤，身上沾满了道路上的灰尘。他和家人吵架了，我们隔着墙听着...他们想让马克逃到北方某个地方。妈的，他就是这么做的，离开了自己的家庭，该死的懦夫！都是因为在为莱特先生工作时发生了一些事情，他无法完成他开始的工作。是啊，真倒霉。}
#{126}{}{Thank you for the info. I've gotta go now. Oh, and this talk never happened.}
{126}{}{谢谢你的信息。我得走了。哦，这次谈话从来没有发生过。}
#{127}{}{Turns out Mark ran away up north.}
{127}{}{结果马克逃到了北方。}
#{128}{}{Oh, I understand... Err, I'll be happy to help your boss... Any way I can. No problem.}
{128}{}{哦，我明白...呃，我很乐意帮助你的老板...尽我所能。没问题。}
#{129}{}{W-wait... I'll be glad to help.}
{129}{}{等等...我很乐意帮忙。}
#{130}{}{Don't make me laugh. Do you know who owns these slums? I'm talking about Wright, Mister Wright. He would like us to keep turning him a profit, so you can keep your tricks to yourself.}
{130}{}{别逗我笑。你知道这些贫民窟是谁的吗？我说的是赖特，赖特先生。他想让我们继续给他赚一笔钱，这样你就可以独善其身了。}
#{131}{}{You were lucky this time.}
{131}{}{你这次很幸运。}
#{1123}{}{Oh, thank you ma'am. [he sticks the money into a pocket] It's good that you came to see us.}
{1123}{}{哦，谢谢你，女士。[他把钱塞进口袋]你来看我们真好。}
