#{100}{}{You see a slave.}
{100}{}{你看到一个奴隶。}
#{101}{}{This tough, tanned slave looks strikingly different from the others.}
{101}{}{这个强壮的，晒黑的奴隶看起来和其他人有着显著的不同。}
#{102}{}{Thank you, wanderer.}
{102}{}{谢谢你，流浪者。}
#{110}{}{Me no be knowing you, paleface.}
{110}{}{我不认识你，白脸。}
#{111}{}{I don't know you either. Er, that is what you meant to say, right?}
{111}{}{我也不认识你。呃，你就是这个意思，对吧？}
#{112}{}{Paleface? That's what the Cheyenne called me. Are you from there?}
{112}{}{脸色苍白？夏延人就是这么叫我的。你是那里人吗？}
#{113}{}{I can't be bothered to try to decipher that. Bye.}
{113}{}{我不想费心去破译它。再见。}
#{114}{}{Me be Gishiyash the Quiet River, of the Cheyenne to the north. Me be slave of evil men, who took me when me be returning from hunting. Now they be making me watch brahmin. Me be hating it! Me being hunter, not shepherd!}
{114}{}{我是吉希雅，平静的河流，夏延河的北面。我是恶人的奴隶，他们在我打猎回来的时候带走了我。现在他们让我看双头牛。我讨厌它！我是猎人，不是牧羊人！}
#{115}{}{I have good news. Your brother Acabidab asked me to free you.}
{115}{}{我有个好消息。你哥哥阿卡比达要我释放你。}
#{116}{}{Is it really so bad here?}
{116}{}{这里真的这么糟吗？}
#{117}{}{Would you like to go back home?}
{117}{}{你想回家吗？}
#{118}{}{We'll talk later.}
{118}{}{我们稍后再谈。}
#{119}{}{What if I helped you escape?}
{119}{}{如果我帮你逃走呢？}
#{120}{}{Hmm, not be bad for every slave. Many here be happy with master telling them what to be doing. But me be born free! Me be proud! Me be Cheyenne, not slave!}
{120}{}{嗯，对每个奴隶来说都不错。这里的许多人很高兴师父告诉他们该做什么。但我生来就是自由的！让我骄傲！我是夏延人，不是奴隶！}
#{121}{}{Cheyenne be waiting for me. Me be knowing this. Me be carrying Cheyenne in me soul. If... If me could find Cheyenne, we all be celebrating. But me be trapped in this cage instead.}
{121}{}{夏延在等我。让我知道这一点。我的灵魂里带着夏延。如果...如果我能找到夏延，我们都会庆祝的。但我却被困在这个笼子里。}
#{122}{}{Mountain air be cold... But also be bringing rain. If you be wanting help me and Cheyenne, thank you. But it will not be easy. The guards be keeping me here, and me cannot be free while me be wearing this [he points to a shock collar around his neck]. Can you be helping?}
{122}{}{山上的空气很冷...但也带来了雨水。如果你想帮助我和夏延，谢谢。但这并不容易。卫兵把我关在这里，我戴着这个不能自由（他指着脖子上的防震圈）。你能帮忙吗？}
#{123}{}{First, I'll talk to your master and ask him to let you go.}
{123}{}{首先，我要和你的主人谈谈，让他放你走。}
#{124}{}{I'll take care of the collar, then we'll fight our way out. How does that sound?}
{124}{}{我来处理领子，然后我们就拼出来。听起来怎么样？}
#{125}{}{Tell me about yourself again.}
{125}{}{再跟我说说你自己。}
#{126}{}{Elder in the big house be smart. Maybe free me if he be getting more in return. But me be thinking he be wanting to own the sky itself.}
{126}{}{大房子里的长者要聪明。如果他能得到更多的回报，也许能释放我。但我认为他想拥有天空。}
#{127}{}{Other slaves be saying small house next to barn be controlling collars. Slaves be saying small house has "generator". Me no be knowing what be happening in there. But maybe you be knowing how to be stopping it.}
{127}{}{其他奴隶说谷仓旁边的小房子控制着项圈。奴隶们说小房子里有“发电机”。我不知道那里发生了什么。但也许你知道如何阻止它。}
#{128}{}{I have good news. You're free!}
{128}{}{我有个好消息。你自由了！}
#{129}{}{[You go through the formalities of freeing the man and proceeding to the exit. He warily looks back at the guards, rubbing his hand over his now bare neck.] }
{129}{}{[你去办理释放那个人的手续，然后走到出口。他小心翼翼地回头看着卫兵，用手捂着他现在光秃秃的脖子。]}
#{130}{}{So, will you go back to the Cheyenne now?}
{130}{}{那么，你现在回夏延去吗？}
#{131}{}{Me be going alone. Me be knowing how to be finding food and water on the way. If you be traveling to Cheyenne, please be finding me.}
{131}{}{我要一个人去。我知道如何在路上找到食物和水。如果你要去夏延，请找我。}
#{132}{}{Good luck on the road, Gishiyash.}
{132}{}{祝你在路上好运，吉希亚什。}
#{133}{}{That's a pretty dumb idea, but it's your choice. If you get to your tribe in one piece, maybe we'll meet again. Goodbye.}
{133}{}{那是个相当愚蠢的主意，但这是你的选择。如果你能完整地到达你的部落，也许我们还会再见面。再见。}
#{134}{}{Before leaving, Gishiyash points out his tribe's location on your Pip-boy map.}
{134}{}{在离开之前，吉希亚什指出他的部落在你的皮普男孩地图上的位置。}
#{140}{}{The guards are dead. Get out of here, faster.}
{140}{}{卫兵死了。快点离开这里。}
#{141}{}{Me no be leaving. This collar be killing me if me be going too far.}
{141}{}{我不想离开。如果我走得太远，这个领子会把我累死的。}
#{142}{}{I turned off the collars. Take it off and climb over the fence.}
{142}{}{我把衣领关了。把它脱下来，爬过篱笆。}
#{143}{}{I'll help you get it off.}
{143}{}{我帮你把它弄下来。}
#{144}{}{This be changing things.}
{144}{}{这将改变一切。}
#{145}{}{[You easily disarm the collar.] }
{145}{}{[你很容易解除项圈的武装。]}
#{146}{}{[The slave defiantly tears off the collar.] }
{146}{}{[奴隶挑衅地撕掉衣领。]}
#{147}{}{Me be thanking you, but me must be asking you for another favor.}
{147}{}{我很感谢你，但我一定是想请你再帮个忙。}
#{148}{}{[You carefully inspect the device. You come to the realization that it is well beyond your abilities.]}
{148}{}{[请仔细检查设备。你意识到这远远超出了你的能力。]}
#{149}{}{Sorry, I need to check something out first. I'll be back.}
{149}{}{对不起，我得先检查一下。我会回来的。}
#{150}{}{You be saving me, wanderer! When me be returning to Cheyenne, me be telling them of your help. Thank you!}
{150}{}{你在救我，流浪汉！当我回到夏延时，我会告诉他们你的帮助。谢谢您！}
#{151}{}{What do you need?}
{151}{}{你需要什么？}
#{152}{}{Me must be going through Reno to escape. When me be hiding from gecko, gecko must not be seeing me. But when me be hiding from people, people must not be noticing me. Me be needing clothes like Reno people be wearing, so no one be knowing me be escaped from slave's cage.}
{152}{}{我一定要经过雷诺才能逃走。当我躲着壁虎的时候，壁虎一定没看见我。但是当我躲着别人的时候，人们一定不会注意到我。我需要雷诺人穿的衣服，所以没人知道我是从奴隶的笼子里逃出来的。}
#{153}{}{Let's see what I've got.}
{153}{}{让我们看看我有什么。}
#{154}{}{I'll see what I can find. Hold on for a bit.}
{154}{}{我看看能找到什么。等一下。}
#{155}{}{Me be needing clothes that be making me look like Reno people. Do you be having that?}
{155}{}{我需要让我看起来像雷诺人的衣服。你要吃吗？}
#{156}{}{[Give: }
{156}{}{[给出：}
#{157}{}{]}
{157}{}{]}
#{158}{}{[Next]}
{158}{}{[下一步]}
#{159}{}{[Back]}
{159}{}{[后退]}
#{160}{}{Hold on for a bit. I'll try and find something to help you.}
{160}{}{等一下。我会设法帮你的。}
#{1102}{}{Thank you, wanderer.}
{1102}{}{谢谢你，流浪者。}
#{1110}{}{Me no be knowing you, paleface.}
{1110}{}{我不认识你，白脸。}
#{1142}{}{I turned off the collars. Take it off and climb over the fence.}
{1142}{}{我把衣领关了。把它脱下来，爬过篱笆。}
#{1150}{}{You be saving me, wanderer! When me be returning to Cheyenne, me be telling them of your help. Thank you!}
{1150}{}{你在救我，流浪汉！当我回到夏延时，我会告诉他们你的帮助。谢谢您！}
