#{100}{}{You see a Reno local.}
{100}{}{你看到一个雷诺本地人。}
#{110}{}{This day in Reno is marked by the hand of Devil.}
{110}{}{雷诺的这一天是魔鬼之手的标志。}
#{111}{}{We're all in this together. Don't we understand that?}
{111}{}{我们都在一起。我们不明白吗？}
#{112}{}{Someone's going to die tonight. I can feel it.}
{112}{}{今晚会有人死的。我能感觉到。}
#{113}{}{I'm so sick of the noises at night...}
{113}{}{我讨厌晚上的噪音。。。}
#{114}{}{If I ever the chance, I'll move to hell. It has to be better than this.}
{114}{}{如果有机会，我就去地狱。一定比这个好。}
#{115}{}{I can't stop thinking these are Reno's last days.}
{115}{}{我不停地想这是雷诺的最后几天。}
#{116}{}{We have no collars, but we still live like slaves.}
{116}{}{我们没有项圈，但我们仍然像奴隶一样生活。}
#{117}{}{Damn this war!}
{117}{}{该死的战争！}
#{118}{}{}
{118}{}{}
#{119}{}{}
{119}{}{}
#{120}{}{This is my home! Stop pushing me around or you will regret it!}
{120}{}{这是我的家！别逼我了，否则你会后悔的！}
#{121}{}{If I spill a one drop of my soup because of you...}
{121}{}{如果我因为你洒了一滴汤。。。}
#{122}{}{Find somewhere else to do that sort of thing!}
{122}{}{找别的地方做那种事！}
#{123}{}{Don't do that!}
{123}{}{别那么做！}
#{129}{}{I miss my husband... *sobs* after that drug dealer died, he had nowhere else to buy his medicine...}
{129}{}{我想念我的丈夫。。。*那个毒贩死后，他没有别的地方可以买他的药。。。}
#{130}{}{Don't mind them, they're always fighting. Just give them a reason.}
{130}{}{别理他们，他们总是打架。给他们一个理由。}
#{131}{}{How would you like it if I barged into YOUR home and started asking questions?}
{131}{}{如果我闯进你家开始问问题，你会怎么想？}
#{132}{}{I have nothing to tell you.}
{132}{}{我没什么要告诉你的。}
#{133}{}{I'd love to chat, but I'm already late to the night club...}
{133}{}{我很想聊天，但我去夜总会已经迟到了。。。}
#{134}{}{It's... You! Wow! I'm a big fan - I catch your dances whenever I can!}
{134}{}{这是。。。你！哇！我是你的超级粉丝-我随时都能看到你的舞蹈！}
#{135}{}{Huh? Don't bother me. I lost my ticket to the night club, and I'm looking for it.}
{135}{}{呵呵？别打扰我。我把去夜总会的票丢了，我正在找。}
#{136}{}{Hey, good performance! I caught it at Mom's club. Nice place...}
{136}{}{嘿，表现不错！我在妈妈的俱乐部看到的。好地方。。。}
#{137}{}{Do you mind? I'm having my breakfast.}
{137}{}{你介意吗？我在吃早餐。}
#{138}{}{Leave me alone. I'm eating lunch.}
{138}{}{别管我。我在吃午饭。}
#{139}{}{Don't interrupt my dinner.}
{139}{}{别打断我的晚餐。}
#{140}{}{You're not welcome here.}
{140}{}{这里不欢迎你。}
#{141}{}{I don't even want to touch the doorknobs in this place! Also, I dropped my bobby pin in the washroom sink. Ew!}
{141}{}{我都不想碰这个地方的门把手！还有，我的别针掉在洗手间的水槽里了。电子战！}
#{142}{}{Oh, how nice of you! Thanks!}
{142}{}{哦，你真好！谢谢！}
#{143}{}{This lady definitely likes you.}
{143}{}{这位女士肯定喜欢你。}
#{145}{}{I must a dreaming! A celebrity, here, in my home?!}
{145}{}{我一定是在做梦！一个名人，在这里，在我家？！}
#{146}{}{My god, it's you! Can I have your autograph?}
{146}{}{天哪，是你！我可以要你的签名吗？}
#{147}{}{It's an honor, seeing you!}
{147}{}{很荣幸见到你！}
#{148}{}{I saw your latest performance. Amazing!}
{148}{}{我看了你最近的表演。太神了！}
#{149}{}{}
{149}{}{}
#{150}{}{You see a ragged-looking man. He looks bored.}
{150}{}{你看到一个衣衫褴褛的人。他看起来很无聊。}
#{151}{}{You see a ragged-looking man. His eyes are dull.}
{151}{}{你看到一个衣衫褴褛的人。他的眼睛迟钝。}
#{152}{}{You see a ragged-looking man. He looks hung over.}
{152}{}{你看到一个衣衫褴褛的人。他看起来醉醺醺的。}
#{153}{}{You see a ragged-looking man. He looks a little tipsy.}
{153}{}{你看到一个衣衫褴褛的人。他看起来有点醉了。}
#{154}{}{You see a ragged-looking man. He gives you an irritated glance, and then ignores you.}
{154}{}{你看到一个衣衫褴褛的人。他恼怒地瞥了你一眼，然后不理你。}
#{155}{}{You see a ragged-looking man. He looks angry.}
{155}{}{你看到一个衣衫褴褛的人。他看起来很生气。}
#{160}{}{You see a ragged-looking woman. She looks bored.}
{160}{}{你看到一个衣衫褴褛的女人。她看起来很无聊。}
#{161}{}{You see a ragged-looking woman. Her eyes are dull.}
{161}{}{你看到一个衣衫褴褛的女人。她的眼睛迟钝。}
#{162}{}{You see a ragged-looking woman. She's staring a thousand miles away.}
{162}{}{你看到一个衣衫褴褛的女人。她凝视着千里之外。}
#{163}{}{You see a ragged-looking woman. She looks a little drunk.}
{163}{}{你看到一个衣衫褴褛的女人。她看起来有点醉了。}
#{164}{}{You see a ragged-looking woman. She gives you an irritated glance, and then ignores you.}
{164}{}{你看到一个衣衫褴褛的女人。她生气地瞥了你一眼，然后不理你。}
#{165}{}{You see a ragged-looking woman. When she catches your eye, she sneers.}
{165}{}{你看到一个衣衫褴褛的女人。当她抓住你的眼睛，她嘲笑。}
#{200}{}{We're busy.}
{200}{}{我们很忙。}
#{201}{}{What are you, blind? Get out!}
{201}{}{你是什么，瞎子？走出！}
#{202}{}{Leave us alone or we'll call security!}
{202}{}{别管我们，不然我们就叫保安了！}
#{203}{}{Watch yourself. I'm a very respected customer here.}
{203}{}{小心点。我是这里非常受尊敬的顾客。}
#{204}{}{Don't watch me, you freak!}
{204}{}{别看我，你这个怪胎！}
#{205}{}{I don't do gang-bangs, okay?}
{205}{}{我不搞黑帮，好吗？}
#{206}{}{Get out of my room!}
{206}{}{滚出我的房间！}
#{207}{}{What the hell are you doing here?}
{207}{}{你到底在这里干什么？}
#{208}{}{Rude!}
{208}{}{粗鲁无礼！}
#{209}{}{Stop it!}
{209}{}{住手！}
#{210}{}{What are you looking at?}
{210}{}{你在看什么？}
#{211}{}{Do you mind?}
{211}{}{你介意吗？}
#{212}{}{Get out of our room!}
{212}{}{滚出我们的房间！}
#{213}{}{You looking to start up a threesome?}
{213}{}{你想开始三人行吗？}
#{214}{}{Get the fuck out, pervert!}
{214}{}{滚出去，变态！}
#{215}{}{What is your problem?}
{215}{}{你有什么问题？}
#{216}{}{I'm busy.}
{216}{}{我很忙。}
#{217}{}{I'm too tired...}
{217}{}{我太累了。。。}
#{218}{}{Get out before I get *really* pissed!}
{218}{}{在我生气之前滚开！}
#{219}{}{Find yourself another one.}
{219}{}{再找一个。}
#{220}{}{She's mine.}
{220}{}{她是我的。}
#{1214}{}{Get the fuck out, bitch!}
{1214}{}{滚出去，婊子！}
