#{100}{}{You see a madam.}
{100}{}{你看到一位女士。}
#{101}{}{You see a madam named Betty Paige.}
{101}{}{你看到一位叫贝蒂·佩奇的女士。}
#{102}{}{You successfully changed the contraceptive.}
{102}{}{你成功地换了避孕药。}
#{103}{}{You enjoy an entire hour of passionate, tireless sex. The whore teaches you everything she knows.}
{103}{}{你享受了整整一个小时的激情，不知疲倦的性爱。妓女教你她所知道的一切。}
#{104}{}{It's not until the lights turn on that you see a vicious skin disease affecting the prostitute's genitals. You can only hope you didn't catch it.}
{104}{}{直到灯亮了，你才看到一种影响妓女生殖器的恶性皮肤病。你只能希望你没抓到它。}
#{105}{}{It's not until the lights turn on that you see a vicious skin disease affecting the prostitute's genitals. Hopefully, your protection worked.}
{105}{}{直到灯亮了，你才看到一种影响妓女生殖器的恶性皮肤病。希望你的保护起作用了。}
#{106}{}{It's not until the lights turn on that you see a vicious skin disease affecting the prostitute's genitals. But today, you got lucky.}
{106}{}{直到灯亮了，你才看到一种影响妓女生殖器的恶性皮肤病。但今天，你很幸运。}
#{107}{}{Soon, streets will talk of the madam who tragically met her end to a sudden, mysterious "disease".}
{107}{}{很快，街上就会有人谈论这位女士，她不幸遭遇了一场突然而神秘的“疾病”。}
#{110}{}{Thanks for the light. I'm sick of the darkness - at some nights you can't tell customers from thugs...}
{110}{}{谢谢你的光。我厌倦了黑暗-有些夜晚你无法分辨顾客和暴徒...}
#{111}{}{ If you want one of my girls, I'll give you a small discount for your trouble.}
{111}{}{如果你想要我的一个女孩，我会给你一个小的折扣。}
#{112}{}{ Hmm. You're still here, even after your illness? I've lost a lot of my own girls to it. Here, take a bit of money. Treat yourself to something nice.}
{112}{}{嗯。你病后还在这里？我失去了很多自己的女儿。来，拿点钱。好好招待自己。}
#{113}{}{Thanks.}
{113}{}{谢谢。}
#{114}{}{You sure know how to bring in a customer. Let's see what you've got in "stock".}
{114}{}{你真会招揽顾客。让我们看看你有什么存货。}
#{115}{}{Thank you, but not today.}
{115}{}{谢谢，但今天不行。}
#{116}{}{Hey, baby, get the hell out of here! No one would fuck your ugly ass. Even whores have limits!}
{116}{}{嘿，宝贝，滚出去！没人会操你的丑屁股。连妓女都有极限！}
#{117}{}{Have you made up your mind?}
{117}{}{你下定决心了吗？}
#{118}{}{I'm looking. Do you have any suggestions?}
{118}{}{我在找。你有什么建议吗？}
#{119}{}{Not today.}
{119}{}{今天不行。}
#{120}{}{If you've got the money, we have whatever you need. My girls will give you any kind of sex you want.}
{120}{}{如果你有钱，我们有你需要的一切。我的女儿们会给你任何你想要的性。}
#{121}{}{How much?}
{121}{}{多少？}
#{122}{}{What kinds of sex are there?}
{122}{}{有什么样的性行为？}
#{123}{}{Thank you, but I'm not interested.}
{123}{}{谢谢，但我不感兴趣。}
#{124}{}{Uh... [she gives you a quizzical look] ...you don't know? Listen, hire my girls and you can find out. Actions speak louder than words, yeah?}
{124}{}{Uh...[她疑惑地看了你一眼]…你不知道？听着，雇我的女儿，你会发现的。行动胜于雄辩，是吗？}
#{125}{}{Is it... Safe?}
{125}{}{它是...安全吗？}
#{126}{}{Oh yeah, yeah! Of course! Perfectly safe... The same-sex option is the safest... Anyway, I'm not talking about that whores near the nightclub. Gonna catch something nasty with those girls.}
{126}{}{哦，耶，耶！当然！非常安全...同性选择是最安全的...总之，我不是说夜总会附近的妓女。我要和那些女孩搞点不愉快的事。}
#{127}{}{Nasty? Why?}
{127}{}{恶心？为什么？}
#{128}{}{Oh, they don't even wash, dear. They'll get you sick, they're *crawling* with it. But not my girls - they're all clean.}
{128}{}{哦，他们甚至不洗，亲爱的。他们会让你生病的，他们在爬。但不是我的女儿-她们都是清白的。}
#{129}{}{ dollars. Best price in the city.}
{129}{}{美元。这个城市最好的价格。}
#{130}{}{For us girls, I can knock a bit off the price. Just for you, honey. Let's say...}
{130}{}{对我们女孩子来说，我可以把价钱降一点。只为你，亲爱的。比如说...}
#{131}{}{ dollars. That's a special price, just for you and your boss.}
{131}{}{美元。这是一个特价，只给你和你老板。}
#{132}{}{Here's the money. It had better be worth it.}
{132}{}{这是钱。最好是值得的。}
#{133}{}{It'll be worth every penny. Who do you want? They're yours for an hour.}
{133}{}{它值每一分钱。你想要谁？他们是你的一个小时。}
#{134}{}{[Choose a prostitute and head up to a room.]}
{134}{}{[选择一个妓女，然后去一个房间。]}
#{135}{}{You seem to get a lot of business. What's your secret?}
{135}{}{你好像有很多生意。你的秘密是什么？}
#{136}{}{Locals know we're the best in the city. It's a status thing, really, to come here. And out-of-towners, well, they need someone that'll treat them right after a long journey. But you know, it's core, it's just the way people are. *Everybody* wants what we're selling. It's just human instinct.}
{136}{}{当地人知道我们是城里最好的。来这里真的是一种地位。外地人，嗯，他们需要一个在长途旅行后马上治疗他们的人。但你知道，这是核心，这只是人们的方式。*每个人都想要我们卖的东西。这只是人类的本能。}
#{137}{}{I see.}
{137}{}{我懂了。}
#{138}{}{I'll go then.}
{138}{}{那我就去。}
#{139}{}{They say you have a good relationship with Thompson. Is that true?}
{139}{}{他们说你和汤普森关系很好。是真的吗？}
#{140}{}{Oh, Thompson... You know, he's gonna make me his wife after he wins this war... Wait, why am I telling you this? Never mind, it's personal.}
{140}{}{哦，汤普森...你知道，他赢了这场战争后会娶我为妻...等等，我为什么要告诉你这些？没关系，这是私人的。}
#{141}{}{Hey, you just looking or... Oh, wow, it's you! You came to the right place. Someone like you deserves only the best.}
{141}{}{嘿，你只是看看还是...哦，哇，是你！你来对地方了。像你这样的人只配得到最好的。}
#{150}{}{Mr. Thompson sent me to look into the attacks on your employees.}
{150}{}{汤普森先生派我来调查对你们雇员的袭击。}
#{151}{}{[Her smile disappears] Really? It used to be good here, until those fucking cocksuckers moved in. Roughing up my girls, threatening me - ME! I was here first! You ought to show them who really owns this street.}
{151}{}{[她的微笑消失]真的吗？以前这里很好，直到那些混蛋搬进来。粗暴对待我的女儿，威胁我-我！我先来的！你应该让他们知道这条街真正的主人是谁。}
#{152}{}{What do you know about them?}
{152}{}{你对他们了解多少？}
#{153}{}{Why do you think they're doing it?}
{153}{}{你觉得他们为什么这么做？}
#{154}{}{You want me to kill them?}
{154}{}{你想让我杀了他们？}
#{155}{}{And why should Mr. Thompson solve your problems for free?}
{155}{}{为什么汤普森先生要免费解决你的问题？}
#{156}{}{Okay. I'll get it done.}
{156}{}{可以。我会搞定的。}
#{157}{}{I know one of those boys... He's named Stinky Grizzly. I don't know if they're local or not, but they started hanging around here recently. They think they're such hot shit... They've got no idea the shit they've stepped in.}
{157}{}{我认识其中一个男孩...他叫臭灰熊。我不知道他们是不是本地人，但他们最近开始在这里闲逛。他们觉得自己是个混蛋...他们根本不知道自己干了什么。}
#{158}{}{Do you really care? Did Mr. Thompson send you to deal with this problem or to just ask a lot of stupid questions?}
{158}{}{你真的在乎吗？汤普森先生派你来是为了解决这个问题还是只是问了很多愚蠢的问题？}
#{159}{}{I don't care what you do to them, I just don't want to see them interrupting with my business anymore.}
{159}{}{我不在乎你对他们做了什么，我只是不想再看到他们打断我的生意。}
#{160}{}{[She smirks] Oh, let me guess. He didn't pay you, huh? And he's not going to, is he? Damn, a sucker really is born every minute! I pay him weekly for protection, right on time, and when I finally need him he sends an idiot like you. Why am I not surprised? Listen, if you want to make some money, don't try to shake me down. Grow a spine and do your fucking *job* instead!}
{160}{}{哦，让我猜猜。他没付钱给你，嗯？他不会的，是吗？该死的，一个笨蛋真的每分钟都在生！我每周付他一次保护费，准时，当我终于需要他时，他就派你这样的白痴来。为什么我不感到惊讶？听着，如果你想赚点钱，别想吓唬我。长一根脊梁，做你他妈的工作！}
#{161}{}{I don't like your tone. Give me the money, or I'll show you what real trouble looks like.}
{161}{}{我不喜欢你的语气。把钱给我，不然我就让你看看真正的麻烦是什么样子。}
#{162}{}{Or what? Whattaya gonna do, huh? I'm your boss's top bitch. Touch one hair on my head, and you'll wish you'd never been born.}
{162}{}{或者什么？你打算怎么办？我是你老板的大婊子。摸摸我头上的一根头发，你会希望你从未出生。}
#{163}{}{I'm the one solving this problem. I'll decide what information is important or not.}
{163}{}{我是解决这个问题的人。我来决定什么信息重要与否。}
#{164}{}{Yeah? Fine, I'll tell you what I think. They probably thought they could take some territory for themselves while all the big boys are fighting. Fucking stupid. But I guess they don't know how things work around here, since I've never seen them in the neighborhood before this.}
{164}{}{是 啊？好吧，我告诉你我的想法。他们可能认为，当所有的大男孩都在战斗时，他们可以为自己占领一些领地。他妈的蠢。但我猜他们不知道这里的情况，因为我以前从没在附近见过他们。}
#{165}{}{I've solved your problem.}
{165}{}{我已经解决了你的问题。}
#{166}{}{Already? I guess you're good for something after all. Tell Thompson I'm pleased with your work.}
{166}{}{已经开始了？我想你终究还是做得很好的。告诉汤普森我对你的工作很满意。}
#{1117}{}{Have you made up your mind?}
{1117}{}{你下定决心了吗？}
#{1161}{}{I don't like your tone. Give me the money, or I'll show you what real trouble looks like.}
{1161}{}{我不喜欢你的语气。把钱给我，不然我就让你看看真正的麻烦是什么样子。}
#{1163}{}{I'm the one solving this problem. I'll decide what information is important or not.}
{1163}{}{我是解决这个问题的人。我来决定什么信息重要与否。}
