#{100}{}{You see a madam.}
{100}{}{你看到一位女士。}
#{101}{}{You see a relaxed older woman named Lilly st. Cyr.}
{101}{}{你看到一个放松的老妇人，名叫莉莉·圣西尔。}
#{102}{}{You'll never meet another like the busty wonder Nanny! Her third breast, swollen with milk, just drives you wild!}
{102}{}{你再也见不到像这位大腹便便的神奇保姆了！她的第三个胸脯，被牛奶弄肿了，简直让你疯了！}
#{103}{}{You gently and passionately fuck for an entire hour. It is a very... Educational experience.}
{103}{}{你温柔而热情地干了整整一个小时。这是一个非常。。。教育经验。}
#{104}{}{Under the dim lamplight, you see that a vicious skin disease has affected the prostitute's genitals. You can only hope you weren't infected.}
{104}{}{在昏暗的灯光下，你看到一种恶性皮肤病感染了妓女的生殖器。你只能希望自己没有被感染。}
#{105}{}{Under the dim lamplight, you see that a vicious skin disease has affected the prostitute's genitals. Hopefully, the condom provided adequate protection.}
{105}{}{在昏暗的灯光下，你看到一种恶性皮肤病感染了妓女的生殖器。希望避孕套能提供足够的保护。}
#{106}{}{Under the dim lamplight, you see that a vicious skin disease has affected the prostitute's genitals. Nonetheless, you do the deed and everyone is satisfied in the end.}
{106}{}{在昏暗的灯光下，你看到一种恶性皮肤病感染了妓女的生殖器。尽管如此，你做了这件事，最后大家都很满意。}
#{110}{}{Sorry, honey. I thought nothing was too much for my girls, but one look at your face proves me wrong.}
{110}{}{对不起，亲爱的。我以为对我的女儿们来说什么都不过分，但一眼你的脸就证明我错了。}
#{111}{}{Hello there, honey. You like my girls? They'll like you too, for the right price.}
{111}{}{你好，亲爱的。你喜欢我的女孩吗？他们也会喜欢你的，价格合适。}
#{112}{}{Just looking around. What do you have to offer?}
{112}{}{只是四处看看。你能提供什么？}
#{113}{}{Nothing for today.}
{113}{}{今天没什么。}
#{114}{}{Are there any others like you in the city?}
{114}{}{城里还有像你这样的人吗？}
#{115}{}{Oh, you stay away from those girls next to the Cotton Club. It breaks my heart, I feel so sorry for them - that old woman works them terribly, makes them take any awful, dirty man that comes by and doesn't even give them time to wash after. It's like she's hell bent on putting them in an grave early... And her customers too. You want nothing to do with them, trust me.}
{115}{}{哦，你离棉花俱乐部旁边的那些女孩远点。这让我心碎，我为他们感到难过——那个老太婆把他们弄得一团糟，让他们带走任何一个来过的讨厌的，肮脏的男人，甚至不给他们洗衣服的时间。好像她一心想早点把他们埋进坟墓。。。还有她的顾客。你不想和他们有任何关系，相信我。}
#{116}{}{I see. Can I ask you something else?}
{116}{}{我懂了。我能问你点别的吗？}
#{117}{}{Thanks for the heads up, but I have to go.}
{117}{}{谢谢你的提醒，但我得走了。}
#{120}{}{On, don't you worry about that. For the right price, my girls will give you any sort of pleasure you want.}
{120}{}{拜托，别担心。只要价钱合适，我的女儿们会给你任何你想要的乐趣。}
#{121}{}{And what is that price?}
{121}{}{那价格是多少？}
#{122}{}{What sorts of pleasure are there?}
{122}{}{有什么乐趣？}
#{123}{}{Thank you, but I don't need anything right now.}
{123}{}{谢谢，但我现在什么都不需要。}
#{124}{}{[She looks at you quizzically] You... Really don't know? Well... My girls will be happy to teach you. And don't worry... Learning's the best part.}
{124}{}{[她疑惑地看着你]你。。。真的不知道？好。。。我的女儿们会很乐意教你的。别担心。。。学习是最好的部分。}
#{125}{}{Is it... Safe?}
{125}{}{它是。。。安全吗？}
#{126}{}{Of course, honey! All my girls are clean! Not like those girls down by the Cotton Club... [shudders]}
{126}{}{当然，亲爱的！我所有的女孩都是清白的！不像棉花俱乐部的那些女孩。。。[颤抖]}
#{127}{}{What's wrong with the girls by the Cotton Club?}
{127}{}{棉花俱乐部的女孩们怎么了？}
#{128}{}{Honey, they don't even wash! You have to stay away from them if you don't want to get sick. But you don't have to worry about that from my girls - we're careful to always stay clean and prevent any... Baby trouble. You understand?}
{128}{}{亲爱的，他们甚至不洗！如果你不想生病，就得离他们远点。但你不必担心我的女儿们-我们总是小心保持清洁，防止任何。。。婴儿问题。你明白吗？}
#{129}{}{ dollars. You won't find a better price for service this fine.}
{129}{}{美元。这么好的服务，你找不到更好的价格了。}
#{130}{}{You're in luck, honey. There's a special deal on lesbian sex: }
{130}{}{你很幸运，亲爱的。关于女同性恋性爱有一个特别的协议：}
#{131}{}{ dollars. And, of course, we have a special price for you and your boss.}
{131}{}{美元。当然，我们对你和你的老板还有特价。}
#{132}{}{Here's the money. This had better be worth it.}
{132}{}{这是钱。这最好是值得的。}
#{133}{}{I promise it won't, honey - it'll be worth much more. Who would you like? The blond Susie, the brunette Charlotte, the unforgettable Melanie, or our one-of-a-kind nanny, Stephanie?}
{133}{}{我保证不会的，亲爱的-会值很多钱的。你想要谁？金发的苏西，黑发的夏洛特，难忘的梅兰妮，还是我们独一无二的保姆斯蒂芬妮？}
#{134}{}{}
{134}{}{}
#{135}{}{Susie.}
{135}{}{苏西。}
#{136}{}{Charlotte.}
{136}{}{夏洛特。}
#{137}{}{Melanie.}
{137}{}{梅勒妮。}
#{138}{}{Stephanie, the nanny.}
{138}{}{斯蒂芬妮，保姆。}
#{139}{}{Can I get them all at once?}
{139}{}{我能一次把它们都拿出来吗？}
#{140}{}{Tell me, which of them would you recommend?}
{140}{}{告诉我，你推荐哪一种？}
#{141}{}{I knew it the second I laid eyes on you. Good choice, honey.}
{141}{}{我一看到你就知道了。不错的选择，亲爱的。}
#{142}{}{[You go to a small apartment.]}
{142}{}{[你去一个小公寓。]}
#{143}{}{Now, you understand she's a *special* treat for *special* tastes. That'll be an extra 75 dollars. Or do you want to choose one of the others?}
{143}{}{现在，你明白了，她是一个“特别的”享受，特别的品味。那要额外加75美元。或者你想从其他人中选一个？}
#{144}{}{She'll be worth it. I'm sure of it.}
{144}{}{她会值得的。我敢肯定。}
#{145}{}{A gangbang? Sure, honey, but you understand it won't be cheap. You'll have to pay for all four, so that's an extra }
{145}{}{帮帮？当然，亲爱的，但你知道这不会便宜的。你得付四个人的钱，所以这是额外的}
#{146}{}{ dollars. Are you alright with that?}
{146}{}{美元。你同意吗？}
#{147}{}{I'm sure it's worth it. Here's the money.}
{147}{}{我相信这是值得的。这是钱。}
#{148}{}{You won't regret it!}
{148}{}{你不会后悔的！}
#{149}{}{Well, all my girls are good. But you'll never meet another woman like the busty wonder nanny Stephanie. Trust me, honey, all the men go crazy for her!}
{149}{}{嗯，我所有的女孩都很好。但你再也见不到另一个像这位丰满的神奇保姆斯蒂芬妮那样的女人了。相信我，亲爱的，所有的男人都为她疯狂！}
#{150}{}{What's so special about her?}
{150}{}{她有什么特别之处？}
#{151}{}{[Winks] Why don't you find out?}
{151}{}{你为什么不知道？}
#{160}{}{I hear there was an attack around here. Did you see anything?}
{160}{}{我听说这附近有人袭击。你看到什么了吗？}
#{161}{}{Sorry, but we just ran for the night club when it all started. Some poor fella was shot, but I didn't know him. Funny, though, I never saw a shooter or even heard any shots. Maybe someone else around here can tell you more.}
{161}{}{抱歉，我们刚去夜总会，一切就开始了。有个可怜的家伙中枪了，但我不认识他。不过，有趣的是，我从没见过枪手，甚至没听到枪声。也许这里的其他人能告诉你更多。}
#{162}{}{Thanks for the help.}
{162}{}{谢谢你的帮助。}
