#{100}{}{You see coach.}
{100}{}{你看教练。}
#{101}{}{You see a veteran of many fights. Looks like he loves giving orders.}
{101}{}{你看到一个打过很多仗的老兵。看起来他喜欢发号施令。}
#{105}{}{I've taught you everything I know. I have nothing else for you.}
{105}{}{我把我知道的都教给你了。我没有别的东西给你了。}
#{106}{}{I'm proud to have been a part of your journey!}
{106}{}{我很自豪能成为你旅程的一部分！}
#{107}{}{Keep it up! You're unstoppable!}
{107}{}{坚持下去！你势不可挡！}
#{108}{}{You're the best butcher on the ring!}
{108}{}{你是拳击场上最好的屠夫！}
#{110}{}{Drop and give me twenty!}
{110}{}{给我二十块！}
#{111}{}{Who are you?}
{111}{}{你是谁？}
#{112}{}{Are you a coach? Could you train me?}
{112}{}{你是教练吗？你能训练我吗？}
#{113}{}{Not now, goodbye.}
{113}{}{现在不行，再见。}
#{114}{}{Who the hell gave you permission to talk, maggot?! You will only refer to me as SIR, am I clear?! I'm the coach! I turn whelps like you into real men! If I say jump, you jump! If I say run, you run! If I say kill, then you will most certainly kill!}
{114}{}{是谁允许你说话的，蛆虫？！你只能称我为先生，明白吗？！我是教练！我把你这样的小崽子变成了真正的男人！如果我说跳，你就跳！如果我说跑，你就跑！如果我说杀人，那你肯定会杀人！}
#{115}{}{I'm the coach! I turn whelps like you into real men! If I say jump, you jump! If I say run, you run! If I say kill, then you will most certainly kill!}
{115}{}{我是教练！我把你这样的小崽子变成了真正的男人！如果我说跳，你就跳！如果我说跑，你就跑！如果我说杀人，那你肯定会杀人！}
#{116}{}{Like hell! I don't waste my time on spineless wimps like you!}
{116}{}{见鬼去吧！我不会把时间浪费在像你这样没骨气的懦夫身上！}
#{117}{}{What's in it for me?}
{117}{}{对我有什么好处？}
#{118}{}{Chummer, your skills are brighter than the El Dorado lights! I don't have much to teach you. But, we could work a little, if you make it worth my while.}
{118}{}{楚默，你的技能比埃尔多拉多之光还要亮！我没什么可以教你的。但是，如果你让我觉得值得的话，我们可以做一点。}
#{119}{}{I don't need it, anyway...}
{119}{}{不管怎样，我不需要它...}
#{120}{}{Err... Cash, sir!}
{120}{}{呃...现金，先生！}
#{121}{}{That's right! I take 1000 bucks per session. No questions!}
{121}{}{这是正确的！我每节课收1000美元。没有问题！}
#{122}{}{Sure thing. Here's the money. When do we begin?}
{122}{}{当然。这是钱。我们什么时候开始？}
#{123}{}{Understood. I'll come back with the money.}
{123}{}{理解。我会带着钱回来的。}
#{124}{}{Right now! Hit the showers! MOVE!!!}
{124}{}{马上！去洗澡吧！移动！！！}
#{125}{}{Yes, sir!}
{125}{}{是的，先生！}
#{126}{}{Your right hook is on point! The rest is up to you. Come again when you've got a serious fight - we'll warm up!}
{126}{}{你的右钩子对了！剩下的就看你了。如果你真的打架了再来-我们会热身的！}
#{127}{}{Great. Warmed up, let's get to work!}
{127}{}{伟大的。准备好了，开始工作吧！}
#{128}{}{After an intensive session with the coach, your unarmed skill has increased by 5%.}
{128}{}{经过教练的强化训练，你的徒手技能提高了5%。}
#{129}{}{A lot of this coaching is old hat to you, but you've still increased your skills by 3%.}
{129}{}{很多这种指导对你来说都是老生常谈，但你的技能仍然提高了3%。}
#{130}{}{If I'm going to be all I can be, I'll need to use everything I can use, right? How about a little chemical help?}
{130}{}{如果我要做我能做的一切，我需要用我能用的一切，对吗？来点化学药品怎么样？}
#{131}{}{Is that some joke?! That's off limits around here! We ran all the dealers off! Don't even think of asking again!}
{131}{}{开什么玩笑？！这里禁止入内！我们把所有的毒贩都赶走了！别想再问了！}
#{132}{}{But I have a note!}
{132}{}{但我有一张纸条！}
#{133}{}{Fine.}
{133}{}{好的。}
#{134}{}{Right, that's it! Either you shut up and get the fuck out of here, or I beat your face to a pulp!}
{134}{}{对，就是这样！要么你闭嘴滚出去，要么我把你的脸打得粉碎！}
#{135}{}{You can try, old man!}
{135}{}{你可以试试，老头子！}
#{136}{}{Fine, I'm going.}
{136}{}{好吧，我去。}
#{1105}{}{I've taught you everything I know. I have nothing else for you.}
{1105}{}{我把我知道的都教给你了。我没有别的东西给你了。}
#{1106}{}{I'm proud to have been a part of your journey!}
{1106}{}{我很自豪能成为你旅程的一部分！}
#{1107}{}{Keep it up! You're unstoppable!}
{1107}{}{坚持下去！你势不可挡！}
#{1108}{}{You're the best butcher on the ring!}
{1108}{}{你是拳击场上最好的屠夫！}
#{1110}{}{Drop and give me twenty!}
{1110}{}{给我二十块！}
#{1114}{}{Who the hell gave you permission to talk, maggot?! You will only refer to me as SIR, am I clear?! I'm the coach! I turn pretenders like you into real fighters! If I say jump, you jump! If I say run, you run! If I say kill, then you will most certainly kill!}
{1114}{}{是谁允许你说话的，蛆虫？！你只能称我为先生，明白吗？！我是教练！我把你这种装模作样的人变成了真正的战士！如果我说跳，你就跳！如果我说跑，你就跑！如果我说杀人，那你肯定会杀人！}
#{1115}{}{I'm the coach! I turn pretenders like you into real fighters! If I say jump, you jump! If I say run, you run! If I say kill, then you will most certainly kill!}
{1115}{}{我是教练！我把你这种装模作样的人变成了真正的战士！如果我说跳，你就跳！如果我说跑，你就跑！如果我说杀人，那你肯定会杀人！}
#{1118}{}{Chummer, your skills are brighter than the El Dorado lights! I don't have much to teach you. But, we could work a little, if you make it worth my while.}
{1118}{}{楚默，你的技能比埃尔多拉多之光还要亮！我没什么可以教你的。但是，如果你让我觉得值得的话，我们可以做一点。}
#{1124}{}{Right now! Hit the showers! MOVE!!!}
{1124}{}{马上！去洗澡吧！移动！！！}
#{1126}{}{Your right hook is on point! The rest is up to you. Come again when you've got a serious fight - we'll warm up!}
{1126}{}{你的右钩子对了！剩下的就看你了。如果你真的打架了再来-我们会热身的！}
#{1131}{}{Is that some joke?! That's off limits around here! We ran all the dealers off! Don't even think of asking again!}
{1131}{}{开什么玩笑？！这里禁止入内！我们把所有的毒贩都赶走了！别想再问了！}
