#{100}{}{You see the match instigator.}
{100}{}{你看到比赛策划者了。}
#{101}{}{You see the ring instigator who accepts bets during a match.}
{101}{}{你可以看到在比赛中接受赌注的指环煽动者。}
#{102}{}{ dollars for }
{102}{}{美元}
#{103}{}{! Any more?!}
{103}{}{! 再？！}
#{104}{}{! Taking bets!}
{104}{}{! 打赌！}
#{110}{}{Ladies and Gentlemen! Taking bets!}
{110}{}{女士们先生们！打赌！}
#{111}{}{Make your bets here!}
{111}{}{在这里下注！}
#{112}{}{Don't dawdle, make a bet!}
{112}{}{别磨蹭了，打个赌吧！}
#{113}{}{Who's gonna win today?!}
{113}{}{今天谁会赢？！}
#{114}{}{Hey! Who hasn't bet on the winner yet?!}
{114}{}{嘿！谁还没赌赢呢？！}
#{115}{}{Bets are a minimum of ten dollars!}
{115}{}{下注最少10美元！}
#{116}{}{More bets! More bets!}
{116}{}{更多赌注！更多赌注！}
#{117}{}{Come on! Faster! Faster!}
{117}{}{加油！快点！快点！}
#{118}{}{Look at that heat!}
{118}{}{看那热！}
#{119}{}{This is intense!}
{119}{}{这太激烈了！}
#{120}{}{Who didn't bet yet?}
{120}{}{谁还没下注？}
#{121}{}{Come on! Bet on the winner!}
{121}{}{加油！赌赢家！}
#{200}{}{Hey, champion! Such a shame that you're out of the ring now... }
{200}{}{嘿，冠军！真遗憾你现在不在拳击场上了。。。}
#{201}{}{Those fights were a sight to see! Too bad it's all over... }
{201}{}{那些打斗场面太壮观了！可惜一切都结束了。。。}
#{202}{}{Ring's not gonna be the same without you... }
{202}{}{没有你戒指就不一样了。。。}
#{203}{}{You've got great talent!}
{203}{}{你真有天分！}
#{204}{}{I hope you'll be back one day!}
{204}{}{我希望有一天你会回来！}
#{205}{}{You're not out of the ring forever, right? Right!?}
{205}{}{你不会永远离开拳击场，对吧？正确的！？}
#{210}{}{Hey, champion! Such a shame that you're out of the ring now... }
{210}{}{嘿，冠军！真遗憾你现在不在拳击场上了。。。}
#{211}{}{Those fights were a sight to see! Too bad it's all over... }
{211}{}{那些打斗场面太壮观了！可惜一切都结束了。。。}
#{212}{}{Ring's not gonna be the same without you... }
{212}{}{没有你戒指就不一样了。。。}
#{213}{}{You've got great talent!}
{213}{}{你真有天分！}
#{214}{}{I hope you'll be back one day!}
{214}{}{我希望有一天你会回来！}
#{215}{}{You're not out of the ring forever, right? Right!?}
{215}{}{你不会永远离开拳击场，对吧？正确的！？}
#{219}{}{Bye.}
{219}{}{再见。}
#{220}{}{Hey.}
{220}{}{嘿。}
#{221}{}{Can I make a bet?}
{221}{}{我能打赌吗？}
#{222}{}{Not now. We only make bets during a fight.}
{222}{}{不是现在。我们只在打架时下注。}
#{223}{}{What the hell is going on right now then?}
{223}{}{那现在到底是怎么回事？}
#{224}{}{They're just sparring. We let them out to dance for the crowd. I'm not sure when we'll next have a proper fight.}
{224}{}{他们只是在争吵。我们让他们出来为群众跳舞。我不确定我们下一次什么时候能好好地打一架。}
#{225}{}{Got it.}
{225}{}{知道了。}
#{226}{}{Hey, fighter! You've got great bets going for you!}
{226}{}{嘿，斗士！你下了很大的赌注！}
#{227}{}{Oh? That's great. See you.}
{227}{}{哦？太好了。再见。}
#{228}{}{Hey, champion! How are you feeling after the fight? That was quite a show! The crowd was fucking wild! I thought they were gonna tear the fence apart! Super! Super! Super!}
{228}{}{嘿，冠军！打架后你感觉怎么样？那真是场秀！人群太疯狂了！我以为他们会把栅栏拆开！超级的！超级的！超级的！}
#{229}{}{Uh-huh, it was fun. See you.}
{229}{}{啊哈，很有趣。再见。}
#{230}{}{Hey, these fights are fair, right? No doping or anything?}
{230}{}{嘿，打架是公平的，对吧？没有兴奋剂什么的？}
#{240}{}{Hey, what the hell are you implying?! Bishop was fucking crystal clear - no chems before a fight. He even sent all the dealers out the door to keep his rep. At least I don't know anything about that.}
{240}{}{嘿，你到底在暗示什么？！毕晓普他妈的很清楚-打架前没有化学反应。他甚至把所有的经销商都派出去留下他的代表。至少我对此一无所知。}
#{241}{}{Is that so? I guess that means I can't steam up a little before the fight?}
{241}{}{是这样吗？我想那意味着我不能在比赛前发泄一下？}
#{242}{}{Well, unless you want some bad rep and a boot out the door, that's a no.}
{242}{}{好吧，除非你想要一个坏名声和一只靴子出门，那是不行的。}
#{243}{}{Oh yeah, except that's a lie. See this note? You still gonna deny that dealers are selling here?}
{243}{}{哦，是的，不过那是个谎言。看到这张纸条了吗？你还否认这里有卖毒品的人吗？}
#{244}{}{Got it. Still hard to believe.}
{244}{}{知道了。还是很难相信。}
#{245}{}{Wha... Hold up, chum, don't judge too quick! This ain't a deal with the ring, you dig? Some strangers came in and did some deals between themselves, in the corner. The ring has nothing to do with this, got it?}
{245}{}{什么。。。等等，朋友，不要判断得太快！这不是戒指的交易，明白吗？一些陌生人进来，在角落里做了一些交易。戒指和这无关，明白吗？}
#{246}{}{No problem, the ring is out of it. But that didn't stop a certain someone from catching a glimpse of those two, right?}
{246}{}{没问题，戒指没了。但这并没有阻止某个人瞥见那两个人，对吧？}
#{247}{}{Hmm. Why should I even bother talking to you? Maybe I should just call security and have you thrown out?}
{247}{}{嗯。我干嘛还要跟你说话呢？也许我应该叫保安把你赶出去？}
#{248}{}{I'm sure two people could find something to agree on. [quietly hand him $100]}
{248}{}{我相信两个人会找到一致意见的。[悄悄地递给他100美元]}
#{249}{}{I wonder who the boss is more likely to believe - some midget, or the champion of the ring with hard evidence?}
{249}{}{我想知道老板更可能相信谁——某个侏儒，还是有确凿证据的拳击冠军？}
#{250}{}{Forget it.}
{250}{}{算了吧。}
#{251}{}{[With a sly smile, he pulls you over to the side, acting like nothing is going on] Hard to argue with that. I think we could find a common ground.}
{251}{}{[带着狡黠的微笑，他把你拉到一边，装作什么都没发生]很难反驳。我想我们可以找到共同点。}
#{252}{}{Great, now tell me everything you know.}
{252}{}{太好了，现在告诉我你知道的一切。}
#{253}{}{Quit it with the conspiracy! Tell me everything, and don't even think of lying to me!}
{253}{}{别再搞阴谋了！把一切都告诉我，别想骗我！}
#{254}{}{Shit, that's hard to argue with.}
{254}{}{妈的，这很难说。}
#{255}{}{Quit whining and talk what you know!}
{255}{}{别发牢骚了，说你知道的吧！}
#{256}{}{I want to know everything you do. And then we might part peacefully.}
{256}{}{我想知道你做的一切。然后我们可以和平分手。}
#{257}{}{Like I said, the ring has nothing to do with this. But that filth crawls out of every hole and we can't do much about it. The dealers want to sling dope to our fighters, they quickly figured that's goldmine. And the fighters want to win, so they buy the shit like candy. The smarter ones refused, realizing how serious the whole thing is. And then they came here to find *proper* dealers, with *quality* product. Our boys don't hold back, if they're gonna buy, they're gonna *buy*.}
{257}{}{就像我说的，戒指和这个无关。但是那些脏东西从每个洞里爬出来，我们对此无能为力。毒贩想把毒品扔给我们的战士，他们很快就发现那是金矿。战士们想赢，所以他们买糖果之类的东西。更聪明的人拒绝了，意识到事情有多严重。然后他们到这里来寻找有质量的合适的经销商。我们的人不会退缩，如果他们要买，他们会买。}
#{258}{}{And this dealer from the note, he comes here often?}
{258}{}{从纸条上看，他经常来这里？}
#{259}{}{You know, dealing with Solomon isn't exactly the best decision. But, if you need him, you're at the wrong place. Bishop said he can't show his face around here. If you still wanna find him, I'll give you some free advice - find those who work with him to get an introduction.}
{259}{}{你知道，和所罗门打交道不是最好的决定。但是，如果你需要他，你就来错地方了。毕晓普说他不能在这里露脸。如果你还想找到他，我会给你一些免费的建议——找那些和他一起工作的人做个介绍。}
#{260}{}{And who might that be?}
{260}{}{那可能是谁？}
#{261}{}{Well, he's had lots of people working with him. Ask Racer at the bowling club, he worked with him. Although, I'm not sure how close they are now... Oh, and, if anyone asks - I didn't say nothing. Talked about fights, bets - that's it. Dig?}
{261}{}{他有很多人和他一起工作。问保龄球俱乐部的赛车手，他和他一起工作过。虽然，我不知道他们现在有多近。。。哦，如果有人问我-我什么也没说。谈论打架，赌博-就是这样。挖？}
#{262}{}{Alright... }
{262}{}{好吧。。。}
#{263}{}{[Sniffs the note, making face like it's stronger than any drug]}
{263}{}{[嗅了嗅纸条，让脸看起来比任何药物都强]}
#{264}{}{[Rubs the $100 note affectionately] }
{264}{}{[深情地揉着100美元的钞票]}
#{265}{}{You have a second lead to finding the illusive drug dealer.}
{265}{}{你还有第二条线索可以找到那个虚幻的毒贩。}
#{266}{}{So that's how the fighters get the glory around here?! And you don't know anything about this dealer? [show Fatso's note]}
{266}{}{所以战士们就是这样在这里获得荣誉的？！你对这个商人一无所知？[出示胖子的便条]}
#{270}{}{Listen, I've got some tough fights ahead. Any suggestions?}
{270}{}{听着，我前面还有几场硬仗要打。有什么建议吗？}
#{271}{}{Hold on, how are you feeling after that last fight? You see, I heard that a... Successful fighter is coming over. Much tougher than the last one you fought. I didn't say anything, but you might wanna prepare a bit more, if you catch my drift. [he winks]}
{271}{}{等等，上次打架后你感觉怎么样？你看，我听说。。。成功的战士来了。比你上一次战斗要艰难得多。我什么都没说，但如果你明白我的意思，你可能想多准备一点。[他眨眼]}
#{272}{}{What fighter?}
{272}{}{什么斗士？}
#{273}{}{Gonna be a tough few days. I'll need to train even harder... }
{273}{}{这几天会很艰难。我需要更努力的训练。。。}
#{274}{}{Mhm, I get you. What've you got in mind?}
{274}{}{嗯，我明白了。你在想什么？}
#{275}{}{I don't know that much. I heard that this monster was brought up on human meat. A huge brute without any brains. He was *born* a killing machine.}
{275}{}{我不知道那么多。我听说这个怪物是用人的肉养大的。一个没有大脑的大畜生。他生来就是杀人机器。}
#{276}{}{Train? Are you kidding me?! Err... Seriously? You don't get a little "pump" before a fight? You know what I'm talking about. Do you?}
{276}{}{训练？你在开玩笑吧？！呃。。。说真的？在打架之前你没有得到一点“泵”？你知道我在说什么。你…吗？}
#{277}{}{Well, no, I don't. Is that a problem?}
{277}{}{嗯，不，我不知道。有问题吗？}
#{278}{}{Well... Maybe from time to time... A little, just in case.}
{278}{}{好。。。也许有时候。。。一点点，以防万一。}
#{279}{}{[He motions you closer] I'll say this, champion. You know Stryker, right? He's got a man who cooks chems. You need to talk with him about how to improve your skills. But that's only between us.}
{279}{}{[他示意你靠近]我会这么说，冠军。你认识史崔克，对吧？他有个做化学制品的人。你需要和他谈谈如何提高你的技能。但那只是我们之间的事。}
#{280}{}{}
{280}{}{}
#{281}{}{Why are you telling me this? For free, I mean.}
{281}{}{你为什么告诉我这些？免费的，我是说。}
#{282}{}{Thanks for that. I'll be going now.}
{282}{}{谢谢你。我要走了。}
#{283}{}{Connections - they're as valuable as cash, even more, chum. Never forget that. That's why I help everyone here and there.}
{283}{}{人脉——他们和现金一样值钱，甚至更值钱，朋友。别忘了这一点。这就是为什么我在这里和那里帮助每个人。}
#{284}{}{What are you implying? If you're talking about chems, then I'll say this - Bishop doesn't like it. If he gets word of this, you can kiss this place goodbye.}
{284}{}{你在暗示什么？如果你说的是化学，那么我会说-毕晓普不喜欢。如果他听到这个消息，你可以和这个地方吻别。}
#{285}{}{Like that's stopping anyone... }
{285}{}{好像阻止了任何人。。。}
#{286}{}{Well, forget about it then.}
{286}{}{好吧，那就算了吧。}
#{287}{}{Listen, talks like this never end well. All I want is to work and earn money. I've got to feed my family and help my sick mother, got it?}
{287}{}{听着，这样的谈话永远不会有好结果。我只想工作挣钱。我得养活我的家人，帮助我生病的母亲，明白吗？}
#{288}{}{Of course. But look what I have here - 1000 bucks. Just enough to buy medicine for your sick mother.}
{288}{}{当然。但看看我这里有什么-1000美元。只够给你生病的母亲买药。}
#{289}{}{Uhmm. Not a bad sum. Still not worth the risk I'm putting myself in by dealing with you. No offense, but everyone in this town knows that it's safer to avoid you.}
{289}{}{嗯。数目不错。还是不值得我冒这个险跟你打交道。无意冒犯，但镇上的每个人都知道避开你更安全。}
#{290}{}{[He hungrily grasps the cash] Just in time, friendo. I appreciate the... Err, help. So, I heard you wanted to know who does the dirty on this ring? Well, I know one secret that I'll be happy to share with you.}
{290}{}{[他饥肠辘辘地抓住现金]来得正是时候，朋友。我很感激。。。呃，救命啊。所以，我听说你想知道谁在这戒指上干坏事？好吧，我知道一个秘密，我很乐意和你分享。}
#{291}{}{Talk.}
{291}{}{说话。}
#{1228}{}{Hey, champion! How are you feeling after the fight? That was quite a show! The crowd was fucking wild! I thought they were gonna tear the fence apart! Super! Super! Super!}
{1228}{}{嘿，冠军！打架后你感觉怎么样？那真是场秀！人群太疯狂了！我以为他们会把栅栏拆开！超级的！超级的！超级的！}
#{1271}{}{Hold on, how are you feeling after that last fight? You see, I heard that a... Successful fighter is coming over. Much tougher than the last one you fought. I didn't say anything, but you might wanna prepare a bit more, if you catch my drift. [he winks]}
{1271}{}{等等，上次打架后你感觉怎么样？你看，我听说。。。成功的战士来了。比你上一次战斗要艰难得多。我什么都没说，但如果你明白我的意思，你可能想多准备一点。[他眨眼]}
#{1245}{}{Wha... Hold up, chum, don't judge too quick! This ain't a deal with the ring, you dig? Some strangers came in and did some deals between themselves, in the corner. The ring has nothing to do with this, got it?}
{1245}{}{什么。。。等等，朋友，不要判断得太快！这不是戒指的交易，明白吗？一些陌生人进来，在角落里做了一些交易。戒指和这无关，明白吗？}
#{1279}{}{[He motions you closer] I'll say this, champion. You know Stryker, right? He's got a man who cooks chems. You need to talk with him about how to improve your skills. But that's only between us.}
{1279}{}{[他示意你靠近]我会这么说，冠军。你认识史崔克，对吧？他有个做化学制品的人。你需要和他谈谈如何提高你的技能。但那只是我们之间的事。}
#{1283}{}{Connections - they're as valuable as cash, even more, baby. Never forget that. That's why I help everyone here and there.}
{1283}{}{关系——它们和现金一样值钱，甚至更值钱，宝贝。别忘了这一点。这就是为什么我在这里和那里帮助每个人。}
#{1290}{}{[He hungrily grasps the cash] Just in time, girl. I appreciate the... Err, help. So, I heard you wanted to know who does the dirty on this ring? Well, I know one secret that I'll be happy to share with you.}
{1290}{}{[他饥肠辘辘地抓住现金]来得正是时候，姑娘。我很感激。。。呃，救命啊。所以，我听说你想知道谁在这戒指上干坏事？好吧，我知道一个秘密，我很乐意和你分享。}
