#{100}{}{You see a receptionist.}
{100}{}{你看到一个接待员。}
#{101}{}{You see elegantly dressed receptionist. He gives you a welcoming smile.}
{101}{}{你看到一个穿着考究的接待员。他给你一个欢迎的微笑。}
#{102}{}{Sorry, but you'll have to holster that.}
{102}{}{对不起，但你得把它套起来。}
#{109}{}{Tell me about this hotel.}
{109}{}{告诉我这家旅馆的情况。}
#{110}{}{Welcome to the Silver Legacy, the greatest hotel in Reno! It's also the only hotel in Reno, so you might as well book a room now. And while you're here, why not check out the casino? It's been a long road, you should treat yourself!}
{110}{}{欢迎来到银色遗产酒店，里诺最好的酒店！这也是雷诺唯一的酒店，所以你不妨现在就预订一个房间。既然你在这里，为什么不去赌场看看呢？这是一条漫长的路，你应该善待自己！}
#{111}{}{What can I do for you?}
{111}{}{有什么事吗？}
#{112}{}{I need to talk to the owner. Where is he?}
{112}{}{我要和店主谈谈。他在哪？}
#{113}{}{Did you see that two thugs? One has dreadlocks and the other one carries a crowbar. Where did they go? Please, be honest!}
{113}{}{你看到那两个暴徒了吗？一个戴着长发锁，另一个拿着撬棍。他们去哪了？拜托，说实话！}
#{114}{}{Why do you let people paint all over your walls outside?}
{114}{}{你为什么让人们在你的外墙上涂满油漆？}
#{115}{}{Okay, but first, tell me about the hotel.}
{115}{}{好吧，但首先，告诉我酒店的情况。}
#{116}{}{I need a room.}
{116}{}{我需要一个房间。}
#{117}{}{I don't need anything right now. I'll just be going.}
{117}{}{我现在什么都不需要。我要走了。}
#{118}{}{I have another question...}
{118}{}{我还有一个问题...}
#{119}{}{I see. Thanks.}
{119}{}{我懂了。谢谢。}
#{125}{}{[The receptionist's smile slips off his face, and he glances nervously out the door] Uh... They, uh... The El Dorado, just down Virginia Street... }
{125}{}{[接待员的微笑从他脸上滑落，他紧张地向外看了一眼]呃...他们，呃...El Dorado，就在弗吉尼亚大街上...}
#{126}{}{"Let"? Ha! We've tried to stop those doing it, believe me. But we can never catch them in the act. Whoever it is, they're careful.}
{126}{}{“让”？哈！相信我，我们已经尽力阻止那些人这么做了。但我们永远也抓不到他们。不管是谁，他们都很小心。}
#{127}{}{Maybe I can catch this artist for you.}
{127}{}{也许我能帮你抓住这位艺术家。}
#{128}{}{Maybe. Probably not, but it's worth a try. I'll pay you 100 bucks if you can nab them on their crime.}
{128}{}{也许 吧。可能不会，但值得一试。如果你能抓住他们的罪行，我就付给你100美元。}
#{129}{}{I'll remember that.}
{129}{}{我会记住的。}
#{130}{}{You are in the one, the only, Silver Legacy! This building's is Reno's main resting place for travelers from the wasteland. Before the war, we were famous for our hospitality and the beauty of our surroundings. We were the gem of the city! Reno's a lot rougher nowadays, but we're fighting to remain the diamond in it.}
{130}{}{你是唯一的，唯一的，银色遗产！这座建筑是雷诺的主要休息地，为旅客从荒地。战前，我们以好客和美丽的环境而闻名。我们是城市的瑰宝！雷诺现在更粗糙了，但我们正在努力保持它的钻石。}
#{131}{}{The world now is very different from those days. How can the hotel still attract customers?}
{131}{}{现在的世界与过去大不相同。酒店怎么还能吸引顾客呢？}
#{132}{}{People do need to sleep, don't they? Reno still gets people from out of town. Most of our customers are caravan workers, but there's also some refugees from other settlements that want to try their luck in the big city.}
{132}{}{人们确实需要睡觉，不是吗？雷诺仍然有人从外地来。我们的客户大多是商队工人，但也有一些来自其他定居点的难民想在大城市碰碰运气。}
#{133}{}{Why do people come to Reno?}
{133}{}{人们为什么来雷诺？}
#{134}{}{Besides business? Hmm. I'd say the biggest reason is freedom. There's no mayor or sheriff here. Control is in the hands of the common people! And yeah, that can get dangerous, but it's also very appealing to a lot of people, myself included. Anyway, even if you don't want to stay in here, it's a great place to visit. Reno's always been a great place for tourists.}
{134}{}{除了生意？嗯。我想说最大的原因是自由。这里没有市长和警长。控制权掌握在老百姓手中！是的，这会很危险，但对很多人来说也很有吸引力，包括我自己。不管怎样，即使你不想呆在这里，那也是个好地方。雷诺一直是游客的好去处。}
#{135}{}{Tourists? We're living in a wasteland, how much tourism can there be?}
{135}{}{游客？我们生活在一片荒地里，能有多少旅游业？}
#{136}{}{You'd be surprised! Reno was barely touched by the bombs, so a lot of the old entertainment ventures is still intact. If you want a good time, well, just look down the hall to the casino! Or, you can go down Virginia Street and check out the El Dorado. They've got booze, a night club, and even fights in the basement! And don't forget - if you need to rest your head, we're the best in the city.}
{136}{}{你会惊讶的！里诺几乎没有被炸弹击中，所以很多老的娱乐项目仍然完好无损。如果你想玩得开心，那就从大厅往下看赌场吧！或者，你可以沿着弗吉尼亚大街去看看埃尔多拉多。他们喝酒，开夜总会，甚至在地下室打架！别忘了-如果你需要休息的话，我们是城里最好的。}
#{137}{}{What about food and supplies?}
{137}{}{食物和用品呢？}
#{138}{}{The Silver Legacy has a wonderful restaurant just across the street. You won't find any better food in Reno, that's for sure! And there's a shop next to the caravan parking lot. Whatever you need for the road, you can get it there.}
{138}{}{Silver Legacy在街对面有一家很棒的餐厅。你肯定在雷诺找不到比这更好的食物了！大篷车停车场旁边有一家商店。无论你在路上需要什么，你都可以在那里买到。}
#{139}{}{Do you know where 75 Virginia Street is?}
{139}{}{你知道弗吉尼亚街75号在哪里吗？}
#{140}{}{Hmm. Most of the houses don't have numbers up, but that should be somewhere around here. I'd check out the slums on the other side of the street.}
{140}{}{嗯。大多数房子都没有数字，但应该在这附近。我会去看看街对面的贫民窟。}
#{141}{}{Thanks.}
{141}{}{谢谢。}
#{142}{}{Do you know of any quiet parts of the city where someone could live safely?}
{142}{}{你知道这个城市有什么安静的地方有人可以安全地居住吗？}
#{143}{}{There's not a lot of safe places in Reno, and even fewer quiet ones! You'd have to find a place without any people. Hmm...if I had to choose somewhere quiet and safe, I'd go to the airport or train station. They don't work anymore, obviously, so no one has a reason to go out there.}
{143}{}{雷诺没有很多安全的地方，安静的地方更少！你得找个没有人的地方。嗯…如果我必须选择一个安静和安全的地方，我会去机场或火车站。很明显，他们已经不工作了，所以没有人有理由去那里。}
#{149}{}{A room will run you }
{149}{}{一个房间可以容纳你}
#{150}{}{ dollars for 24 hours. We only rent by the day, nothing longer.}
{150}{}{24小时25美元。我们只按天租房，不再租房了。}
#{151}{}{I'll take a room, thank you. Here's the money.}
{151}{}{我要一个房间，谢谢。这是钱。}
#{152}{}{I don't have that kind of money right now. I'll come back later.}
{152}{}{我现在没那么多钱。我一会儿回来。}
#{153}{}{Great! Let me show you your room. When was the last night you slept in a real bed, huh?}
{153}{}{太好了！我带你去看看你的房间。你昨晚睡在真正的床上是什么时候？}
#{154}{}{[Follow him.]}
{154}{}{[跟着他。]}
#{155}{}{You puked all over the floor! Now who's going to clean this up?}
{155}{}{你吐得满地都是！现在谁来清理？}
#{156}{}{You feel rested.}
{156}{}{你觉得休息了。}
#{160}{}{Were there any bikers staying here? I'm looking for one named Jay Kukish.}
{160}{}{有骑自行车的人住在这里吗？我在找一个叫杰伊·库基什的。}
#{161}{}{A bunch of bikers came through town recently. They don't usually stay at the hotel, although Mr. Mordino likes to meet them. He used to ride the bike, you know. If you have questions about bikers, you should probably talk to him.}
{161}{}{最近城里来了一群骑自行车的人。他们通常不住在酒店，尽管摩迪诺先生喜欢和他们见面。你知道，他以前骑自行车。如果你对骑自行车的人有疑问，你应该和他谈谈。}
#{170}{}{Do you have any jobs for me?}
{170}{}{你有工作给我吗？}
#{171}{}{I fixed the vent fan.}
{171}{}{我把通风风扇修好了。}
#{172}{}{Nah... Well, wait. Do you know anything about technology? There's an empty room on the second floor with a busted air vent fan. I think one of the prior guests was messing with it. If you can fix it, I'll pay.}
{172}{}{不...好吧，等等。你懂技术吗？二楼有间空房间，通风机坏了。我想前面的一位客人在捣乱。如果你能修好，我就付钱。}
#{173}{}{I'll take a look.}
{173}{}{我去看看。}
#{174}{}{Thanks, that takes care of one headache. Here's 100 bucks for your trouble. All the best!}
{174}{}{谢谢，这能治好一个头痛。这是100美元给你的麻烦。祝你一切顺利！}
#{175}{}{You're welcome!}
{175}{}{不客气！}
#{180}{}{I'm impressed that your boss can keep this place by himself. He must have no family if he's able to devote this much time to his work.}
{180}{}{你的老板能独自经营这个地方给我留下了深刻的印象。如果他能把这么多时间花在工作上，他一定没有家人。}
#{181}{}{Oh no, no, he has a family. He has a wife and a beautiful baby girl. I remember the night he proposed to her at the hotel restaurant. Ah... Romantic. They still eat there sometimes.}
{181}{}{哦，不，不，他有一个家庭。他有一个妻子和一个漂亮的女婴。我记得那天晚上他在饭店餐厅向她求婚。啊...浪漫。他们有时还在那里吃饭。}
#{182}{}{At the restaurant, you say. Good to know.}
{182}{}{你说在餐厅。很高兴知道。}
