#{100}{}{You see a bodyguard.}
{100}{}{你看到一个保镖。}
#{101}{}{You see a bodyguard and he sees you.}
{101}{}{你看到一个保镖，他也看到了你。}
#{102}{}{You completed Luciano's task.}
{102}{}{你完成了卢西亚诺的任务。}
#{103}{}{You're right, I *have* been working too hard.}
{103}{}{你说得对，我工作太辛苦了。}
#{104}{}{At least someone understands me... Friend.}
{104}{}{至少有人理解我。。。朋友。}
#{105}{}{::snores::}
{105}{}{●打鼾：}
#{106}{}{The guard dozes off. He probably won't be out for long, so it's best to hurry.}
{106}{}{卫兵打瞌睡。他可能不会出去太久，所以最好快点。}
#{107}{}{The hell is this? You expect me to drink this swill? Just get me some beer.}
{107}{}{这到底是什么？你想让我喝这个泔水？给我拿点啤酒。}
#{110}{}{Don't distract me.}
{110}{}{别分散我的注意力。}
#{111}{}{Hold it! What do you want?}
{111}{}{别动！你想要什么？}
#{112}{}{Stryker said I could pass.}
{112}{}{史崔克说我可以通过。}
#{113}{}{I can't go in there?}
{113}{}{我不能进去？}
#{114}{}{[He speaks with a mocking tone] No, you *can't* go in there! No one does unless Stryker says so, and I don't remember him saying anything about you.}
{114}{}{不，你不能进去！除非史崔克这么说，否则没人会这么做，我也不记得他说过什么关于你的事。}
#{115}{}{No problem.}
{115}{}{没问题。}
#{116}{}{Fine, just don't distract the egghead for too long.}
{116}{}{好吧，别让书呆子分心太久。}
#{117}{}{No problem.}
{117}{}{没问题。}
#{118}{}{I'll be quick. I have a message from his wife. She's worried, you know?}
{118}{}{我会很快的。我有他妻子的口信。她很担心，你知道吗？}
#{119}{}{Why didn't you say so? Come right through.}
{119}{}{你为什么不这么说？直接过来。}
#{120}{}{I'm not falling for that. Stryker gives the order, I'll let you through.}
{120}{}{我不会上当的。史崔克下命令，我让你过去。}
#{121}{}{[Hand over $100] I understand, Stryker is very... Strict. Won't even let a man see his wife. How would you like it if that was you?}
{121}{}{[交出100美元]我明白，史崔克非常。。。严格的。甚至不让男人看到他的妻子。如果是你的话，你觉得怎么样？}
#{122}{}{Hmm... Fine, ten minutes.}
{122}{}{隐马尔可夫模型。。。好的，十分钟。}
#{123}{}{Thanks.}
{123}{}{谢谢。}
#{1104}{}{At least someone understands me... Friend.}
{1104}{}{至少有人理解我。。。朋友。}
#{1118}{}{They won't let his own wife see him?! What kind of people are you?! Let me through!}
{1118}{}{他们不会让他老婆看到他的？！你是什么样的人？！让我过去！}
