#{100}{}{You see a traveler.}
{100}{}{你看到一个旅行者。}
#{101}{}{You see an exhausted traveler.}
{101}{}{你看到一个筋疲力尽的旅行者。}
#{105}{}{Please, I'm tired. Let me rest.}
{105}{}{拜托，我累了。让我休息一下。}
#{106}{}{I can still stand on my own feet!}
{106}{}{我仍然可以自立！}
#{107}{}{Not now. I just want to sleep.}
{107}{}{不是现在。我只想睡觉。}
#{110}{}{Sorry, but I'm too tired to talk. It was a long trip.}
{110}{}{对不起，我累得说不出话来。那是一次长途旅行。}
#{111}{}{Tough times on the road? I can relate.}
{111}{}{路途艰难？我能理解。}
#{112}{}{We'll talk later, then.}
{112}{}{那我们晚点再谈。}
#{113}{}{Hmm? ...Oh, no, not like that. The travel was fine, but I had to hurry to get here before nightfall.}
{113}{}{嗯。。。哦，不，不是那样的。旅途还行，但我得赶在天黑前赶到这里。}
#{114}{}{I know what you mean. I'd never spend a night outside the city!}
{114}{}{我知道你的意思。我决不会在城外过夜！}
#{115}{}{Yes, the wasteland can be very dangerous at night.}
{115}{}{是的，荒地在晚上很危险。}
#{116}{}{Ha! What, are you afraid of the dark?}
{116}{}{哈！什么，你害怕黑暗吗？}
#{117}{}{Mmm. Look, I'm too exhausted to care right now. Come back in the morning and maybe I'll get offended then, okay?}
{117}{}{嗯。听着，我现在太累了。明早回来也许我会生气，好吗？}
#{118}{}{Aww, poor baby. Go have your nap in your crib.}
{118}{}{啊，可怜的孩子。去婴儿床上小睡一会儿。}
#{119}{}{Fine. Sorry to keep you up.}
{119}{}{好的。抱歉让你久等了。}
#{120}{}{I should be going.}
{120}{}{我该走了。}
#{121}{}{Where are you traveling from?}
{121}{}{你从哪里来？}
#{122}{}{Bye.}
{122}{}{再见。}
#{123}{}{I'm not so concerned with the wasteland as I am with the people in it, to be honest. It's usually easier to "negotiate" with a gecko, if you know what I mean.}
{123}{}{老实说，我关心的不是荒地，而是荒地里的人。如果你明白我的意思的话，和壁虎“谈判”通常比较容易。}
#{124}{}{Are you serious?}
{124}{}{你是认真的吗？}
#{125}{}{Oh, yes. People don't stay around for long where I come from, so they don't respect anyone - not neighbors, nor visitors.}
{125}{}{哦，是的。在我来的地方人们不会待太久，所以他们不尊重任何人——不尊重邻居，也不尊重来访者。}
#{126}{}{Where do you come from?}
{126}{}{你来自哪里？}
#{127}{}{Interesting. Well, see you around.}
{127}{}{很有趣。好吧，回头见。}
#{128}{}{Wendover... Oh, right, you've probably never heard of it. Uh, it's a seasonal hunting village near Salt Lake.}
{128}{}{温多弗。。。哦，对了，你可能从没听说过。呃，这是盐湖附近的一个季节性狩猎村。}
#{129}{}{What made you come here?}
{129}{}{你为什么来这里？}
#{130}{}{Can you show me where it's located?}
{130}{}{你能告诉我它在哪里吗？}
#{131}{}{That's all I wanted to know. Bye.}
{131}{}{我只想知道这些。再见。}
#{132}{}{Tell me again, where did you came from?}
{132}{}{再告诉我一次，你从哪里来的？}
#{133}{}{Yeah, sure.}
{133}{}{是的，当然。}
#{134}{}{Eh, I'm no good with maps. If you're ever in Salt Lake, ask a local. They'll probably be able to point it out for you.}
{134}{}{呃，我不擅长地图。如果你去过盐湖城，问问当地人。他们也许能帮你指出。}
#{135}{}{Is there anything I should know if I'm ever in Wendover?}
{135}{}{如果我在温多弗，有什么我应该知道的吗？}
#{136}{}{That's all, thanks.}
{136}{}{就这些，谢谢。}
#{137}{}{[He sighs] That's a long story. You don't need to worry about it, it's my problem.}
{137}{}{[他叹息]说来话长。你不用担心，这是我的问题。}
#{138}{}{If you say so. See you around.}
{138}{}{如果你这样说。回头见。}
#{139}{}{It's mostly hunters and their families. Men hunt for geckos while women and children tend to their huts. It has everything you need - a tavern, a shop, a hunting guild - but other than that there's not much to it. Also... A lot of people only live there for the hunting season, so they think they can do whatever they want without being punished for it.}
{139}{}{主要是猎人和他们的家人。男人捕猎壁虎，而女人和孩子则在他们的小屋里。它有你所需要的一切-一个酒馆，一个商店，一个狩猎协会-但除此之外，它没有太多。也。。。很多人只在狩猎季节住在那里，所以他们认为自己可以为所欲为，而不会因此受到惩罚。}
#{140}{}{No punishment? Sounds like my kind of town! Where is it?}
{140}{}{没有惩罚？听起来像是我的家乡！它在哪里？}
#{141}{}{What are you planing to do in Reno?}
{141}{}{你打算在雷诺干什么？}
#{142}{}{I don't know. It's easy to catch a bullet here, if you don't watch yourself. Or the people around you, come to think of it. I'll have to strive hard to survive here.}
{142}{}{我不知道。如果你不注意自己，在这里很容易被子弹击中。或者你周围的人，想想看。我要在这里努力生存。}
#{1114}{}{I know what you mean. I'd never spend a night outside the city!}
{1114}{}{我知道你的意思。我决不会在城外过夜！}
#{1116}{}{Ha! What, are you afraid of the dark?}
{1116}{}{哈！什么，你害怕黑暗吗？}
#{1130}{}{Can you show me where it's located?}
{1130}{}{你能告诉我它在哪里吗？}
