#{100}{}{You see documents on a table.}
{100}{}{你看到桌子上有文件。}
#{101}{}{You see various maps and other documents scattered across a table.}
{101}{}{您可以看到分散在一张表中的各种地图和其他文档。}
#{102}{}{You can't read while in combat!}
{102}{}{你不能在战斗中看书！}
#{150}{}{These documents belong to the recruitment officer. He probably won't appreciate you looking through them.}
{150}{}{这些文件属于招聘官。他可能不会感激你翻阅它们。}
#{151}{}{These documents contain reports for the Nevada Express administrator, as well as up-to-date maps of Nevada.}
{151}{}{这些文件包含内华达州快递管理员的报告，以及内华达州的最新地图。}
#{152}{}{Look for any locations you haven't discovered yet.}
{152}{}{寻找任何你还没有发现的地点。}
#{153}{}{Leave.}
{153}{}{离开。}
#{154}{}{You look through the documents, but you don't find anything new.}
{154}{}{你翻阅了文件，但没有发现任何新的东西。}
#{155}{}{You found something.}
{155}{}{你发现了什么。}
#{156}{}{Copy the raided stagecoach's coordinates into your Pip-Boy.}
{156}{}{把突击的驿站马车的坐标复制到你的皮普小子身上。}
#{157}{}{Copy Las Vegas's coordinates into your Pip-Boy.}
{157}{}{把拉斯维加斯的坐标复制到你的皮普小子身上。}
#{158}{}{Copy Salt Lake City's coordinates into your Pip-Boy.}
{158}{}{把盐湖城的坐标复制到你的皮普小子身上。}
#{159}{}{Copy Lovelock's coordinates into your Pip-Boy.}
{159}{}{把洛夫洛克的坐标复制到你的皮普小子身上。}
#{160}{}{Copy Wind of War's coordinates into your Pip-Boy.}
{160}{}{把战争之风的坐标复制到你的皮普小子身上。}
#{161}{}{Copy Hawthorne's coordinates into your Pip-Boy.}
{161}{}{把霍桑的坐标复制到你的皮普小子身上。}
#{162}{}{Copy Black Rock's coordinates into your Pip-Boy.}
{162}{}{把黑石的坐标复制到你的皮普小子身上。}
#{163}{}{Copy Wendover's coordinates into your Pip-Boy.}
{163}{}{把温多弗的坐标复制到你的皮普小子身上。}
#{164}{}{Search some more.}
{164}{}{再搜索一些。}
#{165}{}{Done.}
{165}{}{完成。}
#{166}{}{You look for new locations on the map.}
{166}{}{你在地图上寻找新的地点。}
#{167}{}{You find nothing of interest.}
{167}{}{你没发现什么有趣的。}
#{168}{}{Step away from the maps.}
{168}{}{离地图远点。}
#{169}{}{Copy Uranium City's coordinates into your Pip-Boy.}
{169}{}{把铀城的坐标复制到你的皮普小子身上。}
