#{100}{}{This is a common strong door.}
{100}{}{这是一扇普通的坚固的门。}
#{101}{}{This door is bolted shut and can only be opened from inside.}
{101}{}{这扇门是用螺栓锁上的，只能从里面打开。}
#{102}{}{This door is bolted shut and cannot be opened from this side.}
{102}{}{这扇门是用螺栓锁着的，不能从这边开。}
#{103}{}{Bolted from inside.}
{103}{}{从里面栓上。}
#{104}{}{You remove the bolt and open the door.}
{104}{}{你拆下螺栓，打开门。}
#{105}{}{Locked from the other side.}
{105}{}{从另一边锁着。}
#{106}{}{Opened.}
{106}{}{开的。}
#{107}{}{Not a scratch.}
{107}{}{一点划痕都没有。}
#{108}{}{The explosion rips the door off its hinges. It falls on the floor with a thud.}
{108}{}{爆炸把门从铰链上扯下来。它砰的一声掉在地板上。}
