#{100}{}{You see Derry.}
{100}{}{你看德里。}
#{101}{}{You see Bruce Derry, leader of the bikers.}
{101}{}{你看布鲁斯·德里，车手的领袖。}
#{102}{}{Your message about the situation in Hawthorne had caused quite a stir. Apparently, soon the bikers will leave Bridgeport, to the delight of rednecks.}
{102}{}{你关于霍桑局势的消息引起了很大的轰动。显然，很快，骑自行车的人就要离开布里奇波特了，这让乡巴佬们很高兴。}
#{103}{}{Piss off}
{103}{}{滚开}
#{104}{}{Hello}
{104}{}{你好}
#{110}{}{What is it?}
{110}{}{这是怎么一回事？}
#{111}{}{Nothing.}
{111}{}{没有什么。}
#{112}{}{I'm looking for Jay Kukish.}
{112}{}{我在找杰伊·库基什。}
#{113}{}{You won??t find him here. He went mad and ran off to Hawthorne.}
{113}{}{你在这里找不到他。他发疯了，跑到霍桑去了。}
#{114}{}{Why are you so calm while telling me this?}
{114}{}{你为什么这么冷静地告诉我这些？}
#{115}{}{Because our gang and Jay has a special kind of relationships. He is a lone wolf, all by himself. If you have business with him - go ahead, find him. As for me, I'm more worried about what we all are supposed to do now. He made some hussle in Hawthorne, we answered his call, gathered here - and now we are still sitting, with no effect.}
{115}{}{因为我们的帮派和杰伊有一种特殊的关系。他是一只孤狼，独自一人。如果你和他有生意-去吧，找到他。至于我，我更担心的是我们现在应该做什么。他在霍桑胡闹了一会儿，我们响应他的号召，聚集在这里——现在我们仍然坐着，毫无效果。}
#{116}{}{So you're all waiting for some special news from Hawthorne?}
{116}{}{所以你们都在等霍桑的特别消息？}
#{117}{}{Why did Jay need to go to Hawthorne?}
{117}{}{为什么杰伊要去霍桑？}
#{118}{}{The garrison in Hawthorne got jacked - its automated defense systems are no longer working. Time to pay a visit there.}
{118}{}{霍桑的驻军被劫持了——它的自动防御系统已经不能工作了。是时候去那里看看了。}
#{119}{}{Tell me about yourself. How did you join a biker gang?}
{119}{}{跟我说说你自己。你是怎么加入一个摩托帮的？}
#{120}{}{Tell me about your gang.}
{120}{}{告诉我你的帮派。}
#{121}{}{Bye.}
{121}{}{再见。}
#{122}{}{Well, yeah. We could smell something's changing. Jay have been spreading the rumors that it's better to stay close to Hawthorne, that something is going to happen there. So, we gathered in Bridgeport - considering that to stay in Hawthorne itself is dangerous.}
{122}{}{嗯，是的。我们能闻到有什么变化。杰伊一直在散布谣言，说最好和霍桑待在一起，那里会发生什么事。所以，我们聚集在布里奇波特-考虑到留在霍桑本身是危险的。}
#{123}{}{Jay said he became interested in a governmental vault. According to him, it is located somewhere in Nevada. Therefore, Jay decided to look for the coordinates on a military base.}
{123}{}{杰伊说他对政府避难所感兴趣。据他说，它位于内华达州的某个地方。因此，杰伊决定在一个军事基地寻找坐标。}
#{124}{}{Oh really? Somehow, Jay haven??t contacted us yet, to tell about it. We've been waiting this news for quite a long time. Also, frankly speaking, the rednecks here are beginning to get on our nerves. We'll move to the base as soon as everyone is ready.}
{124}{}{哦，真的吗？不知怎么的，杰伊还没有联系我们，告诉我们这件事。我们已经等这个消息很久了。而且，坦率地说，这里的乡巴佬们开始让我们紧张起来。大家一准备好我们就去基地。}
#{125}{}{I am a veteran of the Civil War in Reno. Then, local entrepreneurs used to get bikers involved into their shady dealings. We fought as a strike force, as mercenaries, until the situation came to the level when we were not needed anymore. Then we realized that we've just been used. So, we decided to spit in the face of the whole city. I wanted to be free.}
{125}{}{我是里诺内战的老兵。然后，当地的企业家过去常常让骑自行车的人参与他们的阴暗交易。我们作为一支打击部队，作为雇佣兵作战，直到局势发展到不再需要我们的地步。然后我们意识到我们被利用了。所以，我们决定向整个城市吐痰。我想要自由。}
#{126}{}{Here you'll see people who failed to fit into the current society. Look at Bigfoot - he's a Wind of War veteran. When he realized that the local military was worse than the raiders, he abandoned them, to live by his own principles. And here's Whiner - his settlement has been destroyed by raiders. He had no choice, but to seek revenge. Our gang helped him, and then - gave him new purpose to live.}
{126}{}{在这里你会看到那些未能融入当前社会的人。看看大脚怪，他是个老兵。当他意识到当地军队比袭击者更糟时，他抛弃了他们，按照自己的原则生活。这是抱怨者-他的营地被袭击者摧毁了。他别无选择，只能寻求报复。我们帮派帮助了他，然后给了他新的生活目标。}
