#{100}{}{You see Dante.}
{100}{}{你看但丁。}
#{101}{}{You see a young inhabitant of Bridgeport. Although he tries to imitate the bikers, he still looks like a farmer.}
{101}{}{你看到布里奇波特的一个年轻居民。尽管他努力模仿骑自行车的人，但他看上去还是像个农民。}
#{102}{}{}
{102}{}{}
#{103}{}{Wanna fight? I'll show you!.. I mean, WE will show you!}
{103}{}{想打架吗？我给你看！。。我是说，我们会给你看的！}
#{104}{}{Damn! They left! WITHOUT ME! And I had such high hopes...}
{104}{}{该死！他们走了！没有我！我有很高的期望...}
#{105}{}{They're all dead... But... How? I thought, they were the toughest!}
{105}{}{他们都死了...但是...怎样？我想，他们是最难对付的！}
#{106}{}{I'm staying. Perhaps, I will have to leave some day. But for now... I??m staying.}
{106}{}{我要留下来。也许，我总有一天要离开。但现在...我要留下来。}
#{110}{}{}
{110}{}{}
#{111}{}{Hello.}
{111}{}{你好。}
#{112}{}{And who are you? You??re not a biker, right? If not, then we have nothing to talk about. And tell my dad, that I??m in a gang now.}
{112}{}{你是谁？你不是摩托车手，对吧？如果没有，那我们就没什么好谈的了。告诉我爸爸，我现在在帮派里。}
#{113}{}{You??re tired of being a farmer?}
{113}{}{你厌倦了当农夫吗？}
#{114}{}{That??s right! I've hated this shithole for a long time. The fuck?! I can do better than that! Let my parents dig the dirt if they want, but I want to be free.}
{114}{}{没错！我讨厌这鬼地方很久了。他妈的？！我可以做得更好！如果我父母想的话，就让他们去挖土吧，但我想自由。}
#{115}{}{[Next]}
{115}{}{[下一步]}
#{116}{}{Bikers became my idols when they first came here. They know so many things, so they have seen so much! When I'll join their ranks - that's when I'll be really happy.}
{116}{}{骑车人第一次来这里时就成了我的偶像。他们知道很多事情，所以他们看到了很多！当我加入他们的行列时，我会非常高兴。}
#{117}{}{Okay. Well, good luck to you.}
{117}{}{可以。祝你好运。}
#{118}{}{You again? Don??t mess with me, I'll become a BIKER soon! Yeah!}
{118}{}{又是你？别惹我，我很快就会成为一个摩托车手的！是 啊！}
#{119}{}{Right, whatever you say.}
{119}{}{好吧，随你怎么说。}
#{120}{}{Wouldn??t your parents disagree with that?}
{120}{}{你父母不同意吗？}
#{121}{}{What do you know about the bikers?}
{121}{}{你对摩托车手了解多少？}
#{122}{}{How are you going to join bikers?}
{122}{}{你打算怎么加入摩托队？}
#{123}{}{Of course they would. But I won??t ask them. Living here is boring. I want to be with the bikers.}
{123}{}{他们当然会。但我不会问他们。住在这里很无聊。我想和摩托车手在一起。}
#{124}{}{They will test me. Perhaps, it won??t be easy.}
{124}{}{他们会考验我的。也许，这并不容易。}
#{125}{}{Not easy? But you??re confident right?}
{125}{}{不容易？但你很自信，对吧？}
#{126}{}{Yes... Damn it, I'm willing to die trying! Listen, Can you help me? There are two challenges I have to complete, and I may not be up to it. First is shooting a pistol. I don??t even have one, not even talking about shooting skills. The second one is a fistfight. The chief said, that no one's gonna beat me to death, I just have to stay on my feet, while I??m being beaten. How will I get through the pain? This is not some game.}
{126}{}{对...妈的，我愿意去死！听着，你能帮我吗？有两个挑战我必须完成，我可能无法胜任。首先是用手枪射击。我连一个都没有，甚至连射击技巧都没有。第二个是打架。头儿说，没人会把我打死的，我只要站起来，等我被打的时候。我将如何度过痛苦？这不是什么游戏。}
#{127}{}{Fine, I'll help you. It seems you have no choice other than to join the bikers. Okay, I will get you a pistol and some painkillers.}
{127}{}{好吧，我来帮你。看来你别无选择，只能加入摩托队。好的，我给你拿把手枪和止痛药。}
#{128}{}{I won??t help you.}
{128}{}{我不会帮你的。}
#{129}{}{Then get the fuck out of here! [hysterically] I??ll manage without you! I can... I??m a man... I??m a man... [It seems this guy desperately wants to join the bikers.]}
{129}{}{那他妈的滚出去！[歇斯底里地]没有你我能应付！我可以...我是个男人...我是个男人...[这家伙似乎非常想加入摩托队。]}
#{130}{}{[Leave]}
{130}{}{[离开]}
#{131}{}{You will? Awesome. Just hurry before they leave. Otherwise I will be left alone, and I will have to wait until the next time they come.}
{131}{}{你会？令人惊叹的。在他们离开之前赶快。否则我就一个人呆着，我只能等到他们下次来。}
#{132}{}{I??ll keep that in mind. Especially if I had some personal incentive.}
{132}{}{我会记住的。尤其是如果我有个人的动机。}
#{133}{}{Hi. Do you remember your promise to help me? Hurry the bikers could leave at any moment.}
{133}{}{你好。你还记得你答应过帮我吗？快点，骑自行车的人随时可能离开。}
#{134}{}{[Hits his forehead] How could I! Of course! I know a place, where my dad keeps his cash. I don??t know how much money there is, to be honest, I never asked - because I didn??t need any money in this shithole. If you help me I??ll tell you where the stash is.}
{134}{}{我怎么能！当然！我知道一个地方，我爸爸把钱放在那里。我不知道那里有多少钱，说实话，我从来没问过——因为我在这个破地方不需要钱。如果你能帮我，我就告诉你藏在哪里。}
#{135}{}{Great.}
{135}{}{伟大的。}
#{136}{}{I know enough, to make the decision to join the gang. The rest doesn??t matter. Where they live, what they eat - what??s the difference? What??s more important, they don??t belong to anyone and they do whatever they feel is right. Now that??s a life!}
{136}{}{我知道的足够多，决定加入这个团伙。剩下的不重要。他们住在哪里，吃什么-有什么区别？更重要的是，他们不属于任何人，他们做任何他们认为正确的事。这就是生活！}
#{137}{}{Hello.}
{137}{}{你好。}
#{140}{}{Let??s talk about you joining the gang.}
{140}{}{我们来谈谈你加入帮派的事。}
#{141}{}{They want to give me some tests. There are few, but I??m worried only about two. First is shooting a pistol. Second is a fistfight. The chief said, that no one's gonna beat me to death, I just have to stay on my feet, while I??m being beaten.}
{141}{}{他们想给我做些检查。很少，但我只担心两个。首先是用手枪射击。第二是打架。头儿说，没人会把我打死的，我只要站起来，等我被打的时候。}
#{142}{}{This pistol will be just right for your test [give }
{142}{}{这把手枪正适合你的测试}
#{143}{}{].}
{143}{}{].}
#{144}{}{Take a painkiller.}
{144}{}{吃点止痛药。}
#{145}{}{Take a painkiller from this kit.}
{145}{}{从药箱里取一片止痛药。}
#{146}{}{Take a painkiller from this doctor bag.}
{146}{}{从这个医生包里取一片止痛药。}
#{147}{}{Take this gun [give 10mm pistol].}
{147}{}{拿着这把枪[给我10毫米手枪]。}
#{148}{}{Take this gun [give 10mm pistol with ext. mag].}
{148}{}{拿着这把枪[给我一把10毫米长的带外置弹匣的手枪]。}
#{149}{}{Take this gun [give 10mm pistol model ??80].}
{149}{}{拿着这把枪[给我10毫米手枪型号80]。}
#{150}{}{Take this gun [give 10mm pistol with a flashlight].}
{150}{}{拿着这把枪[用手电筒给我一把10毫米口径的手枪]。}
#{151}{}{Take this gun [give a premium 10mm pistol].}
{151}{}{拿着这把枪[给我一把10毫米的高级手枪]。}
#{152}{}{I can??t help right now.}
{152}{}{我现在没办法。}
#{153}{}{Wow! A real gun? Does it work? Superb! Now I have to learn how to use it. Can you teach me?}
{153}{}{哇！真的枪？它有用吗？棒 极 了！现在我必须学会如何使用它。你能教我吗？}
#{154}{}{Sure, I have enough experience to teach you.}
{154}{}{当然，我有足够的经验教你。}
#{155}{}{Honestly, my shooting skills are below average. You'll have to do it without me.}
{155}{}{老实说，我的射击技术低于平均水平。你得在没有我的情况下做这件事。}
#{156}{}{No. You have the pistol, teach yourself.}
{156}{}{不，你有枪，自学吧。}
#{157}{}{Fine, I'll ask that old prospector from the farm house. He shoots good and probably won??t tell my dad about it. Thanks for the help.}
{157}{}{好吧，我去问农舍的老探矿者。他射得很好，可能不会告诉我爸爸。谢谢你的帮助。}
#{158}{}{You??re welcome.}
{158}{}{不客气。}
#{159}{}{[Outside of the town, you set up a shooting range and teach boy the basics of shooting. He was a quick learner.] Awesome! Thanks for the help. Just don??t tell my dad, he will lock me up and won??t let me out, until the bikers are gone.}
{159}{}{[在城外，你建立了一个射击场，教男孩射击的基本知识。他学得很快！谢谢你的帮助。只是别告诉我爸爸，他会把我锁起来，不让我出去，直到摩托车手走了。}
#{160}{}{Fine.}
{160}{}{好的。}
#{161}{}{Will this help with the pain? Great, just what I need! Thanks.}
{161}{}{这有助于减轻疼痛吗？太好了，正是我需要的！谢谢。}
#{162}{}{You??re welcome.}
{162}{}{不客气。}
#{163}{}{Now I??m ready! I??ll have to practice a little and then go to the chief. Thank you, this day will change my life you understand? Remember that stash I told you about.}
{163}{}{现在我准备好了！我得练习一下，然后去找主任。谢谢你，这一天会改变我的生活你明白吗？记得我跟你说过的那个藏匿处吗。}
#{164}{}{Yes, tell me.}
{164}{}{是的，告诉我。}
#{165}{}{Your father does not want you to go with bikers.}
{165}{}{你父亲不想让你和摩托车手一起去。}
#{166}{}{I did not ask him. To live in a hole like Bridgeport is not for me. I??m better off with bikers.}
{166}{}{我没有问他。住在布里奇波特这样的洞里不适合我。我最好和骑自行车的人在一起。}
#{167}{}{I don??t wanna know about it. I wouldn't steal from a farmer. Let??s just leave that stash a secret.}
{167}{}{我不想知道。我不会偷农夫的东西。让我们把这个秘密留给别人吧。}
#{168}{}{Okay, it??s in the bathroom under the tub. You just have to move the planks from the floor.}
{168}{}{好的，在浴室里，在浴缸下面。你只要把木板从地板上移开就行了。}
#{169}{}{Under the tub? Great, I will check it out.}
{169}{}{在浴缸下面？太好了，我去看看。}
#{170}{}{You don??t impress me. Fine, if you don??t want it I won??t make you.}
{170}{}{你没有给我留下深刻印象。好吧，如果你不想要的话，我不会让你做的。}
#{171}{}{Good.}
{171}{}{很好。}
#{172}{}{You??re making a mistake. You have a home and a family that needs you. The bikers are just a bunch of strangers.}
{172}{}{你犯了个错误。你有一个家和一个需要你的家庭。骑自行车的人只是一群陌生人。}
#{173}{}{So? I??m sick of this place. You??re telling me to just stay here? I'd rather die!}
{173}{}{所以呢？我讨厌这个地方。你要我呆在这里？我宁愿死！}
#{174}{}{Look at yourself. You have nothing in common with the bikers. Even if you pass all the tests, you won??t be able to live like they do. Eventually, you'll become only a burden to them. Think about your family - not many have the luxury to live in a place like this.}
{174}{}{看看你自己。你和骑自行车的人没什么共同点。即使你通过了所有的考试，你也不能像他们那样生活。最终，你只会成为他们的负担。想想你的家人吧——没有多少人有奢侈的生活在这样的地方。}
#{175}{}{It seems I cant change your mind. I??ll try some other time. Bye.}
{175}{}{看来我改变不了你的主意。我改天再试试。再见。}
#{176}{}{I didn??t think about that... I thought I would learn everything in my time. But you??re right - am I like them? I won??t pass the tests. And my home... As much as I don??t want to rot here, I can see your point - this is the only place where I??m really needed... Man, I??m confused.}
{176}{}{我没想到...我想我会在我的时代学到一切。但你说得对-我喜欢他们吗？我不会通过考试的。我的家...虽然我不想在这里腐烂，但我明白你的意思——这是唯一真正需要我的地方...伙计，我很困惑。}
#{177}{}{Come back to your father and tell him you??ll stay with him. It will be best for everyone.}
{177}{}{回到你父亲身边，告诉他你会和他在一起。这对每个人都是最好的。}
#{178}{}{The thing is, you??re not ready. So give me some time too, so I can answer.}
{178}{}{问题是，你还没准备好。所以也给我点时间，好让我回答。}
#{179}{}{Okay. I??ll do that.}
{179}{}{可以。我会的。}
#{180}{}{Great.}
{180}{}{伟大的。}
