#{100}{}{You see Zhu Shi.}
{100}{}{你看朱熹。}
#{101}{}{You see a woman with unusual skin color and slanted eyes.}
{101}{}{你看到的是一个肤色不寻常、眼睛歪斜的女人。}
#{102}{}{You see Zian Shi.}
{102}{}{你看资安石。}
#{103}{}{You see a man with unusual skin color and slanted eyes.}
{103}{}{你看到一个肤色不寻常、眼睛歪斜的男人。}
#{110}{}{My respect, sir.}
{110}{}{尊敬的先生。}
#{111}{}{My respect, sheriff.}
{111}{}{尊敬的，警长。}
#{112}{}{Best regards.}
{112}{}{致以最诚挚的问候。}
#{113}{}{I'd like to know how you ended up here.}
{113}{}{我想知道你是怎么来到这里的。}
#{114}{}{What do you do in this little town?}
{114}{}{你在这个小镇做什么？}
#{115}{}{Why don't you leave to somewhere where life is better?}
{115}{}{你为什么不去一个生活更好的地方呢？}
#{116}{}{Me and my husband Zian are from San-Francisco. Emperor decided that we are useless to the community and banished us. Well, sometimes he's a little too harsh, but we didn't mind.}
{116}{}{我和我丈夫齐安来自旧金山。皇帝认为我们对社会毫无用处，就把我们放逐了。嗯，有时候他有点太苛刻了，但我们不介意。}
#{117}{}{Me and my wife Zhu are from San-Francisco. Emperor decided that we are useless to the community and banished us. Well, sometimes he's a little too harsh, but we didn't mind.}
{117}{}{我和我妻子朱是旧金山人。皇帝认为我们对社会毫无用处，就把我们放逐了。嗯，有时候他有点太苛刻了，但我们不介意。}
#{118}{}{Who's Emperor?}
{118}{}{谁是皇帝？}
#{119}{}{Tell me about San-Francisco.}
{119}{}{告诉我旧金山的情况。}
#{120}{}{Why didn't you mind?}
{120}{}{你为什么不介意？}
#{121}{}{No one saw Emperor since the founding of Palace. And it was a long time ago. We only know that he lives in the Palace, and no one, except his First Advisor, can go see him.}
{121}{}{自从皇宫建立以来，没有人见过皇帝。那是很久以前的事了。我们只知道他住在皇宫里，除了他的第一个顾问，没有人能去看他。}
#{122}{}{Ruins and ruins again - that is what awaits any traveler. But Shi are trying to restore the city with the hard labor. Palace is already rebuilt, clan already settled in dormitory suburbs, other areas are waiting for their turn.}
{122}{}{废墟一片又一片——这是等待任何旅行者的。但施正试图用辛勤的劳动来重建这座城市。皇宫已经重建，宗族已经定居在宿舍郊区，其他地区正在等待轮到他们。}
#{123}{}{We do not dare resisting the will of the Emperor. He decided that - so we must obey. But we like living as farmers, I must say. The soil smells of life and soothes - and city ruins only set anguish and anger upon us.}
{123}{}{我们不敢违抗皇帝的意志。他决定-所以我们必须服从。但我必须说，我们喜欢农民的生活。这片土地散发着生命的气息，令人心旷神怡，而城市废墟只会给我们带来痛苦和愤怒。}
#{124}{}{We cultivate maize and breed Brahmin. We are peasants, we are born to do this.}
{124}{}{我们种植玉米，培育双头牛。我们是农民，我们生来就是要这样做的。}
#{125}{}{But we live here well. We grow crops, breed cattle, we are not hampered by the noise and bustle of the big city. Now this is our home. And we do not want to leave, even if the earth dragons devour all our brahmin.}
{125}{}{但我们住在这里很好。我们种庄稼，养牛，我们不受大城市喧嚣的阻碍。现在这是我们的家。我们不想离开，即使地上的龙吞噬了我们所有的双头牛。}
#{126}{}{Earth dragons?}
{126}{}{地球龙？}
#{127}{}{Oh, Nelson hasn't told yet? The greed of people that worked at the mine awakened the earth dragons. They want to punish people, as God once punished them with an infernal flame that wiped out entire cities.}
{127}{}{哦，纳尔逊还没告诉我？在矿场工作的人们的贪婪唤醒了地球上的巨龙。他们想要惩罚人们，就像上帝曾经用毁灭整个城市的地狱之火惩罚他们一样。}
#{128}{}{Let's suppose I want to meet them. What do I need for this?}
{128}{}{假设我想见他们。我需要什么？}
#{129}{}{Well, then there is nothing easier than to create more noise. We even had to remove the noisemaker made from cans, that guarded our herd at night. It's on the shelves.}
{129}{}{那么，没有什么比制造更多的噪音更容易的了。我们甚至不得不把罐头做的噪音制造器移走，它在晚上保护着我们的牛群。它在架子上。}
#{150}{}{I apologize, but your brahmin is needed to save this settlement.}
{150}{}{我很抱歉，但是你的双头牛需要拯救这个定居点。}
#{151}{}{Betty? She's the only one left. We can not give it away just like that.}
{151}{}{贝蒂？她是唯一剩下的人。我们不能就这样把它送人。}
#{152}{}{Betty? Do you give names to all your Brahmin?}
{152}{}{贝蒂？你给你所有的双头牛起名字了吗？}
#{153}{}{Think about it - someday these underground creatures not only will eat miners, but will get to you and Betty.}
{153}{}{想想看，总有一天，这些地下生物不仅会吃掉矿工，还会吃掉你和贝蒂。}
#{154}{}{I can buy this brahmin. Will 1000 bucks satisfy you?}
{154}{}{我可以买这个双头牛。1000美元能让你满意吗？}
#{155}{}{You think about the offer, while I walk around.}
{155}{}{当我四处走动的时候，你想想这个提议。}
#{156}{}{Actually, it's not us who called her like that, but the old Nelson. He called all our brahmin with such name, sometimes muttering, as if in jest: "Betty, my beauty, you want a ride in my car?" Seems like a long life without women is affecting him, tee-hee.}
{156}{}{实际上，不是我们这样叫她，而是老尼尔森。他用这样的名字称呼我们所有的双头牛，有时喃喃自语，好像在开玩笑：“贝蒂，我的美人，你想坐我的车吗？”似乎没有女人的漫长生活影响着他，泰熙。}
#{157}{}{[They whisper with each other for a while] We agree.}
{157}{}{[他们窃窃私语了一会儿]我们同意。}
#{158}{}{Here's the money.}
{158}{}{这是钱。}
#{159}{}{I'll return with money.}
{159}{}{我会带着钱回来的。}
#{160}{}{We'll be sorry to part with Betty...}
{160}{}{我们很抱歉和贝蒂分手...}
#{161}{}{It does not matter anymore. Now she's mine!}
{161}{}{这已经不重要了。现在她是我的了！}
#{162}{}{I understand. But nothing lasts forever.}
{162}{}{我理解。但没有什么是永恒的。}
#{163}{}{[They whispers with each other for a while] We understand. We'll be sorry to part with Betty, but your words sounds so wise that we can't refuse.}
{163}{}{[他们窃窃私语了一会儿]我们理解。我们很抱歉与贝蒂分手，但你的话听起来很明智，我们无法拒绝。}
#{164}{}{[They shake their heads] The greedy miners are to blame themselves. Dragons will not touch those who live in peace, like us. All our property is a shack and Betty, so what can make up for loosimg her?}
{164}{}{[他们摇头]贪婪的矿工应该自责。龙不会碰那些像我们这样生活在和平中的人。我们所有的财产都是一间小屋和贝蒂，那么失去她又能得到什么补偿呢？}
#{165}{}{Thanks, you did the right thing.}
{165}{}{谢谢，你做得对。}
#{1110}{}{My respect, ma'am.}
{1110}{}{尊敬的女士。}
