#{100}{}{You see Nelson.}
{100}{}{你看到尼尔森了。}
#{101}{}{You see a ghoul, burned through with hellish mixture of radiation, Rot gut and huge ambitions to big earnings.}
{101}{}{你会看到一个食尸鬼，被地狱般的辐射、腐烂的肠子和追求高额收入的巨大野心所吞噬。}
#{110}{}{[Stands looking at you, pretending to be a cowboy from a movie] Who are you? if Wright sent you for negotiations - then get the hell out of here, while I??m in a good mood.}
{110}{}{你是谁？如果赖特派你来谈判的话-那就滚吧，趁我心情好的时候。}
#{111}{}{Easy, I have no interest in your beef with some Wright.}
{111}{}{别紧张，我对你和赖特的关系不感兴趣。}
#{112}{}{Then what the hell are you doing here?}
{112}{}{那你到底在这里干什么？}
#{113}{}{I??m just traveling and looking for a place to stay the night.}
{113}{}{我只是在旅行，想找个地方过夜。}
#{114}{}{Is that so? Fine, you can enter. But keep in mind - I'll be watching you. And don??t think that I??m so blind, as I may seem in this ghoul skin.}
{114}{}{是这样吗？好的，你可以进去。但请记住-我会看着你的。别以为我瞎了眼，就像我在这食尸鬼的皮肤里一样。}
#{115}{}{Uh, right. Whatever you say.}
{115}{}{嗯，对。不管你说什么。}
#{116}{}{No negotiations. I??m the boss here, until I find out what is what.}
{116}{}{没有谈判。我是这里的老板，直到我发现什么是什么。}
#{117}{}{[Opens widely one of his eyes, which makes him look even more crazier, than before] Hmm... Say whatever you want, it won??t solve the problem. The big daddy from the big city won??t deal with local problems, even with his loads of money. So, if you want to try that - go on ahead.}
{117}{}{[睁开一只眼睛，看起来比以前更疯狂]嗯...想说什么就说什么，解决不了问题。来自大城市的大老爹不会处理当地的问题，即使他有很多钱。所以，如果你想试试的话-继续吧。}
#{118}{}{Well, then you??re no problem to me. Take care for now.}
{118}{}{好吧，那你对我来说没问题。现在小心点。}
#{119}{}{You confuse me with someone, I don??t know any Wright.}
{119}{}{你把我和某人搞混了，我不认识任何人。}
#{150}{}{What is this? Corvega? Meh - a pickup, 72' model. Shitty car.}
{150}{}{这是什么？科维加？一辆皮卡，72英尺型号。糟糕的车。}
#{151}{}{Well, better than nothing...}
{151}{}{好吧，总比什么都没有好...}
#{152}{}{What would you know about cars, rotting corpse?}
{152}{}{你对汽车，腐烂的尸体了解多少？}
#{153}{}{Don??t you dare insulting the best car in Nevada!}
{153}{}{你敢侮辱内华达最好的车！}
#{154}{}{[Mumbles] If today were 77th, I would show you what a real car is. But yeah, in our times even a piece of junk with wheels is good enough.}
{154}{}{[喃喃自语]如果今天是77号，我会告诉你什么是真正的汽车。但是，在我们这个时代，即使是一块带轮子的垃圾也足够了。}
#{155}{}{Do not exaggerate. Many have underestimated me in the past. And I??m still alive. And I must say, this doesn??t change the facts... Alas, I forget sometimes, the times we live in. If there would be 77th, I would show you then, what is a real car. But yeah, in our times even a junk on wheels is good enough.}
{155}{}{不要夸大其词。过去很多人都低估了我。我还活着。我必须说，这并不能改变事实...唉，我有时会忘记，我们生活的时代。如果有第77位，我会告诉你，什么是真正的汽车。但是，在我们这个时代，即使是一辆破车也足够了。}
#{156}{}{Oh yeah, I forget sometimes, the times we live in. If today were 77th, I would show you, what a real car is. But yeah, in our times even a junk with wheels is considered good enough.}
{156}{}{哦，是的，我有时会忘记，我们生活的时代。如果今天是77号，我会告诉你，什么是真正的汽车。但是，在我们这个时代，即使是带轮子的垃圾也被认为是足够好的。}
#{157}{}{I would prefer it instead of walking anytime, be sure.}
{157}{}{我宁愿去那里，也不要在任何时候走路。}
#{170}{}{Boop? Is that you? Baby, let me give you a ride on my wheels! Oh... Nevermind, forget it...}
{170}{}{博普？是你吗？宝贝，让我载你一程！哦...别担心，算了吧...}
#{171}{}{Who is Boop?}
{171}{}{波普是谁？}
#{172}{}{Hey, can we have some privacy?! It??s not your business!}
{172}{}{嘿，我们能有点隐私吗？！这不关你的事！}
#{173}{}{Er, whatever...}
{173}{}{呃，不管怎样...}
#{180}{}{You know, Lewis Birch is up to something.}
{180}{}{你知道，刘易斯·伯奇在搞什么鬼。}
#{181}{}{Amazing - how can you and I think the same things about him! Although, why would you talk about it?}
{181}{}{太棒了-你和我怎么能对他有同样的想法！不过，你为什么要谈这个？}
#{182}{}{He asked me to deliver some encoded message to Hub. That bastard is sly. We should throw him out of the City.}
{182}{}{他让我把一些编码的信息传送到中心。那个混蛋很狡猾。我们应该把他赶出城市。}
#{183}{}{You know, I will check it again first.}
{183}{}{你知道，我会先再检查一遍。}
#{184}{}{Secret message? Ha! I got this piece of shit! He won??t get away this time. Hey, guys, settle up, there is an idiot that needs to be thrown out of Uranium City!}
{184}{}{秘密消息？哈！我得到了这狗屎！他这次逃不掉了。嘿，伙计们，冷静点，有个白痴要被赶出铀城！}
#{185}{}{Tee-hee. Be careful.}
{185}{}{泰姬。小心。}
#{186}{}{Ha-ha! We drove him away. He was in such a hurry, that left his stuff in the room. Such a cretin!}
{186}{}{哈哈！我们把他赶走了。他太急了，把东西忘在房间里了。真是个白痴！}
#{187}{}{Aha. That was fun, but it??s time for me to go.}
{187}{}{啊哈。那很有趣，但我该走了。}
#{188}{}{It should be useful for you to know, that he send a report to Hub with a request of people to come here to take over the City. I??ve seen the report with my own eyes.}
{188}{}{你应该知道，他给中心发了一份报告，要求人们来这里接管这座城市。我亲眼看到了这份报告。}
#{200}{}{What do you want?}
{200}{}{你想要什么？}
#{201}{}{Tell me about the problem with Wright. What happened?}
{201}{}{告诉我赖特的问题。怎么搞的？}
#{202}{}{I want to know more about you - you??re interesting to me.}
{202}{}{我想更多地了解你——你对我很有意思。}
#{203}{}{What can you tell about Uranium City?}
{203}{}{关于铀城你能说些什么？}
#{204}{}{Why there is so few people living here?}
{204}{}{为什么这里住的人那么少？}
#{205}{}{Nothing, everything is good.}
{205}{}{没什么，一切都很好。}
#{206}{}{Between us? The damn swarm of worms shat between us. And each has shat so much, that me or Wright can't even approach. Though, I think sometimes, he??s just disgusted by my looks.}
{206}{}{我们之间？那群该死的虫子在我们中间。每一个都有太多，以至于我或赖特都无法接近。不过，我想有时候，他只是讨厌我的长相。}
#{207}{}{Yes. I??m Nelson. Remember that.}
{207}{}{对。我是尼尔森。记住这一点。}
#{208}{}{This is my home. And that??s it. Almost my entire life I lived here. I don??t want to travel anymore, neither to go back south.}
{208}{}{这是我的家。就这样。我几乎一生都住在这里。我不想再旅行了，也不想回南方。}
#{209}{}{You really want to know? What if I tell they don??t belong here? Though yes, most of the locals simply died. Not because of me, don??t look at me like that.}
{209}{}{你真的想知道吗？如果我告诉他们不属于这里怎么办？是的，大部分当地人都死了。不是因为我，别那样看着我。}
#{210}{}{Tony lays lifeless in your room.}
{210}{}{托尼躺在你的房间里毫无生气。}
#{211}{}{I don??t like bad news... Yes I knew, he hasn??t much time left. I hoped, he will go through ghoulification, like me. But no!}
{211}{}{我不喜欢坏消息...是的，我知道，他剩下的时间不多了。我希望，他会像我一样经历食尸鬼的折磨。但是没有！}
#{212}{}{Let's leave it for now, there are other subjects.}
{212}{}{我们先别说了，还有别的题目。}
#{213}{}{That is all I wanted to know.}
{213}{}{我只想知道这些。}
#{214}{}{Everything's good, sheriff?}
{214}{}{一切都好吗，警长？}
#{220}{}{Tell me about the mutants in the mines.}
{220}{}{告诉我矿井里的变种人。}
#{221}{}{What will you do with the mine now?}
{221}{}{你现在拿我的怎么办？}
#{222}{}{And what are you going to do with it?}
{222}{}{你打算怎么处理？}
#{223}{}{My little slippery worms. I dream to catch at least one, to cook it on fire. But they are so sneaky that it??s not easy. Difficult task, definitely.}
{223}{}{我的小滑虫。我梦想至少能钓到一只，在火上煮。但是他们太狡猾了，这并不容易。当然，任务很艰巨。}
#{224}{}{How many of them are there?}
{224}{}{他们有多少人？}
#{225}{}{Where did they came from?}
{225}{}{他们从哪里来的？}
#{226}{}{Where are they located?}
{226}{}{他们在哪里？}
#{227}{}{How can I attract them to surface?}
{227}{}{我怎样才能吸引他们浮出水面？}
#{228}{}{What are you going to do with them?}
{228}{}{你打算怎么处理它们？}
#{229}{}{I know how many. Three. Surprised? Yes, I learned a lot about them.}
{229}{}{我知道有多少。三个。惊讶吗？是的，我了解他们很多。}
#{230}{}{Straight from hell. The entrance there have been dug by miners, at the far end of the mine.}
{230}{}{直接从地狱来。那里的入口已经被矿工们挖了，在矿井的尽头。}
#{231}{}{That's what I think - they live underground, meaning they can move around only in friable soil. And, for some reason, they always stick close to the mine. I know, it may sound strange, but look at me - I??m alive, because I eat uranium dust for breakfast. I??m sure, they do the same.}
{231}{}{我就是这么想的——它们生活在地下，这意味着它们只能在易碎的土壤中活动。而且，出于某种原因，它们总是粘在矿井附近。我知道，这听起来很奇怪，但看看我-我还活着，因为我早餐吃铀尘。我敢肯定，他们也是这样做的。}
#{232}{}{Use your brain or whatever you have there. Maybe perfume? Of course not - they can??t smell anything down there. Perhaps, nice dress? Oh, didn??t guess it - they have no eyes. Then by dancing around with tambourine and maracas? And I will tell you - yes!}
{232}{}{用你的脑子或者其他你有的东西。也许是香水？当然没有-他们在下面什么都闻不到。也许，漂亮的衣服？哦，我没猜到-他们没有眼睛。然后用手鼓和马拉卡斯跳舞？我会告诉你-是的！}
#{233}{}{I wanted to befriend them, but they steer clear of me, no matter how much I tried. I don??t know why. The only option is to put someone in the middle of the field with a dynamite, but for some reason everyone refused. Hmm, you know, you could do pretty well.}
{233}{}{我想和他们做朋友，但不管我怎么努力，他们总是避开我。我不知道为什么。唯一的选择是把一个人用炸药放在场地中间，但由于某种原因，每个人都拒绝了。嗯，你知道，你可以做得很好。}
#{234}{}{I placed something to make sound and vibration and attract the mutants. I wouldn??t mind few more guns for the fight.}
{234}{}{我放了一些东西来制造声音和振动，吸引变种人。我不介意再多带几把枪去打仗。}
#{235}{}{Do you know where to get dynamite? I want to make a brahmin to go inside with it.}
{235}{}{你知道在哪儿能买到炸药吗？我想做一个双头牛进去。}
#{236}{}{I want to hunt the mutants. I wouldn??t mind few more guns for the fight.}
{236}{}{我想猎杀变种人。我不介意再多带几把枪去打仗。}
#{237}{}{How about something stronger? I??m sure you have some dynamite for mining purposes.}
{237}{}{来点烈性的怎么样？我肯定你有一些用于采矿的炸药。}
#{238}{}{In the mine there is a storage with dynamite, and I have the key for it, but I myself won??t go there. If someone brings it here, then I could make a dynamite pack, but... [thinks]}
{238}{}{矿井里有一个炸药仓库，我有钥匙，但我自己不去。如果有人把它带到这里，我可以做一个炸药包，但是...[思考]}
#{239}{}{Right. See you.}
{239}{}{正确的。再见。}
#{240}{}{Just a few simple questions.}
{240}{}{只是几个简单的问题。}
#{241}{}{Such as?}
{241}{}{比如？}
#{242}{}{Funny idea. The only one that has a decent firepower here is Kelly. talk to him, perhaps, he will agree to go with you.}
{242}{}{有趣的主意。这里唯一有火力的是凯利。和他谈谈，也许他会同意和你一起去。}
#{243}{}{I know. It??s in the mine, and I have the key from the storage room, but I won??t go there myself. I can assemble a whole dynamite pack. Oh, I see, you have a brahmin... Damn, why it has to be Betty!? Ah, fine. Nothing that can be done.}
{243}{}{我知道。它在矿井里，我有储藏室的钥匙，但我自己不去。我能装一整包炸药。哦，我明白了，你有一个双头牛...该死，为什么一定是贝蒂！？啊，很好。什么也做不了。}
#{244}{}{Give me the key, I will get the dynamite.}
{244}{}{把钥匙给我，我去拿炸药。}
#{245}{}{Not so fast, monster! I spent the best years of my life in this mine. And you want to blow it all up? I don??t want to dig it back afterwards. The most important - there is not much dynamite left. This is the last supply. What can you say about that?}
{245}{}{别那么快，怪物！我在这个矿里度过了我一生中最美好的时光。你想把一切都搞砸吗？我不想事后再把它挖回来。最重要的是，炸药所剩无几。这是最后一批货了。你能说些什么？}
#{246}{}{I??m a demolition expert. You can trust me.}
{246}{}{我是爆破专家。你可以相信我。}
#{247}{}{Yes, it??s a risk. But understand, while mutants are here, you have nothing to be so concerned about anyway. Who wants your dynamite, if even you are afraid to go get it? At least we have a chance.}
{247}{}{是的，这是一种风险。但是你要明白，当变种人在这里的时候，你没什么好担心的。如果连你都不敢去拿，谁还想要你的炸药？至少我们还有机会。}
#{248}{}{I have nothing to assure you.}
{248}{}{我没有什么可以向你保证的。}
#{249}{}{Fine, I believe you. Here is the key. And... Be careful there. Bring me the dynamite sticks, I will assemble them, to be sure in the results. You can never know...}
{249}{}{好吧，我相信你。这是钥匙。还有...小心点。把炸药棒给我，我会把它们组装起来，以确定结果。你永远不会知道...}
#{250}{}{That was the right decision, Nelson.}
{250}{}{这是正确的决定，尼尔森。}
#{251}{}{I managed to get few dynamite sticks. Can you assemble it?}
{251}{}{我设法弄到了几根炸药棒。你能把它组装起来吗？}
#{252}{}{Sure. Easy. I need five dynamite sticks, then the force of the blow will be enough to bring down the mine right on those worms.}
{252}{}{当然。容易的。我需要五根炸药棒，那么打击的力量就足以把地雷打到那些虫子身上。}
#{253}{}{Here five sticks.}
{253}{}{这里有五根棍子。}
#{254}{}{Wait. it won??t take long.}
{254}{}{等待。不会花很长时间的。}
#{255}{}{[Wait]}
{255}{}{[等等]}
#{256}{}{Here, done. I hope, you know, what you??re doing.}
{256}{}{来，搞定。我希望，你知道，你在做什么。}
#{257}{}{Good job, Nelson.}
{257}{}{干得好，尼尔森。}
#{258}{}{I'll talk to him later, for now answer some questions.}
{258}{}{我稍后再和他谈，现在回答一些问题。}
#{259}{}{You know, Tony would trust me...}
{259}{}{你知道，托尼会相信我...}
#{260}{}{If I even managed to beat that brawler at the bar three times, then to go get the dynamite is pretty easy.}
{260}{}{如果我能在酒吧里打败那个打架的人三次，那么去拿炸药就很容易了。}
#{261}{}{I did what you couldn't do all this time - killed the monsters.}
{261}{}{我做了你一直做不到的事-杀死了怪物。}
#{262}{}{Hmm. Such irony, just when I started to like them. It??s always hard to say goodbye to your loved ones. But I cannot but thank you. Good job.}
{262}{}{嗯。真讽刺，就在我开始喜欢他们的时候。和你所爱的人说再见总是很难的。但我不得不感谢你。干得好。}
#{263}{}{Good!? You should praise me for it!}
{263}{}{很好！？你应该为此表扬我！}
#{270}{}{While the worms are mangle at our feet, nothing good will come out of the mine.}
{270}{}{当虫子在我们脚下撕咬时，矿井里就不会有什么好东西出来了。}
#{271}{}{}
{271}{}{}
#{272}{}{}
{272}{}{}
#{273}{}{Listen this one, from the south, how is his name... Birch. He promised to bring a shipment of dynamite and he's interested in the restoration of the mine, so now we have a future... I think.}
{273}{}{听这个，从南方来的，他叫什么名字...桦木。他答应带一批炸药来，他对修复矿井很感兴趣，所以现在我们有了未来...我想。}
#{274}{}{Me - nothing. This mobster from big city found a way to threaten us with big explosives. Resisting is useless. I, think, I will move from here, while I??m still in one piece. That mobster memory - you know... Doesn??t forget.}
{274}{}{我-没什么。这个来自大城市的暴徒找到了一个用大炸药威胁我们的方法。抵抗是无用的。一、 想一想，我会离开这里，而我仍然在一块。黑帮的记忆-你知道...别忘了。}
#{275}{}{Well, Now we have nothing to fear, with so many explosives in our hands. So everything will be okay... At least, while I??m in charge.}
{275}{}{好吧，现在我们没什么好害怕的了，手里有这么多炸药。所以一切都会好起来的...至少，在我负责的时候。}
#{276}{}{Now, when the worms are dealt with, all that remains is to gather new team. I... We will have to work very hard.}
{276}{}{现在，当虫子被处理后，剩下的就是组建新的团队。一、 ...我们必须非常努力地工作。}
#{277}{}{ The most important thing needed right now is explosives. A lot of it. If we have it, we will keep our independence from the big daddy from the City.}
{277}{}{现在最重要的是炸药。很多。如果我们有它，我们将保持我们的独立从大爸爸从城市。}
#{278}{}{What kind of explosives do you need?}
{278}{}{你需要什么样的炸药？}
#{279}{}{About the team - who do you have in mind?}
{279}{}{关于球队-你想找谁？}
#{280}{}{It seems you have everything that is necessary. So - will you restore the Uranium City?}
{280}{}{看来你什么都有了。那么-你会修复铀城吗？}
#{281}{}{Hey, you??re right! We have people, tools too. First we must refine some ore and sell it to Wright. Then we will restore our connection with south and the east. We must earn some money to start, and attract workers. Now, everyone to their places! Get to work!}
{281}{}{嘿，你说得对！我们有人，也有工具。首先我们必须提炼一些矿石卖给赖特。然后我们将恢复与南方和东方的联系。我们必须挣些钱才能开始工作，并吸引工人。现在，大家各就各位！开始工作吧！}
#{282}{}{Damn, little bossy huh...}
{282}{}{妈的，有点专横啊...}
#{283}{}{Three people first. talk about it with Marilyn, she knows better how to find them.}
{283}{}{三个人优先。跟玛丽莲谈谈，她知道怎么找到他们。}
#{284}{}{I think Wright hired a group of prospectors, to get C-4 box from the military base. It will be enough for now. The question is who are they and where is the base.}
{284}{}{我想赖特雇了一群探矿者，从军事基地搞到C-4盒子。现在就足够了。问题是他们是谁，基地在哪里。}
#{285}{}{It happens, that I have everything, you need. Here.}
{285}{}{碰巧，我拥有你所需要的一切。在这里。}
#{286}{}{What - just like that you will give it away? Interesting. Listen, I??ve learned in my life, that nobody works for free. I'll give you a 1000 bucks for your trouble.}
{286}{}{什么-就这样你要把它送人？很有趣。听着，我这辈子学到了，没有人是免费工作的。我给你1000块钱来补偿你的麻烦。}
#{287}{}{Thanks for the money. See you, Nelson.}
{287}{}{谢谢你的钱。再见，尼尔森。}
#{1188}{}{It should be useful for you to know, that he send a report to Hub with a request of people to come here to take over the City. I??ve seen the report with my own eyes.}
{1188}{}{你应该知道，他给中心发了一份报告，要求人们来这里接管这座城市。我亲眼看到了这份报告。}
#{1232}{}{Use your brain or whatever you have there. Maybe perfume? of course not - they can??t smell anything down there. Perhaps, nice dress? Oh, didn??t guess it - they have no eyes. Then by dancing with tambourine and maracas? And I will tell you - yes!}
{1232}{}{用你的脑子或者其他你有的东西。也许是香水？当然没有-他们在下面什么都闻不到。也许，漂亮的衣服？哦，我没猜到-他们没有眼睛。然后用手鼓和马拉卡斯跳舞？我会告诉你-是的！}
#{1233}{}{I wanted to befriend them, but they steer clear of me, no matter how much I tried. I don??t know why. The only option is to put someone in the middle of the field with a dynamite, but for some reason everyone refused. Hmm, you know, you could do pretty well.}
{1233}{}{我想和他们做朋友，但不管我怎么努力，他们总是避开我。我不知道为什么。唯一的选择是把一个人用炸药放在场地中间，但由于某种原因，每个人都拒绝了。嗯，你知道，你可以做得很好。}
#{1234}{}{I placed something to make sound and vibration and attract the mutants. I wouldn??t mind few more guns for the fight.}
{1234}{}{我放了一些东西来制造声音和振动，吸引变种人。我不介意再多带几把枪去打仗。}
#{1249}{}{Fine, I believe you. Here is the key. And... Be careful there. Bring me the dynamite sticks, I will assemble them, to be sure in the results. You can never know...}
{1249}{}{好吧，我相信你。这是钥匙。还有...小心点。把炸药棒给我，我会把它们组装起来，以确定结果。你永远不会知道...}
#{1261}{}{I did what you couldn't do all this time - killed the monsters.}
{1261}{}{我做了你一直做不到的事-杀死了怪物。}
