#{100}{}{You see Juan.}
{100}{}{你看到胡安了。}
#{101}{}{You see a strong miner with large exposed muscles.}
{101}{}{你看到一个强壮的矿工，肌肉外露。}
#{102}{}{Leave me alone! I'll drink myself to death without Nelson.}
{102}{}{别管我！没有尼尔森我会喝得烂醉。}
#{103}{}{It's a test, yo!}
{103}{}{这是个考验，哟！}
#{107}{}{Make yourself at home.}
{107}{}{别拘束。}
#{108}{}{Somehow you don't look particularly friendly. As if your hands itching for a fight.}
{108}{}{不知怎么的，你看起来不是特别友好。好像你的手渴望打架。}
#{109}{}{Would the sheriff waste his time on empty talk?}
{109}{}{警长会把时间浪费在空谈上吗？}
#{110}{}{[Scratching his long unshaved chin with hairy hand] You will call me Juan. And I don't give a shit what do your think about it. And if you want to argue, I'm always at your service.}
{110}{}{[用毛茸茸的手抓着他长长的下巴]你会叫我胡安。我才不管你怎么看呢。如果你想争辩，我随时为你效劳。}
#{111}{}{I see you're a skilled debater.}
{111}{}{我看你是个辩论能手。}
#{112}{}{[Examines his thick palms] These hands handled so many arguments that yours will be a piece of cake. [He folds his arms and looks at you dismissively and sharply] Don't believe me? You're right for not believing. It's never too late to prove.}
{112}{}{[检查他厚厚的手掌]这些手处理了太多的争论，你的手将是小菜一碟。[他交叉双臂，轻蔑而尖锐地看着你]你不相信我？你不相信是对的。证明永远不会太迟。}
#{113}{}{Good. I accept the challenge! Where it will be more convenient to beat your face?}
{113}{}{很好。我接受挑战！在哪里打你的脸更方便？}
#{114}{}{I do not want anyone to prove anything to me right now. Let's just talk?}
{114}{}{我现在不想任何人向我证明任何事情。我们谈谈吧？}
#{115}{}{I don't like this chat, so I leave.}
{115}{}{我不喜欢这样聊天，所以我离开了。}
#{116}{}{If you want to say something, don't mumble, speak loud and clear. We don't like windbags here.}
{116}{}{如果你想说什么，不要喃喃自语，大声说清楚。我们不喜欢这里的风袋。}
#{117}{}{I recall you wanted to argue who's stronger. So, did you change your mind yet?}
{117}{}{我记得你想争论谁更强壮。那么，你改变主意了吗？}
#{118}{}{Who are you?}
{118}{}{你是谁？}
#{119}{}{How did you end up here?}
{119}{}{你怎么到这里来的？}
#{120}{}{How do you feel about Nelson?}
{120}{}{你觉得纳尔逊怎么样？}
#{121}{}{Enough chatter for today.}
{121}{}{今天闲聊够了。}
#{122}{}{You're hard on hearing? Juan, told you already. I worked in the mine until it closed. I could work even now, but there's nobody to pay me.}
{122}{}{你听力不好？胡安，我已经告诉过你了。我一直在矿井里工作，直到矿井关闭。我现在还能工作，但没人付钱给我。}
#{123}{}{I came from Vegas, right after they stopped giving me jobs. They said that I have a bad temper. Ha! For real?! They should regret that they got rid of me.}
{123}{}{我从维加斯来，就在他们停止给我工作之后。他们说我脾气不好。哈！真的吗？！他们应该为摆脱我而后悔。}
#{124}{}{G-great fellow. I immediately loved him as a brother. So just touch him - and you're dead, alright? And then - who else, but him, could organize everything in here?}
{124}{}{伟大的家伙。我立马把他当哥哥一样爱。所以只要碰他-你就死定了，好吗？然后-除了他，还有谁能组织这里的一切？}
#{125}{}{[Scratches the chest with thick fingers and assesses you] I'm no masochist. To scuffle without the reason is not for me. If you want to beat me in arm wrestling, then I'm at your service. Right now, on the table at Marilyn's. Who loses, pays 100 bucks. How do you like this option?}
{125}{}{我不是受虐狂。无缘无故地扭打对我来说是不合适的。如果你想在摔跤比赛中打败我，我会为你效劳的。现在，在玛丽莲的桌子上。谁输了，就付100美元。你觉得这个选项怎么样？}
#{126}{}{Excellent! I place my bet and accept the challenge!}
{126}{}{杰出的！我下注接受挑战！}
#{127}{}{I first ask a few questions.}
{127}{}{我先问几个问题。}
#{128}{}{Can't do right now. Later.}
{128}{}{现在不行。以后再说。}
#{129}{}{[Whistles] Hey, everyone in the bar! Now I'll make someone hell.}
{129}{}{嘿，酒吧里的每个人！现在我要让某人下地狱。}
#{130}{}{[Go to the bar, sit at a table and start a match]}
{130}{}{[去酒吧，坐在桌子旁开始比赛]}
#{131}{}{Wouldn't Marylin mind it?}
{131}{}{你不介意吗？}
#{132}{}{Probably she would. But I didn't ask her.}
{132}{}{也许她会的。但我没问她。}
#{133}{}{Well? Suckers aren't getting along here, and you seem to want to prove you're not one.}
{133}{}{好？笨蛋们在这里相处不好，你似乎想证明你不是。}
#{134}{}{I'm not healthy, cough-cough, maybe next time.}
{134}{}{我不健康，咳嗽，也许下次吧。}
#{135}{}{And I just changed my mind. And I don't care what you think about it.}
{135}{}{我改变了主意。我不在乎你怎么想。}
#{140}{}{Tony passed out.}
{140}{}{托尼昏过去了。}
#{141}{}{It must've happened someday. I hope he gets a place in hell somewhere near the exit.}
{141}{}{一定有一天会发生的。我希望他能在出口附近的地狱里找到一个地方。}
#{142}{}{Let's change the topic.}
{142}{}{我们换个话题吧。}
#{143}{}{That's all.}
{143}{}{这就是全部。}
#{150}{}{*Ar-r-rg!*}
{150}{}{*Ar-r-rg！*}
#{151}{}{*Hmmm-m!*}
{151}{}{*嗯，嗯！*}
#{152}{}{*Hy-y-y-a*}
{152}{}{*Hy-y-y-a公司*}
#{153}{}{A-ARG, YOU FUCKER!!}
{153}{}{阿格，你个混蛋！！}
#{154}{}{You won the arm wrestling match.}
{154}{}{你赢得了摔跤比赛。}
#{155}{}{You lost the arm wrestling match.}
{155}{}{你在摔跤比赛中输了。}
#{156}{}{Phew... No one could beat me in this for a long time, then you just showed up! Where did you come from? Okay it doesn't matter. Here is my bet.}
{156}{}{呸...很长一段时间没人能打败我，然后你就出现了！你从哪里来的？好吧，没关系。这是我的赌注。}
#{157}{}{Here, you'll think twice before messing with me.}
{157}{}{在这里，你要三思而后行。}
#{158}{}{Ha! I thought you're a serious opponent. [Takes your bet] Yeah, even geckos give me more trouble.}
{158}{}{哈！我以为你是个很厉害的对手。是啊，连壁虎都给我添麻烦了。}
#{159}{}{Probably not my lucky day.}
{159}{}{可能不是我的幸运日。}
#{160}{}{And you are just got not enough, are you? Well, let's have a rematch. Here and now, on the table at Marilyn's. The bet is the same - $ 100. Satisfies you?}
{160}{}{你只是不够，是吗？好吧，我们再来一次。现在，在玛丽莲的桌子上。赌注是一样的——100美元。你满意吗？}
#{161}{}{What the hell! Again! That's it, I will no longer challenge you, enough of this. Take the bet and do not even mention it, you got it?}
{161}{}{我勒个去！再一次！就这样，我不会再挑战你了，够了。赌一把，别提了，明白吗？}
#{1135}{}{And I just changed my mind. And I don't care what you think about it.}
{1135}{}{我改变了主意。我不在乎你怎么想。}
#{1156}{}{Phew... No one could beat me in this for a long time, then you just showed up! Where did you come from? Okay it doesn't matter. Here is my bet.}
{1156}{}{呸...很长一段时间没人能打败我，然后你就出现了！你从哪里来的？好吧，没关系。这是我的赌注。}
