#{100}{}{You see Carl.}
{100}{}{你看到卡尔了。}
#{101}{}{You see the operator of the ore processing machine.}
{101}{}{你看到了矿石处理机的操作员。}
#{110}{}{Hey, hey! What brings you here?}
{110}{}{嘿，嘿！什么风把你吹来了？}
#{111}{}{I have a similar question - how was the trip?}
{111}{}{我有一个类似的问题-旅途怎么样？}
#{112}{}{I want to ask how the things are going.}
{112}{}{我想问问事情进展如何。}
#{113}{}{Bye.}
{113}{}{再见。}
#{114}{}{Well, my wife didn??t even wanted me to leave the house, but I persuaded her and left her all my money. Pretty risky move, but you gave me new hope for life in this town. So I fully expect to get 'em back, even if I die from radiation after a year.}
{114}{}{嗯，我妻子甚至不想我离开这所房子，但我说服了她，把我所有的钱都留给了她。很冒险的举动，但你给了我在这个城市生活的新希望。所以我完全希望他们回来，即使我一年后死于辐射。}
#{115}{}{Uh, a year?}
{115}{}{呃，一年？}
#{116}{}{Well, people don??t live long around here. And I have to work with the ore processing machine, you know.}
{116}{}{嗯，这里的人活得不长。你知道，我得和矿石加工机一起工作。}
#{117}{}{Tell me about your job.}
{117}{}{告诉我你的工作。}
#{118}{}{Yeah, not very good, really. The machine's automated computer broke down, Now I have to manually manage this hulking thing. It takes a lot time, and I'm more exposed to radiation that way. I have to normalize my schedule and work only four times a day, with long breaks. If we had a supplier, he probably could find the part to fix the machine.}
{118}{}{是的，不是很好，真的。机器的自动计算机坏了，现在我不得不手动管理这个笨重的东西。这需要很多时间，而且我更容易受到辐射。我必须使我的日程正常化，一天只工作四次，有很长的休息时间。如果我们有供应商，他可能会找到修理机器的零件。}
#{119}{}{Yeah, not very good, really. The machine's automated computer broke down, Now I have to manually manage this hulking thing. It takes a lot time, and I'm more exposed to radiation that way. I have to normalize my schedule and work only four times a day, with long breaks. I ordered the needed part from our supplier, but search will take some time.}
{119}{}{是的，不是很好，真的。机器的自动计算机坏了，现在我不得不手动管理这个笨重的东西。这需要很多时间，而且我更容易受到辐射。我必须使我的日程正常化，一天只工作四次，有很长的休息时间。我向我们的供应商订购了所需的零件，但搜索需要一些时间。}
#{120}{}{Now everything is just fine! The computer on the machine now does all the work for me, and I don't have much time to sit in an irradiated room. Thanks for your help, }
{120}{}{现在一切都好了！机器上的电脑现在帮我完成了所有的工作，我没有太多时间坐在一间被辐射过的房间里。谢谢你的帮助，}
#{121}{}{sheriff.}
{121}{}{警长。}
#{122}{}{wanderer.}
{122}{}{流浪者。}
#{123}{}{What kind of part is needed to fix the machine?}
{123}{}{修理机器需要什么零件？}
#{124}{}{There is a blown fuse. Not that it is such a rarity, but we still don??t have it.}
{124}{}{保险丝烧断了。并不是说它如此稀有，但我们仍然没有它。}
#{125}{}{I've got some fuse. Will this do?}
{125}{}{我有保险丝。这样行吗？}
#{126}{}{Exactly what I need! Listen, I can't pay for this thing now, but when the supplier shows up, he'll pay, he really will! Without this part I'm as good as without hands.}
{126}{}{正是我需要的！听着，我现在付不起钱，但当供应商出现时，他会付的，他真的会付的！没有这部分我就像没有手一样好。}
#{127}{}{Exactly what I need! Look, I still can't pay for this thing, but our supplier can. Without this part I as without hands.}
{127}{}{正是我需要的！听着，我还是付不起钱，但我们的供应商可以。没有这部分我就像没有手一样。}
#{128}{}{Then take it.}
{128}{}{那就拿去吧。}
#{129}{}{I'll think about it.}
{129}{}{我会考虑的。}
#{130}{}{Thanks! Now I'm gonna work to the fullest. When the supplier shows up, he will return the money. As for me - I owe you some rotgut.}
{130}{}{谢谢！现在我要全力工作。当供应商出现时，他会退钱的。至于我-我欠你一些罗古特。}
#{131}{}{Thanks! Now I'm gonna work to the fullest. Ask the supplier in his office, he will return the money, As for me - I owe you some rotgut.}
{131}{}{谢谢！现在我要全力工作。问问他办公室里的供应商，他会把钱还的，至于我——我欠你一些钱。}
#{132}{}{Goodbye.}
{132}{}{再见。}
#{133}{}{The operator looks worried, as you are looking for the item in your pockets.}
{133}{}{接线员看起来很担心，因为你正在寻找口袋里的东西。}
#{134}{}{Near the mine stands a big mechanic machine for the ore processing. You put raw ore at one side and get purified uranium and mountains of slag at the other. I'm controlling that machine. The matter is more complicated than it seems to be. Besides, the job happens near irradiated ore.}
{134}{}{在矿井附近有一台大型选矿机械。你把原矿放在一边，另一边得到提纯的铀和堆积如山的矿渣。我在控制那台机器。这件事比看上去要复杂得多。此外，这项工作发生在辐照矿石附近。}
#{135}{}{So why are you working there, if you're constantly exposed?}
{135}{}{如果你经常暴露在外，你为什么要在那里工作？}
#{136}{}{Because it's the only honest way to feed my family. Of course, I will die in a year - two at best, if I don't exceed the rate of exposure. But, during this time, my family will be supplied with money for several years ahead.}
{136}{}{因为这是养活我家人的唯一诚实的方法。当然，我会在一年内死去——如果我不超过曝光率，最多两年。但是，在这段时间里，我的家庭将获得未来几年的资金供应。}
#{1122}{}{wanderer.}
{1122}{}{流浪者。}
