#{100}{}{You see a closet with arsenal.}
{100}{}{你看到一个有军火库的壁橱。}
#{101}{}{You see a basic wardrobe, equipped for the storage of firearms.}
{101}{}{你会看到一个基本的衣柜，用来存放枪支。}
#{102}{}{The mistress won't like it if someone will be digging in here without permission.}
{102}{}{如果有人未经允许在这里挖东西，女主人会不喜欢的。}
#{103}{}{Well, well, well, would you like to ask me first, m?}
{103}{}{好吧，好吧，好吧，你想先问我吗，m？}
#{104}{}{Next time you try something without permission - you'll get your ass kicked}
{104}{}{下一次你未经允许就做某事的时候，你会被踢屁股的}
#{105}{}{Well, I've had enough!}
{105}{}{我受够了！}
#{106}{}{You delivered the administrator of the guild to the destination using your car.}
{106}{}{你用你的车把帮会管理员送到了目的地。}
#{107}{}{You delivered the operator to the destination using your car.}
{107}{}{你用你的车把接线员送到了目的地。}
#{108}{}{You delivered the guild supplier to the destination using your car.}
{108}{}{你用你的车把帮会供应商送到了目的地。}
