#{100}{}{You see Niskigvan Ruffled Feathers.}
{100}{}{你看尼斯基文的羽毛皱褶。}
#{101}{}{You see a tanned, middle-aged Native American with a stoned look in his eyes.}
{101}{}{你看到一个皮肤黝黑的中年美洲土著，眼神呆滞。}
#{110}{}{Now that was unnecessary... }
{110}{}{现在没必要了...}
#{111}{}{Sorry, maybe later... }
{111}{}{抱歉，也许以后...}
#{112}{}{Once upon a time, children, there was a little mouse.}
{112}{}{从前，孩子们，有一只小老鼠。}
#{113}{}{He was the youngest mouse out of all his brothers and sisters.}
{113}{}{他是他所有兄弟姐妹中最小的一只老鼠。}
#{114}{}{One day, he heard a noise he'd never heard before. "What was that noise?" he asked.}
{114}{}{有一天，他听到了一个从未听过的声音。”那是什么声音？”他问。}
#{115}{}{"What noise?" said the other mice. "Tend to your garden. There is no noise."}
{115}{}{“什么声音？”其他老鼠说照料你的花园。没有噪音。”}
#{116}{}{But this mouse was curious. He went on a journey find the noise.}
{116}{}{但是这只老鼠很好奇。他去旅行寻找噪音。}
#{117}{}{He met a frog. The frog said, "You hear the Great River flowing. I will take you there."}
{117}{}{他遇到一只青蛙。青蛙说：“你听见大河在流。我带你去。”}
#{118}{}{They traveled together to the Great River. When they got there, the frog said... }
{118}{}{他们一起去了那条大河。当他们到了那里，青蛙说...}
#{119}{}{"Jump as high as you can, and you'll see the Great Mountains!"}
{119}{}{“跳得越高越好，你就会看到大山！”}
#{120}{}{And so the mouse did. He jumped so high, he saw the Great Mountains! But they were very far away.}
{120}{}{老鼠也是这样做的。他跳得那么高，他看到了大山！但他们离得很远。}
#{121}{}{The mouse was curious about the mountains. He knew he couldn't rest until he saw them up close.}
{121}{}{老鼠对山很好奇。他知道他不能休息，直到他看到他们近距离。}
#{122}{}{So the mouse traveled through the Great Plains to get to the Great Mountains.}
{122}{}{所以老鼠穿过大平原来到了大山。}
#{123}{}{Suddenly, he saw a bison lying in the plains. He was strong and mighty.}
{123}{}{突然，他看见平原上躺着一头野牛。他强壮有力。}
#{124}{}{"Brother bison!" said the mouse. "Please take me to the Great Mountains!"}
{124}{}{“野牛兄弟！”老鼠说请带我去大山！”}
#{125}{}{"But I can't," said the bison. "I've died. Only the eye of a mouse can save me."}
{125}{}{“但是我不能，”野牛说我已经死了。只有老鼠的眼睛才能救我。”}
#{126}{}{"An eye?" the mouse asked. "Here, if it will save you, take mine!"}
{126}{}{“一只眼睛？”老鼠问道来，如果它能救你，就拿我的吧！”}
#{127}{}{The bison took the gift and came back to life. In gratitude, he took the mouse to the Great Mountains.}
{127}{}{野牛接受了礼物，复活了。出于感激，他把老鼠带到了大山上。}
#{128}{}{At the base of the Great Mountains, the mouse saw a wolf hiding in the bush. Still, silent, thinking.}
{128}{}{在大山脚下，老鼠看见一只狼躲在灌木丛里。静静地，沉默着，思考着。}
#{129}{}{"Brother wolf!" said the mouse. "Please help me climb the Great Mountains!" But the wolf didn't speak.}
{129}{}{“狼哥哥！”老鼠说请帮我爬大山！”但是狼没有说话。}
#{130}{}{The mouse knew the wolf had died, and so gave him his other eye.}
{130}{}{老鼠知道狼已经死了，于是给了他另一只眼睛。}
#{131}{}{And so the wolf came back to life. In gratitude, he took the mouse to the very heart of the Great Mountains.}
{131}{}{于是狼复活了。出于感激，他把老鼠带到了大山的中心。}
#{132}{}{Now the little mouse was all alone in the heart of Great Mountains, unable, even for a moment, to witness their beauty.}
{132}{}{现在，这只小老鼠独自一人在大山的中心，哪怕是一瞬间，也无法目睹它们的美丽。}
#{133}{}{Suddenly he saw, in blur... The soil... The water... But everything became so distant... }
{133}{}{突然他模糊地看到...土壤...水...但一切变得如此遥远...}
#{134}{}{And someone spoke to him. "Hello, brother, you have joined our flock. Fly with us. Fly with us, brother eagle!"}
{134}{}{有人跟他说话了。”你好，兄弟，你加入了我们的队伍。和我们一起飞。和我们一起飞吧，老鹰兄弟！”}
#{135}{}{Well, children? Did you like it? If you're good, I'll tell you another story later... }
{135}{}{好吧，孩子们？你喜欢吗？如果你很好，我以后再给你讲另一个故事...}
#{200}{}{What do you need, outsider?}
{200}{}{你需要什么，局外人？}
#{201}{}{I need healing.}
{201}{}{我需要治疗。}
#{202}{}{I need medication.}
{202}{}{我需要药物治疗。}
#{203}{}{Do you think your healing stuff actually work? Are you serious?}
{203}{}{你认为你的治疗方法有效吗？你是认真的吗？}
#{204}{}{Sorry, what are you doing?}
{204}{}{对不起，你在干什么？}
#{205}{}{I found your lost backpack.}
{205}{}{我找到了你丢失的背包。}
#{206}{}{Nothing.}
{206}{}{没有什么。}
#{207}{}{Do you know where the radio station is?}
{207}{}{你知道电台在哪里吗？}
#{250}{}{Let's see. [he examines you, mumbling to himself] Yes, yes... I can heal you.}
{250}{}{让我们看看。[他审视着你，喃喃自语]是的，是的...我可以治愈你。}
#{251}{}{Let's see. [he examines you, mumbling to himself] Yes, yes... I can heal you, but you'll have to pay me 100 of your dollars.}
{251}{}{让我们看看。[他审视着你，喃喃自语]是的，是的...我可以治好你，但你得付我100美元。}
#{252}{}{Heal me!}
{252}{}{治愈我！}
#{253}{}{Here's the money. Now heal me!}
{253}{}{这是钱。现在治愈我！}
#{254}{}{But I don't have that much money. Are you really just going to let me suffer?}
{254}{}{但我没有那么多钱。你真的要让我受苦吗？}
#{255}{}{Never mind, then. It'll heal on its own. In the meantime, I have other questions.}
{255}{}{那没关系。它会自己痊愈的。同时，我还有其他问题。}
#{256}{}{Actually, I don't need anything after all.}
{256}{}{其实，我什么都不需要。}
#{257}{}{I am the healer of my tribe. I should not have to say anything else.}
{257}{}{我是我部落的治疗者。我不该说别的。}
#{258}{}{I'm not asking, I'm ordering! Heal me, or else!}
{258}{}{我不是在问，我是在点菜！治愈我，否则！}
#{259}{}{Fine, here's the money! Just heal me!}
{259}{}{好吧，钱来了！只要治愈我！}
#{260}{}{[He smiles smugly] In the past, a raider came to torture me. Now a raider pleads for my mercy. It's funny, don't you think?}
{260}{}{[他得意地笑着]过去，一个袭击者来折磨我。现在一个袭击者恳求我的宽恕。很有趣，你不觉得吗？}
#{261}{}{Shut up and heal me!}
{261}{}{闭嘴，治愈我！}
#{262}{}{That's interesting. I'll go think about it.}
{262}{}{那很有趣。我去考虑一下。}
#{263}{}{You would harm my body to make me heal yours? [he shakes his head] Wisdom has made you foolish, outsider, if this is what your journeys have taught you.}
{263}{}{你想伤害我的身体让我治愈你的？外人哪，智慧使你愚昧，这是你行经所教训你的。}
#{264}{}{Fine, here's 100 bucks! Heal me already!}
{264}{}{好吧，这是100美元！已经治愈我了！}
#{265}{}{Fuck this. I'll deal with it on my own. Thanks for nothing.}
{265}{}{去他妈的。我自己来处理。什么都不用谢。}
#{266}{}{I did as much as I could.}
{266}{}{我已经尽力了。}
#{267}{}{In the past, a raider came to torture me. Now he asks for a favor. No, outsider. Seek help from your own people.}
{267}{}{过去，有个袭击者来折磨我。现在他请求帮忙。不，外人。向你自己的人寻求帮助。}
#{268}{}{I won't forget this, old man!}
{268}{}{我不会忘记的，老头！}
#{269}{}{Fine, I'll ask my people at the camp.}
{269}{}{好吧，我去问问营地的人。}
#{300}{}{We can't share what little we have, outsider. But I can mix medicine for you if you bring me the components.}
{300}{}{我们不能分享我们所拥有的，局外人。但是如果你把成分给我，我可以给你配药。}
#{301}{}{What do you need to make healing powder?}
{301}{}{你需要什么来做疗伤粉？}
#{302}{}{What do you need to make an antidote?}
{302}{}{你需要什么来做解药？}
#{303}{}{I have another question.}
{303}{}{我还有一个问题。}
#{304}{}{That's all.}
{304}{}{这就是全部。}
#{305}{}{Make one.}
{305}{}{做一个。}
#{306}{}{Make two.}
{306}{}{做两个。}
#{307}{}{Make three.}
{307}{}{做三个。}
#{308}{}{Make five.}
{308}{}{做五个。}
#{309}{}{Make ten.}
{309}{}{做十个。}
#{310}{}{Xander root, a broc flower, and 25 of your dollars.}
{310}{}{仙德根，一朵椰子花，还有你的25美元。}
#{311}{}{The tail of a radscorpion and 25 of your dollars.}
{311}{}{一只蝎子的尾巴和你的25美元。}
#{312}{}{Done.}
{312}{}{完成。}
#{313}{}{I have another question.}
{313}{}{我还有一个问题。}
#{314}{}{That's all.}
{314}{}{这就是全部。}
#{315}{}{Can you make medicine for an infection?}
{315}{}{你能做治疗感染的药吗？}
#{316}{}{[He raises his eyebrows] That's a complicated task, outsider. I'll need xander root, a broc flower, two bunches of nightshade berries and 250 of your dollars.}
{316}{}{[他扬起眉毛]这是一项复杂的任务，局外人。我需要香根，一朵椰子花，两束茄果和250美元。}
#{350}{}{I will never forget what you did for Makkon. No reward would be enough, but I'd be honored to teach you everything I know.}
{350}{}{我永远不会忘记你为Makkon所做的一切。没有报酬是不够的，但我很荣幸能教你我所知道的一切。}
#{351}{}{You've done so much for our tribe. I'd be honored to teach you everything I know. May it help you on your journey.}
{351}{}{你为我们部落做了这么多。我很荣幸能教你我所知道的一切。愿它对你的旅途有所帮助。}
#{352}{}{Can you teach me how to make herbal medicine?}
{352}{}{你能教我怎么做草药吗？}
#{353}{}{Of course. You won't need healers anymore. You'll know how to use the gifts of nature to heal yourself.}
{353}{}{当然。你不再需要治疗师了。你会知道如何利用大自然的恩赐来治愈自己。}
#{354}{}{Great! Teach me, oh great healer!}
{354}{}{太好了！教我，哦，伟大的治疗者！}
#{355}{}{I don't have time right now. Can we do it later?}
{355}{}{我现在没时间。我们可以晚点再做吗？}
#{356}{}{When you're ready, return here and I will teach you.}
{356}{}{等你准备好了，回来我教你。}
#{357}{}{Actually, I can find some time. Teach me, oh great healer!}
{357}{}{实际上，我可以找时间。教我，哦，伟大的治疗者！}
#{358}{}{I'll come back.}
{358}{}{我会回来的。}
#{360}{}{Radio?.. No, I do not know.}
{360}{}{收音机？。。不，我不知道。}
#{361}{}{You're lying! Show me where it is, now!}
{361}{}{你在撒谎！告诉我它在哪里，现在！}
#{362}{}{Another question, then.}
{362}{}{那么，另一个问题。}
#{363}{}{Fine, but I??ll come back.}
{363}{}{好吧，不过我会回来的。}
#{364}{}{You come into my home, a place of peace and healing and threaten me?! How dare you?!}
{364}{}{你闯进我的家，一个和平疗伤的地方，威胁我？！你怎么敢？！}
#{365}{}{Have it your way. I'll go through your villagers one by one until somebody shows me where it is. You'll have plenty of people giving your "place of healing" its proper respect then.}
{365}{}{随你的便。我会一个一个地检查你们的村民，直到有人告诉我它在哪里。你会有很多人给予你的“疗伤之地”应有的尊重。}
#{366}{}{Woah, woah, sorry. I just got a little excited. But don't you really know where the station is?}
{366}{}{哇，哇，对不起。我只是有点兴奋。但你真的不知道车站在哪里吗？}
#{367}{}{This is pointless. I'm leaving.}
{367}{}{这是毫无意义的。我要走了。}
#{368}{}{No.}
{368}{}{不。}
#{369}{}{Fine.}
{369}{}{好的。}
#{370}{}{No, wait! I'll show you the radio station. Just don't hurt anyone!}
{370}{}{不，等等！我带你去看广播电台。别伤害任何人！}
#{371}{}{Now we're talking! Get moving, old man.}
{371}{}{现在我们在说话！快走，老头。}
#{400}{}{Yes. The Ruler of Life gives us food and water. By living in harmony with our environment and being aware of the gifts we are given, we have everything we need to survive.}
{400}{}{对。生命的统治者给我们食物和水。通过与我们的环境和谐相处，意识到我们所得到的礼物，我们拥有了生存所需的一切。}
#{401}{}{You can't possibly treat advanced diseases and injuries with herbs and water.}
{401}{}{你不可能用草药和水治疗晚期疾病和伤害。}
#{402}{}{Couldn't you do more if you had better tools, though?}
{402}{}{如果你有更好的工具，你能做得更多吗？}
#{403}{}{I see. I want to ask something else.}
{403}{}{我懂了。我想问点别的。}
#{404}{}{That's all I wanted.}
{404}{}{这就是我想要的。}
#{405}{}{I don't expect a city person like you to understand. We, Cheyenne, have lived this way for many years, whether you choose to believe it or not.}
{405}{}{我不指望像你这样的城里人能理解。我们夏延人已经这样生活了很多年，不管你信不信。}
#{406}{}{Hmm. What gifts does nature provide, then?}
{406}{}{嗯。那么大自然提供了什么礼物呢？}
#{407}{}{What techniques do you use?}
{407}{}{你用什么技巧？}
#{408}{}{And does it work?}
{408}{}{它有用吗？}
#{409}{}{And how healthy are the Cheyenne?}
{409}{}{夏延人有多健康？}
#{410}{}{Why don't you use pre-war medicine?}
{410}{}{你为什么不用战前的药？}
#{411}{}{We use roots, herbs, mushrooms, and mice feces.}
{411}{}{我们用根、草药、蘑菇和老鼠的粪便。}
#{412}{}{What roots?}
{412}{}{什么根？}
#{413}{}{What kind of herbs?}
{413}{}{什么草药？}
#{414}{}{Mushrooms?}
{414}{}{蘑菇？}
#{415}{}{Mice feces?! You're kidding!}
{415}{}{老鼠的粪便？！你开玩笑吧！}
#{416}{}{How all of this can help with healing?}
{416}{}{所有这些是如何帮助康复的？}
#{417}{}{I have other questions.}
{417}{}{我还有其他问题。}
#{418}{}{Many roots, especially xander root, can be smoked, rubbed into the skin, or drunk as a tea.}
{418}{}{许多根，特别是香根，可以熏，揉进皮肤，或作为茶喝。}
#{419}{}{How do they help?}
{419}{}{他们有什么帮助？}
#{420}{}{What else do you use?}
{420}{}{你还用什么？}
#{421}{}{Our magical healing powder tastes bitter, but is poisonous to the evil spirits that take root in the body.}
{421}{}{我们神奇的疗伤粉味道苦涩，但对体内扎根的邪灵却是有毒的。}
#{422}{}{You mean it has antimicrobial properties? Okay, what about your other medicine?}
{422}{}{你是说它有抗菌作用？好吧，你的其他药呢？}
#{423}{}{I'll keep that in mind. What else do you use?}
{423}{}{我会记住的。你还用什么？}
#{424}{}{Broc flowers, and other plant life.}
{424}{}{花椰花等植物的生命。}
#{425}{}{Spicy upon the tongue, but miraculous taste of potion relieves the heat of the body and speeds its recovery.}
{425}{}{舌头上的辛辣，但神奇的药水味道缓解身体的热量，加快其恢复。}
#{426}{}{You mean they can break a fever? It sounds like they have antibiotic properties. What about your other medicine?}
{426}{}{你是说他们可以退烧？听起来它们有抗生素的特性。你的其他药呢？}
#{427}{}{Mushrooms, which hide from the eye of the seeker in the dark corners of the wasteland.}
{427}{}{蘑菇，在荒地的黑暗角落里躲避探索者的眼睛。}
#{428}{}{Mushroom's glow lights the path to healing, guiding the spirit through its trials, and thus relieving the body's suffering.}
{428}{}{蘑菇的光芒照亮了通往疗愈的道路，引导精神通过它的考验，从而减轻身体的痛苦。}
#{429}{}{It sounds like they have hallucinogenic and pain-relieving properties. Tell me about your other medicine.}
{429}{}{听起来它们有致幻和止痛的作用。告诉我你的其他药。}
#{430}{}{I don't kid about the Heavenly Mother's gifts, outsider. These mice feces contain the life energy of the Earth itself.}
{430}{}{我不嘲笑天母的天赋，局外人。这些老鼠的粪便含有地球本身的生命能量。}
#{431}{}{Not every mice feces can heal. Only those mice that live in caves and have never gone outside are blessed by the Heavenly Mother and can aid the body's healing process.}
{431}{}{不是每只老鼠的粪便都能愈合。只有那些生活在洞穴里，从未出过门的老鼠才能得到天母的祝福，并能帮助身体的愈合过程。}
#{432}{}{Hmm... It sounds like something connected to the mice's diet. Their feces probably contain minerals that boost the body's metabolism. Okay, what about your other medicine?}
{432}{}{Hmm...听起来好像和老鼠的饮食有关。他们的粪便可能含有促进身体新陈代谢的矿物质。好吧，你的其他药呢？}
#{433}{}{Only those gifted by the Heavenly Mother can make medicine from these components. Others are doomed to drink poison.}
{433}{}{只有天母恩赐的人才可以用这些成分制成药物。其他人注定要喝毒药。}
#{434}{}{Right. Tell me one more time about those components.}
{434}{}{正确的。再告诉我一次关于这些部件的情况。}
#{440}{}{The ritual of healing is never the same. Sometimes a tea of herbs and roots is all someone needs to recover. Other times I must fight for one's life with everything the Heavenly Mother has given me - pipes, spells, potions, and of course, the skill of my hands.}
{440}{}{治疗的仪式从来都不一样。有时，一杯草药和根茶是所有人需要恢复。其他时候，我必须用天母赐予我的一切——烟斗、符咒、药水，当然还有我的手艺，为自己的生命而战。}
#{441}{}{I see.}
{441}{}{我懂了。}
#{442}{}{All healing is a battle in its own way. That's why it is often a trial of pain and screaming... But with bravery and perseverance even the strongest evil spirits will leave the body.}
{442}{}{所有的治疗都是一场以自己的方式进行的战斗。这就是为什么它经常是痛苦和尖叫的考验...但只要有勇气和毅力，即使是最强大的恶魔也会离开身体。}
#{443}{}{Right.}
{443}{}{正确的。}
#{444}{}{We are strong, even in old age, while outsiders are wrecked and weakened by the spirits infesting them. The Cheyenne people will outlive all others in the wasteland.}
{444}{}{我们是强大的，即使在老年，而外人是破坏和削弱的精神侵扰他们。夏延人将比荒地上所有其他人活得都长。}
#{445}{}{Well, if you say so.}
{445}{}{好吧，如果你这么说的话。}
#{446}{}{Humanity had forgotten what the Heavenly Mother taught us. Pre-war medicine could chase away evil spirits, but did not strengthen the body, so those spirits were always replaced by others - often stronger.}
{446}{}{人类已经忘记了天母教给我们的东西。战前的医学可以驱除邪恶的灵魂，但并不能增强身体，所以那些灵魂总是被其他的灵魂所取代——通常更强。}
#{447}{}{I see.}
{447}{}{我懂了。}
#{448}{}{That's not true. There was a lot of medicine and treatments used before the war. Some of it could be useful to you.}
{448}{}{那不是真的。战前有很多药物和治疗方法。其中一些可能对你有用。}
#{449}{}{Outsiders' medicine has never helped us. Don't try to convince me on blind faith it will now.}
{449}{}{外人的药从来没有帮助过我们。别盲目地相信我，现在会的。}
#{450}{}{Hmm. If I knew more about pharmaceutics, maybe I could convince you. Maybe later.}
{450}{}{嗯。如果我对药剂学有更多的了解，也许我能说服你。也许以后吧。}
#{451}{}{I'm an expert in medical field. I could explain it to you, if you share your knowledges with me in return.}
{451}{}{我是医学领域的专家。我可以向你解释，如果你和我分享你的知识作为回报。}
#{452}{}{Hmm... [he regards you curiously] The Heavenly Mother always taught us to seek new knowledge.}
{452}{}{Hmm...[他好奇地看着你]天母总是教导我们去寻求新的知识。}
#{453}{}{So, let's make ourself comfortable?}
{453}{}{那么，让我们自己舒服点？}
#{454}{}{Of course. I'd be happy to share with you.}
{454}{}{当然。我很乐意和你分享。}
#{455}{}{Let's get started, then!}
{455}{}{那我们开始吧！}
#{456}{}{Not now.}
{456}{}{不是现在。}
#{457}{}{Exchanging medical techniques with Niskigvan has increased your first aid skill by 5%.}
{457}{}{与Niskigvan交换医疗技术可使您的急救技能提高5%。}
#{460}{}{[He grumbles under his breath] I have had to do without some of the Heavenly Mother's gifts recently. It is hard to work my craft with nothing but knives and spoons.}
{460}{}{[他低声抱怨]我最近不得不放弃一些天母的礼物。除了刀子和勺子，我的手艺很难做。}
#{461}{}{The fertile earth provides all we need, if we have the wisdom to see it.}
{461}{}{肥沃的土地提供了我们所需要的一切，如果我们有智慧看到它的话。}
#{462}{}{We have what we need. Thank you, again.}
{462}{}{我们有我们需要的。再次谢谢你。}
#{463}{}{What happened?}
{463}{}{怎么搞的？}
#{464}{}{That's sad to hear. Let's talk about something else.}
{464}{}{听到这个消息很难过。我们再谈点别的吧。}
#{465}{}{In that case, I'll let you concentrate on your work. Goodbye.}
{465}{}{那样的话，我就让你专心工作。再见。}
#{466}{}{You're welcome. Can you answer some more questions?}
{466}{}{不客气。你能再回答几个问题吗？}
#{467}{}{No problem. See you later.}
{467}{}{没问题。再见。}
#{468}{}{Right.}
{468}{}{正确的。}
#{469}{}{It's hard to collect herbs and roots without my backpack. All of my supplies were in there.}
{469}{}{没有我的背包很难采集草药和根。我所有的补给都在里面。}
#{470}{}{What happened to it?}
{470}{}{怎么了？}
#{471}{}{Let??s talk about something else.}
{471}{}{我们再谈点别的吧。}
#{472}{}{I won't make you dwell on it. I'll leave you alone.}
{472}{}{我不会让你细想的。我不打扰你了。}
#{473}{}{One of the raiders took it when I was away from the village. It will be a long time before we can spare the leather for a new one and it will take even longer to replace the tools I kept in it. Healing will be difficult for some time.}
{473}{}{我不在村里的时候，一个袭击者拿走了它。我们要花很长时间才能把皮革换成新的，换掉我放在里面的工具也要花更长的时间。治愈在一段时间内是困难的。}
#{474}{}{What if I get your backpack for you?}
{474}{}{如果我帮你拿背包呢？}
#{475}{}{[He looks at you with an unsure expression] These are dangerous men, outsider. To approach them is to risk death, unless you are one of them.}
{475}{}{[他用不确定的表情看着你]他们是危险的人，局外人。接近他们就是冒着死亡的危险，除非你是他们中的一员。}
#{476}{}{Don't worry about me. You'd be amazed how often I take deadly risks.}
{476}{}{别担心我。你会惊讶于我经常冒致命的风险。}
#{477}{}{Never mind, then.}
{477}{}{那没关系。}
#{478}{}{If you hope for a reward, I have hardly anything to give, and even less that would interest an outsider like yourself.}
{478}{}{如果你希望得到报酬，我几乎没有什么可以给的，更别提像你这样的局外人会感兴趣的了。}
#{479}{}{Well, I want to help anyway. Maybe it will change your view on outsiders.}
{479}{}{好吧，反正我也想帮忙。也许这会改变你对外人的看法。}
#{480}{}{I'm not a charity. Forget it.}
{480}{}{我不是慈善机构。算了吧。}
#{481}{}{Then I would be very gracious for your kindness.}
{481}{}{那我就非常感谢你的好意了。}
#{482}{}{Do you know where to look for that raider?}
{482}{}{你知道去哪儿找那个袭击者吗？}
#{483}{}{Okay, but I have more questions first.}
{483}{}{好吧，但我先有更多的问题。}
#{484}{}{I'll be back with your stuff.}
{484}{}{我会带着你的东西回来的。}
#{485}{}{The raiders hideout is not far from here, to the north. The one who took my backpack is named Diesel.}
{485}{}{袭击者的藏身处离这里不远，在北面。拿我背包的那个叫迪塞尔。}
#{486}{}{No doubt the Ruler of Life sent you! Thank you, outsider! Such generosity is rare in our times - rare and precious. For as long as you live, I will heal your injuries without payment.}
{486}{}{毫无疑问是生活的统治者派你来的！谢谢你，外人！这种慷慨在我们这个时代是罕见的——罕见而珍贵。只要你活着，我会无偿为你疗伤。}
#{487}{}{That's great, but all this generosity really works up an appetite... }
{487}{}{那太好了，但是这些慷慨真的让人胃口大开...}
#{488}{}{Aw, it was nothing. You're welcome.}
{488}{}{哦，没什么。不客气。}
#{490}{}{Of course! Wait here. I will bring you some sandwiches from Omakaki.}
{490}{}{当然！在这里等着。我会给你带来一些来自Omakaki的三明治。}
#{491}{}{[Wait.]}
{491}{}{[等等。]}
#{500}{}{The chief didn't allow me to treat Makkon!}
{500}{}{头儿不允许我治疗麦肯！}
#{501}{}{Ogima's word is final.}
{501}{}{奥吉玛的话是最后的。}
#{502}{}{Ogima's word is final. I will not act against him.}
{502}{}{奥吉玛的话是最后的。我不会对他采取行动。}
#{503}{}{But what do we do now?!}
{503}{}{但我们现在该怎么办？！}
#{504}{}{It is done, outsider. Forget it and go peacefully.}
{504}{}{就这样，局外人。算了吧，平静地走吧。}
#{505}{}{Are you serious?! Walk away, just like that?}
{505}{}{你是认真的吗？！就这样走开？}
#{506}{}{Fine, I will. But you will regret this!}
{506}{}{好吧，我会的。但你会后悔的！}
#{507}{}{[He leans forward, looking into your eyes] Is outsider's heart weights with grief, like my own?}
{507}{}{[他俯下身，看着你的眼睛]外人的心和我的一样充满悲伤吗？}
#{508}{}{Yes!}
{508}{}{对！}
#{509}{}{And he wants only to help, without asking anything in return?}
{509}{}{他只想帮忙，不要求任何回报？}
#{510}{}{Of course!}
{510}{}{当然！}
#{511}{}{[He sighs] The chief is right. There is too much darkness in your heart, outsider, to place Makkon's life in your hands.}
{511}{}{[他叹息]头儿说得对。局外人，你的内心有太多的黑暗，无法将Makkon的生命交给你。}
#{512}{}{[Leave.]}
{512}{}{[离开]}
#{513}{}{[He gives a very long, troubled sigh] Chief Ogima... Wise as he is, he is only a man, like myself. Sometimes, even he is wrong... And I know more of healing than him, don't I?}
{513}{}{[他发出一声长长的，不安的叹息]奥格玛酋长...尽管他很聪明，但他只是个男人，像我一样。有时候，即使他错了...我比他更懂得治疗，不是吗？}
#{514}{}{Exactly! What can I do to prove you can trust me?}
{514}{}{确切地！我能做些什么来证明你能信任我？}
#{515}{}{Too often outsiders claim to have skills they do not. Just last month, a man came from the east. He promised us rain, but could only show us the clouds.}
{515}{}{很多时候，局外人都声称自己拥有他们没有的技能。就在上个月，一个男人从东方来。他答应给我们下雨，但只能给我们看云彩。}
#{516}{}{You want to test my knowledge?}
{516}{}{你想测试我的知识吗？}
#{517}{}{Have you changed your mind about examining my healing skills?}
{517}{}{你改变主意去检查我的治疗技巧了吗？}
#{518}{}{Chief Ogima has forbade me to treat Makkon.}
{518}{}{奥吉马酋长禁止我治疗麦肯。}
#{550}{}{What happened to that boy in the corner?}
{550}{}{角落里的那个男孩怎么了？}
#{551}{}{Poor Makkon. His legs were crushed in a landslide. For a long time I've tried to save him, but his legs are in constant pain and he's fallen into a fever for three months. Even the Heavenly Mother's gifts cannot produce miracles. I won't give up on him, but feel that he will die soon. Everyone in the village grieves for him.}
{551}{}{可怜的麦肯。他的腿在山体滑坡中被压碎了。很长一段时间以来，我一直想救他，但他的腿一直在痛，而且他已经发烧三个月了。即使天母的恩赐也不能创造奇迹。我不会放弃他，但我觉得他很快就会死。村里每个人都为他悲伤。}
#{552}{}{If your, uh, mother isn't enough, maybe more advanced medicine can save him. Can I help?}
{552}{}{如果你的，呃，母亲还不够，也许更先进的药物可以救他。我能帮忙吗？}
#{553}{}{I hope that all works out. See you.}
{553}{}{我希望一切顺利。再见。}
#{554}{}{Hmm... [he frowns] Go talk to Ogima. I cannot make this decision. I am too close to this boy and I cannot allow my heart to think instead of my head.}
{554}{}{Hmm...[他皱眉]去和奥吉玛谈谈。我不能做这个决定。我离这个男孩太近了，我不能让我的心代替我的头去思考。}
#{555}{}{I'll talk to him. But first, another question.}
{555}{}{我会和他谈谈。但首先，另一个问题。}
#{556}{}{I'll go talk to him then.}
{556}{}{那我就去和他谈谈。}
#{557}{}{I'd like to help you with treating that injured boy. Your chief gave me permission.}
{557}{}{我想帮助你治疗那个受伤的男孩。你的头儿给了我许可。}
#{558}{}{You're serious? You want to help?! This is a rarity in our times. [he pauses, then his brow furrows] I would love to see you heal this boy, but if even my skill is not enough... Are you sure you can handle it?}
{558}{}{你说真的？你想帮忙吗？！这在我们这个时代是罕见的。[他停顿了一下，然后眉头皱了起来]我很想看到你治好这个男孩，但如果连我的技能都不够的话...你确定你能应付吗？}
#{559}{}{I??m sure.}
{559}{}{我肯定。}
#{560}{}{Then I would like to test your skills first. I have never seen you work before. Shall we begin?}
{560}{}{那我想先测试一下你的技术。我以前从没见过你工作。我们开始吧？}
#{561}{}{No problem. Let's get started.}
{561}{}{没问题。我们开始吧。}
#{562}{}{I??m a little tired right now. Maybe later?}
{562}{}{我现在有点累。以后再说吧？}
#{600}{}{We will test your skills, outsider. [he straightens his posture and peers keenly into your eyes] I will ask questions, and you will answer.}
{600}{}{我们会考验你的技能，局外人。[他摆正姿势，敏锐地注视着你的眼睛]我要问你问题，你要回答。}
#{601}{}{I'm ready.}
{601}{}{我准备好了。}
#{602}{}{[He pulls his robe aside to show a scar located to the left of, and slightly below, his navel] When I was shot here, what did the bullet hit?}
{602}{}{[他把长袍拉到一边，露出肚脐左侧略低于肚脐的伤疤]我在这里被枪击时，子弹击中了什么？}
#{603}{}{Your lungs.}
{603}{}{你的肺。}
#{604}{}{Your colon.}
{604}{}{你的结肠。}
#{605}{}{Your bladder.}
{605}{}{你的膀胱。}
#{606}{}{Your small intestine.}
{606}{}{你的小肠。}
#{607}{}{Your penis.}
{607}{}{你的阴茎。}
#{610}{}{Hmm. And why wasn't the injury lethal?}
{610}{}{嗯。为什么受伤不致命？}
#{611}{}{All of your bones remained intact.}
{611}{}{你所有的骨头都完好无损。}
#{612}{}{Your central nervous system remained intact.}
{612}{}{你的中枢神经系统完好无损。}
#{613}{}{Your belly contains a lot of water, which stopped the bullet.}
{613}{}{你的肚子里有很多水，这阻止了子弹。}
#{614}{}{The heat of the bullet cauterized the injury.}
{614}{}{子弹的热量烧灼了伤口。}
#{615}{}{It didn't hit any vital organs.}
{615}{}{它没有击中任何重要器官。}
#{620}{}{Hmm. And what does the small intestine do for the body?}
{620}{}{嗯。小肠对身体有什么作用？}
#{621}{}{It processes blood.}
{621}{}{它处理血液。}
#{622}{}{It holds urine.}
{622}{}{它能装尿液。}
#{623}{}{It holds feces.}
{623}{}{它有粪便。}
#{624}{}{It sucks the water out of food.}
{624}{}{它从食物中吸取水分。}
#{625}{}{It digests food.}
{625}{}{它能消化食物。}
#{630}{}{Hmm. And how long does it take for such an injury to heal?}
{630}{}{嗯。这种伤需要多长时间才能痊愈？}
#{631}{}{A few hours.}
{631}{}{几个小时。}
#{632}{}{A few days.}
{632}{}{几天。}
#{633}{}{A few weeks.}
{633}{}{几个星期。}
#{634}{}{A year.}
{634}{}{一年。}
#{640}{}{Hmm. How should we treat this injury, so that it is not infected with evil spirits?}
{640}{}{嗯。我们应该怎样治疗这个伤，使它不被邪灵感染？}
#{641}{}{Wash it out with water from the well.}
{641}{}{用井里的水把它洗干净。}
#{642}{}{Wash it out with alcohol, such as booze.}
{642}{}{用酒精洗掉，比如酒。}
#{643}{}{Sear it with fire or heated metal.}
{643}{}{用火或加热的金属把它烧焦。}
#{644}{}{Lick it.}
{644}{}{舔它。}
#{645}{}{Nothing, the heat of the bullet already cauterized the wound.}
{645}{}{没什么，子弹的热量已经烧灼了伤口。}
#{650}{}{Hmm. Some herbs help the body restore injured flesh quickly, but they all have a side effect. What is the side effect of powder made from xander root and broc flowers?}
{650}{}{嗯。有些草药能帮助身体迅速恢复受伤的肌肉，但它们都有副作用。仙人掌和椰子花制成的粉末有什么副作用？}
#{651}{}{It weakens your strength.}
{651}{}{它会削弱你的力量。}
#{652}{}{It reduces your endurance.}
{652}{}{它会降低你的耐力。}
#{653}{}{It clouds your perception.}
{653}{}{它模糊了你的感知。}
#{654}{}{It slows your agility.}
{654}{}{它会减缓你的敏捷性。}
#{655}{}{There is the risk of becoming addicted.}
{655}{}{有上瘾的危险。}
#{660}{}{Hmm. Some pre-war medicine is very addictive. If the addicted person doesn't get it regularly, they suffer. Can this addiction be treated?}
{660}{}{嗯。一些战前的药很容易上瘾。如果上瘾的人没有得到它定期，他们遭受痛苦。这种瘾能治好吗？}
#{661}{}{Yes. Go long enough without another dose and the addiction will eventually fade.}
{661}{}{对。如果不服用另一剂，持续足够长的时间，成瘾性最终会消失。}
#{662}{}{Yes. Another type of medicine can remove the addiction.}
{662}{}{对。另一种药可以戒除毒瘾。}
#{663}{}{Yes. Conducting a rite of purification with special smoke will remove the cravings.}
{663}{}{对。用特殊的烟雾进行净化仪式可以消除这种渴望。}
#{664}{}{No. The burden will last forever.}
{664}{}{不，这个负担将永远持续下去。}
#{665}{}{What now?}
{665}{}{现在怎么办？}
#{666}{}{[Continue.]}
{666}{}{[继续。]}
#{667}{}{That is all. [he smiles and his eyes glint with excitement] Your knowledge of healing is incredible, outsider! Perhaps, it's you, who should be testing me! Together, I think we have the wisdom to treat Makkon.}
{667}{}{仅此而已。[他微笑着，眼睛闪烁着兴奋的光芒]你的治疗知识真是难以置信，局外人！也许，是你，应该考验我！一起，我想我们有智慧去对待麦肯。}
#{668}{}{That is all. [he smiles] You know much of healing, outsider. I know I can trust you.}
{668}{}{仅此而已。[他微笑]你知道很多治疗的方法，局外人。我知道我可以相信你。}
#{669}{}{That is all. [he frowns] Makkon's condition is very complicated, outsider, and I don't think you have the knowledge to treat it correctly. But perhaps you have skills in other areas.}
{669}{}{仅此而已。[他皱眉]外人，Makkon的情况非常复杂，我认为你不知道如何正确对待它。但也许你在其他领域有技能。}
#{670}{}{[He throws up his hands] There's no point in continuing this. You don't know anything! How can you call yourself a healer? I can't risk you treating Makkon. I... I forbid it!}
{670}{}{[他举手]继续这样下去没有意义。你什么都不知道！你怎么能称自己为治疗者？我不能冒险让你去治疗麦肯。一、 ...我禁止！}
#{671}{}{[He crosses his arms] Experience has told me that knowledge is not enough. Omakaki was my helper once, and while she learned much of herbs, roots, and plants, she could not make a simple potion. Show me your skills on this dummy, so I may see them in practice.}
{671}{}{经验告诉我，知识是不够的。奥玛卡基曾经是我的帮手，虽然她学会了很多草药、根和植物，但她不能做一种简单的药水。让我看看你在这个假人上的技能，这样我就可以在练习中看到它们了。}
#{672}{}{Sometimes, the Ruler of Life deprives a person's skills in one area, but grants them something else in exchange. Gekek had a brother who could not tell the difference between an iguana and a gecko, but could throw a spear through its eye from fifty paces. Show me your skills on this dummy, so I may see them in practice.}
{672}{}{有时，生活的统治者剥夺了一个人在某一方面的技能，却给予了他们其他的东西作为交换。盖克有一个哥哥，他不能分辨鬣蜥和壁虎的区别，但能从五十步远的地方用长矛刺穿它的眼睛。让我看看你在这个假人上的技能，这样我就可以在练习中看到它们了。}
#{673}{}{Niskigvan analyzed your medical skills by watching you work on the dummy.}
{673}{}{Niskigvan通过观察你在假人上的工作来分析你的医疗技能。}
#{674}{}{Now, I will know the swiftness of your hands. You must have skillful fingers to work with soft or damaged flesh. Here is a gecko skin and needle. Drive the needle through the dots I have left for you.}
{674}{}{现在，我将知道你的手的敏捷。你必须有熟练的手指来处理柔软或受损的皮肤。这是壁虎皮和针。把针穿过我留给你的小点。}
#{675}{}{[Niskigvan carefully appraises the speed, accuracy, caution, and confidence of your needlework] Hmm. Now, I will know the sharpness of your eyes. Here are two glasses of water. In one, you have water from the well, and in the other, carefully purified water. Tell me which is the purer water.}
{675}{}{[尼斯基文仔细评价了你针线活的速度、准确性、谨慎和自信]嗯。现在，我就知道你眼睛的锐利了。这儿有两杯水。一种是井水，另一种是经过仔细净化的水。告诉我哪种水更纯净。}
#{676}{}{[Choose.]}
{676}{}{[选择]}
#{677}{}{Hmm. Now, I will know the stamina of your heart. The operation may take several hours, and it will be exhausting work. Do some sit-ups, and then, I will listen to the speed of your heart.}
{677}{}{嗯。现在，我就知道你心脏的耐力了。手术可能需要几个小时，这将是一项累人的工作。做一些仰卧起坐，然后，我会听你心跳的速度。}
#{678}{}{Fine, let's do this. [begin sit-ups]}
{678}{}{好吧，我们开始吧。[开始仰卧起坐]}
#{679}{}{[After a few minutes, Niskigvan grabs your wrist and measures your heart rate] Hmm... You are remarkably fit and talented, outsider! You make the old man jealous!}
{679}{}{[几分钟后，尼斯基文抓住你的手腕，测量你的心率]嗯...外人，你身体健康，才华横溢！你让老人嫉妒！}
#{680}{}{[After a few minutes, Niskigvan grabs your wrist and measures your heart rate] Hmm... Yes, this should be enough. You are strong and skilled enough for this surgery, outsider.}
{680}{}{[几分钟后，尼斯基文抓住你的手腕，测量你的心率]嗯...是的，这应该足够了。外人，你足够强壮和熟练来做这个手术。}
#{681}{}{[After a few minutes, Niskigvan grabs your wrist and measures your heart rate] Hmm... I am not sure you have the strength for this operation, outsider. I had hoped for more from someone so much younger than me. But with both of us there, perhaps it will be enough.}
{681}{}{[几分钟后，尼斯基文抓住你的手腕，测量你的心率]嗯...外人，我不确定你是否有能力做这个手术。我对一个比我年轻得多的人寄予了更多的希望。但我们两个都在，也许就够了。}
#{682}{}{[After a few minutes, Niskigvan shakes his head] Stop, stop. Your kind spirit cannot make up for the weakness of your body, outsider. If I let you perform this surgery, you'll kill the boy, and maybe yourself! I'm sorry, but... I must forbid you from treating Makkon.}
{682}{}{[几分钟后，尼斯基文摇了摇头]停，停。你善良的精神无法弥补你身体的弱点，局外人。如果我让你做这个手术，你会杀了那个男孩，也许还会杀了你自己！对不起，但是...我必须禁止你治疗麦肯。}
#{683}{}{Finally, the last test. I have here a pet mouse. She is very sensitive and can easily determine the difference between filthy and pure. I will place some seed in your hands, and we will see if she eats it.}
{683}{}{最后，最后一个测试。我这里有一只宠物老鼠。她很敏感，很容易分辨污秽和纯洁。我要把种子放在你手里，看她吃不吃。}
#{684}{}{[The mouse runs from you without even trying to eat the food in your hands] Hmm... I think there are evil spirits within you. Poison, sickness, or even something darker. Anyway, I'm ready to make my decision.}
{684}{}{[老鼠从你身边跑开，连你手里的食物都没吃]嗯...我认为你内心有邪恶的灵魂。毒药，疾病，甚至更黑暗的东西。不管怎样，我已经准备好做决定了。}
#{685}{}{[The mouse cautiously sniffs at the seed in your hands, then starts to eat] An animal cannot be tricked! I'm ready to make my decision!}
{685}{}{[老鼠小心翼翼地嗅了嗅你手中的种子，然后开始吃]动物是不会被欺骗的！我准备好做决定了！}
#{686}{}{I had no idea the Heavenly Mother granted such blessings to the people of the city! I will be honored to assist you during the operation.}
{686}{}{我不知道天母给了城里人这样的祝福！我很荣幸能在手术期间协助你。}
#{687}{}{You did well, outsider! I have no doubts now. Together, we should be able to heal Makkon.}
{687}{}{你做得很好，局外人！我现在不怀疑了。一起，我们就能治愈麦肯。}
#{688}{}{I believe I can trust you, outsider. You will be able to assist me in the operation.}
{688}{}{我相信我能信任你，局外人。你可以帮我做手术。}
#{689}{}{You are a great healer, outsider! I will be honored to have your help during the operation! But you should be careful - animals know things that we people do not. If there are evil spirits within you, do not allow them to grow too strong, or it will end badly for you.}
{689}{}{你是一个伟大的治疗者，局外人！在手术过程中能得到你的帮助我将不胜荣幸！但是你应该小心——动物知道我们人类不知道的事情。如果你内心有邪恶的灵魂，不要让它们变得太强大，否则它会给你带来不好的结局。}
#{690}{}{You did well, outsider. It is a shame that the mouse smelled uncleanliness on your hands, but I still think you can handle the operation.}
{690}{}{你做得很好，局外人。很遗憾，你手上的老鼠闻起来不干净，但我仍然认为你能处理好这个手术。}
#{691}{}{I had reasons to trust you, outsider, but animals know things that we people do not. I do not know what my mouse feared in you, but I cannot allow you to treat Makkon. I... Forbid it.}
{691}{}{我有理由相信你，局外人，但动物知道我们人类不知道的事情。我不知道我的老鼠在你身上害怕什么，但我不能允许你对待麦肯。一、 ...禁止它。}
#{692}{}{Anything else?}
{692}{}{还有别的吗？}
#{693}{}{Remember that time will not wait for you, outsider. A few more months without treatment, and the boy will die. Rest for now, and when you're ready to discuss the operation, come to me.}
{693}{}{记住，时间不会等你，局外人。再过几个月不治疗，孩子就会死。现在休息一下，等你准备好讨论手术的时候，来找我。}
#{694}{}{That??s it! I??m leaving.}
{694}{}{就这样！我要走了。}
#{695}{}{[Exit.]}
{695}{}{[退出。]}
#{696}{}{For passing the test with flying colors, you earn }
{696}{}{以优异成绩通过考试，你将获得}
#{697}{}{For your great performance on the test, you earn }
{697}{}{因为你在考试中的出色表现，你赢得了}
#{698}{}{For passing the test, you earn }
{698}{}{通过考试，你就赚了}
#{699}{}{ experience points.}
{699}{}{经验点。}
#{700}{}{Let's discuss Makkon's operation.}
{700}{}{我们来讨论一下Makkon的行动。}
#{701}{}{[He sighs] The time has come. What should we do?}
{701}{}{时间到了。我们该怎么办？}
#{702}{}{First, we'll have to drain the pus and reduce the inflammation. We'll have to make him bleed and clean the injury.}
{702}{}{首先，我们得排脓，减轻炎症。我们得让他流血并清理伤口。}
#{703}{}{[He nods] Yes, yes... We need clean water and a sharp knife. But how will he endure it? He is so young... }
{703}{}{[他点头]是的，是的...我们需要干净的水和锋利的刀。但他怎么能忍受呢？他太年轻了...}
#{704}{}{Yes, the boy needs anesthesia. Pre-war chems would be best, but if you don't trust them, we can give him alcohol or herbs.}
{704}{}{是的，这孩子需要麻醉。战前化学是最好的，但如果你不信任他们，我们可以给他酒精或草药。}
#{705}{}{Yes... My healing powder can give him respite in the world of dreams. But you bring your chems, too. When the time comes, we'll decide what is best. What else?}
{705}{}{对...我的治疗粉能让他在梦境中得到喘息。但你也带着化学药品。到时候，我们会决定什么是最好的。还有什么？}
#{706}{}{We'll need strong hands to set his broken bones, and forceps or pliers to remove any bone fragments under the skin.}
{706}{}{我们需要强壮的手来固定他的骨折，需要镊子或钳子来移除皮肤下的骨头碎片。}
#{707}{}{Yes, that's right. And after that?}
{707}{}{是的，没错。那之后呢？}
#{708}{}{We'll have to stitch and bandage his injuries and splint his broken bones.}
{708}{}{我们得给他缝合绷带，用夹板固定骨折。}
#{709}{}{Bandages? In the cities, they are stored in boxes marked with a red cross. You will probably know better than me where to get them.}
{709}{}{绷带？在城市里，它们被存放在标有红十字的盒子里。你可能比我更清楚去哪儿买。}
#{710}{}{Yes, in first aid kits. But after the operation is complete, the boy will need constant care and lot of bed rest. He'll need medication to deal with his fever and something to stimulate the growth of cells.}
{710}{}{是的，在急救箱里。但手术完成后，男孩需要不断的护理和大量的卧床休息。他需要治疗发烧的药物和刺激细胞生长的药物。}
#{711}{}{Yes, I will prepare healing powder from xander root and broc flowers. It will speed his recovery.}
{711}{}{是的，我会用仙人掌和椰子花准备治疗粉。这会加速他的康复。}
#{712}{}{I can also bring stimpaks. Don't worry, they're harmless. A stimpak contains natural components, but heals much more effective, than healing powder}
{712}{}{我也可以带点兴奋剂。别担心，它们是无害的。stimpak含有天然成分，但比治疗粉更有效}
#{713}{}{Good, I will leave that to you.}
{713}{}{很好，我把这个交给你了。}
#{714}{}{Remind me, what's the full list of things we need?}
{714}{}{提醒我，我们需要的东西有哪些？}
#{715}{}{We need 1) clean water; 2) healing powder, painkillers, or alcohol; 3) a sharp knife; 4) forceps or pliers; 5) a first aid kit; and 6) healing powder or stimpaks.}
{715}{}{我们需要1）干净的水；2）治疗粉、止痛药或酒精；3）尖刀；4）钳子或钳子；5）急救箱；以及6）治疗粉或止痛药。}
#{716}{}{When you have everything, come back here.}
{716}{}{当你拥有一切，回到这里。}
#{717}{}{I'll be back.}
{717}{}{我会回来的。}
#{718}{}{About Makkon - what do we need?}
{718}{}{关于Makkon-我们需要什么？}
#{719}{}{Don??t forget anything. We need: }
{719}{}{别忘了什么。我们需要：}
#{720}{}{Right.}
{720}{}{正确的。}
#{800}{}{I'm ready to perform the operation on Makkon.}
{800}{}{我已经准备好给麦肯做手术了。}
#{801}{}{[He takes a deep breath, then nods] It is time. You have a sharp knife?}
{801}{}{[他深吸了一口气，然后点了点头]是时候了。你有一把锋利的刀吗？}
#{802}{}{Right here.}
{802}{}{就在这里。}
#{803}{}{Er... No.}
{803}{}{呃...不。}
#{804}{}{How will we do this without a knife? What were you thinking? You can't be so careless with Makkon's life!}
{804}{}{没有刀我们怎么办？你在想什么？你不能对Makkon的生活这么粗心！}
#{805}{}{Good. Then we shall begin.}
{805}{}{很好。那我们就开始吧。}
#{806}{}{[Begin.]}
{806}{}{[开始]}
#{807}{}{No, wait, I forgot something. I'll be right back.}
{807}{}{不，等等，我忘了什么。我马上回来。}
#{808}{}{[Niskigvan's hands shake slightly, but he looks determined] We must make sure Makkon does not awake during the operation. What will we use?}
{808}{}{[尼斯基文的手微微颤抖，但他看起来很坚定]我们必须确保马克孔在手术中没有醒来。我们用什么？}
#{809}{}{Let's use your healing powder.}
{809}{}{让我们用你的治疗粉。}
#{810}{}{I have painkillers in this doctor's bag.}
{810}{}{医生的包里有止痛药。}
#{811}{}{I have painkillers in this first aid kit.}
{811}{}{我的急救箱里有止痛药。}
#{812}{}{But what if they're dangerous? Where were they kept? What if they've spoiled?}
{812}{}{但如果他们很危险呢？他们被关在哪里？如果他们被宠坏了呢？}
#{813}{}{Fine, use your traditional medicine.}
{813}{}{好吧，用你的传统药物。}
#{814}{}{These painkillers don't expire and have no side effect. Read the bottle, it's a clean product! Besides, i've used such ones myself.}
{814}{}{这些止痛药不会过期，也没有副作用。看这个瓶子，它是一个干净的产品！另外，我自己也用过。}
#{815}{}{Good. See, the boy's eyes are already closing... He is in the world of dreams now, and don't feel pain. Let's prepare his wounds. [Niskigvan's hands tremble as he removes the bandages from Makkon's feet, but his movements are confident] What will we use to prevent infection? Those spirits are very cunning... }
{815}{}{很好。看，男孩的眼睛已经闭上了...他现在在梦的世界里，不感到痛苦。让我们给他准备伤口。[尼斯基文的手颤抖着，他把绷带从Makkon的脚上取下来，但他的动作很自信]我们将用什么来防止感染？那些鬼魂很狡猾...}
#{816}{}{Clean water.}
{816}{}{干净的水。}
#{817}{}{The bottle of booze. The alcohol will sterilize his wounds.}
{817}{}{那瓶酒。酒精可以消毒他的伤口。}
#{818}{}{I have some rotgut here. The alcohol will sterilize his wounds.}
{818}{}{我这里有一些罗古特。酒精可以消毒他的伤口。}
#{819}{}{We'll have to risk using well water.}
{819}{}{我们将不得不冒险使用井水。}
#{820}{}{No! [he shakes his head, frowning] I will prepare the water. I have a herbal infusion that will clean it.}
{820}{}{不！[他摇摇头，皱眉]我来准备水。我有一种草药可以清洗它。}
#{821}{}{What's next?}
{821}{}{下一步是什么？}
#{822}{}{Everything is ready. It's time to take care of his bones. Where's the knife? It should also be sterilized. Did you get pliers, or something like?}
{822}{}{一切都准备好了。是时候照顾他的骨头了。刀在哪里？它也应该消毒。你有钳子之类的东西吗？}
#{823}{}{Use these thin pliers. They'll be perfect.}
{823}{}{用这把细钳子。他们会很完美的。}
#{824}{}{No, sorry.}
{824}{}{不，对不起。}
#{825}{}{These too must be cleaned... There. Hold his legs here, while I remove the loose fragments... }
{825}{}{这些也必须清理...在那里。把他的腿放在这里，我把散落的碎片移走...}
#{826}{}{Hmm. That is not good. Fortunately I have some pre-war tweezers here. A poor tool for such a delicate operation, but there is nothing else. Hold his legs while I remove the fragments... }
{826}{}{嗯。那可不好。幸好我这里有一些战前的镊子。对于这样一个精细的操作来说，这是一个糟糕的工具，但没有别的了。抓住他的腿，我把碎片移走...}
#{827}{}{[You spend half an hour treating Makkon's wounds and removing small bone fragments from his legs]}
{827}{}{[你花了半个小时治疗Makkon的伤口，从他腿上取出小块骨头]}
#{828}{}{We must wash out the pus. We'll have to open the wounds. [You gently drain the pus from Makkon's injured flesh]}
{828}{}{我们必须把脓洗掉。我们得打开伤口。[你轻轻地吸干Makkon受伤的肌肉中的脓液]}
#{829}{}{We must wash out the pus. We'll have to open the wounds. Why are you standing around? We cannot afford to lose any time! Hold his legs while I release the pus.}
{829}{}{我们必须把脓洗掉。我们得打开伤口。你为什么站在这儿？我们不能浪费时间！我放脓的时候抓住他的腿。}
#{830}{}{The tissue is clean. There is no turning back now. Now we need to set the bones. [he takes a deep breath] If we damage the tissue, he will be as bad as when we started. Let us begin.}
{830}{}{纸巾是干净的。现在没有回头路了。现在我们需要固定骨头。[他深呼吸]如果我们破坏了组织，他会和我们开始时一样糟糕。让我们开始吧。}
#{831}{}{[You clean the wounds] Now we must stitch the wounds shut, or at least, bandage them tightly.}
{831}{}{[你清理伤口]现在我们必须缝合伤口，或者至少用绷带紧紧包扎。}
#{832}{}{I have gauze and bandages in this doctor's bag.}
{832}{}{医生的包里有纱布和绷带。}
#{833}{}{I have gauze and bandages in this first aid kit.}
{833}{}{我的急救箱里有纱布和绷带。}
#{834}{}{I have nothing like that. Maybe we can use a gecko skin?}
{834}{}{我没有那样的东西。也许我们可以用壁虎皮？}
#{835}{}{[Niskigvan blinks rapidly as sweat runs into his eyes] Now we have to put a splint. I have wooden poles and some cloth to tie them. [You and Niskigvan carefully splint Makkon's injured legs. Makkon slowly starts to come around, moaning softly.] Quiet, Bear Cub. Stay strong. We are almost done.}
{835}{}{[尼斯基文眨了眨眼，汗水流进了他的眼睛]现在我们必须用夹板。我有木杆和一些布来系。[你和Niskigvan小心地用夹板夹住Makkon受伤的腿。麦肯慢慢地转过身来，轻轻地呻吟着。]安静，小熊。保持强壮。我们差不多完成了。}
#{836}{}{[Finally, you tie the last bandage. Niskigvan stands, his hands shaking with fatigue.] The operation is complete. Makkon's body must heal. We must decide how to rehabilitate him.}
{836}{}{[最后，你系上最后一条绷带。尼斯基文站在那里，双手因疲劳而颤抖。Makkon的身体必须痊愈。我们必须决定如何为他平反。}
#{837}{}{Bed rest and plenty of food. He'll need to devote all of his strength to healing.}
{837}{}{卧床休息和充足的食物。他需要把所有的精力都用在治疗上。}
#{838}{}{He'll need to be treated with healing powder tomorrow to speed his recovery.}
{838}{}{他明天需要用疗伤粉治疗，以加速他的康复。}
#{839}{}{Here's a stimpak. It makes cells grow faster. Inject it into his leg tomorrow .}
{839}{}{这是一个stimpak。它使细胞生长得更快。明天注射到他的腿上。}
#{840}{}{Here's two stimpaks. Inject one into each leg tomorrow. It will prompt cell growth and speed the recovery process.}
{840}{}{这是两个Stimpak。明天每条腿注射一支。它会促进细胞生长，加速恢复过程。}
#{841}{}{[The healer's face is pale and slick with sweat. He washes his hands and steps outside for some fresh air.]}
{841}{}{[医者脸色苍白，汗流浃背。他洗手，走出去呼吸新鲜空气}
#{842}{}{[Go get some fresh air too.]}
{842}{}{[去呼吸点新鲜空气]}
#{843}{}{I feel sick... }
{843}{}{我觉得恶心...}
#{844}{}{I have an old painkiller.}
{844}{}{我有一个旧的止痛药。}
#{860}{}{I have a switchblade.}
{860}{}{我有个开关刀。}
#{861}{}{I have an old kitchen knife.}
{861}{}{我有一把旧菜刀。}
#{862}{}{I have a throwing knife.}
{862}{}{我有一把飞刀。}
#{863}{}{I have a sharp combat knife.}
{863}{}{我有一把锋利的战斗刀。}
#{864}{}{I have a straight razor.}
{864}{}{我有一把直剃刀。}
#{865}{}{Knives for surgery? Barbaric! Use this scalpel. It's designed specifically for this purpose.}
{865}{}{手术刀？野蛮！用这个手术刀。它是专门为这个目的设计的。}
#{850}{}{You earn 1000 experience points for assisting Niskigvan as he treated Makkon's crippling injuries. You and Niskigvan both learned something new.}
{850}{}{协助Niskigvan治疗Makkon的残废伤可获得1000点经验值。你和尼斯基文都学到了新东西。}
#{851}{}{You earn 2000 experience points for helping Niskigvan treat Makkon's crippling injuries. You and Niskigvan both learned something new.}
{851}{}{帮助Niskigvan治疗Makkon的残废伤可获得2000点经验点。你和尼斯基文都学到了新东西。}
#{852}{}{You earn 3000 experience points for treating Makkon's crippling injuries. You and Niskigvan both learned something new.}
{852}{}{治疗Makkon的残废伤可获得3000点经验值。你和尼斯基文都学到了新东西。}
#{853}{}{You earn 5000 experience points for your miraculous healing. You and Niskigvan both learned something new.}
{853}{}{你获得5000点经验值来获得奇迹般的治疗。你和尼斯基文都学到了新东西。}
#########################################################
#
#          玉蜞疱怿? 鬣耱?滂嚯钽?(not used, old version)
#
#########################################################

{2146}{}{}
{2149}{}{}
{2178}{}{}
{2179}{}{}
{2180}{}{}
{2181}{}{}
{2182}{}{}
{2183}{}{}
{2184}{}{}
{2185}{}{}
{2186}{}{}

#########################################################
#
#             Female character
#
#########################################################
#{1205}{}{I found your lost backpack.}
{1205}{}{我找到了你丢失的背包。}
#{1300}{}{We can't share what little we have, outsider. But I can mix medicine for you if you bring me the components.}
{1300}{}{我们不能分享我们所拥有的，局外人。但是如果你把成分给我，我可以给你配药。}
#{1366}{}{Woah, woah, sorry. I just got a little excited. But you really don't know where the station is?}
{1366}{}{哇，哇，对不起。我只是有点兴奋。但你真的不知道车站在哪里？}
#{1370}{}{No, wait! I'll show you the radio station. Just don't hurt anyone!}
{1370}{}{不，等等！我带你去看广播电台。别伤害任何人！}
#{1450}{}{Hmm. If I knew more about medicine, maybe I could convince you. Maybe later.}
{1450}{}{嗯。如果我对医学有更多的了解，也许我能说服你。也许以后吧。}
#{1451}{}{You won't need blind faith. I'm an expert in medicine. I could explain it to you.}
{1451}{}{你不需要盲目的信仰。我是医学专家。我可以解释给你听。}
#{1480}{}{I'm not a charity. Forget it.}
{1480}{}{我不是慈善机构。算了吧。}
#{1486}{}{No doubt the Ruler of Life sent you! Thank you, outsider! Such generosity is rare in our times - rare and precious. For as long as you live, I will heal your injuries without payment.}
{1486}{}{毫无疑问是生活的统治者派你来的！谢谢你，外人！这种慷慨在我们这个时代是罕见的——罕见而珍贵。只要你活着，我会无偿为你疗伤。}
#{1504}{}{It is done, outsider. Forget it and go peacefully.}
{1504}{}{就这样，局外人。算了吧，平静地走吧。}
#{1507}{}{[He leans forward, looking into your eyes] The outsider's heart is heavy with grief, like my own?}
{1507}{}{[他俯下身，看着你的眼睛]外人的心是沉重的悲伤，像我自己的？}
#{1509}{}{And she wants only to help, without asking anything in return?}
{1509}{}{她只想帮忙，不要求任何回报？}
#{1557}{}{I'd like to help that injured boy. Your chief gave me permission.}
{1557}{}{我想帮助那个受伤的男孩。你的头儿给了我许可。}
#{1559}{}{I??m sure.}
{1559}{}{我肯定。}
#{1562}{}{I??m a little tired right now. Maybe later?}
{1562}{}{我现在有点累。以后再说吧？}
#{1704}{}{Yes, the boy needs anesthesia. Pre-war chems would be best, but if you don't trust them, we can give him alcohol or herbs.}
{1704}{}{是的，这孩子需要麻醉。战前化学是最好的，但如果你不信任他们，我们可以给他酒精或草药。}
#{1800}{}{I'm ready to perform the operation on Makkon.}
{1800}{}{我已经准备好给麦肯做手术了。}
#{1802}{}{Right here.}
{1802}{}{就在这里。}
#{1804}{}{How will we do this without a knife? What were you thinking? You can't be so careless with Makkon's life!}
{1804}{}{没有刀我们怎么办？你在想什么？你不能对Makkon的生活这么粗心！}
#{1807}{}{No, wait, I forgot something. I'll be right back.}
{1807}{}{不，等等，我忘了什么。我马上回来。}
