#{100}{}{You see a lookout.}
{100}{}{你看到了望台了。}
#{101}{}{You see a raider on patrol.}
{101}{}{你看到一个正在巡逻的袭击者。}
#{110}{}{Stop right there!}
{110}{}{站住！}
#{111}{}{You move, you die!}
{111}{}{你动就死！}
#{112}{}{Hold it, punk!}
{112}{}{别动，朋克！}
#{113}{}{Don't move!}
{113}{}{别动！}
#{114}{}{I said don't move!}
{114}{}{我说了别动！}
#{115}{}{You're not getting away!}
{115}{}{你逃不了！}
#{116}{}{You're mine!}
{116}{}{你是我的！}
#{120}{}{The lookout saw you, but didn't see through your disguise.}
{120}{}{了望员看见了你，但没看穿你的伪装。}
#{121}{}{Hey, Mold, is that you?}
{121}{}{嘿，莫德，是你吗？}
#{122}{}{Hey, wait a minute! Who the hell? Oh, it's just you.}
{122}{}{嘿，等等！到底是谁？哦，只有你。}
#{123}{}{Hey, you in the jacket! Who are you?}
{123}{}{嘿，你穿夹克了！你是谁？}
#{124}{}{Who is that? Mold, is that you?}
{124}{}{那是谁？莫德，是你吗？}
#{125}{}{Out to puke again, huh, Mold? You gotta pull it together, man.}
{125}{}{又吐了，嗯，霉？你得振作起来，伙计。}
#{150}{}{Freeze! You move, you die!}
{150}{}{别动！你动就死！}
#{151}{}{Hey, hey! Easy! I'm not moving, see?}
{151}{}{嘿，嘿！容易的！我不动了，明白吗？}
#{152}{}{If you put your hands on me, you won't get them back.}
{152}{}{如果你把手放在我身上，你就拿不回来了。}
#{153}{}{And I thought this would be boring. Let's see what the boss says about you...}
{153}{}{我觉得这会很无聊。让我们看看老板怎么说你...}
#{154}{}{Fine, bring me to your boss. I won't fight.}
{154}{}{好吧，带我去见你老板。我不会打架的。}
#{155}{}{[Attack the raider.]}
{155}{}{[攻击袭击者。]}
#{156}{}{Shut up! You try anything, and there won't be enough of you left to bury.}
{156}{}{闭嘴！你什么都试过了，剩下的人就不够了。}
#{157}{}{Fine, I won't move.}
{157}{}{好吧，我不动了。}
#{158}{}{No, YOU shut up!}
{158}{}{不，你闭嘴！}
#{159}{}{}
{159}{}{}
#{160}{}{Great.}
{160}{}{伟大的。}
#{161}{}{Did you know there's a body in those ruins across from the base?}
{161}{}{你知道基地对面的废墟里有一具尸体吗？}
#{162}{}{See you around.}
{162}{}{回头见。}
#{163}{}{Yeah, that's Mold. He OD'd, so we threw him out before he started to smell. Weirdest thing is, we can't figure out where he got the shit. Fatso swears he cut him off.}
{163}{}{是的，那是霉菌。他喝多了，所以在他闻到气味之前我们把他赶了出去。最奇怪的是，我们不知道他从哪儿弄来的。胖子发誓要把他砍掉。}
#{164}{}{I see...}
{164}{}{我懂了...}
#{200}{}{Hey, you!}
{200}{}{嘿，你！}
#{201}{}{Waste this bitch!}
{201}{}{浪费这个婊子！}
#{202}{}{I'm gonna fuck you up!}
{202}{}{我要把你搞砸！}
#{203}{}{Do you wanna be gutted or flayed?!}
{203}{}{你想被掏空还是剥皮？！}
#{204}{}{Let's dance, baby!}
{204}{}{我们跳舞吧，宝贝！}
#{205}{}{Time to make you cry.}
{205}{}{是时候让你哭了。}
#{206}{}{Hold still while I gut you, will ya?}
{206}{}{别动，我把你挖出来，好吗？}
#{207}{}{Nobody...}
{207}{}{没有人...}
#{208}{}{This is boring.}
{208}{}{这太无聊了。}
#{209}{}{I'm so sick of walking in circles...}
{209}{}{我厌倦了绕圈子...}
#{210}{}{Will this patrol ever end?}
{210}{}{这次巡逻会结束吗？}
#{211}{}{Why am I even doing this?}
{211}{}{我为什么要这么做？}
#{212}{}{Great.}
{212}{}{伟大的。}
#{213}{}{All's quiet.}
{213}{}{一切都很安静。}
#{214}{}{Ain't seen nobody.}
{214}{}{谁也没看见。}
#{215}{}{Ain't nobody comin' through here!}
{215}{}{这里没有人！}
#{216}{}{Nothing to say, really.}
{216}{}{没什么好说的，真的。}
#{217}{}{I'm on watch.}
{217}{}{我在值班。}
