#{100}{}{You see a shepherd.}
{100}{}{你看到一个牧羊人。}
#{101}{}{You see a shepherd of the Cheyenne tribe.}
{101}{}{你看到夏延部落的牧羊人。}
#{200}{}{Haw!}
{200}{}{哈哈！}
#{201}{}{Hello. Who are you and what are you doing here?}
{201}{}{你好。你是谁，你在这里干什么？}
#{202}{}{}
{202}{}{}
#{203}{}{Let's trade.}
{203}{}{我们交易吧。}
#{204}{}{I'm just passing through.}
{204}{}{我只是路过。}
#{205}{}{How much for that shiny metal box, again?}
{205}{}{那个闪亮的金属盒子多少钱？}
#{207}{}{You blindly purchased a seemingly useless knickknack on the off chance it might be useful someday. You feel like quite the gambler.}
{207}{}{你盲目地购买了一件看似无用的小摆设，却不知道有一天它可能会有用。你觉得自己像个赌徒。}
#{210}{}{I is shepherd! I live here, in field. I watch crops and guide livestock. I is alone, but that is good for me.}
{210}{}{我是牧羊人！我住在这里，在田野里。我观察庄稼，引导牲畜。我独自一人，但这对我有好处。}
#{211}{}{Right. What's that big metal thing in the middle of the field?}
{211}{}{正确的。田里的那个大金属是什么？}
#{212}{}{So you watch this whole field, huh? You must have found a lot of interesting things out here. Want to trade? It's a shame I don't have any glass beads... }
{212}{}{所以你看了整个球场，嗯？你一定在这里发现了很多有趣的东西。想交易吗？可惜我没有玻璃珠...}
#{213}{}{A shepherd without sheep, huh? I should be going.}
{213}{}{一个没有羊的牧羊人，嗯？我该走了。}
#{214}{}{That big bucket full of poison fire! It fell from sky and spilled. It burned beautiful, but only I saw. Then... Plants that bite grew around it. Hmm.}
{214}{}{装满毒火的大桶！它从天而降，洒了出来。它烧得很漂亮，但只有我看到了。然后...它周围生长着能咬人的植物。隐马尔可夫模型。}
#{215}{}{Fell from the sky? How interesting! I'll go have a closer look.}
{215}{}{从天上掉下来的？多有趣啊！我去仔细看看。}
#{216}{}{Uh, wait, outsider! Do not go there. That filth burns feet!}
{216}{}{等等，外人！不要去那里。那脏东西烫脚！}
#{217}{}{I'll keep that in mind.}
{217}{}{我会记住的。}
#{218}{}{Mmm. I have junk. I trade junk.}
{218}{}{嗯。我有垃圾。我交易垃圾。}
#{219}{}{Let's barter.}
{219}{}{我们交换吧。}
#{220}{}{I'll come back later.}
{220}{}{我一会儿回来。}
#{221}{}{Mmm. I have some junk... Some stuff. And... Something shiny!}
{221}{}{嗯。我有一些垃圾...一些东西。还有...闪亮的东西！}
#{222}{}{What is it? Will you show me?}
{222}{}{它是什么？你能给我看看吗？}
#{223}{}{Shiny? This I gotta see!}
{223}{}{闪亮的？我要看看这个！}
#{224}{}{Look! [He holds out a metal box emblazoned with a multi-colored animal with big ears. You have no idea what it is, but it looks like a pre-war device. You study a few buttons in the hope that the shepherd hasn't thought to press them.]}
{224}{}{你看！[他拿出一个金属盒子，上面印有一只多色的大耳朵动物。你不知道它是什么，但它看起来像是战前的装置。你研究了几个按钮，希望牧羊人没有想到按它们。]}
#{225}{}{Very tempting. What do you want for it!}
{225}{}{非常诱人。你想要什么！}
#{226}{}{Money! Much money! Trade for... Hmm... }
{226}{}{钱！很多钱！用…换...Hmm...}
#{227}{}{Deal. Here's the money.}
{227}{}{处理。这是钱。}
#{228}{}{Sorry, I don't have that much. Maybe later.}
{228}{}{对不起，我没有那么多。也许以后吧。}
#{229}{}{Good!}
{229}{}{很好！}
#{230}{}{Let's talk about something else.}
{230}{}{我们再谈点别的吧。}
#{233}{}{How about a leather jacket? It protects against the sun and wind.}
{233}{}{皮夹克怎么样？它能防晒防风。}
#{234}{}{You want clothes? It must be unpleasant walking around half-naked.}
{234}{}{你想要衣服吗？半裸着走来走去一定很不舒服。}
#{235}{}{Nah. I is comfortable in own skin.}
{235}{}{不。我对自己的皮肤很舒服。}
#{237}{}{It'll be easier just to kill you! You'll sell your junk to the worms, shithead!}
{237}{}{杀了你就容易多了！你要把你的垃圾卖给虫子，混蛋！}
#{238}{}{Ooh! [he rubs his hands together] I want that! Deal!}
{238}{}{哦！[他搓着手]我要！处理！}
#{239}{}{Give me a second to take it off, then.}
{239}{}{给我一点时间把它脱下来。}
#{240}{}{Then remind me, what do you need?}
{240}{}{那提醒我，你需要什么？}
#{241}{}{Ooh! I want that! Deal! [he takes the jacket, rubbing his fingers over the leather with a satisfied nod, and hands you the device]}
{241}{}{哦！我要那个！处理！[他拿起夹克，满意地点了点头，用手指在皮革上摩擦，然后把装置递给你]}
#{250}{}{I'm looking for a radio station somewhere around here. You probably know where it is. Can you show me?}
{250}{}{我在这附近找一个电台。你可能知道它在哪里。你能给我看看吗？}
#{251}{}{Hmm... Nah. Chief will angry, hurt with words. Bad.}
{251}{}{Hmm...不。酋长会生气，会用言语伤害他。糟糕。}
#{252}{}{Yeah, with my reputation, no one would be happy to hear you helped me. Oh well.}
{252}{}{是啊，以我的名誉，没人会高兴听到你帮助我。哦，好吧。}
#{253}{}{Let??s talk about something else.}
{253}{}{我们再谈点别的吧。}
#{254}{}{He won??t find out. I promise. You can trust me.}
{254}{}{他不会发现的。我保证。你可以相信我。}
#{255}{}{Hmm. [he looks around] Okay. You is good people. I show you.}
{255}{}{嗯[他环顾四周]好的。你是好人。我给你看。}
#{256}{}{Great. Take me there.}
{256}{}{伟大的。带我去那儿。}
#{257}{}{You can do this the easy way, or my gang can make you do it the hard way.}
{257}{}{你可以用简单的方法，或者我的帮派让你用困难的方法。}
#{258}{}{Uhh - ! No, I show, I show!}
{258}{}{呃-！不，我展示，我展示！}
#{259}{}{It's important. I need to find that station to find out about my past. Please, can't you help me? I know you're a good man.}
{259}{}{这很重要。我得去那家电台看看我的过去。拜托，你能帮帮我吗？我知道你是个好人。}
#{260}{}{Hmmmm... Pretty talk. Okay. I show you.}
{260}{}{嗯...说得不错。可以。我给你看。}
#{261}{}{What if I give you this sharpened spear?}
{261}{}{我给你这把磨快的矛怎么样？}
#{262}{}{What if I give you this leather jacket?}
{262}{}{我给你这件皮夹克怎么样？}
#{263}{}{What if I give you this cattle prod?}
{263}{}{如果我给你这个牛戳怎么办？}
#{264}{}{[He nods and takes it] I show you.}
{264}{}{[他点头接受]我给你看。}
#{350}{}{Can I borrow your spear? I need it!}
{350}{}{我能借用你的矛吗？我需要它！}
#{351}{}{No! You take spear and run away. I lose spear forever!}
{351}{}{不！你拿着长矛跑了。我永远失去长矛！}
#{352}{}{No, no! I'll bring it back, I promise!}
{352}{}{不，不！我会把它带回来的，我保证！}
#{353}{}{Ogima asked me to kill the dangerous plants. I need that spear to do it!}
{353}{}{奥吉玛让我杀了那些危险的植物。我需要那把矛！}
#{354}{}{Give me the damn spear, now!}
{354}{}{快把那该死的矛给我！}
#{355}{}{Don't you think you're being selfish?}
{355}{}{你不觉得你很自私吗？}
#{356}{}{Fine, fine. I'll manage without your help.}
{356}{}{很好，很好。没有你的帮助我能应付。}
#{357}{}{[He grits his teeth and clutches his spear tighter.]}
{357}{}{[他咬紧牙关，握紧长矛。]}
#{358}{}{[Grab the spear and pull it away from him.]}
{358}{}{[抓住长矛，把它从他身上拔开。]}
#{359}{}{Fine, have it your way.}
{359}{}{好吧，随你的便。}
#{360}{}{[You grab the spear and pull, but the shepherd sets his feet and pulls back, grunting in effort.]}
{360}{}{[你抓住长矛，然后拉，但是牧羊人站稳了脚，拉了回来，努力地咕哝着。]}
#{361}{}{Hrrngg! [pull harder]}
{361}{}{Hrrngg！[用力拉]}
#{362}{}{Fine, keep the damn spear! [let go]}
{362}{}{好吧，拿着那该死的矛！[放手]}
#{363}{}{[The shepherd falls onto his back] Ooof!}
{363}{}{[牧羊人倒地]噢！}
#{364}{}{Ha! Serves you right. [leave]}
{364}{}{哈！你做得对。[离开]}
#{365}{}{[This shepherd's pretty strong! He pulls back on the spear, his veins standing out on his arms and neck so intensely that they look like they'll pop any second.]}
{365}{}{[这个牧羊人很强壮！他拉回长矛，手臂和脖子上的血管非常突出，看起来随时都会爆裂。]}
#{366}{}{HRRRAAAGGHHH!! [pull with all of your strength]}
{366}{}{哈哈哈！！[用尽全力]}
#{367}{}{[Suddenly let go of the spear.]}
{367}{}{[突然放开长矛。]}
#{368}{}{[Snatch the spear while the shepherd is stunned] Aha!}
{368}{}{[在牧羊人惊呆的时候抓住长矛]啊哈！}
#{369}{}{Ha! Now shut up... }
{369}{}{哈！现在闭嘴...}
#{370}{}{[The shepherd overpowers you, pulling the spear back and sending you sprawling to the ground] Ha! I is strong! Outsider is weak!}
{370}{}{[牧羊人压倒了你，拔出长矛，把你摔倒在地]哈！我很坚强！外人很软弱！}
#{371}{}{Do you know who you're fucking with?! Come here and I'll rip your fucking arms out!}
{371}{}{你知道你在和谁做爱吗？！过来，我要把你的胳膊撕下来！}
#{372}{}{Fine, fine. No fighting.}
{372}{}{很好，很好。不许打架。}
#{373}{}{Ha-ha-ha! Outsider act bad, but no! I see in your eyes!}
{373}{}{哈哈哈！局外人表现不好，但不是！我看见你的眼睛了！}
#{374}{}{No, I is not selfish! You is greedy!}
{374}{}{不，我不自私！你太贪心了！}
#{375}{}{I politely asked to borrow your spear for just a little while, and you wouldn't even let me do that. YOU'RE greedy.}
{375}{}{我礼貌地向你借了一小会儿你的矛，你甚至不让我这么做。你太贪心了。}
#{376}{}{NO!}
{376}{}{不！}
#{377}{}{YES!}
{377}{}{对！}
#{378}{}{No, outsider is... Is... No, no! I wanted give spear!}
{378}{}{不，外人是...是...不，不！我要给你矛！}
#{379}{}{You see? Someone asks you for help, and you can only think of yourself. The tribe will be so disappointed when I tell them!}
{379}{}{你看到了吗？有人向你求助，你只能想到自己。我告诉他们，部落会很失望的！}
#{380}{}{Ahhh, no! Outsider no tell! Take spear, take it! [he throws the spear down on the ground and steps back, grabbing his head in hysteria]}
{380}{}{啊，不！外人不说！拿着长矛，拿着它！[他把长矛扔在地上，退后一步，歇斯底里地抓着他的头]}
#{381}{}{Right choice, pal.}
{381}{}{选择正确，伙计。}
#{382}{}{I no trust outsiders!}
{382}{}{我不相信外人！}
#{383}{}{Why don't you try? Maybe the world isn't as bad as you think.}
{383}{}{你为什么不试试？也许这个世界没有你想象的那么糟糕。}
#{384}{}{Ha! Outsiders bring pain to tribe. Ogima say tribe should avoid outsiders!}
{384}{}{哈！局外人给部落带来痛苦。奥吉玛说部落应该避开外人！}
#{385}{}{Well, not everyone, right? I'm not like the others!}
{385}{}{不是每个人都这样，对吧？我不像其他人！}
#{386}{}{No, spirits say different.}
{386}{}{不，灵魂说的不一样。}
#{387}{}{Hmm... Spirits not sure about you. Strange.}
{387}{}{Hmm...我对你不确定。奇怪。}
#{388}{}{This means you have the chance to help a good person. Isn't that right?}
{388}{}{这意味着你有机会帮助一个好人。不是吗？}
#{389}{}{Hmm... Ogima say must help good people. Here, take spear.}
{389}{}{Hmm...奥吉玛说必须帮助好人。拿着长矛。}
#{390}{}{Thank you, friend. I'll use it well.}
{390}{}{谢谢你，朋友。我会好好利用的。}
#{391}{}{Ha! You??re so easy to fool!}
{391}{}{哈！你太容易被愚弄了！}
#{392}{}{Thank you. I'll bring it back once I'm done.}
{392}{}{非常感谢。我一做完就把它拿回来。}
#{393}{}{No. I need spear to herd moo-moos. Tribe need it.}
{393}{}{不，我需要长矛来放牧哞哞。我需要它。}
#{394}{}{You say you kill plants, but you have no spear? [he shakes his head] Stupid.}
{394}{}{你说你杀植物，但你没有长矛？[他摇头]愚蠢。}
#{395}{}{So can I borrow the spear?}
{395}{}{那我能借用一下长矛吗？}
#{396}{}{You must promise you will bring back!}
{396}{}{你必须保证你会带回来的！}
#{397}{}{Uhh... I'll try.}
{397}{}{呃...我试试看。}
#{398}{}{Promise!}
{398}{}{答应我！}
#{399}{}{I solemnly swear I will return the spear after killing the dangerous plants, may I be damned if I don't.}
{399}{}{我郑重发誓，杀掉那些危险的植物后，我会把长矛还给你的，如果我不还的话，我会被诅咒的。}
#{400}{}{I can??t promise that, sorry.}
{400}{}{我不能保证，对不起。}
#{401}{}{Then I keep spear.}
{401}{}{那我就留着长矛。}
#{402}{}{[The shepherd solemnly hands you the spear as if it's a holy relic] May its blade forever point forward on path of light.}
{402}{}{[牧羊人郑重地把长矛递给你，好像它是圣物一样]愿它的刀刃永远指向光明之路。}
#{403}{}{Uh, yeah, sure. I'll be back.}
{403}{}{嗯，是的，当然。我会回来的。}
#{404}{}{Ha! What an idiot!}
{404}{}{哈！真是个白痴！}
#{405}{}{Jeez, what a hassle. You sure you don't want to write up a contract or something?}
{405}{}{天哪，真麻烦。你确定不想写合同什么的？}
#{406}{}{Thank you. I'll bring it back when I'm done.}
{406}{}{非常感谢。我做完了再拿回来。}
#{407}{}{No. The tribe say outsider is bad.}
{407}{}{不，部落说外人不好。}
#{408}{}{Here's your spear.}
{408}{}{这是你的长矛。}
#{409}{}{[The shepherd's eyes widen in astonishment.]}
{409}{}{[牧羊人惊奇地睁大了眼睛。]}
#{410}{}{Yes, I'm giving it back. I'm honest.}
{410}{}{是的，我要还给你。我是诚实的。}
#{411}{}{Pfft, look at your face! Nah, I'm just kidding, it's mine now.}
{411}{}{Pfft，看看你的脸！不，我只是开玩笑，现在是我的了。}
#{412}{}{Outsider no steal? Outsider not forget about poor shepherd?}
{412}{}{外人不偷？外人不忘可怜的牧羊人吗？}
#{413}{}{Just take the damn spear!}
{413}{}{拿着那该死的长矛！}
#{414}{}{Yes, that's right. I want to be good.}
{414}{}{是的，没错。我想做个好人。}
#{415}{}{No, outsider just kidding. I'm keeping it.}
{415}{}{不，外人只是开玩笑。我留着呢。}
#{416}{}{[The shepherd takes the spear and bows his head respectfully] Outsider do right thing.}
{416}{}{[牧羊人拿起长矛，恭敬地低头]外人做正确的事。}
#{417}{}{Yeah, I'm just that kind of guy. See you.}
{417}{}{是的，我就是那种人。再见。}
#{418}{}{[The shepherd pushes the spear towards you] Outsider is good. Outsider need it. Take!}
{418}{}{[牧羊人向你推矛]外人很好。外人需要。拿着！}
#{419}{}{Thank you, friend! I do need it.}
{419}{}{谢谢你，朋友！我确实需要它。}
#{420}{}{The shepherd gave you his spear as a gift. It seems he trusts you.}
{420}{}{牧羊人送给你他的长矛作为礼物。看来他信任你。}
#{450}{}{I need you to carry something heavy for me.}
{450}{}{我需要你帮我拿些重东西。}
#{451}{}{Nah. I no want to carry heavy things.}
{451}{}{不。我不想搬重物。}
#{452}{}{I wasn't asking. That's an order!}
{452}{}{我没问。这是命令！}
#{453}{}{I want to fix the bridge. Don't you care about helping the tribe?}
{453}{}{我想修这座桥。你不关心帮助部落吗？}
#{454}{}{Oh yeah? What if I tell your chief that you fed the brahmin that green filth in the field?}
{454}{}{哦，是吗？如果我告诉你的首领你喂双头牛田野里的绿色脏物呢？}
#{455}{}{Forget it. Let me ask you something else.}
{455}{}{算了吧。我再问你一件事。}
#{456}{}{Fine, I'll do it myself.}
{456}{}{好吧，我自己来。}
#{457}{}{What?! I no feed moo-moos green filth! No!}
{457}{}{什么？！我不喂妈妈绿色的脏东西！不！}
#{458}{}{Oh, I know that. But the chief doesn't. You see what I'm getting at?}
{458}{}{哦，我知道。但头儿没有。你明白我的意思吗？}
#{459}{}{Grr... Bad outsider! All outsiders bad! Leave!}
{459}{}{Grr...坏外人！所有外人都很坏！快走！}
#{460}{}{I'm warning for the last time - help me with those planks, or I'll turn the whole tribe against you! I'm pretty sure they'll believe me, too - I bet there's a reason you live all by yourself.}
{460}{}{我最后一次警告你-帮我拿那些木板，否则我会让整个部落都反对你！我很肯定他们也会相信我的-我打赌你一个人生活是有原因的。}
#{461}{}{Fine, whatever.}
{461}{}{好吧，随便了。}
#{462}{}{[He nervous] N-no! Outsider wrong! Only... I help anyway. I strong. No problem.}
{462}{}{[他紧张]不！外人错了！只有...反正我也帮你。我很强壮。没问题。}
#{463}{}{Move your ass, already!}
{463}{}{快点，快点！}
#{464}{}{Great! Get to work!}
{464}{}{太好了！开始工作吧！}
#{465}{}{Maybe I don't need your help after all.}
{465}{}{也许我根本不需要你的帮助。}
#{466}{}{[He punches himself in the chest and stands up straight] I is NO SLAVE!}
{466}{}{[他打了自己的胸口，站直了]我不是奴隶！}
#{467}{}{Oh, look at the big man!}
{467}{}{哦，看那个大个子！}
#{468}{}{[He pauses indecisively for a moment before glancing in the direction of Big Louie's base] I... No want trouble. What I carry?}
{468}{}{[他犹豫不决地停顿了一会儿，然后朝大路易的基地方向瞥了一眼]我...不想惹麻烦。我带什么？}
#{469}{}{Move those planks to the bridge. Double time!}
{469}{}{把那些木板搬到桥上去。加倍时间！}
#{470}{}{Nothing, I can do it without you.}
{470}{}{没有你，我什么也做不了。}
#{471}{}{I no trust outsider. Outsiders never do thing just to help.}
{471}{}{我不相信外人。局外人从不做只是为了帮忙的事。}
#{472}{}{Fine. Maybe I can change your mind about me.}
{472}{}{好的。也许我可以改变你对我的看法。}
#{473}{}{Outsider wants to help? Hmm... Outsider is good people. I help.}
{473}{}{外人想帮忙？Hmm...外人是好人。我帮忙。}
#{474}{}{Great! We have to take those planks to the bridge... }
{474}{}{太好了！我们得把那些木板拿到桥上去...}
#{475}{}{I think I can do it without you. Rest.}
{475}{}{我想没有你我也能做到。休息。}
#{476}{}{With the shepherd's help, you assemble a drawbridge from the wooden planks.}
{476}{}{在牧羊人的帮助下，你用木板组装了一座吊桥。}
#{477}{}{The bridge is complete.}
{477}{}{这座桥是完整的。}
#{1204}{}{I'm just passing through.}
{1204}{}{我只是路过。}
#{1212}{}{So you watch this whole field, huh? You must have found a lot of interesting things out here. Want to trade? It's a shame I don't have any glass beads... }
{1212}{}{所以你看了整个球场，嗯？你一定在这里发现了很多有趣的东西。想交易吗？可惜我没有玻璃珠...}
#{1227}{}{Deal. Here's the money.}
{1227}{}{处理。这是钱。}
#{1375}{}{I politely asked to borrow your spear for just a little while, and you wouldn't even let me do that. YOU'RE greedy.}
{1375}{}{我礼貌地向你借了一小会儿你的矛，你甚至不让我这么做。你太贪心了。}
#{1385}{}{Well, not everyone, right? I'm not like the others!}
{1385}{}{不是每个人都这样，对吧？我不像其他人！}
#{1410}{}{Yes, I'm giving it back. I'm honest.}
{1410}{}{是的，我要还给你。我是诚实的。}
#{1414}{}{Yes, that's right. I want to be good.}
{1414}{}{是的，没错。我想做个好人。}
#{1417}{}{Yeah, I'm just that kind of girl. See you.}
{1417}{}{是啊，我就是那种女孩。再见。}
