#{100}{}{}
{100}{}{}
#{101}{}{}
{101}{}{}
#{110}{}{These wood planks are still quite suitable for construction.}
{110}{}{这些木板仍然很适合建筑。}
#{111}{}{You don't need these planks anymore.}
{111}{}{你不再需要这些木板了。}
#{112}{}{With your physique, carrying such weights can result in trauma.}
{112}{}{就你的体格而言，负重会造成创伤。}
#{113}{}{Oomph...}
{113}{}{哦...}
#{114}{}{This will hardly be of use here.}
{114}{}{这在这里几乎没有用。}
#{115}{}{Construction finished}
{115}{}{施工完毕}
#{116}{}{You've built the hinged part of the bridge.}
{116}{}{你把桥的铰链部分修好了。}
#{117}{}{These wood planks could be used for construction.}
{117}{}{这些木板可用于建筑。}
#{118}{}{Just some planks.}
{118}{}{只是一些木板。}
