#{100}{}{Better not to go in there}
{100}{}{最好不要进去}
#{101}{}{You can't go in there}
{101}{}{你不能进去}
#{102}{}{Get away from there!}
{102}{}{离开那里！}
#{103}{}{You shouldn't go there}
{103}{}{你不应该去那里}
#{104}{}{Hey, I'm still watching you}
{104}{}{嘿，我还在看你呢}
#{105}{}{Where do you think you're going?}
{105}{}{你想去哪儿？}
#{106}{}{The Chief's hut is the other way, outsider}
{106}{}{酋长的小屋是另一条路，外人}
#{107}{}{What are you going there for?}
{107}{}{你去那里干什么？}
#{108}{}{What do you want there?}
{108}{}{你想在那里干什么？}
#{109}{}{What do you have in mind?}
{109}{}{你有什么想法？}
#{110}{}{Get back here now!}
{110}{}{快回来！}
#{111}{}{Looking for trouble?}
{111}{}{找麻烦？}
#{112}{}{Outsider, this is not your hut!}
{112}{}{外人，这不是你的小屋！}
#{113}{}{Outsider, get out of this hut!}
{113}{}{外人，离开这个小屋！}
#{114}{}{Outsider, the Chief lives in the other hut}
{114}{}{外人，酋长住在另一间小屋里}
#{115}{}{You weren't invited}
{115}{}{你没有被邀请}
#{116}{}{Where are you hiding, outsider? Come out, you're just making it worse for yourself!}
{116}{}{外人，你躲在哪里？出来，你只会让你自己更糟！}
