#{100}{}{You see a bored visitor.}
{100}{}{你看到一个无聊的访客。}
#{101}{}{You see a visitor with a sad look.}
{101}{}{你看到一个面带愁容的来访者。}
#{110}{}{Hello. You missed the booze too?}
{110}{}{你好。你也错过了喝酒？}
#{111}{}{Maybe. What are you doing here?}
{111}{}{也许 吧。你在这里干什么？}
#{112}{}{Why you have such a sour look?}
{112}{}{你怎么这么愁眉苦脸的？}
#{113}{}{Yeah, why do you care?}
{113}{}{是啊，你为什么在乎？}
#{114}{}{No, I was just passing by.}
{114}{}{不，我只是路过。}
#{115}{}{Well, I thought maybe you would join my company, but if you don't want to...}
{115}{}{嗯，我想也许你会加入我的公司，但如果你不想...}
#{116}{}{Oh, this. Of course, here's 5 bucks for a beer.}
{116}{}{哦，这个。当然，这5块钱买一杯啤酒。}
#{117}{}{Not this time.}
{117}{}{这次不行。}
#{118}{}{Let me think... Hmm... Oh well, I guess I'm just sad and have no one to drink with.}
{118}{}{让我想想...Hmm...哦，好吧，我想我只是难过，没人陪我喝酒。}
#{119}{}{I see. Well, I won't keep you.}
{119}{}{我懂了。好吧，我不留你了。}
#{120}{}{Trying to drink and forget about everything and everyone, don't you see?}
{120}{}{试着去喝酒，忘记所有的事和人，你不明白吗？}
#{121}{}{Let me get you a drink. Hey bartender, here's 10 bucks for a beer for my friend!}
{121}{}{我给你拿杯喝的。嘿，酒保，给我朋友10块钱买一杯啤酒！}
#{122}{}{Here is a beer, help yourself.}
{122}{}{这是啤酒，请随便喝。}
#{123}{}{Then let me get you a beer from my supply.}
{123}{}{那我去给你拿瓶啤酒。}
#{124}{}{Well, then have a beer from my supply.}
{124}{}{好吧，那就喝我供应的啤酒吧。}
#{125}{}{Thanks, buddy. Nice to see such friendly people in this place.}
{125}{}{谢谢，伙计。很高兴在这里见到这么友好的人。}
#{126}{}{Why are you so sad?}
{126}{}{你为什么这么伤心？}
#{127}{}{You could at least try to look happy.}
{127}{}{你至少可以试着看起来开心点。}
#{128}{}{Sorry, just sad. Sometimes I come here to honor the memory of my best friend.}
{128}{}{对不起，只是难过。有时我来这里纪念我最好的朋友。}
#{129}{}{What happened to him?}
{129}{}{他怎么了？}
#{130}{}{He was quite the athlete, moved by the idea of a healthy lifestyle! Day by day he trained hard, wore clean clothes and even brushed his teeth.}
{130}{}{他是个十足的运动员，被健康的生活方式所感动！他日复一日地刻苦训练，穿着干净的衣服，甚至刷牙。}
#{131}{}{Must been a nice guy.}
{131}{}{一定是个好人。}
#{132}{}{Why? Didn't he got anything else to do?}
{132}{}{为什么？他没有别的事要做吗？}
#{133}{}{Well, it would be all nice if one day he didn't read the poster with the pre-war advertising. It said that the use of radium water is good for the body. Here it is. [gives you a small bottle with clear liquid] He found a whole box of this abomination and started to drink 3 bottles a day... Until he died from toxic poisoning.}
{133}{}{好吧，如果有一天他不看战前广告的海报就好了。据说使用镭水对身体有好处。给你。[给你一小瓶清澈的液体]他发现了一整盒这种可憎的东西，开始每天喝3瓶...直到他死于中毒。}
#{134}{}{How sad and strange...}
{134}{}{多么悲伤和奇怪...}
#{135}{}{What an absurd death!}
{135}{}{多么荒谬的死亡！}
#{136}{}{Yes, it is. It turned out that radium water is toxic - slow acting poison. Oh, poor Byers, who would have known that people before the were was so stupid...}
{136}{}{是的，是的。原来镭水是有毒的-慢效毒药。哦，可怜的拜尔斯，谁会知道以前的人是如此愚蠢...}
#{137}{}{It's a sad story, friend. I'm sorry.}
{137}{}{这是一个悲伤的故事，朋友。我很抱歉。}
#{138}{}{Yeah, just a large crowd of idiots. Damn right!}
{138}{}{是啊，只是一群白痴。他妈的对！}
#{139}{}{Let's drink for the deceased, that is all we can do now.}
{139}{}{让我们为死者干杯，这就是我们现在能做的。}
#{140}{}{Sure, let's drink!}
{140}{}{当然，我们喝一杯吧！}
#{141}{}{Okay, I probably tired you. Thank you for listening. And for the beer too. You're a good person.}
{141}{}{好吧，我可能累了你。谢谢你的聆听。还有啤酒。你是个好人。}
#{142}{}{Okay, I probably tired you. Thank you for listening. And for the beer too. Don't know what you have in mind, but I like you.}
{142}{}{好吧，我可能累了你。谢谢你的聆听。还有啤酒。不知道你在想什么，但我喜欢你。}
#{143}{}{Yeah, bye.}
{143}{}{好的，再见。}
#{1110}{}{Hello. You missed the booze too?}
{1110}{}{你好。你也错过了喝酒？}
#{1114}{}{No, I was just passing by.}
{1114}{}{不，我只是路过。}
#{1115}{}{Well, I thought maybe you would join my company, but if you don't want to...}
{1115}{}{嗯，我想也许你会加入我的公司，但如果你不想...}
#{1125}{}{Thanks, girl. Nice to see such friendly people in this place.}
{1125}{}{谢谢，姑娘。很高兴在这里见到这么友好的人。}
#{1141}{}{Okay, I probably tired you. Thank you for listening. And for the beer too. You're a good person.}
{1141}{}{好吧，我可能累了你。谢谢你的聆听。还有啤酒。你是个好人。}
#{1142}{}{Okay, I probably tired you. Thank you for listening. And for the beer too. Don't know what you have in mind, but I like you.}
{1142}{}{好吧，我可能累了你。谢谢你的聆听。还有啤酒。不知道你在想什么，但我喜欢你。}
