#{100}{}{You see Woody the bartender.}
{100}{}{你看到酒保伍迪了。}
#{101}{}{This man could pass for an ordinary bartender if not for the patches and bits of metal sewn into his business suit.}
{101}{}{如果不是西装上缝的补丁和金属片，这个人可以算是一个普通的酒保。}
#{102}{}{I'd be happy to serve you, but that thing in your hands is making me nervous.}
{102}{}{我很乐意为你服务，但你手里的东西让我很紧张。}
#{103}{}{We don't judge, but... It'd be nice to know who we're dealing with.}
{103}{}{我们不判断，但是...很高兴知道我们在和谁打交道。}
#{110}{}{Where can I find a job around here?}
{110}{}{我在这附近哪里能找到工作？}
#{111}{}{We need representatives for a courier service. The job isn't hard, but delicate. [Looks you over] Doubt you'll fit the bill.}
{111}{}{我们需要快递服务的代表。这工作不难，但很微妙。[看着你]我怀疑你是否符合条件。}
#{112}{}{Well, not like I needed it that much.}
{112}{}{好吧，我不是那么需要它。}
#{113}{}{Well, I won't waste your time then.}
{113}{}{好吧，那我就不浪费你的时间了。}
#{114}{}{We need representatives for a courier service. The job isn't hard, but delicate. [Looks you over] You could stand to earn quite a bit.}
{114}{}{我们需要快递服务的代表。这工作不难，但很微妙。[看着你]你可以挣不少钱。}
#{115}{}{Great, what needs to be done?}
{115}{}{太好了，需要做什么？}
#{116}{}{I'll need to think about it. Hopefully you won't find anyone beforehand.}
{116}{}{我需要考虑一下。希望你不会事先找到任何人。}
#{117}{}{There are a few clients who need pizza to be delivered to them. They pay on the spot - the cost is 10$ and a little extra for the delivery service. Keep in mind - whatever happens, you must show yourself in the best light. There are times when you can't stand your client. That's where the delicacy is required.}
{117}{}{有一些客户需要送比萨饼给他们。他们当场付款——费用是10美元，还有一点额外的送货服务费。记住——无论发生什么，你都必须在最好的光线下展现自己。有时候你受不了你的客户。这就是需要美味的地方。}
#{118}{}{Alright. I'm ready.}
{118}{}{好吧。我准备好了。}
#{119}{}{I can't do it right now. But I'll keep it in mind.}
{119}{}{我现在不行。但我会记住的。}
#{120}{}{Here, this is for the clients. Now write this down. One pizza needs to be delivered to the "Monte" casino, room 15, on the second floor. Another order is by a trader at the caravan stop, named Tibbett. And another one for mister Farber, the administrator of the Slavertown ring. Now come on - get to work!}
{120}{}{这是给客户的。现在把这个写下来。一份比萨饼需要送到二楼15号“蒙特”赌场。另一个订单是商队车站的一个商人，名叫蒂贝特。另一张是给法伯先生的，他是斯莱弗敦戒指的管理员。快点-开始工作！}
#{121}{}{Alright.}
{121}{}{好吧。}
#{122}{}{Oh yeah, almost forgot. You've got an hour. Keep an eye on the time.}
{122}{}{哦，是的，差点忘了。你还有一个小时。注意时间。}
#{123}{}{Okay.}
{123}{}{可以。}
#{124}{}{About the pizza delivery.}
{124}{}{关于送披萨的事。}
#{125}{}{What about pizza? You already missed all the possible deadlines. Have you got anything to say in your defense?}
{125}{}{披萨怎么样？你已经错过了所有可能的最后期限。你有什么要说的吗？}
#{126}{}{Did you finish the job yet?}
{126}{}{你完成工作了吗？}
#{127}{}{All the clients have received their order.}
{127}{}{所有客户都已收到订单。}
#{128}{}{I'm still working on it.}
{128}{}{我还在努力。}
#{129}{}{Unfortunately, err, I wasn't able to finish the job. The clients are lost, the time is up and I'm out of pizza.}
{129}{}{不幸的是，呃，我没能完成这项工作。客户不见了，时间到了，我的比萨饼也吃完了。}
#{130}{}{[Through his teeth] Moron!! [quickly gets a hold of himself] So, you lost }
{130}{}{[咬牙切齿]白痴！！[很快控制住自己]那么，你输了}
#{131}{}{$ of profit. Who's is going to get them back?}
{131}{}{美元的利润。谁来把他们弄回来？}
#{132}{}{No problem, I'll pay it out of my own wallet. Here: }
{132}{}{没问题，我用自己的钱包付。在这里：}
#{133}{}{$.}
{133}{}{$.}
#{134}{}{I'm not gonna pay for anything!}
{134}{}{我什么都不会付钱的！}
#{135}{}{I don't have that kind of money!}
{135}{}{我没有那么多钱！}
#{136}{}{Yeah, I can see that! How could I even think you were right for the job?! Ugh... Get out!}
{136}{}{是的，我看得出来！我怎么能认为你适合这份工作？！呃...走出！}
#{137}{}{You don't...}
{137}{}{你不...}
#{138}{}{Really? Is that honesty or stupidity? Well, if you're gonna pay for your screw-up, then I've got no problems. [counts the money] I should also get extra from you for crippling our reputation, but since you were honest, I'll let you off the hook.}
{138}{}{真正地？那是诚实还是愚蠢？好吧，如果你要为你的失败付出代价，那我就没问题了。[数钱]我也应该从你那里得到额外的钱，因为你损害了我们的声誉，但既然你是诚实的，我就让你摆脱困境。}
#{139}{}{Security! Security! Pat this motherfucker down for money and throw him out on the streets! Come on! Quickly, before he gets away!}
{139}{}{保安！保安！拍下这个混蛋要钱然后把他扔到街上！加油！快点，在他逃走之前！}
#{140}{}{Uh-oh...}
{140}{}{哦哦...}
#{141}{}{Great. You delivered three pizzas. That's }
{141}{}{伟大的。你送了三个披萨。那是}
#{142}{}{30$ for the cafe. Hand over the money. Keep the tip, of course.}
{142}{}{咖啡馆30美元。把钱交出来。当然，小费要留着。}
#{143}{}{[Hand over the profits]}
{143}{}{[交出利润]}
#{144}{}{I, err, I'll bring them right now.}
{144}{}{一、 呃，我现在就拿来。}
#{145}{}{A fine job, courier! You know, there were some positive reviews of your work. Someone even hired our kitchen for a party, talking about your service. So, other than thanking you, I should pay you 10$ extra. You can rest for now, there are no more orders... Oh yeah, since you're one of our own, you'll get a 20% discount any time you eat here.}
{145}{}{干得好，信使！你知道，对你的工作有一些积极的评价。有人甚至雇了我们的厨房来开派对，谈论你的服务。所以，除了谢谢你，我应该多给你10美元。你现在可以休息了，没有更多的命令...哦，是的，既然你是我们的人，你在这里吃东西的时候可以打八折。}
#{146}{}{Good job, courier! Good job. You know, you even got some good reviews. Unfortunately we don't have any more orders, so there's nothing to keep you busy. You can go now, thanks.}
{146}{}{干得好，信使！干得好。你知道，你甚至得到了一些好评。很遗憾我们没有更多的订单了，所以没有什么能让你忙的。你现在可以走了，谢谢。}
#{147}{}{I'd congratulate you on a job well done, but some of the clients left a negative review. I warned you that being a courier is a delicate job. You are the face of the company, not just two legs running. I mean, I get it - to the clients you are nobody, no one takes you seriously, they try to mock you. Happens all the time. But we need couriers who can keep to the standards, even in the face of mockery. Now, let me work.}
{147}{}{我要祝贺你的工作做得很好，但有些客户留下了负面评价。我警告过你，当信使是件棘手的工作。你是公司的代言人，不只是两条腿跑。我的意思是，我明白-对客户来说你是无名小卒，没有人把你当回事，他们试图嘲笑你。经常发生。但我们需要那些即使面对嘲笑也能遵守标准的快递员。现在，让我工作。}
#{148}{}{Take care.}
{148}{}{当心。}
#{150}{}{One of the arcade machines doesn't work.}
{150}{}{一台街机坏了。}
#{151}{}{Yeah, I know. We're looking for someone to repair it, but haven't found anyone yet. The machines break pretty often, and we can usually fix them pretty quick. But, as far as I'm aware, that one's fried. Big time.}
{151}{}{是的，我知道。我们正在找人修理，但还没找到人。机器经常坏，我们通常能很快修好。但是，据我所知，那个是油炸的。重要时刻。}
#{152}{}{Why do they break so often?}
{152}{}{为什么它们经常破裂？}
#{153}{}{The players tend to push them to the limit. The old tech just can't handle it - the machines overheat, the wiring burns, something gets jammed. Seems to me, that they were like that even before the war.}
{153}{}{选手们往往把他们逼到极限。旧技术就是处理不了——机器过热，电线烧坏，有东西卡住了。在我看来，他们甚至在战争前都是这样的。}
#{154}{}{Maybe I could fix it?}
{154}{}{也许我能修好它？}
#{155}{}{Maybe. See what you can do. If you fix it, there's 300 bucks in it for you.}
{155}{}{也许 吧。看看你能做什么。如果你修好了，里面有300块给你。}
#{156}{}{Alright, I'll go see what I can do.}
{156}{}{好吧，我去看看我能做什么。}
#{157}{}{Alright, enough about the machines.}
{157}{}{好了，别再提机器了。}
#{158}{}{I managed to repair the machine. It wasn't easy.}
{158}{}{我设法修理了机器。这并不容易。}
#{159}{}{Great! Work like that deserves a reward. Here, as promised, 300$}
{159}{}{太好了！这样的工作值得奖励。这里，如承诺的，300$}
#{200}{}{One rot gut, coming right up...}
{200}{}{一根腐烂的肠子，马上就上来...}
#{201}{}{That will be three bucks...}
{201}{}{三块钱...}
#{202}{}{Another one, friend?}
{202}{}{再来一杯，朋友？}
#{203}{}{Don't touch Suzie!}
{203}{}{别碰苏西！}
#{204}{}{Hey, you can't belch here! Belches and other gasses go outside!}
{204}{}{嘿，你不能在这里打嗝！打嗝和其他毒气都出去了！}
#{205}{}{Two half-ounce bags or a tin?}
{205}{}{两袋半盎司还是一罐？}
#{206}{}{Special order for a Chris right here...}
{206}{}{给克里斯的特别订单就在这里...}
#{207}{}{Let me guess, you want me to put it on your tab?}
{207}{}{让我猜猜，你想让我记在你的帐上吗？}
#{208}{}{One "dive bomb" with ice.}
{208}{}{一个“潜水炸弹”加冰块。}
#{230}{}{How about a hot pizza?}
{230}{}{来个热披萨怎么样？}
#{231}{}{Let me see that menu.}
{231}{}{让我看看菜单。}
#{232}{}{No thanks.}
{232}{}{不用了，谢谢。}
#{233}{}{What's that plant?}
{233}{}{那是什么植物？}
#{234}{}{Desert lily. I bought it from some caravaneers. I'm hoping it's gonna bear fruit, but someone keeps picking it clean before I can get anything. So, really, just keeping it for decoration.}
{234}{}{沙漠百合。我从商队那里买的。我希望它能结出果实，但有人在我得到任何东西之前一直把它摘得干干净净。所以，真的，只是为了装饰。}
#{235}{}{Got it.}
{235}{}{知道了。}
#{236}{}{Oh! This is pizza?! I haven't seen that before.}
{236}{}{哦！这是披萨？！我以前没见过。}
#{237}{}{Yes, it's our special dish. Pizza with mushrooms and gecko meat. Goes really well with Nuka-Cola. I'll certainly recommend trying some, you won't regret it!}
{237}{}{是的，这是我们的特色菜。蘑菇和壁虎肉比萨。和努卡可乐很配。我当然会推荐你尝尝，你不会后悔的！}
#{238}{}{I guess I'll try some.}
{238}{}{我想我要尝尝。}
#{239}{}{I've got another question.}
{239}{}{我还有一个问题。}
#{240}{}{Cute waitress! Bet she has no problems with the guys.}
{240}{}{可爱的女招待！我打赌她和那些家伙没什么问题。}
#{241}{}{She's precious. The kid had a hard childhood. She... How should I put it, is afraid of representatives of the... Stronger gender.}
{241}{}{她很珍贵。这孩子的童年很艰难。她...我该怎么说呢，就是怕代表...更强的性别。}
#{242}{}{Is that so? Any reason?}
{242}{}{是这样吗？有什么原因吗？}
#{243}{}{[Shrugs] I have no idea. But we need to be gentle with her.}
{243}{}{我不知道。但我们要对她温柔一点。}
#{244}{}{Alright, I've got a few more questions.}
{244}{}{好吧，我还有几个问题。}
#{245}{}{Hey friend, tell me, do bikers come around often?}
{245}{}{嘿，朋友，告诉我，骑自行车的人经常来吗？}
#{246}{}{Depends. At times, you don't see 'em for months, and other times they don't leave the city for weeks. They're free people and don't follow a schedule.}
{246}{}{视情况而定。有时，你几个月都见不到他们，有时他们几个星期都不离开城市。他们是自由人，不遵守时间表。}
#{247}{}{Do you know how I can find them?}
{247}{}{你知道我怎么找到他们吗？}
#{248}{}{Well, caravaneers from Salt Lake say that they often see them on this highway. I think their base is somewhere up north.}
{248}{}{嗯，盐湖城的商队说他们经常在这条高速公路上看到他们。我想他们的基地在北边。}
#{249}{}{What does Salt Lake City have to do with this?}
{249}{}{盐湖城和这有什么关系？}
#{250}{}{They're fanatics for technology. Particularly stuff on wheels. Salt Lake had lots of factories, it was a huge industrial center before the War, I think.}
{250}{}{他们是技术狂热分子。尤其是轮子上的东西。盐湖城有很多工厂，我想它在战前是一个巨大的工业中心。}
#{251}{}{Other than tech, they like young girls, don't they?}
{251}{}{除了科技，他们还喜欢年轻女孩，不是吗？}
#{252}{}{Well of course. And girls are crazy for leather-clad men with shiny guns and motorcycles... Especially young ones.}
{252}{}{当然。女孩们喜欢穿皮衣的男人，带着闪亮的枪和摩托车...尤其是年轻人。}
#{253}{}{Well, thanks for nothing! Guess I'll have to figure things out on my own.}
{253}{}{好吧，什么都不用谢！我想我得自己想办法了。}
#{254}{}{Thanks for the help! Might be useful.}
{254}{}{谢谢你的帮助！可能有用。}
#{255}{}{Why's the stage so empty?}
{255}{}{为什么舞台这么空？}
#{256}{}{It's hard to find musicians in our times - people don't have time for music. We usually just put on the jukebox.}
{256}{}{在我们这个时代很难找到音乐家——人们没有时间听音乐。我们通常只放点唱机。}
#{257}{}{What if I find a musician for you?}
{257}{}{如果我给你找个音乐家呢？}
#{258}{}{You know, if Sam Phillips was here, you'd have to take a long time trying to convince him - he's totally disappointed in musicians today. But, the boss isn't here anymore, so bring your friend and we can hear him out. No promises - it all depends on how good he is.}
{258}{}{你知道，如果山姆·菲利普斯在这里，你得花很长时间才能说服他——他对今天的音乐家完全失望了。但是，老板已经不在了，带上你的朋友，我们就可以听到他的声音了。没有承诺-这取决于他有多好。}
#{259}{}{Of course, I'll do exactly that.}
{259}{}{当然，我会做的。}
#{260}{}{If you have a suggestion, talk to Sam Phillips. But, I'll tell you now - he doesn't trust those who want to perform on stage after a series of unfortunate events. He even *personally* checked every worker of this cafe.}
{260}{}{如果你有什么建议，可以和山姆·菲利普斯谈谈。但是，我现在告诉你——他不信任那些在一系列不幸事件之后想在舞台上表演的人。他甚至亲自检查了这家咖啡馆的每个员工。}
#{261}{}{Got it.}
{261}{}{知道了。}
#{262}{}{I'm an official Nuka-Cola supplier...}
{262}{}{我是努卡可乐的官方供应商...}
#{263}{}{Err, no! Don't even start! We've got fooled by your "product" more than once.}
{263}{}{呃，不！别动！我们不止一次被你的“产品”愚弄了。}
#{264}{}{What do you mean?!}
{264}{}{你什么意思？}
#{265}{}{I've no idea who sells that shit, but after anyone tries to drink it, their stomach starts doing backflips all day.}
{265}{}{我不知道是谁卖的，但当有人喝了之后，他们的胃开始整天反胃。}
#{266}{}{That's exactly why we need to work together!}
{266}{}{这正是我们需要合作的原因！}
#{267}{}{Why's that?}
{267}{}{为什么？}
#{268}{}{Because I'm a courier from a Nuka-Cola factory in Salt Lake. No middlemen! The real stuff! Here's my documents.}
{268}{}{因为我是盐湖城努卡可乐厂的快递员。没有中间人！真正的东西！这是我的文件。}
#{269}{}{Because I work without middlemen. The real stuff!}
{269}{}{因为我的工作没有中间人。真正的东西！}
#{270}{}{Because my product is the cleanest. The real deal.}
{270}{}{因为我的产品是最干净的。真正的交易。}
#{271}{}{Because nobody can compare to me in trading skill! Only the best for my clients!}
{271}{}{因为没有人能比得上我的交易技巧！只有对我的客户最好的！}
#{272}{}{I heard that already. No thanks.}
{272}{}{我已经听说了。不用了，谢谢。}
#{273}{}{I've got proof - here's my official documents.}
{273}{}{我有证据-这是我的官方文件。}
#{274}{}{What a shame.}
{274}{}{真可惜。}
#{275}{}{Well that changes things! Great, but I can't make decisions like that. Come, I'll show you to my boss.}
{275}{}{好吧，这改变了一切！很好，但我不能做那样的决定。来，我带你去见我老板。}
#{276}{}{Alright.}
{276}{}{好吧。}
#{277}{}{Yes, I remember. I'd be happy to sign the agreement, but Sam Phillips, my boss, likes to make decisions like that personally.}
{277}{}{是的，我记得。我很乐意签署协议，但我的老板山姆·菲利普斯喜欢亲自做这样的决定。}
#{278}{}{Understood.}
{278}{}{理解。}
#{279}{}{Yes, I remember but... Sam isn't with us anymore, so I'll risk making the deal without him.}
{279}{}{是的，我记得但是...山姆不再和我们在一起了，所以没有他我就冒险做这笔交易。}
#{280}{}{So you agree?!}
{280}{}{你同意吗？！}
#{281}{}{Absolutely! I always told Phillips that we should, but he always said something about it being too hard to get deliveries from Salt Lake. But the competition doesn't sleep - they've got reliable supplies.}
{281}{}{当然！我总是告诉菲利普斯我们应该这样做，但他总是说从盐湖城送货太难了。但是竞争对手没有睡着-他们有可靠的供应。}
#{282}{}{Well, now we can sign the agreement...}
{282}{}{好吧，现在我们可以签协议了...}
#{283}{}{Exactly! You know, I remember the "Monte" casino has a vending machine. It would be sweet to get one set up, so we can sell the product without bothering each other. I'll try and figure that out in the next few days, while you handle the deliveries.}
{283}{}{确切地！我记得“蒙特”赌场有自动售货机。如果能设置一个这样我们就可以在不打扰对方的情况下销售产品，那就太好了。我会在接下来的几天里设法弄清楚的，而你负责送货。}
#{284}{}{Perfect, a pleasure doing business with you!}
{284}{}{太好了，很高兴和你做生意！}
#{285}{}{Hm, Sam isn't with us anymore, and I wouldn't risk such a deal without him.}
{285}{}{嗯，山姆不再和我们在一起了，没有他我不会冒险做这样的交易。}
#{290}{}{I need to see your boss.}
{290}{}{我要见你老板。}
#{291}{}{Of course. Follow me.}
{291}{}{当然。跟着我。}
#{292}{}{Thank you.}
{292}{}{非常感谢。}
#{293}{}{Sam Phillips is in his office. I can show you to him through the kitchen if you really need to see my boss.}
{293}{}{山姆·菲利普斯在他的办公室。如果你真的要见我老板，我可以带你去厨房找他。}
#{294}{}{Yes I do. Take me to him, please.}
{294}{}{是的。请带我去见他。}
#{295}{}{Not yet, I'll be back later.}
{295}{}{还没有，我一会儿回来。}
#{296}{}{How's the new addition to the cultural programme?}
{296}{}{新加入的文化节目怎么样？}
#{297}{}{Wonderful. Your man didn't lose his touch. We had a few problems at first, but everything's fine now. He brings in good money, enticing some rather rich clients.}
{297}{}{精彩的。你的人没有失去联系。起初我们有一些问题，但现在一切都好了。他赚了不少钱，吸引了一些相当富有的客户。}
#{298}{}{Does he play here all the time?}
{298}{}{他一直在这里玩吗？}
#{299}{}{Of course not. He usually comes in during evenings, when some of the more well-off clients come with their wives after work, so they can unwind for a bit. That's when our new, shining star appears on stage... And everyone gets ecstatic!}
{299}{}{当然不是。他通常在晚上来，一些比较富裕的客户下班后和他们的妻子一起来，这样他们可以放松一下。就在那时，我们闪亮的新星出现在舞台上...每个人都会欣喜若狂！}
#{1236}{}{Whoah! This is pizza? I haven't seen this before.}
{1236}{}{哇哦！这是比萨饼？我以前没见过这个。}
