#{100}{}{You see: a guard.}
{100}{}{你看：一个卫兵。}
#{101}{}{You see: a guard of your city. He wears shades.}
{101}{}{你看：你城市的卫兵。他戴着墨镜。}
#{110}{}{You're too late! Do you even realize it?! What are we going to do now?!}
{110}{}{你太晚了！你意识到了吗？！我们现在该怎么办？！}
#{111}{}{Wait. Tell me exactly what happened.}
{111}{}{等待。告诉我到底发生了什么事。}
#{112}{}{I'll think of something.}
{112}{}{我会想办法的。}
#{113}{}{They came from the shadows, like appeared out of nowhere! Then every one of ours had this seizure, all at the same time! And then they went into the vault. Now it??s under their control.}
{113}{}{他们来自阴影，好像不知从哪里冒出来！然后我们每个人都同时发作了！然后他们进了保险库。现在它在他们的控制之下。}
#{114}{}{What about our civilians?}
{114}{}{我们的平民呢？}
#{115}{}{Where is the head of security?}
{115}{}{安全主管在哪里？}
#{116}{}{How many are they in the vault?}
{116}{}{避难所里有多少？}
#{117}{}{Who are they?}
{117}{}{他们是谁？}
#{118}{}{And you are just standing here doing nothing?! You??re useless!}
{118}{}{你只是站在这里无所事事？！你真没用！}
#{119}{}{Fine, I'll think of something.}
{119}{}{好吧，我会想办法的。}
#{120}{}{We took them to the mountains, to a safe place, far away from here. These nights will be like a nightmare for them.}
{120}{}{我们把他们带到山上，一个安全的地方，远离这里。这些夜晚对他们来说就像一场噩梦。}
#{121}{}{Right.}
{121}{}{正确的。}
#{122}{}{Sergeant Graves is in the vault. He went there and never came back. He won??t respond on the radio. I think, we lost him... For good.}
{122}{}{格雷夫斯中士在地下室。他去了那里再也没有回来。他不会在收音机里回应。我想，我们失去了他...永远。}
#{123}{}{Whole squad, couple a dozens of men, I??m not sure how many exactly, but they took two floors and got to the Overseer's post. Complete disaster.}
{123}{}{整班人，几十个人，我不知道到底有多少人，但他们走了两层楼，到了监工的岗位。彻底的灾难。}
#{124}{}{And what CAN we do?! We hadn't even been taught how to shoot properly! Lot of us saw death for the first time in our life... Shit, I think I??m going to be sick!}
{124}{}{我们能做什么？！我们甚至还没被教过如何正确射击！我们很多人有生以来第一次看到死亡...妈的，我想我要生病了！}
#{125}{}{Just a big gang of raiders. that??s all.}
{125}{}{只是一大群袭击者。仅此而已。}
#{126}{}{I can??t even tell if they are humans or not. They all look the same, just like a copy of each other. And their leader... Is some ripped off head in a jar! What is going on?!}
{126}{}{我甚至不知道他们是不是人类。它们看起来都一样，就像彼此的复制品。他们的领袖...是罐子里的脑袋！怎么回事？！}
#{127}{}{I can??t even tell if they are humans or not. They all look the same, just like a copy of each other. And their leader... Looks exactly like our Overseer! I can??t believe it. Could the Overseer betray us?! Why he attacked the vault?! Why?!!!}
{127}{}{我甚至不知道他们是不是人类。它们看起来都一样，就像彼此的复制品。他们的领袖...看起来和我们的监工一模一样！我真不敢相信。监工会背叛我们吗？！他为什么要攻击避难所？！为什么？}
#{128}{}{I can??t even tell if they are humans or not. They all look the same, just like a copy of each other. And their leader... With a bag on his head, a bunch of cables hanging out. I can??t even tell, is he alive or he??s a robot. You better not mess with him, believe me.}
{128}{}{我甚至不知道他们是不是人类。它们看起来都一样，就像彼此的复制品。他们的领袖...头上挎着个包，外面挂着一堆电缆。我甚至不知道，他是活着还是机器人。你最好别惹他，相信我。}
#{1110}{}{You're too late! Do you even realize it?! What are we going to do now?!}
{1110}{}{你太晚了！你意识到了吗？！我们现在该怎么办？！}
