#{100}{}{You see a poor man.}
{100}{}{你看到一个穷人。}
#{101}{}{You see a slum dwellers. He almost lost hope, but still holding.}
{101}{}{你看到一个贫民窟的居民。他几乎失去了希望，但仍然坚持着。}
#{102}{}{Hello}
{102}{}{你好}
#{110}{}{Hello. [coughs] Just came by or you??re here for a reason?}
{110}{}{你好。[咳嗽]刚来还是你来这是有原因的？}
#{111}{}{Not quite. I just want to know, how is the life in these slums.}
{111}{}{不完全是。我只想知道，贫民窟的生活怎么样。}
#{112}{}{Just passing through. So I better get out of here.}
{112}{}{只是路过。所以我最好离开这里。}
#{113}{}{It's shitty, as you can see. This is not the Clean City - we have no electricity, no water, the house crumbles as we speak. I don??t know, how long we can hold in such conditions.}
{113}{}{就像你看到的那样，很糟糕。这不是一个干净的城市-我们没有电，没有水，房子在我们说话的时候就倒塌了。我不知道，在这种情况下我们能坚持多久。}
#{114}{}{What is this place? Some hostel?}
{114}{}{这是什么地方？什么旅馆？}
#{115}{}{Anyone in charge here in the slums?}
{115}{}{贫民窟里有人负责吗？}
#{116}{}{Why Clean City flourishes, while you live in such conditions?}
{116}{}{为什么你生活在这样的环境中，清洁城市却欣欣向荣？}
#{117}{}{Tell me about the Kings.}
{117}{}{告诉我关于国王的事。}
#{118}{}{That is all, I wanted to know. Bye.}
{118}{}{仅此而已，我想知道。再见。}
#{119}{}{Yeah, something like that. Of course, no one will tolerate just anyone in here, but we don??t have strict demands either. People don??t stay for long anyway - they just die, other get away as far as possible.}
{119}{}{是啊，差不多吧。当然，没有人会容忍这里的任何人，但我们也没有严格的要求。不管怎样，人们不会待太久——他们只是死了，其他人会尽可能地离开。}
#{120}{}{Well, we, of course, have an intendant. But he??s more for show. In reality the kings run the slums.}
{120}{}{好吧，我们当然有个监护人。但他更喜欢作秀。实际上，国王管理着贫民窟。}
#{121}{}{Because they have money and power. And we have nothing. They didn??t made their city so clean and fixed with their own hands, but with slavery! And the likes of us they use as cheap labor force. After all, it??s impossible to find a job in the city, you have to work almost for nothing, and the Clean City takes advantage of it. Greedy and arrogant.}
{121}{}{因为他们有钱有权。我们什么都没有。他们并没有用自己的双手把自己的城市变得如此干净和固定，而是用奴隶制度！像我们这样的人被当作廉价劳动力。毕竟，在城市里找工作是不可能的，你必须白白工作，而清洁的城市会利用它。贪婪和傲慢。}
#{122}{}{These bandits don??t play around. If they told to do something, then make sure you do it with a smile. Perhaps, you will find them in other regions, they are all over the periphery. But they aren??t just a gang. They watch over everything, they get water, food, hold off other gangs, when they must. In return we must work for them. The weak are food for the strong, that??s what they say.}
{122}{}{这些强盗不会到处游荡。如果他们让你做某事，那么你一定要微笑着去做。也许，你会在其他地区发现它们，它们遍布周边地区。但他们不只是一个帮派。他们看管一切，他们得到水，食物，阻止其他帮派，当他们必须的时候。作为回报，我们必须为他们工作。弱者是强者的食物，这就是他们所说的。}
