#{100}{}{You see a dealer.}
{100}{}{你看到一个商人。}
#{101}{}{You see a man in rumpled clothes. He rubs his nose and furtively looks around.}
{101}{}{你看到一个衣衫褴褛的男人。他揉了揉鼻子，偷偷地环顾四周。}
#{102}{}{Don't even dream, nothing gets into my pockets so easily.}
{102}{}{别做梦了，没什么东西能这么容易进我的口袋。}
#{103}{}{You got a hint of the existence of a drug lab somewhere around Las Vegas.}
{103}{}{你知道拉斯维加斯附近有个毒品实验室。}
#{110}{}{Come closer, don't expose yourself. Looking to get high? I have what you need. A lot of it. Choose, if you can pay.}
{110}{}{靠近点，不要暴露自己。想兴奋吗？我有你需要的。很多。选择，如果你能付钱的话。}
#{111}{}{Bye.}
{111}{}{再见。}
#{112}{}{Wait, wait. Can I look again?}
{112}{}{等等，等等。我能再看看吗？}
#{113}{}{Show me what you've got.}
{113}{}{给我看看你有什么。}
#{114}{}{I don't need anything this time.}
{114}{}{这次我什么都不需要。}
#{115}{}{[Nods, hastily zips up his stuff gazing round] Is that all?}
{115}{}{[点点头，急忙拉上拉链，环顾四周]就这些吗？}
#{120}{}{Sorry, less goods with each day passing. Choose from what is still available. And hurry, because tomorrow there may not be anything left.}
{120}{}{对不起，货物一天比一天少。从仍然可用的内容中选择。快点，因为明天可能什么都没有了。}
#{121}{}{What happened to your stock?}
{121}{}{你的股票怎么了？}
#{122}{}{My relations came to an end, they shut up both the provider and the manufacturer at once. But you gotta hurry with the choice, look, there's another client coming.}
{122}{}{我的关系结束了，他们立刻关闭了供应商和制造商。但你得赶快做出选择，听着，又来了一个客户。}
#{123}{}{Yeah, let's make a deal.}
{123}{}{是的，我们做个交易吧。}
#{124}{}{Leave this to him the. Bye.}
{124}{}{把这个交给他。再见。}
#{130}{}{So you're the one Phillips is buying the drugs from?}
{130}{}{你就是菲利普斯买毒品的人？}
#{131}{}{[Looks surprised] Sam Phillips? Really? Is he up to his old tricks again?}
{131}{}{山姆·菲利普斯？真正地？他又耍老把戏了吗？}
#{132}{}{[Quietly turn on recording on the Pip-Boy] Is it that surprising?}
{132}{}{[悄悄地打开皮普男孩的录音]有那么令人惊讶吗？}
#{133}{}{I can see it surprises you. It means, you're not aware of the fact. Fine, worth taking note of. Bye.}
{133}{}{我看你很惊讶。意思是，你不知道事实。很好，值得注意。再见。}
#{134}{}{[Shrugs thoughtfully] People don't change. Sam had a personal problem with drugs, until he took the restoration of this cafe upon himself. Everyone thought he was done with drugs. But if this is true, I should pay him a visit.}
{134}{}{[若有所思地耸耸肩]人是不会变的。山姆个人吸毒有问题，直到他自己修复了这家咖啡馆。大家都以为他吸毒完了。但如果这是真的，我应该去拜访他。}
#{135}{}{Never mind, I'm actually here for the goods. Let me see.}
{135}{}{没关系，我其实是来拿货的。我想一下。}
#{136}{}{Looks like you don't know anything else. Okay, bye.}
{136}{}{看来你什么都不知道。好的，再见。}
#{140}{}{Where did you get the goods?}
{140}{}{你从哪儿弄来的货？}
#{141}{}{From reliable suppliers. That's all you need to know.}
{141}{}{来自可靠的供应商。你只需要知道这些。}
#{150}{}{You certainly know how to reassure the client. But it won't work with me.}
{150}{}{你当然知道如何让客户放心。但这对我没用。}
#{151}{}{You're lying! You don't have any reliable suppliers! Only dubious statements.}
{151}{}{你在撒谎！你没有可靠的供应商！只有可疑的陈述。}
#{152}{}{Actually, you're right. Let's just quietly make a deal.}
{152}{}{实际上，你是对的。我们就悄悄地做个交易吧。}
#{153}{}{Either way, I'm not buying what you're selling. Bye.}
{153}{}{不管怎样，我都不买你卖的东西。再见。}
#{154}{}{I'm not lying. My suppliers are reliable.}
{154}{}{我没有撒谎。我的供应商是可靠的。}
#{155}{}{But in our time the *clean* product can't be found anywhere. Who else but us knows it better, right?}
{155}{}{但在我们这个时代，“干净”的产品到处都找不到。除了我们还有谁更了解它，对吗？}
#{156}{}{[Grins] One just have to know where to look. Not all chemicals in the world are from before the war.}
{156}{}{一个人只要知道去哪里找就行了。世界上并非所有的化学物质都来自战前。}
#{157}{}{Wait, are you saying that there's exist an active chem manufacturer?!}
{157}{}{等等，你是说有一个活跃的化学制造商？！}
#{158}{}{Indeed. And that's all you need to know. Are you satisfied? Now you can safely choose a product. It's clean, don't worry.}
{158}{}{的确。你只需要知道这些。你满意吗？现在您可以放心地选择产品。很干净，别担心。}
#{159}{}{And yet, tell me about the manufacturer. I need to know who and where it is.}
{159}{}{但是，告诉我制造商的情况。我要知道是谁在哪里。}
#{160}{}{[Sternly] Are you out of your mind? Who tells such things to a complete stranger? I myself know very little. The production is delivered with a courier, I have never even been in the lab.}
{160}{}{你疯了吗？谁把这些事告诉一个完全陌生的人？我自己知道的很少。产品是由快递员送来的，我甚至都没去过实验室。}
#{161}{}{Of course... Of course... You see, I'm interested in chems, not as a consumer but as a chemist. I would like to contact this laboratory - there can be a vacant position for me.}
{161}{}{当然...当然...你看，我对化学感兴趣，不是作为一个消费者，而是作为一个化学家。我想和这个实验室联系-可能有一个空缺的职位给我。}
#{162}{}{[Raises an eyebrow skeptically] Well, tell me, weirdo, what do you know about methamphetamine from a scientific point of view.}
{162}{}{[怀疑地扬起眉毛]好吧，告诉我，怪人，你从科学的角度对甲基苯丙胺了解多少。}
#{163}{}{N-methyl-alpha-methylfentanyl, a derivative of amphetamine, it's a white crystalline substance, a strong psychostimulant.}
{163}{}{N-甲基-α-甲基芬太尼，安非他明的衍生物，是一种白色结晶物质，一种强烈的精神刺激剂。}
#{164}{}{Quite a surprise. But I still can't help you. Like I said, I'm supplied by a delivery courier, and I myself have never been there.}
{164}{}{真是个惊喜。但我还是帮不了你。就像我说的，我是由快递员提供的，我自己从来没有去过那里。}
#{165}{}{Well... A drug. White powder. All the junkies know that!}
{165}{}{好...毒品。白色粉末。所有的瘾君子都知道！}
#{166}{}{Go to hell! If I find out you're a cop I will shoot you where you stand.}
{166}{}{去死吧！如果我发现你是警察，我就开枪打死你。}
#{167}{}{Hey, easy!}
{167}{}{嘿，别紧张！}
#{168}{}{Maybe you know how to get in contact with them?}
{168}{}{也许你知道怎么和他们联系？}
#{169}{}{[Looks around and starts to whisper] This place is called the Pound. They say it is far from the city, in the Mojave desert. I get their products through an intermediary, communicating in advance by the radio. The callsign is "Black Caravan". It's a couple of guys who pretend to be ordinary caravan merchants, standing in the parking lot among others. You have to look for them if you want to get in contact with the Pound. Certainly, Slavertown is also connected with them, but that's only a guess.}
{169}{}{[环顾四周，开始耳语]这个地方叫英镑。他们说它远离城市，在莫哈韦沙漠。我通过一个中间人得到他们的产品，事先通过广播进行沟通。呼号是“黑商队”。这是一对假装是普通商队商人的家伙，站在停车场里。如果你想和英镑取得联系，就得去找他们。当然，Slavertown也与他们有关，但这只是猜测。}
#{170}{}{Thanks, I'll remember that. Now show me what these guys palmed off to you. Maybe I'll buy something.}
{170}{}{谢谢，我会记住的。现在让我看看这些家伙向你隐瞒了什么。也许我会买点东西。}
#{171}{}{That's good that you let all this talk slip from your tongue. Now is the time to kill you!}
{171}{}{你让这些话从你的舌头上溜走了真是太好了。现在是杀你的时候了！}
#{172}{}{This information is very useful to me. Bye.}
{172}{}{这个信息对我很有用。再见。}
#{173}{}{Right, cool story, tell me more. Where is the evidence? Where?!}
{173}{}{好吧，很酷的故事，告诉我更多。证据在哪里？哪里？！}
#{174}{}{Okay, I believe you. Let's trade.}
{174}{}{好吧，我相信你。我们交易吧。}
#{175}{}{Sure, of course. But I still won't buy anything from you.}
{175}{}{当然可以。但我还是不买你的东西。}
#{176}{}{Your words are reassuring. Show me what you've got.}
{176}{}{你的话让人放心。给我看看你有什么。}
#{177}{}{I'll refrain. Bye.}
{177}{}{我克制一下。再见。}
#{178}{}{Of course... Of Course... You see, I'm interested in chems, not as a consumer, but as...}
{178}{}{当然...当然...你看，我对化学感兴趣，不是作为消费者，而是作为...}
#{179}{}{[Furiously] Shut up, before I shoot you dead! Now get out of here.}
{179}{}{闭嘴，在我开枪打死你之前！现在离开这里。}
#{180}{}{[Attack]}
{180}{}{[攻击]}
#{181}{}{[Go away]}
{181}{}{[走开]}
#{182}{}{Well, that's enough for me. Now, let's get down to business.}
{182}{}{好吧，我受够了。现在，我们开始谈正事吧。}
#{183}{}{Anyway, still sounds not convincing. I'm leaving.}
{183}{}{不管怎样，听起来还是没有说服力。我要走了。}
#{184}{}{I'm not going to prove you anything. Do you need a dose or not?}
{184}{}{我不会证明给你看的。你需要剂量吗？}
#{185}{}{Yeah, show me what you've got.}
{185}{}{是的，让我看看你有什么。}
#{186}{}{I don't need your suspicious 'dose'. I don't need any so to speak. I'm leaving.}
{186}{}{我不需要你可疑的“剂量”。我不需要这样说。我要走了。}
#{187}{}{Do you even know how much stuff was pushed on me by the likes of you?! All them dealers never bother to understand you, they only know how to line their pockets by selling crap to the living corpses...}
{187}{}{你知道像你这样的人给了我多少压力吗？！所有的毒贩都不会费心去理解你，他们只知道如何通过向活着的尸体出售垃圾来充实自己的口袋...}
#{188}{}{Hey, take it easy, I care about my clients. You can count on me.}
{188}{}{嘿，别紧张，我关心我的客户。你可以相信我。}
#{189}{}{Really? You won't fool me? Well then, let's see what you've got.}
{189}{}{真正地？你不会骗我吧？那么，让我们看看你有什么。}
#{190}{}{Don't lie to me! I see through you. And so I'll just leave.}
{190}{}{别骗我！我看穿了你。所以我就走了。}
#{191}{}{Right. Everyone says so, but I don't intend to die from taking what you cook!}
{191}{}{正确的。每个人都这么说，但我不想因为吃了你做的东西而死！}
#{192}{}{[Looks intently] You don't look like a drug addict. You work for whom? For the cops? Stay away from me!}
{192}{}{你看起来不像个瘾君子。你为谁工作？为了警察？离我远点！}
#{193}{}{[Leave]}
{193}{}{[离开]}
#{194}{}{[Looks intently] I see, you seem to have a serious problem with drugs. Even if I give you what you want It won't save you.}
{194}{}{我明白了，你似乎有严重的毒品问题。即使我给你你想要的也救不了你。}
#{195}{}{Huh?}
{195}{}{嗯？}
#{196}{}{You, addicts, are all hopeless... Although, I know how to help you.}
{196}{}{你们这些瘾君子都没希望了...不过，我知道怎么帮你。}
#{197}{}{I know your kind too well but, I guess, listening won't hurt anyway.}
{197}{}{我太了解你这种人了，不过，我想，听着也不会有什么坏处。}
#{198}{}{You may help only if you give me something to relieve the addiction. Show me what you're selling.}
{198}{}{你只要给我点东西解药就可以帮我了。给我看看你在卖什么。}
#{199}{}{I don't need your help. Will work something out without you.}
{199}{}{我不需要你的帮助。没有你会有办法的。}
#{200}{}{You may help only if you tell me where the lab is. I want to get THE purest drug!}
{200}{}{只要你告诉我实验室在哪里，你就可以帮忙。我要买最纯的药！}
#{201}{}{You need to contact the supplier. Sometimes they look for drug addicts. You will be glad to participate, I think.}
{201}{}{你需要联系供应商。有时他们会找瘾君子。我想你会很乐意参加的。}
#{202}{}{Hmm. Curious. Tell me more.}
{202}{}{嗯。好奇。告诉我更多。}
#{203}{}{If only I could count solely on myself and my skepticism. You are too good with the words.}
{203}{}{要是我能完全依靠我自己和我的怀疑就好了。你太会说话了。}
#{500}{}{Look who it is! Drop in, maybe something will interest you?}
{500}{}{看看是谁！顺便来看看，也许你会感兴趣？}
#{501}{}{Hey, I have a sweet candy for the brain!}
{501}{}{嘿，我有一个甜糖果给大脑！}
#{502}{}{Can give a discount, come here!}
{502}{}{可以打折，过来！}
#{503}{}{::whistles::}
{503}{}{●口哨声：}
#{504}{}{There's nothing better than taking a dose after a hard day. Am I right?}
{504}{}{没有什么比在辛苦一天后吃一剂更好的了。我说得对吗？}
#{505}{}{I have something that will allow you to kiss the sky!}
{505}{}{我有东西可以让你亲吻天空！}
#{506}{}{Oh... From which lands are you from?}
{506}{}{哦...你来自哪个国家？}
#{507}{}{I'll give you a discount on ALL of my stuff.}
{507}{}{我所有的东西都给你打折。}
#{508}{}{I know what you are looking for and I have it. As much as you NEED.}
{508}{}{我知道你在找什么，我有。你需要多少就多少。}
#{509}{}{Why walk when you can *fly*?}
{509}{}{既然能飞，为什么还要走路？}
#{510}{}{I have the purest product in the city, mind you.}
{510}{}{请注意，我有城里最纯的产品。}
#{511}{}{You wanna fly? You have money? So *I'm* the one you need.}
{511}{}{你想飞吗？你有钱吗？所以我就是你需要的人。}
#{512}{}{Wanna fly to a place where only the gods can be? I will help you!}
{512}{}{想飞到一个只有神的地方吗？我会帮助你的！}
#{513}{}{I have stuff, and more stuff. Let's talk.}
{513}{}{我有东西，还有更多的东西。我们谈谈。}
#{1158}{}{Indeed. And that's all you need to know. Are you satisfied? Now you can safely choose a product. It's clean, don't worry.}
{1158}{}{的确。你只需要知道这些。你满意吗？现在您可以放心地选择产品。很干净，别担心。}
#{1192}{}{[Looks intently] You don't look like a drug addict. You work for whom? For the cops? Stay away from me!}
{1192}{}{你看起来不像个瘾君子。你为谁工作？为了警察？离我远点！}
