#{100}{}{You see Richard Pryor.}
{100}{}{你看到理查德·普赖尔了。}
#{101}{}{You see a comedian with a bushy mustache and gambling glance. He lets everyone know with only his looks - anything can be expected from him.}
{101}{}{你看到一个留着浓密胡子和赌气眼神的喜剧演员。他让每个人都知道只有他的外表-任何事情都可以期待从他。}
#{102}{}{All the paparazzi leave my house! I don't give out autographs today.}
{102}{}{所有的狗仔队都离开我家！我今天不发签名。}
#{103}{}{No-oo! I have not yet finished my tour around Nevada!}
{103}{}{不，哦！我还没游完内华达州呢！}
#{104}{}{Now, when I'm standing on the stage with one leg, I can stick the other one into the Clean City's ass, and take it out through the mouth. Can you imagine how it's like!?}
{104}{}{现在，当我用一条腿站在舞台上时，我可以把另一条腿插进清洁城市的屁股里，然后用嘴把它拿出来。你能想象它是什么样子吗！？}
#{105}{}{Wild verbal itching with an abundance of vulgarity makes you constantly distracted. Because of this, you may have serious problems.}
{105}{}{狂野的语言瘙痒和大量的粗俗使你不断分心。因此，你可能会有严重的问题。}
#{106}{}{While Pryor is with you, your luck will be reduced by }
{106}{}{普赖尔和你在一起时，你的运气会减少}
#{107}{}{.}
{107}{}{.}
#{108}{}{Freed from the comedian, you feel an incredible peace in the head.}
{108}{}{摆脱了喜剧演员的束缚，你会感到头脑里无比平静。}
#{110}{}{What the gecko are we doing here?!}
{110}{}{我们在这干什么？！}
#{111}{}{ }
{111}{}{ }
#{112}{}{ }
{112}{}{ }
#{113}{}{ }
{113}{}{ }
#{114}{}{ }
{114}{}{ }
#{115}{}{ }
{115}{}{ }
#{140}{}{Ah, I stepped on a thorn!}
{140}{}{啊，我踩到一根刺了！}
#{141}{}{Ouch}
{141}{}{哎哟}
#{142}{}{Better look for *your* balls}
{142}{}{最好找你的球}
#{143}{}{Easy! I'm special.}
{143}{}{容易的！我很特别。}
#{144}{}{Push me harder. I don't mind, if you know what I mean.}
{144}{}{用力推我。我不介意，如果你知道我的意思。}
#{145}{}{Your hands are moist. Care to scrub my back?}
{145}{}{你的手是湿的。要不要擦洗我的背？}
#{150}{}{Hey, why are you *wandering* around so much?.. Aha-ha! Nice one!}
{150}{}{嘿，你为什么这么到处闲逛？。。啊哈！不错！}
#{151}{}{Time to move. Let's go.}
{151}{}{是时候行动了。走吧。}
#{152}{}{Don't say another word.}
{152}{}{别再说了。}
#{153}{}{...And I ask him - hey, is this Reno? And he says...}
{153}{}{…我问他-嘿，这是雷诺吗？他说...}
#{154}{}{You will have to wait me here.}
{154}{}{你得在这儿等我。}
#{155}{}{Let's go. Reno awaits us.}
{155}{}{走吧。雷诺在等我们。}
#{156}{}{Don't say another word.}
{156}{}{别再说了。}
#{200}{}{Fans, fans... You didn't bring paparazzi with you, did you? Good enough.}
{200}{}{粉丝们，粉丝们...你没带狗仔队，是吗？够好了。}
#{201}{}{So it's you I have to accompany to the Reno's stage?}
{201}{}{所以我要陪你去雷诺的舞台？}
#{202}{}{I didn't need you! I don't even want to talk to you.}
{202}{}{我不需要你！我甚至不想和你说话。}
#{203}{}{Reno's stage is calling for me, baby! But you are... By yourself... Didn't they have a security escort, or, at least, a stagecoach? Okay, okay, I'm going now, if it is time to.}
{203}{}{雷诺的舞台在召唤我，宝贝！但你是...你一个人...他们不是有保安护送，或者至少有驿站马车吗？好吧，好吧，我现在就走，如果是时候的话。}
#{204}{}{Let's go.}
{204}{}{走吧。}
#{205}{}{Wait, I should prepare for departing.}
{205}{}{等等，我要准备出发了。}
#{210}{}{How would I put it mildly... The thing is, the club's owner died and now you're out of work.}
{210}{}{我该怎么委婉地说...问题是，俱乐部的老板死了，现在你失业了。}
#{211}{}{What the fuck am I doing here then!? [looks around in confusion] What a shithole! [Sees homeless men around the barrel] Hey, guys! Want some company?.. [Goes to them and gets lost in the crowd, then a collective laughter is heard in the distance, eventually falling silent.]}
{211}{}{那我他妈的在这里干什么！？[困惑地环顾四周]真是个混蛋！嘿，伙计们！有人陪吗？。。[走近他们，在人群中迷路，然后远处传来集体笑声，最终沉寂。]}
#{212}{}{Well, apparently, we won't see each other again, Richard Pryor.}
{212}{}{显然，我们不会再见面了，理查德·普赖尔。}
#{213}{}{Go fuck yourself, piece of shit!}
{213}{}{去你妈的，混蛋！}
#{250}{}{Tell me about your work.}
{250}{}{告诉我你的工作。}
#{251}{}{Look, I'm funny. People laugh at my jokes, like a crowd of morons. I was born for this. However, Vegas is already tired of me, so I stopped performing here. But I still have to eat, so I decided to try my luck in Reno.}
{251}{}{听着，我很有趣。人们对我的笑话一笑置之，就像一群白痴。我生来就是为了这个。然而，维加斯已经厌倦了我，所以我不再在这里表演了。但我还是要吃饭，所以我决定在雷诺碰碰运气。}
#{252}{}{You don't talk like a comedian right now...}
{252}{}{你现在说话不像个喜剧演员...}
#{253}{}{Fine.}
{253}{}{好的。}
#{254}{}{Well... You know, I have some heavy shit on my heart. I tell something important to people - and they don't listen. They think it's just a joke. But they listen to *you*. Because you're serious, even though you don't have much to say. You know what I'm saying?}
{254}{}{好...你知道吗，我心里有点烦。我告诉人们一些重要的事情-他们不听。他们认为这只是个玩笑。但他们听你的。因为你是认真的，尽管你没什么好说的。你知道我在说什么吗？}
#{255}{}{And what would you tell to people in Reno?}
{255}{}{你会对里诺的人说什么？}
#{256}{}{Just the same crap, I think. Nobody takes me seriously anyway. Besides, I can't do anything else. After all this fun on big stages for years, I can't just go back to something like digging through brahmin shit, you know what I'm saying?}
{256}{}{我想还是一样。反正没人把我当回事。再说了，我什么也做不了。在大舞台上玩了这么多年之后，我不能再回到像挖掘双头牛的东西上，你知道我在说什么吗？}
#{300}{}{What the fuck am I doing here!?}
{300}{}{我他妈的在这里干什么！？}
#{301}{}{See No Evil, Hear No Evil}
{301}{}{不见恶，不闻恶}
#{302}{}{Dedicated to all those who took care of my cocaine}
{302}{}{献给所有照顾我可卡因的人}
#{303}{}{Good days, bad days... But I still am a talkin' motherfucker!}
{303}{}{好日子，坏日子...但我还是个会说话的混蛋！}
#{304}{}{Do you remember that dry fucking season 20 years ago? I survived through that shit...}
{304}{}{你还记得20年前的那个旱季吗？我挺过来了...}
#{305}{}{The first time, when I came, I fucking shit my pants, dude!}
{305}{}{第一次，我来的时候，我他妈的尿裤子了，伙计！}
#{306}{}{And everybody starts asking: what is it?! It's Richard Pryor running down the street!}
{306}{}{每个人都开始问：这是什么？！理查德·普赖尔在街上跑！}
#{307}{}{I thought, this is because of the straight hair. While they are like this, the white bully me around. And I burned them.}
{307}{}{我想，这是因为直发。当他们这样的时候，白人欺负我。我把它们烧了。}
#{308}{}{Let me zipper up, if I'm performing before an audience.}
{308}{}{如果我在观众面前表演，让我拉上拉链。}
#{309}{}{60 years ago you could fuck no one, because every girl had a sickness called "virginity"}
{309}{}{60年前你不能和任何人上床，因为每个女孩都有一种叫做“处女”的疾病}
#{310}{}{Being black is cool. 'Cause being white is not cool.}
{310}{}{黑色很酷因为变白并不酷。}
#{311}{}{Kiss my black ass!}
{311}{}{亲我的黑屁股！}
#{312}{}{Did you know, that one million bucks weights 2204,6 pounds?}
{312}{}{你知道吗，那一百万块重2204,6磅？}
#{313}{}{What is it: a cross on cross? it's a pope on a nurse.}
{313}{}{它是什么：十字架上的十字架？是一个护士的教宗。}
#{1200}{}{Fans, fans... You didn't bring paparazzi with you, did you? Good enough.}
{1200}{}{粉丝们，粉丝们...你没带狗仔队，是吗？够好了。}
#{1254}{}{Well... You know, I have some heavy shit on my heart. I tell something important to people - and they don't listen. They think it's just a joke. But they listen to *you*. Because you're serious, even though you don't have much to say. You know what I'm saying?}
{1254}{}{好...你知道吗，我心里有点烦。我告诉人们一些重要的事情-他们不听。他们认为这只是个玩笑。但他们听你的。因为你是认真的，尽管你没什么好说的。你知道我在说什么吗？}
