#{100}{}{You see a gambler.}
{100}{}{你看到一个赌徒。}
#{101}{}{You see a gambler, excitedly waving his hands to the beat of running geckos.}
{101}{}{你看到一个赌徒，兴奋地挥舞着他的手，以运行壁虎的节拍。}
#{110}{}{Come on! Come on!}
{110}{}{加油！加油！}
#{111}{}{Bring me the money, geckos!}
{111}{}{把钱给我，壁虎！}
#{112}{}{Toki, forward!}
{112}{}{托克，向前！}
#{113}{}{Please! Please!}
{113}{}{拜托！拜托！}
#{114}{}{Damn!}
{114}{}{该死！}
#{115}{}{Go!}
{115}{}{快走！}
#{116}{}{What a race!}
{116}{}{多精彩的比赛啊！}
#{117}{}{Will this one win?!}
{117}{}{这个能赢吗？！}
#{118}{}{What?! Red is leading?!}
{118}{}{什么？！瑞德领先？！}
#{119}{}{Too slow!}
{119}{}{太慢了！}
#{120}{}{Too fast!}
{120}{}{太快了！}
