#{100}{}{You see a stranger.}
{100}{}{你看到一个陌生人。}
#{101}{}{You see Maxson.}
{101}{}{你看到麦克森了。}
#{102}{}{You see a stranger, looking... Familiar. He reminds you someone.}
{102}{}{你看到一个陌生人，看着...熟悉。他提醒你有人。}
#{103}{}{It's Bald Maxson from Big Louie's gang! It's him, for sure!}
{103}{}{是大路易帮派的秃头麦克森！肯定是他！}
#{104}{}{Big Louie's dirty business is done. You get 1000 experience points.}
{104}{}{大路易的肮脏勾当结束了。你得到1000点经验值。}
#{105}{}{You found Maxson. So that's where he laid down after New Reno!}
{105}{}{你找到麦克森了。那就是他在新雷诺之后躺下的地方！}
#{110}{}{Huh? What? [looks at you and then quickly turns away] I do not communicate with clients, sorry. All questions to the administrators.}
{110}{}{呵呵？什么？[看着你然后迅速转身离开]对不起，我不和客户交流。所有问题都交给管理员。}
#{111}{}{Huh? What? [looks at you and then quickly turns away] Okay, all questions to the administrators. And I??ll ask you to leave my office.}
{111}{}{呵呵？什么？[看着你然后快速转身]好的，所有问题都交给管理员。我请你离开我的办公室。}
#{112}{}{If you??re not an administrator, who are you then?}
{112}{}{如果你不是管理员，那你是谁？}
#{113}{}{Fine, I'll leave you alone.}
{113}{}{好吧，我不打扰你了。}
#{114}{}{I don??t work with clients in this... [He looks and you suddenly pulls himself together]... Dammit! Didn??t you hear me? You want me to call security? I repeat - I don??t talk to clients, I??ll ask you to leave my office.}
{114}{}{我不跟客户合作...[他看着你突然振作起来]...该死！你没听见吗？你要我叫保安吗？我再说一遍-我不跟客户说话，我会让你离开我的办公室。}
#{115}{}{I don??t work with clients in this... [He looks and you suddenly pulls himself together]... Dammit! Didn??t you hear me? You want me to call security? I repeat - I don??t talk to clients, I??ll ask you to leave me alone.}
{115}{}{我不跟客户合作...[他看着你突然振作起来]...该死！你没听见吗？你要我叫保安吗？我再说一遍-我不跟客户说话，我会让你离我远点。}
#{116}{}{Wait, why reacting like this? What is the problem?}
{116}{}{等等，为什么这样反应？有什么问题？}
#{117}{}{Okay-okay, I'll leave you alone.}
{117}{}{好吧，我不打扰你了。}
#{118}{}{Okay, let??s get this over with. Right here right now! This is what you want, do you?}
{118}{}{好吧，让我们结束这一切。现在就在这里！这就是你想要的，是吗？}
#{119}{}{Okay prepare yourself, scum! You asked for it! [attack]}
{119}{}{好了，准备好，人渣！你自找的！[攻击]}
#{120}{}{No, I don??t want any trouble, I??ll leave peacefully.}
{120}{}{不，我不想惹麻烦，我会平静地离开。}
#{121}{}{Wait, I remember you...}
{121}{}{等等，我记得你...}
#{122}{}{What, finally got it? Yes, it is me! A dirty raider from a paranoid bastard's gang in the past, but now totally different person - a respectable citizen with the prestigious work in downtown Vegas. Isn??t that surprising, huh?}
{122}{}{什么，终于明白了？是的，是我！过去是一个偏执的混蛋团伙的肮脏袭击者，但现在完全不同了——一个在维加斯市中心工作的受人尊敬的公民。这不奇怪吗？}
#{123}{}{But... How?!}
{123}{}{但是...怎样？！}
#{124}{}{Doesn??t matter. It??s time to pay, baldy. Die!}
{124}{}{没关系。该付钱了，秃头。去死吧！}
#{125}{}{The skills of the local surgeon, the fees of my new boss and my personal ability to create real miracles. Now I am a different person, forget about me. Otherwise you won??t get out of this casino.}
{125}{}{当地外科医生的技能，我新老板的费用，以及我创造真正奇迹的个人能力。现在我是另一个人了，忘了我吧。否则你就出不了这个赌场。}
#{126}{}{You think, I??m scared? Well, okay, show me what you got! [attack]}
{126}{}{你觉得我害怕吗？好吧，让我看看你有什么！[攻击]}
#{127}{}{Okay, Maxson, I won??t bother you. Calm down.}
{127}{}{好吧，麦克森，我不会打扰你的。冷静。}
#{130}{}{You??re asking for it!}
{130}{}{你自找的！}
#{131}{}{Brothers! Someone is asking for it here!}
{131}{}{兄弟！有人在这里要！}
#{132}{}{Hey, guys! Throw him outside!}
{132}{}{嘿，伙计们！把他扔出去！}
#{133}{}{Stay away from me, you got that?!}
{133}{}{离我远点，明白吗？！}
#{134}{}{What?! You??re asking for it again?!}
{134}{}{什么？！你又问我了？！}
#{135}{}{You want to catch a bullet, huh?! Okay then!}
{135}{}{你想挨子弹吗？！那好吧！}
#{150}{}{I don??t work with clients in this... [He looks and you suddenly pulls himself together]... Dammit! Well who do I see! I didn??t expect to meet my friends in this part of Nevada. How did you get here, fuck me gecko?!}
{150}{}{我不跟客户合作...[他看着你突然振作起来]...该死！我看见谁了！我没想到会在内华达州的这个地方见到我的朋友。你怎么来的，操我的壁虎？！}
#{151}{}{Maxson... You managed to get to Vegas.}
{151}{}{麦克森...你设法去了维加斯。}
#{152}{}{Yes, it??s me. A dirty raider from a paranoid bastard's gang in the past, but now totally different person - a respectable citizen with the prestigious work in downtown Vegas. Isn??t that surprising, huh?}
{152}{}{是的，是我。过去是一个偏执的混蛋团伙的肮脏袭击者，但现在完全不同了——一个在维加斯市中心工作的受人尊敬的公民。这不奇怪吗？}
#{153}{}{How did you managed to change your appearance?}
{153}{}{你是怎么改变你的外表的？}
#{154}{}{How did you get here?}
{154}{}{你怎么来的？}
#{155}{}{Now you work for the casino?}
{155}{}{现在你在赌场工作？}
#{156}{}{I was glad to see you, but I have to go.}
{156}{}{很高兴见到你，但我得走了。}
#{157}{}{The skills of the local surgeon, the fees of my new boss and my personal ability to create real miracles. Not much - just changed my hairstyle and did a surgery on my nose. That was enough to make anybody from the past not recognize me.}
{157}{}{当地外科医生的技能，我新老板的费用，以及我创造真正奇迹的个人能力。没什么-只是换了个发型，做了个鼻子手术。这足以让过去的人认不出我。}
#{158}{}{What surgeon?}
{158}{}{什么外科医生？}
#{159}{}{Who is your boss now?}
{159}{}{你现在的老板是谁？}
#{160}{}{With stagecoach, obviously. Only with these guys one can safely move along the Great Nevada ring to the other side.}
{160}{}{显然，是用驿站马车。只有这些人才能安全地沿着内华达大环移动到另一边。}
#{161}{}{Not exactly in the casino, more likely for Hal Wallace personally. Don??t ask. Otherwise I will have to kill you. Joking.}
{161}{}{不是在赌场，更可能是哈尔·华莱士本人。别问了。否则我就杀了你。开玩笑。}
#{162}{}{Rob Reiner? He sits down in the underground. No idea how to contact him. I was taken to his laboratory at night, blindfolded, and brought and I was sedated after surgery.}
{162}{}{罗伯雷纳？他坐在地下室里。不知道怎么联系他。我晚上被带到他的实验室，蒙上眼睛，然后被带到医院，手术后我被注射了镇静剂。}
#{163}{}{Hal Wallace, who else? He owns the casino and has... Some other business in the city. Very powerful man, someone you should stay friendly, trust me.}
{163}{}{哈尔·华莱士，还有谁？他拥有赌场而且...城里还有别的生意。很有权势的人，你应该对他保持友好，相信我。}
#{164}{}{Until recently it was Hal Wallace... But his assistants are still in the casino, so the work is still going on without him.}
{164}{}{直到最近还是哈尔·华莱士...但是他的助手还在赌场里，所以工作还没有他。}
#{165}{}{I want to work for him too! Can you recommend me?}
{165}{}{我也想为他工作！你能推荐我吗？}
#{166}{}{Hmm... I don??t know, how much my word means to my boss, but I can try. Talk to his main guard and tell him, that Maxson sent you. Perhaps he will listen.}
{166}{}{Hmm...我不知道，我的话对老板有多重要，但我可以试试。跟他的警卫说，麦克森派你来的。也许他会听。}
#{167}{}{Thanks, Maxson.}
{167}{}{谢谢，麦克森。}
#{168}{}{What??s up, old pal. What is it now?}
{168}{}{怎么了，老朋友。现在怎么了？}
#{169}{}{You know the news about big Louie?}
{169}{}{你知道大路易的消息吗？}
#{170}{}{That he abandoned the gang and performs in the "Hard Rock"? Yes, I heard. I will have to stay in the Clean City for some time.}
{170}{}{他抛弃了帮派在“硬石”里表演？是的，我听说了。我将不得不在清洁的城市呆一段时间。}
#{171}{}{Aren??t you surprised?}
{171}{}{你不感到惊讶吗？}
#{172}{}{Honestly? I knew he's weak. He was forced to be a raider, but he always dreamed to be a musician.}
{172}{}{说真的？我知道他很虚弱。他被迫成为一名袭击者，但他一直梦想成为一名音乐家。}
#{1130}{}{You??re asking for it!}
{1130}{}{你自找的！}
#{1131}{}{Brothers! Someone is asking for it here!}
{1131}{}{兄弟！有人在这里要！}
#{1132}{}{Hey, guys! Throw her outside!}
{1132}{}{嘿，伙计们！把她扔出去！}
#{1133}{}{Stay away from me, you got that?!}
{1133}{}{离我远点，明白吗？！}
#{1134}{}{What?! You??re asking for it again?!}
{1134}{}{什么？！你又问我了？！}
#{1135}{}{You want to catch a bullet, huh?! Okay then!}
{1135}{}{你想挨子弹吗？！那好吧！}
#{1168}{}{What??s up, gal. What is it now?}
{1168}{}{怎么了，姑娘。现在怎么了？}
