#{100}{}{You see the minister of culture.}
{100}{}{你看到文化部长了。}
#{101}{}{You see a smart City Hall employee. Judging by the badge, he is holding the position of the minister of culture.}
{101}{}{你看到一个聪明的市政厅职员。从徽章上看，他是文化部长。}
#{110}{}{What is it about?}
{110}{}{是关于什么的？}
#{111}{}{Oh, I have a lot of questions. Can you help me answer them?}
{111}{}{哦，我有很多问题。你能帮我回答吗？}
#{112}{}{It depends on your position. Are you the minister of culture? What does that mean?}
{112}{}{这取决于你的位置。你是文化部长吗？那是什么意思？}
#{113}{}{I don??t have any questions. See you.}
{113}{}{我没有任何问题。再见。}
#{114}{}{This means, that I am - the minister of culture, and you are - the foolish child of the wastes. Explaining to you what "culture" means is pointless to me, sorry.}
{114}{}{这意味着，我是文化部长，而你是废物中愚蠢的孩子。向你解释“文化”的含义对我来说毫无意义，对不起。}
#{115}{}{Still - be nice to clear at least something.}
{115}{}{不过，至少要清楚一些事情。}
#{116}{}{In that case we have nothing to talk about.}
{116}{}{那样的话我们就没什么好谈的了。}
#{117}{}{[Nervously sighs] My work is to develop and preserve all the cultural norms of the Clean City. My department assesses how the city should look and sound, but the main thing - how the locals should improve their intellectual abilities. It will be difficult for you to understand.}
{117}{}{[紧张地叹息]我的工作是发展和维护清洁城市的所有文化规范。我所在的部门评估了这个城市的外观和声音，但最重要的是当地人应该如何提高他们的智力。你很难理解。}
#{118}{}{It seems you??re of a bad opinion on people living outside the city.}
{118}{}{看来你对住在城外的人不好。}
#{119}{}{What are you saying!? There are a lot of talented and knowledgeable people beyond the walls of the Clean City. Like me, for example.}
{119}{}{你在说什么！？在清洁城市的城墙外，有许多有才华和知识的人。比如我。}
#{120}{}{The situation is clear. Perhaps now you'll be able to answer some questions?}
{120}{}{情况很清楚。也许现在你能回答一些问题了？}
#{121}{}{Yes, I think this information is enough for my brain. See you.}
{121}{}{是的，我想这些信息对我的大脑来说已经足够了。再见。}
#{122}{}{[Slyly grinning] What are YOU saying?! I'm actually of good opinion on the inhabitants of the Wasteland. You just have to wash them, dress, give each one of them a book, teach them some good manners - and here you have an army of decent people. The question is - how long this decency will last?}
{122}{}{你在说什么？！事实上，我对这片荒地的居民很有好感。你只需要给他们洗衣服，给他们每人一本书，教他们一些礼貌——在这里你有一大群正派的人。问题是-这种体面会持续多久？}
#{123}{}{I won??t argue with you. Outside the walls there is really a heck of a pitiful and miserable life.}
{123}{}{我不会和你争论的。墙外真是一片凄惨凄惨的生活。}
#{124}{}{With such snobbery, nothing but discrimination can be expected from you.}
{124}{}{有了这样的势利，你只会受到歧视。}
#{125}{}{I have every reason to believe that you have very little knowledge of the world, and that you fell victim of your own delusions. I am the direct proof of that.}
{125}{}{我有充分的理由相信你对这个世界知之甚少，你成为自己妄想的牺牲品。我就是直接的证据。}
#{126}{}{Let's leave this discussion on that.}
{126}{}{让我们把讨论的重点放在这个问题上。}
#{127}{}{I don??t understand - are you trying to impress me, or are you out of this world yourself? Although, given the contrast between the Clean City and the periphery, your point of view of our city is quite understandable.}
{127}{}{我不明白-你是想给我留下深刻印象，还是你自己离开了这个世界？尽管如此，鉴于清洁城市和周边地区的对比，你对我们城市的看法还是可以理解的。}
#{128}{}{No, I??m talking not about that! You know, all these bandits on the streets of Reno, wild ghouls, raiders, crazy idiots - I happened to see a lot during my journey.}
{128}{}{不，我不是在说那个！你知道吗，里诺街头的强盗，野食鬼，袭击者，疯狂的白痴——我在旅途中碰巧看到了很多。}
#{129}{}{Be careful, youngster! Do you have any idea how much work is invested in the reconstruction of this area?! For ten years we tried to establish a decent living here, with joined effort. And now any outcomer scum is capable of talking garbage here. But, in any case, I don??t have the mood to prove anything to you. *You* come here and distract me from my work with your pointless conversations.}
{129}{}{小心点，年轻人！你知道这个地区的重建投资了多少吗？！十年来，我们共同努力，努力在这里过上体面的生活。现在任何外来的人渣都能在这里说废话。但是，无论如何，我没有心情向你证明任何事情。*你到这里来，用你那些毫无意义的谈话来分散我对工作的注意力。}
#{130}{}{You don??t look like a caravaneer, or a representative of "Nevada express". This conversation is already becoming pointless.}
{130}{}{你看起来不像一个大篷车司机，或者“内华达快车”的代表。这种对话已经变得毫无意义了。}
#{131}{}{Perhaps, in this case, you can answer a few questions?}
{131}{}{也许，在这种情况下，你能回答几个问题吗？}
#{132}{}{Did you really acquire such rich experience from your travels? How interesting... I would like to discuss with you the life of people in other cities. You don??t mind, do you?}
{132}{}{你真的从旅行中获得了如此丰富的经验吗？真有趣...我想和你谈谈其他城市人们的生活。你不介意吧？}
#{133}{}{Oh, sure, with pleasure!}
{133}{}{哦，当然，很荣幸！}
#{134}{}{I don??t have time for this right now. Perhaps, another time.}
{134}{}{我现在没有时间做这个。也许，下次吧。}
#{135}{}{There can be no other time. But you've already decided, so let??s leave it at that. Is that all you wanted?}
{135}{}{没有别的时间了。但你已经决定了，就这样吧。这就是你想要的吗？}
#{136}{}{No, I had more questions about the Clean City and City Hall.}
{136}{}{不，我有更多关于清洁城市和市政厅的问题。}
#{137}{}{Yes, it??s time for me to go. Take care.}
{137}{}{是的，我该走了。当心。}
#{138}{}{Excellent. Every day I'm having dinner at the casino across the street. Meet me there, so we can talk in more cultural atmosphere.}
{138}{}{杰出的。每天我都在街对面的赌场吃晚饭。在那里等我，这样我们可以在更具文化氛围的地方交谈。}
#{139}{}{I will remember that. And now - could you answer some more questions about the city?}
{139}{}{我会记住的。现在-你能回答更多关于这个城市的问题吗？}
#{140}{}{See you.}
{140}{}{再见。}
#{141}{}{Oh no, you won??t fool me. You don??t shine in erudition department, that??s for sure.}
{141}{}{哦，不，你骗不了我。你在博学系里肯定不光彩。}
#{142}{}{What arrogance... But maybe I??m little off sometimes. I didn't make a single step out of Clean City for ten years. Perhaps, some things changed during that time, but I highly doubt it. You are going to say that the life became better outside, aren't you?}
{142}{}{多么傲慢...但也许我有时候有点不舒服。十年来我一步也没走出清洁城市。也许，在那期间有些事情发生了变化，但我对此深表怀疑。你会说外面的生活变好了，是吗？}
#{143}{}{Ten years - it??s a period of Great depression. Ages. You know, things are going better in New Reno recently, and a number of new settlements rise around the federal highways... The world is changing, you should take a closer look.}
{143}{}{十年——这是大萧条时期。年龄。你知道，最近新里诺的情况有所好转，联邦高速公路周围出现了许多新的定居点...世界在变，你应该仔细看看。}
#{144}{}{Great depression... Now, stop. This is from history. Aren??t you a little well-educated for a wastelander?}
{144}{}{大萧条...现在，停下来。这是来自历史。作为一个荒原人，你不是受过一点良好的教育吗？}
#{145}{}{I??m just interested in studying. But how do you manage to keep the craving for cultural development in these conditions?}
{145}{}{我只是对学习感兴趣。但是，在这种情况下，你如何保持对文化发展的渴望呢？}
#{146}{}{My God! Who am I talking to? Listen, it??s actually not that simple. For many years I'm trying to establish a culturally educational program here, but I constantly come across a misunderstanding on the part of other members of the mayor's office. For them, to bring direct benefits, like trade, rent, entertainment business, electricity and everything on what you can speculate on - is more important. A few can appreciate my ambitions. Fortunately, the Mayor allowed me to establish this department, though we have a low budget.}
{146}{}{天哪！我在和谁说话？听着，其实没那么简单。多年来，我一直试图在这里建立一个文化教育项目，但我经常遇到市长办公室其他成员的误解。对他们来说，带来直接的利益，比如贸易、租金、娱乐业、电力和一切你可以投机的东西——更重要。有几个人能欣赏我的雄心壮志。幸运的是，市长允许我建立这个部门，尽管我们的预算很低。}
#{147}{}{So, you??re having hard times here. Perhaps, I should think about this a little. Good bye.}
{147}{}{所以，你在这里的日子不好过。也许，我应该考虑一下。再见。}
#{148}{}{You proved the snob that outside the city walls exist some clever people.}
{148}{}{你向势利小人证明了城墙外有一些聪明人。}
#{149}{}{Great, but I would like to ask a few questions, not answer them.}
{149}{}{很好，但是我想问几个问题，而不是回答。}
#{150}{}{[Restrains the charity behind arrogant smile] Your curiosity is certainly worthy of respect, but I have no time for pointless talk.}
{150}{}{[克制傲慢微笑背后的慈善]你的好奇心当然值得尊重，但我没有时间进行毫无意义的谈话。}
#{151}{}{With pleasure, but I have little time for small talk.}
{151}{}{很高兴，但我几乎没有时间闲聊。}
#{152}{}{I'll pretend I didn??t hear that, but other members of the Clean City would not. Many are proud to live here. Do you even understand, how much work has been invested in the reconstruction of this area?! For ten years we tried to establish a decent living here, with joined effort. It??s hard for outcomers to understand, they think that the locals just had everything from the beginning.}
{152}{}{我假装没听到，但清洁城市的其他成员不会。许多人以住在这里为荣。你知道吗，这个地区的重建投入了多少工作？！十年来，我们共同努力，努力在这里过上体面的生活。外地人很难理解，他们认为当地人从一开始就拥有一切。}
#{153}{}{Even if you have great experience, I would prefer to look into more reliable sources.}
{153}{}{即使你有丰富的经验，我更愿意寻找更可靠的来源。}
#{154}{}{I am the minister of culture, not your drinking buddy in a bar! I won??t answer any questions.}
{154}{}{我是文化部长，不是你酒吧里的酒友！我不回答任何问题。}
#{155}{}{You respond too emotionally to a simple question. Do you hate my company?}
{155}{}{你对一个简单的问题反应太情绪化了。你讨厌我的公司吗？}
#{156}{}{Let's talk about your office, the minister of culture office.}
{156}{}{我们来谈谈你的办公室，文化部长办公室。}
#{157}{}{Yes, exactly. I don??t see in you the qualities that I appreciate in others. Besides, I??m not obliged to communicate with you. There is a secretary for this.}
{157}{}{是的，没错。我看不出你身上有我欣赏别人的品质。另外，我没有义务和你交流。这里有个秘书。}
#{158}{}{Fine, I??m leaving.}
{158}{}{好吧，我要走了。}
#{159}{}{Too bad you treat me this way. I bring profits to Vegas...}
{159}{}{你这样对我太可惜了。我把利润带到维加斯...}
#{160}{}{Tell me about the history of the Clean City. How did you manage to restore all this?}
{160}{}{告诉我清洁城市的历史。你是怎么恢复这一切的？}
#{161}{}{Why is there so much discrimination toward outsiders?}
{161}{}{为什么对外人有这么多歧视？}
#{162}{}{In our time, the police and the mayor's office are unusual thing in cities. Will you be able to keep the order?}
{162}{}{在我们这个时代，警察和市长办公室在城市里是不寻常的事情。你能维持秩序吗？}
#{163}{}{Tell me about your department. How is it different from the rest?}
{163}{}{告诉我你所在部门的情况。它和其他的有什么不同？}
#{164}{}{Tell me about your mayor.}
{164}{}{跟我说说你的市长。}
#{167}{}{Another question please.}
{167}{}{请再问一个问题。}
#{168}{}{What do you want to know?}
{168}{}{你想知道什么？}
#{169}{}{We have already clarified a lot. Let??s stop at that.}
{169}{}{我们已经澄清了很多。我们就到此为止吧。}
#{170}{}{Ten years of hard work. At first, the boulevard was nothing but the same boring and uncrowded neighborhood like any other in Vegas. Then it became a central market with few wealthy families that made fortune on the trade of food and water. Soon the families increased their income and started practicing slave labor. With the help of slaves they cleared the area and put everything in order. For ten years the people here are trying to establish a decent life. A vicious circle of elites and celebrities formed. Much has changed in ten years.}
{170}{}{十年的辛勤劳动。起初，这条林荫道和维加斯的其他街区一样，只是一个无聊而拥挤的街区。后来它变成了一个中心市场，很少有富裕家庭靠食物和水的贸易发财。很快，这些家庭增加了收入，开始从事奴隶劳动。在奴隶的帮助下，他们清理了这个地区，把一切都整理好了。十年来这里的人们都在努力过上体面的生活。精英和名人形成了恶性循环。十年来变化很大。}
#{171}{}{Would you like it if your clean and lovingly maintained house was invaded by dirty beggars that make noise and create problems? Most of them see only luxury and brights, and our hard daily work falls behind the scenes. If so, then I see no reason to treat the monkey as a person, if it is an animal and I'm a man.}
{171}{}{如果你的房子被肮脏的乞丐闯入，弄出噪音，制造麻烦，你愿意吗？他们中的大多数人只看到奢华和光明，而我们每天辛勤的工作却落在了幕后。如果是这样的话，那我就没有理由把猴子当作人，如果它是动物而我是人的话。}
#{172}{}{Of course. But only in the Clean City. We simply have no time for the whole Vegas. Therefore, outskirts are mired in poverty and crime.}
{172}{}{当然。但只有在干净的城市。我们根本没时间看整个维加斯。因此，郊区深陷贫困和犯罪之中。}
#{173}{}{The department of culture is responsible fo the program of cultural events, representation of the Clean City and its inhabitants, but most important of all - for education. Recently we even started selling the surviving pre-war books using vending machines. Just imagine a man reading a book outside of the Clean City. It's almost impossible, is it not?}
{173}{}{文化部负责文化活动计划，代表清洁城市及其居民，但最重要的是教育。最近，我们甚至开始用自动售货机销售尚存的战前书籍。想象一下，一个人在清洁的城市外看书。这几乎是不可能的，不是吗？}
#{174}{}{I would prefer not to discuss the mayor with anyone, even with my acquaintances. But sometimes I just think - how the Council could choose a spineless and pliant old man to such an important post? I??m just afraid that personal interest will corrupt the mayor.}
{174}{}{我不想和任何人讨论市长，即使是和我的熟人。但有时我只是在想——安理会怎么能选择一个没有骨气、柔顺的老人担任如此重要的职务？我只是担心个人利益会败坏市长。}
#{175}{}{Really? What is that business, allow me to know?}
{175}{}{真正地？有什么事，请允许我知道？}
#{176}{}{I supply Nuka-Cola, on the agreement with the factory in the north. I can show the papers, if you don??t believe me.}
{176}{}{我供应努卡可乐，根据与北方工厂的协议。如果你不相信我，我可以出示文件。}
#{177}{}{My private business bears an independent nature. I'm not even obliged to report to the Clean City.}
{177}{}{我的私人生意是独立的。我甚至没有义务去清洁城市报到。}
#{178}{}{It's confidential. I have special agreement with the mayor of the city.}
{178}{}{这是机密。我和市长有特别协议。}
#{179}{}{Hmm, sorry then. I??m obliged to send away all kind of scum, so they wouldn??t bother me and interfere with my work. You know how it is.}
{179}{}{嗯，对不起。我不得不送走各种各样的人渣，这样他们就不会打扰我，干扰我的工作。你知道的。}
#{180}{}{Oh yes. Maybe you can tell me about the work in the City Hall?}
{180}{}{哦，是的。也许你能告诉我市政厅的工作情况？}
#{181}{}{You have made the arrogant minister of culture answer all your questions.}
{181}{}{你让傲慢的文化部长回答了你所有的问题。}
#{182}{}{D-don??t touch me!!! Stay away! How did the security let you in here?! Leave! Leave now, ghoul, so I don??t see you anymore!}
{182}{}{别碰我！！！远离！保安怎么让你进来的？！快走！快走，食尸鬼，我再也见不到你了！}
#{183}{}{Hey, don??t confuse skin disease with ghoulification! Ah, damn it, its pointless to explain it to you.}
{183}{}{嘿，别把皮肤病和食尸鬼混为一谈！啊，见鬼，跟你解释是没有意义的。}
#{184}{}{If you'll talk about my sickness again - you will look lot worse than that. A lot worse.}
{184}{}{如果你再谈起我的病，你会比那更难看的。更糟。}
#{185}{}{Security! SECURUTY!!!}
{185}{}{保安！安全！！！}
#{186}{}{[Leave]}
{186}{}{[离开]}
#{187}{}{Actually, it's really significant. Maybe, you can answer a few questions?}
{187}{}{事实上，这真的很重要。也许，你能回答几个问题？}
#{188}{}{Forget it, it??s not important.}
{188}{}{算了吧，这不重要。}
#{189}{}{I try to stay away from large settlements during my travels. The experience of survival in the wild is more important to me.}
{189}{}{我旅行时尽量远离大型定居点。野外生存的经历对我来说更重要。}
#{190}{}{Did you really acquire such rich experience from your travels? How interesting... I would like to have a talk with you about the life in the wasteland. You don??t mind, do you?}
{190}{}{你真的从旅行中获得了如此丰富的经验吗？真有趣...我想和你谈谈荒地的生活。你不介意吧？}
#{200}{}{And I thought you won??t come.}
{200}{}{我以为你不会来了。}
#{201}{}{Do you dine here often?}
{201}{}{你经常在这里吃饭吗？}
#{202}{}{You wanted to talk to me about the outside world. So I'm at your service.}
{202}{}{你想和我谈谈外面的世界。所以我愿意为你效劳。}
#{203}{}{Please wait, I have something to do and then I'll come back.}
{203}{}{请稍等，我有事要做，然后再回来。}
#{204}{}{It??s my duty to know, how are local business running. Plus, I like it here.}
{204}{}{我有责任了解当地的商业运作情况。另外，我喜欢这里。}
#{205}{}{Yes, it would be great to hear the story from a traveler directly. Let's make ourselves comfortable, order a some whiskey and talk about it.}
{205}{}{是的，直接从一个旅行者那里听到这个故事会很好。让我们舒舒服服地，点一杯威士忌谈谈。}
#{206}{}{Sure, I don??t mind...}
{206}{}{当然，我不介意...}
#{207}{}{Sorry, but I can??t right now. Please wait, I have some things to do.}
{207}{}{对不起，我现在不行。请等一下，我有事要做。}
#{208}{}{You have opened the eyes of the snob and showed him an amazing and diverse world outside Vegas.}
{208}{}{你让势利的人大开眼界，向他展示了一个在维加斯之外的奇妙而多样的世界。}
#{209}{}{Good evening.}
{209}{}{晚上好。}
#{210}{}{Goodbye.}
{210}{}{再见。}
