#{100}{}{You see: Ely.}
{100}{}{你看：伊利。}
#{101}{}{You see a terribly mutilated ghoul. It's repulsive just to look at him.}
{101}{}{你看到一个残缺不全的食尸鬼。光看他就恶心。}
#{108}{}{[You stare at each other in shock. Whoever this creature is, he hasn't seen anyone in a long time.]}
{108}{}{[你们震惊地盯着对方。不管这家伙是谁，他很久没见任何人了}
#{109}{}{[Move]}
{109}{}{[移动]}
#{110}{}{Aaaaah! Don't! No sudden moves, and keep your hands where I can see them. That's how this is done, right?}
{110}{}{啊啊！不要！不要突然动，把手放在我能看见的地方。就是这样做的，对吗？}
#{111}{}{Pretty much, but it would work better if you loaded your gun first.}
{111}{}{差不多，但如果你先把枪装好的话效果会更好。}
#{112}{}{Hey, wait a minute! I didn't know anyone was here. How about we just go our separate ways, huh?}
{112}{}{嘿，等等！我不知道这里有人。我们各奔东西怎么样？}
#{113}{}{[Looks down at his gun in panic] Ah, shit! I knew I forgot something... And I guess yours is loaded, huh? Uh... You're not a cop or anything, right? How about we just sit down and be cool?}
{113}{}{[惊恐地看着他的枪]啊，该死！我知道我忘了什么...我猜你的已经上膛了，是吧？Uh...你不是警察什么的，对吧？我们坐下来冷静一下怎么样？}
#{114}{}{Fine, but I have some questions. Don't lie to me, and don't forget who has the loaded gun here.}
{114}{}{好吧，但我有一些问题。别骗我，别忘了谁拿着上膛的枪。}
#{115}{}{No, I don't think so. I'm just going to go, now.}
{115}{}{不，我不这么认为。我现在就要走了。}
#{116}{}{I like the sound of that. You're not going to come back with a bunch of cops, are you? Nah, you wouldn't.}
{116}{}{我喜欢这声音。你不会带着一群警察回来吧？不，你不会的。}
#{117}{}{I'm interested in something else - how about answering some questions?}
{117}{}{我对别的东西感兴趣-回答一些问题怎么样？}
#{118}{}{I was just leaving, anyway.}
{118}{}{反正我正要离开。}
#{119}{}{Questions... [you see a spark of memory in his eyes, and he look distracted for a moment] "I refuse to speak without my lawyer!" [shakes his head] Why did I say that? It just popped into my head... Alright, I don't mind talking for a bit. I haven't talked to anyone since the war.}
{119}{}{问题...[你看到他眼中闪现出记忆的火花，他一时神色恍惚]“没有律师，我拒绝说话！”我为什么这么说？我突然想到...好吧，我不介意谈一会儿。战后我就没和任何人谈过。}
#{120}{}{Tell me a little about yourself.}
{120}{}{跟我说说你自己。}
#{121}{}{What is this place?}
{121}{}{这是什么地方？}
#{122}{}{Maybe later.}
{122}{}{也许以后吧。}
#{130}{}{Are you still here? What are you hanging around for?}
{130}{}{你还在吗？你在这儿干什么？}
#{131}{}{I have a few questions.}
{131}{}{我有几个问题。}
#{132}{}{I'm just on my way out.}
{132}{}{我正要出去。}
#{133}{}{Plague?}
{133}{}{瘟疫？}
#{134}{}{Limit 115. America testing its new superweapon on its own citizens! Oooooh! What's the matter, you don't like conspiracy theories? It was a plague that broke out in 2053. And 2063. One day you're sneezing and coughing, the next day you're sweating and hemorrhaging, and the day after - you're dead. Scary shit. Denver was the worst - the locals burned it to the ground trying to quarantine it.}
{134}{}{限制115。美国在自己的公民身上测试它的新超级武器！哦哦！怎么了，你不喜欢阴谋论？那是2053年爆发的一场瘟疫。2063年。前一天你打喷嚏，咳嗽，第二天你出汗，出血，第二天-你死了。可怕的狗屎。丹佛是最糟糕的-当地人把它烧成地试图隔离它。}
#{137}{}{Have I been here so long the world's forgotten about the war? October 23, 2077... [gazes over as his notes on the wall, absorbed in his thoughts] I'd like to forget it, too. So many corpses, you couldn't walk the streets of Reno for the stench. I don't even want to know how bad it was where the bombs hit. And the silence on the radio... Silence everywhere.}
{137}{}{我在这里这么久了，全世界都忘了战争了吗？2077年10月23日...[凝视着墙上的笔记，全神贯注地思考]我也想忘掉它。这么多的尸体，你不能走在里诺的街道上的臭味。我甚至不想知道炸弹击中的地方有多糟糕。收音机里的寂静...到处都是寂静。}
#{138}{}{[Next]}
{138}{}{[下一步]}
#{139}{}{Let me think... Hmm, federal highways! Before the war I traveled all over Nevada in my nuclear-powered Corvega. Now she was one hell of a car. Expensive, but worth every penny. Yeah... I didn't know how good I had it.}
{139}{}{让我想想...嗯，联邦高速公路！战争前，我开着核动力的科维加车走遍了内华达州。现在她成了一辆好车。很贵，但每一分钱都值。是 啊...我不知道我有多好。}
#{140}{}{About me? Well... [scratches head] What do you want to know?}
{140}{}{关于我？好...你想知道什么？}
#{141}{}{How did you end up in this place?}
{141}{}{你是怎么来到这里的？}
#{142}{}{You said something about the war... }
{142}{}{你说了些关于战争的事...}
#{143}{}{I'm interested in something else.}
{143}{}{我对别的东西感兴趣。}
#{144}{}{Nothing, actually. Everything seems self-explanatory.}
{144}{}{其实没什么。一切似乎都不言自明。}
#{145}{}{I was driving to Reno for business when some drunk black guy wandered out in front of my car. He was dead the moment I hit him. If that judge hadn't been such a racist, I'd have been in prison for sure. After that shit, I drove into the desert to clear my head, but some crazy cop attacked me and caused an accident! I managed to get here on foot, and on that day... Boom. The war.}
{145}{}{我开车去里诺出差时，一个喝醉的黑人在我的车前闲逛。我一打他他就死了。如果那个法官不是个种族主义者，我肯定会进监狱的。在那之后，我开车到沙漠去清醒头脑，但是一个疯狂的警察袭击了我，造成了一场事故！我设法步行来到这里，那天...繁荣。战争。}
#{146}{}{You were very lucky. Now some more questions.}
{146}{}{你很幸运。现在还有一些问题。}
#{147}{}{War? What kind of war?}
{147}{}{战争？什么战争？}
#{148}{}{I see. Well, shit happens. See you around.}
{148}{}{我懂了。好吧，大便发生了。回头见。}
#{149}{}{[He suddenly remembers something] You know... You know, listen. Fuck everyone who says life was better before the war. It was crap! The war with China, Canada's annexing, the new plague... Fear and hatred everywhere. And now? Freedom! Nobody bothers me, and I don't bother nobody. If only I had my Corvega... I'd drive all over America again, and no cops to stop me.}
{149}{}{[他突然想起一些事]你知道...你知道，听着。操那些说战前生活更好的人。真是糟透了！与中国的战争，加拿大的吞并，新的瘟疫...恐惧和仇恨无处不在。现在呢？自由！没人打扰我，我也不打扰任何人。如果我有我的Corvega...我会再次开车到美国各地，没有警察来阻止我。}
#{150}{}{Thanks for the history lesson. I have another question.}
{150}{}{谢谢你的历史课。我还有一个问题。}
#{151}{}{Really? I'll have to go think about that. See you.}
{151}{}{真正地？我得去考虑一下。再见。}
#{152}{}{Maybe I do know. Maybe I'm the one who locked it. Maybe I even have the key.}
{152}{}{也许我知道。也许是我锁的。也许我还有钥匙。}
#{153}{}{Maybe you'll give it to me?}
{153}{}{也许你会给我？}
#{154}{}{Actually, I was just making conversation. I'm really interesting in something else.}
{154}{}{实际上，我只是在聊天。我对别的东西很感兴趣。}
#{155}{}{Keep it. I have enough information for now.}
{155}{}{留着吧。我有足够的信息。}
#{156}{}{Yeah, maybe... But you'll have to do something for me first. I've got everything I need here - except alcohol. Bring me something strong? Beer, or even booze. Hell, ethanol even. I've gone through my whole stash.}
{156}{}{是的，也许...但你得先为我做点什么。我这里什么都有，除了酒精。给我拿点烈性的？啤酒，甚至是酒。见鬼，甚至是乙醇。我把我所有的藏品都找遍了。}
#{157}{}{I've got it all right here. Take it. Now where's my key?}
{157}{}{我在这里都准备好了。拿去吧。我的钥匙呢？}
#{158}{}{I'll keep that in mind. Another question.}
{158}{}{我会记住的。另一个问题。}
#{159}{}{Fair deal. Wait here.}
{159}{}{公平交易。在这里等着。}
#{160}{}{Take it, take it, of course! I managed to get some nice things in my time.}
{160}{}{拿着，拿着，当然！我设法在我的时间里得到了一些好东西。}
#{161}{}{Excellent. How about another question?}
{161}{}{杰出的。再问一个问题怎么样？}
#{162}{}{It's in your best interest if I find anything useful there. Bye.}
{162}{}{如果我在那里找到有用的东西，对你最有利。再见。}
#{163}{}{Alcohol delivery! Just give me the key first.}
{163}{}{送酒！先把钥匙给我。}
#{164}{}{Take it... Hey, where is it? Did I drop it somewhere? Look in the toilet - I'm not used to pigrat meat yet and I'm always on there. And leave the bottles. You didn't take them all this way for nothing, right?}
{164}{}{拿着...嘿，在哪？我把它掉在什么地方了吗？看看厕所，我还不习惯吃猪扒肉，而且我总是在那里。把瓶子留下。你不是白白带他们来的，对吧？}
#{165}{}{What a loss. See you, loser.}
{165}{}{真是个损失。再见，失败者。}
#{166}{}{War with China?}
{166}{}{与中国开战？}
#{167}{}{Come on, you have to know about it! "Anchorage awaits you, patriot!" "Communism is at your door!" You've really never heard of it? Strange... We fought them for quite some time in Alaska. Now I see it was just the beginning.}
{167}{}{拜托，你得知道！”“安克雷奇在等你，爱国者！”共产主义就在你的门口！”你真的没听说过吗？奇怪...我们在阿拉斯加和他们战斗了很长一段时间。现在我知道这只是个开始。}
#{168}{}{Canada's annexing?}
{168}{}{加拿大要兼并？}
#{169}{}{Those beaver-loving, maple-syrup-drinking, milk-bagging idiots... When the shit hit the fan, we needed to go through them to get to Alaska. It was a good chance to get that "country's" resources. Oh, sure, there were rebels here and there... But most of them knew what side they wanted to be on.}
{169}{}{那些爱吃海狸，喝枫糖，装牛奶的白痴...当那玩意儿砸到风扇上时，我们得穿过它们去阿拉斯加。这是一个获得“国家”资源的好机会。哦，当然，到处都是叛军...但大多数人都知道自己想站在哪一边。}
#{170}{}{Right now, I've got nothing but one toilet. But before the war, I was a family man with two old people at my side.}
{170}{}{现在，我只有一个厕所。但在战争之前，我是一个有家庭的男人，身边有两位老人。}
#{171}{}{So you're here all alone? Where is everybody?}
{171}{}{所以你一个人在这里？大家都在哪？}
#{172}{}{I saw something like a warehouse outside. Do you know if it's locked?}
{172}{}{我看到外面有个仓库。你知道锁不锁？}
#{173}{}{Before the war? What are you talking about?}
{173}{}{战前？你在说什么？}
#{174}{}{One more question... }
{174}{}{还有一个问题...}
#{175}{}{I'm happy for you, but I have to go.}
{175}{}{我为你高兴，但我得走了。}
#{176}{}{Corvega, huh? I've heard of this. It was mentioned in the sheriff's holodisk.}
{176}{}{科维加，嗯？我听说过这个。警长的全息光盘上提到过。}
#{177}{}{Who? [looks around] Oh, them... They ran off when the war started. There's no one left. You won't even find a trace.}
{177}{}{谁？[环顾四周]哦，他们...战争一开始他们就逃跑了。没人了。你甚至找不到踪迹。}
#{178}{}{Interesting. I found a holodisk written by a deputy sheriff. And what a coincidence! - It mentioned an Ely Gorbinsky. Do you have anything to say about that?}
{178}{}{很有趣。我找到了副警长写的全息光盘。多巧啊！-它提到了一个伊利·戈宾斯基。你有什么要说的吗？}
#{179}{}{Well, let's suppose you're not lying. But I still have more questions.}
{179}{}{好吧，假设你没有撒谎。但我还有更多的问题。}
#{180}{}{Well, if they're gone, then there's nothing to talk about. Bye.}
{180}{}{好吧，如果他们走了，那就没什么好谈的了。再见。}
#{181}{}{[His eyes narrow and he goes silent for several seconds] You just had to go digging around, didn't you? [clutches his shotgun] For half a century, I saw them every time I closed my eyes. And here you come, tearing open the scars! Don't you at least want to hear my side of the story?}
{181}{}{[他眯着眼睛，沉默了几秒钟]你得到处挖，不是吗？半个世纪以来，我每次闭上眼睛都能看到他们。你来了，撕开伤疤！你难道不想听听我的观点吗？}
#{182}{}{You can tell it under ten feet of dirt, you murdering piece of shit! [Attack]}
{182}{}{你可以在十英尺深的泥土里看出来，你这个杀人的混蛋！[攻击]}
#{183}{}{Interesting. Don't make any sudden moves, and I'll hear your side of the story.}
{183}{}{很有趣。别急，我会听你的。}
#{184}{}{I wouldn't have touched them, but I was in the middle of the desert with no car, no help, and a nuclear war going on! You have no idea what it was like. Look at what it did to me! Eight people, all against me because of that dirty cop and his stories. But I was smarter than all of them. They didn't even know what had happened to the world.}
{184}{}{我不会碰他们，但我在沙漠中，没有车，没有人帮忙，核战争正在进行！你不知道那是什么感觉。看看它对我做了什么！八个人，都因为那个肮脏的警察和他的故事反对我。但我比他们都聪明。他们甚至不知道世界发生了什么。}
#{185}{}{This isn't a defense. It's a confession. And I'm the one who will carry out your sentence. [Attack]}
{185}{}{这不是辩护。这是忏悔。我会执行你的判决。[攻击]}
#{186}{}{Go on... }
{186}{}{继续...}
#{187}{}{I managed to get to Reno. The bombs hadn't touched it, but the people there... It was hell. When I got back to the mine, I hid in a small cave, only coming out at night. When I ran out of food, I snuck into the kitchen through the window... But one of the workers suprised me. I had to deal with him before he could call the others. The second one got too close to my cave, but he wounded me in the fight. I cut off his head and tossed it in the washing machine, and took the medicine I needed while they were distracted. Clever, huh? But on the way back, I tripped over another worker... On and on, until in a week they were all dead. I know what you're thinking. How could I live with myself? Am I even human?... Hmm. I don't know how to answer that.}
{187}{}{我设法到了雷诺。炸弹没碰到它，但是那里的人...简直是地狱。回到矿井后，我躲在一个小山洞里，只在晚上出来。当我没有食物时，我从窗户溜进厨房...但其中一个工人让我大吃一惊。在他给其他人打电话之前，我得先处理好他。第二个离我的洞穴太近了，但他在战斗中打伤了我。我砍下他的头，扔在洗衣机里，趁他们分心的时候吃了我需要的药。聪明吧？但在回来的路上，我被另一个工人绊倒了...不停地，直到一周后他们都死了。我知道你在想什么。我怎么能和自己一起生活？我是人类吗？...嗯。我不知道怎么回答。}
#{188}{}{Just try.}
{188}{}{试试看。}
#{189}{}{You're going to answer for it, alright. With your blood. [Attack]}
{189}{}{你会为此负责的，好吧。用你的血。[攻击]}
#{190}{}{It was like a nightmare. Everything was different. Wild. Survival of the fittest. I've been living in fear, seeing their faces for all these years... So many years.}
{190}{}{就像一场噩梦。一切都不同了。野性。适者生存。这些年来我一直生活在恐惧中，看到他们的脸...这么多年了。}
#{191}{}{There's no statute of limitations on this crime. It's time to pay, Ely Gorbinsky. [Attack]}
{191}{}{这项罪行没有法定时效。该付钱了，伊利·戈宾斯基。[攻击]}
#{192}{}{Fine, Ely. I'll let you be for now. Who knows what I would have done in your place?}
{192}{}{很好，伊利。我现在就放你走。谁知道我会在你的位置上做什么？}
#{193}{}{Say, about your story... Are you sure everything happened in a week?}
{193}{}{说，关于你的故事...你确定一切都发生在一周之内吗？}
#{194}{}{[Grits his teeth and closes his eyes] No! Don't ask me! I can't tell... [grabs his head and falls to the ground] Shut up, scumbag! - What are you doing? Leave me alone! No, I won't tell them! - [curls up, raking fingers across his skull] - Too late, Gorbinsky! The world is on fire, and we're burning with it! We're all going to die - and you, Ely, will be the first! - Stop, no, I can fix this! NOOO!!! [the ghoul drops on the ground, shaking]}
{194}{}{[咬紧牙关]不！别问我！我不知道...[抓住他的头倒在地上]闭嘴，混蛋！-你在干什么？别管我！不，我不会告诉他们！-[蜷缩起来，用手指划过他的头骨]-太晚了，戈宾斯基！世界着火了，我们也在燃烧！我们都会死的-而你，伊利，将是第一个！-住手，不，我能搞定的！不！！！[食尸鬼掉在地上，颤抖]}
#{195}{}{Woah... }
{195}{}{哇...}
#{196}{}{It seems that this ghoul suffers from multiple personality disorder. You can't tell who he really is - Ely Gorbinsky or the deputy sheriff.}
{196}{}{看来这个食尸鬼患有多重人格障碍。你分不清他到底是谁——伊利·戈宾斯基还是副警长。}
#{197}{}{What? [tenses up, suddenly nervous] You... You don't believe me? Why all these questions?}
{197}{}{什么？[紧张起来，突然紧张]你...你不相信我？为什么要问这些问题？}
#{198}{}{The dates don't match up with this holodisk. And it was written right after it happened... }
{198}{}{日期和这张全息光盘不符。就在事情发生后写的...}
#{199}{}{Leave! Run! He'll come back! He always does... }
{199}{}{快走！快跑！他会回来的！他总是...}
#{200}{}{Oh, just making conversation. I have another question.}
{200}{}{哦，只是说说而已。我还有一个问题。}
#{1112}{}{Hey, wait a minute! I didn't know anyone was here. How about we just go our separate ways, huh?}
{1112}{}{嘿，等等！我不知道这里有人。我们各奔东西怎么样？}
#{1164}{}{Take it... Hey, where is it? Did I drop it somewhere? Look in the toilet - I'm not used to pigrat meat yet and I'm always on there. And leave the bottles. You didn't take them all this way for nothing, right?}
{1164}{}{拿着...嘿，在哪？我把它掉在什么地方了吗？看看厕所，我还不习惯吃猪扒肉，而且我总是在那里。把瓶子留下。你不是白白带他们来的，对吧？}
#{1172}{}{I saw something like a warehouse outside. Do you know if it's locked?}
{1172}{}{我看到外面有个仓库。你知道锁不锁？}
#{1175}{}{I'm happy for you, but I have to go.}
{1175}{}{我为你高兴，但我得走了。}
#{1192}{}{Fine, Ely. I'll let you be for now. Who knows what I would have done in your place?}
{1192}{}{很好，伊利。我现在就放你走。谁知道我会在你的位置上做什么？}
