#{100}{}{You see a coach.}
{100}{}{你看到一辆马车。}
#{101}{}{you see a coach. Behind his straight face you can discern some hidden bloodlust.}
{101}{}{你看到一辆马车。在他笔直的脸后面，你能看出隐藏的嗜血。}
#{102}{}{That's good. But I gotta go.}
{102}{}{那很好。但我得走了。}
#{109}{}{[Shakes head in approval] I'm glad to see you. You are my pride.}
{109}{}{很高兴见到你。你是我的骄傲。}
#{110}{}{Another star? [examines you from head to toe]}
{110}{}{另一个明星？[从头到脚检查你]}
#{111}{}{Speak, I'm listening.}
{111}{}{说吧，我在听。}
#{112}{}{Are you a coach? Will you teach me the art of a bloody fight?}
{112}{}{你是教练吗？你能教我血腥搏斗的艺术吗？}
#{113}{}{I need another training session. Here's 1000 bucks.}
{113}{}{我还需要一次训练。这是1000美元。}
#{114}{}{I don't need anything.}
{114}{}{我什么都不需要。}
#{115}{}{My time is money. I take $1000 for one training.}
{115}{}{我的时间就是金钱。我接受一次培训要1000美元。}
#{116}{}{I have the amount. Shall we start training right now?}
{116}{}{我有这个数目。我们现在就开始训练好吗？}
#{117}{}{I see. I will return when I decide to train.}
{117}{}{我懂了。当我决定训练时，我会回来的。}
#{118}{}{Now! To the shower! Move!}
{118}{}{现在！去洗澡！快走！}
#{119}{}{Sir, yes, sir!.. Uh, where's the shower?}
{119}{}{先生，是的，先生！。。呃，淋浴在哪里？}
#{120}{}{You shouldn't exercise so often. Come back tomorrow when you gain strength.}
{120}{}{你不应该经常锻炼。明天你有力气的时候再来。}
#{121}{}{You know better, coach.}
{121}{}{你更清楚，教练。}
#{122}{}{Sorry, but I have nothing left to teach you anymore. You have grown up and now on your own. Your future teacher is the ring, not the gym.}
{122}{}{对不起，我没什么可以教你的了。你已经长大了，现在只能靠自己了。你未来的老师是戒指，不是体育馆。}
#{123}{}{Oh, well coach, if you say so...}
{123}{}{哦，教练，如果你这么说...}
#{124}{}{After the fifth training session you finally made some progress. Your Unarmed skill increased by 5%!}
{124}{}{第五次训练之后，你终于取得了一些进步。徒手技能提升5%！}
#{125}{}{You have finished your tenth training session already, which hasn't passed without effect. Your Unarmed skill increased by 5%!}
{125}{}{你已经完成了你的第十次训练课程，这不是没有效果的。徒手技能提升5%！}
#{126}{}{Your hard work was not in vain. After the fifteenth training session your Unarmed skill increased by 5%!}
{126}{}{你的努力没有白费。第十五次训练后，你的徒手技能提高了5%！}
#{127}{}{That was your twentieth training! Such diligence was not in vain. Your Unarmed skill increased by 5%.}
{127}{}{那是你的第二十次训练！这样的努力并没有白费。徒手技能提高5%。}
#{128}{}{That was your last training. You increased the Unarmed skill by 5% and your strength by 1!}
{128}{}{那是你最后一次训练。徒手技能提升5%，臂力提升1！}
#{129}{}{You have carried out an ordinary training. But the results are not visible yet. You need to train more.}
{129}{}{你进行了一次普通的训练。但目前还看不到结果。你需要多训练。}
#{130}{}{Great job, champion! Such diligence, such stamina... Who would have thought? Until now, no one could endure such prolonged exercises. I'm proud of you! But... You know, I taught you everything I could. Next you will have to grow on your own.}
{130}{}{干得好，冠军！如此勤奋，如此毅力...谁会想到呢？直到现在，没有人能忍受如此长时间的锻炼。我为你骄傲！但是...你知道，我教了你我能教的一切。下一步你必须自己成长。}
#{131}{}{Thank you, coach, for everything.}
{131}{}{教练，谢谢你所做的一切。}
#{132}{}{Wow! What a technique! But I won't be able to help you. I have never worked with such a good fighter.}
{132}{}{哇！多好的技术啊！但我帮不了你。我从来没有和这么好的战士一起工作过。}
#{133}{}{Stop waltzing around! What kind of movement is it? It's the ring, damn you, not the dance floor!}
{133}{}{别胡闹了！这是什么运动？是戒指，该死的，不是舞池！}
#{134}{}{Good job, you dance nicely. Would be better if you danced like that in the ring. Ha-ha-ha!}
{134}{}{干得好，你跳得很好。如果你在拳击场上那样跳舞会更好。哈哈哈！}
#{135}{}{No, champion. Your place is on the big ring and not on this dance floor.}
{135}{}{不，冠军。你的位置在大舞台上，而不是在舞池里。}
#{136}{}{Eh... Are you talking to me?}
{136}{}{呃...你在跟我说话吗？}
#{137}{}{Your hard work was not in vain: your Unarmed skill increased by 5%!}
{137}{}{你的努力没有白费：你的徒手技能增加了5%！}
#{138}{}{After all those exhausting exercises you increased your Strength.}
{138}{}{做了那么多筋疲力尽的运动后，你增强了体力。}
#{1122}{}{Sorry, but I have nothing left to teach you anymore. You have grown up and now on your own. Your future school is the ring, not the gym.}
{1122}{}{对不起，我没什么可以教你的了。你已经长大了，现在只能靠自己了。你未来的学校是拳击场，不是体育馆。}
#{1130}{}{Great job, champion! Such diligence, such stamina... Who would have thought? Until now, no one could endure such prolonged exercises. I'm proud of you! But... You know, I taught you everything I could. Next you will have to grow on your own.}
{1130}{}{干得好，冠军！如此勤奋，如此毅力...谁会想到呢？直到现在，没有人能忍受如此长时间的锻炼。我为你骄傲！但是...你知道，我教了你我能教的一切。下一步你必须自己成长。}
