#{100}{}{You see Hal Wallace.}
{100}{}{你看到哈尔·华莱士了。}
#{101}{}{Here is none other than the owner of "Three Card Monte" himself.}
{101}{}{这里不是别人，正是“三证山”的主人本人。}
#{102}{}{Killer in the office!!!}
{102}{}{办公室里的杀手！！！}
#{107}{}{You don't say...}
{107}{}{你不会说...}
#{108}{}{Guards! Take this trash out of the office!}
{108}{}{警卫！把这垃圾带出办公室！}
#{109}{}{Who?! Me? He made a mistake! I want to get out of here.}
{109}{}{谁？！我？他犯了个错误！我想离开这里。}
#{110}{}{The guard said you want to see me?}
{110}{}{警卫说你想见我？}
#{111}{}{Yes. I want to work for you!}
{111}{}{对。我想为你工作！}
#{112}{}{Oh, sorry, wrong door.}
{112}{}{哦，对不起，走错门了。}
#{113}{}{Where the guards are looking?! Immediately take him out into the corridor!}
{113}{}{卫兵在找什么？！马上把他带到走廊里去！}
#{114}{}{No! Wait...}
{114}{}{不！等待...}
#{115}{}{Yes, there is one job... Not for the faint-hearted.}
{115}{}{是的，有一份工作...不适合胆小的人。}
#{116}{}{What is it?}
{116}{}{这是怎么一回事？}
#{117}{}{Oh, I'm just like that, so I'd better go away.}
{117}{}{哦，我就是这样，所以我最好走开。}
#{118}{}{You do know who the freaks are, don't you? These ghouls are a pain in the ass. The whole city is suffering because of them and it's uncertain for how long this will continue. We must deal with it.}
{118}{}{你知道谁是怪胎吧？这些食尸鬼真是让人头疼。整个城市都因此而受苦，而且这种情况还不确定会持续多久。我们必须处理它。}
#{119}{}{Hmm. Something tells me you goals are not entirely righteous.}
{119}{}{嗯。有些事告诉我你的目标不完全是正义的。}
#{120}{}{What are they guilty of?}
{120}{}{他们犯了什么罪？}
#{121}{}{Sure. If you pay, then we must.}
{121}{}{当然。如果你付钱，那我们就必须付。}
#{122}{}{Not ghouls! I don't mess with them!}
{122}{}{不是食尸鬼！我不会惹他们的！}
#{123}{}{I, like the rest of the city, have my reasons, but why do you care? Better concentrate on your own interest.}
{123}{}{一、 像其他城市一样，有我的理由，但你为什么在乎？最好专注于你自己的兴趣。}
#{124}{}{[Discreetly turn on the recording on a Pip-Boy] So, what was the job?}
{124}{}{[谨慎地打开一个皮普男孩的录音]那么，工作是什么？}
#{125}{}{So what was the job?}
{125}{}{那工作是什么？}
#{126}{}{If you don't want to be honest with me, then I refuse!}
{126}{}{如果你不想跟我说实话，那我拒绝！}
#{127}{}{Of the production and distribution of drugs. I consider their survival techniques simply monstrous. Because of their drugs people break or die. That includes my clients. So, as a respectable citizen, I would like to clean the city of this... Garbage.}
{127}{}{药品的生产和销售。我认为他们的生存技巧简直太可怕了。因为他们的毒品，人们要么崩溃，要么死亡。包括我的客户。所以，作为一个受人尊敬的公民，我想清理这座城市...垃圾。}
#{128}{}{I'm paying 2,500 for this simple task. Big money for the majority of citizens. But so is the risk. You'll have to do it quietly.}
{128}{}{我为这个简单的任务付了2500英镑。对大多数市民来说是一大笔钱。但风险也是如此。你得安静地做。}
#{129}{}{It's simple. I'll give you a drug, it is very powerful. Do not ask where me where it came from. And do not try it, it's a lethal mixture.}
{129}{}{很简单。我给你一种药，很厉害。别问我它是从哪里来的。别试了，这是致命的混合物。}
#{130}{}{Well, I'll try not to ask questions for now. What next?}
{130}{}{好吧，我现在尽量不提问题。接下来呢？}
#{131}{}{And then everything is simple - quietly and covertly penetrate the hotel of the freaks and place the drug into boxes. After you do that, go to the police station and anonymously pass the information about the evidence to the police chief. He knows what to do.}
{131}{}{然后一切都很简单-悄悄地和秘密地渗透到酒店的怪胎和地方的毒品盒。之后，你去警察局，匿名地把证据的信息传递给警察局长。他知道该怎么办。}
#{132}{}{Seems easy. Is it risky? Do these freaks have guards?}
{132}{}{看起来很简单。有风险吗？这些怪胎有警卫吗？}
#{133}{}{How do I sneak inside the building?}
{133}{}{我要怎么潜入大楼？}
#{134}{}{I'll pass! It's too dangerous!}
{134}{}{我会过去的！太危险了！}
#{135}{}{Well, I was wrong about you. [nods to guards]}
{135}{}{嗯，我看错你了。[向守卫点头]}
#{136}{}{Everybody stand still! I will defend myself!!!}
{136}{}{大家站好！我会保护自己！！！}
#{137}{}{Freaks do not usually get involved in the fight, they are sitting on a needle so long that they lost most of their health. I think you won't encounter serious resistance. Especially considering they are likely don't expect you.}
{137}{}{怪胎通常不会参与战斗，他们坐在针尖上太久以至于失去了大部分的健康。我想你不会遇到严重的抵抗。尤其是考虑到他们可能不指望你。}
#{138}{}{It's not up to me. Residents of Clean City rarely go beyond the walls. Deal with it yourself. It's your job.}
{138}{}{这不由我决定。清洁城市的居民很少走出围墙。你自己处理吧。这是你的工作。}
#{139}{}{Well, the case seems simple. Give me your fake evidence and prepare the money, I'll be back soon.}
{139}{}{这个案子看起来很简单。把你的假证给我，准备好钱，我很快就回来。}
#{140}{}{Excellent. I am a man of my word. But if you screw up...}
{140}{}{杰出的。我是个守信用的人。但如果你搞砸了...}
#{141}{}{I understand you, Mr. Wallace. Work is work. I will do my job without further ado.}
{141}{}{我理解你，华莱士先生。工作就是工作。我会毫不犹豫地做好我的工作。}
#{142}{}{Hell no! I will not take such shady work!!!}
{142}{}{他妈的不！我不会干这种见不得人的工作！！！}
#{143}{}{I will wait for news, partner.}
{143}{}{我等消息，伙计。}
#{144}{}{Okay, Mr. Wallace.}
{144}{}{好的，华莱士先生。}
#{145}{}{I'm waiting for *good* news!}
{145}{}{我在等好消息！}
#{146}{}{It's done. Drugs are put into the boxes. What remains is only to surrender them to the police.}
{146}{}{完成了。毒品被放进盒子里。剩下的就是把他们交给警察。}
#{147}{}{It's done. Drugs, as agreed, were planted and the freaks were commissioned to the police.}
{147}{}{完成了。按照约定，毒品被植入，怪胎被委托给警方。}
#{148}{}{The problem with freaks was resolved without drugs. Larry Geller, their leader, is dead.}
{148}{}{怪胎的问题不用药物就解决了。他们的领袖拉里·盖勒死了。}
#{149}{}{I managed to find other evidence and give the freaks to the police, without faking it.}
{149}{}{我设法找到了其他的证据，把这些怪胎交给了警察，但没有伪造。}
#{150}{}{Sorry, nothing yet.}
{150}{}{对不起，还没有。}
#{151}{}{Yes, this is what we needed. I'll take it from here. As for you, you did your job. I suppose there's no need to make unnecessary remarks about the importance of silence?}
{151}{}{是的，这就是我们需要的。我从这里开始。至于你，你做了你的工作。我想没有必要对沉默的重要性发表不必要的评论吧？}
#{152}{}{Of course, Mr. Wallace. Nobody will find out about this incident from me.}
{152}{}{当然，华莱士先生。没人会从我这里知道这件事的。}
#{153}{}{This looks like a threat! It's time to strike first!}
{153}{}{这看起来是个威胁！该先动手了！}
#{154}{}{Yes, this is what we need. You performed brilliantly. I suppose there's no need to make unnecessary remarks about the importance of silence?}
{154}{}{是的，这就是我们需要的。你表现得很出色。我想没有必要对沉默的重要性发表不必要的评论吧？}
#{155}{}{But I demanded a different solution... Although, this one will suffice. Without a leader they shouldn't be a threat... Okay, I don't mind. I suppose, there's no need to make unnecessary remarks about the importance of silence?}
{155}{}{但我要求一个不同的解决方案...不过，这个就够了。没有领袖，他们不应该成为威胁...好吧，我不介意。我想，没有必要对沉默的重要性发表不必要的评论吧？}
#{156}{}{Well, I do not mind. One way or another, you did your job. I suppose there's no need to make unnecessary remarks about the importance of silence?}
{156}{}{嗯，我不介意。不管怎样，你都做了你的工作。我想没有必要对沉默的重要性发表不必要的评论吧？}
#{157}{}{The reward 2500, as we agreed.}
{157}{}{我们说好的，奖励2500英镑。}
#{158}{}{The amount is good!}
{158}{}{数量不错！}
#{159}{}{More work for you.}
{159}{}{给你更多的工作。}
#{160}{}{I'm listening, Mr. Wallace.}
{160}{}{我在听，华莱士先生。}
#{161}{}{Hell no! Some dubious affairs are going on here! It's time to end it!}
{161}{}{他妈的不！这里发生了一些可疑的事情！是时候结束了！}
#{162}{}{I came to find out whether there is a "special" task for me.}
{162}{}{我是来看看是否有一个“特殊”的任务给我。}
#{163}{}{There is one man who insulted me greatly. I cannot get back at him openly. I need a compromising material on him.}
{163}{}{有一个人侮辱了我。我不能公开报复他。我需要一份关于他的资料。}
#{164}{}{Excellent. Who is this person?}
{164}{}{杰出的。这个人是谁？}
#{165}{}{Hell no! I don't do things like this!}
{165}{}{他妈的不！我不做这种事！}
#{166}{}{His name is Bob Neil. He is in charge of the local dam. Has very tricky personality, be careful with him.}
{166}{}{他叫鲍勃·尼尔。他负责当地的水坝。性格很狡猾，小心他。}
#{167}{}{Okay. What kind of compromising material you need?}
{167}{}{可以。你需要什么样的妥协材料？}
#{168}{}{I need his personal gun. But the Bob Neil must stay alive!}
{168}{}{我需要他的私人枪。但是鲍勃·尼尔必须活着！}
#{169}{}{It will not be easy. Why not to just kill him? Why such complications?}
{169}{}{这并不容易。为什么不直接杀了他？为什么会有这样的并发症？}
#{170}{}{Okay. I'll do everything.}
{170}{}{可以。我什么都会做。}
#{171}{}{A lot of questions always do harm those who ask them.}
{171}{}{很多问题总是伤害那些问问题的人。}
#{172}{}{Okay. I'll do the job. What is the price of the risk?}
{172}{}{可以。我来做这个工作。风险的代价是什么？}
#{173}{}{The same - 5000 bucks.}
{173}{}{同样-5000美元。}
#{174}{}{I'll do it.}
{174}{}{我会的。}
#{175}{}{Not enough. It's too dangerous an complicated. 7000, no less.}
{175}{}{还不够。这太危险了，太复杂了。7000，不少于。}
#{176}{}{You've convinced me. Let's increase the reward up to 7000. I'm not a fan of negotiating the price, but if the issue would be resolved, I am ready to pay.}
{176}{}{你说服了我。让我们把奖金增加到7000英镑。我不喜欢谈判价格，但如果问题能解决，我愿意付钱。}
#{177}{}{Excellent! Prepare the money.}
{177}{}{杰出的！准备好钱。}
#{178}{}{Greed has brought many people to the gallows. Think about it *now*, before it's too late.}
{178}{}{贪婪使许多人上了绞刑架。想一想，趁现在还来得及。}
#{179}{}{I got it. I'm sorry, Mr. Wallace. I will fulfill the task by *your* price.}
{179}{}{我得到了它。对不起，华莱士先生。我将以你的价格完成这项任务。}
#{180}{}{So you're threatening me!!! The dirt is waiting for *you*, scumbag!}
{180}{}{所以你在威胁我！！！泥土在等着你，混蛋！}
#{181}{}{I do not forgive mistakes. I need Bob's gun, quietly.}
{181}{}{我不原谅错误。我需要鲍勃的枪，安静点。}
#{182}{}{I understood. I will try.}
{182}{}{我明白了。我会努力的。}
#{183}{}{You know what to do. So why are you here?}
{183}{}{你知道该怎么办。那你为什么在这里？}
#{184}{}{Mission accomplished. Here is the gun. Bob Neil is still alive, he knows nothing about our deal.}
{184}{}{任务完成了。这是枪。鲍勃·尼尔还活着，他对我们的交易一无所知。}
#{185}{}{Nothing. Just wasting time.}
{185}{}{没有什么。只是浪费时间。}
#{186}{}{I've come to say, that I quit this stupid work!}
{186}{}{我来是想说，我放弃了这项愚蠢的工作！}
#{187}{}{I've come to say that I was presented with a counter-offer. And I took it.}
{187}{}{我来是想说我收到了一份还盘。我接受了。}
#{188}{}{And you had the nerve to come back?! Guards!}
{188}{}{你居然敢回来？！警卫！}
#{189}{}{But Bob Neil is avenged!..}
{189}{}{但是鲍勃尼尔已经报仇了！。。}
#{190}{}{I knew I could rely on you. Excellent work. Here's your reward, as we agreed. Well, it was nice to work with you. However, now we part ways. Stay away from the police and the mayor's office, if you do not want the hassle.}
{190}{}{我知道我可以依靠你。干得好。这是我们约定的报酬。很高兴和你一起工作。然而，现在我们分手了。如果你不想惹麻烦，就离警察和市长办公室远点。}
#{191}{}{So why you needed the gun? It would be easier to kill the chief...}
{191}{}{那你为什么需要枪？杀了酋长会更容易...}
#{192}{}{So be it.}
{192}{}{就这样吧。}
#{193}{}{Compromising material is supposed to be used *against* Bob Neil. That says it all. How - is not your business.}
{193}{}{妥协的材料应该用来对付鲍勃·尼尔。这就说明了一切。怎么-不关你的事。}
#{194}{}{I do not like corridor tramps. I advise you to go about your business.}
{194}{}{我不喜欢走廊流浪汉。我劝你继续干你的事。}
#{195}{}{[Discreetly turn on the recording on your Pip-Boy] Excellent. Who is this person?}
{195}{}{[小心地打开你的皮普小子的录音]太好了。这个人是谁？}
#{196}{}{I will fulfill your every order! Are you sure there is no work for me?!}
{196}{}{我会完成你的每一个命令！你确定我没有工作吗？！}
#{197}{}{Sorry, no.}
{197}{}{对不起，没有。}
#{198}{}{Shame.}
{198}{}{羞愧。}
#{199}{}{Why not contact the police directly?}
{199}{}{为什么不直接联系警察？}
#{200}{}{In America, when something is not in order, the best way to fix is usually the fastest.}
{200}{}{在美国，当事情不正常时，最好的解决方法通常是最快的。}
#{1112}{}{Oh, sorry, wrong door.}
{1112}{}{哦，对不起，走错门了。}
#{1113}{}{Where the guards are looking?! Immediately take her out into the corridor!}
{1113}{}{卫兵在找什么？！马上把她带到走廊里去！}
#{1117}{}{Oh, I'm just like that, so I'd better go away.}
{1117}{}{哦，我就是这样，所以我最好走开。}
#{1141}{}{I understand you, Mr. Wallace. Work is work. I will do my job without further ado.}
{1141}{}{我理解你，华莱士先生。工作就是工作。我会毫不犹豫地做好我的工作。}
#{1176}{}{You've convinced me. Let's increase the reward up to 7000. I'm not a fan of negotiating the price, but if the issue will be resolved, I am ready to pay.}
{1176}{}{你说服了我。让我们把奖金增加到7000英镑。我不喜欢谈判价格，但如果问题能解决，我愿意付钱。}
#{1179}{}{I got it. I'm sorry, Mr. Wallace. I will fulfill the task by *your* price.}
{1179}{}{我得到了它。对不起，华莱士先生。我将以你的价格完成这项任务。}
#{1182}{}{I understood. I will try.}
{1182}{}{我明白了。我会努力的。}
#{1186}{}{I've come to say, that I quit this stupid work!}
{1186}{}{我来是想说，我放弃了这项愚蠢的工作！}
#{1187}{}{I've come to say that I was presented with a counter-offer. And I took it.}
{1187}{}{我来是想说我收到了一份还盘。我接受了。}
