#{100}{}{You see the deputy mayor.}
{100}{}{你去见副市长。}
#{101}{}{You see Tom Parker.}
{101}{}{你看到汤姆·帕克了。}
#{102}{}{You see undersized mustachioed man with a demanding expression. This man is the deputy mayor.}
{102}{}{你看到一个身材矮小、留着胡子、表情苛刻的男人。这个人是副市长。}
#{110}{}{Tom Parker, the deputy mayor. What is it about?}
{110}{}{汤姆·帕克，副市长。是关于什么的？}
#{111}{}{What is it about?}
{111}{}{是关于什么的？}
#{112}{}{I'm looking for the coordinates of Area 51. Could you help me?}
{112}{}{我在找51区的坐标。你能帮我吗？}
#{113}{}{Tell me, how much do you get paid?}
{113}{}{告诉我，你的薪水是多少？}
#{114}{}{I demand an explanation why you sponsor the case of Sam Phillips!}
{114}{}{我要求你解释你为什么赞助山姆·菲利普斯的案子！}
#{115}{}{I guess I do not need anything.}
{115}{}{我想我什么都不需要。}
#{116}{}{Do you know *where* you are? This is not a brothel, it's the mayor's office! I demand an explanation, what are you doing here!}
{116}{}{你知道你在哪里吗？这不是妓院，是市长办公室！我需要一个解释，你在这里干什么！}
#{117}{}{Oh my! Oh my! And what if I don??t answer? Huh?}
{117}{}{天哪！天哪！如果我不回答呢？嗯？}
#{118}{}{I'm here on business. I was hired by Mr. Williamson.}
{118}{}{我是来出差的。我是威廉森先生雇的。}
#{119}{}{Sorry, I just had no one to talk to.}
{119}{}{对不起，我只是没人说话。}
#{120}{}{Sorry, I was looking for the toilet, but entered the wrong door.}
{120}{}{对不起，我在找厕所，但进错门了。}
#{121}{}{I came to drain some blood out of you.}
{121}{}{我是来给你放血的。}
#{122}{}{I'm looking for the archive with the coordinates of Area 51.}
{122}{}{我在找坐标在51区的档案。}
#{123}{}{Archive is at the end of the hallway on this floor... Although it won't be any help to you. It's only for City Hall employees.}
{123}{}{档案馆在这层走廊的尽头...虽然这对你没有任何帮助。只给市政厅的员工。}
#{124}{}{Wow, okay then.}
{124}{}{哇，那好吧。}
#{125}{}{Could you help with that?}
{125}{}{你能帮忙吗？}
#{126}{}{Okay, citizen. Stop fooling around! You are not the first questionable fella that goes to City Hall for no reason. We don??t need people like here. Get out. Now! Right now!}
{126}{}{好的，公民。别胡闹了！你不是第一个无缘无故去市政厅的可疑家伙。我们不需要像这里这样的人。走出。现在！马上！}
#{127}{}{Uh, look at him! So what are you going to do now, huh?!}
{127}{}{呃，看看他！那你现在打算怎么办啊？！}
#{128}{}{Okay-okay, I??ll go peacefully...}
{128}{}{好吧，好吧，我会平静地去...}
#{129}{}{Guards!!! Intruder in the office!!!}
{129}{}{警卫！！！办公室里有入侵者！！！}
#{130}{}{[Resist]}
{130}{}{[抵抗]}
#{131}{}{[Obey and go with a guard]}
{131}{}{[服从并与守卫同行]}
#{132}{}{Hmm. In any case, I??ll have to ask you to leave this office.}
{132}{}{嗯。无论如何，我都得请你离开这间办公室。}
#{133}{}{As you wish.}
{133}{}{如你所愿。}
#{134}{}{I earn enough, to keep afloat. And now, God dammit, I want explanations, why is this question arising.}
{134}{}{我挣的钱足够维持生计。现在，天哪，我需要解释，为什么会出现这个问题。}
#{135}{}{Hey, big guy, chill the fuck out. I ask questions here in accordance with the power that Mr. Williamson gave me. So, you deny any involvement in the recent events in the city then?}
{135}{}{嘿，大个子，冷静点。我根据威廉森先生给我的权力在这里提问。那么，你否认与城市最近发生的事件有关吗？}
#{136}{}{I make questions here!}
{136}{}{我在这里提问！}
#{137}{}{I was just curious. Honestly.}
{137}{}{我只是好奇。说真的？}
#{138}{}{Err... What?! What is this, interrogation?}
{138}{}{呃...什么？！这是什么，审问？}
#{139}{}{What do you know about the case of Sam Phillips?}
{139}{}{你对山姆·菲利普斯的案子了解多少？}
#{140}{}{What are your thoughts about the freaks?}
{140}{}{你对那些怪胎有什么看法？}
#{141}{}{Hoover Dam. Do you own a part of this station?}
{141}{}{胡佛大坝。你拥有这个电台的一部分吗？}
#{142}{}{Have you ever been involved with narcotics?}
{142}{}{你有没有和毒品有关？}
#{143}{}{This is a warning. If I find that you were involved in these crimes - would be better if you disappear from this planet.}
{143}{}{这是一个警告。如果我发现你参与了这些罪行-如果你从这个星球上消失会更好。}
#{144}{}{No more questions. *For now* you??re free.}
{144}{}{没有问题了。*现在你自由了。}
#{145}{}{Oh, we got a tough guy here! Now, if you run out stupid questions, I'm asking you to get out of my office.}
{145}{}{哦，我们这里有个硬汉！现在，如果你没有愚蠢的问题，我要你离开我的办公室。}
#{146}{}{As you wish.}
{146}{}{如你所愿。}
#{147}{}{You know, it was fun to see the a detective that is still alive... And now I'll ask you to leave my office.}
{147}{}{你知道，看到一个还活着的侦探很有趣...现在我要你离开我的办公室。}
#{148}{}{As you wish.}
{148}{}{如你所愿。}
#{149}{}{About "alive" - I will remember that. Keep that in mind, smartass.}
{149}{}{关于“活着”-我会记住的。记住这一点，笨蛋。}
#{150}{}{Just that he is accused of drug production and that he hasn't yet been caught in the act.}
{150}{}{只是他被指控生产毒品，而且他还没有被抓到。}
#{151}{}{The most hostile and skeptical. The Clean City has *no* place for any contagion.}
{151}{}{最具敌意和怀疑的人。清洁的城市没有任何传染的地方。}
#{152}{}{Yes, I do. In the past there was a lot of arguing about it, and the owner came up with the shareholders system, so no one could be left out. Every socially active person in the city aims to have at least a small percentage of shares. And the mayor's office, of course, must keep the greatest possible percentage of it.}
{152}{}{是的，我知道。过去对此争论不休，业主提出了股东制度，所以谁也不能被排除在外。城市里每一个积极参与社会活动的人都希望至少拥有一小部分股份。当然，市长办公室必须尽可能多地保留其中的一部分。}
#{153}{}{Ahem. The city grew on this, but I haven??t used any for many years and have nothing to do with the drugs now.}
{153}{}{啊哼。这个城市是靠这个发展起来的，但我已经很多年没用过了，现在也和毒品没什么关系了。}
#{154}{}{It??s my job. I have to contribute to the development of the city, rather than its degradation or transformation into shooting galleries. This is enough, I hope?}
{154}{}{这是我的工作。我必须为城市的发展做出贡献，而不是让它退化或变成射击馆。我希望这就够了？}
#{155}{}{Oh yes, this is enough for now.}
{155}{}{哦，是的，现在已经够了。}
#{156}{}{Isn??t that too much investment for such small matter?}
{156}{}{对于这样一件小事来说，投资不是太多了吗？}
#{157}{}{That doesn??t concern you.}
{157}{}{这与你无关。}
#{158}{}{Now! Wait a minute! This is serious. It's about the ruin of the city treasury.}
{158}{}{现在！等一下！这是严重的。是关于市财政部的破产。}
#{159}{}{Whatever you say.}
{159}{}{不管你说什么。}
#{160}{}{Damn it! Well why I have to take the rap for the noble deeds?! Why such doubts?! Criminals must be punished, and I do not mind paying a higher fee for a thorough investigation. How much thought did you put into all of this?}
{160}{}{该死的！为什么我要为这些高尚的行为承担责任？！为什么这么怀疑？！犯罪分子必须受到惩罚，我不介意为彻底调查支付更高的费用。你在这件事上花了多少心思？}
#{161}{}{So you deliberately provoke the police to arrest Sam Phillips?}
{161}{}{所以你故意激怒警察逮捕山姆·菲利普斯？}
#{162}{}{Maybe you're right about something. We'll close this question for now.}
{162}{}{也许你是对的。我们暂时结束这个问题。}
#{163}{}{Alright, Mr. detective! Do not cheat and then twist my words. I'm not trying to put behind the bars the innocent, I am sponsoring the police to solve crimes, as I should do. This is my *direct* duty as deputy mayor!}
{163}{}{好的，侦探先生！不要欺骗，然后扭曲我的话。我不是想把无辜的人关进监狱，我是在赞助警察破案，我应该这么做。这是我作为副市长的直接职责！}
#{164}{}{Well, let??s close the issue for now.}
{164}{}{好吧，让我们暂时结束这个问题。}
#{165}{}{Area 51? I think such information should be in our archive. For you, I am willing to take the trouble of 3000, to find it.}
{165}{}{51区？我认为这些信息应该在我们的档案里。为了你，我愿意不辞辛劳的找三千，找到它。}
#{166}{}{How much?! You think, I'm crazy?! Drop it at least to 1000! Otherwise I will leave and you won??t get a penny.}
{166}{}{多少钱？你以为，我疯了？！至少降到1000吧！否则我就走了，你一分钱也拿不到。}
#{167}{}{You have to pay for everything, this is fair. Here is the money.}
{167}{}{你必须为一切付出代价，这是公平的。这是钱。}
#{168}{}{Wow, I don??t have so much right now. Maybe, later.}
{168}{}{哇，我现在没那么多。也许，以后吧。}
#{169}{}{Perhaps you??re right. I drop it to 1000.}
{169}{}{也许你是对的。我把它降到1000。}
#{170}{}{Okay! Here is the money.}
{170}{}{可以！这是钱。}
#{171}{}{I??ll go get the money then.}
{171}{}{那我就去拿钱。}
#{172}{}{I make enough money, to live without your *charity*.}
{172}{}{我赚了足够的钱，没有你的慈善生活。}
#{173}{}{Well okay, okay! Have it your way. Here is 3000 bucks.}
{173}{}{好吧，好吧！随你的便。这是3000美元。}
#{174}{}{I??ll go gather the money then.}
{174}{}{那我就去拿钱。}
#{175}{}{You managed to find the coordinates of Area 51. Now you can travel there.}
{175}{}{你找到了51区的坐标。现在你可以去那里旅行了。}
#{176}{}{No problem. I will make a request to the archive, and you will have the information delivered.}
{176}{}{没问题。我会向档案馆提出申请，你会把资料交给我的。}
#{177}{}{Okay, I??m leaving.}
{177}{}{好吧，我要走了。}
#{178}{}{It??s done.}
{178}{}{一切都结束了。}
#{179}{}{[You enter the coordinates in your Pip-Boy]}
{179}{}{[在你的Pip Boy中输入坐标]}
#{1120}{}{Sorry, I was looking for the toilet, but entered the wrong door.}
{1120}{}{对不起，我在找厕所，但进错门了。}
#{1121}{}{I came to drain some blood out of you.}
{1121}{}{我是来给你放血的。}
#{1145}{}{Oh we got a tough girl here! Now, if you run out stupid questions, I'm asking you to get out of my office.}
{1145}{}{哦，我们这里有个坚强的女孩！现在，如果你没有愚蠢的问题，我要你离开我的办公室。}
#{1163}{}{Okay, Ms. detective! Do not cheat and then twist my words. I'm not trying to put behind the bars the innocent, I am sponsoring the police to solve crimes, as I should do. This is my *direct* duty as deputy mayor!}
{1163}{}{好的，侦探女士！不要欺骗，然后扭曲我的话。我不是想把无辜的人关进监狱，我是在赞助警察破案，我应该这么做。这是我作为副市长的直接职责！}
#{1166}{}{How much?! You think, I'm crazy?! Drop it at least to 1000! Otherwise I will leave and you won??t get a penny.}
{1166}{}{多少钱？你以为，我疯了？！至少降到1000吧！否则我就走了，你一分钱也拿不到。}
