#{100}{}{The trader will not let you delve into her cart.}
{100}{}{那个商人不会让你去钻研她的购物车。}
#{101}{}{Obviously, fixing this cart without additional scrap will not work.}
{101}{}{显然，没有额外的废料来修理这辆车是行不通的。}
#{102}{}{You don't see the need to do this.}
{102}{}{你没必要这么做。}
#{103}{}{This cart is no longer needs to be repaired.}
{103}{}{这辆手推车不再需要修理了。}
#{104}{}{With your skills, you can only do harm here.}
{104}{}{以你的技能，你只能在这里造成伤害。}
#{105}{}{This is not the best solution.}
{105}{}{这不是最好的解决办法。}
#{106}{}{You successfully repaired the cart, replacing some parts.}
{106}{}{您成功地修复了购物车，更换了一些部件。}
#{107}{}{Done}
{107}{}{多恩}
