#{100}{}{You see: Maintenance Computer.}
{100}{}{你看：维修电脑。}
#{101}{}{You see a Maintenance Service computer, currently displaying a password prompt.}
{101}{}{您将看到维护服务计算机，当前显示密码提示。}
#{120}{}{You see Joshua's personal computer with access to the maintenance service server.}
{120}{}{你看到约书亚的个人电脑可以访问维护服务服务器。}
#{121}{}{Read about citizen regulations.}
{121}{}{了解公民条例。}
#{122}{}{Study entries about the wasteland around the Vault.}
{122}{}{研究有关金库周围荒地的条目。}
#{123}{}{Read the requisition for servants.}
{123}{}{读一下仆人的请求书。}
#{124}{}{Research the nearby nuclear power plant.}
{124}{}{研究附近的核电站。}
#{125}{}{Fake a requisition for a fuse from the warehouse.}
{125}{}{伪造仓库的保险丝申请单。}
#{126}{}{[Leave]}
{126}{}{[离开]}
#{130}{}{The citizen regulations are long and boring, but Joshua has highlighted some points he deemed important. 1. Citizens must avoid direct physical contact. 2. Citizens are forbidden from leaving the City without authorization. 3. Discussion of the leadership's activities is only permitted during Council meetings. 4. Communication between subdivisions is only permitted through memorandum, unless in extreme circumstances. }
{130}{}{《公民条例》冗长乏味，但约书亚强调了他认为重要的几点。1公民必须避免直接身体接触。2公民未经批准不得离开城市。三。只有在理事会会议期间才允许讨论领导层的活动。4除非在极端情况下，分部之间的沟通只能通过备忘录进行。}
#{131}{}{You study the reports from patrols around Vault City. This will help you in your journey.}
{131}{}{你研究金库城巡逻队的报告。这将有助于你的旅程。}
#{132}{}{Outdoorsman skill increased by 3%.}
{132}{}{户外技能提高3成。}
#{133}{}{The report concerns an abandoned nuclear power plant north of Vault City. There isn't much information, as the plant's heavy background radiation prevents detailed investigation. You copy the plant's coordinates to your Pip-Boy.}
{133}{}{报告涉及金库市北部一座废弃的核电站。目前没有太多的信息，因为核电站的背景辐射太强，无法进行详细的调查。你把植物的坐标复制给你的小男孩。}
#{134}{}{The report concerns an abandoned nuclear power plant north of Vault City. There isn't much information, as the plant's heavy background radiation prevents detailed investigation.}
{134}{}{报告涉及金库市北部一座废弃的核电站。目前没有太多的信息，因为核电站的背景辐射太强，无法进行详细的调查。}
#{135}{}{A memo from Joshua: "Requesting that five (5) servants be assigned to technical maintenance department for field work in conditions unsafe for citizens due to radiation."}
{135}{}{约书亚的一份备忘录：“要求指派五（5）名仆人到技术维修部，在辐射对公民不安全的条件下进行实地工作。”}
#{136}{}{Read security division's response.}
{136}{}{阅读安全部门的回复。}
#{137}{}{"In order to fulfill your request, the medical department must provide confirmation that the servants in question are suitable for the specified assignment."}
{137}{}{为了满足您的要求，医务部门必须提供有关雇员适合指定任务的确认书}
#{138}{}{Read medical division's response.}
{138}{}{阅读医疗部门的回复。}
#{139}{}{"The medical department doesn't have the responsibility to answer to maintenance department. Please, inquire into the security department."}
{139}{}{“医疗部门没有责任向维修部门负责。请向安全部门查询。”}
#{140}{}{Read security division's response.}
{140}{}{阅读安全部门的回复。}
#{141}{}{"In order to fulfill your request, the medical department must provide confirmation that the servants in question are suitable for the specified assignment."}
{141}{}{为了满足您的要求，医务部门必须提供有关雇员适合指定任务的确认书}
#{142}{}{To understand recursion, you must first understand recursion...}
{142}{}{要理解递归，首先必须理解递归。。。}
#{150}{}{You need Joshua's personal identification to access this computer. Obviously you won't get it from him, so you'll have to hack the system.}
{150}{}{你需要乔舒亚的身份证才能进入这台电脑。显然你不会从他那里得到它，所以你必须破解系统。}
#{151}{}{Let's try...}
{151}{}{让我们试试。。。}
#{152}{}{You managed to crack the code and log an order with the warehouse! Unfortunately, that exceeded the permitted requisitions limit for this division. You probably shouldn't try this again.}
{152}{}{你破解了密码，把订单记录在仓库里了！不幸的是，这超过了该部门允许的申购限额。你可能不应该再这样做了。}
#{153}{}{Great!}
{153}{}{太好了！}
#{154}{}{You couldn't break into the system. Looks like you don't have enough knowledge in this area.}
{154}{}{你不能闯入系统。看来你在这方面的知识还不够。}
#{155}{}{}
{155}{}{}
#{156}{}{Your intellectual abilities are clearly not high enough to even grasp the concept of hacking.}
{156}{}{你的智力水平显然还不足以掌握黑客的概念。}
