#{100}{}{You see a sentry.}
{100}{}{你看见一个哨兵。}
#{101}{}{So, who is here? As you can guess, this is a sentry!}
{101}{}{那么，谁来了？你可以猜到，这是个哨兵！}
#{102}{}{Come in, come in, don't worry.}
{102}{}{进来，进来，别担心。}
#{103}{}{First I'll chop your hands off, then legs, and after that you can start asking questions!}
{103}{}{首先我要砍掉你的手，然后是腿，然后你就可以开始问问题了！}
#{110}{}{Wait! Holster your weapon! Discharge the rifle and put it to the belt! Now!}
{110}{}{等待！把你的枪藏起来！把枪放在皮带上！现在！}
#{111}{}{Why is this necessary? You afraid that I'll start the fourth world war?}
{111}{}{为什么这是必要的？你怕我发动第四次世界大战？}
#{112}{}{Okay, I'll put it away.}
{112}{}{好吧，我把它收起来。}
#{113}{}{Last warning! Put the gun down! Fast!}
{113}{}{最后警告！把枪放下！快点！}
#{114}{}{Still, why do you need it? It's an unsafe place?..}
{114}{}{不过，你为什么需要它？是个不安全的地方？。。}
#{115}{}{All right, see? I putting it away.}
{115}{}{好吧，看到了吗？我把它收起来了。}
#{116}{}{This is the territory of a military garrison. Outsiders without permission are forbidden here.}
{116}{}{这是驻军的领地。未经允许，外人不得在此逗留。}
#{117}{}{I've got business there.}
{117}{}{我在那里有事。}
#{118}{}{How can I get permission?}
{118}{}{我怎样才能得到许可？}
#{119}{}{You mean I can't get through? Well, I'm leaving.}
{119}{}{你是说我打不通？好吧，我要走了。}
#{120}{}{You CAN'T, you idiot! You have nothing to do there. Turn around if you don't want a bullet in the forehead.}
{120}{}{你不能，你这个白痴！你在那没什么可做的。如果你不想让子弹打中前额就转过身来。}
#{121}{}{Now listen to me, you filth, if you're still...}
{121}{}{听我说，你这个混蛋，如果你还...}
#{122}{}{Permission, huh? [darkly grins and squints at the neighbors] Well, we can discuss your problem, if you're interested...}
{122}{}{允许吗？[阴沉地笑着斜视着邻居]好吧，我们可以讨论你的问题，如果你有兴趣的话...}
#{123}{}{Of course, you *can* [wink and take $100 out of the pocket].}
{123}{}{当然，你可以从口袋里拿出100美元。}
#{124}{}{Hmm... I think this is a hint to something?}
{124}{}{Hmm...我想这是个暗示？}
#{125}{}{[His face becomes very unhappy] Go here! Come on!}
{125}{}{[他的脸变得很不高兴]过来！加油！}
#{126}{}{Oh... That's how you speak?}
{126}{}{哦...你就是这么说的？}
#{127}{}{Okay. Finally.}
{127}{}{可以。最后。}
#{128}{}{Bye.}
{128}{}{再见。}
#{129}{}{How? Well... It's a serious place. The passage is worth 300 bucks.}
{129}{}{怎样？好...这是个严肃的地方。这条通道价值300美元。}
#{130}{}{300? Why one has to pay for the passage to a residential area? Who decides it, dammit?!}
{130}{}{300? 为什么要付去居民区的路费？谁决定的，该死的？！}
#{131}{}{All right, here is the money.}
{131}{}{好的，这是钱。}
#{132}{}{Be careful out there... The locals do not favor outsiders.}
{132}{}{小心外面...当地人不喜欢外人。}
#{133}{}{Bye!}
{133}{}{再见！}
#{134}{}{Yeah? What kind of?}
{134}{}{是 啊？什么样的？}
#{135}{}{I need to go to the bathroom... Although, I'd rather do it elsewhere. Bye.}
{135}{}{我要去洗手间...不过，我宁愿在别的地方做。再见。}
#{136}{}{I deal with Nuka-Cola supplies, I think, the Wind of War will not refuse to trade.}
{136}{}{我经营努卡可乐用品，我想，战争之风不会拒绝贸易。}
#{137}{}{I traveled to Hawthorne and found interesting information about your settlement.}
{137}{}{我去了霍桑，发现了关于你们定居点的有趣信息。}
#{138}{}{I have a box of large-caliber ammunition for machine guns. Maybe we could make a deal.}
{138}{}{我有一盒大口径机枪弹药。也许我们可以做个交易。}
#{139}{}{I'm looking for the instigators of the raid on the caravan from Vegas.}
{139}{}{我在找袭击维加斯商队的策划者。}
#{140}{}{I need to see General Wesker for a personal matter.}
{140}{}{我要见韦斯克将军谈一件私事。}
#{141}{}{Wesker?.. Well. You can pass. But we need to check your belongings on the presence of dangerous objects.}
{141}{}{韦斯克？。。好。你可以通过。但我们需要检查你的物品是否有危险物品。}
#{142}{}{Finally.}
{142}{}{最后。}
#{143}{}{Wesker? And why should I buy into this nonsense?}
{143}{}{韦斯克？我为什么要相信这些废话？}
#{144}{}{I don't know...}
{144}{}{我不知道...}
#{145}{}{[Sarcastic] What a surprise. Now turn around and go back to the Wasteland. Here is a military garrison, we don't have any raiders here. Do you understand? Great. And if you insist - one less impudent person would wander the earth.}
{145}{}{[讽刺]真是个惊喜。现在掉头回荒地去。这里有一个军事要塞，我们这里没有袭击者。你明白吗？伟大的。如果你坚持的话，一个不那么厚颜无耻的人会在地球上游荡。}
#{146}{}{Grr...}
{146}{}{Grr...}
#{147}{}{Oh... Well, then I'll allow you to pass. But we need to check your belongings on the presence of dangerous objects.}
{147}{}{哦...好吧，那我就让你过去。但我们需要检查你的物品是否有危险物品。}
#{148}{}{Okay, thanks.}
{148}{}{好的，谢谢。}
#{149}{}{It's forbidden to bring drugs and alcohol in here. Keep the weapon in the holster. If we see you armed... Blame yourself. All is clear? About Wesker: up the street until it ends, then enter the building on the right.}
{149}{}{这里禁止携带毒品和酒精。把枪放在枪套里。如果我们看到你持枪...怪你自己。一切都清楚了？关于韦斯克：沿着这条街一直走到尽头，然后进入右边的大楼。}
#{150}{}{Then check.}
{150}{}{然后检查。}
#{151}{}{No way!}
{151}{}{不可能！}
#{152}{}{}
{152}{}{}
#{153}{}{Okay. I'll lay out these things and come back.}
{153}{}{可以。我把这些东西摆好再回来。}
#{154}{}{This ain't a store, you dimwit, but a military base! Shop's there! [waving at the building behind you]}
{154}{}{这不是商店，笨蛋，而是军事基地！商店在那里！[向你身后的大楼挥手]}
#{155}{}{I know, but the shopkeeper refuses to bargain without the permission of Wesker.}
{155}{}{我知道，但是店主没有韦斯克的允许就拒绝讨价还价。}
#{156}{}{Right, I will go to him.}
{156}{}{好的，我去找他。}
#{157}{}{Because he personally gave me a job in Hawthorne. Don't believe me? Then contact him by the radio!}
{157}{}{因为他亲自给了我一份霍桑的工作。不相信我？然后用无线电联系他！}
#{158}{}{Because I found the important documents in Hawthorne that will be of interest to General.}
{158}{}{因为我在霍桑找到了将军感兴趣的重要文件。}
#{159}{}{}
{159}{}{}
#{160}{}{No, it is forbidden to bring drugs and alcohol in here. You'll have to leave. [Shows on the subject: }
{160}{}{不，这里禁止携带毒品和酒精。你得走了。[主题显示：}
#{161}{}{]}
{161}{}{]}
#{162}{}{Okay, I'll be back.}
{162}{}{好的，我会回来的。}
#{163}{}{This case is confidential and isn't of your concern.}
{163}{}{这个案子是机密，不关你的事。}
#{164}{}{Hold your tongue. If you really have business here, then why I have no orders on your account?}
{164}{}{住嘴。如果你真的在这里有生意，那为什么我没有你的订单？}
#{165}{}{Because your office is a mess. So stop wasting time, your General is waiting for me.}
{165}{}{因为你的办公室一团糟。别浪费时间了，你的将军在等我。}
#{166}{}{I don't know. So you don't let me in? Okay, but I'll be back...}
{166}{}{我不知道。所以你不让我进去？好的，但我会回来的...}
#{170}{}{Come in, come in, don't just stay in there.}
{170}{}{进来，进来，别呆在里面。}
#{171}{}{Wait, let me piss on your leg first. That's how we act friendly in the Wasteland.}
{171}{}{等等，让我先在你腿上撒尿。这就是我们在荒地里表现友好的方式。}
#{172}{}{Okay.}
{172}{}{可以。}
#{173}{}{Eh?! What a savagery! Move away from me!}
{173}{}{嗯？！真野蛮！离我远点！}
#{174}{}{Ha, a big muscular guy with a big gun afraid to dirty himself a bit in the urine!}
{174}{}{哈，一个肌肉发达的家伙，拿着一把大枪，害怕在尿中弄脏自己！}
#{175}{}{I will not insist, as you wish.}
{175}{}{我不会如你所愿坚持的。}
#{176}{}{So, running into troubles? You want to get into our jail for a couple of days? Well, we'll organize it fast!}
{176}{}{那么，遇到麻烦了？你想进我们的监狱几天吗？好吧，我们会尽快组织起来的！}
#{177}{}{For such a loser like you to threaten me with jail? [spit under the feet] You have run up on the wrong person!}
{177}{}{像你这样的失败者用监狱来威胁我？你找错人了！}
#{178}{}{Okay, sure, I'll just go quietly and peacefully.}
{178}{}{好的，当然，我会安静地走。}
#{179}{}{[Speaking through clenched teeth] That's it, scum, hold on, I've had enough of these jokes! [aims a gun at you]}
{179}{}{[咬紧牙关]够了，人渣，等等，我受够了这些笑话！[用枪指着你]}
#{180}{}{Okay, really, enough with the jokes.}
{180}{}{好吧，真的，别开玩笑了。}
#{181}{}{Shut up! Hands behind your head! Now! Now you'll go and sit in jail a full day!}
{181}{}{闭嘴！把手放在脑后！现在！现在你要坐牢一整天了！}
#{182}{}{Whatever, I won't resist...}
{182}{}{不管怎样，我不会反抗...}
#{183}{}{In jail?! Me?! Fuck you!}
{183}{}{在监狱里？！我？！去你妈的！}
#{184}{}{Oh, will I get a lunch there? It would be nice.}
{184}{}{哦，我能在那里吃午饭吗？那太好了。}
#{185}{}{It's rubber tire with sauce of sulfur and concrete crumbs for lunch in our jail. Want to try out? Always at your service!}
{185}{}{在我们的监狱里午餐用的是橡胶轮胎加硫磺酱和水泥屑。想试试吗？随时为您服务！}
#{190}{}{The General was talking about some incident with a couple of rednecks on this post. Tell me more.}
{190}{}{将军说了一些关于这个岗位上几个乡巴佬的事情。告诉我更多。}
#{191}{}{[Shrugs indifferently] Some old man from the Wasteland was trying to break the fence. Got punched in the cheek and a kicked in the ass, then was sent back. Perhaps, now he's at the train station, licking his bruises. There was the girl with him. And what a fool she is.}
{191}{}{[冷漠地耸耸肩]一个来自荒地的老人试图打破篱笆。脸上挨了一拳，屁股上挨了一脚，然后就被送回了。也许，现在他在火车站，舔着伤痕。他身边有个女孩。她真是个傻瓜。}
#{192}{}{Yeah.}
{192}{}{是 啊。}
#{1137}{}{I traveled to Hawthorne and found interesting information about your settlement.}
{1137}{}{我去了霍桑，发现了关于你们定居点的有趣信息。}
#{1145}{}{[Sarcastic] What a surprise. Now turn around and go back to the Wasteland. Here is a military garrison, we don't have any raiders here. Do you understand? Great. And if you insist - one less impudent person would wander the earth.}
{1145}{}{[讽刺]真是个惊喜。现在掉头回荒地去。这里有一个军事要塞，我们这里没有袭击者。你明白吗？伟大的。如果你坚持的话，一个不那么厚颜无耻的人会在地球上游荡。}
#{1158}{}{Because I found the important documents in Hawthorne that will be of interest to General.}
{1158}{}{因为我在霍桑找到了将军感兴趣的重要文件。}
