#{100}{}{You see a private.}
{100}{}{你看到一个私人。}
#{101}{}{It's a private, a soldier of the lowest rank.}
{101}{}{是个二等兵，一个最低级的士兵。}
#{102}{}{Alarm! We're under attack!}
{102}{}{警报！我们受到攻击了！}
#{103}{}{I warned you! Someone's gonna get punished!}
{103}{}{我警告过你！有人会受到惩罚的！}
#{110}{}{Hold it! You're not allowed in the barracks. Get out. Move!}
{110}{}{别动！你不能进军营。走出。快走！}
#{111}{}{I walk wherever I want, got it, grunt? Or shall I show you in mime?}
{111}{}{我想去哪儿就去哪儿，明白吗，格伦特？还是让我给你看哑剧？}
#{112}{}{Barracks? I thought it was a hotel of some sort...}
{112}{}{兵营？我以为那是个旅馆。。。}
#{113}{}{What? You again?! Look, I don't like this. If I see you in the barracks again, I'll tear you, limb from limb, *personally*! Understood?}
{113}{}{什么？又是你？！听着，我不喜欢这样。如果我再看到你在军营里，我会把你撕成碎片，从一个碎片到另一个碎片，*我个人*！理解？}
