#{100}{}{You see a punching bag.}
{100}{}{你看到一个打孔袋。}
#{101}{}{You see a punching bag. It's like inviting you to try it out. You almost hear "Don't miss the opportunity!" in your head.}
{101}{}{你看到一个打孔袋。就像邀请你去尝试一样。你几乎听到“不要错过机会！”在你的脑子里。}
#{102}{}{You can warm up your fists and try out new methods of fighting on this bag.}
{102}{}{你可以在这个包上热身一下拳头，试试新的格斗方法。}
#{103}{}{Hmm, why not?}
{103}{}{嗯，为什么不呢？}
#{104}{}{The bag was so dilapidated after your training that it became unusable.}
{104}{}{经过你的训练，这个包已经破旧不堪，不能再用了。}
#{105}{}{This bag is useless}
{105}{}{这个包没用}
#{106}{}{This bag could be useful for your skills, but they are already too high.}
{106}{}{这个包可能对你的技能有用，但它们已经太高了。}
#{107}{}{Training? I don't need this anymore...}
{107}{}{培训？我不再需要这个了。。。}
#{108}{}{You spend two hours in training and increase your unarmed skill by 5%.}
{108}{}{你花了两个小时在训练中，你的徒手技能提高了5%。}
#{109}{}{Good work!}
{109}{}{干得好！}
