#{100}{}{You see surveillance monitor screen.}
{100}{}{你看到监控屏幕了。}
#{101}{}{You see surveillance monitor screens tracking vault's rooms.}
{101}{}{你看到监控屏幕跟踪保险库的房间。}
#{110}{}{You see surveillance monitor screens tracking vault's rooms. The screens show corridors and some public spaces.}
{110}{}{你看到监控屏幕跟踪保险库的房间。屏幕显示走廊和一些公共空间。}
#{111}{}{[Examine 2nd level]}
{111}{}{[检查第二级]}
#{112}{}{[Examine 3rd level]}
{112}{}{[检查第三级]}
#{113}{}{[Examine 4th level]}
{113}{}{[检查第四级]}
#{114}{}{[Leave]}
{114}{}{[离开]}
#{120}{}{On the second level there are residential and recreational rooms. There is huge mess in these rooms, apparently cleaning wasn't conducted in many years. At the end of the main corridor, near the elevator, the wall collapsed from the blast.}
{120}{}{在第二层有住宅和娱乐室。这些房间里乱七八糟的，显然很多年没有打扫了。在主走廊的尽头，靠近电梯的地方，墙壁因爆炸而倒塌。}
#{121}{}{On the third level there are technical and service rooms, including the overseer's post and power station.}
{121}{}{在第三层有技术室和服务室，包括监督所和发电站。}
#{122}{}{The fourth level is not monitored. The feel of mystery and malice doesn't leave you.}
{122}{}{第四级不受监控。神秘和恶意的感觉不会离开你。}
