#{10}{}{You see a grave cross.}
{10}{}{你看到一个坟墓十字架。}
#{11}{}{You see a grave stone.}
{11}{}{你看到一块墓石。}
#{12}{}{You see a grave plate.}
{12}{}{你看到一个墓碑。}
#{20}{}{On the cross is written: "}
{20}{}{十字架上写着：“}
#{21}{}{On the grave plate is written: "}
{21}{}{墓碑上写着：“}
#{22}{}{}
{22}{}{}
#{23}{}{"}
{23}{}{"}
#{24}{}{There was a writing here, but it's been erased by time.}
{24}{}{这里有一段文字，但被时间抹去了。}
#{25}{}{This cross is blank.}
{25}{}{这个十字架是空的。}
#{30}{}{The graveyard of buried ideas.}
{30}{}{埋葬思想的墓地。}
#{100}{}{Ahiga the Smashing Blow. In the fields of Eternal Hunt, strike at servants of the Devourer with your spear...}
{100}{}{阿希加猛击。在永恒的狩猎之地，用你的长矛攻击吞食者的仆人。。。}
#{101}{}{Mechitehyu the Moonlight Shadow. His spirit still walks with the Night Winds...}
{101}{}{月光的影子。他的灵魂仍然与夜风同行。。。}
#{102}{}{Pouoka the Watcher through Time: 1877 - the Cheyenne's autumn, 2077 - the end of the Old World, 2277 - let the Legion come...}
{102}{}{《穿越时间的守望者：1877年夏延的秋天，2077年旧世界的终结，2277年——让军团来吧。。。}
#{103}{}{Otaktay the Torturing Wolf. He favored the war axe over the peace pipe.}
{103}{}{奥塔克泰折磨着狼。他喜欢战斧胜过和平烟斗。}
#{150}{}{Freddie "Gorefiend" Voorhees: They named the "Ripper" after me, baby!}
{150}{}{弗雷迪“Gorefiend”沃赫斯：他们以我的名字命名“开膛手”，宝贝！}
#{151}{}{Dallas "Evil Kitty" Ocasec. A hot little thing that will feel cold even in the depths of hell.}
{151}{}{达拉斯“邪恶的小猫”奥卡斯。一个热的小东西，即使在地狱深处也会觉得冷。}
#{152}{}{Nick "Savage" Eckhart. 17 kills, 4 robberies, 9 rapes - and thats in only one week.}
{152}{}{尼克“萨维奇”埃克哈特。17起谋杀，4起抢劫，9起强奸——仅仅一周时间。}
#{153}{}{Arkin "Shiz" Fernandez. Hated his family so much that after a week without them blew his brains out to continue torturing them in hell.}
{153}{}{阿金·费尔南德斯。他非常恨他的家人，在一个星期没有家人的情况下，他把脑袋炸了，继续在地狱里折磨他们。}
#{154}{}{Kevin "The Postman" Brooks. Philanthropist, family man, sadistic cannibal.}
{154}{}{凯文“邮差”布鲁克斯。慈善家，家庭男人，残暴的食人族。}
#{155}{}{Patrick "Not a day without pain," Bale. Satan sent him, Satan took him back.}
{155}{}{帕特里克“不是没有痛苦的一天”，贝尔。撒但差遣他，撒但把他带回来。}
#{156}{}{Stephen "Arrow" Travis. He only loved his dog, Lilly... In a good way, asshole!}
{156}{}{斯蒂芬·阿罗·特拉维斯。他只爱他的狗莉莉。。。很好，混蛋！}
#{200}{}{Brunson, Phil. Excellent evening - pleasant company - 8 bribes - myocardial infarction.}
{200}{}{布伦森，菲尔。美好的夜晚-愉快的陪伴-8次贿赂-心肌梗塞。}
#{201}{}{Chris Buddy. Rare bitch - folded with three aces.}
{201}{}{克里斯·巴迪。罕见的婊子-有三个A。}
#{202}{}{Johnny "Zero" Hellmuth. The real player is never too poor to buy chips while he has two kidneys.}
{202}{}{约翰尼“零”赫尔默斯。真正的球员在有两个肾的时候，永远不会穷到买不到筹码。}
#{203}{}{Mordechai Ungar. He was called by the lights of Vegas, and his dreams burned up in them.}
{203}{}{莫德凯·昂加。他被维加斯的灯光召唤，他的梦想在灯光中燃烧。}
#{204}{}{Oscar "Toothy" Manfredi. I'm silent in the ring, because my fists do the talking.}
{204}{}{奥斯卡“牙齿”曼弗雷迪。我在拳击场上保持沉默，因为我的拳头在说话。}
#{250}{}{Patricia Whitman. My love for you was like a nuclear explosion - beautiful, dazzling and deadly...}
{250}{}{帕特里夏·惠特曼。我对你的爱就像核爆炸一样美丽，耀眼，致命。。。}
#{251}{}{Michael "Runner" Phelps. He ran his last hundred yards without a head on his shoulders.}
{251}{}{迈克尔菲尔普斯。他跑完最后一百码，头也没抬起来。}
#{252}{}{Marion Connelly. She died of an overdose - but kept her promise to quit smoking.}
{252}{}{马里恩·康纳利。她死于吸毒过量，但遵守了戒烟的诺言。}
#{253}{}{Lorenz Tate. In these parts we still shoot the messenger.}
{253}{}{洛伦兹·泰特。在这些地方，我们仍在射击信使。}
#{254}{}{Martin "Nomad" Wallace. The last romantic traveler.}
{254}{}{马丁“游牧民”华莱士。最后一个浪漫的旅行者。}
#{300}{}{Gabriel "Jesuit" Borgia. He did not drink, smoke or swear, but the deathclaw was not impressed.}
{300}{}{加布里埃尔“耶稣会”博尔贾。他既不喝酒，也不抽烟，也不骂人，但死亡爪却没有留下深刻的印象。}
#{301}{}{Oliver Smith. "I experienced one day of judgment - to rise to the second!"}
{301}{}{奥利弗·史密斯。”我经历了一天的审判——上升到第二天！”}
#{302}{}{Fuzzy, Gourmet and Striped Tail. To kill women, children and the elderly is understandable. But what monster could harm a cat?!}
{302}{}{毛茸茸的，美味的，有条纹的尾巴。杀害妇女、儿童和老人是可以理解的。但是什么怪物能伤害猫？！}
#{303}{}{Oliver Rigdon. That's all that was known about him.}
{303}{}{奥利弗·里格登。这就是他所知道的一切。}
#{304}{}{Vic Allison. Realized too late that "Aqua Regia" was not the new drink at the "Lead Angel".}
{304}{}{维克·艾莉森。意识到“王水”不是“天使领队”的新饮料为时已晚。}
#{305}{}{Hayley Ross. Her husband had no faith in her immaculate conception.}
{305}{}{海莉·罗斯。她丈夫对她完美的怀孕没有信心。}
#{306}{}{Adam "Cleaner" Garner. He did dirty work... And was cleaned himself in the end.}
{306}{}{亚当“清洁”加纳。他干脏活。。。最后他自己洗干净了。}
#{307}{}{George "Commie" Glick. Oh, here you will not get me, you greedy dogs of capitalism!}
{307}{}{乔治“共产党员”格利克。哦，你不会抓到我的，你们这些贪婪的资本主义狗！}
#{308}{}{Johnny Melton. "As man is now, as was the Lord once, as Lord is now, as was the man"}
{308}{}{约翰尼·梅尔顿。”现在怎样，从前怎样，现在怎样，从前怎样}
#{309}{}{Joseph Harris. "...And shall put my arms to the grave, in order and at the threshold of death, I tirelessly served our Creator..."}
{309}{}{约瑟夫哈里斯“。。。我将把我的手臂放在坟墓里，在死亡的边缘，我不知疲倦地为我们的造物主服务……”}
#{310}{}{Unknown. His last words were: "I will wait for you at the gates of hell, sinners!"}
{310}{}{未知。他的遗言是：“我会在地狱门口等你，罪人！”}
#{350}{}{Captain Benjamin Kurtz. Gone to hell to regroup.}
{350}{}{本杰明·库尔茨上尉。下地狱重新集结。}
#{351}{}{Private First Class Chris "Dull" Lerner. Always smiled while killing.}
{351}{}{一等兵克里斯“迟钝”勒纳。杀人时总是微笑。}
#{352}{}{Corporal James Hartman. He would have forgotten his mother's name over the serial number of his personal weapon.}
{352}{}{詹姆斯·哈特曼下士。他会忘记他母亲的名字而忘记他的私人武器的序列号。}
#{353}{}{Mayor Alex "Gravedigger" Turchin. Where we pass, for a long time is silence.}
{353}{}{市长亚历克斯“掘墓人”图尔钦。我们经过的地方，沉默了很久。}
#{354}{}{Sergeant Richard "Nuclear" Beckett. Invisible, pervasive and deadly.}
{354}{}{理查德中士“核”贝克特。无形的，无处不在的，致命的。}
#{400}{}{Luciano Marin.}
{400}{}{卢西亚诺·马林。}
