# 
# Inventory messages from inventry.c
#
### {0}{}{ST}
{0}{}{ST公司}
### {1}{}{PE}
{1}{}{体育课}
### {2}{}{EN}
{2}{}{EN}
### {3}{}{CH}
{3}{}{CH}
### {4}{}{IN}
{4}{}{在}
### {5}{}{AG}
{5}{}{银}
### {6}{}{LK}
{6}{}{LK语言}
### {7}{}{Hit Points}
{7}{}{命中点}
### {8}{}{Armor Class}
{8}{}{护甲等级}
### {9}{}{  Normal}
{9}{}{典型的}
### {10}{}{  Laser}
{10}{}{激光}
### {11}{}{  Fire}
{11}{}{火}
### {12}{}{  Plasma}
{12}{}{血浆}
### {13}{}{  Explode}
{13}{}{爆炸}
### {14}{}{No item}
{14}{}{无项目}
### {15}{}{Dmg:}
{15}{}{数据毫克：}
### {16}{}{Rng:}
{16}{}{雷诺数：}
### {17}{}{Ammo:}
{17}{}{弹药：}
### {18}{}{(Not worn)}
{18}{}{（未磨损）}
### {19}{}{You don't have enough action points to use inventory.}
{19}{}{你没有足够的行动点来使用库存。}
### {20}{}{Total Wt:}
{20}{}{总重量：}
### {21}{}{MOVE ITEMS}
{21}{}{移动项目}
### {22}{}{ALL}
{22}{}{全部}
### {23}{}{SET TIMER}
{23}{}{设置计时器}
### {24}{}{Unarmed dmg:}
{24}{}{无防护dmg：}
### {25}{}{You cannot pick that up. You are at your maximum weight capacity.}
{25}{}{你不能把它捡起来。你已达到最大承重能力。}
### {26}{}{There is no space left for that item.}
{26}{}{该项目已没有剩余空间。}
### {27}{}{OK, that's a good trade.}
{27}{}{好吧，这是一笔不错的交易。}
### {28}{}{No, your offer is not good enough.}
{28}{}{不，你的报价不够好。}
### {29}{}{You gain %d experience points for successfully using your Steal skill.}
{29}{}{成功使用你的潜行技能将获得%d点经验值。}
### {30}{}{Wt.}
{30}{}{重量。}
### {31}{}{Sorry, you cannot carry that much.}
{31}{}{对不起，你不能带那么多东西。}
### {32}{}{Sorry, that's too much to carry.}
{32}{}{对不起，太多了，拿不动。}

### {50}{}{You can't find anything to take from that.}
{50}{}{你找不到任何可以借鉴的东西。}
