#
# ?????????????????????????????????????????????????????????????????????????????
#
# Text labels and messages used by town and world map
#
# ?????????????????????????????????????????????????????????????????????????????
#

#
# Town map selection names
#
# Format:
#	city type.
#	Up to 10 selection names
#
# Vault 13
### {200}{}{Cavern Entrance}
{200}{}{洞穴入口}
### {201}{}{Entrance}
{201}{}{入口}
### {202}{}{Living Quarters}
{202}{}{生活区}
### {203}{}{Command Center}
{203}{}{指挥中心}
#
# Vault 15
### {210}{}{Desert Entrance}
{210}{}{沙漠入口}
### {211}{}{Caverns/Entrance}
{211}{}{洞穴/入口}
### {212}{}{Living Quarters}
{212}{}{生活区}
### {213}{}{Command Center}
{213}{}{指挥中心}
#
# Shady Sands
### {220}{}{Entrance}
{220}{}{入口}
### {221}{}{Garden}
{221}{}{花园}
### {222}{}{Brahmin Pen}
{222}{}{婆罗门笔}
#
# Junktown
### {230}{}{Entrance}
{230}{}{入口}
### {231}{}{Crash House}
{231}{}{急救室}
### {232}{}{Casino}
{232}{}{赌场}
#
# Raiders
### {240}{}{Base}
{240}{}{基础}
#
# Necropolis
### {250}{}{Hotel}
{250}{}{酒店}
### {251}{}{Hall}
{251}{}{门厅}
### {252}{}{Watershed}
{252}{}{转折点}
#
# Hub
### {260}{}{Entrance}
{260}{}{入口}
### {261}{}{Downtown}
{261}{}{市中心}
### {262}{}{Heights}
{262}{}{高度}
### {263}{}{Old Town}
{263}{}{老城区}
### {264}{}{Merchants}
{264}{}{商人}
### {265}{}{Cave}
{265}{}{山洞}
#
# Brotherhood
### {270}{}{Entrance}
{270}{}{入口}
### {271}{}{Level 1}
{271}{}{级别1}
### {272}{}{Level 2}
{272}{}{级别2}
### {273}{}{Level 3}
{273}{}{级别3}
### {274}{}{Level 4}
{274}{}{级别4}
#
# Military Base
### {280}{}{Entrance}
{280}{}{入口}
### {281}{}{Stronghold Level 1}
{281}{}{要塞一级}
### {282}{}{Stronghold Level 2}
{282}{}{要塞二级}
### {283}{}{Vats Level 1}
{283}{}{Vats级别1}
### {284}{}{Vats Level 2}
{284}{}{Vats级别2}
#
# Glow
### {290}{}{Crater}
{290}{}{坑}
### {291}{}{Level 1}
{291}{}{级别1}
#
# Boneyard
### {300}{}{Adytum}
{300}{}{Adytum公司}
### {301}{}{Downtown}
{301}{}{市中心}
### {302}{}{Library}
{302}{}{图书馆}
### {303}{}{Fortress}
{303}{}{要塞}
### {304}{}{Warehouse}
{304}{}{仓库}
#
# Cathedral
### {310}{}{Entrance}
{310}{}{入口}
### {311}{}{Interior}
{311}{}{内部}

# Misc messages
### {500}{}{You gained 10,000 experience points!}
{500}{}{你获得了10000点经验值！}
### {501}{}{Ruins}
{501}{}{废墟}

#
# Terrain type names for world map hover button
#
### {1000}{}{Desert}
{1000}{}{沙漠}
### {1001}{}{Mountains}
{1001}{}{山脉}
### {1002}{}{City}
{1002}{}{城市}
### {1003}{}{Coast}
{1003}{}{海岸}
### {1004}{}{Unknown}  # Unknown/visited city
{1004}{}{未知的}

