### {100}{}{Here is a nomad.}
{100}{}{这是一个游牧民族。}
### {101}{}{You see a man with long black hair.}
{101}{}{你看到一个留着黑色长发的男人。}
### {102}{}{Oh, these mushrooms turned out to be more powerful than I thought...}
{102}{}{哦，这些蘑菇原来比我想象的更厉害。。。}

### {200}{}{What do you need, stranger?}
{200}{}{你需要什么，陌生人？}
### {1200}{}{What do you need, stranger?}
{1200}{}{你需要什么，陌生人？}
### {201}{}{Leave me, stranger.}
{201}{}{离开我，陌生人。}
### {1201}{}{Leave me, stranger.}
{1201}{}{离开我，陌生人。}
### {202}{}{Whoa, why so much distrust?}
{202}{}{哇，为什么这么不信任？}
### {203}{}{Keep pretending you don't understand. I don't need anything from you anyway. But time flows like sand between your fingers. I have to hurry.}
{203}{}{继续假装你不明白。不管怎样，我不需要你给我任何东西。但是时间像沙子一样在你的指间流动。我得抓紧时间。}
### {204}{}{Where are you in a hurry?}
{204}{}{你在哪儿赶时间？}
### {205}{}{My family is preparing to go out into the desert. We should be in time for the start of the dust storm season. And I still can't fix this cart.}
{205}{}{我的家人正准备去沙漠。我们应该及时赶上沙尘暴季节的开始。我还是修不好这辆手推车。}
### {206}{}{Is this really such a problem?}
{206}{}{这真的是个问题吗？}
### {207}{}{Previously, we could exchange parts or ask for one of your palefaces. But now you are waging a war against us. No one will fix the cart except me. And I can't do it.}
{207}{}{以前，我们可以交换零件或索要您的苍白面孔。但现在你们正在对我们发动战争。除了我，没有人会修理马车。我做不到。}
### {208}{}{I can.}
{208}{}{我可以。}
### {209}{}{I don't need anything from outsiders.}
{209}{}{我不需要外人的任何东西。}
### {210}{}{Let me help you. I want to show you that not all outsiders are the same.}
{210}{}{让我来帮你。我想告诉你，并不是所有的局外人都是一样的。}
### {211}{}{Will you do it? Hmm, okay. But I won't give anything in return.}
{211}{}{你会这么做吗？嗯，好吧。但我不会给任何回报。}
### {212}{}{No problems. You can rely on me.}
{212}{}{没有问题。你可以相信我。}
### {213}{}{Nothing at all? Well, then I won't be in a hurry.}
{213}{}{什么都没有？那我就不急了。}
### {214}{}{I'll fix the cart, but not for nothing. The parts are worth the caps, you know.}
{214}{}{我会修这辆车，但不是白修的。你知道，这些零件值这些帽子。}
### {215}{}{It seems that all the palefaces are obsessed with the sound of all sorts of garbage. I don't have anything like that. But if you really fix the cart, I'll give you dried meat.}
{215}{}{似乎所有的苍白面孔都痴迷于各种垃圾的声音。我没有那样的东西。但如果你真的把车修好了，我就给你肉干。}
### {216}{}{I will think about this proposal.}
{216}{}{我会考虑这个建议。}
### {217}{}{Surely you will slip me bad meat. Do the cart yourself.}
{217}{}{你肯定会把坏肉递给我的。自己动手推车。}

### {220}{}{What do you need, stranger?}
{220}{}{你需要什么，陌生人？}
### {1220}{}{What do you need, stranger?}
{1220}{}{你需要什么，陌生人？}
### {221}{}{Leave me, stranger.}
{221}{}{离开我，陌生人。}
### {1221}{}{Leave me alone, stranger.}
{1221}{}{别管我，陌生人。}
### {222}{}{Peace be upon your home.}
{222}{}{愿你的家平安。}
### {223}{}{See you again.}
{223}{}{再见。}

### {230}{}{Your cart is in perfect order.}
{230}{}{您的购物车秩序井然。}
### {231}{}{You really did it! There was so much harm from the Palefaces that I didn't even hope. It's a pity we can't live in peace.}
{231}{}{你真的做到了！苍白派的伤害太大了，我甚至都没想到。遗憾的是我们不能平静地生活。}
### {1231}{}{You really did it! There was so much harm from the Palefaces that I didn't even hope. It's a pity that we can't live in peace.}
{1231}{}{你真的做到了！苍白派的伤害太大了，我甚至都没想到。很遗憾，我们不能平静地生活。}
### {232}{}{And you won't give me anything for this service?}
{232}{}{这次服务你什么都不给我？}
### {233}{}{(sigh) I knew I couldn't trust you. You're just like the rest of the palefaces, thinking only of yourself. That's how we differ from you.}
{233}{}{（叹气）我就知道我不能相信你。你和其他苍白的人一样，只想着自己。这就是我们与你的不同之处。}
### {234}{}{Don't even start.}
{234}{}{甚至不要开始。}
### {235}{}{Isn't it fair to get a reward for your work?}
{235}{}{你的工作得到报酬难道不公平吗？}
### {236}{}{Okay, here's the jerky. But don't ask for anything else. I need to prepare for the journey.}
{236}{}{好的，这是肉干。但不要要求任何其他东西。我需要为这次旅行做准备。}
### {237}{}{Happily.}
{237}{}{高兴地}
### {238}{}{I don't need anything in return. I help for the sake of peace.}
{238}{}{我不需要任何回报。我帮助是为了和平。}
### {239}{}{This is the first time I've seen a disinterested outsider. Thank you. Let the Brahmin of the Wasteland show you the way in a difficult hour.}
{239}{}{这是我第一次看到一个无私的局外人。非常感谢。让荒原的婆罗门在困难的时刻为你指路。}

### {250}{}{What's the problem with fixing the cart?}
{250}{}{修理推车有什么问题？}
### {251}{}{In our tribe, they know how to make leather, but not to repair carts. We used to ask the Palefaces for this in exchange for meat and skins. And now there is no one to ask.}
{251}{}{在我们部落，他们知道如何制作皮革，但不知道如何修理手推车。我们过去常常向帕莱法斯人索要这些，以换取肉和皮。现在没有人可以问了。}
### {252}{}{I see.}
{252}{}{我明白了。}
### {253}{}{Why are you going to the wasteland with your whole family?}
{253}{}{你为什么要和全家一起去荒原？}
### {254}{}{We wander through the Sonoran desert, and in bad seasons, the whole tribe gathers here. Standing still, we will not feed ourselves. Brahmins need grass, and grass needs time to grow. There is not enough local water for everyone either.}
{254}{}{我们在索诺兰沙漠漫步，在恶劣的季节，整个部落都聚集在这里。站着不动，我们不会养活自己。婆罗门需要草，草需要时间来生长。当地也没有足够的水给每个人。}
### {255}{}{I see.}
{255}{}{我明白了。}

### {260}{}{How do you feel about an alliance with outsiders?}
{260}{}{你觉得与外人结盟怎么样？}
### {261}{}{If you chase two mole rats, you'll tear your pants. You can't look both west and east at the same time.}
{261}{}{如果你追逐两只鼹鼠，你会撕破裤子的。你不可能同时向西方和东方看。}
### {262}{}{I think I know what you mean.}
{262}{}{我想我知道你的意思。}
### {263}{}{We must remain ourselves as long as we have enough strength. And if there are not enough forces, then we will no longer decide with whom to make alliances. Whoever is stronger will become a shepherd for us.}
{263}{}{只要我们有足够的力量，我们就必须保持自我。如果没有足够的力量，那么我们将不再决定与谁结盟。谁更强壮，谁就会成为我们的牧羊人。}
### {264}{}{Sorry for such a painful question.}
{264}{}{很抱歉问了这么痛苦的问题。}
