### {110}{}{Does not lend itself.}
{110}{}{不适合自己。}
### {111}{}{You feel a draft coming from between the old boards. Perhaps this flooring hides something, but it is too well boarded up.}
{111}{}{你感觉到一股来自旧董事会之间的气流。也许这块地板藏着什么，但它用木板封得太好了。}
### {112}{}{There are no visible locks here.}
{112}{}{这里没有可见的锁。}
### {113}{}{The descent is cleared.}
{113}{}{下降被清除。}
### {114}{}{You don't find any lock here.}
{114}{}{你在这里找不到锁。}
### {115}{}{Just brute force is needed here.}
{115}{}{这里只需要蛮力。}
