### {100}{}{Here is a robber.}
{100}{}{这是一个强盗。}
### {101}{}{You see one of the highway robbers. The type is not pleasant.}
{101}{}{你看到一个高速公路劫匪。这种类型不讨人喜欢。}

### {110}{}{If we don't get paid, someone will die.}
{110}{}{如果我们得不到报酬，就会有人死。}
### {111}{}{We are not here from a good life.}
{111}{}{我们不是从美好的生活来到这里的。}
### {112}{}{Let the count count the caps if he wants to see his daughter alive.}
{112}{}{如果伯爵想看到他的女儿活着，就让他数帽子吧。}
### {113}{}{I don't want to dirty my hands about the girl, but someone has to do it.}
{113}{}{我不想因为这个女孩而弄脏我的手，但总得有人来做。}
### {114}{}{What did Bustos decide? Come on, spit it out.}
{114}{}{巴斯托斯做了什么决定？来吧，吐出来。}
### {115}{}{I'm running out of patience.}
{115}{}{我快没耐心了。}
### {116}{}{My fingers are itching to shoot someone.}
{116}{}{我的手指很想开枪打别人。}
{117}{}{}
### {118}{}{Don't even think about following us.}
{118}{}{甚至不要考虑跟随我们。}
### {119}{}{Get out of here.}
{119}{}{离开这里。}
