### {100}{}{Here is Kristina.}
{100}{}{这是克里斯蒂娜。}
### {101}{}{You see a girl with a puzzling look. It seems that the easy life has not taught her anything yet.}
{101}{}{你看到一个女孩带着困惑的表情。轻松的生活似乎还没有教会她什么。}
### {102}{}{You see a girl with a sad look. It seems that recent events have made her think deeply.}
{102}{}{你看到一个女孩带着悲伤的表情。最近发生的事情似乎让她深思。}
### {103}{}{Wow, how do you go to the toilet in this thing?}
{103}{}{哇，你怎么穿着这东西上厕所的？}
### {104}{}{Daddy... daddy... he's gone...}
{104}{}{爸爸。。。爸爸。。。他走了。。。}
### {105}{}{Where did you get THIS? Hide it immediately before anyone sees it. Dad's bodyguards immediately shoot at any highway worker.}
{105}{}{你从哪里得到的？在任何人看到它之前立即把它藏起来。爸爸的保镖立即向任何高速公路工作人员开枪。}
### {106}{}{What's going on? Where's my dad?}
{106}{}{怎么回事？我爸爸在哪里？}

### {110}{}{Z-z-z...}
{110}{}{Z-Z-Z。。。}
### {111}{}{Hr-r...}
{111}{}{小时-小时。。。}
### {112}{}{...Daddy, it's too early...}
{112}{}{…爸爸，现在还为时过早。。。}
### {113}{}{...It's not a dream...}
{113}{}{…这不是梦。。。}
### {114}{}{I'm... dreaming...}
{114}{}{我是做梦。。。}
### {115}{}{...It's... a dream...}
{115}{}{…这是…一个梦。。。}
### {116}{}{Do you know what time it is now?}
{116}{}{你知道现在几点了吗？}
### {117}{}{I want to sleep.}
{117}{}{我想睡觉。}
### {118}{}{Don't disturb my sleep.}
{118}{}{不要打扰我的睡眠。}
### {119}{}{Let me sleep.}
{119}{}{让我睡吧。}

### {120}{}{*Humming*}
{120}{}{*嗡嗡作响*}
### {121}{}{A great day for practical jokes.}
{121}{}{开恶作剧的好日子。}
### {122}{}{Maybe offer that newcomer a poker game?}
{122}{}{也许给那个新人一场扑克游戏？}
### {123}{}{We need to ask for more caps from Daddy.}
{123}{}{我们需要向爸爸要更多的帽子。}
### {124}{}{Nothing, Daddy will forgive me.}
{124}{}{没什么，爸爸会原谅我的。}
### {125}{}{Eh, how boring...}
{125}{}{呃，好无聊。。。}
### {126}{}{What would you like to do?}
{126}{}{你想做什么？}
### {127}{}{Water, caps. caps, water. They can't think of anything else?}
{127}{}{水，盖。盖子，水。他们想不出其他什么了？}
### {128}{}{I would like to see the neon Phoenix again.}
{128}{}{我想再次看到霓虹灯下的凤凰。}
### {129}{}{It got really boring without a bar.}
{129}{}{没有酒吧真的很无聊。}

### {130}{}{Ah...}
{130}{}{啊。。。}
### {131}{}{*Sigh*}
{131}{}{*叹气*}
### {132}{}{I don't even want to play cards.}
{132}{}{我甚至不想打牌。}
### {133}{}{Why did it happen like this?}
{133}{}{为什么会这样？}
### {134}{}{A terrible story.}
{134}{}{一个可怕的故事。}
### {135}{}{I won't be able to live as before.}
{135}{}{我将不能再像以前那样生活了。}
### {136}{}{I don't understand how it could have turned out like this?}
{136}{}{我不明白怎么会变成这样？}
### {137}{}{Why did people become so angry?}
{137}{}{为什么人们变得如此愤怒？}
{138}{}{}
{139}{}{}

#Acquaintance
### {200}{}{Oh, hello. New faces are always so interesting. My name is Kristina. Are you here for a long time?}
{200}{}{哦，你好。新面孔总是那么有趣。我的名字叫克里斯蒂娜。你在这里很长时间了吗？}
### {201}{}{Well, I...}
{201}{}{嗯，我。。。}
### {202}{}{Come on, stay, it's good here. Although the city, of course, is boring. I'm just dying without gambling.}
{202}{}{来吧，留下来，这里很好。当然，尽管这个城市很无聊。没有赌博我就要死了。}
### {203}{}{Not a bad idea, but I need to talk to the mayor.}
{203}{}{这个主意不错，但我需要和市长谈谈。}
### {204}{}{As usual. Okay, go ahead. He's probably in his office. Don't forget to knock before entering.}
{204}{}{和往常一样。好吧，继续。他可能在办公室里。进门前别忘了敲门。}
### {205}{}{OK.}
{205}{}{好啊}
### {206}{}{I'm not up to games right now. Need to look around.}
{206}{}{我现在不能参加比赛。需要四处看看。}
### {207}{}{Ah, what a disappointment. Okay, go ahead. I hope you change your mind. Just don't hang around our house doing nothing. My daddy doesn't like it.}
{207}{}{啊，真令人失望。好吧，继续。我希望你改变主意。只是不要在我们家无所事事。我爸爸不喜欢。}
### {208}{}{OK.}
{208}{}{好啊}
### {209}{}{He should be more friendly.}
{209}{}{他应该更友善一些。}

### {210}{}{Oh, hi.}
{210}{}{哦，嗨。}
### {211}{}{Bye.}
{211}{}{再见}
### {212}{}{I want to ask you about the city.}
{212}{}{我想问你关于这个城市的情况。}
### {213}{}{Uh, listen, I don't want to talk to you, okay? If you insist, I'll call the bodyguards.}
{213}{}{听着，我不想和你说话，好吗？如果你坚持，我会叫保镖。}
### {214}{}{Well, sit alone, bitch. Now it's clear why no one registered you.}
{214}{}{好吧，一个人坐着，婊子。现在很清楚为什么没有人注册你了。}
### {215}{}{Why is the whole city so mad at me? Okay, forget it.}
{215}{}{为什么整个城市都这么生我的气？好吧，算了。}

#Game
### {220}{}{Oh, hello. Do you want to play cards?}
{220}{}{哦，你好。你想打牌吗？}
### {221}{}{Let's play. I'm putting 10 caps on.}
{221}{}{让我们玩吧。我要戴10顶帽子。}
### {222}{}{Oh, hi. Do you want to play cards? I haven't played with anyone for so long that I'm dying of boredom.}
{222}{}{哦，嗨。你想打牌吗？我好久没和任何人玩了，无聊得要死了。}
### {223}{}{Sorry, but I don't gamble.}
{223}{}{对不起，我不赌博。}
### {224}{}{And in my opinion, you're being pribed.}
{224}{}{在我看来，你是在受宠若惊。}
### {225}{}{Uh, I don't think so. Bye.}
{225}{}{我不这么认为。再见。}
### {226}{}{A game of interest?}
{226}{}{兴趣游戏？}
### {227}{}{What else! Without betting, the game becomes boring. And when you know that you can lose your valuables - that's when a real drive appears.}
{227}{}{还有什么！如果不下注，游戏就会变得无聊。当你知道你可能会丢失贵重物品时，就会出现真正的驱动器。}
### {228}{}{Um, do you really have caps on the game?}
{228}{}{嗯，你真的有上限吗？}
### {229}{}{Of course! My daddy is the head of the city. Even if I lose, he will give me more pocket caps, he has the whole safe full of them.}
{229}{}{当然我爸爸是城市的负责人。即使我输了，他也会给我更多的口袋帽，他把整个保险箱都装满了。}
### {230}{}{I'm sorry, but I can't waste time playing games right now. Maybe another time.}
{230}{}{对不起，我现在不能浪费时间玩游戏。也许改天吧。}
### {231}{}{What a pity. Okay, go solve your *important things*.}
{231}{}{真遗憾。好吧，去解决你的“重要事情”。}
### {232}{}{You know, it's time for me to relax. I'll put 10 caps on.}
{232}{}{你知道，是时候让我放松了。我要戴10顶帽子。}
### {233}{}{Uh, bye.}
{233}{}{再见。}
### {234}{}{OK, let's play. I put 10 caps.}
{234}{}{好的，让我们玩吧。我戴了10顶帽子。}
### {235}{}{Great. This is already intriguing...}
{235}{}{太棒了这已经很有趣了。。。}
### {236}{}{And he will do the right thing. Stop wasting his capital.}
{236}{}{他会做正确的事。别再浪费他的资本了。}
### {237}{}{See you later. Don't miss.}
{237}{}{回头见。不要错过。}
### {238}{}{Oops. And where are my bottlecaps...}
{238}{}{哎呀。我的水瓶在哪里。。。}
### {239}{}{[Start the game]}
{239}{}{[开始游戏]}
### {240}{}{Hurray! The card went!}
{240}{}{万岁！卡片掉了！}
### {241}{}{What? No, I want to win back.}
{241}{}{什么不，我想赢回来。}
### {242}{}{I'll leave you.}
{242}{}{我会离开你的。}
### {243}{}{What about? Why so early? We've only just started. Well, that's fine. It's boring with you anyway.}
{243}{}{那么...怎么样为什么这么早？我们才刚刚开始。好吧，没关系。不管怎样，你觉得很无聊。}
### {244}{}{Bye.}
{244}{}{再见}
### {245}{}{What? Did I lose? Oh no, Daddy's gonna kill me... However, this is only 10 caps. But I was happy to kill time.}
{245}{}{什么我输了吗？哦，不，爸爸会杀了我的…不过，这只是10场比赛。但我很乐意消磨时间。}
### {246}{}{Do you want to play again?}
{246}{}{你想再玩一次吗？}
### {247}{}{I will leave you.}
{247}{}{我会离开你的。}
### {248}{}{No, I'm afraid Dad won't give me any more gambling caps.}
{248}{}{不，我担心爸爸不会再给我赌博上限了。}
### {249}{}{Pf. That's so boring!}
{249}{}{太无聊了！}

#Questions
### {300}{}{Who are you?}
{300}{}{你是谁？}
### {301}{}{Christina. Have you lost your memory?}
{301}{}{克里斯蒂娜。你失忆了吗？}
### {302}{}{Are you the mayor's daughter?}
{302}{}{你是市长的女儿吗？}
### {303}{}{Well yes. Don't we look alike? Look - we have the same nose and eyes.}
{303}{}{是的。我们长得像吗？看，我们有同样的鼻子和眼睛。}
### {304}{}{Exactly. And I have a feeling that I need to meet your father urgently. Right now.}
{304}{}{确切地我有一种感觉，我急需见到你父亲。马上}
### {305}{}{It's great. Surely you know a lot about this city?}
{305}{}{太棒了。你肯定对这座城市了解很多吧？}
### {306}{}{What can you tell us about the city?}
{306}{}{关于这个城市，你能告诉我们什么？}
### {307}{}{Just that it's deadly boring here. Although there are seasons when caravans flock to the city. Then a lot of interesting things happen.}
{307}{}{只是这里太无聊了。尽管有时大篷车会蜂拥而至。然后发生了很多有趣的事情。}
### {308}{}{How interesting. But who are you?}
{308}{}{真有趣。但你是谁？}
### {309}{}{There's no help from you. I'm going to look for other experts.}
{309}{}{没有你的帮助。我要找其他专家。}
### {310}{}{Why do you have such a big cemetery in the east?}
{310}{}{你为什么在东部有这么大的墓地？}
### {311}{}{And why not? People are dying, they need to be buried somewhere. Is it not so in other places?}
{311}{}{为什么不呢？人们正在死去，他们需要被埋葬在某个地方。其他地方不是这样吗？}
### {312}{}{I have never come across a larger cemetery.}
{312}{}{我从未见过比这更大的墓地。}
### {313}{}{I don't know. I've been here all my life and have only been to Phoenix once.}
{313}{}{我不知道。我一辈子都在这里，只去过凤凰城一次。}
### {314}{}{I have to go.}
{314}{}{我得走了。}

### {320}{}{Hi. How are you?}
{320}{}{你好你好吗}
### {321}{}{I wanted to check on you. You're doing great. Bye.}
{321}{}{我想看看你。你做得很好。再见}
### {322}{}{Do you want to play cards?}
{322}{}{你想打牌吗？}
### {323}{}{No, I don't play cards anymore. And no games at all.}
{323}{}{不，我不再打牌了。而且根本没有比赛。}
### {324}{}{I understand. Be.}
{324}{}{我理解。是}
### {325}{}{So what did those robbers want from you?}
{325}{}{那些强盗想从你那里得到什么？}
### {326}{}{Revenge on my father for past misdeeds. I didn't know what horrors he had done in this city before.}
{326}{}{为我父亲过去的不端行为报仇。我不知道他以前在这个城市做过什么恐怖的事。}
### {327}{}{I see. Don't lose heart.}
{327}{}{我明白了。不要灰心。}

### {330}{}{Oh, it's you... They killed my dad, do you know?}
{330}{}{哦，是你。。。他们杀了我爸爸，你知道吗？}
### {331}{}{Yes, I saw it with my own eyes. How are you?}
{331}{}{是的，我亲眼看到了。你好吗}
### {1331}{}{Yes, I saw it with my own eyes. How are you?}
{1331}{}{是的，我亲眼看到了。你好吗}
### {332}{}{I am well. Honestly. While I was being held hostage, the bandits were discussing my father. They said that he took power from the last mayor, that he ruthlessly exterminated half of the residents who opposed his power. I was too young to remember those days. Is it really true?}
{332}{}{我很好。真的当我被扣为人质时，匪徒们正在讨论我的父亲。他们说，他从上届市长手中夺取了权力，他无情地消灭了一半反对他的居民。我太年轻了，不记得那些日子了。这真的是真的吗？}
### {333}{}{Stop being a naive fool, open your eyes - any power is violence. Your daddy is just an example.}
{333}{}{别再做一个天真的傻瓜了，睁开你的眼睛——任何力量都是暴力。你爸爸只是一个例子。}
### {334}{}{I understand... Perhaps he was a tyrant and committed terrible atrocities. But for me, he was a loving dad. He always tolerated my whims and gave me the best. How could it have turned out like this?}
{334}{}{我明白。。。也许他是个暴君，犯下了可怕的暴行。但对我来说，他是个慈爱的父亲。他总是容忍我的奇思妙想，给我最好的。怎么会变成这样？}
### {335}{}{Welcome to the world of reality, baby. A world built on blood.}
{335}{}{欢迎来到现实世界，宝贝。一个建立在鲜血之上的世界。}
### {336}{}{Yes. Now I understand. And I will do everything so that this does not happen again.}
{336}{}{对现在我明白了。我会尽一切努力避免这种情况再次发生。}
### {337}{}{As you wish. And my business in this city is over. It's time to hit the road.}
{337}{}{如你所愿。我在这个城市的生意也结束了。是时候上路了。}
### {338}{}{It looks like it. I'm sorry.}
{338}{}{看起来像。对不起。}
### {339}{}{At least he loved you. So, deep down, he was not a tyrant. It's just the way things happened.}
{339}{}{至少他爱你。所以，在内心深处，他不是暴君。事情就是这样发生的。}
### {340}{}{Wait. You probably need bottlecaps for the road. Here, take this. These are the remnants of my pocket bottlecaps. You need them more now.}
{340}{}{等待你可能需要在路上装瓶子。给，拿着这个。这些是我口袋里剩下的瓶子。你现在更需要它们。}
### {341}{}{Thank you. And goodbye.}
{341}{}{非常感谢。再见。}
### {342}{}{Wait. You probably need bottlecaps for the road. Here, take this. These are my pocket bottlecaps. And also all the ones that you safely lost to me at cards. You need them more now.}
{342}{}{等待你可能需要在路上装瓶子。给，拿着这个。这些是我的袋装水瓶。还有你在打牌时安全地输给我的所有东西。你现在更需要它们。}
### {1342}{}{Wait. You probably need bottlecaps for the road. Here, take this. These are my pocket bottlecaps. And also all the ones that you safely lost to me at cards. You need them more now.}
{1342}{}{等待你可能需要在路上装瓶子。给，拿着这个。这些是我的袋装水瓶。还有你在打牌时安全地输给我的所有东西。你现在更需要它们。}
### {343}{}{Good luck to you. And it's time for me to go on a long journey.}
{343}{}{祝你好运。现在是我进行长途旅行的时候了。}
### {344}{}{Goodbye, stranger.}
{344}{}{再见，陌生人。}
### {345}{}{Goodbye.}
{345}{}{再见}
### {346}{}{Oh, it's you... I am eternally grateful to you for saving me.}
{346}{}{哦，是你。。。我永远感激你救了我。}
### {347}{}{Then why do you have such a sad face?}
{347}{}{那你为什么有一张如此悲伤的脸？}
### {348}{}{Hey, where's that gambling look of a naive girl?}
{348}{}{嘿，天真女孩赌博的样子在哪里？}
### {349}{}{At least he loves you. Which means he's not a tyrant at heart. It's just the way things happened.}
{349}{}{至少他爱你。这意味着他根本不是暴君。事情就是这样发生的。}
