### {100}{}{Here is a ranger.}
{100}{}{这是一个护林员。}
### {101}{}{You see a man in leather armor.}
{101}{}{你看到一个穿着皮甲的男人。}
### {102}{}{We have nothing more to talk about.}
{102}{}{我们没有什么可谈的了。}

### {200}{}{Well, well. Looks like we've got a troublemaker here. }
{200}{}{嗯，嗯。看来我们这里有个麻烦制造者。}
### {201}{}{Oops...}
{201}{}{哎呀。。。}
### {202}{}{What are you doing, you fool?}
{202}{}{你在干什么，你这个傻瓜？}
### {1202}{}{What is such a lady doing in a cemetery?}
{1202}{}{这样一位女士在墓地里干什么？}
### {203}{}{It's none of your business. I won't tell you anything.}
{203}{}{这不关你的事。我什么都不告诉你。}
### {204}{}{Very sorry. It's a pity that people like you interfere with normal people's lives.}
{204}{}{非常抱歉。很遗憾，像你这样的人干扰了正常人的生活。}
### {205}{}{[Next]}
{205}{}{[下一个]}
### {206}{}{(pulls out a weapon) By the authority vested in me by the Arizona Ranger Department and the constitution, I sentence you... to death. The sentence should be carried out immediately.}
{206}{}{（拿出武器）根据亚利桑那州游骑兵部和宪法赋予我的权力，我判你。。。死亡。该判决应立即执行。}
### {207}{}{Thu...}
{207}{}{周四。。。}
### {208}{}{Go to hell.}
{208}{}{见鬼去吧。}
### {209}{}{Stop! The tinsmiths asked me. They are looking for their comrade, he is lying in this grave.}
{209}{}{停止铁匠们问我。他们在找他们的战友，他躺在这个坟墓里。}

### {210}{}{Looking for valuables, sir.}
{210}{}{先生，正在找贵重物品。}
### {211}{}{Valuables in the grave? Did it ever occur to you that it would upset someone VERY much?}
{211}{}{坟墓里的贵重物品？你有没有想过这会让别人非常难过？}
### {212}{}{Spit. And what's next? Will you try to stop me?}
{212}{}{吐接下来是什么？你会阻止我吗？}
### {213}{}{The dead don't need it.}
{213}{}{死者不需要它。}
### {214}{}{Maybe so. But it's not up to you to decide. And it is in my power to punish you for such a misdemeanor.}
{214}{}{也许是这样。但这不是由你来决定的。我有权惩罚你这样的轻罪。}
### {215}{}{Who are you?}
{215}{}{你是谁？}
### {216}{}{Yes, sir. I admit my guilt, sir.}
{216}{}{是的，先生。我承认我的罪行，先生。}
### {217}{}{These tricks won't work with me, buddy. I have an eye for people like you.}
{217}{}{这些把戏对我不管用，伙计。我对像你这样的人很有眼光。}
### {1217}{}{These tricks won't work with me, lady. I have an eye for people like you.}
{1217}{}{这些把戏对我不管用，女士。我对像你这样的人很有眼光。}
### {218}{}{Who are you?}
{218}{}{你是谁？}
### {219}{}{Oh no, this person's relatives won't mind. And do you know why?}
{219}{}{哦，不，这个人的亲戚不会介意的。你知道为什么吗？}

### {220}{}{I'm a ranger. But who are you? Why do you come to this city and act like you can do anything?}
{220}{}{我是一名护林员。但你是谁？你为什么来到这个城市，表现得好像什么都能做？}
### {221}{}{The tinsmiths are looking for their comrade. He was killed. And it looks like you know something about it.}
{221}{}{铁匠们正在寻找他们的战友。他被杀了。看起来你对此有所了解。}
### {222}{}{Who are you anyway?}
{222}{}{你到底是谁？}
### {223}{}{None of your business.}
{223}{}{不关你的事。}

### {230}{}{Oh no, no, you misunderstood me, I'll explain everything now.}
{230}{}{哦，不，不，你误会我了，我现在就解释一切。}
### {231}{}{Work hard, I'm listening carefully.}
{231}{}{努力工作，我在认真听讲。}
### {232}{}{You see, I'm looking... [Get a weapon and attack]}
{232}{}{你看，我在看。。。[拿起武器攻击]}
### {233}{}{It's none of your business. I won't tell you anything.}
{233}{}{这不关你的事。我什么都不告诉你。}
### {234}{}{The tinsmiths asked me. They are looking for their brother. He's here.}
{234}{}{铁匠们问我。他们在找他们的兄弟。他在这里。}

### {240}{}{I know. I killed him.}
{240}{}{我知道。我杀了他。}
### {241}{}{But why? What's wrong with the tinker?}
{241}{}{但为什么呢？修补匠怎么了？}
### {242}{}{Scum like tinsmiths should be lying in the ground. They consider themselves gods, as if everything is allowed to them. They oppress the residents, take away the latest technologies from them and force them to work. Their power casts doubt on any hopes for justice in the lands of Southern Arizona. And their very existence, combined (contemptuously) with technology, is inhumane. As for me, this is quite enough.}
{242}{}{像铁匠一样的渣滓应该躺在地上。他们认为自己是神，好像一切都允许他们。他们压迫居民，剥夺他们的最新技术，强迫他们工作。他们的力量使人们对亚利桑那州南部地区伸张正义的希望产生了怀疑。他们的存在，与技术相结合（轻蔑地），是不人道的。对我来说，这已经足够了。}
### {243}{}{[Next]}
{243}{}{[下一个]}
### {244}{}{And what attracted you so much to tinsmiths? Bribed by the ringing of rusty caps?}
{244}{}{是什么吸引你这么喜欢锡匠？被锈迹斑斑的帽子铃声淹没了？}
### {245}{}{Maybe so. I'm a simple mercenary, I don't care about your Arizona and justice.}
{245}{}{也许是这样。我只是一个简单的雇佣兵，我不在乎你的亚利桑那州和正义。}
### {1245}{}{Maybe so. I'm a simple mercenary, I don't care about your Arizona and justice.}
{1245}{}{也许是这样。我只是一个简单的雇佣兵，我不在乎你的亚利桑那州和正义。}
### {246}{}{Well. You work for the enemies of the wasteland, so you are an enemy yourself.}
{246}{}{好你为荒原上的敌人工作，所以你自己就是敌人。}
### {1246}{}{Well, if you work for the enemies of the wasteland, then you are an enemy yourself.}
{1246}{}{如果你为荒原上的敌人工作，那么你自己就是敌人。}
### {247}{}{[Next]}
{247}{}{[下一个]}
### {248}{}{No need. Please.}
{248}{}{不需要。请}
### {249}{}{Oh shit...}
{249}{}{哦，该死。。。}
### {250}{}{So, you confessed. Tell me the reason why you should be left alive.}
{250}{}{所以，你承认了。告诉我为什么你还活着。}
### {251}{}{(pulls out a weapon) I have six reasons, you fool. Listen carefully...}
{251}{}{（拿出武器）我有六个理由，你这个傻瓜。仔细听。。。}
### {1251}{}{ (pulls out a weapon) I have six reasons, you fool. Listen carefully...}
{1251}{}{（拿出武器）我有六个理由，你这个傻瓜。仔细听。。。}
### {252}{}{Oh shit...}
{252}{}{哦，该死。。。}
### {253}{}{Oh, don't...}
{253}{}{哦，不要。。。}
### {254}{}{I'm a ranger too. And I'm on a mission. I have been ordered to infiltrate the ranks of the tinsmiths to find their weaknesses.}
{254}{}{我也是一名护林员。我正在执行一项任务。我奉命潜入铁匠队伍，寻找他们的弱点。}
### {255}{}{Hmm. An unexpected meeting, comrade. It's good to see you. Well, in that case, I have no more questions. We will assume that this meeting did not take place.}
{255}{}{一个意想不到的会议，同志。很高兴见到你。既然如此，我就没有问题了。我们假定这次会议没有举行。}
### {256}{}{Sure. No one saw anything.}
{256}{}{当然没有人看到任何东西。}
### {257}{}{Let me carry the remains. Tinsmiths deserve respect.}
{257}{}{让我来抬遗体。铁匠值得尊敬。}
### {258}{}{I can't let you keep working for these bastards.}
{258}{}{我不能让你继续为这些混蛋工作。}
### {259}{}{[Next]}
{259}{}{[下一个]}
### {260}{}{You can hate them. But as a ranger, you have to respect a strong enemy. Let me take the remains to them.}
{260}{}{你可以恨他们。但作为一名护林员，你必须尊重一个强大的敌人。让我把遗体带给他们。}
### {261}{}{Hmm. These words make you think. Okay, do your dirty work, mercenary. And tell the tinsmiths that the wastelands will not always kneel before them.}
{261}{}{这些话让你思考。好吧，干你的脏活，雇佣兵。告诉铁匠们，荒原不会永远跪在他们面前。}
### {1261}{}{Hmm. These words make you think. Okay, do your dirty work, mercenary. And tell the tinsmiths that the wastelands won't always be on their knees before them.}
{1261}{}{这些话让你思考。好吧，干你的脏活，雇佣兵。告诉铁匠们，荒原不会总是跪在他们面前。}
### {262}{}{Uh, yes, sir. As you say, sir.}
{262}{}{嗯，是的，先生。正如你所说，先生。}
### {263}{}{Just leave me alone.}
{263}{}{别管我。}
### {264}{}{Sir, I have no complaints against you. I'm just fulfilling a peace contract.}
{264}{}{先生，我对你没有任何抱怨。我只是在履行一份和平合同。}
### {265}{}{(mockery) Okay, do your dirty work, mercenary. And tell the tinsmiths that the wastelands will not always kneel before them.}
{265}{}{（嘲笑）好吧，干你的脏活，雇佣兵。告诉铁匠们，荒原不会永远跪在他们面前。}
### {1265}{}{(mockery) Okay, do your dirty work, mercenary. And tell the tinsmiths that the wastelands will not always kneel before them.}
{1265}{}{（嘲笑）好吧，干你的脏活，雇佣兵。告诉铁匠们，荒原不会永远跪在他们面前。}
### {266}{}{I'm just fulfilling a contract. What problems?}
{266}{}{我只是在履行合同。什么问题？}
