### {100}{}{You see a slave.}
{100}{}{你看到一个奴隶。}
### {101}{}{Here is an exhausted slave. His hands are covered with bloody calluses, and his shoulders are blue from the ropes.}
{101}{}{这是一个精疲力竭的奴隶。他的手上满是血肉模糊的老茧，肩膀被绳子弄得青一块。}
### {102}{}{This person is not able to talk.}
{102}{}{这个人不能说话。}

### {110}{}{Oh...}
{110}{}{哦}
### {111}{}{Uh...}
{111}{}{嗯}
### {112}{}{Uh...}
{112}{}{嗯}
### {113}{}{Well...}
{113}{}{好}
### {114}{}{What?}
{114}{}{什么}
### {115}{}{Run away from here.}
{115}{}{逃离这里。}
### {116}{}{Don't talk to me.}
{116}{}{别跟我说话。}
### {117}{}{I'd rather be shot.}
{117}{}{我宁愿被枪毙。}
### {118}{}{}
{118}{}{error : string is empty}
### {119}{}{}
{119}{}{error : string is empty}
