### {100}{}{There is a guard in front of you.}
{100}{}{你面前有一个警卫。}
### {101}{}{You see the guard. He seems tired after a long flight.}
{101}{}{你看到警卫了。长途飞行后他似乎很累。}

### {110}{}{What would you like to do before the shipment?}
{110}{}{发货前你想做什么？}
### {111}{}{Do you want to play "Caravan"?}
{111}{}{你想玩“大篷车”吗？}
### {112}{}{Wake me up when the packing starts.}
{112}{}{收拾行李时叫醒我。}
### {113}{}{In the south, this ore is very much expected.}
{113}{}{在南部，人们对这种矿石寄予厚望。}
### {114}{}{Each shopping trip can be the last.}
{114}{}{每次购物都可能是最后一次。}
### {115}{}{I don't know what I would do if there wasn't a colony here.}
{115}{}{如果这里没有殖民地，我不知道该怎么办。}
### {116}{}{Talk to the chief, I'm just a security guard.}
{116}{}{和局长谈谈，我只是个保安。}
### {117}{}{We usually don't take fellow travelers.}
{117}{}{我们通常不带同行者。}
### {118}{}{Dust storms kept us in San Brahmin for a whole week.}
{118}{}{沙尘暴使我们在圣婆罗门呆了整整一个星期。}
### {119}{}{This flight is going to be tough.}
{119}{}{这次飞行会很艰难。}
