### {100}{}{Here is a hunter.}
{100}{}{这是一个猎人。}
### {101}{}{This man looks haggard.}
{101}{}{这个人看起来很憔悴。}
### {102}{}{PC! Open the gate. Just don't show up in front of savages.}
{102}{}{个人计算机打开大门。只是不要出现在野蛮人面前。}
### {103}{}{The hunter successfully left his camp.}
{103}{}{猎人成功地离开了他的营地。}

### {200}{}{Hey! You're just in time. Just be quiet! These savages have excellent hearing. Did they send you from Flagstaff?}
{200}{}{嘿你来得正是时候。安静点！这些野蛮人的听力很好。他们是从弗拉格斯塔夫派你来的吗？}
### {201}{}{Yes. The bartender wants to know what's going on here.}
{201}{}{对酒保想知道这里发生了什么事。}
### {202}{}{Shit's going on here, that's what I'll tell you. The savages killed the hunters, and I was locked up in reserve.}
{202}{}{这里发生了什么事，我会告诉你的。野蛮人杀死了猎人，我被关在保护区。}
### {203}{}{Actually, no. I got lost and was hoping to find a place to sleep.}
{203}{}{事实上，没有。我迷路了，希望找个地方睡觉。}
### {1203}{}{Actually, no. I got lost and was hoping to find a place to sleep.}
{1203}{}{事实上，没有。我迷路了，希望找个地方睡觉。}
### {204}{}{Well, welcome to Winon. I'm sorry I'm not offering herbal tea. The savages killed the hunters, and I was locked up in reserve.}
{204}{}{好吧，欢迎来到威农。对不起，我不提供凉茶。野蛮人杀死了猎人，我被关在保护区。}
### {205}{}{It's terrible.}
{205}{}{太可怕了。}
### {206}{}{}
{206}{}{error : string is empty}
### {207}{}{Help me get out of here? Just be quiet! We cannot cope with such a crowd without weapons.}
{207}{}{帮我离开这里？安静点！没有武器，我们无法应付这样的人群。}
### {208}{}{Now is not the right time for this. I'll tell you when you can leave.}
{208}{}{现在不是这样做的合适时机。我会告诉你什么时候可以离开。}
### {209}{}{I'm sorry, but you'll have to sit in this cage for a while longer.}
{209}{}{对不起，你得在这个笼子里多坐一会儿。}
### {210}{}{OK. I'll take you out.}
{210}{}{好的，我带你出去。}
### {211}{}{Help me get out of the forest, then I'll find my own way.}
{211}{}{帮我走出森林，然后我会找到自己的路。}
### {212}{}{Okay.}
{212}{}{可以}

### {220}{}{Why did the savages attack you?}
{220}{}{野蛮人为什么攻击你？}
### {221}{}{Isn't it clear? They wanted to profit from our prey, and at the same time - to show who is the boss here. This tribe has a grudge against our brother for a long time.}
{221}{}{不是很清楚吗？他们想从我们的猎物中获利，同时也想展示谁是这里的老板。这个部落对我们的兄弟怀恨在心很久了。}
### {222}{}{Enough talking.}
{222}{}{说够了。}
### {223}{}{And what happened between you?}
{223}{}{你们之间发生了什么？}
### {224}{}{When Faber set up a colony in Flagstaff, he first drove the local tribe out of their homes. He killed someone, drove someone to distant lands, and this group remained to rob the inhabitants of the colony. In a word - savages.}
{224}{}{当费伯在弗拉格斯塔夫建立殖民地时，他首先把当地部落赶出了他们的家园。他杀了一个人，把一个人赶到遥远的地方，而这群人留下来抢劫殖民地的居民。总之——野蛮人。}
### {225}{}{And how did the savages with their sticks manage to defeat you?}
{225}{}{野蛮人是怎么用他们的棍子打败你的？}
### {226}{}{Caught by surprise at night when everyone was asleep, that's the whole trick. They are more adept at such things than us city dwellers.}
{226}{}{在晚上大家都睡着的时候被吓了一跳，这就是诀窍。他们比我们城市居民更擅长做这些事情。}
### {227}{}{Tell me about the surroundings.}
{227}{}{告诉我周围的情况。}
### {228}{}{Wild lands. There are almost no people, but there are a lot of different animals. Forests and mountains stretch for miles around. By the way, we set traps for animals around the camp, be careful.}
{228}{}{荒野。这里几乎没有人，但有很多不同的动物。森林和山脉绵延数英里。顺便说一句，我们在营地周围为动物设置了陷阱，小心点。}
### {229}{}{Can you show me where your traps are?}
{229}{}{你能告诉我你的陷阱在哪里吗？}
### {230}{}{Traps are set in the forest thicket in front of the entrance to the camp. Look carefully at your feet.}
{230}{}{营地入口前的森林灌木丛中设置了陷阱。仔细看你的脚。}
### {231}{}{Thank you.}
{231}{}{非常感谢。}
### {232}{}{What do you know about these savages?}
{232}{}{你对这些野蛮人了解多少？}
### {233}{}{This is a clan of a tribe that once lived in these lands. A small number of people. Faber destroyed the main part of them, and drove away the rest. But for some reason these returned. Probably couldn't find places as rich in game.}
{233}{}{这是一个曾经生活在这些土地上的部落的氏族。少数人。费伯摧毁了他们的大部分，并赶走了其余的人。但由于某种原因，这些人又回来了。可能找不到像这里这样盛产野味的地方了。}
### {234}{}{Any ideas how to get rid of them?}
{234}{}{有什么办法摆脱它们的想法吗？}
### {235}{}{Now it would be a good old shotgun or a detachment of mercenaries from the garrison. In the meantime, I can't even imagine what you can scare them with. They seem to be very superstitious. Otherwise, they would not have placed these totems around the perimeter of the camp.}
{235}{}{现在，它将是一支很好的老式猎枪，或者是一支来自驻军的雇佣兵分队。与此同时，我甚至无法想象你能用什么来吓唬他们。他们似乎很迷信。否则，他们不会在营地周围放置这些图腾。}
### {236}{}{Name the nearest city?}
{236}{}{说出最近的城市？}
### {237}{}{Flagstaff. It's a mining colony southwest of here.}
{237}{}{Flagstaff。它是这里西南部的一个矿业殖民地。}
### {238}{}{Thank you.}
{238}{}{非常感谢。}

### {240}{}{You're safe now.}
{240}{}{你现在安全了。}
### {241}{}{When they find out I've escaped, they'll raise the alarm. But I'll be far away by then. Thanks for the help. The whole Flagstaff will know about your help when I get there.}
{241}{}{当他们发现我逃跑了，他们就会发出警报。但到那时我会离开很远。谢谢你的帮助。当我到达那里时，整个弗拉格斯塔夫人都会知道你的帮助。}
### {242}{}{Good luck.}
{242}{}{祝你好运}
