### {100}{}{Here is a scavenger.}
{100}{}{这是一个拾荒者。}
### {101}{}{You see a man burned by labor and time.}
{101}{}{你看到的是一个被劳动和时间折磨的人。}
### {102}{}{*Clutching his chest convulsively*}
{102}{}{*痉挛地抓着他的胸口*}
### {103}{}{Arch...}
{103}{}{拱}
### {104}{}{You have made a successful transaction. It's time to make Eugene happy with this news.}
{104}{}{您已成功完成交易。是时候让尤金对这个消息感到高兴了。}
### {105}{}{You'd better not disturb me.}
{105}{}{你最好不要打扰我。}

#The first dialog
### {200}{}{What do you need, stranger?}
{200}{}{你需要什么，陌生人？}
### {1200}{}{What do you need, stranger?}
{1200}{}{你需要什么，陌生人？}
### {201}{}{Why such rudeness?}
{201}{}{为什么这么粗鲁？}
### {202}{}{(spits as if casually) We're not used to sissies here, I'm sorry.}
{202}{}{（漫不经心地吐口水）对不起，我们不习惯这里的娘娘腔。}
### {203}{}{Eh, nothing...}
{203}{}{呃，没什么。。。}
### {204}{}{And I'm not used to seeing ragamuffins. Later.}
{204}{}{我不习惯看到乌合之众。后来}

#Repeat dialog
### {210}{}{So what do you need?}
{210}{}{那么你需要什么呢？}
### {211}{}{Nothing.}
{211}{}{没有什么}
### {212}{}{Can you tell us about this settlement?}
{212}{}{你能告诉我们这个和解方案吗？}
### {213}{}{I don't have time for an ass like you.}
{213}{}{我没有时间和你这样的混蛋在一起。}
### {214}{}{Why is there a crossed-out star painted on your door?}
{214}{}{为什么你的门上画着一颗划掉的星星？}
### {215}{}{Rangers. These filthy lovers of other people's goods want to take away from me the most valuable thing - my son. I'm trying to shield him from this stupidity.}
{215}{}{游骑兵队。这些肮脏的情人喜欢别人的东西，他们想夺走我最珍贵的东西——我的儿子。我试图保护他不受这种愚蠢的影响。}
### {216}{}{Why do they need your son?}
{216}{}{他们为什么需要你的儿子？}
### {217}{}{They recruit young animals, and then prepare warriors and scouts from them. I didn't work at this mine in order for my son to become a murderer in the name of someone else's idea. Let him plow, like me, on the ruins and benefit his home, not someone else's.}
{217}{}{他们招募幼兽，然后从中培养战士和侦察兵。我在这个矿场工作并不是为了让我的儿子以别人的名义成为杀人犯。让他像我一样在废墟上犁地，造福他的家，而不是别人的家。}
### {218}{}{What's the situation with the Rangers?}
{218}{}{游骑兵队的情况如何？}
### {219}{}{A crowd of armed guys who are trying to get their hands on the whole neighborhood. They promise security and order in exchange for resources and recruits.}
{219}{}{一群武装人员正试图控制整个街区。他们承诺以安全和秩序换取资源和新兵。}
### {220}{}{And what's the catch?}
{220}{}{有什么收获？}
### {221}{}{Sounds quite acceptable.}
{221}{}{听起来可以接受。}
### {222}{}{Yes, only life has taught that you can not believe such. They just row for themselves, and share only the surplus. The same raiders, only they speak in beautiful words.}
{222}{}{是的，只有生活教会了你不能相信。他们只是自己划船，只分享剩余的部分。同样的袭击者，只是他们说话很动听。}
### {223}{}{I see.}
{223}{}{我明白了。}
### {224}{}{Okay.}
{224}{}{可以}

#Quest
### {250}{}{I'm here to take your son to the Rangers.}
{250}{}{我是来带你儿子去游骑兵队的。}
### {251}{}{Get out, Ranger henchman! You won't get anything here except a piece of scrap between your eyes.}
{251}{}{滚出去，游骑兵党羽！你在这里什么都得不到，只有一块碎片夹在你的眼睛里。}
### {252}{}{So that's what you're teaching him - using scrap to harm, not benefit?}
{252}{}{所以这就是你教他的——用废料来伤害，而不是好处？}
### {253}{}{I said get out!}
{253}{}{我说滚出去！}
### {254}{}{...He can do more. He can be engaged in complex technology, and not collecting dirty garbage.}
{254}{}{…他可以做得更多。他可以从事复杂的技术，而不是收集脏垃圾。}
### {255}{}{I know better what he needs!}
{255}{}{我更清楚他需要什么！}
### {256}{}{This city will die sooner or later, and Eugene will have nothing left but junk.}
{256}{}{这座城市迟早会消亡，尤金将一无所有，只剩下垃圾。}
### {257}{}{Yes, it's true... So what? How do I know these Rangers really mean well to Eugene? I don't believe them!}
{257}{}{是的，这是真的。。。那又怎样？我怎么知道这些流浪者对尤金真的很好？我不相信他们！}
### {258}{}{Trust Eugene. Look how he's wasting away in this dump. Is this what you want? He will gain at least some future from the Rangers.}
{258}{}{相信尤金。看看他在这垃圾堆里是怎么浪费的。这是你想要的吗？他至少会从流浪者队获得一些未来。}
### {259}{}{You speak with the words of a Garbage Devil... Take Eugene and take him to a better place. But keep in mind and remember - if something happens to him, you will answer for it with your head!}
{259}{}{你用垃圾魔鬼的话说话。。。带尤金去一个更好的地方。但请记住，如果他出了什么事，你会用你的脑袋来回答的！}
### {260}{}{You don't have to worry about anything. Eugene is in good hands}
{260}{}{你什么都不用担心。尤金得到了很好的照顾}
### {261}{}{I don't think I can convince you.}
{261}{}{我想我不能说服你。}
### {262}{}{One more word and you'll pay for it!}
{262}{}{再多说一句话，你就会付出代价的！}
### {263}{}{Listen to my words - it will be better for him.}
{263}{}{听我说，这对他会更好。}

### {270}{}{I can buy Eugene out. How much do you want for the contract?}
{270}{}{我可以买下尤金。这份合同你要多少钱？}
### {271}{}{You will never collect so much valuable junk in your whole life.}
{271}{}{你一辈子都不会收集这么多有价值的垃圾。}
### {272}{}{Take a look at my offer first...}
{272}{}{先看看我的报价。。。}
### {273}{}{Then forget it.}
{273}{}{那就忘了。}
### {274}{}{Ha-ha! Get out of here.}
{274}{}{哈哈！离开这里。}
### {275}{}{[Leave]}
{275}{}{[离开]}
### {276}{}{Finally, this brat has brought me at least some benefit. And what is this? A contract? I can't write! Okay, I'll put a cross, if that's what you want. Now take my son. But if something happens to him on the way, I will personally rip your head off! Clear?}
{276}{}{最后，这个小淘气至少给我带来了一些好处。这是什么？合同？我不会写字！好吧，如果你想要的话，我会画一个十字架。现在带上我的儿子。但如果他在路上出了什么事，我会亲自把你的头扯下来！清楚的}
### {277}{}{Clear.}
{277}{}{清楚的}
### {278}{}{(scratching his unshaven cheek in thought)}
{278}{}{（一边想着一边搔着胡子刮不齐的脸颊）}
### {279}{}{[Next]}
{279}{}{[下一个]}
