### {100}{}{Here is the gatekeeper.}
{100}{}{这是看门人。}
### {101}{}{You see a very tanned and not shaved guard for a long time. His steady gaze drills right through you.}
{101}{}{你看到一个晒得黝黑，很长时间没有刮胡子的警卫。他稳定的目光穿透了你。}
### {102}{}{I'll be damned! Is this bike really on the move?!}
{102}{}{我会被诅咒的！这辆自行车真的在行驶吗？！}
### {103}{}{That's another conversation! Welcome to Garage City.}
{103}{}{这又是一次谈话！欢迎来到车库城。}
### {104}{}{Welcome to Garage City. But to get into the city, you will have to answer a couple of questions.}
{104}{}{欢迎来到车库城。但要进入这个城市，你必须回答几个问题。}

#The first dialog
### {200}{}{Wait, stranger. What are you doing in town?}
{200}{}{等等，陌生人。你在城里干什么？}
### {201}{}{I'm looking for my fellow tribesmen. They were enslaved and taken away in this direction.}
{201}{}{我在找我的部落同胞。他们被奴役并被带向这个方向。}
### {202}{}{I need a bed for the night.}
{202}{}{我需要一张床过夜。}
### {203}{}{Probably none.}
{203}{}{可能没有。}

### {204}{}{I don't know anything about it.}
{204}{}{我对此一无所知。}
### {205}{}{So can I pass?}
{205}{}{那么我可以通过吗？}
### {206}{}{And I know for sure that they were here.}
{206}{}{我确信他们在这里。}
### {207}{}{Maybe so. You need to talk to the guys at the bar or the cartel boss.}
{207}{}{也许是这样。你需要和酒吧里的人或卡特尔老板谈谈。}
### {208}{}{OK. So can I pass?}
{208}{}{好的，我可以通过吗？}
### {209}{}{I said I don't know.}
{209}{}{我说我不知道。}
### {210}{}{I want to ask the other settlers. Can I pass?}
{210}{}{我想问问其他定居者。我能通过吗？}

### {211}{}{We have a hotel, but I'm not sure there are available seats there.}
{211}{}{我们有一家酒店，但我不确定那里是否有空位。}
### {212}{}{Maybe I'll go there and ask?}
{212}{}{也许我会去那里问？}
### {213}{}{Sounds unconvincing. If you really are here by chance, then you should not bother the residents.}
{213}{}{听起来难以令人信服。如果你真的是偶然来到这里，那么你不应该打扰居民。}
### {214}{}{Still, I want to look around.}
{214}{}{尽管如此，我还是想四处看看。}

### {215}{}{Are you leaving already? And correctly... After Mr. Kogan's death, people in the city went wild.}
{215}{}{你已经走了吗？正确地说。。。Kogan先生死后，城里的人都疯了。}
### {216}{}{Sorry to hear that.}
{216}{}{很抱歉听到这个消息。}
### {217}{}{Serves you right. There was nothing to make friends with slavers.}
{217}{}{为您服务。没有什么可以和奴隶贩子交朋友的。}
### {218}{}{You mean the convoy from Flagstaff? Yes, the deal was not the best, but it brought the city a good income. I doubt that these two cases were connected... Or not?}
{218}{}{你是说弗拉格斯塔夫的车队？是的，这笔交易不是最好的，但它给这座城市带来了不错的收入。我怀疑这两起案件是否有关联。。。还是不？}
### {219}{}{Think about it. And my business here is really already over.}
{219}{}{想想看，我在这里的生意真的已经结束了。}

### {220}{}{Stop! Show me your hands.}
{220}{}{停止让我看看你的手。}
### {221}{}{Hands? What for?}
{221}{}{手？为何}
### {222}{}{(raises his gun threateningly) Just show me your hands!}
{222}{}{（威胁地举起枪）让我看看你的手！}
### {223}{}{I'll show you the right hook first!}
{223}{}{我先给你看右勾拳！}
### {224}{}{Okay, calm down. I don't want to get into a fight over some little thing. But keep in mind that we don't like them.}
{224}{}{好吧，冷静下来。我不想为了一些小事而吵架。但请记住，我们不喜欢他们。}
### {225}{}{And what does the hands have to do with it?}
{225}{}{手和它有什么关系？}
### {226}{}{Okay, here, look.}
{226}{}{好的，给，看。}
### {227}{}{Hmm? Looks like you're fine. Come on in.}
{227}{}{嗯？看起来你很好。进来吧。}
### {228}{}{What the hell does that mean?}
{228}{}{这到底是什么意思？}
### {229}{}{A routine check for shakes. All Jackals have this syndrome, but we don't need them.}
{229}{}{抖动的例行检查。所有的豺狼都有这种综合症，但我们并不需要它们。}
### {230}{}{It looks like the consequences of cannibalism.}
{230}{}{这看起来像是吃人的后果。}
### {231}{}{If you say so... I've never thought about it, but there have been such rumors about Jackals for a long time.}
{231}{}{如果你这么说的话……我从来没有想过，但关于豺狼的传言已经很久了。}
### {232}{}{Next time I'll take it as a personal insult. Now step aside.}
{232}{}{下次我会把它看作是对个人的侮辱。现在靠边站。}
### {233}{}{Can you explain what it was?}
{233}{}{你能解释一下是什么吗？}
### {234}{}{I hope this misunderstanding is settled. Now let me go into the city.}
{234}{}{我希望这个误会能解决。现在让我进城吧。}
### {235}{}{Be calm, I'm not one of them.}
{235}{}{冷静点，我不是他们中的一员。}
### {236}{}{Wait. Don't get me wrong, but before you enter the city, show your hands.}
{236}{}{等待别误会我的意思，但在你进城之前，请举手。}
### {237}{}{Maybe it's their nature?}
{237}{}{也许这是他们的天性？}
### {238}{}{How should I know? I won't even talk to them - I'll put a bullet in their forehead right away, and that's the end of it.}
{238}{}{我该怎么知道？我甚至不会和他们说话——我会马上在他们的额头上开一枪，就这样结束了。}

#Repeat dialog
### {240}{}{Welcome to the landfill. Make yourself at home.}
{240}{}{欢迎来到垃圾填埋场。别拘束。}
### {241}{}{Welcome to Garage City. You'll like it here... if you get used to it a little.}
{241}{}{欢迎来到车库城。你会喜欢这里的。。。如果你稍微习惯一点。}
### {242}{}{Don't you want to leave so much?}
{242}{}{你不想离开那么多吗？}
### {243}{}{This dump is our home. Our sweet cozy home.}
{243}{}{这个垃圾场是我们的家。我们温馨舒适的家。}
### {244}{}{That's a cool thing on your arm. Is it a computer? I've never seen anything like it.}
{244}{}{你手臂上的东西很酷。它是一台电脑吗？我从来没有见过这样的东西。}
### {245}{}{Wait, who's coming? Oh, it's you...}
{245}{}{等等，谁来了？哦，是你。。。}

### {246}{}{Ah, you're still here. Strange, I thought you didn't like it here.}
{246}{}{啊，你还在这里。奇怪，我以为你不喜欢这里。}
### {247}{}{Listen, the people here are uncooperative, you better not shine on the street once again.}
{247}{}{听着，这里的人都不合作，你最好不要再在街上大放异彩了。}
### {248}{}{Are you on business? It would be better this way, otherwise the locals may misunderstand it.}
{248}{}{你出差吗？这样会更好，否则当地人可能会误解。}
### {249}{}{Listen, get someone else, I can have problems because of you anyway.}
{249}{}{听着，找其他人吧，反正我也会因为你而出问题的。}

### {250}{}{Do you know the guy who asked to join the Rangers?}
{250}{}{你认识那个要求加入游骑兵队的人吗？}
### {251}{}{Or maybe so. But why would I help the Rangers?}
{251}{}{也许是这样。但我为什么要帮助流浪者队？}
### {252}{}{It won't affect you.}
{252}{}{它不会影响你。}
### {253}{}{OK. Eugene Simon is the one you're looking for. His shack near the dorm.}
{253}{}{好的，尤金·西蒙就是你要找的人。他在宿舍附近的棚屋。}
### {254}{}{Thank you.}
{254}{}{非常感谢。}
### {255}{}{It's none of your business. Just step back and don't get in the way.}
{255}{}{这不关你的事。退后一步，不要挡道。}
### {256}{}{Oh no, everything that passes through this gate concerns me.}
{256}{}{哦，不，通过这扇门的一切都与我有关。}
### {257}{}{I'm sorry for being rude. It's just unusual to talk at gunpoint. So you let people in for the night?}
{257}{}{对不起，我太粗鲁了。在枪口下说话是不寻常的。所以你让人们进来过夜？}
### {258}{}{I just want to spend the night. I won't be here tomorrow.}
{258}{}{我只想过夜。我明天不在这里。}
### {259}{}{For now.}
{259}{}{现在。}

### {260}{}{You mentioned some Jackals. Who is this?}
{260}{}{你提到了一些豺狼。这是谁？}
### {261}{}{This tribe of savages lives in the desert, but almost nothing is known about them. All we know is that these are cunning sons of bitches, they lure into traps or attack weak travelers in a crowd.}
{261}{}{这个野蛮部落生活在沙漠中，但对他们几乎一无所知。我们所知道的是，这些都是狡猾的狗娘养的，他们引诱进入陷阱或攻击人群中虚弱的旅行者。}
### {262}{}{I see.}
{262}{}{我明白了。}
### {263}{}{Why not finish them off with the whole crowd?}
{263}{}{为什么不把他们和所有的人一起干掉呢？}
### {264}{}{We'd be glad to unsheathe our weapons, but we don't know where these damn jackals are hiding. Do you know their main camp?}
{264}{}{我们很乐意拿出武器，但我们不知道这些该死的豺狼藏在哪里。你知道他们的主要营地吗？}
### {265}{}{Actually, no.}
{265}{}{事实上，没有。}
### {266}{}{I thought so.}
{266}{}{我是这么想的。}
### {267}{}{Enough talk about these jackals.}
{267}{}{关于这些豺狼的话已经说够了。}
### {268}{}{Actually, yes.}
{268}{}{事实上，是的。}
### {269}{}{Really? This changes things! Listen, we have a couple of guys here who have been thinking about a raid on Jackals for a long time. If you show the lair, it will be easier for you to cope together.}
{269}{}{真正地这改变了一切！听着，我们这里有几个家伙，他们已经考虑突袭豺狼很长时间了。如果你展示了巢穴，你们会更容易一起应对。}
### {270}{}{Great, agreed. I'll be waiting for them in the burrows.}
{270}{}{太好了，同意了。我会在洞穴里等他们。}
### {271}{}{You know, it's too risky. I'll go without partners.}
{271}{}{你知道，这太冒险了。我将在没有合作伙伴的情况下离开。}
### {272}{}{Have you heard the news about Jackals?}
{272}{}{你听说关于豺狼的消息了吗？}
### {273}{}{Yes, I have. And you, it turns out, are not as bad as they thought you were. After all these events, now you will have more friends in Garage City.}
{273}{}{是的，我有。事实证明，你并没有他们想象的那么糟糕。经过所有这些活动，现在你将有更多的朋友在车库城。}
### {1273}{}{Yes, I heard. And you, it turns out, are not as bad as they thought you were. After all these events, now you will have more friends in Garage City.}
{1273}{}{是的，我听说了。事实证明，你并没有他们想象的那么糟糕。经过所有这些活动，现在你将有更多的朋友在车库城。}
### {274}{}{That's good.}
{274}{}{这很好。}
### {275}{}{Getting rid of the Jackal tribe has boosted your reputation in Garage City.}
{275}{}{摆脱豺狼部落提升了你在车库城的声誉。}
### {276}{}{Yes, I heard. The Rangers are completely crazy. After this, the road to Garage City will be closed to them. Tell them so if you meet them on your way.}
{276}{}{是的，我听说了。游骑兵队完全疯了。在此之后，通往车库城的道路将对他们关闭。如果你在路上遇到他们，就告诉他们。}
### {277}{}{OK.}
{277}{}{好啊}
### {278}{}{Hi. By the way, cool armor.}
{278}{}{你好顺便说一句，酷甲。}

#Refugees
### {280}{}{They say refugees have arrived to you?}
{280}{}{他们说难民来找你了？}
### {281}{}{Yeah. They are holed up in an abandoned hut in a residential area. But I don't think they will stay here for long.}
{281}{}{是 啊他们躲在一个居民区的一间废弃小屋里。但我认为他们不会在这里呆太久。}
### {282}{}{Why?}
{282}{}{为什么？}
### {283}{}{There is no work for them. And not every city will be able to settle down in such a place.}
{283}{}{他们没有工作。并不是每个城市都能在这样的地方定居下来。}
### {284}{}{I see. You say they're in a residential area? I just need to go to them.}
{284}{}{我明白了。你说他们在居民区？我只需要去找他们。}
### {285}{}{You're right - it's better not to linger in such a hole. I think I should go too.}
{285}{}{你说得对，最好不要在这样的洞里逗留。我想我也应该去。}

#Brahmins
### {287}{}{I can go after a brahmin.}
{287}{}{我可以去找一个婆罗门。}
### {288}{}{Great. Let's wait for the others...}
{288}{}{太棒了让我们等待其他人。。。}
### {289}{}{[Go to the wasteland]}
{289}{}{[去荒原]}
### {290}{}{They say a Brahmin hunt is planned?}
{290}{}{他们说计划进行婆罗门狩猎？}
### {291}{}{Yeah. A wild brahmin was seen in the desert, our guys are going to catch him and cut him into pieces. But it's not so easy to finish off such a strong beast. We need people to attack. Do you want to join?}
{291}{}{是 啊在沙漠里看到一个野生婆罗门，我们的人要抓住他，把他切成碎片。但是要干掉这么强壮的野兽可不是那么容易。我们需要人来攻击。你想加入吗？}
### {292}{}{First explain what kind of animal it is.}
{292}{}{首先解释一下它是什么动物。}
### {293}{}{A brahmin is... well... a large two-headed and four-legged beast. Lives in the desert, eats grass. Is that clear?}
{293}{}{婆罗门是…嗯。。。两头四条腿的大野兽。生活在沙漠里，吃草。清楚吗？}
### {294}{}{I need some time to pack. Don't leave without me.}
{294}{}{我需要一些时间收拾行李。别丢下我走。}
### {295}{}{I'm not interested in hunting. Shall we talk about something else?}
{295}{}{我对打猎不感兴趣。我们谈谈别的事情好吗？}
### {296}{}{Great, I'm in. When do we move out?}
{296}{}{太好了，我来了。我们什么时候搬出去？}
### {297}{}{When everyone is ready. Check your gear and come back to me.}
{297}{}{当每个人都准备好了。检查一下你的装备，然后回来找我。}
### {298}{}{OK.}
{298}{}{好啊}
### {299}{}{Oh, no, wait a little longer, I'll be back soon.}
{299}{}{哦，不，再等一会儿，我很快就会回来。}

#Questions
### {300}{}{It's the first time I've been so far from home. Can you tell us about this settlement?}
{300}{}{这是我第一次离家这么远。你能告诉我们这个和解方案吗？}
### {301}{}{Let's talk about Garage City?}
{301}{}{让我们谈谈车库城？}
### {302}{}{Get some alcohol at a local bar and use it directly on the gatekeeper to get him to talk.}
{302}{}{在当地酒吧喝点酒，直接用在看门人身上，让他说话。}
### {303}{}{I'd love to chat, but my throat is dry.}
{303}{}{我很想聊天，但我的喉咙很干。}
### {304}{}{Wait, I'll get you something to drink.}
{304}{}{等等，我给你拿点喝的。}
### {305}{}{More like a scam. You'll find a drink without me.}
{305}{}{更像是一个骗局。你会找到一杯没有我的饮料。}
### {306}{}{What do you want to know?}
{306}{}{你想知道什么？}
### {307}{}{Another question.}
{307}{}{另一个问题。}
### {308}{}{Enough talking, I have to go.}
{308}{}{说够了，我得走了。}

### {310}{}{How does this city live? It doesn't look like maize is being grown here.}
{310}{}{这个城市生活得怎么样？这里看起来不像是在种玉米。}
### {311}{}{Are you kidding? The whole city is obliged to mine on the ruins. Scavengers mine old things there, and then the cartel sells them to caravans.}
{311}{}{你在开玩笑吗？整个城市都不得不在废墟上挖掘。拾荒者在那里挖掘旧东西，然后卡特尔把它们卖给大篷车。}
### {312}{}{Who runs everything here?}
{312}{}{谁管理这里的一切？}
### {313}{}{We don't have a mayor or a sheriff. Scavengers are divided into clans, and each has its own leader. But they all obey Mr. Kogan. However, he is only interested in the work of the mine.}
{313}{}{我们没有市长或治安官。拾荒者被分为部族，每个部族都有自己的首领。但他们都服从Kogan先生。然而，他只对矿山的工作感兴趣。}
### {314}{}{Tell me about Kogan.}
{314}{}{告诉我关于Kogan的事。}
### {315}{}{Mr. Kogan runs a cartel of scavengers and does business with merchants. Don't ask me about him anymore. The boss doesn't like to be discussed.}
{315}{}{Kogan先生经营着一个拾荒者卡特尔，并与商人做生意。别再问我关于他的事了。老板不喜欢被人议论。}
### {316}{}{We don't have a mayor or a sheriff. Scavengers are divided into clans, and each has its own leader. They used to obey Mr. Kogan, but after his death, a serious fight for his chair began in the city.}
{316}{}{我们没有市长或治安官。拾荒者被分为部族，每个部族都有自己的首领。他们曾经服从Kogan先生，但在他去世后，城市里开始了一场争夺他的椅子的激烈斗争。}
### {317}{}{Tell me about yourself.}
{317}{}{告诉我你自己。}
### {318}{}{There's nothing to tell. I came with the others in the hope of making money on the mine. Fortunately, Mr. Kogan gave me a job as a gatekeeper. Now I make sure that no extra people go here, and scare away the animals.}
{318}{}{没什么好说的。我和其他人一起来是希望在矿场上赚钱。幸运的是，Kogan先生给了我一份看门人的工作。现在我确保没有多余的人来这里，吓跑动物。}
### {319}{}{And what kind of animals are found here?}
{319}{}{这里发现了什么样的动物？}
### {320}{}{Mostly coyotes and small radscorpions. Large rats can be found in the ruins. In general, this place will disappoint any trapper. They say that hunting is flourishing in the mountains in the east. I'm thinking about going there when it gets really bad in the Garage.}
{320}{}{主要是郊狼和小蝎子。废墟中可以找到大老鼠。总的来说，这个地方会让任何猎人失望。他们说东部山区的狩猎活动十分猖獗。当车库里的情况真的很糟糕的时候，我想去那里。}
### {321}{}{How old are these ruins?}
{321}{}{这些废墟有多古老？}
### {322}{}{Much more than you and me. They say the Great War happened 90 years ago. Since then, this place has been rusting and sinking into the sand.}
{322}{}{比你我多得多。他们说大战发生在90年前。从那时起，这个地方就开始生锈并沉入沙子。}
### {323}{}{What was here *before* The Great War?}
{323}{}{在大战之前这里是什么？}
### {324}{}{Some town called Kingman. But what's the difference? This is ancient history. Nobody cares anymore.}
{324}{}{一个叫金曼的小镇。但有什么区别呢？这是古老的历史。没人再在乎了。}
### {325}{}{Simple curiosity. Let's talk about something more important.}
{325}{}{单纯的好奇心。让我们谈谈更重要的事情。}
### {326}{}{Why do you live among all this junk?}
{326}{}{你为什么生活在这些垃圾堆里？}
### {327}{}{Do you have any better ideas? The old buildings are already unusable, we had to build new ones out of garbage.}
{327}{}{你有更好的主意吗？旧建筑已经无法使用了，我们不得不用垃圾建造新的。}

# About the slave convoy
### {330}{}{A slave convoy passed through here. You should know that.}
{330}{}{一支奴隶车队经过这里。你应该知道这一点。}
### {331}{}{I don't know what you're talking about. There was no slave convoy here. Talk to the guys at the bar or the cartel boss. Maybe the scavengers know something.}
{331}{}{我不知道你在说什么。这里没有奴隶车队。和酒吧里的人或卡特尔老板谈谈。也许拾荒者知道些什么。}
### {332}{}{Please tell me if you know. My relatives were there. Have you ever lost loved ones?}
{332}{}{如果你知道，请告诉我。我的亲戚也在那里。你曾经失去过亲人吗？}
### {333}{}{Okay, I'll talk to them.}
{333}{}{好吧，我会和他们谈谈。}
### {334}{}{(sighs) I didn't tell you that. The convoy left for the city of Flagstaff. Go east along the 40th Federal Highway. They say it takes a week to get there.}
{334}{}{（叹气）我没告诉你。车队启程前往弗拉格斯塔夫市。沿着40号联邦公路往东走。他们说要一个星期才能到达那里。}
### {335}{}{So Flagstaff. Thank you, amigo, you're a good guy.}
{335}{}{弗拉格斯塔夫也是。谢谢你，朋友，你是个好人。}
### {336}{}{So why the hell didn't you say so right away?! That's right, Jose told me about this hole.}
{336}{}{那你为什么不马上这么说？！没错，何塞告诉我这个洞的事。}
### {337}{}{I'm sorry for you, but I can't help you.}
{337}{}{我为你感到抱歉，但我帮不了你。}
### {338}{}{If you lie to me, you will pay cruelly for it.}
{338}{}{如果你对我撒谎，你将为此付出惨痛的代价。}
### {339}{}{Okay, I'll talk to the other residents.}
{339}{}{好的，我会和其他居民谈谈。}
### {340}{}{And keep in mind that the convoy is well armed and organized. These are not man-eating savages from the wasteland.}
{340}{}{请记住，车队装备精良，组织有序。这些不是来自荒原的食人族。}
### {341}{}{Thanks for the information.}
{341}{}{谢谢你提供的信息。}
### {342}{}{Bye, it's time for me to hit the road.}
{342}{}{再见，我该上路了。}

#Weapons
### {350}{}{You have a great gun.}
{350}{}{你有一把很棒的枪。}
### {351}{}{Yeah.}
{351}{}{是 啊}
### {352}{}{Uh, let's not talk about it.}
{352}{}{呃，我们不谈这个。}
### {353}{}{So we talked. Later.}
{353}{}{所以我们聊了聊。后来}

### {354}{}{Where did you get it?}
{354}{}{你从哪里得到的？}
### {355}{}{I bought it from a loser who was doing badly.}
{355}{}{我是从一个做得不好的失败者那里买的。}
### {356}{}{If it was a really good weapon, he wouldn't be a loser. There's clearly something you're not telling me.}
{356}{}{如果这是一个非常好的武器，他就不会是一个失败者。很明显，有些事情你没有告诉我。}
### {357}{}{Does it shoot?}
{357}{}{它会射吗？}
### {358}{}{You never dreamed. This gun has saved my life on duty more than once.}
{358}{}{你做梦也没想到。这把枪不止一次救了我的命。}
### {359}{}{Judging by the dirt on the hull, it has not been fired from it for a very long time.}
{359}{}{从船体上的泥土判断，它已经很久没有从上面发射了。}
### {360}{}{Don't you want to sell?}
{360}{}{你不想卖掉吗？}
### {361}{}{Hmm... no.}
{361}{}{嗯…没有。}
### {362}{}{The pause in the answer gives away that your gun is not that good. It doesn't shoot, right?}
{362}{}{答案中的停顿表明你的枪没有那么好。它不会开枪，对吧？}

### {363}{}{Damn it, how did you guess? (sigh) Your truth, it doesn't shoot. And count the cartridges on your fingers. What's next?}
{363}{}{该死，你怎么猜到的？（叹气）你的真相，它不会开枪。数数你手指上的子弹。下一步是什么？}
### {1363}{}{Damn it, how did you guess? (sigh) Your truth, it doesn't shoot. And count the cartridges on your fingers. Come on, laugh at the top of your voice.}
{1363}{}{该死，你怎么猜到的？（叹气）你的真相，它不会开枪。数数你手指上的子弹。来吧，大声笑。}
### {364}{}{Why do you need a non-firing gun?}
{364}{}{为什么你需要一把不开火的枪？}
### {365}{}{To intimidate, stupid! And when it's necessary, I can put a hole in my groin with a muzzle. Is that clear?}
{365}{}{恐吓，愚蠢！必要的时候，我可以用枪口在腹股沟打个洞。清楚吗？}
### {366}{}{Is there really no one here to fix this gun?}
{366}{}{这里真的没有人修理这把枪吗？}
### {367}{}{Our mechanic doesn't have the right parts. It is difficult to find firearms in working condition in these parts. And even if he fixes the gun, there's still nothing to shoot with.}
{367}{}{我们的机修工没有合适的零件。在这些零件中很难找到处于工作状态的枪支。即使他把枪修好了，也没有什么可射击的。}
### {368}{}{I can fix it.}
{368}{}{我能修好。}
### {369}{}{Seriously? That would be very helpful. I'll pay 25 caps if you succeed.}
{369}{}{认真地那将非常有帮助。如果你成功了，我将支付25顶帽子。}
### {370}{}{I can't handle your gun right now. We'll talk about it later.}
{370}{}{我现在拿不动你的枪。我们稍后再谈。}
### {371}{}{Yes, it doesn't fire. And count the cartridges on your fingers. What's next?}
{371}{}{是的，它不会着火。数数你手指上的子弹。下一步是什么？}
### {372}{}{I want to buy this gun.}
{372}{}{我想买这把枪。}
### {373}{}{Oh, nothing.}
{373}{}{哦，没什么。}
### {374}{}{I see. It's clear that it's better for me to leave you.}
{374}{}{我明白了。很明显，我最好离开你。}
### {375}{}{Looks like you're in trouble, man. Well, I'll go.}
{375}{}{看来你有麻烦了，伙计。好吧，我走。}
### {376}{}{Let's see...}
{376}{}{让我们看看。。。}
### {377}{}{I'll be damned, you did it! And it seemed to me that the peasants had never held weapons in their hands. Uh, I mean, I'm grateful to you. Here are 25 caps, as agreed. Eh, I would still like to find more cartridges...}
{377}{}{我会被诅咒的，是你干的！在我看来，农民们从来没有拿过武器。呃，我的意思是，我很感激你。按照约定，这里有25顶帽子。呃，我还是想找更多的子弹。。。}
### {378}{}{Enjoy, my business here is over.}
{378}{}{享受吧，我在这里的生意结束了。}
### {379}{}{No, I can't fix it.}
{379}{}{不，我修不好。}
### {380}{}{I thought so.}
{380}{}{我是这么想的。}
### {381}{}{I mean, I can't fix it right now. Maybe later.}
{381}{}{我的意思是，我现在无法修复。也许以后吧。}
### {382}{}{Now I definitely won't even touch your gun.}
{382}{}{现在我绝对不会碰你的枪。}
### {383}{}{For such bottlecaps, I can only carry your barrel to the nearest trash can. Look for someone else.}
{383}{}{对于这样的瓶子，我只能把你的桶带到最近的垃圾桶。找其他人。}
