### {100}{}{Here is an assistant.}
{100}{}{这是一位助理。}
### {101}{}{You see a disfigured person. His face slides down like wax.}
{101}{}{你看到一个毁容的人。他的脸像蜡一样往下滑。}

### {110}{}{It's strange that they let you in here.}
{110}{}{他们让你进来真奇怪。}
### {111}{}{I don't have time to talk to pagans.}
{111}{}{我没有时间和异教徒说话。}
### {112}{}{I don't have anything for you.}
{112}{}{我没有什么要给你的。}
### {113}{}{Leave me alone or I'll call my green brothers.}
{113}{}{别管我，否则我会打电话给我的绿色兄弟。}
### {114}{}{What's wrong with your skin? Well, you're ugly.}
{114}{}{你的皮肤怎么了？嗯，你很丑。}
### {115}{}{I don't understand how you normies can survive in the modern world.}
{115}{}{我不明白你们这些正常人怎么能在现代世界生存。}
### {116}{}{Desert dwellers are stupid.}
{116}{}{沙漠居民是愚蠢的。}
### {117}{}{Obey Levi.}
{117}{}{Obey Levi。}
### {118}{}{I don't trust you or strangers like you.}
{118}{}{我不信任你，也不信任像你这样的陌生人。}
### {119}{}{Our people have suffered so much from normics...}
{119}{}{我们的人民遭受了如此多的病毒感染。。。}

### {120}{}{Oh, come in, friend, have a seat.}
{120}{}{哦，进来吧，朋友，坐下。}
### {121}{}{Even though you are a pagan, but at least harmless.}
{121}{}{尽管你是异教徒，但至少无害。}
### {122}{}{Should I make you some radioactive coffee?}
{122}{}{我应该给你煮一些放射性咖啡吗？}
### {123}{}{Excuse my green brothers, they are out of the habit of normal people.}
{123}{}{对不起，我的绿色兄弟们，他们已经脱离了正常人的习惯。}
### {124}{}{What's wrong with your skin? How did you manage to save it?}
{124}{}{你的皮肤怎么了？你是怎么保存的？}
### {125}{}{You normies are doing great in this new world.}
{125}{}{你们这些正常人在这个新世界做得很好。}
### {126}{}{People amaze me with their vitality.}
{126}{}{人们的活力令我惊讶。}
### {127}{}{Obey Levi, he was God's own confidant!}
{127}{}{Obey Levi，他是上帝的心腹！}
### {128}{}{I trust you. But not to these racists from the Brotherhood of Steel.}
{128}{}{我信任你。但不是对这些来自钢铁兄弟会的种族主义者。}
### {129}{}{Our people have been through a lot. You wouldn't understand.}
{129}{}{我们的人民经历了很多。你不会理解的。}
