### {110}{}{This jukebox is broken.}
{110}{}{这个自动存储塔坏了。}
### {111}{}{The jukebox has been restored and is ready to make terrible creaking noises called music.}
{111}{}{自动点唱机已经修复，可以发出可怕的吱吱声，称为音乐。}
### {112}{}{The jukebox has been successfully restored. Oh, how loud!}
{112}{}{自动存储塔已成功还原。哦，好大声！}
### {113}{}{The musical automaton is finally coming out of the string.}
{113}{}{音乐自动机终于从琴弦上出来了。}

### {120}{}{*Boom boom*}
{120}{}{*动臂*}
### {121}{}{*sh-sh-sh*}
{121}{}{*嘘嘘*}
### {122}{}{*sadum-padum*}
{122}{}{*鞍垫*}
### {123}{}{*Shi-boom, shi-boom*}
{123}{}{*史轰，史轰*}
### {124}{}{*Sha-la-la*}
{124}{}{*沙拉拉*}
### {125}{}{*?rum-pum-pum*}
{125}{}{*?朗姆酒*}
