### {100}{}{Here is a raider.}
{100}{}{这是一个袭击者。}
### {101}{}{You see a bandit you already know. He hasn't changed at all since the meeting in the Casa Grande bar.}
{101}{}{你看到了一个你已经认识的土匪。自从在Casa Grande酒吧开会后，他一点也没变。}
### {102}{}{You can't be here. Go away. Let's assume I didn't see you.}
{102}{}{你不能在这里。走开。假设我没看见你。}

### {200}{}{So, you're here. What a surprise. How are the mayor and his spoiled daughter?}
{200}{}{所以，你来了。真是个惊喜。市长和他娇生惯养的女儿过得怎么样？}
### {201}{}{I think they have a lot to think about. So, after that story in the bar, will you continue to rob and take hostages?}
{201}{}{我认为他们有很多事情要考虑。那么，在酒吧的那个故事之后，你还会继续抢劫和劫持人质吗？}
### {202}{}{Hmm, not a bad idea. But it's not that simple. Ben has a plan. Let's see what happens. Talk to him, maybe he'll need you.}
{202}{}{嗯，这个主意不错。但事情并没有那么简单。本有个计划。让我们看看会发生什么。和他谈谈，也许他会需要你。}
### {203}{}{I will do so.}
{203}{}{我会这么做的。}
### {204}{}{Wait. I kept thinking about that story at the bar. I don't know why you helped us, but it would be unfair to remain unanswered. I told the other guys about you so that they would treat you better. And also take a gun and a pack of cartridges. Maybe you don't want to cause pain, but you should still think about your own protection.}
{204}{}{等待我一直在想酒吧里的那个故事。我不知道你为什么帮助我们，但如果不回答，那是不公平的。我把你的事告诉了其他人，这样他们会对你更好。还要带一把枪和一包子弹。也许你不想引起疼痛，但你仍然应该考虑自己的保护。}
### {205}{}{Thank you.}
{205}{}{非常感谢。}
### {206}{}{Real highway workers don't say "thank you" and "please." Remember that.}
{206}{}{真正的高速公路工人不会说“谢谢”和“请”。记住这一点。}
### {207}{}{Yes, bye.}
{207}{}{是的，再见。}
### {208}{}{Not a bad survival kit.}
{208}{}{不错的生存装备。}
### {209}{}{Good luck on the tracks. Let the dust of the road hit you in the back, and the eyes of the enemies are blurred.}
{209}{}{祝你在赛道上好运。让路上的尘土打在你的背后，敌人的眼睛都模糊了。}

### {210}{}{Hi. How is it?}
{210}{}{你好怎么样？}
### {211}{}{Nothing, yet.}
{211}{}{什么都没有。}
