### {100}{}{This is Wang Chun.}
{100}{}{这是王春。}
### {101}{}{You see a large spreading tree. The pattern on its bark reminds you of a man's face. Wait a minute...}
{101}{}{你看到一棵蔓延的大树。树皮上的图案让你想起一张男人的脸。等一下。。。}
### {102}{}{*Cough-cough*}
{102}{}{*咳嗽*}
### {103}{}{It's hard to talk in this smoke. We need to get out into the fresh air faster.}
{103}{}{在这烟雾中很难说话。我们需要更快地出去呼吸新鲜空气。}

### {110}{}{Hr-r-r}
{110}{}{Hr-r}
### {111}{}{Z-z-z}
{111}{}{Z-Z-Z}
### {112}{}{Here, my sweet mantissas, yes, get in your mouth.}
{112}{}{给，我亲爱的螳螂，是的，进入你的嘴里。}
### {113}{}{Yum, yum, what a juicy mantissa.}
{113}{}{好吃，好吃，好多汁的尾数。}
### {114}{}{My roots feel a stranger.}
{114}{}{我的根感到陌生。}
### {115}{}{Hmm, I smell an unfamiliar footstep.}
{115}{}{嗯，我闻到一股陌生的脚步声。}
### {116}{}{What is it? What are you saying?}
{116}{}{它是什么？你在说什么？}
### {117}{}{Herbert, Bob, Nestor - you've grown so much lately.}
{117}{}{赫伯特，鲍勃，内斯特——你最近长得太大了。}
### {118}{}{Now I understand how you miss the sunlight.}
{118}{}{现在我明白你多么想念阳光了。}
### {119}{}{We need more fertilizers from human compost.}
{119}{}{我们需要更多来自人类堆肥的肥料。}
### {120}{}{Oh-x...}
{120}{}{哦。。。}
### {121}{}{*Heavy sigh*}
{121}{}{*沉重的叹息*}

### {150}{}{Go ahead, my little green friends!}
{150}{}{加油，我的绿色小朋友们！}
### {151}{}{Grab them and tear them to shreds!}
{151}{}{抓住它们，把它们撕成碎片！}
### {152}{}{Show your grip!}
{152}{}{展示你的抓地力！}
### {153}{}{Grab them with your sharp paws!}
{153}{}{用你锋利的爪子抓住它们！}

### {200}{}{Ah... uh... Wow. How long I slept... Oh, Mom. So that's why the servants woke me up.}
{200}{}{啊。。。嗯哇！我睡了多久。。。哦，妈妈。这就是仆人叫醒我的原因。}
### {201}{}{Eh, who are you... or what are you?}
{201}{}{呃，你是谁。。。或者你是什么？}
### {202}{}{Horror! A talking plant!}
{202}{}{恐怖会说话的植物！}
### {203}{}{I am Wang Chun, the scientist who created these gardens of paradise. And who are you? Oh, yes, I know. People like you flock to the smell of nectar, like stupid dummies, so that soon they will be eaten by predatory plants. In any case, coming here is a big mistake on your part.}
{203}{}{我就是王淳，创造了这些天堂花园的科学家。你是谁？哦，是的，我知道。像你这样的人像愚蠢的假人一样，对花蜜的气味趋之若鹜，很快就会被食肉植物吃掉。不管怎样，来这里对你来说都是个大错误。}
### {204}{}{Why so?}
{204}{}{为什么会这样？}
### {205}{}{You know, if I wasn't obsessed with science and the prosperity of the world, I would have run away from here long ago. But now I belong here. My grave will be here. If you come out of the earth, you will return to it.}
{205}{}{你知道，如果我没有痴迷于科学和世界的繁荣，我早就逃离了这里。但现在我属于这里。我的坟墓就在这里。如果你从地球上走出来，你就会回到地球上。}
### {206}{}{What are you talking about?}
{206}{}{你在说什么？}
### {207}{}{Circular circulation of matter in nature. We are all a lump of sticky mud. Look at me. I won't be able to walk anymore. Rooted to the ground where he used to wander like an amaranth tumbleweed.}
{207}{}{自然界物质的循环。我们都是一团黏糊糊的泥。看着我，我再也走不动了。扎根在地上，他曾经像一株紫红色的风滚草一样游荡。}
### {208}{}{You're too talkative for a plant.}
{208}{}{你太健谈了。}
### {209}{}{Funny. I can no longer work with my hands and feet, but my brain is still in action. I'm holding on with the last of my strength so as not to go crazy. But I had a lot of time to think about myself and the world around me.}
{209}{}{有趣的我再也不能用手和脚工作了，但我的大脑仍然在工作。我正在竭尽全力，以免发疯。但我有很多时间思考自己和周围的世界。}
### {210}{}{I am so sorry. Are you in pain?}
{210}{}{我很抱歉。你疼吗？}
### {211}{}{Not anymore. My body is replaced by spores and plant cells. I can't work with my hands and feet, but my brain is still in action. I'm holding on with the last of my strength so as not to go crazy. But I had a lot of time to think about myself and the world around me.}
{211}{}{不再是了。我的身体被孢子和植物细胞所取代。我不能用手和脚工作，但我的大脑仍在工作。我正在竭尽全力，以免发疯。但我有很多时间思考自己和周围的世界。}
### {212}{}{It's sad to see you like this. But I have business here. Bye.}
{212}{}{看到你这样真是令人难过。但我在这里有生意。再见}
### {213}{}{No! Stop! I was just as stupid and careless when I came to this dome hoping to taste the fruits of the Ancients. I was in too much of a hurry and made a number of mistakes. Now the whole valley is a paradise for mutants. And if this is not stopped, the whole wasteland will change. People will see the birth of a new world, but there will be no place for them in it.}
{213}{}{不停止当我来到这个圆顶，希望品尝古人的果实时，我也同样愚蠢和粗心。我太匆忙了，犯了很多错误。现在整个山谷都是变种人的天堂。如果不停止这种做法，整个荒原就会改变。人们将看到一个新世界的诞生，但这个世界将没有他们的容身之地。}
### {214}{}{I'm here on Nestor's assignment. I need documents and chemicals to fight the infection.}
{214}{}{我是来接内斯特的任务的。我需要文件和化学品来对抗感染。}
### {215}{}{I don't want to be exposed to the same infection. Is there any medicine against it?}
{215}{}{我不想暴露在同样的感染之下。有特效药吗？}
### {216}{}{And what is "contagion"? People parasitizing on the remnants of an old civilization? Oh, how blind I was when I came to this dome hoping to taste the fruits of the Ancients! I was in too much of a hurry and made a number of mistakes. Now the whole valley is a paradise for mutants. And if this is not stopped, the whole wasteland will change. And people... there will be no place for people in this new world.}
{216}{}{什么是“传染”？寄生在旧文明残余上的人？哦，当我来到这个圆顶，希望品尝古人的果实时，我是多么的盲目！我太匆忙了，犯了很多错误。现在整个山谷都是变种人的天堂。如果不停止这种做法，整个荒原就会改变。人们。。。在这个新世界里，人们将没有立足之地。}
### {217}{}{How so? Can't this infection be stopped?}
{217}{}{为什么呢这种感染不能被阻止吗？}
### {218}{}{May. But if the Followers receive laboratory records and other materials of the complex, someday they will continue their research. And the trouble will happen again.}
{218}{}{也许吧。但如果追随者们收到实验室记录和其他复杂的材料，总有一天他们会继续他们的研究。麻烦还会再次发生。}
### {219}{}{Then what do you suggest?}
{219}{}{那你有什么建议？}
### {220}{}{We need to destroy the WHOLE complex! Fire is the best way to stop the spread of infection beyond the valley. After all, the dome is its main breeding ground.}
{220}{}{我们需要摧毁整个综合体！火灾是阻止感染传播到山谷之外的最好方法。毕竟，圆顶是它的主要繁殖地。}
### {221}{}{The main thing is to stop mutations. I'll do it.}
{221}{}{最重要的是阻止突变。我会做的。}
### {222}{}{Oh-very good, pilgrim. Find the gas pipes. It's not easy to set them on fire, but someone has already tried. Find his digested remains in the greenhouses and take the explosives.}
{222}{}{哦，很好，朝圣者。找到煤气管道。点燃它们并不容易，但已经有人尝试过了。在温室里找到他被消化的遗体，然后拿走炸药。}
### {223}{}{Okay. I'll try.}
{223}{}{可以我会试试的。}
### {224}{}{Too risky. Bye, Wang Chun.}
{224}{}{风险太大。再见，王春。}
### {225}{}{You're definitely going crazy. There is no place in the wastelands more colorful and lively than the dome. Surely there is a way to stop the infection without a fire.}
{225}{}{你肯定快疯了。在荒原上，没有什么地方比圆顶更丰富多彩、更热闹了。毫无疑问，有一种方法可以在不生火的情况下阻止感染。}
### {226}{}{Stupid! I was looking for ways to limit the growth of harmful spores. But no one knows if it will work! Suddenly the growth will continue? Find the gas pipes and blow them up! This is the only way!}
{226}{}{愚蠢的我在寻找限制有害孢子生长的方法。但没有人知道它是否有效！突然间增长会继续吗？找到煤气管，把它们炸了！这是唯一的办法！}

### {230}{}{*Heavy sigh*}
{230}{}{*沉重的叹息*}
### {231}{}{Z-z-z}
{231}{}{Z-Z-Z}
### {232}{}{Hr-r-r}
{232}{}{Hr-r}
### {233}{}{Whatever it is, this creature is fast asleep.}
{233}{}{不管是什么，这个生物都睡得很熟。}
