### {100}{}{Here is a monk.}
{100}{}{这是一个和尚。}
### {101}{}{You see a man in a cassock. He was clearly not here by chance.}
{101}{}{你看到一个穿着袈裟的男人。他显然不是偶然来到这里的。}
### {102}{}{Your place is in the desert, savage.}
{102}{}{你的住处在沙漠里，野蛮人。}
### {1102}{}{Your place is in the desert, savage.}
{1102}{}{你的住处在沙漠里，野蛮人。}
### {103}{}{May the Sacred Fire bless you.}
{103}{}{愿圣火保佑你。}
### {104}{}{Being here, you risk being on a punitive bonfire.}
{104}{}{在这里，你冒着被点燃惩罚性篝火的风险。}

### {200}{}{Greetings, kind man. Can I find out how your path crossed with the atomists?}
{200}{}{你好，善良的人。我能了解一下你是如何与原子论者相交的吗？}
### {201}{}{I don't even know. An accident, probably. What are you doing here?}
{201}{}{我甚至不知道。可能是意外。你在这里干什么？}
### {202}{}{Oh, I'm just a peaceful pilgrim of the Sacred Fire Church. Our religion worships old knowledge and strives for the rebirth of the world. This nuclear power plant is very important for our mission. It would be very sad to know that she fell into the wrong hands.}
{202}{}{哦，我只是圣火教堂的一个和平的朝圣者。我们的宗教崇拜古老的知识，为世界的重生而奋斗。这个核电站对我们的任务非常重要。如果知道她落入坏人之手，那将是非常难过的。}
### {203}{}{I think you have nothing to fear. Now Ralph is at the head of the station. He's going to renegotiate the contract with the church. You will be satisfied.}
{203}{}{我认为你没有什么可害怕的。现在拉尔夫是车站的站长。他将与教会重新谈判合同。你会满意的。}
### {204}{}{Glory to the Atom! Is that what we should be thanking you for? The world is getting better, with your help. Thank you, stranger. Visit our church when you have time.}
{204}{}{原子的荣耀！这就是我们应该感谢你的原因吗？在你的帮助下，世界正在变得更好。谢谢你，陌生人。有时间参观我们的教堂。}
### {1204}{}{Glory to the Atom! Is that what we should be thanking you for? The world is getting better, with your help. Thank you, stranger. Visit our church when you have time.}
{1204}{}{原子的荣耀！这就是我们应该感谢你的原因吗？在你的帮助下，世界正在变得更好。谢谢你，陌生人。有时间参观我们的教堂。}
### {205}{}{Necessarily. Goodbye.}
{205}{}{必要地再见}

### {250}{}{So, is it because of you that our plans collapsed, like the Old World? Why are you doing this?}
{250}{}{那么，是不是因为你，我们的计划像旧世界一样崩溃了？你为什么这么做？}
### {251}{}{I don't like you.}
{251}{}{我不喜欢你。}
### {252}{}{Don't you like the idea of Rebirth? Or don't you like our church with its symbols? In either case, you're just an egoist. An atomic nonentity with an inflated conceit. The Church has given the world Knowledge. With their help, we turned on the lights in the houses and taught some people forgotten literacy. And you? What are you trying to achieve?}
{252}{}{你不喜欢《重生》的想法吗？或者你不喜欢我们的教堂和它的象征吗？无论哪种情况，你都只是一个利己主义者。一个自负的原子。教会给了世界知识。在他们的帮助下，我们打开了房子里的灯，教一些被遗忘的人识字。你呢？你想达到什么目的？}
### {253}{}{Because of your "rebirth" my house is empty. That's enough.}
{253}{}{因为你的“重生”，我的房子是空的。够了。}
### {254}{}{Oh, so we're dealing with animal revenge. In that case, we have nothing more to talk about. Animals do not understand speech, but only understand the whip. Get back to the desert and lead your wild life like a savage. There is no place for people like you in the New World.}
{254}{}{哦，所以我们在处理动物复仇。在这种情况下，我们没有什么可谈的了。动物不懂语言，只懂鞭子。回到沙漠，像个野蛮人一样过你狂野的生活。在新世界里没有像你这样的人的容身之地。}
### {255}{}{Not before I beat the shit out of you, holy man.}
{255}{}{在我把你打得落花流水之前，神圣的人。}
### {256}{}{With pleasure. I don't want to see this whole bastion of sin.}
{256}{}{很高兴。我不想看到这整个罪恶的堡垒。}
### {257}{}{Ralph paid less.}
{257}{}{拉尔夫付的更少。}
### {258}{}{Have the bottlecaps become a reliable adviser for you? In that case, you're just an ordinary egoist. The Church has given the world Knowledge. With their help, we turned on the lights in the houses and taught some people forgotten literacy. And what will a handful of caps in your pocket give this city?}
{258}{}{装瓶人成为你可靠的顾问了吗？在这种情况下，你只是一个普通的利己主义者。教会给了世界知识。在他们的帮助下，我们打开了房子里的灯，教一些被遗忘的人识字。你口袋里的几顶帽子会给这个城市带来什么？}
### {259}{}{I'm just fulfilling a deal. This is a fair contract.}
{259}{}{我只是在履行一项协议。这是一份公平的合同。}
### {260}{}{Perhaps. Perhaps the Old World has fallen because of the greed of your kind. And that's why people like you have no place in the New World. From now on, your presence in the city does not please the Church of Fire. Everyone will be better off if you leave.}
{260}{}{可能也许旧世界的衰落是因为你们这种人的贪婪。这就是为什么像你这样的人在新世界没有立足之地。从现在起，你在这个城市的存在不会取悦火之教会。如果你离开，每个人都会过得更好。}
### {261}{}{Not before I beat the shit out of you.}
{261}{}{在我把你打得落花流水之前。}
### {262}{}{With pleasure. I don't want to stay in such an unfair city anymore.}
{262}{}{很高兴。我不想再呆在这样一个不公平的城市了。}
### {263}{}{You won't know it, dead man.}
{263}{}{你不会知道的，死人。}
