### {100}{}{There's a ghost in front of you!}
{100}{}{你面前有个鬼！}
### {101}{}{You see... the soul of a man burned in a nuclear flame.}
{101}{}{你看。。。一个人的灵魂在核火焰中燃烧。}

### {102}{}{What the hell is this?}
{102}{}{这到底是什么？}
### {103}{}{It wasn't real, was it?}
{103}{}{这不是真的，是吗？}
### {104}{}{I think I'm going crazy... Or not?}
{104}{}{我想我快疯了。。。还是不？}
### {105}{}{These souls are everywhere!}
{105}{}{这些灵魂无处不在！}

### {110}{}{Look what you've done!}
{110}{}{看看你做了什么！}
### {111}{}{It's your fault!}
{111}{}{这是你的错！}
### {112}{}{Why did you do this to us?}
{112}{}{你为什么这样对我们？}
### {113}{}{Why did you kill us?}
{113}{}{你为什么杀了我们？}
### {114}{}{We will haunt you all your life.}
{114}{}{我们会困扰你一辈子。}
### {115}{}{The murderer!}
{115}{}{凶手！}

### {1110}{}{Look what you've done!}
{1110}{}{看看你做了什么！}
### {1111}{}{It's your fault!}
{1111}{}{这是你的错！}
### {1112}{}{Why did you do this to us?}
{1112}{}{你为什么这样对我们？}
### {1113}{}{Why did you kill us?}
{1113}{}{你为什么杀了我们？}
### {1114}{}{We will haunt you all your life.}
{1114}{}{我们会困扰你一辈子。}
### {1115}{}{The murderer!}
{1115}{}{凶手！}
