### {100}{}{This is your opponent.}
{100}{}{这是你的对手。}
### {101}{}{This is a Savage.}
{101}{}{这是野蛮人。}
### {102}{}{This is Canelo.}
{102}{}{这是卡内洛。}
### {103}{}{This is Big Mario.}
{103}{}{这是大马里奥。}
### {104}{}{It's a Super Mutant.}
{104}{}{这是一个超级突变体。}

### {105}{}{You see your opponent. He seems to hint that he put it on you.}
{105}{}{你看到了你的对手。他似乎在暗示他把它放在你身上了。}
### {106}{}{You see your opponent. He seems to be hinting that you are not his equal.}
{106}{}{你看到了你的对手。他似乎在暗示你不是他的对手。}
### {107}{}{You see your opponent. He only sees you as a target.}
{107}{}{你看到了你的对手。他只把你当成目标。}
### {108}{}{You see your opponent. And in his eyes - unspeakable rage.}
{108}{}{你看到了你的对手。在他的眼里——难以形容的愤怒。}
### {109}{}{You see your opponent. But you'd better not see him.}
{109}{}{你看到了你的对手。但你最好别见到他。}

### {110}{}{DIE!}
{110}{}{死！}
