### {100}{}{You see a child.}
{100}{}{你看到一个孩子。}
### {101}{}{Here is a local child. He smells of fish and mud.}
{101}{}{这是一个当地的孩子。他身上有鱼和泥的味道。}

### {110}{}{Garth Ranger. He kills people like you.}
{110}{}{Garth Ranger。他杀了像你这样的人。}
### {111}{}{Don't touch me.}
{111}{}{别碰我。}
### {112}{}{What kind of hole are you from, huh?}
{112}{}{你是从什么地方来的？}
### {113}{}{You're talking strangely..}
{113}{}{你说话很奇怪。。}
### {114}{}{}
{114}{}{error : string is empty}
### {115}{}{}
{115}{}{error : string is empty}
### {116}{}{}
{116}{}{error : string is empty}
### {117}{}{}
{117}{}{error : string is empty}
### {118}{}{* Yawns*}
{118}{}{*Yawns*}
### {119}{}{Z-z-z}
{119}{}{Z-Z-Z}

### {120}{}{Are you here for a long time?}
{120}{}{你在这里很长时间了吗？}
### {121}{}{Where are you from?}
{121}{}{你是哪里人？}
### {122}{}{Do you want to play?}
{122}{}{你想玩吗？}
### {123}{}{Do you know interesting places around?}
{123}{}{你知道周围有趣的地方吗？}
### {124}{}{A monster lives at the bottom of the bay.}
{124}{}{一个怪物住在海湾的底部。}
### {125}{}{If you swim in this water, horns will grow.}
{125}{}{如果你在这水里游泳，角就会长出来。}
### {126}{}{Do you have anything delicious?}
{126}{}{你有好吃的吗？}
### {127}{}{Be, this fish is rotten.}
{127}{}{是的，这条鱼腐烂了。}
### {128}{}{I'm looking for something useful.}
{128}{}{我在找有用的东西。}
### {129}{}{}
{129}{}{error : string is empty}

### {130}{}{It's called a motorcycle, right?}
{130}{}{它叫摩托车，对吧？}
### {131}{}{Wow, does this thing really know how to drive itself?}
{131}{}{哇，这东西真的会自己开车吗？}
### {132}{}{So do you also command old technology, like old Rufus?}
{132}{}{那么，你是否也掌握了旧技术，比如老鲁弗斯？}
### {133}{}{Can you ride this motorcycle?}
{133}{}{你会骑这辆摩托车吗？}
### {134}{}{Can this bike catch fish or predict the weather?}
{134}{}{这辆自行车能钓鱼还是能预测天气？}
### {135}{}{In my opinion, the Rangers should also get themselves motorcycles.}
{135}{}{在我看来，游骑兵队也应该给自己买摩托车。}
### {136}{}{Where did you get a motorcycle from?}
{136}{}{你从哪里买摩托车的？}
