### {100}{}{You see a stranger.}
{100}{}{你看到一个陌生人。}
### {101}{}{Here is a boy in worn-out clothes.}
{101}{}{这是一个穿着破旧衣服的男孩。}
### {102}{}{Good luck. I'm leaving the Aqueduct soon. I'll try to find a place to live upstream of Colorado.}
{102}{}{祝你好运我马上就要离开渡槽了。我会设法在科罗拉多上游找个地方住。}
### {103}{}{What happened... in that water...}
{103}{}{发生了什么。。。在那水里。。。}
### {104}{}{Ah-x...}
{104}{}{啊。。。}

#Dialog
### {200}{}{Uh, hello?}
{200}{}{喂？}
### {201}{}{I'm new here. Looking for dating.}
{201}{}{我是新来的。正在寻找约会。}
### {202}{}{That's how... great. I'm new here too. And I'm not lucky at dating.}
{202}{}{这就是为什么。。。太棒了我也是新来的。我在约会方面运气不好。}
### {203}{}{Did something happen?}
{203}{}{发生什么事了吗？}
### {204}{}{I came with two friends, but they disappeared, and the locals don't want to do business with me. Now I'm sitting by the fire, fishing and thinking about the future.}
{204}{}{我和两个朋友来了，但他们不见了，当地人不想和我做生意。现在我坐在炉火边钓鱼，想着未来。}
### {205}{}{A sad story. I'm sorry.}
{205}{}{一个悲伤的故事。对不起。}
### {206}{}{The distrust of the locals is understandable.}
{206}{}{当地人的不信任是可以理解的。}

### {210}{}{What do you want?}
{210}{}{你想要什么？}
### {211}{}{Nothing. So far.}
{211}{}{没有什么目前为止}
### {212}{}{Well, how's the search going?}
{212}{}{搜索进展如何？}
### {213}{}{Sorry, but I haven't been able to find out anything yet.}
{213}{}{对不起，我什么都没找到。}
### {214}{}{Hello.}
{214}{}{你好}
### {215}{}{Later.}
{215}{}{后来}

### {220}{}{What about the Rangers? They can't find your group?}
{220}{}{游骑兵队呢？他们找不到你的团队？}
### {221}{}{I talked to Garth, he's kind of the sheriff here. But it doesn't look like he's doing anything. And what can he do? I've already interviewed the locals myself, no one knows anything.}
{221}{}{我和加思谈过了，他是这里的治安官。但看起来他什么都没做。他能做什么？我自己也采访过当地人，没人知道。}
### {222}{}{Where are you and your band from?}
{222}{}{你和你的乐队来自哪里？}
### {223}{}{We fled from a small village far from here when life there became unbearable. We were told that the Rangers were ready to take everyone under their protection. Although it doesn't look like we're welcome here.}
{223}{}{当那里的生活变得难以忍受时，我们逃离了远离这里的一个小村庄。我们被告知游骑兵队已经做好了保护所有人的准备。虽然看起来我们不受欢迎。}
### {224}{}{I'll look for your people and if I find out something, I'll let you know.}
{224}{}{我会去找你的人，如果我发现什么，我会告诉你的。}
### {225}{}{Thank you. Tell me everything you find out.}
{225}{}{非常感谢。告诉我你发现的一切。}
### {226}{}{Bye. See you later.}
{226}{}{再见回头见。}

### {230}{}{I managed to find your friends... at the bottom of the aqueduct.}
{230}{}{我设法找到了你的朋友。。。在渡槽底部。}
### {231}{}{They're dead, aren't they? Damn... Now I understand why Garth forbids going to that ancient structure. Surely we're not the first ones he and his henchmen have killed. Damn Rangers...}
{231}{}{他们死了，不是吗？该死现在我明白为什么加思禁止去那个古老的建筑了。我们肯定不是他和他的党羽杀死的第一批人。该死的流浪者。。。}
### {232}{}{What are you going to do now?}
{232}{}{你现在打算做什么？}
### {233}{}{I would like to take revenge on this bastard so that history does not repeat itself. But this way I will only make enemies for myself. In any case, I can't stay here.}
{233}{}{我想报复这个混蛋，这样历史就不会重演了。但这样我只会为自己树敌。无论如何，我不能呆在这里。}
### {234}{}{How about a report to the base? I don't think the command is aware.}
{234}{}{去基地报到怎么样？我认为指挥部没有意识到。}
### {235}{}{They won't let me see the commander, I've already tried. Can you do it? If Garth is not stopped, he will continue to eliminate all objectionable.}
{235}{}{他们不让我见指挥官，我已经试过了。你能做到吗？如果加思没有被阻止，他将继续消除所有令人反感的东西。}
### {236}{}{I will try to reach the general. Although it won't be easy.}
{236}{}{我会设法联系将军。尽管这并不容易。}
### {237}{}{You're a wonderful person. Thank you.}
{237}{}{你是个了不起的人。非常感谢。}
### {238}{}{Wait for news, man.}
{238}{}{等待消息，伙计。}
### {239}{}{Go to hell, I'm already up to my ears in shit because of you.}
{239}{}{见鬼去吧，因为你，我已经到了极点了。}
### {240}{}{Of course, forget it. I'll just walk out of here, and Garth will go unpunished... yes. It's BETTER this WAY.}
{240}{}{当然，忘了它。我就离开这里，加思就会逍遥法外。。。对这样更好。}
### {241}{}{Just don't put pressure on my feelings! Adios, man.}
{241}{}{只是不要给我的感情施加压力！再见，伙计。}
### {242}{}{Let's just kill Garth? It will be easier and more fun.}
{242}{}{我们杀了加思吧？这会更容易，更有趣。}
### {243}{}{Finish off a ranger and end up on the list of criminals? Damn, I don't want to run away from the Rangers for the rest of my life. It's better if I just leave here.}
{243}{}{干掉一个护林员，然后被列入罪犯名单？该死，我这辈子都不想逃离流浪者队。我最好离开这里。}
### {244}{}{Well, have a good trip, man.}
{244}{}{好吧，祝你旅途愉快，伙计。}

### {250}{}{Ranger Garth got what he deserved. Your friends are avenged.}
{250}{}{流浪者加思得到了他应得的。你的朋友报了仇。}
### {251}{}{Yes... although it won't bring them back. You know, we're actually friends rather by misfortune. A lot happened along the way. We had to rob travelers and small settlements. Only here we felt part of something and were able to live a normal life. Even despite the distrust of the locals. But this ranger ruined everything.}
{251}{}{对尽管这不会让他们回来。你知道，我们实际上是朋友，而不是不幸。一路上发生了很多事情。我们不得不抢劫旅行者和小定居点。只是在这里，我们感觉自己是某种事物的一部分，能够过上正常的生活。尽管当地人不信任。但这个护林员毁了一切。}
### {252}{}{Yeah. It's a pity that this happened.}
{252}{}{是 啊很遗憾发生了这种事。}
### {253}{}{He was not far off in his doubts about your gang.}
{253}{}{他对你那帮人的怀疑不远了。}
### {254}{}{Thanks for everything. Take these cartridges. To be honest, I stole them from the Rangers, it would be fair to give them to you as a reward. And it's time for me to hit the road. There will be no life for me here.}
{254}{}{谢谢你所做的一切。拿着这些子弹。老实说，我从流浪者队偷了它们，把它们作为奖励送给你是公平的。现在是我上路的时候了。我在这里将没有生命。}
### {255}{}{Have a safe journey.}
{255}{}{祝你旅途安全。}
