### {100}{}{Here is a cadet.}
{100}{}{这是一名学员。}
### {101}{}{You see one of the recruits.}
{101}{}{你看到一个新兵。}

### {110}{}{They say it's easier in battle than in training.}
{110}{}{他们说在战斗中比在训练中容易。}
### {111}{}{Captain Agatha is a beast, not a man.}
{111}{}{阿加莎上尉是野兽，不是人。}
### {112}{}{I admire Commander Halford.}
{112}{}{我钦佩哈尔福德指挥官。}
### {113}{}{They say the general has hair all over his body, so he wears an anther.}
{113}{}{据说将军全身都是头发，所以他还戴了一个。}
### {114}{}{I wonder what's out there in California?}
{114}{}{我想知道加州有什么？}
### {115}{}{It would be more like lunch time.}
{115}{}{这更像是午餐时间。}
### {116}{}{After stories about monsters, I don't want to sleep.}
{116}{}{在讲了关于怪物的故事之后，我不想睡觉。}
### {117}{}{These exercises will end someday.}
{117}{}{这些练习总有一天会结束的。}
### {118}{}{I like it here so far.}
{118}{}{到目前为止我喜欢这里。}
### {119}{}{Do you want to become a cadet too?}
{119}{}{你也想成为一名学员吗？}
