### {100}{}{You see Old Rufus.}
{100}{}{你看到老鲁弗斯了。}
### {101}{}{Here is the dam keeper, an unshaven, wiry old man in overalls.}
{101}{}{这是大坝管理员，一个没有刮胡子、穿着工装裤的瘦削老人。}

#The first dialog
### {200}{}{(you see a gray-haired, unshaven man of about fifty; dirty work clothes on him betray his occupation) What? I'm sorry, I've become a little deaf. Work for so many years among these noisy machines and you will also go deaf.}
{200}{}{（你看到一个头发花白、胡子未刮、大约五十岁的男人；他身上的脏工作服暴露了他的职业）什么？对不起，我有点聋了。在这些嘈杂的机器里工作这么多年，你也会失聪。}
### {201}{}{I will keep in mind.}
{201}{}{我会记住的。}
### {202}{}{And who are you? I don't remember you, but I know everyone here. Recruits are usually not allowed to the station, and the quartermaster does business with the caravans. So...}
{202}{}{你是谁？我不记得你了，但我认识这里的每一个人。新兵通常不被允许进入车站，军需官与大篷车做生意。所以}
### {203}{}{I'm here on business.}
{203}{}{我是来出差的。}
### {204}{}{Yeah. On business. Let it be so. The main thing is not to interfere with other things to do.}
{204}{}{是 啊公事顺其自然。最重要的是不要干涉其他事情。}
### {205}{}{What are you doing, old man?}
{205}{}{你在干什么，老人？}
### {206}{}{Then I won't interfere.}
{206}{}{那我就不干涉了。}

#Repeat dialog
### {210}{}{Speak up, what are you mumbling about?}
{210}{}{大声说，你在喃喃自语什么？}
### {211}{}{I say goodbye.}
{211}{}{我说再见。}
### {212}{}{I need to ask something else.}
{212}{}{我需要问别的问题。}
### {213}{}{Another question.}
{213}{}{另一个问题。}

#Questions
### {220}{}{And who are you, exactly?}
{220}{}{你到底是谁？}
### {221}{}{My name is Rufus. I'm the dam keeper. I make sure that nothing falls apart here.}
{221}{}{我的名字叫鲁弗斯。我是大坝管理员。我确保这里没有任何东西会散开。}
### {222}{}{What is your rank, Rufus?}
{222}{}{鲁弗斯，你的军衔是多少？}
### {223}{}{I don't have any rank. I'm doing business here, not currying favor.}
{223}{}{我没有军衔。我在这里做生意，不是为了讨好。}
### {224}{}{How long have you been in office?}
{224}{}{你任职多久了？}
### {225}{}{Let me think, it's been thirty years, probably. No one here counts the year.}
{225}{}{让我想想，可能已经三十年了。这里没有人计算年份。}
### {226}{}{Why did the Rangers settle on this dam?}
{226}{}{游骑兵队为什么要在这个水坝上定居？}
### {227}{}{There are many reasons for this: it is an impregnable fortress for enemies, protection from dust storms, an abundant source of water and endless energy. We can say that it happened historically.}
{227}{}{原因有很多：它是敌人坚不可摧的堡垒，可以抵御沙尘暴，是丰富的水源和无尽的能量。我们可以说它发生在历史上。}
### {228}{}{I'm the dam keeper. I make sure that nothing falls apart here.}
{228}{}{我是大坝管理员。我确保这里没有任何东西会散开。}
### {229}{}{So what are you doing, Rufus?}
{229}{}{那你在干什么，鲁弗斯？}

### {230}{}{Is the aqueduct also part of the power plant?}
{230}{}{输水管道也是发电厂的一部分吗？}
### {232}{}{No, no, the station works without an aqueduct. But the aqueduct would not be able to perform its functions without our dam. However, it still doesn't work anymore.}
{232}{}{不，不，车站没有输水管道。但是，如果没有我们的大坝，输水管道将无法发挥其功能。然而，它仍然不起作用。}
### {231}{}{What's wrong with him?}
{231}{}{他怎么了？}
### {233}{}{Time takes its toll. The pumps have been out of order for a long time and it is impossible to repair them. In addition, the flow of water in the river has decreased. But even if the aqueduct was working, it would be idling. After all, there are no more plantations and settlements on his path that would benefit from this water.}
{233}{}{时间会付出代价。这些水泵坏了很长时间了，无法修理。此外，这条河里的水流量减少了。但是，即使输水管道在工作，它也会空转。毕竟，在他的道路上，没有更多的种植园和定居点可以从这些水中受益。}
### {234}{}{An amazing structure. Who built all this?}
{234}{}{令人惊叹的结构。谁建造了这一切？}
### {235}{}{The people of the past were smart. No one living today is capable of such a thing.}
{235}{}{过去的人很聪明。生活在今天的人没有能力做这样的事。}
### {236}{}{Have you forgotten that they destroyed themselves with their own mind?}
{236}{}{你忘了他们用自己的思想毁灭了自己吗？}
### {237}{}{Yes... But this does not negate the fact that they created an aqueduct to irrigate desert lands.}
{237}{}{对但这并不能否定他们建造了一条灌溉沙漠土地的输水管道的事实。}

#The first quest
### {250}{}{Is there such a risk?}
{250}{}{有这样的风险吗？}
### {251}{}{Oh, this old lady has seen the sights! This controller, for example, does not want to work in any way. And there is nowhere to find a replacement - all the equipment here is unique.}
{251}{}{哦，这位老太太看到这些景色了！例如，这个控制器不希望以任何方式工作。而且找不到替代品——这里所有的设备都是独一无二的。}
### {252}{}{So this thing doesn't work? Maybe I can fix it?}
{252}{}{所以这个东西不起作用？也许我能修好？}
### {253}{}{Where are you going! Here you can hardly do with skills alone. However, you travel a lot, right? If you find parts from electronic equipment, then bring them here, maybe they can be restored with their help.}
{253}{}{你要去哪里！在这里，你很难单凭技能。然而，你经常旅行，对吧？如果你从电子设备中找到零件，那么把它们带到这里，也许可以在他们的帮助下修复。}
### {254}{}{I'll see what I can do.}
{254}{}{我看看我能做些什么。}
### {255}{}{I'm afraid that's really not my profile. But I can find the details.}
{255}{}{恐怕这真的不是我的个人资料。但我能找到细节。}
### {256}{}{That's good. And while you're making a hero out of yourself, I think I'll get busy. No offense.}
{256}{}{这很好。当你把自己塑造成英雄的时候，我想我会很忙的。无意冒犯。}
### {257}{}{Uh, no, I need to know more.}
{257}{}{不，我需要知道更多。}
### {258}{}{Then we'll talk later.}
{258}{}{那我们稍后再谈。}

### {260}{}{Let's talk about that broken controller?}
{260}{}{让我们谈谈那个坏了的控制器？}
### {261}{}{Eh? What are you up to?}
{261}{}{呃？你在干什么？}
### {1261}{}{Eh? What are you up to?}
{1261}{}{呃？你在干什么？}
### {262}{}{Yes, the question is about nothing.}
{262}{}{是的，这个问题毫无意义。}

### {263}{}{What's the problem with getting parts from electronics?}
{263}{}{从电子产品中获取零件有什么问题？}
### {264}{}{Do you think we haven't been looking? All patrols and traders are aware. But there is a rural area in the district, where can electronics come from here? And it's far and expensive to drive from big cities. There are plenty of their customers there.}
{264}{}{你觉得我们没在找吗？所有巡逻队和贸易商都知道。但该地区有一个农村地区，电子产品从哪里来？而且从大城市开车又远又贵。那里有很多他们的顾客。}
### {265}{}{Why do we need this controller?}
{265}{}{为什么我们需要这个控制器？}
### {266}{}{Look at that big thing in the middle of the hall. Inside she has a screw submerged in the water of the Colorado River. It turns and generates electricity... You know what "electricity" is, right?}
{266}{}{看看大厅中间的那个大东西。在里面，她有一个螺丝被淹没在科罗拉多河的水中。它转动并发电。。。你知道什么是“电”，对吧？}
### {267}{}{I think I can guess...}
{267}{}{我想我能猜到。。。}
### {268}{}{Through the controller, the current is directed to the power transformers outside, and then to the power lines. But now nothing works there - just bare and useless wires.}
{268}{}{通过控制器，电流被引导到外部的电力变压器，然后被引导到电力线。但现在那里什么都不管用——只有裸露无用的电线。}
### {269}{}{I need to know more.}
{269}{}{我需要知道更多。}

### {270}{}{I managed to fix the equipment.}
{270}{}{我设法把设备修好了。}
### {271}{}{Keep in mind that Rangers sometimes have problems with humor. Especially on the topic of this dam.}
{271}{}{请记住，流浪者有时会遇到幽默问题。尤其是关于这个大坝的话题。}
### {272}{}{But it works. Take a look.}
{272}{}{但它是有效的。看一看。}

### {273}{}{Well, let's see... Holy heavens, it really worked!}
{273}{}{好吧，让我们看看。。。天哪，它真的起作用了！}
### {274}{}{This job is not for nothing, you know.}
{274}{}{你知道，这份工作不是白干的。}
### {275}{}{Yes... of course. Here's a pack of nuclear batteries for your trouble. If you don't need them, exchange them in the nearest city for something useful.}
{275}{}{对当然这是一包核电池给你。如果你不需要它们，可以在最近的城市兑换一些有用的东西。}
### {276}{}{You're welcome.}
{276}{}{不客气。}
### {277}{}{Rangers don't forget their friends. Here's a pack of nuclear batteries for your trouble. If you don't need them, exchange them in the nearest city for something useful.}
{277}{}{游骑兵不会忘记他们的朋友。这是一包核电池给你。如果你不需要它们，可以在最近的城市兑换一些有用的东西。}
### {278}{}{[Next]}
{278}{}{[下一个]}
### {279}{}{Thank you. It's a pity that you won't be able to replace me in this post when I retire. Now leave me with this baby for a while. She needs extra care.}
{279}{}{非常感谢。很遗憾，我退休后你不能代替我担任这一职务。现在让我和这个孩子在一起一段时间。她需要额外的照顾。}
### {280}{}{Okay, I'll be back later... when you bring this iron to life.}
{280}{}{好的，我稍后回来。。。当你把这个熨斗变成现实的时候。}
### {281}{}{Don't overdo it, old man. The wires can respond to your caresses with an electric current.}
{281}{}{别做得太过火了，老人。电线可以通过电流对你的爱抚做出反应。}
### {282}{}{}
{282}{}{error : string is empty}
### {283}{}{Where can I find parts from electronics?}
{283}{}{在哪里可以找到电子产品的零件？}
### {284}{}{The nearest place I know of is Garage City. Yes, but we have already sent a request there.}
{284}{}{据我所知，最近的地方是车库城。是的，但我们已经向那里发出了请求。}

#The second quest
### {300}{}{How does the station work after repair?}
{300}{}{维修后的加油站是如何工作的？}
### {301}{}{That's great! The repair of the station is not in danger in the coming years. It's a pity that you won't be able to replace me in this post when I retire.}
{301}{}{太棒了！车站的维修在未来几年内没有危险。很遗憾，我退休后你不能代替我担任这一职务。}
### {302}{}{So you're the one manning the dam?}
{302}{}{所以你是大坝的负责人？}
### {303}{}{(sighs) Sometimes I listen to the noise of hydraulic units. Their rusty rotation reminds me of the years I've lived.}
{303}{}{（叹气）有时我会听到液压装置的噪音。他们锈迹斑斑的轮换让我想起了我生活的岁月。}
### {304}{}{So you need a shift.}
{304}{}{所以你需要一个转变。}
### {305}{}{That's right, sir. This station needs a new caretaker - a young man gifted with technical skills, and you won't find such people in our time during the day with fire.}
{305}{}{是的，先生。这个车站需要一个新的看护人——一个有技术天赋的年轻人，在我们这个白天有火灾的时代，你不会找到这样的人。}
### {1305}{}{That's right, ma'am. This station needs a new caretaker - a young man gifted with technical skills, and you won't find such people in our time during the day with fire.}
{1305}{}{没错，夫人。这个车站需要一个新的看护人——一个有技术天赋的年轻人，在我们这个白天有火灾的时代，你不会找到这样的人。}
### {306}{}{Is there anyone in mind?}
{306}{}{有人在想什么吗？}
### {307}{}{The caravaneers told about one such young talent. He lives in Garage City and suffers from a waste of time. I would like to take a look at him and bring him up to replace me. The problem is that the local population treats the Rangers without much sympathy, you know? And you can't just come and pick up the child, you need him to want to.}
{307}{}{商队队员们讲述了这样一位年轻的天才。他住在车库城，浪费时间。我想看看他，让他来代替我。问题是当地人对流浪者队没有太多同情，你知道吗？你不能只是来接孩子，你需要他愿意。}
### {308}{}{I'll take the job.}
{308}{}{我会接受这份工作。}
### {309}{}{Whoever wants something in that dump, and I'll bring you a kid.}
{309}{}{谁想在垃圾堆里放点什么，我就给你带个孩子。}
### {310}{}{Well, it looks like you'll have to look for a replacement elsewhere. Bye, old man.}
{310}{}{看来你得在别处找个替代者了。再见，老人。}
### {311}{}{What a determination! It distinguishes greens from old people. Agreed. I will be waiting for your return.}
{311}{}{多么坚定的决心！它把绿色人种和老年人区分开来。同意。我会等你回来的。}
### {312}{}{Later.}
{312}{}{后来}

### {320}{}{Bad news - that guy from Garage City died on the way.}
{320}{}{坏消息——车库城的那个家伙在路上死了。}
### {321}{}{Sorry for the guy, he would be extremely useful to the Rangers in the future... Well, we'll have to work with local guys, although there is not a single one among them who is passionate about technology. I don't have any more assignments for you either. Thank you for your service.}
{321}{}{对不起这个家伙，他将来会对流浪者队非常有用。。。好吧，我们将不得不与当地人合作，尽管他们中没有一个人对技术充满热情。我也没有更多的任务给你了。感谢您的服务。}
### {322}{}{Will I get nothing for my efforts?}
{322}{}{我的努力会一无所获吗？}
### {323}{}{Your labors were useless. Go somewhere already, don't interfere with work.}
{323}{}{你的劳动毫无用处。已经去某个地方了，不要干扰工作。}
### {324}{}{That's it, then...}
{324}{}{就这样，那么。。。}

### {330}{}{This is the gifted guy you were looking for.}
{330}{}{这就是你要找的那个有天赋的人。}
### {331}{}{Hello, son! Here, at the Rangers, you will surely like it. I can see it in your eyes. But first you need to wash a little...}
{331}{}{你好，儿子！在这里，在流浪者队，你一定会喜欢的。我能从你的眼睛里看到。但首先你需要洗一点。。。}
### {332}{}{Ahem...}
{332}{}{啊。。。}
### {333}{}{...And you've done a great service to the Rangers by bringing this guy in. Look to the quartermaster, let him pick up a reward for you.}
{333}{}{……你把这个家伙带进来为流浪者队做了很大的贡献。看看四分卫，让他为你拿奖励。}
### {1333}{}{...And you've done a great service to the Rangers by bringing this guy in. Look to the quartermaster, let him pick up a reward for you.}
{1333}{}{……你把这个家伙带进来为流浪者队做了很大的贡献。看看四分卫，让他为你拿奖励。}
### {334}{}{Great, wait for me, reward! I'm on my way.}
{334}{}{太好了，等我，奖励！我在路上。}
