### {100}{}{You see a farmer.}
{100}{}{你看到一个农民。}
### {101}{}{Here is a typical farmer, busy with his usual peaceful business.}
{101}{}{这是一个典型的农民，忙于他平常平静的生意。}

#The first dialog
### {200}{}{Get out of here and don't come back! There is nothing to spoil the lives of peaceful people. And as soon as the earth tolerates you...}
{200}{}{离开这里，别回来！没有什么可以破坏和平人民的生活。只要地球能容忍你。。。}
### {201}{}{Don't get excited, old man.}
{201}{}{别激动，老头。}
### {202}{}{I won't cause you any problems.}
{202}{}{我不会给你带来任何问题。}

### {210}{}{(Here is a farmer in a plaid shirt, worn work pants and a holey hat; when you get closer, he grabs a rake in his hands and, squinting, looks you up and down; it seems that he is not a particular fan of long conversations.) }
{210}{}{（这里有一个农民，穿着格子衬衫，穿着破旧的工作裤，戴着一顶破洞的帽子；当你走近时，他手里拿着一把耙子，眯着眼睛上下打量着你；他似乎不是一个特别喜欢长时间交谈的人。）}
### {211}{}{I'm sorry to bother you. I'm looking for the nearest settlement.}
{211}{}{很抱歉打扰你。我在找最近的定居点。}
### {212}{}{Hey, old man, where's the nearest bar? I urgently need a drink.}
{212}{}{嘿，老头，最近的酒吧在哪里？我急需一杯饮料。}
### {213}{}{For the first time in these parts? Well, welcome to the Ranger lands. If you need Vault or protection, go higher up the road - there the rangers have set up their citadel, right on the old dam.}
{213}{}{第一次在这些地方？好吧，欢迎来到游骑兵之地。如果你需要保险库或保护，可以走得更高一点——护林员已经在那里建立了他们的堡垒，就在旧水坝上。}
### {214}{}{Can I ask a few questions?}
{214}{}{我能问几个问题吗？}
### {215}{}{Thanks, I'll head straight there.}
{215}{}{谢谢，我会直接去那里。}
### {216}{}{I doubt you'll find what you're looking for here. There's a ranger base up the road, right on the old dam. And they won't like it if you show up there with the same question.}
{216}{}{我怀疑你会在这里找到你想要的东西。路上有一个护林员基地，就在老水坝上。如果你带着同样的问题出现在那里，他们不会喜欢的。}

### {220}{}{Well, what do you say?}
{220}{}{好吧，你怎么说？}
### {221}{}{Don't pull the iguana by the tail, ask.}
{221}{}{不要拉鬣蜥的尾巴，问问。}
### {222}{}{How interesting. Tell me something else?}
{222}{}{真有趣。告诉我别的什么？}
### {223}{}{Looks like you've settled in pretty well. Let's talk about something else.}
{223}{}{看起来你已经适应得很好了。让我们谈谈其他事情。}
### {224}{}{I'm sorry, but I have to get ready for the road..}
{224}{}{对不起，我得准备上路了。。}
### {225}{}{}
{225}{}{error : string is empty}
### {226}{}{Just to say hello. Have a nice day.}
{226}{}{只是打个招呼。祝你今天愉快。}

### {227}{}{You again? Hmm... your eyes are cloudy. Like those crazy sectarians from the east. Do you by any chance worship old things and radioactivity signs? If so, keep in mind that the Rangers do not like such.}
{227}{}{你又来了？嗯…你的眼睛有点模糊。就像那些来自东方的疯狂宗派主义者。你有没有崇拜古老的东西和放射性标志？如果是这样的话，请记住流浪者队不喜欢这样。}
### {228}{}{Thanks for the warning, but I'm not one of those who worship radioactivity.}
{228}{}{谢谢你的警告，但我不是那种崇拜放射性的人。}
### {229}{}{Don't laugh at the true teaching, you insignificant atom! Otherwise I'll laugh at your grave.}
{229}{}{不要嘲笑真正的教学，你这个微不足道的原子！否则我会嘲笑你的坟墓。}

#Questions
### {230}{}{Tell us about yourself and your farm.}
{230}{}{告诉我们你自己和你的农场。}
### {231}{}{What is there to tell? We grow crops as much as we can, and the rangers protect us from enemies and help us in any way they can.}
{231}{}{有什么好说的？我们尽可能多地种植作物，护林员保护我们免受敌人的攻击，并尽其所能帮助我们。}
### {232}{}{How long have you lived here?}
{232}{}{你在这里住多久了？}
### {233}{}{We have already experienced more than a dozen winters in these lands. If it wasn't for the Rangers, no one would have lasted this long here.}
{233}{}{我们已经在这些土地上经历了十几个冬天。如果不是流浪者队，没有人会在这里呆这么久。}
### {234}{}{Who else lives in these parts besides you?}
{234}{}{除了你，还有谁住在这些地方？}
### {235}{}{Up the road, the Rangers have set up their citadel on an old dam. This is the largest settlement, and scattered around it are individual families, farms, outposts and seasonal hunting camps.}
{235}{}{沿着这条路，游骑兵队在一座旧水坝上建立了他们的堡垒。这是最大的定居点，周围散布着个体家庭、农场、前哨基地和季节性狩猎营地。}
### {236}{}{And who lives in the shack opposite?}
{236}{}{谁住在对面的棚屋里？}
### {237}{}{After the former owner died of radscorpion poison, no one lives there anymore.}
{237}{}{在前主人死于毒蝎后，再也没有人住在那里了。}
### {238}{}{Why are crops drying up?}
{238}{}{为什么庄稼都干了？}
### {239}{}{Because the drought does not allow the seedlings to grow. Things would be better if we had an irrigation system working.}
{239}{}{因为干旱不允许幼苗生长。如果我们有一个灌溉系统，情况会更好。}

### {240}{}{Is it safe here?}
{240}{}{这里安全吗？}
### {241}{}{Nowadays, everywhere is unsafe. But compared to other places I've heard of, it's probably the most peaceful. There are almost no bandits here - they are scared off by rangers. Of the mutants, only radscorpions, that's with them there are problems. Especially during the dry season when they migrate from the south.}
{241}{}{如今，到处都不安全。但与我听说过的其他地方相比，这里可能是最宁静的。这里几乎没有土匪——他们被护林员吓跑了。在突变体中，只有辐射蝎子，这就是它们存在的问题。尤其是在旱季，当它们从南方迁徙时。}
### {242}{}{Tell me about the radscorpions.}
{242}{}{告诉我关于雷蝎子的事。}
### {243}{}{Huge creatures in impenetrable shells. The further south, into the desert, the bigger and more dangerous they are. In especially hot seasons, they move here, then it's better not to stick out on the street. Especially at night, when their hunting instinct wakes up.}
{243}{}{巨大的生物，外壳无法穿透。越往南，进入沙漠，它们就越大，越危险。在特别炎热的季节，他们会搬到这里，所以最好不要在街上闲逛。尤其是在晚上，当它们的狩猎本能苏醒时。}
### {244}{}{Do you know their weaknesses?}
{244}{}{你知道他们的弱点吗？}
### {245}{}{Well, the most tender place they have is the abdomen, but it's very difficult to get there. You can try to break the paws, and then finish off the creature from afar. But the most reliable remedy against them is fire. Set fire to the creature - and this torch will flare brighter than the sun.}
{245}{}{嗯，他们最脆弱的地方是腹部，但很难到达那里。你可以试着折断爪子，然后从远处干掉这个生物。但对他们来说，最可靠的补救办法是开火。点燃这个生物——这个火炬会比太阳更亮。}
### {246}{}{Looks like there was a massacre on the road?}
{246}{}{看起来路上发生了大屠杀？}
### {247}{}{Yeah. The Rangers have been tracking this spy all over the valley for several days. And he ended up right in the shack across from us. Can you imagine? Now the enemies will know who is the owner of these lands!}
{247}{}{是 啊几天来，游骑兵队一直在山谷里到处追踪这个间谍。他就在我们对面的棚屋里，你能想象吗？现在敌人将知道谁是这些土地的所有者！}

### {250}{}{Tell me about these rangers.}
{250}{}{告诉我这些护林员的情况。}
### {251}{}{Aren't you one of them? Then I won't tell you anything new. Ask around the other rangers in the citadel.}
{251}{}{你不是他们中的一员吗？那我就不告诉你什么新鲜事了。问问城堡里的其他护林员。}
### {252}{}{And yet I have other questions for you.}
{252}{}{但我还有其他问题要问你。}
### {253}{}{Then enough of this useless talk.}
{253}{}{那么这些无用的谈话就够了。}
### {254}{}{I'll tell you what - they are the protectors and guardians of these lands. The only ones who are ready to give their lives for justice and the law in our harsh world.}
{254}{}{我告诉你，他们是这些土地的保护者和守护者。在我们这个严酷的世界里，只有那些愿意为正义和法律献出生命的人。}
### {255}{}{So they are your patrons?}
{255}{}{所以他们是你的赞助人？}
### {256}{}{Exactly. We pay them a tax on our crops, and they protect us from bandits and mutants. This is if you explain it in a very simple way.}
{256}{}{确切地我们向他们支付作物税，他们保护我们免受土匪和变种人的袭击。如果你用一种非常简单的方式来解释的话。}
### {257}{}{And if you don't want to share with the Rangers?}
{257}{}{如果你不想和流浪者队分享？}
### {258}{}{The wastelands are huge. If you don't like rangers, go somewhere else. But I'll tell you what - they're better than anyone else.}
{258}{}{荒地很大。如果你不喜欢护林员，就去别的地方吧。但我告诉你，他们比任何人都好。}
### {259}{}{I feel like you're not telling me something. How are things really going?}
{259}{}{我觉得你没有告诉我什么。事情到底怎么样？}
### {260}{}{Just like I said. Rangers bring justice and justice to the wasteland. And we pay a tax for it. That's fair, isn't it?}
{260}{}{就像我说的。游骑兵为荒原伸张正义。我们为此纳税。这很公平，不是吗？}
### {261}{}{Hmm...}
{261}{}{嗯。。。}
### {262}{}{The Rangers protect us, but they drink blood afterwards. To give them a part of your harvest, which has been grown so hard, is like giving away a child. But if there were no rangers, there would be bandits who would take everything away. You have to pay, there is no choice anyway.}
{262}{}{游骑兵队保护我们，但他们事后喝了血。把你辛勤种植的收成的一部分送给他们，就像送了一个孩子。但如果没有护林员，就会有土匪夺走一切。你必须付钱，别无选择。}
### {263}{}{That's how it is...}
{263}{}{事情就是这样。。。}
### {264}{}{I need to get to the leader of the Rangers. How to do it?}
{264}{}{我需要去找游骑兵队的队长。怎么做？}
### {265}{}{Well, they won't let you go to the general so easily. He usually sits inside the dam, and the entrance there is securely guarded. If you want to get inside, you'll have to find a really serious reason.}
{265}{}{好吧，他们不会让你这么容易就去找将军的。他通常坐在大坝里，那里的入口有安全的守卫。如果你想进去，你必须找到一个真正严肃的理由。}

### {266}{}{Garage City residents are in dire need of food.}
{266}{}{车库城的居民急需食物。}
### {267}{}{Isn't this a scavenger settlement that the Rangers had some kind of trouble with? No wonder they brought themselves to such a state.}
{267}{}{这不是流浪者队遇到麻烦的拾荒者定居点吗？难怪他们会把自己带到这样的境地。}
### {268}{}{You could trade your crops with them in exchange for machinery and repair services.}
{268}{}{你可以用你的作物和他们交换机械和维修服务。}
### {269}{}{Right. Perhaps the rest of the farmers would also be happy to get some equipment that is useful on the farm. I think the Rangers will have their own interest in this business. Let's see what happens.}
{269}{}{正确的也许其他农民也会很乐意得到一些对农场有用的设备。我认为流浪者队会对这项业务感兴趣。让我们看看会发生什么。}
### {270}{}{Great, I'll give the residents of Garage City your consent.}
{270}{}{太好了，我会同意车库城的居民。}

# Give water
### {288}{}{Get out of here in a good way.}
{288}{}{以一种好的方式离开这里。}
### {289}{}{Whatever you say. I would not like to create a conflict from scratch.}
{289}{}{不管你说什么。我不想从头开始制造冲突。}
### {290}{}{Maybe share some clean water?}
{290}{}{也许共享一些干净的水？}
### {291}{}{Why would we share supplies with you? What if you're an enemy of the Rangers or a runaway bandit? Show yourself first, and then we'll see.}
{291}{}{我们为什么要和你分享物资？如果你是游骑兵队的敌人或逃跑的土匪怎么办？先展示自己，然后我们再看。}
### {292}{}{Fair. But at least you can count on answers?}
{292}{}{公平的但至少你能指望答案？}
### {293}{}{I'll remember it to you as soon as the opportunity presents itself...}
{293}{}{机会一出现，我就会记住。。。}
### {294}{}{Here, drink as much as you want. Don't squeeze, Ranger, it's not a pity for you to have water.}
{294}{}{给，你想喝多少就喝多少。别挤，流浪者，你有水并不可惜。}
### {295}{}{Thank you...}
{295}{}{非常感谢。}
### {296}{}{I am not one of the bandits, on the contrary - my caravan was looted.}
{296}{}{恰恰相反，我不是土匪之一——我的商队被洗劫一空。}
### {297}{}{It must have been hard to walk through the desert? Here, have a little drink. But we won't give any more, ask the Rangers.}
{297}{}{穿过沙漠一定很艰难吧？来，喝点什么。但我们不会再付出了，问问流浪者队吧。}
### {298}{}{Come on, don't spare a couple of sips for a kind guest.}
{298}{}{来吧，别为好心的客人多喝几口。}
### {1298}{}{Come on, don't spare a couple of sips for a kind guest.}
{1298}{}{来吧，别为好心的客人多喝几口。}
### {299}{}{Hmm, it's not a pity for you. Here, hold it tight.}
{299}{}{嗯，这对你来说并不可惜。给，抓紧。}

#Tank repair
### {300}{}{Can't the Rangers fix the water tank?}
{300}{}{游骑兵队不能修理水箱吗？}
### {301}{}{Rangers, of course, are cool guys, but they don't have anything to do with technology. You won't find a person in the whole settlement who would help fix the water tank. So we have to work with our hands, and this is especially difficult at our age.}
{301}{}{流浪者当然是很酷的家伙，但他们与技术无关。在整个定居点里，你找不到一个人来帮忙修理水箱。所以我们必须用双手工作，这在我们这个年纪尤其困难。}
### {302}{}{I can fix it.}
{302}{}{我能修好。}
### {303}{}{Really? That would be a really useful thing! If you manage, we'll share food and water, we have nothing else to repay you with.}
{303}{}{真正地那将是一件非常有用的事情！如果你成功了，我们将分享食物和水，我们没有其他东西可以回报你。}
### {304}{}{I'll think about it.}
{304}{}{我会考虑的。}
### {305}{}{The water tank is no longer leaking.}
{305}{}{水箱不再漏水了。}
### {306}{}{It's true... Yes, you are a real master! Listen, you should stop by the Rangers, they need people like you.}
{306}{}{这是真的。。。是的，你是个真正的大师！听着，你应该去游骑兵队，他们需要像你这样的人。}
### {1306}{}{It's true... Yes, you are a real craftswoman! Listen, you should stop by the Rangers, they need people like you.}
{1306}{}{这是真的。。。是的，你真是个巧妇！听着，你应该去游骑兵队，他们需要像你这样的人。}
### {307}{}{Ahem. Actually, I was hoping for a reward.}
{307}{}{嗯。事实上，我希望得到奖励。}
### {1307}{}{Ahem. Actually, I was hoping for a reward.}
{1307}{}{嗯。事实上，我希望得到奖励。}
### {308}{}{Well, here's what I can give you for it - clean water and some mutafruits. I'm sorry it's so small, but because of the drought and this leaky tank, the harvest is barely enough.}
{308}{}{好吧，这是我能给你的——干净的水和一些诱变剂。很抱歉它太小了，但由于干旱和水箱漏水，收成几乎不够。}
### {309}{}{And thanks for that.}
{309}{}{谢谢你。}
### {310}{}{Take care of yourself.}
{310}{}{照顾好自己。}
### {311}{}{Goodbye.}
{311}{}{再见}
### {312}{}{I didn't work for scraps. Give me the rest of the supplies, otherwise I'll blow up the damn tank.}
{312}{}{我不是为残羹剩饭而工作的。把剩下的补给品给我，否则我会炸掉那该死的坦克。}
### {1312}{}{I didn't work for scraps. Give me the rest of the supplies, otherwise I'll blow up the damn tank.}
{1312}{}{我不是为残羹剩饭而工作的。把剩下的补给品给我，否则我会炸掉那该死的坦克。}
### {313}{}{Okay, don't get too excited, there will be more food and water for you. But that's all we have left. Take it and leave in peace.}
{313}{}{好吧，不要太兴奋，会有更多的食物和水给你。但我们只剩下这些了。拿着它，平静地离开。}
### {314}{}{That's it, old man.}
{314}{}{就是这样，老人。}
### {315}{}{Good. And no reward needed.}
{315}{}{好的而且不需要任何奖励。}
### {316}{}{Are you really not taking anything in return? It's strange, but I'm very grateful to you. Take care of yourself.}
{316}{}{你真的不拿任何回报吗？这很奇怪，但我非常感谢你。照顾好自己。}
### {317}{}{Goodbye.}
{317}{}{再见}

#Dog search
### {350}{}{Sounds like something bad happened.}
{350}{}{听起来好像发生了什么坏事。}
### {351}{}{That's right. We have a missing dog and someone is clearly eating our crops. I think it's radscorpions. If you come across dog remains, let me know.}
{351}{}{没错。我们有一只失踪的狗，显然有人在吃我们的庄稼。我想是蝎子。若你们发现狗的遗骸，请告诉我。}
### {352}{}{Absolutely.}
{352}{}{绝对地}
### {353}{}{I found the remains of your dog. She was killed.}
{353}{}{我发现了你的狗的残骸。她被杀了。}
### {1353}{}{I found the remains of your dog. She was killed.}
{1353}{}{我发现了你的狗的残骸。她被杀了。}
### {354}{}{What are you saying?! Who needed to do this?!}
{354}{}{你在说什么？！谁需要这样做？！}
### {355}{}{It was a bandit who escaped from the Rangers. The dog prevented him from stealing food from your beds.}
{355}{}{是一个土匪从游骑兵队逃走了。狗阻止他从你床上偷食物。}
### {356}{}{I don't know yet. Maybe something will clear up later.}
{356}{}{我还不知道。也许稍后会有好转。}
### {357}{}{So that's who devastated our farm! If there is a bandit in the neighborhood, then it's bad. Listen, go to the Rangers and tell them about it, but soon!}
{357}{}{那就是破坏我们农场的人！如果附近有土匪，那就不好了。听着，去游骑兵队告诉他们这件事，但很快！}
### {358}{}{I'm actually going the other way. You'll have to figure it out on your own.}
{358}{}{实际上我要走另一条路。你得自己想办法。}
### {359}{}{I will definitely let you know when I get there.}
{359}{}{我到那里的时候一定会告诉你的。}
### {360}{}{Relax - that bandit won't bother you anymore.}
{360}{}{别紧张，那个土匪不会再打扰你了。}
