### {100}{}{Here is a ranger.}
{100}{}{这是一个护林员。}
### {101}{}{You see a ranger in desert clothes. He shows you a greeting sign.}
{101}{}{你看到一个穿着沙漠服装的护林员。他给你看一个问候语。}
### {102}{}{Yes, I'll need it.}
{102}{}{是的，我需要它。}

#The first dialog
### {200}{}{Hey, traveler, slow down! You don't often meet people in these parts. Can you tell me what you're doing here?}
{200}{}{嘿，旅行家，慢一点！在这些地方你不常遇到人。你能告诉我你在这里做什么吗？}
### {1200}{}{Hey, traveler, slow down! You don't often meet people in these parts. Can you tell me what you're doing here?}
{1200}{}{嘿，旅行家，慢一点！在这些地方你不常遇到人。你能告诉我你在这里做什么吗？}
### {201}{}{I'm running an errand for Captain Helford.}
{201}{}{我在为赫尔福德上尉跑腿。}
### {202}{}{This is not surprising. The captain has long said that he does not have enough people. Then be careful, this place is not safe.}
{202}{}{这并不奇怪。队长早就说过他人手不够。那就小心点，这个地方不安全。}
### {203}{}{The Ranger cartographer asked me to take measurements.}
{203}{}{游骑兵制图师让我测量一下。}
### {204}{}{It was high time to do it. But now it's too dangerous here to do peaceful cartography.}
{204}{}{这是时候做了。但现在在这里做和平的制图太危险了。}
### {205}{}{I'm here in search of ancient artifacts.}
{205}{}{我在这里寻找古代文物。}
### {206}{}{A relic finder, right? The road has brought you far in search of profit. But this is not the best place to look, believe me. Everything of value has long been lost, and it has become unsafe to be here.}
{206}{}{文物发掘者，对吧？这条路把你带到很远的地方寻找利润。但相信我，这不是最好的地方。所有有价值的东西都早已丢失，在这里变得不安全。}
### {207}{}{It's none of your business.}
{207}{}{这不关你的事。}
### {208}{}{Okay. Let's say. But keep in mind that these ruins are too dangerous. If you get into trouble, don't ask me or the other rangers for help.}
{208}{}{可以比方说。但请记住，这些废墟太危险了。如果你遇到麻烦，不要向我或其他护林员寻求帮助。}
### {209}{}{Why is this place dangerous?}
{209}{}{为什么这个地方很危险？}
### {210}{}{Recently, the radioactive background has increased here. The locals have gone mad and are now attacking anyone they meet. Be careful. I warned you, and then do as you want.}
{210}{}{最近，这里的放射性背景增加了。当地人已经疯了，现在正在攻击他们遇到的任何人。小心。我警告过你，然后你想怎么做就怎么做。}
### {211}{}{Thanks for the warning.}
{211}{}{谢谢你的警告。}
### {212}{}{You're just trying to scare me. Better give way.}
{212}{}{你只是想吓唬我，还是让开吧。}
### {213}{}{I'll figure it out. Happily.}
{213}{}{我会想清楚的。高兴地}

#Repeat dialog
### {220}{}{Yes?}
{220}{}{对}
### {221}{}{Bye.}
{221}{}{再见}
### {222}{}{Let's go back a bit.}
{222}{}{让我们回到过去。}
### {223}{}{It looks like it was the last one. God rest their souls.}
{223}{}{它看起来像是最后一个。上帝保佑他们的灵魂安息。}

### {230}{}{Are there any residents left here?}
{230}{}{这里还有居民吗？}
### {231}{}{I'm here at the request of Commander Helford. Where is the refugee camp located?}
{231}{}{我是应赫尔福德司令的要求来的。难民营在哪里？}
### {232}{}{You can't call the locals people anymore. They are distraught, do not understand speech and attack anyone they meet. Their camp is located in a trailer park opposite a gas station. Go down the street and then turn left.}
{232}{}{你不能再给当地人打电话了。他们悲痛欲绝，不懂言语，并攻击他们遇到的任何人。他们的营地位于加油站对面的一个拖车公园里。沿着这条街走，然后向左拐。}
### {233}{}{Who are they?}
{233}{}{他们是谁？}
### {234}{}{Ordinary refugees from the east. They came here hoping to start a new life, but they found only suffering. If you meet them, it's better to shoot them right away so that they don't suffer and don't create problems for others.}
{234}{}{来自东方的普通难民。他们来到这里希望开始新的生活，但他们发现只有痛苦。如果你遇到他们，最好马上射杀他们，这样他们就不会受苦，也不会给别人制造麻烦。}
### {235}{}{Why are they mad?}
{235}{}{他们为什么生气？}
### {236}{}{I do not know, but I think it's because of radiation.}
{236}{}{我不知道，但我认为是因为辐射。}
### {237}{}{You can't call the locals people anymore. They are distraught, do not understand speech and attack anyone they meet. Their camp is in this trailer park.}
{237}{}{你不能再给当地人打电话了。他们悲痛欲绝，不懂言语，并攻击他们遇到的任何人。他们的营地在这个拖车公园里。}

### {240}{}{Why is it radioactive here?}
{240}{}{为什么这里有放射性？}
### {241}{}{I'd like to know, too. After the Great War, there was a high radiation background due to winds from California. But over time, the radiation level returned to normal. Surely the locals did their best. Maybe they found something they shouldn't have found.}
{241}{}{我也想知道。大战后，由于来自加利福尼亚州的风，出现了高辐射背景。但随着时间的推移，辐射水平恢复了正常。当然，当地人已经尽力了。也许他们找到了不该找到的东西。}

### {250}{}{Who are you?}
{250}{}{你是谁？}
### {251}{}{I'm a ranger. My task is to set up radiation warnings and, if possible, shoot all the Distraught. After that I will return to my service in the east.}
{251}{}{我是一名护林员。我的任务是设置辐射警报，如果可能的话，射杀所有心烦意乱的人。之后，我将返回东部服役。}
### {252}{}{Are you alone here?}
{252}{}{你一个人在这里吗？}
### {253}{}{Yes. Many rangers were sent to the east, and there were rare patrols in this direction. However, it has always been sparsely populated here.}
{253}{}{对许多护林员被派往东部，很少有人在这个方向巡逻。然而，这里一直人烟稀少。}
### {254}{}{I need an escort. Will you come with me?}
{254}{}{我需要护送。你愿意和我一起去吗？}
### {255}{}{It's too dangerous. The two of us attract more attention, and my skills are more useful in the wastelands than in the city limits.}
{255}{}{太危险了。我们两个吸引了更多的注意力，我的技能在荒原上比在城市里更有用。}
### {256}{}{I won't get out alive without your protection.}
{256}{}{没有你的保护，我活不出来。}
### {257}{}{I'm a ranger too. Together it will be easier for us to get rid of the Distraught.}
{257}{}{我也是一名护林员。我们一起会更容易摆脱烦恼。}
### {258}{}{I don't protect people like you.}
{258}{}{我不保护像你这样的人。}
### {259}{}{You speak as if you see me as a fugitive criminal.}
{259}{}{你说话好像把我看成一个在逃的罪犯。}
### {260}{}{Just leave these ruins if you don't have the strength to fight.}
{260}{}{如果你没有战斗的力量，就离开这些废墟吧。}
### {261}{}{Not before I get all the necessary answers from you.}
{261}{}{在我从你那里得到所有必要的答案之前。}
### {262}{}{That's exactly what I'll do. Bye.}
{262}{}{那正是我要做的。再见。}
### {263}{}{(incredulous) Okay But don't forget about radiation.}
{263}{}{（难以置信）好吧，但别忘了辐射。}
### {264}{}{Go ahead!}
{264}{}{着手}
### {265}{}{Come on.}
{265}{}{来吧}
