### {100}{}{You see the computer.}
{100}{}{你看到电脑了。}
### {101}{}{Here is a computer for controlling the ZAX logic module.}
{101}{}{这是一台用于控制ZAX逻辑模块的计算机。}
### {102}{}{Curiosity alone is not enough here.}
{102}{}{这里光有好奇心是不够的。}
### {103}{}{The operation is impossible - the computer has lost contact with the ZAX neural system.}
{103}{}{操作是不可能的——计算机已经失去了与ZAX神经系统的联系。}
### {104}{}{The operation is impossible - the computer has lost contact with the ZAX neural system.}
{104}{}{操作是不可能的——计算机已经失去了与ZAX神经系统的联系。}
### {105}{}{The ZAX program update was successful.}
{105}{}{ZAX程序更新成功。}
