### {100}{}{This is Eden.}
{100}{}{这是伊甸园。}
### {101}{}{Here is a boy named Eden. He seems wild and scared.}
{101}{}{这是一个叫伊登的男孩。他看起来狂野而害怕。}
### {102}{}{*Silently nods his head*}
{102}{}{*默默地点头*}
### {103}{}{Eden returned to the Villa.}
{103}{}{伊甸园回到了别墅。}

### {200}{}{(Looks at you fearfully, without uttering a word)}
{200}{}{（恐惧地看着你，一言不发）}
### {201}{}{Hey, don't you know it's dangerous to walk alone here?}
{201}{}{嘿，你不知道一个人走在这里很危险吗？}
### {202}{}{(Continues to stare at you in fright)}
{202}{}{（继续惊恐地盯着你看）}
### {203}{}{Look, it's hard for everyone right now. But together we will survive everything. Come on - let's go to the village.}
{203}{}{听着，现在对每个人来说都很难。但我们会一起度过一切。来吧，我们去村里吧。}
### {204}{}{Don't worry, I'll take care of you.}
{204}{}{别担心，我会照顾你的。}
### {205}{}{Then stand here and get dirty, you pussy. I'm leaving.}
{205}{}{那就站在这里弄脏，你这个婊子养的。我要走了。}
### {206}{}{It's too dangerous here. Let's go back to the Villa?}
{206}{}{这里太危险了。我们回别墅去吧？}
### {207}{}{Hey, look, I have a juicy mutafruit. You must be hungry, right?}
{207}{}{嘿，看，我有一个多汁的变种水果。你一定饿了吧？}
### {208}{}{Stay here, I'll be back soon.}
{208}{}{呆在这里，我很快就会回来。}
### {209}{}{Oops, I think it fell out of my pocket. Stay here, I'll be back soon.}
{209}{}{哎呀，我想它是从我口袋里掉出来的。呆在这里，我很快就会回来。}

### {210}{}{(Silently shakes his head and backs away from you)}
{210}{}{（他默默地摇摇头，背对你）}
### {211}{}{Ah! (Looks like Eden is ready to follow you now)}
{211}{}{啊！（看起来伊甸园已经准备好跟随你了）}
### {212}{}{Great, follow me.}
{212}{}{太好了，跟我来。}
