### {100}{}{This is your madre.}
{100}{}{这是你的疯子。}
### {101}{}{You see a woman you know well, moreover, your mother.}
{101}{}{你看到一个你很熟悉的女人，还有你的母亲。}
### {102}{}{Goodbye, Mother. Now I'll take care of myself on my own.}
{102}{}{再见，妈妈。现在我要自己照顾自己了。}
### {103}{}{Your Madre has returned to the Villa.}
{103}{}{你的马德雷已经回到了别墅。}
### {104}{}{Here's another one! Get out of there! Stop scaring people.}
{104}{}{这是另一个！滚出去！别再吓唬人了。}
### {105}{}{}
{105}{}{error : string is empty}
### {106}{}{ And here is our hero. We love you.}
{106}{}{这是我们的英雄。我们爱你。}
### {1106}{}{And here is our heroine. We love you.}
{1106}{}{这是我们的女主角。我们爱你。}
### {107}{}{Please leave and don't come back. No one here wants to hurt you.}
{107}{}{请离开，不要回来。这里没有人想伤害你。}
### {108}{}{Be careful. We love you.}
{108}{}{小心。我们爱你。}

#The first dialog
### {200}{}{And here is our hero. The whole Villa owes you after our rescue. It was a real feat.}
{200}{}{这是我们的英雄。经过我们的营救，整个别墅都欠你。这是一个真正的壮举。}
### {1200}{}{And here is our heroine. The whole Villa owes you after our rescue. It was a real feat.}
{1200}{}{这是我们的女主角。经过我们的营救，整个别墅都欠你。这是一个真正的壮举。}
### {201}{}{How did you get to the Villa?}
{201}{}{你是怎么到别墅的？}
### {202}{}{The path was not close. And very difficult. We were saved by unity and cohesion, in this the inhabitants of the Villa have always differed from the savages.}
{202}{}{路径不近。而且非常困难。我们被团结和凝聚力拯救了，在这一点上，别墅的居民总是与野蛮人不同。}
### {203}{}{Perhaps.}
{203}{}{可能}
### {204}{}{Oh my God! What have these damned wastelands done to you? Your skin feels like... burned! How are you doing? Can you talk? Ugh, I don't know what to think. It looks like you're going to stay in this skin forever. I am so sorry. But don't worry - we will definitely find a cure for this disease.}
{204}{}{天啊！这些该死的荒原对你做了什么？你的皮肤感觉。。。烧了！你好吗？你会说话吗？啊，我不知道该怎么想。看起来你将永远保持这种皮肤。我很抱歉。但别担心，我们一定会找到治愈这种疾病的方法。}
### {205}{}{Oh that, I'm already starting to get used to my new body.}
{205}{}{哦，我已经开始习惯我的新身体了。}

#Second dialog
### {210}{}{What can I do for you?}
{210}{}{我能为你做什么？}
### {211}{}{Oh, nothing special.}
{211}{}{哦，没什么特别的。}
### {212}{}{Did something happen? Why aren't you sleeping?}
{212}{}{发生什么事了吗？你为什么不睡觉？}

### {220}{}{Can I ask a delicate question?}
{220}{}{我能问一个微妙的问题吗？}
### {221}{}{Of course, because I can be honest with you?}
{221}{}{当然，因为我可以对你说实话？}
### {222}{}{Why was the rest of the world hidden from the residents of the Villa? I managed to visit various unusual places, and it was... an unexpected experience.}
{222}{}{为什么世界的其他地方对别墅的居民隐藏起来？我设法参观了各种不寻常的地方，这是。。。意想不到的经历。}
### {223}{}{Ah! Look at the Villa. When the Founder brought people here, it was a lifeless wasteland. Our ancestors invested their whole lives so that at least something edible could grow here. They succeeded only thanks to their faith in the precepts of the Founder: work for the good of the community, share your gains with everyone and do not let strangers in.}
{223}{}{啊！看看别墅。当创始人把人们带到这里时，这里是一片死气沉沉的荒地。我们的祖先投入了他们的一生，这样至少可以在这里种植一些可食用的东西。他们的成功归功于他们对创始人戒律的信仰：为社区的利益工作，与每个人分享你的收获，不要让陌生人进来。}
### {224}{}{[Listen]}
{224}{}{[听]}
### {225}{}{Tell me, are there many places outside the Villa where gardens also bloom and peace reigns? In this case, we have nothing to learn from the "rest of the world".}
{225}{}{告诉我，别墅外有没有很多地方花园也盛开，和平盛行？在这种情况下，我们没有什么可以向“世界其他地方”学习的。}
### {226}{}{But the world is changing. Do you think the Villa doesn't need a change?}
{226}{}{但世界正在改变。你认为维拉不需要改变吗？}
### {227}{}{What changes can there be? Grow the harvest and share with everyone - that's all the change that can be in our community. Of course, we sometimes need things from the outside, but they can always be exchanged for our fruits. Don't fill your head with unnecessary thoughts. The outside world has lost its way and is going the wrong way. Someday it ends in an abyss.}
{227}{}{会有什么变化？收获并与每个人分享——这就是我们社区可能发生的所有变化。当然，我们有时需要来自外部的东西，但它们总是可以用来交换我们的水果。不要让你的脑子里充满不必要的想法。外面的世界迷失了方向，走错了路。总有一天它会在深渊中结束。}
### {228}{}{I'll think about your words.}
{228}{}{我会好好想想你的话。}
### {229}{}{Okay, forget it.}
{229}{}{好吧，算了。}
### {230}{}{You know, the community is going to punish Chris for his cowardice.}
{230}{}{你知道，社区会因为克里斯的懦弱而惩罚他。}
### {231}{}{I tried to persuade the Council to mitigate the punishment, but the law is above me. Obviously, people need to blow off steam, and they decided to use Chris. Perhaps it would be better this way. In any case, do not contradict the majority opinion.}
{231}{}{我试图说服委员会减轻处罚，但法律凌驾于我之上。显然，人们需要发泄情绪，他们决定利用克里斯。也许这样会更好。无论如何，不要与多数人的意见相矛盾。}
### {232}{}{It's interesting to listen to you. Can you tell me anything else?}
{232}{}{听你说话很有趣。你还能告诉我什么吗？}

#Quests
### {250}{}{What else can I do for the Villa?}
{250}{}{我还能为别墅做些什么？}
### {251}{}{Your padre still hasn't returned from slavery. I'm afraid someone will have to go on a journey to find him. And there are no volunteers besides you.}
{251}{}{你的牧师还没有从奴役中回来。恐怕得有人走一趟路才能找到他。除了你没有其他志愿者。}
### {252}{}{What happened to him after coming to Flagstaff?}
{252}{}{他来到弗拉格斯塔夫后发生了什么？}
### {253}{}{He was interrogated for a long time, and then taken to a big city called Phoenix. I don't know anything else.}
{253}{}{他被审问了很长时间，然后被带到一个叫凤凰城的大城市。我什么都不知道。}
### {254}{}{I'll take care of it.}
{254}{}{我会处理的。}
### {255}{}{Ask around other residents. Everyone needs help here - in word or deed.}
{255}{}{询问周围的其他居民。这里的每个人都需要帮助，无论是言语上还是行动上。}
### {256}{}{Okay.}
{256}{}{可以}
### {257}{}{The padre died. Don't wait for him.}
{257}{}{牧师死了。不要等他。}
### {258}{}{(sighs) I can't believe it... He was a strong leader, the whole community was supported by him... Do you know that for sure? Then we should not waste any more time.}
{258}{}{（叹气）我简直不敢相信……他是一位坚强的领袖，整个社区都得到了他的支持。。。你确定吗？那我们就不应该再浪费时间了。}
### {259}{}{What are you talking about?}
{259}{}{你在说什么？}
### {260}{}{Go to the town hall. We need to gather the elders and decide what to do next. You're our leader now. Make decisions thoughtfully... And I need to lie down. Don't worry about me.}
{260}{}{去市政厅。我们需要召集长辈，决定下一步该做什么。你现在是我们的领袖。深思熟虑地做出决定。。。我需要躺下。别担心我。}
### {261}{}{OK, I'll be there.}
{261}{}{好的，我会去的。}
### {262}{}{Have you come across Sancho and Hugo? It looks like they stayed in Flagstaff, if they didn't disappear in an attempt to escape.}
{262}{}{你见过桑乔和雨果吗？如果他们不是为了逃跑而消失的话，看起来他们好像留在了弗拉格斯塔夫。}
### {263}{}{Okay.}
{263}{}{可以}
### {264}{}{Let's chat a little more before we part?}
{264}{}{分手前我们再聊一聊吧？}
### {265}{}{Let's chat a little more?}
{265}{}{我们再聊一聊吧？}

### {270}{}{The council wants to blow up the Flagstaff mines. How do you like this idea?}
{270}{}{委员会想炸毁弗拉格斯塔夫煤矿。你觉得这个主意怎么样？}
### {271}{}{Please take care of yourself. I don't want to let you go on such a dangerous mission. But this mine needs to be stopped. Otherwise, the hand of the slaveholders will reach our village again. And we don't have the strength to fight it.}
{271}{}{请照顾好自己。我不想让你去执行这样危险的任务。但是这个矿需要被阻止。否则，奴隶主的手将再次到达我们的村庄。我们没有力量去对抗它。}
### {272}{}{Clear.}
{272}{}{清楚的}
### {273}{}{The council decided to destroy the Garage City plant. What do you think about it?}
{273}{}{市政委员会决定摧毁车库城的工厂。你觉得怎么样？}
### {274}{}{The scavengers have already shown their corrupt nature. They cannot be trusted, they do not have warm neighborly feelings for us. When they launch the plant, a flood of new labor will flow here. This cannot be allowed if we want to preserve our way of life and peaceful life.}
{274}{}{拾荒者已经显示出他们腐败的本性。他们不能被信任，他们对我们没有睦邻友好的感情。当他们启动工厂时，大量的新劳动力将涌入这里。如果我们想保持我们的生活方式和平静的生活，这是不允许的。}
### {275}{}{Clearly.}
{275}{}{清晰地}
### {276}{}{How do you feel about the alliance with the Rangers?}
{276}{}{你觉得和游骑兵队结盟怎么样？}
### {277}{}{We need allies, and we can't find better rangers. But I am afraid that they will interfere in our internal affairs. This should not be allowed. Let them take food and protect us from robbers. Don't settle for more.}
{277}{}{我们需要盟友，我们找不到更好的护林员了。但我担心他们会干涉我们的内政。这是不应该被允许的。让他们拿走食物，保护我们免受抢劫。不要满足于更多。}
### {278}{}{Your doubts are understandable, Madre.}
{278}{}{你的疑虑是可以理解的，马德尔。}
### {279}{}{How do you feel about the alliance with the Brotherhood of Steel?}
{279}{}{你觉得和钢铁兄弟会结盟怎么样？}
### {280}{}{We don't have a choice, do we? Well, the most important thing is that we stay alive. Saving people in such a situation is our main task.}
{280}{}{我们别无选择，是吗？最重要的是我们要活着。在这种情况下救人是我们的主要任务。}
### {281}{}{Good answer, madre.}
{281}{}{回答不错，马德雷。}
### {282}{}{Luck will definitely not hurt me.}
{282}{}{运气肯定不会伤害我。}
### {283}{}{You have received a permanent bonus to luck.}
{283}{}{你获得了永久性的幸运奖金。}

### {290}{}{How were you treated in the colony?}
{290}{}{你在殖民地受到了怎样的待遇？}
### {291}{}{The jailers forced me to work, but at the same time they treated me with leniency, because I am a woman. What can not be said about men. Those they used sometimes with extreme cruelty. However, they did not want to lose their labor force either, so they were mainly engaged in intimidating slaves.}
{291}{}{狱警强迫我工作，但同时他们对我宽大处理，因为我是个女人。男人有什么不能说的。他们有时极其残忍地使用这些东西。然而，他们也不想失去劳动力，所以他们主要从事恐吓奴隶的活动。}
### {292}{}{And ordinary citizens?}
{292}{}{普通公民呢？}
### {293}{}{The colonists tried not to talk to me. I think they themselves are not in a particularly free position because of the large taxes. It is not surprising that even the family pendant, inherited from my grandmother, was taken away from me. Although it does not represent any value to the colonists.}
{293}{}{殖民者尽量不和我说话。我认为他们自己并没有处于特别自由的地位，因为税收太高。即使是从我祖母那里继承的家族吊坠也被拿走了，这并不奇怪。尽管它对殖民者来说没有任何价值。}
### {294}{}{Why would someone need your pendant?}
{294}{}{为什么有人需要你的吊坠？}
### {295}{}{Well, he said he would get "good caps" from the bartender for it. I doubt that he helped out at least one and a half caps.}
{295}{}{嗯，他说他会从酒保那里得到“好帽子”。我怀疑他至少帮了一顶半帽子。}
### {296}{}{Sorry to hear that. I hope that jailer got what he deserved.}
{296}{}{很抱歉听到这个消息。我希望那个狱卒得到他应得的。}
### {297}{}{It's just a family pendant. You can forget about him.}
{297}{}{这只是一个家庭挂件。你可以忘记他。}
### {298}{}{Here's your pendant.}
{298}{}{这是你的吊坠。}
### {299}{}{Ah, thank you! Really, it wasn't worth the risk. And yet you are doing well to preserve our family history. Put on this pendant. It's yours now. May he bring you good luck on the way.}
{299}{}{啊，谢谢！真的，这不值得冒险。然而，你们在保护我们的家族历史方面做得很好。戴上这个吊坠。现在是你的了。愿他在路上给你带来好运。}
