### {100}{}{You see a ghoul.}
{100}{}{你看到一个食尸鬼。}
### {101}{}{There's a ghoul in front of you. He's wearing a collar with a built-in shocker.}
{101}{}{你面前有个食尸鬼。他戴着一个内置减震器的项圈。}
### {102}{}{Are you letting us go? Thank god! There are still good people on this earth.}
{102}{}{你放我们走了吗？感谢上帝！这个地球上仍然有好人。}

### {110}{}{They have captured us and are forcing us to collect these things.}
{110}{}{他们抓住了我们，并强迫我们收集这些东西。}
### {111}{}{Don't hit us, man. We are trying our best.}
{111}{}{别打我们，伙计。我们正在尽力。}
### {112}{}{One of us is distraught. Better not get caught in his eyes.}
{112}{}{我们中的一个人悲痛欲绝。最好不要被他的眼睛夹住。}
### {113}{}{These scavengers don't even know what these things are for.}
{113}{}{这些拾荒者甚至不知道这些东西是干什么的。}

### {120}{}{They make us work.}
{120}{}{他们让我们工作。}
### {121}{}{Did they grab you too? Bad luck, friend.}
{121}{}{他们也抓你了吗？运气不好，朋友。}
### {122}{}{One of us is distraught. Better not get in his way.}
{122}{}{我们中的一个人悲痛欲绝。最好不要妨碍他。}
### {123}{}{These scavengers don't even know what these things are for.}
{123}{}{这些拾荒者甚至不知道这些东西是干什么的。}
