### {100}{}{In front of you is a blind ghoul.}
{100}{}{在你面前是一个盲目的食尸鬼。}
### {101}{}{You see one of the ghouls sitting in a wheelchair.}
{101}{}{你看到一个食尸鬼坐在轮椅上。}

### {110}{}{Who are you? Identify yourself.}
{110}{}{你是谁？表明自己的身份。}
### {111}{}{Let me touch your face.}
{111}{}{让我摸摸你的脸。}
### {112}{}{So are you normal? Don't touch!}
{112}{}{你正常吗？不要碰！}
### {113}{}{Please don't hurt me!}
{113}{}{请不要伤害我！}
### {114}{}{Leave the Glow alone!}
{114}{}{别管辉光！}

### {120}{}{Who are you? Identify yourself.}
{120}{}{你是谁？表明自己的身份。}
### {121}{}{I know all the dead people in this hell. But I don't know you.}
{121}{}{我认识这个地狱里所有的死人。但我不了解你。}
### {122}{}{You're a ghoul. And I'm a ghoul. Why haven't we met yet?}
{122}{}{你是个食尸鬼。我是个食尸鬼。为什么我们还没见过面？}
### {123}{}{I have been in darkness for eternity.}
{123}{}{我已经在黑暗中度过了永恒。}
### {124}{}{Tell me, what does the Glow look like?}
{124}{}{告诉我，Glow是什么样子的？}
