### {100}{}{In front of you is a ghoul.}
{100}{}{在你面前是一个食尸鬼。}
### {101}{}{You see an ordinary ghoul.}
{101}{}{你看到一个普通的食尸鬼。}
### {102}{}{Z-z-z...}
{102}{}{Z-Z-Z。。。}

### {110}{}{Oh...}
{110}{}{哦}
### {111}{}{Ah...}
{111}{}{啊。。。}
### {112}{}{It hurts...}
{112}{}{很疼。。。}
### {113}{}{It still hurts...}
{113}{}{它仍然很痛。。。}

### {200}{}{Hey, man, help me! I just got caught in a landslide a little bit and broke a couple of bones. These old houses are no good at all...}
{200}{}{嘿，伙计，帮帮我！我刚刚遇到山体滑坡，摔断了几块骨头。这些老房子一点也不好。。。}
### {201}{}{Hey, buddy, help me! I just got caught in a landslide a little bit and broke a couple of bones. These old houses are no good at all...}
{201}{}{嘿，伙计，帮帮我！我刚刚遇到山体滑坡，摔断了几块骨头。这些老房子一点也不好。。。}
### {202}{}{Oh my God! Don't move, I'll help you now!}
{202}{}{天啊！别动，我现在就帮你！}
### {203}{}{Daydreaming. I don't even want to dirty my hands about such a freak.}
{203}{}{白日梦。我甚至不想因为这样一个怪胎而弄脏我的手。}
### {204}{}{I'm not going to help you. I'll just take your stuff and leave you to die. And by the way ? no one will hear you here anymore.}
{204}{}{我不会帮你的。我会拿走你的东西，让你去死。顺便说一下? 在这里没人会再听到你说话了。}
### {205}{}{Oh no! No! No...}
{205}{}{哦，不！不不}
### {206}{}{See you in the next world. Maybe.}
{206}{}{下个世界见。大概}
### {207}{}{I'm kidding, man! Wait a bit, I'll cure you soon.}
{207}{}{我在开玩笑，伙计！等一下，我很快就会治好你的。}
### {208}{}{I really didn't expect that a person would help me, and even in the heart of radioactive ruins. Thank you, friend.}
{208}{}{我真的没想到有人会帮助我，甚至在放射性废墟的中心。谢谢你，朋友。}
### {209}{}{You're welcome. By the way, what were you doing here?}
{209}{}{不客气。顺便问一下，你在这里干什么？}
### {210}{}{Don't forget to tell the other ghouls about my feat. How did you end up here anyway?}
{210}{}{别忘了把我的壮举告诉其他食尸鬼。你是怎么来到这里的？}
### {211}{}{Explored the ruins, obviously. But the floors here turned out to be quite flimsy. Tread carefully, friend. Oh, and that's not the main danger. I saw a creature from the window. Huge, scary, with claws like sabers. Don't fall into his clutches. And now ? good luck. I'll try to hobble to the nearest camp.}
{211}{}{显然是在废墟上探险。但事实证明，这里的地板很脆弱。小心踩，朋友。哦，那不是主要的危险。我从窗户看到一个生物。巨大，可怕，爪子像军刀。不要落入他的魔掌。现在? 祝你好运我会尽量一瘸一拐地去最近的营地。}
### {212}{}{Thanks for the warning. Bye.}
{212}{}{谢谢你的警告。再见}
### {213}{}{I don't remember your face. We didn't cross paths in the Necropolis, did we? It's a strange thing. But in any case, thank you, friend. I couldn't even kick down the front door without you.}
{213}{}{我不记得你的脸了。我们没有在墓地里穿过小路，是吗？这是一件奇怪的事情。但无论如何，谢谢你，朋友。没有你，我甚至不能踢开前门。}
### {1213}{}{I don't remember your face. We didn't cross paths in the Necropolis, did we? It's a strange thing. But in any case ? thank you, girlfriend. I couldn't even kick down the front door without you.}
{1213}{}{我不记得你的脸了。我们没有在墓地里穿过小路，是吗？这是一件奇怪的事情。但无论如何? 谢谢你，女朋友。没有你，我甚至不能踢开前门。}
