### {100}{}{You see Rupert.}
{100}{}{你看到鲁伯特了。}
### {101}{}{Here is a ghoul in a pre-war suit.}
{101}{}{这是一个穿着战前西装的食尸鬼。}
### {102}{}{You see a ghoul.}
{102}{}{你看到一个食尸鬼。}
### {103}{}{If it wasn't for De-Santi, we would have been reunited a long time ago.}
{103}{}{如果不是德桑蒂，我们早就团聚了。}
### {104}{}{Hey, hello. You look pretty good for a dead guy.}
{104}{}{嘿，你好。你看起来像个死人。}
### {105}{}{Phew! I can't get used to your nasty smooth faces.}
{105}{}{呜呜！我不习惯你那讨厌的光滑的脸。}
### {106}{}{Oh-h!}
{106}{}{哦！}
### {107}{}{You know how to break off pleasure.}
{107}{}{你知道如何打破快乐。}

### {200}{}{Hey, hello. You look good for a dead guy.}
{200}{}{嘿，你好。你看起来像个死人。}
### {201}{}{I'm not dead.}
{201}{}{我没有死。}
### {202}{}{Well, then you're lucky. I'm lucky too. More points every time!}
{202}{}{那你就幸运了。我也很幸运。每一次都获得更多积分！}
### {203}{}{Well, that's...}
{203}{}{嗯，那是。。。}
### {204}{}{Oh, if only I had always been so fortified! I thought that my old age would be quite sad, but in this hotel I feel young like never before! And it's so much fun!}
{204}{}{噢，要是我一直这么坚强就好了！我原以为我的晚年会很难过，但在这家酒店里，我感到前所未有的年轻！这太有趣了！}
### {205}{}{I actually...}
{205}{}{实际上我。。。}
### {206}{}{Glad that...}
{206}{}{很高兴。。。}
### {207}{}{And now I'm sorry, Daddy needs a pair of brand new shoes. Eh, there was no such thing! I bet on red!}
{207}{}{现在我很抱歉，爸爸需要一双崭新的鞋子。啊，根本就没有！我赌红色！}
### {208}{}{I won't interfere.}
{208}{}{我不会干涉的。}
### {209}{}{Look, old man, don't lose your soul.}
{209}{}{听着，老人，不要失去你的灵魂。}

### {220}{}{Don't mumble under your arm, my card is ready!}
{220}{}{别在你腋下喃喃自语，我的卡片已经准备好了！}
### {221}{}{Nevermind.}
{221}{}{永远不会。}
### {222}{}{Tell me, old man, what's your name?}
{222}{}{告诉我，老人，你叫什么名字？}
### {223}{}{My name is?The-Luckiest-Son-of-a-Bitch-in-the-World!}
{223}{}{我的名字是?幸运儿——世界上的婊子养的！}
### {224}{}{I'm serious.}
{224}{}{我是认真的。}
### {225}{}{Listen, don't be such a bore. I'm not going to be friends with you anyway. Call me old man if you want. I don't care.}
{225}{}{听着，别这么无聊。我无论如何都不会和你做朋友。如果你愿意，叫我老人吧。我不在乎。}
### {226}{}{Okay. Whatever you say, old man.}
{226}{}{可以不管你说什么，老人。}
### {227}{}{Your name is Rupert, isn't it?}
{227}{}{你的名字叫鲁伯特，不是吗？}
### {228}{}{Cough-cough-cough! I don't know who you're talking about. This is the first time I've heard this name.}
{228}{}{咳嗽咳嗽！我不知道你在说谁。这是我第一次听到这个名字。}
### {229}{}{Maybe I should ask the administrator? Or peek in the visitors' log?}
{229}{}{也许我应该问管理员？或者偷看访客日志？}
### {230}{}{Really? Well, then I'm sorry to bother you.}
{230}{}{真正地那我很抱歉打扰你。}
### {231}{}{What do you want in the end? Who sent you?}
{231}{}{你到底想要什么？谁派你来的？}
### {232}{}{Miss Judy. She's looking for her missing husband. And it looks like he's burning his entire fortune in secret from her.}
{232}{}{朱迪小姐。她正在寻找她失踪的丈夫。看起来他正在秘密地向她烧光他的全部财产。}
### {233}{}{(sigh) Listen, buddy. Do you think I would hang out here if I wanted to reunite with Judy?}
{233}{}{（叹气）听着，伙计。如果我想和朱迪重聚，你认为我会在这里闲逛吗？}
### {234}{}{I don't really care.}
{234}{}{我真的不在乎。}
### {235}{}{Then what is the reason for this behavior?}
{235}{}{那么这种行为的原因是什么呢？}
### {236}{}{You're a man, you have to understand what it's like when your wife nags you for 80 years in a row!}
{236}{}{你是一个男人，你必须明白当你的妻子连续80年唠叨你时是什么感觉！}
### {1236}{}{You're a woman, you don't understand what it's like when your wife nags you for 80 years in a row!}
{1236}{}{你是个女人，你不明白当你的妻子连续80年唠叨你时是什么感觉！}
### {237}{}{[Listen]}
{237}{}{[听]}
### {238}{}{I feel good here. I do what I want ? I drink, watch movies, play roulette! You know, Judy never let me play that damn roulette. And that's what I've always wanted.}
{238}{}{我在这里感觉很好。我想做什么就做什么? 我喝酒，看电影，玩轮盘赌！你知道，朱迪从来没让我玩那该死的轮盘赌。这就是我一直想要的。}
### {239}{}{You know it's not a real game, right?}
{239}{}{你知道这不是一场真正的比赛，对吧？}
### {240}{}{Well, yes. But it doesn't matter ? it's important that I finally started playing it!}
{240}{}{嗯，是的。但这并不重要? 重要的是我终于开始演奏了！}
### {241}{}{She won't be happy if she finds out that you were hiding from her while she was looking for you.}
{241}{}{如果她发现你在她找你的时候躲着她，她不会高兴的。}
### {242}{}{I know. Listen, tell her I'm dead, huh? It's not difficult for you, but I can live for some time without her total supervision.}
{242}{}{我知道。听着，告诉她我死了，是吗？这对你来说并不难，但我可以在没有她的完全监督下生活一段时间。}
### {243}{}{Okay. Why not?}
{243}{}{可以为什么不呢？}
### {244}{}{Will you really do that? Oh, I'm so lucky today! So lucky!}
{244}{}{你真的会那样做吗？哦，我今天真幸运！太幸运了！}
### {245}{}{Okay, come on.}
{245}{}{好吧，来吧。}
### {246}{}{No. You have to meet her. She is the person closest to you. It is wrong to hide from her at the end of life.}
{246}{}{不，你得见见她。她是你最亲近的人。在生命的尽头躲着她是不对的。}
### {247}{}{Well, why are you breaking my buzz? (sigh) La adno. Your truth. She'll find out the truth from you anyway.}
{247}{}{你为什么打断我的话？（叹气）拉阿德诺。你的真相。不管怎样，她会从你那里知道真相的。}
### {248}{}{Yes. Go and talk to her. She lives in San Ysidro.}
{248}{}{对去和她谈谈。她住在圣伊西德罗。}

### {250}{}{As you asked, I told her you were dead. And do you know what happened? Her heart couldn't stand it and burst!}
{250}{}{正如你所问，我告诉她你已经死了。你知道发生了什么吗？她的心受不了了，爆裂了！}
### {1250}{}{As you asked, I told her you were dead. And do you know what happened? Her heart couldn't stand it and burst!}
{1250}{}{正如你所问，我告诉她你已经死了。你知道发生了什么吗？她的心受不了了，爆裂了！}
### {251}{}{How... it can't be... I didn't expect this... oh... ugh...}
{251}{}{怎样不可能…我没想到。。。哦呃。。。}
### {252}{}{Just don't tell me that you're going to throw away your skates now.}
{252}{}{只是别告诉我你现在要扔掉你的溜冰鞋。}
