### {102}{}{Well, what else?}
{102}{}{还有什么？}
### {103}{}{I'll kill everyone from the Brotherhood of Steel I can find!}
{103}{}{我会杀死所有我能找到的钢铁兄弟会成员！}
### {104}{}{I hate the Brotherhood! I hate it!}
{104}{}{我讨厌兄弟会！我讨厌它！}

### {110}{}{Hey, fraternal dog, drop the gun and come out!}
{110}{}{嘿，兄弟狗，放下枪出来！}
### {111}{}{I won't hurt you. I just want to talk.}
{111}{}{我不会伤害你的。我只是想谈谈。}
### {112}{}{Say everything that boiled over.}
{112}{}{把所有沸腾的都说出来。}
### {113}{}{Do you know how many of our Lost Hills brats have killed?}
{113}{}{你知道我们的Lost Hills小子杀了多少人吗？}
### {114}{}{You took our house away from us. You have taken God away from us.}
{114}{}{你夺走了我们的房子。你夺走了上帝。}
### {115}{}{Do you think we can get along after this?}
{115}{}{你认为这之后我们能相处吗？}
### {116}{}{Oh, I'm SO angry. But I'll do you a favor?I'll kill you quickly. You won't feel anything.}
{116}{}{哦，我太生气了。但我会帮你一个忙?我会很快杀了你。你不会有任何感觉。}
### {117}{}{Agreed?}
{117}{}{同意吗？}
### {118}{}{Why are you suffering? Why are you resisting? I will put you out of your misery.}
{118}{}{你为什么痛苦？你为什么抗拒？我会让你摆脱痛苦。}
### {119}{}{God was behind us. And behind you are the generals. Pitiful people, how have you fallen!}
{119}{}{上帝在我们身后，将军们在你们身后。可怜的人，你怎么堕落了！}

### {200}{}{Hey, dead guy, be careful. There's a brat from the Brotherhood of Steel skerking around here somewhere. Look, don't be under his bullets.}
{200}{}{嘿，死人，小心。有一个来自钢铁兄弟会的小淘气在这附近游荡。听着，别被他的子弹打穿了。}
### {201}{}{Ah, I see. Then I'll hurry away before it gets too hot in here.}
{201}{}{啊，我明白了。那我就赶紧走，免得这里太热。}
### {202}{}{Don't you dare harass the Brotherhood people! I won't let you do that!}
{202}{}{你不敢骚扰兄弟会的人！我不会让你那样做的！}
### {203}{}{Hey, I just saw him run off to the piers! While you were talking to the air here, he was already gone.}
{203}{}{嘿，我刚才看到他跑到码头上去了！当你在这里对着空气讲话时，他已经走了。}
### {204}{}{Which... Wow, I'm going to catch up with him now! You won't leave!}
{204}{}{哪一个哇，我现在要赶上他了！你不会离开的！}
### {205}{}{Hurry up, bully!}
{205}{}{快，恶霸！}
### {206}{}{Haha, you're a dumbass! It was easier to fool you than a child! What's going on, you fool?}
{206}{}{哈哈，你真傻！骗你比骗孩子容易！怎么了，你这个傻瓜？}
### {207}{}{A bunch? And you're here? Hey, did you take a man as a slave? Younger-ec. And here I am trying to get the dog out of the Brotherhood of Steel. He hid in a cafe. Will you help me get rid of him?}
{207}{}{一堆？你在这里？嘿，你把一个人当奴隶了吗？杨格。在这里，我正试图把狗从钢铁兄弟会中解救出来。他躲在一家咖啡馆里。你能帮我把他赶走吗？}
### {208}{}{Heap, let's get out of here? It's none of our business.}
{208}{}{希普，我们离开这里？这不关我们的事。}
### {209}{}{Heap, tell this klutz that the war is over. Stop feuding. Leave the man alone.}
{209}{}{希普，告诉这个笨蛋战争结束了。停止争执。别管那个人。}
### {210}{}{A bunch and a person have become partners? I've never heard of it. Maybe there really is a truce? Okay, a bunch, I'll believe you.}
{210}{}{一群人和一个人成了伙伴？我从来没有听说过。也许真的休战了？好吧，一群，我相信你。}
### {211}{}{That's good. Go your own way.}
{211}{}{这很好。走你自己的路。}
### {212}{}{A-a-a! Die, stupid people!}
{212}{}{啊啊啊！死吧，愚蠢的人！}
### {213}{}{Not before you, stinky!}
{213}{}{在你面前没有，臭！}
### {214}{}{Wait, let's talk!}
{214}{}{等等，我们谈谈！}
### {215}{}{Wait! You and I have nothing to fight for. I don't want to hurt you.}
{215}{}{等待你和我没有什么可争的。我不想伤害你。}
### {216}{}{I still won't forgive what people have done to us!}
{216}{}{我仍然不会原谅人们对我们所做的一切！}
### {217}{}{It's a pity that you understand in a good way...}
{217}{}{很遗憾你能以一种好的方式理解。。。}
### {218}{}{You shouldn't be so...}
{218}{}{你不应该这么。。。}
### {219}{}{The ghouls won't be happy with you. After all, they are building a city for everyone. Humans and mutants can live together in the Glow of the Day. Don't you really want the long-awaited peace?}
{219}{}{食尸鬼和你在一起不会高兴的。毕竟，他们正在为每个人建设一座城市。人类和变种人可以一起生活在光辉的一天。你真的不想要期待已久的和平吗？}
### {220}{}{Ghouls are careless! Someday they will pay. People will betray them!}
{220}{}{食尸鬼很粗心！总有一天他们会付钱的。人们会背叛他们的！}
### {221}{}{And you protect them. Don't let people twist ghouls around your finger. After all, there will always be more people. Fighting alone can't fix this.}
{221}{}{你保护他们。不要让别人把食尸鬼缠在你的手指上。毕竟，总会有更多的人。单打独斗解决不了这个问题。}
### {222}{}{You say great. I didn't think about it. Go to the city or something? Offer yourself to the ghouls as a guard? Why, that's a good idea! I won't let the ghouls offend, no!}
{222}{}{你说很棒。我没想过。去城里还是什么？把自己交给食尸鬼当警卫？为什么，这是个好主意！我不会让食尸鬼冒犯的，不！}
### {223}{}{That's good. See? You can always negotiate.}
{223}{}{这很好。看见你总是可以谈判的。}
### {224}{}{I'll have to agree with you here. So, shall we continue the fight, dumbass?}
{224}{}{我不得不同意你的看法。那么，我们继续战斗吧，蠢蛋？}
