### {100}{}{This is a permanent hotel$.}
{100}{}{这是一家永久性酒店。}
### {101}{}{you see an ordinary drone in a housecoat.}
{101}{}{你看到一架普通的无人机穿着一件外套。}
### {102}{}{koch, how good! No heat, no stink, no flies!}
{102}{}{koch，太棒了！没有热，没有臭，没有苍蝇！}
### {103}{}{Where are there so many flies? It's because of the heat. "the air conditioner just doesn't work here, can you imagine?}
{103}{}{哪里有这么多苍蝇？这是因为热。“这里的空调根本不工作，你能想象吗？}
