### {200}{}{Enter the command.}
{200}{}{输入命令。}
### {201}{}{End session.}
{201}{}{结束会话。}
### {202}{}{Back.}
{202}{}{返回}
### {203}{}{Next.}
{203}{}{下一个}
### {204}{}{This system is too complicated for you.}
{204}{}{这个系统对你来说太复杂了。}
### {205}{}{It would be nice to find the instructions... or an instructor.}
{205}{}{如果能找到说明书就太好了。。。或教练。}
### {206}{}{It won't help here. Knowledge is needed here.}
{206}{}{这对这里没有帮助。这里需要知识。}
### {207}{}{Now you know what to do.}
{207}{}{现在你知道该怎么办了。}
### {208}{}{Hey, it's not that hard!}
{208}{}{嘿，没那么难！}
### {209}{}{This technology is too complicated. Here you need to study everything thoroughly.}
{209}{}{这项技术太复杂了。在这里，你需要彻底研究每一件事。}

### {210}{}{Checking the system status.}
{210}{}{检查系统状态。}
### {211}{}{The condition of the first turbine.}
{211}{}{第一台涡轮机的状况。}
### {212}{}{Turbine 1: no signal.}
{212}{}{涡轮机1：无信号。}
### {213}{}{Turbine 1: active.}
{213}{}{涡轮机1：激活。}
### {214}{}{Condition of the second turbine.}
{214}{}{第二台涡轮机的状况。}
### {215}{}{Turbine 2: no signal.}
{215}{}{涡轮机2：无信号。}
### {216}{}{Turbine 2: active.}
{216}{}{涡轮机2：激活。}
### {217}{}{Checking the substation.}
{217}{}{检查变电站。}
### {218}{}{Substation: not responding. }
{218}{}{变电站：没有响应。}
### {219}{}{Substation: working. }
{219}{}{变电站：工作。}
### {220}{}{Direct energy to the substation.}
{220}{}{将能量直接输送到变电站。}
### {221}{}{Completed.}
{221}{}{已完成。}
### {222}{}{The substation is not responding.}
{222}{}{变电站没有响应。}
### {223}{}{Turn on the lights in the engine room.}
{223}{}{打开机舱的灯。}
### {224}{}{Turn off the lights in the engine room.}
{224}{}{关掉机舱的灯。}
### {225}{}{Turn on the lights in the control center.}
{225}{}{打开控制中心的灯。}
### {226}{}{Turn off the lights in the control center.}
{226}{}{关闭控制中心的灯。}
### {227}{}{Open the door to the warehouse.}
{227}{}{打开仓库的门。}
