### {100}{}{A pick-up point for departure to Sonora has been announced here.}
{100}{}{这里已经宣布了前往索诺拉的接送点。}
### {101}{}{From here you can return to the wasteland of Sonora.}
{101}{}{从这里你可以回到索诺拉的荒原。}

### {110}{}{The collection point is here.}
{110}{}{收集点在这里。}
### {111}{}{[Wait for the guide and return to the Sonoran wasteland.]}
{111}{}{[等待导游，然后返回索诺兰荒原。]}
### {112}{}{[To return to the Sonoran wasteland alone.]}
{112}{}{[独自回到索诺兰荒原。]}
### {113}{}{[Stay in the Glow of the Day. Sonora can wait.]}
{113}{}{[保持阳光灿烂。索诺拉可以等待。]}
### {114}{}{Are you sure? You won't be coming back.}
{114}{}{你确定吗？你不会回来了。}
### {115}{}{Yes, I want to go back.}
{115}{}{是的，我想回去。}
### {116}{}{No, I'm staying in the Glow.}
{116}{}{不，我要呆在发光区。}
### {117}{}{You can carry no more than 100 pounds of cargo with you.}
{117}{}{你可以随身携带不超过100磅的货物。}
### {118}{}{[Go to the Dayglow on your own.]}
{118}{}{[你自己去日光浴吧。]}
### {119}{}{[Stay in the Sonoran wasteland.]}
{119}{}{[留在索诺兰荒原。]}
