### {110}{}{This howitzer is damaged.}
{110}{}{这门榴弹炮损坏了。}
### {111}{}{This howitzer can hypothetically fire. At least once.}
{111}{}{这种榴弹炮可以假设开火。至少一次。}
### {112}{}{The howitzer makes a shot, after which it finally falls apart.}
{112}{}{榴弹炮发射了一枪，之后它终于散架了。}
### {113}{}{This howitzer is completely out of order.}
{113}{}{这门榴弹炮完全失灵了。}
### {114}{}{The howitzer is loaded.}
{114}{}{榴弹炮上膛了。}
### {115}{}{The howitzer has been restored.}
{115}{}{榴弹炮已经修复。}
