### {100}{}{These doors cannot be locked.}
{100}{}{这些门不能锁。}
### {101}{}{The monorail line is de-energized. The tram won't go anywhere.}
{101}{}{单轨线路断电。电车哪儿也去不了。}
### {102}{}{For some reason, the tram does not go by itself. Something must have broken.}
{102}{}{由于某种原因，电车不能自己开。一定有什么东西坏了。}
### {103}{}{After almost a hundred years, the monorail has started working again!}
{103}{}{将近一百年后，单轨电车又开始工作了！}
### {104}{}{The monorail is working.}
{104}{}{单轨电车正在运行。}

### {110}{}{"You are welcomed by the San Diego Metro Rapid Transit network. Sit back and wait for departure."}
{110}{}{“圣地亚哥地铁快速交通网络欢迎您。坐下来等待出发。”}
### {111}{}{[Leave the tram]}
{111}{}{[离开电车]}
### {112}{}{[Get off at San Isidro Station]}
{112}{}{[在圣伊西德罗车站下车]}
### {113}{}{[Get off at Chula Vista Center Station]}
{113}{}{[在Chula Vista中心站下车]}
### {114}{}{[Get off at Broadway Station]}
{114}{}{[在百老汇车站下车]}
### {115}{}{[Get off at the Old Town station]}
{115}{}{[在老城区车站下车]}
