### {110}{}{In front of you is a printing press. ?once he printed newspapers and magazines, but now he is inactive.}
{110}{}{你面前是一台印刷机。?他曾经印刷报纸和杂志，但现在不活跃了。}
### {111}{}{in front of you is a printing press. he won't be able to print anything anymore because someone pulled an important part out of him.}
{111}{}{你面前是一台印刷机。他将无法再打印任何东西，因为有人从他身上提取了一个重要部分。}
### {112}{}{did he remove the printed circuit board.}
{112}{}{他把印刷电路板拆了吗。}
### {113}{}{"there's nothing valuable here anymore.}
{113}{}{“这里再也没有什么值钱的东西了。}
### {114}{}{ at the moment, this printing press has not presentedIt's of no interest to you.}
{114}{}{目前，这台印刷机还没有出现，你对此不感兴趣。}
