### {100}{}{There is a rusty door in front of you.}
{100}{}{你面前有一扇生锈的门。}
### {101}{}{You see a very rusty warehouse door.}
{101}{}{你看到一扇锈迹斑斑的仓库门。}
### {102}{}{This door is very rusty.}
{102}{}{这扇门锈得很厉害。}
### {103}{}{Does not lend itself.}
{103}{}{不适合自己。}
### {104}{}{The door is rusted. Brute force is needed here.}
{104}{}{门生锈了。这里需要残酷的力量。}
### {105}{}{The door could not resist your efforts.}
{105}{}{门挡不住你的努力。}
### {106}{}{A little rust flew off the steel coating, but the door resisted.}
{106}{}{一点铁锈从钢涂层上飞了下来，但门顶住了。}
### {107}{}{Uv-f!}
{107}{}{Uv-f！}
