### {100}{}{There's a patrolman in front of you.}
{100}{}{你面前有个巡警。}
### {101}{}{Here is a private in standard army armor.}
{101}{}{这是一名身穿标准陆军盔甲的二等兵。}

### {110}{}{El intruso!}
{110}{}{El introso！}
### {111}{}{?veo al intruso!}
{111}{}{?你好！}
### {112}{}{Eres gringo, yNo?}
{112}{}{Eres gringo，不是吗？}
### {113}{}{?bienvenido a M?iso!}
{113}{}{?bienvenido a M?iso！}
### {114}{}{?qu? se te perdi? aqui?}
{114}{}{?qu? se te perdi? aqi？}
### {115}{}{?vienes del norte?}
{115}{}{?北欧？}
### {116}{}{Esto es Nuevo Mexico.}
{116}{}{墨西哥新海岸。}
### {117}{}{YEsta es nuestra tierra!}
{117}{}{耶斯塔是新的蒂耶拉！}
### {118}{}{YGuarda tus armas!}
{118}{}{YGuarda tus armas！}
### {119}{}{No nos caen bien los gringos.}
{119}{}{没有外国人。}
### {120}{}{qui?n eres?}
{120}{}{qui?n eres？}

### {210}{}{Violator!}
{210}{}{违反者！}
### {211}{}{I see the intruder!}
{211}{}{我看到入侵者了！}
### {212}{}{Are you an American?}
{212}{}{你是美国人吗？}
### {213}{}{Welcome to Mexico.}
{213}{}{欢迎来到墨西哥。}
### {214}{}{What are you looking for?}
{214}{}{你在找什么？}
### {215}{}{Did you come from the north?}
{215}{}{你是从北方来的吗？}
### {216}{}{This is the New Mexico.}
{216}{}{这是新墨西哥州。}
### {217}{}{This is our land!}
{217}{}{这是我们的土地！}
### {218}{}{Put away your weapon.}
{218}{}{收起你的武器。}
### {219}{}{We don't need outsiders here.}
{219}{}{我们这里不需要外人。}
### {220}{}{Who else are you?}
{220}{}{你还有谁？}
