### {102}{}{It doesn't make sense.}
{102}{}{这没有道理。}
### {103}{}{This can be set on fire to illuminate the area.}
{103}{}{可以将其点燃以照亮该区域。}

### {110}{}{You lit the lamp. Its dim light barely penetrates the darkness of the cellars.}
{110}{}{你点灯了。昏暗的光线几乎无法穿透地窖的黑暗。}
### {111}{}{This lamp contains a little oil. It remains only to set it on fire to light up the cellar.}
{111}{}{这盏灯里有一点油。它留下来只是为了点燃地窖。}
### {112}{}{This lamp dimly illuminates the cellar.}
{112}{}{这盏灯昏暗地照亮了地窖。}
### {113}{}{This lamp has run out of oil.}
{113}{}{这盏灯没油了。}
### {114}{}{Fire and smoke scare the local coyotes.}
{114}{}{火灾和烟雾使当地的郊狼感到害怕。}
