### {101}{}{It's a newspaper vending machine. With all his appearance, he reminds of a bygone era.}
{101}{}{这是一台报纸自动售货机。他的外表让人想起了过去的时代。}
### {102}{}{The newspaper machine has already been opened.}
{102}{}{报机已经打开了。}
### {103}{}{The lid of the newspaper machine is tightly closed and does not give in.}
{103}{}{报机的盖子关得很紧，没有屈服。}
### {104}{}{The lock does not give in, it is stuck due to dirt and rust.}
{104}{}{这把锁不屈服，它被泥土和铁锈卡住了。}
### {105}{}{You have opened the lid of the newspaper machine. Now everything that lies here belongs to you.}
{105}{}{你打开了报机的盖子。现在这里的一切都属于你。}
### {106}{}{I'm pretty damn lucky today}
{106}{}{我今天真幸运}
